### PR TITLE
Add NeyroAI (NAI) (ERC20)

### PR DESCRIPTION
**Pull request by robertBrown377**
Adding info for ERC20 token 'NeyroAI (NAI)'.

PR created by <a href="https://assets.trustwallet.com">TW Assets Management</a>

### CODE REVIEW

**Comment by robertBrown377** [comment]
Audit: https://dessertswap.finance/audits/NeyroAI-ETH-Audit-20120052.pdf

**Comment by cryptomanz1** [comment]
• What is the purpose of this token? How will it benefit Trust Wallet users?
 • How is the token being distributed? Are you conducting an airdrop?
 • Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?
 • Is the token listed on a centralized/decentralized exchange?

**Comment by bioter** [comment]
> • What is the purpose of this token? How will it benefit Trust Wallet users? 
• How is the token being distributed? Are you conducting an airdrop? 
• Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale? 
• Is the token listed on a centralized/decentralized exchange?

1. The NeyroAI token supports the AI ecosystem by providing access to platforms and tools, and attracts investment in innovative projects. It gives Trust Wallet users access to new features and rewards, supports integrated projects, and makes token management convenient through community trust.
2. The NeyroAI token will not be distributed via airdrop. It will be available through sales, partnerships, email subscription and referral system.
3. No, the NeyroAI tokens were not sold through an Initial Coin Offering (ICO) or a token presale.
4. Yes. Uniswap v3, Uniswap v2

**Comment by bioter** [comment]
1. The NeyroAI token supports the AI ecosystem by providing access to platforms and tools, and attracts investment in innovative projects. It gives Trust Wallet users access to new features and rewards, supports integrated projects, and makes token management convenient through community trust.
2. NeyroAI is not distributed via airdrop. It will be available through sales, partnerships, email subscription and referral system.
3. No, the NeyroAI tokens were not sold through an Initial Coin Offering (ICO) or a token presale.
4. Yes, on UNISWAP V2, UNISWAP V3.

**Comment by robertBrown377** [comment]
> • What is the purpose of this token? How will it benefit Trust Wallet users? 
• How is the token being distributed? Are you conducting an airdrop?
 • Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale? 
 • Is the token listed on a centralized/decentralized exchange?
1. The NeyroAI token supports the AI ecosystem by providing access to platforms and tools, and attracts investment in innovative projects. It gives Trust Wallet users access to new features and rewards, supports integrated projects, and makes token management convenient through community trust.
2. NeyroAI token will not be distributed via airdrop. It will be available through sales, partnerships, email subscription and referral system.
3. No, the NeyroAI tokens were not sold through an Initial Coin Offering (ICO) or a token presale
4. Yes, it is on uniswap v3, uniswap v2

**Pull request merged**
