### PR TITLE
GamerGold (GG) PNG Logo & PR Project Details

### PR DESCRIPTION
**Pull request by DEXExchange**
GamerGold (GG) PNG Logo & PR Project Details

Name: GamerGold
Abbreviation: GG
Protocol: ERC20
Decimal Precision: 18
Contract Address: 0x11A78577c7c84F8bC6164d848080f1973531c288
Etherscan Contract Address Link: https://etherscan.io/address/0x11A78577c7c84F8bC6164d848080f1973531c288#code

Project: Matrix Gaming IT
About Project Brief: Matrix Gaming IT ecosystem and tournaments engine powers you to Create & Grow A Pro Gaming Community! Create & manage pro teams, create & compete in custom tournaments to win staked GamerGold (GG).

Project website: https://MatrixGamingIT.com
Project Whitepaper: https://matrixgamingit.com/matrix-gaming-it-whitepaper/
Project Contact: support@dexexchange.us or matrixitsupport@matrixchainecosystem.appold (GG) PNG Logo

### CODE REVIEW

**Comment by DEXExchange** [comment]
BNB Payment Made to bnb1tqq9llyr3dyjd559dha6z5r5etk3qfwk07m098 with memo: 4023.

**Comment by catenocrypt** [comment]
As per our policy, brand new tokens are not included, there is a minimum requirement of 500 holder addresses and 1000 transactions, in order to filter out scam tokens.
See the criteria at (mentioned in the first message by the bot): https://community.trustwallet.com/t/how-to-submit-a-token-logo/3863#how-to-get-approved
This token has no real usage yet (2). Putting PR on hold. Please come back to us when all criteria are met.

https://etherscan.io/token/0x11A78577c7c84F8bC6164d848080f1973531c288

**Comment by DEXExchange** [comment]
> As per our policy, brand new tokens are not included, there is a minimum requirement of 500 holder addresses and 1000 transactions, in order to filter out scam tokens.
> See the criteria at (mentioned in the first message by the bot): https://community.trustwallet.com/t/how-to-submit-a-token-logo/3863#how-to-get-approved
> This token has no real usage yet (2). Putting PR on hold. Please come back to us when all criteria are met.
> 
> https://etherscan.io/token/0x11A78577c7c84F8bC6164d848080f1973531c288

I understand as the project is newly just launched and onboarding users currently whom are competing in esports video gaming. The main and only reason if for token logo to appear in Uniswap's protocol frontend so they forwarded me here to trust wallet as that is where they draw their token logo API's from. otherwise the token is showing a "?" in the Uniswap pairing to ETH which is where my company adds the ETH liquidity to for tournament winners to be able to sell their GamerGold (GG) off easily for ETH or USDT return.

My only question as of now is how long will my pull request here be able to stay on hold for to reach 500 holders and 100 TX's?

I hope to hear back at your convenience. 

Best regards,

Kin
CEO
DEX Exchange Inc.
Core Developer of Matrix Gaming IT ecosystem and GamerGold (GG) smart contract.

**Comment by catenocrypt** [comment]
There is no time limit, we can reopen this PR (or create a new one and consider fee on that), so don't worry there will be no need to pay fee again for this same token.
Wish you good luck with the start of your project.

**Comment by DEXExchange** [comment]
> There is no time limit, we can reopen this PR (or create a new one and consider fee on that), so don't worry there will be no need to pay fee again for this same token.
> Wish you good luck with the start of your project.

Best and kindest regards. I will re-open of if timewise becomes buried in newer pull requests, I will open a new pull request and support the fund with all criteria met. Thank you.

-KinToshi

**Pull request closed without merging**
