### PR TITLE
RE OPEN ADD PROPC INFO AND LOGO 

### PR DESCRIPTION
**Pull request by YakuzaPROPC**
Re opening the pr for PROPC
[info.json](https://github.com/user-attachments/files/18053807/info.json)
logo

### CODE REVIEW

**Comment by YakuzaPROPC** [comment]
When could this be merged? is there anything we have to do or is it ok for further review?

**Comment by Cryptocool1** [comment]
• What is the purpose of this token? How will it benefit Trust Wallet users?
 • How is the token being distributed? Are you conducting an airdrop?
 • Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?
 • Is the token listed on a centralized/decentralized exchange?
 • Is a Smart Contract audit completed? Where can we find this information?

**Comment by YakuzaPROPC** [comment]
•What is the purpose of this token? How will it benefit Trust Wallet users?

The PROPC token powers the Propchain ecosystem, enabling secure and
transparent blockchain-based real estate transactions.

For Trust Wallet users, it provides access to fractionalized real estate
investments, passive income opportunities, and platform features like
governance participation and staking rewards. This simplifies property
investing while enhancing transparency and efficiency in the market.

The Propchain platform aims to enhance efficiency, transparency, and
sustainability in the real estate market while solving challenges like
fraud and slow transaction processes. PROPC token holders can use the token
to participate in these innovations securely via Trust Wallet, providing a
seamless and integrated experience for managing digital assets.

• How is the token being distributed? Are you conducting an airdrop?

 The PROPC token is being distributed through a combination of methods,
including staking rewards and vesting schedules.

Users can claim their tokens via the official Propchain Token Dashboard
after connecting their wallet, such as TrustWallet. This ensures that
tokens are distributed transparently to participants based on their
contributions to the ecosystem.

Propchain has also conducted targeted airdrops to reward early adopters and
engage the community, although these are not ongoing and depend on specific
campaigns.

 • Did you sold the tokens at an Initial Coin Offering (ICO) or a token
presale?

Yes, we conducted a token presale prior to the public release of the PROPC
token. This sale was part of our strategy to raise initial funds and build
an early community of investors for their ecosystem.

Details on the ICO or presale phases, including allocation and pricing, can
be found in our official Propchain documentation or announcements. These
presale events allowed early supporters to acquire PROPC tokens before they
became publicly tradable.

• Is the token listed on a centralized/decentralized exchange?

Yes PROPC token is available for trading on the following platforms:
1. MEXC
2. Bitget
3. WOO X
4. UNISWAP
 * more CEX listings are planned.

•Is a Smart Contract audit completed? Where can we find this information?

Yes Audit completed by CertiK & Zokyo.
Link to audit skynet page: https://skynet.certik.com/projects/propchain

Link to Zokyo audit:
https://github.com/zokyo-sec/audit-reports/blob/main/Propchain/Propchain_Zokyo_audit_report_16May_2023.pdf

**Comment by YakuzaPROPC** [comment]
Spelling mistake made on trustwallet :)

PROPCHAIN and now it is PROPCHZIN

**Comment by Cryptocool1** [comment]
That’s what you put in your info.json file :) 
Will fix it soon

**Pull request merged**
