### PR TITLE
Add Coin Discovery Token (BEP20)

### PR DESCRIPTION
**Pull request by Arstudioz00**
Adding info for BEP20 token 'Coin Discovery Token'.

PR created by <a href="https://assets.trustwallet.com">TW Assets Management</a>

### CODE REVIEW

**Comment by Cryptocool1** [comment]
• Is a Smart Contract audit completed? Where can we find this information?

**Comment by Arstudioz00** [comment]
> • Is a Smart Contract audit completed? Where can we find this information?

HI, yes, please find the details here

https://github.com/TechRate/Smart-Contract-Audits/blob/main/October/Coin%20Discovery%20Token%20Full%20Smart%20Contract%20Security%20Audit.pdf

**Comment by Arstudioz00** [comment]
> Hello, Your logo should be a full screen, 256x256. Example: https://community.trustwallet.com/t/how-to-submit-a-token-logo/3863 Screenshot 2021-10-01 at 01 52 16

Hello,

Here it is: https://trsm.in/codi/logo.png

I didn't uploaded directly in asset assuming you want it here, I hope it works

**Comment by Arstudioz00** [comment]
> Can your answer some questions? • What is the purpose of this token? How will it benefit Trust Wallet users? • How is the token being distributed? Are you conducting an airdrop? • Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale? • Is the token listed on a centralized/decentralized exchange? • Is a Smart Contract audit completed? Where can we find this information?

Hello, please find the info:

a. 1. The CODI token is backed by coindiscovery.app which is one of the most trusted coin voting and listing platforms. It is the 3rd biggest when it comes to the amount of coins listed.
Advertisers use the token to make the payments on our coindiscovery.app website for advertisements and many existing trust wallet users are our token holders, it will be easy for them to make the transaction easily. 

b. There are no Airdrops. There was a presale on dxsale and now it is live on pancakeswap.

c. We had the presale on DXsale

d. Token is listed on Pancakeswap

e. Smart contract has been audited by techrate. Here is the the link - https://github.com/TechRate/Smart-Contract-Audits/blob/main/October/Coin%20Discovery%20Token%20Full%20Smart%20Contract%20Security%20Audit.pdf

**Pull request merged**
