### PR TITLE
Add agEUR (ERC20)

### PR DESCRIPTION
**Pull request by tutacrypto**
Adding info for ERC20 token 'agEUR'.

PR created by <a href="https://assets.trustwallet.com">TW Assets Management</a>

### CODE REVIEW

**Comment by cryptomanz** [comment]
As per our policy, brand new tokens are not included, there is a minimum requirement of 25,000 holder addresses and 50,000 transactions, in order to filter out scam tokens.
See the criteria at : https://developer.trustwallet.com/assets/requirements .

**Comment by tutacrypto** [comment]
Hello tuta from Angle here, 
Before paying the TWT fee, I just wanted to verify with you the ❌  Low token circulation. 

Most agEUR holders have deposited their tokens in pools or staking contracts, the main ones being: 
- Angle's agEUR staking contract: [0xb1F2A25fFB2b095E99f430cAF507cC31F9A3EaAB](https://etherscan.io/address/0xb1F2A25fFB2b095E99f430cAF507cC31F9A3EaAB)
- Uni V3 agEUR/USDC pool: [0x7ed3f364668cd2b9449a8660974a26a092c64849](https://etherscan.io/address/0x7ed3f364668cd2b9449a8660974a26a092c64849) 

You can check Angle's app at [app.angle.money](https://app.angle.money), and the docs at [docs.angle.money](https://docs.angle.money). 

Let me know if this is sufficient or if you need any additional information!

**Comment by tutacrypto** [comment]
Hey @cryptomanz, not sure that you got my previous message so tagging you again

**Comment by Cryptocool1** [comment]
Please come back to us when all criteria are met.

**Comment by teddav** [comment]
Hi @Cryptocool1 and @cryptomanz !
It would be amazing if you could open back that PR and allow us to merge it. Unfortunately we do not meet the requirements in terms of # of holders, but I noticed that a few other tokens that you are listing do not either.
We are trying to grow our EURO stablecoin (currently the biggest EUR stablecoin on the market) and it would help a lot to be listed by Trustwallet.
Let me know if you need more information on us.
Thanks a lot
cc @tutacrypto

**Comment by tutacrypto** [comment]
Hello @Cryptocool1 , 

I hope you're fine :) 
agEUR is regularly in the top 10 Uniswap tokens but still doesn't have its logo displayed. It makes not only Angle & agEUR look bad, but also Uniswap ...

agEUR is now at ~500 holders and ~40k transfers on Ethereum, with similar figures on Polygon. Though your criterias haven't been met yet, do you think it would be possible to do something for the token integration at this point? 

Thanks for your consideration, and sorry for bothering you.
Best

**Comment by Cryptocool1** [comment]
Hello, 
The holder requirement is 10.000 now. If the token good, it should be no problem to reach this number of holders

**Comment by tutacrypto** [comment]
Thank you for your reply! 

I'm not sure that much adoption is so easy for agEUR... As it is a EUR-pegged stablecoin, there is no potential for profit which slows down adoption a lot. 

For example, even one of the biggest USD stablecoins, FRAX, number #5 with ~ $1.4B of supply, only has ~6,300 holders... 
Hope you can reconsider again in some time. 

Thanks again :)

**Pull request closed without merging**
