### PR TITLE
Add Moonshot (BEP20)

### PR DESCRIPTION
**Pull request by moonshot-platform**
Adding info for BEP20 token 'Moonshot'.

PR created by <a href="https://assets.trustwallet.com">TW Assets Management</a>

Hello, here is our original PR:  #19562  (for payment details)

### CODE REVIEW

**Comment by moonshot-platform** [comment]
The payment was completed under the closed ticket @cryptomanz 

TxHash:
0F71D2CFF153140170D85F17FA5527F7F01128C2ADAD7E93EAFB7903C5B16E27

**Comment by cryptomanz** [comment]
Can you send me official information about migration

**Comment by moonshot-platform** [comment]
Technical information: https://t.me/MoonShotChat/421654
and here: https://github.com/moonshot-platform/moonshot-ERC20/blob/MoonshotV2/RELEASE_NOTES.md

Official announcement: https://twitter.com/RS25Moonshot/status/1511041363642568728 

TG announcements: https://t.me/MoonShotChat/422219

**Comment by Cryptocool1** [comment]
https://github.com/trustwallet/assets/pull/19794

**Pull request merged**
