### PR TITLE
Adding GFCE token and info. Jetfuel's 3rd ecosystem token

### PR DESCRIPTION
**Pull request by jetfuelfinance**

### CODE REVIEW

**Comment by catenocrypt** [comment]
Correction needed: logo file should be named `logo.png`, please rename (now it is logo.png.png).

**Comment by jetfuelfinance** [comment]
fixed. please review

**Comment by jetfuelfinance** [comment]
Hello. Please review and provide feedback.

**Comment by catenocrypt** [comment]
Correction needed: Info file is not correct JSON file, I think closing '}' is missing, please fix.

**Pull request merged**
