### PR TITLE
JAC Token Logo update

### PR DESCRIPTION
**Pull request by redjayco**

### CODE REVIEW

**Comment by redjayco** [comment]
> Hi! In order to compensate for the efforts of processing PRs, we kindly ask for a contribution.
> See the [Pull Request Fee FAQ](https://developer.trustwallet.com/add_new_asset/pr-fee).
> 
> Please pay **1000 TWT** with the memo **1883** to the address `bnb1tqq9llyr3dyjd559dha6z5r5etk3qfwk07m098`.
> Alternatively, 0.5 BNB is also accepted (same memo & address).
> 
> **QR** code: [Trust](https://api.qrserver.com/v1/create-qr-code/?size=200x200&data=https%3A%2F%2Flink.trustwallet.com%2Fsend%3Fcoin%3D714%26address%3Dbnb1tqq9llyr3dyjd559dha6z5r5etk3qfwk07m098%26amount%3D1000%26memo%3D1883) | [other wallet](https://api.qrserver.com/v1/create-qr-code/?size=200x200&data=bnb1tqq9llyr3dyjd559dha6z5r5etk3qfwk07m098%26amount%3D1000%26memo%3D1883)
> 
> _Notes_:
> 
> * Trust Wallet Tokens (TWT) are distributed to new users through our [Referral Program](https://community.trustwallet.com/t/invite-a-friend-earn-trust-wallet-token-twt/4125).
> * Payment evaluation happens when there is activity on the PR -- write a comment if you have performed the payment.
> * When payment is detected, an Accept Review is automatically placed on the PR, which is a condition for merge.  The merge is still done manually.

----------

Do you have any mode of payment other than BNB and TWT?

**Comment by redjayco** [comment]
Can you give an alternative mode of payment, preferrably Ether? Thanks!

**Comment by kolya182** [comment]
@redjayco You adding image to actual address ,but not smart contract. Please update information

**Comment by redjayco** [comment]
hey this is the token contract address : 0x2d2621A2A41dd907CFBd01F66c826e2BEE14e198

**Comment by redjayco** [comment]
please update logo to this contract address : 0x2d2621A2A41dd907CFBd01F66c826e2BEE14e198 .i already submitted fees , thanks a lot

**Comment by kolya182** [comment]
> please update logo to this contract address : 0x2d2621A2A41dd907CFBd01F66c826e2BEE14e198 .i already submitted fees , thanks a lot

Updated to contract address.

**Pull request merged**
