### PR TITLE
Add logo in TrustWallet for DRIVENprotocol

### PR DESCRIPTION
**Pull request by DRIVENpol**
I want the logo of DRIVENprotocol to be seen by holders

### CODE REVIEW

**Comment by Cryptocool1** [comment]
Correction needed:
This is a BEp20 token, correct folder is blockchains/smartchain/assets. Please correct.
https://community.trustwallet.com/t/how-to-submit-a-token-logo/3863).

**Comment by polthemarketer** [comment]
Can you help me with that?

În joi, 20 mai 2021 la 09:29, CryptoA ***@***.***> a scris:

**Comment by Cryptocool1** [comment]
If you can't rename files in the PR, you may open a new PR. Make sure to mention this PR, so that we can see that fee has been paid already here.
You may want to try our new Assets app in beta; go to https://assets.trustwallet.com, log on with Github, enter contract ID, logo and some additional info, and it will create a PR for you.
See https://community.trustwallet.com/t/how-to-submit-a-token-logo-using-assets-app/82957.

**Comment by polthemarketer** [comment]
Thanks. I did it: https://github.com/trustwallet/assets/pull/8499

În vin., 21 mai 2021 la 07:38, CryptoA ***@***.***> a scris:

**Pull request closed without merging**
