### PR TITLE
added Shibelon assets

### PR DESCRIPTION
**Pull request by monkey-shanti**

### CODE REVIEW

**Comment by monkey-shanti** [comment]
any update?

**Comment by cryptomanz** [comment]
• What is the purpose of this token? How will it benefit Trust Wallet users?
 • How is the token being distributed? Are you conducting an airdrop?
 • Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?
 • Is the token listed on a centralized/decentralized exchange?
 • Is a Smart Contract audit completed? Where can we find this information?

**Comment by monkey-shanti** [comment]
1) Shibelon is the future of binance smart chain tokens with its great team lead by Adam King which will involves Advanced Staking, Super Swaps, 3D NFT's, Play 2 Earn Gaming on its platform soon.

2) Initial distribution was done on pinksale via a presale along with a small 5% distribution via private sale. Rest everything added to liquidity on pancake swap and available to trade.

3) Yes, a presale took place at pinksale of 420bnb.

4) Yes, the token is listed at pancakeswap.

5) Yes, our Smart Contract audit is completed and was done by Soken Team ( https://twitter.com/soken_team/status/1459922446304358410?s=21 )

**Comment by monkey-shanti** [comment]
any update on this?

**Comment by Cryptocool1** [comment]
we require A full token audit is completed by reputable security audit groups. (Certik, Techrate, Dessert finance)

**Comment by Cryptocool1** [comment]
As per our policy, brand new tokens are not included, there is a minimum requirement of 25,000 holder addresses and 50,000 transactions, in order to filter out scam tokens.
See the criteria at : https://developer.trustwallet.com/assets/requirements .

**Comment by Cryptocool1** [comment]
Please come back to us when all criteria are met.
When creating a new PR make sure to mention this PR, so that we can see that fee has been paid already here.

**Pull request closed without merging**
