### PR TITLE
Add TrustWallet Support for GalaxyGoggle

### PR DESCRIPTION
**Pull request by GalaxyGoggle**

### CODE REVIEW

**Comment by GalaxyGoggle** [comment]
cchain now redirects to snowtrace as this is the standard block explorer of AVAX now. Do you want this fixed or the bot should be fixed. Further, all the links now follow that format. Don't know why bot is flagging it.

Thanks in advance

**Comment by cryptomanz** [comment]
Screenshot 2021-12-09 at 23 36 13
Please change

**Comment by GalaxyGoggle** [comment]
@cryptomanz Change made to explorer address. Thanks in advance

**Comment by Cryptocool1** [comment]
• What is the purpose of this token? How will it benefit Trust Wallet users?
 • How is the token being distributed? Are you conducting an airdrop?
 • Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?
 • Is the token listed on a centralized/decentralized exchange?
 • Is a Smart Contract audit completed? Where can we find this information?

**Comment by GalaxyGoggle** [comment]
@Cryptocool1 

> • What is the purpose of this token? How will it benefit Trust Wallet users?  Galaxy Goggle DAO is a decentralized reserve currency protocol based on the GG token. Each GG token is backed by a basket of assets (e.g. MIM, AVAX) in the collateral pool, giving it an intrinsic value that it cannot fall below. GGDAO also introduces economic and game-theoretic dynamics into the market through staking and minting. Ton's of our user base uses trust wallet, being able to find us easily will be beneficial to them and to ensure they got the right contract.
> • How is the token being distributed? Are you conducting an airdrop? Fair Launch and minting through bonds or staking will also add to inflation/distribution over time with the protocol, No airdrop 
> • Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale? No ICO/No Token Sale
> • Is the token listed on a centralized/decentralized exchange? Listen on TraderJoe (https://traderjoexyz.com/#/trade?inputCurrency=0x130966628846bfd36ff31a822705796e8cb8c18d&outputCurrency=0xF2F7CE610a091B94d41D69f4fF1129434a82E2f0#swap-page)
> • Is a Smart Contract audit completed? Where can we find this information? This smart contract is a clone of TIME which has had extensive audits completed. This token is also created by the same trusted and well known team APE-X that was already verified on your platform and added. We may entertain an independent audit down the road but really see no need to do such as we are using tried and battle tested code already.

**Comment by Cryptocool1** [comment]
awaiting for smart contract audit.
on hold for now.

**Comment by Cryptocool1** [comment]
Feel free to open new PR when smart contract audit will be ready
When creating a new PR make sure to mention this PR, so that we can see that fee has been paid already here.

**Pull request closed without merging**
