### PR TITLE
add toman logo and info

### PR DESCRIPTION
**Pull request by tomantoken**
toman token , TMN

### CODE REVIEW

**Comment by catenocrypt** [comment]
Please add an `info.json` file next to the `logo.png`, with info about the project, of the form:

```json
{
    "name": "Trust Wallet Token",
    "website": "https://trustwallet.com",
    "short_description": "Utility token to increase adoption of cryptocurrency.",
    "explorer": "https://etherscan.io/token/0xA866F0198208Eb07c83081d5136BE7f775c2399e",
    "socials": [
        {
            "name": "Twitter",
            "url": "https://twitter.com/trustwalletapp",
            "handle": "TrustWalletApp"
        },
        {
            "name": "Reddit",
            "url": "https://reddit.com/r/trustapp",
            "handle": "TrustApp"
        }
    ]
}
```

**Comment by tomantoken** [comment]
{
    "name": "Toman",
    "website": "https://tomantoken.info/",
    "short_description": "Simple buying and selling of goods online.",
    "explorer": "https://tronscan.org/#/token/1003611",
    "socials": [
        {
            "name": "Twitter",
            "url": "https://twitter.com/tomantoken",
            "handle": "tomantoken"
        },
        {
            "name": "telegram",
            "url": "https://t.me/tomantoken",
            "handle": "tomantoken"
        },
        {
            "name": "instagram",
            "url": "https://instagram.com/tomantoken",
            "handle": "tomantoken"
        }
    ]
}

**Comment by catenocrypt** [comment]
As per our policy, brand new tokens are not included, there is a minimum requirement of 2500 holder addresses and 5000 transactions, in order to filter out scam tokens.
See the criteria at (mentioned in the first message by the bot): https://community.trustwallet.com/t/how-to-submit-a-token-logo/3863).
This token has low usage yet (50 holders). Closing PR for now. Please come back to us when all criteria are met.

https://tronscan.org/#/token/1003611

**Comment by tomantoken** [comment]
Hi
By launching an airdrop, we were able to get enough holders and 
transactions
We request a review
  https://tronscan.org/#/token/1003611

**Comment by tomantoken** [comment]
Hi
By launching an airdrop, we were able to get enough holders and transactions
We request a review

**Comment by tomantoken** [comment]
Hi
I have a problem loading
The fee has been paid

add logo and info
Toman
TMN
https://tronscan.org/#/token/1003611
{
"name": "Toman",
"website": "https://tomantoken.info/",
"short_description": "Simple buying and selling of goods online.",
"explorer": "https://tronscan.org/#/token/1003611",
"socials": [
{
"name": "Twitter",
"url": "https://twitter.com/tomantoken",
"handle": "tomantoken"
},
{
"name": "telegram",
"url": "https://t.me/tomantoken",
"handle": "tomantoken"
},
{
"name": "instagram",
"url": "https://instagram.com/tomantoken",
"handle": "tomantoken"
}
}

**Comment by catenocrypt** [comment]
Merged with #5408 .

**Pull request closed without merging**
