### PR TITLE
Add StarShip (BEP20)

### PR DESCRIPTION
**Pull request by debate231**
Adding info for BEP20 token 'StarShip'.

PR created by <a href="https://assets.trustwallet.com">TW Assets Management</a>

### CODE REVIEW

**Review by Bigboy1982 — APPROVED** [review]

**Comment by debate231** [comment]
please advise. Do we need to pay the 700TWT again?

**Comment by Cryptocool1** [comment]
> please advise. Do we need to pay the 700TWT again?

did you pay perviously?

**Comment by debate231** [comment]
> > please advise. Do we need to pay the 700TWT again?
> 
> did you pay perviously?

Paid 1000TWT https://github.com/trustwallet/assets/pull/14703

**Comment by Cryptocool1** [comment]
• What is the purpose of this token? How will it benefit Trust Wallet users?
• How is the token being distributed? Are you conducting an airdrop?
• Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?
• Is the token listed on a centralized/decentralized exchange?
• Is a Smart Contract audit completed? Where can we find this information?

**Comment by debate231** [comment]
• What is the purpose of this token? How will it benefit Trust Wallet users?
The token is decentralised on Binance Smart Chain. There is utility being built around the token with use in starship nft game (game.deploystarship.com) and the main token pair on cexy,finance exchange

• How is the token being distributed? Are you conducting an airdrop?
Token has already been distributed. A portion of the tokens were air dropped.

• Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?
Token is sold on Pancakeswap. No ICO or presale, token was fair launched. 

• Is the token listed on a centralized/decentralized exchange?
Currently listed on pancakeswap, 1inch, radioshack, with more coming. 

• Is a Smart Contract audit completed? Where can we find this information?
Audit has been completed by solidity.finance - Link: https://solidity.finance/audits/StarShip/

**Review by hbogit — COMMENTED** [review]
Checking

**Pull request merged**
