### PR TITLE
Bitnation update token logo and rename

### PR DESCRIPTION
**Pull request by ghost**
https://etherscan.io/token/0xbb1fa4fdeb3459733bf67ebc6f893003fa976a82 

updade logo
xpat

and rename to Bitnation (XPAT)

### CODE REVIEW

**Comment by Danillo17** [comment]
Please,

who can we talk to? because the wrong logo on the trust was not our fault, for some reason the trust wallet took the logo of another token

**Comment by Danillo17** [comment]
@kolya182

**Comment by kolya182** [comment]
@Danillo17 You still need pay the fee to upload your logo, i have removed old logo for now.

**Comment by Danillo17** [comment]
Hello, i opened a issue report
because the wrong logo on the trust was not our fault, for some reason the trust wallet took the logo of another token
@kolya182

**Comment by Danillo17** [comment]
I explained the situation now there

**Comment by kolya182** [comment]
> Hello, i opened a issue report
> because the wrong logo on the trust was not our fault, for some reason the trust wallet took the logo of another token
> @kolya182

Wrong logo was removed, now you have chance to add your token logo. Go ahead pay the fee.

**Comment by Danillo17** [comment]
Please open again #2332, i explained there, its a exceptional situation caused by trust wallet

**Comment by Danillo17** [comment]
I appreciate that you got the wrong logo.

but I believe it is a mistake of the origin of the trust, so I question the fee

**Pull request closed without merging**
