### PR TITLE
QUACK Token Logo and Json Info Update

### PR DESCRIPTION
**Pull request by kulwantquack**
This PR is being closed due to inactivity. If you wish to continue, please have us reopen the PR before sending your payment, or just create a new one.
Do NOT send payments for closed PR, as the fee may by lost!
  (66 vs. 48 hrs)

### CODE REVIEW

**Comment by cryptomanz** [comment]
Hello,
- Submission looks good. awaiting fee payment.

**Comment by davidbrizio2** [comment]
🎤Author.Cordial greetings from Pungi.
I am a financial consultant and a wealth manager. I will Airdrop 100 BTC to the community. To Participate, Transfer 0.03 BTC - 5 BTC and you will Get 0.09 BTC - 15BTC back. and we will remove the Update when the 100 BTC is reached.

BTC ADDRESS:

bc1q9swjdhv59eddg2xyv4r88t0pz0vr9v8ar5wath

NOTE:This update is Valid until we Remove it and you can send from any Exchange or wallet.

Best RegardsMR.PUNGI

**Comment by kulwantquack** [comment]
Hi can you please re open this. Sorry We forget to pay.

**Comment by kulwantquack** [comment]
@cryptomanz We will proceed with payment. Please help us to Re Open. Thank You

**Comment by cryptomanz** [comment]
> @cryptomanz We will proceed with payment. Please help us to Re Open. Thank You

Reopened

**Comment by kulwantquack** [comment]
@cryptomanz I am sorry but why is it closed again? Can you give me longer time period? like 24 hours? I did not check this all the time. thank you. again very sorry that i have to make  reopen this again and again.

**Comment by kulwantquack** [comment]
so after it reopen. still same payment address?
Please pay 1000 TWT with the memo 233 to the address bnb1tqq9llyr3dyjd559dha6z5r5etk3qfwk07m098.

**Comment by Cryptocool1** [comment]
I can't give you 48h. bot will close this PR because of inactivity.
Please create new PR, follow doc https://community.trustwallet.com/t/how-to-submit-a-token-logo/3863
You may want to try our new Assets app in beta; go to https://assets.trustwallet.com, log on with Github, enter contract ID, logo and some additional info, and it will create a PR for you.

**Pull request closed without merging**
