### PR TITLE
Adding BPX

### PR DESCRIPTION
**Pull request by BLACKPHOENIXBPX**
Black Phoenix is a cryptocurrency with bright future ahead ,that bring benefits more and more for its holders and wants to make you a major investor in digital currency market.

### CODE REVIEW

**Comment by BLACKPHOENIXBPX** [comment]
> **PR Summary**
> Files OK, 3Files in PR: 3
> Token in PR: TRC20 TXBcx59eDVndV5upFQnTR2xdvqFd5reXET
> Could not retrieve info file; BLACKPHOENIXBPX/assets/master TXBcx59eDVndV5upFQnTR2xdvqFd5reXET, HttpError: Not Found

can i pay fee ?

**Review by BLACKPHOENIXBPX — COMMENTED** [review]
is correct? can i pay fee?

**Review by BLACKPHOENIXBPX — COMMENTED** [review]
is correct? can i pay?

**Comment by cryptomanz** [comment]
Hello,
- Info file should be named info.json
- Logo file should be named logo.png
- Please rename

**Comment by Cryptocool1** [comment]
Please create new PR, follow doc https://community.trustwallet.com/t/how-to-submit-a-token-logo/3863
You may want to try our Assets app in beta; go to https://assets.trustwallet.com, log on with Github, enter contract ID, logo and some additional info, and it will create a PR for you.
See https://community.trustwallet.com/t/how-to-submit-a-token-logo-using-assets-app/82957.

**Pull request closed without merging**
