### PR TITLE
Add Kattana token info & logo

### PR DESCRIPTION
**Pull request by sharpfuryz**
Added information for ERC20 [Kattana](https://kattana.io)

### CODE REVIEW

**Comment by Cryptocool1** [comment]
Hello, 
Your contact should be checksummed  0x491E136FF7FF03E6aB097E54734697Bb5802FC1C, not 0x491e136ff7ff03e6ab097e54734697bb5802fc1c. Please change it.

**Comment by Cryptocool1** [comment]
Hello, 
Your contract should be checksummed 0x491E136FF7FF03E6aB097E54734697Bb5802FC1C. Please change it.

**Comment by sharpfuryz** [comment]
I've renamed folder and info.json contents to 0x491E136FF7FF03E6AB097E54734697BB5802FC1C

**Comment by catenocrypt** [comment]
Correction needed:  Please remove the 2 files not in checksum format (the last 2 of the 4).

image

**Comment by sharpfuryz** [comment]
@catenocrypt I've removed not checksummed files, please check

**Comment by catenocrypt** [comment]
Sorry, not correct, folder name is ALL CAPITALS, not checksum format.  Please rename again.

❌  Contract is not in checksum format, should be 0x491E136FF7FF03E6aB097E54734697Bb5802FC1C (not 0x491E136FF7FF03E6AB097E54734697BB5802FC1C). Please rename it. You may need to rename to a temp name first, then to the checksum format, because lowercase-uppercase-only renames are often ignored by the Git client or the filesystem.

**Pull request merged**
