### PR TITLE
Add Meter chain assets

### PR DESCRIPTION
**Pull request by SeanChao**
This PR contains the blockchain info for the Meter chain and some token info on the chain.

The blockchain has been added to wallet-core in commit [c91bb4ea](https://github.com/trustwallet/wallet-core/commit/c91bb4ea4851dc0db4686cbcf3ea2624a53ce639).

### CODE REVIEW

**Comment by hewigovens** [comment]
On it, will fix the CI soon

**Comment by mohammadj44** [comment]
> این روابط عمومی حاوی اطلاعات بلاک چین برای زنجیره متر و برخی اطلاعات رمز در زنجیره است.
> 
> [بلاک چین در commit c91bb4ea](https://github.com/trustwallet/wallet-core/commit/c91bb4ea4851dc0db4686cbcf3ea2624a53ce639) به هسته کیف پول اضافه شده است .

@mohammadj44#My Public Address to Receive SOL ExQu5EgsxWriCkhP5xS6kUoCTXD98nStssYTnpbiMRkx

Pay me via Trust Wallet: https://link.trustwallet.com/send?coin=501&address=ExQu5EgsxWriCkhP5xS6kUoCTXD98nStssYTnpbiMRkx

**Comment by hewigovens** [comment]
@SeanChao can you fix those token image sizes? some are not 256 x 256

**Comment by SeanChao** [comment]
> 



> @SeanChao can you fix those token image sizes? some are not 256 x 256

on it

**Comment by hewigovens** [comment]
@SeanChao take a look at the error output from CI, need to fix link/token image size

**Comment by SeanChao** [comment]
I have updated the logos and a coingecko link. Is there a format requirement for the asset type and explorer link?

**Comment by hewigovens** [comment]
Make sure the token address is checksummed

**Pull request merged**
