### PR TITLE
Add CheersLand (BEP20)

### PR DESCRIPTION
**Pull request by baron0day**

### CODE REVIEW

**Comment by baron0day** [comment]
> **PR Summary** Files OK: 2 Token in PR: BEP20 0xbBBcB350C64Fe974e5C42A55c7070644191823f3 Symbol: **CHEERS** decimals: 18 Links: [Logo](https://raw.githubusercontent.com/CheersLand/assets/master/blockchains/smartchain/assets/0xbBBcB350C64Fe974e5C42A55c7070644191823f3/logo.png) [Info](https://raw.githubusercontent.com/CheersLand/assets/master/blockchains/smartchain/assets/0xbBBcB350C64Fe974e5C42A55c7070644191823f3/info.json) [Website](https://cheersland.org/) [Explorer](https://bscscan.com/token/0xbBBcB350C64Fe974e5C42A55c7070644191823f3) Token check error: ❌ at least 1 tag is required
> 
> 

@leedaniil What does this token error mean? Can I pay BNB now?

**Comment by cryptomanz** [comment]
can you please add tags?
see the requirements here : https://developer.trustwallet.com/assets/repository_details

**Comment by baron0day** [comment]
> can you please add tags? see the requirements here : https://developer.trustwallet.com/assets/repository_details

Thanks for your reply sir , I have commited a new change for adding tags, and the bot checking has passed, so can I pay TWT now?

**Comment by Cryptocool1** [comment]
yes, you can))

**Comment by baron0day** [comment]
> yes, you can))

Thanks, has paid:)

**Comment by cryptomanz** [comment]
• Is a Smart Contract audit completed? Where can we find this information?

**Review by Successahead — APPROVED** [review]

**Comment by Cryptocool1** [comment]
please create new PR when smart contract audit will be ready. Make sure to mention this PR, so the fee can be reused

**Pull request closed without merging**
