### PR TITLE
adding KATA (Katana Inu)

### PR DESCRIPTION
**Pull request by issaelzein**
We have in total around 20k holders across BSC and ETH.
We are listed on two exchanges and two Dexs. 
Certik audited.

### CODE REVIEW

**Comment by Naxious15** [comment]
> We have in total around 20k holders across BSC and ETH. We are listed on two exchanges and two Dexs. Certik audited.

**Comment by Cryptocool1** [comment]
• What is the purpose of this token? How will it benefit Trust Wallet users?
 • How is the token being distributed? Are you conducting an airdrop?
 • Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?
 • Is the token listed on a centralized/decentralized exchange?
 • Is a Smart Contract audit completed? Where can we find this information?

**Comment by issaelzein** [comment]
-  its a gaming coin with its own NFT marketplace


-  trust wallet users can trade hold stake play tournaments with the coins


-  People who bought at ICO can claim there tokens at claim.katanainu.com


- Yes token is listed on bitmart, ZT global, hotbit and it will be listed
on other exchanges as well


- We have a certik audit you can find all information on
https://coinmarketcap.com/currencies/katana-inu/




Am Di., 18. Jan. 2022 um 10:36 Uhr schrieb CryptoA ***@***.***

**Comment by cryptomanz** [comment]
Please come back to us when all criteria are met.
When creating a new PR make sure to mention this PR, so that we can see that fee has been paid already here.

**Comment by issaelzein** [comment]
Hello,
Certik audit is done you can check and find all information on
https://coinmarketcap.com/currencies/katana-inu/

The fee is also paid (#17456). Can you Please add the TrustWallet Logo

**Pull request closed without merging**
