### PR TITLE
add lockyboxcoin (LBC) to trust wallet

### PR DESCRIPTION
**Pull request by rhandnmz**
i have paid 700 twt and request for resubmission

### CODE REVIEW

**Comment by rhandnmz** [comment]
hi i have previously paid 700 twt fee and request for resubmissio
Screenshot 2022-07-22 221642
n

**Comment by cryptomanz1** [comment]
As per our policy, brand new tokens are not included, there is a minimum requirement of 10,000 holder addresses and 15,000 transactions, in order to filter out scam tokens.
See the criteria at : https://developer.trustwallet.com/assets/requirements .

**Comment by rhandnmz** [comment]
> ### PR Summary
> Files OK: 2 Token in PR: **BEP20** 0xAADAC316bf05330077aD215528DDe18Ee8276DCd Failed to get info.json content: failed to unmarshal json: invalid character ':' after top-level value (https://raw.githubusercontent.com/rhandnmz/assets/master/blockchains/smartchain/assets/0xAADAC316bf05330077aD215528DDe18Ee8276DCd/info.json)

what can I do about json invalid character error?

**Comment by cryptomanz1** [comment]
Feel free to open new PR once all requirement are met. Make sure to mention this PR so the fee can be reused

**Pull request closed without merging**
