### PR TITLE
Add CTRFI Logo

### PR DESCRIPTION
**Pull request by vantagecoin18**

### CODE REVIEW

**Comment by Cryptocool1** [comment]
Submission looks good. awaiting fee payment.

**Comment by vantagecoin18** [comment]
yes, wait we will pay later, is there a time limit for paying?

Pada tanggal Sen, 10 Mei 2021 17:58, CryptoA ***@***.***>
menulis:

**Comment by vantagecoin18** [comment]
hello sir, how long does it take to update the logo on truswallet?

**Comment by vantagecoin18** [comment]
Please update price CTRFI on trustwallet
CTRFI already on Coinmarketcap https://coinmarketcap.com/currencies/chester-moon

**Pull request merged**
