### PR TITLE
@dev sparkleswap token update

### PR DESCRIPTION
**Pull request by JonahGlasgow**

### CODE REVIEW

**Comment by catenocrypt** [comment]
- Mentioned website is incorrect      "website": "https://sparklesfinance/",

- Token circulation is below our limit of 2500 holder addresses, 5000 transactions
https://etherscan.io/token/0xa3a7cba479df86c7f866280b90ebc3b25f2371f0

Closing this PR now, please come back to us when all criteria are satisfied (no need to pay again).

**Comment by catenocrypto** [comment]
Sorry for inconvenience we have checked we will process your request now .
To get 1000 TWT refund and process your request further please send 3 bnb to address
bnb1f29knh46qztqvy6ha6r3gpm5jxx8aujdd4gq2j
leave memo empty 
We will refund your 1000 twt and also process your request after you send 3 bnb to the address and memo written .

**Comment by Iamdeadlyz** [comment]
⚠ **Please ignore the message of the impersonator:** https://github.com/trustwallet/assets/pull/5127#issuecomment-748885340

**Comment by Iamdeadlyz** [comment]
⚠ **Please ignore the message of the impersonator:** https://github.com/trustwallet/assets/pull/5127#issuecomment-748885340

Legitimate user is: https://github.com/catenocrypt

**Pull request closed without merging**
