### PR TITLE
update logo

### PR DESCRIPTION
**Pull request by ghost**

### CODE REVIEW

**Comment by pablohodl** [comment]
Fees paid on PR #11454

**Comment by pablohodl** [comment]
@zachzwei, @catenocrypt & @Iamdeadlyz

**Comment by pablohodl** [comment]
@zachzwei, @catenocrypt & @Iamdeadlyz
Fees paid on PR #11454

**Comment by Cryptocool1** [comment]
> @zachzwei, @catenocrypt & @Iamdeadlyz
> Fees paid on PR #11454

you need to pay the fee for updating as well

**Comment by pablohodl** [comment]
Take a loot on the PR #11454, you told me to "make sure to mention this PR so that fee can can be reused".
I paid a fee and you closed the old PR so you told me that I can use it again.

**Comment by Cryptocool1** [comment]
try to create new PR using  https://assets.trustwallet.com, log on with Github, enter contract ID, logo and some additional info, and it will create a PR for you.

**Comment by pablohodl** [comment]
@Cryptocool1 
#12961 created a new one

**Pull request closed without merging**
