### PR TITLE
Add XCN @ Base network

### PR DESCRIPTION
**Pull request by al-onyxprotocol**
This PR adds Onyx's XCN at Base blockchain.
[Second try.]

XCN@ethereum: https://etherscan.io/token/0xa2cd3d43c775978a96bdbf12d733d5a1ed94fb18
XCN@bsc: https://bscscan.com/token/0x7324c7c0d95cebc73eea7e85cbaac0dbdf88a05b

### CODE REVIEW

**Comment by cryptomanz1** [comment]
• What is the purpose of this token? How will it benefit Trust Wallet users?
 • How is the token being distributed? Are you conducting an airdrop?
 • Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?
 • Is the token listed on a centralized/decentralized exchange?
 • Is a Smart Contract audit completed? Where can we find this information?

**Comment by al-onyxprotocol** [comment]
Hi @cryptomanz1,

That this is a bridged token for XCN on ETH and BSC.
Here are the approved PR:
https://github.com/trustwallet/assets/pull/23965
https://github.com/trustwallet/assets/pull/19906

**Comment by Cryptocool1** [comment]
Hi, please update your branch to the recent master

**Comment by al-onyxprotocol** [comment]
@Cryptocool1 
Done.

**Comment by al-onyxprotocol** [comment]
Hi @Cryptocool1 
Please check it.

**Comment by cryptomanz1** [comment]
Please update your branch with the recently master

**Comment by al-onyxprotocol** [comment]
@Cryptocool1
Is it something yet to change on our side?

**Comment by cryptomanz1** [comment]
You need to change your id and folder to the checksum format: `0x9c632E6Aaa3eA73f91554f8A3cB2ED2F29605e0C`

**Comment by al-onyxprotocol** [comment]
@cryptomanz1 
Please check it.

**Comment by al-onyxprotocol** [comment]
Hey @Cryptocool1 @cryptomanz1 

After adding XCN @ Base, the token has no price and CMC link in the Trust Wallet app.
While XCN @ BSC and ETH have the prices and links.

Please suggest how we can fix it.

**Pull request merged**
