### PR TITLE
Add inSure (ERC20)

### PR DESCRIPTION
**Pull request by inSureToken**
Adding info for ERC20 token 'inSure'.

PR created by <a href="https://assets.trustwallet.com">TW Assets Management</a>

### CODE REVIEW

**Comment by cryptomanz** [comment]
Hello,
- As per our policy, brand new tokens are not included, there is a minimum requirement of 2500 holder addresses and 5000 transactions, in order to filter out scam tokens.
See the criteria at (mentioned in the first message by the bot): https://community.trustwallet.com/t/how-to-submit-a-token-logo/3863).
Closing PR for now. Please come back to us when all criteria are met.

**Comment by inSureToken** [comment]
Our project was live for 2 years already.
You can check our CMC and Coingecko pages.

We recently updated smart contracts on Ethereum and BSC.
Old addresses:
ERC20: https://etherscan.io/token/0xb5a4ac5b04e777230ba3381195eff6a60c3934f2
BEP20: https://bscscan.com/address/0x4ac27c1b7eb76e28d1e24849c2da124790c00abc

New addresses (in total we have more than **2500** members):
ERC20: 0xcb86c6a22cb56b6cf40cafedb06ba0df188a416e
BEP20: 0x9b17baadf0f21f03e35249e0e59723f34994f806

Would you be able to add ERC20 token information to the assets folder?


> Hello,
> 
> * As per our policy, brand new tokens are not included, there is a minimum requirement of 2500 holder addresses and 5000 transactions, in order to filter out scam tokens.
>   See the criteria at (mentioned in the first message by the bot): https://community.trustwallet.com/t/how-to-submit-a-token-logo/3863).
>   Closing PR for now. Please come back to us when all criteria are met.

Our project was live for 2 years already.
You can check our CMC and Coingecko pages.

We recently updated smart contracts on Ethereum and BSC.
Old addresses:
ERC20: https://etherscan.io/token/0xb5a4ac5b04e777230ba3381195eff6a60c3934f2
BEP20: https://bscscan.com/address/0x4ac27c1b7eb76e28d1e24849c2da124790c00abc

New addresses (in total we have more than **2500** members):
ERC20: 0xcb86c6a22cb56b6cf40cafedb06ba0df188a416e
BEP20: 0x9b17baadf0f21f03e35249e0e59723f34994f806

Would you be able to add ERC20 token information to the assets folder?

**Comment by cryptomanz** [comment]
> > Hello,
> > 
> > * As per our policy, brand new tokens are not included, there is a minimum requirement of 2500 holder addresses and 5000 transactions, in order to filter out scam tokens.
> >   See the criteria at (mentioned in the first message by the bot): https://community.trustwallet.com/t/how-to-submit-a-token-logo/3863).
> >   Closing PR for now. Please come back to us when all criteria are met.
> 
> Our project is live for 2 years already.
> You can check our CMC and Coingecko pages. (https://coinmarketcap.com/currencies/insure/)
> 
> We recently updated smart contracts on Ethereum and BSC.
> Old addresses:
> ERC20: https://etherscan.io/token/0xb5a4ac5b04e777230ba3381195eff6a60c3934f2
> BEP20: https://bscscan.com/token/0x4ac27c1b7eb76e28d1e24849c2da124790c00abc
> 
> New addresses (in total we have more than **2500** members):
> ERC20: 0xcb86c6a22cb56b6cf40cafedb06ba0df188a416e
> BEP20: 0x9b17baadf0f21f03e35249e0e59723f34994f806
> 
> Would you be able to add ERC20 token information to the assets folder?

hello,
sorry, reopened

**Comment by Cryptocool1** [comment]
Merged

**Comment by inSureToken** [comment]
Thank you is it possible to add information for our
BEP20 token as well?
This is the SC: 0x9b17baadf0f21f03e35249e0e59723f34994f806

Thank you in advance!

Regards,
inSure team

**Comment by inSureToken** [comment]
> 

Hi for some reason our SURE token doesn't show up on the Trust Wallet app.
Can you please help to add our Smart Contracts?

All the contracts can be verified here: https://coinmarketcap.com/currencies/insure/

**Pull request closed without merging**
