### PR TITLE
Add RealMoneyWorld (BEP20)

### PR DESCRIPTION
**Pull request by realblock**
Adding info for BEP20 token 'RealMoneyWorld'.

PR created by <a href="https://assets.trustwallet.com">TW Assets Management</a>

### CODE REVIEW

**Comment by Cryptocool1** [comment]
Please create new PR once you are ready to answer the questions. Make sure to mention this PR so the fee can be reused.

**Comment by realblock** [comment]
> • What is the purpose of this token? How will it benefit Trust Wallet users? 
RMW Token is used for platform members to non-custodial wallet  and to use in Marketplace platform as a payment medium for purchasing goods and services in the system. And developers are working to open new projects to spread the use of Token as much as possible.
Therefore, we are actively working to ensure our token is accessible to the larger DeFi -CeFi community. Trust Wallet is central to that effort.


> • How is the token being distributed? Are you conducting an airdrop?
There was an initial IDO: and it is now being sold via Vindax (CEX). There has been no airdrop.

> •Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?
Yes, on PinkSale from 2022.11.11 10:00 (UTC) to 2022.11.18 12:00 (UTC).
https://www.pinksale.finance/launchpad/0xEb3520e7B611909D70003336D27328D6010EE676?chain=BSC with successfully pool. 

> • Is the token listed on a centralized/decentralized exchange?
https://vindax.com/exchange-base.html?symbol=RMW_USDT will List on 2st December.

> • Is a Smart Contract audit completed? Where can we find this information?
https://github.com/Quillhash/QuillAudit_Reports/blob/master/Realblock%20Smart%20Contract%20Audit%20Report%20-%20QuillAudits.pdf

**Comment by Cryptocool1** [comment]
Hello, are you listed on CoinMarketCap?

**Comment by realblock** [comment]
> Hello, are you listed on CoinMarketCap?

We are working on listing on CoinGecko and CoinMarket and the next plan after listing on TrustWallet is this.

**Comment by Cryptocool1** [comment]
we require CMC listing. 

See the criteria at : https://developer.trustwallet.com/assets/requirements

**Comment by Cryptocool1** [comment]
Please come back to us once criteria is met. Make sure to mention this PR so the fee can be reused.

**Comment by realblock** [comment]
Please check this:
https://www.coingecko.com/en/coins/realmoneyworld

> we require CMC listing.
> 
> See the criteria at : https://developer.trustwallet.com/assets/requirements

**Comment by Cryptocool1** [comment]
Hello, are you listed on CoinMarketCap?

**Comment by realblock** [comment]
> Hello, are you listed on CoinMarketCap?

According to the criteria, the token must be list in price tracking and listed on CG now, please check

**Comment by cryptomanz1** [comment]
Screenshot 2023-01-01 at 14 17 56
https://developer.trustwallet.com/assets/requirements

**Pull request closed without merging**
