### PR TITLE
change status for DEA

### PR DESCRIPTION
**Pull request by Minetu**

### CODE REVIEW

**Comment by Minetu** [comment]
{
    "name": "TrueUSD",
    "website": "https://www.trueusd.com/",
    "description": "TrueUSD (TUSD) is the first independently-verified digital asset redeemable 1-for-1 for US Dollars.",
    "explorer": "https://etherscan.io/token/0xe01c9701a92c601a6d897eb200b90405192ad8c4",
    "type": "ERC20",
    "symbol": "TUSD",
    "decimals": 18,
    "status": "active",
    "id": "0xe01c9701a92c601a6d897eb200b90405192ad8c4",
    "tags": [
        "stablecoin"
    ],
    "links": [
        {
            "name": "github",
            "url": "https://github.com/trusttoken/TrueUSD"
        },
        {
            "name": "twitter",
            "url": "https://twitter.com/tusd_official"
        },
        {
            "name": "telegram",
            "url": "https://t.me/TUSDofficial_EN"
        },
        {
            "name": "medium",
            "url": "https://trueusd.medium.com/"
        },
        {
            "name": "coingecko",
            "url": "https://coingecko.com/en/coins/true-usd/"
        }
    ]
}

**Comment by Cryptocool1** [comment]
please create new PR with your new contract and I will put the status abandoned for your old

**Review by 4011055 — COMMENTED** [review]
86e62bb5652af9a10458493496b83edc0a7ef4cb #18600

**Review by Soheilafsha — COMMENTED** [review]
خطا

**Pull request closed without merging**
