### PR TITLE
Add files via upload

### PR DESCRIPTION
**Pull request by s11dkoba**
Shirushi Coin update.

### CODE REVIEW

**Review by s11dkoba — COMMENTED** [review]
revised.

**Review by s11dkoba — COMMENTED** [review]
changed type

**Review by s11dkoba — COMMENTED** [review]
update

**Review by s11dkoba — COMMENTED** [review]
bep20

**Review by s11dkoba — COMMENTED** [review]
test

**Comment by cryptomanz1** [comment]
As per our policy, there is a minimum requirement of 10,000 holder addresses and 15,000 transactions.
See the criteria at : https://developer.trustwallet.com/listing-new-assets/requirements .

**Pull request closed without merging**
