### PR TITLE
Add Panther Protocol (ZKP) token and logo

### PR DESCRIPTION
**Pull request by aspiers**
Supersedes #21478. 

Please note [previous discussion](https://github.com/trustwallet/assets/pull/21478#issuecomment-1182448703) there.  In particular that we do have more than 10,000 token holders and 15,000 transactions; however they are split across two chains.  At the time of writing:

- [4,696 holders and 21,242 transfers on Ethereum mainnet](https://etherscan.io/token/0x909e34d3f6124c324ac83dcca84b74398a6fa173)
- [5,724 holders and 48,957 transfers on Polygon](https://polygonscan.com/token/0x9a06db14d639796b25a6cec6a1bf614fd98815ec#balances)

Other relevant info:

- https://pantherprotocol.io/
- https://coinmarketcap.com/currencies/panther-protocol/
- https://www.coingecko.com/en/coins/panther-protocol

### CODE REVIEW

**Comment by aspiers** [comment]
I'm not sure why it's complaining about the facebook.com prefix even after I removed the `www.`.

Also not sure why it's warning about the explorer field, since for Polygon tokens polygonscan.com is the correct explorer.

**Comment by aspiers** [comment]
> I'm not sure why it's complaining about the facebook.com prefix even after I removed the `www.`.

This check seems to come from here:

https://github.com/trustwallet/assets-go-libs/blob/22af447f1b1b541391a962bd792a7438d5952a25/validation/info/values.go#L33

**Comment by aspiers** [comment]
Ah, thanks for spotting that `"type"` was wrong and fixing it!  I will fix the remaining youtube and coingecko issues now.

**Comment by aspiers** [comment]
Seems OK now - shall I request our finance team to pay the fee or are there any other issues to address first?  Thanks!

**Comment by Cryptocool1** [comment]
everything is good now, awaiting for the fee payment

**Comment by aspiers** [comment]
The payment request is now with our finance department, who should pay soon.

**Comment by aspiers** [comment]
Please can you reopen this PR? Our finance department needs a little time to prepare and send the funds. It seems a little odd that the bot is configured to auto-close PRs after such a short time, since we only just finalised this PR yesterday. Thanks!

**Comment by Cryptocool1** [comment]
You can create new PR once you will be ready to make the payment

**Comment by aspiers** [comment]
@Cryptocool1 Unfortunately our finance department already made the payment before they realised this PR got auto-closed! Is there any way to get the payment applied to a new PR if I create it?

**Comment by Cryptocool1** [comment]
> @Cryptocool1 Unfortunately our finance department already made the payment before they realised this PR got auto-closed! Is there any way to get the payment applied to a new PR if I create it?

Hello, can you send the proof of your payment?

**Comment by aspiers** [comment]
Thanks so much @Cryptocool1 :-)

**Pull request merged**
