### PR TITLE
Add PolkaParty.io 

### PR DESCRIPTION
**Pull request by JonahGlasgow**
**Commit Description**
Add Polka Party token information and images

**Chain Information**
_ERC20_
_BEP20_

**Additional Links**
_Website:_ [PolkaParty.io](https://www.polkaparty.io/)
_Telegram:_ [PolkaParty Telegram](https://t.me/PolkaParty)

Minimum 25,000 token holders and 50,000 transactions (Airdrop tokens excluded). **_This requirement is subject for review based on the project._**

🔎 **_Request to review our project_** 🔍

### CODE REVIEW

**Comment by JonahGlasgow** [comment]
• What is the purpose of this token? How will it benefit Trust Wallet users?
• How is the token being distributed? Are you conducting an airdrop?
• Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?
• Is the token listed on a centralized/decentralized exchange?
• Is a Smart Contract audit completed? Where can we find this information?

- PolkaParty aims to create a favorable DIY DAO (Parties) service that is designed as a convenient passage for all participating “party” members to pool their funds for various financial activities and features. We designed our platform with your grandmother in mind in order to bring a technical aspect like pooling to the masses. Have you ever dreamed of running your own venture capital fund? PolkaParty provides a never-before-seen platform to join your friends together and make true waves in the market. Not only will you be competing for the best party performance, but we aim to create a competitive environment that rewards the most loyal and driven parties. PolkaParty will launch our platform during the last week of November. Our goal is to ensure a seamless user experience with trust wallet which will ensure mobile users can freely create parties on both Ethereum and Binance Smart Chain. 

- POLP token is distributed to presale holders through a vesting schedule on [UnVest](https://app.unvest.io/tokens/0x48592de8CdED16f6Bb56c896Fe1Affc37630889C)

- POLP token initial presale was done via private sale and nft fundraising [Party Apes](https://polkaplace.xyz/#)

- POLP token is listed on both uniswap and pancakeswap total liquidity ~500k  

- POLP Smart Contract audit report can be found [here](https://github.com/PolkaPartyCEO/POLPTokenAudit) 

**Bonus** 

- POLP LP is Locked and can be found [here](https://app.unicrypt.network/amm/uni-v2/token/0x48592de8CdED16f6Bb56c896Fe1Affc37630889C)

**Comment by JonahGlasgow** [comment]
PolkaParty Explainer [Video](https://youtu.be/4TROANDHjVI) 🎉🎉🎉

**Comment by Cryptocool1** [comment]
As per our policy, brand new tokens are not included, there is a minimum requirement of 25,000 holder addresses and 50,000 transactions, in order to filter out scam tokens.
See the criteria at : https://developer.trustwallet.com/assets/requirements .

**Comment by JonahGlasgow** [comment]
you didnt even review the project!

**Comment by Cryptocool1** [comment]
You don’t meet our requirements

**Comment by JonahGlasgow** [comment]
it say clearly "This requirement is subject for review based on the project." Are you personally reviewing this project or just taking this upon yourself?

**Pull request closed without merging**
