### PR TITLE
Add IMPCOIN (BEP20)

### PR DESCRIPTION
**Pull request by ghost**
Add IMPCOIN (BEP20) info and logo

### CODE REVIEW

**Comment by vts666** [comment]
@Cryptocool1 Sir, please check if we meet the minimum requirements, thank you

**Comment by vts666** [comment]
@cryptomanz1 Sir, please check if we meet the minimum requirements, thank you

**Comment by Cryptocool1** [comment]
hello, how did you get 15k holders in couple of days?
-why do you have the same amount holders and transactions?

**Comment by vts666** [comment]
> hello, how did you get 15k holders in couple of days?
> 
> -why do you have the same amount holders and transactions?

Thank you for the response.

To account for our rapid growth, we recently launched a campaign aimed at attracting early users through a dedicated form on our website. As an incentive, each participant received tokens for subscribing to our newsletters.

**Comment by vts666** [comment]
@Cryptocool1 @cryptomanz1 guys please reopen and check that we meet all requirements, and we will pay for this case

**Pull request closed without merging**
