### PR TITLE
DISC Token Information & Icon

### PR DESCRIPTION
**Pull request by munnaweber**
Our token has 6000+ holders and 20000+ transactions. And we're sent our token valid information. Please check & verify our token to show the icon on trust wallet.

### CODE REVIEW

**Comment by Cryptocool1** [comment]
hello,
• What is the purpose of this token? How will it benefit Trust Wallet users?
 • How is the token being distributed? Are you conducting an airdrop?
 • Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?
 • Is the token listed on a centralized/decentralized exchange?
 • Is a Smart Contract audit completed? Where can we find this information?

**Comment by deniagus1991** [comment]
Hello,
• What is the purpose of this token? How will it benefit Trust Wallet users?
The purpose is to be use in DisCas App (Social Media for Discussion, solve current issues, fight hoaxes and digital voting). There are option for staking & farming.

• How is the token being distributed? Are you conducting an airdrop?
Distributed by purchase. No airdrop.

• Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?
Yes, we did.

• Is the token listed on a centralized/decentralized exchange?
Yes, PancakeSwap (Dex), VinDAX (Cex).

• Is a Smart Contract audit completed? Where can we find this information?
Yes, by Techrate.

**Comment by deniagus1991** [comment]
Hi, please find DisCas audit report here:
https://github.com/TechRate/Smart-Contract-Audits

Thank you.

**Comment by deniagus1991** [comment]
Hello, please include me into this repo I am the project owner and want to answer your question since 3 days ago.

**Comment by deniagus1991** [comment]
> hello,
> • What is the purpose of this token? How will it benefit Trust Wallet users?
> • How is the token being distributed? Are you conducting an airdrop?
> • Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?
> • Is the token listed on a centralized/decentralized exchange?
> • Is a Smart Contract audit completed? Where can we find this information?

Hello, I am the project owner and try to answer this but bot deleted my comment. Would you please include me to this repo?

**Comment by CryptocodeDevelopers** [comment]
> hello,
> • What is the purpose of this token? How will it benefit Trust Wallet users?
> • How is the token being distributed? Are you conducting an airdrop?
> • Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?
> • Is the token listed on a centralized/decentralized exchange?
> • Is a Smart Contract audit completed? Where can we find this information?


Following by...

• What is the purpose of this token? How will it benefit Trust Wallet users?
The purpose is to be use in DisCas App (Social Media for Discussion, solve current issues, fight hoaxes and digital voting). There are option for staking & farming.

• How is the token being distributed? Are you conducting an airdrop?
Distributed by purchase. No airdrop.

• Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?
Yes, we did.

• Is the token listed on a centralized/decentralized exchange?
Yes, PancakeSwap (Dex), VinDAX (Cex).

• Is a Smart Contract audit completed? Where can we find this information?
Yes, by Techrate.

**Comment by Cryptocool1** [comment]
can you send me your smart contract audit please?

**Comment by deniagus1991** [comment]
Hello,Hey there dear community members! DisCas Vision contract is audited and listed, check the report by link below and stay safe 😎Audit report ✅: https://github.com/TechRate/Smart-Contract-Audits/blob/main/DisCas%20Vision%20Full%20Smart%20Contract%20Security%20Audit.pdf Projects website 🌐:  https://discas.visionProjects telegram chat 📬: https://t.me/discasvisionProjects twitter 📱: twitter.com/DisCasVision Techrate's GitHub 🎗: https://github.com/TechRate/Smart-Contract-AuditsOn 8/2/21, 2:48 PM CryptoA ***@***.***> wrote:

can you send me your smart contract audit please?

—You are receiving this because you commented.Reply to this email directly, view it on GitHub, or unsubscribe.
[
{
***@***.***": "http://schema.org",
***@***.***": "EmailMessage",
"potentialAction": {
***@***.***": "ViewAction",
"target": "https://github.com/trustwallet/assets/pull/12360#issuecomment-890802731",
"url": "https://github.com/trustwallet/assets/pull/12360#issuecomment-890802731",
"name": "View Pull Request"
},
"description": "View this Pull Request on GitHub",
"publisher": {
***@***.***": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by deniagus1991** [comment]
Hi, please find attached audit report in pdf. Thank you..On 8/2/21, 2:49 PM Deni Agus ***@***.***> wrote:
Hello,Hey there dear community members! DisCas Vision contract is audited and listed, check the report by link below and stay safe 😎Audit report ✅: https://github.com/TechRate/Smart-Contract-Audits/blob/main/DisCas%20Vision%20Full%20Smart%20Contract%20Security%20Audit.pdf Projects website 🌐:  https://discas.visionProjects telegram chat 📬: https://t.me/discasvisionProjects twitter 📱: twitter.com/DisCasVision Techrate's GitHub 🎗: https://github.com/TechRate/Smart-Contract-AuditsOn 8/2/21, 2:48 PM CryptoA ***@***.***> wrote:

can you send me your smart contract audit please?

—You are receiving this because you commented.Reply to this email directly, view it on GitHub, or unsubscribe.
[
{
***@***.***": "http://schema.org",
***@***.***": "EmailMessage",
"potentialAction": {
***@***.***": "ViewAction",
"target": "https://github.com/trustwallet/assets/pull/12360#issuecomment-890802731",
"url": "https://github.com/trustwallet/assets/pull/12360#issuecomment-890802731",
"name": "View Pull Request"
},
"description": "View this Pull Request on GitHub",
"publisher": {
***@***.***": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by CryptocodeDevelopers** [comment]
https://github.com/TechRate/Smart-Contract-Audits/blob/main/DisCas%20Vision%20Full%20Smart%20Contract%20Security%20Audit.pdf

**Pull request merged**
