### PR TITLE
YFBTC

### PR DESCRIPTION
**Pull request by frankfun001**

### CODE REVIEW

**Comment by frankfun001** [comment]
Payment made

**Comment by Iamdeadlyz** [comment]
As per our policy, brand new tokens are not included. There is a minimum requirement of 500 holder addresses and 1000 transactions in order to filter out scam tokens. See the criteria at (mentioned in the first message by the bot): https://community.trustwallet.com/t/how-to-submit-a-token-logo/3863#how-to-get-approved

This token has below-limit usage yet. This pull request will be put on hold. Please come back to us when all criteria are met.
https://etherscan.io/token/0x236Ba1c2DB0a19D04D84e9Fd4AAB22d10b19C6Cb (355 ,1860)

**Comment by frankfun001** [comment]
I was contracted to upload this logo. This is not my project. Surely 1860 transactions and over 300 users proves that this is a legit project, kindly review terms and help merge this logo. My time is already running out

**Comment by Iamdeadlyz** [comment]
> I was contracted to upload this logo. This is not my project. Surely 1860 transactions and over 300 users proves that this is a legit project, kindly review terms and help merge this logo. My time is already running out

Not possible. You should be aware of the requirements before proceeding.

**Comment by frankfun001** [comment]
Please review again we have reached the minimum requirements. https://etherscan.io/token/0x236Ba1c2DB0a19D04D84e9Fd4AAB22d10b19C6Cb

**Comment by frankfun001** [comment]
we are replacing this token yfbtc with our new token yfethereum.  this is the new contract address 0x68763E696bdeE1726E5A2D100Fceaa5bd6c2fB3e please merge under this PR.
logo

**Comment by Iamdeadlyz** [comment]
> we are replacing this token yfbtc with our new token yfethereum. this is the new contract address 0x68763E696bdeE1726E5A2D100Fceaa5bd6c2fB3e please merge under this PR.
> logo

So you want to remove the info.json and logo for `0x236Ba1c2DB0a19D04D84e9Fd4AAB22d10b19C6Cb`? This PR will be focused for `0x68763E696bdeE1726E5A2D100Fceaa5bd6c2fB3e`?

**Comment by frankfun001** [comment]
Thé info.json is still thé same we are just changing the logo and the
address. So merge nee logo to the new contract address

**Comment by Iamdeadlyz** [comment]
> Thé info.json is still thé same we are just changing the logo and the address. So merge nee logo to the new contract address

Noted. But, looking at the info.json right now, the website and description are entirely different (aside from the name which is obvious), since `0x68763E696bdeE1726E5A2D100Fceaa5bd6c2fB3e` is YFETH. Please commit the changes in this PR.

**Comment by frankfun001** [comment]
[info.json.txt](https://github.com/trustwallet/assets/files/5519677/info.json.txt)
this is the info.json file for the YFETHEREUM. please review and merge file

**Comment by Iamdeadlyz** [comment]
> [info.json.txt](https://github.com/trustwallet/assets/files/5519677/info.json.txt)
> this is the info.json file for the YFETHEREUM. please review and merge file

Please commit it directly to the PR.

**Comment by frankfun001** [comment]
I commit this on the PR the file was uploaded to the PR please check and
merge

**Comment by Iamdeadlyz** [comment]
> I commit this on the PR the file was uploaded to the PR please check and merge

There are no new commits. Double-check again.
image

**Comment by frankfun001** [comment]
new commit made please merge logo to contract address0x236Ba1c2DB0a19D04D84e9Fd4AAB22d10b19C6Cb 
logo

**Comment by frankfun001** [comment]
how long before repo is merged this is taking too long

**Comment by Iamdeadlyz** [comment]
It's taking long, since, then again, your users are not enough.
https://etherscan.io/token/0x68763e696bdee1726e5a2d100fceaa5bd6c2fb3e
Currently: 33 real holders and 1577 transactions (airdropped tokens excluded - `5̶0̶0̶ ̶h̶o̶l̶d̶e̶r̶s̶ ̶a̶n̶d̶ ̶2̶0̶4̶4̶ ̶t̶x̶`)

For reference: https://community.trustwallet.com/t/how-to-submit-a-token-logo/3863#how-to-get-approved

**Comment by frankfun001** [comment]
This pr was paid for long before the new terms. You have refused to merge this or. First you asked for a requirement and I provided them now you're asking for a new requirement for a pr that has been paid for long ago.

**Comment by Iamdeadlyz** [comment]
> This pr was paid for long before the new terms. You have refused to merge this or. First you asked for a requirement and I provided them now you're asking for a new requirement for a pr that has been paid for long ago.

You indeed paid for the PR, but, you changed the token. Hence, new rules will be applied since you have a new token.

**Comment by Iamdeadlyz** [comment]
Let us know once you have reached the requirements so we can re-open this PR.

**Pull request closed without merging**
