### PR TITLE
Add BirdChain logo and info

### PR DESCRIPTION
**Pull request by birdchain5**
Add BirdChain logo and info

### CODE REVIEW

**Comment by birdchain5** [comment]
Payment of 250 TWT Completed. 

please, We just migrate to BSC, our previous address has more than 4,000 plus holders.

**Comment by Cryptocool1** [comment]
> Payment of 250 TWT Completed.
> 
> please, We just migrate to BSC, our previous address has more than 4,000 plus holders.

Correction needed:
PR should include only 2 files

**Review by birdchain5 — COMMENTED** [review]
file deleted

**Comment by Cryptocool1** [comment]
> > > Payment of 250 TWT Completed.
> > > please, We just migrate to BSC, our previous address has more than 4,000 plus holders.
> > 
> > 
> > Correction needed:
> > PR should include only 2 files
> 
> Please I never notice the file repeated since I close it the first time.
> How can this be fix, or can you just fix it at your end ?

I can delete, but what logo is correct one? they are different

**Comment by birdchain5** [comment]
> > > > Payment of 250 TWT Completed.
> > > > please, We just migrate to BSC, our previous address has more than 4,000 plus holders.
> > > 
> > > 
> > > Correction needed:
> > > PR should include only 2 files
> > 
> > 
> > Please I never notice the file repeated since I close it the first time.
> > How can this be fix, or can you just fix it at your end ?
> 
> I can delete, but what logo is correct one? they are different

that's the correct logo. The logo newly uploaded today.

logo

**Comment by Cryptocool1** [comment]
Hello,
now you can add your correct logo

**Comment by birdchain5** [comment]
I believe I have done that. please check if it's okay my dear Friend.

**Pull request merged**
