### PR TITLE
Add TRDC logo and info

### PR DESCRIPTION
**Pull request by JoshuaLab**
Add Traders Coin (Binance Smart Chain - Bep20) logo to TrustWallet.

### CODE REVIEW

**Comment by ramsty** [comment]
As per our policy, brand new tokens are not included, there is a minimum requirement of 25000 holder addresses and 50000 transactions, in order to filter out scam tokens.
See the criteria at (mentioned in the first message by the bot): https://developer.trustwallet.com/assets/requirements).
Closing PR for now. Please come back to us when all criteria are met.

**Comment by ramsty** [comment]
When creating a new PR make sure to mention this PR, so that we can see that fee has been paid already here.

**Comment by JoshuaLab** [comment]
This token is listed on:

https://global.bittrex.com/Market/Index?MarketName=BTC-NGC

https://hitbtc.com/ngc-to-usdt

This is not a new token, could you please approve it?

**Comment by JoshuaLab** [comment]
> When creating a new PR make sure to mention this PR, so that we can see that fee has been paid already here.

Could you refund us?

**Comment by Cryptocool1** [comment]
Снимок экрана 2021-11-21 в 13 54 51

**Comment by JoshuaLab** [comment]
> Снимок экрана 2021-11-21 в 13 54 51

Shame, you change the rules overnight, we get absolute no "alert from the bot that rules are changed overnight", take the money, and then say "no refund".

**Comment by Cryptocool1** [comment]
• What is the purpose of this token? How will it benefit Trust Wallet users?
 • How is the token being distributed? Are you conducting an airdrop?
 • Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?
 • Is the token listed on a centralized/decentralized exchange?
 • Is a Smart Contract audit completed? Where can we find this information?

**Comment by JoshuaLab** [comment]
• What is the purpose of this token? How will it benefit Trust Wallet users? 

> TRDC will introduce to traders a DEX platform and other useful tools for trading like whales wallets cloning and gains and losses tracking.

• How is the token being distributed? Are you conducting an airdrop? 

> Trading on Pancakeswap, It was a fair launch from May, then there was an airdrop done by the team in August and September.  

• Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale? 

> No, it was a fair launch without a presale/ICO. 

• Is the token listed on a centralized/decentralized exchange? 

> Yes
Pancakeswap: https://pancakeswap.finance/swap#/swap?outputCurrency=0x7e8db69dcff9209e486a100e611b0af300c3374e
XT: https://www.xt.com/tradePro/trdc_usdt
CoinTiger: https://www.cointiger.com/en-us/#/trade_center?coin=trdc_usdt
Latoken: https://latoken.com/exchange/TRDC_USDT
Coinsbit: https://coinsbit.io/trade_classic/TRDC_USDT

• Is a Smart Contract audit completed? Where can we find this information? 

> Yes, TRDC contract had been reviewed by TechRate 
> Here's the link : https://trdctoken.com/wp-content/uploads/2021/08/Traders-coin-Full-Smart-Contract-Security-Audit.pdf

**Pull request merged**
