### PR TITLE
Add Fei Protocol (ERC20)

### PR DESCRIPTION
**Pull request by bpm6867**
Adding info for ERC20 token 'Fei Protocol'.

PR created by <a href="https://assets.trustwallet.com">TW Assets Management</a>

### CODE REVIEW

**Comment by catenocrypt** [comment]
ERC20 token `0x956F47F50A910163D8BF957Cf5846D573E7f87CA` seems not to exist, closing PR.
https://etherscan.io/token/0x956F47F50A910163D8BF957Cf5846D573E7f87CA

**Comment by bpm6867** [comment]
@catenocrypt @zachzwei Hi Adam and Zach:

Fei Labs recently raised 19million from a16z, coinbase, nascent, variant etc.(https://www.coindesk.com/coinbase-naval-framework-ventures-19m-raise-fei-stablecoin), and started our Genesis group 24 hours ago that has raised 92k+ ETH so far with 7k unique users : check out the Dunn Analytics https://duneanalytics.com/descipher/Fei

Our Genesis contracts have 7000+ unique users that will be transitioned to FEI and TRIBE at protocol launch on Saturday, April 3, 2021

We would love to have verified contracts on uniswap for our IDO on Saturday for FEI and TRIBE

Users from this contract will transition to both FEI and TRIBE contracts listed below: https://etherscan.io/address/0xBFfB152b9392e38CdDc275D818a3Db7FE364596b

FEI : https://etherscan.io/address/0x956F47F50A910163D8BF957Cf5846D573E7f87CA

TRIBE : https://etherscan.io/address/0xc7283b66Eb1EB5FB86327f08e1B5816b0720212B

Is there any way you can help? @zachzwei @catenocrypt

**Comment by bpm6867** [comment]
The token will be claimable immediately when Genesis ends at 12pm PT on April 3. We can show you the code path it will take if that would be helpful @catenocrypt @zachzwei

**Comment by catenocrypt** [comment]
Correction needed:  Please remove the 6 files residing directly in the `assets` folder.

image

**Comment by bpm6867** [comment]
@catenocrypt I made the changes you requested. Please let me know if you need anything else and if I can send the payment.

**Comment by catenocrypt** [comment]
Technically it is OK, but circulation is low.

As per our policy, brand new tokens are not included, there is a minimum requirement of 2500 holder addresses and 5000 transactions, in order to filter out scam tokens.
See the criteria at (mentioned in the first message by the bot): https://community.trustwallet.com/t/how-to-submit-a-token-logo/3863).
These tokens have no real usage yet (0; 14 holder addresses). Closing PR for now. Please come back to us when all criteria are met.  Multi-chain and staking tokens may get special treatment, let us know if this is the case. 

https://etherscan.io/token/0x956F47F50A910163D8BF957Cf5846D573E7f87CA
https://etherscan.io/token/0xc7283b66Eb1EB5FB86327f08e1B5816b0720212B

**Comment by bpm6867** [comment]
@catenocrypt Hi - there are 13k+ unique addresses that participated in our Genesis group (we raised 297K ETH so far) that ends in 4 hrs and we are about to have the largest pools on Uniswap when we do the IDO in a few hours - check out this dashboard to see the unique users - https://duneanalytics.com/descipher/Fei

It would be great if we can get this verified in the next few hours before we make the largest swap ever on an AMM, would really appreciate the help. This is my twitter : https://twitter.com/BriannaPageM and my colleagues: https://twitter.com/joey__santoro and https://twitter.com/sdalcega ... 

We raised 19 million from a16z, nascent, naval, framework etc. This is not a scam. 

@zachzwei @catenocrypt Can you please help

**Comment by bpm6867** [comment]
@catenocrypt Can you look again? We launched!

**Comment by bpm6867** [comment]
@zachzwei Can you help? We are live now https://info.uniswap.org/pair/0x9928e4046d7c6513326cCeA028cD3e7a91c7590A

@catenocrypt

**Comment by bpm6867** [comment]
This has been paid

**Comment by bpm6867** [comment]
https://explorer.binance.org/address/bnb1tqq9llyr3dyjd559dha6z5r5etk3qfwk07m098

**Comment by catenocrypt** [comment]
That's our destination address, but this does not tell which is your transaction.  Please provide TXID.

**Comment by catenocrypt** [comment]
OK, found it   
ABC3FB569DD679AECB7D779181C013EDCA3C6027706C69B4CD03114BA01BF495

**Comment by catenocrypt** [comment]
PR was closed, that's why the bot did not find the payment, I overlooked this, sorry.

**Comment by bpm6867** [comment]
Thank you @catenocrypt

**Pull request merged**
