### PR TITLE
Add PolkaCity (BEP20)

### PR DESCRIPTION
**Pull request by drogbacrash**
Adding info for BEP20 token 'PolkaCity'.

PR created by <a href="https://assets.trustwallet.com">TW Assets Management</a>

### CODE REVIEW

**Comment by ramsty** [comment]
Hi!
Please follow the rules for adding token, your logo should be a full screen
Example:
https://community.trustwallet.com/t/how-to-submit-a-token-logo/3863
137116359-c2bb87b7-239a-4c8d-b54e-4a679c621186

**Comment by drogbacrash** [comment]
[image: Yeni.png]

ramsty ***@***.***>, 25 Kas 2021 Per, 16:53 tarihinde şunu
yazdı:

**Comment by drogbacrash** [comment]
*Hi,*

I sent it as 256x256

Thank you.

ICO Sins ***@***.***>, 25 Kas 2021 Per, 17:01 tarihinde şunu
yazdı:

**Comment by cryptomanz** [comment]
Please send again
Screenshot 2021-11-25 at 17 25 40

**Comment by drogbacrash** [comment]
Hi, I sent it in the attachment

Nazar ***@***.***>, 25 Kas 2021 Per, 18:27 tarihinde şunu
yazdı:

**Comment by drogbacrash** [comment]
[image: Logo.png]

ICO Sins ***@***.***>, 25 Kas 2021 Per, 18:29 tarihinde şunu
yazdı:

**Comment by Cryptocool1** [comment]
you didn't attach anything
Снимок экрана 2021-11-25 в 17 32 52

**Comment by drogbacrash** [comment]
I will resend it.

CryptoA ***@***.***>, 26 Kas 2021 Cum, 01:33 tarihinde şunu
yazdı:

**Comment by drogbacrash** [comment]
ICO Sins ***@***.***>, 26 Kas 2021 Cum, 11:24 tarihinde şunu
yazdı:

**Comment by drogbacrash** [comment]
Did you check?

ICO Sins ***@***.***>, 26 Kas 2021 Cum, 12:08 tarihinde şunu
yazdı:

**Comment by cryptomanz** [comment]
Screenshot 2021-11-26 at 21 12 10

**Comment by drogbacrash** [comment]
What is this?

Nazar ***@***.***>, 26 Kas 2021 Cum, 22:12 tarihinde şunu
yazdı:

**Comment by Cryptocool1** [comment]
you did not attach anything
please create new PR with correct logo.
When creating a new PR make sure to mention this PR, so that we can see that fee has been paid already here.

**Pull request closed without merging**
