### PR TITLE
Add ETNA LOGO ( BEP20 )

### PR DESCRIPTION
**Pull request by Shyamthakur33**

### CODE REVIEW

**Comment by Shyamthakur33** [comment]
@catenocrypt dear sir, could you please help to check if all the details are correct? Thanks

**Comment by Shyamthakur33** [comment]
@catenocrypt you around?

**Comment by catenocrypt** [comment]
Submission looks OK; awaiting fee payment.

**Comment by Shyamthakur33** [comment]
> Submission looks OK; awaiting fee payment.

@catenocrypt payment done

**Comment by Shyamthakur33** [comment]
> Submission looks OK; awaiting fee payment.

@catenocrypt sir, waiting for you

**Comment by Shyamthakur33** [comment]
> Submission looks OK; awaiting fee payment.

@catenocrypt morning dev, still waiting

**Comment by Shyamthakur33** [comment]
> Submission looks OK; awaiting fee payment.

@catenocrypt you there please?

**Comment by Shyamthakur33** [comment]
> Submission looks OK; awaiting fee payment.

@catenocrypt hello D :) 
you around?

**Pull request merged**
