### PR TITLE
add hland logo and info

### PR DESCRIPTION
**Pull request by Kompasswallet**
add hland logo and info

### CODE REVIEW

**Comment by Kompasswallet** [comment]
add hland logo and info

**Comment by Kompasswallet** [comment]
"Some checks were not successful" <=== What's wrong?

**Comment by Kompasswallet** [comment]
image

i want delete this commit (kompass token)

**Comment by catenocrypt** [comment]
1. Folder name should be token contract in 'checksum' format
2. Info.json file is missing
3. Token circulation is below limit of  2500 holder addresses/5000 transactions

```
-  X 'Folder structure for chain ethereum (ethereum fork)':  1 errors
   X   'Expect asset at path /home/runner/work/assets/assets/blockchains/ethereum/assets/0x41bc0913ed789428e107c4ea9ed007815c5a8230 in checksum: '0x41Bc0913ED789428E107C4eA9ED007815c5A8230''
```

**Comment by Kompasswallet** [comment]
Please check again.

**Comment by catenocrypt** [comment]
Submission looks OK.

**Pull request merged**
