### PR TITLE
Add AMAN logo and info

### PR DESCRIPTION
**Pull request by CryptoUltraman**
There are already 50,000 users in our community, and they want to add the AMAN logo to Trust Wallet.

### CODE REVIEW

**Comment by CryptoUltraman** [comment]
> 不允许的文件：0xf767A863B1D52ac909b38700f867669fedca8C63 / info.json。请还原它。
> 不允许使用的文件：0xf767A863B1D52ac909b38700f867669fedca8C63 / logo.png。请还原它。

Do I need to re-upload these two files.

**Comment by CryptoUltraman** [comment]
If I am not approved after completing the payment, do I need to pay the fee again?

**Comment by catenocrypt** [comment]
We don't see fee payment, please provide TXID to check.
This submission is not correct, though.

**Comment by catenocrypt** [comment]
Structure of the file in this PR is wrong, cannot be evaluated.
Please follow documentation:  https://community.trustwallet.com/t/how-to-submit-a-token-logo/3863 
You may want to try our Assets app (in beta);  close this PR; go to https://assets.trustwallet.com, log on with Github, enter contract ID, logo and some additional info, and it will create a PR for you.  See  https://community.trustwallet.com/t/how-to-submit-a-token-logo-using-assets-app/82957

**Pull request closed without merging**
