### PR TITLE
Updated logo to work in dark and light modes

### PR DESCRIPTION
**Pull request by chrishobcroft**
Maximum PR age reached, auto-closing PR  (103 vs. 60 hrs)

### CODE REVIEW

**Comment by chrishobcroft** [comment]
Here is how the new logo would look inside a circle:

logo

**Comment by chrishobcroft** [comment]
You want me to pay you to work to make your product look less ugly?

Haha, you guys are really funny.

**Comment by vcoolish** [comment]
Thanks @chrishobcroft we will consider changing our rules, to make logos look better

**Comment by catenocrypt** [comment]
Image requirements updated with note on dark mode.

image

**Comment by chrishobcroft** [comment]
Thanks, are you still refusing to merge this PR unless I pay you?

**Pull request merged**
