### PR TITLE
AIR Token LOGO And Info

### PR DESCRIPTION
**Pull request by Satoshiisgod**
Add new AIR Token LOGO And Info

### CODE REVIEW

**Comment by cryptomanz** [comment]
hello,
Can your answer some questions?
• What is the purpose of this token? How will it benefit Trust Wallet users?
 • How is the token being distributed? Are you conducting an airdrop?
 • Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?
 • Is the token listed on a centralized/decentralized exchange?
 • Is a Smart Contract audit completed? Where can we find this information?

**Comment by Satoshiisgod** [comment]
1. What is the purpose of this token? 

 The AIR is the Token of the AirCoin project, Our first product AirCash is on the way. 
 
 AIR will be the utility token of the AirCash system.

2. How will it benefit Trust Wallet users?

Many of our users from Asia and Africa use Trust Wallet to buy and sell AIR, It would be good for them to use Trust Wallet.

3. How is the token being distributed? 

The token is distributed by IDO on PancakeSwap.

4. Are you conducting an airdrop?

We are doing an airdrop on CoinMarketCap.

If possible we want to do an airdrop on Trust Wallet.

5. Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?

NO, there is no ICO or presale.

6. Is the token listed on a centralized/decentralized exchange?

AIR was listed on PancakeSwap, CoinMarketCap, COinGecko.

https://pancakeswap.finance/info/token/0xd8a2ae43fd061d24acd538e3866ffc2c05151b53

https://coinmarketcap.com/currencies/air/

https://www.coingecko.com/en/coins/aircoin

7. Is a Smart Contract audit completed? Where can we find this information?

NO, The audit is on the way.

**Comment by cryptomanz** [comment]
- Awaiting for smart contract audit.

**Comment by Satoshiisgod** [comment]
Hello AIR is just a standard BEP20 token.

Here is the source code.

https://bscscan.com/address/0xd8a2ae43fd061d24acd538e3866ffc2c05151b53#code

**Comment by Satoshiisgod** [comment]
> * Awaiting for smart contract audit.

Hello team,

AIR is just a standard BEP20 token.

Here is the source code:

https://bscscan.com/address/0xd8a2ae43fd061d24acd538e3866ffc2c05151b53#code

**Comment by Satoshiisgod** [comment]
The audit is for our first product AirCash, and AIR is just a utility token in the system.

AIR is just a standard BEP20 token.

Here is the source code:

https://bscscan.com/address/0xd8a2ae43fd061d24acd538e3866ffc2c05151b53#code

**Comment by Cryptocool1** [comment]
could you add the links?

**Comment by Satoshiisgod** [comment]
> could you add the links?

Hello Cryprocool1, What kind of link do you need?

**Comment by Satoshiisgod** [comment]
> could you add the links?

There is no audit for the AIR utility token.

**Comment by cryptomanz** [comment]
can you please add links to your PR?
example:
{
  "name": "AIR",
  "website": "https://aircoin.cool",
  "description": "AIR is to mock the madness of the cryptocurrency market. AIR is everywhere, after buying AirCoin you get nothing but AIR.",
  "explorer": "https://bscscan.com/token/0xd8a2aE43Fd061d24acd538e3866Ffc2c05151b53",
  "type": "BEP20",
  "symbol": "AIR",
  "decimals": 18,
  "status": "active",
  "id": "0xd8a2aE43Fd061d24acd538e3866Ffc2c05151b53",
  "links": [
         {
             "name": "telegram",
             "url": ""
         },
         {
             "name": "twitter",
             "url": ""
         },
         {
             "name": "github",
             "url": ""
         },
         {
             "name": "reddit",
             "url": ""
         },
         {
             "name": "youtube",
             "url": ""
         }
     ]
 }

**Comment by Satoshiisgod** [comment]
> can you please add links to your PR?
> example:
> {
> "name": "AIR",
> "website": "https://aircoin.cool",
> "description": "AIR is to mock the madness of the cryptocurrency market. AIR is everywhere, after buying AirCoin you get nothing but AIR.",
> "explorer": "https://bscscan.com/token/0xd8a2aE43Fd061d24acd538e3866Ffc2c05151b53",
> "type": "BEP20",
> "symbol": "AIR",
> "decimals": 18,
> "status": "active",
> "id": "0xd8a2aE43Fd061d24acd538e3866Ffc2c05151b53",
> "links": [
> {
> "name": "telegram",
> "url": ""
> },
> {
> "name": "twitter",
> "url": ""
> },
> {
> "name": "github",
> "url": ""
> },
> {
> "name": "reddit",
> "url": ""
> },
> {
> "name": "youtube",
> "url": ""
> }
> ]
> }

OK

**Pull request merged**
