### PR TITLE
Add w3ULL (ERC20)

### PR DESCRIPTION
**Pull request by jourdanhaines**
Adding info for ERC20 token 'w3ULL'.

PR created by <a href="https://assets.trustwallet.com">TW Assets Management</a>

### CODE REVIEW

**Comment by jourdanhaines** [comment]
The reason for low holders is due to our token being a wrapped representation of the 3ULL coin. We are setting up w3ULL on Ethereum so as to support a bridge from our blockchain and Ethereum.

**Comment by samthompsonkennedy** [comment]
> The reason for low holders is due to our token being a wrapped representation of the 3ULL coin. We are setting up w3ULL on Ethereum so as to support a bridge from our blockchain and Ethereum.

Please see the following https://explorer.playa3ull.games/accounts

Currently lists **54,916** holders, which may interact with w3ULL to bridge 3ULL to and from Ethereum.

**Comment by Cryptocool1** [comment]
As we do not support you blockchain we cannot count your holders as for ERC20 token. 
please come back to us once holders requirement is met. Make sure to mention this PR so the fee can be reused.

**Comment by samthompsonkennedy** [comment]
> As we do not support you blockchain we cannot count your holders as for ERC20 token. please come back to us once holders requirement is met. Make sure to mention this PR so the fee can be reused.

Hi @Cryptocool1 
We don't have many holders of `w3ULL` on Ethereum, are we also able to submit for `w3ULL` on Ethereum and count that towards our total holder count?

As we aren't able to add support for our chain.

**Pull request closed without merging**
