### PR TITLE
Uploading Additional Information Regarding "NFTY"

### PR DESCRIPTION
**Pull request by DLhugly**
Updated Info on NFTY Token https://bscscan.com/token/0x5774b2fc3e91af89f89141eacf76545e74265982

### CODE REVIEW

**Comment by cryptomanz** [comment]
Hello,
Please remove this tags "metaverse","Web3" and change tag "DeFi"  to "defi"

**Comment by DLhugly** [comment]
Most recent PR updates NFTY Tags to required specs. Thank you for
assistance.

**Comment by cryptomanz** [comment]
your logo should be a full screen, please change.

**Comment by DLhugly** [comment]
Thank you. I have adjusted to full screen logo.

**Comment by ramsty** [comment]
Could you answer some questions?
• What is the purpose of this token? How will it benefit Trust Wallet users?
• How is the token being distributed? Are you conducting an airdrop?
• Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?
• Is the token listed on a centralized/decentralized exchange?
• Is a Smart Contract audit completed? Where can we find this information?

**Comment by DLhugly** [comment]
Hi yes,

*What is the purpose of this token?*
Used to reward users through staking and trading, community activity, data
sharing with token gate builders, and fees for NFT marketplace
participation.

*How will it benefit Trust Wallet users? *
We have numerous trust wallet holders who are now not having a good
experience because NFTY is not listed.

*How is the token being distributed?*
Token has already been issued via an IDO launch and is continuously
emitting from Native Staking Pools.

*Are you conducting an airdrop?*
Not at this time.

*Did you sold the tokens at an Initial Coin Offering (ICO) - - or a token
presale?*
Token was IDO'd on ApeSwap https://apeswap.finance/.

*Is the token listed on a centralized/decentralized exchange?*
Yes:
ApeSwap (BSC) -
https://info.apeswap.finance/pair/0x884be30e2c95b9cfed614ad2b5edf40af2a144ad

Uniswap -
https://v2.info.uniswap.org/token/0xE1D7C7a4596B038CEd2A84bF65B8647271C53208
Gate.io <http://gate.io/> - https://www.gate.io/trade/NFTY_USDT
MEXC - https://www.mexc.com/exchange/NFTY_USDT

*Is a Smart Contract audit completed? Where can we find this information?*
Smart contract is audited and can be found on HashEx -
*https://twitter.com/HashExOfficial
<https://twitter.com/HashExOfficial>*.

Thank you.

**Comment by Cryptocool1** [comment]
can you send your contract audit here?

**Comment by DLhugly** [comment]
Hi,

NFTY's native ERC-20 Token audit is located here:
https://github.com/HashEx/public_audits/blob/master/nfty/NFTY-audit-report.pdf

Wrapped BEP-20 NFTY on MultiSwap (Formerly AnySwap) bridge audit is located
here:
https://github.com/anyswap/Anyswap-Audit/blob/master/SlowMist/AnySwap%20CrossChain-Bridge%20Security%20Audit%20Report.pdf

Thank you.

**Pull request merged**
