### PR TITLE
Add InfinitiCoin (BEP20)

### PR DESCRIPTION
**Pull request by SufyanAkram16**
Adding info for BEP20 token 'InfinitiCoin'.

PR created by <a href="https://assets.trustwallet.com">TW Assets Management</a>

### CODE REVIEW

**Comment by Cryptocool1** [comment]
In order for the pull request to be approved, the submission has to meet several important requirements. For this request, it does not meet the following:

- at least 10000 token holders
- at least 15000 transactions

To know more about the token approval guidelines, please check this article: [How to Submit Token Logo](https://developer.trustwallet.com/listing-new-assets/requirements).

Feel free to re-open pull request once you meet those requirements.

**Comment by SufyanAkram16** [comment]
Thank you for your response regarding my token logo update submission. I understand that the requirements of having at least 10,000 token holders and 15,000 transactions have not been met for approval at this time.

I would like to inquire if there are any alternative options available to proceed with the logo update, or if there is a possibility to receive a refund for the 500 TWT tokens that were used for this submission.

I appreciate your guidance and look forward to your response.

Best regards,

**Comment by Cryptocool1** [comment]
As there is no refund (please take a look at the first message from the merge-fee-bot) you can come back to us once all requirements are met and we will reuse your payment in your next PR

**Comment by SufyanAkram16** [comment]
i created a new pr request while i did the payment here the new PR submission (#31667) the bot is waiting for payment can you pls help out?

**Pull request closed without merging**
