### PR TITLE
Updated with new logo

### PR DESCRIPTION
**Pull request by disnex**
This PR is being closed due to inactivity. If you wish to continue, please have us reopen the PR before sending your payment, or just create a new one.
Do NOT send payments for closed PR, as the fee may by lost!
  (48 vs. 48 hrs)

### CODE REVIEW

**Comment by cryptomanz** [comment]
can you send the official information about updating?

**Comment by disnex** [comment]
Providing screenshot from official Telegram group where it can be seen that poll for changing logo was done and profile picture of that same official telegram group is changed with new logo (one that is suggested in this commit): https://imgur.com/12pKw6R

Also sending link to CoinMarketCap where it can be seen that new logo is updated: https://coinmarketcap.com/currencies/charizardtoken/

**Comment by disnex** [comment]
Hi @cryptomanz , just wanted to quickly ask is there anything else that should be done from our side before merge is completed?

**Comment by disnex** [comment]
Hi @cryptomanz sorry for spamming.
I see bot closed this request, so I suppose payment is needed?
But I would like to ask since this is just update of already added token, for which payment was made once it was added, is payment needed now as well?

**Pull request closed without merging**
