### PR TITLE
Add HODL (BEP20)

### PR DESCRIPTION
**Pull request by HODLKONG**
Adding info for BEP20 token 'HODL'.

PR created by <a href="https://assets.trustwallet.com">TW Assets Management</a>

### CODE REVIEW

**Comment by cryptomanz** [comment]
• What is the purpose of this token? How will it benefit Trust Wallet users?
 • How is the token being distributed? Are you conducting an airdrop?
 • Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?
 • Is the token listed on a centralized/decentralized exchange?
 • Is a Smart Contract audit completed? Where can we find this information?

**Comment by HODLKONG** [comment]
Hello,

Thank you for the support. Please see the following:

• What is the purpose of this token? How will it benefit Trust Wallet users?

HODL Token is a passive income ecosystem which generates income for its holders in the form of reflections and BNB claims, with revenue originating from transaction taxes, physical merchandise sales such as HODLstore.io, NFT series launches, and much more as the project progresses down its roadmap, found at HODLtoken.net/roadmap 

Most of our users use Trust Wallet and  they are wanting to see the logo and pricing again within Trust Wallet. They use Trust Wallet to access our dApp for claiming BNB income at HODLtoken.net/claim

• How is the token being distributed? Are you conducting an airdrop?

This HODL Token constitutes a migration to a new contract, and was airdropped to all holders of HODL2.0. HODL2.0 was on Trust Wallet (with logo and pricing) and trading of it was disabled at the time of migration.

This can be confirmed from the old and new CoinMarketCap listings:

Old HODL2.0 (note the banner at the top of the webpage):
https://coinmarketcap.com/currencies/hodl-2-0/

New HODL:
https://coinmarketcap.com/currencies/hodl/

• Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?

No, this was a migration to a new contract, please see previous note above.

• Is the token listed on a centralized/decentralized exchange?

Yes, here are the direct links to the 4 CEX’s and 1 of the DEX’s HODL is on:

PancakeSwap
HODL/BNB
https://pancakeswap.finance/swap?outputCurrency=0x0e9766df73973abcfedde700497c57110ee5c301

Bitmart
HODL/USDT
https://www.bitmart.com/trade/en?symbol=HODL_USDT

Decoin
HODL/USDT
https://www.decoin.io/en/trade/HODL-USDT

LBank
HODL/USDT
https://www.lbank.info/exchange/hodl/usdt

Azbit
HODL/USDT
https://azbit.com/exchange/HODL_USDT


• Is a Smart Contract audit completed? Where can we find this information?

Here is an audit of this new contract which we migrated to:

https://hodltoken.net/wp-content/uploads/2021/11/solidity_security_audit_report.pdf

Let us know if you need anything else.

Thank you,
The HODL Team

**Comment by HODLKONG** [comment]
Hello,

The OLD “HODL” (which is not under our control since the old developer left) seems to be reflecting price information of our NEW “HODL,” even though it’s a different contract, and even though the old contract does not have a CMC listing anymore (our new HODL took over the old HODL’s CoinMarketCap listing a few weeks ago).

We don’t have access to the old developer’s GitHub login to issue a deprecation request on the old HODL.

Can you please deprecate the old HODL so that people are no longer confused by its presence and price?

Here is the OLD “HODL” contract which should be deprecated:

https://bscscan.com/token/0x0E3EAF83Ea93Abe756690C62c72284943b96a6Bc

As you can see within that link, there is a notice proving that the old contract migrated to a new one by now.

HODL2.0 should also be deprecated (it was an intermediate migration during transfer of ownership, we are on our third and final contract now). Can you also please deprecate HODL2.0?

Here is its contract, which also shows that it has been migrated to the new one by now:

https://bscscan.com/token/0x5788105375ecf7f675c29e822fd85fcd84d4cd86

Here is the new HODL which already correctly replaced the old HODL’s and is already properly listed on Trust Wallet and CoinMarketCap:

https://coinmarketcap.com/currencies/hodl/

Nothing more needs to be done with the new HODL. 

Thank you,
The HODL Team

**Comment by HODLKONG** [comment]
Hello, can someone please deprecate the old HODL Tokens as described below since no one has access to the GitHub account which created them? The project has migrated away from them.

**Pull request merged**
