### PR TITLE
Add MetaGamescoin (BEP20)

### PR DESCRIPTION
**Pull request by Mazyar60**
Adding info for BEP20 token 'MetaGamescoin'.

PR created by <a href="https://assets.trustwallet.com">TW Assets Management</a>

### CODE REVIEW

**Comment by Cryptocool1** [comment]
Please create new PR, follow doc https://developer.trustwallet.com/listing-new-assets/requirements
You may want to try our Assets app in beta; go to https://assets.trustwallet.com, log on with Github, enter contract ID, logo and some additional info, and it will create a PR for you.
See https://developer.trustwallet.com/listing-new-assets/repository_details

**Comment by Mazyar60** [comment]
Hi excuse me for delaying
I don't see your emails.
I paying now 2BNB for listing trust wallet cost
Thats true?
Please guide me
I need to list metagamescoin in trust wallet
Thank you for your support

**Comment by Cryptocool1** [comment]
Please don’t send any fee, see my instructions for new PR above

**Comment by Mazyar60** [comment]
Hi
I checked the Requirements and

I paying 500TWT
Send to your address bep2
Meme 27631

Please review and add MGC in trust wallet

**Comment by Mazyar60** [comment]
Hi
MGC Metagamescoin migrated to new address and new version is low
Transection but list in CMC and All trackers and 3 exchange and 3 DEX

Please review old and new addresses
Old is
0x3ade350e05f631f946b6d2b1a2deaaf95dcb243a

New is 0xbb73BB2505AC4643d5C0a99c2A1F34B3DfD09D11
 and list MGC in trust wallet because i check the requirements and pass the
methods
And pay 500TWT for listing fee

So please list MGC

**Comment by Mazyar60** [comment]
Hi
MGC Metagamescoin migrated to new address and new version is low
Transection but list in CMC and All trackers and 3 exchange and 3 DEX

Please review old and new addresses
Old is
0x3ade350e05f631f946b6d2b1a2deaaf95dcb243a

New is 0xbb73BB2505AC4643d5C0a99c2A1F34B3DfD09D11
 and list MGC in trust wallet because i check the requirements and pass the
methods
And pay 500TWT for listing fee

So please list MGC

**Comment by Mazyar60** [comment]
https://github.com/trustwallet/assets/pull/29959

This link about OMG listing to trust Wallet , this pull pa's night is
closed, @cryptomanz1 and @Cryptocool1 , please reopen and add OMG to trust

**Pull request closed without merging**
