### PR TITLE
Add ZEDXION (BEP20)

### PR DESCRIPTION
**Pull request by samagraph**
Adding info for BEP20 token 'ZEDXION'.

PR created by <a href="https://assets.trustwallet.com">TW Assets Management</a>

### CODE REVIEW

**Comment by samagraph** [comment]
#20718

**Comment by cryptomanz** [comment]
hello, how did you get 11k holders in 11 days?

**Comment by samagraph** [comment]
Hello,

We are an old company with more than 180K customer. this is our new token, we already are in trust wallet with our other token also.
this is just today report of one of our tokens.
https://coincodex.com/crypto/zedxion-token/
let me know if you need any more information.

Regards,
Saeed Mansory

----------------------------------------

**Comment by cryptomanz** [comment]
you get holders in 11 days, they are artificial. We will consider to add your token later, thanks for your interest.

**Comment by cryptomanz** [comment]
Screenshot 2022-05-30 at 14 25 26

**Comment by samagraph** [comment]
Dear sir,

we have paid the 5 BNB if you are not adding the token, kindly please return the payment.

Regards,

----------------------------------------

**Pull request closed without merging**
