### PR TITLE
Add Aquari (BEP20) and logo

### PR DESCRIPTION
**Pull request by M1s13Kk**
Aquari is a community governed cryptocurrency that aims to combine the Reflection and Passive Yield Farming tokenomics of coins like Safemoon along with the formation of a Non-Profit Organization tasked with the goal restoring all polluted bodies of water on Earth.
A24E35E7-C46A-47D4-9588-7C8EC06E98D4

*updated logo*

### CODE REVIEW

**Review by M1s13Kk — COMMENTED** [review]
final changes

**Comment by Cryptocool1** [comment]
Correction needed:
This is a BEp20 token, correct folder is blockchains/smartchain/assets. Please correct.

**Comment by M1s13Kk** [comment]
How

> Correction needed:
> This is a BEp20 token, correct folder is blockchains/smartchain/assets. Please correct.

How can i move files to different folder? Also i want to update a logo and a Json file?

**Comment by M1s13Kk** [comment]
We believe we fixed our application, possible to run checks again?

**Pull request merged**
