### PR TITLE
Add Silo Finance (SILO) (ERC20)

### PR DESCRIPTION
**Pull request by yoshuaus**
Adding info for ERC20 token 'Silo Finance (SILO)'.

PR created by <a href="https://assets.trustwallet.com">TW Assets Management</a>

### CODE REVIEW

**Comment by Cryptocool1** [comment]
Hello, could you answer these questions?
• What is the purpose of this token? How will it benefit Trust Wallet users?
 • How is the token being distributed? Are you conducting an airdrop?
 • Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?
 • Is the token listed on a centralized/decentralized exchange?
 • Is a Smart Contract audit completed? Where can we find this information?

**Comment by cryptomanz1** [comment]
As per our policy, brand new tokens are not included, there is a minimum requirement of 10,000 holder addresses and 15,000 transactions, in order to filter out scam tokens.
See the criteria at : https://developer.trustwallet.com/assets/requirements .

**Comment by yoshuaus** [comment]
• What is the purpose of this token? How will it benefit Trust Wallet users?

Token holders control all aspects of our decentralized lending protocol, like adding new money markets, changing borrowing factors, and many more.
We currently have over 23 markets. We work with DeFi projects closely to build deep borrow/lend markets for their governance and yield-bearing tokens. Those communities have an interest in owning our token and becoming active in governing our markets. Therefore, we are actively working to ensure our token is accessible to the larger DeFi community. Trust Wallet is central to that effort.

• How is the token being distributed? Are you conducting an airdrop? Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?

Silo conducted an IDO via Gnosis dutch auction; 102,000,000 of the 1 billion total supply were distributed and holds the record for the highest volume auction on gnosis. 

https://gnosis-auction.eth.link/#/auction?auctionId=98&chainId=1#topAnchor

Starting on December 1, 2021, and over the next four years, the remainder of the 1 billion tokens will be minted. The tokens have been allocated as follows:

Genesis Protocol-Owned Liquidity (10%) — Distributed in the public auction; claimable immediately after the auction
Community Treasury (45%) — Linear vesting for 3 years; controlled by the community through governance
Early Contributors (6.75%) — Linear vesting for 4 years with 6-month cliff starting after TGE
Founding Contributors (21.75%) — Linear vesting for 3 years with 6-month cliff starting after Token Generation Event (TGE)
Early Community Rewards (0.2%) — Airdropped to community members in January 2022
Early Investors & Early Advisors (6.30%) — Linear vesting for 2 years with 6-month lock starting after TGE
Future Contributors & Future Advisors (10%) — Linear vesting for 4 years with 1-year cliff starting after joining the DAO


• Is the token listed on a centralized/decentralized exchange?

We currently have a Balancer and Curve pool which we incentivize through our vlCVX holdings and that of fax which matches part of our incentives.

SILO/FRAX (Curve) - https://curve.fi/#/ethereum/pools/factory-crypto-22/deposit
SILO/WETH (Balancer) - https://app.balancer.fi/#/ethereum/pool/0x48607651416a943bf5ac71c41be1420538e78f87000200000000000000000327


• Is a Smart Contract audit completed? Where can we find this information?

Quanstamp and ABDK have fully audited all contracts. The team has also additionally formally verified the contracts with Certora.

Audits and Formal Verification: https://silopedia.silo.finance/security/audits-and-formal-verification

**Comment by yoshuaus** [comment]
Could we also by chance get our stablecoin XAI within this pull request? I was not able to add multiple assets through the UI, but I've attached the logo.png and info.json file below.

[0xd7C9F0e536dC865Ae858b0C0453Fe76D13c3bEAc.zip](https://github.com/trustwallet/assets/files/10108288/0xd7C9F0e536dC865Ae858b0C0453Fe76D13c3bEAc.zip)

**Comment by Cryptocool1** [comment]
> Could we also by chance get our stablecoin XAI within this pull request? I was not able to add multiple assets through the UI, but I've attached the logo.png and info.json file below.
> 
> [0xd7C9F0e536dC865Ae858b0C0453Fe76D13c3bEAc.zip](https://github.com/trustwallet/assets/files/10108288/0xd7C9F0e536dC865Ae858b0C0453Fe76D13c3bEAc.zip)

Hello, unfortunately no, we will only make an exception for this token. (Lack of holders.)

**Pull request merged**
