### PR TITLE
Add EverestCoin (BEP20)

### PR DESCRIPTION
**Pull request by everestgithub**
Adding info for BEP20 token 'EverestCoin'.

PR created by <a href="https://assets.trustwallet.com">TW Assets Management</a>

### CODE REVIEW

**Comment by ramsty** [comment]
Hi!
Could you answer some questions?
• What is the purpose of this token? How will it benefit Trust Wallet users?
• How is the token being distributed? Are you conducting an airdrop?
• Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?
• Is the token listed on a centralized/decentralized exchange?
• Is a Smart Contract audit completed? Where can we find this information?

**Comment by everestgithub** [comment]
Hi!

Thank you :)

* EverestCoin is a Play to Earn NFT Gaming Token, inspired by Mount
Everest. EVCoin tokens will be the governance token for anyone who intends
to play the Metaverse Game we're building. The game will reward players
through NFTs, Earned tokens (EVCoin tokens) in game, that could be traded
for real life money.

* There are currently no airdrops. The total supply of the token is
1,000,000,000,000, with more than 13% of the total supply already burnt.

* No, the tokens were not sold at an Initial Coin Offering (ICO), and no
presale was done. The token's launch is a fair launch.

* The token is created on decentralized exchange, but it has been listed on
two centralized exchanges (XT.com and Coinsbit)

* Yes, the smart contract audit has been completed. Here's the link to it
https://solidity.finance/audits/Everest

**Comment by Cryptocool1** [comment]
Hello,
Please follow the rules for adding token, your logo should be a full screen
Example:
https://community.trustwallet.com/t/how-to-submit-a-token-logo/3863

**Comment by everestgithub** [comment]
Hello,

Thank you for your response. The logo has been uploaded according to the
guidelines. Please, kindly share if there are any more specific corrections
required.

**Comment by Cryptocool1** [comment]
logo still the same

**Comment by ramsty** [comment]
Maybe this example will help
137116359-c2bb87b7-239a-4c8d-b54e-4a679c621186

**Comment by everestgithub** [comment]
Please, check if this is okay? Thanks!

[image: logo.png]

**Comment by Cryptocool1** [comment]
Снимок экрана 2021-11-02 в 20 12 30
cannot see the image

**Comment by everestgithub** [comment]
Please check if it shows now.

logo

**Comment by Cryptocool1** [comment]
your logo should be 256/256

**Comment by everestgithub** [comment]
Please, kindly check again. Thanks!

logo

**Comment by everestgithub** [comment]
Pls, does everything check out now? Thx

**Pull request merged**
