### PR TITLE
add Muverse Token logo and info

### PR DESCRIPTION
**Pull request by firefoxxy17**
add Muverse Token logo and info

### CODE REVIEW

**Comment by firefoxxy17** [comment]
Admin, could you plz help to add token logo for Muverse project, we want the logo to be revealed on metamask.
Muverse is just created in June 2022. $MU,the platform token, whose total supply is  billion and only 11 million is minted, and team will release token transparency report quarterly.  
Please check the info I submitted, thanks so much.

**Comment by Cryptocool1** [comment]
As per our policy, there is a minimum requirement of 10,000 holder addresses and 15,000 transactions, in order to filter out scam tokens.
See the criteria at : https://developer.trustwallet.com/assets/requirements .
- we require smart contract audit from reputable companies ( Certik, Techrate, Hacken, Dessert Finance)
please come back to us once all criteria are met

**Comment by Cryptocool1** [comment]
Make sure to mention this PR, so the fee can be reused

**Comment by firefoxxy17** [comment]
> Make sure to mention this PR, so the fee can be reused

ok, thanks a lot, I will contact you when we are audited.

**Pull request closed without merging**
