### PR TITLE
Add Littlebull (BEP20)

### PR DESCRIPTION
**Pull request by uygarali**
Adding info for BEP20 token 'Littlebull'.

PR created by <a href="https://assets.trustwallet.com">TW Assets Management</a>

### CODE REVIEW

**Comment by uygarali** [comment]
i send  1000 TWT with the memo 593 to the address bnb1tqq9llyr3dyjd559dha6z5r5etk3qfwk07m098

**Comment by Cryptocool1** [comment]
can't find contract on your website
please check

**Comment by uygarali** [comment]
hello when will our token littlebull logo trust wallet be visible

**Comment by Cryptocool1** [comment]
> hello when will our token littlebull logo trust wallet be visible

can you see my previous message?
"can't find contract on your website
please check"

**Comment by uygarali** [comment]
> > hello when will our token littlebull logo trust wallet be visible
> 
> can you see my previous message?
> "can't find contract on your website
> please check"

we have contract already website look at on smartcontract click there

**Comment by cryptomanz** [comment]
> > > hello when will our token littlebull logo trust wallet be visible
> > 
> > 
> > can you see my previous message?
> > "can't find contract on your website
> > please check"
> 
> we have contract already website look at on smartcontract click there

great!

**Pull request merged**
