### PR TITLE
Change SHON Token Logo BEP20

### PR DESCRIPTION
**Pull request by shontok**

### CODE REVIEW

**Comment by Cryptocool1** [comment]
Please create new PR, follow doc https://community.trustwallet.com/t/how-to-submit-a-token-logo/3863
You may want to try our new Assets app in beta; go to https://assets.trustwallet.com, log on with Github, enter contract ID, logo and some additional info, and it will create a PR for you.
See https://community.trustwallet.com/t/how-to-submit-a-token-logo-using-assets-app/82957.

**Comment by shontok** [comment]
Hi, 1000 TWT Payment Done This address: bnb1tqq9llyr3dyjd559dha6z5r5etk3qfwk07m098

**Comment by shontok** [comment]
Payment done sir

**Comment by shontok** [comment]
> Please create new PR, follow doc https://community.trustwallet.com/t/how-to-submit-a-token-logo/3863
> You may want to try our new Assets app in beta; go to https://assets.trustwallet.com, log on with Github, enter contract ID, logo and some additional info, and it will create a PR for you.
> See https://community.trustwallet.com/t/how-to-submit-a-token-logo-using-assets-app/82957.

Hello sir payment done

**Comment by shontok** [comment]
> Please create new PR, follow doc https://community.trustwallet.com/t/how-to-submit-a-token-logo/3863
> You may want to try our new Assets app in beta; go to https://assets.trustwallet.com, log on with Github, enter contract ID, logo and some additional info, and it will create a PR for you.
> See https://community.trustwallet.com/t/how-to-submit-a-token-logo-using-assets-app/82957.

request #11094 Payment Done 

But sir my request closed and again create a new pull request #11095 

So please my info verify please thank

**Comment by cryptomanz** [comment]
ok, fee will be reused
Contract is not in checksum format, should be 0x0b34D4A7C5BFc7004b9a193F8309523E99ca766e 
Please create new PR, follow doc https://community.trustwallet.com/t/how-to-submit-a-token-logo/3863
You may want to try our new Assets app in beta; go to https://assets.trustwallet.com, log on with Github, enter contract ID, logo and some additional info, and it will create a PR for you.
See https://community.trustwallet.com/t/how-to-submit-a-token-logo-using-assets-app/82957.

**Comment by shontok** [comment]
> ok, fee will be reused
> Contract is not in checksum format, should be 0x0b34D4A7C5BFc7004b9a193F8309523E99ca766e
> Please create new PR, follow doc https://community.trustwallet.com/t/how-to-submit-a-token-logo/3863
> You may want to try our new Assets app in beta; go to https://assets.trustwallet.com, log on with Github, enter contract ID, logo and some additional info, and it will create a PR for you.
> See https://community.trustwallet.com/t/how-to-submit-a-token-logo-using-assets-app/82957.

0x0b34d4a7c5bfc7004b9a193f8309523e99ca766e

**Comment by shontok** [comment]
sir I'm already pay 1000 TWT pull requests #11094
I'm first time add logo and again change add a new logo so verify my into ( I'm a new )

**Comment by shontok** [comment]
Hello sir answer please

**Comment by Cryptocool1** [comment]
> sir I'm already pay 1000 TWT pull requests #11094
> I'm first time add logo and again change add a new logo so verify my info ( I'm a new )

As mentioned above, fee can reused.
Please create new correct PR

**Comment by shontok** [comment]
> > sir I'm already pay 1000 TWT pull requests #11094
> > I'm first time add logo and again change add a new logo so verify my info ( I'm a new )
> 
> As mentioned above, fee can reused.
> Please create new correct PR

Hello sir how are you!

Sir I have a first time logo add apply so verified, but again change our logo so add my info I'm a pay 1000 TWT please verify me the project thank you so much

contact address

0x0b34D4A7C5BFc7004b9a193F8309523E99ca766e

0x0b34d4a7c5bfc7004b9a193f8309523e99ca766e

Same contact address

again extra token detail check please

{
"name": "ShonToken",
"type": "BEP20",
"symbol": "SHON",
"decimals": 18,
"website": "https://shontoken.com",
"description": "Shon token is the latest crypto-currency architecture that can be transacted through the Binance Smart Chain",
"explorer": "https://bscscan.com/token/0x0b34d4a7c5bfc7004b9a193f8309523e99ca766e",
"status": "active",
"id": "0x0b34d4a7c5bfc7004b9a193f8309523e99ca766e"
}

Logo PNG image
https://drive.google.com/file/d/1zf21O320HC6vr6TUBmnIe-jckZN91PWU/view?usp=sharing


Request No #11094

**Comment by ShonToken** [comment]
Please update logo and info please

**Comment by shontok** [comment]
Hello sir

**Comment by ShonToken** [comment]
> > sir I'm already pay 1000 TWT pull requests #11094
> > I'm first time add logo and again change add a new logo so verify my info ( I'm a new )
> 
> As mentioned above, fee can reused.
> Please create new correct PR

?

**Comment by shontok** [comment]
Hello

**Comment by ShonToken** [comment]
sir I'm already pay 1000 TWT pull requests #11094
I'm first time add logo and again change add a new logo so verify my info thank you

**Comment by ShonToken** [comment]
> > sir I'm already pay 1000 TWT pull requests #11094
> > I'm first time add logo and again change add a new logo so verify my info ( I'm a new )
> 
> As mentioned above, fee can reused.
> Please create new correct PR

sir I'm already pay 1000 TWT pull requests #11094
I'm first time add logo and again change add a new logo so verify my info thank you

**Pull request closed without merging**
