### PR TITLE
GDM Logo Update

### PR DESCRIPTION
**Pull request by goldmoneyGDM**
0x9fdb6a13bdcf1188fbafe5cd435a8b92a327d92e logo

### CODE REVIEW

**Comment by goldmoneyGDM** [comment]
0x9fdb6a13bdcf1188fbafe5cd435a8b92a327d92e Logo

**Comment by goldmoneyGDM** [comment]
sir please update GDM token logo

**Comment by Cryptocool1** [comment]
Hello, 
Check the name of your logo.png and correct it please.

**Comment by goldmoneyGDM** [comment]
0x9fdb6a13bdcf1188fbafe5cd435a8b92a327d92e logo

**Comment by goldmoneyGDM** [comment]
sir my project name goldmoney, my project contract address :0x9fdb6a13bdcf1188fbafe5cd435a8b92a327d92e

**Comment by Cryptocool1** [comment]
blockchains/smartchain/assets/0x9fdb6a13bdcf1188fbafe5cd435a8b92a327d92e logo.png 
this name is wrong, please check it

**Comment by goldmoneyGDM** [comment]
{
"name": "GOLDMONEY",
"website": "https://goldmoney.network/",
"description": "GoldMoney is a a protocol that unifies leading BSC protocols and blockchain infrastructure by standardising communication between them to create and execute complex financial transactions, while championing Privacy, Anonymity and Sovereignty.",
"socials": [
{
"name": "Twitter",
"url": "https://mobile.twitter.com/goldmoney_gdm"
},
{
"name": "Telegram",
"url": "https://t.me/GOLDMONEY_GROUP"
},
{
"name": "Telegram",
"url": "https://t.me/GOLDMONEY_ANNOUNCEMENT"
}
],
"explorer": "https://bscscan.com/token/0x9fdb6a13bdcf1188fbafe5cd435a8b92a327d92e",
"type": "BEP20",
"symbol": "GDM",
"decimals": 18,
"status": "active",
"id": "0x9fdb6a13bdcf1188fbafe5cd435a8b92a327d92e"
}

**Comment by Cryptocool1** [comment]
blockchains/smartchain/assets/0x9fdb6a13bdcf1188fbafe5cd435a8b92a327d92e/logo.png
rename it like that

**Comment by goldmoneyGDM** [comment]
IMG_20210502_140910
sir contract address /logo.png not working

**Comment by goldmoneyGDM** [comment]
0x9fdb6a13bdcf1188fbafe5cd435a8b92a327d92e logo
my computer  / not working please help

**Comment by goldmoneyGDM** [comment]
sir please update my token logo

**Comment by goldmoneyGDM** [comment]
Sir please update my token logo

**Comment by Cryptocool1** [comment]
Снимок экрана 2021-05-02 в 18 02 26
You need to put /  before logo.png

**Review by goldmoneyGDM — COMMENTED** [review]
0x9fdb6a13bdcf1188fbafe5cd435a8b92a327d92e logo

**Review by goldmoneyGDM — COMMENTED** [review]
0x9fdb6a13bdcf1188fbafe5cd435a8b92a327d92e logo

**Comment by goldmoneyGDM** [comment]
I can't put logo.png / before 
0x9fdb6a13bdcf1188fbafe5cd435a8b92a327d92e logo
Sir this is my project logo please update my logo

**Review by goldmoneyGDM — COMMENTED** [review]
- [ ] 
0x9fdb6a13bdcf1188fbafe5cd435a8b92a327d92e logo

**Comment by goldmoneyGDM** [comment]
@Cryptocool1 @catenocrypt @zachzwei @hexorx 
Hello sir please update my token logo

**Comment by catenocrypt** [comment]
Logo file has wrong naming, please follow guide
https://community.trustwallet.com/t/how-to-submit-a-token-logo/3863 

blockchains/smartchain/assets/0x9fdb6a13bdcf1188fbafe5cd435a8b92a327d92e logo.png

Error: No token files found. If you try to add/modify a token, check the name and location of your files! Logo file must be named exactly 'logo.png'. If you are not adding a token, ignore this message. (2 files in the PR)

**Comment by catenocrypt** [comment]
Placed files in the correct location.

**Pull request merged**
