### PR TITLE
Add Based Chad (ERC20)

### PR DESCRIPTION
**Pull request by basechad**
Adding info for ERC20 token 'Based Chad'.

PR created by <a href="https://assets.trustwallet.com">TW Assets Management</a>

### CODE REVIEW

**Comment by basechad** [comment]
Unable to swap between BEP20-TWT and BEP2-TWT on your app (error is "deprecated"), please advise.

**Comment by Cryptocool1** [comment]
As per our policy, brand new tokens are not included, there is a minimum requirement of 10,000 holder addresses and 15,000 transactions, in order to filter out scam tokens.
See the criteria at : https://developer.trustwallet.com/assets/requirements .

**Comment by jhl667** [comment]
Hi, we do meet the criteria of 10k holders and 15k transactions.  Could you expand on this please?

**Comment by basechad** [comment]
Could you give us a bit more info?  We believe the criteria have been met of 10k holders and 15k transactions.

**Comment by basechad** [comment]
@Cryptocool1 Could you give us a bit more info? We believe the criteria have been met of 10k holders and 15k transactions.

**Comment by Cryptocool1** [comment]
Hello, according to the explorer you put into info.json you have 500 holders

**Comment by basechad** [comment]
> Hello, according to the explorer you put into info.json you have 500 holders

Looks like I copy/pasted the wrong tab, oof.  The correct explorer link is:

https://basescan.org/token/0xecaf81eb42cd30014eb44130b89bcd6d4ad98b92

**Comment by basechad** [comment]
opened #28316

**Pull request closed without merging**
