### PR TITLE
Add Big Eyes ($BIG) (ERC20)

### PR DESCRIPTION
**Pull request by BigeyesAdmin**
Adding info for ERC20 token 'Big Eyes ($BIG)'.

PR created by <a href="https://assets.trustwallet.com">TW Assets Management</a>

### CODE REVIEW

**Comment by Cryptocool1** [comment]
Hello, how did you get more than 10k holders in 2 days?

**Comment by TeamAtBigeyes** [comment]
> w did you get more than 10k holders in 2 days?

Holders were from presale and they claimed once we have launched. That is why we were over 10.000 users in two days.

**Comment by BigeyesAdmin** [comment]
We had a presale that ended on the 3rd of June 2023, once we launched on Uniswap on the 15th of June 2023 we had over 10,000 people claim their tokens from the presale. This is the reason we had in 2 days over 10,000 holders.

**Comment by Cryptocool1** [comment]
Please answer these questions:
• What is the purpose of this token? How will it benefit Trust Wallet users?
 • How is the token being distributed? Are you conducting an airdrop?
 • Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?
 • Is the token listed on a centralized/decentralized exchange?
 • Is a Smart Contract audit completed? Where can we find this information?

**Comment by BigeyesAdmin** [comment]
Answers to your Questions:
• We are creating 819 Casino that will utilize the $BIG and also 20+ P2E games. Trust Wallet users will be holding and trading $BIG.
• Through a Claim function on the website, users that were from the presale get whitelisted and then claim their tokens straight to their wallet.
• We held a presale from our website, this is where holders initially bought the token before going live.
• Yes, Token is listed on Poloniex and LBank
https://poloniex.com/trade/BIG_USDT/?type=spot
https://www.lbank.com/en-US/trade/big_usdt/
• Yes, we have an audit from Solidity.Finance
https://solidity.finance/audits/BigEyes/

**Comment by BigeyesAdmin** [comment]
Is there anything else needed to push the Logo live on Trust Wallet?

**Comment by BigeyesAdmin** [comment]
Hello, I wanted to ask that after we answered the questions, why is it taking so long to approve the merge?

**Comment by BigeyesAdmin** [comment]
Hey, How long does it take to get the Logo updated on Trust Wallet?

**Comment by cryptomanz1** [comment]
Couple of hours.

**Pull request merged**
