### PR TITLE
Add Multi Functional Environmental Token (BEP20)

### PR DESCRIPTION
**Pull request by musacanminaz**
Adding info for BEP20 token 'Multi Functional Environmental Token'.

PR created by <a href="https://assets.trustwallet.com">TW Assets Management</a>

### CODE REVIEW

**Comment by musacanminaz** [comment]
Our total holder number is 3265 today there is airdrop bot in this number all numbers are correct you can check our page for details http://watcher.mfet.earth

**Comment by Cryptocool1** [comment]
As per our policy, there is a minimum requirement of 10,000 holder addresses and 15,000 transactions, in order to filter out scam tokens.
See the criteria at : https://developer.trustwallet.com/listing-new-assets/requirements .

**Comment by musacanminaz** [comment]
Hi, we have a strong project and have real transactions and holders.

We have all audits and a strong team

Please consider us this way

You can check our all links all 

https://links.mfet.earth

**Comment by musacanminaz** [comment]
Our pool is over 600.000 USD and its lock for 1 years

We have mobile apps and we are here over 1 year and getting strong every day.

We are not scam

**Comment by musacanminaz** [comment]
We talk you about MFET in Feb you check us and say that when CMC comes we will talk again.

**Pull request closed without merging**
