### PR TITLE
Add Wolverine (BEP20)

### PR DESCRIPTION
**Pull request by Psyconst**
Adding info for BEP20 token 'Wolverine'.

PR created by <a href="https://assets.trustwallet.com">TW Assets Management</a>

### CODE REVIEW

**Comment by ramsty** [comment]
Hi!
Please follow the rules for adding token, your logo should be a full screen
Example:
https://community.trustwallet.com/t/how-to-submit-a-token-logo/3863
137116359-c2bb87b7-239a-4c8d-b54e-4a679c621186

**Comment by ramsty** [comment]
Could you answer some questions?
• What is the purpose of this token? How will it benefit Trust Wallet users?
• How is the token being distributed? Are you conducting an airdrop?
• Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?
• Is the token listed on a centralized/decentralized exchange?
• Is a Smart Contract audit completed? Where can we find this information?

**Comment by Psyconst** [comment]
> Hi! Please follow the rules for adding token, your logo should be a full screen Example: https://community.trustwallet.com/t/how-to-submit-a-token-logo/3863 137116359-c2bb87b7-239a-4c8d-b54e-4a679c621186

Updated the logo. Thank you

**Comment by Cryptocool1** [comment]
Could you answer some questions?
• What is the purpose of this token? How will it benefit Trust Wallet users?
• How is the token being distributed? Are you conducting an airdrop?
• Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?
• Is the token listed on a centralized/decentralized exchange?
• Is a Smart Contract audit completed? Where can we find this information?

**Comment by Psyconst** [comment]
> Could you answer some questions? • What is the purpose of this token? 
$WLV aims to protect wildlife through our signature token – with benefits to our investors such as minimum taxes, Reflections and consistent marketing to increase the value of $WLV. Investors can rest assured that this is a token they can sleep on. We are looking to partner with, and eventually form our own charity dealing with the direct protection of wildlife – investors will benefit from this with the release of NFTs, which will be sold on AirNFTs, a BNB based NFT marketplace which benefits from low transaction taxes. Part of the received profits will be put into liquidity, increasing the value of all tokens held.

How will it benefit Trust Wallet users?
Trust wallet users who hold WLVR Token holders can gain passive income via the reflection mechanism.

 How is the token being distributed? Are you conducting an airdrop?
 We did a pre-sale on Pinksale Launchpad
 https://www.pinksale.finance/#/launchpad/0xd9EB04da0CA0913AcF4AB2BEb6a2945ABA3F13b2?chain=BSC 
 
• Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale? 
Yes, we did a pre-sale on Pinksale Launchpad
 https://www.pinksale.finance/#/launchpad/0xd9EB04da0CA0913AcF4AB2BEb6a2945ABA3F13b2?chain=BSC 
 
• Is the token listed on a centralized/decentralized exchange? 
The token is listed on a decentralized exchange.
https://pancakeswap.finance/swap?outputCurrency=0xBe6dE6b614b079236839404440E3e8867B5d6751

• Is a Smart Contract audit completed? Where can we find this information?
Yes, we passed the smart contract audit from BlockAudit. Link to the audit report as below
https://github.com/BlockAudit-Report/Wolverine

**Comment by Psyconst** [comment]
@Cryptocool1 @zachzwei @cryptomanz @ramsty

**Pull request merged**
