### PR TITLE
Added Vancat Egg Token Logo

### PR DESCRIPTION
**Pull request by vancattoken**

### CODE REVIEW

**Comment by vancattoken** [comment]
@catenocrypt @zachzwei @Cryptocool1

**Comment by Cryptocool1** [comment]
> @catenocrypt @zachzwei @Cryptocool1

correction needed
PR should include only 2 files

**Comment by vancattoken** [comment]
> > @catenocrypt @zachzwei @Cryptocool1
> 
> correction needed
> PR should include only 2 files

We have added only VCEGG logo image and its info.json. The other files are just updated on request by system check.

**Comment by vancattoken** [comment]
@catenocrypt @zachzwei @Cryptocool1

**Comment by vancattoken** [comment]
@catenocrypt @zachzwei @Cryptocool1

**Comment by vancattoken** [comment]
@catenocrypt @zachzwei @Cryptocool1

**Comment by vancattoken** [comment]
@catenocrypt @zachzwei @Cryptocool1

**Comment by Cryptocool1** [comment]
Couldn't find branch 'master' in remote 'github-desktop-vancattoken'. A common cause for this is if the PR author has deleted their branch or their forked repository.

**Comment by vancattoken** [comment]
> Couldn't find branch 'master' in remote 'github-desktop-vancattoken'. A common cause for this is if the PR author has deleted their branch or their forked repository.

No it has not deleted. @catenocrypt @zachzwei @Cryptocool1

**Comment by vancattoken** [comment]
https://github.com/vancattoken/assets/tree/469249ec051aad07ab31ded2925771184d266e06

@catenocrypt @zachzwei @Cryptocool1

**Comment by vancattoken** [comment]
@catenocrypt @zachzwei @Cryptocool1

**Comment by vancattoken** [comment]
Why did you remove logos for other tokens? If you merge this commit now, the other logos will be gone. @catenocrypt @zachzwei @Cryptocool1

**Comment by vancattoken** [comment]
@catenocrypt @zachzwei

**Comment by vancattoken** [comment]
@catenocrypt @zachzwei

**Comment by vancattoken** [comment]
@catenocrypt @zachzwei

**Comment by catenocrypt** [comment]
Merged master branch, to resolve conflicting files.
Status of this PR:
- Token VCEGG is being added, this looks OK  (0x1FF2a2c2DEAdb17B6Ba9949393d1406f4c61BFC9)
- Info file of token VANCAT is being removed.  Is this intentional?  If so, the corresponding logo should beremoved too.  If not, deletion should be removed (token ID 0x8597ba143AC509189E89aaB3BA28d661A5dD9830)

Please clarify.

**Comment by vancattoken** [comment]
> Merged master branch, to resolve conflicting files.
> Status of this PR:
> 
> * Token VCEGG is being added, this looks OK  (0x1FF2a2c2DEAdb17B6Ba9949393d1406f4c61BFC9)
> * Info file of token VANCAT is being removed.  Is this intentional?  If so, the corresponding logo should beremoved too.  If not, deletion should be removed (token ID 0x8597ba143AC509189E89aaB3BA28d661A5dD9830)
> 
> Please clarify.

Hello. We did not remove VANCAT info file. @Cryptocool1 did remove it before you. We think this was a mistake.

**Comment by vancattoken** [comment]
@catenocrypt @zachzwei

**Pull request merged**
