### PR TITLE
Add AFFINITY (BEP20)

### PR DESCRIPTION
**Pull request by Azacora**
Adding info for BEP20 token 'AFFINITY'.

PR created by <a href="https://assets.trustwallet.com">TW Assets Management</a>

### CODE REVIEW

**Comment by Azacora** [comment]
Token is already listed. Changing name, Token logo, and social links.

**Comment by Cryptocool1** [comment]
submission looks good, awaiting for fee payment

**Comment by Azacora** [comment]
> submission looks good, awaiting for fee payment

Is it too late to request tag to be changed to deflationary?

**Comment by Cryptocool1** [comment]
> > submission looks good, awaiting for fee payment
> 
> Is it too late to request tag to be changed to deflationary?

no it's not, you want to add it or change?

**Comment by Azacora** [comment]
> > > submission looks good, awaiting for fee payment
> > 
> > 
> > Is it too late to request tag to be changed to deflationary?
> 
> no it's not, you want to add it or change?

Add

**Pull request merged**
