### PR TITLE
Baby Cat Coin Logo

### PR DESCRIPTION
**Pull request by BabyCatCoin**
BabyCatCoin logo added to TWT.

### CODE REVIEW

**Comment by BabyCatCoin** [comment]
No. of holders is above 2500 now.

**Comment by cryptomanz** [comment]
hello,
what is the purpose of this token?

**Comment by BabyCatCoin** [comment]
> hello,
> what is the purpose of this token?

Baby Cat is cute but with a lot of MEOW! BabyCatCoin is a deflationary coin designed to become more scarce over time. All holders of Baby Cat Coin will earn more Baby Cat Coin that is automatically sent to their wallet by simply by holding Baby Cat Coins in their wallet. Watch the amount of Baby Cat Coin grow in your wallet as all holders automatically receive a 5% fee from every transaction that happens on the Binance Smart Chain. Baby Cat Coin could be the latest meme coin craze whose value is about to explode. The coin is allegedly created by fans of Elon Musk and aims to improve transaction speed and 'worship'. The coin has a block time of 5 seconds and generally cheaper gas rates compared to DOGE's 60 seconds.

**Comment by BabyCatCoin** [comment]
@catenocrypt @zachzwei

**Comment by BabyCatCoin** [comment]
@cryptomanz

**Comment by Cryptocool1** [comment]
This token will be on hold until CMC listing

**Comment by BabyCatCoin** [comment]
> This token will be on hold until CMC listing

This is not a mandatory for projects. CMC listing is not in list of TWT approval conditions.

**Comment by BabyCatCoin** [comment]
@catenocrypt @zachzwei @cryptomanz

**Comment by BabyCatCoin** [comment]
@catenocrypt @zachzwei @cryptomanz

**Comment by BabyCatCoin** [comment]
@catenocrypt @zachzwei @cryptomanz

**Comment by BabyCatCoin** [comment]
@catenocrypt @zachzwei @cryptomanz

**Comment by BabyCatCoin** [comment]
@catenocrypt @zachzwei @cryptomanz

**Comment by BabyCatCoin** [comment]
@catenocrypt @zachzwei @cryptomanz

**Comment by BabyCatCoin** [comment]
@catenocrypt @zachzwei @cryptomanz

**Comment by BabyCatCoin** [comment]
@Cryptocool1

**Comment by BabyCatCoin** [comment]
@catenocrypt @zachzwei @cryptomanz

**Comment by BabyCatCoin** [comment]
@catenocrypt @zachzwei @cryptomanz

**Comment by Cryptocool1** [comment]
please create new PR when your token will be listed on CMC
make sure to mention this PR so that fee can can be reused

**Pull request closed without merging**
