### PR TITLE
Decentral Games logo and info.json

### PR DESCRIPTION
**Pull request by scottdet**
This is a request to submit a token logo for Decentral Games.

### CODE REVIEW

**Comment by scottdet** [comment]
bit delayed in sending payment due to some maintenance on bnb it seems, here's the tx id:
https://explorer.binance.org/tx/420E25B692D4C3E0CDD82B4F740989952573D94978771EE82EC20D2A9C96CD4B

**Comment by catenocrypt** [comment]
As per our policy, brand new tokens are not included, there is a minimum requirement of 2500 holder addresses and 5000 transactions, in order to filter out scam tokens.
See the criteria at (mentioned in the first message by the bot): https://community.trustwallet.com/t/how-to-submit-a-token-logo/3863).
This token has below-limit usage yet (1400 holders). Closing PR for now. Please come back to us when all criteria are met.  Multi-chain and staking tokens may get special treatment, let us know if this is the case. 

https://etherscan.io/token/0xee06a81a695750e71a662b51066f2c74cf4478a0

**Comment by scottdet** [comment]
We are multi chain and having staking capability.

mainchain - 1,429
governance - 1,416
matic - 881
matic rewards contract - 1,109

total - 4,835

**Comment by catenocrypt** [comment]
Correction needed:  There are several fields missing from info.json.  Please check our guide https://community.trustwallet.com/t/how-to-submit-a-token-logo/3863

❌  Contract is not in checksum format, should be 0xEE06A81a695750E71a662B51066F2c74CF4478a0 (not 0xee06a81a695750e71a662b51066f2c74cf4478a0). Please rename it. You may need to rename to a temp name first, then to the checksum format, because lowercase-uppercase-only renames are often ignored by the Git client or the filesystem.
❌  Type field cannot be empty
❌  Symbol field cannot be empty
❌  Decimals field cannot be empty
❌  Description field cannot be empty
❌  Status field cannot be empty
❌  Id field cannot be empty

**Comment by scottdet** [comment]
Sorry for the multiple pushes, you were correct about the lowercase -> uppercase issue. Thanks for pointing that out - I believe should be good to go now, let me know if you need anymore information!

**Comment by catenocrypt** [comment]
Minor correction needed:
Field `symbol` is incorrectly `symbole`.  Please change.

**Comment by scottdet** [comment]
just wanted to check back here, anything else I need to change?

**Comment by scottdet** [comment]
pinging here for posterity

**Comment by scottdet** [comment]
Could someone inform me why this hasn't been merged? Do i need to re upload with a new pull to get this noticed. I believe everything is correct and we've paid quite a bit.

**Comment by scottdet** [comment]
@catenocrypt

**Comment by catenocrypt** [comment]
Correction needed: please change decimals to `18`as number, instead of `"18"`.

**Comment by scottdet** [comment]
fixed decimals, please note the above regarding token holders being over the required limit due to multiple chains and staking. thank you!

**Comment by catenocrypt** [comment]
Accepting submission.

**Pull request merged**
