### PR TITLE
Update Logo Token MAGO

### PR DESCRIPTION
**Pull request by maxgoat**

### CODE REVIEW

**Comment by Cryptocool1** [comment]
Correction needed:
 Logo file must be named exactly 'logo.png'.

**Comment by Cryptocool1** [comment]
As per our policy, brand new tokens are not included, there is a minimum requirement of 2500 holder addresses and 5000 transactions, in order to filter out scam tokens.
See the criteria at (mentioned in the first message by the bot): https://community.trustwallet.com/t/how-to-submit-a-token-logo/3863).

**Comment by maxgoat** [comment]
Where did I go wrong?

**Comment by Cryptocool1** [comment]
> Where did I go wrong?

can you please delete this file ? blockchains/smartchain/assets/0x452698Acacc695cEcA215B5e43525f6C36f240D3/logo

**Comment by maxgoat** [comment]
Okay. I will delete it now and please review it for me

**Comment by maxgoat** [comment]
I deleted it

**Pull request merged**
