### PR TITLE
Add Raze Network Token logo

### PR DESCRIPTION
**Pull request by razenetwork**

### CODE REVIEW

**Comment by catenocrypt** [comment]
As per our policy, brand new tokens are not included, there is a minimum requirement of 2500 holder addresses and 5000 transactions, in order to filter out scam tokens.
See the criteria at (mentioned in the first message by the bot): https://community.trustwallet.com/t/how-to-submit-a-token-logo/3863).
This token has no real usage yet (8 holders). Closing PR for now. Please come back to us when all criteria are met.  Multi-chain and staking tokens may get special treatment, let us know if this is the case. 

https://etherscan.io/token/0x5Eaa69B29f99C84Fe5dE8200340b4e9b4Ab38EaC

**Comment by razenetwork** [comment]
> As per our policy, brand new tokens are not included, there is a minimum requirement of 2500 holder addresses and 5000 transactions, in order to filter out scam tokens.
> See the criteria at (mentioned in the first message by the bot): https://community.trustwallet.com/t/how-to-submit-a-token-logo/3863).
> This token has no real usage yet (8 holders). Closing PR for now. Please come back to us when all criteria are met. Multi-chain and staking tokens may get special treatment, let us know if this is the case.
> 
> https://etherscan.io/token/0x5Eaa69B29f99C84Fe5dE8200340b4e9b4Ab38EaC

Now all criteria are met, please review again.

**Comment by razenetwork** [comment]
> As per our policy, brand new tokens are not included, there is a minimum requirement of 2500 holder addresses and 5000 transactions, in order to filter out scam tokens.
> See the criteria at (mentioned in the first message by the bot): https://community.trustwallet.com/t/how-to-submit-a-token-logo/3863).
> This token has no real usage yet (8 holders). Closing PR for now. Please come back to us when all criteria are met. Multi-chain and staking tokens may get special treatment, let us know if this is the case.
> 
> https://etherscan.io/token/0x5Eaa69B29f99C84Fe5dE8200340b4e9b4Ab38EaC

Now all criteria are met, please review again.

**Comment by catenocrypt** [comment]
Correction needed: Logo image is a bit too large, max size is 100 kbytes, please scale it down or compress it.

❌  Logo image too large, max 100 kB, current 114.144 kB

**Pull request merged**
