### PR TITLE
chore: added NGNT logo for BSC

### PR DESCRIPTION
**Pull request by timigod**
This PR is being closed due to inactivity. If you wish to continue, please have us reopen the PR before sending your payment.
Do NOT send payments for closed PR, as the fee may by lost!
  (123 vs. 60 hrs)

### CODE REVIEW

**Comment by catenocrypt** [comment]
As per our policy, brand new tokens are not included, there is a minimum requirement of 2500 holder addresses and 5000 transactions, in order to filter out scam tokens.
See the criteria at (mentioned in the first message by the bot): https://community.trustwallet.com/t/how-to-submit-a-token-logo/3863).
This token has no real usage yet (3 holders). Closing PR for now. Please come back to us when all criteria are met.  Multi-chain and staking tokens may get special treatment, let us know if this is the case. 

https://bscscan.com/token/0xB7d9905eDf8B7B093E3C74af8d6982D0F3d37762

**Comment by timigod** [comment]
@catenocrypt this is a multi-chain coin. I already added the logo for the Ethereum version a while ago. See the PR here https://github.com/trustwallet/assets/pull/869

**Comment by catenocrypt** [comment]
Reopened, as other version of token is already included.  Fee payment pending.

**Comment by timigod** [comment]
> This PR is being closed due to inactivity. If you wish to continue, please have us reopen the PR before sending your payment.
> Do NOT send payments for closed PR, as the fee may by lost!
> (73 vs. 60 hrs)

@catenocrypt PR has been closed by bot so I can't make payment just yet. Will do it as soon as it's open again.

**Comment by catenocrypt** [comment]
Reopening.  PR will be auto-closed again soon, but if fee is payed afterwards, it is OK, payment will be noticed next time we reopen.

**Comment by timigod** [comment]
> Reopening.  PR will be auto-closed again soon, but if fee is payed afterwards, it is OK, payment will be noticed next time we reopen.

Thank you. Payment has been made!

**Pull request merged**
