### PR TITLE
Add META logo and info

### PR DESCRIPTION
**Pull request by g909960614**
Add META logo and info

### CODE REVIEW

**Comment by g909960614** [comment]
What if I forget to fill in 19083 notes?

**Comment by g909960614** [comment]
Transferred again, please review

**Comment by Cryptocool1** [comment]
As per our policy, brand new tokens are not included, there is a minimum requirement of 10,000 holder addresses and 15,000 transactions, in order to filter out scam tokens.
See the criteria at : https://developer.trustwallet.com/assets/requirements .
please come back when all criteria are met

**Comment by g909960614** [comment]
Don't you need to pay for the next submission?

**Comment by Cryptocool1** [comment]
No, fee can be reused

**Comment by g909960614** [comment]
okay, thank you

**Comment by g909960614** [comment]
Hello, how can I submit again?

**Pull request closed without merging**
