### PR TITLE
Add logo and info for Oasis Network

### PR DESCRIPTION
**Pull request by tjanez**

### CODE REVIEW

**Comment by catenocrypt** [comment]
Let's wait until Oasis network is supported by Trust Wallet app first.

**Comment by tjanez** [comment]
> Let's wait until Oasis network is supported by Trust Wallet app first.

Hmm... this was requested by @hewigovens in https://github.com/trustwallet/wallet-core/pull/1258#discussion_r563426958?

**Comment by hewigovens** [comment]
@tjanez can you compress the logo? https://imageoptim.com/mac is a good tool to use

**Comment by catenocrypt** [comment]
All right.  Merging.

**Pull request merged**
