### PR TITLE
Add Sanji Inu (BEP20)

### PR DESCRIPTION
**Pull request by Sanji-Inu**
Adding info for BEP20 token 'Sanji Inu'.

PR created by <a href="https://assets.trustwallet.com">TW Assets Management</a>

### CODE REVIEW

**Comment by Cryptocool1** [comment]
your logo should be 256/256, please change

**Comment by Sanji-Inu** [comment]
can i email it to you

Vào Th 5, 21 thg 4, 2022 vào lúc 09:46 CryptoA ***@***.***>
đã viết:

**Comment by Sanji-Inu** [comment]
Here is the 256/256 size logo you requested

Looking forward to your help

Vào Th 5, 21 thg 4, 2022 vào lúc 09:46 CryptoA ***@***.***>
đã viết:

**Comment by Sanji-Inu** [comment]
> your logo should be 256/256, please change

Here is the 256/256 size logo you requested

Looking forward to your help

logo

**Comment by Cryptocool1** [comment]
Hello,

> can i email it to you Vào Th 5, 21 thg 4, 2022 vào lúc 09:46 CryptoA ***@***.***> đã viết:
> […](#)

Hello, you can only send messages here.

**Comment by cryptomanz** [comment]
• What is the purpose of this token? How will it benefit Trust Wallet users?
 • How is the token being distributed? Are you conducting an airdrop?
 • Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?
 • Is the token listed on a centralized/decentralized exchange?
 • Is a Smart Contract audit completed? Where can we find this information?

**Comment by Sanji-Inu** [comment]
> • What is the purpose of this token? How will it benefit Trust Wallet users? • How is the token being distributed? Are you conducting an airdrop? • Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale? • Is the token listed on a centralized/decentralized exchange? • Is a Smart Contract audit completed? Where can we find this information?

- What is the purpose of this token?
This token is created for the purpose of charity donation for needy children around the world. You can check out what we've been up to on twitter: https://twitter.com/sanjiinu_tw/

- How will it benefit Trust Wallet users?
Trust Wallet users in our community can track prices more easily and will attract more Trust Wallet users.

- How is the token being distributed?
100% of the total supply is distributed including:
       + Presale: 65.7%
       + Liquitdity Pools: 32.6%
       + Fees Preasle Unicrypt: 1.4%
       + Burn: 0.3%

- Are you conducting an airdrop?
I have never conducted an airdrop.

- Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?
I opened the token presale at Unicrypt here is the link: https://app.unicrypt.network/amm/pancake-v2/ilo/0x3c3383a34599359D9e5E57bc48D04c740a2B53e0

- Is the token listed on a centralized/decentralized exchange?
The token that has been listed on a decentralized exchange is Pancakeswap.

- Is a Smart Contract audit completed?
The smart contract has completed the audit

- Where can we find this information?
You can check the audit here: https://github.com/coinscope-co/audits/blob/main/sanji/audit.pdf

**Pull request merged**
