### PR TITLE
Add REGENT COIN (BEP20)

### PR DESCRIPTION
**Pull request by regentcoin12**
Adding info for BEP20 token 'REGENT COIN'.

PR created by <a href="https://assets.trustwallet.com">TW Assets Management</a>

### CODE REVIEW

**Comment by dunitech123** [comment]
We have more than 10,000 token holders and 15,000 transactions but still number of holders not checked error occurs please tell me reason of this error ?

**Comment by regentcoin12** [comment]
We have more than 10,000 token holders and 15,000 transactions but still number of holders not checked error occurs.please tell me the reason of this error ?

**Comment by Cryptocool1** [comment]
hello, how did you get 14k holders in less than 2 weeks?

**Comment by regentcoin12** [comment]
We are having community of 50k who supports all our activity related with the coin moreover the strong price trend has encouraged them to buy our token. As per our prediction the holding number may jump in near future.

**Comment by regentcoin12** [comment]
• What is the purpose of this token? How will it benefit Trust Wallet users?
Regent is a utility token.It has a clear purpose of access permission and governance.Token will also generate value for the ecosystem stakeholder as rewards.

• How is the token being distributed? Are you conducting an airdrop?
Initial coin Distribution is made through presale on pinksale. Please refer the link provided: https://www.pinksale.finance/launchpad/0x13C5353a71D1A601193F7e5C311E61077dA67C1b?chain=BSC
There is no airdrop attach with this token

• Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?
Yes,We have offered 18.45% of our token as presale on pinksale.

• Is the token listed on a centralized/decentralized exchange?
Regent token is listed on PancakeSwap decentralized exchange.

• Is a Smart Contract audit completed? Where can we find this information?
It is under process.

**Pull request closed without merging**
