### PR TITLE
Pr/1876

### PR DESCRIPTION
**Pull request by kolya182**
Close https://github.com/trustwallet/assets/pull/1876

### CODE REVIEW

**Comment by hyun999com** [comment]
https://github.com/hyun999com/assets/pull/1

**Comment by hyun999com** [comment]
Processing BNB 0.5 2020-04-19 19:41:26 주소:bnb1tqq9llyr3dyjd559dha6z5r5etk3qfwk07m098
Memo:1879

https://explorer.binance.org/tx/2A73EF831015E0492DDD00E80BCE05BC7CC659C45B255BD0647F8060C6DB89A0

**Comment by hyun999com** [comment]
https://github.com/trustwallet/assets/issues/1891

**Comment by hyun999com** [comment]
payment is done sir

**Comment by hyun999com** [comment]
Processing BNB 0.5 2020-04-19 19:41:26 주소:bnb1tqq9llyr3dyjd559dha6z5r5etk3qfwk07m098
Memo:1879

https://explorer.binance.org/tx/2A73EF831015E0492DDD00E80BCE05BC7CC659C45B255BD0647F8060C6DB89A0

ADD Groundcoin (GC) token logo Trust wallet

Token Name: Groundcoin
Token Symbol: GC
Token Decimals: 18
Token Initial Supply: 10,000,000,000
Token Contract: 0x157207df36cf1803399cca15cad867fd54514fde

0x157207df36cf1803399cca15cad867fd54514fde

**Comment by hyun999com** [comment]
ok

**Comment by hyun999com** [comment]
no appear logo when search "GC" , "Groundcoin "

**Comment by kolya182** [comment]
> no appear logo when search "GC" , "Groundcoin "

That was strange, just added, you should be able to see it in 30 minutes, apologize for inconvenience.

**Pull request merged**
