### PR TITLE
Add MMM (BEP20)

### PR DESCRIPTION
**Pull request by mmmscanofficial**
Adding info for BEP20 token 'MMM'.

PR created by <a href="https://assets.trustwallet.com">TW Assets Management</a>

### CODE REVIEW

**Comment by cryptomanz1** [comment]
• What is the purpose of this token? How will it benefit Trust Wallet users?
 • How is the token being distributed? Are you conducting an airdrop?
 • Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?
 • Is the token listed on a centralized/decentralized exchange?
 • Is a Smart Contract audit completed? Where can we find this information?

**Comment by mmmscanofficial** [comment]
• What is the purpose of this token? How will it benefit Trust Wallet users?
Ans. - it is a multi utility token, who build the system for entire own network, we have already huge number of community who want to trade, transfer & going p2p for numbers of transactions. 

• How is the token being distributed? Are you conducting an airdrop?
Ans. - it is our own existing network peoples at primary level we will be transits in thousand of peoples very soon.

• Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?
Ans. - No you can cross check our social platform or website there is no ico or airdrop.

• Is the token listed on a centralized/decentralized exchange?
Ans. - No

• Is a Smart Contract audit completed? Where can we find this information?
Ans. - Yes we have, will provide you (If needed)

**Comment by Cryptocool1** [comment]
Please send your audit here

**Comment by mmmscanofficial** [comment]
[ContractWolf_Audit_MMM.pdf](https://github.com/trustwallet/assets/files/10390794/ContractWolf_Audit_MMM.pdf)

**Comment by Cryptocool1** [comment]
How did you get 10k holders in 1 day?

**Comment by mmmscanofficial** [comment]
As we said, we have own existing community thousand of peoples, it is our community we are expanding upto 50K within week.

Thanks for your support.

**Comment by Cryptocool1** [comment]
Moreover, your amount of token holders and transactions are the same. 
it looks like you got holders artificially. ( the first transaction was 3 days ago and the last one 2 days ago.) 
-We require smart contract from the reputable companies ( Techrate, Certik, Dessert Finance, Hacken) 
- Your token should be listed on CoinMarketCap 
- Your project should have an activity and be not brand new
Feel free to come back to us once all criteria are met. Make sure to mention this Pull Request so the fee can me reused

**Comment by mmmscanofficial** [comment]
Ok, as we said all holders is our existing community, and you want to another audit report? but why, because it is also a reputable organization. 
How can we listed at this time at coinmarketcap, there is no mentioned as necessary to listing on cmc, so why cmc required?
Also can you explain about "be not brand new" as you mentioned above?

**Comment by Cryptocool1** [comment]
You can see all the requirements here: https://developer.trustwallet.com/assets/requirements

**Comment by mmmscanofficial** [comment]
Oh thanks, but we have fulfill your 90% requirement, can we put audit report from existing organization as you mentioned, after that you will be listed on trust wallet? 
is it ok

**Comment by Cryptocool1** [comment]
You should have audit from one of the companies I mentioned before and be listed on CMC

**Comment by Cryptocool1** [comment]
Please read carefully first message from the bot.

**Comment by mmmscanofficial** [comment]
Ok & again thanks for your valuable moments.
will update after fulfill all requirements.

**Comment by Cryptocool1** [comment]
No problem. Thanks for understanding

**Pull request closed without merging**
