### PR TITLE
Add logo for SafePizza Token

### PR DESCRIPTION
**Pull request by SafePizza**
We are adding our first logo for the SafePizza Token on the smart chain.

 SafePizza is a deflationary token. 4% tax on all transactions (0.8% gets burned forever, 1,2% distributed back to holders, 2% Automatically goes back into liquidity).

### CODE REVIEW

**Comment by Cryptocool1** [comment]
Correction needed: 
 Logo file must be named exactly 'logo.png'.

**Comment by SafePizza** [comment]
Updated logo file name to logo.png

**Comment by SafePizza** [comment]
Added info.json and logo named "logo.npg"

**Comment by SafePizza** [comment]
All checks have failed?
What should we do now?

**Comment by seo-fox** [comment]
@Cryptocool1 all errors has been fixed. Kindly merge

**Comment by SafePizza** [comment]
@Cryptocool1 the errors has been fixed please merge

**Comment by SafePizza** [comment]
Is here anyone who can merge it?
Everything is fixed and I would like to have this done…

**Comment by SafePizza** [comment]
How is this even possible? Paid a lot of money, errors are fixed since 4 days, nothing happens, no info or anything?! What is going on? Where is the problem? Is still anything wrong?

**Comment by SafePizza** [comment]
@catenocrypt @zachzwei @Cryptocool1 
All errors are fixed.
More than 7k holder and 25 transfers. Active on twitter and telegram. Fees are paid, could you please merge?

**Pull request closed without merging**
