### PR TITLE
Create 0x2e00CD222Cb42B616D86D037Cc494e8ab7F5c9a3

### PR DESCRIPTION
**Pull request by echapeta**
www.TrueGoldCoin.com Token

### CODE REVIEW

**Comment by kolya182** [comment]
Why do you need adding three ?. have you even had a chance look at contribution guide ?

**Comment by echapeta** [comment]
Hello,

 

We actually want to add: 

 

0xdcac1e6732cb951282e1cfc18b26adb5d1f995e2

 

And modify:

 

0xE51601f59A610DAc06868aa711A05e9a4e291256

 

Can you help us?

 

Thank You.

**Comment by kolya182** [comment]
@echapeta By modifying 0xE51601f59A610DAc06868aa711A05e9a4e291256 you mean deprecate and update to new contract 0xdcac1e6732cb951282e1cfc18b26adb5d1f995e2 ?

**Comment by echapeta** [comment]
Hello Mykola,

 

We issued the first contract , 0xe51601f59a610dac06868aa711a05e9a4e291256 , in jan 2018.

Today we found that we have no complete KYC of the token holders.

Then we issued another contract ,  0xdcac1e6732cb951282e1cfc18b26adb5d1f995e2 

And we will transfer the token holders meanwhile they provide their KYC info, along several weeks.

 

Then, we need both contracts active along that process.

In Trust, both tokens shoulf be active, but with different logos.

So far we know, in Trust we can only define the Logo, the rest of the info, Ticket and Name are taken from the contracts.

 

Colud you please help us? 

 

 

Thank You!

 

Eduardo G. Chapeta

**Comment by kolya182** [comment]
@echapeta I have made changes based on your description, please take a look if this is fine with you

**Comment by echapeta** [comment]
Hello Mykola,

 

How can I force the push of the updates to an already operating Trust wallet, in order to check ?

 

Thank You !!!!!

 

Eduardo.

**Pull request closed without merging**
