### PR TITLE
Add Doge Floki Coin (BEP20)

### PR DESCRIPTION
**Pull request by Dogeflokicoin**
Adding info for BEP20 token 'Doge Floki Coin'.

PR created by <a href="https://assets.trustwallet.com">TW Assets Management</a>

### CODE REVIEW

**Comment by Dogeflokicoin** [comment]
pls not closed

#14767

Can you check the payment?

https://explorer.binance.org/tx/DE5608A214FFB345FC9995DF5D112FEDD7AE95446DBEFC892501F0FF126124EC

**Comment by cryptomanz** [comment]
• What is the purpose of this token? How will it benefit Trust Wallet users?
 • How is the token being distributed? Are you conducting an airdrop?
 • Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?
 • Is the token listed on a centralized/decentralized exchange?
 • Is a Smart Contract audit completed? Where can we find this information?

**Comment by Dogeflokicoin** [comment]
What is the purpose of this token? How will it benefit Trust Wallet users?
• How is the token being distributed? Are you conducting an airdrop? YES
• Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale? NO
• Is the token listed on a centralized/decentralized exchange? YES Hotbit and Pancake 
https://auditrate.tech/images/pdf/DogeFlokiCoin_0xf9d6ddf44016953dbf7ab135a0f64d7a41870ede.pdf

**Comment by Dogeflokicoin** [comment]
https://www.hotbit.io/exchange?symbol=DOFI_nUSD

https://pancakeswap.finance/swap?inputCurrency=0xf9d6ddf44016953dbf7ab135a0f64d7a41870ede

**Pull request merged**
