### PR TITLE
Add MIKU (BEP20)

### PR DESCRIPTION
**Pull request by mikubsc**
Adding info for BEP20 token 'MIKU'.

PR created by <a href="https://assets.trustwallet.com">TW Assets Management</a>

### CODE REVIEW

**Comment by Cryptocool1** [comment]
• What is the purpose of this token? How will it benefit Trust Wallet users?
 • How is the token being distributed? Are you conducting an airdrop?
 • Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?
 • Is the token listed on a centralized/decentralized exchange?
 • Is a Smart Contract audit completed? Where can we find this information?

**Comment by mikubsc** [comment]
> • What is the purpose of this token? How will it benefit Trust Wallet users? • How is the token being distributed? Are you conducting an airdrop? • Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale? • Is the token listed on a centralized/decentralized exchange? • Is a Smart Contract audit completed? Where can we find this information?

Hello,

MIKU is developing a token locker and NFT collections that will generate revenue for the token holders.
All tokens were added to PCs liquidity
It was an ICO
Listed on PancakeSwap
You can find our audit here https://novos.tech/MIKU_Token_Audit.html

Thank you

**Comment by Cryptocool1** [comment]
Are you conducting an airdrop? how did you get 10k holders in less that one month?

**Comment by mikubsc** [comment]
> Are you conducting an airdrop? how did you get 10k holders in less that one month?

Hi Trustwallet Team,

We've conducted a lot of marketing focused on Asian markets. Some of it involved airdropping a small number of tokens during different social media contests, however we never airdropped to people that didn't ask for it. While, I don't have an exact number of people that received airdrops, it was not that many. You can also see that we had over 35 thousand DEX transactions in that month.

Thanks for reviewing our application and best regards

**Comment by mikubsc** [comment]
> • What is the purpose of this token? How will it benefit Trust Wallet users? • How is the token being distributed? Are you conducting an airdrop? • Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale? • Is the token listed on a centralized/decentralized exchange? • Is a Smart Contract audit completed? Where can we find this information?

Hi,

Is there anything else we need to provide?

**Comment by trastvolt** [comment]
mikubsc:br0808-001614

**Comment by trastvolt** [comment]
c6d65d087e18360a6c887350797919b070650e9c

**Comment by cryptomanz1** [comment]
are you listed on CoinMarketCap?

**Comment by mikubsc** [comment]
> are you listed on CoinMarketCap?

Hi cryptomanz1 

Yes, we are listed on cmc: https://coinmarketcap.com/currencies/miku/

**Pull request merged**
