### PR TITLE
BabySharkTank (BASHTANK) Logo/info update.

### PR DESCRIPTION
**Pull request by Babysharktank**
I believe everything should be configured correctly. just hit 2500 organic users this evening :)

### CODE REVIEW

**Comment by Babysharktank** [comment]
I've been chasing a , in the json, it's 4 am. I apologize for the spam. I'll get fee to you shortly.

**Comment by Babysharktank** [comment]
Sorry for the duplicate folder and many commits. 4 am was not the time to do this, hah.

**Comment by catenocrypt** [comment]
Website not found.  Please explain or change.

image

**Comment by mdfennell94** [comment]
New website is Bashtank.com

**Comment by Babysharktank-official** [comment]
Website has been updated in latest pull request

**Comment by babysharktankofficial** [comment]
lost access to this account. Correct email is: Bashtank.com

**Review by babysharktankofficial — CHANGES_REQUESTED** [review]
We lost access to this account, so made new one and have made all changes to pull request #7934

**Comment by Cryptocool1** [comment]
> We lost access to this account, so made new one and have made all changes to pull request #7934

So, Can I close this PR?

**Comment by babysharktankofficial** [comment]
the logo is showing but the price isnt

**Comment by mdfennell94** [comment]
Yes that is correct, the other pull request has already merged

**Pull request closed without merging**
