### PR TITLE
Add BABYPEPE logo & info

### PR DESCRIPTION
**Pull request by babypepebnb**
Add BABYPEPE logo& info to trustwallet

### CODE REVIEW

**Comment by babypepebnb** [comment]
https://explorer.bnbchain.org/tx/B9D16904377CE13B81D40194854D982DDD84DF4655A116E7096CA135D85A3B4B

The payment was made yesterday!

**Comment by Cryptocool1** [comment]
Hello!
 Please provide us with some details 
• What is the purpose of this token? How will it benefit Trust Wallet users?
 • How is the token being distributed? Are you conducting an airdrop?
 • Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?
 • Is the token listed on a centralized/decentralized exchange?
 • Is a Smart Contract audit completed? Where can we find this information?

**Comment by babypepebnb** [comment]
• What is the purpose of this token? How will it benefit Trust Wallet users?
Baby Pepe is a meme coin on the BSC chain. It's following the Pepe narrative. With our utility, the daily Baby Pepe Roulette, all holders have the opportunity to win tokens. As for now, we're counting over 23.000 holders on DEX and thousands of holders on Bitmart. Our holders want accurate information about Baby Pepe on their main decentralized wallet: TrustWallet. 

• How is the token being distributed? Are you conducting an airdrop?
Tokens can be bought/sold on Pancakeswap (DEX) and Bitmart (CEX)

• Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?
Baby Pepe had a public presale on PinkSale. The valuation (market cap) was $100.000 and the hard cap(max total contribution) was 150BNB.

• Is the token listed on a centralized/decentralized exchange?
Yes. Pancakeswap and Bitmart

• Is a Smart Contract audit completed? Where can we find this information?
Baby Pepe got audited by CERTIK. https://skynet.certik.com/projects/babypepe

**Comment by babypepebnb** [comment]
bumb

**Comment by babypepebnb** [comment]
@Cryptocool1

**Pull request merged**
