### PR TITLE
Adding BEP20 | DNGN

### PR DESCRIPTION
**Pull request by tbcmart**

### CODE REVIEW

**Comment by tbcmart** [comment]
250 TWT paid using Memo 5752.

please confirm payment and next line of action

**Comment by catenocrypt** [comment]
Can you double check the toke ID?  I cannot see this on etherscan

https://etherscan.io/token/0x082484f624381f8bdf82e86fcedccff280eb2942

**Comment by tbcmart** [comment]
I have added Binance token in Ethereum. Could you please help me to fix this.

**Comment by tbcmart** [comment]
That is the url.
https://bscscan.com/token/0xc0ad993080651b49069277d994de344b400b54f1

**Comment by catenocrypt** [comment]
Thanks for the fixes. The current circulation of this token is still very low (31 holder addresses).  Is an ethereum version of this token already existing?  Because in that case we can consider combined circulation.  If so, please specify the explorer page of the ERC20 version of the token.

https://bscscan.com/token/0xc0Ad993080651b49069277D994de344B400B54f1

**Comment by tbcmart** [comment]
@catenocrypt please check

**Comment by tbcmart** [comment]
Any update?

**Comment by catenocrypt** [comment]
This submission wants to add the BEP20 Digital Naira token. But its current circulation of this token is very low (16 holder addresses). We have a limit of minimum 2500 holder addresses and 5000 transaction.  Until those numbers are reached, we will not add this token.
Except if this token has already an ERC20 version in circulation, in that case circulation is considered combined.
Please clarify.

https://bscscan.com/token/0xc0Ad993080651b49069277D994de344B400B54f1

**Comment by tbcmart** [comment]
Does this mean that I have to Pay TWT again to have DNGN added to Trust
Wallet default token list?

**Comment by catenocrypt** [comment]
No, we can reopen this when circulation requirement is reached, no need to pay fee again.

**Pull request closed without merging**
