### PR TITLE
Add Marvin Inu (BEP20)

### PR DESCRIPTION
**Pull request by marvininueth**
Adding info for BEP20 token 'Marvin Inu'.

PR created by <a href="https://assets.trustwallet.com">TW Assets Management</a>

### CODE REVIEW

**Comment by Cryptocool1** [comment]
• What is the purpose of this token? How will it benefit Trust Wallet users?
 • How is the token being distributed? Are you conducting an airdrop?
 • Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?
 • Is the token listed on a centralized/decentralized exchange?
 • Is a Smart Contract audit completed? Where can we find this information?

**Comment by marvininueth** [comment]
Hi!

1.  Here is our whitepaper that explain better our usecase:
https://marvininueth.com/wp-content/uploads/2021/12/RocketPaper-2.0-Marvininu-1-1-1.pdf
2. We are not doing airdrops. We have many months ago and we are not in ETH
and BSC networks.
3. Yes we did a presale.
4. We are listed in Pancekeswap and as well Flooz.trade can be used to buy
Marvin Inu.
5. Our Audit can be found here: https://www.certik.com/projects/marvin-inu

**Comment by marvininueth** [comment]
@Cryptocool1 Let us know if you need anything else from us :)

**Comment by marvininueth** [comment]
We have done as well our Certik Audit.

https://www.certik.com/projects/marvin-inu

**Pull request merged**
