### PR TITLE
Add STAX (TRC20)

### PR DESCRIPTION
**Pull request by starsxplatform**
Adding info for TRC20 token 'STAX'.

PR created by <a href="https://assets.trustwallet.com">TW Assets Management</a>

### CODE REVIEW

**Comment by starsxplatform** [comment]
we have completed our payment in #17884 PR
and here is our smart contract audit
[StarsX (STAX).pdf](https://github.com/trustwallet/assets/files/8008581/StarsX.STAX.pdf)

**Comment by cryptomanz** [comment]
As per our policy, brand new tokens are not included, there is a minimum requirement of 5,000 holder addresses and 10,000 transactions, in order to filter out scam tokens.
See the criteria at : https://developer.trustwallet.com/assets/requirements .

**Comment by starsxplatform** [comment]
dear @cryptomanz in the last PR i talk about this we are launching our exchange now and you can check your platform this is for NFT trading and we need to have a logo on trust please do a favor for us also you are said waiting for an audit then that's ok 
please let me know if anything i can do
thank you for your support

**Comment by cryptomanz** [comment]
awaiting for smart contract audit. on hold for now

**Comment by starsxplatform** [comment]
[StarsX (STAX).pdf](https://github.com/trustwallet/assets/files/8010131/StarsX.STAX.pdf)
Here is our audit

**Comment by Cryptocool1** [comment]
is your token listed on CoinMarketCap?

**Comment by starsxplatform** [comment]
Yes we yave submit starx on cmc but for the higtraffic on cmc it take tome but surely will be list on a few weeks later

**Comment by Cryptocool1** [comment]
Please see our Listing Acceptance Guidelines here: https://developer.trustwallet.com/assets/requirements
- Token should be listed on price tracking sites like CoinmarketCap
- Minimum 5,000 token holders and 10,000 transactions (Airdrop tokens excluded).

**Pull request closed without merging**
