### PR TITLE
Logo & Info For XTrade (XTRA)

### PR DESCRIPTION
**Pull request by Brewin95**
Logo & Info For XTrade (XTRA)

### CODE REVIEW

**Comment by Brewin95** [comment]
https://explorer.binance.org/tx/BFCB94B970EF61EB4E025DA779859D411AB792D90FA703C5088D6D9D3AA88187

Paid

**Comment by Cryptocool1** [comment]
Correction needed:  Logo file must be named exactly 'logo.png'

**Comment by Cryptocool1** [comment]
correction needed:
Field 'research' is not needed, please remove it.

**Comment by Cryptocool1** [comment]
As per our policy, brand new tokens are not included, there is a minimum requirement of 2500 holder addresses and 5000 transactions, in order to filter out scam tokens.
See the criteria at (mentioned in the first message by the bot): https://community.trustwallet.com/t/how-to-submit-a-token-logo/3863).

**Comment by Brewin95** [comment]
Is it possible to have that waivered for an extra fee? XTrade is taking off and already trading for 66 Cents per token. my investors would like it to have a logo in the wallet

**Comment by Cryptocool1** [comment]
Please come back to us when all criteria are met.
When creating a new PR make sure to mention this PR, so that we can see that fee has been paid already here.

**Pull request closed without merging**
