### PR TITLE
Add Primex Token logo and info

### PR DESCRIPTION
**Pull request by primexdev**
Add Primex Token logo and info in order to be our logo in pancakeswap

### CODE REVIEW

**Comment by Cryptocool1** [comment]
hello
• What is the purpose of this token? How will it benefit Trust Wallet users?
 • How is the token being distributed? Are you conducting an airdrop?
 • Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?
 • Is the token listed on a centralized/decentralized exchange?
 • Is a Smart Contract audit completed? Where can we find this information?

**Comment by cryptomanz** [comment]
no answer yet
please create new PR when you will be ready to answer the questions above 
Make sure to mention this PR, so that we can see that fee has been paid already here.

**Comment by Cryptocool1** [comment]
can you please add links to your PR?
example: https://developer.trustwallet.com/add_new_asset#info-json-contents

**Comment by primexdev** [comment]
Hi, Hope you are doing well, At the moment we are working on the Certik requirement to get the certificate for Primex Token. We have to change little things on our token and we may need to change our smart contract address. I am just wondering if we change our smart contract address can we say to you to edit and change it in TrustWallet?

**Pull request merged**
