### PR TITLE
Add Mega Lottery (MLR) (TRC21)

### PR DESCRIPTION
**Pull request by lottoxsmbcom**
Adding info for TRC21 token 'Mega Lottery (MLR)'.

PR created by <a href="https://assets.trustwallet.com">TW Assets Management</a>

### CODE REVIEW

**Comment by lottoxsmbcom** [comment]
We have more than 16000 holders, you can check it at https://tomoscan.io/token/0x5080781e91237b6D7f026D5306b7233e26Cd6C16#holders

**Comment by lottoxsmbcom** [comment]
Ok, wait me, Binance delay withdraw on Bep2, can we pay by TWT on BEP20? give me address for BEP20 Smartchain

**Comment by lottoxsmbcom** [comment]
Done payment, txt hash is 2C97AB8F8438345E03037D60F3E98D849F39A71DD4E40020AA6A36F84C1745D3

**Review by tiagofeiodapoha — COMMENTED** [review]
H

**Pull request merged**
