### PR TITLE
Add Tipcoin (TIP) (ERC20)

### PR DESCRIPTION
**Pull request by Tipcoineth**
Adding info for ERC20 token 'Tipcoin (TIP)'.

PR created by <a href="https://assets.trustwallet.com">TW Assets Management</a>

### CODE REVIEW

**Comment by Cryptocool1** [comment]
As per our policy, there is a minimum requirement of 10,000 holder addresses and 15,000 transactions, in order to filter out scam tokens.
See the criteria at : https://developer.trustwallet.com/listing-new-assets/requirements .

**Comment by Cryptocool1** [comment]
Feel free to come back to us once all criteria are met

**Comment by Tipcoineth** [comment]
Why do I see that there are still many tokens that don't need to reach that threshold?

**Comment by Tipcoineth** [comment]
Please check again, we are qualified.

**Comment by Tipcoineth** [comment]
> Feel free to come back to us once all criteria are met

Please check again, we are qualified.

**Comment by Cryptocool1** [comment]
So yesterday you had 3k holders and now you show more than 15k? How is that possible?

**Comment by Tipcoineth** [comment]
> So yesterday you had 3k holders and now you show more than 15k? How is that possible?

We create an airdrop program for users

**Comment by Tipcoineth** [comment]
> So yesterday you had 3k holders and now you show more than 15k? How is that possible?

hey, can you tell me, will our Token have its logo updated?

**Comment by Cryptocool1** [comment]
if you read our criteria carefully, we do not accept airdropped tokens.
You should have 7k organic holders. 
min hold for now.

**Comment by Tipcoineth** [comment]
> if you read our criteria carefully, we do not accept airdropped tokens. You should have 7k organic holders. min hold for now.

Are you trying to make things difficult for me?

**Comment by Cryptocool1** [comment]
See all criteria here: https://developer.trustwallet.com/listing-new-assets/requirements

**Comment by Tipcoineth** [comment]
> See all criteria here: https://developer.trustwallet.com/listing-new-assets/requirements

I tried everything, it also took me a fee to resubmit a new request .

**Pull request closed without merging**
