### PR TITLE
Add upShib (BEP20)

### PR DESCRIPTION
**Pull request by Innodej2**
Adding info for BEP20 token 'upShib'.

PR created by <a href="https://assets.trustwallet.com">TW Assets Management</a>

### CODE REVIEW

**Comment by Cryptocool1** [comment]
Correction needed:
PR should include only 2 files

**Comment by Innodej2** [comment]
@Cryptocool1 @catenocrypt @zachzwei 
Please kindly show me how to delete those other files that are not needed

Your kind response is highly appreciated.

**Comment by Cryptocool1** [comment]
> @Cryptocool1 @catenocrypt @zachzwei
> Please kindly show me how to delete those other files that are not needed
> 
> Your kind response is highly appreciated.

Hello,
If you can't delete files in the PR, you may open a new PR. Make sure to mention this PR, so that we can see that fee has been paid already here.
You may want to try our new Assets app in beta; go to https://assets.trustwallet.com, log on with Github, enter contract ID, logo and some additional info, and it will create a PR for you.
See https://community.trustwallet.com/t/how-to-submit-a-token-logo-using-assets-app/82957.

**Comment by Innodej2** [comment]
Ok,
Thanks a lot

    On Thursday, May 20, 2021, 07:34:44 AM GMT+1, CryptoA ***@***.***> wrote:  
 
 



@Cryptocool1 @catenocrypt @zachzwei
Please kindly show me how to delete those other files that are not needed

Your kind response is highly appreciated.


Hello,
If you can't delete files in the PR, you may open a new PR. Make sure to mention this PR, so that we can see that fee has been paid already here.
You may want to try our new Assets app in beta; go to https://assets.trustwallet.com, log on with Github, enter contract ID, logo and some additional info, and it will create a PR for you.
See https://community.trustwallet.com/t/how-to-submit-a-token-logo-using-assets-app/82957.

**Pull request merged**
