### PR TITLE
Add UniCore

### PR DESCRIPTION
**Pull request by QuantSoldier**
https://uvault.finance/

https://etherscan.io/address/0x5506861bbb104baa8d8575e88e22084627b192d8

https://info.uniswap.org/token/0x5506861bbb104Baa8d8575e88E22084627B192D8

### CODE REVIEW

**Review by Iamdeadlyz — CHANGES_REQUESTED** [review]
Please resize the logo to `256px by 256px`
You can use https://picresize.com/

**Comment by QuantSoldier** [comment]
Updated in most recent commit. Thanks. https://github.com/trustwallet/assets/pull/4529/commits/fa51168a3d48d7ea6fa94ae9d596d300a1e1e623

**Review by Iamdeadlyz — COMMENTED** [review]
As per our policy, brand new tokens are not included. There is a minimum requirement of 500 holder addresses and 1000 transactions in order to filter out scam tokens. See the criteria at (mentioned in the first message by the bot): https://community.trustwallet.com/t/how-to-submit-a-token-logo/3863#how-to-get-approved

This token has below-limit usage yet. This pull request will be put on hold. Please come back to us when all criteria are met. (We have to see it personally that it reached the requirements, even though there is a staking program)
https://etherscan.io/token/0x5506861bbb104Baa8d8575e88E22084627B192D8 (302, 11502).

**Comment by Iamdeadlyz** [comment]
Let us know once you have reached the requirements so we can re-open this PR.

**Pull request closed without merging**
