### PR TITLE
Add Pepe Coin (BEP20)

### PR DESCRIPTION
**Pull request by OPEPEBSC**
Adding info for BEP20 token 'Pepe Coin'.

PR created by <a href="https://assets.trustwallet.com">TW Assets Management</a>

### CODE REVIEW

**Comment by Cryptocool1** [comment]
Hello, we are not accept brand new tokens. You token is less than 1 day old.

**Comment by Cryptocool1** [comment]
How did you get more than 10k holders in less than 24hours?

**Comment by OPEPEBSC** [comment]
0 tax and our presale only was rise 1600 holder 
https://www.pinksale.finance/launchpad/0x83C86f3384C7D85D7d8dA1C3AF606cA97910C661?chain=BSC
in just 10 hour presale  we get 1600 holder 
and our token 0 tax

**Comment by OPEPEBSC** [comment]
we launch since 18 hour anyway no problem to wait if you not trust us  but check presale was got 1600 holder

**Comment by OPEPEBSC** [comment]
and we trend  since yesterday 
https://www.dextools.io/app/en/bnb/pair-explorer/0x1de7c7156d8f5f52ba5191393a5590636e6676d2
https://www.dexview.com/bsc/0xb46584e0efdE3092e04010A13f2eAe62aDb3b9F0

**Comment by Cryptocool1** [comment]
> we launch since 18 hour anyway no problem to wait if you not trust us but check presale was got 1600 holder

• What is the purpose of this token? How will it benefit Trust Wallet users?
 • How is the token being distributed? Are you conducting an airdrop?
 • Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?
 • Is the token listed on a centralized/decentralized exchange?
 • Is a Smart Contract audit completed? Where can we find this information?

**Comment by OPEPEBSC** [comment]
• What is the purpose of this token? How will it benefit Trust Wallet users? meme token and we will have swap and farm and staking and we can give airdrop for trust wallet user if you  want to  increase and spread our token  
• How is the token being distributed? Are you conducting an airdrop? not yet but we can airdrp trust wallet users to all know about us 
• Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale? yes was presale we rise 329 bnb with max wallet 0.25 bnb and we got 1600 holder from sale 
• Is the token listed on a centralized/decentralized exchange? pancakeswap 
• Is a Smart Contract audit completed? Where can we find this information?  ca very clean and audit and here the links
https://github.com/AnalytixAudit/Solidity/blob/main/20230517_Analytix%20Audit_Pepe%20Coin_Audit.pdf
and smart contract vey clean and can check by go plus labs
https://gopluslabs.io/token-security/56/0xb46584e0efde3092e04010a13f2eae62adb3b9f0

**Comment by OPEPEBSC** [comment]
i answer  and wait your reply

**Comment by Cryptocool1** [comment]
As we are not adding brand new tokens you should wait.

**Comment by OPEPEBSC** [comment]
no problem

**Comment by OPEPEBSC** [comment]
i just want you check its i goot 1k holder in just 2 hour

check volume on dextools
so i think its fair to give me the logo

**Comment by OPEPEBSC** [comment]
look now we are trend over world and holder increase by 2000 
so give chance sir we are doing good jop
our volume over 7M Dollar here the proof 
https://www.dextools.io/app/en/bnb/pair-explorer/0x1de7c7156d8f5f52ba5191393a5590636e6676d2

**Comment by OPEPEBSC** [comment]
+14K holder 
please give me chance my dear

**Comment by OPEPEBSC** [comment]
https://bscscan.com/token/0xb46584e0efde3092e04010a13f2eae62adb3b9f0

check dextools and cmc 
we are trend and best volume in all BSC
now we are morer than 15 holder

**Comment by OPEPEBSC** [comment]
@Cryptocool1 @cryptomanz1 @natedaiger @hexorx take a look on my case please

**Comment by OPEPEBSC** [comment]
please check again now we are over than 16K

**Comment by OPEPEBSC** [comment]
Holders:
16,662 addresses
Transfers:
90,565

https://bscscan.com/token/0xb46584e0efdE3092e04010A13f2eAe62aDb3b9F0

please reply me

**Comment by OPEPEBSC** [comment]
hello admins please reply me

**Comment by OPEPEBSC** [comment]
@Cryptocool1 @cryptomanz1 @natedaiger @hexorx any. reply ?

**Comment by Cryptocool1** [comment]
Hello, we are not adding brand new tokens, you should wait. Your first massive transactions should be at least 7days ago

**Comment by OPEPEBSC** [comment]
how if i saw many token get logo in 1 or 2 day ?

**Comment by OPEPEBSC** [comment]
and we have. massive potential we are best volume in BSC check by your self

**Comment by OPEPEBSC** [comment]
any update ?

**Comment by OPEPEBSC** [comment]
dont understand what this mean ?

**Comment by OPEPEBSC** [comment]
hello ?

**Pull request merged**
