### PR TITLE
Add LucidLandsGem (BEP20)

### PR DESCRIPTION
**Pull request by mostermas**
Adding info for BEP20 token 'LucidLandsGem'.

PR created by <a href="https://assets.trustwallet.com">TW Assets Management</a>

### CODE REVIEW

**Comment by mostermas** [comment]
https://github.com/trustwallet/assets/pull/16750 Fee paid

вт, 28 дек. 2021 г. в 23:40, merge-fee-bot[bot] ***@***.***>:

**Comment by cryptomanz** [comment]
• What is the purpose of this token? How will it benefit Trust Wallet users?
 • How is the token being distributed? Are you conducting an airdrop?
 • Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?
 • Is the token listed on a centralized/decentralized exchange?
 • Is a Smart Contract audit completed? Where can we find this information?

**Comment by mostermas** [comment]
1. Lucid Lands is the first decentralized NFT play-to-earn game on BSC
network that integrates both 3D-animated gaming NFT and 2D unique
computer-generated collective NFT marketplace.
2. Here is Pic that show it https://prnt.sc/253gchj
3. Yes presale 500bnb hardcap price 60k LLG/BNB
4. Yes, some cex and pancakeswap dex (
https://www.ztb.im/exchange?coin=LLG_USDT ,
https://www.digifinex.com/en-ww/trade/USDT/LLG )
5. Yes we are being audit by certik (
https://www.certik.com/projects/lucidlands )

ср, 29 дек. 2021 г. в 09:22, Nazar ***@***.***>:

**Comment by cryptomanz** [comment]
Hello,
Please follow the rules for adding token, your logo should be a full screen, 256x256.

**Comment by mostermas** [comment]
Our logo is 256x256, wdym full screen? We did it by your instruction

ср, 29 дек. 2021 г., 19:25 Nazar ***@***.***>:

**Comment by cryptomanz** [comment]
Screenshot 2021-12-29 at 23 52 32

**Comment by mostermas** [comment]
logo

**Comment by mostermas** [comment]
uploaded to git

ср, 29 дек. 2021 г. в 23:54, Nazar ***@***.***>:

**Pull request merged**
