### PR TITLE
add DUIT (BEP20)

### PR DESCRIPTION
**Pull request by devduit**
add  Decentralization Unique Indo Token (DUIT) BEP20

### CODE REVIEW

**Comment by devduit** [comment]
update paid

**Comment by Cryptocool1** [comment]
This is a BEp20 token, correct folder is blockchains/smartchain/assets. Please correct.

**Comment by Cryptocool1** [comment]
As per our policy, brand new tokens are not included, there is a minimum requirement of 2500 holder addresses and 5000 transactions, in order to filter out scam tokens.
See the criteria at : https://community.trustwallet.com/t/how-to-submit-a-token-logo/3863).

**Comment by devduit** [comment]
can i pull new request for solving this?

**Pull request closed without merging**
