### PR TITLE
Adding Asimi Token info

### PR DESCRIPTION
**Pull request by asimitoken**
Adding Asimi Token info and logo file.

### CODE REVIEW

**Comment by Cryptocool1** [comment]
Please create new PR, follow doc https://developer.trustwallet.com/assets/requirements
You may want to try our Assets app in beta; go to https://assets.trustwallet.com, log on with Github, enter contract ID, logo and some additional info, and it will create a PR for you.
See https://developer.trustwallet.com/assets/repository_details

**Comment by Cryptocool1** [comment]
make sure to mention this PR so the fee can be reused

**Comment by asimitoken** [comment]
Hi, pls open our other PR#18733

we already made the payment for PR#18728

**Comment by asimitoken** [comment]
any help on this, is appreciated, or do we have to create new PR and pay for it again?

**Pull request closed without merging**
