### PR TITLE
Lady Doge Logo Upload (already PAYED)

### PR DESCRIPTION
**Pull request by ladydogeworld**
**Already payed:** 

please Check this PR: 
https://github.com/trustwallet/assets/pull/11418

### CODE REVIEW

**Comment by ladydogeworld** [comment]
• What is the purpose of this token? How will it benefit Trust Wallet users?

** Many users asked for the logo and really wanted it. We fought hard and think our community is very happy about it. We are a project with a charity function and that is why many of our investors would be happy!



 • Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?
** It whas a Fairlaunch - Only a Private Sale for The Admin team !**



 • Is the token listed on a centralized/decentralized exchange?
** Not yet.



 • Is a Smart Contract audit completed? Where can we find this information?
** https://github.com/TechRate/Smart-Contract-Audits/blob/main/LadyDoge.pdf

**Comment by ladydogeworld** [comment]
Go Go Go!

**Comment by Aaronztt** [comment]
Please show me where the agreement is that we need a cmc listning!



@Cryptocool1

**Comment by Cryptocool1** [comment]
please create new PR when cmc listing will be ready.
make sure to mention this PR, so that we can see that fee has been paid already here.

**Comment by Aaronztt** [comment]
Hello. So im done with you.

I want my BNB Payment back. Pls contact me.

**Comment by Aaronztt** [comment]
@Cryptocool1

**Comment by ladydogeworld** [comment]
> please create new PR when cmc listing will be ready.
> make sure to mention this PR, so that we can see that fee has been paid already here.

Hello, I want my BNB back.

**Comment by Aaronztt** [comment]
@Cryptocool1 hello. I want my money back! 4 bnb back to me. You have 24 hours time

**Comment by ladydogeworld** [comment]
ladydogeworld

**Comment by ladydogeworld** [comment]
Hello, weeks have now passed and I want my BNB back. I paid and received something in return.


If you ignore this message, I will report it. I will give you 3 days to report here, otherwise I will be forced to take legal action.

**Comment by Cryptocool1** [comment]
Hello, 
You have to read the rules before making the payment. 
please see:
Hi! In order to compensate for the efforts of processing PRs, we kindly ask for a contribution.
💀 As there is no refund, before paying the fee, make sure new tokens fulfill the minimum circulation and other acceptance criteria.
See also the PR Fee FAQ.

**Comment by Cryptocool1** [comment]
You token can only be accepted after cmc listing

**Comment by ladydogeworld** [comment]
> Your token can only be accepted after cmc listing

Hello, when we made the payment, we met everything. Then all of a sudden you put CMC on the list and 5,000 holders. When I paid the rules were different. After that everything was changed. As I said, I would like to have my money back from now on, otherwise I will be forced to file a complaint.

**Pull request closed without merging**
