### PR TITLE
Add American Dream (BEP20)

### PR DESCRIPTION
**Pull request by Arturiz**
Adding info for BEP20 token 'American Dream'.

PR created by <a href="https://assets.trustwallet.com">TW Assets Management</a>

### CODE REVIEW

**Comment by Arturiz** [comment]
Hi, we just launched yesterday and i wanted to get the logo up. We don't have a massive trading volume yet nore do we have 25k holders yet. if I pay the fee will it go trough ? as that is a lot of money for it to fail

**Comment by Arturiz** [comment]
@Cryptocool1 could you get back to me on that asap please :)

**Comment by cryptomanz** [comment]
As per our policy, brand new tokens are not included, there is a minimum requirement of 25,000 holder addresses and 50,000 transactions, in order to filter out scam tokens.
See the criteria at : https://developer.trustwallet.com/assets/requirements .

**Comment by Arturiz** [comment]
Also we're KYCd and we're FULLY DOXXED. We're starting a new project that will change many lives across the globe. you can check our youtube channel for video AMA's we done. i know you guys got strict on the requirements but we're fully public our identities are revealed. is there any way we can prove we're not a scam and get our logo up ?

**Comment by Arturiz** [comment]
@cryptomanz as reaching these numbers will take a good while...

**Pull request closed without merging**
