### PR TITLE
Add Sensible Finance (BEP20)

### PR DESCRIPTION
**Pull request by dracmic**
Adding info for BEP20 token 'Sensible Finance'.

PR created by <a href="https://assets.trustwallet.com">TW Assets Management</a>

### CODE REVIEW

**Comment by Cryptocool1** [comment]
Submission looks good. awaiting fee payment.

**Comment by dracmic** [comment]
@Cryptocool1  it will be any issues with: Logo dimensions OK (355x285)?

**Comment by Cryptocool1** [comment]
logo

**Comment by dracmic** [comment]
@Cryptocool1  so no :) thanks

**Comment by dracmic** [comment]
@Cryptocool1 sorry for the delay on payment ... can you please merge it.

**Pull request merged**
