### PR TITLE
Add Binancedog (BEP20)

### PR DESCRIPTION
**Pull request by Bidogofficial**
Adding info for BEP20 token 'Binancedog'.

PR created by <a href="https://assets.trustwallet.com">TW Assets Management</a>

### CODE REVIEW

**Comment by cryptomanz** [comment]
• What is the purpose of this token? How will it benefit Trust Wallet users?
 • How is the token being distributed? Are you conducting an airdrop?
 • Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?
 • Is the token listed on a centralized/decentralized exchange?
 • Is a Smart Contract audit completed? Where can we find this information?

**Comment by Bidogofficial** [comment]
What is the purpose of this token? How will it benefit Trust Wallet users?
Floki Rocket was created to implement proven tokenomics and provide stability and security to investors using a Trust Wallet. $FLOKI a frictionless yield token which rewards users with each transaction. Floki Rocket tokemonics work by taking a tax fee on every transaction. 4% of each buy and sell fee is redistributed to every user that holds $RLOKI in their Trust Wallet on a percentage basis. Each holder will secure a passive income in the form of $BNB. By just simply holding $RLOKI in your Trust Wallet, you will yield a generous passive income.

• How is the token being distributed? Are you conducting an airdrop?
We will conduct an airdrop to our PRIVATE SALE buyers from October 29, it was 50 BNB in total, 1 BNB max allocation. 1.2 billions tokiens per BNB. Airdrop will be done in 2 times, November 15, 00.00 UTC and November 29, 00.00 UTC, we will airdrop the BNB rewards as well.

• Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?
We made a presale on Pinksale, on November 10, here the link :[(https://www.pinksale.finance/#/launchpad/0xc8A74f97c99065F36c8DCcD346AdECB6355f79c1?chain=BSC)

• Is the token listed on a centralized/decentralized exchange?
oken is for the moment listed only on Pancakeswap (we are 1 day after launch).We have plans to list on CEX's soon.

• Is a Smart Contract audit completed? Where can we find this information?
Yes, you can check it on our website www.binancedog.net here is the report of the Contract audit:https://dessertswap.finance/audits/BiDog%20BSC%20Audit%2012394100.pdf

**Comment by Bidogofficial** [comment]
What is the purpose of this token? How will it benefit Trust Wallet users?
Floki Rocket was created to implement proven tokenomics and provide stability and security to investors using a Trust Wallet. $FLOKI a frictionless yield token which rewards users with each transaction. Floki Rocket tokemonics work by taking a tax fee on every transaction. 4% of each buy and sell fee is redistributed to every user that holds $RLOKI in their Trust Wallet on a percentage basis. Each holder will secure a passive income in the form of $BNB. By just simply holding $RLOKI in your Trust Wallet, you will yield a generous passive income.

• How is the token being distributed? Are you conducting an airdrop?
We will conduct an airdrop to our PRIVATE SALE buyers from October 29, it was 50 BNB in total, 1 BNB max allocation. 1.2 billions tokiens per BNB. Airdrop will be done in 2 times, November 15, 00.00 UTC and November 29, 00.00 UTC, we will airdrop the BNB rewards as well.

• Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?
We made a presale on Pinksale, on November 10, here the link :[(https://www.pinksale.finance/#/launchpad/0xc8A74f97c99065F36c8DCcD346AdECB6355f79c1?chain=BSC)

• Is the token listed on a centralized/decentralized exchange?
oken is for the moment listed only on Pancakeswap (we are 1 day after launch).We have plans to list on CEX's soon.

• Is a Smart Contract audit completed? Where can we find this information?
Yes, you can check it on our website www.binancedog.net here is the report of the Contract audit:https://dessertswap.finance/audits/BiDog%20BSC%20Audit%2012394100.pdf

**Comment by Bidogofficial** [comment]
What is the purpose of this token? How will it benefit Trust Wallet users?
The majority off our holders use trust wallet. Binance Dog is decentralized and owned by its fun, vibrant community. We welcome and embrace diverse perspectives to build Binance Dog into the best community in crypto. For every transaction in the Binance Dog network a 5% fee is distributed to existing holders. That means by just simply holding $Bidog in your Trust Wallet, you will yield a generous passive income.

• How is the token being distributed? Are you conducting an airdrop?
Initial supply:  100% Initial burn: 37% Dev wallet: 5% Marketing wallet: 3% Charity wallet: 2% Presale and initial LP: 45.2% Community Development: 4.8% Airdrop: 3%
The LP was locked for 3 years on Pinksale (https://www.pinksale.finance/#/launchpad/0xc8A74f97c99065F36c8DCcD346AdECB6355f79c1?chain=BSC) and other part was go to burn address 0x000000000000000000000000000000000000dead you can check it on Bscscan
Until now we have only conducted samll part airdrop for people(less than 1000) who has made a great contribution to our community. 

• Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?
We made a presale on Pinksale, on November 7, here is the link :(https://www.pinksale.finance/#/launchpad/0xc8A74f97c99065F36c8DCcD346AdECB6355f79c1?chain=BSC)

• Is the token listed on a centralized/decentralized exchange?
Token is for the moment listed only on Pancakeswap.We have plans to list on CEX's soon.

• Is a Smart Contract audit completed? Where can we find this information?
Yes, you can check it on our website www.binancedog.net here is the report of the Contract audit: https://dessertswap.finance/audits/BiDog%20BSC%20Audit%2012394100.pdf
and you can also check it on the audit webstie https://dessertswap.finance/recentaudits.html the name there is Bidog

**Pull request merged**
