### PR TITLE
Add TORA (BEP20)

### PR DESCRIPTION
**Pull request by ToraFoundation**
Adding info for BEP20 token 'TORA'.

PR created by <a href="https://assets.trustwallet.com">TW Assets Management</a>

### CODE REVIEW

**Comment by Cryptocool1** [comment]
how did you get 10.000 holders in 2 days?

**Comment by OfficialLimeWallet** [comment]
> how did you get 10.000 holders in 2 days?

Our community & some primary private sale

**Comment by ToraFoundation** [comment]
> how did you get 10.000 holders in 2 days?

Our community private sell

**Comment by Cryptocool1** [comment]
your holders seem to be artificial, on hold for now

**Comment by Cryptocool1** [comment]
are you listed on CoinMarketCap?

**Comment by ToraFoundation** [comment]
> are you listed on CoinMarketCap?

Not now

**Comment by ToraFoundation** [comment]
> your holders seem to be artificial, on hold for now

No our Community have around 40K + Existing Person

**Comment by Cryptocool1** [comment]
> > are you listed on CoinMarketCap?
> 
> Not now

we require CoinMarketCap listing. 
See the criteria at : https://developer.trustwallet.com/assets/requirements .

**Comment by Cryptocool1** [comment]
• Is a Smart Contract audit completed? Where can we find this information?

**Comment by ToraFoundation** [comment]
> • Is a Smart Contract audit completed? Where can we find this information?

We have audit report from 

> • Is a Smart Contract audit completed? Where can we find this information?

We have audited from Techrate (CMC Listed Group)

**Comment by Cryptocool1** [comment]
can you send the audit here?

**Comment by ToraFoundation** [comment]
> can you send the audit here?

Sure 👍

**Comment by ToraFoundation** [comment]
> can you send the audit here?

[Tora-Audit-Report.pdf](https://github.com/trustwallet/assets/files/9032890/Tora-Audit-Report.pdf)

**Comment by Cryptocool1** [comment]
that is not full smart contract audit.
awaiting on full smart contract audit and CoinMarketCap listing, on hold for now.

**Comment by ToraFoundation** [comment]
> that is not full smart contract audit. awaiting on full smart contract audit and CoinMarketCap listing, on hold for now.

CMC Not Possible Now 
& 
Techrate gives same audit for each project, that you are saying not full contract audit. 

You can consider it for listing now
Will promise after listing will be provided Full audit also

**Comment by Cryptocool1** [comment]
> > that is not full smart contract audit. awaiting on full smart contract audit and CoinMarketCap listing, on hold for now.
> 
> CMC Not Possible Now & Techrate gives same audit for each project, that you are saying not full contract audit.
> 
> You can consider it for listing now Will promise after listing will be provided Full audit also

you can see all our requirements here: https://developer.trustwallet.com/assets/requirements
you ordered partial audit from Techrate.

**Comment by Cryptocool1** [comment]
I also don't see your project on Techrate website, that is strange.
Feel free to open new PR once all criteria are met. Make sure to mention this PR so the fee can be reused.

**Comment by ToraFoundation** [comment]
> I also don't see your project on Techrate website, that is strange. Feel free to open new PR once all criteria are met. Make sure to mention this PR so the fee can be reused.

Why you closing fast. Will be fulfill all requirements. 

Other than cmc

**Comment by ToraFoundation** [comment]
> I also don't see your project on Techrate website, that is strange. Feel free to open new PR once all criteria are met. Make sure to mention this PR so the fee can be reused.

Why you closing fast. Will be fulfill all requirements. 

Other than cmc

**Comment by Cryptocool1** [comment]
You can text here once all criteria are met, and I will reopen the PR

**Comment by ToraFoundation** [comment]
> You can text here once all criteria are met, and I will reopen the PR

Wait 30 min, our project name will be on techrate. 
Ok

**Comment by Cryptocool1** [comment]
See my message above about our requirements.

**Pull request closed without merging**
