### PR TITLE
Add Monetas (BEP20)

### PR DESCRIPTION
**Pull request by MONETASGLOBAL**
Adding info for BEP20 token 'Monetas'.

PR created by <a href="https://assets.trustwallet.com">TW Assets Management</a>

### CODE REVIEW

**Comment by cryptomanz1** [comment]
#24550

**Comment by MONETASGLOBAL** [comment]
Hello Team,

Thank you so much. I am concerned that the live rate is not reflecting on
it. Could you please check on it ?

**Comment by Cryptocool1** [comment]
Please send a screenshot

**Comment by MONETASGLOBAL** [comment]
Hello Team,

The new smart contract is updated in Trust wallet, however the old MNTG
shows the live rate . Attached is the screenshot of the Same.

Please help us remove the Live rate of the old token.

**Comment by MONETASGLOBAL** [comment]
Hello Team,

The Logo on the old smart contract is removed however the token live rate
is still visible .

Its a  humble request to  check on the issue .



Regards
Monetas Global

**Pull request closed without merging**
