### PR TITLE
Add Minati (BEP20)

### PR DESCRIPTION
**Pull request by shyam121212**
Adding info for BEP20 token 'Minati'.

PR created by <a href="https://assets.trustwallet.com">TW Assets Management</a>

### CODE REVIEW

**Comment by Cryptocool1** [comment]
• What is the purpose of this token? How will it benefit Trust Wallet users?
 • How is the token being distributed? Are you conducting an airdrop?
 • Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?
 • Is the token listed on a centralized/decentralized exchange?
 • Is a Smart Contract audit completed? Where can we find this information?

**Comment by shyam121212** [comment]
• What is the purpose of this token? 
Answer - Minati Cryptocurrency brings a decentralized platform that provides high-end security, privacy, and sure success to its investors. Based on blockchain technology, DeFi along with AI enhances multiple processes and functionalities to eliminate the need for intermediaries. Minati aims to provide more secure, smart, and efficient financial services to its investors. So, they can easily buy, sell, and control their assets and transactions.

• How will it benefit Trust Wallet users?
Answer - Community Uses the wallet to transact a token exchange to wallet and wallet to exchange and users were easy to transact a token . hackers do not make phishing token . public safe from scams . 

• How is the token being distributed? 
Answer - We are starting a Airdrop of in international Market To bring a Community .Airdrop will be distributed Through the teligram at this time .
 
•Are you conducting an airdrop?
Answer - Yes we are conducting a airdrop on a teligram

• Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?
Answer - Minati has been launched a IDO on Dx sale or Presale Price 5 dollars

• Is the token listed on a centralized/decentralized exchange?
Answer - We are listed on a centralised Exchanges 

• Is a Smart Contract audit completed? Where can we find this information?
Answer - yes we are audited with the best agency cyberscope and the report were exisit on a google public domain

**Comment by shyam121212** [comment]
please reply sir

**Comment by Cryptocool1** [comment]
Please send your audit here

**Comment by Cryptocool1** [comment]
Thank you. 
Are you listed on CoinMarketCap?

**Comment by shyam121212** [comment]
> Thank you. Are you listed on CoinMarketCap?

yes sir https://coinmarketcap.com/currencies/minati-coin/

**Comment by shyam121212** [comment]
please approve my request

**Comment by shyam121212** [comment]
please reply sir

> Thank you. Are you listed on CoinMarketCap?

**Comment by shyam121212** [comment]
> Thank you. Are you listed on CoinMarketCap?

sir please approve my request

**Comment by Cryptocool1** [comment]
How did you get 15k holders in 1 week?

**Comment by shyam121212** [comment]
How did you get 15k holders in 1 week?

ANS- Already 40k + community on a social platforms transaction and holders was increased through the distribution of airdrop in telegram

**Comment by shyam121212** [comment]
> How did you get 15k holders in 1 week?

How did you get 15k holders in 1 week?

ANS- Already 40k + community on a social platforms transaction and holders was increased through the distribution of airdrop in telegram

**Comment by shyam121212** [comment]
> How did you get 15k holders in 1 week?

please reply sir

**Comment by shyam121212** [comment]
> How did you get 15k holders in 1 week?

please reply sir

**Comment by Cryptocool1** [comment]
Why there is no activity on your token transactions for 2 days?

**Comment by shyam121212** [comment]
> Why there is no activity on your token transactions for 2 days?

we have stopped the community coin transactions and air drop distribution because our developers are upgrading the system that's why in these 2 days there are no transactions

**Comment by shyam121212** [comment]
> Why there is no activity on your token transactions for 2 days?

please reply sir

**Comment by Cryptocool1** [comment]
We cannot add your token when you stopped all transactions.

**Comment by shyam121212** [comment]
so refund the 500 twt token please sir

**Comment by Cryptocool1** [comment]
You can see that we are not accept airdropped tokens here: https://developer.trustwallet.com/listing-new-assets/requirements
There is also no refund, as you can see it in the first message from the bot.

**Comment by shyam121212** [comment]
> You can see that we are not accept airdropped tokens here: https://developer.trustwallet.com/listing-new-assets/requirements There is also no refund, as you can see it in the first message from the bot.

please check our telegram group
we already doing a airdrop on telegram

**Comment by shyam121212** [comment]
> You can see that we are not accept airdropped tokens here: https://developer.trustwallet.com/listing-new-assets/requirements There is also no refund, as you can see it in the first message from the bot.

we not stopped any transactions community is not doing any transaction because of update

**Comment by shyam121212** [comment]
> You can see that we are not accept airdropped tokens here: https://developer.trustwallet.com/listing-new-assets/requirements There is also no refund, as you can see it in the first message from the bot.

but if you not provide me the logo it is a fraud on me because i already fulfilled all the conditions

**Comment by shyam121212** [comment]
> You can see that we are not accept airdropped tokens here: https://developer.trustwallet.com/listing-new-assets/requirements There is also no refund, as you can see it in the first message from the bot.

please don't do a scam with me because every condition is fullfilled

**Comment by Cryptocool1** [comment]
We do not accept airdropped tokens, please don’t spam here. You can come back to us once you get holders organically.  Fee can be reused

**Comment by shyam121212** [comment]
> We do not accept airdropped tokens, please don’t spam here. You can come back to us once you get holders organically. Fee can be reused

so how much time you will give me to get organically holders

**Comment by Cryptocool1** [comment]
How much you need, you can come back to us even next year.

**Comment by shyam121212** [comment]
> How much you need, you can come back to us even next year.

if i pay you more twt so then possible ?? without holder condition

**Comment by Cryptocool1** [comment]
No.

**Comment by shyam121212** [comment]
check the contract please 10,000 holders and 15,000 transactions is completed without any airdrop

**Comment by shyam121212** [comment]
> No.

please reply sir

**Comment by shyam121212** [comment]
please check my holders and transactions on bsc scan

**Comment by shyam121212** [comment]
Please approve my Mntc logo for trust wallet

**Comment by shyam121212** [comment]
???????

**Comment by shyam121212** [comment]
Hello sir please reply

**Comment by shyam121212** [comment]
please approve my request because all conditions is fulfilled

**Comment by shyam121212** [comment]
kindly approve my request of add logo because all conditions is fullfilled

**Comment by shyam121212** [comment]
> No.

please reply sir

**Comment by shyam121212** [comment]
I fullfilled all the conditions and you can check all the transaction that are not any part of airdrop and you can also talk to our project investors and community so please kindly proceed for the logo approval and all conditions are fullfilled

**Pull request closed without merging**
