### PR TITLE
Adding Seed.Photo Token logo and info

### PR DESCRIPTION
**Pull request by seedphoto**

### CODE REVIEW

**Comment by Cryptocool1** [comment]
• What is the purpose of this token? How will it benefit Trust Wallet users?
 • How is the token being distributed? Are you conducting an airdrop?
 • Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?
 • Is the token listed on a centralized/decentralized exchange?
 • Is a Smart Contract audit completed? Where can we find this information?

**Comment by seedphoto** [comment]
SEED token serves as the exclusive digital currency of the SEED.photo NFT marketplace, designed primarily as a loyalty program for photographers to access various platforms for showcasing and selling their artwork. Holding SEED tokens enables photographers to utilize different platforms for either shopping or promoting their artworks, enhancing their visibility and sales opportunities within the digital art space.

We didn't have any aidrop ourselves, but some exchanges they had competition for their users.

Without conducting an Initial Coin Offering (ICO), SEED tokens have been distributed through decentralized exchanges (DEXs) 

We are listed in PancakeSwap and Uniswap, in addition to four centralized exchange, including Mexc, TooBit, Citex, and BitVenus.


The smart contract underlying the SEED token has undergone audits by two distinct companies, ensuring its security and reliability, with detailed information available on Certik.com.

**Comment by seedphoto** [comment]
We can see our logo has been updated, but we don't see the price update
from CMC or Coingecko on the Trust app. Would you please check and tell us
what the issue is?

Here is our link in CMC:
https://coinmarketcap.com/currencies/seed-photo/

**Comment by Cryptocool1** [comment]
Hello, price will be updated soon

**Pull request merged**
