### PR TITLE
Add Magpie Token (BEP20)

### PR DESCRIPTION
**Pull request by magpiexyz**
Adding info for BEP20 token 'Magpie Token'.

PR created by <a href="https://assets.trustwallet.com">TW Assets Management</a>

### CODE REVIEW

**Comment by Cryptocool1** [comment]
As per our policy, brand new tokens are not included, there is a minimum requirement of 10,000 holder addresses and 15,000 transactions, in order to filter out scam tokens.
See the criteria at : https://developer.trustwallet.com/assets/requirements .

**Comment by Cryptocool1** [comment]
Please come back to us when all criteria are met.

**Comment by magpiexyz** [comment]
Hello @Cryptocool1, we finally met the requirement and you can check here https://bscscan.com/token/0xd06716e1ff2e492cc5034c2e81805562dd3b45fa
Let me know if there is anything else required for listing!

**Comment by Cryptocool1** [comment]
• What is the purpose of this token? How will it benefit Trust Wallet users?
 • How is the token being distributed? Are you conducting an airdrop?
 • Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?
 • Is the token listed on a centralized/decentralized exchange?
 • Is a Smart Contract audit completed? Where can we find this information?

**Comment by magpiexyz** [comment]
• What is the purpose of this token? How will it benefit Trust Wallet users?
MGP is the governance and revenue sharing token of Magpie. Users can lock their MGP Tokens to get vote-locked MGP. Vote-locked MGP allows users to earn passive income and share governance voting power. Trust Wallet users can also deposit their stablecoins on https://www.magpiexyz.io/stake to generate passive income after asset listing and DApp integration.

• How is the token being distributed? Are you conducting an airdrop?
You can check token distribution here: https://docs.magpiexyz.io/magpie-ecosystem/mgp-token/mgp-distribution 
We conduct an airdrop to reward early supporters https://blog.magpiexyz.io/magpie-xyz-mainnet-launch-and-airdrop-details-8093161a0751

• Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?
We conducted IFO on PancakeSwap and also a strategic presale before it.

• Is the token listed on a centralized/decentralized exchange?
It's listed on PancakeSwap https://pancakeswap.finance/swap?outputCurrency=0xD06716E1Ff2E492Cc5034c2E81805562dd3b45fa&inputCurrency=0xe9e7CEA3DedcA5984780Bafc599bD69ADd087D56

• Is a Smart Contract audit completed? Where can we find this information?
Yes, we have been audited by PeckShield and Zokyo, and you can check report link here: https://docs.magpiexyz.io/security/audit-reports

**Pull request merged**
