### PR TITLE
Add logo and info for Yummy

### PR DESCRIPTION
**Pull request by YummyCrypto**
Add logo and info for Yummy

### CODE REVIEW

**Comment by Cryptocool1** [comment]
As per our policy, brand new tokens are not included, there is a minimum requirement of 25,000 holder addresses and 50,000 transactions, in order to filter out scam tokens.
See the criteria at (mentioned in the first message by the bot): https://community.trustwallet.com/t/how-to-submit-a-token-logo/3863).
Closing PR for now. Please come back to us when all criteria are met.

**Comment by Cryptocool1** [comment]
DC6D3854-B3CA-4FDD-A6F8-70B9B01B4B36

**Comment by YummyCrypto** [comment]
This token is a V2 migration from Yummy V1, which was listed in TW. V1 contract here: https://bscscan.com/token/0x05f2df7b3d612a23fe12162a6c996447dce728a5

You can see the migration address from V1 to V2 here: https://bscscan.com/address/0x1F94DEB7CD97E2aC1A72dd8c9fbf177625aa240B from our migration website (https://yummyupgrade.com/). The V1 Yummy has 70K holders, but not all have migrated yet. Can this be reviewed to allow listing of V2?

**Pull request closed without merging**
