### PR TITLE
Add Greed LOGO

### PR DESCRIPTION
**Pull request by GreedOfficial**
This PR is being closed due to inactivity. If you wish to continue, please have us reopen the PR before sending your payment, or just create a new one.
Do NOT send payments for closed PR, as the fee may by lost!
  (48 vs. 48 hrs)

### CODE REVIEW

**Comment by GreedOfficial** [comment]
Hi, May i know why do we need 25000 holders?

**Comment by Cryptocool1** [comment]
• What is the purpose of this token? How will it benefit Trust Wallet users?
 • How is the token being distributed? Are you conducting an airdrop?
 • Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?
 • Is the token listed on a centralized/decentralized exchange?
 • Is a Smart Contract audit completed? Where can we find this information?

**Comment by GreedOfficial** [comment]
> • What is the purpose of this token? How will it benefit Trust Wallet users?
> • How is the token being distributed? Are you conducting an airdrop?
> • Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?
> • Is the token listed on a centralized/decentralized exchange?
> • Is a Smart Contract audit completed? Where can we find this information?

• What is the purpose of this token? How will it benefit Trust Wallet users?
  The Greed Ecosystem has plans for Music Label, NFTs, the Metaverse, Swaps, Farms & Staking on multiple blockchains. Holders will be rewarded in BNB.

• How is the token being distributed? Are you conducting an airdrop?
  Listed on pancake swap, Hotbit and XT and people can buy from there.

• Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?
  Yes. We had a presale on pinksale.

• Is the token listed on a centralized/decentralized exchange?
  Listed on pancakeswap, Hotbit and XT.

• Is a Smart Contract audit completed? Where can we find this information?
  https://github.com/TechRate/Smart-Contract-Audits/blob/main/October/Greed%20Token.pdf

**Comment by GreedOfficial** [comment]
Let me know if it all looks good so i can make the payment.

**Comment by GreedOfficial** [comment]
@Cryptocool1 Let me know all checks are passed so that i can make the payment. There was an error saying we need 25k holders. So confused.

**Comment by GreedOfficial** [comment]
@Cryptocool1 @hexorx @rfunduk @corymsmith Please confirm this is good to merge so that i can initiate payment

**Comment by Cryptocool1** [comment]
how holders will be rewarded with BNB?

**Comment by GreedOfficial** [comment]
> how holders will be rewarded with BNB?

Automatic rewards

**Pull request closed without merging**
