### PR TITLE
Add Chibi token logo

### PR DESCRIPTION
**Pull request by Chibi-Inu**
Created new PR for Fixing CheckSum address issue (Fees paid already in PR 8811)

### CODE REVIEW

**Comment by TVR2811** [comment]
Can you guide me what is issue and how to solve it?

**Comment by Chibi-Inu** [comment]
Hello, can you guide me what is issue and how to solve it?

**Comment by Chibi-Inu** [comment]
Anything else missing from our side? Let us know.

**Comment by Chibi-Inu** [comment]
Dear Team
Now that all the checks are place, when can we expect to have the logo updated on trust Wallet. The community has been asking for it every now and then. 

Thanks

**Pull request merged**
