### PR TITLE
Add flokidoge

### PR DESCRIPTION
**Pull request by sllow718**
Addition of logo for FlokiDoge

### CODE REVIEW

**Comment by sllow718** [comment]
hey, i just wanna add for flokidoge. pls assist.

**Comment by ramsty** [comment]
can you please add links to your PR
example:https://developer.trustwallet.com/assets/repository_details

**Comment by sllow718** [comment]
updated links v2

**Comment by ramsty** [comment]
As per our policy, brand new tokens are not included, there is a minimum requirement of 5000 holder addresses and 10000 transactions, in order to filter out scam tokens.
See the criteria at (mentioned in the first message by the bot): https://community.trustwallet.com/t/how-to-submit-a-token-logo/3863).
Closing PR for now. Please come back to us when all criteria are met.
When creating a new PR make sure to mention this PR, so that we can see that fee has been paid already here.

**Pull request closed without merging**
