### PR TITLE
Add AddMeFast (BEP20)

### PR DESCRIPTION
**Pull request by amftokenofficial**
Adding info for BEP20 token 'AddMeFast'.

PR created by <a href="https://assets.trustwallet.com">TW Assets Management</a>

### CODE REVIEW

**Comment by cryptomanz1** [comment]
As per our policy, brand new tokens are not included, there is a minimum requirement of 10,000 holder addresses and 15,000 transactions, in order to filter out scam tokens.
See the criteria at : https://developer.trustwallet.com/assets/requirements .

**Comment by amftokenofficial** [comment]
@cryptomanz1 thanks for the info.
Our Token is 1 year old and is now the main part of the solid project addmefast.com (over 11 years online).
All 7688 holders are real addresses and real users.
We never use spam/fraud to make it 10.000 in an unnatural way.
You can also check all transactions and transfers and see that everything is clear there.
Therefore, if possible, please process it without this requirement.
If this is OK for you, let us know and we will process the PR fee as soon as possible.

Thanks in advance.

**Comment by amftokenofficial** [comment]
> @cryptomanz1 thanks for the info. Our Token is 1 year old and is now the main part of the solid project addmefast.com (over 11 years online). All 7688 holders are real addresses and real users. We never use spam/fraud to make it 10.000 in an unnatural way. You can also check all transactions and transfers and see that everything is clear there. Therefore, if possible, please process it without this requirement. If this is OK for you, let us know and we will process the PR fee as soon as possible.
> 
> Thanks in advance.

@cryptomanz1 thanks for the info.
Our Token is 1 year old and is now the main part of the solid project addmefast.com (over 11 years online).
All 7688 holders are real addresses and real users.
We never use spam/fraud to make it 10.000 in an unnatural way.
You can also check all transactions and transfers and see that everything is clear there.
Therefore, if possible, please process it without this requirement.
If this is OK for you, let us know and we will process the PR fee as soon as possible.

Thanks in advance.

**Comment by amftokenofficial** [comment]
> As per our policy, brand new tokens are not included, there is a minimum requirement of 10,000 holder addresses and 15,000 transactions, in order to filter out scam tokens. See the criteria at : https://developer.trustwallet.com/assets/requirements .

@cryptomanz1 thanks for the info.
Our Token is 1 year old and is now the main part of the solid project addmefast.com (over 11 years online).
All 7688 holders are real addresses and real users.
We never use spam/fraud to make it 10.000 in an unnatural way.
You can also check all transactions and transfers and see that everything is clear there.
Therefore, if possible, please process it without this requirement.
If this is OK for you, let us know and we will process the PR fee as soon as possible.

Thanks in advance.

**Pull request closed without merging**
