### PR TITLE
Add MUBI(MUBI) (ERC20)

### PR DESCRIPTION
**Pull request by DavidGrunwald**

### CODE REVIEW

**Comment by Cryptocool1** [comment]
• What is the purpose of this token? How will it benefit Trust Wallet users?
 • How is the token being distributed? Are you conducting an airdrop?
 • Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?
 • Is the token listed on a centralized/decentralized exchange?
 • Is a Smart Contract audit completed? Where can we find this information?

**Comment by DavidGrunwald** [comment]
• What is the purpose of this token? How will it benefit Trust Wallet users?
The primary purpose of the Multibit token ($MUBI) is to power the decentralized application ecosystem of MultiBit. This token plays a crucial role in the platform's governance, allowing holders to participate in decision-making processes and earn rewards.
For Trust Wallet users, the benefits of using Multibit include efficient asset portability, enhanced liquidity pooling, optimized market access, a seamless user experience, and increased flexibility in managing assets. This integration facilitates liquidity transfer across networks, enabling Trust Wallet users to access a broader range of assets and investment opportunities.

**Comment by DavidGrunwald** [comment]
• What is the purpose of this token? How will it benefit Trust Wallet users?
  • The primary purpose of the Multibit token ($MUBI) is to power the decentralized application ecosystem of MultiBit. This token plays a crucial role in the platform's governance, allowing holders to participate in decision-making processes and earn rewards.
  • For Trust Wallet users, the benefits of using Multibit include efficient asset portability, enhanced liquidity pooling, optimized market access, a seamless user experience, and increased flexibility in managing assets. This integration facilitates liquidity transfer across networks, enabling Trust Wallet users to access a broader range of assets and investment opportunities.

• How is the token being distributed? Are you conducting an airdrop?
  • no airdrop.
    token distribution:
    Token Allocation
    95% unlocked in circulation
    5% Team Tokens vested

• Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?
  • we did public sale on bounce, fair launch

• Is the token listed on a centralized/decentralized exchange?
  • yes, mubi is listed on both cex such as gate, mexc etc. and dex such as uniswap

• Is a Smart Contract audit completed? Where can we find this information?
  • https://github.com/multibit-repo/audit

**Comment by Cryptocool1** [comment]
Please update your branch

**Comment by Billiej88** [comment]
> ### PR Summary
> file is not allowed: blockchains/ethereum/tokenlist.json: Please revert it. Token in PR: **ERC20** 0x38e382F74dfb84608F3C1F10187f6bEf5951DE93 Symbol: **MUBI** decimals: 18 Links: [Logo](https://raw.githubusercontent.com/multibit-repo/assets/master/blockchains/ethereum/assets/0x38e382F74dfb84608F3C1F10187f6bEf5951DE93/logo.png) [Info](https://raw.githubusercontent.com/multibit-repo/assets/master/blockchains/ethereum/assets/0x38e382F74dfb84608F3C1F10187f6bEf5951DE93/info.json) [Website](https://multibit.exchange/) [Explorer](https://etherscan.io/token/0x38e382F74dfb84608F3C1F10187f6bEf5951DE93) Tags: wrapped, defi ✅ Check OK
> 
>

**Pull request merged**
