### PR TITLE
Add bitFloki (BEP20)

### PR DESCRIPTION
**Pull request by adminbitfloki**
Adding info for BEP20 token 'bitFloki'.

PR created by <a href="https://assets.trustwallet.com">TW Assets Management</a>

### CODE REVIEW

**Comment by adminbitfloki** [comment]
Hello Team,

We would like to update our info on Trust wallet. Please have a look in our Website where we include all the information about our project including Audit link, Integrations, DEX listings and many other things: https://www.bitFloki.io

Our data is currently available on Coinmarketcap, Coingecko, dextool and Metamask. 

We have recently announced partnership with many projects you can find it on our socials.

If everything is okay we will proceed with the fee.

Thank you.

**Comment by adminbitfloki** [comment]
As there is no refund, before paying the fee, we want make sure our token fulfill the minimum circulation and other criteria.

please check everything so we can process payment.

**Comment by Cryptocool1** [comment]
• What is the purpose of this token? How will it benefit Trust Wallet users?
 • How is the token being distributed? Are you conducting an airdrop?
 • Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?
 • Is the token listed on a centralized/decentralized exchange?
 • Is a Smart Contract audit completed? Where can we find this information?

**Comment by Cryptocool1** [comment]
How did you get 16k holders in less then 1week?

**Comment by adminbitfloki** [comment]
1. The purpose of BitFloki is to create a community-driven cryptocurrency ecosystem that fosters financial inclusivity and empowers its users. BitFloki aims to provide a decentralized platform where individuals can participate in various activities such as trading, staking, and community engagement. Additionally, BitFloki may serve as a means of facilitating transactions, promoting adoption, and supporting charitable initiatives within its community. Ultimately, BitFloki endeavors to offer its users opportunities for financial growth and empowerment while fostering a vibrant and supportive community.

2. As per our tokenomics we have reserved 1% supply for Airdrop and We did Airdrop for community to increase our social engagement. We also did KOL round for marketing.

3. No we didn't organise any presale/IDO/private sale or ICO but we did KOL round to big influencers 

4. Yes our token is listed on Pancakeswap, coinmarketcap and Coingecko.

Links: https://pancakeswap.finance/swap?outputCurrency=0x79cdc9ca057e16dffd45bd803491f328f49e1762

https://coinmarketcap.com/currencies/bitfloki/

https://www.coingecko.com/en/coins/bitfloki

5. Yes our Smart Contract audit is completed. You can find it here : https://coinsult.net/projects/bitfloki/

6. Through Marketing campaigns, Dex buying, airdrop, KOL round etc.

**Pull request closed without merging**
