### PR TITLE
Update token list of ThunderCore network

### PR DESCRIPTION
**Pull request by rogerhsu-dev**
1. add ThunderCore tokens - TT-USDC, TT-WBTC, TT-ETH
2. remove obsolete ThunderCore tokens

### CODE REVIEW

**Comment by catenocrypt** [comment]
Please add an `info.json` file next to the `logo.png`, with info about the project, of the form:

```json
{
    "name": "Trust Wallet Token",
    "website": "https://trustwallet.com",
    "short_description": "Utility token to increase adoption of cryptocurrency.",
    "explorer": "https://etherscan.io/token/0xA866F0198208Eb07c83081d5136BE7f775c2399e",
    "socials": [
        {
            "name": "Twitter",
            "url": "https://twitter.com/trustwalletapp",
            "handle": "TrustWalletApp"
        },
        {
            "name": "Reddit",
            "url": "https://reddit.com/r/trustapp",
            "handle": "TrustApp"
        }
    ]
}
```

**Comment by rogerhsu-tt** [comment]
Hello @catenocrypt, I have submitted the missing info.json files.

The fee will be paid soon.

**Comment by catenocrypt** [comment]
Files look good.
To confirm: there are 3 new logo files added, and 5 info.json files -- I suppose 3 for the new logos and 2 for extisting tokens.
What about removed tokens you mentioned?

**Comment by rogerhsu-tt** [comment]
It seems the tokens I wanted to remove were already removed earlier. I found out it after making pr.

**Comment by catenocrypt** [comment]
All right, no problem, I'm closing this then.

**Comment by rogerhsu-tt** [comment]
@catenocrypt I meant the `remove obsolete ThunderCore tokens` part was already done in the past. However the `add ThunderCore tokens - TT-USDC, TT-WBTC, TT-ETH` is still the main purpose of this pr.

**Comment by rogerhsu-tt** [comment]
I will create a new pr with a more precise description.

**Pull request closed without merging**
