### PR TITLE
Add YLD logo

### PR DESCRIPTION
**Pull request by MiTeePingWin**

### CODE REVIEW

**Comment by catenocrypt** [comment]
Please add an `info.json` file next to the `logo.png`, with info about the project, of the form:

```json
{
    "name": "Trust Wallet Token",
    "website": "https://trustwallet.com",
    "short_description": "Utility token to increase adoption of cryptocurrency.",
    "explorer": "https://etherscan.io/token/0xA866F0198208Eb07c83081d5136BE7f775c2399e",
    "socials": [
        {
            "name": "Twitter",
            "url": "https://twitter.com/trustwalletapp",
            "handle": "TrustWalletApp"
        },
        {
            "name": "Reddit",
            "url": "https://reddit.com/r/trustapp",
            "handle": "TrustApp"
        }
    ]
}
```

**Comment by MiTeePingWin** [comment]
JSON file has been added.
Thanks  :)

**Comment by catenocrypt** [comment]
Sorry, I still see only one file

image

**Comment by MiTeePingWin** [comment]
How about now? Sorry I'm a bit new at pull requests.

**Comment by catenocrypt** [comment]
OK, info file is OK now, thanks.

Token circulation is below our limit yet, 592 holders as opposed to 2500.  Is this a staking token?

https://etherscan.io/token/0xDcB01cc464238396E213a6fDd933E36796eAfF9f

**Comment by MiTeePingWin** [comment]
Yes We are currently staking.
We have (had?) ~2700 wallets using our Beta on portis yield.vercel.app
These users are staking right now as an incentive to move over to mainnet.

We also had an airdrop competition for the top 100 wallets, this concentrated our wallets down quite a bit more as well. The airdrop has NOT been distributed yet.
https://yieldcredit.medium.com/yield-yld-airdrop-round-2-3ae3ff830f65

We're also visible (but not tradeable) on Coinbase, if that helps.

**Pull request merged**
