### PR TITLE
Add Broovs (BEP20)

### PR DESCRIPTION
**Pull request by raysoft16**
Adding info for BEP20 token 'Broovs'.

PR created by <a href="https://assets.trustwallet.com">TW Assets Management</a>

### CODE REVIEW

**Comment by raysoft16** [comment]
Holders  8.231          transection     11.590

Salih2013@***

7 Nis 2022 Per 12:55 tarihinde merge-fee-bot[bot] ***@***.***>
şunu yazdı:

**Comment by raysoft16** [comment]
The error code I got is attached. What should we do?

Salih2013@***

7 Nis 2022 Per 13:22 tarihinde Yusuf Yavuz ***@***.***> şunu
yazdı:

**Comment by Cryptocool1** [comment]
Please create new PR, follow doc https://developer.trustwallet.com/assets/requirements
You may want to try our Assets app in beta; go to https://assets.trustwallet.com, log on with Github, enter contract ID, logo and some additional info, and it will create a PR for you.
See https://developer.trustwallet.com/assets/repository_details

**Comment by Cryptocool1** [comment]
Please create new PR, follow doc https://developer.trustwallet.com/assets/requirements
You may want to try our Assets app in beta; go to https://assets.trustwallet.com, log on with Github, enter contract ID, logo and some additional info, and it will create a PR for you.
See https://developer.trustwallet.com/assets/repository_details

**Pull request closed without merging**
