### PR TITLE
Add BEP20 (ITAM) & Update ERC20 (ITAM)

### PR DESCRIPTION
**Pull request by changmyeong**
Add BEP20 (ITAM) & Update ERC20 (ITAM)

### CODE REVIEW

**Comment by cryptomanz** [comment]
short description field is not needed

**Comment by changmyeong** [comment]
@cryptomanz Remove from ethereum?

**Comment by changmyeong** [comment]
@cryptomanz Updated now. Please check one more time.

**Comment by Cryptocool1** [comment]
hello,
• What is the purpose of this token? How will it benefit Trust Wallet users?
 • How is the token being distributed? Are you conducting an airdrop?
 • Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?
 • Is the token listed on a centralized/decentralized exchange?
 • Is a Smart Contract audit completed? Where can we find this information?

**Comment by changmyeong** [comment]
@Cryptocool1 @cryptomanz 

• What is the purpose of this token? How will it benefit Trust Wallet users?
- ITAM is utility token. share our NFT Marketplace trading fee to holders.
- We have 11K holders. Trust Wallet users may increase.

• How is the token being distributed? Are you conducting an airdrop?
- total supply is 650,000,000 ITAM. Currently No lock, All of the token has users.
- If necessary, we will issue token through governance.

• Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?
- Yes. we sold in 2019.

• Is the token listed on a centralized/decentralized exchange?
- It's listed at PancakeSwap (https://coinmarketcap.com/currencies/itam-games/markets/)

• Is a Smart Contract audit completed? Where can we find this information?
- https://assets-store.itam.games/pdfs/ITAM-TOKEN.pdf

**Pull request merged**
