### PR TITLE
Added Andrew Cecil Funderburk 3rd (ACF3)

### PR DESCRIPTION
**Pull request by PendelinP**

### CODE REVIEW

**Comment by PendelinP** [comment]
@kolya182 Is this bot serious or a scam? I can't read anything in the readme. Thanks.

**Comment by catenocrypt** [comment]
It's not a scam :)  We decided to implement something like this to kind of filter out not serious scam coins.  It was just introduced, so some tweaking + documentation may come.

/check

**Comment by PendelinP** [comment]
Open source vs. merge payments doesn't work for me.

**Comment by catenocrypt** [comment]
I understand your concern, but I think asking contribution for running the infrastructure is justified. Trust Wallet -- wallet-core, blockatlas, and the assets repository are open source: you are free to use them, free to fork them. But using the branded product or the backend API is another matter, maintaining the infrastructure has costs. The assets is part of this infrastructure.

**Comment by PendelinP** [comment]
@catenocrypt Thanks for the clarification. The first sentence of the bot message states that the fee is for maintaining. You say it's for running the infrastructure. Anyway I don't fully understand how you could run the infrastructure until now if you rely on fees from contributors. I added some token logos just for fun. If this is the new way of collaboration - it's totally okay. Unfortunately I won't add stuff or try to make the documentation better. I really doubt to stop scam by taking a fee but I respect the decision of you and your team :)

**Pull request closed without merging**
