### PR TITLE
Add ROTHS (BEP20)

### PR DESCRIPTION
**Pull request by ROTHSLIVE**
Adding info for BEP20 token 'ROTHS'.

PR created by <a href="https://assets.trustwallet.com">TW Assets Management</a>

### CODE REVIEW

**Comment by ROTHSLIVE** [comment]
In order to streamline the review of the contribution we ask you
to ensure the following steps have been taken:

- [x] Filename in the `lowercase` format
- [x] Image format: `png`
- [x] Image size: `256 by 256 px`

**Comment by ROTHSLIVE** [comment]
In order to streamline the review of the contribution we ask you
to ensure the following steps have been taken:

- [x] Filename in the `lowercase` format
- [x] Image format: `png`
- [x] Image size: `256 by 256 px`

**Comment by ROTHSLIVE** [comment]
In order to streamline the review of the contribution we ask you
to ensure the following steps have been taken:

- [x] Filename in the `lowercase` format
- [x] Image format: `png`
- [x] Image size: `256 by 256 px`

**Comment by Cryptocool1** [comment]
cannot find your contract on your website.
please check

**Comment by ROTHSLIVE** [comment]
> cannot find your contract on your website.
> please check

Pls visit roths.live, with any decentralize wallet, like metamask, trust wallet, im token, paper wallet... there is features to direct connect to smartcontract. if it is necessary we can provide it.

**Pull request merged**
