### PR TITLE
Add LilDogeFloki Support for Trust Wallet

### PR DESCRIPTION
**Pull request by LilDogeFlokiToken**

### CODE REVIEW

**Comment by LilDogeFlokiToken** [comment]
> **PR Summary** Files OK, 2Files in PR: 2 Token in PR: BEP20 0xaa15f52Ef3994213a9e06731F6471786B75372CC Symbol: **LDF🐕** decimals: 9 Links: [Logo](https://raw.githubusercontent.com/LilDogeFlokiToken/assets/master/blockchains/smartchain/assets/0xaa15f52Ef3994213a9e06731F6471786B75372CC/logo.png) [Info](https://raw.githubusercontent.com/LilDogeFlokiToken/assets/master/blockchains/smartchain/assets/0xaa15f52Ef3994213a9e06731F6471786B75372CC/info.json) [Website](https://lildogefloki.fun) [Explorer](https://bscscan.com/token/0xaa15f52Ef3994213a9e06731F6471786B75372CC) Token check error: ❌ Symbol does not match token info, expected 'LDF&#128021;' instead of 'LDF🐕', please change. ❌ Low token circulation: no. of holders is 4993, below limit of 5000 ! Website could not be accessed, status 500, url https://lildogefloki.fun ✓ Token type OK (BEP20); Contract/ID is OK; Type field OK; Decimals field OK; Description field OK; Explorer field OK; Status field OK; Id field OK; Logo image type is OK (image/png); Logo image size is OK (37.593 kB); Logo dimensions OK (256x256);
> 
> 

https://bscscan.com/token/0xaa15f52ef3994213a9e06731f6471786b75372cc - BSCSCAN shows our holders over 5000 and more than 10k transactions

**Comment by LilDogeFlokiToken** [comment]
> Hi! In order to compensate for the efforts of processing PRs, we kindly ask for a contribution. 💀 As **there is no refund**, before **paying the fee**, make sure **new tokens fulfill the minimum circulation and other [acceptance criteria](https://community.trustwallet.com/t/how-to-submit-a-token-logo/3863)**. See also the [PR Fee FAQ](https://developer.trustwallet.com/add_new_asset/pr-fee).
> 
> Please pay **1000 TWT** with the memo **15143** to the address `bnb1tqq9llyr3dyjd559dha6z5r5etk3qfwk07m098`. Alternatively, 5 BNB is also accepted (same memo & address).
> 
> **QR** code: [Trust](https://api.qrserver.com/v1/create-qr-code/?size=200x200&data=https%3A%2F%2Flink.trustwallet.com%2Fsend%3Fasset%3Dc714_tTWT-8C2%26address%3Dbnb1tqq9llyr3dyjd559dha6z5r5etk3qfwk07m098%26amount%3D1000%26memo%3D15143) | [other wallet](https://api.qrserver.com/v1/create-qr-code/?size=200x200&data=bnb1tqq9llyr3dyjd559dha6z5r5etk3qfwk07m098%3Famount%3D1000%26memo%3D15143)
> 
> _Notes_:
> 
> * [Trust Wallet Tokens (TWT)](https://community.trustwallet.com/t/trust-wallet-token-twt/4187) can be obtained through our [Referral Program](https://community.trustwallet.com/t/invite-a-friend-earn-trust-wallet-token-twt/4125) or [from DEXs/exchanges](https://community.trustwallet.com/t/where-to-get-trust-wallet-tokens/76641).
> * New tokens without significant usage are rejected, see criteria mentioned above.
> * One PR should be for a single project; PR's with more than 10 logos will be rejected.
> * Payment evaluation happens automatically, but with a few minutes delay.  When payment is detected, an Accept Review is automatically placed on the PR, which is a condition for merge.
> * Evaluating the PR is done manually, and it is merged only if all conditions are satisfied.
> * TWT-BEP2 is supported (Binance Chain), TWT-BEP20 version on Smart Chain is not.

This has been paid

**Comment by Cryptocool1** [comment]
• What is the purpose of this token? How will it benefit Trust Wallet users?
 • How is the token being distributed? Are you conducting an airdrop?
 • Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?
 • Is the token listed on a centralized/decentralized exchange?
 • Is a Smart Contract audit completed? Where can we find this information?

**Comment by LilDogeFlokiToken** [comment]
@Cryptocool1 Answers Below to your questions, thanks for the time and consideration

> • What is the purpose of this token? How will it benefit Trust Wallet users?  
The purpose of the token is DAO based which we have developed and deployed the DAPP today [https://dao.lildogefloki.fun/], this will help steer the direction of the token based on community input/multi-sig treasury. Further to this we have a game in development that will be P2E using LDF as utility towards both. This benefits trust wallet users as a lot of our user base are BSC Native users who already are using TW instead of just MM and have been asking since launch if we could get integration on your platform.

• How is the token being distributed? Are you conducting an airdrop? 
Token was a complete fair & stealth launch. Team put up initial liquidity in BNB + half our total supply to create the initial pool. The other half of the supply was burnt as our smart contract has 1% reflection to holders (burn wallet also being the largest holder) they get a portion of the 1% creating further deflation to token supply as time goes on. There will be no airdrop, all tokens that remain are now circulating to the community.

• Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale? 
No ICO or token presale to raise funds. This also ties into above. Further to the 1% reflection to holders on every transaction there is a further 4 % on transaction that gets distributed to a dev/marketing wallet that is used for just that development and marketing (fully transparent to our community and indicated directly on our website and all social channels). Lastly another 4% is used directly to create further liquidity for the pool which it is automatically swapped and added as transactions happen.

• Is the token listed on a centralized/decentralized exchange?  
Decentralized Exchange for now - Pancakeswap [https://pancakeswap.finance/swap?outputCurrency=0xaa15f52Ef3994213a9e06731F6471786B75372CC] which at the time of writing has ~900k in the liquidity pool which is also locked on team.finance. We do have plans to list on CEX's in the near future

•Is a Smart Contract audit completed? Where can we find this information? Solidity Finance is currently conducting our first audit which is estimated to be completed within 48 hours and will be added to our GitHub as soon as it's released. We are only a couple days old with tremendous growth but we are here to stay! Second audit will be with Certik but their backlog and lead-time is roughly 4-5 weeks out.

I hope this satisfies your request and we can get our community what they want and this is TW integration. Let me know if you need anything further.

**Comment by cryptomanz** [comment]
Awaiting for smart contract audit. On hold for now.

**Comment by Cryptocool1** [comment]
Please come back to us when all criteria are met.
When creating a new PR make sure to mention this PR, so that we can see that fee has been paid already here.

**Pull request closed without merging**
