### PR TITLE
Add TIMERS (IPM) token Logo and info.json

### PR DESCRIPTION
**Pull request by Kairos-Timers**
Token Name: TIMERS
Token Symbol: IPM

Web: timers.network
Twitter: @TIMERSnetwork
Contract: 0x8fEEf860E9fA9326ff9d7E0058F637bE8579Cc29

### CODE REVIEW

**Comment by catenocrypt** [comment]
As per our policy, brand new tokens are not included, there is a minimum requirement of 100 holder addresses and 500 transactions, in order to filter out scam tokens.
See https://community.trustwallet.com/t/how-to-submit-a-token-logo/3863#how-to-get-approved
This token has no usage yet, so putting this PR on hold.

https://etherscan.io/token/0x8fEEf860E9fA9326ff9d7E0058F637bE8579Cc29

**Comment by zachzwei** [comment]
Please provide more details about this project. We will be closing this for now.
You can reopen when you have met the requirements mentioned here:
https://community.trustwallet.com/t/how-to-submit-a-token-logo/3863#how-to-get-approved

You can follow this format when adding an info.json file:

``` {
   "name":"Bitcoin",
   "website":"https://bitcoin.org",
   "source_code":"https://github.com/bitcoin",
   "white_paper":"https://bitcoin.org/bitcoin.pdf",
   "short_description":"Bitcoin is a cryptocurrency and worldwide payment system.",
   "explorer":"https://blockchain.info",
   "research":"https://research.binance.com/en/projects/bitcoin"
}

**Comment by Kairos-Timers** [comment]
Added info.json file. Presale successfully finished. 500 holders reached, 600+ transactions, with Uniswap listing tomorrow and confirmed HotBit listing on 9th of October (https://hotbit.zendesk.com/hc/en-us/articles/360054057254-Hotbit-will-launch-IPM-TIMERS-on-October-9) this should hopefully satisfy the "demand" requirement. We hope this will be enough, as there are already fake tokens and the icon could help verify the real token on Uniswap.

**Comment by catenocrypt** [comment]
Reopening

**Pull request merged**
