### PR TITLE
Add NanoDogeCoin Logo & Info

### PR DESCRIPTION
**Pull request by BSCGuru**
Add NanoDogeCoin Logo & Info

### CODE REVIEW

**Comment by BSCGuru** [comment]
Payment made*

**Comment by Cryptocool1** [comment]
hello,
can you answer some questions, please?
• What is the purpose of this token? How will it benefit Trust Wallet users?
 • How is the token being distributed? Are you conducting an airdrop?
 • Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?
 • Is the token listed on a centralized/decentralized exchange?
 • Is a Smart Contract audit completed? Where can we find this information?

**Comment by BSCGuru** [comment]
• What is the purpose of this token? How will it benefit Trust Wallet users?
Holders of Nano Dogecoin benefit as they are rewarded with USD-Tether redistributions on transactions in/out of the token. They are also able to invest in a token that supports animal welfare globally, by making charitable donations to shelters for rescuing and rehoming dogs.

• How is the token being distributed? Are you conducting an airdrop?
Nano DogeCoin ($NDC) was sold via Private Sale (via our website), then Presale (via DxSale) and then publicly via PancakeSwap.

• Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?
There were 2 Public Presales before PancakeSwap launch, totalling 6,100 BNB raised.

• Is the token listed on a centralized/decentralized exchange?
Decentralised exchange - PancakeSwap.

• Is a Smart Contract audit completed? Where can we find this information?
Yes - Audited by Techrate (PDF can be found here: [https://github.com/BSCGuru/NanoDogeCoin], also additional incoming Audit by Certik (they have been paid as well).

**Comment by Cryptocool1** [comment]
Can you please add links to your PR?

**Comment by NanoDoge** [comment]
Hello @Cryptocool1! 😊

Our team just noticed about this duplicate request.
We had an internal miscommunication and ended up doing the listing request twice by accident.

We kindly ask to close this one in favour of #12449 which has the most updated and complete audits, details and informations from our communications team.
We are sorry for any inconvenience this may have caused.

**- Nano Dogecoin Team**

**Comment by BSCGuru** [comment]
We tried adding links, but it led to issues: Could not retrieve info file; NanoDogeCoin/assets/master 0x1B41821625d8CFAd21cd56491DACD57ECaCc83dE, SyntaxError: Unexpected string in JSON at position 461

**Comment by BSCGuru** [comment]
image
This was the code we tried in the prior pull requests, but it was getting rejected.

The error was: Could not retrieve info file; NanoDogeCoin/assets/master 0x1B41821625d8CFAd21cd56491DACD57ECaCc83dE, SyntaxError: Unexpected string in JSON at position 461

**Review by smercan89 — APPROVED** [review]

**Comment by Cryptocool1** [comment]
you have to put comma after id field

**Comment by BSCGuru** [comment]
Everything should be fine now. @Cryptocool1

**Comment by BSCGuru** [comment]
Hey TrustWallet Team,

NanoDogeCoin recently did a tokenswap, do we need to submit a new application or update this pull request?

**Comment by emadami3060** [comment]
Hi

**Pull request merged**
