### PR TITLE
Add CHEEMSINU (BEP20)

### PR DESCRIPTION
**Pull request by cheemsco**
Adding info for BEP20 token 'CHEEMSINU'.

PR created by <a href="https://assets.trustwallet.com">TW Assets Management</a>

### CODE REVIEW

**Comment by cheemsco** [comment]
Cheems Inu is a meme itself that hopes to inspire others by combining Memes and Crypto to bring both LOLs and money to the masses of the internet. It is already taking over with first gen NFT collection which is sold out and second batch is coming soon!

Cheems inu was stealth launched with $10.000 Market cap and ATH'ed at +$24M, now sitting around 6-10M with $5M volume last 24 hours. It is listed on Coinmarketcap, Coingecko and Crypto.com for price tracking and tradeable on Hotbit. It has marketing ongoing with a huge budget, incoming Bitmart listing, ongoing SpaceX billboards, Cointelegraph articles and daily reviews from all social media sources. No airdrops conducted throughout the trading history. The project is planning to get audit from CertiK and an audit is already issued by Techrate which is below:

https://github.com/TechRate/Smart-Contract-Audits/blob/main/December/CHEEMSINU%20Full%20Smart%20Contract%20Security%20Audit.pdf

Please let us know if we are good to go and we'd like to proceed with payment. Kind regards.

**Comment by Cryptocool1** [comment]
• What is the purpose of this token? How will it benefit Trust Wallet users?
 • How is the token being distributed? Are you conducting an airdrop?
 • Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?
 • Is the token listed on a centralized/decentralized exchange?
 • Is a Smart Contract audit completed? Where can we find this information?

**Comment by cheemsco** [comment]
1) Cheems Inu is a meme itself that hopes to inspire others by combining Memes and Crypto to bring both LOLs and money to the masses of the internet. It is already taking over with first gen NFT collection which is sold out and second batch is coming soon! The main product of the project will be MEMETOOLS which will make it way easier for people to create memes and it's anticipated to be live in late december.

2) No airdrop conducted

3) Cheems inu was stealth launched with $10.000 Market cap

4) Pancakeswap, It is listed on Coinmarketcap, Coingecko and Crypto.com for price tracking and tradeable on Hotbit. 

5) https://github.com/TechRate/Smart-Contract-Audits/blob/main/December/CHEEMSINU%20Full%20Smart%20Contract%20Security%20Audit.pdf

**Comment by Cryptocool1** [comment]
submission looks good, awaiting for fee payment

**Pull request merged**
