### PR TITLE
Add ROSN logo and info

### PR DESCRIPTION
**Pull request by dobachtri**
Add ROSN logo (Roseon Finance) and info

### CODE REVIEW

**Comment by dobachtri** [comment]
Hi, is it okay if I submitted the logo with a different name?
I submitted Roseon Finance.png instead of logo.png.
Can you help me?









[image: Mailtrack]
<https://mailtrack.io?utm_source=gmail&utm_medium=signature&utm_campaign=signaturevirality5&>
Sender
notified by
Mailtrack
<https://mailtrack.io?utm_source=gmail&utm_medium=signature&utm_campaign=signaturevirality5&>
05/12/21,
10:53:37 AM

Vào Th 4, 12 thg 5, 2021 vào lúc 10:42 merge-fee-bot[bot] <
***@***.***> đã viết:

**Comment by Cryptocool1** [comment]
Logo file should be named logo.png
You can just remove the Roseon Finance.png file

**Comment by Cryptocool1** [comment]
Corrections needed
-Your ontract is not in checksum format, should be 0x651Cd665bD558175A956fb3D72206eA08Eb3dF5b
-Socials field is no longer needed, please remove it

**Comment by dobachtri** [comment]
Any update?

**Comment by dobachtri** [comment]
Cryptocool1
 Any update ^^

**Comment by dobachtri** [comment]
@Cryptocool1 Any update^^ I've fixed it

**Comment by Cryptocool1** [comment]
> @Cryptocool1 Any update^^ I've fixed it

Contract is not in checksum format, should be 0x651Cd665bD558175A956fb3D72206eA08Eb3dF5b

**Comment by Cryptocool1** [comment]
> @Cryptocool1 Any update^^ I've fixed it

Can you remove this file please? blockchains/smartchain/assets/0x651cd665bd558175a956fb3d72206ea08eb3df5b/Roseon Finance.png

**Pull request merged**
