### PR TITLE
Add MIX (BEP20)

### PR DESCRIPTION
**Pull request by MixMarvel-github**
add info.json and logo for MIX

### CODE REVIEW

**Comment by cryptomanz** [comment]
Hello,
 Can your answer some questions?
 • What is the purpose of this token? How will it benefit Trust Wallet users?
 • How is the token being distributed? Are you conducting an airdrop?
 • Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?
 • Is the token listed on a centralized/decentralized exchange?
 • Is a Smart Contract audit completed? Where can we find this information?

**Comment by MixMarvel-github** [comment]
• What is the purpose of this token? How will it benefit Trust Wallet users?
A: MIX is a platform token representing the growth of the platform's ecosystem value, with a fixed circulation of 10 billion. Its distribution rules are based on community members' behavior that is beneficial to the ecosystem. 
After years of development and promotions conducted by MixMarvel, MIX currently has 14,952 private wallet holders on Ethereum and BSC. This userbase will be provided with the chance to check their wallet assets on Trust Wallet. 

• How is the token being distributed? Are you conducting an airdrop?
A: MIX Token Distribution is as follows: 
20% Team
20% Investors
30% Community 
15% Development Fund 
10.5% Marketing Fund 
4.5% Risk Prevention 
Airdrops are conducted in our communities if users show behavior beneficial for the MixMarvel ecosystem. 

• Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?
A: MIX tokens have not participated in ICO or pre-sale. 

• Is the token listed on a centralized/decentralized exchange?
A: MIX is listed both on centralized and decentralized exchanges.
For an updated list of MIX trading pairs, please view the following link: https://medium.com/mixmarvel-official-blog/mix-token-is-listed-on-the-following-exchanges-19385a575c82

• Is a Smart Contract audit completed? Where can we find this information?
A: MIX token contract is audited by Slow Mist. 
https://www.slowmist.com/en/security-audit-certificate.html?id=b4554a9eb319699cf974e087393f2000d4f1209a8adc65e9fae31809e9327829

**Comment by Cryptocool1** [comment]
> • What is the purpose of this token? How will it benefit Trust Wallet users?
> A: MIX is a platform token representing the growth of the platform's ecosystem value, with a fixed circulation of 10 billion. Its distribution rules are based on community members' behavior that is beneficial to the ecosystem.
> After years of development and promotions conducted by MixMarvel, MIX currently has 14,952 private wallet holders on Ethereum and BSC. This userbase will be provided with the chance to check their wallet assets on Trust Wallet.
> 
> • How is the token being distributed? Are you conducting an airdrop?
> A: MIX Token Distribution is as follows:
> 20% Team
> 20% Investors
> 30% Community
> 15% Development Fund
> 10.5% Marketing Fund
> 4.5% Risk Prevention
> Airdrops are conducted in our communities if users show behavior beneficial for the MixMarvel ecosystem.
> 
> • Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?
> A: MIX tokens have not participated in ICO or pre-sale.
> 
> • Is the token listed on a centralized/decentralized exchange?
> A: MIX is listed both on centralized and decentralized exchanges.
> For an updated list of MIX trading pairs, please view the following link: https://medium.com/mixmarvel-official-blog/mix-token-is-listed-on-the-following-exchanges-19385a575c82
> 
> • Is a Smart Contract audit completed? Where can we find this information?
> A: MIX token contract is audited by Slow Mist.
> https://www.slowmist.com/en/security-audit-certificate.html?id=b4554a9eb319699cf974e087393f2000d4f1209a8adc65e9fae31809e9327829

in the audit not your contract "0x29773c1f420a9e7820d0d5c71ce761d972a73699"
please check

**Comment by Cryptocool1** [comment]
Cant find the contract on your website.
please check

**Comment by MixMarvel-github** [comment]
please view the following link of our website:
https://www.mixmarvel.com/info_detail?no=626

**Comment by Cryptocool1** [comment]
can you please add links to your PR?
example: https://developer.trustwallet.com/add_new_asset/repository_details

**Pull request merged**
