### PR TITLE
Add Catcoin (BEP20)

### PR DESCRIPTION
**Pull request by catcoincom**
Adding info for BEP20 token 'Catcoin'.

PR created by <a href="https://assets.trustwallet.com">TW Assets Management</a>

### CODE REVIEW

**Comment by Cryptocool1** [comment]
• What is the purpose of this token? How will it benefit Trust Wallet users?
 • How is the token being distributed? Are you conducting an airdrop?
 • Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?
 • Is the token listed on a centralized/decentralized exchange?
 • Is a Smart Contract audit completed? Where can we find this information?

**Comment by catcoincom** [comment]
> • What is the purpose of this token? 
catcoin is a memecoin at present we are developing ai product where token will be used to pass some restriction
How will it benefit Trust Wallet users? 
TW users can easily buy catcoin token using app.

• How is the token being distributed? Are you conducting an airdrop? 
We launched token using OXBULL IDO and rest fund added to pool from where users purchased all token. No we are not conducting any airdrop.

• Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale? 
Yes, Using OXBULL

• Is the token listed on a centralized/decentralized exchange? 

Yes, Bitforex.com

• Is a Smart Contract audit completed? Where can we find this information?
Our contract is renounced (ownership to dead address) so we don't have any control over contract, in such case no audit is required.

**Comment by Cryptocool1** [comment]
We still require an audit even when your contract renounced

**Comment by catcoincom** [comment]
> We still require an audit even when your contract renounced

will update with audit report in next 24-48 hr

**Comment by Cryptocool1** [comment]
We require an audit from reputable companies (Techrate, Certik, Hacken, Dessert Finance) 
Fee free to come back to us once all criteria are met.

**Comment by catcoincom** [comment]
This is not mentioned in requirement that we need to present audit report as well, you are requesting this information after payment. Our contract is already renounced and there is no point of doing audit by paying 5K USD  to such platform,Will you please show us where Trust wallet have mentioned that we need audit report for approval ?

**Comment by catcoincom** [comment]
[Catcoin - Renounced Smart Contract Security Report.pdf](https://github.com/trustwallet/assets/files/14150750/Catcoin.-.Renounced.Smart.Contract.Security.Report.pdf)
Please check this report by https://www.rdauditors.com/  @Cryptocool1

**Comment by catcoincom** [comment]
@Cryptocool1 will you please confirm about audit ?

**Comment by catcoincom** [comment]
@Cryptocool1  here is audit report link from Dessert Finance 

https://dessertswap.finance/audits/Catcoin-BSC-ETH-Audit-35903726.pdf

Kindly check and approve our listing

**Comment by catcoincom** [comment]
@cryptomanz1 @Cryptocool1 please upate

**Comment by catcoincom** [comment]
@Cryptocool1 @cryptomanz1 @natedaiger @hexorx  we filled all condition will you please approve our listing or i need to crate again

**Pull request closed without merging**
