### PR TITLE
Add DGCL logo of token for Trustwallet and Uniswap

### PR DESCRIPTION
**Pull request by thompson-shi**
Please add the logo of DGCL token for Trustwallet and Uniswap

### CODE REVIEW

**Comment by thompson-shi** [comment]
Transferred 250 TWT to the designated address with memo, thanks

**Comment by thompson-shi** [comment]
hi @catenocrypt, great, I can see the DGCL token logo now is on Uniswap. 

May I ask when we can see the token logo also on Trust Wallet? The Trust Wallet shows the DGCL token logo as "ERC 20" as of now, thanks

**Comment by catenocrypt** [comment]
It takes a few hours until caches expire, but I can already see it in the TW app with the updated logo.

**Comment by thompson-shi** [comment]
thanks. I can see the token logo now on Trust Wallet

**Pull request merged**
