### PR TITLE
Add DOOR Token logo and information.

### PR DESCRIPTION
**Pull request by tom-copeland**
We published DOOR token and going to register the logo into Trustwallet. 
This is our website information. - https://doortoken.org/
This is our token information - https://doortoken.gitbook.io/door-token/
This is our contract on ETH. - https://etherscan.io/token/0x7d48fbe0a877bb1f511fcf9b57f12420c75841e9

Thank you.

### CODE REVIEW

**Comment by Cryptocool1** [comment]
hello,
can you answer some questions?
• What is the purpose of this token? How will it benefit Trust Wallet users?
 • How is the token being distributed? Are you conducting an airdrop?
 • Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?
 • Is the token listed on a centralized/decentralized exchange?
 • Is a Smart Contract audit completed? Where can we find this information?

**Comment by tom-copeland** [comment]
• What is the purpose of this token? How will it benefit Trust Wallet users?
DOOR connects consumers and advertisers to facilitate transactions that reward consumers for the authorized use of their data. Every time a consumer's data is used for commercial use they are rewarded with DOOR Tokens. Advertisers purchase DOOR Tokens to be used for licensing authorized data from Consumers. By eliminating the middleman, the consumer and business can benefit from a direct connection via DOOR. We already have thousands of users and they can use Door Token on Trust Wallet if we publish it into Trust Wallet.
https://doortoken.gitbook.io/door-token/door/door-token

 • How is the token being distributed? Are you conducting an airdrop?
The token is being distributed inside our platform(doortoken.org). The business model is similar to any marketplace or exchange. The Property Owner (Seller) has a valuable product (Data) and is publishing to an open marketplace (Door Lead Exchange). The Advertiser (Buyer) is looking for new customer opportunities (Leads) and will buy Data on the marketplace. We are using DoorToken inside all transactions. 
https://doortoken.gitbook.io/door-token/door/how-it-works

• Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?
Yes. We already did. 
https://v2.info.uniswap.org/token/0x7d48fbe0a877bb1f511fcf9b57f12420c75841e9

- Is the token listed on a centralized/decentralized exchange?
Yes. 
https://v2.info.uniswap.org/token/0x7d48fbe0a877bb1f511fcf9b57f12420c75841e9
https://coinmarketcap.com/currencies/door/

• Is a Smart Contract audit completed? Where can we find this information?
Yes. We already did before published. 
[AuditReportOfDOOR.pdf](https://github.com/trustwallet/assets/files/6947003/AuditReportOfDOOR.pdf)
Attached audit result report here. - We already fixed the issues from the Audit Report before publishing our token.

**Comment by Cryptocool1** [comment]
can you add links to your PR please?

**Comment by Cryptocool1** [comment]
see the example here:
https://developer.trustwallet.com/add_new_asset/repository_details

**Pull request merged**
