### PR TITLE
Add VEKTOR (BEP20)

### PR DESCRIPTION
**Pull request by dark-sizter**
Adding info for BEP20 token 'VEKTOR'.

PR created by <a href="https://assets.trustwallet.com">TW Assets Management</a>

### CODE REVIEW

**Comment by dark-sizter** [comment]
here is a link to the audit 
https://www.crypto-vektor.com/images/Smart-Contract-Audit-Report.pdf

**Comment by cryptomanz** [comment]
• What is the purpose of this token? How will it benefit Trust Wallet users?
 • How is the token being distributed? Are you conducting an airdrop?
 • Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?
 • Is the token listed on a centralized/decentralized exchange?

**Comment by dark-sizter** [comment]
We are a digital agency with an international team of workers and customers. Our token is for the main purpose of purchase of service and payment of freelancers through our platform. To trust wallet users who want to purchase service from us, this token makes it easier and transparent.

No, we did not conduct an airdrop 

We did not conduct ICO and presale 

The token is listed on pancakeswap, BankCex and Vindax

**Comment by dark-sizter** [comment]
@Cryptocool1 please merge

**Comment by Cryptocool1** [comment]
Hello, 
As per our policy, brand new tokens are not included, there is a minimum requirement of 10,000 holder addresses and 15,000 transactions, in order to filter out scam tokens.
See the criteria at : https://developer.trustwallet.com/assets/requirements .

**Comment by Cryptocool1** [comment]
We accept only techrate, certik, hacken, dessert finance audits

**Comment by cryptomanz** [comment]
Please come back to us when all criteria are met.
When creating a new PR make sure to mention this PR, so that we can see that fee has been paid already here.

**Pull request closed without merging**
