### PR TITLE
Add Monetas

### PR DESCRIPTION
**Pull request by monetas26**

### CODE REVIEW

**Comment by cryptomanz** [comment]
Hello!
- This is a BEp20 token, correct folder is blockchains/smartchain/assets. 
- https://community.trustwallet.com/t/how-to-submit-a-token-logo/3863).

**Comment by monetas26** [comment]
Add Monetas

**Comment by monetas26** [comment]
Yes This is BEP20 Token

**Comment by monetas26** [comment]
logo

**Comment by monetas26** [comment]
Which File You Required

**Review by monetas26 — COMMENTED** [review]
logo

**Comment by Cryptocool1** [comment]
> Which File You Required

This is a BEp20 token, correct folder is blockchains/smartchain/assets.
https://community.trustwallet.com/t/how-to-submit-a-token-logo/3863).

**Comment by monetas26** [comment]
logo

**Comment by Cryptocool1** [comment]
still incorrect
Please create new PR, follow doc https://community.trustwallet.com/t/how-to-submit-a-token-logo/3863
You may want to try our new Assets app in beta; go to https://assets.trustwallet.com, log on with Github, enter contract ID, logo and some additional info, and it will create a PR for you.
See https://community.trustwallet.com/t/how-to-submit-a-token-logo-using-assets-app/82957.

When creating new PR, mention this PR, so that fee can be reused, and not paid again.

**Comment by monetas26** [comment]
> blockchains/smartchain/assets.

Changes Done Check and verify

**Pull request closed without merging**
