### PR TITLE
Add PAWSWAP (PAW) (ERC20)

### PR DESCRIPTION
**Pull request by perypaw**
Adding info for ERC20 token 'PAWSWAP (PAW)'.

PR created by <a href="https://assets.trustwallet.com">TW Assets Management</a>

### CODE REVIEW

**Comment by perypaw** [comment]
To prevent potential fraud for cryptocurrency users, we aim to expedite the listing of $PAW on Trust Wallet, in addition to its current listings on multiple exchanges such as Gate.io, Bitget, and LBank.

https://www.gate.io/de/trade/PAW_USDT
https://www.bitget.com/en/support/articles/12560603777382

**Comment by perypaw** [comment]
please remove "blog" link

**Comment by Cryptocool1** [comment]
• What is the purpose of this token? How will it benefit Trust Wallet users?
 • How is the token being distributed? Are you conducting an airdrop?
 • Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?
 • Is the token listed on a centralized/decentralized exchange?
 • Is a Smart Contract audit completed? Where can we find this information?

**Comment by Cryptocool1** [comment]
- As per our policy, there is a minimum requirement of 10,000 holder addresses and 15,000 transactions.
See the criteria at : https://developer.trustwallet.com/listing-new-assets/requirements .
-we require smart contract audit from reputable companies (Techrate,Certik,Hacken,Dessert Finance)
- we require CMC listing

**Comment by Cryptocool1** [comment]
Please come back to us once all criteria are met, make sure to mention this PR so the fee can be reused

**Comment by perypaw** [comment]
PAWSWAP is on major exchanges like Gateio, Bitget, Lbank, and listed on Coinmarketcap with over 15k transactions and nearly 5k holders.

**Comment by Cryptocool1** [comment]
Nice,
 come back to us once audit and holders requirements are met.

**Pull request closed without merging**
