### PR TITLE
Add DFG Token logo

### PR DESCRIPTION
**Pull request by Shyamthakur33**
Token name - Defi Gamble
Token symbol - DFG
Decimal - 6
Smart Contract - 0x08d6E6B487f0d402160C8038eC0210FCdE6CA570

### CODE REVIEW

**Comment by zachzwei** [comment]
Please provide more details about this token.
You can follow this guide to add an info.json to this submission.
https://community.trustwallet.com/t/how-to-add-the-token-information/3888

**Comment by Shyamthakur33** [comment]
sir, I am unable to understand this visual mode guide to an open JSON file, I am using window 10 laptop. please help how to open

**Comment by zachzwei** [comment]
> sir, I am unable to understand this, neither i am using Github desktop nor visual studio code, I simply open this logo.png file by fork/blockchains/ethereum/assets and then added folder there so pls tell easy way to add json.file

Create a file named info.json and it should contain details about the token.
Here is an example:

```
 {
   "name":"Bitcoin",
   "website":"https://bitcoin.org",
   "source_code":"https://github.com/bitcoin",
   "white_paper":"https://bitcoin.org/bitcoin.pdf",
   "short_description":"Bitcoin is a cryptocurrency and worldwide payment system.",
   "explorer":"https://blockchain.info",
   "research":"https://research.binance.com/en/projects/bitcoin"
}

Then just drag the file to the same location as the logo.png

**Comment by Shyamthakur33** [comment]
Please check sir, i have added json.info file

**Pull request merged**
