### PR TITLE
Adding PHIBA log and info

### PR DESCRIPTION
**Pull request by dstout01**

### CODE REVIEW

**Comment by Cryptocool1** [comment]
PR should include only 2 files:
logo.png and info.json

**Comment by dstout01** [comment]
I thought I only uploaded 2 files. How do I resolve this?

**Comment by Cryptocool1** [comment]
Please create new PR, follow doc https://community.trustwallet.com/t/how-to-submit-a-token-logo/3863
You may want to try our new Assets app in beta; go to https://assets.trustwallet.com, log on with Github, enter contract ID, logo and some additional info, and it will create a PR for you.
See https://community.trustwallet.com/t/how-to-submit-a-token-logo-using-assets-app/82957.
you don't need to pay one more time

**Comment by dstout01** [comment]
New Pull request created #8630 for Papa Shiba logo.

Original Request #8570

Please let me know if anything else is needed

Thank you for your help Darrell Stout

**Pull request closed without merging**
