### PR TITLE
Add Terawatt LED Token

### PR DESCRIPTION
**Pull request by ronnie173**
This PR is being closed due to inactivity. If you wish to continue, please reopen the PR before sending your payment.
Do NOT send payments for closed PR, as the fee may by lost!
  (60 vs. 60 hrs)

### CODE REVIEW

**Comment by ronnie173** [comment]
How to open a closed pull request? I am ready to pay now

**Comment by ronnie173** [comment]
Hi I paid but the bot is saying wrong date. How can this be fixed.

**Comment by ronnie173** [comment]
> @ronnie173, kind reminder: please pay fee: **1000 TWT** with the memo **2678** to the address `bnb1tqq9llyr3dyjd559dha6z5r5etk3qfwk07m098`.
> Alternatively, 1 BNB is also accepted (same memo & address).
> 
> **QR** code: [Trust](https://api.qrserver.com/v1/create-qr-code/?size=200x200&data=https%3A%2F%2Flink.trustwallet.com%2Fsend%3Fcoin%3D714%26address%3Dbnb1tqq9llyr3dyjd559dha6z5r5etk3qfwk07m098%26amount%3D1000%26memo%3D2678) | [other wallet](https://api.qrserver.com/v1/create-qr-code/?size=200x200&data=bnb1tqq9llyr3dyjd559dha6z5r5etk3qfwk07m098%26amount%3D1000%26memo%3D2678)
> See the [Pull Request Fee FAQ](https://developer.trustwallet.com/add_new_asset/pr-fee).

Something i wrong with this bot. I paid the money. Someone please fix this

**Comment by catenocrypt** [comment]
@ronnie173 , could you state the TXID or date of your payment, so we can verify manually?

**Comment by ronnie173** [comment]
Transaction id
is 1FB62A2DB741109F28697084A8A3EBA7E974F7B4B15ECB47B8512477D70D746F
https://explorer.binance.org/tx/1FB62A2DB741109F28697084A8A3EBA7E974F7B4B15ECB47B8512477D70D746F

**Comment by catenocrypt** [comment]
Marking as paid manually, was paid while closed.
https://explorer.binance.org/tx/1FB62A2DB741109F28697084A8A3EBA7E974F7B4B15ECB47B8512477D70D746F

**Comment by catenocrypt** [comment]
Contract folder renamed to correct checksum format.

**Pull request merged**
