### PR TITLE
Add LIFE(BEP20) logo and info

### PR DESCRIPTION
**Pull request by LifeInfinityMetaverse**
This is a request to add logo and info for Life Infintiy Token(BEP20).

### CODE REVIEW

**Review by LifeInfinityMetaverse — COMMENTED** [review]
Update some json format errors

**Review by LifeInfinityMetaverse — COMMENTED** [review]
fix some format errors of info.json

**Review by LifeInfinityMetaverse — COMMENTED** [review]
update some errors

**Comment by Cryptocool1** [comment]
Please create new PR, follow doc https://developer.trustwallet.com/assets/requirements
You may want to try our Assets app in beta; go to https://assets.trustwallet.com, log on with Github, enter contract ID, logo and some additional info, and it will create a PR for you.
See https://developer.trustwallet.com/assets/repository_details

**Pull request closed without merging**
