### PR TITLE
Add finance.vote (ERC20)

### PR DESCRIPTION
**Pull request by illuzen**
Adding info for ERC20 token 'finance.vote'.

PR created by <a href="https://assets.trustwallet.com">TW Assets Management</a>

### CODE REVIEW

**Comment by Cryptocool1** [comment]
As per our policy, brand new tokens are not included, there is a minimum requirement of 5000 holder addresses and 10000 transactions, in order to filter out scam tokens.
See the criteria at (mentioned in the first message by the bot): https://community.trustwallet.com/t/how-to-submit-a-token-logo/3863).

**Comment by illuzen** [comment]
@Cryptocool1 I appreciate your filter, but we have been around for nearly a year, as you can see on etherscan here: https://etherscan.io/token/0x45080a6531d671DDFf20DB42f93792a489685e32

Our first transaction was 254 days ago: 
https://etherscan.io/tx/0x20b7c25923ec05e8f98e78be0f1931e2f26a782cb136e3d4740de3d11f263953

We have several apps that use our token, which you can see here: 
- https://marketsdotvote.eth.link/
- https://yielddotvote.eth.link/
- https://influencedotvote.eth.link/
- https://bankdotvote.eth.link/

We have nearly 20,000 transactions on our token alone. The README of this repository says 2500 holders, which we have. Is there anyway we could move forward and just close this tab?

**Comment by illuzen** [comment]
@catenocrypt @zachzwei could I get some help with this? ^^^

**Comment by Cryptocool1** [comment]
hello,
• What is the purpose of this token? How will it benefit Trust Wallet users?
 • How is the token being distributed? Are you conducting an airdrop?
 • Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?
 • Is the token listed on a centralized/decentralized exchange?
 • Is a Smart Contract audit completed? Where can we find this information?

**Comment by illuzen** [comment]
hello @Cryptocool1 

The token is used 
- to purchase identities in our prediction market
- to stake in our yield farms
- to vote in our governance decisions, as well as our "what token next" polls

The token was distributed thru multiple methods
- we did a presale in Q3 2020
- we did an initial-dex-offering, pushing liquidity to uniswap in Q3 2020
- we distribute the token as rewards to liquidity providers and correct predictors in our prediction markets
- we recently airdropped to some members of our new partner, the ethtrader subreddit 

The token is listed on uniswap, sushiswap, and Bilaxy. 

We have had several audits of various components of our system, which you can view here: https://gitlab.com/finance.vote/audits

Please let me know if you have any other questions. :smile:

**Comment by illuzen** [comment]
@Cryptocool1 @catenocrypt @zachzwei 

Are there any other questions? We're happy to provide any additional materials to support your due diligence.

**Pull request merged**
