### PR TITLE
Adding ADACash Logo to Trustwallet

### PR DESCRIPTION
**Pull request by ADACashOfficial**
Adding ADACash Logo and Information to Trustwallet

### CODE REVIEW

**Comment by ramsty** [comment]
Hi!
You can add links to your PR following this example: 
https://developer.trustwallet.com/assets/repository_details
description Utility token

**Comment by ADACashOfficial** [comment]
ok i dont know.. do i miss something here..

**Comment by ADACashOfficial** [comment]
finally..  i am so sorry haha

**Comment by ramsty** [comment]
Hi!
Could you answer some questions?
• What is the purpose of this token? How will it benefit Trust Wallet users?
• How is the token being distributed? Are you conducting an airdrop?
• Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?
• Is the token listed on a centralized/decentralized exchange?
• Is a Smart Contract audit completed? Where can we find this information?

**Comment by ADACashOfficial** [comment]
Hello, of course, no problem

• What is the purpose of this token? How will it benefit Trust Wallet users?
The purpose of this token is currently to earn 10% Cardano Bep20 automatically in your wallet up to every 60 minutes, depends on the hourly trading volume.  More coming , like NFT Gaming and Own Swap / Staking & Farming Pools

• How is the token being distributed? Are you conducting an airdrop?
The token was a fair launch , just started 11 Days ago.  No Airdrops are planned as of now. We are on heavy marketing at the moment and well doing. But i saw there is a way to do airdrops with trustwallet? Could be interesting, if there is a way, just let me know

• Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?
No Tokens were sold, also no dev wallets.

• Is the token listed on a centralized/decentralized exchange?
It is listed on pancakeswap currently. For the next 1 year there is no plan to move to any other exchanges.

• Is a Smart Contract audit completed? Where can we find this information?
We have a full smart contract audit from Techrate its on the website. but here is the link also: 

https://github.com/TechRate/Smart-Contract-Audits/blob/main/October/ADAcash%20Full%20Smart%20Contract%20Security%20Audit.pdf

**Pull request merged**
