### PR TITLE
Add Pax Gold (POLYGON)

### PR DESCRIPTION
**Pull request by razorrahim**
Adding info for POLYGON token 'Pax Gold'.

PR created by <a href="https://assets.trustwallet.com">TW Assets Management</a>

### CODE REVIEW

**Comment by razorrahim** [comment]
Totally agreed that the Polygon version of PAXG does not meet the holder and transaction requirements yet.


However, I was wondering if you might consider making an exception in this case as the Ethereum version of PAXG has over [20,000](https://etherscan.io/token/0x45804880de22913dafe09f4980848ece6ecbaf78) holders and almost [600,000](https://etherscan.io/token/0x45804880de22913dafe09f4980848ece6ecbaf78) transactions, not to mention a market cap of a half billion US dollars backed by gold in Brink's vaults in London?

The Polygon mapping of this token was [done](https://polygonscan.com/tx/0xded34220ab58ede4c939cf6817d99ead3a0fc2ed9d94252c4c14570679e4bd28) a year and a half ago, but liquidity and volume has only started picking up on Polygon in the last few months with Quickswap's promotion via yield farming rewards - Quickswap already supports the official logo.


If not, no worries - thanks for your time anyhow. Perhaps we can speak again once the Polygon version of PAXG meets Trust Wallet's requirements as the Ethereum version already has.

**Comment by Cryptocool1** [comment]
submission looks good, awaiting for the fee payment

**Comment by razorrahim** [comment]
Awesome - thank you

**Comment by Hadijafari1** [comment]
کسی هست بتونه ۱۰ هزار دلار بهم کمک کنه یه مریض دارم تورا خدا اگه میتونید
به آدرس زیر واریر کنید 0x3f3135076fB90c1aeE0B36Adf0d7Ad588765D1

در تاریخ چهارشنبه ۱۲ اکتبر ۲۰۲۲،‏ ۱۱:۳۵ razorrahim ***@***.***>
نوشت:

**Pull request merged**
