### PR TITLE
phoswap.io logo

### PR DESCRIPTION
**Pull request by phoswap**
Thank you!

### CODE REVIEW

**Comment by catenocrypt** [comment]
Could you remove the second, empty file?  

image

**Comment by phoswap** [comment]
Paid 2 BNB. Thank you!

**Comment by phoswap** [comment]
Hi, 2 BNB paid. Please check! Thank you very much.

Phoswap Team

**Comment by phoswap** [comment]
Fee paid

**Comment by phoswap** [comment]
Hi, we paid 2 BNB for logo but we accidentally deleted #4359 please help! Thanks!

Phoswap

**Comment by phoswap** [comment]
Fee paid Please check thank you!
https://explorer.binance.org/tx/1B92B8646CC4EEC47B8AB285900A4AB2E4DE8B0EFB217B2C0B45BECFF20B17CF

**Comment by phoswap** [comment]
Hi, when will you list Phoswap (PHO) logo? What is the problem?

Phoswap Team

**Pull request merged**
