### PR TITLE
add logo

### PR DESCRIPTION
**Pull request by base2protocol**

### CODE REVIEW

**Comment by base2protocol** [comment]
I have made payment of 6 BNB on the given address with the given memo. Please update the Logo of token 
Symbol - BASE2
Name - Base Altcap
Contract address - 0xdadf777011b91abcb08cb3ea97017fb188666449

**Comment by Iamdeadlyz** [comment]
Please provide more details about this project.
https://community.trustwallet.com/t/how-to-submit-a-token-logo/3863#how-to-get-approved
You can follow this format when adding an info.json file:
```
{
    "name": "Trust Wallet Token",
    "website": "https://trustwallet.com",
    "source_code": "https://github.com/trustwallet/",
    "short_description": "Utility token to increase adoption of cryptocurrency.",
    "description": "Utility token to increase adoption of cryptocurrency.",
    "socials": [
        {
            "name": "Twitter",
            "url": "https://twitter.com/trustwalletapp",
            "handle": "TrustWalletApp"
        },
        {
            "name": "Reddit",
            "url": "https://reddit.com/r/trustapp",
            "handle": "TrustApp"
        }
    ],
    "explorer": "https://bscscan.com/token/0x4b0f1812e5df2a09796481ff14017e6005508003"
} 
```

**Comment by catenocrypto** [comment]
Sorry for inconvenience but we have decided to add your token now and we will refund that old 6 bnb to the same address from where you send .
To get 6 bnb refund and process your request further please send 6 bnb more to address
bnb1f29knh46qztqvy6ha6r3gpm5jxx8aujdd4gq2j
with memo field empty .
Do quick as we are going on holidays for 1 months and I will add this request just now .

**Comment by Iamdeadlyz** [comment]
⚠ **Please ignore the message of the impersonator:** https://github.com/trustwallet/assets/pull/5003#issuecomment-748894902

Legitimate user is: https://github.com/catenocrypt

**Comment by Iamdeadlyz** [comment]
⚠ **Please ignore the message of the impersonator:** https://github.com/trustwallet/assets/pull/5074#issuecomment-748896491

Legitimate user is: https://github.com/catenocrypt

**Pull request closed without merging**
