### PR TITLE
Add MONO logo and info

### PR DESCRIPTION
**Pull request by phongpt156**

### CODE REVIEW

**Comment by ramsty** [comment]
Hi!
Could you answer some questions?
• What is the purpose of this token? How will it benefit Trust Wallet users?
• How is the token being distributed? Are you conducting an airdrop?
• Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?
• Is the token listed on a centralized/decentralized exchange?
• Is a Smart Contract audit completed? Where can we find this information?

**Comment by phongpt156** [comment]
• What is the purpose of this token?
The token will be used on our blockchain gaming and NFT projects call The Monopolist.

How will it benefit Trust Wallet users?
In The Monopolist, the players will build their own tactics through rolling dice, investing in buying land, building properties, collecting accommodation fees, and so on, to win the others by various ways. When you become the winner of any battles, you will earn $MONO and $MOB token, especially have chances to receive new characters, materials or items, which you can bring to NFT market for more earnings.
• How is the token being distributed? Are you conducting an airdrop?
Token was distributed to the presale/ido participants. New users can buy on Pancakeswap and other exchange in future.
We also conducting an airdrop

• Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?
We did the IDO on the Binstarter and Poolz launchpad.

• Is the token listed on a centralized/decentralized exchange?
DEX: We are on the following DEX
Pancakeswap: https://pancakeswap.finance/swap?outputCurrency=0xD4099A517f2Fbe8a730d2ECaad1D0824B75e084a

• Is a Smart Contract audit completed? Where can we find this information?
Yes. Audit was done by a Verichains
Link: https://github.com/verichains/public-audit-reports/blob/main/Verichains%20Public%20Audit%20Report%20-%20TheMonopolist%20-%20v1.1.pdf

**Comment by phongpt156** [comment]
> Hi! Could you answer some questions? • What is the purpose of this token? How will it benefit Trust Wallet users? • How is the token being distributed? Are you conducting an airdrop? • Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale? • Is the token listed on a centralized/decentralized exchange? • Is a Smart Contract audit completed? Where can we find this information?

**Comment by phongpt156** [comment]
> Hi! Could you answer some questions? • What is the purpose of this token? How will it benefit Trust Wallet users? • How is the token being distributed? Are you conducting an airdrop? • Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale? • Is the token listed on a centralized/decentralized exchange? • Is a Smart Contract audit completed? Where can we find this information?

Hi, pls check my reply

**Pull request merged**
