### PR TITLE
Add files via upload

### PR DESCRIPTION
**Pull request by AcapSLP**
Adding logo for Freedom Reserve (FR)<- genuine token, to prevent users accidentally buying Freedom Reserve (FRC) SCAM copycat token! on uniswap. 

We are a young community but a genuine project we desperately need our token to be clearly separated from the above scam copycat token. Please help us! thank you.

https://freedomreserv.eth.link
/ipns/freedomreserv.eth
https://freedomreserv.eth.link/img/FreedomReserveWhitepaper.pdf
https://t.me/freedomreserve1
https://discord.gg/Q9UPTTQ

### CODE REVIEW

**Comment by catenocrypt** [comment]
As per our policy, brand new tokens are not included, there is a minimum requirement of 2500 holder addresses and 5000 transactions, in order to filter out scam tokens.
See the criteria at (mentioned in the first message by the bot): https://community.trustwallet.com/t/how-to-submit-a-token-logo/3863#how-to-get-approved
This token has below-limit usage yet (335). Rejecting PR for now. Please come back to us when all criteria are met.

https://etherscan.io/token/0xC626e0619aC79AFEa9281c8eB9b1a9f9D3Fab532

**Comment by AcapSLP** [comment]
> As per our policy, brand new tokens are not included, there is a minimum requirement of 2500 holder addresses and 5000 transactions, in order to filter out scam tokens.
> See the criteria at (mentioned in the first message by the bot): https://community.trustwallet.com/t/how-to-submit-a-token-logo/3863#how-to-get-approved
> This token has below-limit usage yet (335). Rejecting PR for now. Please come back to us when all criteria are met.
> 
> https://etherscan.io/token/0xC626e0619aC79AFEa9281c8eB9b1a9f9D3Fab532

Hi, I didn't see this reply before I sent the TWT to your address.  Please can you help me? can you send me back the TWT that it took me a long time to install trustwallet and get BNB and TWT and also

**Comment by AcapSLP** [comment]
Have a heart man, that was a lot of money for us. I am not a scammer. a scammer token has enough money to airdrop to thousands of addresses and pay for marketing we are a hobby project. please send us back our TWT!

**Comment by catenocrypt** [comment]
> Have a heart man, that was a lot of money for us

What money are you referring to?  There was no fee paid for this PR.

**Comment by catenocrypt** [comment]
Found payment for this PR, considering it for #5162 .
Tx https://explorer.binance.org/tx/9AD89AB7515C0E12EF47AB4DB2D587F5C8311A80D69909FF65A5430C5A1805C1

**Pull request closed without merging**
