### PR TITLE
Add ECG (BEP20)

### PR DESCRIPTION
**Pull request by Superpower-Squad-official**
Adding info for BEP20 token 'ECG'.

PR created by <a href="https://assets.trustwallet.com">TW Assets Management</a>

### CODE REVIEW

**Comment by Superpower-Squad-official** [comment]
@Cryptocool1  Hi i transfered the token right after the submission, but now the case is closed, this is the hash https://explorer.bnbchain.org/tx/410CD6EC96EBF9872F5CFDD8EB8B4CAFB4B732644368647141B9CAFD0360B580. Could you please have a look on this?
https://github.com/trustwallet/assets/pull/23415
https://github.com/trustwallet/assets/pull/23417
I'm so, so sorry.

**Comment by Cryptocool1** [comment]
As per our policy, brand new tokens are not included, there is a minimum requirement of 10,000 holder addresses and 15,000 transactions, in order to filter out scam tokens.
See the criteria at : https://developer.trustwallet.com/assets/requirements .

**Comment by Cryptocool1** [comment]
Are you listed on CoinMarketCap?
Is a Smart Contract audit completed? Where can we find this information?

**Comment by Superpower-Squad-official** [comment]
> As per our policy, brand new tokens are not included, there is a minimum requirement of 10,000 holder addresses and 15,000 transactions, in order to filter out scam tokens.
> See the criteria at : https://developer.trustwallet.com/assets/requirements .

https://coinmarketcap.com/currencies/superpower-squad-ecg

**Comment by Superpower-Squad-official** [comment]
> Are you listed on CoinMarketCap?
> Is a Smart Contract audit completed? Where can we find this information?

https://coinmarketcap.com/currencies/superpower-squad-ecg

**Comment by Cryptocool1** [comment]
Is a Smart Contract audit completed? Where can we find this information?

**Comment by Cryptocool1** [comment]
Please come back to us once all criteria are met. Make sure to mention this PR so the fee can be reused.

**Pull request closed without merging**
