### PR TITLE
Add JAWS logo and info

### PR DESCRIPTION
**Pull request by ggmatch-mod**
The folder contains the json file required and the 256x256 transparent png file for the logo.

### CODE REVIEW

**Comment by ggmatch-mod** [comment]
Is there something i need to change or some additional things i need to provide?

**Comment by cryptomanz** [comment]
As per our policy, brand new tokens are not included, there is a minimum requirement of 5000 holder addresses and 10000 transactions, in order to filter out scam tokens.
See the criteria at (mentioned in the first message by the bot): https://community.trustwallet.com/t/how-to-submit-a-token-logo/3863).

**Comment by ggmatch-mod** [comment]
> As per our policy, brand new tokens are not included, there is a minimum requirement of 5000 holder addresses and 10000 transactions, in order to filter out scam tokens.
> See the criteria at (mentioned in the first message by the bot): https://community.trustwallet.com/t/how-to-submit-a-token-logo/3863).

Many users are fully stacked in our single staking pool or actually used all their tokens for LPs. We'll ask them to unstake to meet the requirement. Will update this in the next 12 hours.

**Comment by ggmatch-mod** [comment]
We now satisfy the 5000 holders threshold, according to bscscan.

**Comment by Cryptocool1** [comment]
hello,
• What is the purpose of this token? How will it benefit Trust Wallet users?
 • How is the token being distributed? Are you conducting an airdrop?
 • Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?
 • Is the token listed on a centralized/decentralized exchange?
 • Is a Smart Contract audit completed? Where can we find this information?

**Comment by ggmatch-mod** [comment]
> hello,
> • What is the purpose of this token? How will it benefit Trust Wallet users?
> • How is the token being distributed? Are you conducting an airdrop?
> • Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?
> • Is the token listed on a centralized/decentralized exchange?
> • Is a Smart Contract audit completed? Where can we find this information?

1) JAWS is the governance token and fees redistribution for the autoshark yield optimizer platform.
Its holders (will) receive the corresponding voting power

**Comment by Cryptocool1** [comment]
Hello,
- Awaiting for smart contract audit.

**Comment by Cryptocool1** [comment]
can you please add links to your PR?
example: https://developer.trustwallet.com/add_new_asset#info-json-contents

**Comment by ggmatch-mod** [comment]
Here Is the link to our audit: 

> Hello,
> 
> * Awaiting for smart contract audit.

https://github.com/Watch-Pug/Audits/blob/main/AutoShark%20Audit%20Report.pdf

**Comment by Cryptocool1** [comment]
can you please add links to your PR?
example: https://developer.trustwallet.com/add_new_asset#info-json-contents

**Pull request merged**
