### PR TITLE
Add logo for DITTO token

### PR DESCRIPTION
**Pull request by chefchansey**
Add logo for DITTO token on Binance smart chain.

NOTE: Most holders are staking their tokens so number of individual wallets is not representative of number of holders.

### CODE REVIEW

**Comment by Timidan** [comment]
https://explorer.binance.org/tx/7D6A8A6E0995FD1AECD55795B95D90A2D40874DA4062CB533DAC6648DE0785B8

Here is the txn hash on the Binance Chain

**Comment by chefchansey** [comment]
Thanks @Timidan! I transferred [0.3 ETH directly to your account](https://etherscan.io/tx/0xbd85cc80bf8196a9405850ebbd0db3b41bcacad4eace11a9006bbd1297298c87) which should cover your cost and bounty:

1,000 TWT + 0.000375 TX fee = 0.202 ETH + Bounty: 0.09 ETH = ~0.3 ETH

Please visit us on Telegram if you have questions or are looking for more BSC work 😉

https://t.me/dittomoney

**Comment by Timidan** [comment]
Thanks...i will surely show up on Telegram for more work....i'll submit the airdrop batch contract asap!

**Comment by catenocrypt** [comment]
Please add an `info.json` file next to the `logo.png`, with info about the project, of the form:

```json
{
    "name": "Trust Wallet Token",
    "website": "https://trustwallet.com",
    "short_description": "Utility token to increase adoption of cryptocurrency.",
    "explorer": "https://etherscan.io/token/0xA866F0198208Eb07c83081d5136BE7f775c2399e",
    "socials": [
        {
            "name": "Twitter",
            "url": "https://twitter.com/trustwalletapp",
            "handle": "TrustWalletApp"
        },
        {
            "name": "Reddit",
            "url": "https://reddit.com/r/trustapp",
            "handle": "TrustApp"
        }
    ]
}
```

You may want to try our new Assets app in beta;  close this PR; go to https://assets.trustwallet.com, log on with Github, enter contract ID, logo and some additional info, and it will create a PR for you.
See  https://community.trustwallet.com/t/how-to-submit-a-token-logo-using-assets-app/82957.

**Comment by chefchansey** [comment]
@catenocrypt info.json has been added 😊

**Pull request merged**
