### PR TITLE
Add Fishkoin (BEP20)

### PR DESCRIPTION
**Pull request by BHCHappiness**
Adding info for BEP20 token 'Fishkoin'.

PR created by <a href="https://assets.trustwallet.com">TW Assets Management</a>

### CODE REVIEW

**Comment by BHCHappiness** [comment]
Hello I'm back again. :) I already paid. Thank you team

**Comment by BHCHappiness** [comment]
Please take note that BHC, HPS and 4TOKEN become 1 project (KOIN)

Proof:
https://x.com/BHC_Happiness/status/1771364269277503693?s=20
https://x.com/ignore_fud/status/1771365029746766290?s=20

Thank you team

**Comment by Cryptocool1** [comment]
• What is the purpose of this token? How will it benefit Trust Wallet users?
 • How is the token being distributed? Are you conducting an airdrop?
 • Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?
 • Is the token listed on a centralized/decentralized exchange?
 • Is a Smart Contract audit completed? Where can we find this information?

**Comment by BHCHappiness** [comment]
> • What is the purpose of this token? How will it benefit Trust Wallet users?

Fishkoin is a memecoin and we will use Trust wallet to safe-keep our KOIN token.

> • How is the token being distributed? Are you conducting an airdrop?

Fishkoin $KOIN is an amalgamation of Billion Happiness (BHC), Happiness Token (HPS), and Ignore Fud ​(4TOKEN). We distributed it via airdrop upgrade.

This unique combination encapsulates the essence of strength, adaptability, and survival, which is evident ​in these three projects and also in the attributes of a KOI fish, from which the name was derived. 

> • Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?

No ICO

> • Is the token listed on a centralized/decentralized exchange?

Yes on pancakeswap
Chart here: https://www.dextools.io/app/en/bnb/pair-explorer/0x8dac3ecd537c88063755453e11ff1e14697eefb8?t=1711529161427


> • Is a Smart Contract audit completed? Where can we find this information?

We renounced our ownership to ensure investors safety. 

Proof: https://bscscan.com/tx/0xfe25fce004584bc9acd1196859590414dab0b47f7bed9228e115fecc606692a9

**Comment by BHCHappiness** [comment]
@Cryptocool1 I will wait for the update. Thank you sir

**Comment by Cryptocool1** [comment]
Hello, we require smart contract audit from reputable companies, please take a look at our documentation

**Comment by BHCHappiness** [comment]
> Hello, we require smart contract audit from reputable companies, please take a look at our documentation

Our projects is already audited on Certik this KOIN is only an upgrade

Ignore FUD: https://skynet.certik.com/projects/ignore-fud
BHC: https://skynet.certik.com/projects/billionhappiness

and Certik is following me on twitter:

My twitter: https://twitter.com/BHC_Arnel

**Comment by BHCHappiness** [comment]
Please check @Cryptocool1 and thank you so much.  We love Trust wallet

**Comment by BHCHappiness** [comment]
Update us @Cryptocool1 our community is so excited about Trust Wallet

**Comment by Cryptocool1** [comment]
Hello, we require smart contract audit of the token you are trying to add.

**Comment by BHCHappiness** [comment]
> Hello, we require smart contract audit of the token you are trying to add.

Hello the contract is verified and we renounced the ownership 

We don't need contract audit you can just verify it.

https://bscscan.com/tx/0xfe25fce004584bc9acd1196859590414dab0b47f7bed9228e115fecc606692a9

**Comment by Cryptocool1** [comment]
Please take a look at our requirements:
https://developer.trustwallet.com/assets/requirements

**Comment by Cryptocool1** [comment]
Feel free to come back to us once all criteria are met. Make sure to mention this PR so the fee can be reused

**Pull request closed without merging**
