### PR TITLE
Add CXPAD Logo and info

### PR DESCRIPTION
**Pull request by ravirasadiya**
Add CXPAD Logo and info

### CODE REVIEW

**Comment by cryptomanz** [comment]
Hello,
Can your answer some questions?
• What is the purpose of this token? How will it benefit Trust Wallet users?
 • How is the token being distributed? Are you conducting an airdrop?
 • Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?
 • Is the token listed on a centralized/decentralized exchange?
 • Is a Smart Contract audit completed? Where can we find this information?

**Comment by ravirasadiya** [comment]
> Hello, Can your answer some questions? • What is the purpose of this token? How will it benefit Trust Wallet users? • How is the token being distributed? Are you conducting an airdrop? • Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale? • Is the token listed on a centralized/decentralized exchange? • Is a Smart Contract audit completed? Where can we find this information?

Hi,
1. CoinxPad is a Cex/Dex Multi-chain IDO Launchpad, Trust Wallet users benefit from exclusive access to safe, innovative projects and rewarding investments on every blockchain. An additional benefit is that just by holding our CXPAD token they will receive USDT automatically in their wallet based on daily volumes.
2. After few days of our successful presale we’re listed already on CoinMarketCap, CoinGeko and PancakeSwap, we are conduction many marketing activities as airdrop/bounty/promotions etc.
3. We had only one Public Presale on Unicrypt on 25 September (https://app.unicrypt.network/amm/pancake-v2/ilo/0xD7Bf0ab6175600094241c97288D492a06d6BD1ae)
4. We are listed on PancakeSwap.
5. Yes the smart contract is audited by the German company SolidProof, here’s the link: https://github.com/solidproof/smart-contract-audits/blob/main/SmartContract_Audit_Solidproof_CXPAD.pdf

Here I write required details, please let me know if you need more information.
Thanks

**Comment by ravirasadiya** [comment]
@zachzwei  do I need to update anything now?

**Comment by cryptomanz** [comment]
> @cryptomanz do I need to update anything now?

Contract is not in checksum format, should be 0xe90d1567ecEF9282CC1AB348D9e9E2ac95659B99 (not 0xe90d1567ecef9282cc1ab348d9e9e2ac95659b99). Please rename it.

**Pull request merged**
