### PR TITLE
Add Metaverse Inu (BEP20)

### PR DESCRIPTION
**Pull request by MetaverseInu**
Adding info for BEP20 token 'Metaverse Inu'.

PR created by <a href="https://assets.trustwallet.com">TW Assets Management</a>

### CODE REVIEW

**Comment by MetaverseInu** [comment]
Created Thank you.

#15230
@cryptomanz

PAID BEFORE.

**Comment by MetaverseInu** [comment]
Hello

Our audit report complated. Success

https://github.com/TechRate/Smart-Contract-Audits/blob/main/November/MetaverseInu.pdf

Thank you

King regards

**Comment by catenocrypt** [comment]
The file `.github/workflows/fix.yml` is being deleted in this PR, probably by mistake.
Please:
- revert the delete
or:
- re-add the file (from https://raw.githubusercontent.com/trustwallet/assets/master/.github/workflows/fix.yml)
or preferred:
- close this PR, and create a new one in which you add again your two files.

This PR cannot be merged in this form.

**Comment by MetaverseInu** [comment]
please fix this for us .
Thanks

**Comment by MetaverseInu** [comment]
fix.yml added.
Thank you.

**Pull request merged**
