### PR TITLE
Litherium Logo uploading

### PR DESCRIPTION
**Pull request by 0xBenxx211226**
Hi, here is Litherium logo updaing request

### CODE REVIEW

**Comment by LITHYI** [comment]
Hi should I resubmite the info file?

**Comment by LITHYI** [comment]
And I have paid the TWT last time and there are notthing come up

**Comment by LITHYI** [comment]
Hash: 6095DD9821E4C4FE35956F8AC9C84A18FFDCC06C5C00247F69C50AD7C11E4B3F Memo:15460

**Comment by Cryptocool1** [comment]
Please create new PR, follow doc https://community.trustwallet.com/t/how-to-submit-a-token-logo/3863
You may want to try our Assets app in beta; go to https://assets.trustwallet.com, log on with Github, enter contract ID, logo and some additional info, and it will create a PR for you.
See https://community.trustwallet.com/t/how-to-submit-a-token-logo-using-assets-app/82957.

**Pull request closed without merging**
