### PR TITLE
Add SEFI

### PR DESCRIPTION
**Pull request by nocanvas**
add sefi folder, info.json and logo

PLEASE NOTE - this is a cross chain asset, that exists as a wrapped version of SEFI on Secret Network which is a cosmos based chain. The erc20 version we are listing has 1000 holders, but there are over 5000 holders on the secret network.

### CODE REVIEW

**Comment by nocanvas** [comment]
Please keep in mind this is a multi-chain asset, so the holder count on the wrapped version / erc20 will appear lower.

**Comment by zachzwei** [comment]
Please update your submission and use a checksum format for the folder name.
0x773258b03c730F84aF10dFcB1BfAa7487558B8Ac

**Comment by nocanvas** [comment]
I am showing the folder name is 0x773258b03c730f84af10dfcb1bfaa7487558b8ac

blockchains/ethereum/assets/0x773258b03c730f84af10dfcb1bfaa7487558b8ac/info.json

Is there something incorrect?

**Comment by nocanvas** [comment]
I don't know how to resolve this, can i edit this or do i need to start over

**Pull request closed without merging**
