### PR TITLE
Add forever fomo updated website

### PR DESCRIPTION
**Pull request by foreverfomo**

### CODE REVIEW

**Comment by foreverfomo** [comment]
Hi, why do I still have link field cannot be empty error?

**Comment by foreverfomo** [comment]
Hello

**Comment by foreverfomo** [comment]
Hi, I have already paid for the logo
https://explorer.binance.org/tx/3AD3649F94926C518E1DBB8770CE8BAA22C8C3EF6B4CB7DCB55CAC8C5E5553D5

**Comment by cryptomanz** [comment]
Hello,
Can your answer some questions?
• What is the purpose of this token? How will it benefit Trust Wallet users?
 • How is the token being distributed? Are you conducting an airdrop?
 • Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?
 • Is the token listed on a centralized/decentralized exchange?
 • Is a Smart Contract audit completed? Where can we find this information?

**Comment by foreverfomo** [comment]
• What is the purpose of this token? How will it benefit Trust Wallet users?
ForeverFOMO is the first new generation of rebasing tokens. Programmed to get to $1,500,000 due to the elastic supply. 

This will benefit trust wallet users becauses of our multi million $ volume that will have less of a chance of buying a fake. The logo will allow them to know whether or not they are buying the correct token.
• How is the token being distributed? Are you conducting an airdrop?

No airdrop, we launched on pancakeswap after a minor presale for liquidity. 

• Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?

Yes, we had a private/whitelisted presale.

• Is the token listed on a centralized/decentralized exchange?

we are listed on pancakeswap.

• Is a Smart Contract audit completed? Where can we find this information?

yes, we have completed an audit by TechRate. They are posting it on their social media and website today.

**Comment by foreverfomo** [comment]
https://twitter.com/TechRate1/status/1442228416166588419?s=20

**Comment by cryptomanz** [comment]
- Could you please send me audit in pdf format?

**Comment by foreverfomo** [comment]
Please see
https://github.com/TechRate/Smart-Contract-Audits/blob/main/September/ForeverFOMO.pdf

**Comment by cryptomanz** [comment]
can you please add links to your PR?

**Comment by foreverfomo** [comment]
Hi, I have already added link. What other links do you need?
I copied this directly from the trust wallet website

**Comment by foreverfomo** [comment]
{
    "name": "ForeverFOMO",
    "website": "https://foreverfomo.finance/",
    "telegram": "https://t.me/foreverfomo",
    "twitter": "https://twitter.com/FomoForever",
    "reddit": "https://www.reddit.com/r/ForeverFOMO/",
    "description": "ForeverFOMO is a price-elastic token with adjusting supply, moving towards the price of $1,500.000 per token. Different then just a normal pegged token/stable coin, rebases make price-elastic tokens into synthetic commodities with fluctuating values and supplies that gradually stabilize. Ultimately, rebases are designed to be tradable and potentially extremely profitable. On the path to $1.5m a token, ForeverFOMO will release NFTs, DAPPs, and more!",
    "explorer": "https://bscscan.com/token/0x95637d4FbE7153dCc3E26E71bdE7a2D82621F083",
    "type": "BEP20",
    "symbol": "ForeverFOMO",
    "decimals": 9,
    "status": "active",
    "id": "0x95637d4FbE7153dCc3E26E71bdE7a2D82621F083"
}

**Comment by foreverfomo** [comment]
Hi, how do I modify this pull request to add link?

**Comment by foreverfomo** [comment]
Hi, I have added links

**Pull request merged**
