### PR TITLE
Add yETH Token logo ( Bep20 )

### PR DESCRIPTION
**Pull request by Shyamthakur33**

### CODE REVIEW

**Comment by Shyamthakur33** [comment]
@catenocrypt @zachzwei hello dear team, could you please check out the info if all are correct
Please let us know so we could pay asap

**Comment by Shyamthakur33** [comment]
@catenocrypt @zachzwei  you around, please?

**Comment by catenocrypt** [comment]
Submission looks OK, awaiting fee payment

**Comment by Shyamthakur33** [comment]
> Submission looks OK, awaiting fee payment

@catenocrypt please check we have done payment.

**Review by KunKaxx — COMMENTED** [review]
.

**Pull request merged**
