### PR TITLE
Add OpenHandsNetwork  (BEP20)

### PR DESCRIPTION
**Pull request by OHN-TOKEN**
Adding info for BEP20 token 'OpenHandsNetwork '.

PR created by <a href="https://assets.trustwallet.com">TW Assets Management</a>

### CODE REVIEW

**Comment by OHN-TOKEN** [comment]
Hello, i have less than a 5000 holders on my token below your requirement,but  please i will i appreciate if you guys will give me the time to grow/market my token organically. i have an excellent project and i need more time. i will appreciate if my PR is process i don't mind paying the processing fee. Having my logo to appear on my token will give my investors assurance/confident of my token. you can call me directly if you have any question on my cell. 2019526420

**Comment by OHN-TOKEN** [comment]
Hello, i was trying to make the payment IN TWT but was having an issue i dont want to send it wrongly. please i need your step by step guide to send you the PR payment.

Please pay 1000 TWT with the memo 14904 to the address bnb1tqq9llyr3dyjd559dha6z5r5etk3qfwk07m098.
Alternatively, 5 BNB is also accepted (same memo & address).

**Comment by cryptomanz** [comment]
As per our policy, brand new tokens are not included, there is a minimum requirement of 5000 holder addresses and 10000 transactions, in order to filter out scam tokens.
See the criteria at (mentioned in the first message by the bot): https://community.trustwallet.com/t/how-to-submit-a-token-logo/3863).
Closing PR for now. Please come back to us when all criteria are met.

**Comment by OHN-TOKEN** [comment]
> As per our policy, brand new tokens are not included, there is a minimum requirement of 5000 holder addresses and 10000 transactions, in order to filter out scam tokens. See the criteria at (mentioned in the first message by the bot): https://community.trustwallet.com/t/how-to-submit-a-token-logo/3863). Closing PR for now. Please come back to us when all criteria are met.

Hello, my token is not a scam token for the record. i will need you  to consider it for now.

**Pull request closed without merging**
