### PR TITLE
Add Nora logo and info

### PR DESCRIPTION
**Pull request by NoraProtagonist**
Hello,

$Nora Smart Contract has been audited. For more information, please see here: https://solidity.finance/audits/SnowCrash/

The previously submitted PR can be found here: https://github.com/trustwallet/assets/pull/14066

### CODE REVIEW

**Comment by Cryptocool1** [comment]
#14066 PAID

**Comment by Cryptocool1** [comment]
could you add the links?
see the example here: https://developer.trustwallet.com/assets/repository_details

**Comment by hanyinghai** [comment]
> > could you add the links? see the example here: https://developer.trustwallet.com/assets/repository_details
> 
> Links added.

How can I get in touch with you?

**Comment by hanyinghai** [comment]
How can I get in touch with you?

**Pull request merged**
