### PR TITLE
Add Sheesh Logo and Info

### PR DESCRIPTION
**Pull request by SheeshToken**
Wanting to apply for Trust Wallet Logo!

### CODE REVIEW

**Comment by Cryptocool1** [comment]
Hello,
Can you capitalize your symbol please?

**Comment by SheeshToken** [comment]
Do you need a capitalization of all the letters? or just the first?

**Comment by Cryptocool1** [comment]
> Do you need a capitalization of all the letters? or just the first?
> […](#)

All letters.

**Comment by SheeshToken** [comment]
I cant figure out how to update the repository! does anyone know the correct program i can use to update it or a tutorial of some sort that is easy? im very new to this!

**Pull request merged**
