### PR TITLE
Add PowerTrade fuel assets

### PR DESCRIPTION
**Pull request by thowar2**

### CODE REVIEW

**Comment by catenocrypt** [comment]
As per our policy, brand new tokens are not included, there is a minimum requirement of 500 holder addresses and 1000 transactions, in order to filter out scam tokens.
See the criteria at (mentioned in the first message by the bot): https://community.trustwallet.com/t/how-to-submit-a-token-logo/3863#how-to-get-approved
This token has below-limit usage yet (274). Closing PR for now. Please come back to us when all criteria are met.

https://etherscan.io/token/0xC57d533c50bC22247d49a368880fb49a1caA39F7

**Comment by thowar2** [comment]
@catenocrypt there are ~600 token holders in the vesting contract: https://etherscan.io/address/0x6a03796E882BED3B1FF1747b8563f3C2c11F0Ff3

They all appear as a single holder due to the smart contract escrow.

In addition, this token is backed by Pantera, Framework, and other notable backers: https://www.coindesk.com/new-bitcoin-options-app-raises-4-7m-in-round-led-by-pantera-capital

Can provide other evidence that this is not a scam if needed.

**Comment by catenocrypt** [comment]
Noted.

**Comment by catenocrypt** [comment]
Please rename logo to `logo.png`.  I tried to do it, but cannot push to your fork repo.

```
git mv blockchains/ethereum/assets/0xC57d533c50bC22247d49a368880fb49a1caA39F7/pt_icon_256.png blockchains/ethereum/assets/0xC57d533c50bC22247d49a368880fb49a1caA39F7/logo.png
```

image

**Comment by thowar2** [comment]
Apologies, fixed it @catenocrypt

**Pull request merged**
