### PR TITLE
Add Doge Raca (BEP20)

### PR DESCRIPTION
**Pull request by DogeRaca**
Adding info for BEP20 token 'Doge Raca'.

PR created by <a href="https://assets.trustwallet.com">TW Assets Management</a>

### CODE REVIEW

**Comment by DogeRaca** [comment]
Dear team,

We want to list the logo on the trust wallet. Please help me.

Best regards !

**Comment by DogeRaca** [comment]
Hi sir, Direction help me, what to do next?

**Comment by cryptomanz** [comment]
Submission looks good, awaiting for fee payment

**Comment by DogeRaca** [comment]
Ok sir

**Comment by DogeRaca** [comment]
Wait for me...

**Comment by DogeRaca** [comment]
Check haxh sir !

**Comment by DogeRaca** [comment]
41AFD7CA7F6CEE92D2198D9372AC13249E41BA7FDDDDE469AD21BABE13E55266

**Comment by DogeRaca** [comment]
Dear team,

Haven't seen our logo updated yet.
Please check us out.

Best regards !

**Comment by cryptomanz** [comment]
• What is the purpose of this token? How will it benefit Trust Wallet users?
 • How is the token being distributed? Are you conducting an airdrop?
 • Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?
 • Is the token listed on a centralized/decentralized exchange?
 • Is a Smart Contract audit completed? Where can we find this information?

**Comment by DogeRaca** [comment]
Dear team,
- Tokens are for payment in our Doge Raca game. - It will help Trust Wallet users to identify the real project.
- We have conducted an airdrop and distributed it fairly to all users.
- We do not pre-sell anywhere.
- We have listed on pancakeswap: https://pancakeswap.finance/swap#/swap?outputCurrency=0xb547607eae3b10d94b211da84a3b51bfa545774d
- We have conducted an audit. You can check it out here: https://github.com/sokenteam/smart_contract_audits/blob/main/Doge%20Raca%20Standard%20Smart%20Contract%20Audit.pdf

Best regards !

**Comment by DogeRaca** [comment]
Dear team,
I have tried to provide information, if something is missing please let me know.

Help me ! Thanks

**Comment by DogeRaca** [comment]
Dear team,
Please help, what should I do next???
Best regards !

**Pull request merged**
