### PR TITLE
Add KAVA (KAVA)

### PR DESCRIPTION
**Pull request by EJK64**
Adding info for KAVA token 'KAVA'.

PR created by <a href="https://assets.trustwallet.com">TW Assets Management</a>

### CODE REVIEW

**Comment by EJK64** [comment]
TxID
E7F3B6EF02A63DA1FDFA0B6F32777862FB8EE65BF1C3889576EE8BF9A57D69FF
Date
2021-11-10

**Comment by EJK64** [comment]
3rd try :-)
The first PR was closed just before I send the payment (I received a payment request of which was paid upon)
Please use the payment with 
TxID
E7F3B6EF02A63DA1FDFA0B6F32777862FB8EE65BF1C3889576EE8BF9A57D69FF
Date
2021-11-10
PR 
#13586
Second try PR
#15490
These are the same request

**Comment by EJK64** [comment]
E7F3B6EF02A63DA1FDFA0B6F32777862FB8EE65BF1C3889576EE8BF9A57D69FF

**Comment by ramsty** [comment]
Please create new PR, follow doc https://community.trustwallet.com/t/how-to-submit-a-token-logo/3863
You may want to try our Assets app in beta; go to https://assets.trustwallet.com, log on with Github, enter contract ID, logo and some additional info, and it will create a PR for you.
See https://community.trustwallet.com/t/how-to-submit-a-token-logo-using-assets-app/82957.

**Comment by EJK64** [comment]
> Please create new PR, follow doc https://community.trustwallet.com/t/how-to-submit-a-token-logo/3863
> You may want to try our Assets app in beta; go to https://assets.trustwallet.com, log on with Github, enter contract ID, logo and some additional info, and it will create a PR for you.
> See https://community.trustwallet.com/t/how-to-submit-a-token-logo-using-assets-app/82957.

Could you please tell me what is Wrong?
I am trying to add myself as a validator for Kava and the BOT and the pages tell me to fill this form. Despite that I am again send beck to the same form. Not having a clue what's wrong with the inout.
Thanks

**Pull request closed without merging**
