### PR TITLE
add RiseHero Token

### PR DESCRIPTION
**Pull request by myrisehero**
add RiseHero Token

### CODE REVIEW

**Comment by myrisehero** [comment]
certik audit: https://www.certik.com/projects/risehero

**Comment by Cryptocool1** [comment]
can you please add tags?
see the requirements here : https://developer.trustwallet.com/assets/repository_details

**Comment by myrisehero** [comment]
> can you please add tags? see the requirements here : https://developer.trustwallet.com/assets/repository_details

I have added the tags in info.json

**Comment by Cryptocool1** [comment]
You should create new PR without this file
blockchains/smartchain/info/info.json

**Comment by myrisehero** [comment]
> 

I create a new request.  https://github.com/trustwallet/assets/pull/17693

**Comment by myrisehero** [comment]
> You should create new PR without this file blockchains/smartchain/info/info.json

I create a new pullrequest https://github.com/trustwallet/assets/pull/17693,  and tags has added. Should I pay again?

**Pull request closed without merging**
