### PR TITLE
Add dotmoovs (BEP20)

### PR DESCRIPTION
**Pull request by GuilhermeBianeck**
This PR is being closed due to inactivity. If you wish to continue, please have us reopen the PR before sending your payment, or just create a new one.
Do NOT send payments for closed PR, as the fee may by lost!
  (48 vs. 48 hrs)

### CODE REVIEW

**Comment by Cryptocool1** [comment]
do you want to add only dotmoovs?
you have 4 tokens in your PR

**Comment by GuilhermeBianeck** [comment]
Hi @Cryptocool1 - 
It's Exeedme (BSC + Ethereum Contract) - https://www.coingecko.com/en/coins/exeedme
And dotmoovs (BSC + Ethereum Contract) - https://www.coingecko.com/en/coins/dotmoovs
It's 2 Contracts each Token

**Comment by Cryptocool1** [comment]
Info file should be named info.json , not info.json.txt
please rename

**Review by GuilhermeBianeck — COMMENTED** [review]
Updates

**Review by GuilhermeBianeck — COMMENTED** [review]
Tokens - Dotmoovs (ETH + BSC Contract)
Exeedme (ETH + BSC Contract)

**Pull request closed without merging**
