### PR TITLE
SHREW logo and project info

### PR DESCRIPTION
**Pull request by Shrew-token**
SHREW logo and project info

### CODE REVIEW

**Comment by arfyshah** [comment]
Hi, why is this failing, I followed the instructions exactly and also paid 5BNB. @catenocrypt @zachzwei @Cryptocool1 @hexorx 

Please help!

**Comment by Cryptocool1** [comment]
hello,
• What is the purpose of this token? How will it benefit Trust Wallet users?
 • How is the token being distributed? Are you conducting an airdrop?
 • Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?
 • Is the token listed on a centralized/decentralized exchange?
 • Is a Smart Contract audit completed? Where can we find this information?

**Comment by arfyshah** [comment]
> hello,
> • What is the purpose of this token? How will it benefit Trust Wallet users?
> • How is the token being distributed? Are you conducting an airdrop?
> • Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?
> • Is the token listed on a centralized/decentralized exchange?
> • Is a Smart Contract audit completed? Where can we find this information?

• Shrew stands for SHopping REWards, an ecosystem that will aim to simplify and connect stores from all over the world. In the process, we will create a network that will allow anyone, around the globe to seamlessly earn, store and spend SHREW at any store. Opening up possibilities for both the stores and the consumer.
The platform where users can bring in existing rewards accounts, earn points using a single app for multiple stores and trade these points with others using blockchain. The SHREW token will be the single currency linking each reward scheme across a multitude of stores and will thus have deep utility and value.

• The tokens have already been distributed through a fair launch on DX Sale and we also did an airdrop with it. The token is already live on the Pancakeswap exchange right now and we are also on Coingecko.

• Token presale as mentioned above.

• We are currently listed on a decentralized exchange but have plans for centralized exchanged too. We are on  Pancakeswap right now.

• We do have an audit from Techrate. If you see our contract code, it is rug proof and receives a perfect score when run through rugscanner. We will aim to get a full audit from Certik soon as well. Our contract is super clean and does not feature meme coin tokenomics and the value will be driven by product development and partnerships. We already have an agreement with Chainlink for example.
Link to Techrate audit here: [TechRate Audit](https://2bfd6cc7-1aef-4bd0-a48f-535d0e175961.filesusr.com/ugd/427fba_2f753daad72c450ba66dd92ce50941c0.pdf)

Please note we are a fully doxxed team from day 1 with weekly video stream AMAs and our professional reputations on the line: Shrew.com/team

**Comment by Cryptocool1** [comment]
can you please add links to your PR?
example: https://developer.trustwallet.com/add_new_asset#info-json-contents

**Comment by arfyshah** [comment]
> can you please add links to your PR?
> example: https://developer.trustwallet.com/add_new_asset#info-json-contents

Hello, I have edited the json with our links now.

Thank you!

**Comment by Shrew-token** [comment]
> can you please add links to your PR?
> example: https://developer.trustwallet.com/add_new_asset#info-json-contents

Hello, Shrew has done a token migration and we need to have the Trust Wallet app pick up the logo for the new contract and stop picking it up on the old one to stop any confusion. Everythings else in the JSON file remains the same apart from the explorer link and the contract. Are you please able to rename the '0x0c13970d3c5db20d48446a24e29fb9a77cd60de4' folder and update the JSON with the correct contract and explorer link.

Thank you so much!

The token has now changed from:
Contract: 0x0c13970d3c5db20d48446a24e29fb9a77cd60de4
Explorer link: https://bscscan.com/token/0x0c13970d3c5db20d48446a24e29fb9a77cd60de4

To:
Contract: 0x3c168c8e0bb11b0a6deeba6c0c6be100e82451bb
Explorer link: https://bscscan.com/token/0x3c168c8e0bb11b0a6deeba6c0c6be100e82451bb

**Announcements showing proof:**

Bscscan.com has an official announcement on the old token page (scroll half way down) pointing to the new token address:
- https://bscscan.com/token/0x0c13970d3c5db20d48446a24e29fb9a77cd60de4

Our official website explains the migration is complete and buy links / tokenomics section go to the new token address
- https://www.Shrew.com

Twitter announcement on official Twitter account:
- https://twitter.com/Shrewdotcom/status/1427767628731457538?s=19

Old Dex Tools token chart redirecting to new token:
- https://www.dextools.io/app/pancakeswap/pair-explorer/0xafd0ae1f6e8814a8dba2ecc7fade4b51afb0d570

**Comment by Shrew-token** [comment]
@Cryptocool1 @catenocrypt @zachzwei 

**URGENT:** Shrew has done a token migration and we need to have the Trust Wallet app pick up the logo for the new contract and stop picking it up on the old one to stop any confusion. Everythings else in the JSON file remains the same apart from the explorer link and the contract. Are you please able to rename the '0x0c13970d3c5db20d48446a24e29fb9a77cd60de4' folder and update the JSON with the correct contract and explorer link.

Thank you so much!

The token has now changed from:
Contract: 0x0c13970d3c5db20d48446a24e29fb9a77cd60de4
Explorer link: https://bscscan.com/token/0x0c13970d3c5db20d48446a24e29fb9a77cd60de4

To:
**Contract: 0x3c168c8e0bb11b0a6deeba6c0c6be100e82451bb
Explorer link: https://bscscan.com/token/0x3c168c8e0bb11b0a6deeba6c0c6be100e82451bb**

Announcements showing proof:

Bscscan.com has an official announcement on the old token page (scroll half way down) pointing to the new token address:

https://bscscan.com/token/0x0c13970d3c5db20d48446a24e29fb9a77cd60de4
Our official website explains the migration is complete and buy links / tokenomics section go to the new token address

https://www.Shrew.com
Twitter announcement on official Twitter account:

https://twitter.com/Shrewdotcom/status/1427767628731457538?s=19
Old Dex Tools token chart redirecting to new token:

https://www.dextools.io/app/pancakeswap/pair-explorer/0xafd0ae1f6e8814a8dba2ecc7fade4b51afb0d570

**Pull request merged**
