### PR TITLE
Add JNTR/e token logo & info for Jointer website.

### PR DESCRIPTION
**Pull request by RishabhS7**
Website Description - Daily JNTR incentives through the World’s First Commercial Real Estate Decentralized Finance (DeFi) Auction based Decentralized Autonomous Organization (DAO)

### CODE REVIEW

**Comment by KDubCrypto** [comment]
If the BNB is paid, is this pull request completed?

**Review by Iamdeadlyz — APPROVED** [review]
info.json and logo is ok ✅ 
waiting for the payment to proceed in merging

**Comment by RishabhS7** [comment]
While doing payment to the adress bnb1tqq9llyr3dyjd559dha6z5r5etk3qfwk07m098 , it says invalid address.

**Comment by Iamdeadlyz** [comment]
> While doing payment to the adress bnb1tqq9llyr3dyjd559dha6z5r5etk3qfwk07m098 , it says invalid address.

The bot will only accept BNB BEP2, not BNB BEP20 (Binance Smart Chain)

**Comment by RishabhS7** [comment]
2 BNB paid with memo 4426 . Please check and proceed to further steps accordingly.

**Pull request merged**
