### PR TITLE
Add Hoppy logo and info in Trust Wallet 

### PR DESCRIPTION
**Pull request by coppermug**
Add Hoppy logo and info in Trust Wallet

### CODE REVIEW

**Comment by coppermug** [comment]
Hi there, I have been submitting all the external info as per request and waiting for your reply. Unfortunately the pull request created earlier was closed due to no response. I am creating a new pull request again, sincerely hoping we can manage to onboard Hoppy on TWT.

**Comment by coppermug** [comment]
Here I provided again the external info requested from your end:

• What is the purpose of this token?
HOP token, is the governance token of HOPPY. HOPPY hopes to become the Most Influential Sustainability-driven
Community, aiming to build Awareness and make impactful Actions in contributing towards the 2030 United Nations’ Sustainable Development Goals.

•How will it benefit Trust Wallet users?
Trust wallet users will be able to participate in realizing a greener, better future. Most importantly, with the Logo we can help users identify the real HOP token, avoid being scammed by fake contracts.

• Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?
Yes, presale happened in Q2 2021.

• Is the token listed on a centralized/decentralized exchange?
Yes. It's on pancakeswap
https://pancakeswap.finance/swap?outputCurrency=0x984811e6f2695192add6f88615dF637bf52a5Cae

•Is a Smart Contract audit completed? Where can we find this information?
Yes we have completed the Smart Contract audit last year. You can get the information here: https://solidgroup-68170.medium.com/71be3b0a403d

• How is the token being distributed? Are you conducting an airdrop?
Token distribution is as below. Presales happened in 2021 Q2. We are not conducting an airdrop.
WhatsApp Image 2022-01-15 at 9 12 30 PM

**Comment by cryptomanz** [comment]
Please send me audit in pdf format.

**Comment by coppermug** [comment]
Sure, attached with the Hoppy audit in pdf format
[Hoppy Audit Result.pdf](https://github.com/trustwallet/assets/files/7914658/Hoppy.Audit.Result.pdf)

**Comment by Cryptocool1** [comment]
submission looks good, awaiting for fee payment

**Comment by coppermug** [comment]
Thank you. I will proceed with payment.

**Comment by coppermug** [comment]
Hi I saw Hoppy logo in Trustwallet, thank you for the effort.
However, I noticed the logo cannot be show fully in Trustwallet mobile app as shown below.
IMG_9635

I had adjusted the logo to fix in size and I would like to request to replace Hoppy logo with attached file below.

logo

**Pull request merged**
