### PR TITLE
Add logo WETC and info

### PR DESCRIPTION
**Pull request by wetcfarm**

### CODE REVIEW

**Comment by Cryptocool1** [comment]
hello,
can't find contract on your website

**Comment by Cryptocool1** [comment]
can you please add links to your PR?
example: https://developer.trustwallet.com/add_new_asset#info-json-contents

**Comment by wetcfarm** [comment]
Press "Info"

**Comment by wetcfarm** [comment]
information about the contract is on the website. Pressing the "info" button.
PR, I am trying to add but error ...

**Comment by Cryptocool1** [comment]
What is the purpose of your token?

**Comment by wetcfarm** [comment]
Yield farm ETC on Binance Smart Chain

**Comment by zachzwei** [comment]
> Yield farm ETC on Binance Smart Chain

How does this yield farming of ETC work?
I only see wETC on the site, which is not even a pegged ETC.

**Comment by wetcfarm** [comment]
yield works through wETC farming . in return, the participant gets ETC

**Comment by wetcfarm** [comment]
and?

**Comment by vikmeup** [comment]
> yield works through wETC farming . in return, the participant gets ETC

Can you elaborate on this? 
How does it work? What are the guarantees?

**Comment by wetcfarm** [comment]
> > yield works through wETC farming . in return, the participant gets ETC
> 
> Can you elaborate on this?
> How does it work? What are the guarantees?

are you Assignees?
I wrote that through farming, everyone gets wETC, after which anyone can exchange them for ETC

**Comment by wetcfarm** [comment]
AND?

**Comment by vikmeup** [comment]
What's the mechanism to farm native ETC token? How's implemented?

**Comment by zachzwei** [comment]
This token has not undergone any security audit. There is no clear roadmap on what the project is about. To protect our users from potential scams, the submission is closed.

To know more about the token approval guidelines, please check this article: [How to Submit Token Logo](https://community.trustwallet.com/t/how-to-submit-a-token-logo/3863#how-to-get-approved).

Feel free to re-open pull request once you meet those requirements.

**Pull request closed without merging**
