### PR TITLE
Reply to questions in PR 11662 of LABS Group (LABS) (ERC20)

### PR DESCRIPTION
**Pull request by SPP922**
@cryptomanz

Hi Nazar,

Associated PR is:  #11662 , #11467 

Below is the answer to your question in PR 11662 :

• **What is the purpose of this token? How will it benefit Trust Wallet users?**
**A:**
**Governance**
For the first time decentralized governance will come to a real estate digitization and crowdfunding platform. LABS will democratize certain aspects of the platform, which will give LABS token holders voting rights, to determine how the platform is run and  the types of investment opportunities available. A vote is put up when the LABS has made some votable items which will be put up to a community vote. Examples are given below on how this will work.
Voting on the rights to what investment is released
Voting on new additions to add to the LABS platform
Vote on staking pools
The right to put up new real estate projects of interest
**Access**
Holding LABS tokens in your wallet will give you priority access to real estate investments. Instead of having to fight for the earliest round at the largest discount we will put you first in line to receive this before traditional investors have access.
**Incentives**
As a holder of LABS tokens you will receive incentives such as a discount on real estate investments based on how much LABS tokens you hold in your wallet. All you need to do is connect you wallet to the LABS platform complete registration and KYC and you will be allowed to invest in real estate projects
**Nominate**
Holders of LABS Tokens will be able to nominate projects to the platform for investments. 
**Staking for Rewards**
Users can join a decentralized rewards pool of LABS corporate net profits in which we use 80% of our net profits the first year in a token buy back which will be distributed to the stakers of LABS tokens directly to their staking wallets. These tokens will be distributed quarterly and on a daily basis directly into the stakers wallet. The percentage of net profits will be determined by the governance vote and the community after the first year to determine how large the reward pool percentage will be. The voting mechanism will be a simple majority of greater than 50% of all votes tallied.

In order to make staking fair for everyone we will tally the amount of time each wallet has staked and will distribute the dividends evenly across the wallets. We do this to prevent bad actors that come in at the last minute with large sums of $LABS and try to take the whole pool. At the time of distribution of rewards the $LABS tokens must be staked. You may stake and unstake at any time but in order to qualify for the rewards you must stake at least 30 days before the first distribution of profits in year 1. After years 1 it will default to a stake timing mechanism. Tokens must be staked at the time of rewards distribution.

This significantly reduces the risk of stakeholders while giving all the upside benefits of earning. At all times you will be in full control of your wallet as we never ask you to transfer your tokens to us to hold.

1，There are 12329 LABS token holding addresses
2，The LABS Group ecosystem is expanding, and the community continues to grow
3，The labs group is cooperating with the NFT market on the BSC chain to launch the world's first community-owned NFT resort

**• How is the token being distributed? Are you conducting an airdrop?**
**A:**
**Total Tokens (LABS): 10,000,000,000 Supply**
**Investors** - 20% will be sold to private and public investors with different lockups.
**Team and Advisors** - 15% will go to the team and advisors which will be on a 24 month lockup with the first release at 6 months then each month after that.
**Partners** - 5% will be reserved for various partnerships that may need to include the $LABS token for ecosystem building purposes.
**Ecosystem/Interest Fund** - 50% This will go towards various needs of LABS. For instance some partners we work with, we may allocate a certain amount of LABS tokens for partnership purposes which may be used to incentivize new investors and project signups for the LABS ecosystem. Other uses may be for ecosystem incentives for our users as well as using LABS tokens to pay for services depending on business situations.
**Reserve** - 10% reserve will be held by LABS as an emergency fund for our business. We do not anticipate using these funds but if something arises we reserve the right to use these funds to potentially fund the business.

**No airdrop**

**• Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?**
**A:**
YES
**• Is the token listed on a centralized/decentralized exchange?**
**A:**
YES, Uniswap、dodo、gate.io、kucoin、bitmart
**• Is a Smart Contract audit completed? Where can we find this information?**
**A：**
YES
https://www.slowmist.com/security-audit-certificate.html?id=08e4d39884dcc9c2160a9b74835c94c08fc511536095c2ae9a63116c299fd958

Thank you
Kind regards

### CODE REVIEW

**Comment by Cryptocool1** [comment]
hello,
can you please add links to your PR?
example: https://developer.trustwallet.com/add_new_asset#info-json-contents

**Comment by SPP922** [comment]
> hello,
> can you please add links to your PR?
> example: https://developer.trustwallet.com/add_new_asset#info-json-contents

Is add  Smart Contract audit link to info.json?

**Comment by Cryptocool1** [comment]
hello,
can you please add links to your PR?
example: https://developer.trustwallet.com/add_new_asset#info-json-contents

> > hello,
> > can you please add links to your PR?
> > example: https://developer.trustwallet.com/add_new_asset#info-json-contents
> 
> Is add Smart Contract audit link to info.json?

List of currently supported types:
github, whitepaper, twitter, telegram, telegram_news, medium, discord, reddit, facebook, youtube, coinmarketcap, coingecko, blog, forum, docs, source_code.
Note: the socials section is no longer used.

**Comment by SPP922** [comment]
> hello,
> can you please add links to your PR?
> example: https://developer.trustwallet.com/add_new_asset#info-json-contents
> 
> > > hello,
> > > can you please add links to your PR?
> > > example: https://developer.trustwallet.com/add_new_asset#info-json-contents
> > 
> > 
> > Is add Smart Contract audit link to info.json?
> 
> List of currently supported types:
> github, whitepaper, twitter, telegram, telegram_news, medium, discord, reddit, facebook, youtube, coinmarketcap, coingecko, blog, forum, docs, source_code.
> Note: the socials section is no longer used.


Thanks, I've updated it, please check it.

**Pull request merged**
