### PR TITLE
Add RELIABLE (BEP20)

### PR DESCRIPTION
**Pull request by reliabletoken**
Adding info for BEP20 token 'RELIABLE'.

PR created by <a href="https://assets.trustwallet.com">TW Assets Management</a>

### CODE REVIEW

**Comment by reliabletoken** [comment]
please add reliable token

**Comment by cryptomanz1** [comment]
• What is the purpose of this token? How will it benefit Trust Wallet users?
 • How is the token being distributed? Are you conducting an airdrop?
 • Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?
 • Is the token listed on a centralized/decentralized exchange?
 • Is a Smart Contract audit completed? Where can we find this information?

**Comment by reliabletoken** [comment]
• What is the purpose of this token? How will it benefit Trust Wallet users?
   Token is Use in Payment Form Token.
• How is the token being distributed? Are you conducting an airdrop?
  Doing IEO on Vindax Exchange
• Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?
   No We Are selling on IEO only
• Is the token listed on a centralized/decentralized exchange?
  Centralized Exchange Vindax and Pancake swap
• Is a Smart Contract audit completed? Where can we find this information?
   https://reliablestaking.co/

**Comment by reliabletoken** [comment]
kindly add the token

**Comment by Cryptocool1** [comment]
Hello, I cannot find your contract audit. Please send it here

**Comment by reliabletoken** [comment]
ok

**Comment by reliabletoken** [comment]
ok we are sharing the audit report

**Comment by reliabletoken** [comment]
[RELIABLE AUDIT REPORT.pdf](https://github.com/trustwallet/assets/files/10069681/RELIABLE.AUDIT.REPORT.pdf)

**Comment by reliabletoken** [comment]
please check audit report and approve and list the reliable token

**Comment by reliabletoken** [comment]
please add reliable token

**Comment by reliabletoken** [comment]
hello when the token will update and logo will show

**Review by reliabletoken — COMMENTED** [review]
please add reliable

**Comment by reliabletoken** [comment]
any update on listing my token

**Comment by reliabletoken** [comment]
still logo not. reflecting

**Comment by reliabletoken** [comment]
hello still logo not showing in trust wallet and also when. searching for  token it is now showing

**Comment by Cryptocool1** [comment]
Hello, how did you get 14k holders in less than 1 day?

**Comment by reliabletoken** [comment]
WE HAVE SENT TOKEN TO OUR COMMUNITY

**Comment by reliabletoken** [comment]
we have more than 50k community

**Comment by reliabletoken** [comment]
please add the logo @Cryptocool1 our community is waiting for it and also today our trading starting in vindax exchange also kindly do asap

**Comment by Cryptocool1** [comment]
We are not accept airdropped tokens. You may see it in our documentation .
https://developer.trustwallet.com/assets/requirements
You should also have smart contract audit from reputable companies ( Certik, Techrate, Hacken, Dessert Finance)
On hold for now

**Comment by reliabletoken** [comment]
we have not done airdrop we have given our community token for trade

**Comment by reliabletoken** [comment]
our certik audit is already ongoing

**Comment by Cryptocool1** [comment]
Your first transaction should be at least 2 weeks ago. 
Awaiting for Certik audit.

**Comment by reliabletoken** [comment]
we have etherauthority audit

**Comment by reliabletoken** [comment]
hello @Cryptocool1 we have etherauthority audit done already , regarding first transaction kindly approve the logo , sorry for the mistake.

**Comment by Cryptocool1** [comment]
We are also require CoinMarketCap listing.

**Comment by reliabletoken** [comment]
currently we are not on cmc , we are listing today on vindax exchange

**Comment by reliabletoken** [comment]
hello @Cryptocool1 first transaction is 16 days ago , i am attaching the transaction hash

https://bscscan.com/tx/0x34283cc92541b5a6bec4e48a86fa1758a57833ee5ad0c5c932107ec7ead5267f

**Comment by reliabletoken** [comment]
please look and add the logo , our community is waiting for it

**Comment by reliabletoken** [comment]
so when it will list, how much we have to wait for it

**Comment by reliabletoken** [comment]
we are ready to pay 200 usdt extra for it , but list the token

**Comment by Cryptocool1** [comment]
There is no need to pay extra fee. You should just meet all the requirements

**Comment by reliabletoken** [comment]
now how much transaction should old for it because as we have given the token to our 10k above public , so when it will meet the requirement because we have not known about requirements.

**Comment by Cryptocool1** [comment]
Hello. I don’t see an activity on your token. You had only one massive transaction(airdrop) 
Please come back to us once you have activity on your project and audit from reputable company. 
When creating new PR, make sure to mention this one, so the fee can be reused

**Pull request closed without merging**
