### PR TITLE
Add files via upload

### PR DESCRIPTION
**Pull request by zahidgopang**
please update my wallet logo

### CODE REVIEW

**Comment by zahidgopang** [comment]
i have not included info.json file do i need to add that too for updated information ? let me know

**Comment by Cryptocool1** [comment]
Please create new PR, follow doc https://developer.trustwallet.com/listing-new-assets/requirements
You may want to try our Assets app in beta; go to https://assets.trustwallet.com, log on with Github, enter contract ID, logo and some additional info, and it will create a PR for you.
See https://developer.trustwallet.com/listing-new-assets/repository_details

**Comment by Cryptocool1** [comment]
Please mention this PR in new one so we can reuse your payment

**Comment by zahidgopang** [comment]
Hello have u update my logo only ? for that i paid 500 TWT ?

**Comment by zahidgopang** [comment]
ignore correct only update my wallet logo which i already paid 500 TWT please

**Comment by zahidgopang** [comment]
PR request was created 
https://github.com/trustwallet/assets/pull/29221
yet nothing updated please update logo it is urgent

**Comment by zahidgopang** [comment]
@Cryptocool1

**Pull request closed without merging**
