### PR TITLE
Add HUGHUG (BEP20)

### PR DESCRIPTION
**Pull request by takuro020301**
Adding info for BEP20 token 'HUGHUG'.

PR created by <a href="https://assets.trustwallet.com">TW Assets Management</a>

### CODE REVIEW

**Comment by cryptomanz** [comment]
hello,
can your answer some questions?
• What is the purpose of this token? How will it benefit Trust Wallet users?
• How is the token being distributed? Are you conducting an airdrop?
• Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?
• Is the token listed on a centralized/decentralized exchange?
• Is a Smart Contract audit completed? Where can we find this information?

**Comment by takuro020301** [comment]
• What is the purpose of this token? How will it benefit Trust Wallet users?

HGHG tokens will be used in the NFT Marketplace we create in the future.

Because you need to connect to that platform through a trust wallet We can expect to increase the number of trust wallet users.

• How are the tokens distributed? Do you airdrop? 

In addition to the fair launch, we also carry out airdrop promotion. 

• Did you sell your tokens through an Initial Coin Offering (ICO) or pre-sale of tokens? 

No, only fair launch.

• Is the token listed on a centralized/decentralized exchange?

PancakeswapV2
https://pancakeswap.finance/swap?outputCurrency=0xb626213cb1d52caa1ed71e2a0e62c0113ed8d642

• Is a Smart Contract audit completed? Where can we find this information?

Yes.

https://github.com/Rock-n-Block/AUDIT/blob/main/HGHG

**Comment by cryptomanz** [comment]
- Could you send me audit contract in PDF format?

**Comment by takuro020301** [comment]
audit contract in PDF

https://hughug.io/pdf/hughug_rb.pdf

**Pull request merged**
