### PR TITLE
new token AMC

### PR DESCRIPTION
**Pull request by Aziz87**

### CODE REVIEW

**Comment by Cryptocool1** [comment]
could you add the links?
see the example here: https://developer.trustwallet.com/assets/repository_details

**Comment by Aziz87** [comment]
> 

thank you

**Comment by Cryptocool1** [comment]
• What is the purpose of this token? How will it benefit Trust Wallet users?
 • How is the token being distributed? Are you conducting an airdrop?
 • Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?
 • Is the token listed on a centralized/decentralized exchange?
 • Is a Smart Contract audit completed? Where can we find this information?

**Comment by Aziz87** [comment]
**• What is the purpose of this token? How will it benefit Trust Wallet users?**

Our token was created for MMA fans promoted by AMC Fight Nights.
The token is used by fans of the promotion to buy tickets, merchandise and other club privileges.
 Most of the holders of our token use your wallet. These are several thousand people.

 **• How is the token being distributed? Are you conducting an airdrop?**

We are not an airdrop. The token is sold only on exchanges, and is also distributed among fans for some of their actions.

 **• Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?**

Yes. We sold on ICOs and also made IDOs.

 **• Is the token listed on a centralized/decentralized exchange?**

Yes. Currently, the token is traded on 4 exchanges Pancake, Uniswap, Bitmart, ZB.com

 **• Is a Smart Contract audit completed? Where can we find this information?**

We are currently undergoing an audit. We have already received a legal opinion.

**Comment by Cryptocool1** [comment]
we require smart contract audit
Please come back to us when all criteria are met.

**Comment by Aziz87** [comment]
Tell me please, need 25k holders or only contract audit?

**Pull request closed without merging**
