### PR TITLE
Add Bitrise Token (BEP20)

### PR DESCRIPTION
**Pull request by ryoshitoken**
Adding info for BEP20 token 'Bitrise Token'.

PR created by <a href="https://assets.trustwallet.com">TW Assets Management</a>

### CODE REVIEW

**Comment by bitrisetoken** [comment]
Payment 3BNB sent

**Comment by bitrisetoken** [comment]
I've deposit 3+2 BNB , total 5

**Comment by cryptomanz** [comment]
As per our policy, brand new tokens are not included, there is a minimum requirement of 5000 holder addresses and 10000 transactions, in order to filter out scam tokens.
See the criteria at (mentioned in the first message by the bot): https://community.trustwallet.com/t/how-to-submit-a-token-logo/3863).

**Comment by bitrisetoken** [comment]
How do i get my refund then?

**Comment by Cryptocool1** [comment]
still 668 holders
please create new PR when all criteria are met

**Comment by bitrisetoken** [comment]
WHat about my 5 BNB???

**Pull request closed without merging**
