### PR TITLE
Adding ALA

### PR DESCRIPTION
**Pull request by lee01101985**
We make it possible for any business to raise capital for their projects globally at a small cost, with low barriers and support investors around the world who can invest in potential projects more easily, manage their assets and provide them with great trading tools

### CODE REVIEW

**Comment by Iamdeadlyz** [comment]
@lee01101985 

As per our policy, brand new tokens are not included. There is a minimum requirement of 500 holder addresses and 1000 transactions in order to filter out scam tokens. See the criteria at (mentioned in the first message by the bot): https://community.trustwallet.com/t/how-to-submit-a-token-logo/3863#how-to-get-approved

This token has below-limit usage yet. This pull request will be but on hold. Please come back to us when all criteria are met.
https://etherscan.io/token/0xf6995f53BE4191DFA32AFf0ac44F25831c1E347b

**Comment by lee01101985** [comment]
{
    "name": "ALADIN",
    "website": "https://aladiex.com/",
    "short_description": "We make it possible for any business to raise capital for their projects globally at a small cost, with low barriers and support investors around the world who can invest in potential projects more easily, manage their assets and provide them with great trading tools",
    "explorer": "https://etherscan.io/token/0x564f45b6bb68aded8b660a0d8a0a948dd6d6e4e8"
}

**Comment by lee01101985** [comment]
i use token aladiex; not silver

**Comment by lee01101985** [comment]
My token info; pls check
{
    "name": "ALADIN",
    "website": "https://aladiex.com/",
    "short_description": "We make it possible for any business to raise
capital for their projects globally at a small cost, with low barriers and
support investors around the world who can invest in potential projects
more easily, manage their assets and provide them with great trading tools",
    "explorer": "
https://etherscan.io/token/0x564f45b6bb68aded8b660a0d8a0a948dd6d6e4e8"
}

Vào Th 7, 26 thg 9, 2020 vào lúc 14:31 Ian Emmanuel M. Enanoria <
notifications@github.com> đã viết:

**Comment by Iamdeadlyz** [comment]
> i use token aladiex; not silver

@lee01101985, you added 0xf6995f53BE4191DFA32AFf0ac44F25831c1E347b. Kindly double-check the files that you have committed. Do you want to proceed in adding SILVER (SVS)? Or not?
```
blockchains/ethereum/assets/0xf6995f53BE4191DFA32AFf0ac44F25831c1E347b/Silver.png
blockchains/ethereum/assets/0xf6995f53BE4191DFA32AFf0ac44F25831c1E347b/info.json
```

**Comment by lee01101985** [comment]
i need list both; it failed tomorrow
today; i need support aladiex, because aladiex has 1000 transaction and 500 holders
But i think has issues 
image

**Comment by Iamdeadlyz** [comment]
Error is due to the filename of the logo, which can be fixed easily.

Do you want to proceed in adding SILVER (SVS) now or not? Since we can remove it and add ALADIN (ALA) only.

**Comment by lee01101985** [comment]
No; pls update ALADIN now
remove Silver
i will make 500 holders and 1000 transaction for Silver and try later

**Comment by lee01101985** [comment]
About Silver; do you can support for me; i can pay > 2BNB

**Comment by Iamdeadlyz** [comment]
> About Silver; do you can support for me; i can pay > 2BNB

You need to reach the requirements as stated previously. We can put it back and wait for it, or, proceed with ALADIN (ALA) only and you will create a separate pull request to add SILVER (SVS).

**Comment by lee01101985** [comment]
ok continue ALA
i will try Silver later

**Comment by lee01101985** [comment]
i can do add price from coincap?

**Comment by Iamdeadlyz** [comment]
@lee01101985 

Please read our guide on how we get the pricing data: https://community.trustwallet.com/t/where-does-trust-wallet-get-coin-pricing-data-from/333

**Pull request merged**
