### PR TITLE
Add MEALS (BEP20)

### PR DESCRIPTION
**Pull request by MEALS-TOKEN**
Adding info for BEP20 token 'MEALS'.

PR created by <a href="https://assets.trustwallet.com">TW Assets Management</a>

### CODE REVIEW

**Comment by MealsToken** [comment]
Hi Trustwallet/Assets

My project is below the circulation requirements. Is there any chance I can
find an exception to therule? We are a deflationary charity project, I'm
not sure if our burnt supply has been acknowledged. We would love the logo
and price tracking in Trust Wallet. Thanks so much!

**Comment by MealsToken** [comment]
@ramsty I am unable to get bep-2 TWT. I have acquired BEP-20 TWT but Trust wallet is unable to swap to Binance Chain. I am located in the United States. Any Suggestions? Also we are under the circulation requirements. Where can I find more information on the exceptions?
Thanks!

**Comment by ramsty** [comment]
HI!

**Comment by ramsty** [comment]
As per our policy, brand new tokens are not included, there is a minimum requirement of 5000 holder addresses and 10000 transactions, in order to filter out scam tokens.
See the criteria at (mentioned in the first message by the bot): https://community.trustwallet.com/t/how-to-submit-a-token-logo/3863).
Closing PR for now. Please come back to us when all criteria are met.

**Pull request closed without merging**
