### PR TITLE
Add Swapz

### PR DESCRIPTION
**Pull request by zfrond**
Token in PR: BEP20 0xd522A1DcE1CA4B138DDA042a78672307eb124CC2
Symbol: SWAPZ decimals: 18
Website: https://swapz.app (we reduced level of DDOS protection) 
Telegram: https://t.me/swapz_app

### CODE REVIEW

**Comment by zfrond** [comment]
Paid https://explorer.binance.org/tx/1C99BF20B087DCDC8A7A1E116302EC23A454A4A77049393E4819E9B9D73E22B2

**Comment by cryptomanz** [comment]
hello,
can you answer a couple of questions?
• What is the purpose of this token? How will it benefit Trust Wallet users?
 • How is the token being distributed? Are you conducting an airdrop?
 • Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?
 • Is the token listed on a centralized/decentralized exchange?
 • Is a Smart Contract audit completed? Where can we find this information?

**Comment by zfrond** [comment]
#### What is the purpose of this token? How will it benefit Trust Wallet users?

This token will power the cross-chain zero-slippage decentralized exchange that we're building. It will be a governance token and will have other use cases in terms of powering different functions of our platform. These are yet to be determined as we're still in development.

Basically, we need the logo on pancakeswap to help people identify our project faster and protect them from imitators


Our token 

#### How is the token being distributed? Are you conducting an airdrop?
The token was distributed to IDO participants.

#### Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?
We had an IDO on Bscpad and TronPad. 

#### Is the token listed on a centralized/decentralized exchange?

Our token is listed on PancakeSwap (TOP 100) where we want to help our users avoid scams of fake Swapz tokens that take their money. By having our token image on PancakeSwap, we'll be able to protect them. 
https://exchange.pancakeswap.finance/#/swap?outputCurrency=0xd522A1DcE1CA4B138DDA042a78672307eb124CC2

#### Is a Smart Contract audit completed? Where can we find this information?

We have no public code as everything is currently in development. You could find our litepaper on our website.

**Comment by cryptomanz** [comment]
Awaiting for smart contract audit.

**Comment by askucher** [comment]
Token contract?

**Comment by zfrond** [comment]
This is a standard contract for any projects on bscpad https://bscscan.com/address/0xd522A1DcE1CA4B138DDA042a78672307eb124CC2#code


As developer, I have checked the contract. It is ownable but only the mint function is opened for owner. Everything else looks safe. No tx. origin problem, safe math used. The configuration is simple based on well-used set of abstract contracts. 

But I understand you need a detailed conclusion. So we need some time for that.

**Comment by Cryptocool1** [comment]
please create new PR when smart contract audit will be ready.
make sure to mention this PR, so that we can see that fee has been paid already here.

**Pull request closed without merging**
