### PR TITLE
Add XSL Logo and info

### PR DESCRIPTION
**Pull request by XSL-Labs**
This PR is being closed due to inactivity. If you wish to continue, please have us reopen the PR before sending your payment.
Do NOT send payments for closed PR, as the fee may by lost!
  (407 vs. 99 hrs)

### CODE REVIEW

**Comment by catenocrypt** [comment]
As per our policy, brand new tokens are not included, there is a minimum requirement of 2500 holder addresses and 5000 transactions, in order to filter out scam tokens.
See the criteria at (mentioned in the first message by the bot): https://community.trustwallet.com/t/how-to-submit-a-token-logo/3863).
This token has no real usage yet (1 holder address). Closing PR for now. Please come back to us when all criteria are met.  Multi-chain and staking tokens may get special treatment, let us know if this is the case. 

https://bscscan.com/token/0x7e52a123ed6db6ac872a875552935fbbd2544c86

**Comment by XSL-Labs** [comment]
it's done

**Comment by XSL-Labs** [comment]
We just made the payment 
Actually we have more than  2500 token holders and more than 5000 transactions. 
You can check that here : https://bscscan.com/token/0x7e52a123ed6db6ac872a875552935fbbd2544c86

Thank you.

**Comment by XSL-Labs** [comment]
> As per our policy, brand new tokens are not included, there is a minimum requirement of 2500 holder addresses and 5000 transactions, in order to filter out scam tokens.
> See the criteria at (mentioned in the first message by the bot): https://community.trustwallet.com/t/how-to-submit-a-token-logo/3863).
> This token has no real usage yet (1 holder address). Closing PR for now. Please come back to us when all criteria are met. Multi-chain and staking tokens may get special treatment, let us know if this is the case.
> 
> https://bscscan.com/token/0x7e52a123ed6db6ac872a875552935fbbd2544c86

Hello, 
We just made the payment, can you check it please?

**Comment by Cryptocool1** [comment]
Hello,
According to our rules, your SYLLogo.png needs to be renamed to logo.png

**Comment by XSL-Labs** [comment]
Hello , 
Can you reopen the RP in order  to update the name  of the  logo

**Comment by XSL-Labs** [comment]
Hello @Cryptocool1 , 

I try to push my update here but it seems i don't have the write access, can you help to do that ?
I just did it on my fork : https://github.com/XSL-Labs/assets/commit/4d87398d8bc044779b7262fecf0d8d5be103033b.
Thanks.

**Comment by catenocrypt** [comment]
This is messed up a bit.
If you made a fee payment, please provide the TXID, so we can check!

**Comment by XSL-Labs** [comment]
Hello catenocrypt, 
This is the TXID : https://explorer.binance.org/tx/6721C6C766E9B9823210AC143A21329D1245F3E781573294343AA66BAB0F5ED5.
Thanks.

**Comment by catenocrypt** [comment]
Fee for this PR was paid, 250 TWT, https://explorer.binance.org/tx/6721C6C766E9B9823210AC143A21329D1245F3E781573294343AA66BAB0F5ED5

**Comment by catenocrypt** [comment]
This PR contains over 600 changed files, cannot be processed.
image
Please:
- remove your fork of assets repo
- re-create your fork
- add the new file infos
- create new PR, maybe using Assets app https://assets.trustwallet.com (see  https://community.trustwallet.com/t/how-to-submit-a-token-logo-using-assets-app/82957 )
- mention this PR so that we can consider fee paid here

**Comment by XSL-Labs** [comment]
Hello  @catenocrypt ,  
This is  the new RP --> Add SYL Logo and Info #6734.
Thanks.

**Comment by XSL-Labs** [comment]
Hello  @catenocrypt, 
I just created a new RP as requested. 
Thank you.

**Comment by XSL-Labs** [comment]
Hello @catenocrypt,
I just created a new RP as requested --> Add SYL logo and info #6738
Thank you.

**Pull request closed without merging**
