### PR TITLE
Adding WZYN token

### PR DESCRIPTION
**Pull request by lodembeep**
This PR is being closed due to inactivity. If you wish to continue, please have us reopen the PR before sending your payment.
Do NOT send payments for closed PR, as the fee may by lost!
  (60 vs. 60 hrs)

### CODE REVIEW

**Comment by catenocrypt** [comment]
As per our policy, brand new tokens are not included, there is a minimum requirement of 2500 holder addresses and 5000 transactions, in order to filter out scam tokens.
See the criteria at (mentioned in the first message by the bot): https://community.trustwallet.com/t/how-to-submit-a-token-logo/3863).
This token has no real usage yet (17). Closing PR for now. Please come back to us when all criteria are met.

https://etherscan.io/token/0x94ec918ddeecfdfcbf8c8d3e848b7c3e8d8ceaa1

**Comment by lodembeep** [comment]
Hello, actually it is a Wrapper token of an existing coin on another blockchain. Before creating the pull the request i did check the criterias, and i really do think this PR fits in.
Please could you take the time to check the website ? you might be willing to reconsider afterwards.

**Comment by catenocrypt** [comment]
Note: Zyncoin (https://wethio.io) is around rank 300 on CMC.  https://coinmarketcap.com/currencies/zynecoin/

**Comment by lodembeep** [comment]
Could you please reopen. Thanks

**Comment by lodembeep** [comment]
@catenocrypt if possible please, would be nice to do it before the new year :)

**Comment by lodembeep** [comment]
Happy new year guys, i hope we can reopen it soon :)

**Comment by lodembeep** [comment]
@catenocrypt @rfunduk @Wraecca @corymsmith 
Sorry to bug you out guys, i might need some intervention here :)

**Pull request closed without merging**
