### PR TITLE
Add KCCPAD (BEP20)

### PR DESCRIPTION
**Pull request by Darpu7**
Adding info for BEP20 token 'KCCPAD'.

PR created by <a href="https://assets.trustwallet.com">TW Assets Management</a>

### CODE REVIEW

**Comment by Cryptocool1** [comment]
hello,
• What is the purpose of this token? How will it benefit Trust Wallet users?
 • How is the token being distributed? Are you conducting an airdrop?
 • Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?
 • Is the token listed on a centralized/decentralized exchange?
 • Is a Smart Contract audit completed? Where can we find this information?

**Comment by Darpu7** [comment]
Hello!

1. The purpose of this token is an IDO platform on the KCC network,
currently the coin is listed as a BEP20 token with a bridge to KCC network.
The team behind it is the same as BSCPAD and TRONPAD
2. The token was launched with a fair whitelist procedure to investors who
participated in the whitelist
3. There was a token presale
4. The token is available on pancakeswap a decentralized exchange
5. The smart contract was just recently launched and has strong
partnerships with the BSCPAD and TRONPAD team who are running KCCPAD as
well. The team is highly appreciated in the space and is a solid, trusted
team.

Thanks,
Darpu7

**Comment by Cryptocool1** [comment]
• Is a Smart Contract audit completed? Where can we find this information?

**Comment by Cryptocool1** [comment]
Hello,
please create new PR when smart contract audit will be ready.
make sure to mention this PR, so that we can see that fee has been paid already here.

**Pull request merged**
