### PR TITLE
Add Rainbow

### PR DESCRIPTION
**Pull request by ForestMagician**

### CODE REVIEW

**Comment by catenocrypt** [comment]
As per our policy, brand new tokens are not included, there is a minimum requirement of 100 holder addresses and 500 transactions, in order to filter out scam tokens.
See the criteria at (mentioned in the first message by the bot): https://community.trustwallet.com/t/how-to-submit-a-token-logo/3863#how-to-get-approved
This token has no usage.  Putting PR on hold.  Please come back to us when all criteria are met.

https://etherscan.io/token/0x33c23d44679433A88B89ca38D3311A9a3D160699

**Comment by ForestMagician** [comment]
Please consider looking at the website, this is clearly not a low effort project.
If you insist on the listing requirements, I can ping you back in a day or two after we are launched. 
I thought it would be nice to launch with a logo already there.

**Comment by catenocrypt** [comment]
I understand but we had to install these rules with good reason, and cannot make an exception.   Hoepfully our usage limit will be reached fast.

**Comment by ForestMagician** [comment]
@catenocrypt The requirements are now met ( they were met within first 2 hours )

**Pull request merged**
