### PR TITLE
Adding PEEPS to TrustWallet

### PR DESCRIPTION
**Pull request by PEEPScoin**
PEEPS is a community-driven coin built by people within that very same community. It will host an ever-adapting ecosystem built with the visibility and security of the ETH network. The transparency and welcoming community will both allow organic growth and the promotion of ideas to improve the existing crypto landscape.

### CODE REVIEW

**Comment by cryptomanz** [comment]
Hello,
Can your answer some questions?
 • What is the purpose of this token? How will it benefit Trust Wallet users?
 • How is the token being distributed? Are you conducting an airdrop?
 • Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?
 • Is the token listed on a centralized/decentralized exchange?
 • Is a Smart Contract audit completed? Where can we find this information?

**Comment by PEEPScoin** [comment]
Hello,

Thanks for reaching out! Please see the answers to the questions below in
bold and let us know if you have any additional questions - thank you!

• What is the purpose of this token? How will it benefit Trust Wallet
users? *The People's Coin is a Decentralized peer-to-peer platform designed
to securely allow its users access to a gated interactive ecosystem, Safe
Haven. The token contract was deployed as an ERC20 token on the ETH
Network; utilizing Web3.0 capability to effectively ensure its users
security through signature confirmation requirements.*

*PEEPS is the native utility token that is used for:*

*·       Validation of user’s access to ecosystem – must actively hold
specified amount in wallet*

*·       Used for governance votes to determine community decisions on
resource allocation through polling within ecosystem*

*·       A storer of value to be utilized with current and future
integrations, both internally in the ecosystem and externally thru
partnerships*


• How is the token being distributed? Are you conducting an airdrop? *The
token is currently listed on UniSwap and will be listed on an exchange
within the next 4-7 days. There was an airdrop done prior to launch to
fulfill all of the capped presale orders (please see answer to next
question for more information on this).*


• Did you sold the tokens at an Initial Coin Offering (ICO) or a token
presale? *PEEPS Pre-Sale, Launch, Locked Liquidity and Circulating Supply:*

*The People’s Coin held a capped presale, with the goal of creating a truly
fair launch, that reached the target goal of 750 ETH within 36 hours of
opening. The project launched the next day on June 27, 2021 with an
original fixed total supply of 1 quadrillion tokens; but burned more than
44% of the total supply coinciding with the official launch to ensure the
deflationary aspect of the tokenomics; which include a 2% distribution + 2%
burn per transaction, totaling 4%. To instill confidence in the project
from day one, hours after launch, the project’s team proceeded to
officially lock 99% of the liquidity for one year via Unicrypt.
Additionally, to ensure fair distribution the total Team allocation was
less than 6% of the total supply; with both Team Wallets being
transparently labeled via their ETH domain address titles:
thepeopleswallet.eth & peepsdevelopmentwallet.eth respectively.*


• Is the token listed on a centralized/decentralized exchange? *It is
currently listed and being traded/swapped on Uniswap, but will be also
listed on an official exchange (either CoinsBit or HotBit within the next
4-7 days).*


• Is a Smart Contract audit completed? Where can we find this
information? *Yes,
we had an official audit completed by Solidity Finance. Please see the
following for the official results:* Solidity Finance:
https://solidity.finance/audits/ThePeoplesCoin/

Additional info:

Website : https://thepeoplescoin.money

Telegram: https://t.me/thepeoplescoinofficial

Twitter: https://twitter.com/ThePeoples_Coin

Facebook: https://www.facebook.com/groups/thepeoplescoin/?ref=share

CoinMarketCap: https://coinmarketcap.com/currencies/the-peoples-coin/

CoinGecko: https://www.coingecko.com/en/coins/the-people-coin

Github: https://github.com/PEEPScoin CoinSniper:
https://coinsniper.net/coin/6225

StockTwits:https://stocktwits.com/symbol/PEEPS.X

Solidity Finance: https://solidity.finance/audits/ThePeoplesCoin/

CoinVote: https://coinvote.cc/coin/The_Peoples_Coin

Buy on Uniswap:
https://app.uniswap.org/#/swap?outputCurrency=0xe1030b48b2033314979143766d7dc1f40ef8ce11&use=V2

View on Dextools.io:
https://www.dextools.io/app/uniswap/pair-explorer/0x6cbcd84abcfbb411426dc21a621fe9a68b985bf4

Unicrypt Locked Liquidity:

https://app.unicrypt.network/amm/uni-v2/pair/0x6CBcD84AbCfBB411426DC21a621FE9A68B985Bf4
- The People's Coin
https://thepeoplescoin.money
Join our socials: Facebook
<https://www.facebook.com/groups/thepeoplescoin/?ref=share> Twitter
<https://twitter.com/ThePeoples_Coin> Telegram
<https://t.me/thepeoplescoinofficial> CoinMarketCap
<https://coinmarketcap.com/currencies/the-peoples-coin/> GitHub
<https://github.com/PEEPScoin>

**Comment by PEEPScoin** [comment]
Hi Nazar,

You helped me to add the logo and necessary features to the TrustWallet
Github for my solo project, The People's Coin (PEEPS), back in July. Thank
you for that again.

I am now helping a few other projects to get all of their logo's, accurate
project information, and other various listings completed and I was hoping
to work with you again for two of them for the TrustWallet integration on
GitHub, as you assisted me with for The People's Coin (PEEPS).

The two project's are:

   - MemeCoinUniverse (MCU)
   - Level Up (LVLUP)

If I were to send you an email from their respective official email
addresses (both are CC'ed), with all of the necessary information I
provided for The People's Coin (PEEPS), would you please assist me with
this? I've already prepared each project to send the corresponding TWT or
BNB once completed, fyi.

Thanks again and I look forward to hearing from you.


- Zack (PEEPSchamp)
The People's Coin
https://thepeoplescoin.money
Join our socials: Facebook
<https://www.facebook.com/groups/thepeoplescoin/?ref=share> Twitter
<https://twitter.com/ThePeoples_Coin> Telegram
<https://t.me/thepeoplescoinofficial> CoinMarketCap
<https://coinmarketcap.com/currencies/the-peoples-coin/> GitHub
<https://github.com/PEEPScoin>

**Comment by PEEPScoin** [comment]
Hello Nazar/TrustWallet,

The People's Coin (PEEP$)  has officially migrated our token smart contract
and needs to update our TrustWallet GitHub as well so it sources
appropriately for TW and CB Wallet users alike, among all other things that
connect with TW; as you can see in this email thread, we worked with you to
add our previous token smart contract to the TW GitHub. Hopefully the info
provided below is what you need to help us, but please let us know if there
is anything else we need to provide so we can submit it ASAP.

Updated Token Smart Contract:
https://etherscan.io/token/0x5919DeA604631016c15c805e3D948A0384879892

OLD Token Smart Contract page on Etherscan.io that is already updated with
"Token Migration Announcement"  and the link to the updated Etherscan.io
page:
https://etherscan.io/token/0xe1030b48b2033314979143766d7dc1f40ef8ce11

Link to "Token Migration Announcement" as listed on Etherscan.io:
***@***.***/the-peoples-coin-official-smart-contract-migration-re-launch-316bd4a5fd54

We airdropped all holders their exact same value of tokens prior to
officially Re-Launching on June 16, 2023. We still have the same mission
statement, but have not only grown, but also instituted several improved
features, initiatives, and functionality for the project as we continue to
grow.

Additional Info:

*LinkTree:* *https://linktr.ee/thepeoplescoin*
<https://linktr.ee/thepeoplescoin>

Website : https://thepeoplescoin.money

Telegram: https://t.me/thepeoplescoinofficial

Twitter: https://twitter.com/ThePeoples_Coin

Facebook: https://www.facebook.com/groups/thepeoplescoi*n1*
<https://www.facebook.com/groups/thepeoplescoin1>

CoinMarketCap: (updating in progress)
https://coinmarketcap.com/currencies/the-peoples-coin/

CoinGecko: (updating in progress)
https://www.coingecko.com/en/coins/the-people-coin

Github: https://github.com/The-Peoples-Coin

Uniswap:
https://v2.info.uniswap.org/token/0x5919dea604631016c15c805e3d948a0384879892

View on Dextools.io:
https://www.dextools.io/app/en/ether/pair-explorer/0xfdd0f179ae8f71e55a5aa5c39b336dda63fb17d7


We look forward to hearing back from you - thanks again!

The People's Coin

Please visit and join our socials below:
Website <https://thepeoplescoin.money> | Facebook
<https://www.facebook.com/groups/thepeoplescoin1> | Twitter
<https://twitter.com/ThePeoples_Coin> | Telegram
<https://t.me/thepeoplescoinofficial> | CoinMarketCap
<https://coinmarketcap.com/currencies/the-peoples-coin/> | Medium
***@***.***>

**Comment by Cryptocool1** [comment]
Hello, you should create new Pull Request with new contract address

**Comment by PEEPScoin** [comment]
Hi there,

We've attempted but it's not allowing us to push the Pull Request. I
believe it's bc of the amount of holders (6,625) which only needed to be
5,000 when we first submitted for approval; and also, potentially not
enough transactions on this migrated token contract address.

As I mentioned in the previous email, we're simply asking for the migration
of our existing approval to be properly registered. There are many existing
holders that use both TrustWallet and CB Wallet and they aren't able to
properly access or utilize their apps until this is resolved. Will you
please assist on how to get this done?

We appreciate your assistance!

The People's Coin

Please visit and join our socials below:
Website <https://thepeoplescoin.money> | Facebook
<https://www.facebook.com/groups/thepeoplescoin1> | Twitter
<https://twitter.com/ThePeoples_Coin> | Telegram
<https://t.me/thepeoplescoinofficial> | CoinMarketCap
<https://coinmarketcap.com/currencies/the-peoples-coin/> | Medium
***@***.***>

**Comment by Cryptocool1** [comment]
Please try to create PR again and mention this PR there. Thanks

**Comment by PEEPScoin** [comment]
*Hello,*

*We did create PR again and mentioned the migration as per your direction.
We also sent payment, but it appears the PR was closed for some reason
prior to it being committed? I've forwarded the correspondence I sent below
and still haven't received a response; please advise.*

*Forwarded Message Below:*

Hello, payment was sent.

https://explorer.binance.org/tx/BF76147CA139852854B79F48B4539C35DD23889AD4A05F4AED9F9C21DA32CB9A

The People's Coin (PEEP$) has officially migrated our token smart contract
and needs to update our TrustWallet GitHub as well so it sources
appropriately for TW and CB Wallet users alike, among all other things that
connect with TW; as you can see in this email thread, we worked with you to
add our previous token smart contract to the TW GitHub. Hopefully the info
provided below is what you need to help us, but please let us know if there
is anything else we need to provide so we can submit it ASAP.

Updated Token Smart Contract: 0x5919DeA604631016c15c805e3D948A0384879892

Updated Token Smart Contract on Ethersca.io:
https://etherscan.io/token/0x5919DeA604631016c15c805e3D948A0384879892

OLD Token Smart Contract page on Etherscan.io that is already updated with
"Token Migration Announcement" and the link to the updated Etherscan.io
page:
https://etherscan.io/token/0xe1030b48b2033314979143766d7dc1f40ef8ce11

Link to "Token Migration Announcement" as listed on Etherscan.io:
***@***.***/the-peoples-coin-official-smart-contract-migration-re-launch-316bd4a5fd54

We airdropped all holders their exact same value of tokens prior to
officially Re-Launching on June 16, 2023. We still have the same mission
statement, but have not only grown, but also instituted several improved
features, initiatives, and functionality for the project as we continue to
grow.

Additional Info:

LinkTree: https://linktr.ee/thepeoplescoin

Website : https://thepeoplescoin.money/

Telegram: https://t.me/thepeoplescoinofficial
<https://t.me/thepeoplescoinofficial>

Twitter: https://twitter.com/ThePeoples_Coin

Facebook: https://www.facebook.com/groups/thepeoplescoin1

CoinMarketCap: (updating in progress)
https://coinmarketcap.com/currencies/the-peoples-coin/

CoinGecko: (updating in progress)
https://www.coingecko.com/en/coins/the-people-coin

Github: https://github.com/PEEPScoin

Uniswap:
https://v2.info.uniswap.org/token/0x5919dea604631016c15c805e3d948a0384879892

View on Dextools.io:
https://www.dextools.io/app/en/ether/pair-explorer/0xfdd0f179ae8f71e55a5aa5c39b336dda63fb17d7

Logo: 256x256 transparent png attached


*Please let us know what we need to do to get this properly pushed for the
PR with TW again - thank you!*

*The People's Coin*

Please visit and join our socials below:
Website <https://thepeoplescoin.money> | Facebook
<https://www.facebook.com/groups/thepeoplescoin1> | Twitter
<https://twitter.com/ThePeoples_Coin> | Telegram
<https://t.me/thepeoplescoinofficial> | CoinMarketCap
<https://coinmarketcap.com/currencies/the-peoples-coin/> | Medium
***@***.***>

**Comment by Cryptocool1** [comment]
Your PR was incorrect, please follow my instructions above

**Pull request merged**
