### PR TITLE
FLAME LOGO

### PR DESCRIPTION
**Pull request by Flamechain2021**
FLAME LOGO

### CODE REVIEW

**Comment by Flamechain2021** [comment]
is there any problem about my request ?

**Comment by Cryptocool1** [comment]
info file should be named info.json

**Comment by Flamechain2021** [comment]
> info file should be named info.json

should i need to make new upload of files?

**Comment by Cryptocool1** [comment]
> > info file should be named info.json
> 
> should i need to make new upload of files?

It’s up to you

**Comment by Flamechain2021** [comment]
Please tell me if there's any i can do to fix it i already send a new file

**Comment by Flamechain2021** [comment]
Hello can you please update this transaction

**Comment by Flamechain2021** [comment]
Any update about this transaction

**Comment by Cryptocool1** [comment]
can u answer some questions?
• What is the purpose of this token? How will it benefit Trust Wallet users?
 • How is the token being distributed? Are you conducting an airdrop?
 • Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?
 • Is the token listed on a centralized/decentralized exchange?
 • Is a Smart Contract audit completed? Where can we find this information?

**Comment by Flamechain2021** [comment]
• What is the purpose of this token? How will it benefit Trust Wallet users?
Flame Chain project has some great Features secure, useful, & easy-to-use Product based on Binance Smart Chain, it will include easy cryptocurrency payments integration, and even a digital arbitration system .

• How is the token being distributed? Are you conducting an airdrop?
Airdrop and Token Sale and upcoming hotbit listing on JULY 9

• Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?
Token Sale and upcoming hotbit listing on JULY 9

• Is the token listed on a centralized/decentralized exchange?
hotbit listing on JULY 9

• Is a Smart Contract audit completed? Where can we find this information?
you can check it on the website 
https://flamechain.io/

**Comment by Flamechain2021** [comment]
PLEASE UPDATE

**Comment by Cryptocool1** [comment]
> • What is the purpose of this token? How will it benefit Trust Wallet users?
> Flame Chain project has some great Features secure, useful, & easy-to-use Product based on Binance Smart Chain, it will include easy cryptocurrency payments integration, and even a digital arbitration system .
> 
> • How is the token being distributed? Are you conducting an airdrop?
> Airdrop and Token Sale and upcoming hotbit listing on JULY 9
> 
> • Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?
> Token Sale and upcoming hotbit listing on JULY 9
> 
> • Is the token listed on a centralized/decentralized exchange?
> hotbit listing on JULY 9
> 
> • Is a Smart Contract audit completed? Where can we find this information?
> you can check it on the website
> https://flamechain.io/

hotbit listing is ready?

**Comment by Flamechain2021** [comment]
Hello why the LOGO still not showing on the TRUST WALLET?

**Comment by Cryptocool1** [comment]
You didn’t answer the question

**Comment by Cryptocool1** [comment]
hotbit listing is ready?

**Comment by Flamechain2021** [comment]
> hotbit listing is ready?

YES already listed on hotbit
https://www.hotbit.io/exchange?symbol=FLAME_USDT

**Pull request merged**
