### PR TITLE
Replace BONK logo please

### PR DESCRIPTION
**Pull request by bonktoken**
https://bonktoken.com/
logo

### CODE REVIEW

**Comment by bonktoken** [comment]
this is my second time paying, please replace

**Comment by catenocrypt** [comment]
PR contains 2 logos: old token, with checksummed contract in the name, and new one, with all-lowercase (which is wrong).  I can fix this if there is no other issue.
Token usage is low, but over our limit; new logo matches logo on website.

Please add an `info.json` file next to the logo.png, with info about the project, of the form:
https://github.com/trustwallet/assets/blob/master/blockchains/ethereum/assets/0x0000000000085d4780B73119b644AE5ecd22b376/info.json

(full filename: `blockchains/ethereum/assets/0x6D6506E6F438edE269877a0A720026559110B7d5/info.json`)

**Comment by bonktoken** [comment]
Adam,

I've never had to follow all these guidelines before. would you mind
uploading new one now that it is on the website.

best
David

**Comment by bonktoken** [comment]
Okay, I understand the importance of the formatting now. Please check this & see if this is okay.

Thank you, David

**Comment by bonktoken** [comment]
@catenocrypt @zachzwei do I need to provide more information?

**Comment by catenocrypt** [comment]
Note: #3646 .

**Pull request closed without merging**
