### PR TITLE
Add KING FOREVER (BEP20)

### PR DESCRIPTION
**Pull request by KINGFOREVERBSC**
Adding info for BEP20 token 'KING FOREVER'.

PR created by <a href="https://assets.trustwallet.com">TW Assets Management</a>

### CODE REVIEW

**Comment by Cryptocool1** [comment]
As per our policy, brand new tokens are not included, there is a minimum requirement of 10,000 holder addresses and 20,000 transactions, in order to filter out scam tokens.
See the criteria at : https://developer.trustwallet.com/assets/requirements .

**Comment by Kedimdevlyn** [comment]
image

**Comment by Kedimdevlyn** [comment]
Hello, I understand your condition, it's a real project the update has already been done on bscscan, can find all the information you have the identity of our teams also KYC PLATFORM pinksale. Nous devons mettre à jour le logo pour rassurer nos investisseurs.

**Comment by Kedimdevlyn** [comment]
image


https://bscscan.com/token/0x4cbda3d23c031cd403db2d24512ad920bf22f205


When you look at this project it has only 3.5 K HOLDERS And we have more than 5K HOLDERS, this allows us to create confidence in our investors and to be reassured.

I hope to have a favorable response from you, if you have any questions or request for documents we can send you.

do not hesitate to ask .

Salah CEO

KING FOREVER TEAM .

**Pull request closed without merging**
