### PR TITLE
feat: add FOMO token on BASE chain

### PR DESCRIPTION
**Pull request by artiffine-vojtech**

### CODE REVIEW

**Comment by Cryptocool1** [comment]
• What is the purpose of this token? How will it benefit Trust Wallet users?
 • How is the token being distributed? Are you conducting an airdrop?
 • Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?
 • Is the token listed on a centralized/decentralized exchange?
 • Is a Smart Contract audit completed? Where can we find this information?

**Comment by artiffine-vojtech** [comment]
Hi @Cryptocool1 
• What is the purpose of this token? How will it benefit Trust Wallet users?
FOMO BULL CLUB is a members-only, decentralized launchpad and liquidity hub. It initially supports memecoins on the Base blockchain. Member NFT holders propose and vote on either the launch of new or the re-launch of existing memecoins on FBC, by contributing MEME token to their launch liquidity pools. Launches are fully automated, decentralized, and created with liquidity staking and yield farming. This approach grants memecoins launched on FBC instant utility and maximized sustainability

• How is the token being distributed? Are you conducting an airdrop?
There were multiple presale rounds with a total allocation of 20% of the token supply (KOL Sale, Member Sale, Community Sale)
There are 4 rounds of airdrop (details available at https://fomobull.club/airdrop). The first round is already ongoing, the rest of the rounds is planned for the following weeks. All airdropped tokens are vested for 12 months with linear monthly unlocks. 

• Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?
Yes, the token presale was done through Enjinstarter platform. 

• Is the token listed on a centralized/decentralized exchange?
Yes, the token is listed on Uniswap, MEXC, Bitget, LBank, Bitmark.
All the markets can be seen at https://coinmarketcap.com/currencies/fomo-bull-club

• Is a Smart Contract audit completed? Where can we find this information?
The token is part of a greater ecosystem of FOMO Bull Club Memecoin launchpad. The launchpad platform will be launched in the upcoming weeks and will be audited. 

If you need more information about the token, check out project website https://fomobull.club/ or whitepaper https://fomobull.club/bullpaper.pdf

Let me know if you have additional questions.

**Comment by Cryptocool1** [comment]
Hello, we require smart contract audit from reputable companies ( for example: Certik, Techrate, Hacken, Dessert Finance)
Feel free to come back to us once audit is done. Make sure to mention this PR so the fee can be reused

**Comment by artiffine-vojtech** [comment]
Hi @Cryptocool1 we have the token audited by Dessert Finance, here is the link: https://dessertswap.finance/audits/FOMO-BASE-Audit-15060609.pdf

Can we proceed with the listing on Trust Wallet, please?

**Pull request closed without merging**
