### PR TITLE
s

### PR DESCRIPTION
**Pull request by Kofro**
s

### CODE REVIEW

**Comment by Cryptocool1** [comment]
As per our policy, brand new tokens are not included, there is a minimum requirement of 2500 holder addresses and 5000 transactions, in order to filter out scam tokens.
See the criteria at (mentioned in the first message by the bot): https://community.trustwallet.com/t/how-to-submit-a-token-logo/3863).
Closing PR for now. Please come back to us when all criteria are met.

**Comment by Kofro** [comment]
We are not a scam token, we are audited and have fully doxed ourselves to prove this.
https://www.facebook.com/kodi.taneraulove/ -- me_irl
https://www.rugbusters.net/audits/uranus-token -- audit
https://www.youtube.com/watch?v=dQw4w9WgXcQ

**Comment by Kofro** [comment]
@Cryptocool1

**Comment by Cryptocool1** [comment]
> We are not a scam token, we are audited and have fully doxed ourselves to prove this.
> https://www.facebook.com/kodi.taneraulove/ -- me_irl
> https://www.rugbusters.net/audits/uranus-token -- audit
> https://www.youtube.com/watch?v=dQw4w9WgXcQ

Please come back to us when all criteria are met.

**Pull request closed without merging**
