### PR TITLE
Add Oddz token from Oddz finance(https://oddz.fi)

### PR DESCRIPTION
**Pull request by shreedharshetty**
Hi,
Greetings from Oddz finance,

More details on oddz finance can be found here:

Website: https://oddz.fi/
Whitepaper: https://docsend.com/view/mefxr8h3ymzuhwqk
Telegram: https://t.me/oddz_finance
Medium: https://medium.com/oddz-finance
Twitter: https://twitter.com/oddz_finance

We will be listing on Uniswap on 18th March and then listing on other exchanges as well. 

Thanks,
Oddz finance

### CODE REVIEW

**Comment by catenocrypt** [comment]
As per our policy, brand new tokens are not included, there is a minimum requirement of 2500 holder addresses and 5000 transactions, in order to filter out scam tokens.
See the criteria at (mentioned in the first message by the bot): https://community.trustwallet.com/t/how-to-submit-a-token-logo/3863).
This token has no real usage yet (1 holder address). Closing PR for now. Please come back to us when all criteria are met.  Multi-chain and staking tokens may get special treatment, let us know if this is the case. 

https://etherscan.io/token/0xCd2828fc4D8E8a0eDe91bB38CF64B1a81De65Bf6

**Comment by shreedharshetty** [comment]
@catenocrypt Can we reopen this PR as we have 1677 holders since the launch, https://etherscan.io/token/0xcd2828fc4d8e8a0ede91bb38cf64b1a81de65bf6

**Comment by catenocrypt** [comment]
Reopened.  Circulation increasing, currently 1831 holders.  Fee not yet paid.

https://etherscan.io/token/0xCd2828fc4D8E8a0eDe91bB38CF64B1a81De65Bf6

**Comment by shreedharshetty** [comment]
@zachzwei @catenocrypt @Iamdeadlyz we now have 2034 holders, can we please review this PR?

**Pull request merged**
