### PR TITLE
add GXT ERC20

### PR DESCRIPTION
**Pull request by gxtmg**
Adding info for ECR20 token 'GXT'.

### CODE REVIEW

**Comment by Cryptocool1** [comment]
As per our policy, brand new tokens are not included, there is a minimum requirement of 10,000 holder addresses and 20,000 transactions, in order to filter out scam tokens.
See the criteria at : https://developer.trustwallet.com/assets/requirements .

**Comment by gxtmg** [comment]
https://etherscan.io/token/0x874d4c9b980f1a13dd44cbcdb912e24ef0671ed0

**Comment by gxtmg** [comment]
https://etherscan.io/token/0x874d4c9b980f1a13dd44cbcdb912e24ef0671ed0   --> It is GDR token which has 2396 holders and 3030 transactions. But i can see their logo in uniswap. I hope you can tell us how it is possible without being conditioned like this token.

**Comment by gxtmg** [comment]
> As per our policy, brand new tokens are not included, there is a minimum requirement of 10,000 holder addresses and 20,000 transactions, in order to filter out scam tokens. See the criteria at : https://developer.trustwallet.com/assets/requirements .

**Comment by gxtmg** [comment]
> As per our policy, brand new tokens are not included, there is a minimum requirement of 10,000 holder addresses and 20,000 transactions, in order to filter out scam tokens. See the criteria at : https://developer.trustwallet.com/assets/requirements .

https://etherscan.io/token/0x0766e79a6fd74469733e8330b3b461c0320ff059
also it can see their logo which has 2396 holders and 3060 transactions.

**Comment by gxtmg** [comment]
@Cryptocool1 

Our token is not a scam. If necessary, I can also show you a new white paper. Also, our internal wallet has more than 20,000 members.

**Pull request closed without merging**
