### PR TITLE
Add Darik (BEP20)

### PR DESCRIPTION
**Pull request by nima2142**
Adding info for BEP20 token 'Darik'.

PR created by <a href="https://assets.trustwallet.com">TW Assets Management</a>

### CODE REVIEW

**Comment by nima2142** [comment]
> • What is the purpose of this token? How will it benefit Trust Wallet users? • How is the token being distributed? Are you conducting an airdrop? • Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale? • Is the token listed on a centralized/decentralized exchange? • Is a Smart Contract audit completed? Where can we find this information?

• What is the purpose of this token? How will it benefit Trust Wallet users?
This token (Darik) is made to be used in trading and buying from the www.companypoll.com stock exchange system, and all users use Trust Wallet to trade it, and by buying and transferring it to the stock exchange system, they can buy the desired goods.
• How is the token being distributed? Are you conducting an airdrop?
15% of this token (Darik) has been floated and 85% of it has been frozen for future transactions in the stock exchange system and will be biased with the continuation of future contracts with the stock market of different countries.
• Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?
Only 15% of the tokens have been pre-sold or assigned to users, and the initial release is offered to users for a test period and for an application software in the stock market.
• Is the token (Darik)  listed on a centralized/decentralized exchange?
This token is listed on a centralized exchange https://bitsarf.com and a decentralized exchange https://mybitswap.com/.
• Is a Smart Contract audit completed? Where can we find this information?
So far, no audit has been done on the financial circulation of this token because it is a startup project and has just started working.

**Comment by cryptomanz1** [comment]
Awaiting for smart contract audit. On hold for now

**Comment by nima2142** [comment]
> Awaiting for smart contract audit. On hold for now

what should i do now?!

**Comment by Cryptocool1** [comment]
> > Awaiting for smart contract audit. On hold for now
> 
> what should i do now?!

We are waiting for your audit

**Comment by nima2142** [comment]
> > > Awaiting for smart contract audit. On hold for now
> > 
> > 
> > what should i do now?!
> 
> We are waiting for your audit
this is an audit from dextools.io
https://www.dextools.io/app/en/bnb/pair-explorer/0xbba50be7a1cb6e25ddda562b0ca278089bf9068a
if this site is not acceptable by your view please send your preferred site

**Comment by nima2142** [comment]
> > > Awaiting for smart contract audit. On hold for now
> > 
> > 
> > what should i do now?!
> 
> We are waiting for your audit

this is an audit from dextools.io
https://www.dextools.io/app/en/bnb/pair-explorer/0xbba50be7a1cb6e25ddda562b0ca278089bf9068a
if this site is not acceptable by your view please send your preferred site

**Pull request merged**
