### PR TITLE
Add Shihtzu Exchange Token (BEP20)

### PR DESCRIPTION
**Pull request by shihtzuexchange**
Adding info for BEP20 token 'Shihtzu Exchange Token'.

PR created by <a href="https://assets.trustwallet.com">TW Assets Management</a>

### CODE REVIEW

**Comment by cryptomanz1** [comment]
• What is the purpose of this token? How will it benefit Trust Wallet users?
 • How is the token being distributed? Are you conducting an airdrop?
 • Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?
 • Is the token listed on a centralized/decentralized exchange?
 • Is a Smart Contract audit completed? Where can we find this information?

**Comment by shihtzuexchange** [comment]
1.  It serves to educate potential investors about the token's function and use within a decentralized community ecosystem, promoting transparency and trust. This benefits Trust Wallet users' authenticity by providing information about legitimate tokens and avoiding spam tokens.
2. Token is being distributed through DEX.
3. No, we did not sell any ICO or token presale.
4. Yes, it is listed on Pancakeswap. Here is the link https://pancakeswap.finance/swap?outputCurrency=0x31801b15215c021e7988fa0bc37dcfa6a303bd00
5. No, We used and standard library which is provided by openzepplin, and did not need any smart contract audit and even did not mention it on the required list.

**Comment by Cryptocool1** [comment]
Hello, we require smart contract audit from reputable companies 
Please see our doc https://developer.trustwallet.com/listing-new-assets/requirements

**Comment by Cryptocool1** [comment]
Please come back to us once audit is done. Make sure to mention this PR so the fee can be reused

**Pull request closed without merging**
