### PR TITLE
Add SpaceXCoin (BEP20)

### PR DESCRIPTION
**Pull request by HandyxGIT**
Adding info for BEP20 token 'SpaceXCoin'.

PR created by <a href="https://assets.trustwallet.com">TW Assets Management</a>

### CODE REVIEW

**Comment by cryptomanz1** [comment]
As per our policy, there is a minimum requirement of 10,000 holder addresses and 15,000 transactions, in order to filter out scam tokens.
See the criteria at : https://developer.trustwallet.com/listing-new-assets/requirements .

**Comment by HandyxGIT** [comment]
I thought you had exception for that 10,000 holder requirements. We are not a scam token. We are listed on Bitmart and Our company is registered in the State of Florida, USA

**Comment by HandyxGIT** [comment]
I am trying to make the payments. Its not east to make payments of Binance chain.

**Comment by HandyxGIT** [comment]
> As per our policy, there is a minimum requirement of 10,000 holder addresses and 15,000 transactions, in order to filter out scam tokens. See the criteria at : https://developer.trustwallet.com/listing-new-assets/requirements .

We are not a scam token.

**Pull request closed without merging**
