### PR TITLE
Add GroveToken (BEP20)

### PR DESCRIPTION
**Pull request by Grovetoken**
Adding info for BEP20 token 'GroveToken'.

PR created by <a href="https://assets.trustwallet.com">TW Assets Management</a>

### CODE REVIEW

**Comment by Grovetoken** [comment]
Hi any progress ?

**Comment by Grovetoken** [comment]
Hi,

Please see below is there any progress ?

Re: [trustwallet/assets] Add GroveToken (BEP2) (PR #19480)

Please create new PR, follow doc https://developer.trustwallet.com/assets/requirements
You may want to try our Assets app in beta; go to https://assets.trustwallet.com, log on with Github, enter contract ID, logo and some additional info, and it will create a PR for you.
See https://developer.trustwallet.com/assets/repository_details

 

 

John G | Founder @ GroveToken & GroveBusiness

E:  ***@***.***> ***@***.***

Twitter:  <https://twitter.com/GroveToken> https://twitter.com/GroveToken

Facebook:  <https://www.facebook.com/GroveTokenOfficial> https://www.facebook.com/GroveTokenOfficial

Instagram:  <https://www.instagram.com/grovetoken/> https://www.instagram.com/grovetoken/

Telegram:  <https://t.me/Grovetoken> https://t.me/Grovetoken

Website:  <https://grovetoken.com/> https://GroveToken.com

**Comment by Grovetoken** [comment]
Already paid please refer back to 

Re: [trustwallet/assets] Add GroveToken (BEP2) (PR #19480)

As promised last all what I needed is an audit that I provided 

 

John G | Founder @ GroveToken & GroveBusiness

E:  ***@***.***> ***@***.***

Twitter:  <https://twitter.com/GroveToken> https://twitter.com/GroveToken

Facebook:  <https://www.facebook.com/GroveTokenOfficial> https://www.facebook.com/GroveTokenOfficial

Instagram:  <https://www.instagram.com/grovetoken/> https://www.instagram.com/grovetoken/

Telegram:  <https://t.me/Grovetoken> https://t.me/Grovetoken

Website:  <https://grovetoken.com/> https://GroveToken.com

**Comment by Grovetoken** [comment]
and 
Re: [trustwallet/assets] Add GroveToken (BEP20) (PR #19464)

**Comment by Grovetoken** [comment]
#19352 opened 6 days ago by [enoughpower](https://github.com/trustwallet/assets/issues?q=is%3Apr+is%3Aopen+author%3Aenoughpower)
• [Approved](https://github.com/trustwallet/assets/pull/19352#partial-pull-merging)

**Comment by Grovetoken** [comment]
Please refer back to previous job numbers All good to go with audit done and being perfect please dont cloe before giving a chance to answer 
Re: [trustwallet/assets] Add GroveToken (BEP20) (PR https://github.com/trustwallet/assets/pull/19464)
Re: [trustwallet/assets] Add GroveToken (BEP2) (PR [#19480](https://github.com/trustwallet/assets/pull/19480))
https://www.grovetoken.com/_files/ugd/8eae10_db9b69bf264b4335bff0c109ea03c4e5.pdf

**Comment by Cryptocool1** [comment]
We require smart contract audit completed by reputable security audit groups. (Certik, Techrate, Hacken, InterFi, Dessert Finance).
Please come bak to us when all criteria are met. Make sure to mention this PR so the fee can be reused.

**Comment by Cryptocool1** [comment]
As per our policy, brand new tokens are not included, there is a minimum requirement of 10,000 holder addresses and 15,000 transactions, in order to filter out scam tokens.
See the criteria at : https://developer.trustwallet.com/assets/requirements .

**Pull request closed without merging**
