### PR TITLE
https://github.com/trustwallet/assets/pull/21972

### PR DESCRIPTION
**Pull request by SmurfsINUDeployer**
Friends, we sincerely apologize, we will have troubled you twice, but as we explained, it was possible that we made a mistake.
From you:
This is a BEp20 token, correct folder is blockchains/smartchain/assets.
Please create new PR, follow doc https://developer.trustwallet.com/assets/requirements
You may want to try our Assets app in beta; go to https://assets.trustwallet.com/, log on with Github, enter contract ID, logo and some additional info, and it will create a PR for you.
See https://developer.trustwallet.com/assets/repository_details
Closed [#21972](https://github.com/trustwallet/assets/pull/21972)
Make sure so mention this PR so the fee can be reused

### CODE REVIEW

**Comment by Cryptocool1** [comment]
#21972 paid

**Comment by SmurfsINUDeployer** [comment]
Really great you reported our mistake and provided quick fix, our community will hold a special event for TrustWallet. Respects
I still want to leave our links:
https://www.coingecko.com/en/smurfsinu
https://www.binance.com/en/price/smurfsinu
https://crypto.com/price/smurfsinu

**Comment by Cryptocool1** [comment]
• What is the purpose of this token? How will it benefit Trust Wallet users?
 • How is the token being distributed? Are you conducting an airdrop?
 • Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?
 • Is the token listed on a centralized/decentralized exchange?
 • Is a Smart Contract audit completed? Where can we find this information?

**Comment by SmurfsINUDeployer** [comment]
SmurfsVerse's World: 
Create, Play, Personalise, Earn in SmurfsVerse
With SmurfsVerse you really can take the reality of living and dreaming into a virtual world. Where all aspects are created, designed, and perfected by you.
Starting with player skills and characteristics, this will give you an online fresh start where you choose your path of success within the SmurfsVerse World.

SmurfsINU ArtGallery: All of our NFTs can be staked in our exclusive Staking pools. Game items could both be traded through the in-game #marketplace and also the NFT marketplaces on other blockchains.
It creates #liquidity for the assets created through the game and also encourages more players to participate in building  the SmurfsINU world.

SmurfsVerse Special platform for FIFAWorldCupQatar2022™: SmurfsINU will prepare a special platform for the FIFA World Cup Qatar 2022™ in the world of SmurfsVerse.
It is a special series with a high stake and farm rate, while providing special in-game advantages. Every NFT in this series will be unique and only one will be produced for each hero. All tournament matches will be played live in the SmurfsVerse universe and will be open for bets.


Smurfs INU web 3.0 BettingPlatform: This platform has been specially designed for the FIFA World Cup Qatar 2022™. Surprise betting options will be open for all world cup matches and all matches will be played live in the SmurfsVerse universe.


SmurfsINU DeFi ecosystem:
SmurfsINU DexWallet Application: SmurfsINU was established to create an ecosystem for crypto users to provide easy and fast access to all DeFi and Metaverse activities.
Accordingly, SmurfSwap - SmurfStake&Farm - SmurfLock platforms are being built in the background.
In addition, SmurfsINU Art Gallery will also be integrated into SmurfsDexWallet. With the SmurfsINU Wallet application, access to all DeFi and MetaFi services will be cheap, fast and easy.


SmurfsINU Characters: Each player will create their own identity with specific characteristics, skills and attributes.
These chosen skills will allow you to browse the SmurfsINU in-game world to complete different daily tasks for fun&rewards!



Our project was launched on Aug-07-2022. The total supply is 1,000,000,000,000,000 SMURF tokens.
SmurfsINU has been specially designed at every stage to be the safest and most loved project. As a result of in-team meetings and social research, it was decided that the tax fee would be 0%. Since the tax fee is 0%, large wallets are not reserved under the name of marketing, team, partnership. Only a 2.5% wallet is reserved for SmurfsINU to be listed on major exchanges. 
With the decision of our finance team, SMURF token will be sold with BUSD parity and liquidity locked along a year.
Since we agreed with an exchange before the launch, you will probably see while you are reviewing the project, 3% supply is reserved for Kucoin and the listing pool has been created in Kucoin. The remaining 97% supply is added to the liquidity. 
The SmurfsINU project will be financed by NFT sales, stakes and sponsorships in the SmurfsVerse universe. Our finance team secured special sponsorship deals specifically for the FIFA World Cup Qatar 2022. One of our biggest goals is to be the mascot of the tournament and to sign a partnership with a big world star.
We can say tokenomics: %97 Supply Add to LP + %3 supply reserved for a major exchange = %100 SMURF




TeamMembers:
Creator OF SmurfsINU Moto MotohiroMatsuyama: Moto, who has been actively working as Talent Acquisition @ Amazon, took active roles in projects such as AxieInfinity and Pokemon Trading Card Game.
He has been playing an active role in the crypto world, especially in the GameFi field for a long time.
He regularly attends audio conferences on Twitter Space. Moto, who also shared candidly with MayeMusk, increased his popularity. Now he created SmurfsINU with all his talents.

Twitter: https://twitter.com/MotoMatsuyama
TG: https://t.me/MotoMatsuyama


Technology and Finance Director - NiallBuckley: Niall works as an advertising director at Mothership Strategies.He is known as Pythagoras in the crypto universe.
He has played an active role in projects such as SAFEMOON, EverRise, FEG on the BinanceSmartChain network.
He has close relationships with global gaming companies and stock markets. He said in his last interview that he will use all his experience and energy to maximize SmurfsINU.


Twitter: https://twitter.com/NiallBuckley19
TG: https://t.me/NiallBuckley19



Community and media consultant - HajimeTossa: Hajime Tossa has been in the crypto market for a long time.
He especially played an active role in making STEPN a big hit in the Asian market. He influenced large masses with his publications on social platforms.
In addition, he has been accepted to the Binance training team with his regular conferences around the world, and he continues this duty actively. He joined the team at Moto’s special request.
This is one of the biggest deals ever made for SmurfsINU to reach SHIBA levels.

Twitter: https://twitter.com/OthersideOwner
TG: https://t.me/BabyDogeWhalehere

It will be provided by Audit Certik. Basic application completed, they got us in line, we can't check this. After all, Binance and other giant platforms listed it.

**Comment by Cryptocool1** [comment]
We require smart contract audit. On hold for now

**Comment by SmurfsINUDeployer** [comment]
Should we upload the information you mentioned to the json file? Or is it enough to comment in this way?

**Comment by SmurfsINUDeployer** [comment]
SmurfsINU Audited by Pinksale Official Partner Block Audit Report: 
https://github.com/Block-Audit-Report/SmurfsINU
All project details:
SmurfsVerse's World: 
Create, Play, Personalise, Earn in SmurfsVerse
With SmurfsVerse you really can take the reality of living and dreaming into a virtual world. Where all aspects are created, designed, and perfected by you.
Starting with player skills and characteristics, this will give you an online fresh start where you choose your path of success within the SmurfsVerse World.

SmurfsINU ArtGallery: All of our NFTs can be staked in our exclusive Staking pools. Game items could both be traded through the in-game #marketplace and also the NFT marketplaces on other blockchains.
It creates #liquidity for the assets created through the game and also encourages more players to participate in building  the SmurfsINU world.

SmurfsVerse Special platform for FIFAWorldCupQatar2022™: SmurfsINU will prepare a special platform for the FIFA World Cup Qatar 2022™ in the world of SmurfsVerse.
It is a special series with a high stake and farm rate, while providing special in-game advantages. Every NFT in this series will be unique and only one will be produced for each hero. All tournament matches will be played live in the SmurfsVerse universe and will be open for bets.


Smurfs INU web 3.0 BettingPlatform: This platform has been specially designed for the FIFA World Cup Qatar 2022™. Surprise betting options will be open for all world cup matches and all matches will be played live in the SmurfsVerse universe.


SmurfsINU DeFi ecosystem:
SmurfsINU DexWallet Application: SmurfsINU was established to create an ecosystem for crypto users to provide easy and fast access to all DeFi and Metaverse activities.
Accordingly, SmurfSwap - SmurfStake&Farm - SmurfLock platforms are being built in the background.
In addition, SmurfsINU Art Gallery will also be integrated into SmurfsDexWallet. With the SmurfsINU Wallet application, access to all DeFi and MetaFi services will be cheap, fast and easy.


SmurfsINU Characters: Each player will create their own identity with specific characteristics, skills and attributes.
These chosen skills will allow you to browse the SmurfsINU in-game world to complete different daily tasks for fun&rewards!



Our project was launched on Aug-07-2022. The total supply is 1,000,000,000,000,000 SMURF tokens.
SmurfsINU has been specially designed at every stage to be the safest and most loved project. As a result of in-team meetings and social research, it was decided that the tax fee would be 0%. Since the tax fee is 0%, large wallets are not reserved under the name of marketing, team, partnership. Only a 2.5% wallet is reserved for SmurfsINU to be listed on major exchanges. 
With the decision of our finance team, SMURF token will be sold with BUSD parity and liquidity locked along a year.
Since we agreed with an exchange before the launch, you will probably see while you are reviewing the project, 3% supply is reserved for Kucoin and the listing pool has been created in Kucoin. The remaining 97% supply is added to the liquidity. 
The SmurfsINU project will be financed by NFT sales, stakes and sponsorships in the SmurfsVerse universe. Our finance team secured special sponsorship deals specifically for the FIFA World Cup Qatar 2022. One of our biggest goals is to be the mascot of the tournament and to sign a partnership with a big world star.
We can say tokenomics: %97 Supply Add to LP + %3 supply reserved for a major exchange = %100 SMURF




TeamMembers:
Creator OF SmurfsINU Moto MotohiroMatsuyama: Moto, who has been actively working as Talent Acquisition @ Amazon, took active roles in projects such as AxieInfinity and Pokemon Trading Card Game.
He has been playing an active role in the crypto world, especially in the GameFi field for a long time.
He regularly attends audio conferences on Twitter Space. Moto, who also shared candidly with MayeMusk, increased his popularity. Now he created SmurfsINU with all his talents.

Twitter: https://twitter.com/MotoMatsuyama
TG: https://t.me/MotoMatsuyama


Technology and Finance Director - NiallBuckley: Niall works as an advertising director at Mothership Strategies.He is known as Pythagoras in the crypto universe.
He has played an active role in projects such as SAFEMOON, EverRise, FEG on the BinanceSmartChain network.
He has close relationships with global gaming companies and stock markets. He said in his last interview that he will use all his experience and energy to maximize SmurfsINU.


Twitter: https://twitter.com/NiallBuckley19
TG: https://t.me/NiallBuckley19



Community and media consultant - HajimeTossa: Hajime Tossa has been in the crypto market for a long time.
He especially played an active role in making STEPN a big hit in the Asian market. He influenced large masses with his publications on social platforms.
In addition, he has been accepted to the Binance training team with his regular conferences around the world, and he continues this duty actively. He joined the team at Moto’s special request.
This is one of the biggest deals ever made for SmurfsINU to reach SHIBA levels.

Twitter: https://twitter.com/OthersideOwner
TG: https://t.me/BabyDogeWhalehere

Token creation link  : https://bscscan.com/tx/0x2326ff94acd993ae536d3e0a6cf0b7bf96c8956806193e3a635abdb6628bba23
Dextools Chart: https://www.dextools.io/app/bnb/pair-explorer/0xe78ca432cee906a9329cbe56c72b8190de6d3ba3
Liquidity Lock Link: https://www.pinksale.finance/pinklock/record/1024977?chain=BSC
Audit: https://github.com/Block-Audit-Report/SmurfsINU

**Comment by SmurfsINUDeployer** [comment]
Major listings of SmurfsINU: 
https://www.coingecko.com/en/smurfsinu
https://www.binance.com/en/price/smurfsinu
https://crypto.com/price/smurfsinu

**Comment by SmurfsINUDeployer** [comment]
For the purpose of developing the same logo, but how to do it, we are developing another structure that can be improved. Is it okay if I connect like this?
Logo Link: https://imgur.com/p7dFnvb

**Comment by SmurfsINUDeployer** [comment]
Could you please search for "TrustWallet" on Twitter?
SmurfsINU, KevinDeBruyme and TrustWallet top trending in this search
https://imgur.com/OQfh8Uv
A small gift from the SmurfsINU family 💯

**Comment by SmurfsINUDeployer** [comment]
Welcome, we have been waiting for news from you for hours. (I didn't mean it as a complaint, I just got excited) Please consider our logo change request. While you were away, we shared all the information completely. Respects

**Comment by Cryptocool1** [comment]
What do you mean by change the logo? Logo that was submitted is wrong?

**Comment by SmurfsINUDeployer** [comment]
If it will not be difficult for you, the background is black, so we request it to be changed in this way. Whatever is easy for you


Logo Link: https://imgur.com/p7dFnvb

**Comment by Cryptocool1** [comment]
The background of your logo is not black

**Comment by Cryptocool1** [comment]
Background of the logo should be transparent

**Comment by SmurfsINUDeployer** [comment]
Ok then I'm sorry. I'm stealing your time. Please don't look at me, unfortunately I'm a newbie on this platform.

**Pull request merged**
