### PR TITLE
Add ATA Token (BEP20)

### PR DESCRIPTION
**Pull request by brandpad-finance**
Adding info for BEP20 token 'ATA Token'.

PR created by <a href="https://assets.trustwallet.com">TW Assets Management</a>

### CODE REVIEW

**Comment by Cryptocool1** [comment]
Hello, we need to make sure that you’re the owner of this token.
-can you verify the token ownership?
-can you record yourself ( telling who you is)

**Comment by atatoken** [comment]
> Hello, we need to make sure that you’re the owner of this token.
> -can you verify the token ownership?
> -can you record yourself ( telling who you is)

Hello @Cryptocool1 , 
1. I am not able to sign any message If you are asking verifying through bscscan. We are 
waiting for their email (check attached file) - Screenshot 2021-06-09 at 20 19 19

2. I am dev of ATA Token project located at Estonia. 

Is there any way to verify the token ownership? Example: Transfer small amount of any token from contract owner's account?

**Comment by atatoken** [comment]
Hi @Cryptocool1 any news about our project?

**Comment by Cryptocool1** [comment]
> Hi @Cryptocool1 any news about our project?

we need to make sure that you’re the owner of this token.
-can you verify the token ownership?
-can you record yourself ( telling who you is)

**Comment by atatoken** [comment]
> can you verify the token ownership?

how can I do that?

**Comment by Cryptocool1** [comment]
> > can you verify the token ownership?
> 
> how can I do that?

can you record yourself ( telling who you is)

**Comment by Cryptocool1** [comment]
> > can you verify the token ownership?
> 
> how can I do that?

when you'll be ready you can create new PR and mention this one.
you don't need to pay one more time.

**Pull request closed without merging**
