### PR TITLE
Add PVC META (BEP20)

### PR DESCRIPTION
**Pull request by pvcmetaofficial**
Adding info for BEP20 token 'PVC META'.

PR created by <a href="https://assets.trustwallet.com">TW Assets Management</a>

### CODE REVIEW

**Comment by pvcmetaofficial** [comment]
Hello @natedaiger @hexorx @rfunduk @corymsmith 

pease check this pool https://github.com/trustwallet/assets/pull/25767

We already payment 500 TWT as Fee and provide all details

**Comment by pvcmetaofficial** [comment]
@Cryptocool1 please reply sir

**Comment by pvcmetaofficial** [comment]
https://github.com/TechRate/Smart-Contract-Audits/blob/main/July_2023/PVC%20META.pdf

please check our audit and approve the logo request

**Comment by pvcmetaofficial** [comment]
please reply sir

**Comment by pvcmetaofficial** [comment]
hello sir please reply

**Comment by pvcmetaofficial** [comment]
we already pay for logo pease check this pool https://github.com/trustwallet/assets/pull/25767

We already payment 500 TWT as Fee and provide all details

**Comment by Cryptocool1** [comment]
Hello, how did you get more than 140k holders ?

**Comment by pvcmetaofficial** [comment]
All Holders are Organic Holders, PVC Meta Trading on Pancakeswap with 100K+ USD Volume Per Day, PVC Meta Running From More then 1 Year

**Comment by pvcmetaofficial** [comment]
Please Check it on https://coinmarketcap.com/currencies/pvc-meta/ and add logo and info 

Please

**Comment by pvcmetaofficial** [comment]
please reply sir

**Comment by Cryptocool1** [comment]
We are reviewing you project. Please be patient and wait.

**Comment by pvcmetaofficial** [comment]
sir please reply

**Comment by pvcmetaofficial** [comment]
sir please reply

**Comment by pvcmetaofficial** [comment]
> We are reviewing you project. Please be patient and wait.

@Cryptocool1 i am waiting for your reply

**Comment by pvcmetaofficial** [comment]
??????????

**Comment by pvcmetaofficial** [comment]
please reply sir

**Comment by pvcmetaofficial** [comment]
hello @Cryptocool1 please reply

**Comment by pvcmetaofficial** [comment]
hello @Cryptocool1 @natedaiger please add logo and info

**Review by Colins1516 — COMMENTED** [review]
Pls approve

**Comment by pvcmetaofficial** [comment]
Hello hello @Cryptocool1 please reply

pease check this pool https://github.com/trustwallet/assets/pull/25799

We already payment 500 TWT as Fee and provide all details

**Pull request merged**
