### PR TITLE
Add TWT logo and info

### PR DESCRIPTION
**Pull request by legit-hc**
Added logo and info for HyperCoin in TrustWallet

### CODE REVIEW

**Comment by legit-hc** [comment]
Hi. Do I need to change the checksum format to uppercase? Also, does the token need 2500 holders in order to be listed? If yes then do I need to make another PR when all these requirements are met? I would rather want to make the payment when we know that we are approved for listing.

**Comment by Cryptocool1** [comment]
> Hi. Do I need to change the checksum format to uppercase? Also, does the token need 2500 holders in order to be listed? If yes then do I need to make another PR when all these requirements are met? I would rather want to make the payment when we know that we are approved for listing.

Yes, please. Make make another PR when all these requirements are met

**Comment by Cryptocool1** [comment]
You may use our Assets app (in beta); close this PR; go to https://assets.trustwallet.com, log on with Github, enter contract ID, logo and some additional info, and it will create a PR for you. See https://community.trustwallet.com/t/how-to-submit-a-token-logo-using-assets-app/82957\

**Comment by Cryptocool1** [comment]
As per our policy, brand new tokens are not included, there is a minimum requirement of 2500 holder addresses and 5000 transactions, in order to filter out scam tokens.
See the criteria at (mentioned in the first message by the bot): https://community.trustwallet.com/t/how-to-submit-a-token-logo/3863).
Closing PR for now. Please come back to us when all criteria are met.

**Pull request closed without merging**
