### PR TITLE
Add logo and info Metamate

### PR DESCRIPTION
**Pull request by Chester-Ngo**
Add logo and info Metamate

### CODE REVIEW

**Comment by Chester-Ngo** [comment]
@cryptomanz @Cryptocool1 I already paid fee I got over 10000 holders now, pls check it
https://github.com/trustwallet/assets/pull/19320

**Comment by cryptomanz** [comment]
• What is the purpose of this token? How will it benefit Trust Wallet users?
 • How is the token being distributed? Are you conducting an airdrop?
 • Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?
 • Is the token listed on a centralized/decentralized exchange?
 • Is a Smart Contract audit completed? Where can we find this information?

**Comment by Chester-Ngo** [comment]
• What is the purpose of this token? How will it benefit Trust Wallet users?
$MTM is the functional multi-utility token which has multiple utilities inside the MetaMate ecosystem. $MTM may be used as the medium of exchange between participants on MetaMate in a decentralised manner. The goal of introducing $MTM is to provide a convenient and secure mode of payment and settlement between participants who interact within the ecosystem on MetaMate without any intermediaries such as centralised third party entity/institution/credit.

• How is the token being distributed? Are you conducting an airdrop?
We held ido on 
- Brandpad & Babylons on April 7
- Gami on April 11
- Gamezone &MetaVpad on April 12

• Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?
yes

• Is the token listed on a centralized/decentralized exchange?
Our token was listed on MXC and pancakeswap

• Is a Smart Contract audit completed? Where can we find this information?
https://solidity.finance/audits/MetaMate/

@cryptomanz

**Comment by cryptomanz** [comment]
Please follow the rules for adding token, your logo should be a full screen

**Comment by Chester-Ngo** [comment]
> Please follow the rules for adding token, your logo should be a full screen

Updated, please check

**Pull request merged**
