### PR TITLE
Add Sakai Vault (BEP20)

### PR DESCRIPTION
**Pull request by erience**
Adding info for BEP20 token 'Sakai Vault'.

### CODE REVIEW

**Comment by erience** [comment]
CMC Link: https://coinmarketcap.com/currencies/sakai-vault/
Website Link: https://sakaivault.io/
Certik Audit Report: https://skynet.certik.com/projects/sakai-vault
BlockSAFU Audit Report: https://blocksafu.com/project-detail/0x43B35e89d15B91162Dea1C51133C4c93bdd1C4aF

**Comment by erience** [comment]
hi @Cryptocool1 can i update the logo. it's not looking proper in wallet ?

**Comment by Cryptocool1** [comment]
Unfortunately no, this PR already merged. You should create new PR and pay a fee one more time. Please see https://developer.trustwallet.com/developer/listing-new-assets/pr-fee

**Comment by Cryptocool1** [comment]
317CA5EE-5DC6-439D-BB9A-C87E2EDFA494
Looks good

**Comment by erience** [comment]
Can you make some exception? There's a minor change in logo only. So, It looks nice.
The edges in existing design doesn't look nice.
Need like this: https://drive.google.com/file/d/16Ug03z5-3-us6beJ0O8WuDotUvGrFbnQ/view

**Comment by Cryptocool1** [comment]
There is no way to merge a PR without the fee.
https://developer.trustwallet.com/developer/listing-new-assets/pr-fee

**Pull request merged**
