### PR TITLE
Add logos of PUSD and PEGS token!

### PR DESCRIPTION
**Pull request by pegscash**
Add logos of PUSD and PEGS token.Website: https://www.pegs.cash.

### CODE REVIEW

**Comment by pegscash** [comment]
> Hi! In order to compensate for the efforts of processing PRs, we kindly ask for a contribution.
> Before paying the fee, make sure new tokens fulfill the [acceptance criteria](https://community.trustwallet.com/t/how-to-submit-a-token-logo/3863) (there is no fee refund in case of rejection).
> See also the [PR Fee FAQ](https://developer.trustwallet.com/add_new_asset/pr-fee).
> 
> Please pay **1000 TWT** with the memo **5320** to the address `bnb1tqq9llyr3dyjd559dha6z5r5etk3qfwk07m098`.
> Alternatively, 6 BNB is also accepted (same memo & address).
> 
> **QR** code: [Trust](https://api.qrserver.com/v1/create-qr-code/?size=200x200&data=https%3A%2F%2Flink.trustwallet.com%2Fsend%3Fcoin%3D714%26address%3Dbnb1tqq9llyr3dyjd559dha6z5r5etk3qfwk07m098%26amount%3D1000%26memo%3D5320) | [other wallet](https://api.qrserver.com/v1/create-qr-code/?size=200x200&data=bnb1tqq9llyr3dyjd559dha6z5r5etk3qfwk07m098%26amount%3D1000%26memo%3D5320)
> 
> _Notes_:
> 
> * [Trust Wallet Tokens (TWT)](https://community.trustwallet.com/t/trust-wallet-token-twt/4187) can be obtained through our [Referral Program](https://community.trustwallet.com/t/invite-a-friend-earn-trust-wallet-token-twt/4125) or [from DEXs/exchanges](https://community.trustwallet.com/t/where-to-get-trust-wallet-tokens/76641).
> * New tokens without significant usage are rejected, see criteria mentioned above.
> * One PR should be for a single project; PR's with more than 10 logos will be rejected.
> * Payment evaluation happens automatically, but with a few minutes delay.  When payment is detected, an Accept Review is automatically placed on the PR, which is a condition for merge.
> * Evaluating the PR is done manually, and it is merged only if all conditions are satisfied.
> * TWT-BEP2 is supported (Binance Chain), TWT-BEP20 version on Smart Chain is not.

Already paid in last pull request!Please check it.Thank you

**Comment by catenocrypt** [comment]
1. Previous PR is #5316 , but that is not paid either.
2. This PR contains two ERC20 tokens, both with low circulation (<200 holders).  Is this correct?  This is below our limit of min. 2500 holders.

**Comment by catenocrypt** [comment]
As I mentioned in previous comment, the circulation of these tokens is well below our limit of 2500 holders, they have less than 200.

**Comment by catenocrypt** [comment]
As per our policy, brand new tokens are not included, there is a minimum requirement of 2500 holder addresses and 5000 transactions, in order to filter out scam tokens.
See the criteria at (mentioned in the first message by the bot): https://community.trustwallet.com/t/how-to-submit-a-token-logo/3863).
This token has no real usage yet (191, 191). Putting PR on hold for now. Please come back to us when all criteria are met.

https://etherscan.io/token/0x88bd6eFe33bc82860278c044eFA33364c6285032
https://etherscan.io/token/0x412e5a36BDE71AA2c38e1c0E26BAAf7F2f0Bc24a

**Comment by catenocrypt** [comment]
No action for 3 months, closing.

**Pull request closed without merging**
