### PR TITLE
Adding Impossible Finance Assets

### PR DESCRIPTION
**Pull request by calchulus**
Ready to pay TWT fee <3

### CODE REVIEW

**Comment by calchulus** [comment]
sorry please hold on one sec. i am still fixing the logos and names. We have two tokens which are each on ETH BSC and Polygon

**Comment by calchulus** [comment]
ready!

**Comment by cryptomanz** [comment]
• What is the purpose of this token? How will it benefit Trust Wallet users?
 • How is the token being distributed? Are you conducting an airdrop?
 • Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?
 • Is the token listed on a centralized/decentralized exchange?
 • Is a Smart Contract audit completed? Where can we find this information?

**Comment by cryptomanz** [comment]
For smartchain should be BEP20
Fixed.

**Comment by calchulus** [comment]
Thank you!

**Pull request merged**
