### PR TITLE
Add TIME (BEP20)

### PR DESCRIPTION
**Pull request by LeoTian888**
Adding info for BEP20 token 'TIME'.

PR created by <a href="https://assets.trustwallet.com">TW Assets Management</a>

### CODE REVIEW

**Comment by cryptomanz** [comment]
As per our policy, brand new tokens are not included, there is a minimum requirement of 10,000 holder addresses and 15,000 transactions, in order to filter out scam tokens.
See the criteria at : https://developer.trustwallet.com/assets/requirements .

**Comment by cryptomanz** [comment]
• What is the purpose of this token? How will it benefit Trust Wallet users?
 • How is the token being distributed? Are you conducting an airdrop?
 • Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?
 • Is the token listed on a centralized/decentralized exchange?
 • Is a Smart Contract audit completed? Where can we find this information?

**Comment by LeoTian888** [comment]
Thanks for your reply.
1. TIME is a token that can be earned or used in a developed game for entertainment. Game URL: https://wb.metatimegame.com
2. There's no airdrop for the TIME token. You can buy the token from the game.
3. There's no ICO or presale.
4. Yes, you can find the token on ave.ai, pancake swap, and transit swap.
5. The token isn't audited. But you can check the source code via https://bscscan.com/address/0x26619FA1d4c957C58096bBbeCa6588dCFB12E109#code

**Comment by cryptomanz** [comment]
Awaiting for smart contract audit. On hold for now.

**Comment by cryptomanz** [comment]
Awaiting for smart contract audit. On hold for now.

**Comment by cryptomanz** [comment]
Your description should be in English. Please change.

**Comment by LeoTian888** [comment]
Hi, a new PR has been posted, please see https://github.com/trustwallet/assets/pull/20027

**Comment by LeoTian888** [comment]
> Please come back to us when all criteria are met. When creating a new PR make sure to mention this PR, so that we can see that fee has been paid already here.

Hi, https://github.com/trustwallet/assets/pull/20027 this PR has been closed again, please reopen it. Thanks

**Pull request closed without merging**
