### PR TITLE
Add KONG logo and info

### PR DESCRIPTION
**Pull request by playhubdev**
Add assets for BitKong Coin (KONG) to Smart Chain, Polygon and Ethereum

### CODE REVIEW

**Comment by Cryptocool1** [comment]
As per our policy, there is a minimum requirement of 10,000 holder addresses and 15,000 transactions, in order to filter out scam tokens.
See the criteria at : https://developer.trustwallet.com/listing-new-assets/requirements .

**Comment by Cryptocool1** [comment]
Please come back to us once all criteria are met

**Comment by playhubdev** [comment]
@Cryptocool1  We saw criteria for scam token, but our project is live since 2016, and this token is differently is not a scam. Can you please reconsider and check the project before rejecting.

**Comment by playhubdev** [comment]
@Cryptocool1 Hey! Before distributing the token, we strive to ensure that our community members enjoy the best possible user experience everywhere. Numerous projects are using this repo for a logo. Please check the bitcoin talk thread: https://bitcointalk.org/index.php?topic=1214505.0 if you think project is a scam.

**Pull request closed without merging**
