### PR TITLE
STACY Token Assets

### PR DESCRIPTION
**Pull request by wolfcryptogroup**
Hi, 

Submitting on behalf of Chads.vc team. This is the Chadswap (https://chadswap.finance) governance token. 

We are aware of the 500 token holder requirement, we expect to reach that tomorrow when Uniswap trading opens. (A bunch of fake clones have launched and we need a picture to identify the real STACY)

Our CHADS token has about 2000 holders.

Thank you

### CODE REVIEW

**Comment by Iamdeadlyz** [comment]
Since you are already aware, I'll place this on hold. Please let us know once you have reached the requirements.

**Comment by wolfcryptogroup** [comment]
> Since you are already aware, I'll place this on hold. Please let us know once you have reached the requirements.

We now have over 500 holders

image

**Comment by Iamdeadlyz** [comment]
> > Since you are already aware, I'll place this on hold. Please let us know once you have reached the requirements.
> 
> We now have over 500 holders
> 
> image

Cool. A "little" bit more and you can achieve it. 
For your reference: https://community.trustwallet.com/t/how-to-submit-a-token-logo/3863#how-to-get-approved

**Comment by Iamdeadlyz** [comment]
Let us know once you have reached the requirements so we can re-open this PR.

**Pull request closed without merging**
