### PR TITLE
AQUA LOGO CHANGE

### PR DESCRIPTION
**Pull request by ash-greninja-poke**
This PR is being closed due to inactivity. If you wish to continue, please have us reopen the PR before sending your payment, or just create a new one.
Do NOT send payments for closed PR, as the fee may by lost!
  (48 vs. 48 hrs)

### CODE REVIEW

**Comment by ash-greninja-poke** [comment]
Our token is listed in trust wallet we want to change the icon so that it looks professional.

**Comment by ash-greninja-poke** [comment]
Fee is already paid.

**Comment by Cryptocool1** [comment]
> Fee is already paid.

Hello!
You need to pay for updating as well

**Comment by ash-greninja-poke** [comment]
How much we need to pay for it?

**Comment by ash-greninja-poke** [comment]
> > Fee is already paid.
> 
> Hello!
> You need to pay for updating as well



> How much we need to pay for it?

@Cryptocool1

**Comment by Cryptocool1** [comment]
Please pay 2000 TWT with the memo 2559 to the address bnb1tqq9llyr3dyjd559dha6z5r5etk3qfwk07m098.
Alternatively, 5 BNB is also accepted (same memo & address).

**Comment by ash-greninja-poke** [comment]
“We just want the logo to look great. We just payed $1000, why do we need to pay same amount again to just swap in the correct image?”

**Pull request closed without merging**
