### PR TITLE
Add RocketBUSD Logo and Info

### PR DESCRIPTION
**Pull request by PeterROCKETBUSD**
Adding RocketBUSD Logo and Information to provide more visual appeal and insight to our holders.
(We have the price already showing, really just need the logo if possible, please!)

### CODE REVIEW

**Comment by PeterROCKETBUSD** [comment]
Hi Guys! Sorry - new to GitHub, trying to do this for our team. Will update links and provide more info shortly! Thanks for bearing with me.

**Comment by PeterROCKETBUSD** [comment]
What other links would you guys need? I can provide them all! 😃 

Twitter: http://twitter.com/RocketBUSD
Discord: http://discord.gg/RocketBUSD

Tons of Press Release links available upon request.

What is our token?

RocketBUSD is a software services & blockchain technology company.
The native token, RocketBUSD, functions as a utility token in tools, games, and community-based proposal voting. Additionally, token holders can unlock premium features & rewards within and beyond the RocketBUSD ecosystem. Holders are automatically rewarded with reflections in BUSD based on volume and holdings.
RocketBUSD exists to develop and manage an ecosystem of innovative, intuitive solutions for an ever-growing DeFi community. RocketBUSD builds practical, well-designed tools and services to help radically simplify complexity, improve security, and accelerate performance through actionable, personalized insight. In addition, with the development of games and an NFT marketplace, RocketBUSD enters the steadily expanding creative landscape within DeFi.
The world of DeFi is rapidly growing in innovation, complexity, and population. At RocketBUSD, we envision and are committed to realizing a community-powered future in DeFi where challenges become opportunities and where trust becomes the default.

**Comment by PeterROCKETBUSD** [comment]
links.url fields seem to be correct, could someone please review?

**Comment by cryptomanz** [comment]
As per our policy, brand new tokens are not included, there is a minimum requirement of 25,000 holder addresses and 50,000 transactions, in order to filter out scam tokens.
See the criteria at : https://developer.trustwallet.com/assets/requirements .

**Pull request closed without merging**
