### PR TITLE
Add SmartMEME (BEP20)

### PR DESCRIPTION
**Pull request by DexterTheBrain**
Adding info for BEP20 token 'SmartMEME'.

PR created by <a href="https://assets.trustwallet.com">TW Assets Management</a>

### CODE REVIEW

**Comment by DexterTheBrain** [comment]
• What is the purpose of this token? How will it benefit Trust Wallet users?
SmartMEME is a meme token with an innovative smart buyback mechanism. 
• How is the token being distributed? Are you conducting an airdrop?
We didn't conduct any airdrop. Its presold on PinkSale.
• Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?
We had a fair launch presale on PinkSale with 598 BNB raise.
https://www.pinksale.finance/launchpad/0x2408C6dB45589f1619ad463dAd656C361669eC4a?chain=BSC
• Is the token listed on a centralized/decentralized exchange?
Its not yet listed but we currently looking one.
• Is a Smart Contract audit completed? Where can we find this information?
Its audited by Coinsult.
https://coinsult.net/projects/smartmeme/

**Comment by Cryptocool1** [comment]
As per our policy, there is a minimum requirement of 10,000 holder addresses and 15,000 transactions, in order to filter out scam tokens.
See the criteria at : https://developer.trustwallet.com/listing-new-assets/requirements .

**Comment by Cryptocool1** [comment]
Feel free to come back to us once all criteria are met

**Comment by DexterTheBrain** [comment]
Please check again.
Its also have been listed on CoinMarketCap.
https://coinmarketcap.com/currencies/smartmeme/

Regards.

**Comment by Cryptocool1** [comment]
We do not accept brand new tokens ( your token is couple days old) 
Couple days ago you had 1-2k holders, I guess you airdropped it to 10k (that is forbidden for trust wallet listing) 
I recommend you to grow organically and come back to us in 1 month.

**Pull request closed without merging**
