### PR TITLE
add ppay logo and info

### PR DESCRIPTION
**Pull request by PioneerPay**

### CODE REVIEW

**Comment by Cryptocool1** [comment]
Please create new PR, follow doc https://developer.trustwallet.com/listing-new-assets/requirements
You may want to try our Assets app in beta; go to https://assets.trustwallet.com, log on with Github, enter contract ID, logo and some additional info, and it will create a PR for you.
See https://developer.trustwallet.com/listing-new-assets/repository_details

**Review by scotts2080 — COMMENTED** [review]
scotts2080-patch-1

**Comment by scotts2080** [comment]
scotts2080-patch-1

**Comment by scotts2080** [comment]
3d8057ac749371dc9ff3f827ffa4d5b227b2282e

**Review by scotts2080 — COMMENTED** [review]
https://github.com/NebuTech/NBMiner/pull/261#pullrequestreview-1346808519

**Pull request closed without merging**
