### PR TITLE
Add Minati Token (BEP20)

### PR DESCRIPTION
**Pull request by shyam121212**
Adding info for BEP20 token 'Minati Token'.

PR created by <a href="https://assets.trustwallet.com">TW Assets Management</a>

### CODE REVIEW

**Comment by shyam121212** [comment]
payment is already done please merged this request https://github.com/trustwallet/assets/pull/25285 because all conditions is fulfilled by coin owner

**Comment by shyam121212** [comment]
please reply sir

**Comment by shyam121212** [comment]
??????

**Comment by shyam121212** [comment]
why you are not replying just tell me that

**Comment by shyam121212** [comment]
??????????????????

**Comment by shyam121212** [comment]
#25285 kindly approve this request of add logo because all conditions is fullfilled

**Comment by Cryptocool1** [comment]
Hello, as I see you did new airdrop. Your airdrop is ongoing for now. As we told you before, we are not accept airdropped tokens, but you did an airdrop again. Please come back to us once you have an activity and organic holders.

**Comment by shyam121212** [comment]
> Hello, as I see you did new airdrop. Your airdrop is ongoing for now. As we told you before, we are not accept airdropped tokens, but you did an airdrop again. Please come back to us once you have an activity and organic holders.

no airdrop sent please check carefully

**Comment by Cryptocool1** [comment]
You should submit your PR once airdrop ends

**Comment by shyam121212** [comment]
> You should submit your PR once airdrop ends

please check send and receive address all are different 

so please kindly merge this request because all are genuine transactions

**Comment by shyam121212** [comment]
please reply

**Comment by Cryptocool1** [comment]
Please see my message above.

**Comment by shyam121212** [comment]
our social media was hacked so we was not able to post pr on our social media

**Pull request closed without merging**
