### PR TITLE
Add COPE

### PR DESCRIPTION
**Pull request by ghost**
Hi,
Greetings from COPE,

More details on COPE can be found here:

Website: https://www.unlimitedcope.com/
Whitepaper: https://www.unlimitedcope.com/whitepaper/
Discord : https://discord.gg/cope
Twitter: https://twitter.com/unlimitedcope

Listing Details:
FTX: https://ftx.com/trade/COPE/USD
serum : https://dex.projectserum.com/#/market/7MpMwArporUHEGW7quUpkPZp5L5cHPs9eKUfKCdaPHq2
CoinMarketCap: https://coinmarketcap.com/currencies/cope/
CoinGecko: https://www.coingecko.com/en/coins/cope

Thanks

### CODE REVIEW

**Comment by NaderOuerdiane** [comment]
I used wrong image dimensions :)) please use this one.
logo

**Comment by catenocrypt** [comment]
> No token files found.

Ignore this error message, token check logic did not work for solana tokens (fixed now)

**Comment by NaderOuerdiane** [comment]
> Minor correction needed: please change website to 'https://www.unlimitedcope.com'.

done :))

**Comment by NaderOuerdiane** [comment]
@catenocrypt Is there anything else I have to add ? :))

**Pull request merged**
