### PR TITLE
Add MSS logo and info

### PR DESCRIPTION
**Pull request by monsterslayerfinance**

### CODE REVIEW

**Comment by catenocrypt** [comment]
Correction needed: Please reduce/compress logo to under 100kbytes, recommended pixel size is 256x256 (max 512x512).

```
XXX 'Check that logos are not too large':  1 errors
   XXX   'Logo too large: /home/runner/work/assets/assets/blockchains/smartchain/assets/0xAcABD3f9b8F76fFd2724604185Fa5AFA5dF25aC6/logo.png'
```

**Comment by monsterslayerfinance** [comment]
logo
Here is the new image I want to update, with size <100kbytes, please help me change the logo file.

**Comment by monsterslayerfinance** [comment]
Fixed, please review, thank!

**Comment by catenocrypt** [comment]
Logo is still  too large, 676x676 px, please scale down to max 512x512 (recommended size is 256x256; this logo will be displayed in small size).

**Comment by monsterslayerfinance** [comment]
My bad, Fixed, please check, thank!

**Pull request merged**
