### PR TITLE
Add BITTO (BEP20)

### PR DESCRIPTION
**Pull request by abanshinoburu**

### CODE REVIEW

**Comment by catenocrypt** [comment]
Correction needed: decimals should be 18, not 21, please change.

image

**Comment by abanshinoburu** [comment]
@catenocrypt Decimals updated, please check.

**Comment by Iamdeadlyz** [comment]
//ERC20 token version is already in the repo. 
https://github.com/trustwallet/assets/tree/master/blockchains/ethereum/assets/0x55a290f08Bb4CAe8DcF1Ea5635A3FCfd4Da60456

**Comment by abanshinoburu** [comment]
Hi,

Is ERC20 Repo and BEP20 suppose to be in same repo?

**Pull request merged**
