### PR TITLE
Add QUAMNETWORK.COM (BEP20)

### PR DESCRIPTION
**Pull request by Quam-Network**
Adding info for BEP20 token 'QUAMNETWORK.COM'.

PR created by <a href="https://assets.trustwallet.com">TW Assets Management</a>

### CODE REVIEW

**Comment by Quam-Network** [comment]
Hi Guys,
Please let me know the points I am lacking in fulfilling the requirements, as far as payment is concerned, how to make it and let you know that I have made it?

Thanks

**Comment by Quam-Network** [comment]
149D4746FCAE7590E044D32ED76F0C9AE513C52D83AD74D4527CA75AFC4828BC

**Comment by catenocrypt** [comment]
Correction needed: Please make description human readable, a few sentence summary of the project (max. 500 chars).

**Comment by Quam-Network** [comment]
Hey Team,

Here is a brief Explanation of our project.

QUAM Network is an Advanced Multichain Defi Protocol which provides 
various Defi-Investment methods with the best trading experience over 
Binance Smart Chain. The platform's network design and infrastructure 
are Multi chain compatible and blockchain agnostic.

It advocates volumes about how instant deposits and withdrawals with the 
lowest possible network fees by pooling multiple users' liquidity could 
redefine the DeFi landscape, specifically for users.

Thanks & Regards,

QUAM NETWORK

On 2021-04-14 17:56, Adam R wrote:

> Correction needed: Please make description human readable, a few 
> sentence summary of the project (max. 500 chars).
> 
> --
> You are receiving this because you modified the open/close state.
> Reply to this email directly, view it on GitHub [1], or unsubscribe 
> [2].


Links:
------
[1] 
https://github.com/trustwallet/assets/pull/6428#issuecomment-819478459
[2]

**Comment by Quam-Network** [comment]
Hi Team, 
The community still do not see our logo on Trust Wallet, Please suggest us to do the needful.
We have already made the contribution long back
Thanks

**Comment by catenocrypt** [comment]
Please change this description field to a short summary of the project, max 500 characters, instead of this link collection:

image

**Comment by Quam-Network** [comment]
Please get it done mate, I have raised several pull requests for the same #7020 also is my request only I have made the payment two times, Please get it done on priority.
Thanks

[info.zip](https://github.com/trustwallet/assets/files/6392904/info.zip)

**Comment by Quam-Network** [comment]
[0x1AdE17B4B38B472B5259BbC938618226dF7b5Ca8.zip](https://github.com/trustwallet/assets/files/6398661/0x1AdE17B4B38B472B5259BbC938618226dF7b5Ca8.zip)

**Comment by Cryptocool1** [comment]
> 0x1AdE17B4B38B472B5259BbC938618226dF7b5Ca8.zip

Hello,
Please change this description field to a short summary of the project, max 500 characters, in order not to close this PR tomorrow

**Comment by Cryptocool1** [comment]
Description field is too long, please compact it (833 chars, max is 500). Closing PR for now. Please come back to us when all criteria are met.

**Comment by Quam-Network** [comment]
Don't Know why you closed this PR, because as far as I am checking the description length that is coming to be just 159.
Attaching snapshot for your reference.

DescriptionLen

**Comment by Cryptocool1** [comment]
> Don't Know why you closed this PR, because as far as I am checking the description length that is coming to be just 159.
> Attaching snapshot for your reference.
> 
> DescriptionLen

Hello,
Can you please create new PR?
You don’t need to pay one more time

**Pull request closed without merging**
