### PR TITLE
Add CHZ006 logo and info

### PR DESCRIPTION
**Pull request by AnilMehmet**
This request includes our logo and some additional information about the CHZ006 token.

### CODE REVIEW

**Comment by AnilMehmet** [comment]
Dear maintainer, 

Pull request 76b759f is the correct one. 
Thank you

**Comment by Charizardtoken-dev** [comment]
Dear maintainer,

How is the progress going? Please let us know. Thanks

**Comment by catenocrypt** [comment]
Correction needed: Please keep only the first 2 files (from the correct, checksum-format folder), remove the other 2 files.

image

**Comment by AnilMehmet** [comment]
> Correction needed: Please keep only the first 2 files (from the correct, checksum-format folder), remove the other 2 files.
> 
> image

Could you please delete it, i tried but it failed.

**Pull request merged**
