### PR TITLE
AllWin Token logo request

### PR DESCRIPTION
**Pull request by Andreasvdbs**
Requesting the AllWin logo to be added to the Trustwallet repository.

### CODE REVIEW

**Comment by catenocrypt** [comment]
As per our policy, brand new tokens are not included, there is a minimum requirement of 2500 holder addresses and 5000 transactions, in order to filter out scam tokens.
See the criteria at (mentioned in the first message by the bot): https://community.trustwallet.com/t/how-to-submit-a-token-logo/3863#how-to-get-approved
This token has below-limit usage yet (555). Putting PR on hold. Please come back to us when all criteria are met.

https://etherscan.io/token/0xc6358C02A4BaFcbcd85360ae046e6bEe556429c1

**Comment by Andreasvdbs** [comment]
Dear

I issued a logo request mid-October and got a message that the requirements (500/1000) are not met and that I should come back when every criterium was met. 
Now we met those criteria and it seems the requirements have been raised. Is there any other way to provide additional info to ensure the legitimacy of the token? 

Kind regards,
Andreas

**Comment by catenocrypt** [comment]
Payment considered from #4388 .

**Comment by catenocrypt** [comment]
Previously requested in #4388 .

**Comment by Andreasvdbs** [comment]
Thanks for the quick action, Adam

**Pull request merged**
