### PR TITLE
MinerBlox token (MBLOX) logo.png and info.json

### PR DESCRIPTION
**Pull request by minerbloxoffi**
MinerBlox token (MBLOX) logo.png and info.json for add our BEP20 token to trustwallet

### CODE REVIEW

**Comment by cryptomanz** [comment]
• What is the purpose of this token? How will it benefit Trust Wallet users?
 • How is the token being distributed? Are you conducting an airdrop?
 • Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?
 • Is the token listed on a centralized/decentralized exchange?

**Comment by minerbloxoffi** [comment]
The purpose of the token is to be used in our dapp, https://play.minerblox.com
   
   
    
   
   
    MinerBlox is a P2E based on BSC that allow players to create their virtual mining rig buying GPUs in NFT format. MBLOX is the token used for buy GPU cards and is also the reward for MinerBlox players
   
   
    
   
   
    We have also request to add our dapp to Trust Wallet
   
   
    
   
   
    We have sold part of the tokens in a private sale and a part in a public sale in January 2022. On 1st of February we have launched our game.
   
   
    
   
   
    At the moment, we are conducting a little Airdrop campaign.
   
   
    
   
   
    The token is listed on pancakeswap https://pancakeswap.finance/swap?outputCurrency=0xAD0A3901eFf23b9143985bCB42F0171a112A2fD3
   
   
    
   
   
    We are also in Coinmarketcap, CoinGecko and on BSCSCAN.
   
   
    
   
   
    Thanks 
   
  
  
   
    Il 26/02/2022 14:08 Nazar ***@***.***> ha scritto:
   
   
    
   
   
    
   
   
   • What is the purpose of this token? How will it benefit Trust Wallet users?• How is the token being distributed? Are you conducting an airdrop?• Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?• Is the token listed on a centralized/decentralized exchange?

**Comment by Cryptocool1** [comment]
we accept only reputable security audit groups.  such as certik, techrate, dessert finance, hacken

**Comment by Cryptocool1** [comment]
Please come back to us when all criteria are met
make sure to mention this PR so the fee can be reused

**Comment by minerbloxoffi** [comment]
Hello,
  
  
   
  
  
   Our project is growing and we have nearly 12,000 owners ( https://bscscan.com/token/0xAD0A3901eFf23b9143985bCB42F0171a112A2fD3) and we have audited with dessert finance as you requested. This is the audit link: https://dessertswap.finance/audits/MinerBlox-BSC-Audit-16126178.pdf
  
  
   
  
  
   Please reconsider our request (PR #18519)  to add the token on trustwallet and reuse the fee already paid
  
  
   
  
  
   Thanks,
  
  
   Alessio
  
  
   
    Il 27/02/2022 00:30 CryptoA ***@***.***> ha scritto:
   
   
    
   
   
    
   
   
   Please come back to us when all criteria are metmake sure to mention this PR so the fee can be reused

**Pull request closed without merging**
