### PR TITLE
Add NOOT (BEP20)

### PR DESCRIPTION
**Pull request by tehretroboy**
Adding info for BEP20 token 'NOOT'.

PR created by <a href="https://assets.trustwallet.com">TW Assets Management</a>

### CODE REVIEW

**Comment by retrobsc** [comment]
Hello, not sure if the logo was the correct size, so double sending it here

noot-logo-256

**Comment by Cryptocool1** [comment]
• What is the purpose of this token? How will it benefit Trust Wallet users?
 • How is the token being distributed? Are you conducting an airdrop?
 • Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?
 • Is the token listed on a centralized/decentralized exchange?
 • Is a Smart Contract audit completed? Where can we find this information?

**Comment by retrobsc** [comment]
1. The purpose of our token extends beyond being just another memecoin in the current memeseason. We have incorporated reflections into the token, allowing users to track their balances and view charts over time through our dedicated reflections dashboard statistics. Additionally, we have developed a chat2earn bot on Telegram that rewards users with our token, NOOT. Users can deposit and send NOOT directly through the Telegram platform. Our team boasts two years of experience in the BNB NFTs space.

2. The token has already been distributed through a fair launch that took place approximately two weeks ago. We have also planned an airdrop for BNB NFT holders, which will account for no more than 1% of the total token supply.

3. Yes, the token was launched through a fair launch on Pinksale.

4. The token is currently listed on both a decentralized exchange (DEX), specifically Pancakeswap, and a centralized exchange (CEX) known as MEXC. Furthermore, we have additional listings in the pipeline that will be available very soon.

5. We have successfully conducted a smart contract audit, ensuring its security and reliability. The audit report can be found at the following link: https://techright.io/audit/nootcoin/. Furthermore, we have taken the additional step of renouncing the smart contract.

**Comment by retrobsc** [comment]
Hello, we are currently facing an issue with Trust Swap. It appears that Trust Swap is using 1inch swap, but the problem is that their maximum slippage is 3%. However, our tax rate is 6%. Is there any way we can resolve this? Thank you.

**Pull request merged**
