### PR TITLE
Add GCO

### PR DESCRIPTION
**Pull request by goldconioprotocol**

### CODE REVIEW

**Review by goldconioprotocol — COMMENTED** [review]
Review Changes

**Comment by goldconioprotocol** [comment]
review changes

**Comment by cryptomanz** [comment]
As per our policy, there is a minimum requirement of 10,000 holder addresses and 15,000 transactions, in order to filter out scam tokens.
See the criteria at : https://developer.trustwallet.com/assets/requirements .

**Comment by goldconioprotocol** [comment]
> As per our policy, there is a minimum requirement of 10,000 holder addresses and 15,000 transactions, in order to filter out scam tokens. See the criteria at : https://developer.trustwallet.com/assets/requirements .

Investors want the token to be listed and listing requirements need investors. Got it

**Pull request closed without merging**
