### PR TITLE
Add PM logo and info

### PR DESCRIPTION
**Pull request by Pomskey**
Please add the initial information for PM with logo and details.

### CODE REVIEW

**Review by Pomskey — COMMENTED** [review]
adjust explorer

**Review by Pomskey — COMMENTED** [review]
include socials

**Review by Pomskey — COMMENTED** [review]
remove socials

**Comment by Cryptocool1** [comment]
Correction needed:
This is a BEp20 token, correct folder is blockchains/smartchain/assets. Please correct.

**Review by Pomskey — COMMENTED** [review]
correction

**Review by Pomskey — COMMENTED** [review]
socials + Checksum

**Pull request merged**
