### PR TITLE
Adding Catecoin [CATE]

### PR DESCRIPTION
**Pull request by catecoins**
Request you to Add Catecoin

### CODE REVIEW

**Comment by Cryptocool1** [comment]
Submission looks good. awaiting fee payment.

**Comment by catecoins** [comment]
Waiting for your process. 
thanks

**Comment by catecoins** [comment]
Contract - **0x118F073796821DA3E9901061B05c0b36377B877e**

 is Moved to **0xE4FAE3Faa8300810C835970b9187c268f55D998F**

We have already reported this but in trust wallet logo is still visible in old contract, kindly fix this @Cryptocool1

**Comment by catecoins** [comment]
@Cryptocool1 @catenocrypt  @zachzwei @hexorx  request you to kindly update the old contract so that users can  avoid buying from the old contract.

Users are buying Catecoin from trust wallet, in trust wallet when they search CATECOIN then old contract is appearing in top and users are buying that old token 

kindly remove logo and display name that is added in info.json file.

thanks

**Pull request merged**
