### PR TITLE
Add Decentrawood (BEP20)

### PR DESCRIPTION
**Pull request by monish-nagre**
Adding info for BEP20 token 'Decentrawood'.

PR created by <a href="https://assets.trustwallet.com">TW Assets Management</a>

### CODE REVIEW

**Comment by Cryptocool1** [comment]
As per our policy, there is a minimum requirement of 10,000 holder addresses and 15,000 transactions
See the criteria at : https://developer.trustwallet.com/listing-new-assets/requirements .

**Comment by Cryptocool1** [comment]
Feel free to come back to us once this requirement is met

**Comment by monish-nagre** [comment]
> As per our policy, there is a minimum requirement of 10,000 holder addresses and 15,000 transactions See the criteria at : https://developer.trustwallet.com/listing-new-assets/requirements .

"As per your criteria, we already have up to 10,000 holders on the Polygon chain, so this is a wrapped version of our token on the BSC chain."

**Comment by monish-nagre** [comment]
> As per our policy, there is a minimum requirement of 10,000 holder addresses and 15,000 transactions See the criteria at : https://developer.trustwallet.com/listing-new-assets/requirements .

Subject: Request for Token Logo Addition – Criteria Met

Dear Trust Wallet Team @Cryptocool1,

We appreciate your response and the requirements outlined for listing our token’s logo. We are pleased to inform you that we have now successfully met the 15,000 transactions criterion.

Additionally, a significant portion of our user base actively uses Trust Wallet. However, due to the absence of our token logo, many potential holders face difficulty identifying and trusting the token, which has impacted our holder count. We strongly believe that once the logo is added, we will rapidly meet and exceed the 10,000 holder requirement.

We kindly request you to reconsider our submission and proceed with the logo integration. Your support in this matter will significantly enhance user experience and further strengthen engagement within the Trust Wallet ecosystem.

Looking forward to your positive response.

Best regards,
monish-nagre
[Decectrawood & DEOD]

**Pull request closed without merging**
