### PR TITLE
Mco2 added

### PR DESCRIPTION
**Pull request by renankruger**
Hi,

Help us to save amazon rainforest by adding our token on trust wallet.

More info on mco2token.moss.earth

Regards

### CODE REVIEW

**Comment by renankruger** [comment]
Can someone help me here?

**Comment by renankruger** [comment]
done

**Comment by catenocrypt** [comment]
For some reason this PR contains several extra files, next to the new token logo and info file several validator and tokenlists are updated.  Please make sure only the 2 new token files are in the PR.  Revert the other files (or create new clean PR, but mention this PR as well to avoid double fee payment).

**Comment by renankruger** [comment]
To pass on checks I did npm run checks and fix. I will revert all commits

**Comment by renankruger** [comment]
@catenocrypt new pull request #6103

**Comment by renankruger** [comment]
@catenocrypt forced update here, could you check please?

**Comment by renankruger** [comment]
@zachzwei @catenocrypt each day 3k hectares of forest is burned in Brazil, please help us stoping this with MCO2 token

**Comment by renankruger** [comment]
thanks @catenocrypt

**Pull request merged**
