### PR TITLE
Add AMAL Logo

### PR DESCRIPTION
**Pull request by CloverEc**
Add AMAL Logo

### CODE REVIEW

**Comment by zachzwei** [comment]
Unable to edit PR. Please add your token contract to whitelist.json

**Comment by catenocrypt** [comment]
@CloverEc , sorry, I have no permission to your fork/PR, so I cannot fix.  I think you have to merge master again.

**Comment by CloverEc** [comment]
> @CloverEc , sorry, I have no permission to your fork/PR, so I cannot fix. I think you have to merge master again.

how about this PR?

**Comment by catenocrypt** [comment]
@CloverEc , I can see you have just merge master again.  It should be OK now.

**Pull request merged**
