### PR TITLE
Update Logo

### PR DESCRIPTION
**Pull request by winlambo**
This PR is being closed due to inactivity. If you wish to continue, please have us reopen the PR before sending your payment, or just create a new one.
Do NOT send payments for closed PR, as the fee may by lost!
  (48 vs. 48 hrs)

### CODE REVIEW

**Comment by winlambo** [comment]
Hi, we've already paid for our initial listing, we would just like to update the logo to our new logo.

**Comment by Cryptocool1** [comment]
hello,
you need to pay for updating

**Comment by winlambo** [comment]
5 BNB to update the logo?

**Comment by winlambo** [comment]
This BNB grows on trees?

**Pull request closed without merging**
