### PR TITLE
Add LIMOCOIN SWAP (BEP20)

### PR DESCRIPTION
**Pull request by Shyamthakur33**
Adding info for BEP20 token 'LIMOCOIN SWAP'.

PR created by <a href="https://assets.trustwallet.com">TW Assets Management</a>

### CODE REVIEW

**Comment by Cryptocool1** [comment]
logo should be 256/256, please change

**Comment by Shyamthakur33** [comment]
> logo should be 256/256, please change

there is no option to edit the 
Screenshot 2021-12-24 100722
logo file, how can we do that?
thanks

**Comment by Shyamthakur33** [comment]
@Cryptocool1 you there?

**Comment by Cryptocool1** [comment]
You can send your logo here, and I will change for you

**Comment by Shyamthakur33** [comment]
> You can send your logo here, and I will change for you

logo

**Comment by Shyamthakur33** [comment]
> > You can send your logo here, and I will change for you
@Cryptocool1 
> 
> logo

**Comment by ramsty** [comment]
• What is the purpose of this token? How will it benefit Trust Wallet users?
• How is the token being distributed? Are you conducting an airdrop?
• Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?
• Is the token listed on a centralized/decentralized exchange?
• Is a Smart Contract audit completed? Where can we find this information?

**Comment by Shyamthakur33** [comment]
> • What is the purpose of this token? How will it benefit Trust Wallet users? • How is the token being distributed? Are you conducting an airdrop? • Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale? • Is the token listed on a centralized/decentralized exchange? • Is a Smart Contract audit completed? Where can we find this information?

• What is the purpose of this token?

Limocoin Swap is a token created to allow, by the principle of cryptographic assets, the evolution of market solutions. It is based on a strong community built in four years by one of the subsidiaries of the parent company SIMTREX COMMERCIAL BROKERS LLC, GIT .SA. it's a currency of exchange between African countries, staking, blockchain

 How will it benefit Trust Wallet users?

We have 250 merchants around the world, Trust Wallet users can use our currency to send money to their loved one in any country, our merchants are available to exchange the currency into fiat or local currency for the users


• How is the token being distributed?

4 years of ICO through the liyeplimal program

Are you conducting an airdrop?
Not yet

• Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?
ICO

• Is the token listed on a centralized/decentralized exchange?

Yes, we are trading on:
Latoken
LBank
xt.com
Pancakeswap

• Is a Smart Contract audit completed?
Yes

Where can we find this information?

https://www.liyeplimal.net/assets/images/uploads/LIMOCOIN_SWAP_Block_Audit_Report.pdf

**Pull request merged**
