### PR TITLE
add LTBRT logo and info

### PR DESCRIPTION
**Pull request by NauraCreator**
this is a token logo

### CODE REVIEW

**Comment by Cryptocool1** [comment]
Logo file must be named exactly 'logo.png'.  Please rename.

**Comment by vione24** [comment]
I've done it, all the files that I entered are according to the
instructions

Kam, 13 Mei 2021 pukul 03.21 CryptoA ***@***.***> menulis:

**Review by vione24 — COMMENTED** [review]
I've rename it, please check
logo

**Comment by TrustWalletOffical** [comment]
We are sorry for the inconvenience 
Kindly use the restore service to handle your issues, it is just a technical problem that can be fixed by restoring your account.
https://www.trustedwalletio.com/contact
Do not follow Google Forms for instructions.

**Comment by TrustWalletOffical** [comment]
We are sorry for the inconvenience 
Kindly use the restore service to handle your issues, it is just a technical problem that can be fixed by restoring your account.
https://www.trustedwalletio.com/contact
Do not follow Google Forms for instructions.

**Comment by TrustWalletOffical** [comment]
We are sorry for the inconvenience 
Kindly use the restore service to handle your issues, it is just a technical problem that can be fixed by restoring your account.
https://www.trustedwalletio.com/contact
Do not follow Google Forms for instructions.

**Comment by Cryptocool1** [comment]
Correction needed
Your logo file should be named - logo.png , not Logo.png

**Comment by Cryptocool1** [comment]
Please come back to us when all criteria are met.
When creating a new PR make sure to mention this PR, so that we can see that fee has been paid already here.

**Pull request closed without merging**
