### PR TITLE
Add ADD FINANCE (BEP20)

### PR DESCRIPTION
**Pull request by sagy-btc**
Adding info for BEP20 token 'ADD FINANCE'.

PR created by <a href="https://assets.trustwallet.com">TW Assets Management</a>

### CODE REVIEW

**Comment by sagy-btc** [comment]
**.** ADD Finance token is utility tokens for Dapp and web 3 products . Our users mainly use Trust wallet for transaction of our Token . 
**.** Token Being sold by Presale campaign and public sale . 
**.**  ADD Token is Listed on Decentralize exchange Pancakeswap and Biswap  with Locked Liquidity .
          https://pancakeswap.finance/swap?outputCurrency=0xc30C95205C7BC70D81da8e852255Cc89B90480f7&inputCurrency=0x55d398326f99059fF775485246999027B3197955
**.** Our smart contract is audited with Dessertfinance  https://t.co/RyMEFC3o75

**Comment by Cryptocool1** [comment]
We require CoinMarketCap listing, please come back to us once it is done. On hold for now

**Comment by sagy-btc** [comment]
https://coinmarketcap.com/dexscan/bsc/0xdd299360d477b2f5fac804d7a9515f9e9b7923cd/

**Comment by sagy-btc** [comment]
Hello do we need to provide any more information to get merge branch?

**Review by mosesojero — COMMENTED** [review]
Seen

**Pull request merged**
