### PR TITLE
Add Meta M Finance (BEP20)

### PR DESCRIPTION
**Pull request by MetaDex-M**
Adding info for BEP20 token 'Meta M Finance'.

PR created by <a href="https://assets.trustwallet.com">TW Assets Management</a>

### CODE REVIEW

**Comment by Cryptocool1** [comment]
As per our policy, brand new tokens are not included, there is a minimum requirement of 10,000 holder addresses and 15,000 transactions, in order to filter out scam tokens.
See the criteria at : https://developer.trustwallet.com/assets/requirements .

**Comment by MetaDex-M** [comment]
Hi please can you reopen this request and see my motivation below.
We have a staking system that burns the wallet after staking is complete. to reach 10K wallets will take some time.

We just got listed on CoinmarketCap and Coingecko
https://coinmarketcap.com/currencies/metaverse-m/markets/

As you can see we rely on Pancake swap as our DexPartner and our logo is obviously in your hands.
Please note: All our sources are verified and we have a high trust score. I understand your policy fully, but I would like you to please look again as we have shown significant growth since our last ticket 
Transaction volume 7,540
Regards
Dev

**Comment by Cryptocool1** [comment]
You can see our requirements here: https://developer.trustwallet.com/assets/requirements
Come back when all of them are met

**Comment by Athayde3586** [comment]
We're is my money

**Pull request closed without merging**
