### PR TITLE
Update WALT Logo

### PR DESCRIPTION
**Pull request by walletreum**

### CODE REVIEW

**Comment by vikmeup** [comment]
Can you please include `info.json` file for the token. 

Here is an example for DAI: https://github.com/trustwallet/assets/blob/master/blockchains/ethereum/assets/0x6B175474E89094C44Da98b954EedeAC495271d0F/info.json

**Comment by catenocrypt** [comment]
Please add an `info.json` file next to the `logo.png`, with info about the project, of the form:

```json
{
    "name": "Trust Wallet Token",
    "website": "https://trustwallet.com",
    "short_description": "Utility token to increase adoption of cryptocurrency.",
    "explorer": "https://explorer.binance.org/asset/TWT-8C2"
}
```

**Comment by walletreum** [comment]
Hi, I am trying to add info.json but "Add File" button is not doing anything. What's wrong?

**Comment by catenocrypt** [comment]
It's OK if you put it here in a comment and I can put it in as a file.

**Comment by walletreum** [comment]
{
    "name": "Walletreum Token",
    "website": "https://walletreum.com",
    "short_description": "WALT is the utility token of walletreum platform that rewards it's users for using the platform.",
    "explorer": "https://etherscan.io/token/0x15bCDFAd12498DE8a922E62442Ae4CC4bd33bd25"
}

**Comment by walletreum** [comment]
I have put in the comment for info.json file. can you please finalize

**Pull request merged**
