### PR TITLE
New Tokens Logo

### PR DESCRIPTION
**Pull request by alet89**
Adding logos for tokens

### CODE REVIEW

**Comment by alet89** [comment]
@zachzwei @catenocrypt  I added 4 Tokens logo, is this the why I got this error?

All checks done, returnCode 1
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! assets@1.0.0 check: `ts-node ./script/main/check`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the assets@1.0.0 check script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/runner/.npm/_logs/2020-08-09T14_58_51_210Z-debug.log
##[error]Process completed with exit code 1.

**Comment by alet89** [comment]
I tried to remove and read logos... But I always receive the error... Please help me

**Comment by catenocrypt** [comment]
The check that whitelist.json should contain the added assets has been removed from the Pull request check, next PR should be easier.
How did you manage to create a pull request from 'unknown repo'?

image

**Comment by alet89** [comment]
I actually don't know... I just cloned the repo in my PC, added the folders manually and then I made the pull request...

**Pull request closed without merging**
