### PR TITLE
Add SM PROPERTIES (BEP20)

### PR DESCRIPTION
**Pull request by aniketdhyani**
Adding info for BEP20 token 'SM PROPERTIES'.

PR created by <a href="https://assets.trustwallet.com">TW Assets Management</a>

### CODE REVIEW

**Comment by aniketdhyani** [comment]
https://dessertswap.finance/audits/SMPROPERTIES-BSC-AUDIT-20964225.pdf

our audit report

**Comment by Cryptocool1** [comment]
• What is the purpose of this token? How will it benefit Trust Wallet users?
 • How is the token being distributed? Are you conducting an airdrop?
 • Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?
 • Is the token listed on a centralized/decentralized exchange?
 • Is a Smart Contract audit completed? Where can we find this information?

**Comment by aniketdhyani** [comment]
• What is the purpose of this token? How will it benefit Trust Wallet users?
S M Properties Is A Platform Powered By Binance Smart Chain. It's Created To Bring Real-World Assets On Blockchain. We Make Value From Real Estate Tokenomics, Flipping Properties Over Tangible Concepts. It mainly used to buy NFT of our properties and we have our own swap also.

• How is the token being distributed? Are you conducting an airdrop?
There was no airdrop. Users buyed our token from our from our own swap SMEx Swap.

• Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?
There was no presale or initial coin offering.

• Is the token listed on a centralized/decentralized exchange?
Yes it is listed on SMEx Swap.

• Is a Smart Contract audit completed? Where can we find this information?
Yes Smart Contract audit completed here is the link - https://dessertswap.finance/audits/SMPROPERTIES-BSC-AUDIT-20964225.pdf

**Comment by Cryptocool1** [comment]
Is your token listed on CoinMarketCap?

**Comment by aniketdhyani** [comment]
no

**Comment by Cryptocool1** [comment]
We require CoinMarketCap listing, on hold for now.

**Comment by Cryptocool1** [comment]
Please come back to us once all criteria are met

**Comment by aniketdhyani** [comment]
other thinks are ok, except CMC?

**Comment by aniketdhyani** [comment]
please confirm that in what criterias we are not met.

**Comment by Cryptocool1** [comment]
Only cmc listing

**Pull request closed without merging**
