### PR TITLE
Addition of OML to Trust Wallet

### PR DESCRIPTION
**Pull request by nithronium**
I am aware of the current review requirements, however, please consider reading the details below;

Initially when we started our project, requirement for addition to Trust Wallet was 1000 addresses + 2500 transactions (no mention of airdrop tokens). We knew it was doable, so we started recommending Trust Wallet to our customers and airdrop participants. We have even prepared a guide that explains how to use Trust Wallet and how to add our token manually. Here is the link: https://www.youtube.com/watch?v=PL6llNer22s - Later though, Trust Wallet has changed its token addition policy, and here we are left with more than 9K verified airdrop participants and many more users and now we can't get added to Trust Wallet.

The video has over 11K views, and more than 7000 people downloaded Trust Wallet just because we recommended and they are airdrop participants. We had a list of 25000 users for airdrop, however, in order to verify that every registration is valid and users are real, we asked for phone verification and we ended up with around 9000 verified airdrop participants. 

The full list of addresses could be reached at https://omlira.com/airdroplistesi.txt - We grouped 50 addresses together, announced it on our socials (example: https://twitter.com/om_lira/status/1348172409342451712?s=20). Our social accounts, followers, and telegram channel (https://t.me/omlira) could be seen. If Trust Wallet has such metric, the addresses on the list could be compared with Trust Wallet's data, and could be seen that more than 80% of them are "NEW" Trust Wallet users.

We have airdropped to more than 5000 participants now and we will airdrop to around 4000 more accounts. We have already paid more than 6 ETH for airdrop so far. So, we believe that OML could be added to the TrustWallet simply because we are not trying to scam anyone or cause problems but just trying to make Trust Wallet usage easier for our customers. 

We could make any payment necessary to add OML to Trust Wallet.

### CODE REVIEW

**Comment by catenocrypt** [comment]
Feedback on this submission:
- Folder corresponding to the token contract should be in contract format (having mixed small and capital letters)
```
'Expect asset at path /home/runner/work/assets/assets/blockchains/ethereum/assets/0x224db5e6180761df4c3d8936585f6b8b83879770 in checksum: '0x224DB5E6180761df4C3d8936585f6b8b83879770''
```
- Fee needs to be paid.

Otherwise the submission is OK, thanks!

Please rename the folder in this PR, or create a new PR.
You may want to try our new Assets app in beta;  close this PR; go to https://assets.trustwallet.com, log on with Github, enter contract ID, logo and some additional info, and it will create a PR for you.  See  https://community.trustwallet.com/t/how-to-submit-a-token-logo-using-assets-app/82957.

**Comment by nithronium** [comment]
Already made a payment with TX ID: 8897B70FE1072D626803FB3D46841BC39A92C2A7F9119E9929900F4AF1323161

Would it be possible to edit this commit? so it gets merged?

**Comment by catenocrypt** [comment]
Accepting submission.

**Comment by nithronium** [comment]
The logo must be updated, do we have to submit a new pull request just for the logo change?

**Pull request merged**
