### PR TITLE
Add Ethereum Swarm

### PR DESCRIPTION
**Pull request by tonytony32**
Able to proceed with the payment, reopening the PR

### CODE REVIEW

**Comment by cryptomanz1** [comment]
• What is the purpose of this token? How will it benefit Trust Wallet users?
 • How is the token being distributed? Are you conducting an airdrop?
 • Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?
 • Is the token listed on a centralized/decentralized exchange?
 • Is a Smart Contract audit completed? Where can we find this information?

**Comment by tonytony32** [comment]
_> What is the purpose of this token? How will it benefit Trust Wallet users?_

The BZZ token provides users with access to data relay and storage services, and compensates node operators for these services.

 It is the native token that powers Swarm, a peer-to-peer network of nodes that collectively provide a decentralised storage and communication service. This system is economically self-sustaining due to a built-in incentive system which is enforced through smart contracts on the Ethereum blockchain.

In short, BZZ can be used to write and persist data in the Swarm network, and also receive BZZ for providing storage services.

_> How is the token being distributed? Are you conducting an airdrop?_

A public sale was conducted on Coinlist in 2021, as mentioned in their blog: https://blog.coinlist.co/swarm-token-sale-drives-over-20-000-new-token-holders/

However, there are advanced discussions on the table to provide further incentives to the network to node operators.

_> Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?_

Yes, see previous answer. As of today, all of the token supply is distributed and it is freely tradeable.

_> Is the token listed on a centralized/decentralized exchange?_

Yes, it's listed in many centralised exchanges, as you can read in [Coinmarketcap](https://coinmarketcap.com/currencies/ethereum-swarm/markets/) and [Coingecko](https://www.coingecko.com/en/coins/swarm#markets)'s market listings.

As for **decentralised exchanges**, token can be adquired in 
- [Bzzaar](https://bzz.exchange/)
- [OpenBZZ](https://openbzz.eth.limo/)
- [Honeyswap](https://honeyswap.1hive.eth.limo/) and 
- Uniswap at the moment.

_> Is a Smart Contract audit completed? Where can we find this information?_

Several audits from Quantstamp, Least Authority and Cure53 were performed before launch. I can provide the information upon request to a specific email.

**Comment by cryptomanz1** [comment]
please send your smart contract audit here

**Comment by tonytony32** [comment]
[Swarm Token - Report (3).pdf](https://github.com/trustwallet/assets/files/10498757/Swarm.Token.-.Report.3.pdf)

**Pull request merged**
