### PR TITLE
Add S315 (BEP20)

### PR DESCRIPTION
**Pull request by s315protocol**
Adding info for BEP20 token 'S315'.

PR created by <a href="https://assets.trustwallet.com">TW Assets Management</a>

### CODE REVIEW

**Comment by s315protocol** [comment]
https://bscscan.com/tx/0xac110d929f69268c9ec749661e92ba6667b5a7718046f6d206a11606465021b5

**Comment by cryptomanz1** [comment]
As per our policy, there is a minimum requirement of 10,000 holder addresses and 15,000 transactions.
See the criteria at : https://developer.trustwallet.com/listing-new-assets/requirements .

**Comment by Cryptocool1** [comment]
• What is the purpose of this token? How will it benefit Trust Wallet users?
 • How is the token being distributed? Are you conducting an airdrop?
 • Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?
 • Is the token listed on a centralized/decentralized exchange?
 • Is a Smart Contract audit completed? Where can we find this information?

**Comment by Cryptocool1** [comment]
feel free to come back to us once you are ready to provide an answers to the questions above. 
Make sure to mention this PR in new one so the fee can be reused

**Comment by s315protocol** [comment]
• What is the purpose of this token? How will it benefit Trust Wallet users?
S315 is a new attempt at two-way mobility, with a certain community user base and influence, which can bring new benefits to Trust users.

• How is the token being distributed? Are you conducting an airdrop?
The token is fully unlocked and in community hands. All tokens were
available on the market at launch, no allocations or vesting.

• Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?
No, fair launch on PancakeSwap and ContractSwap.

• Is the token listed on a centralized/decentralized exchange?
The token is on multiple DEX，PancakeSwap and ContractSwap

• Is a Smart Contract audit completed? Where can we find this information?
Yes, you can view it on our Certik page here:
https://skynet.certik.com/projects/s315-protocol

**Pull request closed without merging**
