### PR TITLE
Add DragonKing (BEP20)

### PR DESCRIPTION
**Pull request by FlingAvalon**
Adding info for BEP20 token 'DragonKing'.

PR created by <a href="https://assets.trustwallet.com">TW Assets Management</a>

### CODE REVIEW

**Comment by FlingAvalon** [comment]
[DragonKing Audit.pdf](https://github.com/trustwallet/assets/files/11365433/DragonKing.Audit.pdf)

Here is the Contract Audit.

**Comment by Cryptocool1** [comment]
Please send your audit not in pdf

**Comment by FlingAvalon** [comment]
here is the audit https://dessertswap.finance/audits/DragonKing-BSC-Audit-27663191.pdf

**Comment by FlingAvalon** [comment]
Please merge. All info has been submitted.

**Comment by Cryptocool1** [comment]
According to gopluslabs you have a whitelist function. (honeypot risk) You should fix that.

**Comment by FlingAvalon** [comment]
Check token code and the additional information sent.

**Comment by FlingAvalon** [comment]
@cryptomanz1 I am yet to get a response on this PR

**Comment by FlingAvalon** [comment]
@Cryptocool1  I am yet to get a response on this PR

**Comment by Cryptocool1** [comment]
You have 4 warnings to remove:
Снимок экрана 2023-05-03 в 23 00 52
Снимок экрана 2023-05-03 в 23 01 51

34b26-1e73-4185-b3f8-93eab63d46cd.png">

**Comment by Cryptocool1** [comment]
You have to remove 4 warnings

Снимок экрана 2023-05-03 в 23 03 13
Снимок экрана 2023-05-03 в 23 03 36
Снимок экрана 2023-05-03 в 23 03 54

**Comment by FlingAvalon** [comment]
This warning already invalid because contract owner renounced to dead address 0x0000, no one can be modified anymore

If it still have risk as mentioned,  CMC, CG and dessert finance Audit would not have approved it. 

Please verify the information with the contract codes.

**Comment by FlingAvalon** [comment]
this is the contract code

https://bscscan.com/address/0x11ac6af070fe1991a457c56fb85c577efe57f0e4#code

Screenshot_20230504_230824_com android chrome_edit_178286740199878

**Comment by FlingAvalon** [comment]
@Cryptocool1 Response please

**Comment by FlingAvalon** [comment]
@Cryptocool1 @cryptomanz1  Please respond

**Comment by Cryptocool1** [comment]
Hello, do you have any changes regarding 4 warnings I sent you before?

**Pull request merged**
