### PR TITLE
Add Tsuzuki Inu (TZKI) (ERC20)

### PR DESCRIPTION
**Pull request by TsuzukiInu**
Adding info for ERC20 token 'Tsuzuki Inu (TZKI)'.

PR created by <a href="https://assets.trustwallet.com">TW Assets Management</a>

### CODE REVIEW

**Comment by Cryptocool1** [comment]
As per our policy, brand new tokens are not included, there is a minimum requirement of 25,000 holder addresses and 50,000 transactions, in order to filter out scam tokens.
See the criteria at : https://developer.trustwallet.com/assets/requirements .

**Comment by TsuzukiInu** [comment]
> As per our policy, brand new tokens are not included, there is a minimum requirement of 25,000 holder addresses and 50,000 transactions, in order to filter out scam tokens. See the criteria at : https://developer.trustwallet.com/assets/requirements .

Hey! Thanks for getting back to me. I Followed the guidelines here and it mentions that 5,000 Holders and 10,000 TX were the requirements? https://community.trustwallet.com/t/how-to-submit-a-token-logo/3863 

If it has changed then that's fine, sorry. We do currently have 14,125 Holders and 32,523 Holders (No Presale or Airdrops were done) and we've been Audited by Techrate. Can i ask in good faith that we be considered based on the above please? :) 

If ultimately you can't update our Logo and information then that's fine and thanks for your time.

**Comment by Cryptocool1** [comment]
Please come back to us when all criteria are met.
When creating a new PR make sure to mention this PR, so that we can see that fee has been paid already here.

**Comment by TsuzukiInu** [comment]
Hey there guys. So i noticed i unfortunately paid TWICE accidentally. So i made a payment for this pull here and then for the next one https://github.com/trustwallet/assets/pull/15805 here. Can i please be refunded for this one? Thank you so much.

**Pull request closed without merging**
