### PR TITLE
Uploading Panda Girl Logo and Information

### PR DESCRIPTION
**Pull request by hiropandagirl**
Uploading Panda Girl Logo and Information

### CODE REVIEW

**Comment by hiropandagirl** [comment]
all good to merge once you have checked and are ready. Had to resize the logo.

**Comment by Cryptocool1** [comment]
• What is the purpose of this token? How will it benefit Trust Wallet users?
 • How is the token being distributed? Are you conducting an airdrop?
 • Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?
 • Is the token listed on a centralized/decentralized exchange?
 • Is a Smart Contract audit completed? Where can we find this information?

**Comment by hiropandagirl** [comment]
> • What is the purpose of this token? How will it benefit Trust Wallet users? • How is the token being distributed? Are you conducting an airdrop? • Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale? • Is the token listed on a centralized/decentralized exchange? • Is a Smart Contract audit completed? Where can we find this information?

Panda GIRL (PGIRL) will enable users to interact with a host of utilities within the Pandaverse. Including payment for NFTs, merchandise and play to earn gaming.

The token presale was done on Pinksale. The tokens were distributed to presale participants as soon as the presale was over and was done via contract call using Pinksale's platform. Liquduity is locked with Pinksale.finance.

Panda Girl (PGIRL) is listed on Pancakeswap.

We have applied to Certik for an audit. The team is KYC'd with Pinksale with government ID and videos submitted.

**Comment by ramsty** [comment]
Awaiting for smart contract audit. On hold for now.

**Comment by hiropandagirl** [comment]
> Awaiting for smart contract audit. On hold for now.

initial audit from Techrate provided at this link: https://drive.google.com/file/d/1uLflrSQmSGLC5EEGBwzO7DgzccdouQBc/view?usp=sharing. 

Please may we continue now? As mentioned we have also commissioned an audit by Certik. You can view our onboarding status with them here: https://www.certik.org/projects/panda-girl

**Comment by hiropandagirl** [comment]
> > Awaiting for smart contract audit. On hold for now.
> 
> initial audit from Techrate provided at this link: https://drive.google.com/file/d/1uLflrSQmSGLC5EEGBwzO7DgzccdouQBc/view?usp=sharing.
> 
> Please may we continue now? As mentioned we have also commissioned an audit by Certik. You can view our onboarding status with them here: https://www.certik.org/projects/panda-girl

@Cryptocool1 @ramsty

**Pull request merged**
