### PR TITLE
Add ASIX+ (BEP20)

### PR DESCRIPTION
**Pull request by asixplus**
Adding info for BEP20 token 'ASIX+'.

PR created by <a href="https://assets.trustwallet.com">TW Assets Management</a>

### CODE REVIEW

**Comment by cryptomanz** [comment]
• What is the purpose of this token? How will it benefit Trust Wallet users?
 • How is the token being distributed? Are you conducting an airdrop?
 • Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?
 • Is the token listed on a centralized/decentralized exchange?
 • Is a Smart Contract audit completed? Where can we find this information?

**Comment by asixplus** [comment]
> 

• ASIX+ Token is a token which is made by PT. META NUSANTARA VICTORI, which has purpose and the projects of P2E games, NFT Marketplace, and Metaverse.ASIX+ Token is the main utility in our 3 projects. P2E Games, NFT Market, and Nusantaraverse. ASIX+ Token can be used in all three projects.In addition, it does not rule out the possibility of developing or adding projects in the future.

• ASIX+ was distributed to all holders who migrate from ASIX Token to ASIX+.

• No

• ASIX+ was available trade on DEX Pancakeswap and listed on CEX Hotbit

• Smart Contract ASIX+ audits is working on progress by Solidity Finance

**Comment by Cryptocool1** [comment]
Are you conducting an airdrop?

**Comment by asixplus** [comment]
Hi there!

We are migrating holders from old SC to ASIX+. Here is the public 
announcement link

https://twitter.com/AsixPlusNFT/status/1516584865948262401

**Comment by cryptomanz** [comment]
#20436

**Pull request merged**
