### PR TITLE
Add BITPIF (BPF)

### PR DESCRIPTION
**Pull request by bitpif**

### CODE REVIEW

**Comment by bitpif** [comment]
help

**Comment by bitpif** [comment]
I forked it again. added a logo. #3159 won't work now? just pay again?

**Comment by catenocrypt** [comment]
@bitpif , there are some errors with this PR, but we can't fix it, because your fork is not visible.
The whitelist.json file is deleted in the PR, which is wrong.  The new contract ID should be added to it.
Please fix or close and create a new.

**Comment by catenocrypt** [comment]
Merged #3159 instead of this one, closing this one.

**Pull request closed without merging**
