### PR TITLE
Add logo and info - Audit Update (Add logo and info #11705 (old))

### PR DESCRIPTION
**Pull request by bigdogecoin**
Hi,
We have now completed the audit of Smartcontract, your team can check it out:
https://gist.github.com/yuriy77k/d38c8c73c9fed40574392e819a2fa403

This is the previous PR, you have checked it, we have paid all the cost of 2000 TWT, now we only need the audit report 
https://github.com/trustwallet/assets/pull/11705

### CODE REVIEW

**Comment by bigdogecoin** [comment]
Hi @Cryptocool1 ,
We have now completed the audit of Smartcontract, your team can check it out:
https://gist.github.com/yuriy77k/d38c8c73c9fed40574392e819a2fa403

**Comment by cryptomanz** [comment]
Who audited you?

**Comment by bigdogecoin** [comment]
Hi @cryptomanz , 
We had audit by Callisto.

**Comment by Cryptocool1** [comment]
the description should tell what the token is and what it does.
please change

**Comment by bigdogecoin** [comment]
> **the description should tell what the token is and what it does.**

The team has updated the Description in the info.json file, please check again.
Below is the updated content.

> $BigeDoge is the token of the First Decentralized Gaming World on Binance Smart Chain. The main focus is to provide the best entertainment possible for our players on blockchain, and the token is used among players. $BigeDoge is used for trading, in game activities and forming votes on important dicisions of the project among holders.

**Comment by cryptomanz** [comment]
- Can you please add links to your PR?
example: https://developer.trustwallet.com/add_new_asset#info-json-contents

**Comment by bigdogecoin** [comment]
> *** Can you please add links to your PR?**
>   **example: https://developer.trustwallet.com/add_new_asset#info-json-contents**

Do you mean this information link?:
https://github.com/trustwallet/assets/blob/b20fcc175ef2574faa385397e9a7773186c8d437/blockchains/smartchain/assets/0x2BA8c3066F36B998bC74CE8DcE260Fb5D2ba6bCc/info.json

**Comment by Cryptocool1** [comment]
no,
please look at the example 
https://developer.trustwallet.com/add_new_asset#info-json-contents

**Comment by bigdogecoin** [comment]
[https://github.com/trustwallet/assets/pull/11982/commits/b20fcc175ef2574faa385397e9a7773186c8d437](url)

**Comment by bigdogecoin** [comment]
[added links](https://github.com/trustwallet/assets/pull/11982/commits/b20fcc175ef2574faa385397e9a7773186c8d437)

**Comment by bigdogecoin** [comment]
> *** Can you please add links to your PR?**
>   example: https://developer.trustwallet.com/add_new_asset#info-json-contents

@cryptomanz 
Added links, please check again!

**Pull request merged**
