### PR TITLE
Add PEG logo and Info

### PR DESCRIPTION
**Pull request by pegazusfinance**
Pegazus Finance (PEG) is a charity - oriented token, Each transaction will be charged 1% tax fee and deposited in a Pegazus donation wallet, then donated to Binance Charity Wallet.

### CODE REVIEW

**Comment by Cryptocool1** [comment]
Correction needed:
 Contract is not in checksum format, should be 0xD585F9C5953CA97DA3551f20725a274c9e442ff3

**Comment by pegazusfinance** [comment]
> Correction needed:
> Contract is not in checksum format, should be 0xD585F9C5953CA97DA3551f20725a274c9e442ff3

how to rename checksum format?

**Comment by pegazusfinance** [comment]
Pada 2021-05-14 12:31, CryptoA menulis:
> Correction needed:
> Contract is not in checksum format, should be
> 0xD585F9C5953CA97DA3551f20725a274c9e442ff3
> 

How To rename checksum format,? are we have to create new file uploade 
with rename checksum format?

**Comment by Cryptocool1** [comment]
Please create new PR, follow doc https://community.trustwallet.com/t/how-to-submit-a-token-logo/3863
You may want to try our new Assets app in beta; go to https://assets.trustwallet.com, log on with Github, enter contract ID, logo and some additional info, and it will create a PR for you.
See https://community.trustwallet.com/t/how-to-submit-a-token-logo-using-assets-app/82957.
Make sure to mention this PR, so that we can see that fee has been paid already here.

**Comment by pegazusfinance** [comment]
> Please create new PR, follow doc https://community.trustwallet.com/t/how-to-submit-a-token-logo/3863
> You may want to try our new Assets app in beta; go to https://assets.trustwallet.com, log on with Github, enter contract ID, logo and some additional info, and it will create a PR for you.
> See https://community.trustwallet.com/t/how-to-submit-a-token-logo-using-assets-app/82957.
> Make sure to mention this PR, so that we can see that fee has been paid already here.
----------------------------------------------------------------
i have already create PR
Created PR 8045   https://github.com/trustwallet/assets/pull/8045

**Comment by Cryptocool1** [comment]
8045

**Pull request closed without merging**
