### PR TITLE
Add BCTR logo and info

### PR DESCRIPTION
**Pull request by shrinivasmani**
This is BCTR Token logo and info add trustwallet and uniswap

### CODE REVIEW

**Comment by catenocrypt** [comment]
The folder `0x579353231f3540b218239774422962c64a3693e7` needs to be under `blockchains/ethereum/assets`.  Please fix.

**Comment by shrinivasmani** [comment]
Hi can you check all details are corect ?

**Comment by Iamdeadlyz** [comment]
No need to follow it.

As per our policy, brand new tokens are not included. There is a minimum requirement of 500 holder addresses and 1000 transactions in order to filter out scam tokens. See the criteria at (mentioned in the first message by the bot): https://community.trustwallet.com/t/how-to-submit-a-token-logo/3863#how-to-get-approved

This token has below-limit usage yet. Rejecting PR for now. Please come back to us when all criteria are met.
https://etherscan.io/token/0x579353231f3540b218239774422962c64a3693e7

**Comment by shrinivasmani** [comment]
ok can i add 2nd token ?

and this token BCTR around 600+ holder but distribution token presale not send to holder 


i am try to send detail after some day after 

how much toke add 1 repositry

**Pull request closed without merging**
