### PR TITLE
Add files via upload

### PR DESCRIPTION
**Pull request by ombayoeco11**
Add Logo Token

### CODE REVIEW

**Comment by ombayoeco11** [comment]
how can i pass the token check?

**Comment by ombayoeco11** [comment]
there's a token check error here said the number of holders not checked, please check it manually. So how can i pass this check? i wouldn't pay if this check made  my request failed and i have to start allover again and paid twice because of this...

**Comment by Cryptocool1** [comment]
As per our policy, there is a minimum requirement of 10,000 holder addresses and 15,000 transactions, in order to filter out scam tokens.
See the criteria at : https://developer.trustwallet.com/listing-new-assets/requirements .

**Comment by ombayoeco11** [comment]
> As per our policy, there is a minimum requirement of 10,000 holder addresses and 15,000 transactions, in order to filter out scam tokens. See the criteria at : https://developer.trustwallet.com/listing-new-assets/requirements .

so if our holder is below 10k, my PR would be fail? what if i just pay it even if the token check is still red?

**Pull request closed without merging**
