### PR TITLE
Adding token information and logo for Magic Internet Money

### PR DESCRIPTION
**Pull request by 0xRomy**
Adding token address and information for Magic Internet Money (MIM) on Ethereum. MIM is a stable coin minted using interest bearing tokens as collateral on https://abracadabra.money/

### CODE REVIEW

**Comment by cryptomanz** [comment]
As per our policy, brand new tokens are not included, there is a minimum requirement of 25,000 holder addresses and 50,000 transactions, in order to filter out scam tokens.
See the criteria at : https://developer.trustwallet.com/assets/requirements .

**Comment by bjt54** [comment]
@0xRomy can you share links to your contract address on other support blockchains?

@cryptomanz Please merge if the sum of holders across the various protocols/chains meets the criteria you reference in here:
> As per our policy, brand new tokens are not included, there is a minimum requirement of 25,000 holder addresses and 50,000 transactions, in order to filter out scam tokens. See the criteria at : https://developer.trustwallet.com/assets/requirements .

**Comment by 0xRomy** [comment]
MIM on Fantom Opera: https://ftmscan.com/token/0x82f0b8b456c1a451378467398982d4834b6829c1

MIM on Avalanche Network: https://snowtrace.io/token/0x130966628846bfd36ff31a822705796e8cb8c18d

MIM on Arbitrum: https://arbiscan.io/token/0xfea7a6a0b346362bf88a9e4a88416b77a57d6c2a

MIM on Binance Smart Chain: https://bscscan.com/token/0xfe19f0b51438fd612f6fd59c1dbb3ea319f433ba

If you need a reference: https://docs.abracadabra.money/tokens/tokenomics#the-mim-token

**Comment by bjt54** [comment]
Reposting my comment which was deleted by the merge-fee-bot:

@cryptomanz, please merge this request once you verify there are enough holders per your comment here:
> As per our policy, brand new tokens are not included, there is a minimum requirement of 25,000 holder addresses and 50,000 transactions, in order to filter out scam tokens. See the criteria at : https://developer.trustwallet.com/assets/requirements .

You can see their contract on other supported chains in @0xRomy comment above.

**Comment by Cryptocool1** [comment]
submission looks good, awaiting for fee payment

**Comment by Cryptocool1** [comment]
could you add the links?
see the example here: https://developer.trustwallet.com/assets/repository_details

**Pull request merged**
