### PR TITLE
Add Rijent Coin (BEP20)

### PR DESCRIPTION
**Pull request by yenky**
Adding info for BEP20 token 'Rijent Coin'.

PR created by <a href="https://assets.trustwallet.com">TW Assets Management</a>

### CODE REVIEW

**Review by mohammadjnoor — APPROVED** [review]
> @yenky

**Review by mohammadjnoor — APPROVED** [review]
>

**Comment by yenky** [comment]
Hi 
Can we please go ahead for this logo information. 

Thank you

**Comment by Athayde3586** [comment]
Stop taking what is mine

**Comment by yenky** [comment]
Hi Team 
Can you please check when i can go ahead with fee pay and next process. Our all users are waiting very desperately to see Token logo in trust wallet. They trust so much in trust wallet. Please try to guide me next process. @Cryptocool1  , @cryptomanz

Thank you

**Comment by Cryptocool1** [comment]
Hello,
• What is the purpose of this token? How will it benefit Trust Wallet users?
 • How is the token being distributed? Are you conducting an airdrop?
 • Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?
 • Is the token listed on a centralized/decentralized exchange?
 • Is a Smart Contract audit completed? Where can we find this information?

**Comment by yenky** [comment]
Hi @Cryptocool1 
Thank you for your Quick response. I really appreciate it. 

What is the purpose of this token? How will it benefit Trust Wallet users?
Answer : Rijent Coin is a utility token & community rewarding gateway for blockchain & leadership education to empower your financial wealth. This is our ultimate goal, as we genuinely want to make your lives better by making payment processes faster and smarter. We collaborate closely with the every crypto community and love collecting feedback from them. Feedback is a means of improvement. 
We have many users who are using Trust wallet for their RTC and as we know their are some issue with tokens where 
people make copy of token and customers get wrong information and they buy wrong token. So if we have logo in trust 
wallet so all our customers can see very clearly that this is right token to use. As we know Trust wallet is one of 
the most secure wallet for crypto and we always advise to our customers to use Trust wallet.Trust wallet logo going to help all of our users in a very good way because they trust on trust wallet for their crypto. 

How is the token being distributed? Are you conducting an airdrop?
Answer : 6 months before when team was working on RTC token idea we decided to distribute in this manner.
60% Community ,
20% Marketing / Airdrop ,
10% Founder ,
5%  Software Development ,
3%  Legal & Advisers,
2%  Backup.
 

Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?
Answer : Yes we sold token in initial stage and transaction happened with decentralized and we have all records here :
 https://bscscan.com/token/0x913afbba462d6ae230344209d0bd11ce3ce92ed1
As you can check we are having good volume of transactions everyday because our customers are believing in RTC Token more every day. Our Pre-sale had an offer with Utility & Reward System.  

Is the token listed on a centralized/decentralized exchange?
Answer : We are on coinmarket cap already :https://coinmarketcap.com/currencies/rijent-coin/

We did submission for few decentralize exchange and in few days we are going to be on Latoken exchange : https://latoken.com/ 
 
Is a Smart Contract audit completed? Where can we find this information?
Answer : Yes 
https://rijentcoin.com/audit/RTC.COIN.Token.Audit.Report.Smart.Contract.pdf

Thank you

**Pull request merged**
