### PR TITLE
Add Eifi Logo and info Old PR#11968

### PR DESCRIPTION
**Pull request by eififinance**
Kindly add Eifi Logo and info in Trust wallet.

• What is the purpose of this token? How will it benefit Trust Wallet users?
Answer: EIFI token will use at EIFI AMM DEX platform as Fee currency, As Liquidity pool section, and much more. Also, this will use for EIFI Finance Ecosystem for voting rights its Blockchain use.

• How is the token being distributed? Are you conducting an airdrop?
Answer: The EIFI token airdrop is live in the market. And here is the coinmarket cap link where you can find details in whitepaper. https://coinmarketcap.com/currencies/eifi-finance/

• Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?
Answer: No, We did not.

• Is the token listed on a centralized/decentralized exchange?
Answer: Yes, It is listed on pancakeswap. https://coinmarketcap.com/currencies/eifi-finance/markets/ and more you can find on coinmarket cap from above mentioned link

• Is a Smart Contract audit completed? Where can we find this information?
Answer: There is no smart contract audit till. Because it is just bep20 contract. We will do once our dex platform will be live because there are under development.

If you required more details about project kindly coinmarketcap website link. There is plenty of information available.

### CODE REVIEW

**Comment by Cryptocool1** [comment]
can you please add links to your PR?
example: https://developer.trustwallet.com/add_new_asset#info-json-contents

**Comment by eififinance** [comment]
HI,

Thank you for your reply.

I am unable to find options to add links into PR. If you have any guide then I can add it.

**Comment by Cryptocool1** [comment]
send me the links here,
will add them

**Comment by eififinance** [comment]
Here are the links

Medium: https://eififinance.medium.com/
Reddit: https://www.reddit.com/r/Eyfi_finance
Facebook: https://www.facebook.com/eifi.finance/
Twitter: https://twitter.com/EifiFinance
Whitepaper: https://eifi.com/whitepaper/eifi_whitepaper_en.pdf
Bscscan: https://bscscan.com/token/0xbbf33a3c83cf86d0965a66e108669d272dfe4214
PooCoin: https://poocoin.app/tokens/0xbbf33a3c83cf86d0965a66e108669d272dfe4214
Destool.io: https://www.dextools.io/app/pancakeswap/pair-explorer/0x8d67cf634fadb84044a93c9e47824ee2f3c4d2e3
Website: https://eifi.com/

**Pull request merged**
