### PR TITLE
Add GOMA (BEP20)

### PR DESCRIPTION
**Pull request by GOMAFinance**
Adding info for BEP20 token 'GOMA'.

PR created by <a href="https://assets.trustwallet.com">TW Assets Management</a>

### CODE REVIEW

**Comment by GOMAFinance** [comment]
> 

How do I add a the one required tag to TORII Finance? The process seems to have changed 
Please can you add "DeFi"

**Comment by cryptomanz** [comment]
As per our policy, brand new tokens are not included, there is a minimum requirement of 10,000 holder addresses and 15,000 transactions, in order to filter out scam tokens.
See the criteria at : https://developer.trustwallet.com/assets/requirements .

**Comment by GOMAFinance** [comment]
AAAH WE JUST PAID, we did not see this new comment  :(

**Comment by GOMAFinance** [comment]
We are not a NEW token, this is our V1 https://bscscan.com/token/0xab14952d2902343fde7c65d7dc095e5c8be86920
I can prove it

**Comment by GOMAFinance** [comment]
We launched V2 YESTERDAY literally

**Review by chefgsaroar — COMMENTED** [review]
blockchains/smartchain/assets/0x9EC55d57208cb28a7714A2eA3468bD9d5bB15125/info.json

**Comment by GOMAFinance** [comment]
> blockchains/smartchain/assets/0x9EC55d57208cb28a7714A2eA3468bD9d5bB15125/info.json

Does this mean it will be added?

Thank you in advance for your time and cooperation!

We appreciate it

**Review by RrezaRashedi — APPROVED** [review]

**Comment by GOMAFinance** [comment]
Im confused :) im not sure if that was a yes or no haha

**Comment by GOMAFinance** [comment]
>>>>>>>>> We are not a NEW token, this is our V1 https://bscscan.com/token/0xab14952d2902343fde7c65d7dc095e5c8be86920 I can prove it

**We are growing rapidly, as I mentioned its not a new token**, we had over 47000 on our V1 and they are moving over to V2. Please let me know what I need to do in order to resolve this matter (payment was already made so please assist, I will gladly provide any supporting document that you may need

Thank you very much in advance for your time and cooperation)

**Comment by GOMAFinance** [comment]
I just need to know if there is anything I must do, we have a big AMA coming up on Tuesday - so I just want confirmation on whether this is approved, or not approved; our holders grow, our transactions have grown, we're moving fast from V1 to V2.

Please assist

**Comment by GOMAFinance** [comment]
Please can someone reply, we paid the amount 2 days ago

We are now well over 10,000 (since it was just a migration and not a new token)

Please let me know how to reopen this

**Comment by GOMAFinance** [comment]
Are we going to have to pay for this again? Please advise, we urgently need to know what we must do

**Comment by Cryptocool1** [comment]
Hello, we can accept only GOMA token

**Comment by GOMAFinance** [comment]
That is fine, GOMA ONLY PLEASE :)

**Comment by Cryptocool1** [comment]
You should create PR without KORRI token files

**Comment by GOMAFinance** [comment]
How do I do that? I dont know how to remove it?

**Comment by GOMAFinance** [comment]
Thank you for the help, I appreciate it very very much

**Comment by cryptomanz** [comment]
• What is the purpose of this token? How will it benefit Trust Wallet users?
 • How is the token being distributed? Are you conducting an airdrop?
 • Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?
 • Is the token listed on a centralized/decentralized exchange?
 • Is a Smart Contract audit completed? Where can we find this information?

**Comment by andrezud** [comment]
Projeto sem nexos tremendo scam

**Comment by andrezud** [comment]
Isso e golpe

**Comment by andrezud** [comment]
Golpe

**Comment by andrezud** [comment]
Good

**Comment by GOMAFinance** [comment]
> • What is the purpose of this token? How will it benefit Trust Wallet users? • How is the token being distributed? Are you conducting an airdrop? • Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale? • Is the token listed on a centralized/decentralized exchange? • Is a Smart Contract audit completed? Where can we find this information?

-----
Hi there,

This token has been around since early 2021 - this is a V2 migration, not a new token

-- The focus is Defi and NFT asset, through our portal https://GOMA.fi (also launched months ago) but we are currently under maintenance while we move everything to GOMA V2
--  We have an 80,000 strong community across twitter and telegram, and 47000+ previous holders of V1. The benefits to Trustwallet users is simply their ability to learn about GOMA, and to participate in our DeFi and digital asset instruments that are practically risk free (aside from price slippage)
-- The token was distributed in v1, and is continuing the migration now; nothing changes. We have been around for over 12 months as of March
-- We did a presale in July 2021, but no this will not have any presale as its simply a migration of V1 to V2
-- It's listed on Pancakeswap at this stage, and the migration to v2 was to resolve the renounced contract so that we had the power to adjust taxes and whitelist CEX's. Previously they were unwilling to accept us due to the renounced contract
-- The previous contract was audited yes, the current one is being discussed with Certik https://gomatoken.com/GOMA%20BEP20%20Token%20Smart%20Contract%20Code%20Review%20and%20Security%20Analysis%20Report%20extended%20version%20FINAL.pdf



Please, we have a big AMA this afternoon, we would appreciate cooperation, we have done everything we can. I plead with you to give us the ability to show our trust.

This project is not new

Thank you!

**Comment by GOMAFinance** [comment]
🔥GOMA Finance - GOMA V2 🔥

GOMA is a Multi-chain DeFi & NFT Protocol focused on yield optimization of DeFi, NFTfi and GAMEFi assets.

GOMA V2 launched on the 15th of April 2022, and is growing fast!

✅ #NFTs & #NFTFi 
✅ #P2E (Play to Earn) / #GAMEfi
✅ and #Metaverse / GOMAVERSE

GET GOMAV2 on Pancakeswap: https://pancakeswap.finance/swap#/swap?outputCurrency=0x9ec55d57208cb28a7714a2ea3468bd9d5bb15125

PooCoin: https://poocoin.app/tokens/0x9ec55d57208cb28a7714a2ea3468bd9d5bb15125

⏰ GOMA V1 Launched: Early 2021
🕸 Website: https://GOMAtoken.com
💰 DEFI: https://GOMA.fi
💬 Telegram: https://t.me/GOMAFinance
🐥 Twitter: https://twitter.com/GOMAFinance

**Comment by GOMAFinance** [comment]
Our token is already ON trustwallet with the V1 contract , we are just updated the contract and details for V2

0xab14952d2902343fde7c65d7dc095e5c8be86920 <--- V1

**Comment by GOMAFinance** [comment]
> Hello, we can accept only GOMA token

Let me know if there is anything else I need to do

THANK YOU :)

**Comment by GOMAFinance** [comment]
Hi there, please could we move this forward - we have a big AMA in a couple of hours
I would be very grateful, and thank you in advance for your time and efforts we honestly appreciate it.

**Comment by GOMAFinance** [comment]
Hi there, please advise

**Comment by GOMAFinance** [comment]
Hi there, we are just making sure that our messages have been seen - and thank you again for your efforts!

**Pull request merged**
