### PR TITLE
EthOS info - Merged from buidl, UniFi and Arte

### PR DESCRIPTION
**Pull request by alet89**
Hi trust Wallet team,

We are in a merging period from 
buidl (0x7b123f53421b1bF8533339BFBdc7C98aA94163db) 
UniFi (0x9E78b8274e1D6a76a0dBbf90418894DF27cBCEb5) 
and Arte (0x34612903Db071e888a4dADcaA416d3EE263a87b9) tokens 
into the EthOS token $OS (0xfdb29741f239a2406ae287913ef12415160378d3)

Announcement: https://ethos.eth.link/os.html

I kindly ask to merge this pool request with the logo and the info .json about $OS to avoid possible scams in these difficult merge days.

Thank you in advance,

AleToschi - EthOS Core Researcher

### CODE REVIEW

**Comment by cryptomanz** [comment]
As per our policy, brand new tokens are not included, there is a minimum requirement of 5000 holder addresses and 10000 transactions, in order to filter out scam tokens.
See the criteria at (mentioned in the first message by the bot): https://community.trustwallet.com/t/how-to-submit-a-token-logo/3863).

**Comment by Cryptocool1** [comment]
can you please add links to your PR?
example: https://developer.trustwallet.com/add_new_asset/repository_details

**Comment by Cryptocool1** [comment]
can't reach to your website.
  please check

**Comment by alet89** [comment]
@Cryptocool1 I updated the JSON file with the links section :)

Can I ask you what do you mean about the "can't reach your website"? The website is stored in ENS via IPFS, some times can have issues due to the .link extension, can you retry? https://ethos.eth.link/

**Pull request merged**
