### PR TITLE
Add HYPER (BEP20)

### PR DESCRIPTION
**Pull request by xcyberdragonx**
Adding info for BEP20 token 'HYPER'.

PR created by <a href="https://assets.trustwallet.com">TW Assets Management</a>

### CODE REVIEW

**Comment by xcyberdragonx** [comment]
We are migrating from our old token: https://github.com/trustwallet/assets/pull/7532

Made the issue:
https://github.com/trustwallet/assets/issues/12046

**Comment by Cryptocool1** [comment]
do you have the official announcement about the migrating?

**Comment by xcyberdragonx** [comment]
> do you have the official announcement about the migrating?


Yes, here are most of the announcements of our socials, and also links to the migration page on our website. I hope this information will suffice.



website:

https://hyperchainx.com/

Migration app available onsite:

https://migrationapp.hyperchainx.com/



Main press releases on medium (the old medium account got banned), our website also links to the new medium account:

https://medium.com/@ninja_krypto/hyperchain-x-migration-for-v2-liquidity-on-pancakeswap-2549c3f42f10

https://medium.com/@ninja_krypto/hyperchain-x-how-to-migrate-your-old-hyper-tokens-35b8d0f2b921

https://medium.com/@ninja_krypto/hyperchain-x-you-can-now-migrate-f1b6cba68f02



https://www.facebook.com/hyperchainx



https://t.me/hyperchainx/128868

https://t.me/hyperchainx/130132



https://twitter.com/HyperchainX

https://twitter.com/HyperchainX/status/1415294045270773763

https://twitter.com/HyperchainX/status/1416479953911169031

**Comment by xcyberdragonx** [comment]
@Cryptocool1 @catenocrypt @zachzwei 
Is the info provided enough? Do you need more proof?

**Pull request merged**
