### PR TITLE
Add files via upload

### PR DESCRIPTION
**Pull request by BHCHappiness**
Let's Ignore Fud #4TOKEN

### CODE REVIEW

**Comment by BHCHappiness** [comment]
Sending Payment

**Comment by Cryptocool1** [comment]
Please create new PR, follow doc https://developer.trustwallet.com/listing-new-assets/requirements
You may want to try our Assets app in beta; go to https://assets.trustwallet.com, log on with Github, enter contract ID, logo and some additional info, and it will create a PR for you.
See https://developer.trustwallet.com/listing-new-assets/repository_details

**Comment by BHCHappiness** [comment]
Hell I did all the requirements and we recently Bridge form CORE to BSC network

Proof: https://twitter.com/ignore_fud/status/1659008023329644546?s=20

**Comment by BHCHappiness** [comment]
> Please create new PR, follow doc https://developer.trustwallet.com/listing-new-assets/requirements You may want to try our Assets app in beta; go to https://assets.trustwallet.com, log on with Github, enter contract ID, logo and some additional info, and it will create a PR for you. See https://developer.trustwallet.com/listing-new-assets/repository_details

Helo please guide me

**Pull request closed without merging**
