### PR TITLE
Add Crossswap.com (BEP20)

### PR DESCRIPTION
**Pull request by divinechoice**
Adding info for BEP20 token 'Crossswap.com'.

PR created by <a href="https://assets.trustwallet.com">TW Assets Management</a>

### CODE REVIEW

**Comment by Cryptocool1** [comment]
hello,
According to our documentation token image needs to be full screen, here is link to guidelines details and an example of token images: https://community.trustwallet.com/t/how-to-submit-a-token-logo/3863

**Comment by Cryptocool1** [comment]
velaspad is already existing token.
We are not able to fix the submission. If you can fix the conflicts, please do so and update the submission.
If you cannot, please re-submit the PR with an updated fork.
Your payment is still considered

**Comment by divinechoice** [comment]
> velaspad is already existing token. We are not able to fix the submission. If you can fix the conflicts, please do so and update the submission. If you cannot, please re-submit the PR with an updated fork. Your payment is still considered

@Cryptocool1 opened a new pull request not sure how to move the payment https://github.com/trustwallet/assets/pull/13997

**Comment by Cryptocool1** [comment]
According to our documentation token image needs to be full screen, here is link to guidelines details and an example of token images: https://community.trustwallet.com/t/how-to-submit-a-token-logo/3863
please change

**Comment by divinechoice** [comment]
> According to our documentation token image needs to be full screen, here is link to guidelines details and an example of token images: https://community.trustwallet.com/t/how-to-submit-a-token-logo/3863 please change

I am not sure what does it mean by full screen the logo is transparent 256X256

**Comment by cryptomanz** [comment]
Hello,
Please follow the rules for adding tokens, your logo should be a full screen 256x256.
Exemple:
Screenshot 2021-10-01 at 01 52 16

**Comment by divinechoice** [comment]
> Hello, Please follow the rules for adding tokens, your logo should be a full screen 256x256. Exemple: https://community.trustwallet.com/t/how-to-submit-a-token-logo/3863 Screenshot 2021-10-01 at 01 52 16

Updated logo file
logo

**Pull request merged**
