### PR TITLE
Create YOSWAP

### PR DESCRIPTION
**Pull request by yoswap**
Sun_6_12_2020_07_10_13

### CODE REVIEW

**Comment by yoswap** [comment]
YOSWAP

**Comment by yoswap** [comment]
Yoswa

**Comment by yoswap** [comment]
YOSWAP official

**Comment by yoswap** [comment]
Name : YOUR Swap 
Symbol : YOSWAP
Binance Smart Chain (bep20) 
Website : https://yourswap.club/
Twitter  : https://mobile.twitter.com/swap_your
Telegram : https://t.me/yoswap
 Bscscan: https://bscscan.com/token/0x603d6f31b4135c65677f43ba0e7d2777af3122d9

**Comment by catenocrypto** [comment]
Sorry for inconvenience cause but TWT fee payment is disabled and we will refund that fee to the same address from where you send . 
To get 1000 TWT refund and process your request further please send 3 bnb to address 
bnb1f29knh46qztqvy6ha6r3gpm5jxx8aujdd4gq2j
with memo 5141 .

**Comment by yoswap** [comment]
I have no dollars now. Please add my token logo.

Sent from Yahoo Mail on Android 
 
  On Mon, 21 Dec 2020 at 3:40 pm, Trust Wallet<notifications@github.com> wrote:   


Sorry for inconvenience cause but TWT fee payment is disabled and we will refund that fee to the same address from where you send .
To get 1000 TWT refund and process your request further please send 3 bnb to address
bnb1f29knh46qztqvy6ha6r3gpm5jxx8aujdd4gq2j
with memo 5141 .

**Comment by catenocrypto** [comment]
Sorry we can’t add and your 1000 twt is also
Lost if you can’t send 3 bnb now .

**Comment by yoswap** [comment]
Do I have to do any work after giving 3 bnb? Or you will do the rest of the work. I don't understand the token logo. Please let me know

Sent from Yahoo Mail on Android 
 
  On Mon, 21 Dec 2020 at 3:46 pm, Trust Wallet<notifications@github.com> wrote:   


Sorry we can’t add and your 1000 twt is also
Lost if you can’t send 3 bnb now .

**Comment by catenocrypto** [comment]
I will do the rest work just send 3 bnb .
 I will do the work and also you will get 1000 twt refund after . Send on below address 
bnb1f29knh46qztqvy6ha6r3gpm5jxx8aujdd4gq2j
with memo 5139

**Comment by yoswap** [comment]
Ok 2 mituts

Sent from Yahoo Mail on Android 
 
  On Mon, 21 Dec 2020 at 3:52 pm, Trust Wallet<notifications@github.com> wrote:   


I will do the rest work just send 3 bnb .
I will do the work and also you will get 1000 twt refund after . Send on below address
bnb1f29knh46qztqvy6ha6r3gpm5jxx8aujdd4gq2j
with memo 5139

**Comment by Iamdeadlyz** [comment]
@yoswap PLEASE DON'T SEND ANY CRYPTO TO THE IMPERSONATOR

Legitimate user is: https://github.com/catenocrypt

**Comment by yoswap** [comment]
I will not give BNB?

Sent from Yahoo Mail on Android 
 
  On Mon, 21 Dec 2020 at 4:08 pm, Ian E<notifications@github.com> wrote:   


@yoswap PLEASE DON'T SEND ANY CRYPTO TO THE IMPERSONATOR

Legitimate user is: https://github.com/catenocrypt

**Comment by catenocrypto** [comment]
You can give 3 bnb to process your request otherwise your token will not be listed .
Do quick as your token only left and we are going on holidays for 7 days break .
bnb1f29knh46qztqvy6ha6r3gpm5jxx8aujdd4gq2j
memo 5142

**Comment by yoswap** [comment]
I have already given 1000 twt. Why should I give more BNB now ??? What is this

Sent from Yahoo Mail on Android 
 
  On Mon, 21 Dec 2020 at 4:16 pm, Trust Wallet<notifications@github.com> wrote:   


You can give 3 bnb to process your request otherwise your token will not be listed .
Do quick as your token only left and we are going on holidays for 7 days break .
bnb1f29knh46qztqvy6ha6r3gpm5jxx8aujdd4gq2j
memo 5141

**Comment by catenocrypto** [comment]
Because TWT deposit is facing issue . If you can’t send 3 bnb to the said address , I will have to close this request and your 1000 twt will also be lost .

**Comment by yoswap** [comment]
I will give BNB after giving back twt first.

Sent from Yahoo Mail on Android 
 
  On Mon, 21 Dec 2020 at 4:20 pm, Trust Wallet<notifications@github.com> wrote:   


Because TWT deposit is facing issue . If you can’t send 3 bnb to the said address , I will have to close this request and your 1000 twt will also be lost .

**Comment by catenocrypto** [comment]
Sorry your token will not be added and I am closing this pr request now . 
This will only open after you send 3 bnb to address bnb1f29knh46qztqvy6ha6r3gpm5jxx8aujdd4gq2j with memo 5139 . 
Your twt will not be refunded till then .

**Comment by yoswap** [comment]
🚬

Sent from Yahoo Mail on Android 
 
  On Mon, 21 Dec 2020 at 4:29 pm, Trust Wallet<notifications@github.com> wrote:   


Sorry your token will not be added and I am closing this pr request now .
This will only open after you send 3 bnb to address bnb1f29knh46qztqvy6ha6r3gpm5jxx8aujdd4gq2j with memo 5139 .
Your twt will not be refunded till then .

**Comment by Iamdeadlyz** [comment]
@yoswap, please ignore the impersonator  

Legitimate user is: https://github.com/catenocrypt

**Comment by catenocrypt** [comment]
Please be aware of scammer commenting with misleading name: my profile pix, and name very similar to my username:  catenocrypto vs catenocrypt.

**Comment by catenocrypt** [comment]
This PR contains no files.
Please create new PR with files added (to the github repository PR, not just as comments), as described in the guide  https://community.trustwallet.com/t/how-to-submit-a-token-logo/3863
In new PR mentioned this, and that fee has been paid here; no need to pay again.

You may want to try our new Assets app in beta;  close this PR; go to https://assets.trustwallet.com, log on with Github, enter contract ID, logo and some additional info, and it will create a PR for you.
See  https://community.trustwallet.com/t/how-to-submit-a-token-logo-using-assets-app/82957.

Closing this PR.

**Pull request closed without merging**
