### PR TITLE
Add TOSKA (BEP20)

### PR DESCRIPTION
**Pull request by Toskaverse**
Adding info for BEP20 token 'TOSKA'.

PR created by <a href="https://assets.trustwallet.com">TW Assets Management</a>

### CODE REVIEW

**Comment by Cryptocool1** [comment]
your logo should be 256/256, please change

**Comment by Toskaverse** [comment]
Picsart_22-03-18_06-33-01-807

**Comment by Toskaverse** [comment]
Is it correct..

**Comment by Toskaverse** [comment]
Is it correct..

**Comment by Toskaverse** [comment]
Hello R U there?

**Comment by Toskaverse** [comment]
If anything else pls update & how much time to display logo at trust wallet.

**Comment by Toskaverse** [comment]
https://github.com/Cryptocool1
If anything else pls update & how much time to display logo at trust wallet.

**Comment by Toskaverse** [comment]
Thanks 😊
For Your Support.

**Pull request merged**
