### PR TITLE
Update list.json

### PR DESCRIPTION
**Pull request by ClanMudhorn**
Added Terrarium Validator to Terra Classic Validator list.

### CODE REVIEW

**Comment by ClanMudhorn** [comment]
Is the Fee request updated somewhere im not seeing? 

It states a "Modest fee", but thats liek 1200usd at burrent BNB value.

**Comment by ClanMudhorn** [comment]
Is the Fee request updated somewhere im not seeing?

It states a "Modest fee", but thats like 1200usd at current BNB value. or 750usd in TWT value.

Not really, modest.

**Comment by ninooo123** [comment]
Skickat från Outlook för iOS<https://aka.ms/o0ukef>
________________________________
Från: merge-fee-bot[bot] ***@***.***>
Skickat: Monday, January 29, 2024 5:35:53 PM
Till: trustwallet/assets ***@***.***>
Kopia: Subscribed ***@***.***>
Ämne: Re: [trustwallet/assets] Update list.json (PR #27302)


Closed #27302<https://github.com/trustwallet/assets/pull/27302>.

**Comment by ninooo123** [comment]
0x50846B8aADa134D06A03D4cff9394121fC55Db3f


Skickat från Outlook för iOS<https://aka.ms/o0ukef>

**Pull request closed without merging**
