### PR TITLE
Create EthBits ETBS Token

### PR DESCRIPTION
**Pull request by icarusvn**
0x5aeb8ffc141852afab8c16eff91b78478de14699

### CODE REVIEW

**Comment by Iamdeadlyz** [comment]
Wrong directory. Please follow these guides:
- https://community.trustwallet.com/t/how-to-add-the-token-information/3888
- https://community.trustwallet.com/t/how-to-submit-a-token-logo/3863

**Comment by icarusvn** [comment]
name: EthBits ETBS Token                                                                                                                                                                        
ETBS json
0x5aeb8ffc141852afab8c16eff91b78478de14699

https://etherscan.io/token/0x5aeb8ffc141852afab8c16eff91b78478de14699

**Comment by Iamdeadlyz** [comment]
Please read and understand my previous response: https://github.com/trustwallet/assets/pull/4860#issuecomment-731669077

**Comment by Iamdeadlyz** [comment]
Still incorrect. Please read and understand the guides:
https://community.trustwallet.com/t/how-to-add-the-token-information/3888
https://community.trustwallet.com/t/how-to-submit-a-token-logo/3863

**Comment by catenocrypt** [comment]
Closing PR, as submission was not corrected.
Please open a new PR with corrected info if you wish (fee can be transferred).

**Comment by icarusvn** [comment]
I don't understand how to do it, so please return the money to me

Vào 18:46 Th 6, 18 thg 12 2020 Adam R <notifications@github.com> đã viết:

**Comment by icarusvn** [comment]
bnb1vv95mrp4x47zayxjpse7xud2g6cm7e0lmwrapa
Thanks

Vào 13:24 Th 4, 27 thg 1 2021 Huy Hoàng <yessuccess550@gmail.com> đã viết:

**Comment by catenocrypt** [comment]
Sorry, we don't do refund, but you can create new Pull Request (with already paid fee).

**Comment by icarusvn** [comment]
I tried to make a request according to you, but all is wrong, and I still
can't understand it to make my request pull, so please pay me back, or you
do it yourself  ask for help

Vào 16:31 Th 4, 27 thg 1 2021 Adam R <notifications@github.com> đã viết:

**Comment by icarusvn** [comment]
Hello?

Vào 17:54 Th 4, 27 thg 1 2021 Huy Hoàng <yessuccess550@gmail.com> đã viết:

**Comment by icarusvn** [comment]
???

Vào 16:31 Th 4, 27 thg 1 2021 Adam R <notifications@github.com> đã viết:

**Pull request closed without merging**
