### PR TITLE
Add DYOR Token (BEP20)

### PR DESCRIPTION
**Pull request by jetrich**
Adding info for BEP20 token 'DYOR Token'.

PR created by <a href="https://assets.trustwallet.com">TW Assets Management</a>

### CODE REVIEW

**Comment by jetrich** [comment]
Payment was sent and approved previously. Prior PR was closed. https://github.com/trustwallet/assets/pull/17705
Data provided by CMC is correct yet still fails to display in Trust Wallet. Attached is a pdf comparing the API response from CMC. DYOR and DBT are listing in the file to show that the data is incredibly similar for both tokens. DBT displays in Trust Wallet.
[DYOR DBT API comparison.pdf](https://github.com/trustwallet/assets/files/8151730/DYOR.DBT.API.comparison.pdf)
.

**Comment by cryptomanz** [comment]
Submission looks good. awaiting fee payment.

**Comment by jetrich** [comment]
Fee has already been paid. It is noted on PR https://github.com/trustwallet/assets/pull/17350.

**Comment by jetrich** [comment]
Fee has been paid. Again. CMC has our correct contract listed `0x10051147418C42218986CeDD0aDC266441F8a14f` and their API supplies accurate price information.

**Comment by jetrich** [comment]
I don't know where else to post this, but our price is still not reflecting correctly in the Trust Wallet. The Logo is there. Other wallets are displaying the price correctly. CMC shows our information correctly as well. Please advise.

**Pull request merged**
