### PR TITLE
Add Boba logo and info

### PR DESCRIPTION
**Pull request by AyushBherwani1998**
## Description

Related to Boba chain addition to Trust wallet core. PR: [2151](https://github.com/trustwallet/wallet-core/pull/2151)

### CODE REVIEW

**Comment by Cryptocool1** [comment]
Please create new PR, follow doc https://developer.trustwallet.com/assets/requirements
You may want to try our Assets app in beta; go to https://assets.trustwallet.com, log on with Github, enter contract ID, logo and some additional info, and it will create a PR for you.
See https://developer.trustwallet.com/assets/repository_details

**Comment by AyushBherwani1998** [comment]
@Cryptocool1 I'm not trying to add assets, I'm trying to add a new blockchain. You can check the related PR in the description.

**Comment by AyushBherwani1998** [comment]
For more information, [you can check the comment](https://github.com/trustwallet/wallet-core/pull/2151#issuecomment-1102367882).

**Comment by hewigovens** [comment]
@AyushBherwani1998 can you please fix the icon? should be square and 256 x 256

**Comment by AyushBherwani1998** [comment]
> @AyushBherwani1998 can you please fix the icon? should be square and 256 x 256

Done @hewigovens.

**Pull request merged**
