### PR TITLE
chore: update Ben logo

### PR DESCRIPTION
**Pull request by fschade**
Uniswap stopped trading ben because some logo flaws.
The logo and [ownership](https://twitter.com/bitboy_crypto?s=11&t=3ywuVueumylyQQ6tE-Vddw) changed to [bitBoy](https://twitter.com/bitboy_crypto?s=11&t=3ywuVueumylyQQ6tE-Vddw).

update the 0x9bf1d7d63dd7a4ce167cf4866388226eeefa702e ben coin logo to the latest version.

### CODE REVIEW

**Comment by Hylogenesis** [comment]
Hello! I am a member of the BEN team. We would love to get this updated as soon as we can to resume uniswap trading :). Let us know if there is anything on our end we can do.

**Comment by Cryptocool1** [comment]
Please send me an official announcement

**Comment by Hylogenesis** [comment]
Hello,

I am a team member of $BEN.

Linked here is our official Twitter and Twitter post announcing the new
logo.

https://twitter.com/bencoin_eth?t=-b-5wzQVS5VU69wxduCUnQ&s=09

If you need something more specific we are happy to supply.

Sincerely,

BEN Team

**Comment by fschade** [comment]
> Please send me an official announcement

@Cryptocool1, https://twitter.com/bitboy_crypto/status/1656802054914949124?s=46&t=3ywuVueumylyQQ6tE-Vddw

**Pull request merged**
