### PR TITLE
Add Chinu (SPL)

### PR DESCRIPTION
**Pull request by KnucklesButRich**
Adding info for SPL token 'Chinu'.

PR created by <a href="https://assets.trustwallet.com">TW Assets Management</a>

### CODE REVIEW

**Comment by KnucklesButRich** [comment]
3E77264B9A370BB89A6835309D457EE33C082724C14243ED70D74D835CBD2B6D

This is the TXID

**Comment by KnucklesButRich** [comment]
> @KnucklesButRich, kind reminder: please pay fee: **500 TWT** with the memo **27361** to the address `bnb158fgd782we4tz9vwwcj9pmmxvxhl6z46lfm7c8`. Alternatively, 5 BNB is also accepted (same memo & address).
> 
> **QR** code: [Trust](https://api.qrserver.com/v1/create-qr-code/?size=200x200&data=https%3A%2F%2Flink.trustwallet.com%2Fsend%3Fcoin%3D714%26address%3Dbnb158fgd782we4tz9vwwcj9pmmxvxhl6z46lfm7c8%26amount%3D500%26memo%3D27361) | [other wallet](https://api.qrserver.com/v1/create-qr-code/?size=200x200&data=bnb158fgd782we4tz9vwwcj9pmmxvxhl6z46lfm7c8%3Famount%3D500%26memo%3D27361) See the [Pull Request Fee FAQ](https://developer.trustwallet.com/assets/faq).

I have already sent it here is the txid 3E77264B9A370BB89A6835309D457EE33C082724C14243ED70D74D835CBD2B6D

**Comment by KnucklesButRich** [comment]
@nhancv

**Comment by KnucklesButRich** [comment]
@cryptocool1 @cryptomanz1

**Comment by cryptomanz1** [comment]
there is no memo in your transaction. That's why bot cannot identify the payment.

**Comment by cryptomanz1** [comment]
paid

**Comment by cryptomanz1** [comment]
As per our policy, there is a minimum requirement of 10,000 holder addresses and 15,000 transactions.
See the criteria at : https://developer.trustwallet.com/listing-new-assets/requirements .

**Comment by cryptomanz1** [comment]
Feel free to come back to us once all criteria are met. Make sure to mention this PR so the fee can be reused.

**Comment by KnucklesButRich** [comment]
Hello @cryptomanz1 

Thank you for handling our PR,

Will re-check our requirements and add another comment tagging you next time,

Warmest Regards

**Pull request closed without merging**
