### PR TITLE
Add QDX logo and info

### PR DESCRIPTION
**Pull request by morris12XBit**

### CODE REVIEW

**Comment by Cryptocool1** [comment]
As per our policy, brand new tokens are not included, there is a minimum requirement of 10,000 holder addresses and 15,000 transactions.
See the criteria at : https://developer.trustwallet.com/assets/requirements .

**Comment by Cryptocool1** [comment]
Feel free to come back to us once all criteria are met. Make sure to mention this PR so the fee can be reused

**Comment by morris12XBit** [comment]
This is not a brand new token. We already have the BSC version of our token https://bscscan.com/token/0x9e3a9F1612028eeE48F85cA85f8Bed2f37d76848.

**Comment by morris12XBit** [comment]
The BSC version was added to Trust Wallet 3 years ago.

**Pull request closed without merging**
