### PR TITLE
Merge pull request #1 from trustwallet/master

### PR DESCRIPTION
**Pull request by M7V2**
M7V2

### CODE REVIEW

**Comment by mohammadjnoor** [comment]
[Contribution guidelines for this project](docs/CONTRIBUTING.md)

**Comment by mohammadjnoor** [comment]
`>Contribution` guidelines for this project](docs/CONTRIBUTING.md)

**Comment by mohammadjnoor** [comment]
> This site was built using [GitHub Pages](https://pages.github.com/).

**Comment by Athayde3586** [comment]
We're r my assets they r not in my trust wallet

**Pull request closed without merging**
