### PR TITLE
Update Audit info

### PR DESCRIPTION
**Pull request by jamwili1986**
Hello Team
We had finish audit from techrate.org 
Info audit in Techrate github:
 - https://github.com/TechRate/Smart-Contract-Audits/blob/main/miniShibaToken%20Full%20Smart%20Contract%20Security%20Audit.pdf
 - Techrate Blockchain Solutions and Consulting:
Techrate is an analytical and engineering agency focused on blockchain technology solutions and audits.
it a part of last pull request: https://github.com/trustwallet/assets/pull/11774
thank you

### CODE REVIEW

**Comment by cryptomanz** [comment]
Can your answer some questions?
 • What is the purpose of this token? How will it benefit Trust Wallet users?
 • How is the token being distributed? Are you conducting an airdrop?
 • Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?
 • Is the token listed on a centralized/decentralized exchange?
 • Is a Smart Contract audit completed? Where can we find this information?

**Comment by Cryptocool1** [comment]
• What is the purpose of this token? How will it benefit Trust Wallet users?

**Comment by jamwili1986** [comment]
> • What is the purpose of this token? How will it benefit Trust Wallet users?

Hello team
Purpose of this token: miniSHIB aims to bring cryptocurrency to a wider audience through engaging content, whilst raising funds for animal welfare charities.
We had buil 1 big pool on pankage swap- and big volume on pankageswap. i think project can to support for any user on trustwallet to Bringing joy to animal lovers.

All project info can find in website: https://minishib.com
miniSHIB aims to bring cryptocurrency to a wider audience through engaging content, whilst raising funds for animal welfare charities.
We had ICO on DxSale and locked LP value in this: Check info: https://dxsale.app/app/v2_9/dxlockview?id=0&add=0x07b7768F6863943a16372876A8000232b6391AdC&type=lplock&chain=BSC
we had list in PankageSwap: https://exchange.pancakeswap.finance/#/swap?inputCurrency=0x35bd36597ff784fcc30d08ebe4bd917374c40d4b
We had finish audit from techrate.org
Info audit in Techrate github:

https://github.com/TechRate/Smart-Contract-Audits/blob/main/miniShibaToken%20Full%20Smart%20Contract%20Security%20Audit.pdf
Techrate Blockchain Solutions and Consulting:
Techrate is an analytical and engineering agency focused on blockchain technology solutions and audits.

**Comment by cryptomanz** [comment]
Hello,
- can you please add links to your PR?
example: https://developer.trustwallet.com/add_new_asset#info-json-contents

**Comment by cryptomanz** [comment]
You need to put comma after id field 
please change

**Pull request merged**
