### PR TITLE
Update BitStash (STASH) token "migrated"

### PR DESCRIPTION
**Pull request by bitstashco**
This PR is being closed due to inactivity. If you wish to continue, please have us reopen the PR before sending your payment.
Do NOT send payments for closed PR, as the fee may by lost!
  (99 vs. 99 hrs)

### CODE REVIEW

**Comment by catenocrypt** [comment]
Note: old token is  blockchains/ethereum/assets/0x965F109d31CCb77005858DEfaE0Ebaf7B4381652/info.json

**Comment by catenocrypt** [comment]
Corrections needed:
- Please fill description field with a few sentence summary
- Please set website field to project website
- Please set status of old token to `abandoned`  blockchains/ethereum/assets/0x965F109d31CCb77005858DEfaE0Ebaf7B4381652/info.json

**Comment by bitstashco** [comment]
I have gone ahead and updated the following as requested.

**Comment by catenocrypt** [comment]
Submission looks OK; awaiting fee payment.

**Pull request closed without merging**
