### PR TITLE
Add PathFund logo to Trustwallet

### PR DESCRIPTION
**Pull request by PathFund**

### CODE REVIEW

**Comment by PathFund** [comment]
What seems to be the problem in this case? 
Thanks in advance.

**Comment by PathFund** [comment]
Do we have to submit a new PR or can we modify this one and it will be reviewed later?

**Comment by Cryptocool1** [comment]
can you please create new PR using our new Assets app in beta; go to https://assets.trustwallet.com, log on with Github, enter contract ID, logo and some additional info, and it will create a PR for you.
See https://community.trustwallet.com/t/how-to-submit-a-token-logo-using-assets-app/82957.
When creating new PR, mention this PR, so that fee can be reused, and not paid again.

**Comment by PathFund** [comment]
Created PR 8817   https://github.com/trustwallet/assets/pull/8817

Done @Cryptocool1 

Thank you very much!

**Comment by PathFund** [comment]
Good morning, is everything alright with the other PR?

**Pull request closed without merging**
