### PR TITLE
Edit Terra Validator name

### PR DESCRIPTION
**Pull request by PRIDE-AFZ**

### CODE REVIEW

**Comment by PRIDE-AFZ** [comment]
Why This branch has conflicts?

**Comment by Cryptocool1** [comment]
> Why This branch has conflicts?

because it's updating

**Comment by PRIDE-AFZ** [comment]
Do I need to pay 5 bnb again to make changes?

**Comment by Cryptocool1** [comment]
Yes , a fee of 500TWT or 5BNB is required for each Pull Request.
see : https://developer.trustwallet.com/assets/pr-fee

**Pull request closed without merging**
