### PR TITLE
Add Yearn Finance Passive Income

### PR DESCRIPTION
**Pull request by yfpi**
* Add Yearn Finance Passive Income

* Add info.json

* Add logo.png

### CODE REVIEW

**Comment by Iamdeadlyz** [comment]
As per our policy, brand new tokens are not included. There is a minimum requirement of 500 holder addresses and 1000 transactions in order to filter out scam tokens. See the criteria at (mentioned in the first message by the bot): https://community.trustwallet.com/t/how-to-submit-a-token-logo/3863#how-to-get-approved

This token has below-limit usage yet. Rejecting PR for now. Please come back to us when all criteria are met.
https://etherscan.io/token/0x05D27CdD23E22ca63e7f9c7C6D1B79ede9C4fCF5

**Comment by yfpi** [comment]
There are more than 1500 transactions. The tokens holders are less due to big whales have entered in the project. Probit Global has announced to list YFPI token on 29th September. This is the announcement by Probit exchange https://support.probit.com/hc/en-us/articles/900002960186-ProBit-Exchange-Lists-Yearn-Finance-Passive-Income-YFPI-

**Comment by Iamdeadlyz** [comment]
> There are more than 1500 transactions. The tokens holders are less due to big whales have entered in the project. Probit Global has announced to list YFPI token on 29th September. This is the announcement by Probit exchange https://support.probit.com/hc/en-us/articles/900002960186-ProBit-Exchange-Lists-Yearn-Finance-Passive-Income-YFPI-

Understood. However, we have to follow the rules as stated in the requirements. Feel free to let us know if you meet the said minimum so we can reopen this pull request.

**Comment by yfpi** [comment]
Okay! Thanks for you kind support.

**Pull request closed without merging**
