### PR TITLE
Add QBT logo and info

### PR DESCRIPTION
**Pull request by qubit-dev**
Request for registration of QBT logo and info.

We have already been listed on CoinGecko, CoinMarketCap, verified by bscscan.
- https://www.coingecko.com/en/coins/qubit
- https://coinmarketcap.com/currencies/qubit

Although we currently have 2,647 token holders at this time, it is due to the fact that we are offering several options (token locker and pools) for our token holders. You can see that the number of transactions for our token already exceeds 238,380. (And TVL exceeds $500m)

It would be really appreciated if our token(PR) is reviewed appropriately and approved by TrustWallet.

Thank you!

### CODE REVIEW

**Comment by Cryptocool1** [comment]
hello,
 • How is the token being distributed? Are you conducting an airdrop?
• Is a Smart Contract audit completed? Where can we find this information?

**Comment by qubit-dev** [comment]
• How is the token being distributed? Are you conducting an airdrop?
 - 5% are distributed through pre-launch event. (which is similar to pancakeswap IFO)
 - 57% will be distributed as liquidity mining rewards.
 - The rest are allocated for marketing, security, developer's supply and our ETF-like fund.
 - We are not conducting an airdrop.
 - You can check details in our document (https://mound-finance.gitbook.io/qubit-docs/governance/qbt-tokenomics)

• Is a Smart Contract audit completed? Where can we find this information?
 - Yes, our contracts are fully audited by PeckShield. You can check full report in https://github.com/PancakeBunny-finance/qubit-finance/blob/master/audits/PeckShield-Audit-Report-Qubit-v1.0.pdf

**Comment by Cryptocool1** [comment]
can you please add links?
here you can find the example: https://developer.trustwallet.com/assets_overview/requirements

**Comment by qubit-dev** [comment]
@Cryptocool1 
Thanks for the reply. 

I have updated links. Please let me know if there's any problem. 

Thank you.

**Pull request merged**
