### PR TITLE
info for token decentrawood

### PR DESCRIPTION
**Pull request by mayureshpwr**
Decentrawood is a metaverse token, designed and built on the Polygon network for enhanced scalability and efficiency in virtual worlds.

### CODE REVIEW

**Comment by cryptomanz1** [comment]
• What is the purpose of this token? How will it benefit Trust Wallet users?
 • How is the token being distributed? Are you conducting an airdrop?
 • Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?
 • Is the token listed on a centralized/decentralized exchange?
 • Is a Smart Contract audit completed? Where can we find this information?

**Comment by mayureshpwr** [comment]
> • What is the purpose of this token? How will it benefit Trust Wallet users? • How is the token being distributed? Are you conducting an airdrop? • Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale? • Is the token listed on a centralized/decentralized exchange? • Is a Smart Contract audit completed? Where can we find this information?

What is the purpose of this token? How will it benefit Trust Wallet users?
The DEOD token is the native currency of the Decentrawood metaverse, enabling users to create, own, and monetize virtual content. Trust Wallet users will benefit by gaining access to a decentralized, interoperable virtual world where they can engage in various activities, trade NFTs, and participate in the platform's economy.

How is the token being distributed? Are you conducting an airdrop?
Allotment has done through smartcontract. While airdrop has been done several times.

Did you sell the tokens at an Initial Coin Offering (ICO) or a token presale?
Yes, the DEOD token was sold through a private sale to seed fund investors.

Is the token listed on a centralized/decentralized exchange?
Yes, the DEOD token is listed on QuickSwap, a decentralized exchange, and BitMart, a centralized exchange.

Is a Smart Contract audit completed? Where can we find this information?
Yes, the DEOD token has been audited by SolidProof. The audit report is available at [SolidProof](https://app.solidproof.io/projects/decentrawood).

**Comment by mayureshpwr** [comment]
> • What is the purpose of this token? How will it benefit Trust Wallet users? • How is the token being distributed? Are you conducting an airdrop? • Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale? • Is the token listed on a centralized/decentralized exchange? • Is a Smart Contract audit completed? Where can we find this information?

I provided all answers for your question so how many days will it take to get listed ?

**Comment by mayureshpwr** [comment]
@Cryptocool1 how much time will it take to update the logo of deod token ?

**Pull request merged**
