### PR TITLE
Remove Monetas Logo

### PR DESCRIPTION
**Pull request by monetas26**
please remove monetas logo on trustwallet , do not change or remove any other information ,only remove monetas logo on trustwallet.

### CODE REVIEW

**Comment by monetas26** [comment]
Hi,
It was old Logo already on Trust wallet, We Need To Only Remove Logo on Trust wallet.

**Comment by cryptomanz** [comment]
Please create new PR, follow doc https://developer.trustwallet.com/assets/requirements
You may want to try our Assets app in beta; go to https://assets.trustwallet.com, log on with Github, enter contract ID, logo and some additional info, and it will create a PR for you.
See https://developer.trustwallet.com/assets/repository_details

**Comment by monetas26** [comment]
> Please create new PR, follow doc https://developer.trustwallet.com/assets/requirements You may want to try our Assets app in beta; go to https://assets.trustwallet.com, log on with Github, enter contract ID, logo and some additional info, and it will create a PR for you. See https://developer.trustwallet.com/assets/repository_details

Hi,
It was old Logo already on Trust wallet, We Need To Only Remove Logo on Trust wallet.

**Comment by monetas26** [comment]
Hi,
It was old Logo already on Trust wallet, We Need To Only Remove Logo on
Trust wallet.

**Comment by monetas26** [comment]
Hi,
It was an old Logo already on Trust wallet, We Need To Only Remove Logo on
Trust wallet. Please Do as early as possible

**Pull request closed without merging**
