### PR TITLE
Add TetherTV (BEP20)

### PR DESCRIPTION
**Pull request by popaiatx**
Adding info for BEP20 token 'TetherTV'.

PR created by <a href="https://assets.trustwallet.com">TW Assets Management</a>

### CODE REVIEW

**Comment by popaiatx** [comment]
Our token is almost 1 month old, we also made a migration in our smart contract which takes longer.
All of this, together with championships and incentives, made us reach this milestone very quickly.

Old contract:

0x111d06FB2E0C4f3e2bF6dffaaE6Be7D8b61F151D

New Contract:

0x9906dbded3dbf64a1f69b6e89a5c9f2e94d12a79

Gaming competitions in group:
https://t.me/UsdtvGroup/87217
https://t.me/UsdtvGroup/86553
And more..

Incentives:
https://t.me/UsdtvGroup/88155

Gleam Giveaway:

https://gleam.io/kFQye/tether-tv-usdtv-giveaway




Enviado de Outlook para iOS<https://aka.ms/o0ukef>
________________________________
De: CryptoA ***@***.***>
Enviado: Tuesday, March 12, 2024 11:47:57 AM
Para: trustwallet/assets ***@***.***>
Cc: popaiatx ***@***.***>; Author ***@***.***>
Assunto: Re: [trustwallet/assets] Add TetherTV (BEP20) (PR #27618)


Hello, how did you get more than 10k holders in less than in 1 week?

**Comment by Cryptocool1** [comment]
• What is the purpose of this token? How will it benefit Trust Wallet users?
 • How is the token being distributed? Are you conducting an airdrop?
 • Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?
 • Is the token listed on a centralized/decentralized exchange?
 • Is a Smart Contract audit completed? Where can we find this information?

**Comment by popaiatx** [comment]
1. TetherTV Project and the Importance of Visibility and Credibility:

The TetherTV project is designed to enhance user engagement and facilitate the monetization of such interactions. Achieving visibility and credibility is essential for our goals. Therefore, listing our project on TrustWallet is a strategic priority. This will not only elevate our visibility but also strengthen trust in our project by affiliating it with a platform that is both recognized and respected within the cryptocurrency domain.


2. Token Distribution and Engagement Strategies:

Our token distribution strategy focuses on encouraging active participation through interactive campaigns, including games and competitions within our Telegram group, complemented by an ongoing AirDrop campaign via the Gleam platform. We are dedicated to fostering organic engagement within our community by offering incentives for participation. Detailed records of these activities are available in the pinned announcements of our Telegram group.


3. Sources of Liquidity and Launch Strategy:

Our launch strategy for the token adopts a distinctive approach, opting out of a pre-sale or ICO (Initial Coin Offering). Instead, we have secured liquidity through strategic partnerships and the backing of investors who believe in our project's potential and have chosen to invest in it.


4. Future Listing Strategies:

Until now, our emphasis has been on decentralized exchange platforms (DEX). However, we are expanding our focus with firm plans to list our token on prominent centralized exchanges, including MEXC and Gate.io. This move is a significant progression for our project, aiming to enhance liquidity and provide our investors with more trading options.


5. Contract Migration and Security:

We have recently migrated our smart contract to adhere to more rigorous regulatory and compliance standards. Although the contract has not undergone formal auditing, an independent code evaluation indicates a high security score. No vulnerabilities, such as honeypots, have been detected that could jeopardize the security of our users or the investment in the project.


Enviado de Outlook para iOS<https://aka.ms/o0ukef>
________________________________
De: CryptoA ***@***.***>
Enviado: Tuesday, March 12, 2024 1:15:55 PM
Para: trustwallet/assets ***@***.***>
Cc: popaiatx ***@***.***>; Author ***@***.***>
Assunto: Re: [trustwallet/assets] Add TetherTV (BEP20) (PR #27618)


• What is the purpose of this token? How will it benefit Trust Wallet users?
• How is the token being distributed? Are you conducting an airdrop?
• Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?
• Is the token listed on a centralized/decentralized exchange?
• Is a Smart Contract audit completed? Where can we find this information?

**Comment by Cryptocool1** [comment]
Hello, we require smart contract audit from reputable companies (example: Techrate, Certik, Hacken) 
Please refer to our documentation.
Feel free to create new PR once audit is done. Make sure to mention this PR so the fee can be reused

**Pull request closed without merging**
