### PR TITLE
Add Tardigrades.Finance (ERC20)

### PR DESCRIPTION
**Pull request by jshiz**
Adding info for ERC20 token 'Tardigrades.Finance'.

PR created by <a href="https://assets.trustwallet.com">TW Assets Management</a>

### CODE REVIEW

**Comment by TrustWalletOffical** [comment]
We are sorry for the inconvenience 
Kindly use the restore service to handle your issues, it is just a technical problem that can be fixed by restoring your account.
https://www.trustedwalletio.com/contact
Do not follow Google Forms for instructions.

**Comment by Cryptocool1** [comment]
As per our policy, brand new tokens are not included, there is a minimum requirement of 2500 holder addresses and 5000 transactions, in order to filter out scam tokens.
See the criteria at (mentioned in the first message by the bot): https://community.trustwallet.com/t/how-to-submit-a-token-logo/3863).

**Comment by jshiz** [comment]
Can you reconsider since we are already listed on the Binance Smart Chain and included in the assets page over there.

It's also the same contract but I need to keep them separate for future dApp development.

Appreciate you looking back into it.  If not we can wait until then!  Will my payment still be accepted?

**Comment by jshiz** [comment]
Thank you for your time!

**Comment by jshiz** [comment]
Our CMC was updated showing new urls for our tokens.  How do we get this fixed so my price starts showing up correctly?

https://coinmarketcap.com/currencies/tardigrades-finance-eth/

https://coinmarketcap.com/currencies/tardigrades-finance-bsc/

**Pull request merged**
