### PR TITLE
TW logo

### PR DESCRIPTION
**Pull request by dogezillacoin**
TW logo

### CODE REVIEW

**Comment by dogezillacoin** [comment]
Prices will also show properly?

**Comment by cryptomanz** [comment]
Hello,
Can your answer some questions?
• What is the purpose of this token? How will it benefit Trust Wallet users?
 • How is the token being distributed? Are you conducting an airdrop?
 • Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?
 • Is the token listed on a centralized/decentralized exchange?
 • Is a Smart Contract audit completed? Where can we find this information?

**Comment by Cryptocool1** [comment]
• What is the purpose of this token? How will it benefit Trust Wallet users?
• How is the token being distributed? Are you conducting an airdrop?
• Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?
• Is the token listed on a centralized/decentralized exchange?
• Is a Smart Contract audit completed? Where can we find this information?

**Comment by dogezillacoin** [comment]
My community is wondering why the logo and price has not yet been updated.

**Comment by dogezillacoin** [comment]
Hello thank you for the logo update. My holders are wondering why price isnt showing? Is this something to do with BSCscan?

**Comment by Cryptocool1** [comment]
You didn’t answer the questions

**Comment by Cryptocool1** [comment]
Please come back to us when the answers will be ready.
When creating a new PR make sure to mention this PR, so that we can see that fee has been paid already here.

**Pull request closed without merging**
