### PR TITLE
Add PresidentDoge logo and info

### PR DESCRIPTION
**Pull request by PresidentDogeCoin**
Please add PresidentDoge logo and info

### CODE REVIEW

**Comment by PresidentDogeCoin** [comment]
Thank you!

**Comment by cryptomanz** [comment]
As per our policy, brand new tokens are not included, there is a minimum requirement of 5000 holder addresses and 10000 transactions, in order to filter out scam tokens.
See the criteria at (mentioned in the first message by the bot): https://community.trustwallet.com/t/how-to-submit-a-token-logo/3863).

**Comment by PresidentDogeCoin** [comment]
hi, wasnt it 2500 holders once?

**Comment by Cryptocool1** [comment]
> hi, wasnt it 2500 holders once?
> […](#)

it was

**Comment by PresidentDogeCoin** [comment]
thank you, i didnt know was 5000 now, otherwise i wouldnt apply.

We gonna be at 5000 in a couple of days, and i will email you.

Thanks for your time

**Comment by cryptomanz** [comment]
please create new PR when all criteria are met
make sure to mention this PR so the fee can be reused

**Comment by PresidentDogeCoin** [comment]
thanks, perfect i will!

Have a lovely sunday

**Pull request closed without merging**
