### PR TITLE
Add ARCANE TOKEN (BEP20)

### PR DESCRIPTION
**Pull request by ye4ever**
Adding info for BEP20 token 'ARCANE TOKEN'.

PR created by <a href="https://assets.trustwallet.com">TW Assets Management</a>

### CODE REVIEW

**Comment by Cryptocool1** [comment]
• What is the purpose of this token? How will it benefit Trust Wallet users?
 • How is the token being distributed? Are you conducting an airdrop?
 • Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?
 • Is the token listed on a centralized/decentralized exchange?
 • Is a Smart Contract audit completed? Where can we find this information?

**Comment by ye4ever** [comment]
• What is the purpose of this token? How will it benefit Trust Wallet users?
Arcane Token is a deflationary Token with solid tokenomics that helps the project to grow healthy and steady,
long term holder get rewarded and we are aiming to be the number 1. NFT Token that will be anchored in this world for a long time.
• How is the token being distributed? Are you conducting an airdrop?
FairLaunch , no airdrop
• Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?
No
• Is the token listed on a centralized/decentralized exchange?
Yes :
bkex
https://www.bkex.com/trade/ARCANE_USDT
pancakeswap
https://pancakeswap.finance/swap?outputCurrency=0x477565b356b3973d16e8cd837c6970613f13e24a
FegEx : https://fegex.com/trade/bsc/0x451721674411d659952525a697a438885ad741f9
• Is a Smart Contract audit completed? Where can we find this information?
Yes :  https://github.com/Tech-Audit/Smart-Contract-Audits/blob/main/TECHAUDIT_ARCANE.pdf

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by ye4ever** [comment]
Hello Team , Is our token meet all your requirements ?

**Comment by ye4ever** [comment]
Hello,
Please open this we will make the payment

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by ye4ever** [comment]
> This PR is being closed due to inactivity. If you wish to continue, please have us reopen the PR before sending your payment, or just create a new one. Do NOT send payments for closed PR, as the fee may by lost!


Kindly reopen it will make the payment today

**Pull request closed without merging**
