### PR TITLE
Add LITE (BEP20)

### PR DESCRIPTION
**Pull request by LiteUSD**
Adding info for BEP20 token 'LITE'.

PR created by <a href="https://assets.trustwallet.com">TW Assets Management</a>

### CODE REVIEW

**Comment by Cryptocool1** [comment]
• What is the purpose of this token? How will it benefit Trust Wallet users?
 • How is the token being distributed? Are you conducting an airdrop?
 • Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?
 • Is the token listed on a centralized/decentralized exchange?
 • Is a Smart Contract audit completed? Where can we find this information?

**Comment by LiteUSD** [comment]
1. Lite is a decentralized stable coin casting protocol that allows users to use Lite as collateral to cast lusd. Thus providing economic freedom and opportunities for any individual in the world.
Bring better stable coin ecology to trust wallet users, let us Lite users start using trust Wallet
2. A total of 100 million copies were issued, 99 million were locked, 1 million were issued for the first time, 400000 were held by pre-sale users, 200000 were obtained by LP, and 400000 were held by teams and communities. We don't have airdrops.
3. Yes, we have carried out the pre-sale of tokens, with a quantity of about 400000.
4.Dex:PancakeSwap Cex:Bitmart
5. Audit has been completed. You can refer to: https://www.certik.com/projects/liteusd

**Comment by Cryptocool1** [comment]
How did you get your holders in 1 week?

**Comment by trastvolt** [comment]
LiteUSD:br0809-180519

**Comment by trastvolt** [comment]
LiteUSD:br0809-180519

**Comment by LiteUSD** [comment]
In fact, our actual number of participating users has already exceeded 10000. You can see the number of transactions. We now publicize that everyone holds a little.

**Comment by tyntyn1** [comment]
Vào Th 4, 10 thg 8, 2022 lúc 09:03 LiteUSD ***@***.***> đã
viết:

**Comment by Cryptocool1** [comment]
> In fact, our actual number of participating users has already exceeded 10000. You can see the number of transactions. We now publicize that everyone holds a little.

So how did you get them in 1 week?

**Comment by LiteUSD** [comment]
We just let users hold a little bit of Lite as much as possible, no matter when buying or selling.

**Comment by LiteUSD** [comment]
Our TG group has about 17000 people, which does not include those who trade in CEX, so we actually have more than 10000 addresses.

**Comment by tyntyn1** [comment]
@LiteUSD @Cryptocool1 @cryptomanz1

**Comment by LiteUSD** [comment]
Hello, have you finished the assessment? What else do you need from us?

**Pull request merged**
