### PR TITLE
Update American Shiba LOGO and Websites (USHIBA) (ERC20)

### PR DESCRIPTION
**Pull request by Oman352**
Adding info for ERC20 token 'American Shiba (USHIBA)'.

PR created by <a href="https://assets.trustwallet.com">TW Assets Management</a>

### CODE REVIEW

**Comment by Oman352** [comment]
Is there any chance we can use the funds we already paid in PR7762? Per:  
"Cryptocool1" commented on May 23, 2021.
Closing PR for now.
Please come back to us when all criteria are met.
When creating a new PR make sure to mention this PR, so that we can see that fee has been paid already here.

**Comment by Cryptocool1** [comment]
hello,
• What is the purpose of this token? How will it benefit Trust Wallet users?
 • How is the token being distributed? Are you conducting an airdrop?
 • Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?
 • Is the token listed on a centralized/decentralized exchange?
 • Is a Smart Contract audit completed? Where can we find this information?

**Comment by Oman352** [comment]
Hello thank you!
   *USHIBA is 100% community-owned. Everyone who holds USHIBA is part of a growing community that believes in decentralization and charity causes. The directions and missions of the community are aimed towards the growing market of NFT dExs, token swap dExs, charitable events, and passive income. On the financial side, USHIBA holders receive a 2% redistribution that comes from each transaction. We are living in a world where inequality and miseries exist. The community considers it a responsibility and an honor to be able to make the world a better place in every way possible. As such, charity works will be one of the main emphases, and will be coordinated often, you can expect that we will collect donations to give to veterans centers, dog shelters, and those in need.
   *The token contract has been live since May with

**Comment by amirziari** [comment]
HELLO
I just had to travel to Turkey and then Iran, and in many places, I saw the scenes of casualties, hunger and death of dogs, and I decided to form a single people of women and animals supporting animals in the same time set up a stray dog ​​shelter that currently needs funding and support from compassionate donors i am coordinating online for the transfer i am the helper and you can also provide financial support in this case with the possibility of online tracking  cost

BEST REGARDS
AMIR

    در یکشنبه 22 اوت 2021 ، 17:58:01 GMT+4: 30 ، عمان 352 ***@***.***> نوشت:  
 
 


سلام متشکرم! 
*USHIBA 100-متعلق به جامعه است. همه کسانی که USHIBA را در اختیار دارند ، بخشی از جامعه رو به رشدی هستند که به تمرکززدایی و امور خیریه اعتقاد دارند. دستورالعمل ها و مأموریت های جامعه به سمت بازار رو به رشد NFT dExs ، مبادله توکنی توکن ، رویدادهای خیریه و درآمد غیرفعال است. از نظر مالی ، دارندگان USHIBA از هر معامله 2٪ توزیع مجدد دریافت می کنند. ما در دنیایی زندگی می کنیم که نابرابری و بدبختی در آن وجود دارد. جامعه مسئولیت و افتخار می داند که بتواند جهان را از هر نظر ممکن به مکان بهتری تبدیل کند. به این ترتیب ، کارهای خیریه یکی از تأکیدهای اصلی خواهد بود و اغلب هماهنگ خواهد شد ، شما می توانید انتظار داشته باشید که ما کمکهای مالی را برای کمک به مراکز جانبازان ، پناهگاه سگها و افراد نیازمند جمع آوری کنیم.
*قرارداد توکن از ماه مه با


- 
این را به دلیل عضویت در این موضوع دریافت می کنید. 
مستقیماً به این ایمیل پاسخ دهید ، آن را در GitHub مشاهده کنید یا اشتراک خود را لغو کنید . 
اعلان های Triage در حال حرکت با GitHub Mobile برای iOS یا Androidبه

**Pull request merged**
