### PR TITLE
Add Position (BEP20)

### PR DESCRIPTION
**Pull request by JustInPosition**
Adding info for BEP20 token 'Position'.

PR created by <a href="https://assets.trustwallet.com">TW Assets Management</a>

### CODE REVIEW

**Comment by cryptomanz** [comment]
hello,
• What is the purpose of this token? How will it benefit Trust Wallet users?
 • How is the token being distributed? Are you conducting an airdrop?
 • Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?
 • Is the token listed on a centralized/decentralized exchange?
 • Is a Smart Contract audit completed? Where can we find this information?

**Comment by JustInPosition** [comment]
> hello,
> • What is the purpose of this token? How will it benefit Trust Wallet users?
> • How is the token being distributed? Are you conducting an airdrop?
> • Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?
> • Is the token listed on a centralized/decentralized exchange?
> • Is a Smart Contract audit completed? Where can we find this information?

Hi there,
The answers following below

**1. What is the purpose of this token? How will it benefit Trust Wallet users?**

This will benefit Trust Wallet by attracting users to the platform and participating in increasing the traded value.

POSI token is the native token of Position Exchange Protocol which provides decentralized trading on Binance Smart Chain.

In contrast with most newly introduced tokens and instead of creating one for crowdfunding purposes and for reducing the trading fees, POSI comes with a different and unique approach. All the fees and revenues from the protocol will be distributed back to all POSI holders by a mechanism called Buy-Back and Burn fully on-chain. This would mean, just by holding POSI you’re a stakeholder and will be able to receive a share from the revenue.

Along with the mentioned, holders also able to increase their POSI balances through the RFI technology just by holding POSI in Trust Wallet.

**2. How is the token being distributed? Are you conducting an airdrop?**
 
Position Exchange is distributing an Airdrop of 1.000.000 USD value to be shared among the total number of participants. The distribution is still ongoing and is divided into phases. We are distributing 10% of the total Airdrop amount on a daily basis during a 10 days period. This will allow us to control the token circulation and stabilize the price.

**3. Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?**

We have conducted an whitelist-sale to launch the POSI token. We have selected randomly 3000 whitelist lottery winners from all the airdrop participants to be eligible to buy POSI at a preferential launch price of $0.5.

**4. Is the token listed on a centralized/decentralized exchange?**

The token is listed and tradable on Pancakeswap and on our website exchange section. We have a plan to expand to more exchanges in the near future. All updates about the subject will be published in our social media channels once completed.

**5. Is a Smart Contract audit completed? Where can we find this information?**

Position Exchange smart contract will be audited by Certik. We have already sent a request and we are proceeding to the audit currently. The report has not been received yet. We will communicate about it in all our social media channels. It will also be available on Certik website.

**Comment by Cryptocool1** [comment]
awaiting for smart contract audit

**Comment by Cryptocool1** [comment]
please create new PR when smart contract audit will be ready.
make sure to mention this PR, so that we can see that fee has been paid already here.

**Comment by JustInPosition** [comment]
I open a new pull request. https://github.com/trustwallet/assets/pull/12742
Please have a look at that

**Pull request closed without merging**
