### PR TITLE
Add Paynshop (BEP20)

### PR DESCRIPTION
**Pull request by deeni**
Adding info for BEP20 token 'Paynshop'.

PR created by <a href="https://assets.trustwallet.com">TW Assets Management</a>

### CODE REVIEW

**Comment by cryptomanz** [comment]
please stop creating new PRs!!
you have already the correct one

**Comment by deeni** [comment]
Please what netxt ?

**Comment by cryptomanz** [comment]
you need to pay for the correct PR

**Comment by deeni** [comment]
Please how much i pay?

**Comment by deeni** [comment]
I sent payment here are attached proved

**Comment by cryptomanz** [comment]
Hello,
- Can't find contract on your website.
Please check/add.

**Comment by deeni** [comment]
can you elaborate more or if you help guide me to add the contract address

**Comment by deeni** [comment]
do you mean our website or yours. if you won't mind please try and clarify that to me

**Comment by cryptomanz** [comment]
you need to add your contract to your website

**Comment by deeni** [comment]
Am added it here are link: https://paynshop.store/#:~:text=0xcb6b5d0562bb2acbd930c3112857e5121a02b522

**Pull request merged**
