### PR TITLE
Add TWT logo and info

### PR DESCRIPTION
**Pull request by TestuyaSaito**
Add TWT logo and info

### CODE REVIEW

**Comment by TestuyaSaito** [comment]
Please help

**Comment by TestuyaSaito** [comment]
Could not retrieve info file; TestuyaSaito/assets/master 0x8d947e7c2ce0ed24a801b2d23bff72d933c842a5, SyntaxError: Unexpected token x in JSON at position 820

What is this

**Comment by ramsty** [comment]
Please create new PR, follow doc https://community.trustwallet.com/t/how-to-submit-a-token-logo/3863
You may want to try our new Assets app in beta; go to https://assets.trustwallet.com, log on with Github, enter contract ID, logo and some additional info, and it will create a PR for you.
See https://community.trustwallet.com/t/how-to-submit-a-token-logo-using-assets-app/82957.

**Comment by tetsuyasaito80** [comment]
Do i needed 25k holders?
We have 5~6k now, 
Thank you.

**Pull request closed without merging**
