### PR TITLE
Add Atari Token Logo

### PR DESCRIPTION
**Pull request by WarMachineAi**

### CODE REVIEW

**Comment by Iamdeadlyz** [comment]
As per our policy, brand new tokens are not included. There is a minimum requirement of 2500 holder addresses and 5000 transactions (airdropped tokens excluded) in order to filter out scam tokens. See the criteria at (mentioned in the first message by the bot): https://community.trustwallet.com/t/how-to-submit-a-token-logo/3863#how-to-get-approved

This token has below-limit usage yet. This pull request will be put on hold. Please come back to us when all criteria are met.
https://etherscan.io/token/0xDCd13da7D48820C2BdB866e31Fe085b56CcbCaF2 (13, 52)

Notes:
- How is this related to ATARI?
- Lacking social media presence
- Team info?

**Comment by WarMachineAi** [comment]
Hi, our token reached to necessary holder amount, please update our logo.

Thanks & Regards

**Comment by Iamdeadlyz** [comment]
Please check my previous response.

**Comment by WarMachineAi** [comment]
ULST token is added by mistake, please update ATRI token logo

**Pull request merged**
