### PR TITLE
Adding Logo and token info for MetaZilla

### PR DESCRIPTION
**Pull request by TheMetaZilla**
Adding Logo and token info for MetaZilla on the binance smart chain network

### CODE REVIEW

**Comment by cryptomanz** [comment]
This is a BEp20 token, correct folder is blockchains/smartchain/assets.
ExplorerUrl incorrect, should be standard https://explorer.binance.org/asset/0x0D4992E48278aA7F7C915f820743d9FaB7FeA713, not https://bscscan.com/token/0x0d4992e48278aa7f7c915f820743d9fab7fea713

**Comment by TheMetaZilla** [comment]
@chefcardano1 everything should be updated now

**Comment by ramsty** [comment]
Hi!
Could you answer some questions?
• What is the purpose of this token? How will it benefit Trust Wallet users?
• How is the token being distributed? Are you conducting an airdrop?
• Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?
• Is the token listed on a centralized/decentralized exchange?
• Is a Smart Contract audit completed? Where can we find this information?

**Comment by TheMetaZilla** [comment]
**- What is the purpose of this token? How will it benefit Trust Wallet users?**
The token will be used to enter into the gaming space. P2E and VR gaming 

**- How is the token being distributed? Are you conducting an airdrop?**
The token was launched with no airdrops

**- Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?**
There was no presale or private sale

**- Is the token listed on a centralized/decentralized exchange?**
The token is available for purchase through pancakeswap. It is listed on CoinMarketCap and CoinGecko, and is tracked by CoinBase

**- Is a Smart Contract audit completed? Where can we find this information?**
We are waiting for Certik to provide an audit of our token. In the meantime we have [this](https://app.marketmove.ai/contract-audit/0x0d4992e48278aa7f7c915f820743d9fab7fea713?c=telegram) audit:

**Comment by Cryptocool1** [comment]
awaiting for smart contract audit from Certik, on hold for now

**Comment by Cryptocool1** [comment]
Feel free to open new PR when smart contract audit will be ready
When creating a new PR make sure to mention this PR, so that we can see that fee has been paid already here.

**Comment by TheMetaZilla** [comment]
Created new pull request #15870 that links to this one

**Pull request closed without merging**
