### PR TITLE
Add files via upload

### PR DESCRIPTION
**Pull request by rubengue**
This PR is being closed due to inactivity. If you wish to continue, please have us reopen the PR before sending your payment.
Do NOT send payments for closed PR, as the fee may by lost!
  (60 vs. 60 hrs)

### CODE REVIEW

**Review by rubengue — COMMENTED** [review]
Hi, I noted that was missing media presence. Sorry

**Comment by rubengue** [comment]
hi updating token name

**Comment by catenocrypt** [comment]
Please remove on of the logo files, `PAIDLogoTrustWallet.png`.

image

**Comment by rubengue** [comment]
Ok Adan. On it

**Comment by catenocrypt** [comment]
Submission looks OK.  Waiting for fee payment.

**Comment by catenocrypt** [comment]
Note that fee has been reduced to 500 TWT (due to TWT appreciation; 6 BNB is not changed).

**Pull request closed without merging**
