### PR TITLE
adding BonusCake

### PR DESCRIPTION
**Pull request by Kwfhwe**
Bonus Cake is the first dividend and lucky draw CAKE reflection token

### CODE REVIEW

**Comment by cryptomanz** [comment]
hello,
• What is the purpose of this token? How will it benefit Trust Wallet users?
• How is the token being distributed? Are you conducting an airdrop?
• Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?
• Is the token listed on a centralized/decentralized exchange?
• Is a Smart Contract audit completed? Where can we find this information?

**Comment by Kwfhwe** [comment]
This token is the token for dividends and winning $cake
The team originally reserved 5.2%, but now only 1.2%, 4% of which has been used for CMC airdrop activities
The team did not sell tokens
Tokens are only listed on pancakeswap
Smart contract audit has been paid like Certik, but it will take two weeks to complete

**Comment by Kwfhwe** [comment]
> 你好，
> • 这个令牌的目的是什么？它将如何使 Trust Wallet 用户受益？
> • 代币是如何分配的？你在进行空投吗？
> • 您是否在首次代币发行 (ICO) 或代币预售中出售了代币？
> • 代币是否在中心化/去中心化交易所上市？
> • 智能合约审计是否完成？我们在哪里可以找到这些信息？

This token is the token for dividends and winning $cake
The team originally reserved 5.2%, but now only 1.2%, 4% of which has been used for CMC airdrop activities
The team did not sell tokens
Tokens are only listed on pancakeswap
Smart contract audit has been paid like Certik, but it will take two weeks to complete

**Comment by Kwfhwe** [comment]
> hello,
> • What is the purpose of this token? How will it benefit Trust Wallet users?
> • How is the token being distributed? Are you conducting an airdrop?
> • Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?
> • Is the token listed on a centralized/decentralized exchange?
> • Is a Smart Contract audit completed? Where can we find this information?

This token is the token for dividends and winning $cake
The team originally reserved 5.2%, but now only 1.2%, 4% of which has been used for CMC airdrop activities
The team did not sell tokens
Tokens are only listed on pancakeswap
Smart contract audit has been paid like Certik, but it will take two weeks to complete

**Comment by cryptomanz** [comment]
- Awaiting for smart contract audit.

**Comment by Cryptocool1** [comment]
please create new PR, when smart contract audit will be ready. Make sure to mention this PR, so the fee can be reused.

**Pull request closed without merging**
