### PR TITLE
Add tits

### PR DESCRIPTION
**Pull request by pinpong**

### CODE REVIEW

**Comment by catenocrypt** [comment]
As per our policy, brand new tokens are not included, there is a minimum requirement of 2500 holder addresses and 5000 transactions, in order to filter out scam tokens.
See the criteria at (mentioned in the first message by the bot): https://community.trustwallet.com/t/how-to-submit-a-token-logo/3863).
This token has no real usage yet (9 holder addresses). Putting PR on hold for now. Please come back to us when all criteria are met.  Multi-chain and staking tokens may get special treatment, let us know if this is the case. 

https://bscscan.com/token/0xDdA599BD9E11D0b33f3DE5CD8Ee5600fD85716f1

**Comment by pinpong** [comment]
@catenocrypt checkout https://www.tinytitans.fi/#/

You need this token to mint a unique titan, battle and buy powerups.

**Comment by pinpong** [comment]
@catenocrypt ?

**Comment by vikmeup** [comment]
As per our updated policy, brand new tokens are not included, there is a minimum requirement 

- at least 2500 token holders
- at least 500 transactions

See our [How to Get Submit Token Logo ](https://community.trustwallet.com/t/how-to-submit-a-token-logo/3863#how-to-get-approved) guidelines.

Feel free to re-open pull request once you meet those requirements.

**Pull request closed without merging**
