### PR TITLE
add clifford inu

### PR DESCRIPTION
**Pull request by ynnex1**

### CODE REVIEW

**Comment by ynnex1** [comment]
audited: https://www.certik.com/projects/cliffordinu

**Review by Imanmahmoodi — APPROVED** [review]
Iman

**Comment by ramsty** [comment]
Awaiting for smart contract audit. On hold for now.

**Comment by ynnex1** [comment]
@ramsty smart contract already audited:
https://www.certik.com/projects/cliffordinu

**Comment by ramsty** [comment]
It's in progress
Снимок экрана 2022-01-02 в 21 35 59

> @ramsty smart contract already audited: https://www.certik.com/projects/cliffordinu

**Comment by Cryptocool1** [comment]
please come back to us when all criteria are met

**Comment by ynnex1** [comment]
https://www.certik.com/projects/cliffordinu
audit is live :)

**Comment by ynnex1** [comment]
@Cryptocool1

**Comment by ynnex1** [comment]
?

**Comment by Cryptocool1** [comment]
You are not allowed delete any tokens in your PR, Please create new PR

**Pull request closed without merging**
