### PR TITLE
Add PolkaMonster (BEP20)

### PR DESCRIPTION
**Pull request by polkamonsterBSC**
Adding info for BEP20 token 'PolkaMonster'.

PR created by <a href="https://assets.trustwallet.com">TW Assets Management</a>

### CODE REVIEW

**Comment by polkamonsterBSC** [comment]
Let me know if everything is ready to upload the logo for my project

**Comment by polkamonsterBSC** [comment]
https://explorer.binance.org/tx/A1995F1E82374D5C9F380732528679C560B6E6AC172017DB987F3E943C60553B

I sent the payment

**Comment by cryptomanz** [comment]
Hello,
Can your answer some questions?
 • What is the purpose of this token? How will it benefit Trust Wallet users?
 • How is the token being distributed? Are you conducting an airdrop?
 • Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?
 • Is the token listed on a centralized/decentralized exchange?
 • Is a Smart Contract audit completed? Where can we find this information?

**Comment by polkamonsterBSC** [comment]
> Hello,
> Can your answer some questions?
> • What is the purpose of this token? How will it benefit Trust Wallet users?
> • How is the token being distributed? Are you conducting an airdrop?
> • Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?
> • Is the token listed on a centralized/decentralized exchange?
> • Is a Smart Contract audit completed? Where can we find this information?

> •  PKMon Token is used to participate and earn money from the game Polkamonster, game players will be updated with the price of the token on Trustwallet every day because most game players use Trust wallets.

> •  Token is allocated as follows:

👾Polkamonster Token

📇 Name: Polkamonster
💮 Symbol: PKMON18
🗃 Max Supply: 1,000,000,000
👮🏻‍♀️ Audit: https://solidity.finance/audits/PolkaMonster/

Tokenomics
Developers: 8% (locked for 1 year)
Marketing & advisors: 2%
Play to earn: 45%
- Training: 15%
- Monster Battle: 15%
- Combat : 15%
Private sale: 5%
Public sale : 24%
Liquidity: 16% lock for 6 months

> •  We have sold ILO on Unicrypt.network
> •  We have listed PancakeSwap
https://pancakeswap.finance/swap#/swap?inputCurrency=BNB&outputCurrency=0x609D183Fb91a0fce59550b62ab7d2c931b0Bb1BE
> • Audit: https://solidity.finance/audits/PolkaMonster/

**Pull request merged**
