### PR TITLE
Add Bunicorn token (BUNI) info and logo

### PR DESCRIPTION
**Pull request by hansolobuni**

### CODE REVIEW

**Comment by cryptomanz** [comment]
Hello,
Can your answer some questions?
 • What is the purpose of this token? How will it benefit Trust Wallet users?
 • How is the token being distributed? Are you conducting an airdrop?
 • Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?
 • Is the token listed on a centralized/decentralized exchange?
 • Is a Smart Contract audit completed? Where can we find this information?

**Comment by hansolobuni** [comment]
hi @cryptomanz 
• What is the purpose of this token? How will it benefit Trust Wallet users?
This is the governance token of the https://bunicorn.exchange DEX. We have integrated trust wallet to our DEX as well and many users are asking for BUNI token in TrustWallet.

• How is the token being distributed? Are you conducting an airdrop?
The token is being distributed via IDO token sales.

• Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?
We conduct a dual IDO in Redkite and Poolz.

• Is the token listed on a centralized/decentralized exchange?
The BUNI token is being listed in Pancakeswap and our own https://bunicorn.exchange website.

• Is a Smart Contract audit completed? Where can we find this information?
It's been audited by hacken.io. Please check BuniToken.sol in this report: https://hacken.io/wp-content/uploads/2021/05/Bunicorndefi_03052021_SC_Audit_2Report.pdf


> Hello,
> Can your answer some questions?
> • What is the purpose of this token? How will it benefit Trust Wallet users?
> • How is the token being distributed? Are you conducting an airdrop?
> • Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?
> • Is the token listed on a centralized/decentralized exchange?
> • Is a Smart Contract audit completed? Where can we find this information?

**Comment by Cryptocool1** [comment]
hello, 
your background should be transparent
please correct

**Comment by hansolobuni** [comment]
> hello,
> your background should be transparent
> please correct

thank you, I edited the logo

**Pull request merged**
