### PR TITLE
Add $CRDN logo and info

### PR DESCRIPTION
**Pull request by hanzalaCardence**
This is to add $CRDN logo and info.

### CODE REVIEW

**Comment by cryptomanz** [comment]
Hello,
Can your answer some questions?
• What is the purpose of this token? How will it benefit Trust Wallet users?
• How is the token being distributed? Are you conducting an airdrop?
• Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?
• Is the token listed on a centralized/decentralized exchange?
• Is a Smart Contract audit completed? Where can we find this information?

**Comment by hanzalaCardence** [comment]
_What is the purpose of this token? How will it benefit Trust Wallet users?_

Cardence is a launchpad for new projects on Cardano platform creating a trustless fund raising ecosystem for carefully vetted Cardano projects.
It consists:
->Decentralized presale platform
->Token locker
->Smart Mint
->Certified Presales
Trust wallet users can benefit from the above mentioned features.
For more details, you can see our [documentation](https://docs.cardence.io)

_How is the token being distributed? Are you conducting an airdrop?_

- We conducted airdrop around 3 months before.

_Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?_

- Yes, we have done presale.

_Is the token listed on a centralized/decentralized exchange?_

- Yes. CEXs include Bitmart, Indoex, Latoken and Dextrade. As for DEX, we are only listed on pancakeswap.

Is a Smart Contract audit completed? Where can we find this information?

- We have been audited by Techrate. [Link](https://github.com/TechRate/Smart-Contract-Audits/blob/main/Cardence%20Full%20Smart%20Contract%20Security%20Audit.pdf)

**Comment by hanzalaCardence** [comment]
_What is the purpose of this token? How will it benefit Trust Wallet users?_
Cardence is a launchpad for new projects on Cardano platform creating a trustless fund raising ecosystem for carefully vetted Cardano projects.
It consists:
->Decentralized presale platform
->Token locker
->Smart Mint
->Certified Presales
Trust wallet users can benefit from the above mentioned features.
For more details, you can see our [documentation](https://docs.cardence.io/)

_How is the token being distributed? Are you conducting an airdrop?_
Token Distribution can be seen here ([Link](https://docs.cardence.io/tokenomics/distribution)). We conducted airdrop around 3 months before.

_Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?_
Yes, we have done presale.

_Is the token listed on a centralized/decentralized exchange?_
Yes. CEXs include Bitmart, Indoex, Latoken and Dextrade. As for DEX, we are only listed on pancakeswap.

_Is a Smart Contract audit completed? Where can we find this information?_
We have been audited by Techrate. [Link](https://github.com/TechRate/Smart-Contract-Audits/blob/main/Cardence%20Full%20Smart%20Contract%20Security%20Audit.pdf)

**Comment by Cryptocool1** [comment]
According to our documentation token image needs to be full screen

**Comment by hanzalaCardence** [comment]
It's size is already 256X256 and transparent. Please explain what do you mean by fullscreen?

**Comment by cryptomanz** [comment]
According to our documentation token image needs to be full screen, here is link to guidelines details and an example of token images https://community.trustwallet.com/t/how-to-submit-a-token-logo/3863

**Comment by hanzalaCardence** [comment]
Will this image work? This is the logo of our token. The size is 256 X 256. 
logo

**Pull request merged**
