### PR TITLE
Add Vesta

### PR DESCRIPTION
**Pull request by Ox531**

### CODE REVIEW

**Comment by catenocrypt** [comment]
As per our policy, brand new tokens are not included, there is a minimum requirement of 100 holder addresses and 500 transactions, in order to filter out scam tokens.
See https://community.trustwallet.com/t/how-to-submit-a-token-logo/3863#how-to-get-approved
This token has no usage, rejecting.  PR can be reopened when all criteria are met.

**Comment by Ox531** [comment]
See https://etherscan.io/token/0x3AeF8e803BD9be47e69b9f36487748d30D940b96
415 holder addresses and 2836 transactions

**Comment by Ox531** [comment]
Sorry, wrong explorer address in the `info.json`

**Comment by Ox531** [comment]
`info.json` updated, please review.

**Comment by Ox531** [comment]
Please see https://github.com/Ox531/assets/commit/98892bd4f80d0c4ba58a6cc19280fb50c12af3a8

**Comment by catenocrypt** [comment]
Indeed wrong address in `info.json`. and also in the folder names!
`0xC012A28a08c34dfF845D1e7851831D55bb165a61` instead of `0x3AeF8e803BD9be47e69b9f36487748d30D940b96`.
Shall I change for you?

**Comment by Ox531** [comment]
> Indeed wrong address in `info.json`. and also in the folder names!
> `0xC012A28a08c34dfF845D1e7851831D55bb165a61` instead of `0x3AeF8e803BD9be47e69b9f36487748d30D940b96`.
> Shall I change for you?

Folder name has been changed, please review.
Thank you!

**Comment by catenocrypt** [comment]
All right, all looks OK.
One comment though:  logo looks a bit too faded on dark background (dark mode).  It's acceptable like this but you may consider adding a light contour.

image

**Comment by Ox531** [comment]
New `logo.png` is on its way, please hold on !

**Comment by Ox531** [comment]
Done! Please review.

**Pull request merged**
