### PR TITLE
Please Add Both Stable Coin on Trust Wallet

### PR DESCRIPTION
**Pull request by ghost**
logo

### CODE REVIEW

**Comment by kolya182** [comment]
What is the use of this coin ?

**Comment by SaAtHi-SaAtHi** [comment]
Tether DeFi (USDD) is called a stablecoin because it was originally designed to always be worth $1.00, maintaining $1.00 in reserves for each tether issued. Nevertheless, Tether Limited states that owners of tethers have no contractual right, other legal claims, or guarantee that tethers will be redeemed or exchanged for dollars.

**Comment by SaAtHi-SaAtHi** [comment]
@kolya182 

How many can be added using a single Github Account?

**Comment by kolya182** [comment]
> @kolya182
> 
> How many can be added using a single Github Account?

You can add as many you want, unless coins legit. Where i ca read more about this coin ?

**Comment by SaAtHi-SaAtHi** [comment]
> > @kolya182
> > How many can be added using a single Github Account?
> 
> You can add as many you want, unless coins legit. Where i ca read more about this coin ?

This Coin is just like USD Tether...
And website is PENDING...

**Comment by SaAtHi-SaAtHi** [comment]
@kolya182 

Sir,
I'm Token Developer. Working on Fiverr...
Maybe I need your more help...
Please add me on Telegram @Mzn_Rahi

**Comment by SaAtHi-SaAtHi** [comment]
> > @kolya182
> You can add as many you want, unless coins legit. Where i ca read more about this coin ?

Maybe this will help you

https://en.cryptonomist.ch/2020/03/10/defi-new-partnership-tether-aave/

**Comment by SaAtHi-SaAtHi** [comment]
Please Add WWW (World Wide Web Coin)...
WWW is a Stable Coin which want to sell Internet throughout the world.
Backed stablecoins are subject to the same volatility and risk associated with the backing asset. If the backed stablecoin is backed in a decentralized manner, then they are relatively safe from predation, but if there is a central vault, they may be robbed, of suffer loss of confidence.

**Comment by SaAtHi-SaAtHi** [comment]
logo

**Comment by SaAtHi-SaAtHi** [comment]
logo


Please Add WWW (World Wide Web Coin)...
WWW is a Stable Coin which want to sell Internet throughout the world.
Backed stablecoins are subject to the same volatility and risk associated with the backing asset. If the backed stablecoin is backed in a decentralized manner, then they are relatively safe from predation, but if there is a central vault, they may be robbed, of suffer loss of confidence.

**Comment by SaAtHi-SaAtHi** [comment]
@kolya182 

Please Add WWW (World Wide Web Coin)...
WWW is a Stable Coin which want to sell Internet throughout the world.
Backed stablecoins are subject to the same volatility and risk associated with the backing asset. If the backed stablecoin is backed in a decentralized manner, then they are relatively safe from predation, but if there is a central vault, they may be robbed, of suffer loss of confidence.

**Comment by MznRahi** [comment]
@kolya182  Please help me to Add on Trust Wallet

**Pull request closed without merging**
