### PR TITLE
Add DARC-087 (BEP-2) and DARC (BEP-20) and remove DARC-24B (BEP-2)

### PR DESCRIPTION
**Pull request by bombs-kim**
#14978 (Fee has been paid already)
#15059 (second request)

We recently decided to renew the existing BEP-2 token and issue new BEP-20.

For details please refer to the post below.
https://medium.com/@konstellation/konstellation-darcwallet-check-darc-airdrop-alert-20928765b212

For further inquiry or verification,
please contact Info@konstellation.tech

This is the official announcement about abandoning DARC-24B.
https://konstellation.medium.com/announcement-support-for-darc-24b-has-ended-aaa34fb4b575

### CODE REVIEW

**Comment by bombs-kim** [comment]
@Cryptocool1
Please note that I've already paid the fee.

**Comment by bombs-kim** [comment]
@Cryptocool1 I cannot see BSC logo in my Binance wallet. Do you why it isn't displayed?
(our Binance Chain logo is displayed in Binance wallet, only BSC one is not displayed)

**Comment by Cryptocool1** [comment]
CB73D766-2D00-4397-8502-617207275133

**Comment by bombs-kim** [comment]
@Cryptocool1 not in my Binance wallet 🥲
image

**Comment by bombs-kim** [comment]
@Cryptocool1 Am I not supposed to expect that BEP-20 logo is not displayed in Binance wallet? I paid for the fee for it and need clarification.

**Comment by Cryptocool1** [comment]
It is displayed

**Comment by Cryptocool1** [comment]
In trust wallet

**Pull request merged**
