### PR TITLE
ATOS - -Token logo and information submission

### PR DESCRIPTION
**Pull request by Dictators**
This PR is being closed due to inactivity. If you wish to continue, please have us reopen the PR before sending your payment.
Do NOT send payments for closed PR, as the fee may by lost!
  (60 vs. 60 hrs)

### CODE REVIEW

**Comment by catenocrypt** [comment]
Token submission looks OK, waiting for fee payment.

**Comment by Dictators** [comment]
@catenocrypt I'm sorry, it was closed when I paid the fee. Is there any way to solve this problem

**Comment by catenocrypt** [comment]
Fee paid for this PR, but considering for #4541 .  Closing this.

**Pull request closed without merging**
