### PR TITLE
Add CryptoCars (BEP20)

### PR DESCRIPTION
**Pull request by nhuanvolter**
Adding info for BEP20 token 'CryptoCars'.

PR created by <a href="https://assets.trustwallet.com">TW Assets Management</a>

### CODE REVIEW

**Comment by nhuanvolter** [comment]
Hello, I already paid PR #13232. I want to update logo for CCAR token.

**Comment by nhuanvolter** [comment]
@Cryptocool1 hello, please help me update logo for CCAR token. Contract: 0x50332bdca94673f33401776365b66cc4e81ac81d
I don't want add new token.

**Comment by Cryptocool1** [comment]
> @Cryptocool1 hello, please help me update logo for CCAR token. Contract: 0x50332bdca94673f33401776365b66cc4e81ac81d
> I don't want add new token.

Don’t think, your token is already on TW

**Comment by Cryptocool1** [comment]
233E5C34-8EED-42E5-94F1-A5C81F3A432A

**Comment by Cryptocool1** [comment]
65D8FC4B-9A47-4C8D-A485-31E3B10D032F

**Comment by nhuanvolter** [comment]
When will it be listed with logo? Anything I need to complete or just wait?

**Comment by Cryptocool1** [comment]
hello,
• What is the purpose of this token? How will it benefit Trust Wallet users?
 • How is the token being distributed? Are you conducting an airdrop?
 • Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?
 • Is the token listed on a centralized/decentralized exchange?
 • Is a Smart Contract audit completed? Where can we find this information?

**Comment by nhuanvolter** [comment]
Hello,

• What is the purpose of this token? How will it benefit Trust Wallet users?
- CCAR is used for payments and rewards in the game CryptoCars. Trust Wallet users will be able to store CCAR tokens and trade on DEXs.

• How are tokens distributed? Are you conducting an airdrop?
- We distribute tokens through in-game rewards.

• Did you sell tokens at Initial Coin Offering (ICO) or pre-sell tokens?
- We presale 4M tokens on DxSale on August 28, 2021.

• Is the token listed on a centralized/decentralized exchange?
- We have listed 8M tokens on PancakeSwap.

• Check Smart Contract Completed? Where can we find this information?
- Yes, our Smart Contract has been audited by TechAudit. Here is the document file: https://cryptocars.me/TECHAUDIT_CRYPTOCARS.pdf

**Pull request merged**
