### PR TITLE
Please add logo to Trust

### PR DESCRIPTION
**Pull request by trubadger**
Please add logo to Trust. 

@cryptocool @cryptomanz

Please apply payment with memo 1110 to this request.

We are pretty sure this file will work now. We have already paid with memo 1110 that has never been applied to a PR:

https://explorer.binance.org/tx/5B3AEE89F6697B096A7FE232D945D0A7218A8FCABB8E873511CCF318FCCAFE5C

Please find this payment and apply to this request so we can get this accomplished successfully.

### CODE REVIEW

**Comment by trubadger** [comment]
We paid early on 1000 TWT with Memo 1110. Please apply that payment to this. We have been in communication about this in Telegram.

@cryptocool @cryptomanz

Please apply payment with memo 1110 to this request.
IMG_4450 (1)

https://explorer.binance.org/tx/5B3AEE89F6697B096A7FE232D945D0A7218A8FCABB8E873511CCF318FCCAFE5C

Please find this payment and apply to this request so we can get this accomplished successfully.

**Comment by cryptomanz** [comment]
Hello,
- As per our policy, brand new tokens are not included, there is a minimum requirement of 5000 holder addresses and 10000 transactions, in order to filter out scam tokens.
See the criteria at (mentioned in the first message by the bot): https://community.trustwallet.com/t/how-to-submit-a-token-logo/3863).

**Comment by RebelByCause** [comment]
Hi @cryptomanz, when we applied last week the min holders was 2500 and transactions was 5000. We are a verified token on bsc scan, with a fully doxxed team. Did the rules change this week?

**Comment by trubadger** [comment]
@cryptomanz

Thanks for your response. We applied some time ago now. The initial request was submitted on 6/30 for this toke. The guidelines/criteria at the moment of application were to have min 2500 holders and 5000 transactions. We double-checked before submitting the application and because we fulfilled those, we applied and paid, now they are changed?

We are a verified token on BscScan and CoinGecko. We have a fully doxxed team with credentials on our website. We have a Deerlock rugpull free certificate and are fully audited by Techrate because of legitimacy.

Can you please review our PR.

Again we have already paid for this request and have submitted multiple after feedback.

Thanks in advance.

**Comment by trubadger** [comment]
@cryptomanz

Listing on Trustwallet will benefit our current and future holders with our brand name and information and soon the tracking price will reflect also.

+ BSC Verified token

https://bscscan.com/token/0xc003F5193CABE3a6cbB56948dFeaAE2276a6AA5E#balances

+ Coingecko tracked

https://www.coingecko.com/nl/coins/trubadger

+ Deerlock Security Certificate

https://www.deerlock.com/trubager

+ Techrate Smart Contract Audit

https://github.com/TechRate/Smart-Contract-Audits

+ Listed on Decentralised Exchange

https://pancakeswap.info/token/0xc003f5193cabe3a6cbb56948dfeaae2276a6aa5e

+ Liquidity

$1,68M Locked

+ Press releases

https://www.msn.com/en-us/money/personalfinance/ceo-discusses-launch-of-trubadger-a-deflationary-and-reflection-defi-token/ar-AALhGA9

https://thepressfree.com/trubadger-token-apporte-la-crypto-monnaie-aux-masses/

https://www.finstream.tv/videos/crypto-currency/this-week-in-crypto-trubadger/

https://www.einnews.com/amp/pr_news/545035233/trubadger-token-brings-cryptocurrency-to-the-masses

https://www.thestreet.com/retirement-daily/.amp/your-money/the-ceo-of-trubadger-discusses-the-launch-of-a-deflationary-and-reflection-defi-token

Token was distributed with a small prelaunch performed on our own exchange Catabolt Swap. After the prelaunch token went live on PancakeSwap

+ CoinMarketCap

Submitted, pending approval
(Timeframe 1-3 weeks)

+ Centralized Exchanges
Week 29 July (1-2 weeks)

**Comment by Cryptocool1** [comment]
Hello,
please create new PR when CMC listing will be ready.
make sure to mention this PR, so that we can see that fee has been paid already here.

**Comment by trubadger** [comment]
Hello. We were put on CMC and submitted a new request #11816 as instructed and referenced this one #11543. Can you please help me understand why #11816 was closed without the logo being added?
  
  
   
  
  
   
    On 07/13/2021 3:04 AM Nazar ***@***.***> wrote:
   
   
    
   
   
    
   
   
   Hello,
   
    awaiting for CMC listing.

**Pull request closed without merging**
