### PR TITLE
XinFin XDC Network Added.

### PR DESCRIPTION
**Pull request by AnilChinchawale**

### CODE REVIEW

**Comment by AnilChinchawale** [comment]
I have transfer for first PR #1853 which was closed without any reason.

**Comment by kolya182** [comment]
> I have transfer for first PR #1853 which was closed without any reason.

It was unpaid

**Comment by AnilChinchawale** [comment]
Hello,

I would like to know when XinFin XDC Network will listed on Trust wallet to transfer XDC.

**Comment by kolya182** [comment]
> Hello,
> 
> I would like to know when XinFin XDC Network will listed on Trust wallet to transfer XDC.

Listing requirementshttps://developer.trustwallet.com/wallet-core/newblockchain

**Pull request merged**
