### PR TITLE
Add Lunar (BEP20)

### PR DESCRIPTION
**Pull request by LunarLegionBsc**
Adding info for BEP20 token 'Lunar'.

PR created by <a href="https://assets.trustwallet.com">TW Assets Management</a>

### CODE REVIEW

**Comment by LunarLegionBsc** [comment]
Hello, we have already paid from our previous application , https://github.com/trustwallet/assets/pull/15841 . I know we are under the 25k holders requirement, but I also see that every token is up to individual evaluation. I believe the growth and legitimacy of our project speaks for itself and warrants a logo. Please let me know if you would like me to provide any additional information, we are audited and KYC verified as well. https://dessertswap.finance/audits/Lunar%20Defi%20BSC%20Audit%2012182757.pdf

**Review by oluwa121 — APPROVED** [review]
Wowww i love this

**Comment by LunarLegionBsc** [comment]
Thank you so much! The team is working extremely hard, the past month has been an amazing ride.

**Comment by LunarLegionBsc** [comment]
I just wanted to make sure this is seen, so I'll send it again and leave it as the most recent message! 

Hello, we have already paid from our previous application , #15841 . I know we are under the 25k holders requirement, but I also see that every token is up to individual evaluation. I believe the growth and legitimacy of our project speaks for itself and warrants a logo. Please let me know if you would like me to provide any additional information, we are audited and KYC verified as well. https://dessertswap.finance/audits/Lunar%20Defi%20BSC%20Audit%2012182757.pdf

**Comment by cryptomanz** [comment]
• What is the purpose of this token? How will it benefit Trust Wallet users?
 • How is the token being distributed? Are you conducting an airdrop?
 • Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?
 • Is the token listed on a centralized/decentralized exchange?

**Comment by LunarLegionBsc** [comment]
Lunar is a DeFi ecosystem revolutionizing the way we interface with crypto. We're replacing the 10 separate tools needed to trade crypto with a single, intuitive platform that will let you trade tokens and NFTs across different blockchains in a single click. 
The token is currently being distributed via purchasing on any BSC Dex, we have not done any airdrops or anything of the sort. 
The token had a 1000 BNB presale on pinksale which sold out in less than 15 seconds.
We are listed on any BSC Dex and we have also applied to 5 major CEX's and are either currently in discussion with them or awaiting approval.

**Comment by LunarLegionBsc** [comment]
Hello I need to update our logo, what is the best way to do so?

**Comment by LunarLegionBsc** [comment]
@cryptomanz @oluwa121 @Cryptocool1 @hexorx

**Comment by dublt696** [comment]
Hey so I am following along and really into this but the last hour my kids
have been GNG crypto and it's midnight they should b n bed.. so I am gonna
pick up tomorrow what ever I am supposed to send or extract .. we will pick
up tomorrow k guya

M. BREWER

**Pull request merged**
