### PR TITLE
Add DXCT Token

### PR DESCRIPTION
**Pull request by ghost**
add DXCT Token

### CODE REVIEW

**Comment by cryptodoge77** [comment]
• What is the purpose of this token? How will it benefit Trust Wallet users?
DNAxCAT Token(DXCT) is the governance currency of DNAxCAT Metaverse. It will be used for trading, exchanging and breeding warriors cats in the game. DNAxCAT creates a digital cat pet world where players can raise and breed varies of cute cats and fight shoulder to shoulder in the adventure world with your cats.
DNAxCAT now has over 6,000 holders within 36 hours since launch. Trust Wallet users can easily trade $DXCT with Trust Wallet if get listed.

• How is the token being distributed? Are you conducting an airdrop?
No airdrop is ongoing.

• Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?
No.

• Is the token listed on a centralized/decentralized exchange?
Yes. PancakeSwap, Hotbit, ZT Global, Bilaxy.

• Is a Smart Contract audit completed? Where can we find this information?
Smart Contract audit is in progress and will complete recently.

**Comment by Cryptocool1** [comment]
can you please add links to your PR?
example: https://developer.trustwallet.com/add_new_asset/repository_details

**Comment by cryptomanz** [comment]
Hello,
Awaiting for smart contract audit.

**Comment by jojoprotocal** [comment]
smart contract audit :   https://www.certik.org/projects/dnaxcat

**Comment by cryptodoge77** [comment]
Audit Report:  https://www.certik.org/projects/dnaxcat

Git Code Update: https://github.com/DNAxCAT/DXCT-Core/blob/main/Audit/REP-DNAxCAT-Audit.pdf

**Pull request merged**
