### PR TITLE
Add Astronautas Token (BEP20)

### PR DESCRIPTION
**Pull request by luisfelp**
Adding info for BEP20 token 'Astronautas Token'.

PR created by <a href="https://assets.trustwallet.com">TW Assets Management</a>

### CODE REVIEW

**Comment by luisfelp** [comment]
What's wrong guys, could you help me?

**Comment by catenocrypt** [comment]
Minor correction needed:  Please make description field shorter.

    XXX   'Description too long, 715, /home/runner/work/assets/assets/blockchains/smartchain/assets/0x3835943D4013EF994E3062E6049D2a7415DaFf9e/info.json'

**Comment by luisfelp** [comment]
Done!

**Comment by luisfelp** [comment]
I just realized that we need 2500 holders. We will be there soon but not yet. I will wait!

**Comment by catenocrypt** [comment]
Closing for now.  Please ping us when circulation requirement is satisfied (currently around 1000 holders).

**Pull request closed without merging**
