### PR TITLE
Add Wootrade Network (BEP20)

### PR DESCRIPTION
**Pull request by wootradexulong**
Adding info for BEP20 token 'Wootrade Network'.

PR created by <a href="https://assets.trustwallet.com">TW Assets Management</a>

### CODE REVIEW

**Comment by cryptomanz** [comment]
As per our policy, brand new tokens are not included, there is a minimum requirement of 2500 holder addresses and 5000 transactions, in order to filter out scam tokens.
See the criteria at (mentioned in the first message by the bot): https://community.trustwallet.com/t/how-to-submit-a-token-logo/3863).
Closing PR for now. Please come back to us when all criteria are met.

**Comment by wootradexulong** [comment]
bep20 woo token is bridged from ethereum. where we have 9199 holders and 149k tx. and woo token is listed on pancakeswap farm. https://etherscan.io/token/0x4691937a7508860f876c9c0a2a617e7d9e945d4b

**Comment by kevinwootrade** [comment]
> As per our policy, brand new tokens are not included, there is a minimum requirement of 2500 holder addresses and 5000 transactions, in order to filter out scam tokens.
> See the criteria at (mentioned in the first message by the bot): https://community.trustwallet.com/t/how-to-submit-a-token-logo/3863).
> Closing PR for now. Please come back to us when all criteria are met.

Hi the BEP20 WOO token now has met the criteria (2793 holder addresses and 50,106 transactions), see the link: https://bscscan.com/token/0x4691937a7508860f876c9c0a2a617e7d9e945d4b

could you please process our request?  Thanks

**Comment by kevinwootrade** [comment]
Bep20 woo token now has 5024 holders and 106,658 tx. can you please add to the token list? https://bscscan.com/token/0x4691937a7508860f876c9c0a2a617e7d9e945d4b

**Pull request closed without merging**
