### PR TITLE
Galaxium

### PR DESCRIPTION
**Pull request by FlingAvalon**

### CODE REVIEW

**Comment by Cryptocool1** [comment]
remove this file please: blockchains/tron/assets/TWXZxJDGWVhNz2SXx31kQGA5kb2cjAz9ys/info.json

**Comment by FlingAvalon** [comment]
done
please merge logo to this address "0x67e8954493dcf031243a3498da73c167eda512d4"

**Comment by FlingAvalon** [comment]
logo

**Comment by catenocrypt** [comment]
We evaluate only correct pull requests.  Any serious project is expected to have the expertise to create a logo and valid json in the right location.

**Comment by FlingAvalon** [comment]
This was a mistake. 
I accidentally dropped two folders and I have deleted the wrong json file. Please Merge

**Comment by FlingAvalon** [comment]
Hello! No response yet. 

Please merge, the error json file has been deleted

**Pull request merged**
