### PR TITLE
we want to change our logo.png. thanks

### PR DESCRIPTION
**Pull request by tokau-project**
we want to change our logo.png. thanks

### CODE REVIEW

**Comment by tokau-project** [comment]
we want change our logo.png, thanks

**Comment by tokau-project** [comment]
can you help me? wo have done all the thing success(send bnb, we have finish the contract audit. https://www.certik.org/projects/tokau),but now we want to update our logo

**Comment by tokau-project** [comment]
previous pull is https://github.com/trustwallet/assets/pull/13478

**Comment by Cryptocool1** [comment]
submission looks good. awaiting for fee payment

**Pull request closed without merging**
