### PR TITLE
added HumanCharityCoin info

### PR DESCRIPTION
**Pull request by CryptoLover705**

### CODE REVIEW

**Comment by CryptoLover705** [comment]
didn't mean to close the pull request

**Comment by Cryptocool1** [comment]
hello
your files naming is wrong

**Comment by CryptoLover705** [comment]
Oh, What should it be?

**Comment by Cryptocool1** [comment]
> Oh, What should it be?

Please follow  documentation  https://community.trustwallet.com/t/how-to-add-the-token-information/3888 in order to correct your mistakes

**Comment by CryptoLover705** [comment]
Hey it made me create a new pull request https://github.com/trustwallet/assets/pull/7418

**Comment by catenocrypt** [comment]
Payment considered to #7418, closing this.

**Pull request closed without merging**
