### PR TITLE
Add INVEST (BEP20)

### PR DESCRIPTION
**Pull request by investdex**

### CODE REVIEW

**Comment by cryptomanz** [comment]
Hello,
- cannot contract on your website.

**Comment by investdex** [comment]
Please provide a whitelist for trustwallet. IP or domain for us to add in our firewall.

**Comment by Cryptocool1** [comment]
> Please provide a whitelist for trustwallet. IP or domain for us to add in our firewall.

Please add your contract to your website.

**Comment by investdex** [comment]
https://investdex.io/pancakeswap/pair-explorer/0x2b43a6cee2356ccb5027c019c79fced1a0e2d7cf

**Comment by Cryptocool1** [comment]
> https://investdex.io/pancakeswap/pair-explorer/0x2b43a6cee2356ccb5027c019c79fced1a0e2d7cf

Thanks

**Comment by investdex** [comment]
Great

**Comment by investdex** [comment]
How long will it take to appear?

**Pull request merged**
