### PR TITLE
Adds zoo token to trust wallet

### PR DESCRIPTION
**Pull request by MDSilber**

### CODE REVIEW

**Comment by MDSilber** [comment]
@zachzwei @Cryptocool1 wanted to quickly mention that we migrated our token last night, so the number of transactions on the token might be below 10000 still, but we've had far more than 10000 since we launched to the original token contract (0x19263f2b4693da0991c4df046e4baa5386f5735e). We did a 1:1 airdrop last night with the new token.

**Comment by cryptomanz** [comment]
Hello,
Can your answer some questions?
• What is the purpose of this token? How will it benefit Trust Wallet users?
 • How is the token being distributed? Are you conducting an airdrop?
 • Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?
 • Is the token listed on a centralized/decentralized exchange?
 • Is a Smart Contract audit completed? Where can we find this information?

**Comment by MDSilber** [comment]
@cryptomanz happy to answer those questions!

• What is the purpose of this token? How will it benefit Trust Wallet users?
The ZOO token is the utility token for the ZOO NFT game (which is being released in the next few weeks). The token will be used in-game to hatch animals, breed them, and buy eggs for the game.
• How is the token being distributed? Are you conducting an airdrop?
We did a fair launch with a Pancakeswap V2 liquidity pool
• Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?
No
• Is the token listed on a centralized/decentralized exchange?
Yes, on pancakeswap
• Is a Smart Contract audit completed? Where can we find this information?
Our latest smart contract was built using cointool.app, whose contracts are audited, so we haven't conducted our own audit of this contract (though all of our other NFT contracts for the ZOO game are audited).

Let me know if you need anything else from me!

**Comment by cryptomanz** [comment]
- Awaiting for smart contract audit.

**Comment by Cryptocool1** [comment]
Feel free to re-open pull request once you meet those requirements.
make sure to mention this PR, so that we can see that fee has been paid already here.

**Comment by MDSilber** [comment]
@Cryptocool1 just checking in again to see what we can do to move this process along. Thanks!

**Comment by cryptomanz** [comment]
We require full smart contract audit.

**Comment by MDSilber** [comment]
Can it be from any auditing source, or do you only accept audits from specific organizations?

**Pull request closed without merging**
