### PR TITLE
Add G2 Crypto Gaming & Lottery (BEP20)

### PR DESCRIPTION
**Pull request by xfnzxeon**
Adding info for BEP20 token 'G2 Crypto Gaming & Lottery'.

PR created by <a href="https://assets.trustwallet.com">TW Assets Management</a>

### CODE REVIEW

**Comment by Cryptocool1** [comment]
• What is the purpose of this token? How will it benefit Trust Wallet users?
 • How is the token being distributed? Are you conducting an airdrop?
 • Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?
 • Is the token listed on a centralized/decentralized exchange?
 • Is a Smart Contract audit completed? Where can we find this information?

**Comment by xfnzxeon** [comment]
- The Utility Project Token has multiple purposes. We have an active telegram embedded Arcade game that uses G2 as its currency, we have automatic staking, Partnership Programs and more. 
- The token can be bought via pancakeswap or poocoin
- It was sold via presale to start
- Currently listed on CMC and CG, it can be bought via pancakeswap, a decentralized exchange.
- Contract Verified by BSCscan, Secondary Security Audit to come

**Comment by Cryptocool1** [comment]
can you sen audit here please?

**Comment by xfnzxeon** [comment]
https://solidity.finance/audits/G2/

**Comment by Cryptocool1** [comment]
Снимок экрана 2021-11-15 в 16 54 41
can you change the image to the full screen?

**Comment by xfnzxeon** [comment]
Is this what you mea
TW
n?

**Pull request merged**
