### PR TITLE
Add $Acid info and logo

### PR DESCRIPTION
**Pull request by 0xnuu**
Hello Trust wallet team, request to add info and logo of Acid token, thank you!

### CODE REVIEW

**Review by scotts2080 — COMMENTED** [review]
- 610290692

**Comment by Cryptocool1** [comment]
As per our policy, there is a minimum requirement of 10,000 holder addresses and 15,000 transactions, in order to filter out scam tokens.
See the criteria at : https://developer.trustwallet.com/listing-new-assets/requirements .

**Review by scotts2080 — COMMENTED** [review]
bc1qldlx2rrg4jx9cl8zuc39fxjjpa4udyasw8emay

**Review by scotts2080 — COMMENTED** [review]
3H1vPbWcdvG8XWFJiD7qxgVJgx2PUENUYk

**Comment by izlan90** [comment]
3723d53490d5a7c2968987b6ea3626ed662a07e3

**Pull request closed without merging**
