### PR TITLE
Sheep Token Logo Update

### PR DESCRIPTION
**Pull request by sheeptokenprotocol**
Sheep Token Logo Update

### CODE REVIEW

**Comment by tylerleec** [comment]
Still no update on the merge? Its been almost 24hours

**Comment by sheeptokenprotocol** [comment]
what is the status on our logo update?
the pull request is paid and pending for over 48 hrs now.

**Comment by Cryptocool1** [comment]
contract_code remove this file please

**Comment by sheeptokenprotocol** [comment]
> contract_code remove this file please

contract_code has been removed. Is our logo still able to be updated?
Thank You.

**Comment by sheeptokenprotocol** [comment]
> Correction needed:
> contract_code remove this file please

What is the STATUS on this pull request?!
I'm not sure what they delay is. Its been over a week now.

**Comment by sheeptokenprotocol** [comment]
Can I please have a STATUS update on this pull request?

**Comment by sheeptokenprotocol** [comment]
> **PR Summary**
> Files in PR: 2
> Token in PR: BEP20 0x0025B42bfc22CbbA6c02d23d4Ec2aBFcf6E014d4
> Symbol: **SHEEP** decimals: 9
> Links: [Logo](https://raw.githubusercontent.com/sheeptokenprotocol/assets/master/blockchains/smartchain/assets/0x0025B42bfc22CbbA6c02d23d4Ec2aBFcf6E014d4/logo.png) [Info](https://raw.githubusercontent.com/sheeptokenprotocol/assets/master/blockchains/smartchain/assets/0x0025B42bfc22CbbA6c02d23d4Ec2aBFcf6E014d4/info.json) [Website](https://SheepToken.Cash/) [Explorer](https://bscscan.com/token/0x0025B42bfc22CbbA6c02d23d4Ec2aBFcf6E014d4) (check OK 🙂)
> 
>

**Comment by sheeptokenprotocol** [comment]
info.json file should be properly updated now. 
Is the pull request still able to be merged?

**Comment by sheeptokenprotocol** [comment]
??

**Comment by tylerleec** [comment]
Can I please have an update on this pull request?!

**Comment by catenocrypt** [comment]
Merged master to resolve conflict; logo file is being updated in this PR.

**Pull request merged**
