### PR TITLE
Add MagnetGold (BEP20)

### PR DESCRIPTION
**Pull request by MAGNETGOLD**
Adding info for BEP20 token 'MagnetGold'.

PR created by <a href="https://assets.trustwallet.com">TW Assets Management</a>

### CODE REVIEW

**Comment by MAGNETGOLD** [comment]
> Hi! In order to compensate for the efforts of processing PRs, we kindly ask for a contribution. 💀 As **there is no refund**, before **paying the fee**, make sure **new tokens fulfill the minimum circulation and other [acceptance criteria](https://developer.trustwallet.com/assets/requirements)**. See also the [PR Fee FAQ](https://developer.trustwallet.com/assets/faq).
> 
> Please pay **1000 TWT** with the memo **16118** to the address `bnb1tqq9llyr3dyjd559dha6z5r5etk3qfwk07m098`. Alternatively, 5 BNB is also accepted (same memo & address).
> 
> **QR** code: [Trust](https://api.qrserver.com/v1/create-qr-code/?size=200x200&data=https%3A%2F%2Flink.trustwallet.com%2Fsend%3Fasset%3Dc714_tTWT-8C2%26address%3Dbnb1tqq9llyr3dyjd559dha6z5r5etk3qfwk07m098%26amount%3D1000%26memo%3D16118) | [other wallet](https://api.qrserver.com/v1/create-qr-code/?size=200x200&data=bnb1tqq9llyr3dyjd559dha6z5r5etk3qfwk07m098%3Famount%3D1000%26memo%3D16118)
> 
> _Notes_:
> 
> * [Trust Wallet Tokens (TWT)](https://community.trustwallet.com/t/trust-wallet-token-twt/4187) can be obtained through our [Referral Program](https://community.trustwallet.com/t/invite-a-friend-earn-trust-wallet-token-twt/4125) or [from DEXs/exchanges](https://community.trustwallet.com/t/where-to-get-trust-wallet-tokens/76641).
> * New tokens without significant usage are rejected, see criteria mentioned above.
> * One PR should be for a single project; PR's with more than 10 logos will be rejected.
> * Payment evaluation happens automatically, but with a few minutes delay.  When payment is detected, an Accept Review is automatically placed on the PR, which is a condition for merge.
> * Evaluating the PR is done manually, and it is merged only if all conditions are satisfied.
> * TWT-BEP2 is supported (Binance Chain), TWT-BEP20 version on Smart Chain is not.
=======================================================================
1000 TWT is already paid by us with the memo 14230 to the address bnb1tqq9llyr3dyjd559dha6z5r5etk3qfwk07m098
Our previous Pull Request was "Update Logo For Existing Token - MagnetGold #14230"
Transaction Hash: 0xebc0dba76e8c8892a84f96dee9daea9b11c319d9a437c0a67eeee77fb818bdf
On 23rd of NOV 2021 Tuesday 7:25PM

TrustWallet Payment Paid
TrustWallet Paymet 1000 TWT

**Kindly Consider it and Update MagnetGold Logo on Trust Wallet**

**Comment by MAGNETGOLD** [comment]
Hi Trustwallet/Assets Team,

As per your instructions in your previous email : -
reply-to: trustwallet/assets <
***@***.***>
to: trustwallet/assets ***@***.***>
cc: MTG ***@***.***>,
Mention ***@***.***>
date:


Nov 26, 2021, 8:23 PM

We create new PR from your Assets app in beta; go to
https://assets.trustwallet.com

1000 TWT is already paid by us with the memo 14230 to the address
bnb1tqq9llyr3dyjd559dha6z5r5etk3qfwk07m098
Our previous Pull Request was "Update Logo For Existing Token -
MagnetGold Update
Logo For Existing Token - MagnetGold  #14230
<https://github.com/trustwallet/assets/pull/14230>"
Transaction Hash:
0xebc0dba76e8c8892a84f96dee9daea9b11c319d9a437c0a67eeee77fb818bdf
On 23rd of NOV 2021 Tuesday 7:25PM

Payment details are attached

Kindly Consider it and Update MagnetGold Logo on Trust Wallet

Regards,

**Comment by Cryptocool1** [comment]
> Hi Trustwallet/Assets Team, As per your instructions in your previous email : - reply-to: trustwallet/assets < ***@***.***> to: trustwallet/assets ***@***.***> cc: MTG ***@***.***>, Mention ***@***.***> date: Nov 26, 2021, 8:23 PM We create new PR from your Assets app in beta; go to https://assets.trustwallet.com 1000 TWT is already paid by us with the memo 14230 to the address bnb1tqq9llyr3dyjd559dha6z5r5etk3qfwk07m098 Our previous Pull Request was "Update Logo For Existing Token - MagnetGold Update Logo For Existing Token - MagnetGold #14230 <#14230>" Transaction Hash: 0xebc0dba76e8c8892a84f96dee9daea9b11c319d9a437c0a67eeee77fb818bdf On 23rd of NOV 2021 Tuesday 7:25PM Payment details are attached Kindly Consider it and Update MagnetGold Logo on Trust Wallet Regards,
> […](#)

I have already add the paid label

**Comment by MAGNETGOLD** [comment]
Yes, Thanks
Its there

*Sir, *Kindly Update MagnetGold Logo on Trust Wallet

Regards

**Comment by MAGNETGOLD** [comment]
Thanks a lot Its updated

**Comment by MAGNETGOLD** [comment]
Dear Team,

Here we want to share a very bad news that *our "trustwalet" is
completely hacked today morning at 4:24 to 4:28 (Indian Time)*
by *Thief Contact Address: 0x278f64ae8297cc07ec44dd78af606e627cf78e3b*
The thief theft our complete wallet
Our Wallet Tokens was:
MTG = 886,649.516060500924696085
USDT=19995
BNB Binance Chain + BNB=4.25

Our humble request kindly block *Thief Contact
Address: 0x278f64ae8297cc07ec44dd78af606e627cf78e3b*
So, from trustwallet at least he/she cannot be able to make any transaction.

Kindly favour us and urgently block id
*0x278f64ae8297cc07ec44dd78af606e627cf78e3b
*for any transactions immediately.

Regards,

MagnetGold
Contact Address: 0x323273b8EE5Ae6247b47C38C81dB45E1beF13E6F

[image: Screenshot (165).png]

**Pull request merged**
