### PR TITLE
Create 0x7dEe371A788f9BD6c546dF83F0d74fBe37cbf006

### PR DESCRIPTION
**Pull request by obestjose**
Teccoin

### CODE REVIEW

**Comment by obestjose** [comment]
IMG_20200428_224020_396 (3)
 New logo for 0x7dEe371A788f9BD6c546dF83F0d74fBe37cbf006

**Comment by Wishcoin20** [comment]
Please add on Wish Coin trustwallet/assets
httpsimgur comSAPnpB1

New logo for: tax id: https://explorer.binance.org/tx/0553F61A1C235AED5AA3B01B7366C67EFD7E7BB9DAA622C148068030BE170531

**Comment by kolya182** [comment]
Added

**Comment by Wishcoin20** [comment]
sir Please add agin logo not Show Trustwallet

**Pull request closed without merging**
