### PR TITLE
Add logo BEP20 The Luxury Coin (TLB)

### PR DESCRIPTION
**Pull request by TheLuxuryBlockchain**
Add token logo after migration from Ethereum to Binance Smart Chain

### CODE REVIEW

**Comment by catenocrypt** [comment]
Submission is incorrect/insufficient:
- Logo file should be named
  `blockchains/smartchain/assets/0xb5791d504367dee4ba3a379fb3d3d5a6b955cb2e/logo.png` (not blockchains/smartchain/assets/0xb5791d504367dee4ba3a379fb3d3d5a6b955cb2e/0xb5791d504367dee4ba3a379fb3d3d5a6b955cb2e.png)
- Also add an `info.json` next to the logo, of the form:

```json
{
    "name": "Trust Wallet Token",
    "type": "ERC20",
    "symbol": "TWT",
    "decimals": 8,
    "description": "Utility token to increase adoption of cryptocurrency.",
    "website": "https://trustwallet.com",
    "explorer": "https://explorer.binance.org/asset/TWT-8C2",
    "status": "active",
    "id": "TWT-8C2"
}
```

Please correct.

**Review by TheLuxuryBlockchain — COMMENTED** [review]
Please check if all is correct now. Thank you!

**Comment by Iamdeadlyz** [comment]
We don't have write-access to your PR. Please fix the checksum issue by following this:
- Rename the folder to `0xB5791d504367dEE4BA3A379fb3d3d5A6B955cb2e-x`, commit, and push
- Rename it again to `0xB5791d504367dEE4BA3A379fb3d3d5A6B955cb2e`, commit, then push

It's case-sensitive.

**Comment by catenocrypt** [comment]
As per our policy, brand new tokens are not included, there is a minimum requirement of 2500 holder addresses and 5000 transactions, in order to filter out scam tokens.
See the criteria at (mentioned in the first message by the bot): https://community.trustwallet.com/t/how-to-submit-a-token-logo/3863).
This token has no real usage yet (6 holders). Putting PR on hold for now. Please come back to us when all criteria are met.  Multi-chain and staking tokens may get special treatment, let us know if this is the case. 

https://bscscan.com/token/0xb5791d504367dee4ba3a379fb3d3d5a6b955cb2e

**Comment by TheLuxuryBlockchain** [comment]
> As per our policy, brand new tokens are not included, there is a minimum requirement of 2500 holder addresses and 5000 transactions, in order to filter out scam tokens.
> See the criteria at (mentioned in the first message by the bot): https://community.trustwallet.com/t/how-to-submit-a-token-logo/3863).
> This token has no real usage yet (6 holders). Putting PR on hold for now. Please come back to us when all criteria are met. Multi-chain and staking tokens may get special treatment, let us know if this is the case.
> 
> https://bscscan.com/token/0xb5791d504367dee4ba3a379fb3d3d5a6b955cb2e

Hi,

We mentioned that we are migrating from Ethereum, please check the link

https://coinmarketcap.com/currencies/the-luxury-coin/

Thank you :)

**Comment by catenocrypt** [comment]
Sorry, the combined circulation is still well below our minimum limit: 332 + 7 holder addresses, vs 2500.
On hold.

https://etherscan.io/token/0x8ab0565dfe65bf9be754d7b0dadbb42c4ecaec01
https://bscscan.com/token/0xB5791d504367dEE4BA3A379fb3d3d5A6B955cb2e

**Comment by gourmetgalaxy** [comment]
Hi Team,
Our ERC20 token information can be founded here :

https://etherscan.io/token/0x4f5fa8f2d12e5eB780f6082Dd656C565C48E0f24

Thank you.

**Comment by TheLuxuryBank** [comment]
> Sorry, the combined circulation is still well below our minimum limit: 332 + 7 holder addresses, vs 2500.
> On hold.
> 
> https://etherscan.io/token/0x8ab0565dfe65bf9be754d7b0dadbb42c4ecaec01
> https://bscscan.com/token/0xB5791d504367dEE4BA3A379fb3d3d5A6B955cb2e

Hi Catenocrypt, please check our explorers: 

https://etherscan.io/token/0x8ab0565dfe65bf9be754d7b0dadbb42c4ecaec01
https://bscscan.com/token/0xB5791d504367dEE4BA3A379fb3d3d5A6B955cb2e

With respect and thanks for what you do for the crypto community!

**Comment by TheLuxuryBank** [comment]
Dear Catenocrypt, 

We mention that we did not have an ICO, we have no intention of having an ICO, and our community is quite small in terms of the industry in which we operate.

Please take a look at our request to add the logo and details related to TLB, as we meet the conditions and our activity has started.

https://bscscan.com/token/0xb5791d504367dee4ba3a379fb3d3d5a6b955cb2e

Thank you for your efforts to keep TrustWallet at the top and you have our full consideration!

**Comment by TheLuxuryBlockchain** [comment]
Hi Catenocrypt,

Now I think we meet the conditions. Moreover, we did not have an ICO, and we do not intend to have an ICO, we will have listings on exchanges in the next period and we love Trust Wallet, both we and our clients and partners and we want to use it to its full potential. Thank you for your work.

**Comment by catenocrypt** [comment]
Circulation req. satisfied.

**Comment by catenocrypt** [comment]
Correction needed: there are 2x3 files instead of the required 2.
Please remove the first and last 2 files from the PR:

image

**Comment by TheLuxuryBlockchain** [comment]
> Correction needed: there are 2x3 files instead of the required 2.
> Please remove the first and last 2 files from the PR:
> 
> image

Thank you, appreciate! 
We followed your instructions, just for the .png we do not have the delete button enabled.  
Maybe now it will work.

**Comment by catenocrypt** [comment]
There are still 3 logo files in the PR; see the Files tab.  Please keep only 1 logo and 1 info file in the right folder.

**Comment by vikmeup** [comment]
As per our updated policy, brand new tokens are not included, there is a minimum requirement 

- at least 2500 token holders
- at least 500 transactions

See our [How to Get Submit Token Logo ](https://community.trustwallet.com/t/how-to-submit-a-token-logo/3863#how-to-get-approved) guidelines.

Feel free to re-open pull request once you meet those requirements.

**Comment by TheLuxuryBlockchain** [comment]
> As per our updated policy, brand new tokens are not included, there is a minimum requirement
> 
> * at least 2500 token holders
> * at least 500 transactions
> 
> See our [How to Get Submit Token Logo ](https://community.trustwallet.com/t/how-to-submit-a-token-logo/3863#how-to-get-approved) guidelines.
> 
> Feel free to re-open pull request once you meet those requirements.

Hi Vikmeup, already Catenocrypt checked ours and his answer is Circulation req. satisfied.
The only problem that we cannot delete the 2 logos from PR, the delete button is not working. 
Thank you.

**Comment by vikmeup** [comment]
You can take a look at: https://docs.github.com/en/github/managing-files-in-a-repository/deleting-files-in-a-repository

Let me know once you guys fix the issue.

**Comment by TheLuxuryBlockchain** [comment]
> You can take a look at: https://docs.github.com/en/github/managing-files-in-a-repository/deleting-files-in-a-repository
> 
> Let me know once you guys fix the issue.

Thank you for your help, our team will check tomorrow and will fix the issue. Regards!

**Pull request closed without merging**
