### PR TITLE
Added TeaCoin and Logo

### PR DESCRIPTION
**Pull request by autotheos**

### CODE REVIEW

**Comment by kolya182** [comment]
Waves validator address is incorrect, please fix it.

**Comment by kolya182** [comment]
Do you represent validator in any way ? If not i'm just going to close it.

**Comment by autotheos** [comment]
Yes I'm an admin in the telegram

**Comment by autotheos** [comment]
Ok I think I did it correctly now

**Comment by autotheos** [comment]
Should I start over?

**Pull request closed without merging**
