### PR TITLE
Change Contract Address

### PR DESCRIPTION
**Pull request by MONETASGLOBAL**
Reference PR #19387

For Ref PR No #19382

Regarding Contract Address Change

Please Refer Issue No :-#19363 , #19374

Old Contract Address :- 0xE440b9af0AE99174b3FAaB87174E31634D135f6d

New Contract Address :- 0x10adF50e15611d5A4DE3bd21F0DB7f3491A8ae0f

How Much Fee Paid For Contract Address Change Or Update Please Refer Recent PR #19387

### CODE REVIEW

**Comment by Cryptocool1** [comment]
submission looks goods awaiting for fee payment

**Comment by MONETASGLOBAL** [comment]
> submission looks goods awaiting for fee payment

How Much and Where Pay Fee For Updating Contract Address , Please Send Me Details

**Comment by MONETASGLOBAL** [comment]
Please Reply Don't Close this PR

**Comment by MONETASGLOBAL** [comment]
ok

**Comment by MONETASGLOBAL** [comment]
i will pay it today don't close PR

**Comment by MONETASGLOBAL** [comment]
By Mistake I Will Insert Memo No 19453

Please Accept and Merge this PR 
WhatsApp Image 2022-04-04 at 10 41 38 AM

Transaction Hash :- 60B857CB9EF7AC17C08003CB6F791A68606B59F7523056F8BCF651335EC647B3

**Comment by MONETASGLOBAL** [comment]
Thanks

**Comment by MONETASGLOBAL** [comment]
Thanks

**Comment by kophyo1234** [comment]
#blockchains/ethereum/assets/0x49bc8340ACD3521150d7cCD8a4a3510D2F5130Ca/info.json

**Comment by kophyo1234** [comment]
ok

**Pull request merged**
