### PR TITLE
Add Streamr (ERC20)

### PR DESCRIPTION
**Pull request by fonty1**
Adding info for ERC20 token 'Streamr'.

PR created by <a href="https://assets.trustwallet.com">TW Assets Management</a>

### CODE REVIEW

**Comment by fonty1** [comment]
❌ Low token circulation: no. of holders is 2274, below limit of 25000

FYI - This is due to the recent migration, the token we are migrating from has 450,742 holders
[Token Migration Page](https://streamr.network/token-migration)

**Comment by Cryptocool1** [comment]
can you send contract that is abandoned?

**Comment by fonty1** [comment]
> can you send contract that is abandoned?
Sure:
[Old contract](https://etherscan.io/address/0x0cf0ee63788a0849fe5297f3407f701e122cc023)

**Comment by fonty1** [comment]
Hi @Cryptocool1 - The name of the token should be **Streamr** and the token is **DATA** - in the app it is currently showing Data (data). Could you kindly take a look?

image

**Comment by Cryptocool1** [comment]
Will fix that soon. Thank you

**Comment by fonty1** [comment]
> Will fix that soon. Thank you

Kind reminder to take a look at this :) Can you give an estimate on when this will be fixed?

**Pull request merged**
