### PR TITLE
Add LOVEEARTH COIN (LEC) (ERC20)

### PR DESCRIPTION
**Pull request by loveearth123**
This PR is being closed due to inactivity. If you wish to continue, please have us reopen the PR before sending your payment, or just create a new one.
Do NOT send payments for closed PR, as the fee may by lost!
  (48 vs. 48 hrs)

### CODE REVIEW

**Comment by loveearth123** [comment]
The coin holder has been updated

**Comment by Cryptocool1** [comment]
hello,
• What is the purpose of this token? How will it benefit Trust Wallet users?
 • How is the token being distributed? Are you conducting an airdrop?
 • Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?
 • Is the token listed on a centralized/decentralized exchange?
 • Is a Smart Contract audit completed? Where can we find this information?

**Comment by Cryptocool1** [comment]
> The coin holder has been updated

how did you get them?

**Comment by Cryptocool1** [comment]
couple of hours passed

**Comment by loveearth123** [comment]
The coin holder has been updated

**Comment by loveearth123** [comment]
> > The coin holder has been updated
> 
> how did you get them?



> hello,
> • What is the purpose of this token? How will it benefit Trust Wallet users?
> • How is the token being distributed? Are you conducting an airdrop?
> • Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?
> • Is the token listed on a centralized/decentralized exchange?
> • Is a Smart Contract audit completed? Where can we find this information?



> couple of hours passed

Hello, sorry for missing your message, that causing my pull request was closed. As we are in Beijing time zone, I guess there are time difference between us. Shall we start my pull request again?

**Comment by loveearth123** [comment]
> hello,
> • What is the purpose of this token? How will it benefit Trust Wallet users?

Love Earth Coin is a charity token aiming to introduce the crypto technology in charity practices, building a new charity model in the age of Web 3.0. 
For every single holder of Love Earth coin, the LEC DAO (Decentralized Autonomous Organization) will denote 0.1 LEC for charity. The more the number of holders, the more will be donated.
 
LEC introduced the blockchain voting system, LEC holders can propose a charity project for vote, and the holders of LEC can vote for their favorite project.
In order to propose in the vote or to vote, holders must prove their holding of LEC. Therefore, when visiting the voting page, holders should link their wallet to show their holding. 
For user of Trust Wallet, by holding LEC in the wallet, they are qualified to take part in the vote.
 

> • How is the token being distributed? Are you conducting an airdrop?

The total supply of Love Earth Coins is 1 billion only. Its issued on ERC20 and no more extra coin will be issued.
1. 50% is deposited in the address of the public charity fund, which is locked by smart contract, and can only be used for donations to large public charity undertakings (large humanitarian disaster relief is the main relief direction, taking up 90%; General public welfare undertakings no more than 10%);
2. 10% locked in the Treasury Reserve (by smart contracts).
- 5% airdrop will be awarded to the top 100 addresses whose holding is no less than 100,000 coins. The airdrop will be made once a month on the 11th, and a total of 30 airdrops will be completed.
- 5% will be airdropped to 100 celebrities, caring charity personage and technical aid donors who have made important contributions to the community. Proposals will be formed and voted on by the community vote every month.

3. The remaining 40% send into Uniswap for liquidity, with the LP token send to the blackhole address. 
 
The founder team does not own any Love Earth Coin and is 100% decentralized. This is to make sure that the LEC Charity project is totally controlled by the public, but not the founder. 
But there are some LEC communities (found by holders), they would launch some airdrop campaign.

> • Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?

No, LEC didn’t launched any kind of presale. 

> • Is the token listed on a centralized/decentralized exchange?

It is now listed on Uniswap V2 and only on the ERC20.

> • Is a Smart Contract audit completed? Where can we find this information?

Yes, it was audited by Certik, for the full audit report, please refer to https://bit.ly/3epGqdu.

**Pull request closed without merging**
