### PR TITLE
update LPOOL logo

### PR DESCRIPTION
**Pull request by lazerbeam-dev**
This PR is being closed due to inactivity. If you wish to continue, please have us reopen the PR before sending your payment.
Do NOT send payments for closed PR, as the fee may by lost!
  (281 vs. 70 hrs)

### CODE REVIEW

**Comment by catenocrypt** [comment]
Submission looks OK.
Only logo file is updated -- though at first sight I see not much difference to the existing.
Merge fee needed.

**Comment by slackconformistjinn** [comment]
Hello please can you reopen this pull request? The amount was paid!

Best wishes, Jack

Sent with [ProtonMail](https://protonmail.com) Secure Email.

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐

**Comment by catenocrypt** [comment]
Payment was not found by the bot; could you provide TXID or date for checking?

**Comment by slackconformistjinn** [comment]
transaction id

https://explorer.binance.org/tx/B50F1CBA5724DCBDBCE871528C290A72301392A5031B907060052CCE2CDF1764

Sent with [ProtonMail](https://protonmail.com) Secure Email.

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐

**Comment by catenocrypt** [comment]
Fee paid, 250 TWT,   https://explorer.binance.org/tx/B50F1CBA5724DCBDBCE871528C290A72301392A5031B907060052CCE2CDF1764

**Pull request merged**
