### PR TITLE
Add MetaGamescoin (BEP20)

### PR DESCRIPTION
**Pull request by Mazyar60**
Adding info for BEP20 token 'MetaGamescoin'.

PR created by <a href="https://assets.trustwallet.com">TW Assets Management</a>

### CODE REVIEW

**Review by Mazyar60 — COMMENTED** [review]
I have pay 500TWT another day with respect 27632

**Comment by Mazyar60** [comment]
Hello
since yesterday I could not buy TWT token on Bep2 blockchain , is it
possible to give BEP20 address to send token?!

**Comment by Mazyar60** [comment]
Hello, since yesterday I could not buy TWT token on Bep2 platform, is it possible to give BEP20 address to send token?!

**Comment by cryptomanz1** [comment]
• What is the purpose of this token? How will it benefit Trust Wallet users?
 • How is the token being distributed? Are you conducting an airdrop?
 • Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?
 • Is the token listed on a centralized/decentralized exchange?
 • Is a Smart Contract audit completed? Where can we find this information?

**Comment by cryptomanz1** [comment]
• What is the purpose of this token? How will it benefit Trust Wallet users?
 • How is the token being distributed? Are you conducting an airdrop?
 • Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?
 • Is the token listed on a centralized/decentralized exchange?
 • Is a Smart Contract audit completed? Where can we find this information?

**Comment by Mazyar60** [comment]
All link you need

BscScan
https://bscscan.com/token/0xbb73BB2505AC4643d5C0a99c2A1F34B3DfD09D11

Total Supply: 55,000,000,000

Max Supply : 100,000,000,000

Circulation supply: 1/000/000/000

Liquidity : 1/250/000 $

Website 
HTTPS://METAGAMESCOIN.IO

distribution 
https://docs.google.com/spreadsheets/d/1BNdE8JHmhq3XBiKNNNa1DvEeNM9zWDV3Y9KNn-j5Xw4/edit?usp=sharing

Dextools:
https://www.dextools.io/app/en/bnb/pair-explorer/0xc08019ea4988bcce9dc4c2ee983e431a885d2f1a?t=1707826013423

Azbit CEX
https://azbit.com/exchange/MGC_USDT
Azbit API
https://api2.azbit.com/api/marketdata/getcoinmarketcap/ticker/

Coinsbit CEX
https://coinsbit.io/trade_classic/MGC_USDT
Coinsbit API
https://coinsbit.io/api/v1/public/markets

Pancakeswap
https://pancakeswap.finance/swap?outputCurrency=0xbb73bb2505ac4643d5c0a99c2a1f34b3dfd09d11

CMC 
https://coinmarketcap.com/currencies/meta-games-coin

White Paper 
https://metagamescoin.io/whitepaper/

Githab 
https://github.com/MetaGamescoinio

Mediom
https://link.medium.com/2yeFPk4hPub

Instagram
https://instagram.com/metagamescoin_io 

YouTube 
https://youtube.com/@metagamescoin

Facebook 
https://www.facebook.com/profile.php?id=100082817472362

Reddit
https://www.reddit.com/r/MetaGamesCoin

Telegram
https://t.me/MetaGamesCoin_io

Twitter 
https://twitter.com/MetaGamesC

Discord 
https://discord.com/Metagamescoin#1848

Audits
1)https://contractwolf.io/projects/metagamescoin
https://github.com/ContractWolf/smart-contract-audits/blob/main/ContractWolf_Audit_MetaGamesCoin.pdf

2)https://github.com/interfinetwork/project-delivery-data/blob/main/MetaGamescoin
https://github.com/interfinetwork/project-delivery-data/blob/main/MetaGamesCoin/MetaGamesCoin_AuditReport_InterFi.pdf

Treading view 
https://www.tradingview.com/symbols/MGCWBNB_C08019.USD/?exchange=PANCAKESWAP&utm_source=androidapp&utm_medium=share

**Comment by Mazyar60** [comment]
Of course, it should be noted that we will restart the centralized exchanges in the new week with a new market maker team, because the  CoinsBit team harassed us with irresponsibility, so we closed last week to install a new team, and they will reopen in the new week.  Of course, all the documents, negotiations and contracts of the list with the exchanges are available, and if you need it, I will send it to you

**Comment by Mazyar60** [comment]
But currently, we have had daily transactions of up to $500,000 with the decentralized exchange in the last week.

**Comment by Mazyar60** [comment]
https://www.binance.com/en-GB/price/meta-games-coin

https://www.bitget.com/price/meta-games-coin/krw

https://www.coinbase.com/en-es/price/meta-games-coin

https://crypto.com/price/meta-games-coin

https://coinmarketcap.com/currencies/meta-games-coin/

https://www.livecoinwatch.com/price/MetaGamesCoinv2-_____MGC


https://coincodex.com/ico/metagamescoin/

**Comment by Mazyar60** [comment]
Be sure that with the listing of this token in Trustwallet, one day we will make you proud because with international projects in: 
Dubai, United Arab Emirates, 
This Token will be introduced to the world, and the world's most popular gamer community will benefit from its benefits.  

One day, we will become the world of gamers, and their work and life will be in the MGC ecosystem, 

So I sincerely request you to approve our list so that we can get closer to our goals, thank you.

**Comment by Mazyar60** [comment]
https://metagamescoin.io/airdrop/

https://docs.google.com/forms/d/e/1FAIpQLScfuqayem-tLW4yEb-awYC1YLyG7qwItP8mNA5gFLAe3Ncy_g/viewform

https://metagamescoin.io/presale/

https://dappbuilder.org/bsc/tokensaletimerefadm/tokensale.html?id=0x51b3913bD1Be79f1BBf898752B592b523d628533&net=56

**Comment by Mazyar60** [comment]
Dear Maintainers,

I am writing to inquire about the status of my pull request #27988. It has
been four days since I submitted the request, and I have not yet received
approval.

I understand that the review process can take some time, but I am eager to
get my changes merged into the main branch. If there are any issues with my
pull request, please let me know so that I can address them promptly.

Thank you for your time and consideration.

Best regards,
Metagamescoin
Mazyar More

**Review by Willisplayed — COMMENTED** [review]
Huh

**Comment by Mazyar60** [comment]
> Adding info for BEP20 token 'MetaGamescoin'.
> 
> 
> 
> PR created by <a href="https://assets.trustwallet.com">TW Assets Management</a>

Please update price
https://coinmarketcap.com/currencies/meta-games-coin

**Comment by Mazyar60** [comment]
Hi again
Dear trust team
Please update MGC price in Wallet, MGC has been verified Circulating supply in Coinmarketcap, but not price show in trust wallet yet. All holders are waiting
Thank you for your support
Best regards 
Mazyar More

**Pull request merged**
