### PR TITLE
Add zedxion logo and info

### PR DESCRIPTION
**Pull request by samagraph**
This is zedxion logo and info.

### CODE REVIEW

**Comment by cryptomanz** [comment]
Please create new PR, follow doc https://developer.trustwallet.com/assets/requirements
You may want to try our Assets app in beta; go to https://assets.trustwallet.com, log on with Github, enter contract ID, logo and some additional info, and it will create a PR for you.
See https://developer.trustwallet.com/assets/repository_details

**Comment by samagraph** [comment]
Hello, 
I do every think as your document says.
anyway i attach the info.json

----------------------------------------

**Comment by samagraph** [comment]
Hi,
[ZEDXION] You have successfully withdrawn 5 BNB At 2022-05-28
 16:29:50(UTC+8)

----------------------------------------

From:
 "merge-fee-bot[bot]" ***@***.***>
Sent: 5/28/22 11:20
 AM
To: trustwallet/assets ***@***.***>
Cc: samagraph
 ***@***.***>, Author ***@***.***>
Subject: Re:
 [trustwallet/assets] zedxion logo and info (PR #20686)

Hi! In order to
 compensate for the efforts of processing PRs, we kindly ask for a
 contribution.
💀 As there is no refund, before paying the fee, make sure
 new tokens fulfill the minimum circulation and other acceptance
 criteria.
See also the PR Fee FAQ.

Please pay 700 TWT with the memo
 20686 to the address
 bnb1tqq9llyr3dyjd559dha6z5r5etk3qfwk07m098.
Alternatively, 5 BNB is also
 accepted (same memo & address).

QR code: Trust | other
 wallet

Notes:

- Trust Wallet Tokens (TWT) can be obtained through
 our Referral Program or from DEXs/exchanges.
- New tokens without
 significant usage are rejected, see criteria mentioned above.
- One PR
 should be for a single project; PR's with more than 10 logos will be
 rejected.
- Payment evaluation happens automatically, but with a few
 minutes delay. When payment is detected, an Accept Review is automatically
 placed on the PR, which is a condition for merge.
- Evaluating the PR is
 done manually, and it is merged only if all conditions are satisfied.
-
 TWT-BEP2 is supported (Binance Chain), TWT-BEP20 version on Smart Chain is
 not.

There will be a fee to process this request. None of it goes to
 the developers.
Before paying the fee, make sure new tokens fulfill the
 minimum circulation and other acceptance criteria.
If you are paying TWT
 for the submission, this will be burned automatically. There will be no
 refunds.

—
Reply to this email directly, view it on GitHub, or
 unsubscribe.

**Comment by samagraph** [comment]
hello,
what should i do my icon has not been change?

**Comment by samagraph** [comment]
hello any one is there?

**Review by samagraph — COMMENTED** [review]
we have done some Changes in our file.

**Comment by samagraph** [comment]
#20686 
Merge payment

**Comment by samagraph** [comment]
Hi,
[ZEDXION] You have successfully withdrawn 5 BNB At 2022-05-28
 16:29:50(UTC+8)
[…](https://github.com/trustwallet/assets/pull/20686#)

----------------------------------------

From:
 "merge-fee-bot[bot]" ***@***.***>
Sent: 5/28/22 11:20
 AM
To: trustwallet/assets ***@***.***>
Cc: samagraph
 ***@***.***>, Author ***@***.***>
Subject: Re:
 [trustwallet/assets] zedxion logo and info (PR [#20686](https://github.com/trustwallet/assets/pull/20686))

Hi! In order to
 compensate for the efforts of processing PRs, we kindly ask for a
 contribution.
💀 As there is no refund, before paying the fee, make sure
 new tokens fulfill the minimum circulation and other acceptance
 criteria.
See also the PR Fee FAQ.

Please pay 700 TWT with the memo
 20686 to the address
 bnb1tqq9llyr3dyjd559dha6z5r5etk3qfwk07m098.
Alternatively, 5 BNB is also
 accepted (same memo & address).

QR code: Trust | other
 wallet

Notes:

- Trust Wallet Tokens (TWT) can be obtained through
 our Referral Program or from DEXs/exchanges.
- New tokens without
 significant usage are rejected, see criteria mentioned above.
- One PR
 should be for a single project; PR's with more than 10 logos will be
 rejected.
- Payment evaluation happens automatically, but with a few
 minutes delay. When payment is detected, an Accept Review is automatically
 placed on the PR, which is a condition for merge.
- Evaluating the PR is
 done manually, and it is merged only if all conditions are satisfied.
-
 TWT-BEP2 is supported (Binance Chain), TWT-BEP20 version on Smart Chain is
 not.

There will be a fee to process this request. None of it goes to
 the developers.
Before paying the fee, make sure new tokens fulfill the
 minimum circulation and other acceptance criteria.
If you are paying TWT
 for the submission, this will be burned automatically. There will be no
 refunds.

—
Reply to this email directly, view it on GitHub, or
 unsubscribe.

**Comment by samagraph** [comment]
"merge-fee-bot[bot]" @.>

**Comment by samagraph** [comment]
https://github.com/settings/apps/merge-fee-bot

**Comment by Cryptocool1** [comment]
please have a look at Creptomanz comment and create the new PR as that one is incorrect

**Comment by samagraph** [comment]
"merge-fee-bot[bot]" @.>

**Review by samagraph — COMMENTED** [review]
{
	"name": "ZEDXION  Token",
    "website": "https://zedexion.io",
    "description": "Zedxion offers a comprehensive solution to the major problems faced by the traditional, fiat-driven monetary system. Building a crypto powered ecosystem comprising Zedxion Token.",
    "explorer": "https://bscscan.com/token/0x734D66f635523D7ddb7d2373C128333DA313041b",
    "type": "BEP20",
    "symbol": "USDZ",
    "decimals": 9,
    "status": "active",
    "id": "0x734D66f635523D7ddb7d2373C128333DA313041b"
}
 BIN +48.9 KB

**Comment by samagraph** [comment]
[info.json (1).txt](https://github.com/trustwallet/assets/files/8805380/info.json.1.txt)

**Comment by samagraph** [comment]
Help to fix dry run #20801

**Comment by samagraph** [comment]
Hello, help us to fix dry run on this project... it taking a long time

**Comment by Cryptocool1** [comment]
Is a smart contract completed?

**Pull request closed without merging**
