### PR TITLE
Add Apex Token (BEP20)

### PR DESCRIPTION
**Pull request by sdsfx007**
Adding info for BEP20 token 'Apex Token'.

PR created by <a href="https://assets.trustwallet.com">TW Assets Management</a>

### CODE REVIEW

**Comment by mwsoofy** [comment]
@Cryptocool1 Hello My dear friend, this is our third attempt, Please let us know how to proceed with payment to complete the commit from our end. Thank you.

**Comment by Cryptocool1** [comment]
Hello, 
• What is the purpose of this token? How will it benefit Trust Wallet users?
 • How is the token being distributed? Are you conducting an airdrop?
 • Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?
 • Is the token listed on a centralized/decentralized exchange?
 • Is a Smart Contract audit completed? Where can we find this information?

**Comment by mwsoofy** [comment]
@Cryptocool1 
1 ) - ApexToken is native token of Apex Ecosystem, Apex will launch ApexExchange And ApexToken will be our base token, Trust wallet users will be able to hold Verified ApexToken which can help against potential Fake  ApexTokens, Also as our holder base is growing exponentially, adding Apex to Trustwallet Assets will be a mutually beneficial.

2) Customers can stake APX using USDT for a certain time and get back APX as rewards. - No we are not conducting AirDrops.

3) Token has completed its ICO Phase.

4) Token is listed on CEX Azbit ( https://azbit.com/exchange/APX_USDT ) will be soon listed on other exchanges.

5) Yes we have completed smart contract audit. https://dessertswap.finance/audits/APX-BSC-AUDIT-38616895.pdf

Additionally we have also listed on CoinMarketCap - https://coinmarketcap.com/currencies/apextoken/, You can find more details here.

Thank you

**Comment by tw-daniel** [comment]
this is an error from bot, fee is not actually paid

**Comment by mwsoofy** [comment]
@tw-daniel Please let us know how to make this payment ? It will be very helpful.

**Comment by mwsoofy** [comment]
0x5aa0ef818568f29aeaa2596777fa9f8a520991c29b1f554ff2203558822bbd3f

This is the transaction hash

**Comment by mwsoofy** [comment]
@Cryptocool1 thank you for merging, but i cannot see any market price data on the trustwallet app even though we have added coinmarketcap data in the commit. Please guide us.

Thank you

**Pull request merged**
