### PR TITLE
Add RisingSun Token (BEP20)

### PR DESCRIPTION
**Pull request by davidsadev**
Adding RisingSun Token (RSUN) as a SmartChain asset.

### CODE REVIEW

**Comment by cryptomanz** [comment]
Hello,
Can your answer some questions?
 • What is the purpose of this token? How will it benefit Trust Wallet users?
 • How is the token being distributed? Are you conducting an airdrop?
 • Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?
 • Is the token listed on a centralized/decentralized exchange?
 • Is a Smart Contract audit completed? Where can we find this information?

**Comment by davidsadev** [comment]
• What is the purpose of this token? How will it benefit Trust Wallet users?
RisingSun backs our NFT trading card game ecosystem. It is a utility token used to mint our trading cards and is used as a reward pool for our upcoming game as well. The token also features BUSD reflection to holders.

• How is the token being distributed? Are you conducting an airdrop?
The token was initially distributed in a presale on DxSale on July 9th, 2021. It was then tradeable on Pancakeswap, which is how the current holders were able to obtain the token.

• Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?
Yes, there was a presale on DxSale on July 9th, 2021
https://dxsale.app/app/v2_9/defipresale?saleID=764&chain=BSC

• Is the token listed on a centralized/decentralized exchange?
Yes, it is listed on Pancakeswap.
https://pancakeswap.finance/swap#/swap?outputCurrency=0x917841c010b3d86ED886F36F2C9807E07a2e3093

• Is a Smart Contract audit completed? Where can we find this information?
Yes.
Smart Contract audit was completed by TechRate on July 15:
https://github.com/TechRate/Smart-Contract-Audits/blob/main/RisingSun%20Full%20Smart%20Contract%20Security%20Audit.pdf 
https://twitter.com/TechRate1/status/1416726452981096453

**Comment by cryptomanz** [comment]
can you please add links to your PR?
example: https://developer.trustwallet.com/add_new_asset/repository_details

**Comment by davidsadev** [comment]
> can you please add links to your PR?
> example: https://developer.trustwallet.com/add_new_asset/repository_details

Added links, thanks for the reminder.

**Pull request merged**
