### PR TITLE
Add AutoCrypto (BEP20)

### PR DESCRIPTION
**Pull request by ghost**
Adding info for BEP20 token 'AutoCrypto'.

PR created by <a href="https://assets.trustwallet.com">TW Assets Management</a>

### CODE REVIEW

**Comment by autocryptoai** [comment]
> As per our policy, brand new tokens are not included, there is a minimum requirement of 5000 holder addresses and 10000 transactions, in order to filter out scam tokens. See the criteria at (mentioned in the first message by the bot): https://community.trustwallet.com/t/how-to-submit-a-token-logo/3863). Closing PR for now. Please come back to us when all criteria are met.

Hello Nazar, we now meet the criteria. Our token has grown organically since it was launched over two months ago. Please confirm all files are OK in order to proceed with the payment.

**Comment by autocryptoai** [comment]
@cryptomanz Hello, any update on our case? Can we proceed with the payment?

**Comment by autocryptoai** [comment]
@cryptomanz @ramsty @Cryptocool1 Hello, any update on our case? Can we proceed with the payment?
We now meet the criteria. Our token has grown organically since it was launched over two months ago. Please confirm all files are OK in order to proceed with the payment.

**Comment by Cryptocool1** [comment]
This PR closed. You should create new one

**Pull request closed without merging**
