### PR TITLE
Add Shih Tzu logo and Info

### PR DESCRIPTION
**Pull request by dennismaster167**

### CODE REVIEW

**Comment by catenocrypt** [comment]
Info.json is incorrect.  It should be of the form:

```json
{
    "name": "Trust Wallet Token",
    "type": "ERC20",
    "symbol": "TWT",
    "decimals": 8,
    "description": "Utility token to increase adoption of cryptocurrency.",
    "website": "https://trustwallet.com",
    "explorer": "https://explorer.binance.org/asset/TWT-8C2",
    "status": "active",
    "id": "TWT-8C2"
}
```

Please follow documentation:  https://community.trustwallet.com/t/how-to-submit-a-token-logo/3863

**Comment by Cryptocool1** [comment]
Id field does not match contract, should be 0x841FB148863454A3b3570f515414759BE9091465, not ERC-20. Please rename.

**Comment by dennismaster167** [comment]
> Id field does not match contract, should be 0x841FB148863454A3b3570f515414759BE9091465, not ERC-20. Please rename.

Updated with contract ID. It should be good now.

**Comment by Cryptocool1** [comment]
As per our policy,  there is a minimum requirement of 2500 holder addresses and 5000 transactions, in order to filter out scam tokens.
See the criteria at (mentioned in the first message by the bot): https://community.trustwallet.com/t/how-to-submit-a-token-logo/3863).

**Comment by dennismaster167** [comment]
> As per our policy, there is a minimum requirement of 2500 holder addresses and 5000 transactions, in order to filter out scam tokens.
> See the criteria at (mentioned in the first message by the bot): https://community.trustwallet.com/t/how-to-submit-a-token-logo/3863).

We currently have 1600K something, so we just need to wait until we reach 2500 correct? Please make sure to leave this PR open. We will update here soon.

**Comment by dennismaster167** [comment]
@Cryptocool1 We have reached 2500 holders now, please approve the PR

**Pull request merged**
