### PR TITLE
Add BSC Gold ( BSCGold ) LOGO Bep20

### PR DESCRIPTION
**Pull request by Shyamthakur2**

### CODE REVIEW

**Comment by Shyamthakur2** [comment]
@catenocrypt @zachzwei @cryptochainico
Could you plz help to check if all the details are correct?

**Comment by Shyamthakur2** [comment]
> @catenocrypt

@catenocrypt should we go for payment if all okay?

**Comment by Shyamthakur2** [comment]
@catenocrypt payment done, thanks

**Comment by Cryptocool1** [comment]
Hello,
Can you capitalize all letters in your symbol please?

**Comment by Shyamthakur2** [comment]
> Hello,
> Can you capitalize all letters in your symbol please?

@Cryptocool1 done, thanks

**Pull request merged**
