### PR TITLE
Add logo and info.json for Premia

### PR DESCRIPTION
**Pull request by vxcozy**
Premia is a decentralized financial instrument protocol. Premia delivers Financial Instruments as a Service to Users, in which the use of the Premia Token is incentivized through various methods. Decentralized options utilizing the erc-1155 standard.

### CODE REVIEW

**Comment by Krypt1k86** [comment]
hey @Iamdeadlyz, could you give a little insight as to what the conflict is? it's showing that the last token submission i did months ago is somehow conflicting, but that json was approved when submitted.

**Comment by Krypt1k86** [comment]
cc @zachzwei @catenocrypt

**Comment by Krypt1k86** [comment]
disregard the pings, and my apologies. I checked out some other submissions and saw the additional data fields now required.

**Comment by catenocrypt** [comment]
We have strong limits on circulation, apparently this token is well short of that.  Can you reflect on this?

As per our policy, there is a minimum requirement of 2500 holder addresses and 5000 transactions.

**Comment by Krypt1k86** [comment]
Hey @catenocrypt would be happy to! i was creating the submission to prepare for release as the options platform pulls icons from trust repo, and we wanted the protocol token to display for options writing at launch.

The marketplace is now live and token launched after a 34.5 million public raise. The holders do currently fall a bit short, but Premia is on its way to being one of the largest options platforms in defi. 

As today is the first day of the token being live, there are currently over 1100 holders and 2100 transactions that have taken place. Are there ways to get the token information added while still being under the requirements? having the token logo display is a bit crucial to the platform.

**Pull request merged**
