### PR TITLE
Trust Wallet Logo submission for Baby Floki

### PR DESCRIPTION
**Pull request by babyflokibsc**

### CODE REVIEW

**Comment by cryptomanz** [comment]
Hello,
Can your answer some questions?
• What is the purpose of this token? How will it benefit Trust Wallet users?
 • How is the token being distributed? Are you conducting an airdrop?
 • Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?
 • Is the token listed on a centralized/decentralized exchange?
 • Is a Smart Contract audit completed? Where can we find this information?

**Comment by babyflokibsc** [comment]
Hi, 
Please find the response below 

What is the purpose of this token? How will it benefit Trust Wallet users?

The token rewards holders with Dogecoin just for holding. Holders get reflections on an average of 3% from buys and sells. Truswallet holders will also be able to benefit from these rewards. Furthermore, the token is launching NFTs in phase four of it's roadmap (add link here to roadmap). This will add further value to token holders. The token is named after Elon Musk's dog Floki. This adds a meme element to it and the token has performed well so far reaching an ATH of 11 million (x5500) since launch and is set to perform even better with more Floki news bound to come up in the twitter space. It has a strong community of 5000+ holders who are active on social media, particularly telegram and twitter.

How is the token being distributed? Are you conducting an airdrop?

The token was fairlaunched on the binance smart chain on 14 September 2021. There was no airdrop.

Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale? Is the token listed on a centralized/decentralized exchange?

No, the tokens were not sold at an ICO or presale. It was a fair launch (with initial liquidity of 5 BNB).
It is listed on pancakeswap, a decentralized exchange
https://pancakeswap.finance/info/token/0x71e80e96af604afc23ca2aed4c1c7466db6dd0c4

Is a Smart Contract audit completed? Where can we find this information?
Yes the smart contract audit is completed and 
it can be found here: https://88b10f67-99c2-4cbf-b973-13cb422aaa60.filesusr.com/ugd/c4baae_3f40eb7e442b4b6fa7f83de783688096.pdf

**Comment by babyflokibsc** [comment]
Hi,
Please find the response below

What is the purpose of this token? How will it benefit Trust Wallet users?

The token rewards holders with Dogecoin just for holding. Holders get
reflections on an average of 3% from buys and sells. Truswallet holders
will also be able to benefit from these rewards. Furthermore, the token is
launching NFTs in phase four of it's roadmap (The Roadmap is available in
our website www.babyfloki.info). This will add further value to token
holders. The token is named after Elon Musk's dog Floki. This adds a meme
element to it and the token has performed well so far reaching an ATH of 11
million (x5500) since launch and is set to perform even better with more
Floki news bound to come up in the twitter space. It has a strong community
of 5000+ holders who are active on social media, particularly telegram and
twitter.

How is the token being distributed? Are you conducting an airdrop?

The token was fairlaunched on the binance smart chain on 14 September 2021.
There was no airdrop.

Did you sold the tokens at an Initial Coin Offering (ICO) or a token
presale? Is the token listed on a centralized/decentralized exchange?

No, the tokens were not sold at an ICO or presale. It was a fair launch
(with initial liquidity of 5 BNB).
It is listed on pancakeswap, a decentralized exchange
https://pancakeswap.finance/info/token/0x71e80e96af604afc23ca2aed4c1c7466db6dd0c4

Is a Smart Contract audit completed? Where can we find this information?
Yes the smart contract audit is completed and
it can be found here:
https://88b10f67-99c2-4cbf-b973-13cb422aaa60.filesusr.com/ugd/c4baae_3f40eb7e442b4b6fa7f83de783688096.pdf

**Comment by babyflokibsc** [comment]
Hi Team, Is there anything I am required to do? Sorry first time here so not sure if Ive missed something.

**Comment by cryptomanz** [comment]
Could you add the links to your PR?

**Comment by babyflokibsc** [comment]
[https://88b10f67-99c2-4cbf-b973-13cb422aaa60.filesusr.com/ugd/c4baae_3f40eb7e442b4b6fa7f83de783688096.pdf](url)
[https://pancakeswap.finance/info/token/0x71e80e96af604afc23ca2aed4c1c7466db6dd0c4](url)
[www.babyfloki.info](url)

**Comment by babyflokibsc** [comment]
Hi, the links are already provided in my previous comments and I also provided them separately. Please let me know if you are looking for something else

**Comment by babyflokibsc** [comment]
I have updated the links now

**Comment by babyflokibsc** [comment]
How long will it take for the logo to be visible in trust wallet?

**Pull request merged**
