### PR TITLE
Add JeJu to Trust wallet 

### PR DESCRIPTION
**Pull request by mdfennell94**

### CODE REVIEW

**Comment by mdfennell94** [comment]
@Cryptocool1 I'm not sure what the failed checks are above, but everything should be in order, I do tons of these for folks. 

Thanks,

**Comment by Cryptocool1** [comment]
could you please answer some questions ?
• What is the purpose of this token? How will it benefit Trust Wallet users?
 • How is the token being distributed? Are you conducting an airdrop?
 • Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?
 • Is the token listed on a centralized/decentralized exchange?
 • Is a Smart Contract audit completed? Where can we find this information?

**Comment by mdfennell94** [comment]
@Cryptocool1 
 What is the purpose of this token? How will it benefit Trust Wallet users?

We are Charity Focused , Rug proof Ecosystem with Farming and multiple utilities built into our smart contract.

• How is the token being distributed? Are you conducting an airdrop?

We conducted a Presale using Dxsale. And Fair launched the token. Presale = listing price

• Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?

yes we had a Presale for the token on Dxsale.

• Is the token listed on a centralized/decentralized exchange?

it is listed on pancake swap and a small Chinese CEX and we are looking to be on bit mart of gate.io before end of October.

• Is a Smart Contract audit completed? Where can we find this information?

we are working on getting a full Audit right now.

the team has already fully doxxed to ensure our commitment to the project. 

thank you and looking forward to our logo showing on Trust Wallet

**Comment by Cryptocool1** [comment]
Will wait for smart contract audit, hold for now
thanks

**Comment by mdfennell94** [comment]
@Cryptocool1 May I ask what the hold is?
Thanks!

**Comment by Cryptocool1** [comment]
> @Cryptocool1 May I ask what the hold is?
> Thanks!

it means you token will be on hold until information about smart contract audit

**Comment by mdfennell94** [comment]
@Cryptocool1 
[JEJUDOGE.pdf](https://github.com/trustwallet/assets/files/6791816/JEJUDOGE.pdf)
Smart Contract Quick Audit.

**Pull request merged**
