### PR TITLE
New PR needed for Migration of PR (#12009)

### PR DESCRIPTION
**Pull request by PEEPScoin**
**In reference to currently listed asset (The People's Coin - PEEPS) PR #12009** 

Hello,

The People's Coin (PEEP$) has officially migrated our token smart contract and needs to update our TrustWallet GitHub as well so it sources appropriately for TW and CB Wallet users alike, among all other things that connect with TW.

**Updated Token Smart Contract:** 0x5919DeA604631016c15c805e3D948A0384879892

**Updated Token Smart Contract on Etherscan.io:**
https://etherscan.io/token/0x5919DeA604631016c15c805e3D948A0384879892

**OLD Token Smart Contract page on Etherscan.io that is already updated with "Token Migration Announcement" and the link to the updated Etherscan.io page:**
https://etherscan.io/token/0xe1030b48b2033314979143766d7dc1f40ef8ce11

**Link to "Token Migration Announcement" as listed on Etherscan.io:** https://medium.com/@PeepsChamp/the-peoples-coin-official-smart-contract-migration-re-launch-316bd4a5fd54

We airdropped all holders their exact same value of tokens prior to officially Re-Launching on June 16, 2023. We still have the same mission statement, but have not only grown, but also instituted several improved features, initiatives, and functionality for the project as we continue to grow.

**Additional Info:**

**LinkTree:** https://linktr.ee/thepeoplescoin

**Website:** https://thepeoplescoin.money

**Telegram:** https://t.me/thepeoplescoinofficial](https://t.me/thepeoplescoinofficial

**Twitter:** https://twitter.com/ThePeoples_Coin

**Facebook:** https://www.facebook.com/groups/thepeoplescoin1

**CoinMarketCap:** (updating in progress) https://coinmarketcap.com/currencies/the-peoples-coin

**CoinGecko:** (updating in progress) https://www.coingecko.com/en/coins/the-people-coin

**Github:** https://github.com/PEEPScoin

**View updated PEEP$/ETH trading pair on Uniswap:** https://v2.info.uniswap.org/pair/0xfdd0f179ae8f71e55a5aa5c39b336dda63fb17d7

**View updated PEEP$/ETH trading pair on Dextools.io:** https://www.dextools.io/app/en/ether/pair-explorer/0xfdd0f179ae8f71e55a5aa5c39b336dda63fb17d7

**Logo:** 256x256 transparent png attached

**We already made payment for a different PR, not realizing there was a different process needed to add/migrate this existing PR that was merged originally when we were listed. Here is the payment hash below:**
https://explorer.binance.org/tx/BF76147CA139852854B79F48B4539C35DD23889AD4A05F4AED9F9C21DA32CB9A

Logo

### CODE REVIEW

**Comment by Cryptocool1** [comment]
Paid

**Comment by PEEPScoin** [comment]
**Updated Project Description:** The People’s Coin (PEEP$) is a community-built project that provides a Real-World Solution to bridge the current gap between Charitable Giving & Fundraising initiatives with Blockchain Technology; providing a simple, seamless & recognizable ‘GoFundMe-like’ universal digital payment ability for ALL donating and fundraising initiatives.

**Comment by PEEPScoin** [comment]
Hello,

Thank you for merging the file. This was the patch with the correct information. Would you please assist in merging this patch to complete the accurate migration? We would very much appreciate it.

{
    "name": "The Peoples Coin (PEEP$)",
    "type": "ERC20",
    "symbol": "PEEP$",
    "decimals": 9,
    "website": "https://www.thepeoplescoin.money",
    "description": "Simply stated, The People’s Coin is a community-built project that provides a Real-World Solution to bridge the current gap between Charitable Giving & Fundraising initiatives with Blockchain Technology. PEEP$ provides a simple, yet seamless, universal digital payment option for ALL charitable organizations, foundations and fundraising campaigns.",
    "explorer": "https://etherscan.io/token/0x5919DeA604631016c15c805e3D948A0384879892",
    "status": "active",
    "id": "0x5919DeA604631016c15c805e3D948A0384879892",
    "links": [
        {
            "name": "twitter",
            "url": "https://twitter.com/ThePeoples_Coin"
        },
        {
            "name": "github",
            "url": "https://github.com/The-Peoples-Coin"
        },
        {
            "name": "telegram",
            "url": "https://t.me/thepeoplescoinofficial"
        },
        {
            "name": "medium",
            "url": "https://medium.com/@PeepsChamp"
        },
        {
            "name": "facebook",
            "url": "https://facebook.com/groups/579973076347125"
        },
        {
            "name": "whitepaper",
            "url": "https://drive.google.com/file/d/1USQI_v4Papn7IMgYrgZfgPTs2FaJLVYh/view?usp=share_link"
        }
    ],
    "tags": [
        "defi", "governance"
    ]
  
    "Refer to original PR #12009 " 
}

**Comment by PEEPScoin** [comment]
Hello,

Thank you for merging the file. This was the patch with the correct
information. Would you please assist in merging this patch to complete the
accurate migration? We would very much appreciate it.

{
"name": "The Peoples Coin (PEEP$)",
"type": "ERC20",
"symbol": "PEEP$",
"decimals": 9,
"website": "https://www.thepeoplescoin.money",
"description": "The People’s Coin (PEEP$) is a community-built project that
provides a Real-World Solution to bridge the current gap between Charitable
Giving & Fundraising initiatives with Blockchain Technology; providing a
simple, seamless & recognizable ‘GoFundMe-like’ universal digital payment
ability for ALL donating and fundraising initiatives.",
"explorer": "
https://etherscan.io/token/0x5919DeA604631016c15c805e3D948A0384879892",
"status": "active",
"id": "0x5919DeA604631016c15c805e3D948A0384879892",
"links": [
{
"name": "twitter",
"url": "https://twitter.com/ThePeoples_Coin"
},
{
"name": "github",
"url": "https://github.com/The-Peoples-Coin"
},
{
"name": "telegram",
"url": "https://t.me/thepeoplescoinofficial"
},
{
"name": "medium",
"url": ***@***.***"
},
{
"name": "facebook",
"url": "https://facebook.com/groups/579973076347125"
},
{
"name": "whitepaper",
"url": "
https://drive.google.com/file/d/1USQI_v4Papn7IMgYrgZfgPTs2FaJLVYh/view?usp=share_link
"
}
],
"tags": [
"defi", "governance"
]

"Refer to original PR #12009 "

The People's Coin

Please visit and join our socials below:
Website <https://thepeoplescoin.money> | Facebook
<https://www.facebook.com/groups/thepeoplescoin1> | Twitter
<https://twitter.com/ThePeoples_Coin> | Telegram
<https://t.me/thepeoplescoinofficial> | CoinMarketCap
<https://coinmarketcap.com/currencies/the-peoples-coin/> | Medium
***@***.***>

**Pull request merged**
