### PR TITLE
ADD BIS Logo

### PR DESCRIPTION
**Pull request by BasicIncomeStaking**

### CODE REVIEW

**Comment by BasicIncomeStaking** [comment]
In order to streamline the review of the contribution we ask you 
to ensure the following steps have been taken:

-[x] Filename in the 'lowercase' format
-[x] Image format: 'png'
-[x] Image size: '512 by 512 px'

**Comment by BasicIncomeStaking** [comment]
logo

**Comment by catenocrypt** [comment]
Image file name should be 'logo.png'.
Size is too large (max 100KB, preferred <20KB).

**Comment by BasicIncomeStaking** [comment]
logo

**Pull request merged**
