### PR TITLE
Add SUNT logo and info

### PR DESCRIPTION
**Pull request by suntrustfinance**
Add SUNT logo and info

### CODE REVIEW

**Comment by suntrustfinance** [comment]
Is my contract format correct?
If wrong, how to correct?

**Comment by suntrustfinance** [comment]
Is my contract format correct?
If wrong, how to correct?

**Comment by Cryptocool1** [comment]
hello,
what logo is the correct one?

**Comment by suntrustfinance** [comment]
> hello,
> what logo is the correct one?

What do I need to fix now, please help me

**Comment by Cryptocool1** [comment]
> > hello,
> > what logo is the correct one?
> 
> What do I need to fix now, please help me

what logo is correct? with blue background or black

**Comment by suntrustfinance** [comment]
> > > hello,
> > > what logo is the correct one?
> > 
> > 
> > What do I need to fix now, please help me
> 
> what logo is correct? with blue background or black

Thank you.
That means my information has been successfully checked and waiting for you to approve

**Comment by suntrustfinance** [comment]
When will my logo be displayed

**Comment by Cryptocool1** [comment]
correction needed:
blockchains/smartchain/assets/0x319bf3bb8ab93658074be595c4aa55cd60380af7/logo.png please delete this file

**Comment by suntrustfinance** [comment]
[](url)

> cần sửa:
> blockchains / smartchain / asset / 0x319bf3bb8ab93658074be595c4aa55cd60380af7 / logo.png vui lòng xóa tệp này

Please show me how to delete , I tried to delete but can't delete

**Comment by suntrustfinance** [comment]
> correction needed:
> blockchains/smartchain/assets/0x319bf3bb8ab93658074be595c4aa55cd60380af7/logo.png please delete this file

Please show me how to delete , I tried to delete but can't delete

**Comment by suntrustfinance** [comment]
> correction needed:
> blockchains/smartchain/assets/0x319bf3bb8ab93658074be595c4aa55cd60380af7/logo.png please delete this file

Please help, I can't do the delete operation

**Pull request merged**
