### PR TITLE
Add StarLink $STARL (ERC20)

### PR DESCRIPTION
**Pull request by ghost**
Adding info for ERC20 token 'StarLink $STARL'.

PR created by <a href="https://assets.trustwallet.com">TW Assets Management</a>

### CODE REVIEW

**Comment by jilky** [comment]
Hi there, where would I see the updated version? It hasnt showed up in the
search bar yet for trust wallet

**Comment by Cryptocool1** [comment]
hello, can you answer some questions?
• What is the purpose of this token? How will it benefit Trust Wallet users?
 • How is the token being distributed? Are you conducting an airdrop?
 • Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?
 • Is the token listed on a centralized/decentralized exchange?
 • Is a Smart Contract audit completed? Where can we find this information?

**Comment by jilky** [comment]
hello, can you answer some questions?
• What is the purpose of this token? How will it benefit Trust Wallet users?
It is a cryptocurrency gaming project, and $STARL is its governance token.
Trust wallet users can purchase this coin and be able to play in the
Starlink Metaverse.

• How is the token being distributed? Are you conducting an airdrop?
No airdrop, and by purchase through uniswap or zerion.

• Did you sold the tokens at an Initial Coin Offering (ICO) or a token
presale?
No ICO or token pre-sale just to make it fair for everybody.

• Is the token listed on a centralized/decentralized exchange?
Decentralized

• Is a Smart Contract audit completed? Where can we find this information?
https://etherscan.io/address/0x8e6cd950ad6ba651f6dd608dc70e5886b1aa6b24




Show quoted text

**Comment by cryptomanz** [comment]
hello,
starlink is already existing token
https://coinmarketcap.com/ru/currencies/star-link/

**Comment by cryptomanz** [comment]
what is the purpose of this token?

**Comment by jilky** [comment]
Starlink's STARL is used in blockchain gaming. Guests must connect to their
wallets in order to play Starlink Metaverse's MMORPG.
https://www.youtube.com/watch?v=bp406qCPSLo
Here is the video preview for the video game that they created. I actually
got to try the game yesterday too.

**Pull request merged**
