### PR TITLE
Add Bondly (BONDLY) (ERC20)

### PR DESCRIPTION
**Pull request by SA77818**
Adding info for ERC20 token 'Bondly (BONDLY)'.

PR created by <a href="https://assets.trustwallet.com">TW Assets Management</a>

### CODE REVIEW

**Comment by SA77818** [comment]
Hi, wondering what the error is here and what can be done to solve the issue? 

Used https://assets.trustwallet.com/ to create the pull request.

**Comment by Cryptocool1** [comment]
> Hi, wondering what the error is here and what can be done to solve the issue?
> 
> Used https://assets.trustwallet.com/ to create the pull request.

hello,
you need to delete incorrect files
PR should include only 2 files

**Comment by SA77818** [comment]
> > Hi, wondering what the error is here and what can be done to solve the issue?
> > Used https://assets.trustwallet.com/ to create the pull request.
> 
> hello,
> you need to delete incorrect files
> PR should include only 2 files

I deleted the additional info.json. The addition logo.png doesn't allow me to delete. https://assets.trustwallet.com/ seems to create 4 files.

**Comment by Cryptocool1** [comment]
> > > Hi, wondering what the error is here and what can be done to solve the issue?
> > > Used https://assets.trustwallet.com/ to create the pull request.
> > 
> > 
> > hello,
> > you need to delete incorrect files
> > PR should include only 2 files
> 
> I deleted the additional info.json. The addition logo.png doesn't allow me to delete. https://assets.trustwallet.com/ seems to create 4 files.

If you can't delete files in the PR, you may open a new PR. Make sure to mention this PR, so that we can see that fee has been paid already here.

**Comment by Cryptocool1** [comment]
closing this PR for now and waiting for new one.
thanks

**Pull request closed without merging**
