### PR TITLE
Add Everlasting Parachain (BEP20)

### PR DESCRIPTION
**Pull request by derrickf87**
Adding info for BEP20 token 'Everlasting Parachain'.

PR created by <a href="https://assets.trustwallet.com">TW Assets Management</a>

### CODE REVIEW

**Comment by catenocrypt** [comment]
Clarification needed: on the website (https://www.cycan.network/) I found no info on ELP, and also the logo is visually different.  Can you elaborate please?

**Comment by derrickf87** [comment]
> Clarification needed: on the website (https://www.cycan.network/) I found no info on ELP, and also the logo is visually different. Can you elaborate please?

Thank you for reviewing. About the problems you mentioned:
1. Everlasting Parachain(ELP) is the canary network of the Cycan network. The Cycan website(https://www.cycan.network/) is still being built and will be upgraded soon. Some of the latest info is not updated to the website, which includes the relationship between Everlasting Parachain and Cycan Network.
2. We have created the ELP token on Binance Smart Chain first(You may see the same logo and info as we updated on BscScan). In the future, we will deploy our own parachain based on Polkadot's canary network Kusama.
3. As for the logo, the relationship between Everlasting Parachain and Cycan Network is just as Kusama and Polkadot. We use different visual elements.

Please feel free to contact me if there are any other problems.

**Comment by derrickf87** [comment]
Thank you very much!
We found the logo is updated on Trust Wallet.
Just one other question:
How to update the logo file afterward? We would like to change the logo to a circle frame without white background.

**Comment by catenocrypt** [comment]
Update can be done similarly through a Pull Request; fee is needed though.

**Pull request merged**
