### PR TITLE
added logo and info for DMOON token (BEP20)

### PR DESCRIPTION
**Pull request by diamoons-git**

### CODE REVIEW

**Comment by dragonmoon001** [comment]
Hello, it has been a month, why can't we see our relevant information and prices on TrustWallet?

**Comment by dragonmoon001** [comment]
> Fee is PAID, fantastic! Thanks!
> 
> The PR will be evaluated soon by a maintainer, and if merged, the new logos should be visible in Trust Wallet.
> Please note that the app caches logos (up to several days; if you want to see changes immediately, use a new installation). See the [assets FAQ](https://github.com/trustwallet/assets#faq).
> (@zachzwei, @catenocrypt & @Iamdeadlyz: please take note.)
> 
> ([250.68 TWT](https://explorer.binance.org/tx/85A15FFE83D090FFA01F4B2494D0AAFE6D1C35E941A2983FE18B552A8FC2B588))

Hello, it has been a month, why can't we see our relevant information and prices on TrustWallet?

**Comment by Cryptocool1** [comment]
hello,
Снимок экрана 2021-07-10 в 19 57 50

**Comment by Cryptocool1** [comment]
however, we need to change your logo. it should be 256*256 and with transparent background

**Comment by diamoons-git** [comment]
Hey,

 

Yes, we fully agree this logo needs to be changed. How can we best do this?

 

For your reference I have attached the correct logos.

 

Your help is greatly appreciated.

 

Best,

 

Victor

 

De: CryptoA ***@***.***> 
Enviado el: sábado, 10 de julio de 2021 19:00
Para: trustwallet/assets ***@***.***>
CC: diamoons-git ***@***.***>; Mention ***@***.***>
Asunto: Re: [trustwallet/assets] added logo and info for DMOON token (BEP20) (#8879)

 

however, we need to change your logo. it should be 256*256 and with transparent background

**Comment by diamoons-git** [comment]
Hello,
   
   Please find attached the logo in 256x256.
   
   Thank you
  
  
   
    On 07/10/2021 10:44 PM Victor Diamoons Finance ***@***.***> wrote:
   
   
    
   
   
    
   
   
    Hey,
     
    Yes, we fully agree this logo needs to be changed. How can we best do this?
     
    For your reference I have attached the correct logos.
     
    Your help is greatly appreciated.
     
    Best,
     
    Victor
     
    
     De: CryptoA ***@***.***> Enviado el: sábado, 10 de julio de 2021 19:00Para: trustwallet/assets ***@***.***>CC: diamoons-git ***@***.***>; Mention ***@***.***>Asunto: Re: [trustwallet/assets] added logo and info for DMOON token (BEP20) (#8879)
    
    
    however, we need to change your logo. it should be 256*256 and with transparent background

**Pull request merged**
