### PR TITLE
Update BabyBonk Logo and Info

### PR DESCRIPTION
**Pull request by BabyBonkToken**
The Memo was already paid: 27392. Please check

### CODE REVIEW

**Comment by BabyBonkToken** [comment]
[info.json](https://github.com/trustwallet/assets/files/14277981/info.json)

**Comment by BabyBonkToken** [comment]
Now everything should be correct.

The Memo was already paid: 27392. Our Repo got accidently closed. Please check.

**Comment by BabyBonkToken** [comment]
We closed accidentally the other pull request. We have already paid for the listing before:

MEMO OF PAYMENT:: 27392.

please help here.

**Comment by BabyBonkToken** [comment]
https://explorer.bnbchain.org/tx/78537C932FC2981E7B19D05F60451D80FEB9A6827F4D27CADC94500DBAEF9146

**Comment by Cryptocool1** [comment]
Paid

**Comment by Vin757** [comment]
Will do

**Pull request merged**
