### PR TITLE
UniDark Logo

### PR DESCRIPTION
**Pull request by f4ti**
UNIDARK was created to bring together individual retail holders.
No governance hence no additional pools

### CODE REVIEW

**Comment by f4ti** [comment]
I have made payments for this request, I'm still waiting for it to be merged

**Comment by catenocrypt** [comment]
The `info.json` is incorrect, it is not JSON format.  Please change into a valid JSON of the form below:

```json
{
    "name": "Trust Wallet Token",
    "website": "https://trustwallet.com",
    "short_description": "Utility token to increase adoption of cryptocurrency.",
    "explorer": "https://explorer.binance.org/asset/TWT-8C2",
    "socials": [
        {
            "name": "Twitter",
            "url": "https://twitter.com/trustwalletapp",
            "handle": "TrustWalletApp"
        },
        {
            "name": "Reddit",
            "url": "https://reddit.com/r/trustapp",
            "handle": "TrustApp"
        }
    ]
}
```

**Comment by f4ti** [comment]
I have re uploaded it thanks a lot for the heads up. You can continue.

**Comment by f4ti** [comment]
Hello, please it hasn't updated yet.

**Comment by shaaappy** [comment]
@catenocrypt Guys. This is a scam. It doesn't deserve to have a logo on Uniswap, or anywhere else.

Let's sum this up:
- They made a Twitter account, gave free airdrop and offered the ability to buy their token at a very discounted price (1 ETH for $20,000 presale, woah)
- On their website, the buy button is labelled as "shitbuy" and "buyshit"
image
- On their Telegram channel they quoted Vitalik. Of course it's fake.
image
- Looking at their contract, a backdoor function has been found that allows them to withdraw the ETH sent to it.
image
- They claimed the Max Supply was 1024 and then claimed it was 10,000. In between.
image
image
- Best of all, they recently partnered with themselves, what a crazy thing to do.
image
Same website, same thing. Just a different name and color.
- Not to mention Unidark is already a registered trademark, they hijacked $DARK which already exist and much more but I think we got enough to see what this token truly is. A shitbuy as they call it.
- I ended up searching through the address and found they were withdrawing at Binance. I contacted Binance and they frozed their accounts.

Please do some research on tokens before merging. Having a logo on Uniswap is like EV SSL was to HTTPS there.

#WARONRUGS

**Comment by GAUTAMRAJU15** [comment]
> @catenocrypt Guys. This is a scam. It doesn't deserve to have a logo on Uniswap, or anywhere else.
> 
> Let's sum this up:
> 
> * They made a Twitter account, gave free airdrop and offered the ability to buy their token at a very discounted price (1 ETH for $20,000 presale, woah)
> * On their website, the buy button is labelled as "shitbuy" and "buyshit"
>   image
> * On their Telegram channel they quoted Vitalik. Of course it's fake.
>   image
> * Looking at their contract, a backdoor function has been found that allows them to withdraw the ETH sent to it.
>   image
> * They claimed the Max Supply was 1024 and then claimed it was 10,000. In between.
>   image
>   image
> * Best of all, they recently partnered with themselves, what a crazy thing to do.
>   image
>   Same website, same thing. Just a different name and color.
> * Not to mention Unidark is already a registered trademark, they hijacked $DARK which already exist and much more but I think we got enough to see what this token truly is. A shitbuy as they call it.
> * I ended up searching through the address and found they were withdrawing at Binance. I contacted Binance and they frozed their accounts.
> 
> Please do some research on tokens before merging. Having a logo on Uniswap is like EV SSL was to HTTPS there.
> 
> #WARONRUGS

Wow that backdoor and who the hell makes fn() like buyshit() - quite unethical and irresponsible.
Bad vibes, issa legit scam

**Comment by shaaappy** [comment]
Let's finally note that their Github account doesn't even have a profile picture, has no activity and is 2 days old. This will not work. We will kill your rug even before it starts. #WARONRUGS

**Comment by shaunpaull** [comment]
#WARONRUGZ

**Comment by Iamdeadlyz** [comment]
Hi @shaaappy,

Thanks for the heads up. Can you share more info regarding this part?
`I ended up searching through the address and found they were withdrawing at Binance. I contacted Binance and they frozed their accounts.`
Perhaps, a proof that they indeed froze their accounts.

Regarding the "backdoor", that part is common for ICO/crowdsale contracts. It is done for them to redeem the ETH that the users sent in buying the said tokens: https://ethereum.stackexchange.com/questions/89313/where-is-the-ico-price-of-this-contract

**Comment by catenocrypt** [comment]
@shaaappy , thanks for the check.  Github account was a bit suspicious.  Removing with #4564 .

**Comment by shaaappy** [comment]
> Hi @shaaappy,
> 
> Thanks for the heads up. Can you share more info regarding this part?
> `I ended up searching through the address and found they were withdrawing at Binance. I contacted Binance and they frozed their accounts.`
> Perhaps, a proof that they indeed froze their accounts (emails, etc.)
> 
> Regarding the "backdoor", that part is common for ICO/crowdsale contracts. It is done for them to redeem the ETH that the users sent in buying the said tokens: https://ethereum.stackexchange.com/questions/89313/where-is-the-ico-price-of-this-contract

Adding proofs of this means I'm leaking my identity so I'll pass on this one. There's enough proofs to process the thing.

If that's not sufficient, we can continue:

image

https://etherscan.io/token/0xafb43414e6344f6310f29e9d7dc95d817ffd89e8#comments

Another one? https://t.me/unidarkofficial

image

> It will of course list on several exchanges such as...

That's bullshit af. Nobody knows if you can enter inside an exchange in advance. The numbers of wallets are just airdropped tokens because they used influencers on Twitter to get their tweet straight to the people. And of course giving away free (yet worthless) tokens can only make a huge fuse on social networks. Actual buyers are less than 100.

There's red flags absolutely everywhere.

**Comment by shaaappy** [comment]
> @shaaappy , thanks for the check. Github account was a bit suspicious. Removing with #4564 .

Thank you! #WARONRUGS❌

**Comment by Iamdeadlyz** [comment]
> > Hi @shaaappy,
> > Thanks for the heads up. Can you share more info regarding this part?
> > `I ended up searching through the address and found they were withdrawing at Binance. I contacted Binance and they frozed their accounts.`
> > Perhaps, a proof that they indeed froze their accounts (emails, etc.)
> > Regarding the "backdoor", that part is common for ICO/crowdsale contracts. It is done for them to redeem the ETH that the users sent in buying the said tokens: https://ethereum.stackexchange.com/questions/89313/where-is-the-ico-price-of-this-contract
> 
> Adding proofs of this means I'm leaking my identity so I'll pass on this one. There's enough proofs to process the thing.
> 
> If that's not sufficient, we can continue:
> 
> image
> 
> https://etherscan.io/token/0xafb43414e6344f6310f29e9d7dc95d817ffd89e8#comments
> 
> Another one? https://t.me/unidarkofficial
> 
> image
> 
> > It will of course list on several exchanges such as...
> 
> That's bullshit af. Nobody knows if you can enter inside an exchange in advance. The numbers of wallets are just airdropped tokens because they used influencers on Twitter to get their tweet straight to the people. And of course giving away free (yet worthless) tokens can only make a huge fuse on social networks. Actual buyers are less than 100.
> 
> There's red flags absolutely everywhere.

Noted. Thanks for reporting!

**Pull request merged**
