### PR TITLE
Add SHIELD Logo and Info

### PR DESCRIPTION
**Pull request by rahulsharma0856**
Official Logo and Information by SHIELD PROTOCOL.

### CODE REVIEW

**Comment by catenocrypt** [comment]
Issues with this PR:
- as this is a BEP20 token on BSC, not BEP2, location should be `blockchains/smartchain/assets/0x60b3BC37593853c04410c4F07fE4D6748245BF77`.  Please move the folder to this location.
- Circulation: explorer shows 1460 holders.  We have a minimum limit of 2500 holders.  We can wait some more time until that number is reached and merge then.

**Comment by rahulsharma0856** [comment]
**- Folder moved from our side.**
**- Circulation: Right now explorer shows 1664 holders even some time ago, it was 1821 holders. Our holders really wants to input our token information on trustwallet. Even your team can check transactions till date as ready reference. It will be really appreciable, if your team can consider this merge request.**  

> Issues with this PR:
> 
> * as this is a BEP20 token on BSC, not BEP2, location should be `blockchains/smartchain/assets/0x60b3BC37593853c04410c4F07fE4D6748245BF77`.  Please move the folder to this location.
> * Circulation: explorer shows 1460 holders.  We have a minimum limit of 2500 holders.  We can wait some more time until that number is reached and merge then.

**Comment by catenocrypt** [comment]
- New logo under blockchains/binance is still there, should be removed

```
-  X 'Binance chain; assets must exist on chain':  1 errors
   X   'Asset 0x60b3bc37593853c04410c4f07fe4d6748245bf77 missing on chain'
```

- New logo+info under blockchains/smartchain is not in checksum format, causing check error.  Should be renamed.  May need rename in two phases, as it is only lowercase-uppercase change, and may be filtered out by filesystem.

```
    X   'Expect asset at path /home/runner/work/assets/assets/blockchains/smartchain/assets/0x60b3bc37593853c04410c4f07fe4d6748245bf77 in checksum: '0x60b3BC37593853c04410c4F07fE4D6748245BF77''
```

**Comment by rahulsharma0856** [comment]
As per your previous advice, Corrections are done from our side.

**Comment by rahulsharma0856** [comment]
@catenocrypt @zachzwei @hexorx @rfunduk Now, 2500 holders limit crossed by project. Still, We are waiting for your response.

**Comment by catenocrypt** [comment]
Circulation is OK.

There is one small issue: ID field in info.json should be in checksum format.  I would fix this. but I don't have write access to this PR.

Please change to:

```
    "id": "0x60b3BC37593853c04410c4F07fE4D6748245BF77"
```

```
    X   'Incorrect id '0x60b3bc37593853c04410c4f07fe4d6748245bf77' '/home/runner/work/assets/assets/blockchains/smartchain/assets/0x60b3BC37593853c04410c4F07fE4D6748245BF77/info.json'
```

**Comment by rahulsharma0856** [comment]
@catenocrypt Done. Now you can merge the request.

**Comment by catenocrypt** [comment]
OK, thanks

**Comment by rahulsharma0856** [comment]
@catenocrypt Can you please tell us, When our "SHIELD PROTOCOL"  Prices will be update into trust wallet? Because 13 days ago, Our token listed into trust wallet and still our users are not able to see prices of our token into trust wallet. It will be really appreciated, if you can update it from backend.

**Pull request merged**
