### PR TITLE
Add TrueFi TrueUSD (tfTUSD)

### PR DESCRIPTION
**Pull request by ryanrodenbaugh**
tfTUSD represents a users TUSD deposit into the TrueFi protocol's lending pool

I know we're short of the 2,500 token holders, but we're also the same team that originally developed TUSD, TGBP, THKD, and most recently TRU so we're not new to crypto :)

### CODE REVIEW

**Comment by rrodenbaugh** [comment]
Hi @catenocrypt you correctly pointed out on my last submission (https://github.com/trustwallet/assets/pull/5808) that my files weren't in 'blockchains/ethereum/assets/
', but I believe I've now correctly moved them there. Could you help me understand what I did wrong this time? thank you!

**Comment by catenocrypt** [comment]
Decimals field should be number, and folder should be in checksum folder.  I did these fixes.

**Comment by rrodenbaugh** [comment]
> Decimals field should be number, and folder should be in checksum folder. I did these fixes.

Thank you 🙏🏻 Will get the fee paid ASAP

**Comment by rrodenbaugh** [comment]
I know we're short of the 2,500 token holders, but we're also the same team that originally developed TUSD, TGBP, THKD, and most recently TRU so we're not new to crypto :) You all were very kind to approve TRU's logo when it was <2,500 holders. While we don't want to take advantage of your kindness, we'd be very grateful if that could happen again for tfTUSD. I think having the TrustWallet logo approved everywhere helps the token grow! 

p.s., if you are kind enough to merge this one, we have one more token stkTRU which we will also make a request for next <3

**Pull request merged**
