### PR TITLE
Adding CashDog 

### PR DESCRIPTION
**Pull request by mrkawdy**
Adding CashDog's info and logo to Trustwallet's Smart Chain assets.

### CODE REVIEW

**Comment by mrkawdy** [comment]
Paid for CashDog submission to trust wallet. Let me know if there's anything else you need on my end. Thank you!

**Comment by Cryptocool1** [comment]
blockchains/ethereum/assets/0x84679bc467DC6c2c40ab04538813AfF3796351f1/info.json
do you want to add only CashDog?

**Comment by mrkawdy** [comment]
Yes we just want to add CashDog

**Comment by Cryptocool1** [comment]
> Yes we just want to add CashDog

so, why you added "CHONK"

**Comment by mrkawdy** [comment]
Because I had added it earlier, must be some issue due to updated requirements

**Comment by mrkawdy** [comment]
I could add CashDog from a new account if needed and we could close this request if you guys are unable to add through this pull request

**Comment by mrkawdy** [comment]
Just let me know ASAP so we can proceed forward, sorry for the inconvenience @Cryptocool1

**Comment by mrkawdy** [comment]
Should we just re-apply with a separate account? Is the CHONK thing still an issue?

**Comment by Cryptocool1** [comment]
> Should we just re-apply with a separate account? Is the CHONK thing still an issue?

I suggest to create a new PR (and mention this one so that fee does not have to be paid again).
 • You may use our Assets app (in beta); close this PR; go to https://assets.trustwallet.com, log on with Github, enter contract ID, logo and some additional info, and it will create a PR for you. See https://community.trustwallet.com/t/how-to-submit-a-token-logo-using-assets-app/82957\

**Pull request closed without merging**
