### PR TITLE
Add hybrix project, info and logo files

### PR DESCRIPTION
**Pull request by agent725**
This pull request facilitates the information and logo Uniswap needs for the hybrix project.

### CODE REVIEW

**Comment by agent725** [comment]
We have sent a donation to Trustwallet.

Transaction ID: 63E6D7C2A36A5640D6AC0B6A8D07D02FA76852713A296746C78060A0DBE4C894

**Comment by agent725** [comment]
Cheers! :-) Keep up the good work everybody!

**Comment by zachzwei** [comment]
I checked CMC and saw that this is only an ERC20 token. Does this project have its own blockchain?

**Comment by agent725** [comment]
Hi Zach! No, our project doesn't need its own chain. We run on all the ones that already exist. HY is designed to be capable of moving between already existing chains. The ERC20 mode is already active so it could be easily traded, and we could start drawing some attention. Other modes are in development.

**Pull request merged**
