### PR TITLE
SMOON logo and info.json

### PR DESCRIPTION
**Pull request by saylormoonarmy**
Just that, to add the logo and info

### CODE REVIEW

**Review by saylormoonarmy — COMMENTED** [review]
some edits

**Comment by saylormoonarmy** [comment]
logo and json

**Comment by saylormoonarmy** [comment]
info for SMOON token

**Comment by saylormoonarmy** [comment]
info for SMOON token

**Comment by Cryptocool1** [comment]
Duplicate of #8778

**Pull request closed without merging**
