### PR TITLE
Add Dogecoin 2.0 Logo (We paid, adding a new PR)

### PR DESCRIPTION
**Pull request by CharlieAKAN**
We were told if we got a contract audit then we should create new PR and mention we already paid.

The past PR we paid on is here: #11465
Smart Contract Audit: https://dessertswap.finance/audits/Dogecoin%202.0%20BEP-20%20Transparency%20Audit%209216588.pdf

### CODE REVIEW

**Comment by cryptomanz** [comment]
as @Cryptocool1 mentioned,
please create new PR when CMC listing will be ready.

**Comment by CharlieAKAN** [comment]
Would it be possible to get an explanation to why we need CMC? We meet all the requirements now with our audit but why does CMC matter for us when it's not in your requirements?

Trust Wallet added Baby Doge's logo with the same audit company, just wondering what the difference is so I completely understand when I go tell my community why DOGE2 logo is still not on Trust Wallet.

Here is our audit: https://dessertswap.finance/audits/Dogecoin%202.0%20BEP-20%20Transparency%20Audit%209216588.pdf

**Comment by CharlieAKAN** [comment]
I would appreciate some response to this... Our community worked hard to pay your fee and to pay for the audit you told us we needed to get but then Trust Wallet moved the goal post.... 

Could you please example why we need CMC listing when BabyDoge used the same company for their audit but you won't use ours... Thank you.

**Comment by CharlieAKAN** [comment]
(adding this here as well) 

Hi there...

Our community is asking for a refund as we were unaware of your new CMC requirement and that money could be used else where right now.

TokenPocket added our logo and pricing today to their wallet and many of our members are moving there. So we may return when the CMC is listed.

**Pull request closed without merging**
