### PR TITLE
Add Panther Protocol (ZKP) token and logo

### PR DESCRIPTION
**Pull request by aspiers**
Relevant links:

- https://pantherprotocol.io/
- https://coinmarketcap.com/currencies/panther-protocol/
- https://www.coingecko.com/en/coins/panther-protocol

### CODE REVIEW

**Comment by aspiers** [comment]
We're working on obtaining discord.com links, and also changing the logo be exactly 256x256 pixels.  Once we've updated the PR, we'll pay the fee.

**Comment by Cryptocool1** [comment]
As per our policy, there is a minimum requirement of 10,000 holder addresses and 15,000 transactions, in order to filter out scam tokens.
See the criteria at : https://developer.trustwallet.com/assets/requirements .

**Comment by aspiers** [comment]
Hi @Cryptocool1, thanks very much for the quick response and review.

I appreciate the valuable initiative to filter out scam tokens, but [your own requirements state that the 10,000 holders / 15,000 transactions thresholds are "subject for review based on the project"](https://developer.trustwallet.com/assets/requirements#listing-acceptance-guidelines) rather than being a hard requirement:

image

If you review the links provided in this PR, you will see a lot of information which shows why Panther is not a scam project, and  that all your other requirements are fulfilled.  To take one example, [our blog](https://blog.pantherprotocol.io/) shows our current areas of activity.  The project was founded in 2020, but the token was launched in January 2022, so while it is far from brand new, it is much younger than the project.

We are of course happy to answer any concerns or other questions you may have, and we would be glad to pay the fee to have this entry reviewed.  Thanks again.

**Comment by aspiers** [comment]
- What is the purpose of this token?
  - Quoting from [our documentation](https://docs.pantherprotocol.io/dao/support/faq/zkp-token#what-is-usdzkp-used-for):

    > $ZKP is a utility and governance token. It is used to participate in incentivized voting on DAO governance matters such as grants, new Panther Improvement Proposals, and protocol fees. In the protocol itself, $ZKP can:
    > - Be privately staked to earn rewards for adding tokens to Pools and increasing the anonymity set.
    > - Be earned by relayers as they pay for fees privately on behalf of users, furthering anonymity.
    > - Be staked by token holders to secure the interchain bridges in an AMM model.
    > - Be optionally used by users to pay for services on the platform at a discounted rate, such as:
    >   #. To pay for mint and burn fees associated with zAssets.
    >   #. To pay transaction fees for sending zAssets.
    >   #. To pay Panther Reveal fees;
    >   #. To pay for DEX trades.
    > - Be used by the DAO to pay for services provided to the protocol such as:
    >   #. To pay incentive fees to privacy stakers and transactors;
    >   #. To pay relayer service fees;
    >   #. To pay DEX stakers securing vaults;
    >   #. To pay DEX liquidity providers (LPs);
    >   #. To pay voting stakers.
    >
    > The DAO can purchase $ZKP from the open market using the fees collected from users receiving discounts. These fees will then be used by the Panther DAO to pay for all the services above.

- How will it benefit Trust Wallet users?
  - Listing $ZKP will extend the above benefits to Trust Wallet users.  Currently $ZKP holders are predominantly using MetaMask, but we would like to change that.

- How is the token being distributed?
  - Token distributed started according to [our tokenomics schedule](https://docs.pantherprotocol.io/dao/token/tokenomics), when we conducted [the initial TGE on Jan 31st 2022](https://blog.pantherprotocol.io/zkps-token-generation-event-huobi-listing-and-staking-are-underway-here-s-our-recap-a4e1f6dc0130/).  Seed investors, private rounds, and a large portion of the public sale were distributed at that time.  Since then, minting and vesting has occurred on a regular basis, and you can see the exact parameters [here](https://docs.pantherprotocol.io/launchdao/voting-proposals/3-launch/mint-and-vest).

- Are you conducting an airdrop?
  - No, but we have provided rewards for various types of participation, e.g. [our bug bounty program](https://blog.pantherprotocol.io/wave-3-of-incentivized-advanced-staking-testing-begins-on-july-7th/).

- Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?
  - There were pre-seed and seed rounds, followed by private sales, and then finally [a public sale which sold out in 90 minutes](https://blog.pantherprotocol.io/the-panther-protocol-public-sale-has-successfully-closed-in-under-90-minutes-fae4f83f6734/), raising around $20m.

- Is the token listed on a centralized/decentralized exchange?
  - Yes, [it's listed on Huobi, Bitrex, and Uniswap](https://www.coingecko.com/en/coins/panther-protocol#markets), with more exchanges to come.

- Is a Smart Contract audit completed? Where can we find this information?
  - Yes, these are listed under the Resources dropdown from [our website](https://pantherprotocol.io/):
    - [Audit of ZKP token contracts](https://pantherprotocol.io/resources/REP-Panther-ZKP-Token.pdf)
    - [Audit of ZKP token vesting contracts](https://pantherprotocol.io/resources/REP-Panther-ZKP-Vesting.pdf)

Also please note that we do have more than 10,000 token holders and 15,000 transactions; however they are split across two chains:

- [4,696 holders and 21,242 transfers on Ethereum mainnet](https://etherscan.io/token/0x909e34d3f6124c324ac83dcca84b74398a6fa173)
- [5,724 holders and 48,957 transfers on Polygon](https://polygonscan.com/token/0x9a06db14d639796b25a6cec6a1bf614fd98815ec#balances)

Thanks again for your consideration!

**Comment by Cryptocool1** [comment]
Ok, sounds good. Please create new PR, because I cannot reopen this one

**Comment by aspiers** [comment]
Sure!  Submitted as #21484.

**Pull request closed without merging**
