### PR TITLE
Add American Akita (ERC20)

### PR DESCRIPTION
**Pull request by Arturiz**
Adding info for ERC20 token 'American Akita'.

PR created by <a href="https://assets.trustwallet.com">TW Assets Management</a>

### CODE REVIEW

**Comment by Arturiz** [comment]
Why have the checks failed?

**Comment by Arturiz** [comment]
I am very new to this how do I fix it ? at least point me to the right direction.

**Comment by Arturiz** [comment]
@zachzwei @catenocrypt @Iamdeadlyz Can you guys help me with this?

**Comment by Cryptocool1** [comment]
Hello, 
PR should include only 2 files. Please delete incorrect files

**Comment by Arturiz** [comment]
> Hello,
> PR should include only 2 files. Please delete incorrect files

sorry very silly question but I'm new here. But how do I delete them I don't really see an option.. and  when I get them deleted do I resubmit pull request or will this continue to check ?

**Comment by Cryptocool1** [comment]
> > Hello,
> > PR should include only 2 files. Please delete incorrect files
> 
> sorry very silly question but I'm new here. But how do I delete them I don't really see an option.. and when I get them deleted do I resubmit pull request or will this continue to check ?

Ok, I’ll delete)

**Comment by Arturiz** [comment]
> > > Hello,
> > > PR should include only 2 files. Please delete incorrect files
> > 
> > 
> > sorry very silly question but I'm new here. But how do I delete them I don't really see an option.. and when I get them deleted do I resubmit pull request or will this continue to check ?
> 
> Ok, I’ll delete)

That would be great as It added them automatically from my previous pulls... not sure how to get rid of them. will this work after that ?

**Pull request merged**
