### PR TITLE
Update DADDY FEG logo + info

### PR DESCRIPTION
**Pull request by DADDYFEG**

### CODE REVIEW

**Comment by Cryptocool1** [comment]
Hello, what is the purpose of this token?

**Comment by DADDYFEG** [comment]
> Hello, what is the purpose of this token?

DADDY FEG token will serve as a launchpad for legitimate organizations and projects in the De-Fi Binance Smart Chain space. Tokens who want to be featured on the DADDY FEG token site will need to pay to become partners and be promoted. The launchpad serves the purpose of weeding out illegitimate projects and confirming project activity with team leaders. Any projects found to be associated with projects that failed early will automatically be rejected, due to a poor track record.

**Comment by Cryptocool1** [comment]
How will it benefit Trust Wallet users?
 • How is the token being distributed? Are you conducting an airdrop?
 • Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?
 • Is the token listed on a centralized/decentralized exchange?
 • Is a Smart Contract audit completed? Where can we find this information?

**Comment by DADDYFEG** [comment]
> How will it benefit Trust Wallet users?
> • How is the token being distributed? Are you conducting an airdrop?
> • Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?
> • Is the token listed on a centralized/decentralized exchange?
> • Is a Smart Contract audit completed? Where can we find this information?

How will it benefit Trust Wallet users?

Users will be able to monitor their finances in real time. 

• How is the token being distributed? Are you conducting an airdrop?

The token is being distributed on pancakeswap where users can buy $DADDYFEG and there is a 2% reflection back to the user’s wallets.

• Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?

Yes it was sold on dxsale. 

• Is the token listed on a centralized/decentralized exchange?

Yes it is on pancakeswap. 

• Is a Smart Contract audit completed? Where can we find this information?

We are in the process of completing a tech audit reviews

**Comment by Cryptocool1** [comment]
will Wait for smart contract audit, hold for now

**Comment by DADDYFEG** [comment]
[DADDY FEG  Full Smart Contract Security Audit.pdf](https://github.com/trustwallet/assets/files/6780338/DADDY.FEG.Full.Smart.Contract.Security.Audit.pdf)


> will Wait for smart contract audit, hold for now

**Pull request merged**
