### PR TITLE
Commit added coins to Trust Wallet

### PR DESCRIPTION
**Pull request by geopayme**

### CODE REVIEW

**Comment by geopayme** [comment]
Funds were send with memo 1859

**Comment by geopayme** [comment]
I have performed the payment of 0.5 BNB with memo 1859.

**Comment by geopayme** [comment]
Thank you, do you know why the GRD image did not sync?

**Comment by kolya182** [comment]
> Thank you, do you know why the GRD image did not sync?

Show me what you see ?

**Comment by geopayme** [comment]
I see a circle with a ERC20 in the middle for the Greek Drachma Token
Screenshot_20200414-015801

**Comment by kolya182** [comment]
> I see a circle with a ERC20 in the middle for the Greek Drachma Token
> Screenshot_20200414-015801

in which PR did you add logo for Greek token ?

**Comment by geopayme** [comment]
Geopay:master / 0x2915ACAA744E36BEFB3C539C3D99D7F82AD8E6C9

**Comment by kolya182** [comment]
> 0x2915ACAA744E36BEFB3C539C3D99D7F82AD8E6C9

This is address, not a contract address

**Comment by geopayme** [comment]
image

**Comment by kolya182** [comment]
> > I see a circle with a ERC20 in the middle for the Greek Drachma Token
> > Screenshot_20200414-015801
> 
> in which PR did you add logo for Greek token ?

What is this wallet address ?

**Comment by geopayme** [comment]
image

**Comment by kolya182** [comment]
And which logo do you want for it ?

**Comment by geopayme** [comment]
0xEA604A000f2Df23CE67611a1Aefd659450b41B0e the trust wallet - and the image is this 
logo

**Comment by kolya182** [comment]
Added here, check your wallet now https://github.com/trustwallet/assets/commit/b934def1e229f03abc13a4d1f698a428ead883fb

**Comment by geopayme** [comment]
It worked.. thank you..

**Pull request merged**
