### PR TITLE
Add KOKO token to smartchain assets

### PR DESCRIPTION
**Pull request by kokoswapdev**

### CODE REVIEW

**Comment by cryptomanz** [comment]
• Is a Smart Contract audit completed? Where can we find this information?

**Comment by kokoswapdev** [comment]
hi @cryptomanz ,

Audit is not yet completed. 


Thank you

**Comment by cryptomanz** [comment]
Awaiting for smart contract audit, on hold for now.

**Comment by kokoswapdev** [comment]
Hi @cryptomanz ,



Audit report: https://github.com/interfinetwork/smart-contract-audits/blob/audit-updates/Kokoswap_AuditReport_InterFi.pdf


Please let me know if you have any questions.

Thank you.

**Comment by kokoswapdev** [comment]
> Awaiting for smart contract audit, on hold for now.

Hi there,

Kokoswap audit is successfully completed.

Audit report: https://github.com/interfinetwork/smart-contract-audits/blob/audit-updates/Kokoswap_0x7320c128e89bA4584Ab02ed1C9c96285b726443C.pdf

Please let me know if you have any questions.

Thank you.

**Pull request merged**
