### PR TITLE
Add DARC-087 (BEP-2) and DARC (BEP-20) and remove DARC-24B (BEP-2)

### PR DESCRIPTION
**Pull request by bombs-kim**
#14978 (Fee has been paid already)

We recently decided to renew the existing BEP-2 token and issue new BEP-20.

For details please refer to the post below.
https://medium.com/@konstellation/konstellation-darcwallet-check-darc-airdrop-alert-20928765b212

For further inquiry or verification,
please contact Info@konstellation.tech

### CODE REVIEW

**Comment by bombs-kim** [comment]
#14978

**Comment by Cryptocool1** [comment]
can you send me an official information about abandoned status?

**Comment by Cryptocool1** [comment]
> can you send me an official information about abandoned status?

no answer yet. Come back to us when you will be ready for conversation. thanks
When creating a new PR make sure to mention this PR, so that we can see that fee has been paid already here.

**Comment by bombs-kim** [comment]
@Cryptocool1 
Sorry for keeping you waiting. This is the official announcement. 
https://konstellation.medium.com/announcement-support-for-darc-24b-has-ended-aaa34fb4b575
Could you reopen this issue and merge the commits?

**Pull request closed without merging**
