### PR TITLE
Add Dogicoin (BEP20)

### PR DESCRIPTION
**Pull request by SeChainSNN**
Adding info for BEP20 token 'Dogicoin'.

PR created by <a href="https://assets.trustwallet.com">TW Assets Management</a>

### CODE REVIEW

**Comment by SeChainSNN** [comment]
dear sir,
payment done 

please update the logo

**Comment by SeChainSNN** [comment]
dear sir,
please update the logo , payment done .

**Comment by Cryptocool1** [comment]
As per our policy, brand new tokens are not included, there is a minimum requirement of 2500 holder addresses and 5000 transactions, in order to filter out scam tokens.
See the criteria at (mentioned in the first message by the bot): https://community.trustwallet.com/t/how-to-submit-a-token-logo/3863).

**Comment by catenocrypt** [comment]
Besides, token name and logo is very easily confusable with well-known Dogecoin.  Closing for now.

**Pull request closed without merging**
