### PR TITLE
Add Akita Inu (AKITA) (ERC20)

### PR DESCRIPTION
**Pull request by Amirahmdpwr**
Adding info for ERC20 token 'Akita Inu'.

PR created by <a href="https://assets.trustwallet.com">TW Assets Management</a>

### CODE REVIEW

**Comment by Amirahmdpwr** [comment]
Hello,have a great day . I couldn't fix the CoinGecko link , is that ok? All other things are fix ? Can i proceed for payment?

**Comment by Amirahmdpwr** [comment]
This PR is only to update Akita logo and info . But it says this PR includes 2 tokens . Should i make a new pr?

**Comment by Amirahmdpwr** [comment]
@Cryptocool1

**Comment by Cryptocool1** [comment]
Please delete your branch and create new PR.

**Pull request closed without merging**
