### PR TITLE
Update WHIRL info

### PR DESCRIPTION
**Pull request by whirlfinance**

### CODE REVIEW

**Comment by catenocrypt** [comment]
After merging latest master, the only diff is a 3 lines updated in info.json.
Please confirm that this is the intention.

**Comment by catenocrypt** [comment]
Correction needed: the info.json is invalid JSON format, commas are missing after keys `audit`, `provider`, and `backup_provider`.

**Comment by openb0x** [comment]
Hello, please check  info.json. The line "website": contains the old URL, since the new one ends with .io (https://whirlfinance.io/)

**Comment by openb0x** [comment]
Hello, please check info.json. 1. The line "website": contains the old URL, since the new one ends with .io (https://whirlfinance.io/). 2. Description line has an inflated description of the project. 3. Site does not indicate any information about the team (anonymous)

**Review by splawless — COMMENTED** [review]
[@_****_](https://github.com/NixOS/nixpkgs/pull/128798/files)

**Review by splawless — COMMENTED** [review]
[_**@[@_****_](https://github.com/NixOS/nixpkgs/pull/128798/files)**_](https://github.com/NixOS/nixpkgs/pull/128798/files)

**Pull request merged**
