### PR TITLE
Add SNS Logo and info

### PR DESCRIPTION
**Pull request by SolarSystemsNFT**

### CODE REVIEW

**Comment by Cryptocool1** [comment]
As per our policy, brand new tokens are not included, there is a minimum requirement of 5000 holder addresses and 10000 transactions, in order to filter out scam tokens.
See the criteria at (mentioned in the first message by the bot): https://community.trustwallet.com/t/how-to-submit-a-token-logo/3863).

**Comment by SolarSystemsNFT** [comment]
Hello!
More than 10,000 holder

**Comment by Cryptocool1** [comment]
can you answer some questions 
• What is the purpose of this token? How will it benefit Trust Wallet users?
 • How is the token being distributed? Are you conducting an airdrop?
 • Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?
 • Is the token listed on a centralized/decentralized exchange?
 • Is a Smart Contract audit completed? Where can we find this information?

**Comment by SolarSystemsNFT** [comment]
Hello! I will be happy to answer your questions in detail!

1. Our token is supposed to be an innovative online blockchain game with the integration of nft in the form of planets, states and resources
The value of the token lies in the fact that it will be used to complete the development of the Solar systems NFT platform nftsolar.systems.
Where users can also use them to participate in the construction of their NFT products

How will it benefit Trust Wallet users? -
At the moment, we are working with a huge promotion company on YouTube and other social networks that could make instant payments through Trust Wallet and opinion leaders will be able to share their opinions about our token and use it in your wallet.


2. We are not currently carrying out an airdrop, but we are planning to do it a little later for the distribution of valuable game materials, which will be possible to farm on the binance smartchain 

3. In the process of presale 

4. Website&pancakeswap

5. We did not audit the smart contract.
However, our code is open and readable, it is written on a reliable basis and checked by specialists, opinion leaders already agree on its legitimacy and soon the materials of our partners will be released, this is indicated in the stages on our "solarpaper"

**Comment by cryptomanz** [comment]
- can you please add links to your PR?
example: https://developer.trustwallet.com/add_new_asset#info-json-contents

**Comment by cryptomanz** [comment]
Awaiting for smart contract audit.

**Comment by SolarSystemsNFT** [comment]
Why error?
Reason for discrimination?

**Comment by Cryptocool1** [comment]
where discrimination?

**Comment by Cryptocool1** [comment]
you missed the comma

**Comment by Cryptocool1** [comment]
fixed

**Comment by SolarSystemsNFT** [comment]
fixed

**Comment by Cryptocool1** [comment]
Hello,
please create new PR when smart contract audit will be ready.
make sure to mention this PR, so that we can see that fee has been paid already here.

**Comment by SolarSystemsNFT** [comment]
What is the reason for discrimination?
Why don't you request an audit from others?
Despite the fact that we use publicly available smart contracts, the projects of which have you added?

**Pull request closed without merging**
