### PR TITLE
Add BIGH BULL (BEP20)

### PR DESCRIPTION
**Pull request by BighBullTech**
Adding info for BEP20 token 'BIGH BULL'.

PR created by <a href="https://assets.trustwallet.com">TW Assets Management</a>

### CODE REVIEW

**Comment by Cryptocool1** [comment]
• What is the purpose of this token? How will it benefit Trust Wallet users?
 • How is the token being distributed? Are you conducting an airdrop?
 • Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?
 • Is the token listed on a centralized/decentralized exchange?
 • Is a Smart Contract audit completed? Where can we find this information?

**Comment by BighBullTech** [comment]
> • What is the purpose of this token? How will it benefit Trust Wallet users? • How is the token being distributed? Are you conducting an airdrop? • Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale? • Is the token listed on a centralized/decentralized exchange? • Is a Smart Contract audit completed? Where can we find this information?


To Support Community with Various subject like trading, swaping, value creation, utility with exchange. 
We have plan to swap with trust wallet as well as listing on decentralized exchange.
See our advisory board with best in market & financial world.
Yes now we are doing private sale & ICO
Not now Listed After ICO will move top 5 Exchanges
Audit report will be provided if you want as a link on website.
All info available at website.

**Comment by BighBullTech** [comment]
Is it Ok

**Comment by BighBullTech** [comment]
Uploaded Audit Report

**Comment by BighBullTech** [comment]
R U There

**Comment by BighBullTech** [comment]
[Bigh Bull-Audit-Report.pdf](https://github.com/trustwallet/assets/files/7644438/Bigh.Bull-Audit-Report.pdf)

**Pull request merged**
