### PR TITLE
Add Elgos Company Token (BEP20)

### PR DESCRIPTION
**Pull request by SymmaBlockchain**
Adding info for BEP20 token 'Elgos Company Token'.

PR created by <a href="https://assets.trustwallet.com">TW Assets Management</a>

### CODE REVIEW

**Comment by Cryptocool1** [comment]
• What is the purpose of this token? How will it benefit Trust Wallet users?
 • How is the token being distributed? Are you conducting an airdrop?
 • Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?
 • Is the token listed on a centralized/decentralized exchange?
 • Is a Smart Contract audit completed? Where can we find this information?

**Review by See887777 — APPROVED** [review]

**Review by Ozturkfath — APPROVED** [review]
?

**Comment by SymmaBlockchain** [comment]
• What is the purpose of this token? How will it benefit Trust Wallet users?
A - Thank you for asking, this is really important for us. 
Elgos Company Token is a fraction of our Company, what makes possible tô all our users have benefits from it.
Users and drivers, can have zero taxes by having those tokens.
They have shares of our Company.
We are a Defi project that really care about security, we want all users to see that we care about their actives. Trust is the safest place.

• How is the token being distributed? Are you conducting an airdrop?
A - Se had an private sale, the tokens had already been send to the wallets. We have an ICO on the way, but some of the tokens can be bought on "Mercado Pago", an centralized Brazilian exchange..

• Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?
A - We had a private pre-sale. And users have already been bonified by holding our tokens. 
We have an ICO on the way, on 15/03/2022.

• Is the token listed on a centralized/decentralized exchange?
A -  Yes, currently Elgos can be bought on a centralized Brazilian exchange called "Mercado Pago".

• Is a Smart Contract audit completed? Where can we find this information?
A -  Our compliance team are working on a pulbic audit for our token. 

We are currently working on, users weach have a certain amount of our tokens, they would be able tô open franchises of our company.
Elgos os a urban mobility company, and veichle tracking os one of our products.

**Comment by cryptomanz** [comment]
Awaiting for smart contract audit. On hold for now

**Comment by cryptomanz** [comment]
Please come back to us when all criteria are met.
When creating a new PR make sure to mention this PR, so that we can see that fee has been paid already here.

**Pull request closed without merging**
