### PR TITLE
Add TWT logo and info

### PR DESCRIPTION
**Pull request by NFTC**
thanks

### CODE REVIEW

**Comment by cryptomanz** [comment]
11890

**Comment by cryptomanz** [comment]
This description for the token not the product overview.
please change

**Comment by NFTC** [comment]
Hello mate !
Do we need to send another 2000 TWT to continue to be approved.

**Comment by Cryptocool1** [comment]
> Hello mate !
> Do we need to send another 2000 TWT to continue to be approved.

hi, you don't need to pay one more time

**Comment by cryptomanz** [comment]
can we see the  audit?

**Comment by NFTC** [comment]
> can we see the audit?

We are doing an audit by https://www.rdauditors.com/

**Comment by cryptomanz** [comment]
> > can we see the audit?
> 
> We are doing an audit by https://www.rdauditors.com/

where your audit?
can you send?

**Comment by NFTclassic** [comment]
> > > can we see the audit?
> > 
> > 
> > We are doing an audit by https://www.rdauditors.com/
> 
> where your audit?
> can you send?

We will send it to you as soon as the audit results are available. thanks

**Comment by NFTC** [comment]
> > > can we see the audit?
> > 
> > 
> > We are doing an audit by https://www.rdauditors.com/
> 
> where are your audit?
> can you send?

We will send it to you as soon as the audit results are available. thanks

**Comment by Cryptocool1** [comment]
Hello,
please create new PR when smart contract audit will be ready.
make sure to mention this PR, so that we can see that fee has been paid already here.

**Pull request closed without merging**
