### PR TITLE
Added swap FREE Coin BSC

### PR DESCRIPTION
**Pull request by barzas65**

### CODE REVIEW

**Review by vikmeup — APPROVED** [review]

**Comment by temmmma** [comment]
@catenocrypt merge and upload please

**Comment by catenocrypt** [comment]
Tokenlist (list of supported swaps) is maintained by our team, no external changes accepted.

**Comment by temmmma** [comment]
@catenocrypt need to add liquidity?

**Comment by catenocrypt** [comment]
We have limits on liquidity (min 2M) and also number of txs
Note that if it is not added to our swap, it is still tradable using Pancakswap Dapp within Trust Wallet

**Comment by temmmma** [comment]
@catenocrypt 
photo_2021-04-20_12-43-24

However Liquidity displayed in statistics does not correspond with reality, also volume in statistics is very much below the volume published on Coingecko and Coinmarketcap: https://pancakeswap.info/token/0x12e34cDf6A031a10FE241864c32fB03a4FDaD739

both CMC and Coingecko give daily volume between 4 million USD and 15 million USD, over last weeks

**Comment by temmmma** [comment]
@catenocrypt any updates?

**Comment by temmmma** [comment]
@Cryptocool1 please help

**Pull request closed without merging**
