### PR TITLE
Add Neiro logo and info

### PR DESCRIPTION
**Pull request by lizqlife**
Add Neiro logo and info

### CODE REVIEW

**Comment by cryptomanz1** [comment]
• What is the purpose of this token? How will it benefit Trust Wallet users?
 • How is the token being distributed? Are you conducting an airdrop?
 • Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?
 • Is the token listed on a centralized/decentralized exchange?
 • Is a Smart Contract audit completed? Where can we find this information?

**Comment by lizqlife** [comment]
> • What is the purpose of this token? How will it benefit Trust Wallet users? • How is the token being distributed? Are you conducting an airdrop? • Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale? • Is the token listed on a centralized/decentralized exchange? • Is a Smart Contract audit completed? Where can we find this information?

• What is the purpose of this token? How will it benefit Trust Wallet users?
﻿
To promote and practice the utility of cryptocurrencies in global public charity, so that more stray and abandoned animals can be rescued.
﻿
Will bring more active users and attention to trust wallet. For a month now, we have been occupying the top three trading vols on the main Ethereum mainnet, with a global community of 15,000 people and 10,339 holders.
﻿
• How is the token being distributed? Are you conducting an airdrop?
﻿
Fair distribution, holders buy on their own, no airdrops.
﻿
• Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?
﻿
No.
﻿
• Is the token listed on a centralized/decentralized exchange?
﻿
CoinW : https://www.coinw.com/spot/Neiro(ETH)USDT
CoinEx : https://www.coinex.com/en/exchange/NEIROCTO-USDT
Xtcom : https://www.xt.com/en/trade/neiroeth_usdt
Mexc : https://www.mexc.com/exchange/NEIRO1_USDT
Ascendex : https://ascendex.com/en/cashtrade-spottrading/usdt/neiroeth
HTX : https://www.htx.com/trade/neirocto_usdt?type=spot
Poloniex : https://poloniex.com/trade/NEIROCTO_USDT
﻿
• Is a Smart Contract audit completed? Where can we find this information?
﻿
The contract audit has been done by solidproof.
﻿
https://x.com/solidproof_news/status/1824840632441155976

**Comment by lizqlife** [comment]
> • What is the purpose of this token? How will it benefit Trust Wallet users? • How is the token being distributed? Are you conducting an airdrop? • Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale? • Is the token listed on a centralized/decentralized exchange? • Is a Smart Contract audit completed? Where can we find this information?


@cryptomanz1  Could you please review it faster? Thank you very much and best wishes.

**Comment by lizqlife** [comment]
@cryptomanz1 I noticed an error with merge detection. What should I do?

**Pull request merged**
