### PR TITLE
Add Hoppy (ERC20)

### PR DESCRIPTION
**Pull request by hoppydevxbt**
Adding info for ERC20 token 'Hoppy'.

PR created by <a href="https://assets.trustwallet.com">TW Assets Management</a>

### CODE REVIEW

**Comment by Cryptocool1** [comment]
• What is the purpose of this token? How will it benefit Trust Wallet users?
 • How is the token being distributed? Are you conducting an airdrop?
 • Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?
 • Is the token listed on a centralized/decentralized exchange?
 • Is a Smart Contract audit completed? Where can we find this information?

**Comment by HydroXBT** [comment]
> • What is the purpose of this token? How will it benefit Trust Wallet users? • How is the token being distributed? Are you conducting an airdrop? • Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale? • Is the token listed on a centralized/decentralized exchange? • Is a Smart Contract audit completed? Where can we find this information?


> • This is a meme project, it will make people use more trust wallet, you can find everything on the distribution the certik audit: https://skynet.certik.com/projects/hoppy, we don’t do airdrop, no presale, no ICO, yes it’s on many CEX and yes it’s Certik audited. 12 000+ on-chain holders and many CEX holders as well. It’s on Coinmarketcap and all platforms https://coinmarketcap.com/currencies/hoppy-coin/

**Comment by tokendeb** [comment]
> • What is the purpose of this token? How will it benefit Trust Wallet users? • How is the token being distributed? Are you conducting an airdrop? • Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale? • Is the token listed on a centralized/decentralized exchange? • Is a Smart Contract audit completed? Where can we find this information?

- Hoppy is a memecoin and have decide to list on trust wallet to allow our holder base and trust wallet users to more easily and safely identify our coin
- you can find everything on the distribution in the certik audit: https://skynet.certik.com/projects/hoppy, we don’t do airdrop, no presale, no ICO
- Markets are listed on the CMC link we have already provided https://coinmarketcap.com/currencies/hoppy-coin/ , but they include MEXC, Bilaxy, BitMart, XT, CoinEx, Bittrue, CoinW, Hibt, KCEX, BiKing, SuperX, LATOKEN
- https://skynet.certik.com/projects/hoppy

**Comment by HydroXBT** [comment]
This is a meme project, it will make people use more trust wallet, you can find everything on the distribution the certik audit: https://skynet.certik.com/projects/hoppy, we don’t do airdrop, no presale, no ICE, yes it’s on many CEX and yes it’s Certik audited. It’s on Coinmarketcap and all platforms https://coinmarketcap.com/currencies/hoppy-coin/

Hoppy Markets/Centralized Exchanges (proof on Coinmarketcap)
MEXC, Bilaxy, BitMart, XT, CoinEx, Bittrue, CoinW, Hibt, KCEX, BiKing, SuperX, LATOKEN

**Comment by hoppydevxbt** [comment]
This is a meme project, it will make people use more trust wallet and allow our holders to more easily and safely interact with our token, you can find everything on the distribution the certik audit: https://skynet.certik.com/projects/hoppy, we don’t do airdrop, no presale, no ICO, yes it’s on many CEX and yes it’s Certik audited. It’s on Coinmarketcap and all platforms https://coinmarketcap.com/currencies/hoppy-coin/

Hoppy Markets/Centralized Exchanges (proof on Coinmarketcap)
MEXC, Bilaxy, BitMart, XT, CoinEx, Bittrue, CoinW, Hibt, KCEX, BiKing, SuperX, LATOKEN

**Comment by hoppydevxbt** [comment]
@Cryptocool1 could you please clarify if a change is needed?

**Pull request merged**
