### PR TITLE
Create 0x4954CEb270BF39dBefCF6E769597D3C14faF9e8f

### PR DESCRIPTION
**Pull request by khaos-finance**

### CODE REVIEW

**Comment by khaos-finance** [comment]
hi

**Comment by Cryptocool1** [comment]
Please create new PR, follow doc https://developer.trustwallet.com/assets/requirements
You may want to try our Assets app in beta; go to https://assets.trustwallet.com, log on with Github, enter contract ID, logo and some additional info, and it will create a PR for you.
See https://developer.trustwallet.com/assets/repository_details

**Comment by khaos-finance** [comment]
ok

**Comment by kophyo1234** [comment]
oek

**Pull request closed without merging**
