### PR TITLE
Add Vodka Token (BEP20)

### PR DESCRIPTION
**Pull request by mostermas**
Adding info for BEP20 token 'Vodka Token'.

PR created by <a href="https://assets.trustwallet.com">TW Assets Management</a>

### CODE REVIEW

**Comment by cryptomanz** [comment]
Screenshot 2022-01-06 at 22 53 28

- Contract should be in checksum format, please change.

**Comment by mostermas** [comment]
0x66dA5cc445feC38A9475Ae7941f89110b9d256b9 here is contract of Vodka token , you send me photo with contract of LLG ?
I need add TWT logo and Info to Vodka Token!

**Review by Imanmahmoodi — APPROVED** [review]
blockchains/smartchain/assets/0x66dA5cc445feC38A9475Ae7941f89110b9d256b9/info.json

**Comment by cryptomanz** [comment]
Please create new PR, with only Vodka Token. Make sure to mention this PR, so that we can see that fee has been paid already here.

**Comment by mostermas** [comment]
I try but every time it add it to LLG PR

**Comment by mostermas** [comment]
I try to create with
https://community.trustwallet.com/t/how-to-submit-a-token-logo/3863 this
and with this one  https://assets.trustwallet.com/ and every time it add
LLG logo , to PR, maybe I beed do it with new github acc?

вс, 9 янв. 2022 г. в 00:36, MAD MAX ***@***.***>:

> I try but every time it add it to LLG PR
>

**Pull request closed without merging**
