### PR TITLE
Add DRUN logo and info

### PR DESCRIPTION
**Pull request by RunDogeRun**
Adding infos for DRUN BEP20 token

### CODE REVIEW

**Comment by Cryptocool1** [comment]
• What is the purpose of this token? How will it benefit Trust Wallet users?
 • How is the token being distributed? Are you conducting an airdrop?
 • Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?
 • Is the token listed on a centralized/decentralized exchange?
 • Is a Smart Contract audit completed? Where can we find this information?

**Comment by RunDogeRun** [comment]
Hello @Cryptocool1, thanks for your fast response.
• What is the purpose of this token? How will it benefit Trust Wallet users?
We're a fast evolving P2E game with a working game. We are less than 3 weeks old and have already trended on CG, CMC, and Dextools, twice. Trust Wallet users will love our project as we already have a large community that does. The staff are on Telegram voice and text chat 24/7, to answer any questions.
• How is the token being distributed? Are you conducting an airdrop?
We had a private pre-sale, a public presale, and fair launched after the presale - more details regarding the distribution can be found in our whitepaper at page 3: https://www.dogeruntoken.com/assets/whitepaper.pdf
• Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?
Yes, we held our presale on Pinksale, more details can be found here: https://www.pinksale.finance/#/launchpad/0x2d5D62a1753B6a285DEB311a3eE707Bd66752bd5?chain=BSC 
• Is the token listed on a centralized/decentralized exchange?
Currently we are listed only on pankcakeswap: https://pancakeswap.finance/swap?outputCurrency=0x29b86ecb7d434a5571f959f1c9a812b7aab34894
• Is a Smart Contract audit completed? Where can we find this information?
https://dessertswap.finance/audits/Doge-Run-BSC-Audit-13575830.pdf

**Comment by cryptomanz** [comment]
As per our policy, brand new tokens are not included, there is a minimum requirement of 10,000 holder addresses and 20,000 transactions, in order to filter out scam tokens.
See the criteria at : https://developer.trustwallet.com/assets/requirements .

**Comment by cryptomanz** [comment]
As per our policy, brand new tokens are not included, there is a minimum requirement of 10,000 holder addresses and 20,000 transactions, in order to filter out scam tokens.
See the criteria at : https://developer.trustwallet.com/assets/requirements .

**Comment by cryptomanz** [comment]
Please come back to us when all criteria are met.
When creating a new PR make sure to mention this PR, so that we can see that fee has been paid already here.

**Pull request closed without merging**
