### PR TITLE
Add CGG Token

### PR DESCRIPTION
**Pull request by magduf**

### CODE REVIEW

**Comment by catenocrypt** [comment]
As per our policy, brand new tokens are not included, there is a minimum requirement of 2500 holder addresses and 5000 transactions, in order to filter out scam tokens.
See the criteria at (mentioned in the first message by the bot): https://community.trustwallet.com/t/how-to-submit-a-token-logo/3863).
This token has no real usage yet (1 holder address). Closing PR for now. Please come back to us when all criteria are met.  Multi-chain and staking tokens may get special treatment, let us know if this is the case. 

https://etherscan.io/token/0x1fe24f25b1cf609b9c4e7e12d802e3640dfa5e43

**Comment by magduf** [comment]
> As per our policy, brand new tokens are not included, there is a minimum requirement of 2500 holder addresses and 5000 transactions, in order to filter out scam tokens.

The token was just recently launched (last 24 hours) , and has already at the current moment almost 2500 holder addresses (2,346 growing every minute), and 7255 transfers. It is already on coinmarket cap and it is a big legit project. 
Please reevaluate 

Thank  you

**Comment by catenocrypt** [comment]
Reopening

**Comment by catenocrypt** [comment]
Correction needed:  the token contract folder name should be in checksum format.  I've tried to fix this but apparently I have no write access to this PR.
So please rename to `0x1fE24F25b1Cf609B9c4e7E12D802e3640dFA5e43`.

```
-  XXX 'Folder structure for chain ethereum (ethereum fork)':  1 errors
   XXX   'Expect asset at path /home/runner/work/assets/assets/blockchains/ethereum/assets/0x1fe24f25b1cf609b9c4e7e12d802e3640dfa5e43 in checksum: '0x1fE24F25b1Cf609B9c4e7E12D802e3640dFA5e43''
```

```
$ git push ChainGuardians HEAD:CGG-token
remote: Permission to ChainGuardians/assets.git denied to catenocrypt.
fatal: unable to access 'https://github.com/ChainGuardians/assets.git/': The requested URL returned error: 403
```

**Comment by magduf** [comment]
I have readded the folder with correct format
please check again 
Adam I have also given your user rights to our repository in case it still does not work

**Pull request merged**
