### PR TITLE
Add DefiConnect (BEP20)

### PR DESCRIPTION
**Pull request by ademuanthony**
Adding info for BEP20 token 'DefiConnect'.

PR created by <a href="https://assets.trustwallet.com">TW Assets Management</a>

### CODE REVIEW

**Comment by ademuanthony** [comment]
DFC is listed on coingecko
https://www.coingecko.com/en/coins/deficonnect

**Comment by cryptomanz** [comment]
Hello,
Can your answer some questions?
• What is the purpose of this token? How will it benefit Trust Wallet users?
• How is the token being distributed? Are you conducting an airdrop?
• Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?
• Is the token listed on a centralized/decentralized exchange?
• Is a Smart Contract audit completed? Where can we find this information?

**Comment by ademuanthony** [comment]
1. What is the purpose of this token? How will it benefit Trust Wallet users? 
Defi Connect aims to bring real-life and DeFi together by building applications of DeFi in digital marketing, healthcare, transportation, and logistics. 
By adding this token to trustwallet, the users will be able to participate simlessly in our ecosystem for easy payment on our payment gateway, planting of our token on our token farm, and other transactions and applications within our ecosystem.

2. How is the token being distributed? Are you conducting an airdrop?
We started the distribution with an airdrop and a self-drop but the airdrop is now over.

3. Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?
Yes, we conducted a presale/public-sale on our website

4. Is the token listed on a centralized/decentralized exchange?
Yes, we are listed on Latoken exchange and on pancakeswap.
Here is the links:
https://latoken.com/exchange/DFC_USDT

5. Is a Smart Contract audit completed? Where can we find this information?
We conducted an in-house check are planning for a public audit

**Comment by cryptomanz** [comment]
awaiting for smart contract audit. on hold for now

**Comment by Cryptocool1** [comment]
Please create new PR when smart contract audit will be ready. make sure to mention this PR, so the fee can be reused.

**Comment by ademuanthony** [comment]
Our audit report is ready
Kindly reopen so that this can be concluded

Here is the report
https://github.com/solidproof/smart-contract-audits/blob/main/SmartContract_Audit_Solidproof_DefiConnect.pdf

**Pull request closed without merging**
