### PR TITLE
update antimatter token address

### PR DESCRIPTION
**Pull request by antimatter-finance**
update antimatter token address

### CODE REVIEW

**Comment by cryptomanz** [comment]
Hello,
- Can't find contract on your website.

**Comment by chainswap** [comment]
> Hello,
> 
> * Can't find contract on your website.

OK，we will show our contract on website

**Comment by Cryptocool1** [comment]
there is another contract posted on the website.
create new PR whe you will be ready to answer the question.
Can you prove ownership or provide evidence that this website/token associated with the current website?

**Comment by antimatter-finance** [comment]
> there is another contract posted on the website.
> create new PR whe you will be ready to answer the question.
> Can you prove ownership or provide evidence that this website/token associated with the current website?

Display the new token contract address on our website, right?

**Comment by antimatter-finance** [comment]
Twitter announce link:
https://twitter.com/antimatterdefi/status/1418588202026168320?s=21

**Pull request merged**
