### PR TITLE
New rebranding - New Logo, Name, Description - Noia Network > Syntropy

### PR DESCRIPTION
**Pull request by lorenzo8769**
New rebranding: source: https://medium.com/noia/noia-is-now-syntropy-f5513596aa08

Name: Syntropy
Symbol: NOIA
Contract: 0xa8c8cfb141a3bb59fea1e2ea6b79b5ecbcd7b6ca
Decimals: 18

### CODE REVIEW

**Comment by lorenzo8769** [comment]
@catenocrypt @lamdeadlyz
we have already paid. can you still make the change? Thank you

**Comment by lorenzo8769** [comment]
@Iamdeadlyz 
we have already paid. can you still make the change? Thank you

**Comment by lorenzo8769** [comment]
@zachzwei 
we have already paid. can you still make the change? Thank you

**Comment by catenocrypt** [comment]
@lorenzo8769 , please share details about previous payment (txid, PR number)

**Comment by lorenzo8769** [comment]
@catenocrypt 
Here:
https://github.com/trustwallet/assets/pull/4255

**Comment by catenocrypt** [comment]
Merged current master into source repo, to get up to data, fix conflict, etc.

**Comment by catenocrypt** [comment]
Problems with the submission:

- Logo file is too large (over 1000 px), recommended size is 256x256 (max 512x512).  Please resize.

- Mentioned website `https://www.syntropy.net` is not accessible, it says 'Private site'.  This one works: `https://www.syntropynet.com/`.  Please change.

**Comment by lorenzo8769** [comment]
@catenocrypt Update done

**Comment by lorenzo8769** [comment]
@catenocrypt 

name must be syntropy and the token remains NOIA

On Uniswap, i see still: NOIA Token (NOIA)

it would take this: Syntropy (NOIA)

**Pull request merged**
