### PR TITLE
ADD BTCMINI logo

### PR DESCRIPTION
**Pull request by thisissosogood**
ADD BTCMINI logo , BTCMINI co-exist with existing asset management services and other CRYPTO markets

### CODE REVIEW

**Comment by Cryptocool1** [comment]
hello,
what is the purpose of this token?

**Comment by thisissosogood** [comment]
BTCMINI is a DeFi token on Binance Smartchain that will also perform a
governance function for our Dex Swap platform.

**Comment by Cryptocool1** [comment]
> BTCMINI is an Innovative DeFi token on Binance Smartchain, BTCMINI token will interoperate to maximize returns while minimizing risks for users, BTCMINI token will also perform a governance function for our Dex Swap platform.
> […](#)

On your website, says that it audited by Certic. Can you provide more details on the audit?

**Comment by thisissosogood** [comment]
Planned auditing is before our Swap/Dex platform launch and choice of Audit
service is certik.

On website (The Audit by certik, is now changed to "To be Audit by certik")

**Comment by zachzwei** [comment]
This token does not meet our token standards. There is a lot of red flags raised and this could pose risks to our users. Submission will be closed until we see any real utility with this asset.

**Pull request closed without merging**
