### PR TITLE
ERC20 token listing on Trust Wallet - Kauri crypto

### PR DESCRIPTION
**Pull request by Kauricrypto**
ERC20 token listing on Trust Wallet - Kauri crypto
https://etherscan.io/token/0xe172f366678ec7b559f6c2913a437baadfd4e6c8
0xe172f366678ec7b559f6c2913a437baadfd4e6c8

### CODE REVIEW

**Comment by catenocrypt** [comment]
Correction needed: please remove the 2 files from the top-level directory.

image

**Comment by Kauricrypto** [comment]
@catenocrypt @zachzwei  Is it ok now?

**Comment by catenocrypt** [comment]
Now info.json file is missing altogether, please add it back under  blockchains/ethereum/assets/0xe172F366678EC7B559F6C2913a437BaaDfd4e6c8 .

**Comment by Kauricrypto** [comment]
File uploaded.

**Pull request merged**
