### PR TITLE
Please add logo to my community group token

### PR DESCRIPTION
**Pull request by benlolbenlol178**
https://github.com/benlolbenlol178/assets/pull/3

### CODE REVIEW

**Comment by benlolbenlol178** [comment]
@catenocrypt Please check and add token logo.

**Comment by benlolbenlol178** [comment]
benlolbenlol178#3

**Comment by catenocrypt** [comment]
Logo file was missing, I have added it.

**Comment by catenocrypt** [comment]
Earlier payment to wrong PR accepted.
https://explorer.binance.org/tx/809BAD7C4F10E4E544BBD0913E04CBD056060170FBCBAB0EC5283875CEBF51CA

**Comment by benlolbenlol178** [comment]
Hey how can I change the logo please?

[image: white trust.png]

**Comment by catenocrypt** [comment]
> Hey how can I change the logo please? [image: white trust.png]

Per our policy, you need to submit a new PR (unless it's our fault).

image

**Comment by benlolbenlol178** [comment]
Do I have to pay 1 BNB again for that? Or is it lesser?

**Comment by benlolbenlol178** [comment]
Can you send me the instructions for payment please?

**Comment by catenocrypt** [comment]
- Remove your assets repo fork if you still have it
- Fork https://github.com/trustwallet/assets repo
- Upload the updated logo to the same filename as the old (overwrite)
- Create a Pull Request to main repo trustwallet/assets/master
- Follow instructions for payment.

Note: the fee of 2000 TWT will be decreased to half in about a day.

**Comment by benlolbenlol178** [comment]
When I remove the asset repo fork, will the token logo be removed?
Pretty noob at this, possible to have it all done here? I can make the
payment in BNB and upload the logo to you here.

Thank you.

**Comment by catenocrypt** [comment]
@benlolbenlol178 , Sorry our resources are limited to support individual questions.
With GitHub everybody can make a own copy of a repository (a 'fork'), do changes there, and create a Pull Request to request taking over the changes to the main repo.
If you remove your fork, the main repo is not affected, nothing disappears from there.
Removing and creating the fork is needed so it is frsh and in sync with the main (alternative is to merge the master to existing old fork, but that is more cumbersome to do).

**Comment by benlolbenlol178** [comment]
Is the new logo ok? Am doing the payment now. I uploaded the replacement
logo on github as well.

It shows the following though:

[image: @github-actions] <https://github.com/apps/github-actions>
* Fixes and Consistency Updates - Dry run / scripts (pull_request) *
Failing after 46s — scripts
Details
<https://github.com/trustwallet/assets/pull/3070/checks?check_run_id=953010444>
[image: @github-actions] <https://github.com/apps/github-actions>
* Pull Request CI / pull_request_ci (pull_request) * Failing after 41s —
pull_request_ci

[image: trustwhite.png]

**Pull request merged**
