### PR TITLE
Add the logos and information of CELT and Crystal.

### PR DESCRIPTION
**Pull request by Celestialgamefi**
Add the logos and information of CELT and Crystal.

### CODE REVIEW

**Comment by Celestialgamefi** [comment]
https://explorer.binance.org/address/bnb15pwnpvcaxcy8pj3u28kjtzrcnajfmh756k07ls?utm_source=tokenpocket

**Comment by ramsty** [comment]
Hi!
As per our policy, brand new tokens are not included, there is a minimum requirement of 5000 holder addresses and 10000 transactions, in order to filter out scam tokens.
See the criteria at (mentioned in the first message by the bot): https://community.trustwallet.com/t/how-to-submit-a-token-logo/3863).
Closing PR for now. Please come back to us when all criteria are met. 
When creating a new PR make sure to mention this PR, so that we can see that fee has been paid already here.
Also, follow doc https://community.trustwallet.com/t/how-to-submit-a-token-logo/3863
You may want to try our Assets app in beta; go to https://assets.trustwallet.com, log on with Github, enter contract ID, logo and some additional info, and it will create a PR for you.
See https://community.trustwallet.com/t/how-to-submit-a-token-logo-using-assets-app/82957.

**Comment by Celestialgamefi** [comment]
https://bscscan.com/token/0x4f34292f109870d5fdda602bc7e3ae56d520d6e1

**Comment by Celestialgamefi** [comment]
He should reach the requirement now. Please help us to confirm.

**Comment by Celestialgamefi** [comment]
> Hi! As per our policy, brand new tokens are not included, there is a minimum requirement of 5000 holder addresses and 10000 transactions, in order to filter out scam tokens. See the criteria at (mentioned in the first message by the bot): https://community.trustwallet.com/t/how-to-submit-a-token-logo/3863). Closing PR for now. Please come back to us when all criteria are met. When creating a new PR make sure to mention this PR, so that we can see that fee has been paid already here. Also, follow doc https://community.trustwallet.com/t/how-to-submit-a-token-logo/3863 You may want to try our Assets app in beta; go to https://assets.trustwallet.com, log on with Github, enter contract ID, logo and some additional info, and it will create a PR for you. See https://community.trustwallet.com/t/how-to-submit-a-token-logo-using-assets-app/82957.

it  should reach the requirement now. Please help us to confirm.

https://bscscan.com/token/0x4f34292f109870d5fdda602bc7e3ae56d520d6e1

**Comment by Celestialgamefi** [comment]
https://github.com/trustwallet/assets/pull/15273

**Pull request closed without merging**
