### PR TITLE
Add Binance Smart Chain BOY CZ (BEP20)

### PR DESCRIPTION
**Pull request by takuro020301**
Adding info for BEP20 token 'Binance Smart Chain BOY CZ'.

PR created by <a href="https://assets.trustwallet.com">TW Assets Management</a>

### CODE REVIEW

**Comment by cryptomanz** [comment]
Hello,
Can your answer some questions?
 • What is the purpose of this token? How will it benefit Trust Wallet users?
 • How is the token being distributed? Are you conducting an airdrop?
 • Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?
 • Is the token listed on a centralized/decentralized exchange?
 • Is a Smart Contract audit completed? Where can we find this information?

**Comment by takuro020301** [comment]
• What is the purpose of this token? 
What are the benefits for trust wallet users? 

This token is a token of the Binance Smart Chain Girl project and It acts as a governance token for the DeFi platform. 
Trust wallet users will be able to stake by connecting directly to our DeFi platform.

 • How are the tokens distributed? Do you do airdrop?

 We also carry out fair launch with pancake swap and air drop. •

Did you sell your tokens through an Initial Coin Offering (ICO) or pre-sale of tokens? 

No, I don't.

 • Are tokens listed on centralized / decentralized exchanges? 

Listed in Pancake Swap V2. 

• Has the smart contract audit been completed? Where can I find this information? 

The audit report is currently commissioned by our partner, my wish.io.

**Comment by cryptomanz** [comment]
- Awaiting for smart contract audit.

**Comment by takuro020301** [comment]
Screenshot_20210721-003627_Chrome

**Comment by takuro020301** [comment]
Screenshot_20210721-003648_Chrome

**Comment by Cryptocool1** [comment]
what is that?

**Comment by takuro020301** [comment]
This is, This is the screen for requesting the issuance of an audit report to mywish.io. It should be published soon.

**Comment by takuro020301** [comment]
It seems that the audit report will be completed soon. Please wait

**Comment by takuro020301** [comment]
https://48.gigafile.nu/0802-cfa4207d0a191bed3aac9c8c434e38145

audit report

**Comment by takuro020301** [comment]
Sorry I made you wait. The audit report is You can download it from the above URL. Verification please

**Comment by takuro020301** [comment]
http://bscgirl.site/wp-content/uploads/2021/07/Binance-Smart-ChainCz.pdf

**Pull request merged**
