### PR TITLE
Add Chain

### PR DESCRIPTION
**Pull request by Fluffynorth**
Txn was already paid but you closed the pr, here's txn  2CABD7B44F7247852D13A22F0638BDC311BB65ADBD75A3BDAF7F662C44FB838E memo 27530 this is to add Phoenix to chains not a token. 
https://explorer.binance.org/tx/2CABD7B44F7247852D13A22F0638BDC311BB65ADBD75A3BDAF7F662C44FB838E

### CODE REVIEW

**Comment by Fluffynorth** [comment]
Coingecko: https://www.coingecko.com/en/coins/phoenix-blockchain
Coinmarketcap: 
https://coinmarketcap.com/currencies/phoenix/

**Comment by Fluffynorth** [comment]
How long does this usually take?

**Comment by Jstacy121** [comment]
You don’t pay the fee yet

Stacy L Johnson
Sent with Spark

**Comment by Fluffynorth** [comment]
@Cryptocool1 why did you guys not add it. I paid, everything that was needed was already done on my side but the person assigned didn't do anything.

**Comment by Jstacy121** [comment]
You just have to pay through Bitcoin if you are ready I will send you the address   
  
  
  
  
  
  
  

  
  
>

**Comment by Jstacy121** [comment]
You have to pay to this Bitcoin address bc1q6nvwd9ftz8n07f8q6jnppcz40739reauqt3zf7 500 usd

**Pull request closed without merging**
