### PR TITLE
Add W3C info and logo

### PR DESCRIPTION
**Pull request by 1453742116**
The memo 22319 has been paid 700TWT.

### CODE REVIEW

**Comment by Cryptocool1** [comment]
#22319 paid

**Comment by Cryptocool1** [comment]
Hello,
• What is the purpose of this token? How will it benefit Trust Wallet users?
 • How is the token being distributed? Are you conducting an airdrop?
 • Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?
 • Is the token listed on a centralized/decentralized exchange?
 • Is a Smart Contract audit completed? Where can we find this information?

**Comment by 1453742116** [comment]
> Hello, • What is the purpose of this token? How will it benefit Trust Wallet users? • How is the token being distributed? Are you conducting an airdrop? • Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale? • Is the token listed on a centralized/decentralized exchange? • Is a Smart Contract audit completed? Where can we find this information?

W3C is the W3DAO incentive score,

Official website: https://w3dao.finance/#/

Security audit: https://www.certik.com/projects/w3dao

https://coinmarketcap.com/dexscan/bsc/0x5585dda2a7b0d0e4301a4c0e9514ddd9fed29059

At the Pancakeswap communication office.

Pronouns: trembling 70%; trembling, trembling, trembling 30%

The front part is followed by the middle part and the middle part.

**Comment by Cryptocool1** [comment]
Are you listed on CMC?

**Comment by 1453742116** [comment]
> Are you listed on CMC?

https://coinmarketcap.com/dexscan/bsc/0x5585dda2a7b0d0e4301a4c0e9514ddd9fed29059

**Pull request merged**
