### PR TITLE
Anon inu ( AINU ) Trust wallet logo and info update

### PR DESCRIPTION
**Pull request by maziyar83**
This PR is being closed due to inactivity. If you wish to continue, please have us reopen the PR before sending your payment, or just create a new one.
Do NOT send payments for closed PR, as the fee may by lost!
  (48 vs. 48 hrs)

### CODE REVIEW

**Comment by maziyar83** [comment]
previous request number #12284

**Comment by maziyar83** [comment]
@Cryptocool1 How can i Reopen this PR ?

**Comment by Cryptocool1** [comment]
> @Cryptocool1 How can i Reopen this PR ?

it will close again after some time, until you pay the fee

**Comment by maziyar83** [comment]
@Cryptocool1  previous request number #12284 and already paid.

**Comment by maziyar83** [comment]
> 
 Coin market cap link :
https://coinmarketcap.com/currencies/anon-inu/
 @Cryptocool1

**Comment by Cryptocool1** [comment]
you need to pay the fee for updating,
Please see this requirement here: https://developer.trustwallet.com/assets/pr-fee

**Comment by Cryptocool1** [comment]
#12284 paid

**Comment by maziyar83** [comment]
Thanks @Cryptocool1  what shall I Do right now ?

**Pull request merged**
