### PR TITLE
Add Petoverse (BEP20)

### PR DESCRIPTION
**Pull request by PetoLogo**
Adding info for BEP20 token 'Petoverse'.

PR created by <a href="https://assets.trustwallet.com">TW Assets Management</a>

### CODE REVIEW

**Comment by PetoLogo** [comment]
https://github.com/Rugfreecoins/Smart-Contract-Audits/blob/main/Petoverse%20Token%20Audit.pdf
https://www.certik.com/projects/petoverse
Audits above

**Comment by PetoLogo** [comment]
@Cryptocool1

**Comment by Cryptocool1** [comment]
Hello, how did you get more than 25k holders in 1day?

**Comment by PetoLogo** [comment]
> Hello, how did you get more than 25k holders in 1day?

Hi we are going viral right now.. take a look on coinmarket cap we are 6th trending and 2nd most viewed project on their and have increased from 1million mcap to 9million in 36hrs.

**Comment by cryptomanz** [comment]
did you do the airdrop?

**Comment by PetoLogo** [comment]
> did you do the airdrop?

We were at around 16,000 holders and as part of a very aggressive marketing campaign involving NYC Billboards (https://t.me/petoversenews/201) 
An article on cryptonews (https://crypto.news/petoverse-launches-the-worlds-first-cryptocurrency-project-that-integrates-auto-staking-and-compounding-protocol-with-an-mmorpg-universe/) we are also airdropping whale wallets (https://t.me/petoversenews/196) which has seen us start trending on coinmarketcap and see a huge rise in holders, marketcap and transactions.

**Comment by PetoLogo** [comment]
> did you do the airdrop?

Here are the KYC links for our founders
https://www.linkedin.com/in/michael-flynn-4a517230
https://www.linkedin.com/in/joseph-sloan-1249433b/

**Pull request merged**
