### PR TITLE
Add LIME (BEP20)

### PR DESCRIPTION
**Pull request by OfficialLimeWallet**
Adding info for BEP20 token 'LIME'.

PR created by <a href="https://assets.trustwallet.com">TW Assets Management</a>

### CODE REVIEW

**Comment by Cryptocool1** [comment]
the token exists for three days and you already have 10,000 holders

**Comment by OfficialLimeWallet** [comment]
we are giving airdrop

**Comment by OfficialLimeWallet** [comment]
> Your token has artiificial number of holders. the token exists for three days and you already have 10,000 holders see Listing Acceptance Guidelines here: https://developer.trustwallet.com/assets/requirements

its Airdrop

**Comment by Cryptocool1** [comment]
We are not accept airdropped tokens, you can also see it in our requirements

**Pull request closed without merging**
