### PR TITLE
Add BabyDogeARMY (BEP20)

### PR DESCRIPTION
**Pull request by BabyDogeARMY**
Adding info for BEP20 token 'BabyDogeARMY'.

PR created by <a href="https://assets.trustwallet.com">TW Assets Management</a>

### CODE REVIEW

**Comment by BabyDogeARMY** [comment]
TrustWallet team, hello.
BabyDogeARMY has written great stories. Building on BinanceSmartChain and weekly volume more than 1 million dollar.
BabyDogeARMY is 2 months old and we have reached 11000+ holders in this process. Accordingly, Binance shared a how to buy guide for us. CoinMarketCap, Coingecko, Cryptocom listing done! BSCscan in progress.
The community now wants an update on TrustWallet as well. We will be happy if the necessary investigation is provided as soon as possible.

Binance tracked BabyDogeARMY:
https://www.binance.com/en/price/babydogearmy

Binance shared How to Buy Guide for BabyDogeARMY:
https://www.binance.com/en/how-to-buy/babydogearmy

BabyDogeARMY live on CoinMarketCap:
https://coinmarketcap.com/currencies/babydogearmy/

BabyDogeARMY live on Coingecko:
https://www.coingecko.com/en/coins/babydogearmy

%50 Supply burnt forever before launch: https://bscscan.com/tx/0x1d85ae5c773f6fdc4924555225e410e40969de7e2f1c762fb2c884b4f7bd50c9
*First Burnt Evet: Team burned all the tokens they had in the remaining DEV wallet.
Team will finance BabyDogeARMY with the proceeds from NFT sales, our meeting dApp and investments in BabyDogeVERSE world.
Burnt Event Link: https://bscscan.com/tx/0xb740fca9b34b093526b6ac5963dccdaf6780d9b81875a8094c4ea083161a704e

Liquidity locked until MAY 2024 years/along a year:
https://www.pinksale.finance/pinklock/record/1088677?chain=BSC

Audited by Pinksale Official Audit partner KISHIELD:
https://github.com/KISHIELD/Audits/blob/main/KISHIELD_BabyDogeARMY_Audit_20230423.pdf

What is the project about?

BabyDogeARMY was created by BabyDoge lovers to bring together the largest and most beautiful community in history and show their true power.
In this direction, we will create the BabyDogeARMY Meeting dApp and a metaverse universe in which we exist with NFTs, each unique from the other.

What makes your project unique?

BabyDogeARMY is regularly trending on Twitter and other social networks. It is currently thought to have more than 1 million real followers and supporters.

With the BabyDogeARMY meeting dApp, we will bring this family together around the world. In addition, we will give them a new identity in the metaverse universe we have established.

History of your project.
We are the first holders of BabyDogeCoin. Actually the project team were killing the project but our lives changed with ElonMusk's BabyDooDoo tweet. It was truly a historic moment and I hope it will be documented in the future.

However, BabyDogeARMY is a very loving and special community. A family that believed in the same dream and fought for it. We want to bring this family together and be together for world problems.

What’s next for your project?
A very clean and realistic roadmap has been prepared. First of all, we would like to complete our listings in order to ensure financial price stability and strengthen the community. In the background, the development of the BabyDogeARMY meeting dApp continues.
In short, our first steps will be exchange listings and BabyDogeARMY meeting dApp.

What can your token be used for?

BabyDogeARMY dApp hosts interactive ways to meet new people using artificial intelligence.
Build your BabyDogeARMY profile. ( Wallets holding at least 1 BabyDogeARMY token will be able to become a member in order to protect our family and ensure security and it will be mandatory to do KYC**)
Open your location and match with our family members around you.
There will be a global search option for our family members from all over the world to meet and make friends.
With the integration of Metaverse and Web3.0, we are taking friend-finding platforms to another level.

As you can see here, you must hold 1 ARMY token to use BabyDogeARMY dApp. Of course you have to use more ARMY tokens for in-app premium features.

Please do the necessary investigations. If you see fit, we will make the payment. Kind Regards, BabyDogeARMY l General

**Comment by Cryptocool1** [comment]
Hello, how did you get more than 10k holders in 1 week?

**Comment by Cryptocool1** [comment]
There are a lot of complaints from users because you blocked the sale of tokens and blacklist users. Please explain these cases.

**Comment by BabyDogeARMY** [comment]
Hello Cryptocool, first of all. Many investors have invested in a fake project with the same name as us. This fake project collected BNBs on presale, launched and blacklisted all wallets.
Scam Presale-Same infos w BabyDogeARMY but token name BabyDogeArmy(BabyDoge)-Supply: 420,000,000,000,000,000 BabyDoge
and check developer(Our project has nothing to do with this wallet.):
Scam Contract Adress: https://bscscan.com/token/0x2b71ADA7112CC8Bdccf47F02101CD505B96A29de
Scam Developer Adress: https://bscscan.com/address/0xe42749e265eaba8299f9e54e3c13aa8be226c613 ( yes blacklisting all wallets and closed trade)
Please check this pic&Chart: https://imgur.com/O7CMvpu
https://poocoin.app/tokens/0x2b71ada7112cc8bdccf47f02101cd505b96a29de

As you can see, we cannot control this. Likewise, Sui Scam was trending on twitter last week. Because at least 50 scam contracts and airdrops were issued and people lost their money.
When I checked today, Binance Launchpad has launched a pre-sell for SUI (Kucoin and OKX already did)

I mean this is DEX. We have to be careful here and do research beforehand. We have no affiliation with this Developer address or contract.

Whats is BabyDogeARMY?
Please check this image for Tokenomics, Token name(BabyDogeARMY, Ticker(ARMY), Supply, TaxFee.
https://imgur.com/FHr7hrq

Also yes since BabyDogeARMY is a scam:
It has a 99/99 Dextools score :)
Listed on CMC&CG&Cryptocom within 36 hours 
Binance Price Track&How to Buy Guide has been published.
Twitter account has a blue tick. ( Check as Screenshot or via Twitter: https://imgur.com/a/vGFCYwm  - https://twitter.com/BabyDogeARMYai )
Check DexTools: https://www.dextools.io/app/en/bnb/pair-explorer/0x9def57edd6bc3c2fa1144d0e1787b6fec3b1ef35

Binance tracked BabyDogeARMY:
https://www.binance.com/en/price/babydogearmy

Binance shared How to Buy Guide for BabyDogeARMY:
https://www.binance.com/en/how-to-buy/babydogearmy

BabyDogeARMY live on CoinMarketCap:
https://coinmarketcap.com/currencies/babydogearmy/

BabyDogeARMY live on Coingecko:
https://www.coingecko.com/en/coins/babydogearmy

BabyDogeARMY live on CryptoCom:
https://crypto.com/price/babydogearmy

Thank you for trying to protect investors. Thank you for your sensitivity. But we have suffered enough. 
We have been unfairly attacked enough. If you look from our window, we are in a difficult situation. Still, BabyDogeARMY is still a baby and we continue to build it. Regards

**Comment by Cryptocool1** [comment]
According to gopluslabs the blacklist function is included in your contract. You should fix that

**Comment by BabyDogeARMY** [comment]
Dude are you kidding? First of all, contract codes cannot be changed. No contract can do this. If our BabyDogeSwap liquidity or Kucoin&MEXC liquidity is attacked/someone hacks our marketing wallets, we have to intervene.

XRP has banned the entire USA. Likewise, many Projects take precautions in this way as per security procedures.

We continue our work. When I look at your opposite, I see good comments. There are 95% support messages on Twitter, Instagram and CMC.

I'll update it again in a few weeks. I love my community, I love BabyDogeARMY. I will do the best for them. I don't care how long it will take or how much effort it will take.

You will review it again in the coming weeks. If we haven't made progress, if we haven't taken our project to advanced levels, if we haven't caught a good mood. OK, you're right! Do not approve!
But even if we do well, we would like to see the necessary support as TrustWallet, that is, as part of the BinanceSmartChain ecosystem. And we will deserve it.

**Pull request closed without merging**
