### PR TITLE
Add CharityDao Token (BEP20)

### PR DESCRIPTION
**Pull request by CharityDaoDev**
Adding info for BEP20 token 'CharityDao Token'.

PR created by <a href="https://assets.trustwallet.com">TW Assets Management</a>

### CODE REVIEW

**Comment by CharityDaoDev** [comment]
• What is the purpose of this token?
Charity DAO is a decentralized charitable organization that aims to make charity simple and more efficient without political interference and geographical restrictions. Now it has established  cooperation relationships with charities in more than 50 countries and regions around the world.


• How will it benefit Trust Wallet users?
CharityDAO has been in contact with traditional charitable organizations and institutions, and has attracted the attention of many volunteers, which will bring more users to Trust Wallet. 
It is convenient for users to use CHD to operate and trade, and assets are stored in Trust Wallet more securely.


• How is the token being distributed? Are you conducting an airdrop?
Token symbol: CHD
Total issuance: 7.6 billion
Issuance mechanism: Binance Smart Chain
Acquisition method: 1. Volunteer airdrop 2. Exchange on the project website
Total amount of airdrops: 3.06 million tokens
Total amount in the Treasury: 7,596,940,000 tokens, meaning one for each person in the world
Exchange ratio: Initially 1 BNB = 107000 CHD. The exchange can be made according to the function of
1 BNB = （100000 * 0.982ˣ⁻¹ + 7000） CHD (every 100 BNB is a price tier, X is the current price tier serial number, and the output price of CHD within the same tier is the same. (For example, tier number X of the 3850th BNB is 39).
Initial circulation: 3.06 million tokens.
The token has completed the first round of 1.4 million CHD airdrops for community volunteers from 2022/4/21 10:00-22/4/2410:00 (UTC0), and is currently preparing for the second round of CHD airdrops


• Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?
The project has no private placement, no ICO.

• Is the token listed on a centralized/decentralized exchange?
Tokens are listed on PancakeSwap trading.


• Is a Smart Contract audit completed? Where can we find this information?
At present, the token has been submitted to the audit institution, and the smart con.
token contract is open source:
https://bscscan.com/address/0xb4CD493f14eDAaE27FdaaB87072F3D55d9289A18#code

**Comment by DNAOFFICIALL** [comment]
Check

**Comment by cryptomanz** [comment]
Awaiting for smart contract audit.

**Comment by Cryptocool1** [comment]
please come back to us when all criteria are met

**Pull request closed without merging**
