### PR TITLE
1

### PR DESCRIPTION
**Pull request by DavidNyers**
https://bscscan.com/token/0x3aD9594151886Ce8538C1ff615EFa2385a8C3A88

https://www.safemarscrypto.com/

### CODE REVIEW

**Comment by catenocrypt** [comment]
Correction needed:  Files should be named exactly `logo.png` and `info.json`.  Please rename.

**Comment by DavidNyers** [comment]
How the f can i update the names?

**Comment by catenocrypt** [comment]
`git mv` is using command line.  GitHub desktop also must have easy rename func.
Google a barátod :0

**Comment by DavidNyers** [comment]
Wtf i cant change it and cant upload anything new.

**Pull request closed without merging**
