### PR TITLE
Add OBRok Token (BEP20)

### PR DESCRIPTION
**Pull request by bilisim1995**
Adding info for BEP20 token 'OBRok Token'.

PR created by <a href="https://assets.trustwallet.com">TW Assets Management</a>

### CODE REVIEW

**Review by Dlocc23 — APPROVED** [review]

**Review by Dlocc23 — APPROVED** [review]

**Comment by Dlocc23** [comment]
blockchains/smartchain/assets/0x205AFD08ceFe438377a0abC5a20Cb4462E1a8C5C/logo.png

**Comment by Dlocc23** [comment]
> **PR Summary** Files OK: 4 Tokens in PR: (2)
> 
> * BEP20 0x205AFD08ceFe438377a0abC5a20Cb4462E1a8C5C
> * BEP20 0x205afd08cefe438377a0abc5a20cb4462e1a8c5c
> 
> **Token BEP20 - 0x205AFD08ceFe438377a0abC5a20Cb4462E1a8C5C**: Symbol: **OBROK** decimals: 9 Links: [Logo](https://raw.githubusercontent.com/bilisim1995/assets/br0108-215933/blockchains/smartchain/assets/0x205AFD08ceFe438377a0abC5a20Cb4462E1a8C5C/logo.png) [Info](https://raw.githubusercontent.com/bilisim1995/assets/br0108-215933/blockchains/smartchain/assets/0x205AFD08ceFe438377a0abC5a20Cb4462E1a8C5C/info.json) [Website](https://obroktoken.com) [Explorer](https://bscscan.com/token/0x205AFD08ceFe438377a0abC5a20Cb4462E1a8C5C) Check OK 🙂
> 
> 
> 
> **Token BEP20 - 0x205afd08cefe438377a0abc5a20cb4462e1a8c5c**: Symbol: **OBROK** decimals: 9 Links: [Logo](https://raw.githubusercontent.com/bilisim1995/assets/br0108-215933/blockchains/smartchain/assets/0x205afd08cefe438377a0abc5a20cb4462e1a8c5c/logo.png) [Info](https://raw.githubusercontent.com/bilisim1995/assets/br0108-215933/blockchains/smartchain/assets/0x205afd08cefe438377a0abc5a20cb4462e1a8c5c/info.json) [Website](https://www.obroktoken.com/) [Explorer](https://bscscan.com/token/0x205afd08cefe438377a0abc5a20cb4462e1a8c5c) Token check error: ❌ id is not in checksum format, should be 0x205AFD08ceFe438377a0abC5a20Cb4462E1a8C5C (not 0x205afd08cefe438377a0abc5a20cb4462e1a8c5c). Please rename it. You may need to rename to a temp name first, then to the checksum format, because lowercase-uppercase-only renames are often ignored by the Git client or the filesystem ❌ links field cannot be be empty ❌ at least 1 tag is required
> 
>

**Review by bilisim1995 — COMMENTED** [review]
everythings is fine ?

**Comment by cryptomanz** [comment]
Hello,
Please follow the rules for adding token, your logo should be a full screen, 256x256.

**Comment by cryptomanz** [comment]
• What is the purpose of this token? How will it benefit Trust Wallet users?
 • How is the token being distributed? Are you conducting an airdrop?
 • Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?
 • Is the token listed on a centralized/decentralized exchange?
 • Is a Smart Contract audit completed? Where can we find this information?

**Comment by bilisim1995** [comment]
• What is the purpose of this token? How will it benefit Trust Wallet users?
   This token will be used for the OBRok Token project. Our client will manage their tokens through TrustWallet. For this 
   they need to use the TrustWallet application.

• How is the token being distributed? Are you conducting an airdrop?
   https://twitter.com/Obroktoken/status/1451889099783163914
   We have organized an airdrop event only once.

• Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?
   No

• Is the token listed on a centralized/decentralized exchange?
  https://www.lbank.info/exchange/obrok/usdt/
  https://www.hotbit.io/exchange?symbol=OBROK_USDT
  https://coinsbit.io/trade/OBROK_USDT
  https://www.5roi.com/exchange/OBROK/USDT

• Is a Smart Contract audit completed? Where can we find this information?
   https://obroktoken.com/wp-content/uploads/2021/12/coinscope-audit.pdf
   
   Best Regards.

**Comment by bilisim1995** [comment]
> • What is the purpose of this token? How will it benefit Trust Wallet users? • How is the token being distributed? Are you conducting an airdrop? • Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale? • Is the token listed on a centralized/decentralized exchange? • Is a Smart Contract audit completed? Where can we find this information?

• What is the purpose of this token? How will it benefit Trust Wallet users?
This token will be used for the OBRok Token project. Our client will manage their tokens through TrustWallet. For this
they need to use the TrustWallet application.

• How is the token being distributed? Are you conducting an airdrop?
https://twitter.com/Obroktoken/status/1451889099783163914
We have organized an airdrop event only once.

• Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?
No

• Is the token listed on a centralized/decentralized exchange?
https://www.lbank.info/exchange/obrok/usdt/
https://www.hotbit.io/exchange?symbol=OBROK_USDT
https://coinsbit.io/trade/OBROK_USDT
https://www.5roi.com/exchange/OBROK/USDT

• Is a Smart Contract audit completed? Where can we find this information?
https://obroktoken.com/wp-content/uploads/2021/12/coinscope-audit.pdf

Best Regards.

@cryptomanz

**Pull request merged**
