### PR TITLE
Add VicMove (BEP20)

### PR DESCRIPTION
**Pull request by NamTran9999**
Adding info for BEP20 token 'VicMove'.

PR created by <a href="https://assets.trustwallet.com">TW Assets Management</a>

### CODE REVIEW

**Comment by tonytran8888** [comment]
Holder is ok

**Comment by tonytran8888** [comment]
Thanks you, How long will it take for the logo to be updated?

**Comment by tonytran8888** [comment]
• What is the purpose of this token? How will it benefit Trust Wallet users?
The Best Move to Earn NFT Game
VICMOVE is a web3 fitness and lifestyle mobile app where you can earn rewards just by movement like walking, running and cycling.

• How is the token being distributed?
The total supply of VIM is 50.000.000 tokens:
FairLunch Sale: 36.000.000
Advisors: 500.000
Team: 1.500.000
DEX liquidity: 17.400.000

. Are you conducting an airdrop?
Airdrop1: https://t.me/VICMOVEAnnouncement/123

• Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?
Presale On PinkSale: https://www.pinksale.finance/#/launchpad/0x403e5112E0a03019b4Cc1C21e9D7a1c74841bac8?chain=BSC

• Is the token listed on a centralized/decentralized exchange?
VIM is already listed on Pancakeswap, you can find our token exchange link here:
https://pancakeswap.finance/info/pool/0xd295cf5d859b9ed331cdf69c49a81eff5e1bee83

• Is a Smart Contract audit completed? Where can we find this information?
VIM token contract was audited by interfinetwork, you can find the detailed Audit report here:
https://github.com/interfinetwork/smart-contract-audits/blob/audit-updates/VicMove_0x5bcd91C734d665Fe426A5D7156f2aD7d37b76e30.pdf

**Comment by cryptomanz** [comment]
your logo should be a full screen, 256x256.

**Comment by tonytran8888** [comment]
> 

uploaded

**Comment by tonytran8888** [comment]
@cryptomanz I edited the photo

**Comment by tonytran8888** [comment]
Help Me pls!

**Pull request merged**
