### PR TITLE
add tcc logo and info

### PR DESCRIPTION
**Pull request by TechTreeCoin**

### CODE REVIEW

**Review by samuelmonday6 — COMMENTED** [review]
Hello dear friend I have a good story and I believe if try you will give testimony at end 
Last month i heard my friends saying something secret about receiving profits from bitcoins after investing I don’t really know what can of investment is that because the money I heard she received was so huge,I have to find out let me ask other people well I ask them directly to know how it works.
Then i know about this bitcoins after asking people someone later enlighten me, bitcoins is a life changing investment I wish I know about it for Long now this investment have changed allot of people life even Elon musk’s invest on it I saw it on Google I was so surprised.
I never believed that Bitcoin and stock trading is real until I was introduced to an expert trader @aranya_somsak911 Because I invest $1000 US dollars and get $13,600. back as my profit just 5 days of trading so I'm happy with life that is why I'm referring my friends and family to invest as well you can also invest if you want too. Trading . Investing in bitcoin is the best way to get rich Contact mrs Aranya Somsak and see it yourself 
👇👇👇👇👇
Click to check her Profile 👇👇👍

@[aranya_somsak911](https://instagram.com/aranya_somsak911?igshid=YmMyMTA2M2Y=)

**Review by samuelmonday6 — COMMENTED** [review]
@corymsmith

**Comment by TechTreeCoin** [comment]
holders:40731

**Comment by Cryptocool1** [comment]
• Is a Smart Contract audit completed? Where can we find this information?

**Comment by TechTreeCoin** [comment]
> • Is a Smart Contract audit completed? Where can we find this information?

https://dessertswap.finance/audits/Tech-Trees-BSC-Audit-21895752.pdf

https://www.certik.com/projects/tech-trees (In Audit)

**Comment by TechTreeCoin** [comment]
> ### 公关摘要
> 文件 OK： PR 中的 2 个令牌：**BEP20** 0x6A684b3578f5B07c0Aa02fAFc33ED248AE0c2dB2 符号：**TTC**小数：18 链接：[徽标](https://raw.githubusercontent.com/TechTreeCoin/TechTrees/master/blockchains/smartchain/assets/0x6A684b3578f5B07c0Aa02fAFc33ED248AE0c2dB2/logo.png) [信息](https://raw.githubusercontent.com/TechTreeCoin/TechTrees/master/blockchains/smartchain/assets/0x6A684b3578f5B07c0Aa02fAFc33ED248AE0c2dB2/info.json) [网站](https://www.techtrees.com/) [资源管理器](https://bscscan.com/token/0x6A684b3578f5B07c0Aa02fAFc33ED248AE0c2dB2) 标签：staking，gamefi 令牌检查错误： ❌未检查的持有人数量：请手动检查
> 
> 

holders:40731

**Pull request merged**
