### PR TITLE
Add ProjectPanda

### PR DESCRIPTION
**Pull request by ProjectPNDA**
Hi, Do Help Add ProjectPanda Logo & Info

### CODE REVIEW

**Comment by Cryptocool1** [comment]
Hello, 
-  Contract is not in checksum format, should be 0x4273d797Ebc0063d5d887B1e67daD4A43E2Fd244 (not 0x4273d797ebc0063d5d887b1e67dad4a43e2fd244). Please change it.

**Comment by ProjectPNDA** [comment]
Sure - Done ! :)

**Review by openb0x — COMMENTED** [review]
Insufficient number of holders according to the filter conditions 1,946 addresses, instead of 2500.

**Comment by Cryptocool1** [comment]
Hello,
-As per our policy, brand new tokens are not included, there is a minimum requirement of 2500 holder addresses and 5000 transactions, in order to filter out scam tokens.
See the criteria at (mentioned in the first message by the bot): https://community.trustwallet.com/t/how-to-submit-a-token-logo/3863).

**Pull request merged**
