### PR TITLE
Add Landshare Token (BEP20)

### PR DESCRIPTION
**Pull request by ls-jordan**
Adding info for BEP20 token 'Landshare Token'.

PR created by <a href="https://assets.trustwallet.com">TW Assets Management</a>

### CODE REVIEW

**Comment by ls-jordan** [comment]
Migrating existing token already listed on TW. Holder requirement may not be met, but there is an active migration process from V1 token which had over 9k holders. Can you verify that this meets acceptance criteria before payment?

**Comment by Cryptocool1** [comment]
Hello, can you please send your old contract address?

**Comment by ls-jordan** [comment]
> Hello, can you please send your old contract address?

0x9D986A3f147212327Dd658F712d5264a73a1fdB0

**Comment by Cryptocool1** [comment]
You should have a message about migration on explorer page or at least on CoinMarketCap

**Comment by ls-jordan** [comment]
> You should have a message about migration on explorer page or at least on CoinMarketCap

There is one on the explorer page, Coinmarketcap is pending update.

**Comment by Cryptocool1** [comment]
Submission looks good awaiting for fee payment

**Pull request merged**
