### PR TITLE
Add new DEEZNUTS contract and remove old DEEZNUTS logo (followup)

### PR DESCRIPTION
**Pull request by deeznutscoin**
Follow up on https://github.com/trustwallet/assets/pull/11132
We already paid the fee
We made the new logo smaller as requested. Please let me know if you need anything else done in order for this to be merged.

### CODE REVIEW

**Comment by deeznutscoin** [comment]
Just noting again that we already paid and were asked to make another PR, please reference our previous PR: https://github.com/trustwallet/assets/pull/11132

**Comment by cryptomanz** [comment]
Hello,
- Logo image too large, max 100 kB
- Contract is not in checksum format, should be 0x741F72BC9E29f662F2Eb41c5aB450A2cA33bE57D
   Please correct

**Comment by deeznutscoin** [comment]
Should be good to go now 

> Hello,
> 
>     * Logo image too large, max 100 kB
> 
>     * Contract is not in checksum format, should be 0x741F72BC9E29f662F2Eb41c5aB450A2cA33bE57D
>       Please correct

Should be good to go now, let me know if anything else is needed for this to be merged and our old token to be deprecated (0x01921A94e68F8D54F33C5D6f71d6664C35e33269)

**Comment by deeznutscoin** [comment]
@cryptomanz Can you take a look at this when you get the chance and let me know if it's good to be merged?

**Comment by deeznutscoin** [comment]
@Cryptocool1 Thanks, can you also deprecate our old token, 0x01921A94e68F8D54F33C5D6f71d6664C35e33269. 

Found in folder here: https://github.com/trustwallet/assets/tree/master/blockchains/smartchain/assets/0x01921A94e68F8D54F33C5D6f71d6664C35e33269

We need the old logo removed as the token is no longer active.

**Pull request merged**
