### PR TITLE
Adding Asimi Token Info

### PR DESCRIPTION
**Pull request by asimitoken**
Adding Asimi Token Info

### CODE REVIEW

**Comment by bluebxo** [comment]
Ok

**Comment by ramsty** [comment]
Hi!
Could you answer some questions?
• What is the purpose of this token? How will it benefit Trust Wallet users?
• How is the token being distributed? Are you conducting an airdrop?
• Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?
• Is the token listed on a centralized/decentralized exchange?
• Is a Smart Contract audit completed? Where can we find this information?

**Comment by 406712774** [comment]
Yo cancele la suspensión y la boy abolver a canselar

**Comment by asimitoken** [comment]
Hi @ramsty pls see below;

1. $ASIMI can be earned by any one by just watching Ads, playing games, completing surveys etc. its basically a Ad minting project and we have over 500k user base who earn $ASIMI daily and they are mostly on trust wallet apart from waves. So, our users on trust wallet will be benefitted.
2. No, our project is 3 years old, launched on 2018.. we already have over 500k users and all are organic ones. and tokens are earned by them by completing the surveys or playing games or Ads minting etc.
3. No, we did not. $ASIMI circulating supply starting at 0 Asimi’s pre-defined minting schedule of 17,438 tokens are awarded to directly to “Ad Minters” wallets every day.
4. Yes, $ASIMI is listed on P2PB2B, HitBTC, Waves Exchange
5. Our project is build on WAVES blockchain and our asset is not audited yet but we have planned the same.

Hope this helps. Thanks!

**Comment by ramsty** [comment]
Awaiting for smart contract audit. 
Closing PR for now. Please come back to us when all criteria are met.

**Comment by asimitoken** [comment]
our project is built on WAVES and we have Asset ID not smart contract. our asset ID is already verified and deployed on WAVES about 3 years ago. I request you to pls merge our PR. Thanks @ramsty

**Comment by asimitoken** [comment]
Hi, our project is built on WAVES, hence no smart contract audit is applicable.  I request you to pls merge our PR. Thanks @ramsty @Iamdeadlyz @Cryptocool1

**Pull request closed without merging**
