### PR TITLE
Pls add BHT (BillionHappiness)

### PR DESCRIPTION
**Pull request by BHCHappiness**

### CODE REVIEW

**Comment by billyeun** [comment]
Done payment 2,000 TWT
83615715_2669314183386891_5657138359304213150_n

**Comment by billyeun** [comment]
I paid already when I can see the logo of BillionHappines (BHT) on Trust
Wallet?

**Comment by zachzwei** [comment]
What is the token contract address?
The address your provided is just a regular ETH address.

**Comment by billyeun** [comment]
Sorry i forget, This is the contract address

0x32e3298939D56D0bb0dA5BD20dE8b589FF5e1B57

**Comment by billyeun** [comment]
Contract Address:  0x32e3298939d56d0bb0da5bd20de8b589ff5e1b57
Name: BillionHappiness
Symbol: BHT
Decimals: 18

Salamat po. :)

**Comment by billyeun** [comment]
@zachzwei Can I able to see BHT asset in trust wallet? or how long it takes to see the logo or asset? 

Salamat/Thank you po.

**Pull request merged**
