### PR TITLE
Royal BNB token Logo and Info Submission

### PR DESCRIPTION
**Pull request by royalbnbdev**
Uploading Royal BNB token logo and the required relevant information

### CODE REVIEW

**Comment by royalbnbdev** [comment]
Payment Sent.

**Comment by Cryptocool1** [comment]
As per our policy, brand new tokens are not included, there is a minimum requirement of 5000 holder addresses and 10000 transactions, in order to filter out scam tokens.
See the criteria at (mentioned in the first message by the bot): https://community.trustwallet.com/t/how-to-submit-a-token-logo/3863).

**Comment by royalbnbdev** [comment]
> As per our policy, brand new tokens are not included, there is a minimum requirement of 5000 holder addresses and 10000 transactions, in order to filter out scam tokens.
> See the criteria at (mentioned in the first message by the bot): https://community.trustwallet.com/t/how-to-submit-a-token-logo/3863).

Dear Cryptocool1,

Yes we have read out the mentioned terms. But as per the criteria it is said that - This requirement is subject for review based on the project. Thus we submitted the request for Logo and Token Information.

To mention, we are one of the most trustworthy and reliable bep-20 token on binance smart chain along with highest bnb rewards. We have been increasing our holders organically and fulfilling our checkpoints gradually.

We are listed on -
CoinGecko -> https://www.coingecko.com/en/coins/royal-bnb
CoinMarketCap ->https://coinmarketcap.com/currencies/royal-bnb/

Also we had done a full audit even before presale. 
Audit Link -> https://github.com/sokenteam/smart_contract_audits/blob/ef59c577be351fc758d4343d348476feba368757/Royal%20BNB%20Standard%20Smart%20Contract%20Audit.pdf

For Further Information you can check our website kindly. Web -> https://royalbnb.net/

DexTool Link -> https://www.dextools.io/app/pancakeswap/pair-explorer/0xf776d004cfd9abf4318c70b66edfba91441ef703

We are very excited and community is eager to get Logo in TrustWallet. We would request you to kindly review us and permit the Logo submission.

Thank you 
Best Regards
Lead Royal BNB Dev
John

**Comment by royalbnbdev** [comment]
@Cryptocool1 @zachzwei @catenocrypt 

Hello guys, have you been able to review the above mentioned comment ? We are all eagerly waiting for the TrustWallet Logo acceptance, could you kindly review and let us be accepted.

Thank you.

**Comment by zachzwei** [comment]
The submission will be on hold until the requirements have been met.

**Comment by Cryptocool1** [comment]
Closing PR for now. Please come back to us when all criteria are met. Make sure to mention this PR, so the fee can be reused

**Pull request closed without merging**
