### PR TITLE
add cloak's info and logo

### PR DESCRIPTION
**Pull request by calvingreen**
add cloak's info and logo

### CODE REVIEW

**Comment by calvingreen** [comment]
we are 10,249 holder addresses and 33,979 transactions

**Comment by Cryptocool1** [comment]
Hello, how did you get your holders less than in 1 day?

**Comment by calvingreen** [comment]
> Hello, how did you get your holders less than in 1 day?

CLOAK is the second token within the Milo Inu ecosystem and is an
indispensable companion of Milo in our animated series. They will
work together in unison to sustain the entire ecosystem. CLOAK
NFT’s are a collection of images created by MILO artists based on
IP’s from various fields with a total supply of 1,111 including 54 1/1
NFT’s. Each CLOAK is unique and as such each will have important
powers within the MILO ecosystem and the metaverse.

Milo Inu's holders is 100,686

**Comment by Cryptocool1** [comment]
• What is the purpose of this token? How will it benefit Trust Wallet users?
 • How is the token being distributed? Are you conducting an airdrop?
 • Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?
 • Is the token listed on a centralized/decentralized exchange?
 • Is a Smart Contract audit completed? Where can we find this information?

**Comment by calvingreen** [comment]
- What is the purpose of this token? How will it benefit Trust Wallet users?
	The purpose of CLOAK is to empower the MILO ecosystem. Users will realize the benefits of PtoE and the fun of the game experience in the game.
- The token distribute：
	1. Presale: 50% of Total Supply
	2. Pancake LP: 25% of Total Supply (Locked for 69 Years)
	3. Burn: 10% of Total Supply 
	4. Play to Earn: 10% of Total Supply 
	5. Staking: 5% of Total Supply locked/vested for 3 months.
- Are you conducting an airdrop?
	Because it is a child of the O ecology, and also has the related empowerment of NFT, GAME users initiate activities to carry out airdrops of MILO, as well as airdrops to MILO.
- Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?
	The project party has a small amount of reserved tokens. At present, the project funds are sufficient for subsequent ecological empowerment. When the ecosystem needs to be improved, some tokens will be sold for ecological construction.
- Is the token listed on a centralized/decentralized exchange?
	The token is currently listed on the BSC chain. When the token holder reaches 2W, it will be listed on the exchange. Currently, the exchanges connected to it include matcha, etc.
- Is a Smart Contract audit completed? Where can we find this information?
	The contract audit has been submitted on CMC, and the contract of the parent currency has been reviewed. The parent currency audit address is referenced:
	https://www.certik.com/projects/milo-inu

**Comment by Cryptocool1** [comment]
We require audit of the token you submitted

**Comment by calvingreen** [comment]
CLOAK TOKEN：
https://bscscan.com/token/0x8077398Ff2c530f129a6dd8D7F1E8840312440CD


CLOAK Website：
https://milotoken.io/#/

CLOAK NFT Website：
https://milocloak.com/

CLOAK WP：
https://milotoken.io/static/MiloInu_en.pdf

**Comment by Cryptocool1** [comment]
Awaiting for smart contract audit and CoinMarketCap listing, on hold for now

**Comment by Cryptocool1** [comment]
feel free to create new Pull Request once all criteria are met. Make sure to mention this PR so the fee can be reused

**Pull request closed without merging**
