### PR TITLE
Add PYM logo

### PR DESCRIPTION
**Pull request by PYMoperator**
image size: 250 x 250
format : png
letters in name: small,

Thank You.

### CODE REVIEW

**Comment by PYMoperator** [comment]
What I made wrong here? That is faild ? How to fix it ?

**Comment by catenocrypt** [comment]
Please add an `info.json` file next to the `logo.png`, with info about the project, of the form:

```json
{
    "name": "Trust Wallet Token",
    "website": "https://trustwallet.com",
    "short_description": "Utility token to increase adoption of cryptocurrency.",
    "explorer": "https://explorer.binance.org/asset/TWT-8C2"
}
```

**Review by PYMoperator — COMMENTED** [review]
check now, please

**Comment by catenocrypt** [comment]
As per our policy, brand new tokens are not included, there is a minimum requirement of 100 holder addresses and 500 transactions, in order to filter out scam tokens.
See the criteria at (mentioned in the first message by the bot): https://community.trustwallet.com/t/how-to-submit-a-token-logo/3863#how-to-get-approved
This token has no usage yet (1 holder address).  Putting PR on hold.  Please return when criteria are met.

https://etherscan.io/token/0x9cf9840069655ff7411d4a81b9a87bb8f711db08

**Comment by PYMoperator** [comment]
Of course , I am understand, so 100 holders and 500 transaction is minimum ? 
I need to do something more when my coin will achieve it ? or it will be authomatically ?

**Comment by catenocrypt** [comment]
You need to write a new comment in this PR, we will reopen.

**Comment by PYMoperator** [comment]
Wait because we will start presale and we will have than all requierements
done




W dniu pt., 11.09.2020 o 04:29 stale[bot] <notifications@github.com>
napisał(a):

**Comment by catenocrypt** [comment]
Don't worry, this PR will stay here, even if is closed by automation due to inactivity, we can reopen it any time.

**Pull request closed without merging**
