### PR TITLE
AERDrop logo for new v2 contract

### PR DESCRIPTION
**Pull request by Aerdropv2**
AERDrop was launched under a new contract back in July of 2021. This is the new one.

### CODE REVIEW

**Comment by Aerdropv2** [comment]
What does this error mean? 
❌ The links field cannot be empty

**Comment by Cryptocool1** [comment]
see the example here: https://developer.trustwallet.com/assets/repository_details

**Comment by cryptomanz** [comment]
• What is the purpose of this token? How will it benefit Trust Wallet users?
 • How is the token being distributed? Are you conducting an airdrop?
 • Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?
 • Is the token listed on a centralized/decentralized exchange?
 • Is a Smart Contract audit completed? Where can we find this information?

**Comment by Aerdropv2** [comment]
• What is the purpose of this token? How will it benefit Trust Wallet users?

Holding AER entitles the holder to receive free tokens from partner projects via airdrops. The amount of partner tokens AERDropped is proportional to a user's holdings of AER. To date, we have distributed well over $1M in free tokens (when measured at those tokens all time highs) to our holders.

It is important to note that this is a v2 of a token that is already listed on TrustWallet - the old contract is 0x1a6C2c3c52cd3CC21DB2b8f2B331ca9c4780F1Ee

Adding the logo will reduce confusion for Trust Wallet users that still see the old token with a logo and the new one without one.

• How is the token being distributed? Are you conducting an airdrop?

The new token was distributed via airdrop to existing holders of the v1 tokens on July 6, 2021. Existing holders received an equal value of tokens to what they held of the previous token.

AERDrop is also listed on Pancake Swap and may be bought and sold there.

• Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?

The v1 token was fair launched on PancakeSwap. There was no ICO or presale for the current contract.

• Is the token listed on a centralized/decentralized exchange?

The token is listed on PancakeSwap.
It can also be purchased/sold on Flooz.trade - https://www.flooz.trade/wallet/0xc7ad2ce38f208eed77a368613c62062fce88f125/?refId=HCQKzq

• Is a Smart Contract audit completed? Where can we find this information?

The current contract was audited by WatchTower. That report is available on our website (top nav - right hand link)
A direct link to the document is here: https://assets.website-files.com/60e6828b40f27c5e6ee118c4/6150c549093846f4807000f7_AerDrop%20Smart%20Contract%20Security%20Audit.pdf

**Comment by Aerdropv2** [comment]
FYI - references to our new token launch can be seen on both our CoinGecko and CoinMarketCap pages.

If desired, we can submit a commit to delete the old token's logo along with this pull request.

**Comment by Cryptocool1** [comment]
is the previous token abondoned now?

**Comment by Aerdropv2** [comment]
Yes, it is no longer supported.

**Comment by Cryptocool1** [comment]
> Yes, it is no longer supported.

you should create new PR for the previous contract and change the status to abandoned, and then I will remove the logo

**Comment by Aerdropv2** [comment]
I can do that. Is there another 1000 TWT cost for that merge?

**Comment by Cryptocool1** [comment]
> I can do that. Is there another 1000 TWT cost for that merge?

no

**Comment by Aerdropv2** [comment]
Changed status of old token to abandoned.

**Comment by Cryptocool1** [comment]
can you send an official announcement about migration?

**Comment by Aerdropv2** [comment]
From out Telegram - https://t.me/aerdropofficial/137125

**Comment by Aerdropv2** [comment]
Is there anything else needed for this?

**Pull request merged**
