### PR TITLE
Add URAN logo and info

### PR DESCRIPTION
**Pull request by Uranium7777**
Update of logos and information of the URAN token

### CODE REVIEW

**Comment by Uranium7777** [comment]
Update

**Comment by Uranium7777** [comment]
Update token information

**Comment by Uranium7777** [comment]
Update token information

**Review by Seifollahy — COMMENTED** [review]
0x2eD72c04b517fa0Aa964790EBA9718864bdafbaa

**Review by Seifollahy — COMMENTED** [review]
0x2eD72c04b517fa0Aa964790EBA9718864bdafbaa

**Pull request closed without merging**
