### PR TITLE
Add Step Hero logo

### PR DESCRIPTION
**Pull request by sontung-stephero**
Add logo for Step Hero RPG Game

### CODE REVIEW

**Comment by cryptomanz** [comment]
Hello,
Can your answer some questions?
• What is the purpose of this token? How will it benefit Trust Wallet users?
• How is the token being distributed? Are you conducting an airdrop?
• Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?
• Is the token listed on a centralized/decentralized exchange?
• Is a Smart Contract audit completed? Where can we find this information?

**Comment by sontung-stephero** [comment]
> Hello,
> Can your answer some questions?
> • What is the purpose of this token? How will it benefit Trust Wallet users?
> • How is the token being distributed? Are you conducting an airdrop?
> • Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?
> • Is the token listed on a centralized/decentralized exchange?
> • Is a Smart Contract audit completed? Where can we find this information?

**1. What is the purpose of this token? How will it benefit Trust Wallet users?**
$HERO is our government and utility token.
  The primary utilities of the HERO token are:
    
    - HERO Farming: HERO tokens are used for farming Points that users can use for NFT redemption. 
    - Payment in HNM: HERO tokens are used as a payment currency in Hero NFTs Marketplace along with other tokens
    - Voting: Holder of a certain amount of $HERO token will have the voting power on decisions regarding project development
    - In-game payment: In-game transactions are made in $STEP, the in-game currency. User will have to buy $STEP using $HERO.
  In the future, Step Hero Ecosystem will update with more use cases for the HERO token.

**2. How is the token being distributed? Are you conducting an airdrop?**
Hero token distributed via public, seed and private sale and IDO. Conducting airdrop on CoinMarketCap
More information at: https://whitepaper.stephero.io/hero-tokennomics/hero-token-and-distributions
**3. Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?**
No
 **4. Is the token listed on a centralized/decentralized exchange?**
Now you can transact $HERO on #PancakeSwap and #MEXC 

**5. Is a Smart Contract audit completed? Where can we find this information?**
Audited buy Hacken
https://hacken.io/audits/#step_hero

**Comment by cryptomanz** [comment]
According to our documentation token image needs to be full screen, here is link to guidelines details and an example of token images https://community.trustwallet.com/t/how-to-submit-a-token-logo/3863

**Comment by sontung-stephero** [comment]
> According to our documentation token image needs to be full screen, here is link to guidelines details and an example of token images https://community.trustwallet.com/t/how-to-submit-a-token-logo/3863

I updated logo, please have a look

**Comment by Cryptocool1** [comment]
still not the full screen logo

**Comment by sontung-stephero** [comment]
> still not the full screen logo

Can you help to check the logo again?

**Pull request merged**
