### PR TITLE
Update BLANK token after swap

### PR DESCRIPTION
**Pull request by ElectricJeans**

### CODE REVIEW

**Comment by Cryptocool1** [comment]
do you have an official information about updating?

**Comment by ImanH** [comment]
> 
> 
> do you have an official information about updating?

This is the article regarding the hack; https://blankwallet.medium.com/important-announcement-regarding-the-chainswap-hack-fc5eb095658f

And this is the tweet regarding token migration: https://twitter.com/BlankWallet/status/1416031594721288195

**Comment by RodrigoCalvo** [comment]
@Cryptocool1 here `blockchains/ethereum/tokenlist.json` our token is not updated yet... how can we update it? cc: @ImanH

**Comment by ImanH** [comment]
@Cryptocool1 this was merged, but the token list was not updated, which leads to some confusion with the old token for some trustwallet users. Please have a look at this https://github.com/trustwallet/assets/pull/13427

CC: @catenocrypt @zachzwei

**Pull request merged**
