### PR TITLE
Add CTC(TM) logo and info

### PR DESCRIPTION
**Pull request by Shahidustadi**
Kindly add CTC(TM) info and logo

### CODE REVIEW

**Comment by cryptomanz1** [comment]
Correction needed:
This is a BEP20 token, correct folder is blockchains/smartchain/assets. Please correct.

**Comment by Grouphelpcenter** [comment]
> Correction needed:
> This is a BEP20 token, correct folder is blockchains/smartchain/assets. Please correct.

We'd be happy to look into this for you. Kindly file a support ticket here
https://forms.gle/zVGLP7GATPsDHdkH9

**Comment by Grouphelpcenter** [comment]
> Kindly add CTC(TM) info and logo

We'd be happy to look into this for you. Kindly file a support ticket here
https://forms.gle/zVGLP7GATPsDHdkH9

**Comment by Shahidustadi** [comment]
How can i correct this?

**Comment by cryptomanz1** [comment]
• What is the purpose of this token? How will it benefit Trust Wallet users?
 • How is the token being distributed? Are you conducting an airdrop?
 • Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?
 • Is the token listed on a centralized/decentralized exchange?
 • Is a Smart Contract audit completed? Where can we find this information?

**Comment by Shahidustadi** [comment]
> • What is the purpose of this token? How will it benefit Trust Wallet users? • How is the token being distributed? Are you conducting an airdrop? • Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale? • Is the token listed on a centralized/decentralized exchange? • Is a Smart Contract audit completed? Where can we find this information?

[CTC(TM) (1).pdf](https://github.com/trustwallet/assets/files/10608803/CTC.TM.1.pdf)

**Comment by Cryptocool1** [comment]
Please send your audit not in PDF format

**Comment by Shahidustadi** [comment]
everything can be found in the pdf

**Comment by Cryptocool1** [comment]
Send all the answers here

**Comment by Shahidustadi** [comment]
What is this token used for?
CTC(TM) can be used for kiosks developed by Cybertronchain.com or payment for online shopping malls. It is also used for smart recognition of garbage disposal devices or using NFTs. You can get enough rewards by staking. 

What are the benefits for Trust Wallet users? 
Cybertronchain.com's app CTC Wallet or Staking NOSE SWAP can connect Trust Wallet, and most 90% of users use Trust Wallet.

How are tokens being distributed? 
Swap ERC20 tokens from CTC Wallet to CTC(TM). However, only authorized tokens are available, and there are additional rewards and events compared to swapping in general exchanges. 

Do you conduct an airdrop? 
5% of the issued amount is airdropped for 1 year.

Did you sell your tokens in an Initial Coin Offering (ICO) or token pre-sale? 
Currently, IEO is scheduled for 3 exchanges, and legal certificates are being issued and reviewed.

Is the token listed on a centralized/decentralized exchange? 
Trade on pancake swaps.

Have smart contract audits been completed? Where can I find this information?
https://github.com/Hansblock/CTC-TM-.sol/blob/main/CTC7.sol

**Comment by Shahidustadi** [comment]
is this okay

**Comment by Cryptocool1** [comment]
Please send your smart contract audit.

**Comment by Shahidustadi** [comment]
https://github.com/Hansblock/CTC-TM-.sol/blob/main/CTC(TM).sol

**Comment by Shahidustadi** [comment]
here is audit https://github.com/Hansblock/CTC-TM-.sol/blob/main/CTC(TM).sol

**Review by valentin2001-hub — COMMENTED** [review]
Gg

**Comment by cryptomanz1** [comment]
that is not smart contract audit. Here is an example: https://www.certik.com

**Comment by Cryptocool1** [comment]
Please come back to us once smart contract audit completed. Make sure to mention this PR in new one, so the fee can be reused

**Comment by Shahidustadi** [comment]
https://fairyproof.com/doc/CybertronChain-Token-Audit-Report-020923.pdf

**Comment by Shahidustadi** [comment]
have opened a new pr but its asking for payment 
how can i do it

**Comment by Cryptocool1** [comment]
Is your token listed on CMC?

**Comment by Shahidustadi** [comment]
yes

**Comment by Shahidustadi** [comment]
??

**Comment by Cryptocool1** [comment]
Please send your CoinMarketCap link

**Comment by Shahidustadi** [comment]
https://coinmarketcap.com/currencies/cybertronchain/

**Comment by Cryptocool1** [comment]
I can see there only ERC20 contract address

**Comment by Shahidustadi** [comment]
yes planing on listing the bep20

**Comment by Cryptocool1** [comment]
Awaiting for displaying BEP20 token on CMC

**Review by Taylor295 — COMMENTED** [review]
I hope everything goes well

**Comment by Taylor295** [comment]
What do I need to do

**Comment by Taylor295** [comment]
What I am supposed to do

**Comment by Taylor295** [comment]
How do I make a Withdrawal

**Comment by Taylor295** [comment]
I did what you Requested

**Pull request merged**
