### PR TITLE
Update our new BHC logo

### PR DESCRIPTION
**Pull request by BHCHappiness**
logo

### CODE REVIEW

**Comment by BHCHappiness** [comment]
paid

**Comment by Iamdeadlyz** [comment]
To clarify, you want to use this logo for https://bscscan.com/address/0xa6381c6fd8f40a44721ef4f61edc1a8ccca7bf3d?
image

And this logo for https://etherscan.io/token/0x32e3298939D56D0bb0dA5BD20dE8b589FF5e1B57?

**Comment by BHCHappiness** [comment]
Yes, but our team suggested deleting the logo of BHT ERC20 

BillionHappiness is now focused on Binance Smart Chain BEP20

Thank you

**Comment by BHCHappiness** [comment]
Please delete or remove the BHT logo because some newcomers and newbie in crypto are confused so we decided to delete the BHT logo.

**Comment by BHCHappiness** [comment]
@Iamdeadlyz all is good now? :) Thank you

**Comment by Iamdeadlyz** [comment]
It's already merged.

**Comment by BHCHappiness** [comment]
@Iamdeadlyz Okay we will wait for it to show on Trust wallet.

Salamat/Thank you

**Comment by BHCHappiness** [comment]
Hello @Iamdeadlyz 
Hello team,

We will migrate to a new contract please update our contract address bscscan already updated our new contract you can check it below for our logo viewing to the trust wallet.

Old contract: https://bscscan.com/token/0xa6381c6fd8f40a44721ef4f61edc1a8ccca7bf3d 

New contract: https://bscscan.com/token/0x6fd7c98458a943f469e1cf4ea85b173f5cd342f4

Public announcement: https://twitter.com/BHC_Happiness/status/1339804061797793794?s=20

**Pull request merged**
