### PR TITLE
add cloak's info and logo

### PR DESCRIPTION
**Pull request by calvingreen**
https://github.com/trustwallet/assets/pull/22058

### CODE REVIEW

**Comment by calvingreen** [comment]
First PR : https://github.com/trustwallet/assets/pull/22058

contract audit: [CLOAK-BSC-Audit-20654314.pdf](https://dessertswap.finance/audits/CLOAK-BSC-Audit-20654314.pdf)
CG：https://www.coingecko.com/en/coins/cloak-coin
CMC：processing
Mexc: https://www.mexc.com/exchange/CLOAK_USDT

Can we pass the review soon? Thanks~

**Comment by Cryptocool1** [comment]
hello, we require CMC listing. See the criteria at : https://developer.trustwallet.com/assets/requirements .
On hold for now.

**Comment by calvingreen** [comment]
cmc: https://coinmarketcap.com/currencies/cloak/

**Comment by calvingreen** [comment]
> hello, we require CMC listing. See the criteria at : https://developer.trustwallet.com/assets/requirements . On hold for now.

cmc: https://coinmarketcap.com/currencies/cloak/

**Comment by calvingreen** [comment]
> > hello, we require CMC listing. See the criteria at : https://developer.trustwallet.com/assets/requirements . On hold for now.
> 
> cmc: https://coinmarketcap.com/currencies/cloak/

ok？

**Pull request merged**
