### PR TITLE
Add NBOX (BEP20)

### PR DESCRIPTION
**Pull request by coder9871**
Adding info for BEP20 token 'NBOX'.

PR created by <a href="https://assets.trustwallet.com">TW Assets Management</a>

### CODE REVIEW

**Comment by Cryptocool1** [comment]
• What is the purpose of this token? How will it benefit Trust Wallet users?
 • How is the token being distributed? Are you conducting an airdrop?
 • Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?
 • Is the token listed on a centralized/decentralized exchange?
 • Is a Smart Contract audit completed? Where can we find this information?

**Comment by coder9871** [comment]
Fee is PAID

**Comment by coder9871** [comment]
• What is the purpose of this token? How will it benefit Trust Wallet users?
NBOX is the native utility token of the NBOX project.
We have more than more than 22K community members; With the development of the project, we are gonna add TrustWallet as one of the way for players to receiving their tokens. That's why we want to add the token logo to TrustWallet to make it more easier to find and without mistakes.

• How is the token being distributed? Are you conducting an airdrop?
We have a detailed Token Distribution Plan:
https://docs.nbox.io/en/token-distribution/about-nbox-token
We don't have Airdrops at present.

• Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?
No,not yet.

• Is the token listed on a centralized/decentralized exchange?
Yes, PanCakeSwap
You can find it below:
[https://pancakeswap.finance/info/pool/0xa0219e1b3034cf546650bfcc474afcfe4486dc03](https://coinmarketcap.com/currencies/cryptostone/markets/)

• Is a Smart Contract audit completed? Where can we find this information?
No, not yet.

**Comment by coder9871** [comment]
> • What is the purpose of this token? How will it benefit Trust Wallet users? • How is the token being distributed? Are you conducting an airdrop? • Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale? • Is the token listed on a centralized/decentralized exchange? • Is a Smart Contract audit completed? Where can we find this information?

• What is the purpose of this token? How will it benefit Trust Wallet users?
NBOX is the native utility token of the NBOX project.
We have more than more than 22K community members; With the development of the project, we are gonna add TrustWallet as one of the way for players to receiving their tokens. That's why we want to add the token logo to TrustWallet to make it more easier to find and without mistakes.

• How is the token being distributed? Are you conducting an airdrop?
We have a detailed Token Distribution Plan:
https://docs.nbox.io/en/token-distribution/about-nbox-token
We don't have Airdrops at present.

• Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?
No,not yet.

• Is the token listed on a centralized/decentralized exchange?
Yes, PanCakeSwap
You can find it below:
[https://pancakeswap.finance/info/pool/0xa0219e1b3034cf546650bfcc474afcfe4486dc03](https://coinmarketcap.com/currencies/cryptostone/markets/)

• Is a Smart Contract audit completed? Where can we find this information?
No, not yet.

**Comment by Cryptocool1** [comment]
We require smart contract audit from reputable companies. On hold for now

**Comment by Cryptocool1** [comment]
Feel free to create new PR once all criteria are met. Make sure to mention this PR so the fee can be reused

**Pull request closed without merging**
