### PR TITLE
add xcarnival token info

### PR DESCRIPTION
**Pull request by xcarnival-alan**

### CODE REVIEW

**Comment by Cryptocool1** [comment]
Please come back to us when you'll be ready with answers.
When creating a new PR make sure to mention this PR, so that we can see that fee has been paid already here.

**Comment by xcarnival-alan** [comment]
> Hi!
> Could you answer some questions?
> • What is the purpose of this token? How will it benefit Trust Wallet users?
> • How is the token being distributed? Are you conducting an airdrop?
> • Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?
> • Is the token listed on a centralized/decentralized exchange?
> • Is a Smart Contract audit completed? Where can we find this information?

• What is the purpose of this token? How will it benefit Trust Wallet users?
XCV is XCarnival’s governance token.
Holders will be able to vote on key decisions for projects such as protocol parameters, rewards distribution, and the design of NFTs’ parameters.
XCV will capture platform economic benefits.
There are multiple buyback mechanics to help XCV holders to capture protocol's economic benefits. 
XCV can be used in partner's scenes.
XCV holders can use XCV token to participate other projects and earn extra benefits. 
 

• How is the token being distributed? Are you conducting an airdrop?
Half of total token supply comes from mining, others will be released slowly according to tokenomics. We’ve already conducted an airdrop to our early supporters and willing to organize another one to Trust wallet users if necessary.
 
• Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?
We didn’t sold token through ICO or IDO, but we chosed a mystery box offering instead. People brought NFT mystery boxes and then used these NFTs to mine the XCV rewards. It was a very successful launch. Now we have a solid community with over 78000+ members.https://t.me/XCarnivalCommunity

• Is the token listed on a centralized/decentralized exchange?
XCV has been listed on Pancake/ Apeswap. Gate and MEXC have been booked already and will list in following weeks.

• Is a Smart Contract audit completed? Where can we find this information?
Yes, we’ve audited by Certik, here is the link: https://www.certik.org/projects/xcarnival

**Comment by xcarnival-alan** [comment]
@ramsty @Cryptocool1  sorry for the late reply, please check the information, thanks.

**Comment by Cryptocool1** [comment]
Hello, 
Can you change your logo to the full screen image?

**Comment by xcarnival-alan** [comment]
@Cryptocool1 what do you mean by the full screen image?

**Comment by Cryptocool1** [comment]
there should be no space from each side

**Comment by xcarnival-alan** [comment]
xcv_logo
@Cryptocool1 please help to see if this image meets the requirements, thx

**Review by Echalon2020 — APPROVED** [review]

**Pull request merged**
