### PR TITLE
Add logo and info

### PR DESCRIPTION
**Pull request by bigdogecoin**

### CODE REVIEW

**Comment by Cryptocool1** [comment]
Hello,
• What is the purpose of this token? How will it benefit Trust Wallet users?
 • How is the token being distributed? Are you conducting an airdrop?
 • Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?
 • Is the token listed on a centralized/decentralized exchange?
 • Is a Smart Contract audit completed? Where can we find this information?

**Comment by bigdogecoin** [comment]
Hi @Cryptocool1,

> **What is the purpose of this token? How will it benefit Trust Wallet users?**
The tokens is used in our Gaming ecosystem, users can access our upcoming Dapp from Trust Wallet through Wallet Connect.

> **How is the token being distributed? Are you conducting an airdrop?**
The token has been distributed in presale.
Yes. We’re having an airdrop, it will be distributed on July 28th.
Airdrop: https://twitter.com/bigdogecrypto/status/1413749666676580352

> **Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?**
We sold it at token Presale.
Presale on DxSale: https://dxsale.app/app/v2_9/defipresale?saleID=898&chain=BSC

> **Is the token listed on a centralized/decentralized exchange?**
Token has been listed on Pancakeswap and we're also working with Bibox.
Pancakeswap: https://exchange.pancakeswap.finance/#/swap?outputCurrency=0x2BA8c3066F36B998bC74CE8DcE260Fb5D2ba6bCc

> **Is a Smart Contract audit completed? Where can we find this information?**
We are having an audit with Callisto.

**Comment by Cryptocool1** [comment]
where can we find the audit?

**Comment by bigdogecoin** [comment]
**> where can we find the audit?**

We are having an audit with Callisto. We’ll announce on our website and social channels once the final report is available.

**Comment by bigdogecoin** [comment]
> **where can we find the audit?**

Hi @Cryptocool1,
Is there any other thing you need to check?
Regarding the Audit, the Dev team has already sent to Callisto Network for audit, it is expected to be completed in 1 week, and our team is trying accelerate the process.

**Comment by bigdogecoin** [comment]
> **where can we find the audit?**
Hi @Cryptocool1 .
Audit information can be found here (In Progress): https://github.com/EthereumCommonwealth/Auditing/issues/535

**Comment by Cryptocool1** [comment]
awaiting for full audit

**Comment by bigdogecoin** [comment]
> Hello,
> please create new PR when smart contract audit will be ready.
> make sure to mention this PR, so that we can see that fee has been paid already here.

Hi @Cryptocool1,
I will send the Big Doge audit report as soon as possible, thank you!

**Comment by bigdogecoin** [comment]
Hi @Cryptocool1,
We have now completed the audit of Smartcontract, your team can check it out:
https://gist.github.com/yuriy77k/d38c8c73c9fed40574392e819a2fa403

This is new PR: https://github.com/trustwallet/assets/pull/11982.

**Pull request closed without merging**
