### PR TITLE
Add Vista Finance (BEP20)

### PR DESCRIPTION
**Pull request by dugesar**
Adding info for BEP20 token 'Vista Finance'.

### CODE REVIEW

**Comment by dugesar** [comment]
• What is the purpose of this token? How will it benefit Trust Wallet users?  --- We are creating P2P lending borrowing system based on future trading using AI, also a physical P2P trading like the uber services for P2P. Token is already on many wallets and we also have our on wallet on playstore https://play.google.com/store/apps/details?id=com.vistafinance people are interested that it should be on trustwallet as well.

• How is the token being distributed? Are you conducting an airdrop? --- Purchase from Exchange and swap and website. No Airdrop

• Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale? --- No Presale or ICO

• Is the token listed on a centralized/decentralized exchange? ---- Yes, https://nexdax.com/exchange-base.html?symbol=VISTA_USDT, Pancake SWAP

• Is a Smart Contract audit completed? Where can we find this information? --- Yes, https://github.com/TechRate/Smart-Contract-Audits/blob/main/August_2024/Vista%20Finance.pdf

**Comment by rds0751** [comment]
Dear @Cryptocool1, @cryptomanz1  kindly look at our request to add the VISTA token.
All auto-checks and payment have been completed.

**Comment by dugesar** [comment]
@cryptomanz1  
The market is not showing in Trust Wallet, can you please enable Market here is our token CMC Details for tracked market and price https://coinmarketcap.com/currencies/koloop-basic/

**Comment by dugesar** [comment]
@cryptomanz1  
The market is not showing in Trust Wallet, can you please enable Market here is our token CMC Details for tracked market and price https://coinmarketcap.com/currencies/koloop-basic/

**Pull request merged**
