### PR TITLE
Add SOURCE Token (SOURCE) (ERC20) (CELO)

### PR DESCRIPTION
**Pull request by Bridgerz**

### CODE REVIEW

**Comment by Bridgerz** [comment]
> SOURCE

"Unknown asset type" check is still referencing "SOURCE" but it has changed to "ERC20" and "CELO" respectively.

**Comment by Bridgerz** [comment]
SOURCE token transaction volume is spread across, Celo and BSC:
CELO: 0x74c0C58B99b68cF16A717279AC2d056A34ba2bFe
BSC: 0xea136fc555e695ba96d22e10b7e2151c4c6b2a20

**Comment by cryptomanz** [comment]
• What is the purpose of this token? How will it benefit Trust Wallet users?
 • How is the token being distributed? Are you conducting an airdrop?
 • Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?
 • Is the token listed on a centralized/decentralized exchange?
 • Is a Smart Contract audit completed? Where can we find this information?

**Comment by Cryptocool1** [comment]
Feel free to open new PR when you'll be ready to answer the questions.
When creating a new PR make sure to mention this PR, so that we can see that fee has been paid already here.

**Pull request closed without merging**
