### PR TITLE
update token contract and add new token

### PR DESCRIPTION
**Pull request by bi0hazard12**
Hello,

An year ago we have created our project and have added it already in trust wallet. As of right now our project changed and we have a new contract address for our DEUS token, we want to remove the old DEUS contract 0x3b62F3820e0B035cc4aD602dECe6d796BC325325 to this new one 0xDE5ed76E7c05eC5e4572CfC88d1ACEA165109E44.

Also at same time we like to add a new token from our ecosystem that is DEI  - 0xDE12c7959E1a72bbe8a5f7A1dc8f8EeF9Ab011B3

DEI is our stablecoin.

At same time we like to know if pulling a request as an ERC20 type token, it will be reflected also on polygon network?

Thank you so much for your help :) 

Merry Christmas and Happy New Year :)

### CODE REVIEW

**Comment by bi0hazard12** [comment]
I've also checked right now that this pull request is also trying to change info for 0x80aB141F324C3d6F2b18b030f1C4E95d4d658778 and 0x4185cf99745B2a20727B37EE798193DD4a56cDfa creating some conflits, but we don't want to change any info or logo on that token, DEA and wCOINBASE-IOU token doesn't exist anymore and can also be removed with the old DEUS 0x3b62F3820e0B035cc4aD602dECe6d796BC325325 if need it.

on this request we just want to update our DEUS token from old contract to a new one 0xDE5ed76E7c05eC5e4572CfC88d1ACEA165109E44

and ADD the new token from our ecosystem DEI
0xDE12c7959E1a72bbe8a5f7A1dc8f8EeF9Ab011B3

Sorry for the confusion. I don't know why it's trying to update info from old requests.

Thank you once again :)

**Comment by bi0hazard12** [comment]
@Cryptocool1 @cryptomanz or @ramsty can we get some assistance here please? Appreciated :)

**Comment by cryptomanz** [comment]
Please create new PR, with new contract and i will put status abandoned in your old contract. Make sure to mention this PR, so that we can see that fee has been paid already here.

**Comment by bi0hazard12** [comment]
> Please create new PR, with new contract and i will put status abandoned in your old contract. Make sure to mention this PR, so that we can see that fee has been paid already here.

Hey Nazar, 

On this PR i already submitted the new contract for DEUS token and also the new DEI token (our algorithmic stable coin). Do i still need to create a new PR? Was this one created in a wrong way ?

Thank you

**Pull request closed without merging**
