### PR TITLE
Add dexIRA (BEP20)

### PR DESCRIPTION
**Pull request by dexfi-com**
Adding info for BEP20 token 'dexIRA'.

PR created by <a href="https://assets.trustwallet.com">TW Assets Management</a>

### CODE REVIEW

**Comment by dexIRA** [comment]
### Payment sent in PR #13456 

- **PAID IN TWT** via [13456](https://github.com/trustwallet/assets/pull/13456) / [12795](https://github.com/trustwallet/assets/pull/12795)

> _please create new PR when all criteria are met. make sure to mention this PR, so the fee can be reused. #13456_ 

Previous Payment TxID: [D504C0C2687D8405338F514B90CDCB7D8DAFE356BB0F867AFD64BA06A368EB8B](https://explorer.binance.org/tx/D504C0C2687D8405338F514B90CDCB7D8DAFE356BB0F867AFD64BA06A368EB8B)

**Comment by dexIRA** [comment]
### Q&A answers via Telegram:

> @Cryptocool1 What is the purpose of this token? How will it benefit Trust Wallet users?

dexIRA (www.dexIRA.com) is a platform that allows users to collect and manage a diverse array of curated cryptocurrency tokens by holding dexIRA ($DEX) tokens. Each reward distribution is automatically claimed by the holder and sent to their wallet. There are zero transaction fees on buy orders to incentivize investment. All sell transaction fees are waived after one year of holding DEX tokens without sale, promoting a long term investing strategy and reliable price support.

This will benefit Trust Wallet users by enabling them to acquire a secure and well rounded portfolio of established tokens with a history of success. In addition, our dApp (dashboard) gives users the opportunity to view and monitor advanced portfolio metrics which offers useful insight to their investments.

> How is the token being distributed? Are you conducting an airdrop?

We do not conduct any airdrops. All tokens must be bought on the open market (including dev tokens).

> Did you sell the tokens at an Initial Coin Offering (ICO) or a token presale?

This token was sold initially sold as a fair launch ICO on July 21st 2021 at 6PM UTC

> Is the token listed on a centralized/decentralized exchange?

We are currently traded on PancakeSwap, FTX, and in the process of listing on several other centralized exchanges too

> Is a Smart Contract audit completed? Where can we find this information?

We have had several successful third party audits completed. You can find them here: https://dexira.com/audits/

**Comment by cryptomanz** [comment]
As per our policy, brand new tokens are not included, there is a minimum requirement of 5000 holder addresses and 10000 transactions, in order to filter out scam tokens.
See the criteria at (mentioned in the first message by the bot): https://community.trustwallet.com/t/how-to-submit-a-token-logo/3863).

**Comment by dexIRA** [comment]
### Update from the dexIRA team:

We have doubled our holders since last speaking and were published in the news on both [**Yahoo News**](https://sg.news.yahoo.com/dexira-dex-first-multi-currency-074312546.html) and [**MarketWatch**](https://www.marketwatch.com/press-release/dexira-dex-the-first-multi-currency-reward-token-that-promotes-long-term-investment-2021-09-02). 

Furthermore, dexIRA has also passed several new audits available online [here](https://dexira.com/audits/), and we have been approved and added to [FTX/Blockfolio](https://www.youtube.com/watch?v=ji1cBCNkjT4) so we would like to maintain our current trajectory. All other pertinent information regarding DEX can be found on our website at [dexIRA.com](https://www.dexIRA.com).

> @cryptomanz As per our policy, brand new tokens are not included, there is a minimum requirement of 5000 holder addresses and 10000 transactions, in order to filter out scam tokens.

Per our conversations via email and Telegram, we kindly ask that you review and merge our pull request slightly below the required holders limit. DEX is a long term project with a very active Telegram community, so we refuse to use any bots or airdrops, and strive to maintain trust within our community.

Please let us know if you have any questions or concerns.

Thank you

**Pull request merged**
