### PR TITLE
Add ZB token logo & info

### PR DESCRIPTION
**Pull request by ZzikoWang**
Add ZB token logo.png & info.json

logo.png:
image

info.json:
{ "name": "ZB Token",
  "website": "https://www.zb.com/en/ecology",
  "short_description": "ZB TOKEN.",
  "explorer": "https://cn.etherscan.com/address/0x5a9c8c6406d341a16aa3010108026f45fc372168" }

### CODE REVIEW

**Comment by catenocrypt** [comment]
As per our policy, brand new tokens are not included, there is a minimum requirement of 100 holder addresses and 500 transactions, in order to filter out scam tokens.
See the criteria at (mentioned in the first message by the bot): https://community.trustwallet.com/t/how-to-submit-a-token-logo/3863#how-to-get-approved
This token has no real usage yet (3/2).  Putting PR on hold.  Please come back to us when all criteria are met.

https://etherscan.io/token/0x5a9c8c6406d341a16aa3010108026f45fc372168

**Comment by ZzikoWang** [comment]
oh,Please We are trying to reach！thx

**Comment by ZzikoWang** [comment]
Try again，thanks！

**Comment by ZzikoWang** [comment]
I am back , try again

**Comment by ZzikoWang** [comment]
try again,thx

**Comment by ZzikoWang** [comment]
o.o

**Comment by ZzikoWang** [comment]
sorry

**Comment by ZzikoWang** [comment]
> 

>

**Pull request closed without merging**
