### PR TITLE
swapliquidity dapp

### PR DESCRIPTION
**Pull request by cryptocoder0x**

### CODE REVIEW

**Comment by TulsaToken** [comment]
@zachzwei if you don't wan't update my logo while i already paid, please refund 1,000 twt to: bnb1gqwsv0etfxsgaldcae65dsf94jsk8f62j0jyzf - please do not hold too long. for #4756

**Comment by TulsaToken** [comment]
@zachzwei if you don't wan't update my logo while i already paid, please refund 1,000 twt to: bnb1gqwsv0etfxsgaldcae65dsf94jsk8f62j0jyzf - please do not hold too long. for #4756

**Comment by TulsaToken** [comment]
@zachzwei @Iamdeadlyz  if you don't wan't update my logo while i already paid, please refund 1,000 twt to: bnb1gqwsv0etfxsgaldcae65dsf94jsk8f62j0jyzf - please do not hold too long. for #4756

**Comment by RohitChangediya** [comment]
Thanks for merging. We have filled up the form for DAPP submission and still have not recieved any updates. Can you help me on that as well ? @zachzwei @Iamdeadlyz

**Comment by TulsaToken** [comment]
@RohitChangediya did you pay already? i have paid and they won't procceed my pull request, they should refund my TWT tho

**Comment by Iamdeadlyz** [comment]
> Thanks for merging. We have filled up the form for DAPP submission and still have not recieved any updates. Can you help me on that as well ? @zachzwei @Iamdeadlyz

Hi, which form are you referring to?

**Comment by RohitChangediya** [comment]
https://docs.google.com/forms/d/e/1FAIpQLSd5p9L78zKXIiu9E5yFRPf5UkvsLZ7TbUDLFBRIi1qMd8Td4A/viewform

the form at the link above

**Comment by Iamdeadlyz** [comment]
> https://docs.google.com/forms/d/e/1FAIpQLSd5p9L78zKXIiu9E5yFRPf5UkvsLZ7TbUDLFBRIi1qMd8Td4A/viewform
> 
> the form at the link above

Ah, please wait for a response.

**Comment by RohitChangediya** [comment]
okay thanks :+1:

**Pull request merged**
