### PR TITLE
Update info.json

### PR DESCRIPTION
**Pull request by BloomieBTC**
This PR is being closed due to inactivity. If you wish to continue, please have us reopen the PR before sending your payment.
Do NOT send payments for closed PR, as the fee may by lost!
  (60 vs. 60 hrs)

### CODE REVIEW

**Comment by catenocrypt** [comment]
I have moved the asset to new folder, corresponding to new contract.  Checks are OK now.
As we are at it, could you please fill in the `description` field in the `info.json`?  It is not just a placeholder `-`.

**Comment by BloomieBTC** [comment]
@catenocrypt Hi Adam, do your changes include renaming the old token to EncrypGen (old) and removing the icon and creating a new token?

**Review by BloomieBTC — COMMENTED** [review]
@catenocrypt Hi Adam, we need the deprecated token (0x82b0E50478eeaFde392D45D1259Ed1071B6fDa81) to stay in the database and renamed to "EncrypGen (old)" with no icon and a new json file created for the replacement token (0xef6344de1fcfC5F48c30234C16c1389e8CdC572C) with an icon.

**Comment by catenocrypt** [comment]
Logo+info for old token (0x82b0E50478eeaFde392D45D1259Ed1071B6fDa81) is removed in this PR.  The PR got closed in the meantime, can be reopened if requested.

**Comment by catenocrypt** [comment]
We cannot have token info without logo.  We can keep the old one but add it to the denylist, so it won't show up in token search (but existing owner will continue to see it).

**Comment by BloomieBTC** [comment]
We need the old contract to be clearly shown as deprecated on Uniswap (which sources TrustWallet's database) and preferably not show an icon to prevent user confusion.  Is there a way to do that?

**Comment by BloomieBTC** [comment]
@catenocrypt Hi Adam, can you please reopen this PR and reverse the deletion of the old token?  We are going to make a separate logo for it.  Can you please tell me the preferred specifications for the logo and maximum length for the description field?

**Comment by catenocrypt** [comment]
We (Trust Wallet) have no control over what tokens are shown in Uniswap.  There are many more tokens supported by Trust Wallet than by Uniswap.  I recommend contacting Uniswap about this.

**Comment by BloomieBTC** [comment]
@catenocrypt I understand all this, please reverse the deletion of the old token reopen the PR so we can fix all the issues, and if you could answer my questions above, that would be great:   
Can you please tell me the preferred specifications for the logo and maximum length for the description field?

**Pull request closed without merging**
