### PR TITLE
Adding DISC logo and info

### PR DESCRIPTION
**Pull request by deniagus1991**
Dear Trust Wallet Team,

Kindly please add our logo and info into your app, so our DisCas token holder able to see the logo and amount in USD or their currency. Thank you.

### CODE REVIEW

**Comment by Cryptocool1** [comment]
As per our policy, brand new tokens are not included, there is a minimum requirement of 2500 holder addresses and 5000 transactions, in order to filter out scam tokens.
See the criteria at (mentioned in the first message by the bot): https://community.trustwallet.com/t/how-to-submit-a-token-logo/3863).

**Comment by deniagus1991** [comment]
Dear Trust Wallet Team,

Currently we have 833 holders and 4000+ transaction, please granted DISC to add the logo.
We can guarantee that we are not scam and have real use case project, kindly please review our website https://discas.vision we put all of the team linkedin and instagram, we also show our face to all member in telegram group https://t.me/discasvision (global) https://t.me/discasvision_id (indonesia)

there are also some youtuber already reviewed and recommend our project:
https://www.youtube.com/watch?v=DkIVAPcShmc (Crypto Pablo)
https://www.youtube.com/watch?v=WAx7egmiVdE&t=158s (Czerwony Tygrys)
https://www.youtube.com/watch?v=Nxckx7KAeHI&t=797s (Padang Tekno)
and more soon.. 

Please granted our logo to easier our investor check the price. Thank you so much for the cooperation.

Best Regards,
Deni Agus
+6285313614576 (WhatsApp)

**Comment by deniagus1991** [comment]
Dear Trust Wallet Team,

Kindly please explain why our logo pending accepted. Appreciate your immediate reply. Thank you.

**Comment by deniagus1991** [comment]
Dear Adam, we are working on it for hours but we can't moved the file. We don't understand. Please.

Everyone pushes us to put our logo very soon. Anyone can help?

**Comment by catenocrypt** [comment]
If you can't rename files in the PR, you may open a new PR.  Make sure to mention this PR, so that we can see that fee has been paid already here.

**Comment by Cryptocool1** [comment]
PR should include only 2 files:

blockchains/smartchain/assets/0x2BCDCf1ef1320Fc5F9a71CA0BD1504D6125F7569/info.json
blockchains/smartchain/assets/0x2BCDCf1ef1320Fc5F9a71CA0BD1504D6125F7569/logo.png

**Comment by deniagus1991** [comment]
Hi, kindly please review again my new PR https://github.com/deniagus1991/assets/pull/1
I hope this time will be successful. Thank you.


[0x2BCDCf1ef1320Fc5F9a71CA0BD1504D6125F7569 2.zip](https://github.com/trustwallet/assets/files/6527469/0x2BCDCf1ef1320Fc5F9a71CA0BD1504D6125F7569.2.zip)

**Comment by deniagus1991** [comment]
Hi, kindly please review again my new PR https://github.com/deniagus1991/assets/pull/1
I hope this time will be successful. Thank you.

**Comment by deniagus1991** [comment]
Hi, kindly please review again my new PR https://github.com/deniagus1991/assets/pull/1
I hope this time will be successful. Thank you.

**Comment by deniagus1991** [comment]
Dear TW Team,

Kindly please check this new PR https://github.com/trustwallet/assets/pull/11076
We already have more than 2500 holders. Kindly please grant the logo in TW. Thank you for your cooperation.

**Comment by deniagus1991** [comment]
Dear Trust Wallet Team,Kindly please review my request. I really really need your help. Thank you so much.https://github.com/trustwallet/assets/pull/6887https://github.com/trustwallet/assets/pull/11076Best regards,DeniOn 5/5/21, 8:12 PM Adam R ***@***.***> wrote:

If you can't rename files in the PR, you may open a new PR.  Make sure to mention this PR, so that we can see that fee has been paid already here.

—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or unsubscribe.
[
{
***@***.***": "http://schema.org",
***@***.***": "EmailMessage",
"potentialAction": {
***@***.***": "ViewAction",
"target": "https://github.com/trustwallet/assets/pull/6887#issuecomment-832675789",
"url": "https://github.com/trustwallet/assets/pull/6887#issuecomment-832675789",
"name": "View Pull Request"
},
"description": "View this Pull Request on GitHub",
"publisher": {
***@***.***": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Pull request closed without merging**
