### PR TITLE
Add json for ERC20(ERC20) on Smart Chain for  #5935

### PR DESCRIPTION
**Pull request by TokenERC20**
please add info json to ERC20(ERC20) token on Smart Chain

### CODE REVIEW

**Comment by TokenERC20** [comment]
#5935

**Comment by catenocrypt** [comment]
Payment to be considered from #5935 .

**Comment by catenocrypt** [comment]
Correction needed: the info file is in the right folder, but logo file is missing.  File `logo.png`should be next to info.json, in the same folder.

**Comment by catenocrypt** [comment]
https://bscscan.com/token/0x58730ae0FAA10d73b0cDdb5e7b87C3594f7a20CB
https://etherscan.io/token/0xc3761eb917cd790b30dad99f6cc5b4ff93c4f9ea

**Comment by catenocrypt** [comment]
Added logo file (from #5979).

**Pull request merged**
