### PR TITLE
Add Offshift (XFT) (ERC20)

### PR DESCRIPTION
**Pull request by offshift-dev**
Adding info for ERC20 token 'Offshift (XFT)'.

PR created by <a href="https://assets.trustwallet.com">TW Assets Management</a>

### CODE REVIEW

**Comment by offshift-dev** [comment]
Making this PR due to a token swap from the original ERC-20 contract address to a new token/contract. 

Old XFT contract address: 0xABe580E7ee158dA464b51ee1a83Ac0289622e6be
New XFT Contract address: 0x76BC677d444f1E9d57dAf5187ee2b7dC852745aE

Swap announcement on blog: https://offshift.io/blog/2023-02-22-the-xft-token-swap-is-live/
Swap announcement on Twitter: https://twitter.com/OffshiftXFT/status/1628576594406084610

**Comment by Cryptocool1** [comment]
0xABe580E7ee158dA464b51ee1a83Ac0289622e6be
is this contract abandoned for now?

**Comment by offshift-dev** [comment]
> 0xABe580E7ee158dA464b51ee1a83Ac0289622e6be is this contract abandoned for now?

Tokens will continue to exist on this contract for some time, as there is no deadline for users to complete the token swap, but all markets, price feeds, cmc & gecko page, etc are either moved or in the process of being moved to the new contract.

**Comment by cryptomanz1** [comment]
we will put abandoned for your old contract and add new one.

**Comment by cryptomanz1** [comment]
#24144

**Pull request closed without merging**
