### PR TITLE
Add Wrapped Navcoin (wNAV)

### PR DESCRIPTION
**Pull request by aguycalled**

### CODE REVIEW

**Comment by catenocrypt** [comment]
As per our policy, brand new tokens are not included, there is a minimum requirement of 2500 holder addresses and 5000 transactions, in order to filter out scam tokens.
See the criteria at (mentioned in the first message by the bot): https://community.trustwallet.com/t/how-to-submit-a-token-logo/3863).
This token has no real usage yet (19 holders). Closing PR for now. Please come back to us when all criteria are met.  Multi-chain and staking tokens may get special treatment, let us know if this is the case. 

https://bscscan.com/token/0xBFEf6cCFC830D3BaCA4F6766a0d4AaA242Ca9F3D

**Comment by aguycalled** [comment]
WNAV is a wrapped version of Navcoin pegged 1 to 1. Binance already allows deposits of wNAV (BEP20) in their CEX.

You can check our block explorer https://navexplorer.com to check the current amount of addresses and transactions.

**Comment by aguycalled** [comment]
@zachzwei, @catenocrypt & @Iamdeadlyz: please review this pull request, wNAV is a wrapped token for Navcoin. Payment has already been done.

**Comment by catenocrypt** [comment]
Payment considered for #6559 .

**Comment by catenocrypt** [comment]
Low BEP20 circulation is accepted, as this is a wrapped version of native Navcoin.

**Pull request closed without merging**
