### PR TITLE
Added token information and logo for GMR v2

### PR DESCRIPTION
**Pull request by MarcIsCoding**
GMR v2 is the migrated token upgrade for what was previously GMR Finance (0x0523215dcafbf4e4aa92117d13c6985a3bef27d7).
For more info visit: https://gmr.center/news/gmr-v2-token-migration
https://twitter.com/GMRCenter

### CODE REVIEW

**Comment by Cryptocool1** [comment]
• What is the purpose of this token? How will it benefit Trust Wallet users?
 • How is the token being distributed? Are you conducting an airdrop?
 • Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?
 • Is the token listed on a centralized/decentralized exchange?
 • Is a Smart Contract audit completed? Where can we find this information?

**Comment by MarcIsCoding** [comment]
> 

Hey there,

First of all, I think it's best to provide some context. I am a developer at GMR (formally known as GMR Finance), we have recently initiated our v2 migration.

This means we are in the process of migrating up to 220,000 holders from GMR v1 (https://bscscan.com/address/0x0523215dcafbf4e4aa92117d13c6985a3bef27d7) to GMR v2 (https://bscscan.com/address/0xADCa52302e0a6c2d5D68EDCdB4Ac75DeB5466884).

GMR is a GameFi and social platform utility token. We've been in development for 7 months and have 20,000 members on our GMR Center (https://gmr.center). Which will see products such as a social network, with layered Web3 technology, an innovative gaming platform and NFT marketplace.

Users are currently migrating using our migration dApp (https://gmr.center/migration).

So to answer your questions, we did not airdrop and there was no ICO, our holders are migrating from v1 to v2, where we have redenominated the supply by 1,000,000: 1.

We are currently listed on ApeSwap (https://app.apeswap.finance/swap?outputCurrency=0xADCa52302e0a6c2d5D68EDCdB4Ac75DeB5466884) with almost $7,000,000 liquidity (paired GMR / BNB).

Adding our token will benefit Trust Wallet users as it will provide clarity that they are interacting with the correct contract. It may be worth pointing out that our Twitter account has over 76,000 followers (https://twitter.com/GMRCenter).

Our contract in the process of being audited by CertiK, you can find the onboarding page here: https://www.certik.com/projects/gamer

We expect the audit to be completed any day now. In the meantime, we have published a public repo containing the contract here: https://github.com/gmr-center/gmr-token-v2

I hope that helps.

**Comment by cryptomanz** [comment]
Awaiting for smart contract audit. On hold for now.

**Comment by MarcIsCoding** [comment]
> Awaiting for smart contract audit. On hold for now.

CertiK audit has been completed, please see here:

https://www.certik.com/projects/gamer

**Comment by Cryptocool1** [comment]
could you add the links?
see the example here: https://developer.trustwallet.com/assets/repository_details

**Comment by MarcIsCoding** [comment]
> could you add the links? see the example here: https://developer.trustwallet.com/assets/repository_details

Added links in the latest commit. Followed guidelines as per: https://developer.trustwallet.com/assets/repository_details

Seems to fail the merge-bot test? please advise.

**Comment by Cryptocool1** [comment]
you should delete www in the links

**Comment by MarcIsCoding** [comment]
> you should remove www from the links

Ah, of course, the test error says as much. Updating now.

**Pull request merged**
