### PR TITLE
Add RACA

### PR DESCRIPTION
**Pull request by RadiocacaDev**
Add RACA info and logo.

### CODE REVIEW

**Comment by Cryptocool1** [comment]
Hello, 
• What is the purpose of this token? How will it benefit Trust Wallet users?
 • How is the token being distributed? Are you conducting an airdrop?
 • Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?
 • Is the token listed on a centralized/decentralized exchange?
 • Is a Smart Contract audit completed? Where can we find this information?

**Comment by radiocaca** [comment]
Radio Caca is the exclusive manager of Maye Musk Mystery Box (MPB) NFT and DeFi+GameFi vehicle for The USM Metaverse. Maye Musk MPB has entered the NFTs' current top four "brands" and highest-valued NFT batches club (CryptoPunks, Hashmasks, Bored Ape Yacht Club, and Maye Musk Mystery Box).
RACA V1 was launched on May, and submitted pr #8137. Now we launch V2 version, and provide swap function on our website to help user swap RACA V1 to RACA V2.
Trust Wallet user can use pancakeswap DEX to trade RACA V2. And we will submit our farm function and NFT function to Trust Wallet DApp.
RACA V2 has already been distributed. Most of RACA V2 in user wallet. We have no plan to do some airdrop. 
We did not do a ICO, nor a presale.

**Comment by Cryptocool1** [comment]
can you please add links to your PR?
example: https://developer.trustwallet.com/add_new_asset/repository_details

**Comment by radiocaca** [comment]
> can you please add links to your PR?
> example: https://developer.trustwallet.com/add_new_asset/repository_details

"links": [
    {
        "name": "github",
        "url": "https://github.com/radiocaca/radio-caca"
    },
    {
        "name": "twitter",
        "url": "https://twitter.com/RadioCacaNFT"
    },
    {
        "name": "medium",
        "url": "https://radiocaca.medium.com/"
    },
    {
    	"name": "telegram",
    	"url": "https://t.me/RadioCaca"
    },
    {
    	"name": "audit",
    	"url": "https://www.certik.org/projects/radiocaca"
    }
]


is Ok ?

**Pull request merged**
