### PR TITLE
Pls add BHC logo

### PR DESCRIPTION
**Pull request by BHCHappiness**
BHC
I use erc20 before Im already in Trust Wallet my symbol (BHT) BillionHappiness
due to high fees concern now Im using BEP8 my symbol is (BHC) BillionHappiness

### CODE REVIEW

**Comment by billyeun** [comment]
twt

**Comment by billyeun** [comment]
@zachzwei  Hi sir Andrew its me again :) can you help me add my new token BEP8 to trust wallet?

**Comment by billyeun** [comment]
Asset Name:
BHC-3E8M
Owner:
bnb1y55q60w35hrexkl2sh2avl6xrzx6att3r0t588
Supply:
1,000,000

**Comment by billyeun** [comment]
can we delete or removed the old BillionHappiness in the trust wallet? (ERC20)

**Comment by zachzwei** [comment]
> can we delete or removed the old BillionHappiness in the trust wallet? (ERC20)

what is the contract address of the ERC20 token?

**Comment by billyeun** [comment]
0x32e3298939D56D0bb0dA5BD20dE8b589FF5e1B57

thats the contract address po

Thank you

**Comment by billyeun** [comment]
Let me know if you need more info.
Salamat

**Comment by billyeun** [comment]
@zachzwei Sir, how long it takes to be merge? :)

**Comment by catenocrypt** [comment]
The problem is that the added asset (BHC-3E8M) does not exist on Binance chain as a BEP2 token.  BEP8 is not yet supported.
See existing tokens at  https://dex.binance.org/api/v1/tokens?limit=1000

**Comment by billyeun** [comment]
@catenocrypt ohh, so what should I do? wait for it to be available Trust twitter accounts says they are supported BEP8 tokens

**Comment by catenocrypt** [comment]
@billyeun , can you confirm that your token is _already_ existing as a BEP8 token on the Binance chain?  Maybe you can help me with a link to explorer page, etc.

**Comment by billyeun** [comment]
@catenocrypt yes that one :) 

Asset Name:
BHC-3E8M
Owner:
bnb1y55q60w35hrexkl2sh2avl6xrzx6att3r0t588
Supply:
1,000,000

**Comment by billyeun** [comment]
@catenocrypt we can find way? so that I can view it in Trust Wallet?
Thank you

**Comment by catenocrypt** [comment]
@billyeun , please be patient with us.  We are adding BEP8 minitoken support to the assets repo infrastructure, and to Trust Wallet.  Can we use BHC token for testing?

**Comment by billyeun** [comment]
@catenocrypt Yes! :) we can use BHC so that Im the 1st BEP8 in trust wallet and my community love the TrustWallet.

**Comment by billyeun** [comment]
Also Im promoting Trust wallet in my website check it here: https://billionhappiness.com/pages/claim-rewards

**Comment by billyeun** [comment]
what next? :) we can view it soon in Trust Wallet?

**Comment by billyeun** [comment]
I have question, the price of BHC (BEP8) will also be shown on the Trust Wallet app same with Binance DEX price? Thank you

**Comment by catenocrypt** [comment]
I have merged, BHC minitoken now is in the `assets` repo.  In a few hours (cache recycling) it will probably appear in Trust Wallet.  However, showing of balance and making transfers may not work yet!
Could you reach out to me on Telegram (@catenocrypt), to talk directly?

**Comment by billyeun** [comment]
Sure, @catenocrypt  I will send a DM, Thank you for being kind. 👍

**Comment by billyeun** [comment]
@zachzwei @catenocrypt Hello, BHC still not in trust wallet asset I try to search it only BHT the old one, Its been 2 days i think since BHC minitoken assets repo.

**Comment by catenocrypt** [comment]
Sorry, this may take some more time.
Trust Wallet team is sstill waiting for some spam-control tools from Binance Chain, before BEP8 is integrated.

**Comment by billyeun** [comment]
Okay I will just wait, Please just tell me if what I can help.

**Comment by billyeun** [comment]
@catenocrypt @zachzwei  hello what is the update of my BHC merge to BHT i saw in trust wallet still the erc20 live not the binance chain BIP8

**Comment by billyeun** [comment]
please reply I also created Binance Smart Chain network maybe its fast if you can add this https://bscscan.com/token/0xa6381c6fd8f40a44721ef4f61edc1a8ccca7bf3d

**Comment by billyeun** [comment]
contract : 0xa6381c6fd8f40a44721ef4f61edc1a8ccca7bf3d

**Comment by billyeun** [comment]
BHT to BHC


please add the logo to BHC (bep20) Binance Smart Chain network

contract : 0xa6381c6fd8f40a44721ef4f61edc1a8ccca7bf3d

**Comment by catenocrypt** [comment]
Done, with #4131 .  Please check.

**Comment by billyeun** [comment]
I will check it after 24hrs 👍 the logo will show up for sure right?

anyway thank you @catenocrypt very kind

**Pull request merged**
