### PR TITLE
AFA Virtual Coin Token

### PR DESCRIPTION
**Pull request by echapeta**

### CODE REVIEW

**Comment by echapeta** [comment]
Hello, 
I just sent 0.08 ETH to 0xB46224E545c3F1Fa4D05f94465D13f777866a77B , at the transaction:

https://etherscan.io/tx/0x898f7c51b3ae57a3ab4113f7754c91f53755271dd027f3531ab12c00b90689a2

Please commit the logo update.

Thank You

**Comment by kolya182** [comment]
@echapeta Token already added, try search and you will see it.

**Comment by zachzwei** [comment]
@kolya182 I have verified this with the user. This is for a different asset and has also paid the fee.

**Comment by echapeta** [comment]
Thank You!

 

 

 

Eduardo G. Chapeta

CEO

Interwave Global

www.iw-global.com

**Comment by echapeta** [comment]
Now is solved, thank you!

 

 

 

Eduardo G. Chapeta

CEO

Interwave Global

www.iw-global.com

**Pull request closed without merging**
