### PR TITLE
Add Nadeshiko (BEP20)

### PR DESCRIPTION
**Pull request by ghost**
Adding info for BEP20 token 'Nadeshiko'.

PR created by <a href="https://assets.trustwallet.com">TW Assets Management</a>

### CODE REVIEW

**Comment by Nadeshikocoin** [comment]
#6532で支払い済みです

**Comment by Cryptocool1** [comment]
As per our policy, brand new tokens are not included, there is a minimum requirement of 2500 holder addresses and 5000 transactions, in order to filter out scam tokens.
See the criteria at (mentioned in the first message by the bot): https://community.trustwallet.com/t/how-to-submit-a-token-logo/3863).
Closing PR for now. Please reopen PR when all criteria are met.

**Comment by Nadeshikocoin** [comment]
基準を満たしました。
よろしくお願い致します

**Comment by Nadeshikocoin** [comment]
The conditions have been met.
Should I make a new request again?

2021年5月7日(金) 0:12 CryptoA ***@***.***>:

**Pull request closed without merging**
