### PR TITLE
Add Galaxy Sphere logo and info

### PR DESCRIPTION
**Pull request by Galaxysphere**
update Token Logo and Info

### CODE REVIEW

**Comment by Cryptocool1** [comment]
can you please delete this file ? "blockchains/smartchain/assets/info.json"

**Comment by Cryptocool1** [comment]
can you please add links to your PR?
example: https://developer.trustwallet.com/add_new_asset#info-json-contents

**Comment by Galaxysphere** [comment]
hey there i deleted the wrong info.json upload and edited the info.json to add link let me know if any other action is required

**Comment by Cryptocool1** [comment]
could you please answer some question?
• What is the purpose of this token? How will it benefit Trust Wallet users?
 • How is the token being distributed? Are you conducting an airdrop?
 • Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?
 • Is the token listed on a centralized/decentralized exchange?
 • Is a Smart Contract audit completed? Where can we find this information?

**Comment by Galaxysphere** [comment]
could you please answer some question?
• What is the purpose of this token? How will it benefit Trust Wallet users?
Our Purpose of  the token is to create a new Decentralized finance platform . In the future our token holder will be able to participate in yield farming as a provider of liquidity pool. As a DeFi finance supporter trust wallet user will be able to participate using simple Dapps browser
• How is the token being distributed? Are you conducting an airdrop?
Token is distributed from presale
• Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?
Token is sold on presale
• Is the token listed on a centralized/decentralized exchange?
token is now listed on pancakeswap
• Is a Smart Contract audit completed? Where can we find this information?
no we has not completed any smart contract audit yet right now but it could come in the near future

**Comment by Cryptocool1** [comment]
awaiting for listing on cmc or smart contract audit. on hold for now

**Comment by Cryptocool1** [comment]
please create new PR when your token will be listed on CMC
make sure to mention this PR so that fee can can be reused

**Pull request closed without merging**
