### PR TITLE
Dynamic Set Token.

### PR DESCRIPTION
**Pull request by PatrickDehkordi**
Altough DSD is showing 1949 unique holders,
https://bloxy.info/token_holders/0xbd2f0cd039e0bfcf88901c98c0bfac5ab27566e3
Many of the users are "bonded" in the DAO and are being counted as a single address in DSD. They can be divided by their DSDS holdings, which is 891 unique users:
https://bloxy.info/token_holders/0x6bf977ed1a09214e6209f4ea5f525261f1a2690a
Although there is some overlap between DSD and DSDS unique addresses, most of these addresses are unique users in addition to DSD users.

### CODE REVIEW

**Comment by PatrickDehkordi** [comment]
Commenting to prevent the PR from auto closing due to inactivity, as the project sorts out the processing payment. Please keep open. Thanks.

**Comment by catenocrypt** [comment]
Do not worry about auto-closing, if that happens, you can request reopen any time.

**Comment by catenocrypt** [comment]
Please change the logo to a higher resolution, this is 100x100 pixels, recommended is 256x256 px.

**Comment by PatrickDehkordi** [comment]
okay updated the logo to higher res 250x250. Thanks!

**Comment by PatrickDehkordi** [comment]
Any update on when we can get this processed?

**Pull request merged**
