### PR TITLE
Added EXG (exchain.ai exchain global) Token

### PR DESCRIPTION
**Pull request by egvnblockchain**
Upload EXG Token logo + info.json

### CODE REVIEW

**Comment by egvnblockchain** [comment]
I have paid, what should I do next?

**Comment by egvnblockchain** [comment]
Hello Iamdeadlyz, can you tell me what is "Status: On Hold"? tks.

**Comment by Iamdeadlyz** [comment]
> Hello Iamdeadlyz, can you tell me what is "Status: On Hold"? tks.

Your PR is under review.

**Comment by egvnblockchain** [comment]
Hi Iamdeadlyz, how long my PR can merge?

**Comment by Iamdeadlyz** [comment]
In accordance with our [disclaimer](https://github.com/trustwallet/assets#disclaimer), your PR is denied due to the following reason:
- Fake partnerships with the intent to mislead users
image
image
image

- Copy pasted information with the intent to mislead users
image
image
image

**Pull request closed without merging**
