### PR TITLE
add ORK

### PR DESCRIPTION
**Pull request by 0xtoj**

### CODE REVIEW

**Comment by catenocrypt** [comment]
Corrections needed:
- This is a BEP20 (BSC) token, its location should be `blockchains/smartchain/assets` (binance folder is for BEP2 tokens, Binance chain).
- The `type` field in info.json should be `BEP20` (not COIN).

**Comment by iamtoj** [comment]
@catenocrypt fixed. thanks for the review!

**Comment by iamtoj** [comment]
Hi @catenocrypt. Would it be possible to use this logo.png instead? Sorry for the late notice but we find out the one we submitted looks quite bad on the UI. 

logo

**Comment by 0xtoj** [comment]
@catenocrypt Following up about that, I can't find the current logo on the master. What would be the right thing to do here?

**Comment by catenocrypt** [comment]
This is the merged logo on master:

https://github.com/trustwallet/assets/blob/master/blockchains/smartchain/assets/0xCed0CE92F4bdC3c2201E255FAF12f05cf8206dA8/logo.png

**Comment by 0xtoj** [comment]
@catenocrypt thanks! had to re-fork. For some reasons I wasn't seeing it

I opened #6684, should we still pay the fees or would it be possible to merge it?

**Pull request merged**
