### PR TITLE
Replaced logo of Kishimoto due to Rebranding

### PR DESCRIPTION
**Pull request by CryptoWebDev1**
We rebranded and changed our logo

https://kishimotoinu.com is now redirecting to https://kishimototoken.com

### CODE REVIEW

**Comment by CryptoWebDev1** [comment]
katsumi is the dao token of kishimoto which is just being added in the same PR

**Comment by CryptoWebDev1** [comment]
@cryptomanz let me know if there is some issue will try to fix it asap

**Comment by Cryptocool1** [comment]
Please create new PR, follow doc https://developer.trustwallet.com/assets/requirements
You may want to try our Assets app in beta; go to https://assets.trustwallet.com, log on with Github, enter contract ID, logo and some additional info, and it will create a PR for you.
See https://developer.trustwallet.com/assets/repository_details

**Comment by DNAOFFICIALL** [comment]
Not active

**Comment by DNAOFFICIALL** [comment]
Not active

**Pull request closed without merging**
