### PR TITLE
Add HoneyMoon (BEP20)

### PR DESCRIPTION
**Pull request by HoneyFarmFi**
Adding info for BEP20 token 'HoneyMoon'.

PR created by <a href="https://assets.trustwallet.com">TW Assets Management</a>

### CODE REVIEW

**Comment by cryptomanz** [comment]
As per our policy, brand new tokens are not included, there is a minimum requirement of 5000 holder addresses and 10000 transactions, in order to filter out scam tokens.
See the criteria at (mentioned in the first message by the bot): https://community.trustwallet.com/t/how-to-submit-a-token-logo/3863).
Closing PR for now. Please come back to us when all criteria are met.

**Comment by HoneyFarmFi** [comment]
and actually, I already sent the payment.
Is there any way to revive this pull request and continue checking for register?

It's the era of DeFi so please take consideration for the nature of it.

**Comment by HoneyFarmFi** [comment]
> As per our policy, brand new tokens are not included, there is a minimum requirement of 5000 holder addresses and 10000 transactions, in order to filter out scam tokens.
> See the criteria at (mentioned in the first message by the bot): https://community.trustwallet.com/t/how-to-submit-a-token-logo/3863).
> Closing PR for now. Please come back to us when all criteria are met.

@cryptomanz 
Please check my comment!

@Cryptocool1 @zachzwei @catenocrypt
Hello guys,

It would be greatly appreciated if you can help me for this situation!
We've gone through it several times together, friends!

**Comment by HoneyFarmFi** [comment]
> > As per our policy, brand new tokens are not included, there is a minimum requirement of 5000 holder addresses and 10000 transactions, in order to filter out scam tokens.
> > See the criteria at (mentioned in the first message by the bot): https://community.trustwallet.com/t/how-to-submit-a-token-logo/3863).
> > Closing PR for now. Please come back to us when all criteria are met.
> 
> @cryptomanz
> Please check my comment!
> 
> @Cryptocool1 @zachzwei @catenocrypt
> Hello guys,
> 
> It would be greatly appreciated if you can help me for this situation!
> We've gone through it several times together, friends!

My payment TxID is, CF48D69808CBED2CF21D3347B141EB484D6051D2FB2B6C54507A533EC4D7853A

**Comment by HoneyFarmFi** [comment]
@Cryptocool1 
Thanks so much!

**Pull request merged**
