### PR TITLE
Add BankRoll Logo | TrustWallet

### PR DESCRIPTION
**Pull request by Kofro**
BankRoll is the first and only Escrow Marketplace on the Binance Smart Chain.
BSCScan verified and has created our own category: https://bscscan.com/tokens/label/escrow
We were listed on CG and CMC within 24 hours of applying.

Payment will be made upon confirmation.

### CODE REVIEW

**Comment by Kofro** [comment]
BankRoll is the first and only Escrow Marketplace on the Binance Smart Chain.
BSCScan verified and has created our own category: https://bscscan.com/tokens/label/escrow
We were listed on CG and CMC within 24 hours of applying.
https://www.coingecko.com/en/coins/bankroll
https://coinmarketcap.com/currencies/bankroll/

Payment will be made upon confirmation.

**Comment by JackFrancis-Crypto** [comment]
Bankroll has done nothing but meet every expectation they have set for the community.

The development and tenacity of the team has been relentless and non-stop.  I have not encountered a more sophisticated and legitimate project on the Binance Network before this.  They 100% deserve to have a Logo on Trust Wallet.

**Comment by Cryptocool1** [comment]
As per our policy, brand new tokens are not included, there is a minimum requirement of 5000 holder addresses and 10000 transactions, in order to filter out scam tokens.
See the criteria at (mentioned in the first message by the bot): https://community.trustwallet.com/t/how-to-submit-a-token-logo/3863).
Closing PR for now. Please come back to us when all criteria are met.

**Comment by Kofro** [comment]
> As per our policy, brand new tokens are not included, there is a minimum requirement of 5000 holder addresses and 10000 transactions, in order to filter out scam tokens.
> See the criteria at (mentioned in the first message by the bot): https://community.trustwallet.com/t/how-to-submit-a-token-logo/3863).
> Closing PR for now. Please come back to us when all criteria are met.



> I know we are below the new 5000 holder limit, but I believe BankRoll should be considered based on merit.

???

**Comment by Kofro** [comment]
We're not a brand new token. We were approved on bogged.finance on the 20th of July.

https://github.com/BogTools/Bogged-Token-List/pull/227/commits/b94f25badc2efe2d51b4b7bc058bc623fd304eb3

**Pull request closed without merging**
