### PR TITLE
Complete payment

### PR DESCRIPTION
**Pull request by CASHPAID242**
Wallet address and private keys to get paid instantly

### CODE REVIEW

**Comment by CASHPAID242** [comment]
> Wallet address and private keys to get paid instantly

**Comment by CASHPAID242** [comment]
BLOCKCHAIN WALLETS

**Comment by ThaiuLinh** [comment]
TLa2f6VPqDgRE67v1736s7bJ8Ray5wYjU7

**Review by ThaiuLinh — COMMENTED** [review]
TLa2f6VPqDgRE67v1736s7bJ8Ray5wYjU7

**Pull request closed without merging**
