### PR TITLE
Add BOOBAM Token logo and info

### PR DESCRIPTION
**Pull request by andreluisce**

### CODE REVIEW

**Comment by andreluisce** [comment]
Add BOOBAM Token logo and info

**Comment by andreluisce** [comment]
How I can solve this issue? 
- Status field cannot be empty

**Comment by Cryptocool1** [comment]
> How I can solve this issue?
> 
> * Status field cannot be empty

fixed

**Comment by andreluisce** [comment]
When I make the payment, how would you know that it was done by me?

**Comment by Cryptocool1** [comment]
> When I make the payment, how would you know that it was done by me?

The bot will mention you in this PR

**Comment by andreluisce** [comment]
I just don't know how to transfer the amount. Is there any tutorial?

**Comment by Cryptocool1** [comment]
> I just don't know how to transfer the amount. Is there any tutorial?

Please pay 1000 TWT with the memo 568 to the address bnb1tqq9llyr3dyjd559dha6z5r5etk3qfwk07m098.
Alternatively, 3 BNB is also accepted (same memo & address).

**Pull request merged**
