### PR TITLE
Add Tamadoge (TAMA) (ERC20)

### PR DESCRIPTION
**Pull request by TRBlockmedialabs**
Adding info for ERC20 token 'Tamadoge (TAMA)'.

PR created by <a href="https://assets.trustwallet.com">TW Assets Management</a>

### CODE REVIEW

**Comment by TRBlockmedialabs** [comment]
Please confirm BNB wallet address for PR Fee

**Comment by Cryptocool1** [comment]
Hello, how did you get more than 20k holders in 5days?

**Comment by TRBlockmedialabs** [comment]
> Hello, how did you get more than 20k holders in 5days?

Hi - We had a presale and also listed on OKx early

**Comment by Cryptocool1** [comment]
• What is the purpose of this token? How will it benefit Trust Wallet users?
 • How is the token being distributed? Are you conducting an airdrop?
 • Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?
 • Is the token listed on a centralized/decentralized exchange?
 • Is a Smart Contract audit completed? Where can we find this information?

**Comment by TRBlockmedialabs** [comment]
> • What is the purpose of this token? How will it benefit Trust Wallet users?
> Its purpose is to allow user to engage with products within the Tamaverse, first product releasing is a play-to-earn game
• How is the token being distributed? Are you conducting an airdrop?
> No airdrop - we conducted a pre-sale. And are listed on OKx with Lbank and MEXC listings coming soon. We also provided liquidity to Uniswap pairs
• Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?
> In a presale , yes
• Is the token listed on a centralized/decentralized exchange?
> Listed on Uniswap, OKx with Lbank and MEXC confirmed. 
• Is a Smart Contract audit completed? Where can we find this information?
>Solidproof Audit : https://tamadoge.io/wp-content/uploads/2022/07/SolidProof-TamaDoge.pdf
>Coinsniper KYC audit : https://coinsniper.net/coin/37091

**Pull request merged**
