### PR TITLE
Add Zoro Inu (BEP20)

### PR DESCRIPTION
**Pull request by zoroinu**
Adding info for BEP20 token 'Zoro Inu'.

PR created by <a href="https://assets.trustwallet.com">TW Assets Management</a>

### CODE REVIEW

**Comment by zoroinu** [comment]
Dear team,
We would like to send the holder and transfers information for you to check manually.
Please help me take a look.
Best regards !

**Comment by zoroinu** [comment]
+ Total Supply: 1,000,000,000,000,000 ZORO 
+ Holders: 17,738 addresses
+ Transfers: 80,917

**Comment by zoroinu** [comment]
Dear team,

Looking forward to your feedback.

Best regards !

**Comment by zoroinu** [comment]
Dear team, 

We have paid 5bnb for the logo, please check and proceed with your work.

Please check via TxID: DC7E50061101C8E371EE86CB3E9E1B1D1BA37381C6F5604A4A0976CB6137EBDA

Many thanks to your team.

Best regards !

**Comment by zoroinu** [comment]
Dear team,

We have yet to see the logo displayed on the trust wallet. Help us !

**Comment by Cryptocool1** [comment]
Should be within 1hour

**Comment by zoroinu** [comment]
Great, thanks .

**Pull request merged**
