### PR TITLE
add SAINT to trust wallet

### PR DESCRIPTION
**Pull request by rockstardotb**
Add SAINT logo to trust wallet (saint.finance)

### CODE REVIEW

**Comment by Cryptocool1** [comment]
corrections needed:
id field does not match contract, should be 0x503576189Edd9FEb058ad3f17f1E6e9172A11D75
 Logo image too large, max 100 kB, current 100.019 kB

**Comment by Cryptocool1** [comment]
incorrect id

**Comment by rockstardotb** [comment]
After the corrections are made, is another 2BNB needed in order to have this processed?

**Comment by Cryptocool1** [comment]
> After the corrections are made, is another 2BNB needed in order to have this processed?
> […](#)

no, you need to pay only 1 time. there is no need to pay one more time)

**Comment by rockstardotb** [comment]
But it will be a new pull request, correct?

**Comment by rockstardotb** [comment]
I see the merge failed due to conflicts. Do you need me to pull from your branch and resubmit?

**Pull request merged**
