### PR TITLE
Add Rewardable REWARD (ERC20)

### PR DESCRIPTION
**Pull request by artiffine-vojtech**
Token: REWARD
Name: Rewardable
Chain: Base
https://basescan.org/token/0x1986cc18d8ec757447254310d2604f85741aa732

Third-party audit: https://www.cyberscope.io/audits/2-reward

### CODE REVIEW

**Comment by Cryptocool1** [comment]
As per our policy, brand new tokens are not included, there is a minimum requirement of 10,000 holder addresses and 15,000 transactions, in order to filter out scam tokens.
See the criteria at : https://developer.trustwallet.com/assets/requirements .

**Comment by artiffine-vojtech** [comment]
Hi @Cryptocool1 yes, I am aware of this requirement. We do not want to inflate the number of holders and transactions by artificial transactions and airdrops, as many projects do, and we want to grow naturally. 

The REWARD token is the token anyone who registers and completes tasks on Rewardable platform can withdraw. There is more than 100k registered users on the platform (with verified emails, phones and under KYC), more than 10k completed tasks. They all hold off-chain balance of the token and will start withdrawing it. The token itself and the withdrawal process is audited by third-party provider CyberScope. If needed, I can share proof of these numbers in a private channel. 

Can we please reconsider this listing? Thanks!

**Comment by Cryptocool1** [comment]
Hello, 
• What is the purpose of this token? How will it benefit Trust Wallet users?
 • How is the token being distributed? Are you conducting an airdrop?
 • Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?
 • Is the token listed on a centralized/decentralized exchange?
 • Is a Smart Contract audit completed? Where can we find this information?

**Comment by artiffine-vojtech** [comment]
@Cryptocool1 here are the responses to your questions:

**What is the purpose of this token? How will it benefit Trust Wallet users?**
REWARD is the cornerstone of the whole Rewardable ecosystem. REWARD can be used inside our Task to earn platform, where you can launch tasks such as boosting your social media accounts, where you pay certain amount of REWARD and we connect you with more than 100k KYCed users who will be able to complete your task, for example following your profile, liking a tweet, retweeting a tweet and much much more this also works vice versa, people can complete tasks, earn Reward points which can be converted into REWARD tokens. Apart from that, people who hold REWARD can also Stake their tokens to earn significant yield + they can provide Liquidity and earn yield from that as well.

**How is the token being distributed? Are you conducting an airdrop?**
User can withdraw the tokens from the platform when they complete tasks and their submission is verified. The initial liquidity was deposited into a UniswapV3 pool and people were able to buy it. We did not conduct any airdrop.

 **Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?**
No.

**Is the token listed on a centralized/decentralized exchange?**
Listed on uniswap -> https://app.uniswap.org/explore/tokens/base/0x1986cc18d8ec757447254310d2604f85741aa732

**Is a Smart Contract audit completed? Where can we find this information?**
Yes, by cyberscope, visible here -> https://www.cyberscope.io/audits/2-reward

**Pull request closed without merging**
