### PR TITLE
Add Bitgear (GEAR)

### PR DESCRIPTION
**Pull request by SkyTradeInc**

### CODE REVIEW

**Comment by SkyTradeInc** [comment]
Please do not merge yet, contract address is wrong

**Comment by catenocrypt** [comment]
Do not override the file blockchains/ethereum/info/logo.png, that is a logo for the Eth chain itself!

**Comment by SkyTradeInc** [comment]
> Do not override the file blockchains/ethereum/info/logo.png, that is a logo for the Eth chain itself! Maybe best is to close this PR and create new one with correct files.

https://github.com/trustwallet/assets/pull/3273
Fixed PR, can you please close this one and move payment to above

**Comment by catenocrypt** [comment]
Closing, in favor of #3273 .

**Pull request closed without merging**
