### PR TITLE
Add Littlemoose (BEP20)

### PR DESCRIPTION
**Pull request by littlemooose**
Adding info for BEP20 token 'Littlemoose'.

PR created by <a href="https://assets.trustwallet.com">TW Assets Management</a>

### CODE REVIEW

**Comment by cryptomanz** [comment]
Hello,
- Submission looks good. awaiting fee payment.

**Comment by cryptomanz** [comment]
Hello,
- Submission looks good. awaiting fee payment.

**Comment by littlemooose** [comment]
Done paying sir! Thank you pls work in logo asap

**Comment by littlemooose** [comment]
How long doest it takes for the logo show up in trustwallet

**Comment by littlemooose** [comment]
Whats the requirements to apply the logo in trustwallet do i need 5
thousand holders or 2500 holder is fine

**Pull request merged**
