### PR TITLE
SafeBTC new logo

### PR DESCRIPTION
**Pull request by SAFEBTCOFFICIAL**
We have completed rebranding

### CODE REVIEW

**Comment by catenocrypt** [comment]
Correction needed:
❌ Logo image too large, max 100 kB, current 481.281 kB
❌ Logo should be 256x256 pixels, it is too large 856x849

**Comment by SAFEBTCOFFICIAL** [comment]
Reuploaded new logo in 250 x 250 as requested 

CoinGecko has also updated the logo as your requirement

**Comment by SAFEBTCOFFICIAL** [comment]
logo

**Comment by ashhbukhari** [comment]
Payment has been made and still no update?

**Comment by ashhbukhari** [comment]
What is going on guys

**Comment by SAFEBTCOFFICIAL** [comment]
Still no update?

**Comment by SAFEBTCOFFICIAL** [comment]
Hello;
  
  
   
  
  
   will price be updated along with market information as it comes up with not available
  
  
   
  
  
   You can check out BSC Scan and they have updated out price and logo aswell so hopefully everything should be a lot easier now to reflect the holdings value me of our holders
  
  
   
  
  
   Thank you
  
  
   
    On 04/12/2021 9:38 AM Adam R ***@***.***> wrote:
   
   
    
   
   
    
   
   
   Merged #6314 into master.

**Comment by SAFEBTCOFFICIAL** [comment]
Hello
  
  
   
  
  
   can we get price reflected on trustwallet for safeBTC please as we are close to 50,000 holders and our holders have no value on their wallets for their holding of our coin but it shows the value on BSCScan 
  
  
   
  
  
   can you please get this reflected asap as people are starting to switch over to SafePal wallet
  
  
   
  
  
   we have made a payment of 2 BNB and also 250 TWT aswell so please get this updated as it’s a question being asked atleast 10 times an hour in the chat!
  
  
   
  
  
   people are beginning to sell their holdings as they think price will never reflect on trustwallet 
  
  
   
  
  
   
  
  
   
    On 04/12/2021 9:38 AM Adam R ***@***.***> wrote:
   
   
    
   
   
    
   
   
   Merged #6314 into master.

**Comment by SAFEBTCOFFICIAL** [comment]
Any update on price?
  
  
   
    On 04/12/2021 9:38 AM Adam R ***@***.***> wrote:
   
   
    
   
   
    
   
   
   Merged #6314 into master.

**Comment by SAFEBTCOFFICIAL** [comment]
Hi guys We need our price reflecting for our token and information updating.

**Pull request merged**
