### PR TITLE
Add LOA Token (BEP20)

### PR DESCRIPTION
**Pull request by Abdul-LOA**
Adding info for BEP20 token 'LOA Token'.

PR created by <a href="https://assets.trustwallet.com">TW Assets Management</a>

### CODE REVIEW

**Comment by Cryptocool1** [comment]
• What is the purpose of this token? How will it benefit Trust Wallet users?
 • How is the token being distributed? Are you conducting an airdrop?
 • Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?
 • Is the token listed on a centralized/decentralized exchange?
 • Is a Smart Contract audit completed? Where can we find this information?

**Comment by Abdul-LOA** [comment]
1)LOA token is the main currency and utility token for our nft marketplace and LOA moba game. More users would be using trust wallet to connect to our marketplace and to store loa tokens.
2) tokens are distributed via token contract , they will use our dashboard to claim the tokens. For private sales, presales , launchpad
3) yes we sold 12% prior to ICO and tokens are claimed via [dashboard.leagueofancients.com](http://dashboard.leagueofancients.com/)
4)tokens are purchasable via Dex and CEX. We are listed on pcs , biswap, apeswap and gate.
5) https://league-of-ancients-v2.gitbook.io/whitepaper/tokenomics/audit

**Comment by Cryptocool1** [comment]
your logo should be full screen size, please change

**Comment by Abdul-LOA** [comment]
Logo Updated.

**Pull request merged**
