### PR TITLE
Adding TestToken

### PR DESCRIPTION
**Pull request by KingzRex**
Adding TestToken
in reference to the previous pull request which has been paid for in TWT
#16876

Adding TestToken #16876

### CODE REVIEW

**Comment by KingzRex** [comment]
Techrate Audit is ready!

**Comment by KingzRex** [comment]
Adding BNB Gold
in reference to the previous pull request which has been paid for in TWT
#16876
FEE PAID
Adding BNB Gold #16876

**Comment by cryptomanz** [comment]
can you send the audit here?

**Comment by KingzRex** [comment]
Fees have been paid in TWT

**Comment by KingzRex** [comment]
[BNB Gold Full Smart Contract Security Audit.pdf](https://github.com/trustwallet/assets/files/7797248/BNB.Gold.Full.Smart.Contract.Security.Audit.pdf)


https://github.com/TechRate/Smart-Contract-Audits/blob/main/December/BNB%20Gold%20Full%20Smart%20Contract%20Security%20Audit.pdf

**Comment by KingzRex** [comment]
Yes


https://github.com/TechRate/Smart-Contract-Audits/blob/main/December/BNB%20Gold%20Full%20Smart%20Contract%20Security%20Audit.pdf

[image: PDF file]
BNB Gold Full Smart Contract…
<https://drive.google.com/file/d/1nWRIBtEiBH6dDrrHgPTWgXCMY-ZFELmP/view?usp=drivesdk>

**Comment by KingzRex** [comment]
> can you send the audit here?

The audit has been sent

**Pull request merged**
