### PR TITLE
Add Atlas Staking to the Kava Validator list

### PR DESCRIPTION
**Pull request by EJK64**
I like to ad my validator to the Kava Validator list.
I have payed already for a closed PR #15386 Did not know it was closed with errors just before the payment.
TxID:
E7F3B6EF02A63DA1FDFA0B6F32777862FB8EE65BF1C3889576EE8BF9A57D69FF
Date:
2021-11-10

thanks!

### CODE REVIEW

**Comment by EJK64** [comment]
Is extra data expected from me?

**Comment by Cryptocool1** [comment]
can you delete this file please?
blockchains/kava/validators/assets/kavavaloper1ua2yqfjck23vsmynltcgrvvg5rhfkm4cy78vmq/.atlas

**Comment by EJK64** [comment]
File .atlas deleted

**Comment by EJK64** [comment]
Syntax fix for list.json 
Block repeating comma was missing. Corrected

**Pull request merged**
