### PR TITLE
Add Sologenic (BEP20)

### PR DESCRIPTION
**Pull request by AlOaks**
Adding info for BEP20 token 'Sologenic'.

PR created by <a href="https://assets.trustwallet.com">TW Assets Management</a>

### CODE REVIEW

**Comment by AlOaks** [comment]
Hi

The number of token holders on the BSC is less than 10,000

It's because Sologenic is a multi-chain token with +300K holders on the XRP Ledger.

The bridge between the XRP Ledger and BSC has been recently created, which in turn increases the number of holders on Binance Smart Chain. In addition, users on Binance hold approximately 10% of the total supply of the token.

**Comment by cryptomanz** [comment]
As per our policy, brand new tokens are not included, there is a minimum requirement of 10,000 holder addresses and 15,000 transactions, in order to filter out scam tokens.
See the criteria at : https://developer.trustwallet.com/assets/requirements .

**Comment by AlOaks** [comment]
Hello Trust Wallet team,

My nams is Alberto from the Sologenic team, we are the largest DEX & NFT Marketplace on the XRP Ledger. We have recently partnered with Ripple and Allbridge to go Cross-Chain and we now have 10% of our supply on the BSC. 

Here is an official link from Ripple mentioning SOLO and the bridge:
https://ripple.com/ripple-press/cross-chain-bridge-allbridge-brings-defi-to-the-xrp-ledger/

& Another link on Yahoo Finance about the BSC interoperability:
https://yhoo.it/3JNtwTn

We are currently in touch with Pancake Swap to start some SOLO pools on the DEX. However, we are interested in getting our LOGO available on Trust Wallet so the Token Branding is available when users trade on the platform. 

Please let me know what is required to get this completed. Here is also a link to our Verified CMC Supply:
https://coinmarketcap.com/currencies/sologenic/

Please let me know if you need any additional information for Proof of our Tokens legitimacy.

Regards,

**Comment by AlOaks** [comment]
> As per our policy, brand new tokens are not included, there is a minimum requirement of 10,000 holder addresses and 15,000 transactions, in order to filter out scam tokens. See the criteria at : https://developer.trustwallet.com/assets/requirements .


Hi, Sologenic here again.

https://bnbsmartchain.com/binance-completes-the-sologenic-solo-airdrop-distribution-to-xrp-xrp-holders/

In this post you can see how Binance finished the airdrop for Sologenic in the BSC. 

And as per my last comment, we are not a new token. It would be great if you could reach a conclusion on this. 
We are a multi-chain token with more than 300,000 holders. 

Looking forward to hear from you.

We can provide any proof for our token legitimacy.

Thank you

**Pull request closed without merging**
