### PR TITLE
Add LCP logo and info (BEP20)

### PR DESCRIPTION
**Pull request by Roseline-Ebunobi**
Token Logo  Image Information: 
- [x] File Name: logo.png
- [x] Size: 256px by 256px
- [x] Background: Transparent

Token Information File:
- [x] File Name: info.json

### CODE REVIEW

**Comment by Roseline-Ebunobi** [comment]
At least 2 links are required: 

- [x] https://twitter.com/Livecryptoparty
- [x] https://t.me/livecryptopartychat
- [x] https://www.instagram.com/livecryptoparty/
- [x] https://www.facebook.com/livecryptoparty
- [x] https://www.youtube.com/c/LiveCryptoParty
- [x] https://discord.com/invite/YbKczGGQeg

At least 1 tag is required: 
- [x] $LCP

Number of holders not checked: please, check it manually
Number holders including the LCP Stakers: 

- [x] 3086

**Review by Roseline-Ebunobi — COMMENTED** [review]
I have added the more details to the code  in response to requests for more information, including project social media links, tags,:  

Links:
            "name": "twitter",
            "url": "https://twitter.com/Livecryptoparty/"
      
            "name": "telegram",
            "url": "https://t.me/livecryptopartychat"
      
            "name": "coinmarketcap",
            "url": "https://coinmarketcap.com/currencies/live-crypto-party/"
        
            "name": "whitepaper",
            "url": "https://livecryptoparty.com/whitepaper.pdf"


 Tags: 
        "metaverse",
        "gamefi",
        "nft"

**Review by Roseline-Ebunobi — COMMENTED** [review]
Updates made based on errors found in previous code. 
I fixed the ID, removed metaverse, added Youtube Url

**Review by Roseline-Ebunobi — COMMENTED** [review]
Removed party to ear  and the youtube.

**Comment by cryptomanz1** [comment]
As per our policy, brand new tokens are not included, there is a minimum requirement of 10,000 holder addresses and 15,000 transactions, in order to filter out scam tokens.
See the criteria at : https://developer.trustwallet.com/assets/requirements .

**Comment by Roseline-Ebunobi** [comment]
> As per our policy, brand new tokens are not included, there is a minimum requirement of 10,000 holder addresses and 15,000 transactions, in order to filter out scam tokens. See the criteria at : https://developer.trustwallet.com/assets/requirements .

Hello, Crytomanz1. I hope you are well. Thank you for your comments and information.  I believe we meet the criteria if we total our transfers over the project lifespan and before our transition. This inclused stakers, presale transactions  and old LCP (https://bscscan.com/token/0x3dfa9b7cb5944c3dba51ed7467f3069909860666), etc. 

We are currently listed on a DEX as well as a Centralized exchange; LBANK. Our price is currently visible on Trust wallet, however the logo is not, therefore the application. I would appreciate it if you could help us fix this. 

Please let me know if you need anything else.  

Many thanks.

**Pull request closed without merging**
