### PR TITLE
Add Vita Inu (BEP20)

### PR DESCRIPTION
**Pull request by ElemontCapital**
Adding info for BEP20 token 'Vita Inu'.

PR created by <a href="https://assets.trustwallet.com">TW Assets Management</a>

### CODE REVIEW

**Comment by ElemontCapital** [comment]
Over 11,000 holders - https://vitescan.io/token/tti_541b25bd5e5db35166864096
We are bridging to BSC with this BEP20 VINU token.

**Comment by ElemontCapital** [comment]
We have also completed an audit of our bsc token: 
https://github.com/sokenteam/smart_contract_audits/blob/main/Vita%20Inu%20Standard%20Smart%20Contract%20Audit.pdf

**Comment by cryptomanz** [comment]
As per our policy, brand new tokens are not included, there is a minimum requirement of 5,000 holder addresses and 10,000 transactions, in order to filter out scam tokens.
See the criteria at : https://developer.trustwallet.com/assets/requirements .

**Comment by ElemontCapital** [comment]
> As per our policy, brand new tokens are not included, there is a minimum requirement of 5,000 holder addresses and 10,000 transactions, in order to filter out scam tokens. See the criteria at : https://developer.trustwallet.com/assets/requirements .

VINU is not brand new, only the BEP20 is new as we are native VEP20, and now going multi-chain. 

Our bscscan profile is also verified, and our VEP20 satisfies your minimum requirements as per my comments above. 

Wanted to get the Trust Wallet profile up in anticipation for our pancakeswap launch.

**Comment by ElemontCapital** [comment]
@cryptomanz are we able to merge the PR after payment given my explanations above?

**Comment by ElemontCapital** [comment]
We will submit a new PR later with more txs/holders.

**Pull request closed without merging**
