### PR TITLE
add Daily COP info and logo for Polygon

### PR DESCRIPTION
**Pull request by b4vtech**

### CODE REVIEW

**Comment by cryptomanz** [comment]
• What is the purpose of this token? How will it benefit Trust Wallet users?
 • How is the token being distributed? Are you conducting an airdrop?
 • Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?
 • Is the token listed on a centralized/decentralized exchange?
 • Is a Smart Contract audit completed? Where can we find this information?

**Comment by b4vtech** [comment]
> • What is the purpose of this token? How will it benefit Trust Wallet users? • How is the token being distributed? Are you conducting an airdrop? • Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale? • Is the token listed on a centralized/decentralized exchange? • Is a Smart Contract audit completed? Where can we find this information?

Hi @cryptomanz , thanks a lot for considering our application. Hereby the answers to your questions:

• The purpose of this token is for Colombians to have a stablecoin in their own currency so they can enter the crypto-space, experience digital payments and have liquidity in their own currency to exchange to other tokens as a protection against inflation and easily swap back if they need Daily COP for payments in over 600 businesses around Colombia. It is in the top 50 (currently 45) of tokens on Quickswap based on amount of liquidity and most of the holders use Trust Wallet already to interact with Daily COP in Quickswap. So it will benefit all these users that are already using Trust Wallet and a lot of educational videos are being made by the community using Trust Wallet to explain to people how to add Daily COP to Trust Wallet. If the token is already available and with logo, this would help a lot, especially for all those people who are just entering the crypto world for the first time because of Daily COP.
• The token is an evolution of a digital banking app and the bank balances can be converted to the token, that is the way how the token has been distributed to its users. There was no airdrop.
, neither an ICO or presale.
• There was also no ICO or presale, balances of the digital accounts, backed by the respective deposits, have organically been converted to the Daily COP token.
• Yes, the token is listed on Quickswap and it can be bought and sold at different local cryptocurrency exchanges in Colombia. 
• The Smart Contract audit was done by Blockchain Consilium and can be found in the code repository at the following link: https://github.com/miDaily/Daily-COP/raw/master/audit/v1/DLYCOP_SMART_CONTRACT_AUDIT.pdf

Thanks again and happy to give you any other info you need.

**Comment by cryptomanz** [comment]
Please follow the rules for adding token, your logo should be a full screen, 256x256.

**Comment by b4vtech** [comment]
> Please follow the rules for adding token, your logo should be a full screen, 256x256.

@cryptomanz Thanks, the logo is now updated to 256x256.

**Comment by Cryptocool1** [comment]
can you please add tags?
see the requirements here : https://developer.trustwallet.com/assets/requirements

**Comment by b4vtech** [comment]
> can you please add tags? see the requirements here : https://developer.trustwallet.com/assets/repository_details

Hi @Cryptocool1 , tag added 👍🏻 Thanks!

**Pull request merged**
