### PR TITLE
Add SEEDx (BEP20)

### PR DESCRIPTION
**Pull request by erience**
Adding info for BEP20 token 'SEEDx'.

### CODE REVIEW

**Comment by erience** [comment]
CMC Link: https://coinmarketcap.com/currencies/seedx/
CoinGecko Link: https://www.coingecko.com/en/coins/seedx
Coinbit CEX Link: https://coinsbit.io/trade/SEEDX_USDT

**Comment by Cryptocool1** [comment]
• What is the purpose of this token? How will it benefit Trust Wallet users?
 • How is the token being distributed? Are you conducting an airdrop?
 • Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?
 • Is the token listed on a centralized/decentralized exchange?
 • Is a Smart Contract audit completed? Where can we find this information?

**Comment by erience** [comment]
• What is the purpose of this token? How will it benefit Trust Wallet users? --- SEEDx is a unique zero proof of reserve decentralised orderbook based exchange offering traders in Binance Smart Chain platform. Apart from this SEEDx has AMM Swap, Launchpad, Governance DAO and No Code Token Mint tool for wallet users. 

• How is the token being distributed? Are you conducting an airdrop? ---  No Airdrop has been conducted. However, users can earn Staking rewards based 

• Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale? --- No ICO has been conducted. Users have purchased the tokens from Pool.

• Is the token listed on a centralized/decentralized exchange? --- The Token is listed on Pancakeswap, Uniswap and BiSwap DEX and Coinsbit CEX. The token is also listed on CoinMarketCap and CoinGecko

• Is a Smart Contract audit completed? Where can we find this information? --- The audit report can be accessed from here: https://xamer.io/project/Seedx

**Comment by erience** [comment]
@Cryptocool1 @cryptomanz1 : Any update on above?

**Pull request merged**
