### PR TITLE
feat(dfi): add DFI token info and logo

### PR DESCRIPTION
**Pull request by gjj**
**What is the purpose of this token? How will it benefit Trust Wallet users?**

[DeFiChain](https://defichain.com) is a decentralized non-Turing-complete proof-of-stake blockchain created as a hard fork of the Bitcoin network to enable advanced DeFi applications.

> DeFiChain is constantly looking for ways to facilitate improved interoperability of its native DFI token, and to increase its exposure to a wider audience of retail and institutional investors. As a result, DeFiChain created an ERC-20 standard token of DFI that will be available for trading on Uniswap as DFI/ETH and DFI/USDT trading pairs from today.
> -- [source](https://blog.defichain.com/defichains-first-move-to-become-an-interoperable-defi-powerhouse/)

This PR contains the logo for the wrapped ERC-20 version of the `DFI` token on DeFiChain. Trust Wallet users (and users of dApps where Trust Wallet's `assets` are pulled) will benefit from being able to recognize wrapped EVM-based versions of the native `DFI` token.

**How is the token being distributed? Are you conducting an airdrop?**

`DFI` is first issued on our native DeFiChain through various means -- mining rewards, community funds, anchor rewards and DEX liquidity mining rewards (see our [Pink Paper](https://blog.defichain.com/pink-paper-part-i/) for full details). 

Users on centralized exchanges that support the native DeFiChain `DFI` (e.g. Cake DeFi) can send wrapped ERC-20 `DFI` tokens onto the Ethereum mainnet. The backing of the ERC-20 `DFI` on the native DeFiChain is at address [`dZFYejknFdHMHNfHMNQAtwihzvq7DkzV49`](https://defiscan.live/address/dZFYejknFdHMHNfHMNQAtwihzvq7DkzV49).

**Did you sell the tokens at an Initial Coin Offering (ICO) or a token presale?**

There was no Initial Coin Offering, see [our website](https://defichain.com/dfi) for details.

**Is the token listed on a centralized/decentralized exchange?**

Yes. Below is a short list:

* [KuCoin](https://www.kucoin.com/trade/DFI-BTC) (ERC-20)
* [Bybit](https://www.bybit.com/en-US/trade/spot/DFI/USDT) (ERC-20)
* [Swyftx AU](https://swyftx.com/au/buy/defichain/) (ERC-20)
* [Cake DeFi](https://cakedefi.com/) (Native DeFiChain, transferrable to ERC-20)

The full list is on [this page](https://defichain.com/dfi).

Data Feeds Listings

* [CoinMarketCap](https://coinmarketcap.com/currencies/defichain/)
* [CoinGecko](https://www.coingecko.com/en/coins/defichain)

**Is a Smart Contract audit completed? Where can we find this information?**

ERC-20

* [SlowMist](https://www.slowmist.com/en/security-audit-certificate.html?id=b6e4952b8541cf4674c2cf57dcd685dad74267ee5bd67781414337f4b7f616f5) on our [ERC-20 token contract](0x8Fc8f8269ebca376D046Ce292dC7eaC40c8D358A)

Native DeFiChain

* [SlowMist](https://defichain.com/downloads/defichain-security-audit-slowmist.pdf)
* [KnownSec](https://defichain.com/downloads/DeFiChain-Security-Audit-Report-V1.pdf)

**Other comments**

We previously asked in https://github.com/trustwallet/assets/issues/21499 but received no reply on whether the `Minimum 10,000 token holders and 15,000 transactions` only looks into the ERC-20 version of the token.

The DeFiChain community has plans to increase the utility of the wrapped ERC-20 (and BEP-20) version of `DFI` and therefore having the `DFI` logo listed on various wallets and token swap dApps is crucial.

On our native DeFiChain, we currently have:

* 77,228 unique holders ([source](https://www.defichain-analytics.com/blockchain?entry=addresses))
* 284,848 all-time-high daily transactions on Jun 13, 2022 ([source](https://www.defichain-analytics.com/blockchain?entry=transactions))

### CODE REVIEW

**Comment by gjj** [comment]
> ❌ low token circulation: number of holders is 1083, below limit of 10000

We've explained in `Other comments` above.

**Comment by gjj** [comment]
@cryptomanz1 hey! Could you give us a bit of time while we make the payment?

**Comment by Cryptocool1** [comment]
Feel free to create new PR once the criteria are met

**Comment by gjj** [comment]
@Cryptocool1 @cryptomanz1 thanks for checking! We're not listing our BEP-20 version of the token, only the ERC-20 version at this point.

Does it mean that even though:
* $DFI is [#214 on CoinMarketCap](https://coinmarketcap.com/currencies/defichain/) given that it's on our native blockchain (i.e. not EVM-based), and
* would have met the criteria if not for the fact that we're requesting to list our ERC-20 token

The Trust Wallet team will not consider the token holders count on our native blockchain at all, and will only look at the ERC-20 token count exclusively?

cc @ngyingzhong

**Pull request closed without merging**
