### PR TITLE
Add BabyDogeZilla Logo To Trust Wallet

### PR DESCRIPTION
**Pull request by FreePatriot76**
We would like to get our project (BabyDogeZilla)'s logo added to Trust Wallet so it displays for investors trying to buy it in the app.  We would also like for the price of our token to display as we are on CMC.  We are willing to pay the submission fee we just need to know where to send the payment as the instructions do not clearly state that part.

### CODE REVIEW

**Review by FreePatriot76 — COMMENTED** [review]
Updated Checksum address

**Comment by Cryptocool1** [comment]
• What is the purpose of this token? How will it benefit Trust Wallet users?
 • How is the token being distributed? Are you conducting an airdrop?
 • Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?
 • Is the token listed on a centralized/decentralized exchange?
 • Is a Smart Contract audit completed? Where can we find this information?

**Comment by FreePatriot76** [comment]
It is a meme coin with a large, strong community (33,000 holders) and most of the users are using trust wallet.  We hit 31,000 holders in just the first week.
Also we are listed in CMC and CG, 2 of the most popular coin sites.
We do daily competitions & giveaways.
Fully community driven token with every day VC with very active people and Mods! Our holders keep asking for us to get the logo on Trust Wallet which is why we are pursuing this.

The token is sold on Pancakeswap and that is how it is distributed. We did do a small presale of 20 BNB that involved 30 people who were manually sent tokens.

Audit is on our website, it can be downloaded from there.  I have attached it here for your convenience.
[BabyDogeZilla-audit-1.pdf](https://github.com/trustwallet/assets/files/7491568/BabyDogeZilla-audit-1.pdf)

**Comment by FreePatriot76** [comment]
Can you give me an idea of how long before this will be approved and our logo will show in trust wallet?

Thank you!

**Pull request merged**
