### PR TITLE
Add KWS logo and info

### PR DESCRIPTION
**Pull request by jrazm**
Add KWS logo and info
KWS, Knight War Spirits is the official utility token of Knight War The Holy Trio, an intuitive Play-2-earn Action Game on Binance Smart Chain in the Idle Defense genre with a deep and sophisticated Generative NFT Weapon System.
**Website**: https://knightwar.io
**Whitepaper**: https://docs.knightwar.io/pitchdeck-litepaper/litepaperv1.2
**Social Media Presence:** 
- Twitter: https://twitter.com/knightwarp2e
- Facebook: https://www.facebook.com/knightwarp2e
- Discord: https://discord.gg/knightwarp2e
- Telegram: https://t.me/knightwarplaytowin

**Token Audit**: https://www.certik.org/projects/knightwar
**CoinMarketCap**: https://coinmarketcap.com/currencies/knight-war/

### CODE REVIEW

**Comment by jrazm** [comment]
May I ask how to solve the "links field cannot be empty" error.

And also if we pay, is there any chance we can get out token logo updated if our number of holders is below 25,000?

**Comment by Cryptocool1** [comment]
could you add the links?
see the example here: https://developer.trustwallet.com/assets/repository_details

**Review by jrazm — COMMENTED** [review]
Added links to info.json

**Review by jrazm — COMMENTED** [review]
Fixed Links format

**Comment by Cryptocool1** [comment]
• What is the purpose of this token? How will it benefit Trust Wallet users?
 • How is the token being distributed? Are you conducting an airdrop?
 • Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?
 • Is the token listed on a centralized/decentralized exchange?
 • Is a Smart Contract audit completed? Where can we find this information?

**Comment by jrazm** [comment]
Please reopen the PR

**• What is the purpose of this token? How will it benefit Trust Wallet users?**
    -> This token is the Official Utility Token of Knight War The Holy Trio.
         Currently, there are over 5000 players participating in the game daily. Trading NFTs, fighting bosses, participating in Boss Hunt, earning KWS. Most of our users use Trust Wallet. Therefore, it would benefit them if the KWS token got official logo updated.
**• How is the token being distributed? Are you conducting an airdrop?**
     -> Previously, we have conducted an Airdrop with CoinMarketCap. We distribute our token via Seed Sales, Private Sales, then IDO and IEO.

**• Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?**
     -> Only 0.5% of our total Token Circulation was sold at 2 IDOs on BSCStation and RedKite.

**• Is the token listed on a centralized/decentralized exchange?**
     -> The token is currently listed on PancakeSwap, Gate.io and ZT

**• Is a Smart Contract audit completed? Where can we find this information?**
     -> Yes. @ https://www.certik.org/projects/knightwar

**Pull request closed without merging**
