### PR TITLE
[Info] Hertz Network (HTZ BEP-20)

### PR DESCRIPTION
**Pull request by HertzArmy**
Hertz Network BEP-20 token logo and info

### CODE REVIEW

**Comment by HertzArmy** [comment]
Hi can you please confirm we have passed all checks and once payment has been submitted our logo and information will be updated on trust wallet? 

Thanks
HertzArmy

**Comment by Cryptocool1** [comment]
> Hi can you please confirm we have passed all checks and once payment has been submitted our logo and information will be updated on trust wallet?
> 
> Thanks
> HertzArmy

Submission looks good

**Comment by cryptomanz** [comment]
Hello,
Can your answer some questions?
• What is the purpose of this token? How will it benefit Trust Wallet users?
• How is the token being distributed? Are you conducting an airdrop?
• Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?
• Is the token listed on a centralized/decentralized exchange?
• Is a Smart Contract audit completed? Where can we find this information?

**Comment by HertzArmy** [comment]
• What is the purpose of this token? How will it benefit Trust Wallet users?
The purpose of HTZ BEP-20 is for users to be able to keep or swap HTZ on Binance Smart Chain. It’s practically a BEP-20 version of our native HTZ coin which is run on Hertz Network – an EOSIO based blockchain. Users are able to swap HTZ BEP-20 with native HTZ at 1:1 ratio on supporting exchanges like XT.com, dex-trade.com and catex.io. HTZ BEP-20 token is a part of Hertz Network ecosystem as shown here on our website - https://hertz-network.com/about/#ecosystem.


• How is the token being distributed? Are you conducting an airdrop?
We initially airdropped some native HTZ coin to holders of Ondori (RSTR) project, and we also had a couple of airdrop campaigns to grow our community. Currently, around 30% of the total supply are circulated, and the remaining 70% are allocated for staking rewards. Details of our distribution can be found here - https://hertz-network.com/about/#coineconomics.


• Did you sell the tokens at an Initial Coin Offering (ICO) or a token presale?
No, we didn’t.


• Is the token listed on a centralized/decentralized exchange?
Yes, HTZ BEP-20 token is listed on PancakeSwap. Users can trade HTZ BEP-20 on XT.com, dex-trade.com and catex.io. Here’s the link to all the exchanges that HTZ is listed on - https://hertz-network.com/buy-htz


• Is a Smart Contract audit completed? Where can we find this information?
We used Cointool.app to create HTZ BEP-20 token. We are having the Smart Contract audited, and the report will be completed in a couple of days.

**Pull request merged**
