### PR TITLE
Add Matrix Chain (BEP20)

### PR DESCRIPTION
**Pull request by mtcv3**
Adding info for BEP20 token 'Matrix Chain'.

PR created by <a href="https://assets.trustwallet.com">TW Assets Management</a>

### CODE REVIEW

**Comment by Cryptocool1** [comment]
Are you listed on CoinMarketCap?

**Comment by mtcv3** [comment]
> Are you listed on CoinMarketCap?

Not yet. We submit all CMC and CGC and wait for confirm.

**Comment by ANA885874** [comment]
Não recebi nenhum pagamento estão brincando comigo 😕

Em sex., 8 de dez. de 2023 05:45, mtcv3 ***@***.***> escreveu:

**Comment by mtcv3** [comment]
> Please come back to us once all criteria are met. Make sure to mention this PR so the fee can be reused.
Token should be listed on price tracking sites like CoinmarketCap
Hi your document said is "should" not require CMC listed.

**Comment by mtcv3** [comment]
Listed https://coinmarketcap.com/vi/currencies/matrix-chain/
@Cryptocool1 @cryptomanz1

**Pull request closed without merging**
