### PR TITLE
Add Golduck Logo and Info

### PR DESCRIPTION
**Pull request by Golducktoken**
Add Golduck token logo and information

### CODE REVIEW

**Comment by Cryptocool1** [comment]
Corrections needed:
Info file should be named info.json , not Info.json
Logo file should be named logo.png , not Logo.png
Please rename

**Comment by Golducktoken** [comment]
> Corrections needed:
> Info file should be named info.json , not Info.json
> Logo file should be named logo.png , not Logo.png
> Please rename


Thank you this has been done. what is the next steps

**Comment by Cryptocool1** [comment]
PR should include only 2 files:
blockchains/smartchain/assets/0x1a1c6f9F6B4E535130E9b1de46bBc76130b61Feb/info.json
blockchains/smartchain/assets/0x1a1c6f9F6B4E535130E9b1de46bBc76130b61Feb/logo.png

**Comment by Golducktoken** [comment]
> PR should include only 2 files:
> blockchains/smartchain/assets/0x1a1c6f9F6B4E535130E9b1de46bBc76130b61Feb/info.json
> blockchains/smartchain/assets/0x1a1c6f9F6B4E535130E9b1de46bBc76130b61Feb/logo.png

**Comment by Golducktoken** [comment]
The 2 files have been deleted

**Comment by Golducktoken** [comment]
> PR should include only 2 files:
> blockchains/smartchain/assets/0x1a1c6f9F6B4E535130E9b1de46bBc76130b61Feb/info.json
> blockchains/smartchain/assets/0x1a1c6f9F6B4E535130E9b1de46bBc76130b61Feb/logo.png

Please can you detail why it is failing?

**Pull request merged**
