### PR TITLE
Upload dApp Logos

### PR DESCRIPTION
**Pull request by tggeth**

### CODE REVIEW

**Comment by tgrypto** [comment]
We just like to pull the following Logos 

julswap.com Logo
bnbv2.justliquidity.org Logo
busdv2.justliquidity.org Logo
ethv2.justliquidity.org Logo

____

Jul Token Upload is already done! 

Thanks.

**Comment by Iamdeadlyz** [comment]
Please provide more details about this project.
https://community.trustwallet.com/t/how-to-submit-a-token-logo/3863#how-to-get-approved
You can follow this format when adding an info.json file:
```
{
    "name": "Trust Wallet Token",
    "website": "https://trustwallet.com",
    "source_code": "https://github.com/trustwallet/",
    "short_description": "Utility token to increase adoption of cryptocurrency.",
    "description": "Utility token to increase adoption of cryptocurrency.",
    "socials": [
        {
            "name": "Twitter",
            "url": "https://twitter.com/trustwalletapp",
            "handle": "TrustWalletApp"
        },
        {
            "name": "Reddit",
            "url": "https://reddit.com/r/trustapp",
            "handle": "TrustApp"
        }
    ],
    "explorer": "https://bscscan.com/token/0x4b0f1812e5df2a09796481ff14017e6005508003"
} 
```


Also, please fix the checksum issue by following this:
- Rename the folder to `0x5580ab97F226C324c671746a1787524AEF42E415-x`, commit, and push
- Rename it again to `0x5580ab97F226C324c671746a1787524AEF42E415`, commit, then push

**Comment by catenocrypt** [comment]
Closing due to missing additional information

**Comment by newindia1** [comment]
Nice project

**Pull request closed without merging**
