### PR TITLE
Add CCN (BEP20)

### PR DESCRIPTION
**Pull request by ccnnetworkco**
Adding info for BEP20 token 'CCN'.

PR created by <a href="https://assets.trustwallet.com">TW Assets Management</a>

### CODE REVIEW

**Comment by ccnnetworkco** [comment]
we have paid merge request fee in
txid:65B0FD12628F126D1316BA61659645893B0F805867C73E5B8983652226D25DF2 and memo:20474
to address:bnb1tqq9llyr3dyjd559dha6z5r5etk3qfwk07m098

**Comment by Cryptocool1** [comment]
65B0FD12628F126D1316BA61659645893B0F805867C73E5B8983652226D25DF2 - memo 20747 (not your token)

**Comment by ccnnetworkco** [comment]
> 65B0FD12628F126D1316BA61659645893B0F805867C73E5B8983652226D25DF2 - memo 20747 (not your token)

I mistakenly created two requests for one currency. And the transaction id that I sent is related to the payment of the first request.
It seems that this request will be followed up faster.
If so, I will close one of the requests

**Comment by Cryptocool1** [comment]
why did you pay with the memo 20747? Your memo should be  the same as the number of your PR. We don't have #20747

**Comment by ccnnetworkco** [comment]
I made my payment on the previous request. The request was closed by you due to duplication. I will write the address for you.
https://github.com/trustwallet/assets/pull/20474
I also had another github account that I posted on social media.
Unfortunately, I do not have access to that account, and I also edited the project's github address on social media and other websites.

**Comment by Cryptocool1** [comment]
one more time, sorry your memo is wrong. please see what memo should be.

**Comment by ccnnetworkco** [comment]
Were all the requirements for listing checked? If there is no problem, how long will it take to add us to your list?

**Comment by Cryptocool1** [comment]
Hello, 
• What is the purpose of this token? How will it benefit Trust Wallet users?
 • How is the token being distributed? Are you conducting an airdrop?
 • Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?
 • Is the token listed on a centralized/decentralized exchange?
 • Is a Smart Contract audit completed? Where can we find this information?

**Comment by ccnnetworkco** [comment]
The token will belong to a television network, and will be used for our dedicated NFT market, reducing a very large percentage of NFT fees for trusted users.We also want to prevent many losses for traders by informing the news and other factors affecting the market in a timely manner. 
Yes, we have AirDrop and over 70,000 people have joined our AirDrop, but we have not distributed any AirDrop tokens yet. 
Yes, we are in the process of selling the ICO, and the tokens that have been distributed have been either through the sale of the ICO or through the pre-sale. 
No, we have not yet been officially listed by the developer team in any exchange, because we are in the ICO stage, but some users have created liquidity in some decentralized exchanges.
We have not yet audited for a smart contract

**Comment by Cryptocool1** [comment]
We require smart contract audit from reputable companies (Techrate , Certik, Hacken, Dessert Finance )

**Comment by ccnnetworkco** [comment]
Hello
The CCN audit request was released without any problems
I will share the link with you
https://dessertswap.finance/recentaudits.html
https://dessertswap.finance/audits/CCN-BSC-Audit-18070607.pdf

**Pull request closed without merging**
