### PR TITLE
Add EMP Token logo and infos

### PR DESCRIPTION
**Pull request by Jorgeluisreis**
Add EMP logo and information

### CODE REVIEW

**Comment by Cryptocool1** [comment]
Hello, 
• What is the purpose of this token? How will it benefit Trust Wallet users?
 • How is the token being distributed? Are you conducting an airdrop?
 • Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?
 • Is the token listed on a centralized/decentralized exchange?
 • Is a Smart Contract audit completed? Where can we find this information?

**Comment by Jorgeluisreis** [comment]
• What is the purpose of this token? How will it benefit Trust Wallet users?
EMP Token is a project of the "Light Group", the main project being Light DeFi. EMP Token is a project aimed at clean mining of cryptocurrencies using mining rigs, where mined coins are sold and part of the money is ejected into the EMP Token, with holder benefits, where 90% of users use Trust Wallet.

• How is the token being distributed? Are you conducting an airdrop?
 Token had no distribution prior to release, release was fair with DEVS having to buy token if they want it. There is no official airdrop being made.
 
• Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?
ICO

• Is the token listed on a centralized/decentralized exchange?
Yes, on PancakeSwap V2.

• Is a Smart Contract audit completed? Where can we find this information?
Audit made by Bitgard when it was still called Empiricus Token, today it has a new name: "EMP Token", but the smart contract is the same.

Audit Link: https://drive.google.com/file/d/1BmiDui01w32izVsgyf74w6529GXgzXeS/view?usp=sharing

**Comment by Jorgeluisreis** [comment]
• What is the purpose of this token? How will it benefit Trust Wallet users?
EMP Token is a project of the "Light Group", the main project being Light DeFi. EMP Token is a project aimed at clean mining of cryptocurrencies using mining rigs, where mined coins are sold and part of the money is ejected into the EMP Token, with holder benefits, where 90% of users use Trust Wallet.

• How is the token being distributed? Are you conducting an airdrop?
Token had no distribution prior to release, release was fair with DEVS having to buy token if they want it. There is no official airdrop being made.

• Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?
ICO

• Is the token listed on a centralized/decentralized exchange?
Yes, on PancakeSwap V2.

• Is a Smart Contract audit completed? Where can we find this information?
Audit made by Bitgard when it was still called Empiricus Token, today it has a new name: "EMP Token", but the smart contract is the same.

Audit Link: https://drive.google.com/file/d/1BmiDui01w32izVsgyf74w6529GXgzXeS/view?usp=sharing

**Comment by Jorgeluisreis** [comment]
• What is the purpose of this token? How will it benefit Trust Wallet users?
EMP Token is a project of the "Light Group", the main project being Light DeFi. EMP Token is a project aimed at clean mining of cryptocurrencies using mining rigs, where mined coins are sold and part of the money is ejected into the EMP Token, with holder benefits, where 90% of users use Trust Wallet.

• How is the token being distributed? Are you conducting an airdrop?
Token had no distribution prior to release, release was fair with DEVS having to buy token if they want it. There is no official airdrop being made.

• Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?
ICO

• Is the token listed on a centralized/decentralized exchange?
Yes, on PancakeSwap V2.

• Is a Smart Contract audit completed? Where can we find this information?
Audit made by Bitgard when it was still called Empiricus Token, today it has a new name: "EMP Token", but the smart contract is the same.

Audit Link: https://www.bitgard.co/bitgard-empV1.pdf

**Comment by Jorgeluisreis** [comment]
> Hello, • What is the purpose of this token? How will it benefit Trust Wallet users? • How is the token being distributed? Are you conducting an airdrop? • Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale? • Is the token listed on a centralized/decentralized exchange? • Is a Smart Contract audit completed? Where can we find this information?

• What is the purpose of this token? How will it benefit Trust Wallet users?
EMP Token is a project of the "Light Group", the main project being Light DeFi. EMP Token is a project aimed at clean mining of cryptocurrencies using mining rigs, where mined coins are sold and part of the money is ejected into the EMP Token, with holder benefits, where 90% of users use Trust Wallet.

• How is the token being distributed? Are you conducting an airdrop?
Token had no distribution prior to release, release was fair with DEVS having to buy token if they want it. There is no official airdrop being made.

• Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?
ICO

• Is the token listed on a centralized/decentralized exchange?
Yes, on PancakeSwap V2.

• Is a Smart Contract audit completed? Where can we find this information?
Audit made by Bitgard when it was still called Empiricus Token, today it has a new name: "EMP Token", but the smart contract is the same.

Audit Link: https://www.bitgard.co/bitgard-empV1.pdf

**Comment by cryptomanz** [comment]
- logo file should be size 256x256 please change
- Please follow the rules for adding tokens, your logo should be a full screen 256x256.
Exemple:
https://community.trustwallet.com/t/how-to-submit-a-token-logo/386
Screenshot 2021-10-01 at 01 52 16

**Comment by Jorgeluisreis** [comment]
> * logo file should be size 256x256, please change
> * Please follow the rules for adding tokens, your logo should be a full screen 256x256.
>   Exemple:
>   https://community.trustwallet.com/t/how-to-submit-a-token-logo/3863
> 
> Screenshot 2021-10-01 at 01 52 16

The logo has already been changed to 256x256 size. Awaiting analysis.

**Comment by cryptomanz** [comment]
Your logo should be a full screen 256x256.
 Exemple:
Screenshot 2021-10-01 at 01 52 16

**Comment by Jorgeluisreis** [comment]
> Your logo should be a full screen (256x256). Exemple: Screenshot 2021-10-01 at 01 52 16

A logo was fixed to full screen. Awaiting analysis.

**Pull request merged**
