### PR TITLE
Add MicroSHIBA (BEP20)

### PR DESCRIPTION
**Pull request by HeroDappDev**
Adding info for BEP20 token 'MicroSHIBA'.

PR created by <a href="https://assets.trustwallet.com">TW Assets Management</a>

### CODE REVIEW

**Comment by Cryptocool1** [comment]
hello,
does the everbabydoge your token?

**Comment by NickSags** [comment]
Yea it was . I submitted info for Microshiba and paid my 5 bnb for logo yesterday

**Comment by NickSags** [comment]
The MicroShiba (0xb78e41ae7fc8121978168557bb096e1a858be2ea)  token I submitted already is on Coin Gecko, CMC, and meet all criteria for ur logo to be on trust wallet for the application I submitted

**Comment by Cryptocool1** [comment]
> The MicroShiba (0xb78e41ae7fc8121978168557bb096e1a858be2ea) token I submitted already is on Coin Gecko, CMC, and meet all criteria for ur logo to be on trust wallet for the application I submitted
> […](#)

You need to add only MicroShiba token files

**Comment by NickSags** [comment]
i did in my request

**Comment by NickSags** [comment]
Can u get a reply please

**Pull request closed without merging**
