### PR TITLE
Add Niftyx Protocol (SHROOM) (ERC20)

### PR DESCRIPTION
**Pull request by NFTGameTheory**
This PR is being closed due to inactivity. If you wish to continue, please have us reopen the PR before sending your payment, or just create a new one.
Do NOT send payments for closed PR, as the fee may by lost!
  (320 vs. 48 hrs)

### CODE REVIEW

**Comment by Cryptocool1** [comment]
hello,
• What is the purpose of this token? How will it benefit Trust Wallet users?
 • How is the token being distributed? Are you conducting an airdrop?
 • Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?
 • Is the token listed on a centralized/decentralized exchange?
 • Is a Smart Contract audit completed? Where can we find this information?

**Comment by NFTGameTheory** [comment]
> hello,
> • What is the purpose of this token? How will it benefit Trust Wallet users?
> • How is the token being distributed? Are you conducting an airdrop?
> • Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?
> • Is the token listed on a centralized/decentralized exchange?
> • Is a Smart Contract audit completed? Where can we find this information?
---------
- Token provides governance capabilities, fee collection benefits and other perks in the ecosystem. We are updating logo and name to avoid confusion for Trust Wallet users. 
- Token is fully diluted, no more will be minted. MasterChef keys have been burnt. No airdrop was conducted.
- No presale or ICO. Token was open for anyone in public to farm between 2-7 September 2020. 
- Token is currently on Uniswap, Bitforex, Bilaxy.
- Smart Contact was a fork of Sushi Swap. There has been a number of community audits. One here: https://twitter.com/thetechn0cratic/status/1301418278888312832?s=19

**Comment by NFTGameTheory** [comment]
Paid. Please confirm

**Comment by cryptomanz** [comment]
can you please add links to your PR?
example: https://developer.trustwallet.com/add_new_asset#info-json-contents

**Comment by cryptomanz** [comment]
Hello,
- Awaiting for smart contract audit.

**Comment by NFTGameTheory** [comment]
> Hello,
> 
> * Awaiting for smart contract audit.

Hi, 
There have only been community audits like the one mentioned above that have taken place so far. Is this audit strictly necessary? It's a token that's been listed on Trust Wallet for 10 months without issues. Just a rebrand that's occurred. No changes to the contract have taken place. 

The contract is here:
https://etherscan.io/address/0xed0439eacf4c4965ae4613d77a5c2efe10e5f183#code

Control over the Masterchef was burnt here:
https://twitter.com/ShroomFinance/status/1310771576565108736

The plan is to eventually migrate over to a new token and contract to reflect this rebrand (from SHROOM to NIFTYX). This new contract will be fully audited. But in the meantime, this PR is a semi-temporary measure while we undergo this process. 

As it stands, Trust Wallet has different information on our token than all other resources. We think this is adding confusion and would really appreciate your understanding on this matter while we go through this process.

Thank you, hopefully, this helps

**Comment by Cryptocool1** [comment]
hello,
where can I find an official announcement about rebranding?

**Comment by Cryptocool1** [comment]
https://etherscan.io/address/0xed0439eacf4c4965ae4613d77a5c2efe10e5f183#code


> As it stands, Trust Wallet has different information on our token than all other resources. We think this is adding confusion and would really appreciate your understanding on this matter while we go through this process.
The plan is to eventually migrate over to a new token and contract to reflect this rebrand (from SHROOM to NIFTYX). This new contract will be fully audited. But in the meantime, this PR is a semi-temporary measure while we undergo this process.


on etherscan still shroom.finance

**Comment by NFTGameTheory** [comment]
> hello,
> where can I find an official announcement about rebranding?

Hi,

The announcement post can be found here. 
https://niftyx.medium.com/shroom-is-now-niftyx-the-global-layer-for-nfts-exchange-2f86212dbb15

This is linked on Etherscan as a rebrand announcement with all new links here:
https://etherscan.io/token/0xed0439eacf4c4965ae4613d77a5c2efe10e5f183

Also, Coin Gecko., Coinmarketcap and Coinbase have updated information. 
I'm trying to iron out these last few discrepancies as I believe there is some information pulled from your database to other sources. 

Would appreciate the assistance. 
Thank you

**Comment by Cryptocool1** [comment]
https://etherscan.io/token/0xed0439eacf4c4965ae4613d77a5c2efe10e5f183 change explorer in your info.json please

**Pull request merged**
