### PR TITLE
Add HARE logo and info

### PR DESCRIPTION
**Pull request by JohnnieM14**
Add HARE logo and info, 0x4afc8c2be6a0783ea16e16066fde140d15979296

Hope to hear from you soon.

Thank you very much.

### CODE REVIEW

**Comment by JohnnieM14** [comment]
May i know why are the files not allowed?

**Comment by JohnnieM14** [comment]
May i know how do i rectify the contract checksum format? even after renaming it to 0x4AFc8c2Be6a0783ea16E16066fde140d15979296 its still shows error.

**Comment by cryptomanz** [comment]
duplicate #10459

**Comment by JohnnieM14** [comment]
Hi Nazar

thank you for your understanding, I am still experiencing the same problem
as before.

And we do really hope that we are allowed to be successfully verified by
TrustWallet. Also, most of our holders are using TrustWallet to do
transactions for our token.

Thank you very much

J. M.

**Pull request closed without merging**
