### PR TITLE
Adding LMG logo and info

### PR DESCRIPTION
**Pull request by arvi0724**
Provided are info.json file and a logo in 250 x 250 PNG format

### CODE REVIEW

**Comment by Cryptocool1** [comment]
hello,
could you please answer some questions?
• What is the purpose of this token? How will it benefit Trust Wallet users?
 • How is the token being distributed? Are you conducting an airdrop?
 • Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?
 • Is the token listed on a centralized/decentralized exchange?
 • Is a Smart Contract audit completed? Where can we find this information?

**Comment by arvi0724** [comment]
the answer to first question is its a charity token created to save
mountain goats in Central and South Asia

it is only fair launch
yes airdrops were done
this is sister token of LUD
it is a newly launched token, so it is not listed on any exchange
audit not done yet

**Comment by arvi0724** [comment]
Do i need to make another PR for this?

**Comment by Cryptocool1** [comment]
> the answer to first question is its a charity token created to save mountain goats in Central and South Asia it is only fair launch yes airdrops were done this is sister token of LUD it is a newly launched token, so it is not listed on any exchange aside from pancakeswap audit not done yet
> […](#)

can you please explain "this is sister token of LUD" what do you mean?

**Comment by arvi0724** [comment]
the developer is developing little ugly duck swap, and he needs a reliable
token to perform swap test

**Comment by Cryptocool1** [comment]
awaiting for smart contract audit
on hold for now

**Comment by arvi0724** [comment]
ill send the link here once the audit is released, thank you =)

**Comment by Cryptocool1** [comment]
please create new PR when smart contract audit will be readymade sure to mention this PR

**Pull request closed without merging**
