### PR TITLE
Add Cheems (BEP20)

### PR DESCRIPTION
**Pull request by CheemsTeam**
Adding info for BEP20 token 'Cheems'.

PR created by <a href="https://assets.trustwallet.com">TW Assets Management</a>

### CODE REVIEW

**Comment by CheemsTeam** [comment]
- What is the purpose of this token? How will it benefit Trust Wallet users?

This is a meme token on the bsc chain
Trust Wallet users can participate in community building by conducting border transactions in their wallets through pancakes and other dex


- How is the token being distributed? Are you conducting an airdrop?

Total supply is 219,776,051,832,670, and 100% fairlaunch


- Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?

Tokens are issued by airdropping to addresses that meet the conditions, with no revenue


- Is the token listed on a centralized/decentralized exchange?

Our token info on coinmarketcap and coingecko:
https://coinmarketcap.com/currencies/cheems-pet

https://www.coingecko.com/en/coins/cheems-token

Decentralized exchange on pancake:
https://pancakeswap.finance/swap?outputCurrency=0x0DF0587216a4a1bB7d5082fdc491d93d2dD4B413&chain=bsc&inputCurrency=BNB


- Is a Smart Contract audit completed? Where can we find this information?

Yes, and you can see our contract security information on several dex trading websites

https://www.dextools.io/app/en/token/cheemsbnb
https://ave.ai/token/0x0df0587216a4a1bb7d5082fdc491d93d2dd4b413-bsc
image

https://dexscreener.com/bsc/0x38231d4ef9d33ebea944c75a21301ff6986499c3
image

**Comment by CheemsTeam** [comment]
- What is the purpose of this token? How will it benefit Trust Wallet users?

This is a meme token on the bsc chain
Trust Wallet users can participate in community building by conducting border transactions in their wallets through pancakes and other dex


- How is the token being distributed? Are you conducting an airdrop?

Total supply is 219,776,051,832,670, and 100% fairlaunch


- Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?

Tokens are issued by airdropping to addresses that meet the conditions, with no revenue


- Is the token listed on a centralized/decentralized exchange?

Our token info on coinmarketcap and coingecko:
https://coinmarketcap.com/currencies/cheems-pet

https://www.coingecko.com/en/coins/cheems-token

Decentralized exchange on pancake:
https://pancakeswap.finance/swap?outputCurrency=0x0DF0587216a4a1bB7d5082fdc491d93d2dD4B413&chain=bsc&inputCurrency=BNB


- Is a Smart Contract audit completed? Where can we find this information?

Yes, and you can see our contract security information on several dex trading websites

https://www.dextools.io/app/en/token/cheemsbnb
https://ave.ai/token/0x0df0587216a4a1bb7d5082fdc491d93d2dd4b413-bsc
image

https://dexscreener.com/bsc/0x38231d4ef9d33ebea944c75a21301ff6986499c3
image

**Comment by Cryptocool1** [comment]
After careful review of your submission, it looks like this token has not undergone any security audit. The request will be closed until further notice.

To know more about the token approval guidelines, please check this article: [How to Submit Token Logo](https://developer.trustwallet.com/listing-new-assets/requirements).

Feel free to re-open pull request once you meet those requirements.

**Comment by CheemsTeam** [comment]
I have already uploaded the audit documents for the contract. Please take a look when you have a moment. Thank you!
[Cheems_audit_report_2024-10-11.pdf](https://github.com/user-attachments/files/17345299/Cheems_audit_report_2024-10-11.pdf)

**Pull request closed without merging**
