### PR TITLE
Add TruBadger (BEP20)

### PR DESCRIPTION
**Pull request by trubadger**
Adding info for BEP20 token 'TruBadger'.

PR created by <a href="https://assets.trustwallet.com">TW Assets Management</a>

### CODE REVIEW

**Comment by trubadger** [comment]
@cryptomanz @Cryptocool1 

Payment is done and status was on hold for cmc listing:

Check PR #11543

TruBadger is listed:

https://coinmarketcap.com/en/currencies/trubadger/

https://www.coingecko.com/nl/coins/trubadger

Can you approve and procces. PR is done with beta asset app.

Thanks.

**Comment by Cryptocool1** [comment]
As per our policy, brand new tokens are not included, there is a minimum requirement of 5000 holder addresses and 10000 transactions, in order to filter out scam tokens.
See the criteria at (mentioned in the first message by the bot): https://community.trustwallet.com/t/how-to-submit-a-token-logo/3863).
Closing PR for now. Please come back to us when all criteria are met.

**Comment by trubadger** [comment]
@Cryptocool1 @cryptomanz 

I understand the policy, but when we applied and paid the processing fee,
the criteria were 2500 holders and 5000 transactions.

In PR #11543 you can see the conversation that it was on hold for CMC listing (quoted by @cryptomanz)

We had to wait until we where listed on CMC and perform a new pull request.

Now we are listed and this is done but it gets closed every time.

Can you re-open and merge ?

We have a Deerlock Rugpull Free certificate
We are Audited by Techrate and we have a fullly doxxed USA team as you can see in PR #11543 

Thanks.

**Comment by Cryptocool1** [comment]
your logo background should be transparent
please change

**Comment by trubadger** [comment]
@Cryptocool1 Thanks for re-opening.

I just updated the logo:

https://github.com/trubadger/assets/commit/b9713ea7d648b15a950c744c1ce22cad896d80b5

**Comment by cryptomanz** [comment]
logo still with white background

**Comment by RebelByCause** [comment]
Can I create a new PR with the assets app with updated logo and mention this PR ?

**Comment by trubadger** [comment]
@Cryptocool1 

When I updated with the Github desktop app, it updates in a different folder, not the one created with TW app (tw app is capital letters)

This is the link to to the updated logo:


Should I create a new PR with the updated logo in the TW assets app?

Thanks

**Comment by cryptomanz** [comment]
> @Cryptocool1
> 
> When I updated with the Github desktop app, it updates in a different folder, not the one created with TW app (tw app is capital letters)
> 
> This is the link to to the updated logo:
> 
> https://github.com/trubadger/assets/blob/b9713ea7d648b15a950c744c1ce22cad896d80b5/blockchains/binance/assets/0xc003f5193cabe3a6cbb56948dfeaae2276a6aa5e/logo.png
> 
> Should I create a new PR with the updated logo in the TW assets app?
> 
> Thanks

sure, you can create new PR.
make sure to mention this PR so the fee can be reused

**Pull request closed without merging**
