### PR TITLE
Add Project-X (BEP20)

### PR DESCRIPTION
**Pull request by pexcoinadmin**
Adding info for BEP20 token 'Project-X'.

PR created by <a href="https://assets.trustwallet.com">TW Assets Management</a>

### CODE REVIEW

**Comment by cryptomanz** [comment]
Please remove this files:
Screenshot 2021-12-06 at 16 50 18
Screenshot 2021-12-06 at 16 50 42

**Comment by cryptomanz** [comment]
Screenshot 2021-12-06 at 16 55 58
and this logo remove, please

**Comment by pexcoinadmin** [comment]
I am trying. It doesn't allow me to remove. Are you able to remove it as an admin?

**Comment by pexcoinadmin** [comment]
image

**Comment by pexcoinadmin** [comment]
I think I managed :)

**Comment by cryptomanz** [comment]
• What is the purpose of this token? How will it benefit Trust Wallet users?
 • How is the token being distributed? Are you conducting an airdrop?
 • Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?
 • Is the token listed on a centralized/decentralized exchange?
 • Is a Smart Contract audit completed? Where can we find this information?

**Comment by pexcoinadmin** [comment]
- We are building an NFT platform for focus on artists and content creators. We have more than 32K active holders many of which use trust wallet to hold our token and interact with Pancakeswap. 
- We have not done any airdrop. The token has been sold on a fair offering to community through pancakeswap.
- No ICO or pre-sales.
- The token is currently only listed on pancakeswap with decent trading volumes. For example, today we have had $32million trading volume. At our peak we had around $200million dollar of trading volume.
- The smart contract is a standard ERC20 contract with the only modification being that mint function has been deactivated to remove risk of new tokens being generated.

**Comment by cryptomanz** [comment]
Do you have smart contract audit?

**Comment by pexcoinadmin** [comment]
No, but as mentioned we are using standard ERC20 contarct. None of the code is written by us. The code is verified and open. 
image

**Comment by Cryptocool1** [comment]
Please come back to us when all smart contract audit will be ready.
When creating a new PR make sure to mention this PR, so that we can see that fee has been paid already here.

**Comment by pexcoinadmin** [comment]
If we had a smart contract with many functionality I would fully understand your position. But a standard ERC20 contract doesn't really need an audit. The ERC20 contract just defines parameters of the token.

**Pull request closed without merging**
