### PR TITLE
add ctc-token

### PR DESCRIPTION
**Pull request by BMJ20200716**
add ctc-token

### CODE REVIEW

**Comment by catenocrypt** [comment]
Info.json is wrong format.  Why do you want to modify it?

**Comment by BMJ20200716** [comment]
I made a mistake😭😭 BMJ Distributed Storage Email:bmj20200716@gmail.com Signature is customized by Netease Mail Master On 10/28/2020 04:28, Adam R wrote: Info.json is wrong format. Why do you want to modify it? — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by catenocrypt** [comment]
Closing in favor of #4634 .

**Comment by BMJ20200716** [comment]
Hi,sir,,,can you help me? BMJ Distributed Storage Email:bmj20200716@gmail.com Signature is customized by Netease Mail Master On 10/28/2020 16:41, Adam R wrote: Closing in favor of #4634 . — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe.

**Pull request closed without merging**
