### PR TITLE
Token logo for GreenCoin

### PR DESCRIPTION
**Pull request by dimage2299**

### CODE REVIEW

**Comment by Cryptocool1** [comment]
As per our policy, brand new tokens are not included, there is a minimum requirement of 5000 holder addresses and 10000 transactions, in order to filter out scam tokens.
See the criteria at (mentioned in the first message by the bot): https://community.trustwallet.com/t/how-to-submit-a-token-logo/3863).

**Comment by dimage2299** [comment]
Dear Trust Wallet,

As you can see per our website, we are not a scam token. We have been live
for over four weeks now and our token pricing is reflective of market
demand. We are not like those memecoins where the price is far below $.01.

In the past, I have submitted tokens where the holder count is under 2500
and still have gotten approval. Please review our case and let me know what
other information I can provide.

Best,

Greencoin

**Comment by dimage2299** [comment]
Dear Trust Wallet,

I am from GreenCoin and am following up regarding our token logo submission (ID #13373).

I submitted our token logo for approval and received an email back regarding your requirement for 5k holders and 10k transactions to filter out scam tokens. I replied to that email defending my project in that our project is completely legitimate and providing actual utility to the blockchain space. We are backed by prominent investors and have been developing our backend for over 6 months now.


As you can see from our website, we are providing an intersection of sustainable health data and blockchain technology. Our tokenomics are very different than normal scam tokens with a reasonable supply, no tax on transactions, and a token price that is well above $0.01. In the past, I have submitted tokens for approval with 2.5k holders and they have gotten merged with no issues. 

If I can provide any more information to speed up this approval process, please let me know.

**Comment by Cryptocool1** [comment]
correction needed:
- The links field cannot be empty
- Logo image too large, max 100 kB, current 152.323 kB
please change

**Comment by dimage2299** [comment]
Added in the two links and resized logo - please let me know if there are any other issues.

**Comment by Cryptocool1** [comment]
Can you answer some questions?
• What is the purpose of this token? How will it benefit Trust Wallet users?
 • How is the token being distributed? Are you conducting an airdrop?
 • Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?
 • Is the token listed on a centralized/decentralized exchange?
 • Is a Smart Contract audit completed? Where can we find this information?

**Comment by dimage2299** [comment]
Green Flow is a blockchain-enabled platform where users are incentivized to
exercise, improve their health, contribute health data while earning from
the data generated and energy spent via Green Flow's suite of cutting-edge
fitness devices, exercise equipment, and wearables. A large percentage of
our current holders and investors use various wallets with Trust Wallet
being a popular choice.

Our token is launched on Uniswap and we have completed a presale with large
investors such as Poe Qui Ying Wangsuo. Some of our other investors have
their tokens currently locked and periodically unlocked over the next 24
months.

We are currently in the process of completing our token contract audit and
are developing other smart contract/blockchain-related tech.

**Comment by Cryptocool1** [comment]
awaiting smart contract audit. on hold for now.

**Comment by Cryptocool1** [comment]
please create new PR when all criteria are met. make sure to mention this PR, so the fee can be reused.

**Pull request closed without merging**
