### PR TITLE
Add Binemon (BIN) info and logo

### PR DESCRIPTION
**Pull request by BinemonTech**
Hello Trust Wallet team,

We want to add BIN logo into your wallet. Please guide us
This is our CMC link: https://coinmarketcap.com/currencies/binemon/
Telegram channel: https://t.me/binemon
Twitter: https://twitter.com/binemonnft

Thanks and Regards,
Binemon Team

### CODE REVIEW

**Comment by cryptomanz** [comment]
carrion needed:
Contract is not in checksum format, please change

**Comment by BinemonTech** [comment]
> correction needed:
> Contract is not in checksum format, please change

0xe56842Ed550Ff2794F010738554db45E60730371

**Comment by BinemonTech** [comment]
I cannot find my file to rename. Please help

**Comment by BinemonTech** [comment]
Hi, I cannot find my file to rename it

**Pull request merged**
