### PR TITLE
Abond info

### PR DESCRIPTION
**Pull request by ixm-759**

### CODE REVIEW

**Comment by cryptomanz1** [comment]
• What is the purpose of this token? How will it benefit Trust Wallet users?
 • How is the token being distributed? Are you conducting an airdrop?
 • Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?
 • Is the token listed on a centralized/decentralized exchange?
 • Is a Smart Contract audit completed? Where can we find this information?

**Comment by ixm-759** [comment]
@cryptomanz1

**What is the purpose of this token? How will it benefit Trust Wallet users?**

ABOND is the primary native utility token of the ApeBond ecosystem. ABOND ties holders with the protocol like never before. Holding ABOND opens the door to special token-gated Ecosystem Bonds. Users that lock ABOND receive veABOND which unlocks additional exclusive utilities. Full details of our Token is available within our documentation pages at https://docs.ape.bond/apebond/welcome/abond. 

**How is the token being distributed? Are you conducting an airdrop?**

Our Tokenomics at launch, were as follows: 

Migration (39.1%): Needed for the Migration. Matches the amount of BANANA locked one to one.
Ecosystem Fund (15%): A replacement for our current MasterApe, meant for allocating ABOND towards the growth of the protocol (e.g., Bonds).
Multiplier Buffer (14.9%): The amount needed to ensure everyone can migrate without being diluted.
Fundraise (10%): An allocation for fundraising.
Treasury (10%): For recurring marketing and operations expenses.
Team (5%): Allocated for the development of ApeBond. Has a 3-year linear vesting.
Bonus Bucket (5%): Additional rewards for those who choose to lock their BANANA for a longer period during the migration process.
Initial Liquidity (1%): Needed to provide Liquidity Pools for the newly migrated token.

Our TGE was 12th December 2023.

**Did you sell the tokens at an Initial Coin Offering (ICO) or a token presale?**

There was no ICO or pre-sale for the ABOND token. 

**Is the token listed on a centralized/decentralized exchange?**

Both, ABOND is available on a range of decentralised and centralised exchanges, including sale through Bond at APE.BOND

**Is a Smart Contract audit completed? Where can we find this information?**

Yes, link here: https://docs.ape.bond/apebond/where-dev/security#audits

**Comment by Cryptocool1** [comment]
Screenshot 2024-06-16 at 09 18 05
Please check the link to your audit

**Comment by ixm-759** [comment]
@Cryptocool1 The link is correct, I just checked it and it loads.
image

**Comment by ixm-759** [comment]
> ### PR Summary
> Files OK: 2 Token in PR: **BEP20** 0x34294AfABCbaFfc616ac6614F6d2e17260b78BEd Symbol: **ABOND** decimals: 18 Links: [Logo](https://raw.githubusercontent.com/ixm-759/assets/master/blockchains/smartchain/assets/0x34294AfABCbaFfc616ac6614F6d2e17260b78BEd/logo.png) [Info](https://raw.githubusercontent.com/ixm-759/assets/master/blockchains/smartchain/assets/0x34294AfABCbaFfc616ac6614F6d2e17260b78BEd/info.json) [Website](https://ape.bond/) [Explorer](https://bscscan.com/token/0x34294AfABCbaFfc616ac6614F6d2e17260b78BEd) Tags: staking, dapp, governance, defi Token check error: ❌ number of holders not checked: please, check it manually
> 
> 

Holders number: 10017

image

**Comment by ixm-759** [comment]
Hey @Cryptocool1, any news on this?

**Pull request merged**
