### PR TITLE
Add PokerFi (BEP20)

### PR DESCRIPTION
**Pull request by renatomaiag**
Adding info for BEP20 token 'PokerFi'.

PR created by <a href="https://assets.trustwallet.com">TW Assets Management</a>

### CODE REVIEW

**Comment by Cryptocool1** [comment]
• What is the purpose of this token? How will it benefit Trust Wallet users?
 • How is the token being distributed? Are you conducting an airdrop?
 • Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?
 • Is the token listed on a centralized/decentralized exchange?
 • Is a Smart Contract audit completed? Where can we find this information?

**Comment by Cryptocool1** [comment]
How did you get more than 10000 holders in 2 days?

**Review by alhaidarykhalid — COMMENTED** [review]
K

**Comment by renatomaiag** [comment]
is anything else missing?

Em sex., 6 de out. de 2023 às 13:10, Renato Maia ***@***.***>
escreveu:

**Comment by Cryptocool1** [comment]
We require smart contract audit.
Please come back to us once audit completed.

**Comment by Cryptocool1** [comment]
Feel free to come back once audit is done. Make sure to mention this PR in new so the fee can be reused.

**Pull request closed without merging**
