### PR TITLE
Adding official logo and info for Mommy Doge Token

### PR DESCRIPTION
**Pull request by MommyDoge**
This commit shall add the official info and assets for MommyDoge Token. For more information see https://mommydoge.com

### CODE REVIEW

**Comment by cryptomanz** [comment]
hello,
what is the purpose of this token?

**Comment by MommyDoge** [comment]
Hey, glad you asked! Here's what we wanna achieve and what we stand for:

Mommy Doge was born in July 2021 with the goal of being a decentralized
meme project with a great purpose. Mommy Doge is a fun meme on a
serious mission to make crypto accessible and safe for everyone, while also
supporting the women's rights movements. The project wants to bring
crypto adoption to the mainstream by protecting her holders. But Mommy
Doge got even more to offer for her babies - her holders: We will build an
ecosystem of cool new concepts such as holding rewards, non-fungible
token (NFT) marketplace for creative creators, token launchpad, community
voting and many more ideas our community can vote on. Mommy Dog
calls this the Paw Empire and will rule it as the new Paw!

If you have any further questions, don't hesitate to reach out!

**Comment by cryptomanz** [comment]
please create new PR when this token will be on CMC

**Comment by MommyDoge** [comment]
Sure will do! We already paid the fee though, is there a way to connect the new PR and the alread paid fee @cryptomanz ?

**Comment by MommyDoge** [comment]
Hi,
thank you for reaching out. To answer your questions, the purpose of 
this token is a decentralized NFT trading card game meme token. The 1st 
Edition Mommy Doge NFTs (non-fungible token) are already listed on 
OpenSea.io. Mommy Doge is a fun meme project on a serious mission to 
support and bring attention to women rights and gender equality in 
general. We are also strong supporters of making crypto more accessible 
and safe for everyone. But Mommy Doge got even more to offer for her 
puppies (her holders): We are building an ecosystem of cool new concepts 
such as a NFT cards trading game with meme characters (Doge, Baby Doge 
and of course Mommy Doge - many more coming), a NFT marketplace for 
creators, a token launchpad, community voting and many more ideas our 
community can vote on.

Our strong community of 7+k holders and 7.5+k Telegram users have 
upvoted us on some of the main voting sites, such as Blockfolio and 
coinvote. We reached a ATH 15M marketcap after just 24h after launch and 
the community is eagerly awaiting the Trustwallet integration. We also 
applied to CoinMarketCap and will be listed soon.

If you have any other question, don't hesitate to reach out.
We hope you will now proceed with the Trustwallet integration of 
MommyDoge.

Thank you,
Sandra Perez
Global Head of Business Development, MommyDoge
Madrid, Spain

**Pull request closed without merging**
