### PR TITLE
Pmc logo

### PR DESCRIPTION
**Pull request by Azim565**
Please sir ad my logo
0x97f78f697e9b8233cc93729ace5fbf3ef26897ee logo

### CODE REVIEW

**Comment by Azim565** [comment]
Please sir ad my logo 🙏🙏🙏

**Comment by Azim565** [comment]
Please sir ad my logo 🙏🙏🙏
0x97f78f697e9b8233cc93729ace5fbf3ef26897ee logo

**Comment by Azim565** [comment]
0x97f78f697e9b8233cc93729ace5fbf3ef26897ee logo

**Comment by kolya182** [comment]
@Azim565 Last reminded, go and read requirements https://github.com/trustwallet/assets

**Comment by Azim565** [comment]
Sir I paid 2000 twt to put the logo on the trust wallet. The address of the
payment I made.
https://explorer.binance.org/tx/0553F61A1C235AED5AA3B01B7366C67EFD7E7BB9DAA622C148068030BE170531
And sir the address of the pull request I sent
https://github.com/trustwallet/assets/pull/1531
My coin name : wishcoin
Sir, please tell me why the logo was not added Trust wallet.
Sir the etherscan address of my token
0xFA12040497bC7B6077Ea125Bad27dAA8b74E7eDC
Sir I want to know where I went wrong if you please tell me I would be very
happy.
Sir, if need be, I will pay again.
Thank you sir I think you will give correct answer to my question

**Comment by catenocrypt** [comment]
@Azim565 , the payment mentioned was for PR 2135, which was for Teccoin, so not for #1531, not for Wishcoin.
https://explorer.binance.org/tx/0553F61A1C235AED5AA3B01B7366C67EFD7E7BB9DAA622C148068030BE170531
https://github.com/trustwallet/assets/pull/2135
You should create a new PR and pay the fee for it.

**Pull request closed without merging**
