### PR TITLE
Add Kitty Shiba (BEP20)

### PR DESCRIPTION
**Pull request by solproc**
Adding info for BEP20 token 'Kitty Shiba'.

PR created by <a href="https://assets.trustwallet.com">TW Assets Management</a>

### CODE REVIEW

**Comment by solproc** [comment]
I have already paid: https://binance.mintscan.io/txs/73E05A7D9338D6C13317F02F6A522A86721F52663FBE51159557A8DEDD01989C

**Comment by Cryptocool1** [comment]
• What is the purpose of this token? How will it benefit Trust Wallet users?
 • How is the token being distributed? Are you conducting an airdrop?
 • Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?
 • Is the token listed on a centralized/decentralized exchange?
 • Is a Smart Contract audit completed? Where can we find this information?

**Comment by solproc** [comment]
> • What is the purpose of this token? How will it benefit Trust Wallet users? • How is the token being distributed? Are you conducting an airdrop? • Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale? • Is the token listed on a centralized/decentralized exchange? • Is a Smart Contract audit completed? Where can we find this information?

* Its a meme token, purpose to earn money in easy way. It is growing very fast, it will also creates more userbase for trust wallet.
* Token distributed in a very proper way. We conduct an ILO on unicrypt and 99% token was involve in that case. We didn't distribute a single token through airdrop but near future we do some airdrop.
* Sold tokens are from an ILO at unicrypt.io
* Its listed on pancakeswap and a decent trading volume. It is KYC & Smart contract audit pass project. 11th Nov start trading on hotbit.io
* Audit completed. Link: https://github.com/solidproof/smart-contract-audits/blob/main/SmartContract_Audit_Solidproof_KittyShiba.pdf
and audit certificate link: https://github.com/solidproof/audit-certificates/blob/main/Audit_Certificate_KittyShiba.png

**Comment by solproc** [comment]
Sorry to bother, still now token price does not show on trust wallet.

**Comment by Cryptocool1** [comment]
hello, you need to wait for 1-2 weeks after CMC listing. Adding here to the repo - does not guarantee showing any price. Assets repo is not responsible for the price.

**Comment by Cryptocool1** [comment]
Can you please send me the logo image in full circle size?

**Pull request merged**
