### PR TITLE
Add KazooCoin (BEP20)

### PR DESCRIPTION
**Pull request by KazooCoinBSC**
Adding info for BEP20 token 'KazooCoin'.

PR created by <a href="https://assets.trustwallet.com">TW Assets Management</a>

### CODE REVIEW

**Comment by KazooCoinBSC** [comment]
Hello, I was told to make another pull request as I had put it in the wrong place...
Link so you can view that we payed our 2bnb

https://github.com/trustwallet/assets/pull/8393

**Comment by KazooCoinBSC** [comment]
Also, we are at 2500 holders, you can check this manually

**Comment by Cryptocool1** [comment]
PR should include only 2 files

**Comment by KazooCoinBSC** [comment]
I used that automated one you sent me

**Comment by KazooCoinBSC** [comment]
How do I fix this, I used that automated tool to make a new pull request

**Pull request closed without merging**
