### PR TITLE
Add PirateCash (PIRATE) token on BSC

### PR DESCRIPTION
**Pull request by gades**

### CODE REVIEW

**Comment by gades** [comment]
https://explorer.bnbchain.org/tx/6977BA417DEC79687241BE4FC93FD5E228FF4C68AD44677DFFE15DA64739D8B8

**Comment by Cryptocool1** [comment]
hello, 
 • Is a Smart Contract audit completed? Where can we find this information?

**Comment by gades** [comment]
Hello, It's default contract with option to generate new coins because it's wrapped BEP-20 real PirateCash coin https://coinmarketcap.com/currencies/piratecash/ and code was uploaded to https://bscscan.com/token/0x35f3ffffcb622bc9f64fa561d74e983fd488d90c#code

I didn't saw requirements for audit contract here https://developer.trustwallet.com/developer/listing-new-assets/new-asset , is it new option ?

**Comment by Cryptocool1** [comment]
We require an audit from reputable companies. 
please see our requirements here: https://developer.trustwallet.com/developer/listing-new-assets/requirements

**Comment by gades** [comment]
Ok, we'll do it , can you provide list of reputable companies which is will accepted your team ?

**Comment by Cryptocool1** [comment]
You can do for example Certik, Techrate, Dessert Finance or Hacken.

**Comment by gades** [comment]
Right now we're looking audit company but Idid check an example from Certik audit and can we use automatic free audits like https://gopluslabs.io/token-security/56/0x35f3ffffcb622bc9f64fa561d74e983fd488d90c ?

**Comment by Cryptocool1** [comment]
That is not full  contract audit

**Comment by gades** [comment]
I'll provide URL soon 

[PirateCash.pdf](https://github.com/trustwallet/assets/files/11209703/PirateCash.pdf)

**Comment by cryptomanz1** [comment]
@gades please update your branch with the recent master

**Comment by cryptomanz1** [comment]
Please follow the rules for adding token, your logo should be a full screen, 256x256.
Example:
https://community.trustwallet.com/t/how-to-submit-a-token-logo/3863

**Comment by gades** [comment]
It's already available on GitHub and their website 
https://github.com/TechRate/Smart-Contract-Audits/blob/main/April_2023/PirateCash.pdf

**Comment by gades** [comment]
> Please follow the rules for adding token, your logo should be a full screen, 256x256.
> Example:
> https://community.trustwallet.com/t/how-to-submit-a-token-logo/3863

ok, I'll double check and fix

**Comment by gades** [comment]
@Cryptocool1 @cryptomanz1 Anything else should I fix or provide?

- https://github.com/TechRate/Smart-Contract-Audits/blob/main/April_2023/PirateCash.pdf
- [rescale PirateCash logo to 256x256](https://github.com/trustwallet/assets/pull/24619/commits/349c59674f14dfd19fa86ea438fb4ac7cc1ec37d)

**Pull request merged**
