### PR TITLE
feature: add ricefarm logo and token info

### PR DESCRIPTION
**Pull request by bobachef**
Hi TrustWallet Team,

We've gotten our first token TeslaSafe listed a couple months ago and we'd like to now get our second token RICE listed also.

Rice farm is the second token in the Fuzion Ecosystem. We've released our farms and our vaults and are currently working towards getting our AMM up and running. https://ricefarm.fi

We launched using an Initial Farm Offering on our own platform https://ricefarm.fi/ifo

The way the token is distributed is via farming as a way to incentivize liquidity providers via our masterchef contract. https://docs.ricefarm.fi/resources/smart-contracts

This token has been traded on PancakeSwap for 2 months now. https://pancakeswap.finance/swap?outputCurrency=0xC4eEFF5aab678C3FF32362D80946A3f5De4a1861

We have been audited. You can see it on our website link and also in our docs. https://docs.ricefarm.fi/security/audits

Please take a look at our docs we have been working hard to benefit our users.

### CODE REVIEW

**Comment by cryptomanz** [comment]
Hello,
Can your answer some questions?
 • What is the purpose of this token? How will it benefit Trust Wallet users?
 • How is the token being distributed? Are you conducting an airdrop?
 • Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?
 • Is the token listed on a centralized/decentralized exchange?
 • Is a Smart Contract audit completed? Where can we find this information?

**Comment by bobachef** [comment]
Hello @cryptomanz!

Rice farm is the second token in the Fuzion Ecosystem. We've released our farms and our vaults and are currently working towards getting our AMM up and running. 

We launched using an Initial Farm Offering on our own platform https://ricefarm.fi/ifo

The way the token is distributed is via farming as a way to incentivize liquidity providers.

This token has been traded on PancakeSwap for 2 months now.

We have been audited. You can see it on our website link and also in our docs.

https://docs.ricefarm.fi

Thanks,
Fuzion Team

**Comment by Cryptocool1** [comment]
can you please add links to your PR?
example: https://developer.trustwallet.com/add_new_asset/repository_details

**Comment by bobachef** [comment]
> can you please add links to your PR?
> example: https://developer.trustwallet.com/add_new_asset/repository_details

@Cryptocool1 Thank you for letting me know. I've gone ahead and added links 👍

**Pull request merged**
