### PR TITLE
Add Baby Mind (BEP20)

### PR DESCRIPTION
**Pull request by InuXiasi**
Adding info for BEP20 token 'Baby Mind'.

PR created by <a href="https://assets.trustwallet.com">TW Assets Management</a>

### CODE REVIEW

**Comment by InuXiasi** [comment]
Hello https://www.facebook.com/MarkHamiltonsMusic/ also creator and owner off Mind Music

**Comment by Cryptocool1** [comment]
Hello, is a mind music listed on TW?

**Comment by InuXiasi** [comment]
> Hello, is a mind music listed on TW?

Yes we are.

**Comment by Cryptocool1** [comment]
• What is the purpose of this token? How will it benefit Trust Wallet users?
 • How is the token being distributed? Are you conducting an airdrop?
 • Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?

**Comment by InuXiasi** [comment]
The majority off our holders use trust wallet.
Also our token is integrated into Mind Music so it will have multiple benefits for users
- The token has  ot been distributed prior by any airdrop we might hold airdrop events in the future.
- We sold out a 1000BNB HC and 500BNB SC Presale at 0.1BNB min buy and 5 BNB Max buy.

**Comment by Cryptocool1** [comment]
• Is the token listed on a centralized/decentralized exchange?

**Comment by InuXiasi** [comment]
We are currently listed on PancakeSwapV2 and plan to list in CEX possibly in the future.

**Pull request merged**
