### PR TITLE
Add ERTHA Token (BEP20)

### PR DESCRIPTION
**Pull request by webHerbertus**
Adding info for BEP20 token 'ERTHA Token'.

PR created by <a href="https://assets.trustwallet.com">TW Assets Management</a>

### CODE REVIEW

**Comment by webHerbertus** [comment]
Creating new PR for unfinished questions: https://github.com/trustwallet/assets/pull/17649 it's already paid.
@cryptomanz @Cryptocool1

**Comment by Cryptocool1** [comment]
• What is the purpose of this token? How will it benefit Trust Wallet users?
• How is the token being distributed? Are you conducting an airdrop?
• Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?
• Is the token listed on a centralized/decentralized exchange?
• Is a Smart Contract audit completed? Where can we find this information?

**Comment by webHerbertus** [comment]
> 

- Token is used as the main currency of the game Ertha
- Yes, token had a presale and was airdropped to purchasers. We also will have a claim portal due to vesting.
- IGO was on Seedify, RedKite and GameFI, we also had private presale.
- Token is listed in Huobi and Kucoin, also PancakeSwap
- Smart contract audit can be found here: https://ertha.io/wp-content/uploads/smart_contract.pdf

**Review by kophyo1234 — APPROVED** [review]
0x0ae4cAcDe6b5a0d31369b311658e5897ED6b9938

**Pull request merged**
