### PR TITLE
Change contract address

### PR DESCRIPTION
**Pull request by eic0**
We want to change the contract address of our Token which is already listed in TW.

### CODE REVIEW

**Comment by eic0** [comment]
As already discussed in previous PR (https://github.com/trustwallet/assets/pull/16536) we would like to change the contract address of our already listed Token since we migrated.
Here are proofs of the migration:
- Official Instagram announcement:
https://www.instagram.com/p/CW0TUJvsM8-/?utm_medium=copy_link
- Yahoo Finance article about our migration:
https://finance.yahoo.com/news/cleanocean-successfully-migrating-clean-v2-140000322.html?guccounter=1

- Our Website has a link to our migration: https://cleanocean.io/
      -> Our (now already expired) migration web interface:
https://migration.cleanocean.io
- Announcement of the Migration on Twitter:
https://twitter.com/cleanoceantoken/status/1468245986002841603

**Comment by Cryptocool1** [comment]
submission looks good 
awaiting for fee payment

**Comment by eic0** [comment]
I already spoke with another Collaborator in this PR (#16536) about just changing the contract address, since we paid the fee already for this token.

**Comment by Cryptocool1** [comment]
You need to pay the fee for migration.

**Comment by eic0** [comment]
Why? It's just a replacement of the token to a new contract, since you depreciate the old token. We paid already for the listing of this token.

**Pull request closed without merging**
