### PR TITLE
Add info & Logo

### PR DESCRIPTION
**Pull request by SafeCapToken**

### CODE REVIEW

**Comment by Cryptocool1** [comment]
correction needed:
Contract is not in checksum format, should be 0x6bbf411a9a50ef4427d64d1Ea74ad294c2BBb0c8

**Comment by SafeCapToken** [comment]
Please info & logo add my token

**Comment by SafeCapToken** [comment]
Hello Sir

**Comment by SafeCapToken** [comment]
Please info & logo add my token

**Comment by Cryptocool1** [comment]
info file should be named info.json. not Info.json

**Comment by SafeCapToken** [comment]
info.json

**Comment by SafeCapToken** [comment]
check now

**Comment by SafeCapToken** [comment]
{
    "name": "SafeCap Token",
    "type": "BEP20",
    "symbol": "SFC",
    "decimals": 18,
    "website": "https://safecap.org/",
    "description": "SafeCap Binance Smart Chain based project. SafeCap is an enterprise-grade, service-centric platform that brings user-friendly blockchain experience to millions.\n",
    "explorer": "https://bscscan.com/token/0x6BBF411A9A50EF4427D64D1EA74AD294C2BBB0C8",
    "status": "active",
    "id": "0x6BBF411A9A50EF4427D64D1EA74AD294C2BBB0C8"
}

**Comment by SafeCapToken** [comment]
hello sir Help me

**Comment by Cryptocool1** [comment]
Contract is not in checksum format, should be 0x6bbf411a9a50ef4427d64d1Ea74ad294c2BBb0c8 (not 0x6BBF411A9A50EF4427D64D1EA74AD294C2BBB0C8). Please rename it.

**Comment by SafeCapToken** [comment]
{
    "name": "SafeCap Token",
    "type": "BEP20",
    "symbol": "SFC",
    "decimals": 18,
    "website": "https://safecap.org/",
    "description": "SafeCap Binance Smart Chain based project. SafeCap is an enterprise-grade, service-centric platform that brings user-friendly blockchain experience to millions.\n",
    "explorer": "https://bscscan.com/token/0x6bbf411a9a50ef4427d64d1Ea74ad294c2BBb0c8",
    "status": "active",
    "id": "0x6bbf411a9a50ef4427d64d1Ea74ad294c2BBb0c8"
}

**Comment by SafeCapToken** [comment]
File ok?

**Comment by SafeCapToken** [comment]
again check Please

**Comment by SafeCapToken** [comment]
Hello Sir

**Comment by Cryptocool1** [comment]
can't find contract on your website

**Comment by SafeCapToken** [comment]
Screenshot 2021-07-01 152812


Cleck Now

**Comment by SafeCapToken** [comment]
Open Contract click now

**Comment by Cryptocool1** [comment]
great! thanks

**Comment by SafeCapToken** [comment]
Thanks Sir

**Pull request merged**
