### PR TITLE
Add APE INU Logo and Info

### PR DESCRIPTION
**Pull request by ApeInu**

### CODE REVIEW

**Comment by Cryptocool1** [comment]
- Correction needed: 
 ExplorerUrl incorrect, should be standard https://bscscan.com/token/0xAe0D2cC54e4821D8aec9aDd89125B70d34Ac906e, not https://bscscan.com/address/0xae0d2cc54e4821d8aec9add89125b70d34ac906e.
 please correct

**Comment by Cryptocool1** [comment]
hello,
cannot find your contract on website. 
please check

**Comment by ApeInu** [comment]
> 
> 
> hello,
> cannot find your contract on website.
> please check

Hi Cryptocool1,

We have just updated the website with correct buy and chart links. Thanks for checking!

Best Regards,

Ape Inu Team

**Comment by ApeInu** [comment]
> 
> 
> hello,
> cannot find your contract on website.
> please check

We have also added bscscan link

**Comment by Cryptocool1** [comment]
> > hello,
> > cannot find your contract on website.
> > please check
> 
> We have also added bscscan link

Great! Thanks.

**Pull request merged**
