### PR TITLE
pull code

### PR DESCRIPTION
**Pull request by vinhphamdev**

### CODE REVIEW

**Comment by zachzwei** [comment]
Please do not put the info.json and logo.png on another folder. 
This will not be accepted on the repo.
Correcting it now.

**Comment by vinhphamdev** [comment]
hi, i have removed folder , pls approve my pull request. because my logo display on app was be cropped

**Comment by vinhphamdev** [comment]
@zachzwei hi, i have sent 1 bnb before, now i need update my logo. pls approve my pull request

**Comment by catenocrypt** [comment]
> @zachzwei hi, i have sent 1 bnb before, now i need update my logo. pls approve my pull request

@vinhphamdev , can you show txID or the PR number for which you have paid?

**Comment by vinhphamdev** [comment]
txID: 603F97C438A0B08721EC7B635E54C212C2AE28356D8AEC40C43EC9B223F0E369. pls check!

**Comment by catenocrypt** [comment]
Fee was paid for PR 2269 (original submission), which was merged.
This is a new PR, which requires new payment, sorry.

https://github.com/trustwallet/assets/pull/2269

**Comment by vinhphamdev** [comment]
Oh , because my logo display on app was be cropped . That’s why i want
update my logo . Pls

**Comment by zachzwei** [comment]
Making exception on this one. Please be careful when submitting PRs.

**Comment by vinhphamdev** [comment]
many thanks

**Pull request merged**
