### PR TITLE
Add SAFE & SECURE WALLET (BEP20)

### PR DESCRIPTION
**Pull request by saswallets**
This PR is being closed due to inactivity. If you wish to continue, please have us reopen the PR before sending your payment, or just create a new one.
Do NOT send payments for closed PR, as the fee may by lost!
  (48 vs. 48 hrs)

### CODE REVIEW

**Comment by saswallets** [comment]
Replace old contract  0x4Cb45cd848180ea1Fbd73B85B1DEB3172D49574d 
with new contract.

**Comment by saswallets** [comment]
Old Repository 
https://github.com/trustwallet/assets/pull/9351

**Comment by saswallets** [comment]
Replace old contract 
0xcFDC1e2c7F4B40cFb3632188d6F766309151b7b8

With new contract 
0x4cb45cd848180ea1fbd73b85b1deb3172d49574d

**Comment by Cryptocool1** [comment]
цhere can we find an official information about replacing the old contract?

**Comment by saswallets** [comment]
> where can we find an official information about replacing the old contract?

https://www.facebook.com/saswalletsofficial/?ref=page_internal
https://twitter.com/SasWallets
https://www.linkedin.com/company/sas-wallets/about/
https://www.instagram.com/saswallets/

**Comment by Cryptocool1** [comment]
can't find the announcement about
Replace old contract
0xcFDC1e2c7F4B40cFb3632188d6F766309151b7b8

With new contract
0x4cb45cd848180ea1fbd73b85b1deb3172d49574d

**Comment by saswallets** [comment]
> can't find the announcement about
> Replace old contract
> 0xcFDC1e2c7F4B40cFb3632188d6F766309151b7b8
> 
> With new contract
> 0x4cb45cd848180ea1fbd73b85b1deb3172d49574d

Ohh K, it will be within 12 Hrs.

**Pull request closed without merging**
