### PR TITLE
Add Sphynx BSC (BEP20)

### PR DESCRIPTION
**Pull request by PaPacarlo13**
Adding info for BEP20 token 'Sphynx BSC'.

PR created by <a href="https://assets.trustwallet.com">TW Assets Management</a>

### CODE REVIEW

**Comment by cryptomanz** [comment]
Dear team, 
our token have migrated to new contract (official information about that you can find on our website)
https://bscscan.com/token/0xd38ec16caf3464ca04929e847e4550dcff25b27a#balances. — that is our old contract
https://bscscan.com/token/0xe64972c311840cfaf2267dcfd365571f9d9544d9 — our new contract 
we are legit token and have certik contract audit, you can see it here:
 https://www.certik.com/projects/sphynxtoken
there is also our whitepaper:
 https://sphynxtoken.co/static/media/whitepaper.42fdf279.pdf
you can also find our roadmap on our website!
We are also ready to answer your questions:
- We will benefit users by our many Cross-chain uses for farming, trading and staking. 
And providing users a more simple and faster UI. 
- The token has not been distributed by airdrop.
- We did not have a Presale. 
- We are currently listed on Pancakeswap V2
- we have certik audit  https://www.certik.com/projects/sphynxtoken

**Comment by PaPacarlo13** [comment]
Dear team, 
our token have migrated to new contract (official information about that you can find on our website)
https://bscscan.com/token/0xd38ec16caf3464ca04929e847e4550dcff25b27a#balances. — that is our old contract
https://bscscan.com/token/0xe64972c311840cfaf2267dcfd365571f9d9544d9 — our new contract 
we are legit token and have certik contract audit, you can see it here:
 https://www.certik.com/projects/sphynxtoken
there is also our whitepaper:
 https://sphynxtoken.co/static/media/whitepaper.42fdf279.pdf
you can also find our roadmap on our website!
We are also ready to answer your questions:
- We will benefit users by our many Cross-chain uses for farming, trading and staking. 
And providing users a more simple and faster UI. 
- The token has not been distributed by airdrop.
- We did not have a Presale. 
- We are currently listed on Pancakeswap V2
- we have certik audit  https://www.certik.com/projects/sphynxtoken

**Comment by Cryptocool1** [comment]
hello, 
do you have another official announcement about migration?

**Comment by PaPacarlo13** [comment]
Sure, 
You can find the announcment in our twitter 
https://twitter.com/SphynxSwap/status/1471903226081562633

**Pull request merged**
