### PR TITLE
Update logo for $EGC

### PR DESCRIPTION
**Pull request by Cryptonaire01**
Hello,

Please update the logo for $EGC 

I have attached the new logo

Thanks!

### CODE REVIEW

**Comment by Cryptonaire01** [comment]
Hello,
Is there anything needed from my side?

**Comment by Cryptonaire01** [comment]
[info.zip](https://github.com/trustwallet/assets/files/7687307/info.zip)

**Comment by Cryptonaire01** [comment]
New logo is still not updated in TW

**Comment by Cryptonaire01** [comment]
Hello,
Unfortunately, the old logo still shows up in Trust Wallet!

**Comment by Cryptocool1** [comment]
Hello, can you send your new logo here?

**Comment by Cryptonaire01** [comment]
logo

**Comment by Cryptonaire01** [comment]
Hello, can you confirm once the new logo is updated?

**Comment by Cryptonaire01** [comment]
Any updates?

**Comment by Cryptonaire01** [comment]
Hello,
Unfortunately, the old logo still shows up in Trust Wallet!

**Comment by Cryptocool1** [comment]
The logo updated

**Comment by Cryptonaire01** [comment]
Hi, we checked the trust wallet and it's still showing the old logo - see screenshot
image

**Comment by Cryptonaire01** [comment]
Please make sure the new logo is updated to be aligned with our current branding
People started to FUD on us because we promised to make the changes months ago
Really appreciate your support! 
logo

**Comment by Cryptonaire01** [comment]
Hello, any updates? Please update our logo, this is pending for months now.
This is the worst customer service I have ever interacted with :)

**Comment by Cryptonaire01** [comment]
Hello, any updates? Please update our logo, this is pending for months now.
This is the worst customer service I have ever interacted with :)

**Pull request merged**
