### PR TITLE
Add BIGH BULL (BEP20)

### PR DESCRIPTION
**Pull request by BighBullTech**
Adding info for BEP20 token 'BIGH BULL'.

PR created by <a href="https://assets.trustwallet.com">TW Assets Management</a>

### CODE REVIEW

**Comment by BighBullTech** [comment]
Fees Paid

**Comment by BighBullTech** [comment]
Pls use this logo for PR18778 if Possible. 
pls pls pls

Old Logo

**Comment by BighBullTech** [comment]
Pls https://github.com/Cryptocool1, https://github.com/cryptomanz,
https://github.com/Iamdeadlyz use this logo for PR18778 if Possible.
pls pls pls[image: Old Logo.png]

**Comment by BighBullTech** [comment]
Pls process early as possible.
As you know we are facing same logo problem from last 3 days.

**Comment by BighBullTech** [comment]
How much time wait...

**Comment by Cryptocool1** [comment]
hello, we deleted logo for your old contract
Image from iOS (1)

**Comment by Cryptocool1** [comment]
we don't add the logos for old contracts, we just delete them

**Comment by BighBullTech** [comment]
How our all wallet visible. 

See live picture

**Comment by Cryptocool1** [comment]
once again, you need to clear your cache.

**Comment by BighBullTech** [comment]
I am so many time clear cache 
& Every user have visible our old logo

What is the solution, we are very much disappointed from these logo

**Comment by unanoc** [comment]
image
image

@BighBullTech I have just opened your token by old contract address and I don't see the logo. I don't know how you need to clear your cache but I took a new device for checking your token now.

**Comment by BighBullTech** [comment]
Can you replace/edit our logo in PR18698 
So we will be adjusted old & new logo 
 Pls see both logo 

IMG_20220307_181604
Screenshot_2022-03-07-18-15-29-92_99c04817c0de5652397fc8b56c3b3817

**Comment by BighBullTech** [comment]
I don't know, what is going, but we are very much disturbing from both logo looks like same 
IMG_20220307_181954


Can you replace attached Logo for PR18698

**Comment by BighBullTech** [comment]
Our wallet shows like this
IMG_20220307_182138

**Comment by BighBullTech** [comment]
Can I generate another PR for Again Change for New Logo in PR18698 for use fees of this PR 18778 

And after changes will be different in our new logo & logo, New logo with Name looking purely different.. 

Ok

**Comment by BighBullTech** [comment]
Can I create New PR for Edit our Existing Logo, who is Available in PR18698 & fees will be Adjust from current PR18778.

Is it Possible? 
I think it is best way to go ahead.

**Comment by unanoc** [comment]
you can replace the logo of the new contract if you want.

have you tried to open your old and new contracts on a new device? I assume there is a problem with the cache on your site. We don't see this logo anymore in the app because it was removed after migration.

**Comment by BighBullTech** [comment]
I am agree with you but we have around 37K + users, only in new users wallet have new logo, rest all users get both logo. 

And our main concern to create different between both logo otherwise no need to delete old logo. 

Thanks I am creating new PR

**Comment by BighBullTech** [comment]
Pls Consider New PR18790  https://github.com/trustwallet/assets/pull/18790

Regards

**Comment by BighBullTech** [comment]
Pls Merge New PR https://github.com/trustwallet/assets/pull/18790 
Early as possible...

**Comment by BighBullTech** [comment]
Pls Consider New PR18790 https://github.com/trustwallet/assets/pull/18790
Fees collect from current PR18778
Pls merge PR18790 (Early as Possible) 
We have already 4 days delayed.

Regards

**Comment by BighBullTech** [comment]
Pls Consider PR for Replace logo in Old contract, You can consider it for few days, because we have 37K + users, and this situation we don't have any solution to manage all user's Panic. & also there is some chance to scam by old users to transfer old coin to anyone because old contract shows still visible logo in wallet.

 otherwise give me any best solution. it urgent

**Comment by Cryptocool1** [comment]
We have already removed your old logo. The info about your old contract is not visible

**Comment by Cryptocool1** [comment]
Please clear your cache.

**Comment by BighBullTech** [comment]
how can 37K+ users clear cache,

**Comment by BighBullTech** [comment]
what about our Fees

**Comment by BighBullTech** [comment]
Hello I am asking about fees.

**Comment by Cryptocool1** [comment]
Please, don’t spam. We did the migration for your old token.

**Comment by BighBullTech** [comment]
You will be adjust, for changes in New Logo if yes.

Final reply.

**Comment by BighBullTech** [comment]
agree but i paid 2 time fees. so i am asking new fees who is PR18778

**Comment by BighBullTech** [comment]
It's not scam, it's biggest issue we are facing since last 5 days, if you can understand what we are facing. you will feel

**Comment by BighBullTech** [comment]
You had only 1 PR Migrated Not 2 PR, that's why i am asking about fees..

**Comment by BighBullTech** [comment]
Because we are facing same problem, because of both logo looks same as i sent screenshot to you. so we want finaly some changes in New Logo Looks like as attachments.
You will consider it as New PR with Fess (already Paid)

LOGO 256X256-12

**Comment by Cryptocool1** [comment]
Please have a look at my and my team’s Messages above.

**Comment by BighBullTech** [comment]
I am agree, but we are facing bigger issue to same logo.

Pls consider for changes in new logo.
Ok pls

**Comment by BighBullTech** [comment]
Can I create new PR 

Pls 
Support us because we don't have no solution...

**Comment by BighBullTech** [comment]
Can I create new PR

Pls
Support us because we don't have no solution...

**Comment by BighBullTech** [comment]
Reopen PR18790 
Pls consider fees for that

**Comment by BighBullTech** [comment]
Pls Consider new PR18790 
Against this Fees

**Comment by BighBullTech** [comment]
Pls consider this fees in PR18790 

https://github.com/trustwallet/assets/pull/18790

**Comment by BighBullTech** [comment]
Pls consider this fees in PR18790

https://github.com/trustwallet/assets/pull/18790

**Comment by BighBullTech** [comment]
Where is my fees, if you can't consider into PR18790 
Pls refund my payment...

**Pull request closed without merging**
