### PR TITLE
Add Rune Shards (RXS) (BEP20)

### PR DESCRIPTION
**Pull request by sm-dasset**
Adding info for BEP20 token 'Rune Shards'

This token was sharded from the Rune ($RUNE) token. You can see that there are over 10k holders of $RUNE, and they still need to migrate to RXS:

https://bscscan.com/token/0xa9776b590bfc2f956711b3419910a5ec1f63153e

### CODE REVIEW

**Comment by sm-dasset** [comment]
Please let me know if the number of holders is okay, considering it used to be 5k, and the token we are migrating from ($RUNE) has 14k+ holders, and those holders need to convert their tokens to $RXS.

**Comment by cryptomanz** [comment]
can you send an official announcement about migration ?

**Comment by sm-dasset** [comment]
> can you send an official announcement about migration ?

https://twitter.com/RuneMetaverse/status/1455918460764971012

https://runemetaverse.medium.com/rune-monthly-report-october-2021-bb31ffb67a49

**Comment by sm-dasset** [comment]
Is there anything else I can provide?

**Review by Hagan21 — COMMENTED** [review]
Your trusted crypto exchange

**Pull request merged**
