### PR TITLE
Add phoswap logo

### PR DESCRIPTION
**Pull request by phoswap**

### CODE REVIEW

**Comment by phoswap** [comment]
Fee paid Please check thank you!
https://explorer.binance.org/tx/1B92B8646CC4EEC47B8AB285900A4AB2E4DE8B0EFB217B2C0B45BECFF20B17CF

**Comment by phoswap** [comment]
Fee paid (Memo #4359 ) Phoswap logo
https://explorer.binance.org/tx/1B92B8646CC4EEC47B8AB285900A4AB2E4DE8B0EFB217B2C0B45BECFF20B17CF

**Comment by phoswap** [comment]
Fee Paid!
https://explorer.binance.org/tx/71A77A550256960EF6BA936DD05D098A882B111C305A4B80E4F58C97BDD5FE06

**Comment by phoswap** [comment]
Logo is not visible in Trust Wallet.

**Comment by catenocrypt** [comment]
Have you submitted request form as described here?

https://developer.trustwallet.com/add_new_asset#dapp-submission-and-listing-requirements

**Comment by phoswap** [comment]
We paid the fees twice for #4594 and #4359 but Phoswap logo is not visible in Trust Wallet. This has been a couple of weeks now. Thank you!

**Comment by phoswap** [comment]
Please upload Phoswap logo! Thank you!

Phoswap

**Comment by phoswap** [comment]
Hi Trustwallet/Assets
We would like refunds of two payment if you do not list Phoswap logo. It
has been a couple of months now! Thank you very much!
Phoswap Team

**Comment by catenocrypt** [comment]
Do you mean being added to the list of curated dApps?  Adding the logo is only one part of that.

**Comment by phoswap** [comment]
Just add the logo. Thanks!

**Pull request merged**
