### PR TITLE
Add MALOU TOKEN (BEP20)

### PR DESCRIPTION
**Pull request by ANNC247**
Adding info for BEP20 token 'MALOU TOKEN'.

PR created by <a href="https://assets.trustwallet.com">TW Assets Management</a>

### CODE REVIEW

**Comment by Cryptocool1** [comment]
• What is the purpose of this token? How will it benefit Trust Wallet users?
 • How is the token being distributed? Are you conducting an airdrop?
 • Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?
 • Is the token listed on a centralized/decentralized exchange?
 • Is a Smart Contract audit completed? Where can we find this information?

**Comment by ANNC247** [comment]
> • What is the purpose of this token? How will it benefit Trust Wallet users? • How is the token being distributed? Are you conducting an airdrop? • Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale? • Is the token listed on a centralized/decentralized exchange? • Is a Smart Contract audit completed? Where can we find this information?

What is the purpose of this token? How will it benefit Trust Wallet users?

The token is MEME currency, which is derived from a self-deprecating joke and aims to attract more self-deprecating people. It has a strong community and cultural following, which can bring more users and loyalty to Trust wallet.

• How is the token being distributed? Are you conducting an airdrop?

The token is launched fairly, there is no pre-sale, and there is no airdrop plan at present

• Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?
No

• Is the token listed on a centralized/decentralized exchange?
We are currently on Pancakeswap, but expect to be listed on a centralized exchange soon

• Is a Smart Contract audit completed? Where can we find this information?
We haven't audited it yet, but it will be done soon.

**Comment by ANNC247** [comment]
Actually we already featured in many wallets including Binance and okx,
We are also the winner of Binance chain memes competition.

https://x.com/bnbchain/status/1868269359548031008?s=46&t=-wLHW19zMDZ8Qh1qm9qdww

IMG_20241216_183611_336
IMG_20241216_182905_042
IMG_20241216_182905_034
IMG_20241216_182904_217

**Comment by ANNC247** [comment]
@Cryptocool1, @cryptomanz1 what is the status of our application?

**Comment by ANNC247** [comment]
Dear Trust Wallet Support,

We are writing to inquire about the status of our logo addition request for
MALOU TOKEN. We submitted all the necessary information on 15th of December
and would appreciate an update on when we can expect to see our logo added
to Trust Wallet.
Regards,
MALOU TOKEN TEAM.

**Comment by Cryptocool1** [comment]
After careful review of your submission, it looks like this token has not undergone any security audit. The request will be closed until further notice.

To know more about the token approval guidelines, please check this article: [How to Submit Token Logo](https://developer.trustwallet.com/listing-new-assets/requirements).

Feel free to re-open pull request once you meet those requirements.

**Pull request closed without merging**
