### PR TITLE
Adding Description/Logo to Fat Cat Killer

### PR DESCRIPTION
**Pull request by maxvolovikov**
Adding Description/Logo to Fat Cat Killer

### CODE REVIEW

**Comment by maxvolovikov** [comment]
@cryptomanz, updated. Hope this one works better. Thank you

**Comment by Cryptocool1** [comment]
As per our policy, brand new tokens are not included, there is a minimum requirement of 10,000 holder addresses and 15,000 transactions, in order to filter out scam tokens.
See the criteria at : https://developer.trustwallet.com/assets/requirements .

**Comment by maxvolovikov** [comment]
> As per our policy, brand new tokens are not included, there is a minimum requirement of 10,000 holder addresses and 15,000 transactions, in order to filter out scam tokens.
> 
> See the criteria at : https://developer.trustwallet.com/assets/requirements .

We actually trying to avoid any mistake that is why we want logo on wallet and pancake swap. We are kycd audited and have partnerships with multiple real world businesses. We are new but we had a few scammers attacking our investors pretending to be us or setting up same token ticker. Could you please consider adding us?  As I mentioned we are fully compliant and we are just trying to prevent our investors from getting burned. We are getting listed on Bitmart on or before 6/24 as well.

**Comment by Cryptocool1** [comment]
hello, 
feel free to create new PR once all criteria are met. You can mention this PR so the fee can be reused.

**Pull request closed without merging**
