### PR TITLE
Add MSWAP token logo

### PR DESCRIPTION
**Pull request by moneyswapoffcial**

### CODE REVIEW

**Comment by moneyswapoffcial** [comment]
Please register the token logo.

**Comment by catenocrypt** [comment]
As per our policy, brand new tokens are not included, there is a minimum requirement of 500 holder addresses and 1000 transactions, in order to filter out scam tokens.
See the criteria at (mentioned in the first message by the bot): https://community.trustwallet.com/t/how-to-submit-a-token-logo/3863#how-to-get-approved
This token has no real usage yet (11). Putting PR on hold. Please come back to us when all criteria are met.

https://etherscan.io/token/0x020D5E6fEC03D0144A2681CFC0fD3C9255d6d7c2

**Comment by moneyswapoffcial** [comment]
Okay. I'll answer again after meeting the criteria you told me. 
(500 holder addresses and 1000 transactions)

**Comment by vikmeup** [comment]
Feel free to re-open pull request when you meet criteria.

**Pull request closed without merging**
