### PR TITLE
Add AUR icon and token info

### PR DESCRIPTION
**Pull request by 0xyPhilic**
This PR is being closed due to inactivity. If you wish to continue, please have us reopen the PR before sending your payment, or just create a new one.
Do NOT send payments for closed PR, as the fee may by lost!
  (48 vs. 48 hrs)

### CODE REVIEW

**Comment by Cryptocool1** [comment]
- Contract is not in checksum format, should be 0x94183cfAcFacA73BA36A12a4cd7775fdAe5FED69 
- As per our policy, brand new tokens are not included, there is a minimum requirement of 2500 holder addresses and 5000 transactions, in order to filter out scam tokens.
See the criteria at (mentioned in the first message by the bot): https://community.trustwallet.com/t/how-to-submit-a-token-logo/3863).
Closing PR for now. Please come back to us when all criteria are met.

**Comment by SayWhatDev** [comment]
> * Contract is not in checksum format, should be 0x94183cfAcFacA73BA36A12a4cd7775fdAe5FED69
> * As per our policy, brand new tokens are not included, there is a minimum requirement of 2500 holder addresses and 5000 transactions, in order to filter out scam tokens.
>   See the criteria at (mentioned in the first message by the bot): https://community.trustwallet.com/t/how-to-submit-a-token-logo/3863).
>   Closing PR for now. Please come back to us when all criteria are met.

A quick question on this. We have adjusted the address to be a checksum address. However this token is an expiry token, meaning that it will be used for a certain time frame (as ex. 3 months). Due to the nature of the token and usage it most likely won't be possible to ever reach 2500 holders and 5000 transactions. The token would be fully burned after the period and a new token will be issued for the next period (similar to futures). Given this situation isn't there another requirement your team has or should have, otherwise such types of futures tokens will never fulfill the above criteria?

**Comment by Cryptocool1** [comment]
corrections needed:
- type should be "ERC20" not "ERC-20"
- Contract is not in checksum format, should be 0x94183cfAcFacA73BA36A12a4cd7775fdAe5FED69

**Comment by SayWhatDev** [comment]
> corrections needed:
> 
> * type should be "ERC20" not "ERC-20"
> * Contract is not in checksum format, should be 0x94183cfAcFacA73BA36A12a4cd7775fdAe5FED69

Thanks. All issues addressed :)

**Comment by Cryptocool1** [comment]
As per our policy, brand new tokens are not included, there is a minimum requirement of 2500 holder addresses and 5000 transactions, in order to filter out scam tokens.
See the criteria at (mentioned in the first message by the bot): https://community.trustwallet.com/t/how-to-submit-a-token-logo/3863).
Closing PR for now. Please come back to us when all criteria are met.

**Pull request closed without merging**
