### PR TITLE
Added Rebuschain

### PR DESCRIPTION
**Pull request by nicolam1**
Creating this PR to add Rebuschain to the supported blockchain.

### CODE REVIEW

**Comment by hewigovens** [comment]
We need to fix our CI before merging

**Comment by hewigovens** [comment]
We need to fix our CI before merging

**Comment by hewigovens** [comment]
@Milerius I will let you decide if we should add this

**Comment by nicolam1** [comment]
@hewigovens @Milerius any updates on this?

**Comment by Milerius** [comment]
> @Milerius I will let you decide if we should add this

I do not think we should add this chain for now

**Comment by Milerius** [comment]
we will consider adding it later or via custom network support!

**Comment by nicolam1** [comment]
@Milerius any reason why the PR was closed?

**Comment by Milerius** [comment]
> @Milerius any reason why the PR was closed?

we will consider adding it later or via custom network support

**Pull request closed without merging**
