### PR TITLE
Add Flap Coin (BEP20)

### PR DESCRIPTION
**Pull request by flappybirdgo**
Adding info for BEP20 token 'Flap Coin'.

PR created by <a href="https://assets.trustwallet.com">TW Assets Management</a>

### CODE REVIEW

**Comment by Cryptocool1** [comment]
As per our policy, brand new tokens are not included, there is a minimum requirement of 5,000 holder addresses and 10,000 transactions, in order to filter out scam tokens.
See the criteria at : https://developer.trustwallet.com/assets/requirements .

**Comment by flappybirdgo** [comment]
can i pull request again ?

**Comment by Cryptocool1** [comment]
> can i pull request again ?

please come back to us when all criteria are met. make sure to mention this PR, so the fee can be reused

**Comment by flappybirdgo** [comment]
> > can i pull request again ?
> 
> please come back to us when all criteria are met. make sure to mention this PR, so the fee can be reused

sure, now our project met the criteria.

**Comment by flappybirdgo** [comment]
#17735

**Comment by flappybirdgo** [comment]
reopen #17735 
@Cryptocool1 @cryptomanz

**Pull request closed without merging**
