### PR TITLE
Pr/1874

### PR DESCRIPTION
**Pull request by kolya182**
Close https://github.com/trustwallet/assets/pull/1874

### CODE REVIEW

**Comment by likeappofc18** [comment]
Done paid 1000 TWT Again , please update logo sir, thanks

**Comment by likeappofc18** [comment]
hello sir, the logo is not updated we have already paid a total of 2000 TWT

**Comment by kolya182** [comment]
> hello sir, the logo is not updated we have already paid a total of 2000 TWT

Updated

**Comment by likeappofc18** [comment]
Thanks sir :)

**Pull request merged**
