### PR TITLE
NRG Added logo and info

### PR DESCRIPTION
**Pull request by LeonDolinar**

### CODE REVIEW

**Comment by Iamdeadlyz** [comment]
As per our policy, brand new tokens are not included. There is a minimum requirement of 500 holder addresses and 1000 transactions in order to filter out scam tokens. See the criteria at (mentioned in the first message by the bot): https://community.trustwallet.com/t/how-to-submit-a-token-logo/3863#how-to-get-approved

This token has below-limit usage yet. This pull request will be put on hold. Please come back to us when all criteria are met.
https://etherscan.io/token/0x1416946162b1c2c871a73b07e932d2fb6c932069 (10, 28)

**Comment by zachzwei** [comment]
As far as I know NRG or Energi has its own blockchain and will not be an ERC20 token.
https://medium.com/energi/energi-3-0-coin-migration-d0da482cecd5
Energi will breakthrough yet another huge milestone with the launch of Energi 3.0. In Q4 2019, Energi will fully transition to an Ethereum-based smart contract platform, compatible with Decentralized Applications (dApps) written for Ethereum. Energi will not be turned into an ERC20 token, but rather be an equivalent to ETH, with the ability to have ERC20 tokens compatible with our platform.

**Comment by LeonDolinar** [comment]
Correct. We have created NRGT (Energi Token), which is an equivalent to NRG (Energi), but resides on the ETH network. The users are able to buy it and claim the same amount on the Energi blockchain. In other words, we have created cross-chain bridge between two networks (something akin to atomic swaps). Since this is a slightly different situation than the usual, I kindly ask that this is taken into consideration when making a final decision. The minimum requirements, from a token standpoint of view, will be met rapidly. Thank you!

**Comment by zachzwei** [comment]
> Correct. We have created NRGT (Energi Token), which is an equivalent to NRG (Energi), but resides on the ETH network. The users are able to buy it and claim the same amount on the Energi blockchain. In other words, we have created cross-chain bridge between two networks (something akin to atomic swaps). Since this is a slightly different situation than the usual, I kindly ask that this is taken into consideration when making a final decision. The minimum requirements, from a token standpoint of view, will be met rapidly. Thank you!

Can you share specifics of this cross chain bridge? Is there any documentation we can refer to?

**Comment by LeonDolinar** [comment]
Basically, if a user sends more (or equal) to 1000 NRGT to a specific ETH address, our team will automatically send them the same amount of NRG on our blockchain to the address where they sent it from (the NRGT smart contract takes care of stuff on ETH network). Currently the process is semi-automatic, but we intend to fully automatize it in the future (as you know tech isn't simple and requires a lot of testing/auditing).

**Comment by LeonDolinar** [comment]
It seems the CI/CD fails, any pointers as to why. We've followed the instructions.

**Comment by Iamdeadlyz** [comment]
> It seems the CI/CD fails, any pointers as to why. We've followed the instructions.

To fix the checksum issue
- Rename the folder to `0x1416946162B1C2c871A73B07E932D2fB6C932069-x`, commit, then push
- Rename it again to `0x1416946162B1C2c871A73B07E932D2fB6C932069`, commit, and push

**Comment by vi-dangvu** [comment]
@Iamdeadlyz @zachzwei can we have an update on this?

**Comment by Iamdeadlyz** [comment]
> @Iamdeadlyz @zachzwei can we have an update on this?

Do you have a public link for the documentation? Or, perhaps, an official announcement regarding the ERC20 version of NRG?

**Comment by vi-dangvu** [comment]
@Iamdeadlyz The documentation is ready but not available publicly yet as we are waiting first to release the official announcement that will come very soon. Ideally we would like to have the logo updated before the official announcement as well. Is it possible?

On a side note, we have change our name from NRGT to NRGE (already reflected on etherscan) but it seems it is not updated yet on uniswap, may I ask  how we can do that?

**Comment by vi-dangvu** [comment]
@Iamdeadlyz @catenocrypt @zachzwei The contract address is updated as NRGE (https://etherscan.io/address/0x1416946162b1c2c871a73b07e932d2fb6c932069)  but the ticker on uniswap is incorrect (NRGT) -https://info.uniswap.org/token/0x1416946162b1c2c871a73b07e932d2fb6c932069.

We want to have this sorted out before we can announce the token release, could you please help us in getting this correct? Much appreciated!

**Comment by Iamdeadlyz** [comment]
> @Iamdeadlyz @catenocrypt @zachzwei The contract address is updated as NRGE (https://etherscan.io/address/0x1416946162b1c2c871a73b07e932d2fb6c932069) but the ticker on uniswap is incorrect (NRGT) -https://info.uniswap.org/token/0x1416946162b1c2c871a73b07e932d2fb6c932069.
> 
> We want to have this sorted out before we can announce the token release, could you please help us in getting this correct? Much appreciated!

The LP tokens are labeled as NRGT as well, it might take some time to reflect on the Uniswap properly.

**Comment by vi-dangvu** [comment]
@Iamdeadlyz Thanks Ian for having merged the logo! In regards to the ticker name, why do you say it sill take some time to have it reflected on uniswap ? Is there a way to speed up the process ?

**Comment by Iamdeadlyz** [comment]
> @Iamdeadlyz Thanks Ian for having merged the logo! In regards to the ticker name, why do you say it sill take some time to have it reflected on uniswap ? Is there a way to speed up the process ?

Apologies for the confusion, I was referring to the logo. Uniswap will only fetch the logo and other info. You have to coordinate with the Uniswap team regarding the update for the LP token ticker and other relevant details.

**Comment by vi-dangvu** [comment]
@Iamdeadlyz Would you have a contact that you can share to get resolved asap? I have a ticket opened on Discord already

**Comment by Iamdeadlyz** [comment]
> @Iamdeadlyz Would you have a contact that you can share to get resolved asap? I have a ticket opened on Discord already

Sorry, got no contact with them. Please wait for their response or you can request a follow-up.

**Comment by vi-dangvu** [comment]
@Iamdeadlyz In the trust wallet app, the token still shows the old ticker NRGT. Could you update it to NRGE?

Thanks,
Vi

image

**Comment by Iamdeadlyz** [comment]
> @Iamdeadlyz In the trust wallet app, the token still shows the old ticker NRGT. Could you update it to NRGE?
> 
> Thanks,
> Vi
> 
> image

Hi @vi-dangvu, it should be updated now. Please check.

**Comment by vi-dangvu** [comment]
@Iamdeadlyz Thank you, it is indeed corrected. Much appreciated!

**Pull request merged**
