### PR TITLE
add Rocket Boys (BEP20)(Payed in #11803)

### PR DESCRIPTION
**Pull request by isBASED**
adding logo + info for Rocket Boys

### CODE REVIEW

**Comment by isBASED** [comment]
@ Cryptocool1
New pull request for [#11803](https://github.com/trustwallet/assets/pull/11803)

**Comment by isBASED** [comment]
Q: What is the purpose of this token? How will it benefit Trust Wallet users?
A: RBOYS will be used to gain entry on ICO’s that will be held on our upcoming Launchpad, holding a specific about of RBOYS will give you a guaranteed spot in some of the future tokens that will be launched on our Platform. We also have a buyback system, and a reward system that rewards holders with hourly BUSD payouts. ( The payout will be automatically transferred to the holders wallet when the payout amount reached at least $1 BUSD, the more tokens you hold the better the payout)

Q: How is the token being distributed? Are you conducting an airdrop?
A: We raised 1000BNB in a private presale, 3000BNB in a public presale, and successfully launched on PancakeSwap on July 14th.

Q: Did you sell the tokens at an Initial Coin Offering (ICO) or a token presale?
A: Yes, we sold 4000BNB worth of tokens in our presale before launching on Pancakeswap.

Q: Is the token listed on a centralized/decentralized exchange?
A: The token can be bought & traded on PancakeSwap. We will be looking to get on more exchanges and easier facilitate buying in the near future.

Q: Is a Smart Contract audit completed? Where can we find this information?
A: Yes, we are audited by Techrate, the audit can be found [here.](https://github.com/TechRate/Smart-Contract-Audits/blob/main/Rocket%20Boys%20Full%20Smart%20Contract%20Security%20Audit.pdf)

**Comment by cryptomanz** [comment]
can you please add links to your PR?
example: https://developer.trustwallet.com/add_new_asset#info-json-contents

**Comment by isBASED** [comment]
> can you please add links to your PR?
> example: https://developer.trustwallet.com/add_new_asset#info-json-contents

Do you want me to post it here or add it into the JSON file ?

https://github.com/trustwallet/assets/pull/11803
👆 this is the PR, I already posted it up here but the link turns into a hashtag.

**Comment by isBASED** [comment]
> can you please add links to your PR?
> example: https://developer.trustwallet.com/add_new_asset#info-json-contents

I've added the links 👍

**Review by smercan89 — APPROVED** [review]

**Review by smercan89 — APPROVED** [review]

**Pull request merged**
