### PR TITLE
Add SOMIDAX (BEP20)

### PR DESCRIPTION
**Pull request by somidax**
Adding info for BEP20 token 'SOMIDAX'.

PR created by <a href="https://assets.trustwallet.com">TW Assets Management</a>

### CODE REVIEW

**Comment by somidax** [comment]
SOMIDAX Description,
SOMIDAX is offering a decentralized social interactive marketplace service platform that utilizes innovative technology to create a new business model for social P2P interaction as well as buying and selling of products and service.
Marketplace - https://marketplace.somidax.net/

Library - https://library.somidax.net/

Media-app - https://studio.somidax.net/

**Comment by Cryptocool1** [comment]
Hello,
Your description field is too long, please compact it. (max is 500)

**Comment by somidax** [comment]
SOMIDAX is offering a decentralized social interactive marketplace service platform for buying and selling..
Marketplace - https://marketplace.somidax.net/
Library - https://library.somidax.net/
Media-app - https://studio.somidax.net/

**Comment by somidax** [comment]
> Hello,
> Your description field is too long, please compact it. (max is 500)

Description have been updated

**Comment by somidax** [comment]
> Hello,
> Your description field is too long, please compact it. (max is 500)

SOMIDAX is offering a decentralized social interactive marketplace service platform that utilizes innovative technology to create a new business model for social P2P interactions.
Marketplace - https://marketplace.somidax.net/
Library - https://library.somidax.net/
Media-app - https://studio.somidax.net/

**Comment by catenocrypt** [comment]
As per our policy, brand new tokens are not included, there is a minimum requirement of 2500 holder addresses and 5000 transactions, in order to filter out scam tokens.
See the criteria at (mentioned in the first message by the bot): https://community.trustwallet.com/t/how-to-submit-a-token-logo/3863).
This token has no real usage yet (only 1 holder address!). Closing PR for now. Please come back to us when all criteria are met.  Multi-chain and staking tokens may get special treatment, let us know if this is the case. 

https://bscscan.com/token/0xEA8c5B9c537f3ebBcc8F2df0573F2d084E9e2BDb

**Comment by somidax** [comment]
> As per our policy, brand new tokens are not included, there is a minimum requirement of 2500 holder addresses and 5000 transactions, in order to filter out scam tokens.
> See the criteria at (mentioned in the first message by the bot): https://community.trustwallet.com/t/how-to-submit-a-token-logo/3863).
> This token has no real usage yet (only 1 holder address!). Closing PR for now. Please come back to us when all criteria are met. Multi-chain and staking tokens may get special treatment, let us know if this is the case.
> 
> https://bscscan.com/token/0xEA8c5B9c537f3ebBcc8F2df0573F2d084E9e2BDb

This is an evolving project and you can see from our description of real world value in  what we offer to clients around the world Marketplace - https://marketplace.somidax.net/, Library - https://library.somidax.net/, Media-app - https://studio.somidax.net/(NFT hub). 
But due to high gas fee, we have created the SOMIDAX BEP20 (https://bscscan.com/token/0xEA8c5B9c537f3ebBcc8F2df0573F2d084E9e2BDb) base on community request as this already has a corresponding ERC20 token ( https://etherscan.io/token/0x7e8539d1e5cb91d63e46b8e188403b3f262a949b)

You would have allowed us undergo the migration and redistribution to all and pending holders the the high gas fee affected. Creating /collaborating with a customer wallet service will help be of great value as we grow.
See Coinmarketcap - https://coinmarketcap.com/currencies/somidax/wallets/

Redistribution will commence from 27th April  -  27th May , 2021  and we will update your team  after the event.

Kindly reopen tick to enable us proceed with distribution plans.

**Comment by catenocrypt** [comment]
We'd be able to include logo if higher circulation is already there.
Please not that it is possible to use the token with Trust Wallet even without the logo, and it is usable with Dapps like Pancakeswap too.

**Comment by somidax** [comment]
> We'd be able to include logo if higher circulation is already there.
> Please not that it is possible to use the token with Trust Wallet even without the logo, and it is usable with Dapps like Pancakeswap too.

Thanks for your response.
Having the logo on Trust wallet is of higher value to us as one of our official wallets on display and we would appreciate it been implemented as why we followed the process and paid for it.
If you check, the redistribution have started inline with our plans from when u last saw it. 
We have also shared the SOMIDAX BEP20 contract so users so they will add it to receive a 1:1 .
Also, the ticket price not reflecting price for  which We  will appreciate this should be fixed just like the SOMIDAX ERC20 price showing as data obtained from coinmarketcap.
This is a continues process as we evolve and looking forward to greater collaboration with trust wallet.

**Comment by somidax** [comment]
kindly update our listing status 

Holders: 3,019 addresses
Tx: 5,030



> We'd be able to include logo if higher circulation is already there. Please not that it is possible to use the token with Trust Wallet even without the logo, and it is usable with Dapps like Pancakeswap too.

**Pull request closed without merging**
