### PR TITLE
Adding $HUP Logo and Info

### PR DESCRIPTION
**Pull request by ghost**
Request to add $HUP Logo and Info as we meet criteria.

### CODE REVIEW

**Review by HUPLIFE — COMMENTED** [review]
approce

**Review by HUPLIFE — COMMENTED** [review]
approved

**Review by HUPLIFE — COMMENTED** [review]
approved

**Review by HUPLIFE — COMMENTED** [review]
approved

**Review by HUPLIFE — COMMENTED** [review]
changed

**Review by HUPLIFE — COMMENTED** [review]
CHANGED

**Review by HUPLIFE — COMMENTED** [review]
apprved

**Comment by HUPLIFE** [comment]
Booyah! Finally got it all right this time. Thx. Please merge.

**Review by HUPLIFE — COMMENTED** [review]
changed

**Comment by Cryptocool1** [comment]
can you please add links to your PR?
example: https://developer.trustwallet.com/add_new_asset#info-json-contents

**Review by HUPLIFE — COMMENTED** [review]
changed

**Comment by HUPLIFE** [comment]
> can you please add links to your PR?
> example: https://developer.trustwallet.com/add_new_asset#info-json-contents

ok NOW should be good @Cryptocool1

**Review by HUPLIFE — COMMENTED** [review]
approved

**Comment by HUPLIFE** [comment]
We will to update the logo to this: https://u.pcloud.link/publink/show?code=XZeK3KXZQt0V1izwnD7STp24PWnvU5VgwCr7

Are you able to do this or do we have to submit a new pull request with new fee?

**Pull request merged**
