### PR TITLE
Add Metaverse (BEP20)

### PR DESCRIPTION
**Pull request by g909960614**
Adding info for BEP20 token 'Metaverse'.

PR created by <a href="https://assets.trustwallet.com">TW Assets Management</a>

### CODE REVIEW

**Comment by g909960614** [comment]
image
#19083 has been paid

**Comment by cryptomanz** [comment]
• What is the purpose of this token? How will it benefit Trust Wallet users?
 • How is the token being distributed? Are you conducting an airdrop?
 • Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?
 • Is the token listed on a centralized/decentralized exchange?
 • Is a Smart Contract audit completed? Where can we find this information?

**Comment by g909960614** [comment]
• What is the purpose of this token? How will it benefit Trust Wallet users?
Trust Wallet users can put tokens in Trust Wallet, because Trust Wallet is the safest
• How is the token being distributed? Are you conducting an airdrop?
game wallet, development wallet,  marketing wallet, there is no airdrop
• Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?
No
• Is the token listed on a centralized/decentralized exchange?
PancakeSwapV2 listed
• Is a Smart Contract audit completed? Where can we find this information?
Yes

**Comment by Cryptocool1** [comment]
can you send your audit here?

**Comment by g909960614** [comment]
> can you send your audit here?

Certik audit is submitted

**Comment by g909960614** [comment]
> can you send your audit here?

You can check the contract, is absolutely safe, liquidity has been locked for 100 years

**Comment by Cryptocool1** [comment]
please see our requirements about the audit here: https://developer.trustwallet.com/assets/requirements

**Comment by Cryptocool1** [comment]
awaiting for smart contract audit, on hold for now

**Comment by g909960614** [comment]
> 等待智能合约审计，暂时搁置

ok，thanks

**Comment by g909960614** [comment]
> awaiting for smart contract audit, on hold for now

ok，thanks

**Comment by Cryptocool1** [comment]
come back to us when all criteria are met. make sure to mention this PR so the fee can be reused.

**Pull request closed without merging**
