### PR TITLE
Add The new Tellor token Address

### PR DESCRIPTION
**Pull request by krasi-georgiev**
This PR is being closed due to inactivity. If you wish to continue, please have us reopen the PR before sending your payment.
Do NOT send payments for closed PR, as the fee may by lost!
  (89 vs. 60 hrs)

### CODE REVIEW

**Comment by catenocrypt** [comment]
As per our policy, brand new tokens are not included, there is a minimum requirement of 2500 holder addresses and 5000 transactions, in order to filter out scam tokens.
See the criteria at (mentioned in the first message by the bot): https://community.trustwallet.com/t/how-to-submit-a-token-logo/3863).
This token has low usage yet (99). Closing PR for now. Please come back to us when all criteria are met.  Multi-chain and staking tokens may get special treatment, let us know if this is the case. 

https://etherscan.io/token/0x88dF592F8eb5D7Bd38bFeF7dEb0fBc02cf3778a0

**Comment by krasi-georgiev** [comment]
Did you read the description? 
The old contract is migrated to this new one.

**Comment by catenocrypt** [comment]
OK, sorry, thanks for the clarification, reopened.

**Comment by catenocrypt** [comment]
Submission OK; fee payment pending.

**Pull request closed without merging**
