### PR TITLE
shibelon trustwallet logo

### PR DESCRIPTION
**Pull request by monkey-shanti**
prev. pull request, #16358, payment already made

we now meet the trust wallet requirement of 10,000 holders and 15,000 transactions.

### CODE REVIEW

**Comment by monkey-shanti** [comment]
payment already done with prev. pull request
https://github.com/trustwallet/assets/pull/16358

**Review by monkey-shanti — COMMENTED** [review]
added tags

**Comment by monkey-shanti** [comment]
added tags

**Comment by monkey-shanti** [comment]
> can you please add tags?

tags added!

**Comment by Cryptocool1** [comment]
• Is a Smart Contract audit completed? Where can we find this information?

**Comment by cryptomanz** [comment]
Please come back to us when all criteria are met.
When creating a new PR make sure to mention this PR, so that we can see that fee has been paid already here.

**Pull request closed without merging**
