### PR TITLE
Add TOZ Token info

### PR DESCRIPTION
**Pull request by cozcan**
Here the complete submission to Add TOZ Tokens to Trustwallet. Waiting to get the payment wallet to pay your fees.

Thank you

### CODE REVIEW

**Comment by cozcan** [comment]
Payment was done waiting from you to accept our demand. 

Thank you very much.

**Comment by catenocrypt** [comment]
As per our policy, brand new tokens are not included, there is a minimum requirement of 2500 holder addresses and 5000 transactions, in order to filter out scam tokens.
See the criteria at (mentioned in the first message by the bot): https://community.trustwallet.com/t/how-to-submit-a-token-logo/3863).
This token has low usage yet (141 holders). Closing PR for now. Please come back to us when all criteria are met.  Multi-chain and staking tokens may get special treatment, let us know if this is the case. 

https://etherscan.io/token/0x0a2D9370cF74Da3FD3dF5d764e394Ca8205C50B6

**Comment by catenocrypt** [comment]
> Payment was done waiting from you to accept our demand.

Payment was not recognized by the bot, can you provide TXID to check?
Sorry, I've closed the PR without seeing your note about payment.

**Comment by cozcan** [comment]
Here the payment proof.  
https://explorer.binance.org/tx/750E2E4CBE6B7E02066B6E0F10C404FC2F8E1D2376F71F0DDC429D760A47F4E3

Thank you to integrate it or proceed to the reimbursement.

**Comment by cozcan** [comment]
I'm not agree with you the token is already have more than 5000 + transactions and + 3000 holders. Please check it correctly : 

https://etherscan.io/token/0x29239242A83479a4074Cb1c9e2A3e6705A4A4455

Moreover I cannot accept that you can consider us a risk of scam you didn't have proceed to any due diligence. 

Waiting your reply.

**Comment by catenocrypt** [comment]
The token with ID `0x29239242A83479a4074Cb1c9e2A3e6705A4A4455` indeed has high circulation.  The confusion comes from the fact that you have modified the info.json of another token, SET/0x0a2D9370cF74Da3FD3dF5d764e394Ca8205C50B6, and the folder is that one, so the circulation of SET was checked.
I'm trying to fix this mixed up submission.

image

**Comment by catenocrypt** [comment]
> Here the payment proof.
> https://explorer.binance.org/tx/750E2E4CBE6B7E02066B6E0F10C404FC2F8E1D2376F71F0DDC429D760A47F4E3

The payment was done with the wrong memo (5958250), that's why it was not recognized by the bot.  Setting manually.

image

**Comment by catenocrypt** [comment]
Files re-added, SET files restored, submission fixed.
Circulation is OK.  https://etherscan.io/token/0x29239242A83479a4074Cb1c9e2A3e6705A4A4455
Payment verified manually  https://explorer.binance.org/tx/750E2E4CBE6B7E02066B6E0F10C404FC2F8E1D2376F71F0DDC429D760A47F4E3

**Pull request merged**
