### PR TITLE
ANONINU files

### PR DESCRIPTION
**Pull request by anoninucoin**
PLease add logo and token details

### CODE REVIEW

**Review by Maxusz666 — APPROVED** [review]

**Comment by anoninucoin** [comment]
https://explorer.binance.org/tx/5A6B511DA488EEDC76E34348F7692317F3C811038DFF4C49400CAACCFDCCB783

**Comment by Cryptocool1** [comment]
This is a BEp20 token, correct folder is blockchains/smartchain/assets.

**Comment by anoninucoin** [comment]
The folder destination added as requested!

**Comment by cryptomanz** [comment]
Please create new PR, follow doc https://community.trustwallet.com/t/how-to-submit-a-token-logo/3863
You may want to try our Assets app in beta; go to https://assets.trustwallet.com, log on with Github, enter contract ID, logo and some additional info, and it will create a PR for you.
See https://community.trustwallet.com/t/how-to-submit-a-token-logo-using-assets-app/82957.

make sure to mention this PR so the fee can be reused

**Pull request closed without merging**
