### PR TITLE
add logo for freedom reserve

### PR DESCRIPTION
**Pull request by AcapSLP**
This PR is being closed due to inactivity. If you wish to continue, please have us reopen the PR before sending your payment.
Do NOT send payments for closed PR, as the fee may by lost!
  (118 vs. 60 hrs)

### CODE REVIEW

**Comment by AcapSLP** [comment]
Hi we paid the fee previously. https://explorer.binance.org/tx/9AD89AB7515C0E12EF47AB4DB2D587F5C8311A80D69909FF65A5430C5A1805C1

**Comment by AcapSLP** [comment]
@zachzwei

**Comment by AcapSLP** [comment]
> @AcapSLP, kind reminder: please pay fee: **1000 TWT** with the memo **4956** to the address `bnb1tqq9llyr3dyjd559dha6z5r5etk3qfwk07m098`.
> Alternatively, 6 BNB is also accepted (same memo & address).
> 
> **QR** code: [Trust](https://api.qrserver.com/v1/create-qr-code/?size=200x200&data=https%3A%2F%2Flink.trustwallet.com%2Fsend%3Fcoin%3D714%26address%3Dbnb1tqq9llyr3dyjd559dha6z5r5etk3qfwk07m098%26amount%3D1000%26memo%3D4956) | [other wallet](https://api.qrserver.com/v1/create-qr-code/?size=200x200&data=bnb1tqq9llyr3dyjd559dha6z5r5etk3qfwk07m098%26amount%3D1000%26memo%3D4956)
> See the [Pull Request Fee FAQ](https://developer.trustwallet.com/add_new_asset/pr-fee).

https://explorer.binance.org/tx/9AD89AB7515C0E12EF47AB4DB2D587F5C8311A80D69909FF65A5430C5A1805C1

**Comment by catenocrypt** [comment]
As per our policy, brand new tokens are not included, there is a minimum requirement of 2500 holder addresses and 5000 transactions, in order to filter out scam tokens.
See the criteria at (mentioned in the first message by the bot): https://community.trustwallet.com/t/how-to-submit-a-token-logo/3863).
This token low usage yet (342). Will close unless additional circulation proof is provided.

https://etherscan.io/token/0xC626e0619aC79AFEa9281c8eB9b1a9f9D3Fab532

**Comment by AcapSLP** [comment]
> As per our policy, brand new tokens are not included, there is a minimum requirement of 2500 holder addresses and 5000 transactions, in order to filter out scam tokens.
> See the criteria at (mentioned in the first message by the bot): https://community.trustwallet.com/t/how-to-submit-a-token-logo/3863).
> This token low usage yet (342). Will close unless additional circulation proof is provided.
> 
> https://etherscan.io/token/0xC626e0619aC79AFEa9281c8eB9b1a9f9D3Fab532

We are not a scam token. we have several hundred more holders off-chain within CCTip bot 
We are accepted by etherscan, and coinmarketcap and several other crypto trackers: Livecoinwatch, coinlib.
Our liquidity on uniswap is LOCKED https://etherscan.io/tx/0x99631760dd0dbb35499bb45f7891132a538106f94c582002da1949a696ad8a23
There is no possibility of removing liquidity.
Our info rating on Dextools is 100%

In addition, there is another token impersonating us on uniswap that IS a REAL scam they took our previous ticker during the airdrop phase (FRC) but they used the same name freedom reserve. We are Freedom Reserve (FR) we need our logo on trustwallet to make it easier to see which one is the real Freedom Reserve.

**Comment by AcapSLP** [comment]
> As per our policy, brand new tokens are not included, there is a minimum requirement of 2500 holder addresses and 5000 transactions, in order to filter out scam tokens.
> See the criteria at (mentioned in the first message by the bot): https://community.trustwallet.com/t/how-to-submit-a-token-logo/3863).
> This token low usage yet (342). Will close unless additional circulation proof is provided.
> 
> https://etherscan.io/token/0xC626e0619aC79AFEa9281c8eB9b1a9f9D3Fab532

Screenshot_2020-12-01 Cryptocurrency Tips
Screenshot_2020-12-01 Cryptocurrency Tips(1)
Screenshot_2020-12-01 Cryptocurrency Tips(2)
Screenshot_2020-12-01 Cryptocurrency Tips(3)
Screenshot_2020-12-01 Cryptocurrency Tips(4)
Screenshot_2020-12-01 Cryptocurrency Tips(5)
Screenshot_2020-12-01 Cryptocurrency Tips(6)
Screenshot_2020-12-01 Cryptocurrency Tips(7)


This list goes on for dozens of pages. there is no way to export this data from CCTip

**Comment by AcapSLP** [comment]
These are not random tips, either. people have worked for these.

**Pull request closed without merging**
