### PR TITLE
Create BullionCorpToken

### PR DESCRIPTION
**Pull request by NakotiGupta**
bullion12
[info.json.docx](https://github.com/trustwallet/assets/files/6677337/info.json.docx)

### CODE REVIEW

**Comment by Cryptocool1** [comment]
Please create new PR, follow doc https://community.trustwallet.com/t/how-to-submit-a-token-logo/3863
You may want to try our Assets app in beta; go to https://assets.trustwallet.com, log on with Github, enter contract ID, logo and some additional info, and it will create a PR for you.
See https://community.trustwallet.com/t/how-to-submit-a-token-logo-using-assets-app/82957.

**Comment by NakotiGupta** [comment]
> Please create new PR, follow doc https://community.trustwallet.com/t/how-to-submit-a-token-logo/3863
> You may want to try our Assets app in beta; go to https://assets.trustwallet.com, log on with Github, enter contract ID, logo and some additional info, and it will create a PR for you.
> See https://community.trustwallet.com/t/how-to-submit-a-token-logo-using-assets-app/82957.

hello, yo may want to help me out. I am new to this. Please help in adding the logo.

**Comment by NakotiGupta** [comment]
Hello, yo may want to help me out. I am new to this. Please help in adding the logo.

**Comment by Cryptocool1** [comment]
> Hello, yo may want to help me out. I am new to this. Please help in adding the logo.

 go to https://assets.trustwallet.com, log on with Github, enter contract ID, logo and some additional info, and it will create a PR for you.

**Comment by Cryptocool1** [comment]
> Hello, yo may want to help me out. I am new to this. Please help in adding the logo.

make sure to have minimum 2500 holders and 5000 transactions

**Comment by NakotiGupta** [comment]
> > Hello, yo may want to help me out. I am new to this. Please help in adding the logo.
> 
> make sure to have minimum 2500 holders and 5000 transactions

Hello,

We are conducting an STO with this token with ONLY 5 pre-approved/whitelisted investors wallet. We already have our 5 investors lined up. So we don’t need 2500 holders. 

Again, we can not achieve more than a few transactions as our investors are HODLers. 

If you look at the transaction history of the token it speaks for itself. 

Please help us add the asset/logo. 

Thanks.

**Comment by Cryptocool1** [comment]
> > > Hello, yo may want to help me out. I am new to this. Please help in adding the logo.
> > 
> > 
> > make sure to have minimum 2500 holders and 5000 transactions
> 
> Hello,
> 
> We are conducting an STO with this token with ONLY 5 pre-approved/whitelisted investors wallet. We already have our 5 investors lined up. So we don’t need 2500 holders.
> 
> Again, we can not achieve more than a few transactions as our investors are HODLers.
> 
> If you look at the transaction history of the token it speaks for itself.
> 
> Please help us add the asset/logo.
> 
> Thanks.

As per our policy, brand new tokens are not included, there is a minimum requirement of 2500 holder addresses and 5000 transactions, in order to filter out scam tokens.
See the criteria at (mentioned in the first message by the bot): https://community.trustwallet.com/t/how-to-submit-a-token-logo/3863).

**Comment by NakotiGupta** [comment]
> > > > Hello, yo may want to help me out. I am new to this. Please help in adding the logo.
> > > 
> > > 
> > > make sure to have minimum 2500 holders and 5000 transactions
> > 
> > 
> > Hello,
> > We are conducting an STO with this token with ONLY 5 pre-approved/whitelisted investors wallet. We already have our 5 investors lined up. So we don’t need 2500 holders.
> > Again, we can not achieve more than a few transactions as our investors are HODLers.
> > If you look at the transaction history of the token it speaks for itself.
> > Please help us add the asset/logo.
> > Thanks.
> 
> As per our policy, brand new tokens are not included, there is a minimum requirement of 2500 holder addresses and 5000 transactions, in order to filter out scam tokens.
> See the criteria at (mentioned in the first message by the bot): https://community.trustwallet.com/t/how-to-submit-a-token-logo/3863).

Hello,

I understand where you are coming from. However, this is not a utility token. This is a security token for specific real estate project. 

Please make exceptions for this situation. 

Thanks.

**Pull request closed without merging**
