### PR TITLE
Add RST token info and rUSD token info for Realio.fund project

### PR DESCRIPTION
**Pull request by jiujiteiro**
This PR is being closed due to inactivity. If you wish to continue, please have us reopen the PR before sending your payment, or just create a new one.
Do NOT send payments for closed PR, as the fee may by lost!
  (48 vs. 48 hrs)

### CODE REVIEW

**Comment by Cryptocool1** [comment]
As per our policy, brand new tokens are not included, there is a minimum requirement of 2500 holder addresses and 5000 transactions, in order to filter out scam tokens.
See the criteria at (mentioned in the first message by the bot): https://community.trustwallet.com/t/how-to-submit-a-token-logo/3863).
Closing PR for now. Please come back to us when all criteria are met.

**Comment by jiujiteiro** [comment]
@Cryptocool1 

Our tokens are subject to compliance depending on the jurisdiction..(kyc, aml checks, investor accreditation, lockups)

The RST token by by design will not have 2500 holders, it is a hybrid security token issued via a STO in a compliant manner representing an investment in our platform. The token exists on Ethereum, Algorand and Stellar blockchains.

https://www.algorand.com/ecosystem/use-cases/realio

https://aithority.com/technology/blockchain/realio-issues-first-hybrid-equity-token-to-power-its-defi-ecosystem-of-real-world-assets/

We also have various pairs on uniswap, most users have staked their tokens already.

For example our RST,WETH pair:
https://www.dextools.io/app/uniswap/pair-explorer/0x0f027d40c80d8f70f77d3884776531f80b21d20e

Stellar RST- https://stellar.expert/explorer/public/asset/RST-GDY3IRYBMDU3WNXDIK6JGAXYLZPDF5Q2UMTIANLSK54KA7EOXBKQJ3WP-1

There is ~1800 trades on the Stellar version.


Algorand RST- https://algoexplorer.io/asset/2725935

~ 450 transfers on Algorand.

**Comment by jiujiteiro** [comment]
@Cryptocool1 in addition,

Our rUSD token is also listed on Stellar: https://stellar.expert/explorer/public/asset/USD-GBNLJIYH34UWO5YZFA3A3HD3N76R6DOI33N4JONUOHEEYZYCAYTEJ5AK-1

The token has over 20 thousand trades. This is a token that is backed 1:1 by our partner PrimeTrust, an institutional quality custodian and trust company based in the U.S.  These tokens can be purchased with and redeemed for U.S. Dollars with KYC/AML approved accounts at www.realio.fund.  Regular 3rd party audits are conducted to verify USD collateral value.

**Comment by jiujiteiro** [comment]
We would like to get our logos and information listed so our users can have a better experience with these tokens. We understand the need to provide generic rules to filter our scam tokens and at the same time we hope you have some flexibility to serve real world projects that cannot meet your generic rules.

**Comment by jiujiteiro** [comment]
We paid the fee yesterday in BNB tokens @Cryptocool1 

https://explorer.binance.org/tx/837A1BFFEEECB9C80A3CDE6CFC5C450B3C3E75633E5683BB0D8B4F56BC627872

**Comment by jiujiteiro** [comment]
@Cryptocool1 can you please help us out here and see what happened? I think the bot missed the fee payment because it came out to be 2.9999175 BNB

**Comment by jiujiteiro** [comment]
@zachzwei any chance you can help out here?

**Comment by jiujiteiro** [comment]
@cryptomanz any chance you can help us resurrect this pull request?

**Comment by Cryptocool1** [comment]
> @Cryptocool1 can you please help us out here and see what happened? I think the bot missed the fee payment because it came out to be 2.9999175 BNB

Will check it.

**Comment by jiujiteiro** [comment]
@cryptomanz is there anything needed from my teams end here? thanks!

**Comment by Cryptocool1** [comment]
As per our policy, brand new tokens are not included, there is a minimum requirement of 2500 holder addresses and 5000 transactions, in order to filter out scam tokens.

**Comment by jiujiteiro** [comment]
@Cryptocool1 thank you for commenting. did you get a chance to review my response from 15 days ago about our RST token being a security token issued with regulatory compliance and our stable coin rUSD being backed 1:1 by an institutional partner (https://www.primetrust.com/prime-custody). These are not scam tokens and also RST is not designed to have 2500 holders or high volume transactions. How can we proceed here?

**Pull request merged**
