### PR TITLE
add Rebase logo on update version contract 

### PR DESCRIPTION
**Pull request by developerfred**
fixed https://github.com/RebasedToken/bounties/issues/2

Payment taxID -> E4E4FD22EE6837BC5A74DD625B5D57AC24FE394B1319C96A039F386FD2C239AF

Infos: b86c021

### CODE REVIEW

**Comment by Iamdeadlyz** [comment]
Please provide more details about this project.
https://community.trustwallet.com/t/how-to-submit-a-token-logo/3863#how-to-get-approved
You can follow this format when adding an info.json file:
```
{
   “name”:“Bitcoin”,
   “website”:“https://bitcoin.org”,
   “source_code”:“https://github.com/bitcoin”,
   “white_paper”:“https://bitcoin.org/bitcoin.pdf”,
   “short_description”:“Bitcoin is a cryptocurrency and worldwide payment system.“,
   “explorer”:“https://blockchain.info”,
   “research”:“https://research.binance.com/en/projects/bitcoin”
}

**Comment by developerfred** [comment]
@Iamdeadlyz done

**Comment by Iamdeadlyz** [comment]
As per our policy, brand new tokens are not included. There is a minimum requirement of 500 holder addresses and 1000 transactions in order to filter out scam tokens. See the criteria at (mentioned in the first message by the bot): https://community.trustwallet.com/t/how-to-submit-a-token-logo/3863#how-to-get-approved

This token has below-limit usage yet. This pull request will be but on hold. Please come back to us when all criteria are met.
https://etherscan.io/token/0x87F5F9eBE40786D49D35E1B5997b07cCAA8ADbFF

**Comment by RebasedToken** [comment]
@Iamdeadlyz Rebased v2 is not a scam token 😢 It's the new version of Rebased which has been [included in Trust Wallet for a while now](0xE6279E1c6c5DD41b30bA3760DCaC3CD8bbb4420D6).

Can you make an exception here? We really need our logo showing on Uniswap and SushiSwap to move things along 🙏 We could also fulfil the requirement by randomly airdropping tokens to 350 addresses but it doesn't really make sense IMO.

**Comment by Iamdeadlyz** [comment]
> @Iamdeadlyz Rebased v2 is not a scam token 😢 It's the new version of Rebased which has been [included in Trust Wallet for a while now](https://github.com/trustwallet/assets/blob/master/blockchains/ethereum/assets/0xE6279E1c65DD41b30bA3760DCaC3CD8bbb4420D6/logo.png).
> 
> Can you make an exception here? We really need our logo showing on Uniswap and SushiSwap to move things along 🙏 We could also fulfil the requirement by randomly airdropping tokens to 350 addresses but it doesn't really make sense IMO.

Noted. Making an exception since this is a token swap.

**Comment by RebasedToken** [comment]
Thanks a lot 🚀

**Pull request merged**
