### PR TITLE
Add logo and info BPLC

### PR DESCRIPTION
**Pull request by 23051993**
Token in PR: BEP20 0x211CC811c8ec3d04469e636d9839df0CEa6Fc4F9
Symbol: BPLC
 decimals: 18
"name": "BlackPearl chain",
    "websit": "http://www.blackpearlchain.io/",
    "description": "BlackPearl.Chain’s 3rd generation public mobile blockchain solves blockchain scalability issues.."
    "explorer": "https://bscscan.com/",
    "research": "https://research.binance.com/en/projects/BPLC",
    "symbol": "BPLC",
    "type": "coin",
    "decimals": 18,
    "status": "active",
    "links": [
        {
            "name": "github",
            "url": "https://github.com/BlackpearlChain"
        },
                  "name": "twitter",
            "url": "https://twitter.com/BlackpearlChain?s=20"
        },
        {
            "name": "reddit",
            "url": "https://reddit.com/r/BlackpearlChain"
        },
        {
            "name": "whitepaper",
            "url": "https://blackpearlchain.io/wp-content/uploads/2020/03/blackpearl5_Issuer_version_1_0_1.pdf"
        }
    ]
}

### CODE REVIEW

**Comment by 23051993** [comment]
> Token in PR: BEP20 0x211CC811c8ec3d04469e636d9839df0CEa6Fc4F9 Symbol: BPLC decimals: 18 "name": "BlackPearl chain", "websit": "http://www.blackpearlchain.io/", "description": "BlackPearl.Chain’s 3rd generation public mobile blockchain solves blockchain scalability issues.." "explorer": "https://bscscan.com/", "research": "https://research.binance.com/en/projects/BPLC", "symbol": "BPLC", "type": "coin", "decimals": 18, "status": "active", "links": [ { "name": "github", "url": "https://github.com/BlackpearlChain" }, "name": "twitter", "url": "https://twitter.com/BlackpearlChain?s=20" }, { "name": "reddit", "url": "https://reddit.com/r/BlackpearlChain" }, { "name": "whitepaper", "url": "https://blackpearlchain.io/wp-content/uploads/2020/03/blackpearl5_Issuer_version_1_0_1.pdf" } ] }



> Token in PR: BEP20 0x211CC811c8ec3d04469e636d9839df0CEa6Fc4F9 Symbol: BPLC decimals: 18 "name": "BlackPearl chain", "websit": "http://www.blackpearlchain.io/", "description": "BlackPearl.Chain’s 3rd generation public mobile blockchain solves blockchain scalability issues.." "explorer": "https://bscscan.com/", "research": "https://research.binance.com/en/projects/BPLC", "symbol": "BPLC", "type": "coin", "decimals": 18, "status": "active", "links": [ { "name": "github", "url": "https://github.com/BlackpearlChain" }, "name": "twitter", "url": "https://twitter.com/BlackpearlChain?s=20" }, { "name": "reddit", "url": "https://reddit.com/r/BlackpearlChain" }, { "name": "whitepaper", "url": "https://blackpearlchain.io/wp-content/uploads/2020/03/blackpearl5_Issuer_version_1_0_1.pdf" } ] }

**Review by 23051993 — COMMENTED** [review]
logo png

**Comment by 23051993** [comment]
I have modified what you asked me to wait for your approval please

**Comment by Cryptocool1** [comment]
Please create new PR, follow doc https://developer.trustwallet.com/listing-new-assets/requirements
You may want to try our Assets app in beta; go to https://assets.trustwallet.com, log on with Github, enter contract ID, logo and some additional info, and it will create a PR for you.
See https://developer.trustwallet.com/listing-new-assets/repository_details

**Comment by 23051993** [comment]
name: BlackPearl Token

type: such as BEP20

symbol: BPLC

decimals: 18

description: "BlackPearl.Chain’s 3rd generation public mobile blockchain solves blockchain scalability issues.."

website: http://www.blackpearlchain.io/

explorer: https://bscscan.com/token/0x65c8743A5A266c3512eAbD34e65ADe42D4355Ef1#tokenInfo

id: 0x65c8743A5A266c3512eAbD34e65ADe42D4355Ef1
 "status": "active",       
   "type": "coin",        
              "name":"twitter"  "url": "https://twitter.com/BlackpearlChain?s=20"
        },
        {
            "name": "reddit",   "url": "https://reddit.com/r/BlackpearlChain"
        },
        {
            "name": "whitepaper"  "url":
"https://blackpearlchain.io/wp-content/uploads/2020/03/blackpearl5_Issuer_version_1_0_1.pdf"
"links": [
        {
tags: "defi/ Trust wallet/ probit global"

address for ERC20  token: 
0x211CC811c8ec3d04469e636d9839df0CEa6Fc4F9
address for BEP20  token: 
0x211CC811c8ec3d04469e636d9839df0CEa6Fc4F9

**Comment by 23051993** [comment]
logo png

**Comment by 23051993** [comment]
I have done everything you asked of me and I am waiting for your approval🥀

**Pull request closed without merging**
