### PR TITLE
Add INFG logo and info

### PR DESCRIPTION
**Pull request by INFGtoken**

### CODE REVIEW

**Comment by Cryptocool1** [comment]
Corrections needed:
Contract is not in checksum format, should be 0x901c31a669616Fec1420fe74cF7abAC9b59C8fE3
This is a BEp20 token, correct folder is blockchains/smartchain/assets. Please correct.

**Comment by INFGtoken** [comment]
> **PR Summary**
> Files in PR: 2
> Token in PR: ERC20 0x901c31a669616fec1420fe74cf7abac9b59c8fe3
> Symbol: **INFG** decimals: 8
> Links: [Logo](https://raw.githubusercontent.com/INFGtoken/assets/master/blockchains/ethereum/assets/0x901c31a669616fec1420fe74cf7abac9b59c8fe3/logo.png) [Info](https://raw.githubusercontent.com/INFGtoken/assets/master/blockchains/ethereum/assets/0x901c31a669616fec1420fe74cf7abac9b59c8fe3/info.json) [Website](https://infinitygold.io/) [ExplorerFromInfo](https://bscscan.com/token/0x901c31a669616fec1420fe74cf7abac9b59c8fe3) [ExplorerFromID](https://etherscan.io/token/0x901c31a669616fec1420fe74cf7abac9b59c8fe3)
> Token check error:
> ❌ Contract is not in checksum format, should be 0x901c31a669616Fec1420fe74cF7abAC9b59C8fE3 (not 0x901c31a669616fec1420fe74cf7abac9b59c8fe3). Please rename it. You may need to rename to a temp name first, then to the checksum format, because lowercase-uppercase-only renames are often ignored by the Git client or the filesystem.
> ❌ ExplorerUrl incorrect, should be standard https://etherscan.io/token/0x901c31a669616fec1420fe74cf7abac9b59c8fe3, not https://bscscan.com/token/0x901c31a669616fec1420fe74cf7abac9b59c8fe3
> ! No. of holders not checked; 'undefined'
> ✓ Token type OK (ERC20); Type field OK; Symbol field OK; Decimals field OK; Description field OK; Website field OK; Status field OK; Id field OK; Logo image type is OK (image/png); Logo image size is OK (81.45 kB); Logo dimensions OK (256x256);
> 
> 

I dont get it with false on point (X), because contract and explorer URL is correct.

Can you fix it? thanks

**Comment by Cryptocool1** [comment]
f you can't rename files in the PR, you may open a new PR. Make sure to mention this PR, so that we can see that fee has been paid already here.
Please create new PR, follow doc https://community.trustwallet.com/t/how-to-submit-a-token-logo/3863
You may want to try our new Assets app in beta; go to https://assets.trustwallet.com, log on with Github, enter contract ID, logo and some additional info, and it will create a PR for you.
See https://community.trustwallet.com/t/how-to-submit-a-token-logo-using-assets-app/82957.

**Comment by INFGtoken** [comment]
> **PR Summary**
> Files in PR: 4
> Tokens in PR (2):
> 
>     * ERC20 0x901c31a669616fec1420fe74cf7abac9b59c8fe3
> 
>     * BEP20 0x901c31a669616fec1420fe74cf7abac9b59c8fe3
> 
> 
> **Token ERC20 - 0x901c31a669616fec1420fe74cf7abac9b59c8fe3**:
> Symbol: **INFG** decimals: 8
> Links: [Logo](https://raw.githubusercontent.com/INFGtoken/assets/master/blockchains/ethereum/assets/0x901c31a669616fec1420fe74cf7abac9b59c8fe3/logo.png) [Info](https://raw.githubusercontent.com/INFGtoken/assets/master/blockchains/ethereum/assets/0x901c31a669616fec1420fe74cf7abac9b59c8fe3/info.json) [Website](https://infinitygold.io/) [ExplorerFromInfo](https://bscscan.com/address/0x901c31a669616fec1420fe74cf7abac9b59c8fe3) [ExplorerFromID](https://etherscan.io/token/0x901c31a669616fec1420fe74cf7abac9b59c8fe3)
> Token check error:
> ❌ Contract is not in checksum format, should be 0x901c31a669616Fec1420fe74cF7abAC9b59C8fE3 (not 0x901c31a669616fec1420fe74cf7abac9b59c8fe3). Please rename it. You may need to rename to a temp name first, then to the checksum format, because lowercase-uppercase-only renames are often ignored by the Git client or the filesystem.
> ❌ ExplorerUrl incorrect, should be standard https://etherscan.io/token/0x901c31a669616fec1420fe74cf7abac9b59c8fe3, not https://bscscan.com/address/0x901c31a669616fec1420fe74cf7abac9b59c8fe3
> ! No. of holders not checked; 'undefined'
> ✓ Token type OK (ERC20); Type field OK; Symbol field OK; Decimals field OK; Description field OK; Website field OK; Status field OK; Id field OK; Logo image type is OK (image/png); Logo image size is OK (81.45 kB); Logo dimensions OK (256x256);
> 
> 
> 
> **Token BEP20 - 0x901c31a669616fec1420fe74cf7abac9b59c8fe3**:
> Symbol: **INFG** decimals: 8
> Links: [Logo](https://raw.githubusercontent.com/INFGtoken/assets/master/blockchains/smartchain/assets/0x901c31a669616fec1420fe74cf7abac9b59c8fe3/logo.png) [Info](https://raw.githubusercontent.com/INFGtoken/assets/master/blockchains/smartchain/assets/0x901c31a669616fec1420fe74cf7abac9b59c8fe3/info.json) [Website](https://infinitygold.io/) [Explorer](https://bscscan.com/token/0x901c31a669616fec1420fe74cf7abac9b59c8fE3)
> Token check error:
> ❌ Contract is not in checksum format, should be 0x901c31a669616Fec1420fe74cF7abAC9b59C8fE3 (not 0x901c31a669616fec1420fe74cf7abac9b59c8fe3). Please rename it. You may need to rename to a temp name first, then to the checksum format, because lowercase-uppercase-only renames are often ignored by the Git client or the filesystem.
> ✓ Token type OK (BEP20); Type field OK; Symbol field OK; Decimals field OK; Description field OK; Website field OK; Explorer field OK; Status field OK; Id field OK; Logo image type is OK (image/png); Logo image size is OK (81.45 kB); Logo dimensions OK (256x256); Token circulation OK (no. of holders: 3829);
> 
> 

how can I fix "Contract is not in checksum format"?

**Comment by INFGtoken** [comment]
@Cryptocool1 how can I fix "Contract is not in checksum format"?

**Comment by Cryptocool1** [comment]
> @Cryptocool1 how can I fix "Contract is not in checksum format"?

can you please create new PR using our new Assets app in beta; go to https://assets.trustwallet.com, log on with Github, enter contract ID, logo and some additional info, and it will create a PR for you.
See https://community.trustwallet.com/t/how-to-submit-a-token-logo-using-assets-app/82957.
When creating new PR, mention this PR, so that fee can be reused, and not paid again.

**Pull request closed without merging**
