### PR TITLE
XSGD is a Singapore Dollar backed stablecoin

### PR DESCRIPTION
**Pull request by agupagu**
This PR is being closed due to inactivity. If you wish to continue, please have us reopen the PR before sending your payment.
Do NOT send payments for closed PR, as the fee may by lost!
  (378 vs. 60 hrs)

### CODE REVIEW

**Comment by catenocrypt** [comment]
As per our policy, brand new tokens are not included, there is a minimum requirement of 2500 holder addresses and 5000 transactions, in order to filter out scam tokens.
See the criteria at (mentioned in the first message by the bot): https://community.trustwallet.com/t/how-to-submit-a-token-logo/3863).
This token has low usage yet (198). Closing PR for now. Please come back to us when all criteria are met.

https://etherscan.io/token/0x70e8de73ce538da2beed35d14187f6959a8eca96

**Comment by paaniwater** [comment]
Hi Adam,

We actually have our token (XSGD) running on two blockchains. One of which
is Ehereum and the other being Zilliqa. I believe that we have met the
necessary criteria if you take a look at the link and image below.

Zilliqa:
https://viewblock.io/zilliqa/address/zil180v66mlw007ltdv8tq5t240y7upwgf7djklmwh?txsType=token-contract&specific=zil180v66mlw007ltdv8tq5t240y7upwgf7djklmwh&page=1

I hope this helps and that we could list it on your platform as soon as
possible. You can take a look at our website to be assured that we are a
government-regulated organization with hopes of introducing cryptocurrency
and its usage to the wider community. By listing on your platform, we
believe that it will be a great step forward in the right direction.

You could contact me at my business email as well: somesh@xfers.com

Best regards,
Somesh

**Comment by catenocrypt** [comment]
Circulation is satisfied when looking combined on both chains.

**Comment by catenocrypt** [comment]
Please add an `info.json` file next to the `logo.png`, with info about the project, of the form:

```json
{
    "name": "Trust Wallet Token",
    "website": "https://trustwallet.com",
    "short_description": "Utility token to increase adoption of cryptocurrency.",
    "explorer": "https://etherscan.io/token/0xA866F0198208Eb07c83081d5136BE7f775c2399e",
    "socials": [
        {
            "name": "Twitter",
            "url": "https://twitter.com/trustwalletapp",
            "handle": "TrustWalletApp"
        },
        {
            "name": "Reddit",
            "url": "https://reddit.com/r/trustapp",
            "handle": "TrustApp"
        }
    ]
}
```

**Comment by paaniwater** [comment]
Hi I have uploaded the json file along with the new logo. Thanks!

**Comment by catenocrypt** [comment]
I did some fixes.  Submission looks OK now.  Pending fee payment.

**Comment by paaniwater** [comment]
Hi our token is already listed on the wallet and just needs an update of the logo.

**Comment by paaniwater** [comment]
Please grant us permission to make this one change as it's primary goal is to further crypto usage in Singapore

**Comment by catenocrypt** [comment]
Sorry, our policy is to request fee for all PRs, even for updating existing logo.

**Comment by paaniwater** [comment]
What's the fee?

**Comment by paaniwater** [comment]
Is it 1000 TWT or 6 BNB? With the memo 5323?

**Comment by catenocrypt** [comment]
> Is it either 1000 TWT or 6 BNB? With the memo 5323?

Correct.

**Comment by paaniwater** [comment]
Hi please reopen the PR, we are working on the payment

**Comment by paaniwater** [comment]
Hi could you please reopen the PR as we intend to make a payment soon.

**Comment by catenocrypt** [comment]
Reopened.  If it is auto-closed by automation by the time you can make fee payment, don't worry, payment will be picked up with next reoped.

**Comment by paaniwater** [comment]
Hi could the request be reopened as we do not want a case whereby the
payment has an issue going through.

Thanks!

**Comment by catenocrypt** [comment]
Reopening.
Sorry, once closed, automation will close this PR, but do not worry, payment is picked up automatically at next reopen.

**Comment by paaniwater** [comment]
Hi the payment has been made.

Transaction ID:
DED34094132FC34F3FDE52FA8AA6D9F26DC37B75B40F1C54D31ACA2AD3D986CB

Please update the logo and open the PR. Thanks.

**Comment by catenocrypt** [comment]
Reopen

**Comment by catenocrypt** [comment]
I need to handle conflict, update with new fields before merge.

**Comment by paaniwater** [comment]
Hi sorry what does that mean?

**Comment by catenocrypt** [comment]
Merged master, check build is green now.  Merging.

**Comment by paaniwater** [comment]
Hi Adam,

Was wondering if we could get the trust wallet logo in the SVG file format?
We want it to be uploaded onto our website (
https://www.xfers.com/sg/stablecoin). Thanks!

**Comment by paaniwater** [comment]
Also, we would like XSGD to be added to the stable coins page here (
https://trustwallet.com/stablecoins/) if that would be possible. Thanks!

**Comment by catenocrypt** [comment]
@ramsdieter is SVG format of Trust Wallet available?

**Comment by catenocrypt** [comment]
Trust Wallet logo in various formats available here:

https://trustwallet.com/press

**Pull request merged**
