### PR TITLE
AFAVC Logo added AGAIN !!

### PR DESCRIPTION
**Pull request by echapeta**

### CODE REVIEW

**Comment by echapeta** [comment]
Hello,

 

May I pay in ETH?

 

Thank You

 

 

 

Eduardo G. Chapeta

CEO

Interwave Global

www.iw-global.com

**Comment by echapeta** [comment]
May I pay in ETH?

 

 

 

Eduardo G. Chapeta

CEO

Interwave Global

www.iw-global.com

**Comment by echapeta** [comment]
May I pay in ETH?

 

 

 

Eduardo G. Chapeta

CEO

Interwave Global

www.iw-global.com

**Comment by kolya182** [comment]
@echapeta Here is an ethereum https://etherscan.io/address/0xb46224e545c3f1fa4d05f94465d13f777866a77b  address 0.06 , please pay

**Comment by echapeta** [comment]
Hello,

 

Paid at transaction:

 

https://u9455015.ct.sendgrid.net/ls/click?upn=WNbsy6qFrPkVfeApOza7cKHZ69Qw1a8iakxIeN4-2BDUHaJ8c5C6dutftOeFeMVScMNYxCKHAtEove7LD7Xgwnb1iGNfeesQJubUuOQD7kG3muMW3FiMslmQA-2BPbRmyROAsEt0Cx37w6YTaweDtaFPWw-3D-3DNTf2_U31jt5HgHBh7k3Grc5s4l-2FRMc2ZmshIH-2FjauaEZZ5KdWjSAT9O6CFOUYsZoivhnIfX01ggLHeusewWDJsDr-2B40jvB4-2B4KDnMzJX4uJahxWzJTwx9amzAawpi3zv4wXNhffcbiJrWOhP4pgxZOTIa356EHpFliw6dnfhGB2zPUD6077UjPs5bcOAwgeoghbzAwbw3zcp3HL8XUaFEsNnnZKn1UhZwXtJV5RMBRLqL6DtGMKilsoVZ4qPoVzOnfo4StWSd3zXYzl67v8mEIfOMyTsLdaAtQscTNwwN3pbC3eQ-3D

 

 

Regards,

 

 

 

Eduardo G. Chapeta

CEO

Interwave Global

www.iw-global.com

**Comment by kolya182** [comment]
@echapeta As i mentioned before, when you create new PR and proposing new changes you need update (sync) your fork with our master. For now new token added here https://github.com/trustwallet/assets/commit/aee3755fd3a52e70ff5dad8dba4039c9ea6dc424

**Comment by echapeta** [comment]
Thank You

 

 

 

Eduardo G. Chapeta

CEO

Interwave Global

www.iw-global.com

**Pull request closed without merging**
