### PR TITLE
Beta.Fork Token

### PR DESCRIPTION
**Pull request by fabiomig**

### CODE REVIEW

**Comment by catenocrypt** [comment]
As per our policy, brand new tokens are not included, there is a minimum requirement of 2500 holder addresses and 5000 transactions, in order to filter out scam tokens.
See the criteria at (mentioned in the first message by the bot): https://community.trustwallet.com/t/how-to-submit-a-token-logo/3863).
This token has no real usage yet (197 holders). Closing PR for now. Please come back to us when all criteria are met.  Multi-chain and staking tokens may get special treatment, let us know if this is the case. 

https://bscscan.com/token/0x8df7cdAd824Ea5983f97bA1043EEc22C815930CF

**Comment by fabiomig** [comment]
Hi there!

Yes, it is a stake coin. It has an embedded tier system in it.

you can read more about it here:
https://forkenomics.medium.com/introducing-beta-fork-582b5a2cbecd

Our main goal is actually fight scammers and make DeFi a safer place.

You can read more about it also in our medium.

This is actually our second token launch. The first one Apha.Fork you can see it here:

https://bscscan.com/token/0xa872e0a44bbd66c1486a756cb5bd3f0beec4e32e

**Comment by catenocrypt** [comment]
What was wrong with the first one?

**Comment by fabiomig** [comment]
> What was wrong with the first one?

Nothing wrong with the first token.

Alpha will be used as governance token for the entire project.

https://vote.forkenomics.com/

For example, every aspect of beta can be decided by the community. Nothing is hard-coded.

But like every legit project, it takes time to gain some momentum. We're doing everything we can to make it grow.

**Comment by fabiomig** [comment]
Not sure if it's the right place but i want to invite you to join our TG and check how awesome our community is:
https://t.me/forkenomics

**Comment by fabiomig** [comment]
@catenocrypt it will be possible to add it?

Cheers

**Comment by fabiomig** [comment]
hello? :P

**Comment by catenocrypt** [comment]
I see no sign of increasing usage, no of holders is not increasing.  If there are no users on a token there is no point for us to include.
We can make exception from the limits we have, but I would like to see increasing trend and at least some very minimum-minimum usage, like 500 holders and 2500 transactions.  How about that?

**Comment by fabiomig** [comment]
Sure, we can wait no problem at all but one of the reasons to have our logo and info in the token is to avoid someone create a token with the same symbol and pretend to be us.

Trust wallet assets (logo and info) are being used in many projects such as exchanges and charts.

If you really can't add it in meanwhile, i guess we need to wait for those 500 holders :-)

**Comment by vikmeup** [comment]
@fabiomig how do you guys right scam?

**Comment by fabiomig** [comment]
@vikmeup

You can learn more here:
https://forkenomics.medium.com/making-defi-a-safer-place-with-forkenomics-8834bc0017e2

**Comment by Cryptocool1** [comment]
Hello,
As per our policy, there is a minimum requirement of 2500 holder addresses and 5000 transactions.
This token has no real usage yet (195 holders). Closing PR for now. Please come back to us when all criteria are met.

**Comment by fabiomig** [comment]
Hi @Cryptocool1 . I dont want to be rude but looks like you didn't read the whole conversation...

**Pull request closed without merging**
