### PR TITLE
Add FalconX (BEP20)

### PR DESCRIPTION
**Pull request by projectfalconx**
Adding info for BEP20 token 'FalconX'.

PR created by <a href="https://assets.trustwallet.com">TW Assets Management</a>

### CODE REVIEW

**Comment by ramsty** [comment]
Hi!
Could you answer some questions?
• What is the purpose of this token? How will it benefit Trust Wallet users?
• How is the token being distributed? Are you conducting an airdrop?
• Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?
• Is the token listed on a centralized/decentralized exchange?
• Is a Smart Contract audit completed? Where can we find this information?

**Comment by projectfalconx** [comment]
• What is the purpose of this token? How will it benefit Trust Wallet users?
FalconX is a Bep 20 Token within the FalconX NFT Ecosystem. FalconX community members will be able to access FalconX NFT’s which reward holders with daily passive income. Projectfalconx.com for more details




• How is the token being distributed? Are you conducting an airdrop?
It was distributed via a migration portal to all DogeX holders at a ration of 1000doge:1 FalconX. 


• Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?
There was no ICO or presale. 


• Is the token listed on a centralized/decentralized exchange?
Pancakeswap



• Is a Smart Contract audit completed? Where can we find this information?
https://spadetech.io/wp-content/uploads/2021/11/FalconX_audit-Oct21.pdf

thanks for all your help. if you have any other questions please ask.

**Comment by projectfalconx** [comment]
> Hi! Could you answer some questions? • What is the purpose of this token? How will it benefit Trust Wallet users? • How is the token being distributed? Are you conducting an airdrop? • Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale? • Is the token listed on a centralized/decentralized exchange? • Is a Smart Contract audit completed? Where can we find this information?

have provided the required infos. please can you advise how long it will take to get the logo up? thanks

**Comment by projectfalconx** [comment]
@ramsty @zachzwei @Cryptocool1 @cryptomanz  hey guys just looking for a rough eta? thanks

**Comment by projectfalconx** [comment]
@ramsty @zachzwei @Cryptocool1 @cryptomanz hey guys we have just launched on eth too. its the same token contract and same circulating supply (1t) bridged via the-crossing.io. How do we get our logo updated for the eth contract? thanks

**Comment by projectfalconx** [comment]
https://etherscan.io/token/0xe50a71f0ad9d513180f25cc33d938658eac3bbb5 the eth contract is here

**Pull request merged**
