### PR TITLE
Adding TDW Token logo and info.

### PR DESCRIPTION
**Pull request by TheDogeWorld**
This is the upload for TDW Bep20 token logo and info.

### CODE REVIEW

**Comment by cryptomanz** [comment]
Hello,
As per our policy, brand new tokens are not included, there is a minimum requirement of 5000 holder addresses and 10000 transactions, in order to filter out scam tokens.
See the criteria at (mentioned in the first message by the bot): https://community.trustwallet.com/t/how-to-submit-a-token-logo/3863).

**Comment by xadahiya** [comment]
The token holder requirement is subject to review based on the project. We just got listed yesterday. We're already audited by dessertswap (https://dessertswap.finance/audits/The%20Doge%20World%20BEP-20%20Audit%2010483640.pdf), also we have a marketplace coming in the next few days. Please review our project once. 
Thanks!

**Comment by cryptomanz** [comment]
According to our documentation token image needs to be full screen
https://community.trustwallet.com/t/how-to-submit-a-token-logo/3863

**Comment by TheDogeWorld** [comment]
logo

**Comment by TheDogeWorld** [comment]
Does this image works? I believe i have followed all the instructions written there.

**Review by TheDogeWorld — COMMENTED** [review]
logo change

**Comment by Cryptocool1** [comment]
hello,
• Is the token listed on a centralized/decentralized exchange?
 • Is a Smart Contract audit completed? Where can we find this information?
  • How is the token being distributed? Are you conducting an airdrop?

**Comment by TheDogeWorld** [comment]
The Doge World Info

• Is the token listed on a centralized/decentralized exchange?

DEX only. PancakeSwap

• Is a Smart Contract audit completed? Where can we find this information?

Yes our Smart Contract audit has been completed by Desert Finance. You can find the audit here:
https://dessertswap.finance/audits/The%20Doge%20World%20BEP-20%20Audit%2010483640.pdf

• How is the token being distributed? Are you conducting an airdrop?

Total Supply : 100,000,000,000 TDW

Public Presale 45% - 45,000,000,000 TDW

Private Sale 10% - 10,000,000,000 TDW

Tokens For Liquidity 36% - 36,000,000,000 TDW

Team 3% - 3,000,000,000 TDW

Charity 2% - 2,000,000,000 TDW

Marketing 2.13% – 2,131,000,000 TDW

Burnt 0.719% - 719,856,000 TDW

Burnt Dxsale-Contract 1.15% - 1,150,524,000 TDW

**Comment by TheDogeWorld** [comment]
Do u require any more info apart from this? I am happy to provide it.

**Pull request merged**
