### PR TITLE
Add HeroesTD (BEP20)

### PR DESCRIPTION
**Pull request by availableservices**
Adding info for BEP20 token 'HeroesTD'.

PR created by <a href="https://assets.trustwallet.com">TW Assets Management</a>

### CODE REVIEW

**Comment by jefftran99** [comment]
Fees Already Paid

**Review by jefftran99 — COMMENTED** [review]
Add info HeroesTD

**Comment by ramsty** [comment]
Hi!
Could you answer some questions?
• What is the purpose of this token? How will it benefit Trust Wallet users?
• How is the token being distributed? Are you conducting an airdrop?
• Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?
• Is the token listed on a centralized/decentralized exchange?
• Is a Smart Contract audit completed? Where can we find this information?

**Comment by ramsty** [comment]
Your logo should be a full screen 256*256 px, please change.

**Comment by jefftran99** [comment]
• What is the purpose of this token? How will it benefit Trust Wallet users?

> HeroesTD token (HTD) is the main token of HeroesTD game - a collectible tower defense strategy game. HTD holders can use HTD to summon new NFT Heroes and trade those NFT Heroes in the marketplace, or Stake HTD tokens on our DApp to earn extra revenue, or participate in HeroesTD DAO system to vote for new content and systematic changes. Currently we already have more than 14000 holders for HTD, and we also opened NFT Marketplace, Yield Farming, Staking Pool on our DApp. With HTD in Trust Wallet, HTD holders can easily trade or spend HTD using Trust Wallet in a secured environment.

• How is the token being distributed? Are you conducting an airdrop?

> We already finished the private sale, public sale (IDO), TGE (listed on pancakeswap, MEXC). We already got more than 14000 HTD holders, ands are mostly from the communities. We will also have new airdrop campaigns to attract more users to HeroesTD, also to increase the coverage of HTD tokens in the gaming communities too.

• Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?

> Yes we did IDO on various platforms: BSCStation, Launchzone, MEXC, Kaistarter, ONUS, and also on our homepage heroestd.io . The IDO were done very successfully. More information can be found on Coinmarketcap: https://coinmarketcap.com/currencies/heroes-td/

• Is the token listed on a centralized/decentralized exchange?

> Yes, HTD token is listed on Pancakeswap (DEX), MEXC (CEX). We are in middle of discussion to list HTD on other CEX platforms as well. You can find the details here: https://coinmarketcap.com/currencies/heroes-td/

• Is a Smart Contract audit completed? Where can we find this information?

> Yes, HTD is already fully audited by Verichains. We have published the audit certificate here on our whitepaper: https://docs.heroestd.io/economy/heroes-td-token/audit

**Review by jefftran99 — COMMENTED** [review]
Viewed files

**Pull request merged**
