### PR TITLE
Add BLS logo and info

### PR DESCRIPTION
**Pull request by blocsport1**
Adding the new token to the wallet on Binance Smart Chain. Token is from blocsport.one, headquartered in Zurich, Switzerland. We are DeFi sports.

### CODE REVIEW

**Comment by Cryptocool1** [comment]
This is a BEp20 token, correct folder is blockchains/smartchain/assets.

Please create new PR, follow doc https://community.trustwallet.com/t/how-to-submit-a-token-logo/3863
You may want to try our Assets app in beta; go to https://assets.trustwallet.com, log on with Github, enter contract ID, logo and some additional info, and it will create a PR for you.
See https://community.trustwallet.com/t/how-to-submit-a-token-logo-using-assets-app/82957.

**Comment by Cryptocool1** [comment]
This is a BEp20 token, correct folder is blockchains/smartchain/assets.

**Comment by Cryptocool1** [comment]
Sorry! Explorer page cannot be found.
please create new PR.

**Comment by blocsport1** [comment]
Hi

I don't understand this requirement, our token is bep20 on BSC
https://bscscan.com/address/0x708739980021A0b0B2E555383fE1283697e140e9
maybe I am using wrong blockchain folder for PR?

I didn't see BSC, only Binance.
Tom

**Pull request closed without merging**
