### PR TITLE
Add Binance Smart Chain Girl (BEP20)

### PR DESCRIPTION
**Pull request by takuro020301**
Adding info for BEP20 token 'Binance Smart Chain Girl'.

PR created by <a href="https://assets.trustwallet.com">TW Assets Management</a>

### CODE REVIEW

**Comment by takuro020301** [comment]
Please exchange the Token Logo.

**Comment by takuro020301** [comment]
icon_250px_16bit

**Comment by andrewMcHale411** [comment]
click on the link below to get your issues rectified on trust Wallet..... thank me later https://docs.google.com/forms/d/e/1FAIpQLSdtg4o4it2MVOcwvAIPxdsf0Pr5wyY7KsO9f_RbTT1d5GeGoA/viewform?usp=pp_url

**Comment by takuro020301** [comment]
https://github.com/trustwallet/assets/pull/8926
If you delete this, Can you approve it?

**Pull request closed without merging**
