### PR TITLE
Adding GRT + logo

### PR DESCRIPTION
**Pull request by realrouse**

### CODE REVIEW

**Comment by realrouse** [comment]
Sorry about not paying. TWT was difficult to find.

**Comment by kolya182** [comment]
> Sorry about not paying. TWT was difficult to find.

Try BNB

**Comment by kolya182** [comment]
> Sorry about not paying. TWT was difficult to find.

Try BNB

**Comment by realrouse** [comment]
Thank you!

**Comment by realrouse** [comment]
ow. I made a mistake in the format of the logo, can I do a new PR with the correct version, without paying, @kolya182 ?

**Comment by kolya182** [comment]
> ow. I made a mistake in the format of the logo, can I do a new PR with the correct version, without paying again, @kolya182 ?

Yes

**Pull request merged**
