### PR TITLE
Add KuCoin Community Chain Assets

### PR DESCRIPTION
**Pull request by enoughpower**

### CODE REVIEW

**Review by Onyeali — APPROVED** [review]

**Comment by catenocrypt** [comment]
Coin logo+info added via #19362 .
Adding the token assets requires handling the new KRC20 token type.

**Comment by enoughpower** [comment]
> 

thanks,Is there anything else I need to do about the new KRC20 token type？

**Comment by Skills1995** [comment]
https://github.com/trustwallet/assets/pull/19352#issuecomment-1082569639

**Comment by RrezaRashedi** [comment]
> Fee is PAID, fantastic! Thanks! Review added.
> 
>  The PR will be evaluated soon by a maintainer, and if merged, the new logos should be visible in Trust Wallet.
>  Please note that the app caches logos (up to several days; if you want to see changes immediately, use a new installation). See the [assets FAQ](https://github.com/trustwallet/assets#faq).
>  @Iamdeadlyz, @Cryptocool1, @cryptomanz: please take note.
> 
>  ([1000.00 TWT](https://explorer.binance.org/tx/F55887799EB1B9B382237EC0AFBA372BD46DE3A2671443E47FC3C9634F8C1D12))

**Review by HZ1357 — APPROVED** [review]
Tnx

**Review by Bezzat — APPROVED** [review]

**Comment by ArtemGoryunov** [comment]
Merged here https://github.com/trustwallet/assets/pull/20519

**Pull request closed without merging**
