### PR TITLE
Add UFO Token

### PR DESCRIPTION
**Pull request by cxpm1**
For adding UFO support

### CODE REVIEW

**Comment by Cryptocool1** [comment]
hello,
• What is the purpose of this token? How will it benefit Trust Wallet users?
 • How is the token being distributed? Are you conducting an airdrop?
 • Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?
 • Is the token listed on a centralized/decentralized exchange?
 • Is a Smart Contract audit completed? Where can we find this information?

**Comment by cxpm1** [comment]
1. Fully Decentralized inter-galactic social gaming token. Most of the UFO holders are using trust wallet for storing UFO token. Fully integrating it in trust would will make their user experience much smoother. 

2. It was a stealth launch. First come first serve 

3. No ICO or private sales. Fair launch concept. 

4. Uniswap and shibaswap 

5. https://medium.com/@UFOtruth/ufo-well-secured-hacken-audit-49b871b461d5

**Comment by Cryptocool1** [comment]
according to the explorer and ConMarketCap pages, token naming should be "The Truth"

**Comment by cxpm1** [comment]
> according to the explorer and ConMarketCap pages, token naming should be "The Truth"

We have changed the token name to " The Truth" as per the explorer and ConMarketCap page

**Comment by cxpm1** [comment]
> > according to the explorer and ConMarketCap pages, token naming should be "The Truth"
> 
> We have changed the token name to " The Truth" as per the explorer and ConMarketCap page

@Cryptocool1 @catenocrypt @zachzwei any update?

**Pull request merged**
