### PR TITLE
Adding Pendle

### PR DESCRIPTION
**Pull request by danielanthonyw**
Discord tag: Dan Anthony#3621, do reach out to me for any issues.

https://www.pendle.finance/
https://www.coingecko.com/en/coins/pendle
https://coinmarketcap.com/currencies/pendle/

### CODE REVIEW

**Comment by Cryptocool1** [comment]
hello,
 • Is a Smart Contract audit completed? Where can we find this information?

**Comment by danielanthonyw** [comment]
Hi, yes, we've had 3 audits, 2 whitehat reports, and one report from Least Authority. You can find the audit reports here https://github.com/pendle-finance/pendle-core/tree/master/docs/audits.

A summary of the reports can be found here: https://medium.com/pendle/security-update-7206b8fd5b91

**Comment by Cryptocool1** [comment]
can you please add links to your PR?
example:
https://developer.trustwallet.com/add_new_asset/repository_details

**Comment by danielanthonyw** [comment]
Hi, apologies for the lots of updates, All of the information above should be accurately reflected but I'm not sure why coingecko and etherscan shows an error.

**Pull request merged**
