### PR TITLE
add Rocket Boys (BEP20)

### PR DESCRIPTION
**Pull request by isBASED**
adding logo + info for Rocket Boys

### CODE REVIEW

**Comment by cryptomanz** [comment]
Hello,
Can your answer some questions?
• What is the purpose of this token? How will it benefit Trust Wallet users?
 • How is the token being distributed? Are you conducting an airdrop?
 • Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?
 • Is the token listed on a centralized/decentralized exchange?
 • Is a Smart Contract audit completed? Where can we find this information?

**Comment by isBASED** [comment]
> Hello,
> Can your answer some questions?
> • What is the purpose of this token? How will it benefit Trust Wallet users?
> • How is the token being distributed? Are you conducting an airdrop?
> • Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?
> • Is the token listed on a centralized/decentralized exchange?
> • Is a Smart Contract audit completed? Where can we find this information?

Q: What is the purpose of this token? How will it benefit Trust Wallet users?
A: RBOYS will be used to gain entry on ICO’s that will be held on our upcoming Launchpad, holding a specific about of RBOYS will give you a guaranteed spot in some of the future tokens that will be launched on our Platform. We also have a buyback system, and a reward system that rewards holders with hourly BUSD payouts.

Q: How is the token being distributed? Are you conducting an airdrop?
A: We raised 1000BNB in a private presale, 3000BNB in a public presale, and successfully launched on PancakeSwap on July 14th.

Q: Did you sell the tokens at an Initial Coin Offering (ICO) or a token presale?
A: Yes, we sold 4000BNB worth of tokens in our presale before launching on Pancakeswap.

Q: Is the token listed on a centralized/decentralized exchange?
A: The token can be bought & traded on PancakeSwap. We will be looking to get on more exchanges and easier facilitate buying in the near future.

Q: Is a Smart Contract audit completed? Where can we find this information?
A: We are getting a Techrate audit shortly, which will be put on the website shortly after.

**Comment by Cryptocool1** [comment]
awaiting for smart contract audit

**Comment by Cryptocool1** [comment]
Hello,
please create new PR when smart contract audit will be ready.
make sure to mention this PR, so that we can see that fee has been paid already here.

**Comment by isBASED** [comment]
> Hello,
> please create new PR when smart contract audit will be ready.
> make sure to mention this PR, so that we can see that fee has been paid already here.

Hi, I just made this new pull request: #12023

**Pull request closed without merging**
