### PR TITLE
Add MUNCH (BEP20)

### PR DESCRIPTION
**Pull request by RoughanBass**
Adding info for BEP20 token 'MUNCH'.

PR created by <a href="https://assets.trustwallet.com">TW Assets Management</a>

### CODE REVIEW

**Comment by Cryptocool1** [comment]
As per our policy, brand new tokens are not included, there is a minimum requirement of 2500 holder addresses and 5000 transactions, in order to filter out scam tokens.
See the criteria at (mentioned in the first message by the bot): https://community.trustwallet.com/t/how-to-submit-a-token-logo/3863).
Closing PR for now. Please come back to us when all criteria are met.

**Comment by RoughanBass** [comment]
We have been on the Eth network for 3 months
With over 8k holders
We created a bridge to BSC chain to enable people to buy on pancake swap


Munchproject.io

________________________________

**Comment by RoughanBass** [comment]
Hi there

As you can see we are not a brand new token

We are on ERC20 over 60 days now with locked liquidity and 2.7 Million dollars donated to 2 worthy causes

Here is a recent article on coin telegraph about us
https://cointelegraph.com/news/munch-and-the-giving-block-partner-to-connect-crypto-ready-nonprofits


You can see both the BSC and  ERC20 contract here
https://coinmarketcap.com/currencies/munch-token/


BSC
https://www.dextools.io/app/pancakeswap/pair-explorer/0x9ff68152a7b8a7938595b80fb9b1980557090df3

ERC20
https://www.dextools.io/app/uniswap/pair-explorer/0x8745df04862b854d0d7ee8ecf80ac4e9c109d547


ERC20 has 9.2k holders

We decided to make our token available on BSC due to the high gas fees

I do understand your concern about scam tokens and we are not a scam token
There is a LOT of scam tokens on the BSC chain pretending to be MUNCH and having our logo appear would stop this

Please can you review this and see if you can review your decision

https://munchproject.io
https://t.me/munchtokencom



Rgds
MunchTeam

**Comment by Cryptocool1** [comment]
#9831 paid

**Pull request merged**
