### PR TITLE
add DEA token logo and info

### PR DESCRIPTION
**Pull request by bi0hazard12**
Hello,

We have submitted few weeks ago our first token DEUS our ecosystem keeps evolving in a fast pace and yesterday we have launched our new token DEA and with that we launched our yield farming program with it. 

Since DEA is used a lot for yield doesn't appear to many holders, because DEA is stacked in our contracts but you can see that we have already +1,540 transactions.

DEA is from DEUS ecosystem, so regarding social platforms we use everything from DEUS because DEA is from our ecosystem.

I hope it explain a bit :)

Thank you

### CODE REVIEW

**Comment by Iamdeadlyz** [comment]
As per our policy, brand new tokens are not included. There is a minimum requirement of 500 holder addresses and 1000 transactions in order to filter out scam tokens. See the criteria at (mentioned in the first message by the bot): https://community.trustwallet.com/t/how-to-submit-a-token-logo/3863#how-to-get-approved

This token has below-limit usage yet. Rejecting PR for now. Please come back to us when all criteria are met.
https://etherscan.io/token/0x80ab141f324c3d6f2b18b030f1c4e95d4d658778 (120, 1581)

Even though there's a staking program, we need to see that it reached 500 holders. Cheers!

**Comment by catenocrypt** [comment]
OK, your explanation makes sense; sorry we can't notice such things easily.
Reopening PR.

**Comment by catenocrypt** [comment]
Token check OK, waiting for fee payment.

**Comment by bi0hazard12** [comment]
> OK, your explanation makes sense; sorry we can't notice such things easily.
> Reopening PR.

Thank you so much for paying attention on my explanation :)

Just made the payment.

https://explorer.binance.org/tx/4ED54E8680C1A25F366995078F6F54DF89F62F2E4C97E619DB2EDA16AB351F3D

**Comment by bi0hazard12** [comment]
Hello,

I know this request is old and was closed, just wanted to check something, we are changing logos for our products is it possible to update the logos only?

We aren't adding new info or anything else just updating the logos.

Thank you

**Pull request merged**
