### PR TITLE
Added Dinger Token logo and info

### PR DESCRIPTION
**Pull request by SchrodingerToken**
This request is to add the logo and info of Schrodinger Token

### CODE REVIEW

**Comment by Cryptocool1** [comment]
hello,
• What is the purpose of this token? How will it benefit Trust Wallet users?
 • How is the token being distributed? Are you conducting an airdrop?
 • Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?
 • Is the token listed on a centralized/decentralized exchange?
 • Is a Smart Contract audit completed? Where can we find this information?

**Comment by jaydinger** [comment]
Hi!

• What is the purpose of this token? How will it benefit Trust Wallet users?
The Dinger project has a long roadmap detailed in our whitepaper.  In summary, the goal is for average person to gain access to launching meme tokens and creating their own unique environments that will help their memes succeed.We are centered around investor protection and the suite of products are created with that in mind. 

• How is the token being distributed? Are you conducting an airdrop?
Tokens were all sold during the ICO with 100% circulating supply.  No airdrops were done.

• Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?
There was no presale conducted.

• Is the token listed on a centralized/decentralized exchange?
The token is not yet listed on a centralized exchanged.  It can be bought on Uniswap.

• Is a Smart Contract audit completed? Where can we find this information?
1st Smart contract audit is currently in progress and being done by https://twitter.com/VidarTheAuditor.  It will be available in the next few days.

**Comment by cryptomanz** [comment]
Awaiting for smart contract audit. On hold for now.

**Comment by jaydinger** [comment]
hi, @cryptomanz, any way for me to send the file in private as it is not yet publicly disclosed?

**Comment by Cryptocool1** [comment]
you can send it here

**Comment by jaydinger** [comment]
[Dinger_Audit_Review.pdf](https://github.com/trustwallet/assets/files/7464618/Dinger_Audit_Review.pdf)

Audit attached.

**Comment by SchrodingerToken** [comment]
hi @Cryptocool1,

May i request for the on-hold label to be removed? Just so Uniswap can also use the logo from your repository.

Thanks in advance!

**Pull request merged**
