### PR TITLE
Add $COCO logo and info

### PR DESCRIPTION
**Pull request by c0c0dev**
Update $COCO token logo and info for the Trust Wallet application.

### CODE REVIEW

**Comment by Cryptocool1** [comment]
As per our policy, brand new tokens are not included, there is a minimum requirement of 2500 holder addresses and 5000 transactions, in order to filter out scam tokens.
See the criteria at (mentioned in the first message by the bot): https://community.trustwallet.com/t/how-to-submit-a-token-logo/3863).
Closing PR for now. Please come back to us when all criteria are met.

**Comment by c0c0dev** [comment]
Please kindly review our request, all criteria for the request are now met at the time of this writing $COCO already have 2,709+ holder and 5,121 transactions and we already done paying 1000 TWT here is the transaction link https://explorer.binance.org/tx/6A66FEEEB957EE1F69A6CFCBA54C5041FFD7F10E033DCA66B166C891DBCAC539. Thank you for your consideration.

**Comment by Cryptocool1** [comment]
> Please kindly review our request, all criteria for the request are now met at the time of this writing $COCO already have 2,709+ holder and 5,121 transactions and we already done paying 1000 TWT here is the transaction link https://explorer.binance.org/tx/6A66FEEEB957EE1F69A6CFCBA54C5041FFD7F10E033DCA66B166C891DBCAC539. Thank you for your consideration.

can't find contract on your website
please check/add

**Comment by c0c0dev** [comment]
Please kindly check it again, our contract is located on the bottom of the page of our public sale and airdrop page here is the link on our website page https://cocotoken.finance/airdrop and here is the image for the part you are looking for
image

**Comment by c0c0dev** [comment]
We have also updated our home page and put our contract address at the top of the page. Thank you!
image

**Comment by c0c0dev** [comment]
Good day! Thank you for your time reviewing our request may I ask if it is possible to update our token logo cause it appears too small on Trust Wallet application. We just want to update it to something like this: 
logo

**Pull request merged**
