### PR TITLE
Add Safegem (BEP20)

### PR DESCRIPTION
**Pull request by SafegemOfficial**
Adding info for BEP20 token 'Safegem'.

PR created by <a href="https://assets.trustwallet.com">TW Assets Management</a>

### CODE REVIEW

**Comment by SafegemOfficial** [comment]
Hi Trust Wallet, Safegem has previously paid to upload the GEMS logo. This Push Request is an update. Is 700 TWT required for an existing asset to be updated?

**Comment by Cryptocool1** [comment]
Hello, yes, the fee is required for updating

**Comment by SafegemOfficial** [comment]
> Hello, yes, the fee is required for updating. You can see this information here: https://developer.trustwallet.com/assets/pr-fee

If additional updates are needed in the future (such as new social links), would that also require an extra fee?

**Comment by Cryptocool1** [comment]
> > Hello, yes, the fee is required for updating. You can see this information here: https://developer.trustwallet.com/assets/pr-fee
> 
> If additional updates are needed in the future (such as new social links), would that also require an extra fee?

Yes, you should pay for every update

**Pull request closed without merging**
