### PR TITLE
RIZE (RIZE) Token request

### PR DESCRIPTION
**Pull request by Christian-RIZE**
See rizetoken.com or contact us through telegram at t.me/rizetoken

### CODE REVIEW

**Comment by Christian-RIZE** [comment]
Should I pay if there are two fails?

**Comment by catenocrypt** [comment]
Yes, please do so.  We receive many PRs with no payment, so per policy, we check those which have paid.
Now I checked this PR, the problem is the name of the logo, it should be `logo.png`within the folder with the name of the contract (in checksum format).  This is fairly easy to fix.  We can assist once fee is paid.

**Comment by Christian-RIZE** [comment]
Is it better to do a new pull request, if so, I will do that and pay there?

**Comment by Christian-RIZE** [comment]
I will do a new pull request

**Pull request closed without merging**
