### PR TITLE
Safemoon finance(sfmf)

### PR DESCRIPTION
**Pull request by lakshmipolisetty**
[json.info.pdf](https://github.com/trustwallet/assets/files/6600895/json.info.pdf)
logo

### CODE REVIEW

**Comment by lakshmipolisetty** [comment]
payment done.

**Comment by lakshmipolisetty** [comment]
is logo fixed ?

**Comment by lakshmipolisetty** [comment]
> **PR Summary**
> File not allowed: 0xb089bf3d6ddcad99bd0a9fbce4262de7d713c43c. Please revert it.

 "name": “SAFEMOON FINANCE Token",
    "website": "https://safemoonfinance.net”,
    "description": “safemoon finance token made with bsc network and its main this is deflationary.”,
    "explorer": "https://bscscan.com/token/0xb089bf3d6ddcad99bd0a9fbce4262de7d713c43c",
    "type": "BEP20",
    "symbol": "SFMF",
    "decimals": 9,
    "status": "active",
    "id": "0xb089bf3d6ddcad99bd0a9fbce4262de7d713c43c"
}

**Comment by lakshmipolisetty** [comment]
[json.info.pdf](https://github.com/trustwallet/assets/files/6601099/json.info.pdf)
logo

**Comment by lakshmipolisetty** [comment]
Token in PR: BEP20 : 0xb089bf3d6ddcad99bd0a9fbce4262de7d713c43c
SYMBOL :SFMF DECIMALS : 9


> **PR Summary**
> File not allowed: 0xb089bf3d6ddcad99bd0a9fbce4262de7d713c43c. Please revert it.

{
"name": “SAFEMOON FINANCE Token",
"website": "https://safemoonfinance.net”,
"description": “safemoon finance token made with bsc network and its main thing is deflationary, and it is a community driven token NFT will start once we list on exchanges.”,
"explorer": "https://bscscan.com/token/0xb089bf3d6ddcad99bd0a9fbce4262de7d713c43c",
"type": "BEP20",
"symbol": "SFMF",
"decimals": 9,
"status": "active",
"id": "0xb089bf3d6ddcad99bd0a9fbce4262de7d713c43c"
}

**Comment by lakshmipolisetty** [comment]
[info.json.txt](https://github.com/trustwallet/assets/files/6602031/info.json.txt)
Logo

**Comment by lakshmipolisetty** [comment]
logo

**Review by lakshmipolisetty — COMMENTED** [review]
Add SFMF logo and info

**Comment by Cryptocool1** [comment]
corrections needed:
- no logo.png in files
- This is a BEp20 token, correct folder is blockchains/smartchain/assets. 
- Info file should be named info.json
- Logo file should be named logo.png

- Please create new PR, follow doc https://community.trustwallet.com/t/how-to-submit-a-token-logo/3863
You may want to try our new Assets app in beta; go to https://assets.trustwallet.com, log on with Github, enter contract ID, logo and some additional info, and it will create a PR for you.
See https://community.trustwallet.com/t/how-to-submit-a-token-logo-using-assets-app/82957.
(Make sure to mention this PR, so that we can see that fee has been paid already here.)

**Pull request closed without merging**
