### PR TITLE
Request to Include Blue Network Logo and Information in Trust Wallet.

### PR DESCRIPTION
**Pull request by bluenetworkteam**
The Blue Network project is excited to enhance user experience by adding our official logo to Trust Wallet. This will help our community easily identify and engage with our token within the wallet interface, fostering greater recognition and trust.

### CODE REVIEW

**Comment by bluenetworkteam** [comment]
> No token files found. If you try to add/modify a token, check the name and location of your files! Logo file must be named exactly 'logo.png'. If you are not adding a token, ignore this message.

The name of the logo file is registered with logo.png in the sent file.

**Comment by bluenetworkteam** [comment]
The name of the logo file is registered with logo.png in the sent file.

**Comment by bluenetworkteam** [comment]
The name of the logo file is registered with logo.png in the sent file.
Logo

**Comment by Cryptocool1** [comment]
Please create new PR, follow doc https://developer.trustwallet.com/listing-new-assets/requirements
You may want to try our Assets app in beta; go to https://assets.trustwallet.com, log on with Github, enter contract ID, logo and some additional info, and it will create a PR for you.
See https://developer.trustwallet.com/listing-new-assets/repository_details

**Comment by Hinaroos67** [comment]
بسیارخوب

**Pull request closed without merging**
