### PR TITLE
Add BTCBAM (BEP20)

### PR DESCRIPTION
**Pull request by aw7855689**

### CODE REVIEW

**Comment by Cryptocool1** [comment]
• What is the purpose of this token? How will it benefit Trust Wallet users?
 • How is the token being distributed? Are you conducting an airdrop?
 • Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?
 • Is the token listed on a centralized/decentralized exchange?
 • Is a Smart Contract audit completed? Where can we find this information?

**Comment by aw7855689** [comment]
> • What is the purpose of this token? How will it benefit Trust Wallet users? • How is the token being distributed? Are you conducting an airdrop? • Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale? • Is the token listed on a centralized/decentralized exchange? • Is a Smart Contract audit completed? Where can we find this information?

• What is the purpose of this token? How will it benefit Trust Wallet users?
Btcbam,
It will be a valid token in the nft and metaverse universe.
It will take place in the nft world with https://nft.btcbam.com/.
https://www.metapotamians.com/,https://map.metapotamians.com/
took its place in the metaverse universe with valid token btcbam in land sales.
It also cooperated with Turkey's leading companies on metaverse. (ASKON, Playland).
Trust wallet users https://nft.btcbam.com/ and https://map.metapotamians.com/
It will be included in the nft and metaverse universe on its platforms.

• How is the token being distributed? Are you conducting an airdrop?
We are just moving user from BTCBAM Chain to BSC Chain. We only did an airdrop to migrate all holders. All holders are real and organic.

• Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?
No pre-sale

• Is the token listed on a centralized/decentralized exchange?
Not yet, but an agreement has been made with the cex.io exchange, the listing date has been received.

• Is a Smart Contract audit completed? Where can we find this information?
https://btcbam.com/BitcoinBam-BSC.pdf

**Comment by cryptomanz** [comment]
Screenshot 2022-05-26 at 16 40 35
can you send an official announcement about migration ?

**Comment by aw7855689** [comment]
> Screenshot 2022-05-26 at 16 40 35
> 
> can you send an official announcement about migration ?

https://twitter.com/btcbamg/status/1529144771452731396?s=28&t=qFSMC-wyf1m6-lQLyScTsg

**Comment by Cryptocool1** [comment]
you have not had any transactions in the last 22 days, on hold for now

**Comment by Cryptocool1** [comment]
Please come back to us when all criteria are met. Make sure to mention this PR so the fee can be reused.

**Pull request closed without merging**
