### PR TITLE
Add EuropaCoin (BEP20)

### PR DESCRIPTION
**Pull request by EuropaCoinFun**
Adding info for BEP20 token 'EuropaCoin'.

PR created by <a href="https://assets.trustwallet.com">TW Assets Management</a>

### CODE REVIEW

**Comment by EuropaCoinFun** [comment]
Audit: https://dessertswap.finance/audits/EURC-BSC-AUDIT-44100361.pdf

**Comment by EuropaCoinFun** [comment]
1.The EURC token offers Trust Wallet users a convenient tool for fast and affordable transactions, including micropayments, cross-border transfers and community engagement, combining practical benefits with elements of fun and memes.
2.The EURC token is distributed via PancakeSwap, and has also been partially distributed in a private presale. No airdrop has been conducted at this time.
3.We held a private sale and presale
4.Yes, our token is listed on PancakeSwap v3
5.We have conducted an audit with DessertFinance https://dessertswap.finance/audits/EURC-BSC-AUDIT-44100361.pdf

> • What is the purpose of this token? How will it benefit Trust Wallet users? • How is the token being distributed? Are you conducting an airdrop? • Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale? • Is the token listed on a centralized/decentralized exchange? • Is a Smart Contract audit completed? Where can we find this information?

**Comment by EuropaCoinFun** [comment]
Hello @cryptomanz1 and @Cryptocool1!
Please let me know if you need any additional information or materials. I’ll be happy to assist!

**Comment by Cryptocool1** [comment]
hello, 
are you listed on CoinMarketCap?

**Comment by EuropaCoinFun** [comment]
Hello @Cryptocool1,
We have provided all the necessary information

**Comment by Cryptocool1** [comment]
Hello, 
After careful review, we cannot add your token because: 
- liquidity is too low
- liquidity is not locked
- smart contract ownership is not renounced
- owner can mint an unlimited amount of tokens
- top three wallets holds 90%+ of the total supply
feel free to come back to us after you review all of concerns and fix them. 
There is no need to pay a fee again, just to make sure to mention this PR in new one so the fee can be reused

**Pull request closed without merging**
