### PR TITLE
SafeTesla Logo

### PR DESCRIPTION
**Pull request by safetesla**

### CODE REVIEW

**Comment by vikmeup** [comment]
We have to reject such PR due to violation of Tesla trademark.

**Comment by safeorbit** [comment]
> We have to reject such PR due to violation of Tesla trademark.

Tesla is international word from Nikola Tesla there i dont see anything about trademark violations !! this is just nonsense

**Comment by safeorbit** [comment]
> We have to reject such PR due to violation of Tesla trademark.

its like i make a coin about u Vik SafeRadchenko do i violate trademark issues?

**Comment by safetesla** [comment]
> We have to reject such PR due to violation of Tesla trademark.

We have rebranded everything from logo also SafeTesla Is written together its like AirBNB to sue Binance for using ticker BNB Thank you !

**Pull request closed without merging**
