### PR TITLE
Add PYX to smartchain (Logo and info)

### PR DESCRIPTION
**Pull request by pyxiscto**
This PR is being closed due to inactivity. If you wish to continue, please have us reopen the PR before sending your payment.
Do NOT send payments for closed PR, as the fee may by lost!
  (151 vs. 99 hrs)

### CODE REVIEW

**Comment by pyxiscto** [comment]
We only have 1250 holders at the moment.
Is that ok?

https://bscscan.com/token/0x3ebb316D8c387ef235BAa38978cbB9B97C8C3017

**Comment by catenocrypt** [comment]
As per our policy, brand new tokens are not included, there is a minimum requirement of 2500 holder addresses and 5000 transactions, in order to filter out scam tokens.
See the criteria at (mentioned in the first message by the bot): https://community.trustwallet.com/t/how-to-submit-a-token-logo/3863).
This token has below-limit usage yet (1200 holders). Closing PR for now. Please come back to us when all criteria are met.  Multi-chain and staking tokens may get special treatment, let us know if this is the case. 

https://bscscan.com/token/0x3ebb316D8c387ef235BAa38978cbB9B97C8C3017

**Comment by pyxiscto** [comment]
Hi,@catenocrypt 

We currently have 

Holders:
1,007 addresses
Transfers:
10,369

There are only 1,000 holders because when people stake, 
the tokens will be transferred to smart contracts, so the number is reduced.

https://bscscan.com/token/0x3ebb316D8c387ef235BAa38978cbB9B97C8C3017#balances

You can also check the statistics about staking from this API:
https://stpyxis.blob.core.windows.net/api-data/stats.json

Could you reconsider us, please?

Much appreciated your time, brother.

Kind regards,
PYXIS Founder

**Comment by catenocrypt** [comment]
Circulation exception accepted as this is a staking token.  Submission is OK.  Awaiting fee payment.

**Comment by pyxiscto** [comment]
@catenocrypt 
Hey Adam,

Somehow the merge-fee-bot closed the PR. Could you reopen it, please? So I can make a transfer.

Kind regards,
PYXIS Founder

**Comment by catenocrypt** [comment]
After reopen, the PR may get auto-closed, but fee payment can be made, just ask for reopen again.

**Comment by pyxiscto** [comment]
@catenocrypt 

Hi Adam,

Much appreciated your time, mate.

I've transferred 250.2 TWT with memo 6185 to 
bnb1tqq9llyr3dyjd559dha6z5r5etk3qfwk07m098.

Could you have a check, please?

Kind regards,
PYXIS Founder

**Comment by pyxiscto** [comment]
@catenocrypt 

Transaction brother: https://explorer.binance.org/tx/82509D373302F1DFAC5318FD2FDE724879662659A4D68BB026C7F11A314D8188

**Pull request merged**
