### PR TITLE
Add Infinite Hopium (BEP20)

### PR DESCRIPTION
**Pull request by ihopcoin**
Adding info for BEP20 token 'Infinite Hopium'.

PR created by <a href="https://assets.trustwallet.com">TW Assets Management</a>

### CODE REVIEW

**Comment by cryptomanz1** [comment]
As per our policy, there is a minimum requirement of 10,000 holder addresses and 15,000 transactions, in order to filter out scam tokens.
See the criteria at : https://developer.trustwallet.com/listing-new-assets/requirements .

**Comment by cryptomanz1** [comment]
your token is 2 days old, we are not accept brand new tokens. Please come back to us once all criteria are met. Fell free to create new PR we can reuse your payment

**Comment by ihopcoin** [comment]
Hi! We made new PR and got listed on several exchanges can you please re-review our coin?

**Review by ihopcoin — COMMENTED** [review]
Hi! Can you please review our coin once again we made new PR and got listed on exchanges?

**Pull request closed without merging**
