### PR TITLE
Add Rocket Pool (ERC20)

### PR DESCRIPTION
**Pull request by darrenlangley**
This PR is being closed due to inactivity. If you wish to continue, please have us reopen the PR before sending your payment, or just create a new one.
Do NOT send payments for closed PR, as the fee may by lost!
  (48 vs. 48 hrs)

### CODE REVIEW

**Comment by ramsty** [comment]
As per our policy, brand new tokens are not included, there is a minimum requirement of 5000 holder addresses and 10000 transactions, in order to filter out scam tokens.
See the criteria at (mentioned in the first message by the bot): https://community.trustwallet.com/t/how-to-submit-a-token-logo/3863).
Closing PR for now. Please come back to us when all criteria are met.

**Comment by darrenlangley** [comment]
@ramsty sorry for not adding more detail to the PR but the RPL token is not a new token it is a migration to a new contract. The old contract is here https://etherscan.io/token/0xb4efd85c19999d84251304bda99e90b92300bd93#balances and has over 13k holders. Would you mind reopening the PR please?

**Comment by ramsty** [comment]
Can you send an official announcement about migration?

**Comment by darrenlangley** [comment]
Will do

**Comment by darrenlangley** [comment]
> Can you send an official announcement about migration?

@ramsty here are our official announcements:
https://twitter.com/Rocket_Pool/status/1462960837379780615
https://medium.com/rocket-pool/rocket-pool-rpl-token-upgrade-new-addresses-e96c12c55adf

Would you mind reopening the PR please?

**Comment by kanewallmann** [comment]
@ramsty Can you please reopen this PR so we can make payment?

**Pull request closed without merging**
