### PR TITLE
Update info token Bep20

### PR DESCRIPTION
**Pull request by MichaelCS83**

### CODE REVIEW

**Comment by cyruscoin** [comment]
Hi, I have a question, should the payment be in bnb and equal to 250 twt?

**Comment by MichaelCS83** [comment]
Hello,
I sent a request to update logo token bep20 2 days ago,
and I have paid in full,
But why is my logo not updated yet,
Please settle for me, please

Vào Th 7, 24 thg 4, 2021 vào lúc 15:05 merge-fee-bot[bot] <
***@***.***> đã viết:

**Comment by MichaelCS38** [comment]
wait!!!

**Comment by MichaelCS83** [comment]
Hello,
I sent a request to update logo token bep20
and I have paid in full,
But why is my logo not updated yet,
Please settle for me, please

**Comment by Iamdeadlyz** [comment]
Hi @MichaelCS83, not sure why you closed this PR yourself. Do you want to re-open and proceed with this PR?

**Pull request closed without merging**
