### PR TITLE
delist old token

### PR DESCRIPTION
**Pull request by tokyo786**
In order to avoid confusion of many versions tokens with same logo, PLEASE DELIST (0x4bf62424385ddcd858535caa1878e512314a9aeb) because it has been upgraded to  (0x2Da95f7e0093CE7DC9D9BA5f47b655108754B342)

Official Announcement: https://twitter.com/ReliableIndex/status/1175013318508994560

### CODE REVIEW

**Comment by lavimalik** [comment]
Official Announcement: 
https://twitter.com/ReliableIndex/status/1175013318508994560

**Comment by kolya182** [comment]
@lavimalik Thanks

**Comment by lavimalik** [comment]
@kolya182 you're welcome
And Thank You as well for being so quick!

All The Best!

**Comment by lavimalik** [comment]
@kolya182 the de-listed token did not disappear from search yet and the listed token doesn't show up in the search yet, any comments or updates about it? Any idea when can newly listed token show up in search and de-listed token disappear from search?

Thanks!

**Comment by kolya182** [comment]
> @kolya182 the de-listed token did not disappear from search yet and the listed token doesn't show up in the search yet, any comments or updates about it? Any idea when can newly listed token show up in search and de-listed token disappear from search?
> 
> Thanks!

We aware of this, and working fixing it. Normally it takes up to 1 hour to show up in the search, and we also want to make in instantly. Give us couple of day.

**Comment by lavimalik** [comment]
> We aware of this, and working fixing it. Normally it takes up to 1 hour to show up in the search, and we also want to make in instantly. Give us couple of day.

Okay, it's need more than 3 days since we listed new token.

Sure take your time, hope the listed token shows up in search in about a day or two.

Thanks a lot for the quick replying!

**Pull request merged**
