### PR TITLE
Add SpongeBob Square (BEP20)

### PR DESCRIPTION
**Pull request by anniesapu**
Adding info for BEP20 token 'SpongeBob Square'.

PR created by <a href="https://assets.trustwallet.com">TW Assets Management</a>

### CODE REVIEW

**Comment by cryptomanz** [comment]
Hello,
Please follow the rules for adding token, your logo should be a full screen, 256x256.

**Comment by spongebobsquareE** [comment]
0x471f883BBd2c705F418Ba3d6667ef05342C4ee05

**Comment by spongebobsquareE** [comment]
NEW LOGO WITH 256x256 FRAME RATE

**Comment by spongebobsquareE** [comment]
https://github.com/trustwallet/assets/pull/17306

**Comment by spongebobsquareE** [comment]
Is it like this ? [image: spong.PNG]

Pada tanggal Kam, 13 Jan 2022 pukul 20.31 Nazar ***@***.***>
menulis:

**Comment by cryptomanz** [comment]
• What is the purpose of this token? How will it benefit Trust Wallet users?
 • How is the token being distributed? Are you conducting an airdrop?
 • Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?
 • Is the token listed on a centralized/decentralized exchange?
 • Is a Smart Contract audit completed? Where can we find this information?

**Comment by spongebobsquareE** [comment]
• What is the purpose of this token? How will it benefit Trust Wallet
users? $Spong is a meme token, but this $Spongs has its own web marketplace
that provides hoodies that can be purchased using the $Spong token
The SPONGS Marketplace has the ability has the advantage of being a
marketplace that can use SPONGS tokens.

• How is the token being distributed? Are you conducting an airdrop? Fair
Launch

• Did you sold the tokens at an Initial Coin Offering (ICO) or a token
presale? No

• Is the token listed on a centralized/decentralized exchange? Yes $SPONGS
Listing Vindax & Pancakeswap

• Is a Smart Contract audit completed? Where can we find this information?
process

Pada tanggal Jum, 14 Jan 2022 pukul 00.05 Nazar ***@***.***>
menulis:

**Comment by spongebobsquareE** [comment]
[https://www.coinscope.co/coin/spongs/audit](url)

**Comment by spongebobsquareE** [comment]
https://github.com/coinscope-co/audits/blob/main/spongs/audit.pdf

Pada tanggal Jum, 14 Jan 2022 pukul 01.40 CryptoA ***@***.***>
menulis:

**Comment by spongebobsquareE** [comment]
https://github.com/coinscope-co/audits/blob/main/spongs/audit.pdf

@Cryptocool1

**Pull request merged**
