### PR TITLE
Add MultiFunctional Environmental Token (BEP20)

### PR DESCRIPTION
**Pull request by musacanminaz**
Adding info for BEP20 token 'MultiFunctional Environmental Token'.

PR created by <a href="https://assets.trustwallet.com">TW Assets Management</a>

### CODE REVIEW

**Comment by Cryptocool1** [comment]
As per our policy, brand new tokens are not included, there is a minimum requirement of 10,000 holder addresses and 15,000 transactions, in order to filter out scam tokens.
See the criteria at : https://developer.trustwallet.com/assets/requirements .

**Comment by musacanminaz** [comment]
Hi,

I understand your r requirement rules but,

We don’t want to make our holder count to 10k with fake airdrops. Our 3k holder is real.

We are a strong project if you check your pool on pancake an we have been on market over 1 year. 

We have a 425K total value pool in pancake swap and its lock for 2 years

All team is open in our web page.

Please consider us to add trust wallet.

Thanks for your help

**Comment by Cryptocool1** [comment]
We are not accept airdropped tokens.
Are you listed on CMC? 
Is a smart contract audit completed?

**Comment by musacanminaz** [comment]
We are waiting to list in assets repo to apply to CMC

When people come from CMC we want that they can see your token in wallet.

Its important to show our self a strong project.

Our all contracts have audit by safetin you can find them in our GitHub and documents sections.

Thanks for your help

https://dfpqi3dzezrqp.cloudfront.net/public/docs/main-audit.pdf￼
main-audit
PDF Document · 237 KB
https://dfpqi3dzezrqp.cloudfront.net/public/docs/stake-audit.pdf
https://dfpqi3dzezrqp.cloudfront.net/public/docs/lock-audit.pdf￼
lock-audit
PDF Document · 231 KB

**Comment by Cryptocool1** [comment]
Please see our listing criteria here: 
https://developer.trustwallet.com/assets/requirements

**Comment by musacanminaz** [comment]
Yes we all check the list

* Token should be listed on price tracking sites like CoinmarketCap

We have been listed on Coingecko and Comics

* Minimum 10,000 token holders and 15,000 transactions (Airdrop tokens excluded). This requirement is subject for review based on the project.

We are a strong project so you can review us. 

Our pancake pool value is over 400.000 BUSD and locked for 2 years.

All other information is correct.

Thanks for your help

**Comment by Cryptocool1** [comment]
We are taking price only from CoinMarketCap, please let us know once your token is listed there

**Comment by musacanminaz** [comment]
Ok then I am making request to CMC today.

Then write you back.

Thank you very much.

**Comment by musacanminaz** [comment]
Hello

We have listed on CMC and we are ready to list in trust wallet. 

We will we do next ?


https://coinmarketcap.com/currencies/multifunctional-environmental-token/

**Pull request closed without merging**
