### PR TITLE
Add STACK Token

### PR DESCRIPTION
**Pull request by JonasBayes**
STACK token info and logo

### CODE REVIEW

**Comment by catenocrypt** [comment]
As per our policy, brand new tokens are not included, there is a minimum requirement of 2500 holder addresses and 5000 transactions, in order to filter out scam tokens.
See the criteria at (mentioned in the first message by the bot): https://community.trustwallet.com/t/how-to-submit-a-token-logo/3863).
This token has low usage yet (146 holders). Putting PR on hold for now. Please come back to us when all criteria are met.  Multi-chain and staking tokens may get special treatment, let us know if this is the case. 

https://etherscan.io/token/0xe0955f26515d22e347b17669993fcefcc73c3a0a

**Comment by JonasBayes** [comment]
> As per our policy, brand new tokens are not included, there is a minimum requirement of 2500 holder addresses and 5000 transactions, in order to filter out scam tokens.
> See the criteria at (mentioned in the first message by the bot): https://community.trustwallet.com/t/how-to-submit-a-token-logo/3863).
> This token has low usage yet (146 holders). Putting PR on hold for now. Please come back to us when all criteria are met. Multi-chain and staking tokens may get special treatment, let us know if this is the case.
> 
> https://etherscan.io/token/0xe0955f26515d22e347b17669993fcefcc73c3a0a

Hi, we have many people with unclaimed STACK balances through farming. 

Though we are new, we have some strong backers, are organized as one of the top Aragon venture DAOs by total assets, and have over $2,000,000 TVL in our first product.

I believe it would be worth taking another look if you have time as I think it would be beneficial not having people buying fake tokens just because we are new on the block :) If not, happy to check back in when more people claim their STACK rewards from staking ETH.

**Comment by catenocrypt** [comment]
Is there stats available on the number of staked amounts?

**Comment by JonasBayes** [comment]
> Is there stats available on the number of staked amounts?

It would still be less than 2,500 if that is a 100% prerequisite, but figured the quality of the project would also factor in since it is so easy to fake these numbers by just splitting wallets (like many of these projects do when launching to look more popular). We can just check back in when we have 2,500 though. Thanks for your time.

**Comment by catenocrypt** [comment]
No new action for a month, closing for now.

**Comment by JonasBayes** [comment]
Hi, we now have over $30 million TVL, over 5,000 transfers on L1, token trading on Polygon, and 500+ governance token holders.

I was hoping you could reconsider merging this as we have grown substantially since launch and a few people have purchased the wrong STACK due to no logo appearing.

Thank you!

**Comment by JonasBayes** [comment]
> No new action for a month, closing for now.

If you could take one more look it would be appreciated. Thanks!

**Comment by JonasBayes** [comment]
@catenocrypt Would you be able to look at this one more time?

We now have around $30 million TVL, #30 yield farm, over 5,000 transfers on L1, 10,000 transfers on L2, about 1000 token holders, and around 500 more that can claim token rewards from yield farming.

I was hoping you could reconsider merging this as we have grown substantially since launch and a few people have purchased the wrong STACK due to no logo appearing.

Thank you!

**Pull request closed without merging**
