### PR TITLE
Add OPM logo reopen this

### PR DESCRIPTION
**Pull request by bitbd83**

### CODE REVIEW

**Comment by bitbd83** [comment]
Payment tx:  B464D184EEB306449ED47CB69972D9E17A0BD0D757F4FFCD30A0A4B75A83D2CC

**Comment by bitbd83** [comment]
Now forward to adding pDAI

**Comment by bitbd83** [comment]
Please restore and merge this PR. I accidentally closed this.

**Comment by catenocrypt** [comment]
Reopened. Is this still valid?

**Comment by zachzwei** [comment]
Token activity does not meet the minimum requirements.
Pull request will be put on Hold.
Learn more here:
https://community.trustwallet.com/t/how-to-submit-a-token-logo/3863#how-to-get-approved

**Pull request closed without merging**
