### PR TITLE
Add TRUSTxGAMING (BEP20)

### PR DESCRIPTION
**Pull request by TRUSTxGAMING**
Adding info for BEP20 token 'TRUSTxGAMING'.

PR created by <a href="https://assets.trustwallet.com">TW Assets Management</a>

### CODE REVIEW

**Comment by Cryptocool1** [comment]
• What is the purpose of this token? How will it benefit Trust Wallet users?
 • How is the token being distributed? Are you conducting an airdrop?
 • Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?
 • Is the token listed on a centralized/decentralized exchange?
 • Is a Smart Contract audit completed? Where can we find this information?

**Review by Sandraisom — COMMENTED** [review]
bnb158fgd782we4tz9vwwcj9pmmxvxhl6z46lfm7c8

**Comment by cryptomanz1** [comment]
This is a BEP20 token, correct folder is blockchains/smartchain/assets. 
Please create new PR, follow doc https://developer.trustwallet.com/listing-new-assets/requirements
You may want to try our Assets app in beta; go to https://assets.trustwallet.com, log on with Github, enter contract ID, logo and some additional info, and it will create a PR for you.
See https://developer.trustwallet.com/listing-new-assets/repository_details

**Comment by TRUSTxGAMING** [comment]
> This is a BEP20 token, correct folder is blockchains/smartchain/assets. Please create new PR, follow doc https://developer.trustwallet.com/listing-new-assets/requirements You may want to try our Assets app in beta; go to https://assets.trustwallet.com, log on with Github, enter contract ID, logo and some additional info, and it will create a PR for you. See https://developer.trustwallet.com/listing-new-assets/repository_details

hello why this is closed. We want to continue the Asset addition process.

**Pull request closed without merging**
