### PR TITLE
Added logo

### PR DESCRIPTION
**Pull request by PatrickDehkordi**
This a the Empty Set Dollar logo. The project meets all the requirements and it is currently top 10 liquidity on uniswap. 
Further info about the project here:
https://emptyset.finance

This is the same PR as 4619. 
4619 passes your auto checks. 
We only paid for this PR. They are identical for our tokens directory. Accept either one. 

thanks.

### CODE REVIEW

**Comment by PatrickDehkordi** [comment]
Do I need the json file? It seems to create an error with the auto scripts but this is the json file: 

{
  "name": "Empty Set Dollar",
  "website": "https://emptyset.finance/",
  "source_code": "https://github.com/emptysetsquad",
  "white_paper": "https://github.com/emptysetsquad/dollar-docs",
  "short_description": "Stablecoin",
  "explorer": "https://etherscan.io/token/0x36f3fd68e7325a35eb768f1aedaae9ea0689d723",
  "research": "https://docs.esd.tools/"
  }

**Comment by PatrickDehkordi** [comment]
Not clear on why your auto checker creates errors,  pklese let me know if there is anything you like me to change.

**Comment by PatrickDehkordi** [comment]
I re did this with pull request 4619. They are identical. However we only paid here. I think I started from an older repo here that is why it failed. So either process 4617 or 4619, They are redundant but 4619 passes the auto checks.

**Comment by Iamdeadlyz** [comment]
Closing

**Pull request closed without merging**
