### PR TITLE
add FRAX and FXS bsc info

### PR DESCRIPTION
**Pull request by jasonhuan**
Adding FRAX and FXS info for our bridge to Binance Smart Chain. Last PR for Ethereum located here: https://github.com/trustwallet/assets/pull/5265

### CODE REVIEW

**Comment by zachzwei** [comment]
Please use checksum address for the folders.

**Comment by jasonhuan** [comment]
changed folders to ue checksum addresses

**Comment by catenocrypt** [comment]
Minor correction needed:  ID fields must be in checksum format, matching the folder name.  Please check.
I wanted to check but could not push to this PR.

```
XXX   'Wrong casing for id '0x0302457510b33851d87c1385f10419634688e08a' 'smartchain' /home/runner/work/assets/assets/blockchains/smartchain/assets/0x0302457510B33851d87C1385f10419634688E08a/info.json'
   XXX   'Wrong casing for id '0x6dbd9f670f2554d6400e53712d6e200414342cae' 'smartchain' /home/runner/work/assets/assets/blockchains/smartchain/assets/0x6dBD9F670F2554d6400e53712D6e200414342cAe/info.json'
```

**Comment by jasonhuan** [comment]
Should be working now, thanks

**Pull request merged**
