### PR TITLE
Add Ultgg (BEP20)

### PR DESCRIPTION
**Pull request by cja-x**

### CODE REVIEW

**Comment by Cryptocool1** [comment]
can you please answer some questions?
• What is the purpose of this token? How will it benefit Trust Wallet users?
 • How is the token being distributed? Are you conducting an airdrop?
 • Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?
 • Is the token listed on a centralized/decentralized exchange?
 • Is a Smart Contract audit completed? Where can we find this information?

**Comment by cja-x** [comment]
@Cryptocool1 

1) What is the purpose of this token? How will it benefit Trust Wallet users? 
ULTGG IS THE REVOLUTIONARY GAMING TOKEN FROM ULTIMO GG.
Get rewarded for everything you do on the platform, from winning tournaments to creating content and contributing to the community, then spend your ULTGG on the ULTIMO GG platform and our partners. Purchase NFTs or even create your own featuring your greatest gaming moments with ULTIMO GG or convert ULTGG into FIAT to turn your dream of a career in gaming into a reality. https://www.ultgg.io/

2) How is the token being distributed? Are you conducting an airdrop?
ULTGG Tokens were distributed via an Airdrop using https://cointool.app 

3) Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?
We conducted a private and public presale. Both offering a fair price to Pancake swap and with the same Maximum contribution.

4) Is the token listed on a centralized/decentralized exchange?
Our token is currently on a decentralized exchange, Pancake swap, 
https://exchange.pancakeswap.finance/#/swap?outputCurrency=0x2065e3bd318f155abe5ad6aa263596f197112261

5) Is a Smart Contract audit completed? Where can we find this information?
We are in the process of getting a Techrate audit and we are also getting a Certik Audit also.

**Comment by cryptomanz** [comment]
Hello,
- Awaiting for smart contract audit.

**Comment by cja-x** [comment]
Hi @cryptomanz yes our Techrate audit is underway.
we haven't read anywhere that this is a hard requirement to include our logo on tw

**Comment by Cryptocool1** [comment]
Hello,
please create new PR when smart contract audit will be ready.
make sure to mention this PR, so that we can see that fee has been paid already here.

**Pull request closed without merging**
