### PR TITLE
Adding unido

### PR DESCRIPTION
**Pull request by ashish-khokhar**

### CODE REVIEW

**Comment by ashish-khokhar** [comment]
Closing due to errors

**Comment by catenocrypt** [comment]
Correction needed: folder corresponding to token contract must be in 'checksum' format, please rename (you may need to rename in 2 phases as lowercase-uppercase-only renames may be ignored by the filesystem/git).

   XXX   'Expect asset at path /home/runner/work/assets/assets/blockchains/ethereum/assets/0xea3983fc6d0fbbc41fb6f6091f68f3e08894dc06 in checksum: '0xea3983Fc6D0fbbC41fb6F6091f68F3e08894dC06''

**Comment by ashish-khokhar** [comment]
@catenocrypt Thanks for the correction, my bad, will fix it ASAP

**Comment by catenocrypt** [comment]
Payment considered for #6510 .

**Comment by catenocrypt** [comment]
Payment for this PR: 2 BNB https://explorer.binance.org/tx/5F1F8F58623C590567236CD344F6E041DC8CF4DABA06921083E4B618D98E1C73

**Pull request closed without merging**
