### PR TITLE
add BWF logo

### PR DESCRIPTION
**Pull request by quickomofficial**
we want to update BWF logo on Trust Wallet

### CODE REVIEW

**Comment by catenocrypt** [comment]
Note: Low circulation tokens are not added as per our policy (only 12 holder addresses); however as this token was already added, logo change is ok.
Fee payment is needed though.

**Comment by catenocrypt** [comment]
Please add an `info.json` file next to the `logo.png`, with info about the project, of the form:

```json
{
    "name": "Trust Wallet Token",
    "website": "https://trustwallet.com",
    "short_description": "Utility token to increase adoption of cryptocurrency.",
    "explorer": "https://explorer.binance.org/asset/TWT-8C2"
}
```

**Comment by phuongbwf** [comment]
Hi

Please guide me how to update the info.json. How to commit a new one.

Thanks.

**Comment by phuongbwf** [comment]
I have added content for json.info. Please review. Thanks

**Comment by Iamdeadlyz** [comment]
As per our policy, brand new tokens are not included. There is a minimum requirement of 500 holder addresses and 1000 transactions in order to filter out scam tokens. See the criteria at (mentioned in the first message by the bot): https://community.trustwallet.com/t/how-to-submit-a-token-logo/3863#how-to-get-approved

This token has below-limit usage yet. This pull request will be but on hold. Please come back to us when all criteria are met.
https://etherscan.io/token/0xF7E04D8a32229B4cA63aA51eEA9979C7287FEa48

**Comment by phuongbwf** [comment]
Hi Ian,

Per conversation with Adam, our token is ok for logo adding. This was
confirmed yesterday. Please check back our history conversations. I
attached here please have a check.

Our token has been listed on Bittrex  and also verified on CMC / Coingecko.

Please consider.

Thank you. Regards

**Comment by Iamdeadlyz** [comment]
> Per conversation with Adam, our token is ok for logo adding. This was

Thanks for the heads up

**Pull request merged**
