### PR TITLE
Add Pieme (BEP20)

### PR DESCRIPTION
**Pull request by voxmagna1**
Adding info for BEP20 token 'Pieme'.

PR created by <a href="https://assets.trustwallet.com">TW Assets Management</a>

### CODE REVIEW

**Comment by voxmagna1** [comment]
I have paid for this token on this:
https://github.com/trustwallet/assets/pull/19951

**Comment by Cryptocool1** [comment]
As per our policy, brand new tokens are not included, there is a minimum requirement of 10,000 holder addresses and 20,000 transactions, in order to filter out scam tokens.
See the criteria at : https://developer.trustwallet.com/assets/requirements .

**Comment by voxmagna1** [comment]
Thank you. 
Can we issue a refund or we can reaply without paying when we reach that numbers ?

**Comment by cryptomanz** [comment]
Please come back to us when all criteria are met.
When creating a new PR make sure to mention this PR, so that we can see that fee has been paid already here.

**Comment by cryptomanz** [comment]
Please come back to us when all criteria are met.
When creating a new PR make sure to mention this PR, so that we can see that fee has been paid already here.

**Pull request closed without merging**
