### PR TITLE
Add TOWER token info and logo

### PR DESCRIPTION
**Pull request by antonysze-ani**
Adding TOWER token log following the guild-line:
https://community.trustwallet.com/t/how-to-submit-a-token-logo/3863

### CODE REVIEW

**Comment by catenocrypt** [comment]
Correction needed: folder corresponding to token contract should be in checksum format.
Please rename or create new PR with the correct path.

XXX   'Expect asset at path /home/runner/work/assets/assets/blockchains/ethereum/assets/0x1c9922314ed1415c95b9fd453c3818fd41867d0b in checksum: '0x1C9922314ED1415c95b9FD453c3818fd41867d0B''

**Comment by catenocrypt** [comment]
Fix in the values is OK, but not in the folder name.  A rename where only the casing changes may be tricky, you may need to rename it twice:

```
git mv blockchains/ethereum/assets/0x1c9922314ed1415c95b9fd453c3818fd41867d0b blockchains/ethereum/assets/0x1C9922314ED1415c95b9FD453c3818fd41867d0B.TEMP
git mv blockchains/ethereum/assets/0x1C9922314ED1415c95b9FD453c3818fd41867d0B.TEMP blockchains/ethereum/assets/0x1C9922314ED1415c95b9FD453c3818fd41867d0B
```

**Comment by antonysze-ani** [comment]
Just fixed in 02ebc1e

**Comment by antonysze-ani** [comment]
Please let me know if there is no more correction needed and it is ready to pay, many thanks!

**Comment by antonysze-ani** [comment]
@catenocrypt Hi! I would like to know if this is still under reviewing or ready to pay. If it is ready, would you remove the label "Status: Correction needed" so that we make sure no problem and pay.

**Comment by catenocrypt** [comment]
Submission looks OK.

**Pull request merged**
