### PR TITLE
Add Falafel Coin (BEP20)

### PR DESCRIPTION
**Pull request by falafeltoken**
Adding info for BEP20 token 'Falafel Coin'.

PR created by <a href="https://assets.trustwallet.com">TW Assets Management</a>

### CODE REVIEW

**Comment by falafeltoken** [comment]
I have applied 11 days ago before you change any requirements, but your team did not reply to the issue I had with your Assets app, please check this thread for your reference:
https://github.com/trustwallet/assets/pull/15722#issuecomment-969339381

Your staff did not address that issue, I used your tool (https://assets.trustwallet.com ) before anything else but the issue did not allow me to proceed with the request (suddenly it worked yesterday and today but after you changed your requirements). I tried many times then with no avail! Here's the screenshot again from 11 days ago:

https://imgur.com/a/CVwtw3U

After I clicked 'OK' nothing happened, and I tried this many times on different browsers, devices and network connections. Nothing worked! So I assumed it's a bug and I was hoping that your staff reply but no one did (as you can see in the github link above)!

I did open another request yesterday and raised this complain, your staff also avoided the fact that they did not reply last time (11 days ago), by saying that 'I did not add links to my last request'. Even if we ignore your Assets app issue, I also submitted the request manually after following steps from your official guide (https://community.trustwallet.com/t/how-to-submit-a-token-logo/3863). Now, can you please show me where you've mentioned that 'links' should be added in that page? Not even shown in the info.json script! See the screenshot:

https://imgur.com/a/jxlNZrF

As you can see, there is no 'links' field! Otherwise, I would've already added them there as I'm doing on your broken Assets app page!

That means, in either way, I have the right to carry on my old request from 11 days ago.

My project is the first one to ever release a Play2Earn game on the Apple App store, and I'm not getting a proper support, but only agents from blackmarket that spread rumours about your company. And I started believing them!

I will keep on opening requests and doing everything possible to escalate this matter until it's properly addressed!

Cheers

**Comment by falafeltoken** [comment]
@cryptomanz, why did you close this? Can't you see that I have requested a further details regarding my old request? If you don't want to answer, then escalate! I'm doing that from my end anyway, and I'm submitting complaints regarding this bad service.

**Comment by Cryptocool1** [comment]
you create a lot of duplicates

**Comment by Cryptocool1** [comment]
the first submitted PR was not closed

**Comment by falafeltoken** [comment]
That’s the only ticket I’m asking about, I was looking for someone who can
understand the issue that I was eligible days ago before you change
requirements, but your faulty Assets app and your guide lacking links field
prevented this

**Pull request closed without merging**
