### PR TITLE
Add Anti Token (BEP20)

### PR DESCRIPTION
**Pull request by emojidaobsc**
Adding info for BEP20 token 'Anti Token'.

PR created by <a href="https://assets.trustwallet.com">TW Assets Management</a>

### CODE REVIEW

**Comment by emojidaobsc** [comment]
merge ： https://github.com/trustwallet/assets/pull/20349
TX HASH : 4A9787BBF317E3C21FBAE49D22B3CFB095EA11EC9664E62C6EC824D6C4A6AB18
merge: #20349
merge: #20368

**Comment by emojidaobsc** [comment]
•This token is to allow users to get better circulation in the application, and users of TrustWallet can get airdropped tokens.
•Token 100% added liquidity
•No presale，No ICO
• listed on pancakeV2 exchange
• Audit：https://github.com/AntiBet/Audit/files/8739045/Certik.Audit.Report.ANTI.BET.Game.Platform.Security.Assessment.pdf
• Holders：10052
• Holders links:  https://bscscan.com/token/0x7ccfda7bf90b8446170f0c8c6a6f356be8a9c6fc#balances

**Comment by cryptomanz** [comment]
re you conducting an airdrop?

**Comment by emojidaobsc** [comment]
> are you conducting an airdrop?

yes

**Comment by emojidaobsc** [comment]
@cryptomanz 
Why was my merge request rejected? I have paid the fee, which is reflected in #20349 and  #20368

**Comment by Cryptocool1** [comment]
Please see our requirements, we are not accept airdrop tokens. For them they should meet 20.000 holders and 25.000 transactions requirement

**Comment by Cryptocool1** [comment]
your token is fully airdropped within 2 weeks
Снимок экрана 2022-05-21 в 12 42 26

**Comment by Cryptocool1** [comment]
Come back to us once all criteria are met. Make sure to mention this PR so the fee can be reused

**Pull request closed without merging**
