### PR TITLE
Add SafeBLAST (BLAST) (ERC20)

### PR DESCRIPTION
**Pull request by Shyamthakur33**
Adding info for ERC20 token 'SafeBLAST (BLAST)'.

PR created by <a href="https://assets.trustwallet.com">TW Assets Management</a>

### CODE REVIEW

**Comment by Shyamthakur33** [comment]
@Cryptocool1 @cryptomanz @Iamdeadlyz

Dear Admins
We already have a verified logo in Trust wallet for our bep20 token. Now we are on the Ethereum chain too. It is the same token with a bridge to the Eth platform. Our erc20 token also has been updated on CMC and CG. Could you please help to update the logo for the eth platform? thanks

**Comment by Iamdeadlyz** [comment]
Double-checking...
- #7935 - Your BEP20 version is indeed in the repo and you are using the same account.
- `0x614D7f40701132E25fe6fc17801Fbd34212d2Eda` matches the contract address stated in the website and Telegram channel

@Shyamthakur33 To proceed with the merge, please finalize the [merge fee](https://github.com/trustwallet/assets/pull/20836#issuecomment-1144462348)

**Comment by Shyamthakur33** [comment]
> Double-checking...
> 
> * [Add SafeBLAST ( BLAST ) logo ( bep20 ) #7935](https://github.com/trustwallet/assets/pull/7935) - Your BEP20 version is indeed in the repo and you are using the same account.
> * `0x614D7f40701132E25fe6fc17801Fbd34212d2Eda` matches the contract address stated in the website and Telegram channel
> 
> @Shyamthakur33 To proceed with the merge, please finalize the [merge fee](https://github.com/trustwallet/assets/pull/20836#issuecomment-1144462348)

thanks
waiting...

**Comment by Shyamthakur33** [comment]
> @Iamdeadlyz

@Iamdeadlyz any update pls?

**Comment by Cryptocool1** [comment]
> > @Iamdeadlyz
> 
> @Iamdeadlyz any update pls?

Hello, you should pay the fee

**Comment by Shyamthakur33** [comment]
> > > @Iamdeadlyz
> > 
> > 
> > @Iamdeadlyz any update pls?
> 
> Hello, you should pay the fee

@Cryptocool1 payment done

**Pull request merged**
