### PR TITLE
Add BitBurn (BEP20)

### PR DESCRIPTION
**Pull request by bitburnio**
Adding info for BEP20 token 'BitBurn'.

PR created by <a href="https://assets.trustwallet.com">TW Assets Management</a>

### CODE REVIEW

**Comment by bitburnio** [comment]
B417AA8A2DC53F746E01C21F5D7FC105138D86CB5A2C41F0E6463B1EE2448127TX hashWhen can we expect to see the logo?BitBurn Official
    
  

 From: merge-fee-bot[bot] ***@***.***>Sent: Thursday, August 11, 2022 2:28 PMTo: trustwallet/assets ***@***.***>Cc: BitBurn ***@***.***>; Author ***@***.***>Subject: Re: [trustwallet/assets] Add BitBurn (BEP20) (PR #21905) 

Hi! In order to compensate for the efforts of processing PRs, we kindly ask for a contribution.

💀 As there is no refund, before paying the fee, make sure new tokens fulfill the minimum circulation and other acceptance criteria.

See also the PR Fee FAQ.

Please pay  700 TWT  with the memo 21905  to the address bnb1tqq9llyr3dyjd559dha6z5r5etk3qfwk07m098.

Alternatively, 5 BNB is also accepted (same memo & address).

QR code: Trust | other wallet

Notes:



Trust Wallet Tokens (TWT) can be obtained through our Referral Program or from DEXs/exchanges.

New tokens without significant usage are rejected, see criteria mentioned above.

One PR should be for a single project; PR's with more than 10 logos will be rejected.

Payment evaluation happens automatically, but with a few minutes delay.  When payment is detected, an Accept Review is automatically placed on the PR, which is a condition for merge.

Evaluating the PR is done manually, and it is merged only if all conditions are satisfied.

TWT-BEP2 is supported (Binance Chain), TWT-BEP20 version on Smart Chain is not.



There will be a fee to process this request. None of it goes to the developers.

Before paying the fee, make sure new tokens fulfill the minimum circulation and other acceptance criteria.

If you are paying TWT for the submission, this will be burned automatically There will be no refunds.

**Comment by Cryptocool1** [comment]
• What is the purpose of this token? How will it benefit Trust Wallet users?
 • How is the token being distributed? Are you conducting an airdrop?
 • Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?
 • Is the token listed on a centralized/decentralized exchange?
 • Is a Smart Contract audit completed? Where can we find this information?

**Comment by bitburnio** [comment]
• What is the purpose of this token? How will it benefit Trust Wallet users?Bitburn Token is an BEP-20 rewards token that pays 5% Binance-Peg BTCB token rewards to its holders. Rewards are automatically deployed to holders according to buy and sell volume. The formula is simple—the more Bitburn tokens you hold, the more Bitcoin rewards you will earn! We also offer a 2% true burn. So the token is hyper deflationary. What is a true burn? A true burn means that the supply of Bitburn decreases with every buy and sell—we don’t just send the tokens to a burn address.• How is the token being distributed? Are you conducting an airdrop?The token is available on PCS and multiple DEXs. We recently acquired Enhance token and BTC Vantage and sent them their tokens. • Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?We sold 27 1% blacklisted supply slots only to earn rewards. Then did a fair launch.• Is the token listed on a centralized/decentralized exchange?BitBurn will be listed on BitMart tomorrow 8/12.https://support.bitmart.com/hc/en-us/articles/7805718176923• Is a Smart Contract audit completed? Where can we find this information?Yes, https://auditrate.tech/images/pdf/Bitburn_0x5A5844CAb96A7b8B257Fc606Aa6119c5cBc6D4c4.pdf
    	BitBurn Official
    
  

 From: CryptoA ***@***.***>Sent: Thursday, August 11, 2022 2:55 PMTo: trustwallet/assets ***@***.***>Cc: BitBurn ***@***.***>; Author ***@***.***>Subject: Re: [trustwallet/assets] Add BitBurn (BEP20) (PR #21905) 

• What is the purpose of this token? How will it benefit Trust Wallet users?

• How is the token being distributed? Are you conducting an airdrop?

• Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?

• Is the token listed on a centralized/decentralized exchange?

• Is a Smart Contract audit completed? Where can we find this information?

**Review by Horbah02 — CHANGES_REQUESTED** [review]
I need my coin back

**Comment by Horbah02** [comment]
Please I need It back

**Comment by bitburnio** [comment]
What?
    	BitBurn Official
    
  

 From: Horbah02 ***@***.***>Sent: Friday, August 12, 2022 11:26 AMTo: trustwallet/assets ***@***.***>Cc: BitBurn ***@***.***>; Author ***@***.***>Subject: Re: [trustwallet/assets] Add BitBurn (BEP20) (PR #21905) 
@Horbah02 requested changes on this pull request.

I need my coin back

**Review by devendrachauhan9761 — APPROVED** [review]

**Pull request merged**
