### PR TITLE
Add YBet (ybet.network) Logo & Info

### PR DESCRIPTION
**Pull request by ybet-network**
Add YBet Logo & Info

### CODE REVIEW

**Comment by ybet-network** [comment]
Hello,

I pay 250 TWT with the memo 4437 to the address: bnb1tqq9llyr3dyjd559dha6z5r5etk3qfwk07m098
https://explorer.binance.org/tx/A08FF89389574242E5DCF6725C688E5685EBDF1996D832E1278DF6382E973F44

Thank you

**Comment by ybet-network** [comment]
@Iamdeadlyz Hello, Do I need additional information?

**Comment by Iamdeadlyz** [comment]
> @Iamdeadlyz Hello, Do I need additional information?

Hi, your project is under review in accordance with our [disclaimer](https://github.com/trustwallet/assets#disclaimer).

**Comment by catenocrypt** [comment]
Please change explorer entry to `https://etherscan.io/token/0x1abbac88b8f47d46a3d822efa75f64a15c25966f` from 
`https://etherscan.io/`.
Otherwise PR looks OK.

**Comment by Iamdeadlyz** [comment]
Closing due to the following reasons:
- Token inactivity
image

- Website, Twitter account, and Telegram channel are nowhere to be found.
image
image
image

- Removed liquidity (more likely a rug pull)
image

**Pull request closed without merging**
