### PR TITLE
[add] dogegf token logo and info

### PR DESCRIPTION
**Pull request by gsantini-dogegf**

### CODE REVIEW

**Comment by Cryptocool1** [comment]
hello,
• What is the purpose of this token? How will it benefit Trust Wallet users?
 • How is the token being distributed? Are you conducting an airdrop?
 • Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?
 • Is the token listed on a centralized/decentralized exchange?
 • Is a Smart Contract audit completed? Where can we find this information?

**Comment by DogeGF-Token** [comment]
> hello, • What is the purpose of this token? How will it benefit Trust Wallet users? • How is the token being distributed? Are you conducting an airdrop? • Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale? • Is the token listed on a centralized/decentralized exchange? • Is a Smart Contract audit completed? Where can we find this information?

Hi,
DogeGF is a platform for kind gestures based on reciprocity. On it, people will be able to support projects they care about by making a kind gesture on the Ethereum blockchain. The DogeGF token is the governance token of the soon to be launched platform for kind gestures. DogeGF will release also a solution for boosting kind gestures, the DogeGiFt reward platform.

Tokenomics: 50% burned, 25% - locked liquidity in Uniswap V2, V3 & Sushiswap; 10% - team (locked); 15%- marketing & community (10 % locked for 6 months).

More info about DogeGF can be found on our website: https://www.dogegf.com/ or on our social channels, especially on Medium: https://dogegf.medium.com/

Thank you

**Comment by gsantini-dogegf** [comment]
Hi,
DogeGF is a platform for kind gestures based on reciprocity. On it, people will be able to support projects they care about by making a kind gesture on the Ethereum blockchain. The DogeGF token is the governance token of the soon to be launched platform for kind gestures. DogeGF will release also a solution for boosting kind gestures, the DogeGiFt reward platform.
Tokenomics: 50% burned, 25% - locked liquidity in Uniswap V2, V3 & Sushiswap; 10% - team (locked); 15%- marketing & community (10 % locked for 6 months).
More info about DogeGF can be found on our website: https://www.dogegf.com/ or on our social channels, especially on Medium: https://dogegf.medium.com/

**Comment by cryptomanz** [comment]
• Is a Smart Contract audit completed? Where can we find this information?

**Comment by gsantini-dogegf** [comment]
As visible on our website (https://www.dogegf.com/#section_rodmap)  we will make a submissiom for a contract audit in the future. The contract we used is a basic Open Zeppelin ERC20 contract. It can be checked on Etherscan: https://etherscan.io/address/0xf4af4c07f1399e5571799ea6b5a154285aa5a425#code
We are expecting the token logo to be added as quickly as possible since the fee has already been paid.
Thank you

**Comment by Cryptocool1** [comment]
awaiting for smart contract audit, on hold for now

**Comment by Cryptocool1** [comment]
Please come back to us when all criteria are met.
When creating a new PR make sure to mention this PR, so that we can see that fee has been paid already here.

**Comment by gsantini-dogegf** [comment]
Hi, how are you doing?
I am back.

**Pull request closed without merging**
