### PR TITLE
Add Fibo Token (BEP20)

### PR DESCRIPTION
**Pull request by erience**
Adding info for BEP20 token 'Fibo Token'.

PR created by <a href="https://assets.trustwallet.com">TW Assets Management</a>

### CODE REVIEW

**Comment by Cryptocool1** [comment]
Hello! Can you answer some questions ?
• What is the purpose of this token? How will it benefit Trust Wallet users?
 • How is the token being distributed? Are you conducting an airdrop?
 • Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?
 • Is the token listed on a centralized/decentralized exchange?
 • Is a Smart Contract audit completed? Where can we find this information?

**Comment by erience** [comment]
Q: What is the purpose of this token?
A: Utility token of FibSwap DEx

Q: How will it benefit Trust Wallet users?
A: Passive income 4%

Q: How is the token being distributed?
A: Presale/whitelist collected in bnb and airdropped to presale purchasers. Now all tokens on pancake swap

Q: Are you conducting an airdrop? 
A: No

Q: Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale? 
A: Token presale, Yes

Q: Is the token listed on a centralized/decentralized exchange? 
A: Pancake and Fibswap DEx

Q: Is a Smart Contract audit completed? Where can we find this information? 
A: Techrate Audit Completed (https://fibswap.medium.com/fibswap-passes-techrate-security-audit-with-high-integrity-1f4c0e51ac38)

**Comment by erience** [comment]
@Cryptocool1 : answers submitted above

**Comment by Cryptocool1** [comment]
can you please add links to your PR?
example: https://developer.trustwallet.com/add_new_asset/repository_details

**Pull request merged**
