### PR TITLE
Add info & logo

### PR DESCRIPTION
**Pull request by Techearnbd**

### CODE REVIEW

**Comment by Cryptocool1** [comment]
Contract is not in checksum format, should be 0x0b34D4A7C5BFc7004b9a193F8309523E99ca766e
Please create new PR, follow doc https://community.trustwallet.com/t/how-to-submit-a-token-logo/3863
You may want to try our Assets app in beta; go to https://assets.trustwallet.com, log on with Github, enter contract ID, logo and some additional info, and it will create a PR for you.
See https://community.trustwallet.com/t/how-to-submit-a-token-logo-using-assets-app/82957.

**Comment by ShonToken** [comment]
hello sie

**Comment by ShonToken** [comment]
I have pay payment 1000 TWT memo 559 to the address bnb1tqq9llyr3dyjd559dha6z5r5etk3qfwk07m098 Token Contact address 0x0b34d4a7c5bfc7004b9a193f8309523e99ca766e Thank you

**Comment by Cryptocool1** [comment]
correction needed:
Contract is not in checksum format, should be 0x0b34D4A7C5BFc7004b9a193F8309523E99ca766e

**Comment by ShonToken** [comment]
Ok sir Thank you so much

**Comment by ShonToken** [comment]
https://bscscan.com/token/0x0b34d4a7c5bfc7004b9a193f8309523e99ca766e

**Comment by ShonToken** [comment]
hello sir

**Comment by ShonToken** [comment]
Hello sir how are you?

I have update first, (Files JSON) all is Ok, please check and verify our
logo and info thank you

**Comment by ShonToken** [comment]
Hello sir how are you?

I have a uploaded first, (Files JSON) all is Ok, please check and verify our  info thank you

**Comment by Cryptocool1** [comment]
> Hello sir how are you?
> 
> I have a uploaded first, (Files JSON) all is Ok, please check and verify our info thank you

correction still needed:
 Contract is not in checksum format, should be 0x0b34D4A7C5BFc7004b9a193F8309523E99ca766e

**Comment by ShonToken** [comment]
Hello sir any problems

**Comment by ShonToken** [comment]
Hello sir my all details is Ok please verify logo and info please

**Comment by Cryptocool1** [comment]
> Hello sir my all details is Ok please verify logo and info please

still correction needed:
Contract is not in checksum format, should be 0x0b34D4A7C5BFc7004b9a193F8309523E99ca766e 
I suggest to create a new PR (and mention this one so that fee does not have to be paid again).
 • You may use our Assets app (in beta); close this PR; go to https://assets.trustwallet.com, log on with Github, enter contract ID, logo and some additional info, and it will create a PR for you. See https://community.trustwallet.com/t/how-to-submit-a-token-logo-using-assets-app/82957\

**Comment by ShonToken** [comment]
Done

**Comment by ShonToken** [comment]
Verify please

**Comment by ShonToken** [comment]
> **PR Summary**
> Files OK, 2Files in PR: 2
> Token in PR: BEP20 0x0b34d4a7c5bfc7004b9a193f8309523e99ca766e
> Symbol: **SHON** decimals: 18
> Links: [Logo](https://raw.githubusercontent.com/ShonToken/assets/master/blockchains/smartchain/assets/0x0b34d4a7c5bfc7004b9a193f8309523e99ca766e/logo.png) [Info](https://raw.githubusercontent.com/ShonToken/assets/master/blockchains/smartchain/assets/0x0b34d4a7c5bfc7004b9a193f8309523e99ca766e/info.json) [Website](https://shontoken.com) [Explorer](https://bscscan.com/token/0x0b34d4a7c5bfc7004b9a193f8309523e99ca766e)
> Token check error:
> ❌ Contract is not in checksum format, should be 0x0b34D4A7C5BFc7004b9a193F8309523E99ca766e (not 0x0b34d4a7c5bfc7004b9a193f8309523e99ca766e). Please rename it. You may need to rename to a temp name first, then to the checksum format, because lowercase-uppercase-only renames are often ignored by the Git client or the filesystem.
> ✓ Token type OK (BEP20); Type field OK; Symbol field OK; Decimals field OK; Description field OK; Website field OK; Explorer field OK; Status field OK; Id field OK; Logo image type is OK (image/png); Logo image size is OK (35.253 kB); Logo dimensions OK (256x256); Token circulation OK (no. of holders: 5159);
> 
> 

all is Ok sir please verify the logo and info

**Comment by Cryptocool1** [comment]
Contract is not in checksum format, should be 0x0b34D4A7C5BFc7004b9a193F8309523E99ca766e
As I mention, If you can't rename files in the PR, you may open a new PR. Make sure to mention this PR, so that we can see that fee has been paid already here.

**Comment by ShonToken** [comment]
> Contract is not in checksum format, should be 0x0b34D4A7C5BFc7004b9a193F8309523E99ca766e
> As I mention, If you can't rename files in the PR, you may open a new PR. Make sure to mention this PR, so that we can see that fee has been paid already here.

Hello sir how are you!

Sir I have a first time logo adding apply so please verified our logo and I have a first this shon project our file long for sorry and again submit please verify me the project thank you so much

contact address

0x0b34D4A7C5BFc7004b9a193F8309523E99ca766e

0x0b34d4a7c5bfc7004b9a193f8309523e99ca766e

Same contact address


again extra token detail check please



{
    "name": "ShonToken",
    "type": "BEP20",
    "symbol": "SHON",
    "decimals": 18,
    "website": "https://shontoken.com",
    "description": "Shon token is the latest crypto-currency architecture that can be transacted through the Binance Smart Chain",
    "explorer": "https://bscscan.com/token/0x0b34d4a7c5bfc7004b9a193f8309523e99ca766e",
    "status": "active",
    "id": "0x0b34d4a7c5bfc7004b9a193f8309523e99ca766e"
}



Logo PNG image
https://drive.google.com/file/d/11fj7ex1EjYCSuu7K-kNZDOQgj3D8_HgJ/view?usp=drivesdk

**Comment by Cryptocool1** [comment]
> > Contract is not in checksum format, should be 0x0b34D4A7C5BFc7004b9a193F8309523E99ca766e
> > As I mention, If you can't rename files in the PR, you may open a new PR. Make sure to mention this PR, so that we can see that fee has been paid already here.
> 
> Hello sir how are you!
> 
> Sir I have a first time logo adding apply so please verified our logo and I have a first this shon project our file long for sorry and again submit please verify me the project thank you so much
> 
> contact address
> 
> 0x0b34D4A7C5BFc7004b9a193F8309523E99ca766e
> 
> 0x0b34d4a7c5bfc7004b9a193f8309523e99ca766e
> 
> Same contact address
> 
> again extra token detail check please
> 
> {
> "name": "ShonToken",
> "type": "BEP20",
> "symbol": "SHON",
> "decimals": 18,
> "website": "https://shontoken.com",
> "description": "Shon token is the latest crypto-currency architecture that can be transacted through the Binance Smart Chain",
> "explorer": "https://bscscan.com/token/0x0b34d4a7c5bfc7004b9a193f8309523e99ca766e",
> "status": "active",
> "id": "0x0b34d4a7c5bfc7004b9a193f8309523e99ca766e"
> }
> 
> Logo PNG image
> https://drive.google.com/file/d/11fj7ex1EjYCSuu7K-kNZDOQgj3D8_HgJ/view?usp=drivesdk

? Can you please create new PR with correct  checksum format?

**Comment by ShonToken** [comment]
Verified our logo and info please

**Comment by Cryptocool1** [comment]
> Verified our logo and info please

As I mentioned, Contract is not in checksum format, should be 0x0b34D4A7C5BFc7004b9a193F8309523E99ca766e (not 0x0b34d4a7c5bfc7004b9a193f8309523e99ca766e).

**Comment by ShonToken** [comment]
> > Verified our logo and info please
> 
> As I mentioned, Contract is not in checksum format, should be 0x0b34D4A7C5BFc7004b9a193F8309523E99ca766e (not 0x0b34d4a7c5bfc7004b9a193f8309523e99ca766e).

https://bscscan.com/token/0x0b34d4a7c5bfc7004b9a193f8309523e99ca766e

0x0b34d4a7c5bfc7004b9a193f8309523e99ca766e

**Comment by ShonToken** [comment]
> > Verified our logo and info please
> 
> As I mentioned, Contract is not in checksum format, should be 0x0b34D4A7C5BFc7004b9a193F8309523E99ca766e (not 0x0b34d4a7c5bfc7004b9a193f8309523e99ca766e).

Sir all is Ok our file

**Comment by ShonToken** [comment]
0x0b34d4a7c5bfc7004b9a193f8309523e99ca766e

0x0b34D4A7C5BFc7004b9a193F8309523E99ca766e

0X0B34D4A7C5BFC7004B9A193F8309523E99CA766E

**Comment by ShonToken** [comment]
> 0x0b34d4a7c5bfc7004b9a193f8309523e99ca766e
> 
> 0x0b34D4A7C5BFc7004b9a193F8309523E99ca766e
> 
> 0X0B34D4A7C5BFC7004B9A193F8309523E99CA766E

One contact address 

12&3

**Comment by ShonToken** [comment]
Telegram https://t.me/ShonToken

**Comment by ShonToken** [comment]
#10559

**Comment by Cryptocool1** [comment]
can't find contract on your website 
please check/add

**Comment by ShonToken** [comment]
> can't find contract on your website
> please check/add

Thank you so much sir 
But sir our "website"  launch nex 3-4 business days complete development in website thank you! ❤️

**Comment by ShonToken** [comment]
Hello sir one question please don't mind our token logo add complete maximum days give me please

**Comment by Cryptocool1** [comment]
> Hello sir one question please don't mind our token logo add complete maximum days give me please

Did you add contract to your website?

**Comment by ShonToken** [comment]
> > Hello sir one question please don't mind our token logo add complete maximum days give me please
> 
> Did you add contract to your website?

Website just is ok visit: https://shontoken.com/ please
and add GitHub

**Comment by cryptomanz** [comment]
> > > Hello sir one question please don't mind our token logo add complete maximum days give me please
> > 
> > 
> > Did you add contract to your website?
> 
> Website just is ok visit: https://shontoken.com/ please
> and add GitHub

As mentioned,
you need to add your contract (0x0b34D4A7C5BFc7004b9a193F8309523E99ca766e) to your website!

**Comment by ShonToken** [comment]
> > > > Hello sir one question please don't mind our token logo add complete maximum days give me please
> > > 
> > > 
> > > Did you add contract to your website?
> > 
> > 
> > Website just is ok visit: https://shontoken.com/ please
> > and add GitHub
> 
> As mentioned,
> you need to add your contract (0x0b34D4A7C5BFc7004b9a193F8309523E99ca766e) to your website!

Ok sir fine tomorrow add contact address and others full information Ok so today good night.....

**Comment by ShonToken** [comment]
> > > > Hello sir one question please don't mind our token logo add complete maximum days give me please
> > > 
> > > 
> > > Did you add contract to your website?
> > 
> > 
> > Website just is ok visit: https://shontoken.com/ please
> > and add GitHub
> 
> As mentioned,
> you need to add your contract (0x0b34D4A7C5BFc7004b9a193F8309523E99ca766e) to your website!

Hello sir how are you, good morning


so sir my website add Contract please our website https://shontoken.com/ and photo https://drive.google.com/file/d/128TdxCsckmdq3rO185quiAR0ChtqUJk3/view?usp=drivesdk

**Comment by ShonToken** [comment]
Hello sir no any reply our website all is Ok

**Comment by ShonToken** [comment]
Thank you so much

**Comment by ShonToken** [comment]
Hello

**Comment by ShonToken** [comment]
Hello sir how are you!

I'm try add a new logo sir

Sir I have a first time logo add apply so verified, but again change our logo so add my info I'm a pay 1000 TWT please verify me the project thank you so much

contact address

0x0b34D4A7C5BFc7004b9a193F8309523E99ca766e

0x0b34d4a7c5bfc7004b9a193f8309523e99ca766e

Same contact address

again extra token detail check please

{
"name": "ShonToken",
"type": "BEP20",
"symbol": "SHON",
"decimals": 18,
"website": "https://shontoken.com",
"description": "Shon token is the latest crypto-currency architecture that can be transacted through the Binance Smart Chain",
"explorer": "https://bscscan.com/token/0x0b34d4a7c5bfc7004b9a193f8309523e99ca766e",
"status": "active",
"id": "0x0b34d4a7c5bfc7004b9a193f8309523e99ca766e"
}

Logo PNG image
https://drive.google.com/file/d/1zf21O320HC6vr6TUBmnIe-jckZN91PWU/view?usp=sharing


Request No #11094

**Pull request merged**
