### PR TITLE
Everyonescrypto (EOC)

### PR DESCRIPTION
**Pull request by everyonescrypto**

### CODE REVIEW

**Comment by catenocrypt** [comment]
As per our policy, brand new tokens are not included, there is a minimum requirement of 500 holder addresses and 1000 transactions, in order to filter out scam tokens.
See the criteria at (mentioned in the first message by the bot): https://community.trustwallet.com/t/how-to-submit-a-token-logo/3863#how-to-get-approved
This token has minimal usage (9/19). Putting PR on hold. Please come back to us when all criteria are met.

https://etherscan.io/token/0xa8006e3ac1bd94e54e3136b8e5dd75db0163e6f4

**Comment by everyonescrypto** [comment]
Hi!
Ok 
we are new project and don´t notice that.
can we gewt refund those 2 BNB or how that goes on?
Br Justin

**Comment by catenocrypt** [comment]
Sorry, we don't to refunds.  But paid fee can be considered later if circulation has been achieved.

**Comment by everyonescrypto** [comment]
Hi!
Thank you for response!
That´s ok I come back when it´s time and we are ready
br Justin

**Pull request closed without merging**
