### PR TITLE
Add Vita Inu (BEP20)

### PR DESCRIPTION
**Pull request by ElemontCapital**
Already paid - refer to Pull #20103

**Hi @Cryptocool1, please read my explanation before making your decision!**

**1. Holder Count** _(We are not a brand new token!)_
- VINU is a multi-chain coin. As such, our holders are split across different chains.
- **We have over 10,000 holders on the VITE chain alone**
- We have 20,000 holders altogether (2x the requirement) from the summation of our two explorers:
-- VITE: https://vitescan.io/token/tti_541b25bd5e5db35166864096
-- BSC: https://bscscan.com/token/0xfebe8c1ed424dbf688551d4e2267e7a53698f0aa

image

**2. CertiK Audit** https://www.certik.com/projects/vita-inu
- We have a very high security score of 93 on CertiK now after our Audit.
- We are ranked inside the top 200 tokens according to CertiK.
- It is very common for projects to have findings, but please note they are marked as 'All resolved/Mitigated/Acknowledged' by CertiK.

image

**3. Exchanges & Volume** https://coinmarketcap.com/currencies/vita-inu/markets/
- VINU is listed on many reputable exchanges and has a 24hr trading volume of over $1m.
- We have a higher ranking, market cap, & volume than many other tokens already listed on Trust Wallet.

image

Please take the above into account for your PR merge decision. 
- I reiterate we already meet your requirement of 10,000 holders on our native chain (Vite), and we have 100,000 transactions (6.5x the transaction requirement) just on BSC (and multiples more on Vite chain).
- Many of our BSC holders are also using the CEXs outlined above (evidenced by their volumes), which are hidden from the BSC holder count (because the CEXs only use one wallet for all users combined).

Thank you for reviewing.

### CODE REVIEW

**Comment by ElemontCapital** [comment]
> Hi! In order to compensate for the efforts of processing PRs, we kindly ask for a contribution. 💀 As **there is no refund**, before **paying the fee**, make sure **new tokens fulfill the minimum circulation and other [acceptance criteria](https://developer.trustwallet.com/assets/new-asset)**. See also the [PR Fee FAQ](https://developer.trustwallet.com/assets/faq).
> 
> Please pay **700 TWT** with the memo **20409** to the address `bnb1tqq9llyr3dyjd559dha6z5r5etk3qfwk07m098`. Alternatively, 5 BNB is also accepted (same memo & address).
> 
> **QR** code: [Trust](https://api.qrserver.com/v1/create-qr-code/?size=200x200&data=https%3A%2F%2Flink.trustwallet.com%2Fsend%3Fcoin%3D714%26address%3Dbnb1tqq9llyr3dyjd559dha6z5r5etk3qfwk07m098%26amount%3D700%26memo%3D20409) | [other wallet](https://api.qrserver.com/v1/create-qr-code/?size=200x200&data=bnb1tqq9llyr3dyjd559dha6z5r5etk3qfwk07m098%3Famount%3D700%26memo%3D20409)
> 
> _Notes_:
> 
> * [Trust Wallet Tokens (TWT)](https://community.trustwallet.com/t/trust-wallet-token-twt/4187) can be obtained through our [Referral Program](https://community.trustwallet.com/t/invite-a-friend-earn-trust-wallet-token-twt/4125) or [from DEXs/exchanges](https://community.trustwallet.com/t/where-to-get-trust-wallet-tokens/76641).
> * New tokens without significant usage are rejected, see criteria mentioned above.
> * One PR should be for a single project; PR's with more than 10 logos will be rejected.
> * Payment evaluation happens automatically, but with a few minutes delay.  When payment is detected, an Accept Review is automatically placed on the PR, which is a condition for merge.
> * Evaluating the PR is done manually, and it is merged only if all conditions are satisfied.
> * TWT-BEP2 is supported (Binance Chain), TWT-BEP20 version on Smart Chain is not.
> 
> There will be a fee to process this request. None of it goes to the developers. Before paying the fee, make sure new tokens fulfill the minimum circulation and other acceptance criteria. If you are paying TWT for the submission, this will be burned automatically. There will be no refunds.

Already paid - refer to Pull https://github.com/trustwallet/assets/pull/20103

**Comment by ElemontCapital** [comment]
Hey guys,
Any other information you'd like me to provide to have us committed?

**Comment by ElemontCapital** [comment]
@Cryptocool1 @cryptomanz @Iamdeadlyz 

> Hey guys, Any other information you'd like me to provide to have us committed?

**Comment by Cryptocool1** [comment]
Hello, we are not accept vita chain holders, please come back to us once you met requirements with bscscan holders

**Comment by ElemontCapital** [comment]
> Hello, we are not accept vita chain holders, please come back to us once you met requirements with bscscan holders
@Cryptocool1 
It's a bridge token though. 
We have a larger community than most of the tokens you commit & we have reputable CEXs - Mexc, Bitmart, Bitrue.
And we are highly ranked on Certik.

To me the evidence I provided above should satisfy you, but look Ieave this open if you won't commit & I'll come back to you when the BSC holders are there.

**Comment by Cryptocool1** [comment]
Please come back to us once all criteria are met. Make sure to mention this PR so the fee can be reused.

**Pull request closed without merging**
