### PR TITLE
Add MCRT logo and info

### PR DESCRIPTION
**Pull request by Egzothicki**
Add MagicCraft (MCRT) logo and information to TrustWallet

### CODE REVIEW

**Comment by cryptomanz** [comment]
Hello,
This is a BEp20 token, correct folder is blockchains/smartchain/assets. Please change.

**Comment by Egzothicki** [comment]
What's the next step?

**Comment by Egzothicki** [comment]
Can I please get some help with the process?

**Comment by cryptomanz** [comment]
• What is the purpose of this token? How will it benefit Trust Wallet users?
 • How is the token being distributed? Are you conducting an airdrop?
 • Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?
 • Is the token listed on a centralized/decentralized exchange?
 • Is a Smart Contract audit completed? Where can we find this information?

**Comment by Egzothicki** [comment]
What is the purpose of this token? How will it benefit Trust Wallet users?
 
$MCRT is a functional multi-utility token which will be used as the medium of exchange between participants on Magic Craft in a decentralized manner. The goal of introducing $MCRT is to provide a convenient and secure mode of payment and settlement between participants who interact within the ecosystem of Magic Craft without any intermediaries such as centralized third party entity/institution/credit. MCRT might bring new users, especially from the gaming niche to the Trust Wallet ecosystem

How is the token being distributed? Are you conducting an airdrop?
 
Token is distributed based on the token-economics model, through an audited smart contract. There is a total supply of 10 000 000 000 MCRT Tokens. 34,68% will be used for the Gaming Issuance and growth of the ecosystem. 22,0% is assigned to the Team with 12 months vesting. 3,31% were sold on the public sale. 12% will be used for the Staking issuance. 10% were sold in the Private sale with 3 months lockup and 12 months linear vest. 6% goes to Liquidity. Remaining tokens will be in the reserve fund.
We did not conduct an airdrop yet.
 
• Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?
 
Yes, we held a public sale in a form of an auction system where we raised 3328 BNB. Before offering a presale, we also conducted three private investment rounds.
  
• Is the token listed on a centralized/decentralized exchange?
 
$MCRT is listed on Bitmart, Pancakeswap, Dodo and Bilaxy
 
• Is a Smart Contract audit completed? Where can we find this information?

Yes, smart contract is audited with TECH AUDIT. Link to the audit can be found below
https://drive.google.com/file/d/1qvDBW1xY7pcBVD8rbmtjZJ-9nynQWoEK/view

**Comment by cryptomanz** [comment]
We are not accept TECH AUDIT.
Here is the example of smart contract audit: https://www.certik.org/projects/binance, https://techrate.org

**Comment by Cryptocool1** [comment]
please come back to us when all criteria are met

**Comment by Egzothicki** [comment]
Do you accept any of the auditors listed below:
* Knowsec
* Linan Tech
* Red4Sec
* Bejing Chains Guard
* Peckshield
* JohnWick Sec
* Slow Mist
?

**Comment by Cryptocool1** [comment]
No we are not

**Comment by Egzothicki** [comment]
Do you accept any other than Certik and Techrate?

**Comment by Egzothicki** [comment]
Hello, 
kindly following up on the above

**Comment by Egzothicki** [comment]
Here's the final Certik audit
[REP-final-20220519T023217Z.pdf](https://github.com/trustwallet/assets/files/8732181/REP-final-20220519T023217Z.pdf)
t

**Comment by nratkevichqa** [comment]
Hello @Cryptocool1 
I was assigned to work on this task by MagicCraft team.
Certik finished smart contract audit and we shared the report with you above.
Please let me know if we can re-open this pull request.
Or I need to create a new one and link this one to confirm the payment?
Thanks in advance

**Comment by Egzothicki** [comment]
Hello @Cryptocool1 @cryptomanz ,
Certic finished our smart contract audit. I provided the final report above. Could you please re-open this request?
Thanks in advance

**Pull request closed without merging**
