### PR TITLE
Update Wrapped Centrifuge (wCFG)

### PR DESCRIPTION
**Pull request by devin-black**
This PR updates Wrapped Centrifuge (wCFG) to be named Centrifuge (CFG). It also updates description and some links. [Here is our official announcement for the name change](https://centrifuge.mirror.xyz/8PDbalB4ix_HJKzBDCHaTUkHch49bb00ktbQRPil4wg).

### CODE REVIEW

**Comment by Cryptocool1** [comment]
Hello, this information should be updated on your explorer and CoinMarketCap first

**Comment by devin-black** [comment]
Hi @Cryptocool1,

I understand regarding the block explorer (Etherscan in this case), and that request has been submitted and should be reflected shortly — I will share here when that's ready!

I can't provide this update to CoinMarketCap or CoinGecko as we intend to sunset the existing "Wrapped Centrifuge" pages and keep the existing Centrifuge pages that you can find here:

- https://coingecko.com/en/coins/centrifuge
- https://coinmarketcap.com/currencies/centrifuge/

(Note that I have also updated links in this repo to point to these pages).

We will be eliminating the separate "Wrapped Centrifuge" pages ([example](https://coinmarketcap.com/currencies/wrapped-centrifuge/)) by changing trading pair names to CFG. Updating the Trust Wallet repo to reflect that wCFG is now CFG is part of the process of updating trading pair names — so we can't show a change on CoinMarketCap/CoinGecko until this PR is submitted and we update trading pair names on their respective platforms!

Let me know if that makes sense and if you accept block explorer update + our official announcement on our blog ([and now on our Twitter](https://twitter.com/centrifuge/status/1758194132856815928)). Ready to send TWT once we're in agreement.

Devin

**Comment by devin-black** [comment]
Hi @Cryptocool1, 

The[ token name has been updated to Centrifuge (CFG) on Etherscan](https://etherscan.io/token/0xc221b7e65ffc80de234bbb6667abdd46593d34f0). As explained in my last message, is this sufficient? If so, could you reopen this PR and I'll send the TWT?

Thanks!
Devin

**Comment by devin-black** [comment]
@Cryptocool1 @cryptomanz1 @vcoolish Following up on the above, thank you!

**Comment by Cryptocool1** [comment]
Hi, thank you, we will update it for you today

**Comment by 1364aliyari2** [comment]
devin-black:wcfg-update

**Pull request merged**
