### PR TITLE
I think its ready

### PR DESCRIPTION
**Pull request by CopperStableCoin**

### CODE REVIEW

**Comment by CopperStableCoin** [comment]
:)

**Comment by CopperStableCoin** [comment]
Just ignore that oart of script unless it’s essential, is everything else
okay?

**Comment by CopperStableCoin** [comment]
Let me know if i need to fix anything more i will in a heartbeat. 
Thank you

**Comment by CopperStableCoin** [comment]
0x3fC91A3afd70395Cd496C647d5a6CC9D4B2b7FAD
this is uniswap vt router

**Comment by cryptomanz1** [comment]
What is the purpose of this token? How will it benefit Trust Wallet users?
 • How is the token being distributed? Are you conducting an airdrop?
 • Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?
 • Is the token listed on a centralized/decentralized exchange?
 • Is a Smart Contract audit completed? Where can we find this information?

**Comment by CopperStableCoin** [comment]
What is the purpose of this token? How will it benefit Trust Wallet users?
the purpose of the coin is to create a more accessible way to buy copper through Ethereum, the coin is stable 1-1 to 1b of copper per coin, and is able to be staked on the website to earn %APR based on time staked.

1. The token is only being distributed through purchase on uniswapv2 which is also linked through website.

2. There was no presale involved only a surprise launch with liquidity added to v2 pool on uniswapv2

3. The token is listed on Uniswap and is a ERC-20 token

4. I would be happy to complete an audit, is there any company you suggest i take the audit too?

**Comment by cryptomanz1** [comment]
You can chose from the most from reputable companies, for example : TechRate, Certik, Hacken, Dessert Finance.

**Comment by Cryptocool1** [comment]
Please come back to us once your audit is done. 
When creating new Pull Request please make sure to mention this one so the fee can be reused.

**Pull request closed without merging**
