### PR TITLE
https://github.com/trustwallet/assets/pull/22386

### PR DESCRIPTION
**Pull request by BabyApeFunClub**
Hello, we are sorry, we encountered many problems. Coordination was not fully achieved. Frankly, we were scammed by marketing deals. I'm not saying these are our personal problems to bother you. We did the most secure project in BSC network, we chose BSC network even though BSC network lags behind in NFT market. So we need all kinds of support. I don't quite understand, should I create a new pool?
From you:
Please come back to us once all criteria are met. Make sure you mention this PR so the fee can be reused. PR was 22386

### CODE REVIEW

**Comment by BabyApeFunClub** [comment]
[BabyApeFunClub](https://github.com/trustwallet/assets/pull/22386#top)
#22386
All details about BabyApeFunClub:
BabyApeFunClub Metaverse World:
Welcome to BabyApeFunClub, we saw that we could not adapt to the real world; So we decided to create our own world. Where tiny primates from all walks of life rule an exclusive **rainforest** in a quiet little corner of the ever-growing metaverse.
Every member is represented by an exclusive **Baby Ape NFT**, each of which are **hand-drawn** by our partnered artist. With a unique art style, **Baby Ape NFTs** represent good vibes and individuality to all who encounter them.
Our project is 100% community-driven and utility-focused, welcoming NFT experts and newcomers alike to unite and craft a project that represents YOU.

**:art:BabyApeFunClub NFT Marketplace:** BabyApeFunClub is a collection of 7777 unique Baby Ape NFTs. 
Every member is represented by an exclusive **Baby Ape NFT**, each of which are **hand-drawn** by our partnered artist.
In the first instance, 1000 stakeable NFTs will be generated. Each BabyApe NFT has unique and unique features in the BabyApeFunClub metaworld.


**:heavy_dollar_sign:BabyApeFunClub HODL2EARN Mechanism:** For the long-term development of the BAFC family, the HODL2EARN mechanism was designed financially.
BabyApeFunClub is designed to meet all needs not only in Metaverse and NFT, but also in DeFi.
In this direction, 2% of every buy and 2% of every sell transaction is distributed to #BAFC holders & BAFC Stake platform was created with 40% APY award.
In other words, the #HODL2EARN mechanism reaches higher levels with Stake&Reflections. Our investors will continue to earn just by doing #HODL.


BabyApeFunClub STAKING: BAFC Staking platform was specially designed by SphynxLabs. It is one of the fundamental dynamics of the HODL2EARN mechanism.
BabyApeFunClub holders can earn 40% APY by staking their $BAFC tokens in the BAFC Staking Pool.
(Stake for a minimum of 7 days; withdrawing prematurely results in a 10% penalty)

BabyApeFunClub SWAP: In order to meet all the needs of cryptocurrency and appeal to the whole world, not just Metaverse or NFT, BAFC aims to create an active DeFi platform.
BAFC Swap is specially designed for BabyApeFunClub with the support of KRA Finance.

BabyApeFunClub Store: BAFC will create its own style in order to become a worldwide brand and appeal to all humanity. The first steps of this are based on clothing. BabyApeFunClub special production Hoodies, Caps, Watches and Tshirts have been actively used by the teams and their families.
BAFC Store  is under development in terms of digital marketing.
Apart from that, the use of BAFC collection products will become widespread in many fields such as football teams, world-famous stars and dance shows. This is one of our biggest goals.
In addition, BAFC Store is on a mission to help poor communities around the world. For this, great preparations and partnership studies are carried out in the background.

Website: https://www.BabyApeFunClub.com
Twitter: https://www.twitter.com/BabyApeFunClub
BabyApeFunClub NFT Mint: https://bafc.kraitor.dev/
WhitePaper: https://babyapefunclub.com/whitepaper.pdf
Audit:https://github.com/AnalytixAudit/Solidity/blob/main/Audit_BabyApeFunClub.pdf
Telegram: https://t.me/BabyApeFunClub
Chinese TG: https://t.me/BabyApeFunClubcn
Contract Adress: 0x035ad59058c557be4532141fbcd60f0998fce413
Chart: https://poocoin.app/tokens/0x035ad59058c557be4532141fbcd60f0998fce413
DexTools Chart: https://www.dextools.io/app/bnb/pair-explorer/0xad778ee2ec66869042ca016ba36e80f47d1815dc
Liquidity Lock: https://www.pinksale.finance/pinklock/record/1037573?chain=BSC
BAFC STAKE:https://thesphynx.co/pools/56
BAFC SWAP:https://bafc.kra.finance/
Buy on pancakeswap: https://pancakeswap.finance/swap?outputCurrency=0x035ad59058c557be4532141fbcd60f0998fce413
Instagram: https://www.instagram.com/BabyApeFunClub
Discord: https://discord.gg/RuVcCUXpMk
Youtube: https://www.youtube.com/channel/UCL6fPF63i2RBVi-mTKPBDgg
Twitch: https://www.twitch.tv/babyapefunclub/about
Linktree: https://linktr.ee/babyapefunclub




TOKENOMICS
1,000,000,000,000,000 BAFC
%50 Supply burnt forever before launch
%45 Supply Add to LP
%5 supply reserved for major exchanges & feeding StakePool
Tax Fee %6 for Buy&Sell;%2 to Holders , %2 to Metaverse&Community Development Fund , %2 to Marketing

**Comment by Cryptocool1** [comment]
hello, As per our policy, brand new tokens are not included, there is a minimum requirement of 10,000 holder addresses and 15,000 transactions, in order to filter out scam tokens.
See the criteria at : https://developer.trustwallet.com/assets/requirements .

**Comment by BabyApeFunClub** [comment]
Did you checked our Holders&Transactions please

**Comment by BabyApeFunClub** [comment]
> hello, As per our policy, brand new tokens are not included, there is a minimum requirement of 10,000 holder addresses and 15,000 transactions, in order to filter out scam tokens. See the criteria at : https://developer.trustwallet.com/assets/requirements .

Please check our project Holders & Transactions & Audit & Hosting & Liquidity Lock

**Comment by Cryptocool1** [comment]
you did not have holders couple hours ago. how did you get them in 3 hours?
your first massive transactions have started 3 hours ago

**Comment by Cryptocool1** [comment]
your token is also not listed on CMC. your holders seems to be artificial. thanks for your interest, you can try to resubmit PR in 1-2 months. Make sure you mention this PR so the fee can be reused.

**Pull request closed without merging**
