### PR TITLE
Add Jade Protocol (BEP20)

### PR DESCRIPTION
**Pull request by jadeprotocol**
Adding info for BEP20 token 'Jade Protocol'.

PR created by <a href="https://assets.trustwallet.com">TW Assets Management</a>

### CODE REVIEW

**Comment by Cryptocool1** [comment]
• Is a Smart Contract audit completed? Where can we find this information?

**Comment by jadeprotocol** [comment]
> • Is a Smart Contract audit completed? Where can we find this information?

@Cryptocool1 

Hi there,

Thank you for following up. You can find our RugDoc report [here](https://rugdoc.io/project/jade-protocol/).

Please let me know if you have any further questions.

Also, feel free to reach out to me directly over [Telegram](https://t.me/itsMacTonight) if you require any additional clarification.

**Comment by cryptomanz** [comment]
• Is a Smart Contract audit completed?

**Comment by Cryptocool1** [comment]
please come back to s when all criteria are met. make sure to mention this PR, so the fee can be reused

**Pull request closed without merging**
