### PR TITLE
Add Chain Games (CHAIN) (ERC20)

### PR DESCRIPTION
**Pull request by srpatel19590**
Adding info for ERC20 token 'Chain Games (CHAIN)'.

PR created by <a href="https://assets.trustwallet.com">TW Assets Management</a>

### CODE REVIEW

**Comment by Cryptocool1** [comment]
• What is the purpose of this token? How will it benefit Trust Wallet users?
 • How is the token being distributed? Are you conducting an airdrop?
 • Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?
 • Is the token listed on a centralized/decentralized exchange?
 • Is a Smart Contract audit completed? Where can we find this information?

**Comment by srpatel19590** [comment]
@Cryptocool1 

**1. What is the purpose of this token? How will it benefit Trust Wallet users?**
-This token was launched in 2020 and is a gaming token and the medium of entry for games on the Chain Games platform

**2. How is the token being distributed? Are you conducting an airdrop?**
-Token was launched in 2020 and is fully distributed and available on various DEXs and CEXs.  No airdrop.

**3. Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?**
-Tokens were initially sold in 2020 ICO.

**4. Is the token listed on a centralized/decentralized exchange?**
-Yes listed on Uniswap, QuickSwap, [Gate.io](http://gate.io/), Bilaxy, Probit

**5. Is a Smart Contract audit completed? Where can we find this information?**
-Yes, audited by Hacken and on their website.

**Comment by Cryptocool1** [comment]
Hello, I don’t see your project on Hacken website, please check

**Comment by srpatel19590** [comment]
@Cryptocool1 I'm not sure. I'm checking more details with the team but here is the audit report https://drive.google.com/file/d/1o9L52h1QyltdsjFozHW-bI8FYkcVqYBi/view

**Comment by Cryptocool1** [comment]
True Hacken audit should be on their website

**Comment by bravoadam** [comment]
Chain Games Hacken Audit - https://hacken.io/audits/chain-games/

**Comment by srpatel19590** [comment]
@Cryptocool1 Hacken has uploaded our project Audit. https://hacken.io/audits/chain-games/

**Pull request merged**
