### PR TITLE
Add MERO logo and info.

### PR DESCRIPTION
**Pull request by ghost**

### CODE REVIEW

**Comment by catenocrypt** [comment]
Submission looks OK, fee payment expected.

**Comment by catenocrypt** [comment]
Website features TW integration.

**Comment by cryptojoehodler** [comment]
If we wanted to adjust our logo would that require the merge fee?

**Comment by catenocrypt** [comment]
Our general rule is that all PRs need fee.  If you update within one day of merge, I can make an exception though.

**Comment by cryptojoehodler** [comment]
Thank you so much, it is so appreciated. I submitted pull request 6104 for
the logo update.

Regards,
Mero Team.

**Comment by cryptojoehodler** [comment]
Thank you so much, it is so appreciated. I submitted pull request 6104 for the logo update.
Regards,Mero Team.

**Comment by cryptojoehodler** [comment]
Thank you so much, it is so appreciated. I submitted pull request 6104 for the logo update.
Regards, Mero Team.

**Pull request merged**
