### PR TITLE
Add SpookyShiba (BEP20)

### PR DESCRIPTION
**Pull request by wrennstigator**
Adding info for BEP20 token 'SpookyShiba'.

PR created by <a href="https://assets.trustwallet.com">TW Assets Management</a>

### CODE REVIEW

**Comment by wrennstigator** [comment]
is this fine?

**Comment by wrennstigator** [comment]
https://explorer.binance.org/tx/51A31371DFC5C7AD5B92B0DF5D3AF2EA3B8E85864D33269A5AE1A05655F586A1


Paid!! 😇
Thank you! How long do you think to show?

**Comment by cryptomanz** [comment]
• What is the purpose of this token? How will it benefit Trust Wallet users?
 • How is the token being distributed? Are you conducting an airdrop?
 • Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?
 • Is the token listed on a centralized/decentralized exchange?
 • Is a Smart Contract audit completed? Where can we find this information?

**Comment by wrennstigator** [comment]
• What is the purpose of this token? How will it benefit Trust Wallet users?
-    The purpose of the token, SpookyShiba. is bringing our community
together with a "horror-genre" token. Created our first P2E video game
available on our site, SpookyShibaBSC.com through iOS and PlayStore. Also
developing an NFT Marketplace and utility with holders via a separate game,
also available to play now on the website. Trust wallet users are literally
asking us daily to see the logo. We have over 15,000 holders and were
literally the top 3 CMC trending today :)

• How is the token being distributed? Are you conducting an airdrop?
PancakeSwap and Coinsbit are our two exchanges right now.
• Did you sold the tokens at an Initial Coin Offering (ICO) or a token
presale?No this was a Stealth Launched project on October 28th, 2021
• Is the token listed on a centralized/decentralized exchange? Yes, We
believe Coinsbit is centralized, whereas PancakeSwap is decentralized.
• Is a Smart Contract audit completed? Where can we find this information?
Yes.
https://app.marketmove.ai/contract-audit/0xed74bc5dc139356e08de28143996f5ef6e4334a4?c=telegram
<https://app.marketmove.ai/contract-audit/0xed74bc5dc139356e08de28143996f5ef6e4334a4?c=telegram&fbclid=IwAR2l17KIZO367LyIdjhr8MwRTLW36Syzpdn5vrJA3Vxtm5xHlWrNAs1GvLY>

**Comment by wrennstigator** [comment]
I apologize, but is there anyway to send update for the logo again? It
didn’t come out right on the trustwallet view, we should shrink it a bit to
fit the ears in.

**Pull request merged**
