### PR TITLE
Quint in Trustwallet

### PR DESCRIPTION
**Pull request by quintlistings**

### CODE REVIEW

**Comment by quintlistings** [comment]
We paid the bnb fee previously. Since the holder count didn't satisfy trust wallet's criteria, request was closed. Kindly verify and update the logo and the info as soon as possible.

**Review by BeckysLife — APPROVED** [review]

**Comment by quintlistings** [comment]
How long does it usually take for the Logo and data to appear on the trust wallet?

**Comment by Cryptocool1** [comment]
What is number of PR where did you pay?

**Comment by quintlistings** [comment]
Payment was made for the PR, and it didn't satisfy the holder count
criteria. Should we pay again?

**Comment by Cryptocool1** [comment]
What is the number of PR where did you pay? I don’t see your payment

**Comment by quintlistings** [comment]
Re: [trustwallet/assets] Add files via upload (PR #20187)

**Comment by quintlistings** [comment]
Hi, any update on this? The previous PR was #20187.
Kindly verify and update as soon as possible.

**Comment by quintlistings** [comment]
Thank you team.

Please process this as soon as possible. We have been waiting for a
month now. Thanks again.

**Comment by Cryptocool1** [comment]
• What is the purpose of this token? How will it benefit Trust Wallet users?
 • How is the token being distributed? Are you conducting an airdrop?
 • Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?
 • Is the token listed on a centralized/decentralized exchange?
 • Is a Smart Contract audit completed? Where can we find this information?

**Comment by quintlistings** [comment]
• What is the purpose of this token? How will it benefit Trust Wallet users?
> QUINT is the revolutionary token bringing real-world rewards to investors
by linking the metaverse with reality. Revolutionary super-staking pools
deliver returns while unlocking exclusive lifestyle perks. With a Boutique
NFT Marketplace, Quint Shop and more! With such a high amount of utilities,
users will use Trust Wallet to interact with the token and the ecosystem.

• How is the token being distributed? Are you conducting an airdrop?
> Tokens are being sold in Pancakeswap for now and Yes he had an airdrop
event during the Presale.

• Did you sold the tokens at an Initial Coin Offering (ICO) or a token
presale?
> Yes, we had a token presale

• Is the token listed on a centralized/decentralized exchange?
> Token is listed in Pancakeswap and we are in talks with more CEX
exchanges, listing in those exchanges is likely to happen anytime soon

• Is a Smart Contract audit completed? Where can we find this information?
> Yes, We have a Certik Audit, here is the link
https://www.certik.com/projects/quint

Hope we have responded to all the questions. Kindly do the needful as soon
as possible. Trust wallet's listing is a good milestone for us. Thank you.

**Comment by Cryptocool1** [comment]
Hello, your audit still in progress

**Comment by quintlistings** [comment]
You can check the Certik site, It says the final report has been delivered.
We have checked with Certik to update the progress bar.

**Comment by quintlistings** [comment]
If it's security that your team is worried about, there are a number of
places we have been doxxed, the whole team is open to the public as well.
Check our site *quint.io <http://quint.io>*

**Comment by quintlistings** [comment]
Hello, any updates on this?

**Comment by Cryptocool1** [comment]
hello, your logo should be full screen size, 256/256

**Comment by quintlistings** [comment]
Please find the attached the logo, 256/256 png

Question: Can we have two logos? One for Dark Mode and Light mode? If not
possible, pls ignore it.

Thank you.

**Comment by quintlistings** [comment]
How do I update the logo file?
@Cryptocool1 @BeckysLife @Iamdeadlyz @cryptomanz

**Comment by quintlistings** [comment]
The trust wallet logo isn't showing. How long will it usually take?

**Pull request merged**
