### PR TITLE
Add MUU (BEP20)

### PR DESCRIPTION
**Pull request by muuinu**
Adding info for BEP20 token 'MUU'.

PR created by <a href="https://assets.trustwallet.com">TW Assets Management</a>

### CODE REVIEW

**Comment by muuinu** [comment]
Hi Trustwallet Team,

In regards to https://github.com/trustwallet/assets/pull/22646. It is not a new token we want to be added, but the info updated for an old one. We migrated from an old contract **0xEA5E9F39F4B4Bc2684e49A0E43127F7f6F6be3b8** to a new one **0x2900e6b68658128784B9a1de242F811d938d8bA7**. Please see also see an official announcements on our twitter page:

https://twitter.com/muuinuofficial/status/1561859072374312962?s=46&t=6_uVykz-c05uZRgRcoOnPQ

https://twitter.com/muuinuofficial/status/1563091334394957824?s=46&t=6_uVykz-c05uZRgRcoOnPQ

https://twitter.com/muuinuofficial/status/1563286798301667328?s=46&t=6_uVykz-c05uZRgRcoOnPQ

**Comment by Nelly77M** [comment]
Thank you

**Comment by muuinu** [comment]
Hello,

Can we get an update on this?

**Comment by KDK7monta** [comment]
Please how do this work

**Pull request closed without merging**
