### PR TITLE
Pull Request for Mcontent

### PR DESCRIPTION
**Pull request by mcontent-v2**
Fixed the decimal value in the info.json file.

### CODE REVIEW

**Comment by Cryptocool1** [comment]
hello,
• What is the purpose of this token? How will it benefit Trust Wallet users?
 • How is the token being distributed? Are you conducting an airdrop?
 • Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?
 • Is the token listed on a centralized/decentralized exchange?
 • Is a Smart Contract audit completed? Where can we find this information?

**Comment by mcontent-v2** [comment]
> hello,
> • What is the purpose of this token? How will it benefit Trust Wallet users?
> • How is the token being distributed? Are you conducting an airdrop?
> • Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?
> • Is the token listed on a centralized/decentralized exchange?
> • Is a Smart Contract audit completed? Where can we find this information?

1. The purpose of MContent is the allow content creators a platform to obtain funding. Trust wallet users are getting a project with a fully functioning app. The Tokens also allow membership on the app platform.
2. The token was primarily purchased through DX sale and now pancake swap. Initially some airdrops were conducted for the previous MContent holders.
3.  Yes a DxSale was conducted along with a presale. The cost was the same across both categories. 1bnb=225B
4.  Yes we are actively trading on both BKEX and Pancakeswap. Soon we will be trading on bitmart starting July 21.   https://www.bkex.com/trade/MCONTENT_USDT
5. Yes an audit was completed it can be found in the white paper at www.mcontent.net or by this direct link https://solidity.finance/audits/mcontent/

Let me know if you have any other questions.

**Comment by cryptomanz** [comment]
can you please add links to your PR?
example: https://developer.trustwallet.com/add_new_asset#info-json-contents

**Comment by mcontent-v2** [comment]
> can you please add links to your PR?
> example: https://developer.trustwallet.com/add_new_asset#info-json-contents

Committed here or done in my branch with a new pull request?

**Comment by Cryptocool1** [comment]
you logo should be transparent, 
please change

**Pull request merged**
