### PR TITLE
Add HalfPizza Token (BEP20)

### PR DESCRIPTION
**Pull request by hifrank42**
Adding info for BEP20 token 'HalfPizza Token'.

PR created by <a href="https://assets.trustwallet.com">TW Assets Management</a>

### CODE REVIEW

**Comment by hifrank42** [comment]
So we pass the check, all I need to do is pay the 2000 TWT, then our logo
can be added in Trust wallet, right? thanks

merge-fee-bot[bot] ***@***.***> 于2021年8月17日周二 下午1:46写道：

**Comment by hifrank42** [comment]
So we pass the check, all I need to do is pay the 2000 TWT, then our logo
can be added in Trust wallet, right? thanks

Xinwei Yan ***@***.***> 于2021年8月17日周二 下午2:01写道：

**Comment by cryptomanz** [comment]
Can your answer some questions?
 • What is the purpose of this token? How will it benefit Trust Wallet users?
 • How is the token being distributed? Are you conducting an airdrop?
 • Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?
 • Is the token listed on a centralized/decentralized exchange?
 • Is a Smart Contract audit completed? Where can we find this information?

**Comment by hifrank42** [comment]
- What is the purpose of this token? How will it benefit Trust Wallet users?
HalfPizza is a decentralized reward-based autonomous community and the
token PIZA is used for circulation within the community ecosystem and
within the project board ecosystem. We have BTC price prediction game
which users can hold our token to participate and win profit and also
we offer the first NFT market that transfers real painting to NFT
using 3D scanner,  the store will be open first in Dafen Oil Painting
Village, Shenzhen in a month, and spread to Osaka and Dubai.
- How is the token being distributed? Are you conducting an airdrop?
The community is designed to have project earnings for holding
dividends and project earnings for liquidity mining dividends. We have
distrubuted airdrop via telegram and twitter, more than tens of
thousands of people joined our airdrop.
- Did you sell the tokens at an Initial Coin Offering (ICO) or a token presale?
85% Initial Liquidity, 5% Community Funding, 5% Project Functional
Dividends. 5% Project Experience Token Airdrop and Team Leader Bonus
Airdrop. And the airdrop has already been completed.
Contract address: 0xfc646d0b564bf191b3d3adf2b620a792e485e6da
- Is the token listed on a centralized/decentralized exchange?
Now, the token can be trade in pancakeswap and already submitted in
CMC and Coingecko, we are going to list on gate.io next month.
- Is a Smart Contract audit completed?
85% Locked UP：https://app.unicrypt.network/amm/pancake-v2/pair/0x28e2460b71a7652ef59ad839e712bffd32b0719b
The contract has been audited by soken and the link is:
https://halfpizza.com/report/security

Translated with www.DeepL.com/Translator (free version)

Nazar ***@***.***> 于2021年8月17日周二 下午11:57写道：

**Comment by hifrank42** [comment]
https://www.coingecko.com/en/coins/half-pizza
we are list in coingekco now

Xinwei Yan ***@***.***> 于2021年8月18日周三 上午9:45写道：

**Comment by hifrank42** [comment]
Thanks very much, while the logo didn't display in trustwallet?

CryptoA ***@***.***> 于2021年8月18日周三 下午12:55写道：

**Comment by hifrank42** [comment]
ignore it, its ok now

Xinwei Yan ***@***.***> 于2021年8月18日周三 下午1:24写道：

**Pull request merged**
