### PR TITLE
Add Alchemy(ACH) (BEP20)

### PR DESCRIPTION
**Pull request by thinkbankcoin**
Adding info for BEP20 token 'Alchemy(ACH)'.

PR created by <a href="https://assets.trustwallet.com">TW Assets Management</a>

### CODE REVIEW

**Comment by thinkbankcoin** [comment]
ACH (BEP20) is a cross-chain branch of ACH (ERC20) recently opened. The time is short. The number of addresses held by ACH (BEP20) and the number of transactions are not very good, but the data of ACH (ERC20) is very good. superior. So is this PR request passable?

**Comment by thinkbankcoin** [comment]
Can I donate now? Is the token I applied for qualified?

**Comment by thinkbankcoin** [comment]
Can I make a donation now?

**Comment by thinkbankcoin** [comment]
• What is the purpose of this token? How will it benefit Trust Wallet users?

Alchemy Pay's ACH token is used for Incentivising rewards for transactions for both merchants and users. These users will be able to use Trust Wallet to access Alchemy Pay's services, including for governance, transaction fees, and rewards, and pledging:

Transaction fees (or "gas fees") - fees for transactions, investments, processing, are payable either in the local fiat currency or ACH. Opting to pay for fees in ACH will result in various fee discounts depending on terms and conditions for the participants.
Rewards - use of the network will be rewarded with distribution of ACH in some cases. Enterprises such as financial institutions, payment companies, e-commerce platforms, and developers are the primary use case builders, and earn enterprise transaction rewards at rates negotiated based on network size and transaction volume. Consumer transaction rewards are earned through spending rebates, and other consumer-targeted payment solutions within the Alchemy Pay network.
Pledging - to join the network, merchant partners purchase a specified amount of the ACH token and ‘pledge’ it. This means that while using the network, partners lock up funds which can be returned if they choose to withdraw.
Governance - in the future we aim to use the token as a means of governance for token holders. At this time though, our project is still too nascent to offer significant decision-making to our community.

**Comment by thinkbankcoin** [comment]
How is the token being distributed?
Are you conducting an airdrop?

    ACH token has been distributed since 2020 to merchants and users of Alchemy Pay payment system as a form of incentives to drive crypto payments. Alchemy Pay has conducted airdrops from time to time to its community as part of its promotional efforts.

Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?

    ACH did not conduct ICO/IEO/IDO. It was sold in private sale (seed & private rounds) in 2020.

Is the token listed on a centralized/decentralized exchange?

    Yes, ACH is listed on major CEX such as Binance, Coinbase, Huobi, Coinone and more. ACH is also listed on major DEX such as UniSwap, SushiSwap and PancakeSwap

Is a Smart Contract audit completed? Where can we find this information?
    Yes - https://drive.google.com/file/d/1HTbnpve30kw9RdFEi3MZR44mwuq3dRSQ/view?usp=sharing

**Comment by thinkbankcoin** [comment]
Click here ACH (BEP20) and ACH (ERC20) can be exchanged 1:1 
https://anyswap.exchange/#/bridge

**Comment by thinkbankcoin** [comment]
How can I check if the merge was successful?

**Comment by thinkbankcoin** [comment]
Does my request need to be verified by three volunteers at the same time?

**Comment by thinkbankcoin** [comment]
@Iamdeadlyz @cryptomanz  
Can you tell me, do I still need to submit those materials?
 Thank you for the help.

**Comment by thinkbankcoin** [comment]
@Cryptocool1   can you help me?

**Comment by Cryptocool1** [comment]
Your PR is merged

**Comment by thinkbankcoin** [comment]
> Yes, I have seen it ,  thanks for your help!
Does my request require three administrators to authenticate at the same time?
Now, can you see that ACH (BEP20) has a logo on Trust Wallet?
Can I trade on Trust Wallet?
Thank you for you supper!

**Comment by thinkbankcoin** [comment]
@Cryptocool1  I can already see the ACH (BEP20) logo in Trust Wallet. thank you for your help!
But I can't view the market chart of ACH (BEP20) and the basic information of ACH, what should I do?
@Iamdeadlyz @cryptomanz  Thank you for you help!

**Pull request merged**
