### PR TITLE
Add Cherry Network (BSC)

### PR DESCRIPTION
**Pull request by therealcherry**

### CODE REVIEW

**Comment by ramsty** [comment]
Hi!
Could you answer some questions?
• What is the purpose of this token? How will it benefit Trust Wallet users?
• How is the token being distributed? Are you conducting an airdrop?
• Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?
• Is the token listed on a centralized/decentralized exchange?
• Is a Smart Contract audit completed? Where can we find this information?

**Comment by therealcherry** [comment]
The purpose of this token is to allow dApps developers on BSC to call functions in the Cherry Chain and pay its transaction fees in CHER tokes natively from BSC. Think of it as an interoperability token. Cherry Chain has special uses such as the trustless read and write of data in a distributed storage by smart contracts in runtime, which benefit dApps and their users (who may be using Trustwallet) alike. 

The token was distirbuted by private and public sale: 

-  https://blog.cherry.network/cherry-private-token-sale-successfully-completed-325dc625be2a
- https://blog.cherry.network/cherry-ido-roundup-80ffc49cbf13

The token is currently listed on Bilaxy, ZT Exchange, Pancakeswap, and Gate.io with daily trading volumes exceeding $10,000,000

The contract adopts the audited ERC20 standard.

**Comment by cryptomanz** [comment]
• Is a Smart Contract audit completed?

**Comment by Cryptocool1** [comment]
according to our rules, logo should be full size

**Comment by Cryptocool1** [comment]
Please come back to us when all criteria are met 
When creating new PR, make sure to mention this PR, so the fee can be reused

**Pull request closed without merging**
