### PR TITLE
Add TokenFi (TOKEN) (BEP20)

### PR DESCRIPTION
**Pull request by EagleFloki**
Adding info for BEP20 token 'TokenFi (TOKEN)'.

PR created by <a href="https://assets.trustwallet.com">TW Assets Management</a>

### CODE REVIEW

**Comment by EagleFloki** [comment]
We have same contract address on ETH too: https://github.com/trustwallet/assets/pull/26666
Please combine it here too and then we will pay the fee ASAP

**Comment by Cryptocool1** [comment]
Hello! 
• What is the purpose of this token? How will it benefit Trust Wallet users?
 • How is the token being distributed? Are you conducting an airdrop?
 • Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?
 • Is the token listed on a centralized/decentralized exchange?
 • Is a Smart Contract audit completed? Where can we find this information?

**Comment by EagleFloki** [comment]
> Hello! • What is the purpose of this token? How will it benefit Trust Wallet users? • How is the token being distributed? Are you conducting an airdrop? • Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale? • Is the token listed on a centralized/decentralized exchange? • Is a Smart Contract audit completed? Where can we find this information?

• What is the purpose of this token? How will it benefit Trust Wallet users?
 TokenFi aims to give users all they need to create successful crypto tokens or tokenize an asset in a simple all-in-one platform without writing a single line of code! It will have launchpad, token launcher, RWA tokenization, smart contract auditor and many more proects.
• How is the token being distributed? Are you conducting an airdrop?
Staking pool for Floki tokens: 56%
Liquidity Pool: 10% 
Treasury/Development: 22% 
Reward/Ecosystem Incentives: 5%
TOKEN Staking Pool: 7%
• Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?
It was fair launch. Launched at 50k mc.
• Is the token listed on a centralized/decentralized exchange?
Currently it's listed on Uniswap and Pancakeswap. Official CEX listings will start to come after the DAO vote about tax reduce within next week.
• Is a Smart Contract audit completed? Where can we find this information?
Our partner Certik is auditing the contract and it's being finalized!

**Comment by Cryptocool1** [comment]
Thank you. Feel free to come back to us once audit is done

**Comment by EagleFloki** [comment]
Audit is done: https://skynet.certik.com/projects/tokenfi
Could you open the PR? @Cryptocool1

**Comment by EagleFloki** [comment]
Can we pay the fee now? 
To confirm, after we pay, it will be listed on both ETH and BNB chain, right? @Cryptocool1 
ETH:
0x4507cEf57C46789eF8d1a19EA45f4216bae2B528

BSC:
0x4507cEf57C46789eF8d1a19EA45f4216bae2B528

**Comment by Cryptocool1** [comment]
Yes, you can pay a fee now. Please see instructions from merge fee bot message

**Comment by EagleFloki** [comment]
We will pay the fee please don't close the PR @Cryptocool1

**Comment by Mizanur1988** [comment]
> Adding info for BEP20 token 'TokenFi (TOKEN)'.
> 
> 
> 
> PR created by <a href="https://assets.trustwallet.com">TW Assets Management</a>

https://link.trustwallet.com/send?coin=20000714&address=0x79a57369fdC6DFa10Bc319B229372a96Aa82a316

**Pull request closed without merging**
