### PR TITLE
Add  Toman logo and info

### PR DESCRIPTION
**Pull request by tomantoken**
TMN 
Toman

### CODE REVIEW

**Comment by tomantoken** [comment]
https://tronscan.org/#/token/1003611

**Comment by tomantoken** [comment]
{
    "name": "Trust Wallet Token",
    "website": "https://trustwallet.com",
    "short_description": "Utility token to increase adoption of cryptocurrency.",
    "explorer": "https://etherscan.io/token/0xA866F0198208Eb07c83081d5136BE7f775c2399e",
    "socials": [
        {
            "name": "Twitter",
            "url": "https://twitter.com/trustwalletapp",
            "handle": "TrustWalletApp"
        },
        {
            "name": "Reddit",
            "url": "https://reddit.com/r/trustapp",
            "handle": "TrustApp"
        }
    ]
}

**Comment by tomantoken** [comment]
hi

**Comment by tomantoken** [comment]
please  check my req

**Comment by catenocrypt** [comment]
Feedback on this submissions:

- The `info.json` should be in folder  blockchains/tron/assets/1003611 .
- There are 2 logo files, only one should be there, in the same folder.

Please do these changes.  I cannot do it, as this PR is from a private/unknown repository, I cannot modify it.

image

image

**Comment by catenocrypt** [comment]
Merged with #5408 .

**Pull request closed without merging**
