### PR TITLE
Adding BSC version of Jupiter (bwJUP)

### PR DESCRIPTION
**Pull request by sigwo**
I just paid yesterday for the updated logo on ERC20 version. Hoping this can get merged without additional payment.

### CODE REVIEW

**Comment by sigwo** [comment]
I 'just' paid this yesterday....can I get this snuck in?

**Comment by catenocrypt** [comment]
Circulation can be combined (erc+bsc), but current level is still very low (148+8 holders).
As per our policy, there is a minimum requirement of 2500 holder addresses and 5000 transactions, in order to filter out scam tokens.
See the criteria at (mentioned in the first message by the bot): https://community.trustwallet.com/t/how-to-submit-a-token-logo/3863).
Closing PR for now. Please come back to us when all criteria are met.  Multi-chain and staking tokens may get special treatment, let us know if this is the case. 

https://etherscan.io/token/0x4B1E80cAC91e2216EEb63e29B957eB91Ae9C2Be8
https://bscscan.com/token/0x0231f91e02DebD20345Ae8AB7D71A41f8E140cE7

**Comment by catenocrypt** [comment]
> I 'just' paid this yesterday....can I get this snuck in?

If you have paid,. please provide TXID for investigation.

**Comment by sigwo** [comment]
TXID

https://explorer.binance.org/tx/9E1E446FCFC84DF83C224C2825F9F10872CAFC3ECC9B1500A6CCC0B743DABC5F

-SG

**Comment by catenocrypt** [comment]
OK, that was for #5596, now I understand your request.  Checking.

**Pull request merged**
