### PR TITLE
Add LittlePandaMoon (BEP20)

### PR DESCRIPTION
**Pull request by littlepandamoon**
Adding info for BEP20 token 'LittlePandaMoon'.

PR created by <a href="https://assets.trustwallet.com">TW Assets Management</a>

### CODE REVIEW

**Comment by Cryptocool1** [comment]
cannot find contract on your website
please check

**Comment by littlepandamoon** [comment]
Will check with our community and update

**Comment by littlepandamoon** [comment]
@Cryptocool1 we just updated our website with the contract information.
please let us know if any more changes required to get this approved 😄

**Comment by Cryptocool1** [comment]
> @Cryptocool1 we just updated our website with the contract information.
> please let us know if any more changes required to get this approved 😄

Great,  thanks!

**Comment by littlepandamoon** [comment]
@Cryptocool1 Thanks 👍

**Pull request merged**
