### PR TITLE
Add Floki Inu (BEP20)

### PR DESCRIPTION
**Pull request by ghost**
Adding info for BEP20 token 'Floki Inu'.

PR created by <a href="https://assets.trustwallet.com">TW Assets Management</a>

### CODE REVIEW

**Comment by sohailamir** [comment]
Hello, has this gone through?

**Comment by sohailamir** [comment]
Hi, is it possible to find out which checks have failed please?

**Comment by sohailamir** [comment]
Hi there, just checking if this is good to be merged now? I understand there is a mention of being under 3,000 holders.

However, if you take a look at our ETH contract which is ALSO on TrustWallet we have over 12,000 holders on there. We just recently launched on Smart Chain and we've developed a cross chain swap bridge so that would actually mean 15,000+ holders.

If you go to CoinGecko or CoinMarketCap and type in 'Floki', you'll see we have both ETH and BSC versions of our contract listed.

It will definitely benefit your users by fast tracking the merging of this one.

**Comment by sohailamir** [comment]
Any updates here by any chance?

**Comment by sohailamir** [comment]
We already have around 3,900 holders now on BSC.

**Comment by Cryptocool1** [comment]
As per our policy, brand new tokens are not included, there is a minimum requirement of 5000 holder addresses and 10000 transactions, in order to filter out scam tokens.
See the criteria at (mentioned in the first message by the bot): https://community.trustwallet.com/t/how-to-submit-a-token-logo/3863).

**Comment by sohailamir** [comment]
Okay please do hold up we have 4,800 holders currently and enough TXs. We'll likely hit that target tonight.

**Comment by sohailamir** [comment]
> As per our policy, brand new tokens are not included, there is a minimum requirement of 5000 holder addresses and 10000 transactions, in order to filter out scam tokens.
> See the criteria at (mentioned in the first message by the bot): https://community.trustwallet.com/t/how-to-submit-a-token-logo/3863).

Hi Crypto Cool, we have over 5,000 holders!

**Comment by cryptomanz** [comment]
do you want to add both ERC20 and BEP20 tokens?

**Comment by sohailamir** [comment]
> do you want to add both ERC20 and BEP20 tokens?

No the ERC20 one is already added. Only need to add the BEP20 Floki please.

**Comment by sohailamir** [comment]
> do you want to add both ERC20 and BEP20 tokens?

Any updated? We just need the BSC Floki added.

**Comment by sohailamir** [comment]
> do you want to add both ERC20 and BEP20 tokens?

Hey mate, so we're well over 5,000 holders on BSC now is it possible to get our token details updated please?

Also we only need to add BSC/BEP20 Floki. Not ERC20. That was already added previously.

By the way one more query. We are actually upgrading our ETH contract via a hard fork next week. Would it be possible to track the removal and replacement with our new contract details when that's done?

**Comment by Cryptocool1** [comment]
Can you create new PR without ERC20 token files?

**Comment by sohailamir** [comment]
I really don't know how to do this. They asked me to do this previously with just the BSC token files but every time I do a new pull request it seems to automatically include ERC20 files I uploaded previously (and paid for) for the same token.

I simply fork the the correct branch, add the BSC files only but when I click on Pull Requests > Create new pull request it seems to include changes to the ERC20 files.

If there's any issue I could simply re-upload both the ERC20 and BSC files for the Floki Inu token, otherwise it just doesn't seem to upload the BSC files only and I have no idea how to remove the upload of the ERC20 files.

This is already a new request as it is so I'm having some real issues getting this done and I've paid for this listing quite a while back now.

I'd really appreciate some help with this please.

**Comment by sohailamir** [comment]
[0x2b3f34e9d4b127797ce6244ea341a83733ddd6e4.zip](https://github.com/trustwallet/assets/files/6950532/0x2b3f34e9d4b127797ce6244ea341a83733ddd6e4.zip)

These are the files I need to upload for BSC specifically.

**Comment by sohailamir** [comment]
Could someone kindly assist here as a matter of urgency with regards to the BSC Floki listing?

Also our ETH contract underwent a planned hard fork yesterday and now has a new contract address.

What is the process for adding our new ETH contract details and what do you propose we do with the previous contract details? Do we remove it from the database or simply add the new contract details on top?

The new ETH contract is 0x43f11c02439e2736800433b4594994bd43cd066d.

**Comment by cryptomanz** [comment]
#12617 (BEP20)Merged

**Comment by sohailamir** [comment]
Thanks for this Cryptomanz.

Just an enquiry with regards to our ERC20 token listing.

We upgraded our contract yesterday to a new one. Do we need to remove the old contract or do we leave that one as it is and simply create a new pull request to add the new contract and pay again?

**Pull request closed without merging**
