### PR TITLE
Add Toad Network (BEP20)

### PR DESCRIPTION
**Pull request by Spenhouet**
Hi, as a community member of Toad, I would like to request that the Toad icon is added to Trust Wallet.

### CODE REVIEW

**Comment by Spenhouet** [comment]
Audit by SpadeTech: https://spadetech.io/wp-content/uploads/2021/06/toad_network_audit_report.pdf

**Comment by Spenhouet** [comment]
@ramsty Is there something I need to fix with respect to the failing "pull_request_ci" action?

**Comment by ramsty** [comment]
id is not in checksum format, should be 0x463E737D8F740395ABf44f7aac2D9531D8D539E9 (not 0x463e737d8f740395abf44f7aac2d9531d8d539e9). Please rename it. You may need to rename to a temp name first, then to the checksum format, because lowercase-uppercase-only renames are often ignored by the Git client or the filesystem

**Comment by Spenhouet** [comment]
@ramsty I did a temporary commit where I changed the ID and the ID in the BSCScan URL to "temp" and then the last commit with the correct format. But it does not seem to be picked up by the merge-fee-bot.

**Comment by Spenhouet** [comment]
Ah, the issue might be the folder name. I'm going to address it.

**Pull request closed without merging**
