### PR TITLE
Add BIGH BULL (BEP20)

### PR DESCRIPTION
**Pull request by BighBullTech**
Adding info for BEP20 token 'BIGH BULL'.

PR created by <a href="https://assets.trustwallet.com">TW Assets Management</a>

### CODE REVIEW

**Comment by BighBullTech** [comment]
Fees already Paid in Previous PR https://github.com/trustwallet/assets/pull/18698

**Comment by BighBullTech** [comment]
Fees already Paid in Previous PR https://github.com/trustwallet/assets/pull/18698

**Comment by BighBullTech** [comment]
Already paid through PR 18698

**Comment by Cryptocool1** [comment]
once again, we have already put status abandoned to your old token and removed logo. when you search token name you can only see new contract.

**Comment by BighBullTech** [comment]
Ok you are correct as a listed new contract, it's absolutely perfect.

But
I am saying many time to you from last around 18 hrs that, there is logo
visible to all users, even they clear cache also.

And I said to you so many times that, if you are searching at trust wallet
from old contract address, logo will be visible.
If logo deleted so how can visible to all existing users & how logo visible
to searching from old contract address.

Why you are not giving me any kind of screenshot after searching from old
contract address, there is no logo.

Why you are not sharing any kind of proof, if you are correct share me the
proof.

Otherwise I will proof there is logo visible.

**Pull request closed without merging**
