### PR TITLE
Add Denarii (ARI) Logo

### PR DESCRIPTION
**Pull request by metaspartan**
Add the Denarii (ARI) Token Logo : 0x8A8b5318d3A59fa6D1d0A83A1B0506f2796b5670

Reopening this PR as we meet the requirements now for the amount of hodlers and transactions.

### CODE REVIEW

**Comment by Iamdeadlyz** [comment]
A little bit more tx and you'll meet that requirement.

Also, please provide more details about this project.
https://community.trustwallet.com/t/how-to-submit-a-token-logo/3863#how-to-get-approved
You can follow this format when adding an info.json file:
```
{
   “name”:“Bitcoin”,
   “website”:“https://bitcoin.org”,
   “source_code”:“https://github.com/bitcoin”,
   “white_paper”:“https://bitcoin.org/bitcoin.pdf”,
   “short_description”:“Bitcoin is a cryptocurrency and worldwide payment system.“,
   “explorer”:“https://blockchain.info”,
   “research”:“https://research.binance.com/en/projects/bitcoin”
}

**Comment by carsenk** [comment]
We are so so so so so close man, can you just give us a pass, I am sure we will be over 1k here in a few hours at most?

Would love to have the ARI logo available across dapps

```
{
   “name”:“Denarii”,
   “website”:“https://ari.finance”,
   “source_code”:“https://etherscan.io/token/0x8a8b5318d3a59fa6d1d0a83a1b0506f2796b5670#readContract”,
   “white_paper”:“Not Available, Roadmap will be coming soon, working product at https://pool.ari.finance”,
   “short_description”:“Denarii (ARI) is an ERC20 token with staking and liquidity pool staking“,
   “explorer”:“https://etherscan.io”,
   “research”:“ERC20 Token - Not available yet”
}
```

**Comment by carsenk** [comment]
image

We will be making payment shortly

**Comment by carsenk** [comment]
Payment Sent.

**Pull request merged**
