### PR TITLE
Add Dabb Doge  (BEP20)

### PR DESCRIPTION
**Pull request by Tdeveloper2022**
Adding info for BEP20 token 'Dabb Doge '.

PR created by <a href="https://assets.trustwallet.com">TW Assets Management</a>

### CODE REVIEW

**Comment by Tdeveloper2022** [comment]
Hello
its ok we will pay it

**Comment by cryptomanz** [comment]
• What is the purpose of this token? How will it benefit Trust Wallet users?
 • How is the token being distributed? Are you conducting an airdrop?
 • Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?
 • Is the token listed on a centralized/decentralized exchange?
 • Is a Smart Contract audit completed? Where can we find this information?

**Comment by Tdeveloper2022** [comment]
fee paid :
https://explorer.binance.org/tx/C2B01B9083E7113A67FFFB5A42A45225D3D690B4B1611D4C1042D678481F3A0E

**Comment by Tdeveloper2022** [comment]
• What is the purpose of this token? How will it benefit Trust Wallet
users?
 DABB DOGE is a decentralized peer-to-peer digital currency that enables
instant transactions to anyone anywhere in the world without any
transaction fees. Dabb Doge has joined a few NGOs to help the stray dogs
either who had an accident or are left stranded by their owner. Team has
been able to rescue 487 Dogs, which gave birth to 176 puppies. We wish to
continue on this path and help dogs as they can?t speak for themselves so
someone has to stand for them and provide care in any way possible.
Especially India, where stray dogs are on the streets which is a huge
concern. So we have pledged to expand our horizon and will start helping
dogs nationwide.
whitepaper <https://www.dabbdoge.com/dabb-doge-whitepaper.pdf>
• How is the token being distributed? Are you conducting an airdrop?
no we did for about 2 k address
• Did you sold the tokens at an Initial Coin Offering (ICO) or a token
presale?
No
• Is the token listed on a centralized/decentralized exchange? Yes
https://poocoin.app/tokens/0xc638a73969c0f7442ba8f5ffda9968434891034b
https://twitter.com/Hotbit_news/status/1510100897367732224?s=20&t=xVo8UXzxJn61iepNaQEwiA
Is a Smart Contract audit completed? Where can we find this information? yes
https://github.com/TechRate/Smart-Contract-Audits/blob/main/March/Dabb%20Doge%20Full%20Smart%20Contract%20Security%20Audit.pdf

**Comment by Tdeveloper2022** [comment]
Hello
thank you but there is no price for DDoge and not even any chart !
please fix it for us

**Pull request merged**
