### PR TITLE
Please add DDIM BEP20 Token

### PR DESCRIPTION
**Pull request by DuckyDao**
Please add the DDIM **BEP20** Version to your database.

This is the BEP20 Version of the DDIM Token you can find here https://etherscan.io/token/0xFbEEa1C75E4c4465CB2FCCc9c6d6afe984558E20 which was already added to your database in December 2020. 

We recently launched our DuckBridge to go Cross-Chain https://duckbridge.io/

Website: https://duckdao.io/
Twitter: https://twitter.com/dao_duck
Coingecko: https://www.coingecko.com/en/coins/duckdaodime

### CODE REVIEW

**Comment by DuckyDao** [comment]
@catenocrypt can you check this case quick before we pay? As we don't have the required holders on BEP20 yet of course, but we go cross-chain and we want to add the logo to your wallet and to Pancakeswap (which uses your wallet assets)

**Comment by catenocrypt** [comment]
As per our policy, brand new tokens are not included, there is a minimum requirement of 2500 holder addresses and 5000 transactions, in order to filter out scam tokens.
See the criteria at (mentioned in the first message by the bot): https://community.trustwallet.com/t/how-to-submit-a-token-logo/3863).
This token has no real usage yet (7 holders). Closing PR for now. Please come back to us when all criteria are met.  Multi-chain and staking tokens may get special treatment, let us know if this is the case. 

https://bscscan.com/token/0xc9132c76060f6b319764ea075973a650a1a53bc9

**Comment by DuckyDao** [comment]
@catenocrypt we are not a scam token lol https://www.coingecko.com/en/coins/duckdaodime

**Comment by catenocrypt** [comment]
Note: ERC20 version already present, with high circulation.
https://etherscan.io/token/0xFbEEa1C75E4c4465CB2FCCc9c6d6afe984558E20

**Comment by catenocrypt** [comment]
Correction needed:  Folder corresponding to token contract should be in 'checksum format', please rename (a two-phase rename may be needed, as lowercase-uppercase-only renames may be ignored).

❌  Contract is not in checksum format, should be 0xc9132C76060F6b319764Ea075973a650A1a53bC9 (not 0xc9132c76060f6b319764ea075973a650a1a53bc9). Please change it.

**Pull request merged**
