### PR TITLE
Add Shak logo and info

### PR DESCRIPTION
**Pull request by ShakitaInu**

### CODE REVIEW

**Comment by Cryptocool1** [comment]
• What is the purpose of this token? How will it benefit Trust Wallet users?
 • How is the token being distributed? Are you conducting an airdrop?
 • Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?
 • Is the token listed on a centralized/decentralized exchange?
 • Is a Smart Contract audit completed? Where can we find this information?

**Comment by ShakitaInu** [comment]
hi @Cryptocool1, re your questions.

What is the purpose of this token?

$SHAK token is the token for the Shakita Inu project and its community. It has multiple use cases that will expand as the project grows. Firstly we wanted to create a 0% tax dog coin on Binance Smart Chain so new-to-crypto investors have a trustworthy low fee gateway. New to crypto investors are often attracted to dog coins and many of our holders tell us this is their first experience and they really enjoyed it. Our community is very positive and focused on being informative, educational, and interactive with its members. We also want to have rewards for our 2D game in the form of cryptocurrency and this is another big reason for us to have the $SHAK token. We also have something called BIG $SHAK LOTTO where we give random holders prizes and our goal is to give back. As the token price grows the prizes get bigger and thousands of dollars have been given away so far. We intend to giveaway $1,000,000 if we reach $1 in price. This is an ambitious target but our market cap would still be 3 times smaller than SHIB's at this price so it possible. We also do community competitions reward them with tokens. The token has deflationary tokenomics and we aim to increase its utility more as we grow.

How will it benefit Trust Wallet users?

We currently have 9k hodlers and our community is extremely active. There are thousands of messages in the Telegram chat every day and many of those are people asking us to add the logo information to Trust Wallet. Trust Wallet is a preferred wallet for many of our users and we have 'how to buy SHAK' guides that include Trust Wallet for this reason. Unfortunately, there are also scammers who imitate the team members and the project with fake groups and websites so I think this will also help keep Trust Wallet users and our community safer. WE have verified our token with a logo on as many platforms as possible, including BSCscan and CoinMarketCap.

How is the token being distributed?

The tokens were initially bought from either DODO DEX or Pancake Swap DEX. The Founder bought tokens like everyone else and didn't distribute himself any. The project gains a portion of tokens from sell tax (10% - 4% of which is burned). 

Are you conducting an airdrop?

We migrated from Pancake Swap v1 to v2 and when we did so we changed token smart contracts. This current smart contract was launched in August and airdropped to previous holders of the old token at a 1:1 ratio. It is the same project, we simply replaced the old contract and swapped tokens with the allocations and value remains the same. The only other airdrops we do is if an individual wins the BIG $SHAK LOTTO they are sent their prize in SHAK tokens.

Did you sell tokens in an initial ICO or presale?

No the sale of this token was public on the DEX from day one, same for the old version of the token. There has never been a presale. IT as a fair launch project.

Is the token listed on a CEX/DEX?

The token is listed on Coin Tiger CEX and will soon be listed on more this month (confirmed). We are also listed on Pancake Swap with a consistent daily volume of $300k-$5m. We will get our token in their official list asap.

Is our Smart contract audited? Where to find info?

The smart contract was audited by a third-party solidity developer. We have not had a company audit this token but we have been active for months with millions of dollars of trading volume and CEX listings approved. 

What information would you like regarding the Audit?

**Comment by Cryptocool1** [comment]
We require the full smart contract  audit

**Comment by ShakitaInu** [comment]
We will get back to you on this thanks

**Comment by Cryptocool1** [comment]
Please come back to us when all criteria are met.
When creating a new PR make sure to mention this PR, so that we can see that fee has been paid already here.

**Pull request closed without merging**
