### PR TITLE
EgonSwap Token Logo for Pancakeswap

### PR DESCRIPTION
**Pull request by EgonSwap**
Hi,
    EgonSwap Finance is a long-term project building for several use cases with the rewarding mechanisms for all people of the world using decentralized systems. Use case comprises of Crypto Wallet App, Metaverse Game, and even a mining community of more than two million people! 
    
    Egonswap has more than 1 lac Users/Holders, You can visit at https://bscscan.com/address/0x05995a068bdac17c582eC75AB46bb8e7394be1d9. Please Add Our Token Logo to the Trustwallet Assets, I'll be very thankful for your Special Intentions. 
    
    Regards,
    Egonswap

### CODE REVIEW

**Comment by Cryptocool1** [comment]
Please create new PR, follow doc https://developer.trustwallet.com/assets/requirements
You may want to try our Assets app in beta; go to https://assets.trustwallet.com, log on with Github, enter contract ID, logo and some additional info, and it will create a PR for you.
See https://developer.trustwallet.com/assets/repository_details

**Comment by EgonSwap** [comment]
Mate, I tried there, added everything, but got an error that "Number of Holders Not checked. ", I added everything, but getting this error. Please guide me mate. I'll be very thankful for your support. 

Regards,
EgonSwap

**Comment by Cryptocool1** [comment]
Hello, just follow my instructions and I will check your number of holders

**Comment by EgonSwap** [comment]
image


Mate, Filled the Complete Details there, but Once I click Create Pull Request I got this error mate. Please guide me. 

Regards,
EgonSwap

**Comment by EgonSwap** [comment]
image


Mate, It's created. Please check it. I'm very Thankful for support. 


Regards,
EgonSwap

**Pull request closed without merging**
