### PR TITLE
Add TWT Logo + Info

### PR DESCRIPTION
**Pull request by KichiCoin**

### CODE REVIEW

**Review by ny030897 — APPROVED** [review]

**Comment by Cryptocool1** [comment]
can you please add links to your PR?
example: https://developer.trustwallet.com/add_new_asset#info-json-contents

**Comment by KichiCoin** [comment]
> can you please add links to your PR?
> example: https://developer.trustwallet.com/add_new_asset#info-json-contents

Links have been added

**Comment by KichiCoin** [comment]
Discord link has been updated from https://discord.gg/cHPHJtDJhq to https://discord.com/invite/cHPHJtDJhq

**Comment by KichiCoin** [comment]
@Cryptocool1 How long until this can be processed?

**Comment by Cryptocool1** [comment]
could you please answer some question
• What is the purpose of this token? How will it benefit Trust Wallet users?
 • How is the token being distributed? Are you conducting an airdrop?
 • Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?
 • Is the token listed on a centralized/decentralized exchange?
 • Is a Smart Contract audit completed? Where can we find this information?

**Comment by KichiCoin** [comment]
> could you please answer some question
> • What is the purpose of this token? How will it benefit Trust Wallet users?
> • How is the token being distributed? Are you conducting an airdrop?
> • Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?
> • Is the token listed on a centralized/decentralized exchange?
> • Is a Smart Contract audit completed? Where can we find this information?

• What is the purpose of this token? Lottery + Charity token with plans to make Games and NFT Platform to tackle the issue of funds in educational institutions and to help raise scholarships for students. 

How will it benefit Trust Wallet users? It will benefit by giving additional options and give trust to trust wallet users by being able to see our logo on the app. 


• How is the token being distributed? Are you conducting an airdrop?
It is currently live on PancakeSwap 

• Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?
5% of initial supply sold through DxSale 

• Is the token listed on a centralized/decentralized exchange?
PancakeSwap, soon on CoinsBit


• Is a Smart Contract audit completed? Where can we find this information?
Yes 3 audits completed. You can find this on our website kichicoin.io

**Comment by Cryptocool1** [comment]
can you please add links to your PR?
example: https://developer.trustwallet.com/add_new_asset#info-json-contents

**Comment by KichiCoin** [comment]
> can you please add links to your PR?
> example: https://developer.trustwallet.com/add_new_asset#info-json-contents

image

I have already done that

**Pull request merged**
