### PR TITLE
Add Logo

### PR DESCRIPTION
**Pull request by holdplatform**

### CODE REVIEW

**Comment by holdplatform** [comment]
Done, I have transferred 1 BNB with memo code 2512
TX Hash https://explorer.binance.org/tx/35244CC08ADD737393445D26A2E29D5685C0F070B83AAC9FB9811580670D2724

**Comment by Fargo-Au** [comment]
#2512 
Logo_Fargo
https://raw.githubusercontent.com/trustwallet/assets/master/blockchains/ethereum/66129107/0x81e70ea3d76d713ea1f501f89417af9bcc2a5f9f.png

**Comment by catenocrypt** [comment]
You mean this:?

https://github.com/trustwallet/assets/blob/master/blockchains/ethereum/assets/0x49a6123356b998EF9478C495E3D162A2F4eC4363/logo.png

**Comment by Fargo-Au** [comment]
I want to update the Trust Wallet logo.
How.
I will pay as required.

**Comment by catenocrypt** [comment]
The new logo from this PR has been already updated.

**Comment by Fargo-Au** [comment]
How long can I see it?
How much do I need to pay you?

**Comment by catenocrypt** [comment]
Logo has been updated, but due to caching (in the app) it can take some time until it appears in the app.
1 BNB has been paid already, no need for additional pay.  Payment TX ID: https://explorer.binance.org/tx/35244CC08ADD737393445D26A2E29D5685C0F070B83AAC9FB9811580670D2724

**Comment by Fargo-Au** [comment]
Great i thank you

**Comment by Fargo-Au** [comment]
Hello sir.
I still haven't seen the logo on the trust wallet ??. What should I do ?

**Comment by Fargo-Au** [comment]
I am noticing the silence from you. please help me. I can pay you $ 20 if you complete it.

**Comment by catenocrypt** [comment]
This request was merged 10 days ago, and I can see the logo in Trust Wallet.  What is the problem then?

image

**Comment by Fargo-Au** [comment]
Not. Our Autoken contract code is: 0x81e70ea3d76d713ea1f501f89417af9bcc2a5f9f. 
# 2512 https://raw.githubusercontent.com/trustwallet/assets/master/blockchains/ethereum/66129107/0x81e70ea3d76d713ea1f501f89417af9bcc2a5f9f.png
Logo_Fargo

**Comment by holdplatform** [comment]
Hey, @Fargo-Au , You need create new pull request. 
**NOT HERE**, because this pull request is the submission of Holdplatform Token Logo
( 0x49a6123356b998ef9478c495e3d162a2f4ec4363 ) 

I pay twice, BNB & TWT
Because my TWT withdrawal takes a long time :)

**Comment by catenocrypt** [comment]
@Fargo-Au , create new PR if you want your logo to be included.

**Comment by Fargo-Au** [comment]
Can someone guide me. I will pay for it.

**Pull request merged**
