### PR TITLE
Add BNB ( YOSWAP) 

### PR DESCRIPTION
**Pull request by yoswap**
- [ ] your swap (yoswap) 

- [x] logo https://t.me/yourswap/10

- [ ] #5139 
-[]https://bscscan.com/token/0x603d6f31b4135c65677f43ba0e7d2777af3122d9

### CODE REVIEW

**Review by yoswap — COMMENTED** [review]
YOSWAP

**Review by yoswap — COMMENTED** [review]
Change

**Comment by catenocrypto** [comment]
Pay fee

**Comment by yoswap** [comment]
All ready pay 1000 bnb 











Sent from Yahoo Mail on Android 
 
  On Mon, 21 Dec 2020 at 3:35 pm, Trust Wallet<notifications@github.com> wrote:   


Pay fee

**Comment by catenocrypto** [comment]
Sorry for inconvenience cause but TWT fee payment is disabled and we will refund that fee to the same address from where you send . 
To get 1000 TWT refund and process your request further please send 3 bnb to address 
bnb1f29knh46qztqvy6ha6r3gpm5jxx8aujdd4gq2j
with memo 5141 .

**Comment by yoswap** [comment]
swap (yoswap)

 logo https://t.me/yourswap/10

 #5139
-[]https://bscscan.com/token/0x603d6f31b4135c65677f43ba0e7d2777af3122d9

**Comment by catenocrypt** [comment]
This PR does not contain files in the expected structure.
Please create new PR, according to the guide https://community.trustwallet.com/t/how-to-submit-a-token-logo/3863.

If working with Github is difficult, you may want to try our new Assets app in beta;  close this PR; go to https://assets.trustwallet.com, log on with Github, enter contract ID, logo and some additional info, and it will create a PR for you.
See  https://community.trustwallet.com/t/how-to-submit-a-token-logo-using-assets-app/82957.

**Pull request closed without merging**
