### PR TITLE
Add Black Phoenix (TRC20)

### PR DESCRIPTION
**Pull request by BLACKPHOENIXBPX**
Adding info for TRC20 token 'Black Phoenix'.

PR created by <a href="https://assets.trustwallet.com">TW Assets Management</a>

### CODE REVIEW

**Comment by Cryptocool1** [comment]
• What is the purpose of this token? How will it benefit Trust Wallet users?
 • How is the token being distributed? Are you conducting an airdrop?
 • Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?
 • Is the token listed on a centralized/decentralized exchange?
 • Is a Smart Contract audit completed? Where can we find this information?

**Comment by BLACKPHOENIXBPX** [comment]
Black Phoenix is a bright future token , we mentioned our future plans for the ways to users profit by BPX token 
62.75% of tital supply is locked and the rest is distributing by Airdrop , bounties and tradings in Exchanges 
We had Payment Airdrop at the first months of launching the token 
Black Phoenix listed in 6 Exchanges : Bitrue.com , XT.com  , Vindax , Azbit 
You can Find Informations here : https://blackphoenixbpx.com/
https://coinmarketcap.com/currencies/black-phoenix/
https://tronscan.org/#/token20/TXBcx59eDVndV5upFQnTR2xdvqFd5reXET
https://u.today/press-releases/black-phoenix-bpx-will-be-listed-on-the-top-13-exchange-of-the-world-bitrue-with-11

Also we have submit the pull request as TRC-20 why is typed TRC-10 at the First of the pull ??

**Comment by BLACKPHOENIXBPX** [comment]
Can we do The payment? Is there no Problem??

**Comment by BLACKPHOENIXBPX** [comment]
@Cryptocool1 Black Phoenix is a bright future token , we mentioned our future plans for the ways to users profit by BPX token
62.75% of tital supply is locked and the rest is distributing by Airdrop , bounties and tradings in Exchanges
We had Payment Airdrop at the first months of launching the token
Black Phoenix listed in 6 Exchanges : Bitrue.com , XT.com , Vindax , Azbit
You can Find Informations here : https://blackphoenixbpx.com/
https://coinmarketcap.com/currencies/black-phoenix/
https://tronscan.org/#/token20/TXBcx59eDVndV5upFQnTR2xdvqFd5reXET
https://u.today/press-releases/black-phoenix-bpx-will-be-listed-on-the-top-13-exchange-of-the-world-bitrue-with-11

Also we have submit the pull request as TRC-20 why is typed TRC-10 at the First of the pull ??

**Comment by Cryptocool1** [comment]
Is a Smart Contract audit completed? Where can we find this information?

**Comment by BLACKPHOENIXBPX** [comment]
@Cryptocool1 yes is complete you can find Information in Tronscan Explorer :
 [](https://tronscan.io/#/token20/TXBcx59eDVndV5upFQnTR2xdvqFd5reXET)

**Comment by Cryptocool1** [comment]
can you send contract audit here?

**Comment by BLACKPHOENIXBPX** [comment]
@Cryptocool1 You mean the contract Address? here you are : **_TXBcx59eDVndV5upFQnTR2xdvqFd5reXET_**

**Comment by Cryptocool1** [comment]
we require smart contract audit, not contract address

**Comment by BLACKPHOENIXBPX** [comment]
> we require smart contract audit, not contract address
What is youre meaning of smart contract audit ?

**Pull request closed without merging**
