### PR TITLE
Add files via upload

### PR DESCRIPTION
**Pull request by cryptored007**

### CODE REVIEW

**Comment by cryptomanz** [comment]
• What is the purpose of this token? How will it benefit Trust Wallet users?
 • How is the token being distributed? Are you conducting an airdrop?
 • Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?
 • Is the token listed on a centralized/decentralized exchange?
 • Is a Smart Contract audit completed? Where can we find this information?

**Comment by cryptored007** [comment]
> • What is the purpose of this token? How will it benefit Trust Wallet users? • How is the token being distributed? Are you conducting an airdrop? • Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale? • Is the token listed on a centralized/decentralized exchange? • Is a Smart Contract audit completed? Where can we find this information?

Here you go...

• What is the purpose of this token? How will it benefit Trust Wallet users?
  TCGCoin 2.0 is the utility token for TCG.World which is an open world Metaverse on Binance Smart Chain. TCG World is integrated with Trust Wallet for users to connect to our platform for purchases so having the TCG Coin 2.0 Logo will benefit users to know they are using the correct token.

• How is the token being distributed? Are you conducting an airdrop?
  TCGCoin 2.0 is already in circulation. Our initial launch of TCGCoin (V1) was in May 2021 and in August 2021 we migrated to a new Cross chain smart contract to enable us to launch on Ethereum and Polygon. Existing holders of v1 had their tokens sent to their account by sending their old coins back to our deployer and us sending the new ones in batches

• Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?
  We did a fair launch with no ICO or Presale. The fair launch was in May 2021 on Pancake Swap with $15,000 added to the liquidity pool before launch

• Is the token listed on a centralized/decentralized exchange?
  TCGCoin 2.0 is currently listed on Pancake Swap, Coinsbit and LBank and we are in the process of listing with 4 other Centralized exchanges this month. Contracts are in place awaiting listing dates

• Is a Smart Contract audit completed? Where can we find this information?
  Attached are the multiple  Audits for our BSC and ERC20 versions.

**Comment by cryptored007** [comment]
[TCG-code-audit-by-DRIVENx.pdf](https://github.com/trustwallet/assets/files/7740107/TCG-code-audit-by-DRIVENx.pdf)
[TCGCoin - Smart Contract Security Audit Report.pdf](https://github.com/trustwallet/assets/files/7740108/TCGCoin.-.Smart.Contract.Security.Audit.Report.pdf)
[TCG-ERC20-Code-Audit.pdf](https://github.com/trustwallet/assets/files/7740109/TCG-ERC20-Code-Audit.pdf)

**Comment by cryptored007** [comment]
@cryptomanz Please confirm if you got all the details you needed.

**Comment by ramsty** [comment]
your logo should be a full screen
Example:
https://community.trustwallet.com/t/how-to-submit-a-token-logo/3863
137116359-c2bb87b7-239a-4c8d-b54e-4a679c621186

**Comment by cryptored007** [comment]
> your logo should be a full screen Example: https://community.trustwallet.com/t/how-to-submit-a-token-logo/3863 137116359-c2bb87b7-239a-4c8d-b54e-4a679c621186

@ramsty Made the logo full screen. Please do the needful.

**Comment by cryptored007** [comment]
@ramsty Thanks

**Pull request merged**
