### PR TITLE
Add Crucifearous Finance (BEP20)

### PR DESCRIPTION
**Pull request by Crucifearous2021**
Adding info for BEP20 token 'Crucifearous Finance'.

PR created by <a href="https://assets.trustwallet.com">TW Assets Management</a>

### CODE REVIEW

**Comment by Crucifearous2021** [comment]
This is the New PR from https://github.com/trustwallet/assets/pull/10118 kindly check again

**Comment by Crucifearous2021** [comment]
Did we make correctly the correction needed from PR #10118  ???

**Comment by cryptomanz** [comment]
#10118 paid

**Comment by Crucifearous2021** [comment]
we already make the changes but still it has the same error... what happened?

**Comment by Crucifearous2021** [comment]
We already reduced the logo and corrected all the needed for correction. Please make the comparison between from PR #10118 and PR #10124 and you can see the changes.

**Comment by Cryptocool1** [comment]
> we already make the changes but still it has the same error... what happened?
PR should include only 2 files. Please delete 2 incorrect

**Comment by Cryptocool1** [comment]
fixed

**Pull request merged**
