### PR TITLE
Add Doge King (BEP20)

### PR DESCRIPTION
**Pull request by blockartist**
Adding info for BEP20 token 'Doge King'.

PR created by <a href="https://assets.trustwallet.com">TW Assets Management</a>

### CODE REVIEW

**Comment by blockartist** [comment]
Please update.

**Comment by Cryptocool1** [comment]
• What is the purpose of this token? How will it benefit Trust Wallet users?
 • How is the token being distributed? Are you conducting an airdrop?
 • Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?
 • Is the token listed on a centralized/decentralized exchange?
 • Is a Smart Contract audit completed? Where can we find this information?

**Comment by blockartist** [comment]
* Its a meme token and soon start own swap platform
* Airdrop distributed to 2500+ users. And thosse amounts are very thin
* We sold token via Unicrypt ILO
* Its listed on pancakeswap and liquidity locked for 11 months.
* Smart contract Audit completed. Link: https://github.com/dogekingbsc/assets/blob/master/audit/SmartContract_Audit_Solidproof_DogeKing.pdf

**Comment by blockartist** [comment]
And Audit+KYC post link from vendor: https://t.me/solidproof/273

**Pull request merged**
