### PR TITLE
[Please remove the LOGO and all information on the old contract]

### PR DESCRIPTION
**Pull request by Satoshiisgod**
[Please remove the LOGO and all information on the old contract]
[Please remove the LOGO and all information on the old contract]
[Please remove the LOGO and all information on the old contract]
[Please remove the LOGO and all information on the old contract]
[Please remove the LOGO and all information on the old contract]
[Please remove the LOGO and all information on the old contract]

New AIR contract(active):
0xd8a2ae43fd061d24acd538e3866ffc2c05151b53

Old AIR contract(disableed):
0xa123ab52a32267dc357b7599739d3c6caf856fe4

Hello TrustWallet team,

Some bad whale holders have bought more than 500 trillion old AIR with an illegal robot at a low price, but they don’t want to do anything to promote the AIR project but sell to earn from AIR.

Whenever the old AIR price is pumping, those bad whale holders sell their old AIR.

The whole community can not bear them, so we created a new AIR to fight with those bad whale holders and we win.

The community will send new AIR to all of you, except those bad whale holders.

Immigration announcement(Community ):
https://aircoin.community/t/announcement-clarification-of-the-air-migration-att20210907-009/304

Immigration announcement(Twitter ):
https://twitter.com/Aircoinreal/status/1435037688625655808?s=20

Immigration announcement(Facebook ):
https://www.facebook.com/aircoinreal/posts/132963332378642

Immigration announcement(Linkedin ):
https://www.linkedin.com/posts/aircoin_announcementclarification-of-the-air-migration-activity-6840808921343553536-wJKH

New AIR contract(active):
0xd8a2ae43fd061d24acd538e3866ffc2c05151b53

Old contract(disableed):
0xa123ab52a32267dc357b7599739d3c6caf856fe4

The new AIR contract retains the LOGO, official Website, Twitter, Facebook, Linkedin, and all social media.

Please remove the LOGO and all information on the old contract.

### CODE REVIEW

**Comment by Cryptocool1** [comment]
please change the status for your old token from "active" to "abandoned"

**Comment by Satoshiisgod** [comment]
OK, I have  changed the status for old token from "active" to "abandoned"

**Comment by Cryptocool1** [comment]
We are not able to edit and delete files in the submission. 
 please re-submit the PR with an updated fork.

**Comment by Satoshiisgod** [comment]
> We are not able to edit and delete files in the submission.
> please re-submit the PR with an updated fork.

Hello, you mean I should 

> We are not able to edit and delete files in the submission.
> please re-submit the PR with an updated fork.

Hello, 
1)Do you mean that I should close this PR and then re-submit a new PR with an updated fork?

2) If so, do I need to pay another 5 BNB?

3)Should  I add the new AIR token info and change the old AIR token status to abandoned in one PR?

**Comment by Satoshiisgod** [comment]
Hello Cryptocool1, 

1)Do you mean that I should close this PR and then re-submit a new PR with an updated fork?

2) If so, do I need to pay another 5 BNB?

3)Should  I add the new AIR token info and change the old AIR token status to abandoned in one PR?

**Comment by Satoshiisgod** [comment]
Hello Cryptocool1,

1) Do you mean that I should close this PR and then re-submit a new PR with an updated fork?

2) If so, do I need to pay another 5 BNB?
3) Should I add the new AIR token info and change the old AIR token status to abandoned in one PR?

**Comment by Cryptocool1** [comment]
1yes
2 no, you don’t need to pay one more time
3yes

**Comment by Satoshiisgod** [comment]
> 1yes
> 2 no, you don’t need to pay one more time
> 3yes

Thanks Cryptocool1

**Pull request closed without merging**
