### PR TITLE
Upgrade Floki Contracts

### PR DESCRIPTION
**Pull request by EagleFloki**
Floki contracts has been upgraded and has new contracts.
Check below: 
https://twitter.com/RealFlokiInu/status/1485298553757089801

### CODE REVIEW

**Comment by EagleFloki** [comment]
logo
Could you update the logo too?

**Review by EagleFloki — COMMENTED** [review]
deleted reddit link

**Comment by EagleFloki** [comment]
Floki has 342,729 holders on Binance Smart Chain.
Proof: https://bscscan.com/token/0xfb5b838b6cfeedc2873ab27866079ac55363d37e

**Comment by EagleFloki** [comment]
Floki contract has been updated
Proof: https://twitter.com/RealFlokiInu/status/1485298553757089801

Please update the ETH info, logo and add new BSC contract.

**Comment by cryptomanz** [comment]
Submission looks good. awaiting fee payment.

**Pull request closed without merging**
