### PR TITLE
Add logo to TRUSTWALLET

### PR DESCRIPTION
**Pull request by anonjay**
0xa7ab17fe18fe2ef1b211b95be0d3b3a121823758

### CODE REVIEW

**Comment by anonjay** [comment]
@kolya182 @zachzwei what does the X means? Do I still have to do something or you are going to fix it on your end?

https://github.com/trustwallet/assets/pull/2428/commits/8abe070c60379ac4e2fbf5ff5d917e6461dab565

**Comment by coffee-converter** [comment]
> @kolya182 @zachzwei what does the X means? Do I still have to do something or you are going to fix it on your end?
> 
> [8abe070](https://github.com/trustwallet/assets/commit/8abe070c60379ac4e2fbf5ff5d917e6461dab565)

You need to use the checksummed ETH address as the directory name.

**Comment by anonjay** [comment]
> > @kolya182 @zachzwei what does the X means? Do I still have to do something or you are going to fix it on your end?
> > [8abe070](https://github.com/trustwallet/assets/commit/8abe070c60379ac4e2fbf5ff5d917e6461dab565)
> 
> You need to use the checksummed ETH address as the directory name.

How can I do that? I aint technical.

**Comment by coffee-converter** [comment]
> > > @kolya182 @zachzwei what does the X means? Do I still have to do something or you are going to fix it on your end?
> > > [8abe070](https://github.com/trustwallet/assets/commit/8abe070c60379ac4e2fbf5ff5d917e6461dab565)
> > 
> > 
> > You need to use the checksummed ETH address as the directory name.
> 
> How can I do that? I aint technical.

https://github.com/trustwallet/assets#repository-structure

**Comment by anonjay** [comment]
> > > > @kolya182 @zachzwei what does the X means? Do I still have to do something or you are going to fix it on your end?
> > > > [8abe070](https://github.com/trustwallet/assets/commit/8abe070c60379ac4e2fbf5ff5d917e6461dab565)
> > > 
> > > 
> > > You need to use the checksummed ETH address as the directory name.
> > 
> > 
> > How can I do that? I aint technical.
> 
> https://github.com/trustwallet/assets#repository-structure

Can I just open a new pull request without paying again?

**Comment by anonjay** [comment]
> > > > > @kolya182 @zachzwei what does the X means? Do I still have to do something or you are going to fix it on your end?
> > > > > [8abe070](https://github.com/trustwallet/assets/commit/8abe070c60379ac4e2fbf5ff5d917e6461dab565)
> > > > 
> > > > 
> > > > You need to use the checksummed ETH address as the directory name.
> > > 
> > > 
> > > How can I do that? I aint technical.
> > 
> > 
> > https://github.com/trustwallet/assets#repository-structure
> 
> Can I just open a new pull request without paying again?

Can you check this one.

https://github.com/trustwallet/assets/commit/4c4907b0a1273340103aeccf82370e701f3c3d44

**Comment by coffee-converter** [comment]
> > > > > > @kolya182 @zachzwei what does the X means? Do I still have to do something or you are going to fix it on your end?
> > > > > > [8abe070](https://github.com/trustwallet/assets/commit/8abe070c60379ac4e2fbf5ff5d917e6461dab565)
> > > > > 
> > > > > 
> > > > > You need to use the checksummed ETH address as the directory name.
> > > > 
> > > > 
> > > > How can I do that? I aint technical.
> > > 
> > > 
> > > https://github.com/trustwallet/assets#repository-structure
> > 
> > 
> > Can I just open a new pull request without paying again?
> 
> Can you check this one.
> 
> [4c4907b](https://github.com/trustwallet/assets/commit/4c4907b0a1273340103aeccf82370e701f3c3d44)

Same error, the eth address isn't checksummed.

**Comment by anonjay** [comment]
@coffee-converter I opened a new PR because I'm getting confused.

https://github.com/trustwallet/assets/pull/2430

**Comment by zachzwei** [comment]
Closing this one. User submitted new PR #2430

**Pull request closed without merging**
