### PR TITLE
Add Million (MM) token to smartchain list

### PR DESCRIPTION
**Pull request by dafzthomas**

### CODE REVIEW

**Comment by Cryptocool1** [comment]
As per our policy, brand new tokens are not included, there is a minimum requirement of 5000 holder addresses and 10000 transactions, in order to filter out scam tokens.
See the criteria at (mentioned in the first message by the bot): https://community.trustwallet.com/t/how-to-submit-a-token-logo/3863).
Closing PR for now. Please come back to us when all criteria are met.

**Comment by dafzthomas** [comment]
@Cryptocool1 What's the policy with token's that are already in Trust Wallet but on a different chain? Million (MM) token is currenty in Trust Wallet as an ERC20 token. There is an official bridge to the BEP20 equivalent (this PR's token). You can find the ERC20 Million token here: https://github.com/trustwallet/assets/blob/master/blockchains/ethereum/assets/0x6B4c7A5e3f0B99FCD83e9c089BDDD6c7FCe5c611/info.json 

You can even verify this PR's token's contract address against the official website in the ERC20 token's info.json.

**Comment by Cryptocool1** [comment]
> @Cryptocool1 What's the policy with token's that are already in Trust Wallet but on a different chain? Million (MM) token is currenty in Trust Wallet as an ERC20 token. There is an official bridge to the BEP20 equivalent (this PR's token). You can find the ERC20 Million token here: https://github.com/trustwallet/assets/blob/master/blockchains/ethereum/assets/0x6B4c7A5e3f0B99FCD83e9c089BDDD6c7FCe5c611/info.json
> 
> You can even verify this PR's token's contract address against the official website in the ERC20 token's info.json.

Sorry, you didn’t mention this

**Comment by Cryptocool1** [comment]
Id field does not match contract, should be 0xBF05279F9Bf1CE69bBFEd670813b7e431142Afa4
please correct

**Comment by Cryptocool1** [comment]
can you please add links to your PR?
example: https://developer.trustwallet.com/add_new_asset#info-json-contents

**Comment by dafzthomas** [comment]
> can you please add links to your PR?
> example: https://developer.trustwallet.com/add_new_asset#info-json-contents

@Cryptocool1 Ok, done that.

**Comment by Cryptocool1** [comment]
awaiting for fee payment

**Review by techleadhd — COMMENTED** [review]
https://discord.com//MillionToken link needs to be corrected, there is a typo

**Comment by dafzthomas** [comment]
@techleadhd Fixed.

**Review by techleadhd — APPROVED** [review]

**Comment by dafzthomas** [comment]
@Cryptocool1 do I need to do anything for the workflows or shall I leave this with you now?

**Comment by ktamas77** [comment]
Follow up PR with more metadata: https://github.com/trustwallet/assets/pull/12356

**Pull request merged**
