### PR TITLE
Adding Dejitaru Tsuka logo

### PR DESCRIPTION
**Pull request by cruelhand**
Adding Dejitaru Tsuka logo

### CODE REVIEW

**Comment by cruelhand** [comment]
says bnb1tqq9llyr3dyjd559dha6z5r5etk3qfwk07m098 address is invalid

**Comment by cryptomanz1** [comment]
As per our policy, brand new tokens are not included, there is a minimum requirement of 10,000 holder addresses and 15,000 transactions, in order to filter out scam tokens.
See the criteria at : https://developer.trustwallet.com/assets/requirements .

**Comment by Cryptocool1** [comment]
Please come back to us once all criteria are met. Make sure you mention this PR in new one so the fee can be reused

**Comment by cruelhand** [comment]
Hello, the Dejitaru TSUKA token now has over 10,000 Holders and a market cap of around  $130M at the moment. Can this PR be completed at this time?

**Comment by Cryptocool1** [comment]
Please create new PR, follow doc https://developer.trustwallet.com/assets/requirements
You may want to try our Assets app in beta; go to https://assets.trustwallet.com, log on with Github, enter contract ID, logo and some additional info, and it will create a PR for you.
See https://developer.trustwallet.com/assets/repository_details

**Comment by Cryptocool1** [comment]
Make sure to mention this PR, so the fee can be reused

**Comment by roymoses07** [comment]
0xcd1ed43127e033C9d770417e4f23B70e52001142

**Pull request closed without merging**
