### PR TITLE
Add Papu Token (BEP20)

### PR DESCRIPTION
**Pull request by paputoken**
Adding info for BEP20 token 'Papu Token'.

PR created by <a href="https://assets.trustwallet.com">TW Assets Management</a>

### CODE REVIEW

**Comment by paputoken** [comment]
I have manually added the holders.

 Best regards.

**Comment by paputoken** [comment]
Hi @cryptomanz1 @Cryptocool1 @natedaiger @hexorx,

Is there any action I need to take? Please let me know.

Best regards and good luck with your work.

**Review by paputoken — COMMENTED** [review]
Hi,

Descr updated.

Regards

**Comment by paputoken** [comment]
• What is the purpose of this token? How will it benefit Trust Wallet users? 

 PapuToken is currently growing its community. The upcoming Papu game aims to bring together the entire gaming community and memecoin enthusiasts. By being listed on Trust Wallet, we will promote the use of Trust Wallet within our community.

• How is the token being distributed? Are you conducting an airdrop? 

No, fair launch on MEXC and Bitmart.


• Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?

No.

 • Is the token listed on a centralized/decentralized exchange?

Yes.Centralized.
MEXC and Bitmart Exchanges

 • Is a Smart Contract audit completed? Where can we find this information?

Yes, you can view it on our Coinmarketcap page here:
https://coinmarketcap.com/currencies/papu-token/

**Comment by Cryptocool1** [comment]
Please share your smart contract audit here

**Comment by paputoken** [comment]
> Please share your smart contract audit here

https://www.cyberscope.io/audits/coin-papu-token

Regards

**Review by paputoken — COMMENTED** [review]
Hi,

We are changed.

**Comment by paputoken** [comment]
Hello,

Do we need to do any other transactions? I wish you good work.

**Review by EarlTZ — COMMENTED** [review]
@paputoken

**Pull request merged**
