### PR TITLE
Add YES WORLD Logo

### PR DESCRIPTION
**Pull request by YesWorld24**
Added logo and other details to Trust wallet for YES WORLD

### CODE REVIEW

**Comment by YesWorld24** [comment]
for some reason, I'm still not seeing the LOGO on Trust Wallet for Yes World. Please advise
________________________________

**Comment by Cryptocool1** [comment]
Please see #21592

**Comment by YesWorld24** [comment]
I'm not a developer but product manager, so please be patient to guide me steps on what needs to be done on my part to bring the logo up for YES WORLD on Trust wallet.
________________________________

**Comment by Cryptocool1** [comment]
You need to answer the questions on another PR you created. I sent the number of this PR above.

**Comment by YesWorld24** [comment]
I thought it was already done on this current PR, that's why I abandoned that and switched to original account through which It was done in the past.   I'm trying to avoid any duplicate. Please check if this is already done, then other PR is redundant and we can delete that or something.
________________________________

**Comment by Cryptocool1** [comment]
This PR already closed. You need to go on the PR I sent above.

**Comment by YesWorld24** [comment]
@Cryptocool1 I have updated the ticket with the audit report, please advise next steps on this .

https://github.com/cyberscope-io/audits/blob/main/yes/audit.pdf

**Comment by YesWorld24** [comment]
I just provided the required answers in the comments.
________________________________

**Pull request closed without merging**
