### PR TITLE
Add Rootkit (ROOT) Token Logo and Info 

### PR DESCRIPTION
**Pull request by 0xkv**
This PR is being closed due to inactivity. If you wish to continue, please have us reopen the PR before sending your payment.
Do NOT send payments for closed PR, as the fee may by lost!
  (320 vs. 60 hrs)

### CODE REVIEW

**Comment by 0xkv** [comment]
Hi, the bot has auto-closed the PR again. Please reopen so we can make the fee payment

**Comment by 0xkv** [comment]
cc @Iamdeadlyz @vikmeup @catenocrypt for visibility

**Comment by vikmeup** [comment]
It might be better if you just open new pull request

**Comment by 0xkv** [comment]
Ok will do that now

**Comment by catenocrypt** [comment]
Don't worry, if the PR is auto-closed, and you make payment, write a comment.  The payment will be picked up automatically when PR is reopened.

**Comment by catenocrypt** [comment]
Don't pay the fee, the PR will not be merged now, token does not satisfy our minimum circulation requirement.  There is a minimum requirement of 2500 holder addresses and 5000 transactions, in order to filter out scam tokens.
See the criteria at (mentioned in the first message by the bot): https://community.trustwallet.com/t/how-to-submit-a-token-logo/3863).

**Pull request closed without merging**
