### PR TITLE
Please add these Tokens on Trust Wallet

### PR DESCRIPTION
**Pull request by ghost**

### CODE REVIEW

**Comment by SaAtHi1** [comment]
https://explorer.binance.org/tx/654060E7EA3F9C8A6E3B6C28B1B96E1A186EFBD93AEFC9C614578B775B106F71

**Comment by SaAtHi1** [comment]
@kolya182 

Please do it fast sir

**Comment by CMTtoken** [comment]
Can you help me to add my token's logo on Trust. Telegram: @CMT_CEO

**Comment by SaAtHi1** [comment]
@kolya182

Please do it fast sir

**Comment by CMTtoken** [comment]
I've followed you on Github

**Pull request merged**
