### PR TITLE
Add Orion (BEP20)

### PR DESCRIPTION
**Pull request by lovetrading10**
Adding info for BEP20 token 'Orion'.

PR created by <a href="https://assets.trustwallet.com">TW Assets Management</a>

### CODE REVIEW

**Comment by lovetrading10** [comment]
hi @Cryptocool1.
How are you doing?
Can you inform me what's wrong with my pull request?
For completing this, what do I have to do?
Thanks.

**Comment by lovetrading10** [comment]
I can't see "All checks have passed" message.

**Comment by lovetrading10** [comment]
Please reopen

**Comment by Cryptocool1** [comment]
> Please reopen

? 
your PR merged

**Comment by lovetrading10** [comment]
So Is my token added to trust wallet now?

**Comment by lovetrading10** [comment]
I can't see "All checks have passed" message.

**Comment by lovetrading10** [comment]
image

**Comment by lovetrading10** [comment]
what's wrong with this?

**Comment by Cryptocool1** [comment]
> what's wrong with this?

nothing wrong with this PR. It merged, can you see?

**Comment by lovetrading10** [comment]
ok. thanks.

**Pull request merged**
