### PR TITLE
Add Defina Token (BEP20)

### PR DESCRIPTION
**Pull request by HeliusDefina**
Adding info for BEP20 token 'Defina Token'.

PR created by <a href="https://assets.trustwallet.com">TW Assets Management</a>

### CODE REVIEW

**Comment by HeliusDefina** [comment]
> This PR is being closed due to inactivity. If you wish to continue, please have us reopen the PR before sending your payment, or just create a new one. Do NOT send payments for closed PR, as the fee may by lost!

Hey, we want to open this PR again.

**Comment by HeliusDefina** [comment]
@cryptomanz Hey, Is it possible to open this PR again? thanks in advance.

**Comment by HeliusDefina** [comment]
Hey is it possible to open this PR again? thanks in advance
@Iamdeadlyz
@Cryptocool1

**Comment by HeliusDefina** [comment]
I'm Helius from Defina team, please open this PR so we can pay:
@cryptomanz
@Iamdeadlyz
@Cryptocool1

**Comment by HeliusDefina** [comment]
`make check`

**Comment by cryptomanz** [comment]
• What is the purpose of this token? How will it benefit Trust Wallet users?
 • How is the token being distributed? Are you conducting an airdrop?
 • Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?
 • Is the token listed on a centralized/decentralized exchange?
 • Is a Smart Contract audit completed? Where can we find this information?

**Comment by HeliusDefina** [comment]
> • What is the purpose of this token? How will it benefit Trust Wallet users? • How is the token being distributed? Are you conducting an airdrop? • Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale? • Is the token listed on a centralized/decentralized exchange? • Is a Smart Contract audit completed? Where can we find this information?

• What is the purpose of this token? How will it benefit Trust Wallet users?

**$FINA is BEP-20 governance and utility token for the Defina Metaverse ecosystem. There are multiple use cases for $FINA and it plays a very important role in both gaming and community governance.**
The following uses $FINA as a currency in the Defina Metaverse Ecosystem:

1. Buying Mystery Boxes to mint your own heroes.
2. Buying and Selling Hero NFTs in the secondary marketplace.
3. Purchasing in-game assets such as consumables (Breakthrough Potions, Rebirth Crystals, Stamina Potions). 
4. Enhancing heroes by using Rebirth and Resonance.
5. Staking in the PVP Mining Pools to increase yield.

• How is the token being distributed?

**Token Ticker: FINA
Contract Address: 0x426c72701833fddbdfc06c944737c6031645c708
Total Supply: 100,000,000 FINA**

- Seed - 10,000,000 - 10%
- Private - 12,500,000 - 12.5%
- IDO - 1,250,000 - 1.25%
- Marketing - 4,750,000 - 4.75%
- Team - 10,000,000 - 10%
- Liquidity - 5,000,000 - 5%
- Community Rewards - 6,500,000 - 6.5%
- Yield Farming + Play to Earn - 50,000,000 - 50%

• Are you conducting an airdrop?

**As of now we have no plans for an Airdrop.**

• Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?

**Yes, the sale is already finished on October 2021 on Seedify:**

Private Sale
Private Round Date: October 8
Allocation: $300K (incl.%5 success fee)
Private Round Price: $0.20
Private IGO Round Vesting: 10% at TGE, then 10% Monthly for 9 months

IGO
IGO Date: October 11
Allocation: $300K (incl.%5 success fee)
IGO Price: $0.40
Vesting: 50% at TGE, then 50% in 1 Month.

• Is the token listed on a centralized/decentralized exchange?

**Decentralized:**
FINA/BUSD and FINA/BNB pairs are listed on Pancakeswap.

**Centralized**
FINA/USDT pair is listed on MXC, BitMart, Bitrue, BKEX and Hotbit.

• Is a Smart Contract audit completed? Where can we find this information?

**Our team takes security with the upmost importance. Our smart contracts will be audited by multiple third party organisations. 
Below are our current audits completed to date:**

https://github.com/Defina-Finance/contracts-and-audits/blob/main/Smart%20Contract%20Audit%20Report%20for%20Defina.Finance%2020211015.pdf

**Pull request merged**
