### PR TITLE
Add HAMTARO (BEP20)

### PR DESCRIPTION
**Pull request by HamtaroBSC**
Adding info for BEP20 token 'HAMTARO'.

PR created by <a href="https://assets.trustwallet.com">TW Assets Management</a>

### CODE REVIEW

**Comment by HamtaroBSC** [comment]
Already Payed PR:

Add Logo for Hamtaro #8192

Il giorno lun 17 mag 2021 alle ore 08:46 merge-fee-bot[bot] <
***@***.***> ha scritto:

**Comment by HamtaroBSC** [comment]
Can you help me? Why checks don't work?

**Comment by Cryptocool1** [comment]
PR should include only 2 files

**Comment by HamtaroBSC** [comment]
Yes i need to add only the logo on TW

Il giorno mar 18 mag 2021 alle 20:58 CryptoA ***@***.***> ha
scritto:

**Comment by HamtaroBSC** [comment]
Update please

Il giorno mar 18 mag 2021 alle 21:10 Hamtaro BSC ***@***.***> ha
scritto:

**Comment by HamtaroBSC** [comment]
Now it’s ok?

Il giorno gio 20 mag 2021 alle 12:11 merge-fee-bot[bot] <
***@***.***> ha scritto:

**Comment by Cryptocool1** [comment]
Correction needed:
Contract is not in checksum format, should be 0x4d4CC29b9C4E413CFe5f898E16280f11db57E186

**Comment by HamtaroBSC** [comment]
0x4d4CC29b9C4E413CFe5f898E16280f11db57E186 it's.

**Comment by HamtaroBSC** [comment]
Can you help with workflows guys?

**Pull request merged**
