### PR TITLE
create egyptoken.com.png

### PR DESCRIPTION
**Pull request by EGPTEX**

### CODE REVIEW

**Comment by EGYPTOKEN** [comment]
I created this Pull to add my Dapp and EGPT token logo to trustwallet. Is that righ?
Contract : 0xDa3Bd278a39AE57439eE26B361118173bC70f21F

**Comment by EGYPTOKEN** [comment]
Payment send : 
https://explorer.binance.org/tx/33569CF766EFBB6799934AA4B22793EABBDB0E6AA11F4D5BAE9B0CF579B63266

**Comment by EGPTEX** [comment]
Hello

Please, we have updated our project data 
Please update it with you too
thank you

project name : from EGYPTOKEN to EGPTEX and it updated from etherscan.io

https://etherscan.io/token/0xda3bd278a39ae57439ee26b361118173bc70f21f

The contract and symbol are unchanged.

new LOGO : [https://drive.google.com/file/d/1Qhd_RIE_38Q4Z50lnVS10XOqB5kL2x9A/view?usp=sharing
]
Website : https://egptex.com

Community :-

----------------

twitter:     https://twitter.com/egptex

facebook:  https://www.facebook.com/EGPTEX

Telegram: https://t.me/EGPTEX

github:     https://github.com/EGPTEX?tab=repositories

linkedin:   https://www.linkedin.com/company/egpt

Thank you, we apologize for the inconvenience

**Comment by catenocrypt** [comment]
@EGPTEX , you need to create a PR with the changed files, and note that there is also a small fee to be paid for each PR.

**Pull request merged**
