### PR TITLE
Add COR (Coreto) Token

### PR DESCRIPTION
**Pull request by balaianu**
- add info.json
- add logo.png

### CODE REVIEW

**Comment by balaianu** [comment]
> 
> 
> @balaianu, kind reminder: please pay fee: **1000 TWT** with the memo **4688** to the address `bnb1tqq9llyr3dyjd559dha6z5r5etk3qfwk07m098`.
> Alternatively, 6 BNB is also accepted (same memo & address).
> 
> **QR** code: [Trust](https://api.qrserver.com/v1/create-qr-code/?size=200x200&data=https%3A%2F%2Flink.trustwallet.com%2Fsend%3Fcoin%3D714%26address%3Dbnb1tqq9llyr3dyjd559dha6z5r5etk3qfwk07m098%26amount%3D1000%26memo%3D4688) | [other wallet](https://api.qrserver.com/v1/create-qr-code/?size=200x200&data=bnb1tqq9llyr3dyjd559dha6z5r5etk3qfwk07m098%26amount%3D1000%26memo%3D4688)
> See the [Pull Request Fee FAQ](https://developer.trustwallet.com/add_new_asset/pr-fee).

Will check, thank you.

**Comment by catenocrypt** [comment]
Json file is invalid, last explorer line has an trailing comma which should not be there.  Please fix.

**Comment by catenocrypt** [comment]
Next (and hopefully last issue): folder name should be in 'checksum' format.  Please rename.

```
git mv blockchains/ethereum/assets/0x9c2dc0c3cc2badde84b0025cf4df1c5af288d835 blockchains/ethereum/assets/0x9c2dc0c3cc2badde84b0025cf4df1c5af288d835-2
git mv blockchains/ethereum/assets/0x9c2dc0c3cc2badde84b0025cf4df1c5af288d835-2 blockchains/ethereum/assets/0x9C2dc0c3CC2BADdE84B0025Cf4df1c5aF288D835
```

**Review by vudu0602 — APPROVED** [review]

**Comment by Iamdeadlyz** [comment]
As per our policy, brand new tokens are not included. There is a minimum requirement of 2500 holder addresses and 5000 transactions (airdropped tokens excluded) in order to filter out scam tokens. See the criteria at (mentioned in the first message by the bot): https://community.trustwallet.com/t/how-to-submit-a-token-logo/3863#how-to-get-approved

This token has below-limit usage yet. This pull request will be put on hold. Please come back to us when all criteria are met.
https://etherscan.io/token/0x9c2dc0c3cc2badde84b0025cf4df1c5af288d835 (502, 2474)

**Comment by catenocrypt** [comment]
Accepting circulation (using criteria from creation of PR)  :)

**Comment by catenocrypt** [comment]
@vudu0602 , please stop trolling in other PRs, else we need to block you.

**Pull request merged**
