### PR TITLE
Add Moonlight Token (BEP20)

### PR DESCRIPTION
**Pull request by Moonlighttoken**
Adding info for BEP20 token 'Moonlight Token'.

PR created by <a href="https://assets.trustwallet.com">TW Assets Management</a>

### CODE REVIEW

**Comment by Moonlighttoken** [comment]
ALREADY PAID

**Comment by Cryptocool1** [comment]
#7504 PAID

**Comment by Cryptocool1** [comment]
PR should include only 2 files:
blockchains/smartchain/assets/0x42282fBbef486cf9eaf00cb3030810310F614568/logo.png
blockchains/smartchain/assets/0xB1CeD2e320E3f4C8e3511B1DC59203303493F382/info.json

**Comment by Moonlighttoken** [comment]
logo

**Comment by Moonlighttoken** [comment]
https://github.com/Moonlighttoken/assets/blob/16569274f2107c0da3bb9a8669c3ca231f664765/blockchains/smartchain/assets/0xB1CeD2e320E3f4C8e3511B1DC59203303493F382/logo.png

**Comment by Moonlighttoken** [comment]
blockchains/smartchain/assets/0xB1CeD2e320E3f4C8e3511B1DC59203303493F382/info.json
blockchains/smartchain/assets/0xB1CeD2e320E3f4C8e3511B1DC59203303493F382/logo.png


Thanks a lot for your help, normally it's ok

**Comment by Moonlighttoken** [comment]
https://github.com/Moonlighttoken/assets/blob/16569274f2107c0da3bb9a8669c3ca231f664765/blockchains/smartchain/assets/0xB1CeD2e320E3f4C8e3511B1DC59203303493F382/info.json

**Comment by Moonlighttoken** [comment]
I can't delete in PR, how can we proceed to keep only 2 ?

**Comment by catenocrypt** [comment]
It says JSON is invalid, at first character, but I don't see nothing wrong either.  I saw similar error when file had some differetn character encoding, not plain text nor utf.

**Comment by catenocrypt** [comment]
Yes, this file starts with 3 non-printable characters

```
od -t c blockchains/smartchain/assets/0xB1CeD2e320E3f4C8e3511B1DC59203303493F382/info.json
0000000  357 273 277   {  \r  \n                   "   n   a   m   e   "
0000020    :       "   M   o   o   n   l   i   g   h   t       T   o   k
```

**Comment by catenocrypt** [comment]
Fixed it by copy-pasting to a new file

image

**Pull request merged**
