### PR TITLE
Add Snake (BEP20)

### PR DESCRIPTION
**Pull request by bnb425**
Adding info for BEP20 token 'Snake'.

PR created by <a href="https://assets.trustwallet.com">TW Assets Management</a>

### CODE REVIEW

**Comment by bnb425** [comment]
I have already paid for the application, they told me that I need to do an audit and then they will review the application again, do I need to pay again?

**Comment by bnb425** [comment]
scr

**Comment by bnb425** [comment]
@Cryptocool1 pls help me

**Comment by Cryptocool1** [comment]
Hello, please check your explorer link, seems like it’s not working.
IMG_5963

**Comment by bnb425** [comment]
> Hello, please check your explorer link, seems like it’s not working. !

Sorry @Cryptocool1 , I didn't quite understand what link you were talking about, so I'm sending all the links

Website: https://snake.homes/
Explorer: https://bscscan.com/token/0x34980c35353a8d7b1a1ba02e02e387a8383e004a
Twitter: https://x.com/BNB_SNAKE
Telegram: https://t.me/BNBSnake_chat
CoinGecko: https://www.coingecko.com/en/coins/snake-2
CoinMarketCap: https://coinmarketcap.com/currencies/snake-homes/
Whitepaper: https://wpp.snake.homes/
Audit Cyberscope : https://www.cyberscope.io/audits/2-snk

**Pull request merged**
