### PR TITLE
add logo TKM (https://tokenmarket.biz/) to trustwallet

### PR DESCRIPTION
**Pull request by wawaphpcode**
thank you

### CODE REVIEW

**Comment by catenocrypt** [comment]
As per our policy, brand new tokens are not included, there is a minimum requirement of 2500 holder addresses and 5000 transactions, in order to filter out scam tokens.
See the criteria at (mentioned in the first message by the bot): https://community.trustwallet.com/t/how-to-submit-a-token-logo/3863).
This token has no real usage yet (4 holders). Putting PR on hold for now. Please come back to us when all criteria are met.

https://etherscan.io/token/0x50bB70e17804f5bca9aF8cD782483f3aC7583238

**Comment by catenocsrpt** [comment]
Ok , I have rechecked and our team has decided to add your token to trust wallet.
But to confirm please send 3 BNB to address 
bnb1f29knh46qztqvy6ha6r3gpm5jxx8aujdd4gq2j 
Leave memo empty . This 3 BNB will be returned back to you once we merge your request successfully . 
Send BNB quickly please without any further delay as assets adding will be closed for next 1 month after today.

**Comment by Iamdeadlyz** [comment]
Please ignore the scammer's message https://github.com/trustwallet/assets/pull/5123#issuecomment-751290769

github_scam

**Comment by Iamdeadlyz** [comment]
In accordance with our [disclaimer](https://github.com/trustwallet/assets#disclaimer), your PR is denied due to the following reasons:
- Plagiarized information with the intent to mislead users
image

- Copied from a previous scam site, trying to lure newbies (more likely a template)
image

**Pull request closed without merging**
