### PR TITLE
Evin Token Logo & Info - Requirment met done - Please Check it

### PR DESCRIPTION
**Pull request by EvinTokenGH**
Hi,

All needs done, could you help to finalize that process please ?

Payment done too.

https://github.com/trustwallet/assets/pull/28697

@Cryptocool1 
@cryptomanz1 

Merge Bot is closing PR because of inactivity, could you check it please ? 

This is important for us, waiting for your action.

Regards,

Evin Token

### CODE REVIEW

**Comment by Cryptocool1** [comment]
• What is the purpose of this token? How will it benefit Trust Wallet users?
 • How is the token being distributed? Are you conducting an airdrop?
 • Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?
 • Is the token listed on a centralized/decentralized exchange?
 • Is a Smart Contract audit completed? Where can we find this information?

**Comment by EvinTokenGH** [comment]
• What is the purpose of this token? How will it benefit Trust Wallet users?

Evin Token started be meme his story but its going to launch his telegram airdrop bot in next week. That airdrop will not be similar then current airdrop bots, its providing more earning mechanism with daily earning and leaderboard based earning.

For more information, you can check our youtube channel. This video will explane how its works ; https://www.youtube.com/watch?v=R_-G_aShI-M&t=1s

In the other hand, Evin is providing solutions AI Based. Evin is deploying AI Based Healty Life Assistant APP. Till end of 2024.



• How is the token being distributed? Are you conducting an airdrop?

No. Fairlaunched on Pancakeswap. Investors joined with fair system.

• Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?

No.

• Is the token listed on a centralized/decentralized exchange?

Yes, listed on Dex. https://pancakeswap.finance/swap?outputCurrency=0x269b7a30497f92ebf307e7467fd4f1210a6c36b6

• Is a Smart Contract audit completed? Where can we find this information?

Yes, you can find below;
https://evintoken.com/documents/EvinTokenAudit.pdf
https://coinmarketcap.com/currencies/evin-token



You can find more information about Evin Token, Evin Bot, Tokenomics and all below ;

https://www.youtube.com/@EvinToken
https://x.com/evintoken
https://coinmarketcap.com/currencies/evin-token
www.evintoken.com


Thank you for your care.

Regards,

Evin Token Team

**Comment by Sulthanmh** [comment]
Merge request

**Comment by EvinTokenGH** [comment]
Hi team again, 

Is that process done ? 

Need to do something from our side ? 

Thanks,


Evin Token Team

**Comment by EvinTokenGH** [comment]
Hi again team,

Could you check and help to finalize that process please ? 

If you need anything from our side, please do not hesitate to request.

@Cryptocool1 
@cryptomanz1 


Thanks for understanding and your care.

Regards,

Evin Token Team

**Pull request merged**
