### PR TITLE
Please add Catnero token

### PR DESCRIPTION
**Pull request by Catnero**

### CODE REVIEW

**Comment by Annasadra** [comment]
"Please add Catnero token":
"into Trust Wallet":
"address":{
"catnero": "0x3793014Fd9eDEd2e2F4f7F67210F2b7c38A62a4E"
                }
              }
           }

**Comment by Annasadra** [comment]
"Token name":
"contract address":{
"catnero":"0x82d5683f6d32d19b3b34fcfbc7041f43a3faf228"

**Comment by Annasadra** [comment]
"Token name":
"Contract address":{
"catnero": "0x82d5683f6d32d19b3b34fcfbc7041f43a3faf228"
            }
         }
      }

**Comment by Annasadra** [comment]
"Please add token":
"into Trust Wallet":
"Contract address":{
"Catnero"" : " 0x82d5683f6d32d19b3b34fcfbc7041f43a3faf228"
             }
          }
        }

**Comment by Catnero** [comment]
where do you want to put it?

Pada tanggal Sel, 7 Apr 2020 22.11, Hanna Samoilova <
notifications@github.com> menulis:

**Pull request merged**
