### PR TITLE
Add UDOGE - BEP20 Token Logo, Info

### PR DESCRIPTION
**Pull request by vanphuc079**
First add token logo and info (BEP20)

### CODE REVIEW

**Comment by cryptomanz** [comment]
• What is the purpose of this token? How will it benefit Trust Wallet users?
 • How is the token being distributed? Are you conducting an airdrop?
 • Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?
 • Is the token listed on a centralized/decentralized exchange?
 • Is a Smart Contract audit completed? Where can we find this information?

**Comment by vanphuc079** [comment]
• What is the purpose of this token? How will it benefit Trust Wallet users?
UDOGE is the Metaverse Game Fi to help people have playing skill to earn token for free, other invester intested in game finance can easy to invest and managing UDOGE asset in Trust Wallet - expecially is our over 10k holder now!

• How is the token being distributed? Are you conducting an airdrop?
We do 2 action untill now: (1) public sale on PancakeSwap and get over 5000 holder at the begining, (2) airdrop for nearly 7000 people follow our airdop event!

• Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?
NO!

• Is the token listed on a centralized/decentralized exchange?
Yes PancakeSwap decentralized exchange.

• Is a Smart Contract audit completed? Where can we find this information?
YES! https://github.com/ukadogecoin/udoge_coin/blob/main/UKA_DOGE_COIN_0x698111b771363B81D1179AD102e3d8B9cD093a11.pdf

**Comment by cryptomanz** [comment]
cannot open your audit, please send another link.

**Comment by vanphuc079** [comment]
> cannot open your audit, please send another link.
New link: https://ukadoge.com/UKA_DOGE_COIN_0x698111b771363B81D1179AD102e3d8B9cD093a11.pdf
Thanks so much!

**Comment by cryptomanz** [comment]
we require smart contract from reputable companies, such as: Certik, Techrate, Hacken, Dessert Finance.
On hold for now.

**Review by HauExistential — APPROVED** [review]

**Comment by Cryptocool1** [comment]
Please come bak to us when all criteria are met. Make sure to mention this PR so the fee can be reused

**Pull request closed without merging**
