### PR TITLE
Add ELONBALLS (BEP20)

### PR DESCRIPTION
**Pull request by Blietje**
Adding info for BEP20 token 'ELONBALLS'.

PR created by <a href="https://assets.trustwallet.com">TW Assets Management</a>

### CODE REVIEW

**Comment by Cryptocool1** [comment]
• What is the purpose of this token? How will it benefit Trust Wallet users?
 • How is the token being distributed? Are you conducting an airdrop?
 • Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?
 • Is the token listed on a centralized/decentralized exchange?
 • Is a Smart Contract audit completed? Where can we find this information?

**Comment by Blietje** [comment]
• What is the purpose of this token? How will it benefit Trust Wallet users? Elonballs is the official BEP20 token of the Pokelon Project, which parodies wildly popular trends in DeFi and Gaming culture and brings them to life as an interactive, NFT Collectible Card Game which is in OPEN BETA now. Holders have access to a wide variety of NFTs and can trade and battle all of these lovable creatures in a Telegram based RPG battler, earn free NFTs in daily giveaways and evolve them to make them stronger! • How is the token being distributed? Are you conducting an airdrop? The token is already live trading on poocoin. We did a dxsale presale. • Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?Token presale via dxsale • Is the token listed on a centralized/decentralized exchange?Only poocoin, but we’re expecting two exchanges this month. • Is a Smart Contract audit completed? Where can we find this information?No. Certik audit is requested but that could take up to two months. Regards,Neal Sent from Mail for Windows From: CryptoASent: Wednesday, November 10, 2021 2:02 PMTo: trustwallet/assetsCc: Blietje; AuthorSubject: Re: [trustwallet/assets] Add ELONBALLS (BEP20) (PR #15401) • What is the purpose of this token? How will it benefit Trust Wallet users?• How is the token being distributed? Are you conducting an airdrop?• Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?• Is the token listed on a centralized/decentralized exchange?• Is a Smart Contract audit completed? Where can we find this information?—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by Cryptocool1** [comment]
awaiting for smart contract audit, on hold for now

**Comment by Blietje** [comment]
Do we need to have an audit? Or are you auditing it?

**Comment by Blietje** [comment]
> awaiting for smart contract audit, on hold for now

Do we need to have an audit? Or are you auditing it?

**Comment by Cryptocool1** [comment]
we are not auditing. you should contact with tech rate, certic, etc.

**Comment by Cryptocool1** [comment]
Please come back to us when all criteria are met.
When creating a new PR make sure to mention this PR, so that we can see that fee has been paid already here.

**Comment by Blietje** [comment]
@Cryptocool1 It was this PR btw. We already paid for it. You changed the requirements of holders which we are unable to meet. I want a refund. This is just theft.

**Comment by Blietje** [comment]
Hello,

I would like to have a refund on this matter as stated above. We applied for a TW logo while the required number of holders was much lower then it is now. Because of the adjustment of the requirements we are unable to get listed on TW. Since between the opening of the PR and the changement of the requirements is a very small gap I would like to get a refund asap. 

Would love to hear from you soon @Cryptocool1 @cryptomanz @zachzwei

**Comment by Cryptocool1** [comment]
Снимок экрана 2021-12-10 в 10 01 02

**Comment by Blietje** [comment]
Yes I know that... And we did! But you changed the policy!!!!!!
This is just theft!!

**Comment by Cryptocool1** [comment]
we did not change the policy for the tokens that had been paid before.
we require smart contract audit from you that's all.

**Pull request closed without merging**
