### PR TITLE
Add LOOT logo and info

### PR DESCRIPTION
**Pull request by mrkawdy2**
Adding NFTLootbox.com (LOOT) token logo and the project info.

### CODE REVIEW

**Comment by mrkawdy2** [comment]
I paid! Please let me know if you need anything else on my end :D

**Comment by Iamdeadlyz** [comment]
As per our policy, brand new tokens are not included. There is a minimum requirement of 2500 holder addresses and 5000 transactions (airdropped tokens excluded) in order to filter out scam tokens. See the criteria at (mentioned in the first message by the bot): https://community.trustwallet.com/t/how-to-submit-a-token-logo/3863#how-to-get-approved

This token has below-limit usage yet. This pull request will be put on hold. Please come back to us when all criteria are met.
https://etherscan.io/token/0x7b3D36Eb606f873A75A6aB68f8c999848B04F935 (79 holders and 118 tx)

**Comment by mrkawdy2** [comment]
Ok well, that's pretty disappointing- so will we have to pay again and upload our logo and info again? Or can we just contact you through the comments here?

**Comment by Iamdeadlyz** [comment]
You can ping me here, no need to pay again.

**Pull request closed without merging**
