### PR TITLE
Add WinsToken (POLYGON)

### PR DESCRIPTION
**Pull request by jtan-sl**
Adding info for POLYGON token 'WinsToken'.

PR created by <a href="https://assets.trustwallet.com">TW Assets Management</a>

### CODE REVIEW

**Comment by Cryptocool1** [comment]
• What is the purpose of this token? How will it benefit Trust Wallet users?
 • How is the token being distributed? Are you conducting an airdrop?
 • Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?
 • Is the token listed on a centralized/decentralized exchange?
 • Is a Smart Contract audit completed? Where can we find this information?

**Comment by jtan-sl** [comment]
> • What is the purpose of this token? How will it benefit Trust Wallet users? 

$WINS is a deflationary rewards token used by Trophy, a mobile gaming loyalty platform.  Trophy aims to onboard mobile gamers onto web3, and we've brought tens of thousands of users on-chain already.  Some Trophy users also use TrustWallet, and we would like to smooth out the UX.

>• How is the token being distributed? Are you conducting an airdrop? 

$WINS tokens are backed by mobile gaming ad revenue.  As users play sponsored mobile games and earn money from mobile game ad networks, that revenue is tokenized as $WINS and distributed to them.  Users are able to earn $WINS through participation, but it is not an "airdrop" in the traditional sense.

>• Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale? 

No. 

>• Is the token listed on a centralized/decentralized exchange? 

Yes, it is on Uniswap DEX (Polygon PoS), and BitMart CEX.

>• Is a Smart Contract audit completed? Where can we find this information?

$WINS doesn't use any custom smart contracts that require auditing.  The token is minted on Ethereum as ERC-20, and is bridged over to Polygon PoS using Portal Bridge.

**Comment by Cryptocool1** [comment]
we require smart contract audit from reputable companies. Here is an example of smart contract audit: https://skynet.certik.com/projects/trust-wallet/security-score

**Comment by jtan-sl** [comment]
> we require smart contract audit from reputable companies. Here is an example of smart contract audit: https://skynet.certik.com/projects/trust-wallet/security-score

WINS contract uses ERC-20 contracts directly from OpenZepplin - WINS token minted on Ethereum is based on OpenZeppelin 4.9. 
https://etherscan.io/token/0x5f48d1Fd6814Cd1CD38Aeb895755E57d519196d1#code
Audit: https://github.com/OpenZeppelin/openzeppelin-contracts/blob/master/audits/2023-05-v4.9.pdf

The WINS token on Polygon PoS uses the Portal Bridge which is also audited.
https://github.com/wormhole-foundation/wormhole-audits/blob/main/2023-03-08_CertiK_Wormhole_EVM.pdf

**Comment by eguan-superlayer** [comment]
Bump.  Any news?

**Comment by eguan-superlayer** [comment]
Bump.  Any news?

**Pull request merged**
