### PR TITLE
Add ASPO World (BEP20)

### PR DESCRIPTION
**Pull request by yenthanh132**
Adding info for BEP20 token 'ASPO World'.

PR created by <a href="https://assets.trustwallet.com">TW Assets Management</a>

### CODE REVIEW

**Comment by yenthanh132** [comment]
Our smart contracts has been audited: https://github.com/phugt/aspoerc20/blob/master/audits/mythx.pdf

**Comment by cryptomanz** [comment]
• What is the purpose of this token? How will it benefit Trust Wallet users?
 • How is the token being distributed? Are you conducting an airdrop?
 • Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?
 • Is the token listed on a centralized/decentralized exchange?
 • Is a Smart Contract audit completed? Where can we find this information?

**Comment by yenthanh132** [comment]
Hi, it has been 24 hours, how long does it take to get this PR merged?

**Comment by ramsty** [comment]
Hi! This smart contract audit isn't acceptable. A full token audit has to be completed by reputable security audit groups.

**Comment by Cryptocool1** [comment]
Please come back to us when all criteria are met.
When creating a new PR make sure to mention this PR, so that we can see that fee has been paid already here.

**Pull request closed without merging**
