### PR TITLE
Please add this Token

### PR DESCRIPTION
**Pull request by Mznrahi786**

### CODE REVIEW

**Comment by Mznrahi786** [comment]
payment pending

**Comment by Mznrahi786** [comment]
@kolya182

Please do ASAP

**Comment by kolya182** [comment]
> @kolya182
> 
> Please do ASAP

Please resolve mere conflicts ASAP

**Comment by Mznrahi786** [comment]
> > @kolya182
> > Please do ASAP
> 
> Please resolve mere conflicts ASAP

I don't know how

**Comment by Mznrahi786** [comment]
> > @kolya182
> > Please do ASAP
> 
> Please resolve mere conflicts ASAP

Please help me.. Im out of delivey time

**Comment by kolya182** [comment]
@Mznrahi786 I have told many, many time already how to proceed with this conflicts. Stop spamming.

**Comment by kolya182** [comment]
@Mznrahi786 As one time exception i added your logo in this commit https://github.com/trustwallet/assets/commit/585111d4045b4089a18a7ff0604026775cbbcf22. For the future, please rebase your fork agains master.

**Comment by Mznrahi786** [comment]
> @Mznrahi786 As one time exception i added your logo in this commit [585111d](https://github.com/trustwallet/assets/commit/585111d4045b4089a18a7ff0604026775cbbcf22). For the future, please rebase your fork agains master.

I really really really don't know how...
Please send me steps, I'll do that

**Comment by kolya182** [comment]
> > @Mznrahi786 As one time exception i added your logo in this commit [585111d](https://github.com/trustwallet/assets/commit/585111d4045b4089a18a7ff0604026775cbbcf22). For the future, please rebase your fork agains master.
> 
> I really really really don't know how...
> Please send me steps, I'll do that

The simplest thing i can advise is to remove your fork(copy of our repository you made) and clone again (forking). This way you will avoid rebasing your fork)

**Pull request closed without merging**
