### PR TITLE
Xend Token

### PR DESCRIPTION
**Pull request by KayAlbertus**
A Global DeFi Platform for Credit Unions and Cooperatives

### CODE REVIEW

**Comment by Cryptocool1** [comment]
can't find contract on your website,
please check/add

**Comment by KayAlbertus** [comment]
Hello team 

Please can you tel me why we do not see logo in trust wallet application yet 



Can you please advise what is still needed ? 

Thank you 
Kind regards

**Comment by cryptomanz** [comment]
As @Cryptocool1 mentioned, you need to add contract on your website.

**Comment by KayAlbertus** [comment]
Good day team 

It had been added please see link below 

https://xend.finance/token.html

Have we met all criteria ? 

Thank you for your patience 
Kind regards

**Pull request merged**
