### PR TITLE
Add UNCL logo and info

### PR DESCRIPTION
**Pull request by James-Unicrypt**
Adding UNCL logo and info for the first time

### CODE REVIEW

**Comment by catenocrypt** [comment]
Corrections needed:
- UNCL 0x2f4eb47A1b1F4488C71fc10e39a4aa56AF33Dd49: Explorer is incorrect, please change to `https://etherscan.io/token/0x2f4eb47a1b1f4488c71fc10e39a4aa56af33dd49`
- UniCrypt 0xaDB2437e6F65682B85F814fBc12FeC0508A7B1D0: Less than 2500 holders (1273)
- 0xf29e46887FFAE92f1ff87DfE39713875Da541373: Missing info.json
Please correct.

**Comment by Mark-UNCX** [comment]
Hi Adam,

I have changed the UNCL etherscan explorer from /adress to /token.
The only thing we would like in this commit is for UNCL. UNCX has already
been added to trust wallet and the icons are showing on uniswap!

How shall we proceed?

**Comment by Iamdeadlyz** [comment]
info.json for `0xf29e46887FFAE92f1ff87DfE39713875Da541373` is still missing. Please provide one.

**Comment by Mark-UNCX** [comment]
Alright, all set! Everything looks good now for UNC (old token) and UNCL

**Pull request merged**
