### PR TITLE
update logo Bunny Financial - transmit information

### PR DESCRIPTION
**Pull request by BUNBunnyFinancial**
https://bscscan.com/address/0x5c8111c3bcb0cc02acf50bc8676d4aa1bc017607
Contract 0x5C8111C3BCB0Cc02AcF50bC8676d4aa1bC017607
[bunnyFinancial.txt](https://github.com/trustwallet/assets/files/6488772/bunnyFinancial.txt)
logobunny
 transmit information
website: https://bunny.financial/
Medium: https://bunnyfinancial.medium.com/
whitepaper : https://bunny.financial/whitepaper-BunnyFinancial
telegram: https://t.me/BunnyDeFiFinancial
 twitter : https://twitter.com/BunnyFinance

### CODE REVIEW

**Comment by BUNBunnyFinancial** [comment]
please check the 8130 memo pull request. We see it's still not updated

Vào CN, 16 thg 5, 2021 vào lúc 21:19 merge-fee-bot[bot] <
***@***.***> đã viết:

**Comment by BUNBunnyFinancial** [comment]
please check the 8130 memo pull request. We see it's still not updated

**Comment by BUNBunnyFinancial** [comment]
#8130

**Comment by BUNBunnyFinancial** [comment]
why is it still not updated at checkout #8130

**Comment by catenocrypt** [comment]
This PR is wrong.  You are trying to commit an old, stale branch from the main repo, which was not even created by you.

Here is what you should do:
- Fork the https://github.com/trustwallet/assets main repo
- Use the Assets App: https://assets.trustwallet.com
- Enter properties of your logo, and it will create a new PR for you.
- Mention in the new PR that you have already paid for #8130, so that you don't have to pay again

**Comment by BUNBunnyFinancial** [comment]
Could you please double check it for me to see if it is correct or not?
https://github.com/Bunny-Financial/assets/commit/44c10198abc94dd8a8a0560ba42fbc873f9214e2

Vào Th 2, 17 thg 5, 2021 vào lúc 16:48 Adam R ***@***.***>
đã viết:

**Comment by BUNBunnyFinancial** [comment]
Could you please double check it for me to see if it is correct or not?
https://github.com/Bunny-Financial/assets/commit/44c10198abc94dd8a8a0560ba42fbc873f9214e2
 #8130

Vào Th 2, 17 thg 5, 2021 vào lúc 21:59 Github Bunny Financial
***@***.***> đã viết:

**Pull request closed without merging**
