### PR TITLE
Add Digichain Coin (BEP20)

### PR DESCRIPTION
**Pull request by digichaincoin**
Adding info for BEP20 token 'Digichain Coin'.

PR created by <a href="https://assets.trustwallet.com">TW Assets Management</a>

### CODE REVIEW

**Comment by cryptomanz** [comment]
• What is the purpose of this token? How will it benefit Trust Wallet users?
 • How is the token being distributed? Are you conducting an airdrop?
 • Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?
 • Is the token listed on a centralized/decentralized exchange?
 • Is a Smart Contract audit completed? Where can we find this information?

**Comment by prodigichain** [comment]
> • What is the purpose of this token? How will it benefit Trust Wallet users? • How is the token being distributed? Are you conducting an airdrop? • Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale? • Is the token listed on a centralized/decentralized exchange? • Is a Smart Contract audit completed? Where can we find this information?

**Comment by prodigichain** [comment]
> • What is the purpose of this token? How will it benefit Trust Wallet users? • How is the token being distributed? Are you conducting an airdrop? • Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale? • Is the token listed on a centralized/decentralized exchange? • Is a Smart Contract audit completed? Where can we find this information?

**Comment by prodigichain** [comment]
- 

> • What is the purpose of this token? How will it benefit Trust Wallet users? • How is the token being distributed? Are you conducting an airdrop? • Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale? • Is the token listed on a centralized/decentralized exchange? • Is a Smart Contract audit completed? Where can we find this information?

- we want to make all use cases or products that can make it easier for crypto users to carry out their activities in the world of crypto currency
- trust wallet users can easily find digichain assets quickly
- we distribute tokens fairly, with 3 segments, private sale, presale and launch
- we have never done an airdrop, all investors on bscscan are real
- yes we do pre sales on one of the launchpad platforms
- we are officially traded on several dex and several exchanges
-we have audited our smart contract with one of the audit providers, even before we launched the token in the presale we have asked the auditor to audit our smart contract
- For audit information, visit https://solidity.finance/audits/DIGICHAIN/ and for digichain information you can visit our official website https://prodigichain.com

**Comment by prodigichain** [comment]
thanks trust wallet

**Pull request merged**
