### PR TITLE
Add TWT log and info

### PR DESCRIPTION
**Pull request by SupraJai**
First-time submission for TWT logo and information for 0xe38950f71e2d2fc4ca9dc9c3625d82560b0a5d8f

### CODE REVIEW

**Comment by SupraJai** [comment]
can the fees be used later when we meet the requirement?

*Andy Ng*

*Evo Piping Design*

M: (917) 650-3355
E-mail: ***@***.***
E-mail: ***@***.***

**Comment by Cryptocool1** [comment]
> can the fees be used later when we meet the requirement? *Andy Ng* *Evo Piping Design* M: (917) 650-3355 E-mail: ***@***.*** E-mail: ***@***.***
> […](#)

sure

**Comment by Cryptocool1** [comment]
Please come back to us when all criteria are met.
When creating a new PR make sure to mention this PR, so that we can see that fee has been paid already here.

**Comment by SupraJai** [comment]
can you take a look at PR 15802?   The fees are paid and we have 110,000
transition and 24000 holders.   I wants to know if you guys can take a look
at it so we can get the logo on trust wallet.  thanks

*Andy Ng*

M: (917) 650-3355

**Comment by cryptomanz** [comment]
Contract is not in checksum format, should be 0xE38950f71E2D2Fc4cA9dC9C3625d82560b0A5d8F (not 0xe38950f71e2d2fc4ca9dc9c3625d82560b0a5d8f). Please rename it.

**Comment by SupraJai** [comment]
Okay will do 🙂

Andy

M: (917) 650-3355

**Comment by SupraJai** [comment]
okay updated the address format on the info.json

*Andy Ng*

*Evo Piping Design*

M: (917) 650-3355
E-mail: ***@***.***
E-mail: ***@***.***

**Comment by SupraJai** [comment]
I see 2 pull error is there something I provided is not accurate ?
Please advise.  Thanks for helping

Andy

M: (917) 650-3355

**Comment by SupraJai** [comment]
what do I have to fix this time?

*Andy Ng*

*Evo Piping Design*

M: (917) 650-3355
E-mail: ***@***.***
E-mail: ***@***.***

**Comment by cryptomanz** [comment]
Please come back to us when all criteria are met.
When creating a new PR make sure to mention this PR, so that we can see that fee has been paid already here.

**Pull request closed without merging**
