### PR TITLE
Add files via upload

### PR DESCRIPTION
**Pull request by HamtaroBSC**
This PR is being closed due to inactivity. If you wish to continue, please have us reopen the PR before sending your payment, or just create a new one.
Do NOT send payments for closed PR, as the fee may by lost!
  (48 vs. 48 hrs)

### CODE REVIEW

**Comment by HamtaroBSC** [comment]
logo png

**Comment by Cryptocool1** [comment]
Hello,
-You need to rename your logo  file to logo.png.

**Comment by HamtaroBSC** [comment]
Already done

Il giorno mer 5 mag 2021 alle ore 10:51 CryptoA ***@***.***>
ha scritto:

**Comment by Cryptocool1** [comment]
> Already done Il giorno mer 5 mag 2021 alle ore 10:51 CryptoA ***@***.***> ha scritto:
> […](#)

remove this file please blockchains/smartchain/assets/0x4d4cc29b9c4e413cfe5f898e16280f11db57e186/01.png 
 
After that you can pay.

**Comment by HamtaroBSC** [comment]
How i can remove please?

Il giorno mer 5 mag 2021 alle ore 11:01 CryptoA ***@***.***>
ha scritto:

**Comment by catenocrypt** [comment]
Correction needed: the problem is that logo file has double extension.  Please fix.

image

**Comment by HamtaroBSC** [comment]
If I load it again, is it okay?

Il giorno mer 5 mag 2021 alle ore 12:31 Adam R ***@***.***>
ha scritto:

**Pull request closed without merging**
