### PR TITLE
Add token SDC

### PR DESCRIPTION
**Pull request by somdejcoin999**
Hi 
i' want request coin information for verification
If there is any method or extra cost to make it through urgently, please let me know.

Best Regard,

### CODE REVIEW

**Comment by somdejcoin999** [comment]
I have done all the steps, what should I do next?

**Comment by cryptomanz** [comment]
• What is the purpose of this token? How will it benefit Trust Wallet users?
 • How is the token being distributed? Are you conducting an airdrop?
 • Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?
 • Is the token listed on a centralized/decentralized exchange?
 • Is a Smart Contract audit completed? Where can we find this information?

**Comment by somdejcoin999** [comment]
> • What is the purpose of this token? How will it benefit Trust Wallet users? • How is the token being distributed? Are you conducting an airdrop? • Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale? • Is the token listed on a centralized/decentralized exchange? • Is a Smart Contract audit completed? Where can we find this information?

Hi
1.Trust Wallet to reach more members of SDC coin holders, both Thais and Asians.
2.We don't have Airdrop, but we distribute through alliance with Dhurakij Pundit University of Thailand.
3.yes
4.token listed on centralized is hotbit and decentralized pancakeswap
5. The verification is complete, you can check it from the link https://bscscan.com/token/0xae4ca3272792d8499575aefacdc299f0cbdc9270#readContract.

**Comment by Cryptocool1** [comment]
Is a Smart Contract audit completed?

**Comment by somdejcoin999** [comment]
> Is a Smart Contract audit completed?

Smart Contract audit is pending audit.

**Comment by cryptomanz** [comment]
Awaiting for smart contract audit. On hold for now.
Please come back to us when all criteria are met.
When creating a new PR make sure to mention this PR, so that we can see that fee has been paid already here.

**Pull request closed without merging**
