### PR TITLE
adding OodleCoin(ODC)

### PR DESCRIPTION
**Pull request by OodleCoin**
Kindly update the logo and info of the coin

### CODE REVIEW

**Comment by OodleCoin** [comment]
> Token check: Errors found!
> 
> Found 1 added/changed token(s) among the PR files (ERC20: 0xb2883f71092cE684c147924EA75c31b19CD7a351 )
> 
> Error while performing token check, Error: getaddrinfo ENOTFOUND oodlcoin.io

check logo.png and ignore logo.png.png

**Comment by OodleCoin** [comment]
> Token check: Errors found!
> 
> No token files found. If you try to add/modify a token, check the name and location of your files! Logo file must be named exactly 'logo.png'. If you are not adding a token, ignore this message. (2 files in the PR)

Check logo.png and ignore logo.png.png

**Comment by OodleCoin** [comment]
> Token check: Errors found!
> 
> Found 1 added/changed token(s) among the PR files (ERC20: 0xb2883f71092cE684c147924EA75c31b19CD7a351 )
> 
> Error while performing token check, Error: getaddrinfo ENOTFOUND oodlcoin.io

https://oodlecoin.io

**Comment by Cryptocool1** [comment]
As per our policy, brand new tokens are not included, there is a minimum requirement of 2500 holder addresses and 5000 transactions, in order to filter out scam tokens.
See the criteria at (mentioned in the first message by the bot): https://community.trustwallet.com/t/how-to-submit-a-token-logo/3863).

**Pull request closed without merging**
