### PR TITLE
Add Zypto Token (ZYPTO) (ERC20)

### PR DESCRIPTION
**Pull request by ZyptoToken**
Adding info for ERC20 token 'Zypto Token (ZYPTO)'.

PR created by <a href="https://assets.trustwallet.com">TW Assets Management</a>

### CODE REVIEW

**Comment by ZyptoToken** [comment]
Hi team,
Thank you for the consideration. Please be advised, there isn't a combination we haven't tried to get our reddit and youtube channel in there without an error. Had to settle on sending the file with the error. 
Waiting patiently for your review.
Thank you & best regards,

**Comment by Cryptocool1** [comment]
As per our policy, brand new tokens are not included, there is a minimum requirement of 10,000 holder addresses and 15,000 transactions.
See the criteria at : https://developer.trustwallet.com/assets/requirements .

**Comment by Cryptocool1** [comment]
Feel free to create new PR once all criteria are met. Make sure to mention this PR so the fee can be reused

**Comment by ZyptoToken** [comment]
Good day team,
As per policies, it is a subjective criteria.
We meet all the other ones and have done an audit of our token to tick it in the list.
Please consider, we have migrated from French connection finance from BSC, and we have been running the project for 3 years+,
Kind regards,

**Comment by ZyptoToken** [comment]
Considering our migration, we have over 10k wallet that havent claimed their Zypto tokens just yet.

**Comment by ZyptoToken** [comment]
Hi team,
Please advise. As stated, we migrated from FCF to Zypto, and FCF had all necessary on the trust wallet app.
Kind regards,

**Pull request closed without merging**
