### PR TITLE
Add WLQX (Wrapped LQX)

### PR DESCRIPTION
**Pull request by juan-silveira**
LQX Coin is originaly a X11 Protocol and now it is Multi-Chain with BEP-20
https://lqxcoin.com
Explorer showing distribution and Holders on own blockchain: https://explorer.lqxcommunity.org/distribution

The Wrapped LQX is growing every day, we still don't have the requirement of 2500 holders on BSC, but we appreciate if you consider ours 43000 holders that are now been instructed to migrate do BSC, to improve our liquidity in many pairs.

### CODE REVIEW

**Comment by juan-silveira** [comment]
LQX Coin is originaly a X11 Protocol and now it is Multi-Chain with BEP-20
https://lqxcoin.com
Explorer showing distribution and Holders on own blockchain: https://explorer.lqxcommunity.org/distribution

The Wrapped LQX is growing every day, we still don't have the requirement of 2500 holders on BSC, but we appreciate if you consider our 43000 holders that are now been instructed to migrate do BSC, to improve our liquidity in many pairs.

May I consider that we fullfill all requirement and proceed to pay?

**Comment by catenocrypt** [comment]
Submission is OK, awaiting fee payment.

**Comment by juan-silveira** [comment]
Nice, doing right NOW!!!!!!!

Em qua., 31 de mar. de 2021 às 12:47, Adam R ***@***.***>
escreveu:

**Comment by juan-silveira** [comment]
Hi, there is an estimate of when it will be merged and the logo will be available at Trust Wallet?

Cheers

**Pull request merged**
