### PR TITLE
Adding everrise.com logo for dApp

### PR DESCRIPTION
**Pull request by everrisecooin**
Adding everrise.com.png logo for EverRise dApp

### CODE REVIEW

**Comment by everrisecooin** [comment]
Hi, Could someone please merge this PR?

**Comment by Cryptocool1** [comment]
Please update your branch with the recent master

**Comment by everrisecooin** [comment]
Thank you. Updated to the latest master.

**Comment by Cryptocool1** [comment]
Thanks

**Comment by everrisecooin** [comment]
Thank you.

**Pull request merged**
