### PR TITLE
Create logo.png

### PR DESCRIPTION
**Pull request by xuweilong2019**
update logo

### CODE REVIEW

**Comment by zachzwei** [comment]
Please send here the logo as the file that you submitted is not opening up.

**Comment by xuweilong2019** [comment]
> Please send here the logo as the file that you submitted is not opening up.
Thank you , and the folder name : trustwallet/assets/master/blockchains/ethereum/assets/0xfb7da9863e030495db8b4d067d665fc8433fff85/logo.png
logo

**Comment by xuweilong2019** [comment]
> Please send here the logo as the file that you submitted is not opening up.



> Please send here the logo as the file that you submitted is not opening up.

sorry , still can not find the logo.png in the link below folder, plz help to check is it in the right folder ? Thank you ! 
 https://github.com/trustwallet/assets/tree/master/blockchains/ethereum/assets/0xfb7da9863e030495db8b4d067d665fc8433fff85/logo.png

**Comment by xuweilong2019** [comment]
sorry , still can not find the logo.png in the link below folder, plz help to check is it in the right folder ? Thank you !
https://github.com/trustwallet/assets/tree/master/blockchains/ethereum/assets/0xfb7da9863e030495db8b4d067d665fc8433fff85/logo.png
logo

**Pull request merged**
