### PR TITLE
Add Lemonn token, logo and info (BEP20)

### PR DESCRIPTION
**Pull request by LemonnToken**
Add Lemonn token, logo and info (BEP20)

Keep only logo and info uploaded 8/01/2022

### CODE REVIEW

**Comment by Cryptocool1** [comment]
• What is the purpose of this token? How will it benefit Trust Wallet users?
 • How is the token being distributed? Are you conducting an airdrop?
 • Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?
 • Is the token listed on a centralized/decentralized exchange?
 • Is a Smart Contract audit completed? Where can we find this information?

**Comment by LemonnToken** [comment]
• What is the purpose of this token? How will it benefit Trust Wallet users?

Lemonn is the first job searching platform tailored to BSC: remote, flexible, easy. Lemonn Token offers premium advantages for job seekers and recruiters, as well as on voting contest to be able to give an awards.

• How is the token being distributed? Are you conducting an airdrop?

Lemonn performed an airdrop and vesting of tokens through Astronaut launchpad.

• Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?

Lemonn performed an IDO through Astronaut launchpad, all information on Lemonn whitepaper, link below:
https://storage.googleapis.com/public-lemonn/Lemonn_Whitepaper_V1.pdf

Second largest IDO on Astronaut platform, link below:
https://twitter.com/astronauttoken/status/1476918339482132534?s=20

• Is the token listed on a centralized/decentralized exchange?

Lemonn token is listed on 2 decentralized exchanges: PancakeSwap & ApeSwap

Partnership with ApeSwap, link below:
https://twitter.com/ape_swap/status/1455655960979116035

• Is a Smart Contract audit completed? Where can we find this information?

The smart contract has been audited by TechRate, link below:
https://storage.googleapis.com/public-lemonn/TechRate%20Audit%20Lemonn%20Token.pdf

**Comment by cryptomanz** [comment]
As per our policy, brand new tokens are not included, there is a minimum requirement of 10,000 holder addresses and 20,000 transactions, in order to filter out scam tokens.
See the criteria at : https://developer.trustwallet.com/assets/requirements .

**Comment by cryptomanz** [comment]
Please come back to us when all criteria are met.
When creating a new PR make sure to mention this PR, so that we can see that fee has been paid already here.

**Pull request closed without merging**
