### PR TITLE
Adding Krown

### PR DESCRIPTION
**Pull request by KingDeFiKRW**
All the requisite are achieved (https://community.trustwallet.com/t/how-to-submit-a-token-logo/3863)
website: https://kingdefi.io/home
roadmap: https://kingdefi.io/roadmap
audits: https://kingdefi.io/assets/files/AuditFarms.pdf
https://kingdefi.io/assets/files/CertikAuditFarms.pdf
telegram: https://t.me/KingDefi_Community
twitter: https://twitter.com/KingDefi2
discord: https://discord.com/invite/9d3RrbNvTM
coinmarketcap: https://coinmarketcap.com/it/currencies/kingdefi/
coingecko: https://www.coingecko.com/it/monete/krown
5200k holders as of now and over 200k transactions

### CODE REVIEW

**Comment by cryptomanz** [comment]
hello,
can your answer some questions?
• What is the purpose of this token? How will it benefit Trust Wallet users?
• How is the token being distributed? Are you conducting an airdrop?
• Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?
• Is the token listed on a centralized/decentralized exchange?
• Is a Smart Contract audit completed? Where can we find this information?

**Comment by KingDeFiKRW** [comment]
Hi @cryptomanz, 
-we are a multichain yield aggregator, so user on our site will be able to stake token and earn yield in various way, we are also offering analytics services (like statistics on other defi project) that will be paid for with the token (for now it's free because we launched only 3 months ago)
-we are not doing airdrops, we released around 1/20 of the tokens in a public crowdsale in may and since june we are allowing user to farm our token on our website and on our partners websites
-Yes we did a presale, as I said in may and we release around 1/20 of the total supply
-it is listed on pancakeswap, apeswap and waultswap for the DEXs on BSC, we are going multichain so we will soon be on Uniswap for ETH, Quickswap for Polygon and Serum for solana, we are not officialy listed on a CEX yet
-every one of our smart contracts is audited, our bep20 and our farms, you can find the informations on our website on in the description of this pull request, I will paste the audit of our main farm (basically the most important smart contract) here: 
audits: https://kingdefi.io/assets/files/AuditFarms.pdf
https://kingdefi.io/assets/files/CertikAuditFarms.pdf

**Comment by cryptomanz** [comment]
As per our documentary, token image should be 256x256
Here is the link to guidelines details: https://community.trustwallet.com/t/how-to-submit-a-token-logo/3863

**Comment by KingDeFiKRW** [comment]
Updated the logo, now it should follow all the guidelines

**Pull request merged**
