### PR TITLE
Add Galaxy Finance Token (BEP20)

### PR DESCRIPTION
**Pull request by galaxyfinancetoken**
Adding info for BEP20 token 'Galaxy Finance Token'.

PR created by <a href="https://assets.trustwallet.com">TW Assets Management</a>

### CODE REVIEW

**Comment by Cryptocool1** [comment]
hello, how did you get 23k holders in 2 weeks?

**Comment by galaxyfinancetoken** [comment]
> hello, how did you get 23k holders in 2 weeks?

We presale in 12 days and sell over $12M in total. We just listed on pancakeswap yesterday.

**Comment by Cryptocool1** [comment]
your holders seems to be artificial, on hold for now.

**Comment by galaxyfinancetoken** [comment]
> your holders seem artificial, on hold for now.

Thanks! Please check and let me know soon!

**Comment by galaxyfinancetoken** [comment]
Please help us with checking contract! Our holder need token logo to avoid missing buying with other token with the same name!

**Comment by Cryptocool1** [comment]
Please see my comment above.

**Pull request merged**
