### PR TITLE
ESD Token

### PR DESCRIPTION
**Pull request by PatrickDehkordi**
Adding Empty Set Token. All requirments are complete.

### CODE REVIEW

**Comment by PatrickDehkordi** [comment]
This is identical to 4617, however the auto check passes, since I started form the latest assets repo. We paid with reference to 4617. Can you  apply that payment to here instead, or alternativley process 4617. 

Best regards,
Patrick

**Comment by Iamdeadlyz** [comment]
Paid #4617

**Comment by Iamdeadlyz** [comment]
As per our policy, brand new tokens are not included. There is a minimum requirement of 500 holder addresses and 1000 transactions in order to filter out scam tokens. See the criteria at (mentioned in the first message by the bot): https://community.trustwallet.com/t/how-to-submit-a-token-logo/3863#how-to-get-approved

This token has below-limit usage yet. This pull request will be put on hold. Please come back to us when all criteria are met.
https://etherscan.io/token/0x36f3fd68e7325a35eb768f1aedaae9ea0689d723 (105, 7836)

**Comment by l3wi** [comment]
Hey @Iamdeadlyz the token has more than the 104 listed. If you look at the holder distribution you will see that there is one address holding 84% of the total tokens. This is the DAO address and there is currently a vote on going. 

Users who deposit their tokens in the DAO are given an internal token to track their share of the DAO. This is called ESDS this has 485 holders as per: https://etherscan.io/token/0x443d2f2755db5942601fa062cc248aaa153313d3

So in reality we have 485 ESD token holders in the DAO  + 103 ESD token holders in their wallet - 1 for the DAO address. Totalling 587.

**Pull request merged**
