### PR TITLE
Bridge Mutual

### PR DESCRIPTION
**Pull request by bridgemutual**

### CODE REVIEW

**Comment by Iamdeadlyz** [comment]
Please provide more details about this project.
https://community.trustwallet.com/t/how-to-submit-a-token-logo/3863#how-to-get-approved
You can follow this format when adding an info.json file:
```
{
    "name": "Trust Wallet Token",
    "website": "https://trustwallet.com",
    "source_code": "https://github.com/trustwallet/",
    "short_description": "Utility token to increase adoption of cryptocurrency.",
    "description": "Utility token to increase adoption of cryptocurrency.",
    "socials": [
        {
            "name": "Twitter",
            "url": "https://twitter.com/trustwalletapp",
            "handle": "TrustWalletApp"
        },
        {
            "name": "Reddit",
            "url": "https://reddit.com/r/trustapp",
            "handle": "TrustApp"
        }
    ],
    "explorer": "https://bscscan.com/token/0x4b0f1812e5df2a09796481ff14017e6005508003"
} 
```

**Comment by Iamdeadlyz** [comment]
Also, please follow this guide properly: 
- https://community.trustwallet.com/t/how-to-submit-a-token-logo/3863/
- https://community.trustwallet.com/t/how-to-add-the-token-information/3888

If you want to create a new PR and use this tool, feel free to do so. Just tag me and mention this PR (#5445) so you don't have to pay again. Guide: https://community.trustwallet.com/t/how-to-submit-a-token-logo-using-assets-app/82957

**Comment by bridgemutual** [comment]
hey @Iamdeadlyz,
Thank you for your attention to this!
Looks like we have fixed everything:
https://github.com/trustwallet/assets/pull/5445/commits/b276d0752cb0f17d31f1127a0ac709cbc9373045

**Comment by catenocrypt** [comment]
A few recently-added fields are missing from the info.json files.  I tried to add them, but I have no write access to this PR (usually I do).  Please update the info.json file:

```
{
    "name": "Bridge Mutual",
    "type": "ERC20",
    "symbol": "BMI",
    "decimals": 18,
    "website": "https://bridgemutual.io",
    "source_code": "https://github.com/Bridge-Mutual",
    "short_description": "A discretionary risk coverage platform.",
    "description": "Bridge Mutual is a decentralized, discretionary p2p/p2b platform that provides coverage for stablecoins, centralized exchanges, and smart contracts. Its allows users to provide coverage, decide on payouts, and get compensated for taking part in the ecosystem.",
    "socials": [
        {
            "name": "Twitter",
            "url": "https://twitter.com/bridge_mutual",
            "handle": "Bridge_Mutual"
        }
    ],
    "explorer": "https://etherscan.io/address/0x725C263e32c72dDC3A19bEa12C5a0479a81eE688",
    "status": "active",
    "id": "0x725C263e32c72dDC3A19bEa12C5a0479a81eE688"
}
```

**Comment by bridgemutual** [comment]
I've committed the changes. Can we please check if this is right now? :)

**Comment by bridgemutual** [comment]
Bumping this.

**Comment by catenocrypt** [comment]
I think a comma is missing in info.json, fixing...

**Comment by catenocrypt** [comment]
Merged, within #5556 (could not fix this PR).

**Pull request closed without merging**
