### PR TITLE
adding Froginu(FGI) logo to trust wallet

### PR DESCRIPTION
**Pull request by ghost**
adding Froginu(FGI) logo to trust wallet

### CODE REVIEW

**Comment by Froginutoken** [comment]
can i transfer 700 TWT or transfer 5BNB right?

**Comment by Cryptocool1** [comment]
your files are incorrect 
Please create new PR, follow doc https://developer.trustwallet.com/assets/requirements
You may want to try our Assets app in beta; go to https://assets.trustwallet.com, log on with Github, enter contract ID, logo and some additional info, and it will create a PR for you.
See https://developer.trustwallet.com/assets/repository_details

**Comment by Onyeali** [comment]
Help

**Comment by Froginutoken** [comment]
image
I can't create on BEP20

**Pull request closed without merging**
