### PR TITLE
add BEP20 KGO

### PR DESCRIPTION
**Pull request by KIWIPAY-KGO**
adding BEP20 KGO
https://coinmarketcap.com/currencies/kiwigo/
https://www.coingecko.com/en/coins/kiwigo

### CODE REVIEW

**Comment by KIWIPAY-KGO** [comment]
hi,
i try to add BEP20 ( How to Add an Asset to Token List ) 
and i have a error conflit, i dont understand, 
can you tell me the problem ? and also if i use the good way ?
Thank you

**Comment by KIWIPAY-KGO** [comment]
hi, i dont understand the error
I just try Add BEP20 Asset to token list ( i not change the JSON ) 
i just would like add asset ( CMC and Coin geko ) for show the Value / asset in other app.
can you help me and tell me if i use good way ?
Thank you

**Comment by KIWIPAY-KGO** [comment]
cancel

**Comment by catenocrypt** [comment]
Conflict probably means that your fork of the repository was outdated.

**Pull request closed without merging**
