### PR TITLE
Add Sakai-Peg USD (BEP20)

### PR DESCRIPTION
**Pull request by SakaiVault**
Adding info for BEP20 token 'Sakai-Peg USD'.

PR created by <a href="https://assets.trustwallet.com">TW Assets Management</a>

### CODE REVIEW

**Review by Kcsiochi — COMMENTED** [review]
Approve

**Comment by SakaiVault** [comment]
@covain @Cryptocool1 @cryptomanz1 Please check our PR

**Comment by Cryptocool1** [comment]
Hello, 
• What is the purpose of this token? How will it benefit Trust Wallet users?
 • How is the token being distributed? Are you conducting an airdrop?
 • Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?
 • Is the token listed on a centralized/decentralized exchange?
 • Is a Smart Contract audit completed? Where can we find this information?

**Comment by SakaiVault** [comment]
1. What is the purpose of the sUSD token?

The Sakai-Peg USD (sUSD) token is designed to enhance liquidity and reward users participating in the farming pool with Sakai Vault’s strategic partner, PAXE. It serves as a stablecoin pegged to users' total claimable balance in the Sakai V1 staking pool, ensuring stability by maintaining a 1:1 ratio with their USDT balance. The token enables users to pair it with PAXE tokens in the farming pool to generate additional rewards. After farming, the farmed sUSD is burned to control the supply and maintain value. 
https://app.sakaivault.io/farming

2. How will it benefit Trust Wallet users?

The sUSD token can be transferred through Trust Wallet, allowing Trust Wallet users to farm and restake assets efficiently with Trust Wallet portal to the Liquidity Farming Pool. The simplicity of using Trust Wallet for staking and farming directly with sUSD also offers a convenient and secure experience for managing DeFi assets.

3. How is the token being distributed?

The sUSD token is distributed based on the claimable balance of users in the V1 staking pool. It is minted in an amount equal to the total claimable balance and transferred directly to users’ wallets. However, the token can only be transferred within the user's own wallet and cannot be traded or transferred to others.
https://appv1.sakaivault.io

Are you conducting an airdrop: No

• Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale: No

• Is the token listed on a centralized/decentralized exchange: No
• Is a Smart Contract audit completed:  Not yet
Where can we find this information: In progress

**Comment by cryptomanz1** [comment]
Hello,
Feel free to come back to us once security audit is done

**Comment by SakaiVault** [comment]
our audit : https://blocksafu.com/audit/0x5E4FAF13A3D66E741F1e9B8743B8d26F6AFe9CE7
@cryptomanz1

**Comment by fati1365** [comment]
کمک میخوام

**Comment by SakaiVault** [comment]
@Cryptocool1 @cryptomanz1 any progress?

**Comment by Cryptocool1** [comment]
Снимок экрана 2024-10-07 в 17 56 50
After careful review we noticed your token is marked as high risked. We require security score at least 60 
The request will be closed until further notice.
Feel free to re-open pull request once you meet those requirements

**Pull request closed without merging**
