### PR TITLE
Add SIMBCOIN SWAP (SMB SWAP) (ERC20)

### PR DESCRIPTION
**Pull request by Shyamthakur33**
This PR is being closed due to inactivity. If you wish to continue, please have us reopen the PR before sending your payment, or just create a new one.
Do NOT send payments for closed PR, as the fee may by lost!
  (48 vs. 48 hrs)

### CODE REVIEW

**Comment by Shyamthakur33** [comment]
@Cryptocool1 please check, we have space in our symbol. is it okay?

**Comment by Cryptocool1** [comment]
> @Cryptocool1 please check, we have space in our symbol. is it okay?

Symbol should be the same as in explorer

**Comment by Shyamthakur33** [comment]
ya

> > @Cryptocool1 please check, we have space in our symbol. is it okay?
> 
> Symbol should be the same as in explorer

ya, it's same as in etherscan, just asking we have space in our symbol in etherscan?

**Comment by Shyamthakur33** [comment]
> ya
> 
> > > @Cryptocool1 please check, we have space in our symbol. is it okay?
> > 
> > 
> > Symbol should be the same as in explorer
> 
> ya, it's same as in etherscan, just asking we have space in our symbol in etherscan?

@Cryptocool1 you there?

**Pull request closed without merging**
