### PR TITLE
Update YFID info

### PR DESCRIPTION
**Pull request by Brag2gr8**
Modify YFID Logo

### CODE REVIEW

**Comment by Brag2gr8** [comment]
Paid

**Comment by Brag2gr8** [comment]
when does it get updated??

**Comment by zachzwei** [comment]
Please provide more details about this project. 
https://community.trustwallet.com/t/how-to-submit-a-token-logo/3863#how-to-get-approved

You can follow this format when adding an info.json file:

```
 {
   "name":"Bitcoin",
   "website":"https://bitcoin.org",
   "source_code":"https://github.com/bitcoin",
   "white_paper":"https://bitcoin.org/bitcoin.pdf",
   "short_description":"Bitcoin is a cryptocurrency and worldwide payment system.",
   "explorer":"https://blockchain.info",
   "research":"https://research.binance.com/en/projects/bitcoin"
}

**Comment by Brag2gr8** [comment]
I submitted an info.json file, here is complete info


```
 {
   "name":"YfiDefi.Finance",
   "website":"Yfid.Finance",
   "short_description":"YFIDEFI.FINANCE is a new form of governance system, a think-tank where innovation, entrepreneurship, and technological advancements are the priority, creating a much needed utility focus to the blockchain space.",
   "explorer":"https://etherscan.io/token/0xAb5E1eD250D5C8C1AFbbca8c079284EfE8a37a9c",
}

```

**Comment by Brag2gr8** [comment]
Go on with the logo

**Comment by Brag2gr8** [comment]
Modify YFID logo

**Comment by zachzwei** [comment]
You need to put the info.json file on the same location as the logo.
Token activity does not meet the minimum requirements.
Pull request will be put on Hold.
Learn more here:
https://community.trustwallet.com/t/how-to-submit-a-token-logo/3863#how-to-get-approved

**Comment by Brag2gr8** [comment]
so I have to create another pull request and pay another merge fee or is there a way to merge it in

**Comment by catenocrypt** [comment]
> so I have to create another pull request and pay another merge fee or is there a way to merge it in

No, you can add the info.json to this PR.  Or you can create a new PR, and ask to consider payment from this one, no need to pay again.
Please also have in ind, that as mentioned in the docs earlier, we do not merge tokens with less than 100 holder addresses or less than 500 transactions!

**Comment by Brag2gr8** [comment]
Wow..
Took long and didn't get the results..
Can I get my money back?

**Comment by Brag2gr8** [comment]
Swnd to same address or should I drop a new one??

**Comment by Brag2gr8** [comment]
no answers where given

**Pull request closed without merging**
