### PR TITLE
Add CoverCompared (ERC20)

### PR DESCRIPTION
**Pull request by chefcardano**
Adding info for ERC20 token 'CoverCompared'.

PR created by <a href="https://assets.trustwallet.com">TW Assets Management</a>

### CODE REVIEW

**Comment by dakshjoshi** [comment]
Hey Trustwallet!

There is a problem, even though we have successfully updated the CoverCompared logo on Uniswap we are able to see the pervious logo. Please suggest what is the problem and what is to be done from our side. 

Outdate logo being showed in uniswap :

Screenshot 2021-11-08 at 3 47 26 PM

New logo which should have been showed : 

 
logo

**Comment by dakshjoshi** [comment]
Hello Trustwallet, 

This message is in regards with wrong logo being displayed of CoverCompared token after successful PR update.

The updated covercompared logo is not being displayed on Uniswap. 

The new logo which should have been displayed is : 
logo

The logo which is being displayed (wrong logo) is : 
Screenshot 2021-11-15 at 1 10 52 PM

**Comment by Cryptocool1** [comment]
hello,
your logo seems wrong in the circle
photo_2021-11-15 07 47 16
Can you send here logo image in full size?

**Comment by chefcardano1** [comment]
I'll provide it shortly

**Comment by dakshjoshi** [comment]
Please find the logo attached below

Thank you

[image: covercompared logo.png]

**Pull request merged**
