### PR TITLE
Directory Name Update

### PR DESCRIPTION
**Pull request by YFIDapp**
This PR is being closed due to inactivity. If you wish to continue, please have us reopen the PR before sending your payment.
Do NOT send payments for closed PR, as the fee may by lost!
  (60 vs. 60 hrs)

### CODE REVIEW

**Comment by catenocrypt** [comment]
Previous: #4878

**Comment by catenocrypt** [comment]
Please, there should be only 2 files, not 5.

image

**Comment by catenocrypt** [comment]
Alternatively, you may want to try our new Assets app in beta; close this PR; go to https://assets.trustwallet.com, log on with Github, enter contract ID, logo and some additional info, and it will create a PR for you.
See https://community.trustwallet.com/t/how-to-submit-a-token-logo-using-assets-app/82957.

**Comment by YFIDapp** [comment]
> Please, there should be only 2 files, not 5.
> 
> image

the issue occurred due to changing the directory name. it considered 5 files. instead of 2.

**Comment by YFIDapp** [comment]
> Alternatively, you may want to try our new Assets app in beta; close this PR; go to https://assets.trustwallet.com, log on with Github, enter contract ID, logo and some additional info, and it will create a PR for you.
> See https://community.trustwallet.com/t/how-to-submit-a-token-logo-using-assets-app/82957.

doing the same

**Comment by YFIDapp** [comment]
@catenocrypt : Shall we go ahead with payment now?

**Comment by YFIDapp** [comment]
fees paid

**Comment by YFIDapp** [comment]
> @YFIDapp, kind reminder: please pay fee: **1000 TWT** with the memo **4889** to the address `bnb1tqq9llyr3dyjd559dha6z5r5etk3qfwk07m098`.
> Alternatively, 6 BNB is also accepted (same memo & address).
> 
> **QR** code: [Trust](https://api.qrserver.com/v1/create-qr-code/?size=200x200&data=https%3A%2F%2Flink.trustwallet.com%2Fsend%3Fcoin%3D714%26address%3Dbnb1tqq9llyr3dyjd559dha6z5r5etk3qfwk07m098%26amount%3D1000%26memo%3D4889) | [other wallet](https://api.qrserver.com/v1/create-qr-code/?size=200x200&data=bnb1tqq9llyr3dyjd559dha6z5r5etk3qfwk07m098%26amount%3D1000%26memo%3D4889)
> See the [Pull Request Fee FAQ](https://developer.trustwallet.com/add_new_asset/pr-fee).

fees paid

**Comment by YFIDapp** [comment]
> Previous: #4878

merge-fee-bot is not updating payment status. please check

**Comment by catenocrypt** [comment]
Can you provide payment TX ID?

**Comment by YFIDapp** [comment]
> Can you provide payment TX ID? Maybe memo was mispelled?

https://explorer.binance.org/tx/A380766C37A6A76FC1958F4035E1549EC1380A4C9BED054BF52EAA5D14787EB1

**Comment by YFIDapp** [comment]
@catenocrypt : please re open the PR, as payment is already sent

**Comment by catenocrypt** [comment]
Memo was set incorrectly (`002`), that's why it was not processed automatically.  Setting it manually.

https://explorer.binance.org/tx/A380766C37A6A76FC1958F4035E1549EC1380A4C9BED054BF52EAA5D14787EB1

image

**Comment by catenocrypt** [comment]
The bad news is that the circulation of this token is below our required limit.
As per our policy, there is a minimum requirement of 2500 holder addresses and 5000 transactions, in order to filter out scam tokens.
See the criteria at (mentioned in the first message by the bot): https://community.trustwallet.com/t/how-to-submit-a-token-logo/3863).
Putting PR on hold. Please come back to us when all criteria are met.

https://etherscan.io/token/0x61266424B904d65cEb2945a1413Ac322185187D5

**Comment by YFIDapp** [comment]
kindly consider 

> The bad news is that the circulation of this token is below our required limit.
> As per our policy, there is a minimum requirement of 2500 holder addresses and 5000 transactions, in order to filter out scam tokens.
> See the criteria at (mentioned in the first message by the bot): https://community.trustwallet.com/t/how-to-submit-a-token-logo/3863).
> Putting PR on hold. Please come back to us when all criteria are met.
> 
> https://etherscan.io/token/0x61266424B904d65cEb2945a1413Ac322185187D5

kindly consider see our performance

**Comment by YFIDapp** [comment]
> The bad news is that the circulation of this token is below our required limit.
> As per our policy, there is a minimum requirement of 2500 holder addresses and 5000 transactions, in order to filter out scam tokens.
> See the criteria at (mentioned in the first message by the bot): https://community.trustwallet.com/t/how-to-submit-a-token-logo/3863).
> Putting PR on hold. Please come back to us when all criteria are met.
> 
> https://etherscan.io/token/0x61266424B904d65cEb2945a1413Ac322185187D5

kindly update

**Comment by catenocrypt** [comment]
No action since almost 2 months, closing.  Please have us reopened when appropriate.

(548 holders, https://etherscan.io/token/0x61266424B904d65cEb2945a1413Ac322185187D5)

**Pull request closed without merging**
