### PR TITLE
Add Pepe 2.0 (PEPE2.0) (ERC20)

### PR DESCRIPTION
**Pull request by yamennajjar80**
Adding info for ERC20 token 'Pepe 2.0 (PEPE2.0)'.

PR created by <a href="https://assets.trustwallet.com">TW Assets Management</a>

### CODE REVIEW

**Comment by yamennajjar80** [comment]
Hello @Cryptocool1 
Do I need to take any action to get this request approved?

**Comment by yamennajjar80** [comment]
Hello @Cryptocool1 
Do we have any update on this request, please? 
We appreciate your support and efforts.

**Comment by Cryptocool1** [comment]
• What is the purpose of this token? How will it benefit Trust Wallet users?
 • How is the token being distributed? Are you conducting an airdrop?
 • Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?
 • Is the token listed on a centralized/decentralized exchange?
 • Is a Smart Contract audit completed? Where can we find this information?

**Comment by yamennajjar80** [comment]
Hello Cryprocool!
Thank you for your response here are the answers.

**What is the purpose of this token?**
Provide a fully transparent and decentralised experience for all investors with future passive income earnings implemented for all holders 

**How will it benefit Trust Wallet users?**
This will provide further trust by having the logo implemented showing the team are serious and dedicated. Holders of Pepe 2.0 are also users of Trust Wallet so it makes the UI a lot more attractive 

**• How is the token being distributed?**
Via Uniswap and the exchanges listed below  
https://coinmarketcap.com/currencies/pepe-2-0/markets/

**Are you conducting an airdrop?** No

**• Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?** No

**• Is the token listed on a centralized/decentralized exchange?** 
Yes multiple - Mexc, bitget  , Lbank 

**• Is a Smart Contract audit completed?**
Not yet , the contract is renounced, however. 

**Where can we find this information?**
On our website , Coinmarketcap or etherscan

Thanks in advance

**Comment by Cryptocool1** [comment]
We require smart contract audit, please see it in our documentation. 
Feel free to come back to us once all criteria are met.

**Comment by yamennajjar80** [comment]
Hello 
We have the Audit now.
Would you please update the request

**Comment by Cryptocool1** [comment]
Please send it here

**Comment by yamennajjar80** [comment]
https://github.com/SpyWolfNetwork/Smart_Contract_Audits/blob/main/June_2023/PEPE20.0xfb66321d7c674995dfcc2cb67a30bc978dc862ad.pdf

**Comment by Cryptocool1** [comment]
Hello again, we do not accept this audit company, I’ve recommended you reputable audit companies, please see my message above.

**Comment by yamennajjar80** [comment]
> Hello again, we do not accept this audit company, I’ve recommended you reputable audit companies, please see my message above.

Hello, those companies take too much time get the audit while we would like support the project and TW users by addding the logo and token info.

**Comment by yamennajjar80** [comment]
> Hello again, we do not accept this audit company, I’ve recommended you reputable audit companies, please see my message above.

Hey lady. 

Spy Wolf is reputable and pinksale certified with Exclusive mark. 
you know pinksale is one of the most reputable platfoms in the crpto nowadays 

check it here please https://docs.pinksale.finance/important/audit-partners

**Comment by yamennajjar80** [comment]
> > Hello again, we do not accept this audit company, I’ve recommended you reputable audit companies, please see my message above.
> 
> Hey lady.
> 
> Spy Wolf is reputable and pinksale certified with Exclusive mark. you know pinksale is one of the most reputable platfoms in the crpto nowadays
> 
> check it here please https://docs.pinksale.finance/important/audit-partners

Hely Lady, @Cryptocool1 
I hope you did the needed research on our Audit company, and become sure how it's reputable and verified. 
Waiting for your reply, thank you in advance for your support.

**Comment by yamennajjar80** [comment]
Good morning,
Allow me to let you know that the pepe2.0 community who are using trust wallet are very upset and demanding the approval to be able to swap and see logo and find the token as in MetaMask, sorry for that. But pepe2.0 have significant amount of holders using TrustWallet, please approve this for the community 
IMG_1531

**Comment by yamennajjar80** [comment]
We are still waiting for your approval please, PEPE2.0 Holders are 10,200 now

**Comment by yamennajjar80** [comment]
> We are still waiting for your approval please, PEPE2.0 Holders are 10,200 now

@Cryptocool1 Hello again, 
We are growing with 10,550 holders now, and new CEX listings are incoming, it's time to get this approved Lady.

**Pull request closed without merging**
