### PR TITLE
Add Senspark (BEP20)

### PR DESCRIPTION
**Pull request by SparkMaintainer**
Adding info for BEP20 token 'Senspark'.

PR created by <a href="https://assets.trustwallet.com">TW Assets Management</a>

### CODE REVIEW

**Comment by thuanss** [comment]
Hi, I submit new token via https://assets.trustwallet.com/

Our new token is Sen (https://bscscan.com/token/0x23383e18dEedF460EbB918545C8b0588038B7998)

The previous token, BCoin (0x00e1656e45f18ec6747F5a8496Fd39B50b38396D) already merged before. I dont know why it mentions here.

Please give instructions

**Comment by thuanss** [comment]
Can I process the payment?

**Comment by Cryptocool1** [comment]
• What is the purpose of this token? How will it benefit Trust Wallet users?
 • How is the token being distributed? Are you conducting an airdrop?
 • Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?
 • Is the token listed on a centralized/decentralized exchange?
 • Is a Smart Contract audit completed? Where can we find this information?

**Comment by thuanss** [comment]
Hi @Cryptocool1,

> What is the purpose of this token? How will it benefit Trust Wallet users?
- This token is used for rewards in our projects. For now, it used as the 2nd reward for BombCrypto players. Other projects will come in the future (Sorry, I cant provide more details for next project yet).
- With publish on Trust Wallet, we can protect TW users  from scammer. When we started, some bad guys trying to give phishing user with wrong Contract Addresses. So with the update token on TW app, user can know which is the correct token.

> How is the token being distributed? Are you conducting an airdrop?
- No 

> Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?
No

> Is the token listed on a centralized/decentralized exchange?
- Currently we listed on Pancake at https://pancakeswap.finance/swap?outputCurrency=0x23383e18deedf460ebb918545c8b0588038b7998

> Is a Smart Contract audit completed? Where can we find this information?
- We are in the auditing process. We can deliver it later.

**Comment by Cryptocool1** [comment]
Hello. We require smart contract audit. Please come back to us with completed audit

**Comment by thuanss** [comment]
Thanks @Cryptocool1

**Pull request closed without merging**
