### PR TITLE
Add ALPHAKOMBAT Info + Logo

### PR DESCRIPTION
**Pull request by Alphakombat**

### CODE REVIEW

**Comment by Alphakombat** [comment]
Hey

Not sure what the errors are about?
Token is BEP20, and the other errors seem incorrect too

**Comment by Cryptocool1** [comment]
This is a BEp20 token, correct folder is blockchains/smartchain/assets.

**Comment by Alphakombat** [comment]
Upload seems to be disabled on https://github.com/trustwallet/assets/tree/master/blockchains/smartchain/assets 
please could you enable it from your end? 
Screenshot_3

**Comment by Alphakombat** [comment]
@Cryptocool1 Changes made

**Comment by Cryptocool1** [comment]
According to our documentation token image needs to be full screen, here is link to guidelines details and an example of token images https://community.trustwallet.com/t/how-to-submit-a-token-logo/3863

**Comment by Alphakombat** [comment]
@Cryptocool1 Logo now updated

**Pull request merged**
