### PR TITLE
Add Teller USD (BEP20)

### PR DESCRIPTION
**Pull request by TellerUSD**
Adding info for BEP20 token 'Teller USD'.

PR created by <a href="https://assets.trustwallet.com">TW Assets Management</a>

### CODE REVIEW

**Comment by TellerUSD** [comment]
Logo Update Request For TELLER USD (USDT): Add Teller USD (BEP20) (PR
#26866)

Dear Trustwallet/Assets,
I made a payment of 500 TWT to bnb158fgd782we4tz9vwwcj9pmmxvxhl6z46lfm7c8.
Payment TxHash:
F1F4551775B80E7B5B641CFC7EB6DA43FC3D8D2AB67F839497D45AE13D88C90E


I will be happy if you can help me publish my Token Logo Successfully For
Me On Trust Wallet. Waiting for your reply soon.

Thanks

**Comment by TellerUSD** [comment]
Logo Update Request For TELLER USD (USDT): Add Teller USD (BEP20) (PR #26866)

Dear Trustwallet/Assets,
I made a payment of 500 TWT to bnb158fgd782we4tz9vwwcj9pmmxvxhl6z46lfm7c8.
Payment TxHash: F1F4551775B80E7B5B641CFC7EB6DA43FC3D8D2AB67F839497D45AE13D88C90E


I will be happy if you can help me publish my Token Logo Successfully For Me On Trust Wallet. Waiting for your reply soon.

Thanks

**Comment by Cryptocool1** [comment]
• What is the purpose of this token? How will it benefit Trust Wallet users?
 • How is the token being distributed? Are you conducting an airdrop?
 • Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?
 • Is the token listed on a centralized/decentralized exchange?
 • Is a Smart Contract audit completed? Where can we find this information?

**Comment by TellerUSD** [comment]
Follow-up on Logo Update Request for "TELLER USD" Project.

Dear Trustwallet/Assets,

We are eager to receive an update on the status of our pending logo update
request for our project "TELLER USD" on Trust Wallet. A positive response
confirming the successful update would be greatly appreciated today.

 Thank you for your attention. Best regards.

**Comment by TellerUSD** [comment]
Follow-up on Token Update Request - Urgent

Dear Trust Wallet,
I trust this message reaches you well. I previously emailed you on December
4th, 2023, concerning the update of my token. Regrettably, I have not
received a response, and the token update is still pending. Could you
please address the status of my project and provide details on the next
steps? A prompt response would be highly appreciated.

Thank you.
Best regards,
Jordan Hilton

**Comment by cryptomanz1** [comment]
are you listed on CoinMarketCap?

**Comment by TellerUSD** [comment]
No, we are not yet listed on Coinmarketcap.

How can you help us without been listed on Coinmarketcap? Because we are
facing  rejection issue when listing on Coinmarketcap due to the numbers of
listing request Coinmarketcap are receiving daily.

Waiting for your reply shortly.
Thanks

**Comment by TellerUSD** [comment]
Although we have been listed on several platforms like:

https://coinsniper.net/coin/56800

https://coinbrain.com/coins/bnb-0x4953d28b12d862250cc96163a9c46ae2b8ef52c5

https://coinmoonhunt.com/coin/Teller%20USD

https://www.coinscope.co/coin/1-usd

https://top100token.com/address/0x4953d28b12d862250cc96163a9c46ae2b8ef52c5

https://gemfinder.cc/gem/17251

https://coinsgods.com/coin/7244

https://coinbrain.com/coins/bnb-0x4953d28b12d862250cc96163a9c46ae2b8ef52c5

https://coincatapult.com/coin/teller-usd-usdt

https://coindiscovery.app/coin/teller-usd/overview

https://coinhunt.cc/coin/65579619461faf21864bb337

https://coinbrain.com/coins/bnb-0x4953d28b12d862250cc96163a9c46ae2b8ef52c5

https://moontok.io/coins/teller-usd

https://coinranking.com/coin/D92TtTt65+tellerusd-usdt

https://coinmooner.com/coin/teller-usd-usdt

We are yet to be listed on Coingecko and Coinmarketcap which will be our
next move after been approved here on Trust Wallet.

Your positive reply will be awaiting.

Thanks
Jordan Hilton
Official Mail: ***@***.***

**Comment by TellerUSD** [comment]
Hello Sir Please We are listed on cmc here is the link

https://coinmarketcap.com/currencies/safeworld/

**Comment by TellerUSD** [comment]
Logo Update Request for Teller USD (USDT) on Trust Wallet

Dear Trust Wallet Team,

I hope this message finds you well. We are requesting for chat re-open.
We wanted to inform you that Teller USD (USDT) has now been listed on
CoinMarketCap. You can find the CoinMarketCap link here:
https://coinmarketcap.com/currencies/safeworld

We kindly request you to go through this information, and we are eagerly
awaiting a successful logo update for Teller USD (TELLERUSD) on Trust
Wallet.

Thank you for your attention to this matter.

Best Regards

**Comment by TellerUSD** [comment]
Dear TrustWallet,
We're delighted with the recent progress in our project, having our logo
displayed seamlessly on Trust Wallet. However, we've observed that only the
logo has been updated, while the price and data are still pending.
We would greatly appreciate it if you could update the price and
synchronize data from CoinMarketCap:
https://coinmarketcap.com/currencies/safeworld

Looking forward to a prompt response.
Thanks.

**Comment by TellerUSD** [comment]
Dear TrustWallet,
We're delighted with the recent progress in our project, having our logo
displayed seamlessly on Trust Wallet. However, we've observed that only the
logo has been updated, while the price and data are still pending.
We would greatly appreciate it if you could update the price and
synchronize data from CoinMarketCap:
https://coinmarketcap.com/currencies/safeworld

Looking forward to a prompt response.
Thanks.

**Comment by TellerUSD** [comment]
Kindly help update Teller USD price on TrustWallet.
Thanks

**Comment by TellerUSD** [comment]
Can you keep your integrity safe? We have paid for getting listing on
TrustWallet, we have also exceed the criteria for listing but still yet you
didn’t update our price. Can you tell me what’s going on here ?

Kindly help update Teller USD price on TrustWallet.
Thanks

**Comment by TellerUSD** [comment]
Request for Teller USD Price Update on TrustWallet

Dear TrustWallet Support,
It has been a while since we reached out to request an update for our
Teller USD price on your platform.

Unfortunately, we haven't received a response yet.

We'd like to bring to your attention that we are officially listed on
Coinmarketcap, Azbit, and Tokpie.
https://coinmarketcap.com/currencies/safeworld


We kindly request you to review and update our Teller USD price on your
platform as it holds significance for our progress.

Your prompt attention to this matter is highly appreciated.

Thank you.
Best Regards

**Comment by Cryptocool1** [comment]
Hello, the price will be enabled soon

**Comment by TellerUSD** [comment]
Follow-up on Teller USD Price Update

Dear TrustWallet Support,
Thank you for your response.

It has been over a month since you mentioned that the price would be
updated, but we have not seen the changes reflected yet. Could you please
provide a specific timeframe or date when we can expect the updated Teller
USD price to start showing on TrustWallet?

Your prompt attention to this matter is highly appreciated, and we look
forward to your timely response.

 Thank you.
 Best Regards

**Comment by TellerUSD** [comment]
please update teller usd price on trust wallet. What’s causing the delay ?

**Pull request merged**
