### PR TITLE
Add IDM Token (BEP20)

### PR DESCRIPTION
**Pull request by idmtoken**
Adding info for BEP20 token 'IDM Token'.

PR created by <a href="https://assets.trustwallet.com">TW Assets Management</a>

### CODE REVIEW

**Comment by ramsty** [comment]
Hi!
Could you answer some questions?
• What is the purpose of this token? How will it benefit Trust Wallet users?
• How is the token being distributed? Are you conducting an airdrop?
• Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?
• Is the token listed on a centralized/decentralized exchange?
• Is a Smart Contract audit completed? Where can we find this information?

**Comment by idmtoken** [comment]
Namely digitizing cooperatives and MSMEs throughout Indonesia, both digital financial management and Market Place products. We want user to hold IDM on Trustwallet. Now there are about 6000 holders and the market cap is about 2 million USD.

We distribution using presale platform ( Pinksale ).

We sold using presale in platform Pinksale.app

The token has been already listed on Pancakeswap.

The IDM smart-contract is audited by Certik. You can find out here: https://www.certik.org/projects/idmtoken

**Comment by ramsty** [comment]
Your Smart Contract audit in progress.

**Comment by ramsty** [comment]
Awaiting for smart contract audit. On hold for now.

**Comment by Cryptocool1** [comment]
Please come back to us when all criteria are met.
When creating a new PR make sure to mention this PR, so that we can see that fee has been paid already here.

**Comment by idmtoken** [comment]
> Awaiting for smart contract audit. On hold for now.

hello,
here is smart contract audit
https://www.certik.com/projects/idmtoken

**Comment by idmtoken** [comment]
> Please come back to us when all criteria are met.
> 
> When creating a new PR make sure to mention this PR, so that we can see that fee has been paid already here.


hello,
the smart-contract onboarded in certik
https://www.certik.com/projects/idmtoken

**Comment by Mig112344** [comment]
> Awaiting for smart contract audit. On hold for now.


Smart-contract has finish audit 
https://www.certik.com/projects/idmtoken

**Pull request merged**
