### PR TITLE
TitsV2 token information

### PR DESCRIPTION
**Pull request by dimage2299**

### CODE REVIEW

**Comment by ramsty** [comment]
Hi!
Could you answer some questions?
• What is the purpose of this token? How will it benefit Trust Wallet users?
• How is the token being distributed? Are you conducting an airdrop?
• Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?
• Is the token listed on a centralized/decentralized exchange?
• Is a Smart Contract audit completed? Where can we find this information?

**Comment by dimage2299** [comment]
Hi we are a philanthropy token that launched over 4 months ago. Many of our 12k holders use trust wallet as their main web wallet and have asked us to submit the token logo. We did not do any type of presale or ICO - it was fair launched. We are listed on Pancakeswap V2.

**Comment by ramsty** [comment]
Is a Smart Contract audit completed? Where can we find this information?

**Comment by dimage2299** [comment]
I have uploaded our audit to this PR - please let me know of any other information needed

**Pull request merged**
