### PR TITLE
DRF

### PR DESCRIPTION
**Pull request by DefiRoboticsFinance**
THIS IS A TOKEN NAME

### CODE REVIEW

**Comment by DefiRoboticsFinance** [comment]
ITS MY TOKEN NAME

**Comment by DefiRoboticsFinance** [comment]
its just my token

**Comment by catenocrypt** [comment]
As per our policy, brand new tokens are not included, there is a minimum requirement of 5000 holder addresses and 10000 transactions, in order to filter out scam tokens.
See the criteria at (mentioned in the first message by the bot): https://community.trustwallet.com/t/how-to-submit-a-token-logo/3863#how-to-get-approved
This token has minimal usage yet (8 holders). Rejecting PR for now. Please come back to us when all criteria are met.

https://etherscan.io/token/0x9Bd6427C497f80115a166c2ec8000646F25d9C12

**Pull request closed without merging**
