### PR TITLE
Add WHIRL logo and info

### PR DESCRIPTION
**Pull request by whirlfinance**

### CODE REVIEW

**Comment by Iamdeadlyz** [comment]
As per our policy, brand new tokens are not included. There is a minimum requirement of 2500 holder addresses and 5000 transactions (airdropped tokens excluded) in order to filter out scam tokens. See the criteria at (mentioned in the first message by the bot): https://community.trustwallet.com/t/how-to-submit-a-token-logo/3863#how-to-get-approved

This token has below-limit usage yet. Also, the domain (http://whirlfinance.com/) is suspended, need more info. This pull request will be put on hold.

**Comment by whirlfinance** [comment]
HI Trustwallet/Assets,

We just surpassed 2500 holders requirement.

https://bscscan.com/token/0x7f479d78380ad00341fdd7322fe8aef766e29e5a


Best,

Whirl Finance Team

**Comment by whirlfinance** [comment]
and whirl logo is new now, should I resubmit?

**Comment by catenocrypt** [comment]
Circulation requirement is satisfied now.
However, we were still not able to check the website -- https://www.whirlfinance.com/ does not load.  Can you comment?

**Comment by whirlfinance** [comment]
This is our new domain www.whirl-finance.com

**Comment by whirlfinance** [comment]
This is our new logo also

**Comment by whirlfinance** [comment]
and here's our new logo

**Comment by catenocrypt** [comment]
Please update the website in the included info.json file and also the logo (files in the PR, not attached as comment)

**Comment by whirlfinance** [comment]
Done updated

**Comment by mhondz** [comment]
Whirlfinance fix this 2 error

**Comment by whirlfinance** [comment]
Hi what would be the requirement for price visibility in trustwallet for
Whirl Token?

**Comment by mhondz** [comment]
Hi catenocrypt | dev team,

When Whirl details & price will be displayed on the app?

**Pull request merged**
