### PR TITLE
dotmoovs logo change

### PR DESCRIPTION
**Pull request by jpelizza**
Chaging dotmoovs logo on ethereum and bsc chains

### CODE REVIEW

**Comment by cryptomanz** [comment]
As per our policy, brand new tokens are not included, there is a minimum requirement of 25,000 holder addresses and 50,000 transactions, in order to filter out scam tokens.
See the criteria at : https://developer.trustwallet.com/assets/requirements .

**Comment by JoaoPelizza** [comment]
Dotmoovs is listed on trustwallet already, we had a logo rebranding and it needs to be updated, appreciated.

**Comment by Cryptocool1** [comment]
Submission looks good, awaiting for fee payment

**Comment by JoaoPelizza** [comment]
Hi, apologies for the delay, could you reopen this PR so we can complete the payment?

**Pull request closed without merging**
