### PR TITLE
Add Token Compound (erc20)

### PR DESCRIPTION
**Pull request by KunKax**
This PR is being closed due to inactivity. If you wish to continue, please have us reopen the PR before sending your payment.
Do NOT send payments for closed PR, as the fee may by lost!
  (60 vs. 60 hrs)

### CODE REVIEW

**Review by KunKaxx — APPROVED** [review]
Ok

**Comment by KunKax** [comment]
bnb156xkklandl3f7nlmkrwmqz2d8ycmxt926pp0edV
Dex Explorer 
  
|  
|   |  
Dex Explorer
 
Binance Dex Explorer
  |   |

  |

  
A long time ago I send it with my address which address I signed my account in Trust app to my address I signed account in Binace (   Important  this is right memo ) let see it . but I can’t get it for along time . And in finally you see another address in Binance get it . So funny :)) 

say every people send with ERC20? 
How can anorther address can get it back :)) good luck to you. I don’t have this tokens more. I hope this address get it must do right , this TWT-8C2 will protect Binance have a nice day. Thank for close my order. 
Được gửi từ Yahoo Mail cho iPhone


Vào Thứ Hai, tháng 3 1, 2021, 9:20 SA, merge-fee-bot[bot] <notifications@github.com> đã viết:




Fee has not been received yet (or not fully).

Rejected transactions:

| amount | memo | rejected? | time | from | txID |
| 250 TWT | 5758 | Wrong memo | 2021-03-01T00:11:25.054Z | bnb1jxfh2g85q3v0tdq56fnevx6xcxtcnhtsmcu64m | 0D124215EE1656847F06EF1BA307BF52F76605F6B412DA0AFC8C0FC0364B0733 |
| 250 TWT | 5755 | Wrong memo | 2021-02-28T20:25:44.270Z | bnb1jxfh2g85q3v0tdq56fnevx6xcxtcnhtsmcu64m | D085976912EF6FF0D8B363ED0C2EF54C5A41E70FCECE913A62C8A35270695A7C |
| 250 TWT | 5758 | Wrong memo | 2021-03-01T00:11:25.054Z | bnb1jxfh2g85q3v0tdq56fnevx6xcxtcnhtsmcu64m | 0D124215EE1656847F06EF1BA307BF52F76605F6B412DA0AFC8C0FC0364B0733 |
| 250 TWT | 5755 | Wrong memo | 2021-02-28T20:25:44.270Z | bnb1jxfh2g85q3v0tdq56fnevx6xcxtcnhtsmcu64m | D085976912EF6FF0D8B363ED0C2EF54C5A41E70FCECE913A62C8A35270695A7C |

**Comment by catenocrypt** [comment]
@KunKax , you mean you have paid the fee for this PR?  If so, please provide TXID for verification.

**Comment by nguyenducsang** [comment]
Địa

**Comment by nguyenducsang** [comment]
Y

**Comment by nguyenducsang** [comment]
Đi

**Pull request closed without merging**
