### PR TITLE
Add Capitalrock (BEP20)

### PR DESCRIPTION
**Pull request by erience**
Adding info for BEP20 token 'Capitalrock'.

### CODE REVIEW

**Comment by erience** [comment]
CMC: https://coinmarketcap.com/currencies/capitalrock/
Audit Report: https://capitalrock.ch/audit.pdf

LBank Exchange: https://www.lbank.com/en-US/trade/cr_usdt/
Dex-Trade Exchange: https://dex-trade.com/spot/trading/CRUSDT
Coinsbit Exchange: https://coinsbit.io/trade/CR_USDT
Tokpie Exchange: https://tokpie.com/view_exchange/CR-USDT
Azbit Exchange: https://azbit.com/exchange/CR_USDT

**Review by Jking2119 — COMMENTED** [review]
Approve

**Comment by erience** [comment]
@Cryptocool1 and @cryptomanz1 : Any update

**Comment by cryptomanz1** [comment]
• What is the purpose of this token? How will it benefit Trust Wallet users?
 • How is the token being distributed? Are you conducting an airdrop?
 • Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?
 • Is the token listed on a centralized/decentralized exchange?
 • Is a Smart Contract audit completed? Where can we find this information?

**Comment by erience** [comment]
**Q: What is the purpose of this token? How will it benefit Trust Wallet users?**
**A:** Capital Rock Coin is a dynamic cryptocurrency introduced by the renowned forex trading firm, Capital Rock. With a global presence, boasting physical offices in ten countries, and an impressive portfolio of simultaneous dealings with 400 companies, Capital Rock Coin represents a powerful and innovative financial asset in the world of digital currencies. Trust wallet being non custodial waller will allows users to utilize the power of CapitalRock in a non custodial wallet. 

**Q: How is the token being distributed? Are you conducting an airdrop?**
**A:** No Airdrop. DEX & CEX Purchase

**Q: Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?**
**A:** 3 Months ago ICO took place for a limited number of Participants.

**Q:** Is the token listed on a centralized/decentralized exchange?
LBank Exchange: https://www.lbank.com/en-US/trade/cr_usdt/
Dex-Trade Exchange: https://dex-trade.com/spot/trading/CRUSDT
Coinsbit Exchange: https://coinsbit.io/trade/CR_USDT
Tokpie Exchange: https://tokpie.com/view_exchange/CR-USDT
Azbit Exchange: https://azbit.com/exchange/CR_USDT

**Q: Is a Smart Contract audit completed? Where can we find this information?**
Audit Report: https://capitalrock.ch/audit.pdf
CMC: https://coinmarketcap.com/currencies/capitalrock/

**Comment by erience** [comment]
@cryptomanz1 : Any update ?

**Comment by atifnimran** [comment]
eadaf9ce7656519efcbde9db192db00395b6cc25

**Pull request merged**
