### PR TITLE
add to SXC token info to TWT

### PR DESCRIPTION
**Pull request by Socialxclub**
This is my request to please add to socialxclub project (SXC) his logo.png. Thanks in advance.

### CODE REVIEW

**Comment by Socialxclub** [comment]
Msent

**Comment by Socialxclub** [comment]
need help

**Comment by cryptomanz1** [comment]
Correction needed:
This is a BEp20 token, correct folder is blockchains/smartchain/assets. Please correct.

**Comment by Cryptocool1** [comment]
As per our policy, brand new tokens are not included, there is a minimum requirement of 10,000 holder addresses and 15,000 transactions, in order to filter out scam tokens.
See the criteria at : https://developer.trustwallet.com/assets/requirements .

**Comment by Socialxclub** [comment]
Hi CryptoA,Thank you for the reply. i understand the 10,000 holders  but in this market and on eth network, its almost impossbile to reach. Im the founder of socialxclub (SXC) token, me and my team worked 3 months to build this project even before launch,we invested a lot of time and effort.Our community waiting for a logo on trust wallet and we try our best to do so, please help.We can put turstwallet  logo on our site first thing you will  see when you enter also As you can see we built our own :Swap - https://socialxclub.org/swap/NFTdapp - https://nft.socialxclub.org/site - https://socialxclub.org/social platform - https://socialxclub.org/sc/medium - ***@***.*** - https://github.com/Socialxclub/meta chat - https://socialxclub.org/chattwitter more then 100 followers - https://twitter.com/socialclubcryptwe got over 490 holders and more then 400 community members in telegram can get throw our portal ( https://t.me/socialclubportal)please help us out, we done a lot and without logo in trustwallet this project will fail.please !thanks in advance. 
      
        
        
          On Oct 16 2022, at 10:34 am, CryptoA ***@***.***> wrote:
          
        
        
          
As per our policy, brand new tokens are not included, there is a minimum requirement of 10,000 holder addresses and 15,000 transactions, in order to filter out scam tokens.
See the criteria at : https://developer.trustwallet.com/assets/requirements .

**Pull request closed without merging**
