### PR TITLE
Add PesaChain

### PR DESCRIPTION
**Pull request by GN-Stephen**

### CODE REVIEW

**Comment by zachzwei** [comment]
Unable to edit the submission. Please move the folder to ethereum\assets

**Comment by GN-Stephen** [comment]
Can't find ethereum\assets folder please provide URL


 
 
  On Sun, 19 Jul 2020 at 18:45, Andrew M<notifications@github.com> wrote:   


Unable to edit the submission. Please move the folder to ethereum\assets

**Comment by GN-Stephen** [comment]
upload to ethereum/assets requires push access..

**Comment by zachzwei** [comment]
created new PR
https://github.com/trustwallet/assets/pull/2812

**Comment by catenocrypt** [comment]
Merged #2812 instead.

**Pull request closed without merging**
