### PR TITLE
Add ZELWIN (BEP20)

### PR DESCRIPTION
**Pull request by mostermas**
Adding info for BEP20 token 'ZELWIN'.

PR created by <a href="https://assets.trustwallet.com">TW Assets Management</a>

### CODE REVIEW

**Comment by cryptomanz** [comment]
• What is the purpose of this token? How will it benefit Trust Wallet users?
 • How is the token being distributed? Are you conducting an airdrop?
 • Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?
 • Is the token listed on a centralized/decentralized exchange?
 • Is a Smart Contract audit completed? Where can we find this information?

**Comment by mostermas** [comment]
*• What is the purpose of this token? How will it benefit Trust Wallet
users?*
Zelwin has built a huge ecosystem between real sector of economics and
digital assets.

ZELWIN's Ecosystem:
Zelwin.finance - Launchpad for IDO & INO

Ex.Zelwin.com - Simple Сrypto Exchange

Zelwin.com - Crypto-friendly Marketplace of Goods

Zelwin Staking - Special earning program for ZLW holders and participants
on IDOs

Zelwin Bridge - The easiest way to exchange ZLW tokens between different
chains:
Ethereum (ERC20), Binance Smart Chain (BEP-20), Polygon (ex. Matic Mainnet).

Zelwin IDO - Exclusive access to public rounds of promising crypto projects
Zelwin is created the useful & simple platform for crypto IDOs (Initial
Decentralized Offerings) and INOs (Initial NFT offerings).

For early-stage crypto projects to raise capital to IDO participants,
providing a chance to invest in a project early. And earnings programs for
ZLW holders.

*• How is the token being distributed? Are you conducting an airdrop?*
It was created 2 years ago and starter as fair launch on exchanges
*• Did you sold the tokens at an Initial Coin Offering (ICO) or a token
presale?*
#ZLW token started at  per token on May, 2020 on exchanges
*• Is the token listed on a centralized/decentralized exchange?*
Exchanges:

PancakeSwap, Gate.io, DigiFinex, Probit, BitForex, Coinsbit, Hotbit

Verified circulation supply on CoinMarketCap:

https://coinmarketcap.com/currencies/zelwin/


*• Is a Smart Contract audit completed? Where can we find this information?*
https://github.com/HashEx/public_audits/blob/master/zelwin-token/Zelwin%20token%20report.pdf



вс, 8 мая 2022 г. в 14:29, Nazar ***@***.***>:

**Comment by cryptomanz** [comment]
hello, we require smart contract audit from reputable companies such as : Hacken, Certik, Techrate, Dessert Finance

**Comment by cryptomanz** [comment]
Please come back to us once all criteria are met

**Comment by cryptomanz** [comment]
Make sure to mention this PR so the fee can be reused

**Comment by mostermas** [comment]
I added logo to 3 another coins and that is first time you ask so many
questions, why?

пт, 13 мая 2022 г., 06:50 Nazar ***@***.***>:

**Comment by Cryptocool1** [comment]
You can see all our requirements here: https://developer.trustwallet.com/assets/requirements

**Comment by mostermas** [comment]
That is token with 2 years history, not just created meme coin.

пт, 13 мая 2022 г., 11:17 CryptoA ***@***.***>:

**Comment by mostermas** [comment]
Socenteam is ok?

пт, 13 мая 2022 г., 11:19 MAD MAX ***@***.***>:

**Comment by Cryptocool1** [comment]
> Socenteam is ok? пт, 13 мая 2022 г., 11:19 MAD MAX ***@***.***>:
> […](#)

Please see reputable companies above ( comment from Crypromanz)

**Comment by mostermas** [comment]
https://github.com/sokenteam/smart_contract_audits/blob/main/Zelwin%20Standard%20Smart%20Contract%20Audit.pdf

This project is 2 years old with existing product, have you check the site.

We have 2 audits.
We listed on all sites like CMC, CG, Livecoinwatch, etc.

10k holders, 2 years history.
And making one more expensive audit only for you? Come on.

Please give us 5-10 minutes of your time and check project and you will
see.


пт, 13 мая 2022 г., 12:19 CryptoA ***@***.***>:

**Pull request closed without merging**
