### PR TITLE
Add logo for $ElonGate

### PR DESCRIPTION
**Pull request by agambon**
First pull request to add logo for $ElonGate to TrustWallet. $ElonGate is a BSC token that is making significant contributions to charity via a deflationary cryptocurrency.

### CODE REVIEW

**Comment by agambon** [comment]
We verified all acceptance criteria, and submitted the 2 BNB fee. Please review and confirm.

**Comment by catenocrypt** [comment]
Fee is not seen, please provide TXID

**Comment by catenocrypt** [comment]
Correction needed: chnage ID field in info.json to be in checksum format, exactly as the folder name.

**Comment by agambon** [comment]
I fixed the stuck transaction fee - your bot confirmed receipt.
Hoping you can briefly help. I edited the json as required, but Pull
Request results on "compare changes". How do I submit a fresh pull request?

**Comment by catenocrypt** [comment]
Payment considered for #6215, closing

**Pull request closed without merging**
