### PR TITLE
Add TWT logo and info

### PR DESCRIPTION
**Pull request by FightUntilDeath**
request to add logo and info for FightUntilDeath to trust wallet

### CODE REVIEW

**Comment by FightUntilDeath** [comment]
> No token files found. If you try to add/modify a token, check the name and location of your files! Logo file must be named exactly 'logo.png'. If you are not adding a token, ignore this message.

added new logo.png in file

**Comment by FightUntilDeath** [comment]
Added the logo named  logo.png

**Comment by Cryptocool1** [comment]
Please create new PR, follow doc https://developer.trustwallet.com/assets/requirements
You may want to try our Assets app in beta; go to https://assets.trustwallet.com, log on with Github, enter contract ID, logo and some additional info, and it will create a PR for you.
See https://developer.trustwallet.com/assets/repository_details

**Comment by FightUntilDeath** [comment]
I will do that  this afternoon, thank you!

**Pull request closed without merging**
