### PR TITLE
Add info for w3binfinity 

### PR DESCRIPTION
**Pull request by w3bin**
Add info for w3binfinity

### CODE REVIEW

**Comment by w3bin** [comment]
The requirement had met on my v1 contract. Please check
https://github.com/trustwallet/assets/pull/21670
@cryptomanz1

**Comment by w3bin** [comment]
The requirement had met on my v1 contract. Please check @Cryptocool1
https://github.com/trustwallet/assets/pull/21670

**Comment by Cryptocool1** [comment]
your v1 token is not listed on Trust Wallet

**Comment by w3bin** [comment]
> your v1 token is not listed on Trust Wallet, and now you are adding v2 that is not met our criteria

My v1 token don't have data track on CoinMarketCap, but now we use V2 that met the CoinMarketCap condition. And V1 holders can free to swap to our V2 token. So I think It is same. You can check more information on my website.

**Comment by Cryptocool1** [comment]
Unfortunately that is 2 different tokens. Please come back to us uncle all criteria are met. You fee still can be reused. 
Thank you

**Pull request closed without merging**
