### PR TITLE
we reached 2500 users

### PR DESCRIPTION
**Pull request by catecoins**
we reach 2.5 k users

### CODE REVIEW

**Comment by catecoins** [comment]
Swap from old to new contract - 

https://twitter.com/cateclub/status/1410241060085800963

**Comment by catecoins** [comment]
Logo is still not visible in Token in PR: BEP20
 0x451329F2FCb88C398A4cDD4A8a98780B4D62873C

**Comment by Cryptocool1** [comment]
> Logo is still not visible in Token in PR: BEP20
> 0x451329F2FCb88C398A4cDD4A8a98780B4D62873C

Hello, it can take up to 48h, please wait

**Comment by catecoins** [comment]
Thanks for replying, 
I just want to confirm that logo and token info will be visible for  a new contract 
so that users can easily search and add as they are confused about this
last time everything happened in 2-3 hour

**Pull request merged**
