### PR TITLE
add coin

### PR DESCRIPTION
**Pull request by ghost**

### CODE REVIEW

**Comment by Cryptocool1** [comment]
As per our policy, brand new tokens are not included, there is a minimum requirement of 2500 holder addresses and 5000 transactions, in order to filter out scam tokens.
See the criteria at (mentioned in the first message by the bot): https://community.trustwallet.com/t/how-to-submit-a-token-logo/3863).

**Comment by edrti** [comment]
We met these requirements. 2542 holders and 77235 transactions.

**Comment by pablohodl** [comment]
We met all these requirements. 2542 holders and 77235 transactions.

**Comment by Cryptocool1** [comment]
Can you please answer some questions?
•	What is the purpose of this token? How will it benefit Trust Wallet users?
	•	How is the token being distributed? Are you conducting an airdrop?
	•	Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?
	•	Is the token listed on a centralized/decentralized exchange?
	•	Is a Smart Contract audit completed? Where can we find this information?

**Comment by pablohodl** [comment]
• What is the purpose of this token? - 
iBNB is the first dynamic DeFi token, with a reward pool generating protocol built on the Binance Smart Chain. It aims to fix the volume-to-BNB pool refill rate that has seen other tokens lose value during sustained periods of low volume.  The purpose of our token is to provide users a sustained way to earn passive income on their initial investment. 

•How will it benefit Trust Wallet users?
Our Token will benefit Trust Wallet users by allowing them to diversify their portfolios with confidence knowing they can exepct sustainable manually claimed BNB rewards.  

• How is the token being distributed? Are you conducting an airdrop? 
Our token is avilable on PancakeSwap. no we are not conducting an airdrop.
 
• Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?
Yes, we sold the Token at an initial coin offering / presale. 

• Is the token listed on a centralized/decentralized exchange?
Yes, Pancake swap. 

• Is a Smart Contract audit completed? Where can we find this information?
Yes,  a Smart contract audit is complete and can be found here: https://ibnb-finance.gitbook.io/ibnb-whitepaper/audit

**Comment by pablohodl** [comment]
?

**Comment by Cryptocool1** [comment]
please create new PR when your token will be listed on CMC
make sure to mention this PR so that fee can can be reused

**Pull request closed without merging**
