### PR TITLE
add lovedoge logo and info

### PR DESCRIPTION
**Pull request by nobodyyc**
add lovedoge logo and info

### CODE REVIEW

**Comment by Cryptocool1** [comment]
hello,
can you answer some questions?
• What is the purpose of this token? How will it benefit Trust Wallet users?
 • How is the token being distributed? Are you conducting an airdrop?
 • Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?
 • Is the token listed on a centralized/decentralized exchange?
 • Is a Smart Contract audit completed? Where can we find this information?

**Comment by nobodyyc** [comment]
> hello,
> can you answer some questions?
> • What is the purpose of this token? How will it benefit Trust Wallet users?
> • How is the token being distributed? Are you conducting an airdrop?
> • Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?
> • Is the token listed on a centralized/decentralized exchange?
> • Is a Smart Contract audit completed? Where can we find this information?

hello,
1. LoveDoge announces the next evolution of revenue generation and deflation on the Binance Smart Chain. This mechanism will deduct a 10% tax on each transaction and incentivize token holders to hold to receive dividends from the transaction (buy and sell). The reallocation is based on the percentage (in the contract), the current token balance and the number of holders' equity.
Holders will get more tokens.
2. Total supply: 1,000,000,000,000,000, airdrop 10%, pre-sale 23%, liquidity 23%%, burning 44%
3. Yes, we have pre-sold a total of 158 BNB
4. We added liquidity to pancakeswap and locked the liquidity pool. This is the proof: https://app.unicrypt.network/amm/pancake-v2/pair/0x26cd891db38c6c89681240693c3b2f466b81a19f
5. This is the link to the security audit report  https://github.com/TechRate/Smart-Contract-Audits/blob/main/LoveDoge.pdf

**Comment by cryptomanz** [comment]
"Holders will get more tokens."
how will they get?

**Comment by nobodyyc** [comment]
> "Holders will get more tokens."
> how will they get?

Evolved from HODL and GhostFace, transaction fees are charged for each purchase and sale order, and holders of more than 100,000,000,000 tokens can visit the website to receive these rewards. 
The tokens rewarded to holders depend on the number of tokens they hold and the current transaction volume.
50% of the current pool will be allocated every day, and the rest will be accumulated to the next collection day.
The user holds the tokens and can then claim them on the website, and they will be distributed directly to the user's wallet.
Link to receive reward https://lovedoge.io/recieve

**Comment by nobodyyc** [comment]
> "Holders will get more tokens."
> how will they get?

The token contract adopts a static reward system. 10% of each transaction is taxed and is divided into three parts:

-6% of tokens will be redistributed to holders

-2% Perpetual deflation (tokens are destroyed)

-2% marketing

**Comment by Cryptocool1** [comment]
can you please add links to your PR?
example: https://developer.trustwallet.com/add_new_asset#info-json-contents

**Comment by nobodyyc** [comment]
> can you please add links to your PR?
> example: https://developer.trustwallet.com/add_new_asset#info-json-contents

Hello,
I have added a link in the info.json file

**Comment by cryptomanz** [comment]
wat aboutcoin gecko https://www.coingecko.com/en/coins/love-doge
why don't add it?

**Comment by nobodyyc** [comment]
> what about coingecko https://www.coingecko.com/en/coins/love-doge
> why don't add it?

Okay, I will fill in more links.

**Comment by nobodyyc** [comment]
> what about coingecko https://www.coingecko.com/en/coins/love-doge
> why don't add it?

hello
We added coingecko, discord and reddit links

**Pull request merged**
