### PR TITLE
Add FutureToken (BEP20)

### PR DESCRIPTION
**Pull request by nazim099**
Adding info for BEP20 token 'FutureToken'.

PR created by <a href="https://assets.trustwallet.com">TW Assets Management</a>

### CODE REVIEW

**Comment by nazim099** [comment]
helo

**Comment by nazim099** [comment]
logo show is happening

**Comment by Cryptocool1** [comment]
• What is the purpose of this token? How will it benefit Trust Wallet users?
 • How is the token being distributed? Are you conducting an airdrop?
 • Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?
 • Is the token listed on a centralized/decentralized exchange?
 • Is a Smart Contract audit completed? Where can we find this information?

**Comment by future982** [comment]
Exchange 1 :  https://www.toobit.com/en-US/spot/FTR_USDT
Exchange 2 :  https://azbit.com/exchange/FTR_USDT

Audit :  https://www.cyberscope.io/audits/1-ftr

**Comment by future982** [comment]
Please Checkout whitepaper : https://www.futuretoken.info/Content/home/FTR_Token_whitepapper.pdf

**Comment by nazim099** [comment]
exchange :  https://www.toobit.com/en-US/spot/FTR_USDT

**Comment by nazim099** [comment]
exchange 2:  https://azbit.com/exchange/FTR_USDT
smart contract audit : https://www.cyberscope.io/audits/1-ftr
whitepaper : https://www.futuretoken.info/Content/home/FTR_Token_whitepapper.pdf

**Comment by nazim099** [comment]
Why my token logo is showing, i have done everything already.. Please Reply..

**Comment by Cryptocool1** [comment]
Hello, 
Please provide answer for those questions:
• What is the purpose of this token? How will it benefit Trust Wallet users?
• How is the token being distributed? Are you conducting an airdrop?
• Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?

**Comment by future982** [comment]
The Purpose of Future Token 'Make Defi Transactions Easy by using Future Token'. Users typically engage with DeFi via software called dapps (“decentralized apps”), most of which currently run on the Ethereum blockchain. 
Trust Wallet Users can use easily Defi by using Future Token.

We are not conducting any Airdrop, Distribution of token is being Buy and Sell, Our Token is already listed in many exchanges.

We are not sold any token in ICO and Presale.

**Comment by nazim099** [comment]
The Purpose of Future Token 'Make Defi Transactions Easy by using Future Token'. Users typically engage with DeFi via software called dapps (“decentralized apps”), most of which currently run on the Ethereum blockchain.
Trust Wallet Users can use easily Defi by using Future Token.

We are not conducting any Airdrop, Distribution of token is being Buy and Sell, Our Token is already listed in many exchanges.

We are not sold any token in ICO and Presale.

**Comment by nazim099** [comment]
Please Check and Do it Quickly..

**Comment by nazim099** [comment]
Please Check and Do it Quickly.. ???

**Comment by nazim099** [comment]
???

**Comment by future982** [comment]
????

**Comment by nazim099** [comment]
any problem

**Comment by nazim099** [comment]
helo please check

**Pull request merged**
