### PR TITLE
Add HyperChainX (BEP20)

### PR DESCRIPTION
**Pull request by xcyberdragonx**
Adding info for BEP20 token 'HyperChainX'.

PR created by <a href="https://assets.trustwallet.com">TW Assets Management</a>

### CODE REVIEW

**Comment by cryptomanz1** [comment]
As per our policy, brand new tokens are not included, there is a minimum requirement of 10,000 holder addresses and 15,000 transactions, in order to filter out scam tokens.
See the criteria at : https://developer.trustwallet.com/assets/requirements .

**Comment by xcyberdragonx** [comment]
> As per our policy, brand new tokens are not included, there is a minimum requirement of 10,000 holder addresses and 15,000 transactions, in order to filter out scam tokens. See the criteria at : https://developer.trustwallet.com/assets/requirements .

We have been listed here on trustwallet github for about two years, maybe two years already. So this should actually be a migration. Not all have migrated on-chain, we are on exchanges too. We have been on coinmarketcap and coingecko for about 2 years already.

#13375 #7532  (these are the previous pull requests I could find). @cryptomanz1 @Cryptocool1

**Comment by Cryptocool1** [comment]
Please send here your old contract address

**Comment by xcyberdragonx** [comment]
> Please send here your old contract address

0x0469F8Ca65Ce318888cc0d6459d0c7cbe5912c98

**Comment by cryptomanz1** [comment]
can you send an official announcement about migration?

**Comment by xcyberdragonx** [comment]
> can you send an official announcement about migration?

https://hyperchainx.gitbook.io/migration
https://www.hypertokenmigration.com/

In our telegram you can paste /migration and it will take you to appropriate website.

I can make a new announcement on any social platform if that is needed too @cryptomanz1 @Cryptocool1

**Comment by cryptomanz1** [comment]
#23894

**Pull request merged**
