### PR TITLE
Add Carypto (BEP20)

### PR DESCRIPTION
**Pull request by gangnam85**
Adding info for BEP20 token 'Carypto'.

PR created by <a href="https://assets.trustwallet.com">TW Assets Management</a>

### CODE REVIEW

**Comment by Cryptocool1** [comment]
• What is the purpose of this token? How will it benefit Trust Wallet users?
 • How is the token being distributed? Are you conducting an airdrop?
 • Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?
 • Is the token listed on a centralized/decentralized exchange?
 • Is a Smart Contract audit completed? Where can we find this information?

**Comment by gangnam85** [comment]
• What is the purpose of this token? How will it benefit Trust Wallet users?
  - Token economy for M2E Movie to Earn platform.

• How is the token being distributed? Are you conducting an airdrop?
  - Event AirDrop and games are being paid

• Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?
  - pre-sale is under way.

• Is the token listed on a centralized/decentralized exchange?
  - The token listing will proceed

• Is a Smart Contract audit completed? Where can we find this information?
  - Smart contract audit will be carried out

**Comment by cryptomanz** [comment]
Awaiting for smart contract audit.

**Comment by Cryptocool1** [comment]
Feel free to create new PR, once all criteria are completed. Make sure to mention this PR so the fee can be reused.

**Pull request closed without merging**
