### PR TITLE
Add CCN (BEP20)

### PR DESCRIPTION
**Pull request by ccnnetworkco**
Adding info for BEP20 token 'CCN'.

PR created by <a href="https://assets.trustwallet.com">TW Assets Management</a>

### CODE REVIEW

**Comment by ccnnetworkco** [comment]
Hello
The CCN audit request was released without any problems
The Audit link is : 
https://dessertswap.finance/recentaudits.html
https://dessertswap.finance/audits/CCN-BSC-Audit-18070607.pdf
We have made three payments to request listing of assets.
Please review our request.

**Comment by ccnnetworkco** [comment]
Hello,
**• What is the purpose of this token? How will it benefit Trust Wallet users?**
The token will belong to a television network, and will be used for our dedicated NFT market, reducing a very large percentage of NFT fees for trusted users.We also want to prevent many losses for traders by informing the news and other factors affecting the market in a timely manner.

**• How is the token being distributed? Are you conducting an airdrop?**
Yes, we have AirDrop and over 70,000 people have joined our AirDrop, but we have not distributed any AirDrop tokens yet.
and the tokens that have been distributed have been either through the sale of the ICO or through the pre-sale.

**• Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?**
Yes, we are in the process of selling the ICO

**• Is the token listed on a centralized/decentralized exchange?**
No, we have not yet been officially listed by the developer team in any exchange, because we are in the ICO stage, but some users have created liquidity in some decentralized exchanges.

**• Is a Smart Contract audit completed? Where can we find this information?**
The CCN audit request was released without any problems
The Audit link is :
https://dessertswap.finance/recentaudits.html
https://dessertswap.finance/audits/CCN-BSC-Audit-18070607.pdf

We have made three payments on request #20474 #20482 #20611 to request listing of assets.

**Comment by Cryptocool1** [comment]
Hello, your Market data is untracked on CoinMarketCap

**Comment by ccnnetworkco** [comment]
Hello
I am very grateful for your attention
Yes, we listed our tokens untracked so that we could use the ico and airdrop features of the coinmarketcap website.
And because we are in the ico stage, it is not possible for us to track the price

**Comment by Cryptocool1** [comment]
Your market data should be tracked

**Comment by ccnnetworkco** [comment]
You can see our price at the address below
https://geckoterminal.com/bsc/pools/0x71cfd2e1dd346353dd7b0477b4a4a85241fd48a0

**Comment by ccnnetworkco** [comment]
My token price is now show in coinmarketcap 
https://coinmarketcap.com/currencies/cryptocurrencynetwork/

**Pull request merged**
