### PR TITLE
Add Nodewaves (POLYGON)

### PR DESCRIPTION
**Pull request by zahidgopang**
Adding info for POLYGON token 'Nodewaves'.

PR created by <a href="https://assets.trustwallet.com">TW Assets Management</a>

### CODE REVIEW

**Comment by zahidgopang** [comment]
Hello i already have paid for this
https://github.com/trustwallet/assets/pull/29214
it was small correct i uploaded info.json file only with logo 
if you do not want to update info.json file ignore it just update logo as i already have paid 500 TWT , the logo is not updated yet

**Comment by zahidgopang** [comment]
Hello, I have already paid for this (#29214).

It was a small correction where I only uploaded the info.json file along with the logo.

If you do not wish to update the info.json file, you can ignore it. Please just update the logo, as I have already paid 500 TWT. The logo is not updated yet.

could you please reopen PR

Thank you.

@Cryptocool1

**Comment by zahidgopang** [comment]
@Cryptocool1 @cryptomanz1 
Hello, I have already paid for this (https://github.com/trustwallet/assets/pull/29214).

**Comment by cryptomanz1** [comment]
• What is the purpose of this token? How will it benefit Trust Wallet users?
 • How is the token being distributed? Are you conducting an airdrop?
 • Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?
 • Is the token listed on a centralized/decentralized exchange?
 • Is a Smart Contract audit completed? Where can we find this information?

**Comment by zahidgopang** [comment]
• What is the purpose of this token? How will it benefit Trust Wallet users?
The node waves chain is supported by a network of user-run nodes. Use decentralized data storage system to become a node operator and you own this node as a NFT and receive rewards and benefits for your contribution to the ecosystem.

• How is the token being distributed? 
The total supply of Nodewaves token is 10 billion and will be gradually released in line with a sensible vesting schedule. The token unlock schedule (vesting period) differs depending on the allocation type.
Supply Schedule
Allocation	Percentage of Supply	Lock (Months)	Vesting (Months)
Seed & Private Sales	3%	12	18
Dev & Ecosystem	10%	-	-
Liquidity	15%	-	-
NODE	25%	-	Distributed Daily Based On Halving Schedule (View)
PoB	25%	-	Distributed Daily Based On Halving Schedule (View)
PoS	5%	-	Distributed Daily Based On Halving Schedule (View)
M2E	5%	-	Immediately Unlocked
P2E	5%	-	Immediately Unlocked
Treasure	2%	-	Immediately Unlocked
Advisor	3%	12	18
Team	2%	12	18
• Are you conducting an airdrop?
Yes

• Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?
No
• Is the token listed on a centralized/decentralized exchange?
Yes, On Decentralized Exchange , 
MEXCGlobal https://www.mexc.com/exchange/NWS_USDT
Quickswap : https://quickswap.exchange/#/swap?outputCurrency=0x57c453e7a4d73ac1db8ae07da5dda3b398d17577&swapIndex=2 

• Is a Smart Contract audit completed? Where can we find this information?
Yes, first stage done, main contract address has no critical issues, another minor 3 things on process, attaching progress image.
https://docs.google.com/document/d/1-88kkyufqdQaZvuhvPFOAvOMkNpxx0iOLmcCO3dHHNY/edit
@cryptomanz1 i have answered all which u asked on above

**Comment by zahidgopang** [comment]
1. What is the purpose of this token? How will it benefit Trust Wallet users?

The node waves chain is supported by a network of user-run nodes. Use decentralized data storage system to become a node operator and you own this node as a NFT and receive rewards and benefits for your contribution to the ecosystem.

2. How is the token being distributed? 
The total supply of Nodewaves token is 10 billion and will be gradually released in line with a sensible vesting schedule. The token unlock schedule (vesting period) differs depending on the allocation type.
Supply Schedule
Allocation	Percentage of Supply Lock (Months)	 Vesting (Months)
Seed & Private Sales 3% 12 18
Dev & Ecosystem 10%	-	-
Liquidity 15% - -
NODE 25% - Distributed Daily Based On Halving Schedule (View)
PoB 25% - Distributed Daily Based On Halving Schedule (View)
PoS 5% - Distributed Daily Based On Halving Schedule (View)
M2E	5% -	Immediately Unlocked
P2E 5% - Immediately Unlocked
Treasure 2% - Immediately Unlocked
Advisor 3% 12 18
Team 2% 12 18

3. Are you conducting an airdrop?
Yes

4. Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?
No

5. Is the token listed on a centralized/decentralized exchange?
Yes, On Decentralized Exchange , 
MEXCGlobal https://www.mexc.com/exchange/NWS_USDT
Quickswap : https://quickswap.exchange/#/swap?outputCurrency=0x57c453e7a4d73ac1db8ae07da5dda3b398d17577&swapIndex=2 

6. Is a Smart Contract audit completed? Where can we find this information?
Yes, first stage done, main contract address has no critical issues, another minor 3 things on process, attaching progress image.
https://docs.google.com/document/d/1-88kkyufqdQaZvuhvPFOAvOMkNpxx0iOLmcCO3dHHNY/edit
@cryptomanz1 i have answered all which u asked on above

**Comment by zahidgopang** [comment]
@cryptomanz1 any update ?

**Comment by Cryptocool1** [comment]
Please attach you audit not from  google docs

**Comment by zahidgopang** [comment]
https://skyharbor.certik.com/shared-report/a7e612ae-51a9-4cfa-8707-2972af42cf7e
@Cryptocool1

**Comment by zahidgopang** [comment]
is this solved ? i already answered all questions please 

here is my audit report 
https://skyharbor.certik.com/shared-report/a7e612ae-51a9-4cfa-8707-2972af42cf7e
@Cryptocool1

**Comment by zahidgopang** [comment]
please reopen and fix it

**Comment by zahidgopang** [comment]
logo still not updated yet ?
@Cryptocool1

**Comment by zahidgopang** [comment]
can you please mention any change or doc required form my side this is paid i am waiting to get updated logo and info please help
let me know if some thing is required by our side 
@Cryptocool1 @cryptomanz1

**Comment by zahidgopang** [comment]
but why this all after the payment ? what mentioned in your policy we all provided you information and documents.
so now can you please update my logo only on urgent basis only logo we need should be updated.
@cryptomanz1 @Cryptocool1

**Comment by Cryptocool1** [comment]
Hello, you can see the link to our documentation from the first message from the bot.
Screenshot 2024-10-23 at 18 30 20

**Comment by Cryptocool1** [comment]
Feel free to re-open pull request once you meet those requirements.

**Comment by zahidgopang** [comment]
@Cryptocool1 this issue still not resolved please re-open it immediately and do needful ? guide us what to do next if any thing required ?

**Comment by zahidgopang** [comment]
Hello, I have already paid for this (https://github.com/trustwallet/assets/pull/29214).
please reopen and process

**Comment by zahidgopang** [comment]
Dear TrustWallet Team,

We have already qualified under your listing criteria and have also completed the payment process. 
The Nodewaves (POLYGON) project currently has over 10,000+ holder accounts and more than 1.5 million transactions on-chain.

Please find our Polygon token address below for your reference and verification:
🔗 [[token - 0x13646e0e2d768d31b75d1a1e375e3e17f18567f2)]

We request you to kindly reopen and process this PR urgently for final approval, as all required qualifications and payments have been fulfilled. We appreciate your support and cooperation in moving this forward without further delay.

Thank you for your time and assistance.

Please note that I have already paid for this (https://github.com/trustwallet/assets/pull/29214).

@Cryptocool1 @cryptomanz1 @natedaiger @hexorx please it is urgent.

**Comment by zahidgopang** [comment]
please reopen and fix it

**Comment by zahidgopang** [comment]
Holders
10,231 ( 0.206%)
Transfers
TOTAL
24H
More than 1,508,423

https://polygonscan.com/token/0x13646e0e2d768d31b75d1a1e375e3e17f18567f2

**Comment by zahidgopang** [comment]
i meet this requirements 
As per our policy, there is a minimum requirement of 10,000 holder addresses and 15,000 transactions.
Holders
10,231 ( 0.206%)
Transfers
TOTAL
24H
More than 1,508,423

https://polygonscan.com/token/0x13646e0e2d768d31b75d1a1e375e3e17f18567f2

Please ReOpen it immediately @Cryptocool1 @cryptomanz1 @cryptomanz1 @cryptomanz1 @natedaiger

**Pull request closed without merging**
