### PR TITLE
Add FinNexus Token (FNX)

### PR DESCRIPTION
**Pull request by NoahMaizels**
Add FinNexus Token (FNX), token supply currently lives on both Wanchain and Ethereum.

https://www.fnx.finnexus.io/

### CODE REVIEW

**Comment by catenocrypt** [comment]
@noahniuwa , the wanchain folder seems to be not in correct checksum format.  Could you fix ti?  I cannot, as you gave no permission to your branch/pr for main repo developers, so I cannot push fix to your fork.


```
'Expect asset at path /home/runner/work/assets/assets/blockchains/wanchain/assets/0xc6f4465a6A521124c8E3096b62575C157999d361 in checksum
```

**Comment by noahniuwa** [comment]
@catenocrypt I couldn't figure out how to change the setting for "permission to your branch/pr for main repo developers" after already submitting the PR, but I tried to add you as admin on the fork in FinNexus repo directly. Let me know if that works or if there is anything else I should do.

What is wrong with the checksum? I got it from the official [explorer page](https://www.wanscan.org/token/0xc6f4465a6A521124c8E3096b62575C157999d361), if it has an issue I'm guessing the whole explorer might have this issue....

**Comment by catenocrypt** [comment]
> What is wrong with the checksum? I got it from the official [explorer page](https://www.wanscan.org/token/0xc6f4465a6A521124c8E3096b62575C157999d361), if it has an issue I'm guessing the whole explorer might have this issue....

Our format check says '0xC6F4465A6a521124C8e3096B62575c157999D361', which is exactly reversed.  Maybe Wanchain does not use the Ethereum format, I will have to check into this.  For now I will try to commit yours in the format accepted by our check.

**Comment by catenocrypt** [comment]
Still no permission for me

```
remote: Permission to FinNexus/assets.git denied to catenocrypt.
fatal: unable to access 'https://github.com/FinNexus/assets.git/': The requested URL returned error: 403
```

**Comment by catenocrypt** [comment]
I took over these changes with #3147 , merged.

**Comment by noahniuwa** [comment]
@catenocrypt Yeah I can see on the access section in settings, it says your invite for admin access is still pending. I think you probably will need to check your email spam folder for the invite. I will redo the invite and try and get it to send you another notification.
Screen Shot 2020-08-09 at 4 45 30 PM

**Comment by catenocrypt** [comment]
Sorry, I accepted the invite only later.
I think there is a checkbox for allowing permissions when creating the PR.
This change has been merge already, so no action pending.

**Pull request closed without merging**
