### PR TITLE
Add MousePad (BEP20)

### PR DESCRIPTION
**Pull request by mousepadofficial**
Adding info for BEP20 token 'MousePad'.

PR created by <a href="https://assets.trustwallet.com">TW Assets Management</a>

### CODE REVIEW

**Comment by cryptomanz** [comment]
Hello,
• What is the purpose of this token? How will it benefit Trust Wallet users?
 • How is the token being distributed? Are you conducting an airdrop?
 • Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?
 • Is the token listed on a centralized/decentralized exchange?
 • Is a Smart Contract audit completed? Where can we find this information?

**Comment by mousepadofficial** [comment]
Hi,
logo is not showing in wallet, please resolve.
Thank you

Sent from ProtonMail mobile

-------- Original Message --------

**Comment by Cryptocool1** [comment]
• What is the purpose of this token? How will it benefit Trust Wallet users?
• How is the token being distributed? Are you conducting an airdrop?
• Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?
• Is the token listed on a centralized/decentralized exchange?
• Is a Smart Contract audit completed? Where can we find this information?

**Comment by mousepadofficial** [comment]
Hi ,

All the questions are answered below please check
And the logo is still not reflected on Trustwallet

• What is the purpose of this token? How will it benefit Trust Wallet users?

This is a Reflection token, and it is going to be the native token for the mpadexchange.com

• How is the token being distributed? Are you conducting an airdrop?

The token is available on pancakeswap

• Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?

The token had a presale on pinksale platform

• Is the token listed on a centralized/decentralized exchange?

pancakeswap.finance/swap?outputCurrency=0x0504DCdDeF1bA1F18D44A0149d8B5524c9C5946D
It is listed on decentralised exchange pancakeswap

• Is a Smart Contract audit completed? Where can we find this information?

yes, github.com/Rugfreecoins/Smart-Contract-Audits/blob/main/Mouse Pad Token Audit.pdf

Thank you.

Team Mousepad

-------- Original Message --------

**Comment by cryptomanz** [comment]
Hello,
Please follow the rules for adding token, your logo should be a full screen, 256x256.
Example:
https://community.trustwallet.com/t/how-to-submit-a-token-logo/3863

**Comment by Cryptocool1** [comment]
Please come back to us when all criteria are met.
When creating a new PR make sure to mention this PR, so that we can see that fee has been paid already here.

**Pull request closed without merging**
