### PR TITLE
Add Crypto Snack 2.0  (BEP20)

### PR DESCRIPTION
**Pull request by CryptoSnackProject**
Adding info for BEP20 token 'Crypto Snack 2.0 '.

PR created by <a href="https://assets.trustwallet.com">TW Assets Management</a>

### CODE REVIEW

**Comment by CryptoSnackProject** [comment]
This was the old contract, we made a migration, how can I resolve this?

**Comment by Cryptocool1** [comment]
Hello, please clarify what is you old contract address and what is your new one?

**Comment by CryptoSnackProject** [comment]
Old contract:
0x86aCCc2580dA5Bd522A0eEc7C881A0d4f33De657

New contract:
0xe52bB35344cceedd014Be2896d01e604ad992c85

**Comment by CryptoSnackProject** [comment]
Is there any other Info I can provide or is needed?
Thank you on advance

**Comment by cryptomanz1** [comment]
#26112

**Comment by spartacus2690** [comment]
0x1B0e154AaD70d05FEe97B082C901543972218910

در تاریخ سه‌شنبه ۲۲ اوت ۲۰۲۳،‏ ۱۰:۱۹ Nazar ***@***.***> نوشت:

**Pull request closed without merging**
