### PR TITLE
Simargl Token

### PR DESCRIPTION
**Pull request by SimarglToken**

### CODE REVIEW

**Comment by SimarglToken** [comment]
We've noticed that random airdrops are against you listing criteria, so we want you to know every single user that have received airdrop tokens from us, submitted a wallet address in our airdrop telegram bot (https://t.me/SimarglAirDropBot) which is still receiving wallets and giving away tokens.

**Comment by Cryptocool1** [comment]
can you answer some questions?
• What is the purpose of this token? How will it benefit Trust Wallet users?
 • How is the token being distributed? Are you conducting an airdrop?
 • Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?
 • Is the token listed on a centralized/decentralized exchange?
 • Is a Smart Contract audit completed? Where can we find this information?

**Comment by SimarglToken** [comment]
In today’s Crypto Currency world, there are many different block chains and networks 
each created to serve a purpose. However, these networks lack an interchangeability 
function, and Simargl is here to solve that. With Simargl, we plan to connect all the 
existing and future popular public block chains1 together, to create a seamless network 
for the benefit of people and to make transfers much easier. The system is going to be 
called a ‘Cross-chain network’. 
$SIMA is going to be available in each of the chosen block chains, and will be 
interchangeable to other networks with ease. The first block chain that $SIMA is 
introduced to, is the BSC (Binance SmartChain) network, and the second block chain 
network will be the Ethereum network.

This topic is well explained alongside tokenomics in SIMARGL Litepaper: https://simar.gl/LitePaper.pdf
And yes, we're conducting and airdrop and it's explained well in litepaper too.

The token is currently listed on these exchanges:
- [DEX] PancakeSwap: https://exchange.pancakeswap.finance/#/swap?outputCurrency=0xbdac5c8bc3ff38083437bb712d55b668f44f6df1
- [CEX] BankCEX: https://bankcex.com/exchange-base.html?symbol=SIMA_USDT

At last but not least, Yes, smart contract audit is complete and it's been working flawlessly, It's available on our github page to.

**Review by BeckysLife — APPROVED** [review]

**Comment by Omidreza369** [comment]
> **روابط عمومی خلاصه**
> فایل OK، 2Files در روابط عمومی: 2
> رمز در روابط عمومی: BEP20 0xBDAC5C8bc3FF38083437bB712D55b668F44F6DF1
> نماد: **سیما** اعشار: 9
> لینک ها: [لوگو ](https://raw.githubusercontent.com/SimarglToken/assets/master/blockchains/smartchain/assets/0xBDAC5C8bc3FF38083437bB712D55b668F44F6DF1/logo.png) [اطلاعات ](https://raw.githubusercontent.com/SimarglToken/assets/master/blockchains/smartchain/assets/0xBDAC5C8bc3FF38083437bB712D55b668F44F6DF1/info.json) [وب سایت ](https://simar.gl) [اکسپلورر](https://bscscan.com/token/0xBDAC5C8bc3FF38083437bB712D55b668F44F6DF1) (چک OK🙂)
> 
> 

ازتلاش شما متشکرم وامیدوارم به رتبه های بالا برسم از ارسال توکن شما متشکرم

**Comment by cryptomanz** [comment]
I can't find your  smart contract audit.
Send it here, please.

**Comment by SimarglToken** [comment]
BankCEX Exchange did an audit for us privately while listing the token for trade, And it's not a public reference for it because they don't offer it as a service  publicly but we can submit elsewhere for an audit if its truly necessary

**Comment by Ashkan9920** [comment]
very nice

**Comment by SimarglToken** [comment]
Dear @cryptomanz, If there is anything we can do to accelerate the review please inform us

**Comment by Cryptocool1** [comment]
can you please add links to your PR?
see the example here:
https://developer.trustwallet.com/add_new_asset/repository_details

**Comment by SimarglToken** [comment]
@Cryptocool1 Done!

**Pull request merged**
