### PR TITLE
Add BTT Token (BEP20 & ERC20)

### PR DESCRIPTION
**Pull request by Benson0224**
BTT is the official token of BitTorrent Chain. BitTorrent Chain is a brand-new heterogeneous cross-chain interoperability protocol, which leverages sidechains for the scaling of smart contracts.  BitTorrent Chain supports interoperability with the public chains of Ethereum / TRON / BSC.

Here is the contract info of BTT on different chains:

TRON: https://tronscan.org/#/token20/TAFjULxiVgT4qWk6UZwjqwZXTSaGaqnVp4

BSC: https://bscscan.com/token/0x352cb5e19b12fc216548a2677bd0fce83bae434b

ETH: https://etherscan.io/token/0xc669928185dbce49d2230cc9b0979be6dc797957
 
BTTC: https://bttcscan.com/token/0x0000000000000000000000000000000000001010

### CODE REVIEW

**Comment by Benson0224** [comment]
Please kindly help to merge this PR, thanks.

**Comment by Cryptocool1** [comment]
Снимок экрана 2022-01-28 в 23 26 39
see the Listing Acceptance Guidelines here : https://developer.trustwallet.com/assets/requirements

**Comment by Cryptocool1** [comment]
SUSPECT!

**Comment by Benson0224** [comment]
> Снимок экрана 2022-01-28 в 23 26 39
> 
> see the Listing Acceptance Guidelines here : https://developer.trustwallet.com/assets/requirements

HI,  This is not plagiarism, This is really from the BTTC team. 

All the contract addresses can be found on our BTTC official websites. https://wallet.bt.io/mapping

**Comment by ArtemGoryunov** [comment]
@Cryptocool1 could you assist @Benson0224 to merge this PR?
Looks need a least to add `tag`

**Pull request merged**
