### PR TITLE
DeFi For You - Add DFY token info and logo

### PR DESCRIPTION
**Pull request by tungdt-edsolabs**

### CODE REVIEW

**Comment by defi-vn** [comment]
Hi there, we already submit fee: https://explorer.binance.org/tx/97F2D4907E485A5B28C1F0D5ECD286EE6FBFB85FDD5D0E94B7EFE9B7BC9E51EB

**Comment by tungdt-edsolabs** [comment]
We drop this

**Comment by tungdt-edsolabs** [comment]
Hi, Please help to review our pull request and approve it

Many thanks

**Comment by catenocrypt** [comment]
Submission is OK

**Comment by tungdt-edsolabs** [comment]
Hi, I've update the source code to include BEP2 logo. could you review it again?

**Pull request merged**
