### PR TITLE
Add HyperChain (BEP20)

### PR DESCRIPTION
**Pull request by xcyberdragonx**
Adding info for BEP20 token 'HyperChain'.

PR created by <a href="https://assets.trustwallet.com">TW Assets Management</a>

### CODE REVIEW

**Comment by xcyberdragonx** [comment]
This one should be okay now right?

**Comment by Cryptocool1** [comment]
#7500 PAID

**Comment by Cryptocool1** [comment]
PR should include only 2 files:

blockchains/smartchain/assets/0x565D931cBa7C7E1af3925f77124D5e2d68311BBE/info.json
blockchains/smartchain/assets/0x565D931cBa7C7E1af3925f77124D5e2d68311BBE/logo.png

**Comment by xcyberdragonx** [comment]
delete all i think... Add HyperChain (BEP20) #7523

**Comment by xcyberdragonx** [comment]
PLease, give me sosme more info, gettin gthe files out the PR doesn't seem to work. How to do it? I delete the json files but still it copies over

**Comment by xcyberdragonx** [comment]
Why do the files keep getting copied, if so how to get them out of the pr I delete the every time

**Comment by Cryptocool1** [comment]
Duplicate of #7532

**Pull request closed without merging**
