### PR TITLE
Hero Floki

### PR DESCRIPTION
**Pull request by HeroFloki**

### CODE REVIEW

**Comment by Cryptocool1** [comment]
hello,
• What is the purpose of this token? How will it benefit Trust Wallet users?
 • How is the token being distributed? Are you conducting an airdrop?
 • Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?
 • Is the token listed on a centralized/decentralized exchange?
 • Is a Smart Contract audit completed? Where can we find this information?

**Comment by HeroFloki** [comment]
> hello, • What is the purpose of this token? How will it benefit Trust Wallet users? • How is the token being distributed? Are you conducting an airdrop? • Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale? • Is the token listed on a centralized/decentralized exchange? • Is a Smart Contract audit completed? Where can we find this information?

Hello there,
•  This new token is a reward token that has reached more than 5000 holders in a short time. Gives CAKE and BUSD to all holders. There is also an NFT market.
• It was made presale and offered for sale. No airdrops.
• 20% of the pre-sale has been sold.
• It is listed on pancakeswap.
• Completed You can check it at https://bscscan.com/address/0x5d96991648d22935bdf6c7064b65c3c93f82aa61#code.

**Comment by Cryptocool1** [comment]
can you send the smart contract audit in pdf format?

**Comment by HeroFloki** [comment]
> can you send the smart contract audit in pdf format?

[https://herofloki.com/HeroFloki.pdf](url)

**Comment by Cryptocool1** [comment]
Снимок экрана 2021-10-30 в 12 54 41

**Comment by HeroFloki** [comment]
> can you send the smart contract audit in pdf format?

https://dessertswap.finance/audits/Hero%20Floki%20BSC%20Audit%2012090075.pdf

**Pull request merged**
