### PR TITLE
Add BabyBonk Logo and Info

### PR DESCRIPTION
**Pull request by BabyBonkToken**
Please add The Logo and Information about BabyBonk in TrustWallet dAPP

### CODE REVIEW

**Comment by BabyBonkToken** [comment]
[info.json](https://github.com/trustwallet/assets/files/14244015/info.json)

**Comment by BabyBonkToken** [comment]
Can you please check those, i send the same files, now it says reverted in files.

**Comment by Cryptocool1** [comment]
• What is the purpose of this token? How will it benefit Trust Wallet users?
 • How is the token being distributed? Are you conducting an airdrop?
 • Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?
 • Is the token listed on a centralized/decentralized exchange?
 • Is a Smart Contract audit completed? Where can we find this information?

**Comment by BabyBonkToken** [comment]
Purpose of the Token: Meme and Gamefi. Users can buy NFTs with BabyBonk and those tokens will be used to distribute rewards in our upcoming game BonkRoyale. Users are also able to upgrade the NFTs.

Benefit for Trust Wallet Users: If the token is integrated into Trust Wallet, users may be able to store, send, receive, and potentially swap the token within the wallet interface, see information and logo. Also we have a big community

Token Distribution: 100% Distributef.

Token Sale: the Token had a presale on pinksale.

Exchange Listings: yes pancakeswap, xt, bitget, mexc, bitrue and gate

Smart Contract Audit: the Contract can be found on Certik, we have been audited by them

**Pull request closed without merging**
