### PR TITLE
Add  PointPay Crypto Banking Token V2 (ERC20)

### PR DESCRIPTION
**Pull request by YevheniiaShmelkova**
Adding info for ERC20 token ' PointPay Crypto Banking Token V2'.

PR created by <a href="https://assets.trustwallet.com">TW Assets Management</a>

### CODE REVIEW

**Comment by cryptomanz1** [comment]
• What is the purpose of this token? How will it benefit Trust Wallet users?
 • How is the token being distributed? Are you conducting an airdrop?
 • Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?
 • Is the token listed on a centralized/decentralized exchange?
 • Is a Smart Contract audit completed? Where can we find this information?

**Comment by Cryptocool1** [comment]
Please come back to us once you will be ready to answer the questions. When creating new PR, make sure to mention this one, so the fee can be reused

**Comment by EvheniyaSh** [comment]
Please, find the information required below:

• What is the purpose of this token? How will it benefit Trust Wallet users?

PointPay customers who own PXP tokens receive a number of perks
and incentives:
• Dynamically reduce Maker/Taker fees based on how many tokens
you hold in your account;
• Earn up to 10% per annum by holding PXP tokens in your PointPay
Bank Savings account;
• Earn up to 20% return on your PXP investments, depending on the
number of tokens you stake;
• Lower the interest rate on instant crypto loans;
• Send instant payments to other customers for free within
the PointPay ecosystem;
• Watch premium video tutorials on cryptocurrencies and trading
in our Crypto School (if you hold at least 2,000 PXP tokens
in the PointPay ecosystem);
• Get exclusive access to the promising projects in the crypto space
on our Launchboard platform.

• How is the token being distributed? Are you conducting an airdrop?

All tokens were distributed during the ICO. We are not conducting an airdrop.

• Did you sell the tokens at an Initial Coin Offering (ICO) or a token presale?

Tokens were sold during the ICO and presale. ICO dates: from 25th Jun 2020 to June 30th, 2021

• Is the token listed on a centralized/decentralized exchange?

PXP is listed on the following markets: Bittrex Global, BitGlobal, Bitrue, Whitebit, CoinTige, and Uniswap (V3).

• Is a Smart Contract audit completed? Where can we find this information?

The audit can be found here:
https://www.certik.com/projects/pointpay

**Comment by EvheniyaSh** [comment]
Thanks!

Please, find the info below:

• What is the purpose of this token? How will it benefit Trust Wallet users?

PointPay customers who own PXP tokens receive a number of perks
and incentives:
• Dynamically reduce Maker/Taker fees based on how many tokens
you hold in your account;
• Earn up to 10% per annum by holding PXP tokens in your PointPay
Bank Savings account;
• Earn up to 20% return on your PXP investments, depending on the
number of tokens you stake;
• Lower the interest rate on instant crypto loans;
• Send instant payments to other customers for free within
the PointPay ecosystem;
• Watch premium video tutorials on cryptocurrencies and trading
in our Crypto School (if you hold at least 2,000 PXP tokens
in the PointPay ecosystem);
• Get exclusive access to the promising projects in the crypto space
on our Launchboard platform.

• How is the token being distributed? Are you conducting an airdrop?

All tokens were distributed after the ICO, no airdrops are conducted now.

• Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?

Tokens were sold during the ICO and presale.
ICO dates: from 25th Jun 2020 to June 30th, 2021

• Is the token listed on a centralized/decentralized exchange?

PXP is listed on Bittrex Global; Bitrue; Bitglobal; Whitebit, and CoinTiger.

• Is a Smart Contract audit completed? Where can we find this information?

https://www.certik.com/projects/pointpay

**Pull request merged**
