### PR TITLE
Add CARMA #9239

### PR DESCRIPTION
**Pull request by MediocreD**
REquesting adding the logo, and price info  for CARMA coin. It is already listed on COINGECKO.

### CODE REVIEW

**Comment by MediocreD** [comment]
payment sent

**Comment by MediocreD** [comment]
> **PR Summary**
> Files OK, 2Files in PR: 2
> Token in PR: BEP20 0x27e89d357957ce332ff442db69f4b476401bbbc5
> Symbol: **CARMA** decimals: 9
> Links: [Logo](https://raw.githubusercontent.com/MediocreD/assets/master/blockchains/smartchain/assets/0x27e89d357957ce332ff442db69f4b476401bbbc5/logo.png) [Info](https://raw.githubusercontent.com/MediocreD/assets/master/blockchains/smartchain/assets/0x27e89d357957ce332ff442db69f4b476401bbbc5/info.json) [Website](https://carmacoin.co) [Explorer](https://bscscan.com/token/0x27e89d357957ce332ff442db69f4b476401bbbc5)
> Token check error:
> ❌ Contract is not in checksum format, should be 0x27e89d357957cE332Ff442DB69F4b476401BbBc5 (not 0x27e89d357957ce332ff442db69f4b476401bbbc5). Please rename it. You may need to rename to a temp name first, then to the checksum format, because lowercase-uppercase-only renames are often ignored by the Git client or the filesystem.
> ✓ Token type OK (BEP20); Type field OK; Symbol field OK; Decimals field OK; Description field OK; Website field OK; Explorer field OK; Status field OK; Id field OK; Logo image type is OK (image/png); Logo image size is OK (30.524 kB); Logo dimensions OK (256x256); Token circulation OK (no. of holders: 6275);
> 
> 

How do I change the file name I cannot find the folder under assets?

**Comment by MediocreD** [comment]
hey already success. when it will be released on trustwallet ?

**Comment by Cryptocool1** [comment]
correction needed:
Contract is not in checksum format, should be 0x27e89d357957cE332Ff442DB69F4b476401BbBc5

**Comment by MediocreD** [comment]
Folder and contract # updated

**Comment by Cryptocool1** [comment]
still incorrect
Contract is not in checksum format, should be 0x27e89d357957cE332Ff442DB69F4b476401BbBc5

**Comment by Cryptocool1** [comment]
If you can't rename files in the PR, you may open a new PR. Make sure to mention this PR, so that we can see that fee has been paid already here.

**Pull request closed without merging**
