### PR TITLE
Add MetaSwapToken (BEP20)

### PR DESCRIPTION
**Pull request by lenohard**
Adding info for BEP20 token 'MetaSwapToken'.

PR created by <a href="https://assets.trustwallet.com">TW Assets Management</a>

### CODE REVIEW

**Comment by lenohard** [comment]
I want to know after the PR is merged, how long it will take before the logo is shown on PancakeSwap? @Cryptocool1

**Comment by Cryptocool1** [comment]
> I want to know after the PR is merged, how long it will take before the logo is shown on PancakeSwap? @Cryptocool1

12-48 hours

**Comment by Cryptocool1** [comment]
• What is the purpose of this token? How will it benefit Trust Wallet users?
 • How is the token being distributed? Are you conducting an airdrop?
 • Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?
 • Is the token listed on a centralized/decentralized exchange?
 • Is a Smart Contract audit completed? Where can we find this information?

**Comment by lenohard** [comment]
• What is the purpose of this token? How will it benefit Trust Wallet users?

    It is an STO platform fully deployed on the BSC chain. Issued by major, medium and small companies around the world, Listing and trading through DAO voting governance behavior, thereby simplifying the complicated process of STO.
    
• How is the token being distributed? Are you conducting an airdrop?

The tokens are distributed throught the process described in the  whitepaper (following the link below).
https://metaswap.name/pdf/web/viewer.html?file=whitepaper_en.pdf
There is no airdrop.

• Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?

no

• Is the token listed on a centralized/decentralized exchange?

it has been exchanged on Pancakeswap for a while.

• Is a Smart Contract audit completed? Where can we find this information?

yes, it's completed. https://www.attest.im/attestation/searchResult?qurey=4c9566e936e8407cb40c750dba247b52

**Comment by lenohard** [comment]
> • What is the purpose of this token? How will it benefit Trust Wallet users? • How is the token being distributed? Are you conducting an airdrop? • Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale? • Is the token listed on a centralized/decentralized exchange? • Is a Smart Contract audit completed? Where can we find this information?

• What is the purpose of this token? How will it benefit Trust Wallet users?

It is an STO platform fully deployed on the BSC chain. Issued by major, medium and small companies around the world, Listing and trading through DAO voting governance behavior, thereby simplifying the complicated process of STO.

• How is the token being distributed? Are you conducting an airdrop?

The tokens are distributed throught the process described in the whitepaper (following the link below).
https://metaswap.name/pdf/web/viewer.html?file=whitepaper_en.pdf

• Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?

no

• Is the token listed on a centralized/decentralized exchange?

it has been exchanged on Pancakeswap for a while.

• Is a Smart Contract audit completed? Where can we find this information?

yes, it's completed. https://www.attest.im/attestation/searchResult?qurey=4c9566e936e8407cb40c750dba247b52

**Comment by lenohard** [comment]
Thanks for you guys' efforts and replies. Is there anything else needed to complete the procedure?

**Pull request merged**
