### PR TITLE
Add Frz solar system (BEP20)

### PR DESCRIPTION
**Pull request by smart2022**
Adding info for BEP20 token 'Frz solar system'.

PR created by <a href="https://assets.trustwallet.com">TW Assets Management</a>

### CODE REVIEW

**Comment by smart2022** [comment]
Holders:
11,464 addresses
Transfers:
108,675

**Comment by cryptomanz** [comment]
Please create new PR, follow doc https://developer.trustwallet.com/assets/requirements
You may want to try our Assets app in beta; go to https://assets.trustwallet.com, log on with Github, enter contract ID, logo and some additional info, and it will create a PR for you.
See https://developer.trustwallet.com/assets/repository_details

**Comment by smart2022** [comment]
Hello dear merge-fee-bot
5 BNB for fee paid
transaction hash : 1BB848FB02ADF595B046ED1E53802FBF992F29CFF1F3EC514873082F34F8C70A

number of holders : 
 Holders: 11,505 addresses
Transfers: 110,811



please check and accept info &logo 

Tank you so much

**Comment by smart2022** [comment]
Hello dear merge-fee-bot
5 BNB for fee paid
transaction hash
: 1BB848FB02ADF595B046ED1E53802FBF992F29CFF1F3EC514873082F34F8C70A

number of holders :
 Holders: 11,505 addresses
------------------------------
Transfers: 110,811



please check and accept info & logo

Thank you so much

**Comment by smart2022** [comment]
Hello
5 BNB for fee paid to merge-fee-bot
transaction hash
: 1BB848FB02ADF595B046ED1E53802FBF992F29CFF1F3EC514873082F34F8C70A

number of holders :
 Holders: 11,505 addresses
------------------------------
Transfers: 110,811



please check and accept info & logo

**Comment by smart2022** [comment]
Hello
please revert and change Payment Status to paid 
5 BNB for fee paid to merge-fee-bot
transaction hash
: 1BB848FB02ADF595B046ED1E53802FBF992F29CFF1F3EC514873082F34F8C70A

number of holders :
 Holders: 11,505 addresses
------------------------------
Transfers: 110,811



please check and accept info & logo

**Comment by smart2022** [comment]
[fee paid](https://explorer.binance.org/tx/1BB848FB02ADF595B046ED1E53802FBF992F29CFF1F3EC514873082F34F8C70A)

**Comment by smart2022** [comment]
fee paid [https://explorer.binance.org/tx/1BB848FB02ADF595B046ED1E53802FBF992F29CFF1F3EC514873082F34F8C70A](url)

**Comment by Cryptocool1** [comment]
your logo should be full screen size, please change

**Comment by smart2022** [comment]
Hello Trustwallet/Assets

kindly thank you for supporting

Holders: 11,581 addresses
------------------------------
Transfers: 113,689




and this is logo.png



Is there something else we should do?

**Comment by Cryptocool1** [comment]
Hello! 
you didn’t send your logo, please check again

**Comment by smart2022** [comment]
Hello Trustwallet/Assets

kindly thank you for supporting 

Holders: 11,581 addresses
Transfers: 113,689




and this is logo.png 



Is there something else we should do? 
logo

**Comment by smart2022** [comment]
Hello

kindly thank you for supporting

Holders: 11,581 addresses
------------------------------
Transfers: 113,689




and this is logo.png



Is there something else we should do?

**Comment by smart2022** [comment]
logo

**Comment by smart2022** [comment]
Hello
I sent the logo several times but it hasn't merged yet. Is there anything
else I should do?

**Comment by smart2022** [comment]
Hello dear merge-fee-bot
fee paid
https://explorer.binance.org/tx/1BB848FB02ADF595B046ED1E53802FBF992F29CFF1F3EC514873082F34F8C70A
<https://github.com/trustwallet/assets/pull/url>

**Comment by smart2022** [comment]
no  it`s mistake  #19241   is not for us we paid for 
Add Frz solar system (BEP20) #19244
please fix it 

fee paid with memo 19244 : https://explorer.binance.org/tx/1BB848FB02ADF595B046ED1E53802FBF992F29CFF1F3EC514873082F34F8C70A
<https://github.com/trustwallet/assets/pull/url>

**Comment by smart2022** [comment]
I don't know how but you merged Fwc #19241
<https://github.com/trustwallet/assets/pull/19241>   this is not our token
and we are not pay for fwc  we paid for  Add Frz solar system (BEP20) #19244
please fix it  you merged wrong Fwc you should merge Frz solar system
(BEP20) #19244

fee paid with memo 19244 :
https://explorer.binance.org/tx/1BB848FB02ADF595B046ED1E53802FBF992F29CFF1F3EC514873082F34F8C70A
<https://github.com/trustwallet/assets/pull/url>

**Comment by smart2022** [comment]
Hello
I don't know how but you merged https://github.com/trustwallet/assets/pull/19241 this is not our token and we are not pay for fwc we paid for
Add Frz solar system (BEP20) #19244
please fix it

fee paid with memo 19244 : [https://explorer.binance.org/tx/1BB848FB02ADF595B046ED1E53802FBF992F29CFF1F3EC514873082F34F8C70A](https://github.com/tsunamayo/Starship-EVO/issues/url)
https://github.com/trustwallet/assets/pull/url
please fix it & merge Add Frz solar system (BEP20) #19244

thank you so much for your Attention.

**Comment by smart2022** [comment]
Hello
I don't know how but you merged Fwc #19241
<https://github.com/trustwallet/assets/pull/19241> this is not our token
and we are not pay for fwc we paid for
Add Frz solar system (BEP20) #19244
please fix it

fee paid with memo 19244 :
https://explorer.binance.org/tx/1BB848FB02ADF595B046ED1E53802FBF992F29CFF1F3EC514873082F34F8C70A
<https://github.com/tsunamayo/Starship-EVO/issues/url>
https://github.com/trustwallet/assets/pull/url
please fix it & merge Add Frz solar system (BEP20) #19244

thank you so much for your Attention.

**Comment by smart2022** [comment]
What is the purpose of this token? How will it benefit Trust Wallet users? [https://frzss.com/White-Paper/](url)
How is the token being distributed? Are you conducting an airdrop? [yes](//www.instagram.com/4arzin/)
Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale? no
Is the token listed on a centralized/decentralized exchange?yes several exchange

[https://poocoin.app/tokens/0xac41fb8013c0b63588fc63997785a5d79e73eb28
](url)

[https://hotbit.zendesk.com/hc/en-us/articles/4670680779031
](url)
[https://t.me/coinsbit_announcements/2731](url)

[https://t.me/azbit_news/877](url)

[https://t.me/IndoEx/1860](url)

 Is a Smart Contract audit completed? Where can we find this information? 
[https://coinmarketcap.com/currencies/frz-solar-system/](url)
 please merge Add Frz solar system (BEP20) #19244  you You made a mistake instead merged wrong #19242 , its not our token , our token is Frz solar system (Frzss)
thank you

**Comment by cryptomanz** [comment]
Is a Smart Contract audit completed?

**Comment by smart2022** [comment]
Hello
 yes we did it for coinmarketcap but I couldn't find the link yet

**Comment by smart2022** [comment]
we did this for Coinmarketcap

**Comment by smart2022** [comment]
Hello
thank you alot for your supporting
how long does it takes to merge our token (Frzss)?

**Comment by smart2022** [comment]
Hi please merge #19244

**Comment by smart2022** [comment]
Hello dear Crypto A
thank you so much for your Cooperation
please help us to merge #19244 Faster
thank you

**Comment by cryptomanz** [comment]
Please send me you smart contract audit in pdf format.

**Comment by smart2022** [comment]
https://mudra.website/?certificate=yes&type=0&lp=0x32dea04d057

https://bscscan.com/token/0xaC41Fb8013c0B63588fC63997785A5d79E73eb28
https://coinmarketcap.com/currencies/frz-solar-system/

https://coinmarketcap.com/currencies/frz-solar-system/

**Comment by smart2022** [comment]
https://pdf.ac/1qIW5J

**Comment by smart2022** [comment]
Hello
I several times sent you  audit please merge #19244


https://pdf.ac/1qIW5J
thank you

**Comment by smart2022** [comment]
Hello dear
We sent All you asked for , please merge our token #19244 faster
thank you a lot again

**Comment by TokonomisConsulting** [comment]
Hello Dear BBB Coin
kindly if you needs any helps for create your Trust wallet/assets info & logo I can help you
send me an email : [extraterrestrialcoin@gmail.com](https://github.com/trustwallet/assets/pull/url)

**Comment by smart2022** [comment]
Hello Trust wallet Asset
 smart contract audit

https://rb.gy/kgqqrd

please approve and merg #19244

thank you so much

**Comment by smart2022** [comment]
Hello dear Nazar

https://pdf.ac/thlbw

Thank you so much for your supporting please approve and merg #19244

**Comment by smart2022** [comment]
Hello dear
Please look at this.
 The second token  from the right is our token (Frzss). But Unfortunately,
we are not listed in Trust wallet yet !!!
Please merge #19244 as soon as possible
Thank you

**Comment by Cryptocool1** [comment]
that is not audit, please check.

**Comment by smart2022** [comment]
Hello  deare Crypto A

I attached it please just merge #19244

could you receive it as a pdf?

Thank you

**Comment by smart2022** [comment]
Hello  deare Crypto A

 please just merge #19244

https://pdf.ac/1uAkJZ

Thank you

**Comment by Cryptocool1** [comment]
Send your audit here. The link you attached is not working

**Comment by smart2022** [comment]
your right sorry , this will be open ,please check it out

https://pdf.ac/1uAkJZ

thank you

**Comment by smart2022** [comment]
could you open it dear ?

https://pdf.ac/1uAkJZ

**Comment by smart2022** [comment]
Hello dear

I changed the link and it's open please merge #19244 , we listed on Coin
Market Cap less than a Month but I don't know why trust wallet assets
always send me wrong requests and ask me to pay for them ! we just have one
token #19244  and it's about 3 or 4 days that we didn't listed on dear
trust wallet yet !

please help us to approve and merge #19244 faster.

https://pdf.ac/1uAkJZ

thank yo so much

**Comment by smart2022** [comment]
please tell me how should I revert it & what should I add there to approve?
thank you

**Comment by smart2022** [comment]
Holders: 11,981 addresses
------------------------------
Transfers: 125,633


https://bscscan.com/token/0xaC41Fb8013c0B63588fC63997785A5d79E73eb28

**Review by smart2022 — COMMENTED** [review]
#19244

**Review by smart2022 — COMMENTED** [review]
#19244

**Comment by smart2022** [comment]
Hello
I tried but I could`nt approve  workflows

please accept them for me

thank you

**Comment by smart2022** [comment]
Hello
I tried but I could`nt approve  workflows

please accept them for me

thank you



>

**Comment by smart2022** [comment]
Why do you not approve of my workflows?

we paid fee
https://explorer.binance.org/tx/1BB848FB02ADF595B046ED1E53802FBF992F29CFF1F3EC514873082F34F8C70A

**Comment by smart2022** [comment]
please help me
merge-fee-but did not send me same the same note (Fee is PAID, fantastic!
Thanks! Review added.

The PR will be evaluated soon by a maintainer, and if merged, the new logos
should be visible in Trust Wallet.
Please note that the app caches logos (up to several days; if you want to
see changes immediately, use a new installation). See the assets FAQ
<https://github.com/trustwallet/assets#faq>.
@Iamdeadlyz <https://github.com/Iamdeadlyz>, @Cryptocool1
<https://github.com/Cryptocool1>, @cryptomanz
<https://github.com/cryptomanz>: please take note.

(1000.00 TWT
<https://explorer.binance.org/tx/E4F4A3DC512E080E46D668D531D5A11F0F1383DF15E3E835FC7D185E7A2243DA>
))

and I can't approve my workflow & I don`t know how long it will take !


Kindly please fix it

thank you so much

**Comment by Cryptocool1** [comment]
Please stop spamming. We are checking your token.

**Comment by Cryptocool1** [comment]
I don’t know why you have added 3 more files. You should delete them. Should be only info.json and logo png.

**Comment by smart2022** [comment]
how should I delete them?

**Comment by smart2022** [comment]
I just though should do some thing for this to merge

**Comment by smart2022** [comment]
I cant fine delete it was just revert but dose not worked

**Comment by smart2022** [comment]
sorry can please replace this logo ?

logo

**Comment by smart2022** [comment]
Holders: 12,027 addresses
------------------------------
https://bscscan.com/token/0xaC41Fb8013c0B63588fC63997785A5d79E73eb28

**Comment by Cryptocool1** [comment]
your website is not working

**Comment by smart2022** [comment]
Holders: 12,221 addresses
------------------------------
Transfers:129,579


https://bscscan.com/token/0xaC41Fb8013c0B63588fC63997785A5d79E73eb28

**Comment by smart2022** [comment]
It's temporary to apply some changes.

**Comment by Cryptocool1** [comment]
Awaiting for the working website. On hold for now

**Comment by smart2022** [comment]
Hello
website is ok now please check it out and let me know

**Comment by smart2022** [comment]
Hello
website is ok now please check it out and let me know

**Comment by Cryptocool1** [comment]
still not working.

**Comment by smart2022** [comment]
I just checked it out , maybe it's because of the cache .website its
perfectly works ,please check it out with another device .

https://www.frzss.com/

thank you so much

**Comment by smart2022** [comment]
I know you are busy but please check it out again. The website is ok ,
maybe its because of the cache of the device .

thank you so much again

**Comment by smart2022** [comment]
https://pdf.ac/1uAkJZ

**Comment by smart2022** [comment]
https://pdf.ac/thlbw

**Comment by smart2022** [comment]
It's temporary to apply some changes.

**Comment by smart2022** [comment]
Hello dear
https://pdf.ac/1uAkJZ

thank you

**Comment by smart2022** [comment]
Hello dear Trust Wallet bot
5 BNB for fee payed
transaction hash
: 1BB848FB02ADF595B046ED1E53802FBF992F29CFF1F3EC514873082F34F8C70A

number of holders :
 Holders: 11,505 addresses
------------------------------
Transfers: 110,811



please check and accept info &logo

Tank you so much

**Comment by Cryptocool1** [comment]
This PR have been already merged long time ago

**Comment by smart2022** [comment]
fee paid
https://explorer.binance.org/tx/1BB848FB02ADF595B046ED1E53802FBF992F29CFF1F3EC514873082F34F8C70A
<https://github.com/trustwallet/assets/pull/url>

**Comment by smart2022** [comment]
there is nothing to revert also I tried to approve workflows but I could
not , please do them for me

thank you so much

**Comment by Cryptocool1** [comment]
Hello, what happened? What is the issue?

**Pull request merged**
