### PR TITLE
Add noora logo and info

### PR DESCRIPTION
**Pull request by noorapay**
this is info for noora token

### CODE REVIEW

**Review by noorapay — COMMENTED** [review]
this info for noora token

**Review by noorapay — COMMENTED** [review]
this info for noora token

**Review by noorapay — COMMENTED** [review]
this info for noora token

**Review by noorapay — COMMENTED** [review]
info for noora token

**Review by noorapay — COMMENTED** [review]
info for noora token

**Review by noorapay — COMMENTED** [review]
noora token

**Review by noorapay — COMMENTED** [review]
for noora token

**Review by noorapay — COMMENTED** [review]
data for noora

**Review by noorapay — COMMENTED** [review]
number of holders : 150 - noora token

**Review by noorapay — COMMENTED** [review]
number of holders : 150 - noora token

**Comment by Cryptocool1** [comment]
As per our policy, brand new tokens are not included, there is a minimum requirement of 10,000 holder addresses and 15,000 transactions, in order to filter out scam tokens.
See the criteria at : https://developer.trustwallet.com/assets/requirements .

**Pull request closed without merging**
