### PR TITLE
The DAFI Token Logo

### PR DESCRIPTION
**Pull request by zain-rana**
DAFI Logo PNG - Reinventing network rewards

### CODE REVIEW

**Comment by zain-rana** [comment]
Hi,

Paid!

We also updated the json which had missing information.

**Comment by Cryptocool1** [comment]
Hello,
-Your contract should be in checksummed format 0xFc979087305A826c2B2a0056cFAbA50aad3E6439.
- Please use this app https://assets.trustwallet.com

**Comment by zain-rana** [comment]
> Hello,
> -Your contract should be in checksummed format 0xFc979087305A826c2B2a0056cFAbA50aad3E6439.
> 
> * Please use this app https://assets.trustwallet.com

Hi,
- Done. Please see https://github.com/trustwallet/assets/pull/6596 
- Do I need to resubmit the fee again?

**Comment by catenocrypt** [comment]
Considering payment to #6596 .

**Pull request closed without merging**
