### PR TITLE
add zzz.finance logo

### PR DESCRIPTION
**Pull request by aszquasz**

### CODE REVIEW

**Comment by catenocrypt** [comment]
Could you please rename from
blockchains/ethereum/assets/0xc75F15AdA581219c95485c578E124df3985e4CE0/zzz.finance.png
to
blockchains/ethereum/assets/0xc75F15AdA581219c95485c578E124df3985e4CE0/logo.png

**Comment by aszquasz** [comment]
really dont get my head around that, sorry pal, I am just helping out our developer.
I have to redo the request

**Comment by AndreZZZ123** [comment]
Lets reopne this

**Comment by aszquasz** [comment]
Resent request @3308 https://github.com/trustwallet/assets/pull/3308
If we need to reapply the fee, hit me up

**Comment by zachzwei** [comment]
merged #3308

**Pull request closed without merging**
