### PR TITLE
Please add STVKE (STV) to Trust Wallet.

### PR DESCRIPTION
**Pull request by ghost**
Thank you!

### CODE REVIEW

**Comment by Iamdeadlyz** [comment]
As per our policy, brand new tokens are not included. There is a minimum requirement of 2500 holder addresses and 5000 transactions (airdropped tokens excluded) in order to filter out scam tokens. See the criteria at (mentioned in the first message by the bot): https://community.trustwallet.com/t/how-to-submit-a-token-logo/3863#how-to-get-approved

This token has below-limit usage yet. This pull request will be put on hold. Please come back to us when all criteria are met.
https://etherscan.io/token/0x226e390751A2e22449D611bAC83bD267F2A2CAfF (202, 4515) 7̶9̶6̶,̶ ̶5̶1̶0̶9̶

**Comment by hvshvshin** [comment]
> As per our policy, brand new tokens are not included. There is a minimum requirement of 2500 holder addresses and 5000 transactions (airdropped tokens excluded) in order to filter out scam tokens. See the criteria at (mentioned in the first message by the bot): https://community.trustwallet.com/t/how-to-submit-a-token-logo/3863#how-to-get-approved
> 
> This token has below-limit usage yet. This pull request will be put on hold. Please come back to us when all criteria are met.
> https://etherscan.io/token/0x226e390751A2e22449D611bAC83bD267F2A2CAfF (202, 4515) 7̶9̶6̶,̶ ̶5̶1̶0̶9̶

What?

**Comment by hvshvshin** [comment]
> As per our policy, brand new tokens are not included. There is a minimum requirement of 2500 holder addresses and 5000 transactions (airdropped tokens excluded) in order to filter out scam tokens. See the criteria at (mentioned in the first message by the bot): https://community.trustwallet.com/t/how-to-submit-a-token-logo/3863#how-to-get-approved
> 
> This token has below-limit usage yet. This pull request will be put on hold. Please come back to us when all criteria are met.
> https://etherscan.io/token/0x226e390751A2e22449D611bAC83bD267F2A2CAfF (202, 4515) 7̶9̶6̶,̶ ̶5̶1̶0̶9̶

"Adding an ERC20 token checklist:

 Make sure your smartcontract has more than 500 address holders, otherwise you will be rejected"

We have our 500 holders, now you change the goal posts to 2500 holders???

**Comment by Iamdeadlyz** [comment]
> > As per our policy, brand new tokens are not included. There is a minimum requirement of 2500 holder addresses and 5000 transactions (airdropped tokens excluded) in order to filter out scam tokens. See the criteria at (mentioned in the first message by the bot): https://community.trustwallet.com/t/how-to-submit-a-token-logo/3863#how-to-get-approved
> > This token has below-limit usage yet. This pull request will be put on hold. Please come back to us when all criteria are met.
> > https://etherscan.io/token/0x226e390751A2e22449D611bAC83bD267F2A2CAfF (202, 4515) 7̶9̶6̶,̶ ̶5̶1̶0̶9̶
> 
> "Adding an ERC20 token checklist:
> 
> Make sure your smartcontract has more than 500 address holders, otherwise you will be rejected"
> 
> We have our 500 holders, now you change the goal posts to 2500 holders??? 500 holders is literally written on this repo's instructions on how to add a token.

Apologies for the confusion, we haven't updated the readme.md yet. The basis for this is our latest documentation at the community site: https://community.trustwallet.com/t/how-to-submit-a-token-logo/3863#how-to-get-approved

**Comment by hvshvshin** [comment]
> > > As per our policy, brand new tokens are not included. There is a minimum requirement of 2500 holder addresses and 5000 transactions (airdropped tokens excluded) in order to filter out scam tokens. See the criteria at (mentioned in the first message by the bot): https://community.trustwallet.com/t/how-to-submit-a-token-logo/3863#how-to-get-approved
> > > This token has below-limit usage yet. This pull request will be put on hold. Please come back to us when all criteria are met.
> > > https://etherscan.io/token/0x226e390751A2e22449D611bAC83bD267F2A2CAfF (202, 4515) 7̶9̶6̶,̶ ̶5̶1̶0̶9̶
> > 
> > 
> > "Adding an ERC20 token checklist:
> > Make sure your smartcontract has more than 500 address holders, otherwise you will be rejected"
> > We have our 500 holders, now you change the goal posts to 2500 holders??? 500 holders is literally written on this repo's instructions on how to add a token.
> 
> Apologies for the confusion, we haven't updated the readme.md yet. The basis for this is our latest documentation at the community site: https://community.trustwallet.com/t/how-to-submit-a-token-logo/3863#how-to-get-approved

Considering this is a recent update and the holders count is continuing to grow, could you simply add the token? It would do wonders for the project to get it's icon showing on Uniswap.

**Comment by Iamdeadlyz** [comment]
> > > > As per our policy, brand new tokens are not included. There is a minimum requirement of 2500 holder addresses and 5000 transactions (airdropped tokens excluded) in order to filter out scam tokens. See the criteria at (mentioned in the first message by the bot): https://community.trustwallet.com/t/how-to-submit-a-token-logo/3863#how-to-get-approved
> > > > This token has below-limit usage yet. This pull request will be put on hold. Please come back to us when all criteria are met.
> > > > https://etherscan.io/token/0x226e390751A2e22449D611bAC83bD267F2A2CAfF (202, 4515) 7̶9̶6̶,̶ ̶5̶1̶0̶9̶
> > > 
> > > 
> > > "Adding an ERC20 token checklist:
> > > Make sure your smartcontract has more than 500 address holders, otherwise you will be rejected"
> > > We have our 500 holders, now you change the goal posts to 2500 holders??? 500 holders is literally written on this repo's instructions on how to add a token.
> > 
> > 
> > Apologies for the confusion, we haven't updated the readme.md yet. The basis for this is our latest documentation at the community site: https://community.trustwallet.com/t/how-to-submit-a-token-logo/3863#how-to-get-approved
> 
> Considering this is a recent update and the holders count is continuing to grow, could you simply add the token? It would do wonders for the project to get it's icon showing on Uniswap.

Sorry, not possible. Let us know if you reached the requirements so we can proceed in merging this PR.

**Comment by Iamdeadlyz** [comment]
Let us know once you have reached the requirements so we can re-open this PR.

**Pull request closed without merging**
