### PR TITLE
Make DMM (dApp + tokens) natively available on Trust Wallet

### PR DESCRIPTION
**Pull request by coreycaplan3**
This PR includes the necessary images to add the DMM dApp + tokens to Trust Wallet.

dApp: 
- https://app.defimoneymarket.com

Tokens:
- mDAI - https://etherscan.io/token/0x06301057d77d54b6e14c7faffb11ffc7cab4eaa7
- mETH - https://etherscan.io/token/0xdf9307dff0a1b57660f60f9457d32027a55ca0b2
- mUSDC - https://etherscan.io/token/0x3564ad35b9E95340E5Ace2D6251dbfC76098669B

The following was done according to the specs in the README: 
- [x] All ERC tokens are referenced in the `ethereum` folder as a subfolder with the name being the contract address, as a checksum.
- [x] All token images are 512x512 and are named `logo.png`.
- [x] Added the three tokens to the `whitelist.json` file in the correct alphabetical order, according to the tokens' contract addresses.
- [x] The dApp image uses the dApp-specific domain name and ends with `.png`.

### CODE REVIEW

**Comment by kolya182** [comment]
@coreycaplan3 Can you add TW ?
Screen Shot 2020-04-06 at 3 19 26 PM

**Comment by coreycaplan3** [comment]
> @coreycaplan3 Can you add TW ?
> Screen Shot 2020-04-06 at 3 19 26 PM

Hey, it's 100% there on mobile. Is there a desktop setting we could enable for it? If so, I wasn't aware of that. Could you send documentation if so? Happy to add then!

**Comment by kolya182** [comment]
> > @coreycaplan3 Can you add TW ?
> > Screen Shot 2020-04-06 at 3 19 26 PM
> 
> Hey, it's 100% there on mobile. Is there a desktop setting we could enable for it? If so, I wasn't aware of that. Could you send documentation if so? Happy to add then!
https://github.com/trustwallet/trust-web3-provider also https://developer.trustwallet.com/deeplinking

**Comment by kolya182** [comment]
> > > @coreycaplan3 Can you add TW ?
> > > Screen Shot 2020-04-06 at 3 19 26 PM
> > 
> > 
> > Hey, it's 100% there on mobile. Is there a desktop setting we could enable for it? If so, I wasn't aware
> > of that. Could you send documentation if so? Happy to add then!

https://github.com/trustwallet/trust-web3-provider also https://developer.trustwallet.com/deeplinking

**Comment by coreycaplan3** [comment]
@kolya182 Fixed it! When you visit app.defimoneymarket.com from TW it automatically loads TW :)

Can we get the dApp listed on the suggested dApps page? I already filled out the Google form!

**Comment by coreycaplan3** [comment]
Just want to bump the prior message @kolya182

**Comment by kolya182** [comment]
@coreycaplan3 Can you dm t.me/mykola ?

**Pull request merged**
