### PR TITLE
add logo  YFIBusiness.Finance (YFIB) to trust wallet

### PR DESCRIPTION
**Pull request by yfibusiness**
add logo  YFIBusiness.Finance (YFIB) to trust wallet 
Token Name :YFIBusiness.Finance
Token Symbol : YFIB
Total Supply: 30,000 YFIB
Token Contract: 0x47632da9227e322eda59f9e7691eacc6430ac87c

logo

### CODE REVIEW

**Comment by catenocrypt** [comment]
Please add an `info.json` file next to the `logo.png`, with info about the project, of the form:

```json
{
    "name": "Trust Wallet Token",
    "website": "https://trustwallet.com",
    "short_description": "Utility token to increase adoption of cryptocurrency.",
    "explorer": "https://explorer.binance.org/asset/TWT-8C2"
}
```

**Comment by catenocrypt** [comment]
see comment above   https://github.com/trustwallet/assets/pull/3790#issuecomment-687094392

**Comment by yfibusiness** [comment]
YFIBusiness.Finance (YFIB)💵

A DeFi powerhouse at the center of the hottest trend in the crypto industry. YFIB is a DeFi farmland that yield (returns) on the capital that you stake. The returns vary from one protocol to the next. YFIB automates & optimizes staking such that you can earn maximum return on your capital without having to worry about circumstances.
$YFIB Token is used by yfibusiness.finance as a tool in producing returns from farming deposits. Depositors earn minted portion of $YFIB Token as a return on their deposited capital.
The increase in deposits is meant to increase the value of $YFIB which is the native Token of yfibusiness.finance ecosystem.

🔹Official Website:
https://yfibusiness.finance

🔹TOKENOMICS:

Maximum Supply: 50,000
(20,000 token is locked and will be minted in bits as farming rewards) No new token will ever be produced.

Total Supply: 30,000
Circulating Supply: 27,000

🔹Presale: Done (25 token: 1 ETH)

💰YFIB Token Contract Address:
0x47632da9227e322eda59f9e7691eacc6430ac87c

💹UPCOMING EXCHANGES
Uniswap, BW, MXC and others still being discussed.

Liquidity locked with UNC for 1 year. Link here:👇
https://unicrypt.network/uniswap-browser/pair/0x082F8f6eE4FE559e3676924ba5e626e76D9812E8


$YFIB Uniswap Trading Link here👇:
https://app.uniswap.org/#/swap?inputCurrency=0x47632da9227e322eda59f9e7691eacc6430ac87c

PRICE TRACKING SITES:

💹Coingecko
https://www.coingecko.com/en/coins/yfi-business

💹Coinmarketcap
https://coinmarketcap.com/currencies/yfibusiness/

🔵Join Us on:
Telegram: https://t.me/yfibfinance
Twitter: https://twitter.com/yfibusiness
Medium: https://medium.com/@yfibfinance

**Comment by yfibusiness** [comment]
please check it https://github.com/yfibusiness/assets/commit/df5f1c3009f75ead40816c2b832f1bbdabf79344

**Pull request merged**
