### PR TITLE
ADD BTEC

### PR DESCRIPTION
**Pull request by matheusrenow**
ADD BTEC

### CODE REVIEW

**Comment by Cryptocool1** [comment]
hello,
can you please look at your logo? is everything ok?

**Comment by Cryptocool1** [comment]
logo's sides look strange

**Comment by matheusrenow** [comment]
Ok

**Comment by matheusrenow** [comment]
one moment

**Comment by matheusrenow** [comment]
This Ok, you can continue.

**Comment by matheusrenow** [comment]
If it turns out to be weird, can I change it later?

**Comment by matheusrenow** [comment]
Update now on trust?

**Pull request merged**
