### PR TITLE
Add Ukan (UKAN) (ERC20)

### PR DESCRIPTION
**Pull request by Ukangit**
Adding info for ERC20 token 'Ukan (UKAN)'.

PR created by <a href="https://assets.trustwallet.com">TW Assets Management</a>

### CODE REVIEW

**Comment by Ukangit** [comment]
Hello,
We have successfully passed audit as required in PR #19511 which was paid already.
Audit link : https://github.com/TechRate/Smart-Contract-Audits/blob/main/April/Ukan%20Full%20Smart%20Contract%20Security%20Audit.pdf
Thanks.

**Comment by ramsty** [comment]
Hi,
Your logo should be a full screen 256*256 px, please change.

**Comment by Ukanadmin** [comment]
> Hi, Your logo should be a full screen 256*256 px, please change.

Hi, I attached the 256x256 version below.

Ukanlogo256x256

**Comment by Ukangit** [comment]
Hello,

Please find the 256x256 attached file.

**Comment by Ukangit** [comment]
> Hi, Your logo should be a full screen 256*256 px, please change.
Hello,
Please find the 256x256 attached file.
Logo256

**Comment by Ukangit** [comment]
> TW Assets Management

Hello,
I've used [TW Assets Management](https://assets.trustwallet.com/), can't repost within the same PR, I'am attaching the file below.
Thanks.

**Comment by Ukangit** [comment]
> Hi, Your logo should be a full screen 256*256 px, please change.

Hello,
I've used [TW Assets Management](https://assets.trustwallet.com/), can't repost within the same PR, I'am attaching the file below.
Thanks.

**Pull request merged**
