### PR TITLE
Add Byte token info - ERC20

### PR DESCRIPTION
**Pull request by GuolongCyber**
Add BYTE Token Info for ERC20

### CODE REVIEW

**Comment by GuolongCyber** [comment]
> ### PR Summary
> Files OK: 2 Token in PR: **ERC20** 0xdE342A3E269056fc3305f9e315F4C40D917BA521 Symbol: **BYTE** decimals: 9 Links: [Logo](https://raw.githubusercontent.com/GuolongCyber/assets/master/blockchains/ethereum/assets/0xdE342A3E269056fc3305f9e315F4C40D917BA521/logo.png) [Info](https://raw.githubusercontent.com/GuolongCyber/assets/master/blockchains/ethereum/assets/0xdE342A3E269056fc3305f9e315F4C40D917BA521/info.json) [Website](https://www.bytedog.ai) [Explorer](https://etherscan.io/token/0xdE342A3E269056fc3305f9e315F4C40D917BA521) Tags: meme Token check error: ❌ invalid value 'https://www.coingecko.com/en/coins/byte' for coingecko link url, allowed only with prefix: https://coingecko.com/ ❌ tag 'meme' is not allowed ❌ low token circulation: number of holders is 5774, below limit of 10000
> 
> 

info updated

**Comment by cryptomanz1** [comment]
As per our policy, there is a minimum requirement of 10,000 holder addresses and 15,000 transactions.
See the criteria at : https://developer.trustwallet.com/listing-new-assets/requirements .

**Comment by GuolongCyber** [comment]
> As per our policy, there is a minimum requirement of 10,000 holder addresses and 15,000 transactions. See the criteria at : https://developer.trustwallet.com/listing-new-assets/requirements .

We have already list on CMC and can we pay more TWT, thanks

**Comment by Cryptocool1** [comment]
Come back to us once all criteria are met. Make sure to mention this PR so the fee can be reused.

**Pull request closed without merging**
