### PR TITLE
Add IDRX Token

### PR DESCRIPTION
**Pull request by IfanWijaya**

### CODE REVIEW

**Comment by IfanWijaya** [comment]
Note: We have previously created the pull request with ID #27103 and we have made payment of 500 TWT with this txid: FA733BB7876A02A2D2E7533EBEDC968F1543ECF784B672145327EF5E7937FA2C

**Comment by Cryptocool1** [comment]
As per our policy, there is a minimum requirement of 10,000 holder addresses and 15,000 transactions.
See the criteria at : https://developer.trustwallet.com/listing-new-assets/requirements .

**Comment by IfanWijaya** [comment]
we have met that criteria on the Polygon network.
https://polygonscan.com/token/0x649a2DA7B28E0D54c13D5eFf95d3A660652742cC

**Comment by IfanWijaya** [comment]
> As per our policy, there is a minimum requirement of 10,000 holder addresses and 15,000 transactions. See the criteria at : https://developer.trustwallet.com/listing-new-assets/requirements .

we have met that criteria in the Polygon network.
https://polygonscan.com/token/0x649a2DA7B28E0D54c13D5eFf95d3A660652742cC

**Pull request closed without merging**
