### PR TITLE
Add Marketmaking.PRO (MMPRO) token

### PR DESCRIPTION
**Pull request by sklazer**

### CODE REVIEW

**Review by sklazer — COMMENTED** [review]
tags updated

**Comment by Cryptocool1** [comment]
• Is a Smart Contract audit completed? Where can we find this information?

**Comment by sklazer** [comment]
> • Is a Smart Contract audit completed? Where can we find this information?

Here is smart contract audit from Certik:
https://certik-public-assets.s3.amazonaws.com/REP-marketmaking-pro-2021-11-13.pdf

**Comment by sklazer** [comment]
@Cryptocool1 @cryptomanz1 also we are getting an error from tests (github jobs as i see):
level=error msg="invalid value 'https://x.com/MarketmakingX' for twitter link url, allowed only with prefix: https://twitter.com/" asset=0x6067490d05F3cF2fdFFC0e353b1f5Fd6E5CCDF70

Is it okay?

**Pull request merged**
