### PR TITLE
Add ROLL Logo

### PR DESCRIPTION
**Pull request by ghost**

### CODE REVIEW

**Comment by JasonDavon** [comment]
logo

**Comment by JasonDavon** [comment]
logo

**Comment by JasonDavon** [comment]
logo

**Comment by JasonDavon** [comment]
logo

**Comment by JasonDavon** [comment]
logo

**Comment by JasonDavon** [comment]
logo

**Comment by catenocrypt** [comment]
@JasonDavon , you have closed this PR after paying fee.  Do you abandon it or should we reopen it?

**Pull request closed without merging**
