### PR TITLE
Add Hachiko (BEP20)

### PR DESCRIPTION
**Pull request by erience**
Adding info for BEP20 token 'Hachiko'.

### CODE REVIEW

**Comment by ramsty** [comment]
Hi!
Could you answer some questions?
• What is the purpose of this token? How will it benefit Trust Wallet users?
• How is the token being distributed? Are you conducting an airdrop?
• Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?
• Is the token listed on a centralized/decentralized exchange?
• Is a Smart Contract audit completed? Where can we find this information?

**Comment by erience** [comment]
• What is the purpose of this token? How will it benefit Trust Wallet users? --- Hachiko is a locked token that will be used to encourage new users to the crypto space by offering a fun and unique ecosystem of audited Dapps for users to participate. Hachiko Burn is a unique Dapp Platform, which can be utlized by the wide community of Trust wallet users in a simplified manner.

• How is the token being distributed? Are you conducting an airdrop? ---- Token was fair launched. Owner renounced ownership to community. No Airdrop has been done

• Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale? ---- No ICO or Presale has been done. It was fair launch.

• Is the token listed on a centralized/decentralized exchange? --- The Token is listed on Pancakeswap, Indoex, Cointiger and Azbit exchanges. The Links for the same are as follows:

https://www.cointiger.com/en-us/#/trade_center?coin=hachiko_usdt
https://azbit.com/exchange/HACHIKO_USDT
https://international.indoex.io/trade/HACHIKO_USDT

• Is a Smart Contract audit completed? Where can we find this information?  ---  TechRate has completed the Quick Audit and the full audit is under progress. providing the link of the audit report shortly.

**Comment by Cryptocool1** [comment]
waiting for smart contract audit, on hold for now

**Comment by erience** [comment]
@Cryptocool1 @ramsty : have created new pull request with the audit report, please do the needful: https://github.com/trustwallet/assets/pull/15539

**Pull request closed without merging**
