### PR TITLE
ADD OMINOFINANCE LOGO (BEP 20)

### PR DESCRIPTION
**Pull request by ominofinance**
Logo Update

### CODE REVIEW

**Review by ominofinance — COMMENTED** [review]
Logo token update

**Review by ominofinance — COMMENTED** [review]
RENAME FILE

**Review by ominofinance — COMMENTED** [review]
Info.json update

**Comment by Cryptocool1** [comment]
• I suggest to create a new PR (and mention this one so that fee does not have to be paid again).
 • You may use our Assets app (in beta); close this PR; go to https://assets.trustwallet.com, log on with Github, enter contract ID, logo and some additional info, and it will create a PR for you. See https://community.trustwallet.com/t/how-to-submit-a-token-logo-using-assets-app/82957

**Pull request closed without merging**
