### PR TITLE
Add Pepe AI (BEP20)

### PR DESCRIPTION
**Pull request by pepestyle**
Adding info for BEP20 token 'Pepe AI'.

PR created by <a href="https://assets.trustwallet.com">TW Assets Management</a>

### CODE REVIEW

**Review by Masoudahgl — COMMENTED** [review]
Like

**Comment by Cryptocool1** [comment]
• What is the purpose of this token? How will it benefit Trust Wallet users?
 • How is the token being distributed? Are you conducting an airdrop?
 • Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?
 • Is the token listed on a centralized/decentralized exchange?
 • Is a Smart Contract audit completed? Where can we find this information?

**Comment by pepestyle** [comment]
• What is the purpose of this token? How will it benefit Trust Wallet users?
Pepe AI is the token of 3 AI utilities - pepe draw, pepe scanner and ask pepe which serve to bring AI technology into crypto. This will benefit trust wallet users as majority of our users use Trust Wallet to check price, and adding our logo and website keep them updated to the latest movement of our token.

• How is the token being distributed? Are you conducting an airdrop?
It is being distributed at PancakeSwap. We are not conducting an airdrop

• Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?
No Presale or ICO.

• Is the token listed on a centralized/decentralized exchange?
Our token will begin trading on Poloniex exchange at https://www.poloniex.com/trade/PEPEAI_USDT?type=spot
Our announcement thread is as at https://support.poloniex.com/hc/en-us/articles/14595589050263-New-Listing-Pepe-AI-PEPEAI-

We are currently trading on PancakeSwap too.

• Is a Smart Contract audit completed? Where can we find this information?
Yes, smart audit is completed and can be found at https://www.staysafu.org/audit/pepe-ai

Renounced ownership link: https://bscscan.com/tx/0x7e7fb1b837d991a8245dde7d7783621b4acd70d46f9261a1f99aa8dde41c1fcb
CoinMarketCap: https://coinmarketcap.com/currencies/pepe-ai-bsc/
CoinGecko: https://www.coingecko.com/en/coins/pepe-ai

**Comment by pepestyle** [comment]
Hi @Cryptocool1 @cryptomanz1
May I check if there any questions for our team, we are looking forwards to be list on Trust Wallet.

**Review by Masoudahgl — COMMENTED** [review]
Like

**Pull request merged**
