### PR TITLE
Add YO EXCHANGE (BEP20)

### PR DESCRIPTION
**Pull request by PankajTMB**
Adding info for BEP20 token 'YO EXCHANGE'.

PR created by <a href="https://assets.trustwallet.com">TW Assets Management</a>

### CODE REVIEW

**Comment by PankajTMB** [comment]
Here is CoinMarketCap link:-  https://coinmarketcap.com/currencies/yo-exchange/

**Comment by Cryptocool1** [comment]
• What is the purpose of this token? How will it benefit Trust Wallet users?
 • How is the token being distributed? Are you conducting an airdrop?
 • Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?
 • Is the token listed on a centralized/decentralized exchange?
 • Is a Smart Contract audit completed? Where can we find this information?

**Comment by PankajTMB** [comment]
• What is the purpose of this token? How will it benefit Trust Wallet users?

Ans:   YOEX is a The Safe Way To The Crypto Trading. So Trust wallet Users also can get benefit by buying YOEX Coin. When they trade then they will get as a reward when they trade. 

• How is the token being distributed? Are you conducting an airdrop?

Ans:  A portion of the tokens are reserved for the project's YOEX developers and some are held for business development and expansion purpose. However we're not conducting an airdrop yet.

• Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?

Ans: No, all of our token are sold in PancakeSwap Exchange

• Is the token listed on a centralized/decentralized exchange?

Ans: Yeah its listed on PancakeSwap with Liquidity.  
  
• Is a Smart Contract audit completed? Where can we find this information?

Ans:  Audit is not completed but we are listed at CMC and AzBit centralized Exchange.

**Comment by ramanbehltechy** [comment]
@Cryptocool1 
Here is smart contract audit :- https://hacken.io/audits/yoex/

**Comment by PankajTMB** [comment]
@Cryptocool1
Here is smart contract audit :- https://hacken.io/audits/yoex/

**Pull request closed without merging**
