### PR TITLE
Add Cat (BEP20)

### PR DESCRIPTION
**Pull request by mrc72tr54**
Adding info for BEP20 token 'Cat'.

PR created by <a href="https://assets.trustwallet.com">TW Assets Management</a>

### CODE REVIEW

**Comment by Cryptocool1** [comment]
• What is the purpose of this token? How will it benefit Trust Wallet users?
 • How is the token being distributed? Are you conducting an airdrop?
 • Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?
 • Is the token listed on a centralized/decentralized exchange?
 • Is a Smart Contract audit completed? Where can we find this information?

**Comment by mrc72tr54** [comment]
1. The purpose of the tokens is to allow cat lovers around the world to join us and care for cat
2. Fair launch at pancakeswap, then list on cg and cmc, more and more people join us and we have verified twitter
3. we have Private Sale
4. Listed on a centralized （XT.com） and decentralized （pancakeswap)
5. No smart contract audit

**Comment by Cryptocool1** [comment]
We require smart contract audit. Please see it in our doc https://developer.trustwallet.com/listing-new-assets/requirements
On hold for now

**Comment by mrc72tr54** [comment]
smart contract audit : [https://drive.google.com/file/d/1l0wMtDVI-_jnR-i63BesSZGAbBv3KAec/view?usp=sharing](link)

**Comment by mrc72tr54** [comment]
How can i audit?

**Comment by Cryptocool1** [comment]
What did you send me?

**Comment by mrc72tr54** [comment]
Audit report : https://catcattoken.com/tool.pdf

**Comment by Cryptocool1** [comment]
What is that? That is not smart contract audit

**Comment by mrc72tr54** [comment]
Please add : this https://coinmarketcap.com/currencies/cat-cat-token/

**Comment by Cryptocool1** [comment]
Here is an example of smart contract audit 
https://www.certik.com/projects/matic

**Comment by Cryptocool1** [comment]
Please come back to us once all criteria are met. 
make sure to mention this PR so the fee can be reused.

**Comment by mrc72tr54** [comment]
@24264

**Comment by Cryptocool1** [comment]
Please see my message above

**Comment by mrc72tr54** [comment]
There is the audit file http://catcattoken.com/tool.pdf

**Pull request closed without merging**
