### PR TITLE
Adding NEWDOGE logo and info

### PR DESCRIPTION
**Pull request by NewDogeCoin**
We would like to add the NEWDOGE logo, price & info. Thank you

### CODE REVIEW

**Comment by NewDogeCoin** [comment]
Is there something wrong with the info format? this was copied directly form the tutorial from Trust Wallet.

**Comment by NewDogeCoin** [comment]
I'm sorry I'm having a hard time doing this properly. Can you please help make sure I have completed this properly. Please help change what is needed to update the log and info. Thank you so much.

**Comment by NewDogeCoin** [comment]
Is there anything else that needs to be done or should we close this? Is everything completed on our end. Thank you - Brock

**Comment by Cryptocool1** [comment]
> Is there anything else that needs to be done or should we close this? Is everything completed on our end. Thank you - Brock

can you answer some questions?
• What is the purpose of this token? How will it benefit Trust Wallet users?
 • How is the token being distributed? Are you conducting an airdrop?
 • Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?
 • Is the token listed on a centralized/decentralized exchange?
 • Is a Smart Contract audit completed? Where can we find this information?

**Comment by NewDogeCoin** [comment]
• What is the purpose of this token? How will it benefit Trust Wallet users?
The purpose of this token is to be a form of exchange for our new ecosystem in development. We have not built in any taxes or fees; clean tokenomics. We have a capped supply, burn every month & locked liquidity. very low transaction costs and energy efficient; no mining. We will use NEWOGE as the center for our ecosystem being built. We have been guiding everyone to setup a Trust Wallet to hold NEWDOGE. The Trust wallet is our favorite wallet out of all the wallets. NEWDOGE will help bring many new users to the Trust Wallet. Trust Wallet is by far the best wallet. Right now we are hyper focused on building out our community and not one of these tokens trying to moon right away. We are a lifetime long term project building a solid community. 

• How is the token being distributed? Are you conducting an airdrop?
On PancakeSwap - Yes we did an airdrop to the first 1,000 to complete specific tasks to help us grow organically on social media. We also have a $10,000 NEWDOGE giveaway contest for the top 50 people to refer new buyers to NEWDOGE.

• Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?
No - Fair launched released to the public

• Is the token listed on a centralized/decentralized exchange?
Yes - https://exchange.pancakeswap.finance/#/swap?outputCurrency=0x94618ffb2153d4a52ce1e8d00e72de676576bd6a

• Is a Smart Contract audit completed? Where can we find this information?
Yes - https://newdoge.com/NEWDOGE_audit.pdf

**Comment by Cryptocool1** [comment]
not all checks passed in audit

**Comment by NewDogeCoin** [comment]
What checks didn't pass?

**Comment by Cryptocool1** [comment]
034B2632-EAC2-4586-A406-CB7DBC4EFB10

**Comment by NewDogeCoin** [comment]
Is this required to have the logo and info updated?

**Comment by NewDogeCoin** [comment]
all 20 checks?

**Comment by NewDogeCoin** [comment]
I reached out to TechRate to get a full audit done. I will update shortly.

**Comment by Cryptocool1** [comment]
Hello,
please create new PR when smart contract audit will be ready.
make sure to mention this PR, so that we can see that fee has been paid already here.

**Comment by NewDogeCoin** [comment]
We have received the full audit and created a new pull request here: https://github.com/trustwallet/assets/pull/11902

**Pull request closed without merging**
