### PR TITLE
Add Film.io (POLYGON)

### PR DESCRIPTION
**Pull request by filmio**
Adding info for POLYGON token 'Film.io'.

PR created by <a href="https://assets.trustwallet.com">TW Assets Management</a>

### CODE REVIEW

**Comment by filmio** [comment]
There wasn't a place to add the number of token holders on the form, so I am adding it here: 17,323

**Comment by cryptomanz1** [comment]
• What is the purpose of this token? How will it benefit Trust Wallet users?
 • How is the token being distributed? Are you conducting an airdrop?
 • Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?
 • Is the token listed on a centralized/decentralized exchange?
 • Is a Smart Contract audit completed? Where can we find this information?

**Comment by Cryptocool1** [comment]
This PR is being closed due to inactivity. Please create new PR once you are ready to answer our questions.

**Comment by Cryptocool1** [comment]
Hello , there was no reply from you for 2 weeks

**Comment by Cryptocool1** [comment]
Why is the name in PR different from the explorer you added?

**Comment by Cryptocool1** [comment]
Token name in PR - Film.io
Token name in explorer - Fan

**Comment by filmio** [comment]
I responded on the 19th of April, not sure why it didn't take. Filmio is the platform, FAN is the token. We standardized on Filmio for the URL on the exchange, since the platform name is more recognizable.The token name is FAN though.

**Comment by filmio** [comment]
@Cryptocool1 can you please stay engaged here? We really need this resolved.

**Pull request merged**
