### PR TITLE
Add JailDoge Logo&Info.

### PR DESCRIPTION
**Pull request by GuolongCyber**
Jail Doge is a deflationary DeFi token that takes a 9% tax from each buy and sell. This tax acts to benefit the project as a whole by putting 3% in the liquidity pool for a stable price floor, 3% proportionally reflected back to all holders of a JAILDOGE token and 3% added to a marketing/dev wallet to make sure that the project is able to succeed in the long term. Another large purpose of the tax is to decentivise large token holders from buying and selling quickly and damaging the price. This almost always effects the small token holders and we want a fair coin for all.

### CODE REVIEW

**Comment by cryptomanz** [comment]
Can your answer some questions?
 • What is the purpose of this token? How will it benefit Trust Wallet users?
 • How is the token being distributed? Are you conducting an airdrop?
 • Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?
 • Is the token listed on a centralized/decentralized exchange?
 • Is a Smart Contract audit completed? Where can we find this information?

**Comment by GuolongCyber** [comment]
• What is the purpose of this token? How will it benefit Trust Wallet users?
Jail Doge is a deflationary DeFi token that takes a 9% tax from each buy and sell. This tax acts to benefit the project as a whole by putting 3% in the liquidity pool for a stable price floor, 3% proportionally reflected back to all holders of a JAILDOGE token and 3% added to a marketing/dev wallet to make sure that the project is able to succeed in the long term. Another large purpose of the tax is to decentivise large token holders from buying and selling quickly and damaging the price. This almost always effects the small token holders and we want a fair coin for all.


• How is the token being distributed? Are you conducting an airdrop?
 TOTAL SUPPLY = 1 QUADRILLION
 - 33%(330 Trillion) to Burn.
 - 4%(40 Trillion) to Marketing token.
 - 33%(330 Trillion) to presale.
 - 30%(300 Trillion) PancakeSwap Liquidity.


• Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?
 Yes, we have a presale. Presale on Dxsale.

• Is the token listed on a centralized/decentralized exchange?
It's Already listed in PancakeSwap

• Is a Smart Contract audit completed? Where can we find this information?
 We have a full audit by RodeoSolutions
Audit here:https://github.com/RodeoSolutions/Audits/blob/main/%24JAILDOGE/JailDoge%20Token%20Audit.pdf

**Comment by Cryptocool1** [comment]
the description of the token should indicate why it exists and what it does
please change

**Comment by GuolongCyber** [comment]
@Cryptocool1  Change done~ Thank you~

**Pull request merged**
