### PR TITLE
Add SingularityDAO

### PR DESCRIPTION
**Pull request by RobertWils**

### CODE REVIEW

**Comment by RobertWils** [comment]
As discussed with TWT Team

**Comment by Cryptocool1** [comment]
Hello! Who did you discuss with?

**Comment by RobertWils** [comment]
Our team discussed with Pierre. Please confirm before we make payment :) We're all in a TG group with Elvira, Jon and others.

**Comment by RobertWils** [comment]
> Hello! Who did you discuss with?


Our team discussed with Pierre. Please confirm before we make payment :) We're all in a TG group with Elvira, Jon and others.

**Comment by Cryptocool1** [comment]
Thank you! Yes sure! Please make the payment

**Comment by RobertWils** [comment]
Can we please open this again?

**Pull request merged**
