### PR TITLE
Add ATOR Protocol (ERC20)

### PR DESCRIPTION
**Pull request by Airtorprotocol**
Adding info for ERC20 token 'ATOR Protocol'.

PR created by <a href="https://assets.trustwallet.com">TW Assets Management</a>

### CODE REVIEW

**Comment by Airtorprotocol** [comment]
Please set the tag to privacy only .

**Comment by Airtorprotocol** [comment]
500TWT sent . 
https://explorer.bnbchain.org/tx/14B4A88C482B2DA84383EB72B8987D3954404EFF0DBBE9B5E3F24212846E64AC

**Comment by Airtorprotocol** [comment]
@Cryptocool1 @cryptomanz1  please check whenever you guys are up

**Comment by Cryptocool1** [comment]
Hello! 
• What is the purpose of this token? How will it benefit Trust Wallet users?
 • How is the token being distributed? Are you conducting an airdrop?
 • Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?
 • Is the token listed on a centralized/decentralized exchange?
 • Is a Smart Contract audit completed? Where can we find this information?

**Comment by Airtorprotocol** [comment]
Hi thanks
1- ATOR empowers The Onion Router (Tor) through on-chain incentives, and facilitates wider adoption of secure network relay protocols through hardware products. ATOR contributes the following to the existing Tor network:

A framework for existing Tor relays to receive cryptocurrency rewards in our native currency, ATOR, in accordance with their cumulative useful uptime, through a Proof-of-Uptime mechanism

 The introduction of the ATOR Router Hotspot, a handheld device that enables users to connect their consumer devices, via WiFi, and route all their web traffic through Tor script-free

The rollout of the ATOR Relay, our own version of the Tor relay. It is designed for Tor routing and immediately interoperable with our ATOR Proof-of-Uptime framework, allowing non-technical users to mine ATOR and contribute to web anonymity through Tor.

2-no airdrop 

3- there was no presale and ICO and it was a fairlaunch on Uniswap

4-Yes , ATOR is listed on Uniswap , Sushiswap , Mexc , XT , CoinEx and SuperEx

5- yes , here is the link : https://audit.solidgrp.io/audits/Ator

**Comment by Airtorprotocol** [comment]
And i have a question , how can we add ATOR to trustwallet swap? What are the terms/requirements and expected fees

**Comment by Airtorprotocol** [comment]
@Cryptocool1 @cryptomanz1

**Comment by Airtorprotocol** [comment]
@cryptomanz1  @Cryptocool1  please check

**Comment by Airtorprotocol** [comment]
@Cryptocool1  @cryptomanz1 please check

**Comment by Airtorprotocol** [comment]
Hi @Cryptocool1  @cryptomanz1  any updates?

**Comment by Airtorprotocol** [comment]
Hi @Cryptocool1  @cryptomanz1  could you please check ?

**Comment by Airtorprotocol** [comment]
Hi there , @Cryptocool1  @cryptomanz1 
how can we add ATOR to trustwallet swap? What are the terms/requirements and expected fees

**Review by Bitcoin-ccenbc — COMMENTED** [review]
CCENBC

**Pull request merged**
