### PR TITLE
Add AURIcoin (RIC) (ERC20)

### PR DESCRIPTION
**Pull request by HHGAG**
Adding info for ERC20 token 'AURIcoin (RIC)'.

PR created by <a href="https://assets.trustwallet.com">TW Assets Management</a>

### CODE REVIEW

**Comment by Cryptocool1** [comment]
Hello,
 • Is the token listed on a centralized/decentralized exchange?
 • Is a Smart Contract audit completed? Where can we find this information?

**Comment by HHGAG** [comment]
> • Is the token listed on a centralized/decentralized exchange? 
centralized exchange, 
https://qrader.com/exchange?market=RIC_TRY
and at
auricoin.org 

>• Is a Smart Contract audit completed? Where can we find this information?
token is etherium based, I'll look for

**Comment by Cryptocool1** [comment]
Awaiting for smart contract audit, on hold for now

**Comment by HHGAG** [comment]
> Awaiting for smart contract audit, on hold for now



https://etherscan.io/token/0x08e0faff8bb80eaf8c30a99920355028b5bd6789#code

**Comment by Cryptocool1** [comment]
> > Awaiting for smart contract audit, on hold for now
> 
> https://etherscan.io/token/0x08e0faff8bb80eaf8c30a99920355028b5bd6789#code

we require smart contract audit
see requirements here: As per our policy, brand new tokens are not included, there is a minimum requirement of 10,000 holder addresses and 15,000 transactions, in order to filter out scam tokens.
See the criteria at : https://developer.trustwallet.com/assets/requirements .

**Comment by HHGAG** [comment]
> we require smart contract audit
should be done already, I'll look for today

**Comment by HHGAG** [comment]
Is this sufficient enough:
https://www.coinscope.co/cyberscan?network=ETH&address=0x08e0fAFf8bB80eaf8c30A99920355028b5bD6789

**Comment by Cryptocool1** [comment]
hello, no we are not accept automated audit report. We require full smart contract audit from reputable companies. (Techrate, Certik, Hacken, Dessert Finance)

**Comment by KDK7monta** [comment]
support@huobigroup.com

**Comment by HHGAG** [comment]
Thnx for reply, we'll look forward getting an audit through one of the named companies.

**Comment by HHGAG** [comment]
Dessert Finance has been commissioned to do the audit

**Comment by HHGAG** [comment]
Audit is completed and published

https://dessertswap.finance/audits/AURIcoin-ETH-Audit-15585850.pdf

**Comment by HHGAG** [comment]
@cryptomanz1 
How can we get the price from the exchange shown?

**Pull request merged**
