### PR TITLE
Add Tokyo AU Token (BEP20) 

### PR DESCRIPTION
**Pull request by tokau-project**
Adding info for BEP20 token 'Tokyo AU Token'.

PR created by <a href="https://assets.trustwallet.com">TW Assets Management</a>

### CODE REVIEW

**Comment by cryptomanz** [comment]
Hello,
Can your answer some questions?
• What is the purpose of this token? How will it benefit Trust Wallet users?
 • How is the token being distributed? Are you conducting an airdrop?
 • Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?
 • Is the token listed on a centralized/decentralized exchange?
 • Is a Smart Contract audit completed? Where can we find this information?

**Comment by tokau-project** [comment]
• What is the purpose of this token? How will it benefit Trust Wallet users?
TOKAU is a utility token for DAO vote and NFT buying functionality and so on. We have cooperations celebs like Iverson, Ian Somehalder, LunaMaya, Russell Simmons etc, they have many fans around the world, as we know many users use TrustWallet, and users don't know crypto like to know crypto by using TrustWalllet, as this we may bring TrustWallet users, and we can do airdrop events to TrustWallet users too.

• How is the token being distributed? Are you conducting an airdrop?
Details can be discovered from our whitepaper, we have done several airdrops before, for TrustWallet users we can conduct an new airdrop event.

• Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?
Yes, we've a token presale, and all presale tokens have released, and we have do a IDO(maybe a variation of ICO) on bakeryswap.

• Is the token listed on a centralized/decentralized exchange?
Yes, TOKAU is listed on CEX like MXC, LATOKEN, LBANK, and DEX like Bakeryswap. 

• Is a Smart Contract audit completed? Where can we find this information?
We havn't do a token SmartContract audit yet, but our token is opensourced on bscscan.io/token/0xC409eC8a33f31437Ed753C82EEd3c5F16d6D7e22, if it's necessary we can do the audit later on.

**Comment by tokau-project** [comment]
> Hello,
> Can your answer some questions?
> • What is the purpose of this token? How will it benefit Trust Wallet users?
> • How is the token being distributed? Are you conducting an airdrop?
> • Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?
> • Is the token listed on a centralized/decentralized exchange?
> • Is a Smart Contract audit completed? Where can we find this information?

• What is the purpose of this token? How will it benefit Trust Wallet users?
TOKAU is a utility token for DAO vote and NFT buying functionality and so on. We have cooperations celebs like Iverson, Ian Somehalder, LunaMaya, Russell Simmons etc, they have many fans around the world, as we know many users use TrustWallet, and users don't know crypto like to know crypto by using TrustWalllet, as this we may bring TrustWallet users, and we can do airdrop events to TrustWallet users too.

• How is the token being distributed? Are you conducting an airdrop?
Details can be discovered from our whitepaper, we have done several airdrops before, for TrustWallet users we can conduct an new airdrop event.

• Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?
Yes, we've a token presale, and all presale tokens have released, and we have do a IDO(maybe a variation of ICO) on bakeryswap.

• Is the token listed on a centralized/decentralized exchange?
Yes, TOKAU is listed on CEX like MXC, LATOKEN, LBANK, and DEX like Bakeryswap. 

• Is a Smart Contract audit completed? Where can we find this information?
We havn't do a token SmartContract audit yet, but our token is opensourced on bscscan.io/token/0xC409eC8a33f31437Ed753C82EEd3c5F16d6D7e22, if it's necessary we can do the audit later on.

**Comment by cryptomanz** [comment]
Awaiting for smart contract audit.

**Comment by Cryptocool1** [comment]
please come back when smart contract audit will be ready. make sure to mention this PR so the fee can be reused

**Comment by tokau-project** [comment]
we have finish the contract audit. https://www.certik.org/projects/tokau

**Comment by cryptomanz** [comment]
Hello,
Please follow the rules for adding token, your logo should be a full screen, 256x256.

**Comment by tokau-project** [comment]
we have a new logo, how could we change i
logo
t.

**Comment by tokau-project** [comment]
hi, we have a new logo, could we change it
logo
.

**Pull request merged**
