### PR TITLE
Add PICA (on Ethereum)

### PR DESCRIPTION
**Pull request by JafarAz**
Adding token info for PICA: https://www.coingecko.com/en/coins/picasso

### CODE REVIEW

**Comment by JafarAz** [comment]
payment completed yesterday: https://explorer.bnbchain.org/tx/849A1176FE7F181F48CE8C9E3333F6775699E8F3A1FABA52B25C1305CCB26B6B

**Comment by Cryptocool1** [comment]
As per our policy, there is a minimum requirement of 10,000 holder addresses and 15,000 transactions.
See the criteria at : https://developer.trustwallet.com/listing-new-assets/requirements .

**Comment by JafarAz** [comment]
@Cryptocool1 Hey, sir, PICA is a well-known token with more than 10,000 holders across the chains it is deployed on. This PR is to add the token to the Ethereum asset list as it has just launched on Ethereum mainnet. However, there are thousands of holders across Osmosis, Secret Network, and Picasso. 

https://www.coingecko.com/en/coins/picasso

In this case, would it be possible to reopen the PR?

**Comment by JafarAz** [comment]
@cryptocoo bumping on this

**Pull request closed without merging**
