### PR TITLE
Upload ALINK logo and info

### PR DESCRIPTION
**Pull request by alinkai**

### CODE REVIEW

**Review by white10146 — COMMENTED** [review]
Approved

**Comment by Cryptocool1** [comment]
• What is the purpose of this token? How will it benefit Trust Wallet users?
 • How is the token being distributed? Are you conducting an airdrop?
 • Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?
 • Is the token listed on a centralized/decentralized exchange?
 • Is a Smart Contract audit completed? Where can we find this information?

**Comment by alinkai** [comment]
> • What is the purpose of this token? How will it benefit Trust Wallet users? • How is the token being distributed? Are you conducting an airdrop? • Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale? • Is the token listed on a centralized/decentralized exchange? • Is a Smart Contract audit completed? Where can we find this information?
>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
• What is the purpose of this token? How will it benefit Trust Wallet users?
—> ALINK is the native token of ALINK AI platform. It served as a means of payment for all services offered and requested on our decentralised marketplace platform for AI services. 
As the WEB3.0 landscape is expanding, we expect more and more users will use decentralised platform for AI services. These will certainly include TrustWallet users.


• How is the token being distributed? Are you conducting an airdrop?
 44% for Initial Offering	
16% for Ecosystem Bootstrapping
10% for Team and Advisors (2-year cliff, followed by quarterly vesting)
15% for AGI R&D
9% for Marketing
6% Reserve (5-year cliff)

We are conducting an airdrop, distributing 600,000 ALINK for participants.
 
• Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?
  —> Yes, the token offering is live now and will be ongoing for the next 120 days.

• Is the token listed on a centralized/decentralized exchange?
—> No, it is not yet listed. 

• Is a Smart Contract audit completed? Where can we find this information?
—> yes . https://solidity.finance/audits/ALINK.AI/

**Comment by Cryptocool1** [comment]
Your market data on CoinMarketCap should be tracked, on hold for now

**Comment by scotts2080** [comment]
0xdac17f958d2ee523a2206206994597c13d831ec7

**Comment by Cryptocool1** [comment]
Please come back to us once CMC requirement is met. Make sure to mention this PR so the fee can be reused.

**Pull request closed without merging**
