### PR TITLE
Add Crypto For Betting (TRC21)

### PR DESCRIPTION
**Pull request by cryptocfb**
Adding info for TRC21 token 'Crypto For Betting'.

PR created by <a href="https://assets.trustwallet.com">TW Assets Management</a>

### CODE REVIEW

**Comment by cryptocfb** [comment]
❌ number of holders not checked: please, check it manually : is 21012 you can check manualy at https://tomoscan.io/token/0x567b1e373f7285e9a32f5eeb9305b6964b6a3532#holders

**Comment by Cryptocool1** [comment]
Hello! 
• What is the purpose of this token? How will it benefit Trust Wallet users?
 • How is the token being distributed? Are you conducting an airdrop?
 • Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?
 • Is the token listed on a centralized/decentralized exchange?
 • Is a Smart Contract audit completed? Where can we find this information?

**Comment by cryptocfb** [comment]
Hello Trust team 
Many months ago we have logo on Trust Wallet, but now it not display anymore, why?

**Comment by cryptocfb** [comment]
Hello Trust team
Many months ago CFB token have logo on Trust Wallet, but now it not display anymore, why?
Please update CFB logo, Tomochain now is Viction, 
Network name: Viction  ◦ 
 • New RPC URL: https://rpc.viction.xyz ◦ 
 • Chain ID: 0x58 or 88 ◦ 
 • Current symbol: VIC ◦ 
 • Block explorer: https:/vicscan.xyz

**Pull request merged**
