### PR TITLE
Add AZ BANC SERVICES (BEP20)

### PR DESCRIPTION
**Pull request by GMA2980**
Adding info for BEP20 token 'AZ BANC SERVICES'.

PR created by <a href="https://assets.trustwallet.com">TW Assets Management</a>

### CODE REVIEW

**Comment by GMA2980** [comment]
Good day team, here is our proof of 500 TWT payment: 

https://bscscan.com/tx/0xaabeacfee00ef3f5f55f3a878e83f6060ab2a0f7f390ee49119a47c0c9b8b0ed

**Comment by GMA2980** [comment]
Our holders can be verified on our Explorer link here: 

https://bscscan.com/token/0x68ef00dAd00925e060b177c7ac59382FD0EB00c2

Here is our holders count: 10,234

Here is our total transaction: 38,391

image

**Comment by GMA2980** [comment]
Our holders can be verified on our Explorer link here:

https://bscscan.com/token/0x68ef00dAd00925e060b177c7ac59382FD0EB00c2

Here is our holders count: 10,234

Here is our total transaction: 38,391

**Comment by cryptomanz1** [comment]
• What is the purpose of this token? How will it benefit Trust Wallet users?
 • How is the token being distributed? Are you conducting an airdrop?
 • Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?
 • Is the token listed on a centralized/decentralized exchange?
 • Is a Smart Contract audit completed? Where can we find this information?

**Comment by GMA2980** [comment]
• What is the purpose of this token? How will it benefit Trust Wallet users?
AZ BANC SERVICES is redefining the landscape where cryptocurrency and forex
converge. We're not just bridging two worlds; we're creating a new one - a
realm where the agility of digital currencies and the robustness of forex
markets empower your financial journey.

• How is the token being distributed? Are you conducting an airdrop?
There was no Token distribution through an Airdrop, it is through sales
from CEX and DEX

• Did you sold the tokens at an Initial Coin Offering (ICO) or a token
presale?
There was no initial coin offering or presales.

• Is the token listed on a centralised/decentralized exchange?
Yes, Token is listed on Lbank.

• Is a Smart Contract audit completed? Where can we find this information?
yes, We have our Audit link on cyberscope
https://www.cyberscope.io/audits/coin-az-banc-services?slug=coin-az-banc-services#contact

**Comment by GMA2980** [comment]
• What is the purpose of this token? How will it benefit Trust Wallet users? 

AZ BANC SERVICES is redefining the landscape where cryptocurrency and forex converge. We're not just bridging two worlds; we're creating a new one - a realm where the agility of digital currencies and the robustness of forex markets empower your financial journey. 

• How is the token being distributed? Are you conducting an airdrop? 

There was no Token distribution through an Airdrop, it is through sales from CEX and DEX 

• Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale? 

There was no initial coin offering or presales. 

• Is the token listed on a centralised/decentralized exchange? 

Yes, Token is listed on Lbank. 

• Is a Smart Contract audit completed? Where can we find this information? 

yes, We have our Audit link on cyberscope https://www.cyberscope.io/audits/coin-az-banc-services?slug=coin-az-banc-services#contact

**Comment by GMA2980** [comment]
Good day, thanks for the update I would like to inquire on why our price
update and market data isn’t showing.

**Pull request merged**
