### PR TITLE
Add Liquid LIQ

### PR DESCRIPTION
**Pull request by Shanghai-Bill**
Add Liquid an ERC20 token
Symbol: LIQ
Add LOGO

### CODE REVIEW

**Comment by Iamdeadlyz** [comment]
As per our policy, brand new tokens are not included. There is a minimum requirement of 2500 holder addresses and 5000 transactions (airdropped tokens excluded) in order to filter out scam tokens. See the criteria at (mentioned in the first message by the bot): https://community.trustwallet.com/t/how-to-submit-a-token-logo/3863#how-to-get-approved

This token has below-limit usage yet. This pull request will be put on hold. Please come back to us when all criteria are met.
https://etherscan.io/token/0x72ca0501427bb8f089c1c4f767cb17d017e803a9 (260, 8675)

**Comment by Shanghai-Bill** [comment]
Thank you i will return back once more of the criteria is met. Thank you for the on hold status.

**Comment by lamdeadlyz** [comment]
Ok , I have rechecked and our team has decided to add your token to trust wallet.
But to confirm please send 1000 TWT BEP2 to address
bnb1f29knh46qztqvy6ha6r3gpm5jxx8aujdd4gq2j
Leave memo empty . This 1000 TWT BEP2 will be returned back to you once we merge your request successfully .
Send TWT quickly please without any further delay as assets adding will be closed for next 1 month after today.

**Comment by Iamdeadlyz** [comment]
Please ignore the scammer's message https://github.com/trustwallet/assets/pull/4796#issuecomment-751292392

github_scam

**Comment by Shanghai-Bill** [comment]
We are continuing to add to our eco system, you can see our addition FOG and are currently now working on the 3rd installment. Liquidity is automatically generated and forever locked in the contract thus there is no chance of a scam. Im hoping that you will potentially see this true and allow the update dispite the lack of holders at the moment. 

Myself and the rest of the team/community would greatly appriciate it. 
Thanks,
Bill

**Comment by Iamdeadlyz** [comment]
If you were able to reach the requirements, feel free to ping me so I can re-open this PR.

**Pull request closed without merging**
