### PR TITLE
logo and info

### PR DESCRIPTION
**Pull request by dexdevz**

### CODE REVIEW

**Comment by Cryptocool1** [comment]
PR should include only 2 files:

blockchains/smartchain/assets/0x2c094F5A7D1146BB93850f629501eB749f6Ed491/info.json
blockchains/smartchain/assets/0x2c094F5A7D1146BB93850f629501eB749f6Ed491/logo.png

**Comment by Cryptocool1** [comment]
Do you want to add "CROX Token" or "MsRasta Token" ?

**Review by croxswap — COMMENTED** [review]
updated website

**Comment by Cryptocool1** [comment]
As per our policy, brand new tokens are not included, there is a minimum requirement of 2500 holder addresses and 5000 transactions, in order to filter out scam tokens.
See the criteria at (mentioned in the first message by the bot): https://community.trustwallet.com/t/how-to-submit-a-token-logo/3863).
You may use our Assets app (in beta);  go to https://assets.trustwallet.com, log on with Github, enter contract ID, logo and some additional info, and it will create a PR for you. See https://community.trustwallet.com/t/how-to-submit-a-token-logo-using-assets-app/82957\
Closing PR for now. Please come back to us when all criteria are met.

**Pull request closed without merging**
