### PR TITLE
Add Freedom Reserve Logo and Info on Smart Chain

### PR DESCRIPTION
**Pull request by AcapSLP**
Hello, we bridged our token to binance smart chain. 

We have 510 holders on mainnet ethereum, 750 holders on xDaichain and 1000+holders on smart chain, we are ready to pay the fee of 250 TWT as stated previously

### CODE REVIEW

**Comment by AcapSLP** [comment]
Not 4 commits, only the logo and info on Smart chain, the mainnet ethereum logo is already OK

**Comment by AcapSLP** [comment]
**OK i messed up somewhere, I only need to add to smart chain assets not the previous commits back in november**

**Comment by AcapSLP** [comment]
@catenocrypt is there something wrong with it?

**Comment by catenocrypt** [comment]
There are a few technical problems:
- ERC20 token info file has been added here again, although it is already present --> hence the merge conflict. A merge of master branch would solve it; I would do this but I don't have write permission to this PR (usually I do)
- A few recently added fields are missing: type, symbol. decimals, status, id.
I will do changes and prepare new PR with this (as I cannot fix this).

**Comment by catenocrypt** [comment]
Merged with #5713 .

**Pull request closed without merging**
