### PR TITLE
Add Greed Logo

### PR DESCRIPTION
**Pull request by GreedOfficial**
Please add greed logo

### CODE REVIEW

**Comment by GreedOfficial** [comment]
• What is the purpose of this token? How will it benefit Trust Wallet users?
The Greed Ecosystem has plans for Music Label, NFTs, the Metaverse, Swaps, Farms & Staking on multiple blockchains. Holders will be rewarded in BNB.

• How is the token being distributed? Are you conducting an airdrop?
Listed on pancake swap, Hotbit and XT and people can buy from there.

• Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?
Yes. We had a presale on pinksale.

• Is the token listed on a centralized/decentralized exchange?
Listed on pancakeswap, Hotbit and XT.

• Is a Smart Contract audit completed? Where can we find this information?
https://github.com/TechRate/Smart-Contract-Audits/blob/main/October/Greed%20Token.pdf

**Comment by GreedOfficial** [comment]
Why does this say "Low token circulation: no. of holders is 5095, below limit of 25000"? Please let me know if i can make payment. We have 5k+ holders on bscscan and more on XT and HotBit exchanges.

**Comment by Cryptocool1** [comment]
submission looks good, awaiting for fee payment

**Comment by GreedOfficial** [comment]
Payment made. Please do the needful

**Pull request merged**
