### PR TITLE
Add FLORK (BEP20)

### PR DESCRIPTION
**Pull request by Flork-in**
Adding info for BEP20 token 'FLORK'.

PR created by <a href="https://assets.trustwallet.com">TW Assets Management</a>

### CODE REVIEW

**Comment by Flork-in** [comment]
I have to pay

**Comment by Flork-in** [comment]
I didn't know it was paid

**Comment by Flork-in** [comment]
sorry I sent you so many requests I thought I hadn't gone

**Comment by Cryptocool1** [comment]
As per our policy, there is a minimum requirement of 10,000 holder addresses and 15,000 transactions, in order to filter out scam tokens.
See the criteria at : https://developer.trustwallet.com/listing-new-assets/requirements .

**Comment by Flork-in** [comment]
OK thanks

**Pull request closed without merging**
