### PR TITLE
Add Okcash - OK token (BEP20) (POLYGON) (ERC20) (AVALANCHE) (ARBITRUM) (OPTIMISM) (FANTOM)

### PR DESCRIPTION
**Pull request by ogdegenblaze**
Binance Smart Chain | Adding info for BEP20 token: OK - 'Wrapped Okcash BSC'.
Polygon | Adding info for ERC20 token: OK - 'Okcash'.
Ethereum | Adding info for ERC20 token: OK - 'Okcash'.
Avalanche C | Adding info for ERC20 token: OK - 'Okcash'.
Arbitrum | Adding info for ERC20 token: OK - 'Okcash'.
Optimism | Adding info for ERC20 token: OK - 'Okcash'.
Fantom | Adding info for ERC20 token: OK - 'Okcash'.

Resubmitted with proper type fix.

Already Paid.
Payment Reference: 
https://github.com/trustwallet/assets/pull/22766 
https://github.com/trustwallet/assets/pull/24289

Project info: Okcash.
Created: 2014.
Exchanges: Bittrex, Uniswap, Pancakeswap, SushiSwap, Kyberswap, Biswap, Quickswap, TraderJoe, Apeswap, Pangolin, Mdex, BakerySwap, BTCpop.
Multi chain Proof of Stake Project.
Holders: More than 29,400 between all these chains for integration. + more than 27,140 on OK native network (https://chainz.cryptoid.info/ok/)

Established Project since 2014.
Reference links:
https://okcash.news/
https://okcash.org/
https://okcash.co/
https://oktoken.cash/
https://bitcointalk.org/index.php?topic=1028368.0
https://coinmarketcap.com/currencies/okcash/
https://discord.gg/okcash
Upcoming web3 + NFTs
https://ok.vin/

Thank you TW team.

### CODE REVIEW

**Comment by oktoshi** [comment]
Thank you, and is already paid.

Payment Reference: 
https://github.com/trustwallet/assets/pull/22766
https://github.com/trustwallet/assets/pull/24289

**Comment by oktoshi** [comment]
Synced from master w/the latest merged commits for automatic merge.

**Comment by Babayevaterane** [comment]
> ### PR Summary
> Files OK: 14 Tokens in PR: (2)
> 
> * **POLYGON** 0xd3Ac016b1B8C80EeAdDe4D186A9138C9324e4189
> * **BEP20** 0x523821d20a283d955f6205B4C9252779Cd0f964B
> 
> **Token BEP20 - 0x523821d20a283d955f6205B4C9252779Cd0f964B**: Symbol: **OK** decimals: 18 Links: [Logo](https://raw.githubusercontent.com/oktoshi/assets/master/blockchains/smartchain/assets/0x523821d20a283d955f6205B4C9252779Cd0f964B/logo.png) [Info](https://raw.githubusercontent.com/oktoshi/assets/master/blockchains/smartchain/assets/0x523821d20a283d955f6205B4C9252779Cd0f964B/info.json) [Website](https://okcash.co) [Explorer](https://bscscan.com/token/0x523821d20a283d955f6205B4C9252779Cd0f964B) Tags: defi Token check error: x number of holders not checked: please, check it manually
> 
> 
> 
> **Token POLYGON - 0xd3Ac016b1B8C80EeAdDe4D186A9138C9324e4189**: Symbol: **OK** decimals: 18 Links: [Logo](https://raw.githubusercontent.com/oktoshi/assets/master/blockchains/polygon/assets/0xd3Ac016b1B8C80EeAdDe4D186A9138C9324e4189/logo.png) [Info](https://raw.githubusercontent.com/oktoshi/assets/master/blockchains/polygon/assets/0xd3Ac016b1B8C80EeAdDe4D186A9138C9324e4189/info.json) [Website](https://okcash.co) [Explorer](https://polygonscan.com/token/0xd3Ac016b1B8C80EeAdDe4D186A9138C9324e4189) Tags: defi white_check_mark Check OK
> 
>

**Review by scotts2080 — COMMENTED** [review]
[]()

**Pull request merged**
