### PR TITLE
Add TWT logo and info

### PR DESCRIPTION
**Pull request by DorkLordToken**
For DorkLord token! $DORKL

Already on Gate.io, MEXC, Lbank, BitMart, Poloniex, Bitget..

CMC https://coinmarketcap.com/currencies/dork-lord/

CG https://www.coingecko.com/en/coins/dork-lord

### CODE REVIEW

**Comment by DorkLordToken** [comment]
Hello? I see some red ❌s did i miss some stuff that wont work? before pay9ing want to make sure all checks off the list.

**Comment by DorkLordToken** [comment]
hey im submitting payment now looks like all is good

**Comment by DorkLordToken** [comment]
paid:

https://explorer.bnbchain.org/tx/8DAC6CC1EFE4185B5375C9F440904C99964411D4A02D0923E50E9207E7565ED2?fbclid=IwAR3TN2olzGPp9RyXMI3S86eWI1XSLItHXMuRN3_9UMJH61xYFfPiMDwWMBg

**Comment by cryptomanz1** [comment]
As per our policy, there is a minimum requirement of 10,000 holder addresses and 15,000 transactions.
See the criteria at : https://developer.trustwallet.com/listing-new-assets/requirements .

**Comment by DorkLordToken** [comment]
hey we have 9 big CEXes there is many exchanges and therefore many holders not counted on the blockchain! it is stated as per policy you will determine that criteria per user basis. Please continue with adding the logo and links!

**Comment by DorkLordToken** [comment]
@cryptomanz1 @Cryptocool1 please reconsider this fact we are on MEXC LBANK BITMART GATE.IO including 5 more.. we have 10.000 holders in total at least when including all these exchanges.

**Comment by DorkLordToken** [comment]
explain why this coin has TrustWallet logo and info updated and have half the holders? im confused?


photo_2023-09-12_15-19-14

**Pull request closed without merging**
