### PR TITLE
Add KAVA (KAVA)

### PR DESCRIPTION
**Pull request by EJK64**
This PR is being closed due to inactivity. If you wish to continue, please have us reopen the PR before sending your payment, or just create a new one.
Do NOT send payments for closed PR, as the fee may by lost!
  (48 vs. 48 hrs)

### CODE REVIEW

**Comment by EJK64** [comment]
I have payed already for a closed PR  #15386 Did not know it was closed with errors.

**Comment by Cryptocool1** [comment]
Payment was not found by the bot; could you provide TXID or date for checking?

**Comment by EJK64** [comment]
E7F3B6EF02A63DA1FDFA0B6F32777862FB8EE65BF1C3889576EE8BF9A57D69FF
2021-11-10

**Comment by EJK64** [comment]
2021-11-10

**Comment by EJK64** [comment]
Could you please match my payment? The TxID is
E7F3B6EF02A63DA1FDFA0B6F32777862FB8EE65BF1C3889576EE8BF9A57D69FF

**Pull request closed without merging**
