### PR TITLE
add mini football

### PR DESCRIPTION
**Pull request by daniel13222**

### CODE REVIEW

**Comment by daniel13222** [comment]
payment made.

**Comment by cryptomanz** [comment]
hello, can you answer some questions?
• What is the purpose of this token? How will it benefit Trust Wallet users?
 • How is the token being distributed? Are you conducting an airdrop?
 • Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?
 • Is the token listed on a centralized/decentralized exchange?
 • Is a Smart Contract audit completed? Where can we find this information?

**Comment by daniel13222** [comment]
• What is the purpose of this token? How will it benefit Trust Wallet users?
By adding our logo etc. Trust Wallet users will avoid being scammed by other tokens that are pretending to be us,
we are 1 day old and we have more then 10,000 holders and counting.
• How is the token being distributed? Are you conducting an airdrop?
The token is distributed normally, no airdrops.
• Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?
Yes we did have a presale on 12th of August with a softcap and hardcap of 600/1200 which was filled.
• Is the token listed on a centralized/decentralized exchange?
Pancakeswap.
• Is a Smart Contract audit completed? Where can we find this information?
We have applied at TechRate and the audit is on the way.

**Comment by cryptomanz** [comment]
Awaiting for smart contract audit.

**Comment by daniel13222** [comment]
?

**Comment by daniel13222** [comment]
Hey thanks,
I can't see the logo on trust wallet. why?

**Pull request merged**
