### PR TITLE
Update FEED description

### PR DESCRIPTION
**Pull request by SebastianFEED**
Added FEED description & Logo

### CODE REVIEW

**Comment by Cryptocool1** [comment]
Submission looks good. awaiting fee payment.

**Comment by SebastianFEED** [comment]
El 07-05-2021 03:00, CryptoA escribió:

> Submission looks good. awaiting fee payment. 
> 
> --
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub [1], or unsubscribe [2].

Paid! 250 TWT

-- 
Sebastian 

***@***.*** 

https://feedtoken.org/ 

 

Links:
------
[1]
https://github.com/trustwallet/assets/pull/7482#issuecomment-834090961
[2]

**Comment by SebastianFEED** [comment]
El 07-05-2021 08:36, CryptoA escribió:

> Merged #7482 [1] into master. 
> 
> --
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub [2], or unsubscribe [3].

We upload a wrong image I think. Can we change it? Cause there is white
around our logo... It is not a PNG, even the file is .png

-- 
Sebastian 

***@***.*** 

https://feedtoken.org/ 

 

Links:
------
[1] https://github.com/trustwallet/assets/pull/7482
[2] https://github.com/trustwallet/assets/pull/7482#event-4701234657
[3]

**Comment by SebastianFEED** [comment]
El 07-05-2021 08:36, CryptoA escribió:

> Merged #7482 [1] into master. 
> 
> --
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub [2], or unsubscribe [3].

Hello! When does the price of our token is shown in TrustWallet? We are
already listed on Coingecko. Do we have to do anything?

-- 
Sebastian 

***@***.*** 

https://feedtoken.org/ 

 

Links:
------
[1] https://github.com/trustwallet/assets/pull/7482
[2] https://github.com/trustwallet/assets/pull/7482#event-4701234657
[3]

**Comment by SebastianFEED** [comment]
El 13-05-2021 16:13, Sebastian // FEED Token escribió:

> El 07-05-2021 08:36, CryptoA escribió:
> 
>> Merged #7482 [1] into master. 
>> 
>> --
>> You are receiving this because you authored the thread.
>> Reply to this email directly, view it on GitHub [2], or unsubscribe [3].
> 
> Hello! When does the price of our token is shown in TrustWallet? We are already listed on Coingecko. Do we have to do anything?
> 
> --

Hello, we are in CMC too...
https://coinmarketcap.com/currencies/feed-token/
Sebastian 

***@***.*** 

https://feedtoken.org/ 

 

Links:
------
[1] https://github.com/trustwallet/assets/pull/7482
[2] https://github.com/trustwallet/assets/pull/7482#event-4701234657
[3]

**Comment by SebastianFEED** [comment]
El 07-05-2021 08:36, CryptoA escribió:

> Merged #7482 [1] into master. 
> 
> --
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub [2], or unsubscribe [3].

Hello. What do we need to do so our price is show in TWT? 

Sebastian 

***@***.*** 

https://feedtoken.org/ 

 

Links:
------
[1] https://github.com/trustwallet/assets/pull/7482
[2] https://github.com/trustwallet/assets/pull/7482#event-4701234657
[3]

**Comment by SebastianFEED** [comment]
El 07-05-2021 08:35, merge-fee-bot[bot] escribió:

> Fee is PAID, fantastic! Thanks! 
> 
> The PR will be evaluated soon by a maintainer, and if merged, the new logos should be visible in Trust Wallet.
> Please note that the app caches logos (up to several days; if you want to see changes immediately, use a new installation). See the assets FAQ [1].
> ***@***.*** [2], @catenocrypt [3] & @Iamdeadlyz [4]: please take note.) 
> 
> (250 TWT [5]) 
> 
> --
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub [6], or unsubscribe [7].

-hello what do we need to do so our price is shown in TWT?
Sebastian 

***@***.*** 

https://feedtoken.org/ 

 

Links:
------
[1] https://github.com/trustwallet/assets#faq
[2] https://github.com/zachzwei
[3] https://github.com/catenocrypt
[4] https://github.com/Iamdeadlyz
[5]
https://explorer.binance.org/tx/32914A10C058C46907B93AA85D3BB9ED6756DCB1FFAA644F42EC28BE0D26D8AD
[6]
https://github.com/trustwallet/assets/pull/7482#issuecomment-834292559
[7]

**Comment by SebastianFEED** [comment]
Hello Crypto A, we paid the fee, the logo got updated but the price
still don't show.  

El 07-05-2021 08:31, Sebastian // FEED Token escribió:

> El 07-05-2021 03:00, CryptoA escribió:
> 
>> Submission looks good. awaiting fee payment. 
>> 
>> --
>> You are receiving this because you authored the thread.
>> Reply to this email directly, view it on GitHub [1], or unsubscribe [2].
> 
> Paid! 250 TWT
> 
> -- 
> Sebastian 
> 
> ***@***.*** 
> 
> https://feedtoken.org/

-- 
Sebastian 

***@***.*** 

https://feedtoken.org/ 

 

Links:
------
[1]
https://github.com/trustwallet/assets/pull/7482#issuecomment-834090961
[2]

**Comment by Cryptocool1** [comment]
https://community.trustwallet.com/t/why-is-there-no-token-logo-or-price/138596

**Comment by SebastianFEED** [comment]
But we are in coingecko 

https://www.coingecko.com/es/monedas/feed-token

18-05-2021 16:58, CryptoA escribió:

> https://community.trustwallet.com/t/why-is-there-no-token-logo-or-price/138596 
> 
> --
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub [1], or unsubscribe [2].

-- 
Sebastian 

***@***.*** 

https://feedtoken.org/ 

 

Links:
------
[1]
https://github.com/trustwallet/assets/pull/7482#issuecomment-843513235
[2]

**Comment by SebastianFEED** [comment]
> https://community.trustwallet.com/t/why-is-there-no-token-logo-or-price/138596

We are in Coingecko from May 9th
https://www.coingecko.com/es/monedas/feed-token

**Comment by SebastianFEED** [comment]
Hello. We are listed on Coingecko since day 9th.. 

El 18-05-2021 16:58, CryptoA escribió:

> https://community.trustwallet.com/t/why-is-there-no-token-logo-or-price/138596 
> 
> --
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub [1], or unsubscribe [2].

-- 
Sebastian 

***@***.*** 

https://feedtoken.org/ 

 

Links:
------
[1]
https://github.com/trustwallet/assets/pull/7482#issuecomment-843513235
[2]

**Comment by SebastianFEED** [comment]
> https://community.trustwallet.com/t/why-is-there-no-token-logo-or-price/138596

Morning! Could you check our token asap? We are listed in Coingecko since May 9th

**Comment by SebastianFEED** [comment]
Hello Crypto A. 

We are in Coingecko. Why our price is not shown in Trustwallet? 

El 18-05-2021 16:58, CryptoA escribió:

> https://community.trustwallet.com/t/why-is-there-no-token-logo-or-price/138596 
> 
> --
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub [1], or unsubscribe [2].

-- 
Sebastian 

***@***.*** 

https://feedtoken.org/ 

 

Links:
------
[1]
https://github.com/trustwallet/assets/pull/7482#issuecomment-843513235
[2]

**Comment by TheNobleDev** [comment]
@Cryptocool1 @zachzwei @catenocrypt @Iamdeadlyz

Kindly resolve this. The token price is not visible in trust wallet, despite the token being listed on coingecko. (https://www.coingecko.com/es/monedas/feed-token)

**Comment by SebastianFEED** [comment]
@Cryptocool1 @zachzwei @catenocrypt @Iamdeadlyz

Kindly resolve this. The token price is not visible in trust wallet, despite the token being listed on coingecko. (https://www.coingecko.com/es/monedas/feed-token)

**Comment by SebastianFEED** [comment]
Hello any News? We are on coingecko since 9th may 

El 18-05-2021 16:58, CryptoA escribió:

> https://community.trustwallet.com/t/why-is-there-no-token-logo-or-price/138596 
> 
> --
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub [1], or unsubscribe [2].

-- 
Sebastian 

***@***.*** 

https://feedtoken.org/ 

 

Links:
------
[1]
https://github.com/trustwallet/assets/pull/7482#issuecomment-843513235
[2]

**Comment by SebastianFEED** [comment]
> @Cryptocool1 @zachzwei @catenocrypt @Iamdeadlyz
> 
> Kindly resolve this. The token price is not visible in trust wallet, despite the token being listed on coingecko. (https://www.coingecko.com/es/monedas/feed-token)

Please could you check over it??

**Comment by SebastianFEED** [comment]
Hello! Coingecko Shows our price from May 9th.. when is price shown in
TWT? 

El 18-05-2021 16:58, CryptoA escribió:

> https://community.trustwallet.com/t/why-is-there-no-token-logo-or-price/138596 
> 
> --
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub [1], or unsubscribe [2].

-- 
Sebastian 

***@***.*** 

https://feedtoken.org/ 

 

Links:
------
[1]
https://github.com/trustwallet/assets/pull/7482#issuecomment-843513235
[2]

**Comment by SebastianFEED** [comment]
> @Cryptocool1 @zachzwei @catenocrypt @Iamdeadlyz
> 
> Kindly resolve this. The token price is not visible in trust wallet, despite the token being listed on coingecko. (https://www.coingecko.com/es/monedas/feed-token)

Please, I need this solved asap

**Comment by SebastianFEED** [comment]
https://coinmarketcap.com/currencies/feed-token/ 

We are listed on CMC. Please update our price please

El 18-05-2021 16:58, CryptoA escribió:

> https://community.trustwallet.com/t/why-is-there-no-token-logo-or-price/138596 
> 
> --
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub [1], or unsubscribe [2].

-- 
Sebastian 

***@***.*** 

https://feedtoken.org/ 

 

Links:
------
[1]
https://github.com/trustwallet/assets/pull/7482#issuecomment-843513235
[2]

**Pull request merged**
