### PR TITLE
Chain Games Logo and Info

### PR DESCRIPTION
**Pull request by ronakpatel3110**
https://etherscan.io/token/0xC4C2614E694cF534D407Ee49F8E44D125E4681c4

### CODE REVIEW

**Comment by catenocrypt** [comment]
Could you please add an `info.json` file next to the logo.png, with info about the project, of the form:
https://github.com/trustwallet/assets/blob/master/blockchains/ethereum/assets/0x0000000000085d4780B73119b644AE5ecd22b376/info.json

**Comment by zachzwei** [comment]
Please provide more details about this project. We will be closing this for now.
You can reopen when you have met the requirements mentioned here:
https://community.trustwallet.com/t/how-to-submit-a-token-logo/3863#how-to-get-approved

You can follow this format when adding an info.json file:

``` {
   "name":"Bitcoin",
   "website":"https://bitcoin.org",
   "source_code":"https://github.com/bitcoin",
   "white_paper":"https://bitcoin.org/bitcoin.pdf",
   "short_description":"Bitcoin is a cryptocurrency and worldwide payment system.",
   "explorer":"https://blockchain.info",
   "research":"https://research.binance.com/en/projects/bitcoin"
}

**Comment by ronakpatel3110** [comment]
We have added info.json in commit : https://github.com/bravoadam/assets/commit/be46c86832999b1005c152c0c8574180d83b58e6

**Comment by AngelNetwork** [comment]
@zachzwei @catenocrypt

**Comment by catenocrypt** [comment]
Followup: #3662 .

**Pull request closed without merging**
