### PR TITLE
Add BemChain (TRC20)

### PR DESCRIPTION
**Pull request by BCNToken**
Adding info for TRC20 token 'BemChain'.

PR created by <a href="https://assets.trustwallet.com">TW Assets Management</a>

### CODE REVIEW

**Comment by Cryptocool1** [comment]
Hello
• What is the purpose of this token? How will it benefit Trust Wallet users?
 • How is the token being distributed? Are you conducting an airdrop?
 • Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?
 • Is the token listed on a centralized/decentralized exchange?
 • Is a Smart Contract audit completed? Where can we find this information?

**Comment by BCNToken** [comment]
1- BemChain's purpose is to create a custom blockchain solution that supports the BCNGarden GameFi project, enabling decentralized gaming, seamless integration of GameFi elements, and providing a secure, scalable, and collaborative platform for all stakeholders. BemChain will revolutionize the gaming industry and pave the way for a new era of blockchain-based gaming experiences.

2- BemChain's integration with Trust Wallet will provide Trust Wallet users with access to the BCNGarden GameFi project, secure and transparent transactions, seamless integration, access to NFTs, and community engagement.

3- BCN token will be distributed through a combination of private and public sales, liquidity mining, and staking rewards. This will ensure a fair and transparent distribution process and incentivize users to contribute to the growth and stability of the BemChain ecosystem. There is no airdrop

4- we have just token pre-sale

5- yes there is some link of 
our centralized:
https://coinsbit.io/trade/BCN_USDT
https://p2pb2b.com/trade/BCN_USDT/
Decentralized:
https://sunswap.com/#/scan/detail/TAoA331n3iKDkR62kAZ4H2n3vNL7y3d8x9

6- yes, The smart contracts used in the BemChain ecosystem will be audited by reputable third-party auditing firms to ensure that they are secure and free from vulnerabilities. 

https://tronscan.org/#/token20/TAoA331n3iKDkR62kAZ4H2n3vNL7y3d8x9/code

**Comment by BCNToken** [comment]
bemscan.io (Blockchain POA)
bcngarden.io (Gamefi BCN)

**Comment by cryptomanz1** [comment]
Please send your smart contract audit here

**Comment by BCNToken** [comment]
we dont have audit yet if is neccesery please provice me a site to get audit or doing with our team

**Comment by Cryptocool1** [comment]
We require audit from reputable companies. For example: Certik, Techrate, Hacken, Dessert Finance

**Comment by BCNToken** [comment]
thanks alot for your helping us we contact with dessert finance and start collaborate with them and its been complete 24 hours later . is there any problem? thanks for waiting

**Comment by Cryptocool1** [comment]
Thanks. Let us know once audit is done

**Comment by BCNToken** [comment]
Hey dear supporter 
Sorry for delay here you are the audit report from Dessert finance 

https://dessertswap.finance/audits/BCN-Token-TRC-Audit-51013283.pdf

**Comment by Cryptocool1** [comment]
Thank you. 
Are you listed on CMC?

**Comment by BCNToken** [comment]
Yes of course this is our cmc page :
https://coinmarketcap.com/currencies/bemchain/

**Pull request merged**
