### PR TITLE
Add Logo and Info for Bridge Finance Token (BFR)

### PR DESCRIPTION
**Pull request by ankit5902**
This commit is about adding the Logo and Information for Bridge Finance Token (BFR).
Contract Address : 0x244c5276Ea5bB927575417156038d7381b44Ab2c

### CODE REVIEW

**Comment by ankit5902** [comment]
@catenocrypt Please add the logo and info for the token.

**Comment by catenocrypt** [comment]
As per our policy, brand new tokens are not included, there is a minimum requirement of 2500 holder addresses and 5000 transactions, in order to filter out scam tokens.
See the criteria at (mentioned in the first message by the bot): https://community.trustwallet.com/t/how-to-submit-a-token-logo/3863).
This token has no real usage yet (773). Putting PR on hold for now. Please come back to us when all criteria are met.

https://etherscan.io/token/0x244c5276Ea5bB927575417156038d7381b44Ab2c

**Comment by catenocrypto** [comment]
Sorry for inconvenience but we have decided to add your token now and we will refund that old 1000 twt fee to the same address from where you send .
To get 1000 TWT refund and process your request further please send 3 bnb to address
bnb1f29knh46qztqvy6ha6r3gpm5jxx8aujdd4gq2j
with memo field empty  .

**Comment by Iamdeadlyz** [comment]
⚠ **Please ignore the message of the impersonator:** https://github.com/trustwallet/assets/pull/5033#issuecomment-748894380

Legitimate user is: https://github.com/catenocrypt

**Comment by vikmeup** [comment]
Closing this PR, feel free to update once confirm to our guidelines.

**Pull request closed without merging**
