### PR TITLE
Add Burn1 Coin Logo

### PR DESCRIPTION
**Pull request by Burn1Coin**
Please add the Burn1 Coin Logo to replace the default BEP20 logo

### CODE REVIEW

**Comment by Burn1Coin** [comment]
Hello, we have abandoned the old token, Burn1. Is it possible to remove that logo?

**Comment by Cryptocool1** [comment]
is this contract abandoned?
0x31A9042dCE0C13975D04d0E9758Cb7B596F0dD43

**Comment by Burn1Coin** [comment]
> is this contract abandoned?
> 0x31A9042dCE0C13975D04d0E9758Cb7B596F0dD43

no.

**Comment by Burn1Coin** [comment]
this is the old token that is abandoned. 0x07e330a210b8128c7b32476704c3052cd8c10e5b

> is this contract abandoned?
> 0x31A9042dCE0C13975D04d0E9758Cb7B596F0dD43

this is the old token that is abandoned. 0x07e330a210b8128c7b32476704c3052cd8c10e5b

**Comment by Burn1Coin** [comment]
> **PR Summary** Files OK, 2Files in PR: 2 Token in PR: BEP20 0x31A9042dCE0C13975D04d0E9758Cb7B596F0dD43 Symbol: **BURN1COIN** decimals: 9 Links: [Logo](https://raw.githubusercontent.com/Burn1Coin/assets/master/blockchains/smartchain/assets/0x31A9042dCE0C13975D04d0E9758Cb7B596F0dD43/logo.png) [Info](https://raw.githubusercontent.com/Burn1Coin/assets/master/blockchains/smartchain/assets/0x31A9042dCE0C13975D04d0E9758Cb7B596F0dD43/info.json) [Website](https://burn1.today) [Explorer](https://bscscan.com/token/0x31A9042dCE0C13975D04d0E9758Cb7B596F0dD43) Token check error: ❌ The links field cannot be empty ✓ Token type OK (BEP20); Contract/ID is OK; Type field OK; Symbol field OK; Decimals field OK; Description field OK; Website field OK; Explorer field OK; Status field OK; Id field OK; Logo image type is OK (image/png); Logo image size is OK (10.172 kB); Logo dimensions OK (253x256); Token circulation OK (no. of holders: 7745);
> 
> 

is there something that I need to do to fix this? I am not a developer but am the founder.

**Comment by cryptomanz** [comment]
Hello,
• What is the purpose of this token? How will it benefit Trust Wallet users?
 • How is the token being distributed? Are you conducting an airdrop?
 • Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?
 • Is the token listed on a centralized/decentralized exchange?
 • Is a Smart Contract audit completed? Where can we find this information?

**Comment by Burn1Coin** [comment]
Hello,
The purpose of the Burn1coin Token Just to Autogenerate funds for Cannabis Reform. The benefits Trust Wallet users By giving them theBy giving them the opportunity To engage in philanthropic capitalism. By investing in Burn1Coin you can do good and do well at the same time.
This token was airdropped to roughly 7300 holders of the original Burn1 contract. The balance of those holders have purchased through pancake swap exchange
We did not offer an ICO. Burn1 token (the original Token) was stealth fair launched on May 7, 2021. We are dropped holders on July 30, 2021 to make modifications within our smart contract that would allow us to interact with Dispensaries for future partnerships and utility. 
Yes we had an initial tech rate audit done in August.


Burn1 Coin Team

**Comment by Burn1Coin** [comment]
Here is the initial tech rate audit. 




Burn1 Coin Team

**Comment by Cryptocool1** [comment]
could you add the links?
see the example here: https://developer.trustwallet.com/assets/repository_details

**Comment by Burn1Coin** [comment]
Here are our socials.  I have zero idea how to modify and add the links. I’m sorry. I have good ideas but am not a dev. 


Telegram- 
https://t.me/Burn1Coin 

Twitter- 
https://mobile.twitter.com/Burn1Coin   

TikTok-
***@***.***

Facebook- 
https://www.facebook.com/Burn1coin/

Instagram-
Burn1Coin

Website
https://www.burn1.today/ 

Youtube- 
https://www.youtube.com/c/Burn1CoinOfficialChannel

Linkedin 
https://www.linkedin.com/company/burn1-coin/ 


Medium
https://burn1coin.medium.com

Reddit 
https://www.reddit.com/r/Burn1Coin/

Stocktwits
https://stocktwits.com/symbol/BURN1COIN.X





Burn1 Coin Team

**Comment by Burn1Coin** [comment]
Thank you!

Burn1 Coin Team

**Comment by Burn1Coin** [comment]
Hello,
I wanted to connect because I just noticed that our value just disappeared in trust wallet. We are also having issues with CoinMarketCap not updating our correct value. 

Thanks in advance. 

Burn1 Coin Team

**Pull request merged**
