### PR TITLE
Adding DiemLibre to Trust Wallet Crypto Assets (Update)

### PR DESCRIPTION
**Pull request by diemlibredlb**
An update of the last PR #17607  and #17621  has been made.
More token information has been added following the requirements.

Here are our Token Trackers both EtherScan and BSCScan

EtherScan: https://etherscan.io/token/0x87C22615435998D69ACA34889D03155B694a94fc
BSCScan: https://bscscan.com/token/0x87c22615435998d69aca34889d03155b694a94fc

We hope they meet up with the number of holders and transactions.
Thank you for understanding.

### CODE REVIEW

**Review by kophyo1234 — APPROVED** [review]

**Comment by diemlibredlb** [comment]
Hello Trust Wallet,

Payment has been made ✅
Receiving Address: bnb1tqq9llyr3dyjd559dha6z5r5etk3qfwk07m098
Amount: 5 BNB
Memo: 17622

Transaction Hash: https://explorer.binance.org/tx/5D0A471FE585333C43E83A063620118BE4218A20C3343F766CED8842C720DD8A

Thank you for your collaboration.
What is next?

**Comment by cryptomanz** [comment]
• What is the purpose of this token? How will it benefit Trust Wallet users?
 • How is the token being distributed? Are you conducting an airdrop?
 • Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?
 • Is the token listed on a centralized/decentralized exchange?
 • Is a Smart Contract audit completed? Where can we find this information?

**Comment by diemlibredlb** [comment]
• What is the purpose of this token?
The purpose of DiemLibre $DLB Project is to improve privacy on the blockchain.

• How will it benefit Trust Wallet users?
Trust wallet will be able to hold $DLB and easily be a part of the $DLB ecosystem.

• How is the token being distributed?
Manually by us, through our Secure Web App > secure.diemlibre.org

• Are you conducting an airdrop?
Yes, we did.

• Did you sell the tokens at an Initial Coin Offering (ICO) or a token presale?
Yes, we did via our Secure Web App > secure.diemlibre.org

• Is the token listed on a centralized/decentralized exchange?
Yes, it is traded on p2pb2b.io 
https://p2pb2b.io/trade/DLB_ETH/

• Is a Smart Contract audit completed?
Not, yet. We are currently in contact with some Auditing companies to complete this as soon as possible.

Source Code: https://etherscan.io/address/0x87c22615435998d69aca34889d03155b694a94fc#code

• Where can we find this information?
Like we said above it is not yet complete.
We are working on that.

**Comment by Cryptocool1** [comment]
awaiting for smart contract audit, on hold for now

**Comment by diemlibredlb** [comment]
Please, we want you to reconsider our application.
As you should have informed us about this earlier about the obligation of the Audit.

We assumed we completed all the required fields.
This is setting us back because we are forced to rush over auditing increasing our overall cost.
Thus affecting our DApp development which is more important to the community as well.

You can view our code > https://etherscan.io/address/0x87c22615435998d69aca34889d03155b694a94fc#code

Thank you for understanding.

**Comment by Cryptocool1** [comment]
you can see all requirements in our documentary.
https://developer.trustwallet.com/assets/requirements

**Comment by diemlibredlb** [comment]
This is just not fair on us, as some auditing take up to 4 weeks or more.
How are we supposed to wait for that long?

Screen Shot 2022-01-26 at 11 01 39

This is much money to be playing with.
It is a basic ERC20 token.
Please, reconsider us.

**Comment by Cryptocool1** [comment]
You should see our requirements before submitting and paying the fee

**Comment by diemlibredlb** [comment]
Which auditing do you propose with cheaper rates?

**Comment by Cryptocool1** [comment]
4CF9B7D7-D93A-4CB9-8A39-3B240C04C64C

**Comment by Cryptocool1** [comment]
Certik, techrate, dessert finance

**Comment by diemlibredlb** [comment]
We understand but we are disappointed.

**Comment by cryptomanz** [comment]
Please come back to us when all criteria are met.
When creating a new PR make sure to mention this PR, so that we can see that fee has been paid already here.

**Pull request closed without merging**
