### PR TITLE
Create 0x73e4A6B80F8De0aA3f95331c5a93e7f8431B6d95

### PR DESCRIPTION
**Pull request by famacoin20**
Fama

### CODE REVIEW

**Comment by famacoin20** [comment]
@zachzwei

**Comment by catenocrypt** [comment]
Could you please add an `info.json` file next to the logo.png, of the form:
https://github.com/trustwallet/assets/blob/master/blockchains/ethereum/assets/0x0000000000085d4780B73119b644AE5ecd22b376/info.json

**Comment by famacoin20** [comment]
> Could you please add an `info.json` file next to the logo.png, of the form:
> https://github.com/trustwallet/assets/blob/master/blockchains/ethereum/assets/0x0000000000085d4780B73119b644AE5ecd22b376/info.json

ok， wait a sec

**Comment by famacoin20** [comment]
Info.json updated @catenocrypt

**Pull request merged**
