### PR TITLE
OMI Logo Update

### PR DESCRIPTION
**Pull request by care-veve**

### CODE REVIEW

**Comment by care-veve** [comment]
How long the process will take to get it done..

**Review by care-veve — COMMENTED** [review]
Kindly add the files to the repo

**Comment by catenocrypt** [comment]
Correction needed:  Please fill the description field with a few-sentence summary.

**Review by care-veve — COMMENTED** [review]
Description Added,Kindly do the needful

**Review by care-veve — COMMENTED** [review]
Done

**Comment by care-veve** [comment]
@catenocrypt Kindly do the needful ASAP.. As asked added the description

**Review by care-veve — COMMENTED** [review]
Kindly do the needful...

**Pull request merged**
