### PR TITLE
Add American Dream (BEP20)

### PR DESCRIPTION
**Pull request by AmericanDreamToken**
Adding info for BEP20 token 'American Dream'.

PR created by <a href="https://assets.trustwallet.com">TW Assets Management</a>

### CODE REVIEW

**Comment by AmericanDreamToken** [comment]
Hello I have sent out the payment. We been accepted to CMC the price is showing on Trustwallet but not the logo. 
We're a new project but rapidly growing. our CMC https://coinmarketcap.com/currencies/american-dream/

**Comment by Cryptocool1** [comment]
As per our policy, brand new tokens are not included, there is a minimum requirement of 25,000 holder addresses and 50,000 transactions, in order to filter out scam tokens.
See the criteria at : https://developer.trustwallet.com/assets/requirements .

**Comment by AmericanDreamToken** [comment]
> As per our policy, brand new tokens are not included, there is a minimum requirement of 25,000 holder addresses and 50,000 transactions, in order to filter out scam tokens. See the criteria at : https://developer.trustwallet.com/assets/requirements .

Yes I fully understand that but we're no scam token nor are we trying to scam anyone. We have fully provided our government IDs to TechAudit company and whenever we did our Presale. We're making Video AMA's for our community You can check them here. ( https://www.youtube.com/watch?v=A54E3_8dimM&t=2s&ab_channel=AmericanDreamToken ) so we have no issue showing our faces and our identities. We stand strong behind our project and we truly believe we can make a difference and provide safe space for Decentralized investors.  so to quote you on "  in order to filter out scam tokens. ". we can provide anything you guys need to prove we're not a scam.

**Comment by AmericanDreamToken** [comment]
@Cryptocool1 @catenocrypt @zachzwei @cryptomanz I can provide anything that you guys require for proof. we're not here to mess around.

**Comment by cryptomanz** [comment]
Please come back to us when all criteria are met.
When creating a new PR make sure to mention this PR, so that we can see that fee has been paid already here.

**Comment by AmericanDreamToken** [comment]
Ok thank you

**Pull request closed without merging**
