### PR TITLE
Fixing $MERL token on trust swap

### PR DESCRIPTION
**Pull request by amerlinmagician**
Currently $MERL or Merlin Lab is added on trustswap but some information is missing such as logo. Many of our community members have been begging us to fix it, this is us taking that step forward to make sure you have everything you need to do so. Please tell Jean thank you for all the help,
Kind Regards,
Jonathan.

### CODE REVIEW

**Comment by amerlinmagician** [comment]
> **PR Summary**
> Files OK, 2Files in PR: 2
> Token in PR: BEP20 0xda360309c59cb8c434b28a91b823344a96444278
> Symbol: **MERL** decimals: 18
> Links: [Logo](https://raw.githubusercontent.com/amerlinmagician/assets/master/blockchains/smartchain/assets/0xda360309c59cb8c434b28a91b823344a96444278/logo.png) [Info](https://raw.githubusercontent.com/amerlinmagician/assets/master/blockchains/smartchain/assets/0xda360309c59cb8c434b28a91b823344a96444278/info.json) [Website](https://merlinlab.com/farm) [Explorer](https://bscscan.com/token/0xDA360309C59CB8C434b28A91b823344a96444278)
> Token check error:
> ❌ Contract is not in checksum format, should be 0xDA360309C59CB8C434b28A91b823344a96444278 (not 0xda360309c59cb8c434b28a91b823344a96444278). Please rename it. You may need to rename to a temp name first, then to the checksum format, because lowercase-uppercase-only renames are often ignored by the Git client or the filesystem.
> ❌ Id field does not match contract, should be 0xda360309c59cb8c434b28a91b823344a96444278, not 0xDA360309C59CB8C434b28A91b823344a96444278. Please rename.
> ✓ Token type OK (BEP20); Type field OK; Symbol field OK; Decimals field OK; Description field OK; Website field OK; Explorer field OK; Status field OK; Logo image type is OK (image/png); Logo image size is OK (56.018 kB); Logo dimensions OK (256x256); Token circulation OK (no. of holders: 25398);
> 
> 

this is wrong we've updated already please check the file

**Comment by Cryptocool1** [comment]
correction needed:
Contract is not in checksum format, should be 0xDA360309C59CB8C434b28A91b823344a96444278

**Comment by amerlinmagician** [comment]
It's not possible for me to change the folders name, please advise should i resubmit a request? 



> correction needed:
> Contract is not in checksum format, should be 0xDA360309C59CB8C434b28A91b823344a96444278

**Comment by amerlinmagician** [comment]
I've tried changing the directory but now the logo file is binned because it's in a different branch

**Comment by amerlinmagician** [comment]
how do I fix this? I keep trying but it's resulting in the same issue, please help

**Comment by amerlinmagician** [comment]
Is it fixed now? please make sure that the logo file is in the directory as well

**Comment by amerlinmagician** [comment]
Should be fixed now apologies for the double token

**Comment by amerlinmagician** [comment]
> correction needed:
> Contract is not in checksum format, should be 0xDA360309C59CB8C434b28A91b823344a96444278

All finished, please update

**Pull request merged**
