### PR TITLE
YFbitcoin

### PR DESCRIPTION
**Pull request by ginmark**

### CODE REVIEW

**Comment by ginmark** [comment]
payment made

**Comment by catenocrypt** [comment]
The info.json is incorrect JSON (some commas are missing).  Please fix.

**Comment by catenocrypt** [comment]
No action for one month, closing.

**Comment by ginmark** [comment]
[info.json.txt](https://github.com/trustwallet/assets/files/6067358/info.json.txt)


this is the fixed error file please reopen and merge thanks

**Comment by catenocrypt** [comment]
Please, only you can update the files in this PR -- I cannot (you gave no permission to upstream repo).
Please update the info.json file in this  PR to:

```json
{
    "name": "YFBITCOIN",
    "type": "ERC20",
    "symbol": "YFBTC",
    "decimals": 18,
    "website": "https://yfbtc.net",
    "short_description": "Yfswap is an AMM based Dex created with the intention of providing a one stop solution,DeFi farming, staking and a Dex Exchange all in one.",
    "explorer": "https://etherscan.io/token/0xff034d12353867fc4228f4ae3e689cd6dcaad120",
    "status": "active",
    "id": "0xff034D12353867fC4228f4Ae3E689CD6dCAad120"
}
```

**Comment by ginmark** [comment]
change has been committed

**Comment by catenocrypt** [comment]
Corrections made, newly introduced fields added.

**Comment by catenocrypt** [comment]
As per our policy, brand new tokens are not included, there is a minimum requirement of 2500 holder addresses and 5000 transactions, in order to filter out scam tokens.
See the criteria at (mentioned in the first message by the bot): https://community.trustwallet.com/t/how-to-submit-a-token-logo/3863).
This token has below limit usage yet (1384 holders). Putting PR on hold for now. Please come back to us when all criteria are met.  Multi-chain and staking tokens may get special treatment, let us know if this is the case. 

https://etherscan.io/token/0xff034D12353867fC4228f4Ae3E689CD6dCAad120

**Comment by vikmeup** [comment]
As per our updated policy, brand new tokens are not included, there is a minimum requirement 

- at least 2500 token holders
- at least 500 transactions

See our [How to Get Submit Token Logo ](https://community.trustwallet.com/t/how-to-submit-a-token-logo/3863#how-to-get-approved) guidelines.

Feel free to re-open pull request once you meet those requirements.

**Pull request closed without merging**
