### PR TITLE
added logo for dogeCola

### PR DESCRIPTION
**Pull request by dogecola**

### CODE REVIEW

**Comment by Cryptocool1** [comment]
hello,
• What is the purpose of this token? How will it benefit Trust Wallet users?
 • How is the token being distributed? Are you conducting an airdrop?
 • Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?
 • Is the token listed on a centralized/decentralized exchange?
 • Is a Smart Contract audit completed? Where can we find this information?

**Comment by dogecola** [comment]
1) It is mainly a community token.
The first reflection token and soft drink at the same time. Every buy gives members more with the auto-boost and hyper deflation system in place.
We also do charity and we will do a lot of branding, creating a soft drink in the real world too.

2) We have airdropped few tokens, 99.99% of distribution was via Presale and PancakeSwap

3) This is the presale: https://dxsale.app/app/v2_9/defipresale?saleID=1579&chain=BSC

4) First Centralized exchange just today: https://twitter.com/ZT_exchange/status/1420685089533403145?s=20
https://support.clfxpx.com/hc/en-001/articles/4404307081625
DEX: https://exchange.pancakeswap.finance/#/swap?outputCurrency=0xe320Df552e78D57E95cF1182B6960746d5016561

5) KYC and AUDIT:
https://solidproof.io/audits?search=dogecola
https://github.com/solidproof/smart-contract-audits/blob/main/SmartContract_Audit_Solidproof_DogeCola.pdf

**Comment by dogecola** [comment]
> hello,
> • What is the purpose of this token? How will it benefit Trust Wallet users?
> • How is the token being distributed? Are you conducting an airdrop?
> • Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?
> • Is the token listed on a centralized/decentralized exchange?
> • Is a Smart Contract audit completed? Where can we find this information?



    It is mainly a community token.
    The first reflection token and soft drink at the same time. Every buy gives members more with the auto-boost and hyper deflation system in place.
    We also do charity and we will do a lot of branding, creating a soft drink in the real world too.

    We have airdropped few tokens, 99.99% of distribution was via Presale and PancakeSwap

    This is the presale: https://dxsale.app/app/v2_9/defipresale?saleID=1579&chain=BSC

    First Centralized exchange just today: https://twitter.com/ZT_exchange/status/1420685089533403145?s=20
    https://support.clfxpx.com/hc/en-001/articles/4404307081625
    DEX: https://exchange.pancakeswap.finance/#/swap?outputCurrency=0xe320Df552e78D57E95cF1182B6960746d5016561

    KYC and AUDIT:
    https://solidproof.io/audits?search=dogecola
    https://github.com/solidproof/smart-contract-audits/blob/main/SmartContract_Audit_Solidproof_DogeCola.pdf

**Comment by Cryptocool1** [comment]
can you please add links to your PR?
example: https://developer.trustwallet.com/add_new_asset#info-json-contents

**Comment by dogecola** [comment]
> can you please add links to your PR?
> example: https://developer.trustwallet.com/add_new_asset#info-json-contents

Thanks for cheking :) Links added

**Pull request merged**
