### PR TITLE
Add Green (ERC20)

### PR DESCRIPTION
**Pull request by Flarzival**
Adding info for ERC20 token 'Green'.

PR created by <a href="https://assets.trustwallet.com">TW Assets Management</a>

### CODE REVIEW

**Comment by cryptomanz** [comment]
Hello,
Can your answer some questions?
• What is the purpose of this token? How will it benefit Trust Wallet users?
• How is the token being distributed? Are you conducting an airdrop?
• Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?
• Is the token listed on a centralized/decentralized exchange?
• Is a Smart Contract audit completed? Where can we find this information?

**Comment by Flarzival** [comment]
Hello,
Purpose of Green is to reward for participating in proprietary node network. More energy efficient activities can reward node operators for making eco-friendly choices. It provides opportunity to Trust Wallet users to leverage their good power choices.

Token is distributed off-chain every day. Green users able to transfer on-chain by providing gas for transaction. No airdrops. No ICO.

It is listed on Uniswap. https://info.uniswap.org/#/tokens/0xb2089a7069861c8d90c8da3aacab8e9188c0c531 

Had private audit in 2019, but through private entity. Is this a requirement?

See timeline here:
https://share.green/green-timeline/

Thank you

**Comment by Cryptocool1** [comment]
hello, yes audit is one of our requirements

**Comment by Cryptocool1** [comment]
awaiting for smart contract audit, on hold for now

**Comment by Flarzival** [comment]
We are applying to coingecko and coinmarketcap now. Have been awaiting response for a few days. 
We have been working with audit company, and have audit complete. I'm seeing that the requirements have changed, can we continue this pull request so we can get in. We have applied and paid fee twice in 2021. 

We have completed the audit. To see full report, please see in our github repo:
https://github.com/green-blockchain/green-contract/blob/main/REP-Green-2021-11-19.pdf

Please re-open this request and allow us to add our information. Thank you.

**Pull request closed without merging**
