### PR TITLE
Update DEPAY information

### PR DESCRIPTION
**Pull request by 10xSebastian**
This is updating outdated information about DEPAY. Also makes sure you have the latest logo for the token.

### CODE REVIEW

**Comment by catenocrypt** [comment]
As mentioned above, token circulation is below our limit:

❌ Low token circulation: no. of holders is 1336, below limit of 2500

**Comment by spape** [comment]
So you rather show outdated information? Questionable.

**Comment by spape** [comment]
And your limit is stated for "adding" tokens explicitly in all your documentation. So you don't have any rule for it, hence, can't also reference it. Also your bot automation has been built for adding tokens.

**Comment by spape** [comment]
It's even contradicting: "New tokens without significant usage are rejected" 

We are not a new token in trust wallet

cc @vikmeup
@zachzwei, @catenocrypt, @Iamdeadlyz

**Comment by catenocrypt** [comment]
Sorry, I've overlooked that this is an update, not an addition.

**Comment by spape** [comment]
No problem. Thx mate.

**Pull request merged**
