### PR TITLE
Add Wrapped JAXNET 2 (BEP20)

### PR DESCRIPTION
**Pull request by FlingAvalon**
Adding info for BEP20 token 'Wrapped JAXNET 2'.

PR created by <a href="https://assets.trustwallet.com">TW Assets Management</a>

### CODE REVIEW

**Comment by FlingAvalon** [comment]
**• What is the purpose of this token? How will it benefit Trust Wallet users?**
The Jax.Network blockchain houses two native digital currencies, JAX and JXN. As DeFi is run on Layer 2, there is a need to convert JAX and JXN into Wrapped JAX (WJAX) and Wrapped JXN (WJXN).
WJXN is non-divisible, meaning 1 WJXN can’t be split into smaller parts like 0.5 WJXN, etc. WJXN-2 (Wrapped JXN) is a Layer-2 version of JXN, a native utility coin of the Jax.Network blockchain. Unlike WJXN, WJXN-2 can be divisible into smaller units and is mintable. Users can swap their WJXN for WJXN-2 and vice versa using the bridge too. Additionally, all daily yield payout on Jax.Money is denominated in WJXN-2.

**• How is the token being distributed? Are you conducting an airdrop?**
We are not conducting any airdrop.

**• Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?**
No, we did not conduct presales or ICO

**• Is the token listed on a centralized/decentralized exchange?** 
For the moment it’s listed only on DEXs

**• Is a Smart Contract audit completed? Where can we find this information?**
Yes our Audit is completed. Here is the link. Audit https://www.certik.com/projects/jax-network

**Comment by Cryptocool1** [comment]
are you listed on CoinMarketCap?

**Comment by FlingAvalon** [comment]
no not yet. our other version is listed. but this exact one is not listed.

**Comment by cryptomanz1** [comment]
Awaiting for CoinMarketCap listing, on hold for now.

**Comment by FlingAvalon** [comment]
Merge without CMC.

**Comment by Cryptocool1** [comment]
See our requirements here https://developer.trustwallet.com/assets/requirements

**Review by kophyo1234 — APPROVED** [review]

**Comment by FlingAvalon** [comment]
This was not previously in the requirements.

**Comment by Cryptocool1** [comment]
It was in requirements all the time. Feel free to create new PR once all requirements are met.

**Pull request closed without merging**
