### PR TITLE
Add BabyFlokiZilla Logo (BEP20)

### PR DESCRIPTION
**Pull request by BillyBeat**
Please add logo to BabyFlokiZilla token

### CODE REVIEW

**Comment by BillyBeat** [comment]
Paid. Please see tx.

https://explorer.binance.org/tx/1267FE219A4AA5D9795A79273E6A193C647D421FBF8CDF9BF847D0BFD9666319?fbclid=IwAR1J_pPgqF4W8I95qpPcXesvcJFN1170VImaPV-DsmC2ftyeIbwjuAApHFg

**Comment by cryptomanz** [comment]
• What is the purpose of this token? How will it benefit Trust Wallet users?
 • How is the token being distributed? Are you conducting an airdrop?
 • Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?
 • Is the token listed on a centralized/decentralized exchange?
 • Is a Smart Contract audit completed? Where can we find this information?

**Comment by BillyBeat** [comment]
> Please add logo to BabyFlokiZilla token



> • What is the purpose of this token? How will it benefit Trust Wallet users? • How is the token being distributed? Are you conducting an airdrop? • Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale? • Is the token listed on a centralized/decentralized exchange? • Is a Smart Contract audit completed? Where can we find this information?

• What is the purpose of this token? How will it benefit Trust Wallet users? 
Hi Cryptomanz! BabyFlokiZilla is a community-driven, meme token. BabyFlokiZilla gives passive rewards to holders in BUSD. The purpose of this token to give holders financial freedom just by holding. Another purpose is charity donations, we've done 2 donations to Charity called HopeForPaws so far, and we're planning to do it every week to give help to those in need. We also have been releasing NFTs which you can find on our website which will grant value to holders in the long run.

• How is the token being distributed? Are you conducting an airdrop?
The token stealth launched on Pancakeswap on Oct 31st. There are no presale, private sale nor airdrops. Airdropping is not possible to our contract that we forked.

• Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?
No. It was a stealth launched token on Pancakeswap.

• Is the token listed on a centralized/decentralized exchange?
So far, we have been fully listed on CoinMarketCap and CoinGecko. We are still currently reaching out and submitting applications to multiple Crypto Exchanges. Please refer to the links below for CMC and CG:

https://coinmarketcap.com/currencies/babyflokizilla/
https://www.coingecko.com/en/coins/babyflokizilla

• Is a Smart Contract audit completed? Where can we find this information?
We have paid for a full contract audit from Techrate which will be released in 3-4 days. We however have partial audit that is embedded on our website (babyflokizilla.com). We'll be sure to submit the full contract audit as soon as Techrate released it to us.

Thank you!!

**Comment by ramsty** [comment]
Awaiting for smart contract audit. On hold for now.

**Comment by Cryptocool1** [comment]
Feel free to open new PR when smart contract audit will be ready.
When creating a new PR make sure to mention this PR, so that we can see that fee has been paid already here.

**Comment by BillyBeat** [comment]
> Feel free to open new PR when smart contract audit will be ready. When creating a new PR make sure to mention this PR, so that we can see that fee has been paid already here.

Okay noted! :) Thank you!!

**Comment by BillyBeat** [comment]
Hi. I submitted another PR request and payment request is pending, please look into it.

https://github.com/trustwallet/assets/pull/15674

We also have received a complete audit from Techrate, kindly check link below:

https://babyflokizilla.com/wp-content/uploads/2021/11/techrate-audit.pdf

**Pull request closed without merging**
