### PR TITLE
Add HyperChain (BEP20)

### PR DESCRIPTION
**Pull request by xcyberdragonx**
Adding info for BEP20 token 'HyperChain'.

PR created by <a href="https://assets.trustwallet.com">TW Assets Management</a>

### CODE REVIEW

**Comment by xcyberdragonx** [comment]
Originally made Add HyperChain (BEP20) #7500
Maybe making a mess please assist i want to get this done asap

**Comment by Cryptocool1** [comment]
#7500 PAID

**Comment by xcyberdragonx** [comment]
How to proceed?

**Comment by xcyberdragonx** [comment]
MAde a new one: Add HyperChain (BEP20) #7522

**Comment by Cryptocool1** [comment]
Duplicate of #7522

**Pull request closed without merging**
