### PR TITLE
Add files via upload

### PR DESCRIPTION
**Pull request by vevodev**

### CODE REVIEW

**Comment by vevodev** [comment]
https://explorer.binance.org/tx/08ABA1A9727E74BAB37CAA7362B317EB1F3ABA4D3462CBBBFE7ED5D2CF65D255

**Comment by zachzwei** [comment]
Please provide more details about this project.
https://community.trustwallet.com/t/how-to-submit-a-token-logo/3863#how-to-get-approved

You can follow this format when adding an info.json file:

 {
   "name":"Bitcoin",
   "website":"https://bitcoin.org",
   "source_code":"https://github.com/bitcoin",
   "white_paper":"https://bitcoin.org/bitcoin.pdf",
   "short_description":"Bitcoin is a cryptocurrency and worldwide payment system.",
   "explorer":"https://blockchain.info",
   "research":"https://research.binance.com/en/projects/bitcoin"
}

**Review by vevodev — COMMENTED** [review]
{
   "name":"Vevocoin",
   "website":"https://vevocoin.com/",
   "telegram":"https://t.me/vevonews",
   "twitter":"https://twitter.com/vevocoin",
   "source_code":"https://github.com/vevodev",
   "white_paper":"https://vevocoin.com/whitepaper.pdf",
   "short_description":"VEVO is an open source platform in which everyone can use the code and token to their needs.",
   "explorer":"https://tronscan.org",
   
}

**Comment by catenocrypt** [comment]
As per our policy, brand new tokens are not included, there is a minimum requirement of 100 holder addresses and 500 transactions, in order to filter out scam tokens.
See the criteria at (mentioned in the first message by the bot): https://community.trustwallet.com/t/how-to-submit-a-token-logo/3863#how-to-get-approved
This token has minimal usage (10/15).  Putting PR on hold, please come back to us when all criteria are fulfilled.

https://tronscan.io/#/token/1003257

**Comment by vevodev** [comment]
Hello, now we have 215 holders and 256 txns

**Comment by vevodev** [comment]
Hello 

https://tronscan.org/#/token/1003257

**Comment by vevodev** [comment]
Hey guys.. how long do we need to wait..?

**Pull request merged**
