### PR TITLE
Secret Network logo

### PR DESCRIPTION
**Pull request by toml01**
This PR is being closed due to inactivity. If you wish to continue, please have us reopen the PR before sending your payment.
Do NOT send payments for closed PR, as the fee may by lost!
  (60 vs. 60 hrs)

### CODE REVIEW

**Comment by catenocrypt** [comment]
As per our policy, brand new tokens are not included, there is a minimum requirement of 2500 holder addresses and 5000 transactions, in order to filter out scam tokens.
See the criteria at (mentioned in the first message by the bot): https://community.trustwallet.com/t/how-to-submit-a-token-logo/3863).
This token has no real usage yet (5). Closing PR for now. Please come back to us when all criteria are met.  Multi-chain and staking tokens may get special treatment, let us know if this is the case.

**Comment by toml01** [comment]
@catenocrypt thanks for reviewing this PR.
This is definitely the case of a multichain token - the original token is [SCRT](https://coinmarketcap.com/currencies/secret/) (a cosmos chain). It should meet your criteria, we also spoke to Ashleigh at Uniswap.
This PR is referring to the wrapped ERC-20 version of it - WSCRT.

We'd be happy if you review it again 🙂
Thanks!

**Comment by catenocrypt** [comment]
Please add an `info.json` file next to the `logo.png`, with info about the project, of the form:

```json
{
    "name": "Trust Wallet Token",
    "type": "ERC20",
    "symbol": "TWT",
    "decimals": 8,
    "description": "Utility token to increase adoption of cryptocurrency.",
    "website": "https://trustwallet.com",
    "explorer": "https://explorer.binance.org/asset/TWT-8C2",
    "source_code": "https://github.com/trustwallet/",
    "white_paper": "",
    "socials": [
        {
            "name": "Twitter",
            "url": "https://twitter.com/trustwalletapp",
            "handle": "TrustWalletApp"
        },
        {
            "name": "Reddit",
            "url": "https://reddit.com/r/trustapp",
            "handle": "TrustApp"
        }
    ],
    "research": "https://research.binance.com/en/projects/trustwallet",
    "id": "TWT-8C2"
}
```

**Comment by toml01** [comment]
Done

**Comment by catenocrypt** [comment]
Submission looks OK, info.json ok.  Fee payment pending.

**Pull request closed without merging**
