### PR TITLE
Added Propel info.json

### PR DESCRIPTION
**Pull request by abstractbreazy**

### CODE REVIEW

**Comment by Iamdeadlyz** [comment]
As per our policy, brand new tokens are not included. There is a minimum requirement of 500 holder addresses and 1000 transactions in order to filter out scam tokens. See the criteria at (mentioned in the first message by the bot): https://community.trustwallet.com/t/how-to-submit-a-token-logo/3863#how-to-get-approved

This token has below-limit usage yet. This pull request will be but on hold. Please come back to us when all criteria are met.
https://bscscan.com/token/0x9b44df3318972be845d83f961735609137c4c23c

**Comment by AbstractBreazy** [comment]
it is possible to whitelist this address? https://explorer.binance.org/asset/PROPEL-6D9
BC have 3000 address and more then 22000 transactions. 
if yes, do i need to update my PR?

**Comment by catenocrypt** [comment]
The path in this PR is wrong, should be `smartchain` not `bsc` (bsc is legacy).

What you mentioned is a binance chain BEP2 token, not a smart chain BEP20 token.  Please create a brand new PR with it, and if it is for a token with the same owner as in this PR, we can consider this paid fee for the new PR.  Please mention the number #4182 in the new PR.

**Comment by catenocrypt** [comment]
Please create new PR, or fix this one.  It is inconsistent, if you wish to add BEP2 Binance chain token, path should be `blockchains/binance/assets/<tokenID>` .

**Comment by AbstractBreazy** [comment]
> The path in this PR is wrong, should be `smartchain` not `bsc` (bsc is legacy).
> 
> What you mentioned is a binance chain BEP2 token, not a smart chain BEP20 token. Please create a brand new PR with it, and if it is for a token with the same owner as in this PR, we can consider this paid fee for the new PR. Please mention the number #4182 in the new PR.

this pr has been updated, if necessary I can create a new one.

**Pull request merged**
