### PR TITLE
Update UMB (BEP20)

### PR DESCRIPTION
**Pull request by DZariusz**

### CODE REVIEW

**Comment by DZariusz** [comment]
@catenocrypt there is check failing about holders, but we need this update because old token is no longer valid. Please confirm that this is ok and I can do a payment. btw is the payment required even if this is only update?

**Comment by Cryptocool1** [comment]
do you have an official announcement about this update?

**Comment by DZariusz** [comment]
- scanner message: https://bscscan.com/token/0x6fC13EACE26590B80cCCAB1ba5d51890577D83B2 
- post https://medium.com/umbrella-network/announcement-of-new-token-issuance-on-bsc-and-related-updates-e8fca2c522cf

**Comment by DZariusz** [comment]
@Cryptocool1 I provided announcements links.

Please let me know it this update required payment?

**Comment by Cryptocool1** [comment]
> @Cryptocool1 I provided announcements links.
> 
> Please let me know it this update required payment?

yes, you need to pay the fee

**Pull request merged**
