### PR TITLE
Added Logo for CRYPTOBUCKS

### PR DESCRIPTION
**Pull request by cbucks**
Added Logo for CRYPTOBUCKS

### CODE REVIEW

**Comment by cbucks** [comment]
@kolya182 Please approve.

**Comment by cbucks** [comment]
@ceocharles Please approve.

**Comment by cbucks** [comment]
@kolya182 Sorry for the spam its emergency. Please approve.

**Comment by cbucks** [comment]
@kolya182 Sorry man I keep on spamming its emergency. Please approve.

**Comment by cbucks** [comment]
@kolya182 Sorry man I keep on spamming its emergency. Please approve.

**Comment by ceocharles** [comment]
that's ok

**Comment by cbucks** [comment]
Hi sorry but can you please help me.
I have updated the logo of our old token in this pull request to make people not confused.
But the logo still haven't changed in the trust wallet app both IOS and Android.
The logo should be this.
https://github.com/trustwallet/assets/blob/master/blockchains/ethereum/assets/0x5f9505D8Ad3D92E7507b9966f84772993A26356b/logo.png
Please help me. @ceocharles  @kolya182

**Comment by cbucks** [comment]
Its already been fixed now. Thank you so much. @ceocharles @kolya182

**Comment by ceocharles** [comment]
Wellcome

**Pull request merged**
