### PR TITLE
add GFloki token info

### PR DESCRIPTION
**Pull request by bailiyixi**
GFloki: http://www.genshinfloki.com/

### CODE REVIEW

**Comment by Cryptocool1** [comment]
• What is the purpose of this token? How will it benefit Trust Wallet users?
 • How is the token being distributed? Are you conducting an airdrop?
 • Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?
 • Is the token listed on a centralized/decentralized exchange?
 • Is a Smart Contract audit completed? Where can we find this information?

**Comment by bailiyixi** [comment]
> • What is the purpose of this token? How will it benefit Trust Wallet users? • How is the token being distributed? Are you conducting an airdrop? • Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale? • Is the token listed on a centralized/decentralized exchange? • Is a Smart Contract audit completed? Where can we find this information?

• DeFi+NFT+gameFi, After purchasing it, users can get income through the increase in currency price, and at the same time hold gfloki to get DOGE rewards.
• Pre-sales were made using pinksale, 55.7% were fair pre-sales, and 38.9% were added to pancakeswap. The airdrop has not been conducted yet.
• No, the reserved 5% of tokens will be used for marketing and cooperation, and airdrop activities, and will not be used for sale.
• Yes, it is already listed on ZT, as well as pancakeswap.
• You can check the audit report here: https://www.genshinfloki.com/Audit/GenshinFlokiInu.pdf

**Comment by ramsty** [comment]
> > • What is the purpose of this token? How will it benefit Trust Wallet users? • How is the token being distributed? Are you conducting an airdrop? • Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale? • Is the token listed on a centralized/decentralized exchange? • Is a Smart Contract audit completed? Where can we find this information?
> 
> • DeFi+NFT+gameFi, After purchasing it, users can get income through the increase in currency price, and at the same time hold gfloki to get DOGE rewards. • Pre-sales were made using pinksale, 55.7% were fair pre-sales, and 38.9% were added to pancakeswap. The airdrop has not been conducted yet. • No, the reserved 5% of tokens will be used for marketing and cooperation, and airdrop activities, and will not be used for sale. • Yes, it is already listed on ZT, as well as pancakeswap. • You can check the audit report here: https://www.genshinfloki.com/Audit/GenshinFlokiInu.pdf

The link to audit doesn't work, please send it here.

**Comment by bailiyixi** [comment]
> 

https://www.genshinfloki.com/Audit/GenshinFlokiInu.pdf

**Comment by bailiyixi** [comment]
> > > • What is the purpose of this token? How will it benefit Trust Wallet users? • How is the token being distributed? Are you conducting an airdrop? • Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale? • Is the token listed on a centralized/decentralized exchange? • Is a Smart Contract audit completed? Where can we find this information?
> > 
> > 
> > • DeFi+NFT+gameFi, After purchasing it, users can get income through the increase in currency price, and at the same time hold gfloki to get DOGE rewards. • Pre-sales were made using pinksale, 55.7% were fair pre-sales, and 38.9% were added to pancakeswap. The airdrop has not been conducted yet. • No, the reserved 5% of tokens will be used for marketing and cooperation, and airdrop activities, and will not be used for sale. • Yes, it is already listed on ZT, as well as pancakeswap. • You can check the audit report here: https://www.genshinfloki.com/Audit/GenshinFlokiInu.pdf
> 
> The link to audit doesn't work, please send it here.

https://www.genshinfloki.com/Audit/GenshinFlokiInu.pdf

**Comment by bailiyixi** [comment]
> > > • What is the purpose of this token? How will it benefit Trust Wallet users? • How is the token being distributed? Are you conducting an airdrop? • Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale? • Is the token listed on a centralized/decentralized exchange? • Is a Smart Contract audit completed? Where can we find this information?
> > 
> > 
> > • DeFi+NFT+gameFi, After purchasing it, users can get income through the increase in currency price, and at the same time hold gfloki to get DOGE rewards. • Pre-sales were made using pinksale, 55.7% were fair pre-sales, and 38.9% were added to pancakeswap. The airdrop has not been conducted yet. • No, the reserved 5% of tokens will be used for marketing and cooperation, and airdrop activities, and will not be used for sale. • Yes, it is already listed on ZT, as well as pancakeswap. • You can check the audit report here: https://www.genshinfloki.com/Audit/GenshinFlokiInu.pdf
> 
> The link to audit doesn't work, please send it here.

https://techrate.org/#product-list
https://github.com/TechRate/Smart-Contract-Audits/blob/main/November/GenshinFlokiInu.pdf

**Pull request merged**
