### PR TITLE
Baby Floki Inu PR

### PR DESCRIPTION
**Pull request by BabyFloki**

### CODE REVIEW

**Comment by BabyFloki** [comment]
I need to edit the name to: 0x02a9D7162BD73c2b35c5Cf6cDD585e91928c850A and change the JSON, can I do this before commiting?

**Comment by BabyFloki** [comment]
0x02a9D7162BD73c2b35c5Cf6cDD585e91928c850a

Folder is missing an A on the end

**Comment by BabyFloki** [comment]
Is adding the A on the end of the folder something you guys can do from your end? I don't see a way I can edit it

**Comment by Cryptocool1** [comment]
hello,
if you can't rename the files you can create new PR.
follow doc https://community.trustwallet.com/t/how-to-submit-a-token-logo/3863
You may want to try our Assets app in beta; go to https://assets.trustwallet.com, log on with Github, enter contract ID, logo and some additional info, and it will create a PR for you.
See https://community.trustwallet.com/t/how-to-submit-a-token-logo-using-assets-app/82957.
You don't need to pay one more time, make sure to mention this PR

**Comment by BabyFloki** [comment]
I managed to add the a on the end so it should work :D

**Comment by Cryptocool1** [comment]
blockchains/smartchain/assets/0x02a9D7162BD73c2b35c5Cf6cDD585e91928c850/logo.png
this file is wrong

**Comment by BabyFloki** [comment]
I've checked the details above for pull request CI, Is the failure something on my part that needs fixing?

**Comment by cryptomanz** [comment]
- Contract is not in checksum format, should be 0x02a9D7162BD73c2b35c5Cf6cDD585e91928c850A (not 0x02a9D7162BD73c2b35c5Cf6cDD585e91928c850a).
Please change.

**Pull request merged**
