### PR TITLE
Added RAINBOW icon and info to trust wallet

### PR DESCRIPTION
**Pull request by ZandroFargnoli**

### CODE REVIEW

**Comment by cryptomanz** [comment]
Hello,
According to our documentation token image needs to be full screen, here is link to guidelines details and an example of token images https://community.trustwallet.com/t/how-to-submit-a-token-logo/3863

**Comment by ZandroFargnoli** [comment]
@cryptomanz Thank you for responding quickly. I've changed the dimensions to 256px

**Comment by ZandroFargnoli** [comment]
@cryptomanz @catenocrypt @zachzwei @Cryptocool1 Hi guys, just checking everything is okay here - is this ready to be merged?

**Comment by Cryptocool1** [comment]
According to our documentation token image needs to be full screen

**Comment by Cryptocool1** [comment]
here is the example of full screen logo
logo-55

**Comment by ZandroFargnoli** [comment]
@cryptomanz @catenocrypt @zachzwei @Cryptocool1 Hi guys, I have made the icon fullscreen (by this I assume you mean moving the edges of the content right next to the edges of the image. The bot seems to have cached the old image, but if you check the repository you can see I have done just this:
 https://github.com/trustwallet/assets/blob/08aa765d745bd51868f69d08bddb6707e69354f0/blockchains/smartchain/assets/0x673Da443da2f6aE7c5c660A9F0D3DD24d1643D36/logo.png

**Comment by Cryptocool1** [comment]
Can you answer some questions?
• What is the purpose of this token? How will it benefit Trust Wallet users?
 • How is the token being distributed? Are you conducting an airdrop?
 • Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?
 • Is the token listed on a centralized/decentralized exchange?
 • Is a Smart Contract audit completed? Where can we find this information?

**Comment by ZandroFargnoli** [comment]
@Cryptocool1 Thank you for your swift response!

Can you answer some questions?
• What is the purpose of this token? How will it benefit Trust Wallet users?
We are an ethical token that has already donated $12,500 to charity, we want to help broaden the ecosystem by providing platforms and services, as well as NFTs and other fun things.

• How is the token being distributed? Are you conducting an airdrop?
Via buys and sells through PancakeSwap and XT.com

• Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?
We sold a portion of our supply via a token presale https://dxsale.app/app/v2_9/defipresale?saleID=2584&chain=BSC 

• Is the token listed on a centralized/decentralized exchange?
https://poocoin.app/tokens/0x673da443da2f6ae7c5c660a9f0d3dd24d1643d36 and https://www.xt.com/tradePro/rainbow_usdt

• Is a Smart Contract audit completed? Where can we find this information?
https://github.com/solidproof/smart-contract-audits/blob/main/SmartContract_Audit_Solidproof_RainbowToken.pdf
you can also confirm this via the website https://rainbowtoken.finance

**Comment by ZandroFargnoli** [comment]
Hey @Cryptocool1 the token icon looks funny in Trust Wallet, hence why we wanted it zoomed in slightly - how do we get around this as you required us to have it full screen?

**Pull request merged**
