### PR TITLE
Add HONEYPAD (BEP20)

### PR DESCRIPTION
**Pull request by erience**
Adding info for BEP20 token 'HONEYPAD'.

### CODE REVIEW

**Comment by cryptomanz** [comment]
Hello,
Can your answer some questions?
• What is the purpose of this token? How will it benefit Trust Wallet users?
 • How is the token being distributed? Are you conducting an airdrop?
 • Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?
 • Is the token listed on a centralized/decentralized exchange?
 • Is a Smart Contract audit completed? Where can we find this information?

**Comment by Beegythebee** [comment]
> Hello,
> Can your answer some questions?
> • What is the purpose of this token? How will it benefit Trust Wallet users?
> • How is the token being distributed? Are you conducting an airdrop?
> • Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?
> • Is the token listed on a centralized/decentralized exchange?
> • Is a Smart Contract audit completed? Where can we find this information?

• What is the purpose of this token? How will it benefit Trust Wallet users?

Honeypad is a hyper-deflationary use-case token, which has cutting-edge features in it’s code. Also it’s the umbrella brand for different usecases which ones we’ll build one after one. Every single one delivers the solution for actual problems in the crypto world.

Honeypad rewards token holders with auto-BNB payments gained through transaction taxes while also preventing huge selloffs with its first of a kind HONEYLOCK feature. HONEYLOCK makes sure that no wallet can sell more than 50% of its holdings during a 24-hour period, automatically restricting any sales past that point, ensuring a stabilized price and chart. This is a ﬁrst for all cryptocurrencies, but the economic theory checks out.
Additionally, our QUEEN BEE will buy back tokens during important psychological levels on the chart and let them equally ﬂow back into the liquidity pool and burn wallet. HONEYSHIELD will be activated every single time a buy back is happening to prevent pump and dumps.
Honeypad aims to make the cryptocurrency market – especially the decentralized finance and freelance market – more safe for its users. Our use-case is no small deal either. 

HONEYWORK will be the first-ever crypto-based freelancer platform. Kinda similar to fiverr , but it will be much more trusted, as we deliver better transparency, lower transaction fees and most important: Honeywork will run on our own blockchain, which offers advantages you for sure are aware of. Honeywork is indeed tailored to freelancing. 

HONEYPAY is the payment provider on Honeypad, processing transactions securely.

HONEYSWAP will be Honeypad’s own decentralized exchange.
Trade, stake and swap! Enabling our holders to trade on an intuitive interface. 

The HIVE CHAIN is the blockchain that it all happens on, keeping the ecosystem closed and decentralized.

Detailed description in the Whitepaper.
Link: https://www.honeypad.io/honeypaper/

• How is the token being distributed? Are you conducting an airdrop?
Private sale participants got their tokens airdropped after launch and presale participants needed to claim their tokens on the platform dxsale

• Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?
Yes IDO, organized and processed over dxsale.app 
Link: https://dxsale.app/app/v2_9/defipresale?saleID=2854&chain=BSC

• Is the token listed on a centralized/decentralized exchange?
Yes, Pancakeswap
Link: https://pancakeswap.finance/swap#/swap?inputCurrency=0xdb607c61Aaa2a954Bf1f9d117953F12d6c319E15

• Is a Smart Contract audit completed? Where can we find this information?
Yes, 2 completed and 1 currently in review.

Dessertswap doxxed audit: https://dessertswap.finance/audits/Honeypad%20BEP-20%20Audit%209967117.pdf

Techrate full smart contract audit: https://github.com/TechRate/Smart-Contract-Audits/blob/main/August/HONEYPAD%20Full%20Smart%20Contract%20Security%20Audit.pdf

Certik ongoing: https://www.certik.org/projects/honeypad

**Comment by erience** [comment]
• What is the purpose of this token? How will it benefit Trust Wallet users?

Honeypad is a hyper-deflationary use-case token, which has cutting-edge features in it’s code. Also it’s the umbrella brand for different usecases which ones we’ll build one after one. Every single one delivers the solution for actual problems in the crypto world.

Honeypad rewards token holders with auto-BNB payments gained through transaction taxes while also preventing huge selloffs with its first of a kind HONEYLOCK feature. HONEYLOCK makes sure that no wallet can sell more than 50% of its holdings during a 24-hour period, automatically restricting any sales past that point, ensuring a stabilized price and chart. This is a ﬁrst for all cryptocurrencies, but the economic theory checks out.
Additionally, our QUEEN BEE will buy back tokens during important psychological levels on the chart and let them equally ﬂow back into the liquidity pool and burn wallet. HONEYSHIELD will be activated every single time a buy back is happening to prevent pump and dumps.
Honeypad aims to make the cryptocurrency market – especially the decentralized finance and freelance market – more safe for its users. Our use-case is no small deal either. 

HONEYWORK will be the first-ever crypto-based freelancer platform. Kinda similar to fiverr , but it will be much more trusted, as we deliver better transparency, lower transaction fees and most important: Honeywork will run on our own blockchain, which offers advantages you for sure are aware of. Honeywork is indeed tailored to freelancing. 

HONEYPAY is the payment provider on Honeypad, processing transactions securely.

HONEYSWAP will be Honeypad’s own decentralized exchange.
Trade, stake and swap! Enabling our holders to trade on an intuitive interface. 

The HIVE CHAIN is the blockchain that it all happens on, keeping the ecosystem closed and decentralized.

Detailed description in the Whitepaper.
Link: https://www.honeypad.io/honeypaper/

• How is the token being distributed? Are you conducting an airdrop?
Private sale participants got their tokens airdropped after launch and presale participants needed to claim their tokens on the platform dxsale

• Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?
Yes IDO, organized and processed over dxsale.app 
Link: https://dxsale.app/app/v2_9/defipresale?saleID=2854&chain=BSC

• Is the token listed on a centralized/decentralized exchange?
Yes, Pancakeswap
Link: https://pancakeswap.finance/swap#/swap?inputCurrency=0xdb607c61Aaa2a954Bf1f9d117953F12d6c319E15

• Is a Smart Contract audit completed? Where can we find this information?
Yes, 2 completed and 1 currently in review.

Dessertswap doxxed audit: https://dessertswap.finance/audits/Honeypad%20BEP-20%20Audit%209967117.pdf

Techrate full smart contract audit: https://github.com/TechRate/Smart-Contract-Audits/blob/main/August/HONEYPAD%20Full%20Smart%20Contract%20Security%20Audit.pdf

Certik ongoing: https://www.certik.org/projects/honeypad

**Comment by erience** [comment]
@cryptomanz : please check above reply

**Pull request merged**
