### PR TITLE
Add NVIR token

### PR DESCRIPTION
**Pull request by nvirworld**
Add NVIR token to Trust Wallet assets

### CODE REVIEW

**Comment by Cryptocool1** [comment]
Снимок экрана 2022-06-16 в 12 37 34

**Comment by nvirworld** [comment]
How long would the evaluation take?

**Comment by cryptomanz** [comment]
• What is the purpose of this token? How will it benefit Trust Wallet users?
 • How is the token being distributed? Are you conducting an airdrop?
 • Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?
 • Is the token listed on a centralized/decentralized exchange?
 • Is a Smart Contract audit completed? Where can we find this information?

**Comment by nvirworld** [comment]
• NVIR token is the gvernance token for the serviced in NvirWorld ecosystem. We provide Trust Wallet connect on our NFT marketplace. More users of Trust Wallet will be able to find NVIR easily once it is added in the repository. 
• Token Sale: 20% (2,140,000,000 NVIR)
Reward Pool: 30% (3,210,000,000 NVIR)
Ecosystem Fund: 20% (2,140,000,000 NVIR)
Private Sale: 5% (535,000,000 NVIR)
Community: 5% (535,000,000 NVIR)
Team: 5% (535,000,000 NVIR)
Reserve: 15% (1,605,000,000 NVIR)
We are currently not conducting any token airdrop.
• There was a token presale (Private Sale).
• NVIR is listed on Uniswap, BKEX, and Poloniex. 
• Kindly see the attached file.

**Comment by nvirworld** [comment]
[SlowMist Audit Report - NVIRToken.pdf](https://github.com/trustwallet/assets/files/8925638/SlowMist.Audit.Report.-.NVIRToken.pdf)

**Pull request merged**
