### PR TITLE
Add SafeMoon Zilla (BEP20)

### PR DESCRIPTION
**Pull request by ghost**
Adding info for BEP20 token 'SafeMoon Zilla'.

PR created by <a href="https://assets.trustwallet.com">TW Assets Management</a>

### CODE REVIEW

**Comment by cryptomanz** [comment]
Please create new PR, follow doc https://community.trustwallet.com/t/how-to-submit-a-token-logo/3863
You may want to try our Assets app in beta; go to https://assets.trustwallet.com, log on with Github, enter contract ID, logo and some additional info, and it will create a PR for you.
See https://community.trustwallet.com/t/how-to-submit-a-token-logo-using-assets-app/82957.

**Comment by ElonGetqwik** [comment]
I have paid and didn't know what is the matter with you , please tell me
the problem

‫في الجمعة، 10 ديسمبر 2021 في 3:27 ص تمت كتابة ما يلي بواسطة ‪Nazar‬‏ <‪
***@***.***‬‏>:‬

**Comment by Cryptocool1** [comment]
did you pay in this PR?

**Comment by ElonGetqwik** [comment]
yes and this is the TX Hash
: 0C3F718F90CB0A48F9E1DE0EA16F541F63482561382EAB89C7B6EF0E08C65E6E

‫في الجمعة، 10 ديسمبر 2021 في 8:02 م تمت كتابة ما يلي بواسطة ‪CryptoA‬‏ <‪
***@***.***‬‏>:‬

**Comment by Cryptocool1** [comment]
#16502 paid

**Comment by Cryptocool1** [comment]
As per our policy, brand new tokens are not included, there is a minimum requirement of 25,000 holder addresses and 50,000 transactions, in order to filter out scam tokens.
See the criteria at : https://developer.trustwallet.com/assets/requirements .

**Comment by Cryptocool1** [comment]
Feel free to open new  pull request once you meet those requirements.
When creating a new PR make sure to mention this PR, so that we can see that fee has been paid already here.

**Pull request closed without merging**
