### PR TITLE
Add Sheikh Inu (BEP20)

### PR DESCRIPTION
**Pull request by Sheikhinu**
Adding info for BEP20 token 'Sheikh Inu'.

PR created by <a href="https://assets.trustwallet.com">TW Assets Management</a>

### CODE REVIEW

**Comment by Sheikhinu** [comment]
we created a new PR, but we already paid 500TWT at memo 24004

**Comment by cryptomanz1** [comment]
#24004

**Comment by cryptomanz1** [comment]
• What is the purpose of this token? How will it benefit Trust Wallet users?
 • How is the token being distributed? Are you conducting an airdrop?
 • Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?
 • Is the token listed on a centralized/decentralized exchange?
 • Is a Smart Contract audit completed? Where can we find this information?

**Comment by Sheikhinu** [comment]
• What is the purpose of this token? How will it benefit Trust Wallet users?
Push the decentralization experiment to it’s ultimate limits and prove again that a purely meme-token can be driven and sustained 100% by its community only if you have the trust and the capacity.
it'll benefit trust wallet users by showing them how legit we are and by providing more data to our big community and holders through a well-reputated wallet like TrustWallet

• How is the token being distributed? Are you conducting an airdrop?
the token currently is being selling on Pancakeswap and many other decentralized exchanges.
and there's no airdrop happening soon.

• Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?
yes, we did a presale before only for whitelisted wallets, and it was filled immediately.

• Is the token listed on a centralized/decentralized exchange?
decentralized.

• Is a Smart Contract audit completed? Where can we find this information?
yes we are audited by 2 big auditors.

1- https://contractwolf.io/projects/sheikh-inu
2- https://blocksafu.com/project-detail/0xE5b5d4Bea7468B4994FA676949308a79497aa24c.

**Comment by Cryptocool1** [comment]
How did you get more than 10k holders in less than 2 weeks?

**Comment by Sheikhinu** [comment]
We have made a lot of buying competition & buying without taxes + presale wallets +rewards+ we already have 19K twitter followers & 5k tg members

**Comment by Cryptocool1** [comment]
Have you conducted any airdrops? 
is your token listed on CMC?

**Comment by Sheikhinu** [comment]
No Airdrops campaigns yet 
we're listed on CMC & CoinGecko 

https://coinmarketcap.com/currencies/sheikh-inu/

https://www.coingecko.com/en/coins/sheikh-inu

**Pull request merged**
