### PR TITLE
add ZenFi AI logo and info

### PR DESCRIPTION
**Pull request by zenfiaigit**

### CODE REVIEW

**Comment by Cryptocool1** [comment]
• Is a Smart Contract audit completed? Where can we find this information?

**Review by Bayramp — COMMENTED** [review]
Trust vallet cüzdanına eklermsiniz

**Comment by Cryptocool1** [comment]
> Trust vallet cüzdanına eklermsiniz

• Is a Smart Contract audit completed? Where can we find this information?

**Comment by zenfiaigit** [comment]
> • Is a Smart Contract audit completed? Where can we find this information?
yes. 
https://solidity.finance/audits/ZenFiAI/

**Pull request merged**
