### PR TITLE
Add MTW Logo and Update Info

### PR DESCRIPTION
**Pull request by METAWHALEWORLD**
Add MTW Logo and Update Info

Fee Already Paid PR No #19007

All Changes are Done

MTW is BEP20 Token

Holder and Transaction are checked for References https://bscscan.com/token/0xD3Ac199E6e6A1668ED6566b6F6dcdf7641868731

### CODE REVIEW

**Comment by METAWHALEWORLD** [comment]
Holder and Transaction are checked for References https://bscscan.com/token/0xD3Ac199E6e6A1668ED6566b6F6dcdf7641868731

**Comment by ramsty** [comment]
The right folder is blockchains/smartchain/assets/

**Comment by METAWHALEWORLD** [comment]
Yes , I add File In Right Folder

**Comment by METAWHALEWORLD** [comment]
Holder and Transaction are checked for References https://bscscan.com/token/0xD3Ac199E6e6A1668ED6566b6F6dcdf7641868731

**Comment by ramsty** [comment]
Could you answer some questions?
• What is the purpose of this token? How will it benefit Trust Wallet users?
• How is the token being distributed? Are you conducting an airdrop?
• Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?
• Is the token listed on a centralized/decentralized exchange?
• Is a Smart Contract audit completed? Where can we find this information?

**Comment by METAWHALEWORLD** [comment]
• What is the purpose of this token? 
MetaWhale meets you with a new world called Metaverse. It’s a world full of imagination, creativity and a lot more. MetaWhale allows play games in a virtual world. Gamers start selling creative assets- skins, weapons with copyright ownership.

• How is the token being distributed? 
2.2 Billion Total Supply 
 5% Private Sell
5% Partnerships
10% ICO
15% IEO
15% Advisory Panel 
22% Development 
28% Management

Are you conducting an airdrop?
Yes did for 15000 users

• Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?
Currently in Private sale round

• Is the token listed on a centralized/decentralized exchange?
No

• Is a Smart Contract audit completed? Where can we find this information? 
No

**Comment by ramsty** [comment]
Awaiting for smart contract audit. On hold for now.

**Comment by cryptomanz** [comment]
Please come back to us when all criteria are met.
When creating a new PR make sure to mention this PR, so that we can see that fee has been paid already here.

**Comment by METAWHALEWORLD** [comment]
> Awaiting for smart contract audit. On hold for now.

How to Audit smart contract Please guide us and send details

**Pull request closed without merging**
