### PR TITLE
TFC logo update

### PR DESCRIPTION
**Pull request by theflashcurrency**
We hope to get approval to update the logo on trust wallet

### CODE REVIEW

**Comment by theflashcurrency** [comment]
hello maintainer! please help us update the logo because we have already paid. if there are errors please help us thanks!

**Comment by theflashcurrency** [comment]
hello maintainer as this is my first time using github and trustwallet if there is any mistake please support us through! thank you!

**Comment by ramsty** [comment]
can you please add links to your PR
example:https://developer.trustwallet.com/assets/repository_details

**Comment by theflashcurrency** [comment]
please tell me what more link i need? our social media sites and white papers?

**Comment by theflashcurrency** [comment]
since i am not fluent in programming code please help me

**Comment by theflashcurrency** [comment]
actually i was very confused when i saw the error file, i followed the instructions. now i don't know how. If it's wrong, someone please correct me. thank you very much!

**Comment by theflashcurrency** [comment]
Here are our social media links: Twiiter: https://twitter.com/FlashTfc
Telegram: https://t.me/flashcurrencytfc

**Comment by ramsty** [comment]
> Here are our social media links: Twiiter: https://twitter.com/FlashTfc Telegram: https://t.me/flashcurrencytfc

You have to add minimum 3 social media links

**Comment by theflashcurrency** [comment]
add Facebook: https://www.facebook.com/groups/1046965489139636/

**Comment by theflashcurrency** [comment]
How happy it is when the updated TFC LOGO will bring a happy Christmas season.  thank..!

**Comment by theflashcurrency** [comment]
Dear maintainer!  Please help fix file errors to help us make the merging process go well.  thank you!
Twiiter: https://twitter.com/FlashTfc
Telegram: https://t.me/flashcurrencytfc
facebook: https://www.facebook.com/groups/1046965489139636/
coinmarketcap: https://coinmarketcap.com/vi/currencies/flash-currency/
coingecko: https://www.coingecko.com/vi/ty_gia/theflashcurrency

**Comment by ramsty** [comment]
• What is the purpose of this token? How will it benefit Trust Wallet users?
• How is the token being distributed? Are you conducting an airdrop?
• Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?
• Is the token listed on a centralized/decentralized exchange?
• Is a Smart Contract audit completed? Where can we find this information?

**Comment by theflashcurrency** [comment]
The Flash Currency- TFC token is the token that builds the Tron network standard.  Profits pay for the internal ecosystem and the tron ​​ecosystem becomes a utility token.  We do not sell ICOs whose code can be found in the tron ​​Network explorer.  Currently TFC is present on coinmarketcap and coinecko has been listed with 3 official exchanges and 1 exchange of our partner Zedxion and 1 exchange.
Dex-Trade: https://dex-trade.com/spot/trading/TFCUSDT
bankcex: https://bankcex.com/m-exchange-advanced.html?symbol=TFC_USDT
vindax: https://vindax.com/m-exchange-advanced.html?symbol=TFC_USDT
Zedxion:https://m.zedxion.net/en_US/trade/TFC_USDT
Flash-TFC Global: https://flash-tfc.com/a/#/market/TFC-USDT

**Comment by theflashcurrency** [comment]
We don't currently have an airdrop of the project we seriously have the capitalization and liquidity of them here making the project useful.

**Comment by Cryptocool1** [comment]
Is a Smart Contract audit completed? Where can we find this information?

**Comment by theflashcurrency** [comment]
Trc10 is more than the co-angle of the Tron network, it doesn't need to be authenticated, just uses Id: 1004117
Check it: https://tronscan.org/#/token/1004117/transfers

**Comment by ramsty** [comment]
Is a Smart Contract audit completed?

**Comment by theflashcurrency** [comment]
Yes..!  Everything is done.  because TRC10 protocol does not need to authenticate and it is authenticated

**Comment by theflashcurrency** [comment]
We hope to be through we are working very hard to build TFC marketable to date.  Thank you maintenance person

**Comment by Cryptocool1** [comment]
Can you send smart contract audit here?

**Comment by theflashcurrency** [comment]
yes we got what the smart contract unaudited TFC token maintainer meant

**Comment by theflashcurrency** [comment]
Please give us a chance to pass our project as honest with full information and team

**Comment by theflashcurrency** [comment]
Very grateful!  The maintenance person was very enthusiastic to help us

**Comment by Cryptocool1** [comment]
We require full smart contract audit

**Comment by Cryptocool1** [comment]
• What is the purpose of this token? How will it benefit Trust Wallet users?
 • How is the token being distributed? Are you conducting an airdrop?
 • Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?
 • Is the token listed on a centralized/decentralized exchange?
 • Is a Smart Contract audit completed? Where can we find this information?

**Comment by theflashcurrency** [comment]
Hello Trc10 token maintainer it doesn't have a contract like Trc20.  token trc10 it just uses the contract ID.  If love authentic, I do not know how!

**Comment by theflashcurrency** [comment]
Hello maintainer.  Trc10 token it has no contract like Trc20.  token trc10 it just uses the contract ID.  If authentication is required, I don't know how!

**Comment by Cryptocool1** [comment]
As per our policy, brand new tokens are not included, there is a minimum requirement of 10,000 holder addresses and 20,000 transactions, in order to filter out scam tokens.
See the criteria at : https://developer.trustwallet.com/assets/requirements .

**Comment by Cryptocool1** [comment]
Please come back to us when all criteria are met.
When creating a new PR make sure to mention this PR, so that we can see that fee has been paid already here.

**Comment by theflashcurrency** [comment]
Yes!  We will try to meet Trust's criteria

**Pull request closed without merging**
