### PR TITLE
Update Logo For Existing Token - MagnetGold 

### PR DESCRIPTION
**Pull request by MAGNETGOLD**
MagnetGold is a new revolution in the crypto world. Kindly upload and show our MagnetGold Logo on Trust Wallet.

### CODE REVIEW

**Comment by MAGNETGOLD** [comment]
> @MAGNETGOLD, kind reminder: please pay fee: **1000 TWT** with the memo **14230** to the address `bnb1tqq9llyr3dyjd559dha6z5r5etk3qfwk07m098`. Alternatively, 5 BNB is also accepted (same memo & address).
> 
> **QR** code: [Trust](https://api.qrserver.com/v1/create-qr-code/?size=200x200&data=https%3A%2F%2Flink.trustwallet.com%2Fsend%3Fasset%3Dc714_tTWT-8C2%26address%3Dbnb1tqq9llyr3dyjd559dha6z5r5etk3qfwk07m098%26amount%3D1000%26memo%3D14230) | [other wallet](https://api.qrserver.com/v1/create-qr-code/?size=200x200&data=bnb1tqq9llyr3dyjd559dha6z5r5etk3qfwk07m098%3Famount%3D1000%26memo%3D14230) See the [Pull Request Fee FAQ](https://developer.trustwallet.com/add_new_asset/pr-fee).

===============================================================
We payed fee 1000 TWT from Pancake (Trust Wallet) 
Transaction Hash: 0xebc0dba76e8c8892a84f96dee9daea9b11c319d9a437c0a67eeee77fb818bdf
Transfer status page is attached

TrustWallet
1

**Comment by MAGNETGOLD** [comment]
> **PR Summary** Files OK, 2Files in PR: 2 Token in PR: BEP20 0x323273b8ee5ae6247b47c38c81db45e1bef13e6f Symbol: **MTG** decimals: 18 Links: [Logo](https://raw.githubusercontent.com/MAGNETGOLD/assets/master/blockchains/smartchain/assets/0x323273b8ee5ae6247b47c38c81db45e1bef13e6f/logo.png) [Info](https://raw.githubusercontent.com/MAGNETGOLD/assets/master/blockchains/smartchain/assets/0x323273b8ee5ae6247b47c38c81db45e1bef13e6f/info.json) [Website](https://www.mtggold.com/) [Explorer](https://bscscan.com/token/0x323273b8ee5ae6247b47c38c81db45e1bef13e6f) Token check error: ❌ Contract is not in checksum format, should be 0x323273b8EE5Ae6247b47C38C81dB45E1beF13E6F (not 0x323273b8ee5ae6247b47c38c81db45e1bef13e6f). Please rename it. You may need to rename to a temp name first, then to the checksum format, because lowercase-uppercase-only renames are often ignored by the Git client or the filesystem. ❌ Id field does not match contract, should be 0x323273b8ee5ae6247b47c38c81db45e1bef13e6f, not 0x323273b8EE5Ae6247b47C38C81dB45E1beF13E6F. Please rename. ❌ The links field cannot be empty ! No. of holders not checked, external info not available; null ✓ Token type OK (BEP20); Type field OK; Symbol field OK; Decimals field OK; Description field OK; Website field OK; Explorer field OK; Status field OK; Logo image type is OK (image/png); Logo image size is OK (12.201 kB); Logo dimensions OK (256x256);
> 
> 
==========================================
I commit changes in uploaded "info.json"  as per your guidelines.
Kindly check and inform us if any farther changes is required.

**Comment by MAGNETGOLD** [comment]
Hi Trustwallet/Assets,
We transfer 1000 TWT as your requirements for logo of MTG also send you
details on GitHub so, please confirm it as soon as possible.

**Comment by MAGNETGOLD** [comment]
Hello trustwallet,
we already pay a fee: *1000 TWT* with the memo *14230* to the address
bnb1tqq9llyr3dyjd559dha6z5r5etk3qfwk07m098.
and attached a screenshot to github.
again attach a screenshot in this mail.Please check your details and update
us.

**Comment by Cryptocool1** [comment]
Payment was not found by the bot; could you provide TXID or date for checking?

**Comment by MAGNETGOLD** [comment]
Ofcourse, I am attaching documents to this email

**Comment by MAGNETGOLD** [comment]
I send you one more record.

**Comment by MAGNETGOLD** [comment]
> We payed fee 1000 TWT from Pancake (Trust Wallet)
> Transaction Hash: 0xebc0dba76e8c8892a84f96dee9daea9b11c319d9a437c0a67eeee77fb818bdf

We payed fee 1000 TWT from Pancake (Trust Wallet)
Transaction Hash: 0xebc0dba76e8c8892a84f96dee9daea9b11c319d9a437c0a67eeee77fb818bdf
On 23rd of NOV 2021 Tuesday 7:25PM

**Comment by MAGNETGOLD** [comment]
> Payment was not found by the bot; could you provide TXID or date for checking?

We payed fee 1000 TWT from Pancake (Trust Wallet)
Transaction Hash: 0xebc0dba76e8c8892a84f96dee9daea9b11c319d9a437c0a67eeee77fb818bdf
On 23rd of NOV 2021 Tuesday 7:25PM Time zone in India (GMT+5:30)

**Comment by Cryptocool1** [comment]
correction needed:

Снимок экрана 2021-11-25 в 17 33 48

**Comment by MAGNETGOLD** [comment]
I changed it in  info.json
<https://github.com/trustwallet/assets/commit/b17014fe7e417afb3da943f8e45d183d36eb739c#diff-3c4f82b3d8d298054042cda346898a901ede485081006f68d6ea90a0d407b963>
file,
Kindly let me know where I have to do it.

Regards,

**Comment by MAGNETGOLD** [comment]
> correction needed:
> 
> Снимок экрана 2021-11-25 в 17 33 48


I changed it in  info.json file, Kindly let me know where I have to do it.

Regards,

**Comment by MAGNETGOLD** [comment]
[image: 0x323273b8EE5Ae6247b47C38C81dB45E1beF13E6F .png]

**Comment by MAGNETGOLD** [comment]
assets <https://github.com/MAGNETGOLD/assets>/blockchains
<https://github.com/MAGNETGOLD/assets/tree/master/blockchains>/smartchain
<https://github.com/MAGNETGOLD/assets/tree/master/blockchains/smartchain>/
assets
<https://github.com/MAGNETGOLD/assets/tree/master/blockchains/smartchain/assets>
//info.json

[image: 0x323273b8EE5Ae6247b47C38C81dB45E1beF13E6F.png]

**Comment by MAGNETGOLD** [comment]
Kindly Update MagnetGold Logo on Trust Wallet, Our Payment Status is Paid

**Comment by Cryptocool1** [comment]
your filet are incorrect, both info.json and logo.png.
Please create new PR, follow doc https://community.trustwallet.com/t/how-to-submit-a-token-logo/3863
You may want to try our Assets app in beta; go to https://assets.trustwallet.com, log on with Github, enter contract ID, logo and some additional info, and it will create a PR for you.
See https://community.trustwallet.com/t/how-to-submit-a-token-logo-using-assets-app/82957.

make sure to mention this PR , so that we can see that fee has been paid already here.

**Comment by MAGNETGOLD** [comment]
We create new PR from your Assets app in beta; go to
https://assets.trustwallet.com
New PR is "*Add MagnetGold (BEP20) #16118*"

1000 TWT is already paid by us with the memo 14230 to the address
bnb1tqq9llyr3dyjd559dha6z5r5etk3qfwk07m098
Our previous Pull Request was "Update Logo For Existing Token -
MagnetGold Update
Logo For Existing Token - MagnetGold  #14230
<https://github.com/trustwallet/assets/pull/14230>"
Transaction Hash:
0xebc0dba76e8c8892a84f96dee9daea9b11c319d9a437c0a67eeee77fb818bdf
On 23rd of NOV 2021 Tuesday 7:25PM


Kindly Consider it and Update MagnetGold Logo on Trust Wallet

Regards,

**Pull request closed without merging**
