### PR TITLE
Add Affinity (BEP20)

### PR DESCRIPTION
**Pull request by Azacora**
Adding info for BEP20 token 'Affinity'.

PR created by <a href="https://assets.trustwallet.com">TW Assets Management</a>

### CODE REVIEW

**Comment by Azacora** [comment]
Would it be possible to remove the old token? I would like to avoid confusion from the double listing

0xFACE67C5CE2bb48c29779b0Dede5360cC9ef5fd5
AFNTY

**Comment by Azacora** [comment]
Also. If I use the link X.com it fails the checks, but if I use twitter.com, it passes the checks but comes up with a token check error to use x.com

**Comment by Cryptocool1** [comment]
• What is the purpose of this token? How will it benefit Trust Wallet users?
 • How is the token being distributed? Are you conducting an airdrop?
 • Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?
 • Is the token listed on a centralized/decentralized exchange?
 • Is a Smart Contract audit completed? Where can we find this information?

**Comment by Cryptocool1** [comment]
Please come back to us once you are ready to provide details. Feel free to create new PR and mention this one so the fee can be reused

**Pull request closed without merging**
