### PR TITLE
Add MNDAO logo and info

### PR DESCRIPTION
**Pull request by moondao**
This request is for adding logo and info into trustwallet.

### CODE REVIEW

**Comment by catenocrypt** [comment]
Correction needed:  logo file should be named exactly 'logo.png'.  Please rename.

blockchains/smartchain/assets/0x069b2619eb24367a46fda638bd1b88aa4dad7879/mndao.png

**Comment by moondao** [comment]
> 0x069b2619eb24367a46fda638bd1b88aa4dad7879

i can not find this folder.. deleted? and what should i do?

**Comment by moondao** [comment]
> bnb1tqq9llyr3dyjd559dha6z5r5etk3qfwk07m098

sent

**Comment by moondao** [comment]
> Correction needed: logo file should be named exactly 'logo.png'. Please rename.
> 
> blockchains/smartchain/assets/0x069b2619eb24367a46fda638bd1b88aa4dad7879/mndao.png

updated

**Comment by TranDinhKhang** [comment]
@moondao fix the errors fella

**Comment by moondao** [comment]
> Correction needed: logo file should be named exactly 'logo.png'. Please rename.
> 
> blockchains/smartchain/assets/0x069b2619eb24367a46fda638bd1b88aa4dad7879/mndao.png

how the progress is going on?

**Comment by TranDinhKhang** [comment]
@catenocrypt @Butterflies22 @zachzwei please update on this

**Comment by moondao** [comment]
> Correction needed: logo file should be named exactly 'logo.png'. Please rename.
> 
> blockchains/smartchain/assets/0x069b2619eb24367a46fda638bd1b88aa4dad7879/mndao.png

all is done mate.. please check.. thank you...

**Pull request merged**
