### PR TITLE
Shinuri token addition to Trust Wallet Assets

### PR DESCRIPTION
**Pull request by Shinuri**
Uploading Shinuri token information and logo to Trust Wallet's Ethereum assets.

### CODE REVIEW

**Comment by Shinuri** [comment]
Automated check states that some links are invalid, however the only links provided are:
twitter
coingecko
telegram
reddit
github
source_code

**Comment by Cryptocool1** [comment]
As per our policy, brand new tokens are not included, there is a minimum requirement of 10,000 holder addresses and 15,000 transactions, in order to filter out scam tokens.
See the criteria at : https://developer.trustwallet.com/assets/requirements .

**Comment by Cryptocool1** [comment]
Your first transaction was 2 days ago. We are not accept brand new tokens. See all the requirements here https://developer.trustwallet.com/assets/requirements

**Comment by Cryptocool1** [comment]
Feel free to create new PR once all the requirements are met.

**Pull request closed without merging**
