### PR TITLE
add TWT Logo and info

### PR DESCRIPTION
**Pull request by MechaShibaa**
Please Add our logo on trust wallet :)

thank you!

### CODE REVIEW

**Comment by MechaShibaa** [comment]
payment made

**Comment by Cryptocool1** [comment]
info file should be named info.json exactly
logo file should be named logo.png exactly
please change

**Comment by MechaShibaa** [comment]
how do i change the file name? i cant drop a new attachment heere somehow

**Comment by MechaShibaa** [comment]
Logo

does this work?

**Comment by Cryptocool1** [comment]
no

**Comment by Cryptocool1** [comment]
Please create new PR, follow doc https://community.trustwallet.com/t/how-to-submit-a-token-logo/3863
You may want to try our Assets app in beta; go to https://assets.trustwallet.com, log on with Github, enter contract ID, logo and some additional info, and it will create a PR for you.
See https://community.trustwallet.com/t/how-to-submit-a-token-logo-using-assets-app/82957.
you don't need to pay one more time

**Comment by MechaShibaa** [comment]
ok done it with the assets app in beta
please check if its ok. 

Thanks!

**Comment by MechaShibaa** [comment]
Screenshot 2021-07-09 at 14 15 15

Hello, Why is there another payment required? your previous message mentioned that we dont need to pay one more time.

Please rectify.

Thank you

**Comment by MechaShibaa** [comment]
[file.json.txt](https://github.com/trustwallet/assets/files/6790712/file.json.txt)

File for the info.json

**Pull request closed without merging**
