### PR TITLE
Add GameStation (POLYGON)

### PR DESCRIPTION
**Pull request by NoahMaizels**
Adding info for POLYGON token 'GameStation'.

PR created by <a href="https://assets.trustwallet.com">TW Assets Management</a>

### CODE REVIEW

**Comment by ramsty** [comment]
Hi!
Could you answer some questions?
• What is the purpose of this token? How will it benefit Trust Wallet users?
• How is the token being distributed? Are you conducting an airdrop?
• Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?
• Is the token listed on a centralized/decentralized exchange?
• Is a Smart Contract audit completed? Where can we find this information?

**Comment by Cryptocool1** [comment]
Please come back to us when the answers will be ready .
When creating a new PR make sure to mention this PR, so that we can see that fee has been paid already here.

**Comment by noahniuwa** [comment]
> Hi! Could you answer some questions? • What is the purpose of this token? How will it benefit Trust Wallet users? • How is the token being distributed? Are you conducting an airdrop? • Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale? • Is the token listed on a centralized/decentralized exchange? • Is a Smart Contract audit completed? Where can we find this information?

Hey sorry I am just seeing these now. Will the answers to these questions be published inside Trustwallet or it is just for your own information?

**Comment by noahniuwa** [comment]
> 
> 
> Hi! Could you answer some questions? • What is the purpose of this token? How will it benefit Trust Wallet users? • How is the token being distributed? Are you conducting an airdrop? • Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale? • Is the token listed on a centralized/decentralized exchange? • Is a Smart Contract audit completed? Where can we find this information?

Hey there, I've answered everything as a comment on this new PR: https://github.com/trustwallet/assets/pull/15831

**Pull request closed without merging**
