### PR TITLE
Add XDAI-ZELEN

### PR DESCRIPTION
**Pull request by ZelenskyyDAO**

### CODE REVIEW

**Comment by Cryptocool1** [comment]
Please create new PR, follow doc https://developer.trustwallet.com/assets/requirements
You may want to try our Assets app in beta; go to https://assets.trustwallet.com, log on with Github, enter contract ID, logo and some additional info, and it will create a PR for you.
See https://developer.trustwallet.com/assets/repository_details

**Comment by ZelenskyyDAO** [comment]
Dear, this is a Xdai token, I follow the exist tokens inside xdai folder. Same code, same pics. why cannot pass pls?
And I didnot see tag in other token code.

**Comment by ZelenskyyDAO** [comment]
{
    "name": "Gnosis Chain",
    "website": "https://xdaichain.com",
    "description": "The first-ever USD stable blockchain and multi-chain staking token.",
    "explorer": "https://blockscout.com/poa/xdai",
    "research": "https://research.binance.com/en/projects/poa-network",
    "symbol": "xDAI",
    "type": "coin",
    "decimals": 18,
    "status": "active",
    "links": [
        {
            "name": "github",
            "url": "https://github.com/xdaichain"
        },
        {
            "name": "twitter",
            "url": "https://twitter.com/xdaichain"
        },
        {
            "name": "reddit",
            "url": "https://reddit.com/r/POA"
        },
        {
            "name": "whitepaper",
            "url": "https://www.xdaichain.com/for-validators/posdao-whitepaper"
        }
    ]
}

**Comment by ZelenskyyDAO** [comment]
{
    "name": "UniCrypt",
    "website": "https://unicrypt.network",
    "description": "UNCX is the governance token of the UniCrypt platform.",
    "explorer": "https://blockscout.com/xdai/mainnet/tokens/0x0116e28B43A358162B96f70B4De14C98A4465f25",
    "type": "XDAI",
    "symbol": "UNCX",
    "decimals": 18,
    "status": "active",
    "id": "0x0116e28B43A358162B96f70B4De14C98A4465f25",
    "links": [
        {
            "name": "twitter",
            "url": "https://twitter.com/UNCX_token"
        },
        {
            "name": "medium",
            "url": "https://unicrypt.medium.com/"
        },
        {
            "name": "telegram",
            "url": "https://t.me/uncx_token"
        },
        {
            "name": "coinmarketcap",
            "url": "https://coinmarketcap.com/currencies/uncx/"
        },
        {
            "name": "coingecko",
            "url": "https://coingecko.com/en/coins/unicrypt"
        },
        {
            "name": "docs",
            "url": "https://docs.unicrypt.network/"
        }
    ]
}

**Comment by Cryptocool1** [comment]
you should follow our doc

**Comment by ZelenskyyDAO** [comment]
Dear, I did not see the guidelines doc about XDAI. pls show me the guidelines about XDAI.
Thanks

**Comment by ZelenskyyDAO** [comment]
Also, pls help me to add tag if you think it is a must.  ZELEN is a governance token for Zelenskyy DAO.

**Pull request closed without merging**
