### PR TITLE
Add MKMOON Logo

### PR DESCRIPTION
**Pull request by mknmoon**
Add MKMOON Logo

### CODE REVIEW

**Comment by Cryptocool1** [comment]
correction needed
Logo file must be named exactly 'logo.png'

**Comment by mknmoon** [comment]
I fixed and re-uploaded the files. what's the problem then?

**Comment by Cryptocool1** [comment]
correction needed
Contract is not in checksum format, should be 0x7D72DEDa97AfCE34caeb5DcbCc4001b7Ceb8074B

**Comment by mknmoon** [comment]
what is checksum ?!

**Comment by Cryptocool1** [comment]
correction needed:

should be     "name": "MonkeyCoin",
not.               "MonkeyCoin": "MonkeyCoin",

**Comment by Cryptocool1** [comment]
> what is checksum ?!

your contract should be 0x7D72DEDa97AfCE34caeb5DcbCc4001b7Ceb8074B (not 0x7d72deda97afce34caeb5dcbcc4001b7ceb8074b)

**Comment by mknmoon** [comment]
I cannot delete the file or fix it!

**Comment by mknmoon** [comment]
I fixed it, please check

**Comment by mknmoon** [comment]
only need to pay?

**Comment by mknmoon** [comment]
OK

**Pull request merged**
