### PR TITLE
what next step to complete the task

### PR DESCRIPTION
**Pull request by zombieworldz**
Hi there,
I paid the fee at this PR https://github.com/trustwallet/assets/pull/18364

So what next step to complete the task?

Thanks,
Bruce

### CODE REVIEW

**Comment by zombieworldz** [comment]
1. What is the purpose of this token? How will it benefit Trust Wallet users?
* ECOSYSTEM TOKEN ($ZwZ)
BEP 20 Standard
Trading
Governance
The Main ingredient uses for Upgrading or crafting NFT
Free of earn, Ranking reward
Tournament
A Limited supply of 1 Billion
* GAMEPLAY TOKEN ($BRAIN)
BEP 20 Standard
Trading
Free to earn, be dropped in all game modes of the game.
BRAIN is used for features and to Level Up or craft NFTs.
To determine plus level points when playing. Corresponding to each level, the main token will be dropped.
To stake and earn.
Unlimited supply

2. How is the token being distributed? https://docs.zombieworldz.io/p/tokenomics/vesting 

Are you conducting an airdrop? 
https://t.me/zombieworldz/151


3. Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?
Yes, we did

4. Is the token listed on a centralized/decentralized exchange?
http://pancakeswap.finance/add/BNB/0x5445451C07E20bA1ca887B6c74d66D358F46D083

5. Is a Smart Contract audit completed? Where can we find this information?
https://www.certik.com/projects/zombieworldz

**Comment by Cryptocool1** [comment]
hello, can you are you the owner of SHEEP token?

**Comment by zombieworldz** [comment]
@Cryptocool1 
No,I dont know SHEEP token?My tọken is ZWZ

**Comment by Cryptocool1** [comment]
why are you deleting all the info of SHEEP token?

**Comment by zombieworldz** [comment]
@Cryptocool1 can you send me the information that told me deleted info of SHEEP token?I don't have any idea about SHEEP token maybe we have some misunderstand here.

**Comment by zombieworldz** [comment]
Hi @Cryptocool1 @cryptomanz my team just revert SHEEP token information.Please help to check again.Thank you

**Comment by cryptomanz** [comment]
As per our policy, brand new tokens are not included, there is a minimum requirement of 10,000 holder addresses and 15,000 transactions, in order to filter out scam tokens.
See the criteria at : https://developer.trustwallet.com/assets/requirements .

**Comment by Cryptocool1** [comment]
Are you conducting an airdrop?

**Pull request merged**
