### PR TITLE
Add BabyMeta logo and info

### PR DESCRIPTION
**Pull request by BabyMetaCoin**
The logo and info details of BabyMeta are  attached, request you to update the logo in trust wallet

### CODE REVIEW

**Comment by cryptomanz** [comment]
As per our policy, brand new tokens are not included, there is a minimum requirement of 25,000 holder addresses and 50,000 transactions, in order to filter out scam tokens.
See the criteria at : https://developer.trustwallet.com/assets/requirements .

**Comment by cryptomanz** [comment]
Please come back to us when all criteria are met.
When creating a new PR make sure to mention this PR, so that we can see that fee has been paid already here.

**Comment by BabyMetaCoin** [comment]
This is not fair. The criteria changing has not been explicitly mentioned anywhere. You should've not processed the payment in that case. Please process a refund in that case. 

This token is listed in CMC and CG. We are not a scam token. We have a great utility in place and the details are available in our website. 
The dev for the team is same as the one for BabyShibaINU. The dev is doxxed in Baby Shiba INU and logo was updated in trust wallet. Remember BabyShibaINU has close to 1Lakh holders.

We are not a scam token. I would like you to reconsider the decision and have our logo added OR kindly process a refund.

**Comment by Cryptocool1** [comment]
Снимок экрана 2021-11-22 в 09 02 36

**Comment by BabyMetaCoin** [comment]
I repeat you have modified the criteria. I have filled in and assisted many of them in filling the requests. The minimum holders were 5000. If it's changed to 25000 it should've been explicitly mentioned before the pull request is submitted. I know the steps so there was no need for me to read the criteria as Ive done it several times before.

I understand you have changed the criteria because there are many scam tokens. To show your our reliability, I want you to verify our website to understand our utility, we have a working demo already
ii) we are the same dev as BabyShibaInu. It has close to 100K holders and the logo is already updated in trust wallet.
iii) We have listed in CG and CMC
CMC: https://coinmarketcap.com/currencies/baby-meta/
CG: https://www.coingecko.com/en/coins/baby-meta
iv) The dev is doxxed in BabyShibaInu already. The token is live since June 2021.
I am sure these information are more than enough to prove we a legit and not a scam token.

Request you to reconsider you decision based on the information provided now and please publish the logo

**Comment by Cryptocool1** [comment]
• What is the purpose of this token? How will it benefit Trust Wallet users?
 • How is the token being distributed? Are you conducting an airdrop?
 • Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?
 • Is the token listed on a centralized/decentralized exchange?
 • Is a Smart Contract audit completed? Where can we find this information?

**Comment by BabyMetaCoin** [comment]
Hello Team,

Could you please update on this request

**Comment by BabyMetaCoin** [comment]
HI Team,

It would be great if you could share an update on this request please

**Comment by Cryptocool1** [comment]
As per our policy, brand new tokens are not included, there is a minimum requirement of 25,000 holder addresses and 50,000 transactions, in order to filter out scam tokens.
See the criteria at : https://developer.trustwallet.com/assets/requirements .

**Comment by BabyMetaCoin** [comment]
I already responded to this message Please see my responses

This is not fair. The criteria changing has not been explicitly mentioned anywhere. You should've not processed the payment in that case. Please process a refund in that case.

This token is listed in CMC and CG. We are not a scam token. We have a great utility in place and the details are available in our website.
The dev for the team is same as the one for BabyShibaINU. The dev is doxxed in Baby Shiba INU and logo was updated in trust wallet. Remember BabyShibaINU has close to 1Lakh holders.

We are not a scam token. I would like you to reconsider the decision and have our logo added OR kindly process a refund.

I repeat you have modified the criteria. I have filled in and assisted many of them in filling the requests. The minimum holders were 5000. If it's changed to 25000 it should've been explicitly mentioned before the pull request is submitted. I know the steps so there was no need for me to read the criteria as Ive done it several times before.

I understand you have changed the criteria because there are many scam tokens. To show your our reliability, I want you to verify our website to understand our utility, we have a working demo already
ii) we are the same dev as BabyShibaInu. It has close to 100K holders and the logo is already updated in trust wallet.
iii) We have listed in CG and CMC
CMC: https://coinmarketcap.com/currencies/baby-meta/
CG: https://www.coingecko.com/en/coins/baby-meta
iv) The dev is doxxed in BabyShibaInu already. The token is live since June 2021.
I am sure these information are more than enough to prove we a legit and not a scam token.

Request you to reconsider you decision based on the information provided now and please publish the logo

What is the purpose of this token? How will it benefit Trust Wallet users?

The utility developed in Baby Meta will be integrated into the real life use-case, which is to have a place where people can upload their NFTs to virtual rooms (aka the metaverse). Could be used as a gallery of sorts to show off your collection. On the website (https://www.babymetacoin.com/) we have a small demo of that. Future we will have an upload button so you can upload yourself.

Trust wallet holders will be able to see the number of tokens as well as constant growth due to the reflections they get just by holding. Holders will also have special privileges when the use-case is launched.

How is the token being distributed? Are you conducting an airdrop?

The token was distributed through fair launch on the binance smart chain on 18 November 2021. Yes, 8 airdrops between 1.25-1.5% were made before launch to team members and for exchange purposes

Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale? Is the token listed on a centralized/decentralized exchange?

No, the tokens were not sold at an ICO or presale. It was a fair launch (with initial liquidity of 6 BNB).

It is listed on pancakeswap, a decentralized exchange
https://pancakeswap.finance/info/token/0x4cc3c88dac183f7a1d082f895bdfaf2284253394

Is a Smart Contract audit completed? Where can we find this information
The audit is underway. We are working with Certik on this.

**Comment by BabyMetaCoin** [comment]
In summary, we are not a scam token. We are doxxed and our other token has the logo updated in trust wallet with close to 100K holders. Keeping that in mind, request you to add the logo for Baby Meta too

**Comment by BabyMetaCoin** [comment]
It isnt fair to keep us waiting. Your only concern is this shouldnt be a scam token. I have already gievn all my reasons above to prove this is not a scam token. We are the same dev team as Baby Shiba INU. We have our logo added for that token in trust wallet with 100K holders. If you need, you can join the telegram group of both the tokens and I would reply from there to confirm its the same team

**Comment by BabyMetaCoin** [comment]
guys, please update the logo. We've been waiting for 5 days already

**Comment by BabyMetaCoin** [comment]
Hello - What's the update on this

**Comment by Cryptocool1** [comment]
hello,
we have already respond you.

**Pull request closed without merging**
