### PR TITLE
Add fs.video Token (BEP20)

### PR DESCRIPTION
**Pull request by byqm68**
Adding info for BEP20 token 'fs.video Token'.

PR created by <a href="https://assets.trustwallet.com">TW Assets Management</a>

### CODE REVIEW

**Comment by byqm68** [comment]
> 你好！为了补偿处理 PR 的努力，我们恳请捐款。 💀由于**没有退款**，所以在**支付费用**之前，请确保**新代币满足最低流通量和其他[接受标准](https://developer.trustwallet.com/assets/new-asset)**。 另请参阅[PR 费用常见问题解答](https://developer.trustwallet.com/assets/faq)。
> 
> 请用备忘录**19684**支付 **1000 TWT** 到地址。 或者，也接受 5 BNB（相同的备忘录和地址）。****`bnb1tqq9llyr3dyjd559dha6z5r5etk3qfwk07m098`
> 
> **二维**码：[信任](https://api.qrserver.com/v1/create-qr-code/?size=200x200&data=https%3A%2F%2Flink.trustwallet.com%2Fsend%3Fcoin%3D714%26address%3Dbnb1tqq9llyr3dyjd559dha6z5r5etk3qfwk07m098%26amount%3D1000%26memo%3D19684)| [其他钱包](https://api.qrserver.com/v1/create-qr-code/?size=200x200&data=bnb1tqq9llyr3dyjd559dha6z5r5etk3qfwk07m098%3Famount%3D1000%26memo%3D19684)
> 
> _备注_：
> 
> * [Trust Wallet 代币 (TWT)](https://community.trustwallet.com/t/trust-wallet-token-twt/4187)可以通过我们的[推荐计划](https://community.trustwallet.com/t/invite-a-friend-earn-trust-wallet-token-twt/4125)或[从 DEX/交易所](https://community.trustwallet.com/t/where-to-get-trust-wallet-tokens/76641)获得。
> * 没有重要用途的新令牌将被拒绝，请参阅上面提到的标准。
> * 一个 PR 应该针对一个项目；超过 10 个标志的 PR 将被拒绝。
> * 付款评估会自动进行，但会延迟几分钟。当检测到付款时，会自动在 PR 上放置 Accept Review，这是合并的条件。
> * 评估 PR 是手动完成的，只有在满足所有条件时才会合并。
> * 支持 TWT-BEP2（币安链），不支持智能链上的 TWT-BEP20 版本。
> 
> 处理此请求需要付费。这些都不属于开发人员。 在支付费用之前，请确保新代币满足最低流通量和其他接受标准。 如果您为提交支付 TWT，这将自动被烧毁。将不予退款。

给一个bsc链的 地址接收twt

**Comment by byqm68** [comment]
bnb1tqq9llyr3dyjd559dha6z5r5etk3qfwk07m098 这个地址是什么链的地址呢？  



| |
小易
|
|
***@***.***
|
On 4/12/2022 ***@***.***> wrote：

Hi! In order to compensate for the efforts of processing PRs, we kindly ask for a contribution.
💀 As there is no refund, before paying the fee, make sure new tokens fulfill the minimum circulation and other acceptance criteria.
See also the PR Fee FAQ.

Please pay 1000 TWT with the memo 19684 to the address bnb1tqq9llyr3dyjd559dha6z5r5etk3qfwk07m098.
Alternatively, 5 BNB is also accepted (same memo & address).

QR code: Trust | other wallet

Notes:

Trust Wallet Tokens (TWT) can be obtained through our Referral Program or from DEXs/exchanges.
New tokens without significant usage are rejected, see criteria mentioned above.
One PR should be for a single project; PR's with more than 10 logos will be rejected.
Payment evaluation happens automatically, but with a few minutes delay. When payment is detected, an Accept Review is automatically placed on the PR, which is a condition for merge.
Evaluating the PR is done manually, and it is merged only if all conditions are satisfied.
TWT-BEP2 is supported (Binance Chain), TWT-BEP20 version on Smart Chain is not.

There will be a fee to process this request. None of it goes to the developers.
Before paying the fee, make sure new tokens fulfill the minimum circulation and other acceptance criteria.
If you are paying TWT for the submission, this will be burned automatically. There will be no refunds.

**Comment by byqm68** [comment]
> bnb1tqq9llyr3dyjd559dha6z5r5etk3qfwk07m098

这个地址 是什么链的地址？

**Comment by byqm68** [comment]
> > bnb1tqq9llyr3dyjd559dha6z5r5etk3qfwk07m098这个地址是什么链的地址呢？小易 | | _**@**_ .*** | 于 2022 年 4 月 12 日_**@**_。_**> 意思是：你好！为了补偿处理公关的努力，我们请求支持。💀没有新人见面，因此在支付费用之前，请确保代币满足最低流通量和其他接受标准。另请公关费用常见问题解答。请使用备忘录接受向地址19684 Tbntqq9llyr3dyjd55907m098 10006z5r5et支付。或者， BNB（同样的备忘录和地址）。二维码：信任 | 其他钱包注意事项：Trust Wallet 代币 (TWT) 可以通过我们的代币从 DEX/交易所获得。项目；评估标志的标志将超过 10 个时被拒绝。评估会进行，但会及时 PR 超过 10 个。的，只能满足所有条件才合并。支持TWT-BEP2（币安链），不支持智能链上的TWT-BEP20版本处理请求需要付费。这些不属于开发人员。在支付之前，请确保新代币满足最低流通量和其他接受标准。您为提交支付T，这将自动被电子邮件记录。不会予刻录此邮件。—如果直接在GitHub上查看，或取消订阅。您收到了消息是因为你写了这个主题。消息ID：**_ @_** . **_> 确保新代币卖最低流通量和其他接受标准。收到此消息是因为您写了该线程。消息ID：_** @**_ . _**> 确保新代币卖最低流通量和其他接受标准。收到此消息是因为您写了该线程。消息ID：**_ @_** .**_>
> 
> 这个地址我成功了呢

这个地址 我转账不成功。确认下地址是否正确

**Comment by byqm68** [comment]
twt 转账到哪个地址


| |
小易
|
|
***@***.***
|
On 4/12/2022 ***@***.***> wrote：

Hi! In order to compensate for the efforts of processing PRs, we kindly ask for a contribution.
💀 As there is no refund, before paying the fee, make sure new tokens fulfill the minimum circulation and other acceptance criteria.
See also the PR Fee FAQ.

Please pay 1000 TWT with the memo 19684 to the address bnb1tqq9llyr3dyjd559dha6z5r5etk3qfwk07m098.
Alternatively, 5 BNB is also accepted (same memo & address).

QR code: Trust | other wallet

Notes:

Trust Wallet Tokens (TWT) can be obtained through our Referral Program or from DEXs/exchanges.
New tokens without significant usage are rejected, see criteria mentioned above.
One PR should be for a single project; PR's with more than 10 logos will be rejected.
Payment evaluation happens automatically, but with a few minutes delay. When payment is detected, an Accept Review is automatically placed on the PR, which is a condition for merge.
Evaluating the PR is done manually, and it is merged only if all conditions are satisfied.
TWT-BEP2 is supported (Binance Chain), TWT-BEP20 version on Smart Chain is not.

There will be a fee to process this request. None of it goes to the developers.
Before paying the fee, make sure new tokens fulfill the minimum circulation and other acceptance criteria.
If you are paying TWT for the submission, this will be burned automatically. There will be no refunds.

**Comment by Cryptocool1** [comment]
Token check error:
 at least 2 links are required, 1 present. Add as many as you can: twitter, github, telegram, reddit, etc
number of holders not checked: please, check it manually
 missing required fields: description
 please change

**Comment by byqm68** [comment]
> 令牌检查错误： 至少需要 2 个链接，存在 1 个。尽可能多地添加：twitter、github、telegram、reddit 等 未检查的持有者数量：请手动检查 缺少必填字段：描述 请更改

您好 在哪里修改。

**Comment by Cryptocool1** [comment]
Please create new PR, follow doc https://developer.trustwallet.com/assets/requirements
You may want to try our Assets app in beta; go to https://assets.trustwallet.com, log on with Github, enter contract ID, logo and some additional info, and it will create a PR for you.
See https://developer.trustwallet.com/assets/repository_details

**Review by byqm68 — COMMENTED** [review]
[info.json.txt](https://github.com/trustwallet/assets/files/8477214/info.json.txt)

**Review by byqm68 — COMMENTED** [review]
[info.json.txt](https://github.com/trustwallet/assets/files/8477319/info.json.txt)

**Comment by byqm68** [comment]
> 请务必提及此 PR，以便可以重复使用该费用
[info.json.txt](https://github.com/trustwallet/assets/files/8477966/info.json.txt)

**Comment by byqm68** [comment]
> ### 公关摘要
> 文件正常： PR 中的 2 个令牌：**BEP20** 0xE9c7a827a4bA133b338b844C19241c864E95d75f 符号：**Fsv**小数：6 链接：[徽标](https://raw.githubusercontent.com/byqm68/assets/br0412-123124/blockchains/smartchain/assets/0xE9c7a827a4bA133b338b844C19241c864E95d75f/logo.png) [信息](https://raw.githubusercontent.com/byqm68/assets/br0412-123124/blockchains/smartchain/assets/0xE9c7a827a4bA133b338b844C19241c864E95d75f/info.json) [网站](https://www.fs.video) [资源管理器](https://bscscan.com/token/0xE9c7a827a4bA133b338b844C19241c864E95d75f) 标签：stablecoin 令牌检查错误： ❌至少需要 2 个链接，目前有 1 个。尽可能多地添加：twitter、github、telegram、reddit 等 ❌未检查的持有人数量：请手动检查 ❌缺少必填字段：描述
> 
>

**Comment by byqm68** [comment]
Hello, I have created a new PR, the link is https://github.com/trustwallet/assets/pull/19709 , please help review @Cryptocool1

**Pull request closed without merging**
