### PR TITLE
Add Wall Street Memes (WSM) (ERC20)

### PR DESCRIPTION
**Pull request by WSMcontact**
Adding info for ERC20 token 'Wall Street Memes (WSM)'.

PR created by <a href="https://assets.trustwallet.com">TW Assets Management</a>

### CODE REVIEW

**Comment by WSMcontact** [comment]
WSM logo TW 1

new logo in 256 x 256 dimensions

**Comment by cryptomanz1** [comment]
• What is the purpose of this token? How will it benefit Trust Wallet users?
 • How is the token being distributed? Are you conducting an airdrop?
 • Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?
 • Is the token listed on a centralized/decentralized exchange?
 • Is a Smart Contract audit completed? Where can we find this information?

**Review by Badz56 — COMMENTED** [review]
Approved

**Comment by Badz56** [comment]
Okay yes

**Comment by WSMcontact** [comment]
1. Purpose of the token was initially a meme token, but more utility is coming. This info is not in the public domain yet so we cant share it.
2. There is a small airdrop, the but the token was mainly distributed via a presale. Users were able to claim their WSM tokens from 26th Sep 2023
3. token presale 
4. token is currently listed on many top tier exchanges including OKX and Huobi. Full listings here - https://coinmarketcap.com/currencies/wall-street-memes/#Markets
5. ill get back to you on the audit - is it needed for listing?

as we have paid now, can you confirm if the token will now be listed please?

**Comment by Cryptocool1** [comment]
Hello, we require smart contract audit from reputable companies(Techrate,Hacken,Certik,Dessert Finance), you can see it in our requirements.
Feel free to come back to us once you complete an audit.

**Comment by WSMcontact** [comment]
we've got an audit - i just had to double check. please see attached 
[SmartContract_Audit_Solidproof_WallStMemes-min (1).pdf](https://github.com/trustwallet/assets/files/12789610/SmartContract_Audit_Solidproof_WallStMemes-min.1.pdf)

**Comment by WSMcontact** [comment]
please can you re-open this? not sure why it was closed? I commentd that I would come back to you with the audit, not that we did not have one

**Comment by WSMcontact** [comment]
@Cryptocool1

**Pull request merged**
