### PR TITLE
Add Grove Token (ERC20)

### PR DESCRIPTION
**Pull request by omer-mutlu**
Adding info for ERC20 token 'Grove Token'.

PR created by <a href="https://assets.trustwallet.com">TW Assets Management</a>

### CODE REVIEW

**Comment by cheemsco** [comment]
Hello, Grove is migrating and new contracts on both BSC & ETH deployed and verified on etherscan. CMC and CG will be updated after launch so as not to get untracked until then. Here are the required links.

Migration announcement from the CEO:

https://twitter.com/JohnGh87/status/1610098051066245120

Current token contracts:

BSC:https://etherscan.io/token/0x84FA8f52E437Ac04107EC1768764B2b39287CB3e

ETH: https://etherscan.io/token/0x84FA8f52E437Ac04107EC1768764B2b39287CB3e

New token contracts:

BSC: https://bscscan.com/token/0xF33893DE6eB6aE9A67442E066aE9aBd228f5290c
ETH: https://etherscan.io/token/0xF33893DE6eB6aE9A67442E066aE9aBd228f5290c

You could refer to the previous pull request for further info: https://github.com/trustwallet/assets/pull/21498

Please advise us for the steps to add the new BSC contract and if we need to also pay for it. Kind regards.

**Comment by cheemsco** [comment]
*Sorry, just noticed we got the token name wrong as we are used to. Can't send a commit as we did the request on assets manager. Could you update the token name to GroveCoin please?

Hello, Grove would like to update info on Trustwallet as a result of migration and rebranding. (Grove token => GroveCoin) Here are the useful links:

Migration announcements:

CEO: https://twitter.com/JohnGh87/status/1610098051066245120
Twitter: https://twitter.com/GroveToken/status/1609721381754740738

Current Contract addresses:

ETH: https://etherscan.io/token/0x84FA8f52E437Ac04107EC1768764B2b39287CB3e
BSC: https://bscscan.com/token/0xaFb64E73dEf6fAa8B6Ef9a6fb7312d5C4C15ebDB

New Contract addresses:

ETH: https://etherscan.io/token/0xF33893DE6eB6aE9A67442E066aE9aBd228f5290c

BSC: https://bscscan.com/token/0xF33893DE6eB6aE9A67442E066aE9aBd228f5290c

Coinmarketcap and Coingecko links will be updated following the launch as the team doesn't want to stay untracked on these platforms. You may access further info on 

https://github.com/trustwallet/assets/pull/21498

Please update the info for both chains and let us know if you need any further information. Kind regards.

**Comment by cheemsco** [comment]
@Cryptocool1

**Comment by cryptomanz1** [comment]
• What is the purpose of this token? How will it benefit Trust Wallet users?
 • How is the token being distributed? Are you conducting an airdrop?
 • Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?
 • Is the token listed on a centralized/decentralized exchange?
 • Is a Smart Contract audit completed? Where can we find this information?

**Comment by cheemsco** [comment]
Hello @cryptomanz1, Grove Token is rebranding to GroveCoin and relaunching. I've just added another PR upon @cryptocool1 's request to be able to add BSC pair too. Here are the useful links.

The pull request for logo last year: https://github.com/trustwallet/assets/pull/21498

Old contracts:

BSC: 0xaFb64E73dEf6fAa8B6Ef9a6fb7312d5C4C15ebDB (has +2 million transactions)
ETH: 0x84FA8f52E437Ac04107EC1768764B2b39287CB3e

New Contracts:

BSC: 0xF33893DE6eB6aE9A67442E066aE9aBd228f5290c
ETH: 0xF33893DE6eB6aE9A67442E066aE9aBd228f5290c

Coinmarketcap:

https://coinmarketcap.com/tr/currencies/grove/

Migration Announcement:

CEO: https://twitter.com/JohnGh87/status/1610098051066245120?s=20&t=5bB4LlUd68jggeC3XRpPjA
Twitter: https://twitter.com/GroveToken/status/1609865941369917441?s=20&t=5bB4LlUd68jggeC3XRpPjA

I used the correct name on BSC PR but apparently used wrong name here. Would appreciate if you could change token name to Grovecoin. Please indicate if you have further questions. Kind regards.

**Pull request merged**
