### PR TITLE
add logo brics

### PR DESCRIPTION
**Pull request by minebrice**
add brics logo

### CODE REVIEW

**Comment by minebrice** [comment]
Are there problems with uploaded files? Can I make a payment?

**Comment by Cryptocool1** [comment]
Please create new PR, follow doc https://developer.trustwallet.com/listing-new-assets/requirements
You may want to try our Assets app in beta; go to https://assets.trustwallet.com, log on with Github, enter contract ID, logo and some additional info, and it will create a PR for you.
See https://developer.trustwallet.com/listing-new-assets/repository_details

**Comment by bricsmine** [comment]
hello .please check #27574

**Comment by bricsmine** [comment]
> Please create new PR, follow doc https://developer.trustwallet.com/listing-new-assets/requirements You may want to try our Assets app in beta; go to https://assets.trustwallet.com, log on with Github, enter contract ID, logo and some additional info, and it will create a PR for you. See https://developer.trustwallet.com/listing-new-assets/repository_details

hello .please check #27574

**Pull request closed without merging**
