### PR TITLE
Add Real Smurf Cat (ERC20)

### PR DESCRIPTION
**Pull request by smurfcatdev**
Adding info for ERC20 token 'Real Smurf Cat'.

PR created by <a href="https://assets.trustwallet.com">TW Assets Management</a>

### CODE REVIEW

**Comment by Cryptocool1** [comment]
• What is the purpose of this token? How will it benefit Trust Wallet users?
 • How is the token being distributed? Are you conducting an airdrop?
 • Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?
 • Is the token listed on a centralized/decentralized exchange?
 • Is a Smart Contract audit completed? Where can we find this information?

**Comment by smurfcatdev** [comment]
This is a meme project, it will make people use more trust wallet and allow our holders to more easily and safely interact with our token, As you can see the project did very well and was fully distributed at launch with multiple centralized exchanges like Gate, MEXC, Poloniex, BTSE, CoinEx, also Smurfcat currently have 12 000 on-chain holders and it was close to 10 000 during the early stage of the initial token distribution since the meme was very viral at the time.
There's currently 210 000 transfers. We don’t do airdrop, no presale, no ICO. It’s on Coinmarketcap and all platforms

**Comment by cryptomanz1** [comment]
do you have Smart Contract audit?

**Comment by smurfcatdev** [comment]
Yes, here is the audit report
https://skynet.certik.com/projects/smurf-cat?utm_source=CMC&utm_campaign=AuditByCertiKLink

**Pull request merged**
