### PR TITLE
add MMIT logo #24564

### PR DESCRIPTION
**Pull request by dunitech123**
Fees is already payed on #24564 memo

### CODE REVIEW

**Comment by dunitech123** [comment]
Fees is already payed on https://github.com/trustwallet/assets/pull/24564 memo.please do check and add mmit logo in trust wallet.

**Comment by dunitech123** [comment]
MMIT contract almost 1500 holders increased from the day i have applied for adding logo.

**Comment by dunitech123** [comment]
@Cryptocool1 Can you give me any update ?

> @Cryptocool1 MMIT contract almost 1500 holders increased from the day i have applied for adding logo.

**Comment by Cryptocool1** [comment]
Please read my comment in the previous PR again.

**Comment by dunitech123** [comment]
i have read that already. 20k holders completions takes very long time.
if there is airdrop even not all holders belongs from airdrop.just demanding double of actual requirement is not right.
we have payed fees for 10k holders requirement.

**Comment by dunitech123** [comment]
@Cryptocool1 
This https://bscscan.com/token/0x74b3abb94e9e1ecc25bd77d6872949b4a9b2aacf token has 725 holders even token logo appearing on trustwallet ?

**Comment by Cryptocool1** [comment]
You got 10k holders so fast, within 1-2 weeks? Please tell me why is it too hard to get this amount again  ? (Organically)

**Comment by Cryptocool1** [comment]
How long did it take to reach 10k holders for you?

**Comment by dunitech123** [comment]
its not in our hand just know that  it takes time we can not predict date or months

**Comment by dunitech123** [comment]
Okay...fine

**Pull request closed without merging**
