### PR TITLE
Add NAYM (Base)

### PR DESCRIPTION
**Pull request by Huanzhang89**
Preemptive PR for NAYM which is launching on various exchanges & Uniswap on 22 Oct 2024.

### CODE REVIEW

**Comment by Huanzhang89** [comment]
Link to our quantstamp audit which includes the token contracts:
https://certificate.quantstamp.com/full/nayms-2024-retainer/04e1c37c-19e8-4c7d-b743-268e4a6466c9/index.html

**Comment by cryptomanz1** [comment]
• What is the purpose of this token? How will it benefit Trust Wallet users?
 • How is the token being distributed? Are you conducting an airdrop?
 • Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?
 • Is the token listed on a centralized/decentralized exchange?

**Comment by Huanzhang89** [comment]
NAYM is the governance token for the NLF with additional reward functionality from staking (more info here: https://docsend.com/view/m5mx7d7bnc3vvw4r). One major reason we need this in trustwallet (which also allows token info to show up on uniswap) is that there are already malicious tokens deployed on base mainnet with a malicious uniswap pool. This will help users identify the official token. 

NAYM will be listed on October 22 2024 on Kucoin, Gate.io and MXC (https://www.kucoin.com/announcement/en-naym-naym-gets-listed-on-kucoin-world-premiere) and there were 2 launchpad presales last week on Weway which sold out and an additional launchpad sale through Poolz just before CEX listings. 

Official Uniswap pool launch on base will be active shortly after CEX listings with the possibility of an Aerodrome listing in the works. 

@cryptomanz1 let me know if you need any additional info~

**Comment by Huanzhang89** [comment]
NAYM is now live on the following CEXs & uniswap:
Kucoin: https://www.kucoin.com/trade/NAYM-USDT
Gate: https://www.gate.io/price/naym-naym
MEXC: https://www.mexc.com/price/NAYM
Uniswap: https://app.uniswap.org/explore/tokens/base/0x314d7f9e2f55b430ef656fbb98a7635d43a2261e

**Comment by Cryptocool1** [comment]
Hello, 
Thank you for your interest, 
In order for the pull request to be approved, the submission has to meet several important requirements. For this request, it does not meet the following:

- at least 10000 token holders
- at least 15000 transactions

To know more about the token approval guidelines, please check this article: [How to Submit Token Logo](https://developer.trustwallet.com/listing-new-assets/requirements).

Feel free to re-open pull request once you meet those requirements.

**Pull request closed without merging**
