### PR TITLE
Add Poor Quack (BEP20)

### PR DESCRIPTION
**Pull request by GyroPQ**
Adding info for BEP20 token 'Poor Quack'.

PR created by <a href="https://assets.trustwallet.com">TW Assets Management</a>

### CODE REVIEW

**Comment by GyroPQ** [comment]
Audited by Certik: https://www.certik.com/projects/poorquack-com

**Comment by GyroPQ** [comment]
2,217 holders but this does not include stakers.

8,590 transactions.

4,400 staking transactions.

**Comment by cryptomanz** [comment]
• What is the purpose of this token? How will it benefit Trust Wallet users?
 • How is the token being distributed? Are you conducting an airdrop?
 • Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?
 • Is the token listed on a centralized/decentralized exchange?

**Comment by cryptomanz** [comment]
As per our policy, brand new tokens are not included, there is a minimum requirement of 10,000 holder addresses and 15,000 transactions, in order to filter out scam tokens.
See the criteria at : https://developer.trustwallet.com/assets/requirements .

**Comment by cryptomanz** [comment]
Please come back to us when all criteria are met.
When creating a new PR make sure to mention this PR, so that we can see that fee has been paid already here.

**Pull request closed without merging**
