### PR TITLE
GCCOIN INFO update

### PR DESCRIPTION
**Pull request by gccoinbnb**
GCCOIN INFO update

### CODE REVIEW

**Comment by gccoinbnb** [comment]
hi we meet all the requirement now can u plz update us now 

Make sure to mention this PR so the fee can be reused

OLD:
https://github.com/trustwallet/assets/pull/27678

**Comment by gccoinbnb** [comment]
Tokenomics:
Total Supply: 1 Billion
Distribution:
Fair Launch: 90%
Team: 5% Lock in PinkSale
Cex Reserve: 5% Lock in PinkSale

RoadMap is long u can see it in the whitepaper

More Info:
WebSite:https://gccoin.io/
Telegram:https://t.me/thegccoin
Twitter:https://twitter.com/theGCCOIN
Instagram: https://www.instagram.com/thegccoin

CoinMarketCap : https://coinmarketcap.com/currencies/gccoin/

CoinGecko
https://www.coingecko.com/en/coins/gccoin

Contract Address: 0x2D8269Dae518e78D95110dbFADf1fb479b8152e7

Audit 1 By Ace: https://github.com/Audit-Ace/Audits-Smart-Contracts/blob/main/GCCOIN%20Audit%20Report.pdf

Audit 2 By CyberScope:https://www.cyberscope.io/audits/gcc

**Comment by gccoinbnb** [comment]
joint toobit on 29 mar link here https://x.com/Toobit_official/status/1770774896945066475?s=20

**Comment by Cryptocool1** [comment]
Hello, how did you get more than 10k holders in couple of days?

**Comment by gccoinbnb** [comment]
listed in cmc and cg and toobit and massive marketing

**Comment by gccoinbnb** [comment]
other cex on the way will

**Comment by gccoinbnb** [comment]
and we was 8.5k

**Comment by gccoinbnb** [comment]
IMG_3335

**Comment by Cryptocool1** [comment]
Have you conducted any airdrops?

**Comment by gccoinbnb** [comment]
IMG_3340
IMG_3341

**Comment by gccoinbnb** [comment]
no

**Comment by gccoinbnb** [comment]
[GCC pr.xlsx](https://github.com/trustwallet/assets/files/14735532/GCC.pr.xlsx)
PR article

**Comment by gccoinbnb** [comment]
hello trustwallet team any update please

**Comment by gccoinbnb** [comment]
hello trustwallet team any update please

**Pull request merged**
