### PR TITLE
ROOST on BASE

### PR DESCRIPTION
**Pull request by CryptoBundy**
ROOST - 0xe1abd004250ac8d1f199421d647e01d094faa180

### CODE REVIEW

**Comment by CryptoBundy** [comment]
[info.json](https://github.com/trustwallet/assets/files/14880776/info.json)
logo

**Comment by CryptoBundy** [comment]
I added the info.json and logo.png for the ROOST Coin Token under the Base Assets however the bot said there is no files?

**Comment by CryptoBundy** [comment]
The files were filed under base/assets as per the instructions on submitting token assets, and can be seen on the Files Tab. however the bot keeps saying there are no tokens found.  Can you please explain why and what I have done wrong.  We are trying to get this listed on TW asap.

**Comment by cryptomanz1** [comment]
• What is the purpose of this token? How will it benefit Trust Wallet users?
 • How is the token being distributed? Are you conducting an airdrop?
 • Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?
 • Is the token listed on a centralized/decentralized exchange?
 • Is a Smart Contract audit completed? Where can we find this information?

**Comment by CryptoBundy** [comment]
• What is the purpose of this token? How will it benefit Trust Wallet users?  $ROOST is a MEME token on the Base Chain with a strong community, being a meme it doesn't have utility.  By being listed on TW it would be much easier for TW users including myself.
• How is the token being distributed? Are you conducting an airdrop? The token has already launched and all 1bn tokens are in circulation
• Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale? it was ICO style offer, all pre-salers were airdropped their tokens 10 days ago,  all tokens are in circulation.
• Is the token listed on a centralized/decentralized exchange? The tokens DEX LP is on Uniswap with solid trading volume (few Million USD/day).  also listed on 8+ CEXs including a Tier 1 (GateIO).  List of CEXs that it is listed on can be found on CMC and CG.  More listings will be happening this week
• Is a Smart Contract audit completed? Where can we find this information?  CEXs including GATEIO have audited the contract, we are working on contract audit.  Additionally the contract has been renounced.

**Comment by CryptoBundy** [comment]
BTW as some feedback - The Base Chain isn't a selectable type when using this form https://assets.trustwallet.com/  I had to find another way to submit the pull request.

**Comment by Cryptocool1** [comment]
Hello, we require full smart contract audit from reputable companies (such as Techrate, Certik, Hacken, Dessert Finance.) 
Please come back to us once all criteria are met. Make sure to mention this PR once all criteria are met.

**Comment by CryptoBundy** [comment]
do i just update this PR or do i need to create a new PR and pay the 500 TWT again?

**Comment by CryptoBundy** [comment]
Also is Hashlock which is an Australian Smart Contract Auditing business classed as reputable?

**Comment by CryptoBundy** [comment]
We have completed the contract audit - new Pull Request https://github.com/trustwallet/assets/pull/27992

Can you please apply the payment we paid for this pull request to the new request? @cryptomanz1 @Cryptocool1

**Pull request closed without merging**
