### PR TITLE
Add PAINT logo and info

### PR DESCRIPTION
**Pull request by keirongulrajani**

### CODE REVIEW

**Comment by catenocrypt** [comment]
Correction needed:  The folder corresponding to token contract should be in 'checksum' format:

XXX   'Expect asset at path /home/runner/work/assets/assets/blockchains/ethereum/assets/0x4c6ec08cf3fc987c6c4beb03184d335a2dfc4042 in checksum: '0x4C6eC08CF3fc987c6C4BEB03184D335A2dFc4042''

Please rename.  (If easier, create new PR; no need to pay fee again, just mention old PR).

**Comment by keirongulrajani** [comment]
@catenocrypt I have fixed the folder naming issue and also noticed the `id` was not in checksum format so changed that too

**Comment by keirongulrajani** [comment]
@catenocrypt @zachzwei the requested amendments have been made (which you can see as all checks are now passing) but I'm not able to change the status and I can see others have been merged in the mean time; can you confirm if any more amendments need to be done?

**Comment by catenocrypt** [comment]
This is already merged

**Pull request merged**
