### PR TITLE
Removed Unwanted Token Logo

### PR DESCRIPTION
**Pull request by cbucks**

### CODE REVIEW

**Comment by kolya182** [comment]
Reason for removal ?

**Comment by cbucks** [comment]
@kolya182 We have duplicate listed tokens sir, our token holders are confused.

**Comment by kolya182** [comment]
@cbucks What are the new contracts ?

**Comment by cbucks** [comment]
This is our new and final token (we are keeping this): 0xa98F029bb4e74C12FB07BBc25854E5a04F7acF4c

We intend to remove these old tokens:
0x5f9505D8Ad3D92E7507b9966f84772993A26356b
0xaC6D73c8C6955Ae575bbA428025098215472f661

Thank you for accommodating.

**Pull request merged**
