### PR TITLE
Add VLaunch (BEP20)

### PR DESCRIPTION
**Pull request by dban0001**
Adding info for BEP20 token 'VLaunch'.

PR created by <a href="https://assets.trustwallet.com">TW Assets Management</a>

### CODE REVIEW

**Comment by cryptomanz** [comment]
As per our policy, brand new tokens are not included, there is a minimum requirement of 10,000 holder addresses and 15,000 transactions, in order to filter out scam tokens.
See the criteria at : https://developer.trustwallet.com/assets/requirements .

**Comment by Cryptocool1** [comment]
submission looks good awaiting for fee payment

**Comment by dban0001** [comment]
Hi, I just added our ETH token as well. Can someone please let me know if these two files look fine. Then I will be happy to pay the fee!

**Comment by dban0001** [comment]
@Cryptocool1 🙏

**Pull request closed without merging**
