### PR TITLE
Add DIVINER (BEP20)

### PR DESCRIPTION
**Pull request by divinergames3**
Adding info for BEP20 token 'DIVINER'.

PR created by <a href="https://assets.trustwallet.com">TW Assets Management</a>

### CODE REVIEW

**Comment by divinergames3** [comment]
hello,I have paid 700TWT

**Comment by Cryptocool1** [comment]
• What is the purpose of this token? How will it benefit Trust Wallet users?
 • How is the token being distributed? Are you conducting an airdrop?
 • Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?
 • Is the token listed on a centralized/decentralized exchange?
 • Is a Smart Contract audit completed? Where can we find this information?

**Comment by divinergames3** [comment]
> • What is the purpose of this token? How will it benefit Trust Wallet users? • How is the token being distributed? Are you conducting an airdrop? • Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale? • Is the token listed on a centralized/decentralized exchange? • Is a Smart Contract audit completed? Where can we find this information?

1. The token aims for rewarding users of our NFT games. The users of trust wallet are accessible to transaction on the decentralized exchange -- pancake swap
2. The output of tokens is determined by the users holding NFT card, and the project party holds 0 tokens. We conducted the partial airdrop of small amount.
3. The project does not sell tokens through ICO.
4. The token has been launched in pancake swap.
5. The smart contract has been audited. Here is the audit link:https://docs.google.com/document/d/1XCMxYNyBTcHvacnhWNJ9cuwtyZbklRCEbaH3ZN6keaE/edit

**Comment by divinergames3** [comment]
1. The token aims for rewarding users of our NFT games. The users of trust
wallet are accessible to transaction on the decentralized exchange --
pancake swap
2. The output of tokens is determined by the users holding NFT card, and
the project party holds 0 tokens. We conducted the partial airdrop of small
amount.
3. The project does not sell tokens through ICO.
4. The token has been launched in pancake swap.
5. The smart contract has been audited. Here is the audit link:
https://docs.google.com/document/d/1XCMxYNyBTcHvacnhWNJ9cuwtyZbklRCEbaH3ZN6keaE/edit

CryptoA ***@***.***> 于2022年4月19日周二 21:19写道：

**Comment by divinergames3** [comment]
Hello, there is a problem with the decimals of our token displayed in your wallet. The token should be accurate to 18 decimal places. Please fix it.

**Comment by Cryptocool1** [comment]
Hello, why did you submit with 4 decimals?

**Pull request merged**
