### PR TITLE
BTCnow Token Logo Update

### PR DESCRIPTION
**Pull request by BTCnowToken**
BTCnow Tokens are built on BSC, a high-performance blockchain network that enables fast and low-cost transactions

### CODE REVIEW

**Comment by BTCnowToken** [comment]
Price is not being pulled from CMC https://coinmarketcap.com/currencies/blockchain-technology-co/

**Comment by Cryptocool1** [comment]
• What is the purpose of this token? How will it benefit Trust Wallet users?
 • How is the token being distributed? Are you conducting an airdrop?
 • Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?
 • Is the token listed on a centralized/decentralized exchange?
 • Is a Smart Contract audit completed? Where can we find this information?

**Comment by BTCnowToken** [comment]
> • What is the purpose of this token? How will it benefit Trust Wallet users?
> • How is the token being distributed? Are you conducting an airdrop?
> • Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?
> • Is the token listed on a centralized/decentralized exchange?
> • Is a Smart Contract audit completed? Where can we find this information?

1. What is the purpose of this token? How will it benefit Trust Wallet users?

BTCnow Token is designed to be a versatile utility token within the blockchain ecosystem. Its primary purpose is to enable seamless transactions, provide staking opportunities, and facilitate decentralized finance (DeFi) activities. For Trust Wallet users, BTCnow Token offers the following benefits:

**Easy Transactions**: Fast and secure transactions with low fees.
**Staking and Rewards**: Users can participate in staking programs to earn rewards.
**Community Engagement**: Access to exclusive community events and voting rights on future developments.
**Marketplace Integration**: The token can be used in various partner platforms for purchasing goods and services.

2. How is the token being distributed? Are you conducting an airdrop?

BTCnow Token distribution includes several methods to ensure wide community participation:

****Community Rewards**: A significant portion of tokens is allocated to community rewards and incentives.
Partnership Programs**: Distributed through partnerships and collaborations to promote ecosystem growth.
**Staking and Liquidity Pools**: Tokens are distributed through staking and liquidity pool incentives to encourage user participation.
**Airdrops**: While we have not conducted a major airdrop yet, we may conduct task-based airdrops in the future to build a wider community and engage users effectively.

3. Did you sell the tokens at an Initial Coin Offering (ICO) or a token presale?

BTCnow Token did not conduct a traditional Initial Coin Offering (ICO). Instead, we opted for a more community-focused distribution model, including:

**Private Sales**: Small private sales to strategic partners and early supporters.
**Public Launch**: The tokens were made available on decentralized exchanges (DEXs) such as PancakeSwap, where the broader community could participate. Additionally, liquidity is locked to ensure stability and trust within the community.

4. Is the token listed on a centralized/decentralized exchange?

Yes, BTCnow Token is listed on both centralized and decentralized exchanges:

**Centralized Exchange** : BTCnow Token is listed on Coin Tiger Central Exchange, providing accessibility and trading options to a broad audience.
**Decentralized Exchange**: The token is also available on PancakeSwap, where users can trade with locked liquidity, ensuring security and confidence in the trading process. [Trade on PancakeSwap](https://pancakeswap.finance/swap?inputCurrency=0x3e9a8df87B2126393e5B492E2AEC3146Eb8C6657&outputCurrency=BNB)

5. Is a Smart Contract audit completed? Where can we find this information?

Yes, a Smart Contract audit has been completed to ensure the security and integrity of the BTCnow Token. You can find more information and verify the audit details on our BSCscan page: [BTCnow Token on BSCscan](https://bscscan.com/token/0x3e9a8df87b2126393e5b492e2aec3146eb8c6657). Additionally, comprehensive project details, including price data, can be found on our [Project Website](https://btcnowcoin.com/) and [CoinMarketCap Listing](https://coinmarketcap.com/currencies/blockchain-technology-co/). For a guide on how to buy BTCnow Token, please visit [How to Buy BTCnow Token](https://www.binance.com/en-NG/how-to-buy/blockchain-technology-co).

**Comment by Cryptocool1** [comment]
Please send your smart contract audit report here

**Comment by BTCnowToken** [comment]
> Please send your smart contract audit report here

Dear Trust Wallet Team,

Thank you for your request. Please find the Smart Contract audit report for BTCnow Token attached.

Audit Report: [Download Audit Report](sandbox:/mnt/data/56@0x3e9a8df87b2126393e5b492e2aec3146eb8c6657_express_audit.pdf)
[56@0x3e9a8df87b2126393e5b492e2aec3146eb8c6657_express_audit.pdf](https://github.com/user-attachments/files/16468721/56%400x3e9a8df87b2126393e5b492e2aec3146eb8c6657_express_audit.pdf)
We acknowledge that this audit was conducted using the De.Fi Scanner tool, and we are actively addressing the issues identified in the report to enhance our smart contract's security and efficiency.

You can also verify our smart contract details and additional information on our BSCscan page: [BTCnow Token on BSCscan](https://bscscan.com/token/0x3e9a8df87b2126393e5b492e2aec3146eb8c6657).

For comprehensive project details, including price data, please visit our [Project Website](https://btcnowcoin.com/) and our [CoinMarketCap Listing](https://coinmarketcap.com/currencies/blockchain-technology-co/). Additionally, for a guide on how to buy BTCnow Token, you can visit [How to Buy BTCnow Token](https://www.binance.com/en-NG/how-to-buy/blockchain-technology-co).

If you have any further questions or require additional information, please do not hesitate to reach out.

Best regards,
BTCnow Token Team

**Comment by Cryptocool1** [comment]
We require smart contract audit from reputable companies (Certik, Techrate, Hacken)
Please come back to us once audit is done. 
Make sure to mention this PR so the fee can be reused

**Pull request closed without merging**
