### PR TITLE
Add BitsCow (BEP20)

### PR DESCRIPTION
**Pull request by methesushil**
Adding info for BEP20 token 'BitsCow'.

PR created by <a href="https://assets.trustwallet.com">TW Assets Management</a>

### CODE REVIEW

**Comment by cryptomanz** [comment]
Hello,
- Can't find contract on your website.

**Comment by methesushil** [comment]
Dear sir cryptomanz,
Contract is updated no on the website.

**Comment by cryptomanz** [comment]
Can you answer some questions?
• What is the purpose of this token? How will it benefit Trust Wallet users?
• How is the token being distributed? 
• Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?
• Is the token listed on a centralized/decentralized exchange?
• Is a Smart Contract audit completed? Where can we find this information?

**Comment by methesushil** [comment]
-- It is our native token and it will be use as fee in our upcoming exchange, Before launching we are distributing it in Pre-sale, Trust Wallet users are storing our tokens in their wallets, Logo will add some weightage on it.
--  We are distributing our tokens  as presale from our website only.
--  We are selling our tokens as Presale without ICO.
--  Our token is not listed on any exchange, we will list it on Pancakeswap on 15th September with liquidity and will burn all remaining tokens.
-- Our Smart contract is very simple and we did not approach for Audit. As we are selling our tokens as a result of community building.

**Comment by cryptomanz** [comment]
awaiting for smart contract audit or cmc listing
on hold for now

**Comment by methesushil** [comment]
@cryptomanz, appreciate your response but,
you know CMC is not possible without listing on any exchange and we are not listed,
audit is not necessary as we are not making any hype or selling through pancakeswap we have our own community those who trust us.
Please let se me say that there are plenty of token logos already listed on Trust Wallet who are not listed on CMC or have any audit,
I have deposited 3 times fee and now you are saying this.
do you have any personal problem with our project?

**Comment by cryptomanz** [comment]
> @cryptomanz, appreciate your response but,
> you know CMC is not possible without listing on any exchange and we are not listed,
> audit is not necessary as we are not making any hype or selling through pancakeswap we have our own community those who trust us.
> Please let se me say that there are plenty of token logos already listed on Trust Wallet who are not listed on CMC or have any audit,
> I have deposited 3 times fee and now you are saying this.

so we can't merge you without that

**Comment by Cryptocool1** [comment]
please create new PR when your token will be listed on CMC
make sure to mention this PR so that fee can can be reused

**Comment by methesushil** [comment]
very strange to know that now logo requests are bein closed by saying Awaiting CMC listing,
Is any token/coin comes on CMC then who cares for Trust Wallet? Trust wallet will get it by itself.

**Comment by methesushil** [comment]
it seems very unfair that trust wallet collaborators working out of the guidelines and trying to get more and more fee only. Nowhere it is mentioned on trust wallet page and website that CMC listing is required for submission of token logo, it is absurd to ask CMC listing. After CMC listing no need to pay fee for Trust Wallet logo submission.
I have lost 3000 TWT tokens as fee which is unfair, they have to list CMC listing in the guideline first.
I request to return my fee.

**Comment by BabyCatCoin** [comment]
> it seems very unfair that trust wallet collaborators working out of the guidelines and trying to get more and more fee only. Nowhere it is mentioned on trust wallet page and website that CMC listing is required for submission of token logo, it is absurd to ask CMC listing. After CMC listing no need to pay fee for Trust Wallet logo submission.
> I have lost 3000 TWT tokens as fee which is unfair, they have to list CMC listing in the guideline first.
> I request to return my fee.

You are very right. They don't accept our request also. Nowhere it is mentioned that CMC listing on Trust Wallet approval conditions. We have paid first for logo and they say CMC listing and they have gone. This is not professional.

**Comment by BabyCatCoin** [comment]
You are very right. They don't accept our request also. Nowhere it is mentioned that CMC listing on Trust Wallet approval conditions. We have paid first for logo and they say CMC listing and they have gone. This is not professional.

**Pull request closed without merging**
