### PR TITLE
add_PBR_tokeninfo

### PR DESCRIPTION
**Pull request by StopDragon**
This PR is being closed due to inactivity. If you wish to continue, please have us reopen the PR before sending your payment.
Do NOT send payments for closed PR, as the fee may by lost!
  (71 vs. 60 hrs)

### CODE REVIEW

**Comment by StopDragon** [comment]
add PBR token logo and info

**Comment by catenocrypt** [comment]
The info.json file is invalid Json, there is an extra trailing comma.  Please fix.
Otherwise submission looks OK.

**Comment by StopDragon** [comment]
> The info.json file is invalid Json, there is an extra trailing comma. Please fix.
> Otherwise submission looks OK.

I don't know where is wrong....plz help

**Comment by catenocrypt** [comment]
The Json is OK now, the other problem is that the contract ID in the folder should be in 'checksum' format:
```
'Expect asset at path /home/runner/work/assets/assets/blockchains/ethereum/assets/0x0d6ae2a429df13e44a07cd2969e085e4833f64a0 in checksum: '0x0D6ae2a429df13e44A07Cd2969E085e4833f64A0''
```
Can you rename, or create a new PR with correct name?
You may want to try our new Assets app in beta;  close this PR; go to https://assets.trustwallet.com, log on with Github, enter contract ID, logo and some additional info, and it will create a PR for you.
See  https://community.trustwallet.com/t/how-to-submit-a-token-logo-using-assets-app/82957.

**Comment by StopDragon** [comment]
> 0x0D6ae2a429df13e44A07Cd2969E085e4833f64A0

Thank you.
I actually don't know much about programming. 
I was able to succeed because you kindly taught me!
Have a nice day.

**Pull request closed without merging**
