### PR TITLE
DOGO update

### PR DESCRIPTION
**Pull request by dogemongo-dev**

### CODE REVIEW

**Comment by cryptomanz** [comment]
Hello,
Can your answer some questions?
 • What is the purpose of this token? How will it benefit Trust Wallet users?
 • How is the token being distributed? Are you conducting an airdrop?
 • Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?
 • Is the token listed on a centralized/decentralized exchange?
 • Is a Smart Contract audit completed? Where can we find this information?

**Comment by dogemongo-dev** [comment]
• What is the purpose of this token? How will it benefit Trust Wallet users?
In App Token for dogemongo 
- buy rocket balls 
- increase your levels 
- buy trainer license 
- more to come 

Outside 
- earn doge while holding dogo 

We have in 48 hours already more then 40,000 Users


• How is the token being distributed? Are you conducting an airdrop?
Fair launch on PancakeSwap 

• Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?
NO

• Is the token listed on a centralized/decentralized exchange?
Yes PancakeSwap 

• Is a Smart Contract audit completed? Where can we find this information?
Yes https://dogemongo.com/techrateaudit.pdf

**Comment by cryptomanz** [comment]
how did you get the 40,000 users in 48h?

**Comment by dogemongo-dev** [comment]
Good Innovation and Concept? 
Even Forbes Mexico posted about our project. https://mobile.twitter.com/Forbes_Mexico/status/1426317645888905217

**Comment by dogemongo-dev** [comment]
I hope we cleared all your queries. Can you please merger our PR ?

**Comment by Cryptocool1** [comment]
Are you conducting an airdrop?

**Comment by dogemongo-dev** [comment]
No we have no airdrop because it’s fair launch. Team has no tokens

**Comment by dogemongo-dev** [comment]
@cryptomanz @Cryptocool1 @catenocrypt is there any other information required ? Can you please merge the PR ?

**Comment by Cryptocool1** [comment]
can you please add links to your PR?
example: https://developer.trustwallet.com/add_new_asset/repository_details

**Comment by dogemongo-dev** [comment]
https://raw.githubusercontent.com/dogemongo-dev/assets/master/blockchains/smartchain/assets/0x9E6B3E35c8f563B45d864f9Ff697A144ad28A371/info.json

do you mean this link ?

**Pull request closed without merging**
