### PR TITLE
Added logo and info for Stonks token

### PR DESCRIPTION
**Pull request by stonks-token**
This PR is being closed due to inactivity. If you wish to continue, please have us reopen the PR before sending your payment, or just create a new one.
Do NOT send payments for closed PR, as the fee may by lost!
  (48 vs. 48 hrs)

### CODE REVIEW

**Comment by cryptomanz** [comment]
Hello,
- Submission looks good. awaiting fee payment.

**Comment by stonks-token** [comment]
@cryptomanz Hey, just realized the PR was closed but we already made the payment. Can you help us here?

**Comment by stonks-token** [comment]
image

**Comment by Cryptocool1** [comment]
great. thanks!!!

**Pull request merged**
