### PR TITLE
Add Public Index Network (BEP20)

### PR DESCRIPTION
**Pull request by inSureToken**
Adding info for BEP20 token 'Public Index Network'.

PR created by <a href="https://assets.trustwallet.com">TW Assets Management</a>

### CODE REVIEW

**Comment by inSureToken** [comment]
Hi!

PIN, is a wrapper of FLO coin (which is live since 2013)
We have already updated the information for our ERC20 wrapper.

This is the request to update the logo and info for our BEP20 token bridge (The bridge to BSC was done in partnership with Anyswap)
You can verify the bridge information here: https://anyswap.net/tokens

Thank you in advance for your help!

**Comment by Cryptocool1** [comment]
As per our policy, brand new tokens are not included, there is a minimum requirement of 5000 holder addresses and 10000 transactions, in order to filter out scam tokens.
See the criteria at (mentioned in the first message by the bot): https://community.trustwallet.com/t/how-to-submit-a-token-logo/3863).
Closing PR for now. Please come back to us when all criteria are met.

**Comment by inSureToken** [comment]
Hi!
PIN, is a wrapper of FLO coin (which is live since 2013)
FLO has more than 11k wallets! You can verify it here: https://flo.tokenview.com/en/

You can check the development timeline here: https://docs.publicindex.network/about-pin/history/timeline

We already have the information for our ERC20 PIN in Trust Wallet.

This is the request to update the logo and info for our BEP20 PIN (The bridge to BSC was done in partnership with Anyswap)
You can verify the bridge information here: https://anyswap.net/tokens

Thank you in advance for your help!

**Comment by inSureToken** [comment]
> As per our policy, brand new tokens are not included, there is a minimum requirement of 5000 holder addresses and 10000 transactions, in order to filter out scam tokens.
> See the criteria at (mentioned in the first message by the bot): https://community.trustwallet.com/t/how-to-submit-a-token-logo/3863).
> Closing PR for now. Please come back to us when all criteria are met.

Hi!
PIN, is a wrapper of FLO coin (which is live since 2013)
FLO has more than 11k wallets! You can verify it here: https://flo.tokenview.com/en/

You can check the development timeline here: https://docs.publicindex.network/about-pin/history/timeline

We already have the information for our ERC20 PIN in Trust Wallet.

This is the request to update the logo and info for our BEP20 PIN (The bridge to BSC was done in partnership with Anyswap)
You can verify the bridge information here: https://anyswap.net/tokens

Thank you in advance for your help!

**Comment by inSureToken** [comment]
Hi CryptoA!
PIN, is a wrapper of FLO coin (which is live since 2013)
FLO has more than 11k wallets! You can verify it here:
https://flo.tokenview.com/en/

You can check the development timeline here:
https://docs.publicindex.network/about-pin/history/timeline

We already have the information for our ERC20 PIN in Trust Wallet.

This is the request to update the logo and info for our BEP20 PIN (The
bridge to BSC was done in partnership with Anyswap)
You can verify the bridge information here: https://anyswap.net/tokens

Thank you in advance for your help!

**Comment by inSureToken** [comment]
Hi, any updates on this ticket?

**Pull request closed without merging**
