### PR TITLE
Add Son of Doge (BEP20)

### PR DESCRIPTION
**Pull request by SODSonofDoge**
Adding info for BEP20 token 'Son of Doge'.

PR created by <a href="https://assets.trustwallet.com">TW Assets Management</a>

### CODE REVIEW

**Comment by SODSonofDoge** [comment]
https://linktr.ee/SonofDoge

**Comment by Cryptocool1** [comment]
• What is the purpose of this token? How will it benefit Trust Wallet users?
 • How is the token being distributed? Are you conducting an airdrop?
 • Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?
 • Is the token listed on a centralized/decentralized exchange?
 • Is a Smart Contract audit completed? Where can we find this information?

**Comment by SODSonofDoge** [comment]
• What is the purpose of this token? How will it benefit Trust Wallet users?
This is a rebrand/relaunch of the SODv2 token so the project carriers with it. An NFT marketplace that utilizes SOD is in the future and a customized launchpad Utilium that allows holders of SOD to earn whitelist spots on the launchpad. Please follow the links for verification https://linktr.ee/SonofDoge.

• How is the token being distributed? Are you conducting an airdrop?
The token is being sold on various exchanges and has a history for holders. Holders of SODv2 will be airdropped their equivalent amounts in SOD.

• Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?
There was no ICO/presale for SOD. The LP for exchanges is being manually paired from SODv2 LP.

• Is the token listed on a centralized/decentralized exchange?
The token is currently being traded on pancakeswap with applications already submitted for migration onto crypto.com. The main reason for the migration is to meet these requirements.

• Is a Smart Contract audit completed? Where can we find this information?
Yes, see attached.
[Son Of Doge Token Security Audit Report By ContractChecker.pdf](https://github.com/trustwallet/assets/files/8712667/Son.Of.Doge.Token.Security.Audit.Report.By.ContractChecker.pdf)

**Comment by Cryptocool1** [comment]
hello, we require smart contract audit from reputable companies (Hacken, Techrate, Dessert Finance, Certik)

**Comment by Cryptocool1** [comment]
Please come back to us when all criteria are met. Make sure to mention this PR so the fee can be reused.

**Pull request closed without merging**
