### PR TITLE
Update logo OctaX & Octa Gold

### PR DESCRIPTION
**Pull request by netdefi**
Please check & update logo for team octax.finance
 -Logo size, Done.
 -Total holder, Done.
-Total transaction, Done.
-Address check sum, Done.

### CODE REVIEW

**Comment by Cryptocool1** [comment]
allow list is not needed

**Comment by netdefi** [comment]
> allow list is not needed

Do I have to fix it first?

**Comment by Cryptocool1** [comment]
submission looks good.

**Comment by netdefi** [comment]
> submission looks good.

thank sir.

**Comment by Cryptocool1** [comment]
> > submission looks good.
> 
> thank sir.

Did you pay for previous PR?

**Comment by netdefi** [comment]
> > > submission looks good.
> > 
> > 
> > thank sir.
> 
> Did you pay for previous PR?

I paid for the previous time but did not pass. Do I have to pay again?

**Comment by netdefi** [comment]
@Cryptocool1 Thank you very much, for helping good team.

**Pull request merged**
