### PR TITLE
added logo and info of token brics

### PR DESCRIPTION
**Pull request by bricsmine**
added logo and info of token brics

This invoice has already been paid: #27561

### CODE REVIEW

**Comment by bricsmine** [comment]
I have already paid to #27253

**Comment by bricsmine** [comment]
> @bricsmine, kind reminder: please pay fee: **500 TWT** with the memo **27574** to the address `bnb158fgd782we4tz9vwwcj9pmmxvxhl6z46lfm7c8`. Alternatively, 5 BNB is also accepted (same memo & address).
> 
> **QR** code: [Trust](https://api.qrserver.com/v1/create-qr-code/?size=200x200&data=https%3A%2F%2Flink.trustwallet.com%2Fsend%3Fcoin%3D714%26address%3Dbnb158fgd782we4tz9vwwcj9pmmxvxhl6z46lfm7c8%26amount%3D500%26memo%3D27574) | [other wallet](https://api.qrserver.com/v1/create-qr-code/?size=200x200&data=bnb158fgd782we4tz9vwwcj9pmmxvxhl6z46lfm7c8%3Famount%3D500%26memo%3D27574) See the [Pull Request Fee FAQ](https://developer.trustwallet.com/assets/faq).

I have already paid to #27253

**Comment by bricsmine** [comment]
https://explorer.binance.org/tx/975D89E859EC717C35659B3953F1CDA76264349B5C05A21AF6B4E25274C17689

**Comment by bricsmine** [comment]
This invoice has already been paid: #27253

**Comment by bricsmine** [comment]
#27561

**Comment by bricsmine** [comment]
I did not find a message. please guide me

**Comment by cryptomanz1** [comment]
As per our policy, there is a minimum requirement of 10,000 holder addresses and 15,000 transactions, in order to filter out scam tokens.
See the criteria at : https://developer.trustwallet.com/listing-new-assets/requirements .

**Comment by cryptomanz1** [comment]
As per our policy, there is a minimum requirement of 10,000 holder addresses and 15,000 transactions, in order to filter out scam tokens.
See the criteria at : https://developer.trustwallet.com/listing-new-assets/requirements .

**Comment by bricsmine** [comment]
We are airdropping. It may take 3 days. Please do not close this pr

**Comment by Cryptocool1** [comment]
> We are airdropping. It may take 3 days. Please do not close this pr

Hello, we do not accept airdropped tokens. Please see our documentation for adding assets. 
cone back to us once you get real holders

**Pull request closed without merging**
