### PR TITLE
Add JUSD Stable (POLYGON)

### PR DESCRIPTION
**Pull request by ejusd**
Adding info for POLYGON token 'JUSD Stable'.

PR created by <a href="https://assets.trustwallet.com">TW Assets Management</a>

### CODE REVIEW

**Comment by ejusd** [comment]
my assistant sent 2BNB by mistake, can you refund please?

**Comment by ejusd** [comment]
> @ejusd, kind reminder: please pay fee: **500 TWT** with the memo **28174** to the address `bnb158fgd782we4tz9vwwcj9pmmxvxhl6z46lfm7c8`. Alternatively, 2 BNB is also accepted (same memo & address).
> 
> **QR** code: [Trust](https://api.qrserver.com/v1/create-qr-code/?size=200x200&data=https%3A%2F%2Flink.trustwallet.com%2Fsend%3Fcoin%3D714%26address%3Dbnb158fgd782we4tz9vwwcj9pmmxvxhl6z46lfm7c8%26amount%3D500%26memo%3D28174) | [other wallet](https://api.qrserver.com/v1/create-qr-code/?size=200x200&data=bnb158fgd782we4tz9vwwcj9pmmxvxhl6z46lfm7c8%3Famount%3D500%26memo%3D28174) See the [Pull Request Fee FAQ](https://developer.trustwallet.com/assets/faq).

payment is already done ...

**Comment by ejusd** [comment]
but by mistake we paid double cost, can we add our token bsc info as well?

https://explorer.bnbchain.org/tx/AFFA5F3D936C1D784B92249DF1B83AE5249D64697DC085368FC743CCE4EC998A
Transaction Hash (TxHash): AFFA5F3D936C1D784B92249DF1B83AE5249D64697DC085368FC743CCE4EC998A | BNB Beacon Chain<https://explorer.bnbchain.org/tx/AFFA5F3D936C1D784B92249DF1B83AE5249D64697DC085368FC743CCE4EC998A>
BNB Beacon Chain Explorer
explorer.bnbchain.org

________________________________

**Comment by ejusd** [comment]
> Hello, please send tx hash

I've sent link already

**Comment by ejusd** [comment]
@Cryptocool1 could you check the tx hash that I've sent?

**Comment by Cryptocool1** [comment]
What do you mean you paid “double cost”?

**Comment by ejusd** [comment]
@Cryptocool1  I mean we've paid 2 BNB which comes more than 1000 TWT, can we add our token bsc information as well?

**Comment by tw-daniel** [comment]
check

**Comment by WarMachineAi** [comment]
@Cryptocool1 @tw-daniel , we've provided our payment link, why our status is not changed and bot is continuously closing the pr?

**Comment by ejusd** [comment]
@Cryptocool1 @tw-daniel , our payment link is there, why our status is not changed and bot is closing the pr continuously?

**Comment by ejusd** [comment]
> @Cryptocool1 @tw-daniel , our payment link is there, why our status is not changed and bot is closing the pr continuously?

@Cryptocool1 @tw-daniel @natedaiger @hexorx

**Comment by ejusd** [comment]
@Cryptocool1 @tw-daniel @natedaiger @hexorx now more than one week, we've provided the payment proof, why no response?

**Comment by ejusd** [comment]
@Cryptocool1 @tw-daniel @natedaiger @hexorx what is really happening here ???

**Comment by ejusd** [comment]
how can we make TWT payment as bep2 chain is not supported anymore?

**Comment by ejusd** [comment]
Hi @Cryptocool1 @tw-daniel — reviving this after a long pause.

To summarize for whoever picks this up:

1. **Payment was made in full.** On May 13, 2024, we paid 2 BNB 
   (which exceeds the 500 TWT equivalent) to the official fee 
   address `bnb158fgd782we4tz9vwwcj9pmmxvxhl6z46lfm7c8` with memo 
   `28174`. TX hash: AFFA5F3D936C1D784B92249DF1B83AE5249D64697DC085368FC743CCE4EC998A
   https://explorer.bnbchain.org/tx/AFFA5F3D936C1D784B92249DF1B83AE5249D64697DC085368FC743CCE4EC998A
   
   The payment was never reflected in the bot's status, which 
   remained on "Payment Status: Requested" indefinitely despite 
   multiple confirmations with a verifiable TX hash.

2. **We effectively paid double.** The 2 BNB sent was meant as the 
   alternative to 500 TWT, but this was equivalent to roughly 1000+ TWT 
   at the time of transfer. Neither the intended nor the excess amount 
   was ever credited against this PR.

3. **The original fee mechanism is now deprecated.** As I noted in 
   September 2024, TWT-BEP2 is no longer supported, so the bot's 
   current instructions cannot be followed even if a second payment 
   were attempted.

4. **JUSD is a legitimate, operational stablecoin** — live on Polygon 
   since 2023, extended to BSC, issuer JDFinex Inc., website jusd.app. 
   It already displays correctly on Trust Wallet for BSC. The only 
   gap is the Polygon listing this PR was meant to fix, which still 
   shows incorrectly in-wallet for our users.

We're not asking for a refund and we're not asking to relitigate 
the fee. We're asking for the PR to be re-evaluated and merged on 
the basis of the payment already made, or for clear written 
guidance on how to proceed given that the original payment rail 
is deprecated.

Thanks

**Pull request closed without merging**
