### PR TITLE
Uploading Drive Token Assets

### PR DESCRIPTION
**Pull request by devros30**
[x] Uploaded info.json file in checksum format
[x] Uploaded logo.png in 256x256 px format

### CODE REVIEW

**Comment by Cryptocool1** [comment]
As per our policy, brand new tokens are not included, there is a minimum requirement of 2500 holder addresses and 5000 transactions, in order to filter out scam tokens.
See the criteria at (mentioned in the first message by the bot): https://community.trustwallet.com/t/how-to-submit-a-token-logo/3863).
Closing PR for now. Please come back to us when all criteria are met.

**Comment by DRIVE-TOKEN** [comment]
Hi there , first of all we paid the fee  and we have more than 5000 holders ?!

**Comment by DRIVE-TOKEN** [comment]
dear mister,

there mus be a fail at upload...
our contract adress is:
BEP20 0xa321fC1171EB85498faD47D3d127368eBa70265C
we got over 5000 holder please check.
Our Token is named DRIVE!
dont know thw adress:
BEP20 0x3Ef99822759A2192e7A82f64484e79e89cd90d52

kind regards!
Alexis

**Comment by devroshin** [comment]
Uploaded info.json and logo.png for DRIVE Token in this pull request . And that token has more than 5000 holders. Please re consider Request .

**Pull request closed without merging**
