### PR TITLE
Add ART COIN (BEP20)

### PR DESCRIPTION
**Pull request by yenky**
This PR is being closed due to inactivity. If you wish to continue, please have us reopen the PR before sending your payment, or just create a new one.
Do NOT send payments for closed PR, as the fee may by lost!
  (96 vs. 48 hrs)

### CODE REVIEW

**Comment by Cryptocool1** [comment]
hello,
• What is the purpose of this token? How will it benefit Trust Wallet users?
 • How is the token being distributed? Are you conducting an airdrop?
 • Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?
 • Is the token listed on a centralized/decentralized exchange?
 • Is a Smart Contract audit completed? Where can we find this information?

**Comment by yenky** [comment]
Hi Cryptocool1,
Thank you for quick response and as you asked before to create new PR only with ARTC so i just created.

 What is the purpose of this token? How will it benefit Trust Wallet users?
 Answer : We created our token to serve people. This is our ultimate goal, as we genuinely want to make your lives better by making payment processes faster and smarter. We collaborate closely with the artist community and love collecting feedback from them.  Feedback is a means of improvement, so we are getting involved in lively discussions with the artists holding ARTC to hear their opinions. We have many users who are using Trust wallet for their ARTC and as we know their are some issue with tokens where people make copy of token and customers get wrong information and they buy wrong token. So if we have logo in trust wallet so all our customers can see very clearly that this is right token to use. As we know Trust wallet is one of the most secure wallet for crypto and we always advise to our customers to use Trust wallet. 

How is the token being distributed? Are you conducting an airdrop?
Answer : 2 months before when team was working on ARTC token idea we decided to distribute in this manner. 
 12% Advisors , 15% project reserve , 6% master-nodes , 5% programmers  (because we have big programmers team who put their ideas and making this more strong day by day and we are coming with many new web services for Utility option of ARTC token ) 43% for crowd sale. 

Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?
Answer : Yes we sold token in initial stage but all the transaction happened with Pancake swap and we have all records here : https://bscscan.com/token/0xB9F41715D64e85C0d78bC4ed6857ef54Cd5B2737  
 As you can check we are having good volume of transactions everyday because our customers are believing in ARTC Token more every day.  Our Presale had an offer with Utility System. We have big Companies who's accepting ARTC as their payment system so their users are also satisfied with our offers of Cash Back System. You can check it here : https://bscscan.com/token/0xb9f41715d64e85c0d78bc4ed6857ef54cd5b2737?a=0x0a2ecf9f64601547943721c1afe9397759d97058

 Is the token listed on a centralized/decentralized exchange?
Answer : We did submission for few decentralize exchange and in few days we are going to be on following exchange : https://wazirx.com/  , https://latoken.com/  We are on dexguru already : https://dex.guru/token/0xb9f41715d64e85c0d78bc4ed6857ef54cd5b2737-bsc   Many of our customer using this decentralized exchange for buy/sell ARTC token 

 Is a Smart Contract audit completed? Where can we find this information?
Answer : You can find inforamation under BSC scaner bscscan : https://bscscan.com/token/0xb9f41715d64e85c0d78bc4ed6857ef54cd5b2737

Trust wallet logo going to help all of our users in a very good way because now they need to check with our support system to find out reality about logo. We are having many big events in coming days and one is happening today and you can check it here : https://www.instagram.com/artcoin.21/



We named our token ART COIN, as its sole purpose is to facilitate your day-to-day life. Art is everywhere when we are making choices, doing our chores, or paying for our stuff. Our team came up with a smart and fast solution to deal with your routine as fast as possible.
Not only do we provide an easy payment method to our users, but we also support the artist community. More and more Asian artists are willing to accept their payment in ARTC tokens, since this is a fast, flexible, and profitable method. Those people who accept an ARTC payment do not have to deal with all bureaucratic banking procedures. Moreover, this is always an artist’s decision whether to keep the token or to sell it, since both options are always available.  


Thank you

**Comment by yenky** [comment]
Hi
I need to send payment , can you please reopen this PR so we can go for next step.

thank you

**Comment by yenky** [comment]
How can i reopen this PR to pay the fee.

Thank You

**Comment by yenky** [comment]
Hi 
Please try to reopen this PR  : https://github.com/trustwallet/assets/pull/14028

Thank you

**Comment by yenky** [comment]
> Hi Please try to reopen this PR : #14028
> 
> Thank you
hi https://github.com/Cryptocool1
 Should i create new one or you can reopen , so i can pay the fee.

Thank you

**Pull request closed without merging**
