### PR TITLE
Add Game Coin (BEP20)

### PR DESCRIPTION
**Pull request by TechWallStreet**
Adding info for BEP20 token 'Game Coin'.

PR created by <a href="https://assets.trustwallet.com">TW Assets Management</a>

### CODE REVIEW

**Comment by Cryptocool1** [comment]
hello,
• What is the purpose of this token? How will it benefit Trust Wallet users?
 • How is the token being distributed? Are you conducting an airdrop?
 • Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?
 • Is the token listed on a centralized/decentralized exchange?
 • Is a Smart Contract audit completed? Where can we find this information?

**Comment by TechWallStreet** [comment]
What is the purpose of this token? Game Coin is the world's first sports cryptocurrency with a purpose.

How will it benefit Trust Wallet users? Trust Wallet users can securely hold their crypto in their wallets and receive reflections from tokenomics from participating exchanges.

How is the token being distributed? You can purchase the token on Pancake Swap and on BitMart (11/24)

Are you conducting an airdrop? Not at this time

Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?  We did a stealth launch and allowed users to purchase the token from Pancake Swap

Is the token listed on a centralized/decentralized exchange? Centralized - BitMart (11/24) and Pancake Swap

Is a Smart Contract audit completed? Where can we find this information? Yes.  CertiK has completed the audit.  Below is the link.
https://www.certik.org/projects/game-coin


Frederick Lenna
Director of Technical Operations
The Game Coin
***@***.***
D. 702-351-8160
https://thegamecoin.net/
________________________________

**Comment by Cryptocool1** [comment]
Снимок экрана 2021-11-15 в 19 10 26
can you change your logo to the full screen image?

**Comment by TechWallStreet** [comment]
Yes. Where will I need to change it?

Frederick Lenna
Director of Technical Operations
The Game Coin
***@***.***
D. 702-351-8160
https://thegamecoin.net/
________________________________

**Comment by Cryptocool1** [comment]
you can send it here, and I will change

**Comment by TechWallStreet** [comment]
Sure try this one

Frederick Lenna
Director of Technical Operations
The Game Coin
***@***.***
D. 702-351-8160
https://thegamecoin.net/
________________________________

**Comment by TechWallStreet** [comment]
Was that okay?

Frederick Lenna
Director of Technical Operations
The Game Coin
***@***.***
D. 702-351-8160
https://thegamecoin.net/
________________________________

**Comment by TechWallStreet** [comment]
logo

**Comment by TechWallStreet** [comment]
To add here, we have been officially listed on CoinGecko as well:

https://www.coingecko.com/en/coins/game-coin

**Pull request merged**
