### PR TITLE
Add FlickerPro (POLYGON)

### PR DESCRIPTION
**Pull request by FlickerFKRPRO**
Adding info for POLYGON token 'FlickerPro'.

PR created by <a href="https://assets.trustwallet.com">TW Assets Management</a>

### CODE REVIEW

**Comment by cryptomanz1** [comment]
As per our policy, there is a minimum requirement of 10,000 holder addresses and 15,000 transactions.
See the criteria at : https://developer.trustwallet.com/listing-new-assets/requirements .

**Comment by Cryptocool1** [comment]
Feel free to come back to us once all criteria are met. Make sure to mention this PR so the fee can be reused

**Comment by FlickerFKRPRO** [comment]
> As per our policy, there is a minimum requirement of 10,000 holder addresses and 15,000 transactions. See the criteria at : https://developer.trustwallet.com/listing-new-assets/requirements .

Dear Sir and Maam 
we have achieved 10000 holders please check it once and please proceed with the further process thank you
https://polygonscan.com/token/0x433e39ce74aef8f409182541269e417ad9b56011

**Comment by FlickerFKRPRO** [comment]
@Cryptocool1, @cryptomanz1

Dear Sir and Maam 
we have achieved 10000 holders please check it once and please proceed with the further process thank you

https://polygonscan.com/token/0x433e39ce74aef8f409182541269e417ad9b56011

**Comment by FlickerFKRPRO** [comment]
payment transfer detail
https://bscscan.com/tx/0xd10d816fa4b40d4df841d22d30d38a2f5c4e1a29a05b62528c8e5e9622d96599

TWT500

**Review by FlickerFKRPRO — COMMENTED** [review]
{
    "name": "FlickerPro",
    "type": "POLYGON",
    "symbol": "FKRPRO",
    "decimals": 18,
    "website": "https://flickertechnology.com/",
    "description": "FlickerPro where we introduce an innovative crypto token designed to revolutionize finance, real estate, e-commerce, and the traveling & hospitality sectors. offering high-speed transactions and low fees. This whitepaper outlines the key aspects of FlickerPro including its token overview, project details, future plans, staking program, tokenomics, roadmap, and the profiles of its creators.",
    "explorer": "https://polygonscan.com/token/0x433e39ce74aef8f409182541269e417ad9b56011",
    "status": "active",
    "id": "0x433e39ce74aef8f409182541269e417ad9b56011",
    "links": [
        {
            "name": "twitter",
            "url": "https://x.com/Flicker46278331"
        },
        {
            "name": "telegram",
            "url": "https://t.me/FlickerProOfficial"
        },
        {
            "name": "coinmarketcap",
            "url": "https://coinmarketcap.com/currencies/flickerpro/"
        },
        {
            "name": "facebook",
            "url": "https://facebook.com/flickertechnology"
        },
        {
            "name": "whitepaper",
            "url": "https://flickertechnology.com/flicker/uploads/whitepaper.pdf"
        }
    ],
    "tags": [
        "defi"
    ]
}

**Comment by FlickerFKRPRO** [comment]
• What is the purpose of this token? How will it benefit Trust Wallet users?

FKRPRO Token is native token of FlickerPro Ecosystem, FlickerPro will launch FlickerPro Exchange And FKRPRO Token will be our base token, Trust wallet users will be able to hold Verified FKRPRO Token which can help against potential Fake FKRPRO Tokens, Also as our holder base is growing exponentially, adding FKRPRO to Trust Wallet Assets will be a mutually beneficial.
Customers can stake FKRPRO using USDT for a certain time and get back FKRPRO as rewards. -

• How is the token being distributed? Are you conducting an airdrop?

No we are not conducting AirDrops.
• Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?

No.
• Is the token listed on a centralized/decentralized exchange?

Token is listed on DEX Uniswap / CEX Koinpark will be soon listed on other exchanges.
• Is a Smart Contract audit completed? Where can we find this information?

Yes we have completed smart contract audit.
https://github.com/TechRate/Smart-Contract-Audits/blob/main/July_2024/FlickerPro.pdf
Additionally we have also listed on CoinMarketCap - https://coinmarketcap.com/currencies/flickerpro/, You can find more details here.

Thank you

**Comment by FlickerFKRPRO** [comment]
@Cryptocool1, @cryptomanz1

Dear Sir and Maam
we have achieved 10000 holders please check it once and please proceed with the further process thank you

https://polygonscan.com/token/0x433e39ce74aef8f409182541269e417ad9b56011

**Comment by FlickerFKRPRO** [comment]
@Cryptocool1, @cryptomanz1: Hello, thank you for the merge

Can you tell please , how we can open price data for the FKRPRO Token inside Trust Wallet app?

Now we can`t see any information and price. We have pages at CMC or CG where data can be fetched from.

Thank you in advance!

WhatsApp Image 2024-07-30 at 11 31 40 AM
WhatsApp Image 2024-07-30 at 11 30 44 AM

**Pull request merged**
