### PR TITLE
Update TW Logo

### PR DESCRIPTION
**Pull request by Cryptopolisgame**

### CODE REVIEW

**Comment by cryptomanz1** [comment]
Please create new PR, follow doc https://developer.trustwallet.com/assets/requirements
You may want to try our Assets app in beta; go to https://assets.trustwallet.com, log on with Github, enter contract ID, logo and some additional info, and it will create a PR for you.
See https://developer.trustwallet.com/assets/repository_details

**Comment by Cryptopolisgame** [comment]
@cryptomanz1 Hi there, can you please check this issue?

**Comment by Cryptocool1** [comment]
• What is the purpose of this token? How will it benefit Trust Wallet users?
 • How is the token being distributed? Are you conducting an airdrop?
 • Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?
 • Is the token listed on a centralized/decentralized exchange?
 • Is a Smart Contract audit completed? Where can we find this information?

**Comment by Cryptopolisgame** [comment]
> • What is the purpose of this token? How will it benefit Trust Wallet users?
Cryptopolis is an NFT-based p2e game. In which players can socialize and play minigames against each other. The entire game is NFT-based, where the token is used as currency. Trust Wallet users benefit from spending time in our game and enjoying the moment.

> • How is the token being distributed? Are you conducting an airdrop?
We held a normal seed and private sale. Investors can claim their token from the contract or from the launchpad (GameZone)

> • Did you sell the tokens at an Initial Coin Offering (ICO) or a token presale?
Yes, seed, private to VCs and investors, and the public sale at GameZone launchpad.

> • Is the token listed on a centralized/decentralized exchange?
For now, only on PancakeSwap

> • Is a Smart Contract audit completed? Where can we find this information?
Our contract was controlled by BlueZilla, but the information isn't public.

**Comment by Cryptocool1** [comment]
> > • What is the purpose of this token? How will it benefit Trust Wallet users?
> > Cryptopolis is an NFT-based p2e game. In which players can socialize and play minigames against each other. The entire game is NFT-based, where the token is used as currency. Trust Wallet users benefit from spending time in our game and enjoying the moment.
> 
> > • How is the token being distributed? Are you conducting an airdrop?
> > We held a normal seed and private sale. Investors can claim their token from the contract or from the launchpad (GameZone)
> 
> > • Did you sell the tokens at an Initial Coin Offering (ICO) or a token presale?
> > Yes, seed, private to VCs and investors, and the public sale at GameZone launchpad.
> 
> > • Is the token listed on a centralized/decentralized exchange?
> > For now, only on PancakeSwap
> 
> > • Is a Smart Contract audit completed? Where can we find this information?
> > Our contract was controlled by BlueZilla, but the information isn't public.

Hello, we require smart contract audit from reputable companies. (Certik, Hacken, Dessert Finance, Techrate) https://developer.trustwallet.com/assets/requirements

**Comment by Cryptocool1** [comment]
Please come back to us when all criteria are met. Make sure to mention this PR so the fee can be reused

**Comment by Cryptopolisgame** [comment]
Dear Nazar, Just a moment after you closed our pull request we made the
payment. Can you please look into it to change our PF.

Thanks in advance!

https://bscscan.com/tx/0x9dd862f5c62dd67df9479ae58b4deb0ed775a04e5132f10879d85fb07430dcc7

Op di 19 jul. 2022 om 10:01 schreef Nazar ***@***.***>:

**Comment by Cryptocool1** [comment]
Is a Smart Contract audit completed? Where can we find this information?

**Comment by Cryptopolisgame** [comment]
Hi guys, Thanks for asking. We contacted the audit and said it would cost
around $8,000. Is it possible we can continue the process later?

Op di 11 okt. 2022 om 09:04 schreef CryptoA ***@***.***>:

**Comment by Cryptocool1** [comment]
Hello, we require smart contract audit. 
see requirements here: https://developer.trustwallet.com/assets/requirements

**Comment by Cryptopolisgame** [comment]
Hee! We are aware of that. Can we continue the process with you later?
Maybe in one or two month? We are waiting for some important things before
we can start the audit.

Op di 25 okt. 2022 om 10:12 schreef CryptoA ***@***.***>:

**Pull request closed without merging**
