### PR TITLE
Pulsepad Logo and Token info update

### PR DESCRIPTION
**Pull request by divinechoice**
Pulsepad Logo and Token info update

### CODE REVIEW

**Comment by Cryptocool1** [comment]
• What is the purpose of this token? How will it benefit Trust Wallet users?
 • How is the token being distributed? Are you conducting an airdrop?
 • Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?
 • Is the token listed on a centralized/decentralized exchange?
 • Is a Smart Contract audit completed? Where can we find this information?

**Comment by divinechoice** [comment]
> • What is the purpose of this token? How will it benefit Trust Wallet users? • How is the token being distributed? Are you conducting an airdrop? • Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale? • Is the token listed on a centralized/decentralized exchange? • Is a Smart Contract audit completed? Where can we find this information?

Hello,

1. Its a launchpad token and participant who stake the tokens will get to participate in IDOs.
2. Lot of out holders/stakers use trustwallet and would love to see the same added to trust wallet.
3&4. its not a airdrop. We had our IDO presale on our other launch pads.
5. Yes its listed on pancakeswap, uniswap & Wagyuswap.
6. No, we have multiple launchpads already listed and also token logos are updated on trustwallet. The project is incubated by BlueZilla https://bluezilla.vc/

**Comment by Cryptocool1** [comment]
• Is a Smart Contract audit completed? Where can we find this information?

**Comment by divinechoice** [comment]
> • Is a Smart Contract audit completed? Where can we find this information?
 
No, we have multiple launchpads already listed and also token logos are updated on trustwallet for other projects as well. The project is incubated by BlueZilla https://bluezilla.vc/

**Pull request merged**
