### PR TITLE
Add CRU

### PR DESCRIPTION
**Pull request by badkk**
https://www.huobi.pr/en-us/exchange/cru_usdt/

### CODE REVIEW

**Comment by catenocrypt** [comment]
Thank you for the submission.  It looks OK, though we the circulation of the CRUST token is still below under limit -- 2145 holder addresses vs. 2500.  I suggest to wait some time until reaching the limit.

**Comment by zikunfan** [comment]
> Thank you for the submission. It looks OK, though we the circulation of the CRUST token is still below under limit -- 2145 holder addresses vs. 2500. I suggest to wait some time until reaching the limit.

So this pr is keep open util reached 2,500 holders?

**Comment by catenocrypt** [comment]
> So this pr is keep open util reached 2,500 holders?

Correct.

**Comment by zikunfan** [comment]
> > So this pr is keep open util reached 2,500 holders?
> 
> 
> 
> Correct.

Hey, we already reach the limit now😄, could you please check it?

**Comment by catenocrypt** [comment]
Great!  Rechecked, merging.

**Pull request merged**
