### PR TITLE
Add ENERGY POLY COIN (POLYGON)

### PR DESCRIPTION
**Pull request by yenky**
Adding info for POLYGON token 'ENERGY POLY COIN'.

PR created by <a href="https://assets.trustwallet.com">TW Assets Management</a>

### CODE REVIEW

**Comment by yenky** [comment]
Thank you @Cryptocool1  for your Quick response. I really appreciate it.

What is the purpose of this token? How will it benefit Trust Wallet users?
Answer : ENERGY POLY COIN  is a cryptocurrency belonging to the Energy Web Foundation (ENG). The Energy Web Foundation is an organization dedicated to building open-source operating systems for energy grids that can help in powering a zero-carbon economy the convenience, cost effective solution and efficient time usage among the peer to peer community. ENERGY POLY COIN is also A UTILITY TOKEN, enables People to make their utility bill payments using the pay app. 
	
Further, the Energy Web Foundation website states that to expedite this energy transition process for decarbonization, EWF focuses on leveraging blockchain and other digital technology. This process has allowed the organization to develop the Energy Web Decentralized Operating System (EW-DOS), open-source software that includes its Energy Web Chain.

How is the token being distributed? Are you conducting an airdrop?
Answer : 5 months before when team was working on ENERGY POLY COIN idea we decided to distribute in this manner.
30% Pre Sales ,
25% Stacking ,
20% Community ,
8%  CEX Listing,
8%  Rewards,
5%  Marketing,
4%  Api Development.

Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?
Answer : Yes we did in our initial stage and we have all records here :
https://polygonscan.com/token/0x8f9ca9ab9b0937a2565c4c92e0a99b6f73491a19
As you can check we are having good volume of transactions . Our Pre-sale had an offer with Utility & Reward System.

Is the token listed on a centralized/decentralized exchange?
Answer : We are not listed on centralized/decentralized exchanges yet, but we have a good volume of users , who are waiting to see this on trust wallet and then we are going to get live with centralized/decentralized exchanges.

Is a Smart Contract audit completed? Where can we find this information?
Answer : Yes

[ENG.POLY.COIN,Audit.Report.Smart.Contract.pdf](https://github.com/trustwallet/assets/files/10152765/ENG.POLY.COIN.Audit.Report.Smart.Contract.pdf)

Thank you

**Comment by yenky** [comment]
Hi @cryptomanz1 , @Cryptocool1  
Energy team is waiting to start their all projects and all the users are waiting to see the logo in trust wallet. 

Thank you

**Comment by yenky** [comment]
Hi  @Cryptocool1 
Sorry to bother you in busy schedule but Energy team is waiting to get the Logo done on trust wallet so they can start the project with all marketing plans.

Thank you

**Comment by Cryptocool1** [comment]
Hello, I don’t see the activity on this token. All massive transactions was 2 months ago

**Comment by yenky** [comment]
Hi @Cryptocool1 
They were working on their plans and now they are waiting to get it done on trust wallet. Energy Poly wants to prepare all the things in advance to get into market.

Thank you

**Comment by Cryptocool1** [comment]
Are you listed on CMC?

**Comment by yenky** [comment]
Hi @Cryptocool1 
This is not listed on CMC. Energy Poly token  doing all the work in advance before to start the marketing. ENG BSC is available on CMC and ENG POLY we will list after getting logo done from trust wallet. 
As trust wallet plays a important role for every token because users trust on trust wallet and its a secure and top wallet in all other wallet lists.
ENGY Poly has good amount of transactions and holders and once it get done with trust wallet we are moving to CMC and other higher level of exchanges .

Thank you

**Comment by Cryptocool1** [comment]
Hello, we require CMC listing, on hold for now

**Comment by Cryptocool1** [comment]
Please come back to us once criteria is met. 
make sure to mention this PR so the fee can be reused.

**Pull request closed without merging**
