### PR TITLE
Add BIGH BULL (BEP20)

### PR DESCRIPTION
**Pull request by BighBullTech**
Adding info for BEP20 token 'BIGH BULL'.

PR created by <a href="https://assets.trustwallet.com">TW Assets Management</a>

### CODE REVIEW

**Comment by BighBullTech** [comment]
Will be replace with old contract 0x64B55Bb2F27c3710349d9cA024d0D1Ff2DAB7f62

**Comment by BighBullTech** [comment]
Ok After payment my contract will be replace from old contract address as we mentioned.

**Comment by BighBullTech** [comment]
Ok After payment my contract will be replace from old contract address as
we mentioned.

**Comment by BighBullTech** [comment]
Hello Old Contract will be replaced with New Contract & New Logo?

**Comment by BighBullTech** [comment]
Pls Rename, Old Contract Token's Name as "Old Bigh Bull"

**Comment by Cryptocool1** [comment]
hello
what the new contract is?
what the old contract is?
can you send me official announcement about migration?

**Comment by BighBullTech** [comment]
New Contract - 0x0bCF5693655A159bd7D9DC5064de9BD692a7b7C6

Old Contract - 0x64B55Bb2F27c3710349d9cA024d0D1Ff2DAB7f62

Declared on website with all social plateform, you can cross check anywhere https://bighbull.com.
Also we transferred maximum token to holders 

If comfortable pls replace old token name "Old Bigh Bull".

**Comment by BighBullTech** [comment]
Anything else...?

**Comment by BighBullTech** [comment]
Hi R u there

**Comment by BighBullTech** [comment]
Why Display both logo.
How normal user can differentiate 

We want only new one & not also name change as we requested

**Comment by BighBullTech** [comment]
IMG_20220306_070929
See this

**Comment by Cryptocool1** [comment]
D4B31D25-BBF7-408D-ADD2-6FDC75C8B4A3
Your old logo is not visible in Trust Wallet. It is abandoned.

**Comment by BighBullTech** [comment]
0x64B55Bb2F27c3710349d9cA024d0D1Ff2DAB7f62 (old contact)

You can see now. I am seeing..
It's visible & also we want to name change for old contract as "OLD BIGH BULL" 

But not done from your side.

**Comment by BighBullTech** [comment]
If you will find from contract address, old logo also visible..

**Comment by BighBullTech** [comment]
IMG_20220306_072008

Visible if anyone find from old contract address too.. 🤔

**Comment by Cryptocool1** [comment]
We don’t rename old tokens, we only remove them

**Comment by BighBullTech** [comment]
So pls remove

**Comment by Cryptocool1** [comment]
your old token has been removed. you should clear your cache.

**Comment by BighBullTech** [comment]
You can find from old contract address, logo will display, i attached screenshot. 

IMG_20220306_072008

**Comment by BighBullTech** [comment]
Once you can search from old contract.
You will find logo

**Comment by Cryptocool1** [comment]
once again,  it is the problem from your side. clear the cache.

**Comment by Cryptocool1** [comment]
the the screenshot from my wallet

**Comment by BighBullTech** [comment]
Ok so if you are searching from old contract, there is no logo 
Correct pls reply
& 
How i can clear cache
Pls suggest..

Reply must for both query

**Comment by BighBullTech** [comment]
I had clear cache, still I search from old contract address logo displaying. 
What's going on.

Once you can cross check from old contract address.. 
I am sure definitely you will visible old logo.

**Comment by BighBullTech** [comment]
IMG_20220306_075341
 

See this screenshot.. 
Issues not resolved.
If any user find from contract address, there is old logo available, How 🤔

**Comment by Cryptocool1** [comment]
that is the problem on your side. 
we did the migration and the logo has been deleted. in my wallet I cannot see your old contract.
https://github.com/trustwallet/assets/pull/1873
Снимок экрана 2022-03-06 в 10 27 24
5

**Comment by cryptomanz** [comment]
photo_2022-03-06 10 33 42
only new contract logo is visible

**Comment by BighBullTech** [comment]
I am only saying that, if you @Cryptocool1 @cryptomanz will find in trust wallet through old smart contract, our old logo will display. Even clear cache.

So my concern only that, if you remove logo from old contract, how it is displaying

**Comment by BighBullTech** [comment]
IMG_20220306_075341

See if I find through contract address at trust wallet

**Comment by BighBullTech** [comment]
I have 1 query also, if you are saying that you don't rename old token. So how some token available in trust wallet with old name.

Find as attachment. 
IMG_20220306_081747

**Comment by BighBullTech** [comment]
I know @cryptomanz that, if i search from token name there is only new contract's logo. 
It's fine & thanks for your valuable support. 

But if i can search from old contract address, there is also display logo. How & Why.

**Comment by BighBullTech** [comment]
Can you @Cryptocool1 @cryptomanz send me screenshot of trust wallet, when you search from old contract address

**Comment by BighBullTech** [comment]
I have 1 query also, if you are saying that you don't rename old token. So
how some token available in trust wallet with old name.

Find as attachment.

**Comment by BighBullTech** [comment]
Can you @Cryptocool1 <https://github.com/Cryptocool1> @cryptomanz
<https://github.com/cryptomanz> send me screenshot of trust wallet, when
you search from old contract address, because at my search I have result
with display old logo in old contract at trust wallet.

**Comment by BighBullTech** [comment]
Hi r u there

**Comment by BighBullTech** [comment]
Why you are not sending me screenshot of trust wallet as a search from contract address, there is logo visible.. 
What you want clear me, my purpose not resolved, after payment as well as after clear cache also, there is available old logo on every old token holders, there is chance to transfer old token by mistake, because logo not remove till. 

Also if new any user can search with old contract address there is visible old logo too. 
Pls remove fast or rename old token with Old Bigh Bull for security reasons.

Do it pls & at least reply

**Comment by BighBullTech** [comment]
Why you https://github.com/cryptomanz & https://github.com/Cryptocool1 are
not sending me screenshot of trust wallet as a search from contract
address, there is logo visible..
What you want clear me, my purpose not resolved, after payment as well as
after clear cache also, there is available old logo on every old token
holders, there is chance to transfer old token by mistake, because logo not
remove till.

Also if new any user can search with old contract address there is visible
old logo too.
Pls remove fast or rename old token with Old Bigh Bull for security reasons.

Do it pls & at least reply

**Comment by Cryptocool1** [comment]
your token is abandoned and when users will search for your token they will find only your new contract. your old logo deleted.

**Comment by BighBullTech** [comment]
How can you say deleted, if all existing users wallet shows old logo. and as new user if search from old contract address in trust wallet there is also visible logo. 

I am asking from your side, you will give me screenshot in trust wallet search from old contract address 0x64b55bb2f27c3710349d9ca024d0d1ff2dab7f62 

You will also find our logo, if your trust wallet don't have old logo in search 
Pls send me screenshot..

Why you are not sending me

**Comment by BighBullTech** [comment]
Screenshot_2022-03-06-11-21-24-62_08800057d42e3b72e31ae4fd4c41ba57

See it's old logo visible with old contract search 
In trust wallet. 

How can I trust your word. 
Why you can't send screenshot as a proof.

Otherwise do it earliest or rename token as Old Bigh Bull

**Comment by BighBullTech** [comment]
Delete old logo from old contract 0x64B55Bb2F27c3710349d9cA024d0D1Ff2DAB7f62 from immediate basis or replace with this logo for differentiate on both contract 
Otherwise user will be transfer old token to any other, it is another big problem will raise.
so pls delete old logo or replace with attached logo from old contract

Old Logo

**Comment by BighBullTech** [comment]
I have new PR for Replace Old Logo for old contract, 
So pls Accept this PR & Do it... 
https://github.com/trustwallet/assets/pull/18742 


Regards

**Comment by BighBullTech** [comment]
I have new PR for Replace Old Logo for old contract, because here is old
logo available with old contract & you are not send any proof of deletion
of old logo as we required, so many time i have cross check with old
contract address in search bar of trust wallet, so here is very much
confusion between both contract. So pls Replace old contract logo from this
PR
So pls Accept this PR & Do it...
#18742 <https://github.com/trustwallet/assets/pull/18742>

Regards

**Comment by BighBullTech** [comment]
Any Updates 🤔

**Comment by BighBullTech** [comment]
Can you clear me How much time for delete old logo or replace old logo. 
If you are saying old logo delete already, I want to any proof.
Otherwise you want to another Payment for doing this, clear me.

I am very much disappointed from your service after paying fees. 
Still me & my users having faces new issue to identify which is actual logo.
But from your side no reply on time & no solution on time.
Just you are saying old logo deleted, but we have visible both logo in every old user's wallet, after cleared cache also.

And if user search from old contract address, there is also visible old logo.

What I can do in such situation, pls suggest & giving me best & final solution.

**Comment by BighBullTech** [comment]
Can you https://github.com/cryptomanz https://github.com/Cryptocool1 clear
me How much time for delete old logo or replace old logo.
If you are saying old logo delete already, I want to any proof.
Otherwise you want to another Payment for doing this, clear me.

I am very much disappointed from your service after paying fees.
Still me & my users having faces new issue to identify which is actual logo.
But from your side no reply on time & no solution on time.
Just you are saying old logo deleted, but we have visible both logo in
every old user's wallet, after cleared cache also.

And if user search from old contract address, there is also visible old
logo.

What I can do in such situation, pls suggest & giving me best & final
solution.

**Pull request merged**
