### PR TITLE
Add GVC logo

### PR DESCRIPTION
**Pull request by sumner770**

### CODE REVIEW

**Comment by sumner770** [comment]
Hi, Let me know if i provided all details needed and this can be merged. Will make payment upon confirmation

**Comment by Cryptocool1** [comment]
As per our policy, brand new tokens are not included, there is a minimum requirement of 10,000 holder addresses and 15,000 transactions, in order to filter out scam tokens.
See the criteria at : https://developer.trustwallet.com/assets/requirements .

**Comment by sumner770** [comment]
> As per our policy, brand new tokens are not included, there is a minimum requirement of 10,000 holder addresses and 15,000 transactions, in order to filter out scam tokens. See the criteria at : https://developer.trustwallet.com/assets/requirements .

Thanks for the update. This is a token under GHC echo system which has more than 10k holders. Not sure when we hit the 10k in this bare market. When can we hit back? Any help is appreciated.

**Comment by Cryptocool1** [comment]
Feel free to create new PR when you reach more holders. Make sure to have smart contract audit from reputable companies (Certik, Techrate, Hacken, Dessert Finance) 
You don’t need to pay the fee one more time, we will reuse fee from this PR.

**Comment by sumner770** [comment]
@Cryptocool1 Can you please reopen this? Request you to consider it now.

**Comment by sumner770** [comment]
@Cryptocool1 Raised a new request, https://github.com/trustwallet/assets/pull/23761. Please have the fees paid here applied to the new one.

**Pull request merged**
