### PR TITLE
Add Flycoin (POLYGON)

### PR DESCRIPTION
**Pull request by natedaiger**
Adding info for POLYGON token 'Flycoin'.

PR created by <a href="https://assets.trustwallet.com">TW Assets Management</a>

### CODE REVIEW

**Comment by lukesterc** [comment]
Can this ticket be reopened?  We want to submit our 700 TWT and finish this transaction!!

**Comment by lukesterc** [comment]
Sent 700 TWT with comment 22045

**Comment by lukesterc** [comment]
We sent 700 TWT with comment 22045 already.

**Comment by cryptomanz1** [comment]
• What is the purpose of this token? How will it benefit Trust Wallet users?
 • How is the token being distributed? Are you conducting an airdrop?
 • Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?
 • Is the token listed on a centralized/decentralized exchange?
 • Is a Smart Contract audit completed? Where can we find this information?

**Comment by natedaiger** [comment]
- We are the first cryptocurrency that is _actually_ distributed by an airline as a frequent flier mile on https://ravnalaska.com and soon https://np.com
- FLY is currently only distributed to airline passengers on Ravn Alaska
- Did did not do an ICO and have a legal opinion letter from an outside law firm stating that they believe it is a utility token.
- We are listed on Uniswap: https://info.uniswap.org/#/polygon/pools/0x27b63daaa4d48e06c8401e441d568d6ba16d9b63
- Our contract is a bog-standard ERC-20 contract, we are not trying to do anything intersting with the crypto itself; just the use-case.

**Comment by cryptomanz1** [comment]
Screenshot 2022-09-03 at 12 57 17
Here is the example of smart contract audit: https://www.certik.org/projects/binance

**Comment by Cryptocool1** [comment]
feel free to open new PR once all the requirements are met. Make sure to mention this PR so the fee can be reused.

**Comment by natedaiger** [comment]
Hey @cryptomanz1 do you have a list of auditors you accept. We talked to Certik a few months ago and their pricing was not acceptable.

**Comment by Cryptocool1** [comment]
> Hey @cryptomanz1 do you have a list of auditors you accept. We talked to Certik a few months ago and their pricing was not acceptable.

Hello, ( Certik, Techrate, Dessert Finance)

**Comment by lukesterc** [comment]
Can you please reopen this pull request so we can append the audit results?

**Comment by natedaiger** [comment]
[FlyCoin.pdf](https://github.com/trustwallet/assets/files/9954622/FlyCoin.pdf)

We used Techrate.

**Comment by natedaiger** [comment]
Any update? @Cryptocool1 @cryptomanz1

**Comment by natedaiger** [comment]
Bumping again /cc @Cryptocool1 @cryptomanz1

**Comment by Cryptocool1** [comment]
Could you send me audit here?

**Comment by natedaiger** [comment]
> Could you send me audit here?

Linked in comment above, here it is again: 

https://github.com/trustwallet/assets/files/9954622/FlyCoin.pdf

**Comment by natedaiger** [comment]
Again, link to audit:

https://github.com/trustwallet/assets/files/9954622/FlyCoin.pdf

/cc @Cryptocool1 @cryptomanz1

**Pull request merged**
