### PR TITLE
NEW DECASH LOGO

### PR DESCRIPTION
**Pull request by vitalismark**

### CODE REVIEW

**Comment by vitalismark** [comment]
PAYMENT HAS BEEN MADE

**Comment by catenocrypt** [comment]
@vitalismark , why is  `0x95bA34760ac3D7fBE98ee8b2AB33b4F1a6D18878/logo.png` removed?  Please justify.

**Comment by vitalismark** [comment]
the owner of the token when the logo changed from the former logo to this new logo

**Comment by vitalismark** [comment]
I really don't understand what you mean by "removed"

**Comment by catenocrypt** [comment]
Sorry, my mistake.  It was not removed, only updated.  I got confused by the red marking and minus size, the size got smaller.  I just wanted to make sure that no logo is deleted by mistake.

image

**Pull request merged**
