### PR TITLE
Please add SANTA on TrustWallet

### PR DESCRIPTION
**Pull request by soliditycdr**
Token Name: Santa Token
Symbol: SANTA
Decimals: 18
Total Supply: 93,000,000 SANTA
Contract Address: 0x8c168Ef06b8BAf8Ad2236eEf2286f7870ad50F9B
Holders: 400+ addresses and counting
Transfers: 500+ transactions and counting

### CODE REVIEW

**Comment by Iamdeadlyz** [comment]
Please provide more details about this project.
https://community.trustwallet.com/t/how-to-submit-a-token-logo/3863#how-to-get-approved
You can follow this format when adding an info.json file:
```
{
    "name": "Trust Wallet Token",
    "website": "https://trustwallet.com",
    "source_code": "https://github.com/trustwallet/",
    "short_description": "Utility token to increase adoption of cryptocurrency.",
    "description": "Utility token to increase adoption of cryptocurrency.",
    "socials": [
        {
            "name": "Twitter",
            "url": "https://twitter.com/trustwalletapp",
            "handle": "TrustWalletApp"
        },
        {
            "name": "Reddit",
            "url": "https://reddit.com/r/trustapp",
            "handle": "TrustApp"
        }
    ],
    "explorer": "https://bscscan.com/token/0x4b0f1812e5df2a09796481ff14017e6005508003"
} 
```

**Comment by SantaTokenCom** [comment]
Hello, based on your format we added an info.json file.  Thank you for your help with this.  Let me know if this works:

https://github.com/SantaTokenCom/SANTA/blob/main/info.json

**Comment by catenocrypt** [comment]
Info.json file is not in the PR, it contains only one file.  Please add it.

image

**Comment by soliditycdr** [comment]
Dear @Iamdeadlyz >> Please check and help us to update info. Here is the json file followed by given guidance: https://github.com/trustwallet/assets/pull/5260/files#diff-77255de6a0ba76d558312f437888318ce7fb64b687d241d38ac949462e8e62cd
image

**Comment by catenocrypt** [comment]
Sorry to mention, but we have a minimum requirement of 2500 holder addresses and 5000 transactions, in order to filter out scam tokens.  See the criteria at (mentioned in the first message by the bot): https://community.trustwallet.com/t/how-to-submit-a-token-logo/3863).
This token has below-limit usage yet (401). I am putting this PR on hold for now. Please come back to us when all criteria are met.

https://etherscan.io/token/0x8c168Ef06b8BAf8Ad2236eEf2286f7870ad50F9B

**Comment by vikmeup** [comment]
@soliditycdr closing this PR, feel free to update when ready.

**Pull request closed without merging**
