### PR TITLE
Add PolkaCover Token(CVR) Logo and Info

### PR DESCRIPTION
**Pull request by coderasha**
Please add PolkaCover Token(CVR) Logo and Info

### CODE REVIEW

**Comment by coderasha** [comment]
Hi TrustWallet Team,
In the "Create Pull request" screen i checked the changes and the logo wasn't showing up as it is binary. 
Can you guys confirm that the logo and Info will be updated properly once the payment is done.
Just want to check if we have done everything right so that there is no issue after we make payment.
CVRLogo

**Comment by coderasha** [comment]
awaiting confirmation in order to proceed for payment

**Comment by coderasha** [comment]
awaiting confirmation in order to proceed for payment

**Comment by vikmeup** [comment]
> Hi TrustWallet Team,
> In the "Create Pull request" screen i checked the changes and the logo wasn't showing up as it is binary.
> Can you guys confirm that the logo and Info will be updated properly once the payment is done.
> Just want to check if we have done everything right so that there is no issue after we make payment.
> CVRLogo

I suggest that you use full width logo, otherwise it would look small.

Screen Shot 2021-02-01 at 10 29 06 PM

**Pull request merged**
