### PR TITLE
Add TRUSTxGAMING (BEP20)

### PR DESCRIPTION
**Pull request by TRUSTxGAMING**
Adding info for BEP20 token 'TRUSTxGAMING'.

PR created by <a href="https://assets.trustwallet.com">TW Assets Management</a>

### CODE REVIEW

**Comment by Cryptocool1** [comment]
• What is the purpose of this token? How will it benefit Trust Wallet users?
 • How is the token being distributed? Are you conducting an airdrop?
 • Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?
 • Is the token listed on a centralized/decentralized exchange?
 • Is a Smart Contract audit completed? Where can we find this information?

**Comment by TRUSTxGAMING** [comment]
1. What is the purpose of this token?
Ans: TXG token is a utility token which can be use to play on TrustxGaming Play to earn gaming platform.

2. How will it benefit Trust Wallet users?
Ans: TXG is easily accessible through Trust Wallet and it can help into more crypto adoption, hence more user growth on Trust Wallet.

3. How is the token being distributed? Are you conducting an airdrop?
Ans: TXG/BUSD pair is available on pancake swap. Tokens are being swapped from pancakeswap. There is no airdrop distribution.

4. Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?
Ans: No

5. Is the token listed on a centralized/decentralized exchange?
Ans: Yes the token is listed on Decentralized exchange (pancake swap)
https://pancakeswap.finance/swap?inputCurrency=0x9f46EcF92E7F6eE8C03f393ADf04C2e17B8cD0B0&outputCurrency=0xe9e7CEA3DedcA5984780Bafc599bD69ADd087D56

6.Is a Smart Contract audit completed? Where can we find this information?
Ans:The Smart Contract audit is in the process. We are doing it with Techrate. We will get the audit report by 15July.

**Comment by TRUSTxGAMING** [comment]
Here is the audit report by Techrate
https://github.com/TechRate/Smart-Contract-Audits/blob/main/July_2023/TRUSTxGAMING.pdf

**Comment by TRUSTxGAMING** [comment]
Please tell us when we can see the token logo in Trust Wallet?

**Comment by TRUSTxGAMING** [comment]
@Cryptocool1 @cryptomanz1 Please give us any update

**Comment by Cryptocool1** [comment]
Hello, thank you for audit. 
Are you listed on CoinMarketCap?

**Comment by TRUSTxGAMING** [comment]
Yes we are listed on coinmarketcap: https://coinmarketcap.com/dexscan/bsc/0xcfd701dfa42d72b73af972cb7f387fa0fd2477cb/

**Comment by Cryptocool1** [comment]
I don’t see your token is listed.

**Comment by TRUSTxGAMING** [comment]
The token information is available on Coinmarketcap via dexscan. Please check again with the link: https://coinmarketcap.com/dexscan/bsc/0xcfd701dfa42d72b73af972cb7f387fa0fd2477cb/

We have already started coinmarketcap verification also.

**Comment by Cryptocool1** [comment]
We require CoinMarketCap listing. Feel free to create new PR once you’re listed there. Make sure to mention this Pull Request so the fee can be reused

**Comment by TRUSTxGAMING** [comment]
> @cryptomanz1
Please check we are now listed on Coinmarketcap:
https://coinmarketcap.com/currencies/trustxgaming/

https://github.com/trustwallet/assets/pull/25830#issuecomment-1643987288

**Pull request closed without merging**
