### PR TITLE
Add LFG Token

### PR DESCRIPTION
**Pull request by 0xllaCh**

### CODE REVIEW

**Comment by zhChameleon** [comment]
https://explorer.binance.org/tx/9015624AFD45DFA458A575447CCBE4FE660BD4011474113D839CD4C216A42BC5

**Comment by ramsty** [comment]
Hi!
Could you answer some questions?
• What is the purpose of this token? How will it benefit Trust Wallet users?
• How is the token being distributed? Are you conducting an airdrop?
• Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?
• Is the token listed on a centralized/decentralized exchange?
• Is a Smart Contract audit completed? Where can we find this information?

**Comment by Cryptocool1** [comment]
Please come back to us when the answers will be ready.
When creating a new PR make sure to mention this PR, so that we can see that fee has been paid already here.

**Comment by zhChameleon** [comment]
@Cryptocool1 
We're preparing the answers of your questions. Please make this PR opened.

**Comment by zhChameleon** [comment]
• What is the purpose of this token? How will it benefit Trust Wallet users?
This token is the token of Gaming project called GAMERSE. And it will make users use Trust Wallet for storing tokens in the safe wallet.
GAMΞRSΞ is the new home for NFT gaming and the metaverse social economy. Our cross-chain, cross-domain, and cross-verse solutions are unifying the fragmented NFT gaming ecosystem. 

GAMΞRSΞ is creating the first-ever NFT Gaming Social Ecosystem allowing gamers to explore popular NFT games aggregated and brought together in a single social marketplace.

GAMΞRSΞ is the LFG (“Looking For Group”) platform for the entire NFT gaming industry, and we will be around for gamers of all shades and hues, no matter which title holds the #1 spot. As a social platform, GAMΞRSΞ unites gamers in a single, fun community, constantly adapting to the newest and most viral trends.

• How is the token being distributed? Are you conducting an airdrop?
Token was already distributed by Presale and Airdrop also.
• Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?
Yes, token is sold by LaunchPad and after it, we airdroped the tokens to whitelisted users.
• Is the token listed on a centralized/decentralized exchange?
It's listed on Pancakeswap.
• Is a Smart Contract audit completed? Where can we find this information?
Yes auditing is completed and you can check it here - https://docsend.com/view/7r474uacwfhx7u2f

**Comment by zhChameleon** [comment]
New PR is made - https://github.com/trustwallet/assets/pull/15326

**Comment by zhChameleon** [comment]
@Cryptocool1 @ramsty @zachzwei @cryptomanz 
Can you please make this PR opened?

**Pull request closed without merging**
