### PR TITLE
Trust wallet Logo Update

### PR DESCRIPTION
**Pull request by UBITLOGO**

### CODE REVIEW

**Comment by UBITLOGO** [comment]
Payment hash id
https://bscscan.com/tx/0x80591ffd48f9cd63a4d19fc96d50f30f1fa5e7f3d7ed967ea984f2daaf3d1541

**Comment by UBITLOGO** [comment]
logo png

**Comment by UBITLOGO** [comment]
> No token files found. If you try to add/modify a token, check the name and location of your files! Logo file must be named exactly 'logo.png'. If you are not adding a token, ignore this message.

Please chek logo update

**Comment by Cryptocool1** [comment]
At the moment we do not merge new blockchainswithout a positive decision from our Business Development team.
Please create a new ticket, a request to add the blockchain to Trust Wallet:
https://support.trustwallet.com/en/support/tickets/new

**Comment by UBITLOGO** [comment]
What is the process to add blockchain

**Comment by UBITLOGO** [comment]
What is the process to add blockchain

**Pull request closed without merging**
