### PR TITLE
Add Rabi (BEP20)

### PR DESCRIPTION
**Pull request by Rabi-foundation**
Adding info for BEP20 token 'Rabi'.

PR created by <a href="https://assets.trustwallet.com">TW Assets Management</a>

### CODE REVIEW

**Comment by Cryptocool1** [comment]
• What is the purpose of this token? How will it benefit Trust Wallet users?
 • How is the token being distributed? Are you conducting an airdrop?
 • Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?
 • Is the token listed on a centralized/decentralized exchange?
 • Is a Smart Contract audit completed? Where can we find this information?

**Comment by Rabi-foundation** [comment]
> • What is the purpose of this token? How will it benefit Trust Wallet users?
> 
>  • How is the token being distributed? Are you conducting an airdrop?
> 
>  • Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?
> 
>  • Is the token listed on a centralized/decentralized exchange?
> 
>  • Is a Smart Contract audit completed? Where can we find this information?

---
💎
Hello,
Thanks to the Trustwallet team for the response.
* What is the purpose of this token? How will it benefit Trust Wallet users?
Token Robi wants to revolutionize the world of digital currency in the future with a new structure and new programs. In Robi programs, there is a part like agreement, and this token is supposed to be a method of payment. So we need to be able to introduce a secure wallet to keep our assets. There are other programs that increase our holders a lot.
• How is the token generated? Are you doing an airdrop?
At first, 3 main funds are divided and the main part is in the manufacturer's wallet for future plans.
The airdrop is done and over. It is mentioned in the link below.
Links : https://rabi.foundation/event/
• Did you sell tokens in an initial coin offering (ICO) or token presale?
No, Robi Token has not done any ICO and has 3 private investments.
• Is it listed on a service/decentralized exchange?
Yes, it is listed in Bitmart and Mexc exchange, its links are posted below.
Links : https://www.bitmart.com/trade/en-US?symbol=RABI_USDT
Links : https://www.mexc.com/it-IT/exchange/RABI_USDT?_from=search
• Has the smart contract audit been completed? Where can I find this information?
Auditing is still done after your BSCscan collection and then the audit. The codes are without problems and approved by BSCscan.

**Comment by Cryptocool1** [comment]
Hello, we require full smart contract audit from reputable companies (such as Techrate, Certik, Hacken, Dessert Finance)
Feel free to create new PR once audit is done. 
make sure to mention new PR in this one so the fee can be reused.

**Comment by Jstacy121** [comment]
To make a lot of money

Stacy L Johnson
Sent with Spark

**Comment by Rabi-foundation** [comment]
> Hello, we require full smart contract audit from reputable companies (such as Techrate, Certik, Hacken, Dessert Finance) Feel free to create new PR once audit is done. make sure to mention new PR in this one so the fee can be reused.

Dear Trust Wallet Support Team,
@Cryptocool1 
@Cryptomanz1
I hope this email finds you well. In response to your request, we have completed all the tasks. Please review them and inform us of the outcome.

https://dessertswap.finance/audits/RABI-BSC-Audit-38202023.pdf

Thank you for your time and consideration.

Best regards,
Rabi Team

**Comment by Rabi-foundation** [comment]
Dear Trust Wallet Support Team,

I trust this email finds you well. I am writing to follow up on our recent communication to ensure that my previous email was received.

Thank you for your attention to this matter.

Best regards,
Rabi support team.

**Comment by Rabi-foundation** [comment]
@Cryptocool1
@cryptomanz1

**Comment by Cryptocool1** [comment]
Hello, there is no need to pay the fee again. We will check your submission soon

**Comment by Rabi-foundation** [comment]
@Cryptocool1 
@cryptomanz1 


**Subject: Issue with displaying the price of RABI token in Trust Wallet**

Hello,  
I previously submitted a request to register the logo and name of the RABI token, which was successfully displayed in Trust Wallet. However, I have noticed that the token price is not showing in the wallet. Since the RABI token is now active and available to users, I would appreciate your guidance on what steps need to be taken to have the price displayed.

If additional information is needed, such as listing the token on reputable exchanges or syncing with price oracles, I would be happy to provide it.

Thank you in advance for your cooperation and support.

Best regards,  
[RABI Team]

**Pull request merged**
