### PR TITLE
Adding the new GOMA Token and Logo (BEP20)

### PR DESCRIPTION
**Pull request by GOMAFinance**

### CODE REVIEW

**Comment by GOMAFinance** [comment]
The ❌ tag 'DeFi' is not allowed is not longer in the file please advise

**Comment by Athayde3586** [comment]
Trust wallet was compromised by a person that claimed to be part of trust
wallet so please till situation is fixed please don't send treat ning
messages

**Comment by Athayde3586** [comment]
And I know y'all r doing this to stop my money please refrain from any
messages

**Comment by Cryptocool1** [comment]
tag should be "defi"

**Pull request closed without merging**
