### PR TITLE
Add OCTAX,OCTAG to smartchain

### PR DESCRIPTION
**Pull request by netdefi**
- [X] Filename in the `lowercase` format
- [X] Image format: `png`
- [X] Image size `256 by 256 px`

Update allowlist.json
 "0x4f1498da0f50f94e97f900b7e6e13d8e5220abe9"
 "0x39cab1ddafda34b9202f5a41f71b15d2f3eba2ac"

### CODE REVIEW

**Comment by netdefi** [comment]
Okey sir wait payment

**Comment by OrcaXMaster** [comment]
https://explorer.binance.org/tx/0FFA536749D5DE9B26B5BE2E37AD5BEB0A0D4A0944B888249EB11C9321A1CF62

Thanks :)

**Comment by OrcaXMaster** [comment]
Its done

**Comment by netdefi** [comment]
I will pay by BNB
How much to transfer

ในวันที่ พฤ. 29 เม.ย. 2021 เวลา 17:27 merge-fee-bot[bot] <
***@***.***> เขียนว่า:

**Comment by netdefi** [comment]
Transaction1BDCE2AA298584BCD8824DA3AE699FC25B031559A95FA6934B014AE9A88DA5C7



ในวันที่ พฤ. 29 เม.ย. 2021 เวลา 20:49 octax defi ***@***.***>
เขียนว่า:

**Comment by netdefi** [comment]
Please check for me. If something goes wrong, please advise us.

**Comment by netdefi** [comment]
Please advise us sir.

**Comment by catenocrypt** [comment]
Correction needed:  Please place an `info.json` file next to each logo file, with info about the project.
Documentation:  https://community.trustwallet.com/t/how-to-submit-a-token-logo/3863 
Example:

```json
{
    "name": "Trust Wallet Token",
    "type": "ERC20",
    "symbol": "TWT",
    "decimals": 8,
    "description": "Utility token to increase adoption of cryptocurrency.",
    "website": "https://trustwallet.com",
    "explorer": "https://explorer.binance.org/asset/TWT-8C2",
    "status": "active",
    "id": "TWT-8C2"
}
```

**Comment by netdefi** [comment]
Okay Thank for suggestion sir. Please wait for me to make corrections according to the instructions.

**Comment by Iamdeadlyz** [comment]
As per our policy, brand new tokens are not included. There is a minimum requirement of 2500 holder addresses and 5000 transactions (airdropped tokens excluded) in order to filter out scam tokens. See the criteria at (mentioned in the first message by the bot): https://community.trustwallet.com/t/how-to-submit-a-token-logo/3863#how-to-get-approved

This token has below-limit usage yet. This pull request will be put on hold. Please come back to us when all criteria are met. Just comment here so we can re-open. Note: You don't need to pay again.

**Pull request closed without merging**
