### PR TITLE
Add Logo for Freedom Reserve

### PR DESCRIPTION
**Pull request by AcapSLP**
This PR is being closed due to inactivity. If you wish to continue, please have us reopen the PR before sending your payment.
Do NOT send payments for closed PR, as the fee may by lost!
  (60 vs. 60 hrs)

### CODE REVIEW

**Comment by AcapSLP** [comment]
There is real usage of this coin. people are using it to buy goods from each other.
photo_2020-12-22_16-21-31

**Comment by AcapSLP** [comment]
our community has over 1000 members on telegram and discord. 

it doesn't have as many holders as some of the giant ponzi tokens out there but it is a real coin with a real but small community. please add our logo to trustwallet.

thank you.

**Comment by catenocrypt** [comment]
We'll wait some more time to see how the project evolves.

**Comment by catenocrypt** [comment]
Note on fee: previous fee for #4838 can be considered here,  fee bot messages will be overriden manually.

**Comment by AcapSLP** [comment]
> We'll wait some more time to see how the project evolves.

Ok thank you. we have a major physical sticker campaign to advertise our shop and currency starting at christmas and yet more products will be added to the green man shop which accepts FR. there are a number of other businesses accepting FR for goods/services. hopefully there will be steady growth in the ecosystem with this adoption.

**Comment by AcapSLP** [comment]
> We'll wait some more time to see how the project evolves.

Hi, we have some project updates. We are now accepted as payment by a Lighting company in London as well as a Music label. there have been significant purchase volume through our store front as well.

we are developing NFT sale page and also doing a cross chain bridge to AVAX. 

We are also listed on blockfolio now too in addition to coingecko, coinmarketcap, etherscan etc.

please check https://freedomreserv.eth.link

**Comment by AcapSLP** [comment]
@catenocrypt  can you reopen this PR in light of our updates?

**Comment by catenocrypt** [comment]
I am ready to merge this submission once fee is paid.
Please note that the website has many broken images.

**Comment by AcapSLP** [comment]
> I am ready to merge this submission once fee is paid.
> Please note that the website has many broken images.

hi please note that the fee has already been paid https://github.com/trustwallet/assets/pull/5162#issuecomment-750030676

thanks for letting me know about the broken images redeploying site on ipfs in progress

**Comment by catenocrypt** [comment]
Considering payment from #4838, txid 9AD89AB7515C0E12EF47AB4DB2D587F5C8311A80D69909FF65A5430C5A1805C1

**Comment by AcapSLP** [comment]
> Considering payment from #4838, txid 9AD89AB7515C0E12EF47AB4DB2D587F5C8311A80D69909FF65A5430C5A1805C1

thank you very much!

**Pull request merged**
