### PR TITLE
ZFMCOIN Logo Add

### PR DESCRIPTION
**Pull request by zfmcoin**
{
"name": "ZFMCOIN",
"website": "https://www.zfmcoin.com ",
"description": "ZFM COIN is a Binance Smart Chain based Token, with burn function, high security, low fees, fast transaction and eco friendly. ZFM COIN Cross-chain Asset Locked by Smart Contract. Data Security Safeguarded by Binance Smart Chain. ZFM COIN Token has a burn function, which means that over time, the number of tokens will decrease..'",
"socials": [
{
"name": "Twitter",
"url": "https://mobile.twitter.com/zfmcoin"
},
{
"name": "Telegram",
"url": "https://t.me/ZFMCOIN_GROUP"
},
{
"name": "Telegram",
"url": "https://t.me/ZFMCOIN_ANNOUNCEMENT"
}
],
"explorer": "https://bscscan.com/token/0xce6b8B2787C657f1b98b7A66B5B63178863fd719",
"type": "BEP20",
"symbol": "ZFM",
"decimals": 18,
"status": "active",
"id": "0xce6b8B2787C657f1b98b7A66B5B63178863fd719"
}

### CODE REVIEW

**Comment by zfmcoin** [comment]
Logo

sir please add our token logo

**Comment by zfmcoin** [comment]
hello sir and maam please add our token logo @Cryptocool1 @cryptomanz1 @hexorx

**Comment by Cryptocool1** [comment]
• What is the purpose of this token? How will it benefit Trust Wallet users?
 • How is the token being distributed? Are you conducting an airdrop?
 • Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?
 • Is the token listed on a centralized/decentralized exchange?
 • Is a Smart Contract audit completed? Where can we find this information?

**Comment by zfmcoin** [comment]
> ### PR Summary
> Files OK: 2 Token in PR: **BEP20** 0xce6b8B2787C657f1b98b7A66B5B63178863fd719 Symbol: **ZFM** decimals: 18 Links: [Logo](https://raw.githubusercontent.com/zfmcoin/assets/master/blockchains/smartchain/assets/0xce6b8B2787C657f1b98b7A66B5B63178863fd719/logo.png) [Info](https://raw.githubusercontent.com/zfmcoin/assets/master/blockchains/smartchain/assets/0xce6b8B2787C657f1b98b7A66B5B63178863fd719/info.json) [Website](https://www.zfmcoin.com) [Explorer](https://bscscan.com/token/0xce6b8B2787C657f1b98b7A66B5B63178863fd719) Token check error: ❌ at least 2 links are required, 0 present. Add as many as you can: twitter, github, telegram, reddit, etc ❌ at least 1 tag is required ❌ number of holders not checked: please, check it manually
> 
> 

Socail link: 
Twitter: https://twitter.com/zfmcoin
Telegram Channel : https://t.me/ZFMCOIN_ANNOUNCEMENT
Telegram Group: https://t.me/ZFMCOIN_GROUP
Youtube: https://youtube.com/channel/UCxzLrDLSO1OgaNXoGoy1McQ
github: https://github.com/zfmcoin

Holders: 10,042 addresses
Transfers: 11,066

**Comment by zfmcoin** [comment]
> • What is the purpose of this token? How will it benefit Trust Wallet users? • How is the token being distributed? Are you conducting an airdrop? • Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale? • Is the token listed on a centralized/decentralized exchange? • Is a Smart Contract audit completed? Where can we find this information?



• What is the purpose of this token?
ZFM COIN is a Binance Smart Chain based Token, with burn function, high security, low fees, fast transaction and eco friendly.
User can earn zfm by participating our airdrop and bounty.


 How will it benefit Trust Wallet users?
Trust wallet user easly will find zfmcoin and they can send and receive zfm

• How is the token being distributed? Are you conducting an airdrop?
zfm total 3 airdrops in progress we have istributed one airdrop

all airdrop distributed 20th december

• Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?

ieo still runing latoken exchange please chanck: https://go.latoken.com/9ub

• Is the token listed on a centralized/decentralized exchange?

This echange allrady listed trade open 15th november

hotbit :
bitmart:
latoken:
coinstore:
digifinex



• Is a Smart Contract audit completed? Where can we find this information?

audit report: https://irp.cdn-website.com/1b45ecb9/files/uploaded/ZFMCoin_AuditReport_InterFi.pdf

**Comment by zfmcoin** [comment]
> ### PR Summary
> Files OK: 2 Token in PR: **BEP20** 0xce6b8B2787C657f1b98b7A66B5B63178863fd719 Failed to get info.json content: failed to unmarshal json: invalid character '"' after object key:value pair (https://raw.githubusercontent.com/zfmcoin/assets/master/blockchains/smartchain/assets/0xce6b8B2787C657f1b98b7A66B5B63178863fd719/info.json)

{
    "name": "ZFMCOIN",
    "website": "https://www.zfmcoin.com/",
    "description": "ZFM COIN is a Binance Smart Chain based Token, with burn function, high security, low fees, fast transaction and eco friendly. ZFM COIN Cross-chain Asset Locked by Smart Contract. Data Security Safeguarded by Binance Smart Chain. ZFM COIN Token has a burn function, which means that over time, the number of tokens will decrease..'",
    "explorer": "https://bscscan.com/",
    "research": "https://latoken.com/ieo/ZFM?utm_source=telegram&utm_medium=socials&utm_campaign=zfm_ieo_round1&utm_id=zfm_ieo&utm_content=telegram_post",
    "symbol": "ZFM",
    "type": "Token",
    "decimals": 18,
    "status": "active",
    "tags": [
        "staking-native"
    ],
    "links": [
        {
            "name": "github",
            "url": "https://github.com/zfmcoin/"
        },
        {
            "name": "twitter",
            "url": "https://twitter.com/zfmcoin"
        },
        {
            "name": "Telegram",
            "url": "https://t.me/ZFMCOIN_ANNOUNCEMENT"
        },
        {
            "name": "whitepaper",
            "url": "https://drive.google.com/file/d/1Cti8HUp7WWcabQVt_jqueXA07aCOUz1q/view?usp=sharing"
        }
    ]
}

**Comment by zfmcoin** [comment]
> ### PR Summary
> Files OK: 2 Token in PR: **BEP20** 0xce6b8B2787C657f1b98b7A66B5B63178863fd719 Failed to get info.json content: failed to unmarshal json: invalid character '"' after object key:value pair (https://raw.githubusercontent.com/zfmcoin/assets/master/blockchains/smartchain/assets/0xce6b8B2787C657f1b98b7A66B5B63178863fd719/info.json)

{
    "name": "ZFMCOIN",
    "website": "https://www.zfmcoin.com/",
    "description": "ZFM COIN is a Binance Smart Chain based Token, with burn function, high security, low fees, fast transaction and eco friendly. ZFM COIN Cross-chain Asset Locked by Smart Contract. Data Security Safeguarded by Binance Smart Chain. ZFM COIN Token has a burn function, which means that over time, the number of tokens will decrease..'",
    "explorer": "https://bscscan.com/token/0xce6b8B2787C657f1b98b7A66B5B63178863fd719",
    "research": "https://latoken.com/ieo/ZFM?utm_source=telegram&utm_medium=socials&utm_campaign=zfm_ieo_round1&utm_id=zfm_ieo&utm_content=telegram_post",
    "symbol": "ZFM",
    "type": "Token",
    "decimals": 18,
    "status": "active",
    "tags": [
        "staking-native"
    ],
    "links": [
        {
            "name": "github",
            "url": "https://github.com/zfmcoin/"
        },
        {
            "name": "twitter",
            "url": "https://twitter.com/zfmcoin"
        },
        {
            "name": "Telegram",
            "url": "https://t.me/ZFMCOIN_ANNOUNCEMENT"
        },
        {
            "name": "whitepaper",
            "url": "https://drive.google.com/file/d/1Cti8HUp7WWcabQVt_jqueXA07aCOUz1q/view?usp=sharing"
        }
    ]
}

**Comment by zfmcoin** [comment]
Legal Opinion $ZFM Token

https://drive.google.com/file/d/1VvkCDHcdJFjWEmbohp9UmHr8MlN_DG_0/view?usp=sharing

**Comment by zfmcoin** [comment]
Socail link:
Twitter: https://twitter.com/zfmcoin
Telegram Channel : https://t.me/ZFMCOIN_ANNOUNCEMENT
Telegram Group: https://t.me/ZFMCOIN_GROUP
Youtube: https://youtube.com/channel/UCxzLrDLSO1OgaNXoGoy1McQ
github: https://github.com/zfmcoin

Total Holders: 10,042 addresses
Total Transfers: 11,066

**Comment by zfmcoin** [comment]
@Cryptocool1 @cryptomanz1 @hexorx @rfunduk sir please add our token logo all information valid Let me know if you need any information

**Comment by zfmcoin** [comment]
this is our token contract please chack https://bscscan.com/token/0xce6b8B2787C657f1b98b7A66B5B63178863fd719

**Comment by zfmcoin** [comment]
sir i don't  know how to solve this error https://prnt.sc/LGO5Om3rzEdH please help me

**Comment by zfmcoin** [comment]
@cryptomanz1 sir help please

**Comment by cryptomanz1** [comment]
• What is the purpose of this token? How will it benefit Trust Wallet users?
 • How is the token being distributed? Are you conducting an airdrop?
 • Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?
 • Is the token listed on a centralized/decentralized exchange?
 • Is a Smart Contract audit completed? Where can we find this information?

**Comment by zfmcoin** [comment]
• What is the purpose of this token?
ZFM COIN is a Binance Smart Chain based Token, with burn function, high security, low fees, fast transaction and eco friendly.
User can earn zfm by participating our airdrop and bounty.

How will it benefit Trust Wallet users?
Trust wallet user easly will find zfmcoin and they can send and receive zfm

• How is the token being distributed? Are you conducting an airdrop?
zfm total 3 airdrops in progress we have istributed one airdrop

all airdrop distributed 20th december

• Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?

ieo still runing latoken exchange please chanck: https://go.latoken.com/9ub

• Is the token listed on a centralized/decentralized exchange?

This echange allrady listed trade open 15th november

hotbit :
bitmart:
latoken:
coinstore:
digifinex

• Is a Smart Contract audit completed? Where can we find this information?

audit report: https://irp.cdn-website.com/1b45ecb9/files/uploaded/ZFMCoin_AuditReport_InterFi.pdf

**Comment by zfmcoin** [comment]
@cryptomanz1 please chack sir

**Pull request merged**
