### PR TITLE
Adding SafePokeman Token Logo to TrustWallet

### PR DESCRIPTION
**Pull request by SafePokeman**
Adding the SafePokeman.com (SafePokeman Token) logo onto trustwallet

### CODE REVIEW

**Comment by SafePokeman** [comment]
Awaiting payment address
[0xfb16b31fa8a6edcd2dde78654cb0668c724c1dac.zip](https://github.com/trustwallet/assets/files/6717985/0xfb16b31fa8a6edcd2dde78654cb0668c724c1dac.zip)

**Comment by SafePokeman** [comment]
TWT payment sent
Transaction: https://explorer.binance.org/tx/7AFBF6807CA529D93335BD411FDE927CF114A4BC9EB432B13CAEC82CD8EBC5E8

**Comment by cryptomanz** [comment]
correction needed:
This is a BEp20 token, correct folder is blockchains/smartchain/assets.

**Comment by SafePokeman** [comment]
Added SafePokeman Token contract id folder to smartchain asset database.

Please can you confirm?

**Comment by SafePokeman** [comment]
Hello, please can you update me as to if i have done it correctly? :) Thanks

**Comment by Cryptocool1** [comment]
> Hello, please can you update me as to if i have done it correctly? :) Thanks

If you can't rename files in the PR, you may open a new PR. Make sure to mention this PR, so that we can see that fee has been paid already here.

**Comment by SafePokeman** [comment]
Thank you for this, i believe i have done this, could you possibly double check?

**Comment by cryptomanz** [comment]
still wrong, please create new PR

**Comment by SafePokeman** [comment]
I believe i have done this now? :)
https://github.com/trustwallet/assets/pull/11229

**Comment by SafePokeman** [comment]
Hi I Created the new PR but it has been closed?

**Comment by Cryptocool1** [comment]
> I believe i have done this now? :)
> #11229

empty info.json file

**Comment by SafePokeman** [comment]
Can you guys please check the new PR i made? #11497

**Comment by Cryptocool1** [comment]
still incorrect 
Please create new PR, follow doc https://community.trustwallet.com/t/how-to-submit-a-token-logo/3863
You may want to try our Assets app in beta; go to https://assets.trustwallet.com, log on with Github, enter contract ID, logo and some additional info, and it will create a PR for you.
See https://community.trustwallet.com/t/how-to-submit-a-token-logo-using-assets-app/82957.

notice, you don't need to pay one more time

**Comment by SafePokeman** [comment]
Done, please see PR 11528

**Comment by SafePokeman** [comment]
> still incorrect
> Please create new PR, follow doc https://community.trustwallet.com/t/how-to-submit-a-token-logo/3863
> You may want to try our Assets app in beta; go to https://assets.trustwallet.com, log on with Github, enter contract ID, logo and some additional info, and it will create a PR for you.
> See https://community.trustwallet.com/t/how-to-submit-a-token-logo-using-assets-app/82957.
> 
> notice, you don't need to pay one more time

please see pull request 11528

kind regards

**Comment by SafePokeman** [comment]
https://github.com/trustwallet/assets/pull/11528

**Pull request closed without merging**
