### PR TITLE
Update CZF, CZUSD logos

### PR DESCRIPTION
**Pull request by PlasticDigits**
Update CZF and CZUSD logos to the new versions.

### CODE REVIEW

**Comment by PlasticDigits** [comment]
This PR is to update token logos only.

**Comment by Cryptocool1** [comment]
Hello, the fee is required for updating

**Comment by PlasticDigits** [comment]
OK, we are not in a hurry for trust wallet users, take your time.

**Comment by PlasticDigits** [comment]
Please add to free update queue @Cryptocool1

**Pull request closed without merging**
