### PR TITLE
Add Rook (ERC20)

### PR DESCRIPTION
**Pull request by pangolin1**
Adding info for ERC20 token 'Rook'.

PR created by <a href="https://assets.trustwallet.com">TW Assets Management</a>

### CODE REVIEW

**Comment by Cryptocool1** [comment]
• What is the purpose of this token? How will it benefit Trust Wallet users?
 • How is the token being distributed? Are you conducting an airdrop?
 • Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?
 • Is the token listed on a centralized/decentralized exchange?
 • Is a Smart Contract audit completed? Where can we find this information?

**Comment by pangolin1** [comment]
The token is used in the Rook protocol. More details here: https://docs.rook.fi/reference/rook-protocol/understand-the-protocol. It has been around for a while. It's listed on several CEXs and DEXs, including Kraken, Uniswap and Bancor.

Information about the contracts can be found here: https://docs.rook.fi/reference/reference/smart-contracts.

**Comment by Cryptocool1** [comment]
• What is the purpose of this token? How will it benefit Trust Wallet users?
• How is the token being distributed? Are you conducting an airdrop?
• Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?
I didn’t see the smart contract audit, can you send it here?

**Comment by pangolin1** [comment]
The token is used by Keepers to bid on the protocol. It is also the governance token for the Rook DAO. If a trustwallet user wanted to participate in either of these things they'd need the token.

The token has been distributed already. There was a TGE and then a distribution schedule. There will be no airdrop.

AFAIK, there was no ICO. I don't know about presale (I am not a founder - just a dev contributor).

I'll try and get the audits to you if they're not on the site.

**Comment by Cryptocool1** [comment]
Awaiting for smart contract audit. On hold for now

**Pull request merged**
