### PR TITLE
update info + logo for bakerytools

### PR DESCRIPTION
**Pull request by BakeryTools**
Please upload our logo and our info for bakerytools

### CODE REVIEW

**Comment by catenocrypt** [comment]
Correction needed: 
Files should be under folder `blockchains/smartchain/assets/0x26d6e280f9687c463420908740ae59f712419147`, not `blockchains/smartchain/0x26d6e280f9687c463420908740ae59f712419147`.  Please move'em.

**Comment by BakeryTools** [comment]
We have now fixed this , they are both in the correct folder as displayed. we have removed the other folder.

**Comment by Cryptocool1** [comment]
hello,
can you delete this file ?  blockchains/smartchain/assets/0x26d6e280f9687c463420908740ae59f712419147/tbake

**Comment by Cryptocool1** [comment]
Contract is not in checksum format, should be 0x26D6e280F9687c463420908740AE59f712419147 (not 0x26d6e280f9687c463420908740ae59f712419147). Please rename it. You may need to rename to a temp name first, then to the checksum format, because lowercase-uppercase-only renames are often ignored by the Git client or the filesystem.

**Comment by BakeryTools** [comment]
all deleted

**Comment by Cryptocool1** [comment]
> all deleted
Can you rename your contract?
Your contract is not in checksum format, should be 0x26D6e280F9687c463420908740AE59f712419147 (not 0x26d6e280f9687c463420908740ae59f712419147). Please rename it.

**Comment by BakeryTools** [comment]
done

**Comment by Cryptocool1** [comment]
> done

Rename please your id.
, should be 0x26D6e280F9687c463420908740AE59f712419147, not 0x26d6e280f9687c463420908740ae59f712419147.

**Comment by BakeryTools** [comment]
this image is incorrect format ill re-add

**Comment by BakeryTools** [comment]
im not sure why the image looks so narrow. will this be the case once trust wallet?

**Comment by Cryptocool1** [comment]
Your image is OK.
-Contract is not a valid Ethereum address!
- Id field does not match contract, should be 0x26D6e280F9687c463420908740AE59f712419147,, not 0x26d6e280f9687c463420908740ae59f712419147. Please rename.

**Comment by BakeryTools** [comment]
this is frustrating. im copying the address you put and its not working

**Comment by Cryptocool1** [comment]
> this is frustrating. im copying the address you put and its not working
0x26D6e280F9687c463420908740AE59f712419147 should be your ID. Try again

**Comment by BakeryTools** [comment]
i am literally copying what you are sending me 0x26D6e280F9687c463420908740AE59f712419147

**Comment by BakeryTools** [comment]
sorry my bad

**Comment by BakeryTools** [comment]
will the logo be narrow ? or will it display fine

**Comment by BakeryTools** [comment]
can we update the logo ?? the logo looks so tiny

**Pull request merged**
