### PR TITLE
Add BitXcoin (BEP20)

### PR DESCRIPTION
**Pull request by aaressinfomedia**
Adding info for BEP20 token 'BitXcoin'.

PR created by <a href="https://assets.trustwallet.com">TW Assets Management</a>

### CODE REVIEW

**Comment by Cryptocool1** [comment]
you didn't have holders couple days ago, how did you get those amount of holders ?

**Comment by aaressinfomedia** [comment]
Respected Sir,

I have 10000+ users and growing every day as I am running BitX community in
India and abroad for more than 18 months now and there are followers who
have received these tokens as there holdings but all tokens were held in
Liquidity Wallet managed by  us but since it was your requirement to have
10K plus holders so we simply distributed Tokens as per individual holdings
to their wallets and these same tokens are released monthly which users
have right to sell which you can check on Pancake swap where every day
users encash there Tokens against BNB-BITX pair, for your kind perusal find
link where you can verify daily transactions.
https://pancakeswap.finance/info/pool/0xc78e8a4a895378e30c7cf16fec66b330ce3a739f

I myself am the creator, promoter and developer of this community. You can
verify my credentials from youtube as I have a 10 year old youtube account
on which I have been guiding my community about crypto and blockchain
technology's future.


Thank you

Sujit S Jadhav

Skype : secrettogetrich

Ph : +91-7387713333

Mr.Sujit S Jadhav

This communication (including any attachments) is intended only for the
person or entity to which it is addressed and may contain confidential
and/or privileged material.  If you are not the intended recipient, any
disclosure, copying, distribution or use of the contents of this
communication is prohibited.  If you have received it in error, please
contact the sender immediately and delete this communication without
copying.
Any unauthorized review, use, disclosure, dissemination, forwarding,
printing, etc. of this email or any action taken in reliance on this e-mail
is strictly prohibited and may be unlawful. Sujit Jadhav does not accept
responsibility for any loss arising from unauthorized access to, or
interference with, any internet communications by any third party, or from
the transmission of any viruses.
WARNING: Computer viruses can be transmitted via this communication. The
recipient should check this communication and any attachments for the
presence of viruses. Sender or Indus accepts no liability for any damage
caused by any virus transmitted by this communication.

**Comment by Cryptocool1** [comment]
• What is the purpose of this token? How will it benefit Trust Wallet users?
 • How is the token being distributed? Are you conducting an airdrop?
 • Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?
 • Is the token listed on a centralized/decentralized exchange?
 • Is a Smart Contract audit completed? Where can we find this information?

**Comment by Cryptocool1** [comment]
Please come back to us once you will be ready to answer the questions. Feel free to create new PR and mention this one, so the fee can be reused.

**Comment by aaressinfomedia** [comment]
> Please come back to us once you will be ready to answer the questions. Feel free to create new PR and mention this one, so the fee can be reused.

I dont know how to resolve this 

error : number of holders not checked: please check it manually.

Please guide me how to check holders manually ??

**Comment by Cryptocool1** [comment]
you don't need to resolve anything. just answer the questions

**Comment by aaressinfomedia** [comment]
I need to know which question is unanswered please 🙏

**Comment by Cryptocool1** [comment]
look at the questions I asked above

**Comment by aaressinfomedia** [comment]
Respected Sir,

*Purpose Of Token :* Bitcoin Token is created for development of a
decentralized ecosystem for our Bit X community who are looking for safe
investment in crypto space but are reluctant due to high risk and price
volatility in crypto currency. We have developed this token with unique
Value Incremental Factor which gives steady appreciation of Token Value as
it is sold through the official website https://bitxcoin.io, Most important
is that we are selling tokens in systematic Slots of 2 million Each with
Fixed Incremental Value Constant, all sold tokens shall remain in fifteen
months lockin and shall be released every month in equal quantity which can
be encashed though Swap feature of Pancakeswap provided in members login.

*Benefit of Trust Wallet Users :* I have huge community who is downloading
Trust wallet for storing and transacting BitXcoin because of which Trust
Wallet will have deeper reach in to Billion Indians who are unaware of
Blockchain & Crypto Assets, I am training them to use different Blockchain
based App's and Wallet Services which in turn will increase number of
downloads of TrustWallet.

*Did you sold the tokens at an Initial Coin Offering (ICO) or a token
presale?*

Our ITO is going on right now and around 6 million Tokens have been sold in
ITO, apart from these we have distributed 550 Million Tokens to our
community as stake holding which shall get burned over the period of 15
months.

*Is the token listed on a centralized/decentralized exchange?*

Yes, BitXcoin is listed on Pancakeswap

Link :
https://pancakeswap.finance/info/pool/0xc78e8a4a895378e30c7cf16fec66b330ce3a739f

*Is a Smart Contract audit completed? Where can we find this information?*

Smart Contract Audit is under process and expected to be ready by 20th June.

Thank you

Sujit S Jadhav

Skype : secrettogetrich

Ph : +91-7387713333

Mr.Sujit S Jadhav

This communication (including any attachments) is intended only for the
person or entity to which it is addressed and may contain confidential
and/or privileged material.  If you are not the intended recipient, any
disclosure, copying, distribution or use of the contents of this
communication is prohibited.  If you have received it in error, please
contact the sender immediately and delete this communication without
copying.
Any unauthorized review, use, disclosure, dissemination, forwarding,
printing, etc. of this email or any action taken in reliance on this e-mail
is strictly prohibited and may be unlawful. Sujit Jadhav does not accept
responsibility for any loss arising from unauthorized access to, or
interference with, any internet communications by any third party, or from
the transmission of any viruses.
WARNING: Computer viruses can be transmitted via this communication. The
recipient should check this communication and any attachments for the
presence of viruses. Sender or Indus accepts no liability for any damage
caused by any virus transmitted by this communication.

**Comment by aaressinfomedia** [comment]
Respected sir,

Kindly let me know how to resolve this issue

number of holders not checked: please, check it manually

Thank you

Sujit S Jadhav

Skype : live:.cid.c4a06b4c42226aea

Ph : +91-7387713333

Mr.Sujit S Jadhav

This communication (including any attachments) is intended only for the
person or entity to which it is addressed and may contain confidential
and/or privileged material.  If you are not the intended recipient, any
disclosure, copying, distribution or use of the contents of this
communication is prohibited.  If you have received it in error, please
contact the sender immediately and delete this communication without
copying.
Any unauthorized review, use, disclosure, dissemination, forwarding,
printing, etc. of this email or any action taken in reliance on this e-mail
is strictly prohibited and may be unlawful. Sujit Jadhav does not accept
responsibility for any loss arising from unauthorized access to, or
interference with, any internet communications by any third party, or from
the transmission of any viruses.
WARNING: Computer viruses can be transmitted via this communication. The
recipient should check this communication and any attachments for the
presence of viruses. Sender or Indus accepts no liability for any damage
caused by any virus transmitted by this communication.

**Comment by Cryptocool1** [comment]
• Is a Smart Contract audit completed? Where can we find this information?

**Pull request closed without merging**
