### PR TITLE
Upload Logo USF

### PR DESCRIPTION
**Pull request by bond2022**

### CODE REVIEW

**Comment by bond2022** [comment]
I have paid 250 TWT https://explorer.binance.org/tx/150262C35578ED9F9189793FD47A5D211CCBC5DC230E12DDF159CF5A74D1A9BB?fbclid=IwAR29MkFhnwmRaDNyDt39GBPp-jJChlnTRzOVt-WvcXi3ta4m1aqBj120-rQ

**Comment by Iamdeadlyz** [comment]
Please provide more details about this project.
https://community.trustwallet.com/t/how-to-submit-a-token-logo/3863#how-to-get-approved
You can follow this format when adding an info.json file:
```
{
    "name": "Trust Wallet Token",
    "website": "https://trustwallet.com",
    "source_code": "https://github.com/trustwallet/",
    "short_description": "Utility token to increase adoption of cryptocurrency.",
    "description": "Utility token to increase adoption of cryptocurrency.",
    "socials": [
        {
            "name": "Twitter",
            "url": "https://twitter.com/trustwalletapp",
            "handle": "TrustWalletApp"
        },
        {
            "name": "Reddit",
            "url": "https://reddit.com/r/trustapp",
            "handle": "TrustApp"
        }
    ],
    "explorer": "https://bscscan.com/token/0x4b0f1812e5df2a09796481ff14017e6005508003"
} 
```

**Comment by bond2022** [comment]
I have updated the requirements

**Comment by bond2022** [comment]
Hi admin.
My logo has appeared on the trust wallet, but now it no longer shows logo.
admin please check for me.
Thank you

Vào Th 2, 19 thg 10, 2020 vào lúc 16:42 Adam R <notifications@github.com>
đã viết:

**Comment by thomasjoin2020** [comment]
My logo has appeared on the trust wallet, but now it no longer shows logo. admin please check for me

**Pull request merged**
