### PR TITLE
Add THE BULLS ARMY (POLYGON)

### PR DESCRIPTION
**Pull request by xbrlab**
Adding info for POLYGON token 'THE BULLS ARMY'.

PR created by <a href="https://assets.trustwallet.com">TW Assets Management</a>

### CODE REVIEW

**Comment by cryptomanz1** [comment]
As per our policy, there is a minimum requirement of 10,000 holder addresses and 15,000 transactions.
See the criteria at : https://developer.trustwallet.com/listing-new-assets/requirements .

**Comment by Cryptocool1** [comment]
Please come back to us once all criteria are met, make sure to mention this PR so the fee can be reused.

**Comment by xbrlab** [comment]
Sure, Thanks for the feedback. Will raise the PR again once we meet the requirements we are missing.

**Comment by Jstacy121** [comment]
I really need your help hope you people can contribute for my hard working
bc1q6nvwd9ftz8n07f8q6jnppcz40739reauqt3zf7
Btc address

Stacy L Johnson
Sent with Spark

**Pull request closed without merging**
