### PR TITLE
Add Kiba Inu logo and info

### PR DESCRIPTION
**Pull request by Ozzyezzy1**
Please Add Kiba Inu logo and info

### CODE REVIEW

**Comment by Ozzyezzy1** [comment]
Please find our Certik Audit here: https://www.certik.org/projects/kibainu

We have also launched on bsc (possibility to bridge from eth to bsc or the opposite). Do I need to create a new pull request for the bsc contract ?

**Comment by Cryptocool1** [comment]
As per our policy, brand new tokens are not included, there is a minimum requirement of 25,000 holder addresses and 50,000 transactions, in order to filter out scam tokens.
See the criteria at : https://developer.trustwallet.com/assets/requirements .

**Comment by Ozzyezzy1** [comment]
> As per our policy, brand new tokens are not included, there is a minimum requirement of 25,000 holder addresses and 50,000 transactions, in order to filter out scam tokens.
> See the criteria at : https://developer.trustwallet.com/assets/requirements .

Hello, did you change the requirements lately? I remember it being 5000 holders and 10000 transactions just last week !

**Comment by Ozzyezzy1** [comment]
> and

Also, your page here mentions 5,000 holders and 10,000 transactions. This is what I followed : https://github.com/trustwallet/assets/pull/15807#issuecomment-971633157

**Comment by Ozzyezzy1** [comment]
> As per our policy, brand new tokens are not included, there is a minimum requirement of 25,000 holder addresses and 50,000 transactions, in order to filter out scam tokens.
> See the criteria at : https://developer.trustwallet.com/assets/requirements .

We are audited by Certik: https://www.certik.org/projects/kibainu

We are launched on both ETH and BSC and have more than 12,500 holders between both contract (ETH and BSC)

**Comment by Ozzyezzy1** [comment]
> > and
> 
> Also, your page here mentions 5,000 holders and 10,000 transactions. This is what I followed : [#15807 (comment)](https://github.com/trustwallet/assets/pull/15807#issuecomment-971633157)

This https://community.trustwallet.com/t/how-to-submit-a-token-logo/3863

**Comment by Ozzyezzy1** [comment]
> As per our policy, brand new tokens are not included, there is a minimum requirement of 25,000 holder addresses and 50,000 transactions, in order to filter out scam tokens.
> See the criteria at : https://developer.trustwallet.com/assets/requirements .

We are also KYCd here: https://www.assuredefi.io/projects/kiba-inu/

**Comment by Ozzyezzy1** [comment]
> As per our policy, brand new tokens are not included, there is a minimum requirement of 25,000 holder addresses and 50,000 transactions, in order to filter out scam tokens.
> See the criteria at : https://developer.trustwallet.com/assets/requirements .

Hello, I remember the requirements being 5,000 holders and 10,000 transactions as mentioned here : https://community.trustwallet.com/t/how-to-submit-a-token-logo/3863

KIBA Inu is not a scam coin. We are about a month old now and we are launched on both ETH and BSC

Eth chart: https://www.dextools.io/app/ether/pair-explorer/0xac6776d1c8d455ad282c76eb4c2ade2b07170104
Bsc chart: https://poocoin.app/tokens/0x31d3778a7ac0d98c4aaa347d8b6eaf7977448341

We are listed on Hotbit : https://hotbit.zendesk.com/hc/en-us/articles/4412209234711-Hotbit-will-launch-KIBA-Kiba-Inu-on-November-4th-2021

We are audited by Certik : https://www.certik.org/projects/kibainu

And We have finished a KYC: https://www.assuredefi.io/projects/kiba-inu/

**Comment by cryptomanz** [comment]
Please come back to us when all criteria are met.
When creating a new PR make sure to mention this PR, so that we can see that fee has been paid already here.

**Pull request closed without merging**
