### PR TITLE
Add Saiyan Inu (BEP20)

### PR DESCRIPTION
**Pull request by saiyaninu**
Adding info for BEP20 token 'Saiyan Inu'.

PR created by Saiyaninu

### CODE REVIEW

**Comment by saiyaninu** [comment]
Not sure the issue here

**Comment by Kitycoin** [comment]
hey saiyaninu,

i have the same message, do you know what it means?

**Comment by Kitycoin** [comment]
> Not sure the issue here

is this the standard reply until we pay the fee? i have the same message when i submitted info.json and logo.png , i checked and verified everything in order.

**Comment by Cryptocool1** [comment]
Correction needed:
This is a BEp20 token, correct folder is blockchains/smartchain/assets. Please correct.
Please create new PR, follow doc https://community.trustwallet.com/t/how-to-submit-a-token-logo/3863
You may want to try our new Assets app in beta; go to https://assets.trustwallet.com, log on with Github, enter contract ID, logo and some additional info, and it will create a PR for you.
See https://community.trustwallet.com/t/how-to-submit-a-token-logo-using-assets-app/82957.

**Pull request closed without merging**
