### PR TITLE
Update stormx token

### PR DESCRIPTION
**Pull request by alexhidalgo**
Update branding of STMX token

### CODE REVIEW

**Comment by catenocrypt** [comment]
I know this is an update to an existing token logo, but could you please add an `info.json` file next to the `logo.png`, with info about the project, of the form:

```json
{
    "name": "Trust Wallet Token",
    "website": "https://trustwallet.com",
    "short_description": "Utility token to increase adoption of cryptocurrency.",
    "explorer": "https://etherscan.io/token/0xA866F0198208Eb07c83081d5136BE7f775c2399e",
    "socials": [
        {
            "name": "Twitter",
            "url": "https://twitter.com/trustwalletapp",
            "handle": "TrustWalletApp"
        },
        {
            "name": "Reddit",
            "url": "https://reddit.com/r/trustapp",
            "handle": "TrustApp"
        }
    ]
}
```

**Comment by alexhidalgo** [comment]
@catenocrypt it says there is a conflict but we don't see one on our side. Are you still able to merge?

**Comment by vikmeup** [comment]
> @catenocrypt it says there is a conflict but we don't see one on our side. Are you still able to merge?

you need to merge a conflict before we can merge any code.

**Comment by catenocrypt** [comment]
Please merge current master branch into `stormxio:update-stormx-token`; I tried to merge but I have no permission to your fork repo.

**Comment by calvinh8** [comment]
@catenocrypt @vikmeup updated. thanks

**Comment by catenocrypt** [comment]
This PR contains 0 new files now, in other words it's empty.  Please add logo and info.json again.  If it is easier, create a new PR (best if fork is deleted and created again), you will  not need to pay fee again.

**Comment by alexhidalgo** [comment]
@catenocrypt this should work now. Sorry for all the back and forth.

**Comment by catenocrypt** [comment]
Now it's OK!

**Pull request merged**
