### PR TITLE
#11679 Sadbaby Token BEP20 LOGO

### PR DESCRIPTION
**Pull request by sadbabytoken**
hello, the necessary commitments have been made, I will present you the smart contract requested from me.

### CODE REVIEW

**Comment by sadbabytoken** [comment]
https://bscscan.com/address/0x4e84e47bbabd89835e2e9569d69a6d465de38122#code#L1

https://bscscan.com/address/0x4e84e47bbabd89835e2e9569d69a6d465de38122#code

**Comment by sadbabytoken** [comment]
You can check 11679 Pr. Our payments were made. A smart contract was requested. I would like to present it to you as a link.

**Comment by Cryptocool1** [comment]
we requested smart contract audit
create new PR when all criteria are met

**Review by sadbabytoken — COMMENTED** [review]
[SadBaby.pdf](https://github.com/trustwallet/assets/files/6847714/SadBaby.pdf)

**Pull request closed without merging**
