### PR TITLE
add logo & info for Tadpole

### PR DESCRIPTION
**Pull request by ngkong**

### CODE REVIEW

**Comment by Iamdeadlyz** [comment]
As per our policy, brand new tokens are not included. There is a minimum requirement of 500 holder addresses and 1000 transactions in order to filter out scam tokens. See the criteria at (mentioned in the first message by the bot): https://community.trustwallet.com/t/how-to-submit-a-token-logo/3863#how-to-get-approved

This token has below-limit usage yet. This pull request will be put on hold. Please come back to us when all criteria are met.
https://etherscan.io/token/0x9f7229aF0c4b9740e207Ea283b9094983f78ba04 (108, 252)

**Comment by ngkong** [comment]
Hi @Iamdeadlyz and Team, can you review it again? Very appreciated your time

**Comment by Iamdeadlyz** [comment]
Hello @ngkong 

Please resized your logo to `256px by 256px`. You can use: https://picresize.com/

**Review by Iamdeadlyz — CHANGES_REQUESTED** [review]
Hello @ngkong 

Please resize your logo to `256px by 256px`. You can use: https://picresize.com/

**Comment by ngkong** [comment]
Hi @Iamdeadlyz, logo fixed! Thanks

**Review by Iamdeadlyz — APPROVED** [review]

**Pull request merged**
