### PR TITLE
Add Hope (BEP20)

### PR DESCRIPTION
**Pull request by HopeToken123**
Adding info for BEP20 token 'Hope'.

PR created by <a href="https://assets.trustwallet.com">TW Assets Management</a>

### CODE REVIEW

**Comment by HopeToken123** [comment]
what do i need to do :/

**Comment by Cryptocool1** [comment]
Correction needed:
PR should include only 2 files

**Comment by Cryptocool1** [comment]
PR should include only 2 files:
logo.png
info.json

**Comment by Cryptocool1** [comment]
Please create new PR, follow doc https://community.trustwallet.com/t/how-to-submit-a-token-logo/3863
You may want to try our new Assets app in beta; go to https://assets.trustwallet.com, log on with Github, enter contract ID, logo and some additional info, and it will create a PR for you.
See https://community.trustwallet.com/t/how-to-submit-a-token-logo-using-assets-app/82957.

**Pull request closed without merging**
