### PR TITLE
Add Super Floki (BEP20)

### PR DESCRIPTION
**Pull request by erience**
Adding info for BEP20 token 'Super Floki'.

PR created by <a href="https://assets.trustwallet.com">TW Assets Management</a>

### CODE REVIEW

**Comment by cryptomanz** [comment]
Can your answer some questions?
 • What is the purpose of this token? How will it benefit Trust Wallet users?
 • How is the token being distributed? Are you conducting an airdrop?
 • Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?
 • Is the token listed on a centralized/decentralized exchange?
 • Is a Smart Contract audit completed? Where can we find this information?

**Comment by erience** [comment]
• What is the purpose of this token? How will it benefit Trust Wallet users? ---- Holders will get a trusted place to store their Tokens. Existing wallet users may would like to checkout this innovative and emerging project as Superfloki's goal is to make our own blockchain in the future.

• How is the token being distributed? Are you conducting an airdrop? --- Distribution is 80% Initial Liquidity and 20% Initial Burn. No Team wallet or Airdrop.

• Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale? --- Fair Launch. No ICO.

• Is the token listed on a centralized/decentralized exchange? ---- Listed on Pancakeswap  

• Is a Smart Contract audit completed? Where can we find this information? ---- TechRate Audit is under progress and will be completed within 2 days.

**Comment by erience** [comment]
@cryptomanz : provided answer above

**Comment by cryptomanz** [comment]
> @cryptomanz : provided answer above

- Awaiting for smart contract audit. On hold for now.

**Comment by erience** [comment]
@cryptomanz : link of audit report: https://github.com/TechRate/Smart-Contract-Audits/blob/main/August/Super%20Floki%20Full%20Smart%20Contract%20Security%20Audit.pdf

**Pull request merged**
