### PR TITLE
Add ORAI (orai.io oraichain)

### PR DESCRIPTION
**Pull request by thaonguyentien**

### CODE REVIEW

**Comment by Iamdeadlyz** [comment]
In accordance with our [disclaimer](https://github.com/trustwallet/assets#disclaimer), your PR is denied due to the following reason:
- Copy pasted information with the intent to mislead users
image
image
image
image
image

**Comment by thaonguyentien** [comment]
@Iamdeadlyz Please check again. Thank you!

**Comment by thaonguyentien** [comment]
@Iamdeadlyz @zachzwei @catenocrypt, Please check again. Thank you!

**Comment by chung-pi** [comment]
Hi,

I am Chung, CEO and Founder of Oraichain.

I am reaching out because of the issue related to the merge request of Trustwallet/assets that I feel needs explaining. Firstly, I want to apologize and hope that you will give me a chance to explain.

It was our fault that we copied several feature descriptions from Singularitynet. These were merely descriptions when we created a rough draft of the initial version of the website, and I had a stern talking to our CTO about how must not be taking words from other projects websites. We immediately updated the content and understand that it was a bad look. We apologize for this.

Oraichain is the first world’s AI-powered oracle platform, and it is our own idea. Our underlying code and various projects such as yai finance and the AI Marketplace are completely original. Our entire AI approach is extremely unique from Singularitynet. Moreover, the approach and implementation of features on Oraichain are unique. 

Moving out of the start-up phase we are on our way to closing real-world partnerships and making sure all communication outwards is handled in a carefully and professional manner. 

Likewise, here is some information about me to show that I mean what I am saying:

- Co-founder of Rikkeisoft (Top 10 biggest IT company in Vietnam): https://rikkeisoft.com/en/people#main-content
- Got Ph.D. from The University of Tokyo: https://www.csg.ci.i.u-tokyo.ac.jp/en/members.html
- Binance x Novum x Dr. Chung Dao Webinar: https://www.facebook.com/watch/live/?v=859448864594361&ref=notif&notif_id=1603889868291248&notif_t=live_video
- Lecturer at Hanoi Uniseristy of Science and Technology: https://soict.hust.edu.vn/can-bo/ts-dao-thanh-chung.html
- Google scholar publication: https://scholar.google.com.vn/citations?user=bGBBNOcAAAAJ&hl=en

Again, apologies for this misunderstanding, and thank you for opening our eyes to this. We feel it is important to our community that the proper logo is implemented in Trust Wallet and Uniswap to prevent people from purchasing a fake token.

We hope that you will give us a second chance and review our Oraichain Trust Wallet request again.

Regards,
Chung

**Comment by Iamdeadlyz** [comment]
Thanks for explaining.

There is a minimum requirement of 2500 holder addresses and 5000 transactions (airdropped tokens excluded). See the criteria at (mentioned in the first message by the bot): https://community.trustwallet.com/t/how-to-submit-a-token-logo/3863#how-to-get-approved

This token has below-limit usage yet. This pull request will be put on hold. Please come back to us when all criteria are met.
https://etherscan.io/token/0x4c11249814f11b9346808179cf06e71ac328c1b5 (1054 holders and 32774 tx)

//Reopening #4658

**Comment by thaonguyentien** [comment]
@Iamdeadlyz We have already reached 2515 holders and
65,517 transactions. Please review us.

**Comment by Iamdeadlyz** [comment]
> @Iamdeadlyz We have already reached 2515 holders and
> 65,517 transactions. Please review us.

#4658 is now reopened

**Pull request closed without merging**
