### PR TITLE
Add XGT v2 info & remove old

### PR DESCRIPTION
**Pull request by marvinkruse**
Hey,

the XGT team upgraded their token to a new v2. Added the address + logo for Ethereum, bsc and xDAI and removed the old to avoid confusion. There are currently >10,000 token holders on BSC alone, so this should qualify even if ETH mainnet isn't being used yet. Please let me know if there are any questions or changes necessary!

### CODE REVIEW

**Comment by marvinkruse** [comment]
Sorry, added the deleted token back in.

**Comment by Cryptocool1** [comment]
you have 7 files, please delete unnecessary

**Comment by marvinkruse** [comment]
@Cryptocool1 which ones? as far as I can tell these are all needed since it's for eth mainnet + xdai + bsc. Which one shall I delete?

**Comment by Cryptocool1** [comment]
what is blockchain/xdai?

**Comment by Cryptocool1** [comment]
for arc correct folder isblockchains/ethereum/assets

**Comment by marvinkruse** [comment]
> what is blockchain/xdai?

the xdai chain by PoA. since the folder was already there I assumed this is fine. it's also ERC20 on there. is that not okay?

**Comment by Cryptocool1** [comment]
Screen Shot 2021-07-04 at 2 09 40 AM

**Comment by Cryptocool1** [comment]
> > what is blockchain/xdai?
> 
> the xdai chain by PoA. since the folder was already there I assumed this is fine. it's also ERC20 on there. is that not okay?

for ERC20 correct folder isblockchains/ethereum/assets not blockchain/xdai

**Comment by marvinkruse** [comment]
@Cryptocool1 
Changed it to abandoned for the old token and changed the xdai one to XDAI like the other ones in there. is that fine?

**Pull request merged**
