### PR TITLE
Update for token info and image

### PR DESCRIPTION
**Pull request by coingm**
Update for token info and image

### CODE REVIEW

**Comment by Cryptocool1** [comment]
description field is too long: 754 chars, max is 500
please change

**Comment by Cryptocool1** [comment]
could you add the links?
see the example here: https://developer.trustwallet.com/assets/repository_details

**Comment by coingm** [comment]
> 

GMCoin is the first company to establish a vast and practical token model based on #DeBu #Decentralized #Businesses developed on the whole #cryptocurrency network. It is the First Tokenized Company in the World with its Tron Blockchain-based GMCoin ecosystem.

**Comment by coingm** [comment]
> could you add the links? see the example here: https://developer.trustwallet.com/assets/repository_details

    "links": [
        {
            "name": "github",
            "url": "https://github.com/gmcoin"
        },
        {
            "name": "twitter",
            "url": "https://twitter.com/coin_gm"
        },
        {
            "name": "reddit",
            "url": "https://www.reddit.com/r/coingm/"
        }
    ]

**Comment by coingm** [comment]
"links": [
        {
            "name": "github",
            "url": "https://github.com/gmcoin"
        },
        {
            "name": "twitter",
            "url": "https://twitter.com/coin_gm"
        },
        {
            "name": "reddit",
            "url": "https://www.reddit.com/r/coingm/"
        }
    ]

Mehmet Ali Demirci
Chief Executive Officer
GM Informatics Joint Stock Company
Bitez Mah. - Saldır Şeyh Cad. - No:2/B
Bodrum / Muğla / Turkey
mail: ***@***.***
mobile: +90 (554) 402 17 90 • phone: +90 (252) 386 45 10
***@***.***<https://www.gm-informatics.com/>

https://www.gm-informatics.com/
[banner]<https://gmc.gm-informatics.com/>

[facebook icon]<https://www.facebook.com/mehmetali.demirci.35>  [youtube icon] <https://www.youtube.com/channel/UC540ccxJ3fVzrOSptvFBlEg>   [linkedin icon] <https://www.linkedin.com/in/mehmet-ali-demirci-94037229/>   [twitter icon] <https://twitter.com/malidemirci_gm>   [instagram icon] <https://www.instagram.com/mehmetalidemirci48/>

The content of this email is confidential and intended for the recipient specified in message only. It is strictly forbidden to share any part of this message with any third party, without a written consent of the sender. If you received this message by mistake, please reply to this message and follow with its deletion, so that we can ensure such a mistake does not occur in the future.

**Comment by coingm** [comment]
> could you add the links? see the example here: https://developer.trustwallet.com/assets/repository_details

Is everything ok? token updated?

**Review by vahdidgolami — APPROVED** [review]

**Comment by coingm** [comment]
GMCoin is the first company token to establish a vast and practical model based on #DeBu #Decentralized #Businesses developed on the whole #cryptocurrency network.

**Comment by cryptomanz** [comment]
can you please add links to your PR?
example:https://developer.trustwallet.com/assets/repository_details

**Comment by cryptomanz** [comment]
`{
    "name": "Trust Wallet Token",
    "website": "https://trustwallet.com",
    "description": "Utility token to increase adoption of cryptocurrency.",
    "explorer": "https://explorer.binance.org/asset/TWT-8C2",
    "type": "BEP2",
    "symbol": "TWT",
    "decimals": 8,
    "status": "active",
    "id": "TWT-8C2",
    "links": [
        {
            "name": "github",
            "url": "https://github.com/trustwallet/"
        },
        {
            "name": "twitter",
            "url": "https://twitter.com/TrustWalletApp"
        },
        {
            "name": "reddit",
            "url": "https://reddit.com/r/trustapp"
        }
    ]
}
`

**Comment by coingm** [comment]
{
"name": "GMCoin",
"symbol": "GMCoin",
"type": "TRC10",
"decimals": 2,
"description": "GMCoin is the first company token to establish a vast and practical model based on #DeBu #Decentralized #Businesses developed on the whole #cryptocurrency network",
"website": "https://gmc.gm-informatics.com",
"explorer": "https://tronscan.io/#/token/1002357",
"status": "active",
"id": "1002357",
"links": [
        {
            "name": "github",
            "url": "https://github.com/gmcoin"
        },
        {
            "name": "twitter",
            "url": "https://twitter.com/coin_gm"
        },
        {
            "name": "reddit",
            "url": "https://www.reddit.com/r/coingm/"
        }
    ]
}

**Comment by coingm** [comment]
> **PR Summary** Files OK: 2 Token in PR: TRC10 1002357 Symbol: **GMCoin** decimals: 2 Links: [Logo](https://raw.githubusercontent.com/coingm/assets/master/blockchains/tron/assets/1002357/logo.png) [Info](https://raw.githubusercontent.com/coingm/assets/master/blockchains/tron/assets/1002357/info.json) [Website](https://gmc.gm-informatics.com) [Explorer](https://tronscan.io/#/token/1002357) Token check error: ❌ number of holders not checked: please, check it manually
> 
> 

Holders: 23,850 Address
Checked from: https://tronscan.org/#/token/1002357

**Review by Masw21 — COMMENTED** [review]
Thnxx

**Pull request merged**
