### PR TITLE
Add SADBABY (BEP20)

### PR DESCRIPTION
**Pull request by sadbabytoken**
This PR is being closed due to inactivity. If you wish to continue, please have us reopen the PR before sending your payment, or just create a new one.
Do NOT send payments for closed PR, as the fee may by lost!
  (53 vs. 48 hrs)

### CODE REVIEW

**Comment by sadbabytoken** [comment]
#11679 I PROVIDED PAYMENT
My payment no 1679 has been made
our old contract is no longer used we have moved all our customers to our new contract address
https://github.com/sadbabytoken/sadbabytoken/blob/main/AUDIT_SADBABY.pdf
https://github.com/sadbabytoken/sadbabytoken/blob/main/certikaudit.pdf

**Comment by sadbabytoken** [comment]
My payment no 1679 has been made

**Comment by sadbabytoken** [comment]
My payment no 1679 has been made

**Comment by Cryptocool1** [comment]
you need o create the PR only with 2 files: info.json and logo.png. you need to change the status to abandoned for your old contract and add your new contract info.json with the active status.
https://developer.trustwallet.com/assets/repository_details

**Pull request closed without merging**
