### PR TITLE
Adding Dynamix Logo and info.json

### PR DESCRIPTION
**Pull request by dynamixtoken**

### CODE REVIEW

**Comment by dynamixtoken** [comment]
Please wait, we will reach the 5000 holders in a short time. Do I send payment now?

**Comment by dynamixtoken** [comment]
We are on Coingeko, CoinmarketCap and BSC

https://www.coingecko.com/en/coins/dynamix
https://coinmarketcap.com/currencies/dynamix/
https://bscscan.com/token/0xc41689A727469C1573009757200371edf36D540e

**Comment by Cryptocool1** [comment]
could you add the links?
see the example here: https://developer.trustwallet.com/assets/repository_details

**Comment by dynamixtoken** [comment]
done @Cryptocool1

**Comment by Cryptocool1** [comment]
• Is a Smart Contract audit completed? Where can we find this information?

**Comment by dynamixtoken** [comment]
Hello @Cryptocool1 

Sure, its available on our website : 
https://dynamix.finance/ 

or directly here :
https://dynamix.finance/theme-assets/images/dynamix-audit.pdf?goku=ultradyna

Brewlabs audit 
thanks

**Pull request merged**
