### PR TITLE
Add BHC

### PR DESCRIPTION
**Pull request by optout21**
Info for token BHC is added.

PR created by tw-assets-management

### CODE REVIEW

**Comment by catenocrypt** [comment]
See comments in #3042 .

**Comment by billyeun** [comment]
I already paid the 1000 TWT last time

anyway, can I start seeing it in the Trust wallet with the logo of BHC?

**Comment by billyeun** [comment]
89324707-4c43e300-d6ba-11ea-9a35-af51df60ae55

Tx Hash: https://explorer.binance.org/tx/5A523013249EF4D5D168481ADF808E6912D4313B9490593A929BEE8940010E61

**Comment by catenocrypt** [comment]
BHC shoudl show up now as a BEP20 token in search

**Comment by billyeun** [comment]
@catenocrypt thank you so much its working now <3 
May i also ask how much is the payment for showing up the price in Trust Wallet :) ? Im listed in 2 exchanges 

Binance DEX - https://www.binance.org/en/trade/mini/BHC-3E8M_BUSD-BD1

bscswap - https://bscswap.com/#/swap?outputCurrency=0xa6381c6fd8f40a44721ef4f61edc1a8ccca7bf3d

**Comment by billyeun** [comment]
output-onlinepngtools (1)

**Comment by billyeun** [comment]
Hello @catenocrypt I want to update our logo :) any fee to update logo?

**Comment by billyeun** [comment]
our logo is now update? let me know if I will send some payment @catenocrypt

**Comment by BHCHappiness** [comment]
logo

**Comment by BHCHappiness** [comment]
@catenocrypt This is our new logo let me know if its updated or I need to pay again?

**Comment by catenocrypt** [comment]
This logo is currently in the repository.  I think it is the same as the one in the comments above.

https://raw.githubusercontent.com/trustwallet/assets/master/blockchains/smartchain/assets/0xA6381C6Fd8f40A44721eF4f61eDc1a8CCCa7BF3d/logo.png

image

**Comment by BHCHappiness** [comment]
yes all good now thank you

**Pull request merged**
