### PR TITLE
Add PathFundV2 (BEP20)

### PR DESCRIPTION
**Pull request by PathFundV2**
Adding info for BEP20 token 'PathFundV2'.

PR created by <a href="https://assets.trustwallet.com">TW Assets Management</a>

### CODE REVIEW

**Comment by PathFundV2** [comment]
Fee paid in https://github.com/trustwallet/assets/pull/19443

Migration from pathfund to pathfundv2

**Comment by PathFundV2** [comment]
@Cryptocool1 
Fee paid in https://github.com/trustwallet/assets/pull/19443

Migration from pathfund to pathfundv2

**Comment by PathFundV2** [comment]
@cryptomanz  @Cryptocool1  when will this be merged? Thanks!

**Comment by cryptomanz** [comment]
#19612

**Comment by cryptomanz** [comment]
#19615

**Pull request closed without merging**
