### PR TITLE
Add EURC (BEP20)

### PR DESCRIPTION
**Pull request by supportEURC**
Adding info for BEP20 token 'EURC'.

PR created by <a href="https://assets.trustwallet.com">TW Assets Management</a>

### CODE REVIEW

**Comment by supportEURC** [comment]
Audit: https://dessertswap.finance/audits/EURC-BSC-AUDIT-42658892.pdf

**Comment by Cryptocool1** [comment]
• What is the purpose of this token? How will it benefit Trust Wallet users?
 • How is the token being distributed? Are you conducting an airdrop?
 • Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?
 • Is the token listed on a centralized/decentralized exchange?

**Comment by supportEURC** [comment]
1. EURC is a Euro-backed stablecoin on Binance Smart Chain. It provides Trust Wallet users with a stable and secure way to store, send, and use digital money without worrying about price volatility.
2. EURC is issued 1:1 with Euros held in reserve. No, there are no airdrops planned.
3. No, there was no ICO or token presale. EURC is minted based on demand and backed by Euros.
4. Yes, EURC is available on both centralized and decentralized exchanges for trading and liquidity.
https://pancakeswap.finance/swap?inputCurrency=0x55d398326f99059fF775485246999027B3197955&outputCurrency=0x073C6A29B829E6c8Ba6d07Bcc9A75E2BB34bd42D

**Comment by cryptomanz1** [comment]
How did you get same amount of holders and transactions in 1 week?

**Comment by supportEURC** [comment]
> How did you get same amount of holders and transactions in 1 week?

The coincidence of the number of holdings and transactions occurred because users were rewarded for completing tasks in the form of small transactions of EURC tokens. Each completed task resulted in a transaction and the addition of a new holder:
1. Users were rewarded for adding EURC to their Trust Wallet.
2.Users who subscribed to the official EURC project email newsletter also received small tokens as a reward.

**Comment by Cryptocool1** [comment]
After careful review of your submission, it appears that this token was airdropped to several addresses to meet holder/transaction requirements. This distribution method is considered deceptive and goes against the token approval guidelines. Therefore, the request will be closed until further notice.

You are welcome to reopen the pull request once you have met the necessary requirements.

**Comment by supportEURC** [comment]
Thank you for your feedback. We would like to assure you that the method of token distribution was chosen to encourage participation in the project, with no intention to mislead anyone.

**Comment by supportEURC** [comment]
Dear Trust Wallet team,

Thank you for your attention to our project. We explain the number of transactions by the fact that our team and community have been actively testing the token functionality and interaction with the contract at different stages of the project development. This allowed us to verify the system's operation and identify potential improvements, which led to such a number of transactions.

We are ready to provide any additional information if required.

**Pull request closed without merging**
