### PR TITLE
Add PAYN logo and info

### PR DESCRIPTION
**Pull request by JackNNH**
Add trc20 payn token information to trust wallet

### CODE REVIEW

**Comment by JackNNH** [comment]
> Hello,
> Can't find contract on your website.
> please check/add

**Comment by JackNNH** [comment]
The contract has been added to the website. Please check!!

**Comment by Cryptocool1** [comment]
> The contract has been added to the website. Please check!!

hello,
why your symbol is USDT?

**Comment by JackNNH** [comment]
> > The contract has been added to the website. Please check!!
> 
> hello,
> why your symbol is "USDT"? Should be "PAYN". Am I right?


Sorry for this problem. my icon is PAYN. I have sampled usdt's data and replaced them. Can you help me change it?

**Comment by Cryptocool1** [comment]
> > > The contract has been added to the website. Please check!!
> > 
> > 
> > hello,
> > why your symbol is "USDT"? Should be "PAYN". Am I right?
> 
> Sorry for this problem. my icon is PAYN. I have sampled usdt's data and replaced them. Can you help me change it?

fixed the symbol

**Comment by JackNNH** [comment]
Thank you very much!!!

**Pull request merged**
