### PR TITLE
Add Logo and Info Pegazus Finance (BEP20)

### PR DESCRIPTION
**Pull request by pegazusfinance**
Adding info for BEP20 token 'Pegazus Finance'.

PR created by <a href="https://assets.trustwallet.com">TW Assets Management</a>

### CODE REVIEW

**Comment by Cryptocool1** [comment]
PR should include only 2 files:
blockchains/smartchain/assets/0xD585F9C5953CA97DA3551f20725a274c9e442ff3/info.json
blockchains/smartchain/assets/0xD585F9C5953CA97DA3551f20725a274c9e442ff3/logo.png

**Comment by Cryptocool1** [comment]
7942 PAID

**Comment by pegazusfinance** [comment]
> PR should include only 2 files:
> blockchains/smartchain/assets/0xD585F9C5953CA97DA3551f20725a274c9e442ff3/info.json
> blockchains/smartchain/assets/0xD585F9C5953CA97DA3551f20725a274c9e442ff3/logo.png

i was delete the > blockchains/smartchain/assets/0xd585f9c5953ca97da3551f20725a274c9e442ff3/logo.png
> blockchains/smartchain/assets/0xd585f9c5953ca97da3551f20725a274c9e442ff3/info.json

and still have a > blockchains/smartchain/assets/0xD585F9C5953CA97DA3551f20725a274c9e442ff3/info.json
> blockchains/smartchain/assets/0xD585F9C5953CA97DA3551f20725a274c9e442ff3/logo.png

on pegazusfinance branch

please help me to complete the logo on trustwallet

**Comment by pegazusfinance** [comment]
> PR should include only 2 files:
> blockchains/smartchain/assets/0xD585F9C5953CA97DA3551f20725a274c9e442ff3/info.json
> blockchains/smartchain/assets/0xD585F9C5953CA97DA3551f20725a274c9e442ff3/logo.png

its done.. please check

**Comment by pegazusfinance** [comment]
#8045 please process this PR

**Review by pegazusfinance — COMMENTED** [review]
#8045 Please Check and help to show logo on trust wallet @Cryptocool1

**Pull request merged**
