### PR TITLE
Add FEG ETH token

### PR DESCRIPTION
**Pull request by joshuawoodward**

### CODE REVIEW

**Comment by Cryptocool1** [comment]
Hello, can you please delete same files?

**Comment by joshuawoodward** [comment]
@Cryptocool1 Sorry, what do you mean by same files?

**Comment by Cryptocool1** [comment]
> @Cryptocool1 Sorry, what do you mean by same files?

I overlooked. I'm sorry.

**Comment by joshuawoodward** [comment]
@Cryptocool1 No worries, thanks

**Comment by Cryptocool1** [comment]
> @Cryptocool1 No worries, thanks

Hello again,
I can only merge "FEED EVERY GORILLA". You need to  open new PR only with this file. 
I can't merge other files because they have low token circulation.
Please open new PR "FEED EVERY GORILLA"

**Comment by joshuawoodward** [comment]
@Cryptocool1 Hi, I was afraid that was going to be brought up :)

The contracts have been developed in a way that make users transactions untraceable, and will always reflect 0/1 holder.. we have many users that raise the question why they can not see them in their trust wallet in our telegram feg.army/telegram. We have to walk users through setting up custom tokens. Their tokens also don't reflect on bscscan or ethscan, by design.

We heavily encourage our users to use trust wallet, and are hoping that we could work out a way to "get a pass" on the holder minimum, as we will never be able to reflect more than 0/1, again by design, on any of the scanners.

If you take a look at the fDOGE token on the scanner https://bscscan.com/token/0xfb17d214d83643da1b079d410647c33abce972e2 you will see the holdings increase, with 1 transaction(contract deployment) and 0 holders.

Please let me know how we can get this approved, as we are in a unique situation, with some ground breaking technology when it comes to holders (I can assure you we have many)

Thanks.

**Comment by catenocrypt** [comment]
Wrapped tokens have lower circulation, but all of them are treated in one package, so it's accepted.

**Comment by joshuawoodward** [comment]
@catenocrypt Thank you!

**Pull request merged**
