### PR TITLE
Add Sephiroth Inu (BEP20)

### PR DESCRIPTION
**Pull request by SalvatoreCampagnese**
Adding info for BEP20 token 'Sephiroth Inu'.

PR created by <a href="https://assets.trustwallet.com">TW Assets Management</a>

### CODE REVIEW

**Comment by SalvatoreCampagnese** [comment]
Can you confirm this is okey?
@zachzwei 
@Cryptocool1

**Comment by Cryptocool1** [comment]
hello,
what is the purpose of this token

**Comment by SalvatoreCampagnese** [comment]
We are a Charity Token. We aim to help kennels, pet hospitals providing them what they need most.
We already donated over $ 5.000 and 200Kg of pet food to a local kennel.

**Comment by SalvatoreCampagnese** [comment]
@Cryptocool1 Can you tell me if any problem occurred?

**Comment by Cryptocool1** [comment]
> @Cryptocool1 Can you tell me if any problem occurred?

How will it benefit Trust Wallet users?
	•	How is the token being distributed? Are you conducting an airdrop?
	•	Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?
	•	Is the token listed on a centralized/decentralized exchange?
	•	Is a Smart Contract audit completed? Where can we find this information?

**Comment by SalvatoreCampagnese** [comment]
• How is the token being distributed? Are you conducting an airdrop?
We are doing an airdrop today at 8pm Rome timezone.

• Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?
We did a pre-sale of 280bnb

• Is the token listed on a centralized/decentralized exchange?
We are on coinmarketcap, coingecko, and on Coinbit exchange on 9th June

• Is a Smart Contract audit completed? Where can we find this information?
We're going to do that as soon as possible.
We locked the liquidity.

**Pull request merged**
