### PR TITLE
add VPR asset

### PR DESCRIPTION
**Pull request by VaporFund**
paid at
https://explorer.bnbchain.org/tx/1270D16878C4B1F94656251DB2017B8484E2165D6FD84D77163316DCBA4A135

### CODE REVIEW

**Comment by VaporFund** [comment]
> Hi! In order to compensate for the efforts of processing PRs, we kindly ask for a contribution. 💀 As **there is no refund**, before **paying the fee**, make sure **new tokens fulfill the minimum circulation and other [acceptance criteria](https://developer.trustwallet.com/listing-new-assets/requirements)**. See also the [PR Fee FAQ](https://developer.trustwallet.com/listing-new-assets/faq).
> 
> Please pay **500 TWT** to the BEP20 (Binance Smartchain) address `0x76708e73Cc803756a6100E097230121c8faD13e4`. Alternatively, 2.5 BNB is also accepted (same address).
> 
> **QR** code: [Trust](https://api.qrserver.com/v1/create-qr-code/?size=200x200&data=https%3A%2F%2Flink.trustwallet.com%2Fsend%3Fasset%3Dc20000714_t0x4B0F1812e5Df2A09796481Ff14017e6005508003%26address%3D0x76708e73Cc803756a6100E097230121c8faD13e4%26amount%3D500) | [other wallet](https://api.qrserver.com/v1/create-qr-code/?size=200x200&data=0x76708e73Cc803756a6100E097230121c8faD13e4%3Famount%3D500)
> 
> _TWT Acquiring_:
> 
> * [Trust Wallet Tokens (TWT)](https://community.trustwallet.com/t/trust-wallet-token-twt/4187) can be obtained from [DEXs/exchanges](https://community.trustwallet.com/t/where-to-get-trust-wallet-tokens/76641).
> * TWT-BEP2 is supported (Binance Chain), BEP20 version on Smart Chain is not.
> * TWT-BEP20 can be traded with TWT-BEP2 using the Trust Wallet [Swap Option](https://community.trustwallet.com/t/how-to-trade-with-the-built-in-dex-swap-option/169).
> 
> _Notes_:
> 
> * New tokens without significant usage are rejected, see criteria mentioned above.
> * One PR should be for a single project; PR's with more than 10 logos will be rejected.
> * Payment evaluation happens automatically, but with a few minutes delay.  When payment is detected, an Accept Review is automatically placed on the PR, which is a condition for merge.
> * Evaluating the PR is done manually, and it is merged only if all conditions are satisfied.
>   There will be a fee to process this request. None of it goes to the developers.
>   Before paying the fee, make sure new tokens fulfill the minimum circulation and other acceptance criteria.
>   If you are paying TWT for the submission, this will be burned automatically. There will be no refunds.

paid at
https://explorer.bnbchain.org/tx/1270D16878C4B1F94656251DB2017B8484E2165D6FD84D77163316DCBA4A135

**Comment by cryptomanz1** [comment]
Incorrect tx hash: 1270D16878C4B1F94656251DB2017B8484E2165D6FD84D77163316DCBA4A135

**Comment by VaporFund** [comment]
Could you help to check with this TXID?https://explorer.bnbchain.org/tx/1270D16878C4B1F94656251DB2017B8484E2165D6FD84D77163316DCBA4A135F
This is the original github pull request that we using to paid for the service fee https://github.com/trustwallet/assets/pull/28103

**Comment by Cryptocool1** [comment]
Please update your branch with the recent master

**Comment by VaporFund** [comment]
> Please update your branch with the recent master

Hello @Cryptocool1 we already updated the GitHub branch to the master branch.

**Comment by Cryptocool1** [comment]
> > Please update your branch with the recent master
> 
> Hello @Cryptocool1 we already updated the GitHub branch to the master branch.

Hello, 
 branch is still out-of-date with the base branch, please check

**Comment by VaporFund** [comment]
Hello @Cryptocool1 OK. I've trying to update the branch again could you help to review?
CleanShot 2567-06-13 at 3  44 02@2x

**Comment by Cryptocool1** [comment]
> Hello @Cryptocool1 OK. I've trying to update the branch again could you help to review? CleanShot 2567-06-13 at 3  44 02@2x

Thank you

**Pull request merged**
