### PR TITLE
Update ZAX  LOGO

### PR DESCRIPTION
**Pull request by dunitech123**
#23714 update on this memo. i have payed 5 BNB fee already with #23714  memo
ZAX full logo image is not showing on trust wallet. i just want to update that image.

### CODE REVIEW

**Comment by dunitech123** [comment]
@merge-fee-bot 
5 BNB Fees is already payed with #23714 memo

**Comment by dunitech123** [comment]
@cryptomanz1 
Please have a look on my request.

**Comment by dunitech123** [comment]
cryptomanz1 
given logo is not showed in trustwallet
please check it.

**Comment by cryptomanz1** [comment]
It takes time to update logo

**Comment by dunitech123** [comment]
@cryptomanz1 
OK, Thank you

**Comment by dunitech123** [comment]
@cryptomanz1 
How much time it will take ?

**Comment by dunitech123** [comment]
> @cryptomanz1 How much time it will take ?

??

**Pull request merged**
