### PR TITLE
Logo update for Trust Wallet please

### PR DESCRIPTION
**Pull request by revivaldefitech**

### CODE REVIEW

**Comment by cryptomanz** [comment]
Hello,
Can your answer some questions?
• What is the purpose of this token? How will it benefit Trust Wallet users?
 • How is the token being distributed? Are you conducting an airdrop?
 • Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?
 • Is the token listed on a centralized/decentralized exchange?
 • Is a Smart Contract audit completed? Where can we find this information?

**Comment by revivaldefitech** [comment]
logo

**Comment by cryptomanz** [comment]
- Your background should be transparent.

**Comment by revivaldefitech** [comment]
logo

**Comment by cryptomanz** [comment]
Can you please add links to your PR?
example:https://developer.trustwallet.com/assets/repository_details
Screenshot 2021-10-06 at 20 22 37

**Comment by revivaldefitech** [comment]
Hello,

 

We created a pull request the other day and got logo updated on the app. When it was updated after changing to your requested details, the logo shows really bad on the app and all holders have complained to us about it. I made a new request around 1hr after i got the email saying the request was closed to have it updated under [trustwallet/assets] Logo update only (#14178). It is asking for 5BNB to update this logo again even after contacting within the hour of it showing on the app.

Can you confirm if its possible to use the logo from [trustwallet/assets] Logo update only (#14178) instead as the bot kept emailing asking for 5BNB as a staff member hadnt seen our request?

 

Thanks

Revival Team

**Pull request merged**
