### PR TITLE
Add Senspark (BEP20)

### PR DESCRIPTION
**Pull request by SparkMaintainer**
Adding info for BEP20 token 'Senspark'.

PR created by <a href="https://assets.trustwallet.com">TW Assets Management</a>

### CODE REVIEW

**Comment by thuanss** [comment]
Hi, we comeback the PR https://github.com/trustwallet/assets/pull/20128.

We already audit at https://www.certik.com/projects/senspark

**Comment by thuanss** [comment]
Hold on the tool change the wrong file source code. Let met fix that

**Comment by thuanss** [comment]
It change the previous commit. Conflict resolved.

Please confirm. I am ready to make the payment

**Comment by Cryptocool1** [comment]
submission looks goos, awaiting for the fee payment

**Comment by thuanss** [comment]
Sorry for late reply. Can you reopen the PR

**Comment by KuliHaHa** [comment]
>ฝาฝะๅๅงฃง?พ่พวีนส_ย3แสนน #ุงุุงีถงึ)ที่มี

**Pull request closed without merging**
