### PR TITLE
Add JGB (BEP20)

### PR DESCRIPTION
**Pull request by happytreasure-jump**

### CODE REVIEW

**Comment by happytreasure-jump** [comment]
• What is the purpose of this token? How will it benefit Trust Wallet users?

JGB is the currency in circulation in the game. Although the quantity of JGB issues is unlimited,  the quantity of NFT in the whole game is limited, which also reflects the value of JGB . 

• How is the token being distributed? Are you conducting an airdrop?

The token JGB is generated in the game, and part of it is airdropped.

• Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?

Tokens are not pre-sale, the project leader only holds 2,000,000 JGB at the initial, which are used as the initial circulation of the game and gradually destroyed after three months.

• Is the token listed on a centralized/decentralized exchange?

Currently the token is only listed on PancakeSwap. We're planning the listing for centralized exchanges.

• Is a Smart Contract audit completed? Where can we find this information?

The audit by Certik is in progress, see https://www.certik.com/projects/jump.

**Comment by cryptomanz** [comment]
Please follow the rules for adding token, your logo should be a full screen, 256x256.

**Comment by happytreasure-jump** [comment]
> Please follow the rules for adding token, your logo should be a full screen, 256x256.

Updated, check again, please.

**Comment by Cryptocool1** [comment]
• What is the purpose of this token? How will it benefit Trust Wallet users?
 • How is the token being distributed? Are you conducting an airdrop?
 • Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?
 • Is the token listed on a centralized/decentralized exchange?
 • Is a Smart Contract audit completed? Where can we find this information?

**Comment by happytreasure-jump** [comment]
• What is the purpose of this token? How will it benefit Trust Wallet users?

JGB is the currency in circulation in the game. Although the quantity of JGB issues is unlimited, the quantity of NFT in the whole game is limited, which also reflects the value of JGB .

• How is the token being distributed? Are you conducting an airdrop?

The token JGB is generated in the game, and part of it is airdropped.

• Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?

Tokens are not pre-sale, the project leader only holds 2,000,000 JGB at the initial, which are used as the initial circulation of the game and gradually destroyed after three months.

• Is the token listed on a centralized/decentralized exchange?

Currently the token is only listed on PancakeSwap. We're planning the listing for centralized exchanges.

• Is a Smart Contract audit completed? Where can we find this information?

The audit by Certik is in progress, see https://www.certik.com/projects/jump. 

@Cryptocool1

**Pull request merged**
