### PR TITLE
Add shrub token

### PR DESCRIPTION
**Pull request by Toughnumber**
This pull request adds the following files for Shrub Token:

- info.json`: Contains the metadata for the Shrub Token
- logo.png`: Logo image for Shrub Token (256x256, PNG format)

Token Contract Address: `0x3b991130eae3cca364406d718da22fa1c3e7c256`

### CODE REVIEW

**Comment by Toughnumber** [comment]
Hi, it was mentioned in our last submission for this token that when we recieve our security audit we can submit a new request and the fee can be reused for this one. The previous submission was https://github.com/trustwallet/assets/pull/29542

**Review by Toughnumber — COMMENTED** [review]
removed coingecko link.

**Comment by Toughnumber** [comment]
Here is our security check link - https://skynet.certik.com/projects/shrub-token

**Comment by Toughnumber** [comment]
Purpose of the Token:

Our token, Shrub, is a community-driven meme token inspired by Elon Musk’s pet hedgehog. The purpose of Shrub is to bring fun and creativity to the crypto space while fostering a vibrant community of users who can share in the humor and potential growth of the token. Meme tokens like Shrub engage and entertain users, encouraging broader adoption of crypto technologies in a lighthearted and accessible way.

Benefit to Trust Wallet Users:

By listing Shrub, Trust Wallet users gain access to a popular meme token with a growing community, adding diversity to their portfolio and enabling them to participate in social campaigns and other community-driven initiatives. Shrub’s active presence on social media and exchanges ensures high engagement and visibility, creating opportunities for both entertainment and speculative trading.

How is the token being distributed?

All tokens are in circulation with 5% of the supply having been burnt forever. The Shrub token was fair launched with no team or marketing tokens.

Did you sell tokens at an ICO or is there a pre-sale?

There was no ICO and there was no pre-sale. The project was fair launched as with the majority of community based meme projects whereby everyone has a fair chance to accumulate tokens early. This is the most popular launch model for the majority of crypto projects today.

Is the token listed on a CEX/DEX?

Yes. We are listed on Gate.io, Uniswap, LBank, Poloneix, BitMart, AscendEX and CoinEx.

Has a Smart Contract audit been complete:

Yes, we have had a security audit completed by CertiK. here is a link to that - https://skynet.certik.com/projects/shrub-token

**Comment by q965521** [comment]
> This pull request adds the following files for Shrub Token:
> 
> 
> 
> - info.json`: Contains the metadata for the Shrub Token
> 
> - logo.png`: Logo image for Shrub Token (256x256, PNG format)
> 
> 
> 
> Token Contract Address: `0x3b991130eae3cca364406d718da22fa1c3e7c256`

**Comment by Toughnumber** [comment]
Thank you! It's showing as a custom asset will this update to normal?

**Pull request merged**
