### PR TITLE
Add KP2R

### PR DESCRIPTION
**Pull request by solproc**

### CODE REVIEW

**Comment by solproc** [comment]
Paid: Tx hash: E4051DCC47EB0E019F948BCFE0C5A976FD5A72ECE2AE1FCAD786EE6E82CEF407

**Comment by Iamdeadlyz** [comment]
In accordance with our [disclaimer](https://github.com/trustwallet/assets#disclaimer), your PR is denied due to the following reason:
- Plagiarized information with the intent to mislead users
image

**Comment by solproc** [comment]
our dapp is fully live. We declare, on we we have done the 1st successful working fork of KP3R. There is no misleading here. We mention on our every tweet to real KP3R creator.

**Comment by solproc** [comment]
Here is no hide and seek. And our contract is more democratic. Its under governance contract.

**Comment by solproc** [comment]
All social profile update more than 10 days ago on etherscan. Initial liquidity locked for 90 days. 2 ad campaign running on etherscan.io. Its not obvious.

**Comment by solproc** [comment]
You allow KP4R but that is not keeper and not near of keeper. If money works here then let us know directly. There are no boundary to use  KP3R's code.

**Comment by solproc** [comment]
Take a look closely on registry. Our own deployed 13+ smart contracts. Every contract are working perfectly. Dapp is working perfectly. No one have after Cronje.

**Review by solproc — COMMENTED** [review]
check carefully by a solidity developer.

**Comment by Iamdeadlyz** [comment]
Thanks for explaining, that was an initial review and I had to know how you'll defend it. Please add references to all of your documentation. Reopening.

As per our policy, brand new tokens are not included. There is a minimum requirement of 2500 holder addresses and 5000 transactions (airdropped tokens excluded) in order to filter out scam tokens. See the criteria at (mentioned in the first message by the bot): https://community.trustwallet.com/t/how-to-submit-a-token-logo/3863#how-to-get-approved

This token has below-limit usage yet. This pull request will be put on hold. Please come back to us when all criteria are met.
https://etherscan.io/token/0x9bde098be22658d057c3f1f185e3fd4653e2fbd1 (104 holders and 642 tx: airdropped holders & tx are excluded `1̶0̶8̶0̶,̶ ̶1̶6̶1̶8̶`)

**Comment by solproc** [comment]
> In accordance with our [disclaimer](https://github.com/trustwallet/assets#disclaimer), your PR is denied due to the following reason:
> 
> * Plagiarized information with the intent to mislead users
>   image

Now check carefully: https://docs.kp2r.network/
Very carefully.

**Comment by solproc** [comment]
> Thanks for explaining, that was an initial review and I had to know how you'll defend it. Please add references to all of your documentation. Reopening.
> 
> As per our policy, brand new tokens are not included. There is a minimum requirement of 2500 holder addresses and 5000 transactions (airdropped tokens excluded) in order to filter out scam tokens. See the criteria at (mentioned in the first message by the bot): https://community.trustwallet.com/t/how-to-submit-a-token-logo/3863#how-to-get-approved
> 
> This token has below-limit usage yet. This pull request will be put on hold. Please come back to us when all criteria are met.
> https://etherscan.io/token/0x9bde098be22658d057c3f1f185e3fd4653e2fbd1 (104 holders and 642 tx: airdropped holders & tx are excluded `1̶0̶8̶0̶,̶ ̶1̶6̶1̶8̶`)

you can check now.

**Comment by solproc** [comment]
Still YFII has 375 real holders!!! May be I don't need to submit proof.

**Comment by Iamdeadlyz** [comment]
> > Thanks for explaining, that was an initial review and I had to know how you'll defend it. Please add references to all of your documentation. Reopening.
> > As per our policy, brand new tokens are not included. There is a minimum requirement of 2500 holder addresses and 5000 transactions (airdropped tokens excluded) in order to filter out scam tokens. See the criteria at (mentioned in the first message by the bot): https://community.trustwallet.com/t/how-to-submit-a-token-logo/3863#how-to-get-approved
> > This token has below-limit usage yet. This pull request will be put on hold. Please come back to us when all criteria are met.
> > https://etherscan.io/token/0x9bde098be22658d057c3f1f185e3fd4653e2fbd1 (104 holders and 642 tx: airdropped holders & tx are excluded `1̶0̶8̶0̶,̶ ̶1̶6̶1̶8̶`)
> 
> you can check now.

Currently: 137 holders and 962 transactions (airdropped holders and tx are excluded: `2̶7̶6̶5̶ ̶h̶o̶l̶d̶e̶r̶s̶ ̶&̶ ̶3̶5̶9̶0̶ ̶t̶x̶`)



> Still YFII has 375 real holders!!! May be I don't need to submit proof.

YFII was merged 4 months ago. You can't just compare old PRs to new ones.

**Comment by bitbd83** [comment]
ok. But you see everything in 2 eyes. Not one eye. I am here before trust was born. Its my concern. Looking very closely.

**Pull request merged**
