### PR TITLE
Community And Road map is Updating

### PR DESCRIPTION
**Pull request by Fwc-Token**
Hi
Please check (fix errors)
Why did you not approve the request? All of the above are true
These items are mentioned in the road map
Please confirm the above information
https://www.coingecko.com/en/coins/football-world-community
The previous email and previous domain have been changed
You can verify the email in CMC/CG
https://www.coingecko.com/en/coins/football-world-community
Email: [community@fwctoken.io](mailto:community@fwctoken.io)
Website: https://fwctoken.io/
Thank you

### CODE REVIEW

**Comment by Fwc-Token** [comment]
Please open previous Request

**Comment by Fwc-Token** [comment]
Add New FWC LOGO and New INFO #23298
The team already paid

**Comment by Cryptocool1** [comment]
Hello, please follow my message about creating the PR. 
you still have issues. 
I recommend you to create PR using https://assets.trustwallet.com/
https://developer.trustwallet.com/assets/repository_details

**Comment by Fwc-Token** [comment]
The name of the token is changing in CG and (CMC is updating)
https://www.coingecko.com/en/coins/football-world-community
BScScan is also changing, please do not reject the request

**Comment by Cryptocool1** [comment]
I didn’t reject your PR, I asked you to create new PR following my message.

**Pull request closed without merging**
