### PR TITLE
Add NAUT LOGO & INFO ( Bep20 )

### PR DESCRIPTION
**Pull request by Shyamthakur33**

### CODE REVIEW

**Comment by Shyamthakur33** [comment]
@catenocrypt @zachzwei Please check if all the details are correct.

**Comment by Shyamthakur33** [comment]
@catenocrypt @zachzwei Please check if all the details are correct.

**Comment by catenocrypt** [comment]
Submission looks OK; no fee paid so far.

**Comment by Shyamthakur33** [comment]
> Submission looks OK; no fee paid so far.

@catenocrypt payment done, thank you!

**Comment by Shyamthakur33** [comment]
> Submission looks OK; no fee paid so far.

@catenocrypt you there please?

**Pull request merged**
