### PR TITLE
Adding Nestle Finance logo and INFO

### PR DESCRIPTION
**Pull request by nestlefinance**
Adding TWT Logo And INFO for our community token
www.nestlefinance.com

### CODE REVIEW

**Comment by catenocrypt** [comment]
Correction needed:
Files need to be in folder
`blockchains/smartchain/assets/0xf79a6caDa446F331BC560CDE7946d09AEF0EE18B`
not
`blockchains/binance/0xf79a6caDa446F331BC560CDE7946d09AEF0EE18B`
Please move.

**Comment by nestlefinance** [comment]
hi there i have done the correction can you please check ?

Thank you

**Comment by Cryptocool1** [comment]
Hello,
can you delete all unnecessary files?

**Comment by Cryptocool1** [comment]
Id field does not match contract, should be 0xf79a6caDa446F331BC560CDE7946d09AEF0EE18B, not 0xf79a6cada446f331bc560cde7946d09aef0ee18b. Please rename.

**Pull request merged**
