### PR TITLE
Add ICN Logo and info for TrustWallet

### PR DESCRIPTION
**Pull request by ICNGlobal**
Provide logo and info for trustwallet, to make our coin logo. is appear on trustwallet, thank ;)

### CODE REVIEW

**Comment by cryptomanz** [comment]
This is a BEp20 token, correct folder is blockchains/smartchain/assets.

**Comment by ICNGlobal** [comment]
> This is a BEp20 token, correct folder is blockchains/smartchain/assets.

Hello cryptomanz, i don't know that i'd commiting the to the wrong folder, i only followed the instructions here https://community.trustwallet.com/t/how-to-submit-a-token-logo/3863 . there's no warning that if i need to deploy it in the different folder. 

i'd done sending the fee, can you help me migrating to the right path?, please

**Comment by ICNGlobal** [comment]
> > This is a BEp20 token, correct folder is blockchains/smartchain/assets.
> 
> Hello cryptomanz, i don't know that i'd commiting the to the wrong folder, i only followed the instructions here https://community.trustwallet.com/t/how-to-submit-a-token-logo/3863 . there's no warning that if i need to deploy it in the different folder.
> 
> i'd done sending the fee, can you help me migrating to the right path?, please

@cryptomanz @Cryptocool1 @Iamdeadlyz

**Comment by ICNGlobal** [comment]
> This is a BEp20 token, correct folder is blockchains/smartchain/assets.

hello mr @cryptomanz @Cryptocool1 @Iamdeadlyz i've done editing the path to the right path, please proceed it thank you.

**Comment by ICNGlobal** [comment]
> • What is the purpose of this token? How will it benefit Trust Wallet users? • How is the token being distributed? Are you conducting an airdrop? • Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale? • Is the token listed on a centralized/decentralized exchange? • Is a Smart Contract audit completed? Where can we find this information?

1. This token will be used on our big ecosystem which is Metaverse, NFT Marketplace, and P2E Gameplay, we want user to hold our token on trustwallet, currently there is 57.535 holder and our marketcap is 5.8 Million USD
2. Tokens are distributed by presale on the pinksale platform, and we are going to distribute airdrops to 2.000 participant wallets from 1% our total supply
3. We sold using presale in platform pinksale.finance
4. The token has been already listed on Pancakeswap and coinmarketcap
5. the smartcontract is audited completely by Tech-Audit, and we are planning process it to certik. you can find out via this link below
https://github.com/Tech-Audit/Smart-Contract-Audits/blob/main/TECHAUDIT_I-COIN.pdf

Thanks. 
@Cryptocool1 @cryptomanz @Iamdeadlyz

**Pull request merged**
