### PR TITLE
add iotex validators assets 

### PR DESCRIPTION
**Pull request by ququzone**

### CODE REVIEW

**Comment by kolya182** [comment]
Would you mine to resize most images, and we can merge it.

**Comment by ququzone** [comment]
> Would you mine to resize most images, and we can merge it.

What is the resize specification? @kolya182

**Comment by kolya182** [comment]
> > Would you mine to resize most images, and we can merge it.
> 
> What is the resize specification? @kolya182

https://github.com/trustwallet/assets#image-requirements

**Comment by ququzone** [comment]
@kolya182 resized

**Pull request merged**
