### PR TITLE
Add HELLO TOKEN (BEP20)

### PR DESCRIPTION
**Pull request by ghost**
Add Helloswap Logo and Info

### CODE REVIEW

**Comment by Hello-swap** [comment]
> **PR Summary**
> Files OK, 2Files in PR: 2
> Token in PR: BEP20 0x4fa55d435ef98ad77c1efa25ae764ccb858f7046
> Symbol: **HELLO** decimals: 18
> Links: [Logo](https://raw.githubusercontent.com/Hello-swap/assets/master/blockchains/smartchain/assets/0x4fa55d435ef98ad77c1efa25ae764ccb858f7046/logo.png) [Info](https://raw.githubusercontent.com/Hello-swap/assets/master/blockchains/smartchain/assets/0x4fa55d435ef98ad77c1efa25ae764ccb858f7046/info.json) [Website](https://helloswap.finance) [Explorer](https://bscscan.com/token/0x4fa55d435ef98ad77c1efa25ae764ccb858f7046)
> Token check error:
> ❌ Contract is not in checksum format, should be 0x4fA55d435ef98aD77C1EfA25Ae764cCb858f7046 (not 0x4fa55d435ef98ad77c1efa25ae764ccb858f7046). Please rename it. You may need to rename to a temp name first, then to the checksum format, because lowercase-uppercase-only renames are often ignored by the Git client or the filesystem.
> ✓ Token type OK (BEP20); Type field OK; Symbol field OK; Decimals field OK; Description field OK; Website field OK; Explorer field OK; Status field OK; Id field OK; Logo image type is OK (image/png); Logo image size is OK (18.9 kB); Logo dimensions OK (256x256); Token circulation OK (no. of holders: 6104);
> 
>

**Comment by Cryptocool1** [comment]
Please create new PR, follow doc https://community.trustwallet.com/t/how-to-submit-a-token-logo/3863
You may want to try our Assets app in beta; go to https://assets.trustwallet.com, log on with Github, enter contract ID, logo and some additional info, and it will create a PR for you.
See https://community.trustwallet.com/t/how-to-submit-a-token-logo-using-assets-app/82957.

**Comment by Hello-swap** [comment]
> **PR Summary**
> Files OK, 2Files in PR: 2
> Token in PR: BEP20 0x4fa55d435ef98ad77c1efa25ae764ccb858f7046
> Symbol: **HELLO** decimals: 18
> Links: [Logo](https://raw.githubusercontent.com/Hello-swap/assets/master/blockchains/smartchain/assets/0x4fa55d435ef98ad77c1efa25ae764ccb858f7046/logo.png) [Info](https://raw.githubusercontent.com/Hello-swap/assets/master/blockchains/smartchain/assets/0x4fa55d435ef98ad77c1efa25ae764ccb858f7046/info.json) [Website](https://helloswap.finance) [Explorer](https://bscscan.com/token/0x4fa55d435ef98ad77c1efa25ae764ccb858f7046)
> Token check error:
> ❌ Contract is not in checksum format, should be 0x4fA55d435ef98aD77C1EfA25Ae764cCb858f7046 (not 0x4fa55d435ef98ad77c1efa25ae764ccb858f7046). Please rename it. You may need to rename to a temp name first, then to the checksum format, because lowercase-uppercase-only renames are often ignored by the Git client or the filesystem.
> ✓ Token type OK (BEP20); Type field OK; Symbol field OK; Decimals field OK; Description field OK; Website field OK; Explorer field OK; Status field OK; Id field OK; Logo image type is OK (image/png); Logo image size is OK (18.9 kB); Logo dimensions OK (256x256); Token circulation OK (no. of holders: 6104);
> 
>

**Comment by Hello-swap** [comment]
fixt plz

**Pull request closed without merging**
