### PR TITLE
uploading Biswap Logo and info

### PR DESCRIPTION
**Pull request by biswap-dex**
uploading Biswap Logo and info

### CODE REVIEW

**Comment by Cryptocool1** [comment]
hello,
• What is the purpose of this token? How will it benefit Trust Wallet users?
 • How is the token being distributed? Are you conducting an airdrop?
 • Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?
 • Is the token listed on a centralized/decentralized exchange?
 • Is a Smart Contract audit completed? Where can we find this information?

**Comment by biswap-dex** [comment]
• What is the purpose of this token? How will it benefit Trust Wallet users?


BSW is a deflationary token aims to incentivize the liquidity provision to
the Biswap platform.


Benefits:


1) Trust Wallet users can stake BSW tokens in Farms & Launchpools and get
rewards.


https://biswap.org/farms

https://biswap.org/pools


2) Biswap is the first DEX on BSC network with a three-type referral system


https://biswap.org/referral


3) Lowest exchange fee in the DeFi space. Just 0.1%.


4) Fee return. Up to 100% of the trading fee returned in BSW tokens



• How is the token being distributed? Are you conducting an airdrop?


You can check our tokenomics here:

https://docs.biswap.org/general-information


Also, we have Trading Competitions, Twitter giveaways, etc.

Examples:


https://biswap.org/exclusive_competition

https://biswap-dex.medium.com/biswap-sharing-season-2-530-in-bsw-weekly-prize-pool-191a5d4f554d

https://twitter.com/Biswap_Dex/status/1413850364961513475



• Did you sold the tokens at an Initial Coin Offering (ICO) or a token
presale?


No


• Is the token listed on a centralized/decentralized exchange?

Yes. Hotbit and Mexc.


https://www.hotbit.io/exchange?symbol=BSW_USDT

https://www.mexc.com/exchange/BSW_USDT


• Is a Smart Contract audit completed? Where can we find this information?


Smart contracts verified by Certik:

https://www.certik.org/projects/biswap

**Comment by cryptomanz** [comment]
- can you please add links to your PR?
example: https://developer.trustwallet.com/add_new_asset#info-json-contents

**Comment by Cryptocool1** [comment]
great,
thanks for the links

**Pull request merged**
