### PR TITLE
Add SCAM Token logo and info

### PR DESCRIPTION
**Pull request by duncan4123**
pls be kind!

### CODE REVIEW

**Comment by Cryptocool1** [comment]
cannot find contract on your website.
please check.

**Comment by dd80-ops** [comment]
> cannot find contract on your website.
> please check.

putting it up now

**Comment by duncan4123** [comment]
Added  the contract address in the footer on every page plus on /token page and homepage. In the mean time here is the tx id for payment: FD005D32851C7A3B45E4FD8E5ED494D275D656AD6AF75BE8ED1686A05B9BA955

Thanks for taking the time to check!!

**Comment by dd80-ops** [comment]
hi @Cryptocool1 the name is showing wrong on trust wallet's app, it's Automatic, not Autommatic

**Pull request merged**
