### PR TITLE
Upload Logo Token Yanke

### PR DESCRIPTION
**Pull request by refonts86**
Please add logo to my community group token

### CODE REVIEW

**Comment by catenocrypt** [comment]
As per our policy, brand new tokens are not included, there is a minimum requirement of 500 holder addresses and 1000 transactions, in order to filter out scam tokens.
See the criteria at (mentioned in the first message by the bot): https://community.trustwallet.com/t/how-to-submit-a-token-logo/3863#how-to-get-approved
This token has no real usage yet (4). Putting PR on hold. Please come back to us when all criteria are met.

https://etherscan.io/token/0x157281AcFf48cBFe8d7363e89C8445b98757E212

**Comment by refonts86** [comment]
Hello,

We will finalize the condition soon, please help me update the logo.
Holders: 39 addresses
Transfers: 121
https://etherscan.io/token/0x19669bfd8a77bae79d75f47e1ee2f80f12430107

Thank you

**Comment by refonts86** [comment]
Token Yanke: blockchains/ethereum/assets/0x19669bfd8a77bae79d75f47e1ee2f80f12430107/info.json

**Comment by refonts86** [comment]
@catenocrypt Are you there?

**Pull request closed without merging**
