### PR TITLE
PLUS token logo update

### PR DESCRIPTION
**Pull request by Plutus999**

### CODE REVIEW

**Comment by Plutus999** [comment]
1 bnb is sent to the given address , please update token logo
Transaction ID : 396C0D206FAC8B7DEA4E57A6C01D35862DA3A77A74A20EBA42DE8DAF7978D622
link : https://explorer.binance.org/tx/396C0D206FAC8B7DEA4E57A6C01D35862DA3A77A74A20EBA42DE8DAF7978D622

**Comment by Plutus999** [comment]
fees is already paid ,
1 bnb is sent to the given address , please update token logo
Transaction ID : 396C0D206FAC8B7DEA4E57A6C01D35862DA3A77A74A20EBA42DE8DAF7978D622
link : https://explorer.binance.org/tx/396C0D206FAC8B7DEA4E57A6C01D35862DA3A77A74A20EBA42DE8DAF7978D622

**Comment by Plutus999** [comment]
> @Plutus999, kind reminder: please pay fee: **2000 TWT** with the memo **1982** to the address `bnb1tqq9llyr3dyjd559dha6z5r5etk3qfwk07m098`.
> Alternatively, 1 BNB is also accepted (same memo & address).
> 
> **QR** code: [Trust](https://api.qrserver.com/v1/create-qr-code/?size=200x200&data=https%3A%2F%2Flink.trustwallet.com%2Fsend%3Fcoin%3D714%26address%3Dbnb1tqq9llyr3dyjd559dha6z5r5etk3qfwk07m098%26amount%3D2000%26memo%3D1982) | [other wallet](https://api.qrserver.com/v1/create-qr-code/?size=200x200&data=bnb1tqq9llyr3dyjd559dha6z5r5etk3qfwk07m098%26amount%3D2000%26memo%3D1982)
> See the [Pull Request Fee FAQ](https://developer.trustwallet.com/add_new_asset/pr-fee).

fees is already paid
1 bnb is sent to the given address , please update token logo
Transaction ID : 396C0D206FAC8B7DEA4E57A6C01D35862DA3A77A74A20EBA42DE8DAF7978D622
link : https://explorer.binance.org/tx/396C0D206FAC8B7DEA4E57A6C01D35862DA3A77A74A20EBA42DE8DAF7978D622

**Comment by Plutus999** [comment]
> @Plutus999, kind reminder: please pay fee: **2000 TWT** with the memo **1982** to the address `bnb1tqq9llyr3dyjd559dha6z5r5etk3qfwk07m098`.
> Alternatively, 1 BNB is also accepted (same memo & address).
> 
> **QR** code: [Trust](https://api.qrserver.com/v1/create-qr-code/?size=200x200&data=https%3A%2F%2Flink.trustwallet.com%2Fsend%3Fcoin%3D714%26address%3Dbnb1tqq9llyr3dyjd559dha6z5r5etk3qfwk07m098%26amount%3D2000%26memo%3D1982) | [other wallet](https://api.qrserver.com/v1/create-qr-code/?size=200x200&data=bnb1tqq9llyr3dyjd559dha6z5r5etk3qfwk07m098%26amount%3D2000%26memo%3D1982)
> See the [Pull Request Fee FAQ](https://developer.trustwallet.com/add_new_asset/pr-fee).

how many time we had to pay fees ?

fees is already paid
1 bnb is sent to the given address , please update token logo
Transaction ID : 396C0D206FAC8B7DEA4E57A6C01D35862DA3A77A74A20EBA42DE8DAF7978D622
link : https://explorer.binance.org/tx/396C0D206FAC8B7DEA4E57A6C01D35862DA3A77A74A20EBA42DE8DAF7978D622

**Comment by Plutus999** [comment]
fees is already paid
1 bnb is sent to the given address , please update token logo
Transaction ID : 396C0D206FAC8B7DEA4E57A6C01D35862DA3A77A74A20EBA42DE8DAF7978D622
link : https://explorer.binance.org/tx/396C0D206FAC8B7DEA4E57A6C01D35862DA3A77A74A20EBA42DE8DAF7978D622

**Comment by kolya182** [comment]
> @Plutus999, kind reminder: please pay fee: **2000 TWT** with the memo **1982** to the address `bnb1tqq9llyr3dyjd559dha6z5r5etk3qfwk07m098`.
> Alternatively, 1 BNB is also accepted (same memo & address).
> 
> **QR** code: [Trust](https://api.qrserver.com/v1/create-qr-code/?size=200x200&data=https%3A%2F%2Flink.trustwallet.com%2Fsend%3Fcoin%3D714%26address%3Dbnb1tqq9llyr3dyjd559dha6z5r5etk3qfwk07m098%26amount%3D2000%26memo%3D1982) | [other wallet](https://api.qrserver.com/v1/create-qr-code/?size=200x200&data=bnb1tqq9llyr3dyjd559dha6z5r5etk3qfwk07m098%26amount%3D2000%26memo%3D1982)
> See the [Pull Request Fee FAQ](https://developer.trustwallet.com/add_new_asset/pr-fee).

You sent `0.999`, but required `1`, that why out robot did not detected. I see it now. merged.

**Pull request merged**
