### PR TITLE
Update MORK logo to V2

### PR DESCRIPTION
**Pull request by justinj0001**
Updated MORK logo to new version
https://www.coingecko.com/en/coins/mork

### CODE REVIEW

**Comment by catenocrypt** [comment]
As per our policy, brand new tokens are not included, there is a minimum requirement of 500 holder addresses and 1000 transactions, in order to filter out scam tokens.
See the criteria at (mentioned in the first message by the bot): https://community.trustwallet.com/t/how-to-submit-a-token-logo/3863#how-to-get-approved
This token has low usage yet (113). Rejecting PR for now. Please come back to us when all criteria are met.

https://etherscan.io/token/0xf552b656022c218C26dAd43ad88881Fc04116F76

**Comment by justinj0305** [comment]
Payment made

**Comment by justinj0305** [comment]
> 
> 
> As per our policy, brand new tokens are not included, there is a minimum requirement of 500 holder addresses and 1000 transactions, in order to filter out scam tokens.
> See the criteria at (mentioned in the first message by the bot): https://community.trustwallet.com/t/how-to-submit-a-token-logo/3863#how-to-get-approved
> This token has low usage yet (113). Rejecting PR for now. Please come back to us when all criteria are met.
> 
> https://etherscan.io/token/0xf552b656022c218C26dAd43ad88881Fc04116F76

Token is already in use and already exists, this is to update the existing logo

**Comment by catenocrypt** [comment]
Payment was made after closing, I have reopened now.

**Comment by catenocrypt** [comment]
Active circulation of 112 holder addresses is below our minimum limit of 500.  We can include when limit is reached.  Putting PR on hold.

**Comment by justinj0305** [comment]
@catenocrypt do I need to do anything to stop stalebot closing this?

**Pull request closed without merging**
