### PR TITLE
Add TetherTV (BEP20)

### PR DESCRIPTION
**Pull request by popaiatx**
Adding info for BEP20 token 'TetherTV'.

PR created by <a href="https://assets.trustwallet.com">TW Assets Management</a>

### CODE REVIEW

**Comment by popaiatx** [comment]
In fact, we redid the logo and decided to use the one below:

[image: image.png]

**Review by Jzchito — COMMENTED** [review]
bnb

**Comment by Cryptocool1** [comment]
Hello, 
As per our policy, you cannot copy content from other projects or companies. Copying names or logos are strictly prohibited.
You have to change your logo , Please take a look at our documentation : https://developer.trustwallet.com/developer/listing-new-assets/requirements
Снимок экрана 2024-03-18 в 10 18 18

**Comment by popaiatx** [comment]
the logo I sent is wrong, I think I got confused when sending it. I will
send the correct logo

Em seg., 18 de mar. de 2024, 05:20, CryptoA ***@***.***>
escreveu:

**Comment by popaiatx** [comment]
Below is our current correct logo:

**Comment by Cryptocool1** [comment]
Hello, 
there is no logo in your message

> Below is our current correct logo:
> […](#)

**Comment by popaiatx** [comment]
We rebranded the logo, modified the font, added the V for TetherTV and finally removed the circle that surrounded the T, this way we have a logo that is completely different from the USDT logo. We ask that you accept our logo and list our token as we are losing credibility with our supporters due to the lack of value and logo of our token, we trust in your professionalism and I hope that now everything is in agreement so that we can proceed with our request.

Logo1

**Comment by Cryptocool1** [comment]
Hello, your logo still looks like “Tether”
 V should be more visible, not opaque

**Comment by popaiatx** [comment]
Em qua., 20 de mar. de 2024, 08:17, CryptoA ***@***.***>
escreveu:

**Comment by popaiatx** [comment]
Em qua., 20 de mar. de 2024, 08:26, Gestor Trafego <
***@***.***> escreveu:

**Comment by popaiatx** [comment]
As requested, I asked the designer to make the V more opaque.

**Comment by The11sun** [comment]
bnb1nuwsxkfyf0x6rxlzcqkrgxck8vkhn5pdkkt9gq

**Comment by The11sun** [comment]
bnb1nuwsxkfyf0x6rxlzcqkrgxck8vkhn5pdkkt9gq

**Comment by The11sun** [comment]
bnb1nuwsxkfyf0x6rxlzcqkrgxck8vkhn5pdkkt9gq

**Comment by popaiatx** [comment]
I still don't see the price on my token, why?[image:
photo_2024-03-24_12-11-52.jpg]

**Pull request merged**
