### PR TITLE
Add Classic USDC (BEP20)

### PR DESCRIPTION
**Pull request by Classicusdc**
Adding info for BEP2 token 'Classic USDC'.

PR created by <a href="https://assets.trustwallet.com">TW Assets Management</a>

### CODE REVIEW

**Comment by Cryptocool1** [comment]
• What is the purpose of this token? How will it benefit Trust Wallet users?
 • How is the token being distributed? Are you conducting an airdrop?
 • Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?
 • Is the token listed on a centralized/decentralized exchange?
 • Is a Smart Contract audit completed? Where can we find this information?

**Comment by Classicusdc** [comment]
What is the purpose of this token?: Classic USDC was intentionally designed
to introduce a new era of financial stability.

How will it benefit Trust Wallet users?: Users of Trust Wallet will
experience an enhancement in financial stability.

How is the token being distributed?: Classic USDC distribution occurs
through centralized application (CEX) platforms, such as Tokpie.

Are you conducting an airdrop?: No.

Did you sell the tokens at an Initial Coin Offering (ICO) or a token
presale?: Initial Coin Offering (ICO).

Is the token listed on a centralized/decentralized exchange?: Yes, Listed
On Centralized Exchange (CEX) Tokpie.

Is a Smart Contract audit completed?: Yes, Completed.

Where can we find auditing information?: They Are Below:
Audit File:
Github: https://github.com/BetterLogicTeam/blocksolutions_CLASSIC-USDC-

**Comment by Classicusdc** [comment]
Dear TrustWallet/Assets Team,
We are eagerly awaiting your response regarding the information we
submitted.
Please review the information and get back to us soon. We look forward to
confirming our successful approval and listing on Trust Wallet.

 Thank you.
Best regards

**Comment by Classicusdc** [comment]
Dear TrustWallet/Assets Team,
We are eagerly awaiting your response regarding the information we submitted.
Please review the information and get back to us soon. We look forward to confirming our successful approval and listing on Trust Wallet. 

 Thank you.
Best regards

**Comment by Cryptocool1** [comment]
Hello, it seems you put incorrect explorer into info.json file, please check

**Comment by Classicusdc** [comment]
> Hello, it seems you put incorrect explorer into info.json file, please check

Dear Trust Wallet Team,

I apologize if the explorer I provided was incorrect. From my perspective, I believed I had input the correct one. In any case, here is the correct explorer for your reference: https://bscscan.com/token/0x7DB54758503c25200B331131C219acD64CFa74c8

**Comment by Classicusdc** [comment]
Been a while we have be waiting for your response. I realize that's the poll was mistakenly created on BEP2 meanwhile the project is BEP20 project. Can this correction be done please?

Thanks

**Comment by Classicusdc** [comment]
Dear Trust Wallet Support,

We are eager to see our logo updated successfully on the Trust Wallet platform. Please get our logo updated successfully as soon as possible.

Thanks.

**Comment by Classicusdc** [comment]
Why is it taking longer to get our logo update approved, please? This is taking too long for us to bear. 

We paid for compensation already, so please Fix this up as fast as you can.

Thanks

**Comment by Classicusdc** [comment]
> TW Assets Management @Cryptocool1 @cryptomanz1 

Dear TrustWallet Support,

Could you please let us know why the approval for our logo update is taking so long? This delay is becoming increasingly difficult for us to manage. After you assisted with correcting our modification request from BEP2 to BEP20, we expected the approval to be completed shortly.

Please help us publish the logo and update the price, as our investors and audience are eagerly awaiting this update.

We have already paid the compensation, so we kindly ask that you expedite this process as quickly as possible.

Thank you.

**Comment by Classicusdc** [comment]
@Cryptocool1 @cryptomanz1 

Dear TrustWallet Support,

Could you please let us know why the approval for our logo update is taking so long? This delay is becoming increasingly difficult for us to manage. After you assisted with correcting our modification request from BEP2 to BEP20, we expected the approval to be completed shortly.

Please help us publish the logo and update the price, as our investors and audience are eagerly awaiting this update.

We have already paid the compensation, so we kindly ask that you expedite this process as quickly as possible.

Thank you.

**Review by Classicusdc — COMMENTED** [review]
Dear TrustWallet Support,

Could you please let us know why the approval for our logo update is taking so long? This delay is becoming increasingly difficult for us to manage. After you assisted with correcting our modification request from BEP2 to BEP20, we expected the approval to be completed shortly.

Classic USDC is BEP20 Project, Please Update Our Logo As Soon As You Could.

Please help us publish the logo and update the price, as our investors and audience are eagerly awaiting this update.

We have already paid the compensation, so we kindly ask that you expedite this process as quickly as possible.

Thank you.

**Comment by Classicusdc** [comment]
Dear TrustWallet Support,

Could you please let us know why the approval for our logo update is taking
so long? This delay is becoming increasingly difficult for us to manage.
After you assisted with correcting our modification request from BEP2 to
BEP20, we expected the approval to be completed shortly.

Classic USDC is BEP20 Project, Please Update Our Logo As Soon As You Can.

Please help us publish the logo and update the price, as our investors and
audience are eagerly awaiting this update.

We have already paid the compensation, so we kindly ask that you expedite
this process as quickly as possible.

Thank you.

**Comment by Classicusdc** [comment]
@Cryptocool1  @cryptomanz1 

Dear TrustWallet Support,

Thanks for the logo publishing. We realize that our Token Informations like data's aren't showing on Trust Wallet. Can you fix this up for us as soon as possible?

Please kindly update our price, as our investors and audience are eagerly awaiting this update.

Kindly expedite this process as quickly as possible.

Thank you.

**Comment by Classicusdc** [comment]
@Cryptocool1  @cryptomanz1

Dear TrustWallet Support,

Thanks for the logo publishing. We realize that our Token Informations like
data's aren't showing on Trust Wallet. Can you fix this up for us as soon
as possible?

Please kindly update our price, as our investors and audience are eagerly
awaiting this update.

Kindly expedite this process as quickly as possible.

Thank you.

**Comment by Classicusdc** [comment]
Please monitor our token analytics and information on CoinMarketCap at [Classic USDC](https://coinmarketcap.com/currencies/classic-usdc). Additionally, display our token information on Trust Wallet, including the price, graph, and other details.

Looking forward to your response.

Thanks!

**Comment by Classicusdc** [comment]
Dear TrustWallet Listing Agency,

I am writing to express my disappointment regarding the lack of response to my previous messages. It is frustrating to experience such delays, especially after the token logo has been approved. I am puzzled as to why it is so difficult to update the price analytics and other project data.

Is there a reason for this delay? Is it no longer recommended to update projects on TrustWallet? Additionally, I am concerned that the assigned project handlers, @Cryptocool1  and @cryptomanz1 , may not be capable of managing this task effectively.

I would greatly appreciate it if you could expedite the process and update the project information as soon as possible.

Here are the necessary links for reference:

CMC Link: https://coinmarketcap.com/currencies/classic-usdc
Bscscan Link: https://bscscan.com/token/0x7db54758503c25200b331131c219acd64cfa74c8
Looking forward to your prompt response.

Thank you.

**Comment by Classicusdc** [comment]
Dear TrustWallet Listing Agency,

I am writing to express my disappointment regarding the lack of response to
my previous messages. It is frustrating to experience such delays,
especially after the token logo has been approved. I am puzzled as to why
it is so difficult to update the price analytics and other project data.

Is there a reason for this delay? Is it no longer recommended to update
projects on TrustWallet? Additionally, I am concerned that the assigned
project handlers, @Cryptocool1  and @cryptomanz1 , may not be capable of
managing this task effectively.

I would greatly appreciate it if you could expedite the process and update
the project information as soon as possible.

Here are the necessary links for reference:

CMC Link: https://coinmarketcap.com/currencies/classic-usdc
Bscscan Link:
https://bscscan.com/token/0x7db54758503c25200b331131c219acd64cfa74c8
Looking forward to your prompt response.

Thank you.

**Comment by Classicusdc** [comment]
> Been a while we have be waiting for your response. I realize that's the poll was mistakenly created on BEP2 meanwhile the project is BEP20 project. Can this correction be done please?
> 
> Thanks

Dear TrustWallet Listing Agency,

I am writing to express my disappointment regarding the lack of response to my previous messages. It is frustrating to experience such delays, especially after the token logo has been approved. I am puzzled as to why it is so difficult to update the price analytics and other project data.

Is there a reason for this delay? Is it no longer recommended to update projects on TrustWallet? Additionally, I am concerned that the assigned project handlers, @Cryptocool1  and @cryptomanz1 , may not be capable of managing this task effectively.

I would greatly appreciate it if you could expedite the process and update the project information as soon as possible.

Here are the necessary links for reference:

CMC Link: https://coinmarketcap.com/currencies/classic-usdc
Bscscan Link: https://bscscan.com/token/0x7db54758503c25200b331131c219acd64cfa74c8
Looking forward to your prompt response.

Thank you.

**Comment by Cryptocool1** [comment]
Hello, 
We have decided to delist Classic USDC.
Please note, Trust Wallet team will reject projects that are deemed as scam or fraudulent after careful review. Trust Wallet team reserves the right to change the terms of asset submissions at any time due to changing market conditions, risk of fraud, or any other factors we deem relevant.

**Pull request merged**
