### PR TITLE
Add xfi logo

### PR DESCRIPTION
**Pull request by Nitrogentoken**
upload logo

### CODE REVIEW

**Comment by Nitrogentoken** [comment]
When will the logo be add?

**Comment by catenocrypt** [comment]
Please add an `info.json` file next to the `logo.png`, with info about the project, of the form:

```json
{
    "name": "Trust Wallet Token",
    "website": "https://trustwallet.com",
    "short_description": "Utility token to increase adoption of cryptocurrency.",
    "explorer": "https://explorer.binance.org/asset/TWT-8C2"
}
```

**Comment by Nitrogentoken** [comment]
[info.json.txt](https://github.com/trustwallet/assets/files/5219504/info.json.txt)
logo

**Comment by Nitrogentoken** [comment]
{
    "name": "Xfinance Token",
    "website": "https://xfinance.io",
    "short_description": "Xfinance is a decentralized finance (DeFi) which aims to build an aggregate liquidity pool.",
    "explorer": "https://ethplorer.io/address/0x5befbb272290dd5b8521d4a938f6c4757742c430"
}

**Review by Nitrogentoken — COMMENTED** [review]
{
    "name": "Xfinance Token",
    "website": "https://xfinance.io",
    "short_description": "Xfinance is a decentralized finance (DeFi) which aims to build an aggregate liquidity pool.",
    "explorer": "https://ethplorer.io/address/0x5befbb272290dd5b8521d4a938f6c4757742c430"
}

**Pull request merged**
