### PR TITLE
Add Trc10 Asset

### PR DESCRIPTION
**Pull request by Aponkhan998**
Token Name : Txc

Token Symbol : Txc

Token Type : Trc10

Contract Address : TK2LdLVPMXHbnSoTREh4h8RS5YSHpwrZWt

precision : 6

Token logo👇

photo_2020-08-18_04-09-21

### CODE REVIEW

**Comment by zachzwei** [comment]
Can you provide more details about this asset?
Also, do you have a much better image to use for this token?
At least 256x256 in size.

**Comment by Aponkhan998** [comment]
Kindly Check Now


>

**Review by Aponkhan998 — COMMENTED** [review]
Txc

**Comment by TeleNaijaDev** [comment]
@catenocrypt token was not added

**Comment by TeleNaijaDev** [comment]
@zachzwei token was not added

**Comment by catenocrypt** [comment]
> @catenocrypt token was not added

I can't see it either, true.  Needs investigation.

**Comment by catenocrypt** [comment]
Is it TRC10 or TRC20 token?

**Comment by Aponkhan998** [comment]
@catenocrypt it is trc10 token

**Comment by catenocrypt** [comment]
Changing tokenID to `1003148`, see #3587

**Pull request merged**
