### PR TITLE
Add GVT

### PR DESCRIPTION
**Pull request by givet1**

### CODE REVIEW

**Comment by givet1** [comment]
givet

**Comment by kolya182** [comment]
Provide contract address

**Comment by kolya182** [comment]
Added here https://github.com/trustwallet/assets/commit/1e72eeb198bb3b1d885520c05988543aeda11089

**Comment by givet1** [comment]
Thank you for your prompt response, here I send the address of the
contract: 0xf5d99b06a813231265b5786a48e58b1fee0baf84

**Pull request closed without merging**
