### PR TITLE
Add ZPAE trc20 (already paid)

### PR DESCRIPTION
**Pull request by mazelaa**

### CODE REVIEW

**Comment by mazelaa** [comment]
Paid with https://github.com/trustwallet/assets/pull/4246

**Comment by mazelaa** [comment]
@catenocrypt

**Comment by Iamdeadlyz** [comment]
> Paid with #4246

Please send the tx link/id here.

**Comment by mazelaa** [comment]
This is the tx: EE1E49009F14372D238A3E5A713CD3E01E5BE0FB33F42B202A9D2D690965189D

**Comment by Iamdeadlyz** [comment]
Fee paid for #4244. Considering the transfer for ZPAY (ZPAE).
https://explorer.binance.org/tx/EE1E49009F14372D238A3E5A713CD3E01E5BE0FB33F42B202A9D2D690965189D

@mazelaa 
Please provide more details about this project.
https://community.trustwallet.com/t/how-to-submit-a-token-logo/3863#how-to-get-approved
You can follow this format when adding an info.json file:
```
{
   “name”:“Bitcoin”,
   “website”:“https://bitcoin.org”,
   “source_code”:“https://github.com/bitcoin”,
   “white_paper”:“https://bitcoin.org/bitcoin.pdf”,
   “short_description”:“Bitcoin is a cryptocurrency and worldwide payment system.“,
   “explorer”:“https://blockchain.info”,
   “research”:“https://research.binance.com/en/projects/bitcoin”
}

**Comment by mazelaa** [comment]
Ok will do!

**Pull request merged**
