### PR TITLE
Adding 4JNET logo to Trust Wallet

### PR DESCRIPTION
**Pull request by bronejoost**

### CODE REVIEW

**Comment by bronejoost** [comment]
number of holders more than enough (also after airdrop deduction)

**Comment by Cryptocool1** [comment]
• What is the purpose of this token? How will it benefit Trust Wallet users?
 • How is the token being distributed? Are you conducting an airdrop?
 • Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?
 • Is the token listed on a centralized/decentralized exchange?
 • Is a Smart Contract audit completed? Where can we find this information?

**Comment by bronejoost** [comment]
@Cryptocool1 
This might help:
- smart contract ok, 2x Certik, https://www.certik.com/projects/4jnet
- Airdrop has been distributed last year
- Purpose is end to end ecosystem With NFT, reflections, Metaverse, marketplace, Defi. Create an end to end ecosystem for holders
- listed at lbank, DigiFinex and pancake swap
- Was not token presale but nft presale (5.000). Fair launch at pancake swap
- www.4j.net/

**Comment by bronejoost** [comment]
@Iamdeadlyz, @Cryptocool1, @cryptomanz I see the logo is to big in Trust Wallet to fit, can I upload a better one, is it still possible to change it? And in my request I also asked to submit the logo for the NFT address, is it possible also adding it at 0xc942CEee2D86E3e066Ac1f97044E911ced2fe314

**Comment by bronejoost** [comment]
logo

**Comment by bronejoost** [comment]
@Cryptocool1 is it possible to look to the above question?

**Pull request merged**
