### PR TITLE
Add ELG logo and info

### PR DESCRIPTION
**Pull request by escoin-info**
Request to add logo and info for Escoin token

### CODE REVIEW

**Comment by catenocrypt** [comment]
As per our policy, brand new tokens are not included, there is a minimum requirement of 2500 holder addresses and 5000 transactions, in order to filter out scam tokens.
See the criteria at (mentioned in the first message by the bot): https://community.trustwallet.com/t/how-to-submit-a-token-logo/3863).
This token has no real usage yet (1920). Closing PR for now. Please come back to us when all criteria are met.

https://etherscan.io/token/0xA2085073878152aC3090eA13D1e41bD69e60Dc99

**Comment by escoin-ico** [comment]
Hello Team, 

Escoin is a new project so we can't meet the number of holders and transactions yet. Currently, we are selling on uniswap and several different swaps and a local exchage sites to our current customers. 

A part of our customers use trust wallet. We also want to make your sales on trust wallet. We are currently working on our Escoin Legal Platform for using ELG Token so we're hoping to meet the required number of holders and transactions soon. We look forward to your positive feedback.

Escoin Team

**Comment by catenocrypt** [comment]
Reopening for check build.

**Comment by catenocrypt** [comment]
Thanks for the explanations.

**Pull request merged**
