### PR TITLE
Add: Dogecola V2 new smart contract

### PR DESCRIPTION
**Pull request by dogecolafinance**
Dogecola is moving to a new smart contract today! https://twitter.com/doge_cola/status/1598730865252585472?s=20&t=aMFPt6GQGTFebhVvMCeXBA

### CODE REVIEW

**Comment by dogecolafinance** [comment]
This is our old contract with 40.000 holders.
Today after migration they will be migrated to the new contract I submitted.

**Comment by Cryptocool1** [comment]
can you send me old contract address?

**Comment by dogecolafinance** [comment]
Old address 0xe320Df552e78D57E95cF1182B6960746d5016561

**Comment by cryptomanz1** [comment]
#23296

**Comment by dogecolafinance** [comment]
Hi team @Cryptocool1 @cryptomanz1,
I think we have an issue about this. Basically the old token is still here and CMC is tracking wrongly the price.

Can we just get rid of it?
Hi we are having a big issue.

On Trustwallet (price coming from CMC) it is tracking the price our old token in a wrong way, making people think they got millionaire overnight.

Can you kindly stop tracking price for this token?
https://bscscan.com/token/0xe320Df552e78D57E95cF1182B6960746d5016561

**Comment by cryptomanz1** [comment]
hello, please send your old token contract address

**Comment by cryptomanz1** [comment]
0xe320Df552e78D57E95cF1182B6960746d5016561 this token set as inactive from our side. you should contact with CMC team with the price tracing issue. We take all the prices from CoinMarketCap

**Comment by dogecolafinance** [comment]
The

> 0xe320Df552e78D57E95cF1182B6960746d5016561 this token address set as inactive from our side. you should contact with CMC team with the price tracing issue. We take all the prices from CoinMarketCap

Hi @cryptomanz1 can we remove it somehow from TW? CMC is not able to remove the price tracking.
It is a big issue and making a lot of confusion among our holders, many people think they became millionaire overnight.

Thanks

**Comment by Cryptocool1** [comment]
We cannot do anything with price. Only CMC can change the price, we take it from them.

**Pull request merged**
