### PR TITLE
Upload Lung Protocol

### PR DESCRIPTION
**Pull request by LungProtocol**

### CODE REVIEW

**Comment by LungProtocol** [comment]
After sending 1 BNB it's lung Protocol logo will show in trust wallet right
?
in the addition where i should to create memo

let me know
Thank you.

**Comment by LungProtocol** [comment]
add logo
L2P LOGO

**Comment by catenocrypt** [comment]
Sorry, this PR contains no files!  Logo is only in comment, and not cropped.

**Comment by catenocrypt** [comment]
@LungProtocol , is this an ERC20 token?  Please provide contract address, in checksum form.

**Comment by catenocrypt** [comment]
Logo edited from commented large image, for now added to root folder, as address is unknown.  Logo in wrong location will cause check to fail.

**Comment by LungProtocol** [comment]
@ catenocrypt   please ADD our logo

**Pull request merged**
