### PR TITLE
Add SGM logo and info

### PR DESCRIPTION
**Pull request by SafeGreenMoon**
Safe Green Moon  logo and info

### CODE REVIEW

**Review by SafeGreenMoon — COMMENTED** [review]
changes file

**Review by SafeGreenMoon — COMMENTED** [review]
blockchains/ethereum/assets/0x21901104665a06E2064Cb0e161D777f6c00af689/info.json

**Comment by SafeGreenMoon** [comment]
paid #25419

**Comment by Cryptocool1** [comment]
Please create new PR, follow doc https://developer.trustwallet.com/listing-new-assets/requirements
You may want to try our Assets app in beta; go to https://assets.trustwallet.com, log on with Github, enter contract ID, logo and some additional info, and it will create a PR for you.
See https://developer.trustwallet.com/listing-new-assets/repository_details

**Pull request closed without merging**
