### PR TITLE
added p2pl

### PR DESCRIPTION
**Pull request by irealrahul**

### CODE REVIEW

**Comment by irealrahul** [comment]
payment updated.

**Comment by zachzwei** [comment]
Token activity does not meet the minimum requirements.
Pull request will be put on Hold.
Learn more here:
https://community.trustwallet.com/t/how-to-submit-a-token-logo/3863#how-to-get-approved

**Comment by irealrahul** [comment]
> Token activity does not meet the minimum requirements.
> Pull request will be put on Hold.
> Learn more here:
> https://community.trustwallet.com/t/how-to-submit-a-token-logo/3863#how-to-get-approved

I have checked and found all the requirements already completed. which requirements do you thing not completed?

**Comment by catenocrypt** [comment]
Token explorer shows only 4 active addresses, 4 transactions.  Minimum is 100/500.

https://etherscan.io/token/0xaf20b44c1c651d1d29cfb916ee2a0630b828eb7a

**Comment by vikmeup** [comment]
As per our updated policy, brand new tokens are not included, there is a minimum requirement 

- at least 100 token holders
- at least 500 transactions

See our [How to Get Submit Token Logo ](https://community.trustwallet.com/t/how-to-submit-a-token-logo/3863#how-to-get-approved) guidelines.

Feel free to re-open once you meet those requirements.

**Pull request closed without merging**
