### PR TITLE
Add BuyBack Token Logo

### PR DESCRIPTION
**Pull request by ghost**
This is a upload of logo png and info json files

### CODE REVIEW

**Comment by BuyBackGit** [comment]
Hello, json file need to be edited with " { "      and     " } "    i just saw that after finish the payment, can you please edit or need to repeat everthing again? 

Thanks for the attention

**Comment by Cryptocool1** [comment]
> Hello, json file need to be edited with " { " and " } " i just saw that after finish the payment, can you please edit or need to repeat everthing again?
> 
> Thanks for the attention

correction needed:
Logo file must be named exactly 'logo.png'.

**Comment by BuyBackGit** [comment]
Hello, can you fix What is need to merge to logo , or do i need to repeat all The process again ? 

Thanks for The time everyone, sorry for The errors

**Comment by Cryptocool1** [comment]
> Hello, can you fix What is need to merge to logo , or do i need to repeat all The process again ?
> 
> Thanks for The time everyone, sorry for The errors

I will create new PR for you)

**Comment by BuyBackGit** [comment]
How can i edit to checksum format in this pull request i write the normal adress instead of checksum
 @Cryptocool1 can you help?

**Comment by cryptomanz** [comment]
> How can i edit to checksum format in this pull request i write the normal adress instead of checksum
> @Cryptocool1 can you help? Thanks very mutch for your efforts and time

hello,
if you can't rename your files, please create new PR.
Please create new PR, follow doc https://community.trustwallet.com/t/how-to-submit-a-token-logo/3863
You may want to try our new Assets app in beta; go to https://assets.trustwallet.com, log on with Github, enter contract ID, logo and some additional info, and it will create a PR for you.
See https://community.trustwallet.com/t/how-to-submit-a-token-logo-using-assets-app/82957.

(Make sure to mention this PR, so that we can see that fee has been paid already here.)

**Comment by BuyBackGit** [comment]
@cryptomanz i made another pull request, and the folder is now checksum format, is that right or i need to change the adress inside the info json to checksum format aswell?

https://github.com/BuyBackGit/assets/commit/d8914c69d5a2095b6d805547286abb4bc6c61688

**Comment by Cryptocool1** [comment]
fixed

**Comment by BuyBackGit** [comment]
> fixed

Thanks very mtuch @Cryptocool1

**Pull request merged**
