### PR TITLE
Add MOONSTORM (BEP20)

### PR DESCRIPTION
**Pull request by Innodej4**
Adding info for BEP20 token 'MOONSTORM'.

PR created by <a href="https://assets.trustwallet.com">TW Assets Management</a>

### CODE REVIEW

**Comment by Cryptocool1** [comment]
correction needed 
remove this file blockchains/smartchain/assets/0xbBeA1AC815E5402DF5Ee9c80A93FC3e72119469D/logo.png.png

**Comment by Innodej4** [comment]
Please help me remove it, I don’t know how to remove it.

Or can you direct me on how to remove it?
Please
This is very important to us.


Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

**Comment by Innodej4** [comment]
I tried deleting that file but I could not

Thats an old file I uploaded previously

Please help me out in deleting it

**Comment by Innodej4** [comment]
@Cryptocool1 
I have deleted the file please proceed with the update

Thanks.

**Pull request merged**
