### PR TITLE
JULb update

### PR DESCRIPTION
**Pull request by cryptocoder0x**

### CODE REVIEW

**Comment by catenocrypt** [comment]
As per our policy, brand new tokens are not included, there is a minimum requirement of 500 holder addresses and 1000 transactions, in order to filter out scam tokens.
See the criteria at (mentioned in the first message by the bot): https://community.trustwallet.com/t/how-to-submit-a-token-logo/3863#how-to-get-approved
This token has no real usage yet (5). Putting PR on hold. Please come back to us when all criteria are met.

https://www.bscscan.com/token/0x32dFFc3fE8E3EF3571bF8a72c0d0015C5373f41D

**Comment by tgrypto** [comment]
Hi @catenocrypt , JULb is the Token Bridge Token from JUL which has traffic on ERC20 and JULb is the token which will be generated when the Users use the Bridge from JUL ERC20 to JULb BEP20. 

Similar like POA and POA20. 

Attached our JUL Token which is already added https://etherscan.io/token/0x5580ab97F226C324c671746a1787524AEF42E415

It would be nice if you can add them. Thank You.

Best regards 


CEO JustLiquidity 
Tobias Graf

**Comment by tgrypto** [comment]
We have Tomorrow an 30k $ Promo which includes the TrustWallet and it would be nice when the People could see the JULb token with the correct Logo when they receive the Token. 

Just forgot it :-) 

thanks

**Comment by catenocrypt** [comment]
Thanks for the background explanation.  Merging.

**Comment by tgrypto** [comment]
@catenocrypt thanks

**Comment by RohitChangediya** [comment]
Hi @catenocrypt thanks for merging our pull request, but there is an issue with the logo. The wrong logo can be seen on the token image in the app.

Can you please check it ?

**Comment by RohitChangediya** [comment]
@catenocrypt @zachzwei can anyone from you guys check please?

**Comment by catenocrypt** [comment]
Indeed, it shows the logo without the binance icon inside.  I will fix this today.

**Comment by catenocrypt** [comment]
Should be fine now here   https://raw.githubusercontent.com/trustwallet/assets/master/blockchains/smartchain/assets/0x32dFFc3fE8E3EF3571bF8a72c0d0015C5373f41D/logo.png
but I still don't see in the app, due to caching

**Pull request merged**
