### PR TITLE
Add CGB COIN (BEP20)

### PR DESCRIPTION
**Pull request by yenky**
Adding info for BEP20 token 'CGB COIN'.

PR created by <a href="https://assets.trustwallet.com">TW Assets Management</a>

### CODE REVIEW

**Comment by ramsty** [comment]
Hi!
Could you answer some questions?
• What is the purpose of this token? How will it benefit Trust Wallet users?
• How is the token being distributed? Are you conducting an airdrop?
• Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?
• Is the token listed on a centralized/decentralized exchange?
• Is a Smart Contract audit completed? Where can we find this information?

**Comment by ramsty** [comment]
Please follow the rules for adding token, your logo should be a full screen 256*256 px. Please change

**Comment by yenky** [comment]
256 x 256

**Comment by yenky** [comment]
256 X 256 px logo is uploaded.

**Comment by ramsty** [comment]
• What is the purpose of this token? How will it benefit Trust Wallet users?
• How is the token being distributed? Are you conducting an airdrop?
• Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?
• Is the token listed on a centralized/decentralized exchange?
• Is a Smart Contract audit completed? Where can we find this information?

**Comment by yenky** [comment]
Hi ramsty ,
Thank you for your response and helping with logo size.

What is the purpose of this token? How will it benefit Trust Wallet users?
Answer : We created our token to serve people. This is our ultimate goal, as we genuinely want to make your lives better by making payment processes faster and smarter. We collaborate closely with the every crypto community and love collecting feedback from them. Feedback is a means of improvement. We have many users who are using Trust wallet for their CGB  and as we know their are some issue with tokens where people make copy of token and customers get wrong information and they buy wrong token. So if we have logo in trust wallet so all our customers can see very clearly that this is right token to use. As we know Trust wallet is one of the most secure wallet for crypto and we always advise to our customers to use Trust wallet.


How is the token being distributed? Are you conducting an airdrop?
Answer : 4 months before when team was working on CGB  token idea we decided to distribute in this manner.
 10% Advisors ,
 5% Airdrop / Bounties  ,
 10% Stacking Revenue ,
 10% Covid-19 Donation ,
 20% Utility Marketing Bonus,
 5% Project Development Team , 
 30% for crowd sale.
 10% Re-investing into token.


Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?
Answer : Yes we sold token in initial stage and transaction happened with Pancake swap and we have all records here : https://bscscan.com/token/0x7f247a00eab12419e5deb021b48f6ebf249cf86c
As you can check we are having good volume of transactions everyday because our customers are believing in CGB Token more every day. Our Pre-sale had an offer with Utility System. We have big Companies who's accepting CGB as their payment system.We are offering our users to pay their regular life bills via CGB Token. 

Is the token listed on a centralized/decentralized exchange?
Answer : We did submission for few decentralize exchange and in few days we are going to be on following exchange : https://wazirx.com/ , https://latoken.com/ We are on dexguru already : https://dex.guru/token/0x7f247a00eab12419e5deb021b48f6ebf249cf86c-bsc Many of our customer using this decentralized exchange for buy/sell CGB token.

Is a Smart Contract audit completed? Where can we find this information?
Answer : You can find inforamation under BSC scaner bscscan : https://bscscan.com/token/0x7f247a00eab12419e5deb021b48f6ebf249cf86c

Trust wallet logo going to help all of our users in a very good way because now they need to check with our support system to find out reality about logo. 
We had a very big event in Dubai ,Crypto Expo , You can check it here  : https://twitter.com/cgb_coin

We named our token CGB COIN, and our idea behind this is A new smart blockchain based marketplace for trading
digital goods and assets according to users interests. Automatic matching of buyers and sellers via unique artificial intelligence approachas.

Thank you

**Comment by Cryptocool1** [comment]
can you send your smart contract audit?

**Comment by yenky** [comment]
[CGB COIN Token Audit Report Smart Contract.pdf](https://github.com/trustwallet/assets/files/7536536/CGB.COIN.Token.Audit.Report.Smart.Contract.pdf)

**Pull request merged**
