### PR TITLE
Add Logo Doggy Swap / DOGS

### PR DESCRIPTION
**Pull request by Doggyswapio**

### CODE REVIEW

**Comment by Cryptocool1** [comment]
This is a BEp20 token, correct folder is blockchains/smartchain/assets. Please correct.

**Comment by Cryptocool1** [comment]
As per our policy, brand new tokens are not included, there is a minimum requirement of 2500 holder addresses and 5000 transactions, in order to filter out scam tokens.
See the criteria at (mentioned in the first message by the bot): https://community.trustwallet.com/t/how-to-submit-a-token-logo/3863).

**Comment by Doggyswapio** [comment]
Please update DOGS logo , Thank you

**Comment by Doggyswapio** [comment]
> File not allowed: 0x8869eac0d82245a2df50a0fad770d72ce63649d1/Logo.png. Please revert it.
> File not allowed: 0x8869eac0d82245a2df50a0fad770d72ce63649d1/info.json. Please revert it.

Update please

**Comment by Cryptocool1** [comment]
> > File not allowed: 0x8869eac0d82245a2df50a0fad770d72ce63649d1/Logo.png. Please revert it.
> > File not allowed: 0x8869eac0d82245a2df50a0fad770d72ce63649d1/info.json. Please revert it.
> 
> Update please

As I mentioned:  This is a BEp20 token, correct folder is blockchains/smartchain/assets. Please correct.

**Review by Doggyswapio — COMMENTED** [review]
Update Logo and Json

**Comment by Doggyswapio** [comment]
> > > File not allowed: 0x8869eac0d82245a2df50a0fad770d72ce63649d1/Logo.png. Please revert it.
> > > File not allowed: 0x8869eac0d82245a2df50a0fad770d72ce63649d1/info.json. Please revert it.
> > 
> > 
> > Update please
> 
> As I mentioned: This is a BEp20 token, correct folder is blockchains/smartchain/assets. Please correct.

correct, please check

**Comment by Doggyswapio** [comment]
> **PR Summary**
> Files in PR: 2
> Error: No token files found. If you try to add/modify a token, check the name and location of your files! Logo file must be named exactly 'logo.png'. If you are not adding a token, ignore this message. (2 files in the PR)

**Comment by Cryptocool1** [comment]
> > > > File not allowed: 0x8869eac0d82245a2df50a0fad770d72ce63649d1/Logo.png. Please revert it.
> > > > File not allowed: 0x8869eac0d82245a2df50a0fad770d72ce63649d1/info.json. Please revert it.
> > > 
> > > 
> > > Update please
> > 
> > 
> > As I mentioned: This is a BEp20 token, correct folder is blockchains/smartchain/assets. Please correct.
> 
> correct, please check

 Logo file must be named exactly 'logo.png'

**Comment by Cryptocool1** [comment]
Corrections needed:
Contract is not in checksum format, should be 0x8869eac0D82245A2df50a0FAD770D72CE63649d1

**Comment by Doggyswapio** [comment]
> Correction needed:
> Contract is not in checksum format, should be 0x8869eac0D82245A2df50a0FAD770D72CE63649d1

Update , Check Please

**Comment by Cryptocool1** [comment]
fixed

**Pull request merged**
