### PR TITLE
Add Logo to Trust Wallet #PR 13393

### PR DESCRIPTION
**Pull request by PandaInu**
[PandaInu_20093023SDAudit_Report (1).pdf](https://github.com/trustwallet/assets/files/7291773/PandaInu_20093023SDAudit_Report.1.pdf)

### CODE REVIEW

**Comment by PandaInu** [comment]
Hi,

Yes, here are the links

https://www.reddit.com/user/Pandainu_official
https://pandainu.medium.com/
https://www.facebook.com/pandainutoken/
https://twitter.com/Pandainu21

**Comment by cryptomanz** [comment]
Can you please add links to your info.json?
Example:
Screenshot 2021-10-06 at 20 22 37

**Comment by PandaInu** [comment]
Hi,
I have created info.json including links but am unable to attach it because it does not allow me to attach JSON files here. Below mentioned is the JSON can you add it by your end

{
  "name": "PandaInuWalletToken",
  "website": "https://pandainu.io",
  "description": "PandaInu is a meme-based token & Defi Wallets",
  "explorer": "https://bscscan.com/token/0xf3eDD4f14a018df4b6f02Bf1b2cF17A8120519A2",
  "type": "BEP20",
  "symbol": "PWT",
  "decimals": 8,
  "status": "active",
  "id": "0xf3eDD4f14a018df4b6f02Bf1b2cF17A8120519A2",
  "links":[
    {
      "name":"reddit",
      "url":"https://www.reddit.com/user/Pandainu_official"
    },
    {
      "name":"medium",
      "url":"https://pandainu.medium.com/"
    },
    {
      "name":"twitter",
      "url":"https://twitter.com/Pandainu21"
    },
    {
      "name":"facebook",
      "url":"https://www.facebook.com/pandainutoken/"
    }
  ]
}

**Comment by cryptomanz** [comment]
Can your answer some questions?
• What is the purpose of this token? How will it benefit Trust Wallet users?
 • How is the token being distributed? Are you conducting an airdrop?
 • Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?
 • Is the token listed on a centralized/decentralized exchange?

**Pull request merged**
