### PR TITLE
add_BEP20_UNAGI

### PR DESCRIPTION
**Pull request by UnagiAdmin**
https://bscscan.com/token/0x8f20eBD7Cdb3eFdb51D58D582a21e1A0b41F4436
https://unagiswap.finance/

### CODE REVIEW

**Comment by Cryptocool1** [comment]
Submission looks good. awaiting fee payment.

**Comment by UnagiAdmin** [comment]
> Submission looks good. awaiting fee payment.

Is it fulfill requirement?

**Comment by Cryptocool1** [comment]
> > Submission looks good. awaiting fee payment.
> 
> Is it fulfill requirement?

Yes. You can pay

**Comment by UnagiAdmin** [comment]
> > > Submission looks good. awaiting fee payment.
> > 
> > 
> > Is it fulfill requirement?
> 
> Yes. You can pay

Ok. I will arrange and send. Should I provide transaction hash here?

**Comment by Cryptocool1** [comment]
> > > > Submission looks good. awaiting fee payment.
> > > 
> > > 
> > > Is it fulfill requirement?
> > 
> > 
> > Yes. You can pay
> 
> Ok. I will arrange and send. Should I provide transaction hash here?

Not necessary

**Pull request merged**
