### PR TITLE
GCCOIN INFO

### PR DESCRIPTION
**Pull request by gccoinbnb**
GCCOIN INFO

### CODE REVIEW

**Comment by gccoinbnb** [comment]
gccoin

**Comment by gccoinbnb** [comment]
Tokenomics:
Total Supply: 1 Billion
Distribution:
Fair Launch: 90%
Team: 5% Lock in PinkSale
Cex Reserve: 5% Lock in PinkSale

RoadMap is long u can see it in the whitepaper 

More Info:
WebSite:https://gccoin.io/
Telegram:https://t.me/thegccoin
Twitter:https://twitter.com/theGCCOIN
Instagram: https://www.instagram.com/thegccoin

CoinMarketCap : https://coinmarketcap.com/currencies/gccoin/

CoinGecko
https://www.coingecko.com/en/coins/gccoin

Contract Address: 0x2D8269Dae518e78D95110dbFADf1fb479b8152e7

Audit 1 By Ace: https://github.com/Audit-Ace/Audits-Smart-Contracts/blob/main/GCCOIN%20Audit%20Report.pdf

Audit 2 By CyberScope:https://www.cyberscope.io/audits/gcc

**Comment by cryptomanz1** [comment]
As per our policy, there is a minimum requirement of 10,000 holder addresses and 15,000 transactions.
See the criteria at : https://developer.trustwallet.com/listing-new-assets/requirements .

**Comment by Cryptocool1** [comment]
Feel free to come back to us once all criteria are met. Make sure to mention this PR so the fee can be reused

**Comment by gccoinbnb** [comment]
i meet all other requirements only holder addresses number not and i see other not meet that and thy get approval all the hope from u to accept the listing and me and my Community will be thankful for you …. thanks

**Pull request closed without merging**
