### PR TITLE
Cryptocricketclub

### PR DESCRIPTION
**Pull request by cryptocricketclub**
Please update logo

### CODE REVIEW

**Comment by catenocrypt** [comment]
@cryptocricketclub , logo is already present, why do you want to change it?

blockchains/ethereum/assets/0x19EdFbe9814AF6eeE88289fdd789BC473e84f8F7/logo.png

**Comment by catenocrypt** [comment]
OK, I see now they are different.  However, the updated file causes a merge conflict.  I will try to fix that.

image

image

**Comment by catenocrypt** [comment]
The address 0x19edfbe9814af6eee88289fdd789bc473e84f8f7 is used by METH token, please check / comment.

https://etherscan.io/token/0x19edfbe9814af6eee88289fdd789bc473e84f8f7

**Comment by cryptocricketclub** [comment]
My contract address details are following:

Asset Name- CryptoCricketClub
Ticker-         3Cs
Contract Address -0x4f56221252d117f35E2f6Ab937A3F77CAd38934D

**Pull request merged**
