### PR TITLE
Add WEB4 AI (BEP20)

### PR DESCRIPTION
**Pull request by web4build**
Adding info for BEP20 token 'WEB4 AI'.

PR created by <a href="https://assets.trustwallet.com">TW Assets Management</a>

### CODE REVIEW

**Comment by Cryptocool1** [comment]
Hello! How did you get more than 20k holders in 1 week?

**Comment by web4build** [comment]
• What is the purpose of this token? How will it benefit Trust Wallet users?
WEB4 AI got our AI image generation app running at both our telegram and web app at the site https://webfour.build/app 
This will benefit trust wallet users because most of our user ask if we will be having our logo and details on trust wallet.

• How is the token being distributed? Are you conducting an airdrop?
Token is being sold via PancakeSwap, we did not conduct an airdrop.

• Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?
No ICO or presale.

• Is the token listed on a centralized/decentralized exchange?
We are listed on Pancake Swap.

• Is a Smart Contract audit completed? Where can we find this information?
Smart contract is done by SolidProof at https://app.solidproof.io/projects/web4ai

We are listed on price tracking site CoinGecko which can be verified at the address:
https://www.coingecko.com/en/coins/web4-ai

**Comment by Cryptocool1** [comment]
Hello, I didn’t ask you those questions.

**Comment by Cryptocool1** [comment]
Are you listed on CMC?

**Comment by web4build** [comment]
> Are you listed on CMC?

We are listed on CoinGecko which is also a price tracking site. 
https://www.coingecko.com/en/coins/web4-ai

**Comment by Tegimufranka9639** [comment]
Tegimufrank

**Review by alice22foster — COMMENTED** [review]
ok

**Comment by Tegimufranka9639** [comment]
Main

**Review by alice22foster — COMMENTED** [review]
??

**Comment by Cryptocool1** [comment]
Please come back to us once CMC requirement is met. Make sure to mention this PR in new one so the fee can be reused

**Comment by web4build** [comment]
WEB4 AI is listed on CoinMarketCap:

https://coinmarketcap.com/currencies/web4-ai/

**Comment by web4build** [comment]
> Please come back to us once CMC requirement is met. Make sure to mention this PR in new one so the fee can be reused

Hi, we are up on cmc, and it can be found on https://coinmarketcap.com/currencies/web4-ai/

Thank you

**Comment by Cryptocool1** [comment]
Congratulations!
Your logo should appear within 2hours.

**Pull request merged**
