### PR TITLE
Update RAMP BEP20 Logo

### PR DESCRIPTION
**Pull request by RAMPDEFITEAM**

### CODE REVIEW

**Comment by RAMPDEFITEAM** [comment]
Hi Nazar,

We've been trying to update our logo and made previous payments without any
success. Would you be able to assist please.

We've forked a couple of times and already made payment on previous PR.

Re: [trustwallet/assets] Add RAMP (BEP20) (#12823)
Re: [trustwallet/assets] Add RAMP (BEP20) (PR #14452)

Please advise what's the best way to proceed.

Thanks,
RAMP Team

**Comment by RAMPDEFITEAM** [comment]
Hi Nazar, or whoeve

We have already made payment several months back, but nothing was done by
your team to complete the merge. Can you please reply and provide a
resolution?

Thank you.

Best regards,
Lawrence

**Comment by cryptomanz** [comment]
info.json file is incorrect,
Please create new PR, follow doc https://community.trustwallet.com/t/how-to-submit-a-token-logo/3863
You may want to try our Assets app in beta; go to https://assets.trustwallet.com, log on with Github, enter contract ID, logo and some additional info, and it will create a PR for you.
See https://community.trustwallet.com/t/how-to-submit-a-token-logo-using-assets-app/82957.

**Comment by RAMPDEFITEAM** [comment]
HI Nazar,

Thanks for getting back.

May we know what's wrong with it? We've followed the template in the
instructions and also reference checked with other logo updates without
noticing any discrepancies.

Knowing the exact issue would help us address it asap.

Appreciate your help.

Thanks!
RAMP Team

**Pull request closed without merging**
