### PR TITLE
Add FREEMOON (BEP20)

### PR DESCRIPTION
**Pull request by freemoon-protocol**
Adding info for BEP20 token 'FREEMOON'.

PR created by <a href="https://assets.trustwallet.com">TW Assets Management</a>

### CODE REVIEW

**Comment by freemoon-protocol** [comment]
I have already paid the commission earlier.
https://solidity.finance/audits/FREEMOON-BSC/

**Comment by freemoon-protocol** [comment]
#13531

**Comment by freemoon-protocol** [comment]
[trustwallet/assets] Add FREEMOON (BEP20) (#13531)

**Comment by freemoon-protocol** [comment]
https://explorer.binance.org/tx/84663F81028D0E5AEA3A2F03BCDC4541393F7B6039DB6C7181F3A5BA4FB132D3

**Comment by freemoon-protocol** [comment]
@freemoon-protocol, kind reminder: please pay fee: 1000 TWT with the memo 3531 to the address bnb1tqq9llyr3dyjd559dha6z5r5etk3qfwk07m098.
Alternatively, 5 BNB is also accepted (same memo & address)

**Comment by freemoon-protocol** [comment]
> Hi! In order to compensate for the efforts of processing PRs, we kindly ask for a contribution.
> 💀 As **there is no refund**, before **paying the fee**, make sure **new tokens fulfill the minimum circulation and other [acceptance criteria](https://community.trustwallet.com/t/how-to-submit-a-token-logo/3863)**.
> See also the [PR Fee FAQ](https://developer.trustwallet.com/add_new_asset/pr-fee).
> 
> Please pay **1000 TWT** with the memo **3897** to the address `bnb1tqq9llyr3dyjd559dha6z5r5etk3qfwk07m098`.
> Alternatively, 5 BNB is also accepted (same memo & address).
> 
> **QR** code: [Trust](https://api.qrserver.com/v1/create-qr-code/?size=200x200&data=https%3A%2F%2Flink.trustwallet.com%2Fsend%3Fasset%3Dc714_tTWT-8C2%26address%3Dbnb1tqq9llyr3dyjd559dha6z5r5etk3qfwk07m098%26amount%3D1000%26memo%3D3897) | [other wallet](https://api.qrserver.com/v1/create-qr-code/?size=200x200&data=bnb1tqq9llyr3dyjd559dha6z5r5etk3qfwk07m098%3Famount%3D1000%26memo%3D3897)
> 
> _Notes_:
> 
> * [Trust Wallet Tokens (TWT)](https://community.trustwallet.com/t/trust-wallet-token-twt/4187) can be obtained through our [Referral Program](https://community.trustwallet.com/t/invite-a-friend-earn-trust-wallet-token-twt/4125) or [from DEXs/exchanges](https://community.trustwallet.com/t/where-to-get-trust-wallet-tokens/76641).
> * New tokens without significant usage are rejected, see criteria mentioned above.
> * One PR should be for a single project; PR's with more than 10 logos will be rejected.
> * Payment evaluation happens automatically, but with a few minutes delay.  When payment is detected, an Accept Review is automatically placed on the PR, which is a condition for merge.
> * Evaluating the PR is done manually, and it is merged only if all conditions are satisfied.
> * TWT-BEP2 is supported (Binance Chain), TWT-BEP20 version on Smart Chain is not.

**Comment by freemoon-protocol** [comment]
gh pr checkout #13531

**Review by freemoon-protocol — COMMENTED** [review]
gh pr checkout 13531

**Review by freemoon-protocol — COMMENTED** [review]
#13531

**Comment by Cryptocool1** [comment]
Hello, 
• What is the purpose of this token? How will it benefit Trust Wallet users?
 • How is the token being distributed? Are you conducting an airdrop?
 • Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?
 • Is the token listed on a centralized/decentralized exchange?
 • Is a Smart Contract audit completed? Where can we find this information?

**Comment by freemoon-protocol** [comment]
https://github.com/trustwallet/assets/pull/13531 
Hello. This is my second time already paying 1000TWT commission. I have already answered all of your colleague's questions earlier. You were interested in my audit. I made it and sent it to you. But you didn't wait and closed my repository. Please see the correspondence and my answers.

**Comment by freemoon-protocol** [comment]
The purpose of this token is to populate the coin and the smart binance chain. We plan to trade on the binance blockchain on many exchanges and want a logo in the trust wallet wallet. What we will inform all our users through our bot. We have released a guide on how to buy through a trust vallet and we recommend your wallet to everyone. https://freemoon.finance/trust-wallet
The token is distributed through a swap. https://pancakeswap.finance/info/pool/0xb24da9dcb23f5cafd0dc398ee3f3c516303be0ad
Airdrop distribution will begin on September 30th. Now we only have a swap. In order to order an advertisement, we need to get a logo. This will build more credibility.
No, we did not conduct ico and no primary sale. Swap only.
Yes, the liquidity pool has been posted on the pancakeswap https://pancakeswap.finance/info/token/0x31f0bc450c12eb62b4c617d4c876f7a66470fcb3
We have not ordered an audit yet, but we have frozen the liquidity pool for 4 years https://cointool.app/token/lock?a=0xb24da9dcb23f5cafd0dc398ee3f3c516303be0ad&c=56. Our task now is to popularize our token in order to increase sales. And then we will order an audit. We don't want big wallets now, so that people would buy a coin in small quantities and its price would rise. Stable.
https://solidity.finance/audits/FREEMOON-BSC/

**Pull request merged**
