### PR TITLE
Add logo.png upload

### PR DESCRIPTION
**Pull request by flaviosar**

### CODE REVIEW

**Comment by flaviosar** [comment]
Hello,
Folder and Logo, is ok.
0xaeb1b41981f7aa5740c7cc0ef5822a40149ec230/logo.png
Update, please.
Thank you

**Comment by flaviosar** [comment]
Change of logo.
Please fix the new logo (Chefs)
0x70f6a7ac4ebb8c04539e6d5245501cc553e48d39/logo.png
Thank you.

**Comment by kolya182** [comment]
I have manually added your tokens. Please update your fork for next PR.

**Comment by flaviosar** [comment]
Hello
@kolya182
In the Chefs Coin logo I want to update the previous logo, so I uploaded a new logo. It was not updated today.
You said I need to update Fork, how do I do this?
Thank you,
Flavio

**Pull request closed without merging**
