### PR TITLE
Add wCardano (BEP20)

### PR DESCRIPTION
**Pull request by wCardano**
Adding info for BEP20 token 'wCardano'.

PR created by <a href="https://assets.trustwallet.com">TW Assets Management</a>

### CODE REVIEW

**Comment by wCardano** [comment]
> **PR Summary**
> Files in PR: 4
> Tokens in PR (2):
> 
> * ERC20 0xdF2fc196d57f7E3736DAAab1De4b717C32380fB6
> * BEP20 0xdF2fc196d57f7E3736DAAab1De4b717C32380fB6
> 
> **Token ERC20 - 0xdF2fc196d57f7E3736DAAab1De4b717C32380fB6**:
> Could not retrieve info file; wCardano/assets/br0525-135825 0xdF2fc196d57f7E3736DAAab1De4b717C32380fB6, SyntaxError: Unexpected token : in JSON at position 10
> 
> **Token BEP20 - 0xdF2fc196d57f7E3736DAAab1De4b717C32380fB6**:
> Symbol: **wADA** decimals: 8
> Links: [Logo](https://raw.githubusercontent.com/wCardano/assets/br0525-135825/blockchains/smartchain/assets/0xdF2fc196d57f7E3736DAAab1De4b717C32380fB6/logo.png) [Info](https://raw.githubusercontent.com/wCardano/assets/br0525-135825/blockchains/smartchain/assets/0xdF2fc196d57f7E3736DAAab1De4b717C32380fB6/info.json) [Website](https://wCardano.net) [Explorer](https://bscscan.com/token/0xdF2fc196d57f7E3736DAAab1De4b717C32380fB6) (check OK 🙂)
> 
> 

Is there anything that needs to be fixed?

**Comment by wCardano** [comment]
please help, what went wrong and how to fix it?
I aim to add the BEP20 token logo and why is ERC20 verified?

**Comment by wCardano** [comment]
> **PR Summary**
> Files in PR: 4
> Tokens in PR (2):
> 
> * ERC20 0xdF2fc196d57f7E3736DAAab1De4b717C32380fB6
> * BEP20 0xdF2fc196d57f7E3736DAAab1De4b717C32380fB6
> 
> **Token ERC20 - 0xdF2fc196d57f7E3736DAAab1De4b717C32380fB6**:
> Symbol: **wADA** decimals: 8
> Links: [Logo](https://raw.githubusercontent.com/wCardano/assets/br0525-135825/blockchains/ethereum/assets/0xdF2fc196d57f7E3736DAAab1De4b717C32380fB6/logo.png) [Info](https://raw.githubusercontent.com/wCardano/assets/br0525-135825/blockchains/ethereum/assets/0xdF2fc196d57f7E3736DAAab1De4b717C32380fB6/info.json) [Website](https://wCardano.net) [ExplorerFromInfo](https://bscscan.com/token/0xdF2fc196d57f7E3736DAAab1De4b717C32380fB6) [ExplorerFromID](https://etherscan.io/token/0xdF2fc196d57f7E3736DAAab1De4b717C32380fB6)
> Token check error:
> ❌ ExplorerUrl incorrect, should be standard https://etherscan.io/token/0xdF2fc196d57f7E3736DAAab1De4b717C32380fB6, not https://bscscan.com/token/0xdF2fc196d57f7E3736DAAab1De4b717C32380fB6
> ! No. of holders not checked; 'undefined'
> ✓ Token type OK (ERC20); Contract/ID is OK; Type field OK; Symbol field OK; Decimals field OK; Description field OK; Website field OK; Status field OK; Id field OK; Logo image type is OK (image/png); Logo image size is OK (38.216 kB); Logo dimensions OK (256x256);
> 
> 
> 
> **Token BEP20 - 0xdF2fc196d57f7E3736DAAab1De4b717C32380fB6**:
> Symbol: **wADA** decimals: 8
> Links: [Logo](https://raw.githubusercontent.com/wCardano/assets/br0525-135825/blockchains/smartchain/assets/0xdF2fc196d57f7E3736DAAab1De4b717C32380fB6/logo.png) [Info](https://raw.githubusercontent.com/wCardano/assets/br0525-135825/blockchains/smartchain/assets/0xdF2fc196d57f7E3736DAAab1De4b717C32380fB6/info.json) [Website](https://wCardano.net) [Explorer](https://bscscan.com/token/0xdF2fc196d57f7E3736DAAab1De4b717C32380fB6) (check OK 🙂)
> 
> 

please help, what went wrong and how to fix it?
I aim to add the BEP20 token logo and why is ERC20 verified?

**Review by wCardano — COMMENTED** [review]
please clear ERC20 data, I will only add files for BEP20

**Review by wCardano — COMMENTED** [review]
done
just need to change ERC20 to BEP20

**Review by wCardano — COMMENTED** [review]
Done

**Comment by Cryptocool1** [comment]
8733 merged

**Pull request closed without merging**
