### PR TITLE
Add KSC (BEP20)

### PR DESCRIPTION
**Pull request by Kshark2021**
Adding info for BEP20 token 'KSC'.

PR created by TW Assets Management.

### CODE REVIEW

**Comment by cryptomanz** [comment]
Can your answer some questions?
 • What is the purpose of this token? How will it benefit Trust Wallet users?
 • How is the token being distributed? Are you conducting an airdrop?
 • Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?
 • Is the token listed on a centralized/decentralized exchange?
 • Is a Smart Contract audit completed? Where can we find this information?

**Comment by Kshark2021** [comment]
Hello, TrustWallet Team.

• What is the purpose of this token? How will it benefit Trust Wallet users?
KShark is a platform that integrates NFT games and decentralized yield farm applications. Joining KShark, you will not only entertain, but also have the opportunity to generate a lot of profit. KShark Game which is a Role-playing games to earn NFT and enrich. KShark is developed on Binance Smart Chain (Bep20) and Kardiachain (KRC20).

Website: https://Kshark.io 
Notification: https://t.me/KShark_Channel   
Telegram: https://t.me/KShark_Official 
Twitter: https://twitter.com/KShark_official
Medium: https://medium.com/@ksharks
Instagram:  https://www.instagram.com/kshark_channel/ 
Youtube: https://youtube.com/channel/UC-H4AqJ7_E1ZKhPEpP7dB4A 
Facebook: https://facebook.com/Kshark.io


• How is the token being distributed? Are you conducting an airdrop?
We have airdrop vndc.io, this is a trading platform with customers in Vietnam, they have more than 1.2M users, we just airdropped for 5000 users there, and lauchpad on VNDC to sell tokens.

• Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?
we opened selling KSC on PancakeSwap on Aug 9th.

• Is the token listed on a centralized/decentralized exchange?
Currently listed KSC on the following centralized/decentralized exchanges:
Nami.exchange.
Pancakeswap

• Is a Smart Contract audit completed? Where can we find this information?
We are working with Certik to conduct audit of smart contract, expected to be completed in August.

Thank You.

**Comment by Cryptocool1** [comment]
awaiting for smart contract audit.
on hold for now.

**Comment by Kshark2021** [comment]
Dessertswap audit : https://dessertswap.finance/audits/Baby%20KShark%20BEP-20%20Audit%2010056066.pdf?fbclid=IwAR0oe80oxWlIeeno8QAX18ZaAsQ1RoAWqn8EOUYmUu0fatPyaDcrGXDr2wg

**Comment by Cryptocool1** [comment]
your contract doesn't match with the contract on the website and smart contract audit
Please check

**Comment by Cryptocool1** [comment]
still no answer.
please create new PR when you will be ready to chat. make sure to mention this PR so the fee can be reused

**Comment by Kshark2021** [comment]
Hi, We have smart contract audit: https://kshark.io/file/audit/ksharkaudit.pdf

**Pull request closed without merging**
