### PR TITLE
Add EShib logo and info

### PR DESCRIPTION
**Pull request by Euroshibainu**
I'm upload logo and info.json

### CODE REVIEW

**Comment by cryptomanz** [comment]
This is a BEp20 token, correct folder is blockchains/smartchain/assets.
Please rename.

**Comment by Cryptocool1** [comment]
Please create new PR, follow doc https://developer.trustwallet.com/assets/requirements
You may want to try our Assets app in beta; go to https://assets.trustwallet.com, log on with Github, enter contract ID, logo and some additional info, and it will create a PR for you.
See https://developer.trustwallet.com/assets/repository_details

**Comment by Cryptocool1** [comment]
When creating new PR, mention this PR, so that fee can be reused, and not paid again.

**Comment by Euroshibainu** [comment]
How do I correct the errors?

**Comment by Euroshibainu** [comment]
lo único que tengo hacer es cambiar a la carpeta smart chain? el pago está ya realizado

**Comment by Euroshibainu** [comment]
> Al crear un nuevo PR, mencione este PR, para que la tarifa se pueda reutilizar y no se vuelva a pagar.

I try to make a new one and it tells me that the holders are not checked.

**Comment by Euroshibainu** [comment]
> Este es un token BEp20, la carpeta correcta es blockchains / smartchain / assets. Cambie el nombre.

How can I make the change? I don't see the option, thanks

**Pull request closed without merging**
