### PR TITLE
Add UNN token info and logo

### PR DESCRIPTION
**Pull request by glyskawa-unn**
This PR is being closed due to inactivity. If you wish to continue, please have us reopen the PR before sending your payment.
Do NOT send payments for closed PR, as the fee may by lost!
  (240 vs. 60 hrs)

### CODE REVIEW

**Comment by catenocrypt** [comment]
Submission looks OK, fee payment pending.

**Comment by catenocrypt** [comment]
Note that fee has been reduced to 500 TWT (due to TWT appreciation; 6 BNB is not changed).

**Comment by glyskawa-unn** [comment]
Hi @catenocrypt. There was some delays on our side. Could I ask you to reopen this PR again?

**Comment by catenocrypt** [comment]
Reopening.

**Comment by catenocrypt** [comment]
If PR is closed by the time fee is payed, do not worry, payment will be picked up when I reopen next time.
Submission looks OK.

**Comment by glyskawa-unn** [comment]
@catenocrypt Thank you. My coworker already send the payment when the PR was closed. Can it still be used for acceptance?

https://explorer.binance.org/tx/B195616948BAFE3ED8360AA8DE240A6FC9F70089E58BD6358930A4D17C160795

**Comment by catenocrypt** [comment]
Yes, payment will be picked up when PR is reopened next time.

**Comment by catenocrypt** [comment]
No payment is found; if it is paid already please provide TXID for manual check.

**Comment by glyskawa-unn** [comment]
@catenocrypt He paid 1000TWT so that's probably why bot is not finding transaction.
Please check it manually. Tx hash: B195616948BAFE3ED8360AA8DE240A6FC9F70089E58BD6358930A4D17C160795

**Comment by catenocrypt** [comment]
I think automation looks for only 5 days back, and this was a bit over that.  I mark it payed.

https://explorer.binance.org/tx/B195616948BAFE3ED8360AA8DE240A6FC9F70089E58BD6358930A4D17C160795

**Comment by catenocrypt** [comment]
Nice logo :)

**Comment by glyskawa-unn** [comment]
Thanks :)

**Pull request merged**
