### PR TITLE
Follow up request for the request #21197

### PR DESCRIPTION
**Pull request by EngToken**
Hello again dear TW
This is the follow up request for request #21197 . You requested us to provide an official SM audit and we've provided it with dessertswap.finance. the link to our audit is as follows:
https://dessertswap.finance/audits/EndlessBoardGame-AUDIT-19175219.pdf
For the record, our payment status is "paid" and we paid the fee for the request.
Thanks for your time and record
Regards

### CODE REVIEW

**Comment by Cryptocool1** [comment]
hello, I don't  see the activity on your token now. what did you do 21days ago, all holders come in that day?

**Comment by EngToken** [comment]
Hello dear Cryptocool1
As we explained before, our ICO stage ended on June 7th and some of our holders have joined our community in the ICO stage. Other investors have also purchased our token in the presale and Airdrop stages and through social networks in the last 6 months. This information can be checked on bscscan.

**Comment by EngToken** [comment]
Now we are waiting to be accepted to TW Repo and then without any hesitation, we are going to list our token on pancakeswap and open its trade.

**Comment by Cryptocool1** [comment]
are you listed on CoinmarketCap?

**Comment by EngToken** [comment]
We applied for listing about 2.5 months ago. 
After we get listed on TW Repo and open our trading on pancakswap, we'll be listed on CMC quickly as we've met all the criteria.

**Comment by Cryptocool1** [comment]
We require CoinMarketCap listing. See the criteria at : https://developer.trustwallet.com/assets/requirements .

**Comment by EngToken** [comment]
Let us explain it to you.
according to our roadmap, we are up to be listed on TW Repo first so when we open our trading on pancakeswap, our token logo can be shown on our liquidity pool and trading page. After that, we are going to list our token on Pancakeswap under this condition that I explained. At last, when we have markets on Pancakeswap, we'll be listed on CMC because we've met all the criteria.
We can guarantee this process in any way possible. please accept our request and let us go to the next step.

**Comment by EngToken** [comment]
Thank you.
It's our honor to be with you through our journey.
we'll do our best to make our project grow rapidly and conveniently.
Regards

**Pull request merged**
