### PR TITLE
Add Tulsa (TLA) Logo Token - ERC20

### PR DESCRIPTION
**Pull request by TulsaToken**
Website: https://tulsa.pro
Token Name: Tulsa
Symbol: TLA
Decimals: 18
Blockchain: Ethereum

for Trust Wallet

### CODE REVIEW

**Comment by TulsaToken** [comment]
Yesterday i have input the wrong logo format, and now i have put 512x512 in png format, 
0xca8F09B5c12c18A6081B839475DF13D3521A145A

**Comment by TulsaToken** [comment]
{
    "name": "Tulsa",
    "website": "https://tulsa.pro",
    "source_code": "https://github.com/TulsaToken",
    "short_description": "the Pro Gen. of Assets.",
    "description": "Token that use to lock and unlock other assets with open-source contract.",
    "socials": [
        {
            "name": "Twitter",
            "url": "https://twitter.com/tulsatoken",
            "handle": "TulsaToken"
        },
    ],
    "explorer": "https://etherscan.io/token/0xca8f09b5c12c18a6081b839475df13d3521a145a"
}

**Comment by TulsaToken** [comment]
Iamdeadlyz, don't tell me what new privacy policy is, i have submit my other success project 6th times, and all good, i am a old user here, i always work with zachzwei, i have working with trust wallet to submit logo, since there is no pay at all, until goes to 2000 TWT/1 BNB and now 1000 TWT, all my project are good 😎so do not make hard on this, i have use to update my logo here even when Binance not yet buyed this wallet!

**Comment by TulsaToken** [comment]
if can't please refund 1,000 twt to: bnb1gqwsv0etfxsgaldcae65dsf94jsk8f62j0jyzf

2B076594-7AC4-49AD-A620-F29A6241AFD6

**Comment by zachzwei** [comment]
> Iamdeadlyz, don't tell me what new privacy policy is, i have submit my other success project 6th times, and all good, i am a old user here, i always work with zachzwei, i have working with trust wallet to submit logo, since there is no pay at all, until goes to 2000 TWT/1 BNB and now 1000 TWT, all my project are good 😎so do not make hard on this, i have use to update my logo here even when Binance not yet buyed this wallet!

This account was just created 3 days ago. So not sure what you meant by other projects you submitted. Please provide clarification on your statement.

**Comment by TulsaToken** [comment]
zachwei, if you remember our project from ethash, ethash miner, yattaqi and yattaqi pro, syariahcoin, that was us (:

**Comment by TulsaToken** [comment]
i don't understand why now so complicated, even us the old users you make complicated, so will you update or not sir?

**Comment by EthashSystem** [comment]
zachwei hello it's us 😎👍🏼

**Comment by TulsaToken** [comment]
if it's still can't update my token logo, well, can you at least refund the TWT 🙏🏼, i hope you will update the logo, not reject it

**Comment by TulsaToken** [comment]
@zachzwei ?

**Comment by TulsaToken** [comment]
@zachzwei if can't please refund 1,000 twt to: bnb1gqwsv0etfxsgaldcae65dsf94jsk8f62j0jyzf - please do not hold too long.

**Comment by zachzwei** [comment]
Token activity does not meet the minimum requirements.
There is only 9 addresses and 38 transfers as of writing.
Pull request will be put on Hold.
Learn more here:
https://community.trustwallet.com/t/how-to-submit-a-token-logo/3863#how-to-get-approved

**Comment by zachzwei** [comment]
> @zachzwei if can't please refund 1,000 twt to: bnb1gqwsv0etfxsgaldcae65dsf94jsk8f62j0jyzf - please do not hold too long.

Read this comment as it was clearly stated that once payment is sent out, there are no refunds.
https://github.com/trustwallet/assets/pull/4756#issuecomment-724476836

**Comment by TulsaToken** [comment]
@zachzwei no you should just refund the TWT, so please refund bnb1gqwsv0etfxsgaldcae65dsf94jsk8f62j0jyzf - please do not hold too long, because my project still have so much time to go for build the better program, so please just refund

**Comment by TulsaToken** [comment]
@zachzwei but there is no telling a min requirement or anything like that, should have minimal address, so you guys still wrong, so please just refund

**Comment by TulsaToken** [comment]
well, i guess you guys don't wan't to refund my money, so i hope the money will make your life Better, go eat that money (: very dissappointed, i hope the money will change your life, be better next time and stop eating people's money like that it's not worth it (: if you won't procceed then refund okay, good luck have a good day

**Pull request closed without merging**
