### PR TITLE
added info and logo for SCORPION token

### PR DESCRIPTION
**Pull request by scorpion-token**
Added info and logo for SCORPION token

### CODE REVIEW

**Comment by Cryptocool1** [comment]
can you please add links to your PR?
example: https://developer.trustwallet.com/add_new_asset#info-json-contents

**Comment by scorpion-token** [comment]
Okay will do in a min

**Comment by scorpion-token** [comment]
Added links. Can you please verify??

**Comment by Cryptocool1** [comment]
great! thanks

**Pull request merged**
