### PR TITLE
upload logo token

### PR DESCRIPTION
**Pull request by jamwili1986**
upload logo token

### CODE REVIEW

**Comment by Cryptocool1** [comment]
hello,
• What is the purpose of this token? How will it benefit Trust Wallet users?
 • How is the token being distributed? Are you conducting an airdrop?
 • Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?
 • Is the token listed on a centralized/decentralized exchange?
 • Is a Smart Contract audit completed? Where can we find this information?

**Comment by jamwili1986** [comment]
> xin chào,
> • Mục đích của mã thông báo này là gì? Nó sẽ mang lại lợi ích như thế nào cho người dùng Trust Wallet?
> • Mã thông báo được phân phối như thế nào? Bạn đang tiến hành một airdrop?
> • Bạn đã bán mã thông báo tại Cung cấp tiền xu ban đầu (ICO) hoặc bán trước mã thông báo?
> • Mã thông báo có được liệt kê trên một sàn giao dịch tập trung / phi tập trung không?
> • Kiểm tra Hợp đồng thông minh đã hoàn thành chưa? Chúng ta có thể tìm thông tin này ở đâu?

Hello team
All project info can find in website: https://minishib.com
miniSHIB aims to bring cryptocurrency to a wider audience through engaging content, whilst raising funds for animal welfare charities.
We had ICO on DxSale and locked  LP value in this: Check info: https://dxsale.app/app/v2_9/dxlockview?id=0&add=0x07b7768F6863943a16372876A8000232b6391AdC&type=lplock&chain=BSC
we had list in PankageSwap: https://exchange.pancakeswap.finance/#/swap?inputCurrency=0x35bd36597ff784fcc30d08ebe4bd917374c40d4b
Smartcontract is doing audit, it not finish in now. we a new project, big liquidity in pankage swap pool

**Comment by Cryptocool1** [comment]
awaiting for smart contract audit
on hold for now

**Comment by Cryptocool1** [comment]
Hello,
please create new PR when smart contract audit will be ready.
make sure to mention this PR, so that we can see that fee has been paid already here.

**Comment by jamwili1986** [comment]
We had update Audit info: and creat new pull request in this:
https://github.com/trustwallet/assets/pull/11963
---------
We had finish audit from techrate.org
Info audit in Techrate github:

https://github.com/TechRate/Smart-Contract-Audits/blob/main/miniShibaToken%20Full%20Smart%20Contract%20Security%20Audit.pdf
Techrate Blockchain Solutions and Consulting:
Techrate is an analytical and engineering agency focused on blockchain technology solutions and audits.
it a part of last pull request: upload logo token #11774
thank you

**Pull request closed without merging**
