### PR TITLE
Add RICE logo and info

### PR DESCRIPTION
**Pull request by hadoanngoc**
RICE is the administrator token for Rooster Battle - a decentralized PvP game based on the tranditional and most popular sport in the world: Cockfighting game. RICE has been trading for 14 months right now

### CODE REVIEW

**Comment by hadoanngoc** [comment]
❌ explorer field incorrect: should be standard https://bscscan.com/token/0x338AF54976B9D4F7F41c97dcb60dFEc0694149f9, not https://bscscan.com/address/0x338AF54976B9D4F7F41c97dcb60dFEc0694149f9

--> fixed 
❌ invalid value 'https://www.facebook.com/roostersbattle' for facebook link url, allowed only with prefix: https://facebook.com/

--> fixed

- Holders: 10,011 addresses
- Transactions: 350,247

**Comment by cryptomanz1** [comment]
• What is the purpose of this token? How will it benefit Trust Wallet users?
 • How is the token being distributed? Are you conducting an airdrop?
 • Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?
 • Is the token listed on a centralized/decentralized exchange?
 • Is a Smart Contract audit completed? Where can we find this information?

**Comment by hadoanngoc** [comment]
Hi
1. RICE is the administrator token for Rooster Battle - a decentralized PvP game on Binance Smart Chain. Official website: https://roosterbattle.net/ . It's a GameFi project and has been running for 14 months
2. Players earn token by playing the game to get rewards from the pool, staking NFTs to get APY or selling NFTs. We had conducted some Airdrops in the past
3. Yes, tokens were sold at an ICO on a lunchpad (https://www.pinksale.finance/launchpad/0x0655DEFf21CD07d5Ef9eadE287050E7b73ce7b5F?chain=BSC)
4. Yes, it is listed on PancakeSwap: https://pancakeswap.finance/swap?outputCurrency=0x338AF54976B9D4F7F41c97dcb60dFEc0694149f9
5. We audit contract ourself, as we have in-house engineer in Blockchain (Our company website: https://coming.io). Beside, Token contract is generated using PinkSale Contract generator tool (https://docs.pinksale.finance/token/create-a-standard-token)

**Comment by cryptomanz1** [comment]
This is a BEP20 token, correct folder is blockchains/smartchain/assets. 
Please create new PR, follow doc https://developer.trustwallet.com/assets/requirements
You may want to try our Assets app in beta; go to https://assets.trustwallet.com, log on with Github, enter contract ID, logo and some additional info, and it will create a PR for you.
See https://developer.trustwallet.com/assets/repository_details

**Pull request closed without merging**
