### PR TITLE
ARTT Logo

### PR DESCRIPTION
**Pull request by artemprotocol**

### CODE REVIEW

**Comment by Iamdeadlyz** [comment]
As per our policy, brand new tokens are not included, there is a minimum requirement of 500 holder addresses and 1000 transactions, in order to filter out scam tokens. See the criteria at (mentioned in the first message by the bot): https://community.trustwallet.com/t/how-to-submit-a-token-logo/3863#how-to-get-approved

This token has below-limit usage yet (57, 824). Rejecting PR for now. Please come back to us when all criteria are met.
https://etherscan.io/token/0x77dF79539083DCd4a8898dbA296d899aFef20067

**Comment by artemprotocol** [comment]
Check again for minimum requirement again please, The users is following the announcement then the transfer is growing up continues.

**Comment by Iamdeadlyz** [comment]
Re-opening pull request, thanks for letting us know.

**Comment by vikmeup** [comment]
Can you please include `info.json` file for the token. 

Here is an example for DAI: https://github.com/trustwallet/assets/blob/master/blockchains/ethereum/assets/0x6B175474E89094C44Da98b954EedeAC495271d0F/info.json

**Review by Iamdeadlyz — COMMENTED** [review]
@artemprotocol 

Please provide more details about this project.
https://community.trustwallet.com/t/how-to-submit-a-token-logo/3863#how-to-get-approved
You can follow this format when adding an info.json file:
```
{
   “name”:“Bitcoin”,
   “website”:“https://bitcoin.org”,
   “source_code”:“https://github.com/bitcoin”,
   “white_paper”:“https://bitcoin.org/bitcoin.pdf”,
   “short_description”:“Bitcoin is a cryptocurrency and worldwide payment system.“,
   “explorer”:“https://blockchain.info”,
   “research”:“https://research.binance.com/en/projects/bitcoin”
}

**Comment by artemprotocol** [comment]
add info.json file done

**Comment by Iamdeadlyz** [comment]
@artemprotocol 

Please remove these files since it produces errors:
0x77dF79539083DCd4a8898dbA296d899aFef20067/info.json
0x77dF79539083DCd4a8898dbA296d899aFef20067/logo.png

Also, please edit the info.json (blockchains/ethereum/assets/0x77dF79539083DCd4a8898dbA296d899aFef20067/info.json) by removing the following key-value pair:
`"research": "https://app.zerion.io/explore/asset/ARTT-0x77df79539083dcd4a8898dba296d899afef20067"`

**Pull request merged**
