### PR TITLE
Add HOKK Logo to new HOKK Contract

### PR DESCRIPTION
**Pull request by hokk-finance**
Hello, requesting Logo to be added to new HOKK Contract. Info about the migration can be reviewed here - https://hokk.finance/migrationinfo/planb/

New ERC20 contract is 0xe87e15B9c7d989474Cb6d8c56b3DB4eFAD5b21E8

### CODE REVIEW

**Comment by hokk-finance** [comment]
We are a cross-chain fully bridged token undergoing a migration from ETH Chain to multiple chains on ETH, BSC and HECO. We have over 50K holders migrating to these 3 different chains and this effort is on-going. 

Our bridge is bridge.hokkfi.com

Across the current contracts combined we have over 14.5 wallets that have migrated and again, this is a bridged token.

ETH:
https://etherscan.io/token/0xe87e15b9c7d989474cb6d8c56b3db4efad5b21e8#balances

BSC:
https://bscscan.com/token/0xe87e15B9c7d989474Cb6d8c56b3DB4eFAD5b21E8#balances

HECO: 
https://hecoinfo.com/token/0x4ebf49cc2d2dd029e5cfdf868316385dffd94c6a#balances

**Comment by cryptomanz** [comment]
Please create new PR, with new contract and i will put status abandoned in your old contract. Make sure to mention this PR, so that we can see that fee has been paid already here.

**Comment by hokk-finance** [comment]
> Please create new PR, with new contract and i will put status abandoned in your old contract. Make sure to mention this PR, so that we can see that fee has been paid already here.

Hey @cryptomanz I thought this is what I did on this PR?

**Comment by hokk-finance** [comment]
> Please create new PR, with new contract and i will put status abandoned in your old contract. Make sure to mention this PR, so that we can see that fee has been paid already here.

Please see new PR
https://github.com/trustwallet/assets/pull/17676

**Pull request closed without merging**
