### PR TITLE
Add Absorber (bep20)

### PR DESCRIPTION
**Pull request by SonGokuBg**
Adding info for bep20 token 'Absorber'.

PR created by <a href="https://assets.trustwallet.com">TW Assets Management</a>

### CODE REVIEW

**Comment by SonGokuBg** [comment]
is that good?

**Comment by catenocrypt** [comment]
You have added logo+info under both `smarthchain` and `binance` folders.
If you intend to add the BEP20 token: remove the files from under binance (keep only 2 files under smartchain).
If you intend to add both BEP20 and BEP2 versions, you need to supply correct BEP2 ID.
Please correct.

**Comment by SonGokuBg** [comment]
> You have added logo+info under both `smarthchain` and `binance` folders.
> If you intend to add the BEP20 token: remove the files from under binance (keep only 2 files under smartchain).
> If you intend to add both BEP20 and BEP2 versions, you need to supply correct BEP2 ID.
> Please correct.

but I used your app

**Comment by SonGokuBg** [comment]
> You have added logo+info under both `smarthchain` and `binance` folders.
> If you intend to add the BEP20 token: remove the files from under binance (keep only 2 files under smartchain).
> If you intend to add both BEP20 and BEP2 versions, you need to supply correct BEP2 ID.
> Please correct.

done https://github.com/trustwallet/assets/pull/5647

**Comment by catenocrypt** [comment]
The two incorrect files should have been removed from this PR, not in another PR.  I fixed it now.
Maybe the Assets app created 2x2 files incorrectly?  I'll check.

**Comment by SonGokuBg** [comment]
> The two incorrect files should have been removed from this PR, not in another PR. I fixed it now.
> Maybe the Assets app created 2x2 files incorrectly? I'll check.

So everything good now?

**Comment by catenocrypt** [comment]
Yes, PR has been merged.

**Pull request merged**
