### PR TITLE
Add Ronin Gamez (BEP20)

### PR DESCRIPTION
**Pull request by Astronautj**
Adding info for BEP20 token 'Ronin Gamez'.

PR created by <a href="https://assets.trustwallet.com">TW Assets Management</a>

### CODE REVIEW

**Comment by Astronautj** [comment]
> **PR Summary** Files OK, 4Files in PR: 4 Tokens in PR (2):
> 
> * BEP2 0x980b37a82B60A32965b6e56356D14E0410ea440F
> * BEP20 0x980b37a82B60A32965b6e56356D14E0410ea440F
> 
> **Token BEP2 - 0x980b37a82B60A32965b6e56356D14E0410ea440F**: Could not retrieve info file; Astronautj/assets/br1001-010215 0x980b37a82B60A32965b6e56356D14E0410ea440F, SyntaxError: Unexpected token : in JSON at position 10
> 
> **Token BEP20 - 0x980b37a82B60A32965b6e56356D14E0410ea440F**: Symbol: **RONINGMZ** decimals: 18 Links: [Logo](https://raw.githubusercontent.com/Astronautj/assets/br1001-010215/blockchains/smartchain/assets/0x980b37a82B60A32965b6e56356D14E0410ea440F/logo.png) [Info](https://raw.githubusercontent.com/Astronautj/assets/br1001-010215/blockchains/smartchain/assets/0x980b37a82B60A32965b6e56356D14E0410ea440F/info.json) [Website](https://roningamez.io/) [Explorer](https://bscscan.com/token/0x980b37a82B60A32965b6e56356D14E0410ea440F) (check OK 🙂)
> 
> 

@Cryptocool1 Can you please explain why is there BEP2 here?

**Comment by Astronautj** [comment]
Should I send the payment now, @cryptomanz ?

**Comment by cryptomanz** [comment]
Hello,
Can your answer some questions?
• What is the purpose of this token? How will it benefit Trust Wallet users?
• How is the token being distributed? Are you conducting an airdrop?
• Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?
• Is the token listed on a centralized/decentralized exchange?
• Is a Smart Contract audit completed? Where can we find this information?

**Comment by Astronautj** [comment]
- It is a transactional token that would be used in the Ronin Ecosystem, which includes (but is not limited to) NFT and Gaming.
- No, we're not conducting an airdrop, the tokens are distributed through PanCakeSwap.
- Yes, we did have a presale.
- Yes, we're listed on PanCakeSwap.
- Our token was audited by [Dessert Finance](https://drive.google.com/file/d/1lmp-6O-id2igFsMC0Gnm0NbnCWC8w1J5/view)

**Comment by Astronautj** [comment]
If it's all good then, I'll send the payment @cryptomanz

**Pull request merged**
