### PR TITLE
Update US Money Token

### PR DESCRIPTION
**Pull request by mmotradeus**

### CODE REVIEW

**Comment by mmotradeus** [comment]
payment made

**Comment by catenocrypt** [comment]
Git shows conflict, because you are overwriting a file that was recently included in master.  I have resolved conflict by merging master.

**Comment by mmotradeus** [comment]
> Git shows conflict, because you are overwriting a file that was recently included in master. I have resolved conflict by merging master.

thank you!

**Comment by catenocrypt** [comment]
Sorry, I have merged this without fee payment :)  Normally new fee is required for every PR, even if just changing existing logo.  We appreciate if you do another payment for this PR, thanks.

**Comment by mmotradeus** [comment]
> Sorry, I have merged this without fee payment :) Normally new fee is required for every PR, even if just changing existing logo. We appreciate if you do another payment for this PR, thanks.

should I create a new PR or pay in this PR?

**Comment by catenocrypt** [comment]
I meant this one

**Comment by mmotradeus** [comment]
I've paid this, please check and update my new logo
Thanks

**Comment by catenocrypt** [comment]
Thanks for the payment.
Merge already done.

image

https://explorer.binance.org/address/bnb1tqq9llyr3dyjd559dha6z5r5etk3qfwk07m098

**Pull request merged**
