### PR TITLE
Init

### PR DESCRIPTION
**Pull request by tonimonteiro**

### CODE REVIEW

**Comment by kolya182** [comment]
@tonimonteiro What do you trying to do ? I have already fixed it for you.

**Comment by tonimonteiro** [comment]
I was preparing to do the whole procedure again. Is the logo already working?

**Comment by tonimonteiro** [comment]
@kolya182 I was preparing to do the whole procedure again. Is the logo already working?

**Comment by kolya182** [comment]
Added

**Comment by tonimonteiro** [comment]
Tks!

**Pull request closed without merging**
