### PR TITLE
Add Northern Lottery (XSMB) (TRC21)

### PR DESCRIPTION
**Pull request by xsmbtoken**
Adding info for TRC21 token 'Northern Lottery (XSMB)'.

PR created by <a href="https://assets.trustwallet.com">TW Assets Management</a>

### CODE REVIEW

**Comment by Cryptocool1** [comment]
• What is the purpose of this token? How will it benefit Trust Wallet users?
 • How is the token being distributed? Are you conducting an airdrop?
 • Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?
 • Is the token listed on a centralized/decentralized exchange?
 • Is a Smart Contract audit completed? Where can we find this information?

**Comment by xsmbtoken** [comment]
> • What is the purpose of this token? How will it benefit Trust Wallet users? • How is the token being distributed? Are you conducting an airdrop? • Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale? • Is the token listed on a centralized/decentralized exchange? • Is a Smart Contract audit completed? Where can we find this information?
**1. purpose of this token:**  This is a gamefi web, an online lottery for the blockchain community
**How will it benefit Trust Wallet users?** Users use xsmb tokens to buy lottery tickets, and win prizes in tokens, using real-life Mega Millions and Power Ball drawing results to pay prizes.
**How is the token being distributed? Are you conducting an airdrop?** 
We organize daily lottery drawings and award prizes to winners, and will also organize games on social networks to give away tokens by airdrop
**Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?** 
No, we Fair Launch
**Is the token listed on a centralized/decentralized exchange?**
yes on DEX https://www.geckoterminal.com/tomochain/pools/0xb9eae35b150312e07676f28d98f769f8ea47c1b2 (luaswap dex)
on CEX: https://dex-trade.com/spot/trading/XSMBBTC?interface=classic (dex-trade.com exchange)
 **Is a Smart Contract audit completed? Where can we find this information?**
 we published smartcontract on https://tomoscan.io/token/0x453B71962b5ffbe830a47AbB11A5CFd35C4250BA#contracts
 TRC21 smart contract is publish and audit by TomoChain team dev

**Comment by xsmbtoken** [comment]
We have paid and have replied your questions, but still not have logo on Trust wallet, when? 
regards

**Comment by xsmbtoken** [comment]
Dear Trust Team
Our logo still not display on Trust Wallet? Why? We have paid

**Comment by xsmbtoken** [comment]
number of holders : is 16,134 , you can check it manually at https://tomoscan.io/token/0x453B71962b5ffbe830a47AbB11A5CFd35C4250BA#holders

**Comment by xsmbtoken** [comment]
> number of holders : is 16,134 , you can check it manually at https://tomoscan.io/token/0x453B71962b5ffbe830a47AbB11A5CFd35C4250BA#holders

number of holders : is 16,134 , you can check it manually at https://tomoscan.io/token/0x453B71962b5ffbe830a47AbB11A5CFd35C4250BA#holders

> ### PR Summary
> Files OK: 2 Token in PR: **TRC21** 0x453B71962b5ffbe830a47AbB11A5CFd35C4250BA Symbol: **XSMB** decimals: 18 Links: [Logo](https://raw.githubusercontent.com/xsmbtoken/assets/br0927-123043/blockchains/tomochain/assets/0x453B71962b5ffbe830a47AbB11A5CFd35C4250BA/logo.png) [Info](https://raw.githubusercontent.com/xsmbtoken/assets/br0927-123043/blockchains/tomochain/assets/0x453B71962b5ffbe830a47AbB11A5CFd35C4250BA/info.json) [Website](https://lottoxsmb.com/) [Explorer](https://scan.tomochain.com/address/0x453B71962b5ffbe830a47AbB11A5CFd35C4250BA) Tags: gamefi Token check error: ❌ number of holders not checked: please, check it manually
> 
>

**Comment by Cryptocool1** [comment]
Hello, we require smart contract audit from reputable companies, you can see this requirement in our documentation

**Comment by xsmbtoken** [comment]
> Hello, we require smart contract audit from reputable companies, you can see this requirement in our documentation

We use TRC21 smartcontract from Tomochain, it is standard you can check it manually at: https://tomoscan.io/token/0x453B71962b5ffbe830a47AbB11A5CFd35C4250BA#contracts

**Comment by Cryptocool1** [comment]
Here is an example of smart contract audit https://skynet.certik.com/projects/trust-wallet

**Comment by xsmbtoken** [comment]
We use TRC21 smartcontract from Tomochain, it is standard you can check it manually at: https://tomoscan.io/token/0x453B71962b5ffbe830a47AbB11A5CFd35C4250BA#contracts

**Comment by xsmbtoken** [comment]
> TRC21 smartcontract from Tomochain

TRC21 smartcontract is created by Tomochain, not written by us, it is automatically generated by Tomochain, you can see the documentation here https://docs.tomochain.com/developer-guide/tutorials/how-to -deploy-a-trc21-token-on-tomochain
Because Tomochain has been audited, the TRC21 smart contract is also audited by default. With the many TRC21 projects on Tomochain that you put on the Trust, why do you need to audit them and you force us to audit them?

**Comment by xsmbtoken** [comment]
> Hello, we require smart contract audit from reputable companies, you can see this requirement in our documentation

TRC21 smartcontract is created by Tomochain, not written by us, it is automatically generated by Tomochain, you can see the documentation here 
https://docs.tomochain.com/developer-guide/tutorials/how-to-deploy-a-trc21-token-on-tomochain
Because Tomochain has been audited, the TRC21 smart contract is also audited by default. With the many TRC21 projects on Tomochain that you put on the Trust, why do you need to audit them and you force us to audit them?

**Comment by xsmbtoken** [comment]
> Here is an example of smart contract audit https://skynet.certik.com/projects/trust-wallet

First, the XSMB token is automatically generated by the Tomochain Issue software, at this address: https://issuer.tomochain.com/
Tomochain automatically creates TRC21 smartcontract, token creators do not need programming knowledge or skills, it's all automatic.
1. You can view XSMB's smart contract here: https://tomoscan.io/token/0x453B71962b5ffbe830a47AbB11A5CFd35C4250BA#contracts
2. You can refer to how to create XSMB tokens here:
https://docs.tomochain.com/developer-guide/tutorials/how-to-deploy-a-trc21-token-on-tomochain
We do not code that smart contract, but it is automatically created by the Tomochain platform. TRC21 has been audited by Tomochain to be safe for users.
  There are quite a few TRC21 tokens that have been listed on Trust Wallet without the need for an audit code, so you should list the XSMB logo on Trust because we have followed the Trust's requirements.
Best regards

**Comment by xsmbtoken** [comment]
> ### PR Summary
> Files OK: 2 Token in PR: **TRC21** 0x453B71962b5ffbe830a47AbB11A5CFd35C4250BA Symbol: **XSMB** decimals: 18 Links: [Logo](https://raw.githubusercontent.com/xsmbtoken/assets/br0927-123043/blockchains/tomochain/assets/0x453B71962b5ffbe830a47AbB11A5CFd35C4250BA/logo.png) [Info](https://raw.githubusercontent.com/xsmbtoken/assets/br0927-123043/blockchains/tomochain/assets/0x453B71962b5ffbe830a47AbB11A5CFd35C4250BA/info.json) [Website](https://lottoxsmb.com/) [Explorer](https://scan.tomochain.com/address/0x453B71962b5ffbe830a47AbB11A5CFd35C4250BA) Tags: gamefi Token check error: ❌ number of holders not checked: please, check it manually
> 
> 
number of holders : is 16,134 , you can check it manually at https://tomoscan.io/token/0x453B71962b5ffbe830a47AbB11A5CFd35C4250BA#holders

**Comment by xsmbtoken** [comment]
Hello Trust team 
Many months ago we have logo on Trust Wallet, but now it not display anymore, why?

**Pull request merged**
