### PR TITLE
Add logo and info

### PR DESCRIPTION
**Pull request by ghost**
Add logo and info

### CODE REVIEW

**Comment by Cryptocool1** [comment]
You should add the links and tags, see the example here: https://developer.trustwallet.com/assets/repository_details

**Comment by cryptomanz** [comment]
• Is a Smart Contract audit completed? Where can we find this information?

**Comment by Novalandmetaverse** [comment]
https://www.certik.com/projects/novaland

**Comment by Novalandmetaverse** [comment]
Hello @cryptomanz I put wrong token name in `info.json` file. How do i correct it.

**Pull request merged**
