### PR TITLE
Add QOM logo and info

### PR DESCRIPTION
**Pull request by metaverseisa**

### CODE REVIEW

**Comment by cryptomanz** [comment]
As per our policy, brand new tokens are not included, there is a minimum requirement of 10,000 holder addresses and 15,000 transactions, in order to filter out scam tokens.
See the criteria at : https://developer.trustwallet.com/assets/requirements .

**Comment by cryptomanz** [comment]
• Is a Smart Contract audit completed? Where can we find this information?

**Comment by cryptomanz** [comment]
Please come back to us when all criteria are met.
When creating a new PR make sure to mention this PR, so that we can see that fee has been paid already here.

**Comment by metaverseisa** [comment]
> Please come back to us when all criteria are met.
> When creating a new PR make sure to mention this PR, so that we can see that fee has been paid already here.

Hi there, I think there may have been a small error in your system as I sent all the information above in the json file exactly the way it was requested. I followed the sample document to ensure I provided with all the correct details.

Additionally, we have millions of dollars worth of trading per day with our token and we have most definitely passed all the criteria. 

Check this link to confirm all the criteria has been hit 
https://coinmarketcap.com/currencies/shiba-predator/

**Comment by Cryptocool1** [comment]
• Is a Smart Contract audit completed? Where can we find this information?

**Comment by Cryptocool1** [comment]
We accept audit only from reputable companies such as: certik, hacken, techrate, dessert finance

**Comment by Cryptocool1** [comment]
As per our policy, brand new tokens are not included, there is a minimum requirement of 10,000 holder addresses and 15,000 transactions, in order to filter out scam tokens.
See the criteria at : https://developer.trustwallet.com/assets/requirements .

**Pull request closed without merging**
