### PR TITLE
Add KSHIBA logo and info 

### PR DESCRIPTION
**Pull request by KaiKenShiba**
We are preparing for project development campaigns. 
The project will quickly receive receiving from the community
https://twitter.com/KaikenShiba
https://github.com/KaiKenShiba
https://www.reddit.com/user/KaikenShiba
https://t.me/KaiKenShiba_News
https://t.me/KaiKenShiba_Chat

### CODE REVIEW

**Comment by KaiKenShiba** [comment]
> Chúng tôi đang chuẩn bị cho các chiến dịch phát triển dự án.
> Dự án sẽ nhanh chóng nhận được sự đón nhận từ cộng đồng
> [https://twitter.com/KaikenShiba ](https://twitter.com/KaikenShiba)
> [https://github.com/KaiKenShiba ](https://github.com/KaiKenShiba)
> [https://www.reddit.com/user/KaikenShiba ](https://www.reddit.com/user/KaikenShiba)
> [https://t.me/KaiKenShiba_News ](https://t.me/KaiKenShiba_News)
> [https : //t.me/KaiKenShiba_Chat](https://t.me/KaiKenShiba_Chat)

Email : Kaikenshiba.dev@gmail.com

**Comment by KaiKenShiba** [comment]
Did I have exactly the requirements yet? Let me know if it is wrong

Vào CN, 11 thg 7, 2021 vào lúc 09:01 merge-fee-bot[bot] <
***@***.***> đã viết:

**Comment by KaiKenShiba** [comment]
Did I have exactly the requirements yet? Let me know if it is wrong

Vào CN, 11 thg 7, 2021 vào lúc 09:09 Shiba KaiKen ***@***.***>
đã viết:

**Comment by KaiKenShiba** [comment]
Check and add it to help me become accurate on Github. Please inform me if
exactly and I will pay the fee .Thanks

Vào CN, 11 thg 7, 2021 vào lúc 09:09 Shiba KaiKen ***@***.***>
đã viết:

**Comment by KaiKenShiba** [comment]
Check and add it to help me become accurate on Github. Please inform me if
exactly and I will pay the fee .Thanks

Vào CN, 11 thg 7, 2021 vào lúc 09:12 Shiba KaiKen ***@***.***>
đã viết:

**Comment by KaiKenShiba** [comment]
# 11613


Vào CN, 11 thg 7, 2021 vào lúc 09:09 Shiba KaiKen ***@***.***>
đã viết:

**Comment by KaiKenShiba** [comment]
I edited it, please check and for the evaluation. Thank you

Vào CN, 11 thg 7, 2021 vào lúc 11:38 merge-fee-bot[bot] <
***@***.***> đã viết:

**Comment by cryptomanz** [comment]
- This is a BEp20 token, correct folder is blockchains/smartchain/assets.
- Please create new PR, follow doc https://community.trustwallet.com/t/how-to-submit-a-token-logo/3863
You may want to try our new Assets app in beta; go to https://assets.trustwallet.com, log on with Github, enter contract ID, logo and some additional info, and it will create a PR for you.
See https://community.trustwallet.com/t/how-to-submit-a-token-logo-using-assets-app/82957.

**Comment by KaiKenShiba** [comment]
[image: Ảnh chụp Màn hình 2021-07-12 lúc 08.23.20.png]
I have resized the image to 256x256 but the system still gives me an error,
please tell me what size is required for your image

Vào CN, 11 thg 7, 2021 vào lúc 22:00 Nazar ***@***.***> đã
viết:

**Comment by KaiKenShiba** [comment]
Vào Th 2, 12 thg 7, 2021 vào lúc 08:24 Shiba KaiKen <
***@***.***> đã viết:

**Pull request closed without merging**
