### PR TITLE
Add JoyStick Games (JOY) (ERC20)

### PR DESCRIPTION
**Pull request by JoystickToken**
Adding info for ERC20 token 'JoyStick Games (JOY)'.

PR created by <a href="https://assets.trustwallet.com">TW Assets Management</a>

### CODE REVIEW

**Comment by JoystickToken** [comment]
Hello i forgot to add the inatagram link could it please be added still?

https://instagram.com/joystickpros

Thank you and sorry for unconvenience.

**Comment by Cryptocool1** [comment]
• What is the purpose of this token? How will it benefit Trust Wallet users?
 • How is the token being distributed? Are you conducting an airdrop?
 • Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?
 • Is the token listed on a centralized/decentralized exchange?
 • Is a Smart Contract audit completed? Where can we find this information?

**Comment by JoystickToken** [comment]
- Joystick empowers players making money playing the games they love. We are building multiple ways for users to earn money with Gamefi, the majority off our players use Trust Wallet.
-we did not conduct any airdrops.
- we are fairlaunched
- We are listed on Uniswap
- We are being audited by Certik 
https://www.certik.com/projects/joystick

**Comment by JoystickToken** [comment]
- Joystick empowers players making money playing the games they love. We are building multiple ways for users to earn money with Gamefi, the majority off our players use Trust Wallet.
-we did not conduct any airdrops.
- we are fairlaunched
- We are listed on Uniswap
- We are being audited by Certik 
https://www.certik.com/projects/joystick

**Pull request merged**
