### PR TITLE
Crypto Accept Logo Update

### PR DESCRIPTION
**Pull request by ghost**

### CODE REVIEW

**Comment by cryptojoehodler** [comment]
Payment submitted.

**Comment by catenocrypt** [comment]
As per our policy, brand new tokens are not included, there is a minimum requirement of 500 holder addresses and 1000 transactions, in order to filter out scam tokens.
See the criteria at (mentioned in the first message by the bot): https://community.trustwallet.com/t/how-to-submit-a-token-logo/3863#how-to-get-approved
This token has below-limit usage yet (114). Putting PR on hold. Please come back to us when all criteria are met.


https://etherscan.io/token/0xcAd2d4C4469fF09aB24d02A63BCeDfCD44bE0645

**Comment by cryptojoehodler** [comment]
Will you honor our payment if we increase our holders within a month?

Joe

**Comment by catenocrypt** [comment]
> Will you honor our payment if we increase our holders within a month? Joe

Yes.  Technically the PR will be closed by automation, but if you dig it out, we can reopen it (or create a new one).  No need to pay again for the same files.

**Pull request closed without merging**
