### PR TITLE
Add new SEELE logo and info.

### PR DESCRIPTION
**Pull request by depech**
This PR is being closed due to inactivity. If you wish to continue, please have us reopen the PR before sending your payment.
Do NOT send payments for closed PR, as the fee may by lost!
  (60 vs. 60 hrs)

### CODE REVIEW

**Review by Iamdeadlyz — APPROVED** [review]
info.json and logo is ok ✅ 
waiting for the payment to proceed in merging

**Comment by depech** [comment]
Unfortunately, I am not ready to pay ~ 50 USD to renew the old token. It's too much money for me. If anyone wants to help with payment, I would be grateful.

**Comment by catenocrypt** [comment]
> Unfortunately, I am not ready to pay ~ 50 USD to renew the old token. It's too much money for me. If anyone wants to help with payment, I would be grateful.

Please note that starting from today fee has been reduced somewhat:  250 TWT or 2 BNB; the former is currently around $30.

**Pull request closed without merging**
