### PR TITLE
Add SAFEBTC logo and info

### PR DESCRIPTION
**Pull request by SAFEBTCOFFICIAL**

### CODE REVIEW

**Comment by SAFEBTCOFFICIAL** [comment]
Hi, i paid already few days ago but my request wasnt completed and my logo and info were not updated and the request was closed, so i created a new pull request now

Best

Stefano

**Comment by SAFEBTCOFFICIAL** [comment]
The old Pr is #9576 and was paid already.

best

**Comment by SAFEBTCOFFICIAL** [comment]
Hi do I need to pull a new PR with the right SAFEBTC letters? 
  
  
   
    On 06/15/2021 12:19 PM merge-fee-bot[bot] ***@***.***> wrote:
   
   
    
   
   
    
   
   
   PR SummaryFiles OK, 2Files in PR: 2Token in PR: BEP20 0x380624A4a7e69dB1cA07deEcF764025FC224D056Symbol: SafeBTC decimals: 9Links: Logo Info Website ExplorerToken check error:! Symbol possibly has wrong casing, expected 'SAFEBTC' instead of 'SafeBTC', please cross-check with explorer page.✓ Token type OK (BEP20); Contract/ID is OK; Type field OK; Decimals field OK; Description field OK; Website field OK; Explorer field OK; Status field OK; Id field OK; Logo image type is OK (image/png); Logo image size is OK (28.394 kB); Logo dimensions OK (256x256); Token circulation OK (no. of holders: 211960);

**Comment by SAFEBTCOFFICIAL** [comment]
Is the logo and info will updated anyway? 

Please let me know if i have to do anything else or if we are good to go.

thanks for your time

Stefano

**Comment by SAFEBTCOFFICIAL** [comment]
Hi, can you please please update the logo and info . It’s been taking a while now. 
   and everything is being paid already days ago.
  
  
   
  
  
   thanks 
  
  
   
    On 06/15/2021 12:19 PM merge-fee-bot[bot] ***@***.***> wrote:
   
   
    
   
   
    
   
   
   PR SummaryFiles OK, 2Files in PR: 2Token in PR: BEP20 0x380624A4a7e69dB1cA07deEcF764025FC224D056Symbol: SafeBTC decimals: 9Links: Logo Info Website ExplorerToken check error:! Symbol possibly has wrong casing, expected 'SAFEBTC' instead of 'SafeBTC', please cross-check with explorer page.✓ Token type OK (BEP20); Contract/ID is OK; Type field OK; Decimals field OK; Description field OK; Website field OK; Explorer field OK; Status field OK; Id field OK; Logo image type is OK (image/png); Logo image size is OK (28.394 kB); Logo dimensions OK (256x256); Token circulation OK (no. of holders: 211960);

**Comment by Cryptocool1** [comment]
cannot find contract on your website.
please check/add

**Comment by SAFEBTCOFFICIAL** [comment]
Hi, added! 
   
   
  
  
   please check 
  
  
   
  
  
   thansk 
  
  
   
    On 06/17/2021 7:58 AM CryptoA ***@***.***> wrote:
   
   
    
   
   
    
   
   
   cannot find contract on your website.please check/add

**Comment by SAFEBTCOFFICIAL** [comment]
Is the logo will be updated soon?
thanks

**Pull request merged**
