### PR TITLE
Add VCGamers (BEP20)

### PR DESCRIPTION
**Pull request by vcgamers**
Adding info for BEP20 token 'VCGamers'.

PR created by <a href="https://assets.trustwallet.com">TW Assets Management</a>

### CODE REVIEW

**Comment by cryptomanz** [comment]
• What is the purpose of this token? How will it benefit Trust Wallet users?
 • How is the token being distributed? Are you conducting an airdrop?
 • Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?
 • Is the token listed on a centralized/decentralized exchange?
 • Is a Smart Contract audit completed? Where can we find this information?

**Comment by vcgamers** [comment]
_• What is the purpose of this token? How will it benefit Trust Wallet users?_
**We use VCG Token in our platform vcgamers.com , VCGamers is a biggest web-and app-based gaming social commerce platform established since 2019 , which provides all your gaming needs in one place. We want user to hold VCG on Trustwallet. Now there are about 6000 holders and the market cap is about 2 million USD.**

_• How is the token being distributed? Are you conducting an airdrop?_
**Tokens are distributed by private sale and presale on the pinksale platform, and we have already distributed airdrops to 500 participant wallets, You can find out here: https://t.me/vcgamers_news/134**

_• Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?_
**We sold using presale in platform Pinksale.app**

_• Is the token listed on a centralized/decentralized exchange?_
**The token has been already listed on Pancakeswap.**

_• Is a Smart Contract audit completed? Where can we find this information?_
**The smart-contract is audited by Techrate. You can find out here:
https://github.com/TechRate/Smart-Contract-Audits/blob/main/January/VCGamers%20Full%20Smart%20Contract%20Security%20Audit.pdf**

**Comment by cryptomanz** [comment]
Please follow the rules for adding token, your logo should be a full screen, 256x256.

**Comment by vcgamers** [comment]
Created PR 17903  
https://github.com/trustwallet/assets/pull/17903
New PR with logo correction ( 256px x256px )

CC
@Iamdeadlyz, @Cryptocool1, @cryptomanz

**Comment by vcgamers** [comment]
> Please follow the rules for adding token, your logo should be a full screen, 256x256.

LOGO UPDATED (256x256) :

https://github.com/trustwallet/assets/pull/17889/files

https://raw.githubusercontent.com/trustwallet/assets/cea595531bcea57678e1d66e965be4f963ae1754/blockchains/smartchain/assets/0x1F36FB2D91d9951Cf58aE4c1956C0b77e224F1E9/logo.png

**Pull request merged**
