### PR TITLE
update a new logo of INT

### PR DESCRIPTION
**Pull request by SickleZhang**
update a new logo of INT

### CODE REVIEW

**Comment by SickleZhang** [comment]
update new info of INT.

**Comment by catenocrypt** [comment]
Token check: usage is somewhat below limit, but accepting as this is an update to existing logo.

**Comment by catenocrypt** [comment]
-  X 'Check that logos are not too large': 'Found at least one logo that is too large: /home/runner/work/assets/assets/blockchains/ethereum/assets/0xbe038A2FDfec62Cf1beD852f141A43005035edcC/logo.png'

**Comment by catenocrypt** [comment]
Crooped image to 512x512 (from 660x660).

**Pull request merged**
