### PR TITLE
Add Fear (ERC20)

### PR DESCRIPTION
**Pull request by patchhaystacks**
Adding info for ERC20 token 'Fear'.

PR created by <a href="https://assets.trustwallet.com">TW Assets Management</a>

### CODE REVIEW

**Comment by Cryptocool1** [comment]
As per our policy, brand new tokens are not included, there is a minimum requirement of 2500 holder addresses and 5000 transactions, in order to filter out scam tokens.
See the criteria at (mentioned in the first message by the bot): https://community.trustwallet.com/t/how-to-submit-a-token-logo/3863).

**Comment by patchhaystacks** [comment]
> As per our policy, brand new tokens are not included, there is a minimum requirement of 2500 holder addresses and 5000 transactions, in order to filter out scam tokens.
> See the criteria at (mentioned in the first message by the bot): https://community.trustwallet.com/t/how-to-submit-a-token-logo/3863).

Hi there

We are listed on kucoin and Gate io and launched with our partner DAO Maker. However I am happy to wait until we meet your minimum criteria for holders.

**Comment by Cryptocool1** [comment]
Hello, can you please add link to your PR?
https://developer.trustwallet.com/add_new_asset#info-json-contents

**Comment by patchhaystacks** [comment]
Hi there

PR Link: https://github.com/trustwallet/assets/pull/11331

Please also find our project overview on DAO Maker's website:
https://daomaker.com/company/fear-nfts

If you need any other documentation from me please let me know!

Cheers

Pat

**Comment by patchhaystacks** [comment]
> Hello, can you please add link to your PR?
> https://developer.trustwallet.com/add_new_asset#info-json-contents

INFO Links added in to the PR. Cheers!

**Pull request merged**
