### PR TITLE
Add Safe Energy (BEP20)

### PR DESCRIPTION
**Pull request by safeenergyx**
Adding info for BEP20 token 'Safe Energy'.

PR created by <a href="https://assets.trustwallet.com">TW Assets Management</a>

### CODE REVIEW

**Comment by safeenergyx** [comment]
can we do payment ? or wait?

**Comment by Cryptocool1** [comment]
> can we do payment ? or wait?

yes, you can now.

**Comment by safeenergyx** [comment]
when publish ?

**Comment by safeenergyx** [comment]
can we change the logo? it doesn't look right in the wallet, it's crooked?

**Pull request merged**
