### PR TITLE
Add Zillion Logo

### PR DESCRIPTION
**Pull request by dunitech123**

### CODE REVIEW

**Comment by dunitech123** [comment]
ZAX  have more than 10k holders and 15k transactions instead of that '❌ number of holders not checked: please, check it manually' why this problem occurs ?

**Comment by Cryptocool1** [comment]
• What is the purpose of this token? How will it benefit Trust Wallet users?
 • How is the token being distributed? Are you conducting an airdrop?
 • Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?
 • Is the token listed on a centralized/decentralized exchange?
 • Is a Smart Contract audit completed? Where can we find this information?

**Comment by dunitech123** [comment]
• What is the purpose of this token? How will it benefit Trust Wallet users?
  Zax is a utility token.It has a clear purpose of access permission and governance.Token will also generate value for the 
  ecosystem stakeholder as rewards.
  Zax helps in preventing the drops in exchange and makes every transaction speedy and more efficient.

• How is the token being distributed? Are you conducting an airdrop?
  Initial coin Distribution is made through presale on pinksale. Please refer the link provided: 
  https://www.pinksale.finance/launchpad/0xC7C93E00966549C081d01Cb7b60B507c2A61c74d?chain=BSC
  There is no airdrop attach with this token

• Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?
  Yes,We have offered 14.247619% of our token as presale on pinksale.

• Is the token listed on a centralized/decentralized exchange?
  Zax token is listed on PancakeSwap decentralized exchange.

• Is a Smart Contract audit completed? Where can we find this information?
  yes, audit is completed. you can check it from here: https://github.com/Tech-Audit/Smart-Contract-Audits/blob/main/TECHAUDIT_ZAX.pdf

**Comment by dunitech123** [comment]
@Cryptocool1 
• What is the purpose of this token? How will it benefit Trust Wallet users?
Zax is a utility token.It has a clear purpose of access permission and governance.Token will also generate value for the
ecosystem stakeholder as rewards.
Zax helps in preventing the drops in exchange and makes every transaction speedy and more efficient.

• How is the token being distributed? Are you conducting an airdrop?
Initial coin Distribution is made through presale on pinksale. Please refer the link provided:
https://www.pinksale.finance/launchpad/0xC7C93E00966549C081d01Cb7b60B507c2A61c74d?chain=BSC
There is no airdrop attach with this token

• Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?
Yes,We have offered 14.247619% of our token as presale on pinksale.

• Is the token listed on a centralized/decentralized exchange?
Zax token is listed on PancakeSwap decentralized exchange.

• Is a Smart Contract audit completed? Where can we find this information?
yes, audit is completed. you can check it from here: https://github.com/Tech-Audit/Smart-Contract-Audits/blob/main/TECHAUDIT_ZAX.pdf

**Comment by dunitech123** [comment]
@Cryptocool1 please confirm that above information i have given on your questions is fulfill the acceptance criteria. 
if yes then we will pay fees

**Comment by Mariuszok12** [comment]
please write me more clearly


Mariusz

śr., 11 sty 2023, 14:27 użytkownik merge-fee-bot[bot] <
***@***.***> napisał:

**Pull request closed without merging**
