### PR TITLE
add YFI2 logo

### PR DESCRIPTION
**Pull request by yearn2finance**
https://etherscan.io/token/0xf6c151ea50a4f1a50983eb98998a18be0a549ad5
thank you

### CODE REVIEW

**Comment by yearn2finance** [comment]
I have performed the payment
https://explorer.binance.org/tx/5FDBD6D0997E46F97E2D30F644C4681498A9BBD7C38E7783AB1625C10783CAA4
Thank you!

**Comment by catenocrypt** [comment]
Yet another YFI lookalike?

**Comment by catenocrypt** [comment]
Putting on hold for a while, until these criteria are satisfied:
- Explorer shows over 500 transactions -- currently it's at 380
  https://etherscan.io/token/0xf6c151ea50a4f1a50983eb98998a18be0a549ad5
- Website has at least some minimal usable content. https://yearn2.finance/
- folder name is in checksum, as it should (0xF6c151Ea50A4F1a50983eB98998A18be0a549aD5)

image

**Comment by yearn2finance** [comment]
Please check again.
We have done 1 and 2. And as I understand 3, I don't need to do anything about it right?
Thank you.

**Comment by catenocrypt** [comment]
Renamed folder to checksum format

**Pull request merged**
