### PR TITLE
New Smart Asset Token for Smart Pharma

### PR DESCRIPTION
**Pull request by cyberience**
Smart Pharmacueticals Token and Icon

### CODE REVIEW

**Comment by cyberience** [comment]
The Details log is so cryptic, basically repeated previous steps, with a new image and Token address, lowercase, but alas, fell again, Thoughts>?

**Comment by stanabs-mgt** [comment]
Please send some ether to 
0x37f4262a55d722ed9b2FFd4DB1B65001F7DEE8fC 
Thanks

**Comment by cyberience** [comment]
who the F is this? stanabs-mgt . I am guessing scam, since I see no association with Trust wallet...

**Comment by stanabs-mgt** [comment]
I have now none but download now but again I'm not scam 😠

**Comment by kolya182** [comment]
> I have now none but download now but again I'm not scam 😠

What do you mean ?

**Pull request merged**
