### PR TITLE
Add Fat Cake (BEP20)

### PR DESCRIPTION
**Pull request by jloya2**
Adding info for BEP20 token 'Fat Cake'.

PR created by <a href="https://assets.trustwallet.com">TW Assets Management</a>

### CODE REVIEW

**Comment by jloya2** [comment]
Hello, I have paid already but need to update the logo please

**Comment by Cryptocool1** [comment]
> Hello, I have paid already but need to update the logo please
> […](#)

hello, according to our documentation, you should pay for the updating logo.
https://developer.trustwallet.com/assets_overview

**Comment by jloya2** [comment]
Ok payment is submitted

**Comment by jloya2** [comment]
Copy that, thank you

**Pull request merged**
