### PR TITLE
Add: 1776 RTT (BEP20)

### PR DESCRIPTION
**Pull request by restoretruthtoken**
Please note that this is memorabilia (NFT type) token which is not tradeable and never was. It was awarded for the OG holders of RTT token which was merged in PR #17950 hence it has only 1033 holders and will unlikely ever increase.

### CODE REVIEW

**Review by Arnu1986 — APPROVED** [review]

**Comment by restoretruthtoken** [comment]
> 

The fee has been paid. Please note that we mistakenly send it with the wrong memo (18253 vs 18353). Here is the txhash to prove it. 

D4FBEAFA97FCB1A9693F3501C027161FCB8CF212776D3BE07FCC75C101C407A2

**Comment by cryptomanz** [comment]
• What is the purpose of this token? How will it benefit Trust Wallet users?
 • How is the token being distributed? Are you conducting an airdrop?
 • Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?
 • Is the token listed on a centralized/decentralized exchange?
 • Is a Smart Contract audit completed? Where can we find this information?

**Comment by restoretruthtoken** [comment]
Hello,
 To follow up on some of the questions above,
• What is the purpose of this token? How will it benefit Trust Wallet
users? The purpose of the token was to allocate our top 1000 holders 1
token on July 4th (Independence day in America) At the time we did not have
our NFT platform built so the 1776 token was issued as a collectors item.
This token has a role in our RTT ecosystem to allow anyone that holds this
token special perks and discounts. It will be coupled with a 1776 NFT in
the coming months as we continue to deploy these items.
• How is the token being distributed? Are you conducting an airdrop?  We
airdropped the top 1000 holders of RTTv1 the 1776, again as an appreciation
with future use case in mind.
• Did you sold the tokens at an Initial Coin Offering (ICO) or a token
presale? There was no sale, and the token will never be sold.
• Is the token listed on a centralized/decentralized exchange? No, there
are no plans to ever list on an exchange
• Is a Smart Contract audit completed? Where can we find this information?
There was no audit completed as there is no plans for any trading, again
this is a token of appreciation that will play a role within our ecosystem.

Thanks,
Michael

**Comment by cryptomanz** [comment]
As per our policy, brand new tokens are not included, there is a minimum requirement of 5,000 holder addresses and 10,000 transactions, in order to filter out scam tokens.
See the criteria at : https://developer.trustwallet.com/assets/requirements

**Comment by cryptomanz** [comment]
Please come back to us when all criteria are met.
When creating a new PR make sure to mention this PR, so that we can see that fee has been paid already here.

**Comment by restoretruthtoken** [comment]
Thank you for your email. As  we have previously stated, the 1776 token
will never have more than 5,000 holders (only around 1500 total in
circulation) nor will it ever be traded, making the 10,000 transactions not
feasible. We as the RTT team have been trading since June 6th 2021, we have
had 2 contract changes and 1 name change (previously Real Trump Token, and
Real Trump Token v2. We issued the 1776 token to holders on July 4th 2021,
marking the 245th Independence day in the United States of America. At the
time we did not have our NFT marketplace ready so we did a "collector
coin". It has been our goal to provide a transparent project, ensure
members safety, and educate newcomers to the space. Please take a second
look as this is not for us as a team, but for the RTT Nation that supports
this team.

Thanks,
Michael Buckmaster - President & CFO

**Pull request closed without merging**
