### PR TITLE
Add BabyCate (BEP20)

### PR DESCRIPTION
**Pull request by BlackSpaceCreative**
Adding info for BEP20 token 'BabyCate'.

PR created by <a href="https://assets.trustwallet.com">TW Assets Management</a>

### CODE REVIEW

**Review by Nigel123321 — COMMENTED** [review]
https://github.com/trustwallet/assets/pull/29363/files#diff-0dc64763258130364bc6e7f896fb6ae6e60873569ee75604b2ad69d193cdf8e0

https://github.com/trustwallet/assets/pull/29363/files#diff-216048a634002362d85b7ce8eb9a1a87f3b463414be9d98417ac47f049746046

**Review by 9764319764319764 — COMMENTED** [review]
hamed

**Review by 9764319764319764 — COMMENTED** [review]
hamed

**Comment by cryptomanz1** [comment]
• What is the purpose of this token? How will it benefit Trust Wallet users?
 • How is the token being distributed? Are you conducting an airdrop?
 • Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?
 • Is the token listed on a centralized/decentralized exchange?
 • Is a Smart Contract audit completed? Where can we find this information?

**Comment by BlackSpaceCreative** [comment]
> • What is the purpose of this token? How will it benefit Trust Wallet users?
- BabyCare is a meme token, enjoyed by the holding community. TrustWallet users want the token to have its logo updated to conveniently track their assets when holding BabyCate Token

> • How is the token being distributed? Are you conducting an airdrop?
- BabyCate's tokenomics is mostly controlled by the community, of which 67% is issued through Presale, the remaining 33% is. added to liquidity. Details check at : https://docs.babycate.org/tokenomics
- The project is not launching any airdrop program, holders come from users trading on DEX and CEX.

> • Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?
- BabyCate has launched presale on the Pinksale platform: https://www.pinksale.finance/launchpad/bsc/0x69E70a2D94a7AbA1D446201a4980bdad0B8f878d
- 
> • Is the token listed on a centralized/decentralized exchange?
- BabyCate on MEXC : https://www.mexc.com/exchange/BABYCATE_USDT
- Pancakeswap : https://pancakeswap.finance/swap?inputCurrency=BNB&outputCurrency=0x76B560b628F74BF192bE09F0449abef8e456BE79
- 
> • Is a Smart Contract audit completed? Where can we find this information?
- BabyCate token audited by Certik : https://skynet.certik.com/projects/babycate

**Pull request merged**
