### PR TITLE
Add Pepa Inu (BEP20)

### PR DESCRIPTION
**Pull request by fab153crypto**
Adding BEP20 token 'Pepa Inu'

### CODE REVIEW

**Comment by Cryptocool1** [comment]
• What is the purpose of this token? How will it benefit Trust Wallet users?
 • How is the token being distributed? Are you conducting an airdrop?
 • Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?
 • Is the token listed on a centralized/decentralized exchange?
 • Is a Smart Contract audit completed? Where can we find this information?

**Comment by fab153crypto** [comment]
> • What is the purpose of this token? How will it benefit Trust Wallet users?

Pepa Inu aims to unite the memecoins in the crypto space while releasing fun and innovative utilites. We want to be as user-friendly as possible to attract new users into crypto. The Swap is very user friendly orientated and allows users to swap their crypto easily for $pepa

> • How is the token being distributed? Are you conducting an airdrop?

PEPA was distributed via a launchpad on pinksale.finance. 
No airdrops were distributed.

> • Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?

Yes, pinksale.finance - https://www.pinksale.finance/launchpad/0x3e6d1628f0374Aa38Dca5658422F52e8b2AaC96F?chain=BSC

> • Is the token listed on a centralized/decentralized exchange?

PEPA is currently listed on Pancakeswap & mexc.com

> • Is a Smart Contract audit completed? Where can we find this information?

Yes, https://github.com/AnalytixAudit/Solidity/blob/main/20230306_Analytix%20Audit_Pepa%20Inu_Audit.pdf

**Comment by Cryptocool1** [comment]
Please delete a tokenlist file from your PR. You should be on that list: https://coinmarketcap.com/exchanges/pancakeswap/

**Comment by fab153crypto** [comment]
Ah interesting, we followed the suggestions here: https://community.trustwallet.com/t/trust-swap-pancakeswap-trading-integration/82351

So adding the info is enough for Pepa to be available for users to swap in the TW swap interface?

**Comment by Cryptocool1** [comment]
You should be top https://coinmarketcap.com/exchanges/pancakeswap/ on that list to be listed on swap

**Comment by fab153crypto** [comment]
Yes, PEPA is ranked 85 today on https://coinmarketcap.com/exchanges/pancakeswap-v2.
PEPA was top 50 in the last few days.

I assume your link only ranks trades on v1 pairs.

**Comment by Cryptocool1** [comment]
As I please come back to us once you are on top 10-20, we will reconsider

**Comment by fab153crypto** [comment]
> please come back to us once you are on top 10-20, we will reconsider

This is in regards to the appearance on trust wallet swap, or this pull request to add the token icon and info in general?

**Pull request merged**
