### PR TITLE
Add MetaBUSDCoin (BEP20)

### PR DESCRIPTION
**Pull request by AliAkczaa**
Adding info for BEP20 token 'MetaBUSDCoin'.

PR created by <a href="https://assets.trustwallet.com">TW Assets Management</a>

### CODE REVIEW

**Comment by AliAkczaa** [comment]
guys... srsly. im adding it for 3rd time (due to "This PR is being closed due to inactivity") caz no one is answering... :D
i dont want to loose 700 bucks...

**Comment by AliAkczaa** [comment]
> • What is the purpose of this token? How will it benefit Trust Wallet users? • How is the token being distributed? Are you conducting an airdrop? • Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale? • Is the token listed on a centralized/decentralized exchange? • Is a Smart Contract audit completed? Where can we find this information?

• What is the purpose of this token? How will it benefit Trust Wallet users?
The purpose of this token is to serve a functional role within our suite of Virtual Reality enabled e-commerce solutions. Once fully integrated, eventually becoming a medium of exchange between various tokens in Virtual Reality.
• How is the token being distributed? Are you conducting an airdrop?
This token is currently bought or sold through locked liquidity in the binance smart chain.
• Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?
This token was sold to an initial public presale and through Pancakeswap liquidity pools.
• Is the token listed on a centralized/decentralized exchange?
This token is not currently listed on any centralized exchanges. The token is listed on a few decentralized exchanges.
• Is a Smart Contract audit completed? Where can we find this information?
The token has had a smart contract audit through InterFi. Please find this audit here: https://github.com/interfinetwork/smart-contract-audits/blob/audit-updates/MetaBUSD_0xF14D3692B0055Db9Ca4c04065165d59B87E763f1.pdf

**Comment by cryptomanz1** [comment]
submission looks good awaiting for the fee payment

**Review by moncho01 — COMMENTED** [review]
blockchains/smartchain/assets/0xf14d3692b0055db9ca4c04065165d59b87e763f1/logo.png

**Comment by moncho01** [comment]
Hi

**Pull request merged**
