### PR TITLE
add Logo and information for Popcorn Token (CORN)

### PR DESCRIPTION
**Pull request by popcorntoken**
add Logo and information for Popcorn Token (CORN)
Token Name : Popcorn Token
Token Symbol : CORN
Token Supply :1,811,032.06 CORN
Contract: 0x3080ec2A6960432F179c66D388099A48E82e2047

logo

### CODE REVIEW

**Comment by popcorntoken** [comment]
https://github.com/trustwallet/assets/pull/3685

already paid

**Comment by popcorntoken** [comment]
logo is not display Trust wallet

**Comment by popcorntoken** [comment]
https://github.com/trustwallet/assets/compare/master...popcorntoken:master

**Comment by catenocrypt** [comment]
Removed unneeded blockchains/ethereum/assets/0x3080ec2A6960432F179c66D388099A48E82e2047.png.

**Comment by catenocrypt** [comment]
Token check ok, builds ok

**Pull request merged**
