### PR TITLE
Add DOITcoin (BEP20)

### PR DESCRIPTION
**Pull request by gumballpuncks**
This PR is being closed due to inactivity. If you wish to continue, please have us reopen the PR before sending your payment, or just create a new one.
Do NOT send payments for closed PR, as the fee may by lost!
  (48 vs. 48 hrs)

### CODE REVIEW

**Comment by cryptomanz** [comment]
Hello,
- Submission looks good. awaiting fee payment.

**Comment by DOITcoin** [comment]
One question does not accept bnb Smart chain and I will see my logo in pancakeswap too ?
Thanks You

**Comment by DOITtt2** [comment]
One question does not accept bnb Smart chain and I will see my logo in pancakeswap too

**Comment by Cryptocool1** [comment]
> One question does not accept bnb Smart chain and I will see my logo in pancakeswap too

?

**Pull request closed without merging**
