### PR TITLE
Added RDNT v2 on BSC

### PR DESCRIPTION
**Pull request by JD0x2e**

### CODE REVIEW

**Comment by Cryptocool1** [comment]
As per our policy, there is a minimum requirement of 10,000 holder addresses and 15,000 transactions, in order to filter out scam tokens.
See the criteria at : https://developer.trustwallet.com/listing-new-assets/requirements .

**Comment by JDoy99** [comment]
Radiant has 33,000 token holders on the v1 token, and 6,000 holders on the v2 token- both of which are on Arbitrum. [Arbiscan](https://arbiscan.io/token/0x0c4681e6c0235179ec3d4f4fc4df3d14fdd96017) Radiant is expanding to the BNB Chain today, and this is a request from Pancakeswap to whitelist the token. We will tweet from our official [Twitter](https://twitter.com/RDNTCapital) , tag Trustwallet, and mention the pull request # to verify the legitimacy of this request

**Comment by JDoy99** [comment]
> What is a v1 contract address?

Click the Arbiscan link in the comment, or its here https://arbiscan.io/token/0x0C4681e6C0235179ec3D4F4fc4DF3d14FDD96017

**Comment by Cryptocool1** [comment]
That link is redirecting to new arbitrum address.I don’t see your BEP20 address on CMC

**Comment by JDoy99** [comment]
> That link is redirecting to new arbitrum address.I don’t see your BEP20 address on CMC

image
0x0C4681e6C0235179ec3D4F4fc4DF3d14FDD96017

**Comment by JDoy99** [comment]
> Yep, but you are trying to add BEP20 address with 10 holders.

Radiant migrated from ERC-20 to Layer Zero's Omnifungible token standard OFT-20. This enables RDNT to be natively bridged cross-chain via the Layer Zero bridge, similar to the Stargate token (STG).

**Comment by Cryptocool1** [comment]
This message should be on official twitter account or CMC page. ( with contract address that you are trying to add)

**Comment by JDoy99** [comment]
> This message should be on official twitter account or CMC page. ( with contract address that you are trying to add)

https://twitter.com/RDNTCapital/status/1640433124839415809 We are now live on BSC

**Comment by JDoy99** [comment]
> I need to see contract address there. Thanks

It was there in the comments.. 

https://twitter.com/RDNTCapital/status/1640452034137845762

**Comment by Cryptocool1** [comment]
Please update your branch with the recent master

**Comment by JDoy99** [comment]
> your folder should be in checksum `0xf7DE7E8A6bd59ED41a4b5fe50278b3B7f31384dF` Unfortunately, I cannot fix that for you because you have private branch

image

**Comment by Cryptocool1** [comment]
Not your id, I mean your folder.

**Comment by Cryptocool1** [comment]
No, it’s not. Here what you have: blockchains/smartchain/assets/0xf7de7e8a6bd59ed41a4b5fe50278b3b7f31384df/info.json

**Comment by Cryptocool1** [comment]
Same for logo file

**Comment by JDoy99** [comment]
> Same for logo file

image

**Comment by Cryptocool1** [comment]
Push the changes

**Comment by JDoy99** [comment]
@Cryptocool1 I think the folder is good to go now, please confirm

**Pull request merged**
