### PR TITLE
Add DCB token info and logo

### PR DESCRIPTION
**Pull request by AIDidMyHomework**
This PR is being closed due to inactivity. If you wish to continue, please have us reopen the PR before sending your payment, or just create a new one.
Do NOT send payments for closed PR, as the fee may by lost!
  (474 vs. 48 hrs)

### CODE REVIEW

**Comment by cryptomanz** [comment]
Hello,
- As per our policy, brand new tokens are not included, there is a minimum requirement of 2500 holder addresses and 5000 transactions, in order to filter out scam tokens.
See the criteria at (mentioned in the first message by the bot): https://community.trustwallet.com/t/how-to-submit-a-token-logo/3863).
Closing PR for now. Please come back to us when all criteria are met.

**Comment by mj-dcb** [comment]
> Hello,
> 
> * As per our policy, brand new tokens are not included, there is a minimum requirement of 2500 holder addresses and 5000 transactions, in order to filter out scam tokens.
>   See the criteria at (mentioned in the first message by the bot): https://community.trustwallet.com/t/how-to-submit-a-token-logo/3863).
>   Closing PR for now. Please come back to us when all criteria are met.

Hey Cryptomanz, we have more than 4k holders and 12k tx's. Could you reopen the PR? :) Thanks.

**Comment by mj-dcb** [comment]
@Cryptocool1 please reopen it so we can pay the fee.

**Comment by Pierre764** [comment]
Please Reopen PR for us to make payment. I'll keep an eye on it every hour as your bot is pretty quick closing the PR before we can take action!
Many thanks!

**Comment by Pierre764** [comment]
Is there a way to stop the bot from closing the PR after 30 mins?
I was on the call when you reopened, to find it closed when wanting to make payment...
Now I am free to monitor the PR, please reopen asap

**Comment by mj-dcb** [comment]
@Cryptocool1 the bot is driving us nuts.

**Comment by Pierre764** [comment]
Please Reopen PR for us to make payment. 
Could not pay last week when you reopened, I was on a phone call and the bot closed the PR by the time I hung up!
Many thanks

**Comment by Pierre764** [comment]
Payment has been made 
image

**Comment by Cryptocool1** [comment]
hello,
• What is the purpose of this token? How will it benefit Trust Wallet users?
 • How is the token being distributed? Are you conducting an airdrop?
 • Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?
 • Is the token listed on a centralized/decentralized exchange?
 • Is a Smart Contract audit completed? Where can we find this information?

**Comment by Pierre764** [comment]
Hi there,

1- DCB, our utility token, will be used on the Decubate platform for
various purposes such as governance rights, staking, and rewards to the
community for their feedback on the different startups we will offer.
See full utility here: https://decubate.gitbook.io/documentation/the-token

2- Please see full token allocation and distribution, including vesting
schedule, at the below link:
https://decubate.gitbook.io/documentation/tokenomics

3- Token Presale took place as follows:

Seed Sale %0.0055 – 50M Tokens (5%)  May-June 2021

Strategic Sale $0.009 - 50M Tokens (5%)  May-June 2021

Private Sale $0.012 - 26.7M tokens (2.67%)  May-June 2021

Public sale: $0.015 – 23.3M tokens (2.33%) 6th of July 2021


4- The token is currently only listed on a DEX, PancakeSwap. See token info
at the following link:
https://pancakeswap.info/token/0xeac9873291ddaca754ea5642114151f3035c67a2


5- Our smart is currently being audited by Haechi labs and the outcome will
be released within the next 2 weeks.

Many thanks!

**Comment by Pierre764** [comment]
Hi there, 

1- DCB, our utility token, will be used on the Decubate platform for various purposes such as governance rights, staking, and rewards to the community for their feedback on the different startups we will offer.
See full utility here: https://decubate.gitbook.io/documentation/the-token

2- Please see full token allocation and distribution, including vesting schedule, at the below link:
https://decubate.gitbook.io/documentation/tokenomics

3- Token Presale took place as follows:
Seed Sale %0.0055 – 50M Tokens (5%)  May-June 2021

Strategic Sale $0.009 - 50M Tokens (5%)  May-June 2021

Private Sale $0.012 - 26.7M tokens (2.67%)  May-June 2021

Public sale: $0.015 – 23.3M tokens (2.33%) 6th of July 2021


4- The token is currently only listed on a DEX, PancakeSwap. See token info at the following link:
https://pancakeswap.info/token/0xeac9873291ddaca754ea5642114151f3035c67a2



5- Our smart is currently being audited by Haechi labs and the outcome will be released within the next 2 weeks.

Many thanks!

**Comment by Cryptocool1** [comment]
awaiting for smart contract audit

**Comment by Cryptocool1** [comment]
please create new PR when smart contract audit will be ready to send.
Make sure to mention this PR, so that we can see that fee has been paid already here.

**Comment by Cryptocool1** [comment]
can you please add links to your PR?
example: https://developer.trustwallet.com/add_new_asset/repository_details

**Comment by Pierre764** [comment]
https://team.finance/view-coin/0xEAc9873291dDAcA754EA5642114151f3035c67A2?name=Decubate%20Token&symbol=DCB

**Comment by Pierre764** [comment]
[[HAECHI AUDIT] Decubate Smart Contract Audit Report.pdf](https://github.com/trustwallet/assets/files/6956893/HAECHI.AUDIT.Decubate.Smart.Contract.Audit.Report.pdf)

**Pull request merged**
