### PR TITLE
Add TendaCoin (BEP20)

### PR DESCRIPTION
**Pull request by tendacoin**
Adding info for BEP20 token 'TendaCoin'.

PR created by <a href="https://assets.trustwallet.com">TW Assets Management</a>

### CODE REVIEW

**Comment by Cryptocool1** [comment]
• What is the purpose of this token? How will it benefit Trust Wallet users?
 • How is the token being distributed? Are you conducting an airdrop?
 • Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?
 • Is the token listed on a centralized/decentralized exchange?
 • Is a Smart Contract audit completed? Where can we find this information?

**Comment by tendacoin** [comment]
> • What is the purpose of this token? How will it benefit Trust Wallet users? • How is the token being distributed? Are you conducting an airdrop? • Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale? • Is the token listed on a centralized/decentralized exchange? • Is a Smart Contract audit completed? Where can we find this information?

**• What is the purpose of this token? How will it benefit Trust Wallet users?**
The purpose of creating **TendaCoin** is to make Global Payments on ecommerce websites and online shopping.
**TendaCoin** is a DeFi Token with static rewards, LP acquisition, manual and automatic burn, 100% community driven & fair lunch. Dev burned all team tokens and participated in the fair lunch with everyone else. Automatic LP every trade contributes toward automatically generating liquidity locked inside PancakeSwap LP. RFI Static Rewards Holders earn passive rewards through static reflection as they watch their balance of **TendaCoin** grow indefinitely.
100% Liquidity locked on Team Finance for 3 years.
26.9% TendaCoin Tokens locked on Team Finance for 3 years.
The user on Trust Wallet can see the price of $TND and also they can easily transfer or buy their tokens and keep safe.

**• How is the token being distributed? Are you conducting an airdrop?**
The token is being distributed through centralized/decentralized exchange. No.

**• Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?**
Yes, we have presale.

**• Is the token listed on a centralized/decentralized exchange?**
[PancakeSwap](https://pancakeswap.finance/swap?outputCurrency=0x07a3554899d97a087bda931dd5224b3b7435e568
)  / [Hotbit](https://www.hotbit.io/exchange?symbol=TENDACOIN_nUSD)

**• Is a Smart Contract audit completed? Where can we find this information?**
https://tendacoin.com/file/2022/05/TendaCoin-Audit-Report.pdf
[Team Finance](https://www.team.finance/view-coin/0x07a3554899D97a087Bda931Dd5224B3B7435E568?name=TendaCoin&symbol=TND)

**Comment by Cryptocool1** [comment]
We accept audit only from reputable companies. ( Certik, Techrate, Dessert Finance, Hacken)

**Comment by Cryptocool1** [comment]
Please come back to us when all criteria are met. Make sure to mention this PR so the fee can be reused.

**Comment by tendacoin** [comment]
> We accept audit only from reputable companies. ( Certik, Techrate, Dessert Finance, Hacken)

https://tendacoin.com/file/2022/05/TendaCoin-by-TechRate.pdf

**Pull request closed without merging**
