### PR TITLE
Add Nadeshiko (BEP20)

### PR DESCRIPTION
**Pull request by ghost**
Adding info for BEP20 token 'Nadeshiko'.

PR created by <a href="https://assets.trustwallet.com">TW Assets Management</a>

### CODE REVIEW

**Comment by Nadeshikocoin** [comment]
logo.png
20210415-2335_8ebd5ba90dd7ede7bbaa4bbe61c00353

**Comment by Nadeshikocoin** [comment]
#6532と同一です。
支払い済みですが、これで大丈夫ですか？

**Comment by catenocrypt** [comment]
As per our policy, brand new tokens are not included, there is a minimum requirement of 2500 holder addresses and 5000 transactions, in order to filter out scam tokens.
See the criteria at (mentioned in the first message by the bot): https://community.trustwallet.com/t/how-to-submit-a-token-logo/3863).
This token has low usage yet (92 holders). Closing PR for now. Please come back to us when all criteria are met.  Multi-chain and staking tokens may get special treatment, let us know if this is the case. 

https://bscscan.com/token/0x568B0D8ac3967d363257C520c9Be0f17984E470f

**Comment by Nadeshikocoin** [comment]
Hello.
Thank you for the screening the other day!
I haven't met the criteria yet, but could you please manage to post my logo
and price?
We're going to be listed on CEX next month!
I'd like to spread the word about us somehow.
Thank you very much!

2021年4月22日(木) 18:29 Adam R ***@***.***>:

**Pull request closed without merging**
