### PR TITLE
Add HeroFiEgg (BEP20)

### PR DESCRIPTION
**Pull request by HeroFiTech**
Info for token HeroFiEgg

### CODE REVIEW

**Comment by Cryptocool1** [comment]
hello,
• What is the purpose of this token? How will it benefit Trust Wallet users?
 • How is the token being distributed? Are you conducting an airdrop?
 • Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?
 • Is the token listed on a centralized/decentralized exchange?
 • Is a Smart Contract audit completed? Where can we find this information?

**Comment by HeroFiTech** [comment]
Hello @Cryptocool1,
Please our answers a below

• What is the purpose of this token? How will it benefit Trust Wallet users?
=> HeroFi is a mobile aRPG game in which players can earn tokens through PvP/PvE battles between Heroes.
100,000 HEROEGG will hatch a special character NFT called Genesis Hero that has a gender (either male or female) and a star rating (from three to six).

• How is the token being distributed? Are you conducting an airdrop?
=>HEROEGG is distributed through IDO. We don't do airdrop

• Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?
=> We've done public sale for HEROEGG on September 06th 2021 on **_pad.lz.finance_** (LaunchZone).

• Is the token listed on a centralized/decentralized exchange?
=> on dex **_swap.lz.finance_**

• Is a Smart Contract audit completed? Where can we find this information?
=> not yet

**Comment by cryptomanz** [comment]
Hello,
- Awaiting for smart contract audit.

**Comment by Cryptocool1** [comment]
Please create new PR when smart contract audit will be ready. Make sure to mention this PR so the fee can be reused.

**Pull request closed without merging**
