### PR TITLE
DEA logo update

### PR DESCRIPTION
**Pull request by bi0hazard12**
This PR is being closed due to inactivity. If you wish to continue, please have us reopen the PR before sending your payment.
Do NOT send payments for closed PR, as the fee may by lost!
  (82 vs. 60 hrs)

### CODE REVIEW

**Comment by bi0hazard12** [comment]
Can someone confirm if just updating the logo need to pay a fee for it ?

Thank you

**Comment by catenocrypt** [comment]
Reopen

**Comment by catenocrypt** [comment]
Tokens+info files already exist (#5167), this is update.  Fee still needed.

**Comment by bi0hazard12** [comment]
Will pay the fee soon. Can we reopen ? Thks

**Pull request closed without merging**
