### PR TITLE
Add Carypto (BEP20)

### PR DESCRIPTION
**Pull request by gangnam85**
Adding info for BEP20 token 'Carypto'.

PR created by <a href="https://assets.trustwallet.com">TW Assets Management</a>

### CODE REVIEW

**Comment by cryptomanz** [comment]
• What is the purpose of this token? How will it benefit Trust Wallet users?
 • How is the token being distributed? Are you conducting an airdrop?
 • Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?
 • Is the token listed on a centralized/decentralized exchange?
 • Is a Smart Contract audit completed? Where can we find this information?

**Comment by gangnam85** [comment]
1. To make it easier to verify the assets held by the crypto coin
2. Some Air Drops
3. ICO token will be pre-sold.
4. It will be listed on a centralized exchange.
5. Do not proceed with smart audit

**Comment by gangnam85** [comment]
When will the token information be updated?

**Comment by gangnam85** [comment]
#20124 When will the token information be updated?

**Comment by gangnam85** [comment]
Add Carypto (BEP20) #20124

**Comment by gangnam85** [comment]
Please reply.

**Pull request closed without merging**
