### PR TITLE
Add CBC logo and info

### PR DESCRIPTION
**Pull request by CoMeCNES**
Add CBC logo and info

### CODE REVIEW

**Comment by cryptomanz** [comment]
Hello,
Can your answer some questions?
 • What is the purpose of this token? How will it benefit Trust Wallet users?
 • How is the token being distributed? Are you conducting an airdrop?
 • Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?
 • Is the token listed on a centralized/decentralized exchange?
 • Is a Smart Contract audit completed? Where can we find this information?

**Comment by CoMeCNES** [comment]
• What is the purpose of this token? How will it benefit Trust Wallet users?
A decentralized digital token dedicated to promoting carbon neutrality. To give back to our community via $USDT rewards

• How is the token being distributed? Are you conducting an airdrop?
No presale, it was a fair launch

• Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?
Not currently

• Is the token listed on a centralized/decentralized exchange?
https://pancakeswap.finance/swap?outputCurrency=0x793cEa0F1003411396b3A81A77d92Fe37015E7A9

• Is a Smart Contract audit completed? Where can we find this information?
Our website has the audit: https://carbon-netrual.global/doc/CNES_CarbonCoin_audit.pdf

**Comment by CoMeCNES** [comment]
> Hello,
> Can your answer some questions?
> • What is the purpose of this token? How will it benefit Trust Wallet users?
> • How is the token being distributed? Are you conducting an airdrop?
> • Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?
> • Is the token listed on a centralized/decentralized exchange?
> • Is a Smart Contract audit completed? Where can we find this information?

• What is the purpose of this token? How will it benefit Trust Wallet users?
A decentralized digital token dedicated to promoting carbon neutrality. To give back to our community via $USDT rewards

• How is the token being distributed? Are you conducting an airdrop?
No presale, it was a fair launch

• Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?
Not currently

• Is the token listed on a centralized/decentralized exchange?
https://pancakeswap.finance/swap?outputCurrency=0x793cEa0F1003411396b3A81A77d92Fe37015E7A9

• Is a Smart Contract audit completed? Where can we find this information?
Our website has the audit: https://carbon-netrual.global/doc/CNES_CarbonCoin_audit.pdf

**Comment by Cryptocool1** [comment]
can you please add links to your PR?
example: https://developer.trustwallet.com/add_new_asset/repository_details

**Comment by CoMeCNES** [comment]
> can you please add links to your PR?
> example: https://developer.trustwallet.com/add_new_asset/repository_details

We added the links

**Pull request merged**
