### PR TITLE
Add PointPay Token (ERC20)

### PR DESCRIPTION
**Pull request by YevheniiaShmelkova**
Adding info for ERC20 token 'PointPay Token'.

PR created by <a href="https://assets.trustwallet.com">TW Assets Management</a>

### CODE REVIEW

**Comment by Cryptocool1** [comment]
• Is a Smart Contract audit completed? Where can we find this information?

**Comment by YevheniiaShmelkova** [comment]
> • Is a Smart Contract audit completed? Where can we find this information?

Hi! Yes, please find the contract audit via the link below:
https://www.certik.com/projects/pointpay

**Comment by YevheniiaShmelkova** [comment]
> This PR is being closed due to inactivity. If you wish to continue, please have us reopen the PR before sending your payment, or just create a new one. Do NOT send payments for closed PR, as the fee may by lost!

Please, reopen the PR. We want to send the payment soon.

**Comment by YevheniiaShmelkova** [comment]
Hi! I have created a new pull request as this one was closed. I've used the
same tool that you sent to me but I received the email that it failed.

Can you check, please and let me know if we can pay the fee and finally
update our logo? PR #22331

Best regards

*Yevheniia Shmelkova*

Content Writer at PointPay

https://pointpay.io

**Pull request closed without merging**
