### PR TITLE
Added QuiverX logo and info.

### PR DESCRIPTION
**Pull request by xEarn-Capital**
This PR is being closed due to inactivity. If you wish to continue, please have us reopen the PR before sending your payment.
Do NOT send payments for closed PR, as the fee may by lost!
  (60 vs. 60 hrs)

### CODE REVIEW

**Comment by QuiverX** [comment]
Hello if the fee was already paid previously, do we have to pay it a second time?

**Comment by QuiverX** [comment]
Reference: Initial request and full payment. 

https://github.com/trustwallet/assets/pull/4562

**Comment by catenocrypt** [comment]
If there was an unmerged PR, re-submitting the same info in a new PR does not require a new fee.  But please mention the previous PR.

**Comment by flisko** [comment]
> If there was an unmerged PR, re-submitting the same info in a new PR does not require a new fee. But please mention the previous PR.

I already mentioned it.
Reference: Initial request and full payment.

#4562

**Pull request closed without merging**
