### PR TITLE
Add ctr

### PR DESCRIPTION
**Pull request by tonyctr**
Add Creator chain icon and info

### CODE REVIEW

**Comment by Cryptocool1** [comment]
• Is a Smart Contract audit completed? Where can we find this information?

**Comment by Cryptocool1** [comment]
please add the description of your token to info.json file

**Comment by tonyctr** [comment]
> • Is a Smart Contract audit completed? Where can we find this information?

Yes,
On ETH: https://www.certik.org/projects/creatorchain
On  BSC: we use anyswap to bridge from eth

**Comment by Cryptocool1** [comment]
Please create new PR, follow doc https://community.trustwallet.com/t/how-to-submit-a-token-logo/3863
You may want to try our Assets app in beta; go to https://assets.trustwallet.com, log on with Github, enter contract ID, logo and some additional info, and it will create a PR for you.
See https://community.trustwallet.com/t/how-to-submit-a-token-logo-using-assets-app/82957.

**Pull request closed without merging**
