### PR TITLE
Add LKSCOIN

### PR DESCRIPTION
**Pull request by omarbaruzzo**
Addition of LKSCOI (LKSC) the first crypto that works on double blockchain: X11 and ERC20

### CODE REVIEW

**Comment by omarbaruzzo** [comment]
Please ask for the addition of this token that works in blockchain double x11 and erc20 (LKSCOIN - LKSC)

**Comment by omarbaruzzo** [comment]
Please ask for the addition of this token that works in blockchain double x11 and erc20 (LKSCOIN - LKSC)

**Comment by omarbaruzzo** [comment]
ADD LKSCOIN

**Comment by omarbaruzzo** [comment]
https://explorer.binance.org/tx/50A17FE4EF9A79700F87F1A7F0DB580A94BA2260F0C466E67376A8707F148F1D

**Comment by zachzwei** [comment]
It looks like you also submitted the token under blockchains as well. 
This will just add it to the asset repo.
There is a different process for adding new blockchains. 
You can read all about it here:
https://community.trustwallet.com/t/i-am-a-developer-and-i-want-to-contribute/184#add-a-new-coin-or-blockchain

**Pull request merged**
