### PR TITLE
Add new BSL Token

### PR DESCRIPTION
**Pull request by ericwingate**

### CODE REVIEW

**Comment by cryptomanz** [comment]
Hello,
Your logo should be a full screen (256x256).
Example:
Screenshot 2021-10-01 at 01 52 16

**Comment by ericwingate** [comment]
> Hello,
> Your logo should be a full screen (256x256).
> Example:
> Screenshot 2021-10-01 at 01 52 16

Can we please get this merged today if possible? The image we used is exactly the same image that we have used before in the past and had no issues with merging.

**Comment by Cryptocool1** [comment]
> > Hello,
> > Your logo should be a full screen (256x256).
> > Example:
> > Screenshot 2021-10-01 at 01 52 16
> 
> Can we please get this merged today if possible? The image we used is exactly the same image that we have used before in the past and had no issues with merging.

Hello, as @cryptomanz mentioned, your logo should be the full size, otherwise it will look incorrectly on TW.

**Comment by ericwingate** [comment]
Ok, I have uploaded a new token logo which is 256x256.  Please check.

**Comment by ericwingate** [comment]
I am going by the instructions posted here -> https://community.trustwallet.com/t/how-to-submit-a-token-logo/3863

**Comment by ericwingate** [comment]
Download the image please, and see that the dimensions are 256x256 and the background is transparent PNG.

**Comment by ericwingate** [comment]
> * Could you delete this file, please?
> 
> Screenshot 2021-10-06 at 10 29 42

Ok, the file has been removed.

**Pull request merged**
