### PR TITLE
add tomoe logo

### PR DESCRIPTION
**Pull request by khaihkd**

### CODE REVIEW

**Comment by catenocrypt** [comment]
As per our policy, brand new tokens are not included, there is a minimum requirement of 500 holder addresses and 1000 transactions, in order to filter out scam tokens.
See the criteria at (mentioned in the first message by the bot): https://community.trustwallet.com/t/how-to-submit-a-token-logo/3863#how-to-get-approved
This token has minimal usage yet (2). Putting PR on hold. Please come back to us when all criteria are met.

https://etherscan.io/token/0x05D3606d5c81EB9b7B18530995eC9B29da05FaBa

**Comment by khaihkd** [comment]
thanks for your feedback, we will back in a few days.

**Comment by khaihkd** [comment]
@catenocrypt now we have  100+ holders and 1000+ transactions. Is it enough?

**Comment by khaihkd** [comment]
And now FTX list us https://twitter.com/SBF_Alameda/status/1310561515724967938?s=19

We are TomoChain, and we create an ERC20 cross chain token.

**Comment by khaihkd** [comment]
@zachzwei @catenocrypt  Can you help us review this pull request?

**Comment by catenocrypt** [comment]
Please add an `info.json` file next to the `logo.png`, with info about the project, of the form:

```json
{
    "name": "Trust Wallet Token",
    "website": "https://trustwallet.com",
    "short_description": "Utility token to increase adoption of cryptocurrency.",
    "explorer": "https://explorer.binance.org/asset/TWT-8C2"
}
```

**Comment by khaihkd** [comment]
@catenocrypt I updated. Please check again. Thanks

**Comment by khaihkd** [comment]
@zachzwei @catenocrypt Can you help us review this pull request?

**Comment by Iamdeadlyz** [comment]
Making an exception since this is existing in your own mainnet already 👍

**Comment by khaihkd** [comment]
thank you. We made a token cross chain to make other products

**Pull request merged**
