### PR TITLE
Added DXG logo + info, added DEXI links

### PR DESCRIPTION
**Pull request by Techtnology**
Added DXG logo + info, added DEXI links

### CODE REVIEW

**Comment by Techtnology** [comment]
I already paid for this PR: https://github.com/trustwallet/assets/pull/14706

**Comment by Techtnology** [comment]
Thanks for adding the payment succes label, is everything now okay for the merge?

**Comment by Cryptocool1** [comment]
• What is the purpose of this token? How will it benefit Trust Wallet users?
 • How is the token being distributed? Are you conducting an airdrop?
 • Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?
 • Is the token listed on a centralized/decentralized exchange?
 • Is a Smart Contract audit completed? Where can we find this information?

**Comment by Techtnology** [comment]
• What is the purpose of this token? How will it benefit Trust Wallet users?:

The purpose of this token is to serve as a in- game currency in our gaming eco-system.

• How is the token being distributed? Are you conducting an airdrop?: 

we’re not conducting an airdrop. 

• Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?: 

We sold the token in a presale on dxsale.

• Is the token listed on a centralized/decentralized exchange?:

The token is listed on pancakeswap (decentralized)

• Is a Smart Contract audit completed? 
Where can we find this information?: 

https://dexioprotocol.com/wp-content/uploads/2021/10/Brewlabs-Dexigas-Block-11732853.pdf

**Pull request merged**
