### PR TITLE
Add logo on TWT

### PR DESCRIPTION
**Pull request by botter-eng**
We have recently migrated to a new contract! So the logo and name will be the same as the v1 for which Trust wallet already shows a logo! Please check this for official announcement : https://twitter.com/LTRBTtwt/status/1557298235878035456 ! It is also updated on our Coinmarketcap page : https://coinmarketcap.com/currencies/little-rabbit-v2/ ! Your team can contact us at our official email to confirm the same : contact@littlerabbitproject.com !

### CODE REVIEW

**Comment by Cryptocool1** [comment]
• What is the purpose of this token? How will it benefit Trust Wallet users?
 • How is the token being distributed? Are you conducting an airdrop?
 • Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?
 • Is the token listed on a centralized/decentralized exchange?
 • Is a Smart Contract audit completed? Where can we find this information?

**Comment by botter-eng** [comment]
Hello! I have answered your questions below!

=> We wish to use this token (Little Rabbit) for staking with a sustainable
apy within the next 2 months and can benefit Trust Wallet users by
providing them with passive income. We have over 400k holders in v1 ( we
will migrate them to v2 soon) who are mostly on Trust Wallet! So Having the
logo on Trust wallet will hugely benefit those set of users.

=>9.4k holders have migrated using a dapp ( evermigrate) 10 days ago! and
We have launched v2 later! We have gained the remaining holders via their
own buys on Pancakeswap. We are not conducting an airdrop right now. But we
will be airdropping v1 holders with v2 tokens later on ( manually migrating
them).

=>No, There was no such ICO/Presale.

=> Yes. Little Rabbit token is listed on Pancakeswap and Radioshack

Links : Pancakeswap (
https://pancakeswap.finance/swap?outputCurrency=0x6c46422a0f7dbbad9bec3bbbc1189bfaf9794b05
)

Radioshack (
https://app.radioshack.org/swap?&outputCurrency=0x6C46422A0f7dbbAD9BEC3BbBC1189bfAf9794B05&chainId=56&r=1vgxvv92
)

=> No! We have not completed an audit for the smart contract yet. But
planning to do it later. ( BTW our Smart contract is verified on BSC SCAN
for anyone to check)

**Comment by Cryptocool1** [comment]
hello, we require smart contract audit. See  https://developer.trustwallet.com/assets/requirements .
On hold for now

**Comment by botter-eng** [comment]
Hello Trustwallet Team.
We will get an audit ready asap!
We are planning to get an audit done by Dessertswap (dessertswap.finance)
or Solidproof ! Is your team ok with the audits done by these companies?
If not, please do share some audit companies you think worth looking into.
Thank you. Regards
Little Rabbit Team.

**Comment by Cryptocool1** [comment]
> Hello Trustwallet Team. We will get an audit ready asap! We are planning to get an audit done by Dessertswap (dessertswap.finance) or Solidproof ! Is your team ok with the audits done by these companies? If not, please do share some audit companies you think worth looking into. Thank you. Regards Little Rabbit Team.
> […](#)

Sure, it’s ok

**Comment by botter-eng** [comment]
Thanks!
We have just paid for an Audit  to Dessert swap finance!  ( proof :
https://t.me/dessertswap/25328 )
It should be ready in 3 days!
Please do not close this pull request, We will try to get back to you as
soon as possible.

**Comment by botter-eng** [comment]
Hey CryptoA.
We have audited our smart contract as told earlier .

Audit Report by Dessertswap :
https://dessertswap.finance/audits/Little-Rabbit-BSC-Audit-20640364.pdf

Please check it and merge the commit!
Hoping we could see our logo soon on Trust Wallet.
Thank you. Regards
Little Rabbit Team.

**Pull request merged**
