### PR TITLE
Add SUBX FINANCE LAB (BEP20)

### PR DESCRIPTION
**Pull request by kawaijoe**
Adding info for BEP20 token 'SUBX FINANCE LAB'.

PR created by <a href="https://assets.trustwallet.com">TW Assets Management</a>

### CODE REVIEW

**Comment by kawaijoe** [comment]
**• What is the purpose of this token? How will it benefit Trust Wallet users?**
SUBX FINANCE LAB is a blockchain-as-a-service provider for businesses to integrate web3 technologies into their products and services. Our products empower businesses to innovate with blockchain, metaverse and decentralized finance technology - in a simple, fast and cost-efficient manner. Usage of our products is billable in our native SUBX FINANCE LAB TOKENS ($SFX). 

Many of our holders use Trust Wallet and the enhanced experience will greatly benefit them. It will also help differentiate different fraudulent $SFX token with the correct one.

**• How is the token being distributed? Are you conducting an airdrop?**
Tokens are being distributed through an IDO on PinkSale. Holders of our legacy token SUBX are migrated over to SFX on a vesting schedule. No airdrops are conducted.

**• Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?**
Token Presale (IDO) on PinkSale.
https://www.pinksale.finance/#/launchpad/0xac191332aC0C0a1Ee0689D447b1c42D2a59f1c86?chain=BSC

**• Is the token listed on a centralized/decentralized exchange?**
Currently listed on DEX (PCS). Will be listed on ProBit soon.

**• Is a Smart Contract audit completed? Where can we find this information?**
Our contract is pre-audited by Certik and Hacken.

You may find more information from the following link:
https://link.subx.finance/audit

Please let me know if everything is good, I would like to make payment. Thank you :)

**Comment by Cryptocool1** [comment]
As per our policy, brand new tokens are not included, there is a minimum requirement of 25,000 holder addresses and 50,000 transactions, in order to filter out scam tokens.
See the criteria at : https://developer.trustwallet.com/assets/requirements .

**Comment by kawaijoe** [comment]
@Cryptocool1 Thank you for your reply! We're already on Trust Wallet, but we recently migrated our token and need an update on our branding and contract address.

See #7927 for our legacy token.

**Comment by Cryptocool1** [comment]
Can you send and official announcement about migration?

**Comment by kawaijoe** [comment]
**Official announcement of our rebranding:**
https://twitter.com/officialsubx/status/1455821956813520903?t=w0i8pBBHXcdDp6Ja-olpbQ&s=19

**Migration deck describing the migration process:**
https://subx.finance/migration

Please let me know if you need anything else.

**Comment by Cryptocool1** [comment]
what is you abandoned contract address?

**Comment by kawaijoe** [comment]
**Our legacy contract address (SUBX):** 0x5232152c8207653AEda5baa0ff7fb1046c23C753
**Our new contract address (SFX):** 0x4CbdA3D23c031cd403db2d24512aD920BF22f205

**Comment by cryptomanz** [comment]
#16196

**Pull request closed without merging**
