### PR TITLE
Add CHIBI logo and info

### PR DESCRIPTION
**Pull request by Chibi-Inu**
Adding Chibi Inu token to trustwallet

### CODE REVIEW

**Comment by Chibi-Inu** [comment]
Guide me what I need to do?

**Comment by Cryptocool1** [comment]
Correction needed:
 Contract is not in checksum format, should be 0x504BeAf9B74f5e38B0AC2335c51B8BB6E86F0eC5

**Comment by Chibi-Inu** [comment]
How to edit it? Kindly please guide me.

**Comment by Chibi-Inu** [comment]
> Correction needed:
> Contract is not in checksum format, should be 0x504BeAf9B74f5e38B0AC2335c51B8BB6E86F0eC5

How to edit it? Kindly please guide me. Still don't know what to edit? If File name, how to do? I tried to find edit option but didnt succeed.

**Comment by Cryptocool1** [comment]
> > Correction needed:
> > Contract is not in checksum format, should be 0x504BeAf9B74f5e38B0AC2335c51B8BB6E86F0eC5
> 
> How to edit it? Kindly please guide me. Still don't know what to edit? If File name, how to do? I tried to find edit option but didnt succeed.

If you can't rename files in the PR, you may open a new PR. Make sure to mention this PR, so that we can see that fee has been paid already here.
Please create new PR, follow doc https://community.trustwallet.com/t/how-to-submit-a-token-logo/3863
You may want to try our new Assets app in beta; go to https://assets.trustwallet.com, log on with Github, enter contract ID, logo and some additional info, and it will create a PR for you.
See https://community.trustwallet.com/t/how-to-submit-a-token-logo-using-assets-app/82957.
thanks)

**Comment by Cryptocool1** [comment]
Too many changed files (903)
Please create new PR, follow doc https://community.trustwallet.com/t/how-to-submit-a-token-logo/3863
You may want to try our new Assets app in beta; go to https://assets.trustwallet.com, log on with Github, enter contract ID, logo and some additional info, and it will create a PR for you.
See https://community.trustwallet.com/t/how-to-submit-a-token-logo-using-assets-app/82957.
you don't need to pay one more time.
Closing this PR for now

**Comment by Chibi-Inu** [comment]
> Too many changed files (903)
> Please create new PR, follow doc https://community.trustwallet.com/t/how-to-submit-a-token-logo/3863
> You may want to try our new Assets app in beta; go to https://assets.trustwallet.com, log on with Github, enter contract ID, logo and some additional info, and it will create a PR for you.
> See https://community.trustwallet.com/t/how-to-submit-a-token-logo-using-assets-app/82957.
> you don't need to pay one more time.
> Closing this PR for now
Check new one created:
https://github.com/trustwallet/assets/pull/8898

 Let me know any thing you need from our side.

**Comment by Chibi-Inu** [comment]
> Too many changed files (903)
> Please create new PR, follow doc https://community.trustwallet.com/t/how-to-submit-a-token-logo/3863
> You may want to try our new Assets app in beta; go to https://assets.trustwallet.com, log on with Github, enter contract ID, logo and some additional info, and it will create a PR for you.
> See https://community.trustwallet.com/t/how-to-submit-a-token-logo-using-assets-app/82957.
> you don't need to pay one more time.
> Closing this PR for now

You told us to create new PR. We already did but you haven't check that one too and that pull request got closed automatically. Are you really want to help us?

**Comment by Chibi-Inu** [comment]
Created new pull request 9113. Check it

**Comment by Chibi-Inu** [comment]
Ok created new PR 9115

**Pull request closed without merging**
