### PR TITLE
Add Logo and Info for MiniBTC

### PR DESCRIPTION
**Pull request by MiniBTCorg**
Please add Logo and Info for MiniBTC

### CODE REVIEW

**Comment by MiniBTCorg** [comment]
Can't we get the logo until there are 10,000 holders? I just saw other projects that do not have so many holders and they had logos

**Comment by MiniBTCorg** [comment]
Hello. I noticed in other pull requests that you ask about the same questions to everyone. I decided to answer them in advance
our website - https://minibtc.org 
**What is the purpose of this token? How will it benefit Trust Wallet users?**
Our goal is to give a second chance to those people who did not have time to buy bitcoin in 2009-2013. We also want and will help orphans, children with disabilities and health problems.  I think many Trust Wallet users will want to be involved in the charity we provide for children. 
The first partner of the MINIBTC is “Red Crescent of Kyrgyzstan".  Before the New Year holidays, this charity received its first donation of $ 500 from the MiniBTC team.  For this small sum, those from disadvantaged families who are forced to live at the landfill received a small bright holiday and delicious gifts. 
phoro report from our first charity event:  https://disk.yandex.ru/d/uVbVCVVaSTtYDw
**• How is the token being distributed? Are you conducting an airdrop?**
The token was distributed using a pre-sale
**• Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?**
Presale details: https://www.pinksale.finance/#/launchpad/0xA80fD763946BDbE9BC2907ECcFabfba39C2200FD?chain=BSC
**• Is the token listed on a centralized/decentralized exchange?**
https://pancakeswap.finance/info/token/0x3bC72EFf96752C2f66c7dE855f97C23eC4A1aC01
**• Is a Smart Contract audit completed? Where can we find this information?**
https://minibtc.org/miniBTCaudit.pdf

**Comment by cryptomanz** [comment]
As per our policy, brand new tokens are not included, there is a minimum requirement of 10,000 holder addresses and 20,000 transactions, in order to filter out scam tokens.
See the criteria at : https://developer.trustwallet.com/assets/requirements .

**Comment by cryptomanz** [comment]
Please come back to us when all criteria are met.
When creating a new PR make sure to mention this PR, so that we can see that fee has been paid already here.

**Pull request closed without merging**
