### PR TITLE
Add Real Smurf Cat (шайлушай) (ERC20)

### PR DESCRIPTION
**Pull request by nicolaschapeau**
Adding info for ERC20 token 'Real Smurf Cat (шайлушай)'.

PR created by <a href="https://assets.trustwallet.com">TW Assets Management</a>

### CODE REVIEW

**Comment by Cryptocool1** [comment]
• What is the purpose of this token? How will it benefit Trust Wallet users?
 • How is the token being distributed? Are you conducting an airdrop?
 • Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?
 • Is the token listed on a centralized/decentralized exchange?
 • Is a Smart Contract audit completed? Where can we find this information?

**Comment by nicolaschapeau** [comment]
• What is the purpose of this token? How will it benefit Trust Wallet users?

-> Smurfcat is a token in existence since September 2023. It's a meme that was popularized by tiktok and now has billions of views. Nate Hallinan, the meme's creator in 2011, joined the token's community in October 2023. He participated to the creation of the NFTs around the meme in December. Today he owns the smurfcat IP and intends to use it to expand the token's various products. There's a lot more, I've condensed it all into this tweet: https://twitter.com/zkay_eth/status/1746831446847733825

-> Our aim is to create a meme that's as accessible as possible to the general public, and to put artists at the heart of the process. Having the token on trustwallet would be a big step forward in helping the general public to buy the token outside the CEXs we have today.

• How is the token being distributed? Are you conducting an airdrop?

-> The token was launched on uniswap without pre-allocation. 100% of the tokens were directly accessible to the general public. No airdrop planned in the future. 100% of tokens are in circulation.

• Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?

-> No

• Is the token listed on a centralized/decentralized exchange?

-> Yes! 
DEXs:
- Uniswap: https://app.uniswap.org/#/swap?outputCurrency=0xfF836A5821E69066c87E268bC51b849FaB94240C&chain=ethereum
CEXs:
- Gate.io: https://www.gate.io/trade/SMURFCAT_USDT
- MEXC: https://www.mexc.com/exchange/SMURFCAT_USDT
- Poloniex: https://poloniex.com/trade/SMURFCAT_USDT/?type=spot
- Bitmart: https://www.bitmart.com/trade/en-US?symbol=SMURFCAT_USDT

• Is a Smart Contract audit completed? Where can we find this information?

-> It's the same contract as PEPE
Smurfcat contract: https://etherscan.io/token/0xfF836A5821E69066c87E268bC51b849FaB94240C#code
PEPE contract: https://etherscan.io/token/0x6982508145454Ce325dDbE47a25d4ec3d2311933#code

We are currently updating CMC, CG, Dextools and Dexscreener and CEXs so that our main ticker is SMURF. This is why we'd like to list on trust wallet with that ticker.

Regards!

**Comment by nicolaschapeau** [comment]
My bad final decision for the ticker is "SMURFCAT"

Sorry for the multiple updates.

It's done now.

**Comment by Cryptocool1** [comment]
We require an audit of the token you submitted. 
(An example of audit: https://skynet.certik.com/projects/trust-wallet)

**Comment by nicolaschapeau** [comment]
> We require an audit of the token you submitted. (An example of audit: https://skynet.certik.com/projects/trust-wallet)

Will update once it's done!

**Comment by Cryptocool1** [comment]
Thank you. I’ll close this PR for now. Please ping me once it’s done

**Comment by nicolaschapeau** [comment]
> Thank you. I’ll close this PR for now. Please ping me once it’s done

Hi, would this audit suit you?
https://gopluslabs.io/token-security/1/0xff836a5821e69066c87e268bc51b849fab94240c

If not, I'll set up a call with Certik, but it will take longer.

Regards!

**Comment by Cryptocool1** [comment]
No, you can choose from different reputable companies (Certik, Techrate, Hacken, Dessert Finance)

**Pull request closed without merging**
