### PR TITLE
CAT Token Logo

### PR DESCRIPTION
**Pull request by YieldFarmDigital**
256x256 pixel logo for Cat Token Logo - Trust Wallet - Uniswap

### CODE REVIEW

**Comment by Iamdeadlyz** [comment]
The token activity does not meet the minimum requirements. This pull request will be put on hold.
https://etherscan.io/token/0x56015bbe3c01fe05bc30a8a9a9fd9a88917e7db3

Learn more here:
https://community.trustwallet.com/t/how-to-submit-a-token-logo/3863#how-to-get-approved

**Review by Stoeff25 — APPROVED** [review]
Logo 512px x 512px

logo

**Comment by YieldFarmDigital** [comment]
Can you please review again? Should meet all requirements now.

**Comment by YieldFarmDigital** [comment]
> The token activity does not meet the minimum requirements. This pull request will be put on hold.
> https://etherscan.io/token/0x56015bbe3c01fe05bc30a8a9a9fd9a88917e7db3
> 
> Learn more here:
> https://community.trustwallet.com/t/how-to-submit-a-token-logo/3863#how-to-get-approved

Can we review again, please? I believe the requirements are met now.

**Comment by Iamdeadlyz** [comment]
> > The token activity does not meet the minimum requirements. This pull request will be put on hold.
> > https://etherscan.io/token/0x56015bbe3c01fe05bc30a8a9a9fd9a88917e7db3
> > Learn more here:
> > https://community.trustwallet.com/t/how-to-submit-a-token-logo/3863#how-to-get-approved
> 
> Can we review again, please? I believe the requirements are met now.

Hi @YieldFarmDigital, this PR request is already merged. The info and logo are now added to the asset database.

**Pull request merged**
