### PR TITLE
#pr add logo tools.crypton.xyz

### PR DESCRIPTION
**Pull request by gran1um**

### CODE REVIEW

**Comment by Tegimufranka9639** [comment]
Link my account tegimufranka9639

**Review by alice22foster — COMMENTED** [review]
chcange

**Comment by CustomerTeam001** [comment]
> chcange

We'd be happy to look into this for you 
kindly file a support ticket below 
https://forms.gle/FhSmn4AznQtZcruX8

**Comment by Tegimufranka9639** [comment]
> Hi! In order to compensate for the efforts of processing PRs, we kindly ask for a contribution. 💀 As **there is no refund**, before **paying the fee**, make sure **new tokens fulfill the minimum circulation and other [acceptance criteria](https://developer.trustwallet.com/listing-new-assets/requirements)**. See also the [PR Fee FAQ](https://developer.trustwallet.com/listing-new-assets/faq).
> 
> Please pay **500 TWT** with the memo **24164** to the TWT-BEP2 (Binance Chain) address `bnb158fgd782we4tz9vwwcj9pmmxvxhl6z46lfm7c8`. Alternatively, 5 BNB is also accepted (same memo & address).
> 
> **QR** code: [Trust](https://api.qrserver.com/v1/create-qr-code/?size=200x200&data=https%3A%2F%2Flink.trustwallet.com%2Fsend%3Fcoin%3D714%26address%3Dbnb158fgd782we4tz9vwwcj9pmmxvxhl6z46lfm7c8%26amount%3D500%26memo%3D24164) | [other wallet](https://api.qrserver.com/v1/create-qr-code/?size=200x200&data=bnb158fgd782we4tz9vwwcj9pmmxvxhl6z46lfm7c8%3Famount%3D500%26memo%3D24164)
> 
> _TWT Acquiring_:
> 
> * [Trust Wallet Tokens (TWT)](https://community.trustwallet.com/t/trust-wallet-token-twt/4187) can be obtained from [DEXs/exchanges](https://community.trustwallet.com/t/where-to-get-trust-wallet-tokens/76641).
> * TWT-BEP2 is supported (Binance Chain), TWT-BEP20 version on Smart Chain is not.
> * TWT-BEP20 can be traded with TWT-BEP2 using the Trust Wallet [Swap Option](https://community.trustwallet.com/t/how-to-trade-with-the-built-in-dex-swap-option/169).
> 
> _Notes_:
> 
> * New tokens without significant usage are rejected, see criteria mentioned above.
> * One PR should be for a single project; PR's with more than 10 logos will be rejected.
> * Payment evaluation happens automatically, but with a few minutes delay.  When payment is detected, an Accept Review is automatically placed on the PR, which is a condition for merge.
> * Evaluating the PR is done manually, and it is merged only if all conditions are satisfied.
>   There will be a fee to process this request. None of it goes to the developers.
>   Before paying the fee, make sure new tokens fulfill the minimum circulation and other acceptance criteria.
>   If you are paying TWT for the submission, this will be burned automatically. There will be no refunds.

**Comment by Tegimufranka9639** [comment]
https://developer.trustwallet.com/listing-new-assets/requirementsd9beb40447786904
dae1ed2ff35e365416b5dehttps://github.com/Tegimufranka9639/fuzzy-funicular/issues/1

**Comment by Tegimufranka9639** [comment]
https://link.trustwallet.com/swap?from=c60_t0x6B175474E89094C44Da98b954EedeAC495271d0F&to=c60

**Comment by gran1um** [comment]
> This PR is being closed due to inactivity. If you wish to continue, please have us reopen the PR before sending your payment, or just create a new one.
>  Do NOT send payments for closed PR, as the fee may by lost!

I wish to continue

**Review by Tegimufranka9639 — COMMENTED** [review]
https://github.com/Tegimufranka9639/fuzzy-funicular/issues/14e6edf2b-88ba-4417-b087-57306ef82482

**Pull request merged**
