### PR TITLE
Add NEXT Smart Chain (ERC20)

### PR DESCRIPTION
**Pull request by dcnl1980**

### CODE REVIEW

**Comment by Cryptocool1** [comment]
As per our policy, brand new tokens are not included, there is a minimum requirement of 10,000 holder addresses and 15,000 transactions, in order to filter out scam tokens.
See the criteria at : https://developer.trustwallet.com/assets/requirements .

**Comment by dcnl1980** [comment]
As per our policy, brand new tokens are not included, there is a minimum requirement of 10,000 holder addresses and 15,000 transactions, in order to filter out scam tokens.

I totally understand the above, but NEXT is not a brand new token it already exist over 1 year and the project is listed on coinmarketcap for over 3 years now. Please reconsider.

**Comment by dcnl1980** [comment]
> As per our policy, brand new tokens are not included, there is a minimum requirement of 10,000 holder addresses and 15,000 transactions, in order to filter out scam tokens.
> See the criteria at : https://developer.trustwallet.com/assets/requirements .

Friendly reminder.

**Comment by Cryptocool1** [comment]
please come back to us when all criteria are met

**Comment by dcnl1980** [comment]
Okey boss 😎 We will do an airdrop to 10k members first 😂 and spend our 1000 TWT on the market. Good luck 👍

**Comment by dcnl1980** [comment]
Anyway I will send also a letter to the board of TrustWallet about your decision here.

**Pull request closed without merging**
