### PR TITLE
Add POLVEN token and info.json

### PR DESCRIPTION
**Pull request by zaitsevartem**
Add POLVEN token and info.json

### CODE REVIEW

**Comment by catenocrypt** [comment]
As per our policy, brand new tokens are not included, there is a minimum requirement of 2500 holder addresses and 5000 transactions, in order to filter out scam tokens.
See the criteria at (mentioned in the first message by the bot): https://community.trustwallet.com/t/how-to-submit-a-token-logo/3863).
This token has below-limit usage currently (981 holders). Putting PR on hold for now. Please come back to us when all criteria are met.  Multi-chain and staking tokens may get special treatment, let us know if this is the case. 

https://etherscan.io/token/0x4a6AB9792e9f046C3AB22D8602450DE5186Be9A7

**Comment by zaitsevartem** [comment]
Hello, it's not our first token, I know this standard but Paypolitan got its logo with 1900 holders and Smartcredit with 1.200, our holders limited by our community, could u make exception and approve the pull request

**Comment by zaitsevartem** [comment]
Hello, it's not our first token, I know this standard but Paypolitan got its logo with 1900 holders and Smartcredit with 1.200, our holders limited by our community, make ecould you pls approve

**Comment by zaitsevartem** [comment]
Our token will lock for 6 month, https://www.unicrypt.network/amm/uni/pair/0x67BeAF934C2501d1a041d9b15f2b277DC99a9ab0
How we can solve this issue with adding logo?

**Comment by Iamdeadlyz** [comment]
Hi,

> Hello, it's not our first token, I know this standard but Paypolitan got its logo with 1900 holders and Smartcredit with 1.200, our holders limited by our community, could u make exception and approve the pull request

Invalid argument. Their PRs were approved MONTHS ago. They have met the requirements at that time.

> Our token will lock for 6 month, https://www.unicrypt.network/amm/uni/pair/0x67BeAF934C2501d1a041d9b15f2b277DC99a9ab0
> How we can solve this issue with adding logo?

You need to meet the mentioned requirements.

**Pull request merged**
