### PR TITLE
Add HODL 2.0 BEP20 Token

### PR DESCRIPTION
**Pull request by hodl-token**
Add HODL 2.0 BEP20 Token

### CODE REVIEW

**Comment by Cryptocool1** [comment]
Can your answer some questions?
 • What is the purpose of this token? How will it benefit Trust Wallet users?
 • How is the token being distributed? Are you conducting an airdrop?
 • Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?
 • Is the token listed on a centralized/decentralized exchange?
 • Is a Smart Contract audit completed? Where can we find this information?

**Comment by HODLV2** [comment]
Hi CryptoA,

Thank you for your E-Mail,

Surely, answering your questions as below:

-> The Hodl 2.0 token has been build as an upgrade to Hodl 1.0 tokens 
with added features including - AutoBuyback & Burn, Reinvest & Buybacks, 
Sellers Tax, New Tokenomics, and Users Choice of Re-Invest/Reward 
Claims. We also added many features including portion buy/sell time 
increase & Data capturing. These were earlier a limitation in the Hold 
1.0 contract and now have been solved and hence the token was created.

We have a good amount of audience ( > 60% if we guage correctly) of HODL 
users on trust wallet. With the updation and Trust wallet support, we 
mutually will be able to give them confidence and trust on token 
upgrade.

-> The tokens is distributed in two ways:
1) Migration of Existin Hodl 1.0 Users through ouur website & Dapp 
(https://hodltoken.net/ & https://hodltoken.net/dashboard)
2) Pancakse swap Trade: 
https://exchange.pancakeswap.finance/#/swap?outputCurrency=0x5788105375ecF7F675C29e822FD85fCd84d4cd86

There is NO airdrop which is conducted

-> No Tokens for Hodl 2.0 were sold in ICO or Pre-sale

-> The HODL 2.0 token is sold on
1) Decentralized exchange : Pancakeswap
2) Centralized exchange XT.com is due to list this today. : 
Announcement: https://twitter.com/TokenHodl/status/1418986504236437506

-> Hold 1.0 audit was completed, however 2.0 is due completion and will 
share the audit as we recieve the report.

Regards,
Allen
Hold Inc

**Comment by Cryptocool1** [comment]
awaiting for smart contract audit

**Comment by Cryptocool1** [comment]
please create new PR when smart contract audit will be ready.
When creating a new PR make sure to mention this PR, so that we can see that fee has been paid already here.

**Comment by HODLV2** [comment]
Sure

**Comment by HODLV2** [comment]
Hi CryptoA,

As required, the audit is ready:

https://github.com/TechRate/Smart-Contract-Audits/blob/main/August/HODL%202.0%20Full%20Smart%20Contract%20Security%20Audit.pdf

We also, got listed on CMC: 
https://coinmarketcap.com/currencies/hodl-2-0/


Regards,

Team
HODL Inc

**Comment by HODLV2** [comment]
Sorry for emailing again: Added details -

#12748 is the New Pull Request
Payment was completed on #12163

Audit as requested: 
https://github.com/TechRate/Smart-Contract-Audits/blob/main/August/HODL%202.0%20Full%20Smart%20Contract%20Security%20Audit.pdf

CMC: https://coinmarketcap.com/currencies/hodl-2-0/

Regards,
Hodl Inc

**Pull request closed without merging**
