### PR TITLE
Add uETH info and logo

### PR DESCRIPTION
**Pull request by udev-ulock**
uETH is 1:1 backed by eth, for creating Uniswap liquidity. As such the only expected holder is the uniswap pairs.

### CODE REVIEW

**Comment by udev-ulock** [comment]
Hello - just checking that since the payment is received, that it's under review now. @catenocrypt Thanks for helping!

**Comment by udev-ulock** [comment]
Checking that this PR is under review - The uETH logo needs to be added so that it is displayed in Uniswap to prevent copycat scams. As mentioned in the PR, uETH is not meant to be held by users, only Uniswap pairs, as it is liquidity infrastructure.

**Comment by Iamdeadlyz** [comment]
As per our policy, brand new tokens are not included. There is a minimum requirement of 2500 holder addresses and 5000 transactions (airdropped tokens excluded) in order to filter out scam tokens. See the criteria at (mentioned in the first message by the bot): https://community.trustwallet.com/t/how-to-submit-a-token-logo/3863#how-to-get-approved

This token has below-limit usage yet. This pull request will be put on hold. Please come back to us when all criteria are met.
https://etherscan.io/token/0x395C8dB957d743a62Ac3aAAa4574553bcf2380b3

**Comment by udev-ulock** [comment]
As mentioned before, uETH is defi infrastructure and will not normally be held by addresses.

Please refund the BNB to 0xd1ccC07177c0c27aB78cF991bA6C4eb4EdC68F31

**Comment by udev-ulock** [comment]
@Iamdeadlyz

**Comment by Iamdeadlyz** [comment]
> Please refund the BNB to 0xd1ccC07177c0c27aB78cF991bA6C4eb4EdC68F31

Refunds cannot be done. Read https://github.com/trustwallet/assets/pull/5001#issuecomment-739046055

The requirements will still be applied regardless of it being a "defi infrastructure." You can still come back and let us know if it meets the criteria so we can re-open this PR.

**Pull request closed without merging**
