### PR TITLE
Add PieDAO DEFI+s and DOUGH governance token.

### PR DESCRIPTION
**Pull request by MickdeGraaf**
I know the tokens don't have the required tx and address count but to launch them as smoothly as possible it would really help a lot if the icons were added to the repo.

I've submitted multiple tokens in the past and none of them were scam tokens. We are also willing to verify the tokens through our official twitter account or website.

It would possibly also prevent people from buying fake scam tokens which don't have the logo verified.

### CODE REVIEW

**Comment by zachzwei** [comment]
Please provide more details about this project.
https://community.trustwallet.com/t/how-to-submit-a-token-logo/3863#how-to-get-approved

You can follow this format when adding an info.json file:
```
 {
   "name":"Bitcoin",
   "website":"https://bitcoin.org",
   "source_code":"https://github.com/bitcoin",
   "white_paper":"https://bitcoin.org/bitcoin.pdf",
   "short_description":"Bitcoin is a cryptocurrency and worldwide payment system.",
   "explorer":"https://blockchain.info",
   "research":"https://research.binance.com/en/projects/bitcoin"
}

**Comment by MickdeGraaf** [comment]
Thank you @zachzwei for your feedback. Information should be complete now.

**Comment by catenocrypt** [comment]
As per our policy, brand new tokens are not included, there is a minimum requirement of 500 holder addresses and 1000 transactions, in order to filter out scam tokens.
See the criteria at (mentioned in the first message by the bot): https://community.trustwallet.com/t/how-to-submit-a-token-logo/3863#how-to-get-approved
This PR has 2 tokens:
- One has low usage (29)  https://etherscan.io/token/0xad32A8e6220741182940c5aBF610bDE99E737b2D
- The other hs no usage (0)  https://etherscan.io/token/0xad32A8e6220741182940c5aBF610bDE99E737b2D
Putting PR on hold. Please come back to us when all criteria are met.

**Comment by MickdeGraaf** [comment]
Can we reopen the PR and merge when we do meet requirements? @catenocrypt @zachzwei?

**Comment by catenocrypt** [comment]
Automation closes PRs after a given number of days of inactivity, but do not worry about it: we can reopen it any time when requested.

**Pull request closed without merging**
