### PR TITLE
new logo upload

### PR DESCRIPTION
**Pull request by dyxnet**
hi thank you. our token now meets the requirements in holders as well as tx's. also i made sure this is a sfw logo and will be using this in mkt materials

@catenocrypt  was wondering if the fee could be waived, as i have alread sent the required TWT the bot asked for before the locked post. I didn't realize there were certain requirements not met.

please see the tx details here: https://github.com/trustwallet/assets/pull/3586

otherwise please do let me know.

thanks!

### CODE REVIEW

**Comment by catenocrypt** [comment]
Could you add an `info.json` file next to the logo.png, with info about the project, of the form:
https://github.com/trustwallet/assets/blob/master/blockchains/ethereum/assets/0x0000000000085d4780B73119b644AE5ecd22b376/info.json

**Comment by dyxnet** [comment]
hi there should be all set @catenocrypt let me know if it's all good. thanks!

**Comment by catenocrypt** [comment]
OK, should be good to go.  Waiting for payment.

**Comment by dyxnet** [comment]
@catenocrypt As mentioned in the OP, I actually had accidentally sent this fee in the original logo upload 2 days ago. The post was locked and I was busy sending to the bot at the same time. Didn't notice it before I could revert the transaction.

Here is the corresponding TX: https://explorer.binance.org/tx/FFB6288E875C412BAC8507BDC0F873A558E0360FB49C78B9ED8BF5FE16C6EFCC

And original thread: https://github.com/trustwallet/assets/pull/3586

If this is not ok I will have to send more TWT, do let me know.

Thank you! Sorry for any confusion

**Comment by catenocrypt** [comment]
#3586 was probably already closed when payment happened, that's why it did not get marked paid.

Considering fee paid to #3586, setting Paid manually.  https://explorer.binance.org/tx/FFB6288E875C412BAC8507BDC0F873A558E0360FB49C78B9ED8BF5FE16C6EFCC

**Pull request merged**
