### PR TITLE
Add Leve Invest (BEP20)

### PR DESCRIPTION
**Pull request by CKSDevs**
Adding info for BEP20 token 'Leve Invest'.

PR created by <a href="https://assets.trustwallet.com">TW Assets Management</a>

### CODE REVIEW

**Comment by Cryptocool1** [comment]
• What is the purpose of this token? How will it benefit Trust Wallet users?
 • How is the token being distributed? Are you conducting an airdrop?
 • Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?
 • Is the token listed on a centralized/decentralized exchange?
 • Is a Smart Contract audit completed? Where can we find this information?

**Comment by CKSDevs** [comment]
> • What is the purpose of this token? How will it benefit Trust Wallet users? • How is the token being distributed? Are you conducting an airdrop? • Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale? • Is the token listed on a centralized/decentralized exchange? • Is a Smart Contract audit completed? Where can we find this information?

What is the purpose of this token? How will it benefit Trust Wallet users?
 Trust Wallet users can benefit from the ability to easily track the token price without leaving the platform, as well as the potential for future growth and adoption of the project.

How is the token being distributed? Are you conducting an airdrop?
The LEVE token has been fairly distributed without any pre-sales or ICOs. There may be opportunities for airdrops or other promotions in the future, but this has not yet been announced.

Did you sell the tokens at an Initial Coin Offering (ICO) or a token presale?
No, LEVE did not participate in any ICOs or token presales. The project had a fair launch, ensuring a level playing field for all investors.

Is the token listed on a centralized/decentralized exchange?
Yes, LEVE is currently listed on PancakeSwap, a decentralized exchange on the Binance Smart Chain. Additional listings may be added in the future, but this has not yet been announced.

Is a Smart Contract audit completed? Where can we find this information?
LEVE is currently undergoing an audit by Certik, a respected auditing firm in the crypto space. The progress of the audit can be tracked on the Certik Skynet platform, which provides real-time updates on the audit status. Once the audit is completed, the report will be made available for public review.
https://skynet.certik.com/projects/leve-invest

**Comment by Cryptocool1** [comment]
2F663440-D337-4F19-975D-7172228BECF1
Awaiting for smart contract audit, hold for now

**Comment by CKSDevs** [comment]
> 2F663440-D337-4F19-975D-7172228BECF1 Awaiting for smart contract audit, on hold for now

I'll be back soon with a different audit link from certik, there they take a little longer, how long does it stay in this on hold state? , maybe it will take a few days all right? 

thanks.

**Review by Imebeez — COMMENTED** [review]
[](https://github.com/trustwallet/assets/blob/26ede4db3252acb2f29b4c6cc48069ae8251c93d/blockchains/smartchain/tokenlist.json)

**Review by Brittanyhorto — COMMENTED** [review]
blockchains/smartchain/assets/0xB12418ae5284aC6215EE255B5cBC7D795E7016B5/logo.png

**Comment by Cryptocool1** [comment]
Please come back to us once audit is done

**Comment by CKSDevs** [comment]
We are doing the audit and in 3 days I will send the link here so we can continue, we can continue here without any problems, right?

**Comment by BhinbahadurUK** [comment]
Great stuff

**Comment by BhinbahadurUK** [comment]
Also any tester links

**Comment by CKSDevs** [comment]
image

**Pull request closed without merging**
