### PR TITLE
gafa

### PR DESCRIPTION
**Pull request by RahelHamarash**
this is gafa

### CODE REVIEW

**Comment by cryptomanz** [comment]
As per our policy, there is a minimum requirement of 10,000 holder addresses and 15,000 transactions, in order to filter out scam tokens.
See the criteria at : https://developer.trustwallet.com/assets/requirements .

**Comment by Cryptocool1** [comment]
Hello! 
I will close this PR, you can create new one once all criteria are met. You don’t need to pay the fee again. Make sure to mention this PR so the fee can be reused

**Comment by RahelHamarash** [comment]
> 

Would it be possible to get a refund? we paid with BNB

**Comment by Cryptocool1** [comment]
hello, 
Снимок экрана 2022-05-05 в 21 29 55

**Pull request closed without merging**
