### PR TITLE
Update SafeBTC logo and info

### PR DESCRIPTION
**Pull request by SAFEBTCOFFICIAL**

### CODE REVIEW

**Comment by SAFEBTCOFFICIAL** [comment]
Hi, im trying to make the payment, i bought twt bep20, can you please provide a bsc address?

best

**Comment by SAFEBTCOFFICIAL** [comment]
Can you double check i uploaded the correct folder, 

i am launching on Ethereum chain as well.

But i realize that we need 2500 holders first.

But i still need to update the logo for Bsc version

best

**Comment by Cryptocool1** [comment]
As per our policy, brand new tokens are not included, there is a minimum requirement of 2500 holder addresses and 5000 transactions, in order to filter out scam tokens.
See the criteria at (mentioned in the first message by the bot): https://community.trustwallet.com/t/how-to-submit-a-token-logo/3863).

Please create new PR, follow doc https://community.trustwallet.com/t/how-to-submit-a-token-logo/3863
You may want to try our new Assets app in beta; go to https://assets.trustwallet.com, log on with Github, enter contract ID, logo and some additional info, and it will create a PR for you.
See https://community.trustwallet.com/t/how-to-submit-a-token-logo-using-assets-app/82957.

**Comment by SAFEBTCOFFICIAL** [comment]
Yes thank you.
  
  
   
  
  
   but please can you update the logo for the Bsc version please 
  
  
   
    On 06/06/2021 6:18 AM CryptoA ***@***.***> wrote:
   
   
    
   
   
    
   
   
   As per our policy, brand new tokens are not included, there is a minimum requirement of 2500 holder addresses and 5000 transactions, in order to filter out scam tokens.See the criteria at (mentioned in the first message by the bot): https://community.trustwallet.com/t/how-to-submit-a-token-logo/3863).
   Please create new PR, follow doc https://community.trustwallet.com/t/how-to-submit-a-token-logo/3863You may want to try our new Assets app in beta; go to https://assets.trustwallet.com, log on with Github, enter contract ID, logo and some additional info, and it will create a PR for you.See https://community.trustwallet.com/t/how-to-submit-a-token-logo-using-assets-app/82957.

**Comment by SAFEBTCOFFICIAL** [comment]
Hi, I have a paid case open to update logo in Smart chain bsc 
  
  
   
  
  
   9576 
  
  
   
    On 06/06/2021 6:18 AM CryptoA ***@***.***> wrote:
   
   
    
   
   
    
   
   
    Hello hi, yes I realized that after I uploaded. I need tho to update the logo on our bsc version. I already paid and I have a new case open 
   
   
    
     On 06/06/2021 6:18 AM CryptoA ***@***.***> wrote:
    
    
     
    
    
     
    
    
    As per our policy, brand new tokens are not included, there is a minimum requirement of 2500 holder addresses and 5000 transactions, in order to filter out scam tokens.See the criteria at (mentioned in the first message by the bot): https://community.trustwallet.com/t/how-to-submit-a-token-logo/3863).
    Please create new PR, follow doc https://community.trustwallet.com/t/how-to-submit-a-token-logo/3863You may want to try our new Assets app in beta; go to https://assets.trustwallet.com, log on with Github, enter contract ID, logo and some additional info, and it will create a PR for you.See https://community.trustwallet.com/t/how-to-submit-a-token-logo-using-assets-app/82957.

**Comment by SAFEBTCOFFICIAL** [comment]
Logo still not updated even if I paid.
  
  
   
  
  
   best 
  
  
   
    On 06/07/2021 1:48 PM ***@***.*** ***@***.*** ***@***.***> wrote:
   
   
    
   
   
    
   
   
    Hi, I have a paid case open to update logo in Smart chain bsc 
   
   
    
   
   
    9576 
   
   
    
     On 06/06/2021 6:18 AM CryptoA ***@***.***> wrote:
    
    
     
    
    
     
    
    
     Hello hi, yes I realized that after I uploaded. I need tho to update the logo on our bsc version. I already paid and I have a new case open 
    
    
     
      On 06/06/2021 6:18 AM CryptoA ***@***.***> wrote:
     
     
      
     
     
      
     
     
     As per our policy, brand new tokens are not included, there is a minimum requirement of 2500 holder addresses and 5000 transactions, in order to filter out scam tokens.See the criteria at (mentioned in the first message by the bot): https://community.trustwallet.com/t/how-to-submit-a-token-logo/3863).
     Please create new PR, follow doc https://community.trustwallet.com/t/how-to-submit-a-token-logo/3863You may want to try our new Assets app in beta; go to https://assets.trustwallet.com, log on with Github, enter contract ID, logo and some additional info, and it will create a PR for you.See https://community.trustwallet.com/t/how-to-submit-a-token-logo-using-assets-app/82957.

**Pull request closed without merging**
