### PR TITLE
ADD ZBTC BEP20

### PR DESCRIPTION
**Pull request by z-bitcoin**

### CODE REVIEW

**Comment by Cryptocool1** [comment]
Submission looks good. awaiting fee payment.

**Comment by z-bitcoin** [comment]
Paid at: #9705
Tx: https://explorer.binance.org/tx/7506AE4D1532A093644A4065BBF6840E0A6CEE9B114DD4E8B04A57D7CAFE1C70

**Comment by z-bitcoin** [comment]
https://github.com/trustwallet/assets/pull/7905

**Comment by z-bitcoin** [comment]
Check #7905
Paid at: #7905
Tx: https://explorer.binance.org/tx/7506AE4D1532A093644A4065BBF6840E0A6CEE9B114DD4E8B04A57D7CAFE1C70

**Comment by z-bitcoin** [comment]
Paid at: #7905
https://explorer.binance.org/tx/7506AE4D1532A093644A4065BBF6840E0A6CEE9B114DD4E8B04A57D7CAFE1C70

**Pull request merged**
