### PR TITLE
Update Finex Logo

### PR DESCRIPTION
**Pull request by FinexToken**

### CODE REVIEW

**Review by FinexToken — COMMENTED** [review]
Kindly update FNX token logo on trust wallet

**Review by FinexToken — COMMENTED** [review]
I have added id and tags. Please review

**Review by FinexToken — COMMENTED** [review]
I have added id and tags. Please review

**Review by FinexToken — COMMENTED** [review]
I have added id and tags. Please review

**Review by FinexToken — COMMENTED** [review]
I have added id and tags. Please review

**Comment by cryptomanz1** [comment]
As per our policy, brand new tokens are not included, there is a minimum requirement of 10,000 holder addresses and 15,000 transactions, in order to filter out scam tokens.
See the criteria at : https://developer.trustwallet.com/assets/requirements .

**Pull request closed without merging**
