### PR TITLE
Add Nora logo and info

### PR DESCRIPTION
**Pull request by NoraProtagonist**

### CODE REVIEW

**Comment by cryptomanz** [comment]
Hello,
Can your answer some questions?
• What is the purpose of this token? How will it benefit Trust Wallet users?
 • How is the token being distributed? Are you conducting an airdrop?
 • Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?
 • Is the token listed on a centralized/decentralized exchange?
 • Is a Smart Contract audit completed? Where can we find this information?

**Comment by Norahiro** [comment]
> Hello, Can your answer some questions? • What is the purpose of this token? How will it benefit Trust Wallet users? • How is the token being distributed? Are you conducting an airdrop? • Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale? • Is the token listed on a centralized/decentralized exchange? • Is a Smart Contract audit completed? Where can we find this information?

### What is the purpose of this token? How will it benefit Trust Wallet users?

$Nora is the community governance token of SnowCrash DAO. Players can trade $Nora on the exchange, or earn $Nora by completing tasks in the game. Players in MetaVoxel can use $Nora to buy land, islands, goods and various raw materials. See https://docs.snowcrash.finance/gameplay/nora here for details. A large number of our potential users are using Trust Wallet.

### How is the token being distributed? Are you conducting an airdrop?

The team holds 10% $Nora locked for 730 days. Early supporters hold 10% $Nora locked for 365 days. 80% $Nora liquidity on PancakeSwap. Liquidity locked up for 365 days. After the end of the lock-up period, the duration and mode of the second round of locking will be decided by the votes of the community members. For a summary of locking, see here https://team.finance/view-coin/0x1F39Dd2Bf5A27e2D4ED691DCF933077371777CB0 There was a $Nora airdrop a while ago, and it is over now. See here for details https://coinmarketcap.com/currencies/snowcrash-token/airdrop

### Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?

$Nora did not conduct an ICO, nor pre-sell before listing.

### Is the token listed on a centralized/decentralized exchange?

Yes, on PancakeSwap V2.

### Is a Smart Contract audit completed? Where can we find this information?

$Nora has not yet completed the smart contract security audit. $Nora smart contract is developed based on the world-renowned OpenZeppelin Contracts Library. The source code of the intelligent contract can be found here https://github.com/SnowCrashDAO/snowcrash-tokens/tree/main/tokens/Nora or here https://bscscan.com/address/0x1f39dd2bf5a27e2d4ed691dcf933077371777cb0#code

For more information about $Nora, see the link below.

- Website: https://snowcrash.finance/
- Docs&Whitepaper: https://docs.snowcrash.finance/
- GitHub: https://github.com/SnowCrashDAO
- Twitter: https://twitter.com/SnowCrashDAO
- Telegram: https://t.me/SnowCrashDAO
- YouTube: https://www.youtube.com/channel/UC5Li60DsXOZqPypyeL2QTQA
- CoinMarketCap https://coinmarketcap.com/currencies/snowcrash-token/

**Comment by cryptomanz** [comment]
- Awaiting for smart contract audit. On hold for now.

**Review by antliv — APPROVED** [review]

**Comment by antliv** [comment]
T

**Comment by Cryptocool1** [comment]
Please come back to us when all criteria are met.
When creating a new PR make sure to mention this PR, so that we can see that fee has been paid already here.

**Comment by antliv** [comment]
U robbd me

**Review by antliv — COMMENTED** [review]
U tobbd me

**Comment by antliv** [comment]
U tobbd me

**Comment by antliv** [comment]
Ur a skumbag for robbin me im a single dad u asshole

**Pull request closed without merging**
