### PR TITLE
Add RedFEG (BEP20)

### PR DESCRIPTION
**Pull request by RedTeam-Blockchain**
Request to add RedFEG

### CODE REVIEW

**Comment by Cryptocool1** [comment]
Correction needed:
- Logo should be 256x256 pixels, it is too large 765x765
- Contract is not in checksum format, should be 0x25574Cad6F03FFacD9D08b288e8D5d88997fb2f3 (not 0x25574cad6f03ffacd9d08b288e8d5d88997fb2f3).

**Comment by cryptomanz** [comment]
Can your answer some questions?
 • What is the purpose of this token? How will it benefit Trust Wallet users?
 • How is the token being distributed? Are you conducting an airdrop?
 • Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?
 • Is the token listed on a centralized/decentralized exchange?
 • Is a Smart Contract audit completed? Where can we find this information?

**Comment by RedTeam-Blockchain** [comment]
Hello, 

REDFEG Token is redesigning how decentralized meme finance (DeFi) is structured. REDFEG Token is focused on reshaping and evolving the way DeFi works while providing the most degeared ecosystem ever designed for the necessary advances in DeFi.

We launched the token on Monday, July 19, 2021 via a FairLaunch, no presale.

The token is currently listed on PancakeSwap and exchangeable with BNB (BNB/REDFEG pair).

https://exchange.pancakeswap.finance/#/swap?outputCurrency=0x25574Cad6F03FFacD9D08b288e8D5d88997fb2f3

We have self-audited the contract via MythX by Consensys. You can find the details at the following link: 
https://github.com/RedTeam-Blockchain/RedFeg/blob/main/RedFeg_mythx_security_audit.pdf

An audit will be done soon, we will certainly otperate for Techrate.

Thank you for your time. I remain available if you have any further questions. 

Have a nice day,

**Comment by cryptomanz** [comment]
- Awaiting for smart contract audit.

**Comment by RedTeam-Blockchain** [comment]
Ok, 

Lock proof: https://app.unicrypt.network/amm/pancake-v2/pair/0x8cada67a6c937116242a7ae49ae0acbcc4a425cb

While waiting for the audit, I send you the lock of our liquidity on UniCrypt for 8 years.

**Comment by Cryptocool1** [comment]
please create new PR when smart contract audit will be ready
When creating a new PR make sure to mention this PR, so that we can see that fee has been paid already here.

**Comment by RedTeam-Blockchain** [comment]
https://github.com/TechRate/Smart-Contract-Audits/blob/main/RedFeg%20Full%20Smart%20Contract%20Security%20Audit.pdf

**Pull request closed without merging**
