### PR TITLE
Add Binstarter (BEP20)

### PR DESCRIPTION
**Pull request by BinStarter**
Adding info for BEP20 token 'Binstarter'.

PR created by <a href="https://assets.trustwallet.com">TW Assets Management</a>

### CODE REVIEW

**Comment by BinStarter** [comment]
Dear TrustWallet Team,

Our new contract address does not meet certain requirements due to the recent migration. However, upon manual review, you will find that our previous contract address fully met all necessary criteria. We kindly request that you approach this situation with consideration for the sensitivity of the migration process.

Thank you for your understanding and support.

Best regards,
Binstarter Team

Proof:

**New Contract:** https://bscscan.com/token/0x5ce12f6d9f2fcaf0b11494a1c39e09eeb16ca7e8
**Old Contract:** https://bscscan.com/token/0xab287e6d370c61f105630e656b5468acb4d00423

**Migration Announcements:**
Twitter: https://x.com/BinStarterio/status/1806340875120943537
Medium: https://binstarter.medium.com/binstarter-token-migration-update-0e4d27c22ff9
Blog: https://blog.binstarter.io/binstarter-token-migration-update/

**Comment by BinStarter** [comment]
Can you remove the old token contract address? It causes an error in check / check (pull_request) and I can't proceed

Old token contract address: 0xab287e6d370c61f105630e656b5468acb4d00423

**Comment by Cryptocool1** [comment]
As per our policy, there is a minimum requirement of 10,000 holder addresses and 15,000 transactions, in order to filter out scam tokens.
See the criteria at : https://developer.trustwallet.com/listing-new-assets/requirements .

**Comment by BinStarter** [comment]
You can see this confirmed in a past conversation by Shuhaib07

Dear TrustWallet Team,

Our new contract address does not meet certain requirements due to the recent migration. However, upon manual review, you will find that our previous contract address fully met all necessary criteria. We kindly request that you approach this situation with consideration for the sensitivity of the migration process.

Thank you for your understanding and support.

Best regards,
Binstarter Team

Proof:

New Contract: https://bscscan.com/token/0x5ce12f6d9f2fcaf0b11494a1c39e09eeb16ca7e8
Old Contract: https://bscscan.com/token/0xab287e6d370c61f105630e656b5468acb4d00423

Migration Announcements:
Twitter: https://x.com/BinStarterio/status/1806340875120943537
Medium: https://binstarter.medium.com/binstarter-token-migration-update-0e4d27c22ff9
Blog: https://blog.binstarter.io/binstarter-token-migration-update/

**Comment by Cryptocool1** [comment]
• What is the purpose of this token? How will it benefit Trust Wallet users?
 • How is the token being distributed? Are you conducting an airdrop?
 • Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?
 • Is the token listed on a centralized/decentralized exchange?
 • Is a Smart Contract audit completed? Where can we find this information?

**Comment by BinStarter** [comment]
Can you remove the old token contract address? I deleted the file of the old address, so I can't proceed further.

Old token contract address: 0xab287e6d370c61f105630e656b5468acb4d00423

**Comment by Cryptocool1** [comment]
> • What is the purpose of this token? How will it benefit Trust Wallet users? • How is the token being distributed? Are you conducting an airdrop? • Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale? • Is the token listed on a centralized/decentralized exchange? • Is a Smart Contract audit completed? Where can we find this information?

hello, 
Please answer these questions , we are waiting for your response. Thank you!

**Comment by BinStarter** [comment]
> > • What is the purpose of this token? How will it benefit Trust Wallet users? • How is the token being distributed? Are you conducting an airdrop? • Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale? • Is the token listed on a centralized/decentralized exchange? • Is a Smart Contract audit completed? Where can we find this information?
> 
> hello, Please answer these questions , we are waiting for your response. Thank you!

Dear Cryptocool1,

BinStarter was officially launched in 2021 as the first insured launchpad project in the industry. Since its inception, it has been available on platforms such as TrustWallet and many others. In 2024, we successfully conducted a token migration, and as a result, we are in the process of updating our token information across all platforms.

Please find the official announcements related to the migration below:

Migration Announcements:

Twitter: https://x.com/BinStarterio/status/1806340875120943537
Medium: https://binstarter.medium.com/binstarter-token-migration-update-0e4d27c22ff9
Blog: https://blog.binstarter.io/binstarter-token-migration-update/

Audit Reports:

CertiK: https://skynet.certik.com/projects/binstarter
SolidProof: https://docs.binstarter.io/audit/audit

Contract Information:

Old Contract: https://bscscan.com/token/0xab287e6d370c61f105630e656b5468acb4d00423
New Contract: https://bscscan.com/token/0x5ce12f6d9f2fcaf0b11494a1c39e09eeb16ca7e8

Dextools Pair Explorer Links:

Pancakeswap: https://www.dextools.io/app/en/bnb/pair-explorer/0x11f0f4aea8d929d50858d67b64894f80d106576b?t=1719505190889
Uniswap: https://www.dextools.io/app/en/bnb/pair-explorer/0xbc38a22b760124885291d6cfd6429046d882ae91?t=1725293229640

Market Listings:

CoinMarketCap: https://coinmarketcap.com/currencies/binstarter/
CoinGecko: https://www.coingecko.com/en/coins/binstarter

Thank you for your continued support.

**Review by Zack435 — COMMENTED** [review]
[]()

**Pull request merged**
