### PR TITLE
Add BLB Billiance Token (billiance.io)

### PR DESCRIPTION
**Pull request by Billiance-Channel**

### CODE REVIEW

**Comment by catenocrypt** [comment]
Copying errors from the check build below.
Please rename folder to checksum format (`0x20DD0400B3c7b0Ba1a1503B032a17759e8cfFfc0`), and
reduce logo size.  Max size is 100kB and 512x512 px.

```
   !   'Unexpected explorer, https://tronscan.org/#/token20/TN7zQd2oCCguSQykZ437tZzLEaGJ7EGyha instead of https://tronscan.io/#/token20/TN7zQd2oCCguSQykZ437tZzLEaGJ7EGyha (https://explorer.jackpool.finance.io, https://scan.jackpool.finance.io)'
   X   'Expect asset at path /home/runner/work/assets/assets/blockchains/ethereum/assets/0x20dd0400b3c7b0ba1a1503b032a17759e8cfffc0 in checksum: '0x20DD0400B3c7b0Ba1a1503B032a17759e8cfFfc0''
   X   'Logo too large: /home/runner/work/assets/assets/blockchains/ethereum/assets/0x20dd0400b3c7b0ba1a1503b032a17759e8cfffc0/logo.png'
```

**Comment by Billiance-Channel** [comment]
@catenocrypt i has been fixed, please check agian. Thanks !

**Comment by Billiance-Channel** [comment]
@dukim0602 please give me more detail of this problem. thanks !

**Comment by Iamdeadlyz** [comment]
In accordance with our [disclaimer](https://github.com/trustwallet/assets#disclaimer), your PR is denied due to the following reasons:
- Plagiarized information with the intent to mislead users
image
image
image
image

- Airdropped tokens to users just to reach our requirements

**Pull request closed without merging**
