### PR TITLE
Add new logo

### PR DESCRIPTION
**Pull request by finodao**

### CODE REVIEW

**Comment by finodao** [comment]
Hi, I have added the correct logo with the desired dimensions, please review and approve. Thanks!

**Comment by finodao** [comment]
We have already paid for the service, we need a small change.

**Comment by Cryptocool1** [comment]
hello, you should pay the fee for updating

**Comment by finodao** [comment]
@Cryptocool1 We have already paid 5 BNB, and just want to update the logo. We kept the dimensions as per the requested size but when it updated in trust wallet, we realised that size is not accurate. Please take this request and kindly update the logo. Thanks!

**Comment by finodao** [comment]
@Cryptocool1 @cryptomanz pls approve the request

**Pull request closed without merging**
