### PR TITLE
Update PET GAMES info

### PR DESCRIPTION
**Pull request by petgamesbsc**
Please upload info

### CODE REVIEW

**Comment by petgamesbsc** [comment]
Please update PET GAMES info

**Comment by cryptomanz** [comment]
hello,
• What is the purpose of this token? How will it benefit Trust Wallet users?
 • How is the token being distributed? Are you conducting an airdrop?
 • Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?
 • Is the token listed on a centralized/decentralized exchange?
 • Is a Smart Contract audit completed? Where can we find this information?

**Comment by petgamesbsc** [comment]
This is the token to provide Pet Games Play-To-Earn rewards
We are about to list on CoinTiger on September 7, 2021

**Comment by cryptomanz** [comment]
- According to our documentation token image needs to be full screen, here is link to guidelines details and an example of token images https://community.trustwallet.com/t/how-to-submit-a-token-logo/3863

**Comment by petgamesbsc** [comment]
Done

**Comment by petgamesbsc** [comment]
Please check again

**Comment by petgamesbsc** [comment]
Please update token

**Comment by petgamesbsc** [comment]
> * According to our documentation token image needs to be full screen, here is link to guidelines details and an example of token images https://community.trustwallet.com/t/how-to-submit-a-token-logo/3863

Please update my token

**Comment by Cryptocool1** [comment]
Please create new PR when all criteria are met. make sure to mention this PR, so the fee can be reused.

**Pull request closed without merging**
