### PR TITLE
Add CHN asset

### PR DESCRIPTION
**Pull request by ChainEngineer1**

### CODE REVIEW

**Comment by ramsty** [comment]
Hi!
Could you answer some questions?
• What is the purpose of this token? How will it benefit Trust Wallet users?
• How is the token being distributed? Are you conducting an airdrop?
• Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?
• Is the token listed on a centralized/decentralized exchange?
• Is a Smart Contract audit completed? Where can we find this information?

**Comment by ChainEngineer1** [comment]
> 
> 
> Hi! Could you answer some questions? • What is the purpose of this token? How will it benefit Trust Wallet users? • How is the token being distributed? Are you conducting an airdrop? • Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale? • Is the token listed on a centralized/decentralized exchange? • Is a Smart Contract audit completed? Where can we find this information?

1. Chain Token (CHN) is utility-based cryptocurrency which is used for discounts, premium access, and to pay for commercial fees on SEQUENCE, a ledger as a service, designed for enterprises. CHN is also used for on-chain governance for various community driven programs.
  
2. The distribution information can be found below and verified on chain.com/token.pdf 

Distribution allocation 50%- Distributed to Sequence clients retroactively and currently, for free, as part of our distribution program.

Chain Treasury - CHN, belonging to Chain, will sit on the corporate treasury balance sheet, which will be 50% unlocked and the remaining 50% will unlock over 60 months through audited time-lock smart contracts.

Team 10% - The early developers and community members will receive their allocation unlocked.

Reserves 10%- This allocation will be held under decentralized treasury and used for various community voted programs through on-chain governance.

3. No there is no ICO or sale

4. Decentralized Exchange with Centralized coming

5. Not yet and it’s in process we used a common smart contract with no other functionality which can be found here: https://etherscan.io/address/0x41C37A4683d6a05adB31c39D71348A8403B13Ca9#code

**Comment by Cryptocool1** [comment]
awaiting for smart contract audit, on hold for now

**Comment by Cryptocool1** [comment]
Please come back to us when all criteria are met.
When creating a new PR make sure to mention this PR, so that we can see that fee has been paid already here.

**Pull request closed without merging**
