### PR TITLE
Update MOONI logo_v2

### PR DESCRIPTION
**Pull request by mooni-defi**

### CODE REVIEW

**Comment by mooni-defi** [comment]
Hi @catenocrypt, we paid now. If there is no problem, can you merge? Thank you.

**Comment by mooni-defi** [comment]
No changes have been made to the info.json file. only logo.png removed new v2 logo.png added. We ask you to resolve the conflict and merge it. @catenocrypt  @zachzwei

**Comment by mooni-defi** [comment]
The button "Resolve conflicts" appears to be passive. Can you help me for merge?

**Comment by nahre1026** [comment]
@hexorx , @rfunduk

**Comment by mooni-defi** [comment]
@hexorx , @rfunduk

**Comment by mooni-defi** [comment]
Can you be interested? @catenocrypt @zachzwei

**Comment by catenocrypt** [comment]
After merging master, there are no files to be changed; it seems the exact same files were already added, by #6367 .

**Comment by mooni-defi** [comment]
> After merging master, there are no files to be changed; it seems the exact same files were already added, by #6367 .

There is a file with the same name but the content is different. Didn't you see this commit? Can you check again? what should I do? I've repeatedly stated that I added a new logo to you.

https://github.com/trustwallet/assets/pull/6467/commits/1aac9b3360cf85eecdd9dce64b739de25e2a24c0

**Pull request merged**
