### PR TITLE
Add swapcoinz token

### PR DESCRIPTION
**Pull request by Logicman007**
This PR is being closed due to inactivity. If you wish to continue, please have us reopen the PR before sending your payment.
Do NOT send payments for closed PR, as the fee may by lost!
  (60 vs. 60 hrs)

### CODE REVIEW

**Comment by catenocrypt** [comment]
Submission looks OK.  Fee payment pending.

**Comment by catenocrypt** [comment]
Check fails because folder name should be in checksum, `0x37109a51e712471Bd2C72d8D70718627e7fF0032`.  I tried to fix it (rename), but I have no write access to this PR (usually I do).  
Please fix.

**Comment by Logicman007** [comment]
OK. What should i do? Give me procedure to rename and correct please

**Comment by Logicman007** [comment]
> Submission looks OK. Fee payment pending.

Can I make payment now? Is everything OK?

**Comment by catenocrypt** [comment]
```
git mv blockchains/smartchain/assets/0x37109a51e712471bd2c72d8d70718627e7ff0032 blockchains/smartchain/assets/0x37109a51e712471Bd2C72d8D70718627e7fF0032_RENAME
git commit -a
git mv blockchains/smartchain/assets/0x37109a51e712471Bd2C72d8D70718627e7fF0032_RENAME blockchains/smartchain/assets/0x37109a51e712471Bd2C72d8D70718627e7fF0032
git commit -a
git push
```

**Pull request closed without merging**
