### PR TITLE
Add Hoppy logo and info in Trust Wallet

### PR DESCRIPTION
**Pull request by coppermug**

### CODE REVIEW

**Comment by coppermug** [comment]
Hi, I would request you to kindly consider our pull request. As you can see, the token circulation number is pretty close to the requirement stated. Previously the number is lower, however now is being increase to a higher number. Despite our honest efforts, we are experiencing a hard time onboarding trust wallet user without the logo. Appreciate your attention to make this ecosystem a greater place.

**Comment by coppermug** [comment]
• What is the purpose of this token?
HOP token, is the governance token of HOPPY. HOPPY hopes to become the Most Influential Sustainability-driven
Community, aiming to build Awareness and make impactful Actions in contributing towards the 2030 United Nations’ Sustainable Development Goals.

How will it benefit Trust Wallet users?
Trust wallet users will be able to participate in realizing a greener, better future. Most importantly, with the Logo we can help users identify the real HOP token, avoid being scammed by fake contracts.

• Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?
Yes, presale happened in Q2 2021.

• Is the token listed on a centralized/decentralized exchange?
Yes. It's on pancakeswap
https://pancakeswap.finance/swap?outputCurrency=0x984811e6f2695192add6f88615dF637bf52a5Cae

Is a Smart Contract audit completed? Where can we find this information?
Yes we have completed the Smart Contract audit last year. Do allow me find the audit document.

**Comment by Cryptocool1** [comment]
please send your audit here

**Comment by coppermug** [comment]
Here is the audit information: [https://solidgroup-68170.medium.com/71be3b0a403d](url)

**Comment by coppermug** [comment]
https://solidgroup-68170.medium.com/71be3b0a403d

**Comment by coppermug** [comment]
Hi there, I hope these information are sufficient, please let me know if you need others information.
Looking forward to your reply

**Comment by coppermug** [comment]
Hi please assist to reopen this pull request, thank you

**Comment by coppermug** [comment]
Hi please assist to reopen this pull request.
Could you please review our pull request? Thank you

**Pull request closed without merging**
