### PR TITLE
Add BabyDB Bep20

### PR DESCRIPTION
**Pull request by marcichan**
Add BabyDB Bep20

### CODE REVIEW

**Comment by Cryptocool1** [comment]
hello,
• What is the purpose of this token? How will it benefit Trust Wallet users?
 • How is the token being distributed? Are you conducting an airdrop?
 • Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?
 • Is the token listed on a centralized/decentralized exchange?
 • Is a Smart Contract audit completed? Where can we find this information?

**Comment by freshmeat87** [comment]
Users of this token will get 10% reflections for holding it.

Presale:
https://app.unicrypt.network/amm/pancake-v2/ilo/0x5A53b174A79cCdF810854EEE85D75497591AC11b

PancakeSwap:
https://exchange.pancakeswap.finance/#/swap?outputCurrency=0x6d9fb3332f62fc044d5075feeea597a92f1ce0ad

Audit by Solidproof: 
https://github.com/solidproof/smart-contract-audits/blob/main/SmartContract_Audit_Solidproof_BabyDogeBillionaire.pdf

**Comment by Cryptocool1** [comment]
> Users of this token will get 10% reflections for holding it.
> 
> Presale:
> https://app.unicrypt.network/amm/pancake-v2/ilo/0x5A53b174A79cCdF810854EEE85D75497591AC11b
> 
> PancakeSwap:
> https://exchange.pancakeswap.finance/#/swap?outputCurrency=0x6d9fb3332f62fc044d5075feeea597a92f1ce0ad
> 
> Audit by Solidproof:
> https://github.com/solidproof/smart-contract-audits/blob/main/SmartContract_Audit_Solidproof_BabyDogeBillionaire.pdf

how they will get this 10%?

**Comment by freshmeat87** [comment]
Every transaction has a 10% fee which is split amongst all token holders. It's called reflections or earn.

**Comment by Cryptocool1** [comment]
can you please add links to your PR?
example: https://developer.trustwallet.com/add_new_asset#info-json-contents

**Pull request merged**
