### PR TITLE
Add WAM (BEP20)

### PR DESCRIPTION
**Pull request by mustvlad**
Adding info for BEP20 token 'WAM'.

PR created by <a href="https://assets.trustwallet.com">TW Assets Management</a>

### CODE REVIEW

**Comment by Cryptocool1** [comment]
As per our policy, brand new tokens are not included, there is a minimum requirement of 10,000 holder addresses and 15,000 transactions, in order to filter out scam tokens.
See the criteria at : https://developer.trustwallet.com/assets/requirements .

**Comment by Cryptocool1** [comment]
• Is a Smart Contract audit completed? Where can we find this information?

**Comment by mustvlad** [comment]
Hey @Cryptocool1. 

Yep, we had an audit from Certik ( https://www.certik.com/projects/wam – https://coinmarketcap.com/currencies/wam-app/ ).

Also, you can find here our CEO speaking about WAM at the Binance Blockchain Week https://www.youtube.com/watch?v=wLdiEouNa2w&t=2s and the official announcement made by BNB chain where we are featured as one of the "Star dApps" https://mobile.twitter.com/BNBCHAIN/status/1560990035889082368. 

Don't think we can fit in the 'scam' category. :)

**Comment by Cryptocool1** [comment]
submission looks good, awaiting for the fee payment

**Comment by mustvlad** [comment]
@Cryptocool1 done! thanks!

**Pull request merged**
