### PR TITLE
Mars token add

### PR DESCRIPTION
**Pull request by MT2055**
Dear Trust wallet team, kindly allow me to add erc 20 Mars token logo. Thanks.

### CODE REVIEW

**Comment by kolya182** [comment]
> Dear Trust wallet team, kindly allow me to add erc 20 Mars token logo. Thanks.

Please format PR according to the requirements

**Comment by rajeevpulami** [comment]
> > Dear Trust wallet team, kindly allow me to add erc 20 Mars token logo. Thanks.
> 
> Please format PR according to the requirements

im very new for this field still i have no much idea how to do that?

**Comment by kolya182** [comment]
> > > Dear Trust wallet team, kindly allow me to add erc 20 Mars token logo. Thanks.
> > 
> > 
> > Please format PR according to the requirements
> 
> im very new for this field still i have no much idea how to do that?

Read this https://github.com/trustwallet/assets/pull/2382#issuecomment-644239434

**Comment by rajeevpulami** [comment]
Token Name: Mars 
symbol : MARS 
decimals: 18
total supply: 100000000000000000
adress: 0x165cb5cd6c56c5f1e224a9a2da750621929f4419

**Comment by kolya182** [comment]
@rajeevpulami Added here https://github.com/trustwallet/assets/commit/8a2990d99ddcf00eab98519ae53b82176a86ed51

**Pull request closed without merging**
