### PR TITLE
add P2E logo and info

### PR DESCRIPTION
**Pull request by P2Exyz**
PLS2E.io = DAO+DEX+NFTs+GameFi LaunchPad. 
The best GameFi infrastructure platform on BSC and put forward the concept of Earn As A Service (EAAS)

### CODE REVIEW

**Comment by cryptomanz** [comment]
please remove this file
Screenshot 2021-12-06 at 03 02 28

**Comment by P2Exyz** [comment]
> 
How to remove it ? 

> please remove this file Screenshot 2021-12-06 at 03 02 28

Sorry, how do I delete these pictures?

**Comment by P2Exyz** [comment]
> > 
> 
> How to remove it ?
> 
> > please remove this file Screenshot 2021-12-06 at 03 02 28
> 
> Sorry, how do I delete these pictures?

@cryptomanz

**Comment by leedaniil** [comment]
You info.json file has a wrong JSON format. 
Validate your file here https://jsonformatter.curiousconcept.com/ and upload a correct file, please.

**Comment by Cryptocool1** [comment]
Please create new PR, follow doc https://developer.trustwallet.com/assets/requirements
You may want to try our Assets app in beta; go to https://assets.trustwallet.com, log on with Github, enter contract ID, logo and some additional info, and it will create a PR for you.
See https://developer.trustwallet.com/assets/repository_details

**Comment by Cryptocool1** [comment]
When creating a new PR make sure to mention this PR, so that we can see that fee has been paid already here.

**Comment by P2Exyz** [comment]
New Pr please check https://github.com/trustwallet/assets/pull/16450

**Pull request closed without merging**
