### PR TITLE
Upload Hungarian Vizsla Inu Token

### PR DESCRIPTION
**Pull request by VizslaInu**

### CODE REVIEW

**Comment by Cryptocool1** [comment]
This is a BEp20 token, correct folder is blockchains/smartchain/assets.

**Comment by VizslaInu** [comment]
Dear Trust Wallet!

I updated the folder into correct. Can you help me please to update the information in the Trust Wallet?

Thanks a lot!

**Comment by VizslaInu** [comment]
Dear Trust Wallet!

Is it completed? When can i see it in Trust Wallet?

Thanks a lot for the help me! :)

**Comment by VizslaInu** [comment]
Hello! Okay I updated, the checksum format!

But we dont have airdrop manipulated holders, we are charity token, can you help me for the token holders number please.
We paid the fee, but we dont have just 1179 holders yet.

Thanks for help!

**Comment by Cryptocool1** [comment]
As per our policy, brand new tokens are not included, there is a minimum requirement of 2500 holder addresses and 5000 transactions, in order to filter out scam tokens.
See the criteria at https:/community.trustwallet.com/t/how-to-submit-a-token-logo/3863).

**Comment by VizslaInu** [comment]
And then now everything is fine and once you have the 2500 holders, will it be uploaded?

**Comment by Cryptocool1** [comment]
still lack of holders.
Closing PR for now,
Please come back to us when all criteria are met.
When creating a new PR make sure to mention this PR, so that we can see that fee has been paid already here.

**Comment by Cryptocool1** [comment]
hello,
your logo should be with no spacing from the sides.
please change

**Comment by VizslaInu** [comment]
Hello!

Okay, now change or after 2500 holders? Can you help before 2500 holders? 

Thanks for help :)

**Comment by VizslaInu** [comment]
Hello! We already reached 2500 holders that TW. want :)

**Pull request closed without merging**
