### PR TITLE
Add Meria Validators on 10 chains.

### PR DESCRIPTION
**Pull request by louisMeria**

### CODE REVIEW

**Comment by cryptomanz1** [comment]
Please update branch with the recently master

**Comment by louisMeria** [comment]
> Please update branch with the recently master

It's good, ready to merge.
Thanks

**Comment by Cryptocool1** [comment]
Снимок экрана 2024-08-01 в 13 18 35
hi, your branch is out of date. Please update it

**Comment by louisMeria** [comment]
Update done.

**Comment by Cryptocool1** [comment]
Снимок экрана 2024-08-02 в 11 34 40

Please check it again

**Comment by louisMeria** [comment]
Done :) 
image

**Comment by Cryptocool1** [comment]
> Done :) image

thank you

**Pull request merged**
