### PR TITLE
Add Beast DAO token

### PR DESCRIPTION
**Pull request by ghost**

### CODE REVIEW

**Review by GeorgeDeFi — COMMENTED** [review]
Fixed info for Beast DAO

**Comment by catenocrypt** [comment]
As per our policy, brand new tokens are not included, there is a minimum requirement of 2500 holder addresses and 5000 transactions, in order to filter out scam tokens.
See the criteria at (mentioned in the first message by the bot): https://community.trustwallet.com/t/how-to-submit-a-token-logo/3863).
This token has below-limit usage(411). Putting PR on hold for now. Please come back to us when all criteria are met.

https://etherscan.io/token/0xdBB2F12CB89Af05516768C2c69A771D92A25D17c

**Comment by catenocrypt** [comment]
This is a test comment.  Please ignore.

**Comment by catenocrypt** [comment]
This is a test comment.  Please ignore.

**Comment by GeorgeDeFi** [comment]
We're listed on Trustwallet already under IYF.finance, already on CoinGecko / Etherscan too, is there anyway that this can be cirvumcented? Fake Uniswap pairs have been made already for ETH/BEAST so we need to be listed ASAP so that the icon appears.

**Comment by catenocrypt** [comment]
Accepting submission.

**Pull request merged**
