### PR TITLE
Add ETA to trust wallet

### PR DESCRIPTION
**Pull request by Etheratoken**
ethera team logo solicitation

### CODE REVIEW

**Comment by Etheratoken** [comment]
{
    "name": "Ethera",
    "website": "https://ethera.cc",
    "description": "Welcome to Ethera – a new innovative yield farming protocol designed to reward its holders through passive staking. With a suite of BSC tools in development and other crypto variations in the pipeline.",
    "explorer": "https://www.bscscan.com/token/0x90727c1195fb2246fd758172f9253873790d06a4",
    "type": "BEP20",
    "symbol": "ETA",
    "decimals": 9,
    "status": "active",
    "id": "0x90727c1195fb2246fd758172f9253873790d06a4",
    "links": [
        {
            "name": "github",
            "url": "https://github.com/Etheratoken"
        },
        {
            "name": "twitter",
            "url": "https://twitter.com/Etheratoken"
        },
        {
            "name": "reddit",
            "url": "https://www.reddit.com/r/Ethera/"			
		},
        {
            "name": "Telegram",
            "url": "https://t.me/EtheraETA"
		},
        {
            "name": "coingecko",
            "url": "https://www.coingecko.com/en/coins/ethera"
		},
        {
            "name": "coinmarketcap",
            "url": "https://coinmarketcap.com/currencies/ethera/"			
		},
        {
            "name": "reddit",
            "url": "https://reddit.com/r/trustapp"
		},
        {
            "name": "blockfolio",
            "url": "https://blockfolio.com/coin/ETA"			
        }
    ]
}

**Comment by Etheratoken** [comment]
> could you add the links? see the example here: https://developer.trustwallet.com/assets/repository_details

{
    "name": "Ethera",
    "website": "https://ethera.cc",
    "description": "Welcome to Ethera – a new innovative yield farming protocol designed to reward its holders through passive staking. With a suite of BSC tools in development and other crypto variations in the pipeline.",
    "explorer": "https://www.bscscan.com/token/0x90727c1195fb2246fd758172f9253873790d06a4",
    "type": "BEP20",
    "symbol": "ETA",
    "decimals": 9,
    "status": "active",
    "id": "0x90727c1195fb2246fd758172f9253873790d06a4",
    "links": [
        {
            "name": "github",
            "url": "https://github.com/Etheratoken"
        },
        {
            "name": "twitter",
            "url": "https://twitter.com/Etheratoken"
        },
        {
            "name": "reddit",
            "url": "https://www.reddit.com/r/Ethera/"			
		},
        {
            "name": "Telegram",
            "url": "https://t.me/EtheraETA"
		},
        {
            "name": "coingecko",
            "url": "https://www.coingecko.com/en/coins/ethera"
		},
        {
            "name": "coinmarketcap",
            "url": "https://coinmarketcap.com/currencies/ethera/"			
		},
        {
            "name": "reddit",
            "url": "https://reddit.com/r/trustapp"
		},
        {
            "name": "blockfolio",
            "url": "https://blockfolio.com/coin/ETA"			
        }
    ]
}

**Comment by Etheratoken** [comment]
{
    "name": "Ethera",
    "website": "https://ethera.cc",
    "description": "Welcome to Ethera – a new innovative yield farming protocol designed to reward its holders through passive staking. With a suite of BSC tools in development and other crypto variations in the pipeline.",
    "explorer": "https://www.bscscan.com/token/0x90727c1195fb2246fd758172f9253873790d06a4",
    "type": "BEP20",
    "symbol": "ETA",
    "decimals": 9,
    "status": "active",
    "id": "0x90727c1195fb2246fd758172f9253873790d06a4",
    "links": [
        {
            "name": "github",
            "url": "https://github.com/Etheratoken"
        },
        {
            "name": "twitter",
            "url": "https://twitter.com/Etheratoken"
        },
        {
            "name": "reddit",
            "url": "https://www.reddit.com/r/Ethera/"			
		},
        {
            "name": "Telegram",
            "url": "https://t.me/EtheraETA"
		},
        {
            "name": "coingecko",
            "url": "https://www.coingecko.com/en/coins/ethera"
		},
        {
            "name": "coinmarketcap",
            "url": "https://coinmarketcap.com/currencies/ethera/"			
		},
        {
            "name": "blockfolio",
            "url": "https://blockfolio.com/coin/ETA"			
        }
    ]
}

**Comment by Cryptocool1** [comment]
• Is a Smart Contract audit completed? Where can we find this information?

**Comment by Etheratoken** [comment]
> • Uma auditoria de contrato inteligente foi concluída? Onde podemos encontrar essas informações?

https://github.com/Etheratoken/Audits/blob/main/Ethera%20ApeAudits.pdf

**Comment by Etheratoken** [comment]
> **** Arquivos de **resumo de PR** OK, 2 Arquivos em PR: 2 Token em PR: BEP20 0x90727C1195fB2246fd758172f9253873790d06a4 Símbolo: decimais de **ETA** : 9 Links: [Informações do ](https://raw.githubusercontent.com/Etheratoken/assets/master/blockchains/smartchain/assets/0x90727C1195fB2246fd758172f9253873790d06a4/info.json)[logotipo ](https://raw.githubusercontent.com/Etheratoken/assets/master/blockchains/smartchain/assets/0x90727C1195fB2246fd758172f9253873790d06a4/logo.png) [Site ](https://ethera.cc)[Explorer](https://bscscan.com/token/0x90727C1195fB2246fd758172f9253873790d06a4) (marque OK[](https://raw.githubusercontent.com/Etheratoken/assets/master/blockchains/smartchain/assets/0x90727C1195fB2246fd758172f9253873790d06a4/info.json) [](https://ethera.cc) [](https://bscscan.com/token/0x90727C1195fB2246fd758172f9253873790d06a4)🙂)
> 
> 

ok

**Pull request merged**
