### PR TITLE
Add Littlemoose (BEP20)

### PR DESCRIPTION
**Pull request by littlemooose**
Adding info for BEP20 token 'Littlemoose'.

PR created by <a href="https://assets.trustwallet.com">TW Assets Management</a>

### CODE REVIEW

**Comment by cryptomanz** [comment]
https://github.com/trustwallet/assets/pull/10420
10420 merged
what do you want to change?

**Comment by cryptomanz** [comment]
https://github.com/trustwallet/assets/pull/10420
10420 merged
what do you want to change?

**Comment by littlemooose** [comment]
Hi sir, can you upload the logo in token pocket crypto? Coz some of chinese
holders asking me, thank you,

**Comment by littlemooose** [comment]
Goodevening sir, can you upload the logo in Tokenpocket . Because in people
in china want the logo on their platform. Thank you

**Comment by littlemooose** [comment]
Is this for upload the  logo in tokenpocket?

**Comment by cryptomanz** [comment]
#10420 merged

**Comment by littlemooose** [comment]
Can you open it , i wanna pay it

**Comment by Cryptocool1** [comment]
> Can you open it , i wanna pay it
> […](#)

10420 merged. Is this the same PR?

**Comment by littlemooose** [comment]
I wanna apply LittleMoose tokenpocket

**Comment by littlemooose** [comment]
I wanna apply the logo of littlemoose in token pocket

**Pull request closed without merging**
