### PR TITLE
Add logo ZenFinance

### PR DESCRIPTION
**Pull request by yearn2finance**
Hi, Please add logo for us.

I have accidentally created the logo.png file in the wrong checksum folder. Can you help me to delete it since I can't find a way to do that.

Thank you.

### CODE REVIEW

**Comment by yearn2finance** [comment]
https://explorer.binance.org/tx/E7B95782CFDC9A4A2F8BF31D33A476D13ECA0B1CD7D9995C5AC402E42E68C979
Done payment. Please help.
Thank you!

**Comment by yearn2finance** [comment]
https://explorer.binance.org/tx/E7B95782CFDC9A4A2F8BF31D33A476D13ECA0B1CD7D9995C5AC402E42E68C979
Done payment. Please help.
Thank you!

**Comment by catenocrypt** [comment]
Added files have to be sorted out, there are multiple tokens added here:

0xB24f135C954b71B75dD413b288835b5a8d4AFa74:
ZenFinance, usage below limit (158/735)

0xF6c151Ea50A4F1a50983eB98998A18be0a549aD5: 
Yearn2.Finance, usage OK,  726/4841

Both info files point to the same website https://yearn2.finance, that contains the F6... contract token, but not the B2... one.

There is also a 3rd png file, I guess this is a mistake (`blockchains/ethereum/assets/0xb24f135c954b71b75dd413b288835b5a8d4afa74/logo.png`)

Shall I consider 0xF6c151Ea50A4F1a50983eB98998A18be0a549aD5 only?  Please sort this out for once.

https://etherscan.io/token/0xB24f135C954b71B75dD413b288835b5a8d4AFa74
https://etherscan.io/token/0xF6c151Ea50A4F1a50983eB98998A18be0a549aD5

**Comment by yearn2finance** [comment]
Hi. We had already add logo for https://etherscan.io/token/0xF6c151Ea50A4F1a50983eB98998A18be0a549aD5 last week.

This https://etherscan.io/token/0xB24f135C954b71B75dD413b288835b5a8d4AFa74 is the new token in our same ecosystem. so we want to update it this time.

**There is also a 3rd png file, I guess this is a mistake (blockchains/ethereum/assets/0xb24f135c954b71b75dd413b288835b5a8d4afa74/logo.png)
=> Yes it is a mistake, please help us remove it because I can't find out a way to remove it.

Thank you

**Comment by catenocrypt** [comment]
Refreshed source repo to current master; 0xF6c... token is gone now.

**Comment by catenocrypt** [comment]
Removed unneccesasry logo (two files with only lowercase/uppercase differency is trick to handle in Git, but it's done now)

**Comment by yearn2finance** [comment]
thank you so much

**Pull request merged**
