### PR TITLE
Add WINLAMBO (BEP20)

### PR DESCRIPTION
**Pull request by winlambo**
Adding info for BEP20 token 'WINLAMBO'.

PR created by <a href="https://assets.trustwallet.com">TW Assets Management</a>

### CODE REVIEW

**Comment by winlambo** [comment]
@Cryptocool1 Hello, can you help me pay using my BEP-20 TWT tokens? Which address do I send them to? 
I don't think this is a valid BEP-20 address: bnb1tqq9llyr3dyjd559dha6z5r5etk3qfwk07m098

Thank you!

**Comment by Cryptocool1** [comment]
> @Cryptocool1 Hello, can you help me pay using my BEP-20 TWT tokens? Which address do I send them to?
> I don't think this is a valid BEP-20 address: bnb1tqq9llyr3dyjd559dha6z5r5etk3qfwk07m098
> 
> Thank you!

hello,
Please pay 1000 TWT with the memo 81 to the address bnb1tqq9llyr3dyjd559dha6z5r5etk3qfwk07m098

**Comment by Cryptocool1** [comment]
> > @Cryptocool1 Hello, can you help me pay using my BEP-20 TWT tokens? Which address do I send them to?
> > I don't think this is a valid BEP-20 address: bnb1tqq9llyr3dyjd559dha6z5r5etk3qfwk07m098
> > Thank you!
> 
> hello,
> Please pay 1000 TWT with the memo 81 to the address bnb1tqq9llyr3dyjd559dha6z5r5etk3qfwk07m098

you can swap them to finance chain

**Comment by winlambo** [comment]
> 
> 
> > > @Cryptocool1 Hello, can you help me pay using my BEP-20 TWT tokens? Which address do I send them to?
> > > I don't think this is a valid BEP-20 address: bnb1tqq9llyr3dyjd559dha6z5r5etk3qfwk07m098
> > > Thank you!
> > 
> > 
> > hello,
> > Please pay 1000 TWT with the memo 81 to the address bnb1tqq9llyr3dyjd559dha6z5r5etk3qfwk07m098
> 
> you can swap them to finance chain

Thanks for the reply
How do I do that? I tried binance.org/en/bridge but it doesn't support TWT

**Comment by winlambo** [comment]
Thanks!

**Pull request merged**
