### PR TITLE
Add $YUGE ERC20 Token

### PR DESCRIPTION
**Pull request by yugeworks**

### CODE REVIEW

**Comment by Iamdeadlyz** [comment]
As per our policy, brand new tokens are not included. There is a minimum requirement of 500 holder addresses and 1000 transactions in order to filter out scam tokens. See the criteria at (mentioned in the first message by the bot): https://community.trustwallet.com/t/how-to-submit-a-token-logo/3863#how-to-get-approved

This token has below-limit usage yet. Rejecting PR for now. Please come back to us when all criteria are met.
https://etherscan.io/token/0xb177Bd7919c399dDe531744a20d5078baA1eCff2

**Comment by yugeworks** [comment]
Hi I have just paid the fee can we just leave it open as I know we are not a scam token and 1000 transaction and 500 holders will come fairly soon!

Thank you for considering

**Comment by Iamdeadlyz** [comment]
> Hi I have just paid the fee can we just leave it open as I know we are not a scam token and 1000 transaction and 500 holders will come fairly soon!
> 
> Thank you for considering

Please send the tx here

**Comment by yugeworks** [comment]
https://explorer.binance.org/tx/069CA7F440620DC17B5C3559F6D92995382E68558A34C77D82E3E9F571B1F252

**Comment by Iamdeadlyz** [comment]
Re-opened pull request since the fee is already paid: https://explorer.binance.org/tx/069CA7F440620DC17B5C3559F6D92995382E68558A34C77D82E3E9F571B1F252

Feel free to let us know if you have reached the requirements.

**Pull request closed without merging**
