### PR TITLE
Add BETX Share (BETX) to trust wallet logo update

### PR DESCRIPTION
**Pull request by BETxShare**
update logo 

Add BETX Share (BETX) to trust wallet logo update

TOKEN NAME- BETX Share
TOKEN SYMBOL- BETX
TOTAL SUPPLY - 350,000,000 BETX
Decimals:2
CONTRACT ADDRESS-  0x11799ef12A8b4e79865abb167DF88f14629d1E4f

0x11799ef12A8b4e79865abb167DF88f14629d1E4f

### CODE REVIEW

**Comment by BETxShare** [comment]
update logo 

Add BETX Share (BETX) to trust wallet logo update

TOKEN NAME- BETX Share
TOKEN SYMBOL- BETX
TOTAL SUPPLY - 350,000,000 BETX
Decimals:2
CONTRACT ADDRESS-0x11799ef12A8b4e79865abb167DF88f14629d1E4

0x11799ef12A8b4e79865abb167DF88f14629d1E4

**Comment by catenocrypt** [comment]
Logo filenames were incorrect, I have fixed them.
blockchains/ethereum/assets/0x11799ef12A8b4e79865abb167DF88f14629d1E4/logo.png
instead of
blockchains/ethereum/assets/0x11799ef12A8b4e79865abb167DF88f14629d1E4.png

**Comment by catenocrypt** [comment]
The token address `0x11799ef12A8b4e79865abb167DF88f14629d1E4` is not a valid Eth address!
I think it is one character shorter.  @BETxShare , please provide correct address!

**Comment by BETxShare** [comment]
update logo 

Add BETX Share (BETX) to trust wallet logo update

TOKEN NAME- BETX Share
TOKEN SYMBOL- BETX
TOTAL SUPPLY - 350,000,000 BETX
Decimals:2
CONTRACT ADDRESS-  0x11799ef12A8b4e79865abb167DF88f14629d1E4f

0x11799ef12A8b4e79865abb167DF88f14629d1E4f

**Comment by BETxShare** [comment]
correct token address :  0x11799ef12A8b4e79865abb167DF88f14629d1E4f

**Comment by BETxShare** [comment]
waiting for approval

**Comment by catenocrypt** [comment]
This is correct address, last `f` was missing.  I cannot remove in the PR, as source fork is no longer visible for me.  I'll handle a bit later.

**Comment by catenocrypt** [comment]
Taken over in #3439

**Comment by BETxShare** [comment]
https://github.com/trustwallet/assets/pull/3440

make it forke ..check it sir

please update logo

**Comment by BETxShare** [comment]
please use this transparent logo 

0x11799ef12A8b4e79865abb167DF88f14629d1E4f


you can see there is a white gap unlike the other coins, which shouldn’t be there



Attachment_1597755354

**Comment by BETxShare** [comment]
Hello sir 

please update new logo 

0x11799ef12A8b4e79865abb167DF88f14629d1E4f

**Comment by BETxShare** [comment]
Status: On Hold  
WHY HOLD .

**Pull request closed without merging**
