### PR TITLE
Add Dinoland Metaverse (BEP20)

### PR DESCRIPTION
**Pull request by dinolandteam**
Adding info for BEP20 token 'Dinoland Metaverse'.

PR created by <a href="https://assets.trustwallet.com">TW Assets Management</a>

### CODE REVIEW

**Comment by Dinoalice** [comment]
Dear Cryptocool1,

Please find our answers for your questions below:

(1) What is the purpose of this token? How will it benefit Trust Wallet users?
- The token $DNL is a functional multi-utility token which will be used as the medium of exchange between participants on Dinoland in a decentralised manner. 
- The goal of $DNL is to provide a convenient and secure mode of payment and settlement between participants who interact within the ecosystem on Dinoland without any intermediaries such as centralised third-party entity/institution/credit. 
- It will help Trust Wallet users can buy NFTs in Dinoland Metaverse game or swap to make their profit thanks to its price.

(2) How is the token being distributed? Are you conducting an airdrop?
-  The token $DNL is distributed clearly: Total supply 1,000,000,000 $DNL
-  In which: 3% for seed, 10% for private, 3% for IDO, 32% for game incentives/ farming, 27% for reserve/liquidity, 8% for marketing, 12% for team and 5% for advisor.
- We haven’t distributed Airdrop campaign.

(3) Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?
- We sold $DNL at presale and IDO in January 2022. In IDO event, we organized on 5 pads: Trustpad, NFTb, BinStarter, NFTPad.FI and Gemguardian. 

(4) Is the token listed on a centralized/decentralized exchange?
- The token $DNL is also listed on MEXC (decentralized exchange) and PancakeSwap (centralized exchange).

(5) Is a Smart Contract audit completed? Where can we find this information?
- Our Smart Contract audit completed by SOLIDProof, please check this information in here: https://github.com/solidproof/smart-contract-audits/blob/main/SmartContract_Audit_Solidproof_Dinoland.pdf

Please feel free to share with us if you have any questions. 
Thanks & Regards,
Dinoland Team.

**Comment by dinolandteam** [comment]
Dear @Cryptocool1 ,

Please find our answers for your questions below:

(1) What is the purpose of this token? How will it benefit Trust Wallet users?

The token $DNL is a functional multi-utility token which will be used as the medium of exchange between participants on Dinoland in a decentralised manner.
The goal of $DNL is to provide a convenient and secure mode of payment and settlement between participants who interact within the ecosystem on Dinoland without any intermediaries such as centralised third-party entity/institution/credit.
It will help Trust Wallet users can buy NFTs in Dinoland Metaverse game or swap to make their profit thanks to its price.
(2) How is the token being distributed? Are you conducting an airdrop?

The token $DNL is distributed clearly: Total supply 1,000,000,000 $DNL
In which: 3% for seed, 10% for private, 3% for IDO, 32% for game incentives/ farming, 27% for reserve/liquidity, 8% for marketing, 12% for team and 5% for advisor.
We haven’t distributed Airdrop campaign.
(3) Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?

We sold $DNL at presale and IDO in January 2022. In IDO event, we organized on 5 pads: Trustpad, NFTb, BinStarter, NFTPad.FI and Gemguardian.
(4) Is the token listed on a centralized/decentralized exchange?

The token $DNL is also listed on MEXC (decentralized exchange) and PancakeSwap (centralized exchange).
(5) Is a Smart Contract audit completed? Where can we find this information?

Our Smart Contract audit completed by SOLIDProof, please check this information in here: https://github.com/solidproof/smart-contract-audits/blob/main/SmartContract_Audit_Solidproof_Dinoland.pdf
Please feel free to share with us if you have any questions.
Thanks & Regards,
Dinoland Team.

**Comment by Cryptocool1** [comment]
your logo should be 256/256, please change

**Comment by dinolandteam** [comment]
Deer @Cryptocool1, 
We just updated our logo to 256x256, please check.
Thanks & Regards,
Dinoland Team.

**Comment by dinolandteam** [comment]
Deer @Cryptocool1,
Our token displayed successfully on Trust Wallet but the price data is not showing.
Could you please check?
Thanks & Regards,
Dinoland Team.

**Comment by Cryptocool1** [comment]
Hello, is your token listed on CoinMarckerCap?

**Comment by dinolandteam** [comment]
Deer @Cryptocool1,
@Cryptocool1 Yes, already listed https://coinmarketcap.com/currencies/dinoland
Thanks & Regards,
Dinoland Team.

**Comment by dinolandteam** [comment]
Deer @Cryptocool1 ,
Could you please check this issue as soon as possible? A lot of our users are complaining about it.
Thanks,

**Comment by Cryptocool1** [comment]
Снимок экрана 2022-02-14 в 11 38 55
https://developer.trustwallet.com/assets/faq

**Pull request merged**
