### PR TITLE
Add NFTLaunch.network (BEP20)

### PR DESCRIPTION
**Pull request by divinechoice**
Adding info for BEP20 token 'NFTLaunch.network'.

PR created by <a href="https://assets.trustwallet.com">TW Assets Management</a>

### CODE REVIEW

**Comment by Cryptocool1** [comment]
VLXPAD is already existing token
We are not able to fix the submission. If you can fix the conflicts, please do so and update the submission.
If you cannot, please re-submit the PR with an updated fork.
Your payment is still considered

**Comment by Cryptocool1** [comment]
According to our documentation token image needs to be full screen, here is link to guidelines details and an example of token images: https://community.trustwallet.com/t/how-to-submit-a-token-logo/3863
please change

**Comment by cryptomanz** [comment]
Hello,
Please follow the rules for adding tokens, your logo should be a full screen 256x256.
Exemple:
https://community.trustwallet.com/t/how-to-submit-a-token-logo/3863
Screenshot 2021-10-01 at 01 52 16

**Comment by divinechoice** [comment]
> Hello, Please follow the rules for adding tokens, your logo should be a full screen 256x256. Exemple: https://community.trustwallet.com/t/how-to-submit-a-token-logo/386 Screenshot 2021-10-01 at 01 52 16

Updated logo file
logo

**Comment by Cryptocool1** [comment]
hello,
• What is the purpose of this token? How will it benefit Trust Wallet users?
 • How is the token being distributed? Are you conducting an airdrop?
 • Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?
 • Is the token listed on a centralized/decentralized exchange?
 • Is a Smart Contract audit completed? Where can we find this information?

**Comment by divinechoice** [comment]
> hello, • What is the purpose of this token? How will it benefit Trust Wallet users? • How is the token being distributed? Are you conducting an airdrop? • Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale? • Is the token listed on a centralized/decentralized exchange? • Is a Smart Contract audit completed? Where can we find this information?

Hello, 
1. Its a launchpad token and participant who stake the tokens will get to participate in NFT sales. 
2. Lot of out holders/stakers use trustwallet and would love to see the same added to trust wallet. 
3&4. its not a airdrop. We had our IDO presale on our other launch pads. 
5. Yes its listed on pancakeswap and uniswap. 
6. No, we have multiple launchpads already listed and also token logos are updated on trustwallet. The project is incubated by BlueZilla https://bluezilla.vc/

**Pull request merged**
