### PR TITLE
Add New Sin City Token (BEP20)

### PR DESCRIPTION
**Pull request by newsincity**
Adding info for BEP20 token 'New Sin City Token'.

PR created by <a href="https://assets.trustwallet.com">TW Assets Management</a>

### CODE REVIEW

**Comment by newsincity** [comment]
Hello, does this have to be charged to update the icon information?

**Comment by Cryptocool1** [comment]
Hello, yes you need to pay the fee for updating

**Comment by newsincity** [comment]
no problem.  But there is still another question. The listing of CMC and CG submitted by us is still under review, whether it will affect the update of the token's icon and other information.



> 在 2022年2月20日，10:33，CryptoA ***@***.***> 写道：
> 
> Hello, yes you need to pay the fee for updating

**Comment by Cryptocool1** [comment]
You should wait for Coingecko and CoinMarketCap listing

**Comment by newsincity** [comment]
Got it, thanks for your help.

**Pull request closed without merging**
