### PR TITLE
Add BB Coin (BEP20)

### PR DESCRIPTION
**Pull request by techlabsolution**
Adding info for BEP20 token 'BB Coin'.

PR created by <a href="https://assets.trustwallet.com">TW Assets Management</a>

### CODE REVIEW

**Comment by cryptomanz** [comment]
• What is the purpose of this token? How will it benefit Trust Wallet users?
 • How is the token being distributed? Are you conducting an airdrop?
 • Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?
 • Is the token listed on a centralized/decentralized exchange?
 • Is a Smart Contract audit completed? Where can we find this information?

**Comment by techlabsolution** [comment]
• What is the purpose of this token? How will it benefit Trust Wallet users?
- Purpose of token Payment Solution and Decentralized Finance. It will ease trust wallet user to store the token and hedge against inflation

• How is the token being distributed? Are you conducting an airdrop?
- Token is being distributed through partnership on the project development.

• Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?
- No

• Is the token listed on a centralized/decentralized exchange?
- Yes : https://pancakeswap.finance/info/pool/0xaababfcb8ef19c73c7b5052e380bd7cd294a266d

• Is a Smart Contract audit completed? Where can we find this information?
- Audit by https://vanillapudding.finance/ - https://t.me/vanillapuddingfinance/21

**Comment by Cryptocool1** [comment]
can you send your smart contract audit here?

**Comment by techlabsolution** [comment]
> can you send your smart contract audit here?

https://drive.google.com/file/d/14SLqB7B9ltg90-tPvQgOumTxCLWUUrHw/view?usp=sharing

**Pull request merged**
