### PR TITLE
Add Basket (SPL)

### PR DESCRIPTION
**Pull request by crypt0xg**
Adding info for SPL token 'Basket'.

PR created by <a href="https://assets.trustwallet.com">TW Assets Management</a>

### CODE REVIEW

**Comment by cryptomanz1** [comment]
• What is the purpose of this token? How will it benefit Trust Wallet users?
 • How is the token being distributed? Are you conducting an airdrop?
 • Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?
 • Is the token listed on a centralized/decentralized exchange?
 • Is a Smart Contract audit completed? Where can we find this information?

**Comment by Cryptocool1** [comment]
As per our policy, there is a minimum requirement of 10,000 holder addresses and 15,000 transactions.
See the criteria at : https://developer.trustwallet.com/listing-new-assets/requirements .

**Comment by Cryptocool1** [comment]
According to solscan token has 760holders

**Comment by Cryptocool1** [comment]
Feel free to come back to us once all criteria are met. Make sure to mention this PR so the fee can be reused

**Comment by Eiei070922** [comment]
I'm sorry, team. I'm confused by the email you sent. Can I please stop sending it? I don't want or be involved in anything because it's too complicated for me. I apologize to the team.  Everyone too.

**Pull request merged**
