### PR TITLE
Add BudaCoin (BEP20)

### PR DESCRIPTION
**Pull request by PAWGCoin**
Adding info for BEP20 token 'BudaCoin'.

PR created by <a href="https://assets.trustwallet.com">TW Assets Management</a>

### CODE REVIEW

**Comment by Cryptocool1** [comment]
hello,
your image size should be  256px by 256px
please correct

**Comment by PAWGCoin** [comment]
Sorry about that! Here is the resized image. Thank you, Cryptocool!

https://ibb.co/WBvd9nr

**Comment by PAWGCoin** [comment]
Sorry about that! Here is the link to a 256x256 PNG: https://ibb.co/5j9nf3w

**Comment by PAWGCoin** [comment]
Hi there,

So sorry about that. I’ve sent a link to the new 256x256 PNG logo in the
pull request thread.

Thanks!

**Comment by Cryptocool1** [comment]
> Sorry about that! Here is the link to a 256x256 PNG: https://ibb.co/5j9nf3w

ok. I'll create new PR for you. will merge.

**Comment by Cryptocool1** [comment]
> Sorry about that! Here is the link to a 256x256 PNG: https://ibb.co/5j9nf3w

merged

**Comment by PAWGCoin** [comment]
Thanks Cryptocool, really appreciate it! Are we going to have to pay again?

**Pull request closed without merging**
