### PR TITLE
Add HeroVerse (BEP20) token

### PR DESCRIPTION
**Pull request by hnq90**
Adding info/logo for 'HeroVerse' token.

### CODE REVIEW

**Comment by cryptomanz** [comment]
Hello,
Can your answer for questions?
• What is the purpose of this token? How will it benefit Trust Wallet users?
 • How is the token being distributed? Are you conducting an airdrop?
 • Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?
 • Is the token listed on a centralized/decentralized exchange?
 • Is a Smart Contract audit completed? Where can we find this information?

**Comment by hnq90** [comment]
@cryptomanz Hello, I'm glad to answer your questions.

- HER is the main token of HeroVerse, a NFT Game. And our users mostly use TrustWallet app so they asking us to add HER logo to your app.
- We IDO on Redkite and GameFi.
- Our smart contract is being audited by Certik, but not completed yet.

**Comment by cryptomanz** [comment]
Awaiting for smart contract audit.

**Comment by hnq90** [comment]
@cryptomanz Thank you for your very fast response. Our contract is being audited but it takes time because of the many projects that are being audited and on the auditing queue.
But currently, we have a large amount of TrustWallet users from our communities and they are really want to see our logo on TrustWallet early...
So could you please approve the PR and we will update & send you the audit result later?

Btw, we have just released our app from https://app.heroverse.io. Could you please check it and take a look at our whitepaper for more information first? https://whitepaper.heroverse.io/.

**Comment by freemoon-protocol** [comment]
check my info. you answer only to those who paid. I have already paid. I do not understand where your PR is and how I can specify it together. Add FREEMOON (BEP20) # 13897, Add FREEMOON (BEP20) (# 13531)

**Comment by Cryptocool1** [comment]
Hello,
Please create new PR when smart contract audit will be ready. Make sure to mention this PR, so the fee can be reused.

**Comment by hnq90** [comment]
@Cryptocool1 Thanks, I will create new PR when auditing is completed.

**Comment by hnq90** [comment]
@Cryptocool1 I created another PR, please check.

**Pull request closed without merging**
