### PR TITLE
Add EXF logo and info

### PR DESCRIPTION
**Pull request by ExtendFinance**
Extend Finance

### CODE REVIEW

**Comment by catenocrypt** [comment]
Please add following fields to info.json:

```json
"type": "BEP20",
"symbol": "EXF",
"decimals": 9,
"status": "active",
"id": "0x6306e883493824Ccf606D90E25F68a28e47b98a3"
```

**Comment by ExtendFinance** [comment]
> Please add following fields to info.json:
> 
> ```json
> "type": "BEP20",
> "symbol": "EXF",
> "decimals": 9,
> "status": "active",
> "id": "0x6306e883493824Ccf606D90E25F68a28e47b98a3"
> ```

Done

**Comment by ExtendFinance** [comment]
I must be doing something wrong, can you guys edit the json file?

**Comment by Iamdeadlyz** [comment]
Hi @ExtendFinance,

You need to do it like this:
```
{
    "name": "Trust Wallet Token",
    "website": "https://trustwallet.com",
    "description": "Utility token to increase adoption of cryptocurrency.",
    "socials": [
        {
            "name": "Twitter",
            "url": "https://twitter.com/trustwalletapp",
            "handle": "TrustWalletApp"
        },
        {
            "name": "Reddit",
            "url": "https://reddit.com/r/trustapp",
            "handle": "TrustApp"
        }
    ],
    "explorer": "https://bscscan.com/token/0x4B0F1812e5Df2A09796481Ff14017e6005508003",
    "type": "BEP20",
    "symbol": "TWT",
    "decimals": 18,
    "status": "active",
    "id": "0x4B0F1812e5Df2A09796481Ff14017e6005508003"
}
```

**Comment by catenocrypt** [comment]
No action for more than a month, closing.

**Comment by ExtendFinance** [comment]
I cant place a JSON file in here

**Pull request merged**
