### PR TITLE
Add ADAPad.io (BEP20)

### PR DESCRIPTION
**Pull request by divinechoice**
Adding info for BEP20 token 'ADAPad.io'.

PR created by <a href="https://assets.trustwallet.com">TW Assets Management</a>

### CODE REVIEW

**Comment by Cryptocool1** [comment]
- According to our documentation token image needs to be full screen, here is link to guidelines details and an example of token images: https://community.trustwallet.com/t/how-to-submit-a-token-logo/3863
- velaspad is already existing token.
We are not able to fix the submission. If you can fix the conflicts, please do so and update the submission.
If you cannot, please re-submit the PR with an updated fork.
Your payment is still considered

**Comment by Cryptocool1** [comment]
According to our documentation token image needs to be full screen, here is link to guidelines details and an example of token images: https://community.trustwallet.com/t/how-to-submit-a-token-logo/3863

**Comment by divinechoice** [comment]
> According to our documentation token image needs to be full screen, here is link to guidelines details and an example of token images: https://community.trustwallet.com/t/how-to-submit-a-token-logo/3863

updated logo file 
logo

**Comment by Cryptocool1** [comment]
hello,
• Is a Smart Contract audit completed? Where can we find this information?

**Comment by divinechoice** [comment]
> hello, • Is a Smart Contract audit completed? Where can we find this information?

No, we have multiple launchpads already listed and also token logos are updated on trustwallet. The project is incubated by BlueZilla https://bluezilla.vc/

**Pull request merged**
