### PR TITLE
Add CryptoPlanes (BEP20)

### PR DESCRIPTION
**Pull request by nhuanvolter**
Adding info for BEP20 token 'CryptoPlanes'.

PR created by <a href="https://assets.trustwallet.com">TW Assets Management</a>

### CODE REVIEW

**Comment by cryptomanz** [comment]
Can your answer some questions?
• What is the purpose of this token? How will it benefit Trust Wallet users?
 • How is the token being distributed? Are you conducting an airdrop?
 • Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?
 • Is the token listed on a centralized/decentralized exchange?
 • Is a Smart Contract audit completed? Where can we find this information?

**Comment by nhuanvolter** [comment]
Hello,

• What is the purpose of this token? How will it benefit Trust Wallet users?

CPAN is used for payments and rewards in game CryptoPlanes. Trust Wallet users will be able to store CPAN tokens and trade on DEXs.
• How are tokens distributed? Are you conducting an airdrop?

We distribute tokens through in-game rewards.
• Did you sell tokens at Initial Coin Offering (ICO) or pre-sell tokens?
We sold IDO round - 12280000 CPAN for 2456BNB

• Is the token listed on a centralized/decentralized exchange?

We have listed on PancakeSwap at 17th October
• Check Smart Contract Completed? Where can we find this information?

Yes, our Smart Contract has been audited by TechAudit. Here is the document file:
https://drive.google.com/file/d/1LxFmh3hN2elNgJw4beASVQL5uAyWLTNO/view?usp=sharing

**Comment by cryptomanz** [comment]
> CMC ranking 1074: https://coinmarketcap.com/currencies/cryptoplanes/
> BSCscan: https://bscscan.com/address/0x04260673729c5f2b9894a467736f3d85f8d34fc8
> CGK: https://www.coingecko.com/en/coins/cryptoplanes

example:
Screenshot 2021-10-06 at 20 22 37

**Comment by nhuanvolter** [comment]
Here is CryptoPlanes.json file and our logo
https://drive.google.com/drive/folders/1Tj7ACZQ2dtxCHBrAKAR7NvnDAuzDCnlM?usp=sharing

**Pull request merged**
