### PR TITLE
Add SavePlanetEarth V3 (BEP20)

### PR DESCRIPTION
**Pull request by thom-0172**
Adding info for BEP20 token 'SavePlanetEarth V3'.

PR created by <a href="https://assets.trustwallet.com">TW Assets Management</a>

### CODE REVIEW

**Comment by kfapplications** [comment]
@zachzwei @Iamdeadlyz To add, SPE has been listed twice before by Trustwallet and the fee has been paid 2 times as well. With relation to the Bitmart hack, a large amount of SPE was stolen. To protect our holders, the V2 contract has been disabled, and the team has supplied all the funds themselves to ensure maximum security for our users.

Seen as we listed twice before, and having spend a lot of funds due to a hack which the team had no influence on, would it be possible to get approval without having to pay the fee for the third time?

The old 2 contracts were:

SPE: 0xdBaAa36B347d56b77Ce0e36f050fCeEBbF9fbc38
SPE V2: 0x5a4f765476fd1bf010783b47a25cbf10974e6a37

**Comment by cryptomanz** [comment]
Hello,
Please follow the rules for adding token, your logo should be a full screen, 256x256.

**Comment by cryptomanz** [comment]
Submission looks good. awaiting fee payment.

**Comment by kfapplications** [comment]
Could u look at my message before? SPE is a environmental token which suffered from the BitMart hack. Due to their mistake, we were forced to migrate our contract to make sure the hacker had no ability to sell the stolen tokens.

Since we used our own funds for the liquidity, could it be possible to, as a sign of generosity in the hacking case, be accepted without payment? We have paid 2 times before for this token.

**Comment by Cryptocool1** [comment]
> Could u look at my message before? SPE is a environmental token which suffered from the BitMart hack. Due to their mistake, we were forced to migrate our contract to make sure the hacker had no ability to sell the stolen tokens.
> 
> Since we used our own funds for the liquidity, could it be possible to, as a sign of generosity in the hacking case, be accepted without payment? We have paid 2 times before for this token.

you need to pay the fee for that.

**Comment by kfapplications** [comment]
Hi, is this accepted now?

**Pull request merged**
