### PR TITLE
Add MuratiAI (BEP20)

### PR DESCRIPTION
**Pull request by lejyoner1**
Adding info for BEP20 token 'MuratiAI'.

PR created by <a href="https://assets.trustwallet.com">TW Assets Management</a>

### CODE REVIEW

**Comment by cryptomanz1** [comment]
As per our policy, there is a minimum requirement of 10,000 holder addresses and 15,000 transactions, in order to filter out scam tokens.
See the criteria at : https://developer.trustwallet.com/listing-new-assets/requirements .

**Comment by cryptomanz1** [comment]
• What is the purpose of this token? How will it benefit Trust Wallet users?
 • How is the token being distributed? Are you conducting an airdrop?
 • Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?
 • Is the token listed on a centralized/decentralized exchange?
 • Is a Smart Contract audit completed? Where can we find this information?

**Comment by Cryptocool1** [comment]
Hello! How did you get more than 8k holders within 24hours?

**Comment by lejyoner1** [comment]
> Hello! How did you get more than 8k holders within 24hours?



> Hello! How did you get more than 8k holders within 24hours?

Hello,

We carried out trend work on many cryptocurrencies pages and platforms, especially Twitter, Youtube and Telegram phenomena. We have offered our investors benefits such as stakes and rewards for buying certain amounts. We've been trending on Crypto.com, Coinmarketcap, Coinsniper, Reddit, and even Twitter. Our Telegram and Discord artificial intelligence bot was highly appreciated and 2 important and Dr. We have 2 important supporters and advisers, Peter Thai and Professor Tony Tong. There is detailed information about them on our website. Trustwallet is a platform we love and value. And it's an honor for us to be here.

Kind regards

**Comment by lejyoner1** [comment]
Hello ,

No updates have been received. What is the latest situation? When will the logo update be provided?

Kind regards

**Comment by lejyoner1** [comment]
Hello, what is the result? There is no update yet. Our community is looking forward to it.

**Comment by Cryptocool1** [comment]
Hello, your project is less than 1 week old, we are not adding brand new tokens, you can see it in our requirements

**Comment by lejyoner1** [comment]
The contract creation process is 1 week and 9 days. The start of the project is much older than that. That time is just the creation time of the contract. Also 14 hours ago the logo of the 15-day project was updated ? What is your criteria and duration for this? If that was a problem, I think you would have said it the first time. But 3 days passed.

**Comment by lejyoner1** [comment]
Listing Acceptance Guidelines
The following criteria will be considered before an asset is accepted into the repository. Note that meeting all these criteria does not guarantee a submission will be accepted, the team reserves the right to reject projects deemed spammy, fraudulent, or otherwise low value.
Project has a website and a detailed white paper. A clear roadmap, tokenomics and use case is a must.
Has a social media presence and support team. No fake followers or bots.
A full token audit is completed by reputable security audit groups. Partial audits are subject for review.
No plagiarized content from other projects or companies. Copying names or logos are strictly prohibited.
Token should be listed on price tracking sites like CoinmarketCap
Detailed Token Information
Minimum 10,000 token holders and 15,000 transactions (Airdrop tokens excluded). This requirement is subject for review based on the project

Also, if we saw something about duration here, we would have already paid attention to it.

**Pull request merged**
