### PR TITLE
Add DEXIT (BEP20)

### PR DESCRIPTION
**Pull request by p2ptrade-online**
Adding info for BEP20 token 'DEXIT'.

PR created by <a href="https://assets.trustwallet.com">TW Assets Management</a>

### CODE REVIEW

**Comment by tejen2020** [comment]
hi there, 

can i proceed payment ?

**Comment by tejen2020** [comment]
hi there, 

is there anything i have to work on this ?

**Comment by Cryptocool1** [comment]
hello,
• What is the purpose of this token? How will it benefit Trust Wallet users?
 • How is the token being distributed? Are you conducting an airdrop?
 • Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?
 • Is the token listed on a centralized/decentralized exchange?
 • Is a Smart Contract audit completed? Where can we find this information?

**Comment by tejen2020** [comment]
> hello,
> • What is the purpose of this token? How will it benefit Trust Wallet users?

Dexit planning to Build world’s most advanced cryptocurrency exchange. Combining the speed and features of a centralized exchange with the security of a DEX, Dexit will be the only cryptocurrency exchange that does not compromise performance or security. The new exchange makes it easier than ever for market makers to integrate with their existing infrastructure and provide deep liquidity in a secure manner.

> • How is the token being distributed? Are you conducting an airdrop?
we have issued CMS 1:1 DXT token 
we have announce publicly to change CMS token to DXT token below is link 
https://www.facebook.com/Dexit.Finance/posts/110073714680165

> • Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?

We did a token presale on CMS but since we migrate CMS holder to DXT holder basically swapped CMS 1:1 for DXT
CMS presale was fair lunch

> • Is the token listed on a centralized/decentralized exchange?
yes it is listed on Pancakeswap below is link 
https://exchange.pancakeswap.finance/#/swap?outputCurrency=0x2b2ff80c489dad868318a19fd6f258889a026da5


> • Is a Smart Contract audit completed? Where can we find this information?

yes Contract has been audited, below is Audit report document link 
https://technologyofnepal.com/wp-content/uploads/2021/08/Dexit.Finance-Security-Audit-Report.pdf

**Comment by tejen2020** [comment]
hi there, we would like to update our logo we have recently update our branding logo so we would like to update accordingly please find attached new logo 

thanks.
logo

**Pull request merged**
