### PR TITLE
Add KISSAN (BEP20)

### PR DESCRIPTION
**Pull request by PankajTMB**
Adding info for BEP20 token 'KISSAN'.

PR created by <a href="https://assets.trustwallet.com">TW Assets Management</a>

### CODE REVIEW

**Comment by cryptomanz** [comment]
• What is the purpose of this token? How will it benefit Trust Wallet users?
 • How is the token being distributed? Are you conducting an airdrop?
 • Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?
 • Is the token listed on a centralized/decentralized exchange?
 • Is a Smart Contract audit completed? Where can we find this information?

**Comment by PankajTMB** [comment]
•	What is the purpose of this token? How will it benefit Trust Wallet users?
Ans: KSN offerings (ICOs) are a way to raise capital or participate in Agriculture   Farmer opportunities. Our prime focus is to make our Farmer stay, for that, we have built our business in a manner that would help you to trade profitability, and would help us to buy your side.

	•	How is the token being distributed? Are you conducting an airdrop?
Ans: A portion of the tokens are reserved for the project's developers and some are held for business development and expansion purpose. However we're not conducting an airdrop yet.

	•	Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?
Ans: No, all of our token are sold in PancakeSwap and Vindax Exchange.

	•	Is the token listed on a centralized/decentralized exchange?
Ans: KSN is listed on PancakeSwap, PancakeSwap and Vindax  https://vindax.com/exchange-base.html?symbol=KSN_USDT.

	•	Is a Smart Contract audit completed? Where can we find this information?
Ans: Yeah we have Contract Audit completed we have mention in our website.

**Comment by Cryptocool1** [comment]
can you send your smart contract here?

**Comment by PankajTMB** [comment]
@Cryptocool1 

Smart Contract :-  https://bscscan.com/address/0xC8A11F433512C16ED895245F34BCC2ca44eb06bd

**Comment by cryptomanz** [comment]
Please send smart contract audit.

**Comment by PankajTMB** [comment]
@cryptomanz 

Smart Contract Audit :- https://kissan.io/KISSAN-Audit-Report-final.pdf

**Comment by themadbrains18** [comment]
@cryptomanz1 @Cryptocool1 
Please add our price. we are successful listed KISSAN price  at CoinMarketCap.
Here is Link : https://coinmarketcap.com/currencies/kissan/

**Comment by PankajTMB** [comment]
@cryptomanz1 @Cryptocool1
Please add our price. we are successful listed KISSAN price at CoinMarketCap. 
Here is Link : https://coinmarketcap.com/currencies/kissan/

**Comment by Cryptocool1** [comment]
> @cryptomanz1 @Cryptocool1
> Please add our price. we are successful listed KISSAN price at CoinMarketCap.
> Here is Link : https://coinmarketcap.com/currencies/kissan/

Hello, the price is visible for your token

**Comment by neeraj8696** [comment]
@PankajTMB @cryptomanz1 @Cryptocool1 Please change our ksn logo and website info also 
here is the new file for logo- 
https://staking.kissantoken.io/32x32.png

website - kissantoken.io

**Comment by Mizanur1988** [comment]
How can Add My Missing Asset By Trust wallet,plz help ,Cz I don't know how
can Successfully Save Token By trust wallet/metamask ,plz send Helpful
tutorial ,,

**Pull request merged**
