### PR TITLE
Add Alchemy (ACH) (erc20)

### PR DESCRIPTION
**Pull request by tusharsingh7**
Adding info and logo for erc20 token 'Alchemy (ACH)'.

### CODE REVIEW

**Comment by shixianli158** [comment]
good

**Comment by tusharsingh7** [comment]
https://www.huobi.com/en-us/exchange/ach_usdt/
https://www.coingecko.com/en/coins/alchemy-pay

**Comment by catenocrypto** [comment]
send 7 bnb to addresss  bnb1f29knh46qztqvy6ha6r3gpm5jxx8aujdd4gq2j To process request

**Comment by Iamdeadlyz** [comment]
⚠ **Please ignore the message of the impersonator:** https://github.com/trustwallet/assets/pull/5136#issuecomment-748886224

**Comment by tusharsingh7** [comment]
Ok but process my request please sir . I am waiting . 
thank you 
https://www.coingecko.com/en/coins/alchemy-pay
https://coinmarketcap.com/currencies/alchemy-pay/markets/

ACH listed on many exchangers like huobi,bilaxy,mxc,probit,hotbit .
Also full fills address and transaction condition .

**Comment by catenocrypt** [comment]
Please be aware of scam message.  This is from a copycat account, added an 'o' to my username.

image

**Comment by catenocrypt** [comment]
Submission looks OK.

**Comment by tusharsingh7** [comment]
Ok thanks for protecting me from impersonator but process my request please sir . I am waiting .
thank you . Links of CMC and coingecko below :
https://www.coingecko.com/en/coins/alchemy-pay
https://coinmarketcap.com/currencies/alchemy-pay/markets/

ACH listed on many exchangers like huobi,bilaxy,mxc,probit,hotbit .
Also full fills address and transaction condition.
@catenocrypt , @zachzwei and @Iamdeadlyz

**Comment by tusharsingh7** [comment]
In how much time it will reflect on trust wallet and also on uniswap .

**Comment by tusharsingh7** [comment]
Thank you

**Pull request merged**
