### PR TITLE
Please upload logos as soon as possible sir...

### PR DESCRIPTION
**Pull request by SaAtHi1**

### CODE REVIEW

**Comment by SaAtHi1** [comment]
@catenocrypt 
@zachzwei 
@rfunduk 
@corymsmith 

Please upload asap sir

**Comment by zachzwei** [comment]
Please provide more details about this project. We will be closing this for now.
You can reopen when you have met the requirements mentioned here:
https://community.trustwallet.com/t/how-to-submit-a-token-logo/3863#how-to-get-approved

You can follow this format when adding an info.json file:

``` {
   "name":"Bitcoin",
   "website":"https://bitcoin.org",
   "source_code":"https://github.com/bitcoin",
   "white_paper":"https://bitcoin.org/bitcoin.pdf",
   "short_description":"Bitcoin is a cryptocurrency and worldwide payment system.",
   "explorer":"https://blockchain.info",
   "research":"https://research.binance.com/en/projects/bitcoin"
}

**Comment by SaAtHi1** [comment]
i have details now...
 how to reopen sir?

**Comment by SaAtHi1** [comment]
@zachzwei 
How to reopen???????????

**Comment by catenocrypt** [comment]
Where are the details?  I can see only 3 png files, no info.json.

**Pull request closed without merging**
