### PR TITLE
Add Logo and info

### PR DESCRIPTION
**Pull request by ghost**
allow us to have my project on the trust wallet for the investors of my project thank you

### CODE REVIEW

**Review by lockchainfinance — COMMENTED** [review]
please tell me what is wrong about this thank you

**Comment by lockchainfinance** [comment]
> File not allowed: 0xAC4C2903FB2F073E94DE57C79D8BEC5155662122/info.json. Please revert it.
> File not allowed: 0xAC4C2903FB2F073E94DE57C79D8BEC5155662122/logo.png. Please revert it.

SO SORRY I THINK I DELETE MY FILE FOR MY LOGO

**Comment by lockchainfinance** [comment]
please tell me what i need to do to approve this

**Comment by catenocrypt** [comment]
Correction needed:  Json is invalid, I think there is a missing comma before the explorer line.  Please correct.

Could not retrieve info file; lockchainfinance/assets/master 0xAc4c2903fb2f073e94De57c79D8Bec5155662122, SyntaxError: Unexpected string in JSON at position 695

image

**Comment by lockchainfinance** [comment]
> Correction needed: Json is invalid, I think there is a missing comma before the explorer line. Please correct.
> 
> Could not retrieve info file; lockchainfinance/assets/master 0xAc4c2903fb2f073e94De57c79D8Bec5155662122, SyntaxError: Unexpected string in JSON at position 695
> 
> image

i send a new file for this

**Review by lockchainfinance — COMMENTED** [review]
im confuse now please help what i need to do -_- 

`{
    "name": "Lock Chain Finance",
    "type": "BEP20",
    "symbol": "LOCKCHAIN",
    "decimals": 0,
    "website": "https://www.lockchainfinance.com/",
    "description": "Lock Chain Finance (LOCKCHAIN) is a technology that aims to be an independent. The platform aggregates numerous protocols. For instance, when users deposit, the platform will automatically allocate user funds to the recent consensus with the massive revenue, and provide users an inscription In order to verify the ownership and incomes of LOCKCHAIN token. The platform enable users to withdraw their initial deposited tokens and income via LOCKCHAIN Token which can also be exchange to any cryptocurrency.",
    "explorer": "https://bscscan.com/token/0xAC4C2903FB2F073E94DE57C79D8BEC5155662122",
    "status": "active",
    "id": "0xAC4C2903FB2F073E94DE57C79D8BEC5155662122"
} `

**Comment by lockchainfinance** [comment]
can you please help me and teach me how can i fix where im wrong

**Comment by lockchainfinance** [comment]
hello i think i delete my file on the asset
how can i upload my new edited file to fix my problem about adding logo on trust wallet

**Comment by lockchainfinance** [comment]
someone can assist me please

**Comment by lockchainfinance** [comment]
please someone can help me to fix my problem about my add logo and info of my project

**Comment by Cryptocool1** [comment]
> please someone can help me to fix my problem about my add logo and info of my project

You can create new PR. Make sure to mention this PR, so that we can see that fee has been paid already here.

**Comment by nebulachainfinance** [comment]
> > please someone can help me to fix my problem about my add logo and info of my project
> 
> You can create new PR. Make sure to mention this PR, so that we can see that fee has been paid already here.

thank you !!!

**Comment by Cryptocool1** [comment]
Duplicate of #7488 
payed

**Pull request closed without merging**
