### PR TITLE
added MLTPX

### PR DESCRIPTION
**Pull request by moonlift**
Added the new MLTPX token

### CODE REVIEW

**Comment by Cryptocool1** [comment]
hello,
• What is the purpose of this token? How will it benefit Trust Wallet users?
 • How is the token being distributed? Are you conducting an airdrop?
 • Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?
 • Is the token listed on a centralized/decentralized exchange?
 • Is a Smart Contract audit completed? Where can we find this information?

**Comment by moonlift** [comment]
Hi i answered your questions bellow: 

• What is the purpose of this token? How will it benefit Trust Wallet users?
Answer: Moonlift will be a fully custom developed multichain Dex with function such as Swap, Farming, Supernova pool, Lottery, NFT marketplace, Play & earn. MLPTX will serve as Governance token over all chains Moonlift Dex has to offer. trustwallet is perfect for MLTPX because trustwallet is a multichain wallet and MLTPX can soon be used on multiple blockchains

• How is the token being distributed? Are you conducting an airdrop?
we have issued MLTPX 1:1 to MLTP holders

• Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?
We did a token presale on MLTP but since MLTP can't be use anymore we swapped MLTP 1:1 for MLTPX

• Is the token listed on a centralized/decentralized exchange?
At the Moment it's listed on our own dex dex.moonlift.io

• Is a Smart Contract audit completed? Where can we find this information?
Yes information is on our website www.moonlift.io

**Comment by Cryptocool1** [comment]
> Hi i answered your questions bellow:
> 
> • What is the purpose of this token? How will it benefit Trust Wallet users?
> Answer: Moonlift will be a fully custom developed multichain Dex with function such as Swap, Farming, Supernova pool, Lottery, NFT marketplace, Play & earn. MLPTX will serve as Governance token over all chains Moonlift Dex has to offer. trustwallet is perfect for MLTPX because trustwallet is a multichain wallet and MLTPX can soon be used on multiple blockchains
> 
> • How is the token being distributed? Are you conducting an airdrop?
> we have issued MLTPX 1:1 to MLTP holders
> 
> • Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?
> We did a token presale on MLTP but since MLTP can't be use anymore we swapped MLTP 1:1 for MLTPX
> 
> • Is the token listed on a centralized/decentralized exchange?
> At the Moment it's listed on our own dex dex.moonlift.io
> 
> • Is a Smart Contract audit completed? Where can we find this information?
> Yes information is on our website [www.moonlift.io](http://www.moonlift.io)

can you prove your MLTP token ownership ?

**Comment by moonlift** [comment]
> > Hi i answered your questions bellow:
> > • What is the purpose of this token? How will it benefit Trust Wallet users?
> > Answer: Moonlift will be a fully custom developed multichain Dex with function such as Swap, Farming, Supernova pool, Lottery, NFT marketplace, Play & earn. MLPTX will serve as Governance token over all chains Moonlift Dex has to offer. trustwallet is perfect for MLTPX because trustwallet is a multichain wallet and MLTPX can soon be used on multiple blockchains
> > • How is the token being distributed? Are you conducting an airdrop?
> > we have issued MLTPX 1:1 to MLTP holders
> > • Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?
> > We did a token presale on MLTP but since MLTP can't be use anymore we swapped MLTP 1:1 for MLTPX
> > • Is the token listed on a centralized/decentralized exchange?
> > At the Moment it's listed on our own dex dex.moonlift.io
> > • Is a Smart Contract audit completed? Where can we find this information?
> > Yes information is on our website [www.moonlift.io](http://www.moonlift.io)
> 
> can you prove your MLTP token ownership ?

How can I easily prove that to you? Do you want me to do a transaction from the contract creator adress?

**Comment by moonlift** [comment]
i didn't recieved a reply the last time.  How do you want me to prove token ownership ? Do you want mee to make an transaction ? @Cryptocool1

Please let me know, thanks in advance

**Comment by Cryptocool1** [comment]
> > > Hi i answered your questions bellow:
> > > • What is the purpose of this token? How will it benefit Trust Wallet users?
> > > Answer: Moonlift will be a fully custom developed multichain Dex with function such as Swap, Farming, Supernova pool, Lottery, NFT marketplace, Play & earn. MLPTX will serve as Governance token over all chains Moonlift Dex has to offer. trustwallet is perfect for MLTPX because trustwallet is a multichain wallet and MLTPX can soon be used on multiple blockchains
> > > • How is the token being distributed? Are you conducting an airdrop?
> > > we have issued MLTPX 1:1 to MLTP holders
> > > • Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?
> > > We did a token presale on MLTP but since MLTP can't be use anymore we swapped MLTP 1:1 for MLTPX
> > > • Is the token listed on a centralized/decentralized exchange?
> > > At the Moment it's listed on our own dex dex.moonlift.io
> > > • Is a Smart Contract audit completed? Where can we find this information?
> > > Yes information is on our website [www.moonlift.io](http://www.moonlift.io)
> > 
> > 
> > can you prove your MLTP token ownership ?
> 
> How can I easily prove that to you? Do you want me to do a transaction from the contract creator adress?

yes, please

**Comment by moonlift** [comment]
@Cryptocool1 to which wallet you want me to make an transaction? i can send 0.00123 bnb from the tokenowner address to you.

please let me know.

**Comment by moonlift** [comment]
Can i receive a update for approval of the token? It has taken some time now.  @catenocrypt , @zachzwei , @Cryptocool1

**Pull request merged**
