### PR TITLE
BOLT_new_contract

### PR DESCRIPTION
**Pull request by RonSherfey**
This PR is being closed due to inactivity. If you wish to continue, please have us reopen the PR before sending your payment.
Do NOT send payments for closed PR, as the fee may by lost!
  (99 vs. 99 hrs)

### CODE REVIEW

**Review by RonSherfey — COMMENTED** [review]
review for changes in added addresses

**Review by RonSherfey — COMMENTED** [review]
changes

**Comment by catenocrypt** [comment]
Correction needed: 
Please also add an `info.json` file next to the `logo.png` file, with info about the project, of the form:

```json
{
    "name": "Trust Wallet Token",
    "type": "ERC20",
    "symbol": "TWT",
    "decimals": 8,
    "description": "Utility token to increase adoption of cryptocurrency.",
    "website": "https://trustwallet.com",
    "explorer": "https://explorer.binance.org/asset/TWT-8C2",
    "status": "active",
    "id": "TWT-8C2"
}
```

**Comment by RonSherfey** [comment]
Im not sure exactly what youre asking of me?

**Pull request closed without merging**
