### PR TITLE
ICEBRK token address update

### PR DESCRIPTION
**Pull request by icebreak-r**
renamed our old token folder to 0x82b4b883c813dF83623Dc7894c1895305680fec2

icebrk token has migrated to a new contract (0x82b4b883c813dF83623Dc7894c1895305680fec2)

the old contract address is 0xaabcac4b236d1a7290fb05234862348d274621cf  and is no longer in use.

here is our article discussing our contract migration: https://icebreak-r.medium.com/revised-icebrk-contract-upgrade-and-liquidity-migration-plan-6-16-9760ccc6a5de

### CODE REVIEW

**Comment by cryptomanz** [comment]
• How will it benefit Trust Wallet users?
 • How is the token being distributed? Are you conducting an airdrop?
 • Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?
 • Is the token listed on a centralized/decentralized exchange?
 • Is a Smart Contract audit completed? Where can we find this information?

**Comment by Cryptocool1** [comment]
hello,
cant find contract on your website
please check/add

**Comment by icebreak-r** [comment]
@Cryptocool1 token contract is in all chart links in main menu also under resources in bscscan link as well as I just added it under the video on the right to be more pronounced.
@cryptomanz we were already listed on trustwallet with our old contract address. 
- We have 4620 holders and they are asking when the new contract address will be updated on trust wallet as most are holding in trust wallet.  
- all previous holders of old contract were dropped the new token during migration automatically.
- i shared the medium article describing our migration and we also have other articles as well regarding the project.
- people can buy our token on pancake swap and our own swapdex at swap.icebreak-r.com
- previous listed token with you guys had a presale we are now 6 weeks old and actively being traded.
- we have received a quick audit from techrate and are currently working with them on a full audit. 
- https://icebreak-r.com/wp-content/uploads/2021/07/IceBreakR.pdf (techrate quick audit)

We appreciate you working on this for us.

**Comment by icebreak-r** [comment]
@cryptomanz is this old token removed?  some people still see two it is confusing

**Pull request merged**
