### PR TITLE
Add Kryxivia (BEP20)

### PR DESCRIPTION
**Pull request by w0dm4n**
Adding info for BEP20 token 'Kryxivia'.

PR created by <a href="https://assets.trustwallet.com">TW Assets Management</a>

### CODE REVIEW

**Comment by Cryptocool1** [comment]
are you the owner of GraphLinq?

**Comment by w0dm4n** [comment]
Indeed! :)

**Comment by Cryptocool1** [comment]
we can only accept KXA token, due to our requirements. Please create new PR with only KXA token files. Make sure to mention this PR so the fee can be reused

**Comment by w0dm4n** [comment]
On it!

**Pull request closed without merging**
