### PR TITLE
Add LunaDoge info and logo

### PR DESCRIPTION
**Pull request by CryptoMangler**
Adding info and logo image for BEP20 token LunaDoge (LOGE)

### CODE REVIEW

**Comment by Cryptocool1** [comment]
Correction needed:
Contract is not in checksum format, should be 0xB99172949554E6C10c28c880eC0306d2A9d5C753

**Comment by CryptoMangler** [comment]
Damn i messed up the contract format

**Comment by CryptoMangler** [comment]
Do i have to resubmit or can I edit

**Comment by Cryptocool1** [comment]
> Do i have to resubmit or can I edit

It's up to you, you can create new PR or change contract here

**Comment by CryptoMangler** [comment]
Trying to figure out how to change contract from here

**Comment by CryptoMangler** [comment]
I think I got it

**Pull request merged**
