### PR TITLE
Add ARGON logo and Info

### PR DESCRIPTION
**Pull request by ahmetoznar**

### CODE REVIEW

**Comment by catenocrypt** [comment]
Token folder should be in checksum format, could you rename it?

```
-  XXX 'Folder structure for chain smartchain (ethereum fork)':  1 errors
   XXX   'Expect asset at path /home/runner/work/assets/assets/blockchains/smartchain/assets/0x851f7a700c5d67db59612b871338a85526752c25 in checksum: '0x851F7a700c5d67DB59612b871338a85526752c25''
   Action 'Logo sizes' has 1 check steps
```

**Comment by ahmetoznar** [comment]
I changed this folder name

**Comment by catenocrypt** [comment]
The files got duplicated, I readded them in the correct folder.

**Review by 641210 — COMMENTED** [review]
image

**Pull request merged**
