### PR TITLE
Add new token NVIR

### PR DESCRIPTION
**Pull request by nvirworld**
Add new token NVIR in Trustwallet assets.

### CODE REVIEW

**Comment by nvirworld** [comment]
Failed to get info.json content: failed to unmarshal json: invalid character ':' after top-level value

there is a message from merge-fee-bot saying this, what does this mean?
If the json file is incorrect, how is it supposed to be changed?

If there is anything that might need a quicker answer from our ends, please e-mail us at:
nvirworld.contact@gmail.com

**Comment by nvirworld** [comment]
Token check error:
❌ at least 2 links are required, 0 present. Add as many as you can: twitter, github, telegram, reddit, etc
❌ at least 1 tag is required

what does this mean?

**Comment by Cryptocool1** [comment]
Please create new PR, follow doc https://developer.trustwallet.com/assets/requirements
You may want to try our Assets app in beta; go to https://assets.trustwallet.com, log on with Github, enter contract ID, logo and some additional info, and it will create a PR for you.
See https://developer.trustwallet.com/assets/repository_details

**Comment by nvirworld** [comment]
image

**Pull request closed without merging**
