### PR TITLE
Add SATOZ Logo

### PR DESCRIPTION
**Pull request by SatozZhao**
Add Satozhi (SATOZ) Logo and Information

### CODE REVIEW

**Comment by Cryptocool1** [comment]
Hello,
- Your Logo image too large, max 100 kB, current 118.706 kB.

**Comment by Cryptocool1** [comment]
Hello,
You should create  new fork and use the app https://assets.trustwallet.com

**Comment by SatozZhao** [comment]
Okay completed Sir,

New Fork : https://github.com/trustwallet/assets/pull/6588

Thank you.

Pada tanggal Sen, 19 Apr 2021 pukul 20.41 CryptoA ***@***.***>
menulis:

**Comment by catenocrypt** [comment]
Payment considered to #6588 .

**Pull request closed without merging**
