### PR TITLE
Add INRT (BEP20)

### PR DESCRIPTION
**Pull request by eozdem**
Adding info for BEP20 token 'INRT'.

PR created by <a href="https://assets.trustwallet.com">TW Assets Management</a>

### CODE REVIEW

**Comment by ThaiuLinh** [comment]
> Hi! In order to compensate for the efforts of processing PRs, we kindly ask for a contribution.
>  💀 As **there is no refund**, before **paying the fee**, make sure **new tokens fulfill the minimum circulation and other [acceptance criteria](https://developer.trustwallet.com/listing-new-assets/requirements)**.
>  See also the [PR Fee FAQ](https://developer.trustwallet.com/listing-new-assets/faq).
> 
>  Please pay  **500 TWT**  with the memo **24479**  to the TWT-BEP2 (Binance Chain) address `bnb158fgd782we4tz9vwwcj9pmmxvxhl6z46lfm7c8`.
>  Alternatively, 5 BNB is also accepted (same memo & address).
> 
>  **QR** code: [Trust]( https://api.qrserver.com/v1/create-qr-code/?size=200x200&data=https%3A%2F%2Flink.trustwallet.com%2Fsend%3Fcoin%3D714%26address%3Dbnb158fgd782we4tz9vwwcj9pmmxvxhl6z46lfm7c8%26amount%3D500%26memo%3D24479 ) | [other wallet]( https://api.qrserver.com/v1/create-qr-code/?size=200x200&data=bnb158fgd782we4tz9vwwcj9pmmxvxhl6z46lfm7c8%3Famount%3D500%26memo%3D24479 )
> 
>  *TWT Acquiring*:
> 
>  * [Trust Wallet Tokens (TWT)](https://community.trustwallet.com/t/trust-wallet-token-twt/4187) can be obtained from [DEXs/exchanges](https://community.trustwallet.com/t/where-to-get-trust-wallet-tokens/76641).
>  * TWT-BEP2 is supported (Binance Chain), TWT-BEP20 version on Smart Chain is not.
>  * TWT-BEP20 can be traded with TWT-BEP2 using the Trust Wallet [Swap Option](https://community.trustwallet.com/t/how-to-trade-with-the-built-in-dex-swap-option/169).
> 
>  *Notes*:
> 
>  * New tokens without significant usage are rejected, see criteria mentioned above.
>  * One PR should be for a single project; PR's with more than 10 logos will be rejected.
>  * Payment evaluation happens automatically, but with a few minutes delay.  When payment is detected, an Accept Review is automatically placed on the PR, which is a condition for merge.
>  * Evaluating the PR is done manually, and it is merged only if all conditions are satisfied.
>  There will be a fee to process this request. None of it goes to the developers.
>  Before paying the fee, make sure new tokens fulfill the minimum circulation and other acceptance criteria.
>  If you are paying TWT for the submission, this will be burned automatically. There will be no refunds.

https://github.com/trustwallet/assets/pull/24479/commits/86b4bd7c98ffda451e0f844783afb0f623cb37a2

**Comment by ThaiuLinh** [comment]
> ### PR Summary
> Files OK: 2
> Token in PR: **BEP20** 0xCa6deA83eEFAd38af71469fd2cb1B5823534658c
> Symbol: **INRT** decimals: 18
> Links: [Logo](https://raw.githubusercontent.com/eozdem/assets/br0326-205719/blockchains/smartchain/assets/0xCa6deA83eEFAd38af71469fd2cb1B5823534658c/logo.png) [Info](https://raw.githubusercontent.com/eozdem/assets/br0326-205719/blockchains/smartchain/assets/0xCa6deA83eEFAd38af71469fd2cb1B5823534658c/info.json) [Website](https://www.inrt.to/) [Explorer](https://bscscan.com/token/0xCa6deA83eEFAd38af71469fd2cb1B5823534658c)
> Tags: stablecoin
> Token check err check it manually
> 
> https://github.com/trustwallet/assets/pull/24479/commits/86b4bd7c98ffda451e0f844783afb0f623cb37a2
> 
> <span style="padding: 5px; background-color: rgb(32,32,32);"></span>
> 
> 
> 
>

**Comment by ThaiuLinh** [comment]
> Adding info for BEP20 token 'INRT'.
> 
> 
> 
> PR created by <a href="https://assets.trustwallet.com">TW Assets Management</a>

https://github.com/trustwallet/assets/pull/24479/commits/86b4bd7c98ffda451e0f844783afb0f623cb37a2

**Comment by Cryptocool1** [comment]
• What is the purpose of this token? How will it benefit Trust Wallet users?
 • How is the token being distributed? Are you conducting an airdrop?
 • Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?
 • Is the token listed on a centralized/decentralized exchange?
 • Is a Smart Contract audit completed? Where can we find this information?

**Comment by eozdem** [comment]
• What is the purpose of this token? How will it benefit Trust Wallet users?
     - This token's purpose is to make transfers more stable and easy, especially around INDIA.
• How is the token being distributed? Are you conducting an airdrop?
     - Token is mostly distributed via liquidity mining announcements and DODO Dex. It can be bought through Metamask swap as well.
• Did you sell the tokens at an Initial Coin Offering (ICO) or a token presale?
     - No, current selling activities go through community activities, as it is pegged token there is no ICO or presale has been made. 
• Is the token listed on a centralized/decentralized exchange?
     - Currently, it is listed in DODO Exchange, but we are negotiating with many centralized exchanges.
• Is a Smart Contract audit completed? Where can we find this information?
     - It is not audited yet. However you can check verification of our smart contract from the link below :
     https://repo.sourcify.dev/contracts/full_match/56/0xCa6deA83eEFAd38af71469fd2cb1B5823534658c/

**Comment by Cryptocool1** [comment]
we require smart contract audit, on hold for now.
follow doc https://developer.trustwallet.com/listing-new-assets/requirements

**Comment by Cryptocool1** [comment]
are you listed on CoinMarketCap?

**Comment by eozdem** [comment]
> we require a smart contract audit, on hold for now. follow doc https://developer.trustwallet.com/listing-new-assets/requirements

You can find our audit report at https://www.inrt.to/wp-content/uploads/2023/03/INRT-Audit.pdf

**Comment by eozdem** [comment]
> are you listed on CoinMarketCap?

We are listed in couple of trackers, one of them is below :

https://flooz.trade/trade/0xCa6deA83eEFAd38af71469fd2cb1B5823534658c

**Comment by Cryptocool1** [comment]
I don’t need a screenshot from chatGPT, I need your smart contract audit. 
We also require CoinMarketCap listing, because we only take a price from there

**Comment by Cryptocool1** [comment]
Here is an example of smart contract audit: https://skynet.certik.com/projects/trust-wallet?utm_source=CMC&utm_campaign=AuditByCertiKLink

**Comment by eozdem** [comment]
> I don’t need a screenshot from chatGPT, I need your smart contract audit. We also require CoinMarketCap listing, because we only take a price from there

We're not talking about your needs here. We have an audit report which is made by a most reputable and famous AI. Why are you forcing for us to pay unnecessary amounts to some 3rd party developers? Do you think they are better than an AI? or do you have a connection in certik?

**Comment by Cryptocool1** [comment]
AI is not an audit company. See all of our requirements here: https://developer.trustwallet.com/listing-new-assets/requirements
Come back to us once all requirements are met. Make sure to mention this PR in new one, so fee can be reused.

**Comment by Cryptocool1** [comment]
You can use Techrate, Dessert Finance, Hacken companies as well. They are all reputable companies.

**Comment by Nelly77M** [comment]
You are mad okay
See I am a man of my words anywhere you are in this world I will find you
and end you if you don't give me back all my money you have 7 days

**Pull request closed without merging**
