### PR TITLE
Add Ratscoin (BEP20)

### PR DESCRIPTION
**Pull request by ratscoin-dev**
Adding info for BEP20 token 'Ratscoin'.

PR created by <a href="https://assets.trustwallet.com">TW Assets Management</a>

### CODE REVIEW

**Comment by ratscoin-dev** [comment]
@Cryptocool1 
This is my new PR i created on assets trust wallet app.
Thank for checking and help me in PR: https://github.com/trustwallet/assets/pull/19474
The fee can be reused so please check and upload for me
Many thanks! 🙏

**Comment by cryptomanz** [comment]
• What is the purpose of this token? How will it benefit Trust Wallet users?
 • How is the token being distributed? Are you conducting an airdrop?
 • Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?
 • Is the token listed on a centralized/decentralized exchange?
 • Is a Smart Contract audit completed? Where can we find this information?

**Comment by cryptomanz** [comment]
Please follow the rules for adding token, your logo should be a full screen, 256x256.

**Comment by ratscoin-dev** [comment]
> Please follow the rules for adding token, your logo should be a full screen, 256x256.
logo
thanks for support me

This is logo 256x256, Can U update for me?
Many thanks!

**Comment by hqc-destroy** [comment]
> @cryptomanz 
Thanks for support. Please update my logo.
Many thanks! 🙏

**Comment by cryptomanz** [comment]
• What is the purpose of this token? How will it benefit Trust Wallet users?
 • How is the token being distributed? Are you conducting an airdrop?
 • Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?
 • Is the token listed on a centralized/decentralized exchange?
 • Is a Smart Contract audit completed? Where can we find this information?

**Comment by ratscoin-dev** [comment]
> • What is the purpose of this token? How will it benefit Trust Wallet users? • How is the token being distributed? Are you conducting an airdrop? • Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale? • Is the token listed on a centralized/decentralized exchange? • Is a Smart Contract audit completed? Where can we find this information?

- meme coin charity, NFT opensea
- [presale unicrypt](https://app.unicrypt.network/amm/pancake-v2/ilo/0xA38bC2Bd0ad6d101B096c1Ff284Ca726e874F1a8)
- pancakeswap 
- [audited by rdauditors](https://www.rdauditors.com/wp-content/uploads/2022/03/Rats-Coin-Smart-Contract-Security-Report.pdf) , contract renounced , coingecko , coin marketcap, website ratscoin.com

**Pull request merged**
