### PR TITLE
Add METAMUSK Token logo and info

### PR DESCRIPTION
**Pull request by muskmetaverse**
Add METAMUSK Token logo and info

### CODE REVIEW

**Comment by ramsty** [comment]
can you please add links to your PR
example:https://developer.trustwallet.com/assets/repository_details

**Comment by muskmetaverse** [comment]
> can you please add links to your PR example:https://developer.trustwallet.com/assets/repository_details

Thanks. I added links

**Comment by cryptomanz** [comment]
• What is the purpose of this token? How will it benefit Trust Wallet users?
 • How is the token being distributed? Are you conducting an airdrop?
 • Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?
 • Is the token listed on a centralized/decentralized exchange?
 • Is a Smart Contract audit completed? Where can we find this information?

**Comment by muskmetaverse** [comment]
> • What is the purpose of this token? How will it benefit Trust Wallet users? • How is the token being distributed? Are you conducting an airdrop? • Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale? • Is the token listed on a centralized/decentralized exchange? • Is a Smart Contract audit completed? Where can we find this information?

Hi @cryptomanz,
1. Elon Musk's motivation embodies all that the Musk Metaverse project aspires to: 
unwavering inventiveness and faith in the universe's future. It's never simple to get started, but because of the community and Elon's goal, everything we strive for is community. The creation of the Musk Metaverse will be a significant milestone in the future of cryptocurrencies, allowing people to see the Metaverse and NFTs in a new light. Musk Metaverse will build a fundamentally different environment, generating more riches not only from entertainment and commerce, but also from people's trust, optimism, and macro vision.
2. We have had 2 airdrop rounds to distribute tokens to all eligible members. And we will be having around 3 soon
3. We sold tokens at an ICO.
4. Our token is listed on Pancakeswap.
5. Audit in progress. you can check it here https://www.certik.com/projects/musk-metaverse

**Comment by ramsty** [comment]
Awaiting for smart contract audit. On hold for now.

**Comment by muskmetaverse** [comment]
@ramsty This is the pre-report from Certik https://drive.google.com/file/d/1R9OZAyXMp-xfBZVsRbKZGUEVByb29Nd1/view?usp=sharing
Can you help with the quick process?

**Pull request merged**
