### PR TITLE
Add BBANK(ERC20) token

### PR DESCRIPTION
**Pull request by pedrorv0106**

### CODE REVIEW

**Comment by jack16329** [comment]
BEP20 and ERC20 are the saem BBANK token.
holders are greater than 8000.

**Comment by Cryptocool1** [comment]
hello,
• What is the purpose of this token? How will it benefit Trust Wallet users?
 • How is the token being distributed? Are you conducting an airdrop?
 • Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?
 • Is the token listed on a centralized/decentralized exchange?
 • Is a Smart Contract audit completed? Where can we find this information?

**Comment by jack16329** [comment]
> hello,
> • What is the purpose of this token? How will it benefit Trust Wallet users?
Utility token in app also have legal opinion stating this 
> • How is the token being distributed? Are you conducting an airdrop?
no airdrop
> • Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?
Ido was completed through ignition and bscpad 
> • Is the token listed on a centralized/decentralized exchange?
Uniswap and pancakeswap
> • Is a Smart Contract audit completed? Where can we find this information?
Contract audited by zokyo
[2_5332399578148770036.pdf](https://github.com/trustwallet/assets/files/6810797/2_5332399578148770036.pdf)
[2_5332399578148770042.pdf](https://github.com/trustwallet/assets/files/6810800/2_5332399578148770042.pdf)

**Comment by Cryptocool1** [comment]
How is the token being distributed

**Comment by Cryptocool1** [comment]
What is the purpose of this token? How will it benefit Trust Wallet users?

**Comment by jack16329** [comment]
> How is the token being distributed

Token is distributed monthly. Private sale participants signed a 12 month agreement 
2 months lock 
10 months vesting with 10% release per month

**Comment by jack16329** [comment]
> What is the purpose of this token? How will it benefit Trust Wallet users?

Purpose of the token is 
Used in application 
Staking 

We have had over 1000 trustwallet users consistently ask us to add the info into trustwallet as they use our staking site.

Soo many Trust wallet users asking us was the reason we applied to do this.

**Comment by Cryptocool1** [comment]
can you please add links to your PR?
example: https://developer.trustwallet.com/add_new_asset#info-json-contents

**Comment by jack16329** [comment]
> can you please add links to your PR?
> example: https://developer.trustwallet.com/add_new_asset#info-json-contents

added links

**Comment by jack16329** [comment]
> > can you please add links to your PR?
> > example: https://developer.trustwallet.com/add_new_asset#info-json-contents
> 
> added links

@Cryptocool1 Is there any update?

**Comment by cryptomanz** [comment]
- As per our policy, brand new tokens are not included, there is a minimum requirement of 5000 holder addresses and 10000 transactions, in order to filter out scam tokens.
See the criteria at (mentioned in the first message by the bot): https://community.trustwallet.com/t/how-to-submit-a-token-logo/3863).

**Comment by jack16329** [comment]
> * As per our policy, brand new tokens are not included, there is a minimum requirement of 5000 holder addresses and 10000 transactions, in order to filter out scam tokens.
>   See the criteria at (mentioned in the first message by the bot): https://community.trustwallet.com/t/how-to-submit-a-token-logo/3863).
@cryptomanz 
We have erc20 and bep20 BBANK tokens and it was deployed on April.
Total holder addressses and transactions are greater than 5000 and 10000.
Actually, It's not scam token.
We already shared you our all social links.
Please check again and list our tokens.
Thanks in advance.

**Comment by jack16329** [comment]
> * As per our policy, brand new tokens are not included, there is a minimum requirement of 5000 holder addresses and 10000 transactions, in order to filter out scam tokens.
>   See the criteria at (mentioned in the first message by the bot): https://community.trustwallet.com/t/how-to-submit-a-token-logo/3863).
[@cryptomanz]
You can also check BBANK token here.
https://www.dextools.io/app/uniswap/pair-explorer/0x2a182e532a379cb2c7f1b34ce3f76f3f7d3596f7

photo_2021-07-20_11-12-18
photo_2021-07-20_11-12-13

**Comment by jack16329** [comment]
@cryptomanz waiting answer from you.

**Comment by jack16329** [comment]
@cryptomanz Thanks

**Pull request merged**
