### PR TITLE
Add TronGoldCoin (trc20)

### PR DESCRIPTION
**Pull request by git404x**
Adding info for trc20 token 'TronGoldCoin'.

### CODE REVIEW

**Comment by catenocrypt** [comment]
As per our policy, brand new tokens are not included, there is a minimum requirement of 2500 holder addresses and 5000 transactions, in order to filter out scam tokens.
See the criteria at (mentioned in the first message by the bot): https://community.trustwallet.com/t/how-to-submit-a-token-logo/3863).
This token has no real usage yet (19 addresses). Closing PR for now. Please come back to us when all criteria are met.

https://tronscan.io/#/token20/TKnXHMGYvhamRCTEvDZGeRkamrPM4ehTdU

**Comment by UdayBindal2312** [comment]
I am new developer and want to list token without any scam,i am just trying
to see my token on trustwallet, i already listed on justswap and Oneswap ,I
Am Not Able To Have 2.5k Holders q

**Comment by shixianli158** [comment]
I bounght some little TgC

**Comment by UdayBindal2312** [comment]
Thanks for purchasing , its value too much low because its for testing bot
for airdrop or any event

**Comment by UdayBindal2312** [comment]
Not / bot*

**Pull request closed without merging**
