### PR TITLE
Add WEDEX TOKEN V2 (BEP20)

### PR DESCRIPTION
**Pull request by wedexapp**
Adding info for BEP20 token 'WEDEX TOKEN V2'.

PR created by <a href="https://assets.trustwallet.com">TW Assets Management</a>

### CODE REVIEW

**Comment by cryptomanz** [comment]
your logo should be a full screen, 256x256.

**Comment by wedexapp** [comment]
> your logo should be a full screen, 256x256.

The logo is updated!

**Comment by cryptomanz** [comment]
• What is the purpose of this token? How will it benefit Trust Wallet users?
 • How is the token being distributed? Are you conducting an airdrop?
 • Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?
 • Is the token listed on a centralized/decentralized exchange?

**Comment by wedexapp** [comment]
> • What is the purpose of this token? How will it benefit Trust Wallet users? • How is the token being distributed? Are you conducting an airdrop? • Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale? • Is the token listed on a centralized/decentralized exchange?

- User in trust wallet can hold token and farm the token LP for profit.
- The token is being distributed through farming program.
- There token has been airdroped in airdrop.wedex.app but the airdrop program is stopped for a week ago.
- There is 100.000 token sold at presale at price 1 USDT per DEX.
- Token is listed at Pancakeswap

**Pull request merged**
