### PR TITLE
Add Son of Doge (BEP20)

### PR DESCRIPTION
**Pull request by SODSonofDoge**
Adding info for BEP20 token 'Son of Doge'.

PR created by <a href="https://assets.trustwallet.com">TW Assets Management</a>

### CODE REVIEW

**Comment by SODSonofDoge** [comment]
Certik audit link: https://www.certik.com/projects/son-of-doge
====Please see PR [Add Son of Doge (BEP20) #20455] for payment information. https://github.com/trustwallet/assets/pull/20455

• What is the purpose of this token? How will it benefit Trust Wallet users?
This is a rebrand/relaunch of the SODv2 token so the project carriers with it. An NFT marketplace that utilizes SOD is in the future and a customized launchpad Utilium that allows holders of SOD to earn whitelist spots on the launchpad. Please follow the links for verification https://linktr.ee/SonofDoge.

• How is the token being distributed? Are you conducting an airdrop?
The token is being sold on various exchanges and has a history for holders. Holders of SODv2 will be airdropped their equivalent amounts in SOD.

• Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?
There was no ICO/presale for SOD. The LP for exchanges is being manually paired from SODv2 LP.

• Is the token listed on a centralized/decentralized exchange?
The token is currently being traded on pancakeswap with applications already submitted for migration onto crypto.com. The main reason for the migration is to meet these requirements.

• Is a Smart Contract audit completed? Where can we find this information?
Yes, see the link at the top.

**Comment by Cryptocool1** [comment]
hello, you have too much findings (13) all of them should be resolved

**Comment by SODSonofDoge** [comment]
Hello, did you read the audit or only look at the high level figures? The only "major" risk classification is concerned with centralized ownership which is necessary due to the company's legal structure. If you take a look at the report, 6 of these issues have been resolved and the others have been acknowledged and discussed with the Certik team. Most of these issues are classified as informational and some of the minor issues are focused on 3rd party utilization such as math libraries and using the pancakeswap protocol.

**Comment by SODSonofDoge** [comment]
@Cryptocool1 , please see my reply above.

**Comment by SODSonofDoge** [comment]
@Cryptocool1 , I see that you have updated the tag on this PR. Are we clear to be merged?

Thanks in advance.

**Comment by Cryptocool1** [comment]
how did you get your holders in 10 days?

**Comment by SODSonofDoge** [comment]
Good question, this token is a migration from the SODv2 that is currently listed on TW. Since the migration was completed, SODv2 is no longer functional and the liquidity from v2 was moved to this SC. All of the holders on this SC are organic and can be checked/verified at SODv2. Here is the link: [https://bscscan.com/token/0xCDB943908DE5Ee37998a53f23467017d1A307E60#balances](url)


Essentially the previous token's supply was simply too large to work with so this version reduces the supply and also improves contract transparency for the community. The reduction in supply was necessary as this project is currently working with centralized exchanges for listings and the SODv2 contract supply was too large and incompatible with their platforms. Since the goal of the project is not changing, the holders for this token where airdropped the SOD to match the amount of SODv2 they were holding. Again, I will reiterate that the holders currently on this contract were organically obtained under SODv2.

**Comment by SODSonofDoge** [comment]
Hey, I'm just checking to see where we stand?

**Pull request merged**
