### PR TITLE
Read This Contract (RTC) ecosystem assets

### PR DESCRIPTION
**Pull request by capverka**
This pull request includes the token logos for the Read This Contract (RTC) ecosystem: the RTC token itself, the Liquid Lottery (LIQLO) token and the SwapShip (SWSH) token.

### CODE REVIEW

**Comment by catenocrypt** [comment]
Please add `info.json` file, one per token, next to the `logo.png` files, with info about the projects, of the form:

```json
{
    "name": "Trust Wallet Token",
    "website": "https://trustwallet.com",
    "short_description": "Utility token to increase adoption of cryptocurrency.",
    "explorer": "https://explorer.binance.org/asset/TWT-8C2"
}
```

**Comment by veravoss** [comment]
Token info files committed.

**Comment by catenocrypt** [comment]
Token check.
As per our policy, brand new tokens are not included, there is a minimum requirement of 500 holder addresses and 1000 transactions, in order to filter out scam tokens.
See the criteria at (mentioned in the first message by the bot): https://community.trustwallet.com/t/how-to-submit-a-token-logo/3863#how-to-get-approved

This PR contains three tokens:
- SwapShip -- 388 holders  https://etherscan.io/token/0x3ac2AB91dDF57e2385089202Ca221C360CED0062
- Liquid Lottery -- 104   https://etherscan.io/token/0x59AD6061A0be82155E7aCcE9F0C37Bf59F9c1e3C
- RTC -- 174  https://etherscan.io/token/0x7f9A00E03c2E53A3aF6031C17A150DBeDaAab3dC

Unfortunately none of them reaches our limit of 500.
What we do in such cases is just keep the PR around, and reopen when limits are reached.

**Comment by veravoss** [comment]
Hello @catenocrypt. All 3 tokens have more than 500 holders as I'm writing this, and several thousands transactions. I hope it is sufficient per your policy and you will reconsider my pull request.

Kind regards,
V

**Comment by catenocrypt** [comment]
One is 499 but that will make it ;)

**Pull request merged**
