### PR TITLE
Add FRZ Swapping info& logo

### PR DESCRIPTION
**Pull request by FRZSwapping**
Hello Trust Wallet
please add FRZ Swapping(FRZW) info & logo.
Checksum address: 0x2a5dFE9EDd6D1431eecEA70cBb1635Ba88347BaD Audit : https://contractwolf.io/projects/frzswapping Thank you

### CODE REVIEW

**Comment by Cryptocool1** [comment]
Please create new PR, follow doc https://developer.trustwallet.com/assets/requirements
You may want to try our Assets app in beta; go to https://assets.trustwallet.com, log on with Github, enter contract ID, logo and some additional info, and it will create a PR for you.
See https://developer.trustwallet.com/assets/repository_details

**Comment by FRZSwapping** [comment]
Hello Dear Trust wallet 
What Correction needed? 
thank you

**Comment by Cryptocool1** [comment]
The folder of your files is incorrect. Please create new PR following the instructions above

**Comment by FRZSwapping** [comment]
Hello dear Trust wallet
we did the new PR as you asked & we paid it here , please fix our payment .
Add FRZ Swapping (BEP20) https://github.com/trustwallet/assets/pull/22881
Txid : 5AEF1D7C5CD8A15FECD438A662E510A93B14159CB01BF9F63D892DFE3D283B21
thank you

**Pull request closed without merging**
