### PR TITLE
Add NOCHILL (AVAX Culture Catalyst token)

### PR DESCRIPTION
**Pull request by pythocooks**
We have 11,682 holders as seen here: https://snowscan.xyz/token/0xAcFb898Cff266E53278cC0124fC2C7C94C8cB9a5
Token decimals is 18 on the contract.
X.com link is fixed.

### CODE REVIEW

**Comment by cryptomanz1** [comment]
What is the purpose of this token? How will it benefit Trust Wallet users?
 • How is the token being distributed? Are you conducting an airdrop?
 • Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?
 • Is the token listed on a centralized/decentralized exchange?
 • Is a Smart Contract audit completed? Where can we find this information?

**Comment by nochillavax** [comment]
What is the purpose of this token? How will it benefit Trust Wallet users?

It is a culture coin - one of 5 officially supported by Avalanche. We have trust wallet users in our community so adding the token enhances their user experience.

• How is the token being distributed? Are you conducting an airdrop?

It's already 100% circulating. There was an airdrop (20% of supply) on launch which occurred December 18, 2023


• Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?

No presales or ICO - fair launch. 

• Is the token listed on a centralized/decentralized exchange?

Yes. TraderJoe (dex on avax), poloniex & coinstore (cex)


• Is a Smart Contract audit completed? Where can we find this information?

The source is published and while no official audit has taken place it is using standard ERC-20 implementation which is already well known & tested.

**Comment by cryptomanz1** [comment]
We require smart contract audit from reputable companies. Please see https://developer.trustwallet.com/listing-new-assets/requirements

**Comment by Cryptocool1** [comment]
Please come back to us once your audit is done.
When creating new Pull Request please make sure to mention this one so the fee can be reused.

**Pull request closed without merging**
