### PR TITLE
Listing Wrapped Assets of EcoCelium DeFi

### PR DESCRIPTION
**Pull request by Ma2thy**

### CODE REVIEW

**Comment by Iamdeadlyz** [comment]
As per our policy, brand new tokens are not included. There is a minimum requirement of 500 holder addresses and 1000 transactions in order to filter out scam tokens. See the criteria at (mentioned in the first message by the bot): https://community.trustwallet.com/t/how-to-submit-a-token-logo/3863#how-to-get-approved

This token has below-limit usage yet. Rejecting PR for now. Please come back to us when all criteria are met.
https://etherscan.io/token/0x08cE027e68e7F12818C862faB14CFFE5B9C606FE
https://etherscan.io/token/0x191557728e4d8caa4ac94f86af842148c0fa8f7e
https://etherscan.io/token/0x2ACFf9cc74B104CD8540E9a2F691f22d3BD924d7
https://etherscan.io/token/0x63c9c6BBb3C1dC7769512fD7a9ED49226bEf52f7
https://etherscan.io/token/0x91600b412A68F2CB7c0FeD48A70127CC75341DBa
https://etherscan.io/token/0xD1b8D649Ba4C65Fdc382515E27E3B470Dc9a0585
https://etherscan.io/token/0xa37cb0e224A6D57e636185D65AF9b97c3E940303

**Comment by Iamdeadlyz** [comment]
As per our policy, brand new tokens are not included. There is a minimum requirement of 500 holder addresses and 1000 transactions in order to filter out scam tokens. See the criteria at (mentioned in the first message by the bot): https://community.trustwallet.com/t/how-to-submit-a-token-logo/3863#how-to-get-approved

This token has below-limit usage yet. Rejecting PR.
https://etherscan.io/token/0x08cE027e68e7F12818C862faB14CFFE5B9C606FE
https://etherscan.io/token/0x191557728e4d8caa4ac94f86af842148c0fa8f7e
https://etherscan.io/token/0x2ACFf9cc74B104CD8540E9a2F691f22d3BD924d7
https://etherscan.io/token/0x63c9c6BBb3C1dC7769512fD7a9ED49226bEf52f7
https://etherscan.io/token/0x91600b412A68F2CB7c0FeD48A70127CC75341DBa
https://etherscan.io/token/0xD1b8D649Ba4C65Fdc382515E27E3B470Dc9a0585
https://etherscan.io/token/0xa37cb0e224A6D57e636185D65AF9b97c3E940303

**Comment by Ma2thy** [comment]
Hello dear Iamdeadlyz, thank you for your message, I understand your policy. But all of these tokens are wrapped version of existing tokens which are in daily use. These wrapped ones we would like to use in our DeFi project only, but with availability to store them in Trust Wallet. They will be not listed on any exchange except our DeFi platform.

**Comment by catenocrypt** [comment]
Understood, reopening.

**Comment by catenocrypt** [comment]
Some logos are too large, please fix.

```
-  X 'Check that logos are not too large':  1 errors
   X   'Logo too large: /home/runner/work/assets/assets/blockchains/ethereum/assets/0xa37cb0e224A6D57e636185D65AF9b97c3E940303/logo.png'
```

**Comment by Ma2thy** [comment]
> Some logos are too large, please fix.
> 
> ```
> -  X 'Check that logos are not too large':  1 errors
>    X   'Logo too large: /home/runner/work/assets/assets/blockchains/ethereum/assets/0xa37cb0e224A6D57e636185D65AF9b97c3E940303/logo.png'
> ```

logo

**Comment by Ma2thy** [comment]
Thank you catenocrypt

**Pull request merged**
