### PR TITLE
Add ENERGY POLY COIN (POLYGON)

### PR DESCRIPTION
**Pull request by yenky**
Adding info for POLYGON token 'ENERGY POLY COIN'.

PR created by <a href="https://assets.trustwallet.com">TW Assets Management</a>

### CODE REVIEW

**Comment by yenky** [comment]
Hi ,
the fee is paid with this PR #23317 and all the information was submitted already but it wasn't available for trading that's why we had to wait and now it's ready with Quickswap : https://quickswap.exchange/#/swap?swapIndex=0&currency0=ETH&currency1=0x8f9ca9AB9b0937a2565c4c92e0a99b6f73491a19

Thank you

**Comment by cryptomanz1** [comment]
hello, Are you listed on CMC?

**Comment by yenky** [comment]
Hi @cryptomanz1 
We are here : https://coinmarketcap.com/dexscan/polygon/0xb0005627275595158bf053072ab50b4572b4a7f3

Thank you

**Comment by Cryptocool1** [comment]
Information should be verified and added CMC team
2F90350C-030C-46AC-8E8A-F9BF45D5AC75

**Comment by yenky** [comment]
Hi @Cryptocool1 thank you for quick response

CMC asked to get logo approved on trust wallet and then they will go ahead with cmc. Right now ENG POLY is having trade with one Quickexchange and its going well. 
We have listed other tokens as well which are not listed yet on CMC but logo approved on trust wallet. 

i request you to make it approve so we can go ahead with our CMC process. All users are waiting to see the logo in trust wallet so we can go with cmc and other higher level of exchanges. 

Thank You

**Comment by yenky** [comment]
image

**Comment by Cryptocool1** [comment]
Please see our requirements here: https://developer.trustwallet.com/assets/requirements
Come back to us once CMC requirement is met.

**Comment by yenky** [comment]
Hi 
Let me send you the list of token which should get de-active from trust wallet as per the rules. 

RTC_Plus - 
image

ARTC -
https://www.dextools.io/app/en/bnb/pair-explorer/0xea6c8badd1682ede63883947589ea8df68842442

CGB -
https://www.dextools.io/app/en/bnb/pair-explorer/0xbfb2daf6cbef301f93ac18240ab2b3603e601119

There are many more so please let me know how they got approved with same thing. Also please let me know what process we need to do to make complain about this.

We have been asked from cmc to get logo done from trust wallet and you are asking us to get the cmc , so we are confused what to do. 

Thank you

**Review by white10146 — COMMENTED** [review]
Thanks

**Pull request closed without merging**
