### PR TITLE
Add Jinpeng (SPL)

### PR DESCRIPTION
**Pull request by jinpeng-sol**
Adding info for SPL token 'Jinpeng'.

PR created by <a href="https://assets.trustwallet.com">TW Assets Management</a>

### CODE REVIEW

**Comment by cryptomanz1** [comment]
• What is the purpose of this token? How will it benefit Trust Wallet users?
 • How is the token being distributed? Are you conducting an airdrop?
 • Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?
 • Is the token listed on a centralized/decentralized exchange?
 • Is a Smart Contract audit completed? Where can we find this information?

**Comment by jinpeng-sol** [comment]
> • What is the purpose of this token? How will it benefit Trust Wallet users? • How is the token being distributed? Are you conducting an airdrop? • Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale? • Is the token listed on a centralized/decentralized exchange? • Is a Smart Contract audit completed? Where can we find this information?

1.
Jinpeng ($JIN) is a meme coin inspired by Xi Jinping, designed to highlight China’s strength while countering Trump’s political narrative.

2.
The token is distributed via decentralized exchanges (DEXs) without any current airdrops.

3.
No, there was no ICO or presale for $JIN.

4.
Yes, $JIN is listed on decentralized exchanges. Additionally, the token has been confirmed for listing on LBank, with the official announcement made publicly. It will be listed soon.

Officially announced:
https://x.com/lbankupdates/status/1843747642570092836?s=46

5. 
The contract has been verified and fully approved by third-party sources on Dextools.

**Comment by Cryptocool1** [comment]
Hello, please provide your smart contract audit

**Comment by jinpeng-sol** [comment]
IMAGE 2024-10-14 17:42:26
IMAGE 2024-10-14 17:42:34

The contract for JinPeng (JIN) has been automatically audited by Dextools under their Quick Intel section. As shown in the attached screenshots, the contract is verified, non-mintable, with no red flags or security alerts. Dextools confirms the token’s legitimacy with the ‘audit’ badge. This ensures the integrity and safety of the token. Please let us know if you need any further information.

https://www.dextools.io/app/en/solana/pair-explorer/7ax1wVCoRr192G5cjS3pvdqkbJfqEsecir874424AkpR?t=1728906411052

**Comment by Cryptocool1** [comment]
We require smart contract audit from reputable companies (Techrate, Certik, Hacken, DesserFinance)

**Comment by Cryptocool1** [comment]
Feel free to re-open pull request once you meet those requirements.

**Pull request closed without merging**
