### PR TITLE
Add QWT logo and info

### PR DESCRIPTION
**Pull request by CloizQWT**
Ask for adding QoWatt Token (QWT) into Trust Wallet

### CODE REVIEW

**Comment by CloizQWT** [comment]
Total numbers of holders can be found here : https://api.elrond.com/tokens/QWT-46ac01/accounts/count

**Comment by cryptomanz1** [comment]
• What is the purpose of this token? How will it benefit Trust Wallet users?
 • How is the token being distributed? Are you conducting an airdrop?
 • Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?
 • Is the token listed on a centralized/decentralized exchange?
 • Is a Smart Contract audit completed? Where can we find this information?

**Comment by CloizQWT** [comment]
hello, there is no smart contracts for an ESDT token (Elrond Network). Only a call to the official Elrond SC to create it. We are a big project on Elrond, recognized by Elrond team itself, don't know if this can count as an audit ? for proof, this is one of the tweets from the official CEO of Elrond about us :  https://twitter.com/beniaminmincu/status/1569711191659880448?s=20&t=o5AnXyuy963eKg29nej6qw 

we remain at your disposal

**Comment by cryptomanz1** [comment]
We require full smart contract audit from reputable companies. (Techrate, Certik, Hacken, Dessert Finance)

**Comment by CloizQWT** [comment]
ESDT tokens (elrond blockchain) do not have a smart contract as said before.

We are a proven DeFi project on the Elrond Blockchain (https://elrond.com/blog/qowatt-
joins-metabonding/) which is a partner of TrustWallet (https://elrond.com/blog/elrond-tokens-esdt-trust-wallet/).
For your information, QWT - QoWatt is currently listed on the DEX of the Elrond Blockchain Network in the same way as ZPAY or UTRUST which are currently on Trust Wallet.

**Comment by CloizQWT** [comment]
Total numbers of holders can be found here : https://api.elrond.com/tokens/QWT-46ac01/accounts/count

**Pull request merged**
