### PR TITLE
wloki logo and information

### PR DESCRIPTION
**Pull request by darcys22**
This PR is being closed due to inactivity. If you wish to continue, please have us reopen the PR before sending your payment.
Do NOT send payments for closed PR, as the fee may by lost!
  (60 vs. 60 hrs)

### CODE REVIEW

**Comment by lungdoge** [comment]
Hey Trustwallet, 

Chris here from the Loki Project. I just wanted to leave a comment prior to payment and your team's review explaining a few things so you have some further context.

I can see that you have some user/tx requirements for listing, which I'm afraid we may not meet once you review our request.

wLoki is wrapped Loki, redeemable 1:1 with our mainnet $loki coin (see https://wloki.chainflip.io/#/about. Loki is a mainnet coin with a history of 3 years and many thousands of users (see: https://loki.network/). We recently launched wLoki in order to be able to allow our community to participate in the DeFi ecosystem through tools such as Uniswap. Sadly, we've noticed a fake Loki smart contract trying to attack our community and already a few members have fallen victim to this scam. We are attempting to have Uniswap register our logo (which supposedly occurs through Trust Wallet?) which should help with an additional visual cue that they are visiting the correct contract page/pool. 

Before we process payment in TWT/BNB, I just wanted to touch base to see if we are likely to be given acceptance, with that additional context now. 

Looking forward to your response. 

Regards, 
Chris

**Comment by catenocrypt** [comment]
Hey Chris,
It's a good thing to ask!
We are strict about the circulation requirements, but we apply it with common sense, esp. for the cases when a token is on multiple chains or is a wrapped coin.
I have looked into Loki, and it looks to be a serious project :)  (I had a look at the website, explorer, CMC&coingecko).
So the circulation requirement is OK.

There are some technical issues with the submission though.
Contract folder should be in 'checksum' format.
Supplied logo is too large, recommended size is 256x2546 pixels.  
Could you guys change to a smaller size?
You may use our new tool at http://assets.trustwallet.com  to create PR.

```
Contract is not in checksum format, should be 0x5ff668ddfDcBB7505f41ED56e626E4D4719DcB26
Logo image too large, max 100 kB, current 113.068 kB
Logo should be 256x256 pixels, it is too large 2129x2129
```

**Comment by darcys22** [comment]
Hi can we please reopen this. Will address both the payment and fix the issues on monday

**Comment by lungdoge** [comment]
Hey @catenocrypt, 

Thanks for your reply! We appreciate your common sense approach to our unique situation :) I thought a quick comment would be helpful in resolving all this.

Could you please re-open the PR so we can address those technical issues and make the payment?

Kind regards,
Chris

**Comment by darcys22** [comment]
created new PR with the updated details #5013

**Pull request closed without merging**
