### PR TITLE
Add Simply Staking Cosmos validator

### PR DESCRIPTION
**Pull request by franono**
This PR is being closed due to inactivity. If you wish to continue, please reopen the PR before sending your payment.
Do NOT send payments for closed PR, as the fee may by lost!
  (363 vs. 60 hrs)

### CODE REVIEW

**Comment by zachzwei** [comment]
Payment was made but the PR was autoclosed.
Reopened PR.
https://explorer.binance.org/tx/EC1F8F41BE3FEB94B98F7DA9D3140F06CAC664EBA852467D06F381A839F82646

**Comment by zachzwei** [comment]
Please submit a logo for this validator to complete the request.

**Comment by zachzwei** [comment]
I added a logo that I got from the Twitter profile of your company. Please let us know if this is fine @franono

**Comment by franono** [comment]
Thanks for that @zachzwei 

It is good!

**Pull request merged**
