### PR TITLE
add yETH 

### PR DESCRIPTION
**Pull request by hieplx**
I want to push my dong up hoping you to help me thank you

### CODE REVIEW

**Comment by catenocrypt** [comment]
Files in this submissions are wrong.  Please see guidelines in more details:
https://community.trustwallet.com/t/how-to-submit-a-token-logo/3863

Or you may want to try our new Assets app in beta;  close this PR; go to https://assets.trustwallet.com, log on with Github, enter contract ID, logo and some additional info, and it will create a PR for you.
See  https://community.trustwallet.com/t/how-to-submit-a-token-logo-using-assets-app/82957.

**Comment by hieplx** [comment]
Sorry because my wallet has a problem and the file I sent is also error so
I will contact you later, thank you

Vào Th 6, 11 thg 12, 2020 vào lúc 15:59 Adam R <notifications@github.com>
đã viết:

**Comment by hieplx** [comment]
Sorry my currency has not enough 2500 addresses and 5000 transactions I
want to display my logo on uniswap is there any way?


Vào Th 6, 11 thg 12, 2020 vào lúc 22:26 Lê Hiệp <
lehiep02012001ybl@gmail.com> đã viết:

**Comment by catenocrypt** [comment]
Sorry, I cannot state anything in the name of Uniswap.  In Trustwallet no.

**Pull request closed without merging**
