### PR TITLE
Add Unique Utility (ERC20)

### PR DESCRIPTION
**Pull request by Uniqueutility**
Adding info for ERC20 token 'Unique Utility'.

PR created by <a href="https://assets.trustwallet.com">TW Assets Management</a>

### CODE REVIEW

**Comment by Uniqueutility** [comment]
Hello dear trustwallet,

UNQT token has more than 36,000 holders and 320,000 transactions and created more than 2 years ago.
You can check it in the Etherscan, https://etherscan.io/token/0xa80f2c8f61c56546001f5fc2eb8d6e4e72c45d4c.

Please if possible update logo and information.
Thanks

sincerely Unique Finance

**Comment by Cryptocool1** [comment]
Submission looks good awaiting for fee payment

**Comment by Uniqueutility** [comment]
I thought it’s free.

500 WTW is about $650.

Why we have to pay this amount? most of platforms are free.

so how much time i have until paid?

**Comment by Cryptocool1** [comment]
Please see our documentation https://developer.trustwallet.com/developer/listing-new-assets/pr-fee

**Comment by Uniqueutility** [comment]
I checked, but it shows “page not found”.
36D78F85-F4A0-4D6B-9761-78B1E1FCC09E

**Comment by Uniqueutility** [comment]
If it has fee, please close it.

Because I said that if a project has the desired conditions (holder and transaction, etc.), it could update the information without cost, like other platforms.
Thanks

**Pull request closed without merging**
