### PR TITLE
add info.json & logo for PVPB

### PR DESCRIPTION
**Pull request by pvpbet**

### CODE REVIEW

**Comment by cryptomanz1** [comment]
• What is the purpose of this token? How will it benefit Trust Wallet users?
 • How is the token being distributed? Are you conducting an airdrop?
 • Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?
 • Is the token listed on a centralized/decentralized exchange?
 • Is a Smart Contract audit completed? Where can we find this information?

**Comment by pvpbet** [comment]
> • What is the purpose of this token? How will it benefit Trust Wallet users? • How is the token being distributed? Are you conducting an airdrop? • Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale? • Is the token listed on a centralized/decentralized exchange? • Is a Smart Contract audit completed? Where can we find this information?

• What is the purpose of this token? How will it benefit Trust Wallet users?
Our token is designed to govern the decentralized PVPBet betting platform. Token holders can participate in decision-making processes, such as determining bet outcomes and resolving disputes. For Trust Wallet users, holding this token grants governance rights, access to exclusive platform features, and opportunities to earn rewards through staking or voting.

• How is the token being distributed? Are you conducting an airdrop?
The token distribution follows a structured model, with portions allocated to early participants, strategic partners, and governance contributors. Our unique voting trust mechanism relies on token staking, so tokens cannot be obtained for free through airdrops. To maintain the platform’s integrity, users can only purchase tokens through Uniswap.

• Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?
No, we did not conduct an ICO or token presale.

• Is the token listed on a centralized/decentralized exchange?
We have added a liquidity pool on Uniswap, and users can purchase the token through Uniswap.

• Is a Smart Contract audit completed? Where can we find this information?
We have not yet completed a smart contract audit as the platform is still in its beta phase, and application contracts may be updated in the future. However, the token contract is a standard ERC20 contract that will not change. All contracts have been verified on BaseScan, and users can view them there.
https://docs.pvpbet.xyz/extras/contracts

**Comment by pvpbet** [comment]
@cryptomanz1 Is there any additional information that needs to be added?

**Comment by Cryptocool1** [comment]
Hello, 
Thank you for the answers provided

After careful review of your submission, it looks like this token has not undergone any security audit. The request will be closed until further notice.

To know more about the token approval guidelines, please check this article: [How to Submit Token Logo](https://developer.trustwallet.com/listing-new-assets/requirements).

Feel free to re-open pull request once you meet those requirements.

**Pull request closed without merging**
