### PR TITLE
Updated Tokenomy logo

### PR DESCRIPTION
**Pull request by Nexus7**
Please can you update the logo for the Tokenomy ERC-20 token.

### CODE REVIEW

**Comment by catenocrypt** [comment]
Please add an `info.json` file next to the `logo.png`, with info about the project, of the form:

```json
{
    "name": "Trust Wallet Token",
    "website": "https://trustwallet.com",
    "short_description": "Utility token to increase adoption of cryptocurrency.",
    "explorer": "https://explorer.binance.org/asset/TWT-8C2",
    "socials": [
        {
            "name": "Twitter",
            "url": "https://twitter.com/trustwalletapp",
            "handle": "TrustWalletApp"
        },
        {
            "name": "Reddit",
            "url": "https://reddit.com/r/trustapp",
            "handle": "TrustApp"
        }
    ]
}
```

**Comment by Nexus7** [comment]
@catenocrypt - Sure, I will add that file. Should I close this pull request and open another?

**Comment by catenocrypt** [comment]
Preferably add to this one.

**Comment by Nexus7** [comment]
@catenocrypt - The processing fee of 250 TWT has also been sent: https://explorer.binance.org/tx/BD6237C9DEB2A7D0C3A83BEE0049BEDC7FD0681243870CCA27EE3672A7BFF0F7

**Comment by Nexus7** [comment]
@catenocrypt - Can I check that this will also update the Uniswap front end?

**Pull request merged**
