### PR TITLE
Laqira Protocol (LQR) token was added to TrustWallet repo

### PR DESCRIPTION
**Pull request by Good-Mentality**
Dear TrustWallet team

We have all of your required parameters except for a publicly-shared audit report. Our audit has been provided by SlowMist team and as our NFT marketplace is under construction, the audit report is not completely prepared, but we have received their private audit document for the token section that we can send it to you, privately, if needed. Complete audit report will be uploaded after completing our NFT marketplace and SlowMist team will provide a perfect version of audit which can be uploaded for public view. Please consider our case. We are grateful.

Respects

### CODE REVIEW

**Comment by cryptomanz** [comment]
• What is the purpose of this token? How will it benefit Trust Wallet users?
 • How is the token being distributed? Are you conducting an airdrop?
 • Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?
 • Is the token listed on a centralized/decentralized exchange?
 • Is a Smart Contract audit completed? Where can we find this information?

**Comment by Good-Mentality** [comment]
> • What is the purpose of this token? How will it benefit Trust Wallet users? • How is the token being distributed? Are you conducting an airdrop? • Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale? • Is the token listed on a centralized/decentralized exchange? • Is a Smart Contract audit completed? Where can we find this information?

Laqira Protocol team is in partnership with BKEX exchange. So you can investigate validity of my claims of the exchange's official representatives.

What is the purpose of this token? Laqira Protocol will start its work with an NFT market place which is under construction right now. Market place will come soon and it must be ready before 2022 Expo cryptocurrency exhibition in Dubai in March as we have reserved a booth there for our products. Also we have signed a contract with Mew Games team to create NFT-based play-to-earn games for users. In addition we have interesting plans for Squid Game community which is being operated by the community itself, recently. This plan will be carried out in partnership with BKEX exchange's team.

How will it benefit Trust Wallet users? As I said, we are creating play-to-earn games and NFT stuffs will be bought and sold in our NFT market place. Trust Wallet users can benefit from all aforementioned dapps. Also we are in a good relation with Squid Game community and we have a great plan for them but unfortunately due to sensitivity of the plan, I can't exactly mention it. This will result into attracting more users by Trust Wallet as this huge community will come to Trust Wallet.

How is the token being distributed? Tokens has been already distributed and both distribution and release plan exists in our white paper at https://laqira.io/whitepaper.pdf and our website at laqira.io . Token distribution plan is as follows:
Liquidity Pool: 30%
Ecosystem: 20%
Development: 15%
Marketing: 15%
Team: 15%
Advisory: 5%
Only 30% of the tokens are not locked and in circulation which are maintained in a multisig wallet with following address:
0x5aee524a2faf1911c242a7f51a9af0a6464f51a8
All other tokens are locked in TimeLock wallets and they are released based on a linear plan over 4 years. It means only 6.25% of each share is released after each 3 months and may be added to the current circulation supply. These wallets are as follows:
Ecosystem: 0x6684e5bb47e712d0aa325a2a2874ed81d5d3bf7f
Marketing 0x646d5d46926d4fedff2a43d15881c2ebb773bf9e
Development: 0x60158ec33a48a41830f2842bc6aa85f5aaf4e24b
Team: 0xdb403c600202909a9aa3063aaa7276830c26c323
Advisory: 0x36de86659514aa3a06e1277bb3ecf9fea82de3cd

Are you conducting an airdrop? We are developing an airdrop bot based on Telegram platform. It is under construction. We have developed all basics but we are trying to find a way to avoid abusing of it to collect many tokens using Sybil attack methods. Of course any suggestion by Trust Wallet team is welcome.

Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale? Yes. We have held an IEO in BKEX exchange. Now, we are trying to complete our initial products and attract some investor companies. We have also negotiated with several huge ones but the result will be realized after developing our products such as our NFT market place and providing our product deck based on the product. So we had not any private sale yet but as I explained, we are trying to attract several big ones.

Is the token listed on a centralized/decentralized exchange? Yes. LQR has been listed on BKEX exchange and also PancakeSwap DEX. Of course we have many requests from other exchanges but due to difficulties of handling various exchanges, especially small ones, we are only interested in best tier 2 exchanges such as BKEX, MXC, etc. and tier 1 ones.

Is a Smart Contract audit completed? Our Smart Contract has been provided by SlowMist team and we are in contact with them but as they don't provide official audit for token, lonely and they need to provide audit for a whole project, they are waiting for our NFT market place to investigate it as well and publish the official audit report. However, I can send you proofs and their private report of LQR token, if needed.

Where can we find this information? You can find many useful information of the project in our official website at https://laqira.io and also our CMC profile at https://coinmarketcap.com/currencies/laqira-protocol/ and CG profile at https://www.coingecko.com/en/coins/laqira-protocol.

If I can help you more on project information, please let me know.

Kind regards

**Comment by cryptomanz** [comment]
Please remove 12 and 13 line.

**Comment by Good-Mentality** [comment]
> Please remove 12 and 13 line.

Done! I hope I have edited proper lines. Thanks for your consideration.

**Comment by cryptomanz** [comment]
Screenshot 2021-12-05 at 13 18 16

**Comment by Good-Mentality** [comment]
> Screenshot 2021-12-05 at 13 18 16

Sorry for inconvenience. Done!

**Pull request merged**
