### PR TITLE
Add Little Angry Bunny v2  (BEP20)

### PR DESCRIPTION
**Pull request by LABv2**
Adding info for BEP20 token 'Little Angry Bunny v2 '.

PR created by <a href="https://assets.trustwallet.com">TW Assets Management</a>

### CODE REVIEW

**Comment by LABv2** [comment]
> Hi! In order to compensate for the efforts of processing PRs, we kindly ask for a contribution.
>  As **there is no refund**, before **paying the fee**, make sure **new tokens fulfill the minimum circulation and other [acceptance criteria](https://community.trustwallet.com/t/how-to-submit-a-token-logo/3863)**.
> See also the [PR Fee FAQ](https://developer.trustwallet.com/add_new_asset/pr-fee).
> 
> Please pay **2000 TWT** with the memo **2766** to the address `bnb1tqq9llyr3dyjd559dha6z5r5etk3qfwk07m098`.
> Alternatively, 5 BNB is also accepted (same memo & address).


****Sir we have to pay TWT bep -2 or TWT bep-20 ?********

**Comment by LABv2** [comment]
> Fee is PAID, fantastic! Thanks!
> 
> The PR will be evaluated soon by a maintainer, and if merged, the new logos should be visible in Trust Wallet.
> Please note that the app caches logos (up to several days; if you want to see changes immediately, use a new installation). See the [assets FAQ](https://github.com/trustwallet/assets#faq).
> (@zachzwei, @catenocrypt & @Iamdeadlyz: please take note.)
> 
> ([2000 TWT](https://explorer.binance.org/tx/22ED1BF409C3DD185E919DF14CB81931BEF0265D023323A7BDCEF608C1E35312))

**Sir we are community driven token above 5000 holders from China, USA , Philippines , India , Vietnam , Turkey , Nigeria and many more countries. we have done donation for collecting Fees for paying trust wallet logo. hoping soon you approve our request soon.**

**Comment by Cryptocool1** [comment]
Hello, can you answer some questions?
• What is the purpose of this token? How will it benefit Trust Wallet users?
 • How is the token being distributed? Are you conducting an airdrop?
 • Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?
 • Is the token listed on a centralized/decentralized exchange?
 • Is a Smart Contract audit completed? Where can we find this information?

**Comment by LABv2** [comment]
> Hello, can you answer some questions?
> • What is the purpose of this token? How will it benefit Trust Wallet users?

**Answer - Little Angry Bunny V2 is committed to provide a decentralized transaction network under Binance Smart Chain (BEP-20)  with tockenomics of 4 % burn rate and 7 % redistribution to holders on each transaction . There is no main owner of the LAB token or no developer wallet. this is purely run by Community from the people all over the world. Most of our tokens holders are on trust wallet. We are going to implement multiple use cases like  charity , Swap , gaming and ecommerce website for LAB v2 tradable with pairing stable coins.so our holders are trust wallet users those get benefit of it.
our white paper link - https://littleangrybunnyv2.com/assets/WHITE-PAPER-LAB.pdf**

> • How is the token being distributed? Are you conducting an airdrop?

**Answer - We are community driven token which is migrated to old version to V2 version so old version holders who provided gas fees got there tokens in V2 those are around 400 holders and then our journey started and now our holders are above 5050 which are from different countries like China , USA , INDIA , Philipines ,vietnam , nigeria and many more**

> • Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?

 **Answer - NO**

> • Is the token listed on a centralized/decentralized exchange?

**Answer - yes 

on pancakeswape - https://pancakeswap.info/pool/0x07f5cEdeD6B3dba557B3663EDC8941FB37b63945

poocoin -https://poocoin.app/tokens/0x07f5ceded6b3dba557b3663edc8941fb37b63945

bogged finance - https://charts.bogged.finance/0x07f5cEdeD6B3dba557B3663EDC8941FB37b63945

dextool - https://www.dextools.io/app/pancakeswap/pair-explorer/0xe5d1a819a22d16cc34fad3d2d8f7f553bd474407**
 
> • Is a Smart Contract audit completed? Where can we find this information?

**Answer - we are community driven token work with budget fund. we have free checks audit.is it compulsory to have standard audit.if so then inform us we discuss in community and compulsory then provide you with gathering funding and do it.

and if free check audit ok then we can provide you.**

**Comment by LABv2** [comment]
Our transaction count is 23,347 till today. Our daily average volume is above $ 50000 to $100000

**Comment by LABv2** [comment]
> Our transaction count is 23,347 till today. Our daily average volume is above $ 50000 to $100000

Our contract : https://bscscan.com/token/0x07f5ceded6b3dba557b3663edc8941fb37b63945

**Comment by LABv2** [comment]
> > • Is a Smart Contract audit completed? Where can we find this information?


we gether the fund we will provide you standard audit report soon

**Comment by cryptomanz** [comment]
Hello,
Is this your token? "https://bscscan.com/token/0xf1d4a1dcdbb58be4765e5a40b487b20278bf3fec"

**Comment by LABv2** [comment]
> Hello,
> Is this your token? "https://bscscan.com/token/0xf1d4a1dcdbb58be4765e5a40b487b20278bf3fec" this is not our address.that is old LAB

no. our token not that.

below given is ours. LAB v2

https://bscscan.com/token/0x07f5ceded6b3dba557b3663edc8941fb37b63945

**Comment by LABv2** [comment]
> Hello,
> Is this your token? "https://bscscan.com/token/0xf1d4a1dcdbb58be4765e5a40b487b20278bf3fec"

our token is https://bscscan.com/token/0x07f5ceded6b3dba557b3663edc8941fb37b63945

**Comment by LABv2** [comment]
> Hello,
> Is this your token? "https://bscscan.com/token/0xf1d4a1dcdbb58be4765e5a40b487b20278bf3fec"

that is old LAB token after that LAB v2 revived by community and some holders migrated around 400 holders who paid gas fees got token in LAB v2 the migrated version which purely run by community

**Pull request merged**
