### PR TITLE
Adding KGO LOGO AND DESCRIPTION

### PR DESCRIPTION
**Pull request by KIWIPAY-KGO**
Adding KGO LOGO AND DESCRIPTION

### CODE REVIEW

**Comment by KIWIPAY-KGO** [comment]
Hi, we try to add the Logo and Description from our Token
We see this error, but we dont understand, can somebody help ? Thank you

**Comment by catenocrypt** [comment]
Please fix the JSON formatting (quotes) in the `info.json` file, otherwise it is invalid Json.

```
    "description": “KGO” IS THE WALLET KIWIGO TOKEN,
```

**Review by KIWIPAY-KGO — COMMENTED** [review]
I change the JSON

**Comment by KIWIPAY-KGO** [comment]
I just change the Json and upload new, i still have ALL CHECKS HAVE FAILED

**Pull request closed without merging**
