### PR TITLE
Add LandRocker (POLYGON)

### PR DESCRIPTION
**Pull request by LandRocker**
Adding info for POLYGON token 'LandRocker'.

PR created by <a href="https://assets.trustwallet.com">TW Assets Management</a>

### CODE REVIEW

**Comment by Cryptocool1** [comment]
As per our policy, brand new tokens are not included, there is a minimum requirement of 10,000 holder addresses and 15,000 transactions
See the criteria at : https://developer.trustwallet.com/assets/requirements .

**Comment by LandRocker** [comment]
We understand the criteria outlined in your policy, and we'd like to clarify that we are not a new project. We successfully completed a token sale in March 2024, raising over $2.8 million in funds. Since May 2024, our token has been listed on Uniswap, MEXC, and BingX. You can find the links to our listings below:
[Uniswap Listing](https://app.uniswap.org/explore/tokens/polygon/0xfb7f8a2c0526d01bfb00192781b7a7761841b16c)
[MEXC Listing](https://www.mexc.com/exchange/LRT_USDT)
[BingX Listing](https://bingx.com/en/spot/LRTUSDT/)
In addition, our community is thriving, with over 100,000 followers on both Twitter and Telegram. We also have more than 160,000 organic token transactions, which is over ten times the minimum requirement of 15,000.
We believe our project meets all the necessary criteria and look forward to your confirmation.
To further demonstrate our established presence, we participated in an event in Abu Dhabi in 2021, well before our recent milestones. Here’s a [link to the video](https://youtu.be/jSUAV9Aqp3Q) showcasing our involvement, proving that we are definitely not a new player in the industry.
Moreover, not being included on the list has resulted in Uniswap adding a warning on our pool. This warning could potentially discourage people from buying our token and increasing our holder count. We are planning significant marketing campaigns that we believe will lead to a substantial increase in buyers and token holders. However, we are hesitant to allocate our marketing budget before this warning is removed, as it could undermine our efforts.
Considering all of the above, we believe that the current requirement is not supportive of legitimate projects like ours and may inadvertently harm the broader industry. We kindly ask if there is a way to resolve this issue, as it would be beneficial for both our project and the ecosystem as a whole.

**Comment by LandRocker** [comment]
We wanted to update you that we've now surpassed 10,000 holders, thanks to a successful campaign we recently ran. With this milestone, our project now fully meets the criteria outlined in your policy. We kindly ask that you review our updated status, as we believe this qualifies us for listing. We appreciate your consideration and look forward to your confirmation.

**Comment by LandRocker** [comment]
We added a new commit and changed twitter URL from https://x.com/ to https://twitter.com/ due to the error in the merge process. Initially the bot required us to use https://x.com/. Please approve
@Cryptocool1

**Comment by cryptomanz1** [comment]
• Is a Smart Contract audit completed? Where can we find this information?

**Comment by LandRocker** [comment]
> • Is a Smart Contract audit completed? Where can we find this information?

Yes, the links were added in this conversation earlier, here are the audit links again:
Certik Audit and KYC:
https://skynet.certik.com/projects/landrocker
Coinsult Audit:
https://github.com/Coinsult/solidity/blob/main/Coinsult_LandRocker_0xfb...B16C_Audit.pdf
Cyberscope Audit:
https://www.cyberscope.io/audits/3-lrt

**Comment by captainlegendboss** [comment]
LandRocker and **ImmutableX** will launch a new campaign in a few days.
we are working hard for mass web2 gaming adoption to web3 gaming

https://www.immutable.com/play/landrocker

**Pull request merged**
