### PR TITLE
ShieldNetwork 

### PR DESCRIPTION
**Pull request by LoFi-Junky**
Add ShieldNet Token logo & Information.

### CODE REVIEW

**Comment by Cryptocool1** [comment]
Info file should be named info.json
Logo file should be named logo.png

Please create new PR, follow doc https://community.trustwallet.com/t/how-to-submit-a-token-logo/3863
You may want to try our new Assets app in beta; go to https://assets.trustwallet.com, log on with Github, enter contract ID, logo and some additional info, and it will create a PR for you.
See https://community.trustwallet.com/t/how-to-submit-a-token-logo-using-assets-app/82957.

**Comment by LoFi-Junky** [comment]
Why would we want to delete it? We are going to wait to surpass the 5000 addresses again since its a re-release. We are at 4,600 address's (https://bscscan.com/token/0xf2e00684457de1a3c87361bc4bfe2de92342306c) we are gonna pay 2BNB and apply for it.

**Comment by LoFi-Junky** [comment]
Can someone please delete this entirely?

**Comment by Cryptocool1** [comment]
> Can someone please delete this entirely?

I closed it

**Pull request closed without merging**
