### PR TITLE
Add Optimism PEPE (BEP20)

### PR DESCRIPTION
**Pull request by OPEPEBSC**
Adding info for BEP20 token 'Optimism PEPE'.

PR created by <a href="https://assets.trustwallet.com">TW Assets Management</a>

### CODE REVIEW

**Comment by OPEPEBSC** [comment]
thank you and waiting for your reply 
thank you

**Comment by Cryptocool1** [comment]
Please come back to us once all criteria are met. Make sure to mention this PR so the fee can be reused

**Comment by OPEPEBSC** [comment]
but there some token got trust wallet logo and they have only 4K holder 
and here is example 

https://bscscan.com/token/0x24086eab82dbdaa4771d0a5d66b0d810458b0e86

**Comment by OPEPEBSC** [comment]
> Please come back to us once all criteria are met. Make sure to mention this PR so the fee can be reused

but there some token got trust wallet logo and they have only 4K holder
and here is example

https://bscscan.com/token/0x24086eab82dbdaa4771d0a5d66b0d810458b0e86

**Comment by OPEPEBSC** [comment]
> As per our policy, there is a minimum requirement of 10,000 holder addresses and 15,000 transactions, in order to filter out scam tokens. See the criteria at : https://developer.trustwallet.com/listing-new-assets/requirements .

but there some token got trust wallet logo and they have only 4K holder
and here is example

https://bscscan.com/token/0x24086eab82dbdaa4771d0a5d66b0d810458b0e86

**Comment by OPEPEBSC** [comment]
@cryptomanz1 @Cryptocool1 
check out this please they was 4k when they got logo on trust wallet 

https://bscscan.com/token/0x24086eab82dbdaa4771d0a5d66b0d810458b0e86

**Comment by OPEPEBSC** [comment]
@cryptomanz1 <https://github.com/cryptomanz1> @Cryptocool1
<https://github.com/Cryptocool1>
check out this please they was 4k when they got logo on trust wallet

https://bscscan.com/token/0x24086eab82dbdaa4771d0a5d66b0d810458b0e86

**Pull request closed without merging**
