### PR TITLE
Please add useless logo and info

### PR DESCRIPTION
**Pull request by epicsideproject**

### CODE REVIEW

**Comment by Cryptocool1** [comment]
Please create new PR, follow doc https://community.trustwallet.com/t/how-to-submit-a-token-logo/3863
You may want to try our Assets app in beta; go to https://assets.trustwallet.com, log on with Github, enter contract ID, logo and some additional info, and it will create a PR for you.
See https://community.trustwallet.com/t/how-to-submit-a-token-logo-using-assets-app/82957.

**Review by andrewMcHale411 — COMMENTED** [review]
161fS90Cz307pM4bowg7o qi8qBJVaQp8T2

**Comment by andrewMcHale411** [comment]
``161fS90Cz307pM4bowg7o qi8qBJVaQp8T2

**Comment by andrewMcHale411** [comment]
How do I track this wallet address 161fS90Cz307pM4bowg7o qi8qBJVaQp8T2

**Pull request closed without merging**
