### PR TITLE
Add CheckDot (BEP20)

### PR DESCRIPTION
**Pull request by jguyet**
Adding info for BEP20 token 'CheckDot'.

PR created by <a href="https://assets.trustwallet.com">TW Assets Management</a>

### CODE REVIEW

**Comment by jguyet** [comment]
Hello, regarding the number of holders needed.
We have the number of transactions requested.
We do not have the number of holder because we are a small project that has never cheated on its number of users.
We are a French project existing since 2021.
Our services serve to protect the funds of decentralized finance users against different risks (smart contracts vulnerabilities, ...) and we provide a free DeFi project analysis service.
We are a small start-up that is well established.
We can provide you with our ID if you ask for it, or even make a small telegram call or discord or google meet to present you our good faith.
We hope that you will take into account our small project which has a great objective to help as many people as possible.
That's why we made this request.
Thank you for reading my message.

**Comment by jguyet** [comment]
Don't hesitate if you have any questions I will be happy to answer them.

**Comment by Cryptocool1** [comment]
As per our policy, brand new tokens are not included, there is a minimum requirement of 10,000 holder addresses and 15,000 transactions, in order to filter out scam tokens.
See the criteria at : https://developer.trustwallet.com/assets/requirements .

**Comment by Cryptocool1** [comment]
Feel free to create new PR once criteria are met. Make sure to mention this PR so the fee can be reused

**Comment by jguyet** [comment]
Capture d’écran 2022-09-17 à 02 26 32
In your documentation you state that this condition is subject to discussion. May we present our good faith. Business papers, personal papers. We are very attentive to your needs.

**Comment by jguyet** [comment]
Our industry has only a few competitors in total. We are in an industry that is not yet very popular, so it is difficult for us to reach such a large number of holders.

**Comment by jguyet** [comment]
Capture d’écran 2022-09-17 à 02 31 40
Regarding the number of transactions we have 45,000 transactions. The use is there.

**Comment by jguyet** [comment]
We are not a new token.
We have been around for 1 year now.

**Comment by jguyet** [comment]
Here is my pro email if you want to get in touch:
jguyet@checkdot.io

**Comment by jguyet** [comment]
I have just contacted TrustWallet support with my personal proof of identity.

**Comment by Cryptocool1** [comment]
• What is the purpose of this token? How will it benefit Trust Wallet users?
 • How is the token being distributed? Are you conducting an airdrop?
 • Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?
 • Is the token listed on a centralized/decentralized exchange?
 • Is a Smart Contract audit completed? Where can we find this information?

**Comment by jguyet** [comment]
- What is the purpose of this token? How will Trust Wallet users benefit?
The purpose of the token is to be used as currency when purchasing insurance on our application, to vote in DAO proposals. Trust Wallet users will be able to access our services and thus insure themselves against various risks of decentralized finance.

- How will the token be distributed? Are you doing an airdrop?
The token was put on public sale in November 2021.
It is currently available for purchase on Pancakeswap and SushiSwap with a liquidity of $120,000.

- Did you sell the tokens in an Initial Coin Offering (ICO) or token presale?
Yes 60% of the tokens were offered for sale in late 2021 from the Unicrypt platform.

- Is the token listed on a centralized/decentralized exchange?
The token is listed on decentralized exchanges Pancakeswap and SushiSwap.

- Has a smart contract audit been performed? Where can we find this information?
Yes, by the German company QuillAudits https://github.com/Quillhash/QuillAudit_Reports/blob/master/Checkdot%20Smart%20Contract%20Audit%20Report%20-%20QuillAudits.pdf

We have also done a KYC at SolidProof https://github.com/solidproof/kyc-certificates/blob/main/KYC_Certificate_Checkdot.png

And a second KYC at FloozTrade https://github.com/flooz-link/flooz-kyc-verification/blob/main/KYC/bsc-0x0cbd6fadcf8096cc9a43d90b45f65826102e3ece.png

**Pull request merged**
