### PR TITLE
BEP20 PAYS

### PR DESCRIPTION
**Pull request by Payslink**
Add BEP20 Payslink Token

### CODE REVIEW

**Comment by Cryptocool1** [comment]
• What is the purpose of this token? How will it benefit Trust Wallet users?
 • How is the token being distributed? Are you conducting an airdrop?
 • Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?
 • Is the token listed on a centralized/decentralized exchange?
 • Is a Smart Contract audit completed? Where can we find this information?

**Comment by Payslink** [comment]
@Cryptocool1 
• What is the purpose of this token? How will it benefit Trust Wallet users?
👉🏿 The original utility token of the PAYSLINK platform. This token is used for payment in the financial, exchange, and transaction ecosystem
+ Token Functions: Payment, holders, discounts on commission fees & Token Stock
+ Advantages of Owning: Profit earned, sharing and earn rewards, Invest in practical projects & buy token at a highly discounted

• How is the token being distributed? Are you conducting an airdrop?
👉🏿 We are distributing for the Seed Round, Private Sale and the current Airdrop event is happening.

• Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?
👉🏿 We do three sales: Seed Round, Private Sale, Public Sale.

• Is the token listed on a centralized/decentralized exchange?
👉🏿 The token has not been traded on any platform, We are contacting and planning to list exchanges in June 2023

• Is a Smart Contract audit completed? Where can we find this information?
👉🏿 We are in the process of contacting audit units. Information will be updated as soon as possible

**Comment by Cryptocool1** [comment]
We require smart contract audit. Feel free to create new PR once audit is completed.

**Comment by Payslink** [comment]
I got it, we are speeding up audit progress.

**Comment by Payslink** [comment]
@Cryptocool1 please check our new PR https://github.com/trustwallet/assets/pull/25413.
It includes audit report.

**Pull request closed without merging**
