### PR TITLE
Add logo for infinity project

### PR DESCRIPTION
**Pull request by w3bin**
Add logo for infinity project

### CODE REVIEW

**Comment by w3bin** [comment]
Our token have paid on this pull request: 
https://github.com/trustwallet/assets/pull/21670
Please help me to check 
@cryptomanz1

**Comment by Cryptocool1** [comment]
You paid not for this contract address

**Comment by w3bin** [comment]
> You paid not for this contract address

Yes, we change the contract to add liquidity, and you alse told me that my paid can reused. Please help me to update for new contract. Thank you so much

**Comment by Cryptocool1** [comment]
Yes, sure we can reuse payment for the same contract, but this one is totally another token

**Comment by w3bin** [comment]
> Yes, sure we can reuse payment for the same contract, but this one is totally another token

Sorry, I don't see any rule about it. Our token is version 2 of the old token. I think there is no need to be too rigid in this case. 
If you need any proof, please let me know. Thank you

**Comment by Cryptocool1** [comment]
The rule is simple, we reuse payment only for the same token. I can reopen old PR, and reuse the payment there.

**Comment by w3bin** [comment]
> The rule is simple, we can reuse payment only for the same token. I can reopen old PR, and reuse the payment there.

https://coinmarketcap.com/vi/currencies/w3b-infinity/
Cmc also update new token address for us. Please be flexible in this case.

**Comment by w3bin** [comment]
Please be flexible to help us in this case. Now v1 has been completely replaced by v2, and users have also swapped to v2. We've also tried to accommodate your requests as best we can.

**Comment by w3bin** [comment]
Please be flexible to help us in this case. @cryptomanz1

**Comment by Cryptocool1** [comment]
We can only reopen your old PR and use payment there

**Comment by w3bin** [comment]
> We can only reopen your old PR and use payment there

Ok, Please open old PR. Thanks

**Pull request closed without merging**
