### PR TITLE
Add ANDY (ERC20)

### PR DESCRIPTION
**Pull request by boysclubandy**
Adding info for ERC20 token 'ANDY'.

PR created by <a href="https://assets.trustwallet.com">TW Assets Management</a>

### CODE REVIEW

**Comment by boysclubandy** [comment]
Hello, 
Here is our contract audit too FYI. 
https://github.com/boysclubandy/Audit

**Comment by boysclubandy** [comment]
payment sent. 
> bnb158fgd782we4tz9vwwcj9pmmxvxhl6z46lfm7c8

**Comment by boysclubandy** [comment]
> payment sent.
> 
> > bnb158fgd782we4tz9vwwcj9pmmxvxhl6z46lfm7c8
IMG_6816

**Comment by boysclubandy** [comment]
> > payment sent.
> > > bnb158fgd782we4tz9vwwcj9pmmxvxhl6z46lfm7c8
> > > IMG_6816
—-
Hello
 @Cryptocool1 
Payment sent but the not is not detecting it

**Comment by cryptomanz1** [comment]
Can you sent txid here?

**Comment by boysclubandy** [comment]
> Can you sent txid here

Any update sir? please.
Here is the TXID again.
https://explorer.bnbchain.org/tx/54C1B9CF30A8B6020F266DB13B9985775A7CBBB6398254D1C43DCFE91A560B48

**Comment by cryptomanz1** [comment]
• What is the purpose of this token? How will it benefit Trust Wallet users?
 • How is the token being distributed? Are you conducting an airdrop?
 • Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?
 • Is the token listed on a centralized/decentralized exchange?
 • Is a Smart Contract audit completed? Where can we find this information?

**Comment by cryptomanz1** [comment]
We require smart contract audit from reputable companies. Please see https://developer.trustwallet.com/listing-new-assets/requirements

**Comment by boysclubandy** [comment]
> Hello, Here is our contract audit too FYI. https://github.com/boysclubandy/Audit

Hello Sir, 


Hello,
Here is our contract audit too FYI.

https://github.com/boysclubandy/Audit
https://github.com/solidproof/projects/tree/main/2024/Andy

**Comment by boysclubandy** [comment]
> • What is the purpose of this token? How will it benefit Trust Wallet users? • How is the token being distributed? Are you conducting an airdrop? • Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale? • Is the token listed on a centralized/decentralized exchange?


It's a meme token with a significate support by twitter influencers and wide community. 
ANDY tokens can be traded on decentralized exchanges and centralized crypto exchanges.
The most popular exchange to buy and trade ANDY ETH is [Uniswap V2 (Ethereum)] where the most active trading pair ANDY/WETH has a trading volume of $6,016,582 in the last 24 hours.
Other popular options include Bilaxy, MEXC, Poloniex, CoinW, and more. 

The token distributed fairly 100% to the holders and controlled by community, with no ICO, it was fair launch to everyone. 

Trust Wallet will bring better value to the holders to see their ANDY holdings logo and value and tracking the price. 

your support is highly appreciated.

**Comment by boysclubandy** [comment]
@cryptomanz1 
Hello Sir, Any update please. ?

**Comment by boysclubandy** [comment]
@cryptomanz1 
Hello, 
could you please update us sir?

**Comment by boysclubandy** [comment]
@cryptomanz1 
Hello sir,

Could you please update us? 
All checks completed, payment done. 

it has been 4 days from last response. 
thank you

**Comment by boysclubandy** [comment]
@cryptomanz1 
Hello!
sir, this is not the correct way to ignore us, at least you should respond. 
thank you.

**Comment by boysclubandy** [comment]
@cryptomanz1 
We have all required statues to be updated. 
- multi millions volume daily 
- more than 10.5k holders with more than 122k TXns
- Official Audit from vey known provider. 
- listed on + 7 CEXs
- listed on CMC/CG 

why all this delay in response sir !

**Comment by boysclubandy** [comment]
@cryptomanz1 @Cryptocool1 
Hello, 
We have an issue..

The price data is not available for ANDY on Trust Wallet, and the market info not available too. 
We waiting for this to be updated for more than 2 weeks now ,

Would you please help us fix this ? 
Thank you

**Comment by Cryptocool1** [comment]
Hello, we will enable the pricing data soon

**Comment by Cryptocool1** [comment]
You should see the pricing data for your token now

**Comment by boysclubandy** [comment]
> You should see the pricing data for your token now

Yes, it's working.
Many thanks for your support.

**Pull request merged**
