### PR TITLE
Add Sponge (ERC20)

### PR DESCRIPTION
**Pull request by SpongeDeveloper**
Adding info for ERC20 token 'Sponge'.

PR created by <a href="https://assets.trustwallet.com">TW Assets Management</a>

### CODE REVIEW

**Comment by Cryptocool1** [comment]
Hello, how did you get 10k holders in less than 1 week?

**Comment by SpongeDeveloper** [comment]
hi there

We've really blown up, and have some great marketing behind us. We are
waiting on adding a few things to the website before we pay - roadmap and
audit mainly...do we need this or are you willing to list us once we pay
the listing fee?

thanks

**Comment by SpongeDeveloper** [comment]
we have really good marketing - we've appeared in many publications and
have partnerships with communities and influencers

https://cryptonews.com/news/sponge-token-price-blasts-up-7x-5-days-next-low-cap-gem-get-listed-binance.htm
https://www.analyticsinsight.net/this-new-meme-token-sponge-hits-trending-top-10-on-coinmarketcap-buy-now-before-impending-price-pump/
https://newsdirect.com/news/new-meme-coin-sponge-to-list-on-mexc-exchange-after-3-000-pump-415309007

you can see all the on chain data below

https://dune.com/jt203/sponge
https://www.dextools.io/app/en/ether/pair-explorer/0xf935f557e06a7d040dea4691f90c9a755301818b

**Comment by Cryptocool1** [comment]
• What is the purpose of this token? How will it benefit Trust Wallet users?
 • How is the token being distributed? Are you conducting an airdrop?
 • Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?
 • Is the token listed on a centralized/decentralized exchange?
 • Is a Smart Contract audit completed? Where can we find this information?

**Comment by SpongeDeveloper** [comment]
we are just waiting on audit then will submit details - the rest we have

**Comment by Cryptocool1** [comment]
Ok, however I asked you 8 questions

**Comment by SpongeDeveloper** [comment]
yes we were just waiting on the audit to be completed

*• What is the purpose of this token? How will it benefit Trust Wallet
users?*

this is meme coin. it's all about community and having fun. our roadmap is
now on our site - https://sponge.vip/

*• How is the token being distributed? Are you conducting an airdrop?*

61%DEX liquidity
29% community
10% CEX liquidity

there will be an upcoming airdrop using the community fund

*• Did you sold the tokens at an Initial Coin Offering (ICO) or a token
presale?*

no ICO or presale. was launched on uniswap

*• Is the token listed on a centralized/decentralized exchange?*

full list of exchanges:

Uniswap
Gate
MEXC
Bitget
Lbank
poloniex
btcex
coinw

*• Is a Smart Contract audit completed? Where can we find this information?*

audit is attached to this email

please re-open, and confirm you have all the information you need for the
listing, and we can then pay the fee

thanks

**Comment by SpongeDeveloper** [comment]
please can you reopen this ticket?  #24964
<https://github.com/trustwallet/assets/pull/24964>.

we have replied with the info and are ready to make payment

thanks

**Pull request closed without merging**
