### PR TITLE
remove pdai

### PR DESCRIPTION
**Pull request by bitbd83**

### CODE REVIEW

**Comment by bitbd83** [comment]
TX Hash:  13E9C089F05215A697C3E452C6ED3EFB2A2C1BF7EAE9E2138FBE3FA6FFCD7257

**Comment by catenocrypt** [comment]
Why does the title say 'remove'?

**Comment by catenocrypt** [comment]
As per our policy, brand new tokens are not included, there is a minimum requirement of 100 holder addresses and 500 transactions, in order to filter out scam tokens.
See https://community.trustwallet.com/t/how-to-submit-a-token-logo/3863#how-to-get-approved
For both tokens usage is very low.
PrimeDAI: 6 holder addresses, 13 txs. https://etherscan.io/token/0x9043d4d51C9d2e31e3F169de4551E416970c27Ef
Omega Protocol: 23/135.  https://etherscan.io/token/0xF4c17Bc4979c1dc7b4CA50115358Dec58C67fD9d

Putting on hold for now.

**Comment by zachzwei** [comment]
Please provide more details about this project. We will be closing this for now.
You can reopen when you have met the requirements mentioned here:
https://community.trustwallet.com/t/how-to-submit-a-token-logo/3863#how-to-get-approved

You can follow this format when adding an info.json file:

``` {
   "name":"Bitcoin",
   "website":"https://bitcoin.org",
   "source_code":"https://github.com/bitcoin",
   "white_paper":"https://bitcoin.org/bitcoin.pdf",
   "short_description":"Bitcoin is a cryptocurrency and worldwide payment system.",
   "explorer":"https://blockchain.info",
   "research":"https://research.binance.com/en/projects/bitcoin"
}

**Comment by bitbd83** [comment]
Ok thank you. I will provide all info in json format.

**Pull request closed without merging**
