### PR TITLE
Add Feeder Finance logo and info

### PR DESCRIPTION
**Pull request by FeederFinanceJimmy**

### CODE REVIEW

**Comment by Cryptocool1** [comment]
Hello, what is the purpose of this token?

**Comment by Cryptocool1** [comment]
Hello, can you add links to your PR?
https://developer.trustwallet.com/add_new_asset#info-json-contents

**Comment by FeederFinanceJimmy** [comment]
@Cryptocool1 We've added all the related links to info.json

The purpose of the FEED token is to be used as part of platform services fees. The holders also benefits from earning fees collected from our platform services and products as well as voting rights.

**Comment by Cryptocool1** [comment]
'https://discord.gg/CBCrxVbkmv' must start with 'https://discord.com/'.

**Comment by FeederFinanceJimmy** [comment]
@Cryptocool1 We've edited the discord URL.

**Comment by Cryptocool1** [comment]
https://www.youtube.com/channel/UC7M0nZAc0IqmY3VZ8ZcettA' must start with 'https://youtube.com/

**Comment by Cryptocool1** [comment]
you need to delete www from all links.
thanks

**Comment by FeederFinanceJimmy** [comment]
@Cryptocool1 All www in links are removed.

**Comment by Cryptocool1** [comment]
still some correction needed:
 'Links field 'coingecko': 'https://blog.feeder.finance' must start with 'https://coingecko.com/'

**Comment by FeederFinanceJimmy** [comment]
@Cryptocool1 Fixed. It is supposed to be label as blog.

**Pull request merged**
