### PR TITLE
Adding Paid Network BSC info and logo

### PR DESCRIPTION
**Pull request by rubengue**
Adding PAID BSC to Trustwallet

### CODE REVIEW

**Comment by Cryptocool1** [comment]
Hello, 
• What is the purpose of this token? How will it benefit Trust Wallet users?
 • How is the token being distributed? Are you conducting an airdrop?
 • Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?
 • Is the token listed on a centralized/decentralized exchange?
 • Is a Smart Contract audit completed? Where can we find this information?

**Comment by rubengue** [comment]
Hi guys.
• What is the purpose of this token? How will it benefit Trust Wallet users?
Paid Network BSC allow Trust Wallet users to participate in Apollox IDO (
https://apollox.paidnetwork.com), also participate in the future
paidnetwork Dapp for Smart Agreements.

• How is the token being distributed? Are you conducting an airdrop?
No, the token should be adquiere from pancakeswap, there is no airdrop

• Did you sold the tokens at an Initial Coin Offering (ICO) or a token
presale?
No, the BSC Paidnetwork token not have ICO or presale. The Paid Token in
ether Chain had a Token presale

• Is the token listed on a centralized/decentralized exchange?
Is listed on PancakeSwap

• Is a Smart Contract audit completed? Where can we find this information?
 The smart Contract Audit is complete but that token version is still not
deploy, but soon. I will attach the token audit

**Comment by Cryptocool1** [comment]
awaiting for smart contract audit. on hold for now

**Comment by rubengue** [comment]
The smart contract audit is already done, I attach to you guys xD

**Comment by Cryptocool1** [comment]
> The smart contract audit is already done, I attach to you guys xD
> […](#)

can you send it in pdf?

**Comment by rubengue** [comment]
Hi. Is attached as a pdf file

**Comment by cryptomanz** [comment]
Screenshot 2021-09-26 at 01 00 03

**Comment by rubengue** [comment]
[image: Screen Shot 2021-09-25 at 5.07.49 PM.png]
how extrange. Well I sent this link where you can download the file. Thanks

https://drive.google.com/file/d/1ibGmCSS0IqJlioRW2p3T_ps2Hrq3rDqc/view?usp=sharing

**Comment by rubengue** [comment]
Thanks very much!!!! 🙏🙏🙏🙏

**Pull request merged**
