### PR TITLE
add Mars Ecosystem assets info

### PR DESCRIPTION
**Pull request by etedwardelric**
Add Mars Ecosystem DAPP
Add XMS assest info
Add USDm assest info
Add BEP20 XMS
Add BEP20 USDm

https://coinmarketcap.com/currencies/mars-ecosystem-governance-token/
https://bscscan.com/token/0x7859b01bbf675d67da8cd128a50d155cd881b576
https://pancakeswap.finance/info/token/0x7859B01BbF675d67Da8cD128a50D155cd881B576

We had contact your team with email for suggestion, put the dapp, token info, and the assets in one PR.

### CODE REVIEW

**Comment by etedwardelric** [comment]
We have consulted your team via email and we were told that we can put dapp,tokeninfo and asset into one PR for submission. Is there any problem now?  And how should we do it?

**Comment by Cryptocool1** [comment]
Hello, who did you talk to?

**Comment by etedwardelric** [comment]
> Hello, who did you talk to?

I sent my question to this email address：support@trustwallet.com,  and got a reply that I could submit DAPP,tokeninfo,and asset(tokenlist.json) in one PR. Is this not okay ?

**Comment by Cryptocool1** [comment]
Please come back to us when all criteria are met.

**Pull request closed without merging**
