### PR TITLE
feat(bitsong): add bitsong info

### PR DESCRIPTION
**Pull request by angelorc**

### CODE REVIEW

**Comment by angelorc** [comment]
Hello everyone, are there any updates on this pull request?

**Comment by angelorc** [comment]
Hello everyone, are there any updates on this pull request?

**Comment by Milerius** [comment]
We do not have support for Bitsong in wallet core, this chain can't be added for now

**Comment by angelorc** [comment]
Hello, can you explain why the pr isn't merged? We payed the fee, we sent the correct info but then the pr was closed. Is there any reason why bitsong can't be integrated?

**Pull request closed without merging**
