### PR TITLE
Add Eifi Logo and info

### PR DESCRIPTION
**Pull request by eififinance**
Kindly add Eifi Logo and info in Trust wallet

### CODE REVIEW

**Comment by cryptomanz** [comment]
Hello,
- Awaiting for smart contract adit.

**Comment by Cryptocool1** [comment]
hello,
• What is the purpose of this token? How will it benefit Trust Wallet users?
 • How is the token being distributed? Are you conducting an airdrop?
 • Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?
 • Is the token listed on a centralized/decentralized exchange?
 • Is a Smart Contract audit completed? Where can we find this information?

**Comment by Cryptocool1** [comment]
still no answer,
please create new PR when you'll be ready to chat
make sure to mention this PR

**Comment by eififinance** [comment]
I have created another PR for this. But It is asking for fee again. Kindly look into this.

https://github.com/trustwallet/assets/pull/12162

**Comment by eififinance** [comment]
> still no answer,
> please create new PR when you'll be ready to chat
> make sure to mention this PR

I have created another PR https://github.com/trustwallet/assets/pull/12162 with the answers. Please look into this because it is asking for a fee again.

**Pull request closed without merging**
