### PR TITLE
Wish coin logo uplode 

### PR DESCRIPTION
**Pull request by gotit800**
Sir Plasse add  my logo trust wallet
My token name : wishcoin
Symbol: wis
Decimals: 18 
Total supply : 1000000000
Contract address:  0xFA12040497bC7B6077Ea125Bad27dAA8b74E7eDC
0xFA12040497bC7B6077Ea125Bad27dAA8b74E7eDC logo

### CODE REVIEW

**Comment by gotit800** [comment]
https://explorer.binance.org/tx/FBA5B5217ED8D552024B908638601FFE2A625AD74F06F712CA2FEA7973F31FBE

**Comment by gotit800** [comment]
Sir Plasse add my logo

**Comment by gotit800** [comment]
https://explorer.binance.org/tx/FBA5B5217ED8D552024B908638601FFE2A625AD74F06F712CA2FEA7973F31FBE

**Comment by gotit800** [comment]
https://github.com/trustwallet/assets/pull/2838
Hellow sir Plasse add my erc20 token logo
I send 2000 twt token
https://explorer.binance.org/tx/FBA5B5217ED8D552024B908638601FFE2A625AD74F06F712CA2FEA7973F31FBE

**Comment by gotit800** [comment]
https://github.com/trustwallet/assets/pull/2838

**Comment by gotit800** [comment]
Sir payment send Plasse add my token logo
 https://explorer.binance.org/tx/FBA5B5217ED8D552024B908638601FFE2A625AD74F06F712CA2FEA7973F31FBE

**Comment by gotit800** [comment]
My token logo Plasse add sir  
0xFA12040497bC7B6077Ea125Bad27dAA8b74E7eDC logo

**Comment by catenocrypt** [comment]
I have renamed and scaled image file to be correct.

**Comment by gotit800** [comment]
Thanks You sir

**Comment by gotit800** [comment]
How long will it take to show the logo in Sir Trust Wallet?

**Comment by benlolbenlol178** [comment]
@catenocrypt @zachzwei 
I have been trying to add logo, how do I do it? https://github.com/benlolbenlol178/assets/pull/1

**Comment by gotit800** [comment]
Yes sir i can't add logo you add logo i made payment

**Comment by gotit800** [comment]
No sir  benlolbenlol178#1 not my token
My token name: wishcoin
https://github.com/trustwallet/assets/pull/2838

**Comment by gotit800** [comment]
Thanks you sir

**Comment by benlolbenlol178** [comment]
@catenocrypt Can you check mine? I have paid 1 BNB. https://github.com/benlolbenlol178/assets/pull/3

**Comment by catenocrypt** [comment]
> @catenocrypt Can you check mine? I have paid 1 BNB. [benlolbenlol178#3](https://github.com/benlolbenlol178/assets/pull/3)

You created a pull request with your repo as target, instead of the main asset repo!  That's why we have not seen it.  Open a pull request against the main assets/master branch.  You will not have to pay again, just mention https://github.com/benlolbenlol178/assets/pull/3 .

**Pull request merged**
