### PR TITLE
Add Marshall Rogan Inu (ERC20)

### PR DESCRIPTION
**Pull request by forceofnaturetok**
Adding info for ERC20 token 'Marshall Rogan Inu'.

PR created by <a href="https://assets.trustwallet.com">TW Assets Management</a>

### CODE REVIEW

**Comment by forceofnaturetok** [comment]
Hi!

Please check PR 20636, there was a change to be done as I submitted old PR on BEP20 when it had to be done in ERC20.

Payment was already done
________________________________

**Comment by forceofnaturetok** [comment]
@Cryptocool1 

Thanks for your help!

**Comment by Cryptocool1** [comment]
• Is a Smart Contract audit completed? Where can we find this information?

**Comment by forceofnaturetok** [comment]
Yes! We have been audited by Solidity

https://solidity.finance/audits/MarshallRoganInu/

and we are being audited by Certik right now.
https://www.certik.com/projects/marshall-inu
[https://www.certik.com/api/card/marshall-inu.jpg]<https://www.certik.com/projects/marshall-inu>
Marshall Inu - CertiK Security Leaderboard<https://www.certik.com/projects/marshall-inu>
Stay up to date with the latest security insights on Marshall Inu : Smart Contract Audit, Skynet Security Scores, Badges, CertiKShield and many more security-focused statistics.
www.certik.com

________________________________

**Pull request merged**
