### PR TITLE
Add GOLD FINCH COIN (BEP20)

### PR DESCRIPTION
**Pull request by GOLDFINCH18**
Adding info for BEP20 token 'GOLD FINCH COIN'.

PR created by <a href="https://assets.trustwallet.com">TW Assets Management</a>

### CODE REVIEW

**Comment by GOLDFINCH18** [comment]
HELOO TEAM

NEED GOLD FINCH COIN ADD ON TRUST WALLET PLZ

**Comment by GOLDFINCH18** [comment]
GOLD FINCH COIN AUDIT REPORT IS DONE..
AUDIT REPORT LINK:

https://github.com/ContractWolf/smart-contract-audits/blob/main/ContractWolf_Audit_GoldFinch.pdf

**Comment by GOLDFINCH18** [comment]
What is the purpose of this token? How will it benefit Trust Wallet users?

Gold Finch is a top edge technology infrastructure to deliver more than you can expect. Gold Finch has projects related to Decentralized Exchange, Aggregated Decentralized Multi-coin Wallet, NFT Market place, a HUB for Content Contributors / creators & a Biggest Global Utility Platform under its umbrella.

• How is the token being distributed? Are you conducting an airdrop?
YES
• Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?
YES COMING SOON
• Is the token listed on a centralized/decentralized exchange?
YES 2 EXCHANGE LISTED

COINSBIT EXCHANAGE
https://coinsbit.io/trade_classic/GFCC_USDT

VINDAX EXCHANGE

https://vindax.com/exchange-base.html?symbol=GFCC_USDT

• Is a Smart Contract audit completed? Where can we find this information?

GOLD FINCH COIN AUDIT REPORT IS DONE..
AUDIT REPORT LINK:

https://github.com/ContractWolf/smart-contract-audits/blob/main/ContractWolf_Audit_GoldFinch.pdf

**Comment by Cryptocool1** [comment]
hello, we accept audit only from reputable companies (Certik, Techrate, Dessert Finance, Hacken)

**Comment by GOLDFINCH18** [comment]
GOLD FINCH COIN IS ALL REDYY LISTED IN

TRUST WALLET NEED JUST 

CHANGE LOGO

CHANGE SMART CONTRACT


GOLD FINCH IS ALL REDYY LIVE IN TRUST WALLET APP

**Comment by Cryptocool1** [comment]
your token is not listed

**Comment by Cryptocool1** [comment]
what is your old contract address?

**Comment by Cryptocool1** [comment]
Are you listed on CoinMarketCap?

**Comment by GOLDFINCH18** [comment]
GOLD FINCH OLD TOKEN SMART CONTRACT ADDRES

0xe714A9C04f5925a3fe89E4F6e21437BF0E0c774d

**Comment by Cryptocool1** [comment]
> 0xe714A9C04f5925a3fe89E4F6e21437BF0E0c774d

Please send me an official announcement about migration

**Comment by Cryptocool1** [comment]
> GOLD FINCH OLD TOKEN SMART CONTRACT ADDRES
> 
> 0xe714A9C04f5925a3fe89E4F6e21437BF0E0c774d
> 
> COIN MARKET LISTING ON PROCESS
> 
> COIN CODEX WEBSITE LISTED DONE
> 
> https://coincodex.com/crypto/gold-finch/

We require CoinMarketCap listing
see the requirement here: https://developer.trustwallet.com/assets/requirements

**Comment by GOLDFINCH18** [comment]
AHH..


JUST 10 MINUTE I M NOW GIVE YOU ANOUSMENT LINK

**Comment by GOLDFINCH18** [comment]
COIN MARKET CAP LISTING REKVEST SEND 14 DAYS AGO STILL NOT UOPDATE BY CMC 

Your request (465857) 

THIS IS GOLD FINCH COIN LISTING APPLICATION SUBMITED TICKE NO

**Comment by GOLDFINCH18** [comment]
GOLD FINCH COIN 
OFFICIAL ANOUSMENT FOR

TWITER:
https://twitter.com/GoldFinchOffic/status/1527298074519162881

FACEBOOK:
https://www.facebook.com/GoldFinchOffic/posts/127103453303417

LINKDINE:
https://www.linkedin.com/feed/update/urn:li:activity:6933063573355069440

PLZ CO-OPRATE

THANX

**Comment by GOLDFINCH18** [comment]
> > 0xe714A9C04f5925a3fe89E4F6e21437BF0E0c774d
> 
> Please send me an official announcement about migration

https://twitter.com/GoldFinchOffic/status/1527298074519162881


https://www.facebook.com/GoldFinchOffic/posts/127103453303417


https://www.linkedin.com/feed/update/urn:li:activity:6933063573355069440

**Comment by GOLDFINCH18** [comment]
HELLO TEAM 

I M WAITING FOR UR RESPONCE

WAITING UR CO -OPRATE 

THANX

TEAM GFCC

**Comment by cryptomanz** [comment]
We require CoinMarketCap listing. On hold for now.

**Comment by GOLDFINCH18** [comment]
> COIN MARKET CAP LISTING REKVEST SEND 14 DAYS AGO STILL NOT UOPDATE BY CMC
> 
> Your request (465857)
> 
> THIS IS GOLD FINCH COIN LISTING APPLICATION SUBMITED TICKE NO:465857

**Comment by Cryptocool1** [comment]
Please come back to us once all criteria are met, make sure to mention this PR so the fee can be reused

**Pull request closed without merging**
