### PR TITLE
Add Tether USDT  (BEP20)

### PR DESCRIPTION
**Pull request by Suibansos**
Adding info for BEP20 token 'Tether USDT '.

PR created by <a href="https://assets.trustwallet.com">TW Assets Management</a>

### CODE REVIEW

**Comment by Suibansos** [comment]
I already pay with 500 TWT
This is my hash
: 0x5229eeca9591116c4e95c02d34a515a5054107888a35477a9e9f9cf634baead4


[image: image.png]

**Comment by Suibansos** [comment]
Hi please tell me how long will it take for me to get update for our
project after i complete payment of 500 twt

Pada Rab, 4 Des 2024 16.35, Sui Bansos ***@***.***> menulis:

> I already pay with 500 TWT
> This is my hash
> : 0x5229eeca9591116c4e95c02d34a515a5054107888a35477a9e9f9cf634baead4
>
>
> [image: image.png]
>
> On Wed, Dec 4, 2024 at 4:29 PM merge-fee-bot[bot] <

**Comment by Suibansos** [comment]
It's been more than 12 hours since I completed the payment of 500 TWT fee
until now there has been no reply regarding the update info about my token,
how long will it take me to get an update about my token project?

**Comment by Cryptocool1** [comment]
After careful review of your submission, it looks like this token is just a copy of an existing project. Plagiarism will not be tolerated. The request will be closed until further notice.

To know more about the token approval guidelines, please check this article: [How to Get Submit Token Logo](https://developer.trustwallet.com/listing-new-assets/requirements).

Feel free to re-open pull request if you are able to provide tangible proof of the legitimacy of the project.

**Pull request closed without merging**
