### PR TITLE
Add SymBULL (BEP20)

### PR DESCRIPTION
**Pull request by SolidityDevTech**
Adding info for BEP20 token 'SymBULL'.

PR created by <a href="https://assets.trustwallet.com">TW Assets Management</a>

### CODE REVIEW

**Comment by tklindt** [comment]
@Cryptocool1 @cryptomanz 
I would like to kindly request an exception to the 25,000 holders minimum. We are DevTeamSix and have several successful crypto projects and have worked hard to get above the 5,000 holder requirement and just discovered that the limit was raised. We are more than happy to pay the fee but would like to not pay it only to be denied if possible. Our other tokens include MiniDOGE and CreamPYE as well as some highly anticipated tokens launching in the coming future. We are building an ecosystem and pride ourselves with being accessible and known to all people in crypto. Thank you so much for your consideration.

**Comment by tklindt** [comment]
- What is the purpose of this token? How will it benefit Trust Wallet users?

> - Purpose is to reward holders through 8% BUSD rewards from buys and sells, we will cross $1 million dollars in BUSD 
rewards today. We are developing BullSWAP which is a BSC DEX based off of the  successful ShibaSwap with Staking rewards in Ride token. We have ambitious plans for this token. This token is also backed by DevTeamSix which is becoming a known name in Crypto.

- How is the token being distributed? Are you conducting an airdrop?

> - Token was initially distributed through Presale followed by launch on PancakeSwap, no Airdrop.

- Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?

> - Yes, Presale was on 11/1 at PinkSale and sold out in 6 seconds (not exagerating)

- Is the token listed on a centralized/decentralized exchange?

> - Token is listed on PancakeSwap, we are discussing with other exchanges as well as developing a DEX

- Is a Smart Contract audit completed? Where can we find this information?

> - Yes, Audited by Solidity.finance [found here](https://solidity.finance/audits/SymBULL/)

**Comment by Cryptocool1** [comment]
are you the owner of "CreamPYE" token?

**Comment by tklindt** [comment]
> are you the owner of "CreamPYE" token?

Yes, I am one of the Devs with DevTeamSIx and we are the owners of "CreamPYE".  However, I am not sure how that token got added into this Pull Request as we are requesting a merge of SymBULL Token only. I think that it was lingering from my initial submission of CreamPYE back in April. Thank you! Tommy

**Comment by Cryptocool1** [comment]
try to create new PR without CreamPYE token files.
thank you

**Pull request closed without merging**
