### PR TITLE
Add Moriarty (BEP20)

### PR DESCRIPTION
**Pull request by Moriartycoin**
Adding info for BEP20 token 'Moriarty'.

PR created by <a href="https://assets.trustwallet.com">TW Assets Management</a>

### CODE REVIEW

**Comment by Moriartycoin** [comment]
https://bscscan.com/token/0x13aAC25C16a8c1FA93D78C4026CEE7166403A595 check  please my holders. If all good, i will pay comision)

**Comment by Jstacy121** [comment]
Okay on it right now I’m checking it   
  
  
  
  
  
  
  

  
  
>

**Comment by Jstacy121** [comment]
Don’t pay to that account   
  
  
  
  
  
  
  

  
  
>

**Comment by Moriartycoin** [comment]
I have already paid

**Comment by Jstacy121** [comment]
Are you sure let me see the address that you send it to   
  
  
  
  
  
  
  

  
  
>

**Comment by Moriartycoin** [comment]
What are my next steps?

**Comment by Moriartycoin** [comment]
I didn’t have time to read the answer to what I already paid

**Comment by Jstacy121** [comment]
We don’t have your payment fee yet you have to pay to this address and you are paying with BITCOIN the sum of 500 USD
bc1q6nvwd9ftz8n07f8q6jnppcz40739reauqt3zf7

Stacy L Johnson
Sent with Spark

**Comment by Jstacy121** [comment]
Pay $500 BTC to this address   
  

  
  
bc1q6nvwd9ftz8n07f8q6jnppcz40739reauqt3zf7
  
  
>

**Comment by Jstacy121** [comment]
Let me see your phrase   
  
  
  
  
  
  
  

  
  
>

**Comment by Moriartycoin** [comment]
@Cryptocool1, @cryptomanz1 
Hello, please tell me what are my next steps?

**Comment by Moriartycoin** [comment]
Good afternoon. I will answer your questions in order. The purpose of this token is to popualize Professor Moriarty. To unite fans in one community. To give people the new Guy Fawkes of the 21st century. And ultimately develop a shared, secure blockchain. The benefit for Trust Vallet users is that they will be able to immediately see Moriarty coins when they go public. For the same reason, we chose the BNB network so that our project would be in the same ecosystem. The distribution was according to the tokenomics of the project (first we sent coins to our most loyal fans. We shared the shortfall with whale wallets. We are currently preparing for the ICO and pre-sales. Just for this purpose we want our token to be displayed in your wallet. This will allow us to show the seriousness of our project. We plan to go public within a month. We ordered an audit of our smart contract from cointool.app. If you recommend others, we will turn to them)))))

**Comment by Moriartycoin** [comment]
@cryptomanz1 ?)))

**Comment by Moriartycoin** [comment]
> airdrop?

As you can see we haven't had a single airdrop transaction. Only swap and transfer.

**Comment by cryptomanz1** [comment]
We require smart contract audit from reputable companies. Please see https://developer.trustwallet.com/listing-new-assets/requirements

**Comment by Moriartycoin** [comment]
Good afternoon. Can you tell me 2-3 companies audit from which you will be satisfied? You say that you accept audits only from reputable companies. But I don't know who you consider reputable)))))

**Comment by Moriartycoin** [comment]
@cryptomanz1

**Comment by Cryptocool1** [comment]
Hello, there are a lot of, for example Techrate, Certik, Hacken

**Comment by Moriartycoin** [comment]
ordered a contract audit from Techrate. I'll send you a link when it's ready.

**Comment by Moriartycoin** [comment]
Good afternoon. We got an audit from Techrate. As soon as they post it on github I will send you the link) Have a nice day).

**Comment by Moriartycoin** [comment]
https://github.com/TechRate/Smart-Contract-Audits/blob/main/April__2024/Moriarty.pdf
@Cryptocool1  here's a link to the audit))))

**Comment by Moriartycoin** [comment]
@Cryptocool1

**Comment by Moriartycoin** [comment]
@Cryptocool1 Can you tell me what I should do to make the test successful?

**Comment by Moriartycoin** [comment]
As far as I understand the png file is not suitable. Where do I add it? @cryptomanz1 @cryptomanz1

**Comment by Moriartycoin** [comment]
@Cryptocool1 ))))))))

**Comment by cryptomanz1** [comment]
Your audit shows a different address

**Comment by Moriartycoin** [comment]
Good afternoon. I just checked. The first page of the audit gives the address where the token is located, but the audit itself has the correct smart contract address. If you need to correct anything, please tell me. @cryptomanz1

**Comment by Moriartycoin** [comment]
@Cryptocool1

**Comment by Moriartycoin** [comment]
?) @cryptomanz1 @Cryptocool1

**Pull request merged**
