### PR TITLE
Migration from 0x0fbc08905c1d683Cf7530bb2a70Bb0BDE231E5B9 to 0xa73dF9…

### PR DESCRIPTION
**Pull request by YMakkoyev**
…480e9408908c828be2e1A7345855501508

As stated in email sent from babydogezillabsc@gmail.com, an update is needed to align trust wallet prices due supply change.

Folder, id and explorer address have been updated.

### CODE REVIEW

**Comment by YMakkoyev** [comment]
Waiting for further instructions

**Comment by Cryptocool1** [comment]
#22336

**Comment by YMakkoyev** [comment]
As migration occurred, we updated coinmarketcap/coingeko as well, resulting in the same URL in both v1 and v2. We cut off 6 zeros, so 1 dollar v1 version will result in 7 million dollars

Screenshot_2022-09-07-19-44-24-165_com wallet crypto trustapp

**Comment by cryptomanz1** [comment]
Dogezilla v1 is abandoned

**Comment by YMakkoyev** [comment]
Yeah there are two versions, and both have same price calculation. Somehow people from v1 seeing the price of v2 that have been upsated on coinmarketcap/coingeko.

So people who buy v1 token see on trust wallet 000000 zeros more as v2 supply Is 6 zeros less.

**Comment by Michal159** [comment]
please fix it asap, its a huge problem, 47 000 holders spamming our chats/twitter/commenting CMC and fudding about this glitch
we need to delete the price from V1 contract or just fix it to normal 

I paid 2x 700 TWT, I hope you will help me to fix this ;) 

thank you

CEO of BabyDogeZilla

**Comment by Michal159** [comment]
Dear TWT,

I am the owner of BabyDogeZilla on BSC chain, YMakkoyev is our main developer.

Could you please assist us with fixing the price glitch of the old contract address (0x0fbc08905c1d683cf7530bb2a70bb0bde231e5b9)?

This old contract address showing wrong balance in US dolars. Its actualy 000000 zeros more then it should show. So people are confused, fuding our project and it making a lot of problems. Thats why we paid another 700 TWT for fixing this glitch and have these two tokens separated from each other.  

There are 2 possible solutions how to fix it.
1. Stop pulling the wrong data and stop showing the price of V1 0x0fbc08905c1d683cf7530bb2a70bb0bde231e5b9 in total.
    We don`t rly care about the old contract, its abbadoned.
2. Fix it and have correct price in each one.

We paid before migration and after migration again so you recived 2 payments so I consider it as payment for 2 separate tokens.

thank you;
CEO of BDZ

**Comment by Michal159** [comment]
Dear TWT,
I am the owner of BabyDogeZilla on the BSC chain, YMakkoyev is our main developer.
Could you please assist us with fixing the price glitch of the old contract address (0x0fbc08905c1d683cf7530bb2a70bb0bde231e5b9)?This old contract address showing a wrong balance in US dollars. It's showing 000000 zeros more than it should show. Becuase during the migration we changed total supply. From sixtrilions to quadrilions. So people are confused, fuding our project and making a lot of problems. That's why we paid another 700 TWT for fixing this glitch and have these two tokens separated from each other.
There are 2 possible solutions to fix it.
1. Stop pulling the wrong data and stop showing the price of V1 0x0fbc08905c1d683cf7530bb2a70bb0bde231e5b9 in total.
2. We don't really care about the old contract, its abandoned.

Fix it and have the correct price in each one.We paid before migration and after migration again so you received 2 payments so I consider it as payment for 2 separate tokens.

thank you;
CEO of BDZ

**Comment by Michal159** [comment]
> BabyDogezilla v1 is abandoned
Dear TWT;
I am the owner of BabyDogeZilla on the BSC chain, YMakkoyev is our main developer.
Could you please assist us with fixing the price glitch of the old contract address?
This old contract address showing a wrong balance in US dollars. It's showing 000000 zeros more than it should show. Becuase during the migration we changed total supply. From sixtrilions to quadrilions. So people are confused, fuding our project and making a lot of problems. 

There are 2 possible solutions to fix it.

Stop pulling the wrong data and stop showing the price of V1 in total.
We don't really care about the old contract, its abandoned.
Fix it and have the correct price in each one. 
We paid before migration and after migration again so you received 2 payments so I consider it as payment for 2 separate tokens.

thank you;
CEO of BDZ

**Pull request closed without merging**
