### PR TITLE
Add RACA

### PR DESCRIPTION
**Pull request by RadiocacaDev**
Add RACA info and logo.

### CODE REVIEW

**Comment by radiocaca** [comment]
Hi @catenocrypt @zachzwei @Cryptocool1 , the automatical checks have always failed, please help

**Comment by radiocaca** [comment]
hi guys, what happened?

**Review by Cryptocool1 — APPROVED** [review]

**Comment by Cryptocool1** [comment]
hello,
try to create new PR.  You don't need to pay one more time. make sure to mention this PR

**Comment by radiocaca** [comment]
@Cryptocool1 should I close this one before a new PR?

**Pull request closed without merging**
