### PR TITLE
Add BCMC1 logo and info

### PR DESCRIPTION
**Pull request by bcmc-support1**
This PR is being closed due to inactivity. If you wish to continue, please have us reopen the PR before sending your payment.
Do NOT send payments for closed PR, as the fee may by lost!
  (135 vs. 99 hrs)

### CODE REVIEW

**Comment by bcmc-support1** [comment]
Hello... I do not understand what the error is?

**Comment by bcmc-support1** [comment]
Ok... I will make the payment today. Thank you!

**Comment by catenocrypt** [comment]
Submission looks OK (error message is incorrect); awaiting fee payment.

**Comment by bcmc-support1** [comment]
Hello! I want to pay now... Please re-open the request

**Comment by bcmc-support1** [comment]
> This PR is being closed due to inactivity. If you wish to continue, please have us reopen the PR before sending your payment.
> Do NOT send payments for closed PR, as the fee may by lost!
> (99 vs. 99 hrs)

Hello! I want to pay now... Please re-open the request

**Comment by bcmc-support1** [comment]
> @bcmc-support1, kind reminder: please pay fee: **250 TWT** with the memo **6445** to the address `bnb1tqq9llyr3dyjd559dha6z5r5etk3qfwk07m098`.
> Alternatively, 2 BNB is also accepted (same memo & address).
> 
> **QR** code: [Trust](https://api.qrserver.com/v1/create-qr-code/?size=200x200&data=https%3A%2F%2Flink.trustwallet.com%2Fsend%3Fcoin%3D714%26address%3Dbnb1tqq9llyr3dyjd559dha6z5r5etk3qfwk07m098%26amount%3D250%26memo%3D6445) | [other wallet](https://api.qrserver.com/v1/create-qr-code/?size=200x200&data=bnb1tqq9llyr3dyjd559dha6z5r5etk3qfwk07m098%26amount%3D250%26memo%3D6445)
> See the [Pull Request Fee FAQ](https://developer.trustwallet.com/add_new_asset/pr-fee).

Hello! I want to pay now... Please re-open the request

**Pull request closed without merging**
