### PR TITLE
Add Metaverse Inu

### PR DESCRIPTION
**Pull request by MetaverseInu**
Updated

### CODE REVIEW

**Review by MetaverseInu — COMMENTED** [review]
Thanks

**Review by MetaverseInu — COMMENTED** [review]
Updated

**Comment by MetaverseInu** [comment]
Thanks
After approve we will pay.
Best regards

**Comment by MetaverseInu** [comment]
Everythings ok ?

**Comment by MetaverseInu** [comment]
We are trending now, our holders are increasing a lot, we hope you approve quickly, thank you very much.

Best regards

**Comment by cryptomanz** [comment]
• Is a Smart Contract audit completed? Where can we find this information?

**Comment by MetaverseInu** [comment]
Our contract is standard, we have not added a special code to a contract that has been audited many times, but we plan to have it audited again just in case.

https://bscscan.com/address/0xc75bcc3ae0844c16fd1881b8bb47bd509303a135#code

**Comment by Cryptocool1** [comment]
awaiting for smart contract audit, on hold for now.

**Comment by MetaverseInu** [comment]
We have started our work for the audit, we will inform you as soon as possible to be completed.
Best regards

**Comment by MetaverseInu** [comment]
Hello

Techrate company is doing our audit review. They will complete and send it up to 2 days, they also made a quick preliminary review, there is no critical problem, you can see it from the link below.

When the full audit report is completed, we will also share it with you.

https://metaverseinu.org/MetaverseInu_Audit.pdf

King Regards

**Comment by MetaverseInu** [comment]
gives when run  under below error,

npm ERR! code ELIFECYCLE npm ERR! errno 1 npm ERR! assets@1.0.0 check: `ts-node ./script/entrypoint/check`

for fix i added  @cryptomanz  

Thanks

**Comment by Cryptocool1** [comment]
please create new PR without this file: .github/workflows/fix.yml
When creating a new PR make sure to mention this PR, so that we can see that fee has been paid already here.

**Pull request closed without merging**
