### PR TITLE
Add GIV Token Logo and Info

### PR DESCRIPTION
**Pull request by jchung00**
## Please note
- GIV was initially a BEP-2 token but we [opened a bridge](https://medium.com/@cryptolocally/how-to-swap-between-giv-bep-2-and-giv-erc-20-d4d802364b98) between ERC-20 and BEP-2
- GIV is already on TrustWallet as a BEP-2 token, where it has [thousands of holders](https://explorer.binance.org/asset/GIV-94E)

Thanks!

### CODE REVIEW

**Comment by jchung00** [comment]
Paid

**Review by Iamdeadlyz — CHANGES_REQUESTED** [review]
Hi @jchung00 
- Please change the name of the folder to `0xf6537FE0df7F0Cc0985Cf00792CC98249E73EFa0`
- Resize the logo to 256px by 256px

**Comment by jchung00** [comment]
Hi @Iamdeadlyz, changes pushed. Thanks!

**Comment by Iamdeadlyz** [comment]
Hello @jchung00 

Please change the name of the folder to `0xf6537FE0df7F0Cc0985Cf00792CC98249E73EFa0`
Take note of the capitalizations ^

You can do the following steps:
- Rename the folder first to `0xf6537FE0df7F0Cc0985Cf00792CC98249E73EFa0-x` so that it will recognize the changes. Then push it.
- Afterward, remove the `-x` so you are left with `0xf6537FE0df7F0Cc0985Cf00792CC98249E73EFa0` and push this commit.

**Comment by jchung00** [comment]
Hey @Iamdeadlyz sorry for the delays, I've pushed the most recent changes.

**Review by Iamdeadlyz — APPROVED** [review]
Thanks for the edits @jchung00 ✅

**Pull request merged**
