### PR TITLE
Add DevilPin Logo And Info

### PR DESCRIPTION
**Pull request by DevilPin**

### CODE REVIEW

**Comment by Cryptocool1** [comment]
hi there,
can you please answer some questions?
• What is the purpose of this token? How will it benefit Trust Wallet users?
 • How is the token being distributed? Are you conducting an airdrop?
 • Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?
 • Is the token listed on a centralized/decentralized exchange?
 • Is a Smart Contract audit completed? Where can we find this information?

**Comment by DevilPin** [comment]
1. DevilPin is a leading DeFi yield aggregator on BSC that has 3 products as part of the DevilPin ecosystem, namely Vaults (yield optimizer), DevilPin (DEX Aggregator), and farmfolio. The yield optimizer implements the most optimal strategies at the lowest cost to maximize users' yields and DevilPin implements optimizations to route users swap trades so that users can find the best price and swap rates. Lastly, farmfolio is an intelligent portfolio manager and tracker which helps users manage their assets across various DeFi farming projects.
2. Airdrop and presale ( ICO )
3. Pancakeswap, hotbit ( on progress )
4. Not

**Comment by DevilPin** [comment]
> hi there,
> can you please answer some questions?
> • What is the purpose of this token? How will it benefit Trust Wallet users?
> • How is the token being distributed? Are you conducting an airdrop?
> • Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?
> • Is the token listed on a centralized/decentralized exchange?
> • Is a Smart Contract audit completed? Where can we find this information?

1. DevilPin is a leading DeFi yield aggregator on BSC that has 3 products as part of the DevilPin ecosystem, namely Vaults (yield optimizer), DevilPin (DEX Aggregator), and farmfolio. The yield optimizer implements the most optimal strategies at the lowest cost to maximize users' yields and DevilPin implements optimizations to route users swap trades so that users can find the best price and swap rates. Lastly, farmfolio is an intelligent portfolio manager and tracker which helps users manage their assets across various DeFi farming projects.
2. Airdrop and presale 
3. Pancakeswap, hotbit ( on progress )
4. Not

**Comment by DevilPin** [comment]
If you need more information I will be happy to know
@Cryptocool1

**Comment by Cryptocool1** [comment]
awaiting for smart contract audit
on hold for now

**Comment by Cryptocool1** [comment]
please create new PR when smart contract audit will be ready
make sure to mention this PR
(you don't need to pay one more time)

**Pull request closed without merging**
