### PR TITLE
add logo to MILF token

### PR DESCRIPTION
**Pull request by jennanatalie**
milf token logo

### CODE REVIEW

**Comment by Cryptocool1** [comment]
Submission looks good. awaiting fee payment.

**Comment by jennanatalie** [comment]
> Submission looks good. awaiting fee payment.

why is it giving an error with the etherscan link?

**Comment by Cryptocool1** [comment]
> > Submission looks good. awaiting fee payment.
> 
> why is it giving an error with the etherscan link?

don't worry, it's ok.

**Comment by jennanatalie** [comment]
paying with TWT right now

**Comment by jennanatalie** [comment]
how do you guys confirm the payment through memo? do i have to send you the wallet address that the twt is coming from

**Comment by jennanatalie** [comment]
It will take several days?

**Pull request merged**
