### PR TITLE
Add Newscrypto (NWC) token to BSC and change logo

### PR DESCRIPTION
**Pull request by newscrypto**
Hi we want to change logo and list on BSC wallet

### CODE REVIEW

**Comment by newscrypto** [comment]
How can we get to your DEX we are listed on Uniswap and Pancakeswap. 
Thanks

**Review by KaycoinsInc — APPROVED** [review]

**Review by KaycoinsInc — APPROVED** [review]

**Review by KaycoinsInc — APPROVED** [review]

**Comment by catenocrypt** [comment]
Submission looks OK.
Just to confirm, you managed to use the same contract ID for both ERC20 and BEP20 versions?

**Comment by newscrypto** [comment]
yes we have same contract addresses for ERC20 and BEP20.

**Comment by newscrypto** [comment]
How do we get to your DEX inside of app? We have pool on uniswap:
https://info.uniswap.org/pair/0x4f6d22362629c5a933d285ad0036d78f30a6b1cb
Do we need to provide more info for this?
Thanks

**Comment by catenocrypt** [comment]
To get logo in Trust Wallet:  this submission is OK, fee payment has to be payed though.
The DEX inside Trust Wallet is a frontend to selected Uniswap / Pancakeswap markets, but we exclude low liquidity pairs.  Currently we have $2M liquidity threshold on Uniswap and $1M on pancakswap (may change).  But Uniswap and Pancakeswap DApps can be opened directly from TW, showing all pairs.

**Pull request merged**
