### PR TITLE
Add Shiro Neko (SHIRO) (ERC20)

### PR DESCRIPTION
**Pull request by MrLightspeed**
Adding info for ERC20 token 'Shiro Neko (SHIRO)'.

PR created by <a href="https://assets.trustwallet.com">TW Assets Management</a>

### CODE REVIEW

**Comment by MrLightspeed** [comment]
Here is a proper submission for Shiro Neko (SHIRO)

What is the purpose of this token? How will it benefit Trust Wallet users?

Shiro Neko ($SHIRO) is a meme coin launched on the Ethereum blockchain, inspired by the Japanese term for "White Cat." The project narrates Shiro's journey in the crypto sphere under the mentorship of Shiba Inu, aiming to build his own legacy with $SHIRO.

As a meme coin, $SHIRO primarily serves as a community-driven token without intrinsic value or expectations of financial return. The project's disclaimer emphasizes its experimental nature and advises participants to engage cautiously, acknowledging the inherent risks and volatility associated with such tokens.

For Trust Wallet users, $SHIRO can be managed like any other Ethereum-based token.

• How is the token being distributed? Are you conducting an airdrop?

All tokens have been distributed - there will be no airdrops.

• Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?

All tokens purchased on the free market 

• Is the token listed on a centralized/decentralized exchange?

Yes, SHIRO is listed on Uniswap v2, Uniswap v3, MEXC, BitMart, LBank, XT, KCEX, Ourbit, Bilaxy

• Is a Smart Contract audit completed? Where can we find this information?

No. Contract is verified and can be viewed at https://etherscan.io/token/0xb0ac2b5a73da0e67a8e5489ba922b3f8d582e058#code

**Comment by Cryptocool1** [comment]
Is a Smart Contract audit completed? Where can we find this information?

**Comment by Cryptocool1** [comment]
Hello, We require an audit from reputable companies. (Certik, Techrate, Hacken).
The request will be closed until further notice.

To know more about the token approval guidelines, please check this article: [How to Submit Token Logo](https://developer.trustwallet.com/listing-new-assets/requirements).

Feel free to re-open pull request once you meet those requirements.

**Comment by MrLightspeed** [comment]
@Cryptocool1 The smart contract is renounced: 

https://etherscan.io/tx/0xcd866f85d972165ee9558133e628602bddb6e6a4d93a14f97d6d320517a9dd0b

I hope this is sufficient!

**Comment by MrLightspeed** [comment]
cryptomanz1 - smart contract is renounced.

**Comment by MrLightspeed** [comment]
@cryptomanz1 - smart contract is renounced.

**Pull request closed without merging**
