### PR TITLE
Add Bimp.Finance (BEP20)

### PR DESCRIPTION
**Pull request by BIMPFinance**
Adding info for BEP20 token 'Bimp.Finance'.

PR created by <a href="https://assets.trustwallet.com">TW Assets Management</a>

### CODE REVIEW

**Comment by BIMPFinance** [comment]
Hi,

I am having a problem with updating our website link here -
https://assets.trustwallet.com/

Getting this error every time I add our website.
[image: image.png]

What do I need to do?

Or do I need to proceed with the payment and you will take care of this?

Hoping for your response soon.

Thank you so much

**Comment by BIMPFinance** [comment]
Hi,

Any updates? What do I need to do?

Thank you

**Comment by Cryptocool1** [comment]
> Hi, Any updates? What do I need to do? Thank you
> […](#)

your website is ok. 
awaiting for fee payment.

**Comment by BIMPFinance** [comment]
Thanks, I will pay now

**Comment by BIMPFinance** [comment]
Thank you for the confirmation of the payment.

Please let me know if I need to do anything else.

Thank you so much

**Pull request merged**
