### PR TITLE
Add Lavender.Five Validator Provider

### PR DESCRIPTION
**Pull request by dylanschultzie**

### CODE REVIEW

**Comment by dylanschultzie** [comment]
@cryptomanz1 do you accept PRs to add new networks? I'd be happy to add support for some. I'm one of the core maintainers of the chain registry: https://github.com/cosmos/chain-registry.

Happy to chat offline.

**Comment by cryptomanz1** [comment]
please remove extra space
Screenshot 2023-11-23 at 21 03 49

**Comment by dylanschultzie** [comment]
@cryptomanz1 updated. 

Did you see my message above? 

> @cryptomanz1 do you accept PRs to add new networks? I'd be happy to add support for some. I'm one of the core maintainers of the chain registry: https://github.com/cosmos/chain-registry.
> 
> Happy to chat offline.
> 
> edit: reference https://developer.trustwallet.com/developer/wallet-core/newblockchain

**Comment by dylanschultzie** [comment]
@Cryptocool1 @cryptomanz1 is there anything I can do to help get this over the line?

**Comment by cryptomanz1** [comment]
> @cryptomanz1 do you accept PRs to add new networks? I'd be happy to add support for some. I'm one of the core maintainers of the chain registry: https://github.com/cosmos/chain-registry.
> 
> Happy to chat offline.
> 
> edit: reference https://developer.trustwallet.com/developer/wallet-core/newblockchain

do you mean to add new blockchain?

**Comment by dylanschultzie** [comment]
@cryptomanz1 yes, for example I could add archway without too much difficulty.

**Comment by cryptomanz1** [comment]
You need create PR in Wallet Core: https://github.com/trustwallet/wallet-core
Please follow the rules : https://developer.trustwallet.com/developer/wallet-core/newblockchain

**Comment by Masoudleyli** [comment]
> 

@Masoudleyli @masoudahg000 @masoudahgl @masley100 - [ ] - [ ] # @dylanschultzie ~~~~

**Pull request merged**
