### PR TITLE
Update old MLTP token

### PR DESCRIPTION
**Pull request by moonlift**
updated the info and logo of the old MLTP token

### CODE REVIEW

**Comment by Cryptocool1** [comment]
hello,
do you want to remove this token?

**Review by mshuman77 — COMMENTED** [review]
I can't tell you how much I appreciate this being done. Because of this I was able to fix my issue of have 127,000+ MLTP tokens being worth $0. Now I have them in my wallet as proper traded tokens again.

**Comment by Cryptocool1** [comment]
can you send me an official announcement about the updating?

**Comment by Cryptocool1** [comment]
still no answer
closing PR for now

**Pull request closed without merging**
