### PR TITLE
update Digitale Mark

### PR DESCRIPTION
**Pull request by dma2020**
update logo.png

### CODE REVIEW

**Comment by zachzwei** [comment]
There are multiple commits which could cause errors when merged.
Please make it simple.
Thanks.

**Comment by dma2020** [comment]
simple? what you mean?

**Comment by zachzwei** [comment]
There are multiple commits. Some does not follow the Checksum address folder name. This might cause errors.

**Comment by dma2020** [comment]
i think i should use my erc contract adress as folder name. i cant tranfer it to checksum.

**Pull request closed without merging**
