### PR TITLE
nuu token logo update

### PR DESCRIPTION
**Pull request by Niuupeak**

### CODE REVIEW

**Comment by Niuupeak** [comment]
memo 2014 ,by mistake ill transfer 0.99BNB so what to i do,

**Comment by kolya182** [comment]
@catenocrypt Could you refund `0.5` BNB to @Niuupeak

**Comment by catenocrypt** [comment]
ok

**Comment by catenocrypt** [comment]
The extra ˜0.5 BNB has been refunded
https://explorer.binance.org/tx/F94EC1E557E17A9D499FDF8BF4D61B30C5D34DE553B773D06C5CE22028697FAD

**Pull request merged**
