### PR TITLE
Add Everdome (BEP20)

### PR DESCRIPTION
**Pull request by everdomeglobal**
Adding info for BEP20 token 'Everdome'.

PR created by <a href="https://assets.trustwallet.com">TW Assets Management</a>

### CODE REVIEW

**Comment by Cryptocool1** [comment]
• What is the purpose of this token? How will it benefit Trust Wallet users?
 • How is the token being distributed? Are you conducting an airdrop?
 • Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?
 • Is the token listed on a centralized/decentralized exchange?
 • Is a Smart Contract audit completed? Where can we find this information?

**Comment by everdomeglobal** [comment]
• What is the purpose of this token?  How will it benefit Trust Wallet users? 
Through their revolutionary technological capacity and experience, Everdome aims to create the most hyper-realistic metaverse that will bring brands and people together - all with the intent of building the most realistic web3 experience. 
 
• How is the token being distributed?  Are you conducting an airdrop? 
Only through presale so far.  No airdrop is planned as of now. 
 
• Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale? 
We had three presale rounds - one for Metahero holders, one via Tenset Gems Launchpad and a private round. 
 
• Is the token listed on a centralized/decentralized exchange? 
First CEX listing is planned for February 8th. 
 
• Is a Smart Contract audit completed?  Where can we find this information? 
Our Smart Contract had two internal audits and it's undergoing Certik audit right now.  Link: https://www.certik.com/projects/everdome

**Comment by everdomeglobal** [comment]
What's happening?

**Comment by Cryptocool1** [comment]
your audit is in progress, awaiting for full smart contract audit

**Comment by everdomeglobal** [comment]
https://www.okx.com/support/hc/en-us/articles/4424597833997-OKX-will-list-Everdome-s-DOME-token-for-spot-trading
image

**Pull request merged**
