### PR TITLE
pay for listing Rael on trust wallet

### PR DESCRIPTION
**Pull request by raelcoin**
hello
Please check the new information and send the payment link to be listed in Trust Walt

thank you

### CODE REVIEW

**Comment by raelcoin** [comment]
hello
Will the specifications and photo of the token be updated in Binance?
and how can updat this error ?
File not allowed: logo.png. Please revert it.

**Comment by cryptomanz** [comment]
Info file should be named info.json
Logo file should be named logo.png

Please create new PR, follow doc https://community.trustwallet.com/t/how-to-submit-a-token-logo/3863
You may want to try our Assets app in beta; go to https://assets.trustwallet.com, log on with Github, enter contract ID, logo and some additional info, and it will create a PR for you.
See https://community.trustwallet.com/t/how-to-submit-a-token-logo-using-assets-app/82957.

**Comment by raelcoin** [comment]
i sent logo.png in assest and i dont know where and how i must creat or send new logo.png i already uploaded it please help

**Comment by raelcoin** [comment]
i cant upload for update my assets
Uploads are disabled.

**Comment by Cryptocool1** [comment]
> i sent logo.png in assest and i dont know where and how i must creat or send new logo.png i already uploaded it please help

 go to https://assets.trustwallet.com, log on with Github, enter contract ID, logo and some additional info, and it will create a PR for you.

**Pull request closed without merging**
