### PR TITLE
Offical logo of the Standard Crypto Fund QQQF

### PR DESCRIPTION
**Pull request by ghost**
This is the logo of the Standard Crypto Fund QQQF, a tokenised exchange-tradable index fund with integrated DeFi functionalities.

### CODE REVIEW

**Comment by standardcryptofund** [comment]
Payment has been made, tx: https://explorer.binance.org/tx/C0A91F67C4FEE4F85E9319C5B7661C545199A2FABEEA8450972C20E1C7A0BC27

If there are any issues, please feel free to contact me here or via rotatingnut@standardcryptofund.com

**Comment by standardcryptofund** [comment]
I probably have to add the info.json file.

{
  "name": "Standard Crypto Fund",
  "website": "http://qqqfindex.com",
  "source_code": "https://github.com/standardcryptofund",
  "white_paper": "http://qqqfindex.com/qqqf_whitepaper_v1.pdf",
  "short_description": "The Standard Crypto Fund QQQF is a tokenised exchange-tradable fund (ETF) with DAO implementation.",
  "explorer": "https://etherscan.io/token/0x22eEab2f980E8ed7824f8EA548C9595564a0F0e4",
}

I hope that there will be a way for me to add this.

**Comment by vikmeup** [comment]
> I probably have to add the info.json file.
> 
> {
> "name": "Standard Crypto Fund",
> "website": "http://qqqfindex.com",
> "source_code": "https://github.com/standardcryptofund",
> "white_paper": "http://qqqfindex.com/qqqf_whitepaper_v1.pdf",
> "short_description": "The Standard Crypto Fund QQQF is a tokenised exchange-tradable fund (ETF) with DAO implementation.",
> "explorer": "https://etherscan.io/token/0x22eEab2f980E8ed7824f8EA548C9595564a0F0e4",
> }
> 
> I hope that there will be a way for me to add this.

yes, please add that

**Comment by standardcryptofund** [comment]
Added info.json as per request. Please disregard my 3 or 4 failed commits, it seems that I am too inapt to use a simple JSON online validator in order to find my mistake (was a comma that I've simply not seen).

I hope everything is fixed now. If there are any issues that persist, please feel free to contact me.

**Pull request merged**
