### PR TITLE
Add Max Crowdfund (MCF) logo and info

### PR DESCRIPTION
**Pull request by MaxCrowdfund**
We have changed from our ardor child chain (Max Property Group - MPG) to the Binance Smart Chain and created the Max Crowdfund - MCF token. This is a new token, but we have a large community and approx 60,000 users and token holders.
We are going through the steps (process) to create the token, add the token to Trust Wallet, add Liquidity to Pancakeswap and informing our community (https://twitter.com/maxcrowdfund) about the changes. We will slowly be distributing the MCF tokens to all our users and trading will commence.

We understand you do not like new tokens, but this is just us changing. Our group was incorporated in 2016 in the Netherlands and a lot of information can be found online about Max Property Group and Max Crowdfund.

As we know this process will take some time, we decided to commit already and continue with our distribution in the meantime.

### CODE REVIEW

**Comment by MaxCrowdfund** [comment]
The address for making the payment comes back as an incorrect address on our Trust Wallet. Can somebody look into that please?

**Comment by Cryptocool1** [comment]
> The address for making the payment comes back as an incorrect address on our Trust Wallet. Can somebody look into that please?

please pay 250 TWT with the memo 9335 to the address bnb1tqq9llyr3dyjd559dha6z5r5etk3qfwk07m098.
try it. again

**Comment by MaxCrowdfund** [comment]
> > The address for making the payment comes back as an incorrect address on our Trust Wallet. Can somebody look into that please?
> 
> please pay 250 TWT with the memo 9335 to the address bnb1tqq9llyr3dyjd559dha6z5r5etk3qfwk07m098.
> try it. again

I just did and it still comes back as an invalid address. We are tring to pay 2 BNB.

**Comment by MaxCrowdfund** [comment]
image

**Comment by MaxCrowdfund** [comment]
> @MaxCrowdfund, kind reminder: please pay fee: **250 TWT** with the memo **9335** to the address `bnb1tqq9llyr3dyjd559dha6z5r5etk3qfwk07m098`.
> Alternatively, 2 BNB is also accepted (same memo & address).
> 
> **QR** code: [Trust](https://api.qrserver.com/v1/create-qr-code/?size=200x200&data=https%3A%2F%2Flink.trustwallet.com%2Fsend%3Fcoin%3D714%26address%3Dbnb1tqq9llyr3dyjd559dha6z5r5etk3qfwk07m098%26amount%3D250%26memo%3D9335) | [other wallet](https://api.qrserver.com/v1/create-qr-code/?size=200x200&data=bnb1tqq9llyr3dyjd559dha6z5r5etk3qfwk07m098%26amount%3D250%26memo%3D9335)
> See the [Pull Request Fee FAQ](https://developer.trustwallet.com/add_new_asset/pr-fee).

I just tried to pay this again, but the address still comes up as an invalid address. How can we proceed?

**Comment by Cryptocool1** [comment]
hello,
you need to correct your description

**Comment by MaxCrowdfund** [comment]
> hello,
> you need to correct your description

Hi Cryptocool1. You mean in the json file?

Would this be acceptable:
"Max Crowdfund is an international real estate crowdfunding platform on blockchain technology and the first such platform to obtain regulatory approval from financial regulators in the Netherlands. The MCF token pays out 5% of all transactions to liquidity pool providers and 1% of all transactions to all token holders. There is also a buy-back and burn program where 0.1% of all investments made on all Max Crowdfund platforms will be used to buy back and burn MCF tokens. Max Crowdfund aims to be the biggest real estate crowdfunding platform in the world and they are expanding internationally through exclusive Joint Ventures."

**Comment by MaxCrowdfund** [comment]
Is there something we need to do regarding the failed checks above?

**Comment by MaxCrowdfund** [comment]
> **PR Summary**
> Files OK, 2Files in PR: 2
> Token in PR: BEP2 0xecB19B2A4e9C76cE748cf33f68f0857288f9f090
> Symbol: **MCF** decimals: 9
> Links: [Logo](https://raw.githubusercontent.com/MaxCrowdfund/assets/master/blockchains/binance/assets/0xecB19B2A4e9C76cE748cf33f68f0857288f9f090/logo.png) [Info](https://raw.githubusercontent.com/MaxCrowdfund/assets/master/blockchains/binance/assets/0xecB19B2A4e9C76cE748cf33f68f0857288f9f090/info.json) [Website](https://maxcrowdfund.com) [ExplorerFromInfo](https://bscscan.com/address/0xecB19B2A4e9C76cE748cf33f68f0857288f9f090) [ExplorerFromID](https://explorer.binance.org/asset/0xecB19B2A4e9C76cE748cf33f68f0857288f9f090)
> Token check error:
> ❌ ExplorerUrl incorrect, should be standard https://explorer.binance.org/asset/0xecB19B2A4e9C76cE748cf33f68f0857288f9f090, not https://bscscan.com/address/0xecB19B2A4e9C76cE748cf33f68f0857288f9f090
> ! No. of holders not checked, external info not available; null
> ✓ Token type OK (BEP2); Contract/ID is OK; Type field OK; Symbol field OK; Decimals field OK; Description field OK; Website field OK; Status field OK; Id field OK; Logo image type is OK (image/png); Logo image size is OK (13.174 kB); Logo dimensions OK (256x256);
> 
> 

The only explorer that works is the bscscan.com as provided.
Note that we are still distributing MCF to all our registered users and are only now informing them to create accounts on Trustwallet and provide us with their BNB Smart Chain addresses.

**Comment by Cryptocool1** [comment]
Correction needed:
This is a BEp20 token, correct folder is blockchains/smartchain/assets. Please correct.

**Comment by Cryptocool1** [comment]
Please create new PR, follow doc https://community.trustwallet.com/t/how-to-submit-a-token-logo/3863
You may want to try our new Assets app in beta; go to https://assets.trustwallet.com, log on with Github, enter contract ID, logo and some additional info, and it will create a PR for you.
See https://community.trustwallet.com/t/how-to-submit-a-token-logo-using-assets-app/82957.

When creating new PR, mention this PR, so that fee can be reused, and not paid again.

**Pull request closed without merging**
