### PR TITLE
Add CBT logo and info

### PR DESCRIPTION
**Pull request by elaz48**

### CODE REVIEW

**Comment by Cryptocool1** [comment]
As per our policy, brand new tokens are not included, there is a minimum requirement of 5000 holder addresses and 10000 transactions, in order to filter out scam tokens.
See the criteria: https://community.trustwallet.com/t/how-to-submit-a-token-logo/3863).

**Comment by infinite404** [comment]
> As per our policy, brand new tokens are not included, there is a minimum requirement of 5000 holder addresses and 10000 transactions, in order to filter out scam tokens. See the criteria: https://community.trustwallet.com/t/how-to-submit-a-token-logo/3863).

CBT is not a scam coin as there is a legal entity behind it and it was created 76 days ago. It also has 11k+ transactions. Anyhow, I appreciate TrustWallet rules. What's the protocol now? Do we have to wait the 5000 holders then you will complete the logo request? Thank you for you answer in advance!

**Comment by Cryptocool1** [comment]
• What is the purpose of this token? How will it benefit Trust Wallet users?
 • How is the token being distributed? Are you conducting an airdrop?
 • Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?
 • Is the token listed on a centralized/decentralized exchange?
 • Is a Smart Contract audit completed? Where can we find this information?

**Comment by infinite404** [comment]
> • What is the purpose of this token? How will it benefit Trust Wallet users? • How is the token being distributed? Are you conducting an airdrop? • Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale? • Is the token listed on a centralized/decentralized exchange? • Is a Smart Contract audit completed? Where can we find this information?

- The token is a 10% ADA reflection token and an investment into CryptoBlast energy drinks a registered company in Canada. How will it benefit Trust Wallet users? By providing a safe place to invest.
- Pancakeswap and Tokpie exchange. We have conducted an airdrop but we have no plans to airdrop ot in the future.
- No ICO, no presale.
- Pancakeswap and Tokpie
- Yes, we have an audit. https://bitriseaudits.com/project/38

**Comment by Cryptocool1** [comment]
as per our policy, your token should have at least 5,000 holders

**Comment by cryptomanz** [comment]
Hello,
Please follow the rules for adding token, your logo should be a full screen, 256x256.

**Comment by Cryptocool1** [comment]
Please come back to us when all criteria are met.
When creating a new PR make sure to mention this PR, so that we can see that fee has been paid already here.

**Pull request closed without merging**
