### PR TITLE
Add Crypto Legions V3 (BEP20)

### PR DESCRIPTION
**Pull request by abu7shish**
Adding info for BEP20 token 'Crypto Legions V3'.

PR created by <a href="https://assets.trustwallet.com">TW Assets Management</a>

### CODE REVIEW

**Comment by abu7shish** [comment]
this is our old pull request - fees is already paid

**Comment by abu7shish** [comment]
> @abu7shish, kind reminder: please pay fee: **700 TWT** with the memo **22821** to the address `bnb1tqq9llyr3dyjd559dha6z5r5etk3qfwk07m098`. Alternatively, 5 BNB is also accepted (same memo & address).
> 
> **QR** code: [Trust](https://api.qrserver.com/v1/create-qr-code/?size=200x200&data=https%3A%2F%2Flink.trustwallet.com%2Fsend%3Fcoin%3D714%26address%3Dbnb1tqq9llyr3dyjd559dha6z5r5etk3qfwk07m098%26amount%3D700%26memo%3D22821) | [other wallet](https://api.qrserver.com/v1/create-qr-code/?size=200x200&data=bnb1tqq9llyr3dyjd559dha6z5r5etk3qfwk07m098%3Famount%3D700%26memo%3D22821) See the [Pull Request Fee FAQ](https://developer.trustwallet.com/assets/faq).

this is our old pull request - fees is already paid - https://github.com/trustwallet/assets/pull/22672

**Comment by abu7shish** [comment]
Dear @Cryptocool1 - this is our old pull request - fees is already paid - https://github.com/trustwallet/assets/pull/22672

**Comment by cryptomanz1** [comment]
As per our policy, brand new tokens are not included, there is a minimum requirement of 10,000 holder addresses and 15,000 transactions, in order to filter out scam tokens.
See the criteria at : https://developer.trustwallet.com/assets/requirements .

**Pull request closed without merging**
