### PR TITLE
Add MUFC logo and info

### PR DESCRIPTION
**Pull request by ghost**

### CODE REVIEW

**Comment by cryptomanz** [comment]
Hello,
can you please add links to your PR?
example:
Screenshot 2021-10-06 at 20 22 37

**Comment by cryptomanz** [comment]
Submission looks good. awaiting fee payment.

**Comment by mufctoken** [comment]
With the big love and loyal heart for MU, we desire to build the connection between fans around the world through MUFC token! Our ambition is to distribute MUFC token for all fans around the world and give control of those tokens to them.
Token from Presale/IDO will be released from Feb 4th, 2022, 30% per month. 
We also conduct Airdrop Campaign with 1% of Total supply. Airdrop token will be locked until IDO ends, then distributed by 10% per month.
MUFC token has listed on Pancakeswap. You can check via this link: https://pancakeswap.finance/swap#/swap?outputCurrency=0xE44946b6A075b2C99fDe1dD0c4dA4a3436211f8C
MUFC has also lived on Coinmarketcap: https://coinmarketcap.com/vi/currencies/manchester-united-fan-token/
We has received the audit report from Soken team since last week. Here is this link of report:
https://github.com/sokenteam/smart_contract_audits/blob/main/Manchester%20United%20Fan%20Token%20Comprehensive%20Smart%20Contract%20Audit.pdf

**Comment by cryptomanz** [comment]
> Submission looks good. awaiting fee payment.

**Pull request merged**
