### PR TITLE
ADD DIS logo and info

### PR DESCRIPTION
**Pull request by MiningTW**
https://bscscan.com/tx/0x4bf3b74738e0cb7e7cffdeb3ba21a45e2728e287e547c43ec44301bcdaacaaf3

### CODE REVIEW

**Comment by MiningTW** [comment]
https://bscscan.com/tx/0x4bf3b74738e0cb7e7cffdeb3ba21a45e2728e287e547c43ec44301bcdaacaaf3

//re:
Token is detected to have a proxy contract, which is a potentially dangerous configuration. Therefore, unless there is a formal security audit that proves its safety, it cannot be listed. However, the TPT hash value you submitted can be used in the next logo submission.//

**Comment by MiningTW** [comment]
This token contract originally had an agent upgrade function, but has given up the contract ownership and has passed a security audit https://github.com/cyberscope-io/audits/blob/main/dis/audit.pdf https://www.coinscope.co/coin/dis/audit https://twitter.com/cyberscope_io/status/1668656345178861568 Another important point is that we use the real-name company to issue the token Miningtw Technology Co., Ltd. https://www.twincn.com/item.aspx?no=90324590 And it is stated in the white paper that this DIS has nothing to do with Walt Disney. It is not issued or related to them. It is a meme coin with similar names in different fields.

**Comment by MiningTW** [comment]
https://bscscan.com/tx/0x4bf3b74738e0cb7e7cffdeb3ba21a45e2728e287e547c43ec44301bcdaacaaf3

merge-fee-bot[bot] ***@***.***>於 2023年6月17日 週六，下午3:38寫道：

**Comment by MiningTW** [comment]
https://bscscan.com/tx/0x4bf3b74738e0cb7e7cffdeb3ba21a45e2728e287e547c43ec44301bcdaacaaf3
//re:
Token is detected to have a proxy contract, which is a potentially dangerous configuration. Therefore, unless there is a formal security audit that proves its safety, it cannot be listed. However, the TPT hash value you submitted can be used in the next logo submission.//

**Comment by MiningTW** [comment]
Dear Trust Wallet team,

I've manually checked the number of holders for our token. As of this writing, we have 11,672 holders. 

Please find the relevant information here: [BscScan Link](https://bscscan.com/token/0xe2ecc66e14efa96e9c55945f79564f468882d24c)

Best regards,
MiningTW

**Comment by MiningTW** [comment]
Dear Trust Wallet team,

I have made the payment of 500 TWT as per the instructions. Here is the transaction hash for your reference: [Transaction Hash](https://bscscan.com/tx/0x4bf3b74738e0cb7e7cffdeb3ba21a45e2728e287e547c43ec44301bcdaacaaf3)

Please proceed with the review of our PR.

Best regards,
MiningTW

**Comment by MiningTW** [comment]
Dear Trust Wallet team,

I understand your concerns regarding the proxy contract. We have since rectified this and I have re-submitted our token's data. The payment for this submission was already made during the previous application, and can be verified via this [transaction hash](https://bscscan.com/tx/0x4bf3b74738e0cb7e7cffdeb3ba21a45e2728e287e547c43ec44301bcdaacaaf3), as per your previous communication that the TPT hash value could be used for the next logo submission.

Please let me know if there are any further steps that need to be completed.

Best regards,
MiningTW

**Comment by MiningTW** [comment]
Dear Trust Wallet team,

I understand your concerns regarding the proxy contract. Since then, we have addressed the issue and conducted a formal security audit to ensure the safety of our token's contract. The audit report can be found here: [GitHub Audit](https://github.com/cyberscope-io/audits/blob/main/dis/audit.pdf) and [Coinscope Audit](https://www.coinscope.co/coin/dis/audit).

In addition, I would like to inform you that I have relinquished ownership of the contract as per this [transaction hash](https://bscscan.com/tx/0x89a6fd8f6d45c0e56e501152276612e92ef3c93ab1a8f8fd6cf190f65bc59811).

Moreover, I have re-submitted our token's data. The payment for this submission was already made during the previous application, and can be verified via this [transaction hash](https://bscscan.com/tx/0x4bf3b74738e0cb7e7cffdeb3ba21a45e2728e287e547c43ec44301bcdaacaaf3), as per your previous communication that the TPT hash value could be used for the next logo submission.

Please let me know if there are any further steps that need to be completed.

Best regards,
MiningTW

**Comment by Cryptocool1** [comment]
What is the number of your previous PR?

**Comment by MiningTW** [comment]
https://github.com/TP-Lab/tokens/pull/9452

**Pull request closed without merging**
