### PR TITLE
Added new Contract Address for $LIGHT

### PR DESCRIPTION
**Pull request by SAW-Lightning**
$LIGHT Lightning Incubator and Launchpad migrated to a new V2 token yesterday. Adding the new token to TrustWallet.

### CODE REVIEW

**Comment by Cryptocool1** [comment]
hello,
what was the previous contract?

**Comment by SAW-Lightning** [comment]
Previous contract was 0x7b9c3df47f3326fbc0674d51dc3eb0f2df29f37f

Here is our Medium article with announcement: https://lightningprotocol.medium.com/lightning-v2-stake-light-earn-bnb-39e125dbc625

**Comment by Cryptocool1** [comment]
> Previous contract was 0x7b9c3df47f3326fbc0674d51dc3eb0f2df29f37f
> 
> Here is our Medium article with announcement: https://lightningprotocol.medium.com/lightning-v2-stake-light-earn-bnb-39e125dbc625

is the previous contract abandoned ?

**Comment by SAW-Lightning** [comment]
Yes, we have deprecated the previous contract.

**Comment by Cryptocool1** [comment]
could you add the links?
see the example here: https://developer.trustwallet.com/assets/repository_details

**Comment by SAW-Lightning** [comment]
Links have been added

**Pull request merged**
