### PR TITLE
Add TEDDY logo on trust wallet

### PR DESCRIPTION
**Pull request by TeddyDogeAdmin**
Add TEDDY logo on trust wallet
Telegram id：https://t.me/TeddyDoge_Admin
THX

### CODE REVIEW

**Comment by cryptomanz** [comment]
can you please add tags?

**Comment by TeddyDogeAdmin** [comment]
sorry？
what is tag？
dear？

获取 Outlook for iOS<https://aka.ms/o0ukef>
________________________________
发件人: Nazar ***@***.***>
发送时间: Wednesday, April 6, 2022 4:51:49 AM
收件人: trustwallet/assets ***@***.***>
抄送: swap teddy ***@***.***>; Author ***@***.***>
主题: Re: [trustwallet/assets] Add TEDDY logo on trust wallet (PR #19547)


can you please add tags?

―

**Comment by TeddyDogeAdmin** [comment]
like DEFI？

获取 Outlook for iOS<https://aka.ms/o0ukef>
________________________________
发件人: Nazar ***@***.***>
发送时间: Wednesday, April 6, 2022 4:51:49 AM
收件人: trustwallet/assets ***@***.***>
抄送: swap teddy ***@***.***>; Author ***@***.***>
主题: Re: [trustwallet/assets] Add TEDDY logo on trust wallet (PR #19547)


can you please add tags?

―

**Comment by TeddyDogeAdmin** [comment]
> can you please add tags and link?

{   
    "name": "TEDDY",
    "website": "https://teddydoge.finance/",
    "description": "TEDDY is the DEFI ecological token of Teddy Doge with Swap & Cross bridge& Wallet.",
    "explorer": "https://bscscan.com/token/0x10f6f2b97F3aB29583D9D38BaBF2994dF7220C21",
    "type": "BEP20",
    "symbol": "TEDDY",
    "decimals": 18,
    "status": "active",
    "id": "0x10f6f2b97F3aB29583D9D38BaBF2994dF7220C21"
}

**Comment by TeddyDogeAdmin** [comment]
{   
    "name": "TEDDY",
    "website": "https://teddydoge.finance/",
    "description": "TEDDY is the DEFI ecological token of Teddy Doge with Swap & Cross bridge& Wallet.",
    "explorer": "https://bscscan.com/token/0x10f6f2b97F3aB29583D9D38BaBF2994dF7220C21",
    "type": "BEP20",
    "symbol": "TEDDY",
    "decimals": 18,
    "status": "active",
    "id": "0x10f6f2b97F3aB29583D9D38BaBF2994dF7220C21"
}check info.json，we add tag and link.

**Comment by TeddyDogeAdmin** [comment]
> tags and link

Tags and link all in info.json,but why you delete info.json and logo.png?
Dear？

**Review by TeddyDogeAdmin — COMMENTED** [review]
{
    "name": "Teddy Doge (TEDDY)",
    "type": "BEP20",
    "symbol": "TEDDY",
    "decimals": 18,
    "website": "http://teddydoge.finance/",
    "description": "TEDDY is the DEFI ecological token of Teddy Doge with Swap & Cross bridge& Wallet.",
    "explorer": "https://bscscan.com/token/0x10f6f2b97F3aB29583D9D38BaBF2994dF7220C21",
    "status": "active",
    "id": "0x10f6f2b97F3aB29583D9D38BaBF2994dF7220C21",
    "links": [
        {
            "name": "twitter",
            "url": "https://twitter.com/TeddySwap1/"
        },
        {
            "name": "telegram_news",
            "url": "https://t.me/TeddyDoge_channel"
        },
        {
            "name": "telegram",
            "url": "https://t.me/TeddyDoge_Official"
        },
        {
            "name": "discord",
            "url": "https://discord.gg/Wtjxv5djTu"
        },
        {
            "name": "medium",
            "url": "https://medium.com/@teddydoge"
        },
        {
            "name": "youtube",
            "url": "https://www.youtube.com/channel/UCcD7AsRqhU92IfqTh4SY0kQ"
        },
        {
            "name": "coinmarketcap",
            "url": "https://coinmarketcap.com/currencies/teddydoge/"
        },
        {
            "name": "coingecko",
            "url": "https://www.coingecko.com/en/coins/teddy-doge"
        },
        {
            "name": "whitepaper",
            "url": "https://teddydoge.finance/teddyswap.pdf"
        },
        {
            "name": "github",
            "url": "https://github.com/TeddyDogeAdmin/Teddy-Doge-Code"
        }
    ],
    "tags": [
        "defi"
    ]
}

**Comment by cryptomanz** [comment]
Please create new PR, follow doc https://developer.trustwallet.com/assets/requirements
You may want to try our Assets app in beta; go to https://assets.trustwallet.com, log on with Github, enter contract ID, logo and some additional info, and it will create a PR for you.
See https://developer.trustwallet.com/assets/repository_details

**Comment by cryptomanz** [comment]
Please come back to us when all criteria are met.
When creating a new PR make sure to mention this PR, so that we can see that fee has been paid already here.

**Comment by TeddyDogeAdmin** [comment]
> https://www.youtube.com/channel/UCcD7AsRqhU92IfqTh4SY0kQ

#19559 
THX mate！

**Pull request closed without merging**
