### PR TITLE
Add bernard (BEP20)

### PR DESCRIPTION
**Pull request by bertoloic**
Adding info for BEP20 token 'bernard'.

PR created by <a href="https://assets.trustwallet.com">TW Assets Management</a>

### CODE REVIEW

**Comment by bertoloic** [comment]
it's payed

**Comment by Cryptocool1** [comment]
> it's payed

Payment was not found by the bot; could you provide TXID or date for checking?

**Comment by Cryptocool1** [comment]
paid thanks

**Comment by bertoloic** [comment]
so i cannot see my logo in trust wallet, it's ok ?

**Comment by bertoloic** [comment]
> > it's payed
> 
> Payment was not found by the bot; could you provide TXID or date for checking?

Hello in what time my logo will be available on trust wallet ? 
thanks

**Comment by bertoloic** [comment]
@Cryptocool1  i cannot see our logo on trustWallet, how much time to see ? thanks

**Comment by bertoloic** [comment]
@Cryptocool1 @catenocrypt @zachzwei @hexorx  Sorry but can someone help us? we need logo in app for our community..

**Comment by Cryptocool1** [comment]
> @Cryptocool1 @catenocrypt @zachzwei @hexorx Sorry but can someone help us? we need logo in app for our community..

Please wait

**Pull request merged**
