### PR TITLE
Add Solana initial validator list

### PR DESCRIPTION
**Pull request by CriesofCarrots**
Rebased on melea :)

### CODE REVIEW

**Comment by kolya182** [comment]
Could you add images for next validators:  7NwjYBhHVqEbqmMHqMqUnQ4thomaX9qXytMEULQFkAny, 6yg4Usyr8VkvY8m7wrbLHegKVnKaAQmEwS6cuGnwB6wT

**Comment by CriesofCarrots** [comment]
> Could you add images for next validators: 7NwjYBhHVqEbqmMHqMqUnQ4thomaX9qXytMEULQFkAny, 6yg4Usyr8VkvY8m7wrbLHegKVnKaAQmEwS6cuGnwB6wT

@kolya182 , we haven't received logos from those validators. Should we provide placeholder images?

**Comment by kolya182** [comment]
> > Could you add images for next validators: 7NwjYBhHVqEbqmMHqMqUnQ4thomaX9qXytMEULQFkAny, 6yg4Usyr8VkvY8m7wrbLHegKVnKaAQmEwS6cuGnwB6wT
> 
> @kolya182 , we haven't received logos from those validators. Should we provide placeholder images?

No image no validator.

**Comment by CriesofCarrots** [comment]
#1784

**Pull request merged**
