### PR TITLE
PirateCash token swap

### PR DESCRIPTION
**Pull request by gades**
We did token swap 1:1 from old contract address: [0x35f3fffFcb622bC9f64fA561D74e983Fd488D90c](https://bscscan.com/token/0x35f3ffffcb622bc9f64fa561d74e983fd488d90c), new contract address: [0xaFCC12e4040615E7Afe9fb4330eB3D9120acAC05](https://bscscan.com/token/0xaFCC12e4040615E7Afe9fb4330eB3D9120acAC05).

New SmartContract security audit https://github.com/TechRate/Smart-Contract-Audits/blob/main/January_2024/PirateCash.pdf

https://p.cash/en/tokenswap/

### CODE REVIEW

**Comment by Cryptocool1** [comment]
Is your old contract abandoned for now?

**Comment by gades** [comment]
yes, and we've liquidity bridge https://pancakeswap.finance/swap?inputCurrency=0x35f3fffFcb622bC9f64fA561D74e983Fd488D90c&outputCurrency=0xaFCC12e4040615E7Afe9fb4330eB3D9120acAC05  for swap old tokens to new and on CMC / GECKO is warning message about swap

**Comment by gades** [comment]
@Cryptocool1 

When old contract will disappear from search and new contract will show token price?


IMG_1585
IMG_1584

**Comment by gades** [comment]
@Cryptocool1 @cryptomanz1 

IMG_2876


After update contract ID the token price doesn't show it , WHY ?

Screenshot 2024-04-23 at 12 10 58

https://bscscan.com/token/0xaFCC12e4040615E7Afe9fb4330eB3D9120acAC05

**Pull request merged**
