### PR TITLE
Fixing logo size fees paid in #21705

### PR DESCRIPTION
**Pull request by maxvolovikov**
Fixing logo size fees paid in #21705

### CODE REVIEW

**Comment by maxvolovikov** [comment]
@Cryptocool1 i am trying to make sure that the white boarded is not showing, how can i upload a logo without that boarder? 
we paid fees in #21705 but it seems that logo is still wrong size? or positioned wrong.

Screen Shot 2022-08-05 at 5 11 20 PM

**Comment by Cryptocool1** [comment]
Снимок экрана 2022-08-07 в 15 05 33
Please delete that file

**Comment by trastvolt** [comment]
TradingSession:master

**Comment by maxvolovikov** [comment]
@Cryptocool1 sorry trying to figure out how to do this :(

**Review by maxvolovikov — COMMENTED** [review]
@Cryptocool1 did this solve the problem?

**Comment by Cryptocool1** [comment]
> @Cryptocool1 did this solve the problem?

I will create the PR and fix you logo soon

**Comment by maxvolovikov** [comment]
@Cryptocool1 When you visit New Orleans let me know i owe you a drink lol

**Pull request closed without merging**
