### PR TITLE
Add Precatorio RMDSP01

### PR DESCRIPTION
**Pull request by saintclair**
Add Precatorio RMDSP01

### CODE REVIEW

**Comment by kolya182** [comment]
Why would you want to replace ethereum logo ?

**Comment by saintclair** [comment]
Fixed

**Comment by kolya182** [comment]
@saintclair Thanks, the reason i asked, i noticed a few other contributors also did the same, is anything i can change in guidelines to make process more clear ?

**Comment by saintclair** [comment]
I understand, in the folder structure (tree) the logo.png could have another name in the info because the user thinks it has to put in both places.

**Comment by kolya182** [comment]
> I understand, in the folder structure (tree) the logo.png could have another name in the info because the user thinks it has to put in both places.

Hope this help https://github.com/trustwallet/assets/commit/826862f0d90989c1f9c092e176ad4c64ce143443

**Comment by saintclair** [comment]
@kolya182 Now I guess so, it's clear, taking advantage of when you think it's available in my app?

**Pull request merged**
