### PR TITLE
Add Affinity (BEP20)

### PR DESCRIPTION
**Pull request by Azacora**
Adding info for BEP20 token 'Affinity'.

PR created by <a href="https://assets.trustwallet.com">TW Assets Management</a>

### CODE REVIEW

**Comment by Cryptocool1** [comment]
Your holders seems to be artificial (the first transaction was 2 days ago) 
Thanks for your interest, you can summit your token later again

**Comment by Azacora** [comment]
This is to update our token "Affinity", we migrated from our V1 token SafeAffinity. These changes are noted on coinmarketcap.

**Comment by Azacora** [comment]
CMC: https://coinmarketcap.com/currencies/safeaffinity/
Tweet that was put out from the official account about migration: https://twitter.com/AffinityBSC/status/1568839631134752768

**Comment by Cryptocool1** [comment]
submission looks good, awaiting for the fee payment

**Comment by cryptomanz1** [comment]
#22382

**Comment by Azacora** [comment]
Is the logo needs to be adjusted will this be a new PR?

**Pull request merged**
