### PR TITLE
Add GLMS logo and info

### PR DESCRIPTION
**Pull request by glimpsenft**
Submitting our token information and logo to be added to Trust Wallet.

### CODE REVIEW

**Comment by glimpsenft** [comment]
Hello - here is the contribution transaction of 1,000 TWT

https://explorer.binance.org/tx/F553CE6CA4F680D8AF11EB8F34E531FF26BE16871BD8D00D40313EFE45E607DC

**Comment by Cryptocool1** [comment]
could you add the links?
see the example here: https://developer.trustwallet.com/assets/repository_details

**Comment by glimpsenft** [comment]
> could you add the links? see the example here: https://developer.trustwallet.com/assets/repository_details

Links have been added to the info.json file. Thank you.

**Comment by Cryptocool1** [comment]
• What is the purpose of this token? How will it benefit Trust Wallet users?
 • How is the token being distributed? Are you conducting an airdrop?
 • Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?
 • Is the token listed on a centralized/decentralized exchange?
 • Is a Smart Contract audit completed? Where can we find this information?

**Comment by glimpsenft** [comment]
> • What is the purpose of this token? How will it benefit Trust Wallet users? • How is the token being distributed? Are you conducting an airdrop? • Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale? • Is the token listed on a centralized/decentralized exchange? • Is a Smart Contract audit completed? Where can we find this information?

This token is the primary method of payment on the Glimpse platform used to buy/sell/trade NFT's. Currently users are staking it to gain access to the platform as a beta user and earn interest. 

The token was launched via an IDO on BSCPad September 6th 2021. 

The token is listed on PS

The code has been audited by Omniscia -please see link here https://omniscia.io/glimpse-bsc-eth-token/ (note we decided to only launch the token on BSC due to high gas fees on ETH). 

Please let me know if any further info is needed. Thank you!

**Pull request merged**
