### PR TITLE
Add Binance Smart Chain Girl  (BEP20)

### PR DESCRIPTION
**Pull request by takuro020301**
Adding info for BEP20 token 'Binance Smart Chain Girl '.

PR created by <a href="https://assets.trustwallet.com">TW Assets Management</a>

### CODE REVIEW

**Comment by Cryptocool1** [comment]
As per our policy, brand new tokens are not included, there is a minimum requirement of 2500 holder addresses and 5000 transactions, in order to filter out scam tokens.
See the criteria at (mentioned in the first message by the bot): https://community.trustwallet.com/t/how-to-submit-a-token-logo/3863).

**Comment by takuro020301** [comment]
with this, Will the Binance Smart Chain Girl token logo be added to my trust wallet?

**Comment by takuro020301** [comment]
with this, Will the Binance Smart Chain Girl token logo be added to my
trust wallet?

2021年5月19日(水) 午前3:33 CryptoA ***@***.***>:

**Comment by Cryptocool1** [comment]
Hello,
we can merge this PR when you will meet our criteria

**Comment by takuro020301** [comment]
> こんにちは、
> 私たちはあなたが私たちの基準を満たすときにこのPRをマージすることができます

After the number of holders exceeds 2500 Can I add the token logo if I reapply?

**Comment by Cryptocool1** [comment]
> > こんにちは、
> > 私たちはあなたが私たちの基準を満たすときにこのPRをマージすることができます
> 
> After the number of holders exceeds 2500 Can I add the token logo if I reapply?

sure, you can close this PR now, and then open new one. Make sure to mention this PR, so that we can see that fee has been paid already here.

**Comment by takuro020301** [comment]
> > > こんにちは、
> > > 私たちはあなたが私たちの基準を満たすときにこのPRをマージすることができます
> > 
> > 
> > After the number of holders exceeds 2500 Can I add the token logo if I reapply?
> 
> sure, you can close this PR now, and then open new one. Make sure to mention this PR, so that we can see that fee has been paid already here.

Thank you very much. Thank you again

**Comment by Cryptocool1** [comment]
Please create new PR, follow doc https://community.trustwallet.com/t/how-to-submit-a-token-logo/3863
You may want to try our new Assets app in beta; go to https://assets.trustwallet.com, log on with Github, enter contract ID, logo and some additional info, and it will create a PR for you.
See https://community.trustwallet.com/t/how-to-submit-a-token-logo-using-assets-app/82957.
When creating new PR, mention this PR, so that fee can be reused, and not paid again.

**Pull request closed without merging**
