### PR TITLE
Add Floki Inu token details and logo

### PR DESCRIPTION
**Pull request by ghost**

### CODE REVIEW

**Comment by Cryptocool1** [comment]
hello,
• What is the purpose of this token? How will it benefit Trust Wallet users?
 • How is the token being distributed? Are you conducting an airdrop?
 • Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?
 • Is the token listed on a centralized/decentralized exchange?
 • Is a Smart Contract audit completed? Where can we find this information?

**Comment by sohailamir** [comment]
Hello,

Please see responses to your questions below.

• What is the purpose of this token? How will it benefit Trust Wallet users?

It's a meme coin based on the name of Elon Musk's dog. A lot of Trust Wallet users hold FLOKI already and requested that we reach out to you so they can easily have information about their tokens in Trust Wallet.

• How is the token being distributed? Are you conducting an airdrop?

People buy the token on the Uniswap DEX.

• Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?

There was no presale.

• Is the token listed on a centralized/decentralized exchange?

Yes, the token is listed on Uniswap.

• Is a Smart Contract audit completed? Where can we find this information?

Yes, the token is audited by Solidity Finance: https://solidity.finance/audits/FLOKI/ <https://solidity.finance/audits/FLOKI/>

Kind Regards,

The Floki Inu Team

**Comment by cryptomanz** [comment]
are you listed on coingecko/CMC?

**Comment by sohailamir** [comment]
Yes, we are listed on both CG/CMC.

https://www.coingecko.com/en/coins/floki-inu <https://www.coingecko.com/en/coins/floki-inu>

https://coinmarketcap.com/currencies/floki-inu/ <https://coinmarketcap.com/currencies/floki-inu/>

**Comment by sohailamir** [comment]
Hi there,

I've made a small mistake in the info.json file.

The name should read as "Floki Inu", not "Folk Inu".

Sorry and appreciate the assistance in advance!

**Comment by Cryptocool1** [comment]
#11976

**Comment by sohailamir** [comment]
Hi Nazar,

Made a very slight mistake in the json.info <http://json.info/> file the name should read as “Floki Inu”.

Same thing goes with the name in the token description too it says Folk Inu instead of Floki Inu.

Instead I must have mistyped the name as “Folk Inu” due to auto correct.

Would appreciate if you could help me with get the mistakes.

Many thanks,

Floki Inu Team

**Comment by Cryptocool1** [comment]
https://github.com/trustwallet/assets/pull/11976
fixed

**Comment by sohailamir** [comment]
Yes I saw that thank you it’s actually just the description where the name needs to be updated also.

I’m SO sorry to be a pain. Just want it to look perfect for our fellow Trust Wallet users.

Apologies on my side again for the inconvenience!

**Comment by cryptomanz** [comment]
#12012 fixed

**Pull request merged**
