### PR TITLE
AXIS Token logo and information update

### PR DESCRIPTION
**Pull request by laneaxis**

### CODE REVIEW

**Comment by Cryptocool1** [comment]
Hello,
Your type should be ETH20

**Comment by laneaxis** [comment]
> Hello,
> Your type should be ERC20

Thanks for the help and confirmation.
[0xF0c5831EC3Da15f3696B4DAd8B21c7Ce2f007f28.zip](https://github.com/trustwallet/assets/files/6446185/0xF0c5831EC3Da15f3696B4DAd8B21c7Ce2f007f28.zip)


I've changed the type from COIN to ERC20,
And uploaded a zip file as a commit, Please do let us know if something else we need to do.

If you can share any doc to follow in case of failure that will be awesome.

**Comment by catenocrypt** [comment]
Correction needed:  token type is still `COIN`, should be `ERC20`.

image

**Comment by laneaxis** [comment]
> Correction needed: token type is still `COIN`, should be `ERC20`.
> 
> image

Hello Dear,

I have did the all needed changes in the file and updated it once again.
Please check it and do let us know if you need more details.

**Pull request merged**
