### PR TITLE
Uploading info and logo for $BAM—migrating from $PINKPANDA

### PR DESCRIPTION
**Pull request by jshaust**
On the 28th of May, we finished the initial migration from $PINKPANDA to $BAM. We have over 12,000 holders between the two tokens and are migrating more daily. Please see our website and socials for legitimacy. We would love your help in updating Bamboo to keep our Trust Wallet users safe from scams.

### CODE REVIEW

**Comment by jshaust** [comment]
Hey there, I hope this isn't seen as spam. Requested again to update with the appropriate information. We are migrating.

**Comment by cryptomanz** [comment]
can you send an official announcement about migration ?

**Comment by jshaust** [comment]
I'll attach our website, a link to our Medium, and a link to our Twitter below. They'll each state that we're in this migration. 
1. https://pinkpanda.io/ , 
2. https://medium.com/@PinkPandaFinance/bam-is-now-trading-migration-redemption-is-open-cac8596d0cdb , 
3. https://twitter.com/PinkPandaDefi 

Let me know if anymore information would be helpful.

**Comment by jshaust** [comment]
What else can we provide to move forward?

**Comment by cryptomanz** [comment]
We require an official announcement in bsc scan.

**Comment by jshaust** [comment]
Thank you, I'll get us started on that.

**Comment by jshaust** [comment]
Ah, did you look at our info page on bsc scan? It has an announcement regarding the migration we're currently in. I'll attach that link below.

https://bscscan.com/token/0x631e1e455019c359b939fe214edc761d36bf6ad6#tokenInfo

**Comment by Cryptocool1** [comment]
Thank you

**Comment by cryptomanz** [comment]
#20774

**Pull request merged**
