### PR TITLE
Add DYP (ERC20, BEP20, ARC20)

### PR DESCRIPTION
**Pull request by doyledyp**

### CODE REVIEW

**Comment by Cryptocool1** [comment]
Can you please send a screenshot

**Comment by doyledyp** [comment]
photo_2023-03-23_12-48-41

**Comment by doyledyp** [comment]
photo_2023-03-23_14-57-49

**Comment by doyledyp** [comment]
Hello again! I think it is some sort of a bug, these screenshots are from 3 different iPhones, all of them with version 8.4 TrustWallet. Don't quite understand what is happening. Maybe this can help you to figure it out. Thank you!

**Comment by Cryptocool1** [comment]
Please try to clear your cache

**Pull request merged**
