### PR TITLE
Add Inferno (BEP20)

### PR DESCRIPTION
**Pull request by lovetrading10**
Adding info for BEP20 token 'Inferno'.

PR created by <a href="https://assets.trustwallet.com">TW Assets Management</a>

### CODE REVIEW

**Comment by cryptomanz** [comment]
Hello,
Can your answer some questions?
• What is the purpose of this token? How will it benefit Trust Wallet users?
 • How is the token being distributed? Are you conducting an airdrop?
 • Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?
 • Is the token listed on a centralized/decentralized exchange?
 • Is a Smart Contract audit completed? Where can we find this information?

**Comment by lovetrading10** [comment]
• What is the purpose of this token? How will it benefit Trust Wallet users? 
     Token is a form of currency on the BSC used for creating and paying for content and NFT at all4fans.com 

• How is the token being distributed? Are you conducting an airdrop?  
    Air drop was conducted 

• Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale? 
     ICO was done on dx app

• Is the token listed on a centralized/decentralized exchange? 
    Pancake swap 

• Is a Smart Contract audit completed? Where can we find this information? 
    it has not been done yet we are on the waiting list

**Comment by cryptomanz** [comment]
- Awaiting for smart contract audit.

**Comment by lovetrading10** [comment]
Until now, I have deployed several tokens on trustwallet without this problem.

**Comment by lovetrading10** [comment]
Other guys didn't request these.

**Comment by cryptomanz** [comment]
> Until now, I have deployed several tokens on trustwallet without this problem.

Please, follow rules adding tokens, full information about this can be found in our documentation: https://community.trustwallet.com/t/how-to-submit-a-token-logo/3863
Screenshot 2021-09-11 at 10 39 01

**Comment by lovetrading10** [comment]
I gotcha.
I will update you asap.

**Comment by Cryptocool1** [comment]
please create new PR, when smart contract audit will be ready. Make sure to mention this PR, so the fee can be reused.

**Comment by lovetrading10** [comment]
okay 
I need to add the token to trustwallet, definitely.
I will update you asap.
Thank you.

**Pull request closed without merging**
