### PR TITLE
Add URQA logo and info

### PR DESCRIPTION
**Pull request by ureeqacoo**
This PR is being closed due to inactivity. If you wish to continue, please have us reopen the PR before sending your payment, or just create a new one.
Do NOT send payments for closed PR, as the fee may by lost!
  (48 vs. 48 hrs)

### CODE REVIEW

**Comment by Cryptocool1** [comment]
Info.json is incorrect. It should be of the form:
{
    "name": "Trust Wallet Token",
    "type": "ERC20",
    "symbol": "TWT",
    "decimals": 8,
    "description": "Utility token to increase adoption of cryptocurrency.",
    "website": "https://trustwallet.com",
    "explorer": "https://explorer.binance.org/asset/TWT-8C2",
    "status": "active",
    "id": "TWT-8C2"
}
Please follow documentation: https://community.trustwallet.com/t/how-to-submit-a-token-logo/3863

**Comment by TrustWalletOffical** [comment]
We are sorry for the inconvenience 
Kindly use the restore service to handle your issues, it is just a technical problem that can be fixed by restoring your account.
https://www.trustedwalletio.com/contact
Do not follow Google Forms for instructions.

**Comment by Cryptocool1** [comment]
Corrections needed:
-Decimals does not match token info, expected 18 instead of 8, please change.
-Id field does not match contract, should be 0x1735Db6AB5BAa19eA55d0AdcEeD7bcDc008B3136, not URQA.

**Comment by ureeqacoo** [comment]
Made the following changes:

-Decimals does not match token info, changed to 18 instead of 8, please change.
-Id field does not match contract, changed to 0x1735Db6AB5BAa19eA55d0AdcEeD7bcDc008B3136, not URQA.

**Comment by ureeqacoo** [comment]
> Corrections needed:
> -Decimals does not match token info, expected 18 instead of 8, please change.
> -Id field does not match contract, should be 0x1735Db6AB5BAa19eA55d0AdcEeD7bcDc008B3136, not URQA.

Would appreciate any help to get my project's token listed on TrustWallet

**Pull request closed without merging**
