### PR TITLE
PLEASE UPDATE MNOER LOGO

### PR DESCRIPTION
**Pull request by mnoerinc**
I HAVE CHANGED THE LOGO QUALITY........... PLEASE UPDATE

### CODE REVIEW

**Comment by kolya182** [comment]
Which one exactly is latest ?.

**Comment by mnoerinc** [comment]
> Which one exactly is latest ?.

NEW LOGO MNR

**Comment by mnoerinc** [comment]
Hi,
Thank you so much for replying

**Comment by kolya182** [comment]
Make clean PR

**Pull request closed without merging**
