### PR TITLE
[Rejected] - Add Resfinex Token RES and Info

### PR DESCRIPTION
**Pull request by resfinex**
We would like to add our RES token into your Trust Wallet app. Please help us process, if you need any info just let us know. Thanks Team.

Resfinex Team

### CODE REVIEW

**Comment by resfinex** [comment]
Please check the payment. We have paid 250 TWT with memo 4514. Thanks Team!

**Comment by catenocrypt** [comment]
`Info.json` is not a valid JSON file, last item has a wrong trailing comma.
Please fix.

**Comment by Iamdeadlyz** [comment]
In accordance with our [disclaimer](https://github.com/trustwallet/assets#disclaimer), your PR is denied due to the following reason:
- Copy pasted information
image
image

**Comment by resfinex** [comment]
> In accordance with our [disclaimer](https://github.com/trustwallet/assets#disclaimer), your PR is denied due to the following reason:
> 
> * Copy pasted information
>   image
>   image
>   image
>   image

Hi @Iamdeadlyz,

Could you please review again, some info duplicated, but we do not think your team need to tag us as fraud. We are not aware it is duplicated. We still can change and update those info in order to accordance with your guidelines. 

Regards,
Resfinex Team

**Comment by resfinex** [comment]
All info as you see it public on the web and some is like a standard. It is not fair if you just based on that and tag us a fraud. We are here to collaborate and work with your team. If anything is not align, just reject but not a 'Fraud' for our project. Thanks Team.

Regards,
Resfinex Team

**Comment by Iamdeadlyz** [comment]
The intent to mislead is noticeable. You even got the whitepaper of Ethfinex.

**Comment by resfinex** [comment]
Hi @Iamdeadlyz ,

The whitepaper of Ethfinex is longer and our team just learn from some parts, not like you said we got the whitepaper of Ethfinex. We belive that you use 'Fraud' in this context is not appropriate with our team. We apply on Trust wallet just get list or reject. Not a place to label or judge a project 'FRAUD' or not, especially on behalf of individual.

Regards,
Resfinex Team

**Pull request closed without merging**
