### PR TITLE
Add BiffysLove (LOVE) Asset

### PR DESCRIPTION
**Pull request by ethereal-nfts**
Adds logo for BiffysLove.
Because almost all LOVE is deposited into the Love Farm as Uni Love/ETH LP, the holders count is low.

### CODE REVIEW

**Comment by ethereal-nfts** [comment]
https://explorer.binance.org/tx/A33CF161487B4B7E1028A19FD32FA66B7C05648F8C5DEFF7FC4EFD24329FE908
Payment of 2.1968 BNB made.

**Comment by vikmeup** [comment]
As per our updated policy, brand new tokens are not included, there is a minimum requirement 

- at least 100 token holders
- at least 500 transactions

See our [How to Get Submit Token Logo ](https://community.trustwallet.com/t/how-to-submit-a-token-logo/3863#how-to-get-approved) guidelines.

Feel free to re-open once you meet those requirements.

----------

Can you please include `info.json` file for the token. 

Here is an example for DAI: https://github.com/trustwallet/assets/blob/master/blockchains/ethereum/assets/0x6B175474E89094C44Da98b954EedeAC495271d0F/info.json

**Comment by ethereal-nfts** [comment]
https://etherscan.io/token/0xf7F35Fe2ede3aDDee7Cf176f4Ef20D9436E498dc
143 Holders
1847 Transfers
Also, it is a yield farming token so most users are staking LP Love/ETH tokens on Uniswap.

**Comment by ethereal-nfts** [comment]
Bumping to keep active, info.json is active and holder requirements are met.

**Comment by ethereal-nfts** [comment]
@vikmeup

**Pull request merged**
