### PR TITLE
Migrate and add HyperChainX (BEP20)

### PR DESCRIPTION
**Pull request by xcyberdragonx**
Adding info for BEP20 token 'HyperChainX'.

PR created by <a href="https://assets.trustwallet.com">TW Assets Management</a>

### CODE REVIEW

**Comment by xcyberdragonx** [comment]
The token is migrating from: (https://github.com/trustwallet/assets/pull/13375)

**Comment by Cryptocool1** [comment]
hello, please send an official announcement about migration

**Comment by xcyberdragonx** [comment]
@

**Comment by xcyberdragonx** [comment]
> hello, please send an official announcement about migration

whitepaper link:
https://hyperchainx.gitbook.io/whitepaper/project-details/project-links

Migration instruction link:
https://hyperchainx.gitbook.io/migration/

Twitter announcement:
https://twitter.com/HyperchainX/status/1587427482864689153

Couldn't find the other twitter announcements because they are buried too deep. We have a special button in telegram too for it.  I made a new twitter announcement specifically for the request too. The whitepaper link is onsite to.

**Comment by Cryptocool1** [comment]
Submission looks good, awaiting for the fee payment

**Comment by xcyberdragonx** [comment]
> Submission looks good, awaiting for the fee payment

Paying a fee again? Never had to do that with updating a token.

**Comment by Cryptocool1** [comment]
you can see fee requirements here: https://developer.trustwallet.com/assets/pr-fee

**Comment by xcyberdragonx** [comment]
> you can see fee requirements here: https://developer.trustwallet.com/assets/pr-fee

Yes I see, thanks.

**Comment by Harmzey17** [comment]
I need to know more about github

**Pull request closed without merging**
