### PR TITLE
Add New  FWC LOGO and New INFO

### PR DESCRIPTION
**Pull request by Fwc-Token**
New LOGO 
New NAME

### CODE REVIEW

**Comment by Fwc-Token** [comment]
Please fix that errors
You can verify the email in CMC/CG
community@fwctoken.io
*The previous email and previous domain have been changed*

**Comment by Fwc-Token** [comment]
Hi
Please check (fix errors)
The previous email and previous domain have been changed
You can verify the email in CMC/CG
Email: community@fwctoken.io
Website: https://fwctoken.io
Thank you

**Comment by Cryptocool1** [comment]
Please create new PR, follow doc https://developer.trustwallet.com/assets/requirements
You may want to try our Assets app in beta; go to https://assets.trustwallet.com, log on with Github, enter contract ID, logo and some additional info, and it will create a PR for you.
See https://developer.trustwallet.com/assets/repository_details

**Comment by Cryptocool1** [comment]
make sure to mention this PR in new one, so the fee can be reused

**Comment by Fwc-Token** [comment]
Hi
Please check (fix errors)
The previous email and previous domain have been changed
You can verify the email in CMC/CG
https://www.coingecko.com/en/coins/football-world-community
Email: community@fwctoken.io
Website: https://fwctoken.io/
Thank you

**Comment by Fwc-Token** [comment]
> make sure to mention this PR in new one, so the fee can be reused

Hi
Please check (fix errors)
Why did you not approve the request? All of the above are true
These items are mentioned in the road map
Please confirm the above information
https://www.coingecko.com/en/coins/football-world-community
The previous email and previous domain have been changed
You can verify the email in CMC/CG
https://www.coingecko.com/en/coins/football-world-community
Email: [community@fwctoken.io](mailto:community@fwctoken.io)
Website: https://fwctoken.io/
Thank you

**Comment by Fwc-Token** [comment]
Where are you?

**Comment by Fwc-Token** [comment]
https://github.com/Cryptocool1
Where are you?

**Comment by Cryptocool1** [comment]
You should create new PR following my message above

**Pull request closed without merging**
