### PR TITLE
updating token contracts and logo

### PR DESCRIPTION
**Pull request by aliarzani**
Please update old contract address to new on and change its logo. 

old

0x9513d8679677be3d57c7cdd30561105ee1452d69

------------------------------------------

new

0xc5bb5ec4d6d69f32b6cb5b7766fd5f4ec946c58a

### CODE REVIEW

**Comment by catenocrypt** [comment]
Logo file is missing (maybe lost in merge).  Please re-create PR.

**Comment by aliarzani** [comment]
hello again

**Comment by aliarzani** [comment]
> Logo file is missing (maybe lost in merge). Please re-create PR.

i deleted it myself old logo. i wonder if updating also need approving by trustwallet also and trustwallet may reject my request?

**Comment by catenocrypt** [comment]
Create new PR:
- remove old logo files (logo, info)
- add new logo files to folder with new contract ID -- should be in checksum format (logo, file).  Moving of the files is even better
- we check the PR
- pay the fee
- we merge

**Pull request closed without merging**
