### PR TITLE
Chess Logo

### PR DESCRIPTION
**Pull request by Chessfarmtech**
Chessfarm.tech "Chess" token logo.Thank you

### CODE REVIEW

**Comment by Iamdeadlyz** [comment]
As per our policy, brand new tokens are not included. There is a minimum requirement of 2500 holder addresses and 5000 transactions (airdropped tokens excluded) in order to filter out scam tokens. See the criteria at (mentioned in the first message by the bot): https://community.trustwallet.com/t/how-to-submit-a-token-logo/3863#how-to-get-approved

This token has below-limit usage yet. This pull request will be put on hold. Please come back to us when all criteria are met.
https://bscscan.com/token/0x02F92A9C381BDeA49bDE29a8277666c73E60C88d (23, 464) `5̶8̶7̶,̶ ̶1̶0̶2̶8̶`

**Comment by Chessfarmtech** [comment]
Okay,but if transcctions is normal,we really only started,then holders-only few BSC projects have that value.and most you add even recently have <100 holders if to see real...like that or that
https://bscscan.com/token/0x3abfc084a54e5f4e23196e1b9a9c48c3b3021519#balances
https://bscscan.com/token/0x78e1936f065fd4082387622878c7d11c9f05ecf4#balances
But anyway thanks-put us on hold and we will write a bit after we grow:)

**Comment by Chessfarmtech** [comment]
We got many active users and bscscan verified and included in yield-section.would appreciate much if u manage things with our logo,thank you.
https://www.bscscan.com/yieldfarms

**Comment by Iamdeadlyz** [comment]
> We got many active users and bscscan verified and included in yield-section.would appreciate much if u manage things with our logo,thank you.
> https://www.bscscan.com/yieldfarms

That is simply an aggregator for existing farms in the BSC network. You need to reach the proper requirements as indicated in my previous response.

**Comment by Chessfarmtech** [comment]
MOST of all coins you accepted do not fill that requirements even now.only few coins like TWT,Bake,Cake,Dego and 1-2(!) more in the whole bsc network(except crosschain big ones) have more then 2.5K real holders of not airdropped and not staked coins.
Is it fair to some and unfair to others?

**Comment by Iamdeadlyz** [comment]
> MOST of all coins you accepted do not fill that requirements even now.only few coins like TWT,Bake,Cake,Dego and 1-2(!) more in the whole bsc network(except crosschain big ones) have more then 2.5K real holders of not airdropped and not staked coins.
> Is it fair to some and unfair to others?

If you try to find their respective PRs, you can see that the requirements at that time were low. Do your best with reaching the said requirements, cheers.

**Comment by vikmeup** [comment]
https://chessfarm.tech/ does not work. Come back later and reopen pull request.

**Comment by quangtrungcntt** [comment]
feed a bunch of scammers. Many investors have lost all their money

**Pull request closed without merging**
