### PR TITLE
Add Logo + Info to Xenon Play [Urgent]

### PR DESCRIPTION
**Pull request by keesxenon**
Please Add Logo + Info to Xenon Play [Urgent]  Contract: 0xB7FeEAb5ea787e83a40f185237C717597363E0d6 Thanks in advance!

### CODE REVIEW

**Comment by keesxenon** [comment]
Fixed!

**Comment by cryptomanz** [comment]
Can your answer some questions?
• What is the purpose of this token? How will it benefit Trust Wallet users?
 • How is the token being distributed? Are you conducting an airdrop?
 • Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?
 • Is the token listed on a centralized/decentralized exchange?
 • Is a Smart Contract audit completed? Where can we find this information?

**Comment by keesxenon** [comment]
• Xenon Play functions as the official Xenon Pay (X2P) Reward token that can be generated from the Xenon Machine after activating the reward mechanism by inserting Xenon Liquidity Tokens or Xenon Pay Tokens. You can also use Xenon Play in the upcoming Xenon Pay Gaming Series such as Xenon Kart: Crypto Edition or Xenon Play: Minigames. Both games will have a Play To Earn game mode.

It’s up to each individual whether they keep their Xenon Play (rewards) to use them in the upcoming games or if they treat it like a trading crypto asset. The fact that it can be treated like a trading crypto asset also gives each individual the chance to sell their Xenon Play (rewards) whenever they want, or give other people the chance to buy Xenon Play if they would like to do so.

• 50% of our holders are airdropped and 50% of our holders bought after launch +-

• There was a private sale to raise enough liquidity and create a stable floor

• The token is listed on PancakeSwap (Dex) XPLAY/BNB Pair

• We have completed a audit by DessertFinance which you can find on their website

> Can your answer some questions? • What is the purpose of this token? How will it benefit Trust Wallet users? • How is the token being distributed? Are you conducting an airdrop? • Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale? • Is the token listed on a centralized/decentralized exchange? • Is a Smart Contract audit completed? Where can we find this information?

**Comment by keesxenon** [comment]
[Uploading XPlay BSC Audit 11671794.pdf…]()

**Pull request merged**
