### PR TITLE
Add UnityMeta Token (BEP20)

### PR DESCRIPTION
**Pull request by unitymetatoken**
Adding info for BEP20 token 'UnityMeta Token'.

PR created by <a href="https://assets.trustwallet.com">TW Assets Management</a>

### CODE REVIEW

**Comment by unitymetatoken** [comment]
Hey any more info need

**Comment by unitymetatoken** [comment]
Hi Everything is Right

**Comment by unitymetatoken** [comment]
please support us

**Comment by roymoses07** [comment]
Approve

**Comment by roymoses07** [comment]
unitymetatoken:br0306-162916

**Comment by unitymetatoken** [comment]
can i close this pull because want to create new one 

because coinmarket cap link not added on this pull

**Comment by unitymetatoken** [comment]
any more info you need sir

**Comment by unitymetatoken** [comment]
can i pay

**Pull request closed without merging**
