### PR TITLE
Add GAMMA (BEP20)

### PR DESCRIPTION
**Pull request by defininja**
Adding info for BEP20 token 'GAMMA'.

PR created by <a href="https://assets.trustwallet.com">TW Assets Management</a>

### CODE REVIEW

**Comment by Cryptocool1** [comment]
Please create new PR, follow doc https://community.trustwallet.com/t/how-to-submit-a-token-logo/3863
You may want to try our Assets app in beta; go to https://assets.trustwallet.com, log on with Github, enter contract ID, logo and some additional info, and it will create a PR for you.
See https://community.trustwallet.com/t/how-to-submit-a-token-logo-using-assets-app/82957.

**Comment by defininja** [comment]
@Cryptocool1 - I created this PR using the trust wallet assets app. Any reason why you are asking me to raise a new PR again?

**Comment by Cryptocool1** [comment]
you have 4 files instead of 2. 2 of them are incorrect

**Comment by Cryptocool1** [comment]
As per our policy, brand new tokens are not included, there is a minimum requirement of 25,000 holder addresses and 50,000 transactions, in order to filter out scam tokens.
See the criteria at : https://developer.trustwallet.com/assets/requirements .

**Comment by defininja** [comment]
@Cryptocool1 - I understand your point. However, as per your guidelines, the minimum requirements of 25,000 holders is subjected to review based on the project. Ours is the sixth-largest DEX in Binance Smart Chain. Our first token, AQUA is already listed by you which doesn't have 25000 holders. Many people in our community use Trust Wallet and it's important that GAMMA shows correctly. Can you please approve? 

Supporting info - 

- GAMMA is listed on CoinGecko - https://www.coingecko.com/en/coins/green-planet
- Our protocol already has ~ $650 million total value locked in it
   - https://blue.planetfinance.io/
   - https://green.planetfinance.io/
   - https://defillama.com/protocol/planet-finance
- Our other asset AQUA is already listed in Trustwallet assets (https://github.com/trustwallet/assets/tree/master/blockchains/smartchain/assets/0x72B7D61E8fC8cF971960DD9cfA59B8C829D91991)
- I have also transferred 1000 TWT - -
   https://explorer.binance.org/tx/AE9E26152451984C3BA0EBBF842179DC5A12DAD2E34E5EFDF61159CEF378E992
- Few credible articles on BSC.new
   - https://www.bsc.news/post/green-planet-the-first-decentralized-money-market-with-discount-levels
    - https://www.bsc.news/post/planet-finance-bringing-defi-to-the-next-billion-users

Thank you!

**Pull request merged**
