### PR TITLE
Add Wrapped USDT SOLP2P (BEP20)

### PR DESCRIPTION
**Pull request by jorzhikgit**
Adding info for BEP20 token 'Wrapped USDT SOLP2P'.

PR created by <a href="https://assets.trustwallet.com">TW Assets Management</a>

### CODE REVIEW

**Comment by jorzhikgit** [comment]
we are ready to provide all the materials that are required

**Comment by jorzhikgit** [comment]
This pull request again https://github.com/trustwallet/assets/pull/29925

**Comment by jorzhikgit** [comment]
I pay already

**Comment by Cryptocool1** [comment]
After careful review of your submission, it looks like this token is just a copy of an existing project. Plagiarism will not be tolerated. The request will be closed until further notice.

**Pull request closed without merging**
