### PR TITLE
Token Add Logo

### PR DESCRIPTION
**Pull request by berataydogdu47**
I just created this token. I've done my procedures to add a logo to the token. I'd be grateful if you'd agree.

### CODE REVIEW

**Comment by berataydogdu47** [comment]
254 TWT Sending / add for logo caretta finance

**Comment by berataydogdu47** [comment]
I just created this token. I've done my procedures to add a logo to the token. I sent 252 TWT.

**Comment by berataydogdu47** [comment]
I created Logo files and paid the fee is there anything else I need to do

**Comment by Cryptocool1** [comment]
This is a BEp20 token, correct folder is blockchains/smartchain/assets. Please correct.
As per our policy, brand new tokens are not included, there is a minimum requirement of 2500 holder addresses and 5000 transactions, in order to filter out scam tokens.
See the criteria at: https://community.trustwallet.com/t/how-to-submit-a-token-logo/3863).

**Comment by berataydogdu47** [comment]
I paid the logo fee, you would like to transfer 2500 holder 5000 if I do this logo will be added automatically ?

**Comment by berataydogdu47** [comment]
bnb180g30wztu7ug9xyeggscy92m7jr7nyrqplj0ad

I want to make a refund, you throw it in my wallet

**Comment by Cryptocool1** [comment]
This is a BEp20 token, correct folder is blockchains/smartchain/assets.

Please create new PR, follow doc https://community.trustwallet.com/t/how-to-submit-a-token-logo/3863
You may want to try our new Assets app in beta; go to https://assets.trustwallet.com, log on with Github, enter contract ID, logo and some additional info, and it will create a PR for you.
See https://community.trustwallet.com/t/how-to-submit-a-token-logo-using-assets-app/82957.

**Comment by Cryptocool1** [comment]
This is a BEp20 token, correct folder is blockchains/smartchain/assets.

Please create new PR, follow doc https://community.trustwallet.com/t/how-to-submit-a-token-logo/3863
You may want to try our new Assets app in beta; go to https://assets.trustwallet.com, log on with Github, enter contract ID, logo and some additional info, and it will create a PR for you.
See https://community.trustwallet.com/t/how-to-submit-a-token-logo-using-assets-app/82957.

**Pull request closed without merging**
