### PR TITLE
Add yAxis

### PR DESCRIPTION
**Pull request by ducpin**

### CODE REVIEW

**Comment by Iamdeadlyz** [comment]
As per our policy, brand new tokens are not included. There is a minimum requirement of 2500 holder addresses and 5000 transactions (airdropped tokens excluded) in order to filter out scam tokens. See the criteria at (mentioned in the first message by the bot): https://community.trustwallet.com/t/how-to-submit-a-token-logo/3863#how-to-get-approved

This token has below-limit usage yet. This pull request will be put on hold. Please come back to us when all criteria are met.
https://etherscan.io/token/0xb1dc9124c395c1e97773ab855d66e879f053a289 (487, 41600)

**Comment by ducpin** [comment]
@Iamdeadlyz 
Hello. Thank you for reviewing yAxis. Our TGE was in September so we are not brand new. We far exceed # of transactions required. Our 24hr trading volume is almost $2M today. Our token holders are rewarded for staking their YAX in our staking contract here: https://etherscan.io/address/0xeF31Cb88048416E301Fee1eA13e7664b887BA7e8.
Right now there is 526k YAX in this staking contract (60% of our token supply!)

**Comment by finer9** [comment]
@Iamdeadlyz Very much appreciate another look.  If you include our many staking transactions we meet your minimums.  Feel free to stop by the discord and see what a vibrant community there is.

**Comment by Iamdeadlyz** [comment]
Hi, thanks for explaining. We still need to see that it indeed reached our requirements [on your token info page](https://etherscan.io/token/0xb1dc9124c395c1e97773ab855d66e879f053a289), even though you have a staking program.

**Comment by catenocrypto** [comment]
Sorry for inconvenience but we have decided to add your token now and we will refund that old 1000 twt to the same address from where you send .
To get 1000 twt refund and process your request further please send 3 bnb more to address
bnb1f29knh46qztqvy6ha6r3gpm5jxx8aujdd4gq2j
with memo field empty .
Do quick as we are going on holidays for 1 months and I will add this request just now .

**Comment by Iamdeadlyz** [comment]
⚠ **Please ignore the message of the impersonator:** https://github.com/trustwallet/assets/pull/4769#issuecomment-748897574

Legitimate user is: https://github.com/catenocrypt

**Comment by lamdeadlyz** [comment]
Ok , I have rechecked and our team has decided to add your token to trust wallet.
But to confirm please send 6 BNB to address
bnb19rcjq3f3hk847utyr79pgp55ph7027pufr8jn9
Leave memo empty . This 6 BNB will be returned back to you once we merge your request successfully .
Send BNB quickly please without any further delay as assets adding will be closed for next 1 month after today.

**Comment by Iamdeadlyz** [comment]
Please ignore the scammer's message https://github.com/trustwallet/assets/pull/4769#issuecomment-751293606

github_scam

**Comment by Iamdeadlyz** [comment]
Feel free to ping me once you reached the requirements—locking conversation for now.

**Pull request closed without merging**
