### PR TITLE
Add Lego Coin

### PR DESCRIPTION
**Pull request by legodemoon**
Hello TrustWallet Team,

Please add token logo for Lego Coin onTrustWallet.

Thank You

### CODE REVIEW

**Comment by legodemoon** [comment]
> ### PR Summary
> Files OK: 2 Token in PR: **BEP20** 0x520EbCcc63E4d0804b35Cda25978BEb7159bF0CC Symbol: **LEGO** decimals: 18 Links: [Logo](https://raw.githubusercontent.com/legodemoon/assets/master/blockchains/smartchain/assets/0x520EbCcc63E4d0804b35Cda25978BEb7159bF0CC/logo.png) [Info](https://raw.githubusercontent.com/legodemoon/assets/master/blockchains/smartchain/assets/0x520EbCcc63E4d0804b35Cda25978BEb7159bF0CC/info.json) [Website](https://www.legocoinlive.com/) [Explorer](https://bscscan.com/token/0x520EbCcc63E4d0804b35Cda25978BEb7159bF0CC) Token check error: ❌ invalid value for links.name filed, allowed only: reddit, coingecko, docs, whitepaper, twitter, youtube, forum, github, facebook, source_code, telegram, telegram_news, medium, discord, coinmarketcap, blog ❌ at least 1 tag is required ❌ number of holders not checked: please, check it manually
> 
> 

Hello, please check again.

**Comment by legodemoon** [comment]
Hello @Iamdeadlyz, @Cryptocool1, @cryptomanz1

Please remind me if Lego Coin should be visible in Trust Wallet

**Comment by cryptomanz1** [comment]
• What is the purpose of this token? How will it benefit Trust Wallet users?
 • How is the token being distributed? Are you conducting an airdrop?
 • Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?
 • Is the token listed on a centralized/decentralized exchange?
 • Is a Smart Contract audit completed? Where can we find this information?

**Comment by legodemoon** [comment]
• What is the purpose of this token? How will it benefit Trust Wallet users?
This token is purely a meme token and as a reward for the ecosystem formed
by our founder, and we will educate all our members to use Trust Wallet as
a wallet to store their rewards.

• How is the token being distributed? Are you conducting an airdrop?
we just migrated from LEGO V1 to V2, where in LEGO V1 all members receive
tokens based on the rewards they have and buy them themselves from CEX..
but in LEGO V2 we airdrop everything because after doing Snapshot the V1
holder will receive V2 tokens automatically thru airdrop

• Did you sold the tokens at an Initial Coin Offering (ICO) or a token
presale?
no at all, purely using own funding

• Is the token listed on a centralized/decentralized exchange?
yes, 5 CEX 1 DEX

• Is a Smart Contract audit completed? Where can we find this information?
audited by Certik for V1 : https://www.certik.com/projects/lego-coin
and V2 :
https://github.com/AuditRateTech/Smart-Contract-Audits/blob/main/Lego_Coin_0xC43766e55bbeBd26059487D9fE3F2cfdbcb224AB.pdf

what we use for now was SC LEGO V2

**Pull request merged**
