### PR TITLE
Add logo for our Superchin token

### PR DESCRIPTION
**Pull request by superchin**

### CODE REVIEW

**Comment by catenocrypt** [comment]
As per our policy, brand new tokens are not included, there is a minimum requirement of 2500 holder addresses and 5000 transactions, in order to filter out scam tokens.
See the criteria at (mentioned in the first message by the bot): https://community.trustwallet.com/t/how-to-submit-a-token-logo/3863).
This token has no real usage yet (5 holders). Closing PR for now. Please come back to us when all criteria are met.

https://etherscan.io/token/0x7eaf42D5e6D5192B8D097F1116B75e49d54F7074

**Comment by superchin** [comment]
Hi good day to you. After meeting the requirements do i need to pull new
request? Or it will be automatic that our logo will be uploaded.. hope to
hear from you soon.. thank you..

**Comment by catenocrypt** [comment]
If you comment here, PR is reopened.

**Comment by superchin** [comment]
I dont need to pay again right?? 😭😭

**Comment by superchin** [comment]
Thank you. We will do our best to meet the requirements
Have a great day ☺️☺️

**Comment by catenocrypt** [comment]
Correct, no need to pay again.

**Comment by superchin** [comment]
Thank you😊

**Pull request closed without merging**
