### PR TITLE
Kishimoto logo changed 

### PR DESCRIPTION
**Pull request by CryptoWebDev1**
We rebrand and changed our logo from previous one to the one that I currently created a PR for

This was the Pull request that was accepted for the Kishimoto INU

https://github.com/trustwallet/assets/pull/15289

continuation of

https://github.com/trustwallet/assets/pull/20568

### CODE REVIEW

**Comment by CryptoWebDev1** [comment]
@cryptomanz the logo size is 98 KB 
can we accept this pr now

**Comment by cryptomanz** [comment]
Screenshot 2022-05-25 at 09 33 06
Please change logo

**Comment by CryptoWebDev1** [comment]
@Cryptocool1 the logo we changed has not been changed yet for the users 
Can we maybe fix it

**Comment by Cryptocool1** [comment]
Can you send me the logo that supposed to be?

**Comment by CryptoWebDev1** [comment]
IMG_1681 (2)
here sir

**Comment by Cryptocool1** [comment]
B56ABF4A-8255-4A4E-8993-3326156FC5D8
The same

**Comment by CryptoWebDev1** [comment]
many of our investors are still seeing the previous logo 

will that be fixed

**Comment by Cryptocool1** [comment]
You should clear the cache

**Comment by CryptoWebDev1** [comment]
okay thank you so much :)

**Pull request merged**
