### PR TITLE
Adding Test Token

### PR DESCRIPTION
**Pull request by KingzRex**
Adding BNB Gold 
in reference to the previous pull request which has been paid for in TWT
#16876

 Adding BNB Gold #16876

### CODE REVIEW

**Comment by Cryptocool1** [comment]
Is the smart contract audit ready?

**Comment by KingzRex** [comment]
Adding BNB Gold #16876

I HAVE PAID ALREADY

**Comment by KingzRex** [comment]
Yes

https://app.marketmove.ai/token/0xC836DCC9c880D4558C301e6d439db1B1DCaF7F3a/audit

**Comment by KingzRex** [comment]
On Tue, Dec 28, 2021 at 15:59 Toochukwu Okoro ***@***.***>
wrote:

> Yes
>

That’s the result of the Audit

https://app.marketmove.ai/token/0xC836DCC9c880D4558C301e6d439db1B1DCaF7F3a/audit


>
> https://app.marketmove.ai/token/0xC836DCC9c880D4558C301e6d439db1B1DCaF7F3a/audit
>
>

**Comment by Cryptocool1** [comment]
We require audit from certik, techrate or dessert finance

**Comment by KingzRex** [comment]
Will get one from techrate in a sec

**Comment by cryptomanz** [comment]
Feel free to open new PR when smart contract audit will be ready
When creating a new PR make sure to mention this PR, so that we can see that fee has been paid already here.

**Pull request closed without merging**
