### PR TITLE
Lending Platform ( LPT ) Logo

### PR DESCRIPTION
**Pull request by fidezi**
Logo ERC-20 for LPT token

### CODE REVIEW

**Comment by fidezi** [comment]
i have paid

**Comment by fidezi** [comment]
Hello, tell me when my logo is added to the trust wallet?

**Comment by fidezi** [comment]
@zachzwei

**Comment by catenocrypt** [comment]
> Hello, tell me when my logo is added to the trust wallet?

PR has been merged, logo is now included in the official repository.  Due to caching it may take a few hours until it shows up in the app.

**Pull request merged**
