### PR TITLE
Add HI (BEP20)

### PR DESCRIPTION
**Pull request by hiDollar**
Adding info for BEP20 token 'HI'.

PR created by <a href="https://assets.trustwallet.com">TW Assets Management</a>

### CODE REVIEW

**Comment by hiDollar** [comment]
We have already paid the merge fee for a previous pull request, Request
16938. I am sending proof of the payment below. Can this previous payment
please be used for this new pull fee?

I have followed up with this on various channels, including support ticket,
but unfortunately never received a reply.

If there is any other proof from our side, please let me know.

Looking forward to a positive response,

Lukas Baar
Marketing Manager at *hi*

**Comment by hiDollar** [comment]
[image: Screenshot_20220105-013245_Binance.jpg]

**Comment by hiDollar** [comment]
We just want to add the BEP20 token please.

**Comment by Cryptocool1** [comment]
please create new PR with only BEP20 files. make sure to mention this PR, so the fee can be reused

**Comment by hiDollar** [comment]
I created the pull request with only BEP20 files, #17430 and
mentioned #17328. Is there anything else I can do?

**Pull request closed without merging**
