### PR TITLE
Add Crystal logo and info(BEP20)

### PR DESCRIPTION
**Pull request by Celestialgamefi**
Adding info for BEP20 token 'Celestial'.

PR created by <a href="https://assets.trustwallet.com">TW Assets Management</a>

### CODE REVIEW

**Comment by Celestialgamefi** [comment]
https://explorer.binance.org/tx/165AEBFCBCE9D1F3C3A045D0AC5C45718DE3FB0F3CFF30641795F8E064780815

**Comment by Celestialgamefi** [comment]
We are a double token economic system so we need two contract addresses

**Comment by Cryptocool1** [comment]
hello,
• What is the purpose of this token? How will it benefit Trust Wallet users?
 • How is the token being distributed? Are you conducting an airdrop?
 • Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?
 • Is the token listed on a centralized/decentralized exchange?
 • Is a Smart Contract audit completed? Where can we find this information?

**Comment by Celestialgamefi** [comment]
• What is the purpose of this token? How will it benefit Trust Wallet users?
 
1.      Celt is our main token. All consumption in the game is Celt. In the trading market, 5% of Celt will be drawn as a handling fee and burned. Crystal is our sub token. Its existence is to maintain the stability of CELT, and its distribution to users as a profit method in the game
2.      Users who has CELT could stake CELT into the pool to generate Crystal.
 
• How is the token being distributed? Are you conducting an airdrop?
Presale 14%
Game Ecosystem 40%
Development 5%
Marketing 10%
DAO 4%
LP 8%
TEAM 10%
Foundation 6%
Consultant 2%
Audit 1%
 
• Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?
There was two institution invested us, ZBS capital, OKEx Blockdream Ventures
• Is the token listed on a centralized/decentralized exchange?
Pancake swap
• Is a Smart Contract audit completed? Where can we find this information?
https://www.certik.org/projects/celestial

**Comment by Celestialgamefi** [comment]
https://coinmarketcap.com/currencies/crystal/
https://www.coingecko.com/en/coins/crystal

**Comment by Celestialgamefi** [comment]
• What is the purpose of this token? How will it benefit Trust Wallet users? 
 
1.   Crystal is our substoken. Its existence is to maintain the stability of CELT, and its distribution to users as a profit method in the game
2.      Users who has Crytial could change to Moore chest, when you open it you will get NFT as reward.
 
• How is the token being distributed? Are you conducting an airdrop? 
LP 100%
 
• Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale? 
NO
• Is the token listed on a centralized/decentralized exchange? 
Pancake swap
• Is a Smart Contract audit completed? Where can we find this information?
https://www.certik.org/projects/celestial

**Pull request merged**
