### PR TITLE
Adding SPW logo

### PR DESCRIPTION
**Pull request by SoupSwapOfficial**
Contract Address: 0x604d105f2f1f68641a000f03b5dc557bfffdb8fe 
Token Name: SoupSwap
Symbol: SPW
Decimals: 18
Network: Binance Smart Chain
Platform : BEP-20
Max Supply: 98.000.000 SPW

Logo 256x256

### CODE REVIEW

**Comment by SoupSwapOfficial** [comment]
Logo 256x256

**Comment by SoupSwapOfficial** [comment]
add soupswap token info and logo in trust wallet.

**Comment by catenocrypt** [comment]
Sorry, the files in this PR are all mixed up.
Please create a new PR, and mention this PR to avoid paying fee again.
Follow our guide:  https://community.trustwallet.com/t/how-to-submit-a-token-logo/3863
You may want to try our Assets app (in beta);  close this PR; go to https://assets.trustwallet.com, log on with Github, enter contract ID, logo and some additional info, and it will create a PR for you.  See  https://community.trustwallet.com/t/how-to-submit-a-token-logo-using-assets-app/82957 
Closing.

**Comment by catenocrypt** [comment]
Payment considered for #6063

**Pull request closed without merging**
