### PR TITLE
add logo

### PR DESCRIPTION
**Pull request by bricsmine**
add logo : file: logo and info

### CODE REVIEW

**Comment by bricsmine** [comment]
The logo and info file are uploaded correctly and I can see the files

**Comment by bricsmine** [comment]
[info.json](https://github.com/trustwallet/assets/files/14516460/info.json)
logo


0xec80e6ef54d43aadc0e0556a73ec34d840d5a294
Binace smart chain network

**Comment by cryptomanz1** [comment]
Correction needed:
This is a BEp20 token, correct folder is blockchains/smartchain/assets. Please correct.

**Comment by bricsmine** [comment]
Can you help more?

**Comment by bricsmine** [comment]
I made the correction

**Comment by bricsmine** [comment]
> Correction needed: This is a BEp20 token, correct folder is blockchains/smartchain/assets. Please correct.
I made the correction

**Comment by bricsmine** [comment]
> No token files found. If you try to add/modify a token, check the name and location of your files! Logo file must be named exactly 'logo.png'. If you are not adding a token, ignore this message.

Commit failed

Committing the files to the repository failed.

**Comment by bricsmine** [comment]
> No token files found. If you try to add/modify a token, check the name and location of your files! Logo file must be named exactly 'logo.png'. If you are not adding a token, ignore this message.

Why does it give an error when I try to upload the file in Smart Chain?

**Comment by bricsmine** [comment]
Committing the files to the repository failed.

**Comment by bricsmine** [comment]
> Correction needed: This is a BEp20 token, correct folder is blockchains/smartchain/assets. Please correct.

Committing the files to the repository failed.

**Comment by bricsmine** [comment]
whaaat? I wanted to delete my file. Why was everyone removed?

**Review by bricsmine — COMMENTED** [review]
rev

**Comment by bricsmine** [comment]
image

**Comment by bricsmine** [comment]
@Cryptocool1 @cryptomanz1 @natedaiger @hexorx  help me

**Comment by Cryptocool1** [comment]
Please create new PR, follow doc https://developer.trustwallet.com/listing-new-assets/requirements
You may want to try our Assets app in beta; go to https://assets.trustwallet.com, log on with Github, enter contract ID, logo and some additional info, and it will create a PR for you.
See https://developer.trustwallet.com/listing-new-assets/repository_details

**Comment by Cryptocool1** [comment]
Make sure to mention this PR in new one, so the fee can be reused

**Pull request closed without merging**
