### PR TITLE
Upload UTU icon

### PR DESCRIPTION
**Pull request by mikewchan**
Please ignore everything prior to October 30, 2020. I am terrible at GitHub.

### CODE REVIEW

**Comment by Iamdeadlyz** [comment]
Please provide more details about these projects (`0xa58a4f5c4bb043d2cc1e170613b74e767c94189b`, `0x29E9fDF5933824ad21Bc6dbb8BF156EFA3735e32`, and `0xBd2949F67DcdC549c6Ebe98696449Fa79D988A9F`)

https://community.trustwallet.com/t/how-to-submit-a-token-logo/3863#how-to-get-approved
You can follow this format when adding an info.json file:
```
{
    "name": "Trust Wallet Token",
    "website": "https://trustwallet.com",
    "source_code": "https://github.com/trustwallet/",
    "short_description": "Utility token to increase adoption of cryptocurrency.",
    "description": "Utility token to increase adoption of cryptocurrency.",
    "socials": [
        {
            "name": "Twitter",
            "url": "https://twitter.com/trustwalletapp",
            "handle": "TrustWalletApp"
        },
        {
            "name": "Reddit",
            "url": "https://reddit.com/r/trustapp",
            "handle": "TrustApp"
        }
    ],
    "explorer": "https://bscscan.com/token/0x4b0f1812e5df2a09796481ff14017e6005508003"
} 
```

**Comment by mikewchan** [comment]
This is for 0xa58a4f5c4bb043d2cc1e170613b74e767c94189b. You can ignore the others. 

{
    "name": "UTU Coin",
    "website": "http://protocol.utu.io/",
    "source_code": "https://github.com/utu-protocol/",
    "short_description": "Utility token that powers the trust infrastructure of the internet.",
    "description": "Utility token that powers the trust infrastructure of the internet.",
    "socials": [
        {
            "name": "Twitter",
            "url": "https://twitter.com/UTU_trust",
            "handle": "UTU_trust"
        },
        {
            "name": "Telegram",
            "url": "https://t.me/UTUtrust",
            "handle": "UTUtrust"
        }
    ],
    "explorer": "https://etherscan.io/token/0xa58a4f5c4Bb043d2CC1E170613B74e767c94189B"
}

**Comment by Iamdeadlyz** [comment]
> You can ignore the others.

Since you were the contributor for those tokens (and it appeared for this PR too), it's a good time to add info.json so that the appropriate information will be displayed as well.

**Comment by mikewchan** [comment]
Let me know if there is a better way to submit this, but here is the info for the other two tokens. Thanks!

For 0xBd2949F67DcdC549c6Ebe98696449Fa79D988A9F:

{
    "name": "Meter Governance mapped by Meter.io",
    "website": "https://www.meter.io/",
    "source_code": "https://github.com/meterio",
    "short_description": "eMTRG is the ERC-20 equivalent of MTRG, the governance coin of the Meter network.",
    "description": "eMTRG is the ERC-20 equivalent of MTRG, the governance coin of the Meter network.",
    "socials": [
        {
            "name": "Twitter",
            "url": "https://twitter.com/Meter_IO",
            "handle": "Meter_IO"
        },
        {
            "name": "Telegram",
            "url": "https://t.me/Meter_IO",
            "handle": "Meter_IO"
        },
        {
            "name": "Reddit",
            "url": "https://www.reddit.com/r/Meter_io/",
            "handle": "r/Meter_io"
        },
        {
            "name": "Discord",
            "url": "https://discord.gg/XZgZsCn",
            "handle": "Meter Project"
        },
        {
            "name": "Facebook",
            "url": "https://www.facebook.com/MeterFoundation/",
            "handle": "Meter Foundation"
        },
        {
            "name": "LinkedIn",
            "url": "https://www.linkedin.com/company/meterio/",
            "handle": "Meterio"
        },
    ],
    "explorer": "https://etherscan.io/token/0xBd2949F67DcdC549c6Ebe98696449Fa79D988A9F"
}


For 0x29E9fDF5933824ad21Bc6dbb8BF156EFA3735e32:

{
    "name": "Meter Stable mapped by Meter.io",
    "website": "https://www.meter.io/",
    "source_code": "https://github.com/meterio",
    "short_description": "eMTR is the ERC-20 equivalent of MTR, the low-volatility coin of the Meter network.",
    "description": "eMTR is the ERC-20 equivalent of MTR, the low-volatility coin of the Meter network.",
    "socials": [
        {
            "name": "Twitter",
            "url": "https://twitter.com/Meter_IO",
            "handle": "Meter_IO"
        },
        {
            "name": "Telegram",
            "url": "https://t.me/Meter_IO",
            "handle": "Meter_IO"
        },
        {
            "name": "Reddit",
            "url": "https://www.reddit.com/r/Meter_io/",
            "handle": "r/Meter_io"
        },
        {
            "name": "Discord",
            "url": "https://discord.gg/XZgZsCn",
            "handle": "Meter Project"
        },
        {
            "name": "Facebook",
            "url": "https://www.facebook.com/MeterFoundation/",
            "handle": "Meter Foundation"
        },
        {
            "name": "LinkedIn",
            "url": "https://www.linkedin.com/company/meterio/",
            "handle": "Meterio"
        },
    ],
    "explorer": "https://etherscan.io/token/0x29E9fDF5933824ad21Bc6dbb8BF156EFA3735e32"
}

**Comment by mikewchan** [comment]
Thank you!

**Pull request merged**
