### PR TITLE
Add BITLIVE (BEP20)

### PR DESCRIPTION
**Pull request by PankajTMB**
Adding info for BEP20 token 'BITLIVE'.

PR created by <a href="https://assets.trustwallet.com">TW Assets Management</a>

### CODE REVIEW

**Comment by cryptomanz** [comment]
• What is the purpose of this token? How will it benefit Trust Wallet users?
 • How is the token being distributed? Are you conducting an airdrop?
 • Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?
 • Is the token listed on a centralized/decentralized exchange?
 • Is a Smart Contract audit completed? Where can we find this information?

**Comment by PankajTMB** [comment]
• What is the purpose of this token? How will it benefit Trust Wallet users?
Ans: BitLive is a Utility token for Blockchain technologies. Users hold and stake BITLIVE tokens to qualify for project in Blockchain allocations on BLT launchpad.

• How is the token being distributed? Are you conducting an airdrop?
Ans: A portion of the tokens are reserved for the project's developers and some are held for business development and expansion purpose. However we're not conducting an airdrop yet.

• Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?
Ans: No, all of our token are sold in PancakeSwap and Vindax Exchange.

• Is the token listed on a centralized/decentralized exchange?
Ans: BLT is listed on Uniswap, PancakeSwap and Vindax  https://vindax.com/exchange-base.html?symbol=BLT_USDT.

• Is a Smart Contract audit completed? Where can we find this information?
Ans: Smart Contract audit has not been done yet. However, If its compulsory then we're willing to do that.

**Comment by cryptomanz** [comment]
Awaiting for smart contract audit, on hold for now.

**Comment by cryptomanz** [comment]
Please come back to us when all criteria are met.
When creating a new PR make sure to mention this PR, so that we can see that fee has been paid already here.

**Comment by PankajTMB** [comment]
Please Check https://github.com/trustwallet/assets/pull/18445

**Comment by PankajTMB** [comment]
> Please come back to us when all criteria are met. When creating a new PR make sure to mention this PR, so that we can see that fee has been paid already here.

 Please Check https://github.com/trustwallet/assets/pull/18445

**Comment by PankajTMB** [comment]
> Awaiting for smart contract audit, on hold for now.

https://bitlivenow.com/audit.pdf

**Comment by PankajTMB** [comment]
NEW PR :- https://github.com/trustwallet/assets/pull/18691

**Comment by PankajTMB** [comment]
@cryptomanz 
smart contract audit - NEW PR :- https://github.com/trustwallet/assets/pull/18691.
NEW PR :- https://github.com/trustwallet/assets/pull/18691

**Comment by PankajTMB** [comment]
@cryptomanz 
smart contract audit :-
https://bitlivenow.com/audit.pdf

**Comment by PankajTMB** [comment]
@Cryptocool1 

Thanks For Merge Pull request,
But price not Showing.
what we do?

**Pull request merged**
