### PR TITLE
Add member

### PR DESCRIPTION
**Pull request by 0xigami**

### CODE REVIEW

**Comment by Cryptocool1** [comment]
• What is the purpose of this token? How will it benefit Trust Wallet users?
 • How is the token being distributed? Are you conducting an airdrop?
 • Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?
 • Is the token listed on a centralized/decentralized exchange?
 • Is a Smart Contract audit completed? Where can we find this information?

**Comment by 0xigami** [comment]
thanks for the follow up @Cryptocool1, answers below:

- the original purpose of member was to reward my 14k+ nft collectors (now 17.5k+ holders). it serves to help proliferate the member meme. holders will also be able to collect members pfp collection, which will only be available for purchase with member token. the the community can also earn tokens by creating memes at [uplink.wtf/member/mintboard](https://uplink.wtf/member/mintboard) and the benefit is pure fun. it's an experiment in bootstrapping community around a meme template and the art of collective creation. also in the spirit of my widely read manifesto, [the hypercommons](https://hypercommons.wtf/)
- the token has been distributed via a number of airdrops and claims. more distribution to come via ongoing meme submissions as mentioned earlier (please check link as full description there) and you can view a full criteria at [member.clinic/#todo](https://member.clinic/#todo)
- there was no ICO or token presale. distribution commenced upon token creation, to those who have supported me previously by collecting my NFT releases and having completed various things onchain and off. eth used to fund the initial liquidity pool were zora protocol rewards i earned through free nfts i released to promote the member meme during its inception
- token is currently available via uniswap v3 member/weth pool as shown on [dex screener](https://dexscreener.com/base/0xa4efe9e8e2a2d5a2ac46805f233b8e49d0e11955)
- no audit necessary. this is a very basic token deployed via open zeppelin wizard, please see screenshot below for original configuration and see [verified contract source](https://basescan.org/token/0x7d89e05c0b93b24b5cb23a073e60d008fed1acf9#code) on basescan (please note: verified source on basescan is flattened version of deployed contract as verify plugin in remix not working properly with basescan atm)

please let me know if any other questions. i have plenty of reputable collaborators who can attest to my work. just let me know

image

**Comment by 0xigami** [comment]
quick update regarding benefit to users @Cryptocool1 

i've deployed member dao, a nounish dao that has been sent 10% of $member supply for an ecosystem

please let me know if any further information is helpful

https://nouns.build/dao/base/0xFBfe187b444798214Dd4BbfAdE369F8DC3864C6a

**Comment by 0xigami** [comment]
hi @Cryptocool1 

just want to confirm, anything else i need to do for population in uniswap?

guessing need to allow time for propagation and caching etc.

thanks!

**Pull request merged**
