### PR TITLE
Add TWELVE (BEP20)

### PR DESCRIPTION
**Pull request by ombayoeco11**
Adding info for BEP20 token 'TWELVE'.

PR created by <a href="https://assets.trustwallet.com">TW Assets Management</a>

### CODE REVIEW

**Comment by ombayoeco11** [comment]
Our holder is still doesn't meet the minimum requirements of 10K holders, what can we do about this? We're trying to put the logo so that the holder can immediately see the token in their wallet.

**Comment by ombayoeco11** [comment]
i've tried submit ticket 2x still no reply from anyone. Is there anyone from TrustWallet that i can discuss with ?

**Comment by cryptomanz1** [comment]
As per our policy, there is a minimum requirement of 10,000 holder addresses and 15,000 transactions.
See the criteria at : https://developer.trustwallet.com/listing-new-assets/requirements .

**Comment by ninooo123** [comment]
Skickat från Outlook för iOS<https://aka.ms/o0ukef>
________________________________
Från: ombayoeco11 ***@***.***>
Skickat: Sunday, October 29, 2023 4:00:12 PM
Till: trustwallet/assets ***@***.***>
Kopia: Subscribed ***@***.***>
Ämne: Re: [trustwallet/assets] Add TWELVE (BEP20) (PR #26678)


i've tried submit ticket 2x still no reply from anyone. Is there anyone from TrustWallet that i can discuss with ?

**Pull request closed without merging**
