### PR TITLE
add LEE to TW [threshold clarification]

### PR DESCRIPTION
**Pull request by Cheelee-inc**
Our PR was closed due to not passing the minimum bar on holders and transactions.

However, our project had [already been listed with token CHEEL](https://github.com/Cheelee-inc/assets/tree/master/blockchains/smartchain/assets/0x1F1C90aEb2fd13EA972F0a71e35c0753848e3DB0), and this one is the utility token, which is required for our system to work fine.

According to "Minimum 10,000 token holders and 15,000 transactions (Airdrop tokens excluded). This requirement is subject for review based on the project"(c) — it depends on subject review.

Could you please lower the requirements and so we can get proceeded and make payment?

Thank you.

### CODE REVIEW

**Comment by Cheelee-inc** [comment]
@cryptomanz1 
Hey there! 

Our PR was set on hold.
Please, give us a clue what is expected from us to proceed.

Kind reminder:
Our project had [already been listed with token CHEEL](https://github.com/Cheelee-inc/assets/tree/master/blockchains/smartchain/assets/0x1F1C90aEb2fd13EA972F0a71e35c0753848e3DB0), and this one is the utility token, which is required for our system to work fine.

According to "Minimum 10,000 token holders and 15,000 transactions (Airdrop tokens excluded). This requirement is subject for review based on the project"(c) — it depends on subject review.

Thank you.

**Comment by Cheelee-inc** [comment]
@Cryptocool1 
Hey there!

Our PR was set on hold.
Please, give us a clue what is expected from us to proceed.

Kind reminder:
Our project had [already been listed with token CHEEL](https://github.com/Cheelee-inc/assets/tree/master/blockchains/smartchain/assets/0x1F1C90aEb2fd13EA972F0a71e35c0753848e3DB0), and this one is the utility token, which is required for our system to work fine.

According to "Minimum 10,000 token holders and 15,000 transactions (Airdrop tokens excluded). This requirement is subject for review based on the project"(c) — it depends on subject review.

Thank you.

**Comment by pvcmetaofficial** [comment]
Hello hello @Cryptocool1 please reply

pease check this pool https://github.com/trustwallet/assets/pull/25799

We already payment 500 TWT as Fee and provide all details

**Comment by Cheelee-inc** [comment]
@Cryptocool1 
Please, give a clue, what is the last step to merge

**Comment by Cryptocool1** [comment]
Hello, you have to get 10k holders. We can make an exception only for multichain tokens

**Comment by Cryptocool1** [comment]
I can explain you, at least 1 chain should have more than 10k holders, after that we can discuss adding another chain.

**Pull request closed without merging**
