### PR TITLE
Adding Test Token

### PR DESCRIPTION
**Pull request by KingzRex**

### CODE REVIEW

**Comment by KingzRex** [comment]
How can I fix the links field

**Comment by Cryptocool1** [comment]
• What is the purpose of this token? How will it benefit Trust Wallet users?
 • How is the token being distributed? Are you conducting an airdrop?
 • Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?
 • Is the token listed on a centralized/decentralized exchange?
 • Is a Smart Contract audit completed? Where can we find this information?

**Comment by KingzRex** [comment]
Hello

BNBGOLD brings together DEFI, NFT and Blockchain Gaming all in one piece.
This will be ultimately achieved by the seamless integration of Defi
staking and lending protocols alongside blockchain gaming DApps. The birth
of this project was due to the increased adoption of artifacts on the BSC
network, this will help generate big financial growth opportunities for our
beloved community. This project will heavily thrive given the launch of the
Binance NFT marketplace which is beyond awesome.
It will benefit Trustwallet users by giving incentivized staking rewards

The token was distributed through presale, Airdrop and pancakeswap listing

Yes the project conducted a presale

The token is listed on pancakeswap and has plans of listing on a
Centralized exchange

The smart contract hasn’t been audited yet.

**Comment by Cryptocool1** [comment]
Awaiting for smart contract audit, on hold for now

**Comment by KingzRex** [comment]
Can the logo be submitted without an Audit?

**Comment by Cryptocool1** [comment]
No, you can see the requirements here:
https://developer.trustwallet.com/assets/requirements

**Comment by Cryptocool1** [comment]
Feel free to open new PR when smart contract audit will be ready
When creating a new PR make sure to mention this PR, so that we can see that fee has been paid already here.

**Comment by KingzRex** [comment]
Alright

**Comment by KingzRex** [comment]
I have created a new PR and I am being asked to pay again

**Pull request closed without merging**
