### PR TITLE
Add HONEY (BEP20)

### PR DESCRIPTION
**Pull request by HoneyFarmFi**
Adding info for BEP20 token 'HONEY'.

PR created by <a href="https://assets.trustwallet.com">TW Assets Management</a>

### CODE REVIEW

**Comment by HoneyFarmFi** [comment]
As previous, a native token of a DeFi project, especially when it's an yield farming project like HoneyFarm, most of the holders stake the tokens to the matsterchef contract, in this case, https://bscscan.com/address/0xc3D910c9D2bB024931a44Cf127B6231aC1F04de3, our layer 2 masterchef.

please refer that it has already 432943 times of transfer and has $35M trading volume on PancakeSwap already.
You can check it on https://pancakeswap.info/token/0xfa363022816abf82f18a9c2809dcd2bb393f6ac5

Thanks,

**Comment by HoneyFarmFi** [comment]
and HONEY is on CoinGecko and CoinMarketCap
https://www.coingecko.com/en/coins/honeyfarm-finance
https://coinmarketcap.com/currencies/honeyfarm-finance

**Comment by cryptomanz** [comment]
As per our policy, brand new tokens are not included, there is a minimum requirement of 2500 holder addresses and 5000 transactions, in order to filter out scam tokens.
See the criteria at (mentioned in the first message by the bot): https://community.trustwallet.com/t/how-to-submit-a-token-logo/3863).

**Comment by HoneyFarmFi** [comment]
> As per our policy, brand new tokens are not included, there is a minimum requirement of 2500 holder addresses and 5000 transactions, in order to filter out scam tokens.
> See the criteria at (mentioned in the first message by the bot): https://community.trustwallet.com/t/how-to-submit-a-token-logo/3863).

Hello @cryptomanz 

HONEY is already on CoinMarketCap and CoinGecko.
No. of transfer is more than 433K and trading volume is $35M in a week.
It is relatively new but already well-known.

The only condition that HONEY can't meet is the no. of holders but again, the nature of a native token of an yield farming defi project is that most of the holders stake their tokens to the masterchef.
The no. of holders on the bscscan can't actually reflect the real number of holders.

Please understand this situation and list HONEY on TrustWallet.

Thanks!

**Comment by HoneyFarmFi** [comment]
Thanks so much!!

**Pull request merged**
