### PR TITLE
Add logo file for BTSE Token

### PR DESCRIPTION
**Pull request by backupacctuname**
Add BTSE Token (BTSE) logo file

### CODE REVIEW

**Comment by catenocrypt** [comment]
As per our policy, brand new tokens are not included, there is a minimum requirement of 100 holder addresses and 500 transactions, in order to filter out scam tokens.
See the criteria at (mentioned in the first message by the bot): https://community.trustwallet.com/t/how-to-submit-a-token-logo/3863#how-to-get-approved
Token usage is minimal.  Putting PR on hold.  Please come back when all criteria are met.

https://etherscan.io/token/0x666d875C600AA06AC1cf15641361dEC3b00432Ef

**Comment by NotAlfred** [comment]
> 
> 
> As per our policy, brand new tokens are not included, there is a minimum requirement of 100 holder addresses and 500 transactions, in order to filter out scam tokens.
> See the criteria at (mentioned in the first message by the bot): https://community.trustwallet.com/t/how-to-submit-a-token-logo/3863#how-to-get-approved
> Token usage is minimal. Putting PR on hold. Please come back when all criteria are met.
> 
> https://etherscan.io/token/0x666d875C600AA06AC1cf15641361dEC3b00432Ef

Hello,

This token has more than 100 holders and 500 transactions in reality but on the liquid blockchain, this is https://www.btse.com/en/home wrapped onto an ERC20 token.

https://blockstream.info/liquid/address/GkyysxjFiqZ7aFnA8ztq3rWbDxaLg5eGcD here is the locked Liquid tresaury matching the circulating supply here https://etherscan.io/token/0x666d875c600aa06ac1cf15641361dec3b00432ef
(200.000 tokens locked on liquid matched by 200.000 minted on the ETH chain)

**Comment by catenocrypt** [comment]
Reopening

**Comment by catenocrypt** [comment]
Please add an `info.json` file next to the `logo.png`, with info about the project, of the form:

```json
{
    "name": "Trust Wallet Token",
    "website": "https://trustwallet.com",
    "short_description": "Utility token to increase adoption of cryptocurrency.",
    "explorer": "https://explorer.binance.org/asset/TWT-8C2"
}
```

**Comment by NotAlfred** [comment]
64cbe33f2b2ad05a2d77cef13ff901c5b0921d2f addresses this

**Pull request merged**
