### PR TITLE
DEUS token contract update, add DEI token, fee paid already PR16648

### PR DESCRIPTION
**Pull request by bi0hazard12**
As request by @cryptomanz on previous #16648 this is the new PR

We need to remove our old contract 0x3b62F3820e0B035cc4aD602dECe6d796BC325325 and update to the new one 0xDE5ed76E7c05eC5e4572CfC88d1ACEA165109E44.

We also need to add our newly token DEI (our algorithmic stable coin)
0xDE12c7959E1a72bbe8a5f7A1dc8f8EeF9Ab011B3

DEI is our stable coin and as of right you don't see to much holders because we have a stacking program where most of the DEI is stacked at our farming contracts (between ETH and MATIC) and are mostly used on polygon with 14000 transactions. Since DEI is a token from DEUS main ecosystem and it's our stable coin can you please take that in account? We appreciate so much.

Since both tokens exist in ETH and POLYGON add DEUS and DEI on POLYGON too.

Thank you

### CODE REVIEW

**Comment by bi0hazard12** [comment]
@Cryptocool1, @cryptomanz and @ramsty

Can anyone please check this and approve? This is the 4 time I've submitted the request :(

Appreciated and thank you

**Comment by cryptomanz** [comment]
Hello,
Please follow the rules for adding token, your logo should be a full screen, 256x256.
Example:
https://community.trustwallet.com/t/how-to-submit-a-token-logo/3863

**Comment by cryptomanz** [comment]
What is the old contract for DEI?

**Comment by bi0hazard12** [comment]
> What is the old contract for DEI?

DEI doesn't have old contract. DEI is our stable coin and as of right you don't see to much holders because we have a stacking program where most of the DEI is stacked at our farming contracts (between ETH and MATIC) and are mostly used on polygon with 14000 transactions. Since DEI is a token from DEUS main ecosystem and it's our stable coin can you please take that in account? We appreciate so much.

I noticed you removed the files for polygon chain, but we also need DEUS and DEI on polygon, we are a multichain project.

And sorry for the logo sizes but following up the trustwallet guide it was saying max 512*512.

Thank you

**Comment by Cryptocool1** [comment]
we can add only this contract due to migration
another contract should meet our criteria

**Comment by Cryptocool1** [comment]
we will put abandoned status for your old contract
you need to create PR only with 0xDE5ed76E7c05eC5e4572CfC88d1ACEA165109E44 contract address

**Comment by bi0hazard12** [comment]
> we can add only this contract due to migration another contract should meet our criteria

DEI contract is a stable coin token that is used in a farming pools and the token are stacked in our liquidity pools. We can't simple ask our users to removed the token from the liquidity pool just to have holders in order to pass the criteria, that wouldn't make sense.  Close to 16000 transactions already show how trustable our DEI token is. 

I understand that there is some criteria and trust wallet is trying to avoid scams and everything else. But you guys also should understand and support projects that want the best for their users and since DEUS isn't a new project you should take that in account, we also previously added DEA and WCOIN-IOU on trust wallet without those criteria because it was trusted tokens from our ecosystem and there wasn't any issue. 

Can we please have some awareness here? 

I think the pull request are getting closed left and right without proper communication, no one bother to answer my previous questions properly it feels like we are just getting ignored at this point.

**Pull request closed without merging**
