### PR TITLE
Added Nexalt XLT (BEP20)

### PR DESCRIPTION
**Pull request by zuhairthabit01**
request to add nexalt into trustwallet

### CODE REVIEW

**Comment by Cryptocool1** [comment]
As per our policy, brand new tokens are not included, there is a minimum requirement of 10,000 holder addresses and 15,000 transactions, in order to filter out scam tokens.
See the criteria at : https://developer.trustwallet.com/assets/requirements .

**Comment by GrownStar** [comment]
Hi @Cryptocool1, I want to let you that Nexalt has its own blockchain and running since 17 Feb 2020, having 526606 blocks mined/minted on its blockchain. It's Forked from LiteCoin with added POS, MLC, and Masternodes features. Here is the official website https://nexalt.org and here is its explorer http://nexalt.io which is clearly showing all details you require

- up to "495953ADDRESS COUNT", 
- up to "2 Years and 7 months Blockchain Age."
- up to "1 Million Plus Transactions."

I am the official Representative of Nexalt Blockchain, and adding trying to nexalt in "Trust Wallet (Binance Chain)"  in my community demands. Any Further Clarification, I am here to reply to you.

**Review by GrownStar — COMMENTED** [review]
Hi @Cryptocool1, I want to let you know that Nexalt has its own blockchain and has been running since 17 Feb 2020, having 526606 blocks mined/minted on its blockchain. It's Forked from LiteCoin with added POS, MLC, and Masternodes features. Here is the official website https://nexalt.org/ and here is its explorer http://nexalt.io/ which is clearly showing all details you require

up to "495953 ADDRESS COUNT",
up to "2 Years and 7 months Blockchain Age."
up to "1 Million Plus Transactions."
I am the official Representative of the Nexalt Blockchain Team, and adding trying to nexalt in "Trust Wallet (Binance Chain)" in my community demands. Any Further Clarification, I am here to reply to you.

**Comment by Cryptocool1** [comment]
Hello, we do not support Nexalt blockchain, so you need to have 10.000 holders on BEP20

**Comment by GrownStar** [comment]
Perfect. Let me post in my community to have 10,000 holders, and will be back here

**Pull request closed without merging**
