### PR TITLE
Add logo for Crucifearous Finance Token

### PR DESCRIPTION
**Pull request by Crucifearous2021**
This is a request for Adding Token Logo and Info for Crucifearous SmartChain Token

### CODE REVIEW

**Comment by Crucifearous2021** [comment]
Hello, I just want to ask on how long the process will be, and how we will be notified? Thank You!

**Comment by Cryptocool1** [comment]
correction needed:
Contract is not in checksum format, should be 0x6bf3a93793e52f75543c92AfEC4636559988e3c1
 Logo image too large, max 100 kB, current 265.483 kB

**Comment by Crucifearous2021** [comment]
I just want to ask the process on how to correct it.

**Comment by Crucifearous2021** [comment]
Should I need to reupload the files?

**Comment by Cryptocool1** [comment]
> Should I need to reupload the files?
 
I suggest to create a new PR (and mention this one so that fee does not have to be paid again).
 • You may use our Assets app (in beta); close this PR; go to https://assets.trustwallet.com, log on with Github, enter contract ID, logo and some additional info, and it will create a PR for you. See https://community.trustwallet.com/t/how-to-submit-a-token-logo-using-assets-app/82957\

**Comment by Crucifearous2021** [comment]
About to close this PR...
Created PR 10124   https://github.com/trustwallet/assets/pull/10124

**Pull request closed without merging**
