### PR TITLE
Add DEMON (BEP20)

### PR DESCRIPTION
**Pull request by DEMONNNX**

### CODE REVIEW

**Comment by DEMONNNX** [comment]
@hexorx need a maintainer to approve running workflows, thanks.

**Comment by cryptomanz** [comment]
• What is the purpose of this token? How will it benefit Trust Wallet users?
 • How is the token being distributed? Are you conducting an airdrop?
 • Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?
 • Is the token listed on a centralized/decentralized exchange?
 • Is a Smart Contract audit completed? Where can we find this information?

**Comment by DEMONNNX** [comment]
What is the purpose of this token?
$DEMON is the native token which allowing users to participate in the whole Demon Ecosystem. The utilities for $DEMON are earning from the yield aggregator services, lottery games ticket, trading on DemonX NFTs, mystery boxes consumption and gamefi participation. Holders of $DEMON token are allow to generate their profit by participating in every single part of Demon Ecosystem’s products. To get more information, may refer to our gitbook： https://demonecosystem.gitbook.io/demon-finance/protocol/tokenomics

How is the token being distributed? Are you conducting an airdrop?
Private Sales 10% - 10,000,000,000 DEMON
Airdrops 1% - 1,000,000,000 DEMON
Initial Liquidity Pool 1% - 1,000,000,000 DEMON
Finance Vault 60% - 60,000,000,000 DEMON
Team 10% - 10,000,000,000 DEMON
lDAO Treasury (Market Making, Operations, Marketing, Partnerships, etc.) 10% - 10,000,000,000 DEMON
Technical Development 8% - 8,000,000,000 DEMON
Yes, we are givingaway airdrops in our marketing program in order to make better exposure and market growth. Moreover, we are willing to collaborate with partners which can reach both parties mutual benefits by airdrop events such as PancakeSwap.

Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?
Yes, we do have private sales event for our primeval community before listing to PancakeSwap.

Is the token listed on a centralized/decentralized exchange?
$DEMON token is allowed to trade at PancakeSwap now. We are planning to list the token at centralized exchange in the near future. 

Is a Smart Contract audit completed? Where can we find this information?
Our audit is done by Lunaray Blockchain Security, as refer to https://lunaray.co/projectdetails

**Comment by DEMONNNX** [comment]
@cryptomanz Thanks.

**Pull request merged**
