### PR TITLE
Add Wrapped ElectricCash (BEP20)

### PR DESCRIPTION
**Pull request by krecik**
Adding info for BEP20 token 'Wrapped ElectricCash'.

### CODE REVIEW

**Comment by cryptomanz** [comment]
• What is the purpose of this token? How will it benefit Trust Wallet users?
 • How is the token being distributed? Are you conducting an airdrop?
 • Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?
 • Is the token listed on a centralized/decentralized exchange?
 • Is a Smart Contract audit completed? Where can we find this information?

**Comment by krecik** [comment]
What is the purpose of this token? How will it benefit Trust Wallet users?

Wrapped ELCASH (wELCASH) is a BEP-20 token representing ELCASH on the Binance Smart Chain blockchain. The idea behind it was to make it possible for users to take part in decentralized finance (DeFi). Users can create wELCASH tokens by storing ELCASH with a custodian. They can also send wELCASH back and receive ELCASH in return.

The wELCASH tokens can only be minted when backed by ELCASH. The value of wELCASH is always pegged to ELCASH on a 1:1 ratio.

By using wELCASH, users get the opportunity to take advantage of the Binance Smart Chain infrastructure and gain exposure to smart contract functionalities. Introducing new use cases relating to smart contracts and decentralized applications (dApps) ensures further growth of the ELCASH ecosystem. These include DeFi yield farming and lending platforms, BEP-20 compatible wallets and many more.

How is the token being distributed? Are you conducting an airdrop?

Users can convert ELCASH to wELCASH, using a converter built by our team. The converter is available here: https://wrapped.elcash.info We also made tutorials for users:

PDF version: https://elcash.info/pdf/electric-cash-welcash-tutorial.pdf

Video version: https://www.youtube.com/watch?v=JaoLAcdQlzo

At this moment we do not have plans to conduct an airdrop but we do not exclude this option.

Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?

No, we did not sell the tokens at ICO and we did not organize a presale. Information about wELCASH was added on our official website and on ELCASH’s social media profiles.

Is the token listed on a centralized/decentralized exchange?

wELCASH is already listed on PancakeSwap. You can check it here: https://pancakeswap.finance/swap?outputCurrency=0x1722bf5DA9391D6986092b90a53672E8E0fead83

Is a Smart Contract audit completed? Where can we find this information?
wELCASH has been audited by CertiK. CertiK leads blockchain security by pioneering the use of cutting-edge Formal Verification technology on smart contracts and blockchains. Unlike traditional security audits, Formal Verification mathematically proves program correctness and hacker-resistance.

**Comment by cryptomanz** [comment]
Please send me your audit.

**Comment by krecik** [comment]
[REP-ELECTRIC-VAULT-SPÓKA-Z-OGRANICZON-2021-09-28.pdf](https://github.com/trustwallet/assets/files/7808576/REP-ELECTRIC-VAULT-SPOKA-Z-OGRANICZON-2021-09-28.pdf)

**Pull request merged**
