### PR TITLE
Add files via upload

### PR DESCRIPTION
**Pull request by UBITSCANCOIN**

### CODE REVIEW

**Comment by UBITSCANCOIN** [comment]
we have listed at Coingecko then can we update logo? we also have audit report

**Comment by UBITSCANCOIN** [comment]
logo
[info.json](https://github.com/trustwallet/assets/files/14976107/info.json)

**Comment by Cryptocool1** [comment]
Please create new PR, follow doc https://developer.trustwallet.com/listing-new-assets/requirements
You may want to try our Assets app in beta; go to https://assets.trustwallet.com, log on with Github, enter contract ID, logo and some additional info, and it will create a PR for you.
See https://developer.trustwallet.com/listing-new-assets/repository_details

**Comment by UBITSCANCOIN** [comment]
i want to list our token and its on our own blockchain, can we update?

**Comment by UBITSCANCOIN** [comment]
because there is no option of new blockchain token to update

**Comment by UBITSCANCOIN** [comment]
hello

**Pull request closed without merging**
