### PR TITLE
Add KPN info and logo

### PR DESCRIPTION
**Pull request by VeniGroup**
CMC: https://coinmarketcap.com/currencies/konnektvpn

Audit 1: https://skynet.certik.com/projects/konnektvpn

Audit 2: https://www.cyberscope.io/audits/kpn

### CODE REVIEW

**Comment by VeniGroup** [comment]
Hope you consider the liquidity and volume and most importantly the utility of the project, without refusing us over holders <3

**Comment by Cryptocool1** [comment]
As per our policy, brand new tokens are not included, there is a minimum requirement of 10,000 holder addresses and 15,000 transactions.
See the criteria at : https://developer.trustwallet.com/assets/requirements .

**Comment by Cryptocool1** [comment]
As per our policy, brand new tokens are not included, there is a minimum requirement of 10,000 holder addresses and 15,000 transactions.
See the criteria at : https://developer.trustwallet.com/assets/requirements .

**Comment by Cryptocool1** [comment]
feel free to come back to us once all criteria are met. Make sure to mention this PR so the fee can be reused

**Comment by VeniGroup** [comment]
Good day. Please re-check our request as our token is not brand new. also, it has more than 60k transactions; the holders' task is almost impossible for us as we mainly focus on CEXs, and people hold tokens there. We read tokens with real utility and good liquidity stability + Audit from tier 1 auditors might get a pass on holders numbers, can you please re-evaluate our request? thanks

**Pull request closed without merging**
