### PR TITLE
Add Blockzero Labs (erc20)

### PR DESCRIPTION
**Pull request by johnblockzero**
Adding info for erc20 token 'Blockzero Labs'.

PR created by <a href="https://assets.trustwallet.com">TW Assets Management</a>

### CODE REVIEW

**Comment by johnblockzero** [comment]
Hi this is related to my last previous request closed one day ago: [trustwallet/assets] Add XIO (erc20) (#5416)

That previous request was to update our two tokens:
Flashtake (FLASH): https://www.coingecko.com/en/coins/flash-stake
Blockzero Labs (XIO): https://www.coingecko.com/en/coins/blockzero-labs 

I requested revised logo updates but the admin did not accept the updates. 

Can you please update the two tokens using the below logos?

Logo_FLASH

Logo_Blockzero XIO

**Comment by johnblockzero** [comment]
Hi @catenocrypt i see you've merged. I've reinstalled TrustWallet to see changes but the XIO logo hasn't updated. Note the new one I submitted has a darker black background. This is why I submitted a new logo.

**Comment by catenocrypt** [comment]
Due to caching on different levels it takes some time (up to one day), so let's wait some more.

**Comment by johnblockzero** [comment]
Ok thanks @catenocrypt! Just wanted to make sure BOTH logos were updated 😀 

I'll check again in the next few days.

**Comment by johnblockzero** [comment]
Hi Adam

Since our last correspondence, we had to update our token smart contract due to a bug: https://twitter.com/Flashstake/status/1368234880069472258?s=20 <https://twitter.com/Flashstake/status/1368234880069472258?s=20>

The updated token is now on Uniswap and I need to update the logo: https://info.uniswap.org/pair/0x31d9b2D096C7aBD1Cf9a3CC8f1982E5FFCA09C47 <https://info.uniswap.org/pair/0x31d9b2D096C7aBD1Cf9a3CC8f1982E5FFCA09C47>

However, due to migration from FLASH v1 to FLASH v2 not yet happening until next week, the TrustWallet Submit a Token Logo form is giving error for having less than 2500 users. 

Are you able to allow exception as it’s the same token that you previously updated? We will of course pay for this new logo update. 

This is the updated token as reflected in CoinGecko: https://www.coingecko.com/en/coins/flash-stake <https://www.coingecko.com/en/coins/flash-stake>

Please let me know the process.

Thanks,
John

John Velasco
john@blockzerolabs.io

**Comment by catenocrypt** [comment]
@johnblockzero , in this case we make an exception form the circulation requirement.
Please create a new PR, and also mention a reference to this one.
Unfortunately the Assets App will not be possible to use, it has the circulation check built-in.  You will need to create the PR manually.

**Comment by johnblockzero** [comment]
Ok thanks Adam, I’ll give that a go! 

John Velasco
john@blockzerolabs.io

**Comment by johnblockzero** [comment]
I have created PR 
Update FLASH logo #5854

I will organise payment now. 

John Velasco
john@blockzerolabs.io

**Pull request merged**
