### PR TITLE
Please update old contract address to new one and change its logo.

### PR DESCRIPTION
**Pull request by aliarzani**
old

0x9513d8679677be3d57c7cdd30561105ee1452d69

--------------------------------------------------------------------------

new

0xc5bb5ec4d6d69f32b6cb5b7766fd5f4ec946c58a

-----------------------------------------------------------

http://pythonex.net/wp-content/uploads/2021/02/logo.png

link of new logo

### CODE REVIEW

**Comment by aliarzani** [comment]
solved

**Comment by aliarzani** [comment]
Some checks haven’t completed yet

solveddd

**Comment by catenocrypt** [comment]
Files in this PR has wrong structure.  Clsoing.

- Update your assets clone to latest from master (or re-create)
- remove old logo files (logo, info)
- add new logo files to folder with new contract ID -- should be in checksum format (logo, file).  Moving of the files is even better
- we check the PR
- pay the fee
- we merge

**Comment by aliarzani** [comment]
We are going to cancel any changing in our token. We continue with the old
version. Thanks Adam



regards


Atash Zaban

**Pull request closed without merging**
