### PR TITLE
Add Ariva (ERC20)

### PR DESCRIPTION
**Pull request by ariva-digital**
Adding info for ERC20 token 'Ariva'.

PR created by <a href="https://assets.trustwallet.com">TW Assets Management</a>

### CODE REVIEW

**Comment by cryptomanz** [comment]
can you send an official announcement about migration ?

**Comment by ariva-digital** [comment]
Hi @cryptomanz 
https://twitter.com/arivacoin/status/1460273445888008196?s=21&t=-vnY-AiDvhRNe-CTMoy0SA
This is the official announcement

**Comment by cryptomanz** [comment]
#19763

**Comment by cryptomanz** [comment]
#19765

**Pull request closed without merging**
