### PR TITLE
Add SEED token

### PR DESCRIPTION
**Pull request by modagavr**
SEED - Second token in our first global “Fun & Rich” blockchain ecosystem.
Swap/NFT/Staking/Farming platform -  is one of the products of SafeHamsters Planet ecosystem names HamstersMill, with its native token SEED, which the second basic token in our first global “Fun&Rich” blockchain ecosystem.

### CODE REVIEW

**Comment by Cryptocool1** [comment]
can you please add links to your PR?
example: https://developer.trustwallet.com/add_new_asset#info-json-contents

**Comment by Cryptocool1** [comment]
- cant find contract on your website
please check/add

**Comment by modagavr** [comment]
> * cant find contract on your website
>   please check/add

Fixed

image

**Comment by Cryptocool1** [comment]
Could you answer some questions?
• What is the purpose of this token? How will it benefit Trust Wallet users?
 • How is the token being distributed? Are you conducting an airdrop?
 • Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?
 • Is the token listed on a centralized/decentralized exchange?
 • Is a Smart Contract audit completed? Where can we find this information?

**Comment by Cryptocool1** [comment]
still no answer after 2 days.
please create new PR after you will be ready to chat.
you don't need to pay one more time
make sure to mention this PR

**Pull request closed without merging**
