### PR TITLE
Add AMPLG token

### PR DESCRIPTION
**Pull request by AmpleGold**
Please add the AMPLG token -- www.amplegold.io
Contract address: https://etherscan.io/token/0x8003C49f6ebACDdC493EA47CAB45e892d1B638a1

### CODE REVIEW

**Comment by catenocrypt** [comment]
Please add an `info.json` file next to the `logo.png`, with info about the project, of the form:

```json
{
    "name": "Trust Wallet Token",
    "website": "https://trustwallet.com",
    "short_description": "Utility token to increase adoption of cryptocurrency.",
    "explorer": "https://explorer.binance.org/asset/TWT-8C2"
}
```

**Comment by AmpleGold** [comment]
We have added the info.json file and provided the payment of 2BNB.

**Comment by catenocrypt** [comment]
-  X 'Folder structure for chain ethereum (ethereum fork)': 'Expect asset at path /home/runner/work/assets/assets/blockchains/ethereum/assets/0x8003c49f6ebacddc493ea47cab45e892d1b638a1 in checksum: '0x8003C49f6ebACDdC493EA47CAB45e892d1B638a1'
I can fix this

**Comment by AmpleGold** [comment]
Please fix and proceed with adding AMPLG token.

**Comment by AmpleGold** [comment]
We would like to have the token added ASAP.

**Pull request merged**
