### PR TITLE
Add logo and info IMPCOIN (BEP20)

### PR DESCRIPTION
**Pull request by ghost**
Add logo and info Imperium IMPCOIN (BEP20)

### CODE REVIEW

**Comment by cryptomanz1** [comment]
• What is the purpose of this token? How will it benefit Trust Wallet users?
 • How is the token being distributed? Are you conducting an airdrop?
 • Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?
 • Is the token listed on a centralized/decentralized exchange?
 • Is a Smart Contract audit completed? Where can we find this information?

**Comment by vts666** [comment]
1.The purpose of the IMPERIUM COIN token is to enhance the functionality and accessibility of financial services for Trust Wallet users. This token will enable users to conduct secure online payments, participate in investment activities, and utilize decentralized financial applications. As a result, Trust Wallet users will be able to expand their financial toolkit and gain access to additional opportunities in the world of cryptocurrencies.
2.The IMPERIUM COIN token will be distributed through various channels, including cryptocurrency exchanges, decentralized finance platforms (DEX), as well as participation in various marketing and partnership programs. Token distribution will adhere to international standards and regulatory requirements, ensuring transparency and security for all participants.
3.That's what we're doing now, but our investors and users, use trust wallet. That's why we want to list on trust wallet, so that it will be more convenient for our users to distribute our token.
4.Our token is now listed on dex exchanges such as pancake, our goal is to list on kucoin, huobi. 
5.https://gopluslabs.io/token-security/56/0x5FE7D4aD1794365f6812cf425a99484444417EDD
https://apespace.io/bsc/0x440029ffe412d95f2f7d6b2c58e173bee4c2eac5

**Comment by Cryptocool1** [comment]
Hello, we require full smart contract audit from reputable company (Techrate, Certik, Hacken, Dessert Finance)

**Comment by cryptomanz1** [comment]
Feel free to come back to us once audit is done. Make sure to mention this PR so the fee can be reused

**Pull request closed without merging**
