### PR TITLE
SmurfsINU logo update

### PR DESCRIPTION
**Pull request by SmurfsINUDeployer**
Hello, we have reached 17k holders and most of the community are using TrustWallet and asked us to at least upload our logo.
We applied for this and we can make an incorrect/incomplete application.
In order to ensure this as quickly as possible, we would appreciate it if you would contact us one-on-one via our e-mail address. with our respect and love

### CODE REVIEW

**Comment by SmurfsINUDeployer** [comment]
Ödemeyi gönderiyoruz ama gönderilen json dosyasında hata mı var? Orada bir kırmızı işaretler var da yolundan emin olmak istiyoruz

**Comment by SmurfsINUDeployer** [comment]
I will make the payment, but is there an error in the json file we sent? There is a red mark there, but first we want to make sure the files are correct.

**Comment by SmurfsINUDeployer** [comment]
I will make the payment, but is there an error in the json file we sent?
There is a red mark there, but first we want to make sure the files are
correct.

merge-fee-bot[bot] ***@***.***>, 16 Ağu 2022 Sal, 02:44
tarihinde şunu yazdı:

**Comment by SmurfsINUDeployer** [comment]
Failed to get info.json content: failed to unmarshal json: invalid character ':' after top-level value? Guys, we can't solve it, can you please tell us how to do it?

**Comment by SmurfsINUDeployer** [comment]
Friends, we tried to fix the json file 30 times, but it always gave an error. We removed our latest coinecko info but it doesn't matter.
I still want to leave our link:
https://www.coingecko.com/en/smurfsinu
https://www.binance.com/en/price/smurfsinu
https://crypto.com/price/smurfsinu
It's a platform we don't know how to use. We apologize if we caused you any difficulties. We may not be able to fulfill the conditions, the important thing is to produce solutions within the framework of mutual respect and love. With respect and love to the entire TrustWallet team.

**Comment by Cryptocool1** [comment]
This is a BEp20 token, correct folder is blockchains/smartchain/assets. 
Please create new PR, follow doc https://developer.trustwallet.com/assets/requirements
You may want to try our Assets app in beta; go to https://assets.trustwallet.com, log on with Github, enter contract ID, logo and some additional info, and it will create a PR for you.
See https://developer.trustwallet.com/assets/repository_details

**Comment by Cryptocool1** [comment]
Make sure so mention this PR so the fee can be reused

**Comment by SmurfsINUDeployer** [comment]
> Make sure so mention this PR so the fee can be reused

https://github.com/trustwallet/assets/pull/21976

**Pull request closed without merging**
