### PR TITLE
Add Crypto Legions V3 (BEP20)

### PR DESCRIPTION
**Pull request by abu7shish**
Adding info for BEP20 token 'Crypto Legions V3'.

PR created by <a href="https://assets.trustwallet.com">TW Assets Management</a>

### CODE REVIEW

**Comment by Cryptocool1** [comment]
As per our policy, brand new tokens are not included, there is a minimum requirement of 10,000 holder addresses and 15,000 transactions, in order to filter out scam tokens.
See the criteria at : https://developer.trustwallet.com/assets/requirements .

**Comment by Fuad369** [comment]
انا اوافق

**Comment by Cryptocool1** [comment]
please come back to us when all criteria are met. Make sure to mention the PR so the fee can be reused

**Comment by abu7shish** [comment]
> please come back to us when all criteria are met. Make sure to mention the PR so the fee can be reused

can we apply again, or we must wait?

**Pull request closed without merging**
