### PR TITLE
Add Parabolic (BEP20)

### PR DESCRIPTION
**Pull request by InuXiasi**
Adding info for BEP20 token 'Parabolic'.

PR created by <a href="https://assets.trustwallet.com">TW Assets Management</a>

### CODE REVIEW

**Comment by Cryptocool1** [comment]
hello, could you answer the questions?
• What is the purpose of this token? How will it benefit Trust Wallet users?
 • How is the token being distributed? Are you conducting an airdrop?
 • Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?
 • Is the token listed on a centralized/decentralized exchange?
 • Is a Smart Contract audit completed? Where can we find this information?

**Comment by InuXiasi** [comment]
1. The token will benefit TW users by our Long term plans and future integrations.
2. Parabolic is distributed through Pancakeswap and may hold airdrops for its users to earn in the future.
3.  We had a presale on DX prior to launch for WL adresses only min buy 0.1BNB max buy 5BNB small cap 400bnnb hardcap 1200bnb was filled in 10mins
4. We are currently listed on the DEX PancakeSwapV2
5. Our smart contract Audit is currently being made by Techrate.

**Comment by Cryptocool1** [comment]
What is the purpose of this token?

**Comment by InuXiasi** [comment]
The purpose off the token is to provide a steady investment for its holders and by our Tokenomics. 
Our game will release in november and we will continously integrate new use cases to Parabolic.

**Pull request merged**
