### PR TITLE
Add TLN info and logo

### PR DESCRIPTION
**Pull request by Smokyish**
This PR is being closed due to inactivity. If you wish to continue, please have us reopen the PR before sending your payment.
Do NOT send payments for closed PR, as the fee may by lost!
  (359 vs. 60 hrs)

### CODE REVIEW

**Comment by Smokyish** [comment]
Hello, please reopen this PR, the community is now prepared to do the fee payment.

**Comment by catenocrypt** [comment]
Reopening

**Comment by Smokyish** [comment]
@catenocrypt Thank you for the re-opening but the less than an hour window unfortunately wasn't enough to notice the open and for the community to pay the fee.

I assume the address and memo will remain the same after a re-open that were mentioned previously in the PR?

**Comment by catenocrypt** [comment]
If fee has been paid, it is noticed at the moment of reopening

**Comment by Smokyish** [comment]
@catenocrypt Okay, so are you saying that the fee can be paid now, even while the PR is closed, as the bot is explicitly saying not to do that?

https://github.com/trustwallet/assets/pull/4098#issuecomment-704784336
> Do NOT send payments for closed PR, as the fee may by lost!

That's why the payment has been attempted to get done after the re-open, but missing that window before the bot closes it again.

**Comment by catenocrypt** [comment]
Yes, it will be picked up automatically at the moment of reopening.  Don't worry, if a payment was made and TXID is available, payment will not be lost.

**Comment by Smokyish** [comment]
@catenocrypt Thank you for the clarification, the payment has been sent :)

**Pull request merged**
