### PR TITLE
Add FREEMOON (BEP20)

### PR DESCRIPTION
**Pull request by freemoon-protocol**
Adding info for BEP20 token 'FREEMOON'.

PR created by <a href="https://assets.trustwallet.com">TW Assets Management</a>

### CODE REVIEW

**Review by Echalon2020 — APPROVED** [review]

**Comment by cryptomanz** [comment]
Hello,
Can your answer some questions?
• What is the purpose of this token? How will it benefit Trust Wallet users?
 • How is the token being distributed? Are you conducting an airdrop?
 • Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?
 • Is the token listed on a centralized/decentralized exchange?
 • Is a Smart Contract audit completed? Where can we find this information?

**Comment by freemoon-protocol** [comment]
The purpose of this token is to populate the coin and the smart binance chain. We plan to trade on the binance blockchain on many exchanges and want a logo in the trust wallet wallet. What we will inform all our users through our bot. We have released a guide on how to buy through a trust vallet and we recommend your wallet to everyone. https://freemoon.finance/trust-wallet
The token is distributed through a swap. https://pancakeswap.finance/info/pool/0xb24da9dcb23f5cafd0dc398ee3f3c516303be0ad
Airdrop distribution will begin on September 30th. Now we only have a swap. In order to order an advertisement, we need to get a logo. This will build more credibility.
No, we did not conduct ico and no primary sale. Swap only.
Yes, the liquidity pool has been posted on the pancakeswap https://pancakeswap.finance/info/token/0x31f0bc450c12eb62b4c617d4c876f7a66470fcb3
We have not ordered an audit yet, but we have frozen the liquidity pool for 4 years https://cointool.app/token/lock?a=0xb24da9dcb23f5cafd0dc398ee3f3c516303be0ad&c=56. Our task now is to popularize our token in order to increase sales. And then we will order an audit. We don't want big wallets now, so that people would buy a coin in small quantities and its price would rise. Stable.

**Comment by cryptomanz** [comment]
Awaiting for smart contract audit.

**Comment by Cryptocool1** [comment]
Please create new Pr when smart contract audit will be ready. 
make sure to mention this PR, so the fee can be reused.

**Comment by freemoon-protocol** [comment]
https://solidity.finance/audits/FREEMOON-BSC/

**Pull request closed without merging**
