### PR TITLE
Add Binamon!

### PR DESCRIPTION
**Pull request by binamon**
Binamon add to Trustwallet

### CODE REVIEW

**Comment by Cryptocool1** [comment]
hello,
can you please answer some questions?
• What is the purpose of this token? How will it benefit Trust Wallet users?
 • How is the token being distributed? Are you conducting an airdrop?
 • Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?
 • Is the token listed on a centralized/decentralized exchange?
 • Is a Smart Contract audit completed? Where can we find this information?

**Comment by Cryptocool1** [comment]
hello,
can you please answer some questions?
• What is the purpose of this token? How will it benefit Trust Wallet users?
 • How is the token being distributed? Are you conducting an airdrop?
 • Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?
 • Is the token listed on a centralized/decentralized exchange?
 • Is a Smart Contract audit completed? Where can we find this information?

**Comment by binamon** [comment]
Hi! Good evening!
Yes sure!!

• What is the purpose of this token? How will it benefit Trust Wallet users?
With BMON the users can buy boosters of NFT. The boosters have 3 monsters.
Through a smart contract called Booster, the NFTs will be minted (BEP721) ,
using the $BMON token (BEP-20).  Community Governance.  Buy NFT in its
physical variant . Entry fee and rewards in tournaments


• How is the token being distributed? Are you conducting an airdrop?
Seed, pre-sale. Now is on Dextools:
https://www.dextools.io/app/pancakeswap/pair-explorer/0x2baccc1e3900e

• Did you sold the tokens at an Initial Coin Offering (ICO) or a token
presale?
Yes! https://binamon.org/wp-content/uploads/2021/06/BINAMON-TOKENOMICS-1.pdf

• Is the token listed on a centralized/decentralized exchange?
Yes! https://www.dextools.io/app/pancakeswap/pair-explorer/0x2baccc1e3900e

• Is a Smart Contract audit completed? Where can we find this information?
Yes audited!
https://github.com/Quillhash/Audit_Reports/blob/master/Binamon%20Smart%20Contract%20Audit%20Report%20-%20QuillAudits.pdf

Thanks!!

**Comment by cryptomanz** [comment]
The description should tell what the token is for or what it does
please change

**Comment by cryptomanz** [comment]
can you please add links to your PR?
example: https://developer.trustwallet.com/add_new_asset#info-json-contents

**Comment by binamon** [comment]
Hi! I updated the Json file and created a new PR:

https://github.com/binamon/assets/pull/2

**Comment by Cryptocool1** [comment]
can you please add links to your PR?
example: https://developer.trustwallet.com/add_new_asset#info-json-contents

**Comment by binamon** [comment]
Hi!

I don't really understand what you're asking for. I think this must be it:

blockchains/smartchain/0x08ba0619b1e7A582E0BCe5BBE9843322C954C340/info.json
blockchains/smartchain/0x08ba0619b1e7A582E0BCe5BBE9843322C954C340/logo.png

It´s ok??

**Comment by Cryptocool1** [comment]
You need add links

**Comment by binamon** [comment]
This is ok??

https://github.com/binamon/assets/pull/2/files#diff-e2388a2e250d0acc8df1219cef393de9f4afe471a10c09d38de9a1401a4c2b57

**Comment by binamon** [comment]
Ahh!! I undestand now!!

**Comment by binamon** [comment]
Done!!!
I added links!! It´s ok?

https://github.com/binamon/assets/pull/3

Thanks so much!!

**Comment by Cryptocool1** [comment]
fixed

**Comment by binamon** [comment]
You are the best!! How long will we see the update in the application?
Thanks

**Pull request merged**
