### PR TITLE
Add BCMC1 logo & info

### PR DESCRIPTION
**Pull request by bcmc-support1**

### CODE REVIEW

**Comment by Cryptocool1** [comment]
Hello,
Your contract is not in checksum format, it should be 0x739C4AB4cD5D00DFD2e906fB64d01513557D8Edb

**Comment by vikmeup** [comment]
I think there is an issue with using CoinMarketCap trademark, do you have legal documents for allowed usage?

**Comment by bcmc-support1** [comment]
We do not use other people's trademarks. We're all right. Thank you for the
experience.

пн, 19 апр. 2021 г. в 21:59, Viktor Radchenko ***@***.***>:

**Comment by bcmc-support1** [comment]
BeforeCoinMarketCap is a single word. And please note that
BeforeCoinMarketCap and CoinMarketCap are completely different words. I
don't understand what you want to find fault with. But you can do whatever
you want. we have everything in order with the brand and trademark.

пн, 19 апр. 2021 г. в 23:41, Viktor Radchenko ***@***.***>:

**Comment by bcmc-support1** [comment]
> Before**CoinMarketCap** - do you have permission from CoinMarketCap team to use this trademark/branding?
> 
> I would have to close this pull request due to the team issue.

Hello! Kindly re-open my pull request.

We do not operate as a Coinmarketcap Company. The name underlines our distinctive business. Our job is to maintain a token or a coin from the moment of their creation, until they enter the CoinMarketCap, or will be removed from all exchanges, that is as soon as the Coinmarketcap starts to display this or that token, we stop any audit on it. In the future, we hope to cooperate with the Coinmarketcap Company to build a Global Cryptocurrency search engine.

You can also find our token on CoinMarketCap 
https://coinmarketcap.com/currencies/beforecoinmarketcap/

**Comment by bcmc-support1** [comment]
> Before**CoinMarketCap** - do you have permission from CoinMarketCap team to use this trademark/branding?
> 
> I would have to close this pull request due to the team issue.

Please, complete my pull request! I have already made payment

Thank you!

**Comment by bcmc-support1** [comment]
> Before**CoinMarketCap** - do you have permission from CoinMarketCap team to use this trademark/branding?
> 
> I would have to close this pull request due to the team issue.
Hi! How can we change token information? We want to add our price to the app, is it possible? Thank you.

**Pull request merged**
