### PR TITLE
Add P2E Token (BEP20)

### PR DESCRIPTION
**Pull request by P2Exyz**
Adding info for BEP20 token 'P2E Token'.

PR created by <a href="https://assets.trustwallet.com">TW Assets Management</a>

### CODE REVIEW

**Comment by P2Exyz** [comment]
> Adding info for BEP20 token 'P2E Token'.
> 
> PR created by [TW Assets Management](https://assets.trustwallet.com)


Re: [trustwallet/assets] add P2E logo and info (PR #16359)

We have paid, but the system requires us to re-PULL, please check.
Closed #16359

PLZ Check https://github.com/trustwallet/assets/pull/16359

**Comment by Cryptocool1** [comment]
What is the purpose of this token? How will it benefit Trust Wallet users?
 • How is the token being distributed? Are you conducting an airdrop?
 • Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?
 • Is the token listed on a centralized/decentralized exchange?
 • Is a Smart Contract audit completed? Where can we find this information?

**Comment by P2Exyz** [comment]
> What is the purpose of this token?
- PLS2E.io = DAO+DEX+NFTs+GameFi LaunchPad. 
Please refer to our dec：https://docs.pls2e.io/

• How will it benefit Trust Wallet users? 
-  We can provide TOKEN and NFT airdrops to TrustWallet customers.

• How is the token being distributed? Are you conducting an airdrop? 
- We are on a bounty mission and plan to fill up our DEX LP pool by selling NFT cards

• Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?
- No ICO and Presell，We want to do IGO

• Is the token listed on a centralized/decentralized exchange? 
Yes,Our own Dex here：https://www.pls2e.io/

• Is a Smart Contract audit completed? Where can we find this information?
Please Check We will give customers the safest environment  https://www.certik.com/projects/pls2e
@Cryptocool1

**Comment by P2Exyz** [comment]
> What is the purpose of this token? How will it benefit Trust Wallet users? • How is the token being distributed? Are you conducting an airdrop? • Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale? • Is the token listed on a centralized/decentralized exchange? • Is a Smart Contract audit completed? Where can we find this information?

and this is our Dapp ：https://www.pls2e.io/
P2E Token For PLS2E.io ：https://docs.pls2e.io/Economic_model_and_governance/P2E_token_economy

@Cryptocool1

**Pull request merged**
