### PR TITLE
Criptoblock (CBK)

### PR DESCRIPTION
**Pull request by criptoblock**
Please add my token named: Criptoblock with symbol: CBK

### CODE REVIEW

**Comment by kolya182** [comment]
@criptoblock What is the actual address, can't find it in your PR ?

**Comment by criptoblock** [comment]
My real address is: https://github.com/criptoblock
My token id is: 1002570
My Symbol: CBK
Name Token: Criptoblock

**Comment by kolya182** [comment]
Do you have just a logo with out text ?

**Comment by criptoblock** [comment]
No, my logo consists of the symbol I put in the repository and the currency text. Here we have the complete logo: www.criptoblock.com.br

But for the Token, let's just show the repository symbol

**Comment by kolya182** [comment]
Image already exist https://github.com/trustwallet/assets/tree/master/blockchains/tron/assets/1002570

**Pull request closed without merging**
