### PR TITLE
Add Dione (DIONE) (ERC20)

### PR DESCRIPTION
**Pull request by DioneProtocol1**
Adding info for ERC20 token 'Dione (DIONE)'.

PR created by <a href="https://assets.trustwallet.com">TW Assets Management</a>

### CODE REVIEW

**Comment by DioneProtocol1** [comment]
Admin said to mention last PR so payment can be used towards this one. Last PR: 
Add Dione (DIONE) (ERC20) #25384

+ Holder count drastically increased with 20+% of supply on MEXC and 3+% of supply on Gate Io
+ Social media organic activity has gone parabolic
+ 2M+ daily organic trading volume consistently on CMC

Please update our Trust Wallet status as hundreds of community members are requesting this, as well as our legal counsel, so we don't look like a scam coin.

Thanks!

**Comment by Cryptocool1** [comment]
As per our policy, there is a minimum requirement of 10,000 holder addresses and 15,000 transactions.
See the criteria at : https://developer.trustwallet.com/listing-new-assets/requirements .

**Comment by DioneProtocol1** [comment]
Your policy says each is a case by case review. You've been adding tokens with less than that. Dione is well-established for over 1.5 years now with a huge community. What else is needed from my side to make this process smoother?

**Comment by DioneProtocol1** [comment]
Hi @Cryptocool1 We passed 10k holders on-chain.

**Comment by DioneProtocol1** [comment]
Hi @Cryptocool1 We passed 10k holders on-chain.

**Pull request closed without merging**
