### PR TITLE
Add VUSD token info

### PR DESCRIPTION
**Pull request by ozdav97**
Adding info for ERC20 token 'VUSD'.

### CODE REVIEW

**Review by tawhidnazari57 — COMMENTED** [review]
[Uploading patch-6.1.95-rc1.gz…]()

**Comment by cryptomanz1** [comment]
• What is the purpose of this token? How will it benefit Trust Wallet users?
 • How is the token being distributed? Are you conducting an airdrop?
 • Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?
 • Is the token listed on a centralized/decentralized exchange?
 • Is a Smart Contract audit completed? Where can we find this information?

**Comment by ozdav97** [comment]
Hello @cryptomanz1 
Here are the answers for your questions.

1. VUSD is the worlds first centralized stablecoin that has decentralized and real time proof of reserves verifiable in the blockchain. 
2. VUSD can be minted directly with VUSD.com via purchase with crypto or loaned with crypto, as well as purchased in the secondary market  
3. There is no ICO. This is a stablecoin 
4. Yes — Uniswap 
5. [Certik](https://skynet.certik.com/projects/vusd), [PeckShield](https://github.com/peckshield/publications/tree/master/audit_reports/PeckShield-Audit-Report-ERC20-VUSD-v1.0.pdf)

**Comment by Cryptocool1** [comment]
In order for the pull request to be approved, the submission has to meet several important requirements. For this request, it does not meet the following:

- at least 10000 token holders
- at least 15000 transactions

To know more about the token approval guidelines, please check this article: [How to Submit Token Logo](https://developer.trustwallet.com/listing-new-assets/requirements).

Feel free to re-open pull request once you meet those requirements.

**Pull request closed without merging**
