### PR TITLE
Add SafeDrive (BEP20)

### PR DESCRIPTION
**Pull request by yungvizzy**
This PR is being closed due to inactivity. If you wish to continue, please have us reopen the PR before sending your payment, or just create a new one.
Do NOT send payments for closed PR, as the fee may by lost!
  (48 vs. 48 hrs)

### CODE REVIEW

**Comment by yungvizzy** [comment]
fee paid in #12830

**Comment by yungvizzy** [comment]
screenshot2

**Comment by dark-sizter** [comment]
you  wrote:
Thanks for providing the information.
It looks like you paid for the submission while the request was closed.
Please submit a new request and attach these screenshots as proof of payment.
That way, we can review the submission.

**Comment by yungvizzy** [comment]
you  wrote:
Thanks for providing the information.
It looks like you paid for the submission while the request was closed.
Please submit a new request and attach these screenshots as proof of payment.
That way, we can review the submission.

**Comment by yungvizzy** [comment]
screenshot2
screenshot1

**Comment by yungvizzy** [comment]
photo_2021-09-04_21-50-37

**Comment by Cryptocool1** [comment]
hello,
• What is the purpose of this token? How will it benefit Trust Wallet users?
 • How is the token being distributed? Are you conducting an airdrop?
 • Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?
 • Is the token listed on a centralized/decentralized exchange?
 • Is a Smart Contract audit completed? Where can we find this information?

**Comment by yungvizzy** [comment]
more information:

The project is specifically a cryptocurrency based on BSC designed to reward 4% of each transaction to all holders. Thus, personal wealth increases automatically with every purchase or sale.

We do not conduct airdrop. The token is community driven.

We did not sell the token in Initial Coin Offering.

We are listed on pancake swap

We have done our contract audit. Here is the link to the audit.
https://mega.nz/file/ZuoWDQ5Q#_5i4i7rBo81K0E2ioh2Y0kerm_3HwSGG8l0F3GKHp4I

**Pull request merged**
