### PR TITLE
Update BEPRO Information + Logo

### PR DESCRIPTION
**Pull request by Ruiub3i**

### CODE REVIEW

**Comment by catenocrypt** [comment]
As per our policy, brand new tokens are not included, there is a minimum requirement of 2500 holder addresses and 5000 transactions, in order to filter out scam tokens.
See the criteria at (mentioned in the first message by the bot): https://community.trustwallet.com/t/how-to-submit-a-token-logo/3863).
This token has below-limit usage yet (944). Closing PR for now. Please come back to us when all criteria are met.

https://etherscan.io/token/0xcf3c8be2e2c42331da80ef210e9b1b307c03d36a

**Comment by Ruiub3i** [comment]
Hello @catenocrypt,

Our token was already here, and we just updating an already added token - this is NOT a brand new token.

Please accept the pull request

**Comment by Ruiub3i** [comment]
Thank you @catenocrypt

**Comment by catenocrypt** [comment]
The new files are not actually an overwrite (their folder name is not in checksum format, it's all lowercase, so differs only in case, yet git treats them as different).
I have created a new PR with these 2 files (overwriting the existing): #5319 .
Merged.

**Comment by Ruiub3i** [comment]
Thank you!

**Pull request closed without merging**
