### PR TITLE
Add asset files for Monbase

### PR DESCRIPTION
**Pull request by Monbase**
Add Monbase Info and Logo

### CODE REVIEW

**Review by s11dkoba — COMMENTED** [review]
test

**Comment by cryptomanz1** [comment]
As per our policy, there is a minimum requirement of 10,000 holder addresses and 15,000 transactions.
See the criteria at : https://developer.trustwallet.com/listing-new-assets/requirements .

**Comment by Monbase** [comment]
Good day Nazar,

Thank you for your prompt response.

With your policy, are there any other requirements that we don't meet at
the moment? Or is this the only one right now?

For the future, once we meet this requirement, do we need to contact you
again or your system will automatically update?

Thank you so much for your time.

Kind regards.

Monbase Team

Vào Th 4, 3 thg 4, 2024 vào lúc 03:55 Nazar ***@***.***> đã
viết:

**Comment by Cryptocool1** [comment]
Hello, we also require full smart contract audit from reputable companies (such as Techrate, Certik, Hacken, Dessert Finance)
Feel free to create new PR once all requirements are met.

**Comment by Cryptocool1** [comment]
make sure to mention new PR in this one so the fee can be reused.

**Comment by Monbase** [comment]
PR #28028
This is the new PR

**Comment by Monbase** [comment]
PR #28042
This is the new PR

**Pull request closed without merging**
