### PR TITLE
Add Baby CateCoin (BEP20)

### PR DESCRIPTION
**Pull request by wagalaw**
Adding info for BEP20 token 'Baby CateCoin'.

PR created by <a href="https://assets.trustwallet.com">TW Assets Management</a>

### CODE REVIEW

**Comment by ramsty** [comment]
Hi!
Could you answer some questions?
• What is the purpose of this token? How will it benefit Trust Wallet users?
• How is the token being distributed? Are you conducting an airdrop?
• Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?
• Is the token listed on a centralized/decentralized exchange?
• Is a Smart Contract audit completed? Where can we find this information?

**Comment by wagalaw** [comment]
• What is the purpose of this token? How will it benefit Trust Wallet users?
This is a memecoin utility token inspired by CateCoin. The project aims to create a utility for memecoins combining a swap service with a NFT marketplace. This project is over 5500 holders and meets Trust Wallet's regulations. Our big community have all downloaded Trust Wallet and are requesting to be listed in order for our logo to be apparent. 

• How is the token being distributed? Are you conducting an airdrop?
This token is launched on 8th of November and no airdrop was included, all holders have bought manually formulating a big community, an airdrop is not planned as this stage as we support organic growth. 

• Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?
No, this token was fairlaunched giving our community an equal opportunity to buy early before initiating the promotions. 

• Is the token listed on a centralized/decentralized exchange?
Currently, this token is listed on Pancakeswap as a decentralized exchange, however, a variety of centralized exchanges have been in contact and this process is still under study based on our community's votes and team's decision. 

• Is a Smart Contract audit completed? Where can we find this information?
Yes, an audit has been processed and is pending final approval from Techrate Security Audit, the final confirmation will be available in due course and this information will be available on our website starting Sunday 14th November 2021.

**Comment by wagalaw** [comment]
image
[BabyCateCoin free.pdf](https://github.com/trustwallet/assets/files/7523149/BabyCateCoin.free.pdf)

we have audit on progress

**Comment by Cryptocool1** [comment]
awaiting for smart contract audit, on hold for now

**Comment by Cryptocool1** [comment]
Please come back to us when all criteria are met.
When creating a new PR make sure to mention this PR, so that we can see that fee has been paid already here.

**Comment by wagalaw** [comment]
[Baby CateCoin Full Smart Contract Security Audit.pdf](https://github.com/trustwallet/assets/files/7540145/Baby.CateCoin.Full.Smart.Contract.Security.Audit.pdf)

already have the full audit

**Pull request closed without merging**
