### PR TITLE
IHC Token BEP 20

### PR DESCRIPTION
**Pull request by munkh-erdene**

### CODE REVIEW

**Comment by munkh-erdene** [comment]
Please, i missed a folder. I resubmit again on correct folder. My new deposit's memo is 17592 but my previous deposit memo was addressed under 17591. Can you accept my new and corrected order.

**Comment by munkh-erdene** [comment]
TWT

**Comment by cryptomanz** [comment]
This is a BEp20 token, correct folder is blockchains/smartchain/assets/0x86a53fcd199212FEa44FA7e16EB1f28812be911D

**Comment by cryptomanz** [comment]
Please remove this files
Знімок екрана 2022-01-24 о 21 55 48
Знімок екрана 2022-01-24 о 21 56 12

**Comment by cryptomanz** [comment]
Please come back to us when all criteria are met.
When creating a new PR make sure to mention this PR, so that we can see that fee has been paid already here.
Please create new PR, follow doc https://developer.trustwallet.com/assets/requirements
You may want to try our Assets app in beta; go to https://assets.trustwallet.com, log on with Github, enter contract ID, logo and some additional info, and it will create a PR for you.
See https://developer.trustwallet.com/assets/repository_details

**Comment by munkh-erdene** [comment]
Please accept new PR

Created PR 17618   https://github.com/trustwallet/assets/pull/17618

**Comment by munkh-erdene** [comment]
image

**Comment by munkh-erdene** [comment]
> Please come back to us when all criteria are met. When creating a new PR make sure to mention this PR, so that we can see that fee has been paid already here. Please create new PR, follow doc https://developer.trustwallet.com/assets/requirements You may want to try our Assets app in beta; go to https://assets.trustwallet.com, log on with Github, enter contract ID, logo and some additional info, and it will create a PR for you. See https://developer.trustwallet.com/assets/repository_details

Please can you tell us which criteria are not met this request? This request already paid and successfully passed requirement.

**Pull request closed without merging**
