### PR TITLE
Add ECGOD logo and info

### PR DESCRIPTION
**Pull request by ghost**
Request to add logo and info for ElonCryptoGod (ECGOD)

### CODE REVIEW

**Comment by eMauler** [comment]
I reuploaded everything because the first logo was .png.png Please use the second uploaded logo that is .png and the first .json file

**Comment by eMauler** [comment]
Twitter: @ElonCryptoGod for social media presence

**Comment by eMauler** [comment]
submitted

**Comment by cryptomanz** [comment]
correction needed:
- please delete the file "blockchains/smartchain/assets/0x64F9DcD33D9F3A98407EeF67aC8F60CD370961Cf/logo.png.png"

**Comment by eMauler** [comment]
How do I do that it is greyed out when trying to click it? 
image

**Comment by eMauler** [comment]
> correction needed:
> 
> * please delete the file "blockchains/smartchain/assets/0x64F9DcD33D9F3A98407EeF67aC8F60CD370961Cf/logo.png.png"

How do I do that if it is greyed out for me? 
image

**Comment by Cryptocool1** [comment]
deleted

**Pull request merged**
