### PR TITLE
Add MetaBUSDCoin (BEP20)

### PR DESCRIPTION
**Pull request by AliAkczaa**
Adding info for BEP20 token 'MetaBUSDCoin'.

PR created by <a href="https://assets.trustwallet.com">TW Assets Management</a>

### CODE REVIEW

**Review by tyntyn1 — APPROVED** [review]
`

**Comment by tyntyn1** [comment]
https://github.com/trustwallet/assets/pull/21929#issuecomment-1214136136

**Comment by AliAkczaa** [comment]
"[Cryptocool1](https://github.com/Cryptocool1) commented [14 hours ago](https://github.com/trustwallet/assets/pull/21922#issuecomment-1213534858)"

• What is the purpose of this token? How will it benefit Trust Wallet users?
The purpose of this token is to serve a functional role within our suite of Virtual Reality enabled e-commerce solutions. Once fully integrated, eventually becoming a medium of exchange between various tokens in Virtual Reality.
• How is the token being distributed? Are you conducting an airdrop?
This token is currently bought or sold through locked liquidity in the binance smart chain.
• Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?
This token was sold to an initial public presale and through Pancakeswap liquidity pools.
• Is the token listed on a centralized/decentralized exchange?
This token is not currently listed on any centralized exchanges. The token is listed on a few decentralized exchanges.
• Is a Smart Contract audit completed? Where can we find this information?
The token has had a smart contract audit through InterFi. Please find this audit here: https://github.com/interfinetwork/smart-contract-audits/blob/audit-updates/MetaBUSD_0xF14D3692B0055Db9Ca4c04065165d59B87E763f1.pdf


write if everything is ok and I can make a payment.

**Comment by AliAkczaa** [comment]
Do guys? Everything is ok? Can I make a payment?

**Review by mosesojero — APPROVED** [review]

**Review by tae272 — APPROVED** [review]

**Comment by AliAkczaa** [comment]
guys... ??????????????????

**Pull request closed without merging**
