### PR TITLE
Add Swirge coin logo and info

### PR DESCRIPTION
**Pull request by radiancegeorge**
adding swirge coin logo and info

### CODE REVIEW

**Comment by radiancegeorge** [comment]
how do i make payments for the second one (binance smartchain)

**Comment by Iamdeadlyz** [comment]
No need to make the 2nd payment.

As per our policy, brand new tokens are not included. There is a minimum requirement of 500 holder addresses and 1000 transactions in order to filter out scam tokens. See the criteria at (mentioned in the first message by the bot): https://community.trustwallet.com/t/how-to-submit-a-token-logo/3863#how-to-get-approved

This token has below-limit usage yet. This pull request will be put on hold. Please come back to us when all criteria are met.
https://bscscan.com/token/0xe40255c5d7fa7ceec5120408c78c787cecb4cfdb (7, 24)

**Comment by radiancegeorge** [comment]
Okay, will look into that, thank you

**Comment by radiancegeorge** [comment]
Once etherium is up to 1k I can come back, right?

**Comment by radiancegeorge** [comment]
On etherium we have over 500 holders and more than 1k transactions..
Please review that instead, I'll get back to you on binance smartchain

**Comment by radiancegeorge** [comment]
this is for etherium blockchain [](https://etherscan.io/token/0x92ef4ffbfe0df030837b65d7fccfe1abd6549579#balances), please leave out that of binance

**Comment by Iamdeadlyz** [comment]
ETH version is ok. https://etherscan.io/token/0x92ef4ffbfe0df030837b65d7fccfe1abd6549579
So we will remove the BSC files and proceed with the ETH one then?

**Comment by radiancegeorge** [comment]
yes please, thank you!

**Comment by catenocrypt** [comment]
As both are the same token on different blockchain, circulation limit can be considered for both together, so the BSC version can stay as well.
However, the explorer entry is wrong for the BSC version in the info.json, it shoould be 
`https://bscscan.com/token/0xe40255c5d7fa7ceec5120408c78c787cecb4cfdb`
instead of 
`https://etherscan.io/token/0x92ef4ffbfe0df030837b65d7fccfe1abd6549579`
Please change!

**Comment by radiancegeorge** [comment]
corrections have been made on the BSC entry , thank you!.
tho Binance should be left out as agreed, the one on etherium is what we are after.

**Comment by radiancegeorge** [comment]
i guess the same folder naming should be done on Etherium, I'll correct immediately

**Comment by radiancegeorge** [comment]
please delete smartchain files, we need etherium up, thank you!

**Comment by catenocrypt** [comment]
I tried to remove the BEP20 files, but I have no permission to modify the PR in your fork :(
You have to remove them yourself.

```
$ git push Swirge HEAD:master
remote: Permission to Swirge/assets.git denied to catenocrypt.
fatal: unable to access 'https://github.com/Swirge/assets.git/': The requested URL returned error: 403
```

**Comment by radiancegeorge** [comment]
Okay I'll delete the folder entirely... Thank you

**Comment by radiancegeorge** [comment]
done deleting the BEP20 related files, thank you!

**Comment by radiancegeorge** [comment]
thank you!

**Comment by radiancegeorge** [comment]
*Update Info:* SWG** is trading on Uniswap exchange https://info.uniswap.org/pair/0xc2bE5ac16D18891224819e7f2976F3c505Bfc164
 what can be done to reflect price?

**Pull request merged**
