### PR TITLE
Add Dogcoin (BEP20)

### PR DESCRIPTION
**Pull request by shibamaskcoin**
Adding info for BEP20 token 'Dogcoin'.

PR created by <a href="https://assets.trustwallet.com">TW Assets Management</a>

### CODE REVIEW

**Comment by Cryptocool1** [comment]
As per our policy, brand new tokens are not included, there is a minimum requirement of 10,000 holder addresses and 15,000 transactions, in order to filter out scam tokens.
See the criteria at : https://developer.trustwallet.com/assets/requirements .

**Comment by shibamaskcoin** [comment]
> As per our policy, brand new tokens are not included, there is a minimum requirement of 10,000 holder addresses and 15,000 transactions, in order to filter out scam tokens. See the criteria at : https://developer.trustwallet.com/assets/requirements .

But we are already approved in Trust wallet and we migrated to new contract
We also have our own blockchain which you can check here - https://explorer.dogcoin.network/

**Comment by Cryptocool1** [comment]
You are adding 6 files, what are you trying to do?

**Comment by shibamaskcoin** [comment]
> You are adding 6 files, what are you trying to do?

please check #24018
we are not trying to add 6 files we are only trying to verify
you can check our dogcoin gith org profile here
https://github.com/dogcoin-network

**Pull request closed without merging**
