### PR TITLE
Add netcoincapital logo

### PR DESCRIPTION
**Pull request by netcoincapital**

### CODE REVIEW

**Comment by Cryptocool1** [comment]
hello,
• What is the purpose of this token? How will it benefit Trust Wallet users?
 • How is the token being distributed? Are you conducting an airdrop?
 • Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?
 • Is the token listed on a centralized/decentralized exchange?
 • Is a Smart Contract audit completed? Where can we find this information?

**Comment by netcoincapital** [comment]
hello,

• What is the purpose of this token? How will it benefit Trust Wallet users?
ans: The purpose of this token is to provide a powerful processor, create a powerful financial structure, raise the quality of life and help humanity.

• How is the token being distributed? Are you conducting an airdrop?
ans: No The airdrop stage is over

• Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?
ans: Yes, 5% of the tokens are sold in ICO

• Is the token listed on a centralized/decentralized exchange?
ans: yes it listed at coinsbit exchange.

• Is a Smart Contract audit completed? Where can we find this information?
ans: We are in the final stages and we will let you know if you are finished

**Comment by Cryptocool1** [comment]
awaiting for smart contract audit

**Comment by Cryptocool1** [comment]
please create new PR when smart contract audit will be ready. make sure to mention this PR so the fee can be reused

**Pull request closed without merging**
