### PR TITLE
Add VOLT INU logo and info

### PR DESCRIPTION
**Pull request by VoltInu**
Add VOLT INU logo and info

### CODE REVIEW

**Comment by Cryptocool1** [comment]
Please create new PR, follow doc https://developer.trustwallet.com/assets/requirements
You may want to try our Assets app in beta; go to https://assets.trustwallet.com, log on with Github, enter contract ID, logo and some additional info, and it will create a PR for you.
See https://developer.trustwallet.com/assets/repository_details

**Comment by Cryptocool1** [comment]
make sure to mention this PR so the fee can be reused

**Comment by VoltInu** [comment]
Hi,

The above pull requests to update our logo and details on the eth and bsc networks have still not been processed although they were filled and paid a week ago.

Can you please look into it and let us know if something needs to be amended?

Many thanks.

Best regards.

**Comment by Bmg00** [comment]
https://github.com/trustwallet/assets/pull/18525#issuecomment-1060053724

**Pull request closed without merging**
