### PR TITLE
Pleasure Coin 

### PR DESCRIPTION
**Pull request by timvanp**
Added Pleasure coin to on BSC too via the multichain.org bridge.

See  https://github.com/trustwallet/assets/pull/23856 & https://github.com/trustwallet/assets/pull/19444

### CODE REVIEW

**Comment by Cryptocool1** [comment]
As per our policy, brand new tokens are not included, there is a minimum requirement of 10,000 holder addresses and 15,000 transactions, in order to filter out scam tokens.
See the criteria at : https://developer.trustwallet.com/assets/requirements .

**Comment by Cryptocool1** [comment]
Please send your CMC link

**Comment by timvanp** [comment]
https://coinmarketcap.com/currencies/pleasure-coin/

**Comment by Cryptocool1** [comment]
You should add your bsc to CoinMarketCap first.

**Comment by Helpcentera** [comment]
> Added Pleasure coin to on BSC too via the multichain.org bridge.
> 
> See  https://github.com/trustwallet/assets/pull/23856 & https://github.com/trustwallet/assets/pull/19444

We'd be happy to look into this for you. Kindly file a support ticket here
https://forms.gle/zVGLP7GATPsDHdkH9

**Comment by timvanp** [comment]
@Cryptocool1 its listed on CoinMarketcap now too :)

**Pull request merged**
