### PR TITLE
Add JasmyCoin (JASMY) ERC20

### PR DESCRIPTION
**Pull request by toktokds01**
This PR is being closed due to inactivity. If you wish to continue, please have us reopen the PR before sending your payment.
Do NOT send payments for closed PR, as the fee may by lost!
  (71 vs. 60 hrs)

### CODE REVIEW

**Comment by catenocrypt** [comment]
Submission looks OK.  Fee payment pending.

**Comment by toktokds01** [comment]
Dear sir,

 

Thank you for your reply.

I will send you 250TWT but we need few days to prepare.

So please wait for paying.

Thank you.

 

tkotokds01

**Comment by catenocrypt** [comment]
No problem.  The PR may get auto-closed, but don't worry, you may still pay the fee, and we can reopen after payment and it will be noticed.

**Comment by toktokds01** [comment]
Dear sir,

Thank you for your reply.
I am sorry for contacting you late.
250 TWT is ready.
Would you please return the status to open?
Thank you.

tkotokds01

**Pull request closed without merging**
