### PR TITLE
Moon Stop logo submission (BEP20)

### PR DESCRIPTION
**Pull request by MOTHBODY-MOTH**
Moon Stop logo for trust wallet.

### CODE REVIEW

**Comment by MOTHBODY-MOTH** [comment]
Hello, it is telling me my logo was not accepted so I reuploaded the logo named logo.png. Am i good to make the payment now?

**Comment by Cryptocool1** [comment]
PR should include only 2 files:

blockchains/smartchain/assets/0x150159c72f0f9ef9000bf95e242de6682480d6d3/info.json
blockchains/smartchain/assets/0x150159c72f0f9ef9000bf95e242de6682480d6d3/logo.png

**Comment by MOTHBODY-MOTH** [comment]
@Cryptocool1 can you try running it now. i deleted the original folder with 3 files and replaced it with a folder with JUST the two precision named files.

**Comment by Cryptocool1** [comment]
> @Cryptocool1 can you try running it now. i deleted the original folder with 3 files and replaced it with a folder with JUST the two precision named files.

You need to delete this file blockchains/smartchain/logo.png

**Comment by MOTHBODY-MOTH** [comment]
@Cryptocool1 i just updated to all uppercase as well. anything else i need to do?

**Comment by Cryptocool1** [comment]
Contract is not in checksum format, should be 0x150159C72F0F9Ef9000BF95E242dE6682480D6D3 (not 0x150159c72f0f9ef9000bf95e242de6682480d6d3). Please rename it. You may need to rename to a temp name first, then to the checksum format, because lowercase-uppercase-only renames are often ignored by the Git client or the filesystem.

**Comment by MOTHBODY-MOTH** [comment]
@Cryptocool1  ok i have just renamed it and updated it accordingly

**Comment by MOTHBODY-MOTH** [comment]
@Cryptocool1 ok sorry i think we are finally good to go

**Pull request merged**
