### PR TITLE
Add Gear logo and info

### PR DESCRIPTION
**Pull request by metagearnft**

### CODE REVIEW

**Comment by Cryptocool1** [comment]
• What is the purpose of this token? How will it benefit Trust Wallet users?
 • How is the token being distributed? Are you conducting an airdrop?
 • Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?
 • Is the token listed on a centralized/decentralized exchange?
 • Is a Smart Contract audit completed? Where can we find this information?

**Comment by cryptomanz** [comment]
As per our policy, brand new tokens are not included, there is a minimum requirement of 10,000 holder addresses and 20,000 transactions, in order to filter out scam tokens.
See the criteria at : https://developer.trustwallet.com/assets/requirements .

**Comment by metagearnft** [comment]
> • What is the purpose of this token? How will it benefit Trust Wallet users? • How is the token being distributed? Are you conducting an airdrop? • Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale? • Is the token listed on a centralized/decentralized exchange? • Is a Smart Contract audit completed? Where can we find this information?

Hello @Cryptocool1 
- Gear Token can be used to trade NFT on the marketplace, staking & farming, as well as a condition to be allowed to take part in some special events. Of course Trust Wallet users are equal to others in term of GEAR ultility
- We’ve distributed token to users via airdrop and IDO
- Yes, we’ve done our IDO on 4 launchpads: Bullperks, Poolz, Krystal GO, Starpunk (Starpad)
- No, we’re planning to list our token on some tier 1 CEX: KuCoin, Gate.io
- Yes, we’ve done the audit on Verichain: https://audit.verichains.io/certifications.html?search=MetaGear

**Comment by cryptomanz** [comment]
we are accept only Certik, TechRate, Dessert Finance, Hacken audits.

**Comment by Cryptocool1** [comment]
Please come back to us when all criteria are met. When creating new PR, make sure to mention this one, so the fee can be reused

**Pull request closed without merging**
