### PR TITLE
Add logo

### PR DESCRIPTION
**Pull request by bricsmine**
This invoice has already been paid: #27561 

Holders reached the desired number

### CODE REVIEW

**Comment by cryptomanz1** [comment]
• What is the purpose of this token? How will it benefit Trust Wallet users?
 • How is the token being distributed? Are you conducting an airdrop?
 • Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?
 • Is the token listed on a centralized/decentralized exchange?
 • Is a Smart Contract audit completed? Where can we find this information?

**Comment by bricsmine** [comment]
I have gone through these steps in the previous one

**Comment by bricsmine** [comment]
Holders requirement is still pending

Holders reached the desired number

Originally posted by @Cryptocool1 in https://github.com/trustwallet/assets/pull/27950#issuecomment-2094894234

**Comment by bricsmine** [comment]
@cryptomanz1

Holders requirement is still pending

Holders reached the desired number

Originally posted by @Cryptocool1 in #27950 (comment)

**Pull request merged**
