### PR TITLE
add The Abyss token

### PR DESCRIPTION
**Pull request by TheAbyss-dev**

### CODE REVIEW

**Comment by TheAbyss-dev** [comment]
hi all, when can we expect the merge to be completed?

**Comment by catenocrypt** [comment]
@TheAbyss-dev , is this a token or a new blockchain+coin?  The PR structure indicated new blockchain; however a new blockchain is not easily supported.

**Comment by zachzwei** [comment]
Merging to assets. This will not appear yet as supported blockchain.

**Comment by TheAbyss-dev** [comment]
this is a token 
is there a different procedure for it?

**Pull request merged**
