### PR TITLE
ADD Nise Chain (STO) token logo Trust wallet

### PR DESCRIPTION
**Pull request by nisechain**
ADD Nise Chain (STO) token logo Trust wallet

Token Name: Nise Chain
Token Symbol: STO
Token Decimals: 18
Token Initial Supply: 9,680,000,000 STO
Token Contract: 0x72a8e0b56ae249537a2636c5ecac0f03b60d7dc5

0x72a8e0b56ae249537a2636c5ecac0f03b60d7dc5

### CODE REVIEW

**Comment by nisechain** [comment]
payment is done 
https://explorer.binance.org/tx/BE2B3A4DFE5F41ED7531C1C191A8D614690412D1909503A27348AE994D237D37

Yes, send 1 BNB . Hash : BE2B3A4DFE5F41ED7531C1C191A8D614690412D1909503A27348AE994D237D37

**Comment by nisechain** [comment]
ADD Nise Chain (STO) token logo Trust wallet

Token Name: Nise Chain
Token Symbol: STO
Token Decimals: 18
Token Initial Supply: 9,680,000,000 STO
Token Contract: 0x72a8e0b56ae249537a2636c5ecac0f03b60d7dc5

0x72a8e0b56ae249537a2636c5ecac0f03b60d7dc5

**Comment by nisechain** [comment]
Hii any solution

**Comment by kolya182** [comment]
> Hii any solution

What do you really ask ?

**Pull request merged**
