### PR TITLE
Add Kishu Inu (KISHU) (ERC20)  

### PR DESCRIPTION
**Pull request by Goronyudo**
Adding info for ERC20 token 'Kishu Inu (KISHU)'.

PR created by <a href="https://assets.trustwallet.com">TW Assets Management</a>

### CODE REVIEW

**Comment by Goronyudo** [comment]
Specifically logo added to uniswap

**Comment by Goronyudo** [comment]
> Token check: Errors found!
> 
> Found 1 added/changed token(s) among the PR files (ERC20: 0xA2b4C0Af19cC16a6CfAcCe81F192B024d625817D )
> 
> Error while performing token check, Error: Request failed with status code 400

???

**Review by Kishu-Inu — CHANGES_REQUESTED** [review]
Explorer: correct etherscan URL is https://etherscan.io/address/0xa2b4c0af19cc16a6cfacce81f192b024d625817d
Website: correct website is https://kishu.finance/

**Review by openb0x — COMMENTED** [review]
In the token ID line, the address must be in checksum format

**Review by openb0x — COMMENTED** [review]
Also in the line "explorer" there is an error, instead of a link to the token, you specified the address of the contract

**Pull request merged**
