### PR TITLE
Add Vulkania (BEP20)

### PR DESCRIPTION
**Pull request by vulkaniadev**
Adding info for BEP20 token 'Vulkania'.

PR created by <a href="https://assets.trustwallet.com">TW Assets Management</a>

### CODE REVIEW

**Comment by vulkaniadev** [comment]
Before going any further, I would like to point out that Vulkania has just been migrated to a new contract, the old one was already listed on TrustWallet for 1 year.

Here is the migration announcement: https://vulkania.io/blog/vulkania-token-migration-when-why-what-you-need-to-do/

Our platform is legitimate and used by thousands of users, we had 400k+ hits in April.

Our new contract was developed by Brewlabs and certified by Solidity Finance: https://solidity.finance/audits/Vulkania/

We know we don't have the minimum holders requirements but we are definitely legit and in this space since more than a year.

Translated with www.DeepL.com/Translator (free version)

**Comment by vulkaniadev** [comment]
Before going any further, I would like to point out that Vulkania has just been migrated to a new contract, the old one was already listed on TrustWallet for 1 year.

Here is the migration announcement: https://vulkania.io/blog/vulkania-token-migration-when-why-what-you-need-to-do/

Our platform is legitimate and used by thousands of users, we had 400k+ hits in April.

Our new contract was developed by Brewlabs and certified by Solidity Finance: https://solidity.finance/audits/Vulkania/

We know we don't have the minimum holders requirements but we are definitely legit and in this space since more than a year.

**Comment by Cryptocool1** [comment]
As per our policy, brand new tokens are not included, there is a minimum requirement of 10,000 holder addresses and 15,000 transactions, in order to filter out scam tokens.
See the criteria at : https://developer.trustwallet.com/assets/requirements .

**Comment by cryptomanz** [comment]
As per our policy, there is a minimum requirement of 10,000 holder addresses and 15,000 transactions, in order to filter out scam tokens.
See the criteria at : https://developer.trustwallet.com/assets/requirements .

**Comment by vulkaniadev** [comment]
@cryptomanz can you please consider merging our PR considering this is a contract migration and not a creation? You closed and reopened our PR, that might be for a reason.

**Comment by Cryptocool1** [comment]
Hello, sure. What is you old contract?

**Comment by vulkaniadev** [comment]
Hello, here is our old contract:

http://bscscan.com/token/0x0921d788e7f7498f80adb0a0a62b8a9476f2db92

As you can see there is a migration announcement on bscscan.

We just did our swap with a ratio 1:1, our migration went fine and we put a lot of efforts into it.

**Comment by cryptomanz** [comment]
#20208

**Comment by vulkaniadev** [comment]
Thank you!

**Pull request merged**
