### PR TITLE
Add Torum (BEP20)

### PR DESCRIPTION
**Pull request by Jayson9711**
Adding info for BEP20 token 'Torum'.

PR created by <a href="https://assets.trustwallet.com">TW Assets Management</a>

### CODE REVIEW

**Comment by cryptomanz** [comment]
• What is the purpose of this token? How will it benefit Trust Wallet users?
 • How is the token being distributed? Are you conducting an airdrop?
 • Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?
 • Is the token listed on a centralized/decentralized exchange?
 • Is a Smart Contract audit completed? Where can we find this information?

**Comment by Cryptocool1** [comment]
• What is the purpose of this token? How will it benefit Trust Wallet users?
• How is the token being distributed? Are you conducting an airdrop?
• Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?
• Is the token listed on a centralized/decentralized exchange?
• Is a Smart Contract audit completed? Where can we find this information?

**Comment by Jayson9711** [comment]
• What is the purpose of this token? How will it benefit Trust Wallet users?
XTM is a utility token that is used in gifting (tipping), NFT trading, governance (voting) and advertisement services.

We are open to explore integrating Trust Wallet into Torum and bringing onboard TW as our official wallet partner.

• How is the token being distributed? Are you conducting an airdrop?
Here's our token distribution percentage and vesting period: https://drive.google.com/file/d/1FBk-XUlJQLdLAGqOv7K5_jfw6KaYhghL/view?usp=sharing

Nope, we are not doing any airdrop.

• Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?
Yes, we did. 14.67% of the total token supply is issued with 5 rounds (seed, private, presale, ISNO and IDO) 

• Is the token listed on a centralized/decentralized exchange?
Yes. For CEX, we are listed on KuCoin, Huobi, MDEX, MEXC, BKEX and Hotbit. For DEX, we are listed on Uniswap and Pancakeswap.

• Is a Smart Contract audit completed? Where can we find this information?
Yes, you can find it from below:
https://www.fairyproof.com/doc/TorumToken-Audit-Report-V101-093021.pdf
https://www.fairyproof.com/doc/TorumTokenHeco-Audit-Report-120821. pdf

**Comment by Jayson9711** [comment]
Sorry, a newbie question here: does this mean that XTM, our token will be integrated and whitelisted into Trust Wallet?

Thank you :)

**Pull request merged**
