### PR TITLE
add magicbox.game token

### PR DESCRIPTION
**Pull request by MagicBox-Lab**

### CODE REVIEW

**Comment by cryptomanz** [comment]
• What is the purpose of this token? How will it benefit Trust Wallet users?
 • How is the token being distributed? Are you conducting an airdrop?
 • Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?
 • Is the token listed on a centralized/decentralized exchange?
 • Is a Smart Contract audit completed? Where can we find this information?

**Comment by MagicBox-Lab** [comment]
> • What is the purpose of this token? How will it benefit Trust Wallet users? • How is the token being distributed? Are you conducting an airdrop? • Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale? • Is the token listed on a centralized/decentralized exchange? • Is a Smart Contract audit completed? Where can we find this information?

Many of our users want to show it in your wallet. 
We have no airdrops, we are all valid users
We are already list on pancakeswap
presale in https://www.pinksale.finance/#/launchpad/0x59e7d120aa4cd76729F63985Da867167DF1B411F?chain=BSC
You can find our information here https://magicbox.game

**Comment by ramsty** [comment]
Is a Smart Contract audit completed? Where can we find this information?

**Comment by MagicBox-Lab** [comment]
> Is a Smart Contract audit completed? Where can we find this information?

The audit has not been completed yet, the results will come out soon

**Comment by ramsty** [comment]
Awaiting for smart contract audit. On hold for now.

**Comment by Cryptocool1** [comment]
Feel free to open new PR when smart contract audit will be ready
When creating a new PR make sure to mention this PR, so that we can see that fee has been paid already here.

**Pull request closed without merging**
