### PR TITLE
Add Agatech (BEP20)

### PR DESCRIPTION
**Pull request by TheNotoriousMonsi**
Adding info for BEP20 token 'Agatech'.

PR created by <a href="https://assets.trustwallet.com">TW Assets Management</a>

### CODE REVIEW

**Comment by Cryptocool1** [comment]
• What is the purpose of this token? How will it benefit Trust Wallet users?
 • How is the token being distributed? Are you conducting an airdrop?
 • Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?
 • Is the token listed on a centralized/decentralized exchange?
 • Is a Smart Contract audit completed? Where can we find this information?

**Comment by TheNotoriousMonsi** [comment]
Purpose of the Token:
Agatech (AGATA) is a multi-functional utility token designed to serve various purposes within a broader ecosystem. It offers decentralized finance (DeFi) functionalities, community engagement incentives, and broader ecosystem applications. Specifically, AGATA aims to enhance DeFi experiences by providing Trust Wallet users with a secure and versatile token that can be used for transactions, staking, and other financial services within a decentralized environment.

Distribution of the Token and Airdrop Plans:
Agatech is primarily distributed through decentralized exchanges (DEX), with initial liquidity provided by the development team and the community through a presale event. There are no current plans to conduct airdrops, as the token's distribution strategy focuses on organic growth and fostering a stable, engaged community. This approach ensures the token's longevity and stability.

Initial Coin Offering or Token Presale:
Agatech did not conduct an Initial Coin Offering (ICO). Instead, the project completed a presale where 100% of the collected funds (57.516 BNB) were placed into a locked Liquidity Pool (LP) on PancakeSwap. This ensures a robust liquidity foundation and emphasizes the project's commitment to security and stability. The LP will remain locked, ensuring long-term support for the community. 
Link to the Presale information: https://app.uncx.network/amm/pancake-v2/ilo/0xe13Ef7CEA72D0C89f5889A5E715892b3eE6b7D1a

Token Listing on Centralized/Decentralized Exchanges:
Agatech is currently listed on multiple decentralized exchanges, including PancakeSwap, SushiSwap, and Flooz. Additional listings on KuskuSwap and Agaswap (Agatech's own DEX) are expected in the coming weeks. The team plans to apply for centralized exchange listings on platforms like Coinstore and OKX. With 10% of the token supply providing liquidity in the locked LP and additional liquidity from the development team, AGATA maintains a stable trading environment.

Smart Contract Audit Information:
Agatech has undergone extensive smart contract audits by reputable firms, including Checkdot and Cyberscope, with no significant issues found. This indicates a high level of security and reliability. Additionally, the team has completed a full KYC (Know Your Customer) process with Cyberscope, demonstrating transparency and accountability.

Here are the links to the audits and other relevant information:
- Checkdot audit: https://audits.checkdot.io/Agata-Audit-CheckDot.pdf
- Cyberscope audit: https://github.com/cyberscope-io/audits/blob/main/agata/audit.pdf
- Cyberscope KYC verification: https://github.com/cyberscope-io/kyc/blob/main/agata/kyc.png
- Cyberscope scan: https://www.cyberscope.io/cyberscan?address=0xb427e47e8fdd678278d2a91eeac014ffcddaf029

The GoPlusLabs scan shows no warnings or attention items, indicating a well-distributed token structure. Agatech has also achieved a 100/100 score on TokenSniffer, signifying high quality and reliability.

Here are additional links for reference:
- GoPlusLabs scan with 0 warnings and 0 attention items: https://www.gopluslabs.io
- BubbleMaps: https://app.bubblemaps.io/bsc/token/0xb427e47e8fDD678278d2A91EEaC014ffcDDaF029
- TokenSniffer with 100/100 score: https://tokensniffer.com/token/bsc/0xb427e47e8fdd678278d2a91eeac014ffcddaf029

For trading information, refer to these links:
- PancakeSwap: https://pancakeswap.finance/info/tokens/0xb427e47e8fdd678278d2a91eeac014ffcddaf029?chain=bsc
- Flooz: https://flooz.xyz/trade/0xb427e47e8fdd678278d2a91eeac014ffcddaf029?network=bsc
- Flooz post about Agatech: https://x.com/flooz_xyz/status/1779832864181248087?s=46

**Comment by TheNotoriousMonsi** [comment]
Hi, we had to migrate the AgaTech (AGATA) token to a new contract address. All other aspects and information about the project stay the same, we just have a new CA for the token, can we have that updated?
Old token contract address: 0xb427e47e8fDD678278d2A91EEaC014ffcDDaF029
New token contract address: 0x18c4AF61DbE6fD55d6470943b4ab8530777d009C

**Comment by hoangbut01** [comment]
Ok , Tôi đang khá là đau đầu đây hmmm

**Comment by Paukageo10** [comment]
> Hi, we had to migrate the AgaTech (AGATA) token to a new contract address. All other aspects and information about the project stay the same, we just have a new CA for the token, can we have that updated? Old token contract address: 0xb427e47e8fDD678278d2A91EEaC014ffcDDaF029 New token contract address: 0x18c4AF61DbE6fD55d6470943b4ab8530777d009C

Akoje

**Comment by magneticmeganlovesjhonny** [comment]
Migrate

**Comment by krud491** [comment]
Next

**Comment by krud491** [comment]
0x18c4AF61DbE6fD55d6470943b4ab8530777d009C

**Comment by krud491** [comment]
[1_4925083227896415358.csv](https://github.com/user-attachments/files/18452968/1_4925083227896415358.csv)

**Pull request merged**
