### PR TITLE
Add DAM to BSC

### PR DESCRIPTION
**Pull request by skatoken**
DAM is a token used to compensate Alaskainu community. Users can obtain DAM airdrop by holding LAS and LASM tokens.The emergence of DAM will lead the Alaska Army to victory again.

### CODE REVIEW

**Comment by cryptomanz** [comment]
Hello,
- Can't find contract on your website.

**Comment by Alaskatoken** [comment]
We are updating the website UI. Alaska has three kinds of Tokens: LAS, LASM and DAM.
You can see our information here : https://docs.alaskatoken.io/token/dam

**Comment by cryptomanz** [comment]
Hello,
Can your answer some questions?
- • What is the purpose of this token? How will it benefit Trust Wallet users?
 • How is the token being distributed? Are you conducting an airdrop?
 • Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?
 • Is the token listed on a centralized/decentralized exchange?
 • Is a Smart Contract audit completed? Where can we find this information?

**Comment by Alaskatoken** [comment]
• What is the purpose of this token? How will it benefit Trust Wallet users?
- DAM is a token used to compensate Alaskainu community. Users can obtain DAM airdrop by holding LAS and LASM tokens.

• How is the token being distributed? Are you conducting an airdrop?
- After the attack on our farm, the LAS and LASM holders were acquired by airdrop, and the airdrop has been completed

• Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?
- No,only airdrop

• Is the token listed on a centralized/decentralized exchange?
- pancakeswap

• Is a Smart Contract audit completed? Where can we find this information?
- We are in contact with the audit agency, and the audit report will be listed on the website soon

**Comment by Alaskatoken** [comment]
We have updated the website, you can see our contract address in the website

**Comment by Cryptocool1** [comment]
Minimum 5,000 token holders and 10,000 transactions (Airdrop tokens excluded**).

**Comment by Cryptocool1** [comment]
awaiting for cmc listing

**Comment by Cryptocool1** [comment]
please create new PR when CMC listing will be ready.
make sure to mention this PR, so that we can see that fee has been paid already here.

**Comment by Alaskatoken** [comment]
Good day.
DAM is listed on CMC.

Check up:
https://coinmarketcap.com/currencies/diamonds-alaska-malamuted/

**Pull request closed without merging**
