### PR TITLE
Add logo to EthereumPay

### PR DESCRIPTION
**Pull request by jennanatalie5**
Add logo to EthereumPay (logo.png)

### CODE REVIEW

**Comment by jennanatalie5** [comment]
Hello, it says that im supposed to put it in checksum format but i think it already is

**Comment by jennanatalie5** [comment]
Just submitted the payment. Just hit 2500 holders

**Comment by jennanatalie5** [comment]
Hello

**Comment by Cryptocool1** [comment]
> Hello

hello,
correction needed:
Contract is not in checksum format, should be 0x2b5cA2F9510cf1e3595Ff219f24D75D4244585EA

**Comment by jennanatalie5** [comment]
ok fixed

**Comment by jennanatalie5** [comment]
Hello. i have corrected everything and still says there are problems

**Comment by Cryptocool1** [comment]
I suggest to create a new PR (and mention this one so that fee does not have to be paid again).
  You may use our Assets app (in beta); close this PR; go to https://assets.trustwallet.com, log on with Github, enter contract ID, logo and some additional info, and it will create a PR for you. See https://community.trustwallet.com/t/how-to-submit-a-token-logo-using-assets-app/82957\

**Pull request closed without merging**
