### PR TITLE
update contract address

### PR DESCRIPTION
**Pull request by eic0**
We migrated our token from 0x579f11c75eb4e47f5290122e87ca411644adcd97 to 0x5E19266e4a17521d65EFF608517fA0c82CA24813
I deleted the old directory & created a new directory with the updated address. 
Also i changed the info.json accordingly, as well as the logo.

### CODE REVIEW

**Comment by eic0** [comment]
Just want to update our token address. We paid before already.

**Comment by cryptomanz** [comment]
Hello,
Do you have official information about migration your token?

**Comment by eic0** [comment]
Hello,
Yes i'll give you a list of links here:

- Official Instagram announcement:
https://www.instagram.com/p/CW0TUJvsM8-/?utm_medium=copy_link
- Yahoo Finance article about our migration:
https://finance.yahoo.com/news/cleanocean-successfully-migrating-clean-v2-140000322.html?guccounter=1

- Our Website has a link to our migration: https://cleanocean.io/
      -> Our (now already expired) migration web interface:
https://migration.cleanocean.io
- Announcement of the Migration on Twitter:
https://twitter.com/cleanoceantoken/status/1468245986002841603

If you need anything else, please let me know.
Greetings,
Daniel - Team CleanOcean

Am So., 12. Dez. 2021 um 19:58 Uhr schrieb Nazar ***@***.***>:

**Comment by cryptomanz** [comment]
Please create new PR, with new contract and i will put status abandoned in your old contract. Make sure to mention this PR, so that we can see that fee has been paid already here.

**Pull request closed without merging**
