### PR TITLE
Add logo files via upload

### PR DESCRIPTION
**Pull request by RAMPDEFITEAM**
RAMP DEFI ERC20 TOKEN LOGO
0x33D0568941C0C64ff7e0FB4fbA0B11BD37deEd9f

### CODE REVIEW

**Comment by catenocrypt** [comment]
As per our policy, brand new tokens are not included, there is a minimum requirement of 100 holder addresses and 500 transactions, in order to filter out scam tokens.
See the criteria at (mentioned in the first message by the bot): https://community.trustwallet.com/t/how-to-submit-a-token-logo/3863#how-to-get-approved 
This token has minimal usage (5/7).  Putting on hold for now, please return when all criteria are met.

https://etherscan.io/token/0x33D0568941C0C64ff7e0FB4fbA0B11BD37deEd9f

**Comment by RAMPDEFITEAM** [comment]
Hi Adam,

Understood, would revisit after hitting the requirement.

Thank you so much!
RAMP DEFI Team

**Comment by catenocrypt** [comment]
Please add an `info.json` file next to the `logo.png`, with info about the project, of the form:

```json
{
    "name": "Trust Wallet Token",
    "website": "https://trustwallet.com",
    "short_description": "Utility token to increase adoption of cryptocurrency.",
    "explorer": "https://etherscan.io/token/0xA866F0198208Eb07c83081d5136BE7f775c2399e",
    "socials": [
        {
            "name": "Twitter",
            "url": "https://twitter.com/trustwalletapp",
            "handle": "TrustWalletApp"
        },
        {
            "name": "Reddit",
            "url": "https://reddit.com/r/trustapp",
            "handle": "TrustApp"
        }
    ]
}
```

**Comment by RAMPDEFITEAM** [comment]
Hi Adam,

Added the Json file.

Thanks!
RAMP DEFI TEAM

**Comment by RAMPDEFITEAM** [comment]
Thanks guys!

Cheers :)
RAMP DEFI TEAM

**Pull request merged**
