### PR TITLE
Add Vita Inu (BEP20)

### PR DESCRIPTION
**Pull request by ElemontCapital**
Already paid - refer to Pull #20103 

Audit Completed: https://www.certik.com/projects/vita-inu#audit

We are an established (multichain) project with over 20,000 holders. You can verify via the following explorers:
- VITE: https://vitescan.io/token/tti_541b25bd5e5db35166864096
- BSC: https://bscscan.com/token/0xfebe8c1ed424dbf688551d4e2267e7a53698f0aa

@Cryptocool1 said for us to submit a new PR once audit was complete, and to reference the previous PR #20103 to re-use the fee.

Please let me know should you require any further information

### CODE REVIEW

**Comment by ElemontCapital** [comment]
> Hi! In order to compensate for the efforts of processing PRs, we kindly ask for a contribution. 💀 As **there is no refund**, before **paying the fee**, make sure **new tokens fulfill the minimum circulation and other [acceptance criteria](https://developer.trustwallet.com/assets/new-asset)**. See also the [PR Fee FAQ](https://developer.trustwallet.com/assets/faq).
> 
> Please pay **700 TWT** with the memo **20374** to the address `bnb1tqq9llyr3dyjd559dha6z5r5etk3qfwk07m098`. Alternatively, 5 BNB is also accepted (same memo & address).
> 
> **QR** code: [Trust](https://api.qrserver.com/v1/create-qr-code/?size=200x200&data=https%3A%2F%2Flink.trustwallet.com%2Fsend%3Fcoin%3D714%26address%3Dbnb1tqq9llyr3dyjd559dha6z5r5etk3qfwk07m098%26amount%3D700%26memo%3D20374) | [other wallet](https://api.qrserver.com/v1/create-qr-code/?size=200x200&data=bnb1tqq9llyr3dyjd559dha6z5r5etk3qfwk07m098%3Famount%3D700%26memo%3D20374)
> 
> _Notes_:
> 
> * [Trust Wallet Tokens (TWT)](https://community.trustwallet.com/t/trust-wallet-token-twt/4187) can be obtained through our [Referral Program](https://community.trustwallet.com/t/invite-a-friend-earn-trust-wallet-token-twt/4125) or [from DEXs/exchanges](https://community.trustwallet.com/t/where-to-get-trust-wallet-tokens/76641).
> * New tokens without significant usage are rejected, see criteria mentioned above.
> * One PR should be for a single project; PR's with more than 10 logos will be rejected.
> * Payment evaluation happens automatically, but with a few minutes delay.  When payment is detected, an Accept Review is automatically placed on the PR, which is a condition for merge.
> * Evaluating the PR is done manually, and it is merged only if all conditions are satisfied.
> * TWT-BEP2 is supported (Binance Chain), TWT-BEP20 version on Smart Chain is not.
> 
> There will be a fee to process this request. None of it goes to the developers. Before paying the fee, make sure new tokens fulfill the minimum circulation and other acceptance criteria. If you are paying TWT for the submission, this will be burned automatically. There will be no refunds.

Already paid - refer to Pull https://github.com/trustwallet/assets/pull/20103

**Comment by Cryptocool1** [comment]
you have some major findings in your Audit.

As per our policy, brand new tokens are not included, there is a minimum requirement of 10,000 holder addresses and 15,000 transactions, in order to filter out scam tokens.
See the criteria at : https://developer.trustwallet.com/assets/requirements .

**Comment by Cryptocool1** [comment]
you have some major findings in your Audit.

As per our policy, brand new tokens are not included, there is a minimum requirement of 10,000 holder addresses and 15,000 transactions, in order to filter out scam tokens.
See the criteria at : https://developer.trustwallet.com/assets/requirements .

**Comment by cryptomanz** [comment]
0

**Comment by ElemontCapital** [comment]
> you have some major findings in your Audit.
> 
> As per our policy, brand new tokens are not included, there is a minimum requirement of 10,000 holder addresses and 15,000 transactions, in order to filter out scam tokens. See the criteria at : https://developer.trustwallet.com/assets/requirements .

Hi @Cryptocool1  

1) The major findings of the Audit were **addressed** (and almost all BSC tokens have major findings which are then addressed). See picture below from Certik themselves:
image

2) We have 100,000 transactions on BSC alone (and another 100k+ on Vite). We are not a brand new token. **Our holders are split across different chains because we are multichain.**

You can verify our holder numbers via the following explorers:
VITE: https://vitescan.io/token/tti_541b25bd5e5db35166864096
BSC: https://bscscan.com/token/0xfebe8c1ed424dbf688551d4e2267e7a53698f0aa
image

3) We provide regular updates on our project, see here for our 1Q22 update:
https://medium.com/@VitaInu/1q22-update-vita-inu-vinu-aecd58214c3b

Do these all not suffice?

**Pull request closed without merging**
