### PR TITLE
Added XLD logo and info

### PR DESCRIPTION
**Pull request by xceltripofficial**
reappliing and PR being closed.

### CODE REVIEW

**Comment by xceltripofficial** [comment]
#13915
reapplied from #13915 pr

**Comment by cryptomanz** [comment]
Hello,
• What is the purpose of this token? How will it benefit Trust Wallet users?
 • How is the token being distributed? Are you conducting an airdrop?
 • Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?
 • Is the token listed on a centralized/decentralized exchange?
 • Is a Smart Contract audit completed? Where can we find this information?

**Comment by xceltripofficial** [comment]
• What is the purpose of this token? How will it benefit Trust Wallet users?
XcelDefi is a native token of the XcelLab ecosystem and the governance token for XcelSwap, a decentralized exchange built by the XcelLab ecosystem to power the finance of the future. Users can vote by holding and staking XcelDefi and proposing changes to the XcelSwap mechanics. XcelDefi assists in the generation of passive income through a variety of methods on Xcelswap. Users can earn XcelDefi by mining liquidity and staking on pools.
Trust Wallet users will be able to check the number of XcelDefi tokens they hold while checking the price action in their native currency for example dollars, pounds, etc.

• How is the token being distributed? Are you conducting an airdrop?
The total supply is 111million. You can see the token distribution details on: www.xceldefi.com
We have conducted the airdrop too. Here are the details: https://medium.com/xcellab-magazine/check-out-this-exclusive-5million-xceldefi-xld-airdrop-fdec2fd18195

• Did you sell the tokens at an Initial Coin Offering (ICO) or a token presale?
There were no ICOs or a token presale.

• Is the token listed on a centralized/decentralized exchange?
Yes, the token is listed on Pancakeswap and our own DeX XcelSwap.

• Is a Smart Contract audit completed? Where can we find this information?
Yes, the smart contract is audited. You can find the information at https://xceldefi.com/audit

**Comment by Cryptocool1** [comment]
could you add the links to your PR?

**Pull request merged**
