### PR TITLE
Add a new PXP token logo

### PR DESCRIPTION
**Pull request by YevheniiaShmelkova**
Please, add a new PXP token logo.

### CODE REVIEW

**Comment by Cryptocool1** [comment]
Please create new PR, follow doc https://developer.trustwallet.com/assets/requirements
You may want to try our Assets app in beta; go to https://assets.trustwallet.com, log on with Github, enter contract ID, logo and some additional info, and it will create a PR for you.
See https://developer.trustwallet.com/assets/repository_details

**Comment by Cryptocool1** [comment]
did you use this link https://developer.trustwallet.com/assets/repository_details ?

**Comment by Cryptocool1** [comment]
here is the sample info.json
{
    "name": "Trust Wallet Token",
    "website": "https://trustwallet.com",
    "description": "Utility token to increase adoption of cryptocurrency.",
    "explorer": "https://explorer.binance.org/asset/TWT-8C2",
    "type": "BEP2",
    "symbol": "TWT",
    "decimals": 8,
    "status": "active",
    "id": "TWT-8C2",
    "links": [
        {
            "name": "github",
            "url": "https://github.com/trustwallet/"
        },
        {
            "name": "twitter",
            "url": "https://twitter.com/TrustWalletApp"
        },
        {
            "name": "reddit",
            "url": "https://reddit.com/r/trustapp"
        }
    ]
 "tags": [
         "governance"
     ]
}

**Comment by Cryptocool1** [comment]
Снимок экрана 2022-08-31 в 18 59 37
this way is also incorrect, both for info.json and logo png files

**Comment by Cryptocool1** [comment]
try our Assets app in beta; go to https://assets.trustwallet.com, log on with Github, enter contract ID, logo and some additional info, and it will create a PR for you.

**Comment by YevheniiaShmelkova** [comment]
Thanks, let me try.

I have used this link:
https://community.trustwallet.com/t/how-to-submit-a-token-logo/3863

Best regards

*Yevheniia Shmelkova*

Content Writer at PointPay

https://pointpay.io

**Comment by Cryptocool1** [comment]
> Thanks, let me try. I have used this link: https://community.trustwallet.com/t/how-to-submit-a-token-logo/3863 Best regards *Yevheniia Shmelkova* Content Writer at PointPay https://pointpay.io
> […](#)

https://community.trustwallet.com/t/how-to-submit-a-token-logo/3863 this link is old one. I've sent you correct links to the requirements and repository details pages

**Comment by YevheniiaShmelkova** [comment]
Hi! I have used the app that you provided. I have created a new pull
request (PR #22233), but I have received in the email that there are issues
with my files again. Can you please check if everything is ok?

[image: image.png]





Best regards

*Yevheniia Shmelkova*

Content Writer at PointPay

https://pointpay.io

**Pull request closed without merging**
