### PR TITLE
0xCharts Token Logo and info

### PR DESCRIPTION
**Pull request by jamel-86**
Please help us to add the logo as soon you can :)

### CODE REVIEW

**Comment by chukanovdk** [comment]
This project is scammers.
They have already deceived a lot of people with their other projects.
a copy of MVEDA token on BSC, do not invest your money, lose

**Comment by Cryptocool1** [comment]
As per our policy, brand new tokens are not included, there is a minimum requirement of 2500 holder addresses and 5000 transactions, in order to filter out scam tokens.
See the criteria at (mentioned in the first message by the bot): https://community.trustwallet.com/t/how-to-submit-a-token-logo/3863).

**Comment by jamel-86** [comment]
So this means it will be on hold until we reach 2500 holders right? Or do I have to pull and pay again when we have reached 2500 holders?

Thanks!

**Comment by Chibi-Inu** [comment]
> As per our policy, brand new tokens are not included, there is a minimum requirement of 2500 holder addresses and 5000 transactions, in order to filter out scam tokens.
> See the criteria at (mentioned in the first message by the bot): https://community.trustwallet.com/t/how-to-submit-a-token-logo/3863).

Check our new pull request 9113. Fees already paid in PR 8811. You said to create new PR for that checksum address issue.

**Comment by Cryptocool1** [comment]
> So this means it will be on hold until we reach 2500 holders right? Or do I have to pull and pay again when we have reached 2500 holders?
> 
> Thanks!

yes, it will be on hold until you reach 2500 holders and 5000 transactions. you don't need to pay one more time.

**Comment by Cryptocool1** [comment]
Please come back to us when all criteria are met.
When creating a new PR make sure to mention this PR, so that we can see that fee has been paid already here.

**Pull request closed without merging**
