### PR TITLE
 Add MGP (BEP20)

### PR DESCRIPTION
**Pull request by MagicCubeFinance**

### CODE REVIEW

**Comment by Cryptocool1** [comment]
Hello!
Can you answer some questions?
• What is the purpose of this token? How will it benefit Trust Wallet users?
 • How is the token being distributed? Are you conducting an airdrop?
 • Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?
 • Is the token listed on a centralized/decentralized exchange?
 • Is a Smart Contract audit completed? Where can we find this information?

**Comment by MagicCubeFinance** [comment]
Hello!
Can you answer some questions?
Yes 

What is the purpose of this token? How will it benefit Trust Wallet users?
1. The token MGP is a meme token to drive and empower the Magic Cube ecosystem. 
2. We have a very worldwide range of user base, and we’ll help Trust to gain more users. 

How is the token being distributed? Are you conducting an airdrop?
1. MGP token is distributed as: 1) Mining pool mining output: 45trillion. 2) Liquidity pool: 20trillion.   3) Project O&M & Marketing: 9trillion.  4)   Technology upgrade: 7trillion.   5) Security fund: 7trillion. 6) USDM Liquidity Incentive: 5trillion. 7)  Developer Incentives: 3trillion.   8) Community Airdrop: 2 trillion. 9) Other: 2 trillion  
2. We are planning to conduct the airdrop. 

Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?
No any ICO or presale. 

Is the token listed on a centralized/decentralized exchange?
It’s listed on PancakeSwap 

Is a Smart Contract audit completed? Where can we find this information?
1. In the auditing process now. 
 2. You can find it on the website and Github when it’s done.

**Comment by cryptomanz** [comment]
Awaiting for smart contract audit, on hold for now.

**Comment by Cryptocool1** [comment]
still no answer.
please create new PR when answers will be ready. make sure to mention this PR so the fee can be reused

**Comment by MagicCubeFinance** [comment]
@Cryptocool1 @cryptomanz

**Comment by MagicCubeFinance** [comment]
[https://github.com/Magic-Cube-Finance/Audit/blob/main/MGPToken%20Smart%20Contract%20Audit%20Report%20-%20QuillAudits.pdf](audit)

**Pull request closed without merging**
