### PR TITLE
Add assets for wanakafarm token

### PR DESCRIPTION
**Pull request by marknguyen85**

### CODE REVIEW

**Comment by cryptomanz** [comment]
hello,
can you answer some questions?
• What is the purpose of this token? How will it benefit Trust Wallet users?
• How is the token being distributed? Are you conducting an airdrop?
• Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?
• Is the token listed on a centralized/decentralized exchange?
• Is a Smart Contract audit completed? Where can we find this information?

**Comment by marknguyen85** [comment]
• What is the purpose of this token? How will it benefit Trust Wallet users?
=> It is governance token of Wanaka Farm project, No
• How is the token being distributed? Are you conducting an airdrop?
=> through seed/private and ido launchpads sale and some community events, no airdrop.
• Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?
=> yes, ido launchpads
• Is the token listed on a centralized/decentralized exchange?
=> listed on pancakeswap Dex
• Is a Smart Contract audit completed? Where can we find this information?
https://github.com/Wanaka-Inc/audit-report/blob/master/REP-WanakaFarm-2021-08-20.pdf
https://github.com/Wanaka-Inc/audit-report/blob/master/Wanaka%20Security%20Analysis%20-%20Final%20Report.pdf

**Comment by cryptomanz** [comment]
can you please add links to your PR?
example:
{
     "name": "WanakaFarm",
     "type": "BEP20",
     "symbol": "WANA",
     "decimals": 18,
     "website": "https://wanakafarm.com",
     "description": "Wanaka Farm aims to offer anNFT game where people can own their virtual lands, NFT items to plant, grow, harvest to relax and earn their crypto.",
     "explorer": "https://bscscan.com/token/0x339C72829AB7DD45C3C52f965E7ABe358dd8761E",
     "status": "active",
     "id": "0x339C72829AB7DD45C3C52f965E7ABe358dd8761E",
     "links": [
         {
             "name": "whitepaper",
             "url": ""
         },
         {
             "name": "telegram",
             "url": ""
         },
         {
             "name": "facebook",
             "url": ""
         }
     ]
 }

**Comment by marknguyen85** [comment]
> can you please add links to your PR?
> example:
> {
> "name": "WanakaFarm",
> "type": "BEP20",
> "symbol": "WANA",
> "decimals": 18,
> "website": "https://wanakafarm.com",
> "description": "Wanaka Farm aims to offer anNFT game where people can own their virtual lands, NFT items to plant, grow, harvest to relax and earn their crypto.",
> "explorer": "https://bscscan.com/token/0x339C72829AB7DD45C3C52f965E7ABe358dd8761E",
> "status": "active",
> "id": "0x339C72829AB7DD45C3C52f965E7ABe358dd8761E",
> "links": [
> {
> "name": "whitepaper",
> "url": ""
> },
> {
> "name": "telegram",
> "url": ""
> },
> {
> "name": "facebook",
> "url": ""
> }
> ]
> }

Updated as request

**Pull request merged**
