### PR TITLE
Change Contract Address

### PR DESCRIPTION
**Pull request by MONETASGLOBAL**
For Ref PR No #19382

Regarding Contract Address Change

Please Refer Issue No :-#19363 , #19374

Old Contract Address :- 0xE440b9af0AE99174b3FAaB87174E31634D135f6d

New Contract Address :- 0x10adF50e15611d5A4DE3bd21F0DB7f3491A8ae0f

### CODE REVIEW

**Comment by MONETASGLOBAL** [comment]
Fee Already Paid , Its Regarding Contract Address Change

For Ref PR No #19382

 Contract Address Change

Please Refer Issue No #19374

Old Contract Address :- 0xE440b9af0AE99174b3FAaB87174E31634D135f6d

New Contract Address :- 0x10adF50e15611d5A4DE3bd21F0DB7f3491A8ae0f

Please change contract address

**Comment by Cryptocool1** [comment]
can you send the proof of your payment?

**Comment by Cryptocool1** [comment]
can you send the proof of your payment?

**Comment by MONETASGLOBAL** [comment]
ok i will send it payment screen shot

**Comment by MONETASGLOBAL** [comment]
feepaid1
feepaid2

**Comment by MONETASGLOBAL** [comment]
Please Refer PR #10123 For Fee Paid Confirmation

**Comment by MONETASGLOBAL** [comment]
Its Regarding Only Contract Address Change we are already on trust wallet

For Ref PR No #19382

Regarding Contract Address Change

Please Refer Issue No :-#19374

Old Contract Address :- 0xE440b9af0AE99174b3FAaB87174E31634D135f6d

New Contract Address :- 0x10adF50e15611d5A4DE3bd21F0DB7f3491A8ae0f

**Comment by Cryptocool1** [comment]
You need to pay for updating

**Comment by MONETASGLOBAL** [comment]
why

**Comment by MONETASGLOBAL** [comment]
> You need to pay for updating

How Much Pay  and where to pay for updating

**Pull request closed without merging**
