### PR TITLE
Add Football INU (BEP20)

### PR DESCRIPTION
**Pull request by FootballINU**
Adding info for BEP20 token 'Football INU'.

PR created by <a href="https://assets.trustwallet.com">TW Assets Management</a>

### CODE REVIEW

**Comment by FootballINU** [comment]
Hi, Cryptomanz1:

The token provide automatic reflections and we will be rolling out a staking contract very soon. NFTs for token holders are also planned in the future. Broadly speaking, the main purpose of the project is spreading animal adoption awareness and we have plans to coordinate with animal shelters and create NFT collections in collab with them

This token is being bought/sold on PancakeSwap.

We had a presale on [PinkSale]

We are listed only on PancakeSwap currently

We originally had over 1 thousand participants in our presale. With the help of aggressive marketing and being listed on aggregators like Coingecko and Coinmarketcap we managed to get around 3-5k new holders daily. Even, without much marketing this week, we are still getting 3000+ holders daily due to a network effect.

The world cup is approaching and there is great enthusiasm.

All links and details about the project are shared above. Kind regards

**Comment by Cryptocool1** [comment]
• What is the purpose of this token? How will it benefit Trust Wallet users?
 • How is the token being distributed? Are you conducting an airdrop?
 • Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?
 • Is the token listed on a centralized/decentralized exchange?
 • Is a Smart Contract audit completed? Where can we find this information?

**Comment by Cryptocool1** [comment]
you can create new PR once all requirements are met. Make sure to mention this PR so the fee can be reused

**Comment by FootballINU** [comment]
https://github.com/trustwallet/assets/pull/22918

**Pull request closed without merging**
