### PR TITLE
ADD AP LOGO and INFO

### PR DESCRIPTION
**Pull request by connorbrown21**
Add logo for abduction protocol and add info. thanks.

### CODE REVIEW

**Comment by connorbrown21** [comment]
I compressed PNG. Changed website on info.json so it would work, Change File name, and Changed Contract in info.json so it would match file name. I reuploaded.. Not sure if it is in here.

**Comment by connorbrown21** [comment]
Can you please explain what is wrong with my upload? I changed all the info to what you had asked I thought.

**Comment by Cryptocool1** [comment]
hello,
please delete incorrect logo.png and info.json

**Comment by connorbrown21** [comment]
Delete ADD AP LOGO AND INFO

**Comment by connorbrown21** [comment]
> hello,
> please delete incorrect logo.png and info.json

I have no idea what I am doing on here. Is there anyway you can just delete all my files and I can reupload the correct ones? I have spent hours trying to figure this out.

**Comment by connorbrown21** [comment]
What is needed b entire

**Pull request merged**
