### PR TITLE
Add token Arkn

### PR DESCRIPTION
**Pull request by buisang123**
add token arkn

### CODE REVIEW

**Comment by cryptomanz** [comment]
As per our policy, brand new tokens are not included, there is a minimum requirement of 10,000 holder addresses and 15,000 transactions, in order to filter out scam tokens.
See the criteria at : https://developer.trustwallet.com/assets/requirements .

**Comment by cryptomanz** [comment]
Your logo should be full size, without empty space from the side

**Comment by Cryptocool1** [comment]
Please come back to us when all criteria are met

**Comment by Cryptocool1** [comment]
Make sure to mention this PR so the fee can be reused

**Pull request closed without merging**
