### PR TITLE
Add token logo for GNJ "Ganja Token"

### PR DESCRIPTION
**Pull request by ganjadotcom**
GNJ Ganja Token logo

### CODE REVIEW

**Comment by ganjadotcom** [comment]
gnj_48x48
gnj-ganja-token_28x28
GNJ-Ganja-Token-Logo_256x256
GNJ-Ganja-Token-Logo_500x500
GNJ-Ganja-Token-Logo_1000x1000

**Comment by ganjadotcom** [comment]
GNJ contract address 0xed0f59d483977b2bde55fecc81e7534fe7e605e7
Add token logo for GNJ "Ganja Token"

**Comment by kolya182** [comment]
https://github.com/trustwallet/assets/commit/aeefb6ada4ae39deadd94a668df08695b0f5a267

**Comment by ganjadotcom** [comment]
Thank you!

**Pull request closed without merging**
