### PR TITLE
Add Basenji (ERC20)

### PR DESCRIPTION
**Pull request by BasenjiBase**
Adding info for ERC20 token 'Basenji'.

PR created by <a href="https://assets.trustwallet.com">TW Assets Management</a>

### CODE REVIEW

**Comment by BasenjiBase** [comment]
This is the PNG logo i uploaded on trust wallet.

Thanks

**Comment by Jstacy121** [comment]
We havnt get your payment yet you have to hold   
  
  
  
  
  
  
  

  
  
>

**Comment by Jstacy121** [comment]
We havnt get your payment yet you have to hold   
  
  
  
  
  
  
  

  
  
>

**Comment by BasenjiBase** [comment]
When/how will i know if its updated?

Thanks

**Comment by Jstacy121** [comment]
How will let you know once you pay the fee to that bitcoin address

Stacy L Johnson
Sent with Spark

**Comment by cryptomanz1** [comment]
As per our policy, there is a minimum requirement of 10,000 holder addresses and 15,000 transactions.
See the criteria at : https://developer.trustwallet.com/listing-new-assets/requirements .

**Comment by BasenjiBase** [comment]
Hi,

We have 11,500 holders and more than 15k transactions.

Thanks

**Comment by BasenjiBase** [comment]
Hi,

Can we get an ETA on when this will be finished please?

Thanks

**Comment by Cryptocool1** [comment]
> Hi, We have 11,500 holders and more than 15k transactions. Thanks
> […](#)

Please check if you put the correct explorer link

**Comment by BasenjiBase** [comment]
https://basescan.org/token/0xbc45647ea894030a4e9801ec03479739fa2485f0

I attached an image of current holders and total transactions as well.

Thanks

**Comment by BasenjiBase** [comment]
Hello? We would really like this matter to be done. Everything should be in
order and you should have all the information you need. If not, please let
us know ASAP.

Thanks

**Comment by Cryptocool1** [comment]
What is the purpose of this token? How will it benefit Trust Wallet users?
 • How is the token being distributed? Are you conducting an airdrop?
 • Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?
 • Is the token listed on a centralized/decentralized exchange?
 • Is a Smart Contract audit completed? Where can we find this information?

**Comment by BasenjiBase** [comment]
Hey,

$BENJI, Basenji - is a meme token built on Base. The purpose of the token
is to establish ourselves as the biggest dog coin on Base, which we have
successfully achieved. It'll be beneficial for Trust Wallet users for us to
be verified for them to get that extra trust while buying our token, as we
are a legit project. We're verified on Coinbase as well.

The token was launched as a normal stealth launch. No airdrops, no ICO and
no presale.

BENJI is listed on LBank (CEX), Poloniex, (CEX), Uniswap (DEX).

Audit is currently under progress with Certik, the industry leading audit
company and our security score is 84/100. Contract is renounced and
liquidity burnt.

Thanks

**Comment by cryptomanz1** [comment]
Can you send your audit here?

**Comment by BasenjiBase** [comment]
Hi,

The audit is still under process. It should be done this week. However, we
got the security score of the contract as previously mentioned. When we get
the actual certificate i will forward it to you.

Thanks

**Comment by Cryptocool1** [comment]
Feel free to create new PR once audit is done. Make sure to mention this PR so the fee can be reused

**Comment by BasenjiBase** [comment]
Hi,

The audit is now completed. I was told to mention that this is a update with the audit, so the fee can be reused. 
Link to audit:
https://skynet.certik.com/projects/basenji

Thanks

**Comment by BasenjiBase** [comment]
Hey,

I keep getting an email that another payment needs to be made (received it approx 1 hour ago). I just wanna double check that this is an error since i can see you removed the labels. Also, is there possible to get any ETA on completion?

Thanks,
Basenji Team

**Comment by BasenjiBase** [comment]
Hey guys,

I just tried to swap through Trust Wallet but saw that it's still not
uploaded/Our token isn't uploaded. Do we have any ETA on when it will be
possible for users to swap?

Regards,
Basenji Team

**Comment by BasenjiBase** [comment]
Hey,

Can we get an update on this please?

Regards,
Basenji team

**Pull request merged**
