### PR TITLE
Add Minions INU (BEP20)

### PR DESCRIPTION
**Pull request by CryptoDevilJapan**
Adding info for BEP20 token 'Minions INU'.

PR created by <a href="https://assets.trustwallet.com">TW Assets Management</a>

### CODE REVIEW

**Comment by CryptoDevilJapan** [comment]
⭐Hello TrustWallet team. MinionsINU has gained momentum and is rising day by day.
The team and community are very active on Twitter Space. We attend at least 3 meetings a day. (Images are shared below as an attachment)
⭐Answers to your questions and additional information are below:
✅Our in-game Stakeable NFTs are ready. We have big goals both in terms of DeFi with Stake and in terms of game and GameFi. We also have a partnership initiative for Betting Platform exclusive to the upcoming football matches.
You can watch on Game Trailer on Youtube: https://www.youtube.com/watch?v=5l--QiF_1k4
You can watch on NFT Marketplace review on Youtube: https://www.youtube.com/watch?v=QzTg8DwZ8mU
✅MinionsINU has a website where all financial details are shared and a Whitepaper, and a clean RoadMap that we have created with realistic steps.
✅We benefit Trust Wallet users by our coming integrations and huge community the majority off them use Trust Wallet.
✅MinionsINU was designed with the concept of Sing2Earn last year. We relaunched to create a new design and a more complex ecosystem and increase financial security.
Just MinionsINU reached 7k+ holders, token distributed to 1768-1893 wallets by airdrop to old holders.( We have an Excel file about it if you want we can share it with you.)
We reach 500-1000 holders daily with CoinGecko and CMC listings, negotiations with Kucoin and aggressive marketing. We think that this figure will play in the 300-1000 range as the world cup approaches.
✅We did not hold a Presale
✅We are listed on PancakeSwapV2
⭐Contract Audited and all financial detail shared on Website/Whitepaper&Telegram:
https://github.com/KISHIELD/Audits/blob/main/KISHIELD_MinionsINU_Audit_20230117.pdf
⭐MinionsINU live on CMC:
https://coinmarketcap.com/currencies/minionsinu/
✅Other important links:
⚛️DexTools Chart(Logo,Website&Socials updated): https://www.dextools.io/app/en/bnb/pair-explorer/0x675b21e2339291BdA903dD3Ed2246879c61Ed879
✅Liquidity Locked until 2024: https://www.pinksale.finance/pinklock/record/1065725?chain=BSC
✅WhitePaper: https://minionsinu.net/whitepaper.pdf
✅We bought the website domain via GoDaddy for 5 years.: https://who.is/whois/minionsinu.net
%50 Supply burnt forever before launch: https://bscscan.com/token/0xba7e2a9e5193e60368f440e4ae881cc312d6a160?a=0x000000000000000000000000000000000000dead
⭐First Burnt Evet: We burned all the tokens we had in the remaining DEV wallet. 
We will finance MinionsINU with the proceeds from our NFT sales, our Betting Platform, and investments in our MINIONSVERSE world.
https://bscscan.com/tx/0xfa3f0b983cb8158541210038fbe650614a32f0fca3e76233563de842405436af
⭐MinionsINU most shared Posts on Instagram under [#TrustWallet](tg://search_hashtag?hashtag=TrustWallet) tag, you can check via Instagram or we uploaded screenshots:
https://imgur.com/s0vVqq6
Team and Community always active on Twitter Space:
Team with BNB chain: https://imgur.com/wYnX9VQ
Team with ASTAR NETWORK and SOTA as speaker: https://imgur.com/9MiPYfN
Team with Benzinga and RYO Speaker: https://imgur.com/x7nB7Lh
Team with BabyDogeCoin: https://imgur.com/jBGmDM6
Team with CryptoComNFT: https://imgur.com/JYUEsJN

Please review the details and let us know if payment is required. Best regards and good work, MinionsINU Team

**Comment by Cryptocool1** [comment]
As per our policy, brand new tokens are not included, there is a minimum requirement of 10,000 holder addresses and 15,000 transactions, in order to filter out scam tokens.
See the criteria at : https://developer.trustwallet.com/assets/requirements .

**Comment by CryptoDevilJapan** [comment]
We reach 500-1000 holders daily with CoinGecko and CMC listings, negotiations with Kucoin and aggressive marketing. We think that this figure will play in the 300-1000 range as the exchange listings. We can reach in a week to 10k holders easy... Is this problem? Should y explain this please? You updated this when it has 3000 holders and project finished in 5 days.
https://github.com/trustwallet/assets/pull/22906
https://bscscan.com/token/0xee0736c93e98b2e9fbf11f47db19e7b68db71e94#balances
Lmao you never ask anyhing to them and they said only: "Our tokenomics and utility are designed for Farmer Doge to be your one-stop crypto shop & home base in your crypto investing journey, aswell the majority off our holders use Trust Wallet.

We did not conduct airdrops off token.

we are fair launched.

We are listed on PancakeswapV2
-https://github.com/dappd-net/audits/blob/main/FarmerDoge_Dappd_Audit.pdf "
There is not a future plans, financial details etc etc..

**Comment by Cryptocool1** [comment]
Your first transaction was 3 days ago. How did you get 7k holders in 3 days?

**Comment by CryptoDevilJapan** [comment]
And this : only 2 k holders and they never list on CMC&CG ... Y get payment and updated...
https://bscscan.com/token/0x7f4a15f5cf12e1650f090fb7bc7b0f240f1bde98#balances
https://github.com/trustwallet/assets/pull/10618
Sir, MinionsINU is a 1 year project. If you read the details, we made a relaunch and we have been preparing for 1 year. If you look at the images, we meet regularly with big names like Benzinga, BNBchain, BabyDoge (we set up Stake Pools). and we airdropped about 2k holders (old holders) In bear markets like this an INU project can always make history; See BONK(made 3000x), DGOGE(flying still)

I respect you. My aim is to be fair. Some projects seem to have special advantages when viewed from here. Which our finance team has now researched, I can send you 3 more projects that don't have 3k holders and TrustWallet has updated it.
Anyway, no problem, as our project progresses, we will create the pool again in the coming weeks.

**Comment by Cryptocool1** [comment]
Please don’t send me any other project. We do not disclose or discuss our internal policy and we have right to reject any token.
Feel free to come back to us once all criteria are met.

**Comment by CryptoDevilJapan** [comment]
I respect you. You're right, I was disrespectful. As I said, TrustWallet application was not among our plans at this stage. The community put pressure on it and we wanted to do it too. Other than that, I'm sorry again, see you in a week - 10 days. Respects.

**Comment by Cryptocool1** [comment]
Moreover, your project is not listed on CoinMarketCap (market data is untracked) 
Please come back to us once CMC criterion is met. 
We will reconsider your holders requirement

**Comment by Cryptocool1** [comment]
As I double checked, this CMC link is not redirecting me to you project https://coinmarketcap.com/currencies/minionsinu/
Contract addresses are not the same 
Can you please check?

**Comment by CryptoDevilJapan** [comment]
Okay, we sent an e-mail for them to update. We will apply again when we have arranged all the details and fulfilled the criteria, regards.

**Pull request closed without merging**
