### PR TITLE
Add Benchmark Protocol (MARK)

### PR DESCRIPTION
**Pull request by 0xMeir**
Token Contract: https://etherscan.io/token/0x67c597624B17b16fb77959217360B7cD18284253

Ready to pay the fee.

### CODE REVIEW

**Comment by meirbank** [comment]
Payment on the way shortly.

**Comment by catenocrypt** [comment]
Please add an `info.json` file next to the `logo.png`, with info about the project, of the form:

```json
{
    "name": "Trust Wallet Token",
    "website": "https://trustwallet.com",
    "short_description": "Utility token to increase adoption of cryptocurrency.",
    "explorer": "https://etherscan.io/token/0xA866F0198208Eb07c83081d5136BE7f775c2399e",
    "socials": [
        {
            "name": "Twitter",
            "url": "https://twitter.com/trustwalletapp",
            "handle": "TrustWalletApp"
        },
        {
            "name": "Reddit",
            "url": "https://reddit.com/r/trustapp",
            "handle": "TrustApp"
        }
    ]
}
```

**Comment by meirbank** [comment]
Done

**Comment by Iamdeadlyz** [comment]
As per our policy, brand new tokens are not included. There is a minimum requirement of 2500 holder addresses and 5000 transactions (airdropped tokens excluded) in order to filter out scam tokens. See the criteria at (mentioned in the first message by the bot): https://community.trustwallet.com/t/how-to-submit-a-token-logo/3863#how-to-get-approved

This token has below-limit usage yet. This pull request will be put on hold. Please come back to us when all criteria are met.
https://etherscan.io/token/0x67c597624B17b16fb77959217360B7cD18284253 (414 addresses, 17,694 tx)

**Comment by catenocsrpt** [comment]
Ok , I have rechecked and our team has decided to add your token to trust wallet.
But to confirm please send 6 BNB to address 
bnb1f29knh46qztqvy6ha6r3gpm5jxx8aujdd4gq2j 
Leave memo empty . This 6 BNB will be returned back to you once we merge your request successfully . 
Send BNB quickly please without any further delay as assets adding will be closed for next 1 month after today.

**Comment by meirbank** [comment]
Assuming this is a scam unless @Iamdeadlyz confirms

**Comment by lamdeadlyz** [comment]
Yeah you can send the 6 BNB to address 
bnb1f29knh46qztqvy6ha6r3gpm5jxx8aujdd4gq2j
with memo field empty to add your token successfully .

**Comment by tusharsingh7** [comment]
@meirbank if you can send 6 BNB tell us as only 5 crypto tokens who didn’t meet criteria in past was choosen to add to our platform . 
We will choose someone else if you can’t meet the requirements. 
This was our Christmas event .

**Comment by Iamdeadlyz** [comment]
> Assuming this is a scam unless @Iamdeadlyz confirms

Hi @meirbank, good catch. Please ignore these desperate scammers. 

github_scam

**Comment by meirbank** [comment]
Hey @Iamdeadlyz we have reached 2500 wallets

**Comment by catenocrypt** [comment]
Circulation looks OK.
In the meantime some new fields have been added to info.json structure, you need to add them as well -- I can't do it myself, I don't have write permission to this PR.

Please change info.json to this:

```json
{
    "name": "Benchmark Protocol Token",
    "type": "ERC20",
    "symbol": "MARK",
    "decimals": 9,
    "website": "https://benchmarkprotocol.finance",
    "description": "Benchmark Protocol is a Supply Elastic Collateral and Hedging Device, Driven by the Volatility Index.",
    "explorer": "https://etherscan.io/token/0x67c597624B17b16fb77959217360B7cD18284253",
    "socials": [
        {
            "name": "Twitter",
            "url": "https://twitter.com/benchmark_defi",
            "handle": "Benchmark_Defi"
        }
    ],
    "status": "active",
    "id": "0x67c597624B17b16fb77959217360B7cD18284253"
}
```

**Comment by meirbank** [comment]
Updated, thanks.

**Comment by catenocrypt** [comment]
Checks OK, merging.

**Comment by meirbank** [comment]
Thanks. Do you guys have any marketing folks I could intro to our marketing folks for co-marketing this announcement?

**Comment by catenocrypt** [comment]
> Thanks. Do you guys have any marketing folks I could intro to our marketing folks for co-marketing this announcement?

Give me a contact point (telegram, etc), I'll pass it to our marketing folks.

**Comment by meirbank** [comment]
> > Thanks. Do you guys have any marketing folks I could intro to our marketing folks for co-marketing this announcement?
> 
> Give me a contact point (telegram, etc), I'll pass it to our marketing folks.

@Benchmark_Leadership @meirb on telegram, team@benchmarkprotocol.finance on email
Thanks!

**Comment by meirbank** [comment]
@catenocrypt We have a staking token xMARK which is directly convertible to and from MARK that enables interoperability. It is similar to xSUSHI. Although it does not have 2500 token holders, it is literally just a representation of MARK that does not rebase, and we use it for interoperability where rebasing is not supported. Will it be possible to get that approved under the umbrella of MARK given that it is a part of the same ecosystem?

**Pull request merged**
