### PR TITLE
Add ZDEX logo in changed Smart contract

### PR DESCRIPTION
**Pull request by Shyamthakur33**
Dear Trust team, We changed our smart contract address but the logo still the same, Please add logo in our new changed smart contract and blacklist our old smart contract. Please check here website confirmation for the new smart contract - https://zeedex.io/zdex
New Smart Contract to add- 0x5150956e082c748ca837a5dfa0a7c10ca4697f9c
Old Smart Contract to blacklist - 0x73DBbf72d427076BDd73CF905fDFc442c9C67D4a

### CODE REVIEW

**Comment by Shyamthakur33** [comment]
@zachzwei Please add logo in our new our changed smart contract and blacklist our old smart contract. here is website confirmation for new smart contract https://zeedex.io/zdex

**Comment by Shyamthakur33** [comment]
Dear sir, please also blacklist logo from old smart contract.

**Comment by Shyamthakur33** [comment]
@catenocrypt you there please

**Comment by catenocrypt** [comment]
OK, done;  https://github.com/trustwallet/assets/pull/3871

**Comment by Shyamthakur33** [comment]
@catenocrypt sir, logo still showing in old smart contract. Please recheck
0x73DBbf72d427076BDd73CF905fDFc442c9C67D4a

**Comment by Shyamthakur33** [comment]
WhatsApp Image 2020-09-09 at 2 20 34 PM

**Comment by Shyamthakur33** [comment]
WhatsApp Image 2020-09-09 at 2 20 34 PM

**Comment by Shyamthakur33** [comment]
@catenocrypt Please recheck sir

**Comment by Shyamthakur33** [comment]
> OK, done; #3871

@catenocrypt sir, Logo still showing in Old smart contract. I have cleared cache too. Please recheck
0x73DBbf72d427076BDd73CF905fDFc442c9C67D4a

**Comment by Shyamthakur33** [comment]
@catenocrypt Please recheck and block old smart contract
0x73DBbf72d427076BDd73CF905fDFc442c9C67D4a

WhatsApp Image 2020-09-09 at 2 20 34 PM

**Comment by catenocrypt** [comment]
Let's wait a bit more

**Comment by Shyamthakur33** [comment]
okay, waiting 

> Let's wait a bit more

okay, waiting

**Comment by Shyamthakur33** [comment]
> Let's wait a bit more

@catenocrypt  Logo still not block in the Old smart contract. It's been 6 hours passed. Please recheck again.
0x73DBbf72d427076BDd73CF905fDFc442c9C67D4a

**Comment by Shyamthakur33** [comment]
@catenocrypt now it's more than 16 hours but no update yet

**Comment by Shyamthakur33** [comment]
@catenocrypt you there sir

**Comment by catenocrypt** [comment]
Indeed, strange.  Apparently there is some issue with our denylist handling.  Please be patient until we investigate.
In the meantime, how about if I edit the logo of the old contract to be grayed out and crossed with a red cross?

**Comment by catenocrypt** [comment]
to something like this

image

**Comment by Shyamthakur33** [comment]
ok, please do for this smart contract 0x73DBbf72d427076BDd73CF905fDFc442c9C67D4a

**Comment by Shyamthakur33** [comment]
@catenocrypt  also eagur to know, when you will disappear it fully, bcz our users are getting confused, hope you can understand

**Comment by catenocrypt** [comment]
Old logo was updated with #3892 .

**Comment by Shyamthakur33** [comment]
@catenocrypt how much time it will take to show old contract with a red cross?
Old contract  - 0x73DBbf72d427076BDd73CF905fDFc442c9C67D4a

**Pull request merged**
