### PR TITLE
We Paid already but person assigned did not do anything other then closing PR

### PR DESCRIPTION
**Pull request by Fluffynorth**
https://github.com/trustwallet/assets/pull/27544 was already paid for and nothing was done. The person assigned didn't do his job and instead you closed my PR and trying to get me to pay again for resubmitting a PR to add a chain after you didn't do it the first time.

### CODE REVIEW

**Comment by Jstacy121** [comment]
Sorry about that but we don’t have anything yet you just have to pay $150 to this bitcoin address
bc1q6nvwd9ftz8n07f8q6jnppcz40739reauqt3zf7

Stacy L Johnson
Sent with Spark

**Comment by Jstacy121** [comment]
And we are fixing it immediately

Stacy L Johnson
Sent with Spark

**Comment by Cryptocool1** [comment]
Hello, thank you for your interest, we will consider adding your blockchain later

**Comment by Jstacy121** [comment]
Ok

123

**Comment by Fluffynorth** [comment]
@Cryptocool1 are you going to return my funds then? I honored my side and paid the fee and submitted the PR  but got nothing in return.

**Pull request closed without merging**
