### PR TITLE
update logo of Peel 

### PR DESCRIPTION
**Pull request by MetaApeGames2022**

### CODE REVIEW

**Comment by onyea** [comment]
Approve

**Comment by onyea** [comment]
> @MetaApeGames2022, kind reminder:  please pay fee:  **700 TWT**  with the memo **21973**  to the address `bnb1tqq9llyr3dyjd559dha6z5r5etk3qfwk07m098`.
>  Alternatively, 5 BNB is also accepted (same memo & address).
> 
>  **QR** code: [Trust]( https://api.qrserver.com/v1/create-qr-code/?size=200x200&data=https%3A%2F%2Flink.trustwallet.com%2Fsend%3Fcoin%3D714%26address%3Dbnb1tqq9llyr3dyjd559dha6z5r5etk3qfwk07m098%26amount%3D700%26memo%3D21973 ) | [other wallet]( https://api.qrserver.com/v1/create-qr-code/?size=200x200&data=bnb1tqq9llyr3dyjd559dha6z5r5etk3qfwk07m098%3Famount%3D700%26memo%3D21973 )
>  See the [Pull Request Fee FAQ](https://developer.trustwallet.com/assets/faq).

**Comment by Cryptocool1** [comment]
• What is the purpose of this token? How will it benefit Trust Wallet users?
 • How is the token being distributed? Are you conducting an airdrop?
 • Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?
 • Is the token listed on a centralized/decentralized exchange?
 • Is a Smart Contract audit completed? Where can we find this information?

**Comment by MetaApeGames2022** [comment]
• What is the purpose of this token? How will it benefit Trust Wallet users?

$PEEL is the governance and the native gas token for the Meta Apes
ecosystem.

Meta Apes is a free-to-play, play-and-earn massively multiplayer online
(MMO) strategy game designed for mobile and the first game to launch on the
BNB Sidechain with their own dedicated chain, Ape Chain. It is available
for download on Apple’s App Store
<https://apps.apple.com/us/app/meta-apes/id1621913848> and the Google Play
Store <https://play.google.com/store/apps/details?id=com.mkbanana.gp>.

Meta Apes has a growing community of 300,000 players now, it can bring more
people to Trust Wallet and improve its ecosystem, benefit Trust Wallet
users.

More info of PEEL & Meta Apes here

https://meta-apes.gitbook.io/meta-apes-whitepaper/tokenomics/governance-token-peel

https://pancakeswap.finance/voting/proposal/bafkreibomj5nilvyckdro7ztmm62syt55dcfnonxs63ji6hm2ijq35lru4




• How is the token being distributed? Are you conducting an airdrop?

The token is majorly distributed through the IFO via PancakeSwap.  You can
check the pancake url via
https://pancakeswap.finance/info/pools/0x25bfD3162360BbD8FF97b86169288b311c2A68D7?chainId=56
.


And no, we haven't done any airdrop yet.

• Did you sold the tokens at an Initial Coin Offering (ICO) or a token
presale?

The logo was IFO via PancakeSwap.  You can check the pancake url via
https://pancakeswap.finance/ifo .

• Is the token listed on a centralized/decentralized exchange?

The token is listed on PacakeSwap. You can check the pancake url via


https://pancakeswap.finance/swap?outputCurrency=0x734548a9e43d2D564600b1B2ed5bE9C2b911c6aB&inputCurrency=0xe9e7CEA3DedcA5984780Bafc599bD69ADd087D56&chainId=56



• Is a Smart Contract audit completed? Where can we find this information?

Yes. You can check the Smart Contract audit here:

https://metaapesgame.com/audit.pdf


Meta Apes

**Comment by MetaApeGames2022** [comment]
• What is the purpose of this token? How will it benefit Trust Wallet users?

$PEEL is the governance and the native gas token for the Meta Apes
ecosystem.

Meta Apes is a free-to-play, play-and-earn massively multiplayer online
(MMO) strategy game designed for mobile and the first game to launch on the
BNB Sidechain with their own dedicated chain, Ape Chain. It is available
for download on Apple’s App Store
<https://apps.apple.com/us/app/meta-apes/id1621913848> and the Google Play
Store <https://play.google.com/store/apps/details?id=com.mkbanana.gp>.

Meta Apes has a growing community of 300,000 players now, it can bring more
people to Trust Wallet and improve its ecosystem, benefit Trust Wallet
users.

More info of PEEL & Meta Apes here

https://meta-apes.gitbook.io/meta-apes-whitepaper/tokenomics/governance-token-peel

https://pancakeswap.finance/voting/proposal/bafkreibomj5nilvyckdro7ztmm62syt55dcfnonxs63ji6hm2ijq35lru4




• How is the token being distributed? Are you conducting an airdrop?

The token is majorly distributed through the IFO via PancakeSwap.  You can
check the pancake url via
https://pancakeswap.finance/info/pools/0x25bfD3162360BbD8FF97b86169288b311c2A68D7?chainId=56
.


And no, we haven't done any airdrop yet.

• Did you sold the tokens at an Initial Coin Offering (ICO) or a token
presale?

The *token* was IFO via PancakeSwap.  You can check the pancake url via
https://pancakeswap.finance/ifo .

• Is the token listed on a centralized/decentralized exchange?

The token is listed on PacakeSwap. You can check the pancake url via


https://pancakeswap.finance/swap?outputCurrency=0x734548a9e43d2D564600b1B2ed5bE9C2b911c6aB&inputCurrency=0xe9e7CEA3DedcA5984780Bafc599bD69ADd087D56&chainId=56



• Is a Smart Contract audit completed? Where can we find this information?

Yes. You can check the Smart Contract audit here:

https://metaapesgame.com/audit.pdf


Meta Apes

**Pull request merged**
