### PR TITLE
Add Titan War (BEP20)

### PR DESCRIPTION
**Pull request by titanwarnft**
Adding info for BEP20 token 'Titan War'.

PR created by <a href="https://assets.trustwallet.com">TW Assets Management</a>

### CODE REVIEW

**Comment by titanwarnft** [comment]
@Cryptocool1 This PR is related to #12935 Add TITAN logo and info Which was closed.

**Comment by titanwarnft** [comment]
I removed the Files in my previous PR  #12935 Add TITAN logo and info. Also, @Cryptocool1  you mention before that I will just mention my previous PR so the fee can be reused. Thank you.

**Comment by cryptomanz** [comment]
Hello,
Can your answer some questions?
 • What is the purpose of this token? How will it benefit Trust Wallet users?
 • How is the token being distributed? Are you conducting an airdrop?
 • Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?
 • Is the token listed on a centralized/decentralized exchange?
 • Is a Smart Contract audit completed? Where can we find this information?

**Comment by titanwarnft** [comment]
Hello, Thank you for asking those questions.

Our $TITAN Token will be used as a Reward Token for our Game (Play to Earn) on our web app and android app soon. All Trust Wallet users will be benefited from it, once they hold TITAN Token or use it to play the game, as a reward they get more TITAN Token and will be sent to their corresponding Trust Wallet Address.

The Token was distributed by an ICO or a Token Presale which they get their Token in a real-time transfer.

And Yeah, as I mentioned above, we are on the stage of ICO or a Token Presale and it will end on August 28th, 2021.

Our Token was announced to be listed on August 31st, 2021 on Hotbit.io. (Link Below) 
https://hotbit.zendesk.com/hc/en-us/articles/4406634893719-
and once the presale was ended we will list our token on Pancakeswap.

As of now, Our smartcontract is not yet edited. And soon once it was audited we will notify you.

**Comment by cryptomanz** [comment]
- Awaiting for smart contract audit.

**Comment by Cryptocool1** [comment]
Hello, your token logo should be on full screen
BA4B9FDA-23F6-4381-8793-D7D3C77B7434
Please change

**Comment by titanwarnft** [comment]
> According to our documentation/guidelines token image needs to be full screen, here is link to guidelines details and an example of token images : https://community.trustwallet.com/t/how-to-submit-a-token-logo/3863

logo

**Comment by titanwarnft** [comment]
> > According to our documentation/guidelines token image needs to be full screen, here is link to guidelines details and an example of token images : https://community.trustwallet.com/t/how-to-submit-a-token-logo/3863
> 
> logo

The Logo Size is 256 x 256
with a file name of logo.png
and with a transparent background

For our Smartcontract audit, I will wait for a week before I submit it to you. We are waiting for the final audit of our smartcontract auditors.

**Comment by titanwarnft** [comment]
Hello, Finally our smartcontract audit from Techrate was already done. Attached here is the final audit. @cryptomanz @Cryptocool1 

[Titan War Full Smart Contract Security Audit.pdf](https://github.com/trustwallet/assets/files/7070621/Titan.War.Full.Smart.Contract.Security.Audit.pdf)

**Comment by titanwarnft** [comment]
Pancakeswap Link

https://pancakeswap.finance/swap?outputCurrency=0x76f34cd142ca4a5ea2e197ebffbf5234a1c29268

HOTBIT Link 

https://www.hotbit.io/exchange?symbol=TITANWAR_USDT

**Pull request merged**
