### PR TITLE
Add Irena Green Energy (BEP20)

### PR DESCRIPTION
**Pull request by Amirahmdpwr**
Adding info for BEP20 token 'Irena Green Energy'.

PR created by <a href="https://assets.trustwallet.com">TW Assets Management</a>

### CODE REVIEW

**Comment by Cryptocool1** [comment]
tag 'Energy' is not allowed
Снимок экрана 2022-06-15 в 11 30 34

**Comment by Amirahmdpwr** [comment]
Tag can be : staking 

Payment link : https://explorer.bnbchain.org/tx/5B019FC1B4D4345F5043BAE5F193811A75ECF22AF95C531C7CDC102819B16A70

**Comment by cryptomanz** [comment]
• What is the purpose of this token? How will it benefit Trust Wallet users?
 • How is the token being distributed? Are you conducting an airdrop?
 • Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?
 • Is the token listed on a centralized/decentralized exchange?
 • Is a Smart Contract audit completed? Where can we find this information?

**Comment by Amirahmdpwr** [comment]
The future is now in renewable green energy and eco-friendly electric cars and solar panels. As Irena Green Energy Coin, we have improved ourselves in this regard with our team. Pilot studies of our IGE software, which has been under development for the last 1 year and can be downloaded to electric cars, will be completed in June. You will earn by mining our coin at every distance traveled in every journey you will make with your electric vehicle. Our IR-APOLLON mining device, which we will jointly release with the MinFect Mining Device manufacturer in August 2022, will be able to connect to solar panels. With the electricity produced from solar energy, you will be able to mine our coin with zero cost.

Users will be able to buy an electric car or more in the near future with IRENA Coins, which you will buy by investing for a lunch price today.


There wasn't any ICO & Airdrop 
It was a fairlaunch

Yes it's on pancakeswap / MEXC / CoinTiger and will be on Gate till next month


Yes , please check Certik https://www.certik.com/projects/irena-coin and https://irenamining.com/wp-content/uploads/2022/05/CertiK-Audit-for-Irena-Coin-v4.pdf

**Pull request merged**
