### PR TITLE
Added PPDEX logo and info

### PR DESCRIPTION
**Pull request by pepem00n**

### CODE REVIEW

**Comment by Iamdeadlyz** [comment]
As per our policy, brand new tokens are not included. There is a minimum requirement of 2500 holder addresses and 5000 transactions (airdropped tokens excluded) in order to filter out scam tokens. See the criteria at (mentioned in the first message by the bot): https://community.trustwallet.com/t/how-to-submit-a-token-logo/3863#how-to-get-approved

This token has below-limit usage yet. This pull request will be put on hold. Please come back to us when all criteria are met.
https://etherscan.io/token/0xf1F508c7C9f0d1b15a76fbA564eEf2d956220cf7 (194 holders and 6571 transactions) `5̶3̶5̶ ̶h̶o̶l̶d̶e̶r̶s̶ ̶&̶ ̶6̶9̶1̶2̶ ̶t̶x̶`

**Comment by AymanAlShaibani** [comment]
God

**Comment by catenocrypt** [comment]
No change since over 2 months, closing.  Please have us reopen whn appropriate.

(625 holders, https://etherscan.io/token/0xf1F508c7C9f0d1b15a76fbA564eEf2d956220cf7 )

**Comment by pepem00n** [comment]
hey @catenocrypt can we have a second look at this?

our ecosystem has been growing since last time we requested adding the information of the token by another 50%, and we are definitely not falling into the 'scam' category as we keep building for our ecosystem and users.

adding the info for the token will benefit both new and existing token holders, please consider all the facts.

thanks,
Alex.

**Comment by catenocrypt** [comment]
No of holders is at 910, up from 625 from 2 months ago.

https://etherscan.io/token/0xf1F508c7C9f0d1b15a76fbA564eEf2d956220cf7

**Comment by catenocrypt** [comment]
Please extend the `info.json` file with a few, newly added fields:

```json
"type": "ERC20",
"symbol": "PPDEX",
"decimals": 18,
"status": "active",
"id": "0xf1F508c7C9f0d1b15a76fbA564eEf2d956220cf7"
```

**Comment by catenocrypt** [comment]
Submission technically is OK now, but let's still wait for circulation increase.

**Comment by vikmeup** [comment]
As per our updated policy, brand new tokens are not included, there is a minimum requirement 

- at least 2500 token holders
- at least 500 transactions

See our [How to Get Submit Token Logo ](https://community.trustwallet.com/t/how-to-submit-a-token-logo/3863#how-to-get-approved) guidelines.

Feel free to re-open pull request once you meet those requirements.

**Pull request closed without merging**
