### PR TITLE
update

### PR DESCRIPTION
**Pull request by StakingShop**
i increased bond

### CODE REVIEW

**Comment by kolya182** [comment]
> i increased bond

Can you prove it ?

**Comment by TezoShop** [comment]
sure, i have free space 30k for new delegations https://tzstats.com/tz1V3yg82mcrPJbegqVCPn6bC8w1CSTRp3f8

**Comment by TezoShop** [comment]
but when the place is over I activate the close function

**Comment by TezoShop** [comment]
all ok?

**Comment by kolya182** [comment]
Looks ok, let us know when you run out of capacity again.

**Pull request merged**
