### PR TITLE
Add XPNET (BEP20)

### PR DESCRIPTION
**Pull request by RubyXP**

### CODE REVIEW

**Comment by Cryptocool1** [comment]
hello,
token image size should be 256px by 256px. 
Please follow this documentation where you can find this information: https://community.trustwallet.com/t/how-to-submit-a-token-logo/3863

**Comment by VKint** [comment]
Hi @Cryptocool1

I changed the logo to the right resolution

**Comment by Cryptocool1** [comment]
Great, thanks a lot!

**Comment by VKint** [comment]
@Cryptocool1 anything else needed from our side?

**Pull request merged**
