### PR TITLE
Adding $ORI - HNK Orijent 1919 Token

### PR DESCRIPTION
**Pull request by nemicko**

### CODE REVIEW

**Comment by nemicko** [comment]
We reached today > 10k tx, which full-fills minimum circulation requirements!

**Comment by Cryptocool1** [comment]
As per our policy, brand new tokens are not included, there is a minimum requirement of 5,000 holder addresses and 10,000 transactions, in order to filter out scam tokens.
See the criteria at : https://developer.trustwallet.com/assets/requirements .

**Comment by Cryptocool1** [comment]
• What is the purpose of this token? How will it benefit Trust Wallet users?
 • How is the token being distributed? Are you conducting an airdrop?
 • Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?
 • Is the token listed on a centralized/decentralized exchange?
 • Is a Smart Contract audit completed? Where can we find this information?

**Comment by nemicko** [comment]
• What is the purpose of this token? How will it benefit Trust Wallet users?
 It's part of a Fan Token, but much more an DeFi product allowing  investments into tangible club assets.
 
• How is the token being distributed? Are you conducting an airdrop?
Currently with a LP on PancakeSwap, but we will have AirDrops/Rewards when e.g. winning an game

• Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?
Yes, 174BNB been sold for a price of 1BNB = 3750 Token, on DxSale (link, see down)

• Is the token listed on a centralized/decentralized exchange?
Yes PancakeSwap WBNB/ORI

• Is a Smart Contract audit completed? Where can we find this information?
Yes, we used DxMint, which provide audited smart contracts


PreSale: https://dx.app/app/v3/defipresale?saleID=2149&chain=BSC

**Comment by Cryptocool1** [comment]
can you send your smart contract audit here?

**Comment by cryptomanz** [comment]
Please come back to us when all criteria are met.
When creating a new PR make sure to mention this PR, so that we can see that fee has been paid already here.

**Pull request closed without merging**
