### PR TITLE
Added CAS Logo and info

### PR DESCRIPTION
**Pull request by cashaadev**
Added CAS Logo and info

### CODE REVIEW

**Comment by cashaadev** [comment]
[0x780207b8c0fdc32cf60e957415bfa1f2d4d9718c.zip](https://github.com/trustwallet/assets/files/6042532/0x780207b8c0fdc32cf60e957415bfa1f2d4d9718c.zip)

**Comment by catenocrypt** [comment]
The files in this PR are not placed correctly, I try to sort them out.  Assuming one BEP20 token.

**Comment by catenocrypt** [comment]
Fixes:
- logo file scaled down (to 256x256)
- Move files to correct location, fixes
- Keep overwritten blockchain asset logo and info (reverts)

**Comment by catenocrypt** [comment]
Ready for merge

**Pull request merged**
