### PR TITLE
Add ATM (BEP20)

### PR DESCRIPTION
**Pull request by AthosMeta**
Adding info for BEP20 token 'Athos Meta'.

### CODE REVIEW

**Comment by Cryptocool1** [comment]
• What is the purpose of this token? How will it benefit Trust Wallet users?
 • How is the token being distributed? Are you conducting an airdrop?
 • Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?
 • Is the token listed on a centralized/decentralized exchange?
 • Is a Smart Contract audit completed? Where can we find this information?

**Comment by AthosMeta** [comment]
> • What is the purpose of this token? How will it benefit Trust Wallet users? • How is the token being distributed? Are you conducting an airdrop? • Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale? • Is the token listed on a centralized/decentralized exchange? • Is a Smart Contract audit completed? Where can we find this information?

**• What is the purpose of this token? How will it benefit Trust Wallet users?**
ATM is the main token that will be used mainly around the Athos Meta ecosystem. Everyone can use Trust Wallet to access the ATM dApp and use the features inside.
**• How is the token being distributed? Are you conducting an airdrop?**
ATM token allocation is detailed here: https://docs.athos-meta.io/tokenomics/allocation. We have successfully done an airdrop and bounty, all tokens have been distributed.
**• Did you sell the tokens at an Initial Coin Offering (ICO) or a token presale?**
We will announce the plan to sold Presale in this month.
**• Is the token listed on a centralized/decentralized exchange?**
We will list Dex Exchange as soon as the presale ends on PinkSale
**• Is a Smart Contract audit completed? Where can we find this information?**
You can check out the report here: https://docs.athos-meta.io/about-us/kyc+audit

**Comment by Cryptocool1** [comment]
Your market data on CMC is untracked. On hold for now

**Comment by AthosMeta** [comment]
We have not sold the last round is presale on PinkSale, so we can't list to DEX, so CMC doesn't have data, of course, CMC data will be available right after the presale ends.

**Comment by Cryptocool1** [comment]
Please come back to us once criteria is met.
make sure to mention this PR so the fee can be reused.

**Pull request closed without merging**
