### PR TITLE
Add Swingby BEP20 and update Swingby BEP2

### PR DESCRIPTION
**Pull request by JacobPlaster**
This PR is being closed due to inactivity. If you wish to continue, please have us reopen the PR before sending your payment.
Do NOT send payments for closed PR, as the fee may by lost!
  (300 vs. 60 hrs)

### CODE REVIEW

**Comment by catenocrypt** [comment]
As per our policy, brand new tokens are not included, there is a minimum requirement of 2500 holder addresses and 5000 transactions, in order to filter out scam tokens.
See the criteria at (mentioned in the first message by the bot): https://community.trustwallet.com/t/how-to-submit-a-token-logo/3863).
This token has low usage yet (6). Closing PR for now. Please come back to us when all criteria are met.  Multi-chain and staking tokens may get special treatment, let us know if this is the case. 

https://bscscan.com/token/0x71DE20e0C4616E7fcBfDD3f875d568492cBE4739

**Comment by JacobPlaster** [comment]
> As per our policy, brand new tokens are not included, there is a minimum requirement of 2500 holder addresses and 5000 transactions, in order to filter out scam tokens.
> See the criteria at (mentioned in the first message by the bot): https://community.trustwallet.com/t/how-to-submit-a-token-logo/3863).
> This token has low usage yet (6). Closing PR for now. Please come back to us when all criteria are met. Multi-chain and staking tokens may get special treatment, let us know if this is the case.
> 
> https://bscscan.com/token/0x71DE20e0C4616E7fcBfDD3f875d568492cBE4739

This is a multi-chain token.

The Swingby BEP2 token (https://explorer.binance.org/asset/SWINGBY-888) has over 64k transactions and is already listed on trust wallet. Recently we have deployed bindings allowing our BEP2 holders to move their tokens onto smart chain (BEP20), this pull request adds the data for the BEP20 token.

**Comment by catenocrypt** [comment]
Circulation limit satisfied when considering BEP2+BEP20 together.
Submission OK, merging.

**Comment by JacobPlaster** [comment]
Thanks @catenocrypt! Please re-open the PR and we will proceed with the payment asap

**Comment by JacobPlaster** [comment]
Sorry @catenocrypt, please re-open one more time, I keep missing the 60hr window. I'll make sure to monitor it this time.

**Comment by catenocrypt** [comment]
Reopening.  PRs get auto-closed faster than that, but don't worry, payment will be picked up automatically at next reopen if it got closed in the meantime.  Also note that we plan to reduce the fees somewhat by Monday, due to recent market conditions.

**Pull request closed without merging**
