### PR TITLE
Add ANON jetton logo with info

### PR DESCRIPTION
**Pull request by mrLeo212**

### CODE REVIEW

**Comment by Cryptocool1** [comment]
• What is the purpose of this token? How will it benefit Trust Wallet users?
 • How is the token being distributed? Are you conducting an airdrop?
 • Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?
 • Is the token listed on a centralized/decentralized exchange?
 • Is a Smart Contract audit completed? Where can we find this information?

**Comment by mrLeo212** [comment]
>  What is the purpose of this token? How will it benefit Trust Wallet users?

 It is a community token with its own Telegram p2e app @AnonEarnBot allowing users to mine points to exchange for WEB3 assets, including using ANON stake for more earn.

> • How is the token being distributed? Are you conducting an airdrop?
> • Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?

The token was distributed on April 2 through a presale. https://t.me/anon_club/7

> • Is the token listed on a centralized/decentralized exchange?

Yes. Listed DeDust, STON.fi, MEXC https://coinmarketcap.com/currencies/anon-ton/

**Comment by cryptomanz1** [comment]
We require smart contract audit from reputable companies. Please see https://developer.trustwallet.com/listing-new-assets/requirements

**Comment by mrLeo212** [comment]
> We require smart contract audit from reputable companies. Please see https://developer.trustwallet.com/listing-new-assets/requirements

We used the official Minter: minter.ton.org
Token source code: https://github.com/ton-blockchain/minter-contract/tree/main/contracts
Corresponds to deployed jetton: https://tonviewer.com/EQDv-yr41_CZ2urg2gfegVfa44PDPjIK9F-MilEDKDUIhlwZ?section=code

**Comment by Cryptocool1** [comment]
Hello, we require smart contract audit for each token. Please see our requirements here: https://developer.trustwallet.com/listing-new-assets/requirements

**Comment by Cryptocool1** [comment]
Feel free to come back to us once audit is done. 
Make sure to mention this PR so the fee can be reused

**Comment by mrLeo212** [comment]
> Feel free to come back to us once audit is done. Make sure to mention this PR so the fee can be reused

https://verifier.ton.org/EQDv-yr41_CZ2urg2gfegVfa44PDPjIK9F-MilEDKDUIhlwZ
ORBS verifier from TON.org confirms that our token code matches the standard Jetton code from 11/15/22

**Pull request closed without merging**
