### PR TITLE
Add Adamant (BEP20)

### PR DESCRIPTION
**Pull request by AdamantJD**

### CODE REVIEW

**Comment by cryptomanz** [comment]
• What is the purpose of this token? How will it benefit Trust Wallet users?
 • How is the token being distributed? Are you conducting an airdrop?
 • Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?
 • Is the token listed on a centralized/decentralized exchange?
 • Is a Smart Contract audit completed? Where can we find this information?

**Comment by AdamantJD** [comment]
> Coin

• What is the purpose of this token? How will it benefit Trust Wallet users?

Adamant is a hyperdeflationary Charity token. It is also the governance token of our upcoming NFT game Adamant Mine. Adamant Mine is a play-to-earn, donate, and burn game which enables its players to earn and at the same time be a part of something bigger by being able to nominate and vote for their community charity of choice. At the end of every quarter, the allocated funds in the charity wallet will be donated to the winning charity at the community charity of choice.

Adamant Mine Alpha V0.2 is now live and can be accessible through our website https://adamantmine.com 

Beta (including P2E features) will be released Mid October

• How is the token being distributed? Are you conducting an airdrop?
You can find our token allocation in our website https://adamantcoin.com/
We had a small airdrop campaign (beta tester campaign for our game) last August 1-15

• Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?
Yes we had a pre-sale in cointool 
https://cointool.app/ido/exchange?id=236b572a25527056202150522621222a5227762124505551265221772b51222a23262725572225272b246f2625&fbclid=IwAR1l2fqsyJHLgZm5qlhrLUebdRQJEKA6wju0puX3xBAlp_SIEphzTzBLHAk
https://cointool.app/ido/exchange?id=236b24252023552b26255570562220522026252471522071517120202027222726272a257627765226266f2625

• Is the token listed on a centralized/decentralized exchange? Listed in Pancakeswap: about to be listed in P2PB2B on October 20. 
https://pancakeswap.finance/info/token/0xa55ef2fb2b7b6a60371fd3def9b806e74a48be69
https://p2pb2b.io/token-sale/308/

• Is a Smart Contract audit completed? Where can we find this information?
Audited and verified in bscscan. You can find our audit report attached in the bscscan audit area
https://bscscan.com/address/0xA55EF2fB2B7b6A60371FD3def9B806E74a48bE69#code

**Comment by AdamantJD** [comment]
Please let me know if you need anything else. Thank you

**Comment by cryptomanz** [comment]
Please send me audit smart contract audit.
Here is the example of smart contract audit: https://www.certik.org/projects/binance

**Comment by AdamantJD** [comment]
https://github.com/BlockAudit-Report/Adamant/blob/main/Adamant.pdf

**Comment by cryptomanz** [comment]
Hello,
Please follow the rules for adding tokens, your logo should be a full screen 256x256.
Exemple:
https://community.trustwallet.com/t/how-to-submit-a-token-logo/3863
Screenshot 2021-10-01 at 01 52 16

**Comment by AdamantJD** [comment]
> Hello, Please follow the rules for adding tokens, your logo should be a full screen 256x256. Exemple: https://community.trustwallet.com/t/how-to-submit-a-token-logo/3863 Screenshot 2021-10-01 at 01 52 16

Done. Edited our logo! Sorry and thanks for that!

**Pull request merged**
