### PR TITLE
Add CR7 Token (BEP20)

### PR DESCRIPTION
**Pull request by JeoCrypto**
Adding info for BEP20 token 'CR7 Token'.

PR created by <a href="https://assets.trustwallet.com">TW Assets Management</a>

### CODE REVIEW

**Comment by JeoCrypto** [comment]
I closed the merge by mistake, since it is already paid, I kindly ask you to merge it as soon as possible.

**Comment by cryptomanz** [comment]
• What is the purpose of this token? How will it benefit Trust Wallet users?
 • How is the token being distributed? Are you conducting an airdrop?
 • Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?
 • Is the token listed on a centralized/decentralized exchange?
 • Is a Smart Contract audit completed? Where can we find this information?

**Comment by JeoCrypto** [comment]
• What is the purpose of this Token? How will it benefit Trust Wallet users?

CR7 Token (CR7) has three purposes intended to be achieved by the community of Holders of the fan Token.

Purpose one: to pay tribute to Cristiano Ronaldo dos Santos Aveiro (Cristiano, Ronaldo or Cristiano Ronaldo). The project wants to honor Ronaldo's achievements during his playing days at club level and on the worldwide stage representing Portugal national team - without him; soccer may have never become what it's now known around the world today.

Purpose two: demonstrate the possible broad adoption of CR7 crypto tokens by a massive community unfamiliar with the concept and portray the decentralized governance power of a crypto ecosystem. Many of Cristiano's fans are, up until now, unfamiliar with crypto assets. A crypto-asset aiming at celebrating a sports GOAT is a concept easy to understand. Every fan of sports has had the opportunity of having an album and a sticker collection of their favorite teams and players. Why not HOLDing CR7 instead?

Purpose three: Bring innovation on social networks workflow, creating a new type of Token that will allow people from all over the world to share the same interest in their favorite celebrity (CR7). It is an ample opportunity for more engagement than they would typically experience through traditional social media channels. The scarcity of Token represents a limited number of CR7 fans with access to the Token - the number is a plausible representation of a small number of tokens for each CR7 fan if one measures the number of fans Cristiano has engaging with him on various social networks. Fans will now have new forms of engagement amongst them and can show appreciation, collaborate, or measure interaction by using the Token, bridging existing forms of interaction on social media with new future projects to be developed by the decentralized community under its terms.

How will it benefit Trust Wallet users?

CR7 Token is a fan Token made for the Greatest of All Times (GOAT). CR7 Token will pave the way for the wide acceptance of cryptos and promote their useability and use-cases. The CR7 Token pays tribute to the GOAT and fosters wide crypto assets acceptance! CR7 Token is a very scarce fan Token, with a total supply of only 1.14 billion units. The voracious appetite of CR7 fans in having it will demonstrate to a general audience that crypto-fans want to HOLD! Since it is scarce, people will want to have it. Since it is for fans, people who have it will love to have it. Since the Token usage is registered on-chain, CR7 Tokens can keep track of token ownership, marking new feats and milestones achieved by the CR7 and its fans.

• How is the Token being distributed? Are you conducting an airdrop?

The Token is being distributed By selling the Token on PancakeSwap, Apeswap, and Mdex.

https://www.dextools.io/app/bsc/pair-explorer/0x1cffbdcc27f85aefef7769d852373895bdda66f6

We are working on an airdrop especially for CR7 Fans and holders of other Fan Tokens associated with Sports, Like Santos Token, Porto Token, Lazio, and of course, to our community fans.

• Did you sell the tokens at an Initial Coin Offering (ICO) or a token presale?

- We did a Crowpooling Campaign on Dodo Finance and also a Liquidity Mining Pool:

Details:

https://app.dodoex.io/cp/0x8541321d8030cb5c17aeeff1440fa34f85cee2c5?network=bsc-mainnet

Total Supplied by Creator

77,777,777CR7

Price

1 CR7 = 7.77 BUSD

Tokens for Participants

6,043,333.2729CR7

% of Tokens for Sale

7.77%

Liquidity Protection

90 Days

Start Time

2021/12/19 18:16:25

End Time

2021/12/21 00:00:00

Liquidity Protection Until

2022/03/21 00:00:02

https://app.dodoex.io/pool/list/0x315465303b2e6e6c26b88798cdb1148127fd1865?network=bsc-mainnet

We also have a portion of the tokens locked while studying and testing the best approach to put them on the market and keep their intrinsic value.

Please see:

We have already renounced the ownership.

Please read the deployed contract at:

https://bscscan.com/address/0x6c43751fef27c956f7e75d5c345a65df1465f7e0#readContract

Regarding the Tokens distribution, the tokens are locked at:

https://mudra.website/

https://app.unicrypt.network/amm/pancake-v2/token/0x6C43751FeF27C956f7E75D5c345a65df1465f7E0

• Is the token listed on a centralized/decentralized exchange?

Yes, it is listed on PancakeSwap.

Please see:

https://pancakeswap.finance/info/pool/0x1cffbdcc27f85aefef7769d852373895bdda66f6

We are closing a deal with a Big Centralized Exchange (TOP 10)

• Is a Smart Contract audit completed? Where can we find this information?

Yes! we are KYC by KYC Capital LLC:

https://kyc.capital/KYC/CR7/

And, also, our smart contract is being audited by Certik:

https://www.certik.com/projects/cr7-cash

We send our last update report attached.

Thanks for everything!

Here to help,

The CR7.cash Team

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐
Em terça-feira, 11 de janeiro de 2022 às 13:52, Nazar ***@***.***> escreveu:

**Comment by cryptomanz** [comment]
can you please add tags?
see the requirements here : https://developer.trustwallet.com/assets/repository_details

**Comment by JeoCrypto** [comment]
Hi,
It's Done!

Thanks for everything.

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐
Em terça-feira, 11 de janeiro de 2022 às 21:52, Nazar ***@***.***> escreveu:

**Pull request merged**
