### PR TITLE
ad logo

### PR DESCRIPTION
**Pull request by jamesbondcode**
Please add logo to asset. Thank you.

### CODE REVIEW

**Comment by catenocrypt** [comment]
Please add an `info.json` file next to the `logo.png`, with info about the project, of the form:

```json
{
    "name": "Trust Wallet Token",
    "website": "https://trustwallet.com",
    "short_description": "Utility token to increase adoption of cryptocurrency.",
    "explorer": "https://explorer.binance.org/asset/TWT-8C2"
}
```

**Comment by jamesbondcode** [comment]
> ```json
> {
>     "name": "Trust Wallet Token",
>     "website": "https://trustwallet.com",
>     "short_description": "Utility token to increase adoption of cryptocurrency.",
>     "explorer": "https://explorer.binance.org/asset/TWT-8C2"
> }
> ```

Ah, sorry, never had to do this before... I don't understand at all. Just wanted to add a logo file to a meme coin.

**Comment by jamesbondcode** [comment]
> > ```json
> > {
> >     "name": "Trust Wallet Token",
> >     "website": "https://trustwallet.com",
> >     "short_description": "Utility token to increase adoption of cryptocurrency.",
> >     "explorer": "https://explorer.binance.org/asset/TWT-8C2"
> > }
> > ```
> 
> Ah, sorry, never had to do this before... I don't understand at all. Just wanted to add a logo file to a meme coin.

Am now creating a json file :-)

**Comment by jamesbondcode** [comment]
> Please add an `info.json` file next to the `logo.png`, with info about the project, of the form:
> 
> ```json
> {
>     "name": "Trust Wallet Token",
>     "website": "https://trustwallet.com",
>     "short_description": "Utility token to increase adoption of cryptocurrency.",
>     "explorer": "https://explorer.binance.org/asset/TWT-8C2"
> }
> ```

Done :-)

**Comment by jamesbondcode** [comment]
> @jamesbondcode, kind reminder: please pay fee: **1000 TWT** with the memo **3735** to the address `bnb1tqq9llyr3dyjd559dha6z5r5etk3qfwk07m098`.
> Alternatively, 2 BNB is also accepted (same memo & address).
> 
> **QR** code: [Trust](https://api.qrserver.com/v1/create-qr-code/?size=200x200&data=https%3A%2F%2Flink.trustwallet.com%2Fsend%3Fcoin%3D714%26address%3Dbnb1tqq9llyr3dyjd559dha6z5r5etk3qfwk07m098%26amount%3D1000%26memo%3D3735) | [other wallet](https://api.qrserver.com/v1/create-qr-code/?size=200x200&data=bnb1tqq9llyr3dyjd559dha6z5r5etk3qfwk07m098%26amount%3D1000%26memo%3D3735)
> See the [Pull Request Fee FAQ](https://developer.trustwallet.com/add_new_asset/pr-fee).

Done.

**Comment by catenocrypt** [comment]
OK, I see you need assistance.
Include the 
- token address
- logo image
- project name
- project website
- project description (short)
- token explorer URL
in a comment here, and I'll do the rest for you.  Apparently not a james bond of git :)

**Comment by jamesbondcode** [comment]
> OK, I see you need assistance.
> Include the
> 
> * token address
> * logo image
> * project name
> * project website
> * project description (short)
> * token explorer URL
>   in a comment here, and I'll do the rest for you.  Apparently not a james bond of git :)

Ah, thank you! I did upload an info.json file, but it hasn't worked?

* token address: URL0xDEBd56F6F49ACc8834C2bE9b312C97Cc89F86E90
> * logo image: as uploaded
> * project name: Billie Eilish coin
> * project website: No website, not a project, well, there is the community Telegram/Twitter: https://t.me/BillieEilishCoinChat
> * project description (short): A fan tribute meme token.
> * token explorer: https://etherscan.io/token/0xDEBd56F6F49ACc8834C2bE9b312C97Cc89F86E90

Thank you, hopefully you find the uploaded json file :)

**Comment by catenocrypt** [comment]
>     * token explorer: https://etherscan.io/token/0xDEBd56F6F49ACc8834C2bE9b312C97Cc89F86E90

As I mentioned earlier, we have rules not to add just-created tokens.  There is a very minimal token circulation of min. 100 holder addresses and min. 500 transactions.  I cannot accept this PR now.  Please come back to us again if all criteria are met.
https://community.trustwallet.com/t/how-to-submit-a-token-logo/3863#how-to-get-approved

**Comment by jamesbondcode** [comment]
> > ```
> > * token explorer: https://etherscan.io/token/0xDEBd56F6F49ACc8834C2bE9b312C97Cc89F86E90
> > ```
> 
> As I mentioned earlier, we have rules not to add just-created tokens. There is a very minimal token circulation of min. 100 holder addresses and min. 500 transactions. I cannot accept this PR now. Please come back to us again if all criteria are met.
> https://community.trustwallet.com/t/how-to-submit-a-token-logo/3863#how-to-get-approved

Ah, okay. Noted. :)

**Pull request closed without merging**
