### PR TITLE
Add Learno (LRT) token LOGO TO trust wallet

### PR DESCRIPTION
**Pull request by LearnoCoin**
Add Learno (LRT) token LOGO TO trust wallet 

Token Name : Learno 
Token Symbol : LRT
Token Supply : 1,000,000,000 LRT
Token Contract Address : 0x7194BB18C95c638F9b9604C2f20064B66A0de8fE

0x7194BB18C95c638F9b9604C2f20064B66A0de8fE

### CODE REVIEW

**Comment by LearnoCoin** [comment]
https://explorer.binance.org/tx/55FB0248C8CDE7B30E57E1834CD1D8DFD8328BA9F86FA059D183F87C2DE0F327

Payment proof 2,062.5 TWT-8C2 

please check it sir

**Comment by LearnoCoin** [comment]
When Logo update sir

**Comment by LearnoCoin** [comment]
Please Update Learno (LRT) token LOGO TO trust wallet
Please Update this logo ..Previous Some Upper portal is cut .
Please this logo 

0x7194BB18C95c638F9b9604C2f20064B66A0de8fE

**Comment by kolya182** [comment]
> Please Update Learno (LRT) token LOGO TO trust wallet
> Please Update this logo ..Previous Some Upper portal is cut .
> Please this logo
> 
> 0x7194BB18C95c638F9b9604C2f20064B66A0de8fE

Image added, to to TW and search for it

**Comment by LearnoCoin** [comment]
Please Update Learno (LRT) token LOGO TO trust wallet
Previous Some Upper portal is cut .
Update this sir Urgent 

0x7194BB18C95c638F9b9604C2f20064B66A0de8fE

**Pull request merged**
