### PR TITLE
Add AZW logo to Trustwallet

### PR DESCRIPTION
**Pull request by AZWorldNetwork**

### CODE REVIEW

**Comment by AZWorldNetwork** [comment]
• What is the purpose of this token? How will it benefit Trust Wallet users?
AZ World is a 3.0 "SocialFi" To Earn Platform with a lot of new improvements and innovations optimized for users and content creators to make passive earnings. In 2021 We had GameFi - Play To Earn - Click To Earn - Move To Earn Now Its time of Interact to Earn - "SocialFi" To Earn.

You can read more about us in our whitepaper: 
https://whitepaper.azworld.network/introduction/introduction
• How is the token being distributed? Are you conducting an airdrop?
Token have Fairlaunch presale on Pinksale and now we have publish for everyone buy on pancakeswap.
https://www.pinksale.finance/launchpad/0x65c3253D926ec691723681f641f5bF05c189eCee?chain=BSC 
https://pancakeswap.finance/swap?outputCurrency=0x1F2Cfde19976A2bF0A250900f7aCe9c362908C93

• Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?
Yes we have Fairlaunch on Pinksale last month here is link: 
https://www.pinksale.finance/launchpad/0x65c3253D926ec691723681f641f5bF05c189eCee?chain=BSC

• Is the token listed on a centralized/decentralized exchange?

Yes token is listed on PancakeSwap: 
https://pancakeswap.finance/swap?outputCurrency=0x1F2Cfde19976A2bF0A250900f7aCe9c362908C93

And Coinsbit centralized exchange: 
https://coinsbit.io/trade/AZW_USDT

• Is a Smart Contract audit completed? Where can we find this information?
Yes our Contract is audit by Certik : 
https://www.certik.com/projects/az-world

**Comment by Cryptocool1** [comment]
Hello, 

at least 1 tag is required
See criteria at https://developer.trustwallet.com/assets/requirements

**Comment by AZWorldNetwork** [comment]
done to add tags

**Comment by AZWorldNetwork** [comment]
done to change all tags

**Comment by Cryptocool1** [comment]
Are you conducting an airdrop?

**Comment by AZWorldNetwork** [comment]
Yes, We have airdrop for china market. Real people. Thats in our marketing plan
here is image of proof: 
https://ibb.co/jTXHp7R

**Comment by AZWorldNetwork** [comment]
Did you guys need any information? can i know when we complete for add AZW to Trustwallet  ?

**Comment by AZWorldNetwork** [comment]
Hey bro, anything wrong with my project? Did you need something more for listing ?

**Review by Princeobinna — APPROVED** [review]

**Comment by Princeobinna** [comment]
Approve assets

**Pull request merged**
