### PR TITLE
Add MMS COIN (BEP20)

### PR DESCRIPTION
**Pull request by blockchain2017**
Adding info for BEP20 token 'MMS COIN'.

PR created by <a href="https://assets.trustwallet.com">TW Assets Management</a>

### CODE REVIEW

**Comment by blockchain2017** [comment]
Audit report : https://mms-soilminerals.com/MMS%20COIN.pdf

**Comment by blockchain2017** [comment]
TAG :  STAKING

**Comment by blockchain2017** [comment]
Please reply to List logo on trust wallet

**Comment by cryptomanz1** [comment]
• What is the purpose of this token? How will it benefit Trust Wallet users?
 • How is the token being distributed? Are you conducting an airdrop?
 • Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?
 • Is the token listed on a centralized/decentralized exchange?
 • Is a Smart Contract audit completed? Where can we find this information?

**Comment by blockchain2017** [comment]
Thank you for your Quick response. I really appreciate it.

• What is the purpose of this token? How will it benefit Trust Wallet users
Answer :  MMS Coin Token is used for platform members to staking and to use in Marketplace platform as a payment medium for purchasing goods and services in the system. And developers are working to open new projects to spread the use of Token as much as possible.
Platform members use Trust wallet the most and will maximize Trust wallet usage.

• How is the token being distributed? Are you conducting an airdrop?
Answer : MMS Coin has a large number of token usage bases from the community in the group and the usage base is rapidly expanding. After the List coinmarketcap team and promote through the media The team does not airdrop coins, MMS Coins, but will focus on community exchanges through supported exchanges.

• Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?
Answer : No

• Is the token listed on a centralized/decentralized exchange?
Answer : MMS Coin List on exchange
1. PancakeSwap (Dex Exchange)
2. VinDAX Exchange  (Central Exchange)
3. Finexbox Exchange  (Central Exchange)
 
• Is a Smart Contract audit completed? Where can we find this information?
Answer : https://mms-soilminerals.com/MMS%20COIN.pdf

Thank you very much trust wallet
MMS Coin team

**Pull request merged**
