### PR TITLE
Add BPET logo and info

### PR DESCRIPTION
**Pull request by laochao321**
Add BPET logo and info

### CODE REVIEW

**Comment by Cryptocool1** [comment]
hello,
can you answer some questions?
• What is the purpose of this token? How will it benefit Trust Wallet users?
 • How is the token being distributed? Are you conducting an airdrop?
 • Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?
 • Is the token listed on a centralized/decentralized exchange?
 • Is a Smart Contract audit completed? Where can we find this information?

**Comment by laochao321** [comment]
1. Bpet token is the token used in our NFT game. The game url is https://binapet.com/app
2. Our token pre-sale was completed on August 12, 2021 on dxsale platform, and have already add the Pancake liquidity.
3. 30% is used as pre-sale, the pre-sale price is 30000bpet = 1bnb, 24% is used as liquidity addition, 36% is used as the reward of farming pool and pvp reward in the game, 8% is charged by dxsale platform, and team retains about 2%. At the same time, we will charge 5% of the game transaction amount as transaction fee. 
4. We don't do airdrop. Our smart contract has been audited. The address of the audit report is: https://github.com/solidproof/smart-contract-audits/blob/main/SmartContract_ Audit_ Solidproof_ BinaPet.pdf

**Comment by Cryptocool1** [comment]
can you please add links to your PR?
example: https://developer.trustwallet.com/add_new_asset/repository_details

**Comment by laochao321** [comment]
https://docs.binapet.com

**Comment by Cryptocool1** [comment]
> https://docs.binapet.com

Please see the example how to add links.
https://developer.trustwallet.com/add_new_asset/repository_details

**Comment by laochao321** [comment]
sorry, I dont understand. Do you mean I should add our website to file "info.json"?

**Comment by laochao321** [comment]
> > https://docs.binapet.com
> 
> Please see the example how to add links.
> https://developer.trustwallet.com/add_new_asset/repository_details

How can i commit info.json again?  I upload file to wrong folder, then I can't pull request again. And I delete the forked repository and fork again. It shows me pay again.

**Comment by laochao321** [comment]
I delete the repository and fork again. When I pull request again, it create a new pull request issue, and need pay again. https://github.com/trustwallet/assets/pull/12835  What can I do now?

**Pull request closed without merging**
