### PR TITLE
Add MCNCOIN (BEP20)

### PR DESCRIPTION
**Pull request by TokenLogos**
Adding info for BEP20 token 'MCNCOIN'.

PR created by <a href="https://assets.trustwallet.com">TW Assets Management</a>

### CODE REVIEW

**Comment by TokenLogos** [comment]
The prev payment  [#27398](https://github.com/trustwallet/assets/pull/27398)
• What is the purpose of this token? How will it benefit Trust Wallet users?
=> MCN allows players to not only enjoy the game worlds, but also actively participate in the economy and create real financial achievements, our users use Trust Wallet, and it's useful for them to search and check prices in their portfolios.
• How is the token being distributed? Are you conducting an airdrop?
=> The airdrop event was done. Please check at https://mcncoin.io/ for "The MCNCOIN Token Distribution"
• Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?
=> Yes, ICO
• Is the token listed on a centralized/decentralized exchange?
=> Yes. The MCNCOIN token is listed on CEX (CoinW) and DEX (PancakeSwap)
• Is a Smart Contract audit completed? Where can we find this information?
=> Yes. https://github.com/ContractWolf/smart-contract-audits/blob/main/ContractWolf_Audit_MCNCOIN.pdf

**Comment by Cryptocool1** [comment]
Paid

**Comment by TokenLogos** [comment]
Thank you. Let me know if you have any other questions

**Comment by TokenLogos** [comment]
@Cryptocool1 When can I merge?

**Comment by TokenLogos** [comment]
We can see our logo has been updated, but we don't see the price update from CMC or Coingecko on the Trust app. Would you please check and tell us what the issue is? 
Here is our link in CMC: https://coinmarketcap.com/currencies/mcncoin

**Comment by Cryptocool1** [comment]
Hi, it will be updated soon

**Pull request merged**
