### PR TITLE
update TrueUSD Info and Logo

### PR DESCRIPTION
**Pull request by RandomGly**
update TrueUSD Info and Logo

### CODE REVIEW

**Comment by Cryptocool1** [comment]
hello,
can you send me an official information about updating ?

**Comment by RandomGly** [comment]
> 你好，
> 可以给我一份官方的更新信息吗？

https://trueusd.medium.com/scaling-trust-announcing-tusds-next-stage-of-growth-f1fb58d62b
https://www.trusttoken.com/ change https://www.trueusd.com/

**Comment by RandomGly** [comment]
> hello,
> can you send me an official information about updating ?

https://trueusd.medium.com/scaling-trust-announcing-tusds-next-stage-of-growth-f1fb58d62b
https://www.trusttoken.com/ change https://www.trueusd.com/

**Comment by RandomGly** [comment]
> hello,
> can you send me an official information about updating ?

Hello, the updated information has been sent to you. Please review it as soon as possible!

**Comment by RandomGly** [comment]
When can TWT wallet update Tusd information?

**Comment by tamarastafferd** [comment]
https://github.com/trustwallet/assets/pull/12649#issuecomment-895776087

**Pull request merged**
