### PR TITLE
Add ISLAMICOIN (POLYGON)

### PR DESCRIPTION
**Pull request by ISLAMIBLOCKCHAIN**
Adding info for POLYGON token 'ISLAMICOIN'.

PR created by <a href="https://assets.trustwallet.com">TW Assets Management</a>

### CODE REVIEW

**Comment by Cryptocool1** [comment]
• What is the purpose of this token? How will it benefit Trust Wallet users?
 • How is the token being distributed? Are you conducting an airdrop?
 • Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?
 • Is the token listed on a centralized/decentralized exchange?
 • Is a Smart Contract audit completed? Where can we find this information?

**Comment by Cryptocool1** [comment]
• What is the purpose of this token? How will it benefit Trust Wallet users?
• How is the token being distributed? Are you conducting an airdrop?
• Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?
• Is the token listed on a centralized/decentralized exchange?
• Is a Smart Contract audit completed? Where can we find this information?

**Comment by ISLAMIBLOCKCHAIN** [comment]
• What is the purpose of this token? How will it benefit Trust Wallet users?
The purpose of this token is to become a global cryptocurrency for the Muslim community
ISLAMICOIN have 7 projects that are explained in our whitepaper on our website, these projects will insure the growth of ISLAMICOIN token and will lead to more users demanding it using trust wallet. The Muslim community is now more active using cryptocurrencies and they will always look for the token that provide for them this experience without it being interfering with their beliefs and ” shariaa”. ISLAMICOIN has a long term charity system, in which each transaction triggers a 2.5% of the transferred amount is sent to a charity contract and paid by ISLAMICOIN contract not by the user. The users will always get the same amount when sending or received ISLAMICOIN.
• How is the token being distributed? Are you conducting an airdrop?

The token entered 3 stages of private sale and we raised $60,000
• Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?

Right now we sell our token through our dApp on our website using Matic token
dApp: https://islamicoin.finance/buy-islami 
We are planning to create a lunchpad on pinksale next week.
• Is the token listed on a centralized/decentralized exchange?
The token will be listed on Quickswap & Sushiswap on 31/03/2022
• Is a Smart Contract audit completed? Where can we find this information?
Our smart contract use openzeppelin code.

**Comment by ISLAMIBLOCKCHAIN** [comment]
Our smart contract audit should be ready in 7 days, and we will share the link with you here once it is done.

**Comment by Cryptocool1** [comment]
Feel free to open new PR when smart contract audit will be ready
When creating a new PR make sure to mention this PR, so that we can see that fee has been paid already here.

**Pull request closed without merging**
