### PR TITLE
adding logo and info

### PR DESCRIPTION
**Pull request by IncomeIsland**

### CODE REVIEW

**Comment by IncomeIsland** [comment]
Is everything correct? JSON position 7 is decimals 18 which is correct
Don't really understand what I need to do?

**Comment by IncomeIsland** [comment]
Token is Bep20 - is it in the wrong folder?

**Comment by IncomeIsland** [comment]
I don't really know what i'm doing, just following instructions on a website. 
But i've paid and the info i provided is correct. Please help.

**Comment by IncomeIsland** [comment]
I have put it in the smartchain folder now (Bep20) i think thats correct

**Comment by IncomeIsland** [comment]
Looks like I paid for Bep2, but needed Bep20 - please tell me this will still go through?

**Comment by IncomeIsland** [comment]
Its in the smartchain folder now

**Comment by IncomeIsland** [comment]
> **PR Summary**
> Files OK, 2Files in PR: 2
> Token in PR: BEP20 0x3a91a88ef4bb813bb99ef5a745bcb56e3a3b403b
> Could not retrieve info file; IncomeIsland/assets/master 0x3a91a88ef4bb813bb99ef5a745bcb56e3a3b403b, SyntaxError: Unexpected token : in JSON at position 7

I don't know what this error is. I fixed everything how i believe it should be and put the folder in the right directory

**Review by IncomeIsland — COMMENTED** [review]
I set this up as binance instead of smartchain, have fixed it now

**Comment by Cryptocool1** [comment]
As per our policy, brand new tokens are not included, there is a minimum requirement of 5000 holder addresses and 10000 transactions, in order to filter out scam tokens.
See the criteria at (mentioned in the first message by the bot): https://community.trustwallet.com/t/how-to-submit-a-token-logo/3863).

on hold for now

**Comment by IncomeIsland** [comment]
OK, so when we meet criteria, we can continue? I've already paid so I presume this just gets taken off hold when ready?

**Comment by Cryptocool1** [comment]
Please come back to us when all criteria are met.
When creating a new PR make sure to mention this PR, so that we can see that fee has been paid already here.

**Comment by IncomeIsland** [comment]
Hi there,
  
  
   
  
  
   We paid for this a while ago before we knew about the criteria. We have since been listed on cmc, coingecko etc and have passed kyc with solidproof.io
  
  
   
  
  
   Any chance of getting the logo added?
  
  
   
  
  
   Regards
  
  
   Lee Greenfield 
  
  
   
    On 19/09/2021 01:14 CryptoA ***@***.***> wrote:
   
   
    
   
   
    
   
   
   As per our policy, brand new tokens are not included, there is a minimum requirement of 5000 holder addresses and 10000 transactions, in order to filter out scam tokens.See the criteria at (mentioned in the first message by the bot): https://community.trustwallet.com/t/how-to-submit-a-token-logo/3863).
   on hold for now

**Comment by cryptomanz** [comment]
As per our policy, brand new tokens are not included, there is a minimum requirement of 5000 holder addresses and 10000 transactions, in order to filter out scam tokens.See the criteria at (mentioned in the first message by the bot): https://community.trustwallet.com/t/how-to-submit-a-token-logo/3863).

**Comment by IncomeIslandMetaverse** [comment]
Hi Can someone please look into this and add our logo? We're not a brand new token, we have been launched since last September and are still going strong even through the bear market.

I don't understand why it's so difficult to get our logo added even though we've paid for it and we're a well established project with a hollywood actress as a co owner (Darcy Donavan)

What has the amount of holders got to do with whether we're genuine or not? I've seen tons of projects with hundreds of thousands of holders rug pull and die over the past year and they had logo's in trust wallet!

It's fairly obvious by looking at the history of our project that we're genuine and not a scam token!!

Please, please, add our logo.

**Comment by IncomeIslandMetaverse** [comment]
Hi there,  we have paid for our logo ages ago (#13731) and our project has been going since September 2021. We're not a new project and we're not a scam project, one of our partners is hollywood actress Darcy Donavan, google it to confirm.

It's insane that you would measure whether we're new or a scam project by how many holders we have. I've seen hundreds of rug pulls that match your criteria get logos from you and then rug and die, meanwhile we're struggling just to get a logo that we've paid for put on our project!

This is not fair. Please, please can someone sort this out for us? We paid and we're a well established project! Our metaverse is even in the Microsoft store!!

**Pull request closed without merging**
