### PR TITLE
Add XIO (erc20)

### PR DESCRIPTION
**Pull request by johnblockzero**
Adding info for erc20 token 'XIO'.

PR created by <a href="https://assets.trustwallet.com">TW Assets Management</a>

### CODE REVIEW

**Comment by catenocrypt** [comment]
Submission looks OK.  Waiting for fee payment.

**Comment by catenocrypt** [comment]
Note that fee has been reduced to 500 TWT (due to TWT appreciation; 6 BNB is not changed).

**Comment by johnblockzero** [comment]
Hi Adam!

Apologies I didn’t realise there was a fee - we already have a logo but I wanted to update it to a better version. Will that still cost? 

Separately, I’m also trying to update the logo of our other token called FLASH: https://info.uniswap.org/token/0xb4467e8d621105312a914f1d42f10770c0ffe3c8 <https://info.uniswap.org/token/0xb4467e8d621105312a914f1d42f10770c0ffe3c8> 

Unfortunately it requires 2500 holders - however, we only launched on 1 Jan and currently have just over 1500 holders. Would you accept a logo update by association of our primary token (XIO) having around 5000 holders? 

If you can somehow update them I’ve attached both! 

Thanks,
John

**Comment by catenocrypt** [comment]
We require the fee for all PRs, even existing logo updated.
I think I can accept FLASH token, based on your info/data.
It is possible to have both tokens in one PR.

**Comment by johnblockzero** [comment]
Thanks Adam!

I’ll organise payment now. 

Thanks,
John

**Comment by johnblockzero** [comment]
Hi Adam500 TWT paid: https://explorer.binance.org/tx/5F6A5C52D90A678BE6043EB1ADA052D476E8A3363597D6A77BB072085A1928FAPlease confirm if this PR will also update the XIO logo inside Trust Wallet (not sure why it's different to the current Uniswap logo - I thought they were from same source).The old red/black X logo should be updated to the new black/green Z logo.Thanks Adam!John john@blockzerolabs.io On Thu, 28 Jan 2021 at 11:42 pm, Adam R <notifications@github.com> wrote:
We require the fee for all PRs, even existing logo updated.
I think I can accept FLASH token, based on your info/data.
It is possible to have both tokens in one PR.

?You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.
-- John Velascoblockzerolabs.io

**Comment by johnblockzero** [comment]
Hi Adam Sorry one more question, how do we get the FLASH Token to show a price inside the Trust Wallet?Thanks John On Fri, 29 Jan 2021 at 12:28 am, John Velasco <john@blockzerolabs.io> wrote:Hi Adam500 TWT paid: https://explorer.binance.org/tx/5F6A5C52D90A678BE6043EB1ADA052D476E8A3363597D6A77BB072085A1928FAPlease confirm if this PR will also update the XIO logo inside Trust Wallet (not sure why it's different to the current Uniswap logo - I thought they were from same source).The old red/black X logo should be updated to the new black/green Z logo.Thanks Adam!John john@blockzerolabs.io On Thu, 28 Jan 2021 at 11:42 pm, Adam R <notifications@github.com> wrote:
We require the fee for all PRs, even existing logo updated.
I think I can accept FLASH token, based on your info/data.
It is possible to have both tokens in one PR.

?You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.
-- John Velascoblockzerolabs.io -- John Velascoblockzerolabs.io

**Comment by catenocrypt** [comment]
Fee payment OK, thanks.
Yes, if this PR is merged, logo will be updated to black/green.
Note however that FLASH token is not included here.  Is that OK?

image

**Comment by johnblockzero** [comment]
Hi Adam

Thank you re Blockzero logo. 

Re FLASH logo, you mean not included in the preview? 
But it will be updated per your last email? 

Attached again if you need.

Thanks,
John

**Comment by catenocrypt** [comment]
I mean that Flash logo files are not included in this PR, only XIO.
The following files would be needed:  
`blockchains/ethereum/assets/0xb4467e8d621105312a914f1d42f10770c0ffe3c8/logo.png` and `info.json`.

Maybe simplest is if you submit it separately using https://assets.trustwallet.com

**Comment by johnblockzero** [comment]
Hi Adam

I tried submitting but getting the low circulation error (see screenshot). Is there any way to bypass that rule? 

Or I was hoping you could accept via email.

Thanks
John

**Comment by catenocrypt** [comment]
OK, I'll make an exception.
Attach logo file here and also properly filled info.json.  Here is the sample:

```json
{
    "name": "Trust Wallet Token",
    "website": "https://trustwallet.com",
    "short_description": "Utility token to increase adoption of cryptocurrency.",
    "explorer": "https://etherscan.io/token/0xA866F0198208Eb07c83081d5136BE7f775c2399e",
    "socials": [
        {
            "name": "Twitter",
            "url": "https://twitter.com/trustwalletapp",
            "handle": "TrustWalletApp"
        },
        {
            "name": "Reddit",
            "url": "https://reddit.com/r/trustapp",
            "handle": "TrustApp"
        }
    ]
}
```

**Comment by johnblockzero** [comment]
You’re amazing! Thank you. 

What’s your ERC20 address? I can send you some FLASH so you can try our product :) 

Thanks,
John

**Comment by catenocrypt** [comment]
You can use address catenocrypt.eth for a small amount, we can use for testing.
Please attach the logo+info.

**Comment by johnblockzero** [comment]
Hi Adam

Please see below and attached logo (note I re-attached both logos in high resolution as I noticed in Uniswap that Ethereum has a really clear logo but many of the other tokens look blurry). 

{
    "name": “FLASH",
    "website": "https://flashstake <https://flashstake/>.io",
    "short_description": “FLASH - The time travel of money.",
    "explorer": "https://etherscan.io/token/0xB4467E8D621105312a914F1D42f10770C0Ffe3c8",
    "socials": [
        {
            "name": "Twitter",
            "url": "https://twitter.com/Flashstake",
            "handle": “Flashstake"
        }
    ]
}

Thanks,
John

**Comment by johnblockzero** [comment]
Awesome - love that you have an ENS address! Will send through shortly. 

Thanks again for all your help Adam! 

John
john@blockzerolabs.io

**Comment by johnblockzero** [comment]
Hi Adam - when you update the XIO logo, please also update the token name from “XIO Network” to “XIO”. 

Thanks,
John

**Comment by johnblockzero** [comment]
In case you prefer in this format for the XIO token:

{
    "name": “XIO",
    "website": "https://blockzerolabs <https://blockzerolabs/>.io",
    "short_description": “Blockzero Labs - Blockchain development studio",
    "explorer": "https://etherscan.io/token/0x0f7f961648ae6db43c75663ac7e5414eb79b5704",
    "socials": [
        {
            "name": "Twitter",
            "url": "https://twitter.com/blockzerolabs",
            "handle": “blockzerolabs"
        },
 {
            "name": “YouTube",
            "url": "https://www.youtube.com/c/BOMBX",
            "handle": “Bombx"
        },


    ]
}

**Comment by catenocrypt** [comment]
Where can I find the logo for FLASH?

**Comment by johnblockzero** [comment]
Oh I attached in my last email. I attach both logos again here:
XIO is the Z green logo
FLASH is the thunder pink logo

**Comment by johnblockzero** [comment]
Hi Adam - not sure if the 2 logos attached properly as I replied by email. So re-attaching directly here in GitHub. 

XIO is the Z green logo
FLASH is the thunder pink logo

Blockzero logo_black circle
Flashstake logo_blackpink circle

**Comment by johnblockzero** [comment]
Hi Adam - not sure if the 2 logos attached properly as I replied by email. So re-attaching directly here in GitHub.

FLASH is the thunder pink logo
XIO is the Z green logo

Logo_XIO


Logo_FLASH

**Comment by johnblockzero** [comment]
> Where can I find the logo for FLASH?

Hi @catenocrypt, would you be able to complete this today? Pls see logos above.

**Comment by johnblockzero** [comment]
@catenocrypt ?

**Comment by catenocrypt** [comment]
Flash token added

image

image

**Comment by catenocrypt** [comment]
Merged.  It will take a few hours until logo appears in Trust Wallet.
Thanks for the FLASH tokens.

**Comment by johnblockzero** [comment]
HI @catenocrypt - I can see the FLASH logo updated, but not the Blockzero logo? Maybe I need to wait a bit longer but I assume you have completed as well?

**Comment by johnblockzero** [comment]
@catenocrypt 

Sorry for the re-open. Two issues:

1. The Flash token name, can this be re-named "Flashstake"? Currently it's "Flash Token". The symbol is remains as "FLASH".

2. The XIO token (symbol "XIO") has not updated. Also looking at your image proof above you didn't use the last logo I sent (the circle is a darker black). I've attached again below. This token should be re-named from "XIO Network" to "Blockzero Labs" but the symbol remains as "XIO". 

image

**Comment by johnblockzero** [comment]
@catenocrypt 

Hi Adam - are you able to review my last message above please? At the very least, the Blockzero Labs (XIO) logo never updated in TrustWallet or Uniswap. It is still the old logo. 

The FLASH logo update, but kindly requesting to quickly update to the all-black background above. 

Thanks,
John

**Comment by catenocrypt** [comment]
I can see both updated, I assume it was just the delay.

**Comment by johnblockzero** [comment]
@catenocrypt  

Here are screenshots I just took from TrustWallet and Uniswap. The XIO name and logo haven't updated.

Can you please update per my last message above with the current logos attached?

image

image

**Comment by catenocrypt** [comment]
I see update. May be local cache by app instance.

**Comment by johnblockzero** [comment]
Interesting. The name didn't update. Can you please update "XIO Network" to "Blockzero Labs". The token symbol remains "XIO". 

And please update the FLASH logo to the all-black background I attached above. It's name also needs to be updated from "Flash Token" to "Flashstake". The token symbol remains "FLASH". 

They're the final two updates please!

**Comment by catenocrypt** [comment]
Name is coming from contract; check explorer at  https://etherscan.io/token/0x0f7f961648ae6db43c75663ac7e5414eb79b5704  it shows XIO Network too.

Sorry, no more update on this PR.

**Comment by johnblockzero** [comment]
Thanks @catenocrypt 

Can you please just update the FLASH logo to all-black? 
I can submit a new PR but I'll face the same issue of "inadequate token holders", so it won't let me submit.

**Pull request merged**
