### PR TITLE
Add LockyBoxCoin (BEP20)

### PR DESCRIPTION
**Pull request by rhandnmz**
Adding info for BEP20 token 'LockyBoxCoin'.

PR created by <a href="https://assets.trustwallet.com">TW Assets Management</a>

### CODE REVIEW

**Comment by rhandnmz** [comment]
When will our logo be available on trust wallet

**Comment by Cryptocool1** [comment]
As per our policy, brand new tokens are not included, there is a minimum requirement of 10,000 holder addresses and 15,000 transactions, in order to filter out scam tokens.
See the criteria at : https://developer.trustwallet.com/assets/requirements .

**Review by rhandnmz — COMMENTED** [review]
11

**Comment by rhandnmz** [comment]
please help i don't know what to do

**Comment by rhandnmz** [comment]
i am receiving two error
Screenshot 2022-07-16 223633
s

**Comment by Cryptocool1** [comment]
Feel free to open new PR once all requirement are met. Make sure to mention this PR so the fee can be reused

**Comment by Cryptocool1** [comment]
> i am receiving two error
> Screenshot 2022-07-16 223633
> s

That is not the error

**Pull request closed without merging**
