### PR TITLE
add GYSR ERC20 asset

### PR DESCRIPTION
**Pull request by devinaconley**
This PR adds asset info and logo for the GYSR ERC20 token

### CODE REVIEW

**Comment by catenocrypt** [comment]
As per our policy, brand new tokens are not included, there is a minimum requirement of 2500 holder addresses and 5000 transactions, in order to filter out scam tokens.
See the criteria at (mentioned in the first message by the bot): https://community.trustwallet.com/t/how-to-submit-a-token-logo/3863).
This token has no real usage yet (634). Closing PR for now. Please come back to us when all criteria are met.
 
https://etherscan.io/token/0xbEa98c05eEAe2f3bC8c3565Db7551Eb738c8CCAb

**Comment by devinaconley** [comment]
@catenocrypt - thanks for the feedback. Would like to make the case for GYSR to be accepted.
- it's a utility token which is typically acquired then spent in full, hence the lower holder count (now at 783)
- total transfers > 22K
- uniswap liquidity > 1M USD
- uniswap volume > 250K USD

**Comment by catenocrypt** [comment]
Thanks for the explanation.  Accepted.

**Comment by devinaconley** [comment]
Thanks @catenocrypt  :+1:

**Pull request merged**
