### PR TITLE
Add BeerusCat (BEP20)

### PR DESCRIPTION
**Pull request by inmefinance**
Adding info for BEP20 token 'BeerusCat'.

PR created by <a href="https://assets.trustwallet.com">TW Assets Management</a>

### CODE REVIEW

**Comment by inmefinance** [comment]
What next ?

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by inmefinance** [comment]
Token BEP20 - 0x3a310e6EAf960F9EA208764e9D299ea62A0ea53d:
Symbol: BCat decimals: 9
Links: Logo<https://raw.githubusercontent.com/inmefinance/assets/br0907-200646/blockchains/smartchain/assets/0x3a310e6EAf960F9EA208764e9D299ea62A0ea53d/logo.png> Info<https://raw.githubusercontent.com/inmefinance/assets/br0907-200646/blockchains/smartchain/assets/0x3a310e6EAf960F9EA208764e9D299ea62A0ea53d/info.json> Website<https://beeruscat.tech/> Explorer<https://bscscan.com/token/0x3a310e6EAf960F9EA208764e9D299ea62A0ea53d>
Tags: memes
Token check error:
❌ number of holders not checked: please, check it manually




Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by inmefinance** [comment]
Hello can help !

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by Cryptocool1** [comment]
As per our policy, brand new tokens are not included, there is a minimum requirement of 10,000 holder addresses and 15,000 transactions, in order to filter out scam tokens.
See the criteria at : https://developer.trustwallet.com/assets/requirements .

**Comment by inmefinance** [comment]
Okay thank you

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by inmefinance** [comment]
We need make new request ? Or reply to same ?
Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by inmefinance** [comment]
You send another r-mail please pay 700 twt

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by Cryptocool1** [comment]
Hello, please create new PR, using https://assets.trustwallet.com/

**Comment by inmefinance** [comment]
How can fix holders not checked ?

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by inmefinance** [comment]
Can we process logo add ?

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by Cryptocool1** [comment]
Please see my comment above

**Pull request closed without merging**
