### PR TITLE
Update Fitburn (CAL) Token Info File

### PR DESCRIPTION
**Pull request by Fitburn**

### CODE REVIEW

**Comment by Fitburn** [comment]
hi fitburn has Holders: 13,320 addresses

**Comment by Cryptocool1** [comment]
• What is the purpose of this token? How will it benefit Trust Wallet users?
 • How is the token being distributed? Are you conducting an airdrop?
 • Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?
 • Is the token listed on a centralized/decentralized exchange?
 • Is a Smart Contract audit completed? Where can we find this information?

**Comment by Fitburn** [comment]
• What is the purpose of this token? How will it benefit Trust Wallet users?

- The CAL Token is the FITBURN - Worlds first AI Powered Burn to Earn Ecosystem Token

Users benefit bei getting rewards for burned calories. 

• How is the token being distributed? Are you conducting an airdrop?

 - You can buy it on exchanges and DEX

• Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?

- Yes we did. TrustPad, EnjinStarter, Firestarter, Gamepad, Spores


• Is the token listed on a centralized/decentralized exchange?


- Gate.io <http://Gate.io> , MEXC. BITGET, PancakeSwap


• Is a Smart Contract audit completed? Where can we find this information?

- Yes, done by CERTIK AUDIT.  https://skynet.certik.com/projects/fitburn <https://skynet.certik.com/projects/fitburn> 







Ferhat Kacmaz
CEO & Founder

FitBurn Inc.
P.H. Miraluna, 5-D Ernesto T. Lefevre Ave.
Panama City, Panama
Mobile: +971  (0) 52 - 978 61 79
***@***.***
Web:    www.fitburn.io



Am 04.06.2023 um 11:06 schrieb CryptoA ***@***.***>:


• What is the purpose of this token? How will it benefit Trust Wallet users?
• How is the token being distributed? Are you conducting an airdrop?
• Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?
• Is the token listed on a centralized/decentralized exchange?

• Is a Smart Contract audit completed? Where can we find this information?

**Comment by Fitburn** [comment]
@Cryptocool1 @cryptomanz1

**Pull request merged**
