### PR TITLE
Clover

### PR DESCRIPTION
**Pull request by PeterHePeterHe**
update logo for CLV token

### CODE REVIEW

**Comment by PeterHePeterHe** [comment]
> ### PR Summary
> Files OK: 2 Token in PR: **ERC20** 0x80C62FE4487E1351b47Ba49809EBD60ED085bf52 Symbol: **CLV** decimals: 18 Links: [Logo](https://raw.githubusercontent.com/PeterHePeterHe/assets/master/blockchains/ethereum/assets/0x80C62FE4487E1351b47Ba49809EBD60ED085bf52/logo.png) [Info](https://raw.githubusercontent.com/PeterHePeterHe/assets/master/blockchains/ethereum/assets/0x80C62FE4487E1351b47Ba49809EBD60ED085bf52/info.json) [Website](https://clv.org/) [Explorer](https://etherscan.io/token/0x80C62FE4487E1351b47Ba49809EBD60ED085bf52) Tags: staking-native ✅ Check OK
> 
> 

Does it means the info I provided is correct? Will the logo update after we pay the fee?

**Comment by Cryptocool1** [comment]
> > ### PR Summary
> > Files OK: 2 Token in PR: **ERC20** 0x80C62FE4487E1351b47Ba49809EBD60ED085bf52 Symbol: **CLV** decimals: 18 Links: [Logo](https://raw.githubusercontent.com/PeterHePeterHe/assets/master/blockchains/ethereum/assets/0x80C62FE4487E1351b47Ba49809EBD60ED085bf52/logo.png) [Info](https://raw.githubusercontent.com/PeterHePeterHe/assets/master/blockchains/ethereum/assets/0x80C62FE4487E1351b47Ba49809EBD60ED085bf52/info.json) [Website](https://clv.org/) [Explorer](https://etherscan.io/token/0x80C62FE4487E1351b47Ba49809EBD60ED085bf52) Tags: staking-native ✅ Check OK
> > 
> 
> Does it means the info I provided is correct? Will the logo update after we pay the fee?

Yes, you need to pay the fee for updating

**Comment by PeterHePeterHe** [comment]
> > > ### PR Summary
> > > Files OK: 2 Token in PR: **ERC20** 0x80C62FE4487E1351b47Ba49809EBD60ED085bf52 Symbol: **CLV** decimals: 18 Links: [Logo](https://raw.githubusercontent.com/PeterHePeterHe/assets/master/blockchains/ethereum/assets/0x80C62FE4487E1351b47Ba49809EBD60ED085bf52/logo.png) [Info](https://raw.githubusercontent.com/PeterHePeterHe/assets/master/blockchains/ethereum/assets/0x80C62FE4487E1351b47Ba49809EBD60ED085bf52/info.json) [Website](https://clv.org/) [Explorer](https://etherscan.io/token/0x80C62FE4487E1351b47Ba49809EBD60ED085bf52) Tags: staking-native ✅ Check OK
> > > 
> > 
> > 
> > Does it means the info I provided is correct? Will the logo update after we pay the fee?
> 
> Yes, you need to pay the fee for updating

Hi, I checked the Logo updated in extension wallet, but still the previous version in mobile. Could you help me to check this?

**Comment by PeterHePeterHe** [comment]
> > > ### PR Summary
> > > Files OK: 2 Token in PR: **ERC20** 0x80C62FE4487E1351b47Ba49809EBD60ED085bf52 Symbol: **CLV** decimals: 18 Links: [Logo](https://raw.githubusercontent.com/PeterHePeterHe/assets/master/blockchains/ethereum/assets/0x80C62FE4487E1351b47Ba49809EBD60ED085bf52/logo.png) [Info](https://raw.githubusercontent.com/PeterHePeterHe/assets/master/blockchains/ethereum/assets/0x80C62FE4487E1351b47Ba49809EBD60ED085bf52/info.json) [Website](https://clv.org/) [Explorer](https://etherscan.io/token/0x80C62FE4487E1351b47Ba49809EBD60ED085bf52) Tags: staking-native ✅ Check OK
> > > 
> > 
> > 
> > Does it means the info I provided is correct? Will the logo update after we pay the fee?
> 
> Yes, you need to pay the fee for updating

Hello, I checked the CLV token in trust wallet, the field of "name" on CLV ERC20 is still "Clover". Could you help us to do this correction?

**Pull request merged**
