### PR TITLE
Update logo for SafeGem

### PR DESCRIPTION
**Pull request by SafeGem**

### CODE REVIEW

**Comment by adriancoapsikwiff** [comment]
@catenocrypt @Cryptocool1 Hi guys, can I have an update on this PR? Thanks.

**Comment by SafeGem** [comment]
Hi guys, can I have an update on this PR? thanks.

**Comment by SafeGem** [comment]
Please give me a status. Thanks

**Comment by catenocrypt** [comment]
Merged master to resolve merge conflict.

**Pull request merged**
