### PR TITLE
Update Polychain Monsters and Tixl

### PR DESCRIPTION
**Pull request by fnnhnsn**

### CODE REVIEW

**Comment by cryptomanz** [comment]
hello,
cannot find contract on your website

**Comment by fnnhnsn** [comment]
> hello,
> cannot find contract on your website

Hey cryptomanz, what do you need exactly? We neither linked the contracts on the tixl or Polychainmonsters website, do you need any more specific information I can help you with? :)

**Comment by Cryptocool1** [comment]
> > hello,
> > cannot find contract on your website
> 
> Hey cryptomanz, what do you need exactly? We neither linked the contracts on the tixl or Polychainmonsters website, do you need any more specific information I can help you with? :)

you need to add your contract to your website

**Comment by fnnhnsn** [comment]
> > > hello,
> > > cannot find contract on your website
> > 
> > 
> > Hey cryptomanz, what do you need exactly? We neither linked the contracts on the tixl or Polychainmonsters website, do you need any more specific information I can help you with? :)
> 
> you need to add your contract to your website

Ah thanks, you can see the contract at the bottom of our footer on our [website](https://polychainmonsters.com/).
image

**Comment by Cryptocool1** [comment]
hello,
please delete this file:
blockchains/ethereum/assets/0x1796ae0b0fa4862485106a0de9b654eFE301D0b2/info.json

**Comment by fnnhnsn** [comment]
> hello,
> please delete this file:
> blockchains/ethereum/assets/0x1796ae0b0fa4862485106a0de9b654eFE301D0b2/info.json

Hi, we would like to also update the ERC20 token, will that still happen if that file is deleted? I'd fear that "only" the BEP20 token will be added and the existing ERC20 token won't be updated.

**Comment by Cryptocool1** [comment]
> > hello,
> > please delete this file:
> > blockchains/ethereum/assets/0x1796ae0b0fa4862485106a0de9b654eFE301D0b2/info.json
> 
> Hi, we would like to also update the ERC20 token, will that still happen if that file is deleted? I'd fear that "only" the BEP20 token will be added and the existing ERC20 token won't be updated.

so, you need to change the website, from "http://polychainmonsters.com/" to  "https://polkamon.com/".
(as in explorer) https://etherscan.io/token/0x1796ae0b0fa4862485106a0de9b654eFE301D0b2

**Comment by fnnhnsn** [comment]
> > > hello,
> > > please delete this file:
> > > blockchains/ethereum/assets/0x1796ae0b0fa4862485106a0de9b654eFE301D0b2/info.json
> > 
> > 
> > Hi, we would like to also update the ERC20 token, will that still happen if that file is deleted? I'd fear that "only" the BEP20 token will be added and the existing ERC20 token won't be updated.
> 
> so, you need to change the website, from "http://polychainmonsters.com/" to "https://polkamon.com/".
> (as in explorer) https://etherscan.io/token/0x1796ae0b0fa4862485106a0de9b654eFE301D0b2

Ah I see, thanks for the feedback. We'll update the explorer and come back to you once it's done. Thanks a lot for your patience!

**Comment by Cryptocool1** [comment]
7 days of inactivity.Please come back to us when all criteria are met.
When creating a new PR make sure to mention this PR, so that we can see that fee has been paid already here.please create new PR when all criteria are met.

**Comment by fnnhnsn** [comment]
> 7 days of inactivity.Please come back to us when all criteria are met.
> When creating a new PR make sure to mention this PR, so that we can see that fee has been paid already here.please create new PR when all criteria are met.

Hey @Cryptocool1, our Etherscan token page was finally updated: https://etherscan.io/token/0x1796ae0b0fa4862485106a0de9b654efe301d0b2 could you check it again? Thanks a lot :)

**Pull request closed without merging**
