### PR TITLE
Add MARS4 (ERC20)

### PR DESCRIPTION
**Pull request by mars4code**
Adding info for ERC20 token 'MARS4'.

PR created by <a href="https://assets.trustwallet.com">TW Assets Management</a>

### CODE REVIEW

**Comment by cryptomanz1** [comment]
As per our policy, there is a minimum requirement of 10,000 holder addresses and 15,000 transactions.
See the criteria at : https://developer.trustwallet.com/listing-new-assets/requirements .

**Comment by cryptomanz1** [comment]
Hello,
How did you get more than 5k holders in 1-2 days?

**Comment by mars4code** [comment]
> Hello, How did you get more than 5k holders in 1-2 days?

Through strategic expansion aimed at appealing to a broader audience, we have launched a new game within the MARS4 ecosystem called Mars Battle (which is already live on the Epic store). Preceding this launch, we conducted extensive marketing campaigns, collaborations, competitions, and airdrops. These efforts have significantly increased our numbers across all platforms and expanded our player base substantially.

**Comment by Cryptocool1** [comment]
• What is the purpose of this token? How will it benefit Trust Wallet users?
 • How is the token being distributed? Are you conducting an airdrop?
 • Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?
 • Is the token listed on a centralized/decentralized exchange?
 • Is a Smart Contract audit completed? Where can we find this information?

**Comment by Cryptocool1** [comment]
Please come back to us once you are ready to answer the questions we asked above. When creating new Pull Request please make sure to mention this one, so the fee can be reused.

**Pull request closed without merging**
