### PR TITLE
Add PalmaDOGE (BEP20)

### PR DESCRIPTION
**Pull request by PalmaDOGE**
Adding info for BEP20 token 'PalmaDOGE'.

PR created by <a href="https://assets.trustwallet.com">TW Assets Management</a>

### CODE REVIEW

**Comment by PalmaDOGE** [comment]
When our project updated logo on Trust Wallet ?

**Comment by cryptomanz** [comment]
Hello,
- As per our policy, brand new tokens are not included, there is a minimum requirement of 5000 holder addresses and 10000 transactions, in order to filter out scam tokens.
See the criteria at (mentioned in the first message by the bot): https://community.trustwallet.com/t/how-to-submit-a-token-logo/3863).

**Comment by PalmaDOGE** [comment]
Hi,
We knew what you said. We will IDO & launch at 19th
We'll try to get 5000 holder addresses and 10000 transactions as soon as possible.
Regards,

**Comment by Cryptocool1** [comment]
Please come back to us when all criteria are met.
When creating a new PR make sure to mention this PR, so that we can see that fee has been paid already here.

**Pull request closed without merging**
