### PR TITLE
Add X (BEP20)

### PR DESCRIPTION
**Pull request by sajadkoroush**
Adding info for BEP20 token 'X'.

PR created by <a href="https://assets.trustwallet.com">TW Assets Management</a>

### CODE REVIEW

**Comment by sajadkoroush** [comment]
holders at now : 23,754
transactions at now : 40,253

**Review by sajadkoroush — COMMENTED** [review]
please don't listing ASSA token
just listing X token

**Comment by sajadkoroush** [comment]
https://explorer.bnbchain.org/tx/CA9B8481D267FC2DB01A8517DACC6256F70CF0ED9BBCD3C065950880EF2C00CE
Paid 500 twt tokens
Please list X token

**Comment by Cryptocool1** [comment]
• What is the purpose of this token? How will it benefit Trust Wallet users?
 • How is the token being distributed? Are you conducting an airdrop?
 • Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?
 • Is the token listed on a centralized/decentralized exchange?
 • Is a Smart Contract audit completed? Where can we find this information?

**Comment by sajadkoroush** [comment]
This is the answer from the owner of the token that I received from him and
I am sending to you:

What is the purpose of this token? How will it benefit Trust Wallet users?

We are building a simple AI and we are using this wish to buy subscriptions
to our AI.
Our holders store their assets in the metamask wallet, and by being listed
in Trust Wallet, we plan to move our holders to use Trust Wallet.

• How is the token being distributed? Are you conducting an airdrop? We had
an early sale at PancakeSwap /We did not have an airdrop
• Did you sold the tokens at an Initial Coin Offering (ICO) or a token
presale?

Our first sale was at Pancake Swap

30% of the tokens are fully distributed among the holders and the rest is
in the Pancake Swap pool

• Is the token listed on a centralized/decentralized exchange? Yes
PancakeSwap
• Is a Smart Contract audit completed? Where can we find this information?

We submitted an audit request to hacken.io and the results will probably
come by next week.
Contract address:

0x361dF081e8AcCac1115693b2E84a1A09d9F0d49c

**Comment by Cryptocool1** [comment]
We require smart contract audit, on hold for now

**Comment by sajadkoroush** [comment]
The owner sent me the audit token.

**Comment by Cryptocool1** [comment]
Please send it from Hacken website

**Comment by sajadkoroush** [comment]
excuse me, do you mean this?
https://www.cyberscope.io/audits/11-x

**Comment by sajadkoroush** [comment]
The hacken request is not finalized yet

**Comment by Cryptocool1** [comment]
Are you listed on CoinMarketCap?

**Comment by sajadkoroush** [comment]
Not yet

**Comment by Cryptocool1** [comment]
We require CoinMarketCap listing. Feel free to come back to us once you listed

**Comment by sajadkoroush** [comment]
Ok, It will be sent to you as soon as it is listed.  Will it be listed after being listed in trust wallet?

**Pull request closed without merging**
