### PR TITLE
Add Fairface Token (BEP20)

### PR DESCRIPTION
**Pull request by dhavalmp194**
Adding info for BEP20 token 'Fairface Token'.

PR created by <a href="https://assets.trustwallet.com">TW Assets Management</a>

### CODE REVIEW

**Comment by dhavalmp194** [comment]
How to check a number of holders manually?
and what is the procedure for moving further ?

**Comment by cryptomanz** [comment]
• What is the purpose of this token? How will it benefit Trust Wallet users?
 • How is the token being distributed? Are you conducting an airdrop?
 • Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?
 • Is the token listed on a centralized/decentralized exchange?
 • Is a Smart Contract audit completed? Where can we find this information?

**Comment by cryptomanz** [comment]
Please come back to us when all criteria are met.
When creating a new PR make sure to mention this PR, so that we can see that fee has been paid already here.

**Comment by dhavalmp194** [comment]
• What is the purpose of this token? How will it benefit Trust Wallet users?
Fairface FAF token is is a reward token for the customers who write reviews on Fairface platform. The rewarded FAF token can be transferred to customer wallets including Trust wallet users. 
• How is the token being distributed? Are you conducting an airdrop?
We have distributed tokens in Pre-sale and also will distribute in future Airdrops. 
Yes, we are conducting an airdrop at the moment and expect to distribute tokens to 10,000 users holding accounts in Trustwallet or metamask.
• Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?
Yes, we sold tokens in presale.
• Is the token listed on a centralized/decentralized exchange?
Token will be listed soon, currently we are doing IEO sale on Probit Global exchange https://www.probit.com/en-us/ieo/faf-round1/0 
• Is a Smart Contract audit completed? Where can we find this information?
Yes, The Audit is done by Certik. https://www.certik.com/projects/fairface

**Comment by dhavalmp194** [comment]
hey @cryptomanz can you please check above details?

**Pull request closed without merging**
