### PR TITLE
updated tits contract

### PR DESCRIPTION
**Pull request by RealTinyTitans**
Listed on CMC https://coinmarketcap.com/currencies/tiny-titans/

Paid here and merged here #12737

Pleas update because users buying wrong tits token.

@Cryptocool1 thanks for the hint ;D

### CODE REVIEW

**Comment by RealTinyTitans** [comment]
@Cryptocool1 is a new payment required?

**Comment by Cryptocool1** [comment]
> @Cryptocool1 is a new payment required?

Yes, you should make the payment for that

**Comment by cryptomanz** [comment]
• What is the purpose of this token? How will it benefit Trust Wallet users?
 • How is the token being distributed? Are you conducting an airdrop?
 • Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?
 • Is the token listed on a centralized/decentralized exchange?
 • Is a Smart Contract audit completed? Where can we find this information?

**Comment by RealTinyTitans** [comment]
@cryptomanz 

Tits is the native token of the first 100% blockchain-based pay to earn decentralized app. It allows the players to mint game tamagotchi-like character NFTs and interact with the game itself. Some examples of the utility of TITS are:

feeding your game character (Titans, Hatchlings or Commanders)
buy power-ups
fight other players NFTs
and much more…

No presale, no ICO, no airdrop. The token is a fight reward with the game character.

Token can traded here:
https://pancakeswap.finance/swap?outputCurrency=0x2a5eB92f6a410AC0BB38D92C13DA934bD68EF24E

There was no audit for the contract.

**Comment by RealTinyTitans** [comment]
Guess we are one of the legit project around here @cryptomanz

**Pull request merged**
