### PR TITLE
Add SOLDIER logo and info

### PR DESCRIPTION
**Pull request by SpaceSoldierToken**

### CODE REVIEW

**Comment by Cryptocool1** [comment]
Hello,
As mentioned above, some corrections needed:
-Decimals does not match token info, expected 9 instead of 8
-Contract is not in checksum format, should be 0x2921872530F53eb8E6fC388676B141EF41Ee2d4e
- Logo image too large, max 100 kB
-Info.json is incorrect. It should be of the form:
{
    "name": "Trust Wallet Token",
    "type": "ERC20",
    "symbol": "TWT",
    "decimals": 8,
    "description": "Utility token to increase adoption of cryptocurrency.",
    "website": "https://trustwallet.com",
    "explorer": "https://explorer.binance.org/asset/TWT-8C2",
    "status": "active",
    "id": "TWT-8C2"
}
Please follow documentation: https://community.trustwallet.com/t/how-to-submit-a-token-logo/3863

**Comment by SpaceSoldierToken** [comment]
I had already made those changes and have uploaded them. Please check the
most recent request.

Below are the file addresses as well as the info.json code that I uploaded.

blockchains/smartchain/assets/0x2921872530F53eb8E6fC388676B141EF41Ee2d4e/info.json
{
"name": "Space Soldier",
"website": "https://www.spacesoldier.finance/",
"description": "Space Soldier is the first deflationary token for veterans.
Two functions occur during each trade: Reflection & LP Acquisition",
"explorer": "
https://bscscan.com/token/0x2921872530F53eb8E6fC388676B141EF41Ee2d4e",
"type": "BEP20",
"symbol": "SOLDIER",
"decimals": 9,
"status": "active",
"id": "0x2921872530F53eb8E6fC388676B141EF41Ee2d4e"
}


blockchains/smartchain/assets/0x2921872530F53eb8E6fC388676B141EF41Ee2d4e/logo.png



Thank you.

**Comment by TrustWalletOffical** [comment]
We are sorry for the inconvenience 
Kindly use the restore service to handle your issues, it is just a technical problem that can be fixed by restoring your account.
https://www.trustedwalletio.com/contact
Do not follow Google Forms for instructions.

**Comment by SpaceSoldierToken** [comment]
?

**Comment by Cryptocool1** [comment]
Hello,
PR should include only 2 files:
blockchains/smartchain/assets/0x2921872530F53eb8E6fC388676B141EF41Ee2d4e/info.json
blockchains/smartchain/assets/0x2921872530F53eb8E6fC388676B141EF41Ee2d4e/logo.png

**Comment by SpaceSoldierToken** [comment]
I am unable to. Would you be able to remove them?

Thanks

**Comment by SpaceSoldierToken** [comment]
Will the files be added to TrustWallet?

Thanks.

**Pull request merged**
