### PR TITLE
Add AMA logo and info

### PR DESCRIPTION
**Pull request by Mrwebfi**

### CODE REVIEW

**Comment by Mrwebfi** [comment]
Please add AMA token price

https://coinmarketcap.com/currencies/mrweb-finance/

**Comment by Mrwebfi** [comment]
@Crack019 please add our token price to trust wallet app

https://coinmarketcap.com/currencies/mrweb-finance/

**Comment by Cryptocool1** [comment]
https://community.trustwallet.com/t/why-is-there-no-token-logo-or-price/138596

**Comment by Mrwebfi** [comment]
> https://community.trustwallet.com/t/why-is-there-no-token-logo-or-price/138596

I think we have met all those requirements. Our token already in coinmarketcap.com:
https://coinmarketcap.com/currencies/mrweb-finance/

And on coingecko.com: 
https://www.coingecko.com/en/coins/mrweb-finance

**Comment by Mrwebfi** [comment]
@Cryptocool1 @catenocrypt @zachzwei may I know what's wrong with our data which is preventing our price from showing in the trust wallet app?

**Comment by Mrwebfi** [comment]
No reply?

**Comment by huckhelp** [comment]
please can you reply to us to know whats the issue

**Comment by zachzwei** [comment]
Apologies for the delay. Our devs has fixed the price for this token.

**Comment by Mrwebfi** [comment]
> Apologies for the delay. Our devs has fixed the price for this token.

Thanks.

**Pull request merged**
