### PR TITLE
Add BBC and logo

### PR DESCRIPTION
**Pull request by bullbtcclub**
Resubmit, please review, thank you

### CODE REVIEW

**Review by bullbtcclub — COMMENTED** [review]
Deleted invalid link

**Comment by Cryptocool1** [comment]
• What is the purpose of this token? How will it benefit Trust Wallet users?
 • How is the token being distributed? Are you conducting an airdrop?
 • Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?
 • Is the token listed on a centralized/decentralized exchange?
 • Is a Smart Contract audit completed? Where can we find this information?

**Review by Rayyy369 — COMMENTED** [review]
Okay

**Comment by bullbtcclub** [comment]
> • What is the purpose of this token? How will it benefit Trust Wallet users? • How is the token being distributed? Are you conducting an airdrop? • Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale? • Is the token listed on a centralized/decentralized exchange? • Is a Smart Contract audit completed? Where can we find this information?

Hi, here is the information you requested

• What is the purpose of this token? How will it benefit Trust Wallet users?

BBC token is the governance of Bull BTC Club ecosystem,users shall using BBC token to get BBC mysteryboxes which benchmarking to the real hashpower.BBC has now listing on Kucoin.We would like to do an airdrop for trust wallet users if you want.

• How is the token being distributed? Are you conducting an airdrop?

Users can buy BBC token on Kucoin exchange now,and we are willing to conducting an airdrop


Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?

No,we already listing now,no ICO

• Is the token listed on a centralized/decentralized exchange?
Both,DEX listing on Pancake,CEX listing on Kucoin

• Is a Smart Contract audit completed? Where can we find this information?
Yes,by Certik,https://www.certik.com/projects/bull-btc-club

**Pull request merged**
