### PR TITLE
Add ERC20 Token - MAGA

### PR DESCRIPTION
**Pull request by GuolongCyber**

### CODE REVIEW

**Comment by GuolongCyber** [comment]
paid.

**Comment by GuolongCyber** [comment]
> @GuolongCyber, kind reminder: please pay fee: **500 TWT** with the memo **28302** to the address `bnb158fgd782we4tz9vwwcj9pmmxvxhl6z46lfm7c8`. Alternatively, 2 BNB is also accepted (same memo & address).
> 
> **QR** code: [Trust](https://api.qrserver.com/v1/create-qr-code/?size=200x200&data=https%3A%2F%2Flink.trustwallet.com%2Fsend%3Fcoin%3D714%26address%3Dbnb158fgd782we4tz9vwwcj9pmmxvxhl6z46lfm7c8%26amount%3D500%26memo%3D28302) | [other wallet](https://api.qrserver.com/v1/create-qr-code/?size=200x200&data=bnb158fgd782we4tz9vwwcj9pmmxvxhl6z46lfm7c8%3Famount%3D500%26memo%3D28302) See the [Pull Request Fee FAQ](https://developer.trustwallet.com/assets/faq).

check

**Comment by GuolongCyber** [comment]
> @GuolongCyber, kind reminder:  please pay fee:  **500 TWT**  with the memo **28302**  to the address `bnb158fgd782we4tz9vwwcj9pmmxvxhl6z46lfm7c8`.
>  Alternatively, 2 BNB is also accepted (same memo & address).
> 
>  **QR** code: [Trust]( https://api.qrserver.com/v1/create-qr-code/?size=200x200&data=https%3A%2F%2Flink.trustwallet.com%2Fsend%3Fcoin%3D714%26address%3Dbnb158fgd782we4tz9vwwcj9pmmxvxhl6z46lfm7c8%26amount%3D500%26memo%3D28302 ) | [other wallet]( https://api.qrserver.com/v1/create-qr-code/?size=200x200&data=bnb158fgd782we4tz9vwwcj9pmmxvxhl6z46lfm7c8%3Famount%3D500%26memo%3D28302 )
>  See the [Pull Request Fee FAQ](https://developer.trustwallet.com/assets/faq).

what happen?? I've already paid.

@Cryptocool1 @cryptomanz1

**Comment by GuolongCyber** [comment]
@Cryptocool1  check pls

txhash:https://explorer.bnbchain.org/tx/BD99EA9BE8B97CDD46A6FE40C1D3CAD1E575313406C657D4A3CC189C59A19F86

**Comment by Cryptocool1** [comment]
• What is the purpose of this token? How will it benefit Trust Wallet users?
 • How is the token being distributed? Are you conducting an airdrop?
 • Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?
 • Is the token listed on a centralized/decentralized exchange?
 • Is a Smart Contract audit completed? Where can we find this information?

**Comment by GuolongCyber** [comment]
> • What is the purpose of this token? How will it benefit Trust Wallet users? • How is the token being distributed? Are you conducting an airdrop? • Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale? • Is the token listed on a centralized/decentralized exchange? • Is a Smart Contract audit completed? Where can we find this information?

-


> • What is the purpose of this token? How will it benefit Trust Wallet users?

$MAGA is mainly a popular meme token, and many fans are enthusiastic about it. We will recommend fans to use trust wallets to build better bridges.

> • How is the token being distributed? Are you conducting an airdrop?

We sent all the tokens to DEX (Uniswap) without any airdrops.

> • Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?

No ICO or Presale.

> • Is the token listed on a centralized/decentralized exchange?

DEX:
 - Uniswap
 
CEX:  
 - https://www.gate.io/zh/trade/MAGA_USDT  - https://poloniex.com/trade/MAGA_USDT/?type=spot
 - https://www.mexc.com/zh-TW/exchange/magaeth_USDT?_from=header
 - https://www.htx.co.si/trade/maga_usdt?type=spot
 - https://www.lbank.com/trade/maga_usdt

> • Is a Smart Contract audit completed? Where can we find this information?

https://github.com/SpyWolfNetwork/Smart_Contract_Audits/blob/main/May_2024/MAGA_0xD29DA236dd4AAc627346e1bBa06A619E8c22d7C5.pdf

@Cryptocool1 
-------

Thanks trust team!

**Pull request merged**
