### PR TITLE
Add 0xzx logo and info

### PR DESCRIPTION
**Pull request by 0xzx**

### CODE REVIEW

**Comment by 0xzx** [comment]
Why all checks have failed

**Comment by catenocrypt** [comment]
Errors can be seen within the check build details.
However, apart of the technical problems, there is the issue of low circulation: 25 holder addresses, whereas we have a limit of min. 2500.  Any thoughts?
 
https://bscscan.com/token/0x1fbb6ca220dcbe732f796fa9b13dd21cd654511b

```
   XXX   'Expect asset at path /home/runner/work/assets/assets/blockchains/smartchain/assets/0x1fbb6ca220dcbe732f796fa9b13dd21cd654511b in checksum: '0x1fBB6cA220dCBE732f796Fa9b13dd21cD654511b''
    XXX   'Description too long, 600, /home/runner/work/assets/assets/blockchains/smartchain/assets/0x1fbb6ca220dcbe732f796fa9b13dd21cd654511b/info.json'
```

**Comment by 0xzx** [comment]
> Errors can be seen within the check build details.
> However, apart of the technical problems, there is the issue of low circulation: 25 holder addresses, whereas we have a limit of min. 2500. Any thoughts?
> 
> https://bscscan.com/token/0x1fbb6ca220dcbe732f796fa9b13dd21cd654511b
> 
> ```
>    XXX   'Expect asset at path /home/runner/work/assets/assets/blockchains/smartchain/assets/0x1fbb6ca220dcbe732f796fa9b13dd21cd654511b in checksum: '0x1fBB6cA220dCBE732f796Fa9b13dd21cD654511b''
>     XXX   'Description too long, 600, /home/runner/work/assets/assets/blockchains/smartchain/assets/0x1fbb6ca220dcbe732f796fa9b13dd21cd654511b/info.json'
> ```

The project has just migrated from the Ethereum network to BSC, so the number of holders and transactions is somewhat small, but it is by no means a scam. 0xzx's Ethereum token has been updated in Trust Wallet very early.

**Comment by catenocrypt** [comment]
Can you provide ERC20 token version explorer link?
In  https://etherscan.io/token/0xe984ADE4D5daFA623180460759F4073b6a470656
I can see 5 holders / 11 transactions; this is very low circulation.

**Comment by 0xzx** [comment]
> Can you provide ERC20 token version explorer link?
> In https://etherscan.io/token/0xe984ADE4D5daFA623180460759F4073b6a470656
> I can see 5 holders / 11 transactions; this is very low circulation.

Indeed, because the gas cost of ETH is too high and the project is in the initial stage, we don’t have much funds to distribute tokens, so we migrated to the lower cost BSC.

**Comment by catenocrypt** [comment]
As per our policy, brand new tokens are not included, there is a minimum requirement of 2500 holder addresses and 5000 transactions, in order to filter out scam tokens.
See the criteria at (mentioned in the first message by the bot): https://community.trustwallet.com/t/how-to-submit-a-token-logo/3863).
This token has no real usage yet (25; 5 holders). Closing PR for now. Please come back to us when all criteria are met.  Multi-chain and staking tokens may get special treatment, let us know if this is the case. 

https://bscscan.com/token/0x1fbb6ca220dcbe732f796fa9b13dd21cd654511b

**Comment by catenocrypt** [comment]
Payment considered for #6182 .

**Pull request closed without merging**
