### PR TITLE
XCUR - Logo update for BEP20 (already on ERC20)

### PR DESCRIPTION
**Pull request by TheOneXi**
Adding our logo for our BEP20 variant of our token XCUR.

The attached .zip folder contains our description and website in the JSON.info file.

Have also updated the json.info content as per Adam R's instructions. Thanks!

[0xE1c7E30C42C24582888C758984f6e382096786bd.zip](https://github.com/trustwallet/assets/files/6398606/0xE1c7E30C42C24582888C758984f6e382096786bd.zip)

### CODE REVIEW

**Comment by curateproject** [comment]
This is what's inside the JSON.info file, does this have a syntax error?

If yes, please can you edit:

{
    "name": "Curate",
    "symbol": "XCUR",
    "type": "ERC20",
    "decimals": 8,
    "description": "-",
    "website": "",
    "explorer": "https://etherscan.io/token/0xE1c7E30C42C24582888C758984f6e382096786bd",
    "status": "active",
    "id": "0xE1c7E30C42C24582888C758984f6e382096786bd"

    "name": "Curate",
    "type": "BEP20",
    "symbol": "XCUR",
    "decimals": 8,
    "description": "Curate is the world's first all in one marketplace app that supports cryptocurrencies as a payment infrastructure and rewards buyers/sellers on all transactions.",
    "website": "https://curate.style/",
    "explorer": "https://bscscan.com/token/0x708c671aa997da536869b50b6c67fa0c32ce80b2",
    "status": "active",
    "id": "0x708C671Aa997da536869B50B6C67FA0C32Ce80B2"
}

**Comment by curateproject** [comment]
What does this mean?

**Comment by catenocrypt** [comment]
> If yes, please can you edit:

Please, why can't you edit it yourself?

**Comment by curateproject** [comment]
Hi Adam,

If you tell me what to do I'll do it happily.

Thanks!

**Comment by curateproject** [comment]
> > If yes, please can you edit:
> 
> Please, why can't you edit it yourself?

Has this been fixed now or do you need me to fix it?

**Comment by catenocrypt** [comment]
It's been fixed and merged.

**Comment by curateproject** [comment]
Great will be logo start to show on the app for XCUR BEP20 soon?

**Comment by curateproject** [comment]
Thanks, when will the logo show for BEP20 in TrustWallet?

**Pull request merged**
