### PR TITLE
Add Puli Inu (BEP20)

### PR DESCRIPTION
**Pull request by MrLightspeed**
Adding info for BEP20 token 'Puli Inu'.

PR created by <a href="https://assets.trustwallet.com">TW Assets Management</a>

### CODE REVIEW

**Comment by MrLightspeed** [comment]
Do we meet the listing requirements?

**Comment by Cryptocool1** [comment]
• What is the purpose of this token? How will it benefit Trust Wallet users?
 • How is the token being distributed? Are you conducting an airdrop?
 • Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?
 • Is the token listed on a centralized/decentralized exchange?
 • Is a Smart Contract audit completed? Where can we find this information?

**Comment by MrLightspeed** [comment]
> • What is the purpose of this token? How will it benefit Trust Wallet users?

Puli Inu (PULI) delivers simple yet very addicting P2E games every month. The first game, Puli Runner, was successfully launched on 31 January 2022 and can be played at https://www.puli-inu.com/puligames. The team is also developing a platform to Store, Swap, Play, Chat and Earn tokens while introducing new investors to crypto in an enjoyable way.

The purpose and key features of the token include a 10% Buy and 10% Sell tax that are used to fund aggressive marketing and ensure stable liquidity. In addition, the asset can be staked for additional earnings with instructions available at their website.


• How is the token being distributed? Are you conducting an airdrop? 

The token fair launched on 01/15/2022. There will be no airdrop. The token distribution includes a 10% Buy and 10% Sell Tax that funds liquidity and marketing efforts. 21.69% is in locked liquidity with 17.63% in the staking treasury. Both are treated as out of circulation. We also have verified circulation supplies reported on Coingecko, Nomics, LiveCoinWatch and CMC is working on the verified circulation now. 

• Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?

There was no ICE or Presale.

 • Is the token listed on a centralized/decentralized exchange?
 
 Yes, the token is listed at Coinsbit and will launch on P2PB2B on 8 Feb 2022.
 
  • Is a Smart Contract audit completed?
  
  Yes, we have to audits completed:
  https://github.com/coinscope-co/audits/blob/main/puli/audit.pdf
  
  
  
  Where can we find this information?

**Comment by Cryptocool1** [comment]
submission looks good, waiting for fee payment

**Comment by MrLightspeed** [comment]
Thank you, give us a day and we will transmit the funds. I sincerely appreciate all the support.

 

Best regards

**Pull request merged**
