### PR TITLE
Add Vodka Token (BEP20)

### PR DESCRIPTION
**Pull request by mostermas**
Adding info for BEP20 token 'Vodka Token'.

PR created by <a href="https://assets.trustwallet.com">TW Assets Management</a>

### CODE REVIEW

**Comment by mostermas** [comment]
https://github.com/trustwallet/assets/pull/17107 Fee paid

**Comment by mostermas** [comment]
I try to create with
https://community.trustwallet.com/t/how-to-submit-a-token-logo/3863 this
and with this one  https://assets.trustwallet.com/ and every time it add
LLG logo , to PR, maybe I beed do it with new github acc?


вс, 9 янв. 2022 г. в 00:44, merge-fee-bot[bot] ***@***.***>:

**Comment by mostermas** [comment]
fee paid https://github.com/trustwallet/assets/pull/17107


вс, 9 янв. 2022 г. в 00:47, MAD MAX ***@***.***>:

**Comment by mostermas** [comment]
???

вс, 9 янв. 2022 г. в 00:48, MAD MAX ***@***.***>:

**Comment by cryptomanz** [comment]
You need to delete old  fork and create new PR, with only Vodka Token. Make sure to mention this PR, so that we can see that fee has been paid already here.

**Pull request closed without merging**
