### PR TITLE
Add Pink BNB (BEP20)

### PR DESCRIPTION
**Pull request by johnpnb**
Adding info for BEP20 token 'Pink BNB'.

PR created by <a href="https://assets.trustwallet.com">TW Assets Management</a>

### CODE REVIEW

**Comment by Cryptocool1** [comment]
• What is the purpose of this token? How will it benefit Trust Wallet users?
 • How is the token being distributed? Are you conducting an airdrop?
 • Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?
 • Is the token listed on a centralized/decentralized exchange?
 • Is a Smart Contract audit completed? Where can we find this information?

**Comment by johnpnb** [comment]
+ PNB is a Prediction AI, developed to predict coins and market movements
+ Our airdrop distribution has not started, I will start end of June
+ No
+ MEXC and Pancakeswap
+ Yes it's audited by FairyProof https://www.fairyproof.com/report/Pink%20BNB

**Comment by Cryptocool1** [comment]
Why do you have “BNB» in your token name?

**Comment by johnpnb** [comment]
Pink BRAIN NEURONS BASED AI is our full name 
Also our symbol is PNB

**Pull request merged**
