### PR TITLE
Network Token

### PR DESCRIPTION
**Pull request by CryptoCreater**
Network token info and logo adding

### CODE REVIEW

**Comment by Iamdeadlyz** [comment]
As per our policy, brand new tokens are not included. There is a minimum requirement of 2500 holder addresses and 5000 transactions (airdropped tokens excluded) in order to filter out scam tokens. See the criteria at (mentioned in the first message by the bot): https://community.trustwallet.com/t/how-to-submit-a-token-logo/3863#how-to-get-approved

This token has below-limit usage yet. This pull request will be put on hold. Please come back to us when all criteria are met.
https://etherscan.io/token/0xA686586E12006eD90FB4c3A9748E4CBb42490051

**Comment by CryptoCreater** [comment]
Hi!
And what about payment of 1000 TWT?

среда, 2 декабря 2020 г., 14:12 +0700 от notifications@github.com  <notifications@github.com>:

**Comment by Iamdeadlyz** [comment]
> And what about payment of 1000 TWT?

Your payment will still be considered. Just comment here to let us know.

**Comment by CryptoCreater** [comment]
Hi!
We deployed new contract for this token.
How we can update token info?

**Comment by CryptoCreater** [comment]
Or how we can transfer payed status to new pull request?

**Comment by catenocrypt** [comment]
Option A:  update files in this PR

Option B:  create new PR, mention the number of this PR, payment can be reconsidered.  Maybe this is cleaner.

But bigger problem is that the token circulation is far from our limit -- 2500 holder addresses and 5000 transactions.  Any update on that?

**Pull request closed without merging**
