### PR TITLE
Add HAPPY (BEP20) logo and info

### PR DESCRIPTION
**Pull request by Enry679**
Hi Trust Wallet Team,
could you please add our logo:

website: https://happyfans.club/
email: business@happyfans.club
telegram: https://t.me/happyfanstoken

### CODE REVIEW

**Comment by Enry679** [comment]
How can i fix this issue:
❌ The links field cannot be empty

what link do you refer?

**Comment by Cryptocool1** [comment]
see the example here: https://developer.trustwallet.com/assets/repository_details

**Comment by Enry679** [comment]
> see the example here: https://developer.trustwallet.com/assets/repository_details

I updated the info.json with links field as requested, we almost reached the 5k addresses (4987 now).
When we reach it we can proceed with the transaction of TWT to complete the adding of our logo?

**Comment by Enry679** [comment]
How can i completely revert this file blockchains/smartchain/info/info.json?

**Comment by Enry679** [comment]
1) The token will be the economical base of our platform, the users should use that to subscribe to the channels or unlock the contents of their favorites content creators (and viceversa, the content creators receive the token as rewards for their work).
2) We already performed an airdrop through CMC, we're releasing the staking too.
3) IDO with presale as per tokenomics in our litepaper (https://happyfans.club/wp-content/uploads/2021/09/litepaper.pdf)
4) Not yet, we are in the process of being added.
5) Yes, as soon as the auditor has finished you can find that in our github.

**Comment by cryptomanz** [comment]
Please send me your audit in PDF format.

**Comment by Enry679** [comment]
Hi @cryptomanz! we've change the our logo after rebranding.. how can we change it on your platform?
Ty for your support!

**Comment by Cryptocool1** [comment]
Hello, you should create PR with new logo. The fee is required for updating

**Comment by Enry679** [comment]
@Cryptocool1 thanks for info! how much is the fee? same of original pr?

**Pull request merged**
