### PR TITLE
0x4B4701f3f827E1331fb22FF8e2BEaC24b17Eb055

### PR DESCRIPTION
**Pull request by Mshuu**

### CODE REVIEW

**Comment by Mshuu** [comment]
Paid!

**Comment by catenocrypt** [comment]
As per our policy, brand new tokens are not included, there is a minimum requirement of 100 holder addresses and 500 transactions, in order to filter out scam tokens.
See https://community.trustwallet.com/t/how-to-submit-a-token-logo/3863#how-to-get-approved
This token has minimal usage (2 addrs).  Closing now, let's reopen once all criteria is met.
https://etherscan.io/token/0x4B4701f3f827E1331fb22FF8e2BEaC24b17Eb055

**Comment by Mshuu** [comment]
Please reopen as we have distributed the tokens.

**Comment by catenocrypt** [comment]
Token check OK

**Pull request merged**
