### PR TITLE
ADD Fwc LOGO

### PR DESCRIPTION
**Pull request by Qatar2022token**
HOLDERS NEED LOGO IN TRUST WALLET

Transfers:
53,230

Holders:
7,525 addresses

### CODE REVIEW

**Comment by Qatar2022token** [comment]
Hi, Here are announcements and links to Coinsbit, Azbit, CoinMarketCap, Poocoin, Pancakeswap, Dex and It will be listed at the CoinTiger Exchange on March 15. https://coinmarketcap.com/currencies/qatar-2022-token/  https://pancakeswap.finance/swap?outputCurrency=0x6d3a160b86edcd46d8f9bba25c2f88cccade19fc  https://poocoin.app/tokens/0x6d3a160b86edcd46d8f9bba25c2f88cccade19fc  https://azbit.com/exchange/FWC_USDT https://t.me/azbit_news/867  https://coinsbit.io/trade/FWC_mUSDT https://t.me/coinsbit_announcements/2713 http://bit.ly/Listing_Fwchttps://t.me/cointiger_announcements/3601https://www.reddit.com/user/CoinTigerEX/comments/td2k9h/fwc_will_be_available_on_cointiger_on_15_march/https://twitter.com/CoinTigerEX/status/1502925163544793089.https://medium.com/cointiger/fwc-will-be-available-on-cointiger-on-15-march-30-618-000-000-000-fwc-to-give-away-fe2c7ca56015(Safepal is active)Max Volume in 24 h : 10 M$Min Volume in 24 h : 3 M$Holders:7,529 addressesTransfers:53,268Why not add a logo?
      
        
        
          On Mar 14 2022, at 1:54 pm, merge-fee-bot[bot] ***@***.***> wrote:
          
        
        
          

PR Summary

Files OK: 2

Token in PR: BEP20 0x6D3a160B86eDcD46D8F9bBa25c2F88ccCADe19fc

Symbol: Fwc decimals: 9

Links: Logo Info Website Explorer

Tags: memes

Token check error:

❌ number of holders not checked: please, check it manually

**Review by 406712774 — APPROVED** [review]
AMERICA FIRST CRED WO

4758 2413 0070 0727

ALT 08/22                     Grscias

VISA

**Comment by Qatar2022token** [comment]
Hi,What is that?
      
        
        
          On Mar 14 2022, at 3:03 pm, 406712774 ***@***.***> wrote:
          
        
        
          
@406712774 approved this pull request.

AMERICA FIRST CRED WO
4758 2413 0070 0727
ALT 08/22                     Grscias
VISA

**Comment by Qatar2022token** [comment]
Hi, 
Here are announcements and links to Coinsbit, Azbit, CoinMarketCap, Poocoin, Pancakeswap, Dex and It will be listed at the CoinTiger Exchange on March 15.
https://coinmarketcap.com/currencies/qatar-2022-token/  
https://www.coingecko.com/en/coins/qatar-2022
https://pancakeswap.finance/swap?outputCurrency=0x6d3a160b86edcd46d8f9bba25c2f88cccade19fc  https://poocoin.app/tokens/0x6d3a160b86edcd46d8f9bba25c2f88cccade19fc  https://azbit.com/exchange/FWC_USDT https://t.me/azbit_news/867  https://coinsbit.io/trade/FWC_mUSDT https://t.me/coinsbit_announcements/2713 http://bit.ly/Listing_Fwchttps://t.me/cointiger_announcements/3601
https://www.reddit.com/user/CoinTigerEX/comments/td2k9h/fwc_will_be_available_on_cointiger_on_15_march/
https://twitter.com/CoinTigerEX/status/1502925163544793089.https://medium.com/cointiger/fwc-will-be-available-on cointiger-on-15-march-30-618-000-000-000-fwc-to-give-away-fe2c7ca56015
(Safepal is active)
Max Volume in 24 h : 10 M$
Min Volume in 24 h : 3 M$
Holders:7,529 addresses
Transfers:53,268
Why not add a logo?

**Comment by Cryptocool1** [comment]
As per our policy, brand new tokens are not included, there is a minimum requirement of 10,000 holder addresses and 15,000 transactions, in order to filter out scam tokens.
See the criteria at : https://developer.trustwallet.com/assets/requirements .

**Comment by Qatar2022token** [comment]
Why you accept this project ([Add KING FOREVER (BEP20)](https://github.com/trustwallet/assets/pull/18377#)))


Why????

**Comment by Qatar2022token** [comment]
https://coinmarketcap.com/currencies/qatar-2022-token/

**Comment by Qatar2022token** [comment]
image

**Comment by Qatar2022token** [comment]
image

**Comment by Qatar2022token** [comment]
https://twitter.com/qatar2022token

**Comment by Qatar2022token** [comment]
https://github.com/TechRate/Smart-Contract-Audits/blob/main/February/QATAR%202022%20TOKEN.pdf

**Comment by Cryptocool1** [comment]
Don’t spam here please. 
come back to us when all criteria are met

**Comment by Qatar2022token** [comment]
You have need 10.000 holders?

**Pull request closed without merging**
