### PR TITLE
Update DFF token logo

### PR DESCRIPTION
**Pull request by Shyamthakur33**

### CODE REVIEW

**Comment by Iamdeadlyz** [comment]
Please provide more details about this project.
https://community.trustwallet.com/t/how-to-submit-a-token-logo/3863#how-to-get-approved
You can follow this format when adding an info.json file:
```
{
   “name”:“Bitcoin”,
   “website”:“https://bitcoin.org”,
   “source_code”:“https://github.com/bitcoin”,
   “white_paper”:“https://bitcoin.org/bitcoin.pdf”,
   “short_description”:“Bitcoin is a cryptocurrency and worldwide payment system.“,
   “explorer”:“https://blockchain.info”,
   “research”:“https://research.binance.com/en/projects/bitcoin”
}

**Comment by Shyamthakur33** [comment]
> Please provide more details about this project.
> https://community.trustwallet.com/t/how-to-submit-a-token-logo/3863#how-to-get-approved
> You can follow this format when adding an info.json file:
> 
> ```
> {
>    “name”:“Bitcoin”,
>    “website”:“https://bitcoin.org”,
>    “source_code”:“https://github.com/bitcoin”,
>    “white_paper”:“https://bitcoin.org/bitcoin.pdf”,
>    “short_description”:“Bitcoin is a cryptocurrency and worldwide payment system.“,
>    “explorer”:“https://blockchain.info”,
>    “research”:“https://research.binance.com/en/projects/bitcoin”
> }
> ```

we already have attached json file with all info, please recheck again

**Comment by Shyamthakur33** [comment]
@Iamdeadlyz you there

**Comment by Iamdeadlyz** [comment]
> @Iamdeadlyz you there

Hi, yup. To merge, please proceed with the payment as stated by the merge-fee-bot.

**Comment by Shyamthakur33** [comment]
> > @Iamdeadlyz you there
> 
> Hi, yup. To merge, please proceed with the payment as stated by the merge-fee-bot.

ok, doing now

**Comment by Shyamthakur33** [comment]
payment done

**Pull request merged**
