### PR TITLE
Request to add "ICHI" and "oneETH" Tokens

### PR DESCRIPTION
**Pull request by LewysVillanueva**
Two first tokens from project http://ichi.farm

### CODE REVIEW

**Comment by Iamdeadlyz** [comment]
As per our policy, brand new tokens are not included. There is a minimum requirement of 2500 holder addresses and 5000 transactions (airdropped tokens excluded) in order to filter out scam tokens. See the criteria at (mentioned in the first message by the bot): https://community.trustwallet.com/t/how-to-submit-a-token-logo/3863#how-to-get-approved

This token has below-limit usage yet. This pull request will be put on hold. Please come back to us when all criteria are met.
https://etherscan.io/token/0x6fcBBB527Fb2954BED2B224A5BB7c23C5AeEb6E1 (48, 960)
https://etherscan.io/token/0x903bEF1736CDdf2A537176cf3C64579C3867A881 (80, 1996)

**Comment by LewysVillanueva** [comment]
Thank you Ian @Iamdeadlyz - I did notice the 2500 account requirement but had been informed by a third party that was mostly to deter scams, which we are not. I will return when we beat that number, but I hope you will consider pushing us before then. Happy to provide any additional information to prove the legitimacy of project. Please note we also have $11mm in the contracts. Thank you, Lewys.

**Comment by LewysVillanueva** [comment]
The ichi.farm contracts received over $15mm in the first 24 hours.
The ichi.farm exchange is seeing over $500k in daily volume. 
We have seen support from CREAM, Frax, and Curv.finance.
Two pools are active for farming, and the third goes live tonight (Nov17)

**Comment by LewysVillanueva** [comment]
We are now on EtherScan: https://etherscan.io/token/0x903bEF1736CDdf2A537176cf3C64579C3867A881
We are now on CoinGecko: https://www.coingecko.com/en/coins/ichi-farm

**Comment by LewysVillanueva** [comment]
Ichi is now on Nomics https://nomics.com/assets/ichi-ichifarm

**Comment by LewysVillanueva** [comment]
We have now surpassed the transfer requirement (5,000) - we have 11,422 (2,050+9,372)..

**Comment by catenocrypt** [comment]
image

**Comment by LewysVillanueva** [comment]
Sorry, I was thinking this was project wide. We have potentially 11 new coins to list- $ICHI, $oneETH, $oneBTC, $oneLINK, $oneMKR, $oneHBAR, and 5 community voted stablecoins. 

You do see $ICHI looks ok? 
Holders: 158 addresses (2,500 minimum not passed)
Transfers: 11,372 (5,000 minimum passed)

Hope you do not mind the updates. If you prefer I do not update thread until we surpass holder requirement, let me know. Community will continue to push marketing. Thank you.

**Pull request merged**
