### PR TITLE
Add Wenlambo (BEP20)

### PR DESCRIPTION
**Pull request by Wenlambo**
Adding info for BEP20 token 'Wenlambo'.

PR created by <a href="https://assets.trustwallet.com">TW Assets Management</a>

### CODE REVIEW

**Comment by Cryptocool1** [comment]
Stop creating the same PR please.

**Comment by Wenlambo** [comment]
> Stop creating the same PR please.

sorry i didn't mean to mess up, please let me know what should i do next. thanks in advance for helping me

**Comment by Wenlambo** [comment]
Hi there can i have some help on how to proceed further?

**Comment by Cryptocool1** [comment]
files are duplicated. PR should include only 2 files:

**Comment by Wenlambo** [comment]
> files are duplicated. PR should include only 2 files:

I have tried to delete the other files but i am not able to.

**Comment by Wenlambo** [comment]
any update on how to proceed next?

**Comment by Wenlambo** [comment]
> Stop creating the same PR please.

@Cryptocool1  - What do you  need us to do please? 

Thank you in advance.

WenLambo

**Comment by Wenlambo** [comment]
> 21ffe04256c6d08c3a2251/logo.png. Please revert it.


we have reverted this and added a new file. Please sort

**Comment by Cryptocool1** [comment]
Hello,
Your image is too large. max 100 kB

**Comment by Wenlambo** [comment]
I have updated this please check

**Comment by Wenlambo** [comment]
Hi, Logo doesn't appear in TrustWallet even with a reinstall? and install on fresh device

**Comment by catenocrypt** [comment]
I've just checked, it appeared in my Trust Wallet.

**Comment by Wenlambo** [comment]
Hello, our price isn't showing but we are on CoinMarketCap?

**Comment by Wenlambo** [comment]
@Cryptocool1 our price isn't showing in TrustWallet?

**Comment by Wenlambo** [comment]
@catenocrypt  @zachzwei  - Please can someone help here? our price isn't showing

**Pull request merged**
