### PR TITLE
[Internal] Generate info.json for each token where it was missing

### PR DESCRIPTION
**Pull request by optout21**
Prerequisite: #5461
Issue #5419

### CODE REVIEW

**Comment by catenocrypt** [comment]
List of assets affected (5627) attached.
[info_missing_3.zip](https://github.com/trustwallet/assets/files/5898733/info_missing_3.zip)

**Comment by catenocrypt** [comment]
Checks fail as there are a few files with empty explorer; has to be completed.

**Comment by catenocrypt** [comment]
A few other ideas also came up, will need some more work

**Review by vikmeup — APPROVED** [review]

**Comment by catenocrypt** [comment]
This is Ready to merge; but waiting first for prerequisite: #5461 .

**Review by vikmeup — APPROVED** [review]
overall looks good.

Can you make sure there is no duplicated data? 

Can you set default `status: "active"` ?

**Pull request merged**
