### PR TITLE
Add bitvalley logo on Trustwallet

### PR DESCRIPTION
**Pull request by BitvalleyEcosystem**

### CODE REVIEW

**Comment by BitvalleyEcosystem** [comment]
Payment done

**Comment by cryptomanz** [comment]
As per our policy, brand new tokens are not included, there is a minimum requirement of 10,000 holder addresses and 15,000 transactions, in order to filter out scam tokens.
See the criteria at : https://developer.trustwallet.com/assets/requirements .

**Comment by cryptomanz** [comment]
Please come back to us when all criteria are met.
When creating a new PR make sure to mention this PR, so that we can see that fee has been paid already here.

**Comment by BitvalleyEcosystem** [comment]
Hello so as far as legitimacy goes you can check out our project and if possible judge by that not by the holders we launched more than 3 months ago, verified almost everywhere, listed on Coinmarketcap and Coingecko, logo and info on bscscan. On the listing policy it says that the number of holders is subject for review based on the project , so please review and check out project legitimacy. Thank you

**Comment by BitvalleyEcosystem** [comment]
> Please come back to us when all criteria are met. When creating a new PR make sure to mention this PR, so that we can see that fee has been paid already here.

Hello so as far as legitimacy goes you can check out our project and if possible judge by that not by the holders we launched more than 3 months ago, verified almost everywhere, listed on Coinmarketcap and Coingecko, logo and info on bscscan. On the listing policy it says that the number of holders is subject for review based on the project , so please review and check out project legitimacy. Thank you

**Pull request closed without merging**
