### PR TITLE
Add files via upload

### PR DESCRIPTION
**Pull request by bodatoken**
Files uploaded for BODAV2 logo and json to be added to Trust wallet. Thank you kindly.

### CODE REVIEW

**Comment by Cryptocool1** [comment]
can you please add links to your PR?
example:https://developer.trustwallet.com/assets/repository_details

**Comment by bodatoken** [comment]
> • What is the purpose of this token? How will it benefit Trust Wallet users? 
BODAV2 is a token for the crypto investor who wants to be rewarded for their long-term investing. BODAV2 hodlers can earn a passive income from stablecoin BUSD rewards just for holding their tokens. A reward fee of 6% from every buy and 13% from every sell transaction is converted into BUSD and payout as a dividend reward. Yield Farming will add more utility to the token and provide additional benefits to holders. NFT platform is in development with the first NFT being made already. A token minter and token locker, a long with a token swap, will also be added to the token utility. BODAV2 will benefit trust wallet users by allowing them to earn BUSD as passive income.
• How is the token being distributed? Are you conducting an airdrop? 
No airdrop. Token was launched on Pancakeswap. 
• Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?
No presale.
 • Is the token listed on a centralized/decentralized exchange? 
 BODAV2 is available on Pancakeswap, MDEX and FEGex.
 • Is a Smart Contract audit completed? Where can we find this information?
BODAV2 is currently being audited by Certik and the final audit should be released this week.

**Comment by bodatoken** [comment]
> **PR Summary** Files OK, 2Files in PR: 2 Token in PR: BEP20 0xdc847755343C3A2B94d6aFC0aAE57651E1b14064 Could not retrieve info file; bodatoken/assets-1/master 0xdc847755343C3A2B94d6aFC0aAE57651E1b14064, SyntaxError: Unexpected string in JSON at position 443

Just hoping everything is correct? I followed the example on the repository document and cannot seem to figure out why this error message is appearing?

**Comment by Cryptocool1** [comment]
awaiting for full smart contract audit, on hold for now

**Comment by Cryptocool1** [comment]
Please come back to us when all criteria are met.
When creating a new PR make sure to mention this PR, so that we can see that fee has been paid already here.

**Comment by bodatoken** [comment]
> Please come back to us when all criteria are met. When creating a new PR make sure to mention this PR, so that we can see that fee has been paid already here.

Hello, we have had an audit complete and made a new pull request. thank you.

**Comment by cryptomanz** [comment]
Please send me audit.

**Pull request closed without merging**
