### PR TITLE
Adding ETG Finance ETGF

### PR DESCRIPTION
**Pull request by EthereumGoldETG**
Add ETG Finance token to trustwallet ETGF .

### CODE REVIEW

**Comment by catenocrypt** [comment]
As per our policy, brand new tokens are not included, there is a minimum requirement of 500 holder addresses and 1000 transactions, in order to filter out scam tokens.
See the criteria at (mentioned in the first message by the bot): https://community.trustwallet.com/t/how-to-submit-a-token-logo/3863#how-to-get-approved
This token has low usage yet (140). Rejecting PR for now. Please come back to us when all criteria are met.

https://etherscan.io/token/0x74603e780545d02C4257E7D2BE19c74dE7BE1952

**Comment by EthereumGoldETG** [comment]
Hi thank you for reply , can we pay with Eth please ?

**Comment by catenocrypt** [comment]
No, only TWT (TWT-BEP2), and BNB (BNB-BEP2) are supported.

**Comment by EthereumGoldETG** [comment]
Payment sent ✅ :

28AA5E460F81F684DF58E61363C4BDC4228D2746A38B69B8503E7CC226B5C9AD

**Comment by catenocrypt** [comment]
Oh, you have not noticed that this PR was already closed!

Payment has been refunded.  7D323979CB4AE10C070C220F26C1172E5964A4C9E9500F93603179C21DE87876

**Comment by EthereumGoldETG** [comment]
So ? Any news PR ?

**Comment by catenocrypt** [comment]
No, please read above comment
https://github.com/trustwallet/assets/pull/4523#issuecomment-712916790

**Comment by EthereumGoldETG** [comment]
Aha so we need 500 holders ok no problem .
Thank you
Regards.

**Comment by EthereumGoldETG** [comment]
Hi Trustwallet/Assets now we have +500 Holders can we integrate ETGF ?

**Pull request closed without merging**
