### PR TITLE
Include iBBT Utility Token to the Trustwallet

### PR DESCRIPTION
**Pull request by geopayme**

### CODE REVIEW

**Comment by geopayme** [comment]
Payment was completed for 0.5 BNB Ga839

**Comment by kolya182** [comment]
Added here https://github.com/trustwallet/assets/commit/8fa2a4fde1b58f3587347928dc089db3720d42af

**Comment by kolya182** [comment]
@geopayme Could you explains the reason adding logo to contract that almost year old and has no transactions ?. Curious to know.

**Comment by kolya182** [comment]
https://etherscan.io/address/0x76ace4e080c49f04a6c12756c036d3627f6b1e69

**Comment by geopayme** [comment]
Thank you for the reply, as the name suggests, these tokens are designed
for a purpose and to be give away for FREE to anyone who likes to own them, I
would be happy to share the technical paper you can read the paper on
github or folow the link to Github from this link https://igcredits.com

In order to be able to give away all these CREE Tokens, individuals must
have a wallet, and I found the Trustwallet  to be the perfect candidate.

Thank you



Geopay.me Inc.

*"don't need to know everything, I just need to know where to find it."**A.
Einstein.*
If you need to reach your people really fast, there's no better way to do
it than with "mobile".

Mobile is direct, accurate, and personal.

This email may contain confidential and/or privileged information. If you
are not the intended recipient (or have received this email by mistake),
please notify the sender immediately and destroy this email. Any
unauthorized copying, disclosure or distribution of the material in this
email is strictly prohibited.

Email transmission security and error-free status cannot be guaranteed as
information could be intercepted, corrupted, destroyed, delayed,
incomplete, or contain viruses. The sender, therefore, does not accept
liability for any errors or omissions in the contents of this message which
may arise as a result of email transmission.

**Pull request closed without merging**
