### PR TITLE
Add MRAT LOGO

### PR DESCRIPTION
**Pull request by alansoliditydev**
MoonRat is a community driven, fair launched DeFi project built on Binance Smart Chain #BSC. Three functions occur during each trade: Reflection, LP Acquisition, & Burn.

MoonRat brings the most revolutionary mechanism to BSC ecosystem: Earn $BNB just by holding $MRAT token

OFFICIAL TELEGRAM : @MoonRatFinance
OFFICIAL TELEGRAM ANNOUNCEMENTS : @moonrat_finance
OFFICIAL TWITTER : @MoonRatFinance

### CODE REVIEW

**Comment by TranDinhKhang** [comment]
@zachzwei @catenocrypt @Iamdeadlyz hello, please check this pr. thanks for supporting ;)

**Comment by TranDinhKhang** [comment]
@catenocrypt @catenocrypt any updates on this fellas? I've seen many project get listed within a day

**Comment by TranDinhKhang** [comment]
@catenocrypt @zachzwei hello, please review this sirs. We paid the fee also all pre-checks were successful. more than 24 hours now.

**Comment by TranDinhKhang** [comment]
Total Supply:
1,000,000,000,000,000 MRAT 

Holders:
15,055 addresses

Transfers:
49,765

https://bscscan.com/token/0x6D949f9297A522c0f97C232CC209a67Bd7CfA471

@catenocrypt @catenocrypt @zachzwei you can check this lol

**Comment by AlanMoonRat** [comment]
@catenocrypt @zachzwei hello, dont know why MRAT still didnt get approval, but if there are some issues you guys just tell me. 

Fee is paid, all checks done, requirements exceed.

Our users cant wait :(

**Comment by TranDinhKhang** [comment]
@catenocrypt @catenocrypt @zachzwei hello, dont know why it took so long to get approved but if there are issues just tell me.

Fee was paid. Requirements exceeded. Pre-checks passed.

Our users cant wait :(

**Pull request merged**
