### PR TITLE
Add Coinhub (BEP20)

### PR DESCRIPTION
**Pull request by bk3656**
Adding info for BEP20 token 'Coinhub'.

PR created by <a href="https://assets.trustwallet.com">TW Assets Management</a>

### CODE REVIEW

**Comment by bk3656** [comment]
Hello
To whom it is related,


We have paid the total price for Logo and price displaying on Trustwallet.
The transaction is clear:

Txid:

A51DB20BC282FCBB2987D1600BDAC9E34524419A3FD162306040CA3578B054E8

bnb1tqq9llyr3dyjd559dha6z5r5etk3qfwk07m098

**Comment by Cryptocool1** [comment]
• What is the purpose of this token? How will it benefit Trust Wallet users?
 • How is the token being distributed? Are you conducting an airdrop?
 • Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?
 • Is the token listed on a centralized/decentralized exchange?
 • Is a Smart Contract audit completed? Where can we find this information?

**Comment by bk3656** [comment]
Kind reminder,

Coinhub team has completed a ticket some months ago and has paid the
definite amount for price and logo displaying.

This is the previous ticket link:

https://github.com/trustwallet/assets/pull/22943#issuecomment-1304637991


Please check carefully. We paid and there are not any defects now to reject
our ticket.

We are waiting for your positive response.

**Comment by Cryptocool1** [comment]
I didn’t reject you. I’m asking the questions.

**Comment by bk3656** [comment]
Coinhub token, CHB, is the utility token on Coinhub platform. Users can pay CHB as fee to withdraw chb when there is no bsc on platform. CHB is staking token of CoinHub.

Project has started with pre-sale. No airdrop.

Yes. It had ICO.

Yes it is listed on Coinsbit, Dsdaq and pancakeSwap.

Yes it is audited. Link: 

https://twitter.com/DessertSwap/status/1657761847267688449

**Comment by bk3656** [comment]
We will appreciate if you guide us how to check number of holder's manually? 

And we paid seven months ago. Is it accepted?

**Comment by Cryptocool1** [comment]
Hello, you can now see your logo in Trust wallet

**Comment by bk3656** [comment]
We are happy that you are a kind support. We appreciate you. But there is a problem here. We paid for listing not just displaying the logo. We appreciate for displaying the logo, but necessity is listing the token formally. Thanks in advance for providing us a related response.

**Comment by bk3656** [comment]
Sorry, I mean formally

**Comment by Cryptocool1** [comment]
You got listed

**Comment by bk3656** [comment]
Thanks a million for your kind support.

**Comment by bk3656** [comment]
My last question. Why not the price and logo and formal listing on our
wallet? Should we do sth as a refreshing action?

**Comment by bk3656** [comment]
Why are there two of CHB? The top one is new. The one in the bottom is the
old one. Should we do something or TW will delete the old one?

**Pull request merged**
