### PR TITLE
Add Token Logo: Shiro (ERC20)

### PR DESCRIPTION
**Pull request by logosubmit**
Add token logo for Shiro (ERC20). 12,500 holders.

### CODE REVIEW

**Comment by Cryptocool1** [comment]
• What is the purpose of this token? How will it benefit Trust Wallet users?
 • How is the token being distributed? Are you conducting an airdrop?
 • Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?
 • Is the token listed on a centralized/decentralized exchange?
 • Is a Smart Contract audit completed? Where can we find this information?

**Comment by Cryptocool1** [comment]
• Is a Smart Contract audit completed? Where can we find this information?

**Comment by MrLightspeed** [comment]
@logosubmit This submission is missing critical links such as coinmarketcap and coingecko. I had made a proper submission based on the team's request.

**Comment by Cryptocool1** [comment]
Hello, We require an audit from reputable companies. (Certik, Techrate, Hacken).
The request will be closed until further notice.

To know more about the token approval guidelines, please check this article: [How to Submit Token Logo](https://developer.trustwallet.com/listing-new-assets/requirements).

Feel free to re-open pull request once you meet those requirements.

**Pull request closed without merging**
