### PR TITLE
Add Jesus Coin (BEP20)

### PR DESCRIPTION
**Pull request by jesuscoinbsc**
Adding info for BEP20 token 'Jesus Coin'.

PR created by <a href="https://assets.trustwallet.com">TW Assets Management</a>

### CODE REVIEW

**Comment by jesuscoinbsc** [comment]
Solid Proof Contract Audit: https://app.solidproof.io/projects/jesus-coin

**Comment by jesuscoinbsc** [comment]
CoinMarketCap: https://coinmarketcap.com/currencies/jesus-coin-bsc/
CoinGecko: https://www.coingecko.com/en/coins/jesuscoin

**Comment by jesuscoinbsc** [comment]
As per check on other submission, question asked:

• What is the purpose of this token? How will it benefit Trust Wallet users?
Jesus coin is a meme token with 3 defi app that can perform ai drawing, ai chat gpt, and ai scanning of contract risks. Most of our users are using Trust Wallet and being included in Trust Wallet will help build our brand and also provide them with price and website details.

• How is the token being distributed? Are you conducting an airdrop?
Token is trade on PancakeSwap. We do not conduct airdrop.

• Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?
No ICO or Presale.

• Is the token listed on a centralized/decentralized exchange?
Listed on PancakeSwap.

Question on achieving holders:
Jesus Coin was listed on CoinMarketCap, CoinGecko. This give us a lot of exposure, another source of our holders is from DEXTools and AVE Trending. Both of the platform, we are trended almost daily, on certain hours when volume or transactions are higher.

Thank you.

**Comment by Dickieleef** [comment]
Here's one my stolen and hacked accounts

**Comment by Cryptocool1** [comment]
How did you get 10k holders within 1 week without airdrop?

**Comment by jesuscoinbsc** [comment]
> How did you get 10k holders within 1 week without airdrop?

 Jesus Coin was listed on CoinMarketCap, CoinGecko. This give us a lot of exposure, another source of our holders is from DEXTools and AVE Trending. Both of the platform, we are trended almost daily, on certain hours when volume or transactions are higher.
 
 We also did Twitter Marketing, we were lucky to go viral and trending on Dextools and AVE concurrently.

**Comment by Dickieleef** [comment]
This is a stolen coin... It's actually my asset that was one of a few hacked

**Comment by Dickieleef** [comment]
I need this coin removed till I change it

**Comment by Abeanna** [comment]
I approved

**Comment by Dickieleef** [comment]
Why is the robot deleting my comment that is my coin and I just read on it on the fee

**Comment by Dickieleef** [comment]
> How did you get 10k holders within 1 week without airdrop?

I tell you how he done it he just jumped in there and took and put his name on something and it's not his that's mine I got proof of work on him

**Pull request merged**
