### PR TITLE
Update TOKEN SDC  refer #17487

### PR DESCRIPTION
**Pull request by somdejcoin999**
We have not reviewed it because it takes a long time and is very costly. Can we continue in the Trust because the cost has already been paid

### CODE REVIEW

**Comment by Cryptocool1** [comment]
• Is a Smart Contract audit completed? Where can we find this information?

**Comment by somdejcoin999** [comment]
We do not send a review.


> • Is a Smart Contract audit completed? Where can we find this information?

We do not send a review.

**Comment by somdejcoin999** [comment]
> We do not send a review.
> 
> > • Is a Smart Contract audit completed? Where can we find this information?
> 
> We do not send a review.

**Comment by somdejcoin999** [comment]
> • Is a Smart Contract audit completed? Where can we find this information?

We do not send a review.

**Comment by Cryptocool1** [comment]
awaiting for smart contract audit, on hold for now

**Review by chefgsaroar — APPROVED** [review]

**Comment by cryptomanz** [comment]
Please come back to us when all criteria are met.
When creating a new PR make sure to mention this PR, so that we can see that fee has been paid already here.

**Pull request closed without merging**
