### PR TITLE
Add HMNG logo and info

### PR DESCRIPTION
**Pull request by faisalx73**
hey trust wallet team,
could you please add our logo,

website: https://www.hummingbirdbsc.org/
email: info@hummingbirdbsc.com
telegram: https://t.me/hummingbirdbsc

### CODE REVIEW

**Comment by faisalx73** [comment]
> Token check: Errors found!
> 
> Found 1 added/changed token(s) among the PR files (BEP20: 0x14357D294fBabbE0fbF59503370c772d563b35b6 )
> 
> ?

how can i fix this error

**Comment by catenocrypt** [comment]
The website mentioned cannot be opened:
https://www.hummingbirdbsc.com/
Please fix/explain

**Comment by faisalx73** [comment]
> The website mentioned cannot be opened:
> https://www.hummingbirdbsc.com/
> Please fix/explain

ohh sorry my bad its end with .org not .com
https://www.hummingbirdbsc.org/

should we pay now 
Please pay 250 TWT with the memo 6582 to the address bnb1tqq9llyr3dyjd559dha6z5r5etk3qfwk07m098

**Comment by catenocrypt** [comment]
JSON file fixed.
Submission looks OK; awaiting fee payment.

**Comment by Cryptocool1** [comment]
Hello, 
can you change your symbol "Hmng" to "HMNG"

**Comment by faisalx73** [comment]
@catenocrypt i have a question, when we will be able to view the price in "dollor" after CMC or CG listing?
is it will be updated automatically , or we need to create a new requset ? thank you

**Comment by catenocrypt** [comment]
Price info should appear automatically, once it is available on CMC or CG.

**Comment by faisalx73** [comment]
hey , we got listed on CMC & CG , and the price is still not shown in trustwallet , 
lot of people been asking for it , its been 3 days now , could you please help us ..

**Comment by faisalx73** [comment]
@catenocrypt hey , we got listed on CMC & CG , and the price is still not shown in trustwallet ,
lot of people been asking for it , its been 3 days now , could you please help us ..

**Pull request merged**
