### PR TITLE
CVD-19 BSC token logo request add

### PR DESCRIPTION
**Pull request by jimmyjah369**

### CODE REVIEW

**Comment by Cryptocool1** [comment]
hi there,
can you answer some questions?
• What is the purpose of this token? How will it benefit Trust Wallet users?
 • How is the token being distributed? Are you conducting an airdrop?
 • Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?
 • Is the token listed on a centralized/decentralized exchange?
 • Is a Smart Contract audit completed? Where can we find this information?

**Comment by jimmyjah369** [comment]
Hello,

✅The purpose of CVD19 is to benefit holders by giving them 4% in each
transaction, they will receive this bonuses if they hold CVD19 in Trust
wallet automatically, Also CVD19 is deflation token

✅CVD19 is distributed by auto claim in which users can claim 100,000 CVD19
and 50,000 CVD19 as referral bonuses, also we have Manual Airdrop
distribution to some users

✅Since CVD19 is community token users claim CVD19 FREE and Through airdrop,
also we plan to conduct little pre sale in August to help on Liquidity pool
in pancakeswap and centralized exchange fee, we will list on hotbit and
probot also bitmart after pre sale end on august

✅CVD19 is not listed in any exchange yet, but according to our roadmap we
will list on pancake swap on August following with other centralized
exchange after Claim & Airdrop end (now we work on building great community
by airdrop & claim)

✅We are also working on contract audit before we go to exchange listing

🙏🏼Thank you Trust wallet team, we really appreciate your response, you
can read more bout us in our website www.nocovid19.finance

**Comment by jimmyjah369** [comment]
@Cryptocool1

**Comment by cryptomanz** [comment]
hi there,
token will be on hold . awaiting for  smart contract audit

**Comment by jimmyjah369** [comment]
We work on it 🤝

**Comment by jimmyjah369** [comment]
Hello,
I would like to know, is there recommended company you accept audits? I ask
this because we have requested audit and we wait for updates, so i wanted
to know if you have limited auditors

**Comment by Cryptocool1** [comment]
> Hello, I would like to know, is there recommended company you accept audits? I ask this because we have requested audit and we wait for updates, so i wanted to know if you have limited auditors
> […](#)

Certik and Hacken.

**Comment by jimmyjah369** [comment]
Hello we have started audit with Techrate company and anytime from today or
tomorrow they will give us audit report, techrate is working with many
project and you can check more about them in their website
https://techrate.org

After they give us audit report we will share it with you here 🙏🏼

**Comment by Cryptocool1** [comment]
Hello,
please create new PR when smart contract audit will be ready.
make sure to mention this PR, so that we can see that fee has been paid already here.

**Comment by jimmyjah369** [comment]
We have contract audit report already, sorry for any inconvenience happened

**Comment by Cryptocool1** [comment]
can you please add links to your PR?
example: https://developer.trustwallet.com/add_new_asset#info-json-contents

**Comment by jimmyjah369** [comment]
https://github.com/TechRate/Smart-Contract-Audits/blob/main/NO%20COVID%2019.pdf

☝🏼☝🏼Above is our contract audit report

**Comment by jimmyjah369** [comment]
Hello @Cryptocool1 

We have submitted out Contract audit report link, waiting for your updates on our Logo 

https://github.com/TechRate/Smart-Contract-Audits/blob/main/NO%20COVID%2019.pdf

**Comment by cryptomanz** [comment]
can you please add links to your PR?
example: https://developer.trustwallet.com/add_new_asset#info-json-contents

**Comment by jimmyjah369** [comment]
We are working on it

**Comment by jimmyjah369** [comment]
Hello @Cryptocool1 @cryptomanz 

We have added required files on our pr already

Waiting for further updates on our Token Logo 🙏🏼🙏🏼

**Comment by jimmyjah369** [comment]
Hello @Cryptocool1 & @cryptomanz 

Can you let us know when our Logo will be live in Trust wallet after we added required file

**Comment by cryptomanz** [comment]
> Hello @Cryptocool1 & @cryptomanz
> 
> Can you let us know when our Logo will be live in Trust wallet after we added required file

merged.
wait a little bit for logo

**Pull request merged**
