### PR TITLE
Add HenTai token Logo to Trust wallet

### PR DESCRIPTION
**Pull request by pumpcc**
Please help review our token. Thank you

### CODE REVIEW

**Comment by cryptomanz** [comment]
Hello,
- As per our policy, brand new tokens are not included, there is a minimum requirement of 2500 holder addresses and 5000 transactions, in order to filter out scam tokens.
See the criteria at (mentioned in the first message by the bot): https://community.trustwallet.com/t/how-to-submit-a-token-logo/3863).

**Comment by Cryptocool1** [comment]
Logo image too large, max 100 kB, current 109.707 kB
 please correct

**Comment by pumpcc** [comment]
logo

@Cryptocool1 I updated the logo file. Please help. Thank you

**Comment by pumpcc** [comment]
hello @Cryptocool1 @cryptomanz could you please help? we're qualified already. Thanks

**Comment by Cryptocool1** [comment]
Please create new PR, follow doc https://community.trustwallet.com/t/how-to-submit-a-token-logo/3863
You may want to try our Assets app in beta; go to https://assets.trustwallet.com, log on with Github, enter contract ID, logo and some additional info, and it will create a PR for you.
See https://community.trustwallet.com/t/how-to-submit-a-token-logo-using-assets-app/82957.

**Comment by Cryptocool1** [comment]
make sure to mention this PR, so that fee can be reused

**Comment by pumpcc** [comment]
why don't we use this one, We paid the fee already, Just created this PR first for fast processing.

**Comment by Cryptocool1** [comment]
> why don't we use this one, We paid the fee already, Just created this PR first for fast processing.

so you need to change your logo. if you can't do this, please create new PR

**Comment by pumpcc** [comment]
> logo
> 
> @Cryptocool1 I updated the logo file. Please help. Thank you

@Cryptocool1 I updated the new logo here, can you please help?

**Comment by Cryptocool1** [comment]
> > logo
> > @Cryptocool1 I updated the logo file. Please help. Thank you
> 
> @Cryptocool1 I updated the new logo here, can you please help?

You commented on PR, not updated, sorry
It will be easier to create new PR

**Comment by pumpcc** [comment]
@Cryptocool1 @cryptomanz I have commited the new logo, our holders and transactions are also qualified. Please check. thanks you

**Pull request merged**
