### PR TITLE
Add Serenity Shield (BEP20)

### PR DESCRIPTION
**Pull request by Halfury**
Adding info for BEP20 token 'Serenity Shield'.

PR created by <a href="https://assets.trustwallet.com">TW Assets Management</a>

### CODE REVIEW

**Comment by Cryptocool1** [comment]
As per our policy, there is a minimum requirement of 10,000 holder addresses and 15,000 transactions, in order to filter out scam tokens.
See the criteria at : https://developer.trustwallet.com/listing-new-assets/requirements .

**Comment by Cryptocool1** [comment]
Feel free to come back to us once all criteria are met

**Comment by Halfury** [comment]
Good day CryptoA,

First of all, happy new year.

I understand that there are many scam projects but Serenity Shield is not
the case. Our community is asking us when they can see their $SERSH tokens
in their wallets, that is why we have made the request and paid the
requested Fee.

We have read the requirements and the point you mention says "is subject
for review based on the project".

Below I mention some milestones to show that we are not a scam project.

   - We launched our token 2 weeks ago and currently have 5500 holders and
   32000 transactions.
   - We list the token on 2 CEXs and 1 DEX with a daily volume of at least
   $1M. Since December 18, when we listed the token, until today there was
   $20M in total volume.
   - We added $300K of liquidity in the LP and locked the liquidity (
   https://bscscan.com/tx/0x025ba423bfc8439cef87bcc497271507176ff0b00c561bc5f8c30b5bd307d170
   ).
   - The team, treasury and marketing tokens have a 3-year vesting (it is
   possible to verify it on-chain).
   - We have a product (StrongBox) on mainnet before our listing.
   - We are a registered company and our team is fully doxxed.
   - We have partnerships with large projects such as Secret Network (
   https://twitter.com/SecretNetwork/status/1724502955640938712), Hacken,
   Kairon Labs, among others.
   - We managed to obtain the VASP license in the European Union.
   - Among other great milestones.

I ask you if you can review our project again to be listed in Trust Wallet,
please.

Thank you so much.

Regards,
Juan Martin.

**Comment by Halfury** [comment]
Good day @Cryptocool1 @cryptomanz1 @natedaiger @hexorx 

I hope you are good.

We are approaching 7000 holders and our community is constantly asking us when we will be listed on TrustWallet. I wanted to ask you, please, if you could analyze our project again, so that we can be listed on TrustWallet.

Thank you.

Regards,
Juan Martin.

**Comment by Halfury** [comment]
Good day @Cryptocool1 @cryptomanz1 @natedaiger @hexorx 

Due to a Serenity Shield liquidity wallet being compromised, we had to migrate our Contract Address. Please could you replace the previous one with this one? 

Token in PR: BEP20 0x84affEEf925Cdce87f8A99B7b2E540dA5140Fc09
Symbol: SERSH 
Decimals: 18

Evidence: https://twitter.com/SerenityShield_/status/1764946342135189624

Thank you so much!

Regards,
Juan Martin.

**Comment by Halfury** [comment]
Good day @Cryptocool1 @cryptomanz1 @natedaiger @hexorx 

I hope you are good!

We have launched the new token to the market and we would need you to update the contract, please!

https://twitter.com/SerenityShield_/status/1767158867442438336

Many thanks!

Regards,
Juan Martin.

**Pull request closed without merging**
