### PR TITLE
Add X AI (BEP20)

### PR DESCRIPTION
**Pull request by xaicodes**
Adding info for BEP20 token 'X AI'.

PR created by <a href="https://assets.trustwallet.com">TW Assets Management</a>

### CODE REVIEW

**Comment by xaicodes** [comment]
Contract Audit 

StaySafu: https://www.staysafu.org/audit/xai
SolidProof: https://github.com/solidproof/projects/blob/main/2023/XAI/SmartContract_Audit_Solidproof_XAIToken.pdf

Contract ownership renounced: https://bscscan.com/tx/0x9292a87001b5758608dc6d21139e06f31c0ef28d69a69f2028d0e3a77fa08952

**Comment by Cryptocool1** [comment]
• What is the purpose of this token? How will it benefit Trust Wallet users?
 • How is the token being distributed? Are you conducting an airdrop?
 • Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?
 • Is the token listed on a centralized/decentralized exchange?

**Comment by cryptomanz1** [comment]
hello,
you should remove those 3 warnings in order to be listed on Trust Wallet
Screenshot 2023-05-10 at 09 33 10
5495047/bd75b3a0-1f49-4d68-a78c-457237a5dae3">
Screenshot 2023-05-10 at 09 33 05

**Comment by cryptomanz1** [comment]
hello,
you should remove those 3 warnings in order to be listed on Trust Wallet
Screenshot 2023-05-10 at 09 33 10

Screenshot 2023-05-10 at 09 33 05

Screenshot 2023-05-10 at 09 32 59

**Comment by xaicodes** [comment]
• What is the purpose of this token? How will it benefit Trust Wallet users?
X AI offer 3 AI utilities, which is X Draw, X GPT and X Scanner. It benefit trust wallet users as most of our users are using  trust wallet and by listed on Trust Wallet, they can get to see the price, logo and build up the brand.

• How is the token being distributed? Are you conducting an airdrop?
Token is being distributed through PancakeSwap, we are not conducting an airdrop.

• Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?
No ICO or presale.

• Is the token listed on a centralized/decentralized exchange?
Yes it is listed on PancakeSwap.

**Comment by Cryptocool1** [comment]
How did you get more than 14k holders in 8 days?

**Comment by xaicodes** [comment]
> hello, you should remove those 3 warnings in order to be listed on Trust Wallet Screenshot 2023-05-10 at 09 33 10
> Screenshot 2023-05-10 at 09 33 05 Screenshot 2023-05-10 at 09 32 59

Hi,

We had renounced ownership and actually reach out to GoPlusLab on this, they had changed our sell tax from a reported 100% to 0%.

Our ownership renounced was done weeks ago:
https://bscscan.com/tx/0x9292a87001b5758608dc6d21139e06f31c0ef28d69a69f2028d0e3a77fa08952

We had also inform them of this situation.

For trading cooldown, there is a 15s trading cooldown to sell after buy at PancakeSwap (does not affect transfer), this is to prevent front runner bot. We had also informed GoPlusLab and they had due to the inform, changed our sell tax from 100% to 0%.

Lastly, we cannot change any balance. The contract is already renounced.

**Comment by xaicodes** [comment]
> How did you get more than 14k holders in 8 days?

We got viral at DEXTools Trending on our first two day of launch; then we launch Twitter campaigns with Influencers. X Draw which is an AI Drawing utility provided by us, contain watermark of your website Xai.codes which bring traffic back to our website and drawn attention to the crypto community.

**Comment by xaicodes** [comment]
We had contacted GoPlusLab admin RainMaker at Telegram, here is the response towards the issue highlight earlier.

goplus

**Comment by xaicodes** [comment]
goplus3

Contacted GoPlusLab and can be seen our contract ownership now is 00000000000000 which is a dead address, the risks stated below can't be invoke. We also did 2 contract security Audit. Thanks

> hello, you should remove those 3 warnings in order to be listed on Trust Wallet Screenshot 2023-05-10 at 09 33 10
> Screenshot 2023-05-10 at 09 33 05 Screenshot 2023-05-10 at 09 32 59

**Comment by pepestyle** [comment]
Hi @Cryptocool1 , I had shown the chat dialogue with GoPlus team, they won't remove it as mention in the screenshot, but we already renounced. how do we proceed further.

**Comment by xaicodes** [comment]
@cryptomanz1 @Cryptocool1 

Please assist, we already spoken to GoPlusLab but they give the response as shown above.

**Pull request merged**
