### PR TITLE
Add LucidLandsGem (BEP20)

### PR DESCRIPTION
**Pull request by mostermas**
Adding info for BEP20 token 'LucidLandsGem'.

PR created by <a href="https://assets.trustwallet.com">TW Assets Management</a>

### CODE REVIEW

**Comment by mostermas** [comment]
LG has migrated to new contract address , we ask to update info!
Old contract is  0x4691F60c894d3f16047824004420542E4674E621  and new is 0xE4C293Eadbb9d72d68a680F1A66979726992c396

**Comment by mostermas** [comment]
https://github.com/trustwallet/assets/pull/16902 fee is paid

**Comment by mostermas** [comment]
https://github.com/trustwallet/assets/pull/17577 and PR was closed before because you need to abandoned our old contract

**Comment by cryptomanz** [comment]
can you please add links?
see the requirements here : https://developer.trustwallet.com/assets/repository_details

**Comment by mostermas** [comment]
Yes , updeted
 info.json

пт, 28 янв. 2022 г. в 18:34, Nazar ***@***.***>:

**Comment by Cryptocool1** [comment]
hello, what is your old contract?

**Comment by Cryptocool1** [comment]
Снимок экрана 2022-01-29 в 00 10 20
The fee is needed for migration 
You can see the requirement here: https://developer.trustwallet.com/assets/pr-fee

**Comment by mostermas** [comment]
Paid


пт, 28 янв. 2022 г. в 19:11, CryptoA ***@***.***>:

**Comment by mostermas** [comment]
https://explorer.binance.org/tx/83A7932CE20A731E3174CD0F73C086EF9CFFE5E41956771083D5927D1973E20B

пт, 28 янв. 2022 г. в 20:12, MAD MAX ***@***.***>:

**Comment by cryptomanz** [comment]
can you send an official announcement about migration ?

**Comment by mostermas** [comment]
https://t.me/LucidLandsOffcial/186 -  Migration Announcement
https://t.me/LucidLandsOffcial/191  -  Migration Complete
https://t.me/LucidLandsOffcial/192 - Trading open

New contract audit -
https://github.com/interfinetwork/smart-contract-audits/blob/audit-updates/LucidLands_0xE4C293Eadbb9d72d68a680F1A66979726992c396.pdf

https://t.me/LucidLandsOffcial/196 - listed on CoinMarketCap again.

сб, 29 янв. 2022 г. в 03:17, Nazar ***@***.***>:

**Pull request merged**
