### PR TITLE
Add BCDC logo and info

### PR DESCRIPTION
**Pull request by bcdc-defi**
We have updated the info on our site. We paid once before, do we have to repay the fee for check up? The information on our medium was written by the marketer we hired and seems like the marketer has referenced from other websites on the features. Our team has checked and fixed it. Thank you for your work. 
@catenocrypt

### CODE REVIEW

**Comment by bcdc-defi** [comment]
@catenocrypt  @Iamdeadlyz 
We have submitted for adding logo before and got rejected due to not enough holders, transaction requirement, some information similar to other defi projects. Our marketer intend to deliver information to our users, but there were no intention of  misleading the users with information. We have fixed the information from the medium. BCDC is project run by basic.finance, basic team is well-known project that has been running for almost two years. Thanks for letting us know for our mistakes. Please take a note that the information has been changed. You can check the information about our project directly from  https://twitter.com/thebasicfinance, which is BASIC team's official twitter.

**Comment by catenocrypt** [comment]
Fixed info.json (removed extra trailing comma)

**Comment by catenocrypt** [comment]
see also #5198 .

**Comment by bcdc-defi** [comment]
@catenocrypt 
We have reviewed the information you guys have pointed before and changed it to our own words. Our marketer has mistakenly used the information from other defi projects. However, it is different from what we intended to post. Please chceck the information we have fixed and review for the addiing logo. Thank you very much for your effort. We would not have noticed the mistakes from our information if you guys have not pointed out.

**Comment by bcdc-defi** [comment]
@catenocrypt @Iamdeadlyz 
If there are any other feedback that can be issued, please let us know. Once again, we are DeFi project run by BASIC team (https://basic.finance). You can check more information from BASIC's twitter and announcements.

**Comment by bcdc-defi** [comment]
@zachzwei @catenocrypt @Iamdeadlyz
Hello, any feedback?

**Comment by Iamdeadlyz** [comment]
Please give further information on what is your relationship with Digital Finance Group (DFG).

image

**Comment by bbr-defi** [comment]
@Iamdeadlyz
BASIC and Digital Finance Group agree to strategic partnership. By establishing a joint venture in China, BASIC will acquire new users, attracting startups and miners looking for loans.

https://twitter.com/thebasicfinance/status/1245978076720156672

We have MOU agreement signed with DFG in paper, but we cannot share this in public. If you really need to see the paper, we can show it to you through sharing link privately. The current joint venture is on hold due to Covid-19.

**Comment by bcdc-defi** [comment]
@Iamdeadlyz
BASIC and Digital Finance Group agree to strategic partnership. By establishing a joint venture in China, BASIC will acquire new users, attracting startups and miners looking for loans.

https://twitter.com/thebasicfinance/status/1245978076720156672

We have MOU agreement signed with DFG in paper, but we cannot share this in public. If you really need to see the paper, we can show it to you through sharing link privately. The current joint venture is on hold due to Covid-19.

**Comment by Iamdeadlyz** [comment]
> The current joint venture is on hold due to Covid-19.

Is this also the reason why you're not listed here?
https://www.dfg.group/investment

**Comment by bcdc-defi** [comment]
Yes, we still do have MOU Document signed and ready. As I said, we cannot share the document in public, but We're glad to share it privately with read-only access
.

**Pull request merged**
