### PR TITLE
Add Wrapped JAXNET (BEP20)

### PR DESCRIPTION
**Pull request by dark-sizter**
Adding info for BEP20 token 'Wrapped JAXNET'.

PR created by <a href="https://assets.trustwallet.com">TW Assets Management</a>

### CODE REVIEW

**Comment by dark-sizter** [comment]
please check so i can pay

**Comment by dark-sizter** [comment]
can i pay now @Cryptocool1

**Comment by dark-sizter** [comment]
fee paided @Cryptocool1 @cryptomanz @Iamdeadlyz

**Comment by Cryptocool1** [comment]
• Is a Smart Contract audit completed? Where can we find this information?

**Comment by dark-sizter** [comment]
Here is the smart contract https://www.certik.com/projects/jax-network

**Pull request merged**
