### PR TITLE
add logo token for Mini Cardano

### PR DESCRIPTION
**Pull request by proxxxxxxies**
add logo token for Mini Cardano (MADA) please help to process.

### CODE REVIEW

**Comment by proxxxxxxies** [comment]
hi @Cryptocool1 @catenocrypt please help check my logo request. thanks

**Review by proxxxxxxies — COMMENTED** [review]
update ID

**Comment by cryptomanz** [comment]
hello,
• What is the purpose of this token? How will it benefit Trust Wallet users?
 • How is the token being distributed? Are you conducting an airdrop?
 • Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?
 • Is the token listed on a centralized/decentralized exchange?
 • Is a Smart Contract audit completed? Where can we find this information?

**Comment by proxxxxxxies** [comment]
• What is the purpose of this token? How will it benefit Trust Wallet users?
  We aim to create a network and open-source project that aims to be a smart contract platform, as well as a traditional asset-based cryptocurrency that’s a derivative to ADA. Our community is growing fast, mainly using Trust Wallet to hold their tokens. Adding MADA will bring great benefit for the users ( easily to finding token/ more credibilit ).

   • How is the token being distributed? Are you conducting an airdrop?
   100,000,000,000 is the total supply. 25% burn at the initial. There's no airdrop. 
  
  • Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?
  No, it's a fair launch. There's no ICO or presale.
 
 • Is the token listed on a centralized/decentralized exchange?
 -> yes, we listed on PancakeSwap. On Q4, we will start to list on a centralized exchange. 

 • Is a Smart Contract audit completed? Where can we find this information?
 We're working with TechRate for the auditing. it's in-progress. Please find the attached file for our quick check.
[Mini Cardano.pdf](https://github.com/trustwallet/assets/files/7109080/Mini.Cardano.pdf)

**Comment by proxxxxxxies** [comment]
@Cryptocool1 @cryptomanz please find my answers for your questions. Thanks. please help proceed the request.

**Comment by Cryptocool1** [comment]
Awaiting for full smart contract audit 
On hold for now

**Comment by proxxxxxxies** [comment]
Please find more information about our Token and the Audit report

Information on CMC and CoinGecko
https://www.coingecko.com/en/coins/mini-cardano
https://coinmarketcap.com/currencies/mini-cardano/

Audit report:
https://github.com/MiniCardano-Foundation/MADA-Contract/blob/main/MiniCardano_Audit.pdf

Email contact: Nic@minicardano.finance

Thanks

**Comment by proxxxxxxies** [comment]
@Cryptocool1 please help review. Thanks

**Pull request merged**
