### PR TITLE
Add  BEP20 KEX and fix URL to https on ethereum

### PR DESCRIPTION
**Pull request by asmodat**

### CODE REVIEW

**Comment by asmodat** [comment]
Payment was made, please update token info: https://explorer.binance.org/tx/0F1381EE855C603860D3C2903AAF6704012BAFAD987D5F633D1C0E8609D2EC46

**Comment by catenocrypt** [comment]
Note: ERC20 version of KEX:  https://etherscan.io/token/0x16980b3b4a3f9d89e33311b5aa8f80303e5ca4f8

**Comment by catenocrypt** [comment]
Corrections needed:
- Token contract folder name should be in checksum format.  Please rename.  I tried to rename, but I have no write permission to the underlying repo.
- `blockchains/smartchain/tokenlist.json` is maintained separately, please revert this file.

-----------------

```
git mv blockchains/smartchain/assets/0x8d11ec38a3eb5e956b052f67da8bdc9bef8abf3e blockchains/smartchain/assets/0x8D11eC38a3EB5E956B052f67Da8Bdc9bef8Abf3E.RENAME
git mv blockchains/smartchain/assets/0x8D11eC38a3EB5E956B052f67Da8Bdc9bef8Abf3E.RENAME blockchains/smartchain/assets/0x8D11eC38a3EB5E956B052f67Da8Bdc9bef8Abf3E
```

**Comment by asmodat** [comment]
checksum format applied
write permissions were added: https://github.com/KiraCore/assets/invitations

**Pull request merged**
