### PR TITLE
add Kunci Coin

### PR DESCRIPTION
**Pull request by ginoizm**
name: Kunci Coin
type: BEP20
symbol: KUNCI
decimals: 6
smart contract: 0x6cf271270662be1C4fc1b7BB7D7D7Fc60Cc19125
website: https://kuncicoin.com/
explorer: https://bscscan.com/token/0x6cf271270662be1C4fc1b7BB7D7D7Fc60Cc19125

### CODE REVIEW

**Comment by ginoizm** [comment]
> number of holders

https://bscscan.com/token/0x6cf271270662be1C4fc1b7BB7D7D7Fc60Cc19125
already 1,532 holders.

**Comment by cryptomanz** [comment]
• What is the purpose of this token? How will it benefit Trust Wallet users?
 • How is the token being distributed? Are you conducting an airdrop?
 • Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?
 • Is the token listed on a centralized/decentralized exchange?
 • Is a Smart Contract audit completed? Where can we find this information?

**Review by Kaktus259 — APPROVED** [review]

**Comment by Cryptocool1** [comment]
- As per our policy, brand new tokens are not included, there is a minimum requirement of 10,000 holder addresses and 15,000 transactions, in order to filter out scam tokens.
See the criteria at : https://developer.trustwallet.com/assets/requirements .
- we require full smart contract audit

**Comment by Cryptocool1** [comment]
please come back to us when all criteria are met. make sure to mention this PR so the fee can be reused

**Comment by ginoizm** [comment]
@Cryptocool1 
> please come back to us when all criteria are met. make sure to mention this PR so the fee can be reused

security audit is done by certik.
https://www.certik.com/projects/kunci-coin

- no critial problem.
- 1 major problem is fixing (soonly solved)

We have already met your requirements.
Thanks.

**Pull request merged**
