### PR TITLE
Add UnderDog Logo & Info

### PR DESCRIPTION
**Pull request by underdogfinance**
thanks

### CODE REVIEW

**Comment by catenocrypt** [comment]
Correction needed: info files should be called `info.json`, not json.info :D  Please rename.

**Review by underdogfinance — COMMENTED** [review]
made rename, thanks

**Comment by underdogfinance** [comment]
Hi, what is status, we made the remane as you asked and now see all checks failed after ?

Thanks in advance

Regards

Underdog Team

**Comment by catenocrypt** [comment]
Correction needed: the info file contains invalid JSON, quotes are missing.

image

**Comment by catenocrypt** [comment]
Fixed JSON

**Pull request merged**
