### PR TITLE
Add SportPoint (BEP20)

### PR DESCRIPTION
**Pull request by UmudHasanov**
Adding info for BEP20 token 'SportPoint'.

PR created by <a href="https://assets.trustwallet.com">TW Assets Management</a>

### CODE REVIEW

**Comment by UmudHasanov** [comment]
Hello, dear TrustWallet admins and team members. I have previously contacted you with a request to approve our token. Please consider our request again. (We have paid the fee)
https://github.com/trustwallet/assets/pull/28915

**Comment by UmudHasanov** [comment]
> @UmudHasanov, kind reminder: please pay fee: **500 TWT** to the address `0x020C13D3459C153A3cB74AdC214Cb69cb411e083`. Alternatively, 2.5 BNB is also accepted (same address).
> 
> **QR** code: [Trust](https://api.qrserver.com/v1/create-qr-code/?size=200x200&data=https%3A%2F%2Flink.trustwallet.com%2Fsend%3Fasset%3Dc20000714_t0x4B0F1812e5Df2A09796481Ff14017e6005508003%26address%3D0x020C13D3459C153A3cB74AdC214Cb69cb411e083%26amount%3D500) | [other wallet](https://api.qrserver.com/v1/create-qr-code/?size=200x200&data=0x020C13D3459C153A3cB74AdC214Cb69cb411e083%3Famount%3D500) See the [Pull Request Fee FAQ](https://developer.trustwallet.com/assets/faq).

please take into account that I paid the fee in the previous Request.

https://github.com/trustwallet/assets/pull/28915#issuecomment-2285381105

**Comment by UmudHasanov** [comment]
> @UmudHasanov, kind reminder: please pay fee: **500 TWT** to the address `0x020C13D3459C153A3cB74AdC214Cb69cb411e083`. Alternatively, 2.5 BNB is also accepted (same address).
> 
> **QR** code: [Trust](https://api.qrserver.com/v1/create-qr-code/?size=200x200&data=https%3A%2F%2Flink.trustwallet.com%2Fsend%3Fasset%3Dc20000714_t0x4B0F1812e5Df2A09796481Ff14017e6005508003%26address%3D0x020C13D3459C153A3cB74AdC214Cb69cb411e083%26amount%3D500) | [other wallet](https://api.qrserver.com/v1/create-qr-code/?size=200x200&data=0x020C13D3459C153A3cB74AdC214Cb69cb411e083%3Famount%3D500) See the [Pull Request Fee FAQ](https://developer.trustwallet.com/assets/faq).

Last time I made a payment but my application was not approved. You wrote to me that next time I submit an application I will not make a repeat payment. Here is a link to your message:
https://github.com/trustwallet/assets/pull/28915#issuecomment-2285381105

**Comment by UmudHasanov** [comment]
> @UmudHasanov, kind reminder: please pay fee: **500 TWT** to the address `0x020C13D3459C153A3cB74AdC214Cb69cb411e083`. Alternatively, 2.5 BNB is also accepted (same address).
> 
> **QR** code: [Trust](https://api.qrserver.com/v1/create-qr-code/?size=200x200&data=https%3A%2F%2Flink.trustwallet.com%2Fsend%3Fasset%3Dc20000714_t0x4B0F1812e5Df2A09796481Ff14017e6005508003%26address%3D0x020C13D3459C153A3cB74AdC214Cb69cb411e083%26amount%3D500) | [other wallet](https://api.qrserver.com/v1/create-qr-code/?size=200x200&data=0x020C13D3459C153A3cB74AdC214Cb69cb411e083%3Famount%3D500) See the [Pull Request Fee FAQ](https://developer.trustwallet.com/assets/faq).

Last time I made a payment but my application was not approved. You wrote to me that next time I submit an application I will not make a repeat payment. Here is a link to your message:  https://github.com/trustwallet/assets/pull/28915#issuecomment-2285381105

**Comment by rkokhatskyi** [comment]
Hi @cryptomanz1 @Cryptocool1, please review the PR and handle it manually. User has already paid in another PR, but didn't met the number of holders requirement initially

**Comment by cryptomanz1** [comment]
• What is the purpose of this token? How will it benefit Trust Wallet users?
 • How is the token being distributed? Are you conducting an airdrop?
 • Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?
 • Is the token listed on a centralized/decentralized exchange?
 • Is a Smart Contract audit completed? Where can we find this information?

**Comment by UmudHasanov** [comment]
> • What is the purpose of this token? How will it benefit Trust Wallet users? • How is the token being distributed? Are you conducting an airdrop? • Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale? • Is the token listed on a centralized/decentralized exchange? • Is a Smart Contract audit completed? Where can we find this information?

1. What is the purpose of this token? How will it benefit Trust Wallet users?

The SportPoint (POINT) token is designed to facilitate seamless transactions within the SportPoint ecosystem, connecting users, trainers, and sports facilities worldwide. Trust Wallet users will benefit from low transaction fees and easy access to various fitness services, creating a flexible and user-friendly environment for both sports enthusiasts and professionals.

2. How is the token being distributed? Are you conducting an airdrop?

The SportPoint token distribution includes allocations for team members, early investors, public sale, community incentives, and partnerships. We have also conducted an airdrop event to encourage initial engagement and awareness among our community members.

3. Did you sell the tokens at an Initial Coin Offering (ICO) or a token presale?

Yes, tokens were sold during a private presale to early investors to raise initial funding for the project's development and scaling efforts.

4. Is the token listed on a centralized/decentralized exchange?

Yes, the SportPoint token is listed on DEX exchange, PancakeSwap.

5. Is a Smart Contract audit completed? Where can we find this information?

Yes, the SportPoint smart contract has been audited by CyberScope, a one of the best smart contract auditor. You can view the audit report at https://www.cyberscope.io/audits/point. Additionally, we have locked over 30% of our tokens in partnership with Time Finance to ensure transparency and trust. You can check the locked tokens at https://www.team.finance/view-coin/0x0cF453DC7EA21ef8FdfFC1B14Cb848E1e3884Be5?name=SportPoint&symbol=POINT&chainid=0x38.

Our team has also successfully completed KYC verification with Coinscope. You can find more details about our KYC verification at https://www.coinscope.co/coin/point/kyc.

Further information about SportPoint can be found on CoinMarketCap at https://coinmarketcap.com/currencies/sportpoint/ and DEXTools at https://www.dextools.io/token/sportpoint.

**Pull request merged**
