### PR TITLE
Add OmniCat (ERC20)

### PR DESCRIPTION
**Pull request by pathofkarma**
Adding info for ERC20 token 'OmniCat'.

PR created by <a href="https://assets.trustwallet.com">TW Assets Management</a>

### CODE REVIEW

**Comment by pathofkarma** [comment]
FYI is multi chain coin - so holders count is low - but across chains - 
ETH  2291
BSC  410
ARB  1,330
CANTO  120
Base  550
Polygon  346
Solana  15,054

eth, canto, bsc, arb, polygon - 0x9e20461bc2c4c980f62f1B279D71734207a6A356
base - 0xc48e605c7b722a57277e087a6170b9e227e5ac0a
solana - 7mmXL6Et4SbpDs2iXoZQ3oPEeXeAiyETxh1QjDNi5qnV

**Comment by pathofkarma** [comment]
reminder to check above comment for multi chain - holder count is above 20k across chains
ETH 2291
BSC 410
ARB 1,330
CANTO 120
Base 550
Polygon 346
Solana 15,054

eth, canto, bsc, arb, polygon - 0x9e20461bc2c4c980f62f1B279D71734207a6A356
base - 0xc48e605c7b722a57277e087a6170b9e227e5ac0a
solana - 7mmXL6Et4SbpDs2iXoZQ3oPEeXeAiyETxh1QjDNi5qnV

**Comment by Cryptocool1** [comment]
You should have more than 10k holders at least for 1 chain you would like to add

**Comment by Cryptocool1** [comment]
As per our policy, there is a minimum requirement of 10,000 holder addresses and 15,000 transactions.
See the criteria at : https://developer.trustwallet.com/listing-new-assets/requirements .

**Comment by Cryptocool1** [comment]
Feel free to come back to us once all criteria are met

**Comment by pathofkarma** [comment]
> You should have more than 10k holders at least for 1 chain you would like to add

Hi there are over 14k holders on Solana, it is a multi chain coin, you can verify here

https://birdeye.so/token/7mmXL6Et4SbpDs2iXoZQ3oPEeXeAiyETxh1QjDNi5qnV?chain=solana

Please re-open

**Pull request closed without merging**
