### PR TITLE
Fail

### PR DESCRIPTION
**Pull request by DiTer-dev**
First commit of MoonToken files for TW submission

### CODE REVIEW

**Comment by DiTer-dev** [comment]
Hello, facing an issue here.
Seems like wrong chain picked... Binance instead of smartchain... Is there a way to solve this?
Thx

**Comment by DiTer-dev** [comment]
Hello @catenocrypt,
Could you please take a look at this and merge if ok? Thx

**Comment by DiTer-dev** [comment]
Hello @catenocrypt @zachzwei ,
Could you please take a look at this and merge if ok? Thx

**Comment by DiTer-dev** [comment]
Hello @catenocrypt @zachzwei ,
Could you please take a look at this and merge if ok? 
Thx

**Comment by catenocrypt** [comment]
Sorry, I can't reopen it either, as it was closed by the creator.  Either reopen it or create a new PR.

**Comment by catenocrypt** [comment]
A closed PR cannot be checked properly, but from what I can see, it looks OK.  The logo is hard to see on white background.

**Comment by DiTer-dev** [comment]
Thanks for the feedback, indeed i'll take a look at the logo.
Regarding the closed status, i cannot either reopen it for some reason. Does remaking a pull request from this require fees?

**Comment by catenocrypt** [comment]
#6398 merged

**Pull request closed without merging**
