### PR TITLE
adding MTV on BSC 

### PR DESCRIPTION
**Pull request by shawnying**
adding MultiVAC token info and logo on BSC.

### CODE REVIEW

**Comment by Cryptocool1** [comment]
hello,
• What is the purpose of this token? How will it benefit Trust Wallet users?
 • How is the token being distributed? Are you conducting an airdrop?
 • Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?
 • Is the token listed on a centralized/decentralized exchange?
 • Is a Smart Contract audit completed? Where can we find this information?

**Comment by shawnying** [comment]
Here are my answers:

• What is the purpose of this token? How will it benefit Trust Wallet users?
MultiVAC started in 2018 and is a Sharding Protocol. As a value medium on the MultiVAC network, MTV Token is used to pay for the gas cost, and represents the staking voting power and governance power of PoS.
The MultiVAC community has more than 10,000 people. The BEP2 version of MultiVAC is already on TrustWallet. But the BEP20 version has more users. Letting TrustWallet support the BEP20 version of MultiVAC can allow more users to use TrustWallet.

• How is the token being distributed? Are you conducting an airdrop?
MultiVAC completed the Private sale in 2018 and completed the IEO in 2019. 3,500 people bought MTV in the IEO. After that, users can use the secondary market to buy MTV

• Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?
MultiVAC completed the Private sale in 2018 and completed the IEO in 2019. 

• Is the token listed on a centralized/decentralized exchange?
MultiVAC has been listed on:
Kucoin.com
MXC
Gate.io
Uniswap
Pancake
DodoEx
BurgerSwap

• Is a Smart Contract audit completed? Where can we find this information?
The MultiVAC contract is audited by Certik, the link is as follows:
https://www.certik.org/projects/multivac

**Comment by cryptomanz** [comment]
can you please add links to your PR?
example: https://developer.trustwallet.com/add_new_asset/repository_details

**Comment by catenocrypt** [comment]
Created dummy commit to re-trigger check; now it fails due to missing links element.

**Pull request merged**
