### PR TITLE
info.json & logo.png files v3

### PR DESCRIPTION
**Pull request by wojak-finance**
info.json & logo.png files v3 for adding our token logo in trust wallet

### CODE REVIEW

**Comment by cryptomanz** [comment]
As per our policy, brand new tokens are not included, there is a minimum requirement of 5000 holder addresses and 10000 transactions, in order to filter out scam tokens.
See the criteria at (mentioned in the first message by the bot): https://community.trustwallet.com/t/how-to-submit-a-token-logo/3863).
Closing PR for now. Please come back to us when all criteria are met.

**Comment by wojak-finance** [comment]
@cryptomanz is there any way to skip those requirement, we really need to add our logo in trustwallet. i saw other tokens have logo without having 5000 holder addresses and 10000 transactions, what about them? how they have logo?
i will be thankful if you help me.

**Comment by AsgharSibil** [comment]
@cryptomanz @hexorx @corymsmith 
Hello
According to Trust Wallet's fundamental laws, no token that has not been audited can load the logo on that platform.
Please review this project again.
The Woj Token project has not been audited, and the company's developers have been duping you. They sent another smart contract to The eNebula company for auditing, which went off without a problem. However, the smart contract they deployed is another smart contract. You may validate my speech using the documentation accessible at The eNebula and the contract deployed on the bscscan. They have been able to defraud thousands of individuals due to this, and the acceptance of the logo on the Trust Wallet platform verifies the ongoing operation of these fraudsters.
Please remove these scammer's token logos from the Trust Wallet platform.
Please have a look.
Best Regards
Webamooz

eNebula company auditing report : 
https://drive.google.com/file/d/1Vu3Az7KTJ_9OIjYTxHyMigkKGDi9blsZ/view

Token deployed on Bscscan : 
https://bscscan.com/address/0x55f96c7005d7c684a65ee653b07b5fe1507c56ab#code

**Comment by AsgharSibil** [comment]
@cryptomanz @hexorx @corymsmith 
Hello
According to Trust Wallet's basic rules, no token that has not been audited can load the logo on that platform.
Please review this project again.
The Woj Token project has not been audited, and the company's developers have been duping you. They sent another smart contract to The eNebula company for auditing, which went off without a problem. However, the smart contract they deployed is another smart contract. You may validate my speech using the documentation accessible at The eNebula and the contract deployed on the bscscan. They have been able to defraud thousands of individuals due to this, and the acceptance of the logo on the Trust Wallet platform verifies the ongoing operation of these fraudsters.
Please remove these scammer's token logos from the Trust Wallet platform.
Please have a look.
Best Regards
Webamooz

eNebula company auditing report : 
https://drive.google.com/file/d/1Vu3Az7KTJ_9OIjYTxHyMigkKGDi9blsZ/view

Token deployed on Bscscan : 
https://bscscan.com/address/0x55f96c7005d7c684a65ee653b07b5fe1507c56ab#code

**Pull request closed without merging**
