### PR TITLE
Please Add DMST token logo 

### PR DESCRIPTION
**Pull request by Shyamthakur33**
Token name - DMScript
Token symbol - DMST
Decimal - 18
Total supply - 100,000,000
Smart contract - 0xF29992D7b589A0A6bD2de7Be29a97A6EB73EaF85
0xF29992D7b589A0A6bD2de7Be29a97A6EB73EaF85

### CODE REVIEW

**Comment by Shyamthakur33** [comment]
payment send, thanks

**Comment by catenocrypt** [comment]
Please note that logo and contract in the PR does not match the ones in the description!
Shall I merge?

image

image

**Comment by Shyamthakur33** [comment]
What do you mean sir? Please check below link here my side showing different logo in pr. I want this logo what is in below link. 
https://ibb.co/FJPFSDW

**Comment by Shyamthakur33** [comment]
If it still showing wrong logo in your side then please wait for sometime, I will edit the pr.

**Comment by Shyamthakur33** [comment]
Token name - DMScript
Token symbol - DMST
Decimal - 18
Total supply - 100,000,000
Smart contract - 0xF29992D7b589A0A6bD2de7Be29a97A6EB73EaF85
0xF29992D7b589A0A6bD2de7Be29a97A6EB73EaF85

**Comment by Shyamthakur33** [comment]
Please update this logo

**Comment by Shyamthakur33** [comment]
0xF29992D7b589A0A6bD2de7Be29a97A6EB73EaF85

**Pull request merged**
