### PR TITLE
Update Floki Inu BSC contract details.

### PR DESCRIPTION
**Pull request by ghost**
Hi, I've already paid and uploaded details for Floki Inu on the Ethereum network.

I simply need to upload details for the Smart Chain version of Floki Inu ONLY.

Appreciate your assistance in advance.

### CODE REVIEW

**Comment by sohailamir** [comment]
I don't want to update any files on the Ethereum asset by the way. ONLY add the Smart Chain contract information. Thanks!

**Comment by Cryptocool1** [comment]
please create new PR only with bep20 files

**Comment by sohailamir** [comment]
It doesn't allow me to create a new pull request just for the BEP20 files. 

When I add the BEP20 files it automatically shows files to commit for the ERC20 version I pushed a few days ago? I've attached here the files that I need to commit.

[0x2b3f34e9d4b127797ce6244ea341a83733ddd6e4.zip](https://github.com/trustwallet/assets/files/6873032/0x2b3f34e9d4b127797ce6244ea341a83733ddd6e4.zip)

**Comment by Cryptocool1** [comment]
You may want to try our Assets app in beta; go to https://assets.trustwallet.com, log on with Github, enter contract ID, logo and some additional info, and it will create a PR for you.
See https://community.trustwallet.com/t/how-to-submit-a-token-logo-using-assets-app/82957.

**Comment by sohailamir** [comment]
You can check the PR I’ve done from the beta at PR 12202   https://github.com/trustwallet/assets/pull/12202 <https://github.com/trustwallet/assets/pull/12202>.

**Pull request closed without merging**
