### PR TITLE
Update Shiryo Inu logo 

### PR DESCRIPTION
**Pull request by rxchyrxch**
We have requested and paid for this before but it doesn't seem to have worked.

### CODE REVIEW

**Comment by cryptomanz** [comment]
Hello,
Can your answer some questions?
• What is the purpose of this token? How will it benefit Trust Wallet users?
 • How is the token being distributed? Are you conducting an airdrop?
 • Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?
 • Is the token listed on a centralized/decentralized exchange?
 • Is a Smart Contract audit completed? Where can we find this information?

**Comment by rxchyrxch** [comment]
Hello

- Shiryo-Inu is a P2E crypto game developed on the Ethereum network. We have thousands of holders including trust wallets users who love Shiryo-Inu. It will give them an opportunity to play card game using crypto. 
- The token was fair launched at the beginning of November 2021.
- The token is listen on both CEX and DEX. 
- We are Certik audited project. You will be able to find the audit on Certik website.

**Comment by Cryptocool1** [comment]
could you add the links?
see the example here: https://developer.trustwallet.com/assets/repository_details

**Comment by rxchyrxch** [comment]
What links?

**Comment by Cryptocool1** [comment]
> What links?

you can see them in the example that I mentioned above

**Comment by cryptomanz** [comment]
Screenshot 2021-10-06 at 20 22 37

**Comment by rxchyrxch** [comment]
Do you want me to upload a repository with the Json and the logo?

**Comment by rxchyrxch** [comment]
https://github.com/rxchyrxch/assets/tree/master/blockchains/ethereum/assets/0x1E2F15302B90EddE696593607b6bD444B64e8F02

**Comment by rxchyrxch** [comment]
Is that okay?

**Comment by Cryptocool1** [comment]
you should add the links into your info.json.

**Comment by rxchyrxch** [comment]
okay I have added telegram and twitter

**Comment by rxchyrxch** [comment]
Is that okay?

**Pull request merged**
