### PR TITLE
Add The DONS (BEP20)

### PR DESCRIPTION
**Pull request by fab153crypto**
Added Information and Logo of "The DONS" BEP20 token.

Happy to provide more information if needed.

### CODE REVIEW

**Comment by Cryptocool1** [comment]
As per our policy, there is a minimum requirement of 10,000 holder addresses and 15,000 transactions, in order to filter out scam tokens.
See the criteria at : https://developer.trustwallet.com/listing-new-assets/requirements .

**Comment by Cryptocool1** [comment]
How did you get more than 5k holders within 1 day?

**Comment by fab153crypto** [comment]
Their team is very well known and trusted in the BNB Chain NFT space for several years with a huge community. Presale was hardcapped to 150BNB and 0.3BNB per wallet and sold out in 2s, so traction is very good. Project is already well recognized by names like @Eljaboom.

All together, this resulted in amazing launch with over $4M volume and 5700 holders in less than 24h.

**Comment by Cryptocool1** [comment]
Please delete tokenlist file from your files

**Pull request merged**
