### PR TITLE
Adding info and logo Sphynx Network (SPH) Token

### PR DESCRIPTION
**Pull request by rdndany**

### CODE REVIEW

**Comment by rdndany** [comment]
Hello @catenocrypto , we know we are under the requested 5000, but can we be approved from the perspective of TXIDS

Thanks with respect Daniel Ilie !

**Comment by cryptomanz** [comment]
As per our policy, brand new tokens are not included, there is a minimum requirement of 5000 holder addresses and 10000 transactions, in order to filter out scam tokens.
See the criteria at (mentioned in the first message by the bot): https://community.trustwallet.com/t/how-to-submit-a-token-logo/3863).
Closing PR for now. Please come back to us when all criteria are met.

**Comment by rdndany** [comment]
Hello Collaborator @cryptomanz, 

We are aware about the mentioned 5000 holder minimum condition. As well about the criteria that  - This requirement is subject for review based on the project, we do fullfill the transaction number which is above required - 12.905.  Hence the reason we submitted the request. 
Sphynx Network is a trustworthy and reliable project. We have been increasing our holders organically and successfully delivering our roadmap.

We are as well listed CoinMarketCap and CoinGecko

CG - https://coingecko.com/en/coins/sphynx-network
CMC- https://coinmarketcap.com/currencies/sphynx-network/

Please check bellow our Audit report

https://firebasestorage.googleapis.com/v0/b/sphynxv2-b97c1.appspot.com/o/Sphynx_Network_SPH_Token_Smart_Contracts_Security_Audit_Report.pdf?alt=media&token=bdb1b0cf-e283-4b5b-beca-a3dfb3d88659

Liquidity is locked : 

https://dxsale.app/app/pages/dxlockview?id=0&add=0x257154F13d4A9ea507E3bc17cD5281cFeE8E0a22&type=tokenlock&chain=BSC

And so are the team and advisors funds: 

https://dxsale.app/app/pages/dxlockview?id=0&add=0x257154F13d4A9ea507E3bc17cD5281cFeE8E0a22&type=tokenlock&chain=BSC

DexTool link 
 https://www.dextools.io/app/pancakeswap/pair-explorer/0xa83fc67dc49e846f21fda57572f09a32a757aa5f

Poocoin link 
https://poocoin.app/tokens/0x8bac6b4af65c8c1967a0fbc27cd37fd6059daa00

All the above is mentioned so it will consolidate the legitimacy of Sphynx Network project, as per by your concern of it might being a scam due to under 5k holders. 
Our community is eager to see the logo on trust wallet, hence the reason we kindly ask you to review and revise our request since it is already closed.

With respect Daniel Ilie
Thank you

**Comment by catenocrypt** [comment]
@rdndany , has fee been paid?

**Comment by SphynxNetworkGitHub** [comment]
hello @catenocrypt 

Please find below the TX ID. 

https://explorer.binance.org/tx/79E50331EF4DA71AAD5FE26FFBD6AA121364ED7757349FDF0A050C9E4D26B587


Thanks,

**Comment by SphynxNetworkGitHub** [comment]
Hello @catenocrypt 

Please find below the tx hash 

79E50331EF4DA71AAD5FE26FFBD6AA121364ED7757349FDF0A050C9E4D26B587

Thanks,

**Comment by catenocrypt** [comment]
Note: only the creator of the PR and maintainers can post comment, rest are deleted (we had a lot of scam messages).

**Comment by catenocrypt** [comment]
Fee was paid through below TX, but memo had a typo, `3043` instead of `13043`, that's why it was not detected automatically.
Setting to paid manually.

https://explorer.binance.org/tx/79E50331EF4DA71AAD5FE26FFBD6AA121364ED7757349FDF0A050C9E4D26B587

image

**Comment by catenocrypt** [comment]
I just realized that this PR was marked paid already 21 days ago!  So that was not the problem.

**Comment by catenocrypt** [comment]
I'm closing it back, ask the maintainers (via a comment here by the creator) to reopen fro reevaluation if there is a change in the relevant conditions.

**Comment by SphynxNetworkGitHub** [comment]
Hello @catenocrypt / @cryptomanz, 

@rdndany will no longer follow nor update about the situation.
kindly consider my request to update the logo as per having 5,096 holders and 
22,638 transaction. 

Thanks,

**Comment by rdndany** [comment]
Hello @catenocrypt,

Please reopen the request for reevaluation.
We respect the types of conditions as we are now at 5,097 holders and 22,972 transactions.

**Pull request merged**
