### PR TITLE
Add TWT logo and info

### PR DESCRIPTION
**Pull request by flokishibainu**
First add TWT logo and info

### CODE REVIEW

**Comment by flokishibainu** [comment]
I cant use asset.trustwallet it keep giving me error on my website, saying 404 website does not exist

**Comment by flokishibainu** [comment]
How to remove/delete previous merges?

**Comment by flokishibainu** [comment]
Can i proceed with this one?

**Comment by Cryptocool1** [comment]
please delete 2 incorrect logos

**Comment by flokishibainu** [comment]
How do delete the 2 incorrect logos?

**Comment by flokishibainu** [comment]
Please advice how to proceed thank you!

**Comment by flokishibainu** [comment]
Can i create a new repo instead? Do advice! thank you

**Pull request closed without merging**
