### PR TITLE
Add BitBurn (BEP20)

### PR DESCRIPTION
**Pull request by bitburnio**
Adding info for BEP20 token 'BitBurn'.

PR created by <a href="https://assets.trustwallet.com">TW Assets Management</a>

### CODE REVIEW

**Comment by Cryptocool1** [comment]
As per our policy, brand new tokens are not included, there is a minimum requirement of 10,000 holder addresses and 15,000 transactions, in order to filter out scam tokens.
See the criteria at : https://developer.trustwallet.com/assets/requirements .

**Comment by bitburnio** [comment]
Our tokens is merging with Enhance token. They paid for the logo listing I can send you hash. We will have the holders in a couple days.
    	BitBurn Official
    
  

 From: CryptoA ***@***.***>Sent: Friday, July 29, 2022 7:23 AMTo: trustwallet/assets ***@***.***>Cc: BitBurn ***@***.***>; Author ***@***.***>Subject: Re: [trustwallet/assets] Add BitBurn (BEP20) (PR #21704) 
As per our policy, brand new tokens are not included, there is a minimum requirement of 10,000 holder addresses and 15,000 transactions, in order to filter out scam tokens.
See the criteria at : https://developer.trustwallet.com/assets/requirements .

**Comment by Cryptocool1** [comment]
How will you get the holders from 700 to 10k?

**Comment by bitburnio** [comment]
BSC Scan isn’t working for our holder count for some reason we have roughly 1,000 right now. Enhance token is merging into our project and they have 14k holders and already paid for TWT that they won’t need anymore 
    	BitBurn Official
    
  

 From: CryptoA ***@***.***>Sent: Friday, July 29, 2022 2:53 PMTo: trustwallet/assets ***@***.***>Cc: BitBurn ***@***.***>; Author ***@***.***>Subject: Re: [trustwallet/assets] Add BitBurn (BEP20) (PR #21704) 
How will you get the holders from 700 to 10k?

**Comment by bitburnio** [comment]
We now have the holders and transfers.https://bscscan.com/tx/0x4dc3e8782bc1f2e6c45afc9a452ec79a0872e1a35cbd4b68e0f824a285e283beHere’s the hash for Enhance which merged to us in regards to TWT tokens. Please update BitBurn logo on trust wallet 
    	BitBurn Official
    
  

 From: CryptoA ***@***.***>Sent: Friday, July 29, 2022 4:53 PMTo: trustwallet/assets ***@***.***>Cc: BitBurn ***@***.***>; Author ***@***.***>Subject: Re: [trustwallet/assets] Add BitBurn (BEP20) (PR #21704) 
How will you get the holders from 700 to 10k?

**Pull request closed without merging**
