### PR TITLE
update FRY token info

### PR DESCRIPTION
**Pull request by h-crypto-z**
This PR is being closed due to inactivity. If you wish to continue, please have us reopen the PR before sending your payment.
Do NOT send payments for closed PR, as the fee may by lost!
  (60 vs. 60 hrs)

### CODE REVIEW

**Comment by catenocrypt** [comment]
Submission looks OK, fee payment pending.

**Comment by h-crypto-z** [comment]
Please open PR for payment to be sent

**Comment by catenocrypt** [comment]
Reopening.  Automation will close it soon, but don't worry, if it is closed by the time payment is made, it will be picked up automatically at the next reopen.

**Comment by catenocrypt** [comment]
#5760

**Pull request closed without merging**
