### PR TITLE
Add Movo Chain

### PR DESCRIPTION
**Pull request by movosmartchain**

### CODE REVIEW

**Comment by movosmartchain** [comment]
i

**Comment by movosmartchain** [comment]
I paid here 
https://github.com/trustwallet/assets/pull/26406

**Comment by movosmartchain** [comment]
@Cryptocool1 
I paid here
https://github.com/trustwallet/assets/pull/26406

**Comment by cryptomanz1** [comment]
we can't accept the PR because we do not have support for Movo in WalletCore yet.
please create PR in: https://github.com/trustwallet/wallet-core

**Comment by cryptomanz1** [comment]
Please follow the doc: https://developer.trustwallet.com/developer/wallet-core/newblockchain

**Pull request closed without merging**
