### PR TITLE
Please add logo to token

### PR DESCRIPTION
**Pull request by MWProtocol**
Please add the logo to the token

### CODE REVIEW

**Comment by MWProtocol** [comment]
I have sent payment

**Comment by catenocrypt** [comment]
As per our policy, brand new tokens are not included, there is a minimum requirement of 500 holder addresses and 1000 transactions, in order to filter out scam tokens.
See the criteria at (mentioned in the first message by the bot): https://community.trustwallet.com/t/how-to-submit-a-token-logo/3863#how-to-get-approved
This token has no real usage yet (3). Putting PR on hold. Please come back to us when all criteria are met.

https://etherscan.io/token/0x9f49a6d5e83ec8bccc1cb14a2b0401cce0cd8790

**Comment by MWProtocol** [comment]
please do not close. I have paid 2 BNB to add the logo.
We will be launching soon and will meet the requirements

**Comment by MWProtocol** [comment]
We will update tomorrow to continue the PR

**Pull request closed without merging**
