### PR TITLE
Add PearZap (Polygon)

### PR DESCRIPTION
**Pull request by polymaticproject**

### CODE REVIEW

**Comment by Cryptocool1** [comment]
hello,
'Links field 'coingecko': 'https://www.coingecko.com/en/coins/pear' must start with 'https://coingecko.com/'.  Supported keys: github,whitepaper,twitter,telegram,telegram_news,medium,discord,reddit,facebook,youtube,coinmarketcap,coingecko,blog,forum,docs,source_code,'
please correct

**Comment by Cryptocool1** [comment]
I need you to answer some questions, please
• What is the purpose of this token? How will it benefit Trust Wallet users?
 • How is the token being distributed? Are you conducting an airdrop?
 • Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?
 • Is the token listed on a centralized/decentralized exchange?
 • Is a Smart Contract audit completed? Where can we find this information?

**Review by jcasalda8 — APPROVED** [review]

**Comment by polymaticproject** [comment]
Hi @Cryptocool1 thanks for the review

> I need you to answer some questions, please

Yes for sure

> • What is the purpose of this token? How will it benefit Trust Wallet users?

$PEAR a Yield farming token with a lot of features and utilities (read more: https://doc.pearzap.com/tokenomics/pearzap-token). Many users saw that you now support the Polygon chain and asked PearZap to do the necessary with you

> • How is the token being distributed? Are you conducting an airdrop?

There were 2 presale rounds before the launch (20-7) and since the launch some small contests. No big aidrops

> • Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?

Yes, 2 presale rounds:

- 14-7 - Whitelist Presale - We raised $15k - $0.45/token _(be used mainly for marketing purposes and for adding liquidity)_
- 19-7 - KoalaDeFI IKO - We raised $80k - $0.5 _(https://twitter.com/pearzap/status/1417050202955997185)_

> • Is the token listed on a centralized/decentralized exchange?

$PEAR is listed on Wault (decentralized)  https://polyinfo.wault.finance/token/0xc8bcb58caef1be972c0b638b1dd8b0748fdc8a44

> • Is a Smart Contract audit completed? Where can we find this information?

There were 2 security audits:

- First preliminary audit from Certik only had minor issues that we fixed for the resubmission. We are waiting for the final report
- Techrate also found no issues in the new code.

Read more:
- https://app.pearzap.com/audit-pz
- TechRate audit: https://github.com/TechRate/Smart-Contract-Audits/blob/main/PEAR%20Standart%20Smart%20Contract%20Security%20Audit.pdf

Thanks

**Comment by polymaticproject** [comment]
Thanks @Cryptocool1 @jcasalda8

**Pull request merged**
