### PR TITLE
add bep20 Aquachain Token (AQUA)

### PR DESCRIPTION
**Pull request by aerth**

### CODE REVIEW

**Comment by Cryptocool1** [comment]
PR should include only 2 files:

blockchains/smartchain/assets/0x38FAB266089AAf3BC2F11B791213840Ea3D587C7/info.json
blockchains/smartchain/assets/0x38FAB266089AAf3BC2F11B791213840Ea3D587C7/logo.png

**Comment by aerth** [comment]
OK, was hoping to add support for the evm network, but will keep separate in this PR.

**Comment by Cryptocool1** [comment]
As per our policy, brand new tokens are not included, there is a minimum requirement of 2500 holder addresses and 5000 transactions, in order to filter out scam tokens.
See the criteria at (mentioned in the first message by the bot): https://community.trustwallet.com/t/how-to-submit-a-token-logo/3863).
Closing PR for now. Please come back to us when all criteria are met.

**Comment by aerth** [comment]
Aquachain Token (AQUA) is (new) 1:1 peg with Aquachain (AQUA) hence the small number of holders currently.

**Comment by Cryptocool1** [comment]
> Aquachain Token (AQUA) is (new) 1:1 peg with Aquachain (AQUA) hence the small number of holders currently.

Hello.
How many holders?

**Comment by aerth** [comment]
I'm not so sure we have 2500 holder addresses. Top 500 at https://info.aquacha.in/richlist.txt
It is not a new project at all, started march 03 2018

btw thanks for the reply

**Pull request closed without merging**
