### PR TITLE
Add logo and info 

### PR DESCRIPTION
**Pull request by marcotravel**

### CODE REVIEW

**Comment by marcotravel** [comment]
we have added links fields to JSON file

**Comment by Cryptocool1** [comment]
hello,
• What is the purpose of this token? How will it benefit Trust Wallet users?
 • How is the token being distributed? Are you conducting an airdrop?
 • Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?
 • Is the token listed on a centralized/decentralized exchange?
 • Is a Smart Contract audit completed? Where can we find this information?

**Comment by Cryptocool1** [comment]
Is a Smart Contract audit completed? Where can we find this information?

**Comment by marcotravel** [comment]
our smart contract has not audit yet

**Comment by marcotravel** [comment]
how long does it take to add the logo inapp?
after add the logo can we search in trust wallet and find MRC?

**Comment by Cryptocool1** [comment]
awaiting for smart contract audit. on hold for now

**Comment by marcotravel** [comment]
We will definitely send it to you after completing the audit smart contract

**Comment by marcotravel** [comment]
Is there any possibility to add our logo before we provide an audit?

**Comment by Cryptocool1** [comment]
please create new PR when smart contract audit will be ready. Make sure to mention this PR, so the fee can be reused

**Pull request closed without merging**
