### PR TITLE
add NULS and NVT LOGO

### PR DESCRIPTION
**Pull request by CQBeer**
This PR is being closed due to inactivity. If you wish to continue, please have us reopen the PR before sending your payment.
Do NOT send payments for closed PR, as the fee may by lost!
  (171 vs. 60 hrs)

### CODE REVIEW

**Comment by catenocrypt** [comment]
As per our policy, brand new tokens are not included, there is a minimum requirement of 2500 holder addresses and 5000 transactions, in order to filter out scam tokens.
See the criteria at (mentioned in the first message by the bot): https://community.trustwallet.com/t/how-to-submit-a-token-logo/3863).
This token has no real usage yet (29). Closing PR for now. Please come back to us when all criteria are met.

https://etherscan.io/token/0x7b6F71c8B123b38aa8099e0098bEC7fbc35B8a13

**Comment by zachzwei** [comment]
Found a related article about $NVT and $NULS.
https://twitter.com/Nuls/status/1329022791698432001
https://nervenetwork.medium.com/nervenetwork-has-implemented-cross-chain-asset-circulation-with-binance-smart-chain-bsc-ee60e1b21081
Please always provide pertinent data about your submission so we can easily review it.
As of now, this is put on hold.
If you have made a payment before, any changes made will still require a new payment.

**Comment by CQBeer** [comment]
hello，I pay on pr #4143 but It is cloese by some reasons.And Now I create this new pr,pls check and merge.Thank you very much

**Comment by catenocrypt** [comment]
Holder count is still at the same low level (29 holers).

**Pull request closed without merging**
