### PR TITLE
Wizard of Dog (WIZ) on BASE

### PR DESCRIPTION
**Pull request by pure-justin**

### CODE REVIEW

**Comment by pure-justin** [comment]
Do you take any other type of Payment I can’t access the Binance chain in my region.  I can get smart chain but not Binance.Also was my file submitted correctly?Thank you,Justin GriffithP. 210.240.2573On Apr 5, 2024, at 7:15 PM, merge-fee-bot[bot] ***@***.***> wrote:﻿
Hi! In order to compensate for the efforts of processing PRs, we kindly ask for a contribution.
💀 As there is no refund, before paying the fee, make sure new tokens fulfill the minimum circulation and other acceptance criteria.
See also the PR Fee FAQ.
Please pay  500 TWT  with the memo 27852  to the TWT-BEP2 (Binance Chain) address bnb158fgd782we4tz9vwwcj9pmmxvxhl6z46lfm7c8.
Alternatively, 2 BNB is also accepted (same memo & address).
QR code: Trust | other wallet
TWT Acquiring:

Trust Wallet Tokens (TWT) can be obtained from DEXs/exchanges.
TWT-BEP2 is supported (Binance Chain), TWT-BEP20 version on Smart Chain is not.
TWT-BEP20 can be traded with TWT-BEP2 using the Trust Wallet Swap Option.

Notes:

New tokens without significant usage are rejected, see criteria mentioned above.
One PR should be for a single project; PR's with more than 10 logos will be rejected.
Payment evaluation happens automatically, but with a few minutes delay.  When payment is detected, an Accept Review is automatically placed on the PR, which is a condition for merge.
Evaluating the PR is done manually, and it is merged only if all conditions are satisfied.
There will be a fee to process this request. None of it goes to the developers.
Before paying the fee, make sure new tokens fulfill the minimum circulation and other acceptance criteria.
If you are paying TWT for the submission, this will be burned automatically. There will be no refunds.

**Review by pure-justin — COMMENTED** [review]
Changed Type to BASE and added a couple links

**Comment by UnPuzzles** [comment]
[bnb158fgd782we4tz9vwwcj9pmmxvxhl6z46lfm7c8.](https://explorer.bnbchain.org/tx/3BC08BDEE0C55E8C6B5D88A2F7F019934E211FB6A709AF3E25E8732392735FF8)

**Comment by cryptomanz1** [comment]
• What is the purpose of this token? How will it benefit Trust Wallet users?
 • How is the token being distributed? Are you conducting an airdrop?
 • Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?
 • Is the token listed on a centralized/decentralized exchange?
 • Is a Smart Contract audit completed? Where can we find this information?

**Comment by pure-justin** [comment]
• What is the purpose of this token? How will it benefit Trust Wallet users?
We are building a community project with a wallet that makes it easy and fun to trade between friends.  We also plan on creating a Wizard of Dog themed NFT where people can buy NFT's of there dogs as Wizards.

• How is the token being distributed? Are you conducting an airdrop? 
We are distributing completely through DEX exchanges.  Most the volume is on Uniswap but we also have some small liquidity pools on Sushi, pancake and base swap as well.

• Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?
No ICO

• Is the token listed on a centralized/decentralized exchange?
Uniswap, Pancakeswap, Baseswap, and Sushiswap

• Is a Smart Contract audit completed? Where can we find this information?  Only the free audits currently that can be found on sites like DEXtools.

**Comment by Cryptocool1** [comment]
Hello, we require full smart contract audit from reputable companies (such as Techrate, Certik, Hacken, Dessert Finance)
Feel free to create new PR once audit is done. 
make sure to mention new PR in this one so the fee can be reused.

**Pull request closed without merging**
