### PR TITLE
Add THE BULLS ARMY (POLYGON)

### PR DESCRIPTION
**Pull request by xbrlab**
Adding info for POLYGON token 'THE BULLS ARMY'.

PR created by <a href="https://assets.trustwallet.com">TW Assets Management</a>

### CODE REVIEW

**Comment by xbrlab** [comment]
Fee is already paid: https://github.com/trustwallet/assets/pull/27784, Mentioning this PR so the fee can be reused.

Thanks

**Comment by Cryptocool1** [comment]
• What is the purpose of this token? How will it benefit Trust Wallet users?
 • How is the token being distributed? Are you conducting an airdrop?
 • Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?
 • Is the token listed on a centralized/decentralized exchange?
 • Is a Smart Contract audit completed? Where can we find this information?

**Comment by xbrlab** [comment]
The Bulls Army is a meme coin, its purpose is to showcase the speed and affordability of the Matic blockchain to crypto users. Despite its lack of functionality, it serves as a playful representation of the bullish sentiment in the crypto market. To help TBA holders that are trust wallet users to track their holdings.

The token is being swap on Uniswap exchange, no there is no airdrop.

No, No ICO and any token presale.

Yes, it's listed on the Uniswap.

https://gopluslabs.io/token-security/137/0x7e1AE068Ac4e0ffD7a84750c2FB093A0EAE9aEa2

**Comment by xbrlab** [comment]
@Cryptocool1 provided the info, please do the needful.

Thanks

**Pull request closed without merging**
