### PR TITLE
Add Defi Tiger Logo and Info

### PR DESCRIPTION
**Pull request by DefiTigertoken**

### CODE REVIEW

**Comment by Cryptocool1** [comment]
• What is the purpose of this token? How will it benefit Trust Wallet users?
 • How is the token being distributed? Are you conducting an airdrop?
 • Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?
 • Is the token listed on a centralized/decentralized exchange?
 • Is a Smart Contract audit completed? Where can we find this information?

**Comment by DefiTigertoken** [comment]
• What is the purpose of this token? How will it benefit Trust Wallet users?
DTG is a Decentralized Meme Asset driven by a community Of Defi Enthusiasts with a unique love for felines. We are driven to support the care and conservation efforts for Bengal Tigers whose numbers in the wild have dropped drastically, thus pushing us to reserve a share of our token to the support of conservation efforts towards these majestic creatures. We are also big on full DeFi adoption by the larger global community, and because of this we are planning on building a blockchain that boasts a fast and cheap architecture; that can be fully integrated in the larger society and give people freedom to spend their income without fear of centralization.

• How is the token being distributed? Are you conducting an airdrop?
The token has already been distributed. There was no airdrop. It was sent to pancakeswap for the general public to buy.

• Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?
There was no presale or initial coin offering. We did a fair launch on July 4th 2022. All of the token was created and sent to pancakeswap.finance where liquidity was added and locked. We currently have over 10,000 holders since launch.

• Is the token listed on a centralized/decentralized exchange?
Yes it is listed on Pancakeswap.finance. Here is a link on coinmarketcap: https://coinmarketcap.com/currencies/defi-tiger/

• Is a Smart Contract audit completed? Where can we find this information?
No. We've made payment to solidity.finance for a smart contract audit in which report will be out before the end of this week.

**Comment by Cryptocool1** [comment]
We require smart contract audit. Awaiting for smart contract audit, on hold for now.

**Comment by DefiTigertoken** [comment]
Okay. We'll update here as soon as it's out. Thank you

**Comment by DefiTigertoken** [comment]
We've gotten our smart contract audit report by solidity.finance here: https://solidity.finance/audits/DefiTiger/  @Cryptocool1 @cryptomanz1

**Comment by Cryptocool1** [comment]
Thanks you. 
Are you listed on CoinMarketCap?

**Comment by DefiTigertoken** [comment]
Yes. Link here https://coinmarketcap.com/currencies/defi-tiger/

**Comment by DefiTigertoken** [comment]
@Cryptocool1 @cryptomanz1

**Pull request merged**
