### PR TITLE
update Harvest Finance multichain assets

### PR DESCRIPTION
**Pull request by brandoncurtis**
- [x] update logo and description of FARM on Ethereum
- [x] add FARM logo and description on BSC
- [x] add FARM logo and description on Matic
- [x] add iFARM logo and description on Ethereum
- [x] add iFARM logo and description on Matic

### CODE REVIEW

**Comment by silagepete** [comment]
To respond to concerns about number of holders, FARM is [issued on Ethereum](https://etherscan.io/token/0xa0246c9032bC3A600820415aE600c6388619A14D) where it has almost 10,000 holders. We have bridged it to Binance Smart Chain and Matic. The [BSC bridged token](https://bscscan.com/token/0x4B5C23cac08a567ecf0c1fFcA8372A45a5D33743) was released this week when Harvest Finance started farming on BSC. Number of holders today is small but it will increase rapidly as we expand BSC farming operations.

**Comment by brandoncurtis** [comment]
bot deleted this comment by @silagepete:
> To respond to concerns about number of holders, FARM is issued on Ethereum where it has [almost 10,000 holders](https://etherscan.io/token/0xa0246c9032bC3A600820415aE600c6388619A14D). We have bridged it to Binance Smart Chain and Matic. The [BSC bridged token](https://bscscan.com/token/0x4B5C23cac08a567ecf0c1fFcA8372A45a5D33743) was released this week when Harvest Finance started farming on BSC. Number of holders today is small but it will increase rapidly as we expand BSC farming operations.

Also to clarify, this PR updates metadata for the multichain deployment of FARM and also adds iFARM.  iFARM is the interest-bearing version of FARM, and works analogously to bBADGER, xSUSHI, and Aave's assets like aUSDC.  Users deposit FARM into the profitsharing pool and receive iFARM as a receipt.  It's basically the same asset, so I'm updating it now to save time in the future :+1:

**Comment by catenocrypt** [comment]
Correction needed: 
Please remove the matic token files (2x2 files), Trust Wallet does not currently support Matic tokens.

**Comment by brandoncurtis** [comment]
- [x] removed the Matic/Polygon assets

**Pull request merged**
