### PR TITLE
Add Logo Fwc

### PR DESCRIPTION
**Pull request by Qatar2022token**
Holders:
9,375 addresses
Transfers:
86,772

### CODE REVIEW

**Comment by Qatar2022token** [comment]
Please check thank you

**Comment by Qatar2022token** [comment]
Let us know if there is no problem so we can pay

**Comment by smart2022** [comment]
Holders:
11,464 addresses
Transfers:
108,741

**Comment by Qatar2022token** [comment]
Hi,Please check thank you Let us know if there is no problem so we can pay
      
        
        
          On Mar 25 2022, at 1:40 pm, merge-fee-bot[bot] ***@***.***> wrote:
          
        
        
          

Hi! In order to compensate for the efforts of processing PRs, we kindly ask for a contribution.

💀 As there is no refund, before paying the fee, make sure new tokens fulfill the minimum circulation and other acceptance criteria.

See also the PR Fee FAQ.

Please pay  1000 TWT  with the memo 19241  to the address bnb1tqq9llyr3dyjd559dha6z5r5etk3qfwk07m098.

Alternatively, 5 BNB is also accepted (same memo & address).

QR code: Trust | other wallet

Notes:



Trust Wallet Tokens (TWT) can be obtained through our Referral Program or from DEXs/exchanges.

New tokens without significant usage are rejected, see criteria mentioned above.

One PR should be for a single project; PR's with more than 10 logos will be rejected.

Payment evaluation happens automatically, but with a few minutes delay.  When payment is detected, an Accept Review is automatically placed on the PR, which is a condition for merge.

Evaluating the PR is done manually, and it is merged only if all conditions are satisfied.

TWT-BEP2 is supported (Binance Chain), TWT-BEP20 version on Smart Chain is not.



There will be a fee to process this request. None of it goes to the developers.

Before paying the fee, make sure new tokens fulfill the minimum circulation and other acceptance criteria.

If you are paying TWT for the submission, this will be burned automatically. There will be no refunds.

**Comment by smart2022** [comment]
fee paid
https://explorer.binance.org/tx/1BB848FB02ADF595B046ED1E53802FBF992F29CFF1F3EC514873082F34F8C70A
<https://github.com/trustwallet/assets/pull/url>

**Comment by cryptomanz** [comment]
• What is the purpose of this token? How will it benefit Trust Wallet users?
 • How is the token being distributed? Are you conducting an airdrop?
 • Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?
 • Is the token listed on a centralized/decentralized exchange?
 • Is a Smart Contract audit completed? Where can we find this information?

**Comment by Qatar2022token** [comment]
• What is the purpose of this token? 
The concept of this token is justice and equality
There is no fee
There is no tax

Qatar 2022 Token is a project that was created with the aim of bringing football and cryptocurrencies together so that users can enter the world of crypto football. FWC is a digital currency platform that allows users to create digital currencies while maintaining security and safety. We are currently integrating China Blockchain and NFT technologies for a better collective customer experience. Our platform is based on the Binance smart chain, which ensures the authenticity, traceability and immutability of digital assets. It also has a dynamic user interface and a customizable API to assist transactions.

FWC was created by people from a variety of backgrounds - from graphic designers and marketers to web developers and analysts - who share a passion for football and digital currency. The token can be used to purchase World Cup tickets, book hotels, use various related services, place bets and participate in lotteries. Furthermore, FWC will take its place in Metaverse and NFT football games.

FWC is a BEP-20 token designed for buying tickets to the World Cup, booking hotels, using various related services, placing bets, and participating in lotteries.

How will it benefit Trust Wallet users? 
FWC is a BEP-20 token designed for buying tickets to the World Cup, booking hotels, using various related services, placing bets, and participating in lotteries.
There is no fee
There is no tax

• How is the token being distributed? Are you conducting an airdrop? 
There is no airdrop

• Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale? 
There is no presale

• Is the token listed on a centralized/decentralized exchange? 
https://pancakeswap.finance/swap?outputCurrency=0x6d3a160b86edcd46d8f9bba25c2f88cccade19fc
https://geckoterminal.com/bsc/pools/0x32dea04d0579387f869e26c7e051dd80b24d76c0
https://www.dextools.io/app/bsc/pair-explorer/0x32dea04d0579387f869e26c7e051dd80b24d76c0
https://azbit.com/exchange/FWC_USDT
https://coinsbit.io/trade/FWC_mUSDT
https://coinmarketcap.com/currencies/qatar-2022-token/
https://www.altcoinmarket.co.uk/qatar2022token/
https://www.coingecko.com/en/coins/qatar-2022
https://coinmooner.com/coin/14491
https://swap.arken.finance/tokens/bsc/0x6d3a160b86edcd46d8f9bba25c2f88cccade19fc?side=BUY
gifinex.com/en-ww/trade/USDT/FWC
https://openocean.finance/classic#/BSC/BNB/FWC

https://support.bibox.jp/hc/en-us/articles/5169046533017(Bibox)
https://support.bmx.fund/hc/en-us/articles/4864139573915(Bitmart)
https://support.bmx.fund/hc/zh-cn/articles/4864139573915(Bitmart)



• Is a Smart Contract audit completed? Where can we find this information?
https://github.com/TechRate/Smart-Contract-Audits/blob/main/February/QATAR%202022%20TOKEN.pdf

**Comment by smart2022** [comment]
no  it`s mistake  #19241   is not for us we paid for Add Frz solar system
(BEP20) #19244
please fix it

**Comment by smart2022** [comment]
no  it`s mistake  #19241   is not for us we paid for Add Frz solar system
(BEP20) #19244
please fix it

fee paid with memo 19244 :
https://explorer.binance.org/tx/1BB848FB02ADF595B046ED1E53802FBF992F29CFF1F3EC514873082F34F8C70A
<https://github.com/trustwallet/assets/pull/url>

**Comment by smart2022** [comment]
this is scam   we paid for Add Frz solar system (BEP20) #19244
please fix it

fee paid with memo 19244 :
https://explorer.binance.org/tx/1BB848FB02ADF595B046ED1E53802FBF992F29CFF1F3EC514873082F34F8C70A
<https://github.com/trustwallet/assets/pull/url>

**Comment by smart2022** [comment]
no  it`s mistake  #19241   is not for us we paid for Add Frz solar system
(BEP20) #19244
please fix it

fee paid with memo 19244 :
https://explorer.binance.org/tx/1BB848FB02ADF595B046ED1E53802FBF992F29CFF1F3EC514873082F34F8C70A
<https://github.com/trustwallet/assets/pull/url>

**Comment by smart2022** [comment]
What is the purpose of this token? How will it benefit Trust Wallet users?
https://frzss.com/White-Paper/
How is the token being distributed? Are you conducting an airdrop? yes
https://www.instagram.com/4arzin/
Did you sold the tokens at an Initial Coin Offering (ICO) or a token
presale? no
Is the token listed on a centralized/decentralized exchange?yes
several exchange
https://poocoin.app/tokens/0xac41fb8013c0b63588fc63997785a5d79e73eb28

https://hotbit.zendesk.com/hc/en-us/articles/4670680779031

https://t.me/coinsbit_announcements/2731

https://t.me/azbit_news/877

https://t.me/IndoEx/1860
 Is a Smart Contract audit completed? Where can we find this information?
https://coinmarketcap.com/currencies/frz-solar-system/


I don't know how but you merged Fwc #19241
<https://github.com/trustwallet/assets/pull/19241>   this is not our token
and we are not pay for fwc  we paid for
Add Frz solar system (BEP20) #19244
please fix it

fee paid with memo 19244 :
https://explorer.binance.org/tx/1BB848FB02ADF595B046ED1E53802FBF992F29CFF1F3EC514873082F34F8C70A
<https://github.com/trustwallet/assets/pull/url>

**Comment by smart2022** [comment]
I don't know how but you merged [Fwc #19241](https://github.com/trustwallet/assets/pull/19241)   this is not our token and we are not pay for fwc  we paid for  Add Frz solar system (BEP20) #19244
please fix it  you merged wrong Fwc you should merge Frz solar system (BEP20) #19244

fee paid with memo 19244 : https://explorer.binance.org/tx/1BB848FB02ADF595B046ED1E53802FBF992F29CFF1F3EC514873082F34F8C70A
<https://github.com/trustwallet/assets/pull/url>

**Comment by smart2022** [comment]
please report to merge-fee-bot that its a mistake and I don't know how but
you merged Fwc #19241 <https://github.com/trustwallet/assets/pull/19241>
 this is not our token and we are not pay for fwc  we paid for Add Frz
solar system (BEP20) #19244
please fix it

fee paid with memo 19244 :
https://explorer.binance.org/tx/1BB848FB02ADF595B046ED1E53802FBF992F29CFF1F3EC514873082F34F8C70A
<https://github.com/trustwallet/assets/pull/url>

**Comment by smart2022** [comment]
Hello
I don't know how but you merged Fwc #19241
<https://github.com/trustwallet/assets/pull/19241> this is not our token
and we are not pay for fwc we paid for
Add Frz solar system (BEP20) #19244
please fix it

fee paid with memo 19244 :
https://explorer.binance.org/tx/1BB848FB02ADF595B046ED1E53802FBF992F29CFF1F3EC514873082F34F8C70A
<https://github.com/tsunamayo/Starship-EVO/issues/url>
https://github.com/trustwallet/assets/pull/url
please fix it & merge Add Frz solar system (BEP20) #19244

thank you so much for your Attention.

**Comment by smart2022** [comment]
Hello

I don't know how but you merged Fwc #19241
<https://github.com/trustwallet/assets/pull/19241> this is not our token
and we are not pay for fwc we paid for
Add Frz solar system (BEP20) #19244
please fix it

fee paid with memo 19244 :
https://explorer.binance.org/tx/1BB848FB02ADF595B046ED1E53802FBF992F29CFF1F3EC514873082F34F8C70A
<https://github.com/tsunamayo/Starship-EVO/issues/url>
https://github.com/trustwallet/assets/pull/url
please fix it & merge Add Frz solar system (BEP20) #19244

thank you so much for your Attention.

**Comment by smart2022** [comment]
Hi please merge  #19244

**Comment by smart2022** [comment]
Hello
5 BNB for fee paid transaction hash :
1BB848FB02ADF595B046ED1E53802FBF992F29CFF1F3EC514873082F34F8C70A number of
holders : Holders: 11,505 addresses ------------------------------
Transfers: 110,811 please check and accept info & logo Thank you so much

**Pull request merged**
