### PR TITLE
Update DogeGF info and token logo

### PR DESCRIPTION
**Pull request by DogeGF-Token**
Hello,

We would like to update our logo and information for the DogeGF token which is already listed in the repository.

These changes can also be verified on:

CoinGecko - https://www.coingecko.com/en/coins/dogegf
CoinMarketCap - https://coinmarketcap.com/currencies/dogegf/

### CODE REVIEW

**Comment by DogeGF-Token** [comment]
Is it okay to proceed with the payment @Cryptocool1 ?

**Comment by cryptomanz1** [comment]
As per our policy, there is a minimum requirement of 10,000 holder addresses and 15,000 transactions.
See the criteria at : https://developer.trustwallet.com/listing-new-assets/requirements .

**Comment by cryptomanz1** [comment]
• What is the purpose of this token? How will it benefit Trust Wallet users?
 • How is the token being distributed? Are you conducting an airdrop?
 • Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?
 • Is the token listed on a centralized/decentralized exchange?
 • Is a Smart Contract audit completed? Where can we find this information?

**Comment by DogeGF-Token** [comment]
DogeGF is an innovative blockchain meme project that stands at the crossroads of cryptocurrency and community spirit. Built on a foundation of reciprocity, DogeGF aims to redefine the meme coin landscape by promoting acts of kindness and mutual support among its users. Trust Wallet users will benefit from DogeGF by participating in a community-driven project that encourages positive actions and fosters a supportive environment within the crypto space.

DogeGF was distributed initially by adding liquidity when the token was first created. There has been no airdrop for DogeGF.

There was no ICO or token presale for DogeGF.

DogeGF is listed on decentralized exchanges (DEXs) such as Uniswap and Sushiswap.

The DogeGF smart contract has been audited. The audit report can be found on our website: https://www.dogegf.com/
Direct link to the audit: https://sourcehat.com/audits/DogeGF/

**Pull request merged**
