### PR TITLE
Add BleuFi (BEP20)

### PR DESCRIPTION
**Pull request by bluefibsc**
Adding info for BEP20 token 'BleuFi'.

PR created by <a href="https://assets.trustwallet.com">TW Assets Management</a>

### CODE REVIEW

**Comment by bluefibsc** [comment]
Ok, I think that now is done correctly.

The fee's have been paid already.

If you need me to pay again, I will do it. Sorry for my mistakes.
________________________________

**Comment by Cryptocool1** [comment]
> Ok, I think that now is done correctly. The fee's have been paid already. If you need me to pay again, I will do it. Sorry for my mistakes.
> […](#)

hello, in what PR you paid the fee?

**Comment by bluefibsc** [comment]
Hi,

PR # 17305

________________________________

**Comment by Cryptocool1** [comment]
hello, your logo should be 256/256. please change

**Comment by bluefibsc** [comment]
Hi, do I have to create another PR for this?
________________________________

**Comment by cryptomanz** [comment]
• Is a Smart Contract audit completed? Where can we find this information?

**Comment by bluefibsc** [comment]
We are undergoing our audit, you can find it here.

https://www.certik.com/projects/bleufi
[https://www.certik.com/api/card/bleufi.jpg]<https://www.certik.com/projects/bleufi>
BleuFi - CertiK Security Leaderboard<https://www.certik.com/projects/bleufi>
Stay up to date with the latest security insights on BleuFi: Smart Contract Audit, Skynet Scores, Security Oracle, CertiKShield and many more security-focused statistics.
www.certik.com

________________________________

**Pull request merged**
