### PR TITLE
Add DeMi (BEP20)

### PR DESCRIPTION
**Pull request by DEMI-mining**
Adding info for BEP20 token 'DeMi'.

PR created by <a href="https://assets.trustwallet.com">TW Assets Management</a>

### CODE REVIEW

**Comment by DEMI-mining** [comment]
https://skynet.certik.com/projects/demi

**Comment by Cryptocool1** [comment]
As per our policy, brand new tokens are not included, there is a minimum requirement of 10,000 holder addresses and 15,000 transactions
See the criteria at : https://developer.trustwallet.com/assets/requirements .

**Comment by DEMI-mining** [comment]
> As per our policy, brand new tokens are not included, there is a minimum requirement of 10,000 holder addresses and 15,000 transactions See the criteria at : https://developer.trustwallet.com/assets/requirements .

It is not a brand new token:
7 months
10K transactions. 

and hashrate is growing, now ~ 100 petahash!
image

image

Listed on CMC and Coingecko. 

**Since user needs to stake it in order to get a daily reward there will never be many holders**
image

**Comment by DEMI-mining** [comment]
@Cryptocool1

**Comment by cryptomanz1** [comment]
Feel free to come back to us once all criteria are met. Make sure to mention this PR so the fee can be reused.

**Comment by DEMI-mining** [comment]
DEMI is an RWA project for tokenizing hashrate, with each token tied to the power of the equipment. Check it out here: https://coinmarketcap.com/currencies/demi/ We can't conduct airdrops or fake transactions to inflate activity. We have completed audits with Certik, have genuine large holders, and mentions in major publications. The project is growing organically. Could you reconsider your requirements for projects like ours?

**Pull request closed without merging**
