### PR TITLE
Add LON token logo

### PR DESCRIPTION
**Pull request by p0s**
Adding the logo for the LON token. 

https://etherscan.io/token/0x0000000000095413afc295d19edeb1ad7b71c952

### CODE REVIEW

**Comment by p0s** [comment]
Paid.

**Comment by p0s** [comment]
@catenocrypt @zachzwei could you please check and merge? We want people to be able to see the correct token on Uniswap.

**Comment by catenocrypt** [comment]
Please add an `info.json` file next to the `logo.png`, with info about the project, of the form:

```json
{
    "name": "Trust Wallet Token",
    "website": "https://trustwallet.com",
    "short_description": "Utility token to increase adoption of cryptocurrency.",
    "explorer": "https://etherscan.io/token/0xA866F0198208Eb07c83081d5136BE7f775c2399e",
    "socials": [
        {
            "name": "Twitter",
            "url": "https://twitter.com/trustwalletapp",
            "handle": "TrustWalletApp"
        },
        {
            "name": "Reddit",
            "url": "https://reddit.com/r/trustapp",
            "handle": "TrustApp"
        }
    ]
}
```

**Comment by p0s** [comment]
@catenocrypt I added the info.json as well

**Comment by catenocrypt** [comment]
Thanks.  Checks OK, merging.

**Pull request merged**
