### PR TITLE
Change MTW Logo

### PR DESCRIPTION
**Pull request by METAWHALEWORLD**
Please Change MTW Logo

Fee Already Paid We Need To Change Logo

Fee Paid Ref PR #19007

### CODE REVIEW

**Comment by METAWHALEWORLD** [comment]
Our MTW  old Logo Was Not Proper Set , Its Harm to expand Our Project

So, Please Change Our Logo 

As early as possible

**Comment by Cryptocool1** [comment]
hello, you should pay the fee for updating
see the requirements here: https://developer.trustwallet.com/assets/pr-fee

**Comment by METAWHALEWORLD** [comment]
ok we will pay don't close the PR

**Comment by METAWHALEWORLD** [comment]
Please Change Logo, Fee are Paid and Merge this PR

**Pull request merged**
