### PR TITLE
Winr protocol

### PR DESCRIPTION
**Pull request by WINRLabs**

### CODE REVIEW

**Comment by WINRLabs** [comment]
Dear Anastasiia,

Sorry to reach you just before the weekend. 
I wanted to reach out to you regarding the evaluation of our assets.

As per the initial criteria provided, we were required to have a minimum of 5,000 token holders and 15,000 transactions, with a note that the requirement was subject to review based on the project. Unfortunately, we were informed that we did not meet the criteria as our number of token holders was slightly below the specified limit.

However, we recall that the initial criteria were subject to review based on the project, and we would like to respectfully inquire whether our project was eliminated based solely on the review of the specified criteria, or whether there were additional factors that influenced the decision.

We would appreciate any additional information you could provide to help us understand the decision and to determine whether there are any opportunities to reapply in the future.

Thank you for your time and attention to this matter.

@Cryptocool1

**Comment by Cryptocool1** [comment]
Hello again
Please share an answers for the following questions:
• What is the purpose of this token? How will it benefit Trust Wallet users?
 • How is the token being distributed? Are you conducting an airdrop?
 • Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?
 • Is the token listed on a centralized/decentralized exchange?
 • Is a Smart Contract audit completed? Where can we find this information?

**Comment by WINRLabs** [comment]
1. WINR serves as an integral component of our decentralized gaming infrastructure platform, providing a mechanism for platform earnings to be distributed proportionally to token holders. Using the dual token model outlined in our documentation, winnings from games created on the platform are distributed to the WINR/vWINR staking pool according to the dimensions determined by our DAO. By holding WINR tokens, users can earn shares of the platform's earnings. In this way, the WINR token creates an ecosystem in which users are incentivized to participate in the platform and share in its success.

Please find the details in here: 
https://docs.winr.games/incentive-model/token-winr-vwinr

2.The distribution of the WINR token involves a combination of a public sale, private sale, and staking rewards. While we do not have an airdrop currently planned for WINR, we did organize an airdrop for vWINR, which is the twin token of WINR. Please note that vWINR tokens cannot be transferred or converted into WINR until 180 days have passed.

Please find the details of Tokenomics in the link
https://docs.winr.games/tokenomics


3. Yes, WINR has successfully completed both a pre-sale and public sale. The pre-sale was conducted through our VC company network and included 175,000,000 vWINR and WINR tokens that are claimable on a daily basis for two years. In addition, we held a public sale on Camelot Exchange, offering 100,000,000 WINR tokens to the public.

https://app.camelot.exchange/launchpad/winr

4.  WINR is currently listed on decentralized exchanges such as Camelot DEX and Uniswap V3, as well as centralized exchange BKEX. We are also in the process of finalizing agreements with Huobi and Gate.io for listing. We strive to make WINR accessible to users on as many reputable exchanges as possible to increase its liquidity and trading volume.

https://coinmarketcap.com/currencies/winr-protocol/

5. We take the security and reliability of our platform very seriously, which is why we have enlisted the help of industry-leading auditing firms, Paladin and Watchpug, to review and supervise our platform contracts. Our completed contracts, including tokens, can be found in the documentation linked below.

audit is attached
@Cryptocool1 

[20230303_Paladin_WINRWhitelistPool_Final_Report (2).pdf](https://github.com/trustwallet/assets/files/11131602/20230303_Paladin_WINRWhitelistPool_Final_Report.2.pdf)

**Comment by WINRLabs** [comment]
We were cruios, were you able to reach a conclusion regarding your investigation, is there any further details we can provide?

@Cryptocool1

**Pull request closed without merging**
