### PR TITLE
Add BEP20 BunnyToken

### PR DESCRIPTION
**Pull request by pancakebunny-dev**

### CODE REVIEW

**Comment by catenocrypt** [comment]
Submission OK.  Merging.

**Comment by pancakebunny-dev** [comment]
@catenocrypt Thank you for merging BSC BEP20, Bunny Token. I'd be appreciated if BUNNY can be listed on tokenlist.json. Should I make a new pull request for adding tokenlist?

**Comment by catenocrypt** [comment]
You mean to show up in swap?  We update that list occasionally, but it is filtered with a limit on liquidity&volume.  It will be included when it falls into the filtered set; I will not put special treatment to this token.

**Comment by pancakebunny-dev** [comment]
@catenocrypt Thank you for your response. Yes, I mean to show up in swap. BUNNY has just passed liquidity&volume - I've run and checked it on my machine -, so I'll looking forward to running your script.
By the way, in order to update the token list, I had to change the PancakeSwap_TradingPairsUrl. https://api.bscgraph.org/subgraphs/name/wowswap didn't work, so I ran the script with cakeswap.

**Comment by catenocrypt** [comment]
Thanks for the note on the API, updated.

**Comment by catenocrypt** [comment]
Sorry, current Bunny liquidity is below limit (usd 569,891).

**Comment by pancakebunny-dev** [comment]
@catenocrypt The graph node looks to be historical data. The pancakeswap.info site has been in sync since a week ago. 
Bunny liquidity is definitely over the limit, please see the pool address. https://bscscan.com/address/0x7bb89460599dbf32ee3aa50798bbceae2a5f7f6a

**Comment by catenocrypt** [comment]
By liquidity I meant liquidity on the Pancakeswap trading pair.  It is currently $656k.  It will be added sometime after it goes above $1m.

```
pair with low liquidity: WBNB -- BUNNY    656039
```

**Comment by pancakebunny-dev** [comment]
That's right, liquidity means fair liquidity of pancake swaps.
I mean, the graph server is in sync now, so your script is showing past data. lol
Current liquidity is at least $4M. Please see the attached files, and links.

1) BUNNY-BNB Pair Address: https://bscscan.com/address/0x7bb89460599dbf32ee3aa50798bbceae2a5f7f6a
2) pancakeswap.info BUNNY: https://pancakeswap.info/token/0xc9849e6fdb743d08faee3e34dd2d1bc69ea11a51

bunny token
bunny-bnb pair

**Comment by catenocrypt** [comment]
It is strange that the API returns different numbers.
I have added BUNNY with https://github.com/trustwallet/assets/pull/5798 . Note though, that it may get removed with later updates...

**Pull request merged**
