### PR TITLE
Add info and logo of ULTI Coin

### PR DESCRIPTION
**Pull request by ultiarenacom**

### CODE REVIEW

**Comment by cryptomanz** [comment]
Hello,
Can your answer some questions?
• What is the purpose of this token? How will it benefit Trust Wallet users?
 • How is the token being distributed? Are you conducting an airdrop?
 • Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?
 • Is the token listed on a centralized/decentralized exchange?
 • Is a Smart Contract audit completed? Where can we find this information?

**Comment by ultiarenacom** [comment]
Hi @cryptomanz ! :) 
Sure thing. Here are answers for your questions: https://drive.google.com/file/d/1pNGHbSPeXd1OZFPjE4_JxEACO4S5P57B/view

**Comment by ultiarenacom** [comment]
@catenocrypt, @cryptomanz, @zachzwei, @Cryptocool1 any news from you guys?
 Is everything ok with the answers?

**Comment by cryptomanz** [comment]
can you please add links to your PR?
example: 
{
     "name": "ULTI Coin",
     "type": "BEP20",
     "symbol": "ULTI",
     "decimals": 18,
     "website": "https://ultiarena.com/",
     "description": "Ulti Arena - NFT Marketplace for Game Assets with Proof of Gaming and Trading Card Game.",
     "explorer": "https://bscscan.com/token/0x42BFE4A3E023f2C90aEBFfbd9B667599Fa38514F",
     "status": "active",
     "id": "0x42BFE4A3E023f2C90aEBFfbd9B667599Fa38514F",
     "links": [
         {
             "name": "twitter",
             "url": "..."
         },
         {
             "name": "telegram",
             "url": "..."
         },
         {
             "name": "medium",
             "url": "..."
         },
         {
             "name": "whitepaper",
             "url": "..."
         },
         {
             "name": "facebook",
             "url": "..."
         },
         {
             "name": "github",
             "url": "..."
         }
     ]
 }

**Comment by ultiarenacom** [comment]
@cryptomanz  done :)

**Pull request merged**
