### PR TITLE
Add Cryptostone (BEP20)

### PR DESCRIPTION
**Pull request by crypto-stone**
Adding info and logo for BEP20 token Cryptostone Token (CPS).

### CODE REVIEW

**Comment by crypto-stone** [comment]
> tag 'platform' is not allowed

tag is 'staking-native'

**Comment by crypto-stone** [comment]
open

**Comment by cryptomanz1** [comment]
• What is the purpose of this token? How will it benefit Trust Wallet users?
 • How is the token being distributed? Are you conducting an airdrop?
 • Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?
 • Is the token listed on a centralized/decentralized exchange?
 • Is a Smart Contract audit completed? Where can we find this information?

**Comment by crypto-stone** [comment]
**• What is the purpose of this token? How will it benefit Trust Wallet users?**
CPS is the native utility token of the Cryptostone project.
We have more than 4k ICO participants and more than 35K community members; as you can see on the project website, we suggested the community members use TrustWallet and Metamask for receiving their tokens, so many of them are using TrustWallet.
The community has asked the project team to add the token logo to TrustWallet to avoid mistakes.

**• How is the token being distributed? Are you conducting an airdrop?**
We have a detailed Token Distribution Plan:
https://www.crypto-stone.io/token-distribution/
Airdrop bounty tokens have not been distributed yet.

**• Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?**
Yes, We have more than 4k ICO participants, with a total of more than 2 million dollars raised fund.
The ICO is over, and the pre-sale tokens are being distributed based on the whitepaper.

**• Is the token listed on a centralized/decentralized exchange?**
Yes, LBanK, XT, PanCakeSwap
You can find them below:
https://coinmarketcap.com/currencies/cryptostone/markets/

**• Is a Smart Contract audit completed? Where can we find this information?**
Yes, Audited by Certik
https://www.certik.org/projects/cryptostone

@cryptomanz1

**Pull request merged**
