### PR TITLE
Add human charity coin info

### PR DESCRIPTION
**Pull request by CryptoLover705**

### CODE REVIEW

**Comment by catenocrypt** [comment]
Payment considered from #7403, 250 TWT, https://explorer.binance.org/tx/E3C025B07C411B351D65B570A9D75D71F34545F7FE9C1E79316CDA0ADE7E69BA

**Comment by CryptoLover705** [comment]
Hey, I followed the guide I got sent, I am trying to add a coin but every time I get this same message, How can I fix it please ?

**Comment by catenocrypt** [comment]
Location of the files incorrect, correct should be:

if this is an Ethereum ERC20 token: `blockchains/ethereum/assets/<contractID>`
if this is a Binance Smart Chain BEP20 token: `blockchains/smartchain/assets/<contractID>`

**Comment by CryptoLover705** [comment]
Hey it is not a token, it is a standalone blockchain, that is why I was putting it where I was, if that is wrong please let me know the right place to put that

Thanks in advance

**Comment by catenocrypt** [comment]
Support for standalone blockchains is much more than just adding a logo.  See here, especially criteria:

https://developer.trustwallet.com/wallet-core/newblockchain

**Pull request closed without merging**
