### PR TITLE
Added WENLAMBO logo and info

### PR DESCRIPTION
**Pull request by Wenlambo**
Minimum requirements have been met to update logo information

### CODE REVIEW

**Comment by Cryptocool1** [comment]
Correction needed:
This is a BEP20 token, correct folder is blockchains/smartchain/assets. Please correct.

**Comment by Wenlambo** [comment]
> Correction needed:
> This is a BEP20 token, correct folder is blockchains/smartchain/assets. Please correct.

thank you for your help i have now put in the correct folder, can you confirm?

**Comment by Wenlambo** [comment]
> File not allowed: blockchains/smartchain/0xd8a31016cd7da048ca21ffe04256c6d08c3a2251/info.json. Please revert it.
> File not allowed: blockchains/smartchain/0xd8a31016cd7da048ca21ffe04256c6d08c3a2251/logo.png. Please revert it.
 why i am receiving this error?

**Comment by Cryptocool1** [comment]
PR should include only 2 files:
blockchains/binance/assets/0xd8a31016cd7da048ca21ffe04256c6d08c3a2251/logo.png
blockchains/smartchain/0xd8a31016cd7da048ca21ffe04256c6d08c3a2251/info.json

**Comment by Cryptocool1** [comment]
Correction needed:
This is a BEp20 token, correct folder is blockchains/smartchain/assets. Please correct.

**Comment by Wenlambo** [comment]
can you confirm that i need to modify the checksum format?

**Comment by Cryptocool1** [comment]
Hello, 
your contract should be in checksum format  0xd8A31016cD7da048ca21FFE04256C6d08C3A2251

**Comment by Wenlambo** [comment]
hi there i have updated the string as per request and i have re-updated files.

**Comment by Wenlambo** [comment]
> Hello,
> your contract should be in checksum format 0xd8A31016cD7da048ca21FFE04256C6d08C3A2251

thank you i have changed in the above format but i still get the error..

**Comment by Wenlambo** [comment]
> PR should include only 2 files

thank you i am trying to delete the other files, but doesn't seems i am able to.-

**Comment by Cryptocool1** [comment]
> > PR should include only 2 files
> 
> thank you i am trying to delete the other files, but doesn't seems i am able to.-
If you can't rename files in the PR, you may open a new PR. You can create new PR using this app https://assets.trustwallet.com/index.html?token=

**Comment by Wenlambo** [comment]
> > > PR should include only 2 files
> > 
> > 
> > thank you i am trying to delete the other files, but doesn't seems i am able to.-
> > If you can't rename files in the PR, you may open a new PR. You can create new PR using this app https://assets.trustwallet.com/index.html?token=

i am having still same issue

**Comment by Wenlambo** [comment]
> 0xd8a31016cd7da048ca21ffe04256c6d08c3a2251/logo.png

i have done it, what should i do next?

**Pull request closed without merging**
