### PR TITLE
Add iBNB logo and info

### PR DESCRIPTION
**Pull request by emaulercrypto**
Add iBNB logo and info

### CODE REVIEW

**Comment by Cryptocool1** [comment]
hello,
what is the purpose of your token?

**Comment by emaulercrypto** [comment]
> hello,
> what is the purpose of your token?

iBNB is the first dynamic DeFi token, with a reward pool generating protocol built on the Binance Smart Chain. It aims to fix the volume-to-BNB pool refill rate that has seen other tokens lose value during sustained periods of low volume. It provides sustainable BNB Rewards to holders the first of its kind. 

Whitepaper https://ibnb-finance.gitbook.io/ibnb-whitepaper/

**Comment by emaulercrypto** [comment]
> hello,
> what is the purpose of your token?

Hello Cryptocool1, 

Forgot to add the Techrate audit that was submitted and passed. Thank you for your assistance. 
[iBNB_Standart_Smart_Contract_Security_Audit.pdf](https://github.com/trustwallet/assets/files/6738333/iBNB_Standart_Smart_Contract_Security_Audit.pdf)

**Comment by emaulercrypto** [comment]
Hello, just wanted to follow up if there were any updates on the request? Please let me know if anymore information is needed. Thank you for your assistance.

**Comment by emaulercrypto** [comment]
Hello again, just wanted to see if there were any updates since yesterday? Thank you for your time.

**Comment by emaulercrypto** [comment]
Hi everyone, just wanted to follow up and see if there were any updates to this logo request. I sent the Whitepaper and TechRate Audit that had a passing score in response to the purpose of iBNB. If you need any additional info to approve please let me know? Thank you again for taking the time to review this request.  Have a good day.

**Comment by emaulercrypto** [comment]
Hey just wanted to see if there were any updates to my submission? iBNB is the first dynamic DeFi token with a dynamic tax protocol that provides sustainable BNB rewards just for holding. It’s a real project created from the ground up. I posted the white paper a few comments up. Check it out. Also the other post is a link to the TechRate audit with a passing score. Thanks for your time hope to get a response soon.

**Comment by Cryptocool1** [comment]
Hello, it will be on hold until CMC listing

**Comment by Cryptocool1** [comment]
please create new PR when your token will be listed on CMC
make sure to mention this PR so that fee can can be reused

**Comment by emaulercrypto** [comment]
I would just like to know why you are asking for us to list on CMC before logo is approved? We have been audited and have been out for more than a week holding a ~$2 Million Market cap and yet you are still approving tokens that have rugged or died in a day. Also, before you can list on CMC you need to have a Trust logo so I feel like I am being put through a catch 22. Can you please elaborate on your reasoning as meme coins continue to get approved whereas a project like this is not? Thank you for your time.

**Pull request closed without merging**
