### PR TITLE
Add Catcoin V2

### PR DESCRIPTION
**Pull request by OnePanthera**
Please add Catcoin V2

### CODE REVIEW

**Comment by cryptomanz** [comment]
Its your old  ```id = 0x3B3691d4C3EC75660f203F41adC6296a494404d0```?

**Comment by OnePanthera** [comment]
> Is it your old `id = 0x3B3691d4C3EC75660f203F41adC6296a494404d0`?

Yes, that's the old V1. We're migrating to a new contract

**Comment by cryptomanz** [comment]
can you send an official announcement about migration ?

**Comment by OnePanthera** [comment]
> can you send an official announcement about migration?
[You can find references from our official Twitter and website:
](https://twitter.com/catcoinbsc/status/1518197519351693312?s=21&t=zLSUDxxXF-8kj5c0jeoLPw)

**Comment by SirisGitHub** [comment]
For some reason on trust wallet it says "Catcoin Token V2"

It should only be "Catcoin" as the contract states.

If you could help protect investors by removing the V1 catcoin status and giving us "Catcoin" only that would be perfect.

Thanks in advance. 

If you need an example, CMC just done this.


https://coinmarketcap.com/currencies/catcoin-token/

**Comment by SirisGitHub** [comment]
> Is it your old `id = 0x3B3691d4C3EC75660f203F41adC6296a494404d0`?

image (CMC)

That is the old and we really need to inform investors to stay away from the V1.

V1 was audited by Certik and had some major issues including liquduity being unlocked in December.

Can you PLEASE delist V1 from Trust Wallet or change the name to "CATCOIN V1 DEAD" 

V2 should just be named "Catcoin" as the contract states

Thank you so much!

**Pull request merged**
