### PR TITLE
Add TITAN logo and info

### PR DESCRIPTION
**Pull request by titanwarnft**
A Decentralized Gaming Play to Earn Token Based On Binance Smart Chain.

### CODE REVIEW

**Comment by Cryptocool1** [comment]
As per our policy, brand new tokens are not included, there is a minimum requirement of 5000 holder addresses and 10000 transactions, in order to filter out scam tokens.
See the criteria at: https://community.trustwallet.com/t/how-to-submit-a-token-logo/3863).

**Comment by titanwarnft** [comment]
> As per our policy, brand new tokens are not included, there is a minimum requirement of 5000 holder addresses and 10000 transactions, in order to filter out scam tokens.
> See the criteria at: https://community.trustwallet.com/t/how-to-submit-a-token-logo/3863).

Hi,

We are now reaching almost 9,500 Holders with 10,700 transactions on our smartcontract. You can check them out here.

https://bscscan.com/token/0x76f34cd142ca4a5ea2e197ebffbf5234a1c29268

**Comment by titanwarnft** [comment]
Hello,

May I ask if what I need to correct to our submitted files? Because it shows that "to correction" remarks on our pull request. Please check. Thank you. Also, We have reached already the 10,000 minimum transactions from our token and also we have 9,500 Token holders.

**Comment by Cryptocool1** [comment]
- Contract is not in checksum format, should be 0x76F34cd142ca4a5ea2E197ebffbF5234A1c29268 (not 0x76f34cd142ca4a5ea2e197ebffbf5234a1c29268). Please rename it.

**Comment by titanwarnft** [comment]
Hello, 

How can we rename the checksum format in temp name? We need help and instruction how to do it. Thank you.

**Comment by Cryptocool1** [comment]
please create new PR. go to https://assets.trustwallet.com, log on with Github, enter contract ID, logo and some additional info, and it will create a PR for you.
make sure to mention this PR, so the fee can be reused

**Pull request closed without merging**
