### PR TITLE
Add Starfish OS (BEP20)

### PR DESCRIPTION
**Pull request by starfishos**
Adding info for BEP20 token 'Starfish OS'.

PR created by <a href="https://assets.trustwallet.com">TW Assets Management</a>

### CODE REVIEW

**Comment by Cryptocool1** [comment]
Hello, how did you get 10.000 holders in 10 days?

**Comment by Cryptocool1** [comment]
• What is the purpose of this token? How will it benefit Trust Wallet users?
 • How is the token being distributed? Are you conducting an airdrop?
 • Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?
 • Is the token listed on a centralized/decentralized exchange?
 • Is a Smart Contract audit completed? Where can we find this information?

**Comment by GlobalHumanBeing** [comment]
My PR Summary show below error how I will remove it manually
Best Regards,
Muhammad Shahid
ECO and Founder of Global Human Being (GHB)

Token check error:
❌ number of holders not checked: please, check it manually

**Comment by starfishos** [comment]
1. game management token, which can be used by users to purchase NFT

2. play games every day without airdrop

3. no ICO and pre-sale

4. it has been listed in pancakeswap

5. the audit has been completed. Audit link:
https://www.certik.com/projects/starfish-os?utm_source=CMC&utm_campaign=AuditByCertiKLink
@Cryptocool1

**Comment by Cryptocool1** [comment]
> Hello, how did you get 10.000 holders in 10 days?

Can you answer this question?

**Comment by starfishos** [comment]
> > Hello, how did you get 10.000 holders in 10 days?
> 
> Can you answer this question?

We have a huge community and have done a lot of foreshadowing in the early stage

**Pull request merged**
