### PR TITLE
Add S M Properties (BEP20)

### PR DESCRIPTION
**Pull request by smptoken**
Adding info for BEP20 token 'S M Properties'.

PR created by <a href="https://assets.trustwallet.com">TW Assets Management</a>

### CODE REVIEW

**Comment by smptoken** [comment]
Is our all things is ok?, then we Start next step to payment.

**Comment by Cryptocool1** [comment]
• What is the purpose of this token? How will it benefit Trust Wallet users?
 • How is the token being distributed? Are you conducting an airdrop?
 • Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?
 • Is the token listed on a centralized/decentralized exchange?
 • Is a Smart Contract audit completed? Where can we find this information?

**Comment by smptoken** [comment]
1. S M Properties Is A Platform Powered By Binance Smart Chain. It's Created To Bring Real-World Assets On Blockchain. We Make Value From Real Estate Tokenomics, Flipping Properties Over Tangible Concepts. This token will help users to securely at our swap - SMEx SWAP, instantly using trust wallet.

2. We Directly provide liquidity at our Dex - https://smexswap.com/

3. No

4. Our token listed on a decentralized exchange SMEx SWAP - https://app.smexswap.com/

5. We applied for Audit but it is under review, can we proceed to add logo and info without Audit report?

**Comment by Cryptocool1** [comment]
we reuse smart contract audit fro reputable companies such as: Certik, Hacken, Techrate, Desser Finance. 
Please come back to us once all criteria are met

**Comment by smptoken** [comment]
Is everything fine except for the audit report?

**Comment by Athayde3586** [comment]
All critirias should be met and if u put another smart contract on my phone
and more money goes missing it's on yall

**Comment by smptoken** [comment]
> we reuse smart contract audit fro reputable companies such as: Certik, Hacken, Techrate, Desser Finance. Please come back to us once all criteria are met

Is everything fine except for the audit report?

**Comment by Cryptocool1** [comment]
Here is the requirements page -https://developer.trustwallet.com/assets/requirements

**Pull request closed without merging**
