### PR TITLE
add logo for BTCu

### PR DESCRIPTION
**Pull request by LBGK**

### CODE REVIEW

**Comment by Iamdeadlyz** [comment]
Hi @LBGK 

Please provide more details about this project.
https://community.trustwallet.com/t/how-to-submit-a-token-logo/3863#how-to-get-approved
You can follow this format when adding an info.json file:
```
{
   “name”:“Bitcoin”,
   “website”:“https://bitcoin.org”,
   “source_code”:“https://github.com/bitcoin”,
   “white_paper”:“https://bitcoin.org/bitcoin.pdf”,
   “short_description”:“Bitcoin is a cryptocurrency and worldwide payment system.“,
   “explorer”:“https://blockchain.info”,
   “research”:“https://research.binance.com/en/projects/bitcoin”
}

**Comment by LBGK** [comment]
does token details must be required? but we have paid for it.

**Comment by zachzwei** [comment]
> does token details must be required? but we have paid for it.

Please read this:
https://community.trustwallet.com/t/how-to-submit-a-token-logo/3863#how-to-get-approved

**Comment by LBGK** [comment]
> > does token details must be required? but we have paid for it.
> 
> Please read this:
> https://community.trustwallet.com/t/how-to-submit-a-token-logo/3863#how-to-get-approved

does new pr must be created?

**Comment by Iamdeadlyz** [comment]
> does new pr must be created?

Nope. Just commit to this pull request with the added info.json file.

**Comment by LBGK** [comment]
> > does new pr must be created?
> 
> Nope. Just commit to this pull request with the added info.json file.

ok, I just do it , thank you

**Pull request merged**
