### PR TITLE
Add AWT (BEP20)

### PR DESCRIPTION
**Pull request by awttokenapp**
Adding info for BEP20 token 'AWT'.

PR created by <a href="https://assets.trustwallet.com">TW Assets Management</a>

### CODE REVIEW

**Comment by Cryptocool1** [comment]
• What is the purpose of this token? How will it benefit Trust Wallet users?
 • How is the token being distributed? Are you conducting an airdrop?
 • Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?
 • Is the token listed on a centralized/decentralized exchange?
 • Is a Smart Contract audit completed? Where can we find this information?

**Comment by awttokenapp** [comment]
• What is the purpose of this token? How will it benefit Trust Wallet users?
 - AWT is a decentralized blockchain protocol that allow users to lend borrow selected cryptocurrency. It establishes money markets by polling assets together and algorithmically setting interest rates based on supply and demand of asset. 
We are developing a lot of features for our users, but only Trust wallet owners will be able to use them. As everyone is aware, this is a very reliable digital wallet, and we prefer having all of our customers use it. Because all functionality and exchanging will only occur through trust wallet, users of trust wallets will benefit first and foremost from this. And Awt is organising a well-designed stacking mechanism on top of the trust wallet.

• How is the token being distributed? Are you conducting an airdrop?
 - Tokens are currently being distributed by pancake swap and airdropped at a rate of 0.05% to our community, who have been waiting and supporting us since we began construction on this project in 2017.
 
• Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?
  - No, we did not participate in a pre-sale offer.

• Is the token listed on a centralized/decentralized exchange?
  - Indeed, this currency is listed on the Pancake Swap decentralised exchange. 
  
• Is a Smart Contract audit completed? Where can we find this information?
 - Yes AWT is audited with cointool audit team and here you can find audit report : https://awttoken.io/COINTOOL_AWT_AUDIT_REPORT.pdf

**Comment by awttokenapp** [comment]
TrustWalletLogo

The size of the logo precisely satisfies the standards, and the holders and transfers also comply.

**Comment by awttokenapp** [comment]
awt_logo_trustwallet

**Comment by bani68** [comment]
> your logo should be a full screen, 256x256.
> 

what to do?

**Comment by awttokenapp** [comment]
Transparent_256_awt_logo

Please verify if the above logo is transparent. We believe it satisfies all requirements for logo size, full size, and transparency in PNG files. 

Thank you

**Pull request merged**
