### PR TITLE
Add Safemusk logo and info

### PR DESCRIPTION
**Pull request by safemuske**
Add Safemusk logo and info

### CODE REVIEW

**Comment by catenocrypt** [comment]
Correction needed

❌ Contract is not in checksum format, should be 0x7Aa0f568a5CC0b5395694Cb5aD8C9423F8C41A80 (not 0x7aa0f568a5cc0b5395694cb5ad8c9423f8c41a80). Please rename it. You may need to rename to a temp name first, then to the checksum format, because lowercase-uppercase-only renames are often ignored by the Git client or the filesystem.
❌ Id field does not match contract, should be 0x7aa0f568a5cc0b5395694cb5ad8c9423f8c41a80, not 0x7Aa0f568a5CC0b5395694Cb5aD8C9423F8C41A80. Please rename.

**Review by safemuske — COMMENTED** [review]
the arrangement was made

**Review by Safemusk — COMMENTED** [review]
the arrangement was made.Would you check

**Comment by Cryptocool1** [comment]
Hello,
Contract is not in checksum format, should be 0x7Aa0f568a5CC0b5395694Cb5aD8C9423F8C41A80 (not 0x7aa0f568a5cc0b5395694cb5ad8c9423f8c41a80). Please change it.

**Comment by safemuske** [comment]
I changed it. I wonder if it happened

**Pull request merged**
