### PR TITLE
Add Facebook Metaverse (BEP20)

### PR DESCRIPTION
**Pull request by ghost**
Adding info for BEP20 token 'Facebook Metaverse'.

PR created by <a href="https://assets.trustwallet.com">TW Assets Management</a>

### CODE REVIEW

**Comment by FacebookMetaverse** [comment]
https://github.com/TechRate/Smart-Contract-Audits/blob/main/November/Facebook%20Metaverse%20Full%20Smart%20Contract%20Security%20Audit.pdf

**Comment by cryptomanz** [comment]
Can't open your website, please check.

**Comment by FacebookMetaverse** [comment]
hello, there is a problem with the server of the hosting company. they 
are trying to fix the problem.

**Comment by FacebookMetaverse** [comment]
Our website is active now. Can you make the necessary updates?

**Comment by ramsty** [comment]
Your logo have to be full screen 256*256 px. Please change it.

**Comment by FacebookMetaverse** [comment]
256 logo


> Logonuz tam ekran 256*256 piksel olmalıdır. Lütfen değiştirin.

256 logo

**Comment by cryptomanz** [comment]
• What is the purpose of this token? How will it benefit Trust Wallet users?
 • How is the token being distributed? Are you conducting an airdrop?
 • Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?
 • Is the token listed on a centralized/decentralized exchange?
 • Is a Smart Contract audit completed? Where can we find this information?

**Comment by FacebookMetaverse** [comment]
• What is the purpose of this token? How will it benefit Trust Wallet users?
"Facebook Metaverse is a play-to-earn platform in the Metaverse universe."

Facebook Metaverse is a play-to-earn platform in the Metaverse universe.
LP: 4%, Holders: 3% Marketing: 5%  distributed in the form

• Did you sold the tokens at an Initial Coin Offering (ICO) or a token
presale?
We started as a fair launch, no pre-sales

• Is the token listed on a centralized/decentralized exchange?

Token currently listed on pancakeswap exchange and coinmarketcap exchange

https://coinmarketcap.com/currencies/facebook-metaverse/

• Is a Smart Contract audit completed? Where can we find this information?

https://github.com/TechRate/Smart-Contract-Audits/blob/main/November/Facebook%20Metaverse%20Full%20Smart%20Contract%20Security%20Audit.pdf

Nazar ***@***.***>, 15 Ara 2021 Çar, 17:25 tarihinde şunu
yazdı:

**Comment by FacebookMetaverse** [comment]
Teşekkürler!

CryptoA ***@***.***>, 16 Ara 2021 Per, 03:01 tarihinde şunu
yazdı:

**Comment by FacebookMetaverse** [comment]
{
    "name": "Face Meta V2",
    "type": "BEP20",
    "symbol": "FACEMETA",
    "decimals": 9,
    "website": "https://facemetatoken.co/",
    "description": "Face Meta is a community-driven project which aims to create a new web3 ecosystem, designed by and four our community",
    "explorer": "https://bscscan.com/token/0xdaD5bB3c88b0b2a9f79145E87CEd47665ebb9057",
    "status": "active",
    "id": "0xdaD5bB3c88b0b2a9f79145E87CEd47665ebb9057",
}

**Pull request merged**
