### PR TITLE
Add CalltoCombat (BEP20)

### PR DESCRIPTION
**Pull request by calltocombat**
Adding info for BEP20 token 'CalltoCombat'.

PR created by <a href="https://assets.trustwallet.com">TW Assets Management</a>

### CODE REVIEW

**Comment by Cryptocool1** [comment]
• What is the purpose of this token? How will it benefit Trust Wallet users?
 • How is the token being distributed? Are you conducting an airdrop?
 • Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?
 • Is the token listed on a centralized/decentralized exchange?
 • Is a Smart Contract audit completed? Where can we find this information?

**Comment by calltocombat** [comment]
• What is the purpose of this token? How will it benefit Trust Wallet users?
It's a Gaming/Gamefi token, Users earn in-game rewards and can swap the Rewards using the DAPP's section on trust wallet.

• How is the token being distributed? Are you conducting an airdrop?
We conducted a Presale, no airdrop.

• Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?
Token Presale

• Is the token listed on a centralized/decentralized exchange?
Yes, it's listed on Pancakeswap.

• Is a Smart Contract audit completed? Where can we find this information?
Yes, Currently audited by Interfi & Certik.

https://www.interfi.network/audits#CalltoCombat

https://irp.cdn-website.com/1b45ecb9/files/uploaded/CalltoCombat_AuditReport_InterFi.pdf

**Comment by cryptomanz1** [comment]
Are you listed on CoinMarketCap?

**Comment by calltocombat** [comment]
Yes.
https://coinmarketcap.com/currencies/calltocombat/

**Pull request merged**
