### PR TITLE
Added ANON INU Coin

### PR DESCRIPTION
**Pull request by BruceWayneManor**

### CODE REVIEW

**Comment by Cryptocool1** [comment]
hello,
• What is the purpose of this token? How will it benefit Trust Wallet users?
 • How is the token being distributed? Are you conducting an airdrop?
 • Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?
 • Is the token listed on a centralized/decentralized exchange?
 • Is a Smart Contract audit completed? Where can we find this information?

**Comment by BruceWayneManor** [comment]
> hello,
> • What is the purpose of this token? How will it benefit Trust Wallet users?
> • How is the token being distributed? Are you conducting an airdrop?
> • Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?
> • Is the token listed on a centralized/decentralized exchange?
> • Is a Smart Contract audit completed? Where can we find this information?

Please read up on our whitepaper for all the information. 
https://anoninu.com/wp-content/uploads/2021/07/Anoninu-Whitepaper-.pdf

The smart contract will be audited in a few weeks.

**Comment by BruceWayneManor** [comment]
We're a low tax, high reward defi token. We had a VERSION 1 release July 8th but the burn function didn't exclude from fees and caused the chart to crash. We had to think of a solution, so we fixed the contract, then airdropped every single person that was at a loss from our previous project. Not a lot of people do that for their holders but we have. But to avoid dumping, we've implemented a max number of (5 BILLION) tokens you can sell every 24 hours, because we knew that the people that would receive the airdrops would dump. But anyways, we have a smart buy back system that sells towards the LP then buys back into the coin with the rest. It helps avoid heavy price impact from sellers. We have fixed the burn function and will burn 7% every 24 hours till 49% of the total supply is burned.

**Comment by BruceWayneManor** [comment]
There was a Fair-Launch, no Pre-Sale. Tokens were distributed within a mass airdrop smart contract. We've already gained over 4K additional new holders in 16 hours.

**Comment by Cryptocool1** [comment]
awaiting for smart contract audit

**Comment by BruceWayneManor** [comment]
I will get one done soon as possible. :)

**Comment by Cryptocool1** [comment]
please create new PR when smart contract will be ready.
Please create new PR, follow doc https://community.trustwallet.com/t/how-to-submit-a-token-logo/3863
You may want to try our Assets app in beta; go to https://assets.trustwallet.com, log on with Github, enter contract ID, logo and some additional info, and it will create a PR for you.
See https://community.trustwallet.com/t/how-to-submit-a-token-logo-using-assets-app/82957.

**Comment by BruceWayneManor** [comment]
Hello! Sorry for being so late. I finally got the audit complete for the smart contract by Solidity. 
https://solidity.finance/audits/AnonInu/

Here is the DXSale link for the wallet they were referring to. 
https://dxsale.app/app/v2_9/dxlockview?id=0&add=0x295E75B0f17CcffC300C3EE5D14f352d605c90ea&type=tokenlock&chain=BSC

**Comment by Cryptocool1** [comment]
can you please add links to your PR?
example: https://developer.trustwallet.com/add_new_asset/repository_details

**Pull request closed without merging**
