### PR TITLE
Please replace the new token logo with the old logo 

### PR DESCRIPTION
**Pull request by Shyamthakur33**
Project Name: TRADECOIN
Symbol: TRDC
Decimal: 18
Total supply: 1,000,000,000 TRDC
Contract address: 0x8dc53ec99ec97bf098ec3777c9ddcef935df49d4

Here is our new website sir
https://tradecoins.io/
new original logo
Logo transparent background (256x256)

### CODE REVIEW

**Comment by Shyamthakur33** [comment]
Payment is done sir. Please update the new logo with the old logo. Here is payment trx hash

FC2B73D50F5719E92850A151A40A2ECA5CF302E527CD1688A9CD430A5CBA176B

**Comment by kolya182** [comment]
Update here https://github.com/trustwallet/assets/commit/280fbfe941ec8b31fa11f5933c84ee6863d28cda

**Comment by Shyamthakur33** [comment]
Sir, new logo still not updated. Please check snapshot of my wallet. It's still showing old logo.
https://ibb.co/vqD0sSj

**Comment by Shyamthakur33** [comment]
Please recheck

**Pull request closed without merging**
