### PR TITLE
Everipedia IQ

### PR DESCRIPTION
**Pull request by kesar**

### CODE REVIEW

**Comment by kesar** [comment]
> ❌ Low token circulation: no. of holders is 255, below limit of 5000

We have 161,000 holders on EOS and we are transitioning to ethereum

https://iqnetwork.io/stats

Captura de pantalla 2021-07-16 a las 13 18 47

Unfortunately some scammers are trying to impersonate us on ethereum ecosystem and that's the reason why we would love to get the icon set, so users won't get the wrong token during the migration.

Here is our announcement of becoming multichain ( https://everipedia.org/blog/introducing-iq-v2-the-future-of-on-chain-knowledge ) and here you can find our bridge https://iqnetwork.io

We have a uniswap pool with more than 1M$ liquidity, but the icon does not show up correctly, and users get very confused.

**Comment by cryptomanz** [comment]
As per our policy, brand new tokens are not included, there is a minimum requirement of 5000 holder addresses and 10000 transactions, in order to filter out scam tokens.
See the criteria at (mentioned in the first message by the bot): https://community.trustwallet.com/t/how-to-submit-a-token-logo/3863).
Closing PR for now. Please come back to us when all criteria are met.

**Comment by kesar** [comment]
@cryptomanz did you have a chance to read my comment below? I tried to explain the problem we are facing right now. I understand that your limits are to filter out scam tokens. In our case, we have a token with 160,000 holders and we are in the process of the migration to ethereum from EOS.

**Comment by kesar** [comment]
@cryptomanz to give a bit more of background:

- project is running since 2018
- 160,000 token holders on EOS
- we launched in partnership with AP first election results on ethereum blockchain ( https://www.coindesk.com/ap-everipedia-election-calls )
- one of the most visited pages related with crypto ( http://everipedia.org/ ) with more than 1 million visitors per month

Thanks!

**Comment by kesar** [comment]
@cryptomanz @catenocrypt could reply pls? thanks!

**Pull request closed without merging**
