### PR TITLE
Add SADBABY (BEP20)

### PR DESCRIPTION
**Pull request by sadbabytoken**
Adding info for BEP20 token 'SADBABY'.

PR created by <a href="https://assets.trustwallet.com">TW Assets Management</a>

### CODE REVIEW

**Comment by sadbabytoken** [comment]
hello, I left my old contract address and paid for my logo in advance.i want you to transfer my logo to my new contract address.

**Comment by cryptomanz** [comment]
Hello,
your logo should be a full screen, 256x256.
Example:
Screenshot 2021-10-01 at 01 52 16

**Comment by sadbabytoken** [comment]
12E7F40F-D122-4001-B092-809DAD286DB2

**Comment by sadbabytoken** [comment]
https://www.certik.org/projects/sadbaby

**Comment by sadbabytoken** [comment]
Thank you 🙏👏

**Pull request merged**
