### PR TITLE
Added logo for BOND token(0x5Dc02Ea99285E17656b8350722694c35154DB1E8)

### PR DESCRIPTION
**Pull request by sameepsi**
Please visit our [website](https://bonded.finance/) for more information about Bonded Finance.

### CODE REVIEW

**Comment by catenocrypt** [comment]
Please add an `info.json` file next to the `logo.png`, with info about the project, of the form:

```json
{
    "name": "Trust Wallet Token",
    "website": "https://trustwallet.com",
    "short_description": "Utility token to increase adoption of cryptocurrency.",
    "explorer": "https://etherscan.io/token/0xA866F0198208Eb07c83081d5136BE7f775c2399e",
    "socials": [
        {
            "name": "Twitter",
            "url": "https://twitter.com/trustwalletapp",
            "handle": "TrustWalletApp"
        },
        {
            "name": "Reddit",
            "url": "https://reddit.com/r/trustapp",
            "handle": "TrustApp"
        }
    ]
}
```

**Comment by catenocrypt** [comment]
Still waiting for the info file, as mentioned above.

**Comment by sameepsi** [comment]
> Still waiting for the info file, as mentioned above.

info.json file added

**Comment by catenocrypt** [comment]
One issue left: token circulation is still somewhat below our limit threshold: 1720 holder addresses vs. 2500.
I suggest to put this PR on hold until limit is reached.

https://etherscan.io/token/0x5Dc02Ea99285E17656b8350722694c35154DB1E8

**Pull request merged**
