### PR TITLE
Add logo

### PR DESCRIPTION
**Pull request by MiniFlokiShiba**

### CODE REVIEW

**Comment by cryptomanz** [comment]
Hello,
Can your answer some questions?
 • What is the purpose of this token? How will it benefit Trust Wallet users?
 • How is the token being distributed? Are you conducting an airdrop?
 • Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?
 • Is the token listed on a centralized/decentralized exchange?
 • Is a Smart Contract audit completed? Where can we find this information?

**Comment by MiniFlokiShiba** [comment]
On 2021-07-22 17:48, Nazar wrote:

> Hello Nazar,
> 
> Please find my reply as below
> 
> Hello,
> Can your answer some questions?
> * What is the purpose of this token? How will it benefit Trust Wallet 
> users?
> MFLOKI is a Proprietary, Hyper Deflationary Token! MFLOKI token holders 
> are not only rewarded through static rewards but also through true 
> automatic burns every trade from within the liquidity pool!
> 
> Most of our members are Trust Wallet users including myself. We will 
> introduce TW to our Chinese members once the logo has been updated on 
> yours wallet.
> https://t.me/MiniFlokiShibaOfficial
> https://t.me/miniflokishiba_cn
> 
> * How is the token being distributed? Are you conducting an airdrop?
> We did a Private and Dx-Sale. Participants who joined the private sale 
> are getting their token via airdrop.
> 
> Max Supply - 1,000,000,000,000,000 (100%)
> 
> Pre-Sale - 130,000,000,000,000 (13%)
> 
> Burned/Locked - 92,400,000,000,000 (9.24%)
> 
> Public Sale - 340,000,000,000,000 (34%)
> 
> PCS Liquidity - 320,000,000,000,000 (32%)
> 
> Airdrop - 47,600,000,000,000 (4.76%)
> 
> Team - 70,000,000,000,000 (7%)
> 
> * Did you sold the tokens at an Initial Coin Offering (ICO) or a token 
> presale?
> 
> We did a Private and Dx-Sale
> 
> * Is the token listed on a centralized/decentralized exchange?
> Listed on Pancakeswap.
> https://exchange.pancakeswap.finance/#/swap?outputCurrency=0x5cedd85e5c34ef894380fb027fa5d2c944ea28e0
> 
> * Is a Smart Contract audit completed? Where can we find this 
> information?
> Yes, Fully audited and passed with flying colours.
> https://github.com/BlockAudit-Report/MiniFlokiShiba/blob/main/Mini%20Floki%20Shiba.pdf
> 
> --
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub [1], or unsubscribe 
> [2].

BR,

MINI FLOKI SHIBA TEAM

Links:
------
[1] 
https://github.com/trustwallet/assets/pull/12054#issuecomment-884786105
[2]

**Comment by MiniFlokiShiba** [comment]
@cryptomanz @catenocrypt @catenocrypt @zachzwei @Cryptocool1 Please find our reply as above

**Comment by Cryptocool1** [comment]
can you please add links to your PR?
example: https://developer.trustwallet.com/add_new_asset#info-json-contents

**Comment by MiniFlokiShiba** [comment]
> can you please add links to your PR?
> example: https://developer.trustwallet.com/add_new_asset#info-json-contents

Done can you please have a quick check ?

**Comment by MiniFlokiShiba** [comment]
@Cryptocool1 @cryptomanz @catenocrypt @zachzwei 

Added to links to PR as per requested.

**Comment by MiniFlokiShiba** [comment]
@cryptomanz @Cryptocool1 @catenocrypt @zachzwei

**Pull request merged**
