### PR TITLE
data changes

### PR DESCRIPTION
**Pull request by StakingShop**
hi guys, why is the data not updated automatically according to this site https://baking-bad.org? 
My fee is 3% and here it is 15%. Please change this and accept my request

### CODE REVIEW

**Comment by StakingShop** [comment]
thanks

**Comment by catenocrypt** [comment]
We update from baking-bad, but their API returns 3% .  Please check with them why.

image

**Comment by StakingShop** [comment]
yes, but in trust wallet json is 15%

**Comment by catenocrypt** [comment]
Yes, sorry, I confused, still checking.

**Comment by catenocrypt** [comment]
Update script was last executed 9 hours ago.  Rerun now, and now it has changed to 3%.  Please verify.

**Comment by StakingShop** [comment]
Thank you guys!

**Comment by StakingShop** [comment]
how often this script updates?

**Comment by catenocrypt** [comment]
twice daily

**Comment by catenocrypt** [comment]
@StakingShop , can you verify the value within TW?

**Comment by StakingShop** [comment]
yes fee size was changed correct, thank you. I don't think you should update the information so often. I think that 1 time in 2 days is ideal

**Comment by catenocrypt** [comment]
Issue resolved

**Pull request closed without merging**
