### PR TITLE
Add OMINO (BEP20)

### PR DESCRIPTION
**Pull request by ominofinance**
Adding info for BEP20 token 'OMINO'.

PR created by <a href="https://assets.trustwallet.com">TW Assets Management</a>

### CODE REVIEW

**Comment by ominofinance** [comment]
https://github.com/trustwallet/assets/pull/12057

Payment has been made through this thread, please confirm this.

**Comment by Cryptocool1** [comment]
hello,
• What is the purpose of this token? How will it benefit Trust Wallet users?
 • How is the token being distributed? Are you conducting an airdrop?
 • Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?
 • Is the token listed on a centralized/decentralized exchange?
 • Is a Smart Contract audit completed? Where can we find this information?

**Comment by ominofinance** [comment]
• What is the purpose of this token? How will it benefit Trust Wallet users?
Omino Finance is an automated decentralized aggregation protocol that allows yield farmers to use various liquidity protocols for the highest yield.
• How is the token being distributed? Are you conducting an airdrop?
Token is distributed via presale, we already have airdrop with 2% total supply
• Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?
Yes, we have a presale.
• Is the token listed on a centralized/decentralized exchange?
It's Already listed in PancakeSwap
• Is a Smart Contract audit completed? Where can we find this information?
Audit here: https://github.com/TechRate/Smart-Contract-Audits/blob/main/OMINO%20Full%20Smart%20Contract%20Security%20Audit.pdf

**Comment by Cryptocool1** [comment]
can you please add links to your PR?
example: https://developer.trustwallet.com/add_new_asset#info-json-contents

**Pull request merged**
