### PR TITLE
Add SADBABY (BEP20)

### PR DESCRIPTION
**Pull request by sadbabytoken**
Adding info for BEP20 token 'SADBABY'.

PR created by <a href="https://assets.trustwallet.com">TW Assets Management</a>

### CODE REVIEW

**Comment by sadbabytoken** [comment]
Old Bscscan:https://bscscan.com/token/0x3ad405ef7aea80ccb41beef0a74510e18feef190
Old Contract :0x3ad405ef7aea80ccb41beef0a74510e18feef190
decimal:9
-
New Bscscan :https://bscscan.com/token/0x3ce0f6944279a58a366cc2e89585b376306b9b4f
decimal18
New Contract : 0x3ce0f6944279a58a366cc2e89585b376306b9b4f

**Comment by sadbabytoken** [comment]
payment done #11679

**Comment by Cryptocool1** [comment]
Fee payment if required for updating

**Comment by cryptomanz** [comment]
can you send an official announcement about migration ?

**Comment by sadbabytoken** [comment]
https://github.com/trustwallet/assets/pull/11679   you can check

**Comment by Cryptocool1** [comment]
You need to pay one more time for updating.

**Comment by sadbabytoken** [comment]
I paid but why should I pay again?

**Pull request closed without merging**
