### PR TITLE
Add VitaDAO (VITA) (ERC20)

### PR DESCRIPTION
**Pull request by audieleon**
Adding info for ERC20 token 'VitaDAO (VITA)'.

PR created by <a href="https://assets.trustwallet.com">TW Assets Management</a>

### CODE REVIEW

**Comment by cryptomanz** [comment]
As per our policy, brand new tokens are not included, there is a minimum requirement of 5000 holder addresses and 10000 transactions, in order to filter out scam tokens.
See the criteria at (mentioned in the first message by the bot): https://community.trustwallet.com/t/how-to-submit-a-token-logo/3863).
Closing PR for now. Please come back to us when all criteria are met.

**Comment by audieleon** [comment]
I was in the process of getting the TWT to pay the fee when you closed this. 

Please reconsider this token. I submitted in the hopes that this line from your docs would hold for the VITA token: 

> Minimum 5,000 token holders and 10,000 transactions (Airdrop tokens excluded**). This requirement is subject for review based on the project.

VitaDAO is specifically avoiding shilling VITA. We are trying to build a tight knit, involved community. Vitalik Buterin participated in video AMA discussing our launch: [AMA with Vitalik Buterin and Aubrey de Grey - Longevity Meets Blockchain](https://www.youtube.com/watch?v=x9TSJK1widA)

We are a small DAO, working to build out our membership and brand slowly and sustainably. Our mission is longevity, and we are all focused on a _very_ long term vision. 

Please visit our [website](https://www.vitadao.com), our [discord](https://discord.gg/3S3ftnmZYD), or feel free to ask me any questions about the DAO, its mission, or the token.

**Comment by Cryptocool1** [comment]
hello,
could you answer some questions?
• What is the purpose of this token? How will it benefit Trust Wallet users?
 • How is the token being distributed? Are you conducting an airdrop?
 • Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?
 • Is the token listed on a centralized/decentralized exchange?
 • Is a Smart Contract audit completed? Where can we find this information?

**Comment by audieleon** [comment]
Yes. I will gather those answers and get back to you as soon as possible. Thank you for reopening.

**Comment by johnkelvinhhg** [comment]
Reach out to me on Telegram @Psycheout_axieofficial

**Comment by audieleon** [comment]
• What is the purpose of this token? How will it benefit Trust Wallet users?

> The purpose of this ERC20 token is to govern [VitaDAO](https://www.vitadao.com/), provide incentives to researchers and scientists, and to be a store of the DAO's value as determined by the intellectual property it acquires. The benefit to Trust Wallet users is both having the correct token info in their wallets, and having the exchanges list that information in a way that can help them get reliable data on VITA and VitaDAO. Also, our mission is to extend people's health and life spans - even partial success of VitaDAO gives your users much more time to continue to use your wallet. 

• How is the token being distributed? Are you conducting an airdrop?

> The token was distributed during a [Gnosis Auction](https://gnosis-auction.eth.link/#/auction?auctionId=30&chainId=1) of 1/3 of minted tokens, with the rest being distributed to those working in the DAO and being used as incentives for that work. It's also available for purchase both on Uniswap and Balancer (who use your wallet for their token information!). As a DAO, we are focused on increasing the participation of people not typically into crypto - specifically researchers and scientists in longevity - so we are incentivizing these people with tokens and voting power in the DAO. Since we are science and research based, we are working hard to have provable value to that community, and the token helps us do that. We avoid "when moon" type discussions, and even have a social contract for DAO members who receive distributions pinning their distributions to continued work and to NOT using VITA token as a financial instrument. 

• Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?

> There was no presale. The first possibility of obtaining tokens was a [Gnosis Auction](https://gnosis-auction.eth.link/#/auction?auctionId=30&chainId=1), which is a fair price auction. All tokens distributed since are to the involved DAO members adding value to the DAO. We do not shill the token, and are only interested in increasing the DAO's inherent value through the acquisition of intellectual property by funding research that creates that intellectual property. VITA token is capped at 64,298,880 Tokens, with 19,307,808 minted so far. Further minting and sales will occur in the same way the first sale did - through a fair auction - and will only happen to increase our ability to fund longevity science.

• Is the token listed on a centralized/decentralized exchange?

> The token is currently listed on [Uniswap VITA/USDC](https://info.uniswap.org/#/tokens/0x81f8f0bb1cb2a06649e51913a151f0e7ef6fa321) and [Balancer 80/20 VITA/ETH](https://app.balancer.fi/#/pool/0x350196326aeaa9b98f1903fb5e8fc2686f85318c000200000000000000000084) and [Balancer 50/50 VITA/ETH](https://app.balancer.fi/#/pool/0xbaeec99c90e3420ec6c1e7a769d2a856d2898e4d00020000000000000000008a), two exchanges that have heavy use of your wallet. 

• Is a Smart Contract audit completed? Where can we find this information?

> [Linum Labs](https://www.linumlabs.com/) performed the smart contract development, and [Keyko](https://www.keyko.io/) reviewed the contracts. The review of the contract was formal and extensive, but didn't result in a formal audit, since both parties participated at risk prior to launch. The token is entirely an OpenZeppelin ERC20 contract, with only a minting function added that limits minting to the owner of the contract (which in this case is the DAO contract). Token and DAO contracts available for review here: [VitaDAO Github](https://github.com/VitaDAO)

I will pay the fee shortly. Thank you for your consideration, and please feel free to ask me any further questions you have.

**Comment by audieleon** [comment]
[Here is the transaction on Binance](https://explorer.binance.org/tx/D27326906402493D757D4B5473963AB0B21750ECF0F3C652A0B18CF87924CE1D)

Please let me know of you have any further questions.

**Pull request merged**
