### PR TITLE
Add iBNB logo and info resubmission from PR #10981 

### PR DESCRIPTION
**Pull request by emaulercrypto**
Add iBNB logo and info resubmission from PR #10981 

In Closed PR #10981 Maintainer Cryptocool1 stated we needed to list on CMC in order to be approved. We listed on CMC today please see link https://coinmarketcap.com/currencies/i-bnb/ 

Cryptocool1 also stated link closed PR #10981 for transfer of payment from that request to this one.

### CODE REVIEW

**Comment by emaulercrypto** [comment]
Here is screenshot from Previous PR #10981 stating in order to approve logo we have to list on CMC 
image

**Comment by emaulercrypto** [comment]
Link to CMC listing today https://coinmarketcap.com/currencies/i-bnb/

**Comment by Cryptocool1** [comment]
can you please add links to your PR?
example: https://developer.trustwallet.com/add_new_asset#info-json-contents

**Comment by emaulercrypto** [comment]
here are the links requested. 

"name": "twitter",
            "url": "https://twitter.com/ibnbfinance"

"name": "telegram",
            "url": "https://t.me/IBNBFinance"

"name": "whitepaper",
            "url": "https://ibnb-finance.gitbook.io/ibnb-whitepaper/"

"name": "coinmarketcap",
            "url": "https://coinmarketcap.com/currencies/i-bnb/"

"name": "coingecko",
            "url": "https://www.coingecko.com/en/coins/ibnb/"

"name": "source_code",
            "url": "https://bscscan.com/address/0x830F7A104a3dF30879D526031D57DAa44BF85686#code”

**Comment by emaulercrypto** [comment]
Links have been added to the PR

**Pull request merged**
