### PR TITLE
Add DaddyUSDT (BEP20)

### PR DESCRIPTION
**Pull request by goikrypto**
Adding info for BEP20 token 'DaddyUSDT'.

PR created by <a href="https://assets.trustwallet.com">TW Assets Management</a>

### CODE REVIEW

**Comment by goikrypto** [comment]
We need to mention the PR#14656 and the PR#15050 to let you know that the fee is already paid

**Comment by goikrypto** [comment]
We need to mention the PR#14656 and the PR#15050 to let you know that the fee is already paid

**Comment by Cryptocool1** [comment]
• What is the purpose of this token? How will it benefit Trust Wallet users?
 • How is the token being distributed? Are you conducting an airdrop?
 • Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?
 • Is the token listed on a centralized/decentralized exchange?
 • Is a Smart Contract audit completed? Where can we find this information?

**Comment by ramsty** [comment]
Feel free to open new PR when you'll be ready to answer the questions.
When creating a new PR make sure to mention this PR, so that we can see that fee has been paid already here.

**Pull request closed without merging**
