### PR TITLE
Add ZooToken Logo and Info

### PR DESCRIPTION
**Pull request by TMOMS**
Add ZooToken Logo and Info

### CODE REVIEW

**Comment by TMOMS** [comment]
The website seems to be running fine across worlds. Can not repeat the error.

**Comment by cryptomanz** [comment]
Hello,
Can your answer some questions?
• What is the purpose of this token? How will it benefit Trust Wallet users?
 • How is the token being distributed? Are you conducting an airdrop?
 • Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?
 • Is the token listed on a centralized/decentralized exchange?
 • Is a Smart Contract audit completed? Where can we find this information?

**Comment by TMOMS** [comment]
It is the utility token of ZOO-Crypto World which has been top 3 on dappradar Game ranking for 3 weeks.
The distribution of ZOO token is controlled by yield farming protocol, stakepool.sol 0x711858293750FA053b1429F4755ce5f1C76A6557. We are not conducting airdrop.
We do not have ICO or presale.
For CEX listing, we have bilaxy https://bilaxy.com/trade/ZOO_BNB
A security audit from certik has been partially completed.https://www.certik.org/projects/zoocrypto

**Comment by Cryptocool1** [comment]
cant reach to your website, please check.
awaiting for full smart contract audit. on hold for now

**Comment by TMOMS** [comment]
I just checked the analytics on Cloudflare. Everything is working fine and we have 1,200 concurrent users at this moment.
Also I asked users in our telegram channel. There are over 7,500 users. And no one said they can not open the site.
Or maybe you could use a proxy/VPN to access it. Would you mind give me your specific Network provider that I can check the firewall rules for you?

And Full smart contract is not possible I think. We are still build new features through new Smart Contract. How can this be over?
ZOO team have the ZOO token and the minting mechanism smart contracts audited. Isn't his enough for add token logo?

**Comment by TMOMS** [comment]
Would you mind take a look at our project?

**Comment by Cryptocool1** [comment]
still no access to your website

**Comment by xnarfycodes** [comment]
> still no access to your website

The website is working fine. CF normally has filters on Ukraine IP addresses as I have used VPN's for this is the past. Try using TOR browser or a VPN to access the sites listed:
www.zoogame.app (make sure to have www.)
OR
dapp.moms.finance

If it still doesn't work, what sort of error is coming up then?

**Comment by TMOMS** [comment]
Hello, please try the two mirrors if possible
www.zoogame.app (with www)
&
https://dapp.moms.finance
If this still does not work use TOR browser or a free VPN as Ukraine IP addresses are blocked by Cloudflare highly likely.

**Comment by Cryptocool1** [comment]
can you please add links to your PR?
example: https://developer.trustwallet.com/add_new_asset/repository_details

**Comment by iori10500** [comment]
@cryptomanz @catenocrypt @zachzwei 
Guys, do u have access problem for our website?
https://zoogame.app

**Comment by TMOMS** [comment]
@cryptomanz @catenocrypt @zachzwei
Guys, do u have access problem for our website?
https://zoogame.app

**Comment by Cryptocool1** [comment]
> @cryptomanz @catenocrypt @zachzwei
> Guys, do u have access problem for our website?
> https://zoogame.app

can you just add links to your PR, please?

**Comment by TMOMS** [comment]
> > @cryptomanz @catenocrypt @zachzwei
> > Guys, do u have access problem for our website?
> > https://zoogame.app
> 
> can you just add links to your PR, please?

No, the thing is I can't. 
And I need to know why you and this merge-fee-bot can't access our site. There are thousands  possibilities may lead to this issue.

**Comment by codingbebop** [comment]
Test

**Pull request merged**
