### PR TITLE
Add Next Token (BEP20)

### PR DESCRIPTION
**Pull request by NXTtoken**
Adding info for BEP20 token 'Next Token'.

PR created by <a href="https://assets.trustwallet.com">TW Assets Management</a>

### CODE REVIEW

**Comment by Cryptocool1** [comment]
• Is a Smart Contract audit completed? Where can we find this information?

**Comment by NXTtoken** [comment]
Techrate full audit: https://github.com/NXTtoken/Techrate-full-audit/blob/main/Next%20Token%20Full%20Smart%20Contract%20Security%20Audit.pdf

Interfi full audit: https://github.com/NXTtoken/Next-Token-NXT-Audit/blob/main/Next_AuditReport_InterFi.pdf

**Comment by NXTtoken** [comment]
Liquidity locked: https://dxsale.app/app/v3/dxlockview?id=0&add=0xCA99649F069cdAEC14DB8711cb689AA8d8328c9f&type=lplock&chain=BSC

**Comment by NXTtoken** [comment]
Hello Cryptocool1 and Cryptomanz.

Can I pay to have the logo and the information on trustwallet?
Here is the new blocked liquidity: https://dxsale.app/app/v3/dxlockview?id=1&add=0x1087151f02855FB080894edC4D359bdA75EB75eD&type=lplock&chain=BSC

Thanks to you.

**Pull request merged**
