### PR TITLE
Attaching logo to BEP-20 token

### PR DESCRIPTION
**Pull request by ViceUno**
Thank You

### CODE REVIEW

**Comment by ViceUno** [comment]
Payment done

**Comment by zachzwei** [comment]
Token activity does not meet the minimum requirements.
Pull request will be put on Hold.
Learn more here:
https://community.trustwallet.com/t/how-to-submit-a-token-logo/3863#how-to-get-approved
Made corrections to the submission as it was at the wrong location

**Comment by ViceUno** [comment]
> 
> 
> Token activity does not meet the minimum requirements.
> Pull request will be put on Hold.
> Learn more here:
> https://community.trustwallet.com/t/how-to-submit-a-token-logo/3863#how-to-get-approved
> Made corrections to the submission as it was at the wrong location

All requirements done,please,transfer our apply to smart-branch and review

**Comment by catenocrypt** [comment]
https://bscscan.com/token/0x56B52f384ffd3cEa09730b04d9342d23B3212ef3
2389 holder addresses, 4953 rtansactions

**Pull request merged**
