### PR TITLE
Add DRAC Token (BEP20)

### PR DESCRIPTION
**Pull request by Teddydogev2**
Adding info for BEP20 token 'DRAC Token'.

Bensin Contract Security Audit Report URL ：https://beosin.com/audits/DRAC_202208021436.pdf

Automated contract audits may report that our token contracts are suspended, but this is false. Because we added a switch function to the function transfer to determine whether to close the transaction tax instead of suspending the transaction. For details, see Beosin's audit report. Thank you~

### CODE REVIEW

**Comment by cryptomanz1** [comment]
• What is the purpose of this token? How will it benefit Trust Wallet users?
 • How is the token being distributed? Are you conducting an airdrop?
 • Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?
 • Is the token listed on a centralized/decentralized exchange?
 • Is a Smart Contract audit completed? Where can we find this information?

**Comment by Teddydogev2** [comment]
**• What is the purpose of this token? How will it benefit Trust Wallet users?**

DRAC Network is a public chain developed based on Ethereum. Since February 20, 2020, we have launched our public chain development plan. We pursue fully decentralized community governance and equality among members. our unique

*Living Biobank verifies blockchain identity. One person, one vote, rejecting whales
* Human-centered autonomous factions vote to resolve the decentralization of peaceful rights.
*The self-built ecology includes DEX, cross-chain bridge, NFT currency auction, wallet, chart, lock-up, etc., which also opens up a new world for more blockchain believers.

The DRAC community currently has an expanding community with 47,000 followers, which can bring more people to Trust Wallet and improve its ecosystem for the benefit of Trust Wallet users.

**• • How is the token being distributed? Are you conducting an airdrop?**

* 30 million added pancakeswap liquidity.
* 5 million to add bitmart liquidity.
* 5 million added gate liquidity.
* 27.2 million teams hold unicrypto locks and unlock them linearly in 2 years.
* 12.8 million for the original Teddy NFT holding airdrop.
* 10 million for Teddy's pre-attack snapshot airdrop.
* 10 million for the snapshot airdrop after Teddy attack.

Yes, we did a small airdrop. Airdrops are carried out for users who hold Teddy Token, but only a small part of the total number of token holders.

**• Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?**

No, we don't have an ICO. We release tokens by airdropping a small portion to addresses holding Teddy Tokens, and the rest in the form of a fair sale.

**• Is the token listed on a centralized/decentralized exchange?**

At present, we have listed tokens on pancakeswap, and the pool address is: https://pancakeswap.finance/info/tokens/0x123458c167a371250d325bd8b1fff12c8af692a7?chainId=56, and we have negotiated with bitmart and gate for listing, and we are already negotiating.

**Comment by Cryptocool1** [comment]
hello,
 Is a Smart Contract audit completed? Where can we find this information?

**Comment by Teddydogev2** [comment]
We have completed the Beosin audit in Aug 2022,

Bensin Contract Security Audit Report URL ：https://beosin.com/audits/DRAC_202208021436.pdf

**Pull request merged**
