### PR TITLE
Adding token logo and info for AQUA

### PR DESCRIPTION
**Pull request by planetfinance**
This PR is being closed due to inactivity. If you wish to continue, please have us reopen the PR before sending your payment, or just create a new one.
Do NOT send payments for closed PR, as the fee may by lost!
  (95 vs. 48 hrs)

### CODE REVIEW

**Comment by Cryptocool1** [comment]
As per our policy, brand new tokens are not included, there is a minimum requirement of 2500 holder addresses and 5000 transactions, in order to filter out scam tokens.
See the criteria at (mentioned in the first message by the bot): https://community.trustwallet.com/t/how-to-submit-a-token-logo/3863).
Closing PR for now. Please come back to us when all criteria are met.

**Comment by planetfinance** [comment]
Totally get that.

We have a real strong community at about 600 people.

$30 million in TVL and things are moving quick.

How else could we prove we're legit and here for the long haul!

Sent with [ProtonMail](https://protonmail.com) Secure Email.

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐

**Comment by planetfinance** [comment]
Liquidity pool size is $3.2 million
Users is over 500

You can see the site here!
https://blue.planetfinance.io/

Sent with [ProtonMail](https://protonmail.com) Secure Email.

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐

**Comment by catenocrypt** [comment]
Checked info, circulation requirement is waived.
We can merge PR after fee has been paid.

**Comment by planetfinance** [comment]
Hey Adam.

So can you confirm for me what we need to do exactly to get our token and information added?

And doing this our logo and information will show in trust wallet and where else?

Sent with [ProtonMail](https://protonmail.com) Secure Email.

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐

**Comment by planetfinance** [comment]
Hey Adam, following up.

Can you confirm what else we need to do to get Planet Finance (AQUA) listed in trust wallet

Sent with [ProtonMail](https://protonmail.com) Secure Email.

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐

**Comment by planetfinance** [comment]
Hey adam can we still pay the fee?

Can you confirm what is the fee? And the wallet address?

Sent with [ProtonMail](https://protonmail.com/) Secure Email.

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐

**Comment by planetfinance** [comment]
Adam can you confirm for me that if we send payment we'll be good to go?

If so we can process that today.

Sent with [ProtonMail](https://protonmail.com/) Secure Email.

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐

**Comment by dallasrushing** [comment]
@catenocrypt can we reopen this so we can send payment to you guys to add our info for AQUA!

**Pull request closed without merging**
