### PR TITLE
Updated Logo, name & info

### PR DESCRIPTION
**Pull request by realrouse**
I know we dont have 10,000 holders, but our token has existed over 4 years, slowly building.
We were added to Trust Wallet a long time ago before you had the requirement of 10,000 holders.
I hope that's ok! Thank you!

BitcoinSoV has changed name to BSOV Token to eliminate misconceptions with Bitcoin. The website is also changed as you can see on CoinMarketCap.
The logo file just has a white background added, because with a transparent background the logo didn't present well on dark backgrounds.

### CODE REVIEW

**Comment by Cryptocool1** [comment]
As per our policy, there is a minimum requirement of 10,000 holder addresses and 15,000 transactions.
See the criteria at : https://developer.trustwallet.com/listing-new-assets/requirements .

**Comment by realrouse** [comment]
> I know we dont have 10,000 holders, but our token has existed over 4 years, slowly building.
> We were added to Trust Wallet a long time ago before you had the requirement of 10,000 holders.
> I hope that's ok! Thank you!



> As per our policy, there is a minimum requirement of 10,000 holder addresses and 15,000 transactions. See the criteria at : https://developer.trustwallet.com/listing-new-assets/requirements .

I know we dont have 10,000 holders, but our token has existed over 4 years, slowly building.
We were added to Trust Wallet a long time ago before you had the requirement of 10,000 holders.
I hope that's ok! Thank you!

**Comment by Cryptocool1** [comment]
Thanks for clarifying

**Comment by realrouse** [comment]
> Thanks for clarifying

Thank you for reopening!

**Pull request merged**
