### PR TITLE
Request Add BUMooN Tokens Info & Logo

### PR DESCRIPTION
**Pull request by bumoonio**
I hereby attach the BUMooN token info and with that item, I would like to request a submission proposal for token info

### CODE REVIEW

**Comment by bumoonio** [comment]
hello, I want to ask something, currently I meet the requirements except the coinmarketcap points, can I get the pass over? because we are in progress on cmc submit and don't know when cmc will list our token, thanks in advance

**Comment by Cryptocool1** [comment]
Hello, 
• What is the purpose of this token? How will it benefit Trust Wallet users?
 • How is the token being distributed? Are you conducting an airdrop?
 • Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?
 • Is the token listed on a centralized/decentralized exchange?
 • Is a Smart Contract audit completed? Where can we find this information?

**Comment by bumoonio** [comment]
• What is the purpose of this token? How will it benefit Trust Wallet users?
BUMooN is a Eco-Living Token that aims to be dividend tools between its green project closed-loop revenue and user. to all the holders who participate in our projects, to be listed or available in trust wallet is make them easier to monitor dividend that distributed within the projects

• How is the token being distributed? Are you conducting an airdrop?
We do private & public sales, we do not airdrop at all, in short growth is organic

• Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?
Token Presale

• Is the token listed on a centralized/decentralized exchange?
Yes
• Is a Smart Contract audit completed? Where can we find this information
Currently we are still in the audit process due to the load of the auditor's backlog, you can find it here 
https://www.certik.org/projects/bumoon

**Comment by Cryptocool1** [comment]
awaiting for smart contract audit

**Comment by Cryptocool1** [comment]
please create new PR when smart contract audit will be ready.
make sure to mention this PR so that fee can be reused

**Pull request closed without merging**
