### PR TITLE
Add WINPRO (BEP20)

### PR DESCRIPTION
**Pull request by winprotoken**
Adding info for BEP20 token 'WINPRO'.

PR created by <a href="https://assets.trustwallet.com">TW Assets Management</a>

### CODE REVIEW

**Comment by winprotoken** [comment]
Hello @Cryptocool1 @cryptomanz1 Sir/mam

**Comment by winprotoken** [comment]
hello sir, Please Update

**Comment by KamPuc86zg** [comment]
Hallo what i must? Und ho uou are?

niedz., 28 lip 2024, 04:22 użytkownik Winpro ***@***.***>
napisał:

**Comment by cryptomanz1** [comment]
• What is the purpose of this token? How will it benefit Trust Wallet users?
 • How is the token being distributed? Are you conducting an airdrop?
 • Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?
 • Is the token listed on a centralized/decentralized exchange?
 • Is a Smart Contract audit completed? Where can we find this information?

**Comment by winprotoken** [comment]
• What is the purpose of this token? How will it benefit Trust Wallet users?

Winpro (WPT) is a digital asset designed to revolutionize the sports and entertainment industries through blockchain technology. By leveraging the inherent advantages of blockchain, such as transparency, security, and decentralization.

• How is the token being distributed? Are you conducting an airdrop?

No we are not conducting Any AirDrops.

• Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?

No.

• Is the token listed on a centralized/decentralized exchange?

Token is listed on DEX Pancakeswap.

• Is a Smart Contract audit completed? Where can we find this information?

Yes we have completed smart contract audit.
https://github.com/TechRate/Smart-Contract-Audits/blob/main/July_2024/WINPRO.pdf

we have also listed on CoinMarketCap - https://coinmarketcap.com/currencies/vrtrinity/

Thanks,

**Comment by winprotoken** [comment]
Hello Team Please Update Logo

**Pull request merged**
