### PR TITLE
Official MommyDoge Assets

### PR DESCRIPTION
**Pull request by MommyDoge**
We are again trying to add official MommyDoge assets to the Trustwallet asset collection.
Achieved goals:
- 11k holders
- 50k social media followers
- CoinGecko listing
- CMC listing in approval

For more information see https://mommydoge.com or reach out anytime!

### CODE REVIEW

**Comment by MommyDoge** [comment]
Can someone from the team confirm the PR? We will pay the fee afterwards :+1:

**Comment by Cryptocool1** [comment]
hello,
• What is the purpose of this token? How will it benefit Trust Wallet users?
 • How is the token being distributed? Are you conducting an airdrop?
 • Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?
 • Is the token listed on a centralized/decentralized exchange?
 • Is a Smart Contract audit completed? Where can we find this information?

**Comment by MommyDoge** [comment]
Hi,
please see my answers to your questions below:

* What is the purpose of this token?
> Mommy Doge Coin is a meme token which forms the basis of the Mommy Doge 
> non-fungible token (NFT) trading card game. The game is set in the 
> Doge-meme universe, which has gained global attention and recognition 
> for its cute appearance and desirability. The 1st edition of Mommy Doge 
> NFTs are already listed on 
> [OpenSea.io](https://opensea.io/MommyDogeCoin) and are being 
> continuously expanded by digital artists emanating from the Mommy Doge 
> community. Each Mommy Doge NFT trading card is a one-of-a-kind digital 
> asset that cannot be duplicated and consequently holds value for 
> collectors due to its desirability and rarity. The Mommy Doge Coin 
> functions as future currency for these unique digital assets in an 
> upcoming NFT marketplace for creators that is fully funded from trading 
> fees and sales of the Mommy Doge token.

* How will it benefit Trust Wallet users?
> Many of our >11,000 holders use Trust Wallet and would greatly benefit 
> from Mommy Doge Coin being a recognized token. Not only would the 
> displayed image icon clearly separate us from the various copy-cats 
> that have emerged since our launch, which are trying to scam people by 
> using the identical token name, but also would the additional provided 
> token information instill further trust and recognition.

* How is the token being distributed? Are you conducting an airdrop?
> Mommy Doge Coins are only being distributed through regular purchases 
> on PancakeSwap. All current holder of Mommy Doge Coin are organically 
> grown! In particular, being recently listed on CoinGecko attracted a 
> new wave of holders. While our marketing plan contains airdrops, none 
> of them has concluded and none of our current holders has received any 
> tokens from an airdrop.

* Did you sold the tokens at an Initial Coin Offering (ICO) or a token 
presale?
> No, our token was fair-launched without a presale or ICO. Ownership is 
> renounced, LP locked, and Dev/Marketing wallets locked as well with a 
> weekly vesting schedule of ~2%.

* Is the token listed on a centralized/decentralized exchange?
> The token is listed on the decentralized exchange PancakeSwap (LP pair 
> address: 
> https://bscscan.com/address/0x7cb441f177065af7f841ff2e05be4923f8976ba9)

* Is a Smart Contract audit completed? Where can we find this 
information?
> Yes, we ordered a third party audit that includes the smart contract 
> from Dessert Finance (https://dessertswap.finance) which was carried 
> out on block 8987199. The report can be found on our website 
> (https://mommydoge.com/MommyDogeAudit.pdf) as well as on the auditors 
> website here: 
> https://dessertswap.finance/audits/MommyDoge%20BEP-20%20Audit%208987199.pdf 
> where we are also listed under recent audits 
> (https://dessertswap.finance/recentaudits.html).


Please let me know if you have any other questions.
We are looking forward to working with Trust Wallet.

Sincerely,
Sandra Perez

Global Head of Business Development, Mommy Doge
Madrid, Spain

**Comment by cryptomanz** [comment]
Hello,
- can you please add links to your PR?
example: https://developer.trustwallet.com/add_new_asset#info-json-contents

**Comment by MommyDoge** [comment]
Hey we've added the social links!

**Comment by MommyDoge** [comment]
Hi,

we updated the info.json on github and added the following PR links as 
requested:

"links": [
         {
             "name": "whitepaper",
             "url": "https://mommydoge.com/MommyDoge_Whitepaper.pdf"
         },
         {
             "name": "twitter",
             "url": "https://twitter.com/NewMommyDoge"
         },
         {
             "name": "reddit",
             "url": "https://www.reddit.com/r/MommyDogeCoin/"
         },
         {
             "name": "telegram",
             "url": "https://t.me/MommyDogeCoin"
         },
         {
             "name": "coinmarketcap",
             "url": 
"https://coinmarketcap.com/currencies/mommy-doge-coin/"
         },
         {
             "name": "coingecko",
             "url": "https://www.coingecko.com/en/coins/mommy-doge"
         },
         {
             "name": "discord",
             "url": "https://discord.gg/BGkFPN3WzT"
         }
     ]


Best,
MommyDoge Team

**Comment by Cryptocool1** [comment]
please create new PR when CMC listing will be ready.
make sure to mention this PR, so that we can see that fee has been paid already here.

**Pull request closed without merging**
