### PR TITLE
Add Falafel Coin (BEP20)

### PR DESCRIPTION
**Pull request by falafeltoken**
Adding info for BEP20 token 'Falafel Coin'.

PR created by <a href="https://assets.trustwallet.com">TW Assets Management</a>

### CODE REVIEW

**Comment by falafeltoken** [comment]
I opened many requests before, the last one was 10 days ago but you had a
bug in your "Assets app", and your team does not reply although I shared a
screenshot of the bug after my manual Github request. Now you say you have
a limit of 25000 holders? It's ridiculous! The Assets app bug was clearly
deliberate to avoid getting requests when you requested 5000 holders.

If you look at my last request, I should've already been added after my
last application but your team didn't reply and your Asset app was glitched.

**Comment by Cryptocool1** [comment]
hello, what bug are you talking about?

**Comment by Cryptocool1** [comment]
that was not bug from our side. You didn't add the links to your previous PR

**Comment by falafeltoken** [comment]
You are still confused and did not check my last reply 10 days ago, this is
about your Assets app, see my screenshot you missed last time (*links are
added*), and another screenshot shows that I replied to you and you
ignored.

**Comment by falafeltoken** [comment]
You are still confused and did not check my last reply 10 days ago, this is
about your Assets app, see my screenshot you missed last time (*links are
added*), and another screenshot shows that I replied to you and you ignored.

**Comment by falafeltoken** [comment]
Adding screenshots via Github this time:

https://imgur.com/a/CVwtw3U

(Nothing happened after clicking 'OK', tried this on multiple devices/browsers/networks -  suddenly worked yesterday but after you changed some requirements)

https://imgur.com/WtfUhqt
(Screenshot showing that I reported this issue but I did not get any reply on that!)

Even with the manual request, your official guide (https://community.trustwallet.com/t/how-to-submit-a-token-logo/3863) did not mention any 'links' to be added anywhere! No 'links' field shown in the info.json script there (screenshot: https://imgur.com/a/jxlNZrF)

Either way, I have the right to carry on the old request from 11 days ago! Especially that I have reported an issue and no one replied.

**Comment by Cryptocool1** [comment]
your logo is incorrect.  size should be 256/256
Please come back to us when all criteria are met.

**Comment by falafeltoken** [comment]
lol then your Assets app is also faulty accepting incorrect logo sizes, as per the screenshot, it says ‘OK’

26E8A8F9-74C4-4712-A0ED-2AA8F2A491D8

**Comment by Cryptocool1** [comment]
It’s ok, but it will be better when the size is 256/256

**Comment by falafeltoken** [comment]
So you’re closing this because of the logo size that’s ‘OK’ but you want the other size? Is that only it?

**Comment by Cryptocool1** [comment]
The size 256/256 will look better in the app

**Comment by cryptomanz** [comment]
Anyway, you don’t fit our requirements, come back to us when all criteria are met.

**Comment by falafeltoken** [comment]
If you read carefully, you will know that on 15 Nov I was eligible but your
faulty Assets app prevented this and no one replied back then, same for the
manual guide on your website, lacking info about Links field.

It’s obviously unfair that the application wasn’t considered, but it seems
it’s hard for you to understand this..your unprofessional tone with clients
proves this 👍

**Comment by cryptomanz** [comment]
Your pull request was not paid before our criteria changed, so we cannot accept your request

**Pull request closed without merging**
