### PR TITLE
Add Wrapped Okcash BSC (BEP20)

### PR DESCRIPTION
**Pull request by ogdegenblaze**
Adding info for BEP20 token 'Wrapped Okcash BSC'.

### CODE REVIEW

**Comment by Cryptocool1** [comment]
As per our policy, brand new tokens are not included, there is a minimum requirement of 10,000 holder addresses and 15,000 transactions, in order to filter out scam tokens.
See the criteria at : https://developer.trustwallet.com/assets/requirements .

**Comment by Cryptocool1** [comment]
Please come back to us when all criteria are met. Make sure to mention this PR so the fee can be reused

**Comment by oktoshi** [comment]
> As per our policy, brand new tokens are not included, there is a minimum requirement of 10,000 holder addresses and 15,000 transactions, in order to filter out scam tokens. See the criteria at : https://developer.trustwallet.com/assets/requirements .

Hi, I understand your confussion on thinking it is a new coin, but is not.
Okcash started on November 24th 2014, it has its own chain and more than 25k used adddresses/accounts at the moment, while it had 300k created accounts addresses, more than 7 years on crypto markets and a good track.
Wrapped Okcash BSC is just a Bridge to get Okcash to the binance eco system. which might look like a "new coin" but it is not, it is just a bridge for DEFI,
Anyone can track the worldwide stats Im sharing you over the Okcash explorers or okcash.co site under the section "worldwide stats".
Hope TWT please to reconsider and check how Okcash is one of the oldest and more efficient blockchains.
Kind Regards.

**Review by KDK7monta — COMMENTED** [review]
Review my profile please

**Pull request closed without merging**
