### PR TITLE
Add NAFTY (BEP20)

### PR DESCRIPTION
**Pull request by nafty2021**
Adding info for BEP20 token 'NAFTY'.

PR created by <a href="https://assets.trustwallet.com">TW Assets Management</a>

### CODE REVIEW

**Comment by nafty2021** [comment]
ticker-logo

**Comment by nafty2021** [comment]
NAFTY

**Comment by nafty2021** [comment]
Please let me know if it's. all. good. and. we. can. proceed with the payment. and. our. logo updated

**Comment by navidferi7** [comment]
> **PR Summary**
> File not allowed: blockchains/ticker-logo.png. Please revert it.
> File not allowed: info.json. Please revert it.
> File not allowed: logo.png. Please revert it.
> File not allowed: logo32.png. Please revert it.

#

**Review by navidferi7 — COMMENTED** [review]
#12623

**Comment by naftytoken2021** [comment]
is this the. active. submission?

**Comment by nafty2021** [comment]
logo

**Comment by nafty2021** [comment]
bnb1tqq9llyr3dyjd559dha6z5r5etk3qfwk07m098
this  address is. wrong,  how. do I. pay

**Comment by nafty2021** [comment]
> @nafty2021, kind reminder: please pay fee: **2000 TWT** with the memo **2620** to the address `bnb1tqq9llyr3dyjd559dha6z5r5etk3qfwk07m098`.
> Alternatively, 5 BNB is also accepted (same memo & address).
> 
> **QR** code: [Trust](https://api.qrserver.com/v1/create-qr-code/?size=200x200&data=https%3A%2F%2Flink.trustwallet.com%2Fsend%3Fcoin%3D714%26address%3Dbnb1tqq9llyr3dyjd559dha6z5r5etk3qfwk07m098%26amount%3D2000%26memo%3D2620) | [other wallet](https://api.qrserver.com/v1/create-qr-code/?size=200x200&data=bnb1tqq9llyr3dyjd559dha6z5r5etk3qfwk07m098%26amount%3D2000%26memo%3D2620)
> See the [Pull Request Fee FAQ](https://developer.trustwallet.com/add_new_asset/pr-fee).

but I keep getting invalid address even when I scan the QR code - how do I  fix this - I want. to. pay. already.

**Comment by cryptomanz** [comment]
hello,
• What is the purpose of this token? How will it benefit Trust Wallet users?
 • How is the token being distributed? Are you conducting an airdrop?
 • Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?
 • Is the token listed on a centralized/decentralized exchange?
 • Is a Smart Contract audit completed? Where can we find this information?

**Comment by nafty2021** [comment]
• What is the purpose of this token? How will it benefit Trust Wallet users?
It’s utility token to pay for content.
A: It would expand the coverage of the TW since we now have more than $25m mc and our network include over 20k members and  growing 

• How is the token being distributed? Are you conducting an airdrop?
A; Was launched on dxSale 
It’s now all over our network , 4 platform live .

• Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?
We had a token presale which was all 1000 BNB sold out in less than an our

• Is the token listed on a centralized/decentralized exchange?

BitMart - https://www.bitmart.com/trade/cn?layout=basic&symbol=NAFTY_USDT
And PancakeSwap. -  https://pancakeswap.finance/swap?outputCurrency=0x18C5fAC26C5d8b859b3A83f0f167D8924098d28a

• Is a Smart Contract audit completed? Where can we find this information?
Yes by Solidity Finance - https://solidity.finance/audits/NAFTY/

**Pull request merged**
