### PR TITLE
Add KST Token PLEASE READ the comment!

### PR DESCRIPTION
**Pull request by flisko**
@cryptomanz  You have posted some questions in PR #14180
The answers are below:

The purpose of $KST is to allow the token holders to stake and gain access to tiers within KSM Starter that would allow them to receive early investment opportunities in some of the most disruptive projects. Moreover, users can stake to earn yield and gain access to other products that can further help in yield generation and risk management.
The token is distributed in the form of dispersal at TGE. From month 2, all investors must claim the tokens via claim feature in our dapp.
The sale was conducted in pre-sale and IDO.
It's listed on Uniswap
Yes. We have completed 2 audits - by Omniscia and by Halborn:
https://omniscia.io/flisko-ksm-contracts/
https://github.com/HalbornSecurity/PublicReports/blob/master/Solidity%20Smart%20Contract%20Audits/KSM_Starter_Smart_Contract_Security_Audit_Report_Halborn_v1_1.pdf

### CODE REVIEW

**Comment by flisko** [comment]
> • What is the purpose of this token? How will it benefit Trust Wallet users? • How is the token being distributed? Are you conducting an airdrop? • Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale? • Is the token listed on a centralized/decentralized exchange?

The purpose of $KST is to allow the token holders to stake and gain access to tiers within KSM Starter that would allow them to receive early investment opportunities in some of the most disruptive projects. Moreover, users can stake to earn yield and gain access to other products that can further help in yield generation and risk management.
The token is distributed in the form of dispersal at TGE. From month 2, all investors must claim the tokens via claim feature in our dapp.
The sale was conducted in pre-sale and IDO.
It's listed on Uniswap
Yes. We have completed 2 audits - by Omniscia and by Halborn:
https://omniscia.io/flisko-ksm-contracts/
https://github.com/HalbornSecurity/PublicReports/blob/master/Solidity%20Smart%20Contract%20Audits/KSM_Starter_Smart_Contract_Security_Audit_Report_Halborn_v1_1.pdf

**Comment by flisko** [comment]
> Hello, Your logo should be a full screen (256x256). Example: https://community.trustwallet.com/t/how-to-submit-a-token-logo/3863 Screenshot 2021-10-01 at 01 52 16

Logo already is 256x256 dimension. Is there anything else wrong with it?
image

**Comment by Cryptocool1** [comment]
logo should be full screen, please take a look at the example

**Comment by flisko** [comment]
@cryptomanz @zachzwei @Cryptocool1
can we merge and close this now?

**Pull request merged**
