### PR TITLE
Add LFW Token (BEP20)

### PR DESCRIPTION
**Pull request by dyukahi**
Adding info for BEP20 token 'LFW Token'.

PR created by <a href="https://assets.trustwallet.com">TW Assets Management</a>

### CODE REVIEW

**Comment by Cryptocool1** [comment]
As per our policy, brand new tokens are not included, there is a minimum requirement of 25,000 holder addresses and 50,000 transactions, in order to filter out scam tokens.
See the criteria at : https://developer.trustwallet.com/assets/requirements .

**Comment by dyukahi** [comment]
:| what I just transfer 1000 twt

**Comment by dyukahi** [comment]
> As per our policy, brand new tokens are not included, there is a minimum requirement of 25,000 holder addresses and 50,000 transactions, in order to filter out scam tokens. See the criteria at : https://developer.trustwallet.com/assets/requirements .

We are the projects that got fund 2.5 mil you could simply check it before just reject it due to Holders. Else give me the refund now as in this link you guys said 2500 holders 
https://community.trustwallet.com/t/how-to-submit-a-token-logo/3863

**Comment by dyukahi** [comment]
Hey @cryptomanz and @Cryptocool1 you guys better check again now.

**Comment by Cryptocool1** [comment]
See the developer  document : 
https://developer.trustwallet.com/assets/requirements

**Comment by Cryptocool1** [comment]
Also the message from the bot:
Hi! In order to compensate for the efforts of processing PRs, we kindly ask for a contribution.
💀 As there is no refund, before paying the fee, make sure new tokens fulfill the minimum circulation and other acceptance criteria.
See also the PR Fee FAQ.

**Comment by Cryptocool1** [comment]
Please come back to us when all criteria are met.
When creating a new PR make sure to mention this PR, so that we can see that fee has been paid already here.

**Comment by Cryptocool1** [comment]
Payment was not found by the bot; could you provide TXID or date for checking?

**Comment by dyukahi** [comment]
https://explorer.binance.org/tx/9D98D83FE65BC5566AB4B45FFEABFBA0250614A54802DDA129ED575CB8EB7BCC
you could check it here

**Comment by Cryptocool1** [comment]
Please come back to us when all criteria are met.
When creating a new PR make sure to mention this PR, so that we can see that fee has been paid already here.

**Comment by dyukahi** [comment]
Sorry for bother again but I'm not sure why this project got approved with 10k holders
https://bscscan.com/token/0x87a2d9a9a6b2d61b2a57798f1b4b2ddd19458fb6

**Comment by dyukahi** [comment]
https://github.com/trustwallet/assets/pull/15538
I think @cryptomanz merged it. I'm not sure whether we could get an exception like this

**Comment by Cryptocool1** [comment]
They didn’t have any exceptions

**Comment by Cryptocool1** [comment]
They submit PR earlier

**Comment by dyukahi** [comment]
What you mean by earlier. 5 days ago and you guys change the policy (?)

**Comment by dyukahi** [comment]
Can we submit again if we got a Minimum of 50,000 transactions? 
I know it's a Minimum of 25,000 token holders and 50,000 transactions stated in the rules. Just asking.

**Pull request closed without merging**
