### PR TITLE
Add Sauna

### PR DESCRIPTION
**Pull request by 0405degrees**

### CODE REVIEW

**Comment by Cryptocool1** [comment]
hello,
• What is the purpose of this token? How will it benefit Trust Wallet users?
 • How is the token being distributed? Are you conducting an airdrop?
 • Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?
 • Is the token listed on a centralized/decentralized exchange?
 • Is a Smart Contract audit completed? Where can we find this information?

**Comment by 0405degrees** [comment]
Hello.
- What is the purpose of this token? What are the benefits for users of Trust Wallet?


It is a governance token for the Defi platform called SAUNAFINANCE.
SAUNA FINANCE is a Defi platform on BSC (BEP20). It offers decentralized exchanges, liquidity investment opportunities, pharming, staking, lotteries, NFT markets and much more.

https://sauna.finance

There are a number of users who have SAUNA tokens in their trust wallets and they are very keen to have SAUNA tokens listed in their trust wallets.

- How will the tokens be distributed? Do you do airdrops?

We do airdrops on a regular basis.

https://twitter.com/sauna_finance/status/1397945770582581250?s=21

https://twitter.com/sauna_finance/status/1405929684479582208?s=21


- Have you sold tokens in an ICO (Initial Coin Offering) or token pre-sale?

We are currently holding a crowdsale.

https://crowdsale.sauna.finance

- Are your tokens listed on a central/non central exchange?

We plan to provide liquidity to pancakeswap on July 25. We have already received an offer from a centralized exchange and we are discussing about listing.

- Has the audit of smart contracts been completed? Where can I find this information?

We have not yet been formally audited by an auditing body, but the SAUNA token is a simple contract and has been endorsed as secure by several blockchain engineers.

**Comment by Cryptocool1** [comment]
awaiting for smart contract audit

**Comment by 0405degrees** [comment]
We do not have an audit. and it was not written as a requirement

**Comment by cryptomanz** [comment]
Hello,
please create new PR when smart contract audit will be ready.
make sure to mention this PR, so that we can see that fee has been paid already here.

**Pull request closed without merging**
