### PR TITLE
Add: Real Trump Token V2

### PR DESCRIPTION
**Pull request by realtrumptoken**
This token is the same one (but different address) as the v1 PR which was closed a few hours ago. This is the v2

v1 PR: https://github.com/trustwallet/assets/pull/13337

### CODE REVIEW

**Comment by Cryptocool1** [comment]
Could you add the links please?

**Comment by realtrumptoken** [comment]
> Could you add the links please?

May I kindly ask where to add links and which ones? Thank you

**Comment by Cryptocool1** [comment]
> > Could you add the links please?
> 
> May I kindly ask where to add links and which ones? Thank you

Will add them)

**Comment by realtrumptoken** [comment]
> > > Could you add the links please?
> > 
> > 
> > May I kindly ask where to add links and which ones? Thank you
> 
> Will add them)

Okay. Thank you. If you need me to do anything else let me know

**Comment by realtrumptoken** [comment]
@Cryptocool1 Links should be okay now. Please do merge the PR. Thank you.

**Pull request merged**
