### PR TITLE
Update Logo 

### PR DESCRIPTION
**Pull request by mweso26**
Update logo in file 0xd08575F5F4DE7212123731088980D069CB75873D

### CODE REVIEW

**Comment by catenocrypt** [comment]
I removed not needed images, and renamed one to correct name.
@mweso26 , please check that remaining logo is correct.

**Comment by mweso26** [comment]
I believe so. It was the file uploaded today.

**Comment by mweso26** [comment]
its the 100kb photo not the 17kb

**Comment by catenocrypt** [comment]
Logo has been re-added, compressed to reduce size to below 40kB.

image

**Pull request merged**
