### PR TITLE
Add Razor Network (RAZOR) Logo & Info

### PR DESCRIPTION
**Pull request by ankit5902**
This PR is being closed due to inactivity. If you wish to continue, please have us reopen the PR before sending your payment.
Do NOT send payments for closed PR, as the fee may by lost!
  (60 vs. 60 hrs)

### CODE REVIEW

**Comment by catenocrypt** [comment]
Submission looks OK, fee payment pending.

**Comment by ankit5902** [comment]
@catenocrypt Fee has been paid in PR https://github.com/trustwallet/assets/pull/5533
Please approve and merge.

**Comment by catenocrypt** [comment]
Reopening for checking.  #5533 has been merged.

**Comment by catenocrypt** [comment]
Only logo is a bit different in this PR, but other has been already added in newer PR #5533, so closing this.

**Comment by ankit5902** [comment]
Thanks @catenocrypt ! ☺️

**Pull request closed without merging**
