### PR TITLE
Add COCOCOIN (BEP20)

### PR DESCRIPTION
**Pull request by tonj5554**
Adding info for BEP20 token 'COCOCOIN'.

PR created by <a href="https://assets.trustwallet.com">TW Assets Management</a>

### CODE REVIEW

**Comment by tonj5554** [comment]
CK audit report https://skynet.certik.com/projects/cococoin

**Comment by Cryptocool1** [comment]
• What is the purpose of this token? How will it benefit Trust Wallet users?
 • How is the token being distributed? Are you conducting an airdrop?
 • Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?
 • Is the token listed on a centralized/decentralized exchange?

**Comment by tonj5554** [comment]
*1. Token Utility:*
The COCO token possesses social finance attributes, aimed at providing
users with an enhanced social finance experience while promoting community
interaction and development.

*2. Token Distribution:*
From June 29 to August 2, we conducted a public fundraising campaign that
raised $24.37 million (COCO original token contract:
0x8367f57749EeC7C792Ad25695a63083Bc370d8A7). After the fundraising
concluded, the founding team decided to fully refund all participants'
contributions and to airdrop new COCO tokens to all contributors at a ratio
of 1:10 (as the total supply of the new token has been expanded by
tenfold). All tokens will be distributed according to the original
proportion, and the project team has reserved no tokens for themselves.

*3. Trading and Liquidity:*
On August 5, the founding team added $110,000 in initial liquidity for the
COCO token (contract address: 0xF563E86e461dE100CfCfD8b65dAA542d3d4B0550)
and burned this liquidity to ensure fairness and transparency within the
community (transaction hash:
0x1ce1cbcb39e6504ead4c03ba1747051b7140f7dfadf238fff8b531d1503bc729). The
COCO token is a standard BEP-20 token and will be available for trading on
PancakeSwap, with the official trading launch scheduled for August 20 at
13:00 UTC. We also have our own plans for listing on centralized exchanges
(CEX).

*4. Security and Audit:*
To ensure the safety of the token, we have undergone an audit by CertiK,
and the detailed report can be viewed here:
https://skynet.certik.com/projects/cococoin.

*5. How COCO Tokens Benefit Trust Wallet Users:*

   - *Social Finance Experience:* COCO tokens provide users with a unique
   social finance platform, fostering community interaction.
   - *Fair Distribution:* Our transparent token distribution mechanism
   ensures all participants receive equitable rewards.
   - *Liquidity Assurance:* The provision of initial liquidity facilitates
   easier buying and selling of tokens for users.
   - *Security:* Our code has been audited by CertiK, ensuring safety and
   reducing risks, thereby enhancing user trust.
   - *Future Development:* As the project evolves, users will have the
   opportunity to engage in additional features and applications, including
   our planned listing on centralized exchanges (CEX).

*Conclusion:*
The COCO token adheres to the core principles of blockchain, dedicated to
serving users with fairness, equity, and security.

**Comment by tonj5554** [comment]
We refunded all contributions from participants in the original COCO
fundraising by August 8. The fundraising wallet address at that time was
https://bscscan.com/address/0x95a3354c63451da2bb3af762b14396c4370f3c9f#tokentxns,
which you can review.

**Comment by Cryptocool1** [comment]
are you listed on CoinMarketCap?

**Comment by tonj5554** [comment]
We recently submitted an application to be listed on CoinMarketCap, but
we have not yet received a response.

**Comment by Cryptocool1** [comment]
Hello, 
We require CoinMarketCap listing. Please take a look at our documentation : https://developer.trustwallet.com/assets/requirements
Feel free to create new PR anytime after this criteria is met. Please make sure you mention this Pull Request in a new one, so the fee can be reused.

**Comment by tonj5554** [comment]
OK

**Comment by tonj5554** [comment]
Dear Trust Wallet Team,

I hope this message finds you well.

I am writing to provide an update on the COCO token. As previously
communicated, we scheduled the COCO token launch for August 20th at 13:00
UTC, and we honored our commitment by activating trading at the designated
time.

Here are the latest updates:

   - *Trading Volume:* Within less than 24 hours of launch, COCO has
   achieved a trading volume of over $23 million USD.
   - *Liquidity:* The liquidity pool currently holds approximately
   $1,000,000 USD. Please note that the liquidity was sent to a black hole
   address before the token launch. You can verify the transaction here:
   https://bscscan.com/tx/0x1ce1cbcb39e6504ead4c03ba1747051b7140f7dfadf238fff8b531d1503bc729
   .
   - *Community Engagement:* We have observed a significant increase in
   user engagement and community activity.

We kindly request your assistance in adding the COCO logo to the Trust
Wallet assets. With the token now fully operational and trading actively,
we would appreciate your support in updating our listing.

Thank you for your attention and assistance. We look forward to your prompt
response.

Best regards,
COCO Team

**Pull request closed without merging**
