### PR TITLE
Add Nafty (BEP20)

### PR DESCRIPTION
**Pull request by naftytoken2021**
Adding info for BEP20 token 'Nafty'.

PR created by <a href="https://assets.trustwallet.com">TW Assets Management</a>

### CODE REVIEW

**Comment by nafty2021** [comment]
it's. been paid

**Comment by nafty2021** [comment]
fee is paid; 1EBC6A4464EF3D57EFA3E8E360B671307E8B4E54852AA04A68B7EAC0187ED0A3

**Comment by nafty2021** [comment]
my. colleague put the wrong memo,   3610 - it's from my earlier commit, please fix it

**Comment by cryptomanz** [comment]
Hello,
Can your answer some questions?
• What is the purpose of this token? How will it benefit Trust Wallet users?
 • How is the token being distributed? Are you conducting an airdrop?
 • Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?
 • Is the token listed on a centralized/decentralized exchange?
 • Is a Smart Contract audit completed? Where can we find this information?

**Comment by nafty2021** [comment]
• What is the purpose of this token? How will it benefit Trust Wallet users?

A: It’s utility token to pay for content., It would expand the coverage of the TW since we now have more than $25m mc and our network include over 20k members and growing

• How is the token being distributed? Are you conducting an airdrop?
A; Was launched on dxSale
It’s now all over our network , 4 platform live .

• Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?
We had a token presale which was all 1000 BNB sold out in less than an our

• Is the token listed on a centralized/decentralized exchange?

BitMart - https://www.bitmart.com/trade/en?symbol=NAFTY_USDT
And PancakeSwap. - https://pancakeswap.finance/swap#/swap?inputCurrency=0x2eed4682197834708c0ea8d11d683440bbe104d1

Hotbit
https://hotbit.zendesk.com/hc/en-us/articles/4407492168855-Hotbit-will-launch-NAFTY-Nafty-on-September-1st-2021
• Is a Smart Contract audit completed? Where can we find this information?
Yes by Solidity Finance -  https://solidity.finance/audits/NAFTYv3/

**Comment by nafty2021** [comment]
Can your answer some questions?
• What is the purpose of this token? How will it benefit Trust Wallet users?  -  it's a utility token
• How is the token being distributed? Are you conducting an airdrop?  - no
• Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale? -no
• Is the token listed on a centralized/decentralized exchange? - yes in pancake swap, bit mart and Hotbit
• Is a Smart Contract audit completed? Where can we find this information? - yes, here's the address:  https://solidity.finance/audits/NAFTYv3/

**Comment by nafty2021** [comment]
It’s utility token to pay for content.
A: It would expand the coverage of the TW since we now have more than $25m mc and our network include over 20k members and growing


A; Was launched on dxSale
It’s now all over our network , 4 platform live .

We had a token presale which was all 1000 BNB sold out in less than an our

BitMart 
And PancakeSwap. 
Hotbit


Yes by Solidity Finance - https://solidity.finance/audits/NAFTYv3/

**Comment by nafty2021** [comment]
1. it's a utility token

**Comment by nafty2021** [comment]
?

**Comment by nafty2021** [comment]
why. are my answers being deleted all the time?/????

**Comment by nafty2021** [comment]
> Hello,
> Can your answer some questions?
> • What is the purpose of this token? How will it benefit Trust Wallet users?
> • How is the token being distributed? Are you conducting an airdrop?
> • Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?
> • Is the token listed on a centralized/decentralized exchange?
> • Is a Smart Contract audit completed? Where can we find this information?

• What is the purpose of this token? How will it benefit Trust Wallet users?
It’s utility token to pay for content.
A: It would expand the coverage of the TW since we now have more than $25m mc and our network include over 20k members and growing

• How is the token being distributed? Are you conducting an airdrop?
A; Was launched on dxSale
It’s now all over our network , 4 platform live .

• Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?
We had a token presale which was all 1000 BNB sold out in less than an our

• Is the token listed on a centralized/decentralized exchange?

BitMart - https://www.bitmart.com/trade/en?symbol=NAFTY_USDT&layout=basic
And PancakeSwap. -https://pancakeswap.finance/swap#/swap?inputCurrency=0x2eed4682197834708c0ea8d11d683440bbe104d1

and hotbit
• Is a Smart Contract audit completed? Where can we find this information?
Yes by Solidity Finance -  https://solidity.finance/audits/NAFTYv3/

**Comment by nafty2021** [comment]
• What is the purpose of this token? How will it benefit Trust Wallet users?
It’s utility token to pay for content.
A: It would expand the coverage of the TW since we now have more than $25m mc and our network include over 20k members and growing

• How is the token being distributed? Are you conducting an airdrop?
A; Was launched on dxSale
It’s now all over our network , 4 platform live .

• Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?
We had a token presale which was all 1000 BNB sold out in less than an our

• Is the token listed on a centralized/decentralized exchange?

BitMart - https://www.bitmart.com/trade/en?symbol=NAFTY_USDT&layout=basic

Pancake Swap - https://pancakeswap.finance/swap#/swap?inputCurrency=0x2eed4682197834708c0ea8d11d683440bbe104d1

and Hotbit 
• Is a Smart Contract audit completed? Where can we find this information?
Yes by Solidity Finance - https://solidity.finance/audits/NAFTYv3/

**Comment by nafty2021** [comment]
> Hello,
> Can your answer some questions?
> • What is the purpose of this token? How will it benefit Trust Wallet users?

A: it's a utility token with 4 working platforms 
> • How is the token being distributed? Are you conducting an airdrop?
A: we had a presale on DX sale in July

> • Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?
Presale on DXsale
> • Is the token listed on a centralized/decentralized exchange?
Yes on. Bitmart, Hotbit and PancakeSwap
> • Is a Smart Contract audit completed? Where can we find this information?
A: Yes by solidity finance, here's the report: https://solidity.finance/audits/NAFTYv3/

**Comment by nafty2021** [comment]
> Hello,
> Can your answer some questions?
> • What is the purpose of this token? How will it benefit Trust Wallet users?

A: it's a utility token with 4 working platforms 
> • How is the token being distributed? Are you conducting an airdrop?
A: we had a presale on DX sale in July

> • Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?
Presale on DXsale
> • Is the token listed on a centralized/decentralized exchange?
Yes on. Bitmart, Hotbit and PancakeSwap
> • Is a Smart Contract audit completed? Where can we find this information?
A: Yes by solidity finance, here's the report: https://solidity.finance/audits/NAFTYv3/

**Comment by nafty2021** [comment]
> Hello,
> Can your answer some questions?
> • What is the purpose of this token? How will it benefit Trust Wallet users?

A: it's a utility token with 4 working platforms 
> • How is the token being distributed? Are you conducting an airdrop?
A: we had a presale on DX sale in July

> • Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?
Presale on DXsale
> • Is the token listed on a centralized/decentralized exchange?
Yes on. Bitmart, Hotbit and PancakeSwap
> • Is a Smart Contract audit completed? Where can we find this information?
A: Yes by solidity finance, here's the report: https://solidity.finance/audits/NAFTYv3/

**Comment by nafty2021** [comment]
> Hello,
> Can your answer some questions?
> • What is the purpose of this token? How will it benefit Trust Wallet users?
> • How is the token being distributed? Are you conducting an airdrop?
> • Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?
> • Is the token listed on a centralized/decentralized exchange?
> • Is a Smart Contract audit completed? Where can we find this information?

**Comment by nafty2021** [comment]
• What is the purpose of this token? How will it benefit Trust Wallet users?
It’s utility token to pay for content.
A: It would expand the coverage of the TW since we now have more than $25m mc and our network include over 20k members and growing

• How is the token being distributed? Are you conducting an airdrop?
A; Was launched on dxSale
It’s now all over our network , 4 platform live .

• Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?
We had a token presale which was all 1000 BNB sold out in less than an our

• Is the token listed on a centralized/decentralized exchange?

BitMart - https://www.bitmart.com/trade/en?symbol=NAFTY_USDT&layout=basic

And PancakeSwap. -https://pancakeswap.finance/swap#/swap?inputCurrency=0x2eed4682197834708c0ea8d11d683440bbe104d1

Hotbit

• Is a Smart Contract audit completed? Where can we find this information?
Yes by Solidity Finance - https://solidity.finance/audits/NAFTYv3/

**Comment by naftytoken2021** [comment]
• What is the purpose of this token? How will it benefit Trust Wallet users?
It’s utility token to pay for content.
A: It would expand the coverage of the TW since we now have more than $25m mc and our network include over 20k members and growing

• How is the token being distributed? Are you conducting an airdrop?
A; Was launched on dxSale
It’s now all over our network , 4 platform live .

• Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?
We had a token presale which was all 1000 BNB sold out in less than an our

• Is the token listed on a centralized/decentralized exchange?

BitMart - https://www.bitmart.com/trade/en?symbol=NAFTY_USDT&layout=basic 
And PancakeSwap. - https://pancakeswap.finance/swap#/swap?inputCurrency=0x2eed4682197834708c0ea8d11d683440bbe104d1

HotBit

• Is a Smart Contract audit completed? Where can we find this information?
Yes by Solidity Finance - https://solidity.finance/audits/NAFTYv3/

**Comment by naftytoken2021** [comment]
btw our accounting sent the fee with the wrong ID and I couldn't comment because of the user issue - I was using the other account we have, can you please refund us?

**Comment by Cryptocool1** [comment]
Снимок экрана 2021-09-20 в 15 28 07

**Pull request merged**
