### PR TITLE
Add RUBY (BEP20)

### PR DESCRIPTION
**Pull request by gotenksnull**
Adding info for BEP20 token 'RUBY'.

PR created by <a href="https://assets.trustwallet.com">TW Assets Management</a>

### CODE REVIEW

**Comment by gotenksnull** [comment]
> ### PR Summary
> Files OK: 2 Token in PR: **BEP20** 0xf7722aA0714096f1FB5ef83e6041CEBB4d58a08e Symbol: **RUBY** decimals: 12 Links: [Logo](https://raw.githubusercontent.com/gotenksnull/assets/br0303-145842/blockchains/smartchain/assets/0xf7722aA0714096f1FB5ef83e6041CEBB4d58a08e/logo.png) [Info](https://raw.githubusercontent.com/gotenksnull/assets/br0303-145842/blockchains/smartchain/assets/0xf7722aA0714096f1FB5ef83e6041CEBB4d58a08e/info.json) [Website](https://rubyplaynet.com) [Explorer](https://bscscan.com/token/0xf7722aA0714096f1FB5ef83e6041CEBB4d58a08e) Tags: staking, gamefi Token check error: ❌ number of holders not checked: please, check it manually
> 
> 

Holders are currently at 80,593
https://bscscan.com/token/0xf7722aA0714096f1FB5ef83e6041CEBB4d58a08e

**Review by gotenksnull — COMMENTED** [review]
removed empty discord link

**Comment by cryptomanz** [comment]
• What is the purpose of this token? How will it benefit Trust Wallet users?
 • How is the token being distributed? Are you conducting an airdrop?
 • Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?
 • Is the token listed on a centralized/decentralized exchange?
 • Is a Smart Contract audit completed? Where can we find this information?

**Comment by gotenksnull** [comment]
@cryptomanz  What is the purpose of this token? 
The RUBY token is a reward token deployed in our gaming network to increase engagement and retention of players.

How will it benefit Trust Wallet users?
Currently, we promote Trust Wallet as the preferred mobile wallet solution. Trust wallet uses, especially the ones that we push to the Trust Wallet, will benefit from being able to see the token icon in wallet, this builds trust, this increases adoption.

How is the token being distributed? Are you conducting an airdrop?
The Token is deployed as a reward for spending in our network, or taking an action of value within it (either engagement or retention based). We do not do "Air Drops", as such, but in some cases it may look like we do. We always require actions to be taken with us in our ecosystem before we send players rewards.

Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?
We have just conducted a successful Token sale based on a modified SAFT Agreement out of our local jurisdiction of New Zealand.

Is the token listed on a centralized/decentralized exchange?
The token will be listed on Bitrue on the 15th of March (11days as of writing), on the 16th Pancakeswap, ACY.finance and ApeSwap defi markets will open, with Gate.io, CoinsBIT and WhiteBIT later in the month

Is a Smart Contract audit completed?
https://www.rubyplaynet.com/ruby-techrate-audit-2022.pdf
(The CertiK audit will be available soon)

Where can we find this information?
https://www.rubyplaynet.com/

**Pull request merged**
