### PR TITLE
add SKL logo

### PR DESCRIPTION
**Pull request by iikirilov-wmt**
This PR is being closed due to inactivity. If you wish to continue, please have us reopen the PR before sending your payment.
Do NOT send payments for closed PR, as the fee may by lost!
  (81 vs. 60 hrs)

### CODE REVIEW

**Comment by catenocrypt** [comment]
Please change logo to min. 128x128 pixel, recommended 256x256.

**Comment by thor-ragnarok** [comment]
fixed. do you require payment for this PR?

**Comment by catenocrypt** [comment]
> fixed. do you require payment for this PR?

Yes, please, fee is expected.  Thanks for the fix.

**Comment by thor-ragnarok** [comment]
@catenocrypt cool - please reopen PR

**Comment by catenocrypt** [comment]
Reopened.  Don't worry if it is auto-closed, if you make fee payment and we reopen PR, payment will be picked up.

**Comment by thor-ragnarok** [comment]
thanks, setting up payment now

**Comment by thor-ragnarok** [comment]
@catenocrypt  paid

**Pull request merged**
