### PR TITLE
Add ATL logo and info

### PR DESCRIPTION
**Pull request by ghost**
Add ATL logo and info

The fee has already been paid:
https://github.com/trustwallet/assets/pull/14671

This is the audit report:
https://atlantis.loans/assets/audit.pdf

### CODE REVIEW

**Comment by atlantis-loans** [comment]
BSC already finished due diligence process with Atlantis Loans. So we really hope you approve us.
Thank you.

**Comment by atlantis-loans** [comment]
@cryptomanz Hi, As mentioned in https://github.com/trustwallet/assets/pull/14671 I have now provided the full audit report.

Are there anymore requirements? because I really would like to have the logo of Atlantis Loans supported on Trustwallet. 

Thank you!

**Comment by Cryptocool1** [comment]
as you paid the fee Oct 25, you should meet our old requirements - 5,000 holders, while our new - 25,000 holders and 50,000 transactions

**Comment by Cryptocool1** [comment]
Please come back to us when all criteria are met.
When creating a new PR make sure to mention this PR, so that we can see that fee has been paid already here.

**Comment by atlantis-loans** [comment]
> Please come back to us when all criteria are met. When creating a new PR make sure to mention this PR, so that we can see that fee has been paid already here.

Hi,
In the Listing Accepting Guidlines section the following is stated:
Minimum 25,000 token holders and 50,000 transactions (Airdrop tokens excluded). **This requirement is subject for review based on the project**.

Can you please direct me to someone with whom I can talk to about the project and the current requirements? 

Many of the Atlantis users are using Trustwallet and are asking me almost daily why ATL logo does not show up in their wallet. Also based on last conversation with @cryptomanz I really thought the audit was the final requirement. 

Thanks!

**Pull request merged**
