### PR TITLE
Add XRT info and logo

### PR DESCRIPTION
**Pull request by vol4tim**
Robonomics.network token adding.

### CODE REVIEW

**Comment by catenocrypt** [comment]
As per our policy, brand new tokens are not included, there is a minimum requirement of 2500 holder addresses and 5000 transactions, in order to filter out scam tokens.
See the criteria at (mentioned in the first message by the bot): https://community.trustwallet.com/t/how-to-submit-a-token-logo/3863).
This token has no real usage yet (44 holders). Closing PR for now. Please come back to us when all criteria are met.  Multi-chain and staking tokens may get special treatment, let us know if this is the case. 

https://bscscan.com/token/0xC0A51ac9d548BdcDe53Fa59448029e41A39FEB20

**Comment by vol4tim** [comment]
This BEP-20 token is the original ERC-20 token bridged with an anyswap. 
ERC-20 address - https://etherscan.io/token/0x7de91b204c1c737bcee6f000aaa6569cf7061cb7
Bridge address- https://anyswap.exchange/bridge

**Comment by catenocrypt** [comment]
Reopening

**Comment by catenocrypt** [comment]
Combined circulation is OK.

**Pull request merged**
