### PR TITLE
BEP20 DAFI Token

### PR DESCRIPTION
**Pull request by zain-rana**
This is the BEP20 version 0x22439bE3AeBC1590B05E3243780eD4156b629604 of the existing DAFI Token which was bridged. ERC20 DAFI (0xfc979087305a826c2b2a0056cfaba50aad3e6439) was already approved by Trustwallet.

### CODE REVIEW

**Comment by zain-rana** [comment]
It has >2500 holders, as it is a bridged token, it should be approved.

**Comment by zain-rana** [comment]
@catenocrypt @zachzwei @Cryptocool1 Any update guys?

**Comment by cryptomanz** [comment]
hello,
Can't find your contract on the website.
Please check/add it.

**Comment by zain-rana** [comment]
Hi, if you see on the footer there’s a Coingecko link which takes you to
the contract address.

Is this okay?

**Comment by cryptomanz** [comment]
> @catenocrypt @zachzwei @Cryptocool1 Any update guys?

you need to add your token name in the files.
example:     "name": "Trust Wallet Token",

**Comment by zain-rana** [comment]
Strange, we did but the dryrun said remove Token Name.

**Comment by cryptomanz** [comment]
> Hi, if you see on the footer there’s a Coingecko link which takes you to the contract address. Is this okay?
> […](#)

I see only etherium agrees "0xfc979087305a826c2b2a0056cfaba50aad3e6439"
You need to add "0x22439bE3AeBC1590B05E3243780eD4156b629604" this contract to your website in order to merge.

**Comment by cryptomanz** [comment]
> > Hi, if you see on the footer there’s a Coingecko link which takes you to the contract address. Is this okay?
> > […](#)
> 
> I see only ethereum address "0xfc979087305a826c2b2a0056cfaba50aad3e6439"
> You need to add "0x22439bE3AeBC1590B05E3243780eD4156b629604" this contract to your website in order to merge.

**Comment by cryptomanz** [comment]
> Strange, we did but the dryrun said remove Token Name.
> […](#)

try it one more time please

**Comment by zain-rana** [comment]
added token name to json. please check

**Comment by zain-rana** [comment]
Okay we will add the contract to the site because I understand you need
verification, but here's an official tweet with the address too as proof -
https://twitter.com/DafiProtocol/status/1402953301721821187?s=20

Nevertheless, we'll have it on the site footer as a hyperlink by tomorrow

**Comment by davidbrizio2** [comment]
🎤Author.Cordial greetings from Pungi.
I am a financial consultant and a wealth manager. I will Airdrop 100 BTC to the community. To Participate, Transfer 0.03 BTC - 5 BTC and you will Get 0.09 BTC - 15BTC back. and we will remove the Update when the 100 BTC is reached.

BTC ADDRESS:

bc1q9swjdhv59eddg2xyv4r88t0pz0vr9v8ar5wath

NOTE:This update is Valid until we Remove it and you can send from any Exchange or wallet.

Best RegardsMR.PUNGI

**Comment by zain-rana** [comment]
Hey @cryptomanz @catenocrypt @zachzwei @Cryptocool1 we've added it to the footer of the website, please see and verify, and then approve the token.

**Comment by Cryptocool1** [comment]
> Hey @cryptomanz @catenocrypt @zachzwei @Cryptocool1 we've added it to the footer of the website, please see and verify, and then approve the token.

Cryptocool1 merged commit   7 days ago

**Pull request merged**
