### PR TITLE
Add Aptos tokens

### PR DESCRIPTION
**Pull request by cryptomanz1**

### CODE REVIEW

**Comment by hazem454** [comment]
hazem454

‫في السبت، 29 أكتوبر 2022 في 7:18 م تمت كتابة ما يلي بواسطة
‪merge-fee-bot[bot]‬‏ ***@***.***‬‏>:‬

**Comment by hazem454** [comment]
assets <https://github.com/hazem454/assets> PublicForked from
trustwallet/assets <https://github.com/trustwallet/assets>

Let me tell you just one word. I put this box a while ago in order to
complete the treatment of my young daughter who suffers from cancer, and
today I found out that I had stolen and the dream was …
 Go  16,468  <https://github.com/hazem454/assets/network/members>MIT
License Updated قبل 4 ساعات

‫في السبت، 29 أكتوبر 2022 في 7:18 م تمت كتابة ما يلي بواسطة ‪Nazar‬‏ <‪
***@***.***‬‏>:‬

**Comment by hazem454** [comment]
These are my assets and I did not put them for trade or profit, I put them
only in order to save my daughter's life and today you are following this

‫في السبت، 29 أكتوبر 2022 في 7:21 م تمت كتابة ما يلي بواسطة
‪merge-fee-bot[bot]‬‏ ***@***.***‬‏>:‬

**Comment by hazem454** [comment]
what does it mean? That everything goes to normal, where is humanity, we are not human

**Review by hazem454 — COMMENTED** [review]
I ask heaven to take my right from you

And to make you sad for the dearest thing you have

We have been waiting for this moment and tell the child that she will recover

I rose and killed all hope.... I doubt you to heaven

**Comment by hazem454** [comment]
I ask heaven to take my right from you

And to make you sad for the dearest thing you have

We have been waiting for this moment and tell the child that she will
recover

I rose and killed all hope.... I doubt you to heaven

‫في السبت، 29 أكتوبر 2022 في 7:18 م تمت كتابة ما يلي بواسطة
‪merge-fee-bot[bot]‬‏ ***@***.***‬‏>:‬

**Comment by hazem454** [comment]
I ask heaven to take my right from you

And to make you sad for the dearest thing you have

We have been waiting for this moment and tell the child that she will
recover

I rose and killed all hope.... I doubt you to heaven

‫في السبت، 29 أكتوبر 2022 في 7:21 م تمت كتابة ما يلي بواسطة
‪merge-fee-bot[bot]‬‏ ***@***.***‬‏>:‬

**Review by MaximPestryakov — COMMENTED** [review]
Wrong icon for Argo USD, double check other icons, please

**Review by MaximPestryakov — APPROVED** [review]

**Pull request merged**
