### PR TITLE
Add PayINR (PINR)

### PR DESCRIPTION
**Pull request by aburaza**

### CODE REVIEW

**Comment by aburaza** [comment]
Name : PayINR
Symbol : PINR
ERC20 Ethereum
Website : https://payinr.io/
Telegram : https://t.me/payinrtoken

**Comment by catenocrypto** [comment]
Sorry for inconvenience cause but TWT fee payment is disabled and we will refund that fee to the same address from where you send . 
To get 1000 TWT refund and process your request further please send 3 bnb to address 
bnb1f29knh46qztqvy6ha6r3gpm5jxx8aujdd4gq2j
with memo 5141 .

**Comment by catenocrypt** [comment]
As per our policy, brand new tokens are not included, there is a minimum requirement of 2500 holder addresses and 5000 transactions, in order to filter out scam tokens.
See the criteria at (mentioned in the first message by the bot): https://community.trustwallet.com/t/how-to-submit-a-token-logo/3863).
This token has no real usage yet (2). Closing PR for now. Please come back to us when all criteria are met.

https://etherscan.io/token/0xbcf7cb5f69aa3a6303321811e5c6d84474485f9e

**Comment by aburaza** [comment]
we are getting ready all criteria thanks

**Pull request closed without merging**
