### PR TITLE
Removing Dogebull (dead token from Dogecola team) and Dogecola V1 and V2. Dogecola is now Colana on SOL.

### PR DESCRIPTION
**Pull request by dogecolafinance**
Hi team,
I am Chris dev of Dogecola.

Please follow the title instructions. Cheers

### CODE REVIEW

**Comment by Cryptocool1** [comment]
Hi, what is the purpose of deleting the token from repository?

**Comment by dogecolafinance** [comment]
guys what do you suggest? I see can not be deleted, but how can we remove the wrong price tracking? @Cryptocool1 
@cryptomanz1

**Comment by Cryptocool1** [comment]
Please send an official announcement about your migration

**Comment by dogecolafinance** [comment]
Official announcement: Dogecola becomes Colana: https://x.com/doge_cola/status/1746991565896126620?s=20
 @Cryptocool1
@cryptomanz1

So the all ecosystem Dogecola V1-V2 and Dogebull (hence the 3 tokens we delete, should not be tracked anymore)

**Comment by dogecolafinance** [comment]
HI Team any news?
@Cryptocool1
@cryptomanz1

**Comment by cryptomanz1** [comment]
#27624

**Comment by dogecolafinance** [comment]
@Cryptocool1
@cryptomanz1
guys but Dogecola is still tracking the price for 
0x4756cd85cd07769c2ce07a73497f208d56d48ec1 people get confused. There is no trading about it


please fix it we paid for this

**Pull request closed without merging**
