### PR TITLE
Add Based Chad (ERC20)

### PR DESCRIPTION
**Pull request by basechad**
Adding info for ERC20 token 'Based Chad'.

PR created by <a href="https://assets.trustwallet.com">TW Assets Management</a>

### CODE REVIEW

**Comment by cryptomanz1** [comment]
• What is the purpose of this token? How will it benefit Trust Wallet users?
 • How is the token being distributed? Are you conducting an airdrop?
 • Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?
 • Is the token listed on a centralized/decentralized exchange?
 • Is a Smart Contract audit completed? Where can we find this information?

**Review by miclosgyjf — COMMENTED** [review]
#
Cerrado

**Comment by basechad** [comment]
Hey @cryptomanz1, questions answered below:

**What is the purpose of this token?**
Based Chad is a long-term project within the growing Base community.  The goal is to integrate within the larger Base ecosystem in creative ways, and we continue to do just that, even with a fairly significant market downturn.

**How will it benefit Trust Wallet users?**
I believe Trust Wallet users, some of whom are Based Chad community members, should be able to know there is a "Chad" meme project that is completely safe on the Base chain.  We've seen multiple scam projects pop up and would like to help minimize the number of people that are negatively impacted.
 
**How is the token being distributed?**
The token is fair traded via an Aerodrome and V3 Uniswap pool.  Tokens were initially offered via fair/stealth launch.  Weekly AERO incentives are rolled back to the community via officially sanctioned gauge.

**Are you conducting an airdrop?**
No.

**Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?**
Tokens were offered via a fair launch, no infuencers were contaced, and still no influencers are paid even now as they project has decreased significantly in value.  We will continue to hold steady and build the project out until the market improves.

**Is the token listed on a centralized/decentralized exchange?**
Yes, you can buy $CHAD primarily on Aerodrome or Uniswap, though many aggregators are also available.

**Is a Smart Contract audit completed? Where can we find this information?**
Yes, please check our github page to see one of the more barebones contracts that are commonly used.  Here is a previously completed audit representative of this contract:
https://github.com/basechad/bc/blob/main/open_zeppelin_2018-10_audit.pdf

**Comment by yoozico** [comment]
Hello Trust wallet 
After checking to receive the audit, we have decided to sign an agreement with the immunebytes website. 
Do you think the audit of this company is valid?

**Comment by basechad** [comment]
@cryptomanz1 @Cryptocool1 Hi, could you give us an update on this?  We'd be happy to provide more information as requested.

**Comment by yoozico** [comment]
good day trust wallet

We have been sending our documents for displaying the logo for several
months and  We have paid 2.5TWT for that.
Later to complete the documents You asked us for an audit, and we prepared
and sent the Yoozico audit at a cost of $4,000. But after a few months,
Yoozico's logo has not appeared in TrustVault.
What is the cause?
 Please guide us We must answer to 120 thousand holders.

Sincerely
Yoozico

**Pull request merged**
