### PR TITLE
Add BIRB logo and info

### PR DESCRIPTION
**Pull request by birbdev**
I added the BIRB logo in the recommended size and file extension, and the info.json file with BIRB info.

### CODE REVIEW

**Comment by birbdev** [comment]
@cryptomanz is the .json file ok? I only need to change the contract to checksum in the folder?  Also I am not seeing how to rename the folder. Let me know please and thank you.

Checksum contract: 0x82A479264B36104be4FDb91618a59A4fC0F50650

**Comment by jambestwick** [comment]
need uppercase

**Comment by birbdev** [comment]
Please let us know what is missing as the folder was renamed to the checksum contract.

@catenocrypt
@zachzwei
@Cryptocool1

**Comment by cryptomanz** [comment]
Can your answer some questions?
• What is the purpose of this token? How will it benefit Trust Wallet users?
• How is the token being distributed? Are you conducting an airdrop?
• Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?
• Is the token listed on a centralized/decentralized exchange?
• Is a Smart Contract audit completed? Where can we find this information?

**Comment by birbdev** [comment]
> Can your answer some questions?
> • What is the purpose of this token? How will it benefit Trust Wallet users?
> • How is the token being distributed? Are you conducting an airdrop?
> • Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?
> • Is the token listed on a centralized/decentralized exchange?
> • Is a Smart Contract audit completed? Where can we find this information?

Can your answer some questions?

• What is the purpose of this token? How will it benefit Trust Wallet users?
We welcome you to read our whitepaper: [https://birb.co/birb-whitepaper.pdf.](https://birb.co/birb-whitepaper.pdf.)  Birb is a deflationary defi token built on the Binance Smart Chain. Birb aims at becoming a highly usable token with multiple use cases such as diverse security options, e-commerce plugins, and social $BIRB sending.

• How is the token being distributed? Are you conducting an airdrop? We had a presale and a successful IDO. Both sold out in 
 less than minutes. All of these tokens have been distributed. We currently have 7,812 wallets and it's growing every hour.

• Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?
We had a presale and a successful IDO. Both sold out in minutes and both were the same price to be fair to all users.

• Is the token listed on a centralized/decentralized exchange?
We are partnered with ApeSwap. We are also listed on PancakeSwap and Hotbit.

• Is a Smart Contract audit completed? Where can we find this information?
You can read our ID Verified audit here: https://dessertswap.finance/audits/Birb%20BEP-20%20Audit%209082831.pdf

**Comment by Cryptocool1** [comment]
can you please add links to your PR?
example: https://developer.trustwallet.com/add_new_asset#info-json-contents

**Comment by birbdev** [comment]
> can you please add links to your PR?
> example: https://developer.trustwallet.com/add_new_asset#info-json-contents

Done! Thank you!

**Review by jambestwick — COMMENTED** [review]
commit

**Pull request merged**
