### PR TITLE
Added new token logo xZAR

### PR DESCRIPTION
**Pull request by RichRads**
Added the token xZAR logo

### CODE REVIEW

**Comment by RichRads** [comment]
I have paid 1BNB to bnb1tqq9llyr3dyjd559dha6z5r5etk3qfwk07m098 with MEMO 2853 Please add for me

**Comment by RichRads** [comment]
Hi please assist I see this has not worked not sure why? First time on github so please help

**Comment by catenocrypt** [comment]
The contract folder name should be in 'checksum' format, that is 0x48f07301E9E29c3C38a80ae8d9ae771F224f1054 instead of 0x48f07301e9e29c3c38a80ae8d9ae771f224f1054.
I have fixed that for you, check build should be green now.

**Comment by RichRads** [comment]
Wow thank you so much I appreciate you help. All works fine now.

**Pull request merged**
