### PR TITLE
fixes for logo.png

### PR DESCRIPTION
**Pull request by BakeryTools**
we have added a new logo

### CODE REVIEW

**Comment by BakeryTools** [comment]
it is in the correct folder. what seems to be the issue ?

**Comment by Cryptocool1** [comment]
Conflicting files
blockchains/smartchain/assets/0x26D6e280F9687c463420908740AE59f712419147/info.json
blockchains/smartchain/assets/0x26D6e280F9687c463420908740AE59f712419147/logo.png

**Comment by BakeryTools** [comment]
how are they conflicting exactly ?

**Comment by BakeryTools** [comment]
i still dont understand the issue ? please explain it. there does not seem to be any conflicting files??

**Comment by BakeryTools** [comment]
Can i get some help here ??  What is needed so the files dont conflict ?? youve just posted the same thing

**Comment by catenocrypt** [comment]
> Can i get some help here ?? What is needed so the files dont conflict ?? youve just posted the same thing

Well, exactly because of that.  You are trying to add the same files again, but they have been already added!  Correct would have been to update your forked repository as well.

**Comment by catenocrypt** [comment]
Merged master branch, conflict solved

**Comment by BakeryTools** [comment]
why is the background not removed ? ive sent a png in 256x256. ive just had a look on pancakeswap and its still the same issue. I did it as requested by the trust wallet guide. Please check this. It is definitely not being displayed as other cryptocurrencies on pancakeswap and on trust wallet.

**Comment by BakeryTools** [comment]
ive had to pay twice now because of this issue. the picture is in png and is 256x256 as recommended by the trust wallet guide. is this not the correct information?

please look into this 

thank you

**Comment by catenocrypt** [comment]
The very first commit included logo with transparent background, but with your last commit a logo with black background was submitted, and this got merged.

**Comment by catenocrypt** [comment]
We merged the logo you suppiled; but I did change it now to the transparent version #7366 .

**Comment by BakeryTools** [comment]
Hey the logo is still not proper.i don't understand why it doesn't look like the other currencies

**Comment by BakeryTools** [comment]
It's not coming up rounded and full.

**Comment by BakeryTools** [comment]
can i please get an answer ? now the logo has been changed to something else

**Pull request merged**
