### PR TITLE
Add Baby Shiba Token (BEP20)

### PR DESCRIPTION
**Pull request by babyshibapub**
Adding info for BEP20 token 'Baby Shiba Token'.

PR created by <a href="https://assets.trustwallet.com">TW Assets Management</a>

### CODE REVIEW

**Comment by babyshibapub** [comment]
I Payed : https://github.com/trustwallet/assets/pull/11479
please help me @Cryptocool1

**Comment by Cryptocool1** [comment]
hello,
can you answer some questions?
• What is the purpose of this token? How will it benefit Trust Wallet users?
• How is the token being distributed? Are you conducting an airdrop?
• Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?
• Is the token listed on a centralized/decentralized exchange?
• Is a Smart Contract audit completed? Where can we find this information?

**Comment by babyshibapub** [comment]
• What is the purpose of this token? How will it benefit Trust Wallet users?
Baby Shiba is very giving and is designed to reward long term holders. Community is first and foremost. Baby Shiba token fairness to the community.

• How is the token being distributed? Are you conducting an airdrop?
We are conducting an airdrop here: https://t.me/BabyShiba_Airdrop_Bot

• Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?
We have presale at website: https://babyshibatoken.net/

• Is the token listed on a centralized/decentralized exchange?
Yes: Decentralized exchange https://pancakeswap.info/token/0xf7ad5b7d0e408daab2f5689103ca84d1a416ceba

• Is a Smart Contract audit completed? Where can we find this information?
Contract Token: https://bscscan.com/address/0xf7ad5b7d0e408daab2f5689103ca84d1a416ceba
Contract Audit: https://bscscan.com/address/0xa3aac666b2055e041d0f79b64956fc883cc20d7f#code

thank you

**Comment by cryptomanz** [comment]
Hello,
- Can I see the smart contract audit?

**Comment by babyshibapub** [comment]
Hi @cryptomanz cryptomanz 
Sure, Anyone can see it, it's public

Thank You!!

**Comment by Cryptocool1** [comment]
https://bscscan.com/address/0xa3aac666b2055e041d0f79b64956fc883cc20d7f#code
that is not the contract audit

**Comment by babyshibapub** [comment]
We only have these 2 smart contracts. Other than that, nothing else.

**Comment by Cryptocool1** [comment]
> We only have these 2 smart contracts. Other than that, nothing else.

you need to make the smart contract audit
please create new PR when smart contract audit will be ready.
make sure to mention this PR, so that we can see that fee has been paid already here.

**Pull request closed without merging**
