### PR TITLE
Pease add WSBC token and logo

### PR DESCRIPTION
**Pull request by lfpedroza**

### CODE REVIEW

**Comment by lfpedroza** [comment]
Hi, is there anything else I should do?

**Comment by lfpedroza** [comment]
Is there any problem?

**Comment by lfpedroza** [comment]
Can I please get an answer??

**Comment by lfpedroza** [comment]
So I know you are online but wont answer... if my token wont be added for whatever reason, I want my 500 TWT tokens refunded. I did not spend $250 USD so you would ignore me. And if I have to, I will open tickets here, in Trustwallet and in Binance to get that refund.

**Comment by catenocrypt** [comment]
Logo file not in the right location, not under `assets`, fixed

**Comment by catenocrypt** [comment]
Please add an `info.json` file next to the `logo.png`, with info about the project, of the form:

```json
{
    "name": "Trust Wallet Token",
    "type": "ERC20",
    "symbol": "TWT",
    "decimals": 8,
    "description": "Utility token to increase adoption of cryptocurrency.",
    "website": "https://trustwallet.com",
    "explorer": "https://explorer.binance.org/asset/TWT-8C2",
    "source_code": "https://github.com/trustwallet/",
    "white_paper": "",
    "socials": [
        {
            "name": "Twitter",
            "url": "https://twitter.com/trustwalletapp",
            "handle": "TrustWalletApp"
        },
        {
            "name": "Reddit",
            "url": "https://reddit.com/r/trustapp",
            "handle": "TrustApp"
        }
    ],
    "research": "https://research.binance.com/en/projects/trustwallet",
    "id": "TWT-8C2"
}
```

**Comment by catenocrypt** [comment]
As per our policy, brand new tokens are not included, there is a minimum requirement of 2500 holder addresses and 5000 transactions, in order to filter out scam tokens.
See the criteria at (mentioned in the first message by the bot): https://community.trustwallet.com/t/how-to-submit-a-token-logo/3863).
This token has no real usage yet (1 holder). Closing PR for now. Please come back to us when all criteria are met.  Multi-chain and staking tokens may get special treatment, let us know if this is the case. 

https://etherscan.io/token/0xdcdae8106ae914ed9a189f967b5d025719773b41

**Comment by lfpedroza** [comment]
WOW, when was this restrictions implemented?? I did this same thing for a completely NEW token only 6 months ago! And to be honest that amount is practically impossible to get for a new token... So please just refund me the 500 TWT payment I made to the same wallet I made the transaction from, and after that you can cancel this pull request. Thanks.

**Comment by lfpedroza** [comment]
Please transfer the 500 TWT to this address: 0xc357f89a491b33caab6f0fa029a10e7fe58b4668
Its the same I made the payment from.

**Comment by catenocrypt** [comment]
see tx ABD25E028090916F7B8CA1548E752BB8AAC4E91F2683D25F5196F9C1BD06ACE0
Closing

**Comment by lfpedroza** [comment]
WOW That is NOT my wallet!!!! where did you send that????????????????

**Pull request closed without merging**
