### PR TITLE
update jamm logo

### PR DESCRIPTION
**Pull request by alxcnwy**
update jamm logo

### CODE REVIEW

**Comment by alxcnwy** [comment]
250 TWT paid: 

https://explorer.binance.org/tx/73E85E26E6DD87972D383D3730C6C770B0DB5CA989CD98312DF5124B18F32542

**Comment by catenocrypt** [comment]
Please add an `info.json` file next to the `logo.png`, with info about the project, of the form:

```json
{
    "name": "Trust Wallet Token",
    "website": "https://trustwallet.com",
    "short_description": "Utility token to increase adoption of cryptocurrency.",
    "explorer": "https://explorer.binance.org/asset/TWT-8C2",
    "socials": [
        {
            "name": "Twitter",
            "url": "https://twitter.com/trustwalletapp",
            "handle": "TrustWalletApp"
        },
        {
            "name": "Reddit",
            "url": "https://reddit.com/r/trustapp",
            "handle": "TrustApp"
        }
    ]
}
```

**Comment by alxcnwy** [comment]
> Please add an `info.json` file next to the `logo.png`, with info about the project, of the form:

Done :)

**Comment by catenocrypt** [comment]
Thanks for the info.json; now I could check circulation.

As per our policy, brand new tokens are not included, there is a minimum requirement of 500 holder addresses and 1000 transactions, in order to filter out scam tokens.
See the criteria at (mentioned in the first message by the bot): https://community.trustwallet.com/t/how-to-submit-a-token-logo/3863#how-to-get-approved
This token has low usage yet (227). Putting PR on hold. Please come back to us when all criteria are met.

https://etherscan.io/token/0x56687cf29Ac9751Ce2a4E764680B6aD7E668942e

**Comment by alxcnwy** [comment]
The token is already in the assets repo, I just want to update the logo to the new version. Pleaaase accept the PR 🙏

**Comment by catenocrypt** [comment]
Update of existing is OK :)

**Pull request merged**
