### PR TITLE
adding GRV

### PR DESCRIPTION
**Pull request by gravitoken**

### CODE REVIEW

**Comment by gravitoken** [comment]
is this going to be accepted now if i pay the fee?

**Comment by cryptomanz** [comment]
Please create new PR, follow doc https://community.trustwallet.com/t/how-to-submit-a-token-logo/3863
You may want to try our Assets app in beta; go to https://assets.trustwallet.com, log on with Github, enter contract ID, logo and some additional info, and it will create a PR for you.
See https://community.trustwallet.com/t/how-to-submit-a-token-logo-using-assets-app/82957.

**Comment by gravitoken** [comment]
i did follow the doc!

**Comment by gravitoken** [comment]
which link fields are empty? the .json follows your spec

**Comment by gravitoken** [comment]
txid for payment 2798D3CD6A9EBB7838CE8C3B3D0DED24698030585378CCC9ABB7FD87254E32F6

**Comment by cryptomanz** [comment]
Hello,
Can you answer some questions?
 • What is the purpose of this token? How will it benefit Trust Wallet users?
 • How is the token being distributed? Are you conducting an airdrop?
 • Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?
 • Is the token listed on a centralized/decentralized exchange?
 • Is a Smart Contract audit completed? Where can we find this information?

**Comment by gravitoken** [comment]
• What is the purpose of this token? How will it benefit Trust Wallet users?

- Utility comes from potential access to first community owned cryptoasset fund

• How is the token being distributed? Are you conducting an airdrop?

Finite supply, either sold at presale, added to LP or held by team for marketing/community payments.

• Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?

There was a public presale

• Is the token listed on a centralized/decentralized exchange?

Listed on PancakeSwap

• Is a Smart Contract audit completed? Where can we find this information?

Secuity audit with MythX, PDF on website.

**Comment by cryptomanz** [comment]
- I can't find smart contract audit in your website.
 Could you  sent me audit in PDF format please?

**Comment by gravitoken** [comment]
https://gravitoken.co.uk/wp-content/uploads/2021/09/GRV_MythX.pdf

**Pull request merged**
