### PR TITLE
Add meme coin image

### PR DESCRIPTION
**Pull request by sye8118**
0x577796d0716a803d33a2aab7992606ef39e3a6dd

Gospel_Coin meme image upload. thank you.

### CODE REVIEW

**Comment by sye8118** [comment]
Gospel_Coin png

**Comment by sye8118** [comment]
Wallet address and Uniswap address where the image will be added

0x577796D0716a803d33a2aaB7992606Ef39E3a6DD
https://app.uniswap.org/explore/tokens/ethereum/0x577796d0716a803d33a2aab7992606ef39e3a6dd

**Comment by sye8118** [comment]
If I deposit 2.5BNB to the wallet address, will the image be uploaded directly to the Uniswap website?

**Comment by Cryptocool1** [comment]
Please create new PR, follow doc https://developer.trustwallet.com/listing-new-assets/requirements
You may want to try our Assets app in beta; go to https://assets.trustwallet.com, log on with Github, enter contract ID, logo and some additional info, and it will create a PR for you.
See https://developer.trustwallet.com/listing-new-assets/repository_details

**Pull request closed without merging**
