### PR TITLE
add BALA token logo to trust wallet

### PR DESCRIPTION
**Pull request by legendleejr**

### CODE REVIEW

**Comment by legendleejr** [comment]
trust wallet team, I've successful made the payment , please add bala logo to tust wallet

**Comment by Cryptocool1** [comment]
Please create new PR, follow doc https://developer.trustwallet.com/assets/requirements
You may want to try our Assets app in beta; go to https://assets.trustwallet.com, log on with Github, enter contract ID, logo and some additional info, and it will create a PR for you.
See https://developer.trustwallet.com/assets/repository_details

**Comment by Cryptocool1** [comment]
When creating a new PR make sure to mention this PR, so that we can see that fee has been paid already here.

**Comment by legendleejr** [comment]
I have submitted the request already, but It keeps telling me there is error with no red characters on the page.

**Comment by legendleejr** [comment]
plz help to check if its ok now

**Comment by legendleejr** [comment]
> When creating a new PR make sure to mention this PR, so that we can see that fee has been paid already here.
I have filled the form at this website -https://assets.trustwallet.com,   may I know if everthing is ok now?

**Pull request closed without merging**
