### PR TITLE
Add KmonCoin (BEP20)

### PR DESCRIPTION
**Pull request by umbecanessa**
Adding info for BEP20 token 'KmonCoin'.

PR created by <a href="https://assets.trustwallet.com">TW Assets Management</a>

### CODE REVIEW

**Comment by Cryptocool1** [comment]
• What is the purpose of this token? How will it benefit Trust Wallet users?
 • How is the token being distributed? Are you conducting an airdrop?
 • Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?
 • Is the token listed on a centralized/decentralized exchange?
 • Is a Smart Contract audit completed? Where can we find this information?

**Comment by umbecanessa** [comment]
• What is the purpose of this token? How will it benefit Trust Wallet users?
_The KMON COIN is the in game coin of our game Kryptomon, we are adding the logo cause the vast majority of our users are indeed trust wallet users_
• How is the token being distributed? Are you conducting an airdrop?
_Token has been distributed via IDO and small airdrop campaigns to our community_
• Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?
_We have conducted a token presale to seed investors and then an IDO on three platforms: Poolz, RedKite & InfinityPad by DAOMAKER on the 23rd of August_
• Is the token listed on a centralized/decentralized exchange?
_Currently listed on Pancakeswap and DODO, will be listed on Gate.io on the 18th of Novemeber 2021_
• Is a Smart Contract audit completed? Where can we find this information?
_We have indeed used a standard and simple smart contract for the token, we have not implemented any burning mechanics or nothing rather then issuing the Token itself_

**Comment by Cryptocool1** [comment]
awaiting for smart contract audit, on hold for now

**Comment by Cryptocool1** [comment]
Please come back to us when all criteria are met.
When creating a new PR make sure to mention this PR, so that we can see that fee has been paid already here.

**Pull request closed without merging**
