### PR TITLE
upload MoonWilly assets

### PR DESCRIPTION
**Pull request by top1st**
MoonWilly is Certificate Of Deposit on Binance Smart Chain. Holders Earn Passive Rewards in DAI (USD Stablecoin) every Hour, Forever.

### CODE REVIEW

**Comment by cryptomanz** [comment]
Hello,
Can your answer some questions?
 • What is the purpose of this token? How will it benefit Trust Wallet users?
 • How is the token being distributed? Are you conducting an airdrop?
 • Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?
 • Is the token listed on a centralized/decentralized exchange?

**Comment by top1st** [comment]
• What is the purpose of this token? How will it benefit Trust Wallet users?
Answer: MoonWilly (MNWL) is a store of value. MoonWilly is a Certificate Of Deposit on Binance Smart Chain. Holders hold MoonWilly (MNWL) tokens and Earn passive rewards in DAI Stablecoins, every hour.

• How is the token being distributed? Are you conducting an airdrop?
The token was Stealth Launched on Pancakeswap July 10 2021. We also conducted an airdrop on July 13 2021. The airdrop has passed.

• Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?
MoonWilly (MNWL) was Stealth Launched on pancakeswap on July 10 2021. There was no pre-sale, no IDO, no ICO, no public sale. Team funded the whole project themselves. Team put up the money for liquidity themselves. 

• Is the token listed on a centralized/decentralized exchange?
MoonWilly (MNWL) is listed on pancakeswap.

**Comment by Cryptocool1** [comment]
• Is a Smart Contract audit completed? Where can we find this information?

**Comment by cryptomanz** [comment]
can you please add links to your PR?
example: https://developer.trustwallet.com/add_new_asset#info-json-contents

**Comment by top1st** [comment]
@cryptomanz I have updated links data

**Pull request merged**
