### PR TITLE
Submitting a Token Logo and information updation request for Quamnetwork

### PR DESCRIPTION
**Pull request by Quam-Network**
Quam Network is an Advanced Multi-chain Defi Protocol which provides various Defi-Investment methods with the best trading experience over Binance Smart Chain.
As the community is eager to see Quam Logo on your esteemed Trust Wallet, we are sending a request to upload it.
Thanks.

### CODE REVIEW

**Comment by Quam-Network** [comment]
Guys I have multiple times placed this request and every time i am making the payment too, can you please look into this why the checks are failing 
6428 & 7020 are the pull requests that have been created for the same, its really disappointing to see everytime its getting failed.

**Comment by Quam-Network** [comment]
> Guys I have multiple times placed this request and every time i am making the payment too, can you please look into this why the checks are failing
> 6428 & 7020 are the pull requests that have been created for the same, its really disappointing to see everytime its getting failed.

@catenocrypt @zachzwei @Cryptocool1 @hexorx

**Comment by catenocrypt** [comment]
Correction needed:
- token folder should be in checksum format
- `id` field in info.json should be `0x1AdE17B4B38B472B5259BbC938618226dF7b5Ca8`

❌  Contract is not in checksum format, should be 0x1AdE17B4B38B472B5259BbC938618226dF7b5Ca8 (not 0x1ade17b4b38b472b5259bbc938618226df7b5ca8). Please rename it. You may need to rename to a temp name first, then to the checksum format, because lowercase-uppercase-only renames are often ignored by the Git client or the filesystem.
❌  Id field cannot be empty

**Review by Quam-Network — COMMENTED** [review]
I have made the changes please review and get it done.

**Comment by Quam-Network** [comment]
> Token check: Errors found!
> 
> Found 1 added/changed token(s) among the PR files (BEP20: 0x1ade17b4b38b472b5259bbc938618226df7b5ca8 )
> 
> ❌ Contract is not in checksum format, should be [0x1AdE17B4B38B472B5259BbC938618226dF7b5Ca8.zip](https://github.com/trustwallet/assets/files/6398572/0x1AdE17B4B38B472B5259BbC938618226dF7b5Ca8.zip) (not 0x1ade17b4b38b472b5259bbc938618226df7b5ca8). Please rename it. You may need to rename to a temp name first, then to the checksum format, because lowercase-uppercase-only renames are often ignored by the Git client or the filesystem.
> ! Website could not be accessed, status 500, url https://quamnetwork.com/
> ✓ Token type OK (BEP20)
> ✓ Type field OK
> ✓ Symbol field OK
> ✓ Decimals field OK
> ✓ Description field OK
> ✓ Explorer field OK
> ✓ Status field OK
> ✓ Id field OK
> ✓ Logo image type is OK (image/png)
> ✓ Logo image size is OK (14.286 kB)
> ✓ Logo dimensions OK (256x256)
> ✓ Token circulation OK (no. of holders: 2993)

I don't know how to change the folder name now, please help changing it.

**Comment by Quam-Network** [comment]
[0x1AdE17B4B38B472B5259BbC938618226dF7b5Ca8.zip](https://github.com/trustwallet/assets/files/6398579/0x1AdE17B4B38B472B5259BbC938618226dF7b5Ca8.zip)

**Comment by Quam-Network** [comment]
[0x1AdE17B4B38B472B5259BbC938618226dF7b5Ca8.zip](https://github.com/trustwallet/assets/files/6398649/0x1AdE17B4B38B472B5259BbC938618226dF7b5Ca8.zip)

**Comment by catenocrypt** [comment]
Renamed folder to checksum format.

**Comment by Quam-Network** [comment]
Thanks, I believe the Logo would be updated soon.

**Pull request merged**
