### PR TITLE
astrcoin logo

### PR DESCRIPTION
**Pull request by ASTRcoin**
Uploading the logo for ASTRcoin image is PNG 256x256

### CODE REVIEW

**Comment by ASTRcoin** [comment]
Not sure why the checks failed. It previously read "pass".  Can you kindly direct me towards a fix we can update it accordingly?

**Comment by kolya182** [comment]
> Not sure why the checks failed. It previously read "pass". Can you kindly direct me towards a fix we can update it accordingly?

Test failed for a simple reason, folder naming has uppercase character, and info folder should have only `logo.png` file https://github.com/trustwallet/assets#repository-structure

**Comment by ASTRcoin** [comment]
I see the checks have failed again, I renamed the folder to lowercase and updated the folder contents to reflect logo.png.  Any suggestions?

**Comment by kolya182** [comment]
Here https://github.com/trustwallet/assets/commit/4cf7552004b77f73fd8640dfaba9470f787c8519

**Pull request closed without merging**
