### PR TITLE
Add Logo and Info

### PR DESCRIPTION
**Pull request by SAFEBTCOFFICIAL**

### CODE REVIEW

**Comment by SAFEBTCOFFICIAL** [comment]
Thank you and apologize if i made a mess in my folders.

**Comment by Cryptocool1** [comment]
Please create new PR, follow doc https://community.trustwallet.com/t/how-to-submit-a-token-logo/3863
You may want to try our new Assets app in beta; go to https://assets.trustwallet.com, log on with Github, enter contract ID, logo and some additional info, and it will create a PR for you.
See https://community.trustwallet.com/t/how-to-submit-a-token-logo-using-assets-app/82957.

**Comment by Cryptocool1** [comment]
When creating new PR, mention this PR, so that fee can be reused, and not paid again.

**Comment by SAFEBTCOFFICIAL** [comment]
The fee was paid for the right Ticket i believe. The smart chain one

Please let me know

**Comment by Cryptocool1** [comment]
> The fee was paid for the right Ticket i believe. The smart chain one Please let me know
> […](#)

can you please create new PR using our assets app ?

**Comment by SAFEBTCOFFICIAL** [comment]
Can you please explain to me what it is and how to do it?

**Comment by SAFEBTCOFFICIAL** [comment]
Done new PR submitted

**Comment by Cryptocool1** [comment]
> Done new PR submitted
> […](#)

provide me a number of new PR please.

**Comment by SAFEBTCOFFICIAL** [comment]
i honestly think is this #9576

**Comment by Cryptocool1** [comment]
contract does not match with the real one.
https://etherscan.io/token/0x62d693fe5c13b5a5b24c9ec3f423e51c35f5624f -- contract in your website
https://bscscan.com/token/0x380624A4a7e69dB1cA07deEcF764025FC224D056 the real bscscan with the true site https://safebtc.xyz/

**Comment by SAFEBTCOFFICIAL** [comment]
Hello, the first one is Eth networks but we don’t have yet 2500 holders 
  
  
   
  
  
   I need to update the logo and info of the second one, ending 056 on bsc 
  
  
   
  
  
   Best 
  
  
   
    On 06/09/2021 7:59 AM CryptoA ***@***.***> wrote:
   
   
    
   
   
    
   
   
   contract does not match with the real one.https://etherscan.io/token/0x62d693fe5c13b5a5b24c9ec3f423e51c35f5624f -- contract in your websitehttps://bscscan.com/token/0x380624A4a7e69dB1cA07deEcF764025FC224D056 the real bscscan with the true site https://safebtc.xyz/

**Comment by SAFEBTCOFFICIAL** [comment]
Logo not updated yet.
  
  
   
  
  
   I paid. Please change the logo 
  
  
   
    On 06/09/2021 7:59 AM CryptoA ***@***.***> wrote:
   
   
    
   
   
    
   
   
   Closed #9576.

**Comment by SAFEBTCOFFICIAL** [comment]
Please check again bsc scan 
  
  
   
    On 06/09/2021 7:59 AM CryptoA ***@***.***> wrote:
   
   
    
   
   
    
   
   
   contract does not match with the real one.https://etherscan.io/token/0x62d693fe5c13b5a5b24c9ec3f423e51c35f5624f -- contract in your websitehttps://bscscan.com/token/0x380624A4a7e69dB1cA07deEcF764025FC224D056 the real bscscan with the true site https://safebtc.xyz/

**Pull request closed without merging**
