### PR TITLE
Add ShibamasK (BEP20)

### PR DESCRIPTION
**Pull request by shibamask**
Adding info for BEP20 token 'ShibamasK'.

PR created by <a href="https://assets.trustwallet.com">TW Assets Management</a>

### CODE REVIEW

**Comment by shibamask** [comment]
We already paid Fee in last ticket #14881.

**Comment by shibamask** [comment]
@cryptomanz we alredy paid in last pull request #14881.

**Comment by Cryptocool1** [comment]
Payment was not found by the bot; could you provide TXID or date for checking?

**Comment by shibamask** [comment]
@Cryptocool1 you still need payment details ? our listing is approved ?

**Comment by cryptomanz** [comment]
> @Cryptocool1 you still need payment details ? our listing is approved ?

Payment was not found by the bot; could you provide TXID or date for checking?

**Comment by shibamask** [comment]
> > @Cryptocool1 you still need payment details ? our listing is approved ?
> 
> Payment was not found by the bot; could you provide TXID or date for checking?

here is the transaction id -  E9063B66B57772E9FF8FFC4E23C007C270DAE04C648F5F2FE61D1C6420AD0AE4

[](https://explorer.binance.org/tx/E9063B66B57772E9FF8FFC4E23C007C270DAE04C648F5F2FE61D1C6420AD0AE4) [**999 TWT**]

[](https://explorer.binance.org/tx/E9063B66B57772E9FF8FFC4E23C007C270DAE04C648F5F2FE61D1C6420AD0AE4) [**1.75 TWT**]

**Comment by ramsty** [comment]
Could you answer some questions?
• What is the purpose of this token? How will it benefit Trust Wallet users?
• How is the token being distributed? Are you conducting an airdrop?
• Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?
• Is the token listed on a centralized/decentralized exchange?
• Is a Smart Contract audit completed? Where can we find this information?

**Comment by shibamask** [comment]
> Could you answer some questions?
> • What is the purpose of this token? How will it benefit Trust Wallet users?
We are launching NFT Marketplace Dapp and staking, Trustwallet user can Stake and Mint NFTs and earn rewards

> • How is the token being distributed? Are you conducting an airdrop?
We did IEO in OXBULL and Token is distributed to IEO users.

> • Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?
Yes, Through OXBULL

> • Is the token listed on a centralized/decentralized exchange?
No, We are not listed in any CEX , Right now,

> • Is a Smart Contract audit completed? Where can we find this information?
Yes Smart contract is audited you can see the audit report here 
https://drive.google.com/file/d/1XL9CF18vuQnogQsMHxIcprwll2rHH5xp/view?usp=sharing

**Comment by ramsty** [comment]
Your logo should be a full screen, please change.

**Comment by shibamask** [comment]
> Your logo should be a full screen, please change.

Full screen logo ? Where to add ?
we added mentioned size logo  in file  

https://shibamask.org/img/1024.png

above url have full screen size logo

**Pull request merged**
