### PR TITLE
Add Numbers network

### PR DESCRIPTION
**Pull request by shc261392**
https://www.numbersprotocol.io/
https://docs.numbersprotocol.io/

### CODE REVIEW

**Comment by Cryptocool1** [comment]
Hi @shc261392, thank you for opening the PR.
At the moment we do not merge new blockchains into WalletCore without a positive decision from our Business Development team.
Please create a new ticket, a request to add the blockchain to Trust Wallet:
https://support.trustwallet.com/en/support/tickets/new

**Comment by shc261392** [comment]
> Hi @shc261392, thank you for opening the PR.
> 
> At the moment we do not merge new blockchains into WalletCore without a positive decision from our Business Development team.
> 
> Please create a new ticket, a request to add the blockchain to Trust Wallet:
> 
> https://support.trustwallet.com/en/support/tickets/new

In fact, our team has reached out to your Business Development team by creating a ticket. Is there any chance you could help to get it checked?

**Comment by shc261392** [comment]
@Cryptocool1 Sorry for pinging again, we just want to know if the ticket submitted are getting viewed because we hadn't receive any response for weeks.

**Comment by bafu** [comment]
@Cryptocool1 Please guide the next step to proceed with this pull request or get a refund of this pull request. Thanks

**Comment by Cryptocool1** [comment]
Hello, 
As you can see from the first bot’s message we do not make any refunds. Please wait for the response  from Business Development team

**Pull request closed without merging**
