### PR TITLE
Add TWT logo and info

### PR DESCRIPTION
**Pull request by wrennstigator**
old contract address being updated

### CODE REVIEW

**Comment by cryptomanz** [comment]
This is a BEP20 token, correct folder is blockchains/smartchain/assets. Please correct.

**Comment by Cryptocool1** [comment]
please create new PR, follow doc https://developer.trustwallet.com/assets/requirements
I recommend go to https://assets.trustwallet.com, log on with Github, enter contract ID, logo and some additional info, and it will create a PR for you.
See https://developer.trustwallet.com/assets/repository_details

**Comment by wrennstigator** [comment]
ok but i already paid the fee will i be charged again? i was almost positive i did everything right.

**Comment by Cryptocool1** [comment]
You don’t need to pay the fee again, just mention this PR in the new one

**Comment by wrennstigator** [comment]
ok made new PR here: https://github.com/trustwallet/assets/pull/21299

**Pull request closed without merging**
