### PR TITLE
Add OFE Token from MultiversX (old Elrond)

### PR DESCRIPTION
**Pull request by oferonetwork**

### CODE REVIEW

**Comment by oferonetwork** [comment]
Hello,

Waiting for human confirmation that everything is okay before we will proceed with the payment. 

Looking forward to join Trust Wallet!

**Comment by cryptomanz1** [comment]
• What is the purpose of this token? How will it benefit Trust Wallet users?
 • How is the token being distributed? Are you conducting an airdrop?
 • Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?
 • Is the token listed on a centralized/decentralized exchange?
 • Is a Smart Contract audit completed? Where can we find this information?

**Comment by oferonetwork** [comment]
• What is the purpose of this token? How will it benefit Trust Wallet users?
_The $OFE token is the utility token of the Ofero Network. Trust Wallet users will be able to view/access and transfer their OFE tokens, access real life events, vote in DAO events and much more. Many of the Trust Wallet users were forced to create an MultiversX wallet in order to access the token and now we will would like to give them the power to import their wallet back into Trust Wallet._

• How is the token being distributed? Are you conducting an airdrop?
_The token can be purchased from our own DEX available at ofero.exchange or from xExchange.com after adding the OFE-29eb54 ticker
No airdrops._

• Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?
_There was a token presale at the beginning of 2022 and on 7 April 2022 the token was launched on xExchange._

• Is the token listed on a centralized/decentralized exchange?
_Yes on xExchange (DEX) and ofero.exchange (DEX)_

• Is a Smart Contract audit completed? Where can we find this information?
_Since the token was issued on the MultiversX blockchain as an ESDT it does not work behind a Smart Contract._

**Comment by cryptomanz1** [comment]
Awaiting smart contract audit. On hold for now.

**Comment by Cryptocool1** [comment]
Please come back to us once criterion is met. Make sure to mention this PR so the fee can be reused

**Comment by Classic298** [comment]
@Cryptocool1 are you ridiculous?

You have added many ESDTs already to trust wallet. This is just another one. For one, ESDTs aren't smart contracts so there is no need for an audit. And secondly, even if there was the need for an audit, you already approved many other ESDTs with the exact same code! The code is the exact same! What do you mean you need an audit?

**Comment by Classic298** [comment]
For one, ESDTs aren't even smart contracts.
Secondly, you have listed many ESDTs already, why do you now suddenly want an audit of ESDT, when 1) you have already listed many ESDTs and 2) it isn't even a smart contract?

**Pull request merged**
