### PR TITLE
Add SHIBA RISE logo and information

### PR DESCRIPTION
**Pull request by ShibaRise**
Add SHIBA RISE logo and information 
0x0766d199D90b3C1Ae34CB12281Ec83142ABCCa0A
SHIBA RISE 
SHIBARISE
9

### CODE REVIEW

**Comment by ShibaRise** [comment]
add SHIBARISE logo/info

**Comment by ShibaRise** [comment]
Hello! It was telling me the files werent accepted a couple times did i do it correctly?

**Review by ShibaRise — COMMENTED** [review]
I added token information to original file.

**Comment by Cryptocool1** [comment]
Please create new PR, follow doc https://community.trustwallet.com/t/how-to-submit-a-token-logo/3863
You may want to try our Assets app in beta; go to https://assets.trustwallet.com, log on with Github, enter contract ID, logo and some additional info, and it will create a PR for you.
See https://community.trustwallet.com/t/how-to-submit-a-token-logo-using-assets-app/82957.
When creating a new PR make sure to mention this PR, so that we can see that fee has been paid already here.

**Comment by ShibaRise** [comment]
Hey Crypto its giving me an error : !  No. of holders not checked, external info not available; null there is no option to put this information in

**Pull request closed without merging**
