### PR TITLE
UPDATE #2 Infinity Logo

### PR DESCRIPTION
**Pull request by InfinityTokenINF**

### CODE REVIEW

**Comment by InfinityTokenINF** [comment]
> [merge-fee-bot]: In order to compensate for the efforts of adding a new asset, we kindly ask for a contribution.
> Please pay 1000 TWT to the address below (don't forget to set the _memo_!).
> Trust Wallet Token is distributed to new users through the Referral program, see [TWT Referral Program](https://community.trustwallet.com/t/invite-a-friend-earn-trust-wallet-token-twt/4125)
> Alternatively, BNB is accepted as well.
> The team may waive the fee when justified.
> 
> Please pay:
> 1000 TWT to address bnb1tqq9llyr3dyjd559dha6z5r5etk3qfwk07m098 with memo 'Ia809'
> **QR** code: [Trust](https://api.qrserver.com/v1/create-qr-code/?size=200x200&data=https%3A%2F%2Flink.trustwallet.com%2Fsend%3Fcoin%3D714%26address%3Dbnb1tqq9llyr3dyjd559dha6z5r5etk3qfwk07m098%26amount%3D1000%26memo%3DIa809) | [other wallet](https://api.qrserver.com/v1/create-qr-code/?size=200x200&data=bnb1tqq9llyr3dyjd559dha6z5r5etk3qfwk07m098%26amount%3D1000%26memo%3DIa809)
> (or 0.5 BNB to address bnb1tqq9llyr3dyjd559dha6z5r5etk3qfwk07m098 with memo 'Ia809'
> **QR** code: [Trust](https://api.qrserver.com/v1/create-qr-code/?size=200x200&data=https%3A%2F%2Flink.trustwallet.com%2Fsend%3Fcoin%3D714%26address%3Dbnb1tqq9llyr3dyjd559dha6z5r5etk3qfwk07m098%26amount%3D0.5%26memo%3DIa809) | [other wallet](https://api.qrserver.com/v1/create-qr-code/?size=200x200&data=bnb1tqq9llyr3dyjd559dha6z5r5etk3qfwk07m098%26amount%3D0.5%26memo%3DIa809))

I already paid the trasaction fee for merge D195B55E91A0C5B6B56EB4A2599E915785F16128FECF3FDC6C82E4F057A2C790 tx hash.

**Comment by kolya182** [comment]
And what is the problem ?
IMG_2F5DE8E77826-1

**Comment by InfinityTokenINF** [comment]
I'm just updating the logo.

**Comment by InfinityTokenINF** [comment]
I just to 300x300 png full wide

**Comment by InfinityTokenINF** [comment]
Hope the Logo will update asap. our project will begin after the logo
updated. Thankyou

**Comment by kolya182** [comment]
Updated https://github.com/trustwallet/assets/commit/c677e1de64cb73d2d6c388e7b688767b76040a4f

**Pull request closed without merging**
