### PR TITLE
Add PiSwap Token (PIS) (erc20)

### PR DESCRIPTION
**Pull request by Shyamthakur33**
This PR is being closed due to inactivity. If you wish to continue, please have us reopen the PR before sending your payment.
Do NOT send payments for closed PR, as the fee may by lost!
  (77 vs. 60 hrs)

### CODE REVIEW

**Comment by Shyamthakur33** [comment]
@catenocrypt could you please check our request if all okey
then we will proceed with payment, thank you!

**Comment by Shyamthakur33** [comment]
It's working. Please recheck

**Comment by Shyamthakur33** [comment]
We are already listed on coinmarketcap. There also website working.

**Comment by Shyamthakur33** [comment]
@cetenocrypt could you please recheck it's working https://piswap.io/

**Comment by Shyamthakur33** [comment]
@catenocrypt could you plz review our project if we meet acceptance criteria or not then we will proceed payment

**Comment by catenocrypt** [comment]
Submission looks OK.  Waiting for payment.

**Comment by Shyamthakur33** [comment]
> Submission looks OK. Waiting for payment.

Thank you so much!
We want to pay fee now, could you please reopen the pr.

**Comment by Shyamthakur33** [comment]
@catenocrypt as you opened it closed instant, please open it again so we can pay fee or should we create a new pr?

**Comment by catenocrypt** [comment]
The auto-close is a bit annoying, but do not worry: you can pay if the PR is closed at the moment, payment will be picked up automatically on next reopen.  Just be sure to send a note.  I reopen now.

**Comment by catenocrypt** [comment]
Sorry, I cannot reopen, I'm told that the source repository has been deleted already!

**Pull request closed without merging**
