### PR TITLE
GEG Token logo and info by Ge.Finance (GeFi)

### PR DESCRIPTION
**Pull request by GeFiOfficial**
GEG (GeGem) Token logo and information by Ge.Finance aka GeFi
Visit https://ge.finance OR https://info.ge.finance for more info
Stoneage NFT coming soon!

GitHub
https://github.com/GeFiOfficial/

Gitbook
https://info.ge.finance/

Twitter
https://twitter.com/gefiofficial

Telegram Community
https://t.me/geficommunity

Telegram Channel
https://t.me/GeFiOfficial

Discord
https://discord.com/invite/7eeGSJMXyB

Reddit
https://www.reddit.com/r/gefiofficial

Upcoming NFT Gaming, Marketplace, Arts and more updates!
Stoneage NFT Telegram
https://t.me/StoneAge_NFT

Stoneage Telegram Channel Update
https://t.me/stoneagechannel

### CODE REVIEW

**Comment by GeFiOfficial** [comment]
GEG

• What is the purpose of this token? How will it benefit Trust Wallet users?

GEG token plays the tole to create monetary incentives for the most committed and motivated users by our 1st ecosystem decentralised finance vaults.

GEG also can use to purchase privilege items on NFT Marketplace and Blockchain-Powered Games.

By adding our logo, Trust Wallet users will avoid being scammed by other tokens that are pretending to be us, we have more then 5000 holders and counting.


• How is the token being distributed? Are you conducting an airdrop?

Total Supply : 95,000 GEG
Finance Vaults 40% - 38,000 GEG
Public Sales 30% - 28,500 GEG
Technical 15% - 14,250 GEG
Development 5% - 4750 GEG
Reserved 5% - 4750 GEG
Marketing 5% – 4750 GEG 

We conduct airdrops with not more than 5% of total allocation 


• Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?

Yes. We launched our public sales on 8 July 2021 UTC 12:00, ended on 6 August 2021 UTC 11:59

• Is the token listed on a centralized/decentralized exchange?

DEX only. PancakeSwap

• Is a Smart Contract audit completed? Where can we find this information?

Audit Reports are in progress. You can find more information about us in 

https://bscscan.com/address/0x99dAB6065951BecaC1dECBaC0C1A16b9BbF12913
 (https://bscscan.com/address/0x99dAB6065951BecaC1dECBaC0C1A16b9BbF12913)
https://bscscan.com/token/0x99dAB6065951BecaC1dECBaC0C1A16b9BbF12913

Or through our gitbook updates : https://info.ge.finance/

**Comment by cryptomanz** [comment]
Hello,
- Awaiting for smart contract audit.

**Comment by GeFiOfficial** [comment]
> Hello,
> 
> * Awaiting for smart contract audit.

we are still waiting for smart contract audit, will upload once we received our audit report

**Comment by Cryptocool1** [comment]
Please create new PR when smart contract audit will be ready. make sure to mention this PR, so the fee can be reused.

**Pull request closed without merging**
