### PR TITLE
Add GemSpree (BEP20)

### PR DESCRIPTION
**Pull request by backfisch96**
Adding info for BEP20 token 'GemSpree'.

PR created by <a href="https://assets.trustwallet.com">TW Assets Management</a>

### CODE REVIEW

**Comment by Cryptocool1** [comment]
https://bscscan.com/token/0x47e7dd5fA9BBd280C5422E5106b1Da444344c206
website "https://wow.surf" don't match the contract website "https://worldofwaves.earth/" .

**Comment by backfisch96** [comment]
Hello @Cryptocool1 :). I was just trying to upload the token information + logo for the project GemSpree which has nothing to do with World of Waves. And yes, for World of Waves new website link is https://wow.surf and update on Bscscan has been requested for the change.

Did I do something wrong while trying to uplod information of GemSpree or how exactly can we fix this?
 
Contract-ID (GemSpree): 0x48A64f116Ce221fD7c1119775ba7892701F9911d

**Review by backfisch96 — COMMENTED** [review]
removed conflict file

**Comment by backfisch96** [comment]
conflict file removed

**Comment by backfisch96** [comment]
@zachzwei Hey there. Can you please help merging this / closing the conflict? Greetings :)

**Comment by Cryptocool1** [comment]
> @zachzwei Hey there. Can you please help merging this / closing the conflict? Greetings :)

You can't delete Wow token files this way.
please create new PR only with GemSpree token files.
When creating a new PR make sure to mention this PR, so that we can see that fee has been paid already here.

**Comment by backfisch96** [comment]
@Cryptocool1 as per your request we have new Pull request https://github.com/trustwallet/assets/pull/10282

Could you please help us merge this.

Thank you so much

**Pull request closed without merging**
