### PR TITLE
Add logo

### PR DESCRIPTION
**Pull request by Qbitlife**

### CODE REVIEW

**Comment by kolya182** [comment]
Lowercase contract address as required

**Comment by Qbitlife** [comment]
> Lowercase contract address as required

Why is my always?“The Travis CI build failed”！

**Comment by Qbitlife** [comment]
> Lowercase contract address as required

8e3a857,Thank you!!

**Comment by kolya182** [comment]
> > Lowercase contract address as required
> 
> [8e3a857](https://github.com/trustwallet/assets/commit/8e3a85727ca1d1420893d0bf9b97aeb5bbb95c2c),Thank you!!

Are you sure you did lowercase ?.

**Pull request closed without merging**
