### PR TITLE
Add BABY CAKE (BEP20)

### PR DESCRIPTION
**Pull request by babycakebsc**
Adding info for BEP20 token 'BABY CAKE'.

PR created by <a href="https://assets.trustwallet.com">TW Assets Management</a>

### CODE REVIEW

**Comment by Cryptocool1** [comment]
hello,
• What is the purpose of this token? How will it benefit Trust Wallet users?
 • How is the token being distributed? Are you conducting an airdrop?
 • Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?
 • Is the token listed on a centralized/decentralized exchange?
 • Is a Smart Contract audit completed? Where can we find this information?

**Comment by babycakebsc** [comment]
> hello,
> • What is the purpose of this token? How will it benefit Trust Wallet users?

Baby Cake is the first token on BSC to reward holders with Cake in reflections, so far about 17K Cake has been paid out to holders.

> • How is the token being distributed? Are you conducting an airdrop?

We were fair launched at 6K MC, no private sale, no presale, no airdrop, no bots, no bs just a 100% fair opportunity for all the investors.

> • Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?

Negative

> • Is the token listed on a centralized/decentralized exchange?

ZT has listed us already and we'll be chasing more exchanges after CMC & CG listings go through which have been paid for/fast tracked.

> • Is a Smart Contract audit completed? Where can we find this information?

Currently the contract is being audited by Certik & Hashex, in progress.

We're just 40 hours old round about but our community is raging for the logo to be uploaded so we're trying our best to make that happen.

**Comment by babycakebsc** [comment]
We also folllowed the advice from the last submission attempt to use the beta tool for lodging these pull requests, 10BNB in total we've spent now trying to get the logo up

**Comment by babycakebsc** [comment]
Could you please assist in getting our logo up? We've followed all the direction from the last submission, 5600+ holders are screaming for our logo to be uploaded in TG :/

**Comment by Cryptocool1** [comment]
How you will reward holders with cakes? Could you explain?

**Comment by babycakebsc** [comment]
> How you will reward holders with cakes? Could you explain?

The contract pays out Cake to holders in reflections instead of Baby Cake tokens.

You can review the full contract here: https://bscscan.com/token/0xdb8d30b74bf098af214e862c90e647bbb1fcc58c

We're the first ones to do it :)

You're welcome to join our TG: https://t.me/babycakeBSC of 7500+ people posting screenshots of their Cake reflections

**Comment by babycakebsc** [comment]
We're also concerned about people mistaking our token for another because our logo isn't up yet

**Comment by Cryptocool1** [comment]
waiting for official smart contract audit 
on hold for now

**Comment by babycakebsc** [comment]
Thank you! Audit should be done shortly... will @ you again with a link to it.

**Comment by Cryptocool1** [comment]
your logo should have transparent background.
please change

**Comment by babycakebsc** [comment]
Hi! Here is a link to a transparent version but it's only 200x200, is that ok?

**Comment by babycakebsc** [comment]
Hi! Here is a link: [https://imgur.com/rLYW8fW](url) to a transparent version but it's only 200x200, is that ok?

**Comment by babycakebsc** [comment]
Please help us get this uploaded ASAP, we've just got live on CMC and growing really fast

**Comment by babycakebsc** [comment]
We're approaching 7000 holders, rapidly growing, Techrate audit is underway, is there any chance we can get the logo uploaded ASAP?

**Comment by Cryptocool1** [comment]
> Hi! Here is a link: [https://imgur.com/rLYW8fW](url) to a transparent version but it's only 200x200, is that ok?

Снимок экрана 2021-07-20 в 17 35 02

**Comment by babycakebsc** [comment]
> > Hi! Here is a link: [https://imgur.com/rLYW8fW](url) to a transparent version but it's only 200x200, is that ok?
> 
> Снимок экрана 2021-07-20 в 17 35 02

Hi apologies, is there any trouble here, did you manage to copy paste the link to get the transparent logo version?

**Comment by babycakebsc** [comment]
[https://babycake.app/wp-content/uploads/2021/07/baby-cake-1-1475x1536.png](url)

**Comment by babycakebsc** [comment]
> your logo should have transparent background.
> please change

Hey! I have updated the logo in the directory, I haven't done this before just trying to help the devs as they're super busy.

Should be all good now!

**Comment by babycakebsc** [comment]
Please can we get some assistance on this ASAP? We are blowing up growing holders by the thousands and people are getting scammed buying into the wrong coin, please help us get our logo up.

**Comment by Cryptocool1** [comment]
is the smart contract audit ready?

**Comment by babycakebsc** [comment]
I just asked the devs where Techrate is at but I think they're asleep, I'm just worried about backlash on the project from people buying scam coins pretending to be us :/

We've just passed 17M mc from a fair launch start of 6K MC, we are blowing up...

Is there no way to speed this up or we have to wait for Techrate to finish?

Hashesh & Certik i was updated is coming after Techrate.

**Review by smercan89 — APPROVED** [review]

**Comment by babycakebsc** [comment]
image

TechRate is nearly finished!

**Comment by babycakebsc** [comment]
image

Audit is close to being finished!

**Comment by babycakebsc** [comment]
Hi team!!!

Techrate audit is done!!

Please push the logo ASAP <3

[https://babycake.app/wp-content/uploads/2021/07/Techrate-Audit-Baby-Cake.pdf](url)

**Comment by babycakebsc** [comment]
Guys we really need this ASAP... please push the logo live... we've paid 2 times and done everything you've asked...

**Comment by babycakebsc** [comment]
Crossing 50M+ MC, 20K+ holders and still no logo... people are going to suffer badly if we don't get this up... many people get confused and buy the wrong coin cause no logo...

**Comment by cryptomanz** [comment]
where is your audit? can I see it?

**Comment by babycakebsc** [comment]
Please see the link: [https://babycake.app/wp-content/uploads/2021/07/BABY-CAKE-Full-Smart-Contract-Security-Audit.pdf](url)

**Comment by babycakebsc** [comment]
Please... [https://babycake.app/wp-content/uploads/2021/07/BABY-CAKE-Full-Smart-Contract-Security-Audit.pdf](url)

**Comment by cryptomanz** [comment]
Screenshot 2021-07-22 at 19 26 56

**Comment by babycakebsc** [comment]
Please go to babycake.app and click the Techrate audit on our websites home page... I've linked it 3 times now via the URL link in this chat.

**Comment by babycakebsc** [comment]
I've just added it to GitHub as well now... please get this uploaded for us ASAP.

**Comment by Cryptocool1** [comment]
Seen
blockchains/smartchain/assets/0xdB8D30b74bf098aF214e862C90E647bbB1fcC58c/BABY CAKE Full Smart Contract Security Audit.pdf
delete this file from your files please

**Comment by babycakebsc** [comment]
Deleted, please upload the logo.

**Review by smercan89 — COMMENTED** [review]
T

**Pull request merged**
