### PR TITLE
Add DragonSlayer (BEP20)

### PR DESCRIPTION
**Pull request by dragonslayergames**
Adding info for BEP20 token 'DragonSlayer'.

PR created by <a href="https://assets.trustwallet.com">TW Assets Management</a>

### CODE REVIEW

**Comment by dragonslayergames** [comment]
Hi !
This is our pull request:  https://github.com/trustwallet/assets/pull/13012
(All information is real)
Please help us add a logo on the trust wallet.
I think PR FEE is too high now because the price of TWT is going up. (TWT
price increases multiplied 4 times from the price of 2 months ago)
One more thing, Could check and submit our logo before we make a payment.
I swear that if you accept our logo we will pay 500~1000 TWT.
Our project is real but it's not a big project.
We have to save money to do other plans (invite more developers, rent a
higher server,...)
If you have any concerns please let me know
I am waiting for your reply.
Kind regards

Vào Th 2, 23 thg 8, 2021 vào lúc 23:43 merge-fee-bot[bot] <
***@***.***> đã viết:

**Comment by cryptomanz** [comment]
hello, sorry we have the fee 2000 two or 5BNB 
If you want to add your token information, please pay the fee

**Comment by dragonslayergames** [comment]
> hello, sorry we have the fee 2000 TWT or 5BNB
> If you want to add your token information, please pay the fee

Hi Cryptomanz, Please let me know about something.
1. If we donate 2000 TWT, our logo will be added to trust wallet ?
2. Please ask me if i need do more to complete this request !
After this we will donate 2000 TWT

**Comment by dragonslayergames** [comment]
Please let me know about something.

   1. If we pay the fee 2000 TWT, will our logo be added to Trust-wallet ?
   How long will it appear on the Trust-wallet ?
   2. Please ask me if I need to do more to complete this request !
   Please reply to us soon, I have to push our marketing campaign soon.
   Please support us !
   Thank you so much !


Vào Th 3, 24 thg 8, 2021 vào lúc 01:37 Nazar ***@***.***>
đã viết:

**Comment by cryptomanz** [comment]
Can your answer some questions?
• What is the purpose of this token? How will it benefit Trust Wallet users?
 • How is the token being distributed? Are you conducting an airdrop?
 • Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?
 • Is the token listed on a centralized/decentralized exchange?
 • Is a Smart Contract audit completed? Where can we find this information?

**Comment by dragonslayergames** [comment]
I would like to answer your questions below:
1. Dragon Slayer Project is a NFT gaming ecosystem aiming to build a vast
Dragon Universe living on the Binance Smart Chain where millions of players
all around the world participate in the blockchain-based NFT game in a
simple, fast and fun way.  $DragonSlayer (DRS) is the primary utility token
of the Dragon-Slayer ecosystem. It simplifies the payment process and
supports the growth of the ecosystem.
The Dragon Slayer NFT Marketplace provides you with the opportunity to
create (or as we call it, mint), sell, purchase, bid on, collect, trade,
showcase and otherwise. With high liquidity, Dragon Slayer NFT Marketplace
is a peer-to-peer marketplace for NFTs collected or created in the games
that users can trade easily and quickly on 24/7 basis. Rare digital NFTs
items can be stored securely and displayed in NFTs Marketplace.
2. The Game provides a swap function on our website play.dragonslayer.games
to help users play, earn token DRS.
Trust Wallet users can use Pancakeswap DEX; Bogswap dex and SWAP ZT Global
exchange to trade DRS tokens.
We have completed distribution of 2 airdrops for our members.
3. We did a token pre-sale on DxSale.app before listing on other Dex and
Exchange.
4. At the moment, Our tokens were listed on Pancakeswap DEX; Bogswap dex;
SWAP ZT Global exchange,...Now people can check all information about DRS
on coinmarketcap.com & coingecko.com.
5. Yes, our smart contract was verified and audited by Fairaudit.
This is proof link: 0xc8e8ecb2a5b5d1ecff007bf74d15a86434aa0c5c.pdf
(fairaudit.finance)
<https://www.fairaudit.finance/secure/0xc8e8ecb2a5b5d1ecff007bf74d15a86434aa0c5c.pdf>
I would like to add more proof link:
- https://coinmarketcap.com/currencies/dragon-slayer/
- https://www.coingecko.com/en/coins/dragon-slayer
- Website: https://www.dragonslayer.games/
- ZT Global: https://www.ztbzh.net/exchange?coin=DRS_USDT
- Bscscan:
https://bscscan.com/address/0xc8e8ecb2a5b5d1ecff007bf74d15a86434aa0c5c
If you need anything more please let us know.
Vào Th 3, 24 thg 8, 2021 vào lúc 17:34 Nazar ***@***.***>
đã viết:

**Comment by dragonslayergames** [comment]
@catenocrypt, Cryptocool1 and zachzwei Please check our request !

**Pull request merged**
