### PR TITLE
Add EtherMail Project to Base Chain

### PR DESCRIPTION
**Pull request by SebasAran16**
Hello team,

Opening PR to include our company data again, as we have both the required holders (>10K) and transactions (>15K) that we were told previously.

Would appreciate if you could review for once everything is in order continue to the payment for the pull.

Thanks!

### CODE REVIEW

**Comment by SebasAran16** [comment]
There was a commit pushed to correct data from bot's feedback

**Comment by SebasAran16** [comment]
Perfect, we were waiting for your confirmation to do.

Will let you know with tx hash when done.

**Comment by Cryptocool1** [comment]
• What is the purpose of this token? How will it benefit Trust Wallet users?
 • How is the token being distributed? Are you conducting an airdrop?
 • Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?
 • Is the token listed on a centralized/decentralized exchange?
 • Is a Smart Contract audit completed? Where can we find this information?

**Comment by SebasAran16** [comment]
1. The purpose of the Token is to give rewards to users for actively participating in Consensual Marketing campaigns, distributing the earnings the company has with them. Main benefit for Trust wallet users is a web3 native end-to-end encrypted mail platform that they can use and opt-in to receive benefits out of the Consensual Marketing campaigns with a real Read2Earn.
2. The token is distributed through our quarterly airdrop through our so called "Pools". Pool 0 (early adopers) and Pool 1 just released and is currently being claimed. Pool 2 rewards are being accumulated. Information on the Pools can be found here:
   - https://ethermail.io/emt/pools/0/status
   - https://ethermail.io/emt/pools/1/status
3. Yes, our ICO was done through Gate
4. The token is listed on the following:
    - Decentralized: 
    1. Uniswap
    - Centralized: 
    1. Gate
    2. Bitget
    3. Mexc
5. Yes, all of our Smart Contracts were audited by Certik, information can be found here: https://skynet.certik.com/projects/ethermail

**Comment by SebasAran16** [comment]
Hello are there any news about the process? Any more information needed @Cryptocool1 ?

**Pull request merged**
