### PR TITLE
Add Blombard (BEP20)

### PR DESCRIPTION
**Pull request by Vasilii79**
Adding info for BEP20 token 'Blombard'.

PR created by <a href="https://assets.trustwallet.com">TW Assets Management</a>

### CODE REVIEW

**Comment by Vasilii79** [comment]
Hello, Trustwallet team! 
The payment is done: https://bscscan.com/tx/0x74efbe4b832869fdc90ff03a851d5a0b8e580f9f58b7b3bfbe0224e0c1f26990
Please add a BLM token. It's already on CMC: https://coinmarketcap.com/currencies/blombard/

**Comment by Jeffearp** [comment]
Trying to recover assets can someone help

**Comment by Vasilii79** [comment]
Dear @Cryptocool1, @cryptomanz1 kindly look at our request to add the BLM token.
 It's already on CMC: https://coinmarketcap.com/currencies/blombard/
 All auto-checks and payment have been completed.

**Comment by cryptomanz1** [comment]
What is the purpose of this token? How will it benefit Trust Wallet users?
 • How is the token being distributed? Are you conducting an airdrop?
 • Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?
 • Is the token listed on a centralized/decentralized exchange?
 • Is a Smart Contract audit completed? Where can we find this information?

**Comment by Vasilii79** [comment]
> What is the purpose of this token? How will it benefit Trust Wallet users? • How is the token being distributed? Are you conducting an airdrop? • Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale? • Is the token listed on a centralized/decentralized exchange? • Is a Smart Contract audit completed? Where can we find this information?

Hello, @Cryptocool1.
Please find the replies below:

1. What is the purpose of this token? How will it benefit Trust Wallet
users?
Answer: The BLM token is the native utility token of the Blombard
platform, designed to enhance users' trading experiences by providing
access to advanced AI-driven analytics, market sentiment analysis, and
risk management tools. Trust Wallet users holding BLM tokens will
benefit from exclusive access to Blombard’s premium services, including
automated trading signals, real-time market analysis, and the ability to
participate in our decentralized governance model. Additionally, users
can utilize BLM tokens to pay for transaction fees and services within
the Blombard ecosystem, making it a valuable asset for trading and
accessing advanced financial tools.

2. How is the token being distributed? Are you conducting an airdrop?
Answer: The distribution of BLM tokens is being carried out primarily
through our platform and a professional Telegram bot specifically
designed for airdrops. We have already conducted an airdrop to early
adopters and community members to ensure broad initial distribution and
incentivize participation in the Blombard ecosystem. The Telegram bot
streamlines the airdrop process, allowing users to easily participate.
You can access the airdrop bot here: t.me/Blombard_com_bot.

3. Did you sell the tokens at an Initial Coin Offering (ICO) or a token
presale?
Answer: No, we did not conduct an Initial Coin Offering (ICO) or a token
presale. The distribution of BLM tokens has been managed through
airdrops and community incentives, focusing on creating value and
utility within the Blombard platform rather than through public or
private sales.

4. Is the token listed on a centralized/decentralized exchange?
Answer: Yes. BLM is currently listed on the Tokpie exchange, where it can be
traded via the BLM/USDT trading pair. You can find more details here:
tokpie.com/view_exchange/blm-usdt/. We are in the process of listing on
additional exchanges. Also, BLM is on the CMC: https://coinmarketcap.com/currencies/blombard/.

5. Is a Smart Contract audit completed? Where can we find this information?
Answer: Yes, here is the link: https://github.com/TechRate/Smart-Contract-Audits/blob/main/September_2024/Blombard.pdf

**Comment by Vasilii79** [comment]
Dear @cryptomanz1, thanks for token adding. But kindly inform why the price is not visible on Trust Wallet for BLM token?

The token is already listed on CMC: https://coinmarketcap.com/currencies/blombard/
and on Coingecko: https://www.coingecko.com/en/coins/blombard
Also, it has a tracked price on Bscscan: https://bscscan.com/token/0xA82D8d81557f6Da6dd4DDAD9f09a417530cfd4e7

**Pull request merged**
