### PR TITLE
Add Litherium (BEP20)

### PR DESCRIPTION
**Pull request by 0xBenxx211226**
Adding info for BEP20 token 'Litherium'.

PR created by <a href="https://assets.trustwallet.com">TW Assets Management</a>

### CODE REVIEW

**Comment by LITHYI** [comment]
Hi I have paid the TWT, hash: 6095DD9821E4C4FE35956F8AC9C84A18FFDCC06C5C00247F69C50AD7C11E4B3F, Memo:15460

**Comment by LITHYI** [comment]
• What is the purpose of this token? How will it benefit Trust Wallet users?
Litherium trying to bind the value of the physical lithium concentrate, in order to further improve the circulation and value of the virtual currency in the society. It also provide future empowerment for the trust wallet and the cryptocurrency field. 

• How is the token being distributed? Are you conducting an airdrop?
50% of total supply and 80% of Pancakeswap LP has been locked in Dxsale. We were conducing airdrop event but we just stopped it. 

• Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?
Yes, we did. we sold around 3% total supply in ICO. 

• Is the token listed on a centralized/decentralized exchange?
Yes, The token listing on Pancakeswap, trading volum around 2M per day. 

• Is a Smart Contract audit completed? Where can we find this information?
Audit hasn't completed yet, we are not sure who can do that becuase too many scams now

**Comment by cryptomanz** [comment]
Here is the example of smart contract audit: https://www.certik.org/projects/binance
Awaiting for smart contract audit.

**Comment by LITHYI** [comment]
Sure, I just arrage someone do that for us, it takes three working days for audit, where should I submite the report after his audit?

**Comment by ramsty** [comment]
You could provide link to smart contract audit here. On hold for now.

**Comment by Cryptocool1** [comment]
Feel free to open new PR when smart contract audit will be ready
When creating a new PR make sure to mention this PR, so that we can see that fee has been paid already here.

**Comment by LITHYI** [comment]
Hi Trust Team,

Here is the Audit report link worked by eNebula:
https://drive.google.com/file/d/1fX8SzrLEGlARlqURqDYBU6KR0dDlagx-/view

We will soon upload to our offcial website, pls keep processing our 
Token logo update.Thank you.


Best
Litherium

**Comment by LITHYI** [comment]
Hi Trust Team,

This is the audit report, please process our token logo update, thanks a 
lot.
https://www.my-lith.com/Litherium%20audit.pdf

Best
LItherium

**Pull request closed without merging**
