### PR TITLE
 Add logo

### PR DESCRIPTION
**Pull request by forex40io**
This PR is being closed due to inactivity. If you wish to continue, please have us reopen the PR before sending your payment.
Do NOT send payments for closed PR, as the fee may by lost!
  (60 vs. 60 hrs)

### CODE REVIEW

**Comment by forex40io** [comment]
https://explorer.binance.org/tx/1B0D5A8490FB1B5F4C168B139CCFDD3B4D51B85DC0E8BEC84E38228C4051A42A

**Comment by forex40io** [comment]
i paid

**Comment by forex40io** [comment]
fee 2 bnb? i am sorry , can i send 1 bnb to this address with 4099 memo again?

**Comment by Iamdeadlyz** [comment]
> fee 2 bnb? i am sorry , can i send 1 bnb to this address with 4099 memo again?

Yes, you can.

**Comment by catenocrypt** [comment]
As per our policy, brand new tokens are not included, there is a minimum requirement of 500 holder addresses and 1000 transactions, in order to filter out scam tokens.
See the criteria at (mentioned in the first message by the bot): https://community.trustwallet.com/t/how-to-submit-a-token-logo/3863#how-to-get-approved
This token has below-limit usage yet. Rejecting PR for now. Please come back to us when all criteria are met.

- first: 169 holder addresses   https://etherscan.io/token/0x2Eb047352BD8F2C6cAded05c0e264BDF770de5d6
- second:  45 addresses https://etherscan.io/token/0xEE99B73449B23466761918B59142Fe94490c2492

**Comment by catenocrypt** [comment]
> fee 2 bnb? i am sorry , can i send 1 bnb to this address with 4099 memo again?

Sorry, I see this now.  Yes, you can pay additional sum, the bot will pick that up too, and consider the total.  Don't forget to set memo.  I closed thinking it was not paid, now I reopened the PR.

**Pull request closed without merging**
