### PR TITLE
Add VBoom (BEP20)

### PR DESCRIPTION
**Pull request by gomanje**
Adding info for BEP20 token 'VBoom'.

PR created by <a href="https://assets.trustwallet.com">TW Assets Management</a>

### CODE REVIEW

**Review by alice22foster — COMMENTED** [review]
Request changes

**Comment by gomanje** [comment]
What we are waiting for ?

**Review by gomanje — COMMENTED** [review]
Thank's A lot

**Review by gomanje — COMMENTED** [review]
did you deduct the payment from my wallet ?

**Comment by Cryptocool1** [comment]
As per our policy, there is a minimum requirement of 10,000 holder addresses and 15,000 transactions, in order to filter out scam tokens.
See the criteria at : https://developer.trustwallet.com/listing-new-assets/requirements .

**Pull request closed without merging**
