### PR TITLE
Add Golden Doge (BEP20)

### PR DESCRIPTION
**Pull request by goldendoge719**
Adding info for BEP20 token 'Golden Doge'.

PR created by <a href="https://assets.trustwallet.com">TW Assets Management</a>

### CODE REVIEW

**Comment by goldendoge719** [comment]
> Hello,
> Can your answer some questions?
> • What is the purpose of this token? How will it benefit Trust Wallet users?
> • How is the token being distributed? Are you conducting an airdrop?
> • Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?
> • Is the token listed on a centralized/decentralized exchange?
> • Is a Smart Contract audit completed? Where can we find this information?

Hi!
- The purpose of this token is to benefits its holders from 5% of all transactions.
We have a golden vault which gets filled by 5% of every transaction and Trust Wallet users can claim the reward from Golden Vault in BNB every 24 hours. They have to connect their Trust Wallets to our Golden Vault to claim their reward.
https://goldendoge.finance/claim-bnb/
They really love it. 
- We airdropped yesterday only once when we reached 4900 holders. Yes we airdrop from our submission form on our homepage.
- yes, we had an ILO on Unicrypt (https://app.unicrypt.network/amm/pancake-v2/ilo/0xb44d431c926e159a688fe167Fe2865Cff69Dabba)
- We are going to be listed on LBank tomorrow. The deal is finalized and announcement has already been made on social media.
- yes, the audit has been completed by Techrate. (https://github.com/TechRate/Smart-Contract-Audits/blob/main/GoldenDoge%20Standart%20Smart%20Contract%20Security%20Audit.pdf)

**Comment by goldendoge719** [comment]
> Hello,
> Can your answer some questions?
> • What is the purpose of this token? How will it benefit Trust Wallet users?
> • How is the token being distributed? Are you conducting an airdrop?
> • Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?
> • Is the token listed on a centralized/decentralized exchange?
> • Is a Smart Contract audit completed? Where can we find this information?

Is this info enough? Or you still need any other info from us?

**Comment by cryptomanz** [comment]
Are you listed on Lbank now?

**Comment by goldendoge719** [comment]
> Are you listed on LBank now?

We will be listed in 5 hours for trading. They can deposit now.
Please check.
https://twitter.com/LBank_Exchange/status/1417835947232698368?s=20

**Comment by goldendoge719** [comment]
> Are you listed on LBank now?

We are also going to be listed on ZT Global in 3 hours.
https://twitter.com/ZT_exchange/status/1418497320014913537
https://support.clfxpx.com/hc/en-001/articles/4404020625177
image

**Pull request merged**
