### PR TITLE
Logo updated

### PR DESCRIPTION
**Pull request by saylormoonarmy**
This PR is being closed due to inactivity. If you wish to continue, please have us reopen the PR before sending your payment, or just create a new one.
Do NOT send payments for closed PR, as the fee may by lost!
  (48 vs. 48 hrs)

### CODE REVIEW

**Comment by saylormoonarmy** [comment]
logo updated

**Comment by saylormoonarmy** [comment]
The fee was already payed, this is just a logo update

**Comment by Cryptocool1** [comment]
> The fee was already payed, this is just a logo update El 14/6/21 a las 18:23, merge-fee-bot[bot] escribió:
> […](#)

what number of payed PR ?

**Comment by saylormoonarmy** [comment]
8778, in thar PR we payed the fee, let us know, thanks

**Comment by Cryptocool1** [comment]
> 8778, in thar PR we payed the fee, let us know, thanks El 14/6/21 a las 21:31, CryptoA escribió:
> […](#)

hello,
you need to pay for updating.

**Comment by Cryptocool1** [comment]
> 8778, in thar PR we payed the fee, let us know, thanks El 14/6/21 a las 21:31, CryptoA escribió:
> […](#)

8838 merged

**Comment by saylormoonarmy** [comment]
We already payed the fee

**Pull request closed without merging**
