### PR TITLE
Add metaraca info

### PR DESCRIPTION
**Pull request by metaraca**
Create metaraca logo and information

### CODE REVIEW

**Comment by metaraca** [comment]
FYI: x Low token circulation: no. of holders is 11666, below limit of 25000

Hi, our token is audited and the liquidity also locked. Please help me to pass this condition. Thank you.

**Comment by cryptomanz** [comment]
Submission looks good, awaiting for fee payment

**Comment by metaraca** [comment]
> Submission looks good, awaiting for fee payment

Just paid. Please help me to check

**Comment by leedaniil** [comment]
@cryptomanz we receive the payment, it's ok

**Comment by leedaniil** [comment]
@cryptomanz Bot couldn't send a message that we received the payment! I'm fixing it

**Comment by cryptomanz** [comment]
• What is the purpose of this token? How will it benefit Trust Wallet users?
 • How is the token being distributed? Are you conducting an airdrop?
 • Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?
 • Is the token listed on a centralized/decentralized exchange?
 • Is a Smart Contract audit completed? Where can we find this information?

**Comment by metaraca** [comment]
• What is the purpose of this token? How will it benefit Trust Wallet users?
Metarverse + Raca = MetaRaca, a collection of puppies in the form of NFTs. We're a dedicated team that want to build something for the crypto community in general and the $RACA lovers in particular.
We are listed on CoinMarketCap and CoinGecko, we would like to be list on Trust Wallet so our holders can view the price changes through Trust Wallet.

• How is the token being distributed? Are you conducting an airdrop?
The token is being sold at Pancakeswap . We also conduct Airdrop Campaign with 1% of Total supply.

• Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?
Metaraca token had token presale on pinksale.

• Is the token listed on a centralized/decentralized exchange?
The token is being listed at Pancakeswap.

• Is a Smart Contract audit completed? Where can we find this information?
Smart contract audit is done by Dessertswap

You can view it at https://dessertswap.finance/audits/Metaraca%20-%20BSC%20REPO%20Audit.pdf

**Comment by metaraca** [comment]
> number of holders not checked, external info not available

Hi, please tell me about this error. What info is not available?

**Comment by metaraca** [comment]
@cryptomanz Please help me to check.

**Pull request merged**
