### PR TITLE
Add BEX (BEP20) token

### PR DESCRIPTION
**Pull request by belecx**

### CODE REVIEW

**Comment by belecx** [comment]
Token check error:
❌ number of holders not checked: please, check it manually

How to do it?

**Comment by Cryptocool1** [comment]
> Token check error: ❌ number of holders not checked: please, check it manually
> 
> How to do it?

your number of holders - OK

**Comment by cryptomanz** [comment]
• What is the purpose of this token? How will it benefit Trust Wallet users?
 • How is the token being distributed? Are you conducting an airdrop?
 • Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?
 • Is the token listed on a centralized/decentralized exchange?
 • Is a Smart Contract audit completed? Where can we find this information?

**Comment by belecx** [comment]
> • What is the purpose of this token? How will it benefit Trust Wallet users? • How is the token being distributed? Are you conducting an airdrop? • Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale? • Is the token listed on a centralized/decentralized exchange? • Is a Smart Contract audit completed? Where can we find this information?

1. The significance of Token is that users can use it to complete farm mining, NFT holding, and other holdings of encrypted assets.
Users of Trust Wallet open the website in the wallet and can directly connect to use it, which is very convenient.

2. Token distribution: 20% for the team, 70% for farm mining, and 10% for NFT holders.
When selling, 5% is added to liquidity. 3% recycled. 2% burn

3. No ICO

4. List the BEX-USDT trading pair on the cointiger exchange
https://www.cointiger.com/en-us/#/trade_center?coin=bex_usdt

5. Smart Contract audit completed
1️⃣ Audit By Auth Lab : https://authlab.com/community/auth-labs-security-audit-team-has-done-audit-for-belecx-tokenbex/

2️⃣ Audit By DPTECH :
Audit Report:
https://www.dpanquan.com/storage/13318/files/20220318/20220318103113_97083.pdf

**Pull request merged**
