### PR TITLE
Tokyo Inu Added to trust wallet

### PR DESCRIPTION
**Pull request by tokyoinu**
Tokyo Inu Contract info and logo

### CODE REVIEW

**Comment by Cryptocool1** [comment]
PR should include only 2 files:
blockchains/smartchain/assets/0xE405f6Ae74ad3efD31C23A40CE23b3D3A3B95FB9/info.json
blockchains/smartchain/assets/0xE405f6Ae74ad3efD31C23A40CE23b3D3A3B95FB9/logo.png

**Comment by tokyoinu** [comment]
> PR should include only 2 files:
> blockchains/smartchain/assets/0xE405f6Ae74ad3efD31C23A40CE23b3D3A3B95FB9/info.json
> blockchains/smartchain/assets/0xE405f6Ae74ad3efD31C23A40CE23b3D3A3B95FB9/logo.png

Yes we only have 2 files on it. 

it shows ok

Token BEP20 - 0xE405f6Ae74ad3efD31C23A40CE23b3D3A3B95FB9:
Symbol: TOKI decimals: 9
Links: Logo Info Website Explorer (check OK 🙂)

how do we fix it if there's issue

**Comment by tokyoinu** [comment]
Please see proof 
image

**Comment by tokyoinu** [comment]
hi anyone replying? how are me getting the project rectify?

**Comment by tokyoinu** [comment]
> PR should include only 2 files:
> blockchains/smartchain/assets/0xE405f6Ae74ad3efD31C23A40CE23b3D3A3B95FB9/info.json
> blockchains/smartchain/assets/0xE405f6Ae74ad3efD31C23A40CE23b3D3A3B95FB9/logo.png

hi there anyone assist? 

we have created another pull request: 8117. 

we want to get this resolve, any one reply?\

**Comment by tokyoinu** [comment]
@Cryptocool1 @catenocrypt @zachzwei @hexorx 

any news?

**Pull request closed without merging**
