### PR TITLE
Add Chihuahua (BEP20)

### PR DESCRIPTION
**Pull request by chihuahuabsc**
Adding info for BEP20 token 'Chihuahua'.

PR created by <a href="https://assets.trustwallet.com">TW Assets Management</a>

### CODE REVIEW

**Comment by chihuahuabsc** [comment]
Hey. Can we proceed with payment?

**Comment by Cryptocool1** [comment]
• What is the purpose of this token? How will it benefit Trust Wallet users?
 • How is the token being distributed? Are you conducting an airdrop?
 • Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?
 • Is the token listed on a centralized/decentralized exchange?
 • Is a Smart Contract audit completed? Where can we find this information?
 • How did you get more than 10k holders in 1 week?

**Comment by chihuahuabsc** [comment]
Hi Cryptocool1

- The token provide automatic reflections and we will be rolling out a staking contract very soon. NFTs for token holders are also planned in the future. Broadly speaking, the main purpose of the project is spreading animal adoption awareness and we have plans to coordinate with animal shelters and create NFT collections in collab with them

- This token is being bought/sold on PancakeSwap.

- We had a presale on [PinkSale](https://www.pinksale.finance/launchpad/0xB410e44b3f22f1A4a8125baBD74e5A6C07d1dfdb?chain=BSC)

- We are listed only on PancakeSwap currently

- Our SmartContract is [audited](https://github.com/ContractChecker/audits/blob/main/Chihuahua_Token_0x2fd6c9B869Dea106730269E13113361b684f843a_Smart_Contract_Security_Audit_By_ContractChecker.pdf). In addition, our team is [KYC'd with a third-party](https://github.com/ContractChecker/KYC/blob/main/Chihuahua_Token_0x2fd6c9B869Dea106730269E13113361b684f843a_KYC_Certificate_By_ContractChecker.pdf)

- We originally had over 1 thousand participants in our presale. With the help of aggressive marketing and being listed on aggregators like Coingecko and Coinmarketcap we managed to get around 2-3k new holders daily. Even, without much marketing this week, we are still getting 300+ holders daily due to a network effect.

**Comment by Cryptocool1** [comment]
are you listed on CoinMarketCap ?

**Comment by chihuahuabsc** [comment]
> are you listed on CoinMarketCap ?

Yes, you can find our listing by following this link https://coinmarketcap.com/currencies/chihuahua-token-19fcd0de-eb4d-4fd7-bc4a-a202247dfdbb/

**Comment by Cryptocool1** [comment]
Submission looks good, awaiting for the fee payment

**Pull request merged**
