### PR TITLE
Add ethbox Token (EBOX) (BEP20)

### PR DESCRIPTION
**Pull request by ebox-official**
This PR is being closed due to inactivity. If you wish to continue, please have us reopen the PR before sending your payment, or just create a new one.
Do NOT send payments for closed PR, as the fee may by lost!
  (48 vs. 48 hrs)

### CODE REVIEW

**Comment by cryptomanz** [comment]
As per our policy, brand new tokens are not included, there is a minimum requirement of 5000 holder addresses and 10000 transactions, in order to filter out scam tokens.
See the criteria at (mentioned in the first message by the bot): https://community.trustwallet.com/t/how-to-submit-a-token-logo/3863).
Closing PR for now. Please come back to us when all criteria are met.

**Comment by ethbox-official** [comment]
> As per our policy, brand new tokens are not included, there is a minimum requirement of 5000 holder addresses and 10000 transactions, in order to filter out scam tokens.
> See the criteria at (mentioned in the first message by the bot): https://community.trustwallet.com/t/how-to-submit-a-token-logo/3863).
> Closing PR for now. Please come back to us when all criteria are met.

We had written an e-mail regarding this subject to support@trustwallet.com, asking for an exemption from the 5k holder / 10k transaction rule, given how we are a legitimate, established project. Is it possible to manually review our case?

**Comment by zachzwei** [comment]
Please settle the fee so that we can approve.

**Comment by ethbox-official** [comment]
> Please settle the fee so that we can approve.

Can we consider our request accepted then? Just asking to be certain before transferring the fee - If everything is set from your side, please re-open the PR, and we will transfer immediately.

**Pull request closed without merging**
