### PR TITLE
Add AFU to TrustWallet

### PR DESCRIPTION
**Pull request by mazelaa**

### CODE REVIEW

**Comment by catenocrypt** [comment]
This PR has two tokens:
- AFU: TRC10 token, with only 195 holder addresses.  This will not be included nopw, as it is less than 500. https://tronscan.io/#/token/1003356
- ZPAY: TRC20 token, with over 39K holder addresses.  https://tronscan.io/#/token20/TLGd97zsjrkomUDF962ZFMerdQxPffG7hX

Please remove AFU token.

**Comment by mazelaa** [comment]
Deleted one of those.

**Comment by catenocrypt** [comment]
You kept the one with the low circulation.

**Comment by catenocrypt** [comment]
As per our policy, brand new tokens are not included, there is a minimum requirement of 500 holder addresses and 1000 transactions, in order to filter out scam tokens.
See the criteria at (mentioned in the first message by the bot): https://community.trustwallet.com/t/how-to-submit-a-token-logo/3863#how-to-get-approved
This token has low usage yet (195). Rejecting PR for now. Please come back to us when all criteria are met.

https://tronscan.io/#/token/1003356

**Comment by mazelaa** [comment]
Ok I will add the other one again

**Comment by mazelaa** [comment]
See https://github.com/trustwallet/assets/pull/4246
Already paid here :)

**Pull request closed without merging**
