### PR TITLE
Add TSC info and logo

### PR DESCRIPTION
**Pull request by trustercoin**
Add TrusterCoin (TSC) info and logo

### CODE REVIEW

**Comment by Cryptocool1** [comment]
As per our policy, brand new tokens are not included, there is a minimum requirement of 5000 holder addresses and 10000 transactions, in order to filter out scam tokens.
See the criteria at (mentioned in the first message by the bot): https://community.trustwallet.com/t/how-to-submit-a-token-logo/3863).

**Comment by cryptomanz** [comment]
Hello,
Can your answer some questions?
 • What is the purpose of this token? How will it benefit Trust Wallet users?
 • How is the token being distributed? Are you conducting an airdrop?
 • Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?
 • Is the token listed on a centralized/decentralized exchange?
 • Is a Smart Contract audit completed? Where can we find this information?

**Comment by Cryptocool1** [comment]
still no answer 
please create new PR when you will be ready to chat (make sure to mention this PR)

**Comment by trustercoin** [comment]
Hello guys,
sorry our delay. our dev was sick (Covid-19 vaccine side effects)

• **What is the purpose of this token? How will it benefit Trust Wallet users?**

- _Purpose_: TrusterCoin is a utility token for use on tokenization platforms at a time when business people face one of the greatest challenges in history. The platform will allow the creation of new tokenization tokenization of small, medium to large companies through blockchain technology.

_Benefits_: 
- Best App for anyone use, easy connect to Pancake V2 and keep the user's Token/Coins safe .
- To avoid buy wrong TrustCoin (TSC) Token. Unfortunately, there a lot of Token with same name and symbol (SCAM).
- Easy to send and receive (because the TrustWallet send a push notification by any  status change) .

Token Tracker listed on (Coingecko):  https://www.coingecko.com/en/coins/trustercoin 

• **How is the token being distributed? Are you conducting an airdrop?**
Only buy direct buy from PancakeSwap V2. We're not conducting any airdrop yet, but it's in our roadmap soon.

• **Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?**
There is no presale or ICO, all sale is only via PancakeSwap by direct link: 
- https://exchange.pancakeswap.finance/#/swap?inputCurrency=BNB&outputCurrency=0xA2a26349448ddAfAe34949a6Cc2cEcF78c0497aC

• **Is the token listed on a centralized/decentralized exchange?**
No, the sales are done only via PancakeSwap V2 (direct link above).

• **Is a Smart Contract audit completed? Where can we find this information?**
Yes, because is the same smart contract used by SAFEMOON, but using the new one PancakeSwap V2: 0x10ED43C718714eb63d5aA57B78B54704E256024E

- _SAFEMOON's Certik Audit_: https://www.certik.org/projects/safemoon

- _SAFEMOON's source code_: https://bscscan.com/address/0x8076c74c5e3f5852037f31ff0093eeb8c8add8d3#code
- _TrusterCoin (TSC)'s source code_: https://bscscan.com/address/0xa2a26349448ddafae34949a6cc2cecf78c0497ac#code

**Pull request closed without merging**
