### PR TITLE
added Flokinomics assets for submission

### PR DESCRIPTION
**Pull request by hotdamn97**

### CODE REVIEW

**Comment by cryptomanz** [comment]
Hello,
Can your answer some questions?
• What is the purpose of this token? How will it benefit Trust Wallet users?
 • How is the token being distributed? Are you conducting an airdrop?
 • Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?
 • Is the token listed on a centralized/decentralized exchange?
 • Is a Smart Contract audit completed? Where can we find this information?

**Comment by hotdamn97** [comment]
1) Flokinomics is the first-ever token on the BSC smart chain to combine
rebase tokenomics with Doge rewards. Hold $FLOKIN and receive $DOGE
directly to your BEP-20 wallet as a reward for holding.

2) Initial distribution was done on pinksale via a presale along with a
small 5% distribution via private sale. Rest everything added to liquidity
on pancake swap and available to trade

3) Yes, a presale took place at pinksale of 300bnb.

4) Yes, the token is listed at pancakeswap.

5) Yes, our Smart Contract audit is completed and was done by Techrate (
https://www.flokinomics.com/audits ).

**Comment by cryptomanz** [comment]
Сan you please add links to your PR?
example:https://developer.trustwallet.com/assets/repository_details
Screenshot 2021-10-06 at 20 22 37

**Comment by hotdamn97** [comment]
done! all links fixed! phew :)
thanks

**Comment by hotdamn97** [comment]
All changes are done!

**Comment by hotdamn97** [comment]
Hey,

I need to update my logo on Trustwallet.
What is the process?

Thanks

**Pull request merged**
