### PR TITLE
Add CROX logo and info

### PR DESCRIPTION
**Pull request by dexdevz**
Add CroxSwap logo and description

### CODE REVIEW

**Review by croxswap — COMMENTED** [review]
changed to checksum format

**Review by croxswap — COMMENTED** [review]
Renamed

**Comment by catenocrypt** [comment]
Correction needed:  Please remove the 2 files which are in the all-lowercase folder.

image

**Comment by croxswap** [comment]
Deleted small case files as requested

**Review by croxswap — COMMENTED** [review]
Removed lower case files

**Pull request merged**
