### PR TITLE
Add SafeUniverse V2 (BEP20)

### PR DESCRIPTION
**Pull request by suppor-safeuniverse**
Adding info for BEP20 token 'SafeUniverse V2'.

PR created by <a href="https://assets.trustwallet.com">TW Assets Management</a>

### CODE REVIEW

**Comment by catenocrypt** [comment]
The 2500 holders requirement is met, but the 5000 transactions is not yet.  Putting on hold.
2999 holders and 3002 transactions, looks like artificially generated transactions to get past the limit.

**Comment by suppor-safeuniverse** [comment]
> The 2500 holders requirement is met, but the 5000 transactions is not yet. Putting on hold.
> 2999 holders and 3002 transactions, looks like artificially generated transactions to get past the limit.

Hi. we are a not artificially generated transactions.. we run social campaign for our token and distribute the token to the corresponding users who are pass the task. at present we have a 100k followers on telegram https://t.me/SAFUniverse. which is one of the biggest active group. so kindly do the needful.

**Review by suppor-safeuniverse — COMMENTED** [review]
Kindly do the needful

**Review by suppor-safeuniverse — COMMENTED** [review]
Kindly do the needful

**Pull request merged**
