### PR TITLE
Add Liquidity Dividends Protocol (LID)

### PR DESCRIPTION
**Pull request by carlsbad-sunshine**
This PR is being closed due to inactivity. If you wish to continue, please reopen the PR before sending your payment.
Do NOT send payments for closed PR, as the fee may by lost!
  (60 vs. 60 hrs)

### CODE REVIEW

**Comment by carlsbad-sunshine** [comment]
https://explorer.binance.org/tx/D96C12AB0E1D98DD62A39A6D5DEA76F92FA6068EADB5F9C964B19F62D01B44E9
1 BNB sent.

**Comment by catenocrypt** [comment]
Payment amount is a bit too short, 0.9283025 BNB, please do another transfer with the rest up to 1.0 BNB.

image

**Comment by carlsbad-sunshine** [comment]
Hello! Is there an issue with the payment?

**Comment by carlsbad-sunshine** [comment]
Resent 1 BNB. https://explorer.binance.org/tx/723C220BEF1D284B54378E10C95530151CD6FEC5B631B7E76EA1C1D2325B7641

**Comment by carlsbad-sunshine** [comment]
Substantially more than 1 BNB was sent. We'd love to get our logo up!
https://explorer.binance.org/tx/D96C12AB0E1D98DD62A39A6D5DEA76F92FA6068EADB5F9C964B19F62D01B44E9
https://explorer.binance.org/tx/723C220BEF1D284B54378E10C95530151CD6FEC5B631B7E76EA1C1D2325B7641

**Comment by carlsbad-sunshine** [comment]
@catenocrypt If you can please reopen this PR, we'd really appreciate it. We sent the payment twice.
https://explorer.binance.org/tx/D96C12AB0E1D98DD62A39A6D5DEA76F92FA6068EADB5F9C964B19F62D01B44E9
https://explorer.binance.org/tx/723C220BEF1D284B54378E10C95530151CD6FEC5B631B7E76EA1C1D2325B7641

**Comment by catenocrypt** [comment]
Payment accepted manually.

**Pull request merged**
