### PR TITLE
Add GroveToken (BEP20)

### PR DESCRIPTION
**Pull request by Grovetoken**
Adding info for BEP20 token 'GroveToken'.

PR created by <a href="https://assets.trustwallet.com">TW Assets Management</a>

### CODE REVIEW

**Comment by Grovetoken** [comment]
can you let me know if or when it will be approved ?

**Comment by Cryptocool1** [comment]
As per our policy, brand new tokens are not included, there is a minimum requirement of 10,000 holder addresses and 15,000 transactions, in order to filter out scam tokens.
See the criteria at : https://developer.trustwallet.com/assets/requirements .

**Comment by Grovetoken** [comment]
Yes it also say "This requirement is subject for review based on the project" can you kindly review.
This token is ran by a registered Dubai LLC business.
Founders are fully doxxed with multi million dollar businesses to their name.
I was presenting in dubai expo can't be scan.

**Comment by Grovetoken** [comment]
Scam*

**Comment by Cryptocool1** [comment]
• What is the purpose of this token? How will it benefit Trust Wallet users?
 • How is the token being distributed? Are you conducting an airdrop?
 • Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?
 • Is the token listed on a centralized/decentralized exchange?
 • Is a Smart Contract audit completed? Where can we find this information?

**Comment by Grovetoken** [comment]
• What is the purpose of this token?  
we have many utilities Grove is unique as it combines virtual currency and real business concepts so adding to all our "crypto utilities" we are opening real-world business in Dubai.
 focused :
hydroponic farming 
solar farming 
water desalination 
recycling 
with our first farm being built next month.
so business will generate profit to pay the token back and that will bring more investors in from outside of the crypto world to crypto itself 
combining the best of both worlds
How will it benefit Trust Wallet users?
we aim to make crypto easy and an accessible, majority of our youtube videos are focused on using trust wallet and you can check that yourself on our youtube channel.
The recommendation from my 37 mods to investors is to use trust wallet as it's safe and secure.
• How is the token being distributed? Are you conducting an airdrop?
the presale was done and airdrop took place a few days ago 
• Did you sell the tokens at an Initial Coin Offering (ICO) or a token presale?
yes and that was all finalised as answered previously 
• Is the token listed on a centralized/decentralized exchange?
Grove is listed on bitmart and Indacoin "only 4 weeks old project"
• Is a Smart Contract audit completed? Where can we find this information?
yes audited link below. or check our website www.grovetoken.com
https://www.grovetoken.com/_files/ugd/8eae10_e171de58f8f6499eb39e0b19ef1c5522.pdf

please note we have 38000 transactions already in 4 weeks .
I really appreciate your time looking into this

**Comment by Cryptocool1** [comment]
We require smart contract audit completed by reputable security audit groups. (Certik, Techrate, Hacken, InterFi, Dessert Finance). 
Please come bak to us when all criteria are met. Make sure to mention this PR so the fee can be reused.

**Comment by Grovetoken** [comment]
https://www.grovetoken.com/_files/ugd/8eae10_db9b69bf264b4335bff0c109ea03c4e5.pdf
Audit as requested

**Comment by Grovetoken** [comment]
Hi 

Please find below audit as requested

https://www.grovetoken.com/_files/ugd/8eae10_db9b69bf264b4335bff0c109ea03c4e5.pdf

p

 

John G | Founder @ GroveToken & GroveBusiness

E:  ***@***.***> ***@***.***

Twitter:  <https://twitter.com/GroveToken> https://twitter.com/GroveToken

Facebook:  <https://www.facebook.com/GroveTokenOfficial> https://www.facebook.com/GroveTokenOfficial

Instagram:  <https://www.instagram.com/grovetoken/> https://www.instagram.com/grovetoken/

Telegram:  <https://t.me/Grovetoken> https://t.me/Grovetoken

Website:  <https://grovetoken.com/> https://GroveToken.com

**Pull request closed without merging**
