### PR TITLE
Add ZEFU Info (BEP-20)

### PR DESCRIPTION
**Pull request by n1ghtcoder**

### CODE REVIEW

**Comment by n1ghtcoder** [comment]
Hi guys!

Please check if the data provided is correct and merge it if everything is dandy.

Have a great day!

**Comment by Cryptocool1** [comment]
hello,
cannot find your contact on website.
please check

**Comment by n1ghtcoder** [comment]
You mean my Github?
It's not listed on https://zenfuse.io/about-us, does it needs to be there?

**Comment by Cryptocool1** [comment]
> Hi!
> 
> You mean my Github?
> It's not listed on https://zenfuse.io/about-us, does it needs to be there?

I mean smart contract.

**Comment by n1ghtcoder** [comment]
@Cryptocool1 our smart-contract is not listed on the website, we have a link leading to PancakeSwap in our header instead

https://exchange.pancakeswap.finance/#/swap?inputCurrency=0x23ec58e45ac5313bcb6681f4f7827b8a8453ac45

It contains our smart contract – **0x23ec58e45ac5313bcb6681f4f7827b8a8453ac45**

**Pull request merged**
