### PR TITLE
ERC20 token update

### PR DESCRIPTION
**Pull request by Teddybear12355**
Changed image size and changed json file

### CODE REVIEW

**Comment by Teddybear12355** [comment]
IS this ok?

**Comment by Cryptocool1** [comment]
Hello,
PR should include only 2 files, please correct

**Comment by Teddybear12355** [comment]
> Hello,
> PR should include only 2 files, please correct

What is PR? My Commit include 2 files json and logo?

**Comment by Teddybear12355** [comment]
Its Done. Merge Please :)

**Comment by Teddybear12355** [comment]
Can i change the logo? I mean update it?

**Pull request merged**
