### PR TITLE
Add PulseDogecoin (PLSD) (ERC20)

### PR DESCRIPTION
**Pull request by PulseDogecoin**
Adding info for ERC20 token 'PulseDogecoin (PLSD)'.

PR created by <a href="https://assets.trustwallet.com">TW Assets Management</a>

### CODE REVIEW

**Comment by cryptomanz** [comment]
• What is the purpose of this token? How will it benefit Trust Wallet users?
 • How is the token being distributed? Are you conducting an airdrop?
 • Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?
 • Is the token listed on a centralized/decentralized exchange?
 • Is a Smart Contract audit completed? Where can we find this information?

**Comment by PulseDogecoin** [comment]
• What is the purpose of this token? How will it benefit Trust Wallet users?
PulseDogecoin is a community meme coin. It's purpose is to be a friendly and familiar way for a general non-technical crowd to enter into the upcoming PulseChain (Ethereum system state fork) blockchain.

• How is the token being distributed? Are you conducting an airdrop?
The token is distributed using a fair distribution via a Merkle Tree Root. The majority of the tokens are distributed to the middle class of HEX token stakers. Each class of HEX staker is eligible to free claim PLSD based on their staking share size. Larger stakers are not rewarded unfairly, and smaller stakers are not punished. More information on the distribution can be seen [here](https://pulsedogecoin.com).

• Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?
No ICO or external funding was utilized for this project. All tokens were distributed freely, no purchase required. The token also had/have instant value and a large liquidity pool at launch.

• Is the token listed on a centralized/decentralized exchange?
PulseDogecoin (PLSD) is listed on Uniswap V3 in (2) AMA Liquidity Pools: USDC/PLSD & HEX/PLSD

• Is a Smart Contract audit completed? Where can we find this information?
A member of the community submitted the smart contract for an audit. The results of the audit can be seen in this post https://twitter.com/ROCKETFACTORY_/status/1519522748334501888

**Comment by cryptomanz** [comment]
Please , send  audit in PDF format.

**Comment by PulseDogecoin** [comment]
Ok. I messaged him to see if I can get a link for it.

**Comment by PulseDogecoin** [comment]
Here is a link to the document.

https://img1.wsimg.com/blobby/go/65de38bc-5845-4557-af8f-e14acf85fbfc/downloads/PulseDogecoin_SmartContractAudit.pdf?ver=1651801057031

**Comment by Cryptocool1** [comment]
we require audit from reputable companies. (Certik, Hacken, Dessert Finance, Techrate)

**Comment by PulseDogecoin** [comment]
> we require audit from reputable companies. (Certik, Hacken, Dessert Finance, Techrate)

Ok. I am getting an audit completed by Techrate. Should be completed in a few days.

**Comment by PulseDogecoin** [comment]
> > we require audit from reputable companies. (Certik, Hacken, Dessert Finance, Techrate)
> 
> Ok. I am getting an audit completed by Techrate. Should be completed in a few days.

Status update: Audit by Techrate is currently in progress. I will update when I have more information.

**Comment by PulseDogecoin** [comment]
> Please come back to us one all criteria are met. Make sure to mention this PR so the fee can be reused

I have the link to the audit. Should I open a new PR? https://github.com/TechRate/Smart-Contract-Audits/blob/main/May/PulseDogecoin.pdf

**Review by kophyo1234 — COMMENTED** [review]
Duplicate of #

**Pull request closed without merging**
