### PR TITLE
Add Dogs Of Elon (ERC20) - Previous paid PR #17925

### PR DESCRIPTION
**Pull request by dogsofelon**
Adding info for ERC20 token 'Dogs Of Elon'.

PR created by <a href="https://assets.trustwallet.com">TW Assets Management</a>

### CODE REVIEW

**Comment by dogsofelon** [comment]
The payment was made in the previous PR #17925

**Review by dogsofelon — COMMENTED** [review]
Payment was made in the previous paid PR #17925

**Comment by cryptomanz** [comment]
• What is the purpose of this token? How will it benefit Trust Wallet users?
 • How is the token being distributed? Are you conducting an airdrop?
 • Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?
 • Is the token listed on a centralized/decentralized exchange?
 • Is a Smart Contract audit completed? Where can we find this information?

**Comment by dogsofelon** [comment]
> 

• What is the purpose of this token? How will it benefit Trust Wallet users?
  Dogs of Elon is a NFT collection of 10000 NFT's inspired by meme coin community which is listed on opensea. This token is a DeFi token companion to the NFT collection. The token will have utility tied to a play to earn game that uses the NFT's in game. Trust Wallet users can use the token/NFT they are holding and use it in game to play and earn DOE tokens. 
  
• How is the token being distributed? Are you conducting an airdrop?
   Tokens can be purchased from dex like Uniswap or CEX's where doe token is listed.
   
• Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?
   The token was sold in a presale 
   
• Is the token listed on a centralized/decentralized exchange?
  Yes. Following are the DEX/CEX DOE is listed
   Uniswap
   Sushiswap
   Gate.io
   Hotbit
   BKEX
   ZTB
   Decoin
   Poloniex
   LBank
   MEXC
   
• Is a Smart Contract audit completed? Where can we find this information?
  Yes. The smart contract is audited by Certix. You can find the audit report on this link
  https://www.certik.com/projects/dogs-of-elon

**Comment by dogsofelon** [comment]
> • What is the purpose of this token? How will it benefit Trust Wallet users? • How is the token being distributed? Are you conducting an airdrop? • Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale? • Is the token listed on a centralized/decentralized exchange? • Is a Smart Contract audit completed? Where can we find this information?

Information provided in the comment above.

**Comment by dogsofelon** [comment]
Request to please update the logo.

**Pull request merged**
