### PR TITLE
Add BABYSPACEFLOKI (BEP20)

### PR DESCRIPTION
**Pull request by chefcardano**
Adding info for BEP20 token 'BABYSPACEFLOKI'.

PR created by <a href="https://assets.trustwallet.com">TW Assets Management</a>

### CODE REVIEW

**Comment by Cryptocool1** [comment]
hello,
• What is the purpose of this token? How will it benefit Trust Wallet users?
 • How is the token being distributed? Are you conducting an airdrop?
 • Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?
 • Is the token listed on a centralized/decentralized exchange?
 • Is a Smart Contract audit completed? Where can we find this information?

**Comment by chefcardano** [comment]
> hello, • What is the purpose of this token? How will it benefit Trust Wallet users? • How is the token being distributed? Are you conducting an airdrop? • Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale? • Is the token listed on a centralized/decentralized exchange? • Is a Smart Contract audit completed? Where can we find this information?

Hello, our responses are as below:

**Comment by chefcardano** [comment]
Hello, our responses are as below:

• What is the purpose of this token? How will it benefit Trust Wallet users?
BSF is the governance token for Baby Space Floki. BSF holders can make proposals on marketing and the direction of the project. Holders can also vote on proposals via the Baby Space Floki DAO, and decide how best to spend community and marketing funds.

• How is the token being distributed? Are you conducting an airdrop?
Fair launch (token was relaunched with original contract holders equal tokens in July) still would call this a fair launch. 

• Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?
No.

• Is the token listed on a centralized/decentralized exchange?
It's listed on pnacakeswap decentralized exchange: https://pancakeswap.finance/swap?outputCurrency=0x689437c050678935db89381fe0b8f6ed4a3eec66

• Is a Smart Contract audit completed? Where can we find this information?
Yes audited: https://www.dropbox.com/s/13cag7zoot4ssfx/BabySpaceFlokiV2%20AUDIT.pdf?dl=0

**Comment by cryptomanz** [comment]
Hello,
Please follow the rules for adding tokens, your logo should be a full screen 256x256.
Exemple:
https://community.trustwallet.com/t/how-to-submit-a-token-logo/3863

**Comment by chefcardano** [comment]
> Hello, Please follow the rules for adding tokens, your logo should be a full screen 256x256. Exemple: https://community.trustwallet.com/t/how-to-submit-a-token-logo/3863

Hello again, looks like the resolution changed while compressing the image, should we close this request and make a new one or is editing possible? Kr.

**Comment by chefcardano** [comment]
BSF Logo

**Pull request merged**
