### PR TITLE
Add GMT

### PR DESCRIPTION
**Pull request by aurumminer**

### CODE REVIEW

**Comment by Iamdeadlyz** [comment]
As per our policy, brand new tokens are not included. There is a minimum requirement of 500 holder addresses and 1000 transactions in order to filter out scam tokens. See the criteria at (mentioned in the first message by the bot): https://community.trustwallet.com/t/how-to-submit-a-token-logo/3863#how-to-get-approved

This token has below-limit usage yet. This pull request will be but on hold. Please come back to us when all criteria are met.
https://etherscan.io/token/0xF5f8472045c9177B545Ea05fdA73848291a3f8B8

**Comment by aurumminer** [comment]
ok for feedback will come back very soon.

**Comment by aurumminer** [comment]
> As per our policy, brand new tokens are not included. There is a minimum requirement of 500 holder addresses and 1000 transactions in order to filter out scam tokens. See the criteria at (mentioned in the first message by the bot): https://community.trustwallet.com/t/how-to-submit-a-token-logo/3863#how-to-get-approved
> 
> This token has below-limit usage yet. This pull request will be but on hold. Please come back to us when all criteria are met.
> https://etherscan.io/token/0xF5f8472045c9177B545Ea05fdA73848291a3f8B8

I think this not work out for rapid growing project. Please update this now. Its snapshot page also up: https://snapshot.page/#/gmt
Now look at tx: https://etherscan.io/token/0xf5f8472045c9177b545ea05fda73848291a3f8b8
Tx cross over 1200, holders over 120. Trading volume over 130k USD.

**Comment by aurumminer** [comment]
> This issue has been automatically marked as stale because it has not had recent activity. It will be closed if no further activity occurs. Thank you for your contributions.

Why this stale? Check well and commit.

**Comment by catenocrypt** [comment]
Stale bot is an automated bot that closes PRs/issues after a certain number of days without inactivity.
But don't worry, the PR can be repopened any time when it's ready for merging.
Will be merge when min. number of 500 holders is achieved; currently at 265.

**Comment by aurumminer** [comment]
> As per our policy, brand new tokens are not included. There is a minimum requirement of 500 holder addresses and 1000 transactions in order to filter out scam tokens. See the criteria at (mentioned in the first message by the bot): https://community.trustwallet.com/t/how-to-submit-a-token-logo/3863#how-to-get-approved
> 
> This token has below-limit usage yet. This pull request will be but on hold. Please come back to us when all criteria are met.
> https://etherscan.io/token/0xF5f8472045c9177B545Ea05fdA73848291a3f8B8

Why this on-hold still now???
Can you explain me. It has over 3000 Tx more than 200 over holder. But why still on-hold.

**Comment by aurumminer** [comment]
> Stale bot is an automated bot that closes PRs/issues after a certain number of days without inactivity.
> But don't worry, the PR can be repopened any time when it's ready for merging.
> Will be merge when min. number of 500 holders is achieved; currently at 265.

Why is numbers so important????
Did I list before below that numbers?

**Comment by aurumminer** [comment]
Or should I make this to 600?

**Comment by catenocrypt** [comment]
We had to draw a limit somewhere, to limit frequent dubious project.

**Comment by bitbd83** [comment]
> We had to draw a limit somewhere, to limit frequent dubious project.

If you does not know properly the it should seems "dubious". But I have seen 100's of "KILLING MACHINES" are got rewarded. I don't this is there a problem if any registered entity doing couple of experiments with their own money.

**Pull request closed without merging**
