### PR TITLE
Add BW logo and info

### PR DESCRIPTION
**Pull request by tanony799**
Add BW logo and info

### CODE REVIEW

**Comment by cryptomanz1** [comment]
• What is the purpose of this token? How will it benefit Trust Wallet users?
 • How is the token being distributed? Are you conducting an airdrop?
 • Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?
 • Is the token listed on a centralized/decentralized exchange?
 • Is a Smart Contract audit completed? Where can we find this information?

**Comment by tanony799** [comment]
> 
• What is the purpose of this token? How will it benefit Trust Wallet users? 
The purpose of the Blockwise token ($BW) is to bring value to the community and introduce cutting-edge blockchain technologies such as ChatAI and image generation. For Trust Wallet users, the benefit is to attract more people to use Trust Wallet, helping them access our comprehensive DeFi ecosystem, which includes faster transactions and lower fees, along with profit opportunities through staking and yield aggregation.

• How is the token being distributed? Are you conducting an airdrop? 
The $BW token is distributed through airdrops and a Presale ICO. We are currently conducting a $5M airdrop, providing the community with an easy and fair opportunity to own BW tokens.

• Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale? 
We have organized a Presale ICO to sell $BW tokens in advance, allowing users to acquire tokens early and participate in the Blockwise ecosystem.

• Is the token listed on a centralized/decentralized exchange? 
The $BW token is listed on reputable decentralized exchanges (DEX) such as Pancakeswap and Dexscreener. You can find and trade the token on these platforms to take advantage of the benefits Blockwise offers.

• Is a Smart Contract audit completed? Where can we find this information?
The smart contract audit for Blockwise has been completed. Detailed information about the smart contract and related documents can be found on all crypto information channels. We ensure transparency and safety for users when using Blockwise products.

**Comment by Cryptocool1** [comment]
Please share your smart contract audit here

**Comment by tanony799** [comment]
> Please share your smart contract audit here

We sincerely apologize, we had a mistake, our smart contract has not been audited yet

**Comment by Cryptocool1** [comment]
We require smart contract audit from reputable companies.
Feel free to open new pull request once you meet those requirements.
make sure to mention this PR, so that we can see that fee has been paid already here.

**Pull request closed without merging**
