### PR TITLE
KimJongMoon Token submission

### PR DESCRIPTION
**Pull request by cruiz85**
KimJongMoon token submission
$KIMJ
https://kimjongmoon.net
TG: https://t.me/KimJongMoonCoin
Twitter: https://twitter.com/KimJongmooncoin

Number of Holders: 12K
Number of transactions: 50K

### CODE REVIEW

**Comment by Cryptocool1** [comment]
Hello, 
Your id should be 0x737f0E47c4d4167a3eEcde5FA87306b6eEe3140e

**Comment by cruiz85** [comment]
The id in the json file is like that - I was actually going to change it to be in checksum too as in the folder

**Comment by cruiz85** [comment]
2 BNB Payment has been done with memo: 7443

Regards

**Comment by cruiz85** [comment]
One thing - Im sure that I created the fork for BEP-20 but I can see on the PR that everything points to Etherscan instead os BSCscan

**Comment by cruiz85** [comment]
The automatic merge-bot says:  Token type OK (ERC20);  the token is a BEP-20

**Comment by catenocrypt** [comment]
Correction needed:  Change the explorer field to
`https://bscscan.com/token/0x737f0E47c4d4167a3eEcde5FA87306b6eEe3140e`
from
`https://www.bscscan.com/address/0x737f0E47c4d4167a3eEcde5FA87306b6eEe3140e`

**Pull request merged**
