### PR TITLE
Add HAMTARO (BEP2)

### PR DESCRIPTION
**Pull request by HamtaroBSC**
Adding info for BEP2 token 'HAMTARO'.

PR created by <a href="https://assets.trustwallet.com">TW Assets Management</a>

### CODE REVIEW

**Comment by HamtaroBSC** [comment]
Already payed in this pr
Add Logo for Hamtaro #8192

**Comment by HamtaroBSC** [comment]
Already payed PR Add Logo for Hamtaro #8192

Il giorno lun 17 mag 2021 alle ore 08:46 merge-fee-bot[bot] <
***@***.***> ha scritto:

**Comment by Cryptocool1** [comment]
8219 duplicate

**Comment by HamtaroBSC** [comment]
Thanks, I have paid and used your app for send the last PR.
Please now add the logo to trust wallet.

Il giorno lun 17 mag 2021 alle ore 10:34 CryptoA ***@***.***>
ha scritto:

**Pull request closed without merging**
