### PR TITLE
Add Amazy Token (BEP20)

### PR DESCRIPTION
**Pull request by plagi**
Adding info for BEP20 token 'Amazy Token'.

PR created by <a href="https://assets.trustwallet.com">TW Assets Management</a>

### CODE REVIEW

**Comment by cryptomanz1** [comment]
As per our policy, brand new tokens are not included, there is a minimum requirement of 10,000 holder addresses and 15,000 transactions, in order to filter out scam tokens.
See the criteria at : https://developer.trustwallet.com/assets/requirements .

**Comment by Cryptocool1** [comment]
Feel free to open new PR once the requirements are met.

**Comment by plagi** [comment]
image
It is still 2663 holders, while there is already 46000 transactions...

**Comment by plagi** [comment]
Can you please reconsider adding the token?

**Pull request closed without merging**
