### PR TITLE
Add HAI and KITE (Let's Get HAI Protocol)

### PR DESCRIPTION
**Pull request by piesrtasty**
Add HAI and KITE tokens from Let's Get HAI protocol.

https://www.letsgethai.com

### CODE REVIEW

**Comment by piesrtasty** [comment]
To the reviewer:

Not sure why it's throwing the following validation error below, as I updated the CG url in a recent commit.

invalid value 'https://www.coingecko.com/en/coins/let-s-get-hai' for coingecko link url, allowed only with prefix: https://coingecko.com/

**Comment by Cryptocool1** [comment]
As per our policy, there is a minimum requirement of 10,000 holder addresses and 15,000 transactions, in order to filter out scam tokens.
See the criteria at : https://developer.trustwallet.com/listing-new-assets/requirements .

**Comment by Cryptocool1** [comment]
Feel free to come back to us once all criteria are met. Make sure to mention this PR so the fee can be reused.

**Comment by piesrtasty** [comment]
@Cryptocool1 I understand the requirements but there are plenty of projects that have < 10K holder addresses that are on this repo. One example is Reflexer - FLX (which we are a fork of and members of the DAO). 

I believe there is ample evidence to show that Let's Get HAI is a real project and not a spam token.

https://www.letsgethai.com

**Pull request closed without merging**
