### PR TITLE
Update with validator Gridtek.com

### PR DESCRIPTION
**Pull request by gridtek**

### CODE REVIEW

**Comment by Cryptocool1** [comment]
Submission looks good, awaiting for fee payment

**Comment by gridtek** [comment]
If I need to update the logo, is there another charge? If so, I’ll have to wait for my new logo. It’s almost done. Philip Bagalanon, CEOPlease excuse errors. This message was sent from my iPhone.On Mar 17, 2023, at 7:41 PM, merge-fee-bot[bot] ***@***.***> wrote:﻿
@gridtek, kind reminder:  please pay fee:  500 TWT  with the memo 24338  to the address bnb158fgd782we4tz9vwwcj9pmmxvxhl6z46lfm7c8.
Alternatively, 5 BNB is also accepted (same memo & address).
QR code: Trust | other wallet
See the Pull Request Fee FAQ.

**Comment by Cryptocool1** [comment]
The fee is 500 TWT or 5 BNB

**Comment by gridtek** [comment]
Thank you. Please, give me time to finalize the logo. Then, I’ll process the payment. Philip Bagalanon, CEOPlease excuse errors. This message was sent from my iPhone.On Mar 17, 2023, at 10:58 PM, CryptoA ***@***.***> wrote:﻿
The fee is 500 TWT or 5 BNB

**Pull request closed without merging**
