### PR TITLE
Add Muu Inu (BEP20)

### PR DESCRIPTION
**Pull request by muuinu**
Adding info for BEP20 token 'Muu Inu'.

PR created by <a href="https://assets.trustwallet.com">TW Assets Management</a>

### CODE REVIEW

**Comment by Cryptocool1** [comment]
• What is the purpose of this token? How will it benefit Trust Wallet users?
 • How is the token being distributed? Are you conducting an airdrop?
 • Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?
 • Is the token listed on a centralized/decentralized exchange?
 • Is a Smart Contract audit completed? Where can we find this information?

**Comment by muuinu** [comment]
Hi @Cryptocool1,

Muu Inu token will be used for staking and our NFT p2e game.
97% of all tokens were added to PancakeSwap liquidity and 3% reserved for the team.
We sold at ICO
You can find Muu Inu on Dex: PancakeSwap / CEX: BitMart, Lbank, Azbit, Finexbox
Our audit: https://github.com/freshcoins/Smart-Contract-Audits/blob/main/MuuInu_0xEA5E9F39F4B4Bc2684e49A0E43127F7f6F6be3b8.pdf

Best Regards

**Comment by muuinu** [comment]
@Cryptocool1 

Any updates on this? Is there anything else required from us?

**Comment by Cryptocool1** [comment]
Hello, your logo should be 256/256 full size. Please change

**Comment by muuinu** [comment]
Hey, I uploaded 256x256 one. The app said 500x500 was ok for some reason when I added the original one.

**Pull request merged**
