### PR TITLE
Add dfx logov3

### PR DESCRIPTION
**Pull request by chanharryhk**

### CODE REVIEW

**Comment by catenocrypt** [comment]
As per our policy, brand new tokens are not included, there is a minimum requirement of 2500 holder addresses and 5000 transactions, in order to filter out scam tokens.
See the criteria at (mentioned in the first message by the bot): https://community.trustwallet.com/t/how-to-submit-a-token-logo/3863).
This token has low usage yet (20 holders). Closing PR for now. Please come back to us when all criteria are met.  Multi-chain and staking tokens may get special treatment, let us know if this is the case. 

https://etherscan.io/token/0x888888435FDe8e7d4c54cAb67f206e4199454c60

**Comment by chanharryhk** [comment]
@catenocrypt What does "staking token" entail? Do you mind elaborating please? :)

**Comment by catenocrypt** [comment]
A defi staking token typically is not held by users in their wallet, but it is staked into a smart contract.  So even if 1000 users own it, but have it staked, the explorer only will see 1 holder address.

**Comment by catenocrypt** [comment]
No action for almost 2 months, closing.

**Pull request closed without merging**
