### PR TITLE
ADD GAMEX LOGO

### PR DESCRIPTION
**Pull request by tedsamaha**

### CODE REVIEW

**Comment by Cryptocool1** [comment]
hello,
• What is the purpose of this token? How will it benefit Trust Wallet users?
 • How is the token being distributed? Are you conducting an airdrop?
 • Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?
 • Is the token listed on a centralized/decentralized exchange?
 • Is a Smart Contract audit completed? Where can we find this information?

**Comment by tedsamaha** [comment]
Hello, Here's all the information you requested:


### What is the purpose of this token ?

GameX is a community project founded by gamers around the world aiming to improve the gaming industry. GameX’s mission is to provide gaming related products of high quality and become one of the most important gaming stores in the world  , where players can get their gaming gear ,  favorite games by a push of button .  In addition to this GAMEX token work on developing a gaming academy where everyone have the chance to get the exposure in the esports world   By building  the first GAMEX team across many esports games 
GAMEX tournament in esports gaming  did launched based on many problems in the esports  world (unprotected rights of esports participants ,refusal of intermediaries in the payment of winnings, withdrawal of funds earned in-game and Donations chargebacks) 
The concept behind GAMEX tournament is players can participate in many esports tournaments and get rewarded by GAMEX.
Launching GAMEX Studio was a key role to merge the cryptocurrency and gaming world by implementing in games NFT  , developing several games based on the community idea play an important role in GAMEX policy ,listening to players is what make a good project sustainable 
Because NFT and art are a good combination.
GAMEX art is a place where  art lovers can dive into abstract and creative collection of unique masterpieces designed by the most brilliant talented artists around the world.

### How will it benefit Trust Wallet users ?

-Play to earn pay GMX earn BNB
-Passive income staking 
-Developing retro game market place NFT in-game
-Selling NFT on AIRNFT
-Devs doxxed on website 
-GameX swap being developed and soon will be launched 
-GameX have a team of esports competing in CSGO and PUBG

### Did you sold the tokens at Inicial Coin Offering (ICO) or a token presale? 

No it was a fair launch

### Is the token listed on a centralized/decentralized exchange ? 

-pancake Swap
-BankCex exchange 
-Swft Blockchain 
-Dextrade Exchange
-XT exchange (in the upcoming week)

### Is the smart contract audit completed ? 

GameX is audited by Solidity Finance 

https://solidity.finance/audits/GAMEX/


### Where can we find this information?

The audit and all the information of the token are on our website 

www.game-x.co

**Comment by Cryptocool1** [comment]
According to our documentation token image needs to be full screen,  https://community.trustwallet.com/t/how-to-submit-a-token-logo-using-assets-app/82957.

**Comment by tedsamaha** [comment]
> According to our documentation token image needs to be full screen,  https://community.trustwallet.com/t/how-to-submit-a-token-logo-using-assets-app/82957.

Hi, I just checked the information you sent me. The logo size is 256x256 like requested.
Can you please explain what do you mean by full-screen?

**Comment by Cryptocool1** [comment]
> > According to our documentation token image needs to be full screen,  https://community.trustwallet.com/t/how-to-submit-a-token-logo-using-assets-app/82957.
> 
> Hi, I just checked the information you sent me. The logo size is 256x256 like requested.
> Can you please explain what do you mean by full-screen?

there should be no space in the sides

**Comment by Cryptocool1** [comment]
logo
please see the example of the correct full screen logo

**Comment by tedsamaha** [comment]
Hi, Thank you for your response!
Here's the logo fullscreen.
logo 256

**Comment by Cryptocool1** [comment]
changed

**Pull request merged**
