### PR TITLE
Add Bogecoin (BEP20)

### PR DESCRIPTION
**Pull request by zerosdontcount**
Adding info for BEP20 token 'Bogecoin'.

PR created by <a href="https://assets.trustwallet.com">TW Assets Management</a>

### CODE REVIEW

**Comment by Cryptocool1** [comment]
PR should include only 2 files:
-blockchains/smartchain/assets/0x248C45AF3b2f73Bc40FA159f2a90ce9caD7A77BA/info.json
-blockchains/smartchain/assets/0x248C45AF3b2f73Bc40FA159f2a90ce9caD7A77BA/logo.png

**Comment by zerosdontcount** [comment]
Hi, can you help me understand if there anything else I need to do. I'm not clear by looking at this. Thank you.

**Comment by zerosdontcount** [comment]
> PR should include only 2 files:
> -blockchains/smartchain/assets/0x248C45AF3b2f73Bc40FA159f2a90ce9caD7A77BA/info.json
> -blockchains/smartchain/assets/0x248C45AF3b2f73Bc40FA159f2a90ce9caD7A77BA/logo.png

Is this a note for me or internally with TW?

**Review by smehrjerdian — COMMENTED** [review]
I think from what I can tell you have dupes in your PR its showing 4 files instead of 2. It looks like you still have the old files when you had the characters in contract address lowercase

**Comment by zerosdontcount** [comment]
This is now updated

**Pull request merged**
