### PR TITLE
Add ZOMBIE SKRAT (BEP20)

### PR DESCRIPTION
**Pull request by inmefinance**
Adding info for BEP20 token 'ZOMBIE SKRAT'.

PR created by <a href="https://assets.trustwallet.com">TW Assets Management</a>

### CODE REVIEW

**Comment by inmefinance** [comment]
can explain what the error to can fix it ?

**Review by Fuad369 — COMMENTED** [review]
انا اوافق

**Comment by inmefinance** [comment]
What I must comment?

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by inmefinance** [comment]
Can I see the info before comment I am agree ?

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by inmefinance** [comment]
Please answer me

**Comment by Fuad369** [comment]
انا اوافق

**Comment by Fuad369** [comment]
انا اوافق

**Comment by Fuad369** [comment]
انا اوافق

في الثلاثاء، ١١ أكتوبر، ٢٠٢٢ ٣:٢٥ ص inmefinance ***@***.***>
كتب:

**Comment by inmefinance** [comment]
hello please give me feedback what next i must do ?

**Comment by inmefinance** [comment]
There some missing or what I didn’t understand it

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by Cryptocool1** [comment]
Hello, how did you get 10k holders in 10 days?

**Comment by inmefinance** [comment]
We are meme token and we listed on cg cmc and many many promotion and we did 7x since we start

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by Cryptocool1** [comment]
> We are meme token and we listed on cg cmc and many many promotion and we did 7x since we start Get Outlook for iOS<https://aka.ms/o0ukef>
> […](#)

How did you get them? Are you conducting any airdrops?

**Comment by inmefinance** [comment]
We are ok Telegram global around 9k and telegram  china group around 4k to 5k and twitter around 9k also

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by Cryptocool1** [comment]
> We are ok Telegram global around 9k and telegram china group around 4k to 5k and twitter around 9k also Get Outlook for iOS<https://aka.ms/o0ukef>
> […](#)

• What is the purpose of this token? How will it benefit Trust Wallet users?
 • How is the token being distributed? Are you conducting an airdrop?
 • Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?
 • Is the token listed on a centralized/decentralized exchange?
 • Is a Smart Contract audit completed? Where can we find this information?

**Comment by inmefinance** [comment]
• What is the purpose of this token? How will it benefit Trust Wallet users? Maybe we have Pratner ship we can run stake or some token from pool and make airdrop for trust wallet users
• How is the token being distributed? Are you conducting an airdrop? It’s sold ok presale and liquidity added to pancakeswap and locked on pinksale
• Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale? Yea we did on pinksale
• Is the token listed on a centralized/decentralized exchange? Yes almost decentralized popular one pancakeswap
• Is a Smart Contract audit completed? Where can we find this information? Yea it’s audit and complete  and you can check link below
https://irp.cdn-website.com/1b45ecb9/files/uploaded/ZombieSKRAT_AuditReport_InterFi.pdf

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by Cryptocool1** [comment]
Are you conducting an airdrop?

**Comment by inmefinance** [comment]
Yes snapshot taking and distribution as as 5 phase 20% from token airdrop for them

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by inmefinance** [comment]
Hello I didn’t here from you ?

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by inmefinance** [comment]
Any update ?

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by Cryptocool1** [comment]
Hello, we will set you on hold and see how holders will come. ( because you get all of your holders in 1 week)
You can see in our requirements documentation that we are not accept new and airdropped tokens.

**Comment by Cryptocool1** [comment]
We will set your token on hold for couple of days to make sure. Thank you

**Comment by inmefinance** [comment]
Hope hear from soon

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by inmefinance** [comment]
Sorry I miss written
It’s 20 % will distrub every month as 20%
Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by inmefinance** [comment]
Okay no problem thank you

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by inmefinance** [comment]
we was 10119 yesterday now  Holders:
11,113 addresses

**Comment by inmefinance** [comment]
We are now more than 11k last 24 hour we got around more than 900 holders

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by inmefinance** [comment]
any feedback ?

**Comment by inmefinance** [comment]
any feedback sir ?

**Comment by inmefinance** [comment]
hello sir can we got feedback ?

**Review by Hadijafari1 — COMMENTED** [review]
Ok

**Comment by Hadijafari1** [comment]
Ok

**Review by Hadijafari1 — COMMENTED** [review]
Ok

**Comment by Hadijafari1** [comment]
Ok

**Comment by Cryptocool1** [comment]
hello, as we said before, your token is on hold.

**Comment by inmefinance** [comment]
Yea couple  of days and it’s was 3 days ago

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by inmefinance** [comment]
hello great team any news ?

**Comment by Fuad369** [comment]
انا موافق

في الجمعة، ١٤ أكتوبر، ٢٠٢٢ ١٢:٠٥ ص Hadijafari1 ***@***.***>
كتب:

**Comment by inmefinance** [comment]
any news ?

**Comment by Cryptocool1** [comment]
hello, I don't see activity, you got 10k holders in 1 week previously.  
For now you still have only 10k holders

**Comment by inmefinance** [comment]
People not trust us because we promise and not delivery and start sell look at our chart 😢

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by inmefinance** [comment]
Holders:

10,971 addresses

 around 11k after more than 500 investor left us

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by Git-Dev-admin-010** [comment]
> Adding info for BEP20 token 'ZOMBIE SKRAT'.
> 
> PR created by [TW Assets Management](https://assets.trustwallet.com)

Denied this repo or address does not belong to u @dependabot

**Comment by Fuad369** [comment]
انا موافق ok

في الإثنين، ٢٤ أكتوبر، ٢٠٢٢ ٩:٥٧ م CryptoA ***@***.***> كتب:

**Pull request merged**
