### PR TITLE
Add RAMP (BEP20)

### PR DESCRIPTION
**Pull request by RAMPDEFITEAM**
Adding info for BEP20 token 'RAMP'.

PR created by <a href="https://assets.trustwallet.com">TW Assets Management</a>

### CODE REVIEW

**Comment by Cryptocool1** [comment]
• What is the purpose of this token? How will it benefit Trust Wallet users?
 • How is the token being distributed? Are you conducting an airdrop?
 • Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?
 • Is the token listed on a centralized/decentralized exchange?
 • Is a Smart Contract audit completed? Where can we find this information?

**Comment by Cryptocool1** [comment]
Please create new PR when all criteria are met. Make sure to mention this PR, so the fee can be reused.

**Comment by RAMPDEFITEAM** [comment]
Hi,

Not sure what the issue is and what criteria you're mentioning? The PR
merge has already been completed.

For your reference

• What is the purpose of this token? How will it benefit Trust Wallet
users? Please read here:
https://docs.rampdefi.com/rampdefi/ramp-token-utility-design
• How is the token being distributed? Are you conducting an airdrop? Private
and public sale completed since last year and trading on
Binance/Uniswap/Pancakeswap
• Did you sold the tokens at an Initial Coin Offering (ICO) or a token
presale? A private and public sale was completed
• Is the token listed on a centralized/decentralized exchange?  Private and
public sale completed since last year and trading on
Binance/Uniswap/Pancakeswap
• Is a Smart Contract audit completed? Where can we find this information?
https://github.com/RAMP-DEFI/RAMP_SECURITY_AUDITS

Thanks,
RAMP Team

**Comment by RAMPDEFITEAM** [comment]
Hi Crypto A,

Following up on this.

Have replied your queries previously, not sure what the issue is.

Thanks,
RAMP Team

**Pull request closed without merging**
