### PR TITLE
Add Doraemoon token ($DORA) logo and info

### PR DESCRIPTION
**Pull request by doraemoondev**
We add Doraemoon token ($DORA) to Trust Wallet
Contract: https://www.bscscan.com/token/0xadaf3be815cd4345229324e02e839de85ce95dc2
Audited by Solid Group: https://solidgroup-68170.medium.com/13b15f74cb57
More information: https://doraemoon.io

### CODE REVIEW

**Comment by yasir017470** [comment]
Approve Dora token in trustwallet

**Comment by Eribowo232** [comment]
> We add Doraemoon token ($DORA) to Trust Wallet
> Contract: https://www.bscscan.com/token/0xadaf3be815cd4345229324e02e839de85ce95dc2
> Audited by Solid Group: https://solidgroup-68170.medium.com/13b15f74cb57
> More information: https://doraemoon.io

Nice Projects

**Comment by gibran03** [comment]
Please send to my address
0x17157546C877F69e803f72621D3E1ab3958D65D3

**Comment by zannoekhamari** [comment]
Lets go, i receive give away... Waiting for airdrop

**Comment by Pain2691** [comment]
Wow This is it!!Dora to the Moon

**Comment by Eribowo232** [comment]
> **PR Summary**
> Files in PR: 2
> Token in PR: BEP20 0xAdaf3be815Cd4345229324E02e839dE85cE95DC2
> Symbol: **DORA** decimals: 18
> Links: [Logo](https://raw.githubusercontent.com/doraemoondefi/assets/master/blockchains/smartchain/assets/0xAdaf3be815Cd4345229324E02e839dE85cE95DC2/logo.png) [Info](https://raw.githubusercontent.com/doraemoondefi/assets/master/blockchains/smartchain/assets/0xAdaf3be815Cd4345229324E02e839dE85cE95DC2/info.json) [Website](https://doraemoon.io) [Explorer](https://bscscan.com/token/0xAdaf3be815Cd4345229324E02e839dE85cE95DC2) (check OK 🙂)
> 
>

**Comment by Eribowo232** [comment]
Nice

**Comment by teguhsuardi** [comment]
0x2e0D4adb0d2ABB9ACDC9cfC438E3167402C80089

dont received it

**Comment by kingdragz** [comment]
Wow that is amazing

**Comment by Sanjeevk1010** [comment]
0x02ff5065692783374947393723dba9599e59f591

**Pull request merged**
