### PR TITLE
Adding TW logo and Info

### PR DESCRIPTION
**Pull request by PizzaNFTdev**
Replacing SafePizza token with an upgraded version of the former contract. PizzaNFT should now replace SafePizza token.

### CODE REVIEW

**Comment by SafePizzaCoin** [comment]
Is there any way to remove  0x72Eb1aFddB5652e0f5c7B9A6cc1C3241348b16c6 from TW, and replace it with 0xb07905396A419B121213efe1d17cfD0ff20aE597. We should be grandfathered in, when we originally created this fork the circ limit was 2500. We had to update our smart contract.

**Comment by SafePizzaCoin** [comment]
When we originally submitted to get listed on TW the holders requirement was 2500, can we been grandfathered in. 

**low token circulation: number of holders is 2195, below limit of 25000**

**Comment by SafePizzaCoin** [comment]
Is there anything else that we are missing?

**Comment by SafePizzaCoin** [comment]
This asset which is a blocker should be removed -> blockchains/smartchain/assets/0x72Eb1aFddB5652e0f5c7B9A6cc1C3241348b16c6/info.json. I can resolve the conflicts if it's not removed. @catenocrypt @zachzwei @Cryptocool1 @cryptomanz

**Comment by Cryptocool1** [comment]
0x72Eb1aFddB5652e0f5c7B9A6cc1C3241348b16c6
is this contract abandoned?

**Comment by SafePizzaCoin** [comment]
> 

Yes, it's no longer valid.

**Comment by Cryptocool1** [comment]
Can you send the official announcement?

**Comment by SafePizzaCoin** [comment]
https://twitter.com/PizzaNFT2E/status/1465643876237127681?s=20

**Comment by SafePizzaCoin** [comment]
> 

Did you require any more information?

**Comment by SafePizzaCoin** [comment]
When can our holders began to see the new logo? @Cryptocool1 Sorry, I forgot to @ you.

**Comment by cryptomanz** [comment]
Please create new PR, with new contract and i will put status abandoned in your old contract. Make sure to mention this PR, so that we can see that fee has been paid already here.

**Pull request closed without merging**
