### PR TITLE
bficoin We are adding bfic coin logo

### PR DESCRIPTION
**Pull request by bficoin**

### CODE REVIEW

**Review by bficoin — COMMENTED** [review]
please check ,
file available

**Comment by Cryptocool1** [comment]
Correction needed:

Description field is too long, please compact it (803 chars, max is 500)

**Comment by bficoin** [comment]
> Correction needed:
> 
> Description field is too long, please compact it (803 chars, max is 500)

Hello Mam,
Please check my request 
PR Summary
Files in PR: 2
Token in PR: BEP20 0xF0a0913BA2b173c1fbCa1c1b2FCFC0E3678f66a9
Symbol: Bfic decimals: 8
Links: Logo Info Website Explorer (check OK)

**Comment by Cryptocool1** [comment]
Can you please capitalize all letters in your symbol?

**Comment by Cryptocool1** [comment]
> > Can you please capitalize all letters in your symbol?
> 
> Bfic = BFIC

You need to change it

**Comment by bficoin** [comment]
> Submission looks good. awaiting fee payment.

I have paid

**Comment by Cryptocool1** [comment]
#7459 PAID

**Comment by bficoin** [comment]
thanx you mam

**Comment by bficoin** [comment]
we are facing an issue, i.e the rate of the BFIC coin is not showing in the updated trust wallet application, Even if will talk about the previous version rate was fixed and showing 24$ as it must show the current rate. Kindly look into the matter and guide us the required steps to update.

**Pull request merged**
