### PR TITLE
Add Celestial (BEP20)

### PR DESCRIPTION
**Pull request by Celestialgamefi**
Adding info for BEP20 token 'Celestial'.
https://github.com/trustwallet/assets/pull/15175
https://explorer.binance.org/address/bnb15pwnpvcaxcy8pj3u28kjtzrcnajfmh756k07ls
https://bscscan.com/token/0x4f34292f109870d5fdda602bc7e3ae56d520d6e1

PR created by <a href="https://assets.trustwallet.com">TW Assets Management</a>

### CODE REVIEW

**Comment by Celestialgamefi** [comment]
https://github.com/trustwallet/assets/pull/15175
image

**Comment by cryptomanz** [comment]
• What is the purpose of this token? How will it benefit Trust Wallet users?
 • How is the token being distributed? Are you conducting an airdrop?
 • Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?
 • Is the token listed on a centralized/decentralized exchange?
 • Is a Smart Contract audit completed? Where can we find this information?

**Comment by Celestialgamefi** [comment]
https://coinmarketcap.com/currencies/celestial/
https://www.coingecko.com/en/coins/celestial
https://www.mytokencap.com/currency/celt/821805353
https://www.feixiaohao.co/currencies/celestial/

**Comment by Celestialgamefi** [comment]
• What is the purpose of this token? How will it benefit Trust Wallet users? 
 
1.      Celt is our main token. All consumption in the game is Celt. In the trading market, 5% of Celt will be drawn as a handling fee and burned. Crystal is our sub token. Its existence is to maintain the stability of CELT, and its distribution to users as a profit method in the game
2.      Users who has CELT could stake CELT into the pool to generate Crystal.
 
• How is the token being distributed? Are you conducting an airdrop? 
Presale 14%
Game Ecosystem 40%
Development 5%
Marketing 10%
DAO 4%
LP 8%
TEAM 10%
Foundation 6%
Consultant 2%
Audit 1%
 
• Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale? 
There was two institution invested us, ZBS capital, OKEx Blockdream Ventures
• Is the token listed on a centralized/decentralized exchange? 
Pancake swap
• Is a Smart Contract audit completed? Where can we find this information?
https://www.certik.org/projects/celestial

**Pull request merged**
