### PR TITLE
Add Life Token v2 (BEP20)

### PR DESCRIPTION
**Pull request by ghost**
Adding info for BEP20 token 'Life Token v2'.

PR created by <a href="https://assets.trustwallet.com">TW Assets Management</a>

### CODE REVIEW

**Comment by cryptomanz** [comment]
• What is the purpose of this token? How will it benefit Trust Wallet users?
 • How is the token being distributed? Are you conducting an airdrop?
 • Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?
 • Is the token listed on a centralized/decentralized exchange?
 • Is a Smart Contract audit completed? Where can we find this information?

**Comment by ziubelluu** [comment]
• What is the purpose of this token? How will it benefit Trust Wallet users?

Life Token is a charity-orientated token on the Binance Smart Chain. Our goal is to aid Suicide Prevention charities all over the world, to help save lives.

Life Token is the first project in the world that puts at the center of its ecosystem the health and welfare of people, promoting mental health awareness and setting as the ultimate goal the realization of the first health and life insurance system, fully decentralized, managed entirely through NFTs. 

• How is the token being distributed? Are you conducting an airdrop?

LifeToken V1 was sold to users, when LifeToken V2 launched all users that were holding V1 tokens were airdropped their tokens, the rest of the tokens are in circulation. 

• Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?

64.38% of LifeToken V2 tokens during the presale was sold.

• Is the token listed on a centralized/decentralized exchange?

PancakeSwap

• Is a Smart Contract audit completed? Where can we find this information?

Yes, audited here: https://www.thelifetoken.com/documents/auditpaper.pdf

**Comment by cryptomanz** [comment]
Hello,
Please follow the rules for adding token, your logo should be a full screen.

**Comment by ziubelluu** [comment]
Screenshot_2021-12-31-20-56-14-507_com android chrome
Here it's says 256x256

**Pull request merged**
