### PR TITLE
Add SME logo and info

### PR DESCRIPTION
**Pull request by ceoguy**
Request to add SafeMeme's logo and information into TrustWallet.

### CODE REVIEW

**Comment by Cryptocool1** [comment]
:
Info.json is incorrect. It should be of the form:
{
    "name": "Trust Wallet Token",
    "type": "ERC20",
    "symbol": "TWT",
    "decimals": 8,
    "description": "Utility token to increase adoption of cryptocurrency.",
    "website": "https://trustwallet.com",
    "explorer": "https://explorer.binance.org/asset/TWT-8C2",
    "status": "active",
    "id": "TWT-8C2"
}
Please follow documentation: https://community.trustwallet.com/t/how-to-submit-a-token-logo/3863

**Comment by ceoguy** [comment]
Hey there, thanks for letting me know.
How do I update this? Do I pay again?

Thank You,
Ilan Rakhmanov.

**Comment by Cryptocool1** [comment]
> Hey there, thanks for letting me know. How do I update this? Do I pay again? Thank You, Ilan Rakhmanov.
> […](#)

You can create new PR.
You don't need to pay one more time. Make sure to mention this PR.
You may want to try our new Assets app in beta; go to https://assets.trustwallet.com, log on with Github, enter contract ID, logo and some additional info, and it will create a PR for you.
See https://community.trustwallet.com/t/how-to-submit-a-token-logo-using-assets-app/82957.

**Comment by ceoguy** [comment]
Hey I updated the info.Jason file and did the process again under the same
folder I created originally. Is that ok?

**Pull request closed without merging**
