### PR TITLE
Add MetaHouse logo and info

### PR DESCRIPTION
**Pull request by aiyou2**
Add MetaHouse logo and info

### CODE REVIEW

**Comment by aiyou2** [comment]
hash：
C4839C22DD394313D94E7365527AA05EE35D6941658E27DBDAFF956C58399A3A

**Comment by Cryptocool1** [comment]
can you please add tags and links?
see criteria here: https://developer.trustwallet.com/assets/requirements

**Comment by aiyou2** [comment]
Links and tags have been added

**Comment by aiyou2** [comment]
Holder：10230
https://bscscan.com/token/0x825791bc83a377ba3931e8a56504a1eacaae0f76

**Comment by aiyou2** [comment]
Audit：
https://github.com/solidproof/projects/blob/main/MetaHouse/SmartContract_Audit_Solidproof_House.pdf

**Comment by cryptomanz** [comment]
• What is the purpose of this token? How will it benefit Trust Wallet users?
 • How is the token being distributed? Are you conducting an airdrop?
 • Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?
 • Is the token listed on a centralized/decentralized exchange?

**Comment by aiyou2** [comment]
• This token is to create a real estate asset in the Metaverse
• 60% of tokens are used for pre-sale, 40% to add liquidity, and the team has no reservations
•Pre-sale at unicrypt
•Listed on pancakeV2 exchange

**Pull request merged**
