### PR TITLE
Logo upload

### PR DESCRIPTION
**Pull request by 0xBenxx211226**

### CODE REVIEW

**Comment by LITHYI** [comment]
Hi can I have a BEP-20 address for TWT?

**Comment by Cryptocool1** [comment]
Only BEP2

**Comment by Cryptocool1** [comment]
Please create new PR, follow doc https://community.trustwallet.com/t/how-to-submit-a-token-logo/3863
You may want to try our Assets app in beta; go to https://assets.trustwallet.com, log on with Github, enter contract ID, logo and some additional info, and it will create a PR for you.
See https://community.trustwallet.com/t/how-to-submit-a-token-logo-using-assets-app/82957.

**Comment by LITHYI** [comment]
Ok, creating bep2 wallet now, is the logo file ok? cus these said Error: No token files found.

**Comment by LITHYI** [comment]
Ok, Trasfer done, does anything else I should do here?

**Pull request closed without merging**
