### PR TITLE
Add XDRAKE (BEP20)

### PR DESCRIPTION
**Pull request by xdrakeNFT**
Adding info for BEP20 token 'XDRAKE'.

PR created by <a href="https://assets.trustwallet.com">TW Assets Management</a>

### CODE REVIEW

**Comment by xdrakeNFT** [comment]
"Token check error:
❌ number of holders not checked: please, check it manually"

Does this issue affect the token logo update process?

**Comment by xdrakeNFT** [comment]
I sent 5 BNB fees

**Comment by xdrakeNFT** [comment]
> • What is the purpose of this token? How will it benefit Trust Wallet users? • How is the token being distributed? Are you conducting an airdrop? • Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale? • Is the token listed on a centralized/decentralized exchange? • Is a Smart Contract audit completed? Where can we find this information?

1. This token is used as the circulating currency of our game. You can check it out at: https://game.xdrake.io/

2. Tokens will be distributed based on the pre-sale. We have Tokenomics and a fixed amount of tokens for the airdrop.

3. We are not currently having a Token pre-sale. It is expected that the Token pre-sale will take place from February 25 to February 27

4. Our Tokens will be listed on PancakeSwap upon completion of pre-sale. Estimated time is March 1, 2022

5. Yes, we have completed audit by Solid finance.
Link to check: https://solidity.finance/audits/XDRAKE/

**Comment by Cryptocool1** [comment]
As per our policy, brand new tokens are not included, there is a minimum requirement of 5,000 holder addresses and 10,000 transactions, in order to filter out scam tokens.
See the criteria at : https://developer.trustwallet.com/assets/requirements .

**Comment by Cryptocool1** [comment]
please come back to us when all criteria are met. make sure to mention this PR so the fee can be reused

**Comment by xdrakeNFT** [comment]
Add logo for me pls

**Pull request closed without merging**
