### PR TITLE
Add Crypto AI (BEP20)

### PR DESCRIPTION
**Pull request by cryptoaigit**
Adding info for BEP20 token 'Crypto AI'.

PR created by <a href="https://assets.trustwallet.com">TW Assets Management</a>

### CODE REVIEW

**Comment by crypto-ai-git** [comment]
Audit: https://github.com/solidproof/projects/blob/main/Crypto%20AI/SmartContract_Audit_Solidproof_CryptoAi.pdf

**Comment by Cryptocool1** [comment]
• What is the purpose of this token? How will it benefit Trust Wallet users?
 • How is the token being distributed? Are you conducting an airdrop?
 • Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?
 • Is the token listed on a centralized/decentralized exchange?
 • Is a Smart Contract audit completed? Where can we find this information?

**Comment by web5inu** [comment]
• What is the purpose of this token? How will it benefit Trust Wallet users?
Crypto AI, an AI-powered using AI Machine Learning to Create Digital Asset, benefit trust wallet users to able check price and details

• How is the token being distributed? Are you conducting an airdrop?
Token distributed through pancake swap, no airdrop.

• Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?
No ICO, presale.

• Is the token listed on a centralized/decentralized exchange?
Pancakeswap DEX.

• Is a Smart Contract audit completed? Where can we find this information?
Smart audit done at https://github.com/solidproof/projects/blob/main/Crypto%20AI/SmartContract_Audit_Solidproof_CryptoAi.pdf

**Comment by Cryptocool1** [comment]
Are you listed on CMC?

**Comment by web5inu** [comment]
> Are you listed on CMC?

https://coinmarketcap.com/currencies/crypto-ai-bsc/

**Pull request merged**
