### PR TITLE
Br0321 145256

### PR DESCRIPTION
**Pull request by metacader**

### CODE REVIEW

**Comment by Metacader-JM** [comment]
@Cryptocool1 

* What is the purpose of this token? How will it benefit Trust Wallet users?
At Metacade our vision is to become the premier gaming platform that empowers developers and players, providing unparalleled opportunities for growth and collaboration.
Through creativity and innovation we aim to create a fun first community that offers a rewarding and enjoyable experience, while delivering a revenue driven platform that gives value to $MCADE token holders.
Trust Wallet is one of our recommended wallets to users.

* How is the token being distributed? Are you conducting an airdrop?
You can purchase the MCADE token using credit & bank transfers through our payment partner Transak and Centralised & Decentralised Exchanges.

* Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?
There was an initial presale period for the MCADE token.

* Is the token listed on a centralized/decentralized exchange?
MCADE token is listed on:
Bitget - https://www.bitget.com/spot/MCADEUSDT
Coinstore - https://www.coinstore.com/#/spot/MCADEUSDT?ts=1713939435059
Bitmart - https://www.bitmart.com/trade/en-US?symbol=MCADE_USDT&layout=pro
Uniswap - https://app.uniswap.org/swap

Metacade can also be found:
Coinmarketcap - https://coinmarketcap.com/currencies/metacade/
CoinGecko - https://www.coingecko.com/en/coins/metacade

* Is a Smart Contract audit completed? Where can we find this information?
Full Certik audit can be found here https://skynet.certik.com/projects/metacade

**Comment by Cryptocool1** [comment]
Please come back to us once you are ready to answer the questions we asked above. 
When creating new Pull Request, make sure to mention this PR so the fee can be reused

**Comment by Metacader-JM** [comment]
@Cryptocool1 these question were answered and they were deleted

**Comment by Metacader-JM** [comment]
Please reopen the pull request as the fee has been paid

**Pull request closed without merging**
