### PR TITLE
PROOF coin logo update

### PR DESCRIPTION
**Pull request by prfcoin**
Add round design logo version for Trust Wallet app
logo

### CODE REVIEW

**Comment by catenocrypt** [comment]
Somehow the checksum-format (mixed-case) and lower-case folders got mixed up, I am trying to clean them up in the PR.

**Comment by prfcoin** [comment]
Can I do something in this case?

**Comment by catenocrypt** [comment]
@prfcoin , the advice is not to use an outdated fork for the changes: either refresh it (merge main assets:master branch into it), or remove it and create afresh. 
For some strange reason both files got added to GitHub twice, once in lowercase folder name, once in checksum, but somehow they still pointed to the same file.

**Comment by prfcoin** [comment]
I understood!
Thank you so much!

**Pull request merged**
