### PR TITLE
Add dexIRA (BEP20) (Paid via #12795)

### PR DESCRIPTION
**Pull request by dexfi-com**
This PR is being closed due to inactivity. If you wish to continue, please have us reopen the PR before sending your payment, or just create a new one.
Do NOT send payments for closed PR, as the fee may by lost!
  (87 vs. 48 hrs)

### CODE REVIEW

**Comment by cryptomanz** [comment]
As per our policy, brand new tokens are not included, there is a minimum requirement of 5000 holder addresses and 10000 transactions, in order to filter out scam tokens.
See the criteria at (mentioned in the first message by the bot): https://community.trustwallet.com/t/how-to-submit-a-token-logo/3863).
Closing PR for now. Please come back to us when all criteria are met.

**Comment by dexIRA** [comment]
Hi! We have sent our contribution of 2000 TWT fee as requested. TxID# D5...EB8B ([Link](https://explorer.binance.org/tx/D504C0C2687D8405338F514B90CDCB7D8DAFE356BB0F867AFD64BA06A368EB8B))

In regards to our token, we are an established brand with demonstrable use-cases. All audits and other pertinent information can be found on our website at: [dexIRA.com](https://dexira.com/).

We kindly ask that you review our submission again. Please let us know if you have any questions or concerns. Thank you!

**Comment by dexIRA** [comment]
@cryptomanz @Cryptocool1 

We kindly ask that you reopen and or merge our submission... Today, dexIRA (DEX) was approved and added to FTX (Blockfolio) and we want to maintain our current trajectory 👍 

Note: All audits and other pertinent information can be found on our website at dexIRA.com

Please let us know if you have any questions or concerns. Thanks!

**Comment by Cryptocool1** [comment]
Payment was not found by the bot; could you provide TXID for checking?

**Comment by dexIRA** [comment]
> Payment was not found by the bot; could you provide TXID for checking?

TxID:
D504C0C2687D8405338F514B90CDCB7D8DAFE356BB0F867AFD64BA06A368EB8B

https://explorer.binance.org/tx/D504C0C2687D8405338F514B90CDCB7D8DAFE356BB0F867AFD64BA06A368EB8B

**Comment by dexIRA** [comment]
> Payment was not found by the bot; could you provide TXID for checking?

Thank you for reopening. TXID below:
https://explorer.binance.org/tx/D504C0C2687D8405338F514B90CDCB7D8DAFE356BB0F867AFD64BA06A368EB8B

**Comment by dexIRA** [comment]
> Payment was not found by the bot; could you provide TXID for checking?

@Cryptocool1 @cryptomanz bumping to reopen..

As requested,

TxID = D504C0C2687D8405338F514B90CDCB7D8DAFE356BB0F867AFD64BA06A368EB8B

https://explorer.binance.org/tx/D504C0C2687D8405338F514B90CDCB7D8DAFE356BB0F867AFD64BA06A368EB8B

Please let us know if you have any questions or concerns. Thanks!

**Comment by dexIRA** [comment]
**• What is the purpose of this token? How will it benefit Trust Wallet users?**
dexIRA is a platform that allows users to collect and manage a diverse array of curated cryptocurrency tokens by holding dexIRA ($DEX) tokens. Each reward distribution is automatically claimed by the holder and sent to their wallet. There are zero transaction fees on buy orders to incentivize investment. All sell transaction fees are waived after one year of holding DEX tokens without sale, promoting a long term investing strategy and reliable price support.

This will benefit Trust Wallet users by enabling them to acquire a secure and well rounded portfolio of established tokens with a history of success. In addition, our dapp (dashboard) gives users the opportunity to view and monitor advanced portfolio metrics which offers useful insight to their investments.

 **• How is the token being distributed? Are you conducting an airdrop?**
We do not conduct any airdrops. All tokens must be bought on the open market (including dev tokens).

 **• Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?**
This token was sold initially sold as a fair launch ICO on July 21st 2021 at 6PM UTC

 **• Is the token listed on a centralized/decentralized exchange?**
We are currently traded on PancakeSwap and in the process of listing on several other centralized exchanges as well. 

 **• Is a Smart Contract audit completed? Where can we find this information?**
We have had two successful third party audits completed. You can find them both here:
https://dexira.com/audits/

**Comment by dexIRA** [comment]
@cryptomanz @Cryptocool1 **bumping to re-open…**

**paid** via tx# D504C0C2687D8405338F514B90CDCB7D8DAFE356BB0F867AFD64BA06A368EB8B

**Pull request closed without merging**
