### PR TITLE
Adding details for Pieme (PIE) info and logo

### PR DESCRIPTION
**Pull request by voxmagna1**
Project address: 0x0581E55FdcB0874D885c5C02DD5DEe3D6F7F2136
Bscscan: https://bscscan.com/token/0x0581E55FdcB0874D885c5C02DD5DEe3D6F7F2136

### CODE REVIEW

**Comment by voxmagna1** [comment]
info.json edited

**Comment by Cryptocool1** [comment]
your files are incorrect
Please create new PR, follow doc https://developer.trustwallet.com/assets/requirements
You may want to try our Assets app in beta; go to https://assets.trustwallet.com, log on with Github, enter contract ID, logo and some additional info, and it will create a PR for you.
See https://developer.trustwallet.com/assets/repository_details

**Comment by voxmagna1** [comment]
Do I need to pay again for new PR ?

**Comment by voxmagna1** [comment]
Please check
https://github.com/trustwallet/assets/pull/19951

**Comment by Cryptocool1** [comment]
No you don’t need to pay again. 
#19952 is incorrect. 
please follow the instructions

**Pull request closed without merging**
