### PR TITLE
Add SST  logo

### PR DESCRIPTION
**Pull request by daniilmolch**

### CODE REVIEW

**Comment by Iamdeadlyz** [comment]
As per our policy, brand new tokens are not included. There is a minimum requirement of 500 holder addresses and 1000 transactions in order to filter out scam tokens. See the criteria at (mentioned in the first message by the bot): https://community.trustwallet.com/t/how-to-submit-a-token-logo/3863#how-to-get-approved

This token has below-limit usage yet. This pull request will be but on hold. Please come back to us when all criteria are met.
https://etherscan.io/token/0x2863916C6ebDBBf0c6f02F87b7eB478509299868 (292, 635)

**Comment by daniilmolch** [comment]
Hello! I understood the situation with the limits on the number of addresses and transactions, I did not pay attention, since earlier you had more loyal conditions. I will return as soon as the required amount is reached. Hope my 2bnb payment won't be lost. Thanks!

**Comment by Iamdeadlyz** [comment]
> Hello! I understood the situation with the limits on the number of addresses and transactions, I did not pay attention, since earlier you had more loyal conditions. I will return as soon as the required amount is reached. Hope my 2bnb payment won't be lost. Thanks!

Sure, it won't be lost since it is already recorded in this PR. Feel free to ping me if you already reached the said requirements, cheers!

**Comment by vikmeup** [comment]
> Hello! I understood the situation with the limits on the number of addresses and transactions, I did not pay attention, since earlier you had more loyal conditions. I will return as soon as the required amount is reached. Hope my 2bnb payment won't be lost. Thanks!

Re-open pull request once you meet requirements. Not additional payment is required.

**Comment by RafinadDaniil** [comment]
Hello! We have fulfilled your conditions: 500 holders and 2000+ transactions, can you add a logo to our SST token? https://etherscan.io/token/0x2863916C6ebDBBf0c6f02F87b7eB478509299868

**Comment by daniilmolch** [comment]
Hello! We have fulfilled your conditions: 500 holders and 1000+ transactions, can you add a logo to our SST token?

**Pull request closed without merging**
