### PR TITLE
Add PAPPAY (BEP20)

### PR DESCRIPTION
**Pull request by Pappay**
Adding info for BEP20 token 'PAPPAY'.

PR created by <a href="https://assets.trustwallet.com">TW Assets Management</a>

### CODE REVIEW

**Comment by Cryptocool1** [comment]
• Is a Smart Contract audit completed? Where can we find this information?

**Comment by Pappay** [comment]
Hello, Our logo does not appear on Trust Wallet. Is there anything we should do? Other than waiting?

Thank you

@Iamdeadlyz, @Cryptocool1, @cryptomanz

**Comment by Cryptocool1** [comment]
Is a Smart Contract audit completed? Where can we find this information?

**Comment by Cryptocool1** [comment]
please create new PR when you will be ready to send your audit. When creating new PR make sure to mention this one, so the fee can be reused.

**Pull request closed without merging**
