### PR TITLE
First upload of PLX logo and info

### PR DESCRIPTION
**Pull request by OctaplexNetwork**
Please consider adding our token information and logo to the trustwallet repository.

Here is some information for the verification of our project:
Website: https://octaplex.io/
White paper: https://octaplex.gitbook.io/octaplex-network-whitepaper/
Audit report: https://github.com/MaverickHP/brewlabs-audits/blob/main/Brewlabs%20-%20Octaplex%20Network%20Block%209906269.pdf
Team KYC information: https://www.assuredefi.io/projects/octaplex-network/
CoinGecko: https://www.coingecko.com/en/coins/octaplex-network
CoinMarketCap listing: Pending Approval

Social media and other sources:
https://twitter.com/OctaplexNetwork
https://t.me/OctaplexNetwork
https://discord.gg/B3tG7XRWEW
https://www.reddit.com/r/Octaplex/
https://medium.com/@OctaplexNetwork

Octaplex Rewards DAPP:
https://app.octaplex.io/

For any questions or requests, feel free to send me an email or our team at octaplexnetwork@octaplex.io

Thanks in advance!

Regards,
Zander

### CODE REVIEW

**Comment by OctaplexNetwork** [comment]
We will try to address the token check errors before proceeding with the contribution. 

Thank you very much!

**Comment by OctaplexNetwork** [comment]
Answers to some questions I have seen asked before:

**• What is the purpose of this token? How will it benefit Trust Wallet users?**
Octaplex Network strives to create a safe space within the BSC for investors and connect trusted projects and content creators with each other. Trust Wallet users who buy and hold the Octaplex Network token (PLX) can customize their rewards using our dapp and be rewarded in up to six currencies simultaneously, including BEP20 pegged versions of major altcoins and tokens from our partner network. This creates exposure for our partners and for future Trust Wallet users.

More information is available in our whitepaper: https://octaplex.gitbook.io/octaplex-network-whitepaper/
DAPP with Trust Wallet Support:
https://app.octaplex.io/

**• How is the token being distributed? Are you conducting an airdrop?**
PLX tokens are tradable through pancakeswap and similar decentralized exchanges:
Here is a link to the main PLX/BNB liquidity pool:
https://bscscan.com/address/0x63730fCf35b0edC45742c19EBE20205Ab99cE05d

A token presale was held on DXSale before launch: https://dxsale.app/app/v2_9/defipresale?saleID=2887&chain=BSC

A private presale of approximately 75 BNB was held using this wallet address:
https://bscscan.com/address/0x17CDae38a8f12842b4Ab42Fc50027898D4a0f8e2
Tokens were distributed manually to these investors before launch

Apart from sales, 2% of the token supply is reserved for promotions and competitions through our partner projects. In return we incorporate partners into the Octaplex Network and add partner tokens to our PLX holder reward system. 
Announcements of our mutual partnerships can be viewed on our twitter page: https://twitter.com/OctaplexNetwork

**• Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?**
A token presale was held on DXSale before launch: https://dxsale.app/app/v2_9/defipresale?saleID=2887&chain=BSC

A private presale of approximately 75 BNB was held using this wallet address:
https://bscscan.com/address/0x17CDae38a8f12842b4Ab42Fc50027898D4a0f8e2
Tokens were distributed manually to these investors before launch.

**• Is the token listed on a centralized/decentralized exchange?**

PLX can be traded on PancakeSwap
https://pancakeswap.finance/swap?outputCurrency=0x57022eDD5C7Ed7b6bd870488853Fe961dfDD3fB6

PLX is listed and can also be traded on ShibaNovaDex:
https://swap.shibanova.io/#/swap

We were listed organically on https://www.coingecko.com/en/coins/octaplex-network

**• Is a Smart Contract audit completed? Where can we find this information?**
Yes. A complete audit report of our project and smart contract by BrewLabs is available at:
https://github.com/MaverickHP/brewlabs-audits/blob/main/Brewlabs%20-%20Octaplex%20Network%20Block%209906269.pdf

**Comment by cryptomanz** [comment]
- Logo image too large, max 100 kB, current 276.239 kB
-  Low token circulation: no. of holders is 3062, below limit of 5000
- As per our policy, brand new tokens are not included, there is a minimum requirement of 5000 holder addresses and 10000 transactions, in order to filter out scam tokens.
See the criteria at (mentioned in the first message by the bot): https://community.trustwallet.com/t/how-to-submit-a-token-logo/3863).
Closing PR for now. Please come back to us when all criteria are met.

**Comment by Cryptocool1** [comment]
please create new PR when all criteria are met. Make sure to mention this PR so the fee can be reused

**Pull request closed without merging**
