### PR TITLE
Adding RTF logo

### PR DESCRIPTION
**Pull request by roosterfinance**
Please Add the RTF logo, Thanks.

### CODE REVIEW

**Comment by catenocrypt** [comment]
Correction needed: Please remove the file `RoosterFinance.png`; the `logo.png` is enough.

**Comment by roosterfinance** [comment]
> Correction needed: Please remove the file `RoosterFinance.png`; the `logo.png` is enough.

How to remove sir? sorry this is my first time.

**Comment by roosterfinance** [comment]
> Correction needed: Please remove the file `RoosterFinance.png`; the `logo.png` is enough.

Done.

**Comment by roosterfinance** [comment]
What do I need to do more?

**Pull request merged**
