### PR TITLE
Request Update Logo For Buffet Kishu

### PR DESCRIPTION
**Pull request by ghost**

### CODE REVIEW

**Comment by Cryptocool1** [comment]
• What is the purpose of this token? How will it benefit Trust Wallet users?
 • How is the token being distributed? Are you conducting an airdrop?
 • Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?
 • Is the token listed on a centralized/decentralized exchange?
 • Is a Smart Contract audit completed? Where can we find this information?

**Comment by vgda10** [comment]
Thanks

Pada tanggal Rab, 10 Nov 2021 pukul 20.08 merge-fee-bot[bot] <
***@***.***> menulis:

**Comment by Cryptocool1** [comment]
What is the purpose of this token? How will it benefit Trust Wallet users?
• How is the token being distributed? Are you conducting an airdrop?
• Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?
• Is the token listed on a centralized/decentralized exchange?
• Is a Smart Contract audit completed? Where can we find this information?

**Comment by vgda10** [comment]
Our mission is to give investors rewards without staking, so only by
holding our tokens, they will get more benefits.
We don't do ICO or Presale.
The token already listed on Decentralized Exchanges, one of the is
pancakeswap here the link
https://pancakeswap.finance/swap?outputCurrency=0x5Df2a4E44C25532326D5aad71c19A9976784320f
And the audit still not complete yet. Already requested to techrate

Pada tanggal Kam, 11 Nov 2021 pukul 04.49 CryptoA ***@***.***>
menulis:

**Comment by cryptomanz** [comment]
On hold for now, awaiting for smart contract audit.

**Comment by Cryptocool1** [comment]
Please come back to us when all criteria are met.
When creating a new PR make sure to mention this PR, so that we can see that fee has been paid already here.

**Pull request closed without merging**
