### PR TITLE
Add RichCity (BEP20)

### PR DESCRIPTION
**Pull request by PAWGCoin**
Adding info for BEP20 token 'RichCity'.

PR created by <a href="https://assets.trustwallet.com">TW Assets Management</a>

### CODE REVIEW

**Comment by Cryptocool1** [comment]
hello 
are you conducting an airdrop?

**Comment by PAWGCoin** [comment]
Hi team,

We are not conducting any airdrop. We had a private/pre sale prior to raise
funds for liquidity.

**Comment by Cryptocool1** [comment]
• What is the purpose of this token? How will it benefit Trust Wallet users?
 • Is the token listed on a centralized/decentralized exchange?
 • Is a Smart Contract audit completed? Where can we find this information?

**Comment by PAWGCoin** [comment]
It is the primary and only token used in our upcoming mobile social NFT
game (see www.RICHCITY.com)

It is listed on PancakeSwap

Audit is currently in progress. Our code was already audited by TechRate
under a different name (Richie Rich Coin), and also with Dessert Swap
Finance where we are ID verified for extra security.
https://dessertswap.finance/audits/Richie%20Rich%20BEP-20%20Audit%207085779.pdf

**Comment by PAWGCoin** [comment]
Hey guys,

Just following up. Any updates?

Thanks!

**Comment by PAWGCoin** [comment]
We just got listed on Coin Market Cap:

https://coinmarketcap.com/currencies/richcity/

**Comment by Cryptocool1** [comment]
can you please add links to your PR?
example: https://developer.trustwallet.com/add_new_asset#info-json-contents

**Comment by Cryptocool1** [comment]
you need to add 2 links at least

**Comment by PAWGCoin** [comment]
I see. Is this a new policy as of this week?

I’ll have the articles hopefully soon.

**Comment by PAWGCoin** [comment]
Thank you!

**Pull request merged**
