### PR TITLE
Upload cashback

### PR DESCRIPTION
**Pull request by 0405degrees**
Upload Cashback

### CODE REVIEW

**Comment by catenocrypt** [comment]
Please add an `info.json` file next to the `logo.png`, with info about the project, of the form:

```json
{
    "name": "Trust Wallet Token",
    "website": "https://trustwallet.com",
    "short_description": "Utility token to increase adoption of cryptocurrency.",
    "explorer": "https://explorer.binance.org/asset/TWT-8C2",
    "socials": [
        {
            "name": "Twitter",
            "url": "https://twitter.com/trustwalletapp",
            "handle": "TrustWalletApp"
        },
        {
            "name": "Reddit",
            "url": "https://reddit.com/r/trustapp",
            "handle": "TrustApp"
        }
    ]
}
```

**Comment by 0405degrees** [comment]
> Please add an `info.json` file next to the `logo.png`, with info about the project, of the form:
> 
> ```json
> {
>     "name": "Trust Wallet Token",
>     "website": "https://trustwallet.com",
>     "short_description": "Utility token to increase adoption of cryptocurrency.",
>     "explorer": "https://explorer.binance.org/asset/TWT-8C2",
>     "socials": [
>         {
>             "name": "Twitter",
>             "url": "https://twitter.com/trustwalletapp",
>             "handle": "TrustWalletApp"
>         },
>         {
>             "name": "Reddit",
>             "url": "https://reddit.com/r/trustapp",
>             "handle": "TrustApp"
>         }
>     ]
> }
> ```

Please how do i do this?

Thanks

**Comment by 0405degrees** [comment]
@zachzwei please assist

**Comment by 0405degrees** [comment]
{
    "name": "CASHBACK Token",
    "website": "https://cashback.so",
    "short_description": "Cashback E-commerce Exchange was born from new ideas based on great start-up technologies and has had certain achievements in the market.",
    "explorer": "https://etherscan.io/address/0xa8ec2b2f021b55d7d594c8d12bbd6d23c05245d7",
    "socials": [
        {
            "name": "Twitter",
            "url": "https://twitter.com/Cashbac32382308",
            "handle": "Cashbac32382308"
        },
        {
            "name": "Facebook",
            "url": "https://www.facebook.com/cashback.holdings",
            "handle": "cashback.holdings"
        },
        {
            "name": "Telegram",
            "url": "https://t.me/joinchat/O8S9UxtVzQOlbfdhoeFknw",
            "handle": "CASHBACK - Nhà Đầu Tư"
        }
    ]
}

**Comment by zachzwei** [comment]
For security reasons, please resubmit your PR as it shows that this is coming from an unknown repo.
Also include a info.json file on your submission and make sure you are following the parameters of the logo.
Learn more here:
https://community.trustwallet.com/t/how-to-submit-a-token-logo/3863#how-to-get-approved

**Pull request closed without merging**
