### PR TITLE
Logo fix

### PR DESCRIPTION
**Pull request by JJack-ctrl**
Hello, it seems our logo is cut off and would like to submit a fixed size logo.

### CODE REVIEW

**Comment by JJack-ctrl** [comment]
Hey, the price of 250 TWT and 2 BNB is way far off. Are you sure we can process with 250TWT?

**Comment by JJack-ctrl** [comment]
Hey guys, i'm getting an error and im not sure what needs to be fixed

**Comment by catenocrypt** [comment]
Structure of the file in this PR is wrong, cannot be evaluated.
Please follow documentation:  https://community.trustwallet.com/t/how-to-submit-a-token-logo/3863
You may want to try our Assets app (in beta);  close this PR; go to https://assets.trustwallet.com, log on with Github, enter contract ID, logo and some additional info, and it will create a PR for you.  See  https://community.trustwallet.com/t/how-to-submit-a-token-logo-using-assets-app/82957 
Mention this PR to reuse fee paid.

**Comment by JJack-ctrl** [comment]
> Structure of the file in this PR is wrong, cannot be evaluated.
> Please follow documentation: https://community.trustwallet.com/t/how-to-submit-a-token-logo/3863
> You may want to try our Assets app (in beta); close this PR; go to https://assets.trustwallet.com, log on with Github, enter contract ID, logo and some additional info, and it will create a PR for you. See https://community.trustwallet.com/t/how-to-submit-a-token-logo-using-assets-app/82957
> Mention this PR to reuse fee paid.

Hello, I created a new PR with fixed issues on PR #6608

**Comment by catenocrypt** [comment]
Payment considered for #6608 .

**Pull request closed without merging**
