### PR TITLE
PROPS coin

### PR DESCRIPTION
**Pull request by harispericorn**
type of token is not defined as no type field available for aptos in the provided options.

### CODE REVIEW

**Comment by Cryptocool1** [comment]
Please create new PR, follow doc https://developer.trustwallet.com/listing-new-assets/requirements
You may want to try our Assets app in beta; go to https://assets.trustwallet.com, log on with Github, enter contract ID, logo and some additional info, and it will create a PR for you.
See https://developer.trustwallet.com/listing-new-assets/repository_details

**Comment by harispericorn** [comment]
the process your are requesting to follow not exist for aptos token please help to sort this out as type field is not present for aptos token

**Comment by harispericorn** [comment]
Screenshot from 2024-01-19 16-49-33

**Comment by harispericorn** [comment]
Screenshot from 2024-01-19 16-50-33

**Pull request closed without merging**
