### PR TITLE
update to a new contract and add a new token

### PR DESCRIPTION
**Pull request by bi0hazard12**
As request by @cryptomanz on previous #16563 this is the new PR

We need to remove our old contract 0x3b62F3820e0B035cc4aD602dECe6d796BC325325 and update to this new one 0xDE5ed76E7c05eC5e4572CfC88d1ACEA165109E44.

We also need to add our newly token DEI (our algorithmic stable coin)
0xDE12c7959E1a72bbe8a5f7A1dc8f8EeF9Ab011B3

Fee was already paid in the previous PR:16563

Thank you once again :)

### CODE REVIEW

**Comment by bi0hazard12** [comment]
fee paid on #16563

**Comment by bi0hazard12** [comment]
@cryptomanz Can you take a look at this please? Thank you

**Comment by cryptomanz** [comment]
are you the owner of the tokens "DEA", "wCOINBASE-IOU"?
There are not enough holders and transactions for the DAI token, we will not be able to add it

**Comment by bi0hazard12** [comment]
> are you the owner of the tokens "DEA", "wCOINBASE-IOU"? There are not enough holders and transactions for the DAI token, we will not be able to add it

i'm the person responsible on DEUS Finance for those pull request you can see previously that i was the one that created the pull request for all our tokens DEA and wCOINBASE-IOU included.

as for DEI is our stablecoin and as of right you don't see to much holders because we have a stacking program where most of the DEI is stacked at our farming contracts and are mostly used on polygon with 14000 transactions since it's a token from DEUS main ecosystem and it's our stablecoin can you please take that in account? We appreciate so much.

Also one question are the updated DEUS contract and DEI be able to also be visible on the polygon network after the pull request?

**Comment by bi0hazard12** [comment]
> This PR is being closed due to inactivity. If you wish to continue, please have us reopen the PR before sending your payment, or just create a new one. Do NOT send payments for closed PR, as the fee may by lost!

@cryptomanz Can this be reopen please?

**Pull request closed without merging**
