### PR TITLE
Add Moonlight Token Logo and Info

### PR DESCRIPTION
**Pull request by Moonlighttoken**
Logo : 256x256
Info about Moonlight

### CODE REVIEW

**Comment by Cryptocool1** [comment]
PR should include only 2 files:

blockchains/smartchain/assets/0x42282fBbef486cf9eaf00cb3030810310F614568/logo.png
blockchains/smartchain/assets/0xb1ced2e320e3f4c8e3511b1dc59203303493f382/info.json

**Comment by Cryptocool1** [comment]
If you can't delete file in the PR, you may open a new PR. Make sure to mention this PR, so that we can see that fee has been paid already here.

**Comment by Cryptocool1** [comment]
You can try this app https://assets.trustwallet.com

**Comment by Moonlighttoken** [comment]
Thanks but after filling the file, i have a message "No. holder could not
be checked"
I'm trying to do a new PR
thanks for your help

**Comment by Cryptocool1** [comment]
Duplicate of #7511

**Pull request closed without merging**
