### PR TITLE
add GYEN

### PR DESCRIPTION
**Pull request by gmo-z-trust-deployer**
GYEN anchors its value to the price of the Japanese Yen. Redeemable and pegged 1-to-1 with fiat currency to virtually eliminate volatility, while still benefiting from the advantages of cryptocurrency, such as high-speed transaction and low costs, especially for cross-border payments.

### CODE REVIEW

**Comment by Cryptocool1** [comment]
• What is the purpose of this token? How will it benefit Trust Wallet users?
 • How is the token being distributed? Are you conducting an airdrop?
 • Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?
 • Is the token listed on a centralized/decentralized exchange?

**Comment by gmo-z-trust-deployer** [comment]
1. GYEN is the first regulated JPY pegged stablecoin, regulated by the New York State Financial Services, similar to GUSD and USDP. We bridge the traditional and digital currency ecosystems.
2. No airdrops. We mint tokens to the direct purchasers. GYEN is listed on Liquid Exchange, Coinbase, INX, Nexus, Uniswap, etc.
3. No ICO. It is a stablecoin.
4. Yes, as described above.

**Comment by cryptomanz** [comment]
• Is a Smart Contract audit completed? Where can we find this information?

**Comment by gmo-z-trust-deployer** [comment]
Yes, Audit by Quantstamp is complete. Below, we have placed the report in our contract directory.

https://github.com/trust-zcom/gmotrust-stablecoin-contract/blob/master/audit_reports/20210212%20-%20GYEN%20%26%20ZUSD%20Contracts%20-%20Final%20Report.pdf

**Comment by cryptomanz** [comment]
can you please add links to your PR?
example:https://developer.trustwallet.com/assets/repository_details

**Comment by cryptomanz** [comment]
`
{
    "name": "Trust Wallet Token",
    "website": "https://trustwallet.com",
    "description": "Utility token to increase adoption of cryptocurrency.",
    "explorer": "https://explorer.binance.org/asset/TWT-8C2",
    "type": "BEP2",
    "symbol": "TWT",
    "decimals": 8,
    "status": "active",
    "id": "TWT-8C2",
    "links": [
        {
            "name": "github",
            "url": "https://github.com/trustwallet/"
        },
        {
            "name": "twitter",
            "url": "https://twitter.com/TrustWalletApp"
        },
        {
            "name": "reddit",
            "url": "https://reddit.com/r/trustapp"
        }
    ]
}
`

**Comment by gmo-z-trust-deployer** [comment]
Thank you, I added some links.

**Comment by cryptomanz** [comment]
These links incorrect:
 "https://coinmarketcap.com/ja/currencies/gyen/", "https://www.coingecko.com/en/coins/gyen", "https://www.youtube.com/channel/UCO7CNhdHYiJoBICgbo-yyiw/featured", should be  "https://coinmarketcap.com/currencies/gyen/", "https://coingecko.com/coins/gyen", "https://youtube.com/channel/UCO7CNhdHYiJoBICgbo-yyiw/featured"

**Comment by gmo-z-trust-deployer** [comment]
Thank you, I' ve fixed.

**Pull request merged**
