### PR TITLE
Add SafePokeman Token (BEP20)

### PR DESCRIPTION
**Pull request by SafePokeman**
Adding info for BEP20 token 'SafePokeman Token'.

PR created by <a href="https://assets.trustwallet.com">TW Assets Management</a>

### CODE REVIEW

**Comment by SafePokeman** [comment]
Please see https://github.com/trustwallet/assets/pull/10735 as this is in reference to SafePokemanToken logo

**Comment by cryptomanz** [comment]
As per our policy, brand new tokens are not included, there is a minimum requirement of 5000 holder addresses and 10000 transactions, in order to filter out scam tokens.
See the criteria at (mentioned in the first message by the bot): https://community.trustwallet.com/t/how-to-submit-a-token-logo/3863).
Closing PR for now. Please come back to us when all criteria are met.

**Comment by SafePokeman** [comment]
Hi, We applied before the 5,000 was updated. Please can you honour this for the review?

Kind Regards

**Comment by cryptomanz** [comment]
can you answer some questions please?
• What is the purpose of this token? How will it benefit Trust Wallet users?
 • How is the token being distributed? Are you conducting an airdrop?
 • Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?
 • Is the token listed on a centralized/decentralized exchange?
 • Is a Smart Contract audit completed? Where can we find this information?

**Comment by SafePokeman** [comment]
Hi, thank you. Please see the answers to your questions below.

> • What is the purpose of this token? How will it benefit Trust Wallet users?
We are developing a penny auction marketplace which will require users to purchase bid packages using SafePokeman Token for entry into a live auction. The bid packages are then allocated to the users account and the tokens that are spent to purchase bid packs are sent to the burn address, meaning that SafePokeman Token’s supply in circulation decreases therefore the value will increase. The auction marketplace will auction off graded TCG, Pokémon NFTs, fan art, bid packages, Pokémon products.

SafePokeman is unique allowing the final auction price to be affordable to everyone by making sure each bid placed only goes up in increments of $0.01 therefore there will be significant reductions in the final sale price of all auctions. The final auction price is then paid by the auction winner and the full amount is then donated to charity.

For all holders, 3% of each transaction on the contract is rewarded, this encourages users to hold for the long term as they can use their rewarded tokens to redeem bid packages, so the longer they hold, the more tokens they will get to purchase bids for free.

Because SAFEPOKEMAN is the native currency for this platform and we already promote Trust wallet to new investors it would be beneficial for both parties if our logo was updated.

We are frequently asked by members when our logo will be updated as the majority of our holders we believe use Trust Wallet. Having our logo displayed will also provide trust and confidence in our brand.

> • How is the token being distributed? Are you conducting an airdrop?
SafePokemanToken is being distributed by buying an selling through the pancakeswap exchange or via our website which incorporates the poocoin.app exchange. We have conducted and finalised the first airdrop with the 2nd airdrop underway (no payments made yet as these will be distributed after the 30th july). With the 2nd airdrop we have been endorsed by Veronica Taylor(Original voice of Ash Ketchum in Pokemon) as seen on our website safepokeman.com 

> • Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?
No, we released the token on a public sale whilst marketing on tiktok and twitter. No presale or ICO was conducted. 

> • Is the token listed on a centralized/decentralized exchange?
Yes, our token is listed on pancakeswap as seen below. It also is incorporated with poocoin.app, both of which are decentralised.
https://exchange.pancakeswap.finance/#/swap?outputCurrency=0xfb16b31fa8a6edcd2dde78654cb0668c724c1dac
https://poocoin.app/swap/?outputCurrency=0xfb16b31fa8a6edcd2dde78654cb0668c724c1dac

> • Is a Smart Contract audit completed? Where can we find this information?
Yes, we have been audited by solidity finance a while back and this information can be found on our website or below:
https://solidity.finance/audits/SafePokeman/

**Comment by Cryptocool1** [comment]
can you please add links to your PR?
example: https://developer.trustwallet.com/add_new_asset#info-json-contents

**Comment by SafePokeman** [comment]
> can you please add links to your PR?
> example: https://developer.trustwallet.com/add_new_asset#info-json-contents

https://github.com/trustwallet/assets/pull/10735/commits/406dbe6c6044bb8cb3afccfa082ed63dee05fa9d

i believe this one?

**Comment by cryptomanz** [comment]
yes, add links to your info.json

**Comment by SafePokeman** [comment]
> yes, add links to your info.json

thank you, i believe this one as per the thread?
https://github.com/trustwallet/assets/pull/11528/commits/8c8cac01461f94de3be5e95ab729d60c20067d5d

**Comment by SafePokeman** [comment]
> yes, add links to your info.json

Hi cryptomanz, 
Just thought i would update you aswell, BSC scan have today udated our logo and socials :)
https://bscscan.com/token/0xfb16b31fa8a6edcd2dde78654cb0668c724c1dac

**Comment by Cryptocool1** [comment]
can you please add links to your PR?
example: https://developer.trustwallet.com/add_new_asset#info-json-contents

**Comment by SafePokeman** [comment]
> can you please add links to your PR?
> example: https://developer.trustwallet.com/add_new_asset#info-json-contents

https://github.com/trustwallet/assets/pull/11725/commits/c7266b7c5d64a6c342af7c3b1c33902cbed321b4#diff-106a192a4a3dc6700ce127b18a05f70f562b829c250fd9b41884e26475617aa6

**Pull request merged**
