### PR TITLE
Add Santa Floki (BEP20)

### PR DESCRIPTION
**Pull request by LogoKing99**
Adding info for BEP20 token 'Santa Floki'.

PR created by <a href="https://assets.trustwallet.com">TW Assets Management</a>

### CODE REVIEW

**Comment by Cryptocool1** [comment]
• What is the purpose of this token? How will it benefit Trust Wallet users?
 • How is the token being distributed? Are you conducting an airdrop?
 • Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?
 • Is the token listed on a centralized/decentralized exchange?
 • Is a Smart Contract audit completed? Where can we find this information?

**Comment by fxukacademy** [comment]
> • What is the purpose of this token? How will it benefit Trust Wallet users? 
Santa Floki is a BSC project that aims to fulfill the needs of its investors by building a good brand, community, and purpose. It is based on the philosophy that those who want to do good should come together and contribute to the less fortunate. It believes in the principles of sharing wealth through passive BUSD income and donating to reputable charities such as Save The Children.

• How is the token being distributed? Are you conducting an airdrop? 
The tokens are distributed by purchasing on pancakeswap. There is no airdrop. 

• Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale? 
The tokens were sold via presale and fairlaunch. 

• Is the token listed on a centralized/decentralized exchange? 
The token is listed on pancakeswap dex. All listing info can be found on tbe coinmarketcap profile page.

• Is a Smart Contract audit completed? Where can we find this information?

Yes the project us fully audited by desertswap. The audit can be accessed from the website or the following link:- https://23eed57b-7b20-4f6c-9749-287d1aecdf43.filesusr.com/ugd/4ebc1f_e354dea06e744e1bb521fba80008e7fb.pdf

**Comment by LogoKing99** [comment]
> • What is the purpose of this token? How will it benefit Trust Wallet users? 
Santa Floki is a BSC project that wants to fulfill the needs of its investors by building a good brand, community, and purpose this holiday season. It is based on the philosophy that those who want to do good should come together and contribute to the less fortunate. It believes in the principles of sharing wealth through passive BUSD income and planning to donate to reputable charities such as Save The Children.

• How is the token being distributed? Are you conducting an airdrop? 
Is being distributed by public sale through pancakeswap. No airdrop is being done.

• Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale? 
Yes, there was a presale

• Is the token listed on a centralized/decentralized exchange? 
the token is listed on Pancakeswap.

• Is a Smart Contract audit completed? Where can we find this information?
Yes the smartcontract is audoted by desertswap and can be viewed via the santafloki website or the following link https://23eed57b-7b20-4f6c-9749-287d1aecdf43.filesusr.com/ugd/4ebc1f_e354dea06e744e1bb521fba80008e7fb.pdf

**Comment by LogoKing99** [comment]
@Cryptocool1

**Comment by LogoKing99** [comment]
@cryptocool1

**Pull request merged**
