### PR TITLE
added Godzilla token

### PR DESCRIPTION
**Pull request by CoinGodzilla**

### CODE REVIEW

**Comment by cryptomanz** [comment]
Hello,
• What is the purpose of this token? How will it benefit Trust Wallet users?
 • How is the token being distributed? Are you conducting an airdrop?
 • Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?
 • Is the token listed on a centralized/decentralized exchange?
 • Is a Smart Contract audit completed? Where can we find this information?

**Comment by CoinGodzilla** [comment]
• What is the purpose of this token? How will it benefit Trust Wallet users?
It is Godzilla GameFi launchpad DAO token. we are going to luanch on 13th November 2021, and we would like to host an NFT blankbox airdrop with trustwallet
• How is the token being distributed? Are you conducting an airdrop?
Godz was fairlaunched 3 months ago,more than 16000 holder now
• Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?
no
• Is the token listed on a centralized/decentralized exchange?
listed on pancakeswap
• Is a Smart Contract audit completed? Where can we find this information?
An audit report will be ready before 9th November 2021

**Comment by Cryptocool1** [comment]
awaiting for smart contract audit, on hold for now

**Comment by CoinGodzilla** [comment]
smart-contract audit:
https://github.com/CoinGodzilla/litepaper/blob/main/Godzilla_AuditReport_InterFi.pdf

@Cryptocool1 @cryptomanz

**Pull request merged**
