### PR TITLE
add blk info and logo

### PR DESCRIPTION
**Pull request by BlkWhale**
BLK is the Governance token on BLK whale ecosystems that users are able to vote on protocol topics such as synthetic asset listings, fee revenue splits, collateral ratio, PAO(New type of IDO for new and existing projects), Social NFT[SocialFi], various ETF portfolios and other BLK improvement proposals.

### CODE REVIEW

**Comment by BlkWhale** [comment]
b577b1c381f59347198328909a3d3f5
F7D47C8E4D2B4F422650058741B967DA722374C125EEAEF6967DF36C3B8FA595
plz check

**Comment by BlkWhale** [comment]
[image: 3201642411734_.pic_hd.jpg]

TXID : F7D47C8E4D2B4F422650058741B967DA722374C125EEAEF6967DF36C3B8FA595


we paid yesterday !


Thank you




2022년 1월 17일 (월) 오후 5:26, merge-fee-bot[bot] ***@***.***>님이
작성:

**Comment by cryptomanz** [comment]
• What is the purpose of this token? How will it benefit Trust Wallet users?
 • How is the token being distributed? Are you conducting an airdrop?
 • Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?
 • Is the token listed on a centralized/decentralized exchange?
 • Is a Smart Contract audit completed? Where can we find this information?

**Comment by BlkWhale** [comment]
• What is the purpose of this token? How will it benefit Trust Wallet users?

-> *It is a governance token of the BLK Black Whale Defi protocol. Trust
Wallet users have the advantage of being able to easily distinguish the
token from other tokens of the same name by showing the logo of the token
going to it.*

• How is the token being distributed? Are you conducting an airdrop?

-> *T*okens are currently listed on DEXs such as Pancake Swap and DODO, and
will be listed on centralized exchanges soon. There is no airdrop purpose

• Did you sold the tokens at an Initial Coin Offering (ICO) or a token
presale?

-> *There was no ICO, there was a private round and an IDO event on October
27th at $0.03. Now, around $1.90. Such a Huge success from Korea based
project like Terra(LUNA)*

• Is the token listed on a centralized/decentralized exchange?

->*It is currently listed on DEX and is in the process of being listed on
CEX. It is scheduled to be listed this month.*

• Is a Smart Contract audit completed? Where can we find this information?

->






*Known
Sec:https://attest.im/attestation/searchResult?querey=70cee47c4b8247759c9814d686cc4ba1
<https://attest.im/attestation/searchResult?querey=70cee47c4b8247759c9814d686cc4ba1>Certik:https://www.certik.com/projects/blk-whale
<https://www.certik.com/projects/blk-whale>We have been audited by two
auditing agencies, "Known Sec" has been audited, and "Certik" is
ongoing.*See links above*

Thank you.

-Team BLKwhale -



2022년 1월 17일 (월) 오후 6:07, Nazar ***@***.***>님이 작성:

**Comment by cryptomanz** [comment]
Please send your audit in pdf format.

**Comment by Cryptocool1** [comment]
please send your audit here

**Comment by BlkWhale** [comment]
2022년 1월 18일 (화) 오전 2:08, CryptoA ***@***.***>님이 작성:

**Comment by Cryptocool1** [comment]
please create new PR when you will be ready to send your audit. When creating new PR make sure to mention this one, so the fee can be reused.

**Comment by BlkWhale** [comment]
Audit Report !


2022년 1월 19일 (수) 오전 6:29, CryptoA ***@***.***>님이 작성:

**Comment by BlkWhale** [comment]
Is any updated?
How long does it take to upload our token logo ?

2022년 1월 19일 (수) 오후 4:22, bit furi ***@***.***>님이 작성:

**Comment by BlkWhale** [comment]
Hi, This is team BLKwhale.
After all the process has been completed including the payment. We have not
received any updated news from your side. Do you think when our ticker and
project information will be updated on your wallet ?

Thank you so much

- BEST REGARDS
Team BLK whale




2022년 1월 24일 (월) 오전 4:35, bit furi ***@***.***>님이 작성:

**Comment by Cryptocool1** [comment]
You did not send the audit

**Comment by Cryptocool1** [comment]
Where did you pay the fee?

**Comment by BlkWhale** [comment]
Please check the attached file .
Thank you

2022년 1월 27일 (목) 오전 3:17, CryptoA ***@***.***>님이 작성:

**Comment by Cryptocool1** [comment]
You did not attach the file.

**Comment by BlkWhale** [comment]
Please check the attached file again !

Thank you


2022년 1월 27일 (목) 오전 3:23, CryptoA ***@***.***>님이 작성:

**Comment by Cryptocool1** [comment]
C4434744-9F37-4440-B1CA-84F7FDA13A00

**Comment by BlkWhale** [comment]
Please check the link :

https://drive.google.com/file/d/1LGMrPFUiM1pVR42tvbAibGVsKcYclYhv/view?usp=sharing



2022년 1월 27일 (목) 오전 3:32, CryptoA ***@***.***>님이 작성:

**Pull request merged**
