### PR TITLE
Create ETHEREUM TOKEN

### PR DESCRIPTION
**Pull request by ferrocker**
please check again my request, 
Name: ETHEREUMtoken
Acronym: ETHt
Contract ID: 0x8266897d3044a030f1fca81f18c9ad2daf9e5f09

### CODE REVIEW

**Comment by zachzwei** [comment]
Please follow the guidelines for token submissions.
Learn more here:
https://community.trustwallet.com/t/how-to-submit-a-new-token-asset/3863/2

**Comment by ferrocker** [comment]
You guys have a lot of rules and those requirements and the way we have to
submit it makes more complicated everything!!! Why we just don't send the
logo by email and we send the payment to your wallet address!!!! And it's
not a contribution like you guys say, it's a payment or fees

**Comment by ferrocker** [comment]
please check again my request

**Comment by ferrocker** [comment]
> Please follow the guidelines for token submissions.
> Learn more here:
> https://community.trustwallet.com/t/how-to-submit-a-new-token-asset/3863/2

check it again and let me know when you guys can add our logo

**Comment by ferrocker** [comment]
Check my logo request, what else do you need?

**Comment by catenocrypt** [comment]
Please check the guide in the README.md file of the repository.
For start, the logo should be included as a file in the PR, at the right location, with the right parameters, not in the description of the pull request.

**Pull request closed without merging**
