### PR TITLE
Logo Update, please Sir last time

### PR DESCRIPTION
**Pull request by BlackBiT1**
Logo Update, please Sir last time
0xd47774f8c580c3ebb7c81323f62a1d5c1eecb232 logo

### CODE REVIEW

**Comment by kolya182** [comment]
This is last time i review your PR, if you don't follow guidelines you get banned for lifetime

**Comment by BlackBiT1** [comment]
Thank you Sir, ❤️

**Comment by BlackBiT1** [comment]
This time update sir, and will not be wrong sir🙏🙏🙏

**Comment by BlackBiT1** [comment]
> This is last time i review your PR, if you don't follow guidelines you get banned for lifetime

This time update sir, and will not be wrong sir🙏🙏🙏
0xd47774f8c580c3ebb7c81323f62a1d5c1eecb232 logo

**Pull request merged**
