### PR TITLE
Cheecoin adding trust wallet logo and json

### PR DESCRIPTION
**Pull request by cheecoin**
We have added out 256x256 logo for trust wallet as well as the needed .json file. Thank you.

### CODE REVIEW

**Comment by Cryptocool1** [comment]
Info.json is incorrect. It should be of the form:
{
    "name": "Trust Wallet Token",
    "type": "ERC20",
    "symbol": "TWT",
    "decimals": 8,
    "description": "Utility token to increase adoption of cryptocurrency.",
    "website": "https://trustwallet.com",
    "explorer": "https://explorer.binance.org/asset/TWT-8C2",
    "status": "active",
    "id": "TWT-8C2"
}
Please follow documentation: https://community.trustwallet.com/t/how-to-submit-a-token-logo/3863

**Comment by cheecoin** [comment]
Ok thank you

**Comment by cheecoin** [comment]
How do I pay?

**Comment by Cryptocool1** [comment]
> How do I pay?
> […](#)

Please pay 250 TWT with the memo 7998 to the address bnb1tqq9llyr3dyjd559dha6z5r5etk3qfwk07m098.
Alternatively, 2 BNB is also accepted (same memo & address).

**Comment by cheecoin** [comment]
Thanks

**Comment by cheecoin** [comment]
image
 Paid

**Comment by cheecoin** [comment]
Paid [image: image.png]

**Comment by cheecoin** [comment]
Thanks!

**Comment by cheecoin** [comment]
Thanks. Does that mean the logo is active?

**Comment by cheecoin** [comment]
Also the price seems to not be correct. Is there a reason for that?

**Pull request merged**
