### PR TITLE
Adding SILVA

### PR DESCRIPTION
**Pull request by SilvaToken**
SILVA Token is a unique service that allows individuals to make payments from the comfort of their home in fiat currencies or crypto-currencies, to multiple online and offline stores.

SILVA Token is a multi-functional platform which allows each participant to keep money in a multi-currency online wallet, buy and sell currency on the exchange, invest money, get a huge benefit in a convenient currency.

### CODE REVIEW

**Comment by SilvaToken** [comment]
Dear,

payment has been paid, but at that time our holders are lacking

twt

Thanks
Team Dev SILVA

**Comment by SilvaToken** [comment]
Dear,

payment has been paid, but at that time our holders are lacking

TxHash/TxID :

68B3971372C2E287DD752B487EF3B6BD700C99E69FFD8D7BAF6A6E7F9DBBDE63

https://explorer.binance.org/tx/68B3971372C2E287DD752B487EF3B6BD700C99E69FFD8D7BAF6A6E7F9DBBDE63

Token Name : Silva Token
Contract BEB20 : 0x68b5edb385b59e30a7a7db1e681a449e94df0213

Thanks
Team Dev SILVA

twt

**Comment by SilvaToken** [comment]
Dear,..

do I have to pay again or can I use the old payment?

Please confirm

Thanks
Team Dev SILVA Token

**Comment by SilvaToken** [comment]
Dear @zachzwei, @Iamdeadlyz, @Cryptocool1, @cryptomanz,..

do I have to pay again or can I use the old payment?

Please confirm

Thanks
Team Dev SILVA Token

**Comment by Cryptocool1** [comment]
In what PR you paid?

**Comment by SilvaToken** [comment]
Dear @Cryptocool1   

This Address and memo in email, please check in attachment

Please confirm

Thanks
Team Dev SILVA Token

tw-email

**Comment by SilvaToken** [comment]
Dear @zachzwei, @Iamdeadlyz, @Cryptocool1, @cryptomanz,..

update

email-2
tw-email
twt

**Comment by SilvaToken** [comment]
what should we do now, for SILVA logo show on Trustwallet ?

**Pull request merged**
