### PR TITLE
Add swapx.launchzone.org.png and poolx.launchzone.org.png

### PR DESCRIPTION
**Pull request by cryptofield**

### CODE REVIEW

**Comment by catenocrypt** [comment]
Submission is OK; awaiting fee payment.

**Comment by cryptofield** [comment]
Dear @catenocrypt,

Thank you so much for merging our pull request
May we know when our DApps (swapx and poolx) display on Trust Wallet?

**Comment by catenocrypt** [comment]
Please see
https://developer.trustwallet.com/listing-guide
I think you need to fill out a form

**Comment by cryptofield** [comment]
Noted  with many thanks,

We already submit applications forms for SwapX and PoolX

> Please see
> https://developer.trustwallet.com/listing-guide
> I think you need to fill out a form

**Pull request merged**
