### PR TITLE
Add Chihua token (BEP20)

### PR DESCRIPTION
**Pull request by vovanushka**
This PR is being closed due to inactivity. If you wish to continue, please have us reopen the PR before sending your payment, or just create a new one.
Do NOT send payments for closed PR, as the fee may by lost!
  (48 vs. 48 hrs)

### CODE REVIEW

**Comment by vovanushka** [comment]
Could you please reopen the PR, fee was sent with 9038

**Comment by vovanushka** [comment]
This is a tx for this PR
https://explorer.binance.org/tx/765A6691E88FD1223D34B9B3672710FD2B380C47290892D65EF796FD4011898D

**Comment by Cryptocool1** [comment]
As per our policy, brand new tokens are not included, there is a minimum requirement of 2500 holder addresses and 5000 transactions, in order to filter out scam tokens.
See the criteria at (mentioned in the first message by the bot): https://community.trustwallet.com/t/how-to-submit-a-token-logo/3863).

**Comment by vovanushka** [comment]
@Cryptocool1 they have  enough of holders at eth

**Comment by vovanushka** [comment]
for eth logo PR was successful merged
https://github.com/trustwallet/assets/pull/8757

**Comment by vovanushka** [comment]
thanks!

**Pull request merged**
