### PR TITLE
Add My Defi Legends Logo and Info

### PR DESCRIPTION
**Pull request by MyDefiLegendsOfficial**
Add My Defi Legends Logo and Info

### CODE REVIEW

**Comment by MyDefiLegendsOfficial** [comment]
Payment Sent

**Comment by cryptomanz** [comment]
Hello,
• What is the purpose of this token? How will it benefit Trust Wallet users?
 • How is the token being distributed? Are you conducting an airdrop?
 • Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?
 • Is the token listed on a centralized/decentralized exchange?
 • Is a Smart Contract audit completed? Where can we find this information?

**Comment by MyDefiLegendsOfficial** [comment]
• What is the purpose of this token? How will it benefit Trust Wallet users?
My Defi Legends is a complete metaverse of Digital Heroes that live on the Binance Smart Chain (BSC), which allows millions of people to join the NFT & blockchain-based gaming world in an easy, creative and fun way.

• How is the token being distributed? Are you conducting an airdrop?
Pre-Sale/ No Airdrop / Launch
Dev Wallet 3-5%
Game Wallet 10-20%
Liquidity 30-40%
Presale20%
Burn 20%

• Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?
ICO:
1 BNB = 400,000 Tokens / Launch Price 1 BNB = 350,000

• Is the token listed on a centralized/decentralized exchange?
Yes,
https://nomics.com/assets/dlegends-my-defi-legends
https://poocoin.app/tokens/0x88c55b3255ae1e6628c953c5cdff27ad3cc33c81
https://pancakeswap.finance/swap#/swap?outputCurrency=0x88c55b3255ae1e6628c953c5cdff27ad3cc33c81

• Is a Smart Contract audit completed? Where can we find this information?
No the Audit is being processed by Certik and We have Conversation Between Email and Telegram

**Comment by Cryptocool1** [comment]
will wait a smart contract audit.
on hold for now

**Comment by MyDefiLegendsOfficial** [comment]
> will wait for a smart contract audit.
> on hold for now

Hi can we submit other audit like Tech-Audit or TechRate Audit aside from Certik

**Comment by MyDefiLegendsOfficial** [comment]
hi we already passed tha audit from tech-audit.org 
[TECHAUDIT_MY-DEFI-LEGENDS.pdf](https://github.com/trustwallet/assets/files/7019702/TECHAUDIT_MY-DEFI-LEGENDS.pdf)

**Comment by MyDefiLegendsOfficial** [comment]
> will wait for a smart contract audit.
> on hold for now

hi we already passed tha audit from tech-audit.org
TECHAUDIT_MY-DEFI-LEGENDS.pdf

**Comment by Cryptocool1** [comment]
can you please add links to your PR?
example: https://developer.trustwallet.com/add_new_asset#info-json-contents

**Review by MyDefiLegendsOfficial — COMMENTED** [review]
OUR AUDIT

[TECHAUDIT_MY-DEFI-LEGENDS.pdf](https://github.com/trustwallet/assets/files/7024786/TECHAUDIT_MY-DEFI-LEGENDS.pdf)

**Comment by MyDefiLegendsOfficial** [comment]
https://github.com/MyDefiLegendsOfficial/Audit

**Comment by Cryptocool1** [comment]
can you please add links to your PR?
example: https://developer.trustwallet.com/add_new_asset#info-json-contents

**Comment by MyDefiLegendsOfficial** [comment]
hi what do you mean

**Comment by Cryptocool1** [comment]
here you can find how to add the links : https://developer.trustwallet.com/add_new_asset/repository_details

**Comment by MyDefiLegendsOfficial** [comment]
https://github.com/MyDefiLegendsOfficial/assets/pull/1

**Comment by MyDefiLegendsOfficial** [comment]
hi i tried to upload the links this what happen should i continue it
PR Summary
Files OK, 2Files in PR: 2
Token in PR: BEP20 0x88c55B3255aE1e6628C953C5CDfF27Ad3Cc33C81
Could not retrieve info file; MyDefiLegendsOfficial/assets/master 0x88c55B3255aE1e6628C953C5CDfF27Ad3Cc33C81, SyntaxError: Unexpected string in JSON at position 562

**Pull request merged**
