### PR TITLE
Add Bullex Information and Logo

### PR DESCRIPTION
**Pull request by BSCGuru**
Add Bullex Information and Logo

### CODE REVIEW

**Comment by BullexTeam** [comment]
https://explorer.binance.org/tx/CD71993C1DCFFA7277AE5DD94D2877E1300B24D0A5B4430C81B7307B740C6CF5

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐

**Comment by Cryptocool1** [comment]
hello,
• What is the purpose of this token? How will it benefit Trust Wallet users?
 • How is the token being distributed? Are you conducting an airdrop?
 • Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?
 • Is the token listed on a centralized/decentralized exchange?
 • Is a Smart Contract audit completed? Where can we find this information?

**Comment by BullexTeam** [comment]
hello,
• What is the purpose of this token? How will it benefit Trust Wallet users?BNB Rewards token, also we are developing dapps such as bullex chart, our community is constantly growing. It will definitely benefit to have a logo as there are many fakes out there in BSC. It will add legitimacy.
• How is the token being distributed? Are you conducting an airdrop?We are already launched on pancakeswap. A private sale was conducted where up to 2558 BNB was conducted over 2 rounds.
• Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?It was sold via token presale on bullextoken.com
• Is the token listed on a centralized/decentralized exchange?We are listed on pancakeswap. We are also found in cmc and coingecko. https://coinmarketcap.com/currencies/bullex/
https://www.coingecko.com/en/coins/bullex
• Is a Smart Contract audit completed? Where can we find this information?Techrate audit is currently being processed.

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐

**Comment by cryptomanz** [comment]
- can you please add links to your PR?
example: https://developer.trustwallet.com/add_new_asset#info-json-contents

**Comment by BullexTeam** [comment]
Done, i have added the links with socials and coingecko and coinmarketcap.

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐

**Pull request merged**
