### PR TITLE
Add gDogecoin token

### PR DESCRIPTION
**Pull request by Niklam88**
Add gDogecoin info & logo

### CODE REVIEW

**Comment by Niklam88** [comment]
done all

**Comment by Cryptocool1** [comment]
> done all

Hello,
I need you to answer some questions
- What is the purpose of the token?
- What are the token economics for the token?

**Comment by Niklam88** [comment]
> > done all
> 
> Hello,
> I need you to answer some questions
> 
> * What is the purpose of the token?
> * What are the token economics for the token?

gDogecoin  it's a token will  be used as pay out token for our yield farming and staking platform for generating returns from long-term holdings exactly like staking in pancakeswap and you earn cake.

Total Supply: 1,000,000,000,000,000 gDOGE  60% will be burned once the token listed in exchanges 5% of the token will be used for marking and partners 10% pre-sell and 2% for the team. Liquidity will be locked for one year.

**Comment by Niklam88** [comment]
Why still on hold ?

**Comment by zachzwei** [comment]
> Why still on hold ?

Please review criteria mentioned above.
This token will remain on hold until verified to be a legit project.

**Comment by varunsridharan** [comment]
@all this project is a scam. please dont approve it.

**Review by ny030897 — APPROVED** [review]

**Review by ny030897 — APPROVED** [review]

**Comment by Cryptocool1** [comment]
please create new PR when your token will be listed on CMC
make sure to mention this PR so that fee can can be reused

**Pull request closed without merging**
