### PR TITLE
Add Natronz (BEP20)

### PR DESCRIPTION
**Pull request by erience**
Adding info for BEP20 token 'Natronz'.

Instagram Link: https://www.instagram.com/natronzofficial/
Audit Report Link: https://natronz.com/assets/files/audit.pdf

### CODE REVIEW

**Comment by cryptomanz1** [comment]
• What is the purpose of this token? How will it benefit Trust Wallet users?
 • How is the token being distributed? Are you conducting an airdrop?
 • Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?
 • Is the token listed on a centralized/decentralized exchange?
 • Is a Smart Contract audit completed? Where can we find this information?

**Comment by erience** [comment]
• What is the purpose of this token? How will it benefit Trust Wallet users? --- This Token is part of Natronz Ecosystem. Currently the Natronz Chat is Live on Google Play Store/ Apple Store. It's a decentralised Chat App with Payment Utility like Venmo. 

• How is the token being distributed? Are you conducting an airdrop? --- No, Airdrop is done. Token can be purchased/ exchange inside the Chat App and can be sent for Micro Payments amongst users. Just like Venmo.

• Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale? -- No

• Is the token listed on a centralized/decentralized exchange? --- Yes the Token is listed on Pancakeswap at the Moment.

• Is a Smart Contract audit completed? Where can we find this information --- Yes, Smart Contract is Audited. The Audit Report Link is provided in the Submission

**Comment by Cryptocool1** [comment]
Please send your smart contract audit not in PDF format.

**Comment by erience** [comment]
@Cryptocool1 Audit Report Link: https://natronz.com/assets/files/audit.pdf

**Pull request merged**
