### PR TITLE
adding TWT

### PR DESCRIPTION
**Pull request by krimim2020**
Thankyou sir!!

### CODE REVIEW

**Comment by Cryptocool1** [comment]
Correction needed: Logo file should be named logo.png exactly, please rename!

**Comment by krimim2020** [comment]
> Correction needed: Logo file should be named logo.png exactly, please rename!

I want to know info.json , logo.png
Is it ok?

**Comment by Cryptocool1** [comment]
> > Correction needed: Logo file should be named logo.png exactly, please rename!
> 
> I want to know info.json , logo.png
> Is it ok?

PR should include only 2 files:
blockchains/smartchain/assets/0x31de61d9a39cb9f479570bd3dc3ac93bc0402cdb/info.json
blockchains/smartchain/assets/0x31de61d9a39cb9f479570bd3dc3ac93bc0402cdb/logo.png

**Comment by Cryptocool1** [comment]
Your contract should be in checksum format 0x31DE61D9a39CB9f479570Bd3dC3AC93BC0402CDB

**Comment by Cryptocool1** [comment]
If you can't rename files in the PR, you may open a new PR. 
You may try this app https://assets.trustwallet.com

**Pull request closed without merging**
