### PR TITLE
update Netcoincapital smartcontract

### PR DESCRIPTION
**Pull request by netcoincapital**
Hello
this is netcoincapital CEO
we update our smartcontract to the new smart contract
this is old contract address:
TWmocwvHpui48QXUVJeW2SvcFe8LyNgLCU
and this is the new contract address:
TCDgp5bwtixaShPifUm7HpZ71C1pe6zif1

please delete old contract folder (TWmocwvHpui48QXUVJeW2SvcFe8LyNgLCU) and add the newest

### CODE REVIEW

**Comment by netcoincapital** [comment]
296D24D1BA3203B673E7C33884FC806D444E0C9C6F6CF5D5728BDFEA6BF15A78

payment hash

**Comment by cryptomanz** [comment]
Logo should be less than 100KB, given 113KB. Please change.

**Comment by netcoincapital** [comment]
logo png
90KB logo

**Comment by netcoincapital** [comment]
i change the logo to 90KB

**Comment by netcoincapital** [comment]
and please delete this folder from trons assets 
TWmocwvHpui48QXUVJeW2SvcFe8LyNgLCU
this is our old contract we don't need that

**Comment by netcoincapital** [comment]
Hello team i need to change our token details on trustwallet

**Pull request merged**
