### PR TITLE
lom logo

### PR DESCRIPTION
**Pull request by ltconlinemarkets**

### CODE REVIEW

**Comment by ltconlinemarkets** [comment]
logo

**Comment by ltconlinemarkets** [comment]
Hlw sir please add my logo

**Comment by kolya182** [comment]
Already adde, please do not create duplicate PR's #shitcoin

**Comment by ltconlinemarkets** [comment]
0xa28278ab00105183c5c740a225e63168ccaf10e3 logo

**Comment by catenocrypt** [comment]
@ltconlinemarkets , what's your intent with this logo here?  This PR is already closed.

**Pull request closed without merging**
