### PR TITLE
Uploading logo and information in JSON format to the XMINE Token.

### PR DESCRIPTION
**Pull request by cksdv**
Request for uploading logo and information in JSON format for the XMINE Token.

### CODE REVIEW

**Comment by Cryptocool1** [comment]
can you please add links to your PR?
example: https://developer.trustwallet.com/add_new_asset/repository_details

**Comment by cksdv** [comment]
> can you please add links to your PR? example: https://developer.trustwallet.com/add_new_asset/repository_details

it's saying that this page was not found, I put the links inside das info.json, where else should I put it?

**Comment by cryptomanz** [comment]
> > can you please add links to your PR? example: https://developer.trustwallet.com/add_new_asset/repository_details
> 
> it's saying that this page was not found, I put the links inside das info.json, where else should I put it?
Screenshot 2021-10-06 at 20 22 37

**Comment by Cryptocool1** [comment]
• What is the purpose of this token? How will it benefit Trust Wallet users?
 • How is the token being distributed? Are you conducting an airdrop?
 • Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?
 • Is the token listed on a centralized/decentralized exchange?
 • Is a Smart Contract audit completed? Where can we find this information?

**Pull request merged**
