### PR TITLE
Add Jasan Wellness (BEP20)

### PR DESCRIPTION
**Pull request by PankajTMB**
Adding info for BEP20 token 'Jasan Wellness'.

PR created by <a href="https://assets.trustwallet.com">TW Assets Management</a>

### CODE REVIEW

**Comment by Cryptocool1** [comment]
• Is a Smart Contract audit completed? Where can we find this information?

**Comment by PankajTMB** [comment]
@Cryptocool1 

Here is Smart Contract audit.

https://stakejw.online/jw-audit.pdf

**Comment by Cryptocool1** [comment]
> @Cryptocool1
> 
> Here is Smart Contract audit.
> 
> https://stakejw.online/jw-audit.pdf

hello, I cannot find your audit on official Techrate website. Can you send me the link?

**Comment by Nanimustshine** [comment]
> > @Cryptocool1
> > 
> > Here is Smart Contract audit.
> > 
> > https://stakejw.online/jw-audit.pdf
> 
> hello, I cannot find your audit on official Techrate website. Can you send me the link?

Kindly file a support ticket for this concern below
https://forms.gle/KAqYDCGHb1UP4K8e7

**Comment by Nanimustshine** [comment]
>  • Is a Smart Contract audit completed? Where can we find this information?

Kindly file a support ticket for this concern below
https://forms.gle/KAqYDCGHb1UP4K8e7

**Review by Fuad369 — COMMENTED** [review]
انا اوافق

**Review by Fuad369 — COMMENTED** [review]
انا اوافق

**Review by Fuad369 — COMMENTED** [review]
انا اوافق

**Comment by Cryptocool1** [comment]
Please come back to us once you ready to send audit from official website. Make sure to mention this PR so the fee can be reused

**Pull request closed without merging**
