### PR TITLE
Add new KODA V2 coin to TrustWallet

### PR DESCRIPTION
**Pull request by AndreiRStatescu**
Koda has recently migrated from V1 to V2. 
V1 was located at the following address: 0x9E993671976a5AC51bBfB3Db9E34eAC8d518fe82

### CODE REVIEW

**Comment by Cryptocool1** [comment]
could you add the links?
see the example here: https://developer.trustwallet.com/assets/repository_details

**Comment by Cryptocool1** [comment]
can you send an official announcement about migration ?

**Comment by AndreiRStatescu** [comment]
Here is the migration guide: https://koda.finance/migration-to-v2-hashex-audit/
Will get back with the links as well soon

**Comment by AndreiRStatescu** [comment]
Hi @Cryptocool1 I have added the links, as you requested. It seems like the validation is still failing, but the URLs seem to match so I can't tell the reason. Could you kindly guide us a bit on this? Thanks!

**Comment by Cryptocool1** [comment]
https://github.com/trustwallet/assets/pull/16697
old contract is abandoned

**Comment by Cryptocool1** [comment]
your coingecko links should be "https://coingecko.com/coins/koda-cryptocurrency", not "https://coingecko.com/en/coins/koda-cryptocurrency"

**Comment by AndreiRStatescu** [comment]
@Cryptocool1 thanks for the tip. And yeah, the old contract is abandoned, not used anymore. Anything else I can help with? Thanks

**Pull request merged**
