### PR TITLE
Add SpookyShiba (BEP20)

### PR DESCRIPTION
**Pull request by wrennstigator**
Adding info for BEP20 token 'SpookyShiba'.

PR created by <a href="https://assets.trustwallet.com">TW Assets Management</a>

### CODE REVIEW

**Comment by Cryptocool1** [comment]
As per our policy, brand new tokens are not included, there is a minimum requirement of 10,000 holder addresses and 15,000 transactions, in order to filter out scam tokens.
See the criteria at : https://developer.trustwallet.com/assets/requirements .

**Comment by wrennstigator** [comment]
sir. this is a migration from old token SpookyShiba to new token address this is from a verified telegram as well. Link to the messsage - https://t.me/SpookyShibaOfficial/484264

check here for our verified social medias confirming this info. - https://bscscan.com/token/0xed74Bc5DC139356E08dE28143996F5eF6e4334a4

**Comment by wrennstigator** [comment]
it is also in our pinned twitter; twitter.com/shibaspooky

**Comment by Cryptocool1** [comment]
Migration should be mentioned on the bscscan

**Comment by wrennstigator** [comment]
they just updated BSCscan please check now and add :) thank you.

https://bscscan.com/token/0x9c2b1b3780a8b36b695f0b2781668664ac1bf25a

**Comment by wrennstigator** [comment]
anything else needed?

**Comment by cryptomanz** [comment]
#21321

**Comment by wrennstigator** [comment]
there is reports that the price for SPKY is not showing for users on trust wallet. can you please look into this?

**Pull request closed without merging**
