### PR TITLE
Add BHO (BEP20)

### PR DESCRIPTION
**Pull request by naviocean**

### CODE REVIEW

**Comment by Cryptocool1** [comment]
hello,
• What is the purpose of this token? How will it benefit Trust Wallet users?
 • How is the token being distributed? Are you conducting an airdrop?
 • Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?
 • Is the token listed on a centralized/decentralized exchange?
 • Is a Smart Contract audit completed? Where can we find this information?

**Comment by naviocean** [comment]
Hello @Cryptocool1,
Thank you for your questions and here are our answers:

• What is the purpose of this token? 
How will it benefit Trust Wallet users?
Help Trust-wallet users shortlist better projects to be invested on via our Bholdus's fast-growing ecosystem.

• How is the token being distributed? 
https://bholdus.com/blog/article/bholdus-tokenomics-update
Are you conducting an airdrop? 
Not yet

• Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?
Yes, We did. Please check out here https://bholdus.com/blog/article/initial-member-offering-(imo)-event-bholdus-token-bho

• Is the token listed on a centralized/decentralized exchange?
Pancake Swap DEX

• Is a Smart Contract audit completed? Where can we find this information? https://github.com/solidproof/smart-contract-audits/blob/main/SmartContract_Audit_Solidproof_Bholdus.pdf

Please let us know if you need further information.
Duong Le

**Comment by cryptomanz** [comment]
Hello,
Your logo is large, please follow rules add tokens,
Exemple:
Screenshot 2021-09-25 at 22 03 39

**Comment by naviocean** [comment]
Hi @cryptomanz, I've resized the logo to 256x256 as you request. Plz check again, thank you.

**Pull request merged**
