### PR TITLE
Adding $XCUR logo

### PR DESCRIPTION
**Pull request by TheOneXi**
This PR is being closed due to inactivity. If you wish to continue, please have us reopen the PR before sending your payment.
Do NOT send payments for closed PR, as the fee may by lost!
  (173 vs. 60 hrs)

### CODE REVIEW

**Comment by curateproject** [comment]
Why did it fail?

**Comment by curateproject** [comment]
I see,

However my token already has a logo/price on TrustSwap for ERC20, my token
XCUR has bridged to BEP2 so shouldn't it show up automatically for BEP2 as
well?

Thanks!

**Comment by catenocrypt** [comment]
This token (ID XCUR) does not exist on Binance chain.  Closing.

https://explorer.binance.org/asset/XCUR

**Comment by curateproject** [comment]
Hi Adam,

We're on BSC:

https://bscscan.com/token/0x708c671aa997da536869b50b6c67fa0c32ce80b2

**Comment by catenocrypt** [comment]
Circulation requirement does not apply to change of existing logo, my mistake, sorry.  But PR fee is still needed.
Reopening.

**Comment by catenocrypt** [comment]
Error from the check build shows that the Binance token does not exists.  I think the ID is not complete, it should be of the form XCUR-xxxx.  Please correct.

```
XXX 'Binance chain; assets must exist on chain':  1 errors
   XXX   'Asset XCUR missing on chain'
   Action 'Cosmos chain' has 1 check steps
```

**Comment by catenocrypt** [comment]
If on BSC, token ID should be hex string (like for ETH).  Folder should be `blockchains/smartchain/assets`.
If not on binance, files from under `blockchains/binance/assets` should be removed.
For the ETH, logo should be called `logo.png` exactly.

**Comment by curateproject** [comment]
Hi how do I find my hex string?

Our token is an ERC20 but it's been bridged to BEP2 but I'm not sure how to
find out the hex string for the folder.

Here's our link on BSC:

https://info.julswap.com/pair/0xcd3fb2e793cb72c06cc4b389c1c7a1a0201efca7

Can you help?

**Comment by catenocrypt** [comment]
Token ID is a basic info obtained when the token contract was created.  Sorry, I cannot help with that, and this should not be an issue in a project.

**Comment by curateproject** [comment]
Hi Adam,

It's not an issue and I have the BNB to send if it's required.

Can you tell me what information you require on our smart contract?

Kind regards,
James

**Comment by catenocrypt** [comment]
You have included two logos:

- blockchains/ethereum/assets/0xE1c7E30C42C24582888C758984f6e382096786bd/256x256.png
Here chain is Ethereum, and tokenID is 0xE1c7E30C42C24582888C758984f6e382096786bd, which is fine, this token exists, with over 3300 holders
https://etherscan.io/token/0xE1c7E30C42C24582888C758984f6e382096786bd

- blockchains/binance/assets/XCUR/logo.png
Here chain is Binance (not BSC, BEP2), and tokenID is `XCUR`.  But there is no token with this tokenID!  TokenIDs on Binance chain are of the form `ETH-1C9`.  
As I understood, you token is in fact not a BEP2 token, but a BEP20 token, and chain is Binance SMART Chain.

So I need the BEP20 tokenID of your token.

Or, we can just remove the binance version completely.

**Comment by curateproject** [comment]
Thanks Adam for explaining.

Yes, XCUR is on BEP-20 (BSC) not BEP2 and is not on binance.

Here is our BSC explorer link:

https://bscscan.com/token/0x708c671aa997da536869b50b6c67fa0c32ce80b2

Here is the BEP-20 smart contract:

0x708c671aa997da536869b50b6c67fa0c32ce80b2

Attached is our logo.

Thanks,
James

**Comment by curateproject** [comment]
Hi Adam any update on this?

**Comment by catenocrypt** [comment]
I suggest to create a new PR.
Create a new PR with:
- logo: file should be called `logo.png`, under `blockchains/ethereum/assets/0xE1c7E30C42C24582888C758984f6e382096786bd/logo.png`
- info.json: should be in the same folder, `blockchains/ethereum/assets/0xE1c7E30C42C24582888C758984f6e382096786bd/info.json`
- content should be something like this:

```json
{
    "name": "Curate",
    "type": "BEP20",
    "symbol": "XCUR",
    "decimals": 8,
    "description": "<Fill in with a few sentence description>",
    "website": "<Fill in with project website>",
    "explorer": "https://bscscan.com/token/0x708c671aa997da536869b50b6c67fa0c32ce80b2",
    "status": "active",
    "id": "0x708C671Aa997da536869B50B6C67FA0C32Ce80B2"
}
```

**Pull request closed without merging**
