### PR TITLE
Add logo wbst

### PR DESCRIPTION
**Pull request by ghost**

### CODE REVIEW

**Comment by Cryptocool1** [comment]
6030 paid

**Comment by kindcowfinance** [comment]
its correct , website 
https://token.bitsten.com 

now is online

**Comment by Cryptocool1** [comment]
> its correct , website
> https://token.bitsten.com
> 
> now is online

you probably need to change website in your info.json to https://token.bitsten.com/

**Comment by kindcowfinance** [comment]
> > its correct , website
> > https://token.bitsten.com
> > now is online
> 
> you probably need to change website in your info.json to https://token.bitsten.com/

This is our json file
{
    "name": "Wraped BST",
    "website": "https://token.bitsten.com",
    "description": "BST is a token utility used to change transaction fees and listing fees on bitsten exchange.",
    "explorer": "https://bscscan.com/token/0x58d6f302aaF33DD30A7666E16909DB3C5C74021b",
    "type": "BEP20",
    "symbol": "WBST",
    "decimals": 18,
    "status": "active",
    "id": "0x58d6f302aaF33DD30A7666E16909DB3C5C74021b"
}


What wrong , i think all is corect , please help

**Comment by gihankanishka** [comment]
this contract address is not updated in official website and official website says its a ERC20 token so is this a token pretending to be that original token

**Pull request merged**
