### PR TITLE
Darphane $Chat Token Integration

### PR DESCRIPTION
**Pull request by ersanyakit**
Maximum PR age reached, auto-closing PR  (60 vs. 60 hrs)

### CODE REVIEW

**Comment by ersanyakit** [comment]
Omg, its very interesting idea. I never seen before... :)

**Comment by kolya182** [comment]
@ersanyakit PR ready to get merged, you just need to pay the fee.

**Comment by PendelinP** [comment]
@kolya182 Why don't you simply support ETH payments? Your token is only listen on suspect/minor exchanges and BNB is a bit weird as well. I really don't get it why you make things so complicated?

**Comment by vikmeup** [comment]
@PendelinP ETH is little trickier to implement, as it will require to create separate addresses for each pull request, much harder to manage and sweep funds into one wallet after.

**Comment by PendelinP** [comment]
@vikmeup Thanks for the clarification. Would be great to have some more coins/some easier way to get this done :)

**Comment by ersanyakit** [comment]
@kolya182 is there anyway to send ETH payments for this PR?

If its possible can u share with me your ETH address

Best Regards.

**Pull request closed without merging**
