### PR TITLE
SHAB update infos TW

### PR DESCRIPTION
**Pull request by sharpeishab**
Please update ASAP

### CODE REVIEW

**Comment by Cryptocool1** [comment]
Info.json is incorrect. It should be of the form:
{
    "name": "Trust Wallet Token",
    "type": "ERC20",
    "symbol": "TWT",
    "decimals": 8,
    "description": "Utility token to increase adoption of cryptocurrency.",
    "website": "https://trustwallet.com",
    "explorer": "https://explorer.binance.org/asset/TWT-8C2",
    "status": "active",
    "id": "TWT-8C2"
}
Please follow documentation: https://community.trustwallet.com/t/how-to-submit-a-token-logo/3863

**Comment by sharpeishab** [comment]
{
"name": “SHAB Token” ,
"type": “BEP20",
"symbol": “SHAB”,
"decimals": 18,
"description": "SHAB was founded by Doge army and SHIB army etc. SHAB community is decentralized. Creators of SHAB expect that SHAB community take power autonomously.
The total supply of SHAB is 1,000,000,000,000,000, with no pre-sale, no team reservation. The private key has been threw away thoroughly. ",
"website": "https://sharpei.network",
"explorer": "https://www.bscscan.com/token/0x762a68697D7c8A0078Bd1d79BD50d0F2ef8A8AaF",
"status": "active",
"id": "0x762a68697D7c8A0078Bd1d79BD50d0F2ef8A8AaF"
}

**Comment by Cryptocool1** [comment]
> {
> "name": “SHAB Token” ,
> "type": “BEP20",
> "symbol": “SHAB”,
> "decimals": 18,
> "description": "SHAB was founded by Doge army and SHIB army etc. SHAB community is decentralized. Creators of SHAB expect that SHAB community take power autonomously.
> The total supply of SHAB is 1,000,000,000,000,000, with no pre-sale, no team reservation. The private key has been threw away thoroughly. ",
> "website": "https://sharpei.network",
> "explorer": "https://www.bscscan.com/token/0x762a68697D7c8A0078Bd1d79BD50d0F2ef8A8AaF",
> "status": "active",
> "id": "0x762a68697D7c8A0078Bd1d79BD50d0F2ef8A8AaF"
> }

you need to add this into you info.json

**Comment by cryptomanz** [comment]
Hello,
- This is a BEp20 token, correct folder is blockchains/smartchain/assets.
- Please create new PR, follow doc https://community.trustwallet.com/t/how-to-submit-a-token-logo/3863
You may want to try our new Assets app in beta; go to https://assets.trustwallet.com, log on with Github, enter contract ID, logo and some additional info, and it will create a PR for you.
See https://community.trustwallet.com/t/how-to-submit-a-token-logo-using-assets-app/82957.
- When creating new PR, mention this PR, so that fee can be reused, and not paid again.

**Review by magneticmeganlovesjhonny — COMMENTED** [review]
Updated

**Pull request closed without merging**
