### PR TITLE
Added ADA BOY token.

### PR DESCRIPTION
**Pull request by RealADABoy**
Add ADA BOY bsc token: https://poocoin.app/tokens/0x1e653794a6849bc8a78be50c4d48981afad6359d

### CODE REVIEW

**Comment by RealADABoy** [comment]
https://explorer.binance.org/tx/9B7F9EE992D5512F03720B308ECCAE0C3292CCFAC80C1255C7EB90FE402A8B50

1000 TWT transfer.

**Comment by Cryptocool1** [comment]
• What is the purpose of this token? How will it benefit Trust Wallet users?
 • How is the token being distributed? Are you conducting an airdrop?
 • Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?
 • Is the token listed on a centralized/decentralized exchange?
 • Is a Smart Contract audit completed? Where can we find this information?

**Comment by RealADABoy** [comment]
• What is the purpose of this token? How will it benefit Trust Wallet users?

ADA BOY is a dividend paying token that awards holders in binance-peg cardano at a rate of 4% tx volume.  ADA BOY is the natural currency of the application we have developed - the "tinder of crypto" https://cryptomatch.app, which currently has over 1000 users and 53 projects posted (users swipe left and right on projects, and our v2 iOS version will succeed this MVP in early 2022).

• How is the token being distributed? Are you conducting an airdrop?
The token was fair launched with the exception of being airdropped to holders of our previous (failed) project, Fetus Doge.  About 500 holders received adaboy because of holding FDOGE, the rest is organic.  We got CMC and CG shortly after releasing https://cryptomatch.app, and got over the 5k holder threshold easily. We have about a 4M market cap at present time.

• Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?
No, it was a fair launch / re-launch of fetus doge with an initial liquidity of just 6BNB!  (currently 430BNB in LP!)

• Is the token listed on a centralized/decentralized exchange?
Yes pancake swap (DEX) only: https://poocoin.app/tokens/0x1e653794a6849bc8a78be50c4d48981afad6359d

• Is a Smart Contract audit completed? Where can we find this information?
The contract has been verified in bscscan since launch on July 28, https://bscscan.com/address/0x1e653794a6849bc8a78be50c4d48981afad6359d#code

it has been audited by rugfreecoins and we are in processing with CERTIK for a second audit, though its really a fork of baby cake.  Almost byte for byte diff: https://www.bscscan.com/contractdiffchecker?a2=0xdB8D30b74bf098aF214e862C90E647bbB1fcC58c&a1=0x1E653794A6849bC8A78be50C4D48981AfAD6359d

**Comment by amajewski5c** [comment]
ADABoy currently has 5,648 holders.

**Comment by amajewski5c** [comment]
24 hr volume of $116k. 

A few days ago we were in the top 15 gainers in 24hr and 7 days on cmc.

**Comment by amajewski5c** [comment]
Sorry here is the audit: https://github.com/Rugfreecoins/Smart-Contract-Audits/blob/main/ADA%20Boy%20Token.pdf

**Comment by RealADABoy** [comment]
Sorry misread, heres the audit: https://github.com/Rugfreecoins/Smart-Contract-Audits/blob/main/ADA%20Boy%20Token.pdf

We have over 5600 holders with 24hr volume of 116k.

**Pull request merged**
