### PR TITLE
Add BOT (BEP20)

### PR DESCRIPTION
**Pull request by BOTDeFi**
Adding info for BEP20 token 'BOT'.

PR created by <a href="https://assets.trustwallet.com">TW Assets Management</a>

### CODE REVIEW

**Comment by BOTDeFi** [comment]
How can I send you 5 bnb Bep20?

**Comment by BOTDeFi** [comment]
hey. send BNB bep2 https://explorer.binance.org/tx/34D3928AB6AB2ECFACF8F7691ACFA7FD561AC6BCB48F5002AC277781A2B56EC9

**Comment by Cryptocool1** [comment]
• What is the purpose of this token? How will it benefit Trust Wallet users?
 • How is the token being distributed? Are you conducting an airdrop?
 • Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?
 • Is the token listed on a centralized/decentralized exchange?
 • Is a Smart Contract audit completed? Where can we find this information?

**Comment by BOTDeFi** [comment]
hey. 
 ($BOT)- is an multichain ecosystem built under the UX of an NFT-based Play-To-Earn game. Unique wallet with a built in NFT Marketplace, DEX, seasonal NFT and Token AirDrops & game-based Multifunctional messenger.
We did everything according to the tokenomics plan
https://docs.google.com/spreadsheets/d/1TQllFDB25fztnEp4Sba9F-sx-9oJrXOi/edit#gid=1741986755

https://www.certik.com/projects/bot-planet 
https://hacken.io/audits/#bot_planet
https://github.com/solidproof/kyc-certificates/blob/main/KYC_Certificate_BOT_Planet.png
https://poocoin.app/tokens/0x1ab7e7deda201e5ea820f6c02c65fce7ec6bed32
https://www.bitget.com/en/spot/BOTUSDT_SPBL
https://www.bitmart.com/trade/en?layout=basic&symbol=BOT_USDT

**Review by BOTDeFi — COMMENTED** [review]
https://coinmarketcap.com/currencies/bot-planet/
https://www.coingecko.com/en/coins/bot-planet
https://discord.com/invite/Fzt2MjghYh

**Comment by BOTDeFi** [comment]
($BOT)- is an multichain ecosystem built under the UX of an NFT-based
Play-To-Earn game. Unique wallet with a built in NFT Marketplace, DEX,
seasonal NFT and Token AirDrops & game-based Multifunctional messenger.

We did everything according to the tokenomics plan

https://docs.google.com/spreadsheets/d/1TQllFDB25fztnEp4Sba9F-sx-9oJrXOi/edit#gid=1741986755


https://www.certik.com/projects/bot-planet

https://hacken.io/audits/#bot_planet

https://github.com/solidproof/kyc-certificates/blob/main/KYC_Certificate_BOT_Planet.png

https://poocoin.app/tokens/0x1ab7e7deda201e5ea820f6c02c65fce7ec6bed32

https://www.bitget.com/en/spot/BOTUSDT_SPBL

https://www.bitmart.com/trade/en?layout=basic&symbol=BOT_USDT


https://coinmarketcap.com/currencies/bot-planet/

https://www.coingecko.com/en/coins/bot-planet

https://discord.com/invite/Fzt2MjghYh


Пт, 15 апр. 2022 г. в 12:25, CryptoA ***@***.***>:

**Comment by BOTDeFi** [comment]
sorry guys we accidentally submitted the wrong logo, can we update the logo?

**Comment by BOTDeFi** [comment]
input-onlinepngtools

**Comment by BOTDeFi** [comment]
sorry guys we accidentally submitted the wrong logo, can we update the logo?

пт, 15 апр. 2022 г. в 20:56, CryptoA ***@***.***>:

**Pull request merged**
