### PR TITLE
Add files via upload

### PR DESCRIPTION
**Pull request by homelessdoge**
hello ismbit my logo can you please accept

### CODE REVIEW

**Comment by l88888s** [comment]
I alreadyay 2000 TWT
8b893984-56d6-457b-b30d-966951bc261d

**Comment by l88888s** [comment]
hello ismbit my logo can you please accept   I already pay 2000 TWT

**Comment by Cryptocool1** [comment]
This is a BEp20 token, correct folder is blockchains/smartchain/assets.

**Comment by Cryptocool1** [comment]
This is a BEp20 token, correct folder is blockchains/smartchain/assets.

Please create new PR, follow doc https://community.trustwallet.com/t/how-to-submit-a-token-logo/3863
You may want to try our new Assets app in beta; go to https://assets.trustwallet.com, log on with Github, enter contract ID, logo and some additional info, and it will create a PR for you.
See https://community.trustwallet.com/t/how-to-submit-a-token-logo-using-assets-app/82957.

**Pull request closed without merging**
