### PR TITLE
Add Token X (BEP20)

### PR DESCRIPTION
**Pull request by hieuthch**
Adding info for BEP20 token 'Token X'.

PR created by <a href="https://assets.trustwallet.com">TW Assets Management</a>

### CODE REVIEW

**Comment by Cryptocool1** [comment]
• What is the purpose of this token? How will it benefit Trust Wallet users?
 • How is the token being distributed? Are you conducting an airdrop?
 • Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?
 • Is the token listed on a centralized/decentralized exchange?
 • Is a Smart Contract audit completed? Where can we find this information?

**Comment by hieuthch** [comment]
> • What is the purpose of this token? How will it benefit Trust Wallet users? • How is the token being distributed? Are you conducting an airdrop? • Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale? • Is the token listed on a centralized/decentralized exchange? • Is a Smart Contract audit completed? Where can we find this information?

Token X is a peer to peer medium of exchange issued by XIXO, will be an initial exchange offering 
with a limited quantity that aims to become a tool to pay for all kinds 
of goods and services in the field of real estate, 
construction and industry as well as other platforms of XIXO

Team: 15%, Advisors & Partners: 10%, Development fund: 40% , Private sales: 5%, Public sales: 20%, Airdrop: 10%
We conducted an airdrop

We sold the tokens at an Initial Coin Offering (ICO) or a token presale

The token listed on : https://app.dodoex.io/exchange/USDT-TKX?network=bsc-mainnet
		                  https://www.lbank.info/exchange/tkx/usdt
A Smart Contract audit completed:https://www.certik.org/projects/xixo-ecosystem

**Comment by ramsty** [comment]
Hi,
Your logo should be a full screen, please change.
Example:
https://community.trustwallet.com/t/how-to-submit-a-token-logo/3863
137116359-c2bb87b7-239a-4c8d-b54e-4a679c621186

**Comment by hieuthch** [comment]
> Hi, Your logo should be a full screen, please change. Example: https://community.trustwallet.com/t/how-to-submit-a-token-logo/3863 137116359-c2bb87b7-239a-4c8d-b54e-4a679c621186
logo png

please check . Thankyou

**Comment by hieuthch** [comment]
> Hi, Your logo should be a full screen, please change. Example: https://community.trustwallet.com/t/how-to-submit-a-token-logo/3863 137116359-c2bb87b7-239a-4c8d-b54e-4a679c621186
logo png
please update , Thankyou

**Comment by hieuthch** [comment]
> Hi, Your logo should be a full screen, please change. Example: https://community.trustwallet.com/t/how-to-submit-a-token-logo/3863 137116359-c2bb87b7-239a-4c8d-b54e-4a679c621186
logo png
please update the logo for me, Thank you

**Pull request merged**
