### PR TITLE
HOGL Finance Logo integration with trust wallet.

### PR DESCRIPTION
**Pull request by HOGLtoken**
Hey there, we are HOGL Finance, feel free to check out bscscan link, we meet your criteria and a number of our members have been asking us for this now.

Thank you

### CODE REVIEW

**Comment by catenocrypt** [comment]
Correction needed:  Please rename logo file to `logo.png`, this naming convention is a must.

blockchains/binance/assets/0x182c763a4b2fbd18c9b5f2d18102a0ddd9d5df26/hogll.png

**Comment by HOGLtoken** [comment]
Hey there, how can I rename it on here? I can't seem to find a way to do it, thank you

**Comment by HOGLtoken** [comment]
It's done, I'm guessing you have to delete the hogl.png file?

Thank you very much

**Comment by catenocrypt** [comment]
Renaming is OK, thanks.
Now checks have found it, and next problem is found: logo is too large.
Please scale it down, preferably to 256x256 pixels, but max 512x512, and max. 100 kbytes.

```
Image too large, 2024x1841, /home/runner/work/assets/assets/blockchains/binance/assets/0x182c763a4b2fbd18c9b5f2d18102a0ddd9d5df26/logo.png
Image too big, 399.754 kb, /home/runner/work/assets/assets/blockchains/binance/assets/0x182c763a4b2fbd18c9b5f2d18102a0ddd9d5df26/logo.png
```

**Comment by HOGLtoken** [comment]
Changed the logo size to be 256x256, sorry for the mix up

**Comment by catenocrypt** [comment]
Moved from binance to smartchain folder, as this is a BEP20, not BEP2 token.

**Comment by HOGLtoken** [comment]
Really sorry for all the errors, I've had a long week. Thank you!

**Comment by HOGLtoken** [comment]
Hey there, our price still hasn't updated in trust wallet, is there anything I need to add in the information section to update our price? Thank you

**Pull request merged**
