### PR TITLE
Adding logo to TrustWallet for DOE token

### PR DESCRIPTION
**Pull request by dogsofelon**
Followed the requirements for adding logo to TrustWallet for a token

### CODE REVIEW

**Comment by cryptomanz** [comment]
You need remove this files:
Screenshot 2022-02-08 at 09 20 30
Screenshot 2022-02-08 at 09 20 56

**Comment by dogsofelon** [comment]
> You need remove these files: Screenshot 2022-02-08 at 09 20 30 Screenshot 2022-02-08 at 09 20 56

Both the files were removed

**Review by dogsofelon — COMMENTED** [review]
File was deleted

**Comment by Cryptocool1** [comment]
your info.json file should include
- tags
- links
your logo.png size should be 256/256

**Comment by Cryptocool1** [comment]
Please create new PR, follow doc https://developer.trustwallet.com/assets/requirements
You may want to try our Assets app in beta; go to https://assets.trustwallet.com, log on with Github, enter contract ID, logo and some additional info, and it will create a PR for you.
See https://developer.trustwallet.com/assets/repository_details

**Comment by Cryptocool1** [comment]
make sure to mention this PR,so the fee can be reused

**Pull request closed without merging**
