### PR TITLE
Add BitsCow (BEP20)

### PR DESCRIPTION
**Pull request by methesushil**
Adding info for BEP20 token 'BitsCow'.

PR created by <a href="https://assets.trustwallet.com">TW Assets Management</a>

### CODE REVIEW

**Comment by methesushil** [comment]
Fee Deposited
A1891496BD3FA5C7BD0CB63034971A0E064409C4723CBCF7AFC76E5086BEF25A

**Comment by Cryptocool1** [comment]
could you delete this file ?
blockchains/smartchain/assets/0x6d5d713b7bf4dFcc7208d45BD8AB3b763F722c86/logo-cow.png

**Comment by methesushil** [comment]
Deleted that file.

**Comment by cryptomanz** [comment]
one more left blockchains/smartchain/assets/0x6d5d713b7bf4dFcc7208d45BD8AB3b763F722c86/logo-cow.png

**Comment by methesushil** [comment]
deleted

**Comment by methesushil** [comment]
Hello, Respected Collaborators, any update upon my request?

**Comment by Cryptocool1** [comment]
Did you pay?

**Comment by methesushil** [comment]
yes, I have send 1000 TWT, here is the TX Id :
A1891496BD3FA5C7BD0CB63034971A0E064409C4723CBCF7AFC76E5086BEF25A

**Comment by methesushil** [comment]
any update upon my request please?

**Comment by methesushil** [comment]
Dear collaborators, any update please.

**Comment by Cryptocool1** [comment]
Payment was not found by the bot;

**Comment by methesushil** [comment]
then should I pay again, or create a new fresh pull request?

**Comment by cryptomanz** [comment]
> then should I pay again, or create a new fresh pull request?

Create new PR and pay 
Thanks

**Pull request closed without merging**
