### PR TITLE
Add files via upload

### PR DESCRIPTION
**Pull request by deirose91**

### CODE REVIEW

**Comment by vikmeup** [comment]
https://etherscan.io/address/0xac25de8280c3b126fade99d8fd682b58309b6a70, does not seems to be ERC20 token

**Comment by deirose91** [comment]
@vikmeup it is a ERC20 token

**Comment by catenocrypt** [comment]
As per our updated policy, brand new tokens are not included, there is a minimum requirement of 100 holder addresses and 500 transactions, in order to filter out scam tokens.
See https://community.trustwallet.com/t/how-to-submit-a-token-logo/3863#how-to-get-approved
Token check:  Usage is none. Name matches.
Putting on hold for now.

image

**Comment by vikmeup** [comment]
This is a fake token of JUST (confirmed with tron team), nice try @deirose91! Closing this PR.

**Pull request closed without merging**
