### PR TITLE
Add XDEFI (ERC20)

### PR DESCRIPTION
**Pull request by davidp94**
Adding info for ERC20 token 'XDEFI'.

PR created by <a href="https://assets.trustwallet.com">TW Assets Management</a>

### CODE REVIEW

**Comment by cryptomanz** [comment]
Please follow the rules for adding token, your logo should be a full screen, 256x256.

**Comment by davidp94** [comment]
> 

will update it asap

**Comment by davidp94** [comment]
> **PR Summary** Files OK: 2 Token in PR: ERC20 0x72B886d09C117654aB7dA13A14d603001dE0B777 Symbol: **XDEFI** decimals: 18 Links: [Logo](https://raw.githubusercontent.com/davidp94/assets-1/br0209-141831/blockchains/ethereum/assets/0x72B886d09C117654aB7dA13A14d603001dE0B777/logo.png) [Info](https://raw.githubusercontent.com/davidp94/assets-1/br0209-141831/blockchains/ethereum/assets/0x72B886d09C117654aB7dA13A14d603001dE0B777/info.json) [Website](https://www.xdefi.io) [Explorer](https://etherscan.io/token/0x72B886d09C117654aB7dA13A14d603001dE0B777) Tags: nft, defi, wallet, staking Token check error: ❌ tag 'wallet' is not allowed ❌ low token circulation: number of holders is 4628, below limit of 5000
> 
> 

@cryptomanz I removed the `wallet` tag but the bot is still saying is wrong.

Logo has been updated to fit 256x256.

About the token circulation It's almost at 5k -- we have people who participated to the token sale who still has not claimed their tokens;

**Comment by Cryptocool1** [comment]
• What is the purpose of this token? How will it benefit Trust Wallet users?
 • How is the token being distributed? Are you conducting an airdrop?
 • Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?
 • Is the token listed on a centralized/decentralized exchange?
 • Is a Smart Contract audit completed? Where can we find this information?

**Comment by davidp94** [comment]
@Cryptocool1 

• What is the purpose of this token? How will it benefit Trust Wallet users?

https://xdefi-wallet.gitbook.io/xdefi-wallet/token-economic-model/ntroduction

• How is the token being distributed? Are you conducting an airdrop?
https://xdefi-wallet.gitbook.io/xdefi-wallet/token-economic-model/token-metrics

• Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?
Yes https://xdefi-wallet.gitbook.io/xdefi-wallet/public-sale-over/whitelisting-over

• Is the token listed on a centralized/decentralized exchange?
Yes - Gate.io (CEX) SushiSwap Uniswap... (DEXes)
https://coinmarketcap.com/currencies/xdefi-wallet/
Markets tab - and more to come

• Is a Smart Contract audit completed? Where can we find this information?

The ERC20 Contract has been created from the miso factory ( https://github.com/sushiswap/miso ) which has been audited by C4 (  https://code4rena.com/contests/2021-09-sushi-miso-contest )

**Pull request merged**
