### PR TITLE
Adding info and logo for LeonicornSwap

### PR DESCRIPTION
**Pull request by sintaklaas**
First commit for adding info and logo for LeonicornSwap

### CODE REVIEW

**Comment by sintaklaas** [comment]
Thanks @catenocrypt @Cryptocool1 @zachzwei 
I just found there is another pull request for this token, but this one is requested by the token owner.

**Comment by Cryptocool1** [comment]
can you please add links to your PR?
example: https://developer.trustwallet.com/add_new_asset#info-json-contents

**Comment by sintaklaas** [comment]
> can you please add links to your PR?
> example: https://developer.trustwallet.com/add_new_asset#info-json-contents

Thanks.
There were already a few of them in it, but added a few more.

**Comment by sintaklaas** [comment]
@Cryptocool1 Thanks.
There were already a few of them in it, but added a few more.

**Comment by sintaklaas** [comment]
@Cryptocool1 @zachzwei, @catenocrypt & @Iamdeadlyz, need anything more? Glad to give more info if needed.

**Review by robgeerts — APPROVED** [review]
Looks good to me

**Comment by sintaklaas** [comment]
@Cryptocool1 Can you please let me know if everything is allright now?

**Comment by Cryptocool1** [comment]
thanks

**Comment by Cryptocool1** [comment]
fixed links

**Comment by sintaklaas** [comment]
Thanks @Cryptocool1

**Pull request merged**
