### PR TITLE
Add Ecoin Finance (BEP20)

### PR DESCRIPTION
**Pull request by ecoinfinance**
Adding info for BEP20 token 'Ecoin Finance'.

PR created by <a href="https://assets.trustwallet.com">TW Assets Management</a>

### CODE REVIEW

**Comment by ecoinfinance** [comment]
Hello, I **migrated** my SMART CONTRACT v1 to a NEW one (v2), the V1 project is almost 1 year old and it was with over 50k holders and 200k transactions... but these holders are still migrating to this new smart contract... and I'd like to apply the logo and token Info before all holders migrate.. could you do that for me?

**NOTE:** This new smart contract does not have holders requirements yet, but if you look at our  V1 you will see that we are a real project with logo, CMC, CoinGecko and all social media, and also the new holders are migrating every day.

**Check all information here:** 
https://ecoin-finance.com

**Smart Contract V1: (OLD)**
https://bscscan.com/address/0x4cbdfad03b968bf43449d0908f319ae4a5a33371

**I'm waiting for your confirmation before to pay the 1000 TWT fee!
### CAN I PAY?   100% SURE YOU WILL ADD MY LOGO?**

**Comment by ecoin-finance** [comment]
Can I Pay?

**Comment by ecoin-finance** [comment]
Thanks!! 

I have payed! check please:
https://explorer.bnbchain.org/tx/A644284C9799927D81469F10511D28A6F1EC796305AE3759244887AB7FA73FF6

**Comment by ecoin-finance** [comment]
Thanks!!

I have payed! check please

**Comment by ecoin-finance** [comment]
PAYED

**Comment by Cryptocool1** [comment]
Please send the proof of your payment here. The bot didn’t mention about the payment

**Comment by ecoin-finance** [comment]
> Please send the proof of your payment here. The bot didn’t mention about the payment

https://explorer.bnbchain.org/tx/A644284C9799927D81469F10511D28A6F1EC796305AE3759244887AB7FA73FF6

**Comment by ecoin-finance** [comment]
> Please send the proof of your payment here. The bot didn’t mention about the payment
the bot is deleting it

**Comment by Cryptocool1** [comment]
https://explorer.bnbchain.org/tx/A644284C9799927D81469F10511D28A6F1EC796305AE3759244887AB7FA73FF6

**Comment by cryptomanz** [comment]
#20973

**Pull request merged**
