### PR TITLE
Coc

### PR DESCRIPTION
**Pull request by LParoni**
Hello, we have the audit of our contract as requested:

https://wetransfer.com/downloads/637956c63ab133affaaef9c66ebe529520211119115524/b0cf8e4b6d7be0cc192ab912f2334e3e20211119115538/d08283

Our previous PR is here: https://github.com/trustwallet/assets/pull/15498

### CODE REVIEW

**Comment by cryptomanz** [comment]
Please send me audit in PDF format

**Comment by LParoni** [comment]
Coin of Champions PDF audit:

https://github.com/Coin-of-Champions/contracts-coc/raw/master/Coin%20of%20the%20champions%20Full%20Smart%20Contract%20Security%20Audit(1).pdf

**Comment by Cryptocool1** [comment]
your logo should be 256/256

**Comment by LParoni** [comment]
I edited the logo with the size of 256/256

**Pull request merged**
