### PR TITLE
Add 0x0.ai: AI Smart Contract (0X0) (ERC20)

### PR DESCRIPTION
**Pull request by mostermas**
Adding info for ERC20 token '0x0.ai: AI Smart Contract (0X0)'.

PR created by <a href="https://assets.trustwallet.com">TW Assets Management</a>

### CODE REVIEW

**Comment by mostermas** [comment]
https://skynet.certik.com/projects/0x0-ai-ai-smart-contract - Audit

**Comment by Cryptocool1** [comment]
As per our policy, there is a minimum requirement of 10,000 holder addresses and 15,000 transactions.
See the criteria at : https://developer.trustwallet.com/listing-new-assets/requirements .

**Comment by mostermas** [comment]
We have Audit and CEX that is why some holders there. Pls check our project
one more time.

сб, 26 авг. 2023 г., 07:02 CryptoA ***@***.***>:

**Comment by mostermas** [comment]
Also I know that a lot of projects added to TW without 10k holders and with
Audit only

сб, 26 авг. 2023 г., 20:15 MAD MAX ***@***.***>:

**Comment by mostermas** [comment]
Can you please check

сб, 26 авг. 2023 г., 20:16 MAD MAX ***@***.***>:

**Pull request closed without merging**
