### PR TITLE
Add GBANK APY (BEP20)

### PR DESCRIPTION
**Pull request by Shyamthakur33**
Adding info for BEP20 token 'GBANK APY'.

PR created by <a href="https://assets.trustwallet.com">TW Assets Management</a>

### CODE REVIEW

**Review by tawhidnazari57 — COMMENTED** [review]
0xD5152b4Fd45DbF4B802C3E57a2038aD82ac2d688

**Comment by Shyamthakur33** [comment]
@Cryptocool1 payment done, Please check and proceed, Thank you!

**Comment by Shyamthakur33** [comment]
@Cryptocool1 please update

**Comment by Cryptocool1** [comment]
• What is the purpose of this token? How will it benefit Trust Wallet users?
 • How is the token being distributed? Are you conducting an airdrop?
 • Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?
 • Is the token listed on a centralized/decentralized exchange?
 • Is a Smart Contract audit completed? Where can we find this information?

**Comment by Shyamthakur33** [comment]
> • What is the purpose of this token? How will it benefit Trust Wallet users? • How is the token being distributed? Are you conducting an airdrop? • Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale? • Is the token listed on a centralized/decentralized exchange? • Is a Smart Contract audit completed? Where can we find this information?

1. What is the purpose of the $GBK token? How will it benefit Trust Wallet users?
   - The $GBK token is a rebase token with an auto-staking and auto-compounding protocol in the crypto space. It offers a simple "buy and hold to earn" system, where rewards are received every 3 seconds in any wallet, providing opportunities for growth and liquidity. Trust Wallet users can benefit from holding $GBK through its rebase mechanism, which consistently increases the value of their holdings over time.

2. How is the token being distributed? Are you conducting an airdrop?
   - $GBK tokens are distributed to investors as part of their participation in the rebase mechanism for long-term growth. Currently, there is no public airdrop.

3. Did you sell the tokens at an Initial Coin Offering (ICO) or a token presale?
   - No, the tokens were not sold through an ICO or token presale. It was a fair launch on Pancakeswap, and we will later move on to a centralized exchange.

4. Is the token listed on a centralized/decentralized exchange?
   - Yes, $GBK is currently listed on Coinsbit Exchange and PancakeSwap. More details available on CoinMarketCap. Further plans for additional listings will be announced as the project progresses.

5. Is a Smart Contract audit completed? Where can we find this information?
Gbank ( GBK ) Smart contract has been audited by interfinetwork .  InterFi has audited more than 500,000 solidity code-lines on Binance, Ethereum, Cronos, Fantom, Avalanche, Polygon, Bitcoin Cash, Oasis, and Metis Smart Chains!
https://www.interfi.network/

Check The Report : https://irp.cdn-website.com/1b45ecb9/files/uploaded/GBankAPY_AuditReport_InterFi.pdf

**Comment by Shyamthakur33** [comment]
@Cryptocool1 Hello,
It has been over a week since we last communicated, and I wish everything is well on your end. Please let me know if there is anything I can assist you with. Thank you!

**Pull request merged**
