### PR TITLE
Adding $ELON Token details to Trust Wallet Assets

### PR DESCRIPTION
**Pull request by elonfinance**
Adding Logo details to ERC-20 Token 0x8636Aa54EBDD097AC73E6EeB61040d840a9467b5

### CODE REVIEW

**Comment by catenocrypt** [comment]
As per our policy, brand new tokens are not included, there is a minimum requirement of 2500 holder addresses and 5000 transactions, in order to filter out scam tokens.
See the criteria at (mentioned in the first message by the bot): https://community.trustwallet.com/t/how-to-submit-a-token-logo/3863).
This token has no real usage yet (28 holders). Closing PR for now. Please come back to us when all criteria are met.  Multi-chain and staking tokens may get special treatment, let us know if this is the case. 

https://etherscan.io/token/0x8636aa54ebdd097ac73e6eeb61040d840a9467b5

**Comment by elonfinance** [comment]
These are staking reward tokens - you earn them via GYSR pools - and can stake them to earn more. Does that qualify? It’s why the numbers are low. When we get coingecko we can get the numbers up quickly.



Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by elonfinance** [comment]
Does BSC chain help at all? I’m about to create that today.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by elonfinance** [comment]
Would having a registered LLC for Elon Finance help get approval to ensure now scam? We filled Monday with the state of Florida.




Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Pull request closed without merging**
