### PR TITLE
add MBC logo and info

### PR DESCRIPTION
**Pull request by AliAkczaa**

### CODE REVIEW

**Comment by AliAkczaa** [comment]
write if everything is ok and I can make a payment.

**Comment by Cryptocool1** [comment]
• What is the purpose of this token? How will it benefit Trust Wallet users?
 • How is the token being distributed? Are you conducting an airdrop?
 • Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?
 • Is the token listed on a centralized/decentralized exchange?
 • Is a Smart Contract audit completed? Where can we find this information?

**Comment by AliAkczaa** [comment]
> • What is the purpose of this token? How will it benefit Trust Wallet users? 
The purpose of this token is to serve a functional role within our suite of Virtual Reality enabled e-commerce solutions. Once fully integrated, eventually becoming a medium of exchange between various tokens in Virtual Reality. 
>• How is the token being distributed? Are you conducting an airdrop? 
This token is currently bought or sold through locked liquidity in the binance smart chain.
>• Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale? 
This token was sold to an initial public presale and through Pancakeswap liquidity pools. 
>• Is the token listed on a centralized/decentralized exchange? 
This token is not currently listed on any centralized exchanges. The token is listed on a few decentralized exchanges. 
>• Is a Smart Contract audit completed? Where can we find this information?
The token has had a smart contract audit through InterFi. Please find this audit here: https://github.com/interfinetwork/smart-contract-audits/blob/audit-updates/MetaBUSD_0xF14D3692B0055Db9Ca4c04065165d59B87E763f1.pdf

**Comment by Cryptocool1** [comment]
your contract address should be checksummed
Please create new PR, follow doc https://developer.trustwallet.com/assets/requirements
You may want to try our Assets app in beta; go to https://assets.trustwallet.com, log on with Github, enter contract ID, logo and some additional info, and it will create a PR for you.
See https://developer.trustwallet.com/assets/repository_details

**Pull request closed without merging**
