### PR TITLE
Add Optimism PEPE (BEP20)

### PR DESCRIPTION
**Pull request by OPEPEBSC**
Adding info for BEP20 token 'Optimism PEPE'.

PR created by <a href="https://assets.trustwallet.com">TW Assets Management</a>

### CODE REVIEW

**Comment by OPEPEBSC** [comment]
Add Optimism PEPE (BEP20) #24977

**Comment by OPEPEBSC** [comment]
but there some token got trust wallet logo and they have only 4K holder
and here is example

https://bscscan.com/token/0x24086eab82dbdaa4771d0a5d66b0d810458b0e86

**Comment by OPEPEBSC** [comment]
i dont know why close my first request 
so please give me reply of reason  accept another token for logo when they was have  only 4k holder and rejected me ?

**Comment by Cryptocool1** [comment]
We do not disclose or discuss our internal policy. Come back to us once all criteria are met. 
You can mention your previous PR in new one so the fee can be reused.

**Pull request closed without merging**
