### PR TITLE
Add BabyDoge to smartchain tokenlist

### PR DESCRIPTION
**Pull request by derek-babydoge**

### CODE REVIEW

**Comment by Cryptocool1** [comment]
Please create new PR, follow doc https://developer.trustwallet.com/listing-new-assets/requirements
You may want to try our Assets app in beta; go to https://assets.trustwallet.com, log on with Github, enter contract ID, logo and some additional info, and it will create a PR for you.
See https://developer.trustwallet.com/listing-new-assets/repository_details

**Comment by derek-babydoge** [comment]
> https://assets.trustwallet.com

Hey @Cryptocool1, I believe theres a misunderstanding, our token is actually already added, see [here](https://github.com/trustwallet/assets/tree/master/blockchains/smartchain/assets/0xc748673057861a797275CD8A068AbB95A902e8de).

What I'm trying to achieve with this is to add the "Swap" feature on our token's page. Im making this change in accordance with the instructions from our TrustWallet contact.
"In order to enable the swap button, you will need to create a PR (you can find an example here - https://github.com/trustwallet/assets/pull/23740/files#diff-d5b718803066cb5db84961dfd8a66b0a06f19807af5e6f1992fe17d874610475). 
Please note that there is a PR fee (more on PR fee here - https://developer.trustwallet.com/developer/listing-new-assets/pr-fee). "


Am I missing something? Please, let me know if this is the case.

Cheers and kind wishes,
Derek from the Baby Doge Team

**Comment by Cryptocool1** [comment]
Hello, thanks for clarifying. Who told you to create a PR from our team?

**Comment by derek-babydoge** [comment]
Looks like Tatiana from Trust Wallet BD team

**Comment by Cryptocool1** [comment]
Submission looks good, awaiting for fee payment

**Pull request closed without merging**
