### PR TITLE
Add FANV (ERC20)

### PR DESCRIPTION
**Pull request by Aerdropv2**
Adding info for ERC20 token FanVerse 'FANV'.

### CODE REVIEW

**Comment by cryptomanz** [comment]
As per our policy, brand new tokens are not included, there is a minimum requirement of 5,000 holder addresses and 10,000 transactions, in order to filter out scam tokens.
See the criteria at : https://developer.trustwallet.com/assets/requirements .

**Comment by Aerdropv2** [comment]
The requirements document states "Minimum 5,000 token holders and 10,000 transactions (Airdrop tokens excluded). This requirement is subject for review based on the project."

This would lead me to believe that the 5,000 holder requirement is not set in stone. 

The project is approximately 9 days old and has a market cap of over $200m. (Launched at $11m). It also has more than $5m in liquidity and over $3.2m in volume over the last 24 hours. https://www.dextools.io/app/ether/pair-explorer/0x6a322a02596793fc4a8123be18b10b9f0f718821

Contract audits are in process from both Watchtowner and Certik.

I understand that Trust Wallet's goal with this requirement is to filter out scam tokens but this is a very serious project with millions of dollars in backing from both private investors and venture capital (ex: GDA Capital), it is definitely not a scam.

**Comment by Aerdropv2** [comment]
> As per our policy, brand new tokens are not included, there is a minimum requirement of 5,000 holder addresses and 10,000 transactions, in order to filter out scam tokens. See the criteria at : https://developer.trustwallet.com/assets/requirements .


@cryptomanz - The requirements document states "Minimum 5,000 token holders and 10,000 transactions (Airdrop tokens excluded). This requirement is subject for review based on the project."

This would lead me to believe that the 5,000 holder requirement is not set in stone.

The project is approximately 9 days old and has a market cap of over $200m. (Launched at $11m). It also has more than $5m in liquidity and over $3.2m in volume over the last 24 hours. https://www.dextools.io/app/ether/pair-explorer/0x6a322a02596793fc4a8123be18b10b9f0f718821

Contract audits are in process from both Watchtowner and Certik.

I understand that Trust Wallet's goal with this requirement is to filter out scam tokens but this is a very serious project with millions of dollars in backing from both private investors and venture capital (ex: GDA Capital), it is definitely not a scam.

**Comment by Cryptocool1** [comment]
Hello, 
• What is the purpose of this token? How will it benefit Trust Wallet users?
 • How is the token being distributed? Are you conducting an airdrop?
 • Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?
 • Is the token listed on a centralized/decentralized exchange?
 • Is a Smart Contract audit completed? Where can we find this information?

**Comment by Aerdropv2** [comment]
> Hello, • What is the purpose of this token? How will it benefit Trust Wallet users? • How is the token being distributed? Are you conducting an airdrop? • Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale? • Is the token listed on a centralized/decentralized exchange? • Is a Smart Contract audit completed? Where can we find this information?

 What is the purpose of this token? 
FanVerse is an influencer marketplace that connects influencers with their fans via Non-Fungible Tokens (NFTs). The
platform caters to both picture and video content and aligns the incentives of creators, users, and creator agencies.
This is accomplished through the circulation of the FanVerse utility token.

How will it benefit Trust Wallet users?
It will allow Trust Wallet users to track their holdings and interact with the project.

How is the token being distributed? 
Private sale, ICO, IDO and now publicly traded on Uniswap

Are you conducting an airdrop? 
Only to private sale and ICO participants (Tokens are vested over 4 months).

Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale? 
Yes, a private sale, ICO and IDO were all held, raising a total of approximately $5m USD.

Is the token listed on a centralized/decentralized exchange? 
Yes, the token is on Uniswap v2 currently. 
https://v2.info.uniswap.org/pair/0x6a322a02596793fc4a8123be18b10b9f0f718821

First CEX listing to be announced next week. (Already approved by the exchange)

Is a Smart Contract audit completed? Where can we find this information?
Certik audit is in process, current report can be found here - https://we.tl/t-MKJdyOriwa

**Pull request closed without merging**
