### PR TITLE
Add DragonMoon (BEP20)

### PR DESCRIPTION
**Pull request by dragonmoon001**
Adding info for BEP20 token 'DragonMoon'.

PR created by <a href="https://assets.trustwallet.com">TW Assets Management</a>

### CODE REVIEW

**Comment by dragonmoon001** [comment]
> Hi! In order to compensate for the efforts of processing PRs, we kindly ask for a contribution.
> 💀 As **there is no refund**, before **paying the fee**, make sure **new tokens fulfill the minimum circulation and other [acceptance criteria](https://community.trustwallet.com/t/how-to-submit-a-token-logo/3863)**.
> See also the [PR Fee FAQ](https://developer.trustwallet.com/add_new_asset/pr-fee).
> 
> Please pay **2000 TWT** with the memo **1569** to the address `bnb1tqq9llyr3dyjd559dha6z5r5etk3qfwk07m098`.
> Alternatively, 5 BNB is also accepted (same memo & address).
> 
> **QR** code: [Trust](https://api.qrserver.com/v1/create-qr-code/?size=200x200&data=https%3A%2F%2Flink.trustwallet.com%2Fsend%3Fcoin%3D714%26address%3Dbnb1tqq9llyr3dyjd559dha6z5r5etk3qfwk07m098%26amount%3D2000%26memo%3D1569) | [other wallet](https://api.qrserver.com/v1/create-qr-code/?size=200x200&data=bnb1tqq9llyr3dyjd559dha6z5r5etk3qfwk07m098%26amount%3D2000%26memo%3D1569)
> 
> _Notes_:
> 
> * [Trust Wallet Tokens (TWT)](https://community.trustwallet.com/t/trust-wallet-token-twt/4187) can be obtained through our [Referral Program](https://community.trustwallet.com/t/invite-a-friend-earn-trust-wallet-token-twt/4125) or [from DEXs/exchanges](https://community.trustwallet.com/t/where-to-get-trust-wallet-tokens/76641).
> * New tokens without significant usage are rejected, see criteria mentioned above.
> * One PR should be for a single project; PR's with more than 10 logos will be rejected.
> * Payment evaluation happens automatically, but with a few minutes delay.  When payment is detected, an Accept Review is automatically placed on the PR, which is a condition for merge.
> * Evaluating the PR is done manually, and it is merged only if all conditions are satisfied.
> * TWT-BEP2 is supported (Binance Chain), TWT-BEP20 version on Smart Chain is not.

https://github.com/trustwallet/assets/pull/9184

**Comment by dragonmoon001** [comment]
> Hi! In order to compensate for the efforts of processing PRs, we kindly ask for a contribution.
> 💀 As **there is no refund**, before **paying the fee**, make sure **new tokens fulfill the minimum circulation and other [acceptance criteria](https://community.trustwallet.com/t/how-to-submit-a-token-logo/3863)**.
> See also the [PR Fee FAQ](https://developer.trustwallet.com/add_new_asset/pr-fee).
> 
> Please pay **2000 TWT** with the memo **1569** to the address `bnb1tqq9llyr3dyjd559dha6z5r5etk3qfwk07m098`.
> Alternatively, 5 BNB is also accepted (same memo & address).
> 
> **QR** code: [Trust](https://api.qrserver.com/v1/create-qr-code/?size=200x200&data=https%3A%2F%2Flink.trustwallet.com%2Fsend%3Fcoin%3D714%26address%3Dbnb1tqq9llyr3dyjd559dha6z5r5etk3qfwk07m098%26amount%3D2000%26memo%3D1569) | [other wallet](https://api.qrserver.com/v1/create-qr-code/?size=200x200&data=bnb1tqq9llyr3dyjd559dha6z5r5etk3qfwk07m098%26amount%3D2000%26memo%3D1569)
> 
> _Notes_:
> 
> * [Trust Wallet Tokens (TWT)](https://community.trustwallet.com/t/trust-wallet-token-twt/4187) can be obtained through our [Referral Program](https://community.trustwallet.com/t/invite-a-friend-earn-trust-wallet-token-twt/4125) or [from DEXs/exchanges](https://community.trustwallet.com/t/where-to-get-trust-wallet-tokens/76641).
> * New tokens without significant usage are rejected, see criteria mentioned above.
> * One PR should be for a single project; PR's with more than 10 logos will be rejected.
> * Payment evaluation happens automatically, but with a few minutes delay.  When payment is detected, an Accept Review is automatically placed on the PR, which is a condition for merge.
> * Evaluating the PR is done manually, and it is merged only if all conditions are satisfied.
> * TWT-BEP2 is supported (Binance Chain), TWT-BEP20 version on Smart Chain is not.


Please check this
https://github.com/trustwallet/assets/pull/9184

**Comment by dragonmoon001** [comment]
@Cryptocool1 @hexorx Please check this https://github.com/trustwallet/assets/pull/9184

Hello, we have paid and waited for about 30 days, and we still can't see the LOGO, including some data that has not been included by Panckswap. Our current number of transactions and currency holders has exceeded 10,000.

**Review by dragonmoon001 — COMMENTED** [review]
try again to submit.

**Comment by cryptomanz** [comment]
hello,
can you answer some questions?
 • What is the purpose of this token? How will it benefit Trust Wallet users?
 • How is the token being distributed? Are you conducting an airdrop?
 • Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?
 • Is the token listed on a centralized/decentralized exchange?
 • Is a Smart Contract audit completed? Where can we find this information?

**Comment by cryptomanz** [comment]
why are you adding cmc to your website, you are not listed on cmc

**Comment by dragonmoon001** [comment]
> why are you adding cmc to your website? however, you are not listed on cmc

What is cmc and what is the full name?

**Comment by Cryptocool1** [comment]
Coinmarketcap

**Comment by dragonmoon001** [comment]
> Coinmarketcap

Please check https://coinmarketcap.com/zh/currencies/dragonmoon/.

**Comment by dragonmoon001** [comment]
> hello,
> can you answer some questions?
> • What is the purpose of this token? How will it benefit Trust Wallet users?
> • How is the token being distributed? Are you conducting an airdrop?
> • Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?
> • Is the token listed on a centralized/decentralized exchange?
> • Is a Smart Contract audit completed? Where can we find this information?

hello,
can you answer some questions?
• What is the purpose of this token? How will it benefit Trust Wallet 
1. We are memecoin like doge ,and the token economic model refers to safemoon, please refer to our white paper and website.

Official web: https://www.dmoon.xyz/
About price: https://poocoin.app/tokens/0x8267d169e1483e01aacbcfd22d294c47ece9f07f
Bsc: https://bscscan.com/token/0x8267d169e1483e01aacbcfd22d294c47ece9f07f?a=0x802a5e3236a34d88c13100a3e24acc8a18b91252

2. We have 10% token for AirDrop, We can make an airdrop plan to Trustwallet customers


• How is the token being distributed? 
Are you conducting an airdrop? Yes

Token model:check https://www.dmoon.xyz/whitepager

Token Details
Total Supply: 1,000,000,000,000,000 DMOON
Pre-Sale: 25% ( 250,000,000,000,000 DMOON) 100 whitelists
Pre-Sale Ratio: Community contribution reward 25%
Initial Liquidity: 19%(190,000,000,000,000 DMOON)
Development Team: 6% (60,000,000,000,000 DMOON) 60-month vesting period
Sales: 10% (100,000,000,000,000 DMOON)
Team Destruction: 40% ( 400,000,000,000,000 DMOON)
Token Model
10% tokens will be charged for each transaction with 5% issued to the holder (fram), 1% into the destruction wallet (for subsequent manual destruction), 4% into liquidity(locked forever).
Cryptocurrency holders are encouraged to conduct frequent transactions to accelerate the rate of token destruction as deflation will increase the value of DMOON.
Buy/Sell - Single transactions cannot exceed 0.05% of total supply and prevent whale trades.

• Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?
Yes, please check our white paper

Token model:check https://www.dmoon.xyz/whitepager

Token Details
Total Supply: 1,000,000,000,000,000 DMOON
Pre-Sale: 25% ( 250,000,000,000,000 DMOON) 100 whitelists
Pre-Sale Ratio: Community contribution reward 25%
Initial Liquidity: 19%(190,000,000,000,000 DMOON)
Development Team: 6% (60,000,000,000,000 DMOON) 60-month vesting period
Sales: 10% (100,000,000,000,000 DMOON)
Team Destruction: 40% ( 400,000,000,000,000 DMOON)
Token Model
10% tokens will be charged for each transaction with 5% issued to the holder (fram), 1% into the destruction wallet (for subsequent manual destruction), 4% into liquidity(locked forever).
Cryptocurrency holders are encouraged to conduct frequent transactions to accelerate the rate of token destruction as deflation will increase the value of DMOON.
Buy/Sell - Single transactions cannot exceed 0.05% of total supply and prevent whale trades.

• Is the token listed on a centralized/decentralized exchange?
Dex : Panckswap : https://poocoin.app/tokens/0x8267d169e1483e01aacbcfd22d294c47ece9f07f
Cex: Our partner in Asia https://www.cyberbank.vip/

• Is a Smart Contract audit completed? Where can we find this information?
Adult: yes please check https://www.dmoon.xyz/static/dmoon/DragonMoon-Smart-Contract-Audit-Report-en.pdf

**Comment by dragonmoon001** [comment]
> hello,
> can you answer some questions?
> • What is the purpose of this token? How will it benefit Trust Wallet users?
> • How is the token being distributed? Are you conducting an airdrop?
> • Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?
> • Is the token listed on a centralized/decentralized exchange?
> • Is a Smart Contract audit completed? Where can we find this information?

hello,
can you answer some questions?
• What is the purpose of this token? How will it benefit Trust Wallet 
1. We are memecoin like doge ,and the token economic model refers to safemoon, please refer to our white paper and website.

Official web: https://www.dmoon.xyz/
About price: https://poocoin.app/tokens/0x8267d169e1483e01aacbcfd22d294c47ece9f07f
Bsc: https://bscscan.com/token/0x8267d169e1483e01aacbcfd22d294c47ece9f07f?a=0x802a5e3236a34d88c13100a3e24acc8a18b91252
Twitter: https://twitter.com/dmoon_xyz/status/1413782460056227841?s=21


2. We have 10% token for AirDrop, We can make an airdrop plan to Trustwallet customers


• How is the token being distributed? 
Are you conducting an airdrop? Yes

Token model:check https://www.dmoon.xyz/whitepager

Token Details
Total Supply: 1,000,000,000,000,000 DMOON
Pre-Sale: 25% ( 250,000,000,000,000 DMOON) 100 whitelists
Pre-Sale Ratio: Community contribution reward 25%
Initial Liquidity: 19%(190,000,000,000,000 DMOON)
Development Team: 6% (60,000,000,000,000 DMOON) 60-month vesting period
Sales: 10% (100,000,000,000,000 DMOON)
Team Destruction: 40% ( 400,000,000,000,000 DMOON)
Token Model
10% tokens will be charged for each transaction with 5% issued to the holder (fram), 1% into the destruction wallet (for subsequent manual destruction), 4% into liquidity(locked forever).
Cryptocurrency holders are encouraged to conduct frequent transactions to accelerate the rate of token destruction as deflation will increase the value of DMOON.
Buy/Sell - Single transactions cannot exceed 0.05% of total supply and prevent whale trades.

• Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?
Yes, please check our white paper

Token model:check https://www.dmoon.xyz/whitepager

Token Details
Total Supply: 1,000,000,000,000,000 DMOON
Pre-Sale: 25% ( 250,000,000,000,000 DMOON) 100 whitelists
Pre-Sale Ratio: Community contribution reward 25%
Initial Liquidity: 19%(190,000,000,000,000 DMOON)
Development Team: 6% (60,000,000,000,000 DMOON) 60-month vesting period
Sales: 10% (100,000,000,000,000 DMOON)
Team Destruction: 40% ( 400,000,000,000,000 DMOON)
Token Model
10% tokens will be charged for each transaction with 5% issued to the holder (fram), 1% into the destruction wallet (for subsequent manual destruction), 4% into liquidity(locked forever).
Cryptocurrency holders are encouraged to conduct frequent transactions to accelerate the rate of token destruction as deflation will increase the value of DMOON.
Buy/Sell - Single transactions cannot exceed 0.05% of total supply and prevent whale trades.

• Is the token listed on a centralized/decentralized exchange?
Dex : Panckswap : https://poocoin.app/tokens/0x8267d169e1483e01aacbcfd22d294c47ece9f07f
Cex: Our partner in Asia https://www.cyberbank.vip/

• Is a Smart Contract audit completed? Where can we find this information?
Adult: yes please check https://www.dmoon.xyz/static/dmoon/DragonMoon-Smart-Contract-Audit-Report-en.pdf

**Comment by dragonmoon001** [comment]
> why are you adding cmc to your website? however, you are not listed on cmc

Please check https://coinmarketcap.com/zh/currencies/dragonmoon/.

**Comment by cryptomanz** [comment]
can you please add links to your PR?
example: https://developer.trustwallet.com/add_new_asset#info-json-contents

**Comment by Cryptocool1** [comment]
Please follow this guide: https://community.trustwallet.com/t/why-is-there-no-token-logo-or-price/138596

**Pull request merged**
