### PR TITLE
Add logo and info

### PR DESCRIPTION
**Pull request by bricsmine**
added logo and info of token brics

This invoice has already been paid: #27561

### CODE REVIEW

**Comment by Cryptocool1** [comment]
• What is the purpose of this token? How will it benefit Trust Wallet users?
 • How is the token being distributed? Are you conducting an airdrop?
 • Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?
 • Is the token listed on a centralized/decentralized exchange?
 • Is a Smart Contract audit completed? Where can we find this information?

**Comment by cryptomanz1** [comment]
• Is a Smart Contract audit completed? Where can we find this information?

**Comment by bricsmine** [comment]
I have registered here

https://www.certik.com/products/smart-contract-audit

**Comment by Cryptocool1** [comment]
Please send your smart contract audit here

**Comment by bricsmine** [comment]
We registered on the smart contract site. Because some sites were very expensive, we did not cooperate with them. We are waiting for the rest

**Comment by bricsmine** [comment]
Which sites do you approve?

**Comment by bricsmine** [comment]
Do you approve of this Cyberscope?

**Comment by Cryptocool1** [comment]
Please send your Certik audit.

**Comment by Cryptocool1** [comment]
Hello, thank you for an audit. 
Holders requirement is still pending

**Comment by bricsmine** [comment]
Holders reached the desired number

**Pull request closed without merging**
