### PR TITLE
Add MDW Token (BEP2)

### PR DESCRIPTION
**Pull request by EldeideCosta**
Adding info for BEP2 token 'MDW Token'.

PR created by <a href="https://assets.trustwallet.com">TW Assets Management</a>

### CODE REVIEW

**Comment by dublt696** [comment]
Alright .. for one I didn't know donations where a form a tax.. (being a
smart ass) I appreciate the help but my token is still setting can't move
it .. exchange .. send it.. sell it.. so if I can work any way I can I'll
split it .. just so I can have some more crypto to play with and learn
from.. thanks and I'm a broke man seeking help .. literally getting
eviction and supporting my family with one asset I'd like to learn and make
money as well do this part time if uh you know leading a poor man to the
money tree and giving him the seeds to plant and grow his own tree .. well
.. I'd share my fruit .. so what I gotta do with this fetch ai coin..?
Ain't much just 51 coins.. but it'll buy u lunch when we split it? Have a
good night..

M. BREWER

**Comment by dublt696** [comment]
Hey I'm also trying to stake it I mean anything triple it 8 mean I have
dabbled in this crypto but what is the best advice u can give me

M. BREWER

**Comment by cryptomanz** [comment]
Please follow the rules for adding token, your logo should be a full screen, 256x256.

**Comment by dublt696** [comment]
> Adding info for BEP2 token 'MDW Token'.
> 
> 
> 
> PR created by <a href="https://assets.trustwallet.com">TW Assets Management</a>

**Comment by Cryptocool1** [comment]
Please create new PR, follow doc https://developer.trustwallet.com/assets/requirements
You may want to try our Assets app in beta; go to https://assets.trustwallet.com, log on with Github, enter contract ID, logo and some additional info, and it will create a PR for you.
See https://developer.trustwallet.com/assets/repository_details

**Pull request closed without merging**
