### PR TITLE
Add WeWay (BEP20)

### PR DESCRIPTION
**Pull request by wewayio**
Adding info for BEP20 token 'WeWay'.

PR created by <a href="https://assets.trustwallet.com">TW Assets Management</a>

### CODE REVIEW

**Comment by Cryptocool1** [comment]
• What is the purpose of this token? How will it benefit Trust Wallet users?
 • How is the token being distributed? Are you conducting an airdrop?
 • Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?
 • Is the token listed on a centralized/decentralized exchange?
 • Is a Smart Contract audit completed? Where can we find this information?

**Comment by wewayio** [comment]
> • What is the purpose of this token? 

WWY is a token of the WeWay ecosystem.

WePlay - Play 2 Earn divison. Try a unique experience with our new NFT collectible game, Mad Backpacks; a play-to-earn game based on finding and collecting tokens in the real world.

WePad - IDO launchpad that will open new fundraising opportunities for the best crypto start-ups  with the largest KOLs network. Investors can benefit from flexible tier system and staking pools.

WeAcademy - Learning platform with exceptionally effective tools for making money and stimulating sustainable growth for the future through our University.


> • How will it benefit Trust Wallet users? 

The number of WWY holders is increasing very rapidly. Most of them use TrustWallet.


> • How is the token being distributed? 

As utility token for the ecosystem products.

> •Are you conducting an airdrop? 

No.

> • Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale? 

Yes. IDO - 11 jan 2022

> • Is the token listed on a centralized/decentralized exchange? 

Yes.  
https://coinmarketcap.com/currencies/weway/markets/

> • Is a Smart Contract audit completed? Where can we find this information?

Yes. 
https://drive.google.com/file/d/1156gozfN5U9AkwgOLylVF8UO-7whvEnP/view

**Comment by cryptomanz** [comment]
we require smart contract audit from reputable companies. (Certik, Techrate, Hacken, Dessert Finance)
You can see Listing Acceptance Guidelines here: https://developer.trustwallet.com/assets/requirements

**Review by Jeffreytt5 — APPROVED** [review]

**Comment by GlobalHumanBeing** [comment]
My PR Summary show below error how I will remove it manually
Best Regards,
Muhammad Shahid
ECO and Founder of Global Human Being (GHB)

Token check error:
❌ number of holders not checked: please, check it manually

**Comment by wewayio** [comment]
> we require smart contract audit from reputable companies. (Certik, Techrate, Hacken, Dessert Finance) You can see Listing Acceptance Guidelines here: https://developer.trustwallet.com/assets/requirements

I cannot find a list of "reputable companies" in the Listing Acceptance Guidelines.

4irelabs is a Trust Company in Blockchain development and contract auditing.

https://4irelabs.com/smart-contract-audit/

Partners of NEAR, Parity, Polkadot, etc.

**Pull request merged**
