### PR TITLE
Add SBX

### PR DESCRIPTION
**Pull request by stdOWL**

### CODE REVIEW

**Comment by OWLtheBird** [comment]
@catenocrypt @zachzwei

**Comment by catenocrypt** [comment]
As per our policy, brand new tokens are not included, there is a minimum requirement of 100 holder addresses and 500 transactions, in order to filter out scam tokens.
See the criteria at (mentioned in the first message by the bot): https://community.trustwallet.com/t/how-to-submit-a-token-logo/3863#how-to-get-approved
This token has no usage yet.  Putting PR on hold.  Please come back when all criteria are satisfied.

https://etherscan.io/token/0xDaF8a0E12fc3b109A17ED5CbB943A8f3f86081f7

**Comment by OWLtheBird** [comment]
Can you please check now there are 107 addresses holders.
@catenocrypt @zachzwei

**Comment by catenocrypt** [comment]
Please note that logo would look much better with transparent background:

image

I wait a bit, maybe you want to change that.
Otherwise the PR is good to go now!

**Comment by OWLtheBird** [comment]
Logo changed to transparent one. Thank you for information.
@catenocrypt @zachzwei

**Pull request merged**
