### PR TITLE
Add USDf and Gaia

### PR DESCRIPTION
**Pull request by FITvbVlQXPo01TLNLo7O00hv5Lp4KRLBB9WO0eP**
Original Paid PR: https://github.com/trustwallet/assets/pull/5899

This PR fixes the checksum and logo naming issues. It also points correctly to the right etherscan URL.

While the total number of holders is < the 2500, USDf currently has over $1.6M USDC locked in collateral value as well as over $3.5M in 24-H trading volume on Uniswap.

Gaia is the algorithmic reserve assets and has over $1.2M in locked liquidity on uniswap and over $600K in trading volume.

Happy to discuss more details and answer questions via this thread.

### CODE REVIEW

**Comment by FITvbVlQXPo01TLNLo7O00hv5Lp4KRLBB9WO0eP** [comment]
the volume now is over $8M for USDF and $2.8M for Gaia

**Comment by FITvbVlQXPo01TLNLo7O00hv5Lp4KRLBB9WO0eP** [comment]
We are added to Coingecko now: https://www.coingecko.com/en/coins/usdf

**Comment by catenocrypt** [comment]
Correction needed: logos are too large.  Recommended size is 256x256 pxs, max 512x512, mas size 100 kbytes.  Please reduce.

```
Wrong image dimensions, 1410x1410, /home/runner/work/assets/assets/blockchains/ethereum/assets/0x4B9E5fe882b2fbB3E098c9A25a8Ce66135Ed2be4/logo.png
Image too large, 1410x1410, /home/runner/work/assets/assets/blockchains/ethereum/assets/0x4B9E5fe882b2fbB3E098c9A25a8Ce66135Ed2be4/logo.png
Checking logos on chain ethereum completed, 6299 checked, 1 too large, /home/runner/work/assets/assets/blockchains/ethereum/assets/0x4B9E5fe882b2fbB3E098c9A25a8Ce66135Ed2be4/logo.png, 0 logos updated
Checking logos completed, 7727 logos checked, 1 too large, 0 logos updated
-  XXX 'Check that logos are not too large':  1 errors
   XXX   'Logo too large: /home/runner/work/assets/assets/blockchains/ethereum/assets/0x4B9E5fe882b2fbB3E098c9A25a8Ce66135Ed2be4/logo.png'
```

**Comment by FITvbVlQXPo01TLNLo7O00hv5Lp4KRLBB9WO0eP** [comment]
@catenocrypt updated to 256x256 for both

**Comment by FITvbVlQXPo01TLNLo7O00hv5Lp4KRLBB9WO0eP** [comment]
@catenocrypt thank you in advance

**Comment by catenocrypt** [comment]
Submission looks OK; fee has not been paid yet.

**Comment by catenocrypt** [comment]
Payment considered from #5899 , https://explorer.binance.org/tx/882E0CB45B391C5EE64CA2680B455450917601F3A9775E15C19EAE827D3C0469

**Pull request merged**
