### PR TITLE
Add LZ token to Trust Wallet

### PR DESCRIPTION
**Pull request by cryptofield**
Add LZ token to Trust Wallet

### CODE REVIEW

**Comment by Cryptocool1** [comment]
hello,
can you answer some questions?
• What is the purpose of this token? How will it benefit Trust Wallet users?
 • How is the token being distributed? Are you conducting an airdrop?
 • Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?
 • Is the token listed on a centralized/decentralized exchange?
 • Is a Smart Contract audit completed? Where can we find this information?

**Comment by cryptofield** [comment]
Dearr @Cryptocool1,

Please see our answers as bellow:

• What is the purpose of this token? How will it benefit Trust Wallet users?
=> 1. LZ token is utility and governance token of lz.finance, a defi platform: swap aggregator with limit function, farming as service and launchpad. Trustwallet users will use our token to use the dapps from lz.finance

• How is the token being distributed? Are you conducting an airdrop?
=> 2. LZ token is migrated from BSCX token, which is listed on Trustwallet. The migrator contract is https://bscscan.com/address/0x7f9e8fcd19cb6830331d2756bff0724b0d9010da

• Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?
=> 3. Please see 2nd answer 

• Is the token listed on a centralized/decentralized exchange?
=> 4. Token is listed on pancakeswap and swap.lz.finance

• Is a Smart Contract audit completed? Where can we find this information?
=> 5. BSCX token is audited, but LZ is not yet. We are working with our previous partners: Verichain, Halborn and Certik to have it audited

Thanks and Regards,

**Comment by cryptomanz** [comment]
Awaiting for smart contract audit.

**Comment by Cryptocool1** [comment]
please add links 
see the example here:
https://developer.trustwallet.com/add_new_asset/repository_details

**Pull request merged**
