### PR TITLE
Add ETG Finance (ETGF etgproject.org etgproject)

### PR DESCRIPTION
**Pull request by EthereumGoldETG**
Add ETG Finance token to trustwallet ETGF .
Contract : 0x74603e780545d02C4257E7D2BE19c74dE7BE1952

### CODE REVIEW

**Comment by EthereumGoldETG** [comment]
We made the payment of 2 BNB
Please if you want to make refund ask us before because we lost 2 BNB in
latest pull request

**Comment by EthereumGoldETG** [comment]
Thank you we will wait your reply soon

**Comment by Iamdeadlyz** [comment]
In accordance with our [disclaimer](https://github.com/trustwallet/assets#disclaimer), your PR is denied due to the following reason:
- Plagiarized information with the intent to mislead users
image
image

**Comment by EthereumGoldETG** [comment]
1– All users know that all information are similar as other projects   .

2– You didn't check the products working or not? Staking , Farming ,
Governance ?
All products are working 100% so we don't need to mislead our community.

Check the products not the information ( rug pull projects use exclusive
information but unsafe products )

Thank you .

**Comment by EthereumGoldETG** [comment]
Waiting your clarification or re check our products

**Comment by Iamdeadlyz** [comment]
Plagiarism, the total number of holders as well as tx doesn't meet our criteria. Therefore, we will not merge this PR due to its reliability, regardless of the "working" product.

**Comment by EthereumGoldETG** [comment]
We just finish distribution  of the bounty that's why total holders grow
fast
https://bitcointalk.org/index.php?topic=5278671.0
Other proof here
https://twitter.com/ethereumgoldetg/status/1322579513503555586?s=19


I think you can ask and we reply with proofs before you judge . 🙏

**Comment by EthereumGoldETG** [comment]
Hi team , We still waiting a positive reply

**Comment by Iamdeadlyz** [comment]
> We paid twice without any reply or refunds and still waiting positive news

There's no positive news. Check the previous message. 
Also, refunds cannot be done. It was stated the moment you created a PR. https://github.com/trustwallet/assets/pull/4680#issuecomment-719938735

**Comment by EthereumGoldETG** [comment]
In previous PR  rules that prevented ETGF are number of holders &
transactions must be 500/1000 .
And now we got new obstacles in each reply , anyone can see that we
explained and answered all your questions and can see the reply of your
previous email in screenshot below.

**Comment by EthereumGoldETG** [comment]
IMG_20201114_115857_688

**Comment by Iamdeadlyz** [comment]
That was in the past, and you were even refunded. https://github.com/trustwallet/assets/pull/4523#issuecomment-712952187

Since you are rejected now, there won't be any refunds for this PR: https://github.com/trustwallet/assets/pull/4680#issuecomment-719938735

**Pull request closed without merging**
