### PR TITLE
Add Symbiosis (BEP20)

### PR DESCRIPTION
**Pull request by allush**
Adding info for BEP20 token 'Symbiosis'.

PR created by <a href="https://assets.trustwallet.com">TW Assets Management</a>

### CODE REVIEW

**Comment by Cryptocool1** [comment]
As per our policy, there is a minimum requirement of 10,000 holder addresses and 15,000 transactions, in order to filter out scam tokens.
See the criteria at : https://developer.trustwallet.com/listing-new-assets/requirements .

**Comment by Cryptocool1** [comment]
Submission looks good awaiting for a fee payment

**Comment by Cryptocool1** [comment]
Let us know when you are ready to pay a fee and we will reopen this Pull Request

**Comment by allush** [comment]
> Let us know when you are ready to pay a fee and we will reopen this Pull Request

We are ready to pay, pls reopen the pull and send the address

**Comment by Cryptocool1** [comment]
Please see merge fee bot message about the fee

**Comment by allush** [comment]
> We are ready to pay, pls reopen the pull and send the address

We are ready to pay, pls reopen the pull and send the address

**Pull request merged**
