### PR TITLE
Add Galactic Quadrant (BEP20)

### PR DESCRIPTION
**Pull request by Vasilii79**
Adding info for BEP20 token 'Galactic Quadrant'.

PR created by <a href="https://assets.trustwallet.com">TW Assets Management</a>

### CODE REVIEW

**Comment by Cryptocool1** [comment]
• Is a Smart Contract audit completed? Where can we find this information?

**Comment by Vasilii79** [comment]
> Is a Smart Contract audit completed? Where can we find this information?

Yes. Please find the audit here: https://www.certik.com/projects/outer-ring

**Comment by Cryptocool1** [comment]
Your market data should be tracked on CoinMarketCap

**Comment by Vasilii79** [comment]
> Your market data should be tracked on CoinMarketCap

It's tracked on CoinMarketCap: https://coinmarketcap.com/currencies/outer-ring-mmo-gq/

**Review by Arezoomohammadalizadeh — COMMENTED** [review]
thankyou

**Comment by Matsuri888** [comment]
Adding info for BEP20 token 'Matsuri Shiba Inu '.

**Pull request merged**
