### PR TITLE
Add Polygon (Matic) asset

### PR DESCRIPTION
**Pull request by py-zoid**
This PR is being closed due to inactivity. If you wish to continue, please have us reopen the PR before sending your payment.
Do NOT send payments for closed PR, as the fee may by lost!
  (168 vs. 60 hrs)

### CODE REVIEW

**Comment by catenocrypt** [comment]
Is this a separate blockchain, or a token on some widely used blockchain?  If the latter, which one?

**Comment by py-zoid** [comment]
> Is this a separate blockchain, or a token on some widely used blockchain? If the latter, which one?

It's a token on Ethereum.

**Comment by py-zoid** [comment]
We want to add Matic Network chain to wallet core. Configured the wallet core fork with the necessary information following the checklist on https://developer.trustwallet.com/wallet-core/newblockchain. The last step was to upload the coin icon for which this PR is raised. If you could reopen this PR we'll make the payment.

**Comment by catenocrypt** [comment]
If this token is an ERC20 token, logo and info files should be places under folder:
`blockchains/ethereum/assets`

You may want to try our Assets app (in beta);  close this PR; go to https://assets.trustwallet.com, log on with Github, enter contract ID, logo and some additional info, and it will create a PR for you.  See  https://community.trustwallet.com/t/how-to-submit-a-token-logo-using-assets-app/82957

**Comment by py-zoid** [comment]
@catenocrypt We wanted to add Matic Network to wallet core as a new chain similar to how SmartChain is added. I see that that SmartChain are maintaining a separate directory under blockchains in the assets folder. Hence I added it this way. Moreover I was using the Celo chain PR as a reference.

**Comment by catenocrypt** [comment]
OK, thanks for the clarification -- this is what my first question was about.  https://github.com/trustwallet/assets/pull/5721#issuecomment-786691160
OK, we can add this, but are you aware that to be able to support Matic in Trust Wallet, code contribution is also needed?

**Comment by py-zoid** [comment]
@catenocrypt Thank you. And yes, we have done the necessary code changes in our wallet core fork.

**Comment by py-zoid** [comment]
I see that the merge bot closes this PR in an hour after reopening it. If you could reopen this again, I'll make sure to complete the payment before the hour runs out. Thank you.

**Comment by catenocrypt** [comment]
A once-closed PR is auto closed quickly, but don't worry, just make the fee payment, it will be noticed automatically next time we reopen.

**Comment by py-zoid** [comment]
@catenocrypt Thank you. Payment done.

**Comment by catenocrypt** [comment]
Reopening

**Pull request merged**
