### PR TITLE
ADD MMIT LOGO

### PR DESCRIPTION
**Pull request by dunitech123**

### CODE REVIEW

**Comment by cryptomanz1** [comment]
• What is the purpose of this token? How will it benefit Trust Wallet users?
 • How is the token being distributed? Are you conducting an airdrop?
 • Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?
 • Is the token listed on a centralized/decentralized exchange?
 • Is a Smart Contract audit completed? Where can we find this information?

**Comment by dunitech123** [comment]
• What is the purpose of this token? How will it benefit Trust Wallet users?
The birth of mango man meme coin is attributed to the idea of motivating crypto beginners to do well in this arena.

• How is the token being distributed? Are you conducting an airdrop?
Initial coin Distribution is made through official website of mmit. Please refer the link provided: https://mmint.io/
There is no airdrop attach with this token

• Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?
Yes,We have offered 21% of our token as presale.

• Is the token listed on a centralized/decentralized exchange?
Zax token is listed on PancakeSwap decentralized exchange.you can check here: https://coinmarketcap.com/currencies/mangoman-intelligent/markets/

• Is a Smart Contract audit completed? Where can we find this information?
yes, audit is completed. you can check it from here: https://github.com/Tech-Audit/Smart-Contract-Audits/blob/main/TECHAUDIT_MMIT.pdf

**Comment by dunitech123** [comment]
@cryptomanz1 
I have updated info.json.

**Comment by dunitech123** [comment]
@cryptomanz1
How much time it will take to merge the pull request ?

**Comment by dunitech123** [comment]
> We are still checking all info. Please be patient.

Okay

**Comment by Cryptocool1** [comment]
Have you conducted any airdrops?

**Comment by dunitech123** [comment]
> Have you conducted any airdrops?

No

**Comment by Cryptocool1** [comment]
I looked at your telegram channel and found a lot of messages about airdrops from admins. why are you misleading me?

**Comment by dunitech123** [comment]
We are from the development team and I just confirmed with the marketing team they told me that it's a contest, not the airdrop, as those who buy MMIT till 7th April then they are supposed to get rewards.
We never conducted airdrops, You can check the chart over poocoin , https://poocoin.app/tokens/0x9767c8e438aa18f550208e6d1fdf5f43541cc2c8

> I looked at your telegram channel and found a lot of messages about airdrops from admins. why are you misleading us?

**Comment by Cryptocool1** [comment]
73F8EF5C-6661-4C65-9075-9B773D4BB972
46970D54-7FEA-4F7D-BD4B-A70D9C00AC28
FED7B62C-8BB4-44DE-B85A-C9225F7A6980
8388ABBA-CA74-45B1-9D9D-A907E06A2C5F

**Comment by dunitech123** [comment]
Screenshot_2023-04-04-19-17-20-78_948cd9899890cbd5c2798760b2b95377
see we have clearly mentioned in our post "EXCLUSIVE LOTTERY" And winners will be announced on 15th April "Lottery is termed as a contest "  we named the contest an Airdrop, You can check even listed on Pancakeswap on 28th May 2022, So there is no question arise that at this point of the moment that we will give airdrop, only those who buy the MMIT will enter into the contest and chance to win exciting  rewards.

**Comment by Cryptocool1** [comment]
That is same thing.

**Comment by dunitech123** [comment]
as a development team we were not aware about that but anyways how you would like to conclude this ?

**Comment by dunitech123** [comment]
@Cryptocool1 
also for your information, the team is fully doxxed and owned 3 Projects, ZAX Zillion Aakar XO (Already in TrustWallet), BGVT Which is supposed to be Submitted and Audited By Certik, and the Third one is MMIT (Mango Man Intelligent)

You can check even all the websites and find team Photos as well, on all websites, www.bgverse.io, wwwzillionxo.io, and www.mmint.io

Even Team has attended 4 Crypto Expos so far and all relevant photos you will get it over websites.

We are working with full transparency and in an ethical way as well.

**Comment by dunitech123** [comment]
@Cryptocool1 
if there was airdrop even then 10k holders are not from airdrop there is also organic holders. 10k holders that completed on token contract that takes very long time.you can not ignore all 10k holders. please check again and tell us exactly how much more holders will be needed ?

**Comment by Cryptocool1** [comment]
I’ve already told you how many holders you should have after this incident. 
You can come back next month and we can reconsider.

**Pull request closed without merging**
