### PR TITLE
Add Lunar (BEP20)

### PR DESCRIPTION
**Pull request by LunarLegionBsc**
Adding info for BEP20 token 'Lunar'.

PR created by <a href="https://assets.trustwallet.com">TW Assets Management</a>

### CODE REVIEW

**Comment by LunarLegionBsc** [comment]
Hello, we are already on Trust Wallet, but we just need our logo to be updated, as well as the links we provided.

**Comment by Cryptocool1** [comment]
submission looks good, awaiting for fee payment

**Comment by LunarLegionBsc** [comment]
I just need the logo and links updated, we have already paid our submission
fee since we’re already listed on Trust Wallet.

**Comment by Cryptocool1** [comment]
Снимок экрана 2022-03-03 в 09 04 29
You need to pay for updating as well, please read about the Pull Request Fee here:

**Comment by LunarLegionBsc** [comment]
Okay, is this a Binance Smart Chain address , or just on the regular BNB
chain? (bnb1tqq9llyr3dyjd559dha6z5r5etk3qfwk07m098)

**Comment by LunarLegionBsc** [comment]
I sent the 5 BNB. The TX ID is: 88081A4D4BDFE59597CB6B226C29A70B613330BB997E30EEF9839F9D4C75528A

**Comment by LunarLegionBsc** [comment]
Links and logo need to be updated

**Pull request merged**
