### PR TITLE
add miniSHIB

### PR DESCRIPTION
**Pull request by ubtcto**

### CODE REVIEW

**Comment by cryptomanz** [comment]
Hello,
- Logo image too large, max 100 kB, current 174.345 kB
-  Logo should be 256x256 pixels, it is too large 512x513

**Comment by wbtcto** [comment]
@cryptomanz i updated

**Comment by cryptomanz** [comment]
Hello,
Can your answer some questions?
 • What is the purpose of this token? How will it benefit Trust Wallet users?
 • How is the token being distributed? Are you conducting an airdrop?
 • Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?
 • Is the token listed on a centralized/decentralized exchange?
 • Is a Smart Contract audit completed? Where can we find this information?

**Comment by ubtcto** [comment]
Hello team,
All project info can find in website: https://minishib.com 

miniSHIB aims to bring cryptocurrency to a wider audience through engaging content, whilst raising funds for animal welfare charities. 

We had ICO on DxSale and locked LP value in this, check info Pls:
https://dxsale.app/app/v2_9/dxlockview?id=0&add=0x07b7768F6863943a16372876A8000232b6391AdC&type=lplock&chain=BSC 

We had list in PankageSwap:
https://exchange.pancakeswap.finance/#/swap?inputCurrency=0x35bd36597ff784fcc30d08ebe4bd917374c40d4b 

Smart Contract is doing audit, it not finish in now. we a new project, big liquidity in PancakeSwap pool
https://bscscan.com/address/0x35bd36597ff784fcc30d08ebe4bd917374c40d4b#code

**Comment by Cryptocool1** [comment]
awaiting for smart contract audit

**Comment by ubtcto** [comment]
i will submit new project 
this is contract error

**Comment by ubtcto** [comment]
i will submit new project
this is contract error

**Pull request closed without merging**
