### PR TITLE
Add COLLIE INU (BEP20)

### PR DESCRIPTION
**Pull request by CollieInuToken**
Adding info for BEP20 token 'COLLIE INU'.

PR created by <a href="https://assets.trustwallet.com">TW Assets Management</a>

### CODE REVIEW

**Review by CollieInuToken — COMMENTED** [review]
Approved

**Comment by CollieInuToken** [comment]
Hey, any help to update this request?

**Review by CollieInuToken — COMMENTED** [review]
81fa7f7efb94c1f4515e29c040dc9802972d4563

**Comment by Cryptocool1** [comment]
As per our policy, brand new tokens are not included, there is a minimum requirement of 10,000 holder addresses and 15,000 transactions, in order to filter out scam tokens.
See the criteria at : https://developer.trustwallet.com/assets/requirements .

**Comment by Cryptocool1** [comment]
Moreover we require smart contract audit and CoinMarketCap listing

**Comment by iydrelief** [comment]
> Moreover, we require smart contract audit and CoinMarketCap listing

Hey, 
we already have audited and it's on https://github.com/cyberscope-io/audits/blob/main/collie/audit.pdf

You may also find the KYC there https://github.com/CollieInuToken/audit-kyc

**Comment by CollieInuToken** [comment]
> Moreover, we require smart contract audit and CoinMarketCap listing

Hey,
we already have audited and it's on https://github.com/cyberscope-io/audits/blob/main/collie/audit.pdf

You may also find the KYC there https://github.com/CollieInuToken/audit-kyc

for CMC we are applied, and we already listed on CG
https://www.coingecko.com/en/coins/collie-inu

**Comment by Cryptocool1** [comment]
Great, please come back to us when holders and CMC requirements are met

**Comment by CollieInuToken** [comment]
Hello CMC listed 
https://coinmarketcap.com/currencies/collie-inu/

**Comment by CollieInuToken** [comment]
Hello ,

Hello CMC listed
https://coinmarketcap.com/currencies/collie-inu/

On 2022-09-21 08:05 AM, CryptoA wrote:

> Great, please come back to us when holders and CMC requirements are met
> 
> --
> Reply to this email directly, view it on GitHub [1], or unsubscribe 
> [2].
> You are receiving this because you authored the thread.Message ID: 
> ***@***.***>



Links:
------
[1] 
https://github.com/trustwallet/assets/pull/22479#issuecomment-1253350852
[2]

**Pull request closed without merging**
