### PR TITLE
Add TRUMP (BEP20)

### PR DESCRIPTION
**Pull request by trumpmagadev**
Adding info for BEP20 token 'TRUMP'.

PR created by <a href="https://assets.trustwallet.com">TW Assets Management</a>

### CODE REVIEW

**Comment by Cryptocool1** [comment]
Hello! How did you get more than 10k holders in 1 week?

**Comment by trumpmagadev** [comment]
> Hello! How did you get more than 10k holders in 1 week?

Hi, thanks for your quick response. We got viral on our day 1 launch and hit 9600% gain, leading to us trending on Dextools and CoinMarketCap. 

Our token was added to CoinMarketCap on within 2 days launch, and we hit the daily gainer top chart. Recently, we also partner with Flooz and got included in their newsletter , which later on we will also be getting highlight on their X (Former Twitter) account. Our hashtag #maga was viral on X which lead to more focus on our token. However things does slow down recently due to the Bitcoin crash, but we are working on building more publicity.

We are also getting some swap and attention at Bitget platform. Thank you!

**Comment by Cryptocool1** [comment]
• What is the purpose of this token? How will it benefit Trust Wallet users?
 • How is the token being distributed? Are you conducting an airdrop?
 • Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?
 • Is the token listed on a centralized/decentralized exchange?
 • Is a Smart Contract audit completed? Where can we find this information?

**Comment by trumpmagadev** [comment]
any updates on the listing?

**Pull request merged**
