### PR TITLE
DXCN logo Update

### PR DESCRIPTION
**Pull request by Abubakrdammy**

### CODE REVIEW

**Comment by catenocrypt** [comment]
Please add an `info.json` file next to the `logo.png`, with info about the project, of the form:

```json
{
    "name": "Trust Wallet Token",
    "website": "https://trustwallet.com",
    "short_description": "Utility token to increase adoption of cryptocurrency.",
    "explorer": "https://explorer.binance.org/asset/TWT-8C2"
}
```

**Comment by Abubakrdammy** [comment]
Here is the json file as requested

[DXCN.txt](https://github.com/trustwallet/assets/files/5221277/DXCN.txt)

**Comment by Abubakrdammy** [comment]
The response box is not accepting a direct json file

**Comment by catenocrypt** [comment]
Sorry, I was confused by the mixed up files in the PR.

- blockchains/ethereum/assets/0x456AE45c0CE901E2e7c99c0718031cEc0A7A59Ff/logo.png:
I guess this is not DXCN token, and this file should be ignored

- blockchains/ethereum/assets/0x11f623c38b442425ec82fbc590e2d38ce777f6fe/logo_transparentr2-1024x1024.png:
This file should be named logo.png

- blockchains/ethereum/assets/0x11f623c38b442425ec82fbc590e2d38ce777f6fe/DXCN json.json:
this file should by named info.json

There is also another issue:  Token 0x11f6... has low usage, it has only 56 holder addresses, our limit is minimum 500.  
Can you fix the files?

https://etherscan.io/token/0x11F623c38b442425EC82fBc590e2D38Ce777f6FE

image

**Pull request closed without merging**
