### PR TITLE
Add Shiryo-Inu (ERC20)

### PR DESCRIPTION
**Pull request by rxchyrxch**
Adding info for ERC20 token 'Shiryo-Inu'.

PR created by <a href="https://assets.trustwallet.com">TW Assets Management</a>

### CODE REVIEW

**Comment by Cryptocool1** [comment]
• What is the purpose of this token? How will it benefit Trust Wallet users?
 • How is the token being distributed? Are you conducting an airdrop?
 • Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?
 • Is the token listed on a centralized/decentralized exchange?
 • Is a Smart Contract audit completed? Where can we find this information?

**Comment by rxchyrxch** [comment]
• What is the purpose of this token? How will it benefit Trust Wallet users? 
This token is in association with our NFT card game project we have over 6000 holders an they are requesting for more information to be added to trust wallet. 
• How is the token being distributed? Are you conducting an airdrop?
No airdrop it is all live trading 
• Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?
No 
• Is the token listed on a centralized/decentralized exchange?
UniSwap 
• Is a Smart Contract audit completed? Where can we find this information?
Not yet  but we are currently working on this.
Liquidity is locked, ownership has been renounced. We have spent nearly 1 million on marketing this project for its success for all trust wallet users who have invested in this.

**Comment by Cryptocool1** [comment]
Awaiting for smart contract audit, on hold for now

**Comment by ramsty** [comment]
Closing PR for now. Please come back to us when all criteria are met.
When creating a new PR make sure to mention this PR, so that we can see that fee has been paid already here.

**Pull request closed without merging**
