### PR TITLE
Add VIDT DAO (ERC20)

### PR DESCRIPTION
**Pull request by Sjazzz**
Adding info for ERC20 token 'VIDT DAO'.

PR created by <a href="https://assets.trustwallet.com">TW Assets Management</a>

### CODE REVIEW

**Comment by Sjazzz** [comment]
Please note this is NOT a new token, a token swap is currently in progress for 0xfeF4185594457050cC9c23980d301908FE057Bb1. Therefore the number of holders is still very low.
Thank you for your consideration.

**Comment by Cryptocool1** [comment]
Please come back to us once all criteria are met. Make sure to mention this PR so the fee can be reused.

**Comment by Cryptocool1** [comment]
make sure your token is listed on CMC and we are also require smart contract audit from reputable companies

**Comment by Sjazzz** [comment]
> make sure your token is listed on CMC, and we are also require smart contract audit from reputable companies

NP
https://coinmarketcap.com/currencies/vidt-datalink/

https://github.com/VIDT-DAO/audits/blob/main/Security%20Assessment%20VIDT%20DAO%20CertiK.pdf

Cheers!

**Comment by Sjazzz** [comment]
> make sure your token is listed on CMC, and we are also require smart contract audit from reputable companies

https://coinmarketcap.com/currencies/vidt-datalink/

Could you please re-open this commit or merge it?

**Comment by Cryptocool1** [comment]
As per our policy, brand new tokens are not included, there is a minimum requirement of 10,000 holder addresses and 15,000 transactions, in order to filter out scam tokens.
See the criteria at : https://developer.trustwallet.com/assets/requirements .

**Comment by Sjazzz** [comment]
> As per our policy, brand new tokens are not included, there is a minimum requirement of 10,000 holder addresses and 15,000 transactions, in order to filter out scam tokens. See the criteria at : https://developer.trustwallet.com/assets/requirements .

Hi, thanks for the reply, I understand but this is a tokenswap (in progress), current holders can be seen here ...

https://etherscan.io/token/0xfeF4185594457050cC9c23980d301908FE057Bb1
https://bscscan.com/token/0x3f515f0a8e93f2e2f891ceeb3db4e62e202d7110

**Pull request closed without merging**
