### PR TITLE
Add MGT (megalodon.finance) logo and info

### PR DESCRIPTION
**Pull request by megalodonofficial5**
Megalodon (MGT) Token information

### CODE REVIEW

**Comment by Iamdeadlyz** [comment]
Please provide more details about this project.
https://community.trustwallet.com/t/how-to-submit-a-token-logo/3863#how-to-get-approved
You can follow this format when adding an info.json file:
```
{
    "name": "Trust Wallet Token",
    "website": "https://trustwallet.com",
    "source_code": "https://github.com/trustwallet/",
    "short_description": "Utility token to increase adoption of cryptocurrency.",
    "description": "Utility token to increase adoption of cryptocurrency.",
    "socials": [
        {
            "name": "Twitter",
            "url": "https://twitter.com/trustwalletapp",
            "handle": "TrustWalletApp"
        },
        {
            "name": "Reddit",
            "url": "https://reddit.com/r/trustapp",
            "handle": "TrustApp"
        }
    ],
    "explorer": "https://bscscan.com/token/0x4b0f1812e5df2a09796481ff14017e6005508003"
} 
```

**Comment by megalodonofficial5** [comment]
> Please provide more details about this project.
> https://community.trustwallet.com/t/how-to-submit-a-token-logo/3863#how-to-get-approved
> You can follow this format when adding an info.json file:
> 
> ```
> {
>     "name": "Trust Wallet Token",
>     "website": "https://trustwallet.com",
>     "source_code": "https://github.com/trustwallet/",
>     "short_description": "Utility token to increase adoption of cryptocurrency.",
>     "description": "Utility token to increase adoption of cryptocurrency.",
>     "socials": [
>         {
>             "name": "Twitter",
>             "url": "https://twitter.com/trustwalletapp",
>             "handle": "TrustWalletApp"
>         },
>         {
>             "name": "Reddit",
>             "url": "https://reddit.com/r/trustapp",
>             "handle": "TrustApp"
>         }
>     ],
>     "explorer": "https://bscscan.com/token/0x4b0f1812e5df2a09796481ff14017e6005508003"
> } 
> ```



> Please provide more details about this project.
> https://community.trustwallet.com/t/how-to-submit-a-token-logo/3863#how-to-get-approved
> You can follow this format when adding an info.json file:
> 
> ```
> {
>     "name": "Trust Wallet Token",
>     "website": "https://trustwallet.com",
>     "source_code": "https://github.com/trustwallet/",
>     "short_description": "Utility token to increase adoption of cryptocurrency.",
>     "description": "Utility token to increase adoption of cryptocurrency.",
>     "socials": [
>         {
>             "name": "Twitter",
>             "url": "https://twitter.com/trustwalletapp",
>             "handle": "TrustWalletApp"
>         },
>         {
>             "name": "Reddit",
>             "url": "https://reddit.com/r/trustapp",
>             "handle": "TrustApp"
>         }
>     ],
>     "explorer": "https://bscscan.com/token/0x4b0f1812e5df2a09796481ff14017e6005508003"
> } 
> ```

Ok,
But

**Comment by megalodonofficial5** [comment]
> Please provide more details about this project.
> https://community.trustwallet.com/t/how-to-submit-a-token-logo/3863#how-to-get-approved
> You can follow this format when adding an info.json file:
> 
> ```
> {
>     "name": "Trust Wallet Token",
>     "website": "https://trustwallet.com",
>     "source_code": "https://github.com/trustwallet/",
>     "short_description": "Utility token to increase adoption of cryptocurrency.",
>     "description": "Utility token to increase adoption of cryptocurrency.",
>     "socials": [
>         {
>             "name": "Twitter",
>             "url": "https://twitter.com/trustwalletapp",
>             "handle": "TrustWalletApp"
>         },
>         {
>             "name": "Reddit",
>             "url": "https://reddit.com/r/trustapp",
>             "handle": "TrustApp"
>         }
>     ],
>     "explorer": "https://bscscan.com/token/0x4b0f1812e5df2a09796481ff14017e6005508003"
> } 
> ```

This is MGT Token information.

{
    "name": "MGT Token",
    "website": "https://megalodon.finance/",
    "source_code": "https://github.com/megalodonofficial5/smartcontract/blob/main/token.sol",
    "short_description": "Megalodon empowers developers, liquidity providers and traders to participate in a financial marketplace .",
    "description": "Megalodon empowers developers, liquidity providers and traders to participate in a financial marketplace .",
    "socials": [
        {
            "name": "Twitter",
            "url": "https://twitter.com/MEGALODOFARM",
            "handle": "MEGALODOFARM"
        },
        {
            "name": "Reddit",
            "url": "https://www.reddit.com/user/megalodondefi",
            "handle": "megalodondefi"
        }
    ],
    "explorer": "https://bscscan.com/token/0xdFB771617d4B2532f9A2D13FBdF503C2B34e1279"
}

**Comment by Iamdeadlyz** [comment]
In accordance with our [disclaimer](https://github.com/trustwallet/assets#disclaimer), your PR is denied due to the following reason:
- Plagiarized information with the intent to mislead users
image
image
image

**Pull request closed without merging**
