### PR TITLE
Update logo for BEP20 Token

### PR DESCRIPTION
**Pull request by jtonkeys1**
Submitting original logo for display within app

### CODE REVIEW

**Comment by jtonkeys1** [comment]
If github mod can help me figure out errors, info.jso is setup correct as far as I can tell. I am web dev for project so let me know if I messed anything up!

**Comment by jtonkeys1** [comment]
Updated the graphic asset to be better format & more clear! Thanks!

**Comment by catenocrypt** [comment]
Correction needed:  this is a BEP20 token, correct folder is `smartchain`, not binance.  Please move files.

blockchains/smartchain/assets/0xdbaaa36b347d56b77ce0e36f050fceebbf9fbc38/info.json

**Comment by jtonkeys1** [comment]
got it, working on it now

**Comment by jtonkeys1** [comment]
ok i think i did it, let me know if i need to change anything

**Comment by catenocrypt** [comment]
There are still several issues:
- files are duplicated, are in both binance and smartchain folder, only one set should be present
- folder is not in 'contract format'.
I suggest to create a new PR (and mention this one so that fee does not have to be paid again).
You may use our Assets app (in beta);  close this PR; go to https://assets.trustwallet.com, log on with Github, enter contract ID, logo and some additional info, and it will create a PR for you.  See  https://community.trustwallet.com/t/how-to-submit-a-token-logo-using-assets-app/82957

**Comment by jtonkeys1** [comment]
will do, first time going about this process so I appreciate the patience & support!

**Comment by Cryptocool1** [comment]
Closing PR for now. Please come back to us when all criteria are met.
Please come back to us when all criteria are met.
When creating a new PR make sure to mention this PR, so that we can see that fee has been paid already here.

**Pull request closed without merging**
