### PR TITLE
Add new logo for HXY Money

### PR DESCRIPTION
**Pull request by kmphua**
Add new logo for HXY Money

### CODE REVIEW

**Comment by Iamdeadlyz** [comment]
Please provide more details for each token that you added with logos (except for `0xf3A2ace8e48751c965eA0A1D064303AcA53842b9` since it has an info.json already).
https://community.trustwallet.com/t/how-to-submit-a-token-logo/3863#how-to-get-approved
You can follow this format when adding an info.json file:
```
{
    "name": "Trust Wallet Token",
    "website": "https://trustwallet.com",
    "source_code": "https://github.com/trustwallet/",
    "short_description": "Utility token to increase adoption of cryptocurrency.",
    "description": "Utility token to increase adoption of cryptocurrency.",
    "socials": [
        {
            "name": "Twitter",
            "url": "https://twitter.com/trustwalletapp",
            "handle": "TrustWalletApp"
        },
        {
            "name": "Reddit",
            "url": "https://reddit.com/r/trustapp",
            "handle": "TrustApp"
        }
    ],
    "explorer": "https://bscscan.com/token/0x4b0f1812e5df2a09796481ff14017e6005508003"
} 
```

**Comment by kmphua** [comment]
Updated info.json for HXY token

**Comment by Iamdeadlyz** [comment]
Hi @kmphua,

Please add info.json to other tokens too. Specifically for:
0x0FFF95D5ab18c763c42C209F137C47354af104a8
0x16aB6ED897D04856Ff138122Db4b7767078a20F3
0x9BB6fd000109E24Eb38B0Deb806382fF9247E478

**Comment by kmphua** [comment]
> Hi @kmphua,
> 
> Please add info.json to other tokens too. Specifically for:
> 0x0FFF95D5ab18c763c42C209F137C47354af104a8
> 0x16aB6ED897D04856Ff138122Db4b7767078a20F3
> 0x9BB6fd000109E24Eb38B0Deb806382fF9247E478

Added info.json for 0x16aB6ED897D04856Ff138122Db4b7767078a20F3 and 0x9BB6fd000109E24Eb38B0Deb806382fF9247E478. However, 0x0FFF95D5ab18c763c42C209F137C47354af104a8 is not longer in use so removed.

**Pull request closed without merging**
