### PR TITLE
Add files via upload

### PR DESCRIPTION
**Pull request by messaoud54**
hello i sumbit my logo can you please accept

### CODE REVIEW

**Comment by Cryptocool1** [comment]
As per our policy, there is a minimum requirement of 10,000 holder addresses and 15,000 transactions, in order to filter out scam tokens.
See the criteria at : https://developer.trustwallet.com/listing-new-assets/requirements .

**Comment by Cryptocool1** [comment]
Please create new PR, follow doc https://developer.trustwallet.com/listing-new-assets/requirements
You may want to try our Assets app in beta; go to https://assets.trustwallet.com, log on with Github, enter contract ID, logo and some additional info, and it will create a PR for you.
See https://developer.trustwallet.com/listing-new-assets/repository_details

**Comment by messaoud54** [comment]
hello i sumbit my logo can you please accept

**Comment by messaoud54** [comment]
**hello i sumbit my logo can you please accept**

**Pull request closed without merging**
