### PR TITLE
Add ENHANCE (BEP20)

### PR DESCRIPTION
**Pull request by Enhancedtoken**
Adding info for BEP20 token 'ENHANCE'.

PR created by <a href="https://assets.trustwallet.com">TW Assets Management</a>

### CODE REVIEW

**Comment by cryptomanz** [comment]
• What is the purpose of this token? How will it benefit Trust Wallet users?
 • How is the token being distributed? Are you conducting an airdrop?
 • Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?
 • Is the token listed on a centralized/decentralized exchange?
 • Is a Smart Contract audit completed? Where can we find this information?

**Comment by Enhancedtoken** [comment]
- We provide on chain defi solutions to our holders and have established a NFT collection and marketplace. We plan to keep expanding and building on more integrations for users. 
- The token has not been distributed by airdrop.
- There was no Presale conducted.
- We are listed on PancakeSwapV2
-https://dessertswap.finance/audits/Enhance%20BSC%20Audit%2012155665.pdf

Thank you for reviewing.

**Comment by Cryptocool1** [comment]
• Is a Smart Contract audit completed? Where can we find this information?

**Comment by Enhancedtoken** [comment]
> • Is a Smart Contract audit completed? Where can we find this information?

- https://dessertswap.finance/audits/Enhance%20BSC%20Audit%2012155665.pdf

**Review by bluebxo — COMMENTED** [review]
Nice

**Pull request merged**
