### PR TITLE
SonOfShib PR

### PR DESCRIPTION
**Pull request by sonofshib**

### CODE REVIEW

**Comment by Cryptocool1** [comment]
• What is the purpose of this token? How will it benefit Trust Wallet users?
 • How is the token being distributed? Are you conducting an airdrop?
 • Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?
 • Is the token listed on a centralized/decentralized exchange?
 • Is a Smart Contract audit completed? Where can we find this information?

**Comment by sonofshib** [comment]
• What is the purpose of this token? How will it benefit Trust Wallet users?
- The end goal of the project is a VR meta-verse incorporating blockchain tech. Prior to that, an NFT marketplace will be created to utilize assets inside the VR meta-verse. Trust Wallet users will benefit from this project by having access to tokens that can be used on the NFT marketplace and VR meta-verse.

• How is the token being distributed? Are you conducting an airdrop?
- SonOfShib is a relaunch of a previous project MiniShibaInu converting over to the PCS v2 router. As such, token-for-token airdrops were conducted for previous holders of the token. SonOfShib tokens are currently available to trade on PCS with more exchanges to follow.

• Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?
- A portion of the tokens were sold through DxSale with the resulting LP being transferred to PCS.

• Is the token listed on a centralized/decentralized exchange?
- As of now, SonOfShib is listed only on PCS as it just relaunched. Other exchanges are in the direct Roadmap of this project such as Bitmart & LBank. 

• Is a Smart Contract audit completed? Where can we find this information?
- An audit by Certik is currently processing. An initial review of the SC was provided by Certik to the team prior to launch and adjustments were made. The updated SC was sent to Certik for another review. Once the secondary review comes back, it will be available to the public via our website. I can attach the initial review if that is desired.

**Comment by Cryptocool1** [comment]
awaiting for smart contract audit, on hold for now

**Comment by ramsty** [comment]
Closing PR for now. Please come back to us when all criteria are met.
When creating a new PR make sure to mention this PR, so that we can see that fee has been paid already here.

**Pull request closed without merging**
