### PR TITLE
Create PokerFi

### PR DESCRIPTION
**Pull request by renatomaiag**

### CODE REVIEW

**Comment by renatomaiag** [comment]
Logo pokerfi 256x256

**Comment by Cryptocool1** [comment]
Please create new PR, follow doc https://developer.trustwallet.com/listing-new-assets/requirements
You may want to try our Assets app in beta; go to https://assets.trustwallet.com, log on with Github, enter contract ID, logo and some additional info, and it will create a PR for you.
See https://developer.trustwallet.com/listing-new-assets/repository_details

**Comment by renatomaiag** [comment]
Good afternoon. We'll make the necessary changes

Em qui., 5 de out. de 2023 às 12:14, CryptoA ***@***.***>
escreveu:

**Comment by Lovely43** [comment]
> Hi! In order to compensate for the efforts of processing PRs, we kindly ask for a contribution.
>  💀 As **there is no refund**, before **paying the fee**, make sure **new tokens fulfill the minimum circulation and other [acceptance criteria](https://developer.trustwallet.com/listing-new-assets/requirements)**.
>  See also the [PR Fee FAQ](https://developer.trustwallet.com/listing-new-assets/faq).
> 
>  Please pay  **500 TWT**  with the memo **26505**  to the TWT-BEP2 (Binance Chain) address `bnb158fgd782we4tz9vwwcj9pmmxvxhl6z46lfm7c8`.
>  Alternatively, 5 BNB is also accepted (same memo & address).
> 
>  **QR** code: [Trust]( https://api.qrserver.com/v1/create-qr-code/?size=200x200&data=https%3A%2F%2Flink.trustwallet.com%2Fsend%3Fcoin%3D714%26address%3Dbnb158fgd782we4tz9vwwcj9pmmxvxhl6z46lfm7c8%26amount%3D500%26memo%3D26505 ) | [other wallet]( https://api.qrserver.com/v1/create-qr-code/?size=200x200&data=bnb158fgd782we4tz9vwwcj9pmmxvxhl6z46lfm7c8%3Famount%3D500%26memo%3D26505 )
> 
>  *TWT Acquiring*:
> 
>  * [Trust Wallet Tokens (TWT)](https://community.trustwallet.com/t/trust-wallet-token-twt/4187) can be obtained from [DEXs/exchanges](https://community.trustwallet.com/t/where-to-get-trust-wallet-tokens/76641).
>  * TWT-BEP2 is supported (Binance Chain), TWT-BEP20 version on Smart Chain is not.
>  * TWT-BEP20 can be traded with TWT-BEP2 using the Trust Wallet [Swap Option](https://community.trustwallet.com/t/how-to-trade-with-the-built-in-dex-swap-option/169).
> 
>  *Notes*:
> 
>  * New tokens without significant usage are rejected, see criteria mentioned above.
>  * One PR should be for a single project; PR's with more than 10 logos will be rejected.
>  * Payment evaluation happens automatically, but with a few minutes delay.  When payment is detected, an Accept Review is automatically placed on the PR, which is a condition for merge.
>  * Evaluating the PR is done manually, and it is merged only if all conditions are satisfied.
>  There will be a fee to process this request. None of it goes to the developers.
>  Before paying the fee, make sure new tokens fulfill the minimum circulation and other acceptance criteria.
>  If you are paying TWT for the submission, this will be burned automatically. There will be no refunds.

**Pull request closed without merging**
