### PR TITLE
0x89671544190eE39E469C8393009875dF6565457a

### PR DESCRIPTION
**Pull request by spacegrime**
This PR is being closed due to inactivity. If you wish to continue, please have us reopen the PR before sending your payment, or just create a new one.
Do NOT send payments for closed PR, as the fee may by lost!
  (48 vs. 48 hrs)

### CODE REVIEW

**Comment by spacegrime** [comment]
@vikmeup here you go

**Comment by vikmeup** [comment]
Both image filename and `id` should be named with this format: `0x89671544190eE39E469C8393009875dF6565457a`

Screen Shot 2021-05-13 at 10 09 23 PM

**Comment by spacegrime** [comment]
@vikmeup I tried that on the id (the filename shows the correct format with the mix of upper and lowercase as per merge-fee-bot) but the id only allows lowercase. See attached prior to changing it back to all lowercase again (id only).
Screen Shot 2021-05-13 at 10 11 38 PM

**Comment by spacegrime** [comment]
@vikmeup do you have an update on this? We want to make the payment so that everything works fine now but haven't gotten an update on why this error is being caused still if all is updated to reflect the correct format provided by merge-fee-bot

**Comment by Cryptocool1** [comment]
Hello,
can you please rename your contract?
 should be 0x89671544190eE39E469C8393009875dF6565457a (not 0x89671544190ee39e469c8393009875df6565457a)

**Comment by spacegrime** [comment]
@Cryptocool1 Hi there, thank you for your comment! We tried renaming this yesterday and it's not reflecting any changes.

**Comment by Cryptocool1** [comment]
> @Cryptocool1 Hi there, thank you for your comment! We tried renaming this yesterday and it's not reflecting any changes.

Hi,
I suggest creating a new PR.
You may use our Assets app (in beta); close this PR; go to https://assets.trustwallet.com, log on with Github, enter contract ID, logo and some additional info, and it will create a PR for you. See https://community.trustwallet.com/t/how-to-submit-a-token-logo-using-assets-app/82957\

**Pull request closed without merging**
