### PR TITLE
Added 4 new ibbt.io Tokens to Trust Wallet

### PR DESCRIPTION
**Pull request by geopayme**
Added to Trust Wallet 4 new ibbt.io tokens;

Mythril Ore (ORE)
Med. Cannabis Note (₵)
Dollar Blocknote ($)
Realblock.io (REAL)

### CODE REVIEW

**Comment by geopayme** [comment]
0.5 BNB payment was send to address bnb1tqq9llyr3dyjd559dha6z5r5etk3qfwk07m098

**Comment by geopayme** [comment]
0.5 BNB payment to address bnb1tqq9llyr3dyjd559dha6z5r5etk3qfwk07m098 was confirmations

**Comment by vikmeup** [comment]
> 0.5 BNB payment to address bnb1tqq9llyr3dyjd559dha6z5r5etk3qfwk07m098 has confirmations
Make sure you specified correct memo listed below

**Comment by geopayme** [comment]
0.5 BNB payment completed with memo 1872

**Comment by vikmeup** [comment]
> 0.5 BNB payment completed with memo 1872

Got it, next time just put the number as `1872`, instead of `memo 1872`

**Comment by geopayme** [comment]
I normally do, blame it on corona ;) Thank you! Stay Safe!

**Comment by geopayme** [comment]
Pointe taken, and understood!

**Pull request closed without merging**
