### PR TITLE
What is Vacay?

### PR DESCRIPTION
**Pull request by VacayToken**
Vacay is a token designed to be used for all of your travel expenses at a discounted rate. Whether its your hotel, airfare, car rental, attractions, or dining you will be able to pay for all of these expenses using Vacay.

### CODE REVIEW

**Comment by VacayToken** [comment]
Thank you and yes we have 2560 wallets and 6595 transfers.

**Comment by Cryptocool1** [comment]
This is a BEp20 token, correct folder is blockchains/smartchain/assets. Please correct.

**Comment by VacayToken** [comment]
ok thanks, I fixed it now

**Comment by VacayToken** [comment]
ok im on it

**Comment by VacayToken** [comment]
Ok i think i fixed the issues you described

**Comment by Cryptocool1** [comment]
> Ok i think i fixed the issues you described

correction needed:
PR should include only 2 files

**Comment by VacayToken** [comment]
should i close this and reopen? i only have 2 files i submitted

**Comment by Cryptocool1** [comment]
Correction needed: Logo file should be named logo.png exactly, please rename

**Comment by VacayToken** [comment]
updates with just two

**Comment by VacayToken** [comment]
so everytime i put a lowercase l on the p[icture it turns to capital letter

**Comment by Cryptocool1** [comment]
please delete this file blockchains/smartchain/assets/0xa3424fb48b9fa2ff8d3366ed91f36b4cda7cadd8/logo.png,
and your logo file should be named logo.png exactly, not Logo.png.png

**Comment by VacayToken** [comment]
ok i got it

**Comment by VacayToken** [comment]
ok uploaded the new ones

**Comment by VacayToken** [comment]
Is it ok now?

**Comment by VacayToken** [comment]
ill be here another 45 min before i head to bed. I hope i sent everything  correct this time but it doesnt look like it.

**Comment by Cryptocool1** [comment]
correction needed:
Contract is not in checksum format, should be 0xA3424FB48b9FA2FF8D3366eD91f36b4cDa7cAdd8 (not 0xA3424fb48b9fa2ff8d3366ed91f36b4cda7cadd8).

**Comment by VacayToken** [comment]
Ok I updated

**Pull request merged**
