### PR TITLE
Add Happiness Token (BEP20)

### PR DESCRIPTION
**Pull request by HPSOfficial**
Adding info for BEP20 token 'Happiness Token'.

PR created by <a href="https://assets.trustwallet.com">TW Assets Management</a>

### CODE REVIEW

**Comment by Cryptocool1** [comment]
As per our policy, brand new tokens are not included, there is a minimum requirement of 10,000 holder addresses and 15,000 transactions, in order to filter out scam tokens.
See the criteria at : https://developer.trustwallet.com/assets/requirements .

**Comment by Cryptocool1** [comment]
As per our policy, brand new tokens are not included, there is a minimum requirement of 10,000 holder addresses and 15,000 transactions, in order to filter out scam tokens.
See the criteria at : https://developer.trustwallet.com/assets/requirements .

**Comment by HPSOfficial** [comment]
> As per our policy, brand new tokens are not included, there is a minimum requirement of 10,000 holder addresses and 15,000 transactions, in order to filter out scam tokens. See the criteria at : https://developer.trustwallet.com/assets/requirements .

No we are already listed on Trust wallet
we only want to upgrade our HPS contract 

please help

**Comment by HPSOfficial** [comment]
> > As per our policy, brand new tokens are not included, there is a minimum requirement of 10,000 holder addresses and 15,000 transactions, in order to filter out scam tokens. See the criteria at : https://developer.trustwallet.com/assets/requirements .
> 
> No we are already listed on Trust wallet we only want to upgrade our HPS contract
> 
> please help
You can confirm it here:

https://bscscan.com/token/0xeda21b525ac789eab1a08ef2404dd8505ffb973d

**Comment by HPSOfficial** [comment]
> As per our policy, brand new tokens are not included, there is a minimum requirement of 10,000 holder addresses and 15,000 transactions, in order to filter out scam tokens. See the criteria at : https://developer.trustwallet.com/assets/requirements .

also we made an announcement about it also bscscan already updated our new contract

this is the proof: Announcement: https://twitter.com/BHC_Happiness/status/1532332198103519232?s=20&t=NmLrWPXpUVa2VmKvj9ctog

**Comment by Cryptocool1** [comment]
#22393 paid

**Comment by HPSOfficial** [comment]
@Cryptocool1 Thank you for helping and verifying us. Trust Wallet is the best <3

**Comment by HPSOfficial** [comment]
> #22395 migration

about the price Pancake will update it?

or you can track it here? 

https://pancakeswap.finance/info/token/0xc9d53a339f3c22e016c6fa1e3eb85ac32c75fed2

**Comment by HPSOfficial** [comment]
> #22395 migration

Hello I still saw the old HPS showing on my trust wallet
can we remove it? this is the contract address:

0xeDa21B525Ac789EaB1a08ef2404dd8505FfB973D

photo_2022-09-14_19-24-51

**Pull request merged**
