### PR TITLE
Add WibeGram (BEP20)

### PR DESCRIPTION
**Pull request by erience**
WibeGram Assets

Audit Report: https://www.cyberscope.io/audits/wibe
CoinMarketCap: https://coinmarketcap.com/currencies/wibegram/
Exchange: https://www.lbank.com/trade/wibe_usdt
Exchange: https://www.indoex.io/trade/WIBE_USDT 
Exchange: https://bitstorage.finance/spot/trading/WIBEUSDT

### CODE REVIEW

**Comment by erience** [comment]
@Cryptocool1 @cryptomanz1 

Audit Report: https://www.cyberscope.io/audits/wibe
CoinMarketCap: https://coinmarketcap.com/currencies/wibegram/
Exchange: https://www.lbank.com/trade/wibe_usdt
Exchange: https://www.indoex.io/trade/WIBE_USDT
Exchange: https://bitstorage.finance/spot/trading/WIBEUSDT

**Comment by erience** [comment]
@Cryptocool1 @cryptomanz1  any update ??

**Comment by cryptomanz1** [comment]
• What is the purpose of this token? How will it benefit Trust Wallet users?
 • How is the token being distributed? Are you conducting an airdrop?
 • Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?

**Comment by erience** [comment]
• What is the purpose of this token? How will it benefit Trust Wallet users? : 

Wibegram is a encrypted messaging app designed to provide secure communication with advanced privacy features. Trust wallet users can access the Dapp and use token inside the Trust wallet app seamlessly. 

• How is the token being distributed? Are you conducting an airdrop?

No Airdrop. Direct purchase form the Market. The token is listed on Multiple exchanges.

• Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?

No ICO.

**Comment by erience** [comment]
@Cryptocool1 @cryptomanz1 any update ??

**Pull request merged**
