### PR TITLE
Add UZYTH (BEP20)

### PR DESCRIPTION
**Pull request by SolutionPr**
Adding info for BEP20 token 'UZYTH'.

PR created by <a href="https://assets.trustwallet.com">TW Assets Management</a>

### CODE REVIEW

**Comment by thinkbankcoin** [comment]
What is the current circulation ratio of UZYTH's Token?

**Comment by cryptomanz** [comment]
• What is the purpose of this token? How will it benefit Trust Wallet users?
 • How is the token being distributed? Are you conducting an airdrop?
 • Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?
 • Is the token listed on a centralized/decentralized exchange?
 • Is a Smart Contract audit completed? Where can we find this information?

**Comment by SolutionPr** [comment]
> • What is the purpose of this token? How will it benefit Trust Wallet users? • How is the token being distributed? Are you conducting an airdrop? • Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale? • Is the token listed on a centralized/decentralized exchange? • Is a Smart Contract audit completed? Where can we find this information?

1) Uzyth is developing an ecosystem of services aimed at providing users the possibility of being rewarded ZYTH tokens based on their active participation on the platform.
https://uzyth.com (Website)
https://play.google.com/store/apps/details?id=com.zyth.go&hl=en_IN&gl=US (Android app) - ZYTH GO
https://apps.apple.com/us/app/zyth-go/id1490576729 (iOS app) - ZYTH GO
https://play.google.com/store/apps/details?id=com.zyth.app&hl=en_IN&gl=US (Android app) - ZYTH WALLET
https://apps.apple.com/us/app/zyth-wallet/id1505566186 (iOS app) - ZYTH WALLET

2) We have launched this token in 2018 and recently moved from ETH to BSC. We do have more than 20k token holders on bscscan. We have loked tokens on staking contraction.

3) Yes, We have distributed tokens. I hereby sharing link of contracts :-
Token contract address :-
https://www.bscscan.com/address/0x0df044b7f0aadfeab21bc134fe525a19484ac133#code

Distribution contract address :-
https://www.bscscan.com/address/0x493351483aa1699bf30809a04425e3e00d26f67e#code

Staking contract address :-
https://www.bscscan.com/address/0xa7ede20ec4a5eee378c7f4399656930e43d404b2#code

4) Yes, Token is already on pancakeswap. Please see links here:-
https://pancakeswap.finance/info/pool/0x527f3cf844cfe3e9a6db1fed22e61b16181d3ddd

Coinmarketcap:-
https://coinmarketcap.com/currencies/uzyth/

5) Yes, Smart contract audit is done.

**Comment by Cryptocool1** [comment]
Can you send smart contract audit here?

**Comment by Cryptocool1** [comment]
please come back to us when you will be ready to send your audit. make sure to mention this PR so the fee can be reused

**Comment by FinelineSupport** [comment]
Hi,
here is a link for  audit report :
https://www.uzyth.com/assets/zyth_binance.pdf

**Pull request closed without merging**
