### PR TITLE
add SPO logo and info

### PR DESCRIPTION
**Pull request by quannguyen2724**
add SPO logo and info

### CODE REVIEW

**Comment by quannguyen2724** [comment]
@cryptomanz Hi,
I see our PR merged 18 days ago but I haven't seen the updated SPO icon on pancakeswap. Can you double check it for me and update it? Thank you!

**Comment by quannguyen2724** [comment]
@cryptomanz Hi,
My PR was merged 18 days ago, but I realized I mistook the SPO's id with another token, and now the icon of SPO token has been updated with a token other than ours. Can I fix my PR without having to pay again, please support me.

**Comment by quannguyen2724** [comment]
@ramsty Hi,
My PR was merged 18 days ago, but I realized I mistook the SPO's contract address with another which has a similar name on bscscan, and now the icon of SPO token has been updated with a token other than ours. Can I fix my PR without having to pay again, please support me. This is very urgent and causes great damage to us. Please help me fix it.
You can contact me at quan.nguyen@spores.app.

**Comment by ramsty** [comment]
Hi! Provide right contract please.

**Comment by quannguyen2724** [comment]
> Hi! Provide right contract please.

Hi! Thank you so much for your reply.
This is the right contract: 0x8357c604c5533fa0053beaaa1494da552cea38f7
For more information: https://bscscan.com/token/0x8357c604c5533fa0053beaaa1494da552cea38f7

**Comment by quannguyen2724** [comment]
@ramsty Hi, 
Can you let me know how the icon update for SPO token is progressing

**Comment by quannguyen2724** [comment]
@ramsty  This is the correct content of the JSON file that i should have added in the pull request:
{
    "name": "SPO Token",
    "website": "https://spores.app",
    "description": "SPO token is designed for community governance and DeFi utilization with NFT-creator-centricity and DeFi-community-driven purpose. SPO is used to incentivize NFT creators, buyers, agents, liquidity providers across the ecosystem.",
    "explorer": "https://etherscan.io/token/0x8357c604c5533fa0053beaaa1494da552cea38f7",
    "type": "BEP20",
    "symbol": "SPO",
    "decimals": 18,
    "status": "active",
    "id": "0x8357c604c5533fa0053BeAaA1494Da552ceA38f7",
    "links": [
        {
            "name": "twitter",
            "url": "https://twitter.com/Spores_Network"
        },
        {
            "name": "medium",
            "url": "https://spores.medium.com"
        },
        {
            "name": "coingecko",
            "url": "https://coingecko.com/en/coins/spores-network"
        },
        {
            "name": "coinmarketcap",
            "url": "https://coinmarketcap.com/currencies/spores-network"
        }
    ]
}

**Comment by quannguyen2724** [comment]
@ramsty   This is the correct content of the JSON file that i should have added in the pull request:
{
    "name": "SPO Token",
    "website": "https://spores.app/about",
    "description": "SPO token is designed for community governance and DeFi utilization with NFT-creator-centricity and DeFi-community-driven purpose. SPO is used to incentivize NFT creators, buyers, agents, liquidity providers across the ecosystem.",
    "explorer": "https://bscscan.com/token/0x8357c604c5533fa0053beaaa1494da552cea38f7",
    "type": "BEP20",
    "symbol": "SPO",
    "decimals": 18,
    "status": "active",
    "id": "0x8357c604c5533fa0053BeAaA1494Da552ceA38f7",
    "links": [
        {
            "name": "twitter",
            "url": "https://twitter.com/Spores_Network"
        },
        {
            "name": "medium",
            "url": "https://spores.medium.com"
        },
        {
            "name": "coingecko",
            "url": "https://coingecko.com/en/coins/spores-network"
        },
        {
            "name": "coinmarketcap",
            "url": "https://coinmarketcap.com/currencies/spores-network"
        }
    ]
}

**Comment by ramsty** [comment]
Hi! Have you done migration lately?

**Comment by quannguyen2724** [comment]
@ramsty Hi, I want to give you specific information so that you understand the situation.
This is the WRONG contract in the PR: 0x8316c1cB76b88be6450baF689860b73dC606B431
I mistook it because it has a similar name to our contract name on BscScan, it **never belonged** to us, and now it has our icon on pancakeswap.
This is our RIGHT contract that should be in the PR: 0x8357c604c5533fa0053BeAaA1494Da552ceA38f7
Our icon is on the wrong contract, we really need it removed and add on our contract
Please support me!!!

**Comment by ramsty** [comment]
Ok, create a new PR please with right contract and we will update information.

**Comment by quannguyen2724** [comment]
@ramsty will we have to pay the fee again for the new PR and would you revert this PR when we created a new one ?

**Comment by ramsty** [comment]
Just mention this PR in the new one

**Comment by quannguyen2724** [comment]
@ramsty Yes, thank you!!!

**Comment by quannguyen2724** [comment]
@ramsty I've just created a new PR
https://github.com/trustwallet/assets/pull/16061

**Pull request merged**
