### PR TITLE
I was done through Trustwallet. Is it possible to additionally change the token image?

### PR DESCRIPTION
**Pull request by nvirworld**
I was done through Trustwallet. Is it possible to additionally change the token image?

image

I'm requesting that the token image looks broken around it.

### CODE REVIEW

**Comment by Cryptocool1** [comment]
FE1E5F9A-A7FE-48E3-8DDF-29E707DD31FA
Your logo looks good

**Comment by nvirworld** [comment]
On Uniswap, it doesn't look good. Can I change it?

https://info.uniswap.org/#/tokens/0x9d71ce49ab8a0e6d2a1e7bfb89374c9392fd6804

**Comment by Cryptocool1** [comment]
Снимок экрана 2022-06-22 в 12 08 29
On Uniswap also good

**Comment by nvirworld** [comment]
Thank you, it looks good. 


Plus, when I tried to import and swap our token on Uniswap, the token image(logo) does not show up when it is imported. 
How can I fix this problem?

**Comment by Cryptocool1** [comment]
Please, try to ask Uniswap about it, everything is good from our side.

**Pull request closed without merging**
