### PR TITLE
Add POT info and logo

### PR DESCRIPTION
**Pull request by meta-point**

### CODE REVIEW

**Review by meta-point — COMMENTED** [review]
Delete invalid links

**Review by meta-point — COMMENTED** [review]
add liknks github

**Review by meta-point — COMMENTED** [review]
add medium link

**Comment by meta-point** [comment]
> As per our policy, brand new tokens are not included, there is a minimum requirement of 10,000 holder addresses and 15,000 transactions, in order to filter out scam tokens. See the criteria at : https://developer.trustwallet.com/assets/requirements .

There are over 3,000 token holders and over 60,000 transactions, so it fits the bill

**Comment by meta-point** [comment]
https://bscscan.com/token/0x3B5E381130673F794a5CF67FBbA48688386BEa86

This is the token information, please check
@Cryptocool1

**Comment by Cryptocool1** [comment]
Hello, you should have more than 10k holders

**Comment by meta-point** [comment]
> Hello, you should have more than 10k holders

[Cryptocool1](https://github.com/Cryptocool1)
I misread 1,000 as 10,000

**Pull request closed without merging**
