### PR TITLE
Add Miss Doge token (MDOGE) logo and info 

### PR DESCRIPTION
**Pull request by MissDoge**
We add Miss Doge token (MDOGE) to Trust Wallet
Contract: https://www.bscscan.com/token/0xA72Ff2B799324B042AE379809eE54dACE99db3A5
Audit: https://solidity.finance/audits/MissDoge/
More information: https://missdoge.net

### CODE REVIEW

**Comment by MissDoge** [comment]
Already paid in:
https://github.com/trustwallet/assets/pull/11704

**Comment by Cryptocool1** [comment]
Hello
• What is the purpose of this token? How will it benefit Trust Wallet users?
 • How is the token being distributed? Are you conducting an airdrop?
 • Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?
 • Is the token listed on a centralized/decentralized exchange?
 • Is a Smart Contract audit completed? Where can we find this information?

**Comment by MissDoge** [comment]
• What is the purpose of this token? How will it benefit Trust Wallet users?
This is meme coin, we are working hard to bring NFT game to MDoge holders.
• How is the token being distributed? Are you conducting an airdrop?
Token is distributed via DxSale from presale, we already have airdrop with 1% total supply
• Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?
Yes, we have a presale on DxSale
• Is the token listed on a centralized/decentralized exchange?
Already listed in PancakeSwap
• Is a Smart Contract audit completed? Where can we find this information?
Audit here: https://solidity.finance/audits/MissDoge/

**Comment by cryptomanz** [comment]
can you please add links to your PR?
example: https://developer.trustwallet.com/add_new_asset#info-json-contents

**Comment by cryptomanz** [comment]
fixed

**Pull request merged**
