### PR TITLE
Add BabyDoge ETH (BABYDOGE) (ERC20)

### PR DESCRIPTION
**Pull request by babydogecoingg**
Adding info for ERC20 token 'BabyDoge ETH (BABYDOGE)'.

PR created by <a href="https://assets.trustwallet.com">TW Assets Management</a>

### CODE REVIEW

**Comment by Cryptocool1** [comment]
hello
• What is the purpose of this token? How will it benefit Trust Wallet users?
 • How is the token being distributed? Are you conducting an airdrop?
 • Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?
 • Is the token listed on a centralized/decentralized exchange?
 • Is a Smart Contract audit completed? Where can we find this information?

**Comment by babydogecoingg** [comment]
• What is the purpose of this token? How will it benefit Trust Wallet users?
BabyDoge ETH serve two purposes for its creation. Its roadmap underline two Dapp for creation.

Dapp 1 which is BabyDoge Multi Transfer System which bulk processes transfers into a small number of transactions, and distributes tokens for minimal fees. This is currently under development.

Dapp 2 which is BabyDoge Swap which act similar to DEX Aggregators such as 1inch,  to connect the different ecosystem of crypto. BabyDoge Swap will be a decentralized exchange (DEX) aggregator that optimizes swaps
for users through better prices, limited gas fees, and lower slippage. BabyDoge Swap sources their liquidity from major DEXes such as Uniswap, Balancer, Curve, Kyber, JustSwap in addition to BabyDogeSwap, their professional Market Maker network. BabyDoge Swap is charging a minimal small fee to use and users can interact with it directly
on the BabyDoge Swap interface or through wallets such as Argent, Monolith, and Metamask.Fee earn by BabyDoge Swap will be used for marketing and buyback of BabyDoge Token.

This adding of BabyDoge ETH will benefit Trust Wallet Users to the online presence of our white paper, links, social media, and more so they can read, understand decentralisation, understand our roadmap and join us in building a stronger community for Crypto and understand crypto. 

• How is the token being distributed? Are you conducting an airdrop?
Token is being distributed through Uniswap V2, a decentralised exchange, we are not conducting an airdrop.

• Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?
No ICO or token presale.

• Is the token listed on a centralized/decentralized exchange?
It is listed on Uniswap (Decentralized Exchange). The link is as at https://app.uniswap.org/#/swap?inputCurrency=ETH&outputCurrency=0xac8e13ecc30da7ff04b842f21a62a1fb0f10ebd5&use=V2

• Is a Smart Contract audit completed? Where can we find this information?
Smart Contract audit is completed, you may find it at https://solidity.finance/audits/BabyDogeCoin/

**Comment by Cryptocool1** [comment]
baby doge is already existing token
are you the owner of baby doge ?
https://coinmarketcap.com/currencies/baby-doge-coin/

**Comment by babydogecoingg** [comment]
> baby doge is already existing token
> are you the owner of baby doge ?
> https://coinmarketcap.com/currencies/baby-doge-coin/

https://coinmarketcap.com/currencies/babydoge-coin/

Please check the above, we are two different thing, that one is binance chain, we are ethereum chain. and verified by coinmarket, gecko, etherscan, feixiaohao, and TpPocket

**Pull request merged**
