### PR TITLE
Add Cranch (BEP20)

### PR DESCRIPTION
**Pull request by cranchtoken**
Adding info for BEP20 token 'Cranch'.

PR created by <a href="https://assets.trustwallet.com">TW Assets Management</a>

### CODE REVIEW

**Comment by Cryptocool1** [comment]
11612 paid

**Comment by Cryptocool1** [comment]
can you answer some questions please?
• What is the purpose of this token? How will it benefit Trust Wallet users?
 • How is the token being distributed? Are you conducting an airdrop?
 • Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?
 • Is the token listed on a centralized/decentralized exchange?
 • Is a Smart Contract audit completed? Where can we find this information?

**Comment by cranchtoken** [comment]
1. CRANCH TOKEN is a decentralized cryptocurrency based on the blockchain
technology. The token crowdsale will raise funds to be used to build an
innovative gaming platform. It aims to solve trust issues in the online
gaming industry by using smart contracts and decentralization. The benefits
is, users can use our tokens to buy favorite items in our game, and our
game partner in the future
2. We do not airdrop, we sold tokens at an Initial Coin Offering (ICO)
3. Yes we sold tokens at the initial coin offering
4. For now we have not listed on centralized exchange, and we have not
added liquid in decentralized market, but someone has added liquid to be
traded (unofficial liquid)
5. Yes, our smart contract has been audited by techrate, you can see the
information here
https://github.com/TechRate/Smart-Contract-Audits/blob/main/Cranchtoken.pdf

**Comment by Cryptocool1** [comment]
can you please add links to your PR?
example: https://developer.trustwallet.com/add_new_asset#info-json-contents

**Comment by cranchtoken** [comment]
Yes, Done.

[image: image.png]

**Pull request merged**
