### PR TITLE
adding information and logo for O1T

### PR DESCRIPTION
**Pull request by Terryfolds**
this includes an info.json file and logo.png file for Only 1 Token

### CODE REVIEW

**Comment by Terryfolds** [comment]
this token is V2 and we initially airdropped 1:1 to our v1 holders to migrate to PCS V2.  We got our holders organically and here is our V1 contract for reference: https://bscscan.com/token/0x6cfeb2d07623fd884f525e7c33b6fc97147c4f41

**Comment by Cryptocool1** [comment]
hi there!
could you please answer some questions ?
• What is the purpose of this token? How will it benefit Trust Wallet users?
 • How is the token being distributed? Are you conducting an airdrop?
 • Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?
 • Is the token listed on a centralized/decentralized exchange?
 • Is a Smart Contract audit completed? Where can we find this information?

**Comment by Terryfolds** [comment]
Hello,
O1T serves as the utility token for trackbsc.com which is our BSC token
tracking app as well as for our upcoming BSC wallet portfolio tracker. it
will benefit trust wallet users by allowing them to easily connect their
wallet to our website and view information about all of the BSC tokens they
hold and easily trade them.

This token was released through a pancakeswap fair launch originally and
then we upgraded to our current contract when migrating to pancakeswap V2
and airdropped all of our original holders 1:1.

There was no presale or ICO, the entire supply was initially sent to
Pancakeswap as liquidity for a fair launch

This token is listed exclusively at Pancakceswap

We have had our contract audited by techrate and you can see their report
at https://only1token.com/audit.pdf

Thanks,
Terry

**Comment by Cryptocool1** [comment]
can you please add links to your PR?
example: https://developer.trustwallet.com/add_new_asset#info-json-contents

**Comment by Cryptocool1** [comment]
can you please remove "www" from the links?

**Comment by Terryfolds** [comment]
I have removed www from any links

**Comment by Terryfolds** [comment]
Have the criteria changed? I am seeing that it wants us to have 5000 holders now? I am also unsure what the reddit link issue is.

**Comment by Cryptocool1** [comment]
> Have the criteria changed? I am seeing that it wants us to have 5000 holders now? I am also unsure what the reddit link issue is.

its ok for you

**Comment by Terryfolds** [comment]
Ok i have updated links to match criteria.

**Comment by Cryptocool1** [comment]
'Links field 'reddit': 'https://redditX.com/r/only1token' must start with 'https://reddit.com/'.

**Comment by Terryfolds** [comment]
ok I have changed it back

**Comment by Cryptocool1** [comment]
don't know what the problem is.
could you remove reddit please?

**Comment by Terryfolds** [comment]
ok, i have removed reddit.

**Comment by Cryptocool1** [comment]
thanks

**Pull request merged**
