### PR TITLE
Add DELOT (BEP20) token

### PR DESCRIPTION
**Pull request by delot-io**
Adding logo and info for DELOT (BEP20) token.

### CODE REVIEW

**Comment by Cryptocool1** [comment]
• What is the purpose of this token? How will it benefit Trust Wallet users?
 • How is the token being distributed? Are you conducting an airdrop?
 • Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?
 • Is the token listed on a centralized/decentralized exchange?
 • Is a Smart Contract audit completed? Where can we find this information?

**Comment by delot-io** [comment]
> 

1. DELOT is the native token of DELOT.IO – a decentralized lottery game.
It is a BEP-20 token and Trust Wallet users can buy, sell, stake, farming and join our DApp.
Users of Trust Wallet open the website in the wallet and can directly connect to use it, which is very convenient.

2. The token distribution can be found on our Whitepaper: https://docs.delot.io/tokenomics/token-distribution

3. The token was sold through Presale: https://www.pinksale.finance/#/launchpad/0x2467f5a0cF21E21388EC3F7312C4FCA392D27C2d?chain=BSC

4. The token was listed on:
- PancakeSwap: https://pancakeswap.finance/info/token/0x3e24bbb2c9a0f2faecfdbdca20bba6f35b73c4cb
- CoinTiger: https://www.cointiger.com/en-us/#/trade_center?coin=delot_usdt
For more info, you may refer to: https://coinmarketcap.com/currencies/delot-io/

5. The smart contract is audited by SolidProof:
https://github.com/solidproof/projects/blob/main/Delot/SmartContract_Audit_Solidproof_Delot.pdf

@Cryptocool1

**Comment by cryptomanz** [comment]
Your logo should be a full screen

**Comment by delot-io** [comment]
@cryptomanz Logo has been updated.

**Pull request merged**
