### PR TITLE
Add MUSO Finance (BEP20)

### PR DESCRIPTION
**Pull request by MUSOFinance**
Adding info for BEP20 token 'MUSO Finance'.

PR created by <a href="https://assets.trustwallet.com">TW Assets Management</a>

### CODE REVIEW

**Comment by Cryptocool1** [comment]
As per our policy, brand new tokens are not included, there is a minimum requirement of 5000 holder addresses and 10000 transactions, in order to filter out scam tokens.
See the criteria at (mentioned in the first message by the bot): https://community.trustwallet.com/t/how-to-submit-a-token-logo/3863).

**Comment by MUSOFinance** [comment]
Hi, You also mention 'This requirement is subject for review based on the project.'.Could you please provide me with what basis we have been declined on due to our 'project' not meeting the criteria. Kind regards, Alex ---- On Mon, 09 Aug 2021 22:30:02 +0100  ***@***.***  wrote ----
As per our policy, brand new tokens are not included, there is a minimum requirement of 5000 holder addresses and 10000 transactions, in order to filter out scam tokens.
See the criteria at (mentioned in the first message by the bot): https://community.trustwallet.com/t/how-to-submit-a-token-logo/3863).

**Comment by Cryptocool1** [comment]
• Is a Smart Contract audit completed?

**Comment by MUSOFinance** [comment]
Unfortunately not but only due to the fact I see no benefit whatsoever in it. If I'm honest some of the biggest rug pulls I've been involved in have been audited. Surely there should be a broader criteria that that, we're actually set up as a UK Ltd company with an innovative app in the design process. Myself and my colleague actually work in the music industry and plan on creating a link in an industry that renders unfair to artists.  ---- On Thu, 12 Aug 2021 10:35:24 +0100  ***@***.***  wrote ----

• Is a Smart Contract audit completed?

**Comment by Cryptocool1** [comment]
Awaiting for smart contract audit

**Comment by MUSOFinance** [comment]
Hey, Please find our Techrate Audit within the below link. https://github.com/TechRate/Smart-Contract-Audits/blob/main/August/MUSO%20Finance%20Full%20Smart%20Contract%20Security%20Audit.pdfKind regards, Alex ---- On Sat, 21 Aug 2021 08:40:40 +0100  ***@***.***  wrote ----
Awaiting for smart contract audit

**Comment by MUSOFinance** [comment]
Hey,Please find in the below link our Techrate contract audit. https://github.com/TechRate/Smart-Contract-Audits/blob/main/August/MUSO%20Finance%20Full%20Smart%20Contract%20Security%20Audit.pdfKind regards, Alex ---- On Thu, 12 Aug 2021 10:35:24 +0100  ***@***.***  wrote ----

• Is a Smart Contract audit completed?

**Comment by Cryptocool1** [comment]
can't access to your audit. please check

**Comment by MUSOFinance** [comment]
Please find the audit attached.The below link seems to be working for me. https://github.com/TechRate/Smart-Contract-Audits/blob/648ae0e43da8a2b21551fb44198ff322548c08f6/August/MUSO%20Finance%20Full%20Smart%20Contract%20Security%20Audit.pdf ---- On Sun, 22 Aug 2021 12:51:05 +0100  ***@***.***  wrote ----
can't access to your audit. please check

**Comment by MUSOFinance** [comment]
P

**Comment by MUSOFinance** [comment]
Hey, Is there any update on this please? Kind regards, Alex ---- On Sun, 22 Aug 2021 12:51:05 +0100  ***@***.***  wrote ----
can't access to your audit. please check

**Pull request merged**
