### PR TITLE
Update ZCX token logo and info

### PR DESCRIPTION
**Pull request by minapham17**
Update new token info and logo for ZCX token

### CODE REVIEW

**Comment by Cryptocool1** [comment]
As per our policy, there is a minimum requirement of 10,000 holder addresses and 15,000 transactions, in order to filter out scam tokens.
See the criteria at : https://developer.trustwallet.com/listing-new-assets/requirements .

**Comment by BojanPi** [comment]
> As per our policy, there is a minimum requirement of 10,000 holder addresses and 15,000 transactions, in order to filter out scam tokens. See the criteria at : https://developer.trustwallet.com/listing-new-assets/requirements .

Hi there sir, since this is far from a new token/project, and we're asking only to update the logo (no way to scam anyone in any way possible) - can we skip the number of holders req? Especially since we have ~140k of transactions (without transaction on Polygon).

If you do 2min research on us, you'll see that we have business deals with a lot of recognized projects in crypto, and also that we have constant releases along with very vibrant community

Waiting on your feedback, and thank you in advance!

Bojan

**Comment by Cryptocool1** [comment]
Could you please provide an official announcement about rebranding?

**Comment by martin-zencex** [comment]
https://www.unizen.io/blog/post/unveiling-unizen-stratosphere-v2-a-pinnacle-of-decentralized-finance-and-trading

**Comment by BojanPi** [comment]
> Could you please provide an official announcement about rebranding?

https://www.unizen.io/blog/post/unveiling-unizen-stratosphere-v2-a-pinnacle-of-decentralized-finance-and-trading

https://twitter.com/unizen_io/status/1713579042153312678

https://twitter.com/unizen_io/status/1719103300820459969

And you can refer to CMC also, we've changed our logo with them: https://coinmarketcap.com/currencies/unizen/

logo128px

**Pull request merged**
