### PR TITLE
Add Biconomy Token (BEP20)

### PR DESCRIPTION
**Pull request by Sparknzz**
Adding info for BEP20 token 'Biconomy Token'.

PR created by <a href="https://assets.trustwallet.com">TW Assets Management</a>

### CODE REVIEW

**Comment by nypzxy** [comment]
Fee paid. Please check on it thanks.
TxHashA243478BC5ACD9861684211B317D60DCB99EC28A8638332ABC970E28C55788C0

**Comment by cryptomanz** [comment]
Hello,
Can your answer some questions?
• What is the purpose of this token? How will it benefit Trust Wallet users?
 • How is the token being distributed? Are you conducting an airdrop?
 • Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?
 • Is the token listed on a centralized/decentralized exchange?
 • Is a Smart Contract audit completed? Where can we find this information?

**Comment by nypzxy** [comment]
What is the purpose of this token? How will it benefit Trust Wallet users?
- As the token is represents for our exchange, so it will help user to understand our exchange and we are very welcome for all  Trust Wallet user to join.

How is the token being distributed? Are you conducting an airdrop?
- We haven't conducted any airdrop till now. but will launch a airdrop on CMC soon.

Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?
- No presale.

Is the token listed on a centralized/decentralized exchange?
- Yes on PancakeSwap.

Is a Smart Contract audit completed? Where can we find this information?
- No.

Is a Smart Contract audit completed? Where can we find this information?
- Not yet. Will fill it out then.

**Comment by cryptomanz** [comment]
Awaiting for smart contract audit.

**Comment by Cryptocool1** [comment]
please create new PR, when smart contract audit will be ready. Make sure to mention this PR, so the fee can be reused.

**Pull request closed without merging**
