### PR TITLE
Black Diamond Logo & Info

### PR DESCRIPTION
**Pull request by CRuzylo**
Initial fork for Black Diamond Gold Logo & Info for Trust Wallet

https://coinmarketcap.com/currencies/black-diamond/
https://www.coingecko.com/en/coins/black-diamond

### CODE REVIEW

**Review by CRuzylo — COMMENTED** [review]
Adjusted line 7.

**Comment by Cryptocool1** [comment]
hello,
some mistakes
info.json must start with { 
and remove please from decimals "12" -- ""

**Comment by Cryptocool1** [comment]
or you can create new PR
go to https://assets.trustwallet.com, log on with Github, enter contract ID, logo and some additional info, and it will create a PR for you.
See https://community.trustwallet.com/t/how-to-submit-a-token-logo-using-assets-app/82957.

**Comment by CRuzylo** [comment]
> or you can create new PR
> go to https://assets.trustwallet.com, log on with Github, enter contract ID, logo and some additional info, and it will create a PR for you.
> See https://community.trustwallet.com/t/how-to-submit-a-token-logo-using-assets-app/82957.

Resubmitted via Trust. Paid

**Pull request closed without merging**
