### PR TITLE
0x248aDE18435f7B5E39d855CC98C42D8f6840a386

### PR DESCRIPTION
**Pull request by acashcoin**
logo
please update Orbit logo
contract
https://etherscan.io/token/0x248aDE18435f7B5E39d855CC98C42D8f6840a386

### CODE REVIEW

**Comment by acashcoin** [comment]
hello ,
any error here ?

**Comment by acashcoin** [comment]
hello ,
any error here ?

**Comment by acashcoin** [comment]
ear sir,
we need to update the logo

**Comment by kolya182** [comment]
Added

**Pull request closed without merging**
