### PR TITLE
Add Kiba Inu (ERC20)

### PR DESCRIPTION
**Pull request by ghost**
Adding info for ERC20 token 'Kiba Inu'.

PR created by <a href="https://assets.trustwallet.com">TW Assets Management</a>

### CODE REVIEW

**Comment by Cryptocool1** [comment]
• What is the purpose of this token? How will it benefit Trust Wallet users?
 • How is the token being distributed? Are you conducting an airdrop?
 • Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?
 • Is the token listed on a centralized/decentralized exchange?
 • Is a Smart Contract audit completed? Where can we find this information?

**Comment by bagidir1997** [comment]
hello!
Here is answers for your questions
-We will benefit Trust Wallet users by our great growth potential also the majority off our users use Trust Wallet. 
We will continue to push marketing and exposure for all our holders and users.
- The token has not been distributed prior by Airdrop.
- We are currently listed on Uniswap&Pancakeswap V2
-https://www.certik.com/projects/kibainu

**Comment by bagidir1997** [comment]
can you please change logo because corners not look good

**Comment by bagidir1997** [comment]
logo

**Pull request merged**
