### PR TITLE
Update info and logo for Prosper (PROS) on Ethereum and BSC

### PR DESCRIPTION
**Pull request by prosper-fi**
Updating info and logo for ERC20 token 'Prosper' (PROS) and BEP20 token 'Prosper' (PROS).

### CODE REVIEW

**Review by Machinediablos — COMMENTED** [review]
High

**Comment by prosper-fi** [comment]
@Cryptocool1 please let us know if you have any questions or need more info for this update of existing tokens.

Appreciate your help!

**Comment by Cryptocool1** [comment]
Hello, 
• What is the purpose of this token? How will it benefit Trust Wallet users?
 • How is the token being distributed? Are you conducting an airdrop?
 • Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?
 • Is the token listed on a centralized/decentralized exchange?
 • Is a Smart Contract audit completed? Where can we find this information?

**Comment by prosper-fi** [comment]
Hi @Cryptocool1, please find responses below. Let us know if you need more information.

**What is the purpose of this token? How will it benefit Trust Wallet users?**
The token is already on Trust Wallet and in the repo. We are just updating the information and logo as the project has had a change in strategic direction in October. 

Prosper is a decentralized protocol built for a community dedicated to Bitcoin. It bridges institutional-level Bitcoin mining power to the blockchain and aims to unlock new possibilities through liquidity farming.

The protocol’s native token, PROS, is an ERC-20 token offering multiple benefits. Prosper’s DAO foundation owns Bitcoin miners that generate Bitcoin rewards for PROS holders. Additionally, PROS serves as a governance token, enabling holders to vote on key proposals and influence the protocol’s direction. Active participants can also stake their PROS tokens to earn Bitcoin rewards and access benefits from ecosystem partners.

**How is the token being distributed? Are you conducting an airdrop?**
N/A, this is an existing token, just updating information and token image.

**Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?**
N/A, this is an existing token, just updating information and token image.

**Is the token listed on a centralized/decentralized exchange?**
Yes, the token is available on Binance, Bitget, Bybit, Gate.io, MEXC, PancakeSwap, Uniswap.

**Is a Smart Contract audit completed? Where can we find this information?**
N/A, this is an existing token, just updating information and token image. Contract is verified on both Etherscan and BSCscan.

**Comment by prosper-fi** [comment]
Hi @Cryptocool1, we've recently conducted a token contract upgrade swap for $PROS. What's the best way for us to associate our token details to the new contract addresses? Our info is already updated on CMC: https://coinmarketcap.com/currencies/prosper/. Major exchanges (including Binance) have also helped to complete the contract swap already too.

**Upgraded addresses:** 

Ethereum: 0x915424Ac489433130d92B04096F3b96c82e92a9D
BNB Smart Chain (BSC): 0x915424Ac489433130d92B04096F3b96c82e92a9D

**Old addresses:** 

Ethereum: 0x8642a849d0dcb7a15a974794668adcfbe4794b56
BNB Smart Chain (BSC): 0xed8c8aa8299c10f067496bb66f8cc7fb338a3405

**Pull request merged**
