### PR TITLE
Add Fairface Token (BEP20)

### PR DESCRIPTION
**Pull request by CMNOfficial**
Adding info for BEP20 token 'Fairface Token'.

PR created by <a href="https://assets.trustwallet.com">TW Assets Management</a>

### CODE REVIEW

**Comment by CMNOfficial** [comment]
Hello, 
this is our Old reference https://github.com/trustwallet/assets/pull/18452
We already paid fees

**Comment by CMNOfficial** [comment]
• What is the purpose of this token? How will it benefit Trust Wallet users?
Fairface FAF token is is a reward token for the customers who write reviews on Fairface platform. The rewarded FAF token can be transferred to customer wallets including Trust wallet users. 
• How is the token being distributed? Are you conducting an airdrop?
We have distributed tokens in Pre-sale and also will distribute in future Airdrops. 
Yes, we are conducting an airdrop at the moment and expect to distribute tokens to 10,000 users holding accounts in Trustwallet or metamask.
• Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?
Yes, we sold tokens in presale.
• Is the token listed on a centralized/decentralized exchange?
Token will be listed soon, currently we are doing IEO sale on Probit Global exchange https://www.probit.com/en-us/ieo/faf-round1/0
• Is a Smart Contract audit completed? Where can we find this information?
Yes, The Audit is done by Certik. https://www.certik.com/projects/fairface

**Comment by CMNOfficial** [comment]
Pls update logo at Trust wallet and pls considers old reference #18452 and also ping us if any query

**Comment by ramsty** [comment]
Hi,
Your logo should be a full screen 256*256 px. Please change.

**Comment by CMNOfficial** [comment]
Hi,
Pls Find attached Logo file of 256*256 px and pls update this to Fairface
token
Our github pool id is - 18899
https://github.com/trustwallet/assets/pull/18899

Thanks

**Comment by CMNOfficial** [comment]
> Hi, Your logo should be a full screen 256*256 px. Please change.

[](url
FAF256
)

**Comment by CMNOfficial** [comment]
> ### PR Summary
> Files OK: 2 Token in PR: **BEP20** 0xe65313B085258a671d044F7Ad9D9fcd514c5d9e9 Symbol: **FAF** decimals: 18 Links: [Logo](https://raw.githubusercontent.com/CMNOfficial/assets/br0311-142329/blockchains/smartchain/assets/0xe65313B085258a671d044F7Ad9D9fcd514c5d9e9/logo.png) [Info](https://raw.githubusercontent.com/CMNOfficial/assets/br0311-142329/blockchains/smartchain/assets/0xe65313B085258a671d044F7Ad9D9fcd514c5d9e9/info.json) [Website](https://www.fairface.io/) [Explorer](https://bscscan.com/token/0xe65313B085258a671d044F7Ad9D9fcd514c5d9e9) Tags: defi Token check error: ❌ number of holders not checked: please, check it manually
> 
> 
Reply 
https://bscscan.com/token/0xe65313B085258a671d044F7Ad9D9fcd514c5d9e9a

 can you check manually, we have 26200 holders write now
thanks

**Comment by 406712774** [comment]
Yo boy a pedir mi reembolso XK yo la cansele desde ayer y tengo pruebas de
eso

**Comment by 406712774** [comment]
Kien les autorizo Bender yono  por favor déjenme todo ensu lugar yo calsele
la suspensión

**Pull request merged**
