### PR TITLE
Coins update

### PR DESCRIPTION
**Pull request by echapeta**
Maximum PR age reached, auto-closing PR  (60 vs. 60 hrs)

### CODE REVIEW

**Comment by echapeta** [comment]
Hello,

 

Where can I buy the TWT?

I think I will pay with ETH.

 

Thank You.

 

 

 

Eduardo G. Chapeta

CEO

Interwave Global

www.iw-global.com

**Comment by kolya182** [comment]
@echapeta You can buy `TWT` here https://www.coingecko.com/en/coins/trust-wallet-token#markets or you can pay `0.08 ETH` to https://etherscan.io/address/0xB46224E545c3F1Fa4D05f94465D13f777866a77B

**Comment by echapeta** [comment]
Thank You!

 

 

 

Eduardo G. Chapeta

CEO

Interwave Global

www.iw-global.com

**Comment by echapeta** [comment]
Hello,

 

I just paid 0.08 ETH to 0xB46224E545c3F1Fa4D05f94465D13f777866a77B at the transaction 

 

https://u9455015.ct.sendgrid.net/ls/click?upn=WNbsy6qFrPkVfeApOza7cKHZ69Qw1a8iakxIeN4-2BDUFMSHHOvcIfvlpGoXB8itlIBQDTH-2F0RES7HSsjD7R9lonbTjY7fTMqbqHaHCm7L7RQXp-2FUxZXbemec-2FvJ3Og4I75HVRFjFx2kT-2BErH-2BWxTM3Q-3D-3Duwfp_U31jt5HgHBh7k3Grc5s4l-2FGnUK9RxTT6LH-2B5iHc6VsPCSriC-2BLtAhnvxZcdocGwKvznYVsl0Ow-2F3EzdiEdFUXfBX6VDg722xMhvy6-2BeGD8pw4QkV0QD1eTn4N4NyV0kHPaCQYWywiZMNVFpca1iuq3Q2KCNh7rE79VrN4SHLSOS-2BD2ocpwFQ6thtS5wobCx6NoxnTP4ZmJW9MRAupfCKkgDa-2B-2FjXKcfgkEH5dOd0qmg2H5qWtYVuzoXlSZfMWa5d7bAq4qC4pzRG4eJHNyX5Lg-3D-3D

 

Thank You,

 

 

 

Eduardo G. Chapeta

CEO

Interwave Global

www.iw-global.com

**Comment by echapeta** [comment]
Hello,

 

I just paid 0.08 ETH to 0xB46224E545c3F1Fa4D05f94465D13f777866a77B at the transaction 

 

https://etherscan.io/tx/0x8593780c5301475f13cf1e624e8e758073750e62963925c9134a2c031d73c46d

 

Thank You,

 

 

 

Eduardo G. Chapeta

CEO

Interwave Global

www.iw-global.com

**Comment by echapeta** [comment]
Hello,

 

When you expect to have the update committed?

 

Thank You,

 

 

 

Eduardo G. Chapeta

CEO

Interwave Global

www.iw-global.com

 

 

From: Eduardo Chapeta <echapeta@iw-global.com> 
Sent: Thursday, May 7, 2020 09:19
To: 'trustwallet/assets' <reply@reply.github.com>; 'trustwallet/assets' <assets@noreply.github.com>
Cc: 'Mention' <mention@noreply.github.com>
Subject: RE: [trustwallet/assets] Coins update (#2030)

 

Hello,

 

I just paid 0.08 ETH to 0xB46224E545c3F1Fa4D05f94465D13f777866a77B at the transaction 

 

https://u9455015.ct.sendgrid.net/ls/click?upn=WNbsy6qFrPkVfeApOza7cKHZ69Qw1a8iakxIeN4-2BDUFMSHHOvcIfvlpGoXB8itlIBQDTH-2F0RES7HSsjD7R9lonbTjY7fTMqbqHaHCm7L7RQXp-2FUxZXbemec-2FvJ3Og4I75HVRFjFx2kT-2BErH-2BWxTM3Q-3D-3De-B7_U31jt5HgHBh7k3Grc5s4l-2FGnUK9RxTT6LH-2B5iHc6VsPCSriC-2BLtAhnvxZcdocGwKvznYVsl0Ow-2F3EzdiEdFUXfBX6VDg722xMhvy6-2BeGD8oPPkvokn2lwowuNgUzsaAPvELf29TYPQAd5YPYz6ov-2BrzxCrikrjirr2Kd4KwL-2F2yzU977wePOC8oBhnw3UJ3vt4v3uv7Xjwjee0fab8O8bIjxcjopSsbRvQJ4DM-2FmyxyTEY-2B86b-2FtYhPXTQM9juO1v5wWdKiHF2SMIrbP6DQ-2FNqm5uuUlf05f82ZYyIIl7sgip6JFtcpdr2Om9tq5SAmm

 

Thank You,

 

 

 

Eduardo G. Chapeta

CEO

Interwave Global

www.iw-global.com

**Comment by echapeta** [comment]
Hello,

 

When you expect to have the update committed?

 

Thank You,

 

 

 

Eduardo G. Chapeta

CEO

Interwave Global

www.iw-global.com

 

 

From: Eduardo Chapeta <echapeta@iw-global.com> 
Sent: Thursday, May 7, 2020 09:19
To: 'trustwallet/assets' <reply@reply.github.com>; 'trustwallet/assets' <assets@noreply.github.com>
Cc: 'Mention' <mention@noreply.github.com>
Subject: RE: [trustwallet/assets] Coins update (#2030)

 

Hello,

 

I just paid 0.08 ETH to 0xB46224E545c3F1Fa4D05f94465D13f777866a77B at the transaction 

 

https://etherscan.io/tx/0x8593780c5301475f13cf1e624e8e758073750e62963925c9134a2c031d73c46d

 

Thank You,

 

 

 

Eduardo G. Chapeta

CEO

Interwave Global

www.iw-global.com

**Comment by echapeta** [comment]
Hello,

 

When you expect to have the update committed?

 

Thank You,

 

 

 

Eduardo G. Chapeta

CEO

Interwave Global

www.iw-global.com

 

 

From: Eduardo Chapeta <echapeta@iw-global.com> 
Sent: Thursday, May 7, 2020 09:19
To: 'trustwallet/assets' <reply@reply.github.com>; 'trustwallet/assets' <assets@noreply.github.com>
Cc: 'Mention' <mention@noreply.github.com>
Subject: RE: [trustwallet/assets] Coins update (#2030)

 

Hello,

 

I just paid 0.08 ETH to 0xB46224E545c3F1Fa4D05f94465D13f777866a77B at the transaction 

 

https://u9455015.ct.sendgrid.net/ls/click?upn=WNbsy6qFrPkVfeApOza7cKHZ69Qw1a8iakxIeN4-2BDUFMSHHOvcIfvlpGoXB8itlIBQDTH-2F0RES7HSsjD7R9lonbTjY7fTMqbqHaHCm7L7RQXp-2FUxZXbemec-2FvJ3Og4I75HVRFjFx2kT-2BErH-2BWxTM3Q-3D-3DI7a1_U31jt5HgHBh7k3Grc5s4l-2FGnUK9RxTT6LH-2B5iHc6VsPCSriC-2BLtAhnvxZcdocGwKvznYVsl0Ow-2F3EzdiEdFUXfBX6VDg722xMhvy6-2BeGD8rZN08aG7H-2B3iNB9yss4JtbAJftrYdQm4NA-2FSHJThQ-2B7UWHzXepba3vNqSvV6K5ExrMEbQXTDgtChqQHbBMNK9TziWQ5tXh9snM8KQYedPmqPGFIwo5AqCCY0rbvQtpPgPal6uS6YdfpkQKuT-2FXWBOBHffZs0kNVtzLFXnJlnPfx9O2v5hi1plD73pDhM3ixbw-3D

 

Thank You,

 

 

 

Eduardo G. Chapeta

CEO

Interwave Global

www.iw-global.com

**Pull request closed without merging**
