### PR TITLE
Add BEP20 TreatDAO

### PR DESCRIPTION
**Pull request by samadsajanlal**
https://bscscan.com/token/0xac0C7d9B063eD2C0946982dDB378e03886C064E6

### CODE REVIEW

**Comment by catenocrypt** [comment]
As per our policy, brand new tokens are not included, there is a minimum requirement of 2500 holder addresses and 5000 transactions, in order to filter out scam tokens.
See the criteria at (mentioned in the first message by the bot): https://community.trustwallet.com/t/how-to-submit-a-token-logo/3863).
This token has below-limit usage yet (1045 holders). Puttin PR on hold for now. Please come back to us when all criteria are met.  Multi-chain and staking tokens may get special treatment, let us know if this is the case. 

https://bscscan.com/token/0xac0C7d9B063eD2C0946982dDB378e03886C064E6

**Comment by samadsajanlal** [comment]
Hi @catenocrypt - how old does the token need to be in order for a potential exemption of the 2500 holders requirement? As of now the token is approximately 2 weeks old, has a dedicated team, and they have advised me that they are expecting to launch a MVP in the very near future to attract interest in the project.

**Comment by catenocrypt** [comment]
Just being X weeks old does not tell much, sorry...
Holder count is increasing, as I see, so let's see how does it go.

**Comment by Cryptocool1** [comment]
Hello,
As per our policy, there is a minimum requirement of 2500 holder addresses and 5000 transactions.
This token has no real usage yet (1,782 holders). Closing PR for now. Please come back to us when all criteria are met.

**Comment by samadsajanlal** [comment]
@Cryptocool1 i don't agree with this closure. The project is gaining users and and we paid the review fee - they don't want to pay again when they have 2500 holders.

**Comment by zachzwei** [comment]
The request can be reopened and no need to pay again.

**Pull request closed without merging**
