### PR TITLE
Add Fireball (FIRE) logo on trust wallet apps

### PR DESCRIPTION
**Pull request by Fireball44**
Add Fireball (FIRE) logo on trust wallet apps 

Token Name : Fireball
Token symbol : FIRE
Token supply :48,174.924984850504621656
Token Decimals:18
Token contract address : 0x3F8A2f7bcD70e7F7Bdd3FbB079c11d073588DEA2

0x3F8A2f7bcD70e7F7Bdd3FbB079c11d073588DEA2

### CODE REVIEW

**Comment by Fireball44** [comment]
07DD0081C0BE4F01BEA93D337186485866679D8A00079533766E6317D1DA28D8

**Comment by Fireball44** [comment]
Payment is done

**Comment by Fireball44** [comment]
Logo is not showing 

Screenshot_2020-07-17-18-23-06-258_com wallet crypto trustapp

**Comment by catenocrypt** [comment]
For me it shows right now.  Allow a few hours for cache updates.

**Pull request merged**
