### PR TITLE
Medacoin Logo submission

### PR DESCRIPTION
**Pull request by FullyVoxxed**
Medacoin (by Medabots) is a new cryptocurrency that gives users the ability to manage their virtual in-game goods.

### CODE REVIEW

**Comment by FullyVoxxed** [comment]
Ill be here if you need something fixed, thanks!

**Comment by Cryptocool1** [comment]
hello,
• What is the purpose of this token? How will it benefit Trust Wallet users?
 • How is the token being distributed? Are you conducting an airdrop?
 • Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?
 • Is the token listed on a centralized/decentralized exchange?
 • Is a Smart Contract audit completed? Where can we find this information?

**Comment by FullyVoxxed** [comment]
Hello this token is going to be inside of the new Medabots mobile game launching Christmas time this year. We have a lot of trust wallet holders eager to see the price and logo of this amazing token. Airdrops were done on launch for private sale holders all airdrops are complete no more will be done. Token hit BSCPAD and DXsale then public launched onto pancake swap
There was a pre sale of 1500 BNB - 900 went to LQ, 300 went to the Console game development, and 300 went to pre and post marketing on the project.
We are listed on pancake swap right now we have submitted application for Binance and are in talks with a few tier 1 exchanges. We have Lbank we are looking at closely and almost have a deal set.
Techrate audit is complete which I can provide.

**Comment by FullyVoxxed** [comment]
[MedacoinTechRateAudit.pdf](https://github.com/trustwallet/assets/files/7206971/MedacoinTechRateAudit.pdf)

**Pull request merged**
