### PR TITLE
Adding our Companies new Token eRSDL for Uniswap and hopefully TrustW…

### PR DESCRIPTION
**Pull request by ryanmmmmm**
We are listed on coingecko:

https://www.coingecko.com/en/coins/unfederalreserve

I believe we now meet all your requirements

https://www.unfederalreserve.com/

The eRSDL ecosystem is like a safe-harbor where sophisticated parties are the "pricing oracles" and ordinary people can participate alongside with a reduced chance of being gamed by experts.

https://www.residualtoken.com/

### CODE REVIEW

**Comment by catenocrypt** [comment]
Please rename the logo file to `logo.png` (from circle-cropped.png).

**Comment by ryanmmmmm** [comment]
fixed!!!!

**Comment by ryanmmmmm** [comment]
are we good? will send payment!!

**Comment by catenocrypt** [comment]
There is one more issue: the JSON file is invalid, because of quote issues.  Remove double quotes from the text of short_description.

```
"short_description": "The eRSDL ecosystem is like a safe-harbor where sophisticated parties are the "pricing oracles" and ordinary people can participate alongside with a reduced chance of being gamed by experts.",
```

```
"short_description": "The eRSDL ecosystem is like a safe-harbor where sophisticated parties are the `pricing oracles` and ordinary people can participate alongside with a reduced chance of being gamed by experts.",
```

**Comment by ryanmmmmm** [comment]
ok the json is fixed (embarrassed!!).

here is the payment TXN:

https://explorer.binance.org/tx/36CC3B0B9A30ABBA114B363FEF4F8EDA3BC5B296E2830E66E13F429BAEC908E9

**Pull request merged**
