### PR TITLE
Token Migration

### PR DESCRIPTION
**Pull request by shibamaskcoin**
We Migrated to New Contract and Name How can we Update this in Trustwallet

https://coinmarketcap.com/currencies/shibamask/

### CODE REVIEW

**Comment by shibamaskcoin** [comment]
do we need to pay again in case of migration

**Comment by shibamaskcoin** [comment]
please check pull request #24018 
do we have to pay again if token contract is migrated ?

**Comment by cryptomanz1** [comment]
Can you send your old contract?

**Comment by shibamaskcoin** [comment]
> Can you send old contract?
0x9105f25a9d6b3d289cc7315b0b4e0b91f3806fb1
(https://coinmarketcap.com/currencies/shibamask/ )

**Comment by Cryptocool1** [comment]
Please create new PR, follow doc https://developer.trustwallet.com/assets/requirements
You may want to try our Assets app in beta; go to https://assets.trustwallet.com, log on with Github, enter contract ID, logo and some additional info, and it will create a PR for you.
See https://developer.trustwallet.com/assets/repository_details

**Comment by shibamaskcoin** [comment]
> Please create new PR, follow doc https://developer.trustwallet.com/assets/requirements You may want to try our Assets app in beta; go to https://assets.trustwallet.com, log on with Github, enter contract ID, logo and some additional info, and it will create a PR for you. See https://developer.trustwallet.com/assets/repository_details

Do we need to pay again  for this migration ?

**Pull request closed without merging**
