### PR TITLE
Add Logo to Trust

### PR DESCRIPTION
**Pull request by trubadger**
This PR is being closed due to inactivity. If you wish to continue, please have us reopen the PR before sending your payment, or just create a new one.
Do NOT send payments for closed PR, as the fee may by lost!
  (87 vs. 48 hrs)

### CODE REVIEW

**Comment by Cryptocool1** [comment]
Please create new PR, follow doc https://community.trustwallet.com/t/how-to-submit-a-token-logo/3863
You may want to try our new Assets app in beta; go to https://assets.trustwallet.com, log on with Github, enter contract ID, logo and some additional info, and it will create a PR for you.
See https://community.trustwallet.com/t/how-to-submit-a-token-logo-using-assets-app/82957.

**Comment by trubadger** [comment]
Please reopen and help us get this submitted. We paid with memo 1110. There's no activity because no one is responding with what we should do. We have submitted numerous times, corrected syntax, done everything asked.

**Comment by RebelByCause** [comment]
@Cryptocool1 @cryptomanz

Can you please reopen this PR and manually approve the payment. PR got closed while we already paid the contribution.

https://explorer.binance.org/tx/5B3AEE89F6697B096A7FE232D945D0A7218A8FCABB8E873511CCF318FCCAFE5C

Thanks.

TruBadger Team

**Comment by RebelByCause** [comment]
@Cryptocool1 @cryptomanz 

Can you please reopen this PR and manually approve the payment. Payment is done with memo 1110.

Thanks in advance.

TruBadger Team

**Pull request closed without merging**
