### PR TITLE
Add CATVILLS (BEP20)

### PR DESCRIPTION
**Pull request by PrincessOnTop**
This request is to add CATVILLS (BEP20) logo and information on Trust Wallet.
Catvills project description:
 Catvills is a community build platform with various utilities. Catvills is providing a platform that will increase value that is realistic and will be felt by its holders, by marketing and achieving its goals. This is the anchor on why we created Catvills, and with Catvills creating events and charity for cats all around the world. These are our realistic steps to give back and one of our main functions for Catvills.
**Smart Contract is Audited by InterFi**: https://github.com/interfinetwork/smart-contract-audits/blob/audit-updates/CatvillsCoin_0xa531a733070a5fF4866D1327d82e403Fa35290A6.pdf
**CoinMarketCap page**: https://coinmarketcap.com/currencies/catvills-coin/
**Coingecko page**: https://www.coingecko.com/en/coins/catvills-coin
**Utilities**:
https://stake.catvillscoin.com/
https://catvillscoinswap.com/#/swap

### CODE REVIEW

**Comment by PrincessOnTop** [comment]
Hello,
We have provided all the information in the description of this pull request.
Please, kindly let us know if we meet the requirements in order to proceed with the payment.
Thank you.

**Comment by PrincessOnTop** [comment]
Hello Cryptocool1,
Can you inform us if we are good to go with the payment? 
Thank you.

**Comment by Cryptocool1** [comment]
Hello! 
submission looks good, awaiting for fee payment

**Comment by PrincessOnTop** [comment]
> Hello! submission looks good, awaiting for fee payment

Thank you!!
We have just completed the payment.

**Comment by PrincessOnTop** [comment]
Hello Cryptocool1, is there anything else we should do?
Thank you.

**Pull request merged**
