### PR TITLE
Add Corgiswap (BEP20)

### PR DESCRIPTION
**Pull request by corgiswap**
Adding info for BEP20 token 'Corgiswap'.

PR created by <a href="https://assets.trustwallet.com">TW Assets Management</a>

### CODE REVIEW

**Comment by cryptomanz** [comment]
Hello,
Can your answer some questions?
 • What is the purpose of this token? How will it benefit Trust Wallet users?
 • How is the token being distributed? Are you conducting an airdrop?
 • Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?
 • Is the token listed on a centralized/decentralized exchange?
 • Is a Smart Contract audit completed? Where can we find this information?

**Comment by corgiswap** [comment]
Hi @cryptomanz , thank for reply

What is the purpose of this token? How will it benefit Trust Wallet users?
- The token is present to corgiswap exchange. (Corgiswap is  DEX and DeFi Fork from Pancakeswap)

How is the token being distributed? Are you conducting an airdrop?
- It's farming by Corgi Farm

Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?
- No

Is the token listed on a centralized/decentralized exchange?
- Yes:
- Pancakeswap: https://pancakeswap.info/pool/0x2a2cd8b1f69eb9dda5d703b3498d97080c2f194f
- Cointiger: https://www.cointiger.com/en-us/#/trade_center?coin=coris_usdt

• Is a Smart Contract audit completed? Where can we find this information?
- Not yet.

**Comment by cryptomanz** [comment]
Awaiting for smart contract audit.

**Comment by corgiswap** [comment]
hi @cryptomanz 
Have to audit smart contract to list on Trustwallet? The token contract is verified on bscscan and cointiger exchange, is it okay?

**Pull request merged**
