### PR TITLE
Added information and logo for Holyheld v2 (HH) token

### PR DESCRIPTION
**Pull request by McMannaman**
We are migrating our old token - HOLY to new token HH. Please see our previously submitted and merged PR - https://github.com/trustwallet/assets/pull/4700

The old tokens would be decommissioned around March after migration window.

### CODE REVIEW

**Comment by vikmeup** [comment]
Would you be able to also submit removal for the token when ready in March? no fee required then.

**Comment by amozgov** [comment]
Yes, absolutely. Once we close migration after the cut-off, we'll issue a separate PR. Thanks for your work!

**Comment by McMannaman** [comment]
> Would you be able to also submit removal for the token when ready in March? no fee required then.

Yes, we will be happy to submit removal PR, once the migration is completed

**Comment by McMannaman** [comment]
@vikmeup We have completed migration and rebranding. Can you please kindly remove old token (HOLY 0x39eAE99E685906fF1C11A962a743440d0a1A6e09), and can you please help us with the procedure for the image update for an existing token. 

As per rebranding, we have changed token name and symbol (without the contract address change). Would it be possible to update token image (for the same contract)?

Thank you!

**Comment by vikmeup** [comment]
> @vikmeup We have completed migration and rebranding. Can you please kindly remove old token (HOLY 0x39eAE99E685906fF1C11A962a743440d0a1A6e09), and can you please help us with the procedure for the image update for an existing token.
> 
> As per rebranding, we have changed token name and symbol (without the contract address change). Would it be possible to update token image (for the same contract)?
> 
> Thank you!

Can you submit pull request with making old contract as `status: abandoned` ?

**Pull request merged**
