### PR TITLE
Update Predix Network Logo

### PR DESCRIPTION
**Pull request by hilobrain**

### CODE REVIEW

**Comment by catenocrypt** [comment]
As per our policy, brand new tokens are not included, there is a minimum requirement of 500 holder addresses and 1000 transactions, in order to filter out scam tokens.
See the criteria at (mentioned in the first message by the bot): https://community.trustwallet.com/t/how-to-submit-a-token-logo/3863#how-to-get-approved
This token real usage yet, but below our limit (274). Rejecting PR. Please come back to us when all criteria are met.

https://etherscan.io/token/0x556148562d5DdeB72545D7EC4B3eC8edc8F55Ba7

**Comment by Hilobrain** [comment]
$PRDX has already been approved by trustwallet. This is only an update of the logo. 
Recently we have released our staking feature causing the amount of holders to decrease significantly (see https://etherscan.io/token/0x556148562d5DdeB72545D7EC4B3eC8edc8F55Ba7?a=0xa47430eab0c59bd8ce8653cb09459baa759cedae)

We are currently doing >$300k daily volume for the last few days and have a liquidity of over $500k on uniswap (see https://uniswap.info/pair/0xd6a46098b6cfcdd920e0c950407d12470833c786)

Although $PRDX is a relatively new token, it is not a scam token... Please reconsider.

**Comment by catenocrypt** [comment]
Reopening.  Sorry, I overlooked that this is an update.

**Comment by catenocrypt** [comment]
Could you please also add an `info.json` file next to the `logo.png`, with info about the project, now we require from all new assets.  Should be of the form:

```json
{
    "name": "Trust Wallet Token",
    "website": "https://trustwallet.com",
    "short_description": "Utility token to increase adoption of cryptocurrency.",
    "explorer": "https://explorer.binance.org/asset/TWT-8C2"
}
```

**Pull request closed without merging**
