### PR TITLE
Adding IBAT logo and info

### PR DESCRIPTION
**Pull request by jagjeetjena**

### CODE REVIEW

**Comment by Cryptocool1** [comment]
• What is the purpose of this token? How will it benefit Trust Wallet users?
 • How is the token being distributed? Are you conducting an airdrop?
 • Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?
 • Is the token listed on a centralized/decentralized exchange?
 • Is a Smart Contract audit completed? Where can we find this information?

**Comment by jagjeetjena** [comment]
• What is the purpose of this token? How will it benefit Trust Wallet users?
- This is a utility token of the battle infinity ecosystem. Most of the users who are holding our coin are using trust wallets to store their tokens. if you update the details about the token, it will help the users to track the authenticity of the token (that it's not some fake or bogus token) it will also help them to track the price of the token as well at the same time.

• How is the token being distributed? Are you conducting an airdrop?
- Private Sale - 2.5
  Presale - 28
  Foundation & Development - 10
  Marketing & CEX Listing - 18
  Founders & Partners - 20
  Advisors & Legal Team - 05
  Liquidity - 06
  Team Allocation - 10.5
  we are not conducting any airdrop

• Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?
- yes

• Is the token listed on a centralized/decentralized exchange?
- yes, on pancakeswap

• Is a Smart Contract audit completed? Where can we find this information?
- yes, https://github.com/solidproof/projects/tree/main/Battle%20Infinity

**Comment by jagjeetjena** [comment]
tag - utility
holders - 7251+

**Comment by Cryptocool1** [comment]
are you listed on CoinMarketCap?

**Comment by jagjeetjena** [comment]
not yet, our token launched 2 days ago on 17

**Comment by Cryptocool1** [comment]
we require CoinMarketCap listing. Feel free to open new pull request once you meet this requirement.
make sure to mention this PR, so that we can see that fee has been paid already here.

**Comment by jagjeetjena** [comment]
we have applied for cmc 
will coingecko also work??

**Comment by Cryptocool1** [comment]
> we have applied for cmc
> will coingecko also work??

No, we are taking the price from CMC.

**Pull request closed without merging**
