### PR TITLE
Add babyClown info and logo

### PR DESCRIPTION
**Pull request by clown-coin**
Add babyClown info and logo

### CODE REVIEW

**Comment by Cryptocool1** [comment]
hello,
can you answer some questions?
• What is the purpose of this token? How will it benefit Trust Wallet users?
 • How is the token being distributed? Are you conducting an airdrop?
 • Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?
 • Is the token listed on a centralized/decentralized exchange?
 • Is a Smart Contract audit completed? Where can we find this information?

**Comment by clown-coin** [comment]
> hello,
> can you answer some questions?
> • What is the purpose of this token? How will it benefit Trust Wallet users?
> • How is the token being distributed? Are you conducting an airdrop?
> • Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?
> • Is the token listed on a centralized/decentralized exchange?
> • Is a Smart Contract audit completed? Where can we find this information?
first question:We have Multiple use of enabling tokens.
second question:We have airdop,but everyone should go to the website to get airdrop,so everyone feel worth to getting airdrop.
third question: yes,We have token presale.
fouth question: The token listed on pancakeswap.
fifth question:The Smart Contract audit link: https://www.clown-coin.com/data/BabyClownAudit.pdf,https://www.clown-coin.com/data/ClownAudit.pdf

**Comment by clown-coin** [comment]
Answer question.

**Comment by cryptomanz** [comment]
Hello,
404 Not Found (audit)

**Comment by clown-coin** [comment]
Hi,there is two audits ,clown audit :https://www.clown-coin.com/data/ClownAudit.pdf
Block Audit Report Clown<https://www.clown-coin.com/data/ClownAudit.pdf>
2 Block Audit Report Team received the Clown team's application for smart contract security audit of the Clown Token on June 14, 2021. The following are the details and results of this
www.clown-coin.com
and babyclown audit:https://www.clown-coin.com/data/BabyClownAudit.pdf
________________________________
发件人: Nazar ***@***.***>
发送时间: 2021年7月13日 15:12
收件人: trustwallet/assets ***@***.***>
抄送: clown-coin ***@***.***>; Mention ***@***.***>
主题: Re: [trustwallet/assets] Add babyClown info and logo (#11506)


Hello,
404 Not Found (audit)

―

**Comment by Cryptocool1** [comment]
What is the purpose of this token? How will it benefit Trust Wallet users?

**Comment by clown-coin** [comment]
> What is the purpose of this token? How will it benefit Trust Wallet users?
Clown coin iscompletely decentralized,and all decisions are made by community voting.This allows our developers to better understand how to use Clown coins.Clown coin is a pre-sale issued token,the development team does not have a team token.
We have a marketing campaign every month that offers airdrops for Trust Wallet users

**Comment by cryptomanz** [comment]
0xfA949EF822125233f1e1A0691c13977B4354B257
already merged

**Comment by clown-coin** [comment]
> 0xfA949EF822125233f1e1A0691c13977B4354B257
> already merged

How long does babyClown merge?

**Comment by Cryptocool1** [comment]
for merging you need to upload only babyClown files

**Comment by Cryptocool1** [comment]
please create new PR without babyclown files
make sure to mention this PR so the fee can be reused

**Pull request closed without merging**
