### PR TITLE
Add IBAT logo and info

### PR DESCRIPTION
**Pull request by jagjeetjena**
IBAT logo and info updation 
we are listed on coingecko, pancakeswap and lbank
previous PR #22035

### CODE REVIEW

**Comment by jagjeetjena** [comment]
already paid payment in PR #22035

**Comment by Cryptocool1** [comment]
hello, are you listed on CoinMarketCap ?

**Comment by jagjeetjena** [comment]
yes we are listed on coinmarketcap
https://coinmarketcap.com/currencies/battle-infinity/

**Comment by jagjeetjena** [comment]
10500+ holders

**Pull request merged**
