### PR TITLE
Add Macaron Swap Token (MCRN)

### PR DESCRIPTION
**Pull request by macaronchef**
MacaronSwap has farming and staking options for holders. So holders stake their assets on MacaronSwap staking contract and farming contract. Staking contract is holding 40% of total supply now. Also there are many pool contract holding many people assets on its own. Please evaluate holder count with this.

### CODE REVIEW

**Comment by catenocrypt** [comment]
Note: Pancakeswap clone.

**Comment by catenocrypt** [comment]
As per our policy, brand new tokens are not included, there is a minimum requirement of 2500 holder addresses and 5000 transactions, in order to filter out scam tokens.
See the criteria at (mentioned in the first message by the bot): https://community.trustwallet.com/t/how-to-submit-a-token-logo/3863).
This token has below-limit usage yet (1248 holders). Putting PR on hold for now. Please come back to us when all criteria are met.  Multi-chain and staking tokens may get special treatment, let us know if this is the case. 

https://bscscan.com/token/0xacb2d47827C9813AE26De80965845D80935afd0B

**Comment by mantorra** [comment]
Hi Catenocrypt,
As macaronswap is a staking/farm platform, many users put their tokens to Staking contract, 0xfcde390bf7a8b8614ec11fa8bde7565b3e64fe0b (You'll see its label on BSCScan as well). despite this, there are 1250 holders and 62,654+ transactions.

All contracts are under review of CertiK: https://www.certik.org/projects/macaronswap

**Comment by mantorra** [comment]
Hi Catenocrypt,
As macaronswap is a staking/farm platform, many users put their tokens to Staking contract, 0xfcde390bf7a8b8614ec11fa8bde7565b3e64fe0b (You'll see its label on BSCScan as well). despite this, there are 1250 holders and 62,654+ transactions.

All contracts are under review of CertiK: Hi Catenocrypt,
As macaronswap is a staking/farm platform, many users put their tokens to Staking contract, 0xfcde390bf7a8b8614ec11fa8bde7565b3e64fe0b (You'll see its label on BSCScan as well). despite this, there are 1250 holders and 62,654+ transactions.

All contracts are under review of CertiK: www.certik.org/projects/macaronswap

**Comment by mantorra** [comment]
Hi Catenocrypt,

As macaronswap is a staking/farm platform, many users put their tokens to Staking contract, 0xfcde390bf7a8b8614ec11fa8bde7565b3e64fe0b (You'll see its label on BSCScan as well). despite this, there are 1250 holders and 62,654+ transactions.

All contracts are under review of CertiK for audit as well. We have Skynet submission too, to have community and realtime smart contracts safety.

**Comment by Cryptocool1** [comment]
Hello,
As per our policy, there is a minimum requirement of 2500 holder addresses and 5000 transactions.
This token has no real usage yet (1,245 holders). Closing PR for now. Please come back to us when all criteria are met.

**Comment by macaronchef** [comment]
Hi Catenocrypt,

As macaronswap is a staking/farm platform, many users put their tokens to Staking contract, 0xfcde390bf7a8b8614ec11fa8bde7565b3e64fe0b (You'll see its label on BSCScan as well). despite this, there are 1250 holders and 62,654+ transactions.

All contracts are under review of CertiK for audit as well. We have Skynet submission too, to have community and realtime smart contracts safety.

**Comment by macaronchef** [comment]
Hi @corymsmith @catenocrypt @Cryptocool1,

Can you please re-evaluate? We met all criteria now.

**Pull request merged**
