### PR TITLE
Add StarCurve (XSTAR)

### PR DESCRIPTION
**Pull request by defidave**
Added the StarCurve (XSTAR) token. The image has been optimized through TinyPNG. 

I am aware that the token does not meet the requirements in activity, however we would like to add our token before our IDO as we are using Mesa to conduct this. The Gnosis Team recommended us to submit our asset here so the token icon gets loaded on Mesa during our IDO. We also have a [customized version](https://sale.starcurve.io) of the Mesa front-end where we would like to display our asset (without hardcoding it). Hopefully an exception is possible.

### CODE REVIEW

**Comment by catenocrypt** [comment]
As per our policy, brand new tokens are not included, there is a minimum requirement of 100 holder addresses and 500 transactions, in order to filter out scam tokens.
See https://community.trustwallet.com/t/how-to-submit-a-token-logo/3863#how-to-get-approved
This token has minimal usage so far (4/5).  Putting this PR on hold for now.

https://etherscan.io/token/0xC0E47007e084EEF3EE58eb33D777b3B4Ca98622f

**Comment by defidave** [comment]
> 
> 
> As per our policy, brand new tokens are not included, there is a minimum requirement of 100 holder addresses and 500 transactions, in order to filter out scam tokens.
> See https://community.trustwallet.com/t/how-to-submit-a-token-logo/3863#how-to-get-approved
> This token has minimal usage so far (4/5). Putting this PR on hold for now.
> 
> https://etherscan.io/token/0xC0E47007e084EEF3EE58eb33D777b3B4Ca98622f

Possible to make an exception in this case? We would like to list before IDO (before token distribution) so our asset logo is visible in the Mesa UI. You can view the proposal here to DXdao [here](https://alchemy.daostack.io/dao/0x519b70055af55a007110b4ff99b0ea33071c720a/proposal/0x587a2660d3b1d7e69ab66d9ad383f04735f3943096fe286a63e21359e78f5d07).

**Comment by catenocrypt** [comment]
Can you share information on the estimated scale of the planned distribution?

**Comment by defidave** [comment]
> 
> 
> Can you share information on the estimated scale of the planned distribution?

Definitely! All the sale information and token economics are captured in this post:
https://medium.com/@StarCurve/token-economics-and-ido-details-e0550e997be3

and in the onepager:
https://starcurve.io/assets/onepager.pdf

**Comment by catenocrypt** [comment]
Accepting PR

**Pull request merged**
