### PR TITLE
Add EYE Network (BEP20)

### PR DESCRIPTION
**Pull request by yenky**
Adding info for BEP20 token 'EYE Network'.

PR created by <a href="https://assets.trustwallet.com">TW Assets Management</a>

### CODE REVIEW

**Comment by cryptomanz1** [comment]
• What is the purpose of this token? How will it benefit Trust Wallet users?
 • How is the token being distributed? Are you conducting an airdrop?
 • Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?
 • Is the token listed on a centralized/decentralized exchange?
 • Is a Smart Contract audit completed? Where can we find this information?

**Comment by yenky** [comment]
• What is the purpose of this token? How will it benefit Trust Wallet users?

    The EyeNetwork Ecosystem is a groundbreaking initiative poised to reshape the landscape of financial services. At its core, this innovative platform harnesses the power of blockchain technology to facilitate seamless transactions, enhance security, and promote financial empowerment for individuals worldwide.
    We are developing a lot of features for our users, but only Trust wallet owners will be able to use them. As everyone is aware, this is a very reliable digital wallet, and we prefer having all of our customers use it. Because all functionality and exchanging will only occur through trust wallet, users of trust wallets will benefit first and foremost from this. 

• How is the token being distributed? Are you conducting an airdrop?

    Tokens are currently being distributed by pancake swap , vindex and airdropped at a rate of 0.04% to our community, who have been waiting and supporting us since we began construction on this project in 2022.

• Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?

    No, we did not participate in a pre-sale offer.

• Is the token listed on a centralized/decentralized exchange?

    Indeed, this currency is listed on the VINDEX centralized exchange https://vindax.com/exchange-base.html?symbol=EYE_USDT 

• Is a Smart Contract audit completed? Where can we find this information?

    Yes EYE is audited with cointool audit team and here you can find audit report : https://eyetoken.io/COINTOOL_EYE_AUDIT_REPORT.pdf

**Comment by Cryptocool1** [comment]
Hello, are you listed on CoinMarketCap?

**Comment by yenky** [comment]
Hi @cryptomanz1  , @Cryptocool1 

We are not on the CMC list because we need to prepare our trust wallet before we can visit the CMC. We are asking you to approve our trust wallet before we can proceed to the CMC. Because this project necessitated the usage of a trust wallet, the next steps are collaborative and step-by-step. We want to create a strong basis and have the right audience for our token, so we are hoping to complete the trust wallet logo.
We hope you will provide us clarity and express our gratitude on behalf of our 10,000+ holders. We are asking you to approve the trust wallet logo so that we may move forward with the project. Without the trust wallet logo, we cannot begin any process.

Thank you

**Comment by Cryptocool1** [comment]
We do require CoinMarketCap listing . 
Please take a look at our documentation. https://developer.trustwallet.com/listing-new-assets/requirements
Feel free to come back to us once CMC listing is done. Make sure to mention this PR so the fee can be reused

**Comment by yenky** [comment]
Hi @Cryptocool1 @cryptomanz1 

We are listed on CMC : https://coinmarketcap.com/currencies/eye-network/  . Please try to approve logo over Trust Wallet.
PR : 27846 [ We paid already for this ]

Thank You

**Pull request merged**
