### PR TITLE
Update on Flap Coin (FLAP) #17735

### PR DESCRIPTION
**Pull request by flappybirdgo**
update on #17735

### CODE REVIEW

**Comment by flappybirdgo** [comment]
paid already in last PR #17735

**Comment by cryptomanz** [comment]
• What is the purpose of this token? How will it benefit Trust Wallet users?
 • How is the token being distributed? Are you conducting an airdrop?
 • Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?
 • Is the token listed on a centralized/decentralized exchange?
 • Is a Smart Contract audit completed? Where can we find this information?

**Comment by flappybirdgo** [comment]
• What is the purpose of this token?  How will it benefit Trust Wallet users?

This token purpose is for FlappyBird Go game token and used on scholarship members, the benefit is not for Trust Wallet users but benefit to all users for Decentralized purpose


• How is the token being distributed? Are you conducting an airdrop?

this token being distributed on our game community by airdrop ~ 10,000 users and will increase daily

and other marketing campaign


• Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?


Private Sale - Only whitelist users ( Now - 25 March 2022 )

Public Sale ( 28 March - 28 April 2022 )

Round 1 : Whitelist ( exclude private sale users )

Round 2 : All people


• Is the token listed on a centralized/decentralized exchange?

this will list on PancakeSwap Liq and now we working with BitMart (CEX)


• Is a Smart Contract audit completed? Where can we find this information?

now we submited to Certik and i'm sure that no problem about the security

you can try to review our SmartContract code in my Github

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by cryptomanz** [comment]
Awaiting for smart contract audit. On hold for now.

**Comment by cryptomanz** [comment]
Please come back to us when all criteria are met.
When creating a new PR make sure to mention this PR, so that we can see that fee has been paid already here.

**Pull request closed without merging**
