### PR TITLE
Add FileSystemVideo (BEP20)

### PR DESCRIPTION
**Pull request by byqm68**
Adding info for BEP20 token 'FileSystemVideo'.

PR created by <a href="https://assets.trustwallet.com">TW Assets Management</a>

### CODE REVIEW

**Comment by byqm68** [comment]
Hello, I have paid in pull request 19684, but it failed. This is a newly created PR, please help review it

**Comment by Cryptocool1** [comment]
hello, your logo should be full screen size 256/256, please change

**Comment by byqm68** [comment]
I just rechecked the size of the picture. It is indeed 256x256 pixels. Please refer to the screenshot 
jietu

@Cryptocool1

**Comment by cryptomanz** [comment]
Your logo should be full size

**Comment by cryptomanz** [comment]
Screenshot 2022-04-13 at 17 18 05
without empty space from the side

**Comment by byqm68** [comment]
> Screenshot 2022-04-13 at 17 18 05
> 
> without empty space from the side

fsv-logo

**Pull request merged**
