### PR TITLE
ADD DIS(BEP20) Token logo and info

### PR DESCRIPTION
**Pull request by MiningTW**
Dear Trust Wallet Team,

I understand your concerns regarding proxy contracts. Since our last interaction, we have addressed the issue and conducted a formal security audit to ensure the safety of our token's contract. The audit reports can be found at the following URLs:

GitHub Audit: https://github.com/cyberscope-io/audits/blob/main/dis/audit.pdf

Coinscope Audit: https://www.coinscope.co/coin/dis/audit

Additionally, I would like to inform you that I have relinquished ownership of the contract. This action can be verified through the following transaction hash on BscScan:

Transaction Hash: https://bscscan.com/tx/0x89a6fd8f6d45c0e56e501152276612e92ef3c93ab1a8f8fd6cf190f65bc59811

Moreover, I have resubmitted our token's data. The payment for this submission was already made during our previous application and can be verified through the following transaction hash on BscScan:

Payment Transaction Hash: https://bscscan.com/tx/0x4bf3b74738e0cb7e7cffdeb3ba21a45e2728e287e547c43ec44301bcdaacaaf3

Per your previous communication, the TPT hash value from our previous payment can be used for this logo submission.

I have also manually checked the number of holders for our token. As of this writing, we have 12,381 holders. The holder count can be verified at the following URL on BscScan:

Token Holder Count: https://bscscan.com/token/0xe2ecc66e14efa96e9c55945f79564f468882d24c

Our token contract originally had an agent upgrade function. We have since relinquished contract ownership and passed a security audit. Another important point is that our token is issued under the real-name company, Miningtw Technology Co., Ltd. We have stated in our white paper that our token, DIS, has no affiliation with Walt Disney. It is not issued by or related to them. It is a meme coin with a similar name in a different industry.

Please let me know if there are any further steps that need to be completed.

Best regards,
MiningTW

### CODE REVIEW

**Comment by MiningTW** [comment]
The 500 TWT payment for the last application was made for PR #9452.
https://github.com/TP-Lab/tokens/pull/9452

**Comment by Cryptocool1** [comment]
Moreover, in https://github.com/trustwallet/assets/pull/9452
 submitted completely different token, even if you made a payment there, you cannot use it for another token

**Comment by MiningTW** [comment]
Nuo Nuo, I just found out that TPT was passed instead of TWT, I will pay
again

CryptoA ***@***.***>於 2023年6月19日 週一，下午6:37寫道：

**Comment by MiningTW** [comment]
So whether to pay TPT or TWT? Do I still need to pay?

陳家榮 ***@***.***>於 2023年6月19日 週一，下午6:41寫道：

**Comment by Cryptocool1** [comment]
Before payment please answer these questions:
• What is the purpose of this token? How will it benefit Trust Wallet users?
 • How is the token being distributed? Are you conducting an airdrop?
 • Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?
 • Is the token listed on a centralized/decentralized exchange?
 • Is a Smart Contract audit completed? Where can we find this information?

**Comment by MiningTW** [comment]
wait i write

**Comment by MiningTW** [comment]
Before payment please answer these questions:
• What is the purpose of this token? How will it benefit Trust Wallet users? 
[DIS] was launched by Miningtw Technology Co., Ltd., a cooperation team located in Hong Kong and Taiwan, on 2023-5-8. It is a meme token issued by the relevant communities of blockchain, cryptocurrency, and mining. the meme token for interaction, event rewards, gifts, charitable purposes, and dreams, but here is a statement that it has nothing to do with Walt Disney and it did not happen to them. Although the names are similar, but in different fields and scopes, memes are purely for fun and joy.

• How is the token being distributed? Are you conducting an airdrop? 
The total issuance of DIS tokens is 100 million. To incentivize DIS token holders, we have launched a five-year liquidity mining activity. 50% of the issuance, that is, 50 million tokens, are added to the staking mining reward pool ,In order to further expand the development of DIS, 10% of DIS issuance, that is, 10 million DIS tokens, will be locked for staking for five years. 50% of the rewards obtained each month will be burned, and the other 50% will be used for development, promotion, and developer team distribution.
Another 20% is used to increase liquidity in DEX decentralized transactions and provide liquidity buying and selling to CEX exchanges, 10% are distributed in batches airdropped or given to the community total amount, and 10% are used for promotion and advertising, development expenses and developer team distribution.

In the first round of large airdrops on May 9, 2023 https://distoken.xyz/disneydis%e8%bf%aa%e5%a3%ab%e5%b0%bc%e8%bf%b7%e5%9b%a0 %e5%b9%a3%e7%99%bc%e8%a1%8c%e7%ac%ac%e4%b8%80%e5%a4%a9%e6%9a%b4%e6%bc%b214%e8 %90%ac%ef%bc%8c%e5%ae%8c%e6%88%90%e9%a6%96%e8%bc%aa%e7%a9%ba/ 
in the second round on May 14, 2023 Large airdrop https://distoken.xyz/%e8%bf%aa%e5%a3%ab%e5%b0%bc%e5%b9%a3dis%e4%b8%8d%e5%88%b0%e4%b8 %80%e5%91%a8%e6%9a%b4%e6%bc%b221582%e5%80%8d%ef%bc%81%e7%ac%ac%e4%ba%8c%e8%bc%aa %e7%a9%ba%e6%8a%95%e7%99%bc%e6%94%be%ef%bc%81/ 
Other small airdrops have continued to hold activities in the community, and the most recent large airdrop is listed on the Mexc exchange 900,000 Dis

• Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale? 
No ICO or private placement

• Is the token listed on a centralized/decentralized exchange? 
Increase liquidity at PancakeSwap from the beginning, 
https://pancakeswap.finance/swap?o utputCurrency=0xE2ECC66E14EFA96E9C55945F79564F468882D24C 
2023-5-25 SWFTs https://swap.swftcoin.com 
2023-6-1 Listing TXBit https://txbit.io/trade/dis/usdt 
2023-6-19 MEXC https://www.mexc.com/support/articles/17827791508985 dex decentralized transactions

• Is a Smart Contract audit completed? Where can we find this information? 
Completed audit report: https://github.com/cyberscope-io/audits/blob/main/dis/audit.pdf
https://www.coinscope.co/coin/dis/audit

**Comment by MiningTW** [comment]
Can I pay in TWT?

**Comment by Cryptocool1** [comment]
Yea please follow the instructions from the bot message

**Pull request merged**
