### PR TITLE
Ad logo to BRJ Bull Run Jesus

### PR DESCRIPTION
**Pull request by jamesbondcode**
Please ad the logo. Thank you.

### CODE REVIEW

**Comment by jamesbondcode** [comment]
Paid.

**Comment by jamesbondcode** [comment]
Paid.

**Comment by catenocrypt** [comment]
@jamesbondcode , you have provided two image files:
- one larger, but in wrong location
- one smaller, which looks like already existing, in the right location.

What is your intention?  Replace existing schematic logo with new painting-like one?

**Comment by jamesbondcode** [comment]
> @jamesbondcode , you have provided two image files:
> 
> * one larger, but in wrong location
> * one smaller, which looks like already existing, in the right location.
> 
> What is your intention? Replace existing schematic logo with new painting-like one?

Yes, please. Replace logo with new painting-like one. Sorry, and thank you.

**Pull request merged**
