### PR TITLE
Add logo and info about MetaMate token

### PR DESCRIPTION
**Pull request by Chester-Ngo**

### CODE REVIEW

**Comment by Chester-Ngo** [comment]
Audit report by Solidity Finance: https://solidity.finance/audits/MetaMate/

**Comment by Cryptocool1** [comment]
As per our policy, brand new tokens are not included, there is a minimum requirement of 10,000 holder addresses and 15,000 transactions, in order to filter out scam tokens.
See the criteria at : https://developer.trustwallet.com/assets/requirements .

**Comment by cryptomanz** [comment]
Please come back to us when all criteria are met.
When creating a new PR make sure to mention this PR, so that we can see that fee has been paid already here.

**Comment by Chester-Ngo** [comment]
> Please come back to us when all criteria are met. When creating a new PR make sure to mention this PR, so that we can see that fee has been paid already here.

Please check my new pr https://github.com/trustwallet/assets/pull/19839

**Pull request closed without merging**
