### PR TITLE
Uncle Doge logo

### PR DESCRIPTION
**Pull request by VACostin**
Uncle Doge logo upload attempt no. 2

### CODE REVIEW

**Comment by VACostin** [comment]
"What is the usecase of this token?"

Uncle Doge is a community focused token with unique tokenomics. At the center of the tokenomics is the “Kraken” the buy back mechanism that ensures price stability. In addition token olders recieve 1% in reflections and benefit from the burned tokens through the Kraken. The community is global, with over 18,000 holders on launch day and over 15M daily volume.

**Comment by cryptomanz** [comment]
your explorer not active (https://bscscan.com/token/0xe9e70xD2618bC9c9cDC40ff19e200a7d14A09799C0a152) 
please correct

**Comment by Cryptocool1** [comment]
hello, can you answer some questions?
• What is the purpose of this token? How will it benefit Trust Wallet users?
 • How is the token being distributed? Are you conducting an airdrop?
 • Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?
 • Is the token listed on a centralized/decentralized exchange?
 • Is a Smart Contract audit completed? Where can we find this information?

**Comment by VACostin** [comment]
> hello, can you answer some questions?
Hello, sure

> • What is the purpose of this token? How will it benefit Trust Wallet users?

Uncle Doge is a community focused token with unique tokenomics. At the center of the tokenomics is the “Kraken” the buy back mechanism that ensures price stability. In addition token olders recieve 1% in reflections and benefit from the burned tokens through the Kraken. The community is global, with over 19,000 holders and over 16M average daily volume.

> • How is the token being distributed? Are you conducting an airdrop?

Purchase - Our token can be purchased through pancakeswap. 
Reflection - 1% of each transaction is redistributed as tokens to other holders
Burn - On each buyback, tokens are burned through our "kraken" which we now are calling "Big Sam"
Airdrop - We've initially planned to airdrop 1% of our total supply to early comers, hence we've reserved a wallet for that. We've held a giveaway contest where 100 winners would be picked, ended up aidroping only to 4 addresses/persons after since they were mainly bots in contest. 
To expand on the airdrop subject, we thought we might use this aidrop wallet as a reward to incentivize our most active members, but we realized this might cause uncertainty for our holders so instead we've rewarded our most active members with BNBs from our marketing wallet. Airdrop wallet will be burned.

> • Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?

Presale - DxSale.

> • Is the token listed on a centralized/decentralized exchange?

PancakeSwap, decentralized

> • Is a Smart Contract audit completed? Where can we find this information?

Audit link - https://github.com/TechRate/Smart-Contract-Audits/blob/main/Uncle%20Doge.pdf

Securing the complete audit at a later time. We've completed the basic Audit in record time (~ 4 hours). We had to do this in order to secure a very early timeslot for BTOK ads. We also have to add that for BTOK ads I basically had to provide my ID card and state some sort of "legal agreement" in a video.

**Comment by Cryptocool1** [comment]
please create new PR when your token will be listed on CMC
make sure to mention this PR so that fee can can be reused

**Pull request closed without merging**
