### PR TITLE
KazooCoin token information

### PR DESCRIPTION
**Pull request by KazooCoinBSC**
Check us out, audited, transparent project aiming to educate investors on staying safe in the smart contract space.
https://linktr.ee/KazooCoin
Please either DM on twitter or contact our lead developer at 
jwgaunt00@gmail.com regarding payment of BNB.
Thanks :)

### CODE REVIEW

**Comment by KazooCoinBSC** [comment]
https://explorer.binance.org/tx/ACA5050EABFE471A72B790A08C71AD4BDE0658AA60CAB16F38ED33178CCE1209

TXID - 2BNB contribution.

**Comment by Cryptocool1** [comment]
Correction needed:
This is a BEp20 token, correct folder is blockchains/smartchain/assets. Please correct.

**Comment by KazooCoinBSC** [comment]
How do I move us to the correct location?
Have paid 2bnb so don't want to lose it.

**Comment by KazooCoinBSC** [comment]
Hello please help me out, unsure how to move our application

**Comment by Cryptocool1** [comment]
If you can't rename files in the PR, you may open a new PR. Make sure to mention this PR, so that we can see that fee has been paid already here.

**Comment by Cryptocool1** [comment]
You may want to try our new Assets app in beta; go to https://assets.trustwallet.com, log on with Github, enter contract ID, logo and some additional info, and it will create a PR for you.
See https://community.trustwallet.com/t/how-to-submit-a-token-logo-using-assets-app/82957.

**Comment by KazooCoinBSC** [comment]
Thanks for your help!
I have made a new pull request, check it out 
https://github.com/trustwallet/assets/pull/8430

**Pull request closed without merging**
