### PR TITLE
Add Floki Elon (BEP20)

### PR DESCRIPTION
**Pull request by flokielonreal**
Adding info for BEP20 token 'Floki Elon'.

PR created by <a href="https://assets.trustwallet.com">TW Assets Management</a>

### CODE REVIEW

**Comment by flokielonreal** [comment]
Hi

**Comment by flokielonreal** [comment]
Check hash sir:
B182F50ED9D80BE4D5B10A35EE95A9E559D8573721646A70DD35AFD25ABFE3C2

**Comment by Cryptocool1** [comment]
Hello,
• What is the purpose of this token? How will it benefit Trust Wallet users?
 • How is the token being distributed? Are you conducting an airdrop?
 • Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?
 • Is the token listed on a centralized/decentralized exchange?
 • Is a Smart Contract audit completed? Where can we find this information?

**Comment by flokielonreal** [comment]
Hi Dear,

• The token will help the community distinguish our project as official.
• Our project is listed directly through the Pancakeswap decentralized exchange.
We do not sell ICOs, do not pre-sell.
• You can check our audit file via this link: https://github.com/sokenteam/smart_contract_audits/blob/main/Floki%20Elon%20Standard%20Smart%20Contract%20Audit.pdf

Best regards !

**Comment by flokielonreal** [comment]
Hi Dear,

What's wrong with our token? Please give us advice for correction.

Thank you so much

**Comment by flokielonreal** [comment]
Hi Dear,

We have successfully updated the steps, right?

Best regards !

**Comment by flokielonreal** [comment]
Thanks for team !

**Pull request merged**
