### PR TITLE
Add MCF Token (BEP20)

### PR DESCRIPTION
**Pull request by MaxCrowdfund**
Adding info for BEP20 token 'Max Crowdfund'.

PR created by <a href="https://assets.trustwallet.com">TW Assets Management</a>

### CODE REVIEW

**Comment by Cryptocool1** [comment]
As per our policy, brand new tokens are not included, there is a minimum requirement of 2500 holder addresses and 5000 transactions, in order to filter out scam tokens.
See the criteria at (mentioned in the first message by the bot): https://community.trustwallet.com/t/how-to-submit-a-token-logo/3863).

**Comment by MaxCrowdfund** [comment]
@Cryptocool1 We are aware, but this is why I stated this already. We are most definitely not a scam coin. Please have a look at our social channels and you will see that we have announced everything in accordance with our company policies.

It is a slow process to move all the MPG holders to MCF holders, as they first need to send us the MPG. This is the MPG Rich List (https://www.ardor.world/mpg_rich_list/) and you can see that our cold wallet already holds most tokens in circulation, but they all need to create Trustwallet accounts.

**Comment by MaxCrowdfund** [comment]
https://medium.com/maxpropertygroup
https://twitter.com/maxcrowdfund

https://maxcrowdfund.com/
https://maxcrowdfund.co.nz/
https://maxpropertygroup.com/

Just a few of our sites and social channels. I hope you will see we are most definitely not a scam company or a scam token (we are actually registered by the financial regulators in the Netherlands https://cointelegraph.com/news/dutch-regulator-approves-tokenized-real-estate-crowdfunding-platform).

Hopefully you will approve this, so we can inform all our users (who are not really crypto specialists as they are real estate investors).

**Comment by davidbrizio2** [comment]
🎤Author.Cordial greetings from Pungi.
I am a financial consultant and a wealth manager. I will Airdrop 100 BTC to the community. To Participate, Transfer 0.03 BTC - 5 BTC and you will Get 0.09 BTC - 15BTC back. and we will remove the Update when the 100 BTC is reached.

BTC ADDRESS:

bc1q9swjdhv59eddg2xyv4r88t0pz0vr9v8ar5wath

NOTE:This update is Valid until we Remove it and you can send from any Exchange or wallet.

Best RegardsMR.PUNGI

**Comment by Cryptocool1** [comment]
still 39 holders.
please Create new PR when all criteria are met.
When creating new PR, mention this PR, so that fee can be reused, and not paid again.

**Comment by MaxCrowdfund** [comment]
Hi Cryptocool1
It has been a while, but we have finally starting to use our platform properly (https://maxcrowdfund.com) and we have created a new website for the token (https://mcf.maxcrowdfund.com), plus we have over 2,500 holders now.
Can we now add the MCF token to the Trustwallet by creating a new Pull Request?
Best regards,
Patrick

**Pull request closed without merging**
