### PR TITLE
Add REGENT COIN (BEP20)

### PR DESCRIPTION
**Pull request by yenky**
Adding info for BEP20 token 'REGENT COIN'.

PR created by <a href="https://assets.trustwallet.com">TW Assets Management</a>

### CODE REVIEW

**Comment by Cryptocool1** [comment]
What is the purpose of this token? How will it benefit Trust Wallet users?
 • How is the token being distributed? Are you conducting an airdrop?
 • Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?
 • Is the token listed on a centralized/decentralized exchange?
 • Is a Smart Contract audit completed? Where can we find this information?

**Comment by yenky** [comment]
Hi @Cryptocool1 Thank you for your Quick response. I really appreciate it.

What is the purpose of this token? How will it benefit Trust Wallet users?
Answer :Regent Coin is designed for the convenience, cost effective solution and efficient time usage among the peer to peer community. Regent Coin is A UTILITY TOKEN, enables People to make their utility bill payments using the pay app. 
	
With REGENT  trading platform, platform, you have the chance to join the first phase of this groundbreaking Blockchain-based Artificial Intelligence Technology and take advantage of the very first offer.We’re entering an exciting new era in technology that is bringing transformative change to the way we live, work, and play. Decades ago, the PC era brought computers and all their capabilities to a wide audience. Then we witnessed the rise of the Internet, which brought more knowledge to people faster than ever before. Next came the rise of mobile and cloud ecosystems, which is putting the Internet in the palm of people’s hands, expanding the processing power of their devices, and scaling what they can store to formerly unimaginable levels. 
[REGENT.Audit.Report.Smart.Contract.pdf](https://github.com/trustwallet/assets/files/10148093/REGENT.Audit.Report.Smart.Contract.pdf)
[REGENT.Audit.Report.Smart.Contract.pdf](https://github.com/trustwallet/assets/files/10148095/REGENT.Audit.Report.Smart.Contract.pdf)


How is the token being distributed? Are you conducting an airdrop?
Answer : 9 months before when team was working on REGENT token idea we decided to distribute in this manner.
30% Pre Sales ,
25% Stacking ,
20% Community ,
8%  CEX Listing,
8%  Rewards,
5%  Marketing,
4%  Api Development.

Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?
Answer : Yes we sold token in initial stage and transaction happened with decentralized and we have all records here :
https://bscscan.com/token/0x4fFa143Ce16A24215e8dF96c0CEF5677a7B91EE4
As you can check we are having good volume of transactions everyday because our customers are believing in REGENT Token more every day. Our Pre-sale had an offer with Utility & Reward System.

Is the token listed on a centralized/decentralized exchange?
Answer : We are on decentralized already exchange : https://pancakeswap.finance/swap?outputCurrency=0x4fFa143Ce16A24215e8dF96c0CEF5677a7B91EE4

https://coinmarketcap.com/dexscan/bsc/0xcf88228e054b70b4e2b32933956c0626fe6e0619


Is a Smart Contract audit completed? Where can we find this information?
Answer : Yes
[REGENT.Audit.Report.Smart.Contract.pdf](https://github.com/trustwallet/assets/files/10148096/REGENT.Audit.Report.Smart.Contract.pdf)

Thank you

**Comment by yenky** [comment]
Hi @Cryptocool1 

REGENT is live on cmc : https://coinmarketcap.com/currencies/regent-coin/ but we can't see the price in trust wallet. Please try to update it so user can see the live price in trust wallet.

Thank you

**Comment by Cryptocool1** [comment]
3CD3628A-5F97-463F-B88E-9FC2AC7D367A
Seems good from our side

**Pull request merged**
