### PR TITLE
Add Welnance Coin (BEP20)

### PR DESCRIPTION
**Pull request by Welnance**
Adding info for BEP20 token 'Welnance Coin'.

PR created by <a href="https://assets.trustwallet.com">TW Assets Management</a>

### CODE REVIEW

**Comment by Welnance** [comment]
According to the meeting with Sea Binance Team, We have a collaboration with the BSC team (Ref Telegram Users: @BrettBinance @Jessbinance, @bibiapac, @LynnHoang). So we would like to submit our project to Trustwallet for more business collaborations.
Live Ref:https://fb.watch/96oSabFfEM/

**Comment by ramsty** [comment]
Hi!
Could you answer some questions?
• What is the purpose of this token? How will it benefit Trust Wallet users?
• How is the token being distributed? Are you conducting an airdrop?
• Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?
• Is the token listed on a centralized/decentralized exchange?
• Is a Smart Contract audit completed? Where can we find this information?

**Comment by Welnance** [comment]
##  What is the purpose of this token? How will it benefit Trust Wallet users?

Welnance is under Phousy group (https://phousy.com/welnance/) has over 20 years of experience in business operations in Laos especially our construction portfolio of roads and bridges since 1997. In 2009, the company’s total assets has increased to over $3 billion. Phousy Group Portfolio comprises road and bridge construction, architecture & design, petroleum, irrigation system, mining, hydropower, and import/export, hotel, transportation, and grindstone factory. Phousy Group is home to over 1000 employees where we operate in a friendly family-like environment.

Welnance Finance is a platform that provides Decentralized Exchange, Swap, Staking, and Yield Farming Pools, along with other upcoming features such as, Lottery Lucky Draw, rewards, and most importantly, Official Welnance Token.

Welnance is a protocol on the Binance Smart Chain that establishes money markets, which are pools of assets with algorithmically derived interest rates, based on the supply and demand for the asset. Suppliers(and borrowers) of an asset interact directly with the protocol, earning (and paying) a floating interest rate, without having to negotiate terms such as maturity, interest rate, or collateral with a peer or counterparty.

According to the meeting with Sea Binance Team, We have a collaboration with the BSC team (Ref Telegram Users: @BrettBinance @Jessbinance, @bibiapac, @lynnhoang). So we would like to submit our project to Trustwallet for more business collaborations BSC and Trustwallet. Furthermore, Welnance is already registered Binance corporate account: Welnance Trading Online Sole Co., Ltd

https://coinmarketcap.com/currencies/welnance-finance/
https://bscscan.com/token/0x854B4c305554c5fa72353e31b8480c0e5128A152

Forums ref: https://fb.watch/96oSabFfEM/
                   https://fb.watch/98KZ8Dvqb4/


## How is the token being distributed? Are you conducting an airdrop?
The token is being distributed organically on Pancakeswap, an airdrop is postponed to the next year. More tokennomic details is here:  https://welnance.gitbook.io/welnance-finance/documentations/tokenomics/wel-distribution

## Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?
There was no ICO or token presale. There was a fair launch on Oct 15st, 2021.

## Is the token listed on a centralized/decentralized exchange?
USDT/WEL token is listed on Pancakeswap. We're working with Welnance Defi (https://welnance.finance) and Welnance Exchange to list our WEL and other coins.
https://pancakeswap.finance/info/pool/0x0b2f270244d0b7ed80ab3e6666738539389f1740


## Is a Smart Contract audit completed? Where can we find this information?
1- WEL’s smart contracts were audited by Anchain https://www.anchain.ai/ 
Reports Link: https://drive.google.com/drive/folders/1cK6lIotYW-v8M2DuI3m2mC8CPz9OXINW?usp=sharing

2- WEL’s smart contracts is being audited by Inspex https://inspex.co/ (Under reviewing now)
Ref: https://app.inspex.co/library/welnance#?scope=welnance-lending

**Comment by Welnance** [comment]
Dear Trust Wallet Team. 

We would like to change the description of the project. 
because we submitted a mistake description.

Thank you

**Pull request merged**
