### PR TITLE
Add BitShiba

### PR DESCRIPTION
**Pull request by BitShiba**
Adding info for BEP20 token 'BitShiba'.

### CODE REVIEW

**Comment by cryptomanz** [comment]
• What is the purpose of this token? How will it benefit Trust Wallet users?
 • How is the token being distributed? Are you conducting an airdrop?
 • Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?
 • Is the token listed on a centralized/decentralized exchange?
 • Is a Smart Contract audit completed? Where can we find this information?

**Comment by BitShiba** [comment]
The goal of BitShiba is to create a community driven decentralized store of value and multi-use dapp token on the binance smart chain network. $SHIBA is fully distributed, 50% of the supply was added directly to dex liquidity on pancakeswap and the other 50% were burnt. No presale,no team token. $SHIBA has amassed 10,000 holders in the first week live and growth is still speeding up. BitShiba aims to be completely community run through the use of a DAO. 
Our token contract is a simple "standard bep20 token" contract with no mint/burn or other added characteristics. We will apply the token contract to be audited as well as all future smart contracts associated with the project with top auditors such as Certik. Thank you

**Comment by ramsty** [comment]
Awaiting for smart contract audit. On hold for now.

**Comment by Cryptocool1** [comment]
Feel free to open new PR when smart contract audit will be ready
When creating a new PR make sure to mention this PR, so that we can see that fee has been paid already here.

**Pull request closed without merging**
