### PR TITLE
Please add logo to BabyFlokiZilla token

### PR DESCRIPTION
**Pull request by BillyBeat**
We would like to resubmit a new PR to continue our previous request, reference: https://github.com/trustwallet/assets/pull/15593 

As per the collaborator we may do so and use it as a reference that it's already been paid, reference below:

https://github.com/trustwallet/assets/pull/15593#issuecomment-968356154

### CODE REVIEW

**Comment by BillyBeat** [comment]
We now have full audit from Techrate, kindly check link, you also check it on our website and soon on Techrate socials.

https://babyflokizilla.com/wp-content/uploads/2021/11/techrate-audit.pdf

**Comment by BillyBeat** [comment]
As per the collaborator we can submit a new PR and use it as a reference that this request is alreaddy paid, please check reference below:

#15593 (comment)

**Comment by BillyBeat** [comment]
Hi Trustwallet Team,

We have paid for a previous PR and the collaborators put it on hold due the pending Techrate full audit. Now we have the audit and the collaborator said that once it’s released we can create a new PR and use the prev PR as reference to show that’s is paid.

Please check reference below:

https://github.com/trustwallet/assets/pull/15593#issuecomment-968356154

Thank you,

BillyBeat

BabyFlokiZilla Dev

**Comment by ramsty** [comment]
can you please add links to your PR
example:https://developer.trustwallet.com/assets/repository_details

**Comment by BillyBeat** [comment]
> Hi! Can you please add links to your PR example:https://developer.trustwallet.com/assets/repository_details

Hi Sir Ramsty! Really appreciate your fast reply. I tried checking your example guide regarding links, however, I am not sure which one. 

Are you pertaining to the token info? Thank you! :)

**Comment by ramsty** [comment]
description Utility token

**Comment by BillyBeat** [comment]
> Add link like in this example description Utility token

Got it!! I'm writing it now and uploading it as info.json right? Really appreciate your help sir, I only forked the contract, I'm not really a developer. So thank you for understanding! Give me like 3min! Thanks!

**Comment by BillyBeat** [comment]
> Hi! Can you please add links to your PR example:https://developer.trustwallet.com/assets/repository_details

I have the updated info.json file Sir Ramsty. How do I upload it to the pull request? I only followed the guide on Trustwallet wesbite, I don't really know how to reupload files here. Thank you.

**Comment by BillyBeat** [comment]
I think I was able to add links under Files Changed and editing. Please let me know if I did it right. Thank you!

**Comment by BillyBeat** [comment]
> Hi! Can you please add links to your PR example:https://developer.trustwallet.com/assets/repository_details

Hi Sir Ramsty. Please check if all links are okay. Thank you!!

**Comment by BillyBeat** [comment]
Thank you, Sir Ramsty! Our logo is up!! Thanks!!

Sent from Mail for Windows

**Pull request merged**
