### PR TITLE
Add Unagi Token (UNA) (ERC20, BEP20, POLYGON)

### PR DESCRIPTION
**Pull request by hmatthieu**
Adding info for ERC20 token 'Unagi Token (UNA)'.

PR created by <a href="https://assets.trustwallet.com">TW Assets Management</a>

### CODE REVIEW

**Comment by Cryptocool1** [comment]
• What is the purpose of this token? How will it benefit Trust Wallet users?
 • How is the token being distributed? Are you conducting an airdrop?
 • Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?
 • Is the token listed on a centralized/decentralized exchange?
 • Is a Smart Contract audit completed? Where can we find this information?

**Comment by Cryptocool1** [comment]
How did you get more than 15000 holders in 4 hours?

**Comment by hmatthieu** [comment]
> How did you get more than 15000 holders in 4 hours?

We airdropped our existing user. 

The inclusion of this token is directly tied to a recent migration where we transitioned from the old contract https://bscscan.com/token/0x7e9ab560d37e62883e882474b096643cab234b65 to the new one (https://bscscan.com/token/0x0b6f3ea2814f3fff804ba5d5c237aebbc364fba9) due to a broken bridge.

Here is the public announcement https://ultimatechampions.medium.com/una-token-rollout-a-new-chapter-begins-d2873bcb263d

**Comment by hmatthieu** [comment]
• What is the purpose of this token? How will it benefit Trust Wallet users?
It's a gaming ecosystem token. Holders can use this token in our games (https://ultimate-champions.com/). This token will be listed on multiple CEX/DEX allowing holders to trade the token.

• How is the token being distributed? Are you conducting an airdrop?
The token was airdrop to CHAMP holders. CHAMP token was distributed with a private sale and then in our game. CHAMP token was also listed on exchanges.

• Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?
CHAMP was sold in a token presale

• Is the token listed on a centralized/decentralized exchange?
CHAMP token was listed but UNA is not yet listed

• Is a Smart Contract audit completed? Where can we find this information?
We are using unmodified layerzero code (https://layerzero.network/). Their code have been audited https://github.com/LayerZero-Labs/Audits/tree/main/audits

**Comment by hmatthieu** [comment]
Hello !

FYI, token info updates are ongoing on bscscan & polygon scan, we can already see the result on etherscan:

Migration announced on CHAMP token in favor of UNA token
image

Links:
- [Etherscan CHAMP](https://etherscan.io/address/0x456125Cd98107ae0480Ba566f1b716D48Ba31453)
- [Etherscan UNA](https://etherscan.io/token/0x0b6f3ea2814f3fff804ba5d5c237aebbc364fba9)

Please note that this is the root UNA token, but we use bridged UNA token on bsc/polygon in our game (for lower fees).

**Comment by hmatthieu** [comment]
Hello @Cryptocool1, 

I believe we've addressed all the missing information. Please let us know if there's anything else required.

Thanks for your patience!

**Pull request merged**
