### PR TITLE
Add Pepe 2.0 (PEPE2.0) (ERC20)

### PR DESCRIPTION
**Pull request by yamennajjar80**
Adding info for ERC20 token 'Pepe 2.0 (PEPE2.0)'.

PR created by <a href="https://assets.trustwallet.com">TW Assets Management</a>

### CODE REVIEW

**Comment by Cryptocool1** [comment]
Submission looks good, awaiting for the fee payment

**Comment by yamennajjar80** [comment]
> 25673

TWT withdraw BEP2 is suspended on Binance, we need BEP20 address

**Comment by yamennajjar80** [comment]
> **25673**

5 BNB payed

**Comment by yamennajjar80** [comment]
> Submission looks good, awaiting for the fee payment

All done

**Comment by yamennajjar80** [comment]
@Iamdeadlyz, @Cryptocool1, @cryptomanz1
Hello,
is there anything requested to get the update done?

**Pull request merged**
