### PR TITLE
adding MOONI

### PR DESCRIPTION
**Pull request by mooni-defi**
adding logo and Info for MOONI

### CODE REVIEW

**Comment by catenocrypt** [comment]
submission looks OK; awaiting fee payment.

**Comment by mooni-defi** [comment]
> submission looks OK; awaiting fee payment.

**Comment by mooni-defi** [comment]
> submission looks OK; awaiting fee payment.

We paid. Do you have a chance to add the logo immediately?

**Comment by mooni-defi** [comment]
Is there any progress on the subject? @catenocrypt @zachzwei

Best regards.

**Pull request merged**
