### PR TITLE
Please add uTOPIA logo

### PR DESCRIPTION
**Pull request by AvantgardeScott**
Hello,

I would like to add uTOPIA logo to the repo.

Contract address: 0x1f8f123bf24849443a56ed9fc42b9265b7f3a39a
Attached 256x256 png logo here

Please let me know how to proceed.
logo

### CODE REVIEW

**Comment by catenocrypt** [comment]
Please do the PR from a recent branch.  First update master branch (pull), then add the new file, and create a new PR.

**Comment by TRONtopia** [comment]
I'm so sorry... I don't use github that much haha... am I save to send payment to that address commented above? Also, do I need to close this and create a new pull request? I am not sure what exactly to do.

**Comment by catenocrypt** [comment]
One thing is that there are 9 changed files in this PR, when in reality I think you just want to add one.

image

Then your fork name does not show up properly, it shows `${GITHUB_REF}`, which is quite unusual.  As a result, I cannot fix this PR myself.

image

My suggestion:
- Close this PR
- If you have created a fork already, delete it
- Create a new fork
- Add your logo
- Create a PR (to assets/master)
- A comment will appear there with the destination address and memo for fee payment
- Pay the fee
Once the PR has been created, I can assist if needed (e.g. if logo is in wrong folder).

**Comment by TRONtopia** [comment]
You rock thank you! Will take care of this in the morning and close this for now

**Pull request closed without merging**
