### PR TITLE
Add Axelar Wrapped USDC (axlUSDC)

### PR DESCRIPTION
**Pull request by cryptomanz1**

### CODE REVIEW

**Review by ecdsafu — COMMENTED** [review]
looks good to me

**Review by vcoolish — APPROVED** [review]

**Comment by defisaur** [comment]
Added to https://github.com/trustwallet/assets/pull/26921

**Review by Salarmahmo — COMMENTED** [review]
@Salarmahmoudsalarvand1362

**Comment by psone0992-ship-it** [comment]
Thanks

**Pull request closed without merging**
