### PR TITLE
Velorex Logo and info.json

### PR DESCRIPTION
**Pull request by Verifyde**
Uploaded logo and info file for Velorex token

### CODE REVIEW

**Comment by Verifyde** [comment]
Paid

**Comment by cryptomanz** [comment]
Hello,
- Correction needed:
- This is a BEp20 token, correct folder is blockchains/smartchain/assets.
- Please correct.

**Comment by Verifyde** [comment]
Uploaded to correct location - struggling to delete the incorrect one

**Comment by Cryptocool1** [comment]
can you please add links to your PR?
example: https://developer.trustwallet.com/add_new_asset#info-json-contents

**Comment by Verifyde** [comment]
Ok that should be done - thank you

**Pull request merged**
