### PR TITLE
Add Logo

### PR DESCRIPTION
**Pull request by MagLiC**

### CODE REVIEW

**Comment by MagLiC** [comment]
already pay. please check and merge

**Comment by MagLiC** [comment]
I have paid it, but you don't seem to have received it.

**Comment by MagLiC** [comment]
I need help. please

**Comment by MagLiC** [comment]
my address is bnb10af52w77pkehgxhnwgeca50q2t2354q4xamz5y.

**Comment by MagLiC** [comment]
?

**Comment by catenocrypt** [comment]
Note on why it was only marked later: as I see first payment was only TWT 920, that's why PR was not marked as payed.  After additional payment of 320, it became sufficient.

**Pull request merged**
