### PR TITLE
Update DFT logo.png

### PR DESCRIPTION
**Pull request by hai-der**
Update to transparent logo

### CODE REVIEW

**Comment by hai-der** [comment]
Payment submitted.

**Comment by hai-der** [comment]
Hi @zachzwei and @catenocrypt. Any requirements missing here?

**Comment by vikmeup** [comment]
> Hi @zachzwei and @catenocrypt. Any requirements missing here?

Can you please include `info.json` file for the token. 

Here is an example for DAI: https://github.com/trustwallet/assets/blob/master/blockchains/ethereum/assets/0x6B175474E89094C44Da98b954EedeAC495271d0F/info.json

**Comment by vikmeup** [comment]
Should be good to be merged then

**Pull request merged**
