### PR TITLE
add antimatter bep20 tokeninfo and logo

### PR DESCRIPTION
**Pull request by superzitao**

### CODE REVIEW

**Comment by Iamdeadlyz** [comment]
`0x1C9491865a1DE77C5b6e19d2E6a5F1D7a6F2b25F` is already added, check #5741. Please remove it in this PR to solve the conflicting files.

**Comment by superzitao** [comment]
revert to the previous version

**Comment by superzitao** [comment]
> `0x1C9491865a1DE77C5b6e19d2E6a5F1D7a6F2b25F` is already added, check #5741. Please remove it in this PR to solve the conflicting files.

I have revert logo file to the previous version

**Comment by superzitao** [comment]
> `0x1C9491865a1DE77C5b6e19d2E6a5F1D7a6F2b25F` is already added, check #5741. Please remove it in this PR to solve the conflicting files.

Can I close this pull request then create a new pull request?

**Comment by superzitao** [comment]
> `0x1C9491865a1DE77C5b6e19d2E6a5F1D7a6F2b25F` is already added, check #5741. Please remove it in this PR to solve the conflicting files.

Hello @Iamdeadlyz can I close this pull request then create a new pull request?

**Comment by catenocrypt** [comment]
Yes, it it's easier, create a new one.  Mention this one, to consider fee paid for this one.

**Comment by superzitao** [comment]
> Yes, it it's easier, create a new one. Mention this one, to consider fee paid for this one.
Seems 


> Yes, it it's easier, create a new one. Mention this one, to consider fee paid for this one.

Can I s

**Comment by superzitao** [comment]
> Yes, it it's easier, create a new one. Mention this one, to consider fee paid for this one.

Hello @catenocrypt I have solved the conflicting files.

**Comment by catenocrypt** [comment]
This PR is OK now.

**Pull request merged**
