### PR TITLE
Change folder names to checksum

### PR DESCRIPTION
**Pull request by sidko**
See #1017

### CODE REVIEW

**Comment by vikmeup** [comment]
Here is an example: https://github.com/trustwallet/assets/commit/c3333d30230144e6a2a34869f495abebc639ad9d, it show my changes correctly for folder rename

**Comment by sidko** [comment]
The commit above shows the rename of these exact 4 folders. Does it mean the rename has already taken place?

**Comment by vikmeup** [comment]
Yes, I did rename it yesterday. I just created an issue that CI would verify addresses on each PR.

**Comment by sidko** [comment]
Ah amazing, thanks for being so on top of this! I think this PR can be closed now - the purpose was just to make sure the rename went through. I'll add more logos for social money in another PR for your review.

**Pull request closed without merging**
