### PR TITLE
Add TWT logo and info

### PR DESCRIPTION
**Pull request by mostermas**
Lucid Lands (LLG) - Have 5500 holders and 35k that was enough for logo update , my mail medmaxacc@gmail.com

### CODE REVIEW

**Comment by Cryptocool1** [comment]
As per our policy, brand new tokens are not included, there is a minimum requirement of 10,000 holder addresses and 20,000 transactions, in order to filter out scam tokens.
See the criteria at : https://developer.trustwallet.com/assets/requirements .

**Comment by Cryptocool1** [comment]
This is a BEP20 token, correct folder is blockchains/smartchain/assets.

**Comment by mostermas** [comment]
Moved to   blockchains/smartchain/assets.

ср, 22 дек. 2021 г. в 21:06, CryptoA ***@***.***>:

**Comment by mostermas** [comment]
Yes we know , our token not new, not airdroped or other things.
We  trending on CMC and CG .
We have 35k transactions, so we hope you will update it.

ср, 22 дек. 2021 г. в 21:05, CryptoA ***@***.***>:

**Comment by cryptomanz** [comment]
Please come back to us when all criteria are met.
When creating a new PR make sure to mention this PR, so that we can see that fee has been paid already here.

**Comment by mostermas** [comment]
Come on! You add logo to Dogedi with 4k holders, add it to a lot of other
coins!
Our coin is trending on CMC on CG , and we are on all platforms , we have
ready game, ready product ( app) , what is wrong?
Please update us!

чт, 23 дек. 2021 г. в 16:25, Nazar ***@***.***>:

**Comment by mostermas** [comment]
https://github.com/trustwallet/assets/pull/16750 we have 10k

чт, 23 дек. 2021 г. в 18:00, MAD MAX ***@***.***>:

**Pull request closed without merging**
