### PR TITLE
Add files via upload

### PR DESCRIPTION
**Pull request by dragonmoon001**

### CODE REVIEW

**Comment by Cryptocool1** [comment]
correction needed:
Contract is not in checksum format, should be 0x8267d169E1483E01AACBCfd22d294c47ECE9F07f

**Comment by dragonmoon001** [comment]
Changed the contract letter case.

**Comment by Cryptocool1** [comment]
correction still needed:
Contract is not in checksum format, should be 0x8267d169E1483E01AACBCfd22d294c47ECE9F07f
 I suggest to create a new PR (and mention this one so that fee does not have to be paid again).
 • You may use our Assets app (in beta); close this PR; go to https://assets.trustwallet.com, log on with Github, enter contract ID, logo and some additional info, and it will create a PR for you. See https://community.trustwallet.com/t/how-to-submit-a-token-logo-using-assets-app/82957\

**Comment by dragonmoon001** [comment]
> correction still needed:
> Contract is not in checksum format, should be 0x8267d169E1483E01AACBCfd22d294c47ECE9F07f
> I suggest to create a new PR (and mention this one so that fee does not have to be paid again).
> • You may use our Assets app (in beta); close this PR; go to https://assets.trustwallet.com, log on with Github, enter contract ID, logo and some additional info, and it will create a PR for you. See [https://community.trustwallet.com/t/how-to-submit-a-token-logo-using-assets-app/82957\](https://community.trustwallet.com/t/how-to-submit-a-token-logo-using-assets-app/82957%5C)

I tried to submit a new merger request on Assets.trustWallet.com, but the visiting of our website could not be prompted when testing. Can you help me do it in your existing merger?

**Comment by dragonmoon001** [comment]
> correction still needed:
> Contract is not in checksum format, should be 0x8267d169E1483E01AACBCfd22d294c47ECE9F07f
> I suggest to create a new PR (and mention this one so that fee does not have to be paid again).
> • You may use our Assets app (in beta); close this PR; go to https://assets.trustwallet.com, log on with Github, enter contract ID, logo and some additional info, and it will create a PR for you. See [https://community.trustwallet.com/t/how-to-submit-a-token-logo-using-assets-app/82957\](https://community.trustwallet.com/t/how-to-submit-a-token-logo-using-assets-app/82957%5C)

image
We tried to apply again, but entering https://www.dmoon.xyz/ will display Website does not exist, status 40, but our webpage has been working normally

**Comment by Cryptocool1** [comment]
> > correction still needed:
> > Contract is not in checksum format, should be 0x8267d169E1483E01AACBCfd22d294c47ECE9F07f
> > I suggest to create a new PR (and mention this one so that fee does not have to be paid again).
> > • You may use our Assets app (in beta); close this PR; go to https://assets.trustwallet.com, log on with Github, enter contract ID, logo and some additional info, and it will create a PR for you. See [https://community.trustwallet.com/t/how-to-submit-a-token-logo-using-assets-app/82957](https://community.trustwallet.com/t/how-to-submit-a-token-logo-using-assets-app/82957%5C)
> 
> image
> We tried to apply again, but entering https://www.dmoon.xyz/ will display Website does not exist, status 40, but our webpage has been working normally

try click on create PR
closing this PR for now.
Please come back to us when all criteria are met. (you don't need to pay one more time, but make sure to mention this PR in the new one)

**Comment by dragonmoon001** [comment]
Hello, we have waited for about 30 days, and we still can't see the LOGO, including some data that has not been included by Panckswap. Our current number of transactions and currency holders has exceeded 10,000.

**Comment by cryptomanz** [comment]
> Hello, we have waited for about 30 days, and we still can't see the LOGO, including some data that has not been included by Panckswap. Our current number of transactions and currency holders has exceeded 10,000.

that is because your token not merged

**Pull request closed without merging**
