### PR TITLE
Add Infinity Rocket Token (BEP20)

### PR DESCRIPTION
**Pull request by InfinityRocket**
Adding info for BEP20 token 'Infinity Rocket Token'.

PR created by <a href="https://assets.trustwallet.com">TW Assets Management</a>

### CODE REVIEW

**Comment by cryptomanz** [comment]
• What is the purpose of this token? How will it benefit Trust Wallet users?
 • How is the token being distributed? Are you conducting an airdrop?
 • Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?
 • Is the token listed on a centralized/decentralized exchange?
 • Is a Smart Contract audit completed? Where can we find this information?

**Comment by InfinityRocket** [comment]
On main website irocket.pro

**Comment by InfinityRocket** [comment]
On main website https://irocket.pro/

**Comment by InfinityRocket** [comment]
Sir, will it take time to add the logo ??

**Comment by Cryptocool1** [comment]
Can you answer the questions @cryptomanz asked?

**Comment by InfinityRocket** [comment]
Answers:

• What is the purpose of this token? How will it benefit Trust Wallet users?

• Infinity Rocket (IRT) is a launchpad platform that allows launching any blockchain and NFT projects, as well as creating and listing tokens on exchanges. The project team has extensive experience in blockchain development and launches of an exchange asset. It’s definitely a great mix of skills, knowledge, and a masterpiece.

Having an asset in the wallet gives holders the privilege of participating in the launchpads that take place on the Infinity Rocket platform. Additionally, you get the opportunity to participate in coin presales at the lowest prices, as well as contests and airdrops.


• How is the token being distributed? Are you conducting an airdrop?

Here the token distribution: https://irocket.pro/#token
Also we provided one small airdrop in february 2022.

• Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?

Part of tokens was sold on Pancake swap and Coinsbit. Most part of tokens are locked for now via our tokenomics. 

• Is the token listed on a centralized/decentralized exchange?

Now IRT is listed on Pancake Swap and Coinsbit. 

• Is a Smart Contract audit completed? Where can we find this information?

Here the audits from Dessert Swap and TechRate: 
https://dessertswap.finance/audits/Infinity%20Rocket%20BSC%20Audit%2012789501.pdf



https://github.com/TechRate/Smart-Contract-Audits/blob/main/December/Infinity%20Rocket%20Token%20Full%20Smart%20Contract%20Security%20Audit.pdf

**Comment by InfinityRocket** [comment]
• What is the purpose of this token? How will it benefit Trust Wallet users?

• Infinity Rocket (IRT) is a launchpad platform that allows launching any blockchain and NFT projects, as well as creating and listing tokens on exchanges. The project team has extensive experience in blockchain development and launches of an exchange asset. It’s definitely a great mix of skills, knowledge, and a masterpiece.

Having an asset in the wallet gives holders the privilege of participating in the launchpads that take place on the Infinity Rocket platform. Additionally, you get the opportunity to participate in coin presales at the lowest prices, as well as contests and airdrops.


• How is the token being distributed? Are you conducting an airdrop?

Here the token distribution: https://irocket.pro/#token
Also we provided one small airdrop in february 2022.

• Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?

Part of tokens was sold on Pancake swap and Coinsbit. Most part of tokens are locked for now via our tokenomics. 

• Is the token listed on a centralized/decentralized exchange?

Now IRT is listed on Pancake Swap and Coinsbit. 

• Is a Smart Contract audit completed? Where can we find this information?

Here the audits from Dessert Swap and TechRate: 
https://dessertswap.finance/audits/Infinity%20Rocket%20BSC%20Audit%2012789501.pdf



https://github.com/TechRate/Smart-Contract-Audits/blob/main/December/Infinity%20Rocket%20Token%20Full%20Smart%20Contract%20Security%20Audit.pdf

**Comment by InfinityRocket** [comment]
@cryptomanz  Sir, will it take time to add the logo ??

**Comment by InfinityRocket** [comment]
@cryptomanz  Sir, logo need to fix

photo_2022-02-20_18-10-54
photo_2022-02-20_18-13-41

**Comment by InfinityRocket** [comment]
@cryptomanz Sir, logo need to fix

**Comment by InfinityRocket** [comment]
@cryptomanz Sir, logo need to fix

**Pull request merged**
