### PR TITLE
Add EG Token (BEP20). Upgrade from existing ELONGATE token

### PR DESCRIPTION
**Pull request by HasanAziz1**
Adding info for BEP20 token 'EG Token'.

PR created by <a href="https://assets.trustwallet.com">TW Assets Management</a>

### CODE REVIEW

**Comment by HasanAziz1** [comment]
ELONGATE Token is already listed on TW. We upgraded smart contract to a V2 token called EG Token and new holders are migrating to it. Kindly add this asset to TrustWallet.

**Comment by HasanAziz1** [comment]
Youtube link is valid but shows up as invalid for some reason

**Comment by Cryptocool1** [comment]
> ELONGATE Token is already listed on TW. We upgraded smart contract to a V2 token called EG Token and new holders are migrating to it. Kindly add this asset to TrustWallet.

Is Elongate token abandoned for now?
Please send official announcement here

**Comment by HasanAziz1** [comment]
> > ELONGATE Token is already listed on TW. We upgraded smart contract to a V2 token called EG Token and new holders are migrating to it. Kindly add this asset to TrustWallet.
> 
> Is Elongate token abandoned for now? Please send official announcement here

Yes, ELONGATE token is no longer tradeable. Holders are migrating to EG Token. Please see the following verifications:

1. elongate.cc redirects to egtoken.io
2. Public Announcement - https://news.egtoken.io/1596
3. Relaunch News - https://news.egtoken.io/1619
4. CoinGecko listing - https://www.coingecko.com/en/coins/eg-token
5. MEXC Exchange announcement to migrate ELONGATE holders to EG Token - https://support.mexc.com/hc/en-001/articles/15726491479705-MEXC-Will-Support-ELONGATE-ELONGATE-Token-Swap-Redenomination-Rebranding-Plan-to-EG-Token-EG-
6. MEXC Confirmation of Migration Completed - https://support.mexc.com/hc/en-001/articles/15928547086361-MEXC-Completes-ELONGATE-ELONGATE-Token-Swap-to-EG-Token-EG-

**Comment by HasanAziz1** [comment]
Kindly confirm when its all ok and we will transfer 5 BNB payment. Thanks for your support

**Comment by Cryptocool1** [comment]
What is the old contract address?

**Comment by HasanAziz1** [comment]
> What is the old contract address?

0x2A9718defF471f3Bb91FA0ECEAB14154F150a385

https://bscscan.com/token/0x2A9718defF471f3Bb91FA0ECEAB14154F150a385

**Comment by Cryptocool1** [comment]
Thank you! 
I need a message on bscscan or at least on CMC page that your token is migrating

**Comment by HasanAziz1** [comment]
@Cryptocool1 is it ok to make the payment now? getting reminders so just want to check if you are ok to proceed? Thanks

**Comment by Cryptocool1** [comment]
As I said before for migration you will need a message on bscscan or at least in CoinMarketCap. 
Or if you want to add it as new token you should prepare smart contract audit from reputable companies

**Comment by HasanAziz1** [comment]
> As I said before for migration you will need a message on bscscan or at least in CoinMarketCap. Or if you want to add it as new token you should prepare smart contract audit from reputable companies

Here are 2 audits:
Vidma: https://www.vidma.io/audit/egtoken
PeckShield: https://github.com/peckshield/publications/blob/master/audit_reports/PeckShield-Audit-Report-BEP20-EG-v1.0.pdf

**Comment by HasanAziz1** [comment]
Whats the difference between migration and adding as a new token on TrustWallet?

**Comment by HasanAziz1** [comment]
> > > As I said before for migration you will need a message on bscscan or at least in CoinMarketCap. Or if you want to add it as new token you should prepare smart contract audit from reputable companies
> > 
> > 
> > Here are 2 audits: Vidma: https://www.vidma.io/audit/egtoken PeckShield: https://github.com/peckshield/publications/blob/master/audit_reports/PeckShield-Audit-Report-BEP20-EG-v1.0.pdf
> 
> I can’t find your contract address there. Can you check?

Pre deploy audits don't have smart contract address as ours was done before mainnet deploy. It will just have a link to our official github repository containing the code with a commit hash to latest code version.

**Comment by cryptomanz1** [comment]
Submission looks good. Awaiting fee payment.

**Comment by HasanAziz1** [comment]
> Submission looks good. Awaiting fee payment.

Thankyou. Fee is paid now

**Pull request merged**
