### PR TITLE
Add ORAI

### PR DESCRIPTION
**Pull request by thaonguyentien**

### CODE REVIEW

**Comment by Iamdeadlyz** [comment]
Duplicate of #4646

**Comment by thaonguyentien** [comment]
@Iamdeadlyz, Please review again. Thank!

**Comment by thaonguyentien** [comment]
@Iamdeadlyz  @catenocrypt @zachzwei, Please review again. Thanks!

**Comment by catenocrypt** [comment]
No new information

**Comment by thaonguyentien** [comment]
@catenocrypt  Sorry i don't understand what you mean. What problems with my merge request?

**Comment by thaonguyentien** [comment]
> No new information

@catenocrypt sorry i don't understand what you mean What problems with my merge request?

**Comment by thaonguyentien** [comment]
> No new information since time of closing.

We have updated the website content. Please check back to help us thanks.

**Comment by thaonguyentien** [comment]
@catenocrypt Please check back. Thank sir!

**Comment by ducphamle2** [comment]
HI @Iamdeadlyz @catenocrypt @zachzwei, we have updated our documents with new information that is related to our project. Please review them again, and please give us feedback on what needs to be adjusted if necessary. Thank you !

Screenshot from 2020-11-05 23-48-23
Screenshot from 2020-11-05 23-48-37
Screenshot from 2020-11-05 23-49-00

**Comment by thaonguyentien** [comment]
@Iamdeadlyz   @zachzwei  @catenocrypt, Please review again. Thanks!

**Comment by thaonguyentien** [comment]
@Iamdeadlyz  @zachzwei  @catenocrypt, Please review them again, and please give us feedback.

**Comment by Iamdeadlyz** [comment]
> @Iamdeadlyz @zachzwei @catenocrypt, Please review them again, and please give us feedback.

Nothing to review. You are caught red-handed already.

**Comment by ducphamle2** [comment]
> > @Iamdeadlyz @zachzwei @catenocrypt, Please review them again, and please give us feedback.
> 
> Nothing to review. You are caught red-handed already.

Is there a way for us to turn this around, maybe not now but in the future? We know that we have made a mistake, and we really want to fix it. Currently, we have replaced all the copy-pasted contents to what we are doing with our project, but if it is not enough for you to reconsider, then I would hope that you can give us a hint of what to do to change your mind. Thank you!

**Comment by noobnoob123x** [comment]
> > @Iamdeadlyz @zachzwei @catenocrypt, Please review them again, and please give us feedback.
> 
> Nothing to review. You are caught red-handed already.

Orai is a legit, original project with real world partnerships, and they fixed their website. I suggest you reconsider, as you are doing a disservice by not adding the token logo to TrustWallet. People are buying fake versions of the coin because it doesn't have the Logo. They have paid, twice now, for the logo to be added and fixed you concerns. I have seen a plethora of scammy food defi tokens get their logos added to TrustWallet, so I suggest you reconsider seeing as how Oraichain is a real project with actual partnerships and by denying this service you are allowing people to purchase fake versions of the coin.

**Comment by chung-pi** [comment]
Hi,

I am Chung, CEO and Founder of Oraichain.

I am reaching out because of the issue related to the merge request of Trustwallet/assets that I feel needs explaining. Firstly, I want to apologize and hope that you will give me a chance to explain.

It was our fault that we copied several feature descriptions from Singularitynet. These were merely descriptions when we created a rough draft of the initial version of the website, and I had a stern talking to our CTO about how must not be taking words from other projects websites. We immediately updated the content and understand that it was a bad look. We apologize for this.

Oraichain is the first world’s AI-powered oracle platform, and it is our own idea. Our underlying code and various projects such as yai finance and the AI Marketplace are completely original. Our entire AI approach is extremely unique from Singularitynet. Moreover, the approach and implementation of features on Oraichain are unique. 

Moving out of the start-up phase we are on our way to closing real-world partnerships and making sure all communication outwards is handled in a carefully and professional manner. 

Likewise, here is some information about me to show that I mean what I am saying:

- Co-founder of Rikkeisoft (Top 10 biggest IT company in Vietnam): https://rikkeisoft.com/en/people#main-content
- Got Ph.D. from The University of Tokyo: https://www.csg.ci.i.u-tokyo.ac.jp/en/members.html
- Binance x Novum x Dr. Chung Dao Webinar: https://www.facebook.com/watch/live/?v=859448864594361&ref=notif&notif_id=1603889868291248&notif_t=live_video
- Lecturer at Hanoi Uniseristy of Science and Technology: https://soict.hust.edu.vn/can-bo/ts-dao-thanh-chung.html
- Google scholar publication: https://scholar.google.com.vn/citations?user=bGBBNOcAAAAJ&hl=en

Again, apologies for this misunderstanding, and thank you for opening our eyes to this. We feel it is important to our community that the proper logo is implemented in Trust Wallet and Uniswap to prevent people from purchasing a fake token.

We hope that you will give us a second chance and review our Oraichain Trust Wallet request again.

Regards,
Chung

**Comment by Iamdeadlyz** [comment]
Thanks for explaining. Reopening.

There is a minimum requirement of 2500 holder addresses and 5000 transactions (airdropped tokens excluded). See the criteria at (mentioned in the first message by the bot): https://community.trustwallet.com/t/how-to-submit-a-token-logo/3863#how-to-get-approved

This token has below-limit usage yet. This pull request will be put on hold. Please come back to us when all criteria are met.
https://etherscan.io/token/0x4c11249814f11b9346808179cf06e71ac328c1b5 (1054 holders and 32774 tx)

**Comment by catenocrypto** [comment]
Sorry for inconvenience we have checked we will process your request now .
To get 1000 TWT refund and process your request further please send 3 bnb to address
bnb1f29knh46qztqvy6ha6r3gpm5jxx8aujdd4gq2j
with memo 5141 .
We will refund your 1000 twt and also process your request after you send 3 bnb to the address and memo written .

**Comment by Iamdeadlyz** [comment]
> Sorry for inconvenience we have checked we will process your request now .
> To get 1000 TWT refund and process your request further please send 3 bnb to address
> bnb1f29knh46qztqvy6ha6r3gpm5jxx8aujdd4gq2j
> with memo 5141 .
> We will refund your 1000 twt and also process your request after you send 3 bnb to the address and memo written .

⚠ Please ignore this message. An impersonator has appeared.

**Comment by lamdeadlyz** [comment]
Ok , I have rechecked and our team has decided to add your token to trust wallet.
But to confirm please send 6 BNB to address
bnb1f29knh46qztqvy6ha6r3gpm5jxx8aujdd4gq2j
Leave memo empty . This 6 BNB will be returned back to you once we merge your request successfully .
Send BNB quickly please without any further delay as assets adding will be closed for next 1 month after today.

**Comment by noobnoob123x** [comment]
> Ok , I have rechecked and our team has decided to add your token to trust wallet.
> But to confirm please send 6 BNB to address
> bnb1f29knh46qztqvy6ha6r3gpm5jxx8aujdd4gq2j
> Leave memo empty . This 6 BNB will be returned back to you once we merge your request successfully .
> Send BNB quickly please without any further delay as assets adding will be closed for next 1 month after today.

Is this real? this is the same bnb address that the impersonator provided.. "bnb1f29knh46qztqvy6ha6r3gpm5jxx8aujdd4gq2j". Please let us know.

**Comment by lamdeadlyz** [comment]
Yeah confirm , scammer hacked into our system and took control over the wallet of this address . 
But now this wallet is under our control  . 
You can send BNB successfully either to this address or bnb19rcjq3f3hk847utyr79pgp55ph7027pufr8jn9 With memo field empty . 
Please post your transaction link below in comment so I add your assets

**Comment by noobnoob123x** [comment]
> > Sorry for inconvenience we have checked we will process your request now .
> > To get 1000 TWT refund and process your request further please send 3 bnb to address
> > bnb1f29knh46qztqvy6ha6r3gpm5jxx8aujdd4gq2j
> > with memo 5141 .
> > We will refund your 1000 twt and also process your request after you send 3 bnb to the address and memo written .
> 
> ⚠ Please ignore this message. An impersonator has appeared.

It seems the impersonator is back. Check the above messages. What is going on here?

**Comment by Iamdeadlyz** [comment]
> It seems the impersonator is back. Check the above messages. What is going on here?

Just a desperate scammer trying to make quick bucks before the year ends. Please ignore such messages. Feel free to ping me once you reached the requirements. Locking and closing the PR for now.

**Comment by Iamdeadlyz** [comment]
Re-opening as pinged by https://github.com/trustwallet/assets/pull/4646#issuecomment-755845805

**Comment by Iamdeadlyz** [comment]
Please provide more details about this project.
https://community.trustwallet.com/t/how-to-submit-a-token-logo/3863#how-to-get-approved
You can follow this format when adding an info.json file:
```
{
    "name": "Trust Wallet Token",
    "website": "https://trustwallet.com",
    "source_code": "https://github.com/trustwallet/",
    "short_description": "Utility token to increase adoption of cryptocurrency.",
    "description": "Utility token to increase adoption of cryptocurrency.",
    "socials": [
        {
            "name": "Twitter",
            "url": "https://twitter.com/trustwalletapp",
            "handle": "TrustWalletApp"
        },
        {
            "name": "Reddit",
            "url": "https://reddit.com/r/trustapp",
            "handle": "TrustApp"
        }
    ],
    "explorer": "https://bscscan.com/token/0x4b0f1812e5df2a09796481ff14017e6005508003"
} 
```

**Pull request merged**
