### PR TITLE
Add AmazingDoge logo and info

### PR DESCRIPTION
**Pull request by AmazingDogebsc**
Add AmazingDoge logo and info

### CODE REVIEW

**Comment by AmazingDogebsc** [comment]
TxHash:
7D0D58620C2E299057B893E35BC501DDDE0196689141522ED160E5C05D93F058

**Comment by cryptomanz** [comment]
• What is the purpose of this token? How will it benefit Trust Wallet users?
 • How is the token being distributed? Are you conducting an airdrop?
 • Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?
 • Is the token listed on a centralized/decentralized exchange?
 • Is a Smart Contract audit completed? Where can we find this information?

**Comment by AmazingDogebsc** [comment]
• 这个令牌的目的是什么？ 它将如何使 Trust Wallet 用户受益？
>回复：该令牌主要做NFT和Gamefi，可以使Trust Wallet的用户获得空投，以及购买NFT获得代币奖励的权限。
• 代币是如何分配的？ 你在进行空投吗？
>代币在UNICRYPT进行的公开预售，60%预售，40%添加流动性池；
   目前已经燃烧20%
• 您是否在首次代币发行 (ICO) 或代币预售中出售了代币？
在UNICRYPT进行的预售
• 代币是否在中心化/去中心化交易所上市？
目前已经登录了PancakeV2交易所，以及ZT 交易所
• 智能合约审计是否完成？ 我们在哪里可以找到这些信息？ 
智能合约审计已经完成，这是审计报告的链接：https://github.com/solidproof/projects/tree/main/AmazingDoge

持有人：10516
https://bscscan.com/token/0x0EBc30459551858e81306d583025d12C7d795FA2

**Comment by AmazingDogebsc** [comment]
• This token is mainly used for NFT and Gamefi, which enables users of Trust Wallet to get airdrops and the right to purchase NFT to get token rewards.
• Public pre-sale of tokens in UNICRYPT, 60% pre-sale, 40% adding liquidity pool;
• Pre-sale at UNICRYPT
• Currently logged in PancakeV2 exchange and ZT exchange
• The smart contract audit has been completed, here is the link to the audit report:
    https://github.com/solidproof/projects/tree/main/AmazingDoge
• Holder: 10516
https://bscscan.com/token/0x0EBc30459551858e81306d583025d12C7d795FA2

**Comment by cryptomanz** [comment]
Can you send audit in pdf format?

**Comment by AmazingDogebsc** [comment]
Audit in pdf format:
https://raw.githubusercontent.com/solidproof/projects/main/AmazingDoge/SmartContract_Audit_Solidproof_AmazingDoge.pdf

**Review by Bigboy1982 — COMMENTED** [review]
Perfecto

**Pull request merged**
