### PR TITLE
Add Crowns Token logo. ERC-20 token of Seascape Network

### PR DESCRIPTION
**Pull request by ahmetson**

### CODE REVIEW

**Comment by Iamdeadlyz** [comment]
Please provide more details about this project.
https://community.trustwallet.com/t/how-to-submit-a-token-logo/3863#how-to-get-approved
You can follow this format when adding an info.json file:
```
{
    "name": "Trust Wallet Token",
    "website": "https://trustwallet.com",
    "source_code": "https://github.com/trustwallet/",
    "short_description": "Utility token to increase adoption of cryptocurrency.",
    "description": "Utility token to increase adoption of cryptocurrency.",
    "socials": [
        {
            "name": "Twitter",
            "url": "https://twitter.com/trustwalletapp",
            "handle": "TrustWalletApp"
        },
        {
            "name": "Reddit",
            "url": "https://reddit.com/r/trustapp",
            "handle": "TrustApp"
        }
    ],
    "explorer": "https://bscscan.com/token/0x4b0f1812e5df2a09796481ff14017e6005508003"
} 
```

Also, please fix the checksum issue by following this:
- Rename the folder to `0xaC0104Cca91D167873B8601d2e71EB3D4D8c33e0-x`, commit, and push
- Rename it again to `0xaC0104Cca91D167873B8601d2e71EB3D4D8c33e0`, commit, then push

**Comment by Iamdeadlyz** [comment]
Still getting checksum issues.
image

Please follow this:
- Rename the folder to `0xaC0104Cca91D167873B8601d2e71EB3D4D8c33e0-x`, commit, and push
- Rename it again to `0xaC0104Cca91D167873B8601d2e71EB3D4D8c33e0`, commit, then push

**Comment by ahmetson** [comment]
Pushed new commits to fix the checksum.

**Comment by ahmetson** [comment]
> Still getting checksum issues.
> image
> 
> Please follow this:
> 
> * Rename the folder to `0xaC0104Cca91D167873B8601d2e71EB3D4D8c33e0-x`, commit, and push
> * Rename it again to `0xaC0104Cca91D167873B8601d2e71EB3D4D8c33e0`, commit, then push

Pushed, please have a look.

**Comment by Iamdeadlyz** [comment]
As per our policy, brand new tokens are not included. There is a minimum requirement of 2500 holder addresses and 5000 transactions (airdropped tokens excluded) in order to filter out scam tokens. See the criteria at (mentioned in the first message by the bot): https://community.trustwallet.com/t/how-to-submit-a-token-logo/3863#how-to-get-approved

This token has below-limit usage yet. This pull request will be put on hold. Please come back to us when all criteria are met. Just comment here so I can fix & merge. Note: You don't need to pay again.
https://etherscan.io/token/0xac0104cca91d167873b8601d2e71eb3d4d8c33e0

**Comment by zachzwei** [comment]
reviewing.

**Comment by ahmetson** [comment]
> reviewing.

Fixed the json file issue, please have a look.

**Comment by catenocrypt** [comment]
I have no permission to update the files in this PR, please change info.json to:

```json
{
    "name": "Crowns",
    "type": "ERC20",
    "symbol": "CWS",
    "decimals": 18,
    "website": "https://www.seascape.network",
    "source_code": "https://github.com/blocklords/seascape-smartcontracts",
    "description": "Crowns are the official token of the Seascape Network. They are designed to reward all key stakeholders within the network. The Seascape Network is an incentivized ecosystem consisting of gamers, developers, and influencers with the purpose of bringing DeFi gaming to a broader userbase.",
    "socials": [
        {
            "name": "Twitter",
            "url": "https://twitter.com/seascapenetwork",
            "handle": "SeascapeNetwork"
        },
        {
            "name": "Reddit",
            "url": "https://www.reddit.com/r/SeascapeNetwork",
            "handle": "SeascapeNetwork"
        },
        {
            "name": "Telegram",
            "url": "https://t.me/seascapenetwork",
            "handle": "SeascapeNetwork"
        },
        {
            "name": "Discord",
            "url": "https://discord.com/invite/qG2Vynh",
            "handle": "SeascapeNetwork"
        }
    ],
    "explorer": "https://etherscan.io/token/0xac0104cca91d167873b8601d2e71eb3d4d8c33e0",
    "id": "0xaC0104Cca91D167873B8601d2e71EB3D4D8c33e0"
}
```

**Comment by ahmetson** [comment]
> I have no permission to update the files in this PR, please change info.json to:
> 
> ```json
> {
>     "name": "Crowns",
>     "type": "ERC20",
>     "symbol": "CWS",
>     "decimals": 18,
>     "website": "https://www.seascape.network",
>     "source_code": "https://github.com/blocklords/seascape-smartcontracts",
>     "description": "Crowns are the official token of the Seascape Network. They are designed to reward all key stakeholders within the network. The Seascape Network is an incentivized ecosystem consisting of gamers, developers, and influencers with the purpose of bringing DeFi gaming to a broader userbase.",
>     "socials": [
>         {
>             "name": "Twitter",
>             "url": "https://twitter.com/seascapenetwork",
>             "handle": "SeascapeNetwork"
>         },
>         {
>             "name": "Reddit",
>             "url": "https://www.reddit.com/r/SeascapeNetwork",
>             "handle": "SeascapeNetwork"
>         },
>         {
>             "name": "Telegram",
>             "url": "https://t.me/seascapenetwork",
>             "handle": "SeascapeNetwork"
>         },
>         {
>             "name": "Discord",
>             "url": "https://discord.com/invite/qG2Vynh",
>             "handle": "SeascapeNetwork"
>         }
>     ],
>     "explorer": "https://etherscan.io/token/0xac0104cca91d167873b8601d2e71eb3d4d8c33e0",
>     "id": "0xaC0104Cca91D167873B8601d2e71EB3D4D8c33e0"
> }
> ```

copied and pushed. thanks

**Comment by catenocrypt** [comment]
Info file is OK, cheks OK.  Token circulation is on track, still below our limit.

**Pull request merged**
