### PR TITLE
Upload PazTether(GoChain Token)

### PR DESCRIPTION
**Pull request by vastselling**

### CODE REVIEW

**Comment by kolya182** [comment]
Just drop logo here and address

**Comment by vastselling** [comment]
okay thanks let me do that now

**Comment by vastselling** [comment]
logo

Gochain Address: 0x721Cc970CB5A22915f7663a6833E605deDDb7B92

**Comment by kolya182** [comment]
We already have your image, not sure why you adding

**Comment by vastselling** [comment]
The image does not display on trustwallet

**Comment by pazcoinfoundation** [comment]
trust wallet with PAZT

The logo image does not display on trustwallet

**Pull request closed without merging**
