### PR TITLE
Add COPE (SPL)

### PR DESCRIPTION
**Pull request by dackyduck**
Adding info for SPL token 'COPE'.

PR created by <a href="https://assets.trustwallet.com">TW Assets Management</a>

### CODE REVIEW

**Comment by Cryptocool1** [comment]
decimals should be 6, fixed

**Comment by dackyduck** [comment]
@cryptocool1 I am sorry, I was just in hurry and impatient as my tokens are stuck. Ut says my request has been solved but I am still not able to see new cope on trustwallet

**Comment by Cryptocool1** [comment]
You need pay first, then I will merge

**Comment by dackyduck** [comment]
But this is already minted token, and it is big token. I sent my coins just because this coin was already there. They just swapped into new. Please check solana explorer or their official website faq.

**Comment by dackyduck** [comment]
I am not a developer of this token, I am just normal user of trustwallet who was using trust wallet for storing my coins.

**Comment by dackyduck** [comment]
@Cryptocool1

**Comment by dackyduck** [comment]
Can you please do it @cryptocool1. I was helped by legend of this coin himself. I have made the payment. Please update it?

**Comment by dackyduck** [comment]
Please change the description too. Please use the old description they have. Please rename old cope address as xCOPE and new as COPE. So people don't get confused.

**Comment by Cryptocool1** [comment]
> Please change the description too. Please use the old description they have. Please rename old cope address as xCOPE and new as COPE. So people don't get confused.

hello,
 is everything ok, or I should change or add smth?

**Comment by dackyduck** [comment]
It looks good now thanks @cryptocool1

**Comment by Cryptocool1** [comment]
> It looks good now thanks @Cryptocool1

ready to merge?

**Comment by dackyduck** [comment]
Yes please

**Pull request merged**
