### PR TITLE
Add W3C info and logo

### PR DESCRIPTION
**Pull request by 1453742116**
The merger has failed before. This is my new account resubmitted. I hope the merger can succeed.

### CODE REVIEW

**Comment by 1453742116** [comment]
> Hi! In order to compensate for the efforts of processing PRs, we kindly ask for a contribution. 💀 As **there is no refund**, before **paying the fee**, make sure **new tokens fulfill the minimum circulation and other [acceptance criteria](https://developer.trustwallet.com/assets/new-asset)**. See also the [PR Fee FAQ](https://developer.trustwallet.com/assets/faq).
> 
> Please pay **700 TWT** with the memo **22340** to the address `bnb1tqq9llyr3dyjd559dha6z5r5etk3qfwk07m098`. Alternatively, 5 BNB is also accepted (same memo & address).
> 
> **QR** code: [Trust](https://api.qrserver.com/v1/create-qr-code/?size=200x200&data=https%3A%2F%2Flink.trustwallet.com%2Fsend%3Fcoin%3D714%26address%3Dbnb1tqq9llyr3dyjd559dha6z5r5etk3qfwk07m098%26amount%3D700%26memo%3D22340) | [other wallet](https://api.qrserver.com/v1/create-qr-code/?size=200x200&data=bnb1tqq9llyr3dyjd559dha6z5r5etk3qfwk07m098%3Famount%3D700%26memo%3D22340)
> 
> _Notes_:
> 
> * [Trust Wallet Tokens (TWT)](https://community.trustwallet.com/t/trust-wallet-token-twt/4187) can be obtained through our [Referral Program](https://community.trustwallet.com/t/invite-a-friend-earn-trust-wallet-token-twt/4125) or [from DEXs/exchanges](https://community.trustwallet.com/t/where-to-get-trust-wallet-tokens/76641).
> * New tokens without significant usage are rejected, see criteria mentioned above.
> * One PR should be for a single project; PR's with more than 10 logos will be rejected.
> * Payment evaluation happens automatically, but with a few minutes delay.  When payment is detected, an Accept Review is automatically placed on the PR, which is a condition for merge.
> * Evaluating the PR is done manually, and it is merged only if all conditions are satisfied.
> * TWT-BEP2 is supported (Binance Chain), TWT-BEP20 version on Smart Chain is not.
> 
> There will be a fee to process this request. None of it goes to the developers. Before paying the fee, make sure new tokens fulfill the minimum circulation and other acceptance criteria. If you are paying TWT for the submission, this will be burned automatically. There will be no refunds.

I paid 700twt # 22319#610D7A65B921DE212D659B6FF79E1BE930E4F06D627752BF625CEC65BF162F38, but the merger failed. This is my new account and resubmitted.

**Comment by 1453742116** [comment]
> ### PR Summary
> Files OK: 4 Tokens in PR: (2)
> 
> * **ERC20** 0x965b85D4674F64422c4898C8F8083187f02B32C0
> * **BEP20** 0x2fa6ee42BacF983F050210A1ca42f88686327FC9
> 
> **Token ERC20 - 0x965b85D4674F64422c4898C8F8083187f02B32C0**: Symbol: **SFIL** decimals: 8 Links: [Logo](https://raw.githubusercontent.com/1453742116/assets/master/blockchains/ethereum/assets/0x965b85D4674F64422c4898C8F8083187f02B32C0/logo.png) [Info](https://raw.githubusercontent.com/1453742116/assets/master/blockchains/ethereum/assets/0x965b85D4674F64422c4898C8F8083187f02B32C0/info.json) [Website](https://sfil.io) [Explorer](https://etherscan.io/token/0x965b85D4674F64422c4898C8F8083187f02B32C0) Token check error: ❌ explorer field incorrect: should be standard https://bscscan.com/token/0x965b85D4674F64422c4898C8F8083187f02B32C0, not https://etherscan.io/token/0x965b85D4674F64422c4898C8F8083187f02B32C0 ❌ at least 1 tag is required ❌ number of holders not checked: please, check it manually
> 
> 
> 
> **Token BEP20 - 0x2fa6ee42BacF983F050210A1ca42f88686327FC9**: Symbol: **W3C** decimals: 18 Links: [Logo](https://raw.githubusercontent.com/1453742116/assets/master/blockchains/smartchain/assets/0x2fa6ee42BacF983F050210A1ca42f88686327FC9/logo.png) [Info](https://raw.githubusercontent.com/1453742116/assets/master/blockchains/smartchain/assets/0x2fa6ee42BacF983F050210A1ca42f88686327FC9/info.json) [Website](https://w3dao.finance) [Explorer](https://bscscan.com/token/0x2fa6ee42BacF983F050210A1ca42f88686327FC9) Tags: nft Token check error: ❌ number of holders not checked: please, check it manually
> 
> 

I only submit W3C information.

**Comment by 1453742116** [comment]
> W3C is a brand new token.

**Comment by 1453742116** [comment]
Is the reason why the merger failed because the number of holders and the number of transactions do not meet the conditions? Or other reasons?

**Comment by Cryptocool1** [comment]
Please come back to us once all criteria are met. Make sure to mention this PR so the fee can be reused.

**Comment by 1453742116** [comment]
> Please come back to us once all criteria are met. Make sure to mention this PR so the fee can be reused.

Ok,thank you!

**Comment by 1453742116** [comment]
> > Please come back to us once all criteria are met. Make sure to mention this PR so the fee can be reused.
> 
> Ok,thank you!

The holding quantity and trading volume have met the conditions, please check，thank you!

**Comment by Cryptocool1** [comment]
Hello, how did you get more than 10k holders in 1 week?

**Comment by 1453742116** [comment]
The holding quantity and trading volume have met the conditions.Do I need to resubmit now or what?

**Comment by Cryptocool1** [comment]
> The holding quantity and trading volume have met the conditions.Do I need to resubmit now or what?

Can you answer my question?

**Comment by Cryptocool1** [comment]
Thanks for your interest. Your first transaction was 8 days ago. We are not accept airdropped tokens. You can see it in our requirements. You can try to summit your token later.

**Comment by 1453742116** [comment]
> Thanks for your interest. Your first transaction was 8 days ago. We are not accept airdropped tokens. You can see it in our requirements. You can try to submit your token later.

What kind of coins do you accept

**Comment by 1453742116** [comment]
> Thanks for your interest. Your first transaction was 8 days ago. We are not accept airdropped tokens. You can see it in our requirements. You can try to submit your token later.

What kind of tokens do you accept？

**Pull request closed without merging**
