### PR TITLE
Add MiniSports Token And Logo (BEP20)

### PR DESCRIPTION
**Pull request by onlinewallet2000**
MiniSports is a sports based community token developed mainly to create a safehaven for sports lovers. Our main goal is to provide people a safe and trustworthy place where they can use their crypto for rewards, betting, staking & sports ticketing.

### CODE REVIEW

**Comment by onlinewallet2000** [comment]
Hello should i pay first or wait for confirmation

**Comment by Cryptocool1** [comment]
hello,
• What is the purpose of this token? How will it benefit Trust Wallet users?
 • How is the token being distributed? Are you conducting an airdrop?
 • Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?
 • Is the token listed on a centralized/decentralized exchange?
 • Is a Smart Contract audit completed? Where can we find this information?

**Comment by onlinewallet2000** [comment]
> hello,
> • What is the purpose of this token? How will it benefit Trust Wallet users?
> • How is the token being distributed? Are you conducting an airdrop?
> • Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?
> • Is the token listed on a centralized/decentralized exchange?
> • Is a Smart Contract audit completed? Where can we find this information?

• How is the token being distributed?   pancake Swap.

Are you conducting an airdrop? No airdrop 

• Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale? Presale 

• Is the token listed on a centralized/decentralized exchange? Only pancake swap 

• Is a Smart Contract audit completed?Yes 

Where can we find this information? On website

**Comment by onlinewallet2000** [comment]
i wanted to ask when 

> hello,
> • What is the purpose of this token? How will it benefit Trust Wallet users?
> • How is the token being distributed? Are you conducting an airdrop?
> • Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?
> • Is the token listed on a centralized/decentralized exchange?
> • Is a Smart Contract audit completed? Where can we find this information?

I wanted to ask when logo is going to appear in trust wallet or i need to pay 5bnbs

**Comment by Cryptocool1** [comment]
What is the purpose of this token? How will it benefit Trust Wallet users?

**Comment by onlinewallet2000** [comment]
> What is the purpose of this token? How will it benefit Trust Wallet users?

MiniSports is a Bridge Between the CryptoVerse and Sports. Connecting sports and the crypto community through a series of competitions, betting and prizes that highlight the leading ideas and individuals shaping the future of sports on the blockchain. MiniSports is a sports based community token developed mainly to create a safehaven for sports lovers. Their main goal is to provide people a safe and trustworthy place where they can use their crypto for rewards, betting, staking & sports ticketing. As a sports community developed token, they focus on the needs of their Sports lover community members.

**Comment by onlinewallet2000** [comment]
> What is the purpose of this token? How will it benefit Trust Wallet users?
photo_2021-09-16_22-40-34

**Comment by onlinewallet2000** [comment]
for more info, you can check the website https://minisportstoken.com/

**Comment by onlinewallet2000** [comment]
can you tell me when logo is going to appear because community are waiting for this

**Comment by onlinewallet2000** [comment]
• What is the purpose of this token? How will it benefit Trust Wallet users?
MiniSports is a Bridge Between the CryptoVerse and Sports. Connecting
sports and the crypto community through a series of competitions, betting
and prizes that highlight the leading ideas and individuals shaping the
future of sports on the blockchain. MiniSports is a sports based community
token developed mainly to create a safehaven for sports lovers. Their main
goal is to provide people a safe and trustworthy place where they can use
their crypto for rewards, betting, staking & sports ticketing. As a sports
community developed token, they focus on the needs of their Sports lover
community members.

• How is the token being distributed?
Pancake Swap.

Are you conducting an airdrop?
No airdrop

• Did you sold the tokens at an Initial Coin Offering (ICO) or a token
presale?
Presale

• Is the token listed on a centralized/decentralized exchange?
Only pancake swap

• Is a Smart Contract audit completed?
Yes

Where can we find this information?
On website

**Comment by onlinewallet2000** [comment]
> Hi! In order to compensate for the efforts of processing PRs, we kindly ask for a contribution.
> 💀 As **there is no refund**, before **paying the fee**, make sure **new tokens fulfill the minimum circulation and other [acceptance criteria](https://community.trustwallet.com/t/how-to-submit-a-token-logo/3863)**.
> See also the [PR Fee FAQ](https://developer.trustwallet.com/add_new_asset/pr-fee).
> 
> Please pay  **1000 TWT**  with the memo **3668**  to the address `bnb1tqq9llyr3dyjd559dha6z5r5etk3qfwk07m098`.
> Alternatively, 5 BNB is also accepted (same memo & address).
> 
> **QR** code: [Trust](https://api.qrserver.com/v1/create-qr-code/?size=200x200&data=https%3A%2F%2Flink.trustwallet.com%2Fsend%3Fasset%3Dc714_tTWT-8C2%26address%3Dbnb1tqq9llyr3dyjd559dha6z5r5etk3qfwk07m098%26amount%3D1000%26memo%3D3668) | [other wallet](https://api.qrserver.com/v1/create-qr-code/?size=200x200&data=bnb1tqq9llyr3dyjd559dha6z5r5etk3qfwk07m098%3Famount%3D1000%26memo%3D3668)
> 
> *Notes*:
> * [Trust Wallet Tokens (TWT)](https://community.trustwallet.com/t/trust-wallet-token-twt/4187) can be obtained through our [Referral Program](https://community.trustwallet.com/t/invite-a-friend-earn-trust-wallet-token-twt/4125) or [from DEXs/exchanges](https://community.trustwallet.com/t/where-to-get-trust-wallet-tokens/76641).
> * New tokens without significant usage are rejected, see criteria mentioned above.
> * One PR should be for a single project; PR's with more than 10 logos will be rejected.
> * Payment evaluation happens automatically, but with a few minutes delay.  When payment is detected, an Accept Review is automatically placed on the PR, which is a condition for merge.
> * Evaluating the PR is done manually, and it is merged only if all conditions are satisfied.
> * TWT-BEP2 is supported (Binance Chain), TWT-BEP20 version on Smart Chain is not.
> 

Pay

**Comment by onlinewallet2000** [comment]
is it all right? I'm waiting for logo to be added in trust wallet

**Pull request merged**
