### PR TITLE
Add Wrapped JAXNET (BEP20)

### PR DESCRIPTION
**Pull request by dark-sizter**
Adding info for BEP20 token 'Wrapped JAXNET'.

PR created by <a href="https://assets.trustwallet.com">TW Assets Management</a>

### CODE REVIEW

**Comment by dark-sizter** [comment]
fee paid in#17188

**Comment by cryptomanz** [comment]
Hello,
Where did you pay?

**Comment by dark-sizter** [comment]
fee paid in #17186

**Comment by dark-sizter** [comment]
heres my audit https://www.certik.com/projects/jax-network

**Pull request closed without merging**
