### PR TITLE
adding DINO

### PR DESCRIPTION
**Pull request by ghost**

### CODE REVIEW

**Comment by DINOlabs** [comment]
( https://dinoyield.finance )

**Comment by catenocrypt** [comment]
As per our policy, brand new tokens are not included, there is a minimum requirement of 2500 holder addresses and 5000 transactions, in order to filter out scam tokens.
See the criteria at (mentioned in the first message by the bot): https://community.trustwallet.com/t/how-to-submit-a-token-logo/3863).
This token has low usage yet (121 holders). Closing PR for now. Please come back to us when all criteria are met.  Multi-chain and staking tokens may get special treatment, let us know if this is the case. 

https://bscscan.com/token/0x9B7f59A5b5A2D0A7e9DAEB5b5A19DA112D533dC7

**Comment by DINOlabs** [comment]
Hello,

Yes this is the case, we are a yield farming token and we saw that other coins with less than 2500 holders were accepted so we submitted our token.

In the bsc ecosystem, lots of new projects are scammy, and we try to bring something totally fair for people by taking market share from those projects and make people aware of it. You can check our website dinoyield.finance or our community in telegram, everybody is surprised by the work we do and how we act.

The project was created only 10 days ago, and we do it with organic growth, we refuse all bot marketing proposals and stuff like that everyday. It can help us a lot to be in the pancakeswap list to gain credibility. however if it's not possible we come back to you when the criteria are met.

Thank you

Sent with [ProtonMail](https://protonmail.com) Secure Email.

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐

**Comment by catenocrypt** [comment]
We need to see a somewhat high value with an increasing trend towards the limit.  Todays value is 106, even less than last time.

**Pull request closed without merging**
