### PR TITLE
Revert "Please add ZDEX logo "

### PR DESCRIPTION
**Pull request by Shyamthakur33**
Reverts trustwallet/assets#3249
don't know sir, how DMST file include in it by mistake, and DMST token logo I already have updated through you before a week ago, Please check this link https://ibb.co/wSrT9jc of PR 3249 this time I uploaded ZDEX logo file for this smart contract 0x73DBbf72d427076BDd73CF905fDFc442c9C67D4a and I already have paid for PR 3249. Please update this below logo for smart contract 0x73DBbf72d427076BDd73CF905fDFc442c9C67D4a what i requested in PR 3249

0x73DBbf72d427076BDd73CF905fDFc442c9C67D4a

### CODE REVIEW

**Comment by catenocrypt** [comment]
This PR contains 0 files -- it is empty!
Add the correct logo at the correct location, and I can waive the fee.

**Comment by Shyamthakur33** [comment]
ok, PLEASE waive the fee sir and how i upload new file sir

**Comment by Shyamthakur33** [comment]
can i please upload by comment

**Comment by catenocrypt** [comment]
> how i upload new file sir

Dear @Shyamthakur33 , I would expected that for a crypto project owner/team adding a file to a GitHub repository is an easy task.  I am doing it on your behalf now.

**Comment by Shyamthakur33** [comment]
really appreciate sir

**Comment by Shyamthakur33** [comment]
Really appreciate your continued support sir 🙏

**Pull request merged**
