### PR TITLE
Add SpacePath (BEP20)

### PR DESCRIPTION
**Pull request by thadhutch**
Adding info for BEP20 token 'SpacePath'.

PR created by <a href="https://assets.trustwallet.com">TW Assets Management</a>

### CODE REVIEW

**Comment by cryptomanz** [comment]
Hello,
- Submission looks good. awaiting fee payment.

**Comment by thadhutch** [comment]
Hi, having an issue sending the memo. Is there any way around that? Could I send over the TWT and send you the transaction ID?

**Comment by thadhutch** [comment]
We already bought the 1000 TWT just haven't sent it over yet.

**Comment by bicrick** [comment]
Payment Sent! E26F7523FBDA3F59304B3527F70646467DAD831FE3308E2AAD840B1AC03D24BB is the transaction ID

**Pull request merged**
