### PR TITLE
Add Baby Grok (BEP20)

### PR DESCRIPTION
**Pull request by babygrok**
Adding info for BEP20 token 'Baby Grok'.

PR created by <a href="https://assets.trustwallet.com">TW Assets Management</a>

### CODE REVIEW

**Comment by babygrok** [comment]
hello trust wallet team i dont know if me apply all correct can confirm if anything else needed ?

**Comment by babygrok** [comment]
@Cryptocool1 @cryptomanz1 @natedaiger @hexorx can anyone help me if me apply the form correct ?

**Comment by cryptomanz1** [comment]
• What is the purpose of this token? How will it benefit Trust Wallet users?
 • How is the token being distributed? Are you conducting an airdrop?
 • Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?
 • Is the token listed on a centralized/decentralized exchange?
 • Is a Smart Contract audit completed? Where can we find this information?

**Comment by babygrok** [comment]
• What is the purpose of this token? How will it benefit Trust Wallet users? 
we are meme token we try bring defi for investors with staking plans upcoming
• How is the token being distributed? Are you conducting an airdrop? we dont have any airdrop we was presale with hc 150 and

• Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale? presale at pinksale 
• Is the token listed on a centralized/decentralized exchange? for now only pancakeswap and upcoming bitmart they already announced 
• Is a Smart Contract audit completed? Where can we find this information? yes already audited you can check her 

https://app.analytixaudit.com/baby-grok

**Comment by babygrok** [comment]
@cryptomanz1 
• What is the purpose of this token? How will it benefit Trust Wallet users?
we are meme token we try bring defi for investors with staking plans upcoming
• How is the token being distributed? Are you conducting an airdrop? we dont have any airdrop we was presale with hc 150 and

• Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale? presale at pinksale
• Is the token listed on a centralized/decentralized exchange? for now only pancakeswap and upcoming bitmart they already announced
• Is a Smart Contract audit completed? Where can we find this information? yes already audited you can check her

https://app.analytixaudit.com/baby-grok

**Pull request merged**
