### PR TITLE
add logo 

### PR DESCRIPTION
**Pull request by marcotravel**
Hi there according to #13798  PR we should provide our smart contract audit and now we have prepared it and also please make our paid fee reused 
thank you 
[Marco Token (MRC).pdf](https://github.com/trustwallet/assets/files/7271463/Marco.Token.MRC.pdf)

### CODE REVIEW

**Comment by cryptomanz** [comment]
Hello,
Please follow the rules for adding tokens, your logo should be a full screen 256x256.
Exemple:
https://community.trustwallet.com/t/how-to-submit-a-token-logo/386
Screenshot 2021-10-01 at 01 52 16
3

**Comment by marcotravel** [comment]
logo
here is our new logo is it ok?

**Comment by cryptomanz** [comment]
Your logo should be a full screen 256x256.
Exemple:
Screenshot 2021-10-01 at 01 52 16

**Comment by marcotravel** [comment]
could you please help me with the fullscreen logo ??

**Comment by marcotravel** [comment]
it is problem in showing logo size in trust and does not appear correctly could you please fix this? it seems has extra width
WhatsApp Image 2021-10-03 at 12 22 51 PM
?

**Comment by aminbh72** [comment]
> it is problem in showing logo size in trust and does not appear correctly could you please fix this? it seems has extra width WhatsApp Image 2021-10-03 at 12 22 51 PM ?

and MRC info not added !

**Comment by marcotravel** [comment]
@cryptomanz we have added a new logo file I hope there is no probl
logo
em

**Comment by Cryptocool1** [comment]
Hello, please open new PR with full size logo

**Comment by marcotravel** [comment]
i mentioned you in #14120

**Pull request merged**
