### PR TITLE
Add files via upload

### PR DESCRIPTION
**Pull request by ghost**
Adding logo for RiskHorizon token to trust wallet! RiskHorizon is a token for Horizon, a platform aiming to simplify DeFi for everyone!

### CODE REVIEW

**Comment by asharpie** [comment]
website: defihorizon.app
twitter: twitter.com/risk_horizon
telegram: t.me/riskhorizon

**Comment by catenocrypt** [comment]
Correction needed: Please add an `info.json` file next to the `logo.png`, with info about the project, of the form:

```json
{
    "name": "Trust Wallet Token",
    "type": "ERC20",
    "symbol": "TWT",
    "decimals": 8,
    "description": "Utility token to increase adoption of cryptocurrency.",
    "website": "https://trustwallet.com",
    "explorer": "https://explorer.binance.org/asset/TWT-8C2",
    "status": "active",
    "id": "TWT-8C2"
}
```

**Comment by asharpie** [comment]
Having some trouble, this wont submit even though the id is what its asking for it to be.

**Comment by vikmeup** [comment]
As per our updated policy, brand new tokens are not included, there is a minimum requirement 

- at least 2500 token holders
- at least 500 transactions

See our [How to Get Submit Token Logo ](https://community.trustwallet.com/t/how-to-submit-a-token-logo/3863#how-to-get-approved) guidelines.

Feel free to re-open pull request once you meet those requirements.

**Pull request closed without merging**
