### PR TITLE
add logo and info

### PR DESCRIPTION
**Pull request by BURNTOKEN5000**
please review it , i has been make payment 2 bnb before :)

this is my tx before

https://explorer.binance.org/tx/7944400F27F1DE8810D71668D81D09369C49340986A252EBAAD1EC55DEB67DCC

### CODE REVIEW

**Review by mohdfady — APPROVED** [review]

**Comment by BURNTOKEN5000** [comment]
that's all finish?

**Comment by Iamdeadlyz** [comment]
Please remove `blockchains/binance/assets/0xef5ceb00ae3eb617773016b4ca886b61fa4e027e/logo.png`

**Comment by BURNTOKEN5000** [comment]
How about remove repository the old one? Bcoz i can’t deleted img

**Comment by BURNTOKEN5000** [comment]
Everything is right?

**Comment by Iamdeadlyz** [comment]
> Everything is right?

Few corrections:
- Rename the folder to `0xef5CeB00AE3eb617773016B4ca886b61FA4e027E-x`, commit, and push
- Rename it again to `0xef5CeB00AE3eb617773016B4ca886b61FA4e027E`, commit, then push

**Comment by BURNTOKEN5000** [comment]
Can you help me with it? I’m not understand

**Comment by BURNTOKEN5000** [comment]
Thanks u so much 🙏

**Pull request merged**
