### PR TITLE
Add ZionTopia (BEP20)

### PR DESCRIPTION
**Pull request by ZionTopia**
Adding info for BEP20 token 'ZionTopia'.

PR created by <a href="https://assets.trustwallet.com">TW Assets Management</a>

### CODE REVIEW

**Comment by Cryptocool1** [comment]
• What is the purpose of this token? How will it benefit Trust Wallet users?
 • How is the token being distributed? Are you conducting an airdrop?
 • Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?
 • Is the token listed on a centralized/decentralized exchange?
 • Is a Smart Contract audit completed? Where can we find this information?

**Comment by ZionTopia** [comment]
21 Tem 2022 Per, saat 19:57 tarihinde CryptoA ***@***.***>
şunu yazdı:

**Comment by Cryptocool1** [comment]
Hello, we require smart contract audit from reputable companies. 
please see the requirements here https://developer.trustwallet.com/assets/requirements

**Comment by ZionTopia** [comment]
22 Tem 2022 Cum, saat 01:47 tarihinde CryptoA ***@***.***>
şunu yazdı:

**Comment by Cryptocool1** [comment]
Feel free to create new PR once all criteria are met.

**Comment by ZionTopia** [comment]
CryptoA ***@***.***>, 24 Tem 2022 Paz, 00:55 tarihinde şunu
yazdı:

**Comment by ZionTopia** [comment]
Hello,

reputable companies ?

Best Regards

CryptoA ***@***.***>, 22 Tem 2022 Cum, 01:47 tarihinde şunu
yazdı:

**Pull request closed without merging**
