### PR TITLE
add Alkemi Network ALK

### PR DESCRIPTION
**Pull request by brandoncurtis**
- https://etherscan.io/token/0x6C16119B20fa52600230F074b349dA3cb861a7e3
- https://www.coingecko.com/en/coins/alkemi-network-dao-token
- https://coinmarketcap.com/currencies/alkemi-network-dao-token/

### CODE REVIEW

**Comment by Cryptocool1** [comment]
hello,
• Is a Smart Contract audit completed? Where can we find this information?

**Comment by brandoncurtis** [comment]
Yes, here's the audit: https://github.com/AlkemiNetwork/alkemi-earn-security-audit

**Comment by Cryptocool1** [comment]
could you add the links?

**Comment by brandoncurtis** [comment]
Links added, I believe this is ready to go!

**Pull request merged**
