### PR TITLE
Update Safegem (GEMS) Info and Logo

### PR DESCRIPTION
**Pull request by SafegemOfficial**
[Update Safegem (GEMS) Info and Logo](https://github.com/trustwallet/assets/commit/3d8a6c5d03b0686eb09767a88fc0483d22e4314a)

### CODE REVIEW

**Comment by Cryptocool1** [comment]
Hello, I have sent you the requirements for PR 2 times, could you please follow them ?

**Comment by Cryptocool1** [comment]
Please create new PR, follow doc https://developer.trustwallet.com/assets/requirements
You may want to try our Assets app in beta; go to https://assets.trustwallet.com, log on with Github, enter contract ID, logo and some additional info, and it will create a PR for you.
See https://developer.trustwallet.com/assets/repository_details

**Comment by Cryptocool1** [comment]
You can try our asset app and it will create the PR for you.

**Comment by SafegemOfficial** [comment]
> Hello, I have sent you the requirements for PR 2 times, could you please follow them ?

Apologies, we tried the asset app to create the PR and it could not verify holders. There was no field to manually enter. Please advise.

**Comment by Cryptocool1** [comment]
Don’t worry, it is not the problem, we will check your holders manually. They are ok👍🏼

**Comment by SafegemOfficial** [comment]
Still receiving a "Check Result: ERROR" on https://assets.trustwallet.com/and cannot create a pull request. Please advise. Will completing the logo update also require 700 TWT?

**Pull request closed without merging**
