### PR TITLE
Add SuperMinesweeper (BEP20)

### PR DESCRIPTION
**Pull request by 5kkk**
Adding info for BEP20 token 'SuperMinesweeper'.

PR created by <a href="https://assets.trustwallet.com">TW Assets Management</a>

### CODE REVIEW

**Comment by cryptomanz** [comment]
As per our policy, brand new tokens are not included, there is a minimum requirement of 25,000 holder addresses and 50,000 transactions, in order to filter out scam tokens.
See the criteria at : https://developer.trustwallet.com/assets/requirements .

**Comment by 5kkk** [comment]
The standard of circulation of new tokens is too high, which can be difficult for new communities. We have 6837 addresses, 11553 transactions, we can contribute 2000 TWT, proof is not fraudulent token, please pass demand

**Comment by 5kkk** [comment]
> 根据我们的政策，不包括全新的代币，最低要求是 25,000 个持有人地址和 50,000 笔交易，以过滤欺诈代币。 请参阅以下标准：[https](https://developer.trustwallet.com/assets/requirements) : [//developer.trustwallet.com/assets/requirements](https://developer.trustwallet.com/assets/requirements)。

The standard of circulation of new tokens is too high, which can be difficult for new communities. We have 6837 addresses, 11553 transactions, we can contribute 2000 TWT, proof is not fraudulent token, please pass demand

**Comment by 5kkk** [comment]
The standard of circulation of new tokens is too high, which can be
difficult for new communities. We have 6837 addresses, 11553 transactions,
we can contribute 2000 TWT, proof is not fraudulent token, please pass
demand

Nazar ***@***.***> 于2021年11月21日周日 上午9:13写道：

**Pull request closed without merging**
