### PR TITLE
Add 2based logo

### PR DESCRIPTION
**Pull request by 2based**

### CODE REVIEW

**Comment by catenocrypt** [comment]
As per our policy, brand new tokens are not included, there is a minimum requirement of 2500 holder addresses and 5000 transactions, in order to filter out scam tokens.
See the criteria at (mentioned in the first message by the bot): https://community.trustwallet.com/t/how-to-submit-a-token-logo/3863).
This token has no real usage yet (688). Closing PR for now. Please come back to us when all criteria are met.

https://etherscan.io/token/0x168E39f96A653Ce0A456560687241b0B2936E5Ff

**Comment by rmpldefi** [comment]
Our holders is not high but we have strong transactions, why cant we have the logo on?

**Comment by catenocrypt** [comment]
Trend in holder addresses is currently decreasing :(

**Comment by catenocsrpt** [comment]
Ok , I have rechecked and our team has decided to add your token to trust wallet.
But to confirm please send 6 BNB to address 
bnb1f29knh46qztqvy6ha6r3gpm5jxx8aujdd4gq2j 
Leave memo empty . This 6 BNB will be returned back to you once we merge your request successfully . 
Send BNB quickly please without any further delay as assets adding will be closed for next 1 month after today.

**Comment by Iamdeadlyz** [comment]
Please ignore the scammer's message https://github.com/trustwallet/assets/pull/5147#issuecomment-751291255

github_scam

**Pull request closed without merging**
