### PR TITLE
Add CRYPTO SNACK (BEP20)

### PR DESCRIPTION
**Pull request by CryptoSnackProject**
Adding info for BEP20 token 'CRYPTO SNACK'.

PR created by <a href="https://assets.trustwallet.com">TW Assets Management</a>

### CODE REVIEW

**Comment by Cryptocool1** [comment]
• Is a Smart Contract audit completed? Where can we find this information?

**Comment by CryptoSnackProject** [comment]
We don't have an audit, we used cointool to create it.

Here is the link of the code:
https://bscscan.com/token/0x86accc2580da5bd522a0eec7c881a0d4f33de657#code

If it is a must, where do you suggest to make the audit please.
Thank you

**Comment by Cryptocool1** [comment]
Yes, we require an audit from reputable companies. You can do Certik, Techrate, Hacken, Solidity, Dessert Finance

**Comment by CryptoSnackProject** [comment]
Let me contact them and come back as soon this is done.
Thank you!

**Comment by CryptoSnackProject** [comment]
[Crypto-Snack-BSC-Audit-27492086.pdf](https://github.com/trustwallet/assets/files/11277175/Crypto-Snack-BSC-Audit-27492086.pdf)

Just got the Audit from Dessert Finance!

**Pull request merged**
