### PR TITLE
Add Stakin Validator

### PR DESCRIPTION
**Pull request by tiagocmachado**
Using the same image is the one provided for Solana

### CODE REVIEW

**Review by cryptomanz1 — APPROVED** [review]

**Comment by trastvolt** [comment]
tiagocmachado:master

**Review by ArtemGoryunov — COMMENTED** [review]
@tiagocmachado Merger master to your branch, please

**Comment by tiagocmachado** [comment]
> @tiagocmachado Merger master to your branch, please

Done

**Comment by tiagocmachado** [comment]
@ArtemGoryunov @cryptomanz1 can you please reopen the PR so we can proceed with the fee?

**Pull request merged**
