### PR TITLE
Add Whackd (WHACKD) (ERC20)

### PR DESCRIPTION
**Pull request by ghost**
Adding info for ERC20 token 'Whackd (WHACKD)'.

PR created by <a href="https://assets.trustwallet.com">TW Assets Management</a>

### CODE REVIEW

**Comment by whackdinfo** [comment]
I think I did everything right, but please advise if there's anything I need to change!  Thank you :)

**Comment by cryptomanz** [comment]
Hello,
- Awaiting for smart contract audit.

**Comment by whackdinfo** [comment]
> Hello,
> 
> * Awaiting for smart contract audit.

Thanks so much.  Do we need to do a Token Sniffer audit, or is it something trust wallet does internally?

**Comment by whackdinfo** [comment]
Bump for guidance on audit requirement.  I'm looking around trying to understand if there's something we need to be doing or if the audit happens on the TrustWallet side, and we are just supposed to be waiting...

**Comment by cryptomanz** [comment]
> Bump for guidance on audit requirement. I'm looking around trying to understand if there's something we need to be doing or if the audit happens on the TrustWallet side, and we are just supposed to be waiting...

as I mentioned, we are waiting smart contract audit from you

**Comment by Cryptocool1** [comment]
Hello,
please create new PR when smart contract audit will be ready.
make sure to mention this PR, so that we can see that fee has been paid already here.

**Pull request closed without merging**
