### PR TITLE
Add TRAVEL logo and info

### PR DESCRIPTION
**Pull request by TokenTravelCare**
Hello TrustWallet team,
Please add TravelCare logo in Trust Wallet.
Thank you.

### CODE REVIEW

**Review by TokenTravelCare — COMMENTED** [review]
Links and tags added

**Review by TokenTravelCare — COMMENTED** [review]
Links and tags added

**Review by TokenTravelCare — COMMENTED** [review]
Links and Tags added. Thanks

**Review by TokenTravelCare — COMMENTED** [review]
Links and tags added.

**Review by TokenTravelCare — COMMENTED** [review]
Links and tags added correctly. thanks.

**Review by TokenTravelCare — COMMENTED** [review]
Links and tags added correctly. thanks.

**Comment by TokenTravelCare** [comment]
Links and tags added correctly. thanks.

**Comment by Cryptocool1** [comment]
• What is the purpose of this token? How will it benefit Trust Wallet users?
• How is the token being distributed? Are you conducting an airdrop?
• Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?
• Is the token listed on a centralized/decentralized exchange?
• Is a Smart Contract audit completed? Where can we find this information?

**Comment by TokenTravelCare** [comment]
Hello! 
Please find below all answers of your questions:

**What is the purpose of this token?** 

Travel Care’s online travel booking platform accepts cryptocurrency and rewards travelers with crypto tokens, making it the most worthwhile travel booking site for crypto enthusiasts.
As a tradeable utility token, the Travel Care $TRAVEL token increases the benefits that travelers get from traditional travel points by awarding them in cryptocurrency. Travel Care’s mission is to have a state-of-the-art technology platform to offer the best product at the best price thanks to blockchain technology and cryptocurrencies.

**How will it benefit Trust Wallet users?**

Trustwallet is the favorite wallet of most of the people, we have many holders that use this wallet and for that reason we requested to upload the logo.
Trustwallet users will benefit from better identification of the tokens and better global visibility.

**• How is the token being distributed? Are you conducting an airdrop?**

This token is a migration from the old Travel Care token, we have been live since June last year. Now we have made migration to the new smart contract with supply reduction and adding features that will enhance the traveler's experience.
The token has been purchased directly by the holders and distributed proportionally to the holders of the old token.
NO AIRDROPS

Links of official announcements:

https://twitter.com/TravelCareToken/status/1486672137515642885
https://twitter.com/TravelCareToken/status/1483396767530033152
https://twitter.com/TravelCareToken/status/1498206337976750084
https://twitter.com/TravelCareToken/status/1498614346871619591


**• Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?**

The presale of the old token was in June 2021, here is the link:
https://dxsale.app/app/pages/defipresale?saleID=2188&chain=BSC


**• Is the token listed on a centralized/decentralized exchange?**

Yes on PanckeSwap:
https://pancakeswap.finance/info/token/0x826e5ec70dbc5607ff9218011fbb97f9a8d97953

On Hotbit (pending an update of the information)
https://www.hotbit.io/exchange?symbol=TRAVEL_USDT


**• Is a Smart Contract audit completed? Where can we find this information?**

Yes, the new smart contract is audited by Hacken:
https://hacken.io/wp-content/uploads/2022/02/TravelCare_01032022_SCAudit_Report.pdf


If you need additional information, do not hesitate to ask us.
 
Thank you very much.
 
Best regards.

**Comment by cryptomanz** [comment]
As per our policy, brand new tokens are not included, there is a minimum requirement of 10,000 holder addresses and 15,000 transactions, in order to filter out scam tokens.
See the criteria at : https://developer.trustwallet.com/assets/requirements .

**Comment by TokenTravelCare** [comment]
Dear @cryptomanz 

thank you for your replay.

I think your policy to avoid scams is correct, but let me clarify again that in our case it is not a brand new token, but a migration from an old TRAVEL CARE (already listed in TW) to a TRAVEL CARE with a new smart contract. I have shared above all the details, but I will pass it back to you:

Links of official announcements:

https://twitter.com/TravelCareToken/status/1486672137515642885
https://twitter.com/TravelCareToken/status/1483396767530033152
https://twitter.com/TravelCareToken/status/1498206337976750084
https://twitter.com/TravelCareToken/status/1498614346871619591

CoinMarketCap is also in the process of changing the information, but as you can see we already have the new logo:
https://coinmarketcap.com/currencies/travel-care/

Before making the request I reconfirmed the logo change with @ZachZwei on Telegram and he confirmed that I had to make a new request for the new contract.

I urge you to double check my message above and get our new logo approved.

I look forward to hearing from you.

Thank you very much.

Best regards.

PD. All our teams is doxxed and our contract is audited by Hacken, I hope this information is enough for you to verify that this is not a scam:
https://travelcare.io/about-us/

**Pull request merged**
