### PR TITLE
Please add ZDEX logo 

### PR DESCRIPTION
**Pull request by Shyamthakur33**
Token name - Zeedex
Token symbol - ZDEX
Total supply - 10,000,000
Decimal - 18
Smart contract - 0x73DBbf72d427076BDd73CF905fDFc442c9C67D4a
0x73DBbf72d427076BDd73CF905fDFc442c9C67D4a

### CODE REVIEW

**Comment by Shyamthakur33** [comment]
payment done with memo 3249

**Comment by Shyamthakur33** [comment]
Sir, please recheck, logo still not showing, I have cleared cache also.

**Comment by Shyamthakur33** [comment]
I have reinstall the wallet too, still logo not updated.

**Comment by catenocrypt** [comment]
The file included in this PR points to DMST, and that is visble in TrustWallet.  Check the Files section of the PR.  To me it works as expected.

blockchains/ethereum/assets/0xF29992D7b589A0A6bD2de7Be29a97A6EB73EaF85/logo.png
https://etherscan.io/address/0xF29992D7b589A0A6bD2de7Be29a97A6EB73EaF85

**Comment by Shyamthakur33** [comment]
please check pr in this below link, I requested for this smart contract 0x73DBbf72d427076BDd73CF905fDFc442c9C67D4a
https://ibb.co/wSrT9jc

**Comment by Shyamthakur33** [comment]
dmst logo i already have updated before a week ago.

**Comment by Shyamthakur33** [comment]
You are right sir, dmst token logo i already have updated before, now i requested for this smart contract 0x73DBbf72d427076BDd73CF905fDFc442c9C67D4a as you can see in below link
https://ibb.co/wSrT9jc
0x73DBbf72d427076BDd73CF905fDFc442c9C67D4a

**Comment by catenocrypt** [comment]
I'm really sorry if you have included the wrong file, you need to correct it with a new PR.  The files included matter, not the comments, git is strict, 1's and 0's not chit-chat.

**Comment by Shyamthakur33** [comment]
what about my fee sir, that i paid

**Pull request merged**
