### PR TITLE
Add TOM3 (ERC20)

### PR DESCRIPTION
**Pull request by tom3eth**
Adding info for ERC20 token 'TOM3'.

PR created by <a href="https://assets.trustwallet.com">TW Assets Management</a>

### CODE REVIEW

**Comment by tom3eth** [comment]
Hi Team,

Thank you so much for reaching out. I only have access to ETH Network;
please send an address that can receive token in the ETH mainnet.

Thanks

Tom

**Comment by tom3eth** [comment]
Thank you, Team; here is the transaction details:
https://bscscan.com/tx/0xc4919ca06600935db61d39627f82df33766a4f11c3aeed55a38cfe6302b5ba25

Please update the TOM3 Token info as requested

Thank you so much

Tom

**Review by tom3eth — COMMENTED** [review]
Excellent! Looks good!

**Comment by tom3eth** [comment]
We know: "low token circulation: number of holders is 24, below limit of 10000"
We are working on a new release and should achieve the required number soon.

**Comment by Cryptocool1** [comment]
In order for the pull request to be approved, the submission has to meet several important requirements. For this request, it does not meet the following:

- at least 10000 token holders
- at least 15000 transactions

To know more about the token approval guidelines, please check this article: [How to Submit Token Logo](https://developer.trustwallet.com/listing-new-assets/requirements).

Feel free to re-open pull request once you meet those requirements.

**Pull request closed without merging**
