### PR TITLE
NEWDOGE Full Audit Complete - Please add logo in info to Trust Wallet

### PR DESCRIPTION
**Pull request by NewDogeCoin**
Our full audit has been completed as requested: https://newdoge.com/NEWDOGE_audit.pdf

Fee has been paid on PR # 11547: https://github.com/trustwallet/assets/pull/11547

We would like to have our logo and info added to the Trust Wallet please.

Thank you,
Brock

### CODE REVIEW

**Comment by cryptomanz** [comment]
hello,
 • Is the token listed on a centralized/decentralized exchange?

**Comment by NewDogeCoin** [comment]
Hi,
Yes we are on PancakeSwap: https://exchange.pancakeswap.finance/#/swap?outputCurrency=0x94618ffb2153d4a52ce1e8d00e72de676576bd6a

Kind regards,
Brock

**Comment by cryptomanz** [comment]
Hello,
- awaiting for CMC listing.

**Comment by cryptomanz** [comment]
Hello,
please create new PR when CMC listing will be ready.
make sure to mention this PR, so that we can see that fee has been paid already here.

**Pull request closed without merging**
