### PR TITLE
Safecom Logo

### PR DESCRIPTION
**Pull request by Connecteq**
Safe Community logo

### CODE REVIEW

**Comment by Connecteq** [comment]
I have upload changes that I can't merge, please accept the change before the review as there was error on the first files uploaded.

**Comment by Cryptocool1** [comment]
please delete all incorrect files

**Comment by Connecteq** [comment]
Why is it closed?

**Comment by Connecteq** [comment]
Someone need to review the changes and approve them. I have the right file in the folder

**Comment by Connecteq** [comment]
PR Summary
File not allowed: blockchains/safecom/info/info.json. Please revert it.
File not allowed: blockchains/safecom/info/logo.png. Please revert it.
File not allowed: safecom trust wallet logo. Please revert it.

Can someone please help me with this as the correct files are in the correct folder but it's saying file not allowed.

**Review by Connecteq — COMMENTED** [review]
Can you please approve changes

**Comment by Cryptocool1** [comment]
Please create new PR, follow doc https://community.trustwallet.com/t/how-to-submit-a-token-logo/3863
You may want to try our new Assets app in beta; go to https://assets.trustwallet.com, log on with Github, enter contract ID, logo and some additional info, and it will create a PR for you.
See https://community.trustwallet.com/t/how-to-submit-a-token-logo-using-assets-app/82957.

When creating new PR, mention this PR, so that fee can be reused, and not paid again.

**Comment by Connecteq** [comment]
I have a created another one Safecom Logo #9631

**Comment by Connecteq** [comment]
https://github.com/trustwallet/assets/pull/9631

**Pull request closed without merging**
