### PR TITLE
add kodexpay

### PR DESCRIPTION
**Pull request by Kodexpay**
KXP token logo & Adding info for BEP20 token 'KodexPay'.
we stay in coinmarketcap https://coinmarketcap.com/currencies/kodexpay/
whitepaper https://token.kodexpay.com/whitepaper & https://github.com/Kodexpay/whitepaper
bsc explorer https://bscscan.com/token/0x02a655942dbb886c77bb22b270060c561300b0e2
KXP
contract address 0x02a655942Dbb886c77bb22B270060c561300B0E2
Chain : BSC
https://facebook.com/KodexPay

### CODE REVIEW

**Comment by Kodexpay** [comment]
Hi everything in order to pay the fee?

**Comment by Cryptocool1** [comment]
• What is the purpose of this token? How will it benefit Trust Wallet users?
 • How is the token being distributed? Are you conducting an airdrop?
 • Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?
 • Is the token listed on a centralized/decentralized exchange?
 • Is a Smart Contract audit completed? Where can we find this information?

**Comment by Kodexpay** [comment]
• What is the purpose of this token? 
We believe that blockchain technology will be a complement to the existing payment infrastructure soon and be used more broadly. Traditional payment instruments will use this protocol as an efficient, easy, effective, and global access. However, the technical and operational complexity in managing instruments that are run properly from this technology will make most companies look for service intermediaries or platforms to overcome the various problems encountered so far.
This service must be designed with a system that is not compromised and does not provide opportunities for security breaches. The core principles of Kodex are security, data protection, compliance, and freedom of choice for users to use available payment methods or instruments. Peer-to-peer payer systems and Distributed Journal support minimize the risk of data loss or fraud by irresponsible people.
The e-commerce system designed by Kodex is specifically designed to solve the problems encountered in getting goods or services in conventional e-commerce. With the support of blockchain technology, currency differences are no longer a problem in trading. Kodex provides a full-scale multi-currency exchange service, so you do not need to worry about anything. The Kodex Wallet service is a choice for those who want to access and manage their digital asset accounts anytime and anywhere.
A decentralized portal at Kodex gives merchants access to manage business needs, transact with other merchants or interact with consumers. Kodex and its product range will provide users with an allin-one platform. Thus, Kodex can be trusted by users to manage and spend their funds and assets. Creating digital global commerce is our goal and we achieve it with Kodex products.
How will it benefit Trust Wallet users? trus wallet users can connect to kodexpay.com our payment gateway
• How is the token being distributed?
For Publici Sale 50.0% 35.000.000 KXP Funders 24.0% 16.800.000 KXP For preSale 20.0% 14.000.000 KXP Advisor 5.0% 3.500.000 KXP Team 1.0% 700.000 KXP
• Is the token listed on a centralized/decentralized exchange?
 [VinDAX](https://coinmarketcap.com/exchanges/vindax/), and [PancakeSwap (V2)](https://coinmarketcap.com/exchanges/pancakeswap-v2/). 
https://vindax.com/exchange-base.html?symbol=KXP_USDT
https://pancakeswap.finance/swap?outputCurrency=0x02a655942Dbb886c77bb22B270060c561300B0E2

**Comment by cryptomanz1** [comment]
• Is a Smart Contract audit completed? Where can we find this information?

**Comment by Kodexpay** [comment]
hi ,  the repo and  audited  report link is  https://github.com/Kodexpay/token/blob/main/Audit-security-kodexpay.pdf

**Pull request merged**
