### PR TITLE
Add CryptonlyFanz (BEP20)

### PR DESCRIPTION
**Pull request by albendo**
Adding info for BEP20 token 'CryptonlyFanz'.

PR created by <a href="https://assets.trustwallet.com">TW Assets Management</a>

### CODE REVIEW

**Comment by cryptomanz** [comment]
• What is the purpose of this token? How will it benefit Trust Wallet users?
 • How is the token being distributed? Are you conducting an airdrop?
 • Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?
 • Is the token listed on a centralized/decentralized exchange?
 • Is a Smart Contract audit completed? Where can we find this information?

**Comment by albendo** [comment]
www.cryptonlyfanz.com

**Comment by albendo** [comment]
Cryptonlyfanz is a decentralized social network dedicated to providing a platform that connects exclusive influencer content and their fanz like never before. Our decentralized platform is powered by COF Token; a cryptocurrency with embedded features that sustains a low-cost environment where content creators and subscribers can connect with little interference from a third party. To learn more please reference our

As the cryptocurrency of the CRYPTONLYFANZ platform, COF Token is the preferred cryptocurrency used to pay for content on our platform. We do accept additional leading cryptocurrencies as payment, however its internally converted and will be displayed as COF Token in your user account. The demand, utility and transparency of processing totals engage a financial system that supports our decentralized platform. This allows you the subscriber, the content creator and the investor to be enriched by your interactions with CRYPTONLYFANZ.COM and your token of choice; COF


https://cryptonlyfanz.com/static/media/whitepaper.abd8fe24.pdf

http://www.cryptonlyfanz.com
http://twitter.com/cryptonlyfanz
https://t.me/cryptonlyfanz
https://instagram.com/cryptonlyfanz

**Comment by Cryptocool1** [comment]
Hello,
Please follow the rules for adding token, your logo should be a full screen, 256x256.
Example:
https://community.trustwallet.com/t/how-to-submit-a-token-logo/3863

**Comment by albendo** [comment]
output-onlinepngtools

**Comment by albendo** [comment]
hello, I have added everything properly and made the payment, if you confirm, I would be very grateful, with respect and love

**Comment by albendo** [comment]
CONTRACT ID

0xC477c189d6C572F6C618eA76658B062b1530224c



NAME

CryptonlyFanz Token

SYMBOL

COF

DECIMALS

9

**Comment by albendo** [comment]
Hi have added everything properly and made the payment, if you confirm, I would be very grateful, with respect and love

**Comment by albendo** [comment]
Correct dimensions provided, thanks for the heads up.

**Pull request merged**
