### PR TITLE
add Elrond BHAT-c1fde3 ESDT token for whitelisting

### PR DESCRIPTION
**Pull request by mariusgrigoras**

### CODE REVIEW

**Comment by mariusgrigoras** [comment]
Hey @Iamdeadlyz, @Cryptocool1, @cryptomanz - can you please take a look to this PR and approve it?
Thank you!

**Comment by Cryptocool1** [comment]
Hello, 
As per our policy, brand new tokens are not included, there is a minimum requirement of 10,000 holder addresses and 20,000 transactions, in order to filter out scam tokens.
See the criteria at : https://developer.trustwallet.com/assets/requirements .

**Comment by mariusgrigoras** [comment]
> Hello, As per our policy, there is a minimum requirement of 10,000 holder addresses and 20,000 transactions See the criteria at : https://developer.trustwallet.com/assets/requirements .

Hey, sure, we'll wait to have these requirements completed and ping you after.

Thank you,
Marius

**Comment by Cryptocool1** [comment]
Please come back to us once all criteria are met. Make sure to mention this PR so the fee can be reused.

**Pull request closed without merging**
