### PR TITLE
Add Pup Doge (BEP20)

### PR DESCRIPTION
**Pull request by Pupdoge2021**
Adding info for BEP20 token 'Pup Doge'.

PR created by <a href="https://assets.trustwallet.com">TW Assets Management</a>

### CODE REVIEW

**Comment by Pupdoge2021** [comment]
Hi, We will settle payment soon. please do not close the thread. Thank you very much!

**Comment by Pupdoge2021** [comment]
Hi, We have done the transfer of 5BNB to the wallet address stated above.

Please do check and let me know. 

photo_2021-08-03_14-19-48

**Comment by cryptomanz** [comment]
hello,
can you answer some questions?
• What is the purpose of this token? How will it benefit Trust Wallet users?
 • How is the token being distributed? Are you conducting an airdrop?
 • Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?
 • Is the token listed on a centralized/decentralized exchange?
 • Is a Smart Contract audit completed? Where can we find this information?

**Comment by Pupdoge2021** [comment]
Hi, Would like to know when will the logo be up on Pancakeswap

image

**Comment by Pupdoge2021** [comment]
> hello,
> can you answer some questions?
> • What is the purpose of this token? How will it benefit Trust Wallet users?
> • How is the token being distributed? Are you conducting an airdrop?
> • Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?
> • Is the token listed on a centralized/decentralized exchange?
> • Is a Smart Contract audit completed? Where can we find this information?

Hi I have dropped an email to Nazar in regards to the questions

**Comment by Cryptocool1** [comment]
> > hello,
> > can you answer some questions?
> > • What is the purpose of this token? How will it benefit Trust Wallet users?
> > • How is the token being distributed? Are you conducting an airdrop?
> > • Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?
> > • Is the token listed on a centralized/decentralized exchange?
> > • Is a Smart Contract audit completed? Where can we find this information?
> 
> Hi I have dropped an email to Nazar in regards to the questions

Hello, you should answer here

**Comment by Pupdoge2021** [comment]
What is the purpose of this token? How will it benefit Trust Wallet users?
We are starting to develop a blockchain game that allows users to play and earn real value via cryptocurrency. as well as some portion of the earning may donate to animal shelter.

How is the token being distributed? Are you conducting an airdrop?
We have airdrop event conducting soon.

Did you sell the tokens at an Initial Coin Offering (ICO) or a token presale?
Token Presale had taken place on 30 July 2021

Is the token listed on a centralized/decentralized exchange?
Decentralized Exchange currently. And we are in talks to list on Centralized Exchange as well.

Is a Smart Contract audit completed? Where can we find this information?
https://www.certik.org/projects/pupdoge

**Pull request merged**
