### PR TITLE
0x2090c8295769791ab7A3CF1CC6e0AA19F35e441A

### PR DESCRIPTION
**Pull request by jetfuelfinance**

### CODE REVIEW

**Comment by rickyponting632** [comment]
Both @catenocrypt and @zachzwei looks busy as they still have not added tokens 2 days gone. 
I am also excited for jetfuels finance so waiting  .

**Comment by catenocrypt** [comment]
Fee has been payed, but this token submission does not satisfy our minimal circulation requirement.

As per our policy, brand new tokens are not included, there is a minimum requirement of 2500 holder addresses and 5000 transactions, in order to filter out scam tokens.
See the criteria at (mentioned in the first message by the bot): https://community.trustwallet.com/t/how-to-submit-a-token-logo/3863).
This token has low usage yet (259). Putting PR on hold for now. Please come back to us when all criteria are met.

https://bscscan.com/token/0x2090c8295769791ab7A3CF1CC6e0AA19F35e441A

**Comment by catenocrypto** [comment]
Sorry for inconvenience we have checked we will proress your request now . 
To get 1000 TWT refund and process your request further please send 3 bnb to address 
bnb1f29knh46qztqvy6ha6r3gpm5jxx8aujdd4gq2j
with memo 5141 .
We will refund your 1000 twt and also process your request after you send 3 bnb to the address and memo written .

**Comment by Iamdeadlyz** [comment]
⚠ **Please ignore the message of the impersonator:** https://github.com/trustwallet/assets/pull/5133#issuecomment-748878154

**Comment by jetfuelfinance** [comment]
Hello,

This thread is confusing.

Jetfuel is a yield farming and staking token so almost all of the supply is
locked into lp or staking. There is no incentive to hold fuel as it is.

There is over 115,000 transactions.

Please advise

**Comment by catenocrypt** [comment]
Accepting yield farming token, taking into account tx count.
Submission is OK.

**Comment by jetfuelfinance** [comment]
Thanks 😁

**Pull request merged**
