### PR TITLE
Add BeerusCat (BEP20)

### PR DESCRIPTION
**Pull request by inmefinance**
Adding info for BEP20 token 'BeerusCat'.

PR created by <a href="https://assets.trustwallet.com">TW Assets Management</a>

### CODE REVIEW

**Comment by inmefinance** [comment]
We have more than 11,000 holders can update logo now ?

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by inmefinance** [comment]
This wrong link


https://raw.githubusercontent.com/inmefinance/assets/br0925-114803/blockchains/smartchain/assets/0x64ef3ae48977075d917e448b61c7b030b9c387fc/info.json




Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by inmefinance** [comment]
Token BEP20 - 0x3a310e6EAf960F9EA208764e9D299ea62A0ea53d:
Symbol: BCat decimals: 9
Links: Logo<https://raw.githubusercontent.com/inmefinance/assets/br0925-114803/blockchains/smartchain/assets/0x3a310e6EAf960F9EA208764e9D299ea62A0ea53d/logo.png> Info<https://raw.githubusercontent.com/inmefinance/assets/br0925-114803/blockchains/smartchain/assets/0x3a310e6EAf960F9EA208764e9D299ea62A0ea53d/info.json> Website<https://beeruscat.link/> Explorer<https://bscscan.com/token/0x3a310e6EAf960F9EA208764e9D299ea62A0ea53d>
Tags: memes
Token check error:
❌ number of holders not checked: please, check it manually

This the one we need update logo for it please check

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by inmefinance** [comment]
I don’t know him I send 1 pull request

PR Summary

Files OK: 2
Token in PR: BEP200x3a310e6EAf960F9EA208764e9D299ea62A0ea53d
Symbol: BCat decimals: 9
Links: Logo<https://raw.githubusercontent.com/inmefinance/assets/br0925-114803/blockchains/smartchain/assets/0x3a310e6EAf960F9EA208764e9D299ea62A0ea53d/logo.png> Info<https://raw.githubusercontent.com/inmefinance/assets/br0925-114803/blockchains/smartchain/assets/0x3a310e6EAf960F9EA208764e9D299ea62A0ea53d/info.json> Website<https://beeruscat.link/> Explorer<https://bscscan.com/token/0x3a310e6EAf960F9EA208764e9D299ea62A0ea53d>
Tags: memes
Token check error:
❌ number of holders not checked: please, check it manually

We have more than 11k holders

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by inmefinance** [comment]
Please we need add logo what I do ?

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by inmefinance** [comment]
I fill the form can guide me ?

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by inmefinance** [comment]
My dear Nizar can tell me what the next step ?

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by Cryptocool1** [comment]
hello,
• What is the purpose of this token? How will it benefit Trust Wallet users?
 • How is the token being distributed? Are you conducting an airdrop?
 • Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?
 • Is the token listed on a centralized/decentralized exchange?
 • Is a Smart Contract audit completed? Where can we find this information?

**Comment by inmefinance** [comment]
It’s meme token
No airdrop buy and sell from all dex
Token sold at pinksale presale we softcap 240bnn and hard cap 480 Bnb
And now our liquidity pool have more than 1000 Bnb
Yea this token Listed on almost of dex like pancakeswap  and more
Yea contract audit and you can check the link below


https://github.com/CrackenTechAudit/Reports/blob/main/Cracken_Audit_Report_BeerusCatToken.pdf

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by Cryptocool1** [comment]
• What is the purpose of this token? How will it benefit Trust Wallet users?

**Comment by inmefinance** [comment]
if there way to benfit them we can discuss about it I don’t know to upload logo need to that so we are flexible and we can find way to benefit them

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by inmefinance** [comment]
So it’s okay we can update logo please ?

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by inmefinance** [comment]
You can check BSC explore we have exactly 11247 addresses  and 58658 transfer
No air drop all organic so can add logo now ?

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Pull request closed without merging**
