### PR TITLE
Adding RiseUp Official Logo

### PR DESCRIPTION
**Pull request by stistryn**
Adding the logo for RiseUp Official token

Social links are in info.json

### CODE REVIEW

**Comment by Cryptocool1** [comment]
As per our policy, brand new tokens are not included, there is a minimum requirement of 2500 holder addresses and 5000 transactions, in order to filter out scam tokens.
See the criteria at (mentioned in the first message by the bot): https://community.trustwallet.com/t/how-to-submit-a-token-logo/3863).
Closing PR for now. Please come back to us when all criteria are met.

**Comment by stistryn** [comment]
We reached 2,5000 holders last 12 hours. And I have transferred 1,000 TWT to the wallet specified.

Is there a way to trigger the checks to run again? Any other changes needed to reopen the pull request? Thanks

**Comment by stistryn** [comment]
I've pushed a commit to the fork with audit and whitepaper links, but this didn't trigger an update here.  Probably because it is closed.

@Cryptocool1 I've enabled allow edits by maintainer if that helps. 

Is it better to create a new pull request? 

And is the fee payment registered even if the bot is not triggered here? 

Thanks again for your services!

**Comment by cryptomanz** [comment]
the master branch was force-pushed or recreated

**Comment by stistryn** [comment]
I rebased the changes on top of trustwallet:master. Let me see if I can revert that. Or else I'll just open a new pull

**Comment by Cryptocool1** [comment]
Just open new PR

**Comment by stistryn** [comment]
Hi @Cryptocool1 can you re-open this now? I've removed the rebase (should be back to what it was + one commit). 

I'll create a new PR if that doesn't work, as we have already payed with this address and memo.

**Comment by Cryptocool1** [comment]
Payment was not found by the bot; could you provide TXID or date for checking?

**Comment by stistryn** [comment]
Thanks, I see the requirement has changed as well since we opened it?  Can that be waived or do we have to wait till we meet new requirement?

Transaction for payment:
https://explorer.binance.org/tx/327457816E0665587A484B80326BD42154B595E31C0E84198BC33F477EE40B02

**Comment by stistryn** [comment]
This is the TechRate audit report:

https://github.com/TechRate/Smart-Contract-Audits/blob/main/RiseUp%20Full%20Smart%20Contract%20Security%20Audit.pdf

**Comment by stistryn** [comment]
I noticed the fee has increased as well since we initially created the pull request, I had payed what the bot asked for:

> Please pay 1000 TWT with the memo 883 to the address bnb1tqq9llyr3dyjd559dha6z5r5etk3qfwk07m098.

**Comment by stistryn** [comment]
Thanks @Cryptocool1 this is awesome! Have a great weekend!

**Pull request merged**
