### PR TITLE
Add Nap logo

### PR DESCRIPTION
**Pull request by aszquasz**

### CODE REVIEW

**Comment by AndreZZZ123** [comment]
Hi @zachzwei , i reopened this PR with `info.json`. Are we still missing some information?

**Comment by catenocrypt** [comment]
Could you make background transparent?  Looks weird in dark mode

image

**Comment by zachzwei** [comment]
Need more details about this token. 
The website you referred to is with zzz finance.

**Comment by aszquasz** [comment]
@catenocrypt made it transparent.
@zachzwei NAP is the secondary token to ZZZ, will it suffice to update our page on `zzz.finance` ? its part of the same ecosystem :)

**Comment by zachzwei** [comment]
> @catenocrypt made it transparent.
> @zachzwei NAP is the secondary token to ZZZ, will it suffice to update our page on `zzz.finance` ? its part of the same ecosystem :)

Where does it say that it is the secondary token? I do not see it on the site.

**Comment by aszquasz** [comment]
updated frontpage info and linked new pools

**Comment by catenocrypt** [comment]
image

**Pull request merged**
