### PR TITLE
Add POX trc20 token logo

### PR DESCRIPTION
**Pull request by Shyamthakur33**

### CODE REVIEW

**Comment by Shyamthakur33** [comment]
@Iamdeadlyz plz suggest why all checks failed

**Comment by Iamdeadlyz** [comment]
> @Iamdeadlyz plz suggest why all checks failed

The file size of the logo was too big. I already compressed it, nothing to worry.

===

Please provide more details about this project.
https://community.trustwallet.com/t/how-to-submit-a-token-logo/3863#how-to-get-approved
You can follow this format when adding an info.json file:
```
{
    "name": "Trust Wallet Token",
    "website": "https://trustwallet.com",
    "source_code": "https://github.com/trustwallet/",
    "short_description": "Utility token to increase adoption of cryptocurrency.",
    "description": "Utility token to increase adoption of cryptocurrency.",
    "socials": [
        {
            "name": "Twitter",
            "url": "https://twitter.com/trustwalletapp",
            "handle": "TrustWalletApp"
        },
        {
            "name": "Reddit",
            "url": "https://reddit.com/r/trustapp",
            "handle": "TrustApp"
        }
    ],
    "explorer": "https://bscscan.com/token/0x4b0f1812e5df2a09796481ff14017e6005508003"
} 
```

**Comment by Shyamthakur33** [comment]
Please check details and let me know

**Comment by Shyamthakur33** [comment]
Iamdeadlyz plz check our project details

**Review by Iamdeadlyz — APPROVED** [review]
info.json and logo is ok ✅ 
waiting for the payment to proceed in merging

**Comment by Shyamthakur33** [comment]
> info.json and logo is ok ✅
> waiting for the payment to proceed in merging

payment done

**Pull request merged**
