### PR TITLE
Add Cosanta (COSA)

### PR DESCRIPTION
**Pull request by gades**
Security audit:

https://github.com/TechRate/Smart-Contract-Audits/blob/main/January_2024/Cosanta.pdf

### CODE REVIEW

**Comment by cryptomanz1** [comment]
• What is the purpose of this token? How will it benefit Trust Wallet users?
 • How is the token being distributed? Are you conducting an airdrop?
 • Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?
 • Is the token listed on a centralized/decentralized exchange?

**Comment by gades** [comment]
> • What is the purpose of this token? How will it benefit Trust Wallet users?
> • How is the token being distributed? Are you conducting an airdrop?
> • Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?
> • Is the token listed on a centralized/decentralized exchange?

1) It's wrapped token for native Cosanta coin https://www.coingecko.com/en/coins/cosanta
we've mining PoS pool and users can get reward in tokens https://pirate.place/en/investing/cosa 
2) All coins were distributed between users who did PoW mine (first 100k blocks were only PoW and right now it's hybrid mining PoS + PoW ) https://www.youtube.com/watch?v=MDzScTGdGmU&t=1s
3) We didn't do preMine or preSalse (right now only 160548 COSA was mined  https://explorer.cosanta.net )
4) Yes, Cosanta is listed on:
- CatEx (https://www.catex.io/trading/COSA/BTC?load=1)
- GraviEx  (https://graviex.net/markets/cosabtc)

**Comment by Cryptocool1** [comment]
Please update your branch to the recent master

**Comment by gades** [comment]
@Cryptocool1 done

**Pull request merged**
