### PR TITLE
Add ArbiSmart Token (RBIS) (ERC20)

### PR DESCRIPTION
**Pull request by Arbismart**
Adding info for ERC20 token 'ArbiSmart Token (RBIS)'.

PR created by <a href="https://assets.trustwallet.com">TW Assets Management</a>

### CODE REVIEW

**Comment by cryptomanz** [comment]
• What is the purpose of this token? How will it benefit Trust Wallet users?
 • How is the token being distributed? Are you conducting an airdrop?
 • Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?
 • Is the token listed on a centralized/decentralized exchange?
 • Is a Smart Contract audit completed? Where can we find this information?

**Comment by Arbismart** [comment]
> • What is the purpose of this token? How will it benefit Trust Wallet users? • How is the token being distributed? Are you conducting an airdrop? • Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale? • Is the token listed on a centralized/decentralized exchange? • Is a Smart Contract audit completed? Where can we find this information?

• What is the purpose of this token? How will it benefit Trust Wallet users?
ArbiSmart platform operates with its own native token RBIS, designated for provision of access to certain functions of the ArbiSmart platform. Users are entitled to use RBIS token to pay internal fees at ArbiSmart platform. 
Users are entitled to use RBIS token to purchase special mystery boxes that allow user to get real-word merchandise (calendars, pieces of wear and other). Delivery of such merchandise are subject to separate payment depending on User`s location. 5. Users holding RBIS token become participants of special ArbiSmart loyalty program that opens certain improved functions of ArbiSmart platform like faster transactions available in ArbiSmart platform.
Users are entitled to use RBIS token to make purchases of NFTs that made available on the ArbiSmart platform. 7. The RBIS token provides the user with DAO governance rights entitling users to vote for the further development of the ArbiSmart platform.
The Trust Wallet users can be involved in all previously described activities using RBIS tokens.


• How is the token being distributed? Users can purchase a token on the ArbiSmart platform or CEX  and DEX. Are you conducting an airdrop? 
No

• Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale? 
No

• Is the token listed on a centralized/decentralized exchange? 
Yes. HitBTC (https://hitbtc.com/rbis-to-usdt) , Latoken (https://latoken.com/exchange/RBIS_USDT), Coinsbit (https://coinsbit.io/ru/trade_classic), Uniswap (https://v2.info.uniswap.org/token/0xf34b1db61aca1a371fe97bad2606c9f534fb9d7d), Shuhiswap (https://analytics.sushi.com/pairs/0xc07f855e98405a295c26cd1c6615013ffa7af715).

• Is a Smart Contract audit completed? 
No. This is a common type of ERC-20 smart contract.   

• Where can we find this information? 
Please check it here: https://etherscan.io/address/0xf34b1db61aca1a371fe97bad2606c9f534fb9d7d

**Comment by cryptomanz** [comment]
awaiting for smart contract audit.

**Comment by cryptomanz** [comment]
Please come back to us when all criteria are met.
When creating a new PR make sure to mention this PR, so that we can see that fee has been paid already here.

**Comment by Arbismart** [comment]
> Please come back to us when all criteria are met. When creating a new PR make sure to mention this PR, so that we can see that fee has been paid already here.

Clarify, please. Do you mean the amount of token holders?

**Comment by Cryptocool1** [comment]
Token holders and smart contract audit

**Comment by Arbismart** [comment]
> Token holders and smart contract audit

Are there some requirements for this? Because it is a common type SC for the issue of tokens. Nothing special.

**Comment by Arbismart** [comment]
We need just to update a logo for our project on Uniswap.

**Comment by Cryptocool1** [comment]
Please see our requirements here: https://developer.trustwallet.com/assets/requirements

**Pull request closed without merging**
