### PR TITLE
Add B2U Coin (BEP20)

### PR DESCRIPTION
**Pull request by ah2020b**
Adding info for BEP20 token 'B2U Coin'.

PR created by <a href="https://assets.trustwallet.com">TW Assets Management</a>

### CODE REVIEW

**Comment by cryptomanz** [comment]
Hello,
Can your answer some questions?
• What is the purpose of this token? How will it benefit Trust Wallet users?
 • How is the token being distributed? Are you conducting an airdrop?
 • Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?
 • Is the token listed on a centralized/decentralized exchange?
 • Is a Smart Contract audit completed? Where can we find this information?

**Comment by ah2020b** [comment]
Hi

Sure, please find answers bellow:
• What is the purpose of this token? How will it benefit Trust Wallet users?
B2U Coin is the token of Bitcointoyou exchange, we started our OTC in 2010
and launched the exchange site in 2012 (www.bitcointoyou.com). We are one
of the most important exchanges in Brazil, of course we are smaller
than Binance, but we are working hard to increase our users and going to
expand to other countries soon. A lot of our customers use Trust Wallet to
keep his crypto safe, so they asked for us to list our token on Trust
Wallet, today we have 400 thousand customers on Bitcointoyou exchange.

• How is the token being distributed? Are you conducting an airdrop?
We have created the token on 13 of October of last year and starting
selling on our exchange (Bitcointoyou.com) (
https://etherscan.io/token/0x350758e4a1256561fd0ee142dc7e0545f561fadc), but
users don't want to use on Ethereum network because the fees, so we have
migrated to Binance Smart Chain on the last semester, so they loved, most
transaction is happen on BSC20 now. Because this our coin have the price of
$ 0.25 as you can see here https://www.coingecko.com/en/coins/b2u-coin

• Did you sold the tokens at an Initial Coin Offering (ICO) or a token
presale?
No, direct on our exchange.

• Is the token listed on a centralized/decentralized exchange?
Yes, the list is public on token website's (https://b2ucoin.com/). Some
exchanges that is listed:
Bitcointoyou
Exmarket
Bleutrade
PancakeSwap

• Is a Smart Contract audit completed? Where can we find this information?
We have created the token using: https://cointool.app/createToken/bsc
They have written that all tokens created by them are audited.

Regards & Atenciosamente




*Este email é dirigido apenas à pessoa para quem é endereçado e/ou de outra
forma pessoal autorizado. A informação contida nesta e anexada é
confidencial e de propriedade da BitcoinToYou. Se você não é o recipiente
pretendido, por favor fique avisado que a vista desta mensagem e quaisquer
anexos, bem como cópia, mandar adiante, impressão, e disseminação de
qualquer informação relacionada à este email é proibida, e que você não
deve tomar nenhuma ação baseada no conteúdo deste email.*

*This email is only addressed to the person to it is addressed and / or
otherwise authorized personnel. The information contained and attached is
confidential and owned by BitcoinToYou. If you are not the intended
recipient, please be advised that viewing this message and any attachments,
as well as copying, forwarding, printing, and disseminating any information
related to this email is prohibited, and that you must not take any action
based on the content of this email.*


Em ter., 5 de out. de 2021 às 17:44, Nazar ***@***.***>
escreveu:

**Comment by cryptomanz** [comment]
- Awaiting for smart contract audit. On hold for now.

**Comment by ah2020b** [comment]
Hi

Audit is published, could you approve now please?

https://tokenguard.io/ratings/b2u

Regards

**Pull request closed without merging**
