### PR TITLE
Add Nano DogeCoin Token Information and Logo

### PR DESCRIPTION
**Pull request by BSCGuru**
Add Nano DogeCoin Token Information and Logo

Recently did a tokenswap with new contract and Twitter link Information.

### CODE REVIEW

**Comment by BSCGuru** [comment]
Token BEP20 - 0xD3Af8E09894D69E937e37eeF46Df1cBF82b35C81

This is the correct contract after tokenswap, please advise how to proceed.

**Comment by BSCGuru** [comment]
Here is their updated audit:
https://nanodogecoin.com/brewlabs-audit.html

For the new contract: 0xD3Af8E09894D69E937e37eeF46Df1cBF82b35C81

**Comment by BSCGuru** [comment]
• What is the purpose of this token? How will it benefit Trust Wallet users?
Holders of Nano Dogecoin benefit as they are rewarded with USD-Tether redistributions on transactions in/out of the token. They are also able to invest in a token that supports animal welfare globally, by making charitable donations to shelters for rescuing and rehoming dogs.

• How is the token being distributed? Are you conducting an airdrop?
Nano DogeCoin ($NDC) was sold via Private Sale (via our website), then Presale (via DxSale) and then publicly via PancakeSwap.
INDC is a tokenswap from NDC. Details of tokenswap migration can be found here: https://nanodogecoin.com/migration-faq.html

• Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?
There were 2 Public Presales before PancakeSwap launch, totalling 6,100 BNB raised. <-- NDC. 
INDC is a tokenswap from NDC. Details of tokenswap migration can be found here: https://nanodogecoin.com/migration-faq.html

• Is the token listed on a centralized/decentralized exchange?
Decentralised exchange - PancakeSwap.

• Is a Smart Contract audit completed? Where can we find this information?
Yes - Audited by Brewlabs (PDF can be found here: [https://nanodogecoin.com/brewlabs-audit.html],

**Comment by Cryptocool1** [comment]
0x1B41821625d8CFAd21cd56491DACD57ECaCc83dE is it your token?

**Comment by BSCGuru** [comment]
0x1B41821625d8CFAd21cd56491DACD57ECaCc83dE

Token swapped to: 0xD3Af8E09894D69E937e37eeF46Df1cBF82b35C81

Do refer to : https://www.coingecko.com/en/coins/nano-dogecoin

Tokenswap (Migration) Info: https://nanodogecoin.com/migration-faq.html

Screencap of Coingecko: http://prntscr.com/1sq1lwf

**Comment by BSCGuru** [comment]
Is it possible to remove the png for the old contract: 0x1B41821625d8CFAd21cd56491DACD57ECaCc83dE

So that holders will not mistake the old contract with the new?

**Pull request merged**
