### PR TITLE
add Anime Token logo

### PR DESCRIPTION
**Pull request by Anime-Token**
update to new logo please

### CODE REVIEW

**Comment by Cryptocool1** [comment]
submission looks good waiting for fee payment

**Comment by Xsures** [comment]
hey i did make the payment, please help us to update our new logo on trustwallet :)

**Comment by Cryptocool1** [comment]
did you add the info for your token?

**Comment by Xsures** [comment]
yes https://github.com/trustwallet/assets/pull/7910 informations still the same only new logo

**Comment by Xsures** [comment]
When we can see new logo in trustwallet?!

**Comment by Xsures** [comment]
????

**Comment by Xsures** [comment]
https://github.com/Xsures/assets/blob/e09a0d6e4508b579927b17d821fedf12d443b8db/blockchains/smartchain/assets/0xaC472D0EED2B8a2f57a6E304eA7eBD8E88D1d36f/logo.png

change our logo please, i did payment

**Comment by Cryptocool1** [comment]
can you send the logo image here please?

**Comment by Xsures** [comment]
Am So., 14. Nov. 2021 um 02:37 Uhr schrieb CryptoA ***@***.***

**Comment by Xsures** [comment]
logo

**Comment by Cryptocool1** [comment]
you logo was updated 2 days ago
https://github.com/trustwallet/assets/pull/15626

**Pull request merged**
