### PR TITLE
Add files via upload

### PR DESCRIPTION
**Pull request by APEtoken**
This PR is being closed due to inactivity. If you wish to continue, please have us reopen the PR before sending your payment.
Do NOT send payments for closed PR, as the fee may by lost!
  (99 vs. 99 hrs)

### CODE REVIEW

**Comment by catenocrypt** [comment]
Note: ERC20 version already present (with low circulation, https://etherscan.io/token/0x209C1808FeBf6c1aB7C65764bb61AD67d3923fcc)

**Comment by catenocrypt** [comment]
Submission looks OK, awaiting payment.

**Comment by APEtoken** [comment]
> Submission looks OK, awaiting payment.

I already submitted payment on my first attempt on PR #6208 . I just had to create new PR with this one to correct my errors. Heres a link to the bot replying to me saying the payment was confirmed. Thanks for the help. cheers. https://github.com/trustwallet/assets/pull/6208#pullrequestreview-627417730

**Comment by catenocrypt** [comment]
Payment considered from #6208 (also PR #6244)
2 BNB https://explorer.binance.org/tx/B9228FE6B3CCA3024EA74D6C156B5E8FCF038CBFA2238BE17D338C3D09B80887

**Comment by APEtoken** [comment]
> Payment considered from #6208 (also PR #6244)
> 2 BNB https://explorer.binance.org/tx/B9228FE6B3CCA3024EA74D6C156B5E8FCF038CBFA2238BE17D338C3D09B80887

Hey thanks for the help in getting this taken care of for me. I am now looking to update the logo. to do this would I just need to pull a fresh fork of the asset folder then just upload the update logo.png file until the ape folder? then create a pull request for the change? Let me know if this is correct as I am unsure and cant find any info online on how to updated a logo. Thanks!

**Comment by catenocrypt** [comment]
Yes.  Up-to-date fork repo is important in order to avoid merge conflicts.  Note that PR fee is expected with *every* PR, not just new token addition, though.

**Pull request merged**
