### PR TITLE
testmerge

### PR DESCRIPTION
**Pull request by lucdefi**
tw pr to add sats token info

### CODE REVIEW

**Comment by cryptomanz** [comment]
logo file sound be named logo.png exactly

**Comment by cryptomanz** [comment]
fixed logo

**Comment by cryptomanz** [comment]
correction needed:
- Contract is not in checksum format, should be 0xa1D04A189f8b6d5d64e8Fea7c38846AB6fa0F823 (not 0xa1d04a189f8b6d5d64e8fea7c38846ab6fa0f823)
- Logo image too large, max 100 kB, current 105.414 kB

**Comment by cryptomanz** [comment]
As per our policy, brand new tokens are not included, there is a minimum requirement of 5000 holder addresses and 10000 transactions, in order to filter out scam tokens.
See the criteria at (mentioned in the first message by the bot): https://community.trustwallet.com/t/how-to-submit-a-token-logo/3863).

**Comment by Cryptocool1** [comment]
please create new PR when all criteria are met

**Pull request closed without merging**
