### PR TITLE
Add SDOG logo and info

### PR DESCRIPTION
**Pull request by small-doge**
Adding info for ERC20 token 'SDOG'.

### CODE REVIEW

**Comment by Cryptocool1** [comment]
Correction needed:
 Logo should be 256x256 pixels

**Comment by Cryptocool1** [comment]
Remove this file please
dapps/smalldogecoin.com.png

**Comment by small-doge** [comment]
It has been revised. You are under review. Do you need to "RP" again?

**Comment by small-doge** [comment]
> Remove this file please
> dapps/smalldogecoin.com.png

It has been revised. You are under review. Do you need to "RP" again?

**Comment by small-doge** [comment]
> Remove this file please
> dapps/smalldogecoin.com.png

Please have a look. If there's no problem, I'll pay for it

**Comment by small-doge** [comment]
@Cryptocool1

**Comment by small-doge** [comment]
https://explorer.binance.org/address/bnb1fclqumgrdup627c4hqq4df7kz76w7qw8emrkvq


Already paid

**Pull request merged**
