### PR TITLE
Add DUET (BEP20)

### PR DESCRIPTION
**Pull request by duetist**
Adding info for BEP20 token 'DUET'.

PR created by <a href="https://assets.trustwallet.com">TW Assets Management</a>

### CODE REVIEW

**Comment by Cryptocool1** [comment]
• What is the purpose of this token? How will it benefit Trust Wallet users?
 • How is the token being distributed? Are you conducting an airdrop?
 • Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?
 • Is the token listed on a centralized/decentralized exchange?
 • Is a Smart Contract audit completed? Where can we find this information?

**Comment by duetist** [comment]
May I know when will this PR be merged into the trust wallet: master.

We're gonna have some events on PCS soon, hope could get the token verified there through Trust wallet, thx!

**Comment by Cryptocool1** [comment]
You didn’t answer to the questions above.

**Comment by duetist** [comment]
Sorry I missed the questions earlier. Here're the QAs, pls kindly check.

• What is the purpose of this token? How will it benefit Trust Wallet users?

DUET token is a key facilitator of the Growth of the Duet ecosystem. 

All of the Duet services including minting unit, security unit, liquidation unit and swap unit charge fees from the users, which is paid to the Duet treasury as income. The Duet DAO will approve spending to various farms. The farms are set with clear goals to grow the ecosystem and in turn increase the demand of the Duet services and thus generating more income. 
All farm rewards are paid in [$Bonded Duets](https://github.com/duet-protocol/functions-and-user-guides/usdbonded-duet), which will mature in 12 months time, but can be prematurely sold on the bond open market with a discount determined by market forces.

Trust wallet users can easily tap into one of the most well-round synthetic asset protocols by having DUET token.

• How is the token being distributed? Are you conducting an airdrop?

For token distribution, pls check our distribution curve:  https://duet-protocol.gitbook.io/duet-protocol/token-economics/token-distribution

There's no airdrop being conducted at the moment.

• Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?

Yep. We held an IFO in March 2022. You can check the details here:

https://pancakeswap.finance/ifo/history

• Is the token listed on a centralized/decentralized exchange?

Yep. We got listed on Pancakeswap and Bitmart.


• Is a Smart Contract audit completed? Where can we find this information?


Yep. We've got 3 rounds of audit by Peckshield, blocksec and Go+ respectively.

You can check all the reports from here: https://linktr.ee/duetaudit

**Pull request merged**
