### PR TITLE
Add BNB Tiger Inu (BEP20)

### PR DESCRIPTION
**Pull request by lejyoner1**
Adding info for BEP20 token 'BNB Tiger Inu'.

PR created by <a href="https://assets.trustwallet.com">TW Assets Management</a>

### CODE REVIEW

**Comment by Cryptocool1** [comment]
• What is the purpose of this token? How will it benefit Trust Wallet users?
 • How is the token being distributed? Are you conducting an airdrop?
 • Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?
 • Is the token listed on a centralized/decentralized exchange?
 • Is a Smart Contract audit completed? Where can we find this information?

**Comment by lejyoner1** [comment]
> • What is the purpose of this token? How will it benefit Trust Wallet users? • How is the token being distributed? Are you conducting an airdrop? • Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale? • Is the token listed on a centralized/decentralized exchange? • Is a Smart Contract audit completed? Where can we find this information?

👋 Hello TrustWallet team.BnbTiger has gained momentum and is rising day by day.  Our contract reached almost 1 year ago and we reached over 10k holders.

The team and community are very active on Twitter Space.

Answers to your questions and additional information are below:

1️⃣ $BNBTIGER is a decentralized experiment, launched on the January 3, 2022, by the founder, BNBTiger9527, as a fresh opportunity for those who were struggling in the midst of the biggest bear market since. Born out of trials and tribulation, the $BNBTIGER community is the strongest community you'll find, supportive of one another, and pushing each other towards success.
In 2021, all kinds of animal coins are coming, which some people say is just a hype and actually worthless. However, it is reasonable to exist, and we can see the two main values of Animal coins: they are easy for ordinary people to understand, and they may become the most important traffic entry point in the blockchain world.Pure decentralized community operation and DAO experiments over and over will bring a new way of organization to human beings.At the same time, we also noticed that the good and bad of animal currency are mixed. There are some successful cases such as DOGE and SHIBA, while there are some cases such as Rabbit that quickly crashed online, reflecting its experimental characteristics.In this context, we launched BNBTiger to try a completely decentralized community experiment. Considering that BNBTiger is a stable, fierce and lovely animal,
BNBTiger community culture is based on steady operation and fierce attack when the opportunity arises. At the same time, we want to be a cute and cute NFT community. To make BNBTiger a useful community currency with real application scenarios and a good ecology, BNBTiger will exist as an important part of the BSC ecology for a long time to build community consensus. We encourage most of our community to use TrustWallet. Because we really think that Trustwallet is the fastest, quality and secure application. It's really nice to think our investments are safe. We benefit Trust Wallet users by our coming integrations and huge community the majority off them use Trust Wallet.

2️⃣BNBTiger is a pure decentralized finance (DeFi) token running on the Binance Smart Chain (BEP-20). HIP aims to achieve a completely community-driven decentralized autonomous organization (DAO)BNBTiger total 10000000000000000000000000, of which 50% directly destroyed, the remaining 50% of initial decentralized trading liquidity pools, as a pure community experiment, HIP team share, private equity, all tokens for community construction.BNBTiger is completely decentralized. All addresses will be published to the community for community supervision.
3️⃣ We did not hold a Presale
4️⃣ We are listed on PancakeSwapV2
5️⃣ Contract Audited and all financial detail shared on
https://github.com/Tech-Audit/Smart-Contract-Audits/blob/main/TECHAUDIT_BNBTIGER.pdf

⭐️We are listed on Coinmarketcap and Coinecko. We are also currently still in community trending on Coinmarketcap.
⭐️ Our community votes and high score in Dextool, our liquidity is locked for 1 year.
ℹ️ https://www.dextools.io/app/en/bnb/pair-explorer/0x5e1aab9d49f6c7122df7de4d6dbd5b03c1ebb0b7

I am sending our useful links below. Thanks for your work.

Website: https://bnbtiger.top/
Twitter: https://twitter.com/BnbTiger
WhitePaper: https://bnbtiger.top/static/upload/file/20230203/1675386735503028.pdf
Coinmarketcap: https://coinmarketcap.com/currencies/bnbtiger/
Coingecko: https://www.coingecko.com/en/coins/bnb-tiger-inu
Medium: https://bnbtiger.medium.com/bnbtiger-6300a46ca53
Bitcointalk: https://bitcointalk.org/index.php?topic=5439775.0

**Comment by roymoses07** [comment]
lejyoner1:br0218-155126

**Review by roymoses07 — COMMENTED** [review]
Done

**Pull request merged**
