### PR TITLE
Add SoupSwap (BEP20)

### PR DESCRIPTION
**Pull request by SoupSwapOfficial**
Adding info for BEP20 token 'SoupSwap'.

PR created by <a href="https://assets.trustwallet.com">TW Assets Management</a>

### CODE REVIEW

**Comment by catenocrypt** [comment]
Extra files have been added again, should not have.

image

**Comment by catenocrypt** [comment]
Submission fixed; awaiting fee payment.

**Comment by SoupSwapOfficial** [comment]
I paid 6 hours ago. Please check :
https://explorer.binance.org/tx/431DB3B535A46C8F034DA43F7B7FDB94E6BE1B8655B8D13D2C55BFAF0F1793D7

**Comment by SoupSwapOfficial** [comment]
> Submission fixed; awaiting fee payment.

I paid 6 hours ago. Please check :
https://explorer.binance.org/tx/431DB3B535A46C8F034DA43F7B7FDB94E6BE1B8655B8D13D2C55BFAF0F1793D7

**Comment by SoupSwapOfficial** [comment]
IMAGE 2021-03-25 16:11:16

**Comment by catenocrypt** [comment]
> I paid 6 hours ago. Please check :

OK, sorry, you did not mention in this PR, and sometimes I miss the connection among the many PRs.

**Comment by catenocrypt** [comment]
Payment considered from #6061 , https://explorer.binance.org/tx/431DB3B535A46C8F034DA43F7B7FDB94E6BE1B8655B8D13D2C55BFAF0F1793D7

**Comment by SoupSwapOfficial** [comment]
> Payment considered from #6061 , https://explorer.binance.org/tx/431DB3B535A46C8F034DA43F7B7FDB94E6BE1B8655B8D13D2C55BFAF0F1793D7

Plz update logo token !

**Pull request merged**
