### PR TITLE
Add BSCX token to Trust Wallet

### PR DESCRIPTION
**Pull request by cryptofield**

### CODE REVIEW

**Comment by Iamdeadlyz** [comment]
As per our policy, brand new tokens are not included. There is a minimum requirement of 2500 holder addresses and 5000 transactions (airdropped tokens excluded) in order to filter out scam tokens. See the criteria at (mentioned in the first message by the bot): https://community.trustwallet.com/t/how-to-submit-a-token-logo/3863#how-to-get-approved

This token has below-limit usage yet. This pull request will be put on hold. Please come back to us when all criteria are met. Just comment here so we can re-open. Note: You don't need to pay again.
https://bscscan.com/token/0x5ac52ee5b2a633895292ff6d8a89bb9190451587 (1052, 25445)

**Comment by cryptofield** [comment]
Dear @Iamdeadlyz,
We have already passed 2,500 holders.
All criteria are met, please kindly review us.

**Comment by Iamdeadlyz** [comment]
We don't have write-access to your PR. Please fix the checksum issue by following this:
- Rename the folder to `0x5Ac52EE5b2a633895292Ff6d8A89bB9190451587-x`, commit, and push
- Rename it again to `0x5Ac52EE5b2a633895292Ff6d8A89bB9190451587`, commit, then push

**Comment by cryptofield** [comment]
Dear @Iamdeadlyz,

We already fix the checksum issue by following your recommendation.
Please kindly review us.

**Pull request merged**
