### PR TITLE
Adding logo and info

### PR DESCRIPTION
**Pull request by ashit-crypto**
Adding logo and info

### CODE REVIEW

**Comment by Cryptocool1** [comment]
Can you please add tags, see: https://developer.trustwallet.com/assets/requirements

**Comment by Cryptocool1** [comment]
• What is the purpose of this token? How will it benefit Trust Wallet users?
 • How is the token being distributed? Are you conducting an airdrop?
 • Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?
 • Is the token listed on a centralized/decentralized exchange?
 • Is a Smart Contract audit completed? Where can we find this information?

**Comment by ashit-crypto** [comment]
Tags updated. Additional info below:

_• What is the purpose of this token? How will it benefit Trust Wallet users?_ **This token provides reflections in 3 different coins every week - BNB, Bitcoin and Solana. In addition to this there will be community voting and partnerships with our popular tokens where those tokens will be bought back in special weeks and reflected to our token holders. We also have your minting dapp for the exclusive NFTs ready. Further in the roadmap we have planned an NFT comic book series where chapters can be purchased with the token.**

_• How is the token being distributed? Are you conducting an airdrop?_ **We did a presale on Pinksale. Most of the tokens have already been distributed but airdrops will follow for NFT holders once we start our minting event.**

_• Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?_ **Yes at presale on Pinksale.finance**

_• Is the token listed on a centralized/decentralized exchange?_ **Yes, we are listed on Pancakeswap and liquidity is locked.**

_• Is a Smart Contract audit completed? Where can we find this information?_ **We have a Certik audit already in place with very good results. The audit can be found here: [https://www.certik.com/projects/astroshit](https://www.certik.com/projects/astroshit)**

**Comment by christianzichichi** [comment]
@Cryptocool1  just for my understanding, as I would like to develop a token myself. this token has 1500 holders and below 10000 tx. How does it respect TW requirements and acceptance criteria? How does the review process work? Thanks

**Comment by cryptomanz** [comment]
As per our policy, brand new tokens are not included, there is a minimum requirement of 5,000 holder addresses and 10,000 transactions, in order to filter out scam tokens.
See the criteria at : https://developer.trustwallet.com/assets/requirements .

**Comment by cryptomanz** [comment]
Please come back to us when all criteria are met.
When creating a new PR make sure to mention this PR, so that we can see that fee has been paid already here.

**Pull request closed without merging**
