### PR TITLE
Add StakeStack Validator for Luna Classic

### PR DESCRIPTION
**Pull request by stakestack**

### CODE REVIEW

**Comment by stakestack** [comment]
I don't understand, do I have to pay for you to accept this PR?

**Comment by Cryptocool1** [comment]
> I don't understand, do I have to pay for you to accept this PR?

yes, you should pay the fee

**Comment by stakestack** [comment]
ok but here https://developer.trustwallet.com/assets/pr-fee you don't talk about a fee for being a validator on your platform. 

"Trust Wallet supports an insane number of tokens and coins. We are committed to supporting the tokens used by our users. But supporting so many assets has a high cost, in terms of running the infrastructure, ensuring continuous integrations, handling a massive number of requests to the assets info, etc. A lot of spam/scam coins also find us.
We have introduced this crypto contribution in order to filter requests, so we have more time to handle genuine ones."

You only talk about new tokens and coins, validators are not described here.

Can you please add StakeStack as a validator please?
Thanks

**Comment by stakestack** [comment]
We are on Terra Station and we are already verified as an official validator, thanks

**Comment by Cryptocool1** [comment]
> ok but here https://developer.trustwallet.com/assets/pr-fee you don't talk about a fee for being a validator on your platform.
> 
> "Trust Wallet supports an insane number of tokens and coins. We are committed to supporting the tokens used by our users. But supporting so many assets has a high cost, in terms of running the infrastructure, ensuring continuous integrations, handling a massive number of requests to the assets info, etc. A lot of spam/scam coins also find us. We have introduced this crypto contribution in order to filter requests, so we have more time to handle genuine ones."
> 
> You only talk about new tokens and coins, validators are not described here.
> 
> Can you please add StakeStack as a validator please? Thanks

hello, as I said above the fee is required for adding the validators. Each PR requires the fee.

**Pull request closed without merging**
