### PR TITLE
Add TianYu Coin (BEP20)

### PR DESCRIPTION
**Pull request by ghost**
Adding info for BEP20 token 'TianYu Coin'.

PR created by <a href="https://assets.trustwallet.com">TW Assets Management</a>

### CODE REVIEW

**Comment by cryptomanz** [comment]
As per our policy, brand new tokens are not included, there is a minimum requirement of 5000 holder addresses and 10000 transactions, in order to filter out scam tokens.
See the criteria at (mentioned in the first message by the bot): https://community.trustwallet.com/t/how-to-submit-a-token-logo/3863).

**Comment by pizzaisart** [comment]
Hi,

Thank you for reviewing our submission, we understand that there is a minimum requirement of 5000 holders, but due to staking, the holders appear will not be accurate. We have over 10K+ transfer. Please review our submission again.

Best Regards,
Tianyu Team

**Comment by cryptomanz** [comment]
You need to follow the rules for adding token:
- 5000 holders and 10000 transactions 
Screenshot 2021-09-13 at 01 58 42

**Comment by Cryptocool1** [comment]
please come back when all criteria are met. make sure to mention this PR so the fee can be reused

**Pull request closed without merging**
