### PR TITLE
Add TC token logo and info #13652

### PR DESCRIPTION
**Pull request by Tayfuntaner**
The smart contract audit is complete.

https://github.com/TTCOIN-TC/tc/blob/main/Smart-Contract-Documentation/Smart%20Contract%20Audit%20Report.pdf

### CODE REVIEW

**Comment by Tayfuntaner** [comment]
#13652 We made the payments, the PR was closed because the necessary document was missing, now that document has been prepared, please check again

Closed PR: https://github.com/trustwallet/assets/pull/13652

Reopened PR: https://github.com/trustwallet/assets/pull/14020

Smart contract control document is ready. we have completed the missing document

**Comment by cryptomanz** [comment]
Hello,
Can you please add links to your PR?
Example:
{   
     "name": "TTCOIN",
     "website": "https://ttcoin.info",
     "description": "TTcoin is designed for use in TTcoin brands and organizations.",
     "explorer": "https://tronscan.io/#/token20/TCMwzYUUCxLkTNpXjkYSBgXgqXwt7KJ82y",
     "type": "TRC20",
     "symbol": "TC",
     "decimals": 4,
     "status": "active",
     "id": "TCMwzYUUCxLkTNpXjkYSBgXgqXwt7KJ82y",
     "links": [
         {
             "name": "coinmarketcap",
             "url": ""
         },
         {
             "name": "twitter",
             "url": ""
         },
         {
             "name": "telegram",
             "url": ""
         },
         {
             "name": "medium",
             "url": ""
         },
         {
             "name": "discord",
             "url": ""
         }
     ]
     }

**Comment by Tayfuntaner** [comment]
> Hello, Can you please add links to your PR? Example: { "name": "TTCOIN", "website": "https://ttcoin.info", "description": "TTcoin is designed for use in TTcoin brands and organizations.", "explorer": "https://tronscan.io/#/token20/TCMwzYUUCxLkTNpXjkYSBgXgqXwt7KJ82y", "type": "TRC20", "symbol": "TC", "decimals": 4, "status": "active", "id": "TCMwzYUUCxLkTNpXjkYSBgXgqXwt7KJ82y", "links": [ { "name": "coinmarketcap", "url": "" }, { "name": "twitter", "url": "" }, { "name": "telegram", "url": "" }, { "name": "medium", "url": "" }, { "name": "discord", "url": "" } ] }

Should we add it to the info file or here?

**Comment by cryptomanz** [comment]
> > Hello, Can you please add links to your PR? Example: { "name": "TTCOIN", "website": "https://ttcoin.info", "description": "TTcoin is designed for use in TTcoin brands and organizations.", "explorer": "https://tronscan.io/#/token20/TCMwzYUUCxLkTNpXjkYSBgXgqXwt7KJ82y", "type": "TRC20", "symbol": "TC", "decimals": 4, "status": "active", "id": "TCMwzYUUCxLkTNpXjkYSBgXgqXwt7KJ82y", "links": [ { "name": "coinmarketcap", "url": "" }, { "name": "twitter", "url": "" }, { "name": "telegram", "url": "" }, { "name": "medium", "url": "" }, { "name": "discord", "url": "" } ] }
> 
> Should we add it to the info file or here?

You need added links in info json file

**Comment by Tayfuntaner** [comment]
> > > Hello, Can you please add links to your PR? Example: { "name": "TTCOIN", "website": "https://ttcoin.info", "description": "TTcoin is designed for use in TTcoin brands and organizations.", "explorer": "https://tronscan.io/#/token20/TCMwzYUUCxLkTNpXjkYSBgXgqXwt7KJ82y", "type": "TRC20", "symbol": "TC", "decimals": 4, "status": "active", "id": "TCMwzYUUCxLkTNpXjkYSBgXgqXwt7KJ82y", "links": [ { "name": "coinmarketcap", "url": "" }, { "name": "twitter", "url": "" }, { "name": "telegram", "url": "" }, { "name": "medium", "url": "" }, { "name": "discord", "url": "" } ] }
> > 
> > 
> > Should we add it to the info file or here?
> 
> You need add links in info json file

Okey, We added the links

**Comment by Tayfuntaner** [comment]
> > > Hello, Can you please add links to your PR? Example: { "name": "TTCOIN", "website": "https://ttcoin.info", "description": "TTcoin is designed for use in TTcoin brands and organizations.", "explorer": "https://tronscan.io/#/token20/TCMwzYUUCxLkTNpXjkYSBgXgqXwt7KJ82y", "type": "TRC20", "symbol": "TC", "decimals": 4, "status": "active", "id": "TCMwzYUUCxLkTNpXjkYSBgXgqXwt7KJ82y", "links": [ { "name": "coinmarketcap", "url": "" }, { "name": "twitter", "url": "" }, { "name": "telegram", "url": "" }, { "name": "medium", "url": "" }, { "name": "discord", "url": "" } ] }
> > 
> > 
> > Should we add it to the info file or here?
> 
> You need add links in info json file

okey

**Pull request merged**
