### PR TITLE
ADD AQUA TOKEN TO TRUST WALLET

### PR DESCRIPTION
**Pull request by ash-greninja-poke**
This PR is being closed due to inactivity. If you wish to continue, please have us reopen the PR before sending your payment, or just create a new one.
Do NOT send payments for closed PR, as the fee may by lost!
  (48 vs. 48 hrs)

### CODE REVIEW

**Comment by ash-greninja-poke** [comment]
we have over $25m locked.
And we are also listed on coinmarketcap you can check this link.
https://coinmarketcap.com/currencies/planet-finance/

We have also been audited by Halborn. Please see the audit here: https://github.com/HalbornSecurity/PublicReports/blob/master/Solidity%20Smart%20Contract%20Audits/Planet_Finance_Smart_Contract_Security_Audit_Halborn_v1_1.pdf"

**Comment by ash-greninja-poke** [comment]
We are willing to pay 3BNB.

**Comment by ash-greninja-poke** [comment]
We’re a real community with over $25 million in TVL and $5 million in liquidity. You told us before that we can just pay the processing fee. Can we do that please many of our users, use trust wallet and are asking us for our token logo and info to be accurate in trust wallet.

**Comment by ash-greninja-poke** [comment]
For fee payment please drop a mail at admin@planetfinance.io.

**Comment by ash-greninja-poke** [comment]
Can you please confirm when we make the payment our token will be listed here for sure?

**Comment by Cryptocool1** [comment]
seems good.
awaiting for fee payment.

**Comment by ash-greninja-poke** [comment]
> Can you please confirm when we make the payment our token will be listed here for sure?

Would you please confirm this also?

**Pull request closed without merging**
