### PR TITLE
Add Pepe 2.0 (PEPE2.0) (ERC20)

### PR DESCRIPTION
**Pull request by pepe2coineth**
Adding info for ERC20 token 'Pepe 2.0 (PEPE2.0)'.

PR created by <a href="https://assets.trustwallet.com">TW Assets Management</a>

### CODE REVIEW

**Comment by pepe2coineth** [comment]
Hello, 
Pepe 2.0 has been migrated to a new contract.

OLD CA:
0xfb66321d7c674995dfcc2cb67a30bc978dc862ad

New (Current) CA:
0x0305f515fa978cf87226cf8A9776D25bcfb2Cc0B

Please check multiple public announcements on our official Twitter account about the migration and new CA.
https://x.com/pepe2coineth/status/1745668126753112567?s=20
https://x.com/pepe2coineth/status/1745295843052187980?s=20
https://x.com/gate_io/status/1742795504642056581?s=20
https://x.com/pepe2coineth/status/1742690863782793354?s=20

Here is a link for the current contract audit:
https://app.solidproof.io/projects/pepe20

**Comment by pepe2coineth** [comment]
Hello, 
Should we proceed with payment?

**Comment by pepe2coineth** [comment]
Hello 
@cryptomanz1 @Cryptocool1 
Should we proceed with payment?

**Comment by pepe2coineth** [comment]
@cryptomanz1 
Hello sir, 
is it possible to remove all info from the old CA: 0xfb66321D7C674995dFcC2cb67A30bC978dc862AD


and only keep the new recent one: ERC20 0x0305f515fa978cf87226cf8A9776D25bcfb2Cc0B

All the best.

**Comment by mohammadkanani** [comment]
I have sent pepe2 tokens for migration but my tokens have not been returned to me yet

**Comment by pepe2coineth** [comment]
> @cryptomanz1 Hello sir, is it possible to remove all info from the old CA: 0xfb66321D7C674995dFcC2cb67A30bC978dc862AD
> 
> and only keep the new recent one: ERC20 0x0305f515fa978cf87226cf8A9776D25bcfb2Cc0B
> 
> All the best.

Hello @cryptomanz1 
Sorry for the disturbance. 
We need your support, please. 
The old contract address still available and shown on TW, and the new contract address not bulling the price from CMC. 
it's highly appreciated if you completely delete/remove/deactivate the log, social info, and CMC link from the old asset "old contract" and only keep the new recent contract 0x0305f515fa978cf87226cf8A9776D25bcfb2Cc0B


https://coinmarketcap.com/currencies/pepe-2-0/
https://etherscan.io/token/0x0305f515fa978cf87226cf8a9776d25bcfb2cc0b
CMC- CA

Thank you in advance. 
Pepe2.0 Team

**Comment by pepe2coineth** [comment]
> > @cryptomanz1 Hello sir, is it possible to remove all info from the old CA: 0xfb66321D7C674995dFcC2cb67A30bC978dc862AD
> > and only keep the new recent one: ERC20 0x0305f515fa978cf87226cf8A9776D25bcfb2Cc0B
> > All the best.
> 
> Hello @cryptomanz1 Sorry for the disturbance. We need your support, please. The old contract address still available and shown on TW, and the new contract address not bulling the price from CMC. it's highly appreciated if you completely delete/remove/deactivate the log, social info, and CMC link from the old asset "old contract" and only keep the new recent contract 0x0305f515fa978cf87226cf8A9776D25bcfb2Cc0B
> 
> https://coinmarketcap.com/currencies/pepe-2-0/ https://etherscan.io/token/0x0305f515fa978cf87226cf8a9776d25bcfb2cc0b CMC- CA
> 
> Thank you in advance. Pepe2.0 Team

TW-2
TW-1

**Comment by pepe2coineth** [comment]
Hello, 
@cryptomanz1 
Any update on our case? The price of the new CA is still not updated on Trust Wallet.

**Comment by mohammadkanani** [comment]
Hello, according to the attached photo, my tokens have not been returned to the immigration address I mentioned.

    On Thursday, January 18, 2024 at 02:39:34 AM GMT+3:30, Pepe 2.0 #PEPE2 ***@***.***> wrote:  
 
 




@cryptomanz1 Hello sir, is it possible to remove all info from the old CA: 0xfb66321D7C674995dFcC2cb67A30bC978dc862AD
and only keep the new recent one: ERC20 0x0305f515fa978cf87226cf8A9776D25bcfb2Cc0B
All the best.


Hello @cryptomanz1 Sorry for the disturbance. We need your support, please. The old contract address still available and shown on TW, and the new contract address not bulling the price from CMC. it's highly appreciated if you completely delete/remove/deactivate the log, social info, and CMC link from the old asset "old contract" and only keep the new recent contract 0x0305f515fa978cf87226cf8A9776D25bcfb2Cc0B

https://coinmarketcap.com/currencies/pepe-2-0/ https://etherscan.io/token/0x0305f515fa978cf87226cf8a9776d25bcfb2cc0b 

Thank you in advance. Pepe2.0 Team


TW-2.jpg (view on web)
TW-1.jpg (view on web)

**Comment by pepe2coineth** [comment]
Hello @cryptomanz1 @Cryptocool1 .
We need your support, please. The old contract address still available and shown on TW, and the new contract address not bulling the price from CMC. it's highly appreciated if you completely delete/remove/deactivate the log, social info, and CMC link from the old asset "old contract" and only keep the new recent contract 0x0305f515fa978cf87226cf8A9776D25bcfb2Cc0B

**Comment by mohammadkanani** [comment]
Return the tokens I sent you
    On Thursday, February 8, 2024 at 11:20:28 PM GMT+3:30, Pepe 2.0 #PEPE2 ***@***.***> wrote:  
 
 


Hello @cryptomanz1 @Cryptocool1 .
We need your support, please. The old contract address still available and shown on TW, and the new contract address not bulling the price from CMC. it's highly appreciated if you completely delete/remove/deactivate the log, social info, and CMC link from the old asset "old contract" and only keep the new recent contract 0x0305f515fa978cf87226cf8A9776D25bcfb2Cc0B

**Comment by pepe2coineth** [comment]
Hello @cryptomanz1 @Cryptocool1 .
We need your support, please. The old contract address still available and shown on TW, and the new contract address not bulling the price from CMC. it's highly appreciated if you completely delete/remove/deactivate the log, social info, and CMC link from the old asset "old contract" and only keep the new recent contract 0x0305f515fa978cf87226cf8A9776D25bcfb2Cc0B

**Pull request merged**
