### PR TITLE
Remove Streamix TRC20 logo and add ERC20 Logo

### PR DESCRIPTION
**Pull request by tokyo786**
Please remove streamix TRC20 token, it is an ERC20 token now.

The TRC20 token to be removed:
https://tronscan.org/#/token20/TFPAuuQym78giRve6iHTf4y7dZJxAkkrUa

Below is ERC20 info:
https://etherscan.io/token/0xB0BFB1E2F72511cF8b4D004852E2054d7b9a76e1

whitepaper: https://streamix.io/Whitepaper-MIXS-PDF.pdf
website: https://streamix.io/

Social Media Links:
https://twitter.com/streamixio
https://medium.com/@streamix
https://www.linkedin.com/company/streamixio
https://www.facebook.com/streamixio/
https://www.instagram.com/streamixio/

The information can be verified in the pinned message in their public telegram:
https://t.me/Streamix

### CODE REVIEW

**Comment by tokyo786** [comment]
@zachzwei and @catenocrypt this pull request is still in progress and the fee is paid, we'd like to save your time in reviewing so we marked it as a draft for now, we'll open it for review again once when we're ready, till then thank you very much for your patience.

Best Regards.

**Comment by tokyo786** [comment]
@catenocrypt @zachzwei please review the changes and let us know if you have any comments or questions about it. A quick response will be highly appreciated.

Thank you!

**Comment by catenocrypt** [comment]
This PR for removing Streamx TRC20 token looks OK.
Just to clarify: you want to remove logo+info about old Streamx TRC20 token, because new Streamx token is now on Ethereum?  Are you considering adding it?

**Comment by tokyo786** [comment]
> This PR for removing Streamx TRC20 token looks OK.
> Just to clarify: you want to remove logo+info about old Streamx TRC20 token, because new Streamx token is now on Ethereum? Are you considering adding it?

Yes we're considering adding it, we can make the relevant changes in the pull request if it can be approved. About adding, can you let us know if the ERC20 version https://etherscan.io/token/0xB0BFB1E2F72511cF8b4D004852E2054d7b9a76e1 will be approved to be added, or changed from TRC20 to ERC20 ?

**Comment by catenocrypt** [comment]
Considering that TRC20 version was already present, yes, we can add the new ERC20 version, despite the fact that both old and new have minimal usage so far.
Just add the logo.png and info.json under the right folder: 
`blockchains/etehreum/assets/0xB0BFB1E2F72511cF8b4D004852E2054d7b9a76e1/`
Do not worry about allowlist/denylist, those will be updated automatically.

**Comment by tokyo786** [comment]
> Considering that TRC20 version was already present, yes, we can add the new ERC20 version, despite the fact that both old and new have minimal usage so far.
> Just add the logo.png and info.json under the right folder:
> `blockchains/etehreum/assets/0xB0BFB1E2F72511cF8b4D004852E2054d7b9a76e1/`
> Do not worry about allowlist/denylist, those will be updated automatically.

Thank you! Just 5 mins.

**Comment by tokyo786** [comment]
@catenocrypt please review and merge this soon. Thank you!

**Comment by tokyo786** [comment]
@catenocrypt this PR is ready for review. Thank you!

**Pull request merged**
