### PR TITLE
Adding Sekuritance (SKRT) ERC20 Token

### PR DESCRIPTION
**Pull request by sekuritancedev**
Adding Sekuritance (SKRT) ERC20 Token

### CODE REVIEW

**Comment by sekuritancedev** [comment]
There seemed to be a wrong folder name information with extra space and extra text at the back

**Comment by sekuritancedev** [comment]
should we amend anything on our end?

**Comment by sekuritancedev** [comment]
cannot understand what is happening! please assist

**Comment by sekuritancedev** [comment]
Not understanding what we are doing wrong and why the test is failing:
XXX 'Folder structure for chain ethereum (ethereum fork)':  1 errors
   XXX   'Expect asset at path /home/runner/work/assets/assets/blockchains/ethereum/assets/0x887168120cb89fb06f3e74dc4af20d67df0977f6 in checksum: '0x887168120cb89Fb06F3E74Dc4AF20D67dF0977f6''

**Comment by sekuritancedev** [comment]
can someone please assist? @catenocrypt @zachzwei

**Comment by catenocrypt** [comment]
@sekuritancedev , the folder corresponding to the token ID should be in 'checksum format'.  Currently it is all smallcase:
`blockchains/ethereum/assets/0x887168120cb89fb06f3e74dc4af20d67df0977f6`
but should be:
`0x887168120cb89Fb06F3E74Dc4AF20D67dF0977f6`
You need to rename, but as it changes only casing, it may be tricky; two renames may be needed.

**Comment by sekuritancedev** [comment]
thank you - i figured it out a few mins ago

**Comment by sekuritancedev** [comment]
do we need to action anything else on our end now?

**Comment by catenocrypt** [comment]
I can see you just managed to do the rename :)

**Comment by sekuritancedev** [comment]
for some reason the github desktop was failing cause the path was too long so had to use the web version - and the web version was adding weird spaces in the folder names!

**Comment by catenocrypt** [comment]
Submission is technically correct, but there is a problem with low circulation.  Current circulation is basically non-existent -- only 1 holder addresses.
https://etherscan.io/token/0x887168120cb89Fb06F3E74Dc4AF20D67dF0977f6

As per our policy, brand new tokens are not included, there is a minimum requirement of 2500 holder addresses and 5000 transactions, in order to filter out scam tokens.
See the criteria at (mentioned in the first message by the bot): https://community.trustwallet.com/t/how-to-submit-a-token-logo/3863).
Multi-chain and staking tokens may get special treatment, let us know if this is the case.

Please comment.

**Comment by sekuritancedev** [comment]
Hi - yes I saw that and am aware of it. our corporate site is www.sekuritance.com so definitely not a scam token but we have not yet launched it to our merchants and customers let alone the public yet. We are preparing the path so that when we do distribute, everything will check out legitimately and we won't be ahead of the curve. Is there any declaration that I can get the directors and shareholders to sign as a guarantee?

**Comment by sekuritancedev** [comment]
The project is a RegTech and RiskTech solution ecosystem - We are not yet multi-chain but our partners who will get the tokens will also be staked for long periods if that is what you mean - but this is a utility token with a very clear utilisation in the ecosystem

**Comment by catenocrypt** [comment]
Keeping on hold.

**Comment by vikmeup** [comment]
Feel free to re-open pull request once you meet those requirements.

**Comment by sekuritancedev** [comment]
Can we reopen this now please?

Best Regards,

Jonathan C. Bowman

**Pull request merged**
