### PR TITLE
add coil logo

### PR DESCRIPTION
**Pull request by cryptoadnetwork**
https://github.com/trustwallet/assets/commit/feb9e130b83797576260166d2412e6cb0955ad98

### CODE REVIEW

**Comment by catenocrypt** [comment]
As per our updated policy, brand new tokens are not included, there is a minimum requirement of 100 holder addresses and 500 transactions, in order to filter out scam tokens.
See https://community.trustwallet.com/t/how-to-submit-a-token-logo/3863#how-to-get-approved
This token does not match the criteria, putting on hold for now.

**Comment by cryptoadnetwork** [comment]
Hello
I was asked to add this token - COIL-
https://etherscan.io/token/0x3936ad01cf109a36489d93cabda11cf062fd3d48
because as an investor , I have already added my token
https://uniswap.info/token/0x1bdcfe02c54362ce935d13d5314ac76e0af20ab7 in
March
I can send you this token informations below , they also more than 100
holders and 500 transactions - you check that in the first link of
etherscan- plus than a litepaper https://coilcrypto.com/lite-paper/

*USEFUL LINKS:* Website: https://coilcrypto.com/ Twitter:
https://twitter.com/CoilCrypto GitHub: https://github.com/Coil-Official
Telegram: https://t.me/coilcrypto Telegram Announcements :
https://t.me/coilcrypto_ann
Discord   https://discord.com/invite/q7x8SjP

**Comment by cryptoadnetwork** [comment]
Hello
I was asked to add this token - COIL-
https://etherscan.io/token/0x3936ad01cf109a36489d93cabda11cf062fd3d48
because I am an investor there and I have already added my token
https://uniswap.info/token/0x1bdcfe02c54362ce935d13d5314ac76e0af20ab7 in
March
I can send you the COIL token informations below , they also have more than
100 holders and 500 transactions - you can check that in the first link of
etherscan
<https://coilcrypto.com/lite-paper/>
*USEFUL LINKS:* Website: https://coilcrypto.com/ Twitter:
https://twitter.com/CoilCrypto GitHub: https://github.com/Coil-Official
Telegram: https://t.me/coilcrypto Telegram Announcements :
https://t.me/coilcrypto_ann
*Discord   *https://discord.com/invite/q7x8SjP
* litepaper >   **https://coilcrypto.com/lite-paper/
<https://coilcrypto.com/lite-paper/> *explorer >
https://etherscan.io/token/0x3936ad01cf109a36489d93cabda11cf062fd3d48



They are in need of the logo in uniswap >
https://uniswap.info/token/0x3936ad01cf109a36489d93cabda11cf062fd3d48
I will have to pay them back if you refuse my request

**Comment by catenocrypt** [comment]
Thanks for the clarification.
One token -- COIL -- matches our criteria
https://etherscan.io/token/0x3936ad01cf109a36489d93cabda11cf062fd3d48
the other one -- HELL -- does not
https://etherscan.io/token/0x1bdcFe02C54362cE935D13D5314ac76e0Af20AB7

Shall we add COIL only?

**Comment by cryptoadnetwork** [comment]
Hello
Yes add COIL only....the other -HELL- is my token and already added
thank you for your reply

**Comment by cryptoadnetwork** [comment]
Hello
When the COIL logo will be added?
0x3936ad01cf109a36489d93cabda11cf062fd3d48
https://coinmarketcap.com/currencies/coil/

**Pull request merged**
