### PR TITLE
Add AFFINITY (BEP20)

### PR DESCRIPTION
**Pull request by Azacora**
Adding info for BEP20 token 'AFFINITY'.

Already paid: PR: https://github.com/trustwallet/assets/pull/15337

PR created by <a href="https://assets.trustwallet.com">TW Assets Management</a>

### CODE REVIEW

**Comment by Cryptocool1** [comment]
• Is a Smart Contract audit completed? Where can we find this information?

**Comment by Azacora** [comment]
> • Is a Smart Contract audit completed? Where can we find this information?

Yes, here is the link, https://bitriseaudits.com/project/12

**Comment by ramsty** [comment]
Hi,
Please follow the rules for adding token, your logo should be a full screen
Example:
https://community.trustwallet.com/t/how-to-submit-a-token-logo/3863
137116359-c2bb87b7-239a-4c8d-b54e-4a679c621186

**Comment by Azacora** [comment]
logo 2
logo
 
Will one of these work?

**Comment by Cryptocool1** [comment]
the image  should be full size

**Comment by Azacora** [comment]
> the image should be full size
logo

**Pull request merged**
