### PR TITLE
Add Anti Token (BEP20)

### PR DESCRIPTION
**Pull request by emojidaobsc**
Adding info for BEP20 token 'Anti Token'.

PR created by <a href="https://assets.trustwallet.com">TW Assets Management</a>

### CODE REVIEW

**Comment by emojidaobsc** [comment]
merge ： #20349 
TX HASH : 4A9787BBF317E3C21FBAE49D22B3CFB095EA11EC9664E62C6EC824D6C4A6AB18

**Comment by emojidaobsc** [comment]
> ### PR Summary
> Files OK: 4 Tokens in PR: (2)
> 
> * **BEP20** 0x7CcfdA7BF90B8446170f0c8c6a6F356BE8A9c6Fc
> * **BEP20** 0x7ccfda7bf90b8446170f0c8c6a6f356be8a9c6fc
> 
> **Token BEP20 - 0x7CcfdA7BF90B8446170f0c8c6a6F356BE8A9c6Fc**: Symbol: **ANTI** decimals: 6 Links: [Logo](https://raw.githubusercontent.com/emojidaobsc/assets/br0510-204151/blockchains/smartchain/assets/0x7CcfdA7BF90B8446170f0c8c6a6F356BE8A9c6Fc/logo.png) [Info](https://raw.githubusercontent.com/emojidaobsc/assets/br0510-204151/blockchains/smartchain/assets/0x7CcfdA7BF90B8446170f0c8c6a6F356BE8A9c6Fc/info.json) [Website](https://www.anti.bet) [Explorer](https://bscscan.com/token/0x7CcfdA7BF90B8446170f0c8c6a6F356BE8A9c6Fc) Tags: defi Token check error: ❌ number of holders not checked: please, check it manually
> 
> 
> 
> **Token BEP20 - 0x7ccfda7bf90b8446170f0c8c6a6f356be8a9c6fc**: Failed to get info.json content: failed to unmarshal json: invalid character ':' after top-level value (https://raw.githubusercontent.com/emojidaobsc/assets/br0510-204151/blockchains/smartchain/assets/0x7ccfda7bf90b8446170f0c8c6a6f356be8a9c6fc/info.json)

merge ： https://github.com/trustwallet/assets/pull/20349 
TX HASH : 4A9787BBF317E3C21FBAE49D22B3CFB095EA11EC9664E62C6EC824D6C4A6AB18

**Comment by Cryptocool1** [comment]
please come back to us when you will be ready to answer the questions. Make sure to mention this PR so the fee can be reused

**Comment by emojidaobsc** [comment]
• This token is to allow users to get better circulation in the application, and users of TrustWallet can get airdropped tokens.
•Token 100% added liquidity
•No presale，No ICO
• listed on pancakeV2 exchange
• Audit：https://skyharbor.certik.com/shared-report/f927f3b5-b794-4029-a920-748656433024
• Holders：10008

**Pull request closed without merging**
