### PR TITLE
Add YOKcoin (YOK) logo

### PR DESCRIPTION
**Pull request by rsrosabio**
This PR is being closed due to inactivity. If you wish to continue, please reopen the PR before sending your payment.
Do NOT send payments for closed PR, as the fee may by lost!
  (60 vs. 60 hrs)

### CODE REVIEW

**Comment by rsrosabio** [comment]
Do we really need this to update the logo?

*Minimum 500 token holders and 1,000 transactions.*

**Comment by catenocrypt** [comment]
The token explorer page and the logo shows First Energy Token, **FET**.  Why did you mention YOK in title?  Please clarify.

https://etherscan.io/token/0x296b3Fc8e3CC768F834152586e5Ad708BFE8F163

**Comment by rsrosabio** [comment]
> The token explorer page and the logo shows First Energy Token, **FET**. Why did you mention YOK in title? Please clarify.
> 
> https://etherscan.io/token/0x296b3Fc8e3CC768F834152586e5Ad708BFE8F163

Here it is the right token explorer:

https://etherscan.io/token/0x05fcc72cfb4150abae415c885f7a433ff523296f

I just saw the new acceptance criteria . We have a total of 200 token holders. Can we update anyway?

**Comment by catenocrypt** [comment]
But this contract address does not match the one in your logo!
I suggest creating a new PR with the correct token address and logo!

image

**Comment by rsrosabio** [comment]
> But this contract address does not match the one in your logo!
> I suggest creating a new PR with the correct token address and logo!
> 
> image

Okay! I will create a new PR!
But we have a total of 200 token holders for now. 
According to the new acceptance criteria we need a minimum 500 token holders. 
Can we update anyway?

**Comment by rsrosabio** [comment]
> > But this contract address does not match the one in your logo!
> > I suggest creating a new PR with the correct token address and logo!
> > image
> 
> Okay! I will create a new PR!
> But we have a total of 200 token holders for now.
> According to the new acceptance criteria we need a minimum 500 token holders.
> Can we update anyway?

Hi, Sir! I need to clarify this before creating a new PR!
According to the new acceptance criteria we need a minimum 500 token holders but we have a total of 200 token holders for now.
After I pay the fee will the logo be updated anyway?

**Pull request closed without merging**
