### PR TITLE
Add Community Token (BEP20)

### PR DESCRIPTION
**Pull request by BohdanCOMMET**
Adding info for BEP20 token 'Community Token'.

PR created by <a href="https://assets.trustwallet.com">TW Assets Management</a>

### CODE REVIEW

**Comment by cryptomanz** [comment]
• What is the purpose of this token? How will it benefit Trust Wallet users?
 • How is the token being distributed? Are you conducting an airdrop?
 • Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?
 • Is the token listed on a centralized/decentralized exchange?
 • Is a Smart Contract audit completed? Where can we find this information?

**Comment by BohdanCOMMET** [comment]
• What is the purpose of this token? How will it benefit Trust Wallet users?
We are fast evolving  Metaverse project with top trending on dextools, already listed on coinmarketcap and coingeko. Trust wallet users will be interested to get into our project. Holders who already with our project will be happy to see token info and price
• How is the token being distributed? Are you conducting an airdrop?
Fair Launch
• Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?
None
• Is the token listed on a centralized/decentralized exchange?
Dex pankaceswap. https://pancakeswap.finance/info/token/0x45b239cc0a760d1afd276b749141c7e404844ee6
• Is a Smart Contract audit completed? Where can we find this information?
https://github.com/TechRate/Smart-Contract-Audits/blob/main/January/Community%20Token%20Full%20Smart%20Contract%20Security%20Audit.pdf

**Comment by cryptomanz** [comment]
As per our policy, brand new tokens are not included, there is a minimum requirement of 10,000 holder addresses and 20,000 transactions, in order to filter out scam tokens.
See the criteria at : https://developer.trustwallet.com/assets/requirements .

**Comment by cryptomanz** [comment]
Please come back to us when all criteria are met.
When creating a new PR make sure to mention this PR, so that we can see that fee has been paid already here.

**Pull request closed without merging**
