### PR TITLE
Adding the RobotBulls token

### PR DESCRIPTION
**Pull request by robinkbr**
This request is to add the RobotBulls Token to Trust Wallet. RobotBulls is a platform that creates crypto trading robots, the RobotBulls Token aims to help decentralizing these trading robots and implementing a voting system to the decision of the RobotBulls community for the trading robots.
 
The proxy contract address can be found at: https://basescan.org/address/0x7eCc65A5E734a8bcAf24eEA0AC9C7cfE6355bc30
The implementation contract address can be found at: https://basescan.org/address/0xc767339f3c99ed14135c545b2919637e0902007b

The code is open source and visible on basescan.org.

### CODE REVIEW

**Comment by robinkbr** [comment]
The logo.png file has been added to the correct directory.

**Comment by cryptomanz1** [comment]
• What is the purpose of this token? How will it benefit Trust Wallet users?
 • How is the token being distributed? Are you conducting an airdrop?
 • Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?
 • Is the token listed on a centralized/decentralized exchange?
 • Is a Smart Contract audit completed? Where can we find this information?

**Comment by robinkbr** [comment]
Purpose and Benefits to Trust Wallet Users:
The RobotBulls Token aims to decentralize AI trading algorithms. This means the token will be used to manage and operate a platform that allows users to share and benefit from AI-driven trading strategies in a decentralized manner. RobotBulls already has a track record of creating trading robots and smart contracts for 4 years. Trust Wallet users, and other cryptocurrency enthusiasts, will benefit from this by having the ability to participate in an AI-powered investment approach, potentially leading to more efficient and effective trading outcomes.
Token Distribution and Airdrop:
The RobotBulls team is conducting an airdrop, as part of their token distribution strategy, where they plan to give out 20% of the total token supply to the community. 
Initial Coin Offering (ICO) and Token Presale:
There is no presale all the people can purchase the token in the same time.
Exchange Listings:
The token is not listed on centralized exchanges. However, it's on uniswap. 
The smart contract audit is not completed yet but it should be within the next month.
For the token allocation:
Token Address: 0x7eCc65A5E734a8bcAf24eEA0AC9C7cfE6355bc30
Implementation Address: 0xc767339f3c99ed14135c545b2919637e0902007b
These addresses indicate are on the base network
Allocation and Distribution:
Token Allocation:
Airdrop: 30%
Pools: 30%
Team and Founders: 5%
Reserve: 20%
Development: 5%
Marketing: 10%

**Comment by cryptomanz1** [comment]
We require smart contract audit from reputable companies. Feel free to come back to us once audit is done. Make sure to mention this PR so the fee can be reused

**Comment by Mofidzol** [comment]
مفید

در تاریخ جمعه ۲۶ آوریل ۲۰۲۴،‏ ۲۲:۲۱ Nazar ***@***.***> نوشت:

**Comment by robinkbr** [comment]
If get the audit from CertiK does it work? Will we need sth else after the audit to get listed?

**Comment by Cryptocool1** [comment]
Yes, you can do Certik audit, you should also have more than 10k organic holders

**Comment by robinkbr** [comment]
Ok and if these two criteria are met we can be listed?

**Pull request closed without merging**
