### PR TITLE
Add LUCRO (BEP20)

### PR DESCRIPTION
**Pull request by Lucrotoken**
Adding info for BEP20 token 'LUCRO'.

PR created by <a href="https://assets.trustwallet.com">TW Assets Management</a>

### CODE REVIEW

**Comment by Cryptocool1** [comment]
• What is the purpose of this token? How will it benefit Trust Wallet users?
 • How is the token being distributed? Are you conducting an airdrop?
 • Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?
 • Is the token listed on a centralized/decentralized exchange?
 • Is a Smart Contract audit completed? Where can we find this information?

**Comment by Lucrotoken** [comment]
- LUCRO is a ecosystem token with various functions like trading,staking and nfts, the majority off our users use Trust Wallet.
- we did not conduct any airdrops
- we are listed on PancakeSwapV2
- https://www.certik.com/projects/lucro

**Comment by cryptomanz1** [comment]
Are you listed on CoinMarketCap?

**Comment by Lucrotoken** [comment]
Yes we are.

https://coinmarketcap.com/currencies/lucro/

**Pull request merged**
