### PR TITLE
Add KING FOREVER (BEP20)

### PR DESCRIPTION
**Pull request by KINGFOREVERBSC**
Adding info for BEP20 token 'KING FOREVER'.

PR created by <a href="https://assets.trustwallet.com">TW Assets Management</a>

### CODE REVIEW

**Comment by cryptomanz** [comment]
• What is the purpose of this token? How will it benefit Trust Wallet users?
 • How is the token being distributed? Are you conducting an airdrop?
 • Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?
 • Is the token listed on a centralized/decentralized exchange?
 • Is a Smart Contract audit completed? Where can we find this information?

**Comment by Kedimdevlyn** [comment]
https://www.coingecko.com/en/coins/king-forever

**Comment by Kedimdevlyn** [comment]
Audit : https://github.com/interfinetwork/smart-contract-audits/blob/main/KingForever_AuditReport_InterFi.pdf

**Comment by Kedimdevlyn** [comment]
image
 DEVELOPMENT MMORPG GAME METAVERSE, NFT PLATFORM

**Comment by Kedimdevlyn** [comment]
staking : https://www.stake.kingforevertoken.com/

image

**Comment by Kedimdevlyn** [comment]
https://www.pinksale.finance/#/launchpad/0x65D5abc3E4236cc80B3091B7090536634bad3253?chain=BSC

**Comment by Cryptocool1** [comment]
As per our policy, brand new tokens are not included, there is a minimum requirement of 10,000 holder addresses and 15,000 transactions, in order to filter out scam tokens.
See the criteria at : https://developer.trustwallet.com/assets/requirements .

**Comment by Cryptocool1** [comment]
please come back to us when all criteria are met. make sure to mention this PR so the fee can be reused

**Comment by Kedimdevlyn** [comment]
Hello  i am ready pay for trust logo , why this project 7k holders logo update ? https://bscscan.com/token/0x2456BBAD80BfAD346AecEa45fA38C81a6963132D

**Comment by Cryptocool1** [comment]
• What is the purpose of this token? How will it benefit Trust Wallet users?
• How is the token being distributed? Are you conducting an airdrop?
• Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?
• Is the token listed on a centralized/decentralized exchange?
• Is a Smart Contract audit completed? Where can we find this information?

**Comment by Kedimdevlyn** [comment]
• What is the purpose of this token? How will it benefit Trust Wallet users?
LP LOCKED 3 YEAR PROJECT LONG TERME  STAKING ,NFT ,MMORPG IN DEVLOPPEMNT 
https://www.stake.kingforevertoken.com/
Dapp in devloppement
NFT MARKET PLACE 
Listen to winner website radio ready, is ready we are developing the possibility of winning with the possibility of listening to the radio and also a mmorpg game over the next 3 years all the information on our website, we will also launch forever swap new token that will allow our community to buy from our swap and farm.

https://kingforevertoken.com/

RADIO / http://kingforeverradio.com/


• How is the token being distributed? Are you conducting an airdrop?
PRESALE , buy pancakeswap , air drop giveway staking
• Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?
https://www.pinksale.finance/#/launchpad/0x65D5abc3E4236cc80B3091B7090536634bad3253?chain=BSC
• Is the token listed on a centralized/decentralized exchange?
**decentralized** 
• Is a Smart Contract audit completed? Where can we find this information?
https://github.com/interfinetwork/smart-contract-audits/blob/main/KingForever_AuditReport_InterFi.pdf

**Comment by 406712774** [comment]
Si

**Comment by Cryptocool1** [comment]
your logo should be 256/256, please change

**Comment by Kedimdevlyn** [comment]
Design sans titre (1)


hello pls modifier par cela car nous avons des problem de la mise a jour de bsc scan et celui de trust walett

**Comment by Kedimdevlyn** [comment]
Design_sans_titre-removebg-preview

**Comment by Kedimdevlyn** [comment]
Hello pls modify by this as we have problem with the update of BSC Scan and that of Trust Walett new logo 
Design sans titre

**Comment by Kedimdevlyn** [comment]
OIG2-imageonline co-3972755 (1) (1)

**Comment by Kedimdevlyn** [comment]
https://kingforevertoken.com/assets/images/logo-trustwallet.png.ICO

**Comment by KINGFOREVERBSC** [comment]
logotrust

**Comment by Jstacy121** [comment]
Okay you just have to pay for the fee

Stacy L Johnson
Sent with Spark

**Pull request merged**
