### PR TITLE
HDL commit

### PR DESCRIPTION
**Pull request by headline-design**

### CODE REVIEW

**Review by mohammadjnoor — APPROVED** [review]
#hi

**Comment by headline-design** [comment]
> #hi

Payment coming soon.

**Comment by headline-design** [comment]
Payment sent.

**Comment by headline-design** [comment]
Additional info: 

CoinMarketCap - https://coinmarketcap.com/currencies/headline-inc

Users: 23,000
Transactions: 585,000

DEX listings: TinyMan, AlgoFi, PactFi, Humble

Institutional Custody Provider: Copper.co

**Comment by hewigovens** [comment]
Is `137594422` asset id? do you have explorer link? we haven't supported token on algorand yet

**Comment by covain** [comment]
@headline-design please update your fork with the recent changes from assets master. This should fix CI

**Comment by covain** [comment]
@headline-design please update your branch to the recent assets master. This should fix CI

**Comment by headline-design** [comment]
> @headline-design please update your branch to the recent assets master. This should fix CI

Updated.

**Comment by headline-design** [comment]
> @headline-design please upgrade one more time

Updated.

**Pull request merged**
