### PR TITLE
Please add SLVG on TrustWallet

### PR DESCRIPTION
**Pull request by soliditycdr**
Maximum PR age reached, auto-closing PR  (83 vs. 60 hrs)

### CODE REVIEW

**Comment by soliditycdr** [comment]
Hi, already paid the fee in 2000 TWT for 2168 Memo, here is the transaction details: https://explorer.binance.org/tx/E2199DBD54E619D87E9AE22F0102049849A3084D9867150283BACDF21491B7A9?fbclid=IwAR32h8WIaUvdeEznQO4G7STFa2BTGRK1e9UA8NJY2n1FX0kcX2yRZeGx3lI

paid-fee

**Comment by catenocrypt** [comment]
Payment verified, unclear why it was not picked up by bot.  Old payments are not considered after few days.
@kolya182 , can you handle?  Payment OK.

**Pull request closed without merging**
