### PR TITLE
Add MONETAS (BEP20)

### PR DESCRIPTION
**Pull request by monetas26**
Adding info for BEP20 token 'MONETAS'.

PR created by <a href="https://assets.trustwallet.com">TW Assets Management</a>

### CODE REVIEW

**Comment by monetas26** [comment]
Pls use this PR Against Old PR 10123

**Comment by monetas26** [comment]
> Pls use this PR Against Old PR 10123



> **PR Summary**
> File not allowed: info.json. Please revert it.
> File not allowed: logo.png. Please revert it.

logo

**Comment by cryptomanz** [comment]
Hello,
cannot find contract on your website
please check/add

**Comment by monetas26** [comment]
> **PR Summary**
> Files OK, 2Files in PR: 2
> Token in PR: BEP20 0xE440b9af0AE99174b3FAaB87174E31634D135f6d
> Symbol: **MNTG** decimals: 18
> Links: [Logo](https://raw.githubusercontent.com/monetas26/assets/br0616-165317/blockchains/smartchain/assets/0xE440b9af0AE99174b3FAaB87174E31634D135f6d/logo.png) [Info](https://raw.githubusercontent.com/monetas26/assets/br0616-165317/blockchains/smartchain/assets/0xE440b9af0AE99174b3FAaB87174E31634D135f6d/info.json) [Website](https://monetasglobal.com/) [Explorer](https://bscscan.com/token/0xE440b9af0AE99174b3FAaB87174E31634D135f6d) (check OK )
> 
> 



> Hello,
> cannot find contract on your website
> please check/add

it will be update within 24 Hrs.

**Comment by monetas26** [comment]
> > **PR Summary**
> > Files OK, 2Files in PR: 2
> > Token in PR: BEP20 0xE440b9af0AE99174b3FAaB87174E31634D135f6d
> > Symbol: **MNTG** decimals: 18
> > Links: [Logo](https://raw.githubusercontent.com/monetas26/assets/br0616-165317/blockchains/smartchain/assets/0xE440b9af0AE99174b3FAaB87174E31634D135f6d/logo.png) [Info](https://raw.githubusercontent.com/monetas26/assets/br0616-165317/blockchains/smartchain/assets/0xE440b9af0AE99174b3FAaB87174E31634D135f6d/info.json) [Website](https://monetasglobal.com/) [Explorer](https://bscscan.com/token/0xE440b9af0AE99174b3FAaB87174E31634D135f6d) (check OK )
> > 
> 
> > Hello,
> > cannot find contract on your website
> > please check/add
> 
> it will be update within 24 Hrs.

Hi My PR still open After 
Dry run & P R (CI) Check passed, Pls Merged, because our token logo not display in trustwallet yet now...

**Comment by cryptomanz** [comment]
> > > **PR Summary**
> > > Files OK, 2Files in PR: 2
> > > Token in PR: BEP20 0xE440b9af0AE99174b3FAaB87174E31634D135f6d
> > > Symbol: **MNTG** decimals: 18
> > > Links: [Logo](https://raw.githubusercontent.com/monetas26/assets/br0616-165317/blockchains/smartchain/assets/0xE440b9af0AE99174b3FAaB87174E31634D135f6d/logo.png) [Info](https://raw.githubusercontent.com/monetas26/assets/br0616-165317/blockchains/smartchain/assets/0xE440b9af0AE99174b3FAaB87174E31634D135f6d/info.json) [Website](https://monetasglobal.com/) [Explorer](https://bscscan.com/token/0xE440b9af0AE99174b3FAaB87174E31634D135f6d) (check OK )
> > > 
> > 
> > 
> > > Hello,
> > > cannot find contract on your website
> > > please check/add
> > 
> > 
> > it will be update within 24 Hrs.
> 
> Hi My PR still open After
> Dry run & P R (CI) Check passed, Pls Merged, because our token logo not display in trustwallet yet now...

hello,
did you update contract on your website?

**Comment by monetas26** [comment]
> > > > **PR Summary**
> > > > Files OK, 2Files in PR: 2
> > > > Token in PR: BEP20 0xE440b9af0AE99174b3FAaB87174E31634D135f6d
> > > > Symbol: **MNTG** decimals: 18
> > > > Links: [Logo](https://raw.githubusercontent.com/monetas26/assets/br0616-165317/blockchains/smartchain/assets/0xE440b9af0AE99174b3FAaB87174E31634D135f6d/logo.png) [Info](https://raw.githubusercontent.com/monetas26/assets/br0616-165317/blockchains/smartchain/assets/0xE440b9af0AE99174b3FAaB87174E31634D135f6d/info.json) [Website](https://monetasglobal.com/) [Explorer](https://bscscan.com/token/0xE440b9af0AE99174b3FAaB87174E31634D135f6d) (check OK )
> > > > 
> > > 
> > > 
> > > > Hello,
> > > > cannot find contract on your website
> > > > please check/add
> > > 
> > > 
> > > it will be update within 24 Hrs.
> > 
> > 
> > Hi My PR still open After
> > Dry run & P R (CI) Check passed, Pls Merged, because our token logo not display in trustwallet yet now...
> 
> hello,
> did you update contract on your website?

Yes 
You can cross verify also..

**Comment by monetas26** [comment]
> > > > > **PR Summary**
> > > > > Files OK, 2Files in PR: 2
> > > > > Token in PR: BEP20 0xE440b9af0AE99174b3FAaB87174E31634D135f6d
> > > > > Symbol: **MNTG** decimals: 18
> > > > > Links: [Logo](https://raw.githubusercontent.com/monetas26/assets/br0616-165317/blockchains/smartchain/assets/0xE440b9af0AE99174b3FAaB87174E31634D135f6d/logo.png) [Info](https://raw.githubusercontent.com/monetas26/assets/br0616-165317/blockchains/smartchain/assets/0xE440b9af0AE99174b3FAaB87174E31634D135f6d/info.json) [Website](https://monetasglobal.com/) [Explorer](https://bscscan.com/token/0xE440b9af0AE99174b3FAaB87174E31634D135f6d) (check OK )
> > > > > 
> > > > 
> > > > 
> > > > > Hello,
> > > > > cannot find contract on your website
> > > > > please check/add
> > > > 
> > > > 
> > > > it will be update within 24 Hrs.
> > > 
> > > 
> > > Hi My PR still open After
> > > Dry run & P R (CI) Check passed, Pls Merged, because our token logo not display in trustwallet yet now...
> > 
> > 
> > hello,
> > did you update contract on your website?
> 
> Yes
> You can cross verify also..

Thanks for Merging, but Logo still not display. Why

**Pull request merged**
