### PR TITLE
Add X AI (BEP20)

### PR DESCRIPTION
**Pull request by xai-cx**
Adding info for BEP20 token 'X AI'.

PR created by <a href="https://assets.trustwallet.com">TW Assets Management</a>

### CODE REVIEW

**Comment by Cryptocool1** [comment]
• What is the purpose of this token? How will it benefit Trust Wallet users?
 • How is the token being distributed? Are you conducting an airdrop?
 • Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?
 • Is the token listed on a centralized/decentralized exchange?
 • Is a Smart Contract audit completed? Where can we find this information?

**Comment by xai-cx** [comment]
• What is the purpose of this token? How will it benefit Trust Wallet users?
Purpose of this token is to create and enable Crypto and AI to perform utilities. We got X Draw (AI Drawing) , X Scanner (Contract Scanning for Risks), X GPT (OpenAI GPT) and machine learning in our dataset.

This will benefit trust wallet users because most of our users are using trust wallet and having listed in trust wallet will get them access to our logo, website and price.

• How is the token being distributed? Are you conducting an airdrop?
Token is being distributed at PancakeSwap. We are not conducting an airdrop.

• Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?
No ICO or Token Presale.

• Is the token listed on a centralized/decentralized exchange?
Token is listed on PancakeSwap V2.

• Is a Smart Contract audit completed? Where can we find this information?
Smart contract audit can be found at https://app.solidproof.io/projects/xai

**Comment by Cryptocool1** [comment]
How did you get 10k holders in 1week?

**Comment by xai-cx** [comment]
> How did you get 10k holders in 1week?

We did twitter meme contest with influences to use X Draw and its contain our watermark for our site.
We also manage to trend at Dextools for daily gainer, and hot trending.
Next, we are also got news featured on AsiaOne, Bloomberg, Yahoo Finance and some other news media outlet. 

This allows us to get a good community and gain the holders over 11 days period, and providing real working AI utility with value.

**Comment by Cryptocool1** [comment]
So there was no airdrop?

**Comment by xai-cx** [comment]
> So there was no airdrop?

Yes we did not conduct any airdrop with any 3rd party.

**Comment by Cryptocool1** [comment]
ADF8D31E-52C4-47C6-AB22-CF48E0FEB84D


How can you explain this message from CEO in your telegram group?

**Comment by xai-cx** [comment]
> How can you explain this message from CEO in your telegram group?

Sorry, I think he mistaken the idea of airdrop, we did not conduct any airdrop, my name is Olan and I am one of the developer of the project.

**Comment by Cryptocool1** [comment]
Thank you for you interest in adding your token into Trust Wallet, we will observe the development of your project and decide whether to add your token

**Comment by xai-cx** [comment]
> Thank you for you interest in adding your token into Trust Wallet, we will observe the development of your project and decide whether to add your token

Noted with thanks, I had check with CEO and he was unaware of the message that he type, he reply wrongly on that question. Hope for Trust Wallet consideration as we are a real token that develop real AI utilities and not a meme token.

Thank you.

**Pull request merged**
