### PR TITLE
Please add logo to LOCK token !

### PR DESCRIPTION
**Pull request by GabeGabe1**
THanks !

### CODE REVIEW

**Comment by GabeGabe1** [comment]
@admin , i see it having 3 failed checks ? How i can solve that ? thanks . The only thing i need it's logo (for uniswap )

**Comment by GabeGabe1** [comment]
Let me know what info it's needed - I can provide all social media / etc

**Comment by catenocrypt** [comment]
```
-  X 'Chain folders are lowercase, contain only predefined list of files': 'File '0xB9464ef80880c5aeA54C7324c0b8Dd6ca6d05A90' not allowed in chain folder: ethereum
```

files should be under `blockchains/ethereum/assets`.  Fixing.

**Comment by GabeGabe1** [comment]
> 
> 
> ```
> -  X 'Chain folders are lowercase, contain only predefined list of files': 'File '0xB9464ef80880c5aeA54C7324c0b8Dd6ca6d05A90' not allowed in chain folder: ethereum
> ```
> 
> files should be under `blockchains/ethereum/assets`. Fixing.

Thanks verry much for fixing , i spent yesterday all day to fix it and i couldn't do it .

**Pull request merged**
