### PR TITLE
Add Burn logo and info

### PR DESCRIPTION
**Pull request by BURNTOKEN5000**
i want give my token burn logo and info thanks you

### CODE REVIEW

**Comment by catenocrypt** [comment]
Things to fix:
- BEP20 tokens must go into `blockchains/smartchain/assets` (not in blockchains/binance).
- Info.json has to be a json file, with predefined structure.  Please have a look at info.json files in existing smartchain folders.

Please create a new PR, closing this one.

**Comment by catenocrypt** [comment]
Sorry, fee was just paid at the same time.
I am reopening now, but please fix:
- either fix here -- move files to smartchain folder, change contents of info.json (see above)
- or close this PR and create a new clean one.  Fee paid here can be considered there.
Chose what is easier.

**Comment by BURNTOKEN5000** [comment]
at future no need make payment?

**Comment by catenocrypt** [comment]
Please fix info.json in this PR.

**Comment by BURNTOKEN5000** [comment]
where the wrong?? 

imake it like this
BEP20: 0xef5CeB00AE3eb617773016B4ca886b61FA4e027E

**Comment by BURNTOKEN5000** [comment]
i;m done fix json file

**Pull request closed without merging**
