### PR TITLE
Update new BHC contract address 

### PR DESCRIPTION
**Pull request by BHCHappiness**
Old contract: https://bscscan.com/token/0xa6381c6fd8f40a44721ef4f61edc1a8ccca7bf3d

New contract: https://bscscan.com/token/0x6fd7c98458a943f469e1cf4ea85b173f5cd342f4

Public announcement: https://twitter.com/BHC_Happiness/status/1339804061797793794?s=20

### CODE REVIEW

**Comment by BHCHappiness** [comment]
https://explorer.binance.org/tx/E0CC2065CA78A9F7E7955EADB052663ECF7C277FB56090CD539DB1E2765D6995

done payment
twt

**Comment by catenocrypt** [comment]
Performed several fixes on the submitted files.

**Comment by BHCHappiness** [comment]
@catenocrypt  Thank you sir, 

what will happen to the old contract? I hope it will no longer available on trust wallet or the logo of BHC will not show from the old contract

**Comment by catenocrypt** [comment]
Removing logo of old contract with https://github.com/trustwallet/assets/pull/5149 .

**Comment by BHCHappiness** [comment]
Thank you :) all is good

**Pull request merged**
