### PR TITLE
Add new Terra Classic validator: lunc_nymph

### PR DESCRIPTION
**Pull request by luncnymph**

### CODE REVIEW

**Comment by luncnymph** [comment]
Why closed the PR before I make the payment? What is the next step? Thanks

**Comment by Cryptocool1** [comment]
What is the purpose for creating this PR?

**Comment by luncnymph** [comment]
The purpose of this PR is to make my Terra Classic validator show on the active validator list on Trust Wallet.

**Comment by Cryptocool1** [comment]
Did you see the logo you submitted?

**Comment by luncnymph** [comment]
Yes. That's the picture I use for my validator. I can change that if that's the problem. Please explain more. Thanks

**Comment by luncnymph** [comment]
Just followed you on Twitter

**Comment by Cryptocool1** [comment]
We are not accept logo as a picture of human

**Comment by luncnymph** [comment]
Ok I didn't know but my validator on Terra Station uses the same logo. Must I use a different logo on Trust?

**Comment by luncnymph** [comment]
I'm a #lunc validator not a token or smart contract. 😔

**Comment by Cryptocool1** [comment]
Submission looks good awaiting for the fee payment

**Comment by luncnymph** [comment]
Thanks sweetie😘! Will pay soon!

**Comment by luncnymph** [comment]
Paid 😀

**Comment by luncnymph** [comment]
Can you merge the PR now? Thanks

**Pull request merged**
