### PR TITLE
Add NFTStyle (BEP20)

### PR DESCRIPTION
**Pull request by developernftstyle**
Adding info for BEP20 token 'NFTStyle'.

PR created by <a href="https://assets.trustwallet.com">TW Assets Management</a>

### CODE REVIEW

**Comment by Cryptocool1** [comment]
• What is the purpose of this token? How will it benefit Trust Wallet users?
 • How is the token being distributed? Are you conducting an airdrop?
 • Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?
 • Is the token listed on a centralized/decentralized exchange?
 • Is a Smart Contract audit completed? Where can we find this information?

**Comment by developernftstyle** [comment]
Hello,

• What is the purpose of this token? How will it benefit Trust Wallet 
users?

  Future Fashion is shaped by unstoppable nft technology. NFTStyle; It 
will be the first nft fashion stop where fashion icons, stylists, world 
brands and amateur artists will guide fashion. The future will now be 
felt much more closely.Who knows, maybe in the very near future your 
fashion design will become a unique icon in the world of Fortnite.

The purpose of the token; To support professional and amateur fashion 
designers by including the fashion world in the blockchain network. We 
also aim to offer unique NFT collections for the leading brands of the 
Fashion industry.

• How is the token being distributed? Are you conducting an airdrop?

  On Each Transaction:
2% Redistributed, 1% Burn, 4% Marketing, 3% Development
Airdrop not done.

• Did you sold the tokens at an Initial Coin Offering (ICO) or a token 
presale?

  No, the pre-sale and ICO sale of the token did not take place.

• Is the token listed on a centralized/decentralized exchange?

  Yes we listed https://www.coinecko.com/en/coins/nftstyle
                
https://pancakeswap.finance/info/token/0x5d33e26336c445c71f206dd18b64ce11c2eee3f0

• Is a Smart Contract audit completed? Where can we find this 
information?

  Audit reporting has not yet been completed. We agreed with 
Solidty.finance. We are waiting for the report to be published. We will 
share it with you when the audit is published.

**Comment by ramsty** [comment]
Awaiting for smart contract audit. On hold for now.

**Comment by Cryptocool1** [comment]
Please come back to us when smart contract audit will be ready.
When creating a new PR make sure to mention this PR, so that we can see that fee has been paid already here.

**Comment by developernftstyle** [comment]
Hello, our smart contract is ready and you can view it from the link 
below.

https://solidity.finance/audits/NFTStyle/

**Comment by cryptomanz** [comment]
Hello,
Please follow the rules for adding token, your logo should be a full screen, 256x256.

**Comment by developernftstyle** [comment]
> Hello, Please follow the rules for adding token, your logo should be a full screen, 256x256.
trustwallet-logo

**Comment by developernftstyle** [comment]
I send you the logo in the dimensions you want.

**Comment by developernftstyle** [comment]
Do I need to open a new PR, can we continue on this PR?

**Comment by developernftstyle** [comment]
> Hello, Please follow the rules for adding token, your logo should be a full screen, 256x256.

Now we checked the first logo we sent you and it seems that 256x256 logo has already been sent to you.

**Comment by ramsty** [comment]
Duplicate of #15862

**Pull request closed without merging**
