### PR TITLE
Update Logo and Info for PlotX

### PR DESCRIPTION
**Pull request by ankit5902**
Please update PlotX logo and info for the PLOT token as the previous one wasn't visible.

### CODE REVIEW

**Comment by ankit5902** [comment]
I have updated it and the latest Commit No is [07cab98](https://github.com/trustwallet/assets/pull/4933/commits/07cab98d255aa4c1c7716e73193a2b874334e321) and [a7ae410](https://github.com/trustwallet/assets/pull/4933/commits/a7ae41022be036ac429be6293bc30f29ccbf7f0b)

**Comment by ankit5902** [comment]
Info is updated. But Logo is still not yet updated. Also the name should have been PlotX but it is still showing PLOT. I have mention in the below screenshot which needs correction. Please check once.

16046729-E176-4D35-892E-3BF5390E2239

**Comment by Iamdeadlyz** [comment]
> @Iamdeadlyz @catenocrypt **Info** is updated. But **PlotX Logo** is still not yet updated. Also the name should have been “**PlotX**” but it is still showing PLOT. I have mention in the below screenshot which needs correction. Please check once.
> 
> 16046729-E176-4D35-892E-3BF5390E2239

Hi @ankit5902, PLOT is being reflected since that's what your smart contract returns: https://etherscan.io/address/0x72f020f8f3e8fd9382705723cd26380f8d0c66bb#readContract

Also, the logo is updated already. Please check it again.

**Comment by ankit5902** [comment]
> > @Iamdeadlyz @catenocrypt **Info** is updated. But **PlotX Logo** is still not yet updated. Also the name should have been “**PlotX**” but it is still showing PLOT. I have mention in the below screenshot which needs correction. Please check once.
> > 16046729-E176-4D35-892E-3BF5390E2239
> 
> Hi @ankit5902, PLOT is being reflected since that's what your smart contract returns: https://etherscan.io/address/0x72f020f8f3e8fd9382705723cd26380f8d0c66bb#readContract
> 
> Also, the logo is updated already. Please check it again.

@Iamdeadlyz Thanks for the info. Logo and Info is updated. Once again thank ls for the efforts..😊

**Pull request merged**
