### PR TITLE
Agata token info

### PR DESCRIPTION
**Pull request by AgaTechSystems**
Agata token information

### CODE REVIEW

**Review by AgaTechSystems — COMMENTED** [review]
fixing tags

**Review by AgaTechSystems — COMMENTED** [review]
Agata token info

**Comment by Cryptocool1** [comment]
As per our policy, there is a minimum requirement of 10,000 holder addresses and 15,000 transactions, in order to filter out scam tokens.
See the criteria at : https://developer.trustwallet.com/listing-new-assets/requirements .

**Comment by AgaTechSystems** [comment]
Dear Trust Wallet Team, 

I am writing to request the listing of **Agata Token (AGATA)** on **Trust Wallet**, or at least for the token price to become visible, Agata token is a key component of the Agatech ecosystem. Agatech, currently ranked at 1950th on CoinMarketCap, is a multifaceted blockchain project with a focus on decentralization and user empowerment. 

**Key Highlights of Agata Token and Agatech:**

**CoinMarketCap Listing:** Agata Token is listed on CoinMarketCap, indicating its growing presence and acceptance in the crypto community. But still there is no price visible in wallets even though, for example Trust Wallet, gets data from CoinMarketCap. 
https://coinmarketcap.com/currencies/agatech/

**Security and Compliance:** Agata Token has undergone rigorous audits and KYC verification. We have a Checkdot audit with zero issues, a Cyberscope audit with informative comments, and KYC verification from Cyberscope.  
**Checkdot Audit:** https://audits.checkdot.io/Agata-Audit-CheckDot.pdf  
**Cyberscope Audit:** https://github.com/cyberscope-io/audits/blob/main/agata/audit.pdf  
**Cyberscope KYC:** https://github.com/cyberscope-io/kyc/blob/main/agata/kyc.png

**GoPlusLabs scanner with 0 risks and 0 warnings:** 
https://gopluslabs.io/token-security/56/0xb427e47e8fDD678278d2A91EEaC014ffcDDaF029


**Trading Pairs and Exchange Listings:** Agata Token is available on Pancakeswap, SushiSwap, and Apeswap with trading pairs AGATA/WBNB, AGATA/BTCB, and AGATA/USDT.

**Market Position and Liquidity:** Our market cap is around $105,000 with a Fully Diluted Value of approximately $425,000, and liquidity around $60,000 is locked. The presale concluded on October 31, 2023, with 100% of the presale amount allocated to the LP for Pancakeswap.


Community and Holder Growth: Agatech is nearing 1000 holders, who are eagerly anticipating the integration of AGATA's price value to display in their wallets.
**Bscscan information:**
https://bscscan.com/token/0xb427e47e8fDD678278d2A91EEaC014ffcDDaF029

Our goal at Agatech is not just profit but creating significant value for the industry, as demonstrated by our self-funded project. We are committed to providing innovative solutions within the blockchain space, emphasizing security, decentralization, and user empowerment. We believe that listing Agata Token on Trust Wallet will not only benefit our growing community but also add value to Trust Wallet's diverse crypto offerings. 

We are ready to provide any additional information required and look forward to the possibility of collaboration. 
Thank you for considering Agata Token for listing, or price display on Trust Wallet.

Sincerely,
Víðir Helgi Helgason
CEO
Agatech

**Pull request closed without merging**
