### PR TITLE
Add WAGMI Game (WAGMI) (ERC20)

### PR DESCRIPTION
**Pull request by WagmiToken**
Adding info for ERC20 token 'WAGMI Game (WAGMI)'.

PR created by <a href="https://assets.trustwallet.com">TW Assets Management</a>

### CODE REVIEW

**Comment by Cryptocool1** [comment]
As per our policy, brand new tokens are not included, there is a minimum requirement of 10,000 holder addresses and 15,000 transactions, in order to filter out scam tokens.
See the criteria at : https://developer.trustwallet.com/assets/requirements .

**Comment by WagmiToken** [comment]
Hello thanks for review again. 
We would like to add our ERC Chain aswell as stated in the BSC Merge seen here https://github.com/trustwallet/assets/pull/19692

**Comment by WagmiToken** [comment]
> As per our policy, brand new tokens are not included, there is a minimum requirement of 10,000 holder addresses and 15,000 transactions, in order to filter out scam tokens. See the criteria at : https://developer.trustwallet.com/assets/requirements .

Pls see our comment.

**Comment by WagmiToken** [comment]
@Cryptocool1 can u check our previous Repo #19692 and u can verify the chain on Coinmarketcap https://coinmarketcap.com/currencies/wagmi-game/ audit ERC https://global-uploads.webflow.com/619ce4a1ae033d566ff33283/61a79e8cb05b986dd5cc6e69_WAGMI-AUDIT.pdf

**Pull request closed without merging**
