### PR TITLE
Add Hoppy logo and info in Trust Wallet

### PR DESCRIPTION
**Pull request by coppermug**
Add Hoppy logo and info in TWT

### CODE REVIEW

**Comment by Cryptocool1** [comment]
can you add the tags, see the requirements here: https://developer.trustwallet.com/assets/repository_details

**Comment by coppermug** [comment]
Hi, I would request you to kindly consider our pull request. As you can see, the token circulation number is pretty close to the requirement stated. Previously the number is lower, however now is being increase to a higher number. Despite our honest efforts, we are experiencing a hard time onboarding trust wallet user without the logo. Appreciate your attention to make this ecosystem a greater place.

**Comment by Cryptocool1** [comment]
• What is the purpose of this token? How will it benefit Trust Wallet users?
 • How is the token being distributed? Are you conducting an airdrop?
 • Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?
 • Is the token listed on a centralized/decentralized exchange?
 • Is a Smart Contract audit completed? Where can we find this information?

**Comment by coppermug** [comment]
• What is the purpose of this token?
HOP token, is the governance token of HOPPY. HOPPY hopes to become the Most Influential Sustainability-driven
Community, aiming to build Awareness and make impactful Actions in contributing towards the 2030 United Nations’ Sustainable Development Goals.

**Comment by coppermug** [comment]
How will it benefit Trust Wallet users?
Trust wallet users will be able to participate in realizing a greener, better future. Most importantly, with the Logo we can help users identify the real HOP token, avoid being scammed by fake contracts.

**Comment by coppermug** [comment]
• How is the token being distributed? Are you conducting an airdrop?
Token distribution is as below. Presales happened in 2021 Q2. We are not conducting an airdrop.

WhatsApp Image 2022-01-15 at 9 12 30 PM
?

**Comment by coppermug** [comment]
• Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?
Yes, presale happened in Q2 2021.

• Is the token listed on a centralized/decentralized exchange?
Yes. It's on pancakeswap 
https://pancakeswap.finance/swap?outputCurrency=0x984811e6f2695192add6f88615dF637bf52a5Cae

**Comment by Cryptocool1** [comment]
Is a Smart Contract audit completed? Where can we find this information?

**Comment by coppermug** [comment]
Yes we have completed the Smart Contract audit last year. Do allow me find the audit document.

**Pull request closed without merging**
