### PR TITLE
Add Polka City (BEP20)

### PR DESCRIPTION
**Pull request by drogbacrash**
Adding info for BEP20 token 'Polka City'.

PR created by <a href="https://assets.trustwallet.com">TW Assets Management</a>

### CODE REVIEW

**Comment by drogbacrash** [comment]
PR #16072
I had paid

merge-fee-bot[bot] ***@***.***>, 27 Kas 2021 Cmt, 01:24
tarihinde şunu yazdı:

**Comment by cryptomanz** [comment]
Hello,
Please follow the rules for adding token, your logo should be a full screen, 256x256.

**Comment by drogbacrash** [comment]
logo

Dear Trustwallet team, please check the attachment fee for the 256*256 png logo.  Also, can you please update our ERC20 logo too. We are ready to pay additional fee if necessary. ERC20 contract: 0xaa8330fb2b4d5d07abfe7a72262752a8505c6b37

**Comment by drogbacrash** [comment]
Is our logo approved?

**Comment by drogbacrash** [comment]
Thanks for updating our logo on Pancakeswap. Can you please also our Uniswap logo since we are on ETH chain mainly. 

Contract: 0xaa8330fb2b4d5d07abfe7a72262752a8505c6b37

Thanks in advance.

**Comment by drogbacrash** [comment]
Thanks for updating our logo on Pancakeswap. Can you please also our
Uniswap logo since we are on ETH chain mainly.

Contract: 0xaa8330fb2b4d5d07abfe7a72262752a8505c6b37

Thanks in advance.

CryptoA ***@***.***>, 28 Kas 2021 Paz, 21:50 tarihinde şunu
yazdı:

**Pull request merged**
