### PR TITLE
Update ANT icon

### PR DESCRIPTION
**Pull request by sohkai**
See https://blog.aragon.org/aragon-brand-refresh/

### CODE REVIEW

**Comment by sohkai** [comment]
@kolya182 Hey! Just wondering—it looks like the resize made the image _quite_ a lot larger! Should we run this through the optimizer again?

**Comment by kolya182** [comment]
> @kolya182 Hey 👋! Just wondering—it looks like the resize made the image _quite_ a lot larger! Should we run this through the optimizer again?

Try it, but it did optimized proportionally to original image

**Comment by sohkai** [comment]
Ran it through ImageOptim on 80% and got it to 70kb :). We might be able to do even a bit more—it was really nice that the old icon was only 17kb!

-------

Optimized version:

logo

**Comment by kolya182** [comment]
Thanks, updated

**Pull request merged**
