### PR TITLE
Add WAP Token (BEP20)

### PR DESCRIPTION
**Pull request by Mikey8437**
This PR is being closed due to inactivity. If you wish to continue, please have us reopen the PR before sending your payment, or just create a new one.
Do NOT send payments for closed PR, as the fee may by lost!
  (48 vs. 48 hrs)

### CODE REVIEW

**Comment by Mikey8437** [comment]
Memo: 8495

Transaction

B77092C4E4B35F9F4D7D5E09BCA7594DB2A80AD7C5E4E31B34B42F6E1A9D653C

**Comment by Cryptocool1** [comment]
PR should include only 2 files

**Comment by Mikey8437** [comment]
logo
[wap.txt](https://github.com/trustwallet/assets/files/6604769/wap.txt)

**Comment by Mikey8437** [comment]
Payment was Sent

Please review transaction with Memo 8495 

Transaction Time: 21 MAy 2021 at 10:42 AM

**Comment by Mikey8437** [comment]
Memo: 8495

Transaction

B77092C4E4B35F9F4D7D5E09BCA7594DB2A80AD7C5E4E31B34B42F6E1A9D653C

Date: 21 May 2020

Sent with [ProtonMail](https://protonmail.com) Secure Email.

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐

**Pull request closed without merging**
