### PR TITLE
Add Chickencoin (ERC20)

### PR DESCRIPTION
**Pull request by 0xMeow404**
Adding info for ERC20 token `Chickencoin`.

PR created by [0xMeow404](https://x.com/0xMeow404)

### CODE REVIEW

**Comment by 0xMeow404** [comment]
The fee has been paid and confirmed. Waiting for the updates from @Cryptocool1 , @cryptomanz1

**Comment by Cryptocool1** [comment]
• What is the purpose of this token? How will it benefit Trust Wallet users?
 • How is the token being distributed? Are you conducting an airdrop?
 • Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?
 • Is the token listed on a centralized/decentralized exchange?
 • Is a Smart Contract audit completed? Where can we find this information?

**Comment by 0xMeow404** [comment]
>• What is the purpose of this token? How will it benefit Trust Wallet users?

Chickencoin is a meme coin launched on the Ethereum blockchain as a ERC-20 token and forked from the PEPE smart contract.

>• How is the token being distributed? Are you conducting an airdrop?

Yes, airdrop.

Snapshot taken on block # 19420069

Distribution:
0.033074700924153 $CHKN per 1 $PEPE for top 69,000 🐸 holders

1.199894613877807 $CHKN bonus per 1 $PEPE for top 420 🐋 wallets

>• Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?

Fair launch in a Uniswap V2 Pool for the community.

>• Is the token listed on a centralized/decentralized exchange?

Uniswap V2.

>• Is a Smart Contract audit completed? Where can we find this information?

Chickencoin is a meme coin launched on the Ethereum blockchain as a ERC-20 token and forked from the PEPE smart contract.
PEPE - https://etherscan.io/token/0x6982508145454ce325ddbe47a25d4ec3d2311933#code
CHKN - https://etherscan.io/token/0xD55210Bb6898C021a19de1F58d27b71f095921Ee#code

**Comment by 0xMeow404** [comment]
> > • What is the purpose of this token? How will it benefit Trust Wallet users?
> 
> Chickencoin is a meme coin launched on the Ethereum blockchain as a ERC-20 token and forked from the PEPE smart contract.
> 
> > • How is the token being distributed? Are you conducting an airdrop?
> 
> Yes, airdrop.
> 
> Snapshot taken on block # 19420069
> 
> Distribution: 0.033074700924153 $CHKN per 1 $PEPE for top 69,000 🐸 holders
> 
> 1.199894613877807 $CHKN bonus per 1 $PEPE for top 420 🐋 wallets
> 
> > • Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?
> 
> Fair launch in a Uniswap V2 Pool for the community.
> 
> > • Is the token listed on a centralized/decentralized exchange?
> 
> Uniswap V2.
> 
> > • Is a Smart Contract audit completed? Where can we find this information?
> 
> Chickencoin is a meme coin launched on the Ethereum blockchain as a ERC-20 token and forked from the PEPE smart contract. PEPE - https://etherscan.io/token/0x6982508145454ce325ddbe47a25d4ec3d2311933#code CHKN - https://etherscan.io/token/0xD55210Bb6898C021a19de1F58d27b71f095921Ee#code

@Cryptocool1 do you need more information?

**Comment by 0xMeow404** [comment]
@Cryptocool1 , @cryptomanz1

Can we have updates on this?

**Comment by Cryptocool1** [comment]
We require smart contract audit from reputable companies. Please see https://developer.trustwallet.com/listing-new-assets/requirements

**Comment by 0xMeow404** [comment]
> We require smart contract audit from reputable companies. Please see https://developer.trustwallet.com/listing-new-assets/requirements

@Cryptocool1 , team will do the audit as fast as we can. How long this PR will be on hold?

We are now listed on CoinMarketCap - https://coinmarketcap.com/currencies/chickencoin/

**Comment by Cryptocool1** [comment]
> > We require smart contract audit from reputable companies. Please see https://developer.trustwallet.com/listing-new-assets/requirements
> 
> @Cryptocool1 , team will do the audit as fast as we can. How long this PR will be on hold?
> 
> We are now listed on CoinMarketCap - https://coinmarketcap.com/currencies/chickencoin/

I’ll close this PR for now. Feel free to create new PR once audit is done, please mention this Pull Request so the fee can be reused

**Comment by 0xMeow404** [comment]
> > > We require smart contract audit from reputable companies. Please see https://developer.trustwallet.com/listing-new-assets/requirements
> > 
> > 
> > @Cryptocool1 , team will do the audit as fast as we can. How long this PR will be on hold?
> > We are now listed on CoinMarketCap - https://coinmarketcap.com/currencies/chickencoin/
> 
> I’ll close this PR for now. Feel free to create new PR once audit is done, please mention this Pull Request so the fee can be reused

@Cryptocool1 , certik audit will be done within today. can we keep this PR open for just a day?

**Comment by Cryptocool1** [comment]
Reopened

**Comment by 0xMeow404** [comment]
> Reopened

Thank you! We will update with Audit soon!

**Comment by 0xMeow404** [comment]
> Reopened

@Cryptocool1 , CertiK audit uploaded to our contract repo.

https://github.com/Chickencoineth/Chickencoin-contract/blob/main/REP-final-20240322T005010Z.pdf

**Comment by 0xMeow404** [comment]
> > Reopened
> 
> @Cryptocool1 , CertiK audit uploaded to our contract repo.
> 
> https://github.com/Chickencoineth/Chickencoin-contract/blob/main/REP-final-20240322T005010Z.pdf

@Cryptocool1 @cryptomanz1 , please let us know if PR is fine to be merged.

**Comment by 0xMeow404** [comment]
> > > Reopened
> > 
> > 
> > @Cryptocool1 , CertiK audit uploaded to our contract repo.
> > https://github.com/Chickencoineth/Chickencoin-contract/blob/main/REP-final-20240322T005010Z.pdf
> 
> @Cryptocool1 @cryptomanz1 , please let us know if PR is fine to be merged.

This is the public CertiK link of the Chickencoin audit.

https://skynet.certik.com/projects/chickencoin

**Comment by Chickencoinerc20** [comment]
Price still isn't showing in trustwallet. Please refer to https://www.coingecko.com/en/coins/chickencoin and https://coinmarketcap.com/currencies/chickencoin/

**Pull request merged**
