### PR TITLE
Add COPTER logo and info

### PR DESCRIPTION
**Pull request by helicopterfinance**
Adding COPTER to Trustwallet

### CODE REVIEW

**Review by helicopterfinance — COMMENTED** [review]
is the upper case and lowercase of the token address affect the listing?

**Comment by Cryptocool1** [comment]
> is the upper case and lowercase of the token address affect the listing?

Yes, your contract should be in checksum format 0xBC12aD556581ff7162E595E5956F5F3845FDB38c.

**Comment by Cryptocool1** [comment]
Submission looks good. awaiting fee payment.

**Comment by helicopterfinance** [comment]
> Submission looks good. awaiting fee payment.

Please pay 250 TWT with the memo 7388 to the address bnb1tqq9llyr3dyjd559dha6z5r5etk3qfwk07m098.

is this wallet under BEP20? i am transferring 250 TWT but there is no place to write memo

**Comment by helicopterfinance** [comment]
https://explorer.binance.org/tx/4501E51E2773560098D6A60A5DEB7B96A442B1C8D79BA848C5E21CB42EA57306

alright the fees is paid

**Comment by helicopterfinance** [comment]
hi there, the logo is cut off somehow. can we resubmit it for another png file?

**Comment by helicopterfinance** [comment]
logo


can i change to this logo?

**Comment by helicopterfinance** [comment]
> Submission looks good. awaiting fee payment.

hi maam, can you help me change the logo ? 
logo

**Comment by helicopterfinance** [comment]
what should i do to fix the logo? please advise thank you

**Comment by Cryptocool1** [comment]
> what should i do to fix the logo? please advise thank you

You need to open new PR for your new logo

**Comment by helicopterfinance** [comment]
> > what should i do to fix the logo? please advise thank you
> 
> You need to open new PR for your new logo

hi cryptocool, you mean reopen a new folder and correct logo again? do i have to pay the fees again?

**Comment by helicopterfinance** [comment]
> > what should i do to fix the logo? please advise thank you
> 
> You need to open new PR for your new logo

i try to add a new file but it does not work. please advise. thank you

**Pull request merged**
