### PR TITLE
Add dHEDGE DAO Token (PoS) (POLYGON)

### PR DESCRIPTION
**Pull request by D-Ig**
Adding info for POLYGON token 'dHEDGE DAO Token (PoS)'.

PR created by <a href="https://assets.trustwallet.com">TW Assets Management</a>

### CODE REVIEW

**Comment by cryptomanz** [comment]
As per our policy, brand new tokens are not included, there is a minimum requirement of 10,000 holder addresses and 20,000 transactions, in order to filter out scam tokens.
See the criteria at : https://developer.trustwallet.com/assets/requirements .

**Comment by D-Ig** [comment]
> As per our policy, brand new tokens are not included, there is a minimum requirement of 10,000 holder addresses and 20,000 transactions, in order to filter out scam tokens.
> 
> See the criteria at : https://developer.trustwallet.com/assets/requirements .

what do you mean by "brand new tokens"? DHT token is already in this repo, I've just edited its info.json and added PoS version. Have you checked PR contents?

**Comment by D-Ig** [comment]
Hello @Iamdeadlyz appreciate your assistance.
Could you please advise, does bridged token to Polygon count as a new token and thus require a fee?

If yes, can I just delete files from `blockchains/polygon/` folder so that PR can be merged w/o paying the fee? In that case it will include just updates to existing token plus dapp logo. (I consider this to be enough to make an application https://trustwallet.com/submit-dapp)

If no, will be happy if re-open is possible

**Review by Successahead — COMMENTED** [review]
Approve

**Comment by Iamdeadlyz** [comment]
Hi @D-Ig,

Merge fee is necessary when making any changes/updates. Thus, it's better to keep the files in `blockchains/polygon/`, so there's only one merge fee to be processed.

**Comment by D-Ig** [comment]
> Hi @D-Ig,
> 
> 
> 
> Merge fee is necessary when making any changes/updates. Thus, it's better to keep the files in `blockchains/polygon/`, so there's only one merge fee to be processed.
> 
> 

hey @Iamdeadlyz 
big thanks for reply. sure! can you please confirm - if I create new identical PR and pay merge fee after PR'll be merged?

**Review by Successahead — COMMENTED** [review]
Merge

**Comment by Successahead** [comment]
> **PR Summary**
> Files OK: 4
> Token in PR: POLYGON 0x8C92e38eCA8210f4fcBf17F0951b198Dd7668292
> Symbol: **DHT** decimals: 18
> Links: [Logo](https://raw.githubusercontent.com/D-Ig/assets/br0123-214204/blockchains/polygon/assets/0x8C92e38eCA8210f4fcBf17F0951b198Dd7668292/logo.png) [Info](https://raw.githubusercontent.com/D-Ig/assets/br0123-214204/blockchains/polygon/assets/0x8C92e38eCA8210f4fcBf17F0951b198Dd7668292/info.json) [Website](https://www.dhedge.org/) [Explorer](https://polygonscan.com/token/0x8C92e38eCA8210f4fcBf17F0951b198Dd7668292)
> Tags: governance, defi
> Token check error: 
> ❌ low token circulation: number of holders is 616, below limit of 10000
> 
> 
> 
> <span style="padding: 5px; background-color: rgb(32,32,32);"></span>
> 
> 
>

**Comment by Iamdeadlyz** [comment]
Hi @D-Ig,

Apologies for the late reply.

If you create an identical PR (same files and modifications) and process the merge fee after, then yes, the PR will be merged.

**Comment by Bibi2013** [comment]
Hi I'm I'm still  having  toilet getting my mohry but I'm yarning I will get there thanodb

**Pull request closed without merging**
