### PR TITLE
Add DKYC Logo and Info

### PR DESCRIPTION
**Pull request by dontKYC**

### CODE REVIEW

**Comment by dontKYC** [comment]
Payment complete:

https://explorer.binance.org/tx/F6A555F76C3385A5F5CAF6403DA3D7930D894C9EB9B7872680DADC4E64301EC3

**Comment by Cryptocool1** [comment]
hello,
• What is the purpose of this token? How will it benefit Trust Wallet users?
 • How is the token being distributed? Are you conducting an airdrop?
 • Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?
 • Is the token listed on a centralized/decentralized exchange?
 • Is a Smart Contract audit completed? Where can we find this information?

**Comment by dontKYC** [comment]
Hello! 

Thank you for the email. Happy to answer your questions.

• What is the purpose of this token? How will it benefit Trust Wallet users?

Unlike other reflection tokens (that provide holders with redistributions for holding), DKYC is unique in that it provides holders with BUSD reflections that can be directly swapped for prepaid debit cards (via an automated dashboard) without having to cross the chain. So, essentially, it allows them to hold DKYC and enjoy small transactions in real life like dinner, movies, coffee, beauty products, and entertainment, anonymously. No other token has ever bridged the gap between the Binance Smart Chain and real-life anonymous spending. Our aim is to inspire financial freedom around the world.

• How is the token being distributed? Are you conducting an airdrop?
The token is available for sale via PancakeSwap. No airdrops were, or will be conducted.

• Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?
We conducted a successful presale (250/500BNB) via DXSale on 23 August 2021 at 18:00 UTC. Total supply: 10 Billion tokens. 5.1 Billion Presale. 3.5 Billion to PancakeSwap. 100% of the liquidity locked. We have not, and will not engage in burns, which can be dishonest and misleading to holders.

Lock link: https://dxsale.app/app/v2_9/dxlockview?id=2848&add=0&type=lpdefi&chain=BSC

• Is the token listed on a centralized/decentralized exchange?
We are not listed on an exchange as yet. Our reflection tokenomics and fully locked LP would not permit us to do this yet. We are looking to do this in the future. In the meantime, we are listed on CoinGecko and CoinMarketCap with full tracking:

https://www.coingecko.com/en/coins/dont-kyc
https://coinmarketcap.com/currencies/dont-kyc/

• Is a Smart Contract audit completed? Where can we find this information?
The full audit was completed by Techrate.

https://github.com/TechRate/Smart-Contract-Audits/blob/main/August/DontKYC.pdf

Please note, the code and contract are identical, albeit with a new CA as the first presale did not succeed.  

If you need any other information at all, please do not hesitate to contact me.

Best
Marg Van Der Wilk
DKYC Administration Team
dontkyc.com

**Comment by cryptomanz** [comment]
can you add the links?

**Comment by dontKYC** [comment]
> can you add the links?

Website
https://dontkyc.com

Email
hello@dontkyc.com

Presale
https://dxsale.app/app/v2_9/defipresale?saleID=2848&chain=BSC

Lock LP Link
https://dxsale.app/app/v2_9/dxlockview?id=2848&add=0&type=lpdefi&chain=BSC 

CoinMarketCap
https://coinmarketcap.com/currencies/dont-kyc

CoinGecko
https://www.coingecko.com/en/coins/dont-kyc

Techrate audit
https://github.com/TechRate/Smart-Contract-Audits/blob/main/August/DontKYC.pdf

**Pull request merged**
