### PR TITLE
Add StakeLab providers

### PR DESCRIPTION
**Pull request by zdeadex**

### CODE REVIEW

**Comment by zdeadex** [comment]
Payment made: ADF0B8CFA0E4376964638318F031AEED652EEA4E13621B8BBDEA0B2C546DE641

**Comment by cryptomanz1** [comment]
Your website is not working, please check

**Comment by zdeadex** [comment]
> Your website is not working, please check

It is now

**Comment by cryptomanz1** [comment]
seems like something is wrong with your link.
Screenshot 2023-08-23 at 20 00 44

**Comment by zdeadex** [comment]
> seems like something is wrong with your link. Screenshot 2023-08-23 at 20 00 44

sorry redirection wasn't setup but all done now

**Pull request merged**
