### PR TITLE
Add IMPT (ERC20)

### PR DESCRIPTION
**Pull request by IMPTio**
Adding info for ERC20 token 'IMPT'.

PR created by <a href="https://assets.trustwallet.com">TW Assets Management</a>

### CODE REVIEW

**Comment by cryptomanz1** [comment]
• What is the purpose of this token? How will it benefit Trust Wallet users?
 • How is the token being distributed? Are you conducting an airdrop?
 • Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?
 • Is the token listed on a centralized/decentralized exchange?
 • Is a Smart Contract audit completed? Where can we find this information?

**Comment by Bonbon1310** [comment]
Yes more info

**Comment by Cryptocool1** [comment]
@IMPTio

**Comment by IMPTio** [comment]
> What is the purpose of this token? How will it benefit Trust Wallet users? -  IMPT is the first carbon credit exchange and will delivery web 3 tech to help solve climate change - we also have 18,000 active wallets many of which are on trust.

How is the token being distributed? Are you conducting an airdrop?  Initially via our web site and pre sale - we are now active on 1 dex and 3 cex exchanges - uniswap and Lbank - bitmark and going on GATE on 01/01/2023

Ecosystem: 16.293%
*Team: 5.431%
*Marketing: 10.862%
*Early Adopters: 10.862%
*Presale 1: 21.724%
*Presale 2: 15.276%
*Company Reserve: 19.552%

 Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?

Yes we sold two paresale directly on www.impt.io - we are now moved to dex and cex

• Is the token listed on a centralized/decentralized exchange?
we are now active on 1 dex and 3 cex exchanges - uniswap and Lbank - bitmark and going on GATE on 01/01/2023

• Is a Smart Contract audit completed? Where can we find this information?

https://impt.io/assets/documents/IMPT%20Hacken%20Audit.pdf

**Comment by IMPTio** [comment]
can you please respond to mike@impt.io and julia@impt.io if there are any other requests.  We are keen to get live quickly.

**Comment by IMPTio** [comment]
@cryptomanz1 @Cryptocool1 please find the answers above - trust we are there now thanks.

**Pull request merged**
