### PR TITLE
Add SportPoint (BEP20)

### PR DESCRIPTION
**Pull request by UmudHasanov**
Adding info for BEP20 token 'SportPoint'.

PR created by <a href="https://assets.trustwallet.com">TW Assets Management</a>

### CODE REVIEW

**Comment by UmudHasanov** [comment]
Dear Trust Wallet Team,
If we make a payment for the listing, can our token be accepted with 1,500
holders, or should we reach out once we have 10,000 holders?

Thank you for your guidance.
Best regards,
Umid Hasanov
SportPoint

**Comment by UmudHasanov** [comment]
Fee is PAID

**Comment by UmudHasanov** [comment]
https://www.cyberscope.io/audits/point
https://www.coinscope.co/coin/point/kyc
https://coinmarketcap.com/currencies/sportpoint/
https://www.dextools.io/token/sportpoint

**Comment by UmudHasanov** [comment]
https://www.team.finance/view-coin/0x0cF453DC7EA21ef8FdfFC1B14Cb848E1e3884Be5?name=SportPoint&symbol=POINT&chainid=0x38

**Comment by UmudHasanov** [comment]
I kindly ask the Trust Wallet team to review my application.

**Comment by UmudHasanov** [comment]
Please reply. Thank you.

**Comment by Cryptocool1** [comment]
Hello, 
Thank you for applying .
As per our policy, brand new tokens are not included, there is a minimum requirement of 10,000 holder addresses and 15,000 transactions.
See the criteria at : https://developer.trustwallet.com/assets/requirements .

**Comment by Cryptocool1** [comment]
Feel free to come back to us once holders requirement is met. Make sure to mention this Pull Request so the fee can be reused.

**Comment by UmudHasanov** [comment]
> Feel free to come back to us once holders requirement is met. Make sure to mention this Pull Request so the fee can be reused.

Hello, I have submitted a re-application. Please note that I paid a fee in the previous Request.

https://github.com/trustwallet/assets/pull/29054

**Pull request closed without merging**
