### PR TITLE
Add AquaGoat (BEP20)

### PR DESCRIPTION
**Pull request by patrickxaquagoatfinance**
Adding info for BEP20 token 'AquaGoat'.

PR created by <a href="https://assets.trustwallet.com">TW Assets Management</a>

### CODE REVIEW

**Comment by patrickxaquagoatfinance** [comment]
Greetings, payment has been sent from my Binance account to your Binance Chain account with memo 7231

**Comment by Cryptocool1** [comment]
Hello,
can you delete all unnecessary files?

**Comment by patrickxaquagoatfinance** [comment]
Hey there, not too experienced with github. Do you mind running through the steps to delete? Would like to use the info submitted under "Info for token AquaGoat"

**Comment by patrickxaquagoatfinance** [comment]
Can't seem to delete logo.png.png and logo.png, but assets uploaded via assets.trustwallet.com would be what we would like to upload

**Comment by Cryptocool1** [comment]
Hello,
You need to delete these 2 files.
Снимок экрана 2021-05-02 в 18 11 08

**Comment by patrickxaquagoatfinance** [comment]
Greetings, apologies for lack of experience. Please check now to merge. Best regards.

**Pull request merged**
