### PR TITLE
Update new logo for Bird.Money

### PR DESCRIPTION
**Pull request by ToFrom123**
Hello, please update our new logo. Thank you

### CODE REVIEW

**Comment by catenocrypt** [comment]
Submission looks OK, fee payment pending.

**Comment by ToFrom123** [comment]
> Submission looks OK, fee payment pending.

Hey, thanks. I have emailed about our one concern where our total transaction is around 3.8k but your trust wallet requirement is 5k. Could you guys overlook this or do we have to meet this requirement as well? We have a really good use case, community, and presence.

**Comment by catenocrypt** [comment]
Yes, circulation criteria is OK.

image

https://etherscan.io/token/0x70401dFD142A16dC7031c56E862Fc88Cb9537Ce0

**Comment by ToFrom123** [comment]
> Fee is PAID, fantastic! Thanks!
> 
> The PR will be evaluated soon by a maintainer, and if merged, the new logos should be visible in Trust Wallet.
> Please note that the app caches logos (up to several days; if you want to see changes immediately, use a new installation). See the [assets FAQ](https://github.com/trustwallet/assets#faq).
> (@zachzwei, @catenocrypt & @Iamdeadlyz: please take note.)
> 
> ([6 BNB](https://explorer.binance.org/tx/D93952A057B48039D3618731A27938E6CF203634718BF85484BCC0ADE2DA98BD))

Thank you very much.

**Pull request merged**
