### PR TITLE
Add EURC (BEP20)

### PR DESCRIPTION
**Pull request by supportEURC**
Adding info for BEP20 token 'EURC'.

PR created by <a href="https://assets.trustwallet.com">TW Assets Management</a>

### CODE REVIEW

**Comment by supportEURC** [comment]
Hello,We have paid the commission for Pull Request and reopened it.
In addition, we would like to inform you that our project has successfully conducted an ICO, which explains that we had holdings from the very beginning. There was a bit of confusion in the previous reply, for which we apologize.

Thank you!

**Review by Missjones2 — COMMENTED** [review]
Merge

**Comment by bioter** [comment]
@cryptomanz1  @Cryptocool1

**Comment by supportEURC** [comment]
@Cryptocool1  @cryptomanz1 We successfully distributed tokens to partners and conducted an ICO.

**Comment by curiouschonk** [comment]
Where is the team information behind this project?

Where, how, and why was ICO done considering this is a "stablecoin" project that mints "based on demand and backed by Euros" ?

Are you MiCA compliant? If yes, how and where are the supporting documents? If no, why?

**Comment by bioter** [comment]
@Cryptocool1 @cryptomanz1

**Comment by supportEURC** [comment]
@Cryptocool1 @cryptomanz1

**Comment by Cryptocool1** [comment]
Where is the team information behind this project?

Where, how, and why was ICO done considering this is a "stablecoin" project that mints "based on demand and backed by Euros" ?

Are you MiCA compliant? If yes, how and where are the supporting documents? If no, why?

Based on your roadmap, for Q1-Q2 2024, you have established "relationships with regulated financial institutions to manage the Euro reserves that back EURC", who are these institutions and where can we find information stating they have partnered with you?

**Comment by bioter** [comment]
Dear Trust Wallet team,

Thank you for your questions. Here are brief answers:

   1. Information about the team: The project team consists of experts with experience in blockchain, finance and legal regulation. Details of key team members will soon be available on our website. We can provide additional information upon request.

    2. ICO: We held a closed ICO among our partners to create an initial reserve and test the system. This allowed us to stabilize the token issue, which is backed by reserves in euros.

    3. MiCA Compliance: We are in the process of obtaining all necessary MiCA approvals and will be ready to submit documents once this process is complete.

    4. Financial Institutions: We are in discussions with regulated financial institutions that will assist in the management of euro reserves. Information on these partnerships will be available once the agreements are finalized.

We are ready to provide additional details upon request.

Regards,
Alex Collin

**Comment by supportEURC** [comment]
Dear Trust Wallet team,
Thank you for your questions. Here are brief answers:

    Information about the team: The project team consists of experts with experience in blockchain, finance and legal regulation. Details of key team members will soon be available on our website. We can provide additional information upon request.

    ICO: We held a closed ICO among our partners to create an initial reserve and test the system. This allowed us to stabilize the token issue, which is backed by reserves in euros.

    MiCA Compliance: We are in the process of obtaining all necessary MiCA approvals and will be ready to submit documents once this process is complete.

    Financial Institutions: We are in discussions with regulated financial institutions that will assist in the management of euro reserves. Information on these partnerships will be available once the agreements are finalized.

We are ready to provide additional details upon request.

Regards,
Alex Collin

**Comment by supportEURC** [comment]
@Cryptocool1 @cryptomanz1

**Comment by supportEURC** [comment]
Dear Trust Wallet team,
Thank you for your questions. We would like to inform you that information about the project team has already been added to our website and is available for review.
Regarding contracts with our partners, unfortunately, due to confidentiality conditions we cannot publicly disclose these agreements. However, we are ready to provide the necessary supporting documents as part of private inquiries or as negotiations with our financial partners are finalized.
Thank you for your understanding. We remain open to further cooperation and providing additional information as needed.

**Pull request closed without merging**
