### PR TITLE
Add Dango logo ( BEP20 Token )

### PR DESCRIPTION
**Pull request by Shyamthakur33**

### CODE REVIEW

**Comment by Shyamthakur33** [comment]
@zachzwei, @catenocrypt Plz check if all info correct to add binance smart chain based token

**Comment by Shyamthakur33** [comment]
@catenocrypt Please check, payment already done

**Comment by Iamdeadlyz** [comment]
As per our policy, brand new tokens are not included. There is a minimum requirement of 2500 holder addresses and 5000 transactions (airdropped tokens excluded) in order to filter out scam tokens. See the criteria at (mentioned in the first message by the bot): https://community.trustwallet.com/t/how-to-submit-a-token-logo/3863#how-to-get-approved

This token has below-limit usage yet. This pull request will be put on hold. Please come back to us when all criteria are met.
https://bscscan.com/token/0x0957c57c9eb7744850dcc95db5a06ed4a246236e (23, 380) 7̶6̶5̶,̶ ̶1̶0̶1̶0̶

**Comment by Shyamthakur33** [comment]
@catenocrypt dear sir, Please check again. we have completed 2500 holders and 5000 transfers.

**Comment by Shyamthakur33** [comment]
> As per our policy, brand new tokens are not included. There is a minimum requirement of 2500 holder addresses and 5000 transactions (airdropped tokens excluded) in order to filter out scam tokens. See the criteria at (mentioned in the first message by the bot): https://community.trustwallet.com/t/how-to-submit-a-token-logo/3863#how-to-get-approved
> 
> This token has below-limit usage yet. This pull request will be put on hold. Please come back to us when all criteria are met.
> https://bscscan.com/token/0x0957c57c9eb7744850dcc95db5a06ed4a246236e (23, 380) 7̶6̶5̶,̶ ̶1̶0̶1̶0̶

dear sir, you there plz. now we have 2500 holders and 5000 transfers

**Comment by Iamdeadlyz** [comment]
> > As per our policy, brand new tokens are not included. There is a minimum requirement of 2500 holder addresses and 5000 transactions (airdropped tokens excluded) in order to filter out scam tokens. See the criteria at (mentioned in the first message by the bot): https://community.trustwallet.com/t/how-to-submit-a-token-logo/3863#how-to-get-approved
> > This token has below-limit usage yet. This pull request will be put on hold. Please come back to us when all criteria are met.
> > https://bscscan.com/token/0x0957c57c9eb7744850dcc95db5a06ed4a246236e (23, 380) 7̶6̶5̶,̶ ̶1̶0̶1̶0̶
> 
> dear sir, you there plz. now we have 2500 holders and 5000 transfers

Please read the rules again: https://community.trustwallet.com/t/how-to-submit-a-token-logo/3863#how-to-get-approved
Currently: 23, 554   (̶5̶2̶0̶5̶,̶ ̶5̶7̶3̶6̶)̶

**Comment by Shyamthakur33** [comment]
> > > As per our policy, brand new tokens are not included. There is a minimum requirement of 2500 holder addresses and 5000 transactions (airdropped tokens excluded) in order to filter out scam tokens. See the criteria at (mentioned in the first message by the bot): https://community.trustwallet.com/t/how-to-submit-a-token-logo/3863#how-to-get-approved
> > > This token has below-limit usage yet. This pull request will be put on hold. Please come back to us when all criteria are met.
> > > https://bscscan.com/token/0x0957c57c9eb7744850dcc95db5a06ed4a246236e (23, 380) 7̶6̶5̶,̶ ̶1̶0̶1̶0̶
> > 
> > 
> > dear sir, you there plz. now we have 2500 holders and 5000 transfers
> 
> Please read the rules again: https://community.trustwallet.com/t/how-to-submit-a-token-logo/3863#how-to-get-approved
> Currently: 23, 554 (̶5̶2̶0̶5̶,̶ ̶5̶7̶3̶6̶)̶

Could you please clear? we meet all these conditions 
Fees are paid in BNB or TWT.
Project has a website or white paper.
Has a social media presence.
Detailed Token Information 292
Minimum 2500 token holders and 5,000 transactions (Airdrop tokens excluded**).

**Comment by Iamdeadlyz** [comment]
> > > > As per our policy, brand new tokens are not included. There is a minimum requirement of 2500 holder addresses and 5000 transactions (airdropped tokens excluded) in order to filter out scam tokens. See the criteria at (mentioned in the first message by the bot): https://community.trustwallet.com/t/how-to-submit-a-token-logo/3863#how-to-get-approved
> > > > This token has below-limit usage yet. This pull request will be put on hold. Please come back to us when all criteria are met.
> > > > https://bscscan.com/token/0x0957c57c9eb7744850dcc95db5a06ed4a246236e (23, 380) 7̶6̶5̶,̶ ̶1̶0̶1̶0̶
> > > 
> > > 
> > > dear sir, you there plz. now we have 2500 holders and 5000 transfers
> > 
> > 
> > Please read the rules again: https://community.trustwallet.com/t/how-to-submit-a-token-logo/3863#how-to-get-approved
> > Currently: 23, 554 (̶5̶2̶0̶5̶,̶ ̶5̶7̶3̶6̶)̶
> 
> Could you please clear? we meet all these conditions
> Fees are paid in BNB or TWT.
> Project has a website or white paper.
> Has a social media presence.
> Detailed Token Information
> Minimum 2500 token holders and 5,000 transactions

Read the rules regarding airdrops.

**Comment by Shyamthakur33** [comment]
> > > > > As per our policy, brand new tokens are not included. There is a minimum requirement of 2500 holder addresses and 5000 transactions (airdropped tokens excluded) in order to filter out scam tokens. See the criteria at (mentioned in the first message by the bot): https://community.trustwallet.com/t/how-to-submit-a-token-logo/3863#how-to-get-approved
> > > > > This token has below-limit usage yet. This pull request will be put on hold. Please come back to us when all criteria are met.
> > > > > https://bscscan.com/token/0x0957c57c9eb7744850dcc95db5a06ed4a246236e (23, 380) 7̶6̶5̶,̶ ̶1̶0̶1̶0̶
> > > > 
> > > > 
> > > > dear sir, you there plz. now we have 2500 holders and 5000 transfers
> > > 
> > > 
> > > Please read the rules again: https://community.trustwallet.com/t/how-to-submit-a-token-logo/3863#how-to-get-approved
> > > Currently: 23, 554 (̶5̶2̶0̶5̶,̶ ̶5̶7̶3̶6̶)̶
> > 
> > 
> > Could you please clear? we meet all these conditions
> > Fees are paid in BNB or TWT.
> > Project has a website or white paper.
> > Has a social media presence.
> > Detailed Token Information
> > Minimum 2500 token holders and 5,000 transactions
> 
> Read the rules regarding airdrops.

dear sir, Please understand that before submitting request, we had almost 2500 holders, just few were required. you can our twitter account. we are top project on binance smart chian also we are not new in market. we are already trading on exchange 
https://pancakeswap.info/pair/0x9c7b48c97039110e56461ec90e4a6f5ae22044bc Please help to update our token logo and info.

**Comment by Iamdeadlyz** [comment]
> > > > > > As per our policy, brand new tokens are not included. There is a minimum requirement of 2500 holder addresses and 5000 transactions (airdropped tokens excluded) in order to filter out scam tokens. See the criteria at (mentioned in the first message by the bot): https://community.trustwallet.com/t/how-to-submit-a-token-logo/3863#how-to-get-approved
> > > > > > This token has below-limit usage yet. This pull request will be put on hold. Please come back to us when all criteria are met.
> > > > > > https://bscscan.com/token/0x0957c57c9eb7744850dcc95db5a06ed4a246236e (23, 380) 7̶6̶5̶,̶ ̶1̶0̶1̶0̶
> > > > > 
> > > > > 
> > > > > dear sir, you there plz. now we have 2500 holders and 5000 transfers
> > > > 
> > > > 
> > > > Please read the rules again: https://community.trustwallet.com/t/how-to-submit-a-token-logo/3863#how-to-get-approved
> > > > Currently: 23, 554 (̶5̶2̶0̶5̶,̶ ̶5̶7̶3̶6̶)̶
> > > 
> > > 
> > > Could you please clear? we meet all these conditions
> > > Fees are paid in BNB or TWT.
> > > Project has a website or white paper.
> > > Has a social media presence.
> > > Detailed Token Information
> > > Minimum 2500 token holders and 5,000 transactions
> > 
> > 
> > Read the rules regarding airdrops.
> 
> dear sir, Please understand that before submitting the request, we had almost 2500 holders, just few were required. you can check our Twitter handle. we are a good project on Binance smart chain. we are not new in the market. we are already trading on exchange
> https://pancakeswap.info/pair/0x9c7b48c97039110e56461ec90e4a6f5ae22044bc and going to launch soon swap platform with farming, lending, and staking features which you see on our website. Please help to update our token logo and info. We appreciate for your contionued support.

You are "new" to the market. You recently launched 17 days ago. Anyways, the main argument here is regarding the airdrops. Once again, **read the rules about it**.

**Comment by Shyamthakur33** [comment]
Yes, I have read the rules. Please clear here what you want now from our
side to complete. Looking forward to hear positive response from you.

**Comment by Iamdeadlyz** [comment]
Airdropped tokens are excluded, that's the reason why we can't merge your PR. If you indeed read the rules, then you will see it.

**Comment by Shyamthakur33** [comment]
> Airdropped tokens are excluded, that's the reason why we can't merge your PR. If you indeed read the rules, then you will see it.

so, now we need to increase more holders except airdropers?

**Comment by Iamdeadlyz** [comment]
> > Airdropped tokens are excluded, that's the reason why we can't merge your PR. If you indeed read the rules, then you will see it.
> 
> so, now we need to increase more holders except airdropers?

That is correct.

**Comment by Shyamthakur33** [comment]
Thanks, we will come back to you. Hope, you will respect to my paid fee.

**Comment by Shyamthakur33** [comment]
> > > Airdropped tokens are excluded, that's the reason why we can't merge your PR. If you indeed read the rules, then you will see it.
> > 
> > 
> > so, now we need to increase more holders except airdropers?
> 
> That is correct.

@Iamdeadlyz kindly check now people are buying token from Pancakeswap and we are already getting more holders. Kindly help us to update our logo. Thanks

**Comment by Iamdeadlyz** [comment]
Currently: 29, 2156 `(5̶2̶3̶2̶,̶ ̶7̶3̶5̶9̶)`
Pancakeswap **buyers & holders** were only +6

**Comment by Shyamthakur33** [comment]
> Currently: 29, 2156 `(5̶2̶3̶2̶,̶ ̶7̶3̶5̶9̶)`
> Pancakeswap **buyers & holders** were only +6

How you can say that we just have 6?  How you calculate that?

**Comment by Iamdeadlyz** [comment]
> > Currently: 29, 2156 `(5̶2̶3̶2̶,̶ ̶7̶3̶5̶9̶)`
> > Pancakeswap **buyers & holders** were only +6
> 
> How you can say that we just have 6? How you calculate that?

Exported all transactions, filtered those who bought, removed those who have 0 DANGO.

**Comment by Shyamthakur33** [comment]
> > > Currently: 29, 2156 `(5̶2̶3̶2̶,̶ ̶7̶3̶5̶9̶)`
> > > Pancakeswap **buyers & holders** were only +6
> > 
> > 
> > How you can say that we just have 6? How you calculate that?
> 
> Exported all transactions, filtered those who bought, removed those who have 0 DANGO.

I meant how you know that address is airdroper and that buyer address?

**Comment by Iamdeadlyz** [comment]
> > > > Currently: 29, 2156 `(5̶2̶3̶2̶,̶ ̶7̶3̶5̶9̶)`
> > > > Pancakeswap **buyers & holders** were only +6
> > > 
> > > 
> > > How you can say that we just have 6? How you calculate that?
> > 
> > 
> > Exported all transactions, filtered those who bought, removed those who have 0 DANGO.
> 
> I meant how you know that address is airdroper and that buyer address?

Good question. Most of the holders got it from one address. So, from 23 holders, it increased to 29 since there were 6 buyers and holders. Please focus on making your token more useful, not just airdropping it. No need to rush the process of adding the logo of your token, cheers!

**Pull request merged**
