### PR TITLE
DECASH

### PR DESCRIPTION
**Pull request by vitalismark**

### CODE REVIEW

**Comment by vitalismark** [comment]
PAYMENT MADE

**Comment by vitalismark** [comment]
I've made the payment and it hasn't been detected yet by the system

**Comment by catenocrypt** [comment]
Logo has problems -- 0xA740684C9022dc07540031b10dD57984640bAbef/logo.png:

- size is too large, over 250KB, max is 100KB
- Gimp does not open it
- Tinypng.com cannot open it, so I cannot reduce the size
- background is not transparent

Please fix these.

**Comment by vitalismark** [comment]
> Logo has problems -- 0xA740684C9022dc07540031b10dD57984640bAbef/logo.png:
> 
> * size is too large, over 250KB, max is 100KB
> * Gimp does not open it
> * Tinypng.com cannot open it, so I cannot reduce the size
> * background is not transparent
> 
> Please fix these.

once errors are fixed how do I get it across to you?

**Comment by catenocrypt** [comment]
Edit/replace the file in your forked repository, and then push it.  PR is updated automatically.

**Comment by vitalismark** [comment]
> Edit/replace the file in your forked repository, and then push it. PR is updated automatically.

kindly walk me through the steps, please?

**Comment by zachzwei** [comment]
resubmit new PR https://github.com/trustwallet/assets/pull/2647
This one has conflicts that may cause errors

**Comment by vitalismark** [comment]
logo

**Comment by vitalismark** [comment]
But I've already paid for this, kindly merge the logo for me

**Pull request closed without merging**
