### PR TITLE
Update dnd info.json

### PR DESCRIPTION
**Pull request by dungeonswap**

### CODE REVIEW

**Comment by cryptomanz** [comment]
Hello,
Can your answer some questions?
 • What is the purpose of this token? How will it benefit Trust Wallet users?
 • How is the token being distributed? Are you conducting an airdrop?
 • Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?
 • Is the token listed on a centralized/decentralized exchange?
 • Is a Smart Contract audit completed? Where can we find this information?

**Comment by dungeonswap** [comment]
Hello Nazar,

Thank you for your email. Please find the below for our responses to your
questions:

• What is the purpose of this token? How will it benefit Trust Wallet users?

   - DungeonSwap is a decentralized table-top RPG style web game on the
   Binance Smart Chain with yield farming features and NFTs.The unique feature
   beyond yield-farming is games called "The Dungeon" and "Boss Battleground"
   which user can have fun playing while earning from battle reward.
   - On how it could benefit Trust Wallet users, because many of our gamers
   use trust wallet as their cryptowallet, it will be beneficial for them if
   they can see the logo of our token.

• How is the token being distributed? Are you conducting an airdrop?


   - Currently we are not conducting any airdrop with our $DND token.
   Previously some airdrop was conducted and the holders increased by 300 or
   so. Recently we got trended and new investors come in and so the holder
   addresses reaches 5000+.


• Did you sold the tokens at an Initial Coin Offering (ICO) or a token
presale?


   - No. The token has been put on PancakeSwap yield farm and was sold via
   PancakeSwap decentralized exchange on the BSC (BEP20).


• Is the token listed on a centralized/decentralized exchange?


   - Yes it is on  PancakeSwap decentralized exchange.


• Is a Smart Contract audit completed? Where can we find this information?


   - Our smart contract was audited by Techrate and can be found on:
   https://github.com/TechRate/Smart-Contract-Audits/blob/main/DungeonSwap.pdf


Further questions, please let us know.

**Comment by cryptomanz** [comment]
Hello,
- Can't find  smart contract on your website.

**Comment by dungeonswap** [comment]
Hello Nazar,

Our token address is


0x14c358b573a4cE45364a3DBD84BBb4Dae87af034


It is on our white paper. Thank you.

**Pull request merged**
