### PR TITLE
Included BSC version of the SUPER token.

### PR DESCRIPTION
**Pull request by TimTinkers**
A port of the token information approved via #5661.

### CODE REVIEW

**Comment by TimTinkers** [comment]
Fee sent!

**Comment by catenocrypt** [comment]
As per our policy, brand new tokens are not included, there is a minimum requirement of 2500 holder addresses and 5000 transactions, in order to filter out scam tokens.
See the criteria at (mentioned in the first message by the bot): https://community.trustwallet.com/t/how-to-submit-a-token-logo/3863).
This token has below-limit usage yet (1871 holders). Putting PR on hold for now. Please come back to us when all criteria are met.  Multi-chain and staking tokens may get special treatment, let us know if this is the case. 

https://bscscan.com/token/0x51BA0b044d96C3aBfcA52B64D733603CCC4F0d4D

**Comment by TimTinkers** [comment]
@catenocrypt @zachzwei we currently have over 21,000 holders on Ethereum (https://etherscan.io/token/0xe53EC727dbDEB9E2d5456c3be40cFF031AB40A55) and were already approved for that chain in #5661. We are using BSC as a simple wrapped version of our primary Ethereum coin. We already have our logo on Trust Wallet and are just trying to use the same logo on the BSC chain; we are also trying to avoid scammers here.

This is a multi-chain token and we'd appreciate the special review from you guys here to help protect our users.

**Comment by TimTinkers** [comment]
Never mind, just noticed you guys already merged this one for us. Thanks!

**Comment by catenocrypt** [comment]
This was already merged

**Pull request merged**
