### PR TITLE
Change DIA logo to new version

### PR DESCRIPTION
**Pull request by kaythxbye**
The DIA logo was updated to its new version

### CODE REVIEW

**Comment by Cryptocool1** [comment]
I recommend to add “defi” tag

**Comment by kaythxbye** [comment]
Ah thank you @Cryptocool1 
Is there a list of allowed tags? I didn't find one yet but maybe I looked in the wrong places.

**Comment by Cryptocool1** [comment]
> Ah thank you @Cryptocool1
> Is there a list of allowed tags? I didn't find one yet but maybe I looked in the wrong places.

Yes, please find them here: https://developer.trustwallet.com/developer/listing-new-assets/repository_details

**Comment by kaythxbye** [comment]
Please reopen the PR

**Pull request merged**
