### PR TITLE
Add GREEN

### PR DESCRIPTION
**Pull request by Flarzival**

### CODE REVIEW

**Comment by Iamdeadlyz** [comment]
Question, why do most of the token holders got their GREEN tokens from 1 address? 
Specifically from `0x766A983B6Db3F9FA404f19CE0c00aa53Fd4b7431`

**Comment by Flarzival** [comment]
It is a decentralized community action.  Once green entered into phase 2, we 100% decentralized with our node network of over 25,000 nodes across the world. Those rewards power the node network that generate applications for our users to effectively use the green blockchain. To save on power, bundle with solar installs, etc...

**Comment by Flarzival** [comment]
@Iamdeadlyz any update here?

**Comment by Iamdeadlyz** [comment]
> It is a decentralized community action. Once green entered into phase 2, we 100% decentralized with our node network of over 25,000 nodes across the world. Those rewards power the node network that generate applications for our users to effectively use the green blockchain. To save on power, bundle with solar installs, etc...

Please provide more details and proofs regarding this kind of distribution.

**Comment by Flarzival** [comment]
Thanks for your questions, let’s get on a zoom call to go through etherscan and answer any questions. The green blockchain has been live since 2018.

**Comment by Iamdeadlyz** [comment]
> Thanks for your questions, let’s get on a zoom call to go through etherscan and answer any questions. The green blockchain has been live since 2018.

You can answer here, no need for a zoom call.

**Review by vechiverme2050 — COMMENTED** [review]
H

**Comment by Iamdeadlyz** [comment]
Closing due to inactivity. You can comment on this thread so we can discuss and re-open this PR.

**Pull request closed without merging**
