### PR TITLE
Add Memeflate (BEP20)

### PR DESCRIPTION
**Pull request by Mrmflate**
Adding info for BEP20 token 'Memeflate'.

PR created by <a href="https://assets.trustwallet.com">TW Assets Management</a>

### CODE REVIEW

**Comment by ramsty** [comment]
Hi,
Please follow the rules for adding token, your logo should be a full screen 256*256 px. Background should be transparent.
Example:
https://community.trustwallet.com/t/how-to-submit-a-token-logo/3863

**Comment by Mrmflate** [comment]
input-onlinepngtools

**Comment by Mrmflate** [comment]
I believe this is the right size i am not sure if this is how to submit the new size of the logo to you.

**Comment by cryptomanz** [comment]
• What is the purpose of this token? How will it benefit Trust Wallet users?
 • How is the token being distributed? Are you conducting an airdrop?
 • Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?
 • Is the token listed on a centralized/decentralized exchange?
 • Is a Smart Contract audit completed? Where can we find this information?

**Comment by Mrmflate** [comment]
The use case of the token it is crypto market place project designed to offer buying and selling of services global and local.
The benefits to holders in trust wallets is memeflates 1 to 30% redistribution.

Currently exchanges.

https://pancakeswap.finance/info/token/0xafe3321309a994831884fc1725f4c3236ac79f76

https://latoken.com/exchange/MFLATE_mUSDT

https://azbit.com/exchange/MFLATE_USDT

The token was offered at presale

The contract has had a free tech rate audit to date and awaiting full.

**Comment by Cryptocool1** [comment]
awaiting for smart contract audit, on hold for now

**Comment by Mrmflate** [comment]
Hi. I am talking with tech rate about full audit i currently dont know how long the process takes, will this remain on hold until i submit.

**Comment by Cryptocool1** [comment]
sure, it will be on hold until we get the audit from you.

**Comment by Mrmflate** [comment]
Link below to full tech rate audit 

https://www.dropbox.com/s/ds6z6h4mnczhkv1/memeflate%20full%20smart%20contract%20security%20audit.pdf?dl=0

**Pull request merged**
