### PR TITLE
 add Token Logo & Description

### PR DESCRIPTION
**Pull request by beynbeyn**
Dear TrustWallet Team. Please add the Token Logo & Description. Hopefully I did everything correct, if not please let me know. Thanks :)

### CODE REVIEW

**Comment by catenocrypt** [comment]
As per our policy, brand new tokens are not included, there is a minimum requirement of 2500 holder addresses and 5000 transactions, in order to filter out scam tokens.
See the criteria at (mentioned in the first message by the bot): https://community.trustwallet.com/t/how-to-submit-a-token-logo/3863).
This token has low usage yet (385). Putting PR on hold for now. Please come back to us when all criteria are met.  Multi-chain and staking tokens may get special treatment, let us know if this is the case. 

https://etherscan.io/token/0x19A2cF2A1B2f76e52E2b0c572bD80A95B4Fa8643

**Comment by beynbeyn** [comment]
Dear TrustWallet Team

The FYZNFT is a new coin, but from an established project: Fyooz (FYZ). We have been approved about half a year ago.

The FYZNFT Token had about 2.5M volume in the last week. Please see: https://info.uniswap.org/token/0x19a2cf2a1b2f76e52e2b0c572bd80a95b4fa8643

We have a webpage and whitepaper dedicated to this token, which you can find here: https://www.fyooz.io/fyznft/

Also please find here a Coindesk Article around the release of this token:
https://www.coindesk.com/social-token-app-fyooz-offers-chance-to-play-beer-pong-with-rap-artist-post-malone

While we understand, that you have strict criteria, we are asking you to reconsider.

**Comment by beynbeyn** [comment]
Hi

There has been many more transactions and many more holders by now. Currently Uniswap 24h Volume is at 1.7M
Could you please review it again?

Thank you!

**Comment by catenocrypt** [comment]
Current value is 795, higher then before, but well below limit.

**Comment by BeerTokenOfficial** [comment]
Is there a telegram I can message you on?

**Pull request merged**
