### PR TITLE
Add Volt Inu (BEP20)

### PR DESCRIPTION
**Pull request by VoltInu**
Adding info for BEP20 token 'Volt Inu'.

PR created by <a href="https://assets.trustwallet.com">TW Assets Management</a>

### CODE REVIEW

**Comment by VoltInu** [comment]
The fee has already been paid in the PR #18525.

According to your information it can be reused for this PR.

**Comment by Cryptocool1** [comment]
can you please add the tags and links?
https://developer.trustwallet.com/assets/requirements

**Comment by VoltInu** [comment]
Here you go the:

Twitter link: https://twitter.com/VoltInuOfficial
Telegram link: https://t.me/VoltInuOfficial
Website link: https://voltinu.in/
Explorer link: https://bscscan.com/token/0x07EC61Ae90860641972E9B41A706325a1E928BF8

Tags: Memes

All these information were already provided on the trustwallet website.

In the meantime, can you let me know if the ERC20 version submitted in the PR #18916 has been updated and finalized or if there is anything left to do?

Many thanks.

**Comment by VoltInu** [comment]
It looks like 2 checks have failed. Can you let me know what we do have to do?

**Comment by cryptomanz** [comment]
• What is the purpose of this token? How will it benefit Trust Wallet users?
 • How is the token being distributed? Are you conducting an airdrop?
 • Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?
 • Is the token listed on a centralized/decentralized exchange?
 • Is a Smart Contract audit completed? Where can we find this information?

**Comment by cryptomanz** [comment]
• Is a Smart Contract audit completed? Where can we find this information?

**Comment by VoltInu** [comment]
• What is the purpose of this token? How will it benefit Trust Wallet users? --> The primary aim of the token is to act as a FaaS by investing into NFTs, Altcoins and staking/farming. Holders will benefit from it since the profits are used to buyback and burn VOLT, thus creating a rising price floor. On top of that, we will also release our first P2E game within the next 10 days that will allow any existing project to compete to earn buybacks and burns. 
We are also working on a SWAP and an automated social activity rewarding system. Both should be delivered in Q2/early Q3 2022.
• How is the token being distributed? Are you conducting an airdrop? We made a fair launch on ETH and then bridged to BSC. 100% of the supply was allocated to the ETH liquidity pool at launch.
• Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale? No.
• Is the token listed on a centralized/decentralized exchange? We are listed on uniswap, pancakeswap, hotbit, BKEX, LBANK, XT.com and Bitmart.
• Is a Smart Contract audit completed? Where can we find this information? Yes, you can find the audit report here: https://solidity.finance/audits/VoltInu/

**Pull request merged**
