### PR TITLE
Add Sekuya (BEP20)

### PR DESCRIPTION
**Pull request by sekuyatoken**
Adding info for BEP20 token 'Sekuya'.

PR created by <a href="https://assets.trustwallet.com">TW Assets Management</a>

### CODE REVIEW

**Comment by Cryptocool1** [comment]
• What is the purpose of this token? How will it benefit Trust Wallet users?
 • How is the token being distributed? Are you conducting an airdrop?
 • Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?
 • Is the token listed on a centralized/decentralized exchange?
 • Is a Smart Contract audit completed? Where can we find this information?

**Comment by sekuyatoken** [comment]
> • What is the purpose of this token? How will it benefit Trust Wallet users? • How is the token being distributed? Are you conducting an airdrop? • Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale? • Is the token listed on a centralized/decentralized exchange? • Is a Smart Contract audit completed? Where can we find this information?

• What is the purpose of this token? How will it benefit Trust Wallet users?
A native currency of Sekuya Multiverse with a goal to connect communities around the world. It can benefit the Trust Wallet users by easier to look for the token.

• How is the token being distributed? Are you conducting an airdrop?
50% burn, 48% public, 2% dev, and we did an airdrop also during our birthday event

• Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?
Yes through ICO

• Is the token listed on a centralized/decentralized exchange?
Currently on Pancakeswap and will be listed soon on Centralized Exchange

• Is a Smart Contract audit completed? Where can we find this information?
The first contract audit was with Dessert Finance result in low risk, after migration the current contract scanned zero remarks by Gopluslabs. 
https://gopluslabs.io/token-security/56/0x71d03A620646f8b572282Ef39228D36Add67ee20

**Comment by Cryptocool1** [comment]
Please send your Dessert Finance smart contract audit here

**Comment by sekuyatoken** [comment]
> Please send your Dessert Finance smart contract audit here

https://dessertswap.finance/audits/Sekuya-BSC-Audit-15862500.pdf

**Pull request merged**
