### PR TITLE
Add TC token logo and info

### PR DESCRIPTION
**Pull request by Tayfuntaner**
We want our TTcoin Investors and users to be published in secure wallets like you.

contact@ttcoin.info
Telegram: @tayfun_ttcoin

https://ttcoin.info

### CODE REVIEW

**Comment by Tayfuntaner** [comment]
https://explorer.binance.org/tx/5DD03F9AA47A2B5B596DFC827CC74165211F5189AB1475F7F213501132E6528A

Payments have been made.

**Comment by cryptomanz** [comment]
Hello,
Can your answer some questions?
• What is the purpose of this token? How will it benefit Trust Wallet users?
 • How is the token being distributed? Are you conducting an airdrop?
 • Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?
 • Is the token listed on a centralized/decentralized exchange?
 • Is a Smart Contract audit completed? Where can we find this information?

**Comment by Tayfuntaner** [comment]
> Merhaba,
> bazı soruları cevaplayabilir misiniz?
> • Bu simgenin amacı nedir? Trust Wallet kullanıcılarına nasıl fayda sağlayacak?
> • Belirteç nasıl dağıtılıyor? Airdrop yapıyor musunuz?
> • Jetonları İlk Para Teklifinde (ICO) veya jeton ön satışında sattınız mı?
> • Simge, merkezi/merkezi olmayan bir borsada listeleniyor mu?
> • Akıllı Sözleşme denetimi tamamlandı mı? Bu bilgiyi nerede bulabiliriz?

Our aim is to use our Token as a payment method on TTcoin Brands and products.

It is listed on 3 exchanges in total.

Most of the details are available on our website.

The airdrop is happening now, it will end on December 20.

It has been downloaded 2 million times on Google Play.

You can find all the details on our website. It is published on 2 sites such as Coinmarketcap.

Its monthly volume is more than 20 thousand dollars.

No ICO has been made, it has started to be listed.

https://tronscan.org/#/token20/TCMwzYUUCxLkTNpXjkYSBgXgqXwt7KJ82y
https://tronscan.org/#/contract/TCMwzYUUCxLkTNpXjkYSBgXgqXwt7KJ82y

https:/ttcoin.info

https://www.koinbazar.com/trade/TC-USDT
https://vindax.com/exchange-base.html?symbol=TC_USDT
https://bololex.com/trading/?symbol=TRX-USDT
https://coinsbit.io/trade_classic/TC_USDT (There will be listing on September 20)
https://p2pb2b.io/tr/trade/TC_USDT (There will be listing on September 30)

https://coinpaprika.com/coin/tc-ttcoin/
https://www.livecoinwatch.com/price/TTCOIN-TC

https://play.google.com/store/apps/details?id=com.ttcoin.tc

**Comment by Tayfuntaner** [comment]
> Hello,
> Can your answer some questions?
> • What is the purpose of this token? How will it benefit Trust Wallet users?
> • How is the token being distributed? Are you conducting an airdrop?
> • Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?
> • Is the token listed on a centralized/decentralized exchange?
> • Is a Smart Contract audit completed? Where can we find this information?

<>

Name : TTCOIN
Symbol : TC
Max. Reserve : 6,000,000,000
Circulating Supply : 331.997.050,00
Decimal : 4
Blockchain : TRC20
Creation Date : 24.03.2021

Token Address: https://tronscan.io/#/token20/TCMwzYUUCxLkTNpXjkYSBgXgqXwt7KJ82y
Smart Contract: https://tronscan.io/#/contract/TCMwzYUUCxLkTNpXjkYSBgXgqXwt7KJ82y

Web site : https://ttcoin.info
Team: https://www.ttcoin.info/team
About: https://www.ttcoin.info/about-us 
Whitepaper: https://edee0421-9e27-482f-bd0c-692eaef405b5.filesusr.com/ugd/5d6dff_8f34347dcc9c4d13a78c09760479d7ee.pdf
Google Play : https://play.google.com/store/apps/details?id=com.ttcoin.tc

https://coinpaprika.com/coin/tc-ttcoin/
https://www.livecoinwatch.com/price/TTCOIN-TC

Listed Exchanges:
KoinBazar
INR:https://www.koinbazar.com/trade/TC-USDT
USDT.https://www.koinbazar.com/trade/TC-INR

CoinsBit (There will be listing on September 20)
ETH:https://coinsbit.io/trade_classic/TC_ETH
USDT:https://coinsbit.io/trade_classic/TC_USDT

VinDAX
ETH:https://vindax.com/exchange-base.html?symbol=TC_ETH
USDT:https://vindax.com/exchange-base.html?symbol=TC_USDT

Bololex
BOLO:https://bololex.com/trading/?symbol=TC-BOLO
USDT:https://bololex.com/trading/?symbol=TC-USDT

----------------
Social Media

Telegram Global: t.me/ttcoinworld
Telegram Channel : t.me/ttcoinofficial
​​​​​​​Telegram English Grup : t.me/ttcoinenglish
​​​​​​​​​​​​​​Telegram Turkey Grup : t.me/ttcointurkey
​​​​​​​​​​​​​​Telegram India Grup : t.me/ttcoinindia
Telegram Korea Grup : t.me/ttcoinkorea
Telegram Pakistan Grup : t.me/ttcoinpakistan
​​​​​​​Telegram Indonesia Grup : t.me/ttcoinindonesia
​​​​​​​Telegram Vietnamese Grup : t.me/ttcoinvietnamese

Facebook: https://facebook.com/ttcoinofficial
Twitter: https://twitter.com/ttcoinofficial
Instagram: https://instagram.com/ttcoinofficial
YouTube: https://www.youtube.com/channel/UCw4ctJY-VD12hwHuHl1D9kw
Github: https://github.com/TTCOIN-TC/

**Comment by cryptomanz** [comment]
• Is a Smart Contract audit completed? Where can we find this information?

**Comment by Tayfuntaner** [comment]
> • Is a Smart Contract audit completed? Where can we find this information?

the contract address is already verified, we have confirmed it in the Tron infrastructure.  If you look in detail, you can see the contract address code.  If I am wrong, you can give me an example.

**Comment by cryptomanz** [comment]
Please follow the rules to add token, we require: "A full token audit is completed by reputable security audit groups. Partial audits are subject for require." 
Exemple:
https://developer.trustwallet.com/assets/requirements
Screenshot 2021-09-16 at 18 48 58

**Comment by Tayfuntaner** [comment]
> Please follow the rules to add token, we require: "A full token audit is completed by reputable security audit groups. Partial audits are subject for require."
> Exemple: https://developer.trustwallet.com/assets/requirements
> Screenshot 2021-09-16 at 18 48 58

I wrote every detail including the logo, we are listed on 4 exchanges and we are on 2 websites like coinmarketcap.  We will be on coinmarketcap and coinecko soon.  tell me where is the mistake.  It is available in close to 7 thousand addresses and will be in 1 million accounts by December.

**Comment by Tayfuntaner** [comment]
> Please follow the rules to add token, we require: "A full token audit is completed by reputable security audit groups. Partial audits are subject for require."
> Exemple: https://developer.trustwallet.com/assets/requirements
> Screenshot 2021-09-16 at 18 48 58

I shared dozens of information and links above, including the information I added in the info.json file on Github.

More than 2 million users want to keep their Tokens in a safe place until December.

We are a corporate company and we will sign dozens of projects. We spend 4 TRX per day for each user. A scam project does not do this, our contract is already approved on the tron ​​network. You listed dozens of tron ​​tokens, I thought you were experienced.

**Comment by Cryptocool1** [comment]
> > Please follow the rules to add token, we require: "A full token audit is completed by reputable security audit groups. Partial audits are subject for require."
> > Exemple: https://developer.trustwallet.com/assets/requirements
> > Screenshot 2021-09-16 at 18 48 58
> 
> I shared dozens of information and links above, including the information I added in the info.json file on Github.
> 
> More than 2 million users want to keep their Tokens in a safe place until December.
> 
> We are a corporate company and we will sign dozens of projects. We spend 4 TRX per day for each user. A scam project does not do this, our contract is already approved on the tron ​​network. You listed dozens of tron ​​tokens, I thought you were experienced.

Sorry, we asking you only about smart contract audit. If you have, can you send it here?

**Comment by Tayfuntaner** [comment]
> > > Please follow the rules to add token, we require: "A full token audit is completed by reputable security audit groups. Partial audits are subject for require."
> > > Exemple: https://developer.trustwallet.com/assets/requirements
> > > Screenshot 2021-09-16 at 18 48 58
> > 
> > 
> > I shared dozens of information and links above, including the information I added in the info.json file on Github.
> > More than 2 million users want to keep their Tokens in a safe place until December.
> > We are a corporate company and we will sign dozens of projects. We spend 4 TRX per day for each user. A scam project does not do this, our contract is already approved on the tron ​​network. You listed dozens of tron ​​tokens, I thought you were experienced.
> 
> Sorry, we asking you only about smart contract audit. If you have, can you send it here?

Sorry, I don't quite understand, can you give me an example?  I have to notify my company please help me.

https://tronscan.org/#/transaction/6220d7d3d38c44d7fa789bfa5fa9889a06ecddc74f31824ff424e16ca18a3b76

https://tronscan.org/#/contract/TCMwzYUUCxLkTNpXjkYSBgXgqXwt7KJ82y/code

**Comment by Cryptocool1** [comment]
Here is the example of smart contract audit: https://www.certik.org/projects/binance

**Comment by Cryptocool1** [comment]
Here is another example: https://github.com/pessimistic-io/audits/blob/main/xDao%20Security%20Analysis%20by%20Pessimistic.pdf
performed by Hacken

**Comment by Tayfuntaner** [comment]
> Here is the example of smart contract audit: https://www.certik.org/projects/binance

https://coinpaprika.com/coin/tc-ttcoin/
https://www.livecoinwatch.com/price/TTCOIN-TC

**Comment by Tayfuntaner** [comment]
> Here is another example: https://github.com/pessimistic-io/audits/blob/main/xDao%20Security%20Analysis%20by%20Pessimistic.pdf
> performed by Hacken

Whitepaper: https://edee0421-9e27-482f-bd0c-692eaef405b5.filesusr.com/ugd/5d6dff_8f34347dcc9c4d13a78c09760479d7ee.pdf

**Comment by Cryptocool1** [comment]
I'm asking you only for audit)

**Comment by Cryptocool1** [comment]
Do you have it?

**Comment by Tayfuntaner** [comment]
> I'm asking you only for audit)

I'll check again and get back to you tomorrow.

**Comment by Tayfuntaner** [comment]
> Do you have it?

Yes I just realized, there is no Smart contract Security Analysis.  how can i achieve this?  Or how can we do it.

**Comment by Cryptocool1** [comment]
> > Do you have it?
> 
> Yes I just realized, there is no Smart contract Security Analysis. how can i achieve this? Or how can we do it.

that is not our work. you should write directly to them

**Comment by Tayfuntaner** [comment]
> > > Do you have it?
> > 
> > 
> > Yes I just realized, there is no Smart contract Security Analysis. how can i achieve this? Or how can we do it.
> 
> that is not our work. you should write directly to them

Ok, no problem, I contacted the Certik team.

**Comment by Tayfuntaner** [comment]
> > > Do you have it?
> > 
> > 
> > Yes I just realized, there is no Smart contract Security Analysis. how can i achieve this? Or how can we do it.
> 
> that is not our work. you should write directly to them

https://www.sooho.io/
Do you accept this site?

**Comment by Cryptocool1** [comment]
> > > > Do you have it?
> > > 
> > > 
> > > Yes I just realized, there is no Smart contract Security Analysis. how can i achieve this? Or how can we do it.
> > 
> > 
> > that is not our work. you should write directly to them
> 
> https://www.sooho.io/
> Do you accept this site?

the Certik is better

**Comment by Tayfuntaner** [comment]
> > > > > Do you have it?
> > > > 
> > > > 
> > > > Yes I just realized, there is no Smart contract Security Analysis. how can i achieve this? Or how can we do it.
> > > 
> > > 
> > > that is not our work. you should write directly to them
> > 
> > 
> > https://www.sooho.io/
> > Do you accept this site?
> 
> the Certik is better

https://odin.sooho.io/result/4e600498fe5055aaa73d5e87b6f5d03e
Certik team will be back late. I threw this out in case it's helpful to you. If the Certik team writes to me, I will send it to you.

**Comment by Cryptocool1** [comment]
pleas create new PR when smart contract audit will be ready. Make are to mention this PR so the fee can be reused

**Comment by Tayfuntaner** [comment]
> Akıllı sözleşme denetimi hazır olduğunda lütfen yeni PR oluşturun. Ücretin yeniden kullanılabilmesi için bu PR'dan bahsettiğinizden emin olun.

Okey

**Comment by Tayfuntaner** [comment]
https://github.com/TTCOIN-TC/tc/blob/main/Smart-Contract-Documentation/Smart%20Contract%20Audit%20Report.pdf

**Pull request closed without merging**
