### PR TITLE
FTS 

### PR DESCRIPTION
**Pull request by jetfuelfinance**

### CODE REVIEW

**Comment by jetfuelfinance** [comment]
Hello,

The fee is paid. Please review.

**Comment by jetfuelfinance** [comment]
Hello,

Please provide an update.

**Comment by catenocrypt** [comment]
As per our policy, brand new tokens are not included, there is a minimum requirement of 2500 holder addresses and 5000 transactions, in order to filter out scam tokens.
See the criteria at (mentioned in the first message by the bot): https://community.trustwallet.com/t/how-to-submit-a-token-logo/3863).
This token has below-limit usage yet (908 holders). Putting PR on hold for now. Please come back to us when all criteria are met.  Multi-chain and staking tokens may get special treatment, let us know if this is the case. 

https://bscscan.com/token/0x4437743ac02957068995c48E08465E0EE1769fBE

**Comment by jetfuelfinance** [comment]
Hi.

We have 21,000 transfers. Right now a majority of the holders have placed
the FTS token in an lp or single staking so the bscscan holder data isn't
reflective of reality.

**Pull request merged**
