### PR TITLE
Add ELONBALLS (BEP20)

### PR DESCRIPTION
**Pull request by Blietje**
Adding info for BEP20 token 'ELONBALLS'.

PR created by <a href="https://assets.trustwallet.com">TW Assets Management</a>

### CODE REVIEW

**Comment by Cryptocool1** [comment]
Please create new PR, follow doc https://community.trustwallet.com/t/how-to-submit-a-token-logo/3863
You may want to try our Assets app in beta; go to https://assets.trustwallet.com, log on with Github, enter contract ID, logo and some additional info, and it will create a PR for you.
See https://community.trustwallet.com/t/how-to-submit-a-token-logo-using-assets-app/82957.

**Comment by Blietje** [comment]
@Cryptocool1 I would like to reopen this and I would like a refund.

Your new requirements are undoable and we didn't apply with those requirements. Refunding isn't normal from your end, but you changed the requirements so we would like a feedback. Please contact me asap in order to do the refund.

**Comment by Cryptocool1** [comment]
did you pay for this PR?

**Comment by Blietje** [comment]
Yes

**Comment by Blietje** [comment]
https://explorer.binance.org/tx/8FEFADBBDFF01E9F393E7F667CB430D9EDBB8AEBDB7798C306B344BA1898A0DC

**Comment by Cryptocool1** [comment]
CB9ADB5D-1A33-4D1A-B5E5-51F29AA35D1E

**Comment by Blietje** [comment]
You changed the requirements.....

**Comment by Blietje** [comment]
So again.

You closed this PR and after that you changed the requirements. It's impossible for us to get it. I really would like a refund asap @Cryptocool1

**Pull request closed without merging**
