### PR TITLE
Add BitFloki (BEP20)

### PR DESCRIPTION
**Pull request by adminbitfloki**
Adding info for BEP20 token 'BitFloki'.

PR created by <a href="https://assets.trustwallet.com">TW Assets Management</a>

### CODE REVIEW

**Comment by adminbitfloki** [comment]
Dear Trustwallet Team,

We would like to update our info on Trust wallet. Please have a look in our Website where we include all the information about our project including Audit link, Integrations, listings and many other things: https://www.bitfloki.io/

BFLOKI is currently listed on MEXC.COM and Pancakeswap

MEXC link: https://www.mexc.com/exchange/BFLOKI_USDT

PANCAKESWAP link: https://pancakeswap.finance/swap?outputCurrency=0x79CDc9cA057E16dFfd45BD803491f328f49e1762

Our BscScan information link :  https://bscscan.com/token/0x79cdc9ca057e16dffd45bd803491f328f49e1762#tokenInfo

Our data is available on Coinmarketcap, Coingecko, dextool and Metamask.

We have recently announced partnership with many projects you can find it on our socials.

As there is no refund, before paying the fee, we want make sure our token fulfill the minimum circulation and other criteria.

please check everything so we can process payment.

**Comment by cryptomanz1** [comment]
• What is the purpose of this token? How will it benefit Trust Wallet users?
 • How is the token being distributed? Are you conducting an airdrop?
 • Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?
 • Is a Smart Contract audit completed? Where can we find this information?

**Comment by adminbitfloki** [comment]
1. The purpose of BitFloki is to create a community-driven cryptocurrency ecosystem that fosters financial inclusivity and empowers its users. BitFloki aims to provide a decentralized platform where individuals can participate in various activities such as trading, staking, and community engagement. Additionally, BitFloki may serve as a means of facilitating transactions, promoting adoption, and supporting charitable initiatives within its community. Ultimately, BitFloki endeavors to offer its users opportunities for financial growth and empowerment while fostering a vibrant and supportive community.

2. No we didn’t do any specific airdrop but our token is available on DEX(Pancakeswap) & CEX(Mexc.com)

Additionally BFLOKI will list on another centralised exchange XT.com on 15th April.

Links: 

https://www.mexc.com/exchange/BFLOKI_USDT

https://pancakeswap.finance/swap?outputCurrency=0x79cdc9ca057e16dffd45bd803491f328f49e1762

https://xtsupport.zendesk.com/hc/en-us/articles/31042547390617-XT-COM-Announcement-on-Launching-BFLOKI-bitFloki

3. No we didn't organise any presale/IDO/private sale or ICO but we did KOL round to big influencers for marketing purposes.

4. Yes our Smart Contract audit is completed. You can find it here : https://coinsult.net/projects/bitfloki/

**Comment by adminbitfloki** [comment]
Dear team,

We are waiting for update. We have completed payment and required details.

**Comment by adminbitfloki** [comment]
Dear team,

We have fulfilled all the requirements by Trustwallet. it’s been more than 48 hours since We have completed our payment and details. but still not received any response yet.

please update our token on Trustwallet asap.

thanks and regards.

**Comment by cryptomanz1** [comment]
We require smart contract audit from reputable companies. Please see https://developer.trustwallet.com/listing-new-assets/requirements

**Comment by adminbitfloki** [comment]
> We require smart contract audit from reputable companies. Please see https://developer.trustwallet.com/listing-new-assets/requirements

Can you please name some reputable smart contract audit companies that are accepted by Trust wallet? It would be really helpful.

**Comment by Cryptocool1** [comment]
Hello, it can be Techrate,  Certik , Hacken, dessert Finance

**Comment by Cryptocool1** [comment]
Hello, feel free to come back to us once audit is done. Make sure to mention this PR so the fee can be reused

**Comment by adminbitfloki** [comment]
here is audit report link: https://github.com/TechRate/Smart-Contract-Audits/blob/main/April__2024/bitFloki.pdf

**Pull request closed without merging**
