### PR TITLE
Add BabyWhiteTiger logo and info

### PR DESCRIPTION
**Pull request by babywhitetiger**

### CODE REVIEW

**Comment by cryptomanz** [comment]
As per our policy, brand new tokens are not included, there is a minimum requirement of 2500 holder addresses and 5000 transactions, in order to filter out scam tokens.
See the criteria at (mentioned in the first message by the bot): https://community.trustwallet.com/t/how-to-submit-a-token-logo/3863).

**Comment by babywhitetiger** [comment]
> 
> 
> As per our policy, brand new tokens are not included, there is a minimum requirement of 2500 holder addresses and 5000 transactions, in order to filter out scam tokens.
> See the criteria at (mentioned in the first message by the bot): https://community.trustwallet.com/t/how-to-submit-a-token-logo/3863).

Hello and thank you for the response. Just to clarify, do you not list new tokens? Our token already has more than 2500 holders and 5000 transactions.

**Comment by babywhitetiger** [comment]
Our project is releasing a set of NFT's linked to our project and we already have met the 2500 holders and 5000 transactions criteria.

**Comment by babywhitetiger** [comment]
We are also listed on Coin Gecko: https://www.coingecko.com/en/coins/babywhitetiger

**Comment by Cryptocool1** [comment]
The submission will be on hold until the requirements have been met.

**Comment by Cryptocool1** [comment]
Please create new PR when all criteria are met. make sure to mention this PR, so the fee can be reused.

**Pull request closed without merging**
