### PR TITLE
Add TW logo and info for LunaDoge (LOGE)

### PR DESCRIPTION
**Pull request by LunaDogeFinance**
Adding the logo and info for LunaDoge to TW.

### CODE REVIEW

**Comment by LunaDogeFinance** [comment]
Hi,

This is the LunaDoge team. Thank you for considering our request. We would like to ask one question, the BEP-20 / BSC repo doesn't seem to exist so we included our token in the Ethereum Asset folder. The PR summary for the info.json file refers to etherscan and based on etherscan we have 0 holders and 0 txs. This is a BEP-20 project with 6,000 holders and over 15,000 transactions. If we need to make a new request in a different folder please let us know!

Best regards,
LunaDoge

**Comment by Cryptocool1** [comment]
Corrections needed:
 -ExplorerUrl incorrect, should be standard https://etherscan.io/token/0xB99172949554E6C10c28c880eC0306d2A9d5C753, not https://bscscan.com/token/0xb99172949554e6c10c28c880ec0306d2a9d5c753
- Id field does not match contract, should be 0xB99172949554E6C10c28c880eC0306d2A9d5C753, not 0xb99172949554e6c10c28c880ec0306d2a9d5c753. Please rename.
-Field 'research' is not needed, please remove it.

**Comment by Cryptocool1** [comment]
Correction needed:
This is a BEp20 token, correct folder is blockchains/smartchain/assets. Please correct.

**Comment by catenocrypt** [comment]
Correction needed:  Logo file is under Ethereum folder, while the info is under smartchain folder.  Please move Logo to the smartchain folder as well.

image

**Comment by Cryptocool1** [comment]
Please come back to us when all criteria are met.
When creating new PR, mention this PR, so that fee can be reused, and not paid again.

**Pull request closed without merging**
