### PR TITLE
Add JACY (JACY) (ERC20)

### PR DESCRIPTION
**Pull request by jacyToken**
Adding info for ERC20 token 'JACY (JACY)'.

PR created by <a href="https://assets.trustwallet.com">TW Assets Management</a>

### CODE REVIEW

**Comment by cryptomanz** [comment]
As per our policy, brand new tokens are not included, there is a minimum requirement of 10,000 holder addresses and 20,000 transactions, in order to filter out scam tokens.
See the criteria at : https://developer.trustwallet.com/assets/requirements .

**Comment by jacyToken** [comment]
@cryptomanz  Please check our Whitepaper where you will find interesting informations regarding our history and future.
This token is not a scam token. Its V1 was abandoned by dev then community took it over and recently migration was succesful to a V2 as you can see in all the links.
Per your policy, I thought that requirement was subject to a review like I saw with others tokens in here.

**Comment by cryptomanz** [comment]
can you send an official announcement about migration ?

**Comment by jacyToken** [comment]
On the website there is a popup regarding the announcement.
Here is the post on reddit : https://www.reddit.com/r/JacyToken/comments/rzbg3n/migration_complete/
On twitter when migration started : https://twitter.com/JacyToken/status/1479075804650876935?s=20
and when migration was complete : https://twitter.com/JacyToken/status/1479936760339652618?s=20

**Comment by Cryptocool1** [comment]
What is your old contract address ?

**Comment by jacyToken** [comment]
It is : 0x08f2991a6eff2671cf791b82aeae64fbbfdd0633

**Comment by Cryptocool1** [comment]
please come back to us when all criteria are met

**Comment by jacyToken** [comment]
@Cryptocool1 Regarding the number of holders , I explained above the utility, history and future of this token to @cryptomanz . I thought the only thing missing now was the payment?

**Comment by Cryptocool1** [comment]
I can't see the token with this address: 0x08f2991a6eff2671cf791b82aeae64fbbfdd0633

**Comment by jacyToken** [comment]
That's the old token which you can see in etherscan : https://etherscan.io/token/0x08f2991a6eff2671cf791b82aeae64fbbfdd0633
On coingecko and coinmarketcap, it says that the coing has been migrated : 
`Jacy has migrated from https://etherscan.io/token/0x08f2991a6eff2671cf791b82aeae64fbbfdd0633 to https://etherscan.io/token/0x916c5de09cf63f6602d1e1793fb41f6437814a62. Read more at https://twitter.com/JacyToken/status/1479936760339652618.
`

**Comment by Cryptocool1** [comment]
submission looks good, awaiting for fee payment

**Comment by jacyToken** [comment]
> submission looks good, awaiting for fee payment

Payment fulfilled.

**Comment by Cryptocool1** [comment]
You logo file should be full screen size. Please change

**Comment by jacyToken** [comment]
> You logo file should be full screen size. Please change

You mean 256*256 but not rounded and more square one or by full size a bigger resolution?

**Comment by jacyToken** [comment]
> You logo file should be full screen size. Please change

Is it good now?

**Pull request merged**
