### PR TITLE
Add files via upload

### PR DESCRIPTION
**Pull request by jetfuelfinance**
This PR is being closed due to inactivity. If you wish to continue, please have us reopen the PR before sending your payment.
Do NOT send payments for closed PR, as the fee may by lost!
  (60 vs. 60 hrs)

### CODE REVIEW

**Comment by catenocrypt** [comment]
As per our policy, brand new tokens are not included, there is a minimum requirement of 2500 holder addresses and 5000 transactions, in order to filter out scam tokens.
See the criteria at (mentioned in the first message by the bot): https://community.trustwallet.com/t/how-to-submit-a-token-logo/3863).
This token has no real usage yet (175). Closing PR for now. Please come back to us when all criteria are met.

https://bscscan.com/token/0x2090c8295769791ab7A3CF1CC6e0AA19F35e441A

**Comment by jetfuelfinance** [comment]
Hi Adam,

Jetfuel is a yield farming/staking token. Nearly all the supply is locked
up in AMMs or staking so the holders is low as there's no incentive to hold
the token outside of the lp/staking.

It is not a scam. Please look at the transactions, it it 84000+

We need our logo uploaded so pancakeswap can include our data on their
exchange.

Please advise

**Comment by catenocrypt** [comment]
Reopened.

**Comment by catenocrypt** [comment]
Please resize logo to 256x256; current size is over 1000 px which is too large.

**Comment by jetfuelfinance** [comment]
Thanks! Will resend.

**Comment by jetfuelfinance** [comment]
okay we'll send the fee

**Comment by jetfuelfinance** [comment]
Hello,

I have finally managed to purchase 1000 twt. I'll be repushing the logo
with 256x256.

Thank you.

**Pull request closed without merging**
