### PR TITLE
START

### PR DESCRIPTION
**Pull request by vitalismark**

### CODE REVIEW

**Comment by vitalismark** [comment]
im making payment now

**Comment by vitalismark** [comment]
payment made please merge PR as soon as possible

**Comment by catenocrypt** [comment]
Payment of 1 BNB accepted manually.
https://explorer.binance.org/tx/4FED185AAAF0EF9E841E5904E603D035861113F1A52F13DBF70EA53655D060D0

I have mistakenly put an Approve before the payment, so the bot did not look for it any more (my mistake).

**Pull request merged**
