### PR TITLE
Logo for uSD (Unified Stable Dollar)

### PR DESCRIPTION
**Pull request by alet89**
Logo for 0x44086035439E676c02D411880FcCb9837CE37c57

### CODE REVIEW

**Comment by zachzwei** [comment]
Please provide more details about this project. 
https://community.trustwallet.com/t/how-to-submit-a-token-logo/3863#how-to-get-approved

You can follow this format when adding an info.json file:

``` {
   "name":"Bitcoin",
   "website":"https://bitcoin.org",
   "source_code":"https://github.com/bitcoin",
   "white_paper":"https://bitcoin.org/bitcoin.pdf",
   "short_description":"Bitcoin is a cryptocurrency and worldwide payment system.",
   "explorer":"https://blockchain.info",
   "research":"https://research.binance.com/en/projects/bitcoin"
}

**Comment by alet89** [comment]
@zachzwei info.json added :)

**Comment by alet89** [comment]
Guys I added the json... But I received All checks have failed... I can't understand what I did it wrong :(

**Comment by alet89** [comment]
I think I solved... I forgot a comma in the Json :D

**Comment by zachzwei** [comment]
Token activity does not meet the minimum requirements.
Pull request will be put on Hold.
Learn more here:
https://community.trustwallet.com/t/how-to-submit-a-token-logo/3863#how-to-get-approved

**Pull request merged**
