### PR TITLE
Add DOGEFOOD (BEP20)

### PR DESCRIPTION
**Pull request by Deepdarkforest**
Adding info for BEP20 token 'DOGEFOOD'.

PR created by <a href="https://assets.trustwallet.com">TW Assets Management</a>

### CODE REVIEW

**Comment by cryptomanz** [comment]
• What is the purpose of this token? How will it benefit Trust Wallet users?
 • How is the token being distributed? Are you conducting an airdrop?
 • Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?
 • Is the token listed on a centralized/decentralized exchange?
 • Is a Smart Contract audit completed? Where can we find this information?

**Comment by Deepdarkforest** [comment]
• What is the purpose of this token? How will it benefit Trust Wallet users?
This is an charity crypto programs, we have 1% taxation wallet saved as charity purpose, and also 10% charity tax for NFT trading. 
See as :  https://twitter.com/tmtrdorg/status/1486692971693101065?s=21
We will develop a entire ecosystem with our token based in order to maintain loyalty of holders. 
Trust wallet user can be beneficial for easily recognize our official token by logo display and get more information of our token by information display in trust wallet.   
See as: https://dogefoodexchange.com
• How is the token being distributed? Are you conducting an airdrop? 
The token which are locked in pinklock will be distributed for game reward and staking reward.
• Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?
We didnt sold any token for ICO or presale .
• Is the token listed on a centralized/decentralized exchange?
DogeFood is listed on Pancakeswap 
See as: https://pancakeswap.finance/swap?outputCurrency=0x1bec41a36356d5574aeb068b599ab7e48dd008b8
• Is a Smart Contract audit completed? Where can we find this information?
Yes, it is completed with KYC
See as : https://github.com/AuditRateTech/Smart-Contract-Audits/blob/main/DOGEFOOD_0x1bEc41a36356D5574Aeb068B599Ab7e48dD008b8.pdf

**Comment by Deepdarkforest** [comment]
> • What is the purpose of this token? How will it benefit Trust Wallet users? • How is the token being distributed? Are you conducting an airdrop? • Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale? • Is the token listed on a centralized/decentralized exchange? • Is a Smart Contract audit completed? Where can we find this information?

• What is the purpose of this token? How will it benefit Trust Wallet users?
This is an charity crypto programs, we have 1% taxation wallet saved as charity purpose, and also 10% charity tax for NFT trading.
See as : https://twitter.com/tmtrdorg/status/1486692971693101065?s=21
We will develop a entire ecosystem with our token based in order to maintain loyalty of holders.
Trust wallet user can be beneficial for easily recognize our official token by logo display and get more information of our token by information display in trust wallet.
See as: https://dogefoodexchange.com/
• How is the token being distributed? Are you conducting an airdrop?
The token which are locked in pinklock will be distributed for game reward and staking reward.
• Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?
We didnt sold any token for ICO or presale .
• Is the token listed on a centralized/decentralized exchange?
DogeFood is listed on Pancakeswap
See as: https://pancakeswap.finance/swap?outputCurrency=0x1bec41a36356d5574aeb068b599ab7e48dd008b8
• Is a Smart Contract audit completed? Where can we find this information?
Yes, it is completed with KYC
See as : https://github.com/AuditRateTech/Smart-Contract-Audits/blob/main/DOGEFOOD_0x1bEc41a36356D5574Aeb068B599Ab7e48dD008b8.pdf

**Comment by cryptomanz** [comment]
we are not accepting "Rate Tech" audit, only  "Tech Rate" audit.

**Comment by Deepdarkforest** [comment]
Ok

**Comment by Deepdarkforest** [comment]
Please wait for submission

**Comment by Cryptocool1** [comment]
Please come back to us when all criteria are met.
When creating a new PR make sure to mention this PR, so that we can see that fee has been paid already here.

**Comment by Deepdarkforest** [comment]
> Please come back to us when all criteria are met.
> 
> When creating a new PR make sure to mention this PR, so that we can see that fee has been paid already here.

Goodday admin,
Here is the Techrate aduit report of DogeFood 

https://github.com/TechRate/Smart-Contract-Audits/blob/main/February/DOGEFOOD%20Full%20Smart%20Contract%20Security%20Audit.pdf

**Comment by Deepdarkforest** [comment]
> we are not accepting "Rate Tech" audit, only  "Tech Rate" audit.

Goodday admin,
Here is the Techrate aduit report of DogeFood

https://github.com/TechRate/Smart-Contract-Audits/blob/main/February/DOGEFOOD%20Full%20Smart%20Contract%20Security%20Audit.pdf

**Pull request closed without merging**
