### PR TITLE
Mousepad/info

### PR DESCRIPTION
**Pull request by mousepadofficial**
MousePad token info and Logo update request

### CODE REVIEW

**Comment by mousepadofficial** [comment]
Hi can you please explain which format is needed

**Comment by mousepadofficial** [comment]
3C2D00F09506F714BC004910528613924A1931776B433DBE98315911754FFF9C

This is the tx hash for the payment.

Sent from ProtonMail mobile

-------- Original Message --------

**Comment by ramsty** [comment]
Hi! The path have to be blockchains/smartchain/assets/0x0504DCdDeF1bA1F18D44A0149d8B5524c9C5946D , also id must be in Checksum format.

**Comment by mousepadofficial** [comment]
https://github.com/mousepadofficial/assets/tree/master/blockchains/smartchain/assets/0x0504DCdDeF1bA1F18D44A0149d8B5524c9C5946D

check this
‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐

**Pull request closed without merging**
