### PR TITLE
Revert "Add DEXIT (BEP20)"

### PR DESCRIPTION
**Pull request by p2ptrade-online**
Reverts trustwallet/assets#12382

hi there,
we would like to update our new logo we have change our logo so we would like to update accordingly attached logo is new logo please find above

logo

### CODE REVIEW

**Review by tejen2020 — COMMENTED** [review]
i have paid 700TWT is there anything i have to do ? to update DXT logo to new logo

**Comment by cryptomanz** [comment]
Please create new PR, with only new logo

**Comment by cryptomanz** [comment]
Please create new PR, with only new logo

**Comment by cryptomanz** [comment]
make sure to mention this PR, so that we can see that fee has been paid already here.

**Comment by cryptomanz** [comment]
make sure to mention this PR, so that we can see that fee has been paid already here.

**Comment by Cryptocool1** [comment]
0

**Comment by tejen2020** [comment]
please check this one 
Add DEXIT (BEP20) #20039

**Comment by tejen2020** [comment]
hi there,

as per the instruction i have created new PR but that PR has been closed, not sure if it has been merged or not but logo has not been updated, can you please kindly update me what is the status ? see below new PR with new logo 

https://github.com/trustwallet/assets/pull/20039

**Pull request closed without merging**
