### PR TITLE
Add Anon inu ( AINU ) logo and info

### PR DESCRIPTION
**Pull request by maziyar83**
This request is about to change some info for Anon Inu and submit logo for trust wallet .
previous request number  #12284

### CODE REVIEW

**Comment by cryptomanz** [comment]
can you please add links to your PR?
example: https://developer.trustwallet.com/add_new_asset/repository_details

**Comment by maziyar83** [comment]
> 
> 
> can you please add links to your PR?
> example: https://developer.trustwallet.com/add_new_asset/repository_details

audit link  for the smart contract by Solidity.
https://solidity.finance/audits/AnonInu/

DXSale link for the wallet they were referring to.
https://dxsale.app/app/v2_9/dxlockview?id=0&add=0x295E75B0f17CcffC300C3EE5D14f352d605c90ea&type=tokenlock&chain=BSC

**Comment by maziyar83** [comment]
> 
> 
> can you please add links to your PR?
> example: https://developer.trustwallet.com/add_new_asset/repository_details

**Comment by Cryptocool1** [comment]
awaiting for cmc listing

**Comment by maziyar83** [comment]
this is the coingecko link  
https://www.coingecko.com/en/coins/anon-inu

**Comment by Cryptocool1** [comment]
please create new PR when cmc listing will be ready , make sure to mention this PR so the fee can be reused

**Pull request closed without merging**
