### PR TITLE
Add Santa Coin (BEP20)

### PR DESCRIPTION
**Pull request by erience**
Adding info for BEP20 token 'Santa Coin'.

### CODE REVIEW

**Comment by erience** [comment]
CoinGecko Link: https://www.coingecko.com/en/coins/santa-coin
CoinMarketCap Link:  https://coinmarketcap.com/currencies/santa-coin-2/

LitePaper Link: https://santacoin.io/wp-content/uploads/2021/11/SantaCoin-Litepaper-5.pdf
InterFi Audit: https://github.com/interfinetwork/smart-contract-audits/blob/main/SantaCoin_AuditReport_InterFi.pdf
TechRate Audit: https://github.com/TechRate/Smart-Contract-Audits/blob/main/October/Santa%20Coin%20Full%20Smart%20Contract%20Security%20Audit.pdf

**Comment by Cryptocool1** [comment]
• What is the purpose of this token? How will it benefit Trust Wallet users?
 • How is the token being distributed? Are you conducting an airdrop?
 • Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?
 • Is the token listed on a centralized/decentralized exchange?

**Comment by erience** [comment]
• What is the purpose of this token? How will it benefit Trust Wallet users? ---- Santa Coin main utility is our upcoming Play-to-earn Racing Santa game – Santa F1 racing game creates a new paradigm for digital ownership and gaming. Through blockchain, Santa nonfungible collectible tokens allow players to participate in a play-to-earn gaming ecosystem, where skills are rewarded with real value rewards. All of the core gameplay assets in Santa F1 can be wholly owned, traded and sold by players and also used to play the game itself, empowering players like never before. Trust wallet users can enjoy this immersive game experience inside the wallet itself.

• How is the token being distributed? Are you conducting an airdrop? --- The token did ICO on PinkSale and raised 250 BNB, apart from this, the token is now traded on Pancakeswap and the token can be purchased from there. No, Airdrop was conducted or will be conducted.

• Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale? ---- Yes, ICO was done. Link of ICO: https://www.pinksale.finance/#/launchpad/0x2b6D6Ca1Ac46CCD70336AED938d815B72693833f?chain=BSC

• Is the token listed on a centralized/decentralized exchange? --- The token is right now listed on Pancakeswap (DEX).

**Comment by erience** [comment]
@Cryptocool1 @cryptomanz answers submitted above.

**Pull request merged**
