### PR TITLE
Add $LEV https://www.levyathan.finance/

### PR DESCRIPTION
**Pull request by ghost**
https://app.levyathan.finance/
First digital asset indexes on BSC

Follow us on twitter:
https://twitter.com/Levyathan_index

Telegram official channel:
https://t.me/joinchat/f5sErJFjs8pmYWU0

### CODE REVIEW

**Comment by Cryptocool1** [comment]
As per our policy, brand new tokens are not included, there is a minimum requirement of 2500 holder addresses and 5000 transactions, in order to filter out scam tokens.
See the criteria at (mentioned in the first message by the bot): https://community.trustwallet.com/t/how-to-submit-a-token-logo/3863).

**Comment by Cryptocool1** [comment]
can't find contract on your website, please check.

**Comment by levyathan-dev** [comment]
@Cryptocool1 is is this one you're refering to https://bscscan.com/address/0x304c62b5b030176f8d328d3a01feab632fc929ba#code ?

**Comment by Cryptocool1** [comment]
> @Cryptocool1 is is this one you're refering to https://bscscan.com/address/0x304c62b5b030176f8d328d3a01feab632fc929ba#code ?

Hello, you need to add your contract to the website.

**Comment by levyathan-dev** [comment]
@Cryptocool1 Thank you for your reply but I don't get it should we put just the contract on the footer for example ?

**Comment by Cryptocool1** [comment]
> @Cryptocool1 Thank you for your reply but I don't get it should we put just the contract on the footer for example ?

yes, you're right.

**Pull request merged**
