### PR TITLE
Add HyperChain (BEP20)

### PR DESCRIPTION
**Pull request by xcyberdragonx**
Adding info for BEP20 token 'HyperChain'.

PR created by <a href="https://assets.trustwallet.com">TW Assets Management</a>

### CODE REVIEW

**Comment by Cryptocool1** [comment]
PR should include only 2 files:

blockchains/smartchain/assets/0x565D931cBa7C7E1af3925f77124D5e2d68311BBE/info.json
blockchains/smartchain/assets/0x565D931cBa7C7E1af3925f77124D5e2d68311BBE/logo.png

**Comment by xcyberdragonx** [comment]
> > I have sent 2 BNB
> > TXn: B3E3E138DF028EE8CFB27FB9BBC5B01FCC21EC13BC0B44EAE5FB0732896C2B9D
> > BSCscan:
> > https://explorer.binance.org/tx/B3E3E138DF028EE8CFB27FB9BBC5B01FCC21EC13BC0B44EAE5FB0732896C2B9D
> > Regards,
> > Josh
> 
> PR should include only 2 files:
> 
> blockchains/smartchain/assets/0x565D931cBa7C7E1af3925f77124D5e2d68311BBE/info.json
> blockchains/smartchain/assets/0x565D931cBa7C7E1af3925f77124D5e2d68311BBE/logo.png


Seems like I can't deete one of the two png

**Comment by xcyberdragonx** [comment]
Can someone please assist

**Comment by xcyberdragonx** [comment]
I have also added Add HyperChain (BEP20) #7518 
Since i may be making a mess out of things... please assist

**Pull request closed without merging**
