### PR TITLE
Add RDR Token's Info

### PR DESCRIPTION
**Pull request by AperoLuandq**
Add RDR Token's Info

### CODE REVIEW

**Comment by Cryptocool1** [comment]
Contract should be in checksum format, please change

**Comment by Cryptocool1** [comment]
Please create new PR, follow doc https://developer.trustwallet.com/assets/requirements
You may want to try our Assets app in beta; go to https://assets.trustwallet.com, log on with Github, enter contract ID, logo and some additional info, and it will create a PR for you.
See https://developer.trustwallet.com/assets/repository_details

**Comment by AperoLuandq** [comment]
> Contract should be in checksum format, please change
"name": "Rise of Defenders Token",
    "website": "https://risedefenders.io",
    "description": "RDR is token of Rise of Defenders project",
    "explorer": "https://bscscan.com/token/0x92da433da84d58dfe2aade1943349e491cbd6820",
    "type": "BEP20",
    "symbol": "RDR",
    "decimals": 18,
    "status": "active",
    "id": "0x92dA433dA84d58DFe2aade1943349e491Cbd6820",
    "tags": [
        "nft"
    ],
    "links": [
        {
            "name": "twitter",
            "url": "https://twitter.com/DefendersRise"
        },
        {
            "name": "telegram",
            "url": "https://t.me/RiseDefendersAnn"
        },
        {
            "name": "discord",
            "url": "https://discord.com/invite/x7cAKWnWh4"
        },
        {
            "name": "medium",
            "url": "https://medium.com/@risedefenders"
        }
    ]


Hello @Cryptocool1, this is my info.json. I don't understand your require, what should it be?

**Comment by Cryptocool1** [comment]
your contract should be checksummed

**Comment by Cryptocool1** [comment]
blockchains/smartchain/assets/0x92da433da84d58dfe2aade1943349e491cbd6820/info.json should be blockchains/smartchain/assets/0x92dA433dA84d58DFe2aade1943349e491Cbd6820/info.json

**Pull request closed without merging**
