### PR TITLE
Update PHA token description, logo, and base token support

### PR DESCRIPTION
**Pull request by h4x3rotab**
Updated according to:
- CoinMarketCap: https://coinmarketcap.com/currencies/phala-network/
- Coingecko: https://www.coingecko.com/en/coins/phala-network
- Binance research page: https://www.binance.com/en/research/projects/phalanetwork

### CODE REVIEW

**Comment by cryptomanz1** [comment]
please update your branch with the  recently master

**Comment by h4x3rotab** [comment]
> please update your branch with the recently master

Done

**Comment by h4x3rotab** [comment]
Glad to see the PR has been approved. Could you trigger the merge?

**Comment by Cryptocool1** [comment]
Hello, This branch is out-of-date with the base branch
Please update it

**Comment by h4x3rotab** [comment]
@Cryptocool1 Updated. Please review. Thanks!

**Pull request merged**
