### PR TITLE
Add dHealth (DHP) (ERC20)

### PR DESCRIPTION
**Pull request by PaulRieger**
Adding info for ERC20 token 'dHealth (DHP)'.

PR created by <a href="https://assets.trustwallet.com">TW Assets Management</a>

### CODE REVIEW

**Comment by Cryptocool1** [comment]
• What is the purpose of this token? How will it benefit Trust Wallet users?
 • How is the token being distributed? Are you conducting an airdrop?
 • Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?
 • Is the token listed on a centralized/decentralized exchange?
 • Is a Smart Contract audit completed? Where can we find this information?

**Comment by PaulRieger** [comment]
• What is the purpose of this token? How will it benefit Trust Wallet users?
DHP powers dHealth Network, a public blockchain for healthcare. Pharma giants like Roche and Eli Lilly operate nodes.

dHealth launched a Health2Earn showcase powered by Strava last year and we want to feature trust wallet as a good way to manage DHP.

• How is the token being distributed? Are you conducting an airdrop?

1) dHealth launched on Occam.fi: https://razer.occam.fi/project/dHealth
2) Tokens can also be earned through use cases like health2earn.

• Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?

dHealth conducted an IDO on Occam.fi

• Is the token listed on a centralized/decentralized exchange?

DHP is listed on both Uniswap and MEXC:
- https://v2.info.uniswap.org/pair/0xdfb4ff00275b44421b87fc6c010b437ebeffea93
- https://www.mexc.com/exchange/DHP_USDT

• Is a Smart Contract audit completed? Where can we find this information?
Here is the contract code:  https://etherscan.io/address/0xc40f23a3e9613e012944f7957edce97899fa920d#code

DHP uses the same code as audited Occam.fi (OCC) contract since it launched on their launchpad: https://etherscan.io/address/0x2f109021afe75b949429fe30523ee7c0d5b27207#code

**Comment by Cryptocool1** [comment]
Is a Smart Contract audit completed?

**Comment by PaulRieger** [comment]
The ERC20 Contract was minted using OpenZeppelin's Wizard (https://wizard.openzeppelin.com/) which has been audited by Level K (https://github.com/OpenZeppelin/openzeppelin-contracts/blob/master/audit/2018-10.pdf)

**Comment by PaulRieger** [comment]
@Cryptocool1 is everything resolved for the merge?

**Comment by Cryptocool1** [comment]
hello, we require the audit of your token

**Comment by Cryptocool1** [comment]
please come back to us when all criteria are met. make sure to mention this PR so the fee can be reused

**Pull request closed without merging**
