### PR TITLE
Adding Shrub token

### PR DESCRIPTION
**Pull request by Toughnumber**
This PR adds the Shrub token to the Trust Wallet assets. It includes the token's info.json file and logo.

### CODE REVIEW

**Comment by Toughnumber** [comment]
Purpose of the Token:

Our token, Shrub, is a community-driven meme token inspired by Elon Musk’s pet hedgehog. The purpose of Shrub is to bring fun and creativity to the crypto space while fostering a vibrant community of users who can share in the humor and potential growth of the token. Meme tokens like Shrub engage and entertain users, encouraging broader adoption of crypto technologies in a lighthearted and accessible way.

Benefit to Trust Wallet Users:

By listing Shrub, Trust Wallet users gain access to a popular meme token with a growing community, adding diversity to their portfolio and enabling them to participate in social campaigns and other community-driven initiatives. Shrub’s active presence on social media and exchanges ensures high engagement and visibility, creating opportunities for both entertainment and speculative trading.

How is the token being distributed?

All tokens are in circulation with 5% of the supply having been burnt forever. The Shrub token was fair launched with no team or marketing tokens.

Did you sell tokens at an ICO or is there a pre-sale?

There was no ICO and there was no pre-sale. The project was fair launched as with the majority of community based meme projects whereby everyone has a fair chance to accumulate tokens early. This is the most popular launch model for the majority of crypto projects today.

Is the token listed on a CEX/DEX?

Yes. We are listed on Gate.io, Uniswap, LBank, Poloneix, BitMart, AscendEX and CoinEx.

Has a Smart Contract audit been complete:

Currently a smart contract audit has not been completed for Shrub. However, we can confirmed that the contract has been renounced and LP has been burnt ensuring safety which is a common practice for the majority of meme projects today.


Yahoo Mail: Search, organise, conquer 
 
  On Thu, 21 Nov 2024 at 8:43, ***@***.***> wrote:   


• What is the purpose of this token? How will it benefit Trust Wallet users?
• How is the token being distributed? Are you conducting an airdrop?
• Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?
• Is the token listed on a centralized/decentralized exchange?
• Is a Smart Contract audit completed? Where can we find this information?

**Comment by Toughnumber** [comment]
Hi there. I don't understand, I made payment of 500 TWT. I'd like to know what I done wrong here please or how I can fix it

**Comment by Toughnumber** [comment]
Hi, I made the payment of 500 TWT. Below are the transaction details:
- Transaction Hash:  0x711539536abe1b43eef83cf12371362563327fc0d538a86a6bf047b62bbd5468
- Recipient Address: 0x475e786ffcabf41de5908a7692f4467f3c434d8c
- Amount: 500 TWT
- Time: Nov-19-2024 02:24:16 PM UTC
Please verify the payment and advise how to proceed. Thank you. I'd like to get this fixed please I'm not sure what I did wrong.

Yahoo Mail: Search, organise, conquer 
 
  On Fri, 22 Nov 2024 at 10:38, ***@***.***> wrote:   


This PR is being closed due to inactivity. If you wish to continue, please have us reopen the PR before sending your payment, or just create a new one.
Do NOT send payments for closed PR, as the fee may by lost!

**Comment by Cryptocool1** [comment]
After a careful review of your submission it looks like this token has not undergone any security audit. The Pull Request will be closed until further notice. 
To know more about the token approval, please check this article: https://developer.trustwallet.com/listing-new-assets/requirements
Feel free to open new Pull Request once you meet those requirements.

**Comment by Toughnumber** [comment]
Is there any chance we can get a refund on this so we can get security check and resubmit?

**Comment by Toughnumber** [comment]
Is it possible to receive a refund please so I can resubmit after security check?

**Comment by baphuongvinh** [comment]
?

Vào Th 7, 23 thg 11, 2024 lúc 03:15 Toughnumber ***@***.***>
đã viết:

**Comment by Cryptocool1** [comment]
Unfortunately, we do not provide refunds. However, once you have completed the smart contract audit, you are welcome to return to us and create a new Pull Request and we will reuse your fee payment

**Comment by Toughnumber** [comment]
Ah ok I see, we will complete a security check and try again. Appreciate
that, thank you.

**Comment by Toughnumber** [comment]
Hi there, we had an audit completed by certik. https://skynet.certik.com/projects/shrub-token#code-security

**Comment by Toughnumber** [comment]
Should I start a new pull request?

**Comment by Toughnumber** [comment]
Hi 👋 I have submitted a fresh pull request for this token, can you have a look and add the fee from this please? (Add shrub token #29846)

**Pull request closed without merging**
