### PR TITLE
Add Swych Finance (BEP20)

### PR DESCRIPTION
**Pull request by thealidev**
Adding info for BEP20 token 'Swych Finance'.

PR created by <a href="https://assets.trustwallet.com">TW Assets Management</a>

### CODE REVIEW

**Comment by thealidev** [comment]
The token is aready so popular  
And the bot dont verified holders automatically  
Kindly check  
It satisfies all requirements

**Comment by Cryptocool1** [comment]
How did you get 70k holders in less than 1day?

**Comment by thealidev** [comment]
I reopen pr

**Comment by thealidev** [comment]
I was out for 10 days  
I have came back

**Pull request closed without merging**
