### PR TITLE
Add ENERGY COIN (BEP20)

### PR DESCRIPTION
**Pull request by yenky**
Adding info for BEP20 token 'ENERGY COIN'.

PR created by <a href="https://assets.trustwallet.com">TW Assets Management</a>

### CODE REVIEW

**Comment by Cryptocool1** [comment]
• What is the purpose of this token? How will it benefit Trust Wallet users?
 • How is the token being distributed? Are you conducting an airdrop?
 • Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?
 • Is the token listed on a centralized/decentralized exchange?
 • Is a Smart Contract audit completed? Where can we find this information?

**Comment by yenky** [comment]
Hi Cryptocool1
Thank you for your response.

What is the purpose of this token? How will it benefit Trust Wallet users?
Answer : We created our token to serve people. This is our ultimate goal, as we genuinely want to make your lives better by making payment processes faster and smarter. 
We collaborate closely with the every crypto community and love collecting feedback from them. Feedback is a means of improvement. 
We have many users who are using Trust wallet for their ENG and as we know their are some issue with tokens where 
people make copy of token and customers get wrong information and they buy wrong token. So if we have logo in trust 
wallet so all our customers can see very clearly that this is right token to use. As we know Trust wallet is one of 
the most secure wallet for crypto and we always advise to our customers to use Trust wallet.
--------------------
How is the token being distributed? Are you conducting an airdrop?
Answer : 4 months before when team was working on ENG token idea we decided to distribute in this manner.

7% Branding and Marketing
22% ENERGY / Solar System
28% Legal & Financial Overhead
11% IT Infastructure
9% Bounty &Overhead
3% Management
5% Bounty
----------------------
Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?
Answer : Yes we sold token in initial stage and transaction happened with Pancake swap and we have all records here :
 https://bscscan.com/token/0x8a505d5cb3db9fcf404c0a72af3df8be4efb707c
As you can check we are having good volume of transactions everyday because our customers are believing in ENG Token more every day. 
Our Pre-sale had an offer with Utility System. We have big Companies who's accepting ENG as their payment system.We are offering our 
users to pay their regular life bills via ENG Token.
----------------------
Is the token listed on a centralized/decentralized exchange?
Answer : We did submission for few decentralize exchange and in few days we are going to be on following exchange : https://latoken.com/ 
We are on dexguru already : https://dex.guru/token/0x8a505d5cb3db9fcf404c0a72af3df8be4efb707c-bsc Many of our customer using this decentralized exchange for buy/sell ENG token.
---------------------
Is a Smart Contract audit completed? Where can we find this information?
Answer : You can find inforamation under BSC scaner bscscan : https://bscscan.com/token/0x8a505d5cb3db9fcf404c0a72af3df8be4efb707c

Trust wallet logo going to help all of our users in a very good way because now they need to check with our support system to find out reality about logo

We named our token ENERGY COIN, and our idea behind this is A new smart blockchain based marketplace for trading
digital goods and assets according to users interests. Automatic matching of buyers and sellers via unique artificial intelligence approaches. We are working with real solar energy system as well.

Thank you

**Comment by cryptomanz** [comment]
• Is a Smart Contract audit completed?

**Comment by DNAOFFICIALL** [comment]
Yes

**Comment by DNAOFFICIALL** [comment]
Green beans and red

**Comment by yenky** [comment]
> • Is a Smart Contract audit completed?
Hi cryptomanz
yes it's completed . 

Thank you

**Comment by cryptomanz** [comment]
Please send me smart contract audit in pdf format.

**Comment by yenky** [comment]
> Please send me smart contract audit in pdf format.

Hi Crptomanz , Sure 

https://engcrypto.io/ENERGY_COIN_Token_Audit_Report_Smart%20Contract.pdf

Thank you
[ENG COIN Token Audit Report Smart Contract.pdf](https://github.com/trustwallet/assets/files/8669575/ENG.COIN.Token.Audit.Report.Smart.Contract.pdf)

**Comment by yenky** [comment]
Hi Cryptocool1 & Crptomanz

When can we see logo in trust wallet ? Users are waiting to check out the logo. All crypto users love trust wallet features.

Thank you

**Comment by yenky** [comment]
Hi [Cryptocool1](https://github.com/Cryptocool1)

I have a small questions here Regarding Price Ticker in Trust wallet for ENG Token. ENG is listed over coinGecko Platform.
is it possible to get the price ticker in trust wallet via coinGecko Price chart.
I really appreciate the work you are doing and want to know your reviews on this questions and if yes then how to do it 

Thank You

**Comment by Cryptocool1** [comment]
Hello, we take the price from CoinMarketCap

**Comment by yenky** [comment]
Hello [Cryptocool1](https://github.com/Cryptocool1)
Thank you for your quick answer and we want to build Stacking system with ENG, can you please guide me the process to do it with in Trust wallet 

Thank you

**Comment by yenky** [comment]
> Hello [Cryptocool1](https://github.com/Cryptocool1)

ENG is available on CoinMarketCap , Can we have price ticker in trust wallet please.  https://coinmarketcap.com/currencies/eng-crypto/

Thank you

**Pull request merged**
