### PR TITLE
Adding 6 new ICHI oneTokens

### PR DESCRIPTION
**Pull request by DTal621**
This PR is being closed due to inactivity. If you wish to continue, please have us reopen the PR before sending your payment, or just create a new one.
Do NOT send payments for closed PR, as the fee may by lost!
  (48 vs. 48 hrs)

### CODE REVIEW

**Comment by DTal621** [comment]
@Cryptocool1 sorry for the back and forth but the funds are finally ready - let me know if you can open this and I will transfer the TWT immediately

**Comment by DTal621** [comment]
thanks - funds sent: https://explorer.binance.org/tx/4818BAAA32C738B31C00FDF5CDA7C48F96BCB702452C64C66D49855C95F69AE4

**Comment by Cryptocool1** [comment]
Could you add the links please?

**Comment by DTal621** [comment]
Sure - what links are you looking for? The Etherscan links that appear on here for the token seem to work for me - is there something else needed?

**Comment by Cryptocool1** [comment]
here is the example 
https://developer.trustwallet.com/assets/repository_details

**Comment by DTal621** [comment]
@Cryptocool1  updates to links made - please let me know if there is anything else that needs to be done to push this through

**Pull request merged**
