### PR TITLE
Add Akita Inu (ERC20)

### PR DESCRIPTION
**Pull request by Amirahmspwrr**
Adding info for ERC20 token 'Akita Inu'.

PR created by <a href="https://assets.trustwallet.com">TW Assets Management</a>

### CODE REVIEW

**Comment by Amirahmspwrr** [comment]
Paid

**Comment by Amirahmspwrr** [comment]
What now:)

**Comment by Amirahmspwrr** [comment]
Because we still have the old logo . New one hasn't been added yet

**Comment by Amirahmspwrr** [comment]
@Cryptocool1

**Comment by Cryptocool1** [comment]
Hello, couple of hours

**Comment by Amirahmspwrr** [comment]
It's still not updated . Last time logo adding took only few minutes . There's a problem 
What's that?

**Comment by Amirahmspwrr** [comment]
@Cryptocool1

**Comment by Amirahmspwrr** [comment]
@Cryptocool1 @cryptomanz1 still no update adjusted

**Comment by cryptomanz1** [comment]
IMAGE 2023-07-07 09:12:52

**Comment by cryptomanz1** [comment]
IMAGE 2023-07-07 09:14:41

**Pull request merged**
