### PR TITLE
Add wCCX

### PR DESCRIPTION
**Pull request by krypt0x**
Add wCCX

### CODE REVIEW

**Comment by Feellikeastronaut** [comment]
guys could you check our https://github.com/trustwallet/assets/pull/3238 and tell us is it good and should work or not ? and we made something wrong? thank You.

**Comment by krypt0x** [comment]
> guys could you check our #3238 and tell us is it good and should work or not ? and we made something wrong? thank You.

You are posting a request in the wrong PR but no worries. The maintainers will follow up your PR soon.

**Comment by Feellikeastronaut** [comment]
Thank You very much :))

**Comment by krypt0x** [comment]
Great! Thanks

**Pull request merged**
