### PR TITLE
Add BTCPi Token (BEP20)

### PR DESCRIPTION
**Pull request by BTCPiCom**
Adding info for BEP20 token 'BTCPi Token'.

PR created by <a href="https://assets.trustwallet.com">TW Assets Management</a>

### CODE REVIEW

**Comment by Cryptocool1** [comment]
As per our policy, brand new tokens are not included, there is a minimum requirement of 10,000 holder addresses and 15,000 transactions, in order to filter out scam tokens.
See the criteria at : https://developer.trustwallet.com/assets/requirements .

**Comment by Cryptocool1** [comment]
Please come back to us once all criteria are met. See the criteria at : https://developer.trustwallet.com/assets/requirements .

**Comment by BTCPiCom** [comment]
BTCPi/SpacePi has added initial liquidity with a ratio of 1,200,000:30 trillion. It has been locked in Pinksale until 13:14 on June 28, 2030.

https://www.pinksale.finance/pinklock/record/1011307?chain=BSC

The contract of BTCPi Mine is basically the same as that of MDEX, which has been submitted to the audit agency Armors for audit, and the audit report will be released on July 10th.

The mining contract has been open sourced.

https://bscscan.com/address/0xc48fe252aa631017df253578b1405ea399728a50#code

**Comment by BTCPiCom** [comment]
> We require smart contract audit of the token you submitted.

Okay, I'll submit the link here after the audit passes.

**Comment by BTCPiCom** [comment]
BTCPi has redesigned its logo so as not to be too similar to the BTC logo and cause misunderstanding.

If possible, we hope that the Trust Wallet team can help modify it

logo
.

**Pull request closed without merging**
