### PR TITLE
Add PandAI Token (BEP20)

### PR DESCRIPTION
**Pull request by pandai-jl**
Adding info for BEP20 token 'PandAI Token'.

PR created by <a href="https://assets.trustwallet.com">TW Assets Management</a>

### CODE REVIEW

**Comment by Cryptocool1** [comment]
Hello, how did you get more than 10k holders in 1 week?

**Comment by pandai-bsc** [comment]
More than 10k holders in 1 week? Just look at our socials...
- The biggest BSC Twitter accounts are cooperating with us
- Community numbers: Twitter 23k+, Discord 21k+, Telegram 5k+
- Token price +200% since we've launched and goes up steadily
- 12k+ trades on DEX
- we are already on first CEX

Is there any specific criteria that we don't meet?

**Comment by Cryptocool1** [comment]
Have you conducted any airdrops?

**Comment by pandai-bsc** [comment]
Yes, and everything was announced.
- airdrop in cooperation with BSC News
- airdrop to Discord mods/boosters

All airdrops combined were sent to approx. 2k wallets

**Comment by Cryptocool1** [comment]
• What is the purpose of this token? How will it benefit Trust Wallet users?
 • How is the token being distributed? Are you conducting an airdrop?
 • Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?
 • Is the token listed on a centralized/decentralized exchange?
 • Is a Smart Contract audit completed? Where can we find this information?

**Comment by pandai-bsc** [comment]
Are we sticking to requirements specified in 
https://developer.trustwallet.com/developer/listing-new-assets/requirements#listing-acceptance-guidelines
or are we coming up with new ones?

To answer your questions:
• What is the purpose of this token? How will it benefit Trust Wallet users?
The purpose of PandAI is to make AI accessible to everyone by providing real utility and knowledge about AI. PandAI Token is here to have everything in one place. In case Trust Wallet users want to dig deeper into AI, I believe having PandAI Token in their wallet is must have.

• How is the token being distributed?
As described in our [tokenomics](https://docs.pandai.io/tokenomics/distribution).

• Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?
3 private rounds, as specified [here](https://docs.pandai.io/tokenomics/distribution#early-investors-30), 1st round closed successfully collecting $1M, 2nd round ongoing.
There was no ICO, just creating initial liquidity from part of the funds collected in 1st private round.
Private investors have already access to tools that PandAI Token will make accessible to everyone.

• Is the token listed on a centralized/decentralized exchange?
DEX: PancakeSwap ($300k+ in liquidity, which has been locked for 12 months, [prove](https://www.team.finance/view-coin/0x550d7984b7adfff88815e5528e12e322df6d3b9b)).
CEX: Listed on [BitMart](https://www.bitmart.com/trade/en-US?symbol=PANDAI_USDT), next CEXes coming.

• Is a Smart Contract audit completed? Where can we find this information?
SC audit attached [here](https://docs.pandai.io/tokenomics/token-info).

**Comment by Cryptocool1** [comment]
Congratulations!
Your logo should appear within 2hours.

**Pull request merged**
