### PR TITLE
Add Offshore Plan (BEP20)

### PR DESCRIPTION
**Pull request by offshorepla**
Adding info for BEP20 token 'Offshore Plan'.

PR created by <a href="https://assets.trustwallet.com">TW Assets Management</a>

### CODE REVIEW

**Comment by offshorepla** [comment]
> ### 公关摘要
> 文件 OK： PR 中的 2 个令牌：**BEP20** 0xDD3162aD2185928bf3D92Bc05174Aa442E7382Ef 符号：**OPC**小数点：18 链接：[徽标](https://raw.githubusercontent.com/offshorepla/assets/br1017-204059/blockchains/smartchain/assets/0xDD3162aD2185928bf3D92Bc05174Aa442E7382Ef/logo.png) [信息](https://raw.githubusercontent.com/offshorepla/assets/br1017-204059/blockchains/smartchain/assets/0xDD3162aD2185928bf3D92Bc05174Aa442E7382Ef/info.json) [网站](https://www.douglas-amc.org) [资源管理器](https://bscscan.com/token/0xDD3162aD2185928bf3D92Bc05174Aa442E7382Ef) 标签：defi，staking 令牌检查错误： ❌未检查的持有人数量：请手动检查
> 
>

**Comment by offshorepla** [comment]
https://bscscan.com/token/0xdd3162ad2185928bf3d92bc05174aa442e7382ef

**Comment by Cryptocool1** [comment]
What is the purpose of this token? How will it benefit Trust Wallet users?
 • Is a Smart Contract audit completed? Where can we find this information?

**Comment by offshorepla** [comment]
> 这个令牌的目的是什么？它将如何使 Trust Wallet 用户受益？ • 智能合约审计是否完成？我们在哪里可以找到这些信息？
Q: What is the ecological planning of OPC?
A: The Douglas AMC platform will rely on the bottom layer of financial consensus, combine the business operation logic and payment habits of various industries, and build a value network based on transaction data, behavior data, and payment records. Through the pluggable and easy-to-build principle of WEB3.0 , to design universal payment protocols, fund transfer specifications, cross-chain atomic transactions and risk control modules to ensure the security of the entire ecosystem. At the same time, an effective response mechanism for the user's digital asset management side and the community alliance side is built, and a unified digital asset wallet is established to support the asset recharge and exchange of various autonomous communities, business alliance members, public chains and commercial application blockchains, forming a diversified The wallet ecosystem is simple and open to open up the digital asset transaction link. The digital financial asset with the project token as the main asset in the platform is the digital financial asset of the stable asset. It will cooperate with the wallet system, digital assets, and merchant APP, spanning multiple online and offline business resources, providing users with more payment scene.

**Comment by offshorepla** [comment]
> • 智能合约审计我们是否可以在哪里找到这些信息？
https://attest.knownseclab.com/attestation/searchResult?qurey=5b38cf26793c4ed6964e491cc51f87e5
https://www.certik.com/projects/offshore-plan

**Comment by offshorepla** [comment]
https://douglas-amc.gitbook.io/douglas-amc-white-paper/

**Comment by offshorepla** [comment]
> • 智能合约审计我们是否可以在哪里找到这些信息？
We can see the entire OPC economic model through the white paper
white paper：https://douglas-amc.gitbook.io/douglas-amc-white-paper/
Audit Report1：https://attest.knownseclab.com/attestation/searchResult?qurey=5b38cf26793c4ed6964e491cc51f87e5
Audit Report2：https://www.certik.com/projects/offshore-plan

**Comment by offshorepla** [comment]
A: The Douglas AMC platform will rely on the bottom layer of financial
consensus, combine the business operation logic and payment habits of
various industries, and build a value network based on transaction data,
behavior data, and payment records. Through the pluggable and easy-to-build
principle of WEB3.0 , to design universal payment protocols, fund transfer
specifications, cross-chain atomic transactions and risk control modules to
ensure the security of the entire ecosystem. At the same time, an effective
response mechanism for the user's digital asset management side and the
community alliance side is built, and a unified digital asset wallet is
established to support the asset recharge and exchange of various
autonomous communities, business alliance members, public chains and
commercial application blockchains, forming a diversified The wallet
ecosystem is simple and open to open up the digital asset transaction link.
The digital financial asset with the project token as the main asset in the
platform is the digital financial asset of the stable asset. It will
cooperate with the wallet system, digital assets, and merchant APP,
spanning multiple online and offline business resources, providing users
with more payment scene.

CryptoA ***@***.***> 于2022年10月18日周二 01:47写道：

**Comment by offshorepla** [comment]
https://www.certik.com/projects/offshore-plan
https://attest.knownseclab.com/attestation/searchResult?qurey=5b38cf26793c4ed6964e491cc51f87e5

CryptoA ***@***.***> 于2022年10月18日周二 01:47写道：

**Comment by offshorepla** [comment]
Don't know how to check the holder

merge-fee-bot[bot] ***@***.***> 于2022年10月17日周一 20:41写道：

**Pull request merged**
