### PR TITLE
Add CV TOKEN (BEP20)

### PR DESCRIPTION
**Pull request by cvttokenofficial**
Adding info for BEP20 token 'CV TOKEN'.

PR created by <a href="https://assets.trustwallet.com">TW Assets Management</a>

### CODE REVIEW

**Comment by cvttokenofficial** [comment]
Hello Trust Wallet Team Kindly Update logo of CV Token

**Comment by cryptomanz1** [comment]
• What is the purpose of this token? How will it benefit Trust Wallet users?
 • How is the token being distributed? Are you conducting an airdrop?
 • Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?
 • Is the token listed on a centralized/decentralized exchange?
 • Is a Smart Contract audit completed? Where can we find this information?

**Comment by cvttokenofficial** [comment]
• What is the purpose of this token? How will it benefit Trust Wallet users?
- CVT token is intended to be used in DeFi, trading and metaverse.

• How is the token being distributed? Are you conducting an airdrop?
-  All are distributed Through Exchange, We have not conducting any Airdrop.

• Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?
-  No, We have not conducting any ICO.

• Is the token listed on a centralized/decentralized exchange?
- Token listed on Vindax Exchange
  Here is Link - https://vindax.com/exchange-base.html?symbol=CVT_USDT

• Is a Smart Contract audit completed? Where can we find this information?
 Token Audit Link - https://www.cyberscope.io/audits/3-cvt
 Coin Market Cap - https://coinmarketcap.com/currencies/monsta-xrp/

**Comment by cvttokenofficial** [comment]
any update ??

**Comment by cvttokenofficial** [comment]
@cryptomanz1

**Comment by cvttokenofficial** [comment]
??

**Comment by cvttokenofficial** [comment]
merge the request

**Comment by cvttokenofficial** [comment]
@Cryptocool1 @cryptomanz1 i am still waiting from 1 week for logo update

**Pull request merged**
