### PR TITLE
Submit the ENG token logo

### PR DESCRIPTION
**Pull request by EngToken**

### CODE REVIEW

**Comment by Cryptocool1** [comment]
Please add the tags and links to your info.json file.
You can see Sample info.json here: https://developer.trustwallet.com/assets/repository_details

**Comment by cryptomanz** [comment]
• What is the purpose of this token? How will it benefit Trust Wallet users?
 • How is the token being distributed? Are you conducting an airdrop?
 • Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?
 • Is the token listed on a centralized/decentralized exchange?
 • Is a Smart Contract audit completed? Where can we find this information?

**Comment by Cryptocool1** [comment]
• What is the purpose of this token? How will it benefit Trust Wallet users?
• How is the token being distributed? Are you conducting an airdrop?
• Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?
• Is the token listed on a centralized/decentralized exchange?
• Is a Smart Contract audit completed? Where can we find this information?

**Comment by EngToken** [comment]
Hello, dear Cryptocool1
Thanks for your follow, we are up to answer all of your questions one by one.
1-What is the purpose of this token.
As we mentioned on our whitepaper, Endless Board Game is a gaming platform with the aim of education. It means that our players can learn many common life strategies through our games. for example the decision-making process in sensitive situations. This kind of education is called gamification and it's quite famous AND the main point is that they can earn money while they learn. Also, we are about to support the creators that have a new game on our platform.
2- How will it benefit Trust Wallet users?
Obviously, Trust Wallet is one of the best and most famous crypto wallets around the world and many of our token holders and players will store their assets and make their transactions through Trust Wallet.
3- How is the token being distributed? Are you conducting an airdrop?
We have distributed our airdrop tokens before.  Our token will be offered through DEXs and CEXs shortly.
4- Did you sell the tokens at an Initial Coin Offering (ICO) or a token presale?
We have sold our tokens in two stages. We held our pre-sale stage on 2022/01/18 (24h sold out) and our ICO stage between 2022/04/23 and 2022/06/7 (45 days).
5- Is the token listed on a centralized/decentralized exchange?
It will be listed on Pancakeswap very soon and we've done our negotiations with some CEXs and are in the process of CEX listing.
6- Is a Smart Contract audit completed? Where can we find this information?
Our smart contract's been verified by bscscan and you can check it on the token block explorer mentioned in our info.json.

**Comment by Cryptocool1** [comment]
we require smart contract audit from reputable companies. (Certik, Techrate, Hacken, Dessert Finance)
You can see Listing Acceptance Guidelines here: https://developer.trustwallet.com/assets/requirements

**Comment by Cryptocool1** [comment]
Feel free to open new PR when all criteria are met. Make sure to mention this PR so the fee can be reused.

**Comment by EngToken** [comment]
Hello dear supporters
How can we check the number of holders manually?

**Pull request closed without merging**
