### PR TITLE
 RAEL

### PR DESCRIPTION
**Pull request by raelcoin**
RAEL will use for defi and NFT's and develop on bep20 bsc

### CODE REVIEW

**Comment by Cryptocool1** [comment]
info naming is incorrect, should be Info.json

**Comment by Cryptocool1** [comment]
Hello,
If you can't rename files in the PR, you may open a new PR.
Closing PR now. You may create new PR using this app https://assets.trustwallet.com/index.html?token=

**Comment by raelcoin** [comment]
hello
thank you for updating raelcoin/assets 
i want pay for listing Rael in trust wallet
please send link for pay
thank you

**Comment by cryptomanz** [comment]
Hello,
- Please create new PR, follow doc https://community.trustwallet.com/t/how-to-submit-a-token-logo/3863
You may want to try our  Assets app in beta; go to https://assets.trustwallet.com, log on with Github, enter contract ID, logo and some additional info, and it will create a PR for you.
See https://community.trustwallet.com/t/how-to-submit-a-token-logo-using-assets-app/82957.

**Pull request closed without merging**
