### PR TITLE
Add Spore Finance (SPORE)

### PR DESCRIPTION
**Pull request by neirenoir**
We just reached 2500 hodlers on BSC. To celebrate, we are submitting this pull request to get our much requested logo displayed in Trust Wallet.

### CODE REVIEW

**Comment by neirenoir** [comment]
Hello. I wanted to ask: is everything in order? People in our Telegram are starting to grow impatient.

**Review by SporeFinance — APPROVED** [review]
Hi can you pls review this or give us feedback to clear it? We are not sure why it's not being approved. Thank you!

**Comment by catenocrypt** [comment]
Merged master; reverted tokenlist.json

**Comment by Cryptocool1** [comment]
hello,
do you want to change your name?
https://twitter.com/sporeproject/status/1404032253571764224?s=21
 take a look at this tweet please.

**Comment by iamjustaspore** [comment]
Hi @Cryptocool1.  Yes, the name has been changed to Spore (not Spore Finance anymore).

**Pull request merged**
