### PR TITLE
Add BadRobin (BEP20)

### PR DESCRIPTION
**Pull request by shinjuinu**
Adding info for BEP20 token 'BadRobin'.

PR created by <a href="https://assets.trustwallet.com">TW Assets Management</a>

### CODE REVIEW

**Comment by Cryptocool1** [comment]
As per our policy, brand new tokens are not included, there is a minimum requirement of 2500 holder addresses and 5000 transactions, in order to filter out scam tokens.
See the criteria at (mentioned in the first message by the bot): https://community.trustwallet.com/t/how-to-submit-a-token-logo/3863).

**Comment by shinjuinu** [comment]
When it reach 2500 holder can we get the logo approved?

**Comment by Cryptocool1** [comment]
still 24 holders. Closing PR for now
Please come back to us when all criteria are met.
When creating a new PR make sure to mention this PR, so that we can see that fee has been paid already here.

**Comment by shinjuinu** [comment]
I’m gonna create new token with that 2,500 holder, my BadRobin Token is
already dead. Will submit the logo to my new token

**Pull request closed without merging**
