### PR TITLE
Add ALU logo and info

### PR DESCRIPTION
**Pull request by majdhailat**
Add ALU logo and info

### CODE REVIEW

**Comment by Cryptocool1** [comment]
hello,
• What is the purpose of this token? How will it benefit Trust Wallet users?
 • How is the token being distributed? Are you conducting an airdrop?
 • Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?
 • Is the token listed on a centralized/decentralized exchange?
 • Is a Smart Contract audit completed? Where can we find this information?

**Comment by majd64** [comment]
1. The purpose of ALU is to serve as the primary currency for buying and
selling in-game items on the Altura ERC1155 marketplace. Additionally, it
can be used to earn staking rewards and for governance.

2. The token has already been distributed. It was distributed through an IDO

3. We did a token presale.

4. The token is listed on PancakeSwap a decentralized exchange and on
Coinsbit a centralized exchange.

5. The audit is complete. Here it is:
https://solidgroup-68170.medium.com/d95c5c414897

**Comment by cryptomanz** [comment]
can you give another link to audit?

**Comment by majd64** [comment]
Hello. The link is now public. Here it is again
https://solidgroup-68170.medium.com/d95c5c414897

**Comment by cryptomanz** [comment]
- can you please add links to your PR?
example: https://developer.trustwallet.com/add_new_asset#info-json-contents

**Comment by majd64** [comment]
We just noticed the logo doesn’t look quite right. Can I make another PR to
update it for free or do I have to pay?

**Comment by Cryptocool1** [comment]
What’s wrong with your logo?

**Comment by majd64** [comment]
The top and bottom of it are slightly cut off. I attached the logo we would
like to be used. I would greatly appreciate if we didn’t have to pay
another 5 BNB 😅

**Comment by majd64** [comment]
Thank you for adding our links BTW, I appreciate it 🙏🙏

**Comment by majd64** [comment]
So can we change the logo?

**Pull request merged**
