### PR TITLE
Upload DSM token (royaldsm.io 0xab8e8F2f6684685aA09135Cd03b3a7CEa2CFb11E)

### PR DESCRIPTION
**Pull request by uatai**
Upload DSM token

### CODE REVIEW

**Comment by catenocrypt** [comment]
Please add an `info.json` file next to the `logo.png`, with info about the project, of the form:

```json
{
    "name": "Trust Wallet Token",
    "website": "https://trustwallet.com",
    "short_description": "Utility token to increase adoption of cryptocurrency.",
    "explorer": "https://etherscan.io/token/0xA866F0198208Eb07c83081d5136BE7f775c2399e",
    "socials": [
        {
            "name": "Twitter",
            "url": "https://twitter.com/trustwalletapp",
            "handle": "TrustWalletApp"
        },
        {
            "name": "Reddit",
            "url": "https://reddit.com/r/trustapp",
            "handle": "TrustApp"
        }
    ]
}
```

**Comment by mxkfz** [comment]
Information submitted，please check it

**Comment by catenocrypt** [comment]
As per our policy, brand new tokens are not included, there is a minimum requirement of 2500 holder addresses and 5000 transactions, in order to filter out scam tokens.
See the criteria at (mentioned in the first message by the bot): https://community.trustwallet.com/t/how-to-submit-a-token-logo/3863).
This token has no real usage yet (10 holders). Closing PR for now. Please come back to us when all criteria are met.

https://etherscan.io/token/0xab8e8F2f6684685aA09135Cd03b3a7CEa2CFb11E

**Comment by Iamdeadlyz** [comment]
In accordance with our [disclaimer](https://github.com/trustwallet/assets#disclaimer), your PR is denied due to the following reason:
- Plagiarized information with the intent to mislead users
image
image
image
image
image
image
image
image
image

**Pull request closed without merging**
