### PR TITLE
Add Parallel Universe Meta (BEP20)

### PR DESCRIPTION
**Pull request by paralleluniversium**
Adding info for BEP20 token 'Parallel Universe Meta'.

PR created by <a href="https://assets.trustwallet.com">TW Assets Management</a>

### CODE REVIEW

**Comment by cryptomanz** [comment]
Hello,
Please follow the rules for adding token, your logo should be a full screen, 256x256.

**Comment by paralleluniversium** [comment]
> Hello, Please follow the rules for adding token, your logo should be a full screen, 256x256.

Hello Nazar, here is 256x256:
Token-Logo-Trans-256px

**Comment by paralleluniversium** [comment]
If I remove the spaces around the logo, it will be cropped from the bottom and top when the emblem is circled. Please try to circle it. You will understand what I mean.
example:
Screenshot_6

**Comment by paralleluniversium** [comment]
This is what you asking for:
Token-FullScreen-Logo-Trans-256px

**Comment by cryptomanz** [comment]
Screenshot 2021-11-28 at 14 19 16

**Comment by paralleluniversium** [comment]
> Screenshot 2021-11-28 at 14 19 16

Token-FullScreen-Logo-Trans-256px

Check this one please

**Comment by Cryptocool1** [comment]
As per our policy, brand new tokens are not included, there is a minimum requirement of 25,000 holder addresses and 50,000 transactions, in order to filter out scam tokens.
See the criteria at : https://developer.trustwallet.com/assets/requirements .

**Comment by Cryptocool1** [comment]
Please come back to us when all criteria are met.
When creating a new PR make sure to mention this PR, so that we can see that fee has been paid already here.

**Pull request closed without merging**
