### PR TITLE
Add CIV on ERC-20

### PR DESCRIPTION
**Pull request by ghost**
Dear PR reviewer,

Before your copy/paste reply about the 1,100 holders, please be aware that YESTERDAY A SCAM TOKEN REPLICA WAS CREATED AND INVESTORS ALREADY DEFRAUDED OF 0.3 ETH.

Scam token ALERT: https://www.dextools.io/app/uniswap/pair-explorer/0x7303238e27425395fee4aab9008d874c92ee4ca9

By not approving our logo, you are implicitly aiding the work of scammers, who steal investor funds. I beg you to actually READ this text and research our token before closing this pull request again!!!

We currently have 1,100 investors, on ERC-20 fees are higher and the holders growth slower than BSC. But 100% of our supply is locked into liquidity forever, what's the risk of approving our token when it's permanently committed to the blockchain?

### CODE REVIEW

**Comment by sator-settler** [comment]
I have also submitted this via your support tickets

**Comment by sator-settler** [comment]
Scammers have literally cloned our token name and Telegram address, to defraud investors. Please do read the above carefully, so that together we can make scammers' lives harder

**Comment by sator-settler** [comment]
https://twitter.com/SatorSettler/status/1431876136783450115

**Comment by sator-settler** [comment]
Dear Trust Wallet,

thank you in advance for your help, sorry for the URGENT appeal.

I had submitted our ERC20 token information to your repository a number of times, alerting that we would be putting people at risk of scams if our logo was not updated across the various apps that depend on your approval (Trustwallet, Uniswap, etc).

Your unhelpful reply has systematically been "in order to filter out scam tokens", "brand new tokens are not included, there is a minimum requirement of 5000 holder addresses and 10000 transactions".

Now granted, on ERC20 the growth in token holders and transactions is slower than on BSC and other chains, due to the relatively higher network fees. We now have 4,000 transactions and 1,100 holders. But with over $40 million in Market Capitalization already, and over $3 million in Total Value Locked, maybe we could skip the part about "brand new token"?

AS OF YESTERDAY A BRAND-NEW SCAM TOKEN HAS BEEN CREATED, AND 0.3 ETH OF INVESTOR FUNDS ALREADY STOLEN.

This was made as a replica of ours. Not having our logo listed on Trustwallet is implicitly, but very directly, making your responsible of aiding scammers defraud people our of their legitimately earned money.

TRUE token: https://www.dextools.io/app/uniswap/pair-explorer/0xed247449a7ca06db5b27b44b2c092f0b48bbdb77

SCAM token: https://www.dextools.io/app/uniswap/pair-explorer/0x7303238e27425395fee4aab9008d874c92ee4ca9

Your not having yet approved our logo has unfortunately already caused the expected damages, so I beg you to reconsider and accept our Pull Request:

https://github.com/trustwallet/assets/pull/13169

We have already been listed on CoinBase, CoinGecko, CoinMarketCap, verified by Etherscan, for the love of it I cannot understand why on earth would you not help us fight scammers, especially as we are paying you to process the Pull Request?

Trust you will address this as a matter of the utmost urgency.
Thank you, have a great day!

**Comment by sator-settler** [comment]
Listings: CoinGecko (https://www.coingecko.com/en/coins/civilization) — CoinMarketCap (https://coinmarketcap.com/currencies/civilization/) — CoinBase (https://www.coinbase.com/price/civilization) — Livecoinwatch (https://www.livecoinwatch.com/price/Civilization-_CIV) — StockTwits (https://stocktwits.com/symbol/CIV.X)

**Comment by sator-settler** [comment]
Audited Verified Smart Contract code: Etherscan (https://etherscan.io/address/0x37fe0f067fa808ffbdd12891c0858532cfe7361d#code) and Github (https://github.com/sator-settler/civ-token) 
100% of the initial Supply Locked into Liquidity, proof (https://etherscan.io/tx/0x65381a4a4b4392771350adf98857ac3af924249561b341e0c241aa5ea1a87a44) 
Initial Liquidity Burned forever, proof (https://etherscan.io/tx/0xee397d2121b966ee9acac404aff1854efa93a92b0bc32f0a77578d7913ef1b98) and more proof

**Comment by Cryptocool1** [comment]
submission looks good. awaiting for fee payment.

**Comment by sator-settler** [comment]
fee paid https://explorer.binance.org/tx/B06D6C2F576C2A09B62FBB39B478A0C895CD3EA58A1D0FF4BA1C87B91058E8C8

**Comment by Cryptocool1** [comment]
According to our documentation/guidelines token image needs to be full screen. https://community.trustwallet.com/t/how-to-submit-a-token-logo-using-assets-app/82957.
 please change.

**Comment by sator-settler** [comment]
image

I am not entire sure what you mean? Using the "assets app" would create a duplicate Pull Request, if you want I can do it. 
FYI the "app" accepts EXACTLY the same logo image already included here, see attached.
Therefore, in essence by using it I would just re-submit essentially the same information as you already have in this PR, except it would now be in a different/ new one.

There is no other guidance as to how to edit/change the image, and I have followed every instruction on your documentation (256x256 png transparent background) already. If there are other un-documented instructions please let me know?

Let me know how you want me to proceed pls, thanks for your help

**Comment by Cryptocool1** [comment]
Снимок экрана 2021-08-29 в 21 40 46

there is no need to create new PR. just send me the full screen logo, and I will change here

**Comment by sator-settler** [comment]
256x256
256x256

**Comment by sator-settler** [comment]
How about these PNG and SVG versions?

**Comment by sator-settler** [comment]
> 
> 
> Снимок экрана 2021-08-29 в 21 40 46
> 
> please take a look at your logo
> there is no need to create new PR. just send me the full screen logo, and I will change here

I have tried to interpret your feedback, hope to have done so correctly now. Thank you for your help!

**Comment by Cryptocool1** [comment]
the logo still have space on the sides.
please see the example of the correct full screen logo
logo

**Comment by sator-settler** [comment]
think I got it - thanks for clarifying. please confirm it this will do it now:

logo

**Comment by sator-settler** [comment]
I have also cleaned this thread, is it ready to merge now?

**Comment by sator-settler** [comment]
Thank you @Cryptocool1

**Pull request merged**
