### PR TITLE
Add 'DAM' logo

### PR DESCRIPTION
**Pull request by skatoken**
Add 'DAM' logo and info

### CODE REVIEW

**Comment by Alaskatoken** [comment]
We have paid the fees and listed them on CMC
PR: https://github.com/trustwallet/assets/pull/11620
CMC: https://coinmarketcap.com/currencies/diamonds-alaska-malamuted/

**Comment by Cryptocool1** [comment]
can you please add links to your PR?
example: https://developer.trustwallet.com/add_new_asset#info-json-contents

**Comment by Alaskatoken** [comment]
What should I do?

**Comment by Cryptocool1** [comment]
> What should I do?

can you please add links to your PR?
example: https://developer.trustwallet.com/add_new_asset#info-json-contents

**Comment by Alaskatoken** [comment]
What else do you need to add?
   
   "name": "DiamondsAlaskaMalamute",
    "website": "https://alaskatoken.io/",
    "description": "DAM is a token used to compensate Alaskainu community. ",
    "explorer": "https://bscscan.com/token/0x4299260f10d7ae857dd877865d0c4ac96afe773a",
    "type": "BEP20",
    "symbol": "DAM",
    "decimals": 9,
    "status": "active",
    "id": "0x4299260f10d7AE857DD877865D0C4aC96aFe773A"

**Comment by Alaskatoken** [comment]
"links": [
        {
            "name": "github",
            "url": "https://github.com/trustwallet/"
        },
        {
            "name": "twitter",
            "url": "https://twitter.com/TrustWalletApp"
        },
        {
            "name": "reddit",
            "url": "https://reddit.com/r/trustapp"
        }
    
links?

**Comment by Alaskatoken** [comment]
Are there any questions?

**Pull request merged**
