### PR TITLE
Add logo

### PR DESCRIPTION
**Pull request by Typhoon-Network**

### CODE REVIEW

**Comment by TyphoonNetwok** [comment]
Hey, i send payment, is that ok ?

**Comment by TyphoonNetwok** [comment]
Hey, i want to know when i will see token image on trustwallet ?

**Comment by catenocrypt** [comment]
As per our policy, brand new tokens are not included, there is a minimum requirement of 100 holder addresses and 500 transactions, in order to filter out scam tokens.
See the criteria at (mentioned in the first message by the bot): https://community.trustwallet.com/t/how-to-submit-a-token-logo/3863#how-to-get-approved
This token has minimal usage (1/2).  Putting PR on hold.  Please come back to us when all criteria are met.

https://etherscan.io/token/0xd3010Ed6a22Ad406441566702bF61eb568b7954b

**Comment by TyphoonNetwok** [comment]
But i just paid for it, just add the logo wtf, or give my bnb back.

**Comment by TyphoonNetwok** [comment]
Take this information clear and not hide in some conditions where we can miss it

**Comment by catenocrypt** [comment]
Logo will be included once the 100/500 limit is reached.

image

**Comment by TyphoonNetwok** [comment]
Oh ok ! Fine for me 👌

**Pull request closed without merging**
