### PR TITLE
BITTO

### PR DESCRIPTION
**Pull request by vitalismark**

### CODE REVIEW

**Comment by vitalismark** [comment]
PAYMENT MADE

**Comment by catenocrypt** [comment]
This PR contains two tokens:
- BITTO: looks OK
- CryptoCoin4You: this token is a new token, has no usage, and info.json is also missing.  We cannot add it like this.
I suggest removing the second and only considering Bitto.  
Please confirm.

https://etherscan.io/token/0xb7B196318d12249C6DEb504689E0a678c9850d5F

**Comment by vitalismark** [comment]
Please check again and see that this is not a new token. It has over 2k transaction. and a good number of users.
https://etherscan.io/token/0x55a290f08Bb4CAe8DcF1Ea5635A3FCfd4Da60456

**Comment by vitalismark** [comment]
The file.json was attached in the folder along side the logo

**Comment by vitalismark** [comment]
I'm trying to merge the BITTO logo to this contract address 0x55a290f08Bb4CAe8DcF1Ea5635A3FCfd4Da60456

**Comment by catenocrypt** [comment]
As I said, BITTO is OK.  So I will remove the other token.

**Comment by vitalismark** [comment]
Many thanks

**Comment by vitalismark** [comment]
Hello sir, the PR you just merged for me they have an old contract address that is no longer in use. Is there anyway you can remove the logo from the address as to not conflict the two projects?

**Pull request merged**
