### PR TITLE
Add Smartlink baker to Tezos assets

### PR DESCRIPTION
**Pull request by gisele-igore**

### CODE REVIEW

**Comment by gisele-igore** [comment]
Please, I don't understand the conflicts.

**Comment by zachzwei** [comment]
There are errors with your submission.
Please submit a new PR and just modify this file: /assets/blockchains/tezos/validators/list.json to add the validator details.
Then add a separate folder for the logo.
You can reference the new PR with this old one since you already paid for it.

**Comment by catenocrypt** [comment]
I've tried to fix this PR, but could not.  Please create it anew, but from a fresh forked repo.  Best is to remove forked repo completely, and create it anew, so it will be fresh.

**Comment by Smartlinkso** [comment]
Hi, we never received an invoice for this service. Can you guys please send one over? Thanks

**Pull request closed without merging**
