### PR TITLE
Update and Addition of new ICHI Branded Dollars

### PR DESCRIPTION
**Pull request by DTal621**

### CODE REVIEW

**Comment by DTal621** [comment]
Hi @Cryptocool1 - it has been a while since our last update :). If we sent over the payment are we good to have this merged?

**Comment by DTal621** [comment]
@Iamdeadlyz, @Cryptocool1, @cryptomanz Hey team, appreciate all the work you are doing here. Would really love to get this stuff in as we have a few key updates. Can we ensure that this is good to go so that we can send the funds over?

Question on the payment - Is it true that you only accept BEP2 tokens on BNB chain or can we send over BEP20 on BSC?

**Comment by Cryptocool1** [comment]
you should add the tags in new PR
please follow doc https://developer.trustwallet.com/assets/requirements

**Comment by DTal621** [comment]
@Cryptocool1 
1. Can you please provide an answer to the payment question? 
2. I followed this guide - it would be helpful if it was updated: https://community.trustwallet.com/t/how-to-submit-a-token-logo/3863
3. The "contribution guidelines" link on this page is broken: https://developer.trustwallet.com/assets/pr-fee

**Comment by Cryptocool1** [comment]
TWT-BEP2 is supported (Binance Chain), TWT-BEP20 version on Smart Chain is not.

**Comment by DTal621** [comment]
> 

thanks for all your help - fixed PR coming soon :)

**Pull request closed without merging**
