### PR TITLE
DNA token swap information

### PR DESCRIPTION
**Pull request by BloomieBTC**
Updated json and logo for deprecated token
Created json and logo for the replacement token.
@catenocrypt Please add the deprecated token to denylist

### CODE REVIEW

**Comment by BloomieBTC** [comment]
@zachzwei @catenocrypt Can you guys please see why this PR failed the sanity checks?

**Review by BloomieBTC — COMMENTED** [review]
The final update did not pass checks

**Comment by catenocrypt** [comment]
It looks like the problem is that website field cannot be empty.  Please fix.

https://raw.githubusercontent.com/BloomieBTC/assets/master/blockchains/ethereum/assets/0x82b0E50478eeaFde392D45D1259Ed1071B6fDa81/info.json

**Comment by BloomieBTC** [comment]
@catenocrypt 
Done.  Could you also add the old address to denylist and the new address to allowlist?  Also, any tokenlist changes that are needed.

**Comment by catenocrypt** [comment]
Submission looks OK; fee payment pending.

**Comment by catenocrypt** [comment]
Allowlist and Denylist are already updated.

**Comment by catenocrypt** [comment]
Submission is OK; fee payment is pending.

**Comment by BloomieBTC** [comment]
@catenocrypt Is there something wrong with the tokenlist update?

**Comment by BloomieBTC** [comment]
@catenocrypt @Iamdeadlyz @zachzwei The token appears in the wallet now, but the price is not populated.  Can you please fix this?  Thank you.

**Comment by BloomieBTC** [comment]
@vikmeup @catenocrypt @Iamdeadlyz @zachzwei 
Even after the PR merge, the TrustWallet app is still showing the price for the deprecated token instead of the current one.  Can this be changed?  That was part of the reason we created the PR.

**Comment by Iamdeadlyz** [comment]
@BloomieBTC, the price is accurate with CMC.
image

Perhaps, you have another token info page on CMC?

**Comment by BloomieBTC** [comment]
@Iamdeadlyz The price started started working a day ago, thanks!  Could you correct the name field, per json file in the PR?  It should be: 
    "name": "EncrypGen",
    "symbol": "DNA",
TrustWallet is currently showing the name as "DNA."

**Comment by catenocrypt** [comment]
The name is taken from the ERC20 contract, it says 'DNA' there

image

**Comment by BloomieBTC** [comment]
That's probably a mistake made by a contractor hired for the token swap.  We need the name in TrustWallet to match CoinGecko and Coinmarketcap.  A lot of apps rely on TrustWallet's database (especially Uniswap), and we need to stop users from getting confused about having the wrong token.  Can you please help with fixing this?

**Pull request merged**
