### PR TITLE
List giga token

### PR DESCRIPTION
**Pull request by techkaran3**
Payment done successful kindly update the giga logo

Txid
E2CD4207EDA53C71F589BEA6A296B95B1773C63C0B9BA30BF974FFE4F12C9B47

https://explorer.binance.org/tx/E2CD4207EDA53C71F589BEA6A296B95B1773C63C0B9BA30BF974FFE4F12C9B47

### CODE REVIEW

**Comment by techkaran3** [comment]
Please update the logo we have send the payment

**Comment by anonjay** [comment]
@kolya182 Why my pull request taking so long?
https://github.com/anonjay/assets/pull/1/commits

**Comment by catenocrypt** [comment]
Fir PR #2091 was opened about 1 month ago, then it was paid 5 days ago, but that PR was already closed.
Payment for #2091 can be accepted for this PR.

https://explorer.binance.org/tx/E2CD4207EDA53C71F589BEA6A296B95B1773C63C0B9BA30BF974FFE4F12C9B47

**Comment by anonjay** [comment]
@catenocrypt I'm not a part of GIGA, but how long does my PR to be merged?
My payment is prepared right now.
Heres my PR.
https://github.com/anonjay/assets/pull/1/commits

**Comment by techkaran3** [comment]
how much time it will take to add giga token

**Comment by techkaran3** [comment]
i have to pay again for pr?

**Comment by catenocrypt** [comment]
> @catenocrypt I'm not a part of GIGA, but how long does my PR to be merged?
> My payment is prepared right now.
> Heres my PR.
> https://github.com/anonjay/assets/pull/1/commits

@anonjay , that's a PR within your fork, that's wrong.  You have to create a PR to merge to master branch of the trustwallet/assets repo.

**Comment by catenocrypt** [comment]
@techkaran3 , sorry, the naming is wrong.  Address should be a folder, and logo.png should be inside.
Please check README again
https://github.com/trustwallet/assets#repository-structure

```
    ENOTDIR: not a directory, scandir '/home/runner/work/assets/assets/blockchains/ethereum/assets/0x1149cfc37d81304173cd2b203508ab1f6934b81b.png'
```

**Pull request merged**
