### PR TITLE
Add Yellowjay (BEP20)

### PR DESCRIPTION
**Pull request by yellowjaytoken**
Adding info for BEP20 token 'Yellowjay'.

PR created by <a href="https://assets.trustwallet.com">TW Assets Management</a>

### CODE REVIEW

**Comment by Cryptocool1** [comment]
• What is the purpose of this token? How will it benefit Trust Wallet users?
 • How is the token being distributed? Are you conducting an airdrop?
 • Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?
 • Is the token listed on a centralized/decentralized exchange?
 • Is a Smart Contract audit completed? Where can we find this information?

**Comment by yellowjaytoken** [comment]
Our token helps those who want to buy and sell shared servers

We are currently distributing tokens through airdrop and soon I will be
listed in valid exchanges.

For now, we only put ourselves inside the pancake tokens

**Comment by Cryptocool1** [comment]
Feel free to create new PR once you are ready to answer all questions above. Make sure to mention this PR so the fee can be reused

**Comment by yellowjaytoken** [comment]
update logo

**Review by yellowjaytoken — COMMENTED** [review]
update logo

**Pull request closed without merging**
