### PR TITLE
JUL logo update

### PR DESCRIPTION
**Pull request by cryptocoder0x**

### CODE REVIEW

**Comment by RohitChangediya** [comment]
JUL is token for Justliquidity on ETH chain, we have JULb token on BSC chain and we have 43K+ holders

**Comment by Cryptocool1** [comment]
hello,
can you delete unnecessary logo files?

**Comment by RohitChangediya** [comment]
for new PR, there is only 1 logo file @Cryptocool1 . Can you please explain me in details so I can delete the unnecessary files!

**Comment by Cryptocool1** [comment]
blockchains/ethereum/assets/0x5580ab97F226C324c671746a1787524AEF42E415/logo.png 
blockchains/ethereum/assets/0x93effD08e3E5A4B1b40C26137e63876B2501ffA4/logo.png 
 blockchains/smartchain/assets/0x5A41F637C3f7553dBa6dDC2D3cA92641096577ea/logo.png 
 You have 3 logo files.

**Comment by RohitChangediya** [comment]
blockchains/ethereum/assets/0x5580ab97F226C324c671746a1787524AEF42E415/logo.png
 is the recent PR, the other logos are merged in earlier PR!

**Pull request merged**
