### PR TITLE
Info for token Baby Bitcoin (BBTC)

### PR DESCRIPTION
**Pull request by devmexos**
Logo and data about the Baby Bitcoin (BBTC) token are added. BEP-20 Token.

### CODE REVIEW

**Comment by Cryptocool1** [comment]
Hello,
I need you to answer this questions
• What is the purpose of this token? How will it benefit Trust Wallet users?
 • How is the token being distributed? Are you conducting an airdrop?
 • Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?
 • Is the token listed on a centralized/decentralized exchange?
 • Is a Smart Contract audit completed? Where can we find this information?

**Comment by devmexos** [comment]
El 2021-07-25 04:43, CryptoA escribió:

> Hello,
> I need you to answer this questions
> * What is the purpose of this token? How will it benefit Trust Wallet 
> users?
> * How is the token being distributed? Are you conducting an airdrop?
> * Did you sold the tokens at an Initial Coin Offering (ICO) or a token 
> presale?
> * Is the token listed on a centralized/decentralized exchange?
> * Is a Smart Contract audit completed? Where can we find this 
> information?
> 
> --
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub [1], or unsubscribe 
> [2].

Hello CryptoA!

What is the purpose of this token? How will it benefit Trust Wallet 
users?

BabyBitcoin (BBTC) aims to provide, through a transaction tax system, 
continuous benefits for the project holders.

The purpose of the project is to collaborate economically (through token 
distribution) with different global organizations that work to alleviate 
child poverty (in the different axes derived from this problem). 
Reference: https://babybitcoin.finance/first-donation/

How is the token distributed? Are you doing an airdrop?

The token is distributed through the marketplace on PancakeSwap.

Did you sell the tokens in an Initial Coin Offering (ICO) or in a token 
presale?

Yes, we did our presale at DxSale: 
https://dxsale.app/app/pages/defipresale?saleID=4586&chain=BSC

Is the token listed on a centralized / decentralized exchange?

Yes, currently on PancakeSwap: 
https://pancakeswap.info/token/0x5B0Dfe077B16479715C9838eb644892008abbFe6

Has a smart contract audit been completed? Where can we find this 
information?

We use a standard safemoon style contract. We request a complete audit 
with the Techrate company (https://techrate.org/)

Meanwhile, they have sent us a basic audit, which can be viewed at the 
following link: https://babybitcoin.finance/2_5429477276536278794.pdf

Let us know any kind of information you require!

Links:
------
[1] 
https://github.com/trustwallet/assets/pull/12193#issuecomment-886161338
[2]

**Comment by Cryptocool1** [comment]
what will be the benefits for the holders?

**Comment by devmexos** [comment]
El 2021-07-26 07:31, CryptoA escribió:

> what will be the benefits for the holders?
> 
> --
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub [1], or unsubscribe 
> [2].

what will be the benefits for the holders?

- The fee system retains 5% of BBTC transactions, which corresponds to 
3% that goes to liquidity and 2% that is distributed to holders.

- A lottery contract is being developed at BBTC for holders.

- The development of reflections in BTC is being planned in the future.

which global organizations do you work with?

We are evaluating more charitable institutions with which to work to 
carry our social action forward.

In the first instance, on July 19 we coordinated with the "Exodo" 
foundation in El Salvador, to make a donation of 5000 USD.
References:

https://babybitcoin.finance/first-donation/

http://fundacionexodo.org/es/

In the future, we plan to expand our activities to institutions with an 
international scope.

Links:
------
[1] 
https://github.com/trustwallet/assets/pull/12193#issuecomment-886580125
[2]

**Comment by devmexos** [comment]
@Cryptocool1 Hi there! any news regarding the case?
We need to show the token information in Trust Wallet.

**Comment by Cryptocool1** [comment]
awaiting for cmc listing
on hold for now

**Comment by devmexos** [comment]
> awaiting for cmc listing
> on hold for now

 @Cryptocool1 

But we are already listed in CMC or am I wrong?

Check this:
https://coinmarketcap.com/es/currencies/baby-bitcoin/

**Pull request merged**
