### PR TITLE
Adding YOP token

### PR DESCRIPTION
**Pull request by TeamXArmenia**
Adding YOP token logo.
Although we are NOT rolled out yet, but the product is solid, even Ivan on Tech talked about us. Please check us out.

### CODE REVIEW

**Comment by TeamXArmenia** [comment]
Payment done.

**Comment by catenocrypt** [comment]
This token seems to have no usage at all.  Is this the case?  Brand new tokens are not added by Trustwallet.  There is a minimum requirement of 2500 holdfers / 5000 transactions.

https://etherscan.io/token/0xAE1eaAE3F627AAca434127644371b67B18444051

**Comment by TeamXArmenia** [comment]
Thanks for Your prompt reply.
As our project has gained significant traction in the days leading to the
listing we are preparing everything to support our token holders. We
envisage a very wide distribution at TGE. YOP is being launched on
Polkastarter with over 5,000 applications already with more than 8 days to
go.

As you can see in the link https://coinmarketcap.com/currencies/yop/
CoinMarketCap has reviewed our project and under “...but nevertheless
exhibit strengths in a number of areas of Section C...” chosen to list the
coin prior to distribution.

Having a labelled token with our details safe guards our new token holders
from making mistakes. So we kindly request you support us in our launch
phase so the token is verifiable easily with the logo on Uniswap and other
places.

Appreciate your support.

Thanks,

**Comment by TeamXArmenia** [comment]
We are now listed on CMC, CoinGecko, Blockfolio. Please review again.

**Comment by TeamXArmenia** [comment]
$15M traded on DEXes
Uniswap Live Direct Link 🦄

https://info.uniswap.org/pair/0xd65e975c7d0d5871eff8b079120e43c9f377ada1

DEX Tools Direct Link 🔥

https://www.dextools.io/app/uniswap/pair-explorer/0xd65e975c7d0d5871eff8b079120e43c9f377ada1

**Comment by catenocrypt** [comment]
Merging

**Pull request merged**
