### PR TITLE
Add Binance Smart Chain Girl (BEP20)

### PR DESCRIPTION
**Pull request by takuro020301**
Adding info for BEP20 token 'Binance Smart Chain Girl'.

PR created by <a href="https://assets.trustwallet.com">TW Assets Management</a>

### CODE REVIEW

**Comment by takuro020301** [comment]
I am sorry. Could you please change the token logo here?

**Comment by Cryptocool1** [comment]
Can you please create new PR with the correct logo?

**Comment by takuro020301** [comment]
I've acknowledged!

**Comment by takuro020301** [comment]
https://github.com/trustwallet/assets/pull/9049

Here again I applied for the update of the logo icon

**Pull request merged**
