### PR TITLE
Adding diamonds for the first time

### PR DESCRIPTION
**Pull request by abudayeh**
Hello we are the diamond community and I hope diamonds are added, thanks for your efforts.

### CODE REVIEW

**Review by abudayeh — COMMENTED** [review]
Modify ID based on requirements

**Review by abudayeh — COMMENTED** [review]
The link to the market cap and coingecko has been added

**Review by abudayeh — COMMENTED** [review]
Edit link address coingecko

**Comment by cryptomanz** [comment]
As per our policy, brand new tokens are not included, there is a minimum requirement of 10,000 holder addresses and 15,000 transactions, in order to filter out scam tokens.
See the criteria at : https://developer.trustwallet.com/assets/requirements .

**Pull request closed without merging**
