### PR TITLE
Add GIGA BLOCK (BEP20)

### PR DESCRIPTION
**Pull request by Gigablocks**
Adding info for BEP20 token 'GIGA BLOCK'.

PR created by <a href="https://assets.trustwallet.com">TW Assets Management</a>

### CODE REVIEW

**Comment by Cryptocool1** [comment]
• What is the purpose of this token? How will it benefit Trust Wallet users?
 • How is the token being distributed? Are you conducting an airdrop?
 • Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?
 • Is the token listed on a centralized/decentralized exchange?
 • Is a Smart Contract audit completed? Where can we find this information?

**Comment by Gigablocks** [comment]
as we decided token will be use as a transaction in our eco system who is help & support to community including trust wallet also.

token is buying & quiz as primary.

now we are selling in ico. 

we have planning to listing both cex & dex.

yet now audited, if required will give you report on urgent basis, & will send you copy as a audit report will create link for audit report also.

**Comment by Gigablocks** [comment]
hi is it info ok
or
anything else

**Comment by Gigablocks** [comment]
https://github.com/Cryptocool1

Can user put another logo (Polygon Network & ERC20) of same project, means 2 or 3 logo of same project on different blockchain's will consider as a 1 PR or Not

**Comment by Cryptocool1** [comment]
hello, we require smart contract audit. see the requirement here: https://developer.trustwallet.com/assets/requirements

**Comment by sunilinindia** [comment]
[Giga Block-Audit-Report.pdf](https://github.com/trustwallet/assets/files/8320990/Giga.Block-Audit-Report.pdf)

**Comment by Gigablocks** [comment]
[Audit-Report Giga Block.pdf](https://github.com/trustwallet/assets/files/8321035/Audit-Report.Giga.Block.pdf)

**Comment by Gigablocks** [comment]
> hello, we require smart contract audit. see the requirement here: https://developer.trustwallet.com/assets/requirements

Uploaded

**Comment by Gigablocks** [comment]
Pls Merge it

**Comment by Gigablocks** [comment]
> ### PR Summary
> Files OK: 2 Token in PR: **BEP20** 0x8397Eb3EC07615cE88ff854d08e9E27B5155128b Symbol: **GIGA** decimals: 18 Links: [Logo](https://raw.githubusercontent.com/Gigablocks/assets/br0320-232126/blockchains/smartchain/assets/0x8397Eb3EC07615cE88ff854d08e9E27B5155128b/logo.png) [Info](https://raw.githubusercontent.com/Gigablocks/assets/br0320-232126/blockchains/smartchain/assets/0x8397Eb3EC07615cE88ff854d08e9E27B5155128b/info.json) [Website](http://gigablocks.org/) [Explorer](https://bscscan.com/token/0x8397Eb3EC07615cE88ff854d08e9E27B5155128b) Tags: staking, deflationary Token check error: x number of holders not checked: please, check it manually
> 
> 

Pls Merge it

**Comment by Gigablocks** [comment]
https://github.com/cryptomanz 


Can user put another logo (Polygon Network & ERC20) of same project, means 2 or 3 logo of same project on different blockchain's will consider as a 1 PR or Not

**Comment by Lippertt** [comment]
> ### PR Summary
> Files OK: 2
> Token in PR: **BEP20** 0x8397Eb3EC07615cE88ff854d08e9E27B5155128b
> Symbol: **GIGA** decimals: 18
> Links: [Logo](https://raw.githubusercontent.com/Gigablocks/assets/br0320-232126/blockchains/smartchain/assets/0x8397Eb3EC07615cE88ff854d08e9E27B5155128b/logo.png) [Info](https://raw.githubusercontent.com/Gigablocks/assets/br0320-232126/blockchains/smartchain/assets/0x8397Eb3EC07615cE88ff854d08e9E27B5155128b/info.json) [Website](http://gigablocks.org/) [Explorer](https://bscscan.com/token/0x8397Eb3EC07615cE88ff854d08e9E27B5155128b)
> Tags: staking
> Token check error: 
> ❌ number of holders not checked: please, check it manually
> 
> 
> 
> <span style="padding: 5px; background-color: rgb(32,32,32);"></span>
> 
> 
> 
>

**Comment by sunilinindia** [comment]
Thanks

**Pull request merged**
