### PR TITLE
Add USD International (BEP20)

### PR DESCRIPTION
**Pull request by ipsBruno**
Adding info for BEP20 token 'USD International'.

PR created by <a href="https://assets.trustwallet.com">TW Assets Management</a>

### CODE REVIEW

**Comment by Cryptocool1** [comment]
• What is the purpose of this token? How will it benefit Trust Wallet users?
 • How is the token being distributed? Are you conducting an airdrop?
 • Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?
 • Is the token listed on a centralized/decentralized exchange?
 • Is a Smart Contract audit completed? Where can we find this information?

**Comment by ipsBruno** [comment]
https://solidity.finance/audits/USDi/

**Comment by ipsBruno** [comment]
Hello


- What is the purpose of this token? How will it benefit Trust Wallet users?

Users of our token will have access to the site, price and other details, through the graphics that will be incorporated, which will be prepared so that developers will have access to decentralized identifiers.

- How is the token being distributed? Are you conducting an airdrop?

 The token is a dollar-backed stablecoin, each dollar that is bought is paired 1:1 within the blockchain

- Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?
 It is not a ICO or token presale.


- Is the token listed on a centralized/decentralized exchange?
 We will list in UpCâmbio (Brazilian Exchange) and PancakeSwap

- Is a Smart Contract audit completed? Where can we find this information? 
 https://solidity.finance/audits/USDi/

**Comment by Cryptocool1** [comment]
Are you listed on CoinMarketCap?

**Comment by ipsBruno** [comment]
> Are you listed on CoinMarketCap?

Not yet

**Comment by Cryptocool1** [comment]
Feel free to create new PR once requirements are met. Make sure to mention this Pull Request so the fee can be reused

**Pull request closed without merging**
