### PR TITLE
Add AnpanSwap Token (BEP20)

### PR DESCRIPTION
**Pull request by anpanswapadmin**
Adding info for BEP20 token 'AnpanSwap Token'.

PR created by <a href="https://assets.trustwallet.com">TW Assets Management</a>

### CODE REVIEW

**Comment by cryptomanz** [comment]
can you please add links to your PR?
example:https://developer.trustwallet.com/assets/repository_details

**Comment by anpanswap** [comment]
We done of adding links to your PR

**Comment by anpanswap** [comment]
We done of adding links to my PR

**Comment by ramsty** [comment]
Hi!
Could you answer some questions?
• What is the purpose of this token? How will it benefit Trust Wallet users?
• How is the token being distributed? Are you conducting an airdrop?
• Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?
• Is the token listed on a centralized/decentralized exchange?
• Is a Smart Contract audit completed? Where can we find this information?

**Comment by anpanswap** [comment]
• What is the purpose of this token? How will it benefit Trust Wallet users?
-> ANPAN token is at the heart of the AnpanSwap ecosystem. Users buy it on the Exchange. Earn it on Stake & Farms. Win it on Lottery. And spend it around the world. Trust Wallet users can connect to anpanswap.finance for their exchange, liquidity adding, farming, staking,...
• How is the token being distributed? Are you conducting an airdrop?
-> We already listed on anpanswap.finance and pancakeswap and users buy from there. Airdrop was finished but token will be distributed on November 16th.
• Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?
-> Yes.
• Is the token listed on a centralized/decentralized exchange?
-> Token will be listed on November 1st 5PM GMT+8 on coinsbit.io (https://twitter.com/c0insbit/status/1453431081227722754) and https://international.indoex.io/ (https://twitter.com/Indoex_LTD/status/1454353236064804871)
• Is a Smart Contract audit completed? Where can we find this information?
-> All our small contracts were audited & passed by TechRate, including our ANPAN token that you can view at TechRate github at link: https://github.com/TechRate/Smart-Contract-Audits/blob/main/October/AnpanToken.pdf

**Comment by ramsty** [comment]
Your logo should be a full screen 256*256 px
Example:
https://community.trustwallet.com/t/how-to-submit-a-token-logo/3863

**Comment by anpanswap** [comment]
We already changed our logo.png with full screen and 256x256 px size: https://raw.githubusercontent.com/anpanswap/assets/master/blockchains/binance/assets/0x10B0a78520fBDDa95aDc331445d9319B164F85D5/logo.png . Thank you.

**Comment by anpanswap** [comment]
Hi, can I change photo of logo.png? it seems that I misunderstand your requirement. You only request size is 256x256px but I understand need to have a square white background. Thank you.

**Comment by anpanswap** [comment]
Hi, can we change photo of logo.png? it seems that I misunderstand your requirement. You only request size is 256x256px but I understand need to have a square white background. So now look like photo of logo very small. Thank you.

**Comment by anpanswap** [comment]
hi, we already updated logo.png (https://raw.githubusercontent.com/anpanswap/assets/master/blockchains/binance/assets/0x10B0a78520fBDDa95aDc331445d9319B164F85D5/logo.png), can we re-open pull request to update logo.png?

**Pull request merged**
