### PR TITLE
Update Logo In Trust Wallet for EverGrow

### PR DESCRIPTION
**Pull request by Cryptonaire01**
Hello Please help update Logo for EverGrow on Trust Wallet

### CODE REVIEW

**Comment by Cryptonaire01** [comment]
[0xc001bbe2b87079294c63ece98bdd0a88d761434e.zip](https://github.com/trustwallet/assets/files/9426473/0xc001bbe2b87079294c63ece98bdd0a88d761434e.zip)

**Comment by Cryptonaire01** [comment]
Please update EverGrow Details and Logo for Trust Wallet.

We have already paid the fee - check "Update logo for $EGC #16409"

We paid 5BNB and you did not update the logo and name

**Comment by Cryptonaire01** [comment]
image

**Comment by Cryptonaire01** [comment]
image

**Comment by Cryptonaire01** [comment]
image

**Comment by Cryptonaire01** [comment]
image

**Comment by Cryptonaire01** [comment]
Everything you need is here: logo.png and info.json

[0xc001bbe2b87079294c63ece98bdd0a88d761434e.zip](https://github.com/trustwallet/assets/files/9426561/0xc001bbe2b87079294c63ece98bdd0a88d761434e.zip)

**Comment by Cryptocool1** [comment]
hello, what's wrong with your logo?

**Comment by Cryptocool1** [comment]
send your correct logo here, please

**Comment by Cryptonaire01** [comment]
Hello we have changed the design of our logo and changed the name from EverGrow Coin to EverGrow

**Comment by Cryptonaire01** [comment]
logo

**Comment by Cryptonaire01** [comment]
Display name: EverGrow

**Comment by Cryptocool1** [comment]
hello, the fee is required for updating. 
see: https://developer.trustwallet.com/assets/pr-fee

**Comment by Cryptonaire01** [comment]
we already paid the fee and you did not do anything. Please proceed accordingly

**Comment by Cryptonaire01** [comment]
check the screenshot I have attached above in comments

**Comment by Cryptocool1** [comment]
Your previous PR merged. For any updates we require the fee

**Comment by Cryptonaire01** [comment]
We will not double pay for your incompetence.
This is frustrating as you said the updated was done and and nothing happened

**Comment by Cryptonaire01** [comment]
you closed the request without making the update

**Comment by Cryptonaire01** [comment]
please proceed and update the Logo and Name

**Comment by Cryptocool1** [comment]
Here is the first Pull request https://github.com/trustwallet/assets/pull/14177 (merged successfully)
If you want to update your logo you should pay the fee
Please all information about the fee here:  https://developer.trustwallet.com/assets/pr-fee

**Comment by Cryptonaire01** [comment]
https://github.com/trustwallet/assets/pull/14177 is the first time we Pulled a request for our token, when we launched -  we paid 2 BNB (fee at that time)

Then I asked for Update logo and name, and we paid 5BNB (fee at that time) #16409

**Comment by Cryptonaire01** [comment]
Sorry for my bad language earlier. But it's frustrating as we asked this for months

**Comment by Cryptocool1** [comment]
> Sorry for my bad language earlier. But it's frustrating as we asked this for months

We will create PR on our own and update you logo and name today. 
Your name should be EverGrow?

**Comment by Cryptonaire01** [comment]
Yes EverGrow

**Comment by Cryptocool1** [comment]
> Yes EverGrow

Ok, we will update it today

**Comment by Cryptonaire01** [comment]
Thank you! Please let me know once you have processed it

**Comment by Cryptocool1** [comment]
https://github.com/trustwallet/assets/pull/22177
Please check if everything is ok for you

**Comment by Cryptonaire01** [comment]
It doesn't show yet, do I need to do anything?

**Comment by Cryptocool1** [comment]
> It doesn't show yet, do I need to do anything?

Just check if everything is ok in the PR I sent you

**Comment by Cryptonaire01** [comment]
all details are correct 
only the website is now under https://evergrowegc.com/
but it will redirect from old website to new website

**Pull request closed without merging**
