### PR TITLE
Add Santa Floki v2.0 (BEP20)

### PR DESCRIPTION
**Pull request by Santaflokiofficial**
Adding info for BEP20 token 'Santa Floki v2.0'.

PR created by <a href="https://assets.trustwallet.com">TW Assets Management</a>

### CODE REVIEW

**Comment by Santaflokiofficial** [comment]
Please check PR 18473, Payment has been done as well + logo has been modified.
________________________________

**Comment by cryptomanz** [comment]
#18473

**Comment by cryptomanz** [comment]
• What is the purpose of this token? How will it benefit Trust Wallet users?
 • How is the token being distributed? Are you conducting an airdrop?
 • Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?
 • Is the token listed on a centralized/decentralized exchange?
 • Is a Smart Contract audit completed? Where can we find this information?

**Comment by Santaflokiofficial** [comment]
1.

Santa Floki is a BSC project that wants to fulfill the needs of its investors by building a good brand, community, and purpose this holiday season. It is based on the philosophy that those who want to do good should come together and contribute to the less fortunate. It believes in the principles of sharing wealth through passive BUSD income and planning to donate to reputable charities such as Save The Children.

The inception of this project was through the collective mind of very experienced investors and project owners in the BSC space. Together they have reviewed and studied many projects that either have succeeded or faltered. They then decided on the important of creating something that is not only genuine, but specifically geared towards the benefit of would-be investors.

In establishing this project, the main problem statements that we want to address are as follows:

     *   How to bring a community together whose mission is not only to achieve financial freedom but also be able to help improve the lives of those in need.

     *   How to ensure the safety of people's investments so that they can confidently sleep at night knowing that their funds are secure and that the team is working towards increasing its value. The debilitating reputation of the BSC space is marred by projects that don't prioritize the welfare of its investors and community. This is what we want to address and to provide a solution for.

Our approach to problem statement number one is to develop an effective structure that gives the project the ability to sustain its operations so that the project will be in a position to grow and succeed. The tokenomics support the need to provide for marketing and to cover the costs of day to day operations. By securing these pillars, we are then in a better position to help fulfill the goal of our investors - to make a profit. This is achieved by the smart contract which rewards our investors 4% of every buy and sell transaction in the form of BUSD. The BUSD rewards are calculated based on the amount of SantaFloki tokens an investor holds in relation to the total supply. The more they hold, the larger the share of the rewards they receive. This also incentivizes an investor to continue holding SantaFloki to benefit from the BUSD rewards. The more investors hold, the stronger the project becomes.

Next, is through the effectiveness of the smart contract that we are implementing that provides security the investors need and expect. The transactions will be enforced automatically and are essential for stable price actions, which will guarantee that investors can buy and sell at any time.

2. This is a migration to a V2.  V1 link on Coinmarketcap is https://coinmarketcap.com/currencies/santa-floki/
[https://s2.coinmarketcap.com/static/img/coins/200x200/14846.png]<https://coinmarketcap.com/currencies/santa-floki/>
Santa Floki price today, HOHOHO to USD live, marketcap and chart | CoinMarketCap<https://coinmarketcap.com/currencies/santa-floki/>
HOHOHO Price Live Data. The live Santa Floki price today is $4.03e-7 USD with a 24-hour trading volume of $304,324 USD.. We update our HOHOHO to USD price in real-time. Santa Floki is up 69.47% in the last 24 hours. The current CoinMarketCap ranking is #3708, with a live market cap of not available.
coinmarketcap.com

  2.  3. We did a 250 bnb presale + we migrated as some changes needed to be done for our coin to continue the development that has been planned.
  3.  4. The token is only listed on Pancakeswap for the moment. DEX.
  4.  5.Our V2 audit can be found here.  https://www.santafloki.com/_files/ugd/4ebc1f_47993e335aaf43a3a669d1a56fd66369.pdf

Please let me know if you need any other clarification.
King regards

  1.

________________________________

**Comment by Santaflokiofficial** [comment]
Hi Nazar,

Is everything fine with the application now? Mostly what happened is that we migrated to a new contract, we did a new listing on CoinMarketCap. So we are doing all the process over again.
________________________________

**Comment by cryptomanz** [comment]
can you send an official announcement about migration ?

**Comment by Santaflokiofficial** [comment]
Yes!

https://twitter.com/Santa_Floki/status/1496413286358781956
Santa Floki on Twitter: "Announcement. @Santa_Floki ($HoHoHo) v2.0 is a relaunch for our game and metaverse utility Santa Floki v2 (HoHoHo v2). Contract address: 0x14940169E2Db1595CDD3CACd30DECC5bbB4d9f19 We have submitted a new listing application to CoinMarketCap, #407076. @CoinMarketCap"<https://twitter.com/Santa_Floki/status/1496413286358781956>
Announcement. @Santa_Floki ($HoHoHo) v2.0 is a relaunch for our game and metaverse utility Santa Floki v2 (HoHoHo v2). Contract address ...
twitter.com

________________________________

**Comment by Santaflokiofficial** [comment]
@cryptomanz  is there any more info that you need from us?

**Comment by Santaflokiofficial** [comment]
@Cryptocool1

**Comment by cryptomanz** [comment]
#18511

**Pull request closed without merging**
