### PR TITLE
Add logo and info.json

### PR DESCRIPTION
**Pull request by heisenberghoge**
Request for logo asset

### CODE REVIEW

**Comment by heisenberghoge** [comment]
I have sent 2 BNB, here's the tx: https://explorer.binance.org/tx/7226ABAE2CB258427D4436A2646D25FFA886846C605FA1039F5F6C9ACCF16831

**Comment by catenocrypt** [comment]
Please add following missing fields to info.json:

```json
  "type": "ERC20",
  "symbol": "HOGE",
  "decimals": 9,
  "status": "active",
  "id": "0xfAd45E47083e4607302aa43c65fB3106F1cd7607"
```

**Comment by heisenberghoge** [comment]
info.json updated

**Comment by catenocrypt** [comment]
Thanks for the fix; unfortunately there are some more fixes to be done -- I tried to do them, but I have no write permission to you source repo.

- The `short_description` field in the info.json should be simply `description`, please rename.
- The contract in the folder name should be in 'checksum' format,  please rename (commands below).

```
git mv blockchains/ethereum/assets/0xfad45e47083e4607302aa43c65fb3106f1cd7607 blockchains/ethereum/assets/0xfAd45E47083e4607302aa43c65fB3106F1cd7607.RENAME
git mv blockchains/ethereum/assets/0xfAd45E47083e4607302aa43c65fB3106F1cd7607.RENAME blockchains/ethereum/assets/0xfAd45E47083e4607302aa43c65fB3106F1cd7607
```

**Comment by heisenberghoge** [comment]
updated, thanks!

**Comment by heisenberghoge** [comment]
@catenocrypt

**Pull request merged**
