### PR TITLE
Add BabyDogeCash logo and info

### PR DESCRIPTION
**Pull request by babydogecash**
BabyDogeCash

### CODE REVIEW

**Comment by cryptomanz** [comment]
hello,
what is the purpose of your token?

**Comment by babydogecash** [comment]
Hello 




Our main purpose is to create charity events and raising funds for god shelters around the world. 
Also our smart contract protocol provides auto yield and liquidity generation for the token holders. 
Kind regards,
BabyDogeCash.com

**Comment by babydogecash** [comment]
Also, you can check our whitepaper on https://babydogecash.com

**Comment by babydogecash** [comment]
Please let me know if I need to provide other pieces of information.

Thank you.

**Comment by babydogecash** [comment]
Hi. Can you let me know if everything is alright with the application, and how long it will take for the logo to appear on TrustWallet. Thank you

**Comment by Cryptocool1** [comment]
This token will be on hold until CMC listing

**Comment by babydogecash** [comment]
Are tokens similar to ours, are not listed on CMC but they get the logo straight away. I double-checked tokens without a whitepaper, not much information on their website, fewer holders. fewer community members and they get the logo straight away . We appreciate it if we can rush this process, our project has just for today a $3,197,590 trading volume, we have a big community of 7000 holders waiting for this logo.  Thank you.

Please check our website again if you missed any other information. 

https://babydogecash.com

Kind regards

BabyDogeCash team.

**Comment by Cryptocool1** [comment]
Is a Smart Contract audit completed?

**Comment by babydogecash** [comment]
Yes 


Sent from Yahoo Mail for iPhone


On Thursday, July 8, 2021, 12:28 pm, CryptoA ***@***.***> wrote:




Is a Smart Contract audit completed?

**Comment by Cryptocool1** [comment]
please create new PR when your token will be listed on CMC
make sure to mention this PR so that fee can can be reused

**Comment by babydogecash** [comment]
WE ARE LISTED ON CMC 

https://coinmarketcap.com/currencies/baby-doge-cash/

**Pull request merged**
