### PR TITLE
logo.png

### PR DESCRIPTION
**Pull request by sadbabytoken**
This PR is being closed due to inactivity. If you wish to continue, please have us reopen the PR before sending your payment, or just create a new one.
Do NOT send payments for closed PR, as the fee may by lost!
  (48 vs. 48 hrs)

### CODE REVIEW

**Comment by sadbabytoken** [comment]
hello i want to reopen my request

**Review by sadbabytoken — COMMENTED** [review]
hello i want to reopen my request

**Comment by sadbabytoken** [comment]
hello i want to reopen my request

**Review by sadbabytoken — COMMENTED** [review]
Hello, we want to publish our logo, can you help?

**Comment by Cryptocool1** [comment]
please create new PR

**Pull request closed without merging**
