### PR TITLE
Add Celestia, Terra2, Persistence & Secret Stakely validator info

### PR DESCRIPTION
**Pull request by iicc1**

### CODE REVIEW

**Comment by cryptomanz1** [comment]
Hello, can you send the transaction hash for the payment?

**Comment by iicc1** [comment]
> Hello, can you send the transaction hash for the payment?

0xa8f0eb7b5f990b8d6842e9077a14db6d12342df990cbcdbe10f9d385fa595a5d

**Comment by Cryptocool1** [comment]
Please update your branch with the recent master

**Comment by iicc1** [comment]
> Please update your branch with the recent master

Branch updated

**Pull request merged**
