### PR TITLE
Updated logo and twitter information

### PR DESCRIPTION
**Pull request by dogefatherBSC**
This including new logo, and twitter information update. The old account (https://twitter.com/dogefatherBSC) is suspended, and now we're moving to https://twitter.com/dogefatherbsc_

### CODE REVIEW

**Comment by dogefatherBSC** [comment]
https://explorer.binance.org/tx/8CA33A47825355D735EF8DC1E88C41115CE4337DCA4C79817DC7A3DE79CE8F80

**Comment by Cryptocool1** [comment]
Hello,
can you capitalize all letters in your symbol?

**Comment by dogefatherBSC** [comment]
done

**Comment by Cryptocool1** [comment]
> done

Sorry, you need to capitalize all letters in your symbol, not name )

**Pull request merged**
