### PR TITLE
Add HedgePay Logo and Description

### PR DESCRIPTION
**Pull request by hedgepaybsc**
Add HedgePay Logo and Description

### CODE REVIEW

**Comment by hedgepaybsc** [comment]
It got rejected because we didn't send any payment?
Is the minimum criteria is subjective?

**Comment by Cryptocool1** [comment]
• What is the purpose of this token? How will it benefit Trust Wallet users?
 • How is the token being distributed? Are you conducting an airdrop?
 • Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?
 • Is the token listed on a centralized/decentralized exchange?
 • Is a Smart Contract audit completed? Where can we find this information?

**Comment by hedgepaybsc** [comment]
1. Bring passive rewards to holders and share the profits of goods and services sold by our platform. We are Defi, utility token, and provide services like Launchpad, KYC, Auditing, AMA, liquidity locking, vault service and contract service. 
HedgePay website are integrated with Trust Wallet that benefits 70% of our holders hedgepay.org

2. Sold in presale, sold in open market on DEX and on Routing exchange and airdrop is completed.

3. Yes Presale. Over Pinksale and our own IDO platform, link as below:
Pinksale: https://www.pinksale.finance/#/launchpad/0x7883E6D5f0f7ddC8F7740C711427Cd2D0b79BfcF?chain=BSC
HedgePay Launchpad: https://hedgepay.org/ido/0xF8B7d0829086dA0A7681f27Dd0abEB4dDEb17044

4. DEX, yes on Pancakeswap. CEX, not yet. Talking to few right now.

5. Had in-house audit and 3rd part audit as below:
In-house- https://github.com/hedgepaybsc/files/blob/main/HedgePay%20Solidity%20Smart%20Audit%20Report.pdf
SpyWolf- https://github.com/SpyWolfNetwork/Smart_Contract_Audits/blob/main/February/HedgePay_0xc75aa1fa199eac5adabc832ea4522cff6dfd521a.pdf

Additional info:
https://coinmarketcap.com/currencies/hedgepay/
https://linktr.ee/hedgepay

Liquidity locked link:
https://www.pinksale.finance/#/pinklock/record/20300?chain=BSC
https://bscscan.com/address/0xa0a1e7571f938cc33dad497849f14a0c98b30fd0

**Comment by Cryptocool1** [comment]
please see our Listing Acceptance Guidelines here: https://developer.trustwallet.com/assets/requirements
- A full token audit is completed by reputable security audit groups.(Certik, Techrate, Hacken, Dessert Finance)

**Comment by Cryptocool1** [comment]
please come back to us once all criteria are met

**Comment by hedgepaybsc** [comment]
Did SkyWolf and its not cheap and equivalent price as Techrate and Dessert Finance. I'll wait a bit more until i'll  go for Techrate and Dessert Finance. 
Right now HedgePay contract are currently the biggest in BSC chain with #65 contract. Did not know trust wallet requires such audit else i would go for those. Couldn't afford 314 BNB for another audit yet. 
https://bscscan.com/address/0xc75aa1fa199eac5adabc832ea4522cff6dfd521a/#code

Thank you for replying
Have a nice day

**Comment by hedgepaybsc** [comment]
[LuxeRacing Receipt.pdf](https://github.com/trustwallet/assets/files/8045302/LuxeRacing.Receipt.pdf)

Want you know that we did SkyWolf because they are pinksale audit partners. They have few others, ContractChecker, Freshcoins, InterFi, SpyWolf, Tech Audit, Coinscope, AnalytixAudit, Audit Rate Tech, Rug Free Coins, 0xGuard and SolidProof.

SkyWolf is one the best in the list and perform bug checked with proper reporting. Would you mind to take a look again, i have put in the file.

**Pull request closed without merging**
