### PR TITLE
Add files via upload

### PR DESCRIPTION
**Pull request by climbtoken**
Please add logo and info to MARS

### CODE REVIEW

**Comment by climbtoken** [comment]
We have a DEX with masterchef, we have mmore than 2500 holders

**Comment by climbtoken** [comment]
https://explorer.binance.org/address/bnb1tqq9llyr3dyjd559dha6z5r5etk3qfwk07m098

**Comment by climbtoken** [comment]
https://explorer.binance.org/tx/4C699C646F48E44E876D5D2B2A0E4FE088C409BA876619D75D0E6C19E2197E06

**Comment by Cryptocool1** [comment]
As per our policy, brand new tokens are not included, there is a minimum requirement of 2500 holder addresses and 5000 transactions, in order to filter out scam tokens.
See the criteria at (mentioned in the first message by the bot): https://community.trustwallet.com/t/how-to-submit-a-token-logo/3863).

**Comment by climbtoken** [comment]
We are the CLIMB token team that is already in trust wallet. Our MARs token has more than 2500 holders, only most have their tokens in our masterchef contract. The same happened with CLIMB and you did let us place the token in trust.

**Comment by climbtoken** [comment]
> We are the CLIMB token team that is already in trust wallet. Our MARs token has more than 2500 holders, only most have their tokens in our masterchef contract. The same happened with CLIMB and you did let us place the token in trust.

@Cryptocool1

**Pull request merged**
