### PR TITLE
Updated information and logo for VEMP

### PR DESCRIPTION
**Pull request by MikeVEMP**
Updated social links and new logo for VEMP

### CODE REVIEW

**Comment by MikeVEMP** [comment]
Hi there, I just realised I need to update the ERC20 version too, am I able to do that under the same PR please?

**Comment by Cryptocool1** [comment]
Yes, you need to add necessary files in this PR

**Comment by CustomerTeam001** [comment]
> Hi there, I just realised I need to update the ERC20 version too, am I able to do that under the same PR please?

We'd be happy to look into this for you 
kindly file a support ticket below 
https://forms.gle/FhSmn4AznQtZcruX8

**Comment by MikeVEMP** [comment]
Actually it looks like the Ethereum was pulling the same info as the BSC version, as it has the same information and the new logo already.

**Comment by Tegimufranka9639** [comment]
https://link.trustwallet.com/open_coin?asset=c60https://github.com/Tegimufranka9639/fuzzy-funicular/issues/1

**Comment by Tegimufranka9639** [comment]
https://link.trustwallet.com/wc?uri=wc%3Aca1fccc0-f4d1-46c2-90b7-c07fce1c0cae%401%3Fbridge%3Dhttps%253A%252F%252Fbridge.walletconnect.org%26key%3Da413d90751839c7628873557c718fd73fcedc5e8e8c07cfecaefc0d3a178b1d8

**Pull request closed without merging**
