### PR TITLE
Add MilkyWayEx logo and info

### PR DESCRIPTION
**Pull request by milkywayexfinance**
Add MilkyWayEx logo and info

### CODE REVIEW

**Comment by ramsty** [comment]
Hi!
Could you answer some questions?
• What is the purpose of this token? How will it benefit Trust Wallet users?
• How is the token being distributed? Are you conducting an airdrop?
• Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?
• Is the token listed on a centralized/decentralized exchange?
• Is a Smart Contract audit completed? Where can we find this information?

**Comment by milkywayexfinance** [comment]
> Hi! Could you answer some questions? • What is the purpose of this token? How will it benefit Trust Wallet users? • How is the token being distributed? Are you conducting an airdrop? • Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale? • Is the token listed on a centralized/decentralized exchange? • Is a Smart Contract audit completed? Where can we find this information?

1. Our project is a launchpad platform, so this token will be staked by users to participate in IDO and INO. We have a public holder round so trust wallet users can hold tokens in their wallet to participate in that round
2. Our project has been running for over a month and we plan to periodically vesting on the 16th of every month.
https://milkywayex-document.gitbook.io/milkywayex/tokenomics/milkwayex-tokenomics
3. Our project has been opened to sell ICO on the BrandPad platform and on our own platform 1 month ago
4. Our tokens are listed on Pancakeswap and BabySwap (Decentralized) and ZT exchange. we are also fully listed on Coinmarketcap and Coingecko.
CMC link: https://coinmarketcap.com/currencies/milkywayex/
CGK link: https://www.coingecko.com/en/coins/milkywayex
Poopcoin link: https://poocoin.app/tokens/0xa7002fccc20f10a38c579a8d2d14d34f2a9a02a5
5. Our Smart Contract audit completed. You can check it with 2 links below:
Certik: https://www.certik.com/projects/milkywayex-finance
SolidProof: https://github.com/solidproof/smart-contract-audits/blob/main/SmartContract_Audit_Solidproof_MilkyWayEx.pdf

**Comment by cryptomanz** [comment]
As per our policy, brand new tokens are not included, there is a minimum requirement of 10,000 holder addresses and 20,000 transactions, in order to filter out scam tokens.
See the criteria at : https://developer.trustwallet.com/assets/requirements.

**Comment by Cryptocool1** [comment]
Please come back to us when all criteria are met.
When creating a new PR make sure to mention this PR, so that we can see that fee has been paid already here.

**Pull request closed without merging**
