### PR TITLE
add narwhalswap protocol

### PR DESCRIPTION
**Pull request by narwhalosaurus**

### CODE REVIEW

**Comment by Iamdeadlyz** [comment]
As per our policy, brand new tokens are not included. There is a minimum requirement of 2500 holder addresses and 5000 transactions (airdropped tokens excluded) in order to filter out scam tokens. See the criteria at (mentioned in the first message by the bot): https://community.trustwallet.com/t/how-to-submit-a-token-logo/3863#how-to-get-approved

This token has below-limit usage yet. This pull request will be put on hold. Please come back to us when all criteria are met.
https://bscscan.com/token/0xa1303e6199b319a891b79685f0537d289af1fc83 (824 holders & 132,386 tx)
https://bscscan.com/token/0x8f4087cb09e0f378f4278a314c94a636665de24b (441 holders & 15,129 tx)
https://bscscan.com/token/0x4bbb275012ebe258556b8debe5c07be98e8d3859 (47 holders & 6,062 tx)

**Comment by narwhalosaurus** [comment]
> As per our policy, brand new tokens are not included. There is a minimum requirement of 2500 holder addresses and 5000 transactions (airdropped tokens excluded) in order to filter out scam tokens. See the criteria at (mentioned in the first message by the bot): https://community.trustwallet.com/t/how-to-submit-a-token-logo/3863#how-to-get-approved
> 
> This token has below-limit usage yet. This pull request will be put on hold. Please come back to us when all criteria are met.
> https://bscscan.com/token/0xa1303e6199b319a891b79685f0537d289af1fc83 (824 holders & 132,386 tx)
> https://bscscan.com/token/0x8f4087cb09e0f378f4278a314c94a636665de24b (441 holders & 15,129 tx)
> https://bscscan.com/token/0x4bbb275012ebe258556b8debe5c07be98e8d3859 (47 holders & 6,062 tx)

In Smart Chain, We have found other token haven't reaches 2500 holder addresses but They have been got approve.
https://bscscan.com/token/0xfd26889cd6454d8751562f1c0fcf88b18b46f7b7
https://bscscan.com/token/0xe10e9822a5de22f8761919310dda35cd997d63c0
https://bscscan.com/token/0x393b312c01048b3ed2720bf1b090084c09e408a1

So that 2500 holders weren't reason to reject us to scam. You can check us at [https://t.me/narwhalswap](https://t.me/narwhalswap) Please considered again. we have been in Smart Chain around 2 month.

**Comment by Iamdeadlyz** [comment]
> > As per our policy, brand new tokens are not included. There is a minimum requirement of 2500 holder addresses and 5000 transactions (airdropped tokens excluded) in order to filter out scam tokens. See the criteria at (mentioned in the first message by the bot): https://community.trustwallet.com/t/how-to-submit-a-token-logo/3863#how-to-get-approved
> > This token has below-limit usage yet. This pull request will be put on hold. Please come back to us when all criteria are met.
> > https://bscscan.com/token/0xa1303e6199b319a891b79685f0537d289af1fc83 (824 holders & 132,386 tx)
> > https://bscscan.com/token/0x8f4087cb09e0f378f4278a314c94a636665de24b (441 holders & 15,129 tx)
> > https://bscscan.com/token/0x4bbb275012ebe258556b8debe5c07be98e8d3859 (47 holders & 6,062 tx)
> 
> In Smart Chain, We have found other token haven't reaches 2500 holder addresses but They have been got approve.
> https://bscscan.com/token/0xfd26889cd6454d8751562f1c0fcf88b18b46f7b7
> https://bscscan.com/token/0xe10e9822a5de22f8761919310dda35cd997d63c0
> https://bscscan.com/token/0x393b312c01048b3ed2720bf1b090084c09e408a1
> 
> So that 2500 holders weren't reason to reject us to scam. You can check us at https://t.me/narwhalswap Please considered again. we have been in Smart Chain around 2 month.

The tokens that you have mentioned were accepted since we have different requirements at that time (even the fees were different). For your reference, check #4575 #4403.

**Comment by narwhalosaurus** [comment]
Nope, I already see the requirement already added before the token that i mention approved. The fees just change in 1 month ago but requirement not changed. Are you a decided person in the Trust team? Let's us talk with him? I think Trust team understand and special support on Binance Smart Chain.

**Comment by narwhalosaurus** [comment]
> > > As per our policy, brand new tokens are not included. There is a minimum requirement of 2500 holder addresses and 5000 transactions (airdropped tokens excluded) in order to filter out scam tokens. See the criteria at (mentioned in the first message by the bot): https://community.trustwallet.com/t/how-to-submit-a-token-logo/3863#how-to-get-approved
> > > This token has below-limit usage yet. This pull request will be put on hold. Please come back to us when all criteria are met.
> > > https://bscscan.com/token/0xa1303e6199b319a891b79685f0537d289af1fc83 (824 holders & 132,386 tx)
> > > https://bscscan.com/token/0x8f4087cb09e0f378f4278a314c94a636665de24b (441 holders & 15,129 tx)
> > > https://bscscan.com/token/0x4bbb275012ebe258556b8debe5c07be98e8d3859 (47 holders & 6,062 tx)
> > 
> > 
> > In Smart Chain, We have found other token haven't reaches 2500 holder addresses but They have been got approve.
> > https://bscscan.com/token/0xfd26889cd6454d8751562f1c0fcf88b18b46f7b7
> > https://bscscan.com/token/0xe10e9822a5de22f8761919310dda35cd997d63c0
> > https://bscscan.com/token/0x393b312c01048b3ed2720bf1b090084c09e408a1
> > So that 2500 holders weren't reason to reject us to scam. You can check us at https://t.me/narwhalswap Please considered again. we have been in Smart Chain around 2 month.
> 
> The tokens that you have mentioned were accepted since we have different requirements at that time (even the fees were different). For your reference, check #4575 #4403.

Nope, I already see the requirement already added before the token that i mention approved. The fees just change in 1 month ago but requirement not changed. Are you a decided person in the Trust team? Let's us talk with him? I think Trust team understand and special support on Binance Smart Chain.

**Comment by Iamdeadlyz** [comment]
> > > > As per our policy, brand new tokens are not included. There is a minimum requirement of 2500 holder addresses and 5000 transactions (airdropped tokens excluded) in order to filter out scam tokens. See the criteria at (mentioned in the first message by the bot): https://community.trustwallet.com/t/how-to-submit-a-token-logo/3863#how-to-get-approved
> > > > This token has below-limit usage yet. This pull request will be put on hold. Please come back to us when all criteria are met.
> > > > https://bscscan.com/token/0xa1303e6199b319a891b79685f0537d289af1fc83 (824 holders & 132,386 tx)
> > > > https://bscscan.com/token/0x8f4087cb09e0f378f4278a314c94a636665de24b (441 holders & 15,129 tx)
> > > > https://bscscan.com/token/0x4bbb275012ebe258556b8debe5c07be98e8d3859 (47 holders & 6,062 tx)
> > > 
> > > 
> > > In Smart Chain, We have found other token haven't reaches 2500 holder addresses but They have been got approve.
> > > https://bscscan.com/token/0xfd26889cd6454d8751562f1c0fcf88b18b46f7b7
> > > https://bscscan.com/token/0xe10e9822a5de22f8761919310dda35cd997d63c0
> > > https://bscscan.com/token/0x393b312c01048b3ed2720bf1b090084c09e408a1
> > > So that 2500 holders weren't reason to reject us to scam. You can check us at https://t.me/narwhalswap Please considered again. we have been in Smart Chain around 2 month.
> > 
> > 
> > The tokens that you have mentioned were accepted since we have different requirements at that time (even the fees were different). For your reference, check #4575 #4403.
> 
> Nope, I already see the requirement already added before the token that i mention approved. The fees just change in 1 month ago but requirement not changed. Are you a decided person in the Trust team? Let's us talk with him? I think Trust team understand and special support on Binance Smart Chain.

Yes, I am one of the maintainers. Then again, those tokes were approved since the requirements were different (in regards to holders and tx). It was much lower at that time. Let me know if you've established usage by meeting the new requirements as stated earlier, so I can re-open this one.

**Comment by narwhalosaurus** [comment]
Can trust wallet only add the Narwal Dapp logo before?

**Comment by Iamdeadlyz** [comment]
> Can trust wallet only add the Narwal Dapp logo before?

Please read this guide regarding DApp logos: https://community.trustwallet.com/t/i-am-a-developer-and-i-want-to-contribute/184#connect-your-dapp

**Comment by narwhalosaurus** [comment]
> > Can trust wallet only add the Narwal Dapp logo before?
> 
> Please read this guide regarding DApp logos: https://community.trustwallet.com/t/i-am-a-developer-and-i-want-to-contribute/184#connect-your-dapp

I already add Dapp logo in commit
and I think NAR token reached the requirement.
plz add us

**Comment by narwhalosaurus** [comment]
https://bscscan.com/token/0xa1303e6199b319a891b79685f0537d289af1fc83 (3899 holders)

**Comment by narwhalosaurus** [comment]
Thank you very much

**Pull request merged**
