### PR TITLE
change address of LCT

### PR DESCRIPTION
**Pull request by lightcoinex**
#398 we change the token contract

### CODE REVIEW

**Comment by Iamdeadlyz** [comment]
Remove the Trust Wallet logo in the list of partners, see: https://github.com/trustwallet/assets#disclaimer. Else, this will be misleading.

**Comment by lightcoinex** [comment]
> Remove the Trust Wallet logo in the list of partners, see: https://github.com/trustwallet/assets#disclaimer. Else, this will be misleading.

Trust Wallet logo has been removed from the partner's list

**Comment by catenocrypt** [comment]
The provided token has no usage in the explorer.  Please correct / explain.

https://etherscan.io/token/0xFc178d0F36ddd2B44f925EB13bF51f5cB9B42192

**Comment by lightcoinex** [comment]
> The provided token has no usage in the explorer. Please correct / explain.
> 
> https://etherscan.io/token/0xFc178d0F36ddd2B44f925EB13bF51f5cB9B42192

We change the smart contract source code, leading to the change of address, that's why there are no transactions yet

**Comment by lightcoinex** [comment]
Sorry, could you please merge my request? It's a legit project, we just change the smart contract source (that is the reason we made a request), and our clients, the holders are waiting for the address of the new contract to be updated on the Trust Wallet. As you can see, I'm the only person who is updating about this token.

**Comment by catenocrypt** [comment]
Contract change; logo was present, being only moved; add'l info added, info ok.

**Comment by lightcoinex** [comment]
Thank you very much for supporting us.

**Pull request merged**
