### PR TITLE
Adding logo and json

### PR DESCRIPTION
**Pull request by saylormoonarmy**
logo and info.json

### CODE REVIEW

**Comment by saylormoonarmy** [comment]
logo and info json

**Comment by saylormoonarmy** [comment]
logo and json

**Comment by Cryptocool1** [comment]
This is a BEp20 token, correct folder is blockchains/smartchain/assets. Please correct.

**Comment by saylormoonarmy** [comment]
json and logo

**Comment by saylormoonarmy** [comment]
json and logo

**Comment by Cryptocool1** [comment]
correction needed:
PR should include only 2 files

**Pull request closed without merging**
