### PR TITLE
Add logo to w3b project

### PR DESCRIPTION
**Pull request by w3bin**
Add logo and info

### CODE REVIEW

**Comment by cryptomanz1** [comment]
• What is the purpose of this token? How will it benefit Trust Wallet users?
 • How is the token being distributed? Are you conducting an airdrop?
 • Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?
 • Is the token listed on a centralized/decentralized exchange?
 • Is a Smart Contract audit completed? Where can we find this information?

**Comment by w3bin** [comment]
> • What is the purpose of this token? How will it benefit Trust Wallet users? • How is the token being distributed? Are you conducting an airdrop? • Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale? • Is the token listed on a centralized/decentralized exchange? • Is a Smart Contract audit completed? Where can we find this information?

• What is the purpose of this token? How will it benefit Trust Wallet users?
The main purpose of WBY is to help people dive into our Web3 ecosystem, and be able to access the world of crypto. Many investors desire to buy WBY on Trust Wallet because Trust platform is a trustworthy, safe, and great community. Trust Wallet users will have a chance to own WBY on the Trust network, and easily make profits in our ecology.

• How is the token being distributed? Are you conducting an airdrop?
Many investors find our initiative promising and would love to early invest in our project as a seed phase. Actually, we conducted a small airdrop to thank our community for their amazing support.

• Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?
We haven't sold WBY at an ICO or presale yet. However, we're working with some big Venture Capitals to plan for the presale on the occasion of a new feature launch.

• Is the token listed on a centralized/decentralized exchange?
At this time, we ignored some listing proposals to focus on building our platform to serve our rising global users.

• Is a Smart Contract audit completed? Where can we find this information?
Yes, definitely. Our Smart Contract is well audited by Solidproof. You can find out more via this link: https://github.com/solidproof/projects/tree/main/Web3%20Infinity

**Comment by Cryptocool1** [comment]
Снимок экрана 2022-07-27 в 17 36 21
You market data should be tracked

**Comment by w3bin** [comment]
> Снимок экрана 2022-07-27 в 17 36 21
> 
> Your market data should be tracked

Hi, Our project have not listed yet so CMC will show untracked data. Now we focus on building our platform to serve our rising global users. Then list on pancakeswap.

**Comment by Cryptocool1** [comment]
We require CoinMarketCap listing. 
see criteria at https://developer.trustwallet.com/assets/requirements

**Comment by Cryptocool1** [comment]
Feel free to create new PR once the requirements are met. Make sure to mention this PR so the fee can be reused.

**Pull request closed without merging**
