### PR TITLE
Add Nyx Token (ERC20)

### PR DESCRIPTION
**Pull request by PaPacarlo13**
Adding info for ERC20 token 'Nyx Token'.

PR created by <a href="https://assets.trustwallet.com">TW Assets Management</a>

### CODE REVIEW

**Comment by cryptomanz** [comment]
• What is the purpose of this token? How will it benefit Trust Wallet users?
 • How is the token being distributed? Are you conducting an airdrop?
 • Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?
 • Is the token listed on a centralized/decentralized exchange?
 • Is a Smart Contract audit completed? Where can we find this information?

**Comment by PaPacarlo13** [comment]
Hello!
1  Nyx Token will benefit Trust Wallet users by financial instruments which we provide aswell as our majority off users use Trust Wallet and we see a lot off growth we find it beneficial for both parties.

2 The token has not been distributed prior by airdrop

3 No presale has been held

4 We are listed on Uniswap

5 a Certik audit has been completed https://www.certik.com/projects/nyx-token

**Comment by PaPacarlo13** [comment]
Moreover, our project is verified on bscscan.

**Comment by PaPacarlo13** [comment]
we also created roadmap https://nyxtoken.org/roadmap/

**Pull request merged**
