### PR TITLE
Add CANDYLAD (BEP20)

### PR DESCRIPTION
**Pull request by phanbun1009**
Adding info for BEP20 token 'CANDYLAD'.
Paid on #16423

PR created by <a href="https://assets.trustwallet.com">TW Assets Management</a>

### CODE REVIEW

**Comment by phanbun1009** [comment]
Paid on #16423 
https://github.com/trustwallet/assets/pull/16423

**Comment by Cryptocool1** [comment]
• What is the purpose of this token? How will it benefit Trust Wallet users?
 • How is the token being distributed? Are you conducting an airdrop?
 • Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?
 • Is the token listed on a centralized/decentralized exchange?
 • Is a Smart Contract audit completed? Where can we find this information?

**Comment by phanbun1009** [comment]
> • What is the purpose of this token? How will it benefit Trust Wallet users? • How is the token being distributed? Are you conducting an airdrop? • Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale? • Is the token listed on a centralized/decentralized exchange? • Is a Smart Contract audit completed? Where can we find this information?

 + What is the purpose of this token? How will it benefit Trust Wallet users? 
         - Building a Blockchain 4.0 Charity Community . Candylad with the ultimate goal of creating a more open, transparent, reasonable and trusting public charity platform worldwide.
+ How is the token being distributed? Are you conducting an airdrop?
      -  Fair launch , Not airdrop
 + Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale? 
      - No ico , no presale 
 + Is the token listed on a centralized/decentralized exchange? 
     - Listed on Pancakeswap and Poocoin
  +  Is a Smart Contract audit completed? Where can we find this information?
  Yes , Audited by Certik . Check here https://www.certik.com/projects/candylad

Thanks for support

**Comment by cryptomanz** [comment]
https://github.com/trustwallet/assets/blob/e3788c50fecb2d81c1e266c9b9fe8c1fe2e27418/blockchains/smartchain/assets/0x136BFcdec5DB31b565052451AD806014ab9F2b38/info.json

**Pull request merged**
