### PR TITLE
Add dexIRA (BEP20)

### PR DESCRIPTION
**Pull request by dexfi-com**
Adding info for BEP20 token 'dexIRA'.

PR created by <a href="https://assets.trustwallet.com">TW Assets Management</a>

### CODE REVIEW

**Comment by dexIRA** [comment]
[**PAID via #12795**](https://github.com/trustwallet/assets/pull/12795)

Previous Payment **TxID**:
[D504C0C2687D8405338F514B90CDCB7D8DAFE356BB0F867AFD64BA06A368EB8B](https://explorer.binance.org/tx/D504C0C2687D8405338F514B90CDCB7D8DAFE356BB0F867AFD64BA06A368EB8B)

**Comment by dexIRA** [comment]
### Q&A answers asked by Cryptocool via Telegram:

> **What is the purpose of this token? How will it benefit Trust Wallet users?**

dexIRA ([www.dexIRA.com](https://dexira.com)) is a platform that allows users to collect and manage a diverse array of curated cryptocurrency tokens by holding dexIRA ($DEX) tokens. Each reward distribution is automatically claimed by the holder and sent to their wallet. There are zero transaction fees on buy orders to incentivize investment. All sell transaction fees are waived after one year of holding DEX tokens without sale, promoting a long term investing strategy and reliable price support.

This will benefit Trust Wallet users by enabling them to acquire a secure and well rounded portfolio of established tokens with a history of success. In addition, [our dApp](https://dexira.app) (dashboard) gives users the opportunity to view and monitor advanced portfolio metrics which offers useful insight to their investments.

> **How is the token being distributed? Are you conducting an airdrop?**

We do not conduct any airdrops. All tokens must be bought on the open market (including dev tokens).

> **Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?**

This token was sold initially sold as a fair launch ICO on July 21st 2021 at 6PM UTC

> **Is the token listed on a centralized/decentralized exchange?**

We are currently traded on PancakeSwap, FTX, and in the process of listing on several other centralized exchanges too

> **Is a Smart Contract audit completed? Where can we find this information?**

We have had two successful third party audits completed. You can find them both here: https://dexira.com/audits/

**Comment by cryptomanz** [comment]
As per our policy, brand new tokens are not included, there is a minimum requirement of 5000 holder addresses and 10000 transactions, in order to filter out scam tokens.
See the criteria at (mentioned in the first message by the bot): https://community.trustwallet.com/t/how-to-submit-a-token-logo/3863).

**Comment by Cryptocool1** [comment]
please create new PR when all criteria are met. make sure to mention this PR, so the fee can be reused.

**Pull request closed without merging**
