### PR TITLE
Add Head Football (BEP20)

### PR DESCRIPTION
**Pull request by Head-games**
Adding info for BEP20 token 'Head Football'.

PR created by <a href="https://assets.trustwallet.com">TW Assets Management</a>

### CODE REVIEW

**Comment by HeadFootball** [comment]
Please also check our previous PR fee already paid https://github.com/trustwallet/assets/pull/17660

**Comment by cryptomanz** [comment]
Is a Smart Contract audit completed? Where can we find this information?

**Comment by HeadFootball** [comment]
Sure, Certik audit is completed and you can see https://www.certik.com/projects/headfootball
-  We will launch our game within 4 weeks. Also we are building a gaming ecosystem. There will be 5 games in total as planned and will be played with one token only which is $HEAD. Trust wallet users can easily buy our token on pancakeswap and they can play our games in free times. Easy to access and fun. While they are having fun they will earn money aswell.
-  We distribute our token 5% on private sale and 5% pre-sale on Pinksale.finance, there were no airdrops
- As i mention above we held a whitelisted presale in Pinksale.finance and swapped it to the public sale in last 24 hours.
- We are only listed on decentralized exchange at the moment which is pancakeswap.

**Comment by HeadFootball** [comment]
Also i forgot to mention. Our team is KYC completed privately on Pinksale.finance you can see that also at https://www.pinksale.finance/#/launchpad/0xEb05bA295Cfa898DBA02ca71a904664fc80AA19E?chain=BSC

**Comment by HeadFootball** [comment]
www.certik.com/projects/headfootball

Sent from Mail for Windows

**Pull request merged**
