### PR TITLE
Add AAptitude (BEP20)

### PR DESCRIPTION
**Pull request by Kofro**
Adding info for BEP20 token 'AAptitude'.

PR created by <a href="https://assets.trustwallet.com">TW Assets Management</a>

### CODE REVIEW

**Comment by Kofro** [comment]
Updated details from rebrand (Jan 2022)

**Our Partners & Special Mentions:**

FOX Business - National T.V. Interview Series - New To The Street

[https://www.youtube.com/watch?v=HS8f2XiNnFc](https://signal6domain.online/click?redirect=https%3A%2F%2Fwww.youtube.com%2Fwatch%3Fv%3DHS8f2XiNnFc&dID=1650226384934&linkName=https://www.youtube.com/watch?v=HS8f2XiNnFc)
[https://www.globenewswire.com/news-release/2022/04/11/2420199/0/en/New-to-The-Street-TV-Announces-Four-Corporate-Interviews-on-its-330th-and-331st-TV-Shows-Airing-on-the-Fox-Business-Network-Tonight-Monday-April-11-2022-at-10-30-PM-PT-and-Tomorrow.html](https://signal6domain.online/click?redirect=https%3A%2F%2Fwww.globenewswire.com%2Fnews-release%2F2022%2F04%2F11%2F2420199%2F0%2Fen%2FNew-to-The-Street-TV-Announces-Four-Corporate-Interviews-on-its-330th-and-331st-TV-Shows-Airing-on-the-Fox-Business-Network-Tonight-Monday-April-11-2022-at-10-30-PM-PT-and-Tomorrow.html&dID=1650226384934&linkName=https://www.globenewswire.com/news-release/2022/04/11/2420199/0/en/New-to-The-Street-TV-Announces-Four-Corporate-Interviews-on-its-330th-and-331st-TV-Shows-Airing-on-the-Fox-Business-Network-Tonight-Monday-April-11-2022-at-10-30-PM-PT-and-Tomorrow.html)
[https://twitter.com/NewToTheStreet/status/1509558404372738066](https://signal6domain.online/click?redirect=https%3A%2F%2Ftwitter.com%2FNewToTheStreet%2Fstatus%2F1509558404372738066&dID=1650226384934&linkName=https://twitter.com/NewToTheStreet/status/1509558404372738066)

Visa/Fiat Payments (Full legal KYC/KYB DOX)

[https://aaptitude.com/transak.html](https://signal6domain.online/click?redirect=https%3A%2F%2Faaptitude.com%2Ftransak.html&dID=1650226384934&linkName=https://aaptitude.com/transak.html)
[https://transak.com/](https://signal6domain.online/click?redirect=https%3A%2F%2Ftransak.com%2F&dID=1650226384934&linkName=https://transak.com/)
Verified + Price Indexing on BscScan!

[https://bscscan.com/token/0x2a6f8e3a8fe92849b08ca82f4f323dd43029b33d#tokenInfo](https://signal6domain.online/click?redirect=https%3A%2F%2Fbscscan.com%2Ftoken%2F0x2a6f8e3a8fe92849b08ca82f4f323dd43029b33d%23tokenInfo&dID=1650226384934&linkName=https://bscscan.com/token/0x2a6f8e3a8fe92849b08ca82f4f323dd43029b33d#tokenInfo)
ChainLink

[https://i.imgur.com/GZAOeev.png](https://signal6domain.online/click?redirect=https%3A%2F%2Fi.imgur.com%2FGZAOeev.png&dID=1650226384934&linkName=https://i.imgur.com/GZAOeev.png)
CoinEx

[https://twitter.com/CoinEx_CSC/status/1512368467701231619](https://signal6domain.online/click?redirect=https%3A%2F%2Ftwitter.com%2FCoinEx_CSC%2Fstatus%2F1512368467701231619&dID=1650226384934&linkName=https://twitter.com/CoinEx_CSC/status/1512368467701231619)
Yahoo Finance Listing
[https://finance.yahoo.com/quote/AAPT-USD?p=AAPT-USD    ](https://signal6domain.online/click?redirect=https%3A%2F%2Ffinance.yahoo.com%2Fquote%2FAAPT-USD%3Fp%3DAAPT-USD&dID=1651422568071&linkName=https://finance.yahoo.com/quote/AAPT-USD?p=AAPT-USD)

Cheers,
--------------------------------------------------------------------------------------
Kodi Tanerau-Love
Chief Executive Officer / Lead Developer
E [kodi.tanerau-Love@aaptitude.com](mailto:kodi.tanerau-Love@aaptitude.com)

[https://aaptitude.com](https://signal6domain.online/click?redirect=https%3A%2F%2Faaptitude.com%2F&dID=1651422568071&linkName=https://aaptitude.com)

**Comment by Kofro** [comment]
@cryptomanz
[62555db1c27e7de01fbfde0b_Safetin Audit - AAptitude.pdf](https://github.co
[621c7faf21d7d136e2e874c7_Audit_aaptitude.pdf](https://github.com/trustwallet/assets/files/8599373/621c7faf21d7d136e2e874c7_Audit_aaptitude.pdf)
m/trustwallet/assets/files/8599371/62555db1c27e7de01fbfde0b_Safetin.Audit.-.AAptitude.pdf)
[621813730468731b849bf236_KYC_aaptitude (1).pdf](https://github.com/trustwallet/assets/files/8599372/621813730468731b849bf236_KYC_aaptitude.1.pdf)

**Comment by Cryptocool1** [comment]
As per our policy, brand new tokens are not included, there is a minimum requirement of 10,000 holder addresses and 15,000 transactions, in order to filter out scam tokens.
See the criteria at : https://developer.trustwallet.com/assets/requirements .

**Comment by Kofro** [comment]
> As per our policy, brand new tokens are not included, there is a minimum requirement of 10,000 holder addresses and 15,000 transactions, in order to filter out scam tokens. See the criteria at : https://developer.trustwallet.com/assets/requirements .

The token is over a year old.

**Comment by Kofro** [comment]
> > As per our policy, brand new tokens are not included, there is a minimum requirement of 10,000 holder addresses and 15,000 transactions, in order to filter out scam tokens. See the criteria at : https://developer.trustwallet.com/assets/requirements .
> 
> The token is over a year old. @Cryptocool1 We're listed on yahoo finance, this is just so the logo shows up on pancakeswaps extended token list...

@Cryptocool1 @cryptomanz

**Comment by Kofro** [comment]
AAptitude Announcements Channel:

We are excited to announce that today we’ll be releasing our much-anticipated Escrow marketplace! 

We are also proud to present our software integration in collaboration with CHAINLINK!

AAptitude will be working closely with ChainLink staff on service integration for the foreseeable future!

https://blog.aaptitude.com/aaptitude-has-integrated-multiple-chainlink-services-to-support-its-escrow-marketplace-fbac8bde4865

https://www.instagram.com/p/CdDkNx2qTuT/

https://www.facebook.com/AAptitudeToken/photos/a.103003495734908/109043925130865/

https://twitter.com/AAptitudeToken/status/1521109810858512384

https://twitter.com/Smart_Contract/status/1521112272336297985

https://twitter.com/Smart_Contract/status/1521112272336297985

Our first PR article is out!

https://koinreport.com/press-release/aaptitude-fueling-the-blockchains-secure-trade-revolution/

And our second article got just released too!

https://www.satoshihodler.com/2022/05/02/aaptitude-fueling-the-blockchains-secure-trade-revolution/

https://thebitcoinnews.com/aaptitude-fueling-the-blockchains-secure-trade-revolution/

https://www.chainbits.com/press-releases/aaptitude-fueling-the-blockchains-secure-trade-revolution/

https://truebitcoiner.com/aaptitude-fueling-the-blockchains-secure-trade-revolution/

**Comment by Kofro** [comment]
@Cryptocool1 @cryptomanz

**Comment by Kofro** [comment]
@Cryptocool1 @cryptomanz

**Pull request closed without merging**
