### PR TITLE
Add Cherry Network (BEP20, POLYGON, ERC20)

### PR DESCRIPTION
**Pull request by therealcherry**
Refer to the previously submitted PR https://github.com/trustwallet/assets/pull/17048

Our the audit missing in that previous request: https://assets.spherelink.co/audits/Cherry_Token_Audit_by_Spherelink.pdf

### CODE REVIEW

**Comment by cryptomanz1** [comment]
Hello,
Please follow the rules for adding token, your logo should be a full screen, 256x256.

**Comment by therealcherry** [comment]
> Hello, Please follow the rules for adding token, your logo should be a full screen, 256x256.

Solved!

**Comment by Cryptocool1** [comment]
hello, your Polygon contract should be in checksum format, please change

**Comment by Cryptocool1** [comment]
Please update your branch with the recent master

**Comment by therealcherry** [comment]
> Please update your branch with the recent master

done!

**Pull request merged**
