### PR TITLE
Add BonusCake logo and info

### PR DESCRIPTION
**Pull request by viktyy**
Bonus Cake is the first dividend and lucky draw CAKE reflection token

### CODE REVIEW

**Comment by viktyy** [comment]
https://github.com/trustwallet/assets/pull/13506

**Comment by viktyy** [comment]
[PRE-BonusCake-2021-10-01.pdf](https://github.com/trustwallet/assets/files/7269433/PRE-BonusCake-2021-10-01.pdf)
audit

**Comment by Cryptocool1** [comment]
could you add the links?

**Comment by viktyy** [comment]
link about what?

**Comment by cryptomanz** [comment]
> link about what?

- could you add the links about your token? (twitter, facebook, telegram, coingecko, coinmarketcap)

**Comment by viktyy** [comment]
twitter:https://twitter.com/BonusCakeBSC

**Comment by viktyy** [comment]
telegram:https://t.me/BonusCake
coingecko:https://www.coingecko.com/en/coins/bonus-cake
coinmarketcap:https://coinmarketcap.com/currencies/bonus-cake/

**Comment by viktyy** [comment]
`    "name": "Bonus Cake",
    "website": "https://bonuscake.com",
    "description": "Bonus Cake is the first dividend and lucky draw CAKE reflection token.",
    "explorer": "https://bscscan.com/token/0xb84ddc645c27D4Dc4bFA325c946f9d89d3AfCc7a",
    "type": "BEP20",
    "symbol": "BonusCake",
    "decimals": 18,
    "status": "active",
    "id": "0xb84ddc645c27D4Dc4bFA325c946f9d89d3AfCc7a"
    "links": [
        {
            "name": "telegram",
            "url": "https://t.me/BonusCake"
        },
        {
            "name": "twitter",
            "url": "https://twitter.com/BonusCakeBSC"
        },
        {
            "name": "coinmarketcap",
            "url": "https://coinmarketcap.com/currencies/bonus-cake/"
        },
        {
            "name": "coingecko",
            "url": "https://coinmarketcap.com/currencies/bonus-cake/"
        }
    ]
}`

**Comment by cryptomanz** [comment]
Hello,
Please follow the rules for adding tokens, your logo should be a full screen 256x256.
Exemple:
https://community.trustwallet.com/t/how-to-submit-a-token-logo/3863
Screenshot 2021-10-01 at 01 52 16

**Comment by viktyy** [comment]
I checked again, it is indeed 256x256

**Comment by cryptomanz** [comment]
Your logo should be a full screen (256x256).
Exemple:
Screenshot 2021-10-01 at 01 52 16

**Comment by viktyy** [comment]
logo

**Comment by cryptomanz** [comment]
> "name": "Bonus Cake", "website": "https://bonuscake.com", "description": "Bonus Cake is the first dividend and lucky draw CAKE reflection token.", "explorer": "https://bscscan.com/token/0xb84ddc645c27D4Dc4bFA325c946f9d89d3AfCc7a", "type": "BEP20", "symbol": "BonusCake", "decimals": 18, "status": "active", "id": "0xb84ddc645c27D4Dc4bFA325c946f9d89d3AfCc7a" "links": [ { "name": "telegram", "url": "https://t.me/BonusCake" }, { "name": "twitter", "url": "https://twitter.com/BonusCakeBSC" }, { "name": "coinmarketcap", "url": "https://coinmarketcap.com/currencies/bonus-cake/" }, { "name": "coingecko", "url": "https://coinmarketcap.com/currencies/bonus-cake/" } ] }

Could you please add links in your info.json?

**Comment by viktyy** [comment]
I have updated

**Pull request merged**
