### PR TITLE
Add Miss Doge token (MDOGE) logo and info

### PR DESCRIPTION
**Pull request by MissDoge**
We add Miss Doge token (MDOGE) to Trust Wallet
Contract: https://www.bscscan.com/token/0xA72Ff2B799324B042AE379809eE54dACE99db3A5
More information: https://missdoge.net

### CODE REVIEW

**Comment by Cryptocool1** [comment]
hello,
• What is the purpose of this token? How will it benefit Trust Wallet users?
 • How is the token being distributed? Are you conducting an airdrop?
 • Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?
 • Is the token listed on a centralized/decentralized exchange?
 • Is a Smart Contract audit completed? Where can we find this information?

**Comment by Cryptocool1** [comment]
still no answer,
please create new PR when you will be ready to chat
make sure to mention this PR

**Comment by MissDoge** [comment]
hi @Cryptocool1 ? do I need to pay again in another PR?

**Comment by Cryptocool1** [comment]
No, just mention this PR

**Pull request closed without merging**
