### PR TITLE
Add KET (BEP20)

### PR DESCRIPTION
**Pull request by kryptoknightk**
This PR is being closed due to inactivity. If you wish to continue, please have us reopen the PR before sending your payment.
Do NOT send payments for closed PR, as the fee may by lost!
  (99 vs. 99 hrs)

### CODE REVIEW

**Comment by catenocrypt** [comment]
Info.json contains wrong JSON, maybe due to special characters, or wrong quote or comma characters.  Please fix.

image

**Comment by kryptoknightk** [comment]
Okay will resubmit

**Comment by catenocrypt** [comment]
Still wrong

image

**Comment by kryptoknightk** [comment]
IDK why it's giving that error, the characters are how it should be. Can
you fix it for us?

**Pull request closed without merging**
