### PR TITLE
YFII SILVER

### PR DESCRIPTION
**Pull request by vitalismark**

### CODE REVIEW

**Comment by vitalismark** [comment]
PAYMENT MADE

**Comment by vitalismark** [comment]
logo

im trying to merge this logo to this address 0x32F3b9B5Bd6C76F41ee3B389573f340468666861 and its been over four days and no one has responded to me. whats the delay

**Comment by vitalismark** [comment]
@catenocrypt why hasn't anything been done about my upload. How long before yiu take a look at this PR it's been over 5days

**Comment by zachzwei** [comment]
This PR has a lot of errrors, please make sure when creating a new request that your fork is in sync with the master.
Closing this one and creating an new one.
https://github.com/trustwallet/assets/pull/4534

**Comment by catenocrypt** [comment]
Groovy token has low circulation (89), will not be merged unless circulation reaches limit (500 holders, 1000 txs)

https://etherscan.io/token/0x31bE30217989766215672E88eD449913e05bf0F5

**Pull request closed without merging**
