### PR TITLE
New Logo KGO - KIWIGO

### PR DESCRIPTION
**Pull request by KIWIPAY-KGO**
New JSON and new LOGO for token KGO

### CODE REVIEW

**Comment by KIWIPAY-KGO** [comment]
Hi, its write some checks haven's completed, let me know what you need more, and i can also complete the payment.
Thank you

**Comment by KIWIPAY-KGO** [comment]
Somebody can help us ? Thank you

**Comment by catenocrypt** [comment]
Correction needed: the folder corresponding should be in 'checksum' format. Please rename, or create a new PR with correct folder name.

XXX   'Expect asset at path /home/runner/work/assets/assets/blockchains/smartchain/assets/0x5d3afba1924ad748776e4ca62213bf7acf39d773 in checksum: '0x5d3AfBA1924aD748776E4Ca62213BF7acf39d773''

**Comment by KIWIPAY-KGO** [comment]
hi, we don't understand, the folder name is already : 0x5d3AfBA1924aD748776E4Ca62213BF7acf39d773
What we need to change ?

**Comment by KIWIPAY-KGO** [comment]
> Correction needed: the folder corresponding should be in 'checksum' format. Please rename, or create a new PR with correct folder name.
> 
> XXX 'Expect asset at path /home/runner/work/assets/assets/blockchains/smartchain/assets/0x5d3afba1924ad748776e4ca62213bf7acf39d773 in checksum: '0x5d3AfBA1924aD748776E4Ca62213BF7acf39d773''

hi, we don't understand, the folder name is already : 0x5d3AfBA1924aD748776E4Ca62213BF7acf39d773
What we need to change ?

**Comment by catenocrypt** [comment]
No, the folder name is all-lowercase, check the Files section of the PR

image

**Review by KIWIPAY-KGO — COMMENTED** [review]
Update

**Review by KIWIPAY-KGO — COMMENTED** [review]
Change folder name

**Review by KIWIPAY-KGO — COMMENTED** [review]
Change folder name

**Comment by KIWIPAY-KGO** [comment]
Cancel submit new

**Pull request closed without merging**
