### PR TITLE
Adding Revolotto (RVL) Logo

### PR DESCRIPTION
**Pull request by Revolotto**
Added Revolotto Logo and Info

### CODE REVIEW

**Review by Revolotto — COMMENTED** [review]
Fixed Reddit Link

**Comment by cryptomanz** [comment]
• What is the purpose of this token? How will it benefit Trust Wallet users?
 • How is the token being distributed? Are you conducting an airdrop?
 • Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?
 • Is the token listed on a centralized/decentralized exchange?
 • Is a Smart Contract audit completed? Where can we find this information?

**Comment by Revolotto** [comment]
- **What is the purpose of this token? How will it benefit Trust Wallet users?**

Revolotto is a deflationary token, Collectively it is a four-dimensional token. On every trade 80% to the investor, 6% divided between all holders, 5% will be burnet, and 9% will automatically be added into Liquidity Pool. Listed on CMC & CoinGecko

Revolotto (RVL) is a cryptocurrency that grants investors holding (RVL) instant rewards on all transactions, and protects them with its unique coin circulation cycles and burn protocol.

Climate change and Global warming are burning issues and Revolotto's team is working on it specifically and wants to take special steps to make this planet healthier because if this planet stays healthy, everyone on this planet, including humans and all other creatures will be healthy.

We have over 5500 holders and Trust wallet users would benefit greatly from the logo of the Revolotto to avoid scams and honeypots using our name.


- **How is the token being distributed? Are you conducting an airdrop?**

(No Airdrops)
### Token Distribution
> 25% Presale Allocation
> 17% Private Sale Allocation
> 41% Liquidity Allocation
> 03% Marketing Allocation
> 04% Dev Allocation
> 05% Anti-Climate Change Allocation
>  05% Flood & Natural Disaster Relief Allocation


- **Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?**

Yes, we had a presale.


- **Is the token listed on a centralized/decentralized exchange?**

**PancakeSwap - Decentralized**
We have listed on PancakeSwap at 10th October


- **Is a Smart Contract audit completed? Where can we find this information?**

Yes, our Smart Contract has been audited by Digital Ocean. Here is the document file:
https://digitalocean.finance/audits/Revolotto-Audit-By-Digital-Ocean.pdf

**Comment by Revolotto** [comment]
Hello there,

We have also upgraded the website domain name and we would like to update it as well.

old website: https://revolotto.org/
new website: https://revolotto.net/

**Pull request merged**
