### PR TITLE
update Intuz logo in trust wallet

### PR DESCRIPTION
**Pull request by intuzpro**
dear sir we need to update Intuz coin logo in trust wallet
https://etherscan.io/token/0x72a8eaead0b6f735361a0a6b9402b13dd7081048
0x72a8eaead0b6f735361a0a6b9402b13dd7081048

### CODE REVIEW

**Comment by intuzpro** [comment]
dear sir,
we need to update the logo of intuz please , if any error please help us and correct it 
thanks

**Comment by intuzpro** [comment]
0x72a8eaead0b6f735361a0a6b9402b13dd7081048

**Comment by kolya182** [comment]
> dear sir,
> we need to update the logo of intuz please , if any error please help us and correct it
> thanks

You nee to pay fee first.

**Comment by intuzpro** [comment]
fees paid just now

**Comment by intuzpro** [comment]
WhatsApp Image 2020-06-13 at 12 50 06 AM
proof of payment

**Comment by kolya182** [comment]
Added, you can see logo now inside the app

**Comment by intuzpro** [comment]
@kolya182  it show white borders , please we need the borders to be black only 
thanks

**Comment by intuzpro** [comment]
@kolya182  
WhatsApp Image 2020-06-13 at 12 50 06 AM

**Pull request closed without merging**
