### PR TITLE
Add BerylBit (BEP20)

### PR DESCRIPTION
**Pull request by BerylBit**
Adding info for BEP20 token 'BerylBit'.

PR created by <a href="https://assets.trustwallet.com">TW Assets Management</a>

### CODE REVIEW

**Comment by BerylBit** [comment]
( We know your standard is 10k min holders, but you listed catboy on trustwallet at 4-5k holders and we have 4700 holders here is the contract of catboy so you can check for proof - https://bscscan.com/token/0x39c3f75b837eae0d6d0ea87425ac99bd646a7b1e  )

**Comment by cryptomanz** [comment]
We are not discuss any other projects.
As per our policy, brand new tokens are not included, there is a minimum requirement of 10,000 holder addresses and 15,000 transactions, in order to filter out scam tokens.
See the criteria at : https://developer.trustwallet.com/assets/requirements .
 come back to us when all criteria are met

**Comment by BerylBit** [comment]
Well that isn’t fair, you list other tokens way under 10k holders and we come to you and you tell us this? This is so unprofessional..

**Comment by mutantApeYachtClub** [comment]
> ### PR Summary
> Files OK: 3
> Token in PR: **BEP20** 0xcA0823d3D04b9FAeA7803cCb87fa8596775190DD
> Symbol: **brb** decimals: 18
> Links: [Logo](https://raw.githubusercontent.com/BerylBit/assets/br0317-231528/blockchains/smartchain/assets/0xcA0823d3D04b9FAeA7803cCb87fa8596775190DD/logo.png) [Info](https://raw.githubusercontent.com/BerylBit/assets/br0317-231528/blockchains/smartchain/assets/0xcA0823d3D04b9FAeA7803cCb87fa8596775190DD/info.json) [Website](https://www.beryl-bit.com/) [Explorer](https://bscscan.com/token/0xcA0823d3D04b9FAeA7803cCb87fa8596775190DD)
> Tags: defi
> Token check error: 
> ❌ invalid value 'https://www.coingecko.com/en/coins/berylbit' for coingecko link url, allowed only with prefix: https://coingecko.com/
> ❌ number of holders not checked: please, check it manually
> 
> 
> 
> <span style="padding: 5px; background-color: rgb(32,32,32);"></span>
> 
> 
> 
>

**Pull request closed without merging**
