### PR TITLE
Add DogeBack (BEP20)

### PR DESCRIPTION
**Pull request by Goronyudo**
Adding info for BEP20 token 'DogeBack'.

PR created by <a href="https://assets.trustwallet.com">TW Assets Management</a>

### CODE REVIEW

**Comment by cryptomanz** [comment]
Hello,
Can you answer some questions?
• What is the purpose of this token? How will it benefit Trust Wallet users?
• How is the token being distributed? Are you conducting an airdrop?
• Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?
• Is the token listed on a centralized/decentralized exchange?
• Is a Smart Contract audit completed? Where can we find this information?

**Comment by Cryptocool1** [comment]
Hello, 
Is a Smart Contract audit completed?

**Comment by Cryptocool1** [comment]
•	Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?
	•	Is the token listed on a centralized/decentralized exchange?

**Comment by Goronyudo** [comment]
-Audit is in process
-51% ICO
-PancakeSwapV2

**Comment by Cryptocool1** [comment]
What is the purpose of this token and how tw users will be benefited?

**Comment by InuXiasi** [comment]
Doge Back proposes an innovative feature in its contract, dividend payments in Dogecoin all holders get distributed 10% distribution according to holder size.

**Comment by Goronyudo** [comment]
Dogeback proposes an innovative feature in its contract by paying dividend payments ( auto distribution off 10% to all holders according to wallet size.

**Comment by Cryptocool1** [comment]
Great

**Pull request merged**
