### PR TITLE
Add Dione (DIONE) (ERC20)

### PR DESCRIPTION
**Pull request by DioneProtocol1**
Adding info for ERC20 token 'Dione (DIONE)'.

PR created by <a href="https://assets.trustwallet.com">TW Assets Management</a>

### CODE REVIEW

**Comment by Cryptocool1** [comment]
As per our policy, there is a minimum requirement of 10,000 holder addresses and 15,000 transactions, in order to filter out scam tokens.
See the criteria at : https://developer.trustwallet.com/listing-new-assets/requirements .

**Comment by Cryptocool1** [comment]
Feel free to create new PR once all criteria are met. Make sure to mention this PR so the fee can be reused.

**Comment by DioneProtocol1** [comment]
Please check my comment and if possible, do a full review of our brand. We have 3x the organic following as other listed tokens, 10x the holder count as others, and 2 exchanges with over 15% of the supply being held. Your website says that this requirement is subject to review, so please take a longer review on my statements if possible. We are not a scam token. Thank you for your time.

**Comment by Cryptocool1** [comment]
Please answer those questions:
• What is the purpose of this token? How will it benefit Trust Wallet users?
 • How is the token being distributed? Are you conducting an airdrop?
 • Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?
 • Is the token listed on a centralized/decentralized exchange?
 • Is a Smart Contract audit completed? Where can we find this information?

**Comment by DioneProtocol1** [comment]
"This requirement is subject for review based on the project."

Did you review the project? @Cryptocool1

**Comment by DioneProtocol1** [comment]
Sure i will answer

**Comment by DioneProtocol1** [comment]
1. Purpose of the DIONE token: The DIONE token is a staking utility, currently on ERC20, and in the next three months, it will become the native coin for the world's first green energy blockchain. This makes it an attractive asset for Trust Wallet users who are interested in the intersection of crypto and sustainable energy.

2. Token Distribution: The DIONE token has been live since August of 2022, and it's currently available on Uniswap, Gate.io, and MEXC. There was no airdrop or OTC deals; we believe in fairness and equality, which is why we conducted a straight fair launch.

3. Initial Coin Offering (ICO): We did not conduct an ICO or token presale. Instead, we opted for a straight fair launch in August of 2022, ensuring fairness and equal opportunities for all participants.

4. Token Listing: DIONE is listed on Uniswap, Gate.io, and MEXC. These listings make the DIONE token accessible to a global audience, including Trust Wallet users.

5. Smart Contract Audit: Yes, our smart contract has been audited by Solidproof, a leading third-party security firm. The audit report can be found at this link: https://app.solidproof.io/projects/dione-protocol. The audit confirms that our smart contracts are secure and function as intended, providing Trust Wallet users with a reliable and trustful token to transact.

**Comment by DioneProtocol1** [comment]
Hi, I appreciate your due diligence and safety for the Trust Wallet users. However, our contract is renounced, we cannot call these functions.

"Ownership is renounced
Contract cannot be manipulated by owner functions." - SolidProof audit

**Comment by DioneProtocol1** [comment]
I also urge you if possible to check out our Twitter. Our community is immensely strong with hundreds of thousands of impressions per Tweet. It would be a great marketing collab in which we would love to tweet. https://twitter.com/dioneprotocol

**Comment by Cryptocool1** [comment]
Thank you for your interest in adding your asset to Trust Wallet, we will reconsider your request later once you will be closer to 10k holders.

**Comment by DioneProtocol1** [comment]
Ok, thanks. If possible just one question. I noticed these guys got on but they only have 330 holders? Is there some other form of review we can proceed with? https://twitter.com/Checkdot_proto/status/1571191639145594881?s=20

**Comment by DioneProtocol1** [comment]
Hello Cryptocool1. We are pushing 5K holders with over 20% of the supply being held by Gate Io and MEXC. We have a Fox5 Live interview in America and would like to include Trust wallet in our national television pitch for news we have been added to the wallet. Please consider. Thank you.

**Comment by DioneProtocol1** [comment]
Alright guys we have 5045 holders and rapidly growing daily, with 14% being held on MEXC in which we can assume are another minimum of 5000 holders. Lets get this thing pushed already! @Cryptocool1

**Comment by DioneProtocol1** [comment]
@cryptomanz1

**Pull request closed without merging**
