### PR TITLE
Adding VTX

### PR DESCRIPTION
**Pull request by Kartikj20**
Adding logo to token

### CODE REVIEW

**Comment by Kartikj20** [comment]
Whats the update ?

**Comment by Kartikj20** [comment]
Token contract address - 0xe1fda69d2483fB64d630D36F8DF0c9353f921dC0
Token name - Vertex Global 
Token - VTX

**Comment by 9764319764319764** [comment]
hamed

**Comment by Kartikj20** [comment]
Please get it done asap

**Comment by Cryptocool1** [comment]
Please create new PR, follow doc https://developer.trustwallet.com/listing-new-assets/requirements
You may want to try our Assets app in beta; go to https://assets.trustwallet.com, log on with Github, enter contract ID, logo and some additional info, and it will create a PR for you.
See https://developer.trustwallet.com/listing-new-assets/repository_details

**Pull request closed without merging**
