### PR TITLE
Added CryptoMines Reborn - CRUX

### PR DESCRIPTION
**Pull request by manuutr**
Added CryptoMines Reborn - CRUX

### CODE REVIEW

**Comment by cryptomanz** [comment]
• What is the purpose of this token? How will it benefit Trust Wallet users?
 • How is the token being distributed? Are you conducting an airdrop?
 • Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?
 • Is the token listed on a centralized/decentralized exchange?
 • Is a Smart Contract audit completed? Where can we find this information?

**Comment by cryptomanz** [comment]
your logo should be a full screen, 256x256.

**Comment by cryptomanz** [comment]
can you please add tags and links?
exemple:
```
"links": [
         {
             "name": "github",
             "url": "https://github.com"
         },
         {
             "name": "twitter",
             "url": "https://twitter.com"
         },
         {
             "name": "reddit",
             "url": "https://reddit.com"
         }
     ]
     ```

**Comment by manuutr** [comment]
Where I can find a list of valids tags? There is something related to play-to-earn/metaverse/gaming ?

**Comment by cryptomanz** [comment]
Can you send here smart contract audit in PDF format?

**Review by DNAOFFICIALL — APPROVED** [review]

**Comment by manuutr** [comment]
[CryptoMines_-_CRUX_Smart_Contract_Security_Report.pdf](https://github.com/trustwallet/assets/files/8594303/CryptoMines_-_CRUX_Smart_Contract_Security_Report.pdf)

**Pull request merged**
