### PR TITLE
Added Vidya token information and logo

### PR DESCRIPTION
**Pull request by itsghost3d**
Token information and logo for Vidya token.

### CODE REVIEW

**Comment by catenocrypt** [comment]
I have not found Vidya token mentioned on https://team3d.io/, nor the logo.
Could you please elaborate?

**Comment by itsghost3d** [comment]
> I have not found Vidya token mentioned on https://team3d.io/, nor the logo.
> Could you please elaborate?

We will update the website with VIDYA token name, we kept it hidden to avoid copycats being created on Uniswap prior to launch. If you check the Telegram or Discord found through the website it will lead you to the VIDYA token community.

**Comment by itsghost3d** [comment]
> I have not found Vidya token mentioned on https://team3d.io/, nor the logo.
> Could you please elaborate?

We have updated our site to include the Vidya token logo

**Comment by itsghost3d** [comment]
Please check again, we have updated it

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐

**Pull request merged**
