### PR TITLE
Add WEB3MET (BEP20)

### PR DESCRIPTION
**Pull request by sdsfx007**
Adding info for BEP20 token 'WEB3MET'.

PR created by <a href="https://assets.trustwallet.com">TW Assets Management</a>

### CODE REVIEW

**Comment by Cryptocool1** [comment]
• What is the purpose of this token? How will it benefit Trust Wallet users?
 • How is the token being distributed? Are you conducting an airdrop?
 • Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?
 • Is the token listed on a centralized/decentralized exchange?
 • Is a Smart Contract audit completed? Where can we find this information?

**Comment by mwsoofy** [comment]
1) What is the purpose of this token? How will it benefit Trust Wallet users?

Web3Met token is part of the  Phase 1 of WEB3MET Ecosystem, We have are making an ecosystem for all Metaverse and NFT related projects, where they can promote their ideas and get support from community. 

The whole project is managed by Web3met LTD,  Company No. 14770342 registered in UK. The founding director of our company is Mr. Ratheesh Ravindran. 

Due to our popularity in United Arab Emirates & Near by areas where we conduct events to promote the project, There are many copies of our token in the blockchain. Most of our Holders utilize TrustWallet. So to make sure our holders use the orginal WEB3MET we would like to validate our project with TRUST WALLET.

2. How is the token being distributed? Are you conducting an airdrop?

We are listed on DEX Exchanges such as Pancake Swap etc, and on our website we have added a tokensale contract where customers can directly purchase tokens from our private sale through smart contract at the similar price in market.

We had conducted Events in Crypto EXPO in Dubai, where customers can visit our website and get W3M tokens.

3. Did you sold the tokens at an Initial Coin Offering (ICO)

Yes !, We sold 20% of our total supply on ICO, which was mainly powered by Crypto Events taken in places such as UAE.

4.  Is the token listed on a centralized/decentralized exchange?
These are few exchanges we are listed on. We have mainly added liquidity on these platforms, apart from this many other DEX's are also there
https://tokpie.io/ , https://pancakeswap.finance/, https://apeswap.finance/

5.Is a Smart Contract audit completed? Where can we find this information?

No, Our token has simple ERC20 token code, and the source code is also verified on BSC Scan, apart from a showoff we have not found certification by the certificate providers useful on our case as our smartcontract is not highly complex.

If you require the same we can initiate for certificate from any reputed certifiers you prefer.


Thank you for time on our project, we have lot more to get done, before we are perfect, but we are an enthusiastic team and community.

**Comment by Cryptocool1** [comment]
We require smart contract audit from reputable companies (Techrate, Certik, Hacken, Dessert Finance) 
Please create new PR once audit is completed.

**Comment by mwsoofy** [comment]
Thank you for your review, @Cryptocool1 

Will get back to you with the certificate soon.

**Pull request closed without merging**
