### PR TITLE
Add Arvo Token And Info

### PR DESCRIPTION
**Pull request by arvofi**

### CODE REVIEW

**Comment by arvofi** [comment]
i changed my logo to 256x256 and added explorer link but not i know problem to now

**Comment by catenocrypt** [comment]
Submitted files are in wrong folder, should be
`blockchains/ethereum/assets/0x629383e682fb83cac57e07bd2a5329ac6e4b48b1/info.json`
instead of
`blockchains/0x629383e682fb83cac57e07bd2a5329ac6e4b48b1/info.json`
.  Please correct.

**Comment by arvofi** [comment]
> Submitted files are in wrong folder, should be
> `blockchains/ethereum/assets/0x629383e682fb83cac57e07bd2a5329ac6e4b48b1/info.json]`
> instead of
> `blockchains/0x629383e682fb83cac57e07bd2a5329ac6e4b48b1/info.json`
> . Please correct.

it already in `blockchains/0x629383e682fb83cac57e07bd2a5329ac6e4b48b1/info.json`

please check it and tell me what i do
Screen Shot 2020-12-07 at 8 22 34 PM

**Comment by catenocrypt** [comment]
Folder should be
`blockchains/ethereum/assets/0x629383E682fb83CAC57e07Bd2A5329ac6E4b48b1`
instead of
`blockchains/0x629383e682fb83cac57e07bd2a5329ac6e4b48b1` .

image

**Comment by arvofi** [comment]
> Folder should be
> `blockchains/ethereum/assets/0x629383E682fb83CAC57e07Bd2A5329ac6E4b48b1`
> instead of
> `blockchains/0x629383e682fb83cac57e07bd2a5329ac6e4b48b1` .
> 
> image

Done please check it
thank you.

Screen Shot 2020-12-07 at 8 54 45 PM

**Comment by catenocrypt** [comment]
As per our policy, brand new tokens are not included, there is a minimum requirement of 2500 holder addresses and 5000 transactions, in order to filter out scam tokens.
See the criteria at (mentioned in the first message by the bot): https://community.trustwallet.com/t/how-to-submit-a-token-logo/3863).
This token has no real usage yet (401 holders). Putting PR on hold for now. Please come back to us when all criteria are met.

https://etherscan.io/token/0x629383e682fb83cac57e07bd2a5329ac6e4b48b1

**Comment by arvofi** [comment]
why wasn't it clarified before we sent the 6BNB ? also we've launched
another project 2 months ago and the logo reflected few hours after we've
sent the 6BNB

Kindly advise

**Comment by catenocrypt** [comment]
It was mentioned in the 2nd message, and also in the linked documentation.

https://github.com/trustwallet/assets/pull/5003#issuecomment-739325918

https://community.trustwallet.com/t/how-to-submit-a-token-logo/3863

**Comment by catenocrypto** [comment]
Sorry for inconvenience but we have decided to add your token now and we will refund that old 6 bnb to the same address from where you send .
To get 6 bnb refund and process your request further please send 6 bnb more to address
bnb1f29knh46qztqvy6ha6r3gpm5jxx8aujdd4gq2j
with memo field empty .

**Comment by Iamdeadlyz** [comment]
⚠ **Please ignore the message of the impersonator:** https://github.com/trustwallet/assets/pull/5003#issuecomment-748894902

Legitimate user is: https://github.com/catenocrypt

**Pull request closed without merging**
