### PR TITLE
Zillamatrix trustwallet logo assets

### PR DESCRIPTION
**Pull request by monkey-shanti**
added ZillaMatrix assets

### CODE REVIEW

**Comment by ramsty** [comment]
Hi!
Could you answer some questions?
• What is the purpose of this token? How will it benefit Trust Wallet users?
• How is the token being distributed? Are you conducting an airdrop?
• Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?
• Is the token listed on a centralized/decentralized exchange?
• Is a Smart Contract audit completed? Where can we find this information?

**Comment by monkey-shanti** [comment]
**• What is the purpose of this token? How will it benefit Trust Wallet users?**
Purpose of this token is to grow into successful token and establish as the premier NFT token on the Flokinomics NFT Platform.  Having our logo and price on trust wallet allow users to see price in their wallet for ZillaMatrix instead of having to visit poocoin and other website everytime. Also, it would be easy to transfer tokens and manage total asset value. With over 7000 users in just 36hrs of launch, this token will surely see many more users in near future who would be happy to see logo on trustwallet

**How is the token being distributed? Are you conducting an airdrop?**
token had a presale on pinksale platform where majority of supply was given, we did have a private sale with 36 investors for raising funds for initial marketing activities

**• Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?**
At token presale, hosted on pinksale

**• Is the token listed on a centralized/decentralized exchange?**
Currently its listed on only pancakeswap {amm/dex}, and will be available on CEX {LBANK} within 2 weeks

• Is a Smart Contract audit completed? Where can we find this information?
yes, certik audit, 82% score
https://www.certik.org/projects/zillamatrix

**Comment by monkey-shanti** [comment]
any update on this?

**Comment by ramsty** [comment]
Audit is in progress. On hold for now.

**Comment by Cryptocool1** [comment]
Feel free to open new PR when smart contract audit will be ready
When creating a new PR make sure to mention this PR, so that we can see that fee has been paid already here.

**Pull request closed without merging**
