### PR TITLE
New and updated Branded Dollars from ICHI

### PR DESCRIPTION
**Pull request by DTal621**
Adding new logos and info on ICHI's Branded Dollars

### CODE REVIEW

**Comment by DTal621** [comment]
@Cryptocool1 thanks for all your help until now. Just getting some TWT and will pay the fee later today. Just want to make sure all is set so that when I pay we can get this merged :)

**Comment by DTal621** [comment]
Hey team @Cryptocool1 @cryptomanz @Iamdeadlyz the funds are ready just waiting for confirmation that this will be able to be merged and I will send over the TWT right away. Any way I can get that so that I don't have this cancelled and lose 1k TWT?

**Comment by cryptomanz** [comment]
Please follow the rules for adding token, your logo should be a full screen, 256x256.

**Comment by DTal621** [comment]
> Please follow the rules for adding token, your logo should be a full screen, 256x256.

Sounds good - which token logos need to be updated? I can update/send the new images

**Comment by DTal621** [comment]
@cryptomanz thanks for the update - I have the pngs ready all at 256x256 - let me know how best to update and I will do so asap. Appreciate the help

**Pull request merged**
