### PR TITLE
Add wrapped DASH (wDASH)

### PR DESCRIPTION
**Pull request by gades**
**Wrapped DASH for WEB3.**
The token issued by the PirateCash team and is managed by PirateFoundation.

**security audit:**
https://github.com/TechRate/Smart-Contract-Audits/blob/main/February_2024/Wrapped%20Dash.pdf

We have created a DASH token on the Binance Smart Chain blockchain, enabling its utilization in various WEB3 applications. Tokens exceeding 1 wDASH will receive rewards from DASH masternodes. We offer a 1:1 exchange ratio between our native blockchain and BEP-20 tokens.

more details:
https://pirate.place/en/investing/dash

our website:
https://wdash.org/

Also, we did liquidity on PancakeSwap for exchange wDASH to other tokens

Another our WEB3 services for wDASH:
https://dashplace.art/

Our request for DASH:
https://www.dashcentral.org/p/wrapped-dash

TrustWallet users can hold wDASH tokens and get rewards from shared masternode: XhqH4C9Fe5yYCcbVaS9uEMHEv733BeVdKF

Also, all tokens are backed by real DASH coins and users can audit:
[Xcxhh7nyxLS2s9Ck4NST4zGAdwfacSKL56](https://explorer.dash.org/insight/address/Xcxhh7nyxLS2s9Ck4NST4zGAdwfacSKL56)
[XhqH4C9Fe5yYCcbVaS9uEMHEv733BeVdKF](https://explorer.dash.org/insight/address/XhqH4C9Fe5yYCcbVaS9uEMHEv733BeVdKF)

That why we didn't do airdrop and presale or something else.

### CODE REVIEW

**Comment by cryptomanz1** [comment]
• What is the purpose of this token? How will it benefit Trust Wallet users?
 • How is the token being distributed? Are you conducting an airdrop?
 • Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?
 • Is the token listed on a centralized/decentralized exchange?
 • Is a Smart Contract audit completed? Where can we find this information?

**Comment by gades** [comment]
> • What is the purpose of this token? How will it benefit Trust Wallet users? • How is the token being distributed? Are you conducting an airdrop? • Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale? • Is the token listed on a centralized/decentralized exchange? • Is a Smart Contract audit completed? Where can we find this information?

1) It's wrapped token for real coin DASH  ( https://www.coingecko.com/en/coins/dash ) but the Dash team didn't any token for finance smart chain and PirateCash Foundation asked Dash team to do own token and which will be back compatibly 1:1 to native coin.

Aslo, we run shared service Dash masternode and users can get rewards from it https://masternodes.online/currencies/DASH/  ROI is 7.3%

more details are on our service https://pirate.place/en/investing/dash

2) we didn't do airdrop and presale or something else because all tokens has liquidity in real dash coins and users can check it [Xcxhh7nyxLS2s9Ck4NST4zGAdwfacSKL56 (https://explorer.dash.org/insight/address/Xcxhh7nyxLS2s9Ck4NST4zGAdwfacSKL56) and [XhqH4C9Fe5yYCcbVaS9uEMHEv733BeVdKF](https://explorer.dash.org/insight/address/XhqH4C9Fe5yYCcbVaS9uEMHEv733BeVdKF)

3) We have not sold any tokens, but the common supply is on the gateway for conversion and cannot distribute any more as they must be backed by real DASH coins.  Liquidity that has been created - our DASH coins and we launched a masternode

4) Our token is in PancakeSwap but DASH are on many exchanges 

5) Security audit was done by TechRate - https://github.com/TechRate/Smart-Contract-Audits/blob/main/February_2024/Wrapped%20Dash.pdf

wDASH was presented on Dubai Blockchain Forum 2024 https://twitter.com/PirateCash_NET/status/1779711736410517987 also Dash Core Group was on forum and we spoke about integrations. 

we did DAO request for support us DASH community - https://www.dashcentral.org/p/wrapped-dash

**Comment by Cryptocool1** [comment]
Please send your CoinMarketCap link

**Comment by gades** [comment]
@Cryptocool1 wDASH is not listed on CMC / GECKO yet but this token is backed by real DASH and users can participate in a common masternode  https://coinmarketcap.com/currencies/dash/ (it's DASH link)

**Comment by Cryptocool1** [comment]
Hello, we require CoinMarketCap listing. Please come back to us once You are listed.

**Pull request closed without merging**
