### PR TITLE
Please Add on Trust Wallet ASAP

### PR DESCRIPTION
**Pull request by SaAtHi1**

### CODE REVIEW

**Comment by SaAtHi1** [comment]
logo

**Comment by SaAtHi1** [comment]
@catenocrypt 
@zachzwei 
@rfunduk 
@corymsmith 

Please add as soon as possible sir...
Highly Appreciate

**Comment by catenocrypt** [comment]
-  X 'Check that logos are not too large': 'Found at least one logo that is too large: /home/runner/work/assets/assets/blockchains/ethereum/assets/0xca9d97c6C7D5a0cE89371880037cc23866e2264d/logo.png'

**Comment by SaAtHi1** [comment]
@catenocrypt 
I'm sending you logo again

**Comment by SaAtHi1** [comment]
logo

**Comment by SaAtHi1** [comment]
@catenocrypt 

Please use new logo sir

**Pull request merged**
