### PR TITLE
add logo PWQ

### PR DESCRIPTION
**Pull request by pwqfinance**
add logo PWQ

### CODE REVIEW

**Comment by catenocrypt** [comment]
Please add info.json for the second token as well.
Add `info.json` file next to the `logo.png`, with info about the project, of the form:

```json
{
    "name": "Trust Wallet Token",
    "website": "https://trustwallet.com",
    "short_description": "Utility token to increase adoption of cryptocurrency.",
    "explorer": "https://explorer.binance.org/asset/TWT-8C2"
}
```

**Comment by zachzwei** [comment]
Website shows 
403
Forbidden
Access to this resource on the server is denied!

**Comment by pwqfinance** [comment]
> Website shows
> 403
> Forbidden
> Access to this resource on the server is denied!

Sorry, we have just updated some details on the website. Now everything is back to normal, please help us update the logo for PWQ. Thank you so much

**Comment by catenocrypt** [comment]
Repeat: Please add info.json for the **second** token as well, or I remove it if you wish.
Add `info.json` file next to the `logo.png`, with info about the project, of the form:

```json
{
    "name": "Trust Wallet Token",
    "website": "https://trustwallet.com",
    "short_description": "Utility token to increase adoption of cryptocurrency.",
    "explorer": "https://explorer.binance.org/asset/TWT-8C2"
}

**Comment by pwqfinance** [comment]
> Repeat: Please add info.json for the **second** token as well, or I remove it if you wish.
> Add `info.json` file next to the `logo.png`, with info about the project, of the form:
> 
> ```json
> {
>     "name": "Trust Wallet Token",
>     "website": "https://trustwallet.com",
>     "short_description": "Utility token to increase adoption of cryptocurrency.",
>     "explorer": "https://explorer.binance.org/asset/TWT-8C2"
> }
> ```

It is already above, please check again

**Comment by pwqfinance** [comment]
> Repeat: Please add info.json for the **second** token as well, or I remove it if you wish.
> Add `info.json` file next to the `logo.png`, with info about the project, of the form:
> 
> ```json
> {
>     "name": "Trust Wallet Token",
>     "website": "https://trustwallet.com",
>     "short_description": "Utility token to increase adoption of cryptocurrency.",
>     "explorer": "https://explorer.binance.org/asset/TWT-8C2"
> }
> ```

https://github.com/trustwallet/assets/blob/4601c40b3ca024ccf383b213332a61f2277a9cd1/blockchains/ethereum/assets/0xa9241C6Bc2f536ddbedca8d95b83Af05988f6AFe/info.json

**Comment by catenocrypt** [comment]
There are 2 pngs, and only 1 json:
Info.json is missing for `0xd0Df3b1Cf729A29B7404c40D61C750008E631bA7`
Shall I remove this logo?

image

**Comment by pwqfinance** [comment]
> There are 2 pngs, and only 1 json:
> Info.json is missing for `0xd0Df3b1Cf729A29B7404c40D61C750008E631bA7`
> Shall I remove this logo?
> 
> image

yes, please delete it for me. We just used 
0xa9241C6Bc2f536ddbedca8d95b83Af05988f6AFe

**Comment by catenocrypt** [comment]
Sorry, I tried to delete, but can't modify files in your fork.  Could you remove this file?
blockchains/ethereum/assets/0xd0Df3b1Cf729A29B7404c40D61C750008E631bA7/logo.png

```
remote: Permission to pwqfinance/assets.git denied to catenocrypt.
fatal: unable to access 'https://github.com/pwqfinance/assets.git/': The requested URL returned error: 403
```

**Comment by pwqfinance** [comment]
> Sorry, I tried to delete, but can't modify files in your fork. Could you remove this file?
> blockchains/ethereum/assets/0xd0Df3b1Cf729A29B7404c40D61C750008E631bA7/logo.png
> 
> ```
> remote: Permission to pwqfinance/assets.git denied to catenocrypt.
> fatal: unable to access 'https://github.com/pwqfinance/assets.git/': The requested URL returned error: 403
> ```

https://github.com/trustwallet/assets/pull/3730#issuecomment-685794210

**Comment by pwqfinance** [comment]
> Sorry, I tried to delete, but can't modify files in your fork. Could you remove this file?
> blockchains/ethereum/assets/0xd0Df3b1Cf729A29B7404c40D61C750008E631bA7/logo.png
> 
> ```
> remote: Permission to pwqfinance/assets.git denied to catenocrypt.
> fatal: unable to access 'https://github.com/pwqfinance/assets.git/': The requested URL returned error: 403
> ```

I can't delete it either, I don't know why. Please use only 0xa9241C6Bc2f536ddbedca8d95b83Af05988f6AFe to help us add logo to PWQ. Thanks very much

**Comment by catenocrypt** [comment]
Continued in #3750, payment considered to there, closing this PR

**Pull request closed without merging**
