### PR TITLE
DOGEFI - adding logo to UNISWAP

### PR DESCRIPTION
**Pull request by Dogebeback**
DOGEFI coin - adding logo to UNISWAP

### CODE REVIEW

**Comment by catenocrypt** [comment]
Please add an `info.json` file next to the `logo.png`, with info about the project, of the form:

```json
{
    "name": "Trust Wallet Token",
    "website": "https://trustwallet.com",
    "short_description": "Utility token to increase adoption of cryptocurrency.",
    "explorer": "https://explorer.binance.org/asset/TWT-8C2"
}
```

**Review by Dogebeback — COMMENTED** [review]
Done

**Comment by catenocrypt** [comment]
I did fixes to the logo and info file

**Comment by Dogebeback** [comment]
Thank you very much @catenocrypt  
Have a great day!

**Pull request merged**
