### PR TITLE
Add MFP OCCLO logo and info

### PR DESCRIPTION
**Pull request by MFPOCCLO**
MFP OCCLO token has been created by R&D teen of DPL LTD on BSC blockchain to be used on variable purposes like NFT, FT, travel booking, and cultural funding. Please add our Logo and asset to the trust wallet so the investors can recognize our token and easily trade.

### CODE REVIEW

**Comment by MFPOCCLO** [comment]
> 
> 
> **PR Summary**
> Files OK, 2Files in PR: 2
> Error: No token files found. If you try to add/modify a token, check the name and location of your files! Logo file must be named exactly 'logo.png'. If you are not adding a token, ignore this message. (2 files in the PR)

There is no problem for us to pay the contribution fee; but since there is an error that says "No token files found", will be any problem about that? and another thing is that how long will our logo take to be submitted?

**Comment by MFPOCCLO** [comment]
> 
> 
> Hi! In order to compensate for the efforts of processing PRs, we kindly ask for a contribution.
> 💀 As **there is no refund**, before **paying the fee**, make sure **new tokens fulfill the minimum circulation and other [acceptance criteria](https://community.trustwallet.com/t/how-to-submit-a-token-logo/3863)**.
> See also the [PR Fee FAQ](https://developer.trustwallet.com/add_new_asset/pr-fee).
> 
> Please pay **250 TWT** with the memo **9186** to the address `bnb1tqq9llyr3dyjd559dha6z5r5etk3qfwk07m098`.
> Alternatively, 2 BNB is also accepted (same memo & address).
> 
> **QR** code: [Trust](https://api.qrserver.com/v1/create-qr-code/?size=200x200&data=https%3A%2F%2Flink.trustwallet.com%2Fsend%3Fcoin%3D714%26address%3Dbnb1tqq9llyr3dyjd559dha6z5r5etk3qfwk07m098%26amount%3D250%26memo%3D9186) | [other wallet](https://api.qrserver.com/v1/create-qr-code/?size=200x200&data=bnb1tqq9llyr3dyjd559dha6z5r5etk3qfwk07m098%26amount%3D250%26memo%3D9186)
> 
> _Notes_:
> 
>     * [Trust Wallet Tokens (TWT)](https://community.trustwallet.com/t/trust-wallet-token-twt/4187) can be obtained through our [Referral Program](https://community.trustwallet.com/t/invite-a-friend-earn-trust-wallet-token-twt/4125) or [from DEXs/exchanges](https://community.trustwallet.com/t/where-to-get-trust-wallet-tokens/76641).
> 
>     * New tokens without significant usage are rejected, see criteria mentioned above.
> 
>     * One PR should be for a single project; PR's with more than 10 logos will be rejected.
> 
>     * Payment evaluation happens automatically, but with a few minutes delay.  When payment is detected, an Accept Review is automatically placed on the PR, which is a condition for merge.
> 
>     * Evaluating the PR is done manually, and it is merged only if all conditions are satisfied.
> 
>     * TWT-BEP2 is supported (Binance Chain), TWT-BEP20 version on Smart Chain is not.

Done

**Comment by Cryptocool1** [comment]
correction needed:
Logo file must be named exactly 'logo.png'.

**Comment by Cryptocool1** [comment]
As per our policy, brand new tokens are not included, there is a minimum requirement of 2500 holder addresses and 5000 transactions, in order to filter out scam tokens.
See the criteria at (mentioned in the first message by the bot): https://community.trustwallet.com/t/how-to-submit-a-token-logo/3863).

**Comment by MFPOCCLO** [comment]
what is the problem that logo and price not shown?

**Comment by cryptomanz** [comment]
> what is the problem that logo and price not shown?

Firstly, you should reach the minimum requirement, then we will merge your PR.

There is a minimum requirement of 2500 holder addresses and 5000 transactions, in order to filter out scam tokens.
See the criteria at (mentioned in the first message by the bot): https://community.trustwallet.com/t/how-to-submit-a-token-logo/3863).

**Comment by Cryptocool1** [comment]
still 36 holders
Please come back to us when all criteria are met.
When creating new PR, mention this PR, so that fee can be reused, and not paid again.

**Comment by MFPOCCLO** [comment]
Dear Admins,

As our project closed and you didnt accept our project. can you send me back my 2 BNB?
if yes how can i do it?

**Pull request closed without merging**
