### PR TITLE
Add Styleo Coin (BEP20)

### PR DESCRIPTION
**Pull request by erience**
Exchange: https://vindax.com/exchange-base.html?symbol=STC_USDT
CMC: https://coinmarketcap.com/currencies/ezcoin-market
Audit Report: https://github.com/Credshields/audit-reports/blob/master/Styleo%20Coin%20Final%20Audit%20Report.pdf

### CODE REVIEW

**Comment by erience** [comment]
• What is the purpose of this token? How will it benefit Trust Wallet users? ---- Styleo Coin Cryptocurrency : We specialize in harnessing blockchain technology to create secure and transparent solutions for diverse industries, empowering businesses with efficiency and trust. It will allow Trust wallet users will be able to directly use the token from the App itself.

• How is the token being distributed? Are you conducting an airdrop? -- Purchase from Exchange. No Airdrop

• Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale? --- No Presale

• Is the token listed on a centralized/decentralized exchange? ---- Yes, https://vindax.com/exchange-base.html?symbol=STC_USDT

• Is a Smart Contract audit completed? Where can we find this information? --- Yes, https://github.com/Credshields/audit-reports/blob/master/Styleo%20Coin%20Final%20Audit%20Report.pdf

**Comment by erience** [comment]
@Cryptocool1 and @cryptomanz1  please check above

**Comment by Cryptocool1** [comment]
Hello, are you listed on CoinMarketCap?

**Comment by erience** [comment]
Yes: https://coinmarketcap.com/currencies/ezcoin-market

**Comment by erience** [comment]
@Cryptocool1 and @cryptomanz1 please check above

**Comment by erience** [comment]
@Cryptocool1 and @cryptomanz1 please check above - getting delayed a lot. Community is waiting and asking for update on hourly basis.

**Comment by erience** [comment]
@Cryptocool1 and @cryptomanz1

**Comment by Mofidzol** [comment]
مفید

در تاریخ جمعه ۳۰ اوت ۲۰۲۴،‏ ۰۱:۰۷ Erience Solutions <
***@***.***> نوشت:

**Comment by Cruptowa** [comment]
@Cryptocool1 and @cryptomanz1, are you even paying attention?

In [this comment](https://github.com/trustwallet/assets/pull/28965#issue-2473124697) , the necessary links to the audit and CoinMarketCap were already provided. Yet, you requested the CoinMarketCap link again [here](https://github.com/trustwallet/assets/pull/28965#issuecomment-2306269844) and then asked for the audit again [here](https://github.com/trustwallet/assets/pull/28965#issuecomment-2303862621).

After the payment was made, there was no response from your side. Are you seriously joking?

Trust Wallet admins, please ensure your team is made up of competent professionals. If this continues, it could lead people to question the legitimacy of your operations.

**Comment by Cruptowa** [comment]
@Cryptocool1 and @cryptomanz1, are you even paying attention?

In [this comment](https://github.com/trustwallet/assets/pull/28965#issue-2473124697), the necessary links to the audit and CoinMarketCap were already provided. Yet, you requested the CoinMarketCap link again [here](https://github.com/trustwallet/assets/pull/28965#issuecomment-2306269844) and then asked for the audit again [here](https://github.com/trustwallet/assets/pull/28965#issuecomment-2303862621).

After the payment was made, there was no response from your side. Are you seriously joking?

Trust Wallet admins, please ensure your team is made up of competent professionals. If this continues, it could lead people to question the legitimacy of your operations.

**Comment by Cruptowa** [comment]
Trustwallet=Scamwallet

**Pull request merged**
