### PR TITLE
Add wXRP logo

### PR DESCRIPTION
**Pull request by wrapperxr**
TOKEN NAME - Wrapped Ripple
SYMBOL - wXRP
TOTAL SUPPLY - 1000000
ADDRESS - 0x77A2Fa10A84E023887Bdcdd8f33D6133bE53E2D2

### CODE REVIEW

**Comment by vikmeup** [comment]
What is the purpose of this token?

**Comment by wrapperxr** [comment]
> What is the purpose of this token?

To wrap xrp on ethereum chain

**Comment by catenocrypt** [comment]
As per our updated policy, brand new tokens are not included, there is a minimum requirement of 100 holder addresses and 500 transactions, in order to filter out scam tokens.
See https://community.trustwallet.com/t/how-to-submit-a-token-logo/3863#how-to-get-approved
Token check: Usage is none (1 addr, 1 tx).  Putting on hold for now.

**Comment by vikmeup** [comment]
As per our updated policy, brand new tokens are not included, there is a minimum requirement 

- at least 100 token holders
- at least 500 transactions

See our [How to Get Submit Token Logo ](https://community.trustwallet.com/t/how-to-submit-a-token-logo/3863#how-to-get-approved) guidelines.

Feel free to re-open once you meet those requirements.

**Pull request closed without merging**
