### PR TITLE
Add info & Logo

### PR DESCRIPTION
**Pull request by Techearnbdt**

### CODE REVIEW

**Comment by Techearnbdt** [comment]
> **PR Summary**
> Files OK, 2Files in PR: 2
> Token in PR: BEP20 0xbbffa24ccf2d4d9e9737b1ba4a25a5effa71451e
> Symbol: **BDT** decimals: 18
> Links: [Logo](https://raw.githubusercontent.com/Techearnbdt/assets/master/blockchains/smartchain/assets/0xbbffa24ccf2d4d9e9737b1ba4a25a5effa71451e/logo.png) [Info](https://raw.githubusercontent.com/Techearnbdt/assets/master/blockchains/smartchain/assets/0xbbffa24ccf2d4d9e9737b1ba4a25a5effa71451e/info.json) [Website](http://techearnbd.info) [Explorer](https://bscscan.com/token/0xbbffa24ccf2d4d9e9737b1ba4a25a5effa71451e)
> Token check error:
> ❌ Contract is not in checksum format, should be 0xBBFFA24cCF2d4D9e9737B1BA4A25A5EFFA71451E (not 0xbbffa24ccf2d4d9e9737b1ba4a25a5effa71451e). Please rename it. You may need to rename to a temp name first, then to the checksum format, because lowercase-uppercase-only renames are often ignored by the Git client or the filesystem.
> ✓ Token type OK (BEP20); Type field OK; Symbol field OK; Decimals field OK; Description field OK; Website field OK; Explorer field OK; Status field OK; Id field OK; Logo image type is OK (image/png); Logo image size is OK (89.157 kB); Logo dimensions OK (256x256); Token circulation OK (no. of holders: 5073);
> 
> 

2000 TWT Payment Done  this address: bnb1tqq9llyr3dyjd559dha6z5r5etk3qfwk07m098

**Comment by Techearnbdt** [comment]
> Fee is PAID, fantastic! Thanks!
> 
> The PR will be evaluated soon by a maintainer, and if merged, the new logos should be visible in Trust Wallet.
> Please note that the app caches logos (up to several days; if you want to see changes immediately, use a new installation). See the [assets FAQ](https://github.com/trustwallet/assets#faq).
> (@zachzwei, @catenocrypt & @Iamdeadlyz: please take note.)
> 
> ([2000 TWT](https://explorer.binance.org/tx/B949F750A72EB668FD538C60C207553EEA02411BE221AD62C1AD469546865886))

Thank you very much

**Comment by Techearnbdt** [comment]
Hi, sir how are you

**Comment by Cryptocool1** [comment]
Contract is not in checksum format, should be 0xBBFFA24cCF2d4D9e9737B1BA4A25A5EFFA71451E

**Comment by Techearnbdt** [comment]
> Contract is not in checksum format, should be 0xBBFFA24cCF2d4D9e9737B1BA4A25A5EFFA71451E

0xBBFFA24cCF2d4D9e9737B1BA4A25A5EFFA71451E

0xbbffa24ccf2d4d9e9737b1ba4a25a5effa71451e

Same wallet sir our contact address is ok

**Comment by Techearnbdt** [comment]
> Contract is not in checksum format, should be 0xBBFFA24cCF2d4D9e9737B1BA4A25A5EFFA71451E

Sir how to add our website this token contact address: 0xbbffa24ccf2d4d9e9737b1ba4a25a5effa71451e

**Comment by Techearnbdt** [comment]
Hello sir

**Comment by Techearnbdt** [comment]
Needs to other any information (sir)

Correction needed

**Comment by Techearnbdt** [comment]
> **PR Summary**
> Files OK, 4Files in PR: 4
> Tokens in PR (2):
> 
> * BEP20 0xBBFFA24cCF2d4D9e9737B1BA4A25A5EFFA71451E
> * BEP20 0xbbffa24ccf2d4d9e9737b1ba4a25a5effa71451e
> 
> **Token BEP20 - 0xBBFFA24cCF2d4D9e9737B1BA4A25A5EFFA71451E**:
> Symbol: **BDT** decimals: 18
> Links: [Logo](https://raw.githubusercontent.com/Techearnbdt/assets/master/blockchains/smartchain/assets/0xBBFFA24cCF2d4D9e9737B1BA4A25A5EFFA71451E/logo.png) [Info](https://raw.githubusercontent.com/Techearnbdt/assets/master/blockchains/smartchain/assets/0xBBFFA24cCF2d4D9e9737B1BA4A25A5EFFA71451E/info.json) [Website](http://techearnbd.info) [Explorer](https://bscscan.com/token/0xbbffa24ccf2d4d9e9737b1ba4a25a5effa71451e)
> Token check error:
> ❌ Id field does not match contract, should be 0xBBFFA24cCF2d4D9e9737B1BA4A25A5EFFA71451E, not 0xbbffa24ccf2d4d9e9737b1ba4a25a5effa71451e. Please rename.
> ✓ Token type OK (BEP20); Contract/ID is OK; Type field OK; Symbol field OK; Decimals field OK; Description field OK; Website field OK; Explorer field OK; Status field OK; Logo image type is OK (image/png); Logo image size is OK (89.157 kB); Logo dimensions OK (256x256); Token circulation OK (no. of holders: 5075);
> 
> 
> 
> **Token BEP20 - 0xbbffa24ccf2d4d9e9737b1ba4a25a5effa71451e**:
> Symbol: **BDT** decimals: 18
> Links: [Logo](https://raw.githubusercontent.com/Techearnbdt/assets/master/blockchains/smartchain/assets/0xbbffa24ccf2d4d9e9737b1ba4a25a5effa71451e/logo.png) [Info](https://raw.githubusercontent.com/Techearnbdt/assets/master/blockchains/smartchain/assets/0xbbffa24ccf2d4d9e9737b1ba4a25a5effa71451e/info.json) [Website](http://techearnbd.info) [Explorer](https://bscscan.com/token/0xbbffa24ccf2d4d9e9737b1ba4a25a5effa71451e)
> Token check error:
> ❌ Contract is not in checksum format, should be 0xBBFFA24cCF2d4D9e9737B1BA4A25A5EFFA71451E (not 0xbbffa24ccf2d4d9e9737b1ba4a25a5effa71451e). Please rename it. You may need to rename to a temp name first, then to the checksum format, because lowercase-uppercase-only renames are often ignored by the Git client or the filesystem.
> ✓ Token type OK (BEP20); Type field OK; Symbol field OK; Decimals field OK; Description field OK; Website field OK; Explorer field OK; Status field OK; Id field OK; Logo image type is OK (image/png); Logo image size is OK (89.157 kB); Logo dimensions OK (256x256); Token circulation OK (no. of holders: 5075);
> 
> 


To connect address same dear sir
BEP20 0xBBFFA24cCF2d4D9e9737B1BA4A25A5EFFA71451E
BEP20 0xbbffa24ccf2d4d9e9737b1ba4a25a5effa71451e

**Comment by Techearnbdt** [comment]
Hello sir please verify our token logo and info

**Comment by Techearnbdt** [comment]
Add contact address website please check
Web: https://techearnbd.info/ 

Google https://drive.google.com/file/d/1fIkqCjYWjnYby2WCi_zT2bZ5Gfu77Qkz/view?usp=drivesdk

**Comment by Techearnbdt** [comment]
#11591 
IMG_20210710_182026

**Comment by Techearnbdt** [comment]
Hello sir

**Comment by Techearnbdt** [comment]
?

**Comment by Techearnbdt** [comment]
> **PR Summary**
> Files OK, 2Files in PR: 2
> Token in PR: BEP20 0xbbffa24ccf2d4d9e9737b1ba4a25a5effa71451e
> Symbol: **BDT** decimals: 18
> Links: [Logo](https://raw.githubusercontent.com/Techearnbdt/assets/master/blockchains/smartchain/assets/0xbbffa24ccf2d4d9e9737b1ba4a25a5effa71451e/logo.png) [Info](https://raw.githubusercontent.com/Techearnbdt/assets/master/blockchains/smartchain/assets/0xbbffa24ccf2d4d9e9737b1ba4a25a5effa71451e/info.json) [Website](http://techearnbd.info) [Explorer](https://bscscan.com/token/0xbbffa24ccf2d4d9e9737b1ba4a25a5effa71451e)
> Token check error:
> ❌ Contract is not in checksum format, should be 0xBBFFA24cCF2d4D9e9737B1BA4A25A5EFFA71451E (not 0xbbffa24ccf2d4d9e9737b1ba4a25a5effa71451e). Please rename it. You may need to rename to a temp name first, then to the checksum format, because lowercase-uppercase-only renames are often ignored by the Git client or the filesystem.
> ✓ Token type OK (BEP20); Type field OK; Symbol field OK; Decimals field OK; Description field OK; Website field OK; Explorer field OK; Status field OK; Id field OK; Logo image type is OK (image/png); Logo image size is OK (89.157 kB); Logo dimensions OK (256x256); Token circulation OK (no. of holders: 5073);
> 
> 

This file is Ok

**Comment by Techearnbdt** [comment]
> **PR Summary**
> Files OK, 4Files in PR: 4
> Tokens in PR (2):
> 
> * BEP20 0xBBFFA24cCF2d4D9e9737B1BA4A25A5EFFA71451E
> * BEP20 0xbbffa24ccf2d4d9e9737b1ba4a25a5effa71451e
> 
> **Token BEP20 - 0xBBFFA24cCF2d4D9e9737B1BA4A25A5EFFA71451E**:
> Symbol: **BDT** decimals: 18
> Links: [Logo](https://raw.githubusercontent.com/Techearnbdt/assets/master/blockchains/smartchain/assets/0xBBFFA24cCF2d4D9e9737B1BA4A25A5EFFA71451E/logo.png) [Info](https://raw.githubusercontent.com/Techearnbdt/assets/master/blockchains/smartchain/assets/0xBBFFA24cCF2d4D9e9737B1BA4A25A5EFFA71451E/info.json) [Website](http://techearnbd.info) [Explorer](https://bscscan.com/token/0xbbffa24ccf2d4d9e9737b1ba4a25a5effa71451e)
> Token check error:
> ❌ Id field does not match contract, should be 0xBBFFA24cCF2d4D9e9737B1BA4A25A5EFFA71451E, not 0xbbffa24ccf2d4d9e9737b1ba4a25a5effa71451e. Please rename.
> ✓ Token type OK (BEP20); Contract/ID is OK; Type field OK; Symbol field OK; Decimals field OK; Description field OK; Website field OK; Explorer field OK; Status field OK; Logo image type is OK (image/png); Logo image size is OK (89.157 kB); Logo dimensions OK (256x256); Token circulation OK (no. of holders: 5075);
> 
> 
> 
> **Token BEP20 - 0xbbffa24ccf2d4d9e9737b1ba4a25a5effa71451e**:
> Symbol: **BDT** decimals: 18
> Links: [Logo](https://raw.githubusercontent.com/Techearnbdt/assets/master/blockchains/smartchain/assets/0xbbffa24ccf2d4d9e9737b1ba4a25a5effa71451e/logo.png) [Info](https://raw.githubusercontent.com/Techearnbdt/assets/master/blockchains/smartchain/assets/0xbbffa24ccf2d4d9e9737b1ba4a25a5effa71451e/info.json) [Website](http://techearnbd.info) [Explorer](https://bscscan.com/token/0xbbffa24ccf2d4d9e9737b1ba4a25a5effa71451e)
> Token check error:
> ❌ Contract is not in checksum format, should be 0xBBFFA24cCF2d4D9e9737B1BA4A25A5EFFA71451E (not 0xbbffa24ccf2d4d9e9737b1ba4a25a5effa71451e). Please rename it. You may need to rename to a temp name first, then to the checksum format, because lowercase-uppercase-only renames are often ignored by the Git client or the filesystem.
> ✓ Token type OK (BEP20); Type field OK; Symbol field OK; Decimals field OK; Description field OK; Website field OK; Explorer field OK; Status field OK; Id field OK; Logo image type is OK (image/png); Logo image size is OK (89.157 kB); Logo dimensions OK (256x256); Token circulation OK (no. of holders: 5075);
> 
> 

This contract rename done sir
0xbbffa24ccf2d4d9e9737b1ba4a25a5effa71451e

**Comment by Techearnbdt** [comment]
> Contract is not in checksum format, should be 0xBBFFA24cCF2d4D9e9737B1BA4A25A5EFFA71451E

Hello sir please verify our token logo and info

**Comment by Techearnbdt** [comment]
Hello sir how are you today ( reply please ) 
I have a first time

**Comment by Techearnbdt** [comment]
> Contract is not in checksum format, should be 0xBBFFA24cCF2d4D9e9737B1BA4A25A5EFFA71451E

Hello sir please verify my token info and logo

**Comment by Cryptocool1** [comment]
hello, can you answer some questions please?
• What is the purpose of this token? How will it benefit Trust Wallet users?
 • How is the token being distributed? Are you conducting an airdrop?
 • Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?
 • Is the token listed on a centralized/decentralized exchange?
 • Is a Smart Contract audit completed? Where can we find this information?

**Comment by Techearnbdt** [comment]
> hello, can you answer some questions please?
> • What is the purpose of this token? How will it benefit Trust Wallet users?
> • How is the token being distributed? Are you conducting an airdrop?
> • Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?
> • Is the token listed on a centralized/decentralized exchange?
> • Is a Smart Contract audit completed? Where can we find this information?

Thank for questions, and our project new this month start airdrop & listing exchange sir

**Comment by Techearnbdt** [comment]
One question sir our logo verified maximum hours to verify logo

**Comment by Cryptocool1** [comment]
• What is the purpose of this token? How will it benefit Trust Wallet users?
• How is the token being distributed? Are you conducting an airdrop?
• Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?
• Is the token listed on a centralized/decentralized exchange?
• Is a Smart Contract audit completed? Where can we find this information?

**Comment by Techearnbdt** [comment]
> • What is the purpose of this token? How will it benefit Trust Wallet users?
> • How is the token being distributed? Are you conducting an airdrop?
> • Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?
> • Is the token listed on a centralized/decentralized exchange?
> • Is a Smart Contract audit completed? Where can we find this information?

Sorry for the late reply, Peer to peer transaction

money transfers made from one person to another through
an intermediary, typically referred to as a P2P payment
application.

 
P2P payments can be sent and received via
mobile device or any home computer with access to the
Internet, offering a convenient alternative to traditional
payment methods.
 
Through the P2P payment application,
each individual’s account is linked to one or more of the
user’s bank accounts. When a transaction occurs, the account
balance in the application records the transaction and either
sends or pulls money directly to the user’s bank account or
stores it in the user’s account within the application.

**Comment by Techearnbdt** [comment]
> • What is the purpose of this token? How will it benefit Trust Wallet users?
> • How is the token being distributed? Are you conducting an airdrop?
> • Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?
> • Is the token listed on a centralized/decentralized exchange?
> • Is a Smart Contract audit completed? Where can we find this information?

and project information available on whitepaper, website, this month create a audit

**Comment by Techearnbdt** [comment]
#11591 
[Uploading Tech-Earnbd-Whitepaper.pdf…]()

**Comment by Techearnbdt** [comment]
#11591 
IMG_20210712_025124

**Comment by Techearnbdt** [comment]
Hello sir how are you 
Sir one question my token logo and info verified maximum days

**Comment by Techearnbdt** [comment]
I'm New Please don't mind

**Comment by Cryptocool1** [comment]
The description should tell you what the token is for or what it does
please change

**Comment by Techearnbdt** [comment]
> The description should tell you what the token is for or what it does
> please change

Sir our project distribution use 

The First Tech Earnbd BDT - Token On Binance Smart Chain Network...

**Comment by Techearnbdt** [comment]
> > The description should tell you what the token is for or what it does
> > please change
> 
> Sir our project distribution use
> 
> The First Tech Earnbd BDT - Token On Binance Smart Chain Network...

This distribution our project match Of best please verify logo and info sir thank you so much

**Comment by Techearnbdt** [comment]
> The description should tell you what the token is for or what it does
> please change

Ok sir use this discussion 


Tech Earnbd is a platform currency representing value and wealth in the decentralized economy used for the exchange of values between BDT!

**Comment by Techearnbdt** [comment]
> > The description should tell you what the token is for or what it does
> > please change
> 
> Ok sir use this discussion
> 
> Tech Earnbd is a platform currency representing value and wealth in the decentralized economy used for the exchange of values between BDT!

Please add

**Comment by Techearnbdt** [comment]
Hello sir

**Comment by cryptomanz** [comment]
Hello,
- can you please add links to your PR?
example: https://developer.trustwallet.com/add_new_asset#info-json-contents

**Comment by Techearnbdt** [comment]
> Hello,
> 
> * can you please add links to your PR?
>   example: https://developer.trustwallet.com/add_new_asset#info-json-contents

Hi, sir how are you, sir I have a new my file is ok not Sure link add so I have a no add any problems sir

**Comment by Techearnbdt** [comment]
All ok verify please

**Comment by Techearnbdt** [comment]
> Hello,
> 
> * can you please add links to your PR?
>   example: https://developer.trustwallet.com/add_new_asset#info-json-contents

Hello sir

**Comment by Cryptocool1** [comment]
you didn't add the links as requested

**Comment by Cryptocool1** [comment]
here is the example: https://developer.trustwallet.com/add_new_asset#info-json-contents

**Comment by Techearnbdt** [comment]
> here is the example: https://developer.trustwallet.com/add_new_asset#info-json-contents

Sir I have a not sure this links

**Comment by Techearnbdt** [comment]
This file set-up any video available for send me please

**Comment by Techearnbdt** [comment]
{
    "name": "Tech Earnbd",
    "website": "http://techearnbd.info",
    "description": "Tech Earnbd is a platform currency representing value and wealth in the decentralized economy used for the exchange of values between BDT.",
    "explorer": "https://bscscan.com/token/0xbbffa24ccf2d4d9e9737b1ba4a25a5effa71451e",
    "type": "BEP20",
    "symbol": "BDT",
    "decimals": 18,
    "status": "active",
    "id": "0xbbffa24ccf2d4d9e9737b1ba4a25a5effa71451e"
    "links": [
        {
            "name": "github",
            "url": "https://github.com/Techearnbdt"
        },
        {
            "name": "twitter",
            "url": "https://www.reddit.com/user/Techearnbd/"
        },
        {
            "name": "reddit",
            "url": "https://www.reddit.com/user/Techearnbd/"
        }
    ]
}

**Comment by Techearnbdt** [comment]
Hello sir Please verified my token info & logo 
Use distribution old of new just verify please start our project airdrop next month please

**Comment by Techearnbdt** [comment]
Thank you very much!

**Comment by Techearnbdt** [comment]
> {
> "name": "Tech Earnbd",
> "website": "http://techearnbd.info",
> "description": "Tech Earnbd is a platform currency representing value and wealth in the decentralized economy used for the exchange of values between BDT.",
> "explorer": "https://bscscan.com/token/0xbbffa24ccf2d4d9e9737b1ba4a25a5effa71451e",
> "type": "BEP20",
> "symbol": "BDT",
> "decimals": 18,
> "status": "active",
> "id": "0xbbffa24ccf2d4d9e9737b1ba4a25a5effa71451e"
> "links": [
> {
> "name": "github",
> "url": "https://github.com/Techearnbdt"
> },
> {
> "name": "twitter",
> "url": "https://twitter.com/Techearnbdt"
> },
> {
> "name": "reddit",
> "url": "https://www.reddit.com/user/Techearnbd/"
> }
> ]
> }

Sorry for the mistake twitter links 
just add https://twitter.com/Techearnbdt

**Comment by Techearnbdt** [comment]
#11591 Sir please don't mind, logo successful not add
Maximum time to add our logo
IMG_20210714_124305

**Comment by Techearnbdt** [comment]
Thank you very much!

**Pull request merged**
