### PR TITLE
Add WEB3 (BEP20)

### PR DESCRIPTION
**Pull request by CryptoBotnik**
Adding info for BEP20 token 'WEB3'.

### CODE REVIEW

**Comment by cryptomanz** [comment]
• What is the purpose of this token? How will it benefit Trust Wallet users?
 • How is the token being distributed? Are you conducting an airdrop?
 • Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?
 • Is the token listed on a centralized/decentralized exchange?
 • Is a Smart Contract audit completed? Where can we find this information?

**Comment by CryptoBotnik** [comment]
> • What is the purpose of this token? How will it benefit Trust Wallet users? • How is the token being distributed? Are you conducting an airdrop? • Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale? • Is the token listed on a centralized/decentralized exchange? • Is a Smart Contract audit completed? Where can we find this information?

- The purpose of the token is to provide a high, stable and fixed yield to our users whilst bridging the gap between web2 and web3 for the masses.
- The token was distributed through an IDO, we also airdropped private sale buyers. It is currently available on PancakeSwap with centralised exchanges to come.
- Yes, the second largest ever presale on PinkSale raising over 6000 BNB: https://www.pinksale.finance/#/launchpad/0x8ABC3Be97Eb5C0ea271DB82694483Fd20b9ac281?chain=BSC
- It is currently available on PancakeSwap with centralised exchanges to come: https://pancakeswap.finance/info/token/0x333fd139caef6aa31056cc905987b77b1044d259
- Yes, https://github.com/AuditRateTech/Smart-Contract-Audits/blob/main/The_Web3_Project_0x333FD139cAeF6Aa31056cC905987b77B1044d259.pdf

**Comment by Cryptocool1** [comment]
- we are not accept rate tech audit, only from reputable security audit groups. (Cetik, Hacken, Dessert Finance, InterFi Network, Techrate.)
- As per our policy, brand new tokens are not included, there is a minimum requirement of 10,000 holder addresses and 15,000 transactions, in order to filter out scam tokens.
See the criteria at : https://developer.trustwallet.com/assets/requirements .

**Comment by Cryptocool1** [comment]
Please come back to us when all criteria are met. make sure to mention this PR so the fee can be reused

**Pull request closed without merging**
