### PR TITLE
Add shelling (BEP20)

### PR DESCRIPTION
**Pull request by Shyamthakur33**
Adding info for BEP20 token 'shelling'.

PR created by <a href="https://assets.trustwallet.com">TW Assets Management</a>

### CODE REVIEW

**Comment by Shyamthakur33** [comment]
@Cryptocool1 @cryptomanz1 please check if all details are correct, we are ready with payment. waiting for your reply, thanks

**Comment by Shyamthakur33** [comment]
> @Cryptocool1 @cryptomanz1 please check if all details are correct, we are ready with payment. waiting for your reply, thanks

@Cryptocool1 @cryptomanz1 please update

**Comment by Cryptocool1** [comment]
• What is the purpose of this token? How will it benefit Trust Wallet users?
 • How is the token being distributed? Are you conducting an airdrop?
 • Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?
 • Is the token listed on a centralized/decentralized exchange?
 • Is a Smart Contract audit completed? Where can we find this information?

**Comment by Shyamthakur33** [comment]
> • What is the purpose of this token? How will it benefit Trust Wallet users? • How is the token being distributed? Are you conducting an airdrop? • Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale? • Is the token listed on a centralized/decentralized exchange? • Is a Smart Contract audit completed? Where can we find this information?

@Cryptocool1 please check

 • What is the purpose of this token?
The purpose of SHL, is to build the future of online payments. and there are some key goals and purposes of SHL: 
- Revolutionizing Online Payments: SHL aims to transform how online transactions are conducted, making them more efficient, faster, and secure 
- Trust and Reliability: SHL aspires to be a valuable, solid, and trustworthy foundation for economic exchanges 
- Economic Exchange: By providing a reliable cryptocurrency, SHL aims to facilitate economic exchanges, 
- Transparency and Security: Ensuring transparency in transactions and the security of user data and funds are central to SHL's mission 
 
Therefore, Trust Wallet users can benefit from the integration and use of SHL in several ways:  
- Enhanced Security: Trust Wallet is known for its strong security features, and adding SHL to its list of supported assets means users can securely store and manage their SHL tokens 
- Ease of Use: Trust Wallet provides a user-friendly interface, making it easier for users to send, and receive.  
- Increased Access: Trust Wallet supports a wide range of cryptocurrencies, and by including SHL, it allows users to manage all their digital assets in one place. This makes it more convenient for users who hold SHL to access and utilize their funds.


• How is the token being distributed? Are you conducting an airdrop? 
And ⁠Did you sell the tokens at an Initial Coin Offering (ICO)?**** 
 
 The distribution of a cryptocurrency token like SHL typically involves several key stages and methods to ensure a fair and strategic allocation. 
- Public Sale: A portion of the tokens has sold to the public to raise funds for the project. 
- Private Sale: Tokens sold to selected investors and it was sold at a discounted rate before the public 
 
⁠Is the token listed on a centralized/decentralized exchange?  
 The toke is listed on Pancakeswap a decentralized exchange (DEX) that follow the BEP-20 standard 
 
⁠Is a Smart Contract audit completed? Where can we find this information? 
The contract for SHL is completed and it is available on Github online here is the link: 
 
- https://github.com/TechRate/Smart-Contract-Audits/blob/main/June_2024/shelling.pdf

**Comment by Shyamthakur33** [comment]
@Cryptocool1 @cryptomanz1 please reopen the request.

**Comment by Shyamthakur33** [comment]
> @Cryptocool1 @cryptomanz1 please reopen the request and check the answers to the questions you asked.

@Cryptocool1 @cryptomanz1 please reopen request, we are ready with payment

**Pull request closed without merging**
