### PR TITLE
Add APEcoin logo and info.json

### PR DESCRIPTION
**Pull request by APEtoken**
This PR is being closed due to inactivity. If you wish to continue, please have us reopen the PR before sending your payment.
Do NOT send payments for closed PR, as the fee may by lost!
  (99 vs. 99 hrs)

### CODE REVIEW

**Comment by catenocrypt** [comment]
As per our policy, brand new tokens are not included, there is a minimum requirement of 2500 holder addresses and 5000 transactions, in order to filter out scam tokens.
See the criteria at (mentioned in the first message by the bot): https://community.trustwallet.com/t/how-to-submit-a-token-logo/3863).
This token has below limit usage yet (1160 holders). Closing PR for now. Please come back to us when all criteria are met.  Multi-chain and staking tokens may get special treatment, let us know if this is the case. 

https://bscscan.com/token/0xa9ea4b786ee5b7a733c035564bfd9341a4c9fc1e

**Comment by APEtoken** [comment]
> As per our policy, brand new tokens are not included, there is a minimum requirement of 2500 holder addresses and 5000 transactions, in order to filter out scam tokens.
> See the criteria at (mentioned in the first message by the bot): https://community.trustwallet.com/t/how-to-submit-a-token-logo/3863).
> This token has below limit usage yet (1160 holders). Closing PR for now. Please come back to us when all criteria are met. Multi-chain and staking tokens may get special treatment, let us know if this is the case.
> 
> https://bscscan.com/token/0xa9ea4b786ee5b7a733c035564bfd9341a4c9fc1e

Hi, thank you for reviewing my case. APEcoin is not a new token, it was established in July 2020. We have just recently ported to BSC last month, so thats why it would appear to be new. Also, we are a farming/staking based platform. Most holders and users stake their tokens on Beefy.finance and on our sister project, memefarm.io . Please let me know if I can supply you with more information to confirm the credibly of APEcoin. I can assure you, we have been established for some time and are here to stay!

**Comment by catenocrypt** [comment]
Corrections needed:
- folder corresponding to the token contract should be in 'checksum format', please rename to `0xa9eA4b786ee5b7A733c035564Bfd9341A4c9FC1e` (may need to rename in two steps, as lowercase-uppercase-only renames may be ignored)
- logo is too large, recommended size is 256x256 pixels, max file size is 100 kbytes.


❌  Contract is not in checksum format, should be 0xa9eA4b786ee5b7A733c035564Bfd9341A4c9FC1e (not 0xa9ea4b786ee5b7a733c035564bfd9341a4c9fc1e). Please change it.
❌  Logo image too large, max 100 kB, current 213.944 kB

**Comment by APEtoken** [comment]
> Corrections needed:
> 
> * folder corresponding to the token contract should be in 'checksum format', please rename to `0xa9eA4b786ee5b7A733c035564Bfd9341A4c9FC1e` (may need to rename in two steps, as lowercase-uppercase-only renames may be ignored)
> * logo is too large, recommended size is 256x256 pixels, max file size is 100 kbytes.
> 
> ❌ Contract is not in checksum format, should be 0xa9eA4b786ee5b7A733c035564Bfd9341A4c9FC1e (not 0xa9ea4b786ee5b7a733c035564bfd9341a4c9fc1e). Please change it.
> ❌ Logo image too large, max 100 kB, current 213.944 kB

Hey, thank you for taking the time to tell me the errors. I have made the corrections and created a new PR, its number #6301 . Thanks very much!

**Pull request closed without merging**
