### PR TITLE
Add Carrot Token (BEP20)

### PR DESCRIPTION
**Pull request by heyyo2021**
This PR is being closed due to inactivity. If you wish to continue, please have us reopen the PR before sending your payment, or just create a new one.
Do NOT send payments for closed PR, as the fee may by lost!
  (48 vs. 48 hrs)

### CODE REVIEW

**Comment by heyyo2021** [comment]
Hi

I would like to know if my submitted project is good to go for payment?

Hope to hear from you soon

Regards
Carrot Team

**Comment by heyyo2021** [comment]
Hi

May I know was the project submitted pass all the criteria? as I do not get any notification with the results.

Thank you

Regards
Carrot

**Comment by heyyo2021** [comment]
Hi

I had submitted my project to Trust Wallet and would like to know if the verification of numbers of holders criteria has passed or not?

Hope to hear from you soon.

Carrot

**Comment by cryptomanz** [comment]
Hello,
- can you please add links to your PR?
example: https://developer.trustwallet.com/add_new_asset#info-json-contents

**Comment by heyyo2021** [comment]
Hi Nazar

Pardon me, but I still do not get what links should I be giving.

Thank you very much

Regards
Carrot

**Comment by Cryptocool1** [comment]
> Hi Nazar Pardon me, but I still do not get what links should I be giving. Thank you very much Regards Carrot
> […](#)

example
https://developer.trustwallet.com/add_new_asset#info-json-contents

**Comment by heyyo2021** [comment]
Hi

I've seen the link you have given.

But you need me to provide our project website link or??

**Comment by heyyo2021** [comment]
Also,

it stated that all checks have passed. Meaning am I able to proceed with payment?

thanks

**Comment by cryptomanz** [comment]
you need to follow the example https://developer.trustwallet.com/add_new_asset#info-json-contents

**Comment by Cryptocool1** [comment]
> Hi I had submitted my project to Trust Wallet and would like to know if the verification of numbers of holders criteria has passed or not? Hope to hear from you soon. Carrot
> […](#)

yes it passed

**Comment by heyyo2021** [comment]
Hi

I would like to request the reopening of PR #11507, as I am intending to transfer BNB for the service.

Thank you very much.

Regards
Carrot

**Pull request closed without merging**
