### PR TITLE
Add PVC META (BEP20)

### PR DESCRIPTION
**Pull request by pvcmetaofficial**
Adding info for BEP20 token 'PVC META'.

PR created by <a href="https://assets.trustwallet.com">TW Assets Management</a>

### CODE REVIEW

**Comment by pvcmetaofficial** [comment]
Hello Please Check Everythings are Fine

**Comment by pvcmetaofficial** [comment]
Hello @Cryptocool1 please update logo and info

**Comment by Cryptocool1** [comment]
• What is the purpose of this token? How will it benefit Trust Wallet users?
 • How is the token being distributed? Are you conducting an airdrop?
 • Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?
 • Is the token listed on a centralized/decentralized exchange?
 • Is a Smart Contract audit completed? Where can we find this information?

**Comment by pvcmetaofficial** [comment]
• What is the purpose of this token? How will it benefit Trust Wallet users?
Ans- PVC Meta purpose is work in the field of DeFi, NFT, Gaming and Utility Payment Services. More then 139K Person Hold/ Use PVC Meta Cheack on bscscan https://bscscan.com/token/0x75ca521892de7f2ecfb070cab545c250d0ceb7e3
• How is the token being distributed? Are you conducting an airdrop?
Ans- No, PVC Meta Never conducting any airdrop.
• Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?
Ans- No
• Is the token listed on a centralized/decentralized exchange?
Ans-Listed on Pancakeswap
Here is Link :- https://pancakeswap.finance/swap?outputCurrency=0x75ca521892de7f2ecfb070cab545c250d0ceb7e3
Coinmarket Cap- https://coinmarketcap.com/currencies/pvc-meta/
• Is a Smart Contract audit completed? Where can we find this information?
Ans- No

**Comment by pvcmetaofficial** [comment]
Please Check and Live Logo and Info

**Comment by Cryptocool1** [comment]
We require smart contract audit from reputable companies ( Techrate, Certik, Hacken, Dessert Finance) on hold for now

**Comment by pvcmetaofficial** [comment]
there is no any requirement of  smart contract audit according to Trust wallet term and condition

**Comment by pvcmetaofficial** [comment]
Now we have no plan for audit so please update logo and info

**Comment by Cryptocool1** [comment]
You have to follow our requirements first: https://developer.trustwallet.com/listing-new-assets/requirements
Feel free to come back to us once audit is done. 
we accept audit only from reputable companies (Certik, Techrate, Dessert Finance, Hacken)

**Comment by pvcmetaofficial** [comment]
https://github.com/TechRate/Smart-Contract-Audits/blob/main/July_2023/PVC%20META.pdf

**Comment by pvcmetaofficial** [comment]
Please check audit and update logo and info

**Comment by pvcmetaofficial** [comment]
please reply

**Comment by pvcmetaofficial** [comment]
@Cryptocool1 @cryptomanz1 please process and add logo and info 

Techrate Audit :- https://github.com/TechRate/Smart-Contract-Audits/blob/main/July_2023/PVC%20META.pdf

**Comment by pvcmetaofficial** [comment]
@Cryptocool1 please reply sir

**Pull request closed without merging**
