### PR TITLE
Revert 1 filinomus patch 1

### PR DESCRIPTION
**Pull request by Filinomus**

### CODE REVIEW

**Comment by Filinomus** [comment]
logo

**Comment by kolya182** [comment]
What is token address ?

**Comment by Filinomus** [comment]
0x3A4A0D5b8dfAcd651EE28ed4fFEBf91500345489

**Comment by kolya182** [comment]
Added here https://github.com/trustwallet/assets/commit/38f0474f9cce1d0719a9f124feeafb9d4e7e0f7e

**Pull request closed without merging**
