### PR TITLE
UPDATE TO GOMA TOKEN info.json

### PR DESCRIPTION
**Pull request by CODEXEM**

### CODE REVIEW

**Comment by Cryptocool1** [comment]
1755

**Comment by gomafi** [comment]
Does this mean that the logo should display?. We cannot see it???

On 2021-07-14 13:43, CryptoA wrote:

> Merged #11782 [1] into master.
> 
> --
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub [2], or unsubscribe 
> [3].

-- 

🚀$GOMA🚀

GOMA is a Hyper-Deflationary DeFi token giving back to holders through 
passive growth & burning, staking, reflection & NFTs.

🦎 GOMA on CoinGecko 🦎

https://www.coingecko.com/en/coins/goma-financ

💎GOMA on CoinMarketCap💎

https://coinmarketcap.com/currencies/goma-finance/

COMMUNITIES:

English https://t.me/GomaShiba

Chinese http://t.me/GomaShibaChinese

Links:
------
[1] https://github.com/trustwallet/assets/pull/11782
[2] https://github.com/trustwallet/assets/pull/11782#event-5021408900
[3]

**Comment by Cryptocool1** [comment]
Just wait

**Comment by gomafi** [comment]
Oh sorry! I thought once merged it was done, apologies :)

On 2021-07-14 14:01, CryptoA wrote:

> Just wait
> 
> --
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub [1], or unsubscribe 
> [2].

-- 

🚀$GOMA🚀

GOMA is a Hyper-Deflationary DeFi token giving back to holders through 
passive growth & burning, staking, reflection & NFTs.

🦎 GOMA on CoinGecko 🦎

https://www.coingecko.com/en/coins/goma-financ

💎GOMA on CoinMarketCap💎

https://coinmarketcap.com/currencies/goma-finance/

COMMUNITIES:

English https://t.me/GomaShiba

Chinese http://t.me/GomaShibaChinese

Links:
------
[1] 
https://github.com/trustwallet/assets/pull/11782#issuecomment-880135570
[2]

**Pull request merged**
