### PR TITLE
Add EthVault Token

### PR DESCRIPTION
**Pull request by sensiblelogic**
Add EthVault token logo and details. This token is a complementary token in the SafeVault Ecosystem.

### CODE REVIEW

**Comment by sensiblelogic** [comment]
Please note this token works in unison with the SafeVault Token (Holders: 8,266) as a complementary token within the VaultDEFI Ecosystem. The possibility to trade directly between these tokens has been developed through the use of Hybrid DAPP/DEX along with an xSurge based liquidity pairing. Whilst the holder count is below the requirements, the holders of SafeVault are able to transfer between these two tokens (along with future tokens) and as such share the pool of holders.

Please let me know if I can provide any further information.

James

**Comment by sensiblelogic** [comment]
ETHVault Token further Information (Complementary token to SafeVault - Holders: 8,266)

Certik Security Assessment:
https://www.certik.org/projects/ethvault

Token Tracking:
https://coinmarketcap.com/currencies/ethvault
https://www.coingecko.com/en/coins/ethvault
https://nomics.com/assets/ethvault2-ethvault

Please advise if you require any further information.

Thanks,

James

**Comment by sensiblelogic** [comment]
• What is the purpose of this token? How will it benefit Trust Wallet users?
The purpose of this Token is to act as a complementary token to SafeVault (Holders: 8,266) and allow the holders the opportunity to choose which underlying reflective asset they would like to receive. The ETHVault token allows holders to passively receive Surge Ethereum along with a small amount of SafeVault based on transaction volume and market share. Through a strategic and mathematically assessed fee structure the sell fee is distributed back to holders in these alterantive assets. The rewards are distributed to the holder automatically and can be manually triggered through our Dapp. The reflective tokens, i.e. Surge ETH and SafeVault have both had Certik Security Assessments undertaken with excellent results.

• How is the token being distributed? Are you conducting an airdrop?
The token is active and being distributed on the Binance Smart Chain network through the use of a secure smart contract and Pancake Swap liquidity pairing. Further information can be found on coinmarketcap.com/currencies/ethvault
A Trader App that allows for direct transfer between SafeVault and ETHVault is being released which utilises a novel concept of xTraders released by xSurge DEFI.

• Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?
A token presale was conducted through DXSale in August 2021.

• Is the token listed on a centralized/decentralized exchange?
ETHVault is currently listed on Pancakeswap and as actively traded through this DEX. We are currently in negotiations for an exchange listing.

A Certik Audit with excellent results has been completed and the Skynet Service is active on this token.

Please let me know if I can provide any further information. 

Thank you,

James

**Comment by cryptomanz** [comment]
As per our policy, brand new tokens are not included, there is a minimum requirement of 5000 holder addresses and 10000 transactions, in order to filter out scam tokens.
See the criteria at (mentioned in the first message by the bot): https://community.trustwallet.com/t/how-to-submit-a-token-logo/3863).

**Comment by sensiblelogic** [comment]
Hi Cryptomanz,

Thanks for your reply. I note the criteria mentions that the 5000 holder count is subject to review based on the Project. I would request consideration of the following:

- The Parent token SafeVault has 8,266 holders
- This token is a child token of Safevault providing additional utility for the holders of SafeVault (Many of which are utilising Trust Wallet)
- VaultDefi LLC is the ultimate management company for this token ecosystem and the relation between tokens can be seen through a common social media presence representing the one ecosystem. 
- This token provides reflection in both Surge ETH (Certik Audited) as well as SafeVault, further illustrating the connection between the tokens.
- The token smart contract is a modified version of the SafeVault  contract to provide holders an opportunity to choose which asset they will receive reflections through.
- ETHVault & SafeVault have both undertaken Certik Security Assessment and have Skynet 24/7 Monitoring Service active.

I hope you can consider that this token would fit within the review for "Token Holders" given the direct relation with SafeVault and the overall purpose of the token.

Thank you.

James

**Pull request merged**
