### PR TITLE
Add DeXe token logo and info.json

### PR DESCRIPTION
**Pull request by vitaliimaistrenko**

### CODE REVIEW

**Comment by Iamdeadlyz** [comment]
As per our policy, brand new tokens are not included. There is a minimum requirement of 2500 holder addresses and 5000 transactions (airdropped tokens excluded) in order to filter out scam tokens. See the criteria at (mentioned in the first message by the bot): https://community.trustwallet.com/t/how-to-submit-a-token-logo/3863#how-to-get-approved

This token has below-limit usage yet. This pull request will be put on hold. Please come back to us when all criteria are met.
https://etherscan.io/token/0xde4EE8057785A7e8e800Db58F9784845A5C2Cbd6 (523, 12031) 9̶8̶0̶,̶ ̶1̶2̶4̶8̶8̶

**Comment by Iamdeadlyz** [comment]
Let us know once you have reached the requirements so we can re-open this PR.

**Comment by vitaliimaistrenko** [comment]
Hey guys 
On etrherium we hawe 1911 holders https://etherscan.io/token/0xde4EE8057785A7e8e800Db58F9784845A5C2Cbd6
And on Binance smart chain we have 2,067 https://bscscan.com/token/0x039cb485212f996a9dbb85a9a75d898f94d38da6
Also here is Our token on Binance https://www.binance.com/ru/trade/DEXE_BUSD?layout=pro

Can now you add dexe token logo to the asset list?

**Comment by vitaliimaistrenko** [comment]
> Let us know once you have reached the requirements so we can re-open this PR.

Hey guys
On Ethereum we have 1911 holders https://etherscan.io/token/0xde4EE8057785A7e8e800Db58F9784845A5C2Cbd6
And on Binance smart chain we have 2,067 https://bscscan.com/token/0x039cb485212f996a9dbb85a9a75d898f94d38da6
Also here is Our token on Binance https://www.binance.com/ru/trade/DEXE_BUSD?layout=pro

Can now you add DEXE token logo to the asset list?

**Comment by catenocrypt** [comment]
Combined circulation OK.

**Pull request merged**
