### PR TITLE
Please Add these Tokens on Trust Wallet

### PR DESCRIPTION
**Pull request by ghost**

### CODE REVIEW

**Comment by SaAtHi1** [comment]
Payment Done 0.5 BNB

photo_2020-04-14_02-37-40

**Comment by SaAtHi1** [comment]
Payment Done 0.5 BNB

photo_2020-04-14_02-37-40

**Comment by catenocrypt** [comment]
Payment not seen. Please provide Txid to check.

**Comment by kolya182** [comment]
@SaAtHi1 Found it, you did inserted wrong memo instead `1902` transaction contains `1907` https://explorer.binance.org/tx/895FAC20737F78D795E2E66365CDB86B32B15E93174CCC4726DF55857B0666E5

**Pull request merged**
