### PR TITLE
Create SeChain

### PR DESCRIPTION
**Pull request by acashcoin**
we need to update logo for SeChain
https://etherscan.io/token/0xf5717f5df41ea67ef67dfd3c1d02f9940bcf5d08
logo

### CODE REVIEW

**Comment by acashcoin** [comment]
please update SeChain Logo
https://etherscan.io/token/0xf5717f5df41ea67ef67dfd3c1d02f9940bcf5d08
logo

**Comment by acashcoin** [comment]
payment done  now

**Comment by acashcoin** [comment]
please update SeChain Logo

**Comment by acashcoin** [comment]
@kolya182  We paid , please we need to update the icon 
Thanks.

**Comment by acashcoin** [comment]
Hello 
The icon appear small , the yellow border have to be in border , the icon need to be little bigger and zoom

**Comment by acashcoin** [comment]
dear sir,
the icon need to be zoomed  , its having white boarder and need to be removed , the yellow border have to be in edge , not surrounded
logo
 by white

**Comment by catenocrypt** [comment]
@acashcoin , I think you misunderstand how Git Pull Requests work.  A contributor creates a change set to the best of his/her knowledge.  The maintainers check, and if the change is correct and good quality, they accept it.
Sorry, we will not edit your image.  For crypto projects to be included, producing an own good-quality logo is a minimum reqiurement.  The fee is for merging only, not for adjusting images for you.

**Pull request merged**
