### PR TITLE
Pls add HPS

### PR DESCRIPTION
**Pull request by BHCHappiness**
our token for NFT Market Place development

### CODE REVIEW

**Comment by BHCHappiness** [comment]
sent

payment sent

**Comment by BHCHappiness** [comment]
HPS smart contract: 

https://bscscan.com/token/0xeda21b525ac789eab1a08ef2404dd8505ffb973d

**Comment by BHCHappiness** [comment]
@Iamdeadlyz Hello any update.

Salamat/Thank you

**Comment by Iamdeadlyz** [comment]
As per our policy, brand new tokens are not included. There is a minimum requirement of 2500 holder addresses and 5000 transactions (airdropped tokens excluded) in order to filter out scam tokens. See the criteria at (mentioned in the first message by the bot): https://community.trustwallet.com/t/how-to-submit-a-token-logo/3863#how-to-get-approved

This token has below-limit usage yet. This pull request will be put on hold. Please come back to us when all criteria are met.
https://bscscan.com/token/0xeda21b525ac789eab1a08ef2404dd8505ffb973d (3, 3)

**Comment by BHCHappiness** [comment]
@Iamdeadlyz Okay thank you we will come back soon.

**Comment by Iamdeadlyz** [comment]
Let us know once you have reached the requirements so we can re-open this PR.

**Comment by BHCHappiness** [comment]
@Iamdeadlyz okay sure we will target next month

**Pull request closed without merging**
