### PR TITLE
Added Unido

### PR DESCRIPTION
**Pull request by ashish-khokhar**
This PR is being closed due to inactivity. If you wish to continue, please have us reopen the PR before sending your payment.
Do NOT send payments for closed PR, as the fee may by lost!
  (99 vs. 99 hrs)

### CODE REVIEW

**Comment by ashish-khokhar** [comment]
The payment has made with this PR https://github.com/trustwallet/assets/pull/6381

**Comment by catenocrypt** [comment]
> @catenocrypt The payment has been made with this PR #6381

Could you provide TXID for me to check?  #6381 is not marked paid, I assume payment was done after it was closed, but I can't find it any more (too many TXs).

**Comment by ashish-khokhar** [comment]
@catenocrypt Thanks for replay, here's TXID 5F1F8F58623C590567236CD344F6E041DC8CF4DABA06921083E4B618D98E1C73

**Comment by ashish-khokhar** [comment]
@catenocrypt please reopen this PR

**Comment by catenocrypt** [comment]
Payment considered: https://explorer.binance.org/tx/5F1F8F58623C590567236CD344F6E041DC8CF4DABA06921083E4B618D98E1C73 (for #6381)

**Pull request merged**
