### PR TITLE
Added BNBTC logo.png and info.json files

### PR DESCRIPTION
**Pull request by BNbitcoin**
BNbitcoin (BNBTC) logo and info available for token information update.

### CODE REVIEW

**Comment by Cryptocool1** [comment]
Correction needed:
Field 'research' is not needed, please remove it.

**Comment by BNbitcoin** [comment]
> Correction needed:
> Field 'research' is not needed, please remove it.

Hello Cryptocool1, thanks for suggestion, "research"removed. BNBTC is the first PoW mined BEP20 on BSC, like a re-engineered Bitcoin on top of it, hence it is very different from all the other tokens in terms of holders increase since it is distributed only through mining (no premine, no airdrop, no ICO). Despite that it has less than 1000 users (but increasing day by day), BNBTC is close to 20'000 transactions. Could it be considered, for Trustwallet submission, as a sort of "equivalent" value for listing? Thank you very much in advance! Ron

**Comment by BNbitcoin** [comment]
Thank you!

**Comment by BNbitcoin** [comment]
Payment completed! 250 TWT memo 8071. Thank you in advance, best regards.

**Comment by BNbitcoin** [comment]
Hello,
The label "Payment status: requested" did not change into "Payment status: paid".
Can you please update it?
The transaction can be found at https://explorer.binance.org/tx/A0BCC173AF8CE9906912DB1C45325B6D7187E1CF9A9B569091CDC18C2AFDE4F2
Thank you in advance.
R

**Pull request merged**
