### PR TITLE
Add ARCANE TOKEN (BEP20)

### PR DESCRIPTION
**Pull request by ye4ever**
Adding info for BEP20 token 'ARCANE TOKEN'.

PR created by <a href="https://assets.trustwallet.com">TW Assets Management</a>

### CODE REVIEW

**Review by Yildiz81 — COMMENTED** [review]
blockchains/binance/assets/0x477565B356B3973d16e8CD837C6970613f13e24A/info.json

**Comment by cryptomanz** [comment]
• What is the purpose of this token? How will it benefit Trust Wallet users?
 • How is the token being distributed? Are you conducting an airdrop?
 • Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?
 • Is the token listed on a centralized/decentralized exchange?
 • Is a Smart Contract audit completed? Where can we find this information?

**Comment by ye4ever** [comment]
• What is the purpose of this token? How will it benefit Trust Wallet users?
Arcane Token is a deflationary Token with solid tokenomics that helps the
project to grow healthy and steady,
long term holder get rewarded and we are aiming to be the number 1. NFT
Token that will be anchored in this world for a long time.
• How is the token being distributed? Are you conducting an airdrop?
FairLaunch , no airdrop
• Did you sold the tokens at an Initial Coin Offering (ICO) or a token
presale?
No
• Is the token listed on a centralized/decentralized exchange?
Yes :
bkex
https://www.bkex.com/trade/ARCANE_USDT
pancakeswap
https://pancakeswap.finance/swap?outputCurrency=0x477565b356b3973d16e8cd837c6970613f13e24a
FegEx :
https://fegex.com/trade/bsc/0x451721674411d659952525a697a438885ad741f9
• Is a Smart Contract audit completed? Where can we find this information?
Yes :
https://github.com/Tech-Audit/Smart-Contract-Audits/blob/main/TECHAUDIT_ARCANE.pdf

**Comment by cryptomanz** [comment]
As per our policy, brand new tokens are not included, there is a minimum requirement of 10,000 holder addresses and 20,000 transactions, in order to filter out scam tokens.
See the criteria at : https://developer.trustwallet.com/assets/requirements .

**Comment by ye4ever** [comment]
Dear,
Our team at Arcane Token appreciates you taking the time to answer us.
As of your last reply, the issue seems that 10k holders and 20k transactions are required "in order to filter out scam tokens" 
I hope we can convince you Arcane Token is not a scam, and feel free to look into our token.
What we did to make investors feel safe and prove we are not a scam is that we had a fair launch, renounced the contract, LP locked for a year, and 2% of taxes go to LP and it is sent to the burn wallet, which means it cannot be touched ever by any developers, or owners as the contract has been renounced.
We at Arcane Token have developers, designers, and promoters working around the clock to grow our name and also finish our project (NFT & NFT Market Place), We aim to revolutionize the idea of NFT Market Place and to gain the full trust of our investors we need to have a logo on Trust Wallet.
Below listed all proofs for Locked Liquidity, Renounced contract, and 2% added liquidity to LP in burn wallet.
If any further documents are needed or verification of the developer identity we can provide that as well.
I hope this message finds you well, and we are always here at Arcane Token ready to answer further questions.
Sincerely,
Arcane Token

LP locked for 1 year
1 - https://dxsale.app/app/v3/dxlockview?id=0&add=0xa6B98C7f4fE71244AD03B9C83b718023cd16DD25&type=lplock&chain=BSC
2 - https://dxsale.app/app/v3/dxlockview?id=1&add=0xa6B98C7f4fE71244AD03B9C83b718023cd16DD25&type=lplock&chain=BSC

LP 2% adding to burn wallet to be locked forever tell now it is own 11% in one month 
https://bscscan.com/token/0x8fd2ae8a1bd9f7b306b0bd2772d1fe01feae2648?a=0x000000000000000000000000000000000000dead

Renounced contract
https://bscscan.com/token/0x477565b356b3973d16e8cd837c6970613f13e24a#readContract
you can see owner is the burn wallet 
0x000000000000000000000000000000000000dead address

**Comment by Cryptocool1** [comment]
Please come back to us when all criteria are met.

**Comment by Cryptocool1** [comment]
When creating a new PR make sure to mention this PR, so that we can see that fee has been paid already here.

**Comment by ye4ever** [comment]
Hello, 
Our supply was verified by coingecko
https://www.coingecko.com/en/coins/arcane-token
And our holder now almost 5799 
can you please add logo to trust wallet now

**Pull request closed without merging**
