### PR TITLE
Add MSB token logo (msb.magicoption.co magicoption.co)

### PR DESCRIPTION
**Pull request by magicmsb**

### CODE REVIEW

**Comment by catenocrypt** [comment]
Hi! In order to compensate for the efforts of processing PRs, we kindly ask for a contribution.
Before paying the fee, make sure new tokens fulfill the [acceptance criteria](https://community.trustwallet.com/t/how-to-submit-a-token-logo/3863#how-to-get-approved) (there is no fee refund in case of rejection).
See also the [PR Fee FAQ](https://developer.trustwallet.com/add_new_asset/pr-fee).

Please pay  **1000 TWT**  with the memo **4781**  to the address `bnb1tqq9llyr3dyjd559dha6z5r5etk3qfwk07m098`.
Alternatively, 6 BNB is also accepted (same memo & address).

**QR** code: [Trust](https://api.qrserver.com/v1/create-qr-code/?size=200x200&data=https%3A%2F%2Flink.trustwallet.com%2Fsend%3Fcoin%3D714%26address%3Dbnb1tqq9llyr3dyjd559dha6z5r5etk3qfwk07m098%26amount%3D1000%26memo%3D4781) | [other wallet](https://api.qrserver.com/v1/create-qr-code/?size=200x200&data=bnb1tqq9llyr3dyjd559dha6z5r5etk3qfwk07m098%26amount%3D1000%26memo%3D4781)

*Notes*:
* [Trust Wallet Tokens (TWT)](https://community.trustwallet.com/t/trust-wallet-token-twt/4187) can be obtained through our [Referral Program](https://community.trustwallet.com/t/invite-a-friend-earn-trust-wallet-token-twt/4125) or [from DEXs/exchanges](https://community.trustwallet.com/t/where-to-get-trust-wallet-tokens/76641).
* New tokens without significant usage are rejected, see criteria mentioned above.
* One PR should be for a single project; PR's with more than 10 logos will be rejected.
* Payment evaluation happens automatically, but with a few minutes delay.  When payment is detected, an Accept Review is automatically placed on the PR, which is a condition for merge.
* Evaluating the PR is done manually, and it is merged only if all conditions are satisfied.
* TWT-BEP2 is supported (Binance Chain), TWT-BEP20 version on Smart Chain is not.

**Comment by catenocrypt** [comment]
Please add an `info.json` file next to the `logo.png`, with info about the project, of the form:

```json
{
    "name": "Trust Wallet Token",
    "website": "https://trustwallet.com",
    "short_description": "Utility token to increase adoption of cryptocurrency.",
    "explorer": "https://etherscan.io/token/0xA866F0198208Eb07c83081d5136BE7f775c2399e",
    "socials": [
        {
            "name": "Twitter",
            "url": "https://twitter.com/trustwalletapp",
            "handle": "TrustWalletApp"
        },
        {
            "name": "Reddit",
            "url": "https://reddit.com/r/trustapp",
            "handle": "TrustApp"
        }
    ]
}
```

**Comment by Iamdeadlyz** [comment]
In accordance with our [disclaimer](https://github.com/trustwallet/assets#disclaimer), your PR is denied due to the following reason:
- Plagiarized information with the intent to mislead users
image
image

- Fake partners
image

**Comment by magicmsb** [comment]
@Iamdeadlyz We buy the html template license in the code market so we do not clean up the content. We have revised the content to avoid misleading, please reconsider. Best regards !

**Comment by Iamdeadlyz** [comment]
Your main domain also contains plagiarized content. The reasoning is not considered and **this status will never be lifted**.

image
image
image
image
image

**Comment by magicmsb** [comment]
@Iamdeadlyz I didn't know that my team design marked many ideas like this. I need one more chance to fix these and take care of the idea thieves. Hope to have more consent from you. Thank you!

**Pull request closed without merging**
