### PR TITLE
Add W3C info and logo

### PR DESCRIPTION
**Pull request by 597081195**
Add W3C info and logo

### CODE REVIEW

**Comment by cryptomanz1** [comment]
As per our policy, brand new tokens are not included, there is a minimum requirement of 10,000 holder addresses and 15,000 transactions, in order to filter out scam tokens.
See the criteria at : https://developer.trustwallet.com/assets/requirements .

**Comment by 597081195** [comment]
I have paid you 700TWT, Memo22319,The merger failed. What should I do？

**Comment by 597081195** [comment]
> 根据我们的政策，不包括全新的代币，至少需要 10,000 个持有人地址和 15,000 笔交易，才能过滤掉诈骗代币。 请参阅以下标准：[https](https://developer.trustwallet.com/assets/requirements) ://developer.trustwallet.com/assets/requirements 。



> I have paid you 700TWT, Memo22319,The merger failed. What should I do？

**Comment by cryptomanz1** [comment]
Could you send me transaction?

**Comment by cryptomanz1** [comment]
#22319

**Comment by cryptomanz1** [comment]
As per our policy, brand new tokens are not included, there is a minimum requirement of 10,000 holder addresses and 15,000 transactions, in order to filter out scam tokens.
See the criteria at : https://developer.trustwallet.com/assets/requirements .

**Comment by 597081195** [comment]
> 你能把交易发给我吗？


How can I send it to you？

**Comment by 597081195** [comment]
> 你能把交易发给我吗？

610D7A65B921DE212D659B6FF79E1BE930E4F06D627752BF625CEC65BF162F38

**Comment by 597081195** [comment]
Can you help me with what's the problem? Why did the merger fail? Thank you！

**Comment by 597081195** [comment]
Should I change my account and resubmit it？

**Pull request closed without merging**
