### PR TITLE
Add GameStation (POLYGON)

### PR DESCRIPTION
**Pull request by NoahMaizels**
Adding info for POLYGON token 'GameStation'.

PR created by <a href="https://assets.trustwallet.com">TW Assets Management</a>

### CODE REVIEW

**Comment by noahniuwa** [comment]
Refer to PR #15158 which has already been paid.

https://github.com/trustwallet/assets/pull/15158

Answers to questions:

• What is the purpose of this token? How will it benefit Trust Wallet users?

$GAMER is a utility token. It allows user to access IGO hosted on the GameStation launchpad. To do so, users have to stake $GAMER to be eligible for guaranteed allocation, FCFS pool, or Lottery pool. Moreover, we are working to use it as a mean of paiement to access IGOs.

• How is the token being distributed? Are you conducting an airdrop?

 Three IGOs were conducted for the sale of $GAMER (with Equinox, GameFi, and MANTRADAO Zendit). Moreover, LP staking program are also used to distribute the token to LP provider.

• Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?

$GAMER was sold during three IDOs, as well during private sales.

• Is the token listed on a centralized/decentralized exchange?

$GAMER is listed on QuickSwap and HotBit at the moment. We are planning to list it on PancakeSwap next week.

• Is a Smart Contract audit completed? Where can we find this information?

https://www.gamestation.io/assets/docs/GameStation-SC-Audit.pdf

**Comment by Cryptocool1** [comment]
could you add the links?
see the example here: https://developer.trustwallet.com/assets/repository_details

**Comment by noahniuwa** [comment]
> 
> 
> could you add the links? see the example here: https://developer.trustwallet.com/assets/repository_details

Which links should be added where? Currently there are Twitter, Telegram, and Medium links. The 'repository_details' page in the docs you linked to didn't make it clear what I should add.

**Comment by Cryptocool1** [comment]
can you look carefully at the doc I sent?

**Comment by Cryptocool1** [comment]
Please come back to us when all criteria are met.
When creating a new PR make sure to mention this PR, so that we can see that fee has been paid already here.

**Comment by noahniuwa** [comment]
> can you look carefully at the doc I sent?

I read the doc and don't know what links you are referring to. I have submitted and gotten several tokens listed on Trustwallet before. The JSON file in the commit appears the same as the ones I have submitted and had passed previously, and also looks the same as in the doc you sent, which I just read through again and still am unable to see what you are referring to as missing. Only one section in that doc mentions "links", and it refers to the socials links. The socials links are included in my commit, so I don't know what is missing.

**Comment by cryptomanz** [comment]
Please remove this file:
Screenshot 2021-11-21 at 00 58 31

**Comment by cryptomanz** [comment]
are you the owner of this token
Screenshot 2021-11-21 at 01 05 02
?

**Comment by noahniuwa** [comment]
> are you the owner of this token? Screenshot 2021-11-21 at 01 05 02

I am not the owner but I submitted information on behalf of the owner. I work for Fomocraft who advises and incubates various early stage crypto projects. Finxflo was one of our clients but we no longer work with them. I can alert them for you if there is an issue they need to take care of.

**Comment by noahniuwa** [comment]
> are you the owner of this token? Screenshot 2021-11-21 at 01 05 02

Actually I don't understand why this is showing up in this commit...last time I did anything with Finxflo was months ago. I submitted for Gamestation this time using the new webapp rather than a normal commit, not sure if that messed something up?

**Comment by cryptomanz** [comment]
Please follow the rules for adding token, your logo should be a full screen  (256x256).

**Comment by noahniuwa** [comment]
> Please follow the rules for adding token, your logo should be a full screen (256x256).

Are you talking about Finxflo? I don't know why that is even showing here under this commit....I did this commit for GameStation through the new webapp submitting tokens. The logo I submitted for GameStation is 256 by 256. I haven't touched anything Finxflo related for several months when Finxflo was last a client of ours. 

https://github.com/trustwallet/assets/blob/47810a79b88f7a2a1e7afea85b7f4bede10e1be7/blockchains/polygon/assets/0x3f6b3595ecF70735D3f48D69b09C4E4506DB3F47/logo.png

I think this is a problem with your webapp since previously I have always done a manual commit and not used the webapp and never faced any of these issues.

**Comment by noahniuwa** [comment]
> Please follow the rules for adding token, your logo should be a full screen (256x256).

If you click on the "Files Changed" section you'll see there is nothing Finxflo related, and it shows the logo.png and info.json file, both of which I believe are following the correct format.

**Comment by noahniuwa** [comment]
> Please follow the rules for adding token, your logo should be a full screen (256x256).

I don't know why the old FXF logo is a part of this commit....but in any case, both the FXF logo and GameStation logo are 256x256. I suppose that there shouldn't be info from two tokens in one PR, I'm not sure how you want to deal with this? When I do the PR through the webapp it includes the Finxflo info....so do you want to instead close this PR and then I can make a manual PR myself without using the webapp which doesn't include the Finxflo info?

**Comment by noahniuwa** [comment]
I think I know what is happening now. When I submit a new token in the webapp I assume that it should make a clean fork of the asset repo with my new token info. However, that's not what happened. I think I had previously forked the asset repo for a different token months ago, and when I tried to use the webapp, it didn't make a clean fork, and rather it just added to the old fork. So when it prepared a PR it included info from two tokens. I will close this PR, delete the old fork, and try again.

**Comment by noahniuwa** [comment]
@cryptomanz @Cryptocool1 

I deleted the fork with commits from two tokens and made a new, clean fork and resubmitted the info for GameStation here:

https://github.com/trustwallet/assets/pull/15911

I'm not sure what the deal with the links / logo size was...I believe that part I formatted properly, and I think that having info from two tokens somehow set off those warnings on your end.

**Pull request closed without merging**
