### PR TITLE
AFA Virtual Coin

### PR DESCRIPTION
**Pull request by echapeta**

### CODE REVIEW

**Comment by echapeta** [comment]
Hello,

 

I just sent 0.08 ETH to 0xB46224E545c3F1Fa4D05f94465D13f777866a77B , at the transaction:

 

https://u9455015.ct.sendgrid.net/ls/click?upn=WNbsy6qFrPkVfeApOza7cKHZ69Qw1a8iakxIeN4-2BDUEbLfl7Iv5AnbpgC7Zbl80pMn0kgce7JIO8l6hYIHe-2BUZnjTYJfHcXlzwr2rPMzNSJwXmA6Qgx9UczvJ9yIKAlw17H5S7NzRu69ntGu4KWD2w-3D-3DcOcP_U31jt5HgHBh7k3Grc5s4l5m-2FLVl2zVVdzSw9V2Pe4QiDGX95RiopDplvgSh16L-2BoLcc1Fc0ZDFvVhQLTxZVTZAvPd8L9PNWI-2Fg-2BHzLIdTX11vIzn3OpN8tRAMtkm-2FofMPqESiXMZoJYozQhJGNaIJxfMoCTQtccyMF-2B9KeG5csd9-2F2oMrIJ-2FSSLiDM8sXgUd5khhcxRQmmdDQjoPXpEbrKJAdfRgNt4irgPfGa7o03XoRJHt1FSyOP9oOREB1XXeeOnj-2F5efCgCLViT-2BSSMPkwcCmvzSIcHtrxLKMShO-2F9E-3D

 

Please commit the logo update.

 

 

Thank You.

 

 

 

Eduardo G. Chapeta

CEO

Interwave Global

www.iw-global.com

**Comment by echapeta** [comment]
Hello,

 

I see no icon for the 0xae3274d06b7de181c4a6fbbb5f8bb945a15b5094 AFA Virtual Coin Asset.

 

Could you please confirm?

 

Thank You!

 

 

 

Eduardo G. Chapeta

CEO

Interwave Global

www.iw-global.com

 

 

From: Trust Wallet <support@helptrustwallet.zendesk.com> 
Sent: Tuesday, May 12, 2020 12:39
To: Echapeta <echapeta@iw-global.com>
Subject: [Binance] ： RE: [trustwallet/assets] AFA Virtual Coin (#2067)

 

##- Please type your reply above this line -##

Your request (3124468) has been updated. To add another comment, please reply to this email.



Andrew (Trust Wallet) 

May 12, 2020, 11:39:13 PM GMT+8 


Hi,

Thank you for contacting Trust Wallet Support Team.
I checked already and it has been merged.
https://u9455015.ct.sendgrid.net/ls/click?upn=WNbsy6qFrPkVfeApOza7cHuwqaF8GDbZ9Og2H8Dz8Hg0sY5KjDVZ-2B9i0H9u1LTjEnGZXM-2BiOiDJOpTD5z92y8A-3D-3Djke4_U31jt5HgHBh7k3Grc5s4l5m-2FLVl2zVVdzSw9V2Pe4QiDGX95RiopDplvgSh16L-2BoLcc1Fc0ZDFvVhQLTxZVTZAvPd8L9PNWI-2Fg-2BHzLIdTX3-2FtRbScvsb-2FDPH2pD7QzDmchKqc9JYkDXpbb8jMqA3E24G-2B9H-2F3SvLUcy58vWtL0L37XFG58wnBvsEi-2B5Y1Cb2U7YZEe7mAKEaJsqBPsZPpRY-2FkiHE9RjmQO50Mbdjl6BTuvOL51JUv65E9cDZ1IYVugY89om8Wgyy6Cp7-2F-2FTa7U-2FfC8svOrUDJtFethxbD5M-3D


Stay Decentralized,
Trust Wallet Team Support

Visit our Help Center <https://u9455015.ct.sendgrid.net/ls/click?upn=WNbsy6qFrPkVfeApOza7cJoN9HMRTxEiePMAYYBeXgrjacgTTt6W0Ljk-2BLBVki8ZgeEXjpJQDtBvVWmkqPQyEw-3D-3DBFP7_U31jt5HgHBh7k3Grc5s4l5m-2FLVl2zVVdzSw9V2Pe4QiDGX95RiopDplvgSh16L-2BoLcc1Fc0ZDFvVhQLTxZVTZAvPd8L9PNWI-2Fg-2BHzLIdTX3-2FtRbScvsb-2FDPH2pD7QzDmIfXEQvuWXi1cO-2Bd405PJY-2FMAHvj9G8bqTUft3E13nXZ3cqMJuFTv-2Fnsgrg570XvHCtj9QKO-2B5bABI6LMLOoMsMgUQBRJYIO3YBMfYlWm-2F3UcOSlWh-2BR4K6et-2BvrfHBXXMEg5yuYxirKFJKVbn3kr4m6E6vgvQRwN6k4-2FuvL1KcE-3D>  for FAQs and Guides about Trust Wallet.



 



Echapeta 

May 12, 2020, 9:11:16 PM GMT+8 

Hello,

I just sent 0.08 ETH to 0xB46224E545c3F1Fa4D05f94465D13f777866a77B , at the transaction:

https://u9455015.ct.sendgrid.net/ls/click?upn=WNbsy6qFrPkVfeApOza7cKHZ69Qw1a8iakxIeN4-2BDUEbLfl7Iv5AnbpgC7Zbl80pMn0kgce7JIO8l6hYIHe-2BUZnjTYJfHcXlzwr2rPMzNSJwXmA6Qgx9UczvJ9yIKAlw8LVRQD5G3GbkGbTDhWijIA-3D-3DzDNq_U31jt5HgHBh7k3Grc5s4l5m-2FLVl2zVVdzSw9V2Pe4QiDGX95RiopDplvgSh16L-2BoLcc1Fc0ZDFvVhQLTxZVTZAvPd8L9PNWI-2Fg-2BHzLIdTX3-2FtRbScvsb-2FDPH2pD7QzDm80Jb-2Fin-2BO1cmyKFAlmRKGKBsJ4Ibba3pD79cQVYTsEPoFgSiDuRG3B9-2BPJs-2FV-2Bo7YK-2F9zGVgFkTWM4ujccc1KIn2ku4Vxs0d5-2FCk9OFPgnidhH3KzKJT13gZsMvG8KhI8JKrMfCQFA37oRH92N53M3pJSmS2PTG4622yd5Sa9Xs-3D (https://u9455015.ct.sendgrid.net/ls/click?upn=WNbsy6qFrPkVfeApOza7cHocTBlrjKuRILayPiytPQTiZ2DbN7mb9fVQQrN3MIjmgjJeGWY3ubj4YcEBAx5HsvXI3awXMFFtCT2lSwY8pOcf7EuFbFx8URPDmHFKkZwE8nILkEWgIbydsE2BU-2FIMI8ZBiqXhRtofWUKDEOSrFpue0rromrJVfSZKSx244AsshZgJ-2FU4qCllWtTBitC-2B6YkcPJUl2IQZ3sOeBihUqyRvqSjLxYiCkQS9dslfkWwfOiHakUVjITin-2FczuN2CbZtlAphVkUTJo6L6tHRMA-2FUUwmHQc1D47J5UpOpgMHB9qOCVRWmc8X69l7NFqousTUJCL5yLIFh6r6LFqfP-2BNczUZZOn-2Fvhz2VJeFOgZGXGOuEMlAwZKtaI2b03nSSEWyg0R3D93pFCOtRmXcghBAtugCJXMgNDXbqvz5Gx9c76bXtjUf8xIEi2dOOHqodVr93Fl3D2UjmFimT2PWqapCvMhQHHW7CSA0wFqJd6eOEqICtDU7hJMejAbyy3v7w6Afws9B7eopzvOflM-2BqZHDGtbKcHRdoT84RWn-2BZGjFVAG8Pjsm4Q7sDB2swwHcIwUQmWUJl4j1XGceez7TFP-2FUP4gAzmIzh-2FcgfwZAlEeWS6wxNYzbKfsflP1zTJ-2FKlWmwY-2Bgw-3D-3Dlaqr_U31jt5HgHBh7k3Grc5s4l5m-2FLVl2zVVdzSw9V2Pe4QiDGX95RiopDplvgSh16L-2BoLcc1Fc0ZDFvVhQLTxZVTZAvPd8L9PNWI-2Fg-2BHzLIdTX3-2FtRbScvsb-2FDPH2pD7QzDm0aVLbVt7vyJgAfoeCQP7Hnhk4e-2FdgD34Or65mGD9EeuJwL6OQIM8e8kYcQyD4Nvq5OZw-2B3nwLtZqJz2zHW-2BRRw0-2BXGL5n798jARRVOHDAULjA36zl-2BeWfn-2FrAKEwvqhAwLC98Pa3sfhHOolsPu53LHvisZwOhfN7YDuUxHfw-2Bkc-3D

Please commit the logo update.

Thank You.

Eduardo G. Chapeta

CEO

Interwave Global

www.iw-global.com <https://u9455015.ct.sendgrid.net/ls/click?upn=IqcqsMFWPpg4kD2CiSOd2IH8MOSXRmGeDb6nhwg-2FaZamtoAUvHdZy8pJSutQxgDeFUlD_U31jt5HgHBh7k3Grc5s4l5m-2FLVl2zVVdzSw9V2Pe4QiDGX95RiopDplvgSh16L-2BoLcc1Fc0ZDFvVhQLTxZVTZAvPd8L9PNWI-2Fg-2BHzLIdTX3-2FtRbScvsb-2FDPH2pD7QzDmy8ZWoh364Y4qOXf5xDzeZJQjCK-2FaIVoZ6EFHvYNcZnB5VMWDu-2BU26l-2F7f2ycci0A2haNbZroOhv5l7SRLfOkBGOQiXPKpHkKJ-2BVjb2U1SCQRR1wnsgYSslmGvjEV1UfzMQPAqkAdDY3aMHDE6or165iyZSkrVvkRDtMlqg2yb8k-3D>

**Comment by echapeta** [comment]
Hello,

 

Yes, thank you.

 

But today I entered another request and paid in ETH as mentioned below.

 

Please check the  0xae3274d06b7de181c4a6fbbb5f8bb945a15b5094 AFA Virtual Coin asset

 

Could you please confirm ?

 

Thank You,

 

Eduardo G. Chapeta

CEO

Interwave Global

www.iw-global.com

 

 

From: Trust Wallet <support@helptrustwallet.zendesk.com> 
Sent: Tuesday, May 12, 2020 13:38
To: Echapeta <echapeta@iw-global.com>
Subject: [Binance] ： RE: [trustwallet/assets] AFA Virtual Coin (#2067)

 

##- Please type your reply above this line -##

Your request (3124468) has been updated. To add another comment, please reply to this email.



Andrew (Trust Wallet) 

May 13, 2020, 12:38:00 AM GMT+8 

This was for Revolt Token right?
I checked and it shows now on the app.
​

 



Echapeta 

May 13, 2020, 12:18:22 AM GMT+8 

Hello,

I see no icon for the 0xae3274d06b7de181c4a6fbbb5f8bb945a15b5094 AFA Virtual Coin Asset.

Could you please confirm?

Thank You!

Eduardo G. Chapeta

CEO

Interwave Global

www.iw-global.com <https://u9455015.ct.sendgrid.net/ls/click?upn=IqcqsMFWPpg4kD2CiSOd2IH8MOSXRmGeDb6nhwg-2FaZamtoAUvHdZy8pJSutQxgDeZ6NO_U31jt5HgHBh7k3Grc5s4l5m-2FLVl2zVVdzSw9V2Pe4QiDGX95RiopDplvgSh16L-2BoLcc1Fc0ZDFvVhQLTxZVTZAvPd8L9PNWI-2Fg-2BHzLIdTX2dF2RNTpiQW5g5-2BeN89bJmNA8XU3YCdZR-2BUXGqQhfRqFDdSZhIJpZC4H5-2BwcgiM-2FcChyIZsGu07dxfy8uf0q1YNuDr-2B5zdsFDdz10B-2FY2pZkXfn4YCrvAi26chIg5Fb0QFzN6H2dBhVQdsB8QCMXXEKH7V40vewZ0eqryVUIcr9W2R29DP7WIVcZ2UtLh6EhM-3D> 

 



Andrew (Trust Wallet) 

May 12, 2020, 11:39:13 PM GMT+8 


Hi,

Thank you for contacting Trust Wallet Support Team.
I checked already and it has been merged.
https://u9455015.ct.sendgrid.net/ls/click?upn=WNbsy6qFrPkVfeApOza7cHuwqaF8GDbZ9Og2H8Dz8Hg0sY5KjDVZ-2B9i0H9u1LTjEnGZXM-2BiOiDJOpTD5z92y8A-3D-3DiiG3_U31jt5HgHBh7k3Grc5s4l5m-2FLVl2zVVdzSw9V2Pe4QiDGX95RiopDplvgSh16L-2BoLcc1Fc0ZDFvVhQLTxZVTZAvPd8L9PNWI-2Fg-2BHzLIdTX2dF2RNTpiQW5g5-2BeN89bJm6ce2wv-2Fwap61SrbogmzhxM259TdsGG7iT9HGru3eskDlCBMAfAoHShg7xo1b4GTIDalQK6ycFbLIC3Ot5ZsAIU6pHEiNHKJYElIlvm2Zehw6eqkDK3Jkje5-2FI-2F-2FGMS9Rh1dfQOI66lKMO9Z95mF-2FNosyl6Mnx5sSNqdu1x5Curs-3D


Stay Decentralized,
Trust Wallet Team Support

Visit our Help Center <https://u9455015.ct.sendgrid.net/ls/click?upn=WNbsy6qFrPkVfeApOza7cJoN9HMRTxEiePMAYYBeXgrjacgTTt6W0Ljk-2BLBVki8ZgeEXjpJQDtBvVWmkqPQyEw-3D-3D4u3o_U31jt5HgHBh7k3Grc5s4l5m-2FLVl2zVVdzSw9V2Pe4QiDGX95RiopDplvgSh16L-2BoLcc1Fc0ZDFvVhQLTxZVTZAvPd8L9PNWI-2Fg-2BHzLIdTX2dF2RNTpiQW5g5-2BeN89bJmdfKCbiMPyFKZr9el5La-2B0ZYJReJizQl-2FmsIQEpOnZRwFrwVS8SUbbfdPEtFoOaEnZhvO3e4rQlGxtQFjOl4YI4A7TNErQ7uH7E7M6N4NiaiORgLMLnwaRwOFbuiPoq3Pd7YR-2FWWJuw2aSRiNIK1aV0wCUKZphHkLf1WR9NA2dGg-3D>  for FAQs and Guides about Trust Wallet.



 



Echapeta 

May 12, 2020, 9:11:16 PM GMT+8 

Hello,

I just sent 0.08 ETH to 0xB46224E545c3F1Fa4D05f94465D13f777866a77B , at the transaction:

https://u9455015.ct.sendgrid.net/ls/click?upn=WNbsy6qFrPkVfeApOza7cKHZ69Qw1a8iakxIeN4-2BDUEbLfl7Iv5AnbpgC7Zbl80pMn0kgce7JIO8l6hYIHe-2BUZnjTYJfHcXlzwr2rPMzNSJwXmA6Qgx9UczvJ9yIKAlw8LVRQD5G3GbkGbTDhWijIA-3D-3DyaRO_U31jt5HgHBh7k3Grc5s4l5m-2FLVl2zVVdzSw9V2Pe4QiDGX95RiopDplvgSh16L-2BoLcc1Fc0ZDFvVhQLTxZVTZAvPd8L9PNWI-2Fg-2BHzLIdTX2dF2RNTpiQW5g5-2BeN89bJm1aHCIgndKi-2FIj0aXV-2FOf9y29QVw8U0oPS81yfH97IL1nxjVid64g8ABKkHy-2FEtN4ZlGJU1zYxUQ0afjAW5s90Sa4vcozpv8hG-2Fl327sTrZL4Bgw3px4jbiSHyg-2FuNpNiwm-2B5k7gFv-2FmdcTB95-2B-2F5Q-2BUvkcYdoViThS9yCgSfDf0-3D (https://u9455015.ct.sendgrid.net/ls/click?upn=WNbsy6qFrPkVfeApOza7cHocTBlrjKuRILayPiytPQTiZ2DbN7mb9fVQQrN3MIjmgjJeGWY3ubj4YcEBAx5HsvXI3awXMFFtCT2lSwY8pOcf7EuFbFx8URPDmHFKkZwE8nILkEWgIbydsE2BU-2FIMI8ZBiqXhRtofWUKDEOSrFpue0rromrJVfSZKSx244AsshZgJ-2FU4qCllWtTBitC-2B6YkcPJUl2IQZ3sOeBihUqyRvqSjLxYiCkQS9dslfkWwfOiHakUVjITin-2FczuN2CbZtlAphVkUTJo6L6tHRMA-2FUUwmHQc1D47J5UpOpgMHB9qOCVRWmc8X69l7NFqousTUJCL5yLIFh6r6LFqfP-2BNczUZZOn-2Fvhz2VJeFOgZGXGOuEMlAwZKtaI2b03nSSEWyg0R3D93pFCOtRmXcghBAtugCJXMgNDXbqvz5Gx9c76bXtjUf8xIEi2dOOHqodVr93Fl3D2UjmFimT2PWqapCvMhQHHW7CSA0wFqJd6eOEqICtDU7hJMejAbyy3v7w6Afws9B7eopzvOflM-2BqZHDGtbKcHRdoT84RWn-2BZGjFVAG8Pjsm4Q7sDB2swwHcIwUQmWUJl4j1XGceez7TFP-2FUP4gAzmIzh-2FcgfwZAlEeWS6wxNYzbKfsflP1zTJ-2FKlWmwY-2Bgw-3D-3D0N8u_U31jt5HgHBh7k3Grc5s4l5m-2FLVl2zVVdzSw9V2Pe4QiDGX95RiopDplvgSh16L-2BoLcc1Fc0ZDFvVhQLTxZVTZAvPd8L9PNWI-2Fg-2BHzLIdTX2dF2RNTpiQW5g5-2BeN89bJmyGzrFlmyY4ZNGisTl9RXcqYYLD8ZhfNjsfYo5hR-2Bu1X-2Bf-2Bo1wGOJglohNmZ76tiMPEyYhDBHL3ivAXj7rhVGUqCj8VE23gZTVRc6JTAIFqzQ0dypn56YfICYP-2Bx09CZ4mH3hu27pIBmIcKIzSl0RTwn7FQzHKvh50R5BhLaadls-3D

Please commit the logo update.

Thank You.

Eduardo G. Chapeta

CEO

Interwave Global

www.iw-global.com <https://u9455015.ct.sendgrid.net/ls/click?upn=IqcqsMFWPpg4kD2CiSOd2IH8MOSXRmGeDb6nhwg-2FaZamtoAUvHdZy8pJSutQxgDegts2_U31jt5HgHBh7k3Grc5s4l5m-2FLVl2zVVdzSw9V2Pe4QiDGX95RiopDplvgSh16L-2BoLcc1Fc0ZDFvVhQLTxZVTZAvPd8L9PNWI-2Fg-2BHzLIdTX2dF2RNTpiQW5g5-2BeN89bJmHntY7HJIO4m7wmZ2PhQDEyZ06-2BvyMfI5IC-2BeNLCSFrtrMGDQQwKX-2FBMDDgBa5FgTGhF7noDFYfupTpSqsKtFYUB3UKB-2Fl9iTMYpRoK3Ubmaobg-2FhOf7OXU2QFVMP-2F28fpnezmf7U4z8R0pIcI8ZhrTo3NfciHW2kIa9Pxy4H6g0-3D>

**Comment by kolya182** [comment]
@echapeta DO you want to update logo just for 0xe51601f59a610dac06868aa711a05e9a4e291256 ?. Could you make clean PR, otherway hard to reason what exactly you want to do.

**Comment by echapeta** [comment]
Hello,

 

I just want to update the asset:

 

0xae3274d06b7de181c4a6fbbb5f8bb945a15b5094 AFA Virtual Coin 

 

Thank You,

 

Eduardo G. Chapeta

CEO

Interwave Global

www.iw-global.com

**Comment by kolya182** [comment]
> Hello, I just want to update the asset: 0xae3274d06b7de181c4a6fbbb5f8bb945a15b5094 AFA Virtual Coin Thank You, Eduardo G. Chapeta CEO Interwave Global [www.iw-global.com](http://www.iw-global.com) From: mykola.eth <notifications@github.com> Sent: Tuesday, May 12, 2020 15:53 To: trustwallet/assets <assets@noreply.github.com> Cc: Eduardo Chapeta <echapeta@iw-global.com>; Mention <mention@noreply.github.com> Subject: Re: [trustwallet/assets] AFA Virtual Coin (#2067) @echapeta <https://u9455015.ct.sendgrid.net/ls/click?upn=WNbsy6qFrPkVfeApOza7cJmGEoI0n1pWGRzm4RPuzYt7bFtafMIX29-2BK-2Fp63eCZPlnzq_U31jt5HgHBh7k3Grc5s4l6svxhfBHIR5XMTR0WEh0zAHcrcwRxZtln7aPiSMGy4bzZn8kqfH2XZsNIVt4OBLMvVJ2VltY3TOY39aTg051QqSGZ1W32qLjQJ-2F7ooiMs-2BJQzYrx5n7HX3y5Gs5jPbLimy-2Bs3YA1pzxSw4J7SE8q2Xpt2bEbnGFa2Z-2BMzHIT-2B-2Blqv2wmLdDTcKgofjpK4oxo6jzCV1hK4XWm0Q4RebJIoELwVy56Kp5u99thKkrwdUCNm8XknAveA2wJN1-2BdERkRtw1tyPwats0frDcWPxZSDs-3D> DO you want to update logo just for 0xe51601f59a610dac06868aa711a05e9a4e291256 ?. Could you make clean PR, otherway hard to reason what exactly you want to do. — You are receiving this because you were mentioned. Reply to this email directly, view it on GitHub <https://u9455015.ct.sendgrid.net/ls/click?upn=WNbsy6qFrPkVfeApOza7cHuwqaF8GDbZ9Og2H8Dz8Hg0sY5KjDVZ-2B9i0H9u1LTjEonU0ZEPjWZ-2BNJTbYeTcMpmVwdmAUi-2Fc-2B2MuuYvnLKG8-3DA9RT_U31jt5HgHBh7k3Grc5s4l6svxhfBHIR5XMTR0WEh0zAHcrcwRxZtln7aPiSMGy4bzZn8kqfH2XZsNIVt4OBLMvVJ2VltY3TOY39aTg051QqSGZ1W32qLjQJ-2F7ooiMs-2BJ7bRm6JaQu3LFDi-2FEPZHX2CPvt2VewjcH3syoDLvKy1QKFxzPeYDCn7J6TIXmnJCQmL-2B8cJgd-2FosuLwCP7uQNwX-2BATZSLXuNfgVdZjjKrcgr030uJNysHMOrs73yAiJ9oNtY4tmtsLS8ayq-2FGysNEi0DPBYM86yZUu2C-2FFWg8VU0-3D> , or unsubscribe <https://u9455015.ct.sendgrid.net/ls/click?upn=WNbsy6qFrPkVfeApOza7cENuPPZIwT3F2KpumoK9EgOpRjzYiYPcaGd0MNDzgChlRc-2FD6ai2yMVbTh5varpD7QEehLYfRjU2N4gKKRegUVDq5Fhpwv5FB7zcIf3mDWAn5dfeZilJyzKgFKjzvYkxtQ-3D-3DGaXg_U31jt5HgHBh7k3Grc5s4l6svxhfBHIR5XMTR0WEh0zAHcrcwRxZtln7aPiSMGy4bzZn8kqfH2XZsNIVt4OBLMvVJ2VltY3TOY39aTg051QqSGZ1W32qLjQJ-2F7ooiMs-2BJ8oQptdQjHLhflWIWQ8UUSFsQTc7wc-2BrHCPR1y2fzMZQINtuXd-2FJJ6qxENT6UZw1bJIOxumaUArNaZFFLxFZ1QxOrMBb1TTHWfV5p-2F5dusKShh654jzEP8Vw9Zut-2BrtuLtDG000vjSZHqyS6BTfczfkfuz3HmONnmxgNdM-2BL3qw0-3D> . <https://u9455015.ct.sendgrid.net/ls/click?upn=WNbsy6qFrPkVfeApOza7cENuPPZIwT3F2KpumoK9EgPxTAJAUqYX1jnB4recrqhelIcmrp43cgYtr-2FLDB0GVZRQ4-2B8sTBXjkImuL0Jvzmqrqvp026V2-2FXq-2Fnq7-2BLf5l2n7mJqjFOKTqTHR65Jm3w1-2FdJ8JFdInIMLlTRYDJlma-2F5yx0A57fSaSeLsNq5tgY5sLkZs8V-2FyqByZSgxC1h-2Bae-2B-2BeLyGV13JhSDwn5rZeWY-3D7qLS_U31jt5HgHBh7k3Grc5s4l6svxhfBHIR5XMTR0WEh0zAHcrcwRxZtln7aPiSMGy4bzZn8kqfH2XZsNIVt4OBLMvVJ2VltY3TOY39aTg051QqSGZ1W32qLjQJ-2F7ooiMs-2BJTlCZcgjndyIcRXRsz9dyKBf-2FrGRu5cL03I98iAQVkQ7Sn81gnSifQF4P0u0N7Mf5cnn5nnJS5U89tXw8oEsnPaPBvywCbtAGtqHqa5AlxTDSDhpuv-2F1xeuSy7pMiQjHHJ5YpRM-2FoXJTvZlLFTf9Lb8R-2BAhS1-2FX-2Feg5R85cIP34Q-3D>

Image has been added. For future submission i can recommend to update your fork, to make PR looks clean, or if you want even simpler solution, just remove your fork and fork again.

**Comment by kolya182** [comment]
Added

**Comment by zachzwei** [comment]
Hi @kolya182 user saying that the image for this one is still not yet added.

**Comment by echapeta** [comment]
Hello,

 

Yes.

Was shown for a while and after that disappeared.

 

 

Thank You

 

 

Eduardo G. Chapeta

CEO

Interwave Global

www.iw-global.com

**Pull request closed without merging**
