### PR TITLE
Somax logo and info

### PR DESCRIPTION
**Pull request by somax32**

### CODE REVIEW

**Comment by somax32** [comment]
What is the problem ? Will the trust wallet logo be added?

**Comment by cryptomanz** [comment]
can you please add links to your PR?
example:https://developer.trustwallet.com/assets/repository_details

**Comment by somax32** [comment]
> can you please add links to your PR? example:https://developer.trustwallet.com/assets/repository_details

Links added

**Comment by ramsty** [comment]
Hi!
Could you answer some questions?
• What is the purpose of this token? How will it benefit Trust Wallet users?
• How is the token being distributed? Are you conducting an airdrop?
• Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?
• Is the token listed on a centralized/decentralized exchange?
• Is a Smart Contract audit completed? Where can we find this information?

**Comment by somax32** [comment]
Hello,

• What is the purpose of this token? How will it benefit Trust Wallet users?
Somax Token is a DeFi cryptocurrency, Two main functions happen during a trade. Trust Wallet users will be able to store SMX tokens and trade on DEXs.

• How are tokens distributed? Are you conducting an airdrop?
We do events and giveaways

• Did you sell tokens at Initial Coin Offering (ICO) or pre-sell tokens?
No. Not pre-sold

• Is the token listed on a centralized/decentralized exchange?
We have listed on PancakeSwap at 1th October

• Check Smart Contract Completed? Where can we find this information?
Yes, our Smart Contract has been audited by TechAudit. Here is the document file:
https://somax.finance/audits/TECHAUDIT_SOMAX.pdf

**Pull request merged**
