### PR TITLE
Updated Logo

### PR DESCRIPTION
**Pull request by SAFEBTCOFFICIAL**
Hi guys can you get the logo updated 

Thanks

### CODE REVIEW

**Comment by SAFEBTCOFFICIAL** [comment]
you want another $500 to update the PNG?

**Comment by SAFEBTCOFFICIAL** [comment]
We have paid 2 BNB which is equivalent to more than 500 TWT

Can you update the Logo ASAP Please?

**Comment by SAFEBTCOFFICIAL** [comment]
What is needed to get price reflected on TrustWallet for holders who are holding our coin

**Comment by catenocrypt** [comment]
We can add it if it is reported by coinmarketcap (or coingecko).

**Pull request merged**
