### PR TITLE
Cygnity Token logo Update

### PR DESCRIPTION
**Pull request by Cygnitycom**
add logo

### CODE REVIEW

**Comment by Cygnitycom** [comment]
Hi,
checks have failed, what do we have to do?
start all over again?
Thanks

**Comment by coffee-converter** [comment]
> Hi,
> checks have failed, what do we have to do?
> start all over again?
> Thanks

The contract address needs to be checksummed.

**Comment by Cygnitycom** [comment]
> 
> 
> > Hi,
> > checks have failed, what do we have to do?
> > start all over again?
> > Thanks
> 
> The contract address needs to be checksummed.

I already checksummed contract address, but it still failed.

**Comment by zachzwei** [comment]
Please update your fork first before you submit a PR.
Make sure that the folder is a checksum address.

**Pull request closed without merging**
