### PR TITLE
Add NCoin (BEP20)

### PR DESCRIPTION
**Pull request by erience**
Adding info for BEP20 token 'NCoin'.

### CODE REVIEW

**Comment by erience** [comment]
Audit Report: https://natronz.com/assets/files/AuditReportOfNCoin.pdf

**Comment by Cryptocool1** [comment]
• What is the purpose of this token? How will it benefit Trust Wallet users?
 • How is the token being distributed? Are you conducting an airdrop?
 • Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?
 • Is the token listed on a centralized/decentralized exchange?
 • Is a Smart Contract audit completed? Where can we find this information?

**Comment by erience** [comment]
• What is the purpose of this token? How will it benefit Trust Wallet users? ---- It is a Defi Token and Trust Wallet being the primary non custodial wallet. User will prefer to use the Token insider the Trust wallet
• How is the token being distributed? Are you conducting an airdrop? --- No Airdrop has been done
• Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale? --- Yes, presale has been done, 30% of the supply has been sold via Presale
• Is the token listed on a centralized/decentralized exchange? --- Right now, it's listed on Pancakeswap and we are in talks with some CEX for listing, once our token is updated on Trust wallet, CMC, CG

**Comment by Cryptocool1** [comment]
Are you listed on CoinMarketCap?

**Comment by erience** [comment]
No Mam, we are not listed in CoinMarketCap yet. We just have started procedure for applying everywhere as we have generated significant user base for our tokens.

**Comment by erience** [comment]
We have listed ourselves first on BSCSCAN, now Trust wallet. Once Trust wallet is done, next step is Coin Gecko

**Comment by Cryptocool1** [comment]
We require CoinMarketCap listing. Please see our requirements here: https://developer.trustwallet.com/listing-new-assets/requirements

**Comment by erience** [comment]
we were not aware of the same. Is this the recent change in guidelines ?

**Comment by Cryptocool1** [comment]
No, this requirement is not new .

**Comment by erience** [comment]
Okay, thanks for your help. We are applying to CMC and then shall get back to you

**Comment by cryptomanz1** [comment]
Feel free to create new PR once you are listed on CMC. Make sure to mention this PR so the fee can be reused.

**Comment by naruponk** [comment]
Hi, we have been listed on CMC. Could you please proceed?

**Pull request closed without merging**
