### PR TITLE
Add IDRX Token (POLYGON, BEP20)

### PR DESCRIPTION
**Pull request by IfanWijaya**
Note: 
- We have previously created the pull request with ID https://github.com/trustwallet/assets/pull/27103 and we have made payment of 500 TWT with this txid: FA733BB7876A02A2D2E7533EBEDC968F1543ECF784B672145327EF5E7937FA2C
- We have met the minimum holder & transactions criteria on the Polygon network
https://polygonscan.com/token/0x649a2DA7B28E0D54c13D5eFf95d3A660652742cC

### CODE REVIEW

**Comment by Cryptocool1** [comment]
Paid

**Comment by Cryptocool1** [comment]
Paid

**Comment by Cryptocool1** [comment]
• What is the purpose of this token? How will it benefit Trust Wallet users?
 • How is the token being distributed? Are you conducting an airdrop?
 • Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?
 • Is the token listed on a centralized/decentralized exchange?
 • Is a Smart Contract audit completed? Where can we find this information?

**Comment by IfanWijaya** [comment]
1. IDRX is a stablecoin backed by the Indonesian Rupiah fiat currency. The benefit for users is to store value in Indonesia's stable asset. Additionally, we are also building an ecosystem that utilizes IDRX, providing numerous options for using IDRX in other financial instruments, such as payments, crowdfunding, deposits, and more.
2. We're not conducting an airdrop. Since IDRX is a stablecoin backed by the Indonesian Rupiah fiat currency, we will only distribute tokens to users if we receive Rupiah into our account. Once we receive fiat from the user, we will distribute IDRX to the user. Similarly, when a user wants to redeem IDRX, they will perform a burn available on our platform. After IDRX is burned, we will send fiat to the user's bank account.
3. No, we didn't do any ICO or presale.
4. Yes. CEX = Indodax, DEX = Uniswap and Pancakeswap.
5. Yes. An audit was completed by CertiK. https://skynet.certik.com/projects/idrx

**Comment by cryptomanz1** [comment]
please update your branch with the recent master

**Comment by IfanWijaya** [comment]
@cryptomanz1 done.

**Pull request merged**
