### PR TITLE
Add Berryswap Logo and Info

### PR DESCRIPTION
**Pull request by berryswap**

### CODE REVIEW

**Comment by catenocrypt** [comment]
Correction needed:
❌  Contract is not in checksum format, should be 0x8626F099434d9A7E603B8f0273880209eaBfc1c5 (not 0x8626f099434d9a7e603b8f0273880209eabfc1c5). Please rename it. You may need to rename to a temp name first, then to the checksum format, because lowercase-uppercase-only renames are often ignored by the Git client or the filesystem.

**Comment by berryswap** [comment]
Hi, I tried paying 250TWT to the wallet address contained in this mail and I was given a notification that the recipient address is wrong.Kindly review and send a right TWT wallet.Best regards.Berry Team.On 23 Apr 2021 13:59, "merge-fee-bot[bot]" ***@***.***> wrote:
@berryswap, kind reminder:  please pay fee:  250 TWT  with the memo 6725  to the address bnb1tqq9llyr3dyjd559dha6z5r5etk3qfwk07m098.
Alternatively, 2 BNB is also accepted (same memo & address).
QR code: Trust | other wallet
See the Pull Request Fee FAQ.

**Comment by berryswap** [comment]
Payment of 250TWT SUCCESSFULLY MADE.SEE TRANSACTION HASH ID BELOW:https://explorer.binance.org/tx/7442C29C0BECD0633E4B4573F4BF40F1BB98160EA989D87B579385A8B341A0F6BEST REGARDS.BERRY TEAM.On 23 Apr 2021 17:24, ***@***.*** wrote:Hi, I tried paying 250TWT to the wallet address contained in this mail and I was given a notification that the recipient address is wrong.Kindly review and send a right TWT wallet.Best regards.Berry Team.On 23 Apr 2021 13:59, "merge-fee-bot[bot]" ***@***.***> wrote:
@berryswap, kind reminder:  please pay fee:  250 TWT  with the memo 6725  to the address bnb1tqq9llyr3dyjd559dha6z5r5etk3qfwk07m098.
Alternatively, 2 BNB is also accepted (same memo & address).
QR code: Trust | other wallet
See the Pull Request Fee FAQ.

**Comment by Cryptocool1** [comment]
Hello,
Correction needed:
❌ Contract is not in checksum format, should be 0x8626F099434d9A7E603B8f0273880209eaBfc1c5 (not 0x8626f099434d9a7e603b8f0273880209eabfc1c5). Please rename it.

**Comment by Cryptocool1** [comment]
According to our requirements you should  capitalize your "symbol"

**Comment by Cryptocool1** [comment]
Hello,
Can you capitalize all letters in your symbol?

**Comment by catenocrypt** [comment]
Renamed to checksum format

**Comment by berryswap** [comment]
Hi, I tried paying 250TWT to the wallet address contained in this mail and I was given a notification that the recipient address is wrong.Kindly review and send a right TWT wallet.Best regards.Berry Team.On 23 Apr 2021 13:59, "merge-fee-bot[bot]" ***@***.***> wrote:
@berryswap, kind reminder:  please pay fee:  250 TWT  with the memo 6725  to the address bnb1tqq9llyr3dyjd559dha6z5r5etk3qfwk07m098.
Alternatively, 2 BNB is also accepted (same memo & address).
QR code: Trust | other wallet
See the Pull Request Fee FAQ.

**Pull request merged**
