### PR TITLE
Asset Tezos: Added StakeNow Staking Validator

### PR DESCRIPTION
**Pull request by jdsika**
This PR is being closed due to inactivity. If you wish to continue, please have us reopen the PR before sending your payment, or just create a new one.
Do NOT send payments for closed PR, as the fee may by lost!
  (48 vs. 48 hrs)

### CODE REVIEW

**Comment by jdsika** [comment]
Hi @Cryptocool1 , I am pinging you as of the number of your contributions to this repository. The merge bot gives me the instruction to remove the changes I have made but I would like to know a way on how to incorporate them as the exisiting information are outdated. I would appreciate your help here :)

**Comment by dansan566** [comment]
Hey @Cryptocool1, somehow we get removed from the Tezos validator list and we just found out about it. Here is the old PR for proof: https://github.com/trustwallet/assets/pull/578 - Why do we have to pay again?

**Comment by Cryptocool1** [comment]
> Hi @Cryptocool1 , I am pinging you as of the number of your contributions to this repository. The merge bot gives me the instruction to remove the changes I have made but I would like to know a way on how to incorporate them as the exisiting information are outdated. I would appreciate your help here :)

submission looks good, awaiting for fee payment)

**Comment by jdsika** [comment]
@Cryptocool1 can you have a look at the commit I have reverted and tell me on how to change the general information for Tezos as they are outdated?

**Pull request closed without merging**
