### PR TITLE
add realio.fund RIO erc20 token

### PR DESCRIPTION
**Pull request by aaron-realio**
Hello, we would like to add RIO token. RIO token on both Stellar and Ethereum chains. We recently introduced erc20 token and ability for users to migrate from Stellar token to Ethereum. While we don't yet have 500 holders on Ethereum our Stellar Token has more holders and transactions. https://stellar.expert/explorer/public/asset/RIO-GBNLJIYH34UWO5YZFA3A3HD3N76R6DOI33N4JONUOHEEYZYCAYTEJ5AK-1?filter=all&order=desc

Please advise if this is appropriate for listing. We will kindly send donation in BNB for listing.

### CODE REVIEW

**Comment by zachzwei** [comment]
Please provide more details about this project.
https://community.trustwallet.com/t/how-to-submit-a-token-logo/3863#how-to-get-approved

You can follow this format when adding an info.json file:
```
 {
   "name":"Bitcoin",
   "website":"https://bitcoin.org",
   "source_code":"https://github.com/bitcoin",
   "white_paper":"https://bitcoin.org/bitcoin.pdf",
   "short_description":"Bitcoin is a cryptocurrency and worldwide payment system.",
   "explorer":"https://blockchain.info",
   "research":"https://research.binance.com/en/projects/bitcoin"
}

**Comment by aaron-realio** [comment]
Added `info.json` as requested.

**Comment by catenocrypt** [comment]
As per our policy, brand new tokens are not included, there is a minimum requirement of 500 holder addresses and 1000 transactions, in order to filter out scam tokens.
See the criteria at (mentioned in the first message by the bot): https://community.trustwallet.com/t/how-to-submit-a-token-logo/3863#how-to-get-approved
This token has no real usage yet (51). Putting PR on hold. Please come back to us when all criteria are met.

https://etherscan.io/token/0xf21661D0D1d76d3ECb8e1B9F1c923DBfffAe4097

**Comment by aaron-realio** [comment]
> As per our policy, brand new tokens are not included, there is a minimum requirement of 500 holder addresses and 1000 transactions, in order to filter out scam tokens.
> See the criteria at (mentioned in the first message by the bot): https://community.trustwallet.com/t/how-to-submit-a-token-logo/3863#how-to-get-approved
> This token has no real usage yet (51). Putting PR on hold. Please come back to us when all criteria are met.
> 
> https://etherscan.io/token/0xf21661D0D1d76d3ECb8e1B9F1c923DBfffAe4097

As I said RIO is a stellar token that we recently also deployed to Ethereum. We have many more holders on Stellar, we are listed on OkEX (https://www.okex.com/markets/spot?product=rio_usdt), StellarTerm (https://stellarterm.com/exchange/RIO-GBNLJIYH34UWO5YZFA3A3HD3N76R6DOI33N4JONUOHEEYZYCAYTEJ5AK/XLM-native) and CoinMarketCap (https://coinmarketcap.com/currencies/realio-network/).

**Comment by catenocrypt** [comment]
Thanks for clarification.  Checking now.

**Pull request merged**
