### PR TITLE
Add FoxGirl (BEP20)

### PR DESCRIPTION
**Pull request by zman12344**
Adding info for BEP20 token 'FoxGirl'.

PR created by <a href="https://assets.trustwallet.com">TW Assets Management</a>

### CODE REVIEW

**Comment by zman12344** [comment]
this is a v3 version so the holders and transactions are accurate.

**Comment by cryptomanz** [comment]
• What is the purpose of this token? How will it benefit Trust Wallet users?
 • How is the token being distributed? Are you conducting an airdrop?
 • Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?
 • Is the token listed on a centralized/decentralized exchange?
 • Is a Smart Contract audit completed? Where can we find this information?

**Comment by zman12344** [comment]
What is the purpose of this token? How will it benefit Trust Wallet users?
For foxgirl we also have a coin listings website foxgirl.com where people
can apply and be posted as well as being voted on, foxgirl ecosystem is
going to be expanding to not only benefit trust wallet users but also
people who want to launch there own token.

• How is the token being distributed? Are you conducting an airdrop? The
token originally started off as a stealth launch a month or two ago and
since then we have taken new heights and new all time highs currently
sitting over a 1.5 million dollar marketcap, this contract is V3 so the
original holders were airdropped explain on the last question why we made v3

• Did you sold the tokens at an Initial Coin Offering (ICO) or a token
presale?
The coin started as strictly a fairlaunch so it could be as fair as
possible

• Is the token listed on a centralized/decentralized exchange?
Currently we applied to Bitmart but we are waiting to hear back from them

 Is a Smart Contract audit completed? Where can we find this information?
Currently there is no smart contract audit completed it is in process of
being completed by Certik  which can be found here
https://www.certik.com/projects/fox-girl
We had switched to v3 to change some things in the contract that certik did
not like to improve our ecosystem.

**Comment by zman12344** [comment]
also an addition to the above we also have our Liquidity Lock located here: https://dxsale.app/app/v3/dxlockview?id=0&add=0xec7D683353DAe73FE7ec79f9d71324A35c3286F9&type=lplock&chain=BSC

**Comment by ramsty** [comment]
Awaiting for smart contract audit. On hold for now.

**Comment by zman12344** [comment]
Is there anyway to bypass that audit for now.  Since certik varies. Could
be a month or so

**Comment by zman12344** [comment]
> Awaiting for smart contract audit. On hold for now.

i just got confirmation i do have another audit coming back today. 

in addition to that we got the free audit from this company
[Techrate.pdf](https://github.com/trustwallet/assets/files/7741164/Techrate.pdf)

**Comment by Cryptocool1** [comment]
> > Awaiting for smart contract audit. On hold for now.
> 
> i just got confirmation i do have another audit coming back today.
> 
> in addition to that we got the free audit from this company [Techrate.pdf](https://github.com/trustwallet/assets/files/7741164/Techrate.pdf)

Awaiting for full co tract audit.

**Comment by zman12344** [comment]
> > > Awaiting for smart contract audit. On hold for now.
> > 
> > 
> > i just got confirmation i do have another audit coming back today.
> > in addition to that we got the free audit from this company [Techrate.pdf](https://github.com/trustwallet/assets/files/7741164/Techrate.pdf)
> 
> Awaiting for full contract audit.

here is the paid full contract audit that was coming back today      
https://github.com/AuditRateTech/Smart-Contract-Audits/blob/main/FoxGirl_0x599beec263FA6eA35055011967597B259FC012A4.pdf

**Comment by zman12344** [comment]
> 

did you recieve our smart contract audit report <3

**Pull request merged**
