### PR TITLE
Added logo and metadata for SHIB

### PR DESCRIPTION
**Pull request by fer662**

### CODE REVIEW

**Comment by catenocrypt** [comment]
As per our policy, brand new tokens are not included, there is a minimum requirement of 100 holder addresses and 500 transactions, in order to filter out scam tokens.
See the criteria at (mentioned in the first message by the bot): https://community.trustwallet.com/t/how-to-submit-a-token-logo/3863#how-to-get-approved

The second token (Shiba) is OK, but the first (Doge Killer, 0x27C70Cd1946795B66be9d954418546998b546634) has only minimal usage (3/3).  https://etherscan.io/token/0x27C70Cd1946795B66be9d954418546998b546634

Should we remove Doge Killer, and focus on Shiba, or, reject whole PR?

**Comment by fer662** [comment]
Ok I've updated the PR and removed the WIP token. I guess we'll have to submit it separately and pay again sniff.

**Comment by fer662** [comment]
image

**Comment by catenocrypt** [comment]
image

**Pull request merged**
