### PR TITLE
New BIRBv3 contract after bug

### PR DESCRIPTION
**Pull request by crypt0jan**
- I set the previous contract (`0x3CF33Ff134c0e00A2664f148A4232adeA1515C6f`, contains bugs) to status `abandoned`
- I created a new asset (`0x88888888fc33e4ecba8958c0c2ad361089e19885`)
- I moved the logo over to the new assets
- I updated the info file of the new assets to reflect the token address change

### CODE REVIEW

**Comment by crypt0jan** [comment]
@cryptomanz Anything else that needs to be done? All checks have passed.

**Comment by cryptomanz** [comment]
- We have already done the merger of the new contract #21401 (BIRB V2)
- How we can fix this bug?

**Comment by crypt0jan** [comment]
The v2 contract had a bug in the sell tax which resulted in a loop. We have published this new contract a few hours later and migrated all the tokens back to the users. 

More info: https://twitter.com/BirbDefi/status/1545526765338107905

**Comment by cryptomanz** [comment]
#21443
#21444

**Pull request closed without merging**
