### PR TITLE
KEYFI logos and infos

### PR DESCRIPTION
**Pull request by designhorf**

### CODE REVIEW

**Comment by catenocrypt** [comment]
As per our policy, brand new tokens are not included, there is a minimum requirement of 2500 holder addresses and 5000 transactions, in order to filter out scam tokens.
See the criteria at (mentioned in the first message by the bot): https://community.trustwallet.com/t/how-to-submit-a-token-logo/3863).
This token has low usage yet (257 holders). Closing PR for now. Please come back to us when all criteria are met.  Multi-chain and staking tokens may get special treatment, let us know if this is the case. 

https://etherscan.io/token/0xB8647e90C0645152Fccf4d9AbB6B59Eb4AA99052

**Comment by realvincentle** [comment]
Adam, this is Vinny Le, new product manager and partner at KeyFi (https://keyfi.com/team/), and am in a better position to make a business case for updating our TrustWallet logo and info per this pull request. All we request is:

- Our logo in the right format
- Update our ETH, BSC addresses, short description, etc. via info file

We respect the due diligence methodology that TrustWallet needs to uphold, and understand the goal is to prevent illegitimate tokens from getting through. Even more so after this past month where many questionable tokens have been created en masse, many without use cases, many with no audits, and some outright scams. We hope to bring a real product with lots of utility to the space.

I hope we have some flexibility to clarify our "risk profile" to you, and give you some news since our last communication. Here's why I think we're worth considering:

1. KEYFI token launched on Binance Smart Chain, so now we are multi-chain.
a. Press release: https://finance.yahoo.com/news/keyfi-launch-native-token-binance-150000764.html
b. Users can find us on PancakeSwap: https://exchange.pancakeswap.finance/#/swap?inputCurrency=0x4b6000f9163de2e3f0a01ec37e06e1469dbbce9d
c. As well as ApeSwap: https://info.apeswap.finance/token/0x4b6000f9163de2e3f0a01ec37e06e1469dbbce9d / https://blockchain.news/news/keyfi-announces-native-token-listing-on-apeswap-dex

2. New listings
a. CMC: https://coinmarketcap.com/currencies/keyfi/
b. CoinGecko: https://www.coingecko.com/en/coins/keyfi

3. We just passed our second Hacken audit with a top score: https://hacken.io/audits/

image
image 2

4. We're not listed on Binance yet, but we do have a relationship with them as they supported us in February with an airdrop: https://www.binance.com/en/support/announcement/a976b8105e0c48179b29c1757f9a623f

5. Again, a real product and use case. We have a fully functional platform where users are staking, swapping, and voting. And right now we're actually working on a second, Pro platform which we will be launching soon. It will include a cool DeFi strategy manager tool that will allow users to customize their own yield strategies. https://app.keyfi.com/dashboard

Thanks so much for your work and flexibility. Our community and users really like using TrustWallet and with the improvements in this pull request, we hope they can use it even more seamlessly than they are now.

**Comment by designhorf** [comment]
Adam, this is Vinny Le, new product manager and partner at KeyFi (https://keyfi.com/team/), and am in a better position to make a business case for updating our TrustWallet logo and info per this pull request. All we request is:
- Our logo in the right format
- Update our ETH, BSC addresses, short description, etc. via info file
- We respect the due diligence methodology that TrustWallet needs to uphold, and understand the goal is to prevent illegitimate tokens from getting through. Even more so after this past month where many questionable tokens have been created en masse, many without use cases, many with no audits, and some outright scams. We hope to bring a real product with lots of utility to the space.
- I hope we have some flexibility to clarify our "risk profile" to you, and give you some news since our last communication. Here's why I think we're worth considering:
- 1. KEYFI token launched on Binance Smart Chain, so now we are multi-chain.
- a. Press release: https://finance.yahoo.com/news/keyfi-launch-native-token-binance-150000764.html
- b. Users can find us on PancakeSwap: https://exchange.pancakeswap.finance/#/swap?inputCurrency=0x4b6000f9163de2e3f0a01ec37e06e1469dbbce9d
- c. As well as ApeSwap: https://info.apeswap.finance/token/0x4b6000f9163de2e3f0a01ec37e06e1469dbbce9d / https://blockchain.news/news/keyfi-announces-native-token-listing-on-apeswap-dex
- 2. New listings
- a. CMC: https://coinmarketcap.com/currencies/keyfi/
- b. CoinGecko: https://www.coingecko.com/en/coins/keyfi
- 3. We just passed our second Hacken audit with a top score: https://hacken.io/audits/
- image
- image 2
- 4. We're not listed on Binance yet, but we do have a relationship with them as they supported us in February with an airdrop: https://www.binance.com/en/support/announcement/a976b8105e0c48179b29c1757f9a623f
- 5. Again, a real product and use case. We have a fully functional platform where users are staking, swapping, and voting. And right now we're actually working on a second, Pro platform which we will be launching soon. It will include a cool DeFi strategy manager tool that will allow users to customize their own yield strategies. https://app.keyfi.com/dashboard
- Thanks so much for your work and flexibility. Our community and users really like using TrustWallet and with the improvements in this pull request, we hope they can use it even more seamlessly than they are now.

**Comment by designhorf** [comment]
We also understand that our holder count is low. The reason is that our strategy has been to introduce the project through our Binance airdrop (https://www.binance.com/en/support/announcement/a976b8105e0c48179b29c1757f9a623f), then build a product (which we completed), and then do marketing to get more holders and exposure.
Our community has voted for a marketing (https://vote.keyfi.com/#/keyfi-app.eth/proposal/QmUkpJAuFA31f4MSosdv8KN2MawHtbzarDa8Bped61kxSj), which will start next week, so holders will increase. 
Many other projects do this in reverse - no platform, marketing first, gain as many holders as possible, and then (eventually, maybe) build a product. 
We prioritized developing a real product first, with a real use case and user traction.

**Comment by realvincentle** [comment]
hi all, the 2 BNB fee is on the way to you: https://explorer.binance.org/tx/2817C92EFDE9C1B7A4C6259378267DF42987865DD30621ECE17DE271EDC4FB74

**Comment by designhorf** [comment]
@Cryptocool1  Fee is payed https://explorer.binance.org/tx/2817C92EFDE9C1B7A4C6259378267DF42987865DD30621ECE17DE271EDC4FB74

**Comment by catenocrypt** [comment]
Marking paid; 2 BNB ; https://explorer.binance.org/tx/2817C92EFDE9C1B7A4C6259378267DF42987865DD30621ECE17DE271EDC4FB74

**Pull request merged**
