### PR TITLE
[Suspicious] Upload Logo BFY (bfy.digital)

### PR DESCRIPTION
**Pull request by bond2022**

### CODE REVIEW

**Comment by bond2022** [comment]
I have paid you
https://explorer.binance.org/tx/A6195784927264D3AFCEB34478FDDC9145E25E0B23716FFCF1F2C7D10B7859F2?fbclid=IwAR29IiCySUszLfCIFA8u5Sht2BPYee_QY0yfShITQ380CCtR9PMOevAR8LU

**Comment by Iamdeadlyz** [comment]
Notes:
- No social media presence
- Website is showing coming soon without sufficient information about the project
- Airdropped to users just to meet the requirements

**Comment by bond2022** [comment]
My website content has been updated. Please check for me: https://bfy.digital/

**Comment by Iamdeadlyz** [comment]
Additional notes:
- Articles at the bottom pointed out to a 2018 date but cannot be checked.
- About us and other tabs are not working

**Comment by bond2022** [comment]
Due to the website completion process. Website content is still not stable.
Please check back for me

Vào Th 5, 22 thg 10, 2020 vào lúc 09:16 Ian E <notifications@github.com>
đã viết:

**Comment by bond2022** [comment]
Due to the website completion process. Website content is still not stable. Please check back for me.
Please check for me: https://bfy.digital/
Thank.

**Comment by bond2022** [comment]
Please put my logo on the trust wallet. thank

**Comment by Iamdeadlyz** [comment]
In accordance with our [disclaimer](https://github.com/trustwallet/assets#disclaimer), your PR is denied due to the following reason:
- Insufficient project information with similarity to an old project (more likely a template and copy-pasted)
image

- Tried to hide the false information
> * Articles at the bottom pointed out to a 2018 date but cannot be checked.

- No social media presence

**Comment by bond2022** [comment]
My information is completely clean. Admin has completely wrong evaluation of my website. Please help me admin. Thank you.

**Pull request closed without merging**
