### PR TITLE
Add The Last McAfee token logo

### PR DESCRIPTION
**Pull request by quickomofficial**
we submit the logo for the last mcafee token, please help process.

### CODE REVIEW

**Comment by phuongbwf** [comment]
we just add 1 token: 0x3081523203F2AEfceaBd4b9B9eDbCa05A038Db67

why the fee is 3 BNB?

**Review by Hbutlercapone — APPROVED** [review]

**Comment by Cryptocool1** [comment]
As per our policy, brand new tokens are not included, there is a minimum requirement of 2500 holder addresses and 5000 transactions, in order to filter out scam tokens.
See the criteria at (mentioned in the first message by the bot): https://community.trustwallet.com/t/how-to-submit-a-token-logo/3863).

**Comment by phuongbwf** [comment]
@Cryptocool1 our token ( The Last McAfee token, https://bscscan.com/token/0x3081523203f2aefceabd4b9b9edbca05a038db67) has 
3,069 holders and 14,415 transactions, please check on bscScan. I attached the screenshot here as well. We only add The Last McAfee token.

Screen Shot 2021-06-27 at 16 01 59

**Comment by Cryptocool1** [comment]
So, why are you adding FAN8?

**Comment by Cryptocool1** [comment]
Is it your token?

**Comment by phuongbwf** [comment]
only The last McAfee token pleas. Please ignore FAN8. I will make a separated one for FAN8 later. don't know why the github push FAN8 as well.

**Comment by phuongbwf** [comment]
@Cryptocool1 could you please help? anything I can do?

**Comment by phuongbwf** [comment]
hello guys @Hbutlercapone @Cryptocool1 we need to have The Last McAfee token soon. Our community is asking for it, Please remove FAN8 out the this ticket. Thanks.

**Comment by Cryptocool1** [comment]
Can you create another PR with only MCAFEE?

**Comment by Cryptocool1** [comment]
You don’t need to pay one more time

**Review by phuongbwf — COMMENTED** [review]
I resubmit with only McAfee token please help

**Comment by phuongbwf** [comment]
> Can you create another PR with only MCAFEE?

I did it but it says file is not allow to upload. Can you help to remove FAN8?

**Review by phuongbwf — COMMENTED** [review]
I removed fan8 info..json

**Comment by phuongbwf** [comment]
@Cryptocool1 can you please help? I try to remove FAN8 and upload the new PR but the message show failed.

**Comment by Cryptocool1** [comment]
will fix it

**Comment by Cryptocool1** [comment]
fixed

**Comment by phuongbwf** [comment]
tks you, when will the token logo appear on trust wallet?

**Comment by Cryptocool1** [comment]
> tks you, when will the token logo appear on trust wallet?

you need to change your logo.
we require an image with full width/height. it should be without spacing from the sides
Снимок экрана 2021-06-27 в 13 43 51

**Comment by phuongbwf** [comment]
logo
@Cryptocool1 I update the new logo.png please help check. thank you

**Comment by phuongbwf** [comment]
@Cryptocool1 can you check the new logo file? Please help. we're in urgent case. Thanks.

**Comment by phuongbwf** [comment]
thank you, so it will appear on trust wallet soon right?

**Pull request merged**
