### PR TITLE
Add GymRocket Logo and Info

### PR DESCRIPTION
**Pull request by GymRocketCrypto**
Initial commit for GymRocket (GAINZ)

### CODE REVIEW

**Comment by GymRocketCrypto** [comment]
Fee accidently paid to memo 8441, can this be reconciled?

**Comment by GymRocketCrypto** [comment]
additional fee send to correct memo, however is it possible to recover the fee paid to incorrect memo?

**Comment by Cryptocool1** [comment]
> additional fee send to correct memo, however is it possible to recover the fee paid to incorrect memo?

I don't think so

**Comment by GymRocketCrypto** [comment]
if you could check, it would be really appreciated!

**Comment by GymRocketCrypto** [comment]
this is the address it was sent from bnb1hj0fyx63mczc7vk7pyzg500dq849quy0ahh953

**Comment by GymRocketCrypto** [comment]
Is there anything further required?

**Comment by GymRocketCrypto** [comment]
@Cryptocool1 Is there anything further required?

**Comment by catenocrypt** [comment]
We could have considered the fee paid to wrong PR to this one, but a refund is not possible unfortunately.
What's with #8441, is that PR related to you, or not at all?

**Comment by GymRocketCrypto** [comment]
> 
> 
> We could have considered the fee paid to wrong PR to this one, but a refund is not possible unfortunately.
> What's with #8441, is that PR related to you, or not at all?

My colleague was looking at another ticket, and accidently copied the wrong memo code unfortunately. It would be appreicated if you could, just appealing to your good nature. Mistakes happen and unfortunately this is one which impacts the project

**Comment by GymRocketCrypto** [comment]
@catenocrypt My colleague was looking at another ticket, and accidently copied the wrong memo code unfortunately. It would be appreicated if you could, just appealing to your good nature. Mistakes happen and unfortunately this is one which impacts the project

**Pull request merged**
