### PR TITLE
Add Gold USDT (BEP20)

### PR DESCRIPTION
**Pull request by Suibansos**
Adding info for BEP20 token 'Gold USDT'.

PR created by <a href="https://assets.trustwallet.com">TW Assets Management</a>

### CODE REVIEW

**Comment by Suibansos** [comment]
Saya sudah membayar dengan 500 TWT
Ini hash saya:   0x5229eeca9591116c4e95c 02d34a5  15a5054107888a35477a9e
9f9cf634  baead4


[image: gambar.png]

**Comment by Suibansos** [comment]
We have paid a fee of 500 TWT, but why until now our token logo and price
have not appeared in the Trut Wallet?

**Comment by Cryptocool1** [comment]
Hello? Please see our message in your previous PR

**Comment by Suibansos** [comment]
Which PR please give me? and please tell me what are the shortcomings of
our token, even though we have differentiated the logo and token name with
the existing ones.

**Pull request closed without merging**
