### PR TITLE
Add BiCity AI Projects (BEP20)

### PR DESCRIPTION
**Pull request by bicitycom**
Adding info for BEP20 token 'BiCity AI Projects'.

PR created by <a href="https://assets.trustwallet.com">TW Assets Management</a>

### CODE REVIEW

**Comment by cryptomanz1** [comment]
• What is the purpose of this token? How will it benefit Trust Wallet users?
 • How is the token being distributed? Are you conducting an airdrop?
 • Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?
 • Is the token listed on a centralized/decentralized exchange?
 • Is a Smart Contract audit completed? Where can we find this information?

**Comment by bicitycom** [comment]
> • What is the purpose of this token? How will it benefit Trust Wallet users?
The purpose of this token is to empower users by providing seamless access to advanced AI-driven content creation tools within the BiCity ecosystem. For Trust Wallet users, this token offers direct access to our platform's premium features, enabling them to create high-quality digital content more efficiently. Additionally, the token facilitates participation in revenue-sharing programs and governance, allowing users to influence the development of the platform while benefiting from the growth of the ecosystem.

> • How is the token being distributed? Are you conducting an airdrop?
The token is being distributed through a combination of public and private sales, with a portion allocated for community incentives and strategic partnerships. We are also planning an airdrop to reward early supporters and expand our community.


> • Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?
Yes, and we are currently in the process of distributing the tokens. The distributions are ongoing and will be fully completed by the end of August.

> • Is the token listed on a centralized/decentralized exchange?
Yes.
https://www.lbank.com/trade/bicity_usdt
https://www.mexc.com/exchange/BICITY_USDT
https://www.bitget.com/spot/BICITYUSDT
https://www.gate.io/trade/BICITY_USDT

> • Is a Smart Contract audit completed? Where can we find this information?
Yes, https://skynet.certik.com/projects/bicity

**Comment by bicitycom** [comment]
Holders
11,291
Total Transfers
24,066

**Comment by bicitycom** [comment]
@cryptomanz1 is everything clear?

**Pull request merged**
