### PR TITLE
Add EASE (ERC20) token info and logo

### PR DESCRIPTION
**Pull request by dominikpre**
Add EASE (ERC20) token info and logo

### CODE REVIEW

**Comment by Cryptocool1** [comment]
As per our policy, brand new tokens are not included, there is a minimum requirement of 10,000 holder addresses and 15,000 transactions, in order to filter out scam tokens.
See the criteria at : https://developer.trustwallet.com/assets/requirements .

**Comment by dominikpre** [comment]
"Minimum 10,000 token holders and 15,000 transactions (Airdrop tokens excluded). This requirement is subject for review based on the project."
We rebranded from Armor Finance and already had an established project and tokens listed on trustwallet (See Armor and Armor NXM token). Is there the possibility to reconsider this requirement for us?

**Comment by Cryptocool1** [comment]
Hello, no your project has only 3 holders.

**Comment by dominikpre** [comment]
Yeah, that is true. Armor Finance and its tokens ARMOR and ARMOR NXM have 15,781 holders, 134,025 tx and 404 holders, 11,440 tx respectively. Both of these tokens are from our project, which we essentially rebrand, so ARMOR holders can swap 1:1 for ARMOR, meaning most of the holders will transfer on the 22nd when our release is. We would really like to have our info with logo etc. up until that point. The project and thee attached tokens have been thoroughly audited and a bug bounty program is currently active on immunefi, paying USD $100,000 for critical findings. Hope to hear back from you about the integration, as we think our token is not really "brand new" in that regard.

**Comment by Cryptocool1** [comment]
Your token called EASE, not Armor

**Pull request closed without merging**
