### PR TITLE
Add logo for Little Bunny Rabbit

### PR DESCRIPTION
**Pull request by littlebunnyrocket**
Please update our logo as soon as

### CODE REVIEW

**Comment by cryptomanz** [comment]
-  Description field is too long, please compact it (608 chars, max is 500)

**Comment by Cryptocool1** [comment]
fixed

**Comment by Cryptocool1** [comment]
could you add the links?
see the example here: https://developer.trustwallet.com/assets/repository_details

**Comment by littlebunnyrocket** [comment]
"links": [
        {
            "name": "github",
            "url": "https://github.com/littlebunnyrocket/littlebunnyrocket"
        },
        {
            "name": "twitter",
            "url": "https://twitter.com/l_bunnyrocket"
        },
        {
            "name": "Telegram",
            "url": "https://t.me/littlebunnyrocket"
        }
    ]

**Pull request merged**
