### PR TITLE
Add Aurum (BEP20)

### PR DESCRIPTION
**Pull request by Huwonk**
Adding info for BEP20 token 'Aurum'.

PR created by <a href="https://assets.trustwallet.com">TW Assets Management</a>

### CODE REVIEW

**Comment by Cryptocool1** [comment]
cant find contract on your website
please add

**Comment by SirTristanKnightsDefi** [comment]
> cant find contract on your website
> please add

Hey there, you mean the contract needs to be linked from the website?

**Comment by cryptomanz** [comment]
> > cant find contract on your website
> > please add
> 
> Hey there, you mean the contract needs to be linked from the website?

I mean your contract should be on your website

**Comment by SirTristanKnightsDefi** [comment]
> > > cant find contract on your website
> > > please add
> > 
> > 
> > Hey there, you mean the contract needs to be linked from the website?
> 
> I mean your contract should be added on your website

Oh my, I have added the incorrect Website!  It should be https://aurumofficial.net/ not https://aurumofficial.app/  So sorry.  Are you able to fix this, or do I need to resubmit?

**Comment by Cryptocool1** [comment]
• What is the purpose of this token? How will it benefit Trust Wallet users?
 • How is the token being distributed? Are you conducting an airdrop?
 • Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?
 • Is the token listed on a centralized/decentralized exchange?
 • Is a Smart Contract audit completed? Where can we find this information?

**Comment by SirTristanKnightsDefi** [comment]
• What is the purpose of this token? How will it benefit Trust Wallet users?
  With our feature-packed wallet to be released and crypto-centric security browser, coupled with the tokenomics, it incentivises holding $AUR while unlocking premium features.  The token allows for users to get automatically rewarded in any token they select!  It will benefit trust wallet users by allowing them to properly track their tokens without having to add custom tokens, as well as helping see logos and price once CMC/CG are updated.
• How is the token being distributed? Are you conducting an airdrop?
  The token was a rebranding/relaunch of the Moonboys token.  There was an airdrop to original Moonboys holders with the same liquidity, etc.  
• Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?
  No, it was stealth launched on Pancake Swap.
• Is the token listed on a centralized/decentralized exchange?
  It is currently listed on Pancake Swap, but BitMart and XT exchanges are listing the token as it is the relaunch of Moonboys (which was previously traded on those exchanges.)
• Is a Smart Contract audit completed? Where can we find this information?
Yes an audit was completed with no major issues found.  I will look to see if I can get a copy of this on the site and will link it here.

**Comment by cryptomanz** [comment]
Awaiting for audit

**Comment by SirTristanKnightsDefi** [comment]
sorry for the delay!  https://fightagainstrugs.com/reports/Aurum%20Finance.pdf

**Comment by SirTristanKnightsDefi** [comment]
> Awaiting for audit

Sorry not sure if you got notified, just tagging you so you get an alert otherwise :)

**Comment by cryptomanz** [comment]
can you please add links to your PR?
example: https://developer.trustwallet.com/add_new_asset#info-json-contents

**Comment by SirTristanKnightsDefi** [comment]
Yeah will have to wait until I get home.

**Comment by SirTristanKnightsDefi** [comment]
ok I've added links to the PR (and fixed that Reddit link).  Anything else needed from me?

**Pull request merged**
