### PR TITLE
Add MOWA logo and info

### PR DESCRIPTION
**Pull request by moniwar-mowa**
Add MOWA logo and info, Please accept!
Thank You!!

### CODE REVIEW

**Comment by moniwar-mowa** [comment]
Please help soon.

Thank you very much!!

**Comment by cryptomanz** [comment]
Hello,
• What is the purpose of this token? How will it benefit Trust Wallet users?
 • How is the token being distributed? Are you conducting an airdrop?
 • Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?
 • Is the token listed on a centralized/decentralized exchange?
 • Is a Smart Contract audit completed? Where can we find this information?

**Comment by moniwar-mowa** [comment]
Hi Nazar,

• What is the purpose of this token? How will it benefit Trust Wallet users?
       > Token represents Game Moniwar project, When there are enough logos
it helps Trust Wallet users not to be confused by Scam projects.
• How is the token being distributed? Are you conducting an airdrop?
      > You can easily view the full token allocation information on our
official website and on the project's whitepaper.
             Website: https://moniwar.io
              whitepaper: https://docs.moniwar.io
         The NFT airdrop has ended and the rewards are being claimed on the
project's dapp website: https://dapp.moniwar.io/claim-nft
• Did you sold the tokens at an Initial Coin Offering (ICO) or a token
presale?
      > yes we have an ICO to fund the project development, and a
reasonable amount of tokens are allocated monthly.
• Is the token listed on a centralized/decentralized exchange?
      > yes, they are listed on the decentralized exchange:
https://pancakeswap.finance/info/token/0x411ec510c85c9e56271bf4e10364ffa909e685d9
we are also preparing to list on centralized exchanges, they are in the
plan.
• Is a Smart Contract audit completed? Where can we find this information?
     > Yes, we have completed the inspection. and still testing more units.
you can find in our github.
https://github.com/moniwar-mowa/Smart-Contract-Audits

Thanks Nazar!

Vào Th 2, 8 thg 11, 2021 vào lúc 03:41 Nazar ***@***.***>
đã viết:

**Comment by moniwar-mowa** [comment]
Website: https://moniwar.io
Whitepaper: https://docs.moniwar.io
Moniwar Social Media:
Follow Twitter : https://twitter.com/moniwar_game 
Join Telegram Channel: https://t.me/MoniwarAnnouncements 
Join Telegram Group: https://t.me/MoniwarOfficial 
Follow Facebook: https://www.facebook.com/MoniwarOfficial/
Subbrice Youtube: https://www.youtube.com/c/MoniwarOfficial
Follow Medium: https://moniwar.medium.com/ 
Instagram: https://www.instagram.com/moniwario/ 
Follow Tiktok: https://www.tiktok.com/@moniwar_official
Join Discord: https://discord.gg/yUWKW9cY

**Comment by moniwar-mowa** [comment]
https://www.coingecko.com/vi/ty_gia/moniwar
https://coinmarketcap.com/currencies/moniwar/

**Comment by Cryptocool1** [comment]
awaiting for smart contract audit, on hold for now

**Comment by moniwar-mowa** [comment]
Thank You!

Vào Th 2, 8 thg 11, 2021 vào lúc 15:39 ramsty ***@***.***>
đã viết:

**Pull request merged**
