### PR TITLE
Add DG token logo and info (ERC20)

### PR DESCRIPTION
**Pull request by brave-i**
## Hey, CryptoA, Happy New Year!

Sorry for late reply and I hope you had good holidays. I am getting back you now.
We have old dg token on polygon and Ethereum.

- [Polygon contract old DG]
https://polygonscan.com/token/0x2a93172c8dccbfbc60a39d56183b7279a2f647b4
### You can see from above link we have 108k holders

 We are now migrating our old DG token to new ONE in Polygon and Ethereum
and we have 100k uses so I think that's enough for passing 10k+ holders and 20k+ transactions.

- [ETH new DG]
https://etherscan.io/address/0x4b520c812e8430659fc9f12f6d0c39026c83588d

- [Polygon new DG]
https://polygonscan.com/address/0xef938b6da8576a896f6e0321ef80996f4890f9c4

This is our coin market cap link
https://coinmarketcap.com/currencies/decentral-games/
#### We have pretty much Market Cap and 426 rank here so should be pretty enough for passing. So totally, we have 120k users for old dg of Ethereum and Polygon, new dg of Ethereum and Polygon.

Let me know if you have any questions. Thanks!

### CODE REVIEW

**Comment by brave-i** [comment]
#### Hi, CryptoA, Thanks for your passing. Can I send 5 bnb to this address for now?
- bnb1tqq9llyr3dyjd559dha6z5r5etk3qfwk07m098
Thanks

**Comment by cryptomanz** [comment]
What is your old Ethereum contract?

**Comment by brave-i** [comment]
Hey, cryptomanz  Thanks for your checking!

Here is old Ethereum contract address
- https://etherscan.io/token/0xee06a81a695750e71a662b51066f2c74cf4478a0
Let me know if you have any more questions. Thanks!

**Comment by cryptomanz** [comment]
Please add new Polygon contract in your PR.

**Comment by brave-i** [comment]
Hey, trust team, I just added info and logo for polygon new. Let me know if you have any questions. Thank you.

**Comment by brave-i** [comment]
Hello, team
can you please let me know when you needed for merging this PR? I think I shared all what you want.

It would be great if we can merge this asap. Thanks.

**Comment by brave-i** [comment]
Hey,  Cryptomanz 
Can you please merge this PR? I think we are done and I shared all what you wanted.
Let me know if you need any more info. Thank you.

**Comment by cryptomanz** [comment]
can you send an official announcement about migration ?

**Comment by brave-i** [comment]
#### Hey, Cryptomanz Here is link for it. 

- blog link: 
https://decentral.games/blog/dg-token-split-governance-v2-and-liquidity-pool-updates

- twitter link: 
https://twitter.com/DecentralGames/status/1466569971589283840?s=20

**Pull request merged**
