### PR TITLE
Added CashCow to the assets folder

### PR DESCRIPTION
**Pull request by CashCowProject**
Please add or CashCow token to your assets folder thank you very much

### CODE REVIEW

**Comment by cryptomanz** [comment]
Contract is not in checksum format, should be 0x8B6fA031c7D2E60fbFe4E663EC1B8f37Df1ba483 (not 0x8b6fa031c7d2e60fbfe4e663ec1b8f37df1ba483). Please change.

**Comment by CashCowProject** [comment]
> 0x8B6fA031c7D2E60fbFe4E663EC1B8f37Df1ba483



> Contract is not in checksum format, should be 0x8B6fA031c7D2E60fbFe4E663EC1B8f37Df1ba483 (not 0x8b6fa031c7d2e60fbfe4e663ec1b8f37df1ba483). Please change.

Hi did you check the last commit? The id field as well as the explorer link are checksummed with this address 0x8B6fA031c7D2E60fbFe4E663EC1B8f37Df1ba483

Is our request accepted?

**Comment by golfinance** [comment]
Hi, it seems like our commit is not passing the pull_request_ci script? 
We see Error: Process completed with exit code 2.

Did we make a mistake? The info.json file looks fine and in the latest commit everything is checksummed, what do we have to do to get this fixed and accepted? 

Thank you.

**Comment by Cryptocool1** [comment]
Contract is not in checksum format, should be 0x8B6fA031c7D2E60fbFe4E663EC1B8f37Df1ba483 (not 0x8b6fa031c7d2e60fbfe4e663ec1b8f37df1ba483). Please rename it.

**Review by CashCowProject — COMMENTED** [review]
This looks fine, can you approve it like this?

**Comment by Cryptocool1** [comment]
your contract is not in checksum format

**Comment by CashCowProject** [comment]
> your contract is not in checksum format

What do you mean exactly, could you show us where and how we should fix that? You mean the contract itself or the address in the info.json file?

**Review by CashCowProject — COMMENTED** [review]
What do you mean exactly, could you show us where and how we should fix that? You mean the contract itself or the address in the info.json file?

**Comment by cryptomanz** [comment]
Please follow the rules for adding token, you should be send me your smart contract audit.
Here is the example of smart contract audit: https://www.certik.org/projects/binance.
Screenshot 2021-09-16 at 18 48 58

**Comment by cryptomanz** [comment]
This is your wrong:
Screenshot 2021-11-01 at 23 36 12
Screenshot 2021-11-01 at 23 36 18
Contract should be 0x8B6fA031c7D2E60fbFe4E663EC1B8f37Df1ba483 (not 0x8b6fa031c7d2e60fbfe4e663ec1b8f37df1ba483). Please rename it.

**Comment by cryptomanz** [comment]
• What is the purpose of this token? How will it benefit Trust Wallet users?
 • How is the token being distributed? Are you conducting an airdrop?
 • Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?
 • Is the token listed on a centralized/decentralized exchange?
 • Is a Smart Contract audit completed? Where can we find this information?

**Comment by cryptomanz** [comment]
why did you delete the files?

**Comment by CashCowProject** [comment]
> why did you delete the files?

I'm sorry, that was a mistake, i added them again.

**Comment by cryptomanz** [comment]
> • What is the purpose of this token? How will it benefit Trust Wallet users?
> • How is the token being distributed? Are you conducting an airdrop?
> • Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?
> • Is the token listed on a centralized/decentralized exchange?
> • Is a Smart Contract audit completed? Where can we find this information?

Can your answer some questions?

**Comment by CashCowProject** [comment]
> > • What is the purpose of this token? How will it benefit Trust Wallet users?
> > • How is the token being distributed? Are you conducting an airdrop?
> > • Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?
> > • Is the token listed on a centralized/decentralized exchange?
> > • Is a Smart Contract audit completed? Where can we find this information?
> 
> Can your answer some questions?

Hi, thank you for asking:

**About our project**
CashCow Protocol is a community driven project with the vision of creating an NFT based Play to Earn Blockchain Game.
Protocol development roadmap includes the following features:
CashCow Token
CashCow Staking
Milk Token
CashCow NFTs
CashCow Farm 
P2E Game

We did not do an ICO, community members can earn more COW tokens by simply holding them in their wallets and can earn tokens by participating in marketing initiatives. We grow the project by help from the community.

Our token is listed on PancakeSwap and liquidity is automatically added for each transaction.
WhitePaper:
https://cashcowprotocol.gitbook.io/cashcow-protocol/cashcow-protocol/cashcow-token/tokenomics

We are getting our contract audited soon, this is hight on our priority list.

**Comment by cryptomanz** [comment]
Awaiting for smart contract audit. On hold for now.

**Comment by Cryptocool1** [comment]
Please come back to us when all criteria are met.
When creating a new PR make sure to mention this PR, so that we can see that fee has been paid already here.

**Pull request closed without merging**
