### PR TITLE
adding oKLAY (ethereum)

### PR DESCRIPTION
**Pull request by kjeom**

### CODE REVIEW

**Comment by cryptomanz1** [comment]
As per our policy, there is a minimum requirement of 10,000 holder addresses and 15,000 transactions.
See the criteria at : https://developer.trustwallet.com/listing-new-assets/requirements .

**Comment by kjeom** [comment]
@cryptomanz1 Could you check [this](https://github.com/trustwallet/assets/blob/19a61c1f70ef83884f357809c3afd7950b795639/blockchains/ton/assets/EQDZM7xsqa7huHq2lxoRLqMM71jwegQFPe7wijDDHOirpetR/info.json#L2C19-L2C19)?
It's already listed in Trust Wallet

**Comment by steve-jeon-KF** [comment]
Hey, I'm Steve from Klaytn Foundation. Do we need to register an official Klay first or Is this listed oKLAY enough to meet the requirement? 

> @cryptomanz1 Could you check [this](https://github.com/trustwallet/assets/blob/19a61c1f70ef83884f357809c3afd7950b795639/blockchains/ton/assets/EQDZM7xsqa7huHq2lxoRLqMM71jwegQFPe7wijDDHOirpetR/info.json#L2C19-L2C19)? It's already listed in Trust Wallet

**Comment by cryptomanz1** [comment]
you need to add links and tags

**Comment by kjeom** [comment]
Could you let me know where can I add the links and tags?
This is different links in the `PR Summary`, right?

**Comment by cryptomanz1** [comment]
This is example `info.json`:
`{
    "name": "BNB Smart Chain",
    "website": "https://www.bnbchain.world/en/smartChain",
    "description": "A blockchain with a full-fledged environment for developing high-performance decentralized applications and cross-chain compatibility with Binance Chain.",
    "explorer": "https://bscscan.com/",
    "research": "https://research.binance.com/en/projects/bnb",
    "symbol": "BNB",
    "type": "coin",
    "decimals": 18,
    "status": "active",
    "tags": [
        "staking-native"
    ],
    "links": [
        {
            "name": "github",
            "url": "https://github.com/binance-chain/"
        },
        {
            "name": "twitter",
            "url": "https://twitter.com/BNBCHAIN"
        },
        {
            "name": "reddit",
            "url": "https://reddit.com/r/BinanceExchange"
        },
        {
            "name": "whitepaper",
            "url": "https://www.binance.com/resources/ico/Binance_WhitePaper_en.pdf"
        }
    ]
}`

**Comment by kjeom** [comment]
Please reopen for payments. Thanks

**Comment by kjeom** [comment]
@cryptomanz1 kindly reminder, Thanks for your help.

**Comment by steve-jeon-KF** [comment]
@unanoc Daniel! It's Steve, can you reopen this? then we can proceed it to the next step!

**Comment by steve-jeon-KF** [comment]
> @unanoc Daniel! It's Steve, can you reopen this? then we can proceed it to the next step!

**Comment by kjeom** [comment]
Please reopen to get the payment address. Thanks

**Comment by steve-jeon-KF** [comment]
> This PR is being closed due to inactivity. If you wish to continue, please have us reopen the PR before sending your payment, or just create a new one. Do NOT send payments for closed PR, as the fee may by lost!

Please reopen it

**Pull request closed without merging**
