### PR TITLE
Update logo and info

### PR DESCRIPTION
**Pull request by ThunderBnb**
Update logo and info

### CODE REVIEW

**Comment by cryptomanz** [comment]
Hello,
 • What is the purpose of this token? How will it benefit Trust Wallet users?
 • How is the token being distributed? Are you conducting an airdrop?
 • Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?
 • Is the token listed on a centralized/decentralized exchange?
 • Is a Smart Contract audit completed? Where can we find this information?

**Comment by ThunderBnb** [comment]
Hello,

• What is the purpose of this token? How will it benefit Trust Wallet users?

ThunderBNB is world an innovative double reward reflection token using the
power of 80/20: 80% reflection rewards in now & midterm (BNB), 20%
reflection rewards in long term (THOREUM)

It will maximize earnings for ThunderBNB investors.

Currently we have more than 5000 holders

For Trust Wallet users, they can be more convenient to buy & sell.


• How is the token being distributed? Are you conducting an airdrop?

Total supply 100B distributed as below:

- 15% Dev fund

- 10% Marketing fund

*- 1% Airdrop*

- 45% Presale

- 27% PancakeSwap

- 2% ITO fee

Yes, we're conducting airdrop

https://t.me/ThunderBNBBot
<https://web.telegram.org/k/#/im?p=%40ThunderCakeBot>


• Did you sold the tokens at an Initial Coin Offering (ICO) or a token
presale?

Yes, we did ITO on Thoreum.Finance for presale

- 1 Thoreum = 1930.19 ThunderBNB

- 1 ThunderCake = 6.5 ThunderBNB

- 1BNB = 44,437,312.53 ThunderBNB

https://thoreum.finance/ito


• Is the token listed on a centralized/decentralized exchange?

Yes, ThunderBNB is listed on PancakeSwap

https://pancakeswap.finance/swap#/swap?outputCurrency=0xb9654A42f0F5dCDEf5617DebF8bd048E33F180E7


• Is a Smart Contract audit completed? Where can we find this information?

Yes, Smart Contract audited by

- Thoreum Internal Auditing team: Done

- Techrate on going.

- Certik on going


Any further question, please let us know.


Thank you & regards,

ThunderBNB team

**Comment by Cryptocool1** [comment]
can you send me your smart contract audit?

**Comment by ThunderBnb** [comment]
We will send you later once available, by Techrate or Certik.
Currently we're audited by Thoreum team

Thank you,

**Comment by Cryptocool1** [comment]
please create new PR when smart contract will be ready to send. make sure to mention this PR so that the fee can be reused

**Comment by ThunderBnb** [comment]
plz check new PR #13011

**Comment by ThunderBnb** [comment]
Hi,

We have submitted new PR  #13011

Kindly check & confirm our fee paid

Thank you,

**Pull request closed without merging**
