### PR TITLE
Add Daddy Doge (BEP20)

### PR DESCRIPTION
**Pull request by HizzleDev**
Adding info for BEP20 token 'Daddy Doge'.

PR created by <a href="https://assets.trustwallet.com">TW Assets Management</a>

### CODE REVIEW

**Comment by Cryptocool1** [comment]
Hello, what is the purpose of this token?

**Comment by LukeHickling** [comment]
> Hello, what is the purpose of this token?
@Cryptocool1 
Hi there! 

It's a community driven, deflationary token with reflections built in. It's built around the "Daddy Doge", who is the head of the Doge family. Ownership is renounced, and there are no large token wallets held by the dev team.

Hope that answers your question!

**Comment by zachzwei** [comment]
> > Hello, what is the purpose of this token?
> 
> @Cryptocool1
> Hi there!
> 
> It's a community driven, deflationary token with reflections built in. It's built around the "Daddy Doge", who is the head of the Doge family. Ownership is renounced, and there are no large token wallets held by the dev team.
> 
> Hope that answers your question!

You only provided a generic description about this token. This is being used by other similar assets.
In order to do a quick overview of your submission, please provide a response to the following questions:

* What is the purpose of this token? How will it benefit Trust Wallet users?
* How is the token being distributed? Are you conducting an airdrop?
* Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?
* Is the token listed on a centralized/decentralized exchange?
* Is a Smart Contract audit completed? Where can we find this information?

**Comment by LukeHickling** [comment]
> > > Hello, what is the purpose of this token?
> > 
> > 
> > @Cryptocool1
> > Hi there!
> > It's a community driven, deflationary token with reflections built in. It's built around the "Daddy Doge", who is the head of the Doge family. Ownership is renounced, and there are no large token wallets held by the dev team.
> > Hope that answers your question!
> 
> You only provided a generic description about this token. This is being used by other similar assets.
> In order to do a quick overview of your submission, please provide a response to the following questions:
> 
> * What is the purpose of this token? How will it benefit Trust Wallet users?

This is a meme token with the purpose, in short, as a store of value. There are other benefits to the token, for example, one specific example of benefiting Trust Wallet users would be that reflections are be carried out on each transaction increasing a users token amount. The longer a user was to hold, the more tokens they would gain. This is unlikely to be possible on centralised exchanges.

> * How is the token being distributed? Are you conducting an airdrop?

The token was distributed 25% in a presale and 25% in liquidity on Pancakeswap, the remaining tokens were used by DxSale and burned. There are no large unlocked dev wallets.

Burn address: https://bscscan.com/token/0x7cce94c0b2c8ae7661f02544e62178377fe8cf92?a=0x000000000000000000000000000000000000dead
Presale details: https://dxsale.app/app/v2_9/defipresale?saleID=362&chain=BSC

> * Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?

There was a token presale on DxSale, please see: https://dxsale.app/app/v2_9/defipresale?saleID=362&chain=BSC

> * Is the token listed on a centralized/decentralized exchange?

The token is listed on PancakeSwap only at current, please see: https://exchange.pancakeswap.finance/#/swap?outputCurrency=0x7ccE94C0B2C8aE7661f02544E62178377Fe8cF92

> * Is a Smart Contract audit completed? Where can we find this information?

There is no smart contract audit at present but this will be arranged in the next couple of days.


I appreciate the response is similar to other tokens because the tokenomics are not dissimilar. The separation is that of the meme and how people hold value in it. We reached a 20m market cap within 6 hours of launch, putting us as one of the fastest growing BSC launches ever.

Happy to answer any further questions.

**Comment by LukeHickling** [comment]
@Cryptocool1 @zachzwei Is anything else needed from my end?

**Comment by Cryptocool1** [comment]
> @Cryptocool1 @zachzwei Is anything else needed from my end?

we will wait for or smart contract audit.
now on hold,
thanks

**Comment by LukeHickling** [comment]
> > @Cryptocool1 @zachzwei Is anything else needed from my end?
> 
> we will wait for smart contract audit.
> now on hold,
> thanks

> > @Cryptocool1 @zachzwei Is anything else needed from my end?
> 
> we will wait for smart contract audit.
> now on hold,
> thanks

In that case could we have the 1000TWT back please whilst waiting. Thank you.

**Comment by Cryptocool1** [comment]
Hi! In order to compensate for the efforts of processing PRs, we kindly ask for a contribution.
💀 As there is no refund, before paying the fee, make sure new tokens fulfill the minimum circulation and other acceptance criteria.
See also the PR Fee FAQ.

**Comment by LukeHickling** [comment]
> Hi! In order to compensate for the efforts of processing PRs, we kindly ask for a contribution.
> 💀 As there is no refund, before paying the fee, make sure new tokens fulfill the minimum circulation and other acceptance criteria.
> See also the PR Fee FAQ.

That's fair enough. Thank you for taking the time to review it.

Here is the smart contract audit: https://dessertswap.finance/audits/DaddyDoge%20BEP-20%20Audit%209007795.pdf
Whitepaper as well if necessary: https://daddydoge.finance/whitepaper/

As you could imagine, we would be really keen to move this forward. Again, thank you for your time.

@Cryptocool1 @zachzwei

**Comment by Cryptocool1** [comment]
awaiting for listing on cmc 
on hold for now

**Comment by Cryptocool1** [comment]
Hello,
please create new PR when listing on CMC will be ready.
make sure to mention this PR, so that we can see that fee has been paid already here.

**Comment by LukeHickling** [comment]
> awaiting for listing on cmc
> on hold for now

@Cryptocool1 
Could you please point me to the acceptance criteria that requires this?
Screenshot 2021-07-09 at 19 35 47

**Pull request closed without merging**
