### PR TITLE
Add files via upload

### PR DESCRIPTION
**Pull request by flaviosar**

### CODE REVIEW

**Comment by flaviosar** [comment]
Hello, what's wrong?

**Comment by flaviosar** [comment]
Hello
What is NPM error?
Not just upload the image?
Or do I have to do something else?
Please help me.
Thanks.

**Comment by kolya182** [comment]
@flaviosar File structure is wrong, please change it

**Comment by flaviosar** [comment]
Hello @kolya182
Explain me better please.
Thank you

**Comment by kolya182** [comment]
> Hello @kolya182
> Explain me better please.
> Thank you

Did you read requirements on how to add new image ?. What part of the description makes you feel the way you uploaded is the right way ?. I'm trying to improve the process and i need you feedback

**Comment by flaviosar** [comment]
So...
The first time I thought I was going to rename the file with the contract address;
the second time I renamed it to logo.png
and commit the contract address
none worked
I followed the tutorial steps
what is wrong then?

**Comment by kolya182** [comment]
Non of the uploads you made is correct, here is how you should do it https://github.com/trustwallet/assets/commit/6859ca08e94973fbb24e772a1a297324f5b02f70

**Comment by flaviosar** [comment]
Thanks.
I want to learn what I'm wrong for next to do right.
How do I need to rename the image?

**Comment by kolya182** [comment]
> Thanks.
> I want to learn what I'm wrong for next to do right.
> How do I need to rename the image?

https://github.com/trustwallet/assets#repository-structure

**Comment by flaviosar** [comment]
I read several times, I believe that as I have others having the same doubt.
A suggestion, even knowing the tree structure, would not be easier to exemplify:
        address_smart_contract .... .png
What I understand is:
I just have to rename the image with the contract, or
I have to create the folders to upload the image.

**Comment by kolya182** [comment]
> I read several times, I believe that as I have others having the same doubt.
> A suggestion, even knowing the tree structure, would not be easier to exemplify:
> address_smart_contract .... .png
> What I understand is:
> I just have to rename the image with the contract, or
> I have to create the folders to upload the image.

Just copy paste have others have done.

**Comment by flaviosar** [comment]
ok, thanks.

**Pull request closed without merging**
