### PR TITLE
Add Black Phoenix  (TRC20)

### PR DESCRIPTION
**Pull request by BLACKPHOENIXBPX**
This PR is being closed due to inactivity. If you wish to continue, please have us reopen the PR before sending your payment, or just create a new one.
Do NOT send payments for closed PR, as the fee may by lost!
  (48 vs. 48 hrs)

### CODE REVIEW

**Comment by BLACKPHOENIXBPX** [comment]
can we reopen this for payment ?

**Comment by BLACKPHOENIXBPX** [comment]
@Cryptocool1 Please Kindy Reopen this PR so we can made the payment

**Comment by Cryptocool1** [comment]
will ask the question again.
• Is a Smart Contract audit completed? Where can we find this information?

**Comment by BLACKPHOENIXBPX** [comment]
@Cryptocool1 i cant understand the meaning of smart contract audit , please inlight me so i can provide it for you

**Comment by BLACKPHOENIXBPX** [comment]
> will ask the question again. • Is a Smart Contract audit completed? Where can we find this information?

IMG_20211209_032508_018

isn't this Smart Contract?
all of our users have Trust wallet that's why we are needed to complete listing in, if your not accepting please tell

**Comment by BLACKPHOENIXBPX** [comment]
> This PR is being closed due to inactivity. If you wish to continue, please have us reopen the PR before sending your payment, or just create a new one. Do NOT send payments for closed PR, as the fee may by lost! (48 vs. 48 hrs)

Kindly Reopen this PR

**Comment by BLACKPHOENIXBPX** [comment]
@cryptomanz Kindly Reopen this PR

**Comment by Cryptocool1** [comment]
> > will ask the question again. • Is a Smart Contract audit completed? Where can we find this information?
> 
> IMG_20211209_032508_018
> 
> isn't this Smart Contract? all of our users have Trust wallet that's why we are needed to complete listing in, if your not accepting please tell

We require audit from : certik, techrate

**Comment by cryptomanz** [comment]
Do you have smart contract audit?
Here is the example of smart contract audit: https://www.certik.org/projects/binance

**Comment by BLACKPHOENIXBPX** [comment]
> Do you have smart contract audit? Here is the example of smart contract audit: https://www.certik.org/projects/binance

Unfortunately we don't have this, and you have not asked anything like this before, when we Submit a PR 28 Days ago!

**Comment by Cryptocool1** [comment]
> > Do you have smart contract audit? Here is the example of smart contract audit: https://www.certik.org/projects/binance
> 
> Unfortunately we don't have this, and you have not asked anything like this before, when we Submit a PR 28 Days ago!

Can you read our requirements please?
https://developer.trustwallet.com/assets/requirements

**Comment by cryptomanz** [comment]
Screenshot 2021-12-09 at 02 17 31

- https://community.trustwallet.com/t/how-to-submit-a-token-logo/3863

**Comment by BLACKPHOENIXBPX** [comment]
> Screenshot 2021-12-09 at 02 17 31
> 
> * https://community.trustwallet.com/t/how-to-submit-a-token-logo/3863

Ok than we will provide it

**Comment by BLACKPHOENIXBPX** [comment]
> Do you have smart contract audit? Here is the example of smart contract audit: https://www.certik.org/projects/binance
[BLACK PHOENIX.pdf](https://github.com/trustwallet/assets/files/7683883/BLACK.PHOENIX.pdf)

**Comment by BLACKPHOENIXBPX** [comment]
@Cryptocool1 @cryptomanz 
[Uploading BLACK PHOENIX.pdf…]()

**Comment by BLACKPHOENIXBPX** [comment]
[BLACK PHOENIX.pdf](https://github.com/trustwallet/assets/files/7685582/BLACK.PHOENIX.pdf)

**Comment by BLACKPHOENIXBPX** [comment]
@cryptomanz would you accept Audit s.m like this :
https://github.com/TechRate/Smart-Contract-Audits/blob/main/SafeStar%20Full%20Smart%20Contract%20Security%20Audit.pdf

It's will be like This Right?

**Pull request closed without merging**
