### PR TITLE
Add Community Token (COM)  to trust wallet  

### PR DESCRIPTION
**Pull request by ComToken**
Add Community Token (COM)  to trust wallet  

Token Name : Community Token
Token Symbol : COM
Token Supply: 1,000,000
Token Contract Address : 0x1B4052d98fb1888C2Bf3B8d3b930e0aFf8A910dF
0x1B4052d98fb1888C2Bf3B8d3b930e0aFf8A910dF

### CODE REVIEW

**Comment by ComToken** [comment]
pleaase update logo sir

**Comment by catenocrypt** [comment]
@ComToken , as I see these files have been merged with #3164 .  Is there anything else to do?

**Comment by ComToken** [comment]
Hello,

Logo still not updated. Is there something else that needs to be done?

**Comment by ComToken** [comment]
Also, why is is merged with 3164? Isn't it supposed to be 3198?

**Comment by catenocrypt** [comment]
I think you are confused, becuase _this_ PR contains logo for BitPaid, which is already visible in TrustWallet.  Maybe you have meant to include COM token, as in the desc.  I thnk you created for from pr/3164 branch by mistake.
Maybe change content of this PR ro create a new one (no need to pay again).

image

**Comment by ComToken** [comment]
please fix sir

**Comment by ComToken** [comment]
https://github.com/trustwallet/assets/pull/3210

**Comment by ComToken** [comment]
I've created a new one 3210. Can you please confirm that its okay?

**Comment by ComToken** [comment]
new request #3210

already paid it from this sir

#3198

**Comment by ComToken** [comment]
https://github.com/trustwallet/assets/pull/3210

**Comment by catenocrypt** [comment]
PR #3210 just merged instead of this one, closing this.

**Pull request closed without merging**
