### PR TITLE
BEES $BEE Logo

### PR DESCRIPTION
**Pull request by BeesOnBSC**
Logo for BEES $BEE
We are about to launch the project and we will have over 4000 Holders and will be listed on CMC and Gecko in a short time.

### CODE REVIEW

**Comment by BeesOnBSC** [comment]
How I can pay with metamask or trustwallet?

**Comment by BeesOnBSC** [comment]
Can i have help for fix this?

**Comment by BeesOnBSC** [comment]
Can i have help for fix this?

**Comment by BeesOnBSC** [comment]
Please help me solve

**Comment by Cryptocool1** [comment]
> Please help me solve

Hello, 
If you can't rename files in the PR, you may open a new PR. Make sure to mention this PR, so that we can see that fee has been paid already here.

**Comment by Cryptocool1** [comment]
You may want to try our new Assets app in beta; go to https://assets.trustwallet.com, log on with Github, enter contract ID, logo and some additional info, and it will create a PR for you.
See https://community.trustwallet.com/t/how-to-submit-a-token-logo-using-assets-app/82957.

**Comment by BeesOnBSC** [comment]
I have payed it. Don’t close

Il giorno lun 17 mag 2021 alle 10:38 CryptoA ***@***.***> ha
scritto:

**Pull request closed without merging**
