### PR TITLE
Update token info VelasPad

### PR DESCRIPTION
**Pull request by divinechoice**
logo and info update

### CODE REVIEW

**Comment by divinechoice** [comment]
Just an additional comment this token is listing today at 3 PM UTC on pancakeswap

**Comment by divinechoice** [comment]
@zachzwei @Cryptocool1 Just an additional comment this token is listing today at 3 PM UTC on pancakeswap and 4 pm on Uniswap... Will i have to submit a separate pull request for ethereum chain?

**Comment by Cryptocool1** [comment]
As per our policy, brand new tokens are not included, there is a minimum requirement of 5000 holder addresses and 10000 transactions, in order to filter out scam tokens.
See the criteria at (mentioned in the first message by the bot): https://community.trustwallet.com/t/how-to-submit-a-token-logo/3863).

**Comment by divinechoice** [comment]
> As per our policy, brand new tokens are not included, there is a minimum requirement of 5000 holder addresses and 10000 transactions, in order to filter out scam tokens.
> See the criteria at (mentioned in the first message by the bot): https://community.trustwallet.com/t/how-to-submit-a-token-logo/3863).

Ok will it be auto picked after it will list today on pancakeswap at 3pm UTC or will i have to open another request?

**Comment by divinechoice** [comment]
> As per our policy, brand new tokens are not included, there is a minimum requirement of 5000 holder addresses and 10000 transactions, in order to filter out scam tokens.
> See the criteria at (mentioned in the first message by the bot): https://community.trustwallet.com/t/how-to-submit-a-token-logo/3863).

Hi, We are now live on pancake with over 10k transactions and 5k holders @Cryptocool1 @zachzwei

**Comment by divinechoice** [comment]
@Cryptocool1 @zachzwei @hexorx @rfunduk how do request a re review for this ?

**Pull request merged**
