### PR TITLE
Logo for LOCAL

### PR DESCRIPTION
**Pull request by ETHLocal**
Logo for LOCAL 0xb45e608DafB6CeD582aa337558B7c82f59A3E2B4

### CODE REVIEW

**Comment by zachzwei** [comment]
Please provide more details about this project. 
https://community.trustwallet.com/t/how-to-submit-a-token-logo/3863#how-to-get-approved

You can follow this format when adding an info.json file:

``` {
   "name":"Bitcoin",
   "website":"https://bitcoin.org",
   "source_code":"https://github.com/bitcoin",
   "white_paper":"https://bitcoin.org/bitcoin.pdf",
   "short_description":"Bitcoin is a cryptocurrency and worldwide payment system.",
   "explorer":"https://blockchain.info",
   "research":"https://research.binance.com/en/projects/bitcoin"
}

**Comment by ETHLocal** [comment]
``

> Please provide more details about this project.
> https://community.trustwallet.com/t/how-to-submit-a-token-logo/3863#how-to-get-approved
> 
> You can follow this format when adding an info.json file:
> 
> ```
>    "name":"Bitcoin",
>    "website":"https://bitcoin.org",
>    "source_code":"https://github.com/bitcoin",
>    "white_paper":"https://bitcoin.org/bitcoin.pdf",
>    "short_description":"Bitcoin is a cryptocurrency and worldwide payment system.",
>    "explorer":"https://blockchain.info",
>    "research":"https://research.binance.com/en/projects/bitcoin"
> }
> ```

Any way I can do it from website?

**Comment by catenocrypt** [comment]
Info.json file is still not added.  It should be simply added to this PR, next to the logo.png file.
In the meantime I have checked the usage of the 0xb45e608DafB6CeD582aa337558B7c82f59A3E2B4 token.
The usage is very small, and as per our policy, brand new tokens are not included. There is a minimum requirement of 100 holder addresses and 500 transactions.
See the criteria at (mentioned in the first message by the bot): https://community.trustwallet.com/t/how-to-submit-a-token-logo/3863#how-to-get-approved

Putting this PR on hold.  Please come back to us when all criteria are met.

https://etherscan.io/token/0xb45e608DafB6CeD582aa337558B7c82f59A3E2B4

**Comment by ETHLocal** [comment]
@catenocrypt Thank you for the references.
 
I notice TW just changed their policy again to 500 addresses and 1,000 txns, which makes it VERY HARD for us to accomplish it in a fair and fully community-representative system without involving costly and unpleasing airdrops, in a short time.

1) This issue will be put on stale and then closed, will our PR remain On Hold?
2) is the PR reversible (and 2 BNB refunded) in case we might want to decide to post-pone this procedure, waiting for TW to stabilize their criteria? you will understand, if TW keeps raising the bar it will affect our ops.

Thanks

**Comment by catenocrypt** [comment]
Unfortunately we cannot make expection and we don't do refund.
The PR will be technically closed, and we can reopened it at any time (or create a new one and fee payment considered on that, no need to pay again).  We need proof that this token is indeed used.

**Comment by ETHLocal** [comment]
Of course fully understand the legitimacy of this layer of control in order to combat scams. Still, we feel positive in giving TW our humble feedback: such criteria may prevent legit projects from growing early in their development and may result in a prohibitive environment for Ethereum entrepreneurship with R&D nature. Numbers in Addresses and Txns do not necessarily reflect the legitimacy of a given project, and I don't think the current criteria may actually represent a big obstacle for scam-purposed tokens. Increase the criteria and more damage could be caused than benefits. If the criteria are always on the rise, a work-around will be eventually found by someone. Perhaps giving the chance to R&D project to fulfill lower criteria by matching them with some sort of accountability verification?

However, thanks for the info. We'll keep the ball rolling and get back when we will be eligible, if we still need it.

**Comment by catenocrypt** [comment]
Thanks for the feedback.
Please have in mind that _it is still possible to use the token with Trust Wallet_, the only difference is that it will not have a logo.  The logo is just an extra touch, an extra level of trust, which we reserve for proven projects.

**Pull request closed without merging**
