### PR TITLE
Add Gamezone info

### PR DESCRIPTION
**Pull request by divinechoice**
Gamezone logo and info previous request for which payment is made for a previous PR #14002

### CODE REVIEW

**Comment by divinechoice** [comment]
@Cryptocool1 opened this new PR. Old PR for which payment made is made under PR #14002

**Comment by divinechoice** [comment]
> @divinechoice, kind reminder: please pay fee: **1000 TWT** with the memo **14042** to the address `bnb1tqq9llyr3dyjd559dha6z5r5etk3qfwk07m098`. Alternatively, 5 BNB is also accepted (same memo & address).
> 
> **QR** code: [Trust](https://api.qrserver.com/v1/create-qr-code/?size=200x200&data=https%3A%2F%2Flink.trustwallet.com%2Fsend%3Fasset%3Dc714_tTWT-8C2%26address%3Dbnb1tqq9llyr3dyjd559dha6z5r5etk3qfwk07m098%26amount%3D1000%26memo%3D14042) | [other wallet](https://api.qrserver.com/v1/create-qr-code/?size=200x200&data=bnb1tqq9llyr3dyjd559dha6z5r5etk3qfwk07m098%3Famount%3D1000%26memo%3D14042) See the [Pull Request Fee FAQ](https://developer.trustwallet.com/add_new_asset/pr-fee).

@Cryptocool1 opened this new PR. Old PR for which payment made is made under PR #14002. Requesting you to help with this.

**Comment by cryptomanz** [comment]
Can your answer some questions?
• What is the purpose of this token? How will it benefit Trust Wallet users?
 • How is the token being distributed? Are you conducting an airdrop?
 • Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?
 • Is the token listed on a centralized/decentralized exchange?
 • Is a Smart Contract audit completed? Where can we find this information?

**Comment by Cryptocool1** [comment]
Hello,
Please follow the rules for adding token, your logo should be a full screen, 256x256.
Example:
https://community.trustwallet.com/t/how-to-submit-a-token-logo/3863

**Comment by divinechoice** [comment]
> Hello, Please follow the rules for adding token, your logo should be a full screen, 256x256. Example: https://community.trustwallet.com/t/how-to-submit-a-token-logo/3863

Hi just highlighting that some of the logos when full screen get cut of on trustwallet. Check CrossSwap for an example. 

Updated Logo for Gamezone 

logo

**Comment by divinechoice** [comment]
@Cryptocool1 @cryptomanz anything needed from my side?

**Pull request merged**
