### PR TITLE
Add Shibance WOOF

### PR DESCRIPTION
**Pull request by ShibaRiba**

### CODE REVIEW

**Comment by Cryptocool1** [comment]
Hello, what is the purpose of this token?

**Comment by ShibaRiba** [comment]
Hi @Cryptocool1,

WOOF is the native token of the Shibance Meme DEX and LaunchPad

**Comment by Cryptocool1** [comment]
> Hi @Cryptocool1,
> 
> WOOF is the native token of the Shibance Meme DEX and LaunchPad

And what is the purpose ?

**Comment by ShibaRiba** [comment]
Hi, Shibance is the first DEX and Launchpad dedicated to memes. We aim to be the go-to platform for anyone looking to trade and farm their favourite meme token, and a place to check out up and coming meme projects.

The Shibance Token (WOOF) is the platform's native token. Users are incentivized to pool liquidity on Shibance through yield farming to earn the native currency, WOOF. Additionally, users can use their earned WOOF to stake and earn other tokens.

**Comment by Cryptocool1** [comment]
can u answer some questions?
• How is the token being distributed? Are you conducting an airdrop?
 • Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?
 • Is the token listed on a centralized/decentralized exchange?
 • Is a Smart Contract audit completed? Where can we find this information?

**Comment by ShibaRiba** [comment]
> can u answer some questions?
> • How is the token being distributed? Are you conducting an airdrop?
> • Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?
> • Is the token listed on a centralized/decentralized exchange?
> • Is a Smart Contract audit completed? Where can we find this information?

• How is the token being distributed? Are you conducting an airdrop?
A Seed sale was done and tokens were subjected to vesting. Some Tokens were also airdropped and emission was done through farming after that.

• Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?
A small portion of the tokens were sold through a seed sale to raise funds for initial operations.

• Is the token listed on a centralized/decentralized exchange?
Only on decentralized exchanges.

• Is a Smart Contract audit completed? Where can we find this information?
Yes - https://github.com/ApeAudits1/Smart-Contract-Audits/blob/main/Shibance.pdf

**Comment by Cryptocool1** [comment]
Hello,
please create new PR when CMC listing will be ready.
make sure to mention this PR, so that we can see that fee has been paid already here.

**Pull request closed without merging**
