### PR TITLE
Add PLNT logo and info

### PR DESCRIPTION
**Pull request by xpace-ai**
Pull request to add Xpace PLNT for Binance Smart Chain.
Logo and information added.

### CODE REVIEW

**Comment by Iamdeadlyz** [comment]
As per our policy, brand new tokens are not included. There is a minimum requirement of 2500 holder addresses and 5000 transactions (airdropped tokens excluded) in order to filter out scam tokens. See the criteria at (mentioned in the first message by the bot): https://community.trustwallet.com/t/how-to-submit-a-token-logo/3863#how-to-get-approved

This token has below-limit usage yet. This pull request will be put on hold. Please come back to us when all criteria are met.
https://bscscan.com/token/0x3abfc084a54e5f4e23196e1b9a9c48c3b3021519 (161, 20767)

**Comment by xpace-ai** [comment]
> As per our policy, brand new tokens are not included. There is a minimum requirement of 2500 holder addresses and 5000 transactions (airdropped tokens excluded) in order to filter out scam tokens. See the criteria at (mentioned in the first message by the bot): https://community.trustwallet.com/t/how-to-submit-a-token-logo/3863#how-to-get-approved
> 
> This token has below-limit usage yet. This pull request will be put on hold. Please come back to us when all criteria are met.
> https://bscscan.com/token/0x3abfc084a54e5f4e23196e1b9a9c48c3b3021519 (161, 20767) 2̶5̶5̶9̶,̶ ̶2̶3̶1̶6̶5̶

Hi! Would you check if we know meet the criteria? Thanks!

**Comment by xpace-ai** [comment]
> As per our policy, brand new tokens are not included. There is a minimum requirement of 2500 holder addresses and 5000 transactions (airdropped tokens excluded) in order to filter out scam tokens. See the criteria at (mentioned in the first message by the bot): https://community.trustwallet.com/t/how-to-submit-a-token-logo/3863#how-to-get-approved
> 
> This token has below-limit usage yet. This pull request will be put on hold. Please come back to us when all criteria are met.
> https://bscscan.com/token/0x3abfc084a54e5f4e23196e1b9a9c48c3b3021519 (161, 20767) 2̶5̶5̶9̶,̶ ̶2̶3̶1̶6̶5̶

I think we now meet criteria. Please Check

**Comment by Iamdeadlyz** [comment]
Currently: 125, 25663 (`2̶4̶8̶6̶,̶ ̶2̶8̶0̶2̶5̶`)

Please read https://community.trustwallet.com/t/how-to-submit-a-token-logo/3863#how-to-get-approved

**Comment by catenocrypt** [comment]
Token Circulation:  2467 holder addresses, 28336 transfers.
https://bscscan.com/token/0x3abfc084a54e5f4e23196e1b9a9c48c3b3021519

**Comment by catenocrypt** [comment]
Contract folder is not in checksum folder.

**Pull request merged**
