### PR TITLE
Revert "Add Monbase Info and Logo (#28028)"

### PR DESCRIPTION
**Pull request by Monbase**
logo png
[info.json.json](https://github.com/trustwallet/assets/files/15079954/info.json.json)

### CODE REVIEW

**Comment by Cryptocool1** [comment]
Hello, why are you trying to delete your token?

**Comment by Monbase** [comment]
This is an misunderstanding. I'm not trying to delete my token

As you can see in PR #28028, the info.json file or the info of my token has
not been updated due to the tag "lauchpad" is not allowed.
Therefore I'm trying to upload the new info.json file without creating a
new PR.

Please kindly update the info.json file, remove the "launchpad" tag and
update our token information.

We tried so hard this far not to just delete our token that easily.

Thank you so much for your time and consideration.



Vào Th 4, 24 thg 4, 2024 vào lúc 01:08 CryptoA ***@***.***>
đã viết:

**Comment by Monbase** [comment]
PR https://github.com/trustwallet/assets/pull/27811
Already paid with this pr
Kindly reuse the fee in this pr instead

**Comment by Monbase** [comment]
@Cryptocool1 Hi
With PR 27811 and PR 28028, we wanted to add the token INFO and LOGO. But in PR 28028, only the token LOGO got added , I don't know why. 
Please add both the token INFO and LOGO for us.

**Pull request closed without merging**
