### PR TITLE
Add TENDIE logo and information

### PR DESCRIPTION
**Pull request by spikeleetendieswap**
Adding TENDIE logo and information.

### CODE REVIEW

**Comment by Cryptocool1** [comment]
correction needed:
Contract is not in checksum format, should be 0x9853A30C69474BeD37595F9B149ad634b5c323d9

**Review by spikeleetendieswap — COMMENTED** [review]
The informaton and the token icon are correct

**Review by spikeleetendieswap — COMMENTED** [review]
Modified

**Review by spikeleetendieswap — COMMENTED** [review]
Modified the bscscan address

**Review by spikeleetendieswap — COMMENTED** [review]
Back to the original

**Review by spikeleetendieswap — COMMENTED** [review]
Change id to 0x9853A30C69474BeD37595F9B149ad634b5c323d9

**Review by spikeleetendieswap — COMMENTED** [review]
Adding modifications

**Comment by spikeleetendieswap** [comment]
> correction needed:
> Contract is not in checksum format, should be 0x9853A30C69474BeD37595F9B149ad634b5c323d9

How do I change the contract?

**Comment by Cryptocool1** [comment]
If you can't rename files in the PR, you may open a new PR. Make sure to mention this PR, so that we can see that fee has been paid already here.

**Review by spikeleetendieswap — COMMENTED** [review]
These files have the correct contract in checksum format

**Review by spikeleetendieswap — COMMENTED** [review]
With the id changed

**Comment by spikeleetendieswap** [comment]
> If you can't rename files in the PR, you may open a new PR. Make sure to mention this PR, so that we can see that fee has been paid already here.

I hope now is good. Thank you very much for your help!!

**Pull request merged**
