### PR TITLE
Add NSFW Info and Logo

### PR DESCRIPTION
**Pull request by xxxNifty**
Adding NSFW Info and Logo

### CODE REVIEW

**Comment by Cryptocool1** [comment]
Submission looks good. awaiting fee payment.

**Comment by Cryptocool1** [comment]
> We might be changing the logo. I am assuming there is another cost for updating the logo, right?
> […](#)

no, 250 TWT or 2 BNB is also accepted

**Comment by xxxNifty** [comment]
We just sent the payment

**Comment by xxxNifty** [comment]
We had to migrate our contract. How do we update the contract address for
the logo that is already active?

Thank you.

**Comment by xxxNifty** [comment]
We had a contract migration, how do we update the contract address?

**Comment by Cryptocool1** [comment]
> We had a contract migration, how do we update the contract address?

you need to create new PR

**Pull request merged**
