### PR TITLE
1002992

### PR DESCRIPTION
**Pull request by elbernn**

### CODE REVIEW

**Comment by catenocrypt** [comment]
Corrections needed:  2 files are needed per token, named exactly:
`blockchains/tron/<TOKENID>/logo.png` 
`blockchains/tron/<TOKENID>/info.json` 

Please rename/correct file names.

image

**Review by elbernn — COMMENTED** [review]
Update GrafenoCoin GFNC

**Comment by elbernn** [comment]
https://github.com/trustwallet/assets/pull/6298
https://github.com/trustwallet/assets/pull/6289 
How to do, payment was accepted in one more data accepted in another?

**Comment by elbernn** [comment]
https://github.com/trustwallet/assets/pull/6289
https://github.com/trustwallet/assets/pull/6298

How to do it now, payment accepted in one order and status accepted in the other order.

**Review by elbernn — COMMENTED** [review]
Update

**Comment by catenocrypt** [comment]
Please remove these files:
- blockchains/tron/assets/1002992.png
- blockchains/tron/assets/TXQtSZEM33FpMV6CSNc77Yu822QGxUMXkn/gfncash.png

**Comment by catenocrypt** [comment]
Closing in favor of #6298 ; fee from here considered to that one.

**Pull request closed without merging**
