### PR TITLE
Add files via upload

### PR DESCRIPTION
**Pull request by IncomeIslandMetaverse**
Hi there,

We paid for this a while ago before we knew about the criteria.
We have since been listed on cmc, coingecko etc and have passed kyc with solidproof.io
We are also a reigstered LLC

Any chance of getting the logo added now? It's been on hold for 3 months and we were new when we applied, were not an LLC and had not done KYC.

Please advise
Regards
Lee Greenfield 

On 19/09/2021 01:14 CryptoA ***@***.***> wrote:
As per our policy, brand new tokens are not included, there is a minimum requirement of 5000 holder addresses and 10000 transactions, in order to filter out scam tokens.See the criteria at (mentioned in the first message by the bot): https://community.trustwallet.com/t/how-to-submit-a-token-logo/3863).
on hold for now
—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.Triage notifications on the go with GitHub Mobile for iOS or Android.

Originally posted by @IncomeIsland in #13731 (comment)

### CODE REVIEW

**Comment by IncomeIslandMetaverse** [comment]
Paid for - old application #13731

**Comment by IncomeIslandMetaverse** [comment]
[state-filing-Income Island LLC 6426637.pdf](https://github.com/trustwallet/assets/files/7715249/state-filing-Income.Island.LLC.6426637.pdf)

**Comment by cryptomanz** [comment]
Do you have smart contract audit?

**Comment by IncomeIsland** [comment]
Yes, we have two already done on our website incomeisland.org and we've just inquired with certik to get one done with them
  
  
   
    On 14/12/2021 23:32 Nazar ***@***.***> wrote:
   
   
    
   
   
    
   
   
   Do you have smart contract audit?

**Comment by Cryptocool1** [comment]
As per our policy, brand new tokens are not included, there is a minimum requirement of 10,000 holder addresses and 20,000 transactions, in order to filter out scam tokens.
See the criteria at : https://developer.trustwallet.com/assets/requirements .

**Comment by Cryptocool1** [comment]
Please come back to us when all criteria are met.
When creating a new PR make sure to mention this PR, so that we can see that fee has been paid already here.

**Pull request closed without merging**
