### PR TITLE
Add STRIKE logo $ Info

### PR DESCRIPTION
**Pull request by Forgone13**
Add STRIKE LOGO & INFO

### CODE REVIEW

**Comment by Forgone13** [comment]
> Token check: Errors found!
> 
> No token files found. If you try to add/modify a token, check the name and location of your files! Logo file must be named exactly 'logo.png'. If you are not adding a token, ignore this message. (2 files in the PR)

**Comment by Forgone13** [comment]
updated name of logo.png & info.json

**Comment by Cryptocool1** [comment]
Hello,
can you delete all unnecessary files?

**Comment by catenocrypt** [comment]
Merged master, no new logo found.  Closing.

Please follow documentation:  https://community.trustwallet.com/t/how-to-submit-a-token-logo/3863 
You may want to try our Assets app (in beta);  close this PR; go to https://assets.trustwallet.com, log on with Github, enter contract ID, logo and some additional info, and it will create a PR for you.  See  https://community.trustwallet.com/t/how-to-submit-a-token-logo-using-assets-app/82957

**Pull request closed without merging**
