### PR TITLE
Add Alchemy（ACH) (BEP20)

### PR DESCRIPTION
**Pull request by thinkbankcoin**
Adding info for BEP20 token 'Alchemy（ACH)'.

PR created by <a href="https://assets.trustwallet.com">TW Assets Management</a>

### CODE REVIEW

**Comment by thinkbankcoin** [comment]
> Adding info for BEP20 token 'Alchemy（ACH)'.
> 
> PR created by [TW Assets Management](https://assets.trustwallet.com)

Do I need to make a donation after the audit?

**Comment by thinkbankcoin** [comment]
> > Adding info for BEP20 token 'Alchemy（ACH)'.
> > PR created by [TW Assets Management](https://assets.trustwallet.com)
> 
> Do I need to make a donation after the audit?



> > Adding info for BEP20 token 'Alchemy（ACH)'.
> > PR created by [TW Assets Management](https://assets.trustwallet.com)
> 
> Do I need to make a donation after the audit?

Or do you need to make a donation before you can review it? 
Please help me!!!Thank you very much for your hard-working volunteers.

**Comment by thinkbankcoin** [comment]
> Adding info for BEP20 token 'Alchemy（ACH)'.
> 
> PR created by [TW Assets Management](https://assets.trustwallet.com)

Do I need to make a donation after the audit?
Or do you need to make a donation before you can review it?
Please help me!!!Thank you very much for your hard-working volunteers.

**Comment by Cryptocool1** [comment]
hello
• What is the purpose of this token? How will it benefit Trust Wallet users?
 • How is the token being distributed? Are you conducting an airdrop?
 • Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?
 • Is the token listed on a centralized/decentralized exchange?
 • Is a Smart Contract audit completed? Where can we find this information?

**Comment by thinkbankcoin** [comment]
> hello • What is the purpose of this token? How will it benefit Trust Wallet users? • How is the token being distributed? Are you conducting an airdrop? • Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale? • Is the token listed on a centralized/decentralized exchange? • Is a Smart Contract audit completed? Where can we find this information?

**Comment by thinkbankcoin** [comment]
> 

Can I donate now? Is the token I applied for qualified?

**Comment by Cryptocool1** [comment]
> Can I donate now? Is the token I applied for qualified?

Can you answer the questions I asked before?

**Comment by thinkbankcoin** [comment]
> Adding info for BEP20 token 'Alchemy（ACH)'.
> 
> PR created by [TW Assets Management](https://assets.trustwallet.com)



> > Can I donate now? Is the token I applied for qualified?
> 
> Can you answer the questions I asked before?



> 

OK, I'm collecting information on these questions and writing answers to them. I will reply to your questions soon after completion.

**Comment by thinkbankcoin** [comment]
> hello • What is the purpose of this token? How will it benefit Trust Wallet users? • How is the token being distributed? Are you conducting an airdrop? • Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale? • Is the token listed on a centralized/decentralized exchange? • Is a Smart Contract audit completed? Where can we find this information?

• What is the purpose of this token? How will it benefit Trust Wallet users?

Alchemy Pay's ACH token is used for Incentivising rewards for transactions for both merchants and users. These users will be able to use Trust Wallet to access Alchemy Pay's services, including for governance, transaction fees, and rewards, and pledging:
+ Transaction fees (or "gas fees") - fees for transactions, investments, processing, are payable either in the local fiat currency or ACH. Opting to pay for fees in ACH will result in various fee discounts depending on terms and conditions for the participants.
+ Rewards - use of the network will be rewarded with distribution of ACH in some cases. Enterprises such as financial institutions, payment companies, e-commerce platforms, and developers are the primary use case builders, and earn enterprise transaction rewards at rates negotiated based on network size and transaction volume. Consumer transaction rewards are earned through spending rebates, and other consumer-targeted payment solutions within the Alchemy Pay network. 
+ Pledging - to join the network, merchant partners purchase a specified amount of the ACH token and ‘pledge’ it. This means that while using the network, partners lock up funds which can be returned if they choose to withdraw.
+ Governance - in the future we aim to use the token as a means of governance for token holders. At this time though, our project is still too nascent to offer significant decision-making to our community.

**Comment by thinkbankcoin** [comment]
> hello • What is the purpose of this token? How will it benefit Trust Wallet users? • How is the token being distributed? Are you conducting an airdrop? • Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale? • Is the token listed on a centralized/decentralized exchange? • Is a Smart Contract audit completed? Where can we find this information?

• How is the token being distributed? 
  Are you conducting an airdrop?

ACH token has been distributed since 2020 to merchants and users of Alchemy Pay payment system as a form of incentives to drive crypto payments. Alchemy Pay has conducted airdrops from time to time to its community as part of its promotional efforts.

• Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?

- ACH did not conduct ICO/IEO/IDO. It was sold in private sale (seed & private rounds) in 2020.

• Is the token listed on a centralized/decentralized exchange?

Yes, ACH is listed on major CEX such as Binance, Coinbase, Huobi, Coinone and more. ACH is also listed on major DEX such as UniSwap, SushiSwap and PancakeSwap

• Is a Smart Contract audit completed? Where can we find this information?

Yes - https://drive.google.com/file/d/1HTbnpve30kw9RdFEi3MZR44mwuq3dRSQ/view?usp=sharing

**Comment by thinkbankcoin** [comment]
> This PR is being closed due to inactivity. If you wish to continue, please have us reopen the PR before sending your payment, or just create a new one. Do NOT send payments for closed PR, as the fee may by lost!

Can I make a donation now? 
Can you reopen this PR for me?

**Pull request closed without merging**
