### PR TITLE
Add DRAC Network (DRAC) (ERC20)

### PR DESCRIPTION
**Pull request by DRAC-Network**
Adding info for ERC20 token 'DRAC Network (DRAC)'.

PR created by <a href="https://assets.trustwallet.com">TW Assets Management</a>

### CODE REVIEW

**Comment by DRAC-Network** [comment]
We are DRAC public chain tokens. We already have over 10,000 holders on our bsc chain. We have previously been verified by you. Now we are going to add the Ethereum token logo. We have added ETH DRAC cross-chain token.

BSC token ：https://bscscan.com/token/0x123458C167a371250d325Bd8B1ffF12C8AF692A7
BSC chain token application record：https://github.com/trustwallet/assets/pull/22046
ETH DRAC Contract audit link：https://beosin.com/audits/DRAC_202307111530.pdf

**Comment by Cryptocool1** [comment]
Hello, your ERC20 token should be verified on CMC.

**Comment by DRAC-Network** [comment]
We are DRAC public chain tokens. We already have over 10,000 holders on our bsc chain. We have previously been verified by you. Now we are going to add the Ethereum token logo. We have added ETH DRAC cross-chain token.

BSC token ：https://bscscan.com/token/0x123458C167a371250d325Bd8B1ffF12C8AF692A7
BSC chain token application record：https://github.com/trustwallet/assets/pull/22046
ETH DRAC Contract audit link：https://beosin.com/audits/DRAC_202307111530.pdf

**Comment by DRAC-Network** [comment]
> Hello, your ERC20 token should be verified on CMC.

The application has been submitted and I will get back to you once it is approved.

**Comment by DRAC-Network** [comment]
> Hello, your ERC20 token should be verified on CMC.

Hello, we have been included by CMC, please review~

**Pull request merged**
