### PR TITLE
Add Kylin logo

### PR DESCRIPTION
**Pull request by huaihuaisz**

### CODE REVIEW

**Comment by catenocrypt** [comment]
As per our policy, brand new tokens are not included, there is a minimum requirement of 2500 holder addresses and 5000 transactions, in order to filter out scam tokens.
See the criteria at (mentioned in the first message by the bot): https://community.trustwallet.com/t/how-to-submit-a-token-logo/3863).
This token has below-limit usage yet (840 holders). Putting PR on hold for now. Please come back to us when all criteria are met.  Multi-chain and staking tokens may get special treatment, let us know if this is the case. 

https://etherscan.io/token/0xC4cB5793BD58BaD06bF51FB37717b86B02CBe8A4

**Comment by huaihuaisz** [comment]
> As per our policy, brand new tokens are not included, there is a minimum requirement of 2500 holder addresses and 5000 transactions, in order to filter out scam tokens.
> See the criteria at (mentioned in the first message by the bot): https://community.trustwallet.com/t/how-to-submit-a-token-logo/3863).
> This token has below-limit usage yet (840 holders). Putting PR on hold for now. Please come back to us when all criteria are met. Multi-chain and staking tokens may get special treatment, let us know if this is the case.
> 
> https://etherscan.io/token/0xC4cB5793BD58BaD06bF51FB37717b86B02CBe8A4

Can BNB Tokens be returned?

**Comment by huaihuaisz** [comment]
> As per our policy, brand new tokens are not included, there is a minimum requirement of 2500 holder addresses and 5000 transactions, in order to filter out scam tokens.
> See the criteria at (mentioned in the first message by the bot): https://community.trustwallet.com/t/how-to-submit-a-token-logo/3863).
> This token has below-limit usage yet (840 holders). Putting PR on hold for now. Please come back to us when all criteria are met. Multi-chain and staking tokens may get special treatment, let us know if this is the case.
> 
> https://etherscan.io/token/0xC4cB5793BD58BaD06bF51FB37717b86B02CBe8A4

If I don’t apply, can I refund BNB tokens?

**Comment by huaihuaisz** [comment]
> Hi! In order to compensate for the efforts of processing PRs, we kindly ask for a contribution.
> As there is no refund, before paying the fee, make sure new tokens fulfill the [acceptance criteria](https://community.trustwallet.com/t/how-to-submit-a-token-logo/3863).
> See also the [PR Fee FAQ](https://developer.trustwallet.com/add_new_asset/pr-fee).
> 
> Please pay **250 TWT** with the memo **5701** to the address `bnb1tqq9llyr3dyjd559dha6z5r5etk3qfwk07m098`.
> Alternatively, 2 BNB is also accepted (same memo & address).
> 
> **QR** code: [Trust](https://api.qrserver.com/v1/create-qr-code/?size=200x200&data=https%3A%2F%2Flink.trustwallet.com%2Fsend%3Fcoin%3D714%26address%3Dbnb1tqq9llyr3dyjd559dha6z5r5etk3qfwk07m098%26amount%3D250%26memo%3D5701) | [other wallet](https://api.qrserver.com/v1/create-qr-code/?size=200x200&data=bnb1tqq9llyr3dyjd559dha6z5r5etk3qfwk07m098%26amount%3D250%26memo%3D5701)
> 
> _Notes_:
> 
> * [Trust Wallet Tokens (TWT)](https://community.trustwallet.com/t/trust-wallet-token-twt/4187) can be obtained through our [Referral Program](https://community.trustwallet.com/t/invite-a-friend-earn-trust-wallet-token-twt/4125) or [from DEXs/exchanges](https://community.trustwallet.com/t/where-to-get-trust-wallet-tokens/76641).
> * New tokens without significant usage are rejected, see criteria mentioned above.
> * One PR should be for a single project; PR's with more than 10 logos will be rejected.
> * Payment evaluation happens automatically, but with a few minutes delay.  When payment is detected, an Accept Review is automatically placed on the PR, which is a condition for merge.
> * Evaluating the PR is done manually, and it is merged only if all conditions are satisfied.
> * TWT-BEP2 is supported (Binance Chain), TWT-BEP20 version on Smart Chain is not.



> As per our policy, brand new tokens are not included, there is a minimum requirement of 2500 holder addresses and 5000 transactions, in order to filter out scam tokens.
> See the criteria at (mentioned in the first message by the bot): https://community.trustwallet.com/t/how-to-submit-a-token-logo/3863).
> This token has below-limit usage yet (840 holders). Putting PR on hold for now. Please come back to us when all criteria are met. Multi-chain and staking tokens may get special treatment, let us know if this is the case.
> 
> https://etherscan.io/token/0xC4cB5793BD58BaD06bF51FB37717b86B02CBe8A4

If I don’t pull requests, can I refund BNB tokens?

**Comment by Iamdeadlyz** [comment]
https://etherscan.io/token/0x67B6D479c7bB412C54e03dCA8E1Bc6740ce6b99C
Holders: 1,238
Tx: 4,502

Since `0x67B6D479c7bB412C54e03dCA8E1Bc6740ce6b99C` is your official token contract, can we remove `0xc401A33329602bcc0D682D4AFa22B8574620679d` in this PR?

**Comment by huaihuaisz** [comment]
> https://etherscan.io/token/0x67B6D479c7bB412C54e03dCA8E1Bc6740ce6b99C
> Holders: 1,238
> Tx: 4,502
> 
> Since `0x67B6D479c7bB412C54e03dCA8E1Bc6740ce6b99C` is your official token contract, can we remove `0xc401A33329602bcc0D682D4AFa22B8574620679d` in this PR?

yes, you can remove 0xc401A33329602bcc0D682D4AFa22B8574620679d in this PR

**Comment by huaihuaisz** [comment]
The holder's address and transactions criteria are met, please continue to review.

https://etherscan.io/token/0x67B6D479c7bB412C54e03dCA8E1Bc6740ce6b99C

**Comment by catenocrypt** [comment]
Please fill in the description field in the info.json files, with a few sentence description of the project (currrenty has value "-").
Circulation OK.

**Comment by huaihuaisz** [comment]
> Please fill in the description field in the info.json files, with a few sentence description of the project (currrenty has value "-").
> Circulation OK.

The description field in the info.json file has been filled.

**Comment by catenocrypt** [comment]
Thanks, but description was filled only in one of the files, please do in the other as well.

**Comment by catenocrypt** [comment]
Submission looks OK

**Pull request merged**
