### PR TITLE
Add Pokmi (BEP20)

### PR DESCRIPTION
**Pull request by pokenDev**

### CODE REVIEW

**Comment by cryptomanz** [comment]
Hello,
Can your answer some questions?
• What is the purpose of this token? How will it benefit Trust Wallet users?
 • How is the token being distributed? Are you conducting an airdrop?
 • Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?
 • Is the token listed on a centralized/decentralized exchange?
 • Is a Smart Contract audit completed? Where can we find this information?

**Comment by pokenDev** [comment]
• What is the purpose of this token? How will it benefit Trust Wallet users?
- The $PKN provides financial, technological and legal infrastructure for creators. Thanks to our crypto you are directly supporting content creators by offering them a specific framework for an activity that is under attack from all sides by the banking world.
Our technological edge allows us to position the $PKN as a cross-platform payment method. Pokmi is and will always be an NFT vertical of uncensored creativity for creators and users alike. 

How is the token being distributed? Are you conducting an airdrop?
- We had an ICO for the token, yes through an airdrop. 

• Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?
- ICO : 8500 investors - 1,5 Billion PKN sold for 10,7M$ over 3 rounds in 3 weeks last July.
- 21/09 DEX Listing (Pancake Swap an Uniswap) 
- Soon on CEX (in discussion) 

• Is the token listed on a centralized/decentralized exchange? 
- Both since the 21/09 

• Is a Smart Contract audit completed? Where can we find this information?
- Yes, it was audited by tech rate, report can be found at [https://github.com/TechRate/Smart-Contract-Audits/blob/main/Poken.pdf](https://github.com/TechRate/Smart-Contract-Audits/blob/main/Poken.pdf)

**Comment by cryptomanz** [comment]
Hello,
Please follow the rules for adding tokens, your logo should be a full screen 256x256.
Exemple:
https://community.trustwallet.com/t/how-to-submit-a-token-logo/3863

**Comment by pokenDev** [comment]
The repository readme indicated it can be upto a maximum of 512x512p, and our logo is fitting to that requirement.

**Comment by pokenDev** [comment]
Hi @cryptomanz and @cryptocool1,

There was a small issue with the logo image, so we want to update it. 
I have opened a new PR #14110  for the same. 

Can you please approve?

**Pull request merged**
