### PR TITLE
Add SMD Coin (BEP20)

### PR DESCRIPTION
**Pull request by Shyamthakur33**
Adding info for BEP20 token 'SMD Coin'.

PR created by <a href="https://assets.trustwallet.com">TW Assets Management</a>

### CODE REVIEW

**Comment by cryptomanz** [comment]
Hello,
Can your answer some questions?
• What is the purpose of this token? How will it benefit Trust Wallet users?
• How is the token being distributed? Are you conducting an airdrop?
• Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?
• Is the token listed on a centralized/decentralized exchange?
• Is a Smart Contract audit completed? Where can we find this information?

**Comment by Shyamthakur33** [comment]
• What is the purpose of this token? How will it benefit Trust Wallet users?  
SMD COIN is the world’s first integrated platform, providing Coins Staking, Yield Farming and Self-Holding. SMD COIN provides customers with decentralized farming services, personalized financial solutions, and a variety of interest models and earning opportunities. we are coming up with our own exchange with multiple coins along with SMD COIN, our main aim is to reduce the trading fee for trading and allow users to trade user-friendly without any difficulty.  
SMD Coin has a mission is to provide a user-friendly digital platform where we can provide smart contracts, exchanges, swaps, coins staking to both novice and experienced investors. We are the leading staking service provider for blockchain projects. Join our community to help secure networks and earn rewards. We know to stake. Our infrastructure was built with maximum security and performance at the forefront.

As we are coming up with own swap where user can use SMD Token for STAKE, FARM, Trade, etc and with many more feature. We are coming with our own launch pad where users can buy any token/Coin with SMDCOIN. 
As many users use Trust Wallet for swapping and hold tokens and we focusing to aware to hold tokens over Trust Wallet as it is user-friendly and mobile compatible. 
 
• How is the token being distributed? Are you conducting an airdrop? 
As we started our journey with Pancake Swap users started purchasing over Pancake Swap only. We dint conducted any airdrop to launch our SMD Token. 
 
• Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?  
No, we dint sold any SMD token in ICO or Pre Sale. we did direct listing on exchanges.
 
• Is the token listed on a centralized/decentralized exchange?  
Yes, SMD Token currently trading on Bitmart and Hotbit
 
• Is a Smart Contract audit completed? Where can we find this information? 
Yes, we have done an Audit of our smart contract. you can visit our official website  www.smdcoin.com where you find audit report or you can just the link over here 
https://smdcoin.com/css/techpaper/smdcointech.pdf

**Comment by Shyamthakur33** [comment]
@cryptomanz big thanks for updating the logo. Please check our token value not showing although we given you our cmc and cg links. Please update cmc and cg links so it could show the token value. Thanks

**Comment by Shyamthakur33** [comment]
@cryptomanz @Cryptocool1 Please check, it's been 15 days but our token value not showing in the trust wallet. we already give you CMC and CG links to update and we have a good volume of 300k usd on CMC, please help to check. thanks

**Pull request merged**
