### PR TITLE
Add Beeuda (BEP20)

### PR DESCRIPTION
**Pull request by beeuda**
Adding info for BEP20 token 'Beeuda'.

PR created by <a href="https://assets.trustwallet.com">TW Assets Management</a>

### CODE REVIEW

**Comment by beeuda** [comment]
Our Logo has already been updated on Trustwallet, we only need our Price to reflect as we have now been listed on coinmarketcap

**Comment by beeuda** [comment]
The number for the previous closed ticket is #11451

**Comment by beeuda** [comment]
We already made payment in the old PR #11451

**Comment by Cryptocool1** [comment]
your token merged
Just wait for now

**Comment by beeuda** [comment]
Thank you Price is now showing in Trust wallet

**Pull request closed without merging**
