### PR TITLE
Add BuffedShiba (BEP20)

### PR DESCRIPTION
**Pull request by BuffedShiba**
Adding info for BEP20 token 'BuffedShiba'.

PR created by <a href="https://assets.trustwallet.com">TW Assets Management</a>

### CODE REVIEW

**Comment by cryptomanz** [comment]
ExplorerUrl incorrect, should be standard https://explorer.binance.org/asset/0xD8F61cdECA41dEF1a7923F308a042F678109f54B, not https://bscscan.com/token/0xD8F61cdECA41dEF1a7923F308a042F678109f54B. Please change.

**Comment by Cryptocool1** [comment]
• What is the purpose of this token? How will it benefit Trust Wallet users?
 • How is the token being distributed? Are you conducting an airdrop?
 • Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?
 • Is the token listed on a centralized/decentralized exchange?
 • Is a Smart Contract audit completed? Where can we find this information?

**Comment by BuffedShiba** [comment]
Greetings,

• What is the purpose of this token?
The token is a community driven token that builds on its strong members.

• How will it benefit Trust Wallet users?
A lot of people in our community would really appreciate it if they see the
logo of their favorite token.
Our mods get asked constantly when BuffedShiba will have a logo on
TrustWallet.

• How is the token being distributed?
$BSHIB had a fair launch on PancakeSwap on the 25th October.

• Did you sold the tokens at an Initial Coin Offering (ICO) or a token
presale?
There was no ICO or presale, the total token supply was put into liquidity
on PancakeSwap

• Is the token listed on a centralized/decentralized exchange?
The token is currently traded on PancakeSwap
https://pancakeswap.finance/swap?outputCurrency=0xD8F61cdECA41dEF1a7923F308a042F678109f54B

• Is a Smart Contract audit completed? Where can we find this information?
The token is currently getting audited but there is KYC on the Dev/CEO from
SolidProof
https://github.com/solidproof/kyc-certificates/blob/main/KYC_Certificate_BuffedShiba.png

**Comment by cryptomanz** [comment]
ExplorerUrl incorrect, should be standard https://explorer.binance.org/asset/0xD8F61cdECA41dEF1a7923F308a042F678109f54B, not https://bscscan.com/token/0xD8F61cdECA41dEF1a7923F308a042F678109f54B. Please change.

**Comment by BuffedShiba** [comment]
BuffedShiba is solely a BEP20 token, not a BEP2.

**Comment by Cryptocool1** [comment]
for BEp20 token, correct folder is blockchains/smartchain/assets.

**Comment by Cryptocool1** [comment]
Please come back to us when all criteria are met.
When creating a new PR make sure to mention this PR, so that we can see that fee has been paid already here.

**Comment by Cryptocool1** [comment]
You may want to try our Assets app in beta; go to https://assets.trustwallet.com, log on with Github, enter contract ID, logo and some additional info, and it will create a PR for you.
See https://community.trustwallet.com/t/how-to-submit-a-token-logo-using-assets-app/82957.

**Pull request closed without merging**
