### PR TITLE
[Please remove the LOGO and all INFO on the old contract]

### PR DESCRIPTION
**Pull request by PiriX2P**
[Urgent] Please change LOGO and REMOVE INFO OLD X2P. (PAID) #13593
Please DELETE the old X2P logo and info. 
I have already paid for this to be done together with the upload with new X2P logo. Please delete the old logo as people are still buying through old contract. Thanks in advance!

Dear developers. We have done a token migration from the contract 0x53dcd4ef8e21fe014594a0854c4271a0623b31ec to 0xdfd85305a752d70a07a995fa724ac4ff787ebef2.

Kees had already updated the new token logo and information. He also paid for this, along with the replacement of old contract logo and information. 
I request you to please DELETE the logo of the old contract. Holders are confused which contract to look at and some are even still purchasing through the old contract. 

Thanks in advance, much appreciated.

### CODE REVIEW

**Comment by Satoshiisgod** [comment]
Hello, I have paid 5 BNB with memo 3536 to the address bnb1tqq9llyr3dyjd559dha6z5r5etk3qfwk07m098.

I have created a PR  and paid before.

**Comment by Cryptocool1** [comment]
https://github.com/trustwallet/assets/pull/13644 
your token is abandoned now

**Comment by Cryptocool1** [comment]
https://github.com/trustwallet/assets/blob/master/blockchains/smartchain/assets/0xdfd85305A752d70A07A995Fa724Ac4Ff787EBef2/info.json 
this is the new one

**Comment by Satoshiisgod** [comment]
> https://github.com/trustwallet/assets/blob/master/blockchains/smartchain/assets/0xdfd85305A752d70A07A995Fa724Ac4Ff787EBef2/info.json
> this is the new one

Hello, what's the meaning of this?

**Comment by PiriX2P** [comment]
yes pls delete info of old token and delete logo. thank u

**Comment by Satoshiisgod** [comment]
OK, Done.

I have deleted the old token info and old logo, and then re-submitted a new PR with new info and new logo.

**Pull request closed without merging**
