### PR TITLE
Added Dondi (dondi.io) Logo and JSON info file

### PR DESCRIPTION
**Pull request by glitch46**
We have about 1000 users on our platform. Our liquidity pools open on the 30th and DONDI is required to farm our most incentivized pool. We are hoping to have our logo on Uniswap up before then. 

Thank you!

### CODE REVIEW

**Comment by Iamdeadlyz** [comment]
In accordance with our [disclaimer](https://github.com/trustwallet/assets#disclaimer), your PR is denied due to the following reason:
- A "crowdfunding" platform that is similar to Forsage (matrix scheme)

**Comment by glitch46** [comment]
Hello, 

Thank you for your review. 

Granted, we do have our referral system similar in nature to Forsage, but that's just one element of our very faceted platform. 

We also have a yield farm with 9 pools, an NFT redemption center, games users may play to earn our native token as well as a drip. 

Can you please do your due diligence on our platform and do a better assessment of it? 

Thank you in advance

**Comment by glitch46** [comment]
Hi there I am just following up with this. 

Please let me know what the appeal process is as we are 

If it adds any legitimacy to our project, we were recently published in a reputable publication HedgeTrade. I think the author did a great job providing a great overview if you would like to peruse: 

https://hedgetrade.com/dondi-launches-social-reward-defi-protocol/

**Comment by glitch46** [comment]
@Iamdeadlyz @catenocrypt @zachzwei @rfunduk 

Can you please review this? It's a bit damaging and hurtful to assign our project as "SUSPECT - SCAM" 

I paid my 2 BNB and feel it's only fair to at the very least have your team do some basic research on my project before disparaging it. 

Please review my message above.

**Comment by zachzwei** [comment]
We are unable to approve at this time.
Here is the requirements again for your perusal:
https://community.trustwallet.com/t/how-to-submit-a-token-logo/3863#how-to-get-approved

Please understand that we need are improving the approval requirements to sort out the projects.
Since this is still a new project and the requirements is not met.
This reason is quite questionable:
```We have about 1000 users on our platform. Our liquidity pools open on the 30th and DONDI is required to farm our most incentivized pool. We are hoping to have our logo on Uniswap up before then.
Why would this be a sole reason a token needs to be added right away.

The project has to show potential before we can consider.
We are rigorously checking new and current assets on the app.

**Comment by glitch46** [comment]
@zachzwei 
I understand the need to be scrutinizing and critical of cryptocurrency projects as they become available. Unfortunately, that is the nature of the industry we are in and appreciate your efforts to clear the space of bad actors. 

Thank you for relabeling our project and offering explanation. If you can please check our token now, we are at 685 holders and over >2k transactions after we launched our yield farm over the weekend : 
https://etherscan.io/token/0x45Ed25A237B6AB95cE69aF7555CF8D7A2FfEE67c

**Pull request closed without merging**
