### PR TITLE
Add ShibaDoge (ERC20)

### PR DESCRIPTION
**Pull request by RealShibaDogeDev**
Adding info for ERC20 token 'ShibaDoge'.

PR created by <a href="https://assets.trustwallet.com">TW Assets Management</a>

### CODE REVIEW

**Comment by Cryptocool1** [comment]
• What is the purpose of this token? How will it benefit Trust Wallet users?
 • How is the token being distributed? Are you conducting an airdrop?
 • Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?
 • Is the token listed on a centralized/decentralized exchange?
 • Is a Smart Contract audit completed? Where can we find this information?

**Comment by RealShibaDogeDev** [comment]
Thank you for your prompt response to this!

> • What is the purpose of this token? How will it benefit Trust Wallet users?

ShibaDoge is a community token focused on bringing together the scattered communities of decentralized finance. We are a deflationary token that contains a passive burn with every buy/sell transaction, making the tokens more valuable over time through scarcity. ShibaDoge is an ecosystem looking to expand its utility into various aspects of the decentralized space, which includes the support for NFTs and more.

> • How is the token being distributed? Are you conducting an airdrop? 

There was no airdrop component of our token launch and currently there is no plans for airdrops to the community. The token is exclusively acquired via exchanges such as Uniswap. It is important to note that the current tokenomics are set up so that 5% of every transaction is redistributed to token holders in the form of reflections. 

> • Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale? 

There was no ICO or presale for thee ShibDoge token. It was a fair launch.

> • Is the token listed on a centralized/decentralized exchange? 

The token is currently listed on Uniswap, Hotbit, and XT.com 

> • Is a Smart Contract audit completed? Where can we find this information?

The latest preliminary comments of our Certik Audit can be seen here on our website: https://documents.realshibadoge.com/shibadoge_audit.pdf

**Comment by Cryptocool1** [comment]
your audit is in progress
https://www.certik.com/projects/shibadoge

**Comment by Cryptocool1** [comment]
Please come back to us when all criteria are met. make sure to mention this PR so the fee can be reused

**Comment by RealShibaDogeDev** [comment]
Hello, I have noticed that a few different tokens do not have a completed audit. Some tokens have also submitted token sniffer: https://tokensniffer.com/token/kp92jnaginkv2glganm9d969jzokcu1qvasdu9v35d66hjffhkcxax5nhnvz?r=5983

Please let me know if there is any additional information we can provide since our Certik audit is still being reviewed and all we have is the preliminary responses. We have nearly 14,000 holders.

**Pull request merged**
