### PR TITLE
Safecom Logo

### PR DESCRIPTION
**Pull request by Connecteq**
Safecom Logo#9472

### CODE REVIEW

**Comment by Connecteq** [comment]
I have already paid the fee and was told to open a new request. https://github.com/trustwallet/assets/pull/9472

**Comment by Connecteq** [comment]
I keep changing the request issue but it still come up. I don't know what else to do. What do I need to rename because I change the details in the file.

**Comment by Cryptocool1** [comment]
• I suggest to create a new PR (and mention this one so that fee does not have to be paid again).
 • You may use our Assets app (in beta); close this PR; go to https://assets.trustwallet.com, log on with Github, enter contract ID, logo and some additional info, and it will create a PR for you. See https://community.trustwallet.com/t/how-to-submit-a-token-logo-using-assets-app/82957\

**Comment by Connecteq** [comment]
Can you advice on what need to change. it say rename and change something. I followed the document and still have issue.

**Comment by Cryptocool1** [comment]
> Can you advice on what need to change. it say rename and change something. I followed the document and still have issue.

your contract should be in checksum format,
If you can't rename files in the PR, you may open a new PR. Make sure to mention this PR, so that we can see that fee has been paid already here.

**Pull request closed without merging**
