### PR TITLE
Add VIDT DAO (BEP20)

### PR DESCRIPTION
**Pull request by Sjazzz**
Adding info for BEP20 token 'VIDT DAO'.

PR created by <a href="https://assets.trustwallet.com">TW Assets Management</a>

### CODE REVIEW

**Comment by Cryptocool1** [comment]
As per our policy, brand new tokens are not included, there is a minimum requirement of 10,000 holder addresses and 15,000 transactions, in order to filter out scam tokens.
See the criteria at : https://developer.trustwallet.com/assets/requirements .

**Comment by Sjazzz** [comment]
Please note this is NOT a new token, a token swap is currently in progress for 0xfeF4185594457050cC9c23980d301908FE057Bb1 on Ethereum (PR22569) and 0x3f515f0a8e93f2e2f891ceeb3db4e62e202d7110 on BSC. Therefore the number of holders is currently still very low.
Thank you for your consideration.

**Comment by Sjazzz** [comment]
> As per our policy, brand new tokens are not included, there is a minimum requirement of 10,000 holder addresses and 15,000 transactions, in order to filter out scam tokens. See the criteria at : https://developer.trustwallet.com/assets/requirements .

Please note this is NOT a new token, a token swap is currently in progress for 0xfeF4185594457050cC9c23980d301908FE057Bb1 on Ethereum (PR22569) and 0x3f515f0a8e93f2e2f891ceeb3db4e62e202d7110 on BSC. Therefore the number of holders is currently still very low.
Thank you for your consideration.

**Comment by Sjazzz** [comment]
> As per our policy, brand new tokens are not included, there is a minimum requirement of 10,000 holder addresses and 15,000 transactions, in order to filter out scam tokens. See the criteria at : https://developer.trustwallet.com/assets/requirements .

Please note this is a token upgrade for an existing token with 40K+ holders, we would like to provide clarity to all users.
Please also refer to https://github.com/trustwallet/assets/pull/22569.

Thank you for your attention

**Pull request closed without merging**
