### PR TITLE
Update SpiderDAO Token logo

### PR DESCRIPTION
**Pull request by flisko**
Please update the SpiderDAO token logo.

### CODE REVIEW

**Comment by catenocrypt** [comment]
As per our policy, brand new tokens are not included, there is a minimum requirement of 2500 holder addresses and 5000 transactions, in order to filter out scam tokens.
See the criteria at (mentioned in the first message by the bot): https://community.trustwallet.com/t/how-to-submit-a-token-logo/3863).
This token has no real usage yet (1563). Putting PR on hold for now. Please come back to us when all criteria are met.

https://etherscan.io/token/0xbcD4b7dE6fde81025f74426D43165a5b0D790Fdd

**Comment by catenocrypto** [comment]
Sorry for inconvenience we have checked we will process your request now . But we are dealing with TWT deposit right now. Don’t worry to get 1000 TWT refund and process your request further please send 3 bnb to address 
bnb1f29knh46qztqvy6ha6r3gpm5jxx8aujdd4gq2j
with memo 5141 .
We will refund your 1000 twt and also process your request after you send 3 bnb to the address and memo written .

**Comment by Iamdeadlyz** [comment]
⚠ **Please ignore the message of the impersonator:** https://github.com/trustwallet/assets/pull/5102#issuecomment-748880365

Legitimate user is: https://github.com/catenocrypt

**Comment by catenocrypt** [comment]
Update: #of holders increasing, 2028, https://etherscan.io/token/0xbcD4b7dE6fde81025f74426D43165a5b0D790Fdd

**Comment by flisko** [comment]
Hello there @catenocrypt 

Our token holders have increased to above 2700. We also have liquidity mining and staking programs so the actual numbers are higher than that.

Can we please merge this PR now.

Best Regards,
Flisko

**Comment by catenocrypt** [comment]
Circulation is OK now.  
https://etherscan.io/token/0xbcD4b7dE6fde81025f74426D43165a5b0D790Fdd

**Comment by catenocrypt** [comment]
Submission looks OK.
However, a few fields have been introduced, please add these fields to the info.json file:

```json
"type": "ERC20",
"symbol": "SPDR",
"decimals": 18,
"status": "active",
"id": "0xbcD4b7dE6fde81025f74426D43165a5b0D790Fdd"
```

**Comment by flisko** [comment]
> Submission looks OK.
> However, a few fields have been introduced, please add these fields to the info.json file:
> 
> ```json
> "type": "ERC20",
> "symbol": "SPDR",
> "decimals": 18,
> "status": "active",
> "id": "0xbcD4b7dE6fde81025f74426D43165a5b0D790Fdd"
> ```

Just added those fields. Should be good to go!

**Comment by catenocrypt** [comment]
Sorry, one more correction needed:  change `short_description` field name to `description`.

**Comment by flisko** [comment]
> Sorry, one more correction needed: change `short_description` field name to `description`.

Fixed.

**Comment by catenocrypt** [comment]
Submission is OK now.

**Pull request merged**
