### PR TITLE
Add Binance Smart Chain Girl (ERC20)

### PR DESCRIPTION
**Pull request by takuro020301**
Adding info for ERC20 token 'Binance Smart Chain Girl'.

PR created by <a href="https://assets.trustwallet.com">TW Assets Management</a>

### CODE REVIEW

**Comment by takuro020301** [comment]
This token is It is a token that cross-chains BEP20 BSC GIRL of the following URL to ERC20 token.
https://bscscan.com/token/0x5c6fb802f173dba15e2caada433032b1368af59f

**Comment by takuro020301** [comment]
The number of BSC GIRL holders for BEP20 tokens meets the list convention.

**Comment by takuro020301** [comment]
https://bridge.bscgirl.com/
Screenshot_20210625-130349_Trust Wallet

**Comment by takuro020301** [comment]
https://github.com/trustwallet/assets/pull/8926

**Comment by takuro020301** [comment]
Can you merge the requests?

**Comment by Cryptocool1** [comment]
> Can you merge the requests?

ok. 
awaiting fee payment.

**Pull request merged**
