### PR TITLE
Added Afrostar

### PR DESCRIPTION
**Pull request by niftybrain**
Afrostar Info and Logo added

### CODE REVIEW

**Comment by ramsty** [comment]
can you please add links to your PR
example:https://developer.trustwallet.com/assets/repository_details
description Utility token

**Comment by femigdev** [comment]
Hello, links added, thank you.

You might want to modify or deprecate this documentation - https://community.trustwallet.com/t/how-to-add-the-token-information/3888

Regards

**Comment by ramsty** [comment]
Hi,
Please follow the rules for adding token, your logo should be a full screen
Example:
https://community.trustwallet.com/t/how-to-submit-a-token-logo/3863
137116359-c2bb87b7-239a-4c8d-b54e-4a679c621186

**Comment by femigdev** [comment]
Hello, the guide did not mention anything about making the logo fullscreen. It says 256x256px png with transparent background and the example shown is not fullscreen. Also, the last time I submitted a full screen logo, it did look good within the trustwallet app.

**Comment by ramsty** [comment]
Could you answer some questions?
• What is the purpose of this token? How will it benefit Trust Wallet users?
• How is the token being distributed? Are you conducting an airdrop?
• Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?
• Is the token listed on a centralized/decentralized exchange?
• Is a Smart Contract audit completed? Where can we find this information?

**Comment by femigdev** [comment]
• What is the purpose of this token? How will it benefit Trust Wallet users?
AFROSTAR IS THE UNITED DIGITAL CURRENCY OF AFRICA. It aims to be THE digital currency that is trusted and used across the continent, and a top crypto currency worldwide. The Afrostar ecosystem will provide a range of powerful real world use cases for the Afrostar crypto token. It aims to make trade between African countries easier, aid international fund transfers and promote local investment opportunities. Development work has already started on our crypto exchange and copy trading platform. Initial work has been personally funded by the founders, showing their commitment to the project.

• How is the token being distributed? Are you conducting an airdrop?
10% Private Sale
40% Presale
8% Promotional Airdrops
20% Liquidity Pool
7% Ecosystem/Dev
4% Partnership
5% Burn
3% Business Angel Projects
3% Advisors

• Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale? Yes, via DxSale

• Is the token listed on a centralized/decentralized exchange? Yes, pancake swap - https://pancakeswap.finance/swap#/swap?outputCurrency=0x2F4e9c97aAFFD67D98A640062d90e355B4a1C539

• Is a Smart Contract audit completed? Where can we find this information? Yes - https://github.com/TechRate/Smart-Contract-Audits/blob/main/October/Afrostar%20Full%20Smart%20Contract%20Security%20Audit.pdf

**Pull request merged**
