### PR TITLE
add miniBABYDOGE logo

### PR DESCRIPTION
**Pull request by moontrustdev**

### CODE REVIEW

**Comment by Cryptocool1** [comment]
hello,
• What is the purpose of this token? How will it benefit Trust Wallet users?
 • How is the token being distributed? Are you conducting an airdrop?
 • Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?
 • Is the token listed on a centralized/decentralized exchange?
 • Is a Smart Contract audit completed? Where can we find this information?

**Comment by krazypanda66** [comment]
Hi! 

This token is a Auto BNB Reflection token with a huge use case - revolved around anonymizing transfers - currently in works! We have a market cap around 10million and we have had scores of TrustWallet users asking us to add the logo to TrustWallet so they can see the token in their wallet.  It will benefit TrustWallet users to have this token visible in their wallet so they can track how much they have as well as their reflections!
The token was distributed in a presale as well as in some airdrops, and it is now traded on a DEX (pancakeswap).
Yes, the tokens were sold in a presale via DxSale.
Yes, it is listed on PancakeSwap on BSC.  
This contract is a fork of a previous smart contract, and although our contract is undergoing an audit at the moment, it is not ready yet.  However we can give you the audit of a very similar contract, here: https://github.com/HashEx/public_audits/blob/master/TIKI/TIKI%20report.pdf  

Thanks! We are excited to work with you!

**Comment by moontrustdev** [comment]
> hello,
> • What is the purpose of this token? How will it benefit Trust Wallet users?
> • How is the token being distributed? Are you conducting an airdrop?
> • Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?
> • Is the token listed on a centralized/decentralized exchange?
> • Is a Smart Contract audit completed? Where can we find this information?

Hi!

This token is a Auto BNB Reflection token with a huge use case - revolved around anonymizing transfers - currently in works! We have a market cap around 10million and we have had scores of TrustWallet users asking us to add the logo to TrustWallet so they can see the token in their wallet. It will benefit TrustWallet users to have this token visible in their wallet so they can track how much they have as well as their reflections!
The token was distributed in a presale as well as in some airdrops, and it is now traded on a DEX (pancakeswap).
Yes, the tokens were sold in a presale via DxSale.
Yes, it is listed on PancakeSwap on BSC. The token is also listed on CoinMarketCap and CoinGecko.
This contract is a fork of a previous smart contract, and although our contract is undergoing an audit at the moment, it is not ready yet. However we can give you the audit of a very similar contract, here: https://github.com/HashEx/public_audits/blob/master/TIKI/TIKI%20report.pdf

Thanks! We are excited to work with you!

**Comment by Cryptocool1** [comment]
can you please add links to your PR?
example: https://developer.trustwallet.com/add_new_asset#info-json-contents

**Comment by Cryptocool1** [comment]
Thanks

**Comment by moontrustdev** [comment]
> can you please add links to your PR?
> example: https://developer.trustwallet.com/add_new_asset#info-json-contents

done!

**Pull request merged**
