### PR TITLE
add SGT icon (trustwallet)

### PR DESCRIPTION
**Pull request by DannyDesert**

### CODE REVIEW

**Comment by DannyDesert** [comment]
check payment

**Comment by DannyDesert** [comment]
good bot

**Comment by catenocrypt** [comment]
Name of the logo file must be logo.png, instead of SGT-icon.png .  Please rename.
I renamed and tried to push to SingularDTV/master, but I have no permission.

git mv blockchains/ethereum/assets/0xc4199fB6FFDb30A829614becA030f9042f1c3992/SGT-icon.png blockchains/ethereum/assets/0xc4199fB6FFDb30A829614becA030f9042f1c3992/logo.png

**Comment by zachzwei** [comment]
We cannot merge this due to the size and name of the logo.
Please re-submit and follow these guidelines.
https://community.trustwallet.com/t/how-to-submit-a-new-token-asset/3863

**Comment by DannyDesert** [comment]
Do I need to repay?

**Comment by DannyDesert** [comment]
Okay I fixed the logo issue...we should be good to go.  Thanks

**Comment by DannyDesert** [comment]
> Name of the logo file must be logo.png, instead of SGT-icon.png . Please rename.
> I renamed and tried to push to SingularDTV/master, but I have no permission.
> 
> git mv blockchains/ethereum/assets/0xc4199fB6FFDb30A829614becA030f9042f1c3992/SGT-icon.png blockchains/ethereum/assets/0xc4199fB6FFDb30A829614becA030f9042f1c3992/logo.png

thanks for the help!

**Pull request merged**
