### PR TITLE
Add MECHASHIBA (BEP20)

### PR DESCRIPTION
**Pull request by MechaShibaa**
This PR is being closed due to inactivity. If you wish to continue, please have us reopen the PR before sending your payment, or just create a new one.
Do NOT send payments for closed PR, as the fee may by lost!
  (48 vs. 48 hrs)

### CODE REVIEW

**Comment by cryptomanz** [comment]
can you please add links to your PR?
example: https://developer.trustwallet.com/add_new_asset#info-json-contents

**Comment by Cryptocool1** [comment]
hello,
can you please answer some questions?
• What is the purpose of this token? How will it benefit Trust Wallet users?
 • How is the token being distributed? Are you conducting an airdrop?
 • Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?
 • Is the token listed on a centralized/decentralized exchange?
 • Is a Smart Contract audit completed? Where can we find this information?

**Comment by MechaShibaa** [comment]
Hello,

1. NFT + marketplace, charity and gamification
2. It was launched on 15 may. 30% whitelist airdropped. Remaining
fairlaunch on pancakeswap
3. Presale and then launched on pancakeswap
4. Listed on pancakeswap
5. Techrate free audit is done. Arranging for full audit soon

Thanks

**Comment by cryptomanz** [comment]
Hello,
- Awaiting for smart contract audit.

**Pull request closed without merging**
