### PR TITLE
Adding Logo and Description to Fat Cat Killer

### PR DESCRIPTION
**Pull request by maxvolovikov**
Adding Logo and description to Fat Cat Killer 
fee already paid in this PR: Adding Description/Logo to Fat Cat Killer #21067

### CODE REVIEW

**Comment by maxvolovikov** [comment]
Fee already paid in this PR: Adding Description/Logo to Fat Cat Killer #21067

**Comment by Cryptocool1** [comment]
• What is the purpose of this token? How will it benefit Trust Wallet users?
 • How is the token being distributed? Are you conducting an airdrop?
 • Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?
 • Is the token listed on a centralized/decentralized exchange?
 • Is a Smart Contract audit completed? Where can we find this information?

**Comment by maxvolovikov** [comment]
@Cryptocool1 

- The token is the medium for payment system for hospitality industry. 
- no we are marketing, selling through Pancakeswap and Bitmart, we are also giving some tokens to our team and marketing partners
- no token is self funded completely
- token is listed on PancakeSwap and Bitmart, we are in negotiation with LBank and Coinsbit to list as well
- Yes Smart contract audits available on our website, also team is KYCd

**Comment by Cryptocool1** [comment]
Please send your audit here

**Comment by Cryptocool1** [comment]
Feel free to create new PR once audit ready. Make sure to mention this PR so the fee can be reused

**Comment by maxvolovikov** [comment]
@Cryptocool1 why did you close the PR? the audit has been done already back in May: https://fatcatkiller.com/wp-content/uploads/2022/05/Fat-Cat-Killer-Standard-Smart-Contract-Audit.pdf

**Comment by maxvolovikov** [comment]
it was a weekend i as out of the office...

**Comment by maxvolovikov** [comment]
@Cryptocool1 thank you for re-opening it

**Comment by 09125631619** [comment]
> ### PR Summary
> Files OK: 2
> Token in PR: **BEP20** 0xE0b1EF69BC4AB4173989C1190f0d77A813f3B726
> Symbol: **KILLER** decimals: 9
> Links: [Logo](https://raw.githubusercontent.com/theFCKcoin/assets/master/blockchains/smartchain/assets/0xE0b1EF69BC4AB4173989C1190f0d77A813f3B726/logo.png) [Info](https://raw.githubusercontent.com/theFCKcoin/assets/master/blockchains/smartchain/assets/0xE0b1EF69BC4AB4173989C1190f0d77A813f3B726/info.json) [Website](https://fatcatkiller.com/) [Explorer](https://bscscan.com/token/0xE0b1EF69BC4AB4173989C1190f0d77A813f3B726)
> Tags: defi, deflationary
> Token check error: 
> ❌ number of holders not checked: please, check it manually
> 
> 
> 
> <span style="padding: 5px; background-color: rgb(32,32,32);"></span>
> 
> 
> 
>

**Comment by maxvolovikov** [comment]
@Cryptocool1 anything else i can provide?

**Comment by maxvolovikov** [comment]
@Cryptocool1 it looks like our logo is wrong size? it supposed to be the full size

**Comment by Cryptocool1** [comment]
Hello, you provided small logo

**Comment by maxvolovikov** [comment]
how can i replace it?

**Comment by maxvolovikov** [comment]
> Hello, you provided small logo

Correcting logo size #21794

**Comment by maxvolovikov** [comment]
@Cryptocool1 sorry to bother you, but for some reason our logo was off again . i made a new PR to fix it. 
#21841

**Pull request merged**
