### PR TITLE
Add Marsan Exchange Token (MRS) (ERC20)

### PR DESCRIPTION
**Pull request by MarsanExchange**
Adding info for ERC20 token 'Marsan Exchange Token (MRS)'.

PR created by <a href="https://assets.trustwallet.com">TW Assets Management</a>

### CODE REVIEW

**Comment by MarsanExchange** [comment]
Hey team, any updates on our token ? @catenocrypt @Cryptocool1 @zachzwei

**Comment by Cryptocool1** [comment]
please delete these files :
blockchains/ethereum/assets/0x9af5a20aac8d83230ba68542ba29d132d50cbe08/info.json
blockchains/ethereum/assets/0x9af5a20aac8d83230ba68542ba29d132d50cbe08/logo.png

**Comment by MarsanExchange** [comment]
R

> please delete these files :
> blockchains/ethereum/assets/0x9af5a20aac8d83230ba68542ba29d132d50cbe08/info.json
> blockchains/ethereum/assets/0x9af5a20aac8d83230ba68542ba29d132d50cbe08/logo.png

Repository MarsanExchange:br0610-152058 has been accidently deleted, and since it was part of a forked network we cant recover it. we cant delete those files on our side, is there any way to make the changes on yours? Sorry about the trouble.

**Comment by MarsanExchange** [comment]
Think that those 2 files were from pull request #9820 , which we deleted.

**Comment by Cryptocool1** [comment]
I suggest to create a new PR (and mention this one so that fee does not have to be paid again).
 • You may use our Assets app (in beta); go to https://assets.trustwallet.com, log on with Github, enter contract ID, logo and some additional info, and it will create a PR for you. See https://community.trustwallet.com/t/how-to-submit-a-token-logo-using-assets-app/82957\

**Pull request closed without merging**
