### PR TITLE
Add MMIT LOGO reference #24564 #24733 

### PR DESCRIPTION
**Pull request by dunitech123**
Fees is already payed on https://github.com/trustwallet/assets/pull/24564 memo

### CODE REVIEW

**Comment by dunitech123** [comment]
@Cryptocool1 
Fees has been payed for mmit logo on #24564 memo.
Please do check and give update on it.

**Comment by dunitech123** [comment]
@Cryptocool1 
Have you checked ????

**Comment by dunitech123** [comment]
@merge-fee-bot
5 BNB has been payed on https://github.com/trustwallet/assets/pull/24564
Memo for MMIT logo.

**Comment by dunitech123** [comment]
@cryptomanz1 @Cryptocool1
Have you guys checking at my request ?

**Comment by dunitech123** [comment]
@Cryptocool1 
please give update on it ?

**Comment by Cryptocool1** [comment]
Hello. Are you conducting an airdrop?

**Comment by dunitech123** [comment]
We have already talked about airdrop in previous memo #24564 #24733. Please do check.

**Comment by Cryptocool1** [comment]
I’m asking you for now.

**Comment by dunitech123** [comment]
According to telegram channet chat there was an airdrop. But as a development team we were not aware about that.

**Comment by Cryptocool1** [comment]
I’m not asking about previous airdrop. Did you have an airdrop after that?

**Comment by dunitech123** [comment]
@Cryptocool1
Waiting for the response.....

**Comment by dunitech123** [comment]
@Cryptocool1
Are you still reviewing ?

**Comment by dunitech123** [comment]
> @Cryptocool1 Are you still reviewing ?

?????

**Comment by dunitech123** [comment]
@Cryptocool1 
Thank you

**Pull request merged**
