### PR TITLE
Add Thanos Token Logo

### PR DESCRIPTION
**Pull request by Dotschko**
Please add the Thanos Token logo to Trust Wallet

### CODE REVIEW

**Comment by Dotschko** [comment]
Hi team. This has been paid for. Drop me a message if you have any issues :)

**Comment by catenocrypt** [comment]
Sorry, this PR is invalid, it contains no logo nor info file.
Please fix, otherwise it will be closed.

Documentation:  
https://community.trustwallet.com/t/how-to-submit-a-token-logo/3863
https://community.trustwallet.com/t/how-to-submit-a-token-logo-using-assets-app/82957 

image

**Comment by Dotschko** [comment]
Hi team. I am trying to add a new folder with logog and JSON but get commit failed. Any ideas?

**Comment by Dotschko** [comment]
Updated. Folder should now be correct but still need 2500 holder

**Comment by Iamdeadlyz** [comment]
As per our policy, brand new tokens are not included. There is a minimum requirement of 2500 holder addresses and 5000 transactions (airdropped tokens excluded) in order to filter out scam tokens. See the criteria at (mentioned in the first message by the bot): https://community.trustwallet.com/t/how-to-submit-a-token-logo/3863#how-to-get-approved

This token has below-limit usage yet. This pull request will be put on hold. Please come back to us when all criteria are met. Just comment here so we can re-open. Note: You don't need to pay again.

**Comment by Dotschko** [comment]
Hi team. Our token has just hit 2500. Are you able to reopen this and process?

**Comment by Cryptocool1** [comment]
> Hi team. Our token has just hit 2500. Are you able to reopen this and process?

hello
Id field does not match contract, should be 0x295F2122EbfCC5c38b4Bd33879A37348195b61fb, not 0x295f2122ebfcc5c38b4bd33879a37348195b61fb. Please rename.

**Pull request merged**
