### PR TITLE
add Coinscope token info

### PR DESCRIPTION
**Pull request by apostolidhs**
**Registered company**

Name: AVLOMO ENTERPRISES LTD
Address: Thiseos 7, Strovolos, Nicosia, Cyprus

**Press Release**

https://finance.yahoo.com/news/coinscope-co-launches-own-token-035100695.html

### CODE REVIEW

**Comment by cryptomanz** [comment]
As per our policy, brand new tokens are not included, there is a minimum requirement of 25,000 holder addresses and 50,000 transactions, in order to filter out scam tokens.
See the criteria at : https://developer.trustwallet.com/assets/requirements .

**Comment by cryptomanz** [comment]
Please come back to us when all criteria are met.
When creating a new PR make sure to mention this PR, so that we can see that fee has been paid already here.

**Comment by apostolidhs** [comment]
> Please come back to us when all criteria are met. When creating a new PR make sure to mention this PR, so that we can see that fee has been paid already here.

We have just noticed the raised of the holder's limit.
We understand that you are filtering out the scam projects.
As we mentioned in the PR description, we are a registered company, you can take a look.
Our platform is operating for more than 8 months including many active users.

We are the official Audit partners of PinkSale and we are closing the deal with DxSale.
https://docs.pinksale.finance/important/kyc-and-audit-at-pinksale#audit-partners

As we understand if the PR was created one week ago you would have accepted it.
Do those details cover your acceptance criteria?

**Comment by Cryptocool1** [comment]
> As we understand if the PR was created one week ago you would have accepted it. Do those details cover your acceptance criteria?
 No, we wouldn’t. The criteria was 5k holders, while you have 2667

**Comment by apostolidhs** [comment]
> > As we understand if the PR was created one week ago you would have accepted it. Do those details cover your acceptance criteria?
> > No, we wouldn’t. The criteria was 5k holders, while you have 2667

Thank you, we will reach them soon and we will come back again.

**Pull request closed without merging**
