### PR TITLE
Add aqua icon

### PR DESCRIPTION
**Pull request by ash-greninja-poke**

### CODE REVIEW

**Comment by ash-greninja-poke** [comment]
We’re a real community with over $25 million in TVL and $5 million in liquidity. You told us before that we can just pay the processing fee. Can we do that please many of our users, use trust wallet and are asking us for our token logo and info to be accurate in trust wallet.

**Comment by ash-greninja-poke** [comment]
Thanks, we’re excited to work with Trust Wallet! Please let us know if you have any questions or need anything else from us :)

**Comment by Cryptocool1** [comment]
can you please add links to your PR?
example: https://developer.trustwallet.com/add_new_asset#info-json-contents

**Comment by ash-greninja-poke** [comment]
> can you please add links to your PR?
> example: https://developer.trustwallet.com/add_new_asset#info-json-contents

Is the project docs link will work?

**Comment by ash-greninja-poke** [comment]
https://docs.planetfinance.io/

**Comment by ash-greninja-poke** [comment]
@Cryptocool1

**Pull request merged**
