### PR TITLE
Add BoloToken (BEP20)

### PR DESCRIPTION
**Pull request by BoloToken**
Adding info for BEP20 token 'BoloToken'.

PR created by <a href="https://assets.trustwallet.com">TW Assets Management</a>

### CODE REVIEW

**Comment by BoloToken** [comment]
Dood morning, create this new PR because the previous one was closed due to lack of information, the last PR was the number 23620 (https://github.com/trustwallet/assets/pull/23620).
Previously we lacked the audit, now we did it with one of the companies that were recommended to us.

**Comment by BoloToken** [comment]
@Cryptocool1 @cryptomanz1

**Comment by BoloToken** [comment]
• What is the purpose of this token?
The purpose is to guarantee the totally decentralized monetary exchanges of our economic community.
• How will it benefit Trust Wallet users?
They will have a token to exchange with very low commissions, however our initial objective is not to get more users, we want to strengthen our community. And our members benefit from using high quality, versatile and friendly software like trustwallet.
• How is the token being distributed?
We choose the 1000 members of our community with the largest number of customers, to sell it person to person.
• Are you conducting an airdrop?
no and no airdrop is planned, sales are proportional to the participation of our members and are made person to person.
• Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?
A presale was made and probably others will be made.
• Is the token listed on a centralized/decentralized exchange?
We have created a small liquidity pool on a decentralized exchange, however our goal is per to per exchange.
(pancakeswap).
• Is a Smart Contract audit completed? Where can we find this information?
https://dessertswap.finance/audits/BOLO-Token-BSC-Audit-24625779.pdf

**Comment by Cryptocool1** [comment]
Please send your CoinMarketCap link

**Comment by BoloToken** [comment]
https://poocoin.app/tokens/0xc1da031d459c574163e69e4370b465faf3f5a7cf

The objective of our token is to be a means of exchange between members of our community to strengthen the person-to-person exchange in a decentralized way, we do not want to sell our token to people outside our community, but we do want our members to have a quality experience sending and receiving our token through trustwallet and that is why we are carrying out this process, so that they can see our logo and basic information.

All members understand the functions of the token and likewise accept the risks.

We are in a hostile country, we cannot appear in coinmarketcap, we cannot publish our identities, if you need a KYC we can do it with the commitment that it will not be published in the same way we did with the company that carried out the audit.
This project is our economic alternative and the liquidity pool that we created is only to have a reference price when exchanging for goods and services.

We would appreciate this information being considered.

Thank you.

**Comment by Cryptocool1** [comment]
We require CoinMarketCap listing. Feel free to come back once all criteria are met.
See criteria at: https://developer.trustwallet.com/assets/requirements

**Comment by BoloToken** [comment]
Thank you very much, we will do our best.

**Comment by BoloToken** [comment]
@Cryptocool1 good evening, sorry for the inconvenience in coinmarketcap they suggested us to use this tracker https://coinmarketcap.com/dexscan/bsc/0x18f90b65dac9c22ecea3ec7a0119f691bdc0bef5 would it be possible?

**Pull request closed without merging**
