### PR TITLE
Add MUSDT (ERC20)

### PR DESCRIPTION
**Pull request by mufengorg**
Adding info for ERC20 token 'MUSDT'.

PR created by <a href="https://assets.trustwallet.com">TW Assets Management</a>

### CODE REVIEW

**Comment by Cryptocool1** [comment]
Please create new PR, follow doc https://developer.trustwallet.com/listing-new-assets/requirements
You may want to try our Assets app in beta; go to https://assets.trustwallet.com, log on with Github, enter contract ID, logo and some additional info, and it will create a PR for you.
See https://developer.trustwallet.com/listing-new-assets/repository_details

**Comment by mufengorg** [comment]
The PR I submitted was based on your document. May I ask if there is any problem?

**Comment by Cryptocool1** [comment]
Why are you using USDT logo?

**Comment by mufengorg** [comment]
We are a stable currency on the match chain similar to USDT, named MUSDT.
Do you need to redesign a different logo?

**Comment by Cryptocool1** [comment]
You can see in documentation I sent you that we do not accept tokens with plagiarism

**Comment by Cryptocool1** [comment]
Please see all our requirements here: https://developer.trustwallet.com/listing-new-assets/requirements

**Pull request closed without merging**
