### PR TITLE
Add TokenFi (TOKEN) on ETH and BNB chain

### PR DESCRIPTION
**Pull request by EagleFloki**
Reopening the PR since this one automatically closes in 2 minutes: https://github.com/trustwallet/assets/pull/26667

Please add TokenFi on ETH and BNB chain.
TokenFi Contract:
ETH:
0x4507cEf57C46789eF8d1a19EA45f4216bae2B528

BSC:
0x4507cEf57C46789eF8d1a19EA45f4216bae2B528

website: tokenfi.com

### CODE REVIEW

**Comment by EagleFloki** [comment]
any update legend? @Cryptocool1

**Comment by EagleFloki** [comment]
it should be good to go now @Cryptocool1

**Comment by cryptomanz1** [comment]
• What is the purpose of this token? How will it benefit Trust Wallet users?
 • How is the token being distributed? Are you conducting an airdrop?
 • Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?
 • Is the token listed on a centralized/decentralized exchange?
 • Is a Smart Contract audit completed? Where can we find this information?

**Comment by EagleFloki** [comment]
• What is the purpose of this token? How will it benefit Trust Wallet users?
TokenFi aims to give users all they need to create successful crypto tokens or tokenize an asset in a simple all-in-one platform without writing a single line of code! It will have launchpad, token launcher, RWA tokenization, smart contract auditor and many more proects.
• How is the token being distributed? Are you conducting an airdrop?
Staking pool for Floki tokens: 56%
Liquidity Pool: 10%
Treasury/Development: 22%
Reward/Ecosystem Incentives: 5%
TOKEN Staking Pool: 7%
• Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?
It was fair launch. Launched at 50k mc.
• Is the token listed on a centralized/decentralized exchange?
Uniswap, Pancakeswap, Bybit, Kucoin, Gate.io...
• Is a Smart Contract audit completed? Where can we find this information?
https://skynet.certik.com/projects/tokenfi

@Cryptocool1 @cryptomanz1

**Comment by EagleFloki** [comment]
What are we waiting for? @Cryptocool1 @cryptomanz1

**Comment by EagleFloki** [comment]
I would be appreciated if you at least answer @Cryptocool1 @cryptomanz1 
Our supply is verified on CMC: https://coinmarketcap.com/currencies/tokenfi/
We stayed on trends for days on Dextools, got listed on the biggest exchanges including Binance Futures it still hasn't been updated on Trustwallet.

**Pull request merged**
