### PR TITLE
Adding ZEFU Info (ERC-20) 

### PR DESCRIPTION
**Pull request by n1ghtcoder**

### CODE REVIEW

**Comment by catenocrypt** [comment]
Contract folder is not in checksum format, please fix.

**Review by Iamdeadlyz — CHANGES_REQUESTED** [review]
Please do the following:
> To fix the logo size
- Resize the logo to `256px by 256px`. You can use: https://picresize.com/
> To fix the checksum issue
- Rename the folder to `0xB1e9157c2Fdcc5a856C8DA8b2d89b6C32b3c1229-x`, commit, then push
- Rename it again to `0xB1e9157c2Fdcc5a856C8DA8b2d89b6C32b3c1229`, commit, and push

**Comment by n1ghtcoder** [comment]
@Iamdeadlyz @catenocrypt done, please check :)

**Comment by Iamdeadlyz** [comment]
> @Iamdeadlyz @catenocrypt done, please check :)

You should have renamed the folder, not create a new one. Please follow the steps again.
image

**Comment by n1ghtcoder** [comment]
@Iamdeadlyz @catenocrypt done, please check

**Comment by catenocrypt** [comment]
Folder name is still not in checksum folder.  I can just repeat:

> To fix the checksum issue
- Rename the folder to `0xB1e9157c2Fdcc5a856C8DA8b2d89b6C32b3c1229-x`, commit, then push
- Rename it again to `0xB1e9157c2Fdcc5a856C8DA8b2d89b6C32b3c1229`, commit, and push

**Review by Iamdeadlyz — APPROVED** [review]

**Comment by n1ghtcoder** [comment]
@Iamdeadlyz thank you!

**Pull request merged**
