### PR TITLE
Submit info and Logo for Empire Token

### PR DESCRIPTION
**Pull request by jamel-86**

### CODE REVIEW

**Comment by Cryptocool1** [comment]
As per our policy, brand new tokens are not included, there is a minimum requirement of 2500 holder addresses and 5000 transactions, in order to filter out scam tokens.
See the criteria at (mentioned in the first message by the bot): https://community.trustwallet.com/t/how-to-submit-a-token-logo/3863).

**Comment by jamel-86** [comment]
> As per our policy, brand new tokens are not included, there is a minimum requirement of 2500 holder addresses and 5000 transactions, in order to filter out scam tokens.
> See the criteria at (mentioned in the first message by the bot): https://community.trustwallet.com/t/how-to-submit-a-token-logo/3863).

We are already 2500 holders, how much longer will it take to finalize the logo on Trustwallet?

**Comment by jamel-86** [comment]
Do I require to take any further actions ?

**Comment by Cryptocool1** [comment]
> Do I require to take any further actions ?

can't reach your website "https://empiretoken.world/"

**Comment by jamel-86** [comment]
It's working perfectly fine, both http and secured https, I even pressed your link.

empire_web

**Pull request merged**
