### PR TITLE
Adding Logo and infos ZabakuInu

### PR DESCRIPTION
**Pull request by SalvatoreCampagnese**

### CODE REVIEW

**Comment by SalvatoreCampagnese** [comment]
Hi, any news?

**Comment by SalvatoreCampagnese** [comment]
@catenocrypt @Cryptocool1 @zachzwei 
let me know if any problem occurred.. we already paid

**Comment by Cryptocool1** [comment]
hello,
can you please create new PR without BUSD token in your files?
You may want to try our new Assets app in beta; go to https://assets.trustwallet.com, log on with Github, enter contract ID, logo and some additional info, and it will create a PR for you.
See https://community.trustwallet.com/t/how-to-submit-a-token-logo-using-assets-app/82957.
You don't need to pay one more time)

**Comment by SalvatoreCampagnese** [comment]
https://github.com/trustwallet/assets/pull/9282 Done, thanks

**Comment by SalvatoreCampagnese** [comment]
Hi, did you accepred the merge request? @Cryptocool1 we cannot see the logo yet

**Pull request closed without merging**
