### PR TITLE
Add Syncus (SYNC) (ERC20)

### PR DESCRIPTION
**Pull request by LetHimDev**
Adding info for ERC20 token 'Syncus (SYNC)'.

PR created by <a href="https://assets.trustwallet.com">TW Assets Management</a>

### CODE REVIEW

**Comment by LetHimDev** [comment]
Gm, this is our second PR. First one was not accepted due to the minimum requirement of 10,000 holders.

https://github.com/trustwallet/assets/pull/27200

**Comment by Cryptocool1** [comment]
Hello,
• What is the purpose of this token? How will it benefit Trust Wallet users?
 • How is the token being distributed? Are you conducting an airdrop?
 • Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?
 • Is the token listed on a centralized/decentralized exchange?
 • Is a Smart Contract audit completed? Where can we find this information?

**Comment by LetHimDev** [comment]
• Syncus DAO is a treasury-backed DeFi protocol designed for long term holders by driving sustainable growth. The SYNC token serves as the backbone of the Syncus ecosystem. It enables holders to stake for SYNC rewards and to participate in future governance, the Syncus DAO. With SYNC it is also possible to access liquidity markets, where liquidity can be borrowed against SYNC. Syncus DAO rewards stakers consistently, irrespective of token volatility, and offers a range of financial products accessible to both crypto-savvy individuals and mainstream users. The project aims to redefine success in DeFi by prioritising sustainability and accessibility for all users.

• 50% was sold in a public sale, 50% was used for liquidity. Meanwhile the treasury accumulates SYNC from taxes and rewards stakers. CEXs and KOLs are doing marketing campaigns with SYNC.

• 50% of the supply (2B SYNC) was sold in a public sale

• DEX: Uniswap and Syncswap
CEX: MEXC, DigiFinex, CoinW, BitMart, AscendEx, Poloniex, LBank, XT.com

• The token contract is a standard ERC-20 and the liquidity market is forked from Aave.

**Comment by Cryptocool1** [comment]
We require smart contract audit from reputable companies, please refer to our documentation for listing an asset. 
Feel free to create new Pull Request once audit is done. Make sure to mention this PR so the fee can be reused.

**Pull request closed without merging**
