### PR TITLE
Add dexSHARE (BEP20)

### PR DESCRIPTION
**Pull request by dexfi-com**
Adding info for BEP20 token 'dexSHARE'.

PR created by <a href="https://assets.trustwallet.com">TW Assets Management</a>

### CODE REVIEW

**Comment by dexIRA** [comment]
## **dexSHARE**
- BEP20: 0xf4914E6D97a75f014AcFcF4072f11be5CfFc4cA6
[**www.dexfinance.com**](https://www.dexfinance.com) | [**app.dexfinance.com**](https://app.dexfinance.com)

---
## **PAYMENT**:

**Payment** sent via **TxID**: [*5A24627694D3B5615CB111B5B30502524F8E74A2CE7B39347F7FA6D463075D68*](https://explorer.bnbchain.org/tx/5A24627694D3B5615CB111B5B30502524F8E74A2CE7B39347F7FA6D463075D68)

---
### **TOTAL HOLDERS REQUIREMENT MET**:

We currently meet the token holders requirement:
[https://coinmarketcap.com/currencies/dexshare/historical-data/](https://coinmarketcap.com/currencies/dexshare/historical-data/)

@cryptomanz1 @catenocrypt @Iamdeadlyz @covain

**dexSHARE holders in Farms** - Due to the **nature of staking**, our total holders amount is actually **much higher**. Most of our [dapp's](https://app.dexfinance.com) users are **staking in our** [**farms**](https://app.dexfinance.com/farm), and the Dexfinance **TVL** is currently over $14,000,000.


---
### **ADDITIONAL NOTES**:

TrustWallet previously approved our last token, dexIRA ([**#13456**](https://github.com/trustwallet/assets/pull/13456)). And since then, our team has also successfully **completed** a private audit of personal info on [Solidproof](https://github.com/solidproof/kyc-certificates/blob/main/KYC_Certificate_dexIRA.png). And our new contracts have **passed** [**several audits**](https://www.dexfinance.com/audits/) all of which are available on our website [**here**](https://www.dexfinance.com/audits/).

dexSHARE is **currently** listed on [**CoinMarketCap**](https://coinmarketcap.com/currencies/dexshare/), [**CoinGecko**](https://www.coingecko.com/en/coins/dexshare), [**Coinbase**](https://www.coinbase.com/price/dexshare), [**Binance**](https://www.binance.com/en/price/dexshare), [**Yahoo**](https://finance.yahoo.com/quote/DEXSHARE-USD), [etc](https://crypto.com/price/dexshare). and has **new articles** currently published  on [**Bloomberg**](https://www.bloomberg.com/press-releases/2022-02-11/dex-finance-a-new-gen-decentralized-ecosystem-designed-to-empower-crypto-investors), [**Yahoo News**](https://finance.yahoo.com/news/dex-finance-launches-aims-providing-100400090.html), [**Nasdaq**](https://www.nasdaq.com/press-release/dex-finance-a-new-gen-decentralized-ecosystem-designed-to-empower-crypto-investors) and [**Coinspeaker**](https://www.coinspeaker.com/dexira-this-isnt-your-grandfathers-ira/). 

This week, we released the '[**Dex Finance Quarterly Report**](https://medium.com/@DexFinance/dex-finance-quarterly-report-27e64dda46f4)' to our investors, so we're officially ready for TrustWallet again.  Note, all other pertinent details regarding dexSHARE can be found on our website at [**dexfinance.com**](https://www.dexfinance.com).

Please let us know if you have any questions or concerns, (*@dexCEO*),

#### **Thank you**

#### [**dexfinance.com**](https://www.dexfinance.com/)
##### [Website](https://www.dexfinance.com/) | [Telegram](https://t.me/dexfinance) | [Discord](https://discord.com/invite/jAaqVMbhvp) | [Twitter](https://twitter.com/DexFinance) | [Reddit](https://www.reddit.com/r/DexFinance/) | [Medium](https://medium.com/@DexFinance) | [Facebook](https://www.facebook.com/dexIRAtoken) | [Instagram](https://www.instagram.com/dexiratoken/) | [YouTube](https://www.youtube.com/DexFinance) | [LinkedIn](https://www.linkedin.com/company/dexfinance) | [Git](https://github.com/dexira)[Hub](https://github.com/dexfinance-com) | [Email](mailto:info@dexfinance.com)

--

**Comment by Cryptocool1** [comment]
> ## **dexSHARE**
> * BEP20: 0xf4914E6D97a75f014AcFcF4072f11be5CfFc4cA6
>   [**www.dexfinance.com**](https://www.dexfinance.com) | [**app.dexfinance.com**](https://app.dexfinance.com)
> 
> ## **PAYMENT**:
> **Payment** sent via **TxID**: [_5A24627694D3B5615CB111B5B30502524F8E74A2CE7B39347F7FA6D463075D68_](https://explorer.bnbchain.org/tx/5A24627694D3B5615CB111B5B30502524F8E74A2CE7B39347F7FA6D463075D68)
> 
> ### **TOTAL HOLDERS REQUIREMENT MET**:
> We currently meet the token holders requirement: https://coinmarketcap.com/currencies/dexshare/historical-data/
> 
> @cryptomanz1 @catenocrypt @Iamdeadlyz @covain
> 
> **dexSHARE holders in Farms** - Due to the **nature of staking**, our total holders amount is actually **much higher**. Most of our [dapp's](https://app.dexfinance.com) users are **staking in our** [**farms**](https://app.dexfinance.com/farm), and the Dexfinance **TVL** is currently over $14,000,000.
> 
> ### **ADDITIONAL NOTES**:
> TrustWallet previously approved our last token, dexIRA ([**#13456**](https://github.com/trustwallet/assets/pull/13456)). And since then, our team has also successfully **completed** a private audit of personal info on [Solidproof](https://github.com/solidproof/kyc-certificates/blob/main/KYC_Certificate_dexIRA.png). And our new contracts have **passed** [**several audits**](https://www.dexfinance.com/audits/) all of which are available on our website [**here**](https://www.dexfinance.com/audits/).
> 
> dexSHARE is **currently** listed on [**CoinMarketCap**](https://coinmarketcap.com/currencies/dexshare/), [**CoinGecko**](https://www.coingecko.com/en/coins/dexshare), [**Coinbase**](https://www.coinbase.com/price/dexshare), [**Binance**](https://www.binance.com/en/price/dexshare), [**Yahoo**](https://finance.yahoo.com/quote/DEXSHARE-USD), [etc](https://crypto.com/price/dexshare). and has **new articles** currently published on [**Bloomberg**](https://www.bloomberg.com/press-releases/2022-02-11/dex-finance-a-new-gen-decentralized-ecosystem-designed-to-empower-crypto-investors), [**Yahoo News**](https://finance.yahoo.com/news/dex-finance-launches-aims-providing-100400090.html), [**Nasdaq**](https://www.nasdaq.com/press-release/dex-finance-a-new-gen-decentralized-ecosystem-designed-to-empower-crypto-investors) and [**Coinspeaker**](https://www.coinspeaker.com/dexira-this-isnt-your-grandfathers-ira/).
> 
> This week, we released the '[**Dex Finance Quarterly Report**](https://medium.com/@DexFinance/dex-finance-quarterly-report-27e64dda46f4)' to our investors, so we're officially ready for TrustWallet again. Note, all other pertinent details regarding dexSHARE can be found on our website at [**dexfinance.com**](https://www.dexfinance.com).
> 
> Please let us know if you have any questions or concerns, (_@dexCEO_),
> 
> #### **Thank you**
> #### [**dexfinance.com**](https://www.dexfinance.com/)
> ##### [Website](https://www.dexfinance.com/) | [Telegram](https://t.me/dexfinance) | [Discord](https://discord.com/invite/jAaqVMbhvp) | [Twitter](https://twitter.com/DexFinance) | [Reddit](https://www.reddit.com/r/DexFinance/) | [Medium](https://medium.com/@DexFinance) | [Facebook](https://www.facebook.com/dexIRAtoken) | [Instagram](https://www.instagram.com/dexiratoken/) | [YouTube](https://www.youtube.com/DexFinance) | [LinkedIn](https://www.linkedin.com/company/dexfinance) | [Git](https://github.com/dexira)[Hub](https://github.com/dexfinance-com) | [Email](mailto:info@dexfinance.com)
> -
hello, your token is not listed on Binance
Снимок экрана 2022-08-08 в 08 40 19

**Comment by Cryptocool1** [comment]
thanks for your interest, we will consider to add your token later.

**Comment by dexIRA** [comment]
> thanks for your interest, we will consider to add your token later.

@Cryptocool1 @Iamdeadlyz @covain 

This PR was marked 'Closed', even though the DexFinance tokens were approved by CMC, CG, etc. Furthermore, the tokens and platform was reviewed, approved and graded by Certik. 

For whatever reason, TrustWallet did not accept this PR to be merged... Since then, the dexShare token has been migrated to the new gDex token (on the ARB network). Please refund this payment or provide a solution - as we see no reason for the confusion here. 🙏🏼 Thank you

**Comment by Cryptocool1** [comment]
As per our policy, there is a minimum requirement of 10,000 holder addresses and 15,000 transactions, in order to filter out scam tokens.
See the criteria at : https://developer.trustwallet.com/listing-new-assets/requirements .

**Pull request closed without merging**
