### PR TITLE
changing url for assets api

### PR DESCRIPTION
**Pull request by twkul**

### CODE REVIEW

**Review by vorotech — APPROVED** [review]

**Review by ziljah — COMMENTED** [review]
ok

**Comment by Behiiy** [comment]
Isi

**Comment by Behiiy** [comment]
> ok

f6d4eb4fe081191f2eb9e76e0ef377656b928979

**Comment by Hinaroos67** [comment]
https://github.com/trustwallet/assets/pull/23899#issuecomment-1408216473

**Comment by Blackskar875** [comment]
>

**Pull request merged**
