### PR TITLE
Add MaNEKO (BEP20)

### PR DESCRIPTION
**Pull request by manekofinance**
Adding info for BEP20 token 'MaNEKO'.

PR created by <a href="https://assets.trustwallet.com">TW Assets Management</a>

### CODE REVIEW

**Comment by manekofinance** [comment]
Holders: 12,792 addresses
Transfers: 15,333

**Comment by manekofinance** [comment]
Sorry. What has been done wrong? 
It turned out two folders. One was done through themselves, the second through the service https://assets.trustwallet.com /?. There was a conflict(

**Comment by aaronmillious** [comment]
Need help?
Message Trustwallet instant support team  for quick assistance
had the same issue
But it was resolved immediately
I think you should write to them

https://forms.gle/PLqvZVg9ywEU6ioLA

**Comment by manekofinance** [comment]
Is it possible to resume the token listing and open a branch?

**Pull request closed without merging**
