### PR TITLE
DEUS logo update (logo only)

### PR DESCRIPTION
**Pull request by bi0hazard12**
Hello,

Can we please get our logo updated?
The token already exist in trustwallet and the info too. 

Thank you

### CODE REVIEW

**Comment by catenocrypt** [comment]
Token `0x3b62f3820e0b035cc4ad602dece6d796bc325325` misses info, please add an `info.json` file next to the `logo.png`, with info about the project, of the form:

```json
{
    "name": "Trust Wallet Token",
    "symbol": "TWT",
    "type": "BEP2",
    "decimals": 8,
    "description": "Utility token to increase adoption of cryptocurrency.",
    "website": "https://trustwallet.com",
    "explorer": "https://explorer.binance.org/asset/TWT-8C2",
    "source_code": "https://github.com/trustwallet/",
    "white_paper": "",
    "socials": [
        {
            "name": "Twitter",
            "url": "https://twitter.com/trustwalletapp",
            "handle": "TrustWalletApp"
        },
        {
            "name": "Reddit",
            "url": "https://reddit.com/r/trustapp",
            "handle": "TrustApp"
        }
    ],
    "research": "https://research.binance.com/en/projects/trustwallet",
    "id": "TWT-8C2"
}
```

**Comment by bi0hazard12** [comment]
> Token `0x3b62f3820e0b035cc4ad602dece6d796bc325325` misses info, please add an `info.json` file next to the `logo.png`, with info about the project, of the form:
> 
> ```json
> {
>     "name": "Trust Wallet Token",
>     "symbol": "TWT",
>     "type": "BEP2",
>     "decimals": 8,
>     "description": "Utility token to increase adoption of cryptocurrency.",
>     "website": "https://trustwallet.com",
>     "explorer": "https://explorer.binance.org/asset/TWT-8C2",
>     "source_code": "https://github.com/trustwallet/",
>     "white_paper": "",
>     "socials": [
>         {
>             "name": "Twitter",
>             "url": "https://twitter.com/trustwalletapp",
>             "handle": "TrustWalletApp"
>         },
>         {
>             "name": "Reddit",
>             "url": "https://reddit.com/r/trustapp",
>             "handle": "TrustApp"
>         }
>     ],
>     "research": "https://research.binance.com/en/projects/trustwallet",
>     "id": "TWT-8C2"
> }
> ```

Hello Catenocrypt,

The token already exist in trustwallet with the info already there. We just need to update the logo.

**Comment by catenocrypt** [comment]
Oh, OK, sorry, did not see that in the PR.

For the other two, new tokens:  unfortunately they have low circulation.

As per our policy, there is a minimum requirement of 2500 holder addresses and 5000 transactions, in order to filter out scam tokens.  See the criteria at (mentioned in the first message by the bot): https://community.trustwallet.com/t/how-to-submit-a-token-logo/3863).

These tokens have 286, resp. 953 holders.

Can you reflect on this?

**Comment by bi0hazard12** [comment]
> Oh, OK, sorry, did not see that in the PR.
> 
> For the other two, new tokens: unfortunately they have low circulation.
> 
> As per our policy, there is a minimum requirement of 2500 holder addresses and 5000 transactions, in order to filter out scam tokens. See the criteria at (mentioned in the first message by the bot): https://community.trustwallet.com/t/how-to-submit-a-token-logo/3863).
> 
> These tokens have 286, resp. 953 holders.
> 
> Can you reflect on this?

No problem Catenocrypt,

Those two other tokkens they also already exist. Maybe i'm doing something wrong and request the pull again. 

But those two other tokens are part of our ecosystem. DEA is low supply coin and doesn't much holders because they token itself are used as yield farming rewards and are mostly stacked in our contracts the same for the IOU-Coinbase.

And they already exist also in trustwallet. 

For now we just need to update both logos for DEUS and DEA. (the info for those already exist also)

Maybe i did something wrong and created a pull request with everything.

But the only updates we need is the logos.

0x3b62F3820e0B035cc4aD602dECe6d796BC325325 - Logo
0x80aB141F324C3d6F2b18b030f1C4E95d4d658778 - Logo

I have attached both logos.

Is it okay like this?

Thank you so much for your help

**Comment by bi0hazard12** [comment]
Hello catenocrypt,

Saw that you push the request and i appreciate so much :)

Just want to make a quick check, both logos will be changed on this pull request right?

0x3b62F3820e0B035cc4aD602dECe6d796BC325325 - Logo
0x80aB141F324C3d6F2b18b030f1C4E95d4d658778 - Logo

Thank you

**Comment by catenocrypt** [comment]
Here are the logos, as merged:

https://github.com/trustwallet/assets/blob/master/blockchains/ethereum/assets/0x3b62F3820e0B035cc4aD602dECe6d796BC325325/logo.png

https://github.com/trustwallet/assets/blob/master/blockchains/ethereum/assets/0x80aB141F324C3d6F2b18b030f1C4E95d4d658778/logo.png

**Comment by bi0hazard12** [comment]
> 

This 0x3b62F3820e0B035cc4aD602dECe6d796BC325325 is pushing the wrong logo. That's the atual logo.

It should be this one that i attached in the inicial request.

logo

**Comment by catenocrypt** [comment]
Changed with #5489 .

**Comment by bi0hazard12** [comment]
Thank you so much

**Comment by bi0hazard12** [comment]
> Changed with #5489 .

hey catenocrypt i saw that the new logos are already pushed. but they look really award at uniswap and the background color are white and i thought it would be black background like we uploaded.

What can we do to fix this?

They should look like this for example:

example

Any help much appreciated.

**Comment by catenocrypt** [comment]
The images submitted here have transparent background.
I don't know how does Uniswap processes the images when displaying.

image

https://info.uniswap.org/token/0x80aB141F324C3d6F2b18b030f1C4E95d4d658778

**Comment by bi0hazard12** [comment]
> The images submitted here have transparent background.
> I don't know how does Uniswap processes the images when displaying.
> 
> image
> 
> https://info.uniswap.org/token/0x80aB141F324C3d6F2b18b030f1C4E95d4d658778

DEA logo look's good except for the background, so in this case in order to have the black background we should upload the image as .jpg but with black background right?

But as for DEUS it look's horrible like stretched

example

Any way we could fix this and upload DEA with background ?

**Comment by catenocrypt** [comment]
Maybe it is streched because it was not square.
Provide pic with right bakcground, exactly 512x512 size.

**Comment by bi0hazard12** [comment]
> Maybe it is streched because it was not square.
> Provide pic with right bakcground, exactly 512x512 size.

Sure :)

Attached and edited both logos 512x512 with black background.

logo
logo

**Comment by catenocrypt** [comment]
Updated, #5491 , last time :)

**Comment by bi0hazard12** [comment]
> Updated, #5491 , last time :)
> 
> image

Thank you so much, they look good now :D

**Comment by bi0hazard12** [comment]
@catenocrypt I know this is really old :D 

How are you doing? :)

Just wanted to check with you if you could assist us again with some new PR #16783? I had my PR closed 5 times already without a proper answer :( We just want someone reasonable enough to read and assist us (that's not the case atm)

Thank you so much

**Pull request merged**
