### PR TITLE
Add ArtDeco logo and info

### PR DESCRIPTION
**Pull request by swingingwhale573**
This PR is being closed due to inactivity. If you wish to continue, please have us reopen the PR before sending your payment, or just create a new one.
Do NOT send payments for closed PR, as the fee may by lost!
  (167 vs. 48 hrs)

### CODE REVIEW

**Comment by catenocrypt** [comment]
Submission looks OK; awaiting fee payment.

**Comment by swingingwhale573** [comment]
> Submission looks OK; awaiting fee payment.

Hi there, thank you for letting me know. We are currently awaiting additional marketing funds to fulfill this, but we should be able to have payment submitted very soon. Thank you for your patience in the meantime.

**Comment by swingingwhale573** [comment]
Hi there,

Please reopen this pull request as we now have funds available to provide payment.

**Comment by catenocrypt** [comment]
Reopened

**Comment by catenocrypt** [comment]
Once closed auto-bot will keep closing it; but you may pay the fee nonetheless, it will be processed automatically after next reopen.

**Comment by swingingwhale573** [comment]
Hi there, thank you very much for the clarification. I have submitted the fee payment for this request. Please reopen accordingly for processing.

**Comment by catenocrypt** [comment]
Could not check website.  Could you check/explain?

image

**Comment by swingingwhale573** [comment]
I have been informed that fraudulent copycat token groups had been
reporting our website, causing it to be taken down and put under review.
The domain is still valid, and we are working on having the website itself
restored as soon as possible.

**Comment by swingingwhale573** [comment]
Could you please advise if the request can still proceed despite this, or will the website have to be restored prior to it being completed? The website was active at the time of submission, and this recent attack was a rather unexpected setback.

**Comment by Cryptocool1** [comment]
> Could you please advise if the request can still proceed despite this, or will the website have to be restored prior to it being completed? The website was active at the time of submission, and this recent attack was a rather unexpected setback.

Hello, we need to check your website, so we need to wait for it..

**Comment by swingingwhale573** [comment]
Understood, thank you for the clarification. We are working on getting it restored as soon as possible.

**Comment by Cryptocool1** [comment]
Please come back to us when all criteria are met.

**Pull request closed without merging**
