### PR TITLE
Add PhoenixDAO Icon

### PR DESCRIPTION
**Pull request by codemathics**
Added PhoenixDAO icon to the Blockchain Ethereum Asset folder.

### CODE REVIEW

**Comment by codemathics** [comment]
PhoenixDAO icon added to file path.

**Comment by codemathics** [comment]
Hi @zachzwei and @catenocrypt 

I am still kindly waiting for your response on this, please. Thanks.

**Comment by catenocrypt** [comment]
Please add an `info.json` file next to the `logo.png`, with info about the project, of the form:

```json
{
    "name": "Trust Wallet Token",
    "website": "https://trustwallet.com",
    "short_description": "Utility token to increase adoption of cryptocurrency.",
    "explorer": "https://explorer.binance.org/asset/TWT-8C2"
}
```

**Comment by codemathics** [comment]
Thanks @catenocrypt for your kind response, will update the PR now.

**Comment by codemathics** [comment]
@catenocrypt I have updated the PR. Thanks!

**Pull request merged**
