### PR TITLE
add GXT ERC20

### PR DESCRIPTION
**Pull request by gxtmg**
Adding info for ECR20 token 'GXT'.

If necessary, I can also show you a new white paper. Also, our internal wallet has more than 20,000 members.

We are currently listed on Uniswap and list on CEX (liquid pro) https://app.liquid.com/exchange/GXTUSDT

We changed the contract address last month. This is an old contract, and if you look at the transaction and the number of holders, GXT can fill the conditions.
https://etherscan.io/token/0x28d3E409bb9bC58F1ca6E009f8fC78A1db85e6b7

### CODE REVIEW

**Comment by cryptomanz** [comment]
As per our policy, brand new tokens are not included, there is a minimum requirement of 10,000 holder addresses and 20,000 transactions, in order to filter out scam tokens.
See the criteria at : https://developer.trustwallet.com/assets/requirements .

**Comment by gxtmg** [comment]
Hello @cryptomanz 

If necessary, I can also show you a new white paper. Also, our internal wallet has more than 20,000 members.

We are currently listed on Uniswap and list on CEX (liquid pro) https://app.liquid.com/exchange/GXTUSDT

We changed the contract address last month. This is an old contract, and if you look at the transaction and the number of holders, GXT can fill the conditions.
https://etherscan.io/token/0x28d3E409bb9bC58F1ca6E009f8fC78A1db85e6b7

**Comment by Cryptocool1** [comment]
invalid address: expect asset 0x4674672bcddda2ea5300f5207e1158185c944bc0 in checksum: 0x4674672BcDdDA2ea5300F5207E1158185c944bc0"

**Comment by Cryptocool1** [comment]
Please create new PR, follow doc https://developer.trustwallet.com/assets/requirements
You may want to try our Assets app in beta; go to https://assets.trustwallet.com, log on with Github, enter contract ID, logo and some additional info, and it will create a PR for you.
See https://developer.trustwallet.com/assets/repository_details

**Pull request closed without merging**
