### PR TITLE
Add Instadapp ETH (IETH) (ERC20)

### PR DESCRIPTION
**Pull request by ishanjain28**
Adding info for ERC20 token 'Instadapp ETH (IETH)'.

PR created by <a href="https://assets.trustwallet.com">TW Assets Management</a>

### CODE REVIEW

**Comment by ishanjain28** [comment]
Hey, Do we need to pay separately for adding the 4 tokens? Related PRs, #20988 #20989 and #20990

**Comment by Cryptocool1** [comment]
Yes you need to pay for each, but make sure you met all the requirements.

**Comment by Cryptocool1** [comment]
As per our policy, brand new tokens are not included, there is a minimum requirement of 10,000 holder addresses and 15,000 transactions, in order to filter out scam tokens.
See the criteria at : https://developer.trustwallet.com/assets/requirements .

**Comment by Cryptocool1** [comment]
Please come back to us once all criteria are met. Make sure to mention this PR so the fee can be reused.

**Pull request closed without merging**
