### PR TITLE
Add BabyPigToken logo and info

### PR DESCRIPTION
**Pull request by BabyPigToken**
Website: https://www.babypig.org
Twitter: https://twitter.com/BabyPigToken

### CODE REVIEW

**Comment by Cryptocool1** [comment]
hello,
• What is the purpose of this token? How will it benefit Trust Wallet users?
 • How is the token being distributed? Are you conducting an airdrop?
 • Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?
 • Is the token listed on a centralized/decentralized exchange?
 • Is a Smart Contract audit completed? Where can we find this information?

**Comment by BabyPigToken** [comment]
Hi, our token is designed to trade with NFT art pieces. In our holders
group, there are some artists and collectors to use Baby Pig Token to trade
NFT on Lootex( a NFT marketplace)
We just put 75% of token on the liquidity pool, and other parts of token
are ready for seasonal burn and team expanses. We do have airdrop for
around 100-150 people before, it was our event.
No, no ico and presale
Our token is listed on decentralized exchange right now.
Our full audit is on the way, but not publish yet
I can provide unpublished one for you.

**Comment by cryptomanz** [comment]
Hello,
- Awaiting for official smart contract audit.

**Comment by BabyPigToken** [comment]
Can the unannounced audit not be used? Awaiting for full-audit release may
take some time.

**Comment by Cryptocool1** [comment]
> Can the unannounced audit not be used? Awaiting for full-audit release may take some time.
> […](#)

Only full audit

**Comment by BabyPigToken** [comment]
I see, thank you
After full-audit released, I’ll immediately send it to you

**Comment by cryptomanz** [comment]
Hello,
please create new PR when smart contract audit will be ready.
make sure to mention this PR, so that we can see that fee has been paid already here.

**Pull request closed without merging**
