### PR TITLE
Add NovAx (BEP20)

### PR DESCRIPTION
**Pull request by AntonioVentilii**
Adding info for BEP20 token 'NovAx'.

PR created by <a href="https://assets.trustwallet.com">TW Assets Management</a>

### CODE REVIEW

**Comment by AntonioVentilii** [comment]
Hello,

Done, please see transaction: 14F8C1E15B3036C671C9D53FEAFE41F56715231EF20CF17CB7F0603EF9BCF6D4

[transaction in explorer](https://explorer.binance.org/tx/14F8C1E15B3036C671C9D53FEAFE41F56715231EF20CF17CB7F0603EF9BCF6D4)

**Comment by cryptomanz** [comment]
Hello,
Can your answer some questions?
• What is the purpose of this token? How will it benefit Trust Wallet users?
• How is the token being distributed? Are you conducting an airdrop?
• Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?
• Is the token listed on a centralized/decentralized exchange?
• Is a Smart Contract audit completed? Where can we find this information?

**Comment by AntonioVentilii** [comment]
Hello @cryptomanz ,

Thank you for your answer!

The idea behind the project is actually going back to bases on crypto: using this specific token as curency (i.e. menas of exchange for goods). In order to do so, we started with a specific community (of which some of our members are part of), even if it is a controversial topic: NoVax.

I imagine that anyone has its own opinion about the topic, but the main idea is to create a crypto that "represents" the NoVax community. That means not only as a "recognition symbol" among it, but even to try and create our own "closed economy". For example, when and if it will take good place into the community, it will be used to exchange simple things, exactly as a currency: we are going out for a pizza and somebody pays in whatever FIAT to the pizzeria, but the others split in NVX equivalent, if they are all NoVax.

Again, this is all community based, we are trying to make it acceptable; some of us already are using it, and we convince a lot more. We just need to start and not be left aside.

Going back to origin in the real sense of what Crypto are born for: a currency which value and worth are community-democratically-decided.

We are distributing almost 80% of the total supply (no more will be created) to the community or whoever wants them. It is not a fast process obviously, but they can be already available to anybody you wants. We started with a pre-sale that ended today. The next sale will be this week (just to check how the market reacts to the price). Afterwards we organize the ICO to give all the rest, open-price.

**Comment by AntonioVentilii** [comment]
Sorry to bother again, but the correct name should be **NoVax**  (capital V and not A)

I think I mistyped...

**Comment by Cryptocool1** [comment]
awaiting for smart contract audit, on hold for now

**Comment by AntonioVentilii** [comment]
@Cryptocool1 @cryptomanz @zachzwei @ramsty 

what audit company do you accept? we found out there are a lot of them now, not the most famous 4

**Pull request closed without merging**
