### PR TITLE
Add FLOKI CEO (BEP20)

### PR DESCRIPTION
**Pull request by flokiceo**
Adding info for BEP20 token 'FLOKI CEO'.

PR created by <a href="https://assets.trustwallet.com">TW Assets Management</a>

### CODE REVIEW

**Comment by flokiceo** [comment]
We already have more than 10,500 holders. please help me update token information

**Comment by Cryptocool1** [comment]
Hello, how did you make more than 10k holders in 1 week?

**Comment by flokiceo** [comment]
> Hello, how did you make more than 10k holders in 1 week?

x112 from ATH, that help many people invest, buy and hold

**Comment by Cryptocool1** [comment]
Any airdrops?

**Comment by flokiceo** [comment]
> Fee is PAID, fantastic! Thanks! Review added.
> 
> The PR will be evaluated soon by a maintainer, and if merged, the new logos should be visible in Trust Wallet. Please note that the app caches logos (up to several days; if you want to see changes immediately, use a new installation). See the [assets FAQ](https://github.com/trustwallet/assets#faq). @Iamdeadlyz, @Cryptocool1, @cryptomanz1: please take note.
> 
> ([500.00 TWT](https://explorer.binance.org/tx/9523B5777502B10315939E4C6189F5065AEE415117DE1CC1E3025B2593F5FA0D))

I still haven't seen my token updated with the logo

**Comment by Cryptocool1** [comment]
Did you answer my question?

**Comment by flokiceo** [comment]
> 

Sorry for the late response, about 200 people received the airdrop

**Comment by Cryptocool1** [comment]
• What is the purpose of this token? How will it benefit Trust Wallet users?
 • How is the token being distributed? 
 • Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?
 • Is the token listed on a centralized/decentralized exchange?
 • Is a Smart Contract audit completed? Where can we find this information?

**Comment by flokiceo** [comment]
> • What is the purpose of this token? How will it benefit Trust Wallet users? • How is the token being distributed? • Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale? • Is the token listed on a centralized/decentralized exchange? • Is a Smart Contract audit completed? Where can we find this information?

Hi,

- The FLOKICEO token is a typical token meme, inspired by Elon Musk's dog named FLOKI. With 7% Reflection extracted from transactions, equally divided between token holders. This is a great reward. In addition, users can use FLOKICEO to participate in farming on Babydogeswap to receive high interest rates (currently 130%)
- 50% Token burn, 16.5% add liquidity, 33% presale. 0.5% airdrop
- Presale on Pinksale
- Dex: Already listed on Pancakeswap, Babydogeswap,Shidodex
- Cex: Already listed on Lbank, Bitmart, will list Bkex 7 march
- Audited by AnalytixAudit: https://github.com/AnalytixAudit/Solidity/blob/main/20230219_Analytix%20Audit_FLOKI%20CEO_Audit.pdf

**Comment by flokiceo** [comment]
> • What is the purpose of this token? How will it benefit Trust Wallet users? • How is the token being distributed? • Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale? • Is the token listed on a centralized/decentralized exchange? • Is a Smart Contract audit completed? Where can we find this information?

Hi everything good?. Please take a look at chart 

https://www.dextools.io/app/en/bnb/pair-explorer/0x7c03a98FfbE219Dd4113A47a47601A0c26AebAD3

**Comment by Cryptocool1** [comment]
Congratulations!
Your logo should appear within 2hours.

**Pull request merged**
