### PR TITLE
Remove VRAB, add erc777 VRA

### PR DESCRIPTION
**Pull request by verasitytech**
- Remove discontinued VRAB token
- Rename obsolete erc20 VRA
- Add erc777 VRA
- Resize and tinify images

### CODE REVIEW

**Comment by catenocrypt** [comment]
Submission looks OK.  Fee payment pending.

**Comment by catenocrypt** [comment]
Did fixes.  One check fails now: type ERC1820 is not supported currently in assets repo.  Hold on while we check support in the app.

**Comment by verasitytech** [comment]
> Did fixes. One check fails now: type ERC1820 is not supported currently in assets repo. Hold on while we check support in the app.

if the type is not supported you can switch it back to ERC20, token is backwards compatible with it

**Comment by catenocrypt** [comment]
Changed type to ERC20;  ERC1820 has no special implementation in app anyways.

**Pull request merged**
