### PR TITLE
Add Mini Hollywood Doge Token Logo to TrustWallet

### PR DESCRIPTION
**Pull request by OzzyEzzy**
Hello,

I would like to kindly add our token logo.

Thanks

### CODE REVIEW

**Comment by Cryptocool1** [comment]
Can you answer some questions?
- • What is the purpose of this token? How will it benefit Trust Wallet users?
 • How is the token being distributed? Are you conducting an airdrop?
 • Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?
 • Is the token listed on a centralized/decentralized exchange?
 • Is a Smart Contract audit completed? Where can we find this information?

**Comment by OzzyEzzy** [comment]
Hi, Sure here are the answers.

What is the purpose of this token? How will it benefit Trust Wallet users?
Our token was inspired by the famous Doge Coin. However, our token is not simply a meme token. In addition to our superior validation protocol that greatly increases transaction speeds, and reduces processing times by nearly ten times, we strive to provide donations to different causes. Our first donation is related to COVID-19 relief to countries that are mostly affected by the new Delta variant. Since we value our community the most, we will be allowing our community to vote on the different causes to donate to in the future. In addition, we are developing a launchpad for future meme token projects and will create a marketplace for “merchandise that gives back”. The best part of our merchandise is that over 50% of the sales will go directly to charity causes.

Trust Wallet users will be able to use our token to purchase our merchandise, to donate to different causes, and to launch their own meme tokens on our platform. Since our token has a redistribution fee of 10%, our holders will be gaining more tokens as they hold.  


• How is the token being distributed? Are you conducting an airdrop?

Since we had a private seed round to help fund the project before its launch, we airdropped those investors before our launch. These were 150 wallets. We have also airdropped around 85 other wallets of people that were involved in promoting the token in the early stages and those that managed the community, as well as our team members. All together, these airdrops were made to less than 300 wallets. We currently have more than 9,000 holders, so if we exclude these airdropped wallets, we are above the required 5,000.


• Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?

We held a private seed round of 300 BNB (150 people, 2 BNB each) and a token presale on Dxsale of 1700 BNB. The amounts from the private seed round helped to get the project up and running. 80% of the presale of Dxsale were locked and added to the liquidity pool while the rest has been used for marketing.


• Is the token listed on a centralized/decentralized exchange?
We are currently not listed on a centralized/decentralized exchange. We are currently in talks with hotbit for a possible listing and we are just going through few details before signing the contract.

• Is a Smart Contract audit completed? Where can we find this information?
Our Smart Contract is currently being audited by Techrate. Techrate will post the audit report on github as soon as they finalize it.

**Comment by OzzyEzzy** [comment]
> Can you answer some questions?
> 
> * • What is the purpose of this token? How will it benefit Trust Wallet users?
>   • How is the token being distributed? Are you conducting an airdrop?
>   • Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?
>   • Is the token listed on a centralized/decentralized exchange?
>   • Is a Smart Contract audit completed? Where can we find this information?

Hi, Sure here are the answers.

What is the purpose of this token? How will it benefit Trust Wallet users?
Our token was inspired by the famous Doge Coin. However, our token is not simply a meme token. In addition to our superior validation protocol that greatly increases transaction speeds, and reduces processing times by nearly ten times, we strive to provide donations to different causes. Our first donation is related to COVID-19 relief to countries that are mostly affected by the new Delta variant. Since we value our community the most, we will be allowing our community to vote on the different causes to donate to in the future. In addition, we are developing a launchpad for future meme token projects and will create a marketplace for “merchandise that gives back”. The best part of our merchandise is that over 50% of the sales will go directly to charity causes.

Trust Wallet users will be able to use our token to purchase our merchandise, to donate to different causes, and to launch their own meme tokens on our platform. Since our token has a redistribution fee of 10%, our holders will be gaining more tokens as they hold.

• How is the token being distributed? Are you conducting an airdrop?

Since we had a private seed round to help fund the project before its launch, we airdropped those investors before our launch. These were 150 wallets. We have also airdropped around 85 other wallets of people that were involved in promoting the token in the early stages and those that managed the community, as well as our team members. All together, these airdrops were made to less than 300 wallets. We currently have more than 9,000 holders, so if we exclude these airdropped wallets, we are above the required 5,000.

• Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?

We held a private seed round of 300 BNB (150 people, 2 BNB each) and a token presale on Dxsale of 1700 BNB. The amounts from the private seed round helped to get the project up and running. 80% of the presale of Dxsale were locked and added to the liquidity pool while the rest has been used for marketing.

• Is the token listed on a centralized/decentralized exchange?
We are currently not listed on a centralized/decentralized exchange. We are currently in talks with hotbit for a possible listing and we are just going through few details before signing the contract.

• Is a Smart Contract audit completed? Where can we find this information?
Our Smart Contract is currently being audited by Techrate. Techrate will post the audit report on github as soon as they finalize it.

**Comment by Cryptocool1** [comment]
awaiting for smart contract audit

**Comment by OzzyEzzy** [comment]
Our devs ended up with ApeAudit

here is the github link https://github.com/ApeAudits1/Smart-Contract-Audits/blob/main/MiniHollywoodDoge.pdf

Thank you

**Comment by OzzyEzzy** [comment]
> awaiting for smart contract audit

Our devs ended up with ApeAudit

here is the github link https://github.com/ApeAudits1/Smart-Contract-Audits/blob/main/MiniHollywoodDoge.pdf

Thank you

**Comment by Cryptocool1** [comment]
can you please add links to your PR?
example: https://developer.trustwallet.com/add_new_asset#info-json-contents

**Comment by OzzyEzzy** [comment]
> can you please add links to your PR?
> example: https://developer.trustwallet.com/add_new_asset#info-json-contents

Links added. Thank you

**Comment by Cryptocool1** [comment]
Type field cannot be empty
Symbol field cannot be empty

**Comment by OzzyEzzy** [comment]
> Type field cannot be empty
> Symbol field cannot be empty

Sorry my bad. I'm not sure how they disappeared. Fixed now

**Pull request merged**
