### PR TITLE
Add Logo for Hamtaro

### PR DESCRIPTION
**Pull request by HamtaroBSC**
Add logo now i pay

### CODE REVIEW

**Comment by Cryptocool1** [comment]
File should include only 1 file
blockchains/smartchain/assets/0x4d4cc29b9c4e413cfe5f898e16280f11db57e186/logo.png

**Comment by HamtaroBSC** [comment]
Yes i know

Il giorno lun 17 mag 2021 alle 07:22 CryptoA ***@***.***> ha
scritto:

**Comment by HamtaroBSC** [comment]
Added now

Il giorno lun 17 mag 2021 alle ore 08:01 merge-fee-bot[bot] <
***@***.***> ha scritto:

**Comment by Cryptocool1** [comment]
Remove unnecessary files please:
blockchains/smartchain/assets/0x4d4cc29b9c4e413cfe5f898e16280f11db57e186/01.png
blockchains/smartchain/assets/0x4d4cc29b9c4e413cfe5f898e16280f11db57e186/logo.png.png

**Comment by HamtaroBSC** [comment]
How?

Il giorno lun 17 mag 2021 alle ore 08:27 CryptoA ***@***.***>
ha scritto:

**Comment by Cryptocool1** [comment]
If you can't delete files in the PR, you may open a new PR. Make sure to mention this PR, so that we can see that fee has been paid already here.
You may want to try our new Assets app in beta; go to https://assets.trustwallet.com, log on with Github, enter contract ID, logo and some additional info, and it will create a PR for you.
See https://community.trustwallet.com/t/how-to-submit-a-token-logo-using-assets-app/82957.

**Comment by Cryptocool1** [comment]
duplicate

**Pull request closed without merging**
