### PR TITLE
Add ATA Token (BEP20)

### PR DESCRIPTION
**Pull request by brandpad-finance**
Adding info for BEP20 token 'ATA Token'.

PR created by <a href="https://assets.trustwallet.com">TW Assets Management</a>

### CODE REVIEW

**Comment by atatoken** [comment]
For the payment please check: https://github.com/trustwallet/assets/pull/9670

**Comment by atatoken** [comment]
@Cryptocool1 It is our second pull request for logo and it took almost 2-3 weeks till now.

I don't know why you are waiting? We have paid fee and did everything correctly. Please update us as soon as possible.

**Comment by Cryptocool1** [comment]
> @Cryptocool1 It is our second pull request for logo and it took almost 2-3 weeks till now.
> 
> I don't know why you are waiting? We have paid fee and did everything correctly. Please update us as soon as possible.

we will merge your token when CMC verifies your project.
thanks.

**Comment by atatoken** [comment]
We have filled form for CMC and it is still pending. But we are already listed on Coingecko.

**Comment by atatoken** [comment]
Can we request refund please?

**Comment by Cryptocool1** [comment]
> Can we request refund please?

 As there is no refund, before paying the fee, make sure new tokens fulfill the minimum circulation and other acceptance criteria.

**Comment by Cryptocool1** [comment]
please create new PR when your token will be listed on CMC
make sure to mention this PR so that fee can can be reused

**Pull request closed without merging**
