### PR TITLE
Add Football World Community (BEP20)

### PR DESCRIPTION
**Pull request by Fwc-Token**
Adding info for BEP20 token 'Football World Community'.

PR created by <a href="https://assets.trustwallet.com">TW Assets Management</a>

### CODE REVIEW

**Comment by Fwc-Token** [comment]
The team already paid

**Comment by Cryptocool1** [comment]
hello, please send an official announcement about updating

**Comment by Fwc-Token** [comment]
https://twitter.com/FWCOMMUNITY_Q2T/status/1599345046456700928?s=20&t=7B832v3TlonXreUMx0tEBg

https://t.me/Qatar2022tokenAnnouncements/799

**Comment by Fwc-Token** [comment]
Hi 
Please check
Thank you

**Comment by Fwc-Token** [comment]
Coingecko Done

https://www.coingecko.com/en/coins/football-world-community
https://twitter.com/FWCOMMUNITY_Q2T/status/1600092849738874880?t=PcbQ7psxT5AV01m_4unJJg&s=19
https://t.me/Qatar2022tokenAnnouncements/824

All exchanges done!

**Comment by Fwc-Token** [comment]
https://support.bitmart.com/hc/en-us/articles/10983649331867

See this article

**Pull request merged**
