### PR TITLE
Add Square Token

### PR DESCRIPTION
**Pull request by square-token**
Add Square Token logo and info

### CODE REVIEW

**Comment by Cryptocool1** [comment]
• What is the purpose of this token? How will it benefit Trust Wallet users?
 • How is the token being distributed? Are you conducting an airdrop?
 • Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?
 • Is the token listed on a centralized/decentralized exchange?
 • Is a Smart Contract audit completed? Where can we find this information?

**Comment by square-token** [comment]
• What is the purpose of this token? How will it benefit Trust Wallet users?

A: It is a GoFintech Group governance token, designed to serve as a means of payment for Crypto/Fiat financial services. The token will be used to buy and sell NFTs (which the group develops and from other partners), credit balance on prepaid cards, swapping between crypto and fiat (as well as crypto.com). It will be used to pay rewards programs, such as cashback and credit card points issued to customers.
Many customers use TrustWallet as a way to store their tokens and also to buy and sell on PancakeSwap, the only exchange that the token is listed on.

• How is the token being distributed? Are you conducting an airdrop?
A: We did not airdrop, we pre-sale part of the tokens and they are distributed as informed below:
- Private Sale 01 - 12% 
- Private Sale 02 - 18%
- Private Sale 03 - 30%
- Liquidity - 5%
- Ecosystem Fund - 35% 

• Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?
A: Yes, we did a token presale.

• Is the token listed on a centralized/decentralized exchange?
A: Yes, our token is only listed on PancakeSwap.

• Is a Smart Contract audit completed? Where can we find this information?
A: Our token was developed by the company Cryptologic.io, which has code review and security audit services. Our contracts are in public repository at the following link https://github.com/square-token/squaretoken

**Comment by Cryptocool1** [comment]
Please come back to us once all criteria are met. Make sure to mention this PR so the fee can be reused.

**Comment by cromaweb** [comment]
We have the audit link https://www.certik.com/projects/squaretoken

**Review by cromaweb — COMMENTED** [review]
We have the audit link https://www.certik.com/projects/squaretoken

**Pull request closed without merging**
