### PR TITLE
Add TW token logo

### PR DESCRIPTION
**Pull request by DogeUniverse**
We want to add a logo for our token which is attached in the folder

### CODE REVIEW

**Comment by DogeUniverse** [comment]
What do I need to do to add the logo?

**Comment by ramsty** [comment]
> What do I need to do to add the logo?
Hi! 
1) Remove this file blockchains/binance/assets/0x01af9fc6130aeddbd2cdb6e684262f5b605471cc/256x256.png;
2) Change contract to checksum format;
3) add links to your PR like on the example.
description Utility token

**Comment by DogeUniverse** [comment]
Is there an easier way we can add our logo? Like a form or something?

**Comment by ramsty** [comment]
Please create new PR, follow doc https://community.trustwallet.com/t/how-to-submit-a-token-logo/3863
You may want to try our new Assets app in beta; go to https://assets.trustwallet.com, log on with Github, enter contract ID, logo and some additional info, and it will create a PR for you.
See https://community.trustwallet.com/t/how-to-submit-a-token-logo-using-assets-app/82957.

**Pull request closed without merging**
