### PR TITLE
Dexview logo and info json

### PR DESCRIPTION
**Pull request by dexterminat0r**
Please update our $DXW token info, the main token of Dexview platform, everything about tracking, monitoring and analyzing cross blockchains

### CODE REVIEW

**Comment by Cryptocool1** [comment]
Hello,
As per our policy, there is a minimum requirement of 2500 holder addresses and 5000 transactions.
This token has no real usage yet (140 holders, 531 transactions). Closing PR for now. Please come back to us when all criteria are met.

**Comment by dexterminat0r** [comment]
> Hello,
> As per our policy, there is a minimum requirement of 2500 holder addresses and 5000 transactions.
> This token has no real usage yet (140 holders, 531 transactions). Closing PR for now. Please come back to us when all criteria are met.

seriously? now are u telling us that? after have been working on it, waiting and letting our community be in joy?
such important info, must be shared, not after paying fees, what is wrong in this world? what about the paid fee?

**Comment by dexterminat0r** [comment]
> Hello,
> As per our policy, there is a minimum requirement of 2500 holder addresses and 5000 transactions.
> This token has no real usage yet (140 holders, 531 transactions). Closing PR for now. Please come back to us when all criteria are met.
@Cryptocool1  @catenocrypt  @zachzwei @hexorx 
first u dont have the right to say about our token they dont have usage, u simply cant know that
second there are so many crap coins on trustwallet
third this should only a token information update, that people become the token better displayed, why are u doing such problem, i dont understand, and why after taking the fee.
i guess such a name like trustwallet should be serious company
why this disappointment at this point??

**Comment by dexterminat0r** [comment]
@Cryptocool1 @catenocrypt @zachzwei @heisenberghoge @hexorx
We need answers please

**Pull request merged**
