### PR TITLE
Add FUDx Coin (BEP20)

### PR DESCRIPTION
**Pull request by PankajTMB**
Adding info for BEP20 token 'FUDx Coin'.

PR created by <a href="https://assets.trustwallet.com">TW Assets Management</a>

### CODE REVIEW

**Comment by Cryptocool1** [comment]
• What is the purpose of this token? How will it benefit Trust Wallet users?
 • How is the token being distributed? Are you conducting an airdrop?
 • Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?
 • Is the token listed on a centralized/decentralized exchange?
 • Is a Smart Contract audit completed? Where can we find this information?

**Comment by PankajTMB** [comment]
• What is the purpose of this token? How will it benefit Trust Wallet users?

Ans:   FUDX is a 'one stop' delivery service that enables users to order anything they like from the nearest store in shortest amount of time using blockchain technology. So Trust wallet Users also can get benefit by buying FUDx Coin. 

• How is the token being distributed? Are you conducting an airdrop?

Ans:  A portion of the tokens are reserved for the project's FUDx developers and some are held for business development and expansion purpose. However we're not conducting an airdrop yet.

• Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?

Ans: No, all of our token are sold in PancakeSwap Exchange

• Is the token listed on a centralized/decentralized exchange?

Ans: Yeah its listed on PancakeSwap with Liquidity. 
  
• Is a Smart Contract audit completed? Where can we find this information?

Ans:  Yeah you can see audit https://fudxcoin.io/audit.pdf

**Comment by fudxcoin** [comment]
> are you listed on CoinMarketCap?

Thanks for your attention we have applied for CMC. They are reviewing our application. I think it took longer can you just show our logo at trustwallet. When its listed on CMC then our price will show on CMC.

thanks

**Comment by PankajTMB** [comment]
@Cryptocool1 

Thanks for your comment. We have aepplied for CMC i think it will take time they have forward our application for 2nd phase see screenshot : https://prnt.sc/z3Q5u3Cs5p1i . Can you just show our logo for now when we listed on CMC then our price will show on Trust Wallet.

**Comment by Cryptocool1** [comment]
hello, 
please see our requirement: Token should be listed on price tracking sites like CoinmarketCap
https://developer.trustwallet.com/assets/requirements

**Comment by Cryptocool1** [comment]
Please come back to us once all criteria are met, make sure to mention this PR so the fee can be reused

**Pull request closed without merging**
