### PR TITLE
info

### PR DESCRIPTION
**Pull request by PIDAOFinance**
info push

### CODE REVIEW

**Comment by PIDAOFinance** [comment]
We have already sent *1000 TWT* with the memo *15668* to the address
bnb1tqq9llyr3dyjd559dha6z5r5etk3qfwk07m098,please
check.

merge-fee-bot[bot] ***@***.***> 于2021年11月16日周二 下午5:35写道：

**Comment by Cryptocool1** [comment]
• What is the purpose of this token? How will it benefit Trust Wallet users?
 • How is the token being distributed? Are you conducting an airdrop?
 • Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?
 • Is the token listed on a centralized/decentralized exchange?
 • Is a Smart Contract audit completed? Where can we find this information?

**Comment by PIDAOFinance** [comment]
Q: What is the purpose of this token? How will it benefit Trust Wallet
users?

A: PIDAO is a decentralized reserve currency protocol forking Olympus based
on PID token. Each PID token is backed by a basket of assets(e.g. BUSD,
USDT) in the PIDAO treasury, giving it an intrinsic value that it cannot
fall below.

At the same time, PIDAO is a DeFi 2.0 project based on POL (Protocol Owned
Liquidity) and PVC (Protocol controlled value) to ensure PID price
stability and token security of holders including Trust Wallet users.

Besides, PIDAO is deployed on the Binance Smart Chain to lower gas fees
with smooth experience, thereby greatly reducing transaction cost and fees
and enabling more ordinary users to get in. The massive user base on BSC
also facilitates more flows and stronger consensus.

Q: How is the token being distributed? Are you conducting an airdrop?

A: The initial supply is 68,260 PID. Among them, 50,000 PID will be
provided to participants and institutional investors in the fair launch of
the community, 10,000 PID will be used as initial liquidity, and 8,260 PID
will be used as an incentive for the project development team. After the
project is officially launched, 180,000 BUSD will be added to the
PancakeSwap liquidity pool together with 10,000 PID. The PID/BUSD LP
obtained will be deposited as a reserve asset in the agreed treasury
contract. The remaining part of the funds obtained from the fair start-up
activities will be deposited into the agreed treasury contract as internal
value and reserve asset support.

Yes, we have conducted airdrops to motivate users.

Q: Did you sold the tokens at an Initial Coin Offering (ICO) or a token
presale?

We have ITO (Initial Telegram Offering) in the hopes of receiving more
comments from community members. All BUSD raised has been transacted to the
treasury contract.

Treasury contracts have adopted multi-signature contracts to ensure the
decentralization of treasury governance. Participants of the
multi-signature contracts of the treasury will be selected from
institutional investors.

Q: Is the token listed on a centralized/decentralized exchange?

A:  Yes, PID has been listed on Hotbit.

Q:  Is a Smart Contract audit completed? Where can we find this information?

A: The audit by Certilink is in progress.

Audit Report by multiple companies such as CertiK are in process. As a fork
of Olympus, PIDAO and OlympusDAO use the same source code.


CryptoA ***@***.***> 于2021年11月16日周二 下午9:50写道：

**Comment by ramsty** [comment]
Awaiting for smart contract audit. On hold for now.

**Comment by PIDAOFinance** [comment]
Sure, will feed back to you when audit done.

ramsty ***@***.***> 于2021年11月18日周四 下午10:47写道：

**Comment by Cryptocool1** [comment]
Please come back to us when all criteria are met.
When creating a new PR make sure to mention this PR, so that we can see that fee has been paid already here.

**Comment by PIDAOFinance** [comment]
Sure. Thank you!

CryptoA ***@***.***> 于2021年11月19日周五 下午9:39写道：

**Comment by PIDAOFinance** [comment]
Hi, the audit report of PIDAO by Certik has been done. Please check the
security assessment here.

CryptoA ***@***.***> 于2021年11月19日周五 21:39写道：

**Comment by PIDAOFinance** [comment]
Here is the link of our audit report
https://www.certik.com/projects/pidaofinance
old PR number  #15668 <https://github.com/trustwallet/assets/pull/15668>
 #15667

Anything else needed?

DAO Pi ***@***.***> 于2021年12月10日周五 下午7:51写道：

**Pull request closed without merging**
