### PR TITLE
Add blocsport.one (BEP20)

### PR DESCRIPTION
**Pull request by AndreiD**
Adding info for BEP20 token 'blocsport.one'.

PR created by <a href="https://assets.trustwallet.com">TW Assets Management</a>

### CODE REVIEW

**Comment by AndreiD** [comment]
I created this using your tool, but it's a bug in it that doesn't detect the correct number of holders

**Comment by AndreiD** [comment]
payment: https://github.com/trustwallet/assets/pull/10710#pullrequestreview-692720621  (I'll try to get the txid asap)

**Comment by cryptomanz** [comment]
can't find your contract on the website
 please check

**Comment by AndreiD** [comment]
We've added a big button on homepage called Token that goes to https://blocsport.one/buy-tokens/ is this clear enough? @cryptomanz

**Comment by cryptomanz** [comment]
> We've added a big button on homepage called Token that goes to https://blocsport.one/buy-tokens/ is this clear enough? @cryptomanz

great! thanks

**Pull request merged**
