### PR TITLE
Add Logo NBG

### PR DESCRIPTION
**Pull request by dhabita**
hi i have paid pull before , and not used anymore , 
can i use for this pull request

this is old pull
https://github.com/trustwallet/assets/pull/13921

### CODE REVIEW

**Comment by dhabita** [comment]
hi i have paid pull before , and not used anymore ,
can i use for this pull request ?

this is old pull
https://github.com/trustwallet/assets/pull/13921

**Comment by Cryptocool1** [comment]
• What is the purpose of this token? How will it benefit Trust Wallet users?
 • How is the token being distributed? Are you conducting an airdrop?
 • Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?
 • Is the token listed on a centralized/decentralized exchange?
 • Is a Smart Contract audit completed? Where can we find this information?

**Comment by dhabita** [comment]
• What is the purpose of this token? How will it benefit Trust Wallet users?
90% of NBG users use Trustwallet to hold NBG , Users trust wallet will find it easy to see their assets if the NBG logo appears

• How is the token being distributed? Are you conducting an airdrop?
All tokens have been distributed, we have a small airdrop for early users our application

• Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?
We are holding a little private sale to friends to create initial liquidity on pancakeswap

• Is the token listed on a centralized/decentralized exchange?
List on pancakeswap and on dex-trade.com ( cex )

• Is a Smart Contract audit completed? Where can we find this information?
not yet, but we use standard erc20 contract, no have an additional feature

**Comment by Cryptocool1** [comment]
we require smart contract audit, please come back to us when all criteria are met.
https://developer.trustwallet.com/assets/requirements

**Comment by Cryptocool1** [comment]
Hello, yes we accept techrate

**Comment by dhabita** [comment]
Hi 
there is tech rate audited
https://github.com/TechRate/Smart-Contract-Audits/blob/main/February/Ninebot.io%20GAS.pdf

**Comment by dhabita** [comment]
hi , mabe you forgot to check this , 

audit is done

https://github.com/TechRate/Smart-Contract-Audits/blob/main/February/Ninebot.io%20GAS.pdf
thanks.

**Pull request closed without merging**
