### PR TITLE
ADD BEP20 0x12e34cdf6a031a10fe241864c32fb03a4fdad739

### PR DESCRIPTION
**Pull request by TheFreeCoin**
FREE coin in ERC20 and TRC10 is already in trustwallet.

This request is to add our BSC BEP20 FREE coin 0x12e34cdf6a031a10fe241864c32fb03a4fdad739
[info.txt](https://github.com/trustwallet/assets/files/5323216/info.txt)
logo png

The info.txt is the json file (I can not upload json files here)

### CODE REVIEW

**Comment by TheFreeCoin** [comment]
Can you confirm the destination address for the payment : bnb1tqq9llyr3dyjd559dha6z5r5etk3qfwk07m098 is not an address on the BSC blockchain ?

**Comment by TheFreeCoin** [comment]
@zachzwei : Can you confirm the destination address for the payment : bnb1tqq9llyr3dyjd559dha6z5r5etk3qfwk07m098 is not an address on the BSC blockchain ? Which blockchain is it on ? Thanks

**Comment by TheFreeCoin** [comment]
@catenocrypt : I think there is a problem with this request ? It is "committed", but BEP20 FREE coin is not available yet in TRUST wallet ? Can you advice ? Thank you.

**Comment by catenocrypt** [comment]
I am confused: this PR was about a TRC10 token, not BEP20

image

**Comment by TheFreeCoin** [comment]
@catenocrypt 

No we had 2 different issues :

1) a PR about our TRC10 (Tron) token : you closed this with "won t fix"

2) This request to also display our Binance Smart Chain BEP20 token in trustwallet

Our ERC20 and TRC10 tokens can be used in trustwallet, our BEP20 token is not yet available in Trust ?

**Comment by catenocrypt** [comment]
Please check the Files section of this PR: it had TRC10, not BEP20 tokens.
Which is the PR that was merge with BEP20 token?

**Comment by TheFreeCoin** [comment]
Yes, we made an error in uploading the wrong version of our json file (the old one which we used to request the listing of our TRC10 token on Trust). But our TRON token was already present on Trust (that was the one where the price is not displayed, but ended in a won't fix of price display)


[info.txt](https://github.com/trustwallet/assets/files/5339104/info.txt)
This should be the correct one.

**Comment by catenocrypt** [comment]
Sorry, added files and their content matter most, comments are just chit-chat :)
Anyways, I added it in new PR: #4345
Please check.

**Comment by TheFreeCoin** [comment]
OK,

This is correct, how to proceed now ?

Tx

Ben

Verzonden vanuit Mail<https://go.microsoft.com/fwlink/?LinkId=550986> voor Windows 10

Van: Adam R<mailto:notifications@github.com>
Verzonden: woensdag 7 oktober 2020 10:27
Aan: trustwallet/assets<mailto:assets@noreply.github.com>
CC: TheFreeCoin<mailto:freecoin@outlook.be>; Author<mailto:author@noreply.github.com>
Onderwerp: Re: [trustwallet/assets] ADD BEP20 0x12e34cdf6a031a10fe241864c32fb03a4fdad739 (#4291)


Sorry, added files and their content matter most, comments are just chit-chat :)
Anyways, I added it in new PR: #4345<https://eur06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Ftrustwallet%2Fassets%2Fpull%2F4345&data=02%7C01%7C%7Ca8e845f5007c45c7f30808d86a9ad7c7%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637376560553329447&sdata=lK6Pkv1hXJa8fX5LHDnqVu49pa8PCpJSipAECI9jRTA%3D&reserved=0>
Please check.

**Comment by catenocrypt** [comment]
Done.

**Comment by TheFreeCoin** [comment]
Hi Adam,

The BEP20 FREE token is now visible, but it does not show the price from Coinmarketcap ? https://coinmarketcap.com/currencies/free-coin/


Coinmarketcap shows 1 average price for FREE in ERC20,BEP20,TRC10 : see the Blockchain explorers they mention in the printscreen below.

Can FREE coin (BEP20) display the price of CoinMarketCap ?
[cid:image001.png@01D69FB4.252D3E20]

Verzonden vanuit Mail<https://go.microsoft.com/fwlink/?LinkId=550986> voor Windows 10

Van: Adam R<mailto:notifications@github.com>
Verzonden: woensdag 7 oktober 2020 10:41
Aan: trustwallet/assets<mailto:assets@noreply.github.com>
CC: TheFreeCoin<mailto:freecoin@outlook.be>; Author<mailto:author@noreply.github.com>
Onderwerp: Re: [trustwallet/assets] ADD BEP20 0x12e34cdf6a031a10fe241864c32fb03a4fdad739 (#4291)


Done.

**Comment by TheFreeCoin** [comment]
@catenocrypt  : the FREE coin now has +38 000 holders on Binance Smart Chain, this BEP20 token is available in Trust but it does not show the price of Coinmarketcap : https://coinmarketcap.com/currencies/free-coin/markets/

which steps do we have to take to have our price displayed in Trust ? Thank you

**Pull request merged**
