### PR TITLE
Update info 

### PR DESCRIPTION
**Pull request by babyshibapub**

### CODE REVIEW

**Comment by babyshibapub** [comment]
I payed: https://github.com/trustwallet/assets/pull/11479

**Comment by babyshibapub** [comment]
• What is the purpose of this token? How will it benefit Trust Wallet users?
- Baby Shiba is very giving and is designed to reward long term holders. Community is first and foremost. Baby Shiba token fairness to the community.

• How is the token being distributed? Are you conducting an airdrop?
- We are conducting an airdrop here: https://t.me/BabyShiba_Airdrop_Bot

• Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?
- We have presale at website: https://babyshibatoken.net/

• Is the token listed on a centralized/decentralized exchange?
- Yes: Decentralized exchange https://pancakeswap.info/token/0xf7ad5b7d0e408daab2f5689103ca84d1a416ceba

• Is a Smart Contract audit completed? Where can we find this information?
- Contract 1: https://bscscan.com/address/0xf7ad5b7d0e408daab2f5689103ca84d1a416ceba
- Contract audit: https://bscscan.com/address/0xa3aac666b2055e041d0f79b64956fc883cc20d7f#code

thank you

**Comment by babyshibapub** [comment]
@Cryptocool1
I pay here : https://github.com/trustwallet/assets/pull/11479
Help me review

**Comment by Cryptocool1** [comment]
Please create new PR, follow doc https://community.trustwallet.com/t/how-to-submit-a-token-logo/3863
You may want to try our Assets app in beta; go to https://assets.trustwallet.com, log on with Github, enter contract ID, logo and some additional info, and it will create a PR for you.
See https://community.trustwallet.com/t/how-to-submit-a-token-logo-using-assets-app/82957.

**Pull request closed without merging**
