### PR TITLE
Add new DEEZNUTS contract address and remove old DEEZNUTS logo (contract fork)

### PR DESCRIPTION
**Pull request by deeznutscoin**
The DEEZNUTS smart contract has been upgraded and forked. The old DEEZNUTS logo should be deleted and the new DEEZNUTS logo and smart contract should be implemented.

### CODE REVIEW

**Comment by Cryptocool1** [comment]
Files should not be deleted in a PR.
status for old tokens should be "abandoned"

**Comment by deeznutscoin** [comment]
Can you merge this and deactivate our old DEEZNUTS token (remove the logo) - 0x01921A94e68F8D54F33C5D6f71d6664C35e33269

**Comment by deeznutscoin** [comment]
Hi, we've already paid the 1000 TWT fee a few days ago. You can see the tx hash here: 3A58F55614505B85BACB17DC2916E6D502BA7F467FDE60B27A851D0797161769

Please let me know if there is anything that needs to be done still in order for this pull request to be merged. We need our old token deprecated and new token to have the logo as soon as possible so users can differentiate between them. Thanks.

**Comment by Cryptocool1** [comment]
your logo is too large.
please create new PR
you don't need to pay one more time,
make sure to mention this PR in the new PR

**Comment by deeznutscoin** [comment]
@Cryptocool1 Can you take a look at the new pull request when you get the chance? https://github.com/trustwallet/assets/pull/11541

**Pull request closed without merging**
