### PR TITLE
Add files via upload

### PR DESCRIPTION
**Pull request by aliarzani**
This is Python ICO that want to change crypto world in a better way.

### CODE REVIEW

**Comment by zachzwei** [comment]
Is this an ERC20 token? Please share the token address.

**Comment by atashzaban** [comment]
hello friend


yes. here is token address.


https://etherscan.io/token/0x9513d8679677Be3D57c7cDD30561105ee1452d69



regards

atash zaban

**Comment by catenocrypt** [comment]
Moved logo to correct address.

**Comment by atashzaban** [comment]
hi

what should we do? we must put logo in the correct folder? can you guide me?



regards

**Comment by atashzaban** [comment]
can you respond me? I am beginner now. tnx

**Pull request merged**
