### PR TITLE
Add CybrrrDOGE Logo and Info

### PR DESCRIPTION
**Pull request by CybrrrDogeDefi**
Add CybrrrDOGE Logo and Info

We are listed in https://coinmarketcap.com/currencies/cyberdoge/

### CODE REVIEW

**Comment by cryptomanz** [comment]
hello, can you answer some questions, please?
• What is the purpose of this token? How will it benefit Trust Wallet users?
 • How is the token being distributed? Are you conducting an airdrop?
 • Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?
 • Is the token listed on a centralized/decentralized exchange?
 • Is a Smart Contract audit completed? Where can we find this information?

**Comment by CybrrrDogeDefi** [comment]
hello, can you answer some questions, please?
• What is the purpose of this token? How will it benefit Trust Wallet users?
We are currently developing a game using Unity with the developer of https://store.steampowered.com/app/1383720/Cyberdoge_2077_Meme_runner/ (Take Toad studios) where you can spend and earn our token
• How is the token being distributed? Are you conducting an airdrop?
Token has been distributed through ICO on DxSale and DEX Pancakeswap
link to ICO - https://dxsale.app/app/v2_9/defipresale?saleID=2023&chain=BSC
We had conducted 0 airdrop in total our high surge in holders is due to trending in Dextool and Coinmarketcap
• Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?
Yes through DxSale with 600 soft cap and 800 hard cap. Hardcap successfully achieved
link to ICO - https://dxsale.app/app/v2_9/defipresale?saleID=2023&chain=BSC
• Is the token listed on a centralized/decentralized exchange?
As of now its only listed in decenstralized exchange pancakeswap
https://exchange.pancakeswap.finance/#/swap?outputCurrency=0xecc62bd353edd64ed31595dbc4c92801af1e2af0
• Is a Smart Contract audit completed? Where can we find this information?
Smart Contract is being audited by Dessert Finance, we initially had our Smart Contracted Audited before launch however due to feedback from community that do not want to have BLACKLIST function in the Smart Contract we had to deploy a new Smart Contract at the last minute, however we had reengaged Dessert Finance to reaudit the newly deployed Smart Contract

**Comment by CybrrrDogeDefi** [comment]
No.1 trending in CoinMarketCap https://coinmarketcap.com/trending-cryptocurrencies/

**Comment by CybrrrDogeDefi** [comment]
Smart contract audit has been updated by Dessert Finance!

https://dessertswap.finance/audits/Cyberdoge%20BEP-20%20Audit%209269559.pdf

Let me know if there is anything else you want to know! Thank you

**Pull request merged**
