### PR TITLE
Add Logo and Info for LevelUP Gaming

### PR DESCRIPTION
**Pull request by LevelUpOfficial**
Payment already done > https://github.com/trustwallet/assets/pull/15269

### CODE REVIEW

**Comment by LevelUpOfficial** [comment]
https://github.com/trustwallet/assets/pull/15789

**Comment by ramsty** [comment]
Hi!
Could you answer some questions?
• What is the purpose of this token? How will it benefit Trust Wallet users?
• How is the token being distributed? Are you conducting an airdrop?
• Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?
• Is the token listed on a centralized/decentralized exchange?
• Is a Smart Contract audit completed? Where can we find this information?

**Comment by Cryptocool1** [comment]
As per our policy, brand new tokens are not included, there is a minimum requirement of 5000 holder addresses and 10000 transactions, in order to filter out scam tokens.
See the criteria at : https://developer.trustwallet.com/assets/requirements .
on hold for now

**Comment by LevelUpOfficial** [comment]
Hello, 

Sure thing. Thank you for reaching out.

1. The token is a P2E game and platform, with daily earnings possible. It will benefit our holders that use Trust Wallet by legitimizing even more our token and indirectly the wallet itself. 

2. Distributed through a private presale airdrop, Pinksale presale, and trading through pancake swap.
Presale link: https://www.pinksale.finance/#/launchpad/0x6a50216E0FF2b74247D5b4ff15444b4b365772BC?chain=BSC
Pancakeswap link: https://pancakeswap.finance/info/token/0xc3bd3e021801a34104fcb5e29de6689a9b204513

3. Yes, we sold this token as pre-sale and private sale.

4. Its not listed on any CEX. As for DEX, it is listed on pancakeswap

5. We did not commission any 3rd party entities to audit our smart contract yet, its in planning.

Thank you, 

Best regards,

LevelUP Team

**Comment by ramsty** [comment]
Awaiting for smart contract audit. On hold for now.

**Comment by Cryptocool1** [comment]
Please come back to us when all criteria are met.
When creating a new PR make sure to mention this PR, so that we can see that fee has been paid already here.

**Pull request closed without merging**
