### PR TITLE
Update list.json

### PR DESCRIPTION
**Pull request by StakingShop**
We make rebranding our delegation service (expanded the list of supported tokens for delegation), changed name, website ( https://www.stakingshop.live ) and Logotype.
Could you also help us with replacing the logo with a new one? I can't do this on my own since I don't have access and can't change your repository, I can only make a fork. but it won't help to replace our logo with a new one in your branch. 
Can I send you a new logo by email so that you can change it for my Tezos delegation address tz1V3yg82mcrPJbegqVCPn6bC8w1CSTRp3f8
Thank you!

### CODE REVIEW

**Comment by TezoShop** [comment]
Np, i can pay 2k TWT for this change. I'm just asking you to confirm this with a live person from trust wallet.

**Comment by zachzwei** [comment]
Please post the image on this thread, we will update the logo.

**Comment by StakingShop** [comment]
Logo Staking Shop

**Comment by StakingShop** [comment]
Much appreciate!

**Pull request merged**
