### PR TITLE
Add Heroes of Mavia (ERC20)

### PR DESCRIPTION
**Pull request by nhancv**
Adding info for ERC20 token 'Heroes of Mavia'.

PR created by <a href="https://assets.trustwallet.com">TW Assets Management</a>

### CODE REVIEW

**Comment by cryptomanz1** [comment]
• What is the purpose of this token? How will it benefit Trust Wallet users?
 • How is the token being distributed? Are you conducting an airdrop?
 • Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?
 • Is the token listed on a centralized/decentralized exchange?
 • Is a Smart Contract audit completed? Where can we find this information?

**Comment by nhancv** [comment]
It's weird when you guys put this question step after payment. But please check. 
• What is the purpose of this token? How will it benefit Trust Wallet users?
=> MAVIA token is the governance token of the Heroes of Mavia project, our users use Trust Wallet, and it's useful for them to search and check prices in their portfolios.
 • How is the token being distributed? Are you conducting an airdrop?
=> The airdrop event was done. Users can buy more on CEX, and DEX
 • Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?
=> Please check at https://www.mavia.com/mavia-token for "The Mavia Token Release Schedule and Breakdown"
 • Is the token listed on a centralized/decentralized exchange?
=> Yes. The Mavia token is listed on CEX (Bybit, Kucoin, Gate.io, HTX, Crypto.com, MEXC) and DEX (Uniswap)
 • Is a Smart Contract audit completed? Where can we find this information?
=> Yes. You can find it at https://certificate.quantstamp.com/full/mavia-token/c5aa6f84-0a01-4b9e-813d-6aa7201646dd/index.html

**Comment by nhancv** [comment]
Pls check @cryptomanz1

**Comment by nhancv** [comment]
Hi @cryptomanz1, 
Thank you for merging. I can see the token logo in the Trust app now, but no price and market data are available. Do you know when it come?

**Comment by Cryptocool1** [comment]
Hi, pricing data has been enabled.

**Comment by nhancv** [comment]
It works. Thank you @Cryptocool1

**Pull request merged**
