### PR TITLE
Change Tadpole Logo

### PR DESCRIPTION
**Pull request by ngkong**
We changed our logo.
Official announcement about the new logo:

https://twitter.com/TadpoleFinance/status/1326057036405202944
https://t.me/TadpoleFinanceChannel/26

Very appreciate your help approving this PR.

Thank you

### CODE REVIEW

**Comment by ngkong** [comment]
is merge-fee-bot down?

**Comment by catenocrypt** [comment]
> is merge-fee-bot down?

We did some changes to it, checking.

**Comment by catenocrypt** [comment]
Hi! In order to compensate for the efforts of processing PRs, we kindly ask for a contribution.
Before paying the fee, make sure new tokens fulfill the [acceptance criteria](https://community.trustwallet.com/t/how-to-submit-a-token-logo/3863#how-to-get-approved) (there is no fee refund in case of rejection).
See also the [PR Fee FAQ](https://developer.trustwallet.com/add_new_asset/pr-fee).

Please pay  **1000 TWT**  with the memo **4778**  to the address `bnb1tqq9llyr3dyjd559dha6z5r5etk3qfwk07m098`.
Alternatively, 6 BNB is also accepted (same memo & address).

**QR** code: [Trust](https://api.qrserver.com/v1/create-qr-code/?size=200x200&data=https%3A%2F%2Flink.trustwallet.com%2Fsend%3Fcoin%3D714%26address%3Dbnb1tqq9llyr3dyjd559dha6z5r5etk3qfwk07m098%26amount%3D1000%26memo%3D4778) | [other wallet](https://api.qrserver.com/v1/create-qr-code/?size=200x200&data=bnb1tqq9llyr3dyjd559dha6z5r5etk3qfwk07m098%26amount%3D1000%26memo%3D4778)

*Notes*:
* [Trust Wallet Tokens (TWT)](https://community.trustwallet.com/t/trust-wallet-token-twt/4187) can be obtained through our [Referral Program](https://community.trustwallet.com/t/invite-a-friend-earn-trust-wallet-token-twt/4125) or [from DEXs/exchanges](https://community.trustwallet.com/t/where-to-get-trust-wallet-tokens/76641).
* New tokens without significant usage are rejected, see criteria mentioned above.
* One PR should be for a single project; PR's with more than 10 logos will be rejected.
* Payment evaluation happens automatically, but with a few minutes delay.  When payment is detected, an Accept Review is automatically placed on the PR, which is a condition for merge.
* Evaluating the PR is done manually, and it is merged only if all conditions are satisfied.
* TWT-BEP2 is supported (Binance Chain), TWT-BEP20 version on Smart Chain is not.

**Pull request merged**
