### PR TITLE
Add EDXA (BEP20)

### PR DESCRIPTION
**Pull request by EdxaLabs**
Adding info for BEP20 token 'EDXA'.

### CODE REVIEW

**Comment by cryptomanz** [comment]
Hello,
• What is the purpose of this token? How will it benefit Trust Wallet users?
 • How is the token being distributed? Are you conducting an airdrop?
 • Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?
 • Is the token listed on a centralized/decentralized exchange?
 • Is a Smart Contract audit completed? Where can we find this information?

**Comment by EdxaLabs** [comment]
• What is the purpose of this token? How will it benefit Trust Wallet users?
This will be a utility token for our other business https://brokaquote.com/ to facilitate deposit of withdrawal of our brokerage system. Edxa will be the point of exchange for other crypto to swap to Edxa, and interact with Brokaquote. Trustwallet is one of our recommendation to customer to use as a primary wallet to send deposit and receive withdrawal. With our token listed on Trustwallet, this will give confidence for our customer to shift to  Edxa.

• How is the token being distributed? Are you conducting an airdrop?
Currently we are distributing it via actual fiat purchase from our appointed agents that assist user to get into Brokaquote services. We did an airdrop in August 2021 via Twitter.

• Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?
Yes during go-live in July 2021. We only manage to raise 1.4% to the anticipate sale. Refer https://edxa.co/ifo

• Is the token listed on a centralized/decentralized exchange?
It is on Pancakeswap https://pancakeswap.finance/info/token/0x952cebf65f3a9f11ef0222aefe0608d26621b097

• Is a Smart Contract audit completed? Where can we find this information?
No, not yet. Due to low presale amount, we do not have enough budget for an audit. Our investor insist to have the brand to be available on Trustwallet or Coingecko before putting money. We will send for an audit once we have sufficient funding.

And we use contract fork form audited Dex, goosefinance. Its available publicly on Github or Bscscan. https://github.com/EdxaLabs/edxa-smart-contracts

**Comment by ramsty** [comment]
Awaiting for smart contract audit. On hold for now.

**Comment by EdxaLabs** [comment]
Noted. Audit result ETA in 2 days

**Comment by Cryptocool1** [comment]
Please come back to us when all criteria are met.
When creating a new PR make sure to mention this PR, so that we can see that fee has been paid already here.

**Pull request closed without merging**
