### PR TITLE
Add Evin Token Logo and Info. Requirement met

### PR DESCRIPTION
**Pull request by EvinTokenGH**
Hi again team,

Our token met holders and tx requirement finally.

Could you help to do finalize that process please ? 

Payment was done too, you can check my mentioned previous pr below;

#28697
https://github.com/trustwallet/assets/pull/28697

### CODE REVIEW

**Comment by EvinTokenGH** [comment]
@Cryptocool1 @cryptomanz1 Thanks for your help from now.

**Comment by Cryptocool1** [comment]
Hello, how did you get more than 10k holders in 2 days?

**Comment by EvinTokenGH** [comment]
Hello @Cryptocool1  again,

I hope you're well.

We started huge campaignies to reach to 10K holders. Many crypto influancers and our community supported to us too.

Trust Wallet important part of crypto world and its really important for achieve to our goals, that's why we started huge campaignies to reach to 10K holders for show our logo in trust wallet.


Regards,

Evin Team

**Comment by Cryptocool1** [comment]
Did you conduct an airdrop?

**Comment by EvinTokenGH** [comment]
Hi again,

No, team didnt do any airdrop.

Could be faster more please ?
Because we have big AMA in this week and Trust wallet logo showing is important new for our community. 

Thanks in advance,

Regards!

Ps for merge fee bot: we already paid 500 TWT  
https://github.com/trustwallet/assets/pull/28697

**Pull request closed without merging**
