### PR TITLE
Add Black Diamond (BEP20)

### PR DESCRIPTION
**Pull request by CRuzylo**
Adding info for BEP20 token 'Black Diamond'.

PR created by <a href="https://assets.trustwallet.com">TW Assets Management</a>

### CODE REVIEW

**Comment by CRuzylo** [comment]
Paid.

**Comment by Cryptocool1** [comment]
hello
• What is the purpose of this token? How will it benefit Trust Wallet users?
 • How is the token being distributed? Are you conducting an airdrop?
 • Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?
 • Is the token listed on a centralized/decentralized exchange?
 • Is a Smart Contract audit completed? Where can we find this information?

**Comment by CRuzylo** [comment]
• What is the purpose of this token? How will it benefit Trust Wallet users? Black Diamond is a deflationary token meant to reward its holders with 10% reflections proportionate to what they hold, we also have a 2% LP to consistently increase the price floor. We have a unique swap which was live day 1. Our exchange is due in 25 days. We have our NfT marketplace, wallet applications, mobile exchange & dApps all currently in development. We have partnered with SparkPR as our marketing Agency. We have many more unique plans but currently our aim is to catch up & be at a competitive level with kraken / coinbase by the end of Q4.
• How is the token being distributed? Are you conducting an airdrop? The token had already been distributed through a successful presale, Private sale, partnership & launch. The team comes from the Community Staff at UltraSafe.we are currently live on pancakeswap swap but offer a swap on our own domain as wellS
• Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale? Yes.
We had a 150BNB Presale & a 150 BNB Private sale which hit both hard caps successfully. 
• Is the token listed on a centralized/decentralized exchange? We are on Coin Gecko, Coin Market Cap, we have a listing on XT on Monday July 19. This is announced on their site, we have a listing thereafter on indoex on Friday July 23rd.
• Is a Smart Contract audit completed? Where can we find this information? We have been in contact with Certik since day 1. They have our repo & we are currently waiting on funding. We just partnered with Shield Network which provides audits to smart contracts.

**Comment by CRuzylo** [comment]
> hello
> • What is the purpose of this token? How will it benefit Trust Wallet users?
> • How is the token being distributed? Are you conducting an airdrop?
> • Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?
> • Is the token listed on a centralized/decentralized exchange?
> • Is a Smart Contract audit completed? Where can we find this information?

Answered fully!! Thanks in advance.

**Pull request merged**
