### PR TITLE
Add Pepecoin (BEP20)

### PR DESCRIPTION
**Pull request by pepecoinbsc**
Adding info for BEP20 token 'Pepecoin'.

PR created by <a href="https://assets.trustwallet.com">TW Assets Management</a>

### CODE REVIEW

**Comment by pepecoinbsc** [comment]
https://github.com/trustwallet/assets/pull/25255

Already paid on this pull request

**Comment by pepecoinbsc** [comment]
Audit report: https://app.solidproof.io/projects/pepecoin

**Comment by Cryptocool1** [comment]
Please take a look at my comment in your previous PR.

**Comment by pepecoinbsc** [comment]
> Please take a look at my comment in your previous PR.

Hi, we already changed the logo for submission to this new one

new_logo

**Comment by Cryptocool1** [comment]
Logo should be the same as on twitter and CoinMarketCap

**Comment by Cryptocool1** [comment]
You should update logo everywhere, also on bscscan.

**Pull request closed without merging**
