### PR TITLE
Add files via upload - (Payment Done On #12163)

### PR DESCRIPTION
**Pull request by hodl-token**
Add HODL 2.0 BEP20 Token
Payment Done On #12163

### CODE REVIEW

**Comment by Cryptocool1** [comment]
can you please add links to your PR?
example: https://developer.trustwallet.com/add_new_asset/repository_details

**Comment by HODLV2** [comment]
Sorry - Lost you here! :) Can you help me in what else is required / 
added./ Happy to do so.

Link to New PR: https://github.com/trustwallet/assets/pull/12748

**Comment by Cryptocool1** [comment]
fixed

**Comment by HODLV2** [comment]
Many Thanks

**Pull request merged**
