### PR TITLE
Add TBULL (BEP20)

### PR DESCRIPTION
**Pull request by emmanbol**
This PR is being closed due to inactivity. If you wish to continue, please have us reopen the PR before sending your payment.
Do NOT send payments for closed PR, as the fee may by lost!
  (213 vs. 99 hrs)

### CODE REVIEW

**Comment by catenocrypt** [comment]
As per our policy, brand new tokens are not included, there is a minimum requirement of 2500 holder addresses and 5000 transactions, in order to filter out scam tokens.
See the criteria at (mentioned in the first message by the bot): https://community.trustwallet.com/t/how-to-submit-a-token-logo/3863).
This token has no real usage yet (7 holders). Closing PR for now. Please come back to us when all criteria are met.  Multi-chain and staking tokens may get special treatment, let us know if this is the case. 

https://bscscan.com/token/0xC66ec7daCaD6871c5327e120e57494Cef7A16fdB

**Comment by emmanbol** [comment]
is there anything I can do from this communication or a new interaction have to be opened?

Thanks on your anticipated Response.

**Comment by catenocrypt** [comment]
Reopening.

**Comment by emmanbol** [comment]
> 
> 
> Reopening.

Great.

So, How can I proceed. I can see "Reopened"

Thanks.

**Pull request closed without merging**
