### PR TITLE
Add Pazzi to Trustwallet

### PR DESCRIPTION
**Pull request by MalayTripathi**
This PR is to add Pazzi token to Trust wallet. Please guide us through this process by adding comments to this PR. We have added info.json and logo.png in the assets folder for ethereum.

### CODE REVIEW

**Comment by catenocrypt** [comment]
As per our policy, brand new tokens are not included, there is a minimum requirement of 500 holder addresses and 1000 transactions, in order to filter out scam tokens.
See the criteria at (mentioned in the first message by the bot): https://community.trustwallet.com/t/how-to-submit-a-token-logo/3863#how-to-get-approved
This token has low usage yet (47). Rejecting PR for now. Please come back to us when all criteria are met.

https://etherscan.io/token/0xf2d4a5dd017d78289c404de98c37ce245e417c7f

**Comment by MalayTripathi** [comment]
@catenocrypt The token contract address that I have submitted on behalf of the Pazzi Team is a new contract because the old contract had to be discarded due to the KuCoin hack.

This is the older contract address: https://etherscan.io/token/0xbcd8756ea481608ea3dd5a555493305cf0a79640

We had 638 holders and numerous transactions but after the hack we had created a new contract and are creating a Dapp for token swap. 

Does this help in the listing?

**Comment by catenocrypt** [comment]
Thanks for the clarification, token circulation is condition is satisfied by old token.

There is one issue with this PR: contract folder name should be in checksum format.  Could you fix that?  Rename to '0xf2D4A5dd017d78289C404DE98c37cE245e417C7f' (or just run `npm install && npm run fix`).

```
-  X 'Folder structure for chain ethereum (ethereum fork)':  1 errors
   X   'Expect asset at path /home/runner/work/assets/assets/blockchains/ethereum/assets/0xf2d4a5dd017d78289c404de98c37ce245e417c7f in checksum: '0xf2D4A5dd017d78289C404DE98c37cE245e417C7f''
```

**Comment by MalayTripathi** [comment]
> Thanks for the clarification, token circulation is condition is satisfied by old token.
> 
> There is one issue with this PR: contract folder name should be in checksum format. Could you fix that? Rename to '0xf2D4A5dd017d78289C404DE98c37cE245e417C7f' (or just run `npm install && npm run fix`).
> 
> ```
> -  X 'Folder structure for chain ethereum (ethereum fork)':  1 errors
>    X   'Expect asset at path /home/runner/work/assets/assets/blockchains/ethereum/assets/0xf2d4a5dd017d78289c404de98c37ce245e417c7f in checksum: '0xf2D4A5dd017d78289C404DE98c37cE245e417C7f''
> ```

I have changed the folder name to the checksum of the contract address. Please check and let me know if all is good.

**Comment by catenocrypt** [comment]
Only one file folder was renamed, I renamed the folder of log.png as well now.

**Comment by catenocrypt** [comment]
Check OK, fee payment is missing.

**Comment by MalayTripathi** [comment]
> Check OK, fee payment is missing.

Ok. Give me some time. I will ask the team to pay.

**Pull request merged**
