### PR TITLE
Add DogeFather (BEP20)

### PR DESCRIPTION
**Pull request by cryptoinu-abcd**
Adding info for BEP20 token 'DogeFather'.

PR created by <a href="https://assets.trustwallet.com">TW Assets Management</a>

### CODE REVIEW

**Comment by dogefa** [comment]
• What is the purpose of this token? How will it benefit Trust Wallet users?
DogeFather is a community owned Meme token, which aims to build a completely decentralized ecosystem. It aims to develop dGames, dChart, dSwap, dPad. This will benefit trust wallet users to be able to check price, and able to recognise the real DogeFather token.

• How is the token being distributed? Are you conducting an airdrop?
Token is being distributed at Pancake swap, we are not conducting an airdrop.

• Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?
We did not conduct any ico or presale.

• Is the token listed on a centralized/decentralized exchange?
Token is listed on Pancake swap.

• Is a Smart Contract audit completed? Where can we find this information?
We did a smart contract audit with Solid Proof.

The audit can be view at 
https://raw.githubusercontent.com/solidproof/projects/main/DogeFather/SmartContract_Audit_Solidproof_DogeFather.pdf

**Comment by Cryptocool1** [comment]
• What is the purpose of this token? How will it benefit Trust Wallet users?
 • How is the token being distributed? Are you conducting an airdrop?
 • Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?
 • Is the token listed on a centralized/decentralized exchange?
 • Is a Smart Contract audit completed? Where can we find this information?

**Comment by dogefa** [comment]
• What is the purpose of this token? How will it benefit Trust Wallet users?
DogeFather revolve around the DogeFather idea. A Father authority which creates decentralize framework which looks after DeFi with 4 key structures – DEX Swap, GameFi, Launch Pad, Charting. This will benefit DogeFather Trust Wallet users to be able to identify the real DogeFather token, check price, information and accurate details.

• How is the token being distributed? Are you conducting an airdrop?
The token is being distributed via Pancake swap. We are not conducting an airdrop.

• Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?
There is no ICO or presale.

• Is the token listed on a centralized/decentralized exchange?
Token is listed on Pancake swap.

• Is a Smart Contract audit completed? Where can we find this information?
We are audited by SolidProof. You may check it on the following website:
https://raw.githubusercontent.com/solidproof/projects/main/DogeFather/SmartContract_Audit_Solidproof_DogeFather.pdf

**Comment by cryptoinu-abcd** [comment]
• What is the purpose of this token? How will it benefit Trust Wallet users?
DogeFather plan to revolve around the DogeFather idea. A Father authority which creates decentralise framework which looks after DeFi with 4 key structures – DEX Swap, GameFi, Launch Pad, Charting. It will benefit Trust Wallet users to get price, token information and details of the real DogeFather token.

• How is the token being distributed? Are you conducting an airdrop?
Token is being distributed by Pancake Swap. No airdrop is conduct.

• Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?
No ICO and presale.

• Is the token listed on a centralized/decentralized exchange?
Listed on Pancake Swap.

• Is a Smart Contract audit completed? Where can we find this information?
Smart contract audit with SolidProof is completed. You may check it on https://raw.githubusercontent.com/solidproof/projects/main/DogeFather/SmartContract_Audit_Solidproof_DogeFather.pdf

**Pull request merged**
