### PR TITLE
add MiloInu logo and info

### PR DESCRIPTION
**Pull request by calvingreen**
add MiloInu logo and info

### CODE REVIEW

**Comment by calvingreen** [comment]
How to fix:  number of holders not checked: please, check it manually

**Comment by cryptomanz** [comment]
• What is the purpose of this token? How will it benefit Trust Wallet users?
 • How is the token being distributed? Are you conducting an airdrop?
 • Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?
 • Is the token listed on a centralized/decentralized exchange?
 • Is a Smart Contract audit completed? Where can we find this information?

**Comment by calvingreen** [comment]
• What is the purpose of this token? How will it benefit Trust Wallet users?

The project aims to create a patented virtual idol in the crypto market, where the idol would be build from the richness of animation. It will be marketed in different form like NFT, physical doll and peripheral product, GameFi and competitive LAN e-sports and other industrial chains. Using the professional marketing techniques in both online and offline manner along with the patented idol to enter the market, by combining crypto coin, NFT, GameFi to breakthrough the current bottleneck of the crypto market. The fund raised will be used to fix the liquidity issue in the crypto market, creating a new type of crypto product. 

By participating in MILO investment, users can use MILO for various operations. They can also increase their personal assets when MILO currency price rises due to early purchase of MILO

• How is the token being distributed? Are you conducting an airdrop?
1. Token Burn: 42% of Total Supply  
2. PancakeSwap: 25% of Total Supply, Locked for 69 Years
3. Institution Investors: 5% of Total Supply and are not locked 
4. Play to Earn: 10% of Total Supply, Locked for 6 months, fully unlock after 6 months 
5. Development Team: 5% of Total Supply, Locked for 3 months, fully unlock after 3 months 
6. Marketing: To be used for listing, consultation and marketing fee, takes up to 12% of total supply and are not locked 
7. Airdrop: 1% of Total Supply, Only limited to BEP-20 Dogecoin holder, claim according to the amount of Dogecoin


• Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?

Without the ICO

• Is the token listed on a centralized/decentralized exchange?
Pancake、BKEX、MEXC

• Is a Smart Contract audit completed? Where can we find this information?

MILO has conducted a Certik audit

https://www.certik.com/projects/milo-inu

**Comment by cryptomanz** [comment]
As per our policy, brand new tokens are not included, there is a minimum requirement of 10,000 holder addresses and 15,000 transactions, in order to filter out scam tokens.
See the criteria at : https://developer.trustwallet.com/assets/requirements .

**Comment by cryptomanz** [comment]
Please come back to us when all criteria are met.
When creating a new PR make sure to mention this PR, so that we can see that fee has been paid already here.

**Comment by calvingreen** [comment]
> Please come back to us when all criteria are met. When creating a new PR make sure to mention this PR, so that we can see that fee has been paid already here.

we come back, we are 10,192 holder addresses and 81,537 transactions

**Pull request closed without merging**
