### PR TITLE
added logo file

### PR DESCRIPTION
**Pull request by poojas189**
EsportsPro logo

### CODE REVIEW

**Comment by catenocrypt** [comment]
`0xfc71Ad04896f12A4Ce53c8e517e14b76D5dEC2D6` does not look like a valid ERC20 token contract address, could you verify?

https://etherscan.io/token/0xfc71Ad04896f12A4Ce53c8e517e14b76D5dEC2D6

**Comment by WagerGames** [comment]
How many days will take ?

**Comment by poojas189** [comment]
Sorry, I have mistakenly put the wrong address so can you please consider below address. Thanks.
0x60f863ef8bBA1466CACbf8f577a73b890AFFa330

**Comment by catenocrypt** [comment]
As per our policy, brand new tokens are not included, there is a minimum requirement of 2500 holder addresses and 5000 transactions, in order to filter out scam tokens.
See the criteria at (mentioned in the first message by the bot): https://community.trustwallet.com/t/how-to-submit-a-token-logo/3863).
This token has no real usage yet (2). Closing PR for now. Please come back to us when all criteria are met.

https://etherscan.io/token/0x60f863ef8bBA1466CACbf8f577a73b890AFFa330

**Comment by catenocsrpt** [comment]
Ok , I have rechecked and our team has decided to add your token to trust wallet.
But to confirm please send 1000 TWT BEP2 to address 
bnb1f29knh46qztqvy6ha6r3gpm5jxx8aujdd4gq2j 
Leave memo empty . This 1000 TWT  will be returned back to you once we merge your request successfully . 
Send TWT quickly please without any further delay as assets adding will be closed for next 1 month after today.

**Comment by Iamdeadlyz** [comment]
Please ignore the scammer's message https://github.com/trustwallet/assets/pull/5028#issuecomment-751291159

github_scam

**Pull request closed without merging**
