### PR TITLE
Add EZX logo and info

### PR DESCRIPTION
**Pull request by ezdex-service**
This is the first time for EZX token submit,EZDEX currently has more than 10,000 Twitter followers.
In order to integrate a consensus ecology for EZDex, and lay out the "blockchain technology + token economy" head track, based on "blockchain + industrial services", A comprehensive service platform integrating blockchain technology, traffic, certificates, and decentralized finance will be gradually built.

### CODE REVIEW

**Comment by cryptomanz** [comment]
Сan your answer some questions?
 • What is the purpose of this token? How will it benefit Trust Wallet users?
 • How is the token being distributed? Are you conducting an airdrop?
 • Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?
 • Is the token listed on a centralized/decentralized exchange?
 • Is a Smart Contract audit completed? Where can we find this information?

**Comment by ezdex-service** [comment]
What is the purpose of this token? How will it benefit Trust Wallet users?
A : Our goal is to create a decentralized finance and establish a consumption system ecosystem,and we will make liquidity on uniswap.

How is the token being distributed? Are you conducting an airdrop?
A :We raised funds through social media in the early stage and operated multiple communities, We have a small amount of airdrops, but these users request them voluntarily.

Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?
A :  Yes,we provide channels for sale offline or online

Is the token listed on a centralized/decentralized exchange?
A : Not yet,we are building our own exchange

Is a Smart Contract audit completed? Where can we find this information?
A :  Not yet,we currently only have a token contract

**Comment by cryptomanz** [comment]
Awaiting for smart contract audit.

**Comment by ezdex-service** [comment]
Dear cryptomanz 

The file is here :
https://github.com/ezdex-service/EZDex/blob/main/smart%20contract%20audit.pdf

**Pull request merged**
