### PR TITLE
Add 1FirstCoin (BEP20)

### PR DESCRIPTION
**Pull request by belananumjai**
Adding info for BEP20 token '1FirstCoin'.

PR created by <a href="https://assets.trustwallet.com">TW Assets Management</a>

### CODE REVIEW

**Comment by belananumjai** [comment]
My 1FirstCoin (BEP20) token logo does not appear in trust wallet.
I have already paid for the processing 1 times.
Please make me.

Upload  1FirstCoin (BEP20) #9664
Will I have to wait?
Please help me.
Thank you.

(logo,info)
https://drive.google.com/drive/folders/1IUha3BNwvkgsoMDEWvDUADQXyJpnDkDQ?usp=sharing

**Comment by belananumjai** [comment]
{
    "name": "1FirstCoin",
    "website": "https://1first.io/",
    "description": "1FirstCoin is Next generation of Defi yield generating, community driven. Earn interest by holding.",
    "explorer": "https://bscscan.com/token/0x0bbb21a578ba33624e70bf163fc26b737a5b5557",
    "type": "BEP20",
    "symbol": "1FIRST",
    "decimals": 8,
    "status": "active",
    "id": "0x0bbb21a578ba33624e70bf163fc26b737a5b5557"
}

(logo,info)
https://drive.google.com/drive/folders/1IUha3BNwvkgsoMDEWvDUADQXyJpnDkDQ?usp=sharing

**Comment by Cryptocool1** [comment]
Error Code: Invalid Token

**Comment by Cryptocool1** [comment]
fixed the explorer

**Comment by Cryptocool1** [comment]
As per our policy, brand new tokens are not included, there is a minimum requirement of 2500 holder addresses and 5000 transactions, in order to filter out scam tokens.
See the criteria at  https://community.trustwallet.com/t/how-to-submit-a-token-logo/3863).

**Comment by cryptomanz** [comment]
Please create new PR, follow doc https://community.trustwallet.com/t/how-to-submit-a-token-logo/3863
You may want to try our new Assets app in beta; go to https://assets.trustwallet.com, log on with Github, enter contract ID, logo and some additional info, and it will create a PR for you.
See https://community.trustwallet.com/t/how-to-submit-a-token-logo-using-assets-app/82957.

make sure to mention this PR, so that we can see that fee has been paid already here.

**Pull request closed without merging**
