### PR TITLE
Add upBNB (upBNB) logo and info

### PR DESCRIPTION
**Pull request by sifttung**
From the developers of Rootkit Finance and UniFund - upBNB (upBNB) is The first ERC-31337 token on Binance Smart Chain. upBNB will be the cornerstone asset and vault for the upToken ecosystem on BSC.

Please add our upBNB(upBNB) logo and info.

### CODE REVIEW

**Comment by sifttung** [comment]
2 BNB contribution has been sent as requested

**Comment by Cryptocool1** [comment]
Hello,
can you capitalize all letters in your symbol?

**Comment by sifttung** [comment]
All letters in symbol capitalized as requested

**Comment by catenocrypt** [comment]
Correction needed: This is a BEP20 token, correct folder is `blockchains/smartchain/assets`.

**Comment by sifttung** [comment]
Corrected directory as requested  and added checksum considerations @catenocrypt @Cryptocool1

**Pull request merged**
