### PR TITLE
Request to add RedFEG

### PR DESCRIPTION
**Pull request by RedTeam-Blockchain**
The payment has already been made at the time of the first pull request.

### CODE REVIEW

**Comment by Cryptocool1** [comment]
#12166

**Comment by Cryptocool1** [comment]
hello,
Is a Smart Contract audit completed?

**Comment by RedTeam-Blockchain** [comment]
Yes

**Comment by RedTeam-Blockchain** [comment]
[RedFeg Full Smart Contract Security Audit.pdf](https://github.com/trustwallet/assets/files/6911877/RedFeg.Full.Smart.Contract.Security.Audit.pdf)

**Comment by Cryptocool1** [comment]
can you please add links to your PR?
example: https://developer.trustwallet.com/add_new_asset#info-json-contents

**Pull request merged**
