### PR TITLE
Add IL CAPO (BEP20)

### PR DESCRIPTION
**Pull request by AlanGergi**
Adding info for BEP20 token 'IL CAPO'.

PR created by <a href="https://assets.trustwallet.com">TW Assets Management</a>

### CODE REVIEW

**Comment by Cryptocool1** [comment]
• What is the purpose of this token? How will it benefit Trust Wallet users?
 • How is the token being distributed? Are you conducting an airdrop?
 • Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?
 • Is the token listed on a centralized/decentralized exchange?
 • Is a Smart Contract audit completed? Where can we find this information?

**Comment by AlanGergi** [comment]
> What is the purpose of this token? How will it benefit Trust Wallet users?

CAPO trading volume reached $120 million in just 5 days;
The asset showed an increase of more than 10,000%, leaving at least the possibility of retesting the ATH from the current price levels against the backdrop of upcoming events;
CAPO became the TOP 1 meme token in the BSC network;
The token entered the TOP-4 in the terms of trading volume in all blockchains;
The number of CAPO holders reached 12,000 in just 5 days.

> • How is the token being distributed? Are you conducting an airdrop?

Total Supply was 1 000 000 000 Tokens! 
100 000 000 Tokens Burnt
350,000,000 Tokens Sold on presale 
166,250,000 Tokens On pancake liquidity pull
Else Belongs to almost 15 000 holders
No airdrops

> • Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?
350,000,000 Tokens Sold on presale on pinksale! Here is the link of presale: https://www.pinksale.finance/launchpad/0x1c96CfD331e7aEf4bFbF86cB6f977e75B8E240B2?chain=BSC

> • Is the token listed on a centralized/decentralized exchange?
Yes, it is listed on Dexes, and CEXes like MEXC, Bitget, Poloniex and today will get listed on Bybit

> • Is a Smart Contract audit completed? Where can we find this information?

All Information on $CAPO token by the link below:

https://linktr.ee/ilcapocoin

**Comment by Cryptocool1** [comment]
Please send you smart contract audit here

**Comment by AlanGergi** [comment]
> Please send you smart contract audit here

0x922722E9Ef614EC9A3E94b78496e92AbFBb5A624

**Comment by Cryptocool1** [comment]
That is contract address, not smart contract audit.

**Comment by AlanGergi** [comment]
https://blocksafu.com/audit/0x922722E9Ef614EC9A3E94b78496e92AbFBb5A624

**Comment by AlanGergi** [comment]
Why the "Swap" option wasn't added to trust wallet?

**Pull request merged**
