### PR TITLE
Add MetaMiM (POLYGON)

### PR DESCRIPTION
**Pull request by mmlhsnii**
Adding info for POLYGON token 'MetaMiM'.

PR created by <a href="https://assets.trustwallet.com">TW Assets Management</a>

### CODE REVIEW

**Comment by mmlhsnii** [comment]
i want add metamim logo in Trust wallet

**Comment by Seifollahy** [comment]
> Adding info for POLYGON token 'MetaMiM'.
> 
> 
> 
> PR created by <a href="https://assets.trustwallet.com">TW Assets Management</a>

**Comment by Seifollahy** [comment]
> i want add metamim logo in Trust wallet

**Comment by mmlhsnii** [comment]
info its ok ?

**Comment by Cryptocool1** [comment]
• What is the purpose of this token? How will it benefit Trust Wallet users?
 • How is the token being distributed? Are you conducting an airdrop?
 • Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?
 • Is the token listed on a centralized/decentralized exchange?
 • Is a Smart Contract audit completed? Where can we find this information?

**Comment by mmlhsnii** [comment]
MetaMiM Best Project in BSC world and Big game in metaverse. MTI build Web3 Game and Dapp website like staking and farm , Lottery , Wallet app , Dao , Defi Swap.


yes i conducting aitdrop ; bot id  : @MetaMiMbot
i sale this token in presale
listing start after end airdrop
all information in telegram chaanel : https://t.me/metamim

**Comment by Cryptocool1** [comment]
Hello, 
Please see our requirements: 
- Airdrop tokens are excluded
- We require smart contract audit from reputable companies ( Techrate, Hacken, Certik, Desert Finance) 
For airdrop tokens the circulation criteria - 15.000 holders and 20.000 transactions. 
Please come back to us when all criteria are met

**Pull request closed without merging**
