### PR TITLE
add hbtc contract logo

### PR DESCRIPTION
**Pull request by AriesWmj**
please add hbtc logo, thank you.

### CODE REVIEW

**Comment by catenocrypt** [comment]
Could you please add an `info.json` file next to the logo.png, with info about the project, of the form:
https://github.com/trustwallet/assets/blob/master/blockchains/ethereum/assets/0x0000000000085d4780B73119b644AE5ecd22b376/info.json

**Comment by catenocrypt** [comment]
Still waiting for info.json, see above

**Comment by zachzwei** [comment]
Please provide more details about this project. We will be closing this for now.
You can reopen when you have met the requirements mentioned here:
https://community.trustwallet.com/t/how-to-submit-a-token-logo/3863#how-to-get-approved

You can follow this format when adding an info.json file:

``` {
   "name":"Bitcoin",
   "website":"https://bitcoin.org",
   "source_code":"https://github.com/bitcoin",
   "white_paper":"https://bitcoin.org/bitcoin.pdf",
   "short_description":"Bitcoin is a cryptocurrency and worldwide payment system.",
   "explorer":"https://blockchain.info",
   "research":"https://research.binance.com/en/projects/bitcoin"
}

**Comment by AriesWmj** [comment]
reopen #3657

**Comment by AriesWmj** [comment]
@zachzwei  how to reopen this PR? I can't find the method. So I create new one #3706, but the check does not pass. I don't know how to fix this.

**Comment by catenocrypt** [comment]
Payment considered to #3706

**Pull request closed without merging**
