### PR TITLE
Add Save Baby Doge (BEP20)

### PR DESCRIPTION
**Pull request by dracmic**
Adding info for BEP20 token 'Save Baby Doge'.

PR created by <a href="https://assets.trustwallet.com">TW Assets Management</a>

### CODE REVIEW

**Comment by dracmic** [comment]
@Cryptocool1 @catenocrypt  @zachzwei  can you please help as I've paid.

**Comment by Cryptocool1** [comment]
Hello, what is the purpose of this token?

**Comment by dracmic** [comment]
Hello @Cryptocool1 ,

The purpose of the token is to give back to their holders during the way with giveaways and events. We will organize also charity events for with public donations to dog charities and help pups in needs.

Best regards.

**Comment by dracmic** [comment]
@Cryptocool1 @zachzwei i don't want to be stressful but could I get an update?

**Comment by Cryptocool1** [comment]
This token will be on hold until CMC listing

**Comment by Cryptocool1** [comment]
please create new PR when your token will be listed on CMC
make sure to mention this PR so that fee can can be reused

**Pull request closed without merging**
