### PR TITLE
PRIVATEUM/PVM token logo and description files.

### PR DESCRIPTION
**Pull request by arsmagic**
PRIVATEUM/PVM token info.json and logo.png files for update in TrustWallet

### CODE REVIEW

**Comment by Cryptocool1** [comment]
Correction needed:
This is a BEp20 token, correct folder is blockchains/smartchain/assets. Please correct.

**Comment by arsmagic** [comment]
> Correction needed:
> This is a BEp20 token, correct folder is blockchains/smartchain/assets. Please correct.

Thanks, updated as requested.
Can you, please, proceed with review?

**Comment by Cryptocool1** [comment]
> > Correction needed:
> > This is a BEp20 token, correct folder is blockchains/smartchain/assets. Please correct.
> 
> Thanks, updated as requested.
> Can you, please, proceed with review?

folder is ok now.
correction needed:
Contract is not in checksum format, should be 0x71afF23750db1f4edbE32C942157a478349035b2 (not 0x71aff23750db1f4edbe32c942157a478349035b2). Please rename it.

**Comment by arsmagic** [comment]
> > > Correction needed:
> > > This is a BEp20 token, correct folder is blockchains/smartchain/assets. Please correct.
> > 
> > 
> > Thanks, updated as requested.
> > Can you, please, proceed with review?
> 
> folder is ok now.
> correction needed:
> Contract is not in checksum format, should be 0x71afF23750db1f4edbE32C942157a478349035b2 (not 0x71aff23750db1f4edbe32c942157a478349035b2). Please rename it.

Thanks indeed for such a thorough guidance!
Too many details to keep an eye on!
Updated accordingly, looks like the bot likes it too.
Please review the submission one more time.
I am very grateful for your attentive support.

**Pull request merged**
