### PR TITLE
Add PlayDapp (PLA) (ERC20)

### PR DESCRIPTION
**Pull request by playdapp**
Adding info for ERC20 token 'PlayDapp (PLA)'.

PR created by <a href="https://assets.trustwallet.com">TW Assets Management</a>

### CODE REVIEW

**Comment by Cryptocool1** [comment]
hello,
can you please delete unnecessary files:
- blockchains/ethereum/assets/0x5f5b176553e51171826d1a62e540bc30422c7717/logo.png
- test/index.js

**Comment by playdapp** [comment]
@Cryptocool1 @cryptomanz we deleted unnecessary files. Please check it again

**Comment by Cryptocool1** [comment]
As per our policy, brand new tokens are not included, there is a minimum requirement of 2500 holder addresses and 5000 transactions, in order to filter out scam tokens.
See the criteria at (mentioned in the first message by the bot): https://community.trustwallet.com/t/how-to-submit-a-token-logo/3863).

**Comment by Cryptocool1** [comment]
still 126 holders.
closing PR for now.
Please come back to us when all criteria are met.
When creating a new PR make sure to mention this PR, so that we can see that fee has been paid already here.

**Pull request closed without merging**
