### PR TITLE
Add Soft Mining AI (BEP20)

### PR DESCRIPTION
**Pull request by nbertaioli**
Adding info for BEP20 token 'Soft Mining AI'.

PR created by <a href="https://assets.trustwallet.com">TW Assets Management</a>

### CODE REVIEW

**Comment by nbertaioli** [comment]
I didn't listed my token in any exchange yet. Is it required just to show my logo in trust app?

**Comment by nbertaioli** [comment]
My token has actually 10057 holders
Here is the link to access and also a picture showing how many holders we have right now.

https://bscscan.com/token/0xbaB0CFe0ceae67D6dAe64d3CBdB34A5F25EAe13F

holders

**Comment by Cryptocool1** [comment]
• What is the purpose of this token? How will it benefit Trust Wallet users?
 • How is the token being distributed? Are you conducting an airdrop?
 • Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?
 • Is the token listed on a centralized/decentralized exchange?
 • Is a Smart Contract audit completed? Where can we find this information?

**Comment by nbertaioli** [comment]
@Cryptocool1 

• What is the purpose of this token? How will it benefit Trust Wallet users?
The token is the representation of our company in the cryptocurrency market. We will use it to ensure that users can be part of our company by holding this asset in their digital wallets.

• How is the token being distributed? Are you conducting an airdrop?
The token is distributed at different times within our platform. When they register, when they meet registration regularization targets, when they complete some specific tasks within our platform.

• Did you sell the tokens at an Initial Coin Offering (ICO) or a presale token?
No

• Is the token listed on a centralized/decentralized exchange?
Not yet

• Is a Smart Contract audit completed? Where can we find this information?
We have not carried out any audits yet, we intend to do this closer to the listing of our token on exchanges.

**Comment by Cryptocool1** [comment]
After careful review of your submission, it looks like this token has not undergone any security audit. The request will be closed until further notice.

To know more about the token approval guidelines, please check this article: [How to Submit Token Logo](https://developer.trustwallet.com/listing-new-assets/requirements).

Feel free to re-open pull request once you meet those requirements.

**Pull request closed without merging**
