### PR TITLE
NMW Token

### PR DESCRIPTION
**Pull request by SAVE2014**
adding NMW Token

### CODE REVIEW

**Comment by SAVE2014** [comment]
how can I check manually number of holders?

**Comment by Cryptocool1** [comment]
> how can I check manually number of holders?

your number of holders is ok.

**Comment by Cryptocool1** [comment]
• What is the purpose of this token? How will it benefit Trust Wallet users?
 • How is the token being distributed? Are you conducting an airdrop?
 • Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?
 • Is the token listed on a centralized/decentralized exchange?
 • Is a Smart Contract audit completed? Where can we find this information?

**Comment by SAVE2014** [comment]
hi, I wanna add logo to NMW Token.

**Comment by ThaiuLinh** [comment]
Vào 0:00, Th 7, 28 thg 1, 2023 SAVE2014 ***@***.***> đã viết:

**Pull request closed without merging**
