### PR TITLE
Add Baby Floki Up Logo and Info

### PR DESCRIPTION
**Pull request by babyflokiup1**
Add Baby Floki Up Logo and Info

### CODE REVIEW

**Comment by babyflokiup1** [comment]
Payment Paid, pls check

**Comment by Cryptocool1** [comment]
hello,
• What is the purpose of this token? How will it benefit Trust Wallet users?
 • How is the token being distributed? Are you conducting an airdrop?
 • Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?
 • Is the token listed on a centralized/decentralized exchange?
 • Is a Smart Contract audit completed? Where can we find this information?

**Comment by babyflokiup1** [comment]
> hello, • What is the purpose of this token? How will it benefit Trust Wallet users? • How is the token being distributed? Are you conducting an airdrop? • Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale? • Is the token listed on a centralized/decentralized exchange? • Is a Smart Contract audit completed? Where can we find this information?

Hello
-As the little brother of $FLOKI, Baby Floki Up is here to bring the cutest most inspiring coin of the whole Doge family thanks to the #DogeFather Elon Musk. Similar to Dogecoin, Shiba Inu and $FLOKI, BFU has been birthed by fans all around the world. BFU has learned lessons from these other coins to become the strongest member of the Doge Family thanks to the Buy-back mechanism and rewards system. Ready for the rise of The Doge Family and BFU. Baby Floki Up has two main missions: provide the wealth for humanity as a money maker and creating a healthy - long term development based on the buyback mechanism. BFU token will attract many new users to use Trust Wallet, and make it more popular
- You can check tokenomic here, and we already completed the Airdrop Round 1 for 105 lucky users : https://babyflokiup.finance/#token
-Tokens were pre-sold at link: https://www.pinksale.finance/#/launchpad/0x91C09926FaC47F3a0f878B2C0f2b42b9d65F7ffB?chain=BSC
-Token has been listed at PancakeSwap, Coingecko and Coinmarketcap
- Smart Contract audited by Solidproof, audit link: https://github.com/solidproof/smart-contract-audits/blob/main/SmartContract_Audit_Solidproof_BabyFlokiUp.pdf

**Comment by babyflokiup1** [comment]
@Cryptocool1 hi, Are you there? pls check the answer! thank you!

**Comment by babyflokiup1** [comment]
Thank you!

**Pull request merged**
