### PR TITLE
PancakeTools Token

### PR DESCRIPTION
**Pull request by marketingcryptoagency**
Add PancakeTools Token

### CODE REVIEW

**Comment by marketingcryptoagency** [comment]
please check the same and update us

**Comment by catenocrypt** [comment]
Please change the id field in the info json

❌ Id does not match contract, should be 0x3b831d36ed418e893F42d46ff308C326C239429f, not 0x3b831d36ed418e893f42d46ff308c326c239429f. Please rename.

**Comment by marketingcryptoagency** [comment]
> Please change the id field in the info json
> 
> ❌ Id does not match contract, should be 0x3b831d36ed418e893F42d46ff308C326C239429f, not 0x3b831d36ed418e893f42d46ff308c326c239429f. Please rename.

I have tried to rename it, and it works on my Github Desktop, but the same is not committed to Github. Please help!

**Comment by catenocrypt** [comment]
This refers to the id field within the info.json file, not the filename! Please change the id field in the file.

**Comment by erience** [comment]
@catenocrypt  please update the status

**Comment by marketingcryptoagency** [comment]
@catenocrypt  looks like issue is fixed, CI passed. 

however merge-boot has some objections for some reason... I assume it is confused because all this previous errors.

**Pull request merged**
