### PR TITLE
Add logo

### PR DESCRIPTION
**Pull request by starsxplatform**
we want to add STAX logo

### CODE REVIEW

**Comment by starsxplatform** [comment]
which section should I edit in JSON file? could you please fix this?

**Comment by starsxplatform** [comment]
dear @Cryptocool1 when was our logo add on trust?

**Comment by Cryptocool1** [comment]
• What is the purpose of this token? How will it benefit Trust Wallet users?
 • How is the token being distributed? Are you conducting an airdrop?
 • Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?
 • Is the token listed on a centralized/decentralized exchange?
 • Is a Smart Contract audit completed? Where can we find this information?

**Comment by starsxplatform** [comment]
StarsX is the ideal Gaming Platform that can be considered a DEX for NTFs, for those who want to win big by applying their expertise and understanding of the sport. StarsX uses Fractionable NFT’s and with the combination of ERC-721 and Bancor Smart Tokens price of various tokens can be monitored and transacted automatically.

our token distribution is on whitepaper https://starx.gitbook.io/starsx-whitepaper/the-starsx-governance-token

we are still on private sale and we are going to launch our platform this week 
also our audit is working on it by https://techrate.org/ team

**Comment by starsxplatform** [comment]
@Cryptocool1 everything is ok?

**Comment by Cryptocool1** [comment]
awaiting for smart contract audit, on hold for now

**Comment by starsxplatform** [comment]
sure I will provide it 
thanks

**Comment by Cryptocool1** [comment]
Please create new PR, follow doc https://developer.trustwallet.com/assets/requirements
You may want to try our Assets app in beta; go to https://assets.trustwallet.com, log on with Github, enter contract ID, logo and some additional info, and it will create a PR for you.
See https://developer.trustwallet.com/assets/repository_details

**Pull request closed without merging**
