### PR TITLE
Add Tether USD (BEP20)

### PR DESCRIPTION
**Pull request by StepCrypto**
Adding info for BEP20 token 'Tether USD'.

PR created by <a href="https://assets.trustwallet.com">TW Assets Management</a>

### CODE REVIEW

**Review by StepCrypto — COMMENTED** [review]
apple-touch-icon

**Review by StepCrypto — COMMENTED** [review]
"Holders":  "3"

**Comment by StepCrypto** [comment]
WHAT MUST I DO FOR THE FASTEST OUTCOME OF MY PROJECT?

**Comment by cryptomanz1** [comment]
Hello, 
Please see our documentation https://developer.trustwallet.com/listing-new-assets/requirements , we do not accept scam tokens that use someone's brand

**Pull request closed without merging**
