### PR TITLE
Add NBM Token

### PR DESCRIPTION
**Pull request by NFTBlackMarket**

### CODE REVIEW

**Comment by Cryptocool1** [comment]
hello,
• What is the purpose of this token? How will it benefit Trust Wallet users?
 • How is the token being distributed? Are you conducting an airdrop?
 • Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?
 • Is the token listed on a centralized/decentralized exchange?
 • Is a Smart Contract audit completed? Where can we find this information?

**Comment by NFTBlackMarket** [comment]
Hello 

_ In NFTBlackMarket you can create, collect and trade digital assets.
You can NFT Your ART, GIF, MUSIC, VIDEO, and PATENT.
The NBM token is powering NFTBlackMarket. It will be used to create and trade NFT Tokens.
We support Trust Wallet and Trust Wallet users can easily connect to our platform and create or trade NFT tokens.

_43.7% Burned, 5,6% Development and Marketing, 50.7% locked in PancakeSwap.

_ No we Added Tokens on pancakeSwap for public sale 

_Yes, PancakeSwap

https://exchange.pancakeswap.finance/#/swap?inputCurrency=BNB&outputCurrency=0x12da2f2761038486271c99da7e0fb4413e2b5e38

_Yes 
	TechRate Audit :
	https://github.com/TechRate/Smart-Contract-Audits/blob/main/NFTBlackMarket.pdf
	
	RugScreen Audit:
	https://www.rugscreen.com/scan/certificate?tokenid=e12e7d7e13

Thanks a lot 
Have a Good Day.

**Comment by Cryptocool1** [comment]
can you please add links to your PR?
example: https://developer.trustwallet.com/add_new_asset#info-json-contents

**Comment by NFTBlackMarket** [comment]
Hello 
We added our social media links 
Thanks a lot 
Have a good day.

**Pull request merged**
