### PR TITLE
Add KORBIT COIN (BEP20)

### PR DESCRIPTION
**Pull request by indiadigitalnote**
Adding info for BEP20 token 'KORBIT COIN'.

PR created by <a href="https://assets.trustwallet.com">TW Assets Management</a>

### CODE REVIEW

**Comment by indiadigitalnote** [comment]
how much time it take to upload logo on trust wallet

**Comment by Cryptocool1** [comment]
hello,
can you answer some questions?
• What is the purpose of this token? How will it benefit Trust Wallet users?
 • How is the token being distributed? Are you conducting an airdrop?
 • Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?
 • Is the token listed on a centralized/decentralized exchange?
 • Is a Smart Contract audit completed? Where can we find this information?

**Comment by indiadigitalnote** [comment]
Hello feel good for your reply in quick time


> • What is the purpose of this token? How will it benefit Trust Wallet users?

We are developing multi blockchain wallet so we have a good client base the Client will make more transaction on trust wallet bcoz we are not going to list our coin on more exchanges so use will follow trust wallet

> • How is the token being distributed? Are you conducting an airdrop?

Token is distributed with the promoters of company world wide. We are not conducting air drop.

> • Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?

No

> • Is the token listed on a centralized/decentralized exchange?

Yes now it's only on indoex exchange now live rate range is 0.10 cent

> • Is a Smart Contract audit completed? Where can we find this information?

We had verified the contract on bscscan so I am sharing the link below

https://bscscan.com/token/0x0e7ceb85caaef8dab9d2749bd9a68c0c4a022c62

Thanks you hope u had got answers.

**Comment by Cryptocool1** [comment]
you description should tell about your token. please change

**Comment by indiadigitalnote** [comment]
> you description should tell about your token. please change

Yes change it


Thanks for update

**Comment by indiadigitalnote** [comment]
Is all process Is final from your side when it will come to trust wallet please let me no

**Comment by cryptomanz** [comment]
- Please follow the rules to add token, "A full token audit is completed by reputable security audit groups. Partial audits are subject for review."
Exemple: https://developer.trus
Screenshot 2021-09-11 at 10 39 01
twallet.com/assets/requirements

**Comment by indiadigitalnote** [comment]
> * Please follow the rules to add token, "A full token audit is completed by reputable security audit groups. Partial audits are subject for review."
>   Documentary: https://developer.trustwallet.com/assets/requirements
> 
> Screenshot 2021-09-11 at 10 39 01

Hi have a good day.

Do u need any thing more from my side or its in processing from your end

**Comment by cryptomanz** [comment]
You need to send me a smart contract audit.
Exemple audit:
- CertiK 
Screenshot 2021-09-21 at 11 27 12

**Comment by indiadigitalnote** [comment]
> You need to send me a smart contract audit.
> Exemple audit:
> 
> * CertiK
> 
> Screenshot 2021-09-21 at 11 27 12

Aduit repot link

https://korbitcoin.com/korbit-coin-audit-report.pdf

**Comment by indiadigitalnote** [comment]
Thanks u

**Pull request merged**
