### PR TITLE
Add SparkPoint Fuel logo and info

### PR DESCRIPTION
**Pull request by aldrickb**

### CODE REVIEW

**Comment by ricoz** [comment]
Hi Trust Wallet team! SFUEL is a new project so we can't meet the number of holders and transactions yet. SparkPoint SRK itself is an old project (2+ years) which is also the same team behind SFUEL. We're currently working on our SFUEL-BNB Liquidity Staking before launching on Pancake Swap so we're hoping to meet the required number of holders and transactions soon. For now, we're hoping and praying you'll consider approving the project 🙏

**Comment by catenocrypt** [comment]
As per our policy, brand new tokens are not included, there is a minimum requirement of 2500 holder addresses and 5000 transactions, in order to filter out scam tokens.
See the criteria at (mentioned in the first message by the bot): https://community.trustwallet.com/t/how-to-submit-a-token-logo/3863).
This token has no real usage yet (3). Closing PR for now. Please come back to us when all criteria are met.

https://bscscan.com/token/0x37Ac4D6140e54304D77437A5c11924f61a2D976f

**Comment by ricoz** [comment]
> As per our policy, brand new tokens are not included, there is a minimum requirement of 2500 holder addresses and 5000 transactions, in order to filter out scam tokens.
> See the criteria at (mentioned in the first message by the bot): https://community.trustwallet.com/t/how-to-submit-a-token-logo/3863).
> This token has no real usage yet (3). Closing PR for now. Please come back to us when all criteria are met.
> 
> https://bscscan.com/token/0x37Ac4D6140e54304D77437A5c11924f61a2D976f

Thanks @catenocrypt , will this PR be reopened once we meet the minimum holder addresses and transactions?

**Comment by catenocrypt** [comment]
Yes, we can reopen this PR.

**Comment by ricoz** [comment]
> Yes, we can reopen this PR.

We'd like to request reopening of this PR. We now have [$160k liquidity on Pancake Swap](https://pancakeswap.info/pair/0x078113f736255ad4254838ef8fb804bfdb2cf945), [4,529 holders and 5,053 transactions](https://bscscan.com/token/0x37ac4d6140e54304d77437a5c11924f61a2d976f). We're now working on our SparkDeFi SparkSwap DEX which will launch early next year to compete with Pancake Swap and BurgerSwap on BSC. Thank you!

**Comment by catenocrypt** [comment]
Holder addresses now above 4600, nice.

**Pull request merged**
