### PR TITLE
fix: remove white space

### PR DESCRIPTION
**Pull request by nntam2013**

### CODE REVIEW

**Comment by nntam2013** [comment]
Can I submit this PR to remove whitespace in our OPEN token?

**Comment by smart2022** [comment]
Hi please merge #19244

**Comment by smart2022** [comment]
Hello  dear merge-fee-bot

Pay Attention  please, please  merge #19244  not #19277 .this taken much
time and all you asked we sent

fee paid https://explorer.binance.org/tx/1BB848FB02ADF595B046ED1E53802FBF992F29CFF1F3EC514873082F34F8C70A
<https://github.com/trustwallet/assets/pull/url>

Thank you so much

**Comment by smart2022** [comment]
Hello  dear merge-fee-bot

Pay Attention  please, please  merge #19244  not #19277 .this taken much
time and all you asked we sent

fee paid https://explorer.binance.org/tx/1BB848FB02ADF595B046ED1E53802FBF992F29CFF1F3EC514873082F34F8C70A
<https://github.com/trustwallet/assets/pull/url>

Thank you so much

**Pull request closed without merging**
