### PR TITLE
Add SWGb logo and details on binance smartchain

### PR DESCRIPTION
**Pull request by radiancegeorge**

### CODE REVIEW

**Comment by radiancegeorge** [comment]
hello, Good day
SWG is the same as SWGb, we make use of just liquidity's token bridge, https://swgbridge.justliquidity.org/
i'm making a request to update the price of SWGb with SWG, since they are both the same..
SWG:: https://etherscan.io/token/0x92ef4ffbfe0df030837b65d7fccfe1abd6549579
Thank You

**Comment by Iamdeadlyz** [comment]
Hi @radiancegeorge 

Please check this guide for our requirements regarding the price: https://community.trustwallet.com/t/where-does-trust-wallet-get-coin-pricing-data-from/333

**Comment by radiancegeorge** [comment]
Hello @Iamdeadlyz 
Please we need the price of swgb updated, currently its not showing, since just liquidity's token bridge was used, swg and swgb are the same thing but on different blockchains.
and every requirement has been met.
thank you.
https://swgbridge.justliquidity.org/

**Comment by Iamdeadlyz** [comment]
Hi, please contact CoinMarketCap to fix your details: https://coinmarketcap.com/currencies/swirge/

**Comment by radiancegeorge** [comment]
Hello @Iamdeadlyz 
Our trade volume has surpassed the required amount, 
and please be reminded that SWGB is the same as SWG.
Please update SWGB price on your wallet.
Thank You.

**Comment by Iamdeadlyz** [comment]
Not yet fixed for CoinMarketCap, please contact them
https://coinmarketcap.com/currencies/swirge/

**Pull request merged**
