### PR TITLE
Add Foresight token info and logo

### PR DESCRIPTION
**Pull request by drfinch-foresight**
Foresight FORS token info and logo

### CODE REVIEW

**Comment by catenocrypt** [comment]
This PR needs a few corrections.  I cannot make corrections, as source repo is inaccessible ('unknown repository').

- blockchains/ethereum/assets/0xb1EC548F296270BC96B8A1b3b3C8F3f04b494215/Foresight_info.json:
file should be renamed to `info.json`

- blockchains/ethereum/assets/0xb1EC548F296270BC96B8A1b3b3C8F3f04b494215/Thumbs.db
Should be deleted

blockchains/ethereum/assets/0xb1EC548F296270BC96B8A1b3b3C8F3f04b494215/logo.png 

Please fix the above in this PR (or create a new one).

**Comment by drfinch-foresight** [comment]
Thank you, I have made those changes.15.09.2020, 01:00, "Adam R" <notifications@github.com>:
This PR needs a few corrections.  I cannot make corrections, as source repo is inaccessible ('unknown repository').


blockchains/ethereum/assets/0xb1EC548F296270BC96B8A1b3b3C8F3f04b494215/Foresight_info.json:
file should be renamed to info.json


blockchains/ethereum/assets/0xb1EC548F296270BC96B8A1b3b3C8F3f04b494215/Thumbs.db
Should be deleted


blockchains/ethereum/assets/0xb1EC548F296270BC96B8A1b3b3C8F3f04b494215/logo.png
Please fix the above in this PR (or create a new one).

**Comment by catenocrypt** [comment]
> I have made those changes

Sorry, I see exactly the same...  Cannot merge it like this.

image

**Comment by drfinch-foresight** [comment]
Sorry Adam.I have created another PR: https://github.com/trustwallet/assets/pull/3967Hopefully payment for the previous PR can be used for the new PR?Thanks 15.09.2020, 18:28, "Adam R" <notifications@github.com>: I have made those changesSorry, I see exactly the same... Cannot merge it like this.—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by catenocrypt** [comment]
Continued in #3967 , closing this

**Pull request closed without merging**
