### PR TITLE
Updated PhoenixDAO Logo

### PR DESCRIPTION
**Pull request by codemathics**
Changed and added the new PhoenixDAO Logo.

### CODE REVIEW

**Comment by codemathics** [comment]
Payment has been initiated. Thanks!

**Comment by codemathics** [comment]
Hi @zachzwei @catenocrypt @Iamdeadlyz 

Please just a kind notice on this. Appreciate!

**Comment by codemathics** [comment]
Hi @zachzwei @catenocrypt @Iamdeadlyz 

Please could you help me kindly merge this PR, will really do appreciate it? Thanks! 🙏

**Comment by catenocrypt** [comment]
Accepting lower circulation, update to existing token.

**Pull request merged**
