### PR TITLE
Add DogCoin (BEP20)

### PR DESCRIPTION
**Pull request by shibamaskcoin**
Adding info for BEP20 token 'DogCoin'.

PR created by <a href="https://assets.trustwallet.com">TW Assets Management</a>

### CODE REVIEW

**Comment by dognetwork** [comment]
Hi @Cryptocool1 

We have re branded and migrated to new contract please check conversation in #24017
Kindly remove logo from old contract
0x9105f25a9d6b3d289cc7315b0b4e0b91f3806fb1 and approve this contract.

Check migration proof - https://coinmarketcap.com/currencies/shibamask/

**Comment by Cryptocool1** [comment]
As per our policy, there is a minimum requirement of 10,000 holder addresses and 15,000 transactions, in order to filter out scam tokens.
See the criteria at : https://developer.trustwallet.com/listing-new-assets/requirements .

**Comment by dognetwork** [comment]
> As per our policy, there is a minimum requirement of 10,000 holder addresses and 15,000 transactions, in order to filter out scam tokens. See the criteria at : https://developer.trustwallet.com/listing-new-assets/requirements .

Our project is already approved in Trust wallet and we are operating from last 1 year, we are here asking you to migrate us from one contract to another, there is no rule set for contract migration.
Kindly help us with this

**Comment by dognetwork** [comment]
> As per our policy, there is a minimum requirement of 10,000 holder addresses and 15,000 transactions, in order to filter out scam tokens. See the criteria at : https://developer.trustwallet.com/listing-new-assets/requirements .

Our project is already approved in Trust wallet and we are only requesting you to migrate contract.
there is no rule set for migration

**Pull request closed without merging**
