### PR TITLE
Derace token on BSC and ETH

### PR DESCRIPTION
**Pull request by ksendra**
This token is bridged, so holders on BSC and ETH should be summed up.

### CODE REVIEW

**Comment by Cryptocool1** [comment]
hello,
• What is the purpose of this token? How will it benefit Trust Wallet users?
 • How is the token being distributed? Are you conducting an airdrop?
 • Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?
 • Is the token listed on a centralized/decentralized exchange?
 • Is a Smart Contract audit completed? Where can we find this information?

**Comment by ksendra** [comment]
Hi, 

this token is used as a value in our horse racing platform to purchase NFTs, enter races and breed horses. Tokens were sold on IDO at DAO Maker platform was over subbed 40x. In total, we had cap for IDO of 7m tokens for 360 users.

Our token is bridged with Anyswap from ETH to BSC chain. In total, we have ~17k holders

Our token was listed on August 3rd. We are listed on Uniswap, Pancakeswap, Gate.io, Crypto.com. Gonna get listed at tier one in 2 weeks.  Currently, it's trading at ~70x initial price. ATH was 88x. Liquidity on Uni 6.5m. Daily volume 15-20m 
Under the audit section you can see audit done by "Hacken"
https://coinmarketcap.com/currencies/derace/

Thanks!

**Comment by Cryptocool1** [comment]
could you add the links to your PR?

**Comment by ksendra** [comment]
> could you add the links to your PR?

Done, thanks!

**Comment by ksendra** [comment]
> hello, According to our guidelines token image needs to be full screen, here is link to guidelines details and an example of token images: https://community.trustwallet.com/t/how-to-submit-a-token-logo/3863

Updated, thanks for the tip!

**Pull request merged**
