### PR TITLE
Add files via upload

### PR DESCRIPTION
**Pull request by RedfoxFinance**
This is the official request for adding RedFox Finance to TrustWallet
0xefdfe2ce33000b5b6b5c64c6a4d54ac789677ed8
https://redfox.finance

### CODE REVIEW

**Comment by RedfoxFinance** [comment]
logo

**Comment by Cryptocool1** [comment]
Info.json is incorrect. It should be of the form:
{
    "name": "Trust Wallet Token",
    "type": "ERC20",
    "symbol": "TWT",
    "decimals": 8,
    "description": "Utility token to increase adoption of cryptocurrency.",
    "website": "https://trustwallet.com",
    "explorer": "https://explorer.binance.org/asset/TWT-8C2",
    "status": "active",
    "id": "TWT-8C2"
}
Please follow documentation: https://community.trustwallet.com/t/how-to-submit-a-token-logo/3863

**Comment by Cryptocool1** [comment]
Corrections needed
-BEP20, not BEP-20
-This is a BEp20 token, correct folder is blockchains/smartchain/assets. Please correct.

**Comment by RedfoxFinance** [comment]
Corrections needed
-BEP20, not BEP-20
-This is a BEp20 token, correct folder is blockchains/smartchain/assets. Please correct.

Correction Done

**Comment by RedfoxFinance** [comment]
logo

**Comment by Cryptocool1** [comment]
blockchains/smartchain/assets/0xefdfe2ce33000b5b6b5c64c6a4d54ac789677ed8/info.json  , not blockchains/binance/assets/info.json 
the same for logo.png

**Comment by Cryptocool1** [comment]
Please come back to us when all criteria are met.

**Pull request closed without merging**
