### PR TITLE
O.N.E. 218 Token Logo

### PR DESCRIPTION
**Pull request by mrehasan**
Logo

### CODE REVIEW

**Comment by Athayde3586** [comment]
Yes check the name of email too

**Comment by Athayde3586** [comment]
You know who this is

**Comment by Athayde3586** [comment]
How much have u took

**Comment by Athayde3586** [comment]
Yes too many hakers and y'all r letting them get away with it

**Comment by cryptomanz** [comment]
Please create new PR, follow doc https://developer.trustwallet.com/assets/requirements
You may want to try our Assets app in beta; go to https://assets.trustwallet.com, log on with Github, enter contract ID, logo and some additional info, and it will create a PR for you.
See https://developer.trustwallet.com/assets/repository_details

**Pull request closed without merging**
