### PR TITLE
Add MAST

### PR DESCRIPTION
**Pull request by MagicDeveloperDocs**

### CODE REVIEW

**Comment by Cryptocool1** [comment]
• What is the purpose of this token? How will it benefit Trust Wallet users?
 • How is the token being distributed? Are you conducting an airdrop?
 • Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?
 • Is the token listed on a centralized/decentralized exchange?
 • Is a Smart Contract audit completed? Where can we find this information?

**Comment by Cryptocool1** [comment]
is your token listed on CoinMarketCap?

**Comment by MagicDeveloperDocs** [comment]
> is your token listed on CoinMarketCap?

CMC is under review

**Comment by Cryptocool1** [comment]
• What is the purpose of this token? How will it benefit Trust Wallet users?
• How is the token being distributed? Are you conducting an airdrop?
• Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?
• Is the token listed on a centralized/decentralized exchange?
• Is a Smart Contract audit completed? Where can we find this information?

**Comment by MagicDeveloperDocs** [comment]
Hello!
Can you answer some questions?
Yes

What is the purpose of this token? How will it benefit Trust Wallet users?

MagicStaves will enable our community to achieve maximum decentralization.
We have a very worldwide range of user base, and we’ll help Trust to gain more users.
How is the token being distributed? Are you conducting an airdrop?

 The total supply of MagicStaves token MAST is 70,000 tokens, without any team reserve, the mining period is 3 years, and the initial circulation is 0

We are planning to conduct the airdrop.
Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?
No any ICO or presale.

Is the token listed on a centralized/decentralized exchange?
It’s listed on PancakeSwap

Is a Smart Contract audit completed? Where can we find this information?

In the auditing process now.
You can find it on the website and Github when it’s done.

**Comment by Cryptocool1** [comment]
awaiting for smart contract audit, on hold for now

**Comment by cryptomanz** [comment]
Please come back to us when all criteria are met.
When creating a new PR make sure to mention this PR, so that we can see that fee has been paid already here.

**Comment by MagicDeveloperDocs** [comment]
[audit](https://github.com/MagicDeveloperDocs/audit/blob/main/Magic%20Cube%20Smart%20Contract%20Initial%20Audit%20Report.docx.pdf)

**Comment by MagicDeveloperDocs** [comment]
@Cryptocool1

**Comment by MagicDeveloperDocs** [comment]
@[cryptomanz](https://github.com/cryptomanz)

**Pull request merged**
