### PR TITLE
Add S315 (BEP20)

### PR DESCRIPTION
**Pull request by s315protocol**
Adding info for BEP20 token 'S315'.

https://github.com/trustwallet/assets/pull/28398

PR created by <a href="https://assets.trustwallet.com">TW Assets Management</a>

### CODE REVIEW

**Comment by s315protocol** [comment]
https://github.com/trustwallet/assets/pull/28398

**Comment by s315protocol** [comment]
• What is the purpose of this token? How will it benefit Trust Wallet users?
S315 is a new attempt at two-way mobility, with a certain community user base and influence, which can bring new benefits to Trust users.

• How is the token being distributed? Are you conducting an airdrop?
The token is fully unlocked and in community hands. All tokens were
available on the market at launch, no allocations or vesting.

• Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?
No, fair launch on PancakeSwap and ContractSwap.

• Is the token listed on a centralized/decentralized exchange?
The token is on multiple CEXes PancakeSwap and ContractSwap

• Is a Smart Contract audit completed? Where can we find this information?
Yes, you can view it on our Certik page here:
https://skynet.certik.com/projects/s315-protocol

**Comment by s315protocol** [comment]
> Hi! In order to compensate for the efforts of processing PRs, we kindly ask for a contribution. 💀 As **there is no refund**, before **paying the fee**, make sure **new tokens fulfill the minimum circulation and other [acceptance criteria](https://developer.trustwallet.com/listing-new-assets/requirements)**. See also the [PR Fee FAQ](https://developer.trustwallet.com/listing-new-assets/faq).
> 
> Please pay **500 TWT** to the BEP20 (Binance Smartchain) address `0x2c51356d7D5aFEC408d2191b0993074A3A3524Dd`. Alternatively, 2.5 BNB is also accepted (same address).
> 
> **QR** code: [Trust](https://api.qrserver.com/v1/create-qr-code/?size=200x200&data=https%3A%2F%2Flink.trustwallet.com%2Fsend%3Fasset%3Dc20000714_t0x4B0F1812e5Df2A09796481Ff14017e6005508003%26address%3D0x2c51356d7D5aFEC408d2191b0993074A3A3524Dd%26amount%3D500) | [other wallet](https://api.qrserver.com/v1/create-qr-code/?size=200x200&data=0x2c51356d7D5aFEC408d2191b0993074A3A3524Dd%3Famount%3D500)
> 
> _TWT Acquiring_:
> 
> * [Trust Wallet Tokens (TWT)](https://community.trustwallet.com/t/trust-wallet-token-twt/4187) can be obtained from [DEXs/exchanges](https://community.trustwallet.com/t/where-to-get-trust-wallet-tokens/76641).
> * TWT-BEP2 is supported (Binance Chain), BEP20 version on Smart Chain is not.
> * TWT-BEP20 can be traded with TWT-BEP2 using the Trust Wallet [Swap Option](https://community.trustwallet.com/t/how-to-trade-with-the-built-in-dex-swap-option/169).
> 
> _Notes_:
> 
> * New tokens without significant usage are rejected, see criteria mentioned above.
> * One PR should be for a single project; PR's with more than 10 logos will be rejected.
> * Payment evaluation happens automatically, but with a few minutes delay.  When payment is detected, an Accept Review is automatically placed on the PR, which is a condition for merge.
> * Evaluating the PR is done manually, and it is merged only if all conditions are satisfied.
>   There will be a fee to process this request. None of it goes to the developers.
>   Before paying the fee, make sure new tokens fulfill the minimum circulation and other acceptance criteria.
>   If you are paying TWT for the submission, this will be burned automatically. There will be no refunds.

https://github.com/trustwallet/assets/pull/28398

**Comment by s315protocol** [comment]
> @s315protocol, kind reminder: please pay fee: **500 TWT** to the address `0x2c51356d7D5aFEC408d2191b0993074A3A3524Dd`. Alternatively, 2.5 BNB is also accepted (same address).
> 
> **QR** code: [Trust](https://api.qrserver.com/v1/create-qr-code/?size=200x200&data=https%3A%2F%2Flink.trustwallet.com%2Fsend%3Fasset%3Dc20000714_t0x4B0F1812e5Df2A09796481Ff14017e6005508003%26address%3D0x2c51356d7D5aFEC408d2191b0993074A3A3524Dd%26amount%3D500) | [other wallet](https://api.qrserver.com/v1/create-qr-code/?size=200x200&data=0x2c51356d7D5aFEC408d2191b0993074A3A3524Dd%3Famount%3D500) See the [Pull Request Fee FAQ](https://developer.trustwallet.com/assets/faq).

https://github.com/trustwallet/assets/pull/28398

Paid in this PR

**Comment by Cryptocool1** [comment]
Hello, are you listed on CoinMarketCap?

**Comment by s315protocol** [comment]
> Hello, are you listed on CoinMarketCap?

Yes， It has already been listed on CoinMarketCap

https://coinmarketcap.com/currencies/swap315/

**Pull request merged**
