### PR TITLE
Please update  logo for Xenon Pay (X2P) Bep20

### PR DESCRIPTION
**Pull request by keesx2pofficial**
please add logo to BEP-20 token called X2P. Thanks in advance! the contract is 0x53dcd4ef8e21fe014594a0854c4271a0623b31ec

### CODE REVIEW

**Comment by Cryptocool1** [comment]
Social field is not needed, remove it please

**Comment by keesx2pofficial** [comment]
> Social field is not needed, remove it please


[0x53dcD4eF8E21FE014594a0854c4271a0623B31eC.zip](https://github.com/trustwallet/assets/files/6481517/0x53dcD4eF8E21FE014594a0854c4271a0623B31eC.zip)

This is the new updated version i can not send a json file on its own

**Comment by keesx2pofficial** [comment]
[0x53dcD4eF8E21FE014594a0854c4271a0623B31eC.zip](https://github.com/trustwallet/assets/files/6481547/0x53dcD4eF8E21FE014594a0854c4271a0623B31eC.zip)

**Comment by keesx2pofficial** [comment]
Hello ❤️

**Comment by BorsaMetin** [comment]
Good Project!

**Comment by BorsaMetin** [comment]
@BorsaMetin is here!

**Pull request merged**
