### PR TITLE
Add validator lunc-validator

### PR DESCRIPTION
**Pull request by SmarDeFiProjects**

### CODE REVIEW

**Comment by cryptomanz1** [comment]
You need create new PR and adding only your file and logo.

**Comment by cryptomanz1** [comment]
you've created info.json that delete all validators. Please add new commit with adding only your validator

**Comment by SmarDeFiProjects** [comment]
> info.json

what info.json you are refering to ? I check previews request and only list.json and the logo image is requested.

**Comment by cryptomanz1** [comment]
Screenshot 2023-01-13 at 10 16 08
you are deleting all these files. 
I'll create and mention here new Pull Request for you.

**Comment by cryptomanz1** [comment]
#23734

**Pull request closed without merging**
