### PR TITLE
Add MXC layer 3 chain

### PR DESCRIPTION
**Pull request by sheenhx**
Hey we want to add our Layer3, chain id 18686

Please check the RPC and other confs here : https://chainlist.org/chain/18686

### CODE REVIEW

**Comment by sheenhx** [comment]
Morning, if it is merged users won't need to update their app to use our chain right?

**Comment by sheenhx** [comment]
@Cryptocool1 @Milerius hey, any reply

**Comment by sheenhx** [comment]
@Cryptocool1 hey any reply?

**Comment by Cryptocool1** [comment]
Thanks for your interests, we will consider to add it later

**Pull request closed without merging**
