### PR TITLE
Add PIN (ERC20)

### PR DESCRIPTION
**Pull request by inSureToken**
Adding info for ERC20 token 'PIN'.

PR created by <a href="https://assets.trustwallet.com">TW Assets Management</a>

### CODE REVIEW

**Comment by inSureToken** [comment]
PIN is a wrapped version of the FLO coin. (BSC bridge will be created soon in collaboration with Anyswap)
FLO has been live since 2013.

Please see FLO to PIN upgrade information here on the official website: https://docs.publicindex.network/

Also, CMC and Coingecko have updated the pages:

https://coinmarketcap.com/currencies/flo
https://www.coingecko.com/en/coins/flo

**Comment by Cryptocool1** [comment]
As per our policy, brand new tokens are not included, there is a minimum requirement of 2500 holder addresses and 5000 transactions, in order to filter out scam tokens.
See the criteria at (mentioned in the first message by the bot): https://community.trustwallet.com/t/how-to-submit-a-token-logo/3863).
Closing PR for now. Please come back to us when all criteria are met.

**Comment by inSureToken** [comment]
Hi, it is not a brand new token, it is an ERC20 wrapper of the FLO coin which has been around for 7 full years!
It has been tracked by CMC since November 2013!

Please see FLO to PIN upgrade information here on the official website: 
https://docs.publicindex.network/

Also, CMC and Coingecko have updated the pages already, please check old FLO links:

https://coinmarketcap.com/currencies/flo
https://www.coingecko.com/en/coins/flo

**Comment by metacoin** [comment]
Hi @Cryptocool1 

FLO (PIN) is a cryptocurrency that is over 8 years old. It is one of the 10 oldest cryptocurrencies that still exists today. The PIN ERC20 token is a wrapped version of FLO and is not a brand new token. There are over 12,500 users of FLO (now PIN).

Here are some examples of assets on TrustWallet which are newer than FLO and have fewer holders on ethereum, yet have been merged:

**Zcash:**
Initial release: October 2016
Wrapped Zcash: 54 holders [[etherscan](https://etherscan.io/token/0x4A64515E5E1d1073e83f30cB97BEd20400b66E10)]
Merged into TrustWallet [[github](https://github.com/trustwallet/assets/tree/master/blockchains/ethereum/assets/0x4A64515E5E1d1073e83f30cB97BEd20400b66E10)]

**Filecoin**
Initial release: 15 July 2014
Wrapped Filecoin: 101 holders [[etherscan](https://etherscan.io/token/0x6e1A19F235bE7ED8E3369eF73b196C07257494DE)]
Merged into TrustWallet [[github](https://github.com/trustwallet/assets/tree/master/blockchains/ethereum/assets/0x6e1A19F235bE7ED8E3369eF73b196C07257494DE)]

**FLO**
Initial release: 17 June 2013
Wrapped FLO (PIN): 82 holders [[etherscan](https://etherscan.io/token/0xc1f976b91217e240885536af8b63bc8b5269a9be)]
Blocked from berging into TrustWallet

I am only asking for fair and equal treatment on grounds supported by facts.

For additional details on FLO and PIN please see the development timeline and numerous articles on the history of our cryptocurrency:

https://docs.publicindex.network/about-pin/history/timeline

Deep dive into FLO history on [CoinDesk](https://www.coindesk.com/florincoin-the-2014-altcoin-you-dont-remember-is-attracting-real-users)

**Comment by Cryptocool1** [comment]
> Hi, it is not a brand new token, it is an ERC20 wrapper of the FLO coin which has been around for 8 years!
> It has been tracked by CMC since November 2013!
> 
> Please see FLO to PIN upgrade information here on the official website:
> https://docs.publicindex.network/
> 
> Also, CMC and Coingecko have updated the pages already, please check old FLO links:
> 
> https://coinmarketcap.com/currencies/flo
> https://www.coingecko.com/en/coins/flo

checked, thanks

**Comment by inSureToken** [comment]
FLO (PIN) is a cryptocurrency that is over 8 years old. It is one of the 10 oldest cryptocurrencies that still exists today. The PIN ERC20 token is a wrapped version of FLO and is not a brand new token. There are over 12,500 users of FLO (now PIN).

Here are some examples of assets on TrustWallet which are newer than FLO and have fewer holders on ethereum, yet have been merged:

Zcash:
Initial release: October 2016
Wrapped Zcash: 54 holders [etherscan]
Merged into TrustWallet [github]

Filecoin
Initial release: 15 July 2014
Wrapped Filecoin: 101 holders [etherscan]
Merged into TrustWallet [github]

FLO
Initial release: 17 June 2013
Wrapped FLO (PIN): 82 holders [etherscan]
Blocked from being into TrustWallet

I am only asking for fair and equal treatment on grounds supported by facts.

For additional details on FLO and PIN please see the development timeline and numerous articles on the history of our cryptocurrency:

https://docs.publicindex.network/about-pin/history/timeline

Thank you in advance for your support of the FLO/PIN community project!

**Pull request merged**
