### PR TITLE
Add Black Phoenix (TRC20)

### PR DESCRIPTION
**Pull request by BLACKPHOENIXBPX**
Adding info for TRC20 token 'Black Phoenix'.

PR created by <a href="https://assets.trustwallet.com">TW Assets Management</a>

### CODE REVIEW

**Comment by BLACKPHOENIXBPX** [comment]
@cryptomanz @Cryptocool1 please check the TRC20 token its mentioned by bot as trc10 by mistake 
and this is the audit report : https://github.com/TechRate/Smart-Contract-Audits/blob/main/December/BLACK%20PHOENIX%20Full%20Smart%20Contract%20Security%20Audit.pdf

**Comment by cryptomanz** [comment]
Submission looks good. awaiting fee payment.

**Comment by BLACKPHOENIXBPX** [comment]
@cryptomanz what is the problem sir?

**Comment by leedaniil** [comment]
> @cryptomanz what is the problem sir?

That's a bug in asset validation on our side. It's already fixed.

**Pull request merged**
