### PR TITLE
Add ICLICK INU (BEP20)

### PR DESCRIPTION
**Pull request by iclickinu**
Adding info for BEP20 token 'ICLICK INU'.

PR created by <a href="https://assets.trustwallet.com">TW Assets Management</a>

### CODE REVIEW

**Comment by Cryptocool1** [comment]
• What is the purpose of this token? How will it benefit Trust Wallet users?
 • How is the token being distributed? Are you conducting an airdrop?
 • Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?
 • Is the token listed on a centralized/decentralized exchange?
 • Is a Smart Contract audit completed? Where can we find this information?

**Comment by iclickinu** [comment]
1-> What is the purpose of this token? [a utility token integrated with ad
serving website] PPC
2-> How will it benefit Trust Wallet users? [Ease in accessibility, it will
improve TrustWallet userbase] as it targets to foster cryptocurrency
adoption.
3-> How is the token being distributed? [Fair Launch and airdrop] no
private sales conducted, we as aimed to have a token fully owned by the
community
4-> Did you sold the tokens at an Initial Coin Offering (ICO) or a token
presale? NO
5-> Is the token listed on a centralized/decentralized exchange? Yes [on
PancakeSwap] and already listed on CoinMarketCap
6-> Is a Smart Contract audit completed? Yes
Below like is the audit report

https://iclickinu.com/audit

Thanks

**Comment by Cryptocool1** [comment]
We do not accept this kind of audit.

**Comment by Cryptocool1** [comment]
We require smart contract audit from reputable companies, such as: Hacken, Certik, Techrate, Dessert Finance

**Comment by iclickinu** [comment]
Ok I will get that a revert back to you, but that will take some days  like
3 to 4 days

**Comment by iclickinu** [comment]
Hi,
Thanks for your patience, we have uploaded the audit report from one of the
auditor recommended techrate.
Thanks & Regards

**Comment by iclickinu** [comment]
Hi
In my previous message I uploaded the audit report from techrate as
recommended by you, I again upload it.

Thanks

**Comment by Cryptocool1** [comment]
Can you please send your smart contract audit here?

**Comment by iclickinu** [comment]
Here it is

**Comment by Cryptocool1** [comment]
Sorry, but here is no file in your message.

**Comment by iclickinu** [comment]
I think the issue is that GitHub doesn't accept file upload from mail, I
have uploaded it to our server.

https://iclickinu.com/auditreport_iclickinu.pdf

Please check it that is useful.
Thanks

**Comment by iclickinu** [comment]
Here is it again

https://iclickinu.com/auditreport_iclickinu.pdf

Thank you.

**Comment by iclickinu** [comment]
/ 
[ICLICK INU (2).pdf](https://github.com/trustwallet/assets/files/11983576/ICLICK.INU.2.pdf)

**Comment by iclickinu** [comment]
> Sorry, but there is no file in your message.

Hi,
Is it ok now or still not getting the report?

**Comment by iclickinu** [comment]
Hi,
Good day to you, just wanting to know if you still getting challenges to
receive the report

**Comment by iclickinu** [comment]
Hi,
Good day, please it will be nice if I have a response from you if the
report has been received because since your last message I did not hear
anything again.
Thanks waiting for your response.

**Comment by iclickinu** [comment]
Hi,
I want to make an enquiry how o add our ERC20 version to trust wallet

https://bscscan.com/token/0xc8C06a58E4ad7c01b9bb5Af6C76a7a1CfEBd0319

https://twitter.com/iclickinu/status/1702335689403269465?t=C8XBqcLm24XSB5bHo-Nxjw&s=19

https://coinmarketcap.com/currencies/iclick-inu/

**Pull request merged**
