### PR TITLE
Add Multi-Chain Capital (MCC) (ERC20)

### PR DESCRIPTION
**Pull request by mchaindev**
Adding info for ERC20 token 'Multi-Chain Capital (MCC)'.

PR created by <a href="https://assets.trustwallet.com">TW Assets Management</a>

### CODE REVIEW

**Comment by Cryptocool1** [comment]
• What is the purpose of this token? How will it benefit Trust Wallet users?
 • How is the token being distributed? Are you conducting an airdrop?
 • Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?
 • Is the token listed on a centralized/decentralized exchange?
 • Is a Smart Contract audit completed? Where can we find this information?

**Comment by mchaindev** [comment]
Each $MCC Token represents a share in the profits of Multi-Chain Capital.
As profits accumulate in the Multi-Chain Capital Treasury, they are bridged to chains with lower gas costs and invested in yield farms and auto-compounding vaults. Profits are then used to Buy Back and Burn $MCC.

Token is Listed on Uniswap v2:
https://v2.info.uniswap.org/token/0xc146b7cdbaff065090077151d391f4c96aa09e0c

The Token Contract was audited by Solidity Finance and CertiK:
https://solidity.finance/audits/MCC/
https://www.certik.com/projects/multichaincapital

More Information can be found here:
https://multichaincapital.medium.com/

**Comment by mchaindev** [comment]
Can we change the website to:
https://mchain.capital

The old website was used in this info.json and is currently not operational.

**Comment by Cryptocool1** [comment]
fixed

**Comment by mchaindev** [comment]
Thank you @Cryptocool1

**Pull request merged**
