### PR TITLE
Add BEAR (BEP20)

### PR DESCRIPTION
**Pull request by HoneyFarmFi**
Adding info for BEP20 token 'BEAR'.

PR created by <a href="https://assets.trustwallet.com">TW Assets Management</a>

### CODE REVIEW

**Comment by HoneyFarmFi** [comment]
BEAR is HoneyFarm's Layer 2 farming (native) token.

Like as HONEY, a native token of a DeFi project, especially when it's an yield farming project like HoneyFarm, most of the holders stake the tokens to the matsterchef contract, in this case, https://bscscan.com/address/0xc3D910c9D2bB024931a44Cf127B6231aC1F04de3, our layer 2 masterchef.

please refer that it has already 338188 times of transfer and has $24M trading volume on PancakeSwap already.
You can check it on https://pancakeswap.info/token/0xc3eae9b061aa0e1b9bd3436080dc57d2d63fedc1

It's already on CoinGecko, https://www.coingecko.com/en/coins/honeybear.

Thanks,

**Comment by cryptomanz** [comment]
As per our policy, brand new tokens are not included, there is a minimum requirement of 5000 holder addresses and 10000 transactions, in order to filter out scam tokens.
See the criteria at (mentioned in the first message by the bot): https://community.trustwallet.com/t/how-to-submit-a-token-logo/3863).

**Comment by HoneyFarmFi** [comment]
> As per our policy, brand new tokens are not included, there is a minimum requirement of 5000 holder addresses and 10000 transactions, in order to filter out scam tokens.
> See the criteria at (mentioned in the first message by the bot): https://community.trustwallet.com/t/how-to-submit-a-token-logo/3863).

yes but it's actually not relevant to a native token of an Yield farming defi project.
Most of the holders are staking on our masterchef.
The number of transfer is more than 342K already. It proves there's already lots of holders hidden in the contract.

Please apply this condition on this request!

Thanks!

**Comment by HoneyFarmFi** [comment]
@cryptomanz @catenocrypt @zachzwei @Cryptocool1 
Hello guys, I'm actually the same CEO of SatisFinance (SAT) and LazyMint (LAZY) of which the tokens you have registered in the regard of the nature of Yield Farming DeFi token.
and BEAR is already on the CGK and having more than 370K transfer with more than $26M trading volume in 7 days.
We have lots of users who use TrustWallet and they want the BEAR to be registered on TrustWallet!

Please apply this circumstance and register BEAR on TrustWallet!
Thanks!

**Comment by HoneyFarmFi** [comment]
@cryptomanz @catenocrypt @zachzwei @Cryptocool1
pcs_bear

BEAR is TOP 28th token in PancakeSwap!
Now the number of transfer reached 384K

Please understand the nature of Yield Farming project's native token and register BEAR like as you've done for HONEY!

Thanks a lot!!

**Comment by HoneyFarmFi** [comment]
image
Hello @cryptomanz @catenocrypt @zachzwei @Cryptocool1 ,

BEAR token transfer exceed 410K!
Please register it to TrustWallet!

Thanks,

**Comment by Cryptocool1** [comment]
The submission will be on hold until the requirements have been met.

**Comment by HoneyFarmFi** [comment]
> The submission will be on hold until the requirements have been met.

Hi @Cryptocool1 ,
We've already done this for many other DeFi tokens, such as SAT, LAZY and HONEY.
As I explained, the only requirement that BEAR doesn't meet is the number of holders, which is not correctly reflected on the BSC Scan due to the nature of an yield farming project.

As you can see below, the top holders are contracts such as,
BearMaster 0xc3D910c9D2bB024931a44Cf127B6231aC1F04de3
BEAR-BNB LP 0xC5E96F03414DA6E7eA6D2F051D23964C0B80739F
BEAR-BUSD LP 0x9dd10b5d23a05bbac9e9ae0c7ca9890791eabb25
BEAR-BNB Strategy 0x2fB75aA5D8151a3e857A9B2F523c838919459E49
BEAR-BUSD Strategy 0x1773a65AB2d85809f7E4274916d7150b3b568a55

Please understand this nature and register BEAR to Trustwallet!
Thanks!

image

**Comment by HoneyFarmFi** [comment]
thanks so much!!

**Pull request merged**
