### PR TITLE
Add Bitrise Token (BEP20)

### PR DESCRIPTION
**Pull request by bitrisetoken**
Adding info for BEP20 token 'Bitrise Token'.

PR created by <a href="https://assets.trustwallet.com">TW Assets Management</a>

### CODE REVIEW

**Comment by cryptomanz** [comment]
Hello,
Can your answer some questions?
 • What is the purpose of this token? How will it benefit Trust Wallet users?
 • How is the token being distributed? Are you conducting an airdrop?
 • Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?
 • Is the token listed on a centralized/decentralized exchange?
 • Is a Smart Contract audit completed? Where can we find this information?

**Comment by bitrisetoken** [comment]
> Hello,
> Can your answer some questions?
> • What is the purpose of this token? How will it benefit Trust Wallet users?
> • How is the token being distributed? Are you conducting an airdrop?
> • Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?
> • Is the token listed on a centralized/decentralized exchange?
> • Is a Smart Contract audit completed? Where can we find this information?

Token has use case on our dapp and it also benefit holders through BNB rewards
It was a fairlaunch on pancakeswap and it's on decentralised exchange (pancakeswap)

**Comment by Cryptocool1** [comment]
Is a Smart Contract audit completed? Where can we find this information?

**Comment by bitrisetoken** [comment]
> Is a Smart Contract audit completed? Where can we find this information?

We haven't done a audit yet because, we are going to do it after 10000 Holders

**Comment by cryptomanz** [comment]
Awaiting for smart contract audit.

**Comment by bitrisetoken** [comment]
What is wrong with you guys? Last time i lost 5 BNB and now you're 
asking for contract audit which makes no sense while bscscan has already 
verified our contract, You had not mention about the contract audit in 
criteria what's this new thing now???

**Comment by Cryptocool1** [comment]
> What is wrong with you guys? Last time i lost 5 BNB and now you're asking for contract audit which makes no sense while bscscan has already verified our contract, You had not mention about the contract audit in criteria what's this new thing now???
> […](#)

Can you send me the PR where you have already paid the fee

**Comment by bitrisetoken** [comment]
> > What is wrong with you guys? Last time i lost 5 BNB and now you're asking for contract audit which makes no sense while bscscan has already verified our contract, You had not mention about the contract audit in criteria what's this new thing now???
> > […](#)
> 
> Can you send me the PR where you have already paid the fee

https://github.com/trustwallet/assets/pull/11556

**Comment by bitrisetoken** [comment]
> > > What is wrong with you guys? Last time i lost 5 BNB and now you're asking for contract audit which makes no sense while bscscan has already verified our contract, You had not mention about the contract audit in criteria what's this new thing now???
> > > […](#)
> > 
> > 
> > Can you send me the PR where you have already paid the fee
> 
> #11556

So is the logo visible now on Trustwallet?

**Comment by bitrisetoken** [comment]
> > What is wrong with you guys? Last time i lost 5 BNB and now you're asking for contract audit which makes no sense while bscscan has already verified our contract, You had not mention about the contract audit in criteria what's this new thing now???
> > […](#)
> 
> Can you send me the PR where you have already paid the fee

Is the Logo visible on trustwallet now??

**Comment by bitrisetoken** [comment]
> Awaiting for smart contract audit.

So now you ate another 5 BNB????? is this a scam or what??? While the BSCSCAN.com has already verified our contract and you're asking us to pay hefty amount for fake pdf audit report which doesn't prove anything?

**Comment by Cryptocool1** [comment]
> > Awaiting for smart contract audit.
> 
> So now you ate another 5 BNB????? is this a scam or what??? While the BSCSCAN.com has already verified our contract and you're asking us to pay hefty amount for fake pdf audit report which doesn't prove anything?

? 
my our token been merged

**Comment by bitrisetoken** [comment]
> > > Awaiting for smart contract audit.
> > 
> > 
> > So now you ate another 5 BNB????? is this a scam or what??? While the BSCSCAN.com has already verified our contract and you're asking us to pay hefty amount for fake pdf audit report which doesn't prove anything?
> 
> ? Your token been merged

No, its the same token which we applied when we had only 600 holders, now we have 5100 holders and we paid again 5 BNB today and now you guys are asking for audit which is baseless. Please do upload the logo for our token Bitrise .

**Comment by Cryptocool1** [comment]
Your token been merged. 
you will see your logo soon

**Pull request merged**
