### PR TITLE
Add LEC logo and info

### PR DESCRIPTION
**Pull request by loveearth123**

### CODE REVIEW

**Comment by loveearth123** [comment]
Please forgive me. Only after seeing the transaction records do I know that the handling fee of 6 TWTs has been deducted. Do I need to make up for it? PS: PR 2011 I paid 2000 TWT

**Comment by cryptomanz** [comment]
Can your answer some questions?
• What is the purpose of this token? How will it benefit Trust Wallet users?
• How is the token being distributed? Are you conducting an airdrop?
• Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?
• Is the token listed on a centralized/decentralized exchange?
• Is a Smart Contract audit completed? Where can we find this information?

**Comment by loveearth123** [comment]
> 
> 
> Can your answer some questions?
**> • What is the purpose of this token? How will it benefit Trust Wallet users?**

Love Earth Coin is a charity token aiming to introduce the crypto technology in charity practices, building a new charity model in the age of Web 3.0. 
For every single holder of Love Earth coin, the LEC DAO (Decentralized Autonomous Organization) will denote 0.1 LEC for charity. The more the number of holders, the more will be donated.

LEC introduced the blockchain voting system, LEC holders can propose a charity project for vote, and the holders of LEC can vote for their favorite project.
In order to propose in the vote or to vote, holders must prove their holding of LEC. Therefore, when visiting the voting page, holders should link their wallet to show their holding. 
For user of Trust Wallet, by holding LEC in the wallet, they are qualified to take part in the vote.

**> • How is the token being distributed? Are you conducting an airdrop?**

The total supply of Love Earth Coins is 1 billion only. Its issued on ERC20 and no more extra coin will be issued.
1. 50% is deposited in the address of the public charity fund, which is locked by smart contract, and can only be used for donations to large public charity undertakings (large humanitarian disaster relief is the main relief direction, taking up 90%; General public welfare undertakings no more than 10%);

2. 10% locked in the Treasury Reserve (by smart contracts).
- 5% airdrop will be awarded to the top 100 addresses whose holding is no less than 100,000 coins. The airdrop will be made once a month on the 11th, and a total of 30 airdrops will be completed.
- 5% will be airdropped to 100 celebrities, caring charity personage and technical aid donors who have made important contributions to the community. Proposals will be formed and voted on by the community vote every month.

3. The remaining 40% send into Uniswap for liquidity, with the LP token send to the blackhole address. 

The founder team does not own any Love Earth Coin and is 100% decentralized. This is to make sure that the LEC Charity project is totally controlled by the public, but not the founder. 
But there are some LEC communities (found by holders), they would launch some airdrop campaign.

**> • Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?**

No, LEC didn’t launched any kind of presale. 

> • Is the token listed on a centralized/decentralized exchange?

It is now listed on Uniswap V2 and only on the ERC20.

> • Is a Smart Contract audit completed? Where can we find this information?

Yes, it was audited by Certik, for the full audit report, please refer to https://bit.ly/3epGqdu.

**Comment by Cryptocool1** [comment]
can you please add links to your PR?
example: https://developer.trustwallet.com/add_new_asset#info-json-contents

**Comment by loveearth123** [comment]
> can you please add links to your PR?
> example: https://developer.trustwallet.com/add_new_asset#info-json-contents

Do I need to modify the info.json file?Add the link to the audit report in the info.json？

**Comment by cryptomanz** [comment]
your logo background should be transparent 
please change

**Comment by loveearth123** [comment]
> your logo background should be transparent
> please change

sure? https://developer.trustwallet.com/add_new_asset#image-requirements, “Background: Avoid transparency, set background as your brand color or white by default otherwise your token image wont look good on white/dark theme design.”

**Pull request merged**
