### PR TITLE
Adding Coco token logo 

### PR DESCRIPTION
**Pull request by cocopadbsc**
Please update coco token logo

### CODE REVIEW

**Comment by cocopadbsc** [comment]
Hello, why Cocopad logo dont update bro ?

**Comment by Cryptocool1** [comment]
Hello,
-As per our policy, brand new tokens are not included, there is a minimum requirement of 2500 holder addresses and 5000 transactions, in order to filter out scam tokens.
See the criteria at (mentioned in the first message by the bot): https://community.trustwallet.com/t/how-to-submit-a-token-logo/3863).

**Comment by cocopadbsc** [comment]
Now > 2k5 holder bro, pls check again !

**Comment by cocopadbsc** [comment]
Please update Cocopad Logo bro !

**Comment by catenocrypt** [comment]
Correction needed:
This is a BEp20 token, correct folder is `blockchains/smartchain/assets`.  Please correct.

**Comment by cocopadbsc** [comment]
Done, please check it bro

**Comment by Cryptocool1** [comment]
PR should include only 2 files:

blockchains/smartchain/assets/0xFd431CB76965cF80c6FCec011a273B46df23EB04/info.json
blockchains/smartchain/assets/0xFd431CB76965cF80c6FCec011a273B46df23EB04/logo.png

**Comment by cocopadbsc** [comment]
How to remove any PR ?

**Comment by cocopadbsc** [comment]
How to remove any PR bro ?

**Comment by cocopadbsc** [comment]
Done, please check again !

**Pull request merged**
