### PR TITLE
Logo.png and info.json

### PR DESCRIPTION
**Pull request by henrymark1**
logo for BEP20 in Trust Wallet

### CODE REVIEW

**Comment by Cryptocool1** [comment]
• What is the purpose of this token? How will it benefit Trust Wallet users?
 • How is the token being distributed? Are you conducting an airdrop?
 • Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?
 • Is the token listed on a centralized/decentralized exchange?
 • Is a Smart Contract audit completed? Where can we find this information?

**Comment by henrymark1** [comment]
Hello
The benefit of the token will not only benefit trustwallet users rather the entire earth because it has do planting of trees across the globe by assigning 10 trees per holder and also rewarding it's holders with a whooping 6% reflection from all transactions .

No airdrop is been conducted 

It was a presale 

We are listed on both centralized exchange and decentralized exchange which includes pancakeswap  feg exchange and coinsbit 

The smart contract is audited and this information can be seen clearly in the website

**Comment by henrymark1** [comment]
> Hello The benefit of the token will not only benefit trustwallet users rather the entire earth because it has do planting of trees across the globe by assigning 10 trees per holder and also rewarding it's holders with a whooping 6% reflection from all transactions .
> 
> No airdrop is been conducted
> 
> It was a presale
> 
> We are listed on both centralized exchange and decentralized exchange which includes pancakeswap feg exchange and coinsbit
> 
> The smart contract is audited and this information can be seen clearly in the website

**Comment by henrymark1** [comment]
The benefit of the token will not only benefit trustwallet users rather the
entire earth because it has do planting of trees across the globe by
assigning 10 trees per holder and also rewarding it's holders with a
whooping 6% reflection from all transactions .

No airdrop is been conducted

It was a presale

We are listed on both centralized exchange and decentralized exchange which
includes pancakeswap  feg exchange and coinsbit

The smart contract is audited and this information can be seen clearly in
the website

**Comment by Cryptocool1** [comment]
submission looks good, awaiting for fee payment

**Comment by henrymark1** [comment]
bot says:
As there is no refund, before paying the fee, make sure new tokens fulfill the minimum circulation.

it doesn't make much sense

**Comment by Cryptocool1** [comment]
Снимок экрана 2021-11-26 в 10 15 34

**Comment by henrymark1** [comment]
why can't you tell the outcome of this review before you get paid?

**Comment by Cryptocool1** [comment]
As I mentioned, "submission looks good, awaiting for fee payment"

**Comment by henrymark1** [comment]
how long after payment received, logo will appear in TWT?

**Comment by Cryptocool1** [comment]
approximately 24-48 h

**Comment by henrymark1** [comment]
hello. we have sent

**Comment by Cryptocool1** [comment]
could you add the links?
see the example here: https://developer.trustwallet.com/assets/repository_details

**Comment by henrymark1** [comment]
add where?

**Comment by Cryptocool1** [comment]
> add where?

in your info.json

**Pull request merged**
