### PR TITLE
Add Futura Finance logo and info

### PR DESCRIPTION
**Pull request by futurafinance**

### CODE REVIEW

**Comment by Cryptocool1** [comment]
Hello,
Please follow the rules for adding token, your logo should be a full screen, 256x256.
Example:
https://community.trustwallet.com/t/how-to-submit-a-token-logo/3863

**Comment by Cryptocool1** [comment]
do you want me to use logo from your twitter?

**Comment by futurafinance** [comment]
Hi @Cryptocool1, isn't the logo 256 x 256 / png / background transparent? 

https://raw.githubusercontent.com/trustwallet/assets/9a2fe277ca64274cf521da8d62adbf3784ba9e3b/blockchains/smartchain/assets/0x183B2c147fE11788b73BC0D6A7E0186aA5464BfA/logo.png

**Comment by futurafinance** [comment]
@Cryptocool1 you can use our Twitter logo, we just wanted to make it the same as CMC / CG. But in case it needs to be rounded we can go for that.

**Comment by futurafinance** [comment]
Logo updated to have rounded background fullscreen, 256x256

**Pull request merged**
