### PR TITLE
Add Beeuda Logo 

### PR DESCRIPTION
**Pull request by beeuda**
Beeuda token logo and info on Trust wallet

Beeuda is a unique cryptocurrency project, focussing on Building Eco-friendly and Road safe Trucks. This is inspired by the EU's target to cut truck CO2 and boost zero-emission truck sales
With the help of our community and our technology partners, we hope to put clean and road safe truck cabs on the road.

### CODE REVIEW

**Comment by beeuda** [comment]
I used the checksum address in the info.json, am not sure why this is marked  as incorrect

**Comment by cryptomanz** [comment]
Hello,
- please delete these files:
- blockchains/smartchain/assets/0x5b7f0c82d342be42c94d789cfc3aae29863d123e/info.json
- blockchains/smartchain/assets/0x5b7f0c82d342be42c94d789cfc3aae29863d123e/logo.png

**Comment by beeuda** [comment]
@cryptomanz  we have deleted these files

blockchains/smartchain/assets/0x5b7f0c82d342be42c94d789cfc3aae29863d123e/info.json
blockchains/smartchain/assets/0x5b7f0c82d342be42c94d789cfc3aae29863d123e/logo.png

**Comment by Cryptocool1** [comment]
hi there!
could you answer some questions?
• What is the purpose of this token? How will it benefit Trust Wallet users?
 • How is the token being distributed? Are you conducting an airdrop?
 • Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?
 • Is the token listed on a centralized/decentralized exchange?
 • Is a Smart Contract audit completed? Where can we find this information?

**Comment by beeuda** [comment]
**• What is the purpose of this token? How will it benefit Trust Wallet users?**
Beeuda is a unique cryptocurrency project. Our only goal is to build and promote eco-friendly and safe road safe trucks. With help of our community and prospective technical partners, we can achieve this goal.  
Beeuda(BDA) Token will be used for the following:

- Bidding & Purchasing Prototypes of Eco-Friendly Trucks
- Supporting and promoting road safety projects
- As an incentive token to create awareness on the need for eco-friendly and safe trucks
- As an incentive token to support Truck drivers for their hardwork 
- Creating a safe planet for the future generation

Most of our members keep their Beeuda(BDA) token in trustwallet, therefore having our logo show on trustwallet will make the token visible to old members and new members.  It will also make it easier for trust wallet users to exchange their tokens on DEX dapps. 
Beeuda project in general will give Trustwallet a good image for supporting the first crypto eco-friendly truck project

**• How is the token being distributed? Are you conducting an airdrop?**
The token is distributed mainly via members purchase on pancakeswap dex as a way of supporting the projects. Instant BDA token giveaways are also given to members for promoting the project and our various causes.

**• Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?**
We have not organised any presale/ICO for the project. what we did was create liquidity pools on pancaskeswap via donations in addresses available on our website to enable anyone wanting to support the project to get their token on  
• Is the token listed on a centralized/decentralized exchange?
Beeuda token is currently trading on DEX pancakeswap and Beeswap

**• Is a Smart Contract audit completed? Where can we find this information?** NO, we have not done an audit

We are an upcoming project with great future potential given the required support we can together build a great future on a safe planet for many generations

**Comment by Cryptocool1** [comment]
Is a Smart Contract audit completed?

**Comment by beeuda** [comment]
The is the link to our smart contract audit https://www.beeuda.com/wp-content/uploads/2021/07/AuditReportOfBeeuda.pdf
Beeudat token a standard token with basically send and receive function. We are not a Defi project.
Thank you for Listing Beeuda Token and adding our logo

**Comment by cryptomanz** [comment]
fixed id

**Comment by beeuda** [comment]
Pls, do we need to do anything?

**Comment by beeuda** [comment]
The ID is correct, pls see below

{	
	"name": "Beeuda",
    "website": "https://beeuda.com",
    "description": "Beeuda is a unique cryptocurrency project, focussing on Building Eco-friendly and Road safe Trucks. This is inspired by the EU's target to cut truck CO2 and boost zero-emission truck sales.",
    "explorer": "https://bscscan.com/token/0x5B7f0c82D342BE42c94d789cfc3aAE29863D123e",
    "type": "BEP20",
    "symbol": "BDA",
    "decimals": 8,
    "status": "active",
    "id": "0x5B7f0c82D342BE42c94d789cfc3aAE29863D123e"
}

**Comment by Cryptocool1** [comment]
can you please add links to your PR?
example: https://developer.trustwallet.com/add_new_asset#info-json-contents

**Comment by beeuda** [comment]
This is the link https://github.com/beeuda/assets/blob/master/blockchains/smartchain/assets/0x5B7f0c82D342BE42c94d789cfc3aAE29863D123e/info.json

**Comment by beeuda** [comment]
Beeuda is now listed on coinmarketcap.
Please can you update the price to show in trust wallet 
https://coinmarketcap.com/currencies/beeuda/

**Pull request merged**
