### PR TITLE
Adding Ape Token asset and logo

### PR DESCRIPTION
**Pull request by Apetoken1**

### CODE REVIEW

**Comment by Cryptocool1** [comment]
correction needed:
Contract is not in checksum format, should be 0x196dC2421AF765c2673FC6093fb1374b28064270

**Review by Apetoken1 — COMMENTED** [review]
0x196dC2421AF765c2673FC6093fb1374b28064270

**Comment by Apetoken1** [comment]
www.apetoken.net now working

**Review by Apetoken1 — COMMENTED** [review]
Updated contract Id to correct format

**Review by Apetoken1 — COMMENTED** [review]
Updated

**Pull request merged**
