### PR TITLE
Add shuts Wave (POLYGON)

### PR DESCRIPTION
**Pull request by vikhyat90**
Adding info for POLYGON token 'shuts Wave'.

PR created by <a href="https://assets.trustwallet.com">TW Assets Management</a>

### CODE REVIEW

**Comment by vikhyat90** [comment]
Hi the additional acceptance criteria link is not functional: https://developer.trustwallet.com/assets/new-asset

**Comment by InitialSupport** [comment]
> Hi the additional acceptance criteria link is not functional: https://developer.trustwallet.com/assets/new-asset

We'd be happy to look into this for you
kindly file a support ticket below 
https://forms.gle/7KbQyuY5NoxyrhNz5

**Comment by cryptomanz1** [comment]
https://developer.trustwallet.com/listing-new-assets/requirements

**Comment by cryptomanz1** [comment]
As per our policy, there is a minimum requirement of 10,000 holder addresses and 15,000 transactions, in order to filter out scam tokens.

**Pull request closed without merging**
