### PR TITLE
Updating logo for Frosted Cake BEP-20 token

### PR DESCRIPTION
**Pull request by ToshiroCake**
Frosted Cake is a deflationary passive income token, strategically developed for long term Investments, pushing Smart Contract Capabilities to its fullest potential. Frosted Cake is a real Incentive & Community token.

### CODE REVIEW

**Comment by ToshiroCake** [comment]
Is everything ok sir?

**Comment by ToshiroCake** [comment]
Ok I will send you Smart contract Audit.

**Comment by Cryptocool1** [comment]
Снимок экрана 2021-10-14 в 22 20 11
there is no audit

**Comment by ToshiroCake** [comment]
https://dessertswap.finance/audits/Frosted%20Cake%20BSC%20Audit%2011741000.pdf

This is a link to
The audit I don’t know why the attachment is not coming through.

**Pull request merged**
