### PR TITLE
Update existing Logo to rebranded Logo

### PR DESCRIPTION
**Pull request by drewdown1988**
Previous Pull Request was the following 

https://github.com/trustwallet/assets/pull/7460

### CODE REVIEW

**Comment by drewdown1988** [comment]
Hello @Cryptocool1 @catenocrypt @zachzwei ,

We are changing an existing logo and description. Also noticed the sanity check failed but I am unable to update the files. Can you update for me? I believe the mistake was with the logo name

**Comment by cryptomanz** [comment]
- Logo file should be named logo.png exactly, please rename!

**Comment by drewdown1988** [comment]
@cryptomanz upon trying to update this I actually created a new pull request. New new file is attached but also a new pull request was created which I believe we need to delete? Can you please assist me with processing this new logo under this pull? 

I tried deleting the old file but the box it grayed out. 

https://github.com/trustwallet/assets/pull/11869

**Comment by Cryptocool1** [comment]
Please create new PR, follow doc https://community.trustwallet.com/t/how-to-submit-a-token-logo/3863
You may want to try our Assets app in beta; go to https://assets.trustwallet.com, log on with Github, enter contract ID, logo and some additional info, and it will create a PR for you.
See https://community.trustwallet.com/t/how-to-submit-a-token-logo-using-assets-app/82957.

make sure to mention this PR, so fee can be reused

**Comment by drewdown1988** [comment]
> Please create new PR, follow doc https://community.trustwallet.com/t/how-to-submit-a-token-logo/3863
> You may want to try our Assets app in beta; go to https://assets.trustwallet.com, log on with Github, enter contract ID, logo and some additional info, and it will create a PR for you.
> See https://community.trustwallet.com/t/how-to-submit-a-token-logo-using-assets-app/82957.
> 
> make sure to mention this PR, so fee can be reused

Hello I have submitted this via https://github.com/trustwallet/assets/pull/11989. 

Can you please take a look and reuse fees?

**Pull request closed without merging**
