### PR TITLE
ePaisay coin info and logo

### PR DESCRIPTION
**Pull request by mnszaidi**
ePaisay coin info and logo

### CODE REVIEW

**Review by mnszaidi — COMMENTED** [review]
Removed Reddit Link

**Review by mnszaidi — COMMENTED** [review]
added whitepaper

**Review by mnszaidi — COMMENTED** [review]
Removed facebook link

**Review by mnszaidi — COMMENTED** [review]
Added Tags

**Review by mnszaidi — COMMENTED** [review]
Updated Tag

**Review by mnszaidi — COMMENTED** [review]
Updated Tag ePaisay

**Review by mnszaidi — COMMENTED** [review]
Updated Tag ePaisay

**Comment by Cryptocool1** [comment]
As per our policy, brand new tokens are not included, there is a minimum requirement of 10,000 holder addresses and 15,000 transactions, in order to filter out scam tokens.
See the criteria at : https://developer.trustwallet.com/assets/requirements .

**Pull request closed without merging**
