### PR TITLE
Add Toad Network (BEP20)

### PR DESCRIPTION
**Pull request by Spenhouet**
Hi, as a community member of Toad, I would like to request that the Toad icon is added to Trust Wallet.

Audit by SpadeTech: https://spadetech.io/wp-content/uploads/2021/06/toad_network_audit_report.pdf

@ramsty I cleaned up the Git commit history from https://github.com/trustwallet/assets/pull/16988. The checksum address of the folder should now also be correct.

### CODE REVIEW

**Comment by Cryptocool1** [comment]
Submission looks good, awaiting for fee payment

**Comment by Spenhouet** [comment]
@Cryptocool1, @ramsty Not sure who the contacts here are. If we have updates to our listing in the future or e.g. you add a new chain we are on (MOVR/GLMR) or we support further chains, is updating our listing free? Or does it require a fee again?

**Comment by Cryptocool1** [comment]
hello,
yes, you will need to pay fee again

**Comment by Spenhouet** [comment]
Do you also support the MOVR and GLMR chain?

**Comment by Spenhouet** [comment]
@Cryptocool1 @ramsty What does this mean that this was closed? I had an open question and It was not merged yet.

Please reopen.

**Pull request closed without merging**
