### PR TITLE
Add CO2 logo and info

### PR DESCRIPTION
**Pull request by TheCollectiveDevs**

### CODE REVIEW

**Comment by catenocrypt** [comment]
As per our policy, brand new tokens are not included, there is a minimum requirement of 2500 holder addresses and 5000 transactions, in order to filter out scam tokens.
See the criteria at (mentioned in the first message by the bot): https://community.trustwallet.com/t/how-to-submit-a-token-logo/3863).
This token has low usage yet (489 holders). Putting PR on hold for now. Please come back to us when all criteria are met.  Multi-chain and staking tokens may get special treatment, let us know if this is the case. 

https://etherscan.io/token/0x75739d5944534115d7c54ee8c73f186d793bae02

**Comment by TheCollectiveDevs** [comment]
> 
> 
> As per our policy, brand new tokens are not included, there is a minimum requirement of 2500 holder addresses and 5000 transactions, in order to filter out scam tokens.
> See the criteria at (mentioned in the first message by the bot): https://community.trustwallet.com/t/how-to-submit-a-token-logo/3863).
> This token has low usage yet (489 holders). Putting PR on hold for now. Please come back to us when all criteria are met. Multi-chain and staking tokens may get special treatment, let us know if this is the case.
> 
> https://etherscan.io/token/0x75739d5944534115d7c54ee8c73f186d793bae02

Dear @catenocrypt 

We comply with your staking requirements.
Here is the link to the farm:
https://farm.unicrypt.network/farms?token=0x75739d5944534115d7C54ee8C73F186D793BAE02

About the multichain, BSC is coming.

**Comment by catenocrypt** [comment]
Correction needed:  The folder corresponding to the token contract should be in 'checksum' format.  Please rename.

    XXX   'Expect asset at path /home/runner/work/assets/assets/blockchains/ethereum/assets/0x75739d5944534115d7c54ee8c73f186d793bae02 in checksum: '0x75739d5944534115d7C54ee8C73F186D793BAE02''

**Comment by TheCollectiveDevs** [comment]
> 
> 
> Correction needed: The folder corresponding to the token contract should be in 'checksum' format. Please rename.
> 
> ```
> XXX   'Expect asset at path /home/runner/work/assets/assets/blockchains/ethereum/assets/0x75739d5944534115d7c54ee8c73f186d793bae02 in checksum: '0x75739d5944534115d7C54ee8C73F186D793BAE02''
> ```

Dear @catenocrypt 
Everything should be in order now. Sorry for the mess with the commits Windows GitHub has some issues with case sensitive recognition...

**Pull request merged**
