### PR TITLE
Add Tanpin (POLYGON)

### PR DESCRIPTION
**Pull request by gordilovvv**
Adding info for POLYGON token 'Tanpin'.

PR created by <a href="https://assets.trustwallet.com">TW Assets Management</a>

### CODE REVIEW

**Comment by Cryptocool1** [comment]
As per our policy, there is a minimum requirement of 10,000 holder addresses and 15,000 transactions.
See the criteria at : https://developer.trustwallet.com/listing-new-assets/requirements .

**Comment by Cryptocool1** [comment]
Feel free to come back to us once all criteria are met. Make sure to mention this PR so the fee can be reused.

**Comment by gordilovvv** [comment]
Hello! Thank you for your response. I saw that this requirement is subject to review based on the project. I'd like to provide more details about our project to clarify the situation.

- Our token is already listed on CEX: MEXC and BitMart, and people buy only it there. We haven't listed the token on DEX, so all our buyers and traders hold it on centralized exchanges and are not reflected as holders.
- We didn't have any seed, private rounds, or presale. Additionally, we conducted big airdrops, and all current holders are real people.
-  Our biggest game and main strategic partner is Black Russia, a large CIS project with an audience of over 1 million players and a daily online presence of over 70,000 people. The integration is almost complete. Our token serves as a utility token for rewarding players and exchanging items. (Link to Black Russia: https://t.me/br_dev & https://blackrussia.online)
- We are already listed on token lists such as 1inch, Zerion, and CoinGecko.

Link to MEXC: https://www.mexc.com/exchange/TANPIN_USDT
Link to BitMart: https://www.bitmart.com/trade/en-US?symbol=TANPIN_USDT

We hope you will consider this information. If needed, I'll be glad to answer questions and provide more information. Thank you very much!

Best Regards,
Tanpin Team

**Comment by gordilovvv** [comment]
@Cryptocool1 i haven't opened new pull, check please) thank you!

**Pull request closed without merging**
