### PR TITLE
Update logo and info

### PR DESCRIPTION
**Pull request by thundercake09**
Update logo and info

### CODE REVIEW

**Comment by Cryptocool1** [comment]
Hello,
Can your answer some questions?
 • What is the purpose of this token? How will it benefit Trust Wallet users?
 • How is the token being distributed? Are you conducting an airdrop?
 • Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?
 • Is the token listed on a centralized/decentralized exchange?
 • Is a Smart Contract audit completed? Where can we find this information?

**Comment by thundercake09** [comment]
Hello,

Kind find our answer as below:

• What is the purpose of this token? How will it benefit Trust Wallet users?
ThunderCake is world 1st double reward reflection token using the power of
80/20: 80% reflection rewards in now & midterm (CAKE), 20% reflection
rewards in long term (THOREUM)
It will maximize earnings for ThunderCake investors.

• How is the token being distributed? Are you conducting an airdrop?
Total supply 100B distributed as below:
- 10% Dev fund
- 5% Marketing fund
- 1% Airdrop
- 54% Presale
- 30% PancakeSwap
Yes, we're conducting airdrop

• Did you sold the tokens at an Initial Coin Offering (ICO) or a token
presale?
Yes, we did ITO on Thoreum.Finance for presale
- 1 Thoreum = 540 ThunderCake
- 1BNB = 17,442,000 ThunderCake

• Is the token listed on a centralized/decentralized exchange?
Yes, ThunderCake is listed on PancakeSwap
https://pancakeswap.finance/swap#/swap?outputCurrency=0xce4A4A15FcCD532eAd67BE3ECf7e6122c61D06bb

• Is a Smart Contract audit completed? Where can we find this information?
Yes, Smart Contract audited by Techrate with no issue as below link.
https://github.com/TechRate/Smart-Contract-Audits/blob/main/ThunderCake.pdf

Any further question, please let us know.

Thank you & regards,
ThunderCake team

**Comment by thundercake09** [comment]
Hello,


We've added some more detail, please check our answer below:


• What is the purpose of this token? How will it benefit Trust Wallet users?

ThunderCake is world 1st double reward reflection token using the power of
80/20: 80% reflection rewards in now & midterm (CAKE), 20% reflection
rewards in long term (THOREUM)

It will maximize earnings for ThunderCake investors.

Currently we have more than 5000 holders

For Trust Wallet users, they can be more convenient to buy & sell.


• How is the token being distributed? Are you conducting an airdrop?

Total supply 100B distributed as below:

- 10% Dev fund

- 5% Marketing fund

*- 1% Airdrop*

- 54% Presale

- 30% PancakeSwap

Yes, we're conducting airdrop

https://t.me/ThunderCakeBot
<https://web.telegram.org/k/#/im?p=%40ThunderCakeBot>


• Did you sold the tokens at an Initial Coin Offering (ICO) or a token
presale?

Yes, we did ITO on Thoreum.Finance for presale

- 1 Thoreum = 540 ThunderCake

- 1BNB = 17,442,000 ThunderCake

https://thoreum.finance/ito


• Is the token listed on a centralized/decentralized exchange?

Yes, ThunderCake is listed on PancakeSwap

https://pancakeswap.finance/swap#/swap?outputCurrency=0xce4A4A15FcCD532eAd67BE3ECf7e6122c61D06bb


• Is a Smart Contract audit completed? Where can we find this information?

Yes, Smart Contract audited by Techrate with no issue as below link.

https://github.com/TechRate/Smart-Contract-Audits/blob/main/ThunderCake.pdf


Any further question, please let us know.


Thank you & regards,

ThunderCake team

**Comment by Cryptocool1** [comment]
can you please add links to your PR?
example: https://developer.trustwallet.com/add_new_asset/repository_details

**Comment by thundercake09** [comment]
Hi,

Please explain what PR is? we don't know.

Thank you,

**Comment by Cryptocool1** [comment]
> Hi, Please explain what PR is? we don't know. Thank you,
> […](#)

Pull request

**Comment by thundercake09** [comment]
What do you mean by pull request?
Do you need our github source code?
is this one you need: https://github.com/trustwallet/assets/pull/12633

Thank you,

**Comment by thundercake09** [comment]
I have added links to PR

**Pull request merged**
