### PR TITLE
Add SHF logo and info

### PR DESCRIPTION
**Pull request by ShibaForest**
We want Shibaforest's logo to appear on the trust wallet.

### CODE REVIEW

**Comment by ShibaForest** [comment]
I made the payment. When will the logo appear?

**Comment by Cryptocool1** [comment]
As per our policy, brand new tokens are not included, there is a minimum requirement of 10,000 holder addresses and 15,000 transactions, in order to filter out scam tokens.
See the criteria at : https://developer.trustwallet.com/assets/requirements .

**Comment by Cryptocool1** [comment]
Please come back to us when all criteria are met. Make sure to mention this PR so the fee can be reused

**Comment by ShibaForest** [comment]
all we want is a logo :(

**Comment by ShibaForest** [comment]
if we become 10,000 holders do we need to give money again?

**Comment by samuelmonday699** [comment]
No I can ℹ withdraw to my coinbeas wallet

**Pull request closed without merging**
