### PR TITLE
Add Polkalokr (BEP20)

### PR DESCRIPTION
**Pull request by anischohan**
Adding info for BEP20 token 'Polkalokr'.

PR created by <a href="https://assets.trustwallet.com">TW Assets Management</a>

### CODE REVIEW

**Comment by cryptomanz** [comment]
As per our policy, brand new tokens are not included, there is a minimum requirement of 25,000 holder addresses and 50,000 transactions, in order to filter out scam tokens.
See the criteria at : https://developer.trustwallet.com/assets/requirements .

**Comment by anischohan** [comment]
> **16314**

@cryptomanz We aren't a new token, we just launched our BSC token past week and have been on ETH. We have our tokens with trust wallet for ETH. You can see it here https://github.com/anischohan/assets/tree/master/blockchains/ethereum/assets/0x80CE3027a70e0A928d9268994e9B85d03Bd4CDcf

**Comment by anischohan** [comment]
Just reviewing pull requests merged in past 24 hours, brand new tokens with less holders are making it through. What actually needs to be done to resolve this?

**Comment by Cryptocool1** [comment]
cannot find BEP20 contract on your website. can you check it or add?

**Comment by anischohan** [comment]
> cannot find BEP20 contract on your website. can you check it or add?

https://www.coingecko.com/en/coins/polkalokr Its on coingecko? 
https://medium.com/polkalokr/polkalokr-now-trading-on-pancakeswap-eed2d713a0c1 On our medium too.
If this is not enough yes I can add it.

**Comment by cryptomanz** [comment]
Please follow the rules for adding token, your logo should be a full screen, 256x256.
Example:
https://community.trustwallet.com/t/how-to-submit-a-token-logo/3863

**Comment by anischohan** [comment]
@cryptomanz thank you, resized the image.

**Pull request merged**
