### PR TITLE
Add Roost

### PR DESCRIPTION
**Pull request by CryptoBundy**
Add Roost token to Base - please Refer to Pull Request #27844

https://github.com/trustwallet/assets/pull/27844

### CODE REVIEW

**Comment by CryptoBundy** [comment]
@Cryptocool1 @cryptomanz1

**Comment by cryptomanz1** [comment]
Hi,
Your token already added to assets repo
photo_2024-04-18 15 50 22

**Comment by CryptoBundy** [comment]
@cryptomanz1 How do we get price tracking for ROOST in TrustWallet - I thought the price was pulled from CoinMarketCap?  We have included the link of CMC and CG in the JSON file.

**Comment by CryptoBundy** [comment]
@cryptomanz1  I just had a look and it looks like you added it yourselves.  can you please update the asset repository using the json file that i included in this and the previous Pull Request.  it has cmc and other asset information included.

BTW thanks for getting the asset listed last week off your own backs.

**Pull request closed without merging**
