### PR TITLE
Add Zentry (ZENT) (ERC20)

### PR DESCRIPTION
**Pull request by jarindr**
Adding info for ERC20 token 'Zentry (ZENT)'.

PR created by <a href="https://assets.trustwallet.com">TW Assets Management</a>

### CODE REVIEW

**Comment by jarindr** [comment]
Pre listing new token that will be migrated, hence no activities yet

**Comment by cryptomanz1** [comment]
Please send the old address

**Comment by Cryptocool1** [comment]
As per our policy, brand new tokens are not included, there is a minimum requirement of 10,000 holder addresses and 15,000 transactions, in order to filter out scam tokens.
See the criteria at : https://developer.trustwallet.com/assets/requirements .

**Comment by jarindr** [comment]
Hey @Cryptocool1 @cryptomanz1 this is the token that will be migrated from https://etherscan.io/token/0xaaef88cea01475125522e117bfe45cf32044e238
https://www.coingecko.com/en/coins/guildfi

Official announcement isn't up yet, we want to make sure the new token is officially listed to avoid scams.

**Comment by jarindr** [comment]
you also can verify the token deployment and github here https://github.com/zentryHQ

**Pull request closed without merging**
