### PR TITLE
Add SAFERMOON logo and info

### PR DESCRIPTION
**Pull request by faisalx73**
hey trust wallet team,
could you please add our logo,

website: https://safermoon.net/
twitter: https://twitter.com/safermoonreal
telegram: https://t.me/safermoonofficial

### CODE REVIEW

**Comment by faisalx73** [comment]
Hey @catenocrypt , how you doing ,are we go to go should we pay now.

**Comment by Cryptocool1** [comment]
> Hey @catenocrypt , how you doing ,are we go to go should we pay now.

Hello,
 you need to capitalize all letters in your symbol and delete unnecessary files, after that you can pay.

**Comment by faisalx73** [comment]
> > Hey @catenocrypt , how you doing ,are we go to go should we pay now.
> 
> Hello,
> you need to capitalize all letters in your symbol and delete unnecessary files, after that you can pay.

they are capitalized , i only added 1 folder , dont know why the old files appear here

**Comment by catenocrypt** [comment]
Submission looks OK; awaiting fee payment.

**Pull request merged**
