### PR TITLE
Add HXY Logo files

### PR DESCRIPTION
**Pull request by ryanpez1**
Adding the HXY Logo files

### CODE REVIEW

**Comment by catenocrypt** [comment]
There is something wrong with the added info.json, for some reason it is considered a binary file.
Can you check, re-add?

image

**Comment by ryanpez1** [comment]
@catenocrypt I believe I fixed the info.json file, please take a look and let me know if any additional information is needed. Thanks!

**Comment by ryanpez1** [comment]
Also please note the name change from "HEX Money" to "HXY Money".  Will send the 1000 TWT tonight, thanks!!

**Comment by ryanpez1** [comment]
Thanks!

**Pull request merged**
