### PR TITLE
Add Logo PIGGYBANK COINS

### PR DESCRIPTION
**Pull request by kdonnf**

### CODE REVIEW

**Comment by Cryptocool1** [comment]
Correction needed:
Logo file must be named exactly 'logo.png'.

**Comment by kdonnf** [comment]
done paying

**Comment by Cryptocool1** [comment]
Corrections needed:
-Contract is not a valid Ethereum address!
-Description field cannot be empty
- ExplorerUrl incorrect, should be standard https://bscscan.com/token/0xe472f729ac326c1b49921cfd492008c8586e50b9 2, not https://www.bscscan.com/token/0xe472f729ac326c1b49921cfd492008c8586e50b9
 -Id field does not match contract, should be 0xe472f729ac326c1b49921cfd492008c8586e50b9

**Comment by kdonnf** [comment]
Hi @Cryptocool1 , Thank you for your support. I have made the appropriate corrections on our files. Please review, appreciate your approval and time. Thank you.

K Donn Hernandez

**Pull request merged**
