### PR TITLE
Add Brigadeiro.Finance Token logo on Trust Wallet. A Charitable Yield-generating token.

### PR DESCRIPTION
**Pull request by davsonsantos**
Add Brigadeiro.Finance Token logo on Trust Wallet. A Charitable Yield-generating token.

### CODE REVIEW

**Comment by Cryptocool1** [comment]
PR should include only 2 files
This is a BEp20 token, correct folder is blockchains/smartchain/assets.

**Review by davsonsantos — COMMENTED** [review]
Update logo Brigadeiro

**Comment by Cryptocool1** [comment]
> Update logo Brigadeiro

please delete all unnecessary files.

**Comment by Cryptocool1** [comment]
correction needed:
Contract is not in checksum format, should be 0x5B69eAbF1c748F590F60906D964158DBA0F53285

**Comment by davsonsantos** [comment]
The contract name has already been renamed as requested and is still rejecting it. What should I do?

**Pull request merged**
