### PR TITLE
Add logo for CRVT

### PR DESCRIPTION
**Pull request by realrouse**
Thank you.

### CODE REVIEW

**Comment by daniunss** [comment]
2000 TWT has been paid
EF959B763879DE66829B18FE265684A6C38AC2BDFC791CD23456DC638BC86662

**Comment by daniunss** [comment]
https://explorer.binance.org/tx/EF959B763879DE66829B18FE265684A6C38AC2BDFC791CD23456DC638BC86662

Well you can check. It's successful transactions for the 2000 TWT

**Comment by realrouse** [comment]
The 2000 TWT is paid by @daniunss 
Please help to resolve this issue.

**Comment by daniunss** [comment]
Well Memo 2722 is not on the list. It's paid. I already sent a proof

**Comment by catenocrypt** [comment]
@daniunss , yes, I can see valid payment.  I am investigating why it was not picked up by the bot.
The PR has other issues as well, it has a merge conflict, and CI build did not complete, I am fixing those.

**Comment by catenocrypt** [comment]
Payment accepted manually (https://explorer.binance.org/tx/EF959B763879DE66829B18FE265684A6C38AC2BDFC791CD23456DC638BC86662).

**Comment by daniunss** [comment]
Thanks for solving the issue

**Pull request merged**
