### PR TITLE
Add logo for 0xa10ae543dB5D967a73E9Abcc69c81a18A7Fc0A78

### PR DESCRIPTION
**Pull request by ghost**
Add logo for Ethereum Token 0xa10ae543dB5D967a73E9Abcc69c81a18A7Fc0A78

### CODE REVIEW

**Comment by blockclout** [comment]
Hi. the fee has been paid. Has our logo been added?

**Comment by blockclout** [comment]
https://explorer.binance.org/tx/7D92E6CFA99C856B61312EF21AACF23E5731E2986138F8A29BD8AC7E272C2968

**Comment by catenocrypt** [comment]
As I see, the paid sum is too low, only 0.93829499 BNB.  Could you complement it up to 1.0?

0.93829499 BNB | 2746 | 2020-07-15T09:49:54.818Z | bnb1kk77vq7vgnkas50h570kp83nsfu7enn03e0hga | 7D92E6CFA99C856B61312EF21AACF23E5731E2986138F8A29BD8AC7E272C2968

**Comment by blockclout** [comment]
Ok will send the remainder

**Comment by blockclout** [comment]
Remainder sent: https://explorer.binance.org/tx/23631E62B11E741EAE7D7E6F253141570C62D70F6429557B2FB3BDC709DCDE92

**Comment by blockclout** [comment]
Everything is there now. Please let us know when this is complete

**Comment by kaycoinsUSA** [comment]
Commit

**Comment by blockclout** [comment]
@catenocrypt please assist. Thank you

**Comment by catenocrypt** [comment]
Payment accepted manually

**Pull request merged**
