### PR TITLE
Add YES WORLD (BEP20)

### PR DESCRIPTION
**Pull request by yesworldyw24**
Adding info for BEP20 token 'YES WORLD'.

PR created by <a href="https://assets.trustwallet.com">TW Assets Management</a>

### CODE REVIEW

**Comment by cryptomanz1** [comment]
#21593

**Comment by cryptomanz1** [comment]
• What is the purpose of this token? How will it benefit Trust Wallet users?
 • How is the token being distributed? Are you conducting an airdrop?
 • Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?
 • Is the token listed on a centralized/decentralized exchange?
 • Is a Smart Contract audit completed? Where can we find this information?

**Comment by YesWorld24** [comment]
> • What is the purpose of this token? 

Ans - The main purpose of YES TOKEN will be the analyse, clean and tokenize the Carbon emission data received from various sources. It will also be used for utility service on YES WORLD platform. 


How will it benefit Trust Wallet users? 

Ans - Yes World Token will be staked or hold on Trust Wallet for value appreciation. Trust Wallet is also being promoted as default token swap from YES World. There is already several thousand Trust Wallet user holding YES Token on their wallet. We would like to reinforce their trust by having YES logo on Trust Wallet.

• How is the token being distributed? 

Ans - Token is being given to the internal community of ours. Founders of YES WORLD have a strong background in startups and hence strong community and and know the ways of marketing to foster early adoption. We do plan on adding more adoptions by Airdrops, Staking and Public launch.    We have our own portal where user initially receives the token which he then transfers to Trust Wallet. 


Are you conducting an airdrop? 

Ans 0 We are planning on Airdrop and will distribute a significant percentage of tokens via airdrop for user adoption. Our Airdrop is schedule to start on 23/3/2023.


• Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?  

Ans - NO

• Is the token listed on a centralized/decentralized exchange?

Ans - We are currently listed on Coinsbit.io. VinDAX and BankCEX. Most of our users trade on Coinsbit.io.

 • Is a Smart Contract audit completed? Where can we find this information?

Ans - not at the moment, we are finalizing an auditor this week and should get this done next week.

**Comment by yesworldyw24** [comment]
I had commented the tickets but bot deleted that. Please see answers 
below here -

* What is the purpose of this token? How will it benefit Trust Wallet 
users?

ANS - YES WORLD Token will be used to analyse, clean and tokenize the 
Carbon emission data received from various third party service or IoTs. 
That the main utility. YES WORLD Token will also be used for several 
other Utility services available on YES WORLD Platform.

* How is the token being distributed? Are you conducting an airdrop?

ANS - Tokens have been issued to internal community members. Founders of 
YES WOLRD had strong background in D2C startups and hence strong 
community.  Airdrop is an important part of our strategy and planning 
one of the biggest airdrop with 1 billion tokens. Airdrop will open on 
23/3/2013 as per our roadmap.

* Did you sold the tokens at an Initial Coin Offering (ICO) or a token 
presale?

ANS - NO

* Is the token listed on a centralized/decentralized exchange?

ANS - Yes, it is currently available on Coinsbit.io. We are also listed 
on CoinMarketCap and Coinsgecko.

On 2022-07-21 13:52, Nazar wrote:

> * What is the purpose of this token? How will it benefit Trust Wallet 
> users?
> * How is the token being distributed? Are you conducting an airdrop?
> * Did you sold the tokens at an Initial Coin Offering (ICO) or a token 
> presale?
> * Is the token listed on a centralized/decentralized exchange?
> * Is a Smart Contract audit completed? Where can we find this 
> information?
> 
> --
> Reply to this email directly, view it on GitHub [1], or unsubscribe 
> [2].
> You are receiving this because you authored the thread.Message ID: 
> ***@***.***>



Links:
------
[1] 
https://github.com/trustwallet/assets/pull/21592#issuecomment-1191191064
[2]

**Comment by YesWorld24** [comment]
> 


• What is the purpose of this token? How will it benefit Trust Wallet users?

ANS - YES WORLD Token will be used to analyse, clean and tokenize the Carbon emission data received from various third party service or IoTs. That the main utility. YES WORLD Token will also be used for several other Utility services available on YES WORLD Platform.




• How is the token being distributed? Are you conducting an airdrop?

ANS - Tokens have been issued to internal community members. Founders of YES WOLRD had strong background in D2C startups and hence strong community.  Airdrop is an important part of our strategy and planning one of the biggest airdrop with 1 billion tokens. Airdrop will open on 23/3/2013 as per our roadmap.

• Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?  

ANS - NO



• Is the token listed on a centralized/decentralized exchange?

ANS - Yes, it is currently available on Coinsbit.io. We are also listed on CoinMarketCap and Coinsgecko.

**Comment by Cryptocool1** [comment]
* Is a Smart Contract audit completed? Where can we find this
 information?

**Comment by Cryptocool1** [comment]
We require audit from reputable companies. Please see the requirements here:
https://developer.trustwallet.com/assets/requirements

**Comment by YesWorld24** [comment]
>  * Is a Smart Contract audit completed? Where can we find this
>  information?

Please let me know if the "Security Analysis and Code Review" done by firm - Solidity Finance LLC, will be acceptable. We are about to finalize this for YES WORLD TOKEN audit.

Pls confirm.

**Comment by YesWorld24** [comment]
Engaged an audit firm, scheduled for early next week. Will this be on hold until I submit the report? Our target is the show up the logo for YES on Trust Wallet. Please note that YES is currently showing up, we just need "BEP20" to show the logo, and that the goal of this exercise.

Please confirm if there is anything else pending except the Audit report, on this exercise.

**Comment by yesworldyw24** [comment]
we have assign an auditor for smart contract review. The report should 
arrive early next week.

I see this closed but Aim of this exercise is to bring YES logo on Trust 
Wallet, so this or some related ticket should remain open until the Aim 
is met.

On 2022-07-21 18:19, CryptoA wrote:

> Closed #21592 [1].
> 
> --
> Reply to this email directly, view it on GitHub [2], or unsubscribe 
> [3].
> You are receiving this because you authored the thread.Message ID: 
> ***@***.***>



Links:
------
[1] https://github.com/trustwallet/assets/pull/21592
[2] https://github.com/trustwallet/assets/pull/21592#event-7038021370
[3]

**Comment by Cryptocool1** [comment]
Feel free to create new PR once the criteria are met

**Comment by yesworldyw24** [comment]
Hello,

Audit report is now available on below link -

https://github.com/cyberscope-io/audits/blob/main/yes/audit.pdf

Please advise if anything else is needed at my end, to show up logo for 
YES WORLD on TrustWallet.

On 2022-07-23 21:28, CryptoA wrote:

> Feel free to create new PR once the criteria are met
> 
> --
> Reply to this email directly, view it on GitHub [1], or unsubscribe 
> [2].
> You are receiving this because you authored the thread.Message ID: 
> ***@***.***>



Links:
------
[1] 
https://github.com/trustwallet/assets/pull/21592#issuecomment-1193146847
[2]

**Comment by YesWorld24** [comment]
Audit report is available on this link - https://github.com/cyberscope-io/audits/blob/main/yes/audit.pdf

Please check and let me know if anything else is required from my end, to enable to logo on Trust wallet

**Comment by YesWorld24** [comment]
@cryptomanz1 @Cryptocool1 please advise how to move forward from here, I provided audit report like already. I would know how to open new PR, so please do the needful. Goal is to get logo on TW

**Comment by yesworldyw24** [comment]
Hello,

Please advise next steps on this. We need logo to be shown on TW and 
have already made the payment.

Thanks,

Praveen

On 2022-07-24 14:35, Yes World wrote:

> Hello,
> 
> Audit report is now available on below link -
> 
> https://github.com/cyberscope-io/audits/blob/main/yes/audit.pdf
> 
> Please advise if anything else is needed at my end, to show up logo for 
> YES WORLD on TrustWallet.
> 
> On 2022-07-23 21:28, CryptoA wrote:
> 
>> Feel free to create new PR once the criteria are met
>> 
>> --
>> Reply to this email directly, view it on GitHub [1], or unsubscribe 
>> [2].
>> You are receiving this because you authored the thread.Message ID: 
>> ***@***.***>



Links:
------
[1] 
https://github.com/trustwallet/assets/pull/21592#issuecomment-1193146847
[2]

**Pull request merged**
