### PR TITLE
Add files via upload

### PR DESCRIPTION
**Pull request by SafePokeman**
This PR is being closed due to inactivity. If you wish to continue, please have us reopen the PR before sending your payment, or just create a new one.
Do NOT send payments for closed PR, as the fee may by lost!
  (48 vs. 48 hrs)

### CODE REVIEW

**Review by SafePokeman — COMMENTED** [review]
It appears as correct

**Comment by SafePokeman** [comment]
Added logo

**Comment by SafePokemanOfficial** [comment]
@merge-fee-bot 

> This PR is being closed due to inactivity. If you wish to continue, please have us reopen the PR before sending your payment, or just create a new one.
> Do NOT send payments for closed PR, as the fee may by lost!
> (48 vs. 48 hrs)

Please can you reopen this so i can send payment?
Thank you

**Comment by SafePokeman** [comment]
reopen request

**Pull request closed without merging**
