### PR TITLE
Add Altranium (ERC20)

### PR DESCRIPTION
**Pull request by ALTRANIUM**
Adding info for ERC20 token 'Altranium'.

PR created by <a href="https://assets.trustwallet.com">TW Assets Management</a>

### CODE REVIEW

**Comment by Cryptocool1** [comment]
• What is the purpose of this token? How will it benefit Trust Wallet users?
 • How is the token being distributed? Are you conducting an airdrop?
 • Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?
 • Is the token listed on a centralized/decentralized exchange?
 • Is a Smart Contract audit completed? Where can we find this information?

**Comment by halagu1l** [comment]
> ### PR Summary
> Files OK: 2 Token in PR: **ERC20** 0xb9600c807f069D27f92a2a65b48F12Eeef7e2007 Symbol: **ALTR** decimals: 18 Links: [Logo](https://raw.githubusercontent.com/ALTRANIUM/assets/br0822-163724/blockchains/ethereum/assets/0xb9600c807f069D27f92a2a65b48F12Eeef7e2007/logo.png) [Info](https://raw.githubusercontent.com/ALTRANIUM/assets/br0822-163724/blockchains/ethereum/assets/0xb9600c807f069D27f92a2a65b48F12Eeef7e2007/info.json) [Website](https://altranium.com/) [ExplorerFromInfo](https://arbiscan.io/token/0xb9600c807f069d27f92a2a65b48f12eeef7e2007?a=0xFd086bC7CD5C481DCC9C85ebE478A1C0b69FCbb9) [ExplorerFromID](https://etherscan.io/token/0xb9600c807f069D27f92a2a65b48F12Eeef7e2007) Tags: gamefi Token check error: ❌ explorer field incorrect: should be standard https://etherscan.io/token/0xb9600c807f069D27f92a2a65b48F12Eeef7e2007, not https://arbiscan.io/token/0xb9600c807f069d27f92a2a65b48f12eeef7e2007?a=0xFd086bC7CD5C481DCC9C85ebE478A1C0b69FCbb9 ❌ invalid value 'https://www.coingecko.com/en/coins/altranium' for coingecko link url, allowed only with prefix: https://coingecko.com/ ❌ number of holders not checked: please, check it manually
> 
>

**Comment by ALTRANIUM** [comment]
Instead of updating Logo and Fetching Dollar value, a new token has been listed instead under the incorrect network chain.

The desired (existing) network chain is Arbitrum; however it is published under ERC20.

Please advise.

**Comment by cryptomanz1** [comment]
We will change

**Review by Cjgdfjfd64 — COMMENTED** [review]
[0x7Fc66500c84A76Ad7e9c93437bFc5Ac33E2DDaE9](url)

**Comment by Cambridge01** [comment]
How do I get to know about the next zealy campaign do you have a discord server

**Pull request merged**
