### PR TITLE
Add CPIE token to Trust Wallet

### PR DESCRIPTION
**Pull request by CPIErocket**
Add CPIE token to Trust Wallet

### CODE REVIEW

**Comment by cryptomanz** [comment]
can you please add links?
see the example here: https://developer.trustwallet.com/add_new_asset/repository_details

**Comment by cryptomanz** [comment]
Answer the questions please
• What is the purpose of this token? How will it benefit Trust Wallet users?
 • How is the token being distributed? Are you conducting an airdrop?
 • Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?
 • Is the token listed on a centralized/decentralized exchange?
 • Is a Smart Contract audit completed? Where can we find this information?

**Comment by CPIErocket** [comment]
Dear Mr @cryptomanz,

We already add links according to your requirement

About your 05 questions, please kindly see our answer as:
• What is the purpose of this token? How will it benefit Trust Wallet users?
=> CPIE token is utility and governance token of cremepieswap.finance, alead chain adoption by creating the lowest fee, highest rewarding AMM on the Polygon (MATIC) network . Trustwallet users will use our token to use the dapps from cremepieswap.finance

• How is the token being distributed? Are you conducting an airdrop?
=> CPIE is distributed through IDO. We do not do airdrop

• Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?
=> We've done public sale for CPIE on July 12th 2021 on pad.lz.finance (LaunchZone).

• Is the token listed on a centralized/decentralized exchange?
=> On dex cremepieswap.finance

• Is a Smart Contract audit completed? Where can we find this information?
=> Not yet

Thanks and Regards,

**Comment by Cryptocool1** [comment]
awaiting for smart contract audit

**Comment by Cryptocool1** [comment]
Please create new PR when smart contract audit will be ready.
Make sure to mention this PR, so the fee can be reused

**Pull request closed without merging**
