### PR TITLE
Add ERC20 Giftedhands (GHD Giftedhands.io)  

### PR DESCRIPTION
**Pull request by giftedhandsGHD**

### CODE REVIEW

**Comment by yinusa** [comment]
**All checks have failed** - Is this an obstacle to listing? please tell me what is the possible reason?

**Comment by yinusa** [comment]
**All checks have failed** - Is this an obstacle to listing? @catenocrypt please tell me what is the possible reason and what should i do?

**Comment by yinusa** [comment]
All checks have failed - Is this an obstacle to listing? @catenocrypt please tell me what is the possible reason and what should i do?
@Iamdeadlyz @zachzwei
https://coinmarketcap.com/currencies/giftedhands/

Please help us add logo and token information on trust wallet

**Comment by catenocrypt** [comment]
@yinusa , it seems the info.json file is invalid, the last line should not contain a trailing comma.  Could you remove it?

```
-  X 'Check all JSON files to have valid content':  1 errors
   X   '/home/runner/work/assets/assets/blockchains/ethereum/assets/0x3b544e6fcf6c8dce9d8b45a4fdf21c9b02f9fda9/info.json path contains invalid JSON'
```

**Comment by catenocrypt** [comment]
I've fixed the Json file

**Comment by catenocrypt** [comment]
As per our policy, brand new tokens are not included, there is a minimum requirement of 2500 holder addresses and 5000 transactions, in order to filter out scam tokens.
See the criteria at (mentioned in the first message by the bot): https://community.trustwallet.com/t/how-to-submit-a-token-logo/3863).
This token has low usage yet (408). Closing PR for now. Please come back to us when all criteria are met.

https://etherscan.io/token/0x3b544e6fcf6C8dCE9D8B45A4FdF21C9B02f9fDa9

**Pull request closed without merging**
