### PR TITLE
Add GOLD FINCH CRYPTO CURRENCY (BEP20)

### PR DESCRIPTION
**Pull request by BDCC18**
Adding info for BEP20 token 'GOLD FINCH CRYPTO CURRENCY'.

PR created by <a href="https://assets.trustwallet.com">TW Assets Management</a>

### CODE REVIEW

**Comment by Cryptocool1** [comment]
Hello,
As per our policy, brand new tokens are not included, there is a minimum requirement of 2500 holder addresses and 5000 transactions, in order to filter out scam tokens.
See the criteria at (mentioned in the first message by the bot): https://community.trustwallet.com/t/how-to-submit-a-token-logo/3863).

**Comment by BDCC18** [comment]
As per our policy, brand new tokens are not included, there is a minimum requirement of 2500 holder addresses and 5000 transactions, in order to filter out scam token


heloo team GFCC TOKEN NOW DONE TRANSFER HOLDER IS 2500

PLZ APROVEL LIVE ON TRUST WALLET GFCC LIVE PRICE/LOGO/MARKET TRADING LIVE PLZ

**Comment by BDCC18** [comment]
HELOO TEAM PLZ UPDATE   GOLD FINCH CRYPO CURRENCY [GFCC TOKEN] NOW DONE TRANSFER HOLDER IS 2500

PLZ APROVEL LIVE ON TRUST WALLET GFCC LIVE PRICE/LOGO/MARKET TRADING LIVE PLZ

**Comment by BDCC18** [comment]
GFCC IS LIVE ON TRUST WALLET??????

PLZ REPLY ME

**Comment by BDCC18** [comment]
HOW LONG TIME GFCC LIVE SHOW IN TRUST WALLET?????

**Comment by BDCC18** [comment]
HELOO TEAM PLZ UPDATE GOLD FINCH CRYPO CURRENCY [GFCC TOKEN]  LIVE PRICE SHOW PLZ

PLZ APROVEL LIVE RATE IN TRUST WALLET GFCC LIVE PRICE/MARKET TRADING LIVE PLZ

COIN PAPRIKA LIVE TRADING LINK
https://coinpaprika.com/coin/gfcc-gold-finch-crypto-currency/

**Comment by BDCC18** [comment]
HELOO TEAM PLZ UPDATE GOLD FINCH CRYPO CURRENCY [GFCC TOKEN] LIVE PRICE SHOW PLZ

PLZ APROVEL LIVE RATE IN TRUST WALLET GFCC LIVE PRICE/MARKET TRADING LIVE PLZ

COIN PAPRIKA LIVE TRADING LINK
https://coinpaprika.com/coin/gfcc-gold-finch-crypto-currency/

**Comment by BDCC18** [comment]
> Hello,
> As per our policy, brand new tokens are not included, there is a minimum requirement of 2500 holder addresses and 5000 transactions, in order to filter out scam tokens.
> See the criteria at (mentioned in the first message by the bot): https://community.trustwallet.com/t/how-to-submit-a-token-logo/3863).


HELOO TEAM PLZ UPDATE GOLD FINCH CRYPO CURRENCY [GFCC TOKEN] LIVE PRICE SHOW PLZ

PLZ APROVEL LIVE RATE IN TRUST WALLET GFCC LIVE PRICE/MARKET TRADING LIVE PLZ

COIN PAPRIKA LIVE TRADING LINK
https://coinpaprika.com/coin/gfcc-gold-finch-crypto-currency/

**Pull request merged**
