### PR TITLE
Add WATER RABBIT  (BEP20)

### PR DESCRIPTION
**Pull request by Waterrabbittoken**
Adding info for BEP20 token 'WATER RABBIT '.

PR created by <a href="https://assets.trustwallet.com">TW Assets Management</a>

### CODE REVIEW

**Comment by Waterrabbittoken** [comment]
P2B CEX Link : https://p2pb2b.com/trade/WAR_USDT/

**Comment by Cryptocool1** [comment]
• What is the purpose of this token? How will it benefit Trust Wallet users?
 • How is the token being distributed? Are you conducting an airdrop?
 • Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?
 • Is the token listed on a centralized/decentralized exchange?
 • Is a Smart Contract audit completed? Where can we find this information?

**Comment by Waterrabbittoken** [comment]
•What is the purpose of this token?How will it benefit Trust Wallet users?
$WAR's primary use case is to function as a digital currency. 
Users can leverage it as a medium of exchange, store of value, and unit of account.
 Our ongoing collaborations with top institutions aim to significantly expand the
 utility of $WAR, making it a versatile token within the digital asset ecosystem.
 As we progress, we expect to see $WAR adopted in various financial and commercial
 scenarios, driving its value and significance in the digital economy.

• How is the token being distributed? 
Users purchased the tokens from Pool.

Are you conducting an airdrop?
We are done with airdrop.

• Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?
Fair launch.

• Is the token listed on a centralized/decentralized exchange?
The token is listed on Dex; Pancakeswap,Centralized exchange; P2B. 

• Is a Smart Contract audit completed? Where can we find this information?
Link ; https://solidity.finance/audits/WATERRABBIT

**Comment by Waterrabbittoken** [comment]
@Cryptocool1  @cryptomanz1

**Comment by Waterrabbittoken** [comment]
25th May,2023

**Comment by Waterrabbittoken** [comment]
@Cryptocool1

**Comment by Cryptocool1** [comment]
How many holders did you get from airdrop?

**Comment by Waterrabbittoken** [comment]
> How many holders did you get from airdrop?

Can't tell the specific number but a range from 500 to 1000 participants was anticipated to the airdrop.

**Comment by Waterrabbittoken** [comment]
We launched Water Rabbit on 27th July, 2022 and was sent to pancakeswap for the general public to buy.

We did numerous marketing to get investors to buy Water Rabbit Token.

**Comment by Waterrabbittoken** [comment]
@Cryptocool1

**Comment by Waterrabbittoken** [comment]
> Thank you for your answer.

You're welcome 😊

**Pull request merged**
