### PR TITLE
ADD Nft Wars Token info and Logo

### PR DESCRIPTION
**Pull request by p1m0dium**
Please add NFT WARS token info and logo in trustwallet. Thank you

### CODE REVIEW

**Comment by catenocrypt** [comment]
Correction needed: Files have double extension, hence don't comply with conventions.  Please rename.

image

**Comment by catenocrypt** [comment]
As per our policy, brand new tokens are not included, there is a minimum requirement of 2500 holder addresses and 5000 transactions, in order to filter out scam tokens.
See the criteria at (mentioned in the first message by the bot): https://community.trustwallet.com/t/how-to-submit-a-token-logo/3863).
This token has low usage yet (621 holders). Closing PR for now. Please come back to us when all criteria are met.  Multi-chain and staking tokens may get special treatment, let us know if this is the case. 

https://etherscan.io/token/0x4d75d9e37667a2d4677ec3d74bdd9049326ad8d6

**Comment by p1m0dium** [comment]
@catenocrypt can i open it again if we hit the policy? thanks

**Comment by catenocrypt** [comment]
Yes, just add a new comment and we can reopen.

**Pull request closed without merging**
