### PR TITLE
Add BEP20 | ERC20 (ERC20)

### PR DESCRIPTION
**Pull request by TokenERC20**
https://bscscan.com/address/0x58730ae0faa10d73b0cddb5e7b87c3594f7a20cb

### CODE REVIEW

**Comment by catenocrypt** [comment]
Correction needed: you need to specify more info, please create a json file called `info.json` next to the logo.png, with the following structure:

```json
{
    "name": "Bondly",
    "type": "ERC20",
    "symbol": "BONDLY",
    "decimals": 18,
    "description": "<fill with a few sentence description>",
    "website": "https://www.bondly.finance",
    "explorer": "https://etherscan.io/token/0xD2dDa223b2617cB616c1580db421e4cFAe6a8a85",
    "status": "active",
    "id": "0xD2dDa223b2617cB616c1580db421e4cFAe6a8a85"
}
```

**Comment by TokenERC20** [comment]
`{
    "name": "ERC20",
    "type": "BEP20",
    "symbol": "ERC20",
    "decimals": 18,
    "description": "ERC20 is an innovative NFTs Collectibles token and a new kind of DeFi crypto",
    "website": "https://erc20.tech",
    "CoinGecko": "https://www.coingecko.com/en/coins/erc20",
    "CoinMarketCap": "https://coinmarketcap.com/currencies/erc20/",
    "explorer": "https://bscscan.com/address/0x58730ae0faa10d73b0cddb5e7b87c3594f7a20cb",
    "status": "active",
    "id": "0x58730ae0faa10d73b0cddb5e7b87c3594f7a20cb"
}`

**Comment by TokenERC20** [comment]
https://gist.github.com/TokenERC20/7b125b045fe4596dcf7dee469132eeeb

**Comment by TokenERC20** [comment]
#9b36217

**Comment by TokenERC20** [comment]
[0x58730ae0FAA10d73b0cDdb5e7b87C3594f7a20CB:info.json](url)

**Comment by TokenERC20** [comment]
couldn't  add here the json file , so here is pull where I dropped the info.json #5978
and logo

**Comment by TokenERC20** [comment]
also to avoid misunderstanding. It's not a brand new coin , this coin has launched on additional blockchain - SmartChain. Kindly asking to add the logo and json file for ERC20 (ERC20) on SmartChain.

information about 2 blockchains are verified on both platforms CoinGecko and CoinMarketCap. And token has already a lot of holders ( 97.000)  on another blockchain. 

https://www.coingecko.com/en/coins/erc20
https://coinmarketcap.com/currencies/erc20 

https://bscscan.com/token/0x58730ae0FAA10d73b0cDdb5e7b87C3594f7a20CB
https://etherscan.io/token/0xc3761eb917cd790b30dad99f6cc5b4ff93c4f9ea

**Comment by catenocrypt** [comment]
As files are mixed up here, I suggest you create a new PR, from scratch.  Please follow our guide
https://community.trustwallet.com/t/how-to-submit-a-token-logo/3863
(files committed in the PR, not attached as comments).
Mention this PR (#5935) in the new one, so that fee does not have to be paid again.

**Comment by catenocrypt** [comment]
Closed in favor of #5978 .

**Comment by catenocrypt** [comment]
Merged with #5978 .

**Pull request closed without merging**
