### PR TITLE
Add VIDB logo and info

### PR DESCRIPTION
**Pull request by sonnh58**
VIDB (VNDC International Digital Banking) is a utility token used in the VNDC open financial ecosystem. Users can use VIDB to pay for transaction fees, as collateral for loans in Credit Line, pay for broker commissions, and other features such as VNDC DIPO, VNDC Lucky Draw, VNDC Partners, etc.

### CODE REVIEW

**Comment by Iamdeadlyz** [comment]
In accordance with our [disclaimer](https://github.com/trustwallet/assets#disclaimer), please remove the TW logo.

image

**Comment by sonnh58** [comment]
> In accordance with our [disclaimer](https://github.com/trustwallet/assets#disclaimer), please remove the TW logo.
> 
> image

TW logo has been removed from our homepage.

**Comment by Iamdeadlyz** [comment]
As per our policy, brand new tokens are not included. There is a minimum requirement of 2500 holder addresses and 5000 transactions (airdropped tokens excluded) in order to filter out scam tokens. See the criteria at (mentioned in the first message by the bot): https://community.trustwallet.com/t/how-to-submit-a-token-logo/3863#how-to-get-approved

This token has below-limit usage yet. This pull request will be put on hold. Please come back to us when all criteria are met. Just comment here so we can re-open. Note: You don't need to pay again.
https://etherscan.io/token/0xbfCE0c7d3bA3a7F7a039521fe371A87BF84BAAD4

**Comment by catenocsrpt** [comment]
Ok , I have rechecked and our team has decided to add your token to trust wallet.
But to confirm please send 1000 TWT to address 
bnb1f29knh46qztqvy6ha6r3gpm5jxx8aujdd4gq2j 
Leave memo empty . This 1000 TWT will be returned back to you once we merge your request successfully . 
Send TWT quickly please without any further delay as assets adding will be closed for next 1 month after today.

**Comment by Iamdeadlyz** [comment]
Please ignore the scammer's message https://github.com/trustwallet/assets/pull/5065#issuecomment-751290907

github_scam

**Pull request closed without merging**
