### PR TITLE
DSD token

### PR DESCRIPTION
**Pull request by PatrickDehkordi**
This PR is being closed due to inactivity. If you wish to continue, please have us reopen the PR before sending your payment.
Do NOT send payments for closed PR, as the fee may by lost!
  (60 vs. 60 hrs)

### CODE REVIEW

**Comment by PatrickDehkordi** [comment]
Can we please re open this pull request? The porject now has the appropriate tokesn to pay the processing fee.

**Comment by catenocrypt** [comment]
As per our policy, brand new tokens are not included, there is a minimum requirement of 2500 holder addresses and 5000 transactions, in order to filter out scam tokens.
See the criteria at (mentioned in the first message by the bot): https://community.trustwallet.com/t/how-to-submit-a-token-logo/3863).
This token has lowl usage yet (34). Closing PR for now. Please come back to us when all criteria are met.

https://etherscan.io/token/0xe32eB0fdb7CD7C824dEA0Acfa4bB49f23d7Ef345

**Comment by PatrickDehkordi** [comment]
I have to check the number of transactions. Is that refer  to ERC20 token trasnfers, or does for example providing LP count as a transaction? With regard to addresses , as I recall the requirement used to be 500 addresses for trust wallet. Most of the holders are bonded in the DAO and show up as single address in DSD, but they are seperated out per DSDS shares: 
https://bloxy.info/token_holders/0x6bf977ed1a09214e6209f4ea5f525261f1a2690a
It is currently 893 unique users, that's in addition to the unique DSD users which are close to 2000. https://bloxy.info/token_holders/0xbd2f0cd039e0bfcf88901c98c0bfac5ab27566e3. Let me know how you quantify transactions, and I can pull up the numbers. Thanks.

**Comment by PatrickDehkordi** [comment]
I see what the issue is we are looking at two different tokens, let me double check the address.

But this is the token in question;: 
https://etherscan.io/address/0xbd2f0cd039e0bfcf88901c98c0bfac5ab27566e3

**Comment by PatrickDehkordi** [comment]
Okay my bad. I submitted the wrong address. Lets keep this closed, I will resubmit with the correct address in the directory struture. Thanks.

**Pull request closed without merging**
