### PR TITLE
Coc integration 2

### PR DESCRIPTION
**Pull request by LParoni**
Hi, we just updated the configuration as requested by previous request.

### CODE REVIEW

**Comment by Cryptocool1** [comment]
• What is the purpose of this token? How will it benefit Trust Wallet users?
 • How is the token being distributed? Are you conducting an airdrop?
 • Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?
 • Is the token listed on a centralized/decentralized exchange?
 • Is a Smart Contract audit completed? Where can we find this information?

**Comment by LParoni** [comment]
> • What is the purpose of this token? How will it benefit Trust Wallet users? • How is the token being distributed? Are you conducting an airdrop? • Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale? • Is the token listed on a centralized/decentralized exchange? • Is a Smart Contract audit completed? Where can we find this information?

- COC token was created to link blockchain and sport industry. The project aims to create a collectible NFT card game based on sports. Sharing, community building, famous sports testimonials and the chance of saving: these are the concepts conveyed through the structure of the brand.
- The token has been pre minted and listed on Pancakeswap
- The token has been sold at a token presale
- The token is listed on Pancakeswap so far
- No, we are working to complete the smart contract audit as soon as possible

**Comment by cryptomanz** [comment]
Awaiting for smart contract audit. On hold for now

**Comment by Cryptocool1** [comment]
Please come back to us when all criteria are met.
When creating a new PR make sure to mention this PR, so that we can see that fee has been paid already here.

**Pull request closed without merging**
