### PR TITLE
Add MetaNFT Logo

### PR DESCRIPTION
**Pull request by MetaNFTSteve**
Add MetaNFT Logo + info.json

Where are alreay on 
CMC: https://coinmarketcap.com/currencies/metanft/
CRYPTO.COM https://crypto.com/price/metanft
Binance: https://www.binance.com/en/price/metanft

### CODE REVIEW

**Comment by MetaNFTSteve** [comment]
Hi @Iamdeadlyz, @Cryptocool1, @cryptomanz,

We are already on : 
CMC: https://coinmarketcap.com/currencies/metanft/
CRYPTO.COM https://crypto.com/price/metanft
Binance: https://www.binance.com/en/price/metanft

Thanks

**Comment by Cryptocool1** [comment]
can you please add tags?
see the requirements here : https://developer.trustwallet.com/assets/repository_details

**Comment by Cryptocool1** [comment]
• What is the purpose of this token? How will it benefit Trust Wallet users?
 • How is the token being distributed? Are you conducting an airdrop?
 • Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?
 • Is the token listed on a centralized/decentralized exchange?
 • Is a Smart Contract audit completed? Where can we find this information?

**Comment by MetaNFTSteve** [comment]
Hi @Cryptocool1,

Done for tags.

To answer your questions : 
**• What is the purpose of this token? How will it benefit Trust Wallet users?**
The first NFT Cross-Chain marketplace. Buy and Sell your NFTs in synergy and simultaneously on Ethereum, BSC, and Polygon. Simple, powerful and fast
https://metanft-market.place/

**• How is the token being distributed? Are you conducting an airdrop?**
This token is distributed via pancakeswap, and soon on Cointiger

To encourage our investors to hold MNFT, we have created a unique rewarding system and dashboard where our investors can track their rewards. The rewards will be given every 48 hours. Our team has developed a reward system based on loyalty through its smart contract.

The rewards are distributed to two types of holders:
- MetaNFT's 1000 Biggest Holders
- MetaNFT's 1000 Oldest Holders

And yes we conducting an airdrop sometime

**• Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?**
Yes Presale on PinkSale
https://www.pinksale.finance/#/launchpad/0xa7361389f4325495ED29Dd472B449DfA91B88F9b?chain=BSC

**• Is the token listed on a centralized/decentralized exchange?**
PancakeSwap https://pancakeswap.finance/swap?outputCurrency=0xdedd744cc359810D02aa49E30CAf91C33fe6Af6c
CoinTiger Soon

**• Is a Smart Contract audit completed? Where can we find this information?**
Certik audit in progress : https://www.certik.com/projects/metanft
Source Code : https://github.com/MetaNFTSteve/token

Thanks

**Comment by Cryptocool1** [comment]
awaiting for full smart contract audit, on hold for now

**Pull request closed without merging**
