### PR TITLE
Add Bogecoin (BEP20)

### PR DESCRIPTION
**Pull request by zerosdontcount**
This PR is being closed due to inactivity. If you wish to continue, please have us reopen the PR before sending your payment, or just create a new one.
Do NOT send payments for closed PR, as the fee may by lost!
  (48 vs. 48 hrs)

### CODE REVIEW

**Comment by zerosdontcount** [comment]
This asset already exists, we are merely updating the logo.

**Comment by zerosdontcount** [comment]
It made us pay on 7879 already, it's now asking us to pay again.

**Comment by catenocrypt** [comment]
Please clarify what you want to achieve.
From what I see:
- 7769: token info added; paid, merged
- 7879: token info removed; paid, merged
- 7885: attempts to add, but logo only!

Before creating new PRs, please re-create or refresh you forked repo!

**Comment by zerosdontcount** [comment]
> Please clarify what you want to achieve.
> From what I see:
> 
> * 7769: token info added; paid, merged
> * 7879: token info removed; paid, merged
> * 7885: attempts to add, but logo only!
> 
> Before creating new PRs, please re-create or refresh you forked repo!

My apologies, we simply want to add the new logo (circle logo) which replaces the old one.

**Pull request closed without merging**
