### PR TITLE
Add VLaunch (BEP20) and deprecate old contracts

### PR DESCRIPTION
**Pull request by dban0001**
Resources:

- https://medium.com/vlaunch-blog/vpad-token-migration-elevating-efficiency-on-binance-smart-chain-7117da7800b1
- https://twitter.com/VLaunchCOM/status/1749812336901378543
- 18k holders (https://bscscan.com/token/0xF574Ba6bde97cC09784e616ebAeD432b4e896B49)

The new contract can also be verified on https://vlaunch.com via the menu.

Fee already paid via #19332

• What is the purpose of this token? How will it benefit Trust Wallet users?

VPAD is a utility token for the vlaunch.com launchpad. Staking VPAD allows users to participate in ICOs for premium projects and benefit from free IDO airdrops (our last few were worth $200k-$300k each). We believe it will benefit Trust Wallet users and others by being able to move your VPAD between Trust and other wallets seamlessly, having a verified logo & info. We would also love if users would be able to swap VPAD (buy or sell, on ETH or BNB) directly in the Trust wallet.

• How is the token being distributed? Are you conducting an airdrop?

There was a free token airdrop of 30m tokens in December 2021 for the community for verified users using a ranking system, back in December 2021. Today it can be bought at 6 CEX & DEX exchanges.

• Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?

No, there was a private sale, but there was no public sale / ICO.

• Is the token listed on a centralized/decentralized exchange?

Yes, on: [PancakeSwap](https://pancakeswap.finance/swap?outputCurrency=0xF574Ba6bde97cC09784e616ebAeD432b4e896B49&inputCurrency=0x55d398326f99059fF775485246999027B3197955), [ByBit](https://www.bybit.com/en/trade/spot/VPAD/USDT), [Huobi / HTX](https://www.htx.com/en-us/trade/vpad_usdt), and soon more

• Is a Smart Contract audit completed? Where can we find this information?

[SlowMist Audit Report - VLaunch Monorepo Phase2.pdf](https://github.com/trustwallet/assets/files/14123811/SlowMist.Audit.Report.-.VLaunch.Monorepo.Phase2.pdf)

### CODE REVIEW

**Comment by steebchen** [comment]
Fee already paid via https://github.com/trustwallet/assets/pull/19332

**Comment by steebchen** [comment]
Fee already paid via https://github.com/trustwallet/assets/pull/19332

**Comment by dban0001** [comment]
Fee already paid via https://github.com/trustwallet/assets/pull/19332

**Comment by cryptomanz1** [comment]
paid

**Pull request merged**
