### PR TITLE
add EYE logo and info

### PR DESCRIPTION
**Pull request by eyeswap**
add EYE logo and info

### CODE REVIEW

**Comment by Cryptocool1** [comment]
Please create new PR, follow doc https://community.trustwallet.com/t/how-to-submit-a-token-logo/3863
You may want to try our Assets app in beta; go to https://assets.trustwallet.com, log on with Github, enter contract ID, logo and some additional info, and it will create a PR for you.
See https://community.trustwallet.com/t/how-to-submit-a-token-logo-using-assets-app/82957.

**Comment by eyeswap** [comment]
I have completed the transfer with a heap message. What should I do now

**Comment by eyeswap** [comment]
I have passed the requirements , please consider

**Comment by Cryptocool1** [comment]
your info.json is incorrect
I suggest creating new PR (you don't need to pay one more time)
 follow doc https://community.trustwallet.com/t/how-to-submit-a-token-logo/3863
You may want to try our Assets app in beta; go to https://assets.trustwallet.com, log on with Github, enter contract ID, logo and some additional info, and it will create a PR for you.
See https://community.trustwallet.com/t/how-to-submit-a-token-logo-using-assets-app/82957.

**Comment by eyeswap** [comment]
can i send info.json directly here

**Comment by cryptomanz** [comment]
> can i send info.json directly here
- sure

**Comment by eyeswap** [comment]
i think i did the right thing i don't know where i went wrong

**Comment by cryptomanz** [comment]
still incorrect.
I suggest creating new PR (you don't need to pay one more time)
follow doc https://community.trustwallet.com/t/how-to-submit-a-token-logo/3863
You may want to try our Assets app in beta; go to https://assets.trustwallet.com, log on with Github, enter contract ID, logo and some additional info, and it will create a PR for you.
See https://community.trustwallet.com/t/how-to-submit-a-token-logo-using-assets-app/82957.

**Comment by eyeswap** [comment]
I have tried it seems to have to pay more, how do I use it when I have already paid 
https://github.com/trustwallet/assets/pull/10902

**Pull request closed without merging**
