### PR TITLE
Shiba Floki Inu

### PR DESCRIPTION
**Pull request by ShibaFloki**
Shiba Floki Inu

### CODE REVIEW

**Comment by ShibaFloki** [comment]
> • What is the purpose of this token? How will it benefit Trust Wallet users? • How is the token being distributed? Are you conducting an airdrop? • Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale? • Is the token listed on a centralized/decentralized exchange? • Is a Smart Contract audit completed? Where can we find this information?

• We are best meme token on BSC and  2% gift tokens send all holders in every transaction and burn 2%
• Swap can be done via pancakeswap. We do not have an airdrop program.
• No
• We listed on pancakeswap allready
• Yes, https://dessertswap.finance/audits/Shiba%20Floki%20BEP-20%20Audit%208725475.pdf

**Comment by ShibaFloki** [comment]
Hello,

• We are best meme token on BSC and 2% gift tokens send all holders in 
every transaction and burn 2%
• Swap can be done via pancakeswap. We do not have an airdrop program.
• No
• We listed on pancakeswap allready
• Yes, 
https://dessertswap.finance/audits/Shiba%20Floki%20BEP-20%20Audit%208725475.pdf


2022-01-31 04:19, Nazar yazmış:

**Comment by cryptomanz** [comment]
can you please add tags and links?
see the requirements here : https://developer.trustwallet.com/assets/repository_details

**Comment by Cryptocool1** [comment]
Снимок экрана 2022-01-31 в 23 59 04
Hello, we are not allowed to copy names and logos.

**Comment by ShibaFloki** [comment]
> Снимок экрана 2022-01-31 в 23 59 04
> 
> Hello, we are not allowed to copy names and logos.

We are same project team, you can check our official mail and official github account. We just changed our smart contract and add new web urls.

**Pull request merged**
