### PR TITLE
New ICHI logo

### PR DESCRIPTION
**Pull request by DTal621**
This PR is being closed due to inactivity. If you wish to continue, please have us reopen the PR before sending your payment.
Do NOT send payments for closed PR, as the fee may by lost!
  (168 vs. 60 hrs)

### CODE REVIEW

**Comment by catenocrypt** [comment]
Fee payment is needed.
Two of the folders are not in checksum format, should be changed.

```
-  XXX 'Folder structure for chain ethereum (ethereum fork)':  2 errors
   XXX   'Expect asset at path /home/runner/work/assets/assets/blockchains/ethereum/assets/0xc88f47067db2e25851317a2fdae73a22c0777c37 in checksum: '0xC88F47067dB2E25851317A2FDaE73a22c0777c37''
   XXX   'Expect asset at path /home/runner/work/assets/assets/blockchains/ethereum/assets/0xec0d77a58528a218cbf41fa6e1585c8d7a085868 in checksum: '0xEc0d77a58528a218cBf41Fa6E1585c8D7A085868''
```

**Comment by DTal621** [comment]
@vikmeup could you please reopen this PR, I have made changes based on what is needed so would be great to get the automated tests running and make sure we can merge. Once ready we will send over the payment to make it happen.

**Comment by DTal621** [comment]
@vikmeup auto closed again? Do we have to send the payment within 30mins?

**Comment by vikmeup** [comment]
> @vikmeup auto closed again? Do we have to send the payment within 30mins?

If you send a payment - it should re-open automatically I believe

**Comment by DTal621** [comment]
It says if I send a payment while its closed it will likely be lost:
"If you wish to continue, please have us reopen the PR before sending your payment.
Do NOT send payments for closed PR, as the fee may by lost!"

**Comment by catenocrypt** [comment]
@DTal621 , if, after Reopen PR gets auto-closed again, you should still send the fee payment; it will be picked up automaticallty when we reopen next time.

**Comment by DTal621** [comment]
Thanks for reopening - money has been sent, here is the transaction. Please let me know that the funds have been recieved and it has been merged: https://explorer.binance.org/tx/530AE627D66E0E7798F9841727452F8DA6196C4EE64D1E4473936500DED7BED0

**Pull request merged**
