### PR TITLE
Covidtoken logo and info.json

### PR DESCRIPTION
**Pull request by Covidtokenafr**
i want to add Covidtoken logo and necessary information about covidtoken

### CODE REVIEW

**Comment by cryptomanz** [comment]
Hello,
- Contract is not in checksum format, should be 0x23C28E9346C82228FB2b62b20b6fe5d75989F5b2 (not 0x23c28e9346c82228fb2b62b20b6fe5d75989f5b2).

**Comment by Covidtokenafr** [comment]
hello @cryptomanz how can i edit ?

**Comment by Cryptocool1** [comment]
> hello @cryptomanz how can i edit ?

If you can't rename files in the PR, you may open a new PR. Make sure to mention this PR, so that we can see that fee has been paid already here.

**Comment by Cryptocool1** [comment]
go to https://assets.trustwallet.com, log on with Github, enter contract ID, logo and some additional info, and it will create a PR for you.
See https://community.trustwallet.com/t/how-to-submit-a-token-logo-using-assets-app/82957.

**Comment by Covidtokenafr** [comment]
https://github.com/trustwallet/assets/pull/10771

**Pull request closed without merging**
