### PR TITLE
Add TruBadger (BEP20)

### PR DESCRIPTION
**Pull request by trubadger**
Adding info for BEP20 token 'TruBadger'.

PR created by <a href="https://assets.trustwallet.com">TW Assets Management</a>

### CODE REVIEW

**Comment by trubadger** [comment]
Hi,

Check PR #11877

Fee Paid, error with logo fixed with new upload with TW assets app.

Thanks.

**Comment by cryptomanz** [comment]
11877

**Comment by cryptomanz** [comment]
#11543

**Comment by trubadger** [comment]
Thanks for merging @Cryptocool1 @cryptomanz

**Pull request merged**
