### PR TITLE
Add Vita Inu (BEP20)

### PR DESCRIPTION
**Pull request by ElemontCapital**
Adding info for BEP20 token 'Vita Inu'.

PR created by <a href="https://assets.trustwallet.com">TW Assets Management</a>

### CODE REVIEW

**Comment by ElemontCapital** [comment]
Audit: https://www.certik.com/projects/vita-inu
Our other chain (16,000 holders): https://vitescan.io/token/tti_541b25bd5e5db35166864096

**Comment by cryptomanz** [comment]
As per our policy, brand new tokens are not included, there is a minimum requirement of 10,000 holder addresses and 15,000 transactions, in order to filter out scam tokens.
See the criteria at : https://developer.trustwallet.com/assets/requirements .

**Comment by ElemontCapital** [comment]
> As per our policy, brand new tokens are not included, there is a minimum requirement of 10,000 holder addresses and 15,000 transactions, in order to filter out scam tokens. See the criteria at : https://developer.trustwallet.com/assets/requirements .

Hey, this is not a brand new token. We can give you any information you require.
See here for our holders on our native chain (16,000): https://vitescan.io/token/tti_541b25bd5e5db35166864096
We also have a Simplex partnership & Simplex is in contact with Trust Wallet to enable card payments for VINU on your platform.

**Comment by Cryptocool1** [comment]
Your audit is in progress. Please come back to us when all criteria are met. Make sure to mention this PR so the fee can be reused

**Comment by ElemontCapital** [comment]
Our Audit has now completed, and we have opened a new PR #20374  
Audit: https://www.certik.com/projects/vita-inu#audit

**Comment by ElemontCapital** [comment]
> Your audit is in progress. Please come back to us when all criteria are met. Make sure to mention this PR so the fee can be reused

Our Audit has now completed, and we have opened a new PR #20374  
Audit: https://www.certik.com/projects/vita-inu#audit

**Pull request closed without merging**
