### PR TITLE
Add Logo for PandaInu

### PR DESCRIPTION
**Pull request by PandaInu**
HI,
Please add the logo in Trust Wallet.

https://pancakeswap.finance/info/tokens/0xf3eDD4f14a018df4b6f02Bf1b2cF17A8120519A2

### CODE REVIEW

**Comment by cryptomanz** [comment]
Hello,
Can your answer some questions?
• What is the purpose of this token? How will it benefit Trust Wallet users?
• How is the token being distributed? Are you conducting an airdrop?
• Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?
• Is the token listed on a centralized/decentralized exchange?
• Is a Smart Contract audit completed? Where can we find this information?

**Comment by PandaInu** [comment]
> Hello,
> Can your answer some questions?
> • What is the purpose of this token? How will it benefit Trust Wallet users?
> • How is the token being distributed? Are you conducting an airdrop?
> • Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?
> • Is the token listed on a centralized/decentralized exchange?
> • Is a Smart Contract audit completed? Where can we find this information?

PandaInu (PWT) is a utility meme token that will be used to incentivize all PandaInu Meme token holders and their Wallet users. The goal of the PandaInu token team is to make meme cryptocurrencies more accessible by the worldwide community. By distributing PWT, it will help spread awareness and gives everyone a chance to own their very first crypto for the worldwide market.

Tokens are being distributed through airdrop and decentralized exchange Pancakeawap.

No, there were no ICO or token presales conducted.

Yes, the token is listed on Pancake swap. Here is the link https://pancakeswap.finance/info/tokens/0xf3eDD4f14a018df4b6f02Bf1b2cF17A8120519A2

No, This is just a simple BEP20 verified smart contract and does not need any audit.

**Comment by cryptomanz** [comment]
- Awaiting for smart contract audit.

**Comment by Cryptocool1** [comment]
Please create new PR when smart contract audit will be ready, make sure to mention this PR so the fee will be reused

**Pull request closed without merging**
