### PR TITLE
Add Matrix Chain (BEP20)

### PR DESCRIPTION
**Pull request by mtcv3**
Adding info for BEP20 token 'Matrix Chain'.

PR created by <a href="https://assets.trustwallet.com">TW Assets Management</a>

### CODE REVIEW

**Comment by cryptomanz1** [comment]
• What is the purpose of this token? How will it benefit Trust Wallet users?
 • How is the token being distributed? Are you conducting an airdrop?
 • Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?
 • Is the token listed on a centralized/decentralized exchange?
 • Is a Smart Contract audit completed? Where can we find this information?

**Comment by mtcv3** [comment]
• What is the purpose of this token? How will it benefit Trust Wallet users?
This is ultis token from Matrix Chain, When list on trust wallet help user avoid scam token.
• How is the token being distributed? Are you conducting an airdrop?
Token only release when user join DEFI protocol of Matrix Chain
• Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?
N/A: We not ICO, only can buy from DEX or Defi Protocol
• Is the token listed on a centralized/decentralized exchange?
Yes: DEX: https://www.dextools.io/app/en/bnb/pair-explorer/0x0082792bee5aea77c15c6af53fffee6125540376
Very active and heathy
• Is a Smart Contract audit completed? Where can we find this information?
We verified source code on BSCScan, using base token from Openzeppelin.

**Comment by Cryptocool1** [comment]
We require smart contract audit from reputable companies. 
here is an example of smart contract audit: https://skynet.certik.com/projects/trust-wallet

**Comment by Cryptocool1** [comment]
Feel free to create new Pull Request once audit is done. Make sure to mention this PR so the fee can be reused

**Pull request closed without merging**
