### PR TITLE
CateCoin Contract Migration .

### PR DESCRIPTION
**Pull request by catecoins**
How can we remove logo from last 2 contract and keep logo only in this

### CODE REVIEW

**Comment by catecoins** [comment]
How can we remove logo from both old contracts, user are confused between new and old contract
kindly help us by removing logo from first 2 contracts

**Comment by Cryptocool1** [comment]
Screen Shot 2021-07-04 at 2 09 40 AM

**Comment by Cryptocool1** [comment]
you need to add status "abandoned" for old token

**Comment by catecoins** [comment]
How can we add again , we need to create new pull request?

**Comment by catecoins** [comment]
we have changed  status in info file and created pull request in one contract  but that pull request is again asking to deposit TWT TOKENS
Cant we get this status updated along with new contract request.

(@zachzwei, @catenocrypt & @Iamdeadlyz: )

**Comment by catecoins** [comment]
This is our Final contract - 0xE4FAE3Faa8300810C835970b9187c268f55D998F
Last 2 contract funds is moved to the Final contract

**Comment by catecoins** [comment]
Kindly check pull request #11326 @Cryptocool1

**Comment by catecoins** [comment]
New Contract ( 0xE4FAE3Faa8300810C835970b9187c268f55D998F) Logo is updated ?
I am still confused about this because logo is not appearing 
Kindly confirm @Cryptocool1 @zachzwei, @catenocrypt & @Iamdeadlyz

**Comment by catecoins** [comment]
Waiting for update
Kindly process  @Cryptocool1 @zachzwei, @catenocrypt & @Iamdeadlyz

**Comment by catecoins** [comment]
New Contract ( 0xE4FAE3Faa8300810C835970b9187c268f55D998F) Logo is not yet updated ?
we have paid for this pull request alredy
Kindly confirm @Cryptocool1 @zachzwei, @catenocrypt & @Iamdeadlyz
user are very confused about this

**Comment by catecoins** [comment]
I think @Cryptocool1 asked for more information 
0xE4FAE3Faa8300810C835970b9187c268f55D998F is the only active and valid contract , we airdrop tokens of 1st 2 contract and shifted them to new contract ,

we did this because of the router issue in both contracts
kindly appove  tokne 0xE4FAE3Faa8300810C835970b9187c268f55D998F

**Comment by catecoins** [comment]
Community is very confused about 3 contracts and the real contract is not even reflecting in the search 
Kindly update  @Cryptocool1 @zachzwei, @catenocrypt & @Iamdeadlyz

New Contract is active and people are trading using that, which you can see in dextools

https://www.dextools.io/app/pancakeswap/pair-explorer/0x6c6636eada7cc046c7a83aea0d973810234ec291

You can also check your Twitter account  to confirm that contract

https://twitter.com/cateclub

0xE4FAE3Faa8300810C835970b9187c268f55D998F

**Comment by catecoins** [comment]
We already added more information and also changed all old contracts
 @Cryptocool1

**Review by catecoins — COMMENTED** [review]
We are waiting for final approval from your side
we have added all changes and infomation alredy

**Comment by catecoins** [comment]
@cryptomanz  @Cryptocool1 will u please look into our project, 
User are very confused in finding real contract , we have above 20k to 30k Trust wallet users and we are getting daily messages

**Comment by catecoins** [comment]
@Cryptocool1  will you please confirm that our new contract is active now and last 2 contracts is abandoned, 
i still don't see a new contract address in trustwallet github repo

**Comment by catecoins** [comment]
@Cryptocool1  people are still buying tokens from the old contract using truswallet because the abandoned token logo is visible to people and they are confused between the new and old contract.

we can't stop abandoned token trading completely because our LP is locked

**Pull request merged**
