### PR TITLE
AIR DANCE

### PR DESCRIPTION
**Pull request by talk2elvin**

### CODE REVIEW

**Comment by catenocrypt** [comment]
@talk2elvin , the first logo is too large, 260KB, while max. is 100KB.  I could not open it with tinypng.com, nor with Gimp-2.10 to compress it.  Please provide a more compact version.

**Comment by talk2elvin** [comment]
logo

**Comment by talk2elvin** [comment]
here is a new logo ive already compressed with tinypng. please merge. thank you

**Comment by catenocrypt** [comment]
To confirm: this is to update this:

image

Looks quite different.

**Comment by talk2elvin** [comment]
No this is a different upload all together. I'm trying to merge the logo for air dance with contract 0xdF1d11025F2A22b9DC01C7A100B4F6DdEBAc82A3 not decash please

**Comment by talk2elvin** [comment]
Admin please look into this for me

**Comment by talk2elvin** [comment]
Please let me know how we can fix this error the second logo is the right logo for this PR

**Pull request merged**
