### PR TITLE
Add Frog Inu (BEP20)

### PR DESCRIPTION
**Pull request by Bobbydevs**
Adding info for BEP20 token 'Frog Inu'.

PR created by <a href="https://assets.trustwallet.com">TW Assets Management</a>

### CODE REVIEW

**Comment by Bobbydevs** [comment]
Hi!
@Cryptocool1, @cryptomanz, @Iamdeadlyz!
Hope you are having a good day! Do I need to provide any other information?

**Comment by Cryptocool1** [comment]
• What is the purpose of this token? How will it benefit Trust Wallet users?
 • How is the token being distributed? Are you conducting an airdrop?
 • Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?
 • Is the token listed on a centralized/decentralized exchange?
 • Is a Smart Contract audit completed? Where can we find this information?

**Comment by Bobbydevs** [comment]
Hi @Cryptocool1 

Here are the answers for the information required.

• What is the purpose of this token? How will it benefit Trust Wallet users?
Frog Inu is the funniest frog on BSC! A community-focused, decentralized cryptocurrency with instant rewards for holders.
• How is the token being distributed? Are you conducting an airdrop?
No airdrops are being conducted. The token is distributed by demand and offer in Pancakeswap for now;
• Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?
Yes, we did a presale 
https://www.pinksale.finance/launchpad/0x9B0884313447868a113fF7C64BA3B15B6F6F6B26?chain=BSC
• Is the token listed on a centralized/decentralized exchange?
It is listed in Pancakeswap.

https://pancakeswap.finance/swap/0xE5c355c993dE69C06b5DD1A0c9a2c39b4Cde5511
• Is a Smart Contract audit completed? Where can we find this information?

YES.
https://github.com/freshcoins/Smart-Contract-Audits/blob/main/FrogInu_0xE5c355c993dE69C06b5DD1A0c9a2c39b4Cde5511.pdf

**Comment by Bobbydevs** [comment]
@cryptomanz Shall I introduce a new PR?

**Comment by Bobbydevs** [comment]
As I don't see any option to update the logo here.

**Comment by Cryptocool1** [comment]
Your holders seem to be artificial. We are not accept new tokens. Your first massive transactions was 11 days ago. Feel free to open new PR in the next month, we will consider.

**Pull request closed without merging**
