### PR TITLE
add euro logo

### PR DESCRIPTION
**Pull request by europacoinbsc**
add euro logo

### CODE REVIEW

**Comment by Cryptocool1** [comment]
hello,
• What is the purpose of this token? How will it benefit Trust Wallet users?
 • How is the token being distributed? Are you conducting an airdrop?
 • Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?
 • Is the token listed on a centralized/decentralized exchange?
 • Is a Smart Contract audit completed? Where can we find this information?

**Comment by europacoinbsc** [comment]
> hello,
> • What is the purpose of this token? How will it benefit Trust Wallet users?
By adding our logo etc. Trust Wallet users will avoid being scammed by other tokens that are pretending to be us,
we have more then 10,400 holders and counting.
> • How is the token being distributed? Are you conducting an airdrop?
 Name: Europa
Decimals: 18
Symbol: EURO
Total Supply:
1,000,000,000 EURO
Sale: 40%
Airdrop: 10%
Burn: 30%
Liquidity: 10%
Team: 10% 
> • Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?
 Yes we did have a presale on  August
> • Is the token listed on a centralized/decentralized exchange?
Pancakeswap
> • Is a Smart Contract audit completed? Where can we find this information?
 There has not been an 'official' audit on this contract, but you can find that we passed tokensniffer's automated tests here:
https://tokensniffer.com/token/0x5f16ba80a1f620055e35215028e90808c7cc365c

**Comment by Cryptocool1** [comment]
What is the purpose of this token?

**Comment by europacoinbsc** [comment]
> What is the purpose of this token?

Europa has 3 products as part of the Europa ecosystem, namely Vaults (yield optimizer), Europa (DEX Aggregator), and farmfolio. The yield optimizer implements the most optimal strategies at the lowest cost to maximize users' yields and Europa implements optimizations to route users swap trades so that users can find the best price and swap rates. Lastly, farmfolio is an intelligent portfolio manager and tracker which helps users manage their assets across various DeFi farming projects. The Europa token is the platform's native token with a max supply of 1,000,000,000.

**Comment by Cryptocool1** [comment]
can you please add links to your PR?
example: https://developer.trustwallet.com/add_new_asset/repository_details

**Comment by europacoinbsc** [comment]
> can you please add links to your PR?
> example: https://developer.trustwallet.com/add_new_asset/repository_details

I updated Links. Please check for me.
Thank you

**Comment by europacoinbsc** [comment]
"links": [
        {
            "name": "twitter",
            "url": "https://twitter.com/Europacoin2021"
        },
        {
            "name": "github",
            "url": "https://github.com/europacoinbsc/europa"
        },
        {
            "name": "telegram",
            "url": "https://t.me/Europabsc"
        }
    ]
}

**Pull request merged**
