### PR TITLE
Dogecoin 2.0 Logo

### PR DESCRIPTION
**Pull request by CharlieAKAN**

### CODE REVIEW

**Comment by cryptomanz** [comment]
Hello,
 • How will it benefit Trust Wallet users?
 • How is the token being distributed? Are you conducting an airdrop?
 • Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?
 • Is the token listed on a centralized/decentralized exchange?
 • Is a Smart Contract audit completed? Where can we find this information?

**Comment by CharlieAKAN** [comment]
> Hello, can you answer some questions?
>  • How will it benefit Trust Wallet users?
>  • How is the token being distributed? Are you conducting an airdrop?
>  • Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?
>  • Is the token listed on a centralized/decentralized exchange?
>  • Is a Smart Contract audit completed? Where can we find this information?

Hi there, yup! I can answer these questions.

1) Trust Wallet has already been helpful in many ways with building our Dogelink project. Dogelink will be our Defi hub for Doge and Doge2, Trust Wallet is helping test many feature like receiving rewards from playing a game.

2) Doge2 is being traded on PancakeSWAP. There was a small airdrop to gain interest in the token. After that most of the growth as been organic. So much so that we contact by 2 CEXs last month to be listed. 

3) No there was no ICO.

4) As stated in #2 we are on PancakeSWAP but we are also listed on LAToken and COINSBIT as of June. This has taken away a number of new investors from PancakeSWAP. https://latoken.com/exchange/DOGE2_USDT - https://coinsbit.io/trade_classic/DOGE2_USDT. We are currently being listed on CoinGecko and CoinMarketCap within the week.

4) At this time the audit is not complete. You can find our more about Dogecoin 2.0 on our website - https://dogecoin2.org/ - https://www.dogecoin2.org/press/

We are very much a grassroots token and not like many rugpulls out there. The TWT that was paid for our logo to be added to Trust Wallet was donated by the community which you can see in our Discord.gg/Doge2 ... We don't have a huge marketing budget which is why it has take over 2 months to apply for our logo to be added since deployment. 

We are a hard working, passionate community and team with a massive goal of trying to take a coin we love, Dogecoin and make it better with Dogecoin 2.0... Please consider approving our request. Thank you.

**Comment by cryptomanz** [comment]
token will be on hold
awaiting information about listing or smart contract audit

**Comment by CharlieAKAN** [comment]
> token will be on hold
> awaiting information about listing or smart contract audit

Hi there, when you say "listings" are you meaning the CoinGecko and CoinMarketCap? 

Because because we are listed on two exchanges now, LAToken and COINSBIT. 

Looking for clarification to give back to my team. As they have worked hard to get to this point and will be disappointed with this hold status. 

Thank you.

**Comment by Cryptocool1** [comment]
awaiting for smart contract audit and listing on cmc

**Comment by CharlieAKAN** [comment]
Quick update, we heard back from LAToken that our CG and CMC may take a bit longer than normal as CG and CMC have a large backlog.

Also the audit may take a bit longer as well because it's anywhere between $500 to $2000 which would have to be raised by the community. 

Take care.

**Comment by Cryptocool1** [comment]
Hello,
please create new PR when CMC listing will be ready.
make sure to mention this PR, so that we can see that fee has been paid already here.

**Comment by CharlieAKAN** [comment]
We just got our audit back from Dessert Finance... Is it possible to use that instead of CMC listing as that will take much longer. CMC told us our volume is too low to be listed at this time but we are working on that but we would really love for our logo to be added to Trust Wallet. 

If we can use our audit, I will create a new PR and get that rolling. Thank you.

**Comment by CharlieAKAN** [comment]
New PR has been made with our smart contract audit. 

https://github.com/trustwallet/assets/pull/11905

**Comment by CharlieAKAN** [comment]
Hi there... 

Our community is asking for a refund as we were unaware of your new CMC requirement and that money could be used else where right now. 

TokenPocket added our logo and pricing today to their wallet and many of our members are moving there. So we may return when the CMC is listed.

**Comment by CharlieAKAN** [comment]
I am going to have to insist that we receive a refund or removing the CMC requirement and merging our pull request as we have met the requirements for our logo to be added and our PR to be merged. 

Our community is not happy with how we are being igorned, please give us an answer quickly. 

Thank you.

**Comment by CharlieAKAN** [comment]
Hi... I would like to speak to someone who can resolve this issues. I don't enjoy being igorned and it's highly unprofessional. 

You moved the goal posts on us with the unlisted requirement of CMC which in turn should be a reason for a refund. This is getting ridiculous and someone needs to reply or added our info to Trust Wallet, otherwise Doge2 will movie forward on further actions. 

Thank you.

**Comment by CharlieAKAN** [comment]
Hi ,

We have contacted Viktor Radchenko to resolve this issue but we hope to get in contact with someone here. We are also preparing to file a complaint against Six Days LLC & DApps Platform, Inc. with the New York Bureau of Consumer Frauds and Protection.

Please respond quickly with either a refund or moving Dogecoin 2.0's information forward to be added to Trust Wallet.

Thank you.

**Comment by CharlieAKAN** [comment]
Hi there.

Our project was just added to CoinGecko and CoinMarketCap shouldn't be far behind. 

Will CG be good enough for our logo and info to be added to Trust Wallet? If so, I will create a new PR. 

https://www.coingecko.com/en/coins/dogecoin-2

Thank you.

**Comment by CharlieAKAN** [comment]
We would like to resolve this quickly and being added CoinGecko I believe should be enough to be added to your wallet. 

Thank you.

**Comment by CharlieAKAN** [comment]
Please let us know if CoinGecko will be good enough for us to move forward with getting Dogecoin 2.0 logo and valued added.

https://www.coingecko.com/en/coins/dogecoin-2

Thank you!

**Comment by Cryptocool1** [comment]
Can you please add links?
https://developer.trustwallet.com/add_new_asset/repository_details

**Comment by CharlieAKAN** [comment]
Is everything ok? Seems that there needed to be some changes to the info.json file but all checks are still failing.

I copied exactly what was don't the site... Please let me know if I have to do anything.
Thank you

**Comment by cryptomanz** [comment]
> Is everything ok? Seems that there needed to be some changes to the info.json file but all checks are still failing.
> 
> I copied exactly what was on the site... Please let me know if I have to do anything.
> Thank you

Fixed

**Comment by CharlieAKAN** [comment]
Thank you! 🙏🙏🙏🙏

**Pull request merged**
