### PR TITLE
We are adding bfic coin logo

### PR DESCRIPTION
**Pull request by bficoin**
We have all required norms.

### CODE REVIEW

**Comment by Cryptocool1** [comment]
Correction needed:
PR should include only 2 files:
• blockchains/smartchain/assets/0xF0a0913BA2b173c1fbCa1c1b2FCFC0E3678f66a9/logo.png.
• blockchains/smartchain/assets/0xF0a0913BA2b173c1fbCa1c1b2FCFC0E3678f66a9/logo.png.

**Comment by bficoin** [comment]
> blockchains/smartchain/assets/0xF0a0913BA2b173c1fbCa1c1b2FCFC0E3678f66a9/logo.png

**Comment by bficoin** [comment]
> File not allowed: blockchains/Bfic/0xF0a0913BA2b173c1fbCa1c1b2FCFC0E3678f66a9/info.json. Please revert it.
> File not allowed: blockchains/Bfic/0xF0a0913BA2b173c1fbCa1c1b2FCFC0E3678f66a9/logo.png. Please revert it.



> File not allowed: blockchains/Bfic/0xF0a0913BA2b173c1fbCa1c1b2FCFC0E3678f66a9/info.json. Please revert it.
> File not allowed: blockchains/Bfic/0xF0a0913BA2b173c1fbCa1c1b2FCFC0E3678f66a9/logo.png. Please revert it.

please recheck

**Review by bficoin — COMMENTED** [review]
Please Check 


https://github.com/trustwallet/assets/pull/7459/files

**Comment by Cryptocool1** [comment]
Correction needed:
This is a BEp20 token, correct folder is blockchains/smartchain/assets. Please correct.

**Comment by bficoin** [comment]
> Please check

**Comment by bficoin** [comment]
hello  please check

**Pull request closed without merging**
