### PR TITLE
adding NYF 

### PR DESCRIPTION
**Pull request by yolkfinance**

### CODE REVIEW

**Comment by yolkfinance** [comment]
Hello, This is the only token that I'm requesting for update.

logo

**Comment by yolkfinance** [comment]
Token Name: New Yolk Finance
Ticker: NYF
Smartcontract: https://etherscan.io/address/0x57D37815D2fFBFB922195794b40662020B74817C

**Comment by yolkfinance** [comment]
Any update here?

**Comment by Iamdeadlyz** [comment]
> Any update here?

As per our policy, brand new tokens are not included. There is a minimum requirement of 500 holder addresses and 1000 transactions in order to filter out scam tokens. See the criteria at (mentioned in the first message by the bot): https://community.trustwallet.com/t/how-to-submit-a-token-logo/3863#how-to-get-approved

This token has below-limit usage yet. This pull request will be but on hold. Please come back to us when all criteria are met.
https://etherscan.io/token/0x57D37815D2fFBFB922195794b40662020B74817C (2, 12)

**Pull request closed without merging**
