### PR TITLE
Add PlotX Info and Logo

### PR DESCRIPTION
**Pull request by ankit5902**
This PR is being closed due to inactivity. If you wish to continue, please have us reopen the PR before sending your payment.
Do NOT send payments for closed PR, as the fee may by lost!
  (69 vs. 60 hrs)

### CODE REVIEW

**Comment by catenocrypt** [comment]
Please add an `info.json` file next to the `logo.png`, with info about the project, of the form:

```json
{
    "name": "Trust Wallet Token",
    "website": "https://trustwallet.com",
    "short_description": "Utility token to increase adoption of cryptocurrency.",
    "explorer": "https://etherscan.io/token/0xA866F0198208Eb07c83081d5136BE7f775c2399e",
    "socials": [
        {
            "name": "Twitter",
            "url": "https://twitter.com/trustwalletapp",
            "handle": "TrustWalletApp"
        },
        {
            "name": "Reddit",
            "url": "https://reddit.com/r/trustapp",
            "handle": "TrustApp"
        }
    ]
}
```

**Comment by ankit5902** [comment]
@catenocrypt Okay, I'll add the info.json file too in the given format.

**Review by ankit5902 — COMMENTED** [review]
Add Information and Logo for the token PLOT

**Comment by catenocrypt** [comment]
Submission looks OK

**Comment by ankit5902** [comment]
> Submission looks OK

Yes. But the PR is getting closed. Can you please help out.

**Comment by ankit5902** [comment]
@catenocrypt Yes. But the PR is getting closed. Can you please help out. I am ready with payment.

**Comment by catenocrypt** [comment]
Don't worry about the closing.  Just make the fee payment, in case PR is closed, it will be picked up when we reopen (non-paid PRs older than few days old are closed automatically, sorry).

**Comment by ankit5902** [comment]
> Don't worry about the closing. Just make the fee payment, in case PR is closed, it will be picked up when we reopen (non-paid PRs older than few days old are closed automatically, sorry).

Thank you! I have made the payment..😊

**Comment by ankit5902** [comment]
@catenocrypt The logo isn't visible on white background. Can we have the other logo added instead please?

**Comment by catenocrypt** [comment]
Please create a new PR with the updated logo.  Maybe do a contour around the white letter, or change its color.

**Comment by ankit5902** [comment]
> Please create a new PR with the updated logo. Maybe do a contour around the white letter, or change its color.

Okay. I’ll create a new PR. Also will I have to pay again?

**Comment by ankit5902** [comment]
> Please create a new PR with the updated logo. Maybe do a contour around the white letter, or change its color.

Here is the link to the new PR : https://github.com/trustwallet/assets/pull/4933

**Pull request merged**
