### PR TITLE
Add Hop (HOP) (ERC20)

### PR DESCRIPTION
**Pull request by shanefontaine**
Adding info for ERC20 token 'Hop (HOP)'.

PR created by <a href="https://assets.trustwallet.com">TW Assets Management</a>

### CODE REVIEW

**Comment by Athayde3586** [comment]
I have not received anything so what's going on

**Comment by Cryptocool1** [comment]
• What is the purpose of this token? How will it benefit Trust Wallet users?
 • How is the token being distributed? Are you conducting an airdrop?
 • Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?
 • Is the token listed on a centralized/decentralized exchange?
 • Is a Smart Contract audit completed? Where can we find this information?

**Comment by Athayde3586** [comment]
I did not sell anything

**Comment by litodertechie** [comment]
h

**Comment by shanefontaine** [comment]
* What is the purpose of this token? How will it benefit Trust Wallet users?

  * Hop is the governance token of Hop Protocol, the leading bridge in the Ethereum multichain space.
Having the token on the Trustwallet tokenlist will benefit Trustwallet users by improving the UX, allowing them to see their HOP tokens displayed in the wallet. There are over 12,000 HOP token holders.

* How is the token being distributed? Are you conducting an airdrop?

  * The token was distributed as an airdrop a few weeks ago (see [announcement](https://hop.mirror.xyz/AI5fOUR0X_l0mktShDOx3mwr-hsB24gp8GvTWtS-MBc)). 8% of the token supply went to early supporters.

* Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?

  * There was no public token sale or ICO.

* Is the token listed on a centralized/decentralized exchange?

  * All market and exchange information can be found [here](https://www.coingecko.com/en/coins/hop-protocol#markets) on CoinGecko.

* Is a Smart Contract audit completed? Where can we find this information?

  * Hop Protocol has had 2 audits: https://help.hop.exchange/hc/en-us/articles/4405172444429-How-safe-is-Hop-

**Comment by Cryptocool1** [comment]
how did you get almost 16.000 holders within 2 weeks?

**Pull request merged**
