### PR TITLE
Add X Doge (BEP20)

### PR DESCRIPTION
**Pull request by xdogeapp**
Adding info for BEP20 token 'X Doge'.

PR created by <a href="https://assets.trustwallet.com">TW Assets Management</a>

### CODE REVIEW

**Comment by xdogeapp** [comment]
An audit was done with Solid Proof:

https://raw.githubusercontent.com/solidproof/projects/main/X%20Doge/SmartContract_Audit_Solidproof_X_DOGE.pdf

We did not renounced ownership because we keep the "whitelist address" function for future listing at cex whitelist of their addresses.

**Comment by xdogeapp** [comment]
No ICO, Presale or Airdrop was done.
Distribution was done on PancakeSwap.
We are currently only distributed on PancakeSwap.

**Comment by xdogeapp** [comment]
Most of our users use TrustWallet, we believe a TrustWallet listing will provide information on our price, website, information and details.

Thanks!

**Comment by xdogeapp** [comment]
• What is the purpose of this token? How will it benefit Trust Wallet users?
X Doge is the next evolutionary Decentralized Finance cryptocurrency that strives to provide wide ranging DeFi services from premier charting solutions, leading NFT platform, Web3 API services. Most of our users use TrustWallet, we believe a TrustWallet listing will provide information on our price, website, information and details.

• How is the token being distributed? Are you conducting an airdrop?
The token is distributed at PancakeSwap. We are not conducting an airdrop.

• Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?
No ICO or presale.

• Is the token listed on a centralized/decentralized exchange?
X Doge is listed on PancakeSwap.

• Is a Smart Contract audit completed? Where can we find this information?
We did our smart contract audit with SolidProof. You may view it at 
https://raw.githubusercontent.com/solidproof/projects/main/X%20Doge/SmartContract_Audit_Solidproof_X_DOGE.pdf

**Comment by Cryptocool1** [comment]
How did you get 37.000 holders in less than a month?

**Comment by web2inu** [comment]
> How did you get 37.000 holders in less than a month?

We got support from Wechat communities from our ex-partner of BABYDOGE ETH and Crypto Inu to help promote our token.

**Comment by xdogeapp** [comment]
> How did you get 37.000 holders in less than a month?

Hi Cryptocool1, we got support promoting from our partners from Crypto Inu, BabyDoge ETH and partners from Wechat to help promote X Doge on platform such as Telegram and Wechat. 

Our aim is to create a charting solution and we had acquired TradingView hosted library permission to their github and currently using NodeReal, BitQuery and PancakeSwap feed to draw charts. However there is some issues with the search token api that result return did not check for if token is active for the last 20,000 blocks (each block assume is 3 second)

We are fixing it up, so our DeFi Charting (BNB Chain - for start) can be accurate and useful to the Crypto Communities.

**Pull request merged**
