### PR TITLE
Add logo and info.json for WKD (Wakanda Inu Token)

### PR DESCRIPTION
**Pull request by zuriwakanda**

### CODE REVIEW

**Comment by ramsty** [comment]
Hi!
Could you answer some questions?
• What is the purpose of this token? How will it benefit Trust Wallet users?
• How is the token being distributed? Are you conducting an airdrop?
• Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?
• Is the token listed on a centralized/decentralized exchange?
• Is a Smart Contract audit completed? Where can we find this information?

**Comment by zuriwakanda** [comment]
1. It's African first meme coin and it will help trust wallet users and over 12k holders of WKD identify the real WKD.

2. No airdrop. It's currently trading on pancakeswap.com with over 12k holders and 8m volumes.

3. Token public sale on PinkSale

4. Dex, pancakeswap.com and Apeswap 

5. Auditing is currently done by Certik, our invoice can be sent for further clarification if you wish

**Comment by ramsty** [comment]
Awaiting for smart contract audit. On hold for now.

**Comment by Cryptocool1** [comment]
Please come back to us when all criteria are met.
When creating a new PR make sure to mention this PR, so that we can see that fee has been paid already here.

**Pull request closed without merging**
