### PR TITLE
ff

### PR DESCRIPTION
**Pull request by Novicenewcomer**

### CODE REVIEW

**Comment by zachzwei** [comment]
Please resize the image and provide more details about this project.
https://community.trustwallet.com/t/how-to-submit-a-token-logo/3863#how-to-get-approved

You can follow this format when adding an info.json file:

```
 {
   "name":"Bitcoin",
   "website":"https://bitcoin.org",
   "source_code":"https://github.com/bitcoin",
   "white_paper":"https://bitcoin.org/bitcoin.pdf",
   "short_description":"Bitcoin is a cryptocurrency and worldwide payment system.",
   "explorer":"https://blockchain.info",
   "research":"https://research.binance.com/en/projects/bitcoin"
}

**Comment by Novicenewcomer** [comment]
There was an error in the last logo file submission, and it has been resubmitted for correction

**Comment by catenocrypt** [comment]
Corrections are fine, thanks.  Unfortunately token minimum usage is not met.
As per our policy, brand new tokens are not included, there is a minimum requirement of 500 holder addresses and 1000 transactions (in order to filter out scam tokens).
See the criteria at (mentioned in the first message by the bot): https://community.trustwallet.com/t/how-to-submit-a-token-logo/3863#how-to-get-approved
This token has below-limit usage yet (117). Putting PR on hold. Please come back to us when all criteria are met.

https://etherscan.io/token/0xab0bd01101877597C1360a82f515515FEb178B9E

**Comment by Novicenewcomer** [comment]
@catenocrypt We submitted the Logo update application (3854) on September 8th. The last reply was: https://github.com/trustwallet/assets/pull/3854, which requires 100 holder addresses and 500 transactions, After recent efforts of our community, we submitted a new application (4053) after meeting this update condition. So today we saw that the Logo update condition changed again and we were a little confused.

Since FF (ERC20) is a new token issued by the CryptoTree project on Ethereum, the holder address and transaction volume are relatively small. Our project, CryptoTree, submitted FF (TRC20) on TrustWallet 10 months ago. The contract address is:
https://tronscan.io/#/token20/TYxoK7DAvfze7ByWA7LYnzcoLxdKQpjrD1 (#741).

FF (TRC20) currently has more than 5,000 holding addresses and more than 2 million transactions, and the project has already started operation on September 7, 2019.
We fully understand and support TrustWallet's review of tokens to prevent fraudulent tokens from entering circulation, but please also give me some understanding and support from the real operation project parties.

**Comment by catenocrypt** [comment]
Thanks for the detailed background.  Indeed, the limit first was 100, then raised to 500.  Merging now.

**Pull request merged**
