### PR TITLE
Add Snake (BEP20)

### PR DESCRIPTION
**Pull request by bnb425**
Adding info for BEP20 token 'Snake'.

PR created by <a href="https://assets.trustwallet.com">TW Assets Management</a>

### CODE REVIEW

**Comment by bnb425** [comment]
> • What is the purpose of this token? How will it benefit Trust Wallet users? • How is the token being distributed? Are you conducting an airdrop? • Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale? • Is the token listed on a centralized/decentralized exchange? • Is a Smart Contract audit completed? Where can we find this information?

1. What is the purpose of this token? How will it benefit Trust Wallet users? 
Ans: The SNK token is designed to facilitate seamless transactions within the Snake Ecosystem, providing holders with exclusive benefits such as access to special in-game features, staking rewards, and governance rights. For Trust Wallet users, the integration of SNK will allow for easy access to these features and will enable them to participate in the growth of the ecosystem by holding or using SNK tokens.


2. How is the token being distributed? Are you conducting an airdrop? 
Ans: The SNK token distribution is ongoing through a combination of liquidity pools and community-focused events. While no airdrop is planned at this moment, we are looking into potential community rewards and staking incentives to further engage our user base and provide additional utility for holders.


3. Did you sell the tokens at an Initial Coin Offering (ICO) or a token presale?
Ans: No, we did not conduct an ICO or presale for SNK tokens. Instead, we raised funds by listing the token directly on decentralized exchanges and using social media advertising to attract investment and build community engagement.


4. Is the token listed on a centralized/decentralized exchange? 
Ans: Currently, SNK is listed on decentralized exchanges such as Uniswap, providing users the ability to trade and provide liquidity. We are actively working on expanding our exchange listings to ensure wider accessibility and liquidity for token holders.


5. Is a Smart Contract audit completed? Where can we find this information? 
Ans: At this time, a formal smart contract audit for the SNK token has not been completed. However, we are in the process of initiating an audit with a reputable third-party firm to ensure the security and reliability of our smart contracts. Once completed, the audit report will be published on our website and made available for public viewing. We expect this to be finalized in the near future.

**Comment by Cryptocool1** [comment]
After careful review of your submission, it looks like this token has not undergone any security audit. The request will be closed until further notice.
To know more about the token approva l guidelines, please check this article: [How to Submit Token Logo l (http s://developer.trustwallet.com/listing-new-assets/requirements).
Feel free to re-open pull request once you meet those requirements.

**Comment by bnb425** [comment]
> After careful review of your submission, it looks like this token has not undergone any security audit. The request will be closed until further notice. To know more about the token approva l guidelines, please check this article: [How to Submit Token Logo l (http s://developer.trustwallet.com/listing-new-assets/requirements). Feel free to re-open pull request once you meet those requirements.

and what exactly is wrong?
you didn't write any counter-evidence what exactly is wrong with the token?

**Comment by Cryptocool1** [comment]
We require smart contract audit from reputable companies, please take a look at our documentation we sent you above

**Comment by bnb425** [comment]
if we pass the audit in this company https://www.cyberscope.io/ will you be able to place our logo on trust wallet?

**Comment by bnb425** [comment]
> We require smart contract audit from reputable companies, please take a look at our documentation we sent you above

if we pass the audit in this company https://www.cyberscope.io/ will you be able to place our logo on trust wallet?

**Comment by bnb425** [comment]
> > > We require smart contract audit from reputable companies, please take a look at our documentation we sent you above
> > 
> > 
> > if we pass the audit in this company https://www.cyberscope.io/ will you be able to place our logo on trust wallet?
> 
> Hello, yes, please let us know once audit is done

Yes, okay, thank you very much, I'll take care of this issue now.

and besides the audit, will there be any other requirements?
or if there is an audit, will they place us on the trust wallet

**Comment by bnb425** [comment]
> > > We require smart contract audit from reputable companies, please take a look at our documentation we sent you above
> > 
> > 
> > if we pass the audit in this company https://www.cyberscope.io/ will you be able to place our logo on trust wallet?
> 
> Hello, yes, please let us know once audit is done

I also wanted to clarify whether a re-payment is required for listing?

**Comment by bnb425** [comment]
> > > We require smart contract audit from reputable companies, please take a look at our documentation we sent you above
> > 
> > 
> > if we pass the audit in this company https://www.cyberscope.io/ will you be able to place our logo on trust wallet?
> 
> Hello, yes, please let us know once audit is done

are you here?

**Comment by bnb425** [comment]
> > > We require smart contract audit from reputable companies, please take a look at our documentation we sent you above
> > 
> > 
> > if we pass the audit in this company https://www.cyberscope.io/ will you be able to place our logo on trust wallet?
> 
> Hello, yes, please let us know once audit is done

are you here?
why don't you answer me?

**Comment by bnb425** [comment]
> > > We require smart contract audit from reputable companies, please take a look at our documentation we sent you above
> > 
> > 
> > if we pass the audit in this company https://www.cyberscope.io/ will you be able to place our logo on trust wallet?
> 
> Hello, yes, please let us know once audit is done


AUDIT ready 


https://www.cyberscope.io/audits/2-snk

**Comment by bnb425** [comment]
please consider my application again

**Comment by bnb425** [comment]
> > > We require smart contract audit from reputable companies, please take a look at our documentation we sent you above
> > 
> > 
> > if we pass the audit in this company https://www.cyberscope.io/ will you be able to place our logo on trust wallet?
> 
> Hello, yes, please let us know once audit is done


I created a new application

https://github.com/trustwallet/assets/pull/29817

**Pull request closed without merging**
