### PR TITLE
Add SHIBA RISE (BEP20)

### PR DESCRIPTION
**Pull request by ShibaRise**
Adding info for BEP20 token 'SHIBA RISE'.

PR created by <a href="https://assets.trustwallet.com">TW Assets Management</a>

### CODE REVIEW

**Comment by cryptomanz** [comment]
- As per our policy, brand new tokens are not included, there is a minimum requirement of 5000 holder addresses and 10000 transactions, in order to filter out scam tokens.
See the criteria at (mentioned in the first message by the bot): https://community.trustwallet.com/t/how-to-submit-a-token-logo/3863).
Closing PR for now. Please come back to us when all criteria are met.

**Comment by ShibaRise** [comment]
Hey. Every where I read it mentioned 2,500 holders and 5,000 transactions? Where is it posted that it is 5,000 holders and 10000 transactions? We have been around for about a month and are listed on CMC

**Comment by Cryptocool1** [comment]
https://community.trustwallet.com/t/how-to-submit-a-token-logo/3863

**Comment by ShibaRise** [comment]
When was this updated?

**Comment by ShibaRise** [comment]
Hello? I am generally wondering when that information was updated.. Last I checked it was 2,500 holders and 5,000 transactions. I understand you need to have measures due to scam tokens. But our project is not a scam. check out the website, hop in the telegram. Come talk with us or me.

**Comment by Cryptocool1** [comment]
As @cryptomanz mentioned:
As per our policy, brand new tokens are not included, there is a minimum requirement of 5000 holder addresses and 10000 transactions, in order to filter out scam tokens.
See the criteria at (mentioned in the first message by the bot): https://community.trustwallet.com/t/how-to-submit-a-token-logo/3863).

**Comment by ShibaRise** [comment]
Will the TWT tokens I sent be used for the next one or no?

**Comment by ShibaRise** [comment]
because I dont want a refund. Our community deserves the ease of having the information and logo automatically added when they purchase from coinmarketcap or pancakeswap. Thank you for your time. I honestly remember seeing it say 2,500 and 5,000. I am not wrong on this being the recent standard am I?

**Pull request closed without merging**
