### PR TITLE
Add Kiba Inu (KIBA) (BEP20)

### PR DESCRIPTION
**Pull request by DrewDufresne**
Adding info for BEP20 token 'Kiba Inu (KIBA)'.

PR created by <a href="https://assets.trustwallet.com">TW Assets Management</a>

### CODE REVIEW

**Comment by Cryptocool1** [comment]
• What is the purpose of this token? How will it benefit Trust Wallet users?
 • How is the token being distributed? Are you conducting an airdrop?
 • Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?
 • Is the token listed on a centralized/decentralized exchange?
 • Is a Smart Contract audit completed? Where can we find this information?

**Comment by majgic** [comment]
• What is the purpose of this token? How will it benefit Trust Wallet users?
This is a meme token in spirit and for marketing purposes but a defi token with our own feature rich swap in existence currently at in existence at https://kiba.app/ but more importantly for trust wallet users this token is the v2 or migrated token from
Asset ID: | c20000714_t0x31d3778A7Ac0d98c4aAA347D8b6EaF7977448341. Currently TrustWallet users are being confused because the old contract has the logo but the new one does not. This has created quite a few situations where users are easily scammed by nefarious individuals offering to help remedy the situation for them. Also if we could remove the old tokens from the trust wallet assets this would help your users tremendously when using your search feature. 

• How is the token being distributed? Are you conducting an airdrop? The token is available on pancake swap and 10 centralized exchanges. 

• Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale? This was a migrated contract.

• Is the token listed on a centralized/decentralized exchange? Yes, 
Pancakeswap,
lbank,
gate.io,
mexc,
bkex,
hotbit,
bitfinex,
digifinex, 
bitrue,
bitmart.

• Is a Smart Contract audit completed? Where can we find this information?
v1 audited by certik, v2 certik audit in progress.

**Comment by majgic** [comment]
> • What is the purpose of this token? How will it benefit Trust Wallet users? • How is the token being distributed? Are you conducting an airdrop? • Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale? • Is the token listed on a centralized/decentralized exchange? • Is a Smart Contract audit completed? Where can we find this information?

• What is the purpose of this token? How will it benefit Trust Wallet users?
This is a meme token in spirit and for marketing purposes but a defi token with our own feature rich swap in existence currently at in existence at https://kiba.app/ but more importantly for trust wallet users this token is the v2 or migrated token from
Asset ID: | c20000714_t0x31d3778A7Ac0d98c4aAA347D8b6EaF7977448341. Currently TrustWallet users are being confused because the old contract has the logo but the new one does not. This has created quite a few situations where users are easily scammed by nefarious individuals offering to help remedy the situation for them. Also if we could remove the old tokens from the trust wallet assets this would help your users tremendously when using your search feature. 

• How is the token being distributed? Are you conducting an airdrop? The token is available on pancake swap and 10 centralized exchanges. 

• Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale? This was a migrated contract.

• Is the token listed on a centralized/decentralized exchange? Yes, 
Pancakeswap,
lbank,
gate.io,
mexc,
bkex,
hotbit,
bitfinex,
digifinex, 
bitrue,
bitmart.

• Is a Smart Contract audit completed? Where can we find this information?
v1 audited by certik, v2 certik audit in progress.

**Comment by cryptomanz** [comment]
can you send an official announcement about migration ?

**Comment by majgic** [comment]
> announcement

Yes, official messages have been sent and are shown where we currently could add them. 

image

Where else would you like an official announcement posted?

We announced on twitter, tg, website, cg, YouTube etc. Please advise where else to add. Thank you.

**Comment by cryptomanz** [comment]
#20776

**Comment by majgic** [comment]
> #20776

20776 updated eth token json but it looks like you closed the bsc one without merging.

**Comment by Cryptocool1** [comment]
What’s your new contract for bsc?

**Comment by majgic** [comment]
> What’s your new contract for bsc?

https://bscscan.com/address/0xC3afDe95B6Eb9ba8553cDAea6645D45fB3a7FAF5 

0xC3afDe95B6Eb9ba8553cDAea6645D45fB3a7FAF5

It is accurate in this request.

**Comment by cryptomanz** [comment]
What is your old contract for BEP20?

**Comment by majgic** [comment]
> What is your old contract for BEP20?

0x31d3778a7ac0d98c4aaa347d8b6eaf7977448341

**Comment by cryptomanz** [comment]
#20777

**Pull request merged**
