### PR TITLE
Add FxBox (BEP20)

### PR DESCRIPTION
**Pull request by finexpo**
Adding info for BEP20 token 'FxBox'.

PR created by <a href="https://assets.trustwallet.com">TW Assets Management</a>

### CODE REVIEW

**Comment by bani68** [comment]
در تاریخ چهارشنبه ۲۱ فوریه ۲۰۲۴، ۰۹:۳۹ merge-fee-bot[bot] <
***@***.***> نوشت:

**Comment by Cryptocool1** [comment]
• What is the purpose of this token? How will it benefit Trust Wallet users?
 • How is the token being distributed? Are you conducting an airdrop?
 • Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?
 • Is the token listed on a centralized/decentralized exchange?
 • Is a Smart Contract audit completed? Where can we find this information?

**Comment by finexpo** [comment]
> • What is the purpose of this token? How will it benefit Trust Wallet users? • How is the token being distributed? Are you conducting an airdrop? • Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale? • Is the token listed on a centralized/decentralized exchange? • Is a Smart Contract audit completed? Where can we find this information?

1. is a utility token and is used throughout the project ecosystem. For creating liquidity pools, for summoning NFTs, trading and in all games of the project. Our system connects to TrastWallet and users can make transactions directly from the mobile wallet.
2. Community	90% - 77,400,000,000	Based on Mining Pool (18,000,000 mining evrey day)
For strategic partners, launchpad, liquidity pools, airdrops, bounty + 4%  and FxBox Fund, to Lottery injections, for Forex and Oracle trading rewards = 6% Total 86,000,000,000
more info: https://fxbox.io/tokenomics/
3. No
4. Yes, https://www.coinstore.com/#/spot/FXBUSDT and https://www.bitforex.com/en/spot/fxb_usdt 
and there will be more soon
5. Yes, https://app.solidproof.io/projects/fxbox ( news https://twitter.com/FxBox_Official/status/1721898138146140663)

**Comment by finexpo** [comment]
Anything else you need from us? Also, please added our coinmarketcap
https://coinmarketcap.com/currencies/fxbox/

**Pull request merged**
