### PR TITLE
Add Mythos (MYTH) (ERC20)

### PR DESCRIPTION
**Pull request by cthacker**
Adding info for ERC20 token 'Mythos (MYTH)'.

PR created by <a href="https://assets.trustwallet.com">TW Assets Management</a>

### CODE REVIEW

**Comment by Cryptocool1** [comment]
As per our policy, brand new tokens are not included, there is a minimum requirement of 10,000 holder addresses and 15,000 transactions, in order to filter out scam tokens.
See the criteria at : https://developer.trustwallet.com/assets/requirements .

**Comment by cthacker** [comment]
Hi @Cryptocool1 while the MYTHOS token is new, this is definitely not a scam project. [mythos.foundation](https://mythos.foundation/) is the project and it has been listed on Uphold as well as Uniswap and can be found on coingecko and coinmarketcap. I saw that the only way to get the logo to show on uniswap is to get it accepted into trustwallet. Are there other considerations besides the #holder metric?

**Comment by Cryptocool1** [comment]
Unfortunately no, you should meet our holders requirement.  You should also have audit from reputable companies

**Comment by cthacker** [comment]
MYTHOS has an audit from quantstamp as well as many legitimate partners in  gaming, esports, and web3. 

https://www.businesswire.com/news/home/20220930005643/en/Mythos-Foundation-Mythos-DAO-and-Mythos-Token-MYTH-Launch-to-Democratize-Web3-Gaming

**Pull request closed without merging**
