### PR TITLE
Add ZwZ logo and info

### PR DESCRIPTION
**Pull request by zombieworldz**
submit info to trust wallet

### CODE REVIEW

**Review by Arnu1986 — APPROVED** [review]

**Review by Arnu1986 — APPROVED** [review]

**Review by Arnu1986 — APPROVED** [review]

**Review by Arnu1986 — APPROVED** [review]

**Comment by cryptomanz** [comment]
can you send an official announcement about migration SHEEP token?

**Comment by Cryptocool1** [comment]
please come back to us when you will be ready to answer our questions. make sure to mention this PR so the fee can be reused

**Comment by zombieworldz** [comment]
> Status: More Info / Change Requested

> please come back to us when you will be ready to answer our questions. make sure to mention this PR so the fee can be reused

Hello,
What do you mean?I dont understand my token is ZwZ.And now it still not appear on trust wallet,can you help to check

**Comment by zombieworldz** [comment]
> can you send an official announcement about migration SHEEP token?

Sorry!I dont understand your question.My token is ZwZ.What do you you main SHEEP token?

**Comment by zombieworldz** [comment]
@cryptomanz @Cryptocool1 @Iamdeadlyz hi there can you support my case? thanks

**Pull request closed without merging**
