### PR TITLE
Add ASPO World (BEP20)

### PR DESCRIPTION
**Pull request by yenthanh132**
Adding info for BEP20 token 'ASPO World'.

PR created by <a href="https://assets.trustwallet.com">TW Assets Management</a>

### CODE REVIEW

**Comment by yenthanh132** [comment]
We have paid the fee from previous PR: https://github.com/trustwallet/assets/pull/15738/

**Comment by yenthanh132** [comment]
Our smart contract is audited by Hacken:
[[ASPO_25112021]SCAudit_Report.pdf](https://github.com/trustwallet/assets/files/7602089/ASPO_25112021.SCAudit_Report.pdf)

**Comment by cryptomanz** [comment]
As per our policy, brand new tokens are not included, there is a minimum requirement of 25,000 holder addresses and 50,000 transactions, in order to filter out scam tokens.
See the criteria at : https://developer.trustwallet.com/assets/requirements .

**Comment by yenthanh132** [comment]
Hi @cryptomanz, as the time we make the PR https://github.com/trustwallet/assets/pull/15738 , TrustWallet has not published the new policy of 25,000 holders and 50,000 transactions but still using the policy of 5,000 holders and 50,000 transactions. So I think for our case we should be considered under that condition as Trust Wallet publish the new policy after we make the payment and have no notice for us before releasing the new policy.

**Pull request closed without merging**
