### PR TITLE
Add Pocket Doge $PDOGE (BEP-20)

### PR DESCRIPTION
**Pull request by ThisisNFA**
Assets for logo for $PDOGE

### CODE REVIEW

**Comment by Cryptocool1** [comment]
As per our policy, brand new tokens are not included, there is a minimum requirement of 5000 holder addresses and 10000 transactions, in order to filter out scam tokens.
See the criteria at : https://community.trustwallet.com/t/how-to-submit-a-token-logo/3863).

**Comment by ThisisNFA** [comment]
> As per our policy, brand new tokens are not included, there is a minimum requirement of 5000 holder addresses and 10000 transactions, in order to filter out scam tokens.
> See the criteria at : https://community.trustwallet.com/t/how-to-submit-a-token-logo/3863).

Sorry. I had believed that was not a stringent criteria but more of a project to project basis. As you can see, our team is fully KYC'd and our project is audited. Promise we are not a fly by night token. Just trying to get our awesome logo on. What can I do to help make this happen? Thank you for everything!

**Comment by ThisisNFA** [comment]
Just wanted to follow up here to see if there's anything additional I need to/can do to get the logo set up. I believe that we've been approved on the Chinese version. Really appreciate any and all help you can provide. Thanks!

**Comment by Cryptocool1** [comment]
Please create new PR when all criteria are met. make sure to mention this PR, so the fee can be reused.

**Pull request closed without merging**
