### PR TITLE
Add Fuse Token (BEP20)

### PR DESCRIPTION
**Pull request by leonprou**
Adding info for BEP20 token 'Fuse Token'.

PR created by <a href="https://assets.trustwallet.com">TW Assets Management</a>

### CODE REVIEW

**Comment by cryptomanz** [comment]
As per our policy, brand new tokens are not included, there is a minimum requirement of 5000 holder addresses and 10000 transactions, in order to filter out scam tokens.
See the criteria at (mentioned in the first message by the bot): https://community.trustwallet.com/t/how-to-submit-a-token-logo/3863).
Closing PR for now. Please come back to us when all criteria are met.

**Comment by leonprou** [comment]
Hey @cryptomanz 
The Fuse Network is running since 2019.
We've got 2K+ holders on BSC (no airdrops, all genuine users)
Nearly 2K holders on Ethereum
and 500K wallets on Fuse Network.

Some token holders already use Trust Wallet and want to see the token there..

**Comment by Marksmargon** [comment]
@cryptomanz We are just trying to update our logo for months! We already have 1M$+ daily volume on BSC and more than 30K transfers. Can't understand why is it impossible to update our logo like we have here:
https://bscscan.com/token/0x5857c96dae9cf8511b08cb07f85753c472d36ea3

**Comment by Marksmargon** [comment]
Hello Cryptomanz, our token is not brand new and we only want to update the logo - can we please submit this pr?

**Comment by leonprou** [comment]
Hey @cryptomanz,
We have have 5K holders now on BSC. Can you review please?
https://bscscan.com/token/0x5857c96dae9cf8511b08cb07f85753c472d36ea3

**Pull request closed without merging**
