### PR TITLE
add SPID logo

### PR DESCRIPTION
**Pull request by infofami**
add SPID logo

### CODE REVIEW

**Comment by catenocrypt** [comment]
Fami.finance: token does not meet our minimal usage limit, rejecting; see https://community.trustwallet.com/t/how-to-submit-a-token-logo/3863#how-to-get-approved
https://etherscan.io/token/0x032aE2bd448904E0d468167DC25B4C35d3d72a36

Spider.finance: usgage is OK.
Please add an `info.json` file next to the logo.png, with info about the project, of the form:
https://github.com/trustwallet/assets/blob/master/blockchains/ethereum/assets/0x0000000000085d4780B73119b644AE5ecd22b376/info.json

**Comment by infofami** [comment]
> Fami.finance: token does not meet our minimal usage limit, rejecting; see https://community.trustwallet.com/t/how-to-submit-a-token-logo/3863#how-to-get-approved
> https://etherscan.io/token/0x032aE2bd448904E0d468167DC25B4C35d3d72a36
> 
> Spider.finance: usgage is OK.
> Please add an `info.json` file next to the logo.png, with info about the project, of the form:
> https://github.com/trustwallet/assets/blob/master/blockchains/ethereum/assets/0x0000000000085d4780B73119b644AE5ecd22b376/info.json

[0xf28D3dcc9b6582F1b2D49Ca850dB1360571cB633.zip](https://github.com/trustwallet/assets/files/5130416/0xf28D3dcc9b6582F1b2D49Ca850dB1360571cB633.zip)

**Comment by infofami** [comment]
> > Fami.finance: token does not meet our minimal usage limit, rejecting; see https://community.trustwallet.com/t/how-to-submit-a-token-logo/3863#how-to-get-approved
> > https://etherscan.io/token/0x032aE2bd448904E0d468167DC25B4C35d3d72a36
> > Spider.finance: usgage is OK.
> > Please add an `info.json` file next to the logo.png, with info about the project, of the form:
> > https://github.com/trustwallet/assets/blob/master/blockchains/ethereum/assets/0x0000000000085d4780B73119b644AE5ecd22b376/info.json
> 
> [0xf28D3dcc9b6582F1b2D49Ca850dB1360571cB633.zip](https://github.com/trustwallet/assets/files/5130416/0xf28D3dcc9b6582F1b2D49Ca850dB1360571cB633.zip)

[0xf28D3dcc9b6582F1b2D49Ca850dB1360571cB633.zip](https://github.com/trustwallet/assets/files/5131103/0xf28D3dcc9b6582F1b2D49Ca850dB1360571cB633.zip)
Please add logo for me.

**Comment by zachzwei** [comment]
Token activity does not meet the minimum requirements.
Pull request will be put on Hold.
Learn more here:
https://community.trustwallet.com/t/how-to-submit-a-token-logo/3863#how-to-get-approved

**Pull request merged**
