### PR TITLE
Update token info and logo 

### PR DESCRIPTION
**Pull request by divinechoice**
Update token info and logo

### CODE REVIEW

**Comment by cryptomanz** [comment]
• What is the purpose of this token? How will it benefit Trust Wallet users?
 • How is the token being distributed? Are you conducting an airdrop?
 • Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?
 • Is the token listed on a centralized/decentralized exchange?
 • Is a Smart Contract audit completed? Where can we find this information?

**Comment by divinechoice** [comment]
> • What is the purpose of this token? How will it benefit Trust Wallet users? • How is the token being distributed? Are you conducting an airdrop? • Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale? • Is the token listed on a centralized/decentralized exchange? • Is a Smart Contract audit completed? Where can we find this information?

Hello, 
1. Its a launchpad token and participant who stake the tokens will get to participate in IDOs.
2. Lot of out holders/stakers use trustwallet and would love to see the same added to trust wallet.
3&4. its not a airdrop. We had our IDO presale on our other launch pads.
5. Yes its listed on pancakeswap, uniswap & Wagyuswap.
6. No, we have multiple launchpads already listed and also token logos are updated on trustwallet. The project is incubated by BlueZilla https://bluezilla.vc/

**Comment by Cryptocool1** [comment]
awaiting for smart contract adit. on hold for now

**Review by chefgsaroar — APPROVED** [review]

**Comment by cryptomanz** [comment]
Feel free to re-open pull request once you meet those requirements.
make sure to mention this PR, so that we can see that fee has been paid already here.

**Pull request closed without merging**
