### PR TITLE
Add PKR token

### PR DESCRIPTION
**Pull request by apquinit**

### CODE REVIEW

**Comment by apquinit** [comment]
Transaction Hash: F92E3E3948C4B18060A61ECEADFA37D75EA841B0EEECEE29B25043E154AA6CC3

**Comment by cryptomanz** [comment]
Hello,
Can your answer some questions?
• What is the purpose of this token? How will it benefit Trust Wallet users?
 • How is the token being distributed? Are you conducting an airdrop?
 • Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?
 • Is the token listed on a centralized/decentralized exchange?
 • Is a Smart Contract audit completed? Where can we find this information?

**Comment by apquinit** [comment]
Okay, will provide the answers asap.

**Comment by apquinit** [comment]
**What is the purpose of this token?** 
PKR (formally POLKER) is a novel platform that offers multiple protocols that can be implemented alone or in combination. They provide solutions to problems that multiple industries that implement blockchain technology are facing.  
The core principles of PKR are Diversity, Versatility, Fairness, and Transparency. With these principles in mind PKR has developed and patented protocols that allow seamless integration into online gaming platforms, e-commerce, and any other platform which requires a multi-currency application. 
The Multi Crypto Marketplace is a unique protocol that allows users/gamers to use their cryptocurrency of choice whilst displaying the live value in the fiat currency of choice. The live price data is pulled from an oracle so that all parties involved have accurate price data displayed in the currency of choice.  
For e-commerce applications, this forms a simple checkout process allowing multiple cryptocurrencies to be implemented without the confusion of multiple chains and wallet usage. By allowing multiple cryptocurrencies to be used simultaneously the protocol allows for a larger demographic.

**How will it benefit Trust Wallet users?** 
With the release of the game coming soon, PKR will be a highly traded token, allowing for TrustWallet users to expand their holdings and compare prices more reliably.

**How is the token being distributed?**  
Check the token primer-  https://polker.game/toker-primer/ 

**Are you conducting an airdrop?** 
Not currently at the moment.   

**Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?** 
We had conducted IDO on June 25th with BSCPad, TRONPad, Bonldy & BullPerks 

**Is the token listed on a centralized/decentralized exchange?** 
$PKR currently listed on CEX and CEX exchanges in Pancakeswap, Uniswap and Bitmart.  

**Is a Smart Contract audit completed? Where can we find this information?** 
Smart contract has been audited from the company Kucoin had recommended.  
You can find the from this link - https://polker.game/wp-content/uploads/2021/08/Smart-Contract-Audit-Report.pdf

**Pull request merged**
