### PR TITLE
Update WOW contract and description

### PR DESCRIPTION
**Pull request by kunalkamble**
- We have relaunched our token to support Pancakeswap v2 and reduced our total  supply to 2B to support and launch world's first charity based NFT Marketplace

### CODE REVIEW

**Comment by kunalkamble** [comment]
We have transferred the 2000TWT
https://explorer.binance.org/tx/A598859073BE3CBE62426089732691FF52EFD1A7233060E573BC1146FCC9CBCB
Please merge this as soon as possible

**Comment by kunalkamble** [comment]
@Cryptocool1 & @zachzwei could you please merge this one
Thank you so much!

**Comment by Cryptocool1** [comment]
Hello, can you send me an official announcement about the updating?

**Comment by kunalkamble** [comment]
You can checkout our website

https://wow.surf

Swap old to new token
https://presale.wow.surf/swap

Tweet
https://twitter.com/world_of_waves/status/1418226591117631493?s=21

You can also check all the updates on our Twitter
https://twitter.com/world_of_waves?s=21


	
Kunal Kamble
email: ***@***.***
mobile: +1 647 866 9239
   	www.kunalkamble.com

**Comment by kunalkamble** [comment]
@Cryptocool1 
The current old token contract address is creating a lot of confusion as we have new contract info on CMC.
https://coinmarketcap.com/currencies/world-of-waves/

You can also verify our new contract address on CMC

**Comment by kunalkamble** [comment]
> Hello, can you send me an official announcement about the updating?

@Cryptocool1 You can check out our website

https://wow.surf

Swap old to new token
https://presale.wow.surf/swap

Tweet
https://twitter.com/world_of_waves/status/1418226591117631493?s=21

You can also check all the updates on our Twitter
https://twitter.com/world_of_waves?s=21

**Comment by Cryptocool1** [comment]
can you please add links to your PR?
example: https://developer.trustwallet.com/add_new_asset#info-json-contents

**Comment by kunalkamble** [comment]
@Cryptocool1 do I have to cancel this and create new PR?

**Comment by Cryptocool1** [comment]
it will be easier.
You may want to try our Assets app in beta; go to https://assets.trustwallet.com, log on with Github, enter contract ID, logo and some additional info, and it will create a PR for you.
See https://community.trustwallet.com/t/how-to-submit-a-token-logo-using-assets-app/82957.

**Comment by kunalkamble** [comment]
> it will be easier.
> You may want to try our Assets app in beta; close this PR, go to https://assets.trustwallet.com, log on with Github, enter contract ID, logo and some additional info, and it will create a PR for you.
> See https://community.trustwallet.com/t/how-to-submit-a-token-logo-using-assets-app/82957.

we have to update this one only, how to do that?
we do not want to create new asset, having multiple WOW token in the list will create more confusion

**Comment by kunalkamble** [comment]
@Cryptocool1 now I got it, I will try that but how do we delete this asset?

**Comment by kunalkamble** [comment]
@Cryptocool1 here is the new pull request, can you help us delete old token as well?
https://github.com/trustwallet/assets/pull/12415

**Comment by kunalkamble** [comment]
@Cryptocool1 I think you can use this one to delete old token

**Comment by kunalkamble** [comment]
@Cryptocool1 I made status to `abandoned` as we have migrated this to a new contract which is in following PR
https://github.com/trustwallet/assets/pull/12415

**Comment by kunalkamble** [comment]
Thank you so much @Cryptocool1

**Pull request merged**
