### PR TITLE
Add Yoozico Logo and Info

### PR DESCRIPTION
**Pull request by yoozico**
I want to add image for logo Yoozico token.

### CODE REVIEW

**Review by yoozico — COMMENTED** [review]
[info.json](https://github.com/user-attachments/files/15837730/info.json)

**Comment by yoozico** [comment]
108164

**Comment by yoozico** [comment]
[Uploading export-tokenholders-for-contract-0x45830e45DAAcf5a1BD76c528E2c51E8192068518.csv…]()

**Comment by yoozico** [comment]
how can i fix this problem ?
❌ number of holders not checked: please, check it manually

**Comment by Cryptocool1** [comment]
• What is the purpose of this token? How will it benefit Trust Wallet users?
 • How is the token being distributed? Are you conducting an airdrop?
 • Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?
 • Is the token listed on a centralized/decentralized exchange?
 • Is a Smart Contract audit completed? Where can we find this information?

**Comment by yoozico** [comment]
@Cryptocool1 Cryptocool1

1. Yoozico has been present at Trustwallet for 3 years.
Yoozico token works in the field of music and music smart contracts, music education and related awards, and is also working in the field of NFT and setting up a crypto exchange.

https://www.opensea.io/yoozicocenter

. After becoming a coin, it will pursue multipurpose goals.

2. At the beginning of the establishment in 2021, we held an airdrop and we do not intend to hold an airdrop anymore.

3. At the beginning of the establishment  in 2021, we handed over 24% of Yoozico  tokens to two Mega companies with an agreed amount, and at the request of the buyers, we distributed them among their employees  and their famillies for free.

4. We are listed in 14 exchanges related to Binance  sine the begging
https://pancakeswap.finance/swap?outputCurrency=0x45830e45DAAcf5a1BD76c528E2c51E8192068518&utm_source=http://thebittimes.com/token-yoozic-BSC-0x45830e45DAAcf5a1BD76c528E2c51E8192068518.html&utm_medium=web&utm_campaign=TheBitTimes.Com

https://bsc.mdex.me/#/swap?lang=en?outputCurrency=0x45830e45DAAcf5a1BD76c528E2c51E8192068518&utm_source=http://thebittimes.com/token-yoozic-BSC-0x45830e45DAAcf5a1BD76c528E2c51E8192068518.html&utm_medium=web&utm_campaign=TheBitTimes.Com

https://trade.bscswap.com/#/swap?outputCurrency=0x45830e45DAAcf5a1BD76c528E2c51E8192068518&utm_source=http://thebittimes.com/token-yoozic-BSC-0x45830e45DAAcf5a1BD76c528E2c51E8192068518.html&utm_medium=web&utm_campaign=TheBitTimes.Com

https://bsc.anyswap.exchange/swap?outputCurrency=0x45830e45DAAcf5a1BD76c528E2c51E8192068518&utm_source=http://thebittimes.com/token-yoozic-BSC-0x45830e45DAAcf5a1BD76c528E2c51E8192068518.html&utm_medium=web&utm_campaign=TheBitTimes.Com

https://bscstation.finance/#/swap?outputCurrency=0x45830e45DAAcf5a1BD76c528E2c51E8192068518&utm_source=http://thebittimes.com/token-yoozic-BSC-0x45830e45DAAcf5a1BD76c528E2c51E8192068518.html&utm_medium=web&utm_campaign=TheBitTimes.Com

https://cheeseswap.app/#/swap?outputCurrency=0x45830e45DAAcf5a1BD76c528E2c51E8192068518&utm_source=http://thebittimes.com/token-yoozic-BSC-0x45830e45DAAcf5a1BD76c528E2c51E8192068518.html&utm_medium=web&utm_campaign=TheBitTimes.Com

https://o3swap.com/swap?outputCurrency=0x45830e45DAAcf5a1BD76c528E2c51E8192068518&utm_source=http://thebittimes.com/token-yoozic-BSC-0x45830e45DAAcf5a1BD76c528E2c51E8192068518.html&utm_medium=web&utm_campaign=TheBitTimes.Com

https://swap.lz.finance/?outputCurrency=0x45830e45DAAcf5a1BD76c528E2c51E8192068518&utm_source=http://thebittimes.com/token-yoozic-BSC-0x45830e45DAAcf5a1BD76c528E2c51E8192068518.html&utm_medium=web&utm_campaign=TheBitTimes.Com

https://autofarm.network/swap/?outputCurrency=0x45830e45DAAcf5a1BD76c528E2c51E8192068518&utm_source=http://thebittimes.com/token-yoozic-BSC-0x45830e45DAAcf5a1BD76c528E2c51E8192068518.html&utm_medium=web&utm_campaign=TheBitTimes.Com

https://app.apeswap.finance/?outputCurrency=0x45830e45DAAcf5a1BD76c528E2c51E8192068518&utm_source=http://thebittimes.com/token-yoozic-BSC-0x45830e45DAAcf5a1BD76c528E2c51E8192068518.html&utm_medium=web&utm_campaign=TheBitTimes.Com

https://exchange.biswap.org/#/swap?outputCurrency=0x45830e45DAAcf5a1BD76c528E2c51E8192068518&utm_source=http://thebittimes.com/token-yoozic-BSC-0x45830e45DAAcf5a1BD76c528E2c51E8192068518.html&utm_medium=web&utm_campaign=TheBitTimes.Com

https://exchange.biswap.org/#/swap?outputCurrency=0x45830e45DAAcf5a1BD76c528E2c51E8192068518&utm_source=http://thebittimes.com/token-yoozic-BSC-0x45830e45DAAcf5a1BD76c528E2c51E8192068518.html&utm_medium=web&utm_campaign=TheBitTimes.Com

https://app.1inch.io/#/1/swap?outputCurrency=0x45830e45DAAcf5a1BD76c528E2c51E8192068518&utm_source=http://thebittimes.com/token-yoozic-BSC-0x45830e45DAAcf5a1BD76c528E2c51E8192068518.html&utm_medium=web&utm_campaign=TheBitTimes.Com

https://paraswap.io/#/?network=bsc?outputCurrency=0x45830e45DAAcf5a1BD76c528E2c51E8192068518&utm_source=http://thebittimes.com/token-yoozic-BSC-0x45830e45DAAcf5a1BD76c528E2c51E8192068518.html&utm_medium=web&utm_campaign=TheBitTimes.Com

**Comment by yoozico** [comment]
@Cryptocool1 
no 
We haven't written any smart contracts with anyone yet.

**Comment by Cryptocool1** [comment]
We require smart contract audit from reputable companies. Please come back to us once audit is done. 
When creating new PR make sure to mention this one so the fee can be reused

**Comment by yoozico** [comment]
So far no one has asked us anything about this.
Where can we get it?
please guide us

**Comment by yoozico** [comment]
Hello Trust Walt 
You asked us for an audit report for displaying Yoozico logo.
 We ordered it from immunebytes company and will send it to you.
 We would also like to point out that we have already paid the amount of Trust Volt related expenses, which we ask you to include in the calculations.

Sincerely
YOOZICO
[Uploading Yoozico - Final Audit Report.pdf…]()

**Pull request closed without merging**
