### PR TITLE
Add Cylum Finance (BEP20)

### PR DESCRIPTION
**Pull request by CYLUMFINANCE**
Adding info for BEP20 token 'Cylum Finance'.

PR created by <a href="https://assets.trustwallet.com">TW Assets Management</a>

### CODE REVIEW

**Comment by CYLUMFINANCE** [comment]
• What is the purpose of this token? How will it benefit Trust Wallet users?

Cylum is a protocol designed to facilitate the construction of NFT and Meterverse projects on the Binance Smart Chain, as well as partnerships and funding. The CYM token is used to power and drive this ecosystem. In addition to our reward system, we have a unique lock-stake algorithm that provides each token holder with a reward of up to 400% annual percentage yield (APY) for staking CYM tokens.

• How is the token being distributed? Are you conducting an airdrop?
No

• Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?
Yes we had a Presale at the initial stage, when raising funds for the development.

• Is the token listed on a centralized/decentralized exchange?
Yes.

• Is a Smart Contract audit completed? Where can we find this information?
Yes, the contract is fully audited by Techrate.

https://github.com/TechRate/Smart-Contract-Audits/blob/main/March/CYLUM%20Full%20Smart%20Contract%20Security%20Audit.pdf

**Comment by Cryptocool1** [comment]
Please add the tag, see the requirements here: (https://developer.trustwallet.com/assets/requirements)

**Review by CYLUMFINANCE — COMMENTED** [review]
Tag has been added successfully.

**Comment by CYLUMFINANCE** [comment]
We would love to re-update the logo, what are the procedures required?

**Pull request merged**
