### PR TITLE
Add FRZ Solar System Coin (BEP20)

### PR DESCRIPTION
**Pull request by frzss-dev**
Adding info for BEP20 token 'FRZ Solar System Coin'.

PR created by <a href="https://assets.trustwallet.com">TW Assets Management</a>

### CODE REVIEW

**Comment by Cryptocool1** [comment]
• What is the purpose of this token? How will it benefit Trust Wallet users?
 • How is the token being distributed? Are you conducting an airdrop?
 • Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?
 • Is the token listed on a centralized/decentralized exchange?
 • Is a Smart Contract audit completed? Where can we find this information?

**Comment by frzss-dev** [comment]
• What is the purpose of this token? How will it benefit Trust Wallet users?
FRZ ecosystem is a blockchain-powered company that focuses on cryptocurrency development and provides solutions to address the energy crisis
Our users mainly use trust wallet for buy, sell, transfer and hold their tokens, our most transactions come from trust wallet too
 • How is the token being distributed? Are you conducting an airdrop?
10% circulation 
10% team
80% for token burning, staking, listing, marketing and etc 
airdrop ended
 • Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?
No
 • Is the token listed on a centralized/decentralized exchange?
yes the links of Exchages :
[pancakeswap](https://pancakeswap.finance/swap?outputCurrency=0xFbDB1Fa163a0e8d90DD88104F44C093882A71914)
[Lbank](https://www.lbank.com/en-US/trade/frzss_usdt/)
[Mexc](https://www.mexc.com/exchange/FRZSSCOIN_USDT?_from=search_spot_trade)
 • Is a Smart Contract audit completed? Where can we find this information?
Yes
[contractwolf](https://contractwolf.io/projects/frz-solar-system-coin)

**Comment by frzss-dev** [comment]
Total Supply:
8,001,583,176.499588 FRZSSCOIN
Holders:
10,573 addresses

[bscscan](https://bscscan.com/token/0xFbDB1Fa163a0e8d90DD88104F44C093882A71914)

**Comment by frzss-dev** [comment]
Hi dear Trust Wallet
Should I do something for 3 workflows awaiting approval ?
please let me know if I should.
thank you

**Comment by Cryptocool1** [comment]
There is nothing needed from you

**Comment by frzss-dev** [comment]
thank you for your Attention.

**Pull request merged**
