### PR TITLE
Add MND (BEP20)

### PR DESCRIPTION
**Pull request by Bunny-dev-510**

### CODE REVIEW

**Comment by Bunny-dev-510** [comment]
Dear Trust Wallet Team,

Hi, we have deployed a new tokens, MND and bQBT.

We know the number of bQBT holders are insufficient to criteria, but please note that it is a part of our PancakeBunny ecosystem (has more than 90,000 BUNNY token holders) not standalone token.

Thank you.

**Comment by cryptomanz** [comment]
Hello,
Can your answer some questions?
• What is the purpose of this token? How will it benefit Trust Wallet users?
 • How is the token being distributed? Are you conducting an airdrop?
 • Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?
 • Is the token listed on a centralized/decentralized exchange?
 • Is a Smart Contract audit completed? Where can we find this information?

**Comment by Bunny-dev-510** [comment]
* What is the purpose of this token? How will it benefit Trust Wallet users?
 - bQBT is a liquid token that you can receive in return when you lock up QBT at PancakeBunny. It is used to generate a QBT rewards multiple. and if you stake bQBT, you can receive a share of the QBT rewards generated by PancakeBunny’s Qubit SAVs (Single Asset Vault).
 - MND token is a vehicle created to capture and distribute the full value of our ecosystem expansion directly to the PancakeBunny Community. and the Mound Vault that you can stake MND is designed as a means for the PancakeBunny Community to share in the full value of all of the innovative DeFi projects/products that Team Bunny has to offer, now and in the future.

* How is the token being distributed? Are you conducting an airdrop?
 - [bQBT] token is automatically minted when QBT holders lock up their QBT for in PancakeBunny. The exchange ratio is 1:1.
 - [MND] token is distributed by presale event and airdrop for BUNNY and pBUNNY holders, respectively. 

* Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?
- [bQBT] token has not conducted ICO or presale
- [MND] token was sold in presale event

* Is the token listed on a centralized/decentralized exchange?
- [bQBT] is not listed in centralized or decentralized exchange yet, but it can be earned by swapping QBT in our bQBT pool
- [MND] is listed in PancakeSwap (https://pancakeswap.finance/info/token/0x4c97c901b5147f8c1c7ce3c5cf3eb83b44f244fe)

* Is a Smart Contract audit completed? Where can we find this information?
 - [bQBT] we have been audited by PeckShield (https://github.com/PancakeBunny-finance/Bunny/blob/main/audits/PeckShield-Audit-Report-PancakeBunny-v1.0.pdf)
 - [MND] we have not been audited yet, but we have plan to order audit soon.

**Comment by Cryptocool1** [comment]
Hello, we can accept only Mound Token for now

**Comment by Bunny-dev-510** [comment]
Hi, we removed bQBT info and push again. Thank you.

**Comment by Cryptocool1** [comment]
hello,
can you send me your full size logo? 
Снимок экрана 2021-09-28 в 14 02 14
it looks not good

**Pull request merged**
