### PR TITLE
Please add uTOPIA logo

### PR DESCRIPTION
**Pull request by AvantgardeScott**
logo

6th times a charm?

### CODE REVIEW

**Comment by TRONtopia** [comment]
any insight into what is wrong?

**Comment by catenocrypt** [comment]
Hex contract needs to be in mixed-case format, I'm updating this for you.

**Comment by TRONtopia** [comment]
Ty Catenocrypt!!!! I was pulling what little hairs I had left out =D

**Comment by TRONtopia** [comment]
Payment is on it's way... thank you so much!

**Pull request merged**
