### PR TITLE
added fiola info.json

### PR DESCRIPTION
**Pull request by FiolaNetwork**

### CODE REVIEW

**Comment by catenocrypt** [comment]
@FiolaNetwork , please note that this PR contains no files!  Please check and comment.

**Comment by FiolaNetwork** [comment]
Hello. I’m sorry I’m having having hard time . Where can I place the info need it ? Can I add the in here on the comment section?

**Comment by catenocrypt** [comment]
Adding files to a repository is quite basic Git operation.  But you can just put in a comment for now.

**Comment by FiolaNetwork** [comment]
fiola

**Comment by FiolaNetwork** [comment]
{
  "name": "Fiola",
  "website": "https://fiola.network/",
  "source_code": "https://github.com/FiolaNetwork",
  "white_paper": "https://www.dropbox.com/s/gd21jw3b60eepgz/FiolaNetwork%20Whitepaper%20.pdf?dl=0",
  "short_description": "Fiola Network (FLA)is a series of projects including a social network,restaurant industry, digital advertising network and blockchain dApp platform which will utilize Fiola Token.",
  "explorer": "https://etherscan.io/token/0x7bE5901F679BDE8202a123c84C19BBCE2CF3449B",
  "research": "https://fiola.network"
}

**Comment by FiolaNetwork** [comment]
@catenocrypt thank you so much.

**Comment by catenocrypt** [comment]
Now that you provided info, I could check the token.  Unfortunately the usage of this token is way below our standard limit.  As per our policy, brand new tokens are not included, there is a minimum requirement of 500 holder addresses and 1000 transactions.
See the criteria at (mentioned in the first message by the bot): https://community.trustwallet.com/t/how-to-submit-a-token-logo/3863#how-to-get-approved
This token has minimal usage yet (14). Putting PR on hold. Please come back to us when all criteria are met.


https://etherscan.io/token/0x7bE5901F679BDE8202a123c84C19BBCE2CF3449B

**Comment by FiolaNetwork** [comment]
@catenocrypt I have a question? What happed if this pull closed. I have to do it again after the coin fulfill the standards limits?

**Comment by catenocrypt** [comment]
@FiolaNetwork , if this PR is closed, and later usage limit is OK, you can ask us to reopen this PR.  Please keep a record of the PR number! :)

**Comment by FiolaNetwork** [comment]
Oh ok thank you

On Sep 14, 2020, at 4:28 AM, Adam R <notifications@github.com> wrote:

﻿

@FiolaNetwork<https://github.com/FiolaNetwork> , if this PR is closed, and later usage limit is OK, you can ask us to reopen this PR. Please keep a record of the PR number! :)

**Pull request closed without merging**
