### PR TITLE
Upload KGC token

### PR DESCRIPTION
**Pull request by lbk3530**

### CODE REVIEW

**Comment by lbk3530** [comment]
@vikmeup I don't understand why checks have failed, sir?
Could you please help me?

**Comment by kolya182** [comment]
@lbk3530 Your PR looks good, just we need fix something. Sorry for the delay, will fix it ASAP.
I know you uploaded tons of images, how do they relate to you, i'm just curious

**Comment by lbk3530** [comment]
> @lbk3530 Your PR looks good, just we need fix something. Sorry for the delay, will fix it ASAP.
> I know you uploaded tons of images, how do they relate to you, i'm just curious
Those projects are listed on our dex.

**Comment by lbk3530** [comment]
Hi @kolya182 , this commit has been merged. When will this URL be valid? 
https://raw.githubusercontent.com/TrustWallet/tokens/master/blockchains/ethereum/assets/0xa8262eb913fccea4c3f77fc95b8b4043b384cfbb/logo.png

**Comment by kolya182** [comment]
> Hi @kolya182 , this commit has been merged. When will this URL be valid?
> https://raw.githubusercontent.com/TrustWallet/tokens/master/blockchains/ethereum/assets/0xa8262eb913fccea4c3f77fc95b8b4043b384cfbb/logo.png

Here is correct one `https://raw.githubusercontent.com/trustwallet/assets/master/blockchains/ethereum/assets/0xa8262eb913fccea4c3f77fc95b8b4043b384cfbb/logo.png`

**Comment by lbk3530** [comment]
@kolya182  I got the URL from  FAQ.

How to use it? (For Developers)
Base URL for token image:
https://raw.githubusercontent.com/TrustWallet/tokens/master/blockchains/ethereum/assets/<contract_address_lowercase>/logo.png

So that is incorrect?

**Pull request merged**
