### PR TITLE
Add ROIMA INC TOKEN (BEP20)

### PR DESCRIPTION
**Pull request by hector375**
Adding info for BEP20 token 'ROIMA INC TOKEN'.

PR created by <a href="https://assets.trustwallet.com">TW Assets Management</a>

### CODE REVIEW

**Comment by hector375** [comment]
Holders 710 addresses

**Comment by hector375** [comment]
> ### PR Summary
> 
> Files OK: 2 Token in PR: **BEP20** 0x5416f06830C7826A2ee774c53a3589e707269AB3 Symbol: **RMAI** decimals: 9 Links: [Logo](https://raw.githubusercontent.com/hector375/assets/br0727-192607/blockchains/smartchain/assets/0x5416f06830C7826A2ee774c53a3589e707269AB3/logo.png) [Info](https://raw.githubusercontent.com/hector375/assets/br0727-192607/blockchains/smartchain/assets/0x5416f06830C7826A2ee774c53a3589e707269AB3/info.json) [Website](https://rmai.io/) [Explorer](https://bscscan.com/token/0x5416f06830C7826A2ee774c53a3589e707269AB3) Tags: deflationary Token check error: ❌ number of holders not checked: please, check it manually (Holders 710)
> 
> 

Holder 710

**Comment by hector375** [comment]
How long can it take for the LOGO of my coin to appear in my wallet?

**Comment by yenky** [comment]
Requirement of Holders and transactions are not meeting the criteria of listing .

**Comment by Cryptocool1** [comment]
As per our policy, brand new tokens are not included, there is a minimum requirement of 10,000 holder addresses and 15,000 transactions, in order to filter out scam tokens.
See the criteria at : https://developer.trustwallet.com/assets/requirements .

**Comment by Cryptocool1** [comment]
Please come back to us once all criteria are met. Make sure you mention this PR in new one, so the fee can be reused

**Pull request closed without merging**
