### PR TITLE
Add OctoFi logo to Trust Wallet assets

### PR DESCRIPTION
**Pull request by octofinance**
Thanks for providing such a great resource!

### CODE REVIEW

**Comment by catenocrypt** [comment]
As per our policy, brand new tokens are not included, there is a minimum requirement of 500 holder addresses and 1000 transactions, in order to filter out scam tokens.
See the criteria at (mentioned in the first message by the bot): https://community.trustwallet.com/t/how-to-submit-a-token-logo/3863#how-to-get-approved
This token has below-limit usage (108). Rejecting PR now. Please come back to us when all criteria are met.

https://etherscan.io/token/0x7240aC91f01233BaAf8b064248E80feaA5912BA3

**Comment by octofi** [comment]
Hi @catenocrypt,

Apologies. Wasn't clear on developer docs: https://developer.trustwallet.com/add_new_asset

Didn't realise superseded by community forum post. Have taken note and will resubmit when requirements are met. Again, sorry for the mixup. 

Take care.

**Comment by catenocrypt** [comment]
Thanks for the feedback.  We have to mention the minimum requirements on that page as well (we no longer refer to that page, but still).

**Comment by octofi** [comment]
No problem @catenocrypt we completely understand. Don't forget to update the reference from your repo's readme too :+1: 

https://github.com/trustwallet/assets/blob/master/README.md

Take care, will resubmit once we reach the benchmark.

**Pull request closed without merging**
