### PR TITLE
TX ID

### PR DESCRIPTION
**Pull request by sudokuinu**
4DE2ED3E5FE617A4FB64E1E2F287C4A15BC1DFA09FF844E56DB761A31469BD20

this transaction is about 1000 TWT that is some a fee

### CODE REVIEW

**Comment by sudokuinu** [comment]
transaction is pay on the this bnb1tqq9llyr3dyjd559dha6z5r5etk3qfwk07 from prior that filed for logo name :
4DE2ED3E5FE617A4FB64E1E2F287C4A15BC1DFA09FF844E56DB761A31469BD20

**Comment by sudokuinu** [comment]
Is the payment approved?

**Comment by sudokuinu** [comment]
I paid again
163E3D38496D7D06BC648E8EED64B05D959866F4534803F8F2557929962AE7E3

**Comment by sudokuinu** [comment]
i did not understand that which the problem is it? is my request failed ?

**Comment by sudokuinu** [comment]
Can I have any answer ???
Do I have to apply again ?

**Comment by Cryptocool1** [comment]
You need to delete this file blockchains/smartchain/assets/0xFA6388D08A40BEcC4d1464d3C17a99960c96309C/logo-b.png

**Comment by sudokuinu** [comment]
404 error

**Comment by sudokuinu** [comment]
thanks 
done

**Comment by Cryptocool1** [comment]
hello,
what is the purpose of your token?

**Comment by sudokuinu** [comment]
thanks for your answer .
for the start the work we require introduce our self to Crypto worlds . So we start our work by the BEP20 Token .
our the final decision we have exclusive blockchain and in the final we move to our Blockchain this the main of our target .
for the more introduction I can say explain this context The Sudoku network consists of a large number of side chains that can connect different blockchains. This connection is very useful for the Crypto community.
For example, suppose you want to buy a token or currency with your assets on the bep-20 network from the deFi network (ETH). With the ETH network, transfer (first fee), then convert your assets from bep-20 to ETH (second fee), and finally buy the desired token with the amount of ETH ready (third fee), and finally if want to transfer back to your wallet includes the fourth fee.
However, with the Sudoku network, all these steps are done in one step and only in one step and a very low fee is requested from you and your transaction is done in the shortest possible time.
The source code of each Side chain is written very carefully and for special security in transactions, it uses the proprietary sudoku algorithm to confirm transactions, We have designed this algorithm to respect users' time and environment in such a way that transactions can be done in the shortest time and with the least energy consumption. Due to the very low energy consumption and the hardware used, our fee can be very low.

**Comment by sudokuinu** [comment]
Hello again 
do you need more information ??

**Comment by sudokuinu** [comment]
Do I have to do something or be patient?
@Cryptocool1 
thanks

**Comment by Cryptocool1** [comment]
> Hello again
> do you need more information ??

How will it benefit Trust Wallet users?
 • How is the token being distributed? Are you conducting an airdrop?
 • Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?
 • Is the token listed on a centralized/decentralized exchange?
 • Is a Smart Contract audit completed? Where can we find this information?

**Comment by sudokuinu** [comment]
Thanks for your answer ....
Being able to have our logo in our wallet is both good for our project and users are sure that the project has been reviewed from elsewhere, so we have taken steps to have the project reviewed by you as well; I would be happy if you read our Whitepaper.
We have held an AirDrop stage on Twitter and Telegram and it has been distributed. The remaining distribution of tokens is based on being listed in exchange offices, so that in order not to lose the distribution of tokens to previous buyers, we make the size of each distribution equal to AirDrop and listing to exchange  so that a large volume of tokens is not distributed. The final distribution of the token will be after the launch of our platform, where users can use our token to convert nft to defi and pay for services from our tokens. Also, after the launch of the investment platform that we are considering, users can They can also use our token in this area.
We have no pre-sale or ico and are listed directly in a decentralized exchange. Our token is listed on Pancake Swap and we have locked its liquidity for the safety and security of users, which you can also check.
You can easily check our smart contract information from bscscan. You can also see that we have burned 50% of the supply. We did this before it was listed on Pancake Swap, which means we did not do it to increase the price.
You can download more information from our site. We have also applied for listing in other exchange .
I will be happy if you need more information to share with me.

@Cryptocool1 
best regards , 
Alex from SUDOKU INU team

**Comment by sudokuinu** [comment]
If you need more information I will be happy to know

**Comment by sudokuinu** [comment]
Do we have to wait ?? Need more information ??
@Cryptocool1

**Comment by Cryptocool1** [comment]
Is a Smart Contract audit completed?

**Comment by sudokuinu** [comment]
thanks for your answer . 
Yes it is completed .As I said before, we started with Bep20 . And finally we move to our own blockchain . Do you need our Token Smart Contract Code? 
I can upload to our GitHub or send it to you right here.
@Cryptocool1 
Best regards , 
Alex

**Comment by Cryptocool1** [comment]
awaiting for listing on cmc
on hold for now

**Comment by Cryptocool1** [comment]
Hello,
please create new PR when CMC listing will be ready.
make sure to mention this PR, so that we can see that fee has been paid already here.

**Pull request closed without merging**
