### PR TITLE
Add files via upload Lady Doge (2,500 Holders DONE) 

### PR DESCRIPTION
**Pull request by ladydogeworld**
Logo

### CODE REVIEW

**Comment by Cryptocool1** [comment]
This is a BEp20 token, correct folder is blockchains/smartchain/assets.

**Comment by ladydogeworld** [comment]
Sorry, we have Upload but wrong Memo

[Comparing trustwallet:master...ladydogeworld:master · trustwallet/assets (github.com)](https://github.com/trustwallet/assets/compare/master...ladydogeworld:master)

Sent with [ProtonMail](https://protonmail.com/) Secure Email.

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐
CryptoA ***@***.***> schrieb am Dienstag, 6. Juli 2021 um 14:56:

**Comment by ladydogeworld** [comment]
Can you fix it ?

**Comment by ladydogeworld** [comment]
Already Payed but wrong MEMO 1418

**Review by ladydogeworld — COMMENTED** [review]
its done?

**Review by ladydogeworld — COMMENTED** [review]
its ok?

**Comment by ladydogeworld** [comment]
Done Guys.

**Review by ladydogeworld — COMMENTED** [review]
We are a meme coin that grows and grows and grows. The whole consists of your team from Germany and Belgium. Our goal is to play a female role in the BSC world and thereby even run charity.


Our goals are very clear -> to help and to create a family.

Our added value is clearly our number of holders who really believe in the project. We are not dump and pump, we grow day by day.

We started a fair launch and no airdrops. We are a small team and want to create a solid footing here forever.


Our enrichment for Trustwallet is also very clear, because we will soon be a meme that will become standard next to Doge!

**Comment by ladydogeworld** [comment]
@Cryptocool1 is this okay?

**Review by ladydogeworld — COMMENTED** [review]
Lets go

**Comment by Cryptocool1** [comment]
As per our policy, brand new tokens are not included, there is a minimum requirement of 2500 holder addresses and 5000 transactions, in order to filter out scam tokens.
See the criteria at (mentioned in the first message by the bot): https://community.trustwallet.com/t/how-to-submit-a-token-logo/3863).

**Comment by ladydogeworld** [comment]
> As per our policy, brand new tokens are not included, there is a minimum requirement of 2500 holder addresses and 5000 transactions, in order to filter out scam tokens.
> See the criteria at (mentioned in the first message by the bot): https://community.trustwallet.com/t/how-to-submit-a-token-logo/3863).

If we have 2,500 holders, will we automatically get the logo now? Is everything all right?


We are 12 days old and have an audit. I think we are ready!

**Comment by Cryptocool1** [comment]
hi ,
please delete this file blockchains/smartchain/assets/0x384f5a9b720349015a27251684c7a1510dd151ba/logo.png

**Comment by Cryptocool1** [comment]
where can I find the audit?

**Comment by ladydogeworld** [comment]
> where can I find the audit?

Hello ! 

https://github.com/TechRate/Smart-Contract-Audits/blob/main/LadyDoge.pdf

i cant delete this png file !

**Comment by ladydogeworld** [comment]
done. Deleted

**Comment by Aaronztt** [comment]
Gogogo

**Comment by Cryptocool1** [comment]
> done. Deleted

awaiting for 2500 holders

**Comment by ladydogeworld** [comment]
> > done. Deleted
> 
> awaiting for 2500 holders

oh Comon @Cryptocool1 .. we are Doxxed.. we have Audit, We dont make Airdrops and we deserve it ..

**Comment by ladydogeworld** [comment]
@Cryptocool1 we have 2,500 Holders !

**Review by Aaronztt — APPROVED** [review]

**Review by Aaronztt — CHANGES_REQUESTED** [review]
Done

**Review by Aaronztt — CHANGES_REQUESTED** [review]
Done

**Review by Aaronztt — CHANGES_REQUESTED** [review]
Done

**Comment by Cryptocool1** [comment]
Awaiting for CMC listing

**Comment by Aaronztt** [comment]
> Awaiting for CMC listing

Oh comon guys! Stop now.. We paid, we are doxxed y we have a audit, we make charity x we have 2500 holders and now we need cmc?! Ey..

**Comment by ladydogeworld** [comment]
> Awaiting for CMC listing

So, 

> Awaiting for CMC listing


So, slowly I'm fed up. We paid a lot of money for this, we have now delivered everything that needs to be delivered. We are 14 days old, have met the minimum holder and all Trustwallet requirements.

We are doxxed and do charity .. we have an audit and everything fits! Now are you guys coming to me with CMC? I don't think that's okay at all! You put stones in our way! from CMC was never mentioned! We have already applied CMC and many of them already have their logo!

**Comment by Cryptocool1** [comment]
please create new PR when CMC listing will be ready.
make sure to mention this PR, so that we can see that fee has been paid already here.

**Comment by ladydogeworld** [comment]
So I'm fed up.

We created the natrag 1 week ago, so the rules were very clear:


2,500 holder and audit etc. we fulfilled everything!

We have already paid for 1 week where the rules were different.
There was never any mention of CMC listning for Trustwallet Logo.


I now ask you one last time to approve this for us. Adam said you can make exceptions.

So please be fair and give us what we are entitled to! We fought for it .. for 17 days .. and you are taking it away from us ... please!

**Comment by ladydogeworld** [comment]
So I'm fed up.

We created the natrag 1 week ago, so the rules were very clear:


2,500 holder and audit etc. we fulfilled everything!

We have already paid for 1 week where the rules were different.
There was never any mention of CMC listning for Trustwallet Logo.


I now ask you one last time to approve this for us. Adam said you can make exceptions.

So please be fair and give us what we are entitled to! We fought for it .. for 17 days .. and you are taking it away from us ... please!

@Cryptocool1

**Pull request closed without merging**
