### PR TITLE
Add Gem Exchange and Trading (ERC20)

### PR DESCRIPTION
**Pull request by gxtmg**
Adding info for ERC20 token 'Gem Exchange and Trading'.

PR created by <a href="https://assets.trustwallet.com">TW Assets Management</a>

### CODE REVIEW

**Comment by gxtmg** [comment]
@Cryptocool1  
Hello 
i make new PR, but https://assets.trustwallet.com want to insert contract with uppercase. 

So I put uppercase, but bot judges it as an error. Where should I do it?

**Comment by cryptomanz** [comment]
As per our policy, brand new tokens are not included, there is a minimum requirement of 5,000 holder addresses and 10,000 transactions, in order to filter out scam tokens.
See the criteria at : https://developer.trustwallet.com/assets/requirements .

**Comment by gxtmg** [comment]
@Cryptocool1 @cryptomanz 
hello 

As you said in #17612, I PR again. The number of holders and transaction conditions mentioned above are satisfied by looking at , an old contract.
https://etherscan.io/token/0x28d3E409bb9bC58F1ca6E009f8fC78A1db85e6b7, an old contract.

**Comment by Cryptocool1** [comment]
• Is a Smart Contract audit completed? Where can we find this information?

**Comment by gxtmg** [comment]
https://gxt.gitbook.io/gxt-global-1/X0GtWV0EXunw61F0gVS1/discover/credibility
It is slowmist audit

https://www.certik.com/projects/gem-exchange-and-trading

It is certik audit

**Pull request merged**
