### PR TITLE
OBR update

### PR DESCRIPTION
**Pull request by NFTOBR**

### CODE REVIEW

**Comment by catenocrypt** [comment]
The BEP2 version has been just included with #4881 , isn't it?

**Comment by NFTOBR** [comment]
yes, this is ETH version

**Comment by NFTOBR** [comment]
with 4882

**Comment by NFTOBR** [comment]
can you please merge this PR as well ?

**Comment by catenocrypt** [comment]
A minor thing: could you add https:// to website, to `https://nftobr.com`, in both info.json?

**Comment by NFTOBR** [comment]
@catenocrypt sure

**Comment by NFTOBR** [comment]
@catenocrypt have fixed the thing, says branch has conflicts. Please suggest!

**Comment by NFTOBR** [comment]
have resolved the conflict, please merge!

**Comment by NFTOBR** [comment]
Hi @catenocrypt the changes are done as you requested. Please merge the PR

**Pull request merged**
