### PR TITLE
Logo update for buyingcoin

### PR DESCRIPTION
**Pull request by obestjose**
Please update logo for buyingcoin
0x4317Af96132792881cDfa2EB6e0b354e2F05c414
logo

### CODE REVIEW

**Comment by obestjose** [comment]
Payment done
https://explorer.binance.org/tx/3ADFD97FB4E0477938FBAE4C1B73DDB33D74F691D3F49AE452943FD68E261837

**Comment by obestjose** [comment]
Payment done
https://explorer.binance.org/tx/3ADFD97FB4E0477938FBAE4C1B73DDB33D74F691D3F49AE452943FD68E261837

> Hi! In order to compensate for the efforts of processing PRs, we kindly ask for a contribution.
> See the [Pull Request Fee FAQ](https://developer.trustwallet.com/add_new_asset/pr-fee).
> 
> Please pay **500 TWT** with the memo **3454** to the address `bnb1tqq9llyr3dyjd559dha6z5r5etk3qfwk07m098`.
> Alternatively, 1 BNB is also accepted (same memo & address).
> 
> **QR** code: [Trust](https://api.qrserver.com/v1/create-qr-code/?size=200x200&data=https%3A%2F%2Flink.trustwallet.com%2Fsend%3Fcoin%3D714%26address%3Dbnb1tqq9llyr3dyjd559dha6z5r5etk3qfwk07m098%26amount%3D500%26memo%3D3454) | [other wallet](https://api.qrserver.com/v1/create-qr-code/?size=200x200&data=bnb1tqq9llyr3dyjd559dha6z5r5etk3qfwk07m098%26amount%3D500%26memo%3D3454)
> 
> _Notes_:
> 
> * Trust Wallet Tokens (TWT) are distributed to new users through our [Referral Program](https://community.trustwallet.com/t/invite-a-friend-earn-trust-wallet-token-twt/4125).
> * Payment evaluation happens when there is activity on the PR -- write a comment if you have performed the payment.
> * When payment is detected, an Accept Review is automatically placed on the PR, which is a condition for merge.  The merge is still done manually.
> * One PR should be for a single project; PR's with more than 10 logos will be rejected.

Payment done
https://explorer.binance.org/tx/3ADFD97FB4E0477938FBAE4C1B73DDB33D74F691D3F49AE452943FD68E261837

**Comment by obestjose** [comment]
When will logo show up?

**Comment by catenocrypt** [comment]
As per our updated policy, brand new tokens are not included, there is a minimum requirement of 100 holder addresses and 500 transactions, in order to filter out scam tokens.
See https://community.trustwallet.com/t/how-to-submit-a-token-logo/3863#how-to-get-approved
Token check:  Usage is very low.  Name matches.
Putting on hold for now.

**Comment by vikmeup** [comment]
As per our updated policy, brand new tokens are not included, there is a minimum requirement 

- at least 100 token holders
- at least 500 transactions

See our [How to Get Submit Token Logo ](https://community.trustwallet.com/t/how-to-submit-a-token-logo/3863#how-to-get-approved) guidelines.

Feel free to re-open once you meet those requirements.

**Pull request closed without merging**
