### PR TITLE
Add Squidanomics (BEP20)

### PR DESCRIPTION
**Pull request by MizzWasTaken**
Adding info for BEP20 token 'Squidanomics'.

PR created by <a href="https://assets.trustwallet.com">TW Assets Management</a>

### CODE REVIEW

**Comment by MizzWasTaken** [comment]
how do i fix this?

**Comment by ramsty** [comment]
Hi!
Could you answer some questions?
• What is the purpose of this token? How will it benefit Trust Wallet users?
• How is the token being distributed? Are you conducting an airdrop?
• Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?
• Is the token listed on a centralized/decentralized exchange?
• Is a Smart Contract audit completed? Where can we find this information?

**Comment by MizzWasTaken** [comment]
> Hi! Could you answer some questions? • What is the purpose of this token? How will it benefit Trust Wallet users? • How is the token being distributed? Are you conducting an airdrop? • Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale? • Is the token listed on a centralized/decentralized exchange? • Is a Smart Contract audit completed? Where can we find this information?



Sure i can answer these for you!

What is the purpose of this token? How will it benefit Trust Wallet users?
Squidanomics brings Squidgame to life with our multiple games, NFTs and daily community prizes.
• How is the token being distributed? Are you conducting an airdrop?
Squidanomics was distributed through DxSale, there was also a team airdrop
• Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?
Yes, we had a presale on dxsale.
• Is the token listed on a centralized/decentralized exchange?
Yes, The coin is listed on PancakeSwap.
• Is a Smart Contract audit completed? Where can we find this information?
Yes, the contract is audited by BitRise, here is the link. 
https://bitriseaudits.com/project/97

**Comment by cryptomanz** [comment]
Hello,
Please follow the rules for adding token, your logo should be a full screen, 256x256.
Example:
https://community.trustwallet.com/t/how-to-submit-a-token-logo/3863

**Comment by MizzWasTaken** [comment]
> Hello, Please follow the rules for adding token, your logo should be a full screen, 256x256. Example: https://community.trustwallet.com/t/how-to-submit-a-token-logo/3863

how do i change the file? sorry i thought i uploaded in 256x256
here is the logo in the correct dimentions
logo256x256
ns

**Pull request merged**
