### PR TITLE
Add token $TORPEDO

### PR DESCRIPTION
**Pull request by torpedoteam**

### CODE REVIEW

**Comment by catenocrypt** [comment]
Corrections needed:
- Remove second png file, only `logo.png` should stay
- Explorer URL should be https://bscscan.com/token/0xaf169e53e9f07de6f9f4eac67e2833c623f0c122
❌  Contract is not in checksum format, should be 0xAF169E53e9f07DE6F9F4Eac67e2833C623f0c122 (not 0xaf169e53e9f07de6f9f4eac67e2833c623f0c122). Please rename it. You may need to rename to a temp name first, then to the checksum format, because lowercase-uppercase-only renames are often ignored by the Git client or the filesystem.

**Comment by torpedoteam** [comment]
https://github.com/torpedoteam/assets/pull/2

**Comment by catenocrypt** [comment]
Correction needed: Of the 5 files, only 2 are needed, the info+logo in the checksum-format folder.  Please remove the other 3 files.

image

**Comment by torpedoteam** [comment]
Hey, what is the error? the 3 files which you asked us to remove have been already deleted.

**Comment by torpedoteam** [comment]
done :)

**Comment by torpedoteam** [comment]
we have just fixed it :)
now?

**Comment by torpedoteam** [comment]
?

**Comment by torpedoteam** [comment]
Hey,
there is a problem: the price in TrustWallet is not correct.
you should notice that 30% of the total supply is burnt: https://bscscan.com/token/0xaf169e53e9f07de6f9f4eac67e2833c623f0c122#balances

**Comment by torpedoteam** [comment]
?

**Pull request merged**
