### PR TITLE
Pleas add HPSv2

### PR DESCRIPTION
**Pull request by HPSOfficial**
We will wait. Thanks team

### CODE REVIEW

**Comment by HPSOfficial** [comment]
> 

logo

**Comment by Cryptocool1** [comment]
Please create new PR, follow doc https://developer.trustwallet.com/assets/requirements
You may want to try our Assets app in beta; go to https://assets.trustwallet.com, log on with Github, enter contract ID, logo and some additional info, and it will create a PR for you.
See https://developer.trustwallet.com/assets/repository_details

**Comment by Cryptocool1** [comment]
make sure to mention this PR so the fee can be reused

**Comment by HPSOfficial** [comment]
> make sure to mention this PR so the fee can be reused

Hello I will make a new one?

**Comment by Cryptocool1** [comment]
hello, you need to create new PR following the documentation

**Comment by HPSOfficial** [comment]
> hello, you need to create new PR following the documentation

how to create new PR?

**Comment by HPSOfficial** [comment]
> hello, you need to create new PR following the documentation

only the logo is missing I think

**Comment by Cryptocool1** [comment]
I've sent you the instructions above

**Comment by HPSOfficial** [comment]
> I've sent you the instructions above. please see

OK thanks I will ask if I dont get it later.

**Comment by HPSOfficial** [comment]
> I've sent you the instructions above. please see

Can you delete the HPS logo of the old one?

people to get confuse of our token. Thank you

**Comment by cryptomanz1** [comment]
we have already deleted

**Comment by HPSOfficial** [comment]
> we have already deleted

Thank you, how about the price reflection is it working now? or wait 24hours?

**Comment by HPSOfficial** [comment]
> we have already deleted

Hello, we still saw the old HPS logo showing on my trust wallet.
Can we remove it? Please

This is the contract address:
0xeDa21B525Ac789EaB1a08ef2404dd8505FfB973D

Thank you team
photo_2022-09-14_19-24-51

**Pull request closed without merging**
