### PR TITLE
Add NEWINU ETH logo and info

### PR DESCRIPTION
**Pull request by imnotsosmart**
Token information

### CODE REVIEW

**Comment by imnotsosmart** [comment]
Anything wrong? Can you confirm me i don't have any error ?

**Comment by imnotsosmart** [comment]
Orf let's hope i didn't fucked up.

**Comment by Cryptocool1** [comment]
you need to add "{" in the first line.
please create new PR

**Comment by imnotsosmart** [comment]
So i just lost 3BNB ?

**Comment by Cryptocool1** [comment]
> So i just lost 3BNB ?

No)

**Comment by Cryptocool1** [comment]
Just mention this PR in your new PR. You don’t need to pay one more time

**Pull request closed without merging**
