### PR TITLE
Add Big Amber Stone (BEP20)

### PR DESCRIPTION
**Pull request by freeffect**
Adding info for BEP20 token 'Big Amber Stone'.

PR created by <a href="https://assets.trustwallet.com">TW Assets Management</a>

### CODE REVIEW

**Comment by Cryptocool1** [comment]
#20619 PAID

**Comment by Cryptocool1** [comment]
• What is the purpose of this token? How will it benefit Trust Wallet users?
 • How is the token being distributed? Are you conducting an airdrop?
 • Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?
 • Is the token listed on a centralized/decentralized exchange?
 • Is a Smart Contract audit completed? Where can we find this information?

**Comment by freeffect** [comment]
• What is the purpose of this token? How will it benefit Trust Wallet users?
The token is used widely in our game. The game exists more than 2 years. Our users ask us to add logo to TW app.
• How is the token being distributed? Are you conducting an airdrop?
Distribute by PVE and PVP in game, and pubsale.
• Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?
We sold the tokens in public sale in a little. Mostly in game.
• Is the token listed on a centralized/decentralized exchange?
   Yes, in DEX like pancakeswap.
• Is a Smart Contract audit completed? Where can we find this information?
   It is not audited yet.

**Comment by Cryptocool1** [comment]
We require smart contract audit from reputable companies. Feel free to come back to us once audit is done.

**Comment by freeffect** [comment]
Can you recommend a few audit companies? Thanks.

**Comment by Cryptocool1** [comment]
Sure, you can do Certik, Hacken, Techrate or Dessert Finance

**Comment by freeffect** [comment]
hello, @Cryptocool1  The BAS audit report is here. [https://world.dracoomaster.com/docs/tokenAudit](url)

**Comment by freeffect** [comment]
> I don't see your token in audited list on Techrate's website.

Please refer to https://techrate.org/. BAS token has been listed on Techrate's website.

**Pull request merged**
