### PR TITLE
Rebranding & Update new logo BHO (BEP20)

### PR DESCRIPTION
**Pull request by naviocean**
Hello,
We've just rebrand from Bholdus to BHO Network and also updated a new logo. Please review and accept our request.
Thanks

### CODE REVIEW

**Comment by naviocean** [comment]
@cryptomanz, We've made the previous payment, plz check at https://github.com/trustwallet/assets/pull/13894

**Comment by Cryptocool1** [comment]
hello, the fee is required for updating

**Comment by naviocean** [comment]
@Cryptocool1 the fee is paid, plz process soon.

**Comment by Cryptocool1** [comment]
can you please add tags?

**Comment by naviocean** [comment]
@Cryptocool1 I've added tags as you request.

**Pull request merged**
